### ISSUE TITLE
New Dashboards are always linked to the auto generated standard board

### ISSUE THREAD

**Issue by mrnukem** [home-assistant/frontend#10008]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I set up a new Dashboard in Lovelace with a unique URL and name it is always referenced to the existing standard  dashboard where all new entities are automatically integrated.
This happens with every new Dashboard, no matter how many where created.

### Describe the behavior you expected

A new Dashboard with a unique URL is empty.

### Steps to reproduce the issue

1.Open preferences
2.Lovelace Dashboard
3.new dashboard
4. Fill in the forms a name and then create
5. A New Dashboard exists in the menu with the exact content of the auto generated dashboard
...

### What version of Home Assistant Core has the issue?

core-2021.9.5

### In which browser are you experiencing the issue with?

Firefox and Android App

### Which operating system are you using to run this browser?

Ubuntu Linux 20.04, Android 11

**Comment by spacegaier** [comment]
I don't think this is a bug, but rather the designed behavior. You can then take ownership of the newly generated dashboard and you get asked whether you want to keep its content or completely clear it and add the elements you want on your own.

**Comment by mrnukem** [comment]
Thank you! You're right! I think, this is a confusing behaviour. In my opinion a new Dashboard should be completely empty. Otherwise I could dublicate the auto configured one.
