### ISSUE TITLE
Cache issue when using icons from custom frontend integrations

### ISSUE THREAD

**Issue by bcutter** [home-assistant/frontend#10011]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Icons from e. g.
- https://github.com/elax46/custom-brand-icons or
- https://github.com/hulkhaugen/hass-bha-icons

are not showing up correctly (not at all) for example when being used as title icon for a view.

After leaving gui edit mode it´s visible temporarily, once browser is refreshed it´s gone.

See https://github.com/elax46/custom-brand-icons/issues/39 (issue originally raised there but it´s NOT specific to that custom frontend integration).

Feels like a Core frontend issue cause I tested several browsers/apps on all available platforms (Browser, Android and iOS HA Companion App).

### Describe the behavior you expected

Set a custom frontend integration provided icon (e. g. "phu:apple-iphone" or "bha:nas") as new title icon for an existing view. New icon should be visible now.

### Steps to reproduce the issue

1. Set a custom frontend integration provided icon as new title icon for an existing view.
2. Reload browser / delete browser cache / start new private browsing tab / reset Frontend Cache (iOS)

### What version of Home Assistant Core has the issue?

core-2021.9.5

### In which browser are you experiencing the issue with?

Firefox 92.0 and all included in latest iOS & Android HA Companion App

**Comment by arallsopp** [comment]
Have you tried adding a reference via configuration.yaml, saving and restarting HA:

frontend:
  extra_module_url:
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js

(That was lifted from my front end repo arallsopp/hass-hue-icons, where I think this issue has been solved. Tweak to suit your needs).

**Comment by bcutter** [comment]
That "fixed" it for me after a quick test. Snippet in frontend section of configuration.yaml seems to be absolutely necessary.
Should have read the install instructions correctly, really thought HACS installation is enough (HACS takes care of all necessary steps).
