### ISSUE TITLE
The Color of the lamp on Love Lace UI is not correct

### ISSUE THREAD

**Issue by brunomgsousa** [home-assistant/frontend#10023]
### The problem

When i change the color of the lamp from cool white to warm white, in love lace the color is now between rose and orange, but the correct would be between blue and orange,

please see the images https://www.dropbox.com/sh/wnpue1hkf59afyl/AAAGya4FBQdD72pbTv-n8r-4a?dl=0

### What is version of Home Assistant Core has the issue?

9.6

### What was the last working version of Home Assistant Core?

8.4

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Tuya Lamps zigbee with Sonoff Tasmota ZBridge
Ikea Lamps Zigbee with Sonoff Tasmota ZbBridge

### Anything in the logs that might be useful for us?

No

### Additional information

images: https://www.dropbox.com/sh/wnpue1hkf59afyl/AAAGya4FBQdD72pbTv-n8r-4a?dl=0

**Comment by spacegaier** [comment]
Please post the entity state info of your light in the issue.

**Comment by joe-sydney** [comment]
I also experience similar issues when upgrading to 2021.9.7. You can see the color representations of the (same) light in warm and cool white modes (attached images).

When the light is in maximum cool white mode, you can't actually see the icon anymore :(

The state attributes of the light in warm and cool white modes are copied below.

Warm white:
min_mireds: 153
max_mireds: 500
supported_color_modes:
  - color_temp
color_mode: color_temp
brightness: 255
color_temp: 500
hs_color:
  - 30.601
  - 94.547
rgb_color:
  - 255
  - 136
  - 13
xy_color:
  - 0.599
  - 0.382

Cool white:
min_mireds: 153
max_mireds: 500
supported_color_modes:
  - color_temp
color_mode: color_temp
brightness: 255
color_temp: 153
hs_color:
  - 54.768
  - 1.6
rgb_color:
  - 255
  - 254
  - 250
xy_color:
  - 0.326
  - 0.333
![ww](https://user-images.githubusercontent.com/74637159/135555605-a8e8045b-6fec-425e-8472-fe2b5d1af34e.jpg)

![cw](https://user-images.githubusercontent.com/74637159/135555633-2c7ebd69-c72d-4b40-84d4-325b5cda5218.JPG)

**Comment by brunomgsousa** [comment]
But I have the problem yet.... 😓

**Comment by emontnemery** [comment]
The color band in the slider is fixed, the color of the lamp icon is a best-effort approximation of the light's actual color.

Hence, the icon is more correct than the color band in the slider, but the color band in the slider could perhaps be drawn according to the light's `min_mired` and `max_mired` attributes.

![image](https://user-images.githubusercontent.com/14281572/148072782-bb1641ba-d452-4a71-85d2-6c2a91b56f6d.png)

**Comment by emontnemery** [comment]
Closing this; the UI does not adjust the color temperature slider according to the light's colour temperature range.
A PR implementing it would be welcome 👍
