### ISSUE TITLE
Area created during new device configuration is not selected by default

### ISSUE THREAD

**Issue by thecode** [home-assistant/frontend#10038]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating a new area while adding a new device the new area is not selected by default so that you have to open the drop down menu again and select it, this is not user intuitive, I am not sure if it was always like this or changed but would better to check:
Create new area:
![image](https://user-images.githubusercontent.com/1858925/133421081-c3d399db-0b37-4423-8fa5-cf462a19be18.png)
![image](https://user-images.githubusercontent.com/1858925/133421179-a17058af-63d8-4657-959d-af674712d356.png)
After area is created it is not selected:
![image](https://user-images.githubusercontent.com/1858925/133421282-9a73c8f9-ed77-41c1-9738-a2c99dc67f70.png)
![image](https://user-images.githubusercontent.com/1858925/133421366-2857de49-d39e-415e-b270-7e9d08f5ff0f.png)

### Describe the behavior you expected

When creating a new area while adding a new device the area should be selected by default

### Steps to reproduce the issue

1. Add new device
2. Create an area
3. Area is not selected after it is created

### What version of Home Assistant Core has the issue?

core-2021.10.0.dev0

### In which browser are you experiencing the issue with?

Google Chrome 93.0.4577.63

### Which operating system are you using to run this browser?

Windows 10

**Comment by thecode** [comment]
@spacegaier FYI

**Comment by spacegaier** [comment]
I was able to verify that the `ha-area-picker` initially returns the correct area ID of the newly created area, but directly afterwards something gets cleared inside that component resulting in another `_setValue`()` call but with an empty value that is then passed along to the calling component (e.g. `dialog-device-registry-detail` in my tests, but the same also applies to the device creation dialog that OP reported the issue for).

**Comment by thecode** [comment]
@spacegaier seeing this reminder from stale bot, I checked it again and could not reproduce it now, however I did not find any commit which may explain a change, can you also validate it before I close the issue? Thanks

**Comment by spacegaier** [comment]
I can confirm that this seems indeed to be fixed.
