### ISSUE TITLE
Comments not saved in picture elements card config. 

### ISSUE THREAD

**Issue by mrcmc** [home-assistant/frontend#10034]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When generating a new picture elements card with code editor view any comments added with # are not saved when you return to edit later.

### Describe the behavior you expected

Comments  to code  added with # should stay in place after saving and exiting the card configuration for future reference when editing. 

### Steps to reproduce the issue

1.Create a new picture elements card in Lovelace.
2.Use code view to edit and add a comment using # .
3. Make sure it is identified and turns grey.
4. Click save.
5. Click edit to change the card.
6. Click show code editor.
7. Note that you comment is now gone. 

### What version of Home Assistant Core has the issue?

 Core 2021.9.6

### In which browser are you experiencing the issue with?

Chrome 90.4430.93 and edge 93.0.961.47

### Which operating system are you using to run this browser?

Win 10 enterprise 20h2

### Problem-relevant frontend configuration

```yaml
Any comment starting with #
```

**Comment by spacegaier** [comment]
Not possible, see answer to this duplicate: https://github.com/home-assistant/frontend/issues/8203
