### ISSUE TITLE
Error in shapes created in yaml in picture elements

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#10036]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![Picture Elements](https://user-images.githubusercontent.com/74879713/133338507-aa02b75f-66d7-401d-8a48-ea596e4e6ada.PNG)

### Describe the behavior you expected

The following code generates a black rectangular shape with rounded corners

  - style:
      transform: translate(0%, 0%)
      top: 71.2%
      left: 20.0%
      right: 61.9%
      bottom: 16.4%
      color: rgb(0, 0, 0, 0)
      background-color: rgba(0, 0, 0, 1)
      border-radius: 5px

is it a problem with my code? In that case how should I correct?

### Steps to reproduce the issue

1. 
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.9.6

### What was the last working version of Home Assistant Core?

core-2021.8.0

### In which browser are you experiencing the issue with?

Firefox, Chrome, Android app

### Which operating system are you using to run this browser?

Windows 10, Android

**Comment by spacegaier** [comment]
It's unclear to me what the bug is supposed to be here. Can you please clarify?

**Comment by WRoss7** [comment]
Playing with the yaml syntax in a picture elements card I discovered that inserting the above code under "elements:" produces a rectangle with the set characteristics, and that I can use to highlight multiple elements such as an icon next to a state-label.
It will not be the correct way, but I have not found any other method to draw semi-transparent or opaque shapes to overlap elements.
As mentioned, this error (the exclamation point drawn in a circle) did not appear in the previous release.
If this is not a bug, as I suspect, is there another way to get the same result that I haven't found?

**Comment by WRoss7** [comment]
Please does anyone know a method to draw a geometric shape: a rectangle (possibly with the possibility of setting color, transparency, and corner radius) in a picture elements card? I haven't found it.

For example it would be very useful to highlight different elements

![Immagine](https://user-images.githubusercontent.com/74879713/140317057-2ce916df-f8cf-487c-957f-6795b1a3df09.png)

**Comment by bramkragten** [comment]
You could use?

```yaml
elements:
  - type: image
    style:
      transform: translate(0%, 0%)
      top: 71.2%
      right: 61.9%
      height: 25px
      width: 100px
      background-color: rgba(0, 0, 0, 1)
      border-radius: 5px
```

**Comment by WRoss7** [comment]
@bramkragten

If I increase the height of the image, the loading circle appears

![Image](https://user-images.githubusercontent.com/74879713/152429932-6879ebc9-4c65-4333-b9c2-b88162f0594e.png)

How can I avoid it?

**Comment by bramkragten** [comment]
Then you should create a custom element. But github is not for support, try discord.

**Comment by WRoss7** [comment]
My English is bad for Discord.
Can you tell me where I can look for custom element? Thank you

**Comment by bramkragten** [comment]
Or use a transparent image in the config I gave you.

Info about custom components can be found in the dev docs.

https://developers.home-assistant.io/docs/frontend/custom-ui/lovelace-custom-card

**Comment by WRoss7** [comment]
> Or use a transparent image in the config I gave you.

I don't understand, do you mean that?

elements:
  - type: image
    style:
      transform: translate(0%, 0%)
      top: 71.2%
      right: 61.9%
      height: 25px
      width: 100px
      background-color: rgba(0, 0, 0, 0)
      border-radius: 5px
