### ISSUE TITLE
history-graph not showing the *current* name of a recently renamed entity

### ISSUE THREAD

**Issue by ahd71** [home-assistant/frontend#10030]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If renaming an entity and showing a history-graph it seems the entity name shown is picked from the first data point (I can easily see that it changes the name if I change the interval from 24h to 1h where the name change was somewhere in between)

### Describe the behavior you expected

Best would be to show the CURRENT name of the entity, regardless of the history, but second best would be to show the name from the LAST data point instead of the first data point I guess.

### Steps to reproduce the issue

1. Any entity ID with name "A"
2. Make sure it has some state changes to show up in the history-graph
3. Rename the entity from "A" to "B"
4. Make sure it has some additional state changes.
4. Observe the name is still showing "A" in history-graph (given that it is recently renamed within the time span of history-graph)
5. Reduce the time span for history-graph to a value lower than when the rename was done
6. Observe the name changes to "B"
...

### What version of Home Assistant Core has the issue?

2021.9.6

### In which browser are you experiencing the issue with?

Google Chrome Version 93.0.4577.63 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

**Comment by spacegaier** [comment]
I am pretty sure that data is coming like this from the backend and the frontend is just rendering it.

**Comment by ahd71** [comment]
Is there a way to confirm that? And if so transfer the issue to someone else that handles the backend?

**Comment by spacegaier** [comment]
> 
> 
> Is there a way to confirm that? And if so transfer the issue to someone else that handles the backend?

You can verify that by looking at the network data in your browser dev tools (F12). There will be a request to retrieve the historic data from the backend.

**Comment by ildar170975** [comment]
2021.12.10 - the issue is present
