### ISSUE TITLE
Change icon binary sensors window

### ISSUE THREAD

**Issue by pepsonEL** [home-assistant/frontend#10042]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi. In europe we have more windows as on icon name:
mdi:window-open-variant oraz mdi:window-closed-variant

Is any chance to add other device_class for this type windows ? Many user need it... of course we can create next template but it is no good solution because we have more entity... because we have binarysensors and then binarry sensor from template.... Is any solution for it to use this icon for open and close window ?

### Describe the behavior you expected

Hi. In europe we have more windows as on icon name:
mdi:window-open-variant oraz mdi:window-closed-variant

Is any chance to add other device_class for this type windows ? Many user need it... of course we can create next template but it is no good solution because we have more entity... because we have binarysensors and then binarry sensor from template.... Is any solution for it to use this icon for open and close window ?

### Steps to reproduce the issue

Hi. In europe we have more windows as on icon name:
mdi:window-open-variant oraz mdi:window-closed-variant

Is any chance to add other device_class for this type windows ? Many user need it... of course we can create next template but it is no good solution because we have more entity... because we have binarysensors and then binarry sensor from template.... Is any solution for it to use this icon for open and close window ?

### What version of Home Assistant Core has the issue?

2021.9.6

**Comment by spacegaier** [comment]
Not a bug, so please create a feature request / discussion. However, if you advocate for additional `device_class` values, those require an architecture ticket for approval: https://github.com/home-assistant/architecture
