### ISSUE TITLE
filter on attributes in dev tools state not exact

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#10041]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

filtering for 'current: 1' tp foind automations with that attribute also show climate entity with attribute 'current_temperature: 19', or cover entities with 'current_position: 100'

### Describe the behavior you expected

filter the exact phrase

### Steps to reproduce the issue

1. entier the above in attributes filter
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.9.x

### What was the last working version of Home Assistant Core?

not sure

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

Big sur 11.4

### State of relevant entities

or

<img width="776" alt="Schermafbeelding 2021-09-16 om 08 48 53" src="https://user-images.githubusercontent.com/33354141/133563743-319bf6b9-44f9-426c-95b3-d081a50363dc.png">

### Javascript errors shown in your browser console/inspector

None

### Additional information

<img width="238" alt="Schermafbeelding 2021-09-16 om 08 47 44" src="https://user-images.githubusercontent.com/33354141/133563610-d1ca588e-ab39-4ac0-863a-0820b96923fe.png">

**Comment by spacegaier** [comment]
That is working as designed in https://github.com/home-assistant/frontend/pull/9288

The colon ":" makes it a key/value search: Meaning what comes before the colon is searched of in the attribute name, where as after the colon is for the attribute value.

Might be worth mentioning that in the docs though...

**Comment by Mariusthvdb** [comment]
tbh, this feels like a bug. #9288 is about wildcard search.

even though it is explainable, doesn't mean it is desirable to have the frontend return anything 'including' the search term, where one expected it to find  'exactly' the search term.

especially since there is no other way?

Expected would be:
- if one needs a wildcard: enter a wildcard, like in the entity column. 
- No wildcard entered: find the exact search term

**Comment by spacegaier** [comment]
The entity column also uses an implicit wildcard, and is not doing an exact match.
![image](https://user-images.githubusercontent.com/114137/133615076-46c9f79c-0344-4c1e-ba71-71e3b86f9d84.png)

**Comment by Mariusthvdb** [comment]
Yes but that search phrase is exactly in both returned items. In the attributes search it was merely a section of the returned items. 

It is probably caused by the : which I need to be part of the searched string instead of being an indicator of text search technique.

'current: 1' as full search string

**Comment by spacegaier** [comment]
I understand that you would prefer a different behavior but it is working as expected, and (I just checked) the logic with the colon separator was in there long before we switched to the wildcard search, so that is nothing new.

You could open a FR, but I don't think that there is a high chance that the logic gets changed. I personally vote for keeping the current logic, because I see no reason for breaking the existing behavior for the rare edge case where you actually want to search for a colon. Adding escaping options for it seems overkill to me.

**Comment by Mariusthvdb** [comment]
right. appreciate your well worded comments. I won't persist ;-)

though escaping the colon would be a nice option...
thanks Philip!
