### ISSUE TITLE
Translation Error: The intl string context variable "naam" was not provided to the string "Back-up maken van {naam}"

### ISSUE THREAD

**Issue by ronaldvdmeer** [home-assistant/frontend#10069]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

For the last 3+ updates just before upgrading home-assistant to the latest version I get the following pop-up.

`Translation Error: The intl string context variable "naam" was not provided to the string "Back-up maken van {naam}"`

### Describe the behavior you expected

No popup about missing string.

### Steps to reproduce the issue

1. Open home-assistant
2. Goto `supervisor`
3. Update to latest version

## System Health

version | core-2021.9.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.61
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4922
Installed Version | 1.15.2
Stage | running
Available Repositories | 880
Installed Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 28 september 2021 2:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.3
-- | --
update_channel | stable
supervisor_version | supervisor-2021.09.0
docker_version | 20.10.7
disk_total | 30.8 GB
disk_used | 10.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Visual Studio Code (3.6.2), Terminal & SSH (9.1.3), Mosquitto broker (6.0.1), Z-Wave JS (0.1.37), InfluxDB (4.2.1), Grafana (7.2.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 1
views | 9
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### What version of Home Assistant Core has the issue?

Last few

### What was the last working version of Home Assistant Core?

Not entirely sure. I think since something changed to the back-up or updating system

### In which browser are you experiencing the issue with?

All browsers

### Which operating system are you using to run this browser?

macOS Big Sir 11.6

**Comment by frenck** [comment]
This has been fixed in our translations on the 6th of this month and will be part of the next release.
