### ISSUE TITLE
Motion Detector Colors Inverted - Is this the answer?

### ISSUE THREAD

**Issue by g2InTheDesert** [home-assistant/frontend#10078]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I’m new to HA and noticed that motion detector colors are inverted (green = motion, red = safe) in history.

### Describe the behavior you expected

No motion should be green, motion should be red

### Steps to reproduce the issue

1. View any motion detector history panel

### What version of Home Assistant Core has the issue?

core-2021.9.7

### In which browser are you experiencing the issue with?

Safari Version 14.1.2

### Which operating system are you using to run this browser?

Macos 11.5.2

### State of relevant entities

```txt
Not relevant.  It is not valid to invert the sensor because that displays that motion is detected. Green color, but erroneous state.
```

### Additional information

I looked at the source (current as of September 22, 2021) and could this be an easy fix?
File frontend-dev/src/components/chart/state-history-chart-timeline.ts :
Line 18 has a set variable

Copy to clipboard
```
BINARY_SENSOR_DEVICE_CLASS_COLOR_INVERTED
```
It has things like door and window in the set. Can

Copy to clipboard
```
"motion",
```
simply be added at line 24 to correct the issue?

**Comment by matthiasdebaat** [comment]
It depends how you interpreted motion. From HA perspective, motion = active and active = green.  Why do you think it should be inverted?

**Comment by g2InTheDesert** [comment]
Matthias,

Motion is active in the literal sense.  Visually, green is good, red is alert, just as the visual cue of a stop light.  Using the same cue, smoke, co2, etc. are green if none is detected or inactive, red if detected.

**Comment by matthiasdebaat** [comment]
I don't have strong opinion about this. @bramkragten what do you think?

**Comment by g2InTheDesert** [comment]
Instead of the metaphor I used earlier, here is a concrete example of my reasoning. A quick glance at the history panel should show what needs attention.

Below, a window is ‘Open’ continually through the time-span which may mean it requires attention.  The three motion sensors should indicate attention is needs very intermittently through the time span, not through almost all of the  time period.

**Comment by g2InTheDesert** [comment]
Thanks for looking at this.  

Instead of the metaphor I used earlier, here is a concrete example of my reasoning. A quick glance at the history panel should show what needs attention.

Below, a window is ‘Open’ continually through the time-span which may mean it requires attention.  The three motion sensors should indicate attention is needs very intermittently through the time span, not through almost all of the  time period.

<img width="978" alt="Screen Shot 2021-09-29 at 8 35 43 AM" src="https://user-images.githubusercontent.com/17831633/135293198-83d005fd-612e-45ce-a0c8-376311c278bb.png">

**Comment by matthiasdebaat** [comment]
Thanks for your example. I agree, I think it should be inverted. This is a typical Hacktoberfest issue and I've added the tag.

**Comment by aav7fl** [comment]
I'd like to take a look at fixing this for Hacktoberfest. I'll try to get a PR out today for it.

**Comment by aav7fl** [comment]
Adding the motion class to the list of charts was indeed correct.

<img width="1218" alt="chrome_2021-10-01_12-11-25" src="https://user-images.githubusercontent.com/3487107/135654540-045f3cde-787a-4973-8aaf-6e3a65562ee2.png">

PR: https://github.com/home-assistant/frontend/pull/10128
