### ISSUE TITLE
Dialog to move a card to another Lovelace dashboard has an inconstant button

### ISSUE THREAD

**Issue by matthiasdebaat** [home-assistant/frontend#10083]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When you want to move a card to another Lovelace dashboard you get the following dialog:
<img width="485" alt="Schermafbeelding 2021-09-23 om 15 26 10" src="https://user-images.githubusercontent.com/20203284/134515689-08b38327-8c04-45fe-a651-8b04c6c41f0d.png">

The button below changes to the same name as in the dropdown.

### Describe the behavior you expected

I expected two buttons: 'Cancel' and 'Move' instead of the dashboard name.

### Steps to reproduce the issue

1. Edit a dasboard
2. Hit the three dots menu of a card and select `Move to view`

### What version of Home Assistant Core has the issue?

core-2021.9.6

**Comment by MartinTuroci** [comment]
Hi @matthiasdebaat , may I take this one? :)

**Comment by spacegaier** [comment]
> 
> 
> Hi @matthiasdebaat , may I take this one? :)

I assigned the issue to you. Please keep us posted. If something comes in the way and you are not able to tackle it after all, let us know as well, so that others can have a go then. Thanks.

**Comment by MartinTuroci** [comment]
Thanks @spacegaier. I am almost there I believe. I added a new dropdown to be able to pick the desired view to move to - see pic below:

![image](https://user-images.githubusercontent.com/44962077/136057683-c27f81a7-1b80-4cfa-842d-6c9965ae9976.png)

Does this make sense from bussiness logic perspective? Any other ideas?

**Comment by spacegaier** [comment]
I think that makes sense. It would be nice to also show the icon of the the target view (both in the dropdown menu list as well as for the selected dropdown item).

@matthiasdebaat As we now have dedicated buttons, should the X button in the top right corner be removed? Also should this dialog be modal or not?

**Comment by MartinTuroci** [comment]
> It would be nice to also show the icon of the the target view (both in the dropdown menu list as well as for the selected dropdown item).

Np, what should be the default icon for views that don't have it specified?

**Comment by spacegaier** [comment]
I'd say stick to the behavior of the current UI (the long list of views). If it shows a default icon keep that, otherwise do not render an icon if none is specified.

**Comment by matthiasdebaat** [comment]
> @matthiasdebaat As we now have dedicated buttons, should the X button in the top right corner be removed? Also should this dialog be modal or not?

Good question, we're not consistent with using the 'X' button. I've looked it up and it should be like this:

- Is it an alert or question? Than there are only buttons and no `X` button.
- Is it a form with multiple inputs than it should have an `X`. We follow [Material Design](https://www.material.io/components/dialogs) in this, only we don't make it fullscreen on mobile.
