### ISSUE TITLE
Spelling error in UI

### ISSUE THREAD

**Issue by salsaman** [home-assistant/frontend#10085]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Spelling error in UI: "Automation Conig"

### Describe the behavior you expected

The text should read "Automation Config"

### Steps to reproduce the issue

1. In the UI, click on Configuration - Automations
2. Select an automation and edit it
3. Click on SHOW TRACE
4. Note the spelling error in the tabs in the upper part of the page
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.9.7

### What was the last working version of Home Assistant Core?

N/A

### In which browser are you experiencing the issue with?

N/A

### Which operating system are you using to run this browser?

N/A

**Comment by spacegaier** [comment]
Looks fine to me (running 2021.9.6) and there was no change of that string in the frontend in the last 6 months.

![image](https://user-images.githubusercontent.com/114137/134653801-1023be45-0ae1-4698-abe6-fb93848ff67b.png)

Can you try in private browsing mode to rule out caching issues?

**Comment by salsaman** [comment]
My apologies, yes it is correct, the font was very tiny causing me to misread the label.
