### ISSUE TITLE
youless sensor.power_total gives error in energy dashboard

### ISSUE THREAD

**Issue by TheSilverTech** [home-assistant/frontend#10096]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

when i choose the sensor.power_total of the youless ls110 in the energy dashboard it gives an error: 
Entity has non-numeric state The following entities have a state that cannot be parsed as a number: 
sensor.power_total (6711,136)

i dont understand why this is happening because the entity has a number

### Describe the behavior you expected

the sensor.power_total is in the dropdown on the energy dashboard so i expected that i can use it

### Steps to reproduce the issue

1.install youless integration
2.choose the sensor.power_total in the energy dashboard
3.
...

### What version of Home Assistant Core has the issue?

core-2021.9.7

### In which browser are you experiencing the issue with?

all

### Which operating system are you using to run this browser?

windows 10 19043.1237

### Additional information

![solar](https://user-images.githubusercontent.com/69034804/135068966-8fd1ac0d-b450-4a94-8c3e-67013f67103e.jpg)

**Comment by spacegaier** [comment]
Please post the complete state of the entity (from the HA dev tools).

**Comment by TheSilverTech** [comment]
![Screenshot_20210930-143629](https://user-images.githubusercontent.com/69034804/135456481-2b675af3-ad42-4faa-a83b-6bc1565b5e4d.jpg)

**Comment by TheSilverTech** [comment]
is this what you meant?

**Comment by TheSilverTech** [comment]
hello, if i add the sensor as a utilitymeter in configuration.yaml it works

**Comment by spacegaier** [comment]
Sorry, I had missed your replies. That is indeed the entity state I was referring to, although ideally not a screenshot, but as a copy-able text.

Either way, if you change the comma "," in the value to dot "." => does it work then? Backend integrations should provide the values with a ".". The frontend might then render it as a comma depending on the user selected number format.
