### ISSUE TITLE
Cursor keeps jumping around on mobile iOS/Safari when trying to edit addon configuration

### ISSUE THREAD

**Issue by WhatMeansGithub** [home-assistant/frontend#10102]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On iOS (iPhone), whether I'm using the app or the browser I can't edit addon configurations because the cursor keeps jumping around to the top. This happens when typing, pasting and deleting text. 

### Describe the behavior you expected

have the cursor remain where I placed it and not jump away to top when I start typing.

### Steps to reproduce the issue

[Here's a gif that shows the issue much clearer than I can explain it.](https://imgur.com/a/xHsmXSf)

### What version of Home Assistant Core has the issue?

core-2021.9.7

### In which browser are you experiencing the issue with?

Safari iOS

### Which operating system are you using to run this browser?

iOS 15

**Comment by bpottle1** [comment]
I have the same issue. It happens in any editor for cards in Lovelace or the raw configuration editor too. The only places it doesn’t happen that I have seen are in the File Editor addon when editing a config file or in the ESPHome addon when using the editor in there to edit a node config file.

**Comment by Final-Hawk** [comment]
Same issue as well. Very frustrating when it happens

**Comment by loeffelpan** [comment]
Same here.
Happens in Safari as well as in the iOS/iPasOS App.

**Comment by vandad51** [comment]
Glad I found other people having this same issue. This problem just started happening to me about a week ago. Happens in app and on Safari on iOS. 
HASSOS 2021.11.4 in a Linux VBox
Supervisor 2021.10.8

VERY irritating.

**Comment by juekr** [comment]
Same here. Cursor almost always jumps to the beginning of the text input field. Happens after each character I type. Completely unusable. Happens in Brave, Safari and the Home Assistant app on iPad Pro (2021).

**Comment by ElVit** [comment]
I have also this problem. 
But only in the addon configuration. 

When I'm editing a Lovelace card in the code editor then the cursor is not jumping anymore.

**Comment by loeffelpan** [comment]
Fixed since 2021.12. Can be closed.
