### ISSUE TITLE
Cannot Set Action Name for Script in Entities Card

### ISSUE THREAD

**Issue by EnochPrime** [home-assistant/frontend#10100]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When attempting to change the button name for a script in the `entites` card using the `action_name` variable I receive multiple configuration errors.

### Describe the behavior you expected

I expected to be able to provide only the entity id and a new action name and have the button name changed in the row.

### Steps to reproduce the issue

1. Create a script
2. Add an `entities` card to lovelace
3. Add the script created as a new entity row
4. Edit in YAML mode
5. Add `action_name` configuration

### What version of Home Assistant Core has the issue?

core-2021.9.7

### What was the last working version of Home Assistant Core?

core-2021.9.7

### In which browser are you experiencing the issue with?

Brave Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Linux Mint 20.2 Cinnamon

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - entity: script.change_light_switch_led_color
    action_name: 'Set'
```

### Javascript errors shown in your browser console/inspector

```txt
Configuration errors detected:
Required key "entities.0.type" is missing.
Required key "entities.0.tap_action" is missing.
Required key "entities.0.tap_action" is missing.
Required key "entities.0.tap_action" is missing.
Required key "entities.0.tap_action" is missing.
Required key "entities.0.tap_action" is missing.
Required key "entities.0.tap_action" is missing.
Required key "entities.0.type" is missing.
Required key "entities.0.view" is missing.
Required key "entities.0.view" is missing.
Required key "entities.0.view" is missing.
Required key "entities.0.type" is missing.
Required key "entities.0.conditions" is missing.
Required key "entities.0.type" is missing.
Required key "entities.0.type" is missing.
Required key "entities.0.type" is missing.
Required key "entities.0.url" is missing.
Required key "entities.0.type" is missing.
Required key "entities.0.entities" is missing.
Required key "entities.0.type" is missing.
Required key "entities.0.attribute" is missing.
Required key "entities.0.type" is missing.
Required key "entities.0.name" is missing.
Required key "entities.0.service" is missing.
Required key "entities.0.type" is missing.
Required key "entities.0.name" is missing.
Required key "entities.0.text" is missing.
Required key "entities.0.type" is missing.
Visual editor is not supported for this configuration:
Key "entities.0.action_name" is not expected or not supported by the visual editor.
The provided value for "entities.0" is not supported by the visual editor. We support (string) but received ({"entity":"script.change_light_switch_led_color","action_name":"Set"}).
Key "entities.0.entity" is not expected or not supported by the visual editor.
Key "entities.0.action_name" is not expected or not supported by the visual editor.
Key "entities.0.entity" is not expected or not supported by the visual editor.
Key "entities.0.action_name" is not expected or not supported by the visual editor.
Key "entities.0.entity" is not expected or not supported by the visual editor.
Key "entities.0.action_name" is not expected or not supported by the visual editor.
Key "entities.0.entity" is not expected or not supported by the visual editor.
Key "entities.0.action_name" is not expected or not supported by the visual editor.
Key "entities.0.entity" is not expected or not supported by the visual editor.
Key "entities.0.action_name" is not expected or not supported by the visual editor.
Key "entities.0.entity" is not expected or not supported by the visual editor.
Key "entities.0.action_name" is not expected or not supported by the visual editor.
Key "entities.0.action_name" is not expected or not supported by the visual editor.
Key "entities.0.entity" is not expected or not supported by the visual editor.
Key "entities.0.entity" is not expected or not supported by the visual editor.
Key "entities.0.action_name" is not expected or not supported by the visual editor.
You can still edit your config in YAML.
Change Switch Color
```

**Comment by spacegaier** [comment]
Yes, there were some issues in the validation logic of the editor, that I fixed a few weeks ago and will remove the incorrect (= false-positives) and redundant errors. Will be in the next release: https://github.com/home-assistant/frontend/pull/9962

However, it looks like your specific example is not handled correctly independently of that. Will push a PR for that.

**Comment by spacegaier** [comment]
@bramkragten Inside `entitiesConfigStruct` we have `string()` at the end. I think we can remove that, since if a users adds any arbitrary other YAML keys (e.g. for custom cards) we will allow that also without `string()` and show the correct warning, that it is not supported by the visual editor.

I also think we could add the key `action_name` to the allowed keys for the visual editor, even if we do not have a GUI field (but that is consistent with other fields that can only be set via YAML but still do not block the visual editor).

=> What do you think?

**Comment by spacegaier** [comment]
Update: It looks like we need the `string()` to e.g. allow a history graph card to directly specify entity IDs in `entities:`.

**Comment by EnochPrime** [comment]
I confirmed on 2021.10.1 that I can now use `action_name` to change the text, and get the warning about being unsupported for the visual editor.
