### ISSUE TITLE
Helpers: Options should be movable

### ISSUE THREAD

**Issue by matthiasdebaat** [home-assistant/frontend#10107]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

As described by @flemmingss in this [discussion](https://github.com/home-assistant/frontend/discussions/10106).

In the example I have 4 options, and i can't move "None" to be on the top above "Fast Colorloop".
This should be possible by drag-and-drop or by up/down arrows

![](https://user-images.githubusercontent.com/25674067/135401021-5ec09331-156d-4caa-96d7-f424660365fd.png)

### Describe the behavior you expected

Example of how it works in Lovelace (drag and drop):
![](https://user-images.githubusercontent.com/25674067/135401794-d57c44ee-077c-4357-a37c-0aeb3da17478.png)

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.9.7

**Comment by ChrisBit** [comment]
<img width="765" alt="Screenshot 2021-10-15 at 16 17 26" src="https://user-images.githubusercontent.com/6694377/137502714-f88918aa-5a8f-4d71-b851-a00445a2a32e.png">

I got it running and working locally. I just need to do some more QA and testing before opening a PR.

Do anyone have opinions about how it should look? I'm thinking maybe it should look more like the drag and drop for entities.
And if they should work and look the same, maybe the two components should be merged to reduce code duplicity?

**Comment by matthiasdebaat** [comment]
> <img alt="Screenshot 2021-10-15 at 16 17 26" width="765" src="https://user-images.githubusercontent.com/6694377/137502714-f88918aa-5a8f-4d71-b851-a00445a2a32e.png">
> @matthiasdebaat Do anyone have opinions about how it should look? I'm thinking maybe it should look more like the drag and drop for entities, for consistency. And if they should work and look the same, maybe the two components should be merged to reduce code duplicity?

I like what you did here! To make it consistent with the draggable Lovelace entities and for example the [grocery list](https://github.com/home-assistant/frontend/pull/9971#issuecomment-940466032) we need to remove the outer border. Though this isn't an improvement in my opinion. What do you think?

Could we also make the option into an input? This is a bit of a scope creep, but this makes it easier to edit an option.
