### ISSUE TITLE
Entities of single device cannot be controlled independently using scene editor

### ISSUE THREAD

**Issue by kongo09** [home-assistant/frontend#10101]
### The problem

The scene editor does not allow individual entities to be added to a scene when they belong to a device that provides more than one entity. The editor always adds all entities of the device, even if the user tries to add a single entity in the `Add Entity` dialog.

In the example below I only tried to put the first entity into the scene, not the second:

![image](https://user-images.githubusercontent.com/640121/135219450-52c84bfa-dd7b-49a4-a1a5-1ce8b19d4b4f.png)

As a result, certain scene configurations are impossible to control from the UI. It seems to be possible, however, to add individual entities from the `scenes.yaml` file by hand. That's why I consider this a bug.

### What is version of Home Assistant Core has the issue?

core-2021.9.7

### What was the last working version of Home Assistant Core?

never worked

### What type of installation are you running?

Home Assistant Supervised

### Integration causing the issue

scene

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/scene/

**Comment by kongo09** [comment]
Suggestion for a user-friendly solution consistent with the current interface would be:

- using `Add Device` adds the whole device like it is doing already, including all entities
- using `Add Entity` only adds the selected entity

Adding a device when the user explicitely asked to add an entity feels like a bug from the user perspective.

**Comment by kongo09** [comment]
Possibly related, though I consider this more a bug than a feature request:
https://github.com/home-assistant/frontend/issues/6468

**Comment by kongo09** [comment]
Looking at the code, I understand this behaviour has been introduced by purpose in PR https://github.com/home-assistant/frontend/pull/6343 by @bramkragten so there is probably some higher intention to this?

**Comment by emontnemery** [comment]
The intention is to make the scene editor device oriented, but it doesn't mean we should force a scene to actuate all devices.

Maybe something like this would work:
![image](https://user-images.githubusercontent.com/14281572/135246254-e31cf328-b699-44ee-9955-227f1d7c334b.png)

**Comment by kongo09** [comment]
Understood. However, while the scene editor is _not really_ device oriented just now, would a roll-back of the above mentioned code not solve the problem, or are there other things to consider? It could be re-introduced once the UI reflects the desired device orientation.

**Comment by emontnemery** [comment]
I think the UI is OK as is, but we should allow excluding entities of a device from a scene.
