### ISSUE TITLE
Energy panel axis labels incorrect

### ISSUE THREAD

**Issue by firstof9** [home-assistant/frontend#10124]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the latest beta the axis labels on the energy panel are wrong. The tooltips show the correct label however.

### Describe the behavior you expected

Correct axis labels.

### Steps to reproduce the issue

1. Open Energy Panel

### What version of Home Assistant Core has the issue?

core-2021.10.0b1

### What was the last working version of Home Assistant Core?

core-2021.9.7

### In which browser are you experiencing the issue with?

Brave Version 1.30.86 Chromium: 94.0.4606.61 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Win10

### State of relevant entities

```txt
n/a
```

### Problem-relevant frontend configuration

```yaml
n/a
```

### Javascript errors shown in your browser console/inspector

```txt
None
```

### Additional information

![image](https://user-images.githubusercontent.com/1105672/135642808-22a4b03a-dd86-4000-a4be-c7dfc247e917.png)

**Comment by Mariusthvdb** [comment]
can confirm as per discussion on Discord #beta https://discord.com/channels/330944238910963714/427516175237382144/893432126945525791

before the entities were listed on energy usage (as the bars, tooltips and more-info's still are), currently the entities are listed alphabetically
