### ISSUE TITLE
Home Assistant UI takes minutes to load in Firefox

### ISSUE THREAD

**Issue by DavidZidar** [home-assistant/frontend#10122]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

At first everything seems fine, but after loading HA and trying to load it again in a new tab a few hours later it takes a long time to load. I just tried it and timed it, it took almost 2 minutes before the spinner disappeared and the UI finally loaded.

Here are some things I've tried to resolve the issue that does not work:
* Reload the tab
* Ctrl+F5
* Clear cache
* Remove everything in session storage and local storage
* Unregister the service worker
* Load in an incognito window
* Disable extensions

The only thing that seems to resolve the issue, temporarily, is to restart Firefox. But then it just happens again a while later.

This may or may not be a bug in Firefox but I do not have this issue in any other service or website, just Home Assistant.

I have tried investigating in dev tools while this is happening but there are no outstanding pending requests, it just seemingly doing nothing, waiting for some kind of timeout probably.

### Describe the behavior you expected

I expect HA to load immediately like in other browsers.

### Steps to reproduce the issue

1. Open Firefox
2. Open Home Assistant
3. Close the tab
4. Wait a while (maybe a few hours)
5. Try to open Home Assistant again

### What version of Home Assistant Core has the issue?

Many versions up until at least v2021.9.7

### In which browser are you experiencing the issue with?

Firefox 90+

### Which operating system are you using to run this browser?

Windows 10

**Comment by DavidZidar** [comment]
In case it's helpful, my Home Assistance instance is running in a Docker container on a modern and fast Intel CPU behind an Nginx proxy with HTTPS. I have several other services with the same setup, none of them have this issue.

**Comment by spacegaier** [comment]
Can you check in your Firefox dev tools if there is something going on there. Any errors in the browser console? Any requests on the network tab that take a long time to complete?

Do you use any custom cards/elements in your dashboard?

**Comment by DavidZidar** [comment]
@spacegaier Sure, only warnings I'm seeing in the console are the following:
```
The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.
The resource at “https://homeassistant.ad.steamcore.se/static/fonts/roboto/Roboto-Medium.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly.
``` 

Here's a screenshot of the network panel while it's frozen doing nothing:
![image](https://user-images.githubusercontent.com/381720/135609306-3a8489b5-5ffb-4c03-82bb-78f8ceac5591.png)

Here's what loaded when it finally continued:
![image](https://user-images.githubusercontent.com/381720/135609483-f7942990-deaf-4b03-a0cf-30afb9827816.png)

**Comment by DavidZidar** [comment]
I'm not sure what you mean by custom cards/elements so probably not. I'm using Z-Wave JS, Philips Hue, IKEA Trådfri, and Google Chromecast.

**Comment by DavidZidar** [comment]
Since the websocket request is first after the delay I checked the timings, there was no delay on the server side or anything like that according to Firefox, note that it completed right after it was queued:
![image](https://user-images.githubusercontent.com/381720/135610474-9a060893-73c3-4558-856f-3be52c86ebc4.png)

**Comment by DavidZidar** [comment]
I'm reasonably certain now that this bug is in Firefox and not in Home Assistant. I recently set up a Cloudflare tunnel so I can access Home Assistant when I'm not at home and if I load the same HA instance in the same browser, just in different tabs, the tab which accesses it via the external tunnel works perfectly fine even though the one loaded over my local LAN is basically non functional.

To add to that, I have the exact same problem with Uptime Kuma too which also uses web sockets, so I'm closing this issue.

It would be nice though if Home Assistant could load and work even if the web socket connection is timing out.
