### ISSUE TITLE
Remote send command field is only one line

### ISSUE THREAD

**Issue by theetron** [home-assistant/frontend#10150]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using the GUI to make a script for the service remote.send_command you only get a single line to fill in one command. 
If you enter it like shown in the picture, you get an error saying that command doesn't exsist.

![Capture](https://user-images.githubusercontent.com/2996663/135972448-ed82c5e3-3fdb-4cbf-9f95-2a5ae8237a12.PNG)

This service however supports multiple, just like the remote.learn_command. You can see line numbers for the command field in the learn service and there is a checkbox in front of the label. Both are not present at the send_command service.

![Capture1](https://user-images.githubusercontent.com/2996663/135972496-a88609f5-7788-4d9f-918a-de147cad31a4.PNG)

If I edit the script in a text editor and make a command list, in the GUI it converts it to a comma separated list which causes errors.

```
    data:
      device: ledstrip
      command: 
        - red
        - white
        - blue
```

becomes:

```
    data:
      device: ledstrip
      command: red,white,blue
```

### Describe the behavior you expected

I want to be able to add multiple command to the remote.send_command using the GUI, just like the remote.learn_command.

### Steps to reproduce the issue

1. You need a remote for this, like a rm3 mini
2. Go to the develop / services page (or add a new script configuration\scripts)
3. Select the service remote.send_command as the action
4. You now can't fill in multiple lines for commands to send. it only allows you to enter one line. 
5. Also there is no checkbox to enable the command section.
...
One other way is to switch in the script section to yaml mode, add a list of commands and switch back to GUI mode. The list is now comma seperated.

### What version of Home Assistant Core has the issue?

core-2021.9.7

### In which browser are you experiencing the issue with?

Google Chrome Version 94.0.4606.71 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

**Comment by mmcc-xx** [comment]
For what it is worth, I can confirm this issue. In fact, I was about to report it myself but found @theetron already had.

**Comment by duffyd** [comment]
I can also confirm this is an issue

**Comment by iNaiks** [comment]
Same error

**Comment by petitpiton** [comment]
@balloob Still present in core 2022.2 - lists of commands don’t work!

**Comment by bramkragten** [comment]
Don't ping people please.

This is not a frontend issue, the `remote` integration defines what fields the frontend should show:

<https://github.com/home-assistant/core/blob/dev/homeassistant/components/remote/services.yaml#L50>

<https://github.com/home-assistant/core/blob/dev/homeassistant/components/remote/services.yaml#L98>

You can create a PR to change this in the core repo.
