### ISSUE TITLE
Calculation numbers don't add up with batteries

### ISSUE THREAD

**Issue by liquidacid** [home-assistant/frontend#10163]
### The problem

Hello!

Im very much liking the energy dashboard. Now it is getting interested with energy prices i started to use it more. This morning i came along a weird calculation issue which im not sure if this has been overlooked or i did overlook something:

Some time information:
At 1 AM i started charging my batteries with about 8Kw
At 4 AM i stopped it
At 7 AM i started discharging my batteries to the grid with about 8Kw
At 9 AM i stopped it.

Now it for some reason it shows 20.2kWh usage in home while it should be 7.1kWh if i calculate the numbers manually.

### What is version of Home Assistant Core has the issue?

core-2021.9.7

### What type of installation are you running?

Home Assistant OS

### Additional information

![energycalc](https://user-images.githubusercontent.com/6053516/135410151-026520ec-5d35-4653-bd0d-b0e3f4ca38f5.png)

**Comment by bramkragten** [comment]
No, that is missing the actual data, is there data displayed in the graphs when you ran this?

**Comment by liquidacid** [comment]
Hi, yes it was showing data, however in Chrome it seems to show the data as i would have expected:

`{
    "start": "2021-10-05T22:00:00.000Z",
    "end": "2021-10-06T21:59:59.999Z",
    "info": {
        "cost_sensors": {},
        "solar_forecast_domains": [
            "forecast_solar"
        ]
    },
    "prefs": {
        "energy_sources": [
            {
                "type": "grid",
                "flow_from": [
                    {
                        "stat_energy_from": "sensor.totalfromgrid",
                        "stat_cost": null,
                        "entity_energy_from": "sensor.totalfromgrid",
                        "entity_energy_price": null,
                        "number_energy_price": null
                    }
                ],
                "flow_to": [
                    {
                        "stat_energy_to": "sensor.totaltogrid",
                        "stat_compensation": null,
                        "entity_energy_to": "sensor.totaltogrid",
                        "entity_energy_price": null,
                        "number_energy_price": null
                    }
                ],
                "cost_adjustment_day": 0
            },
            {
                "type": "battery",
                "stat_energy_from": "sensor.essaccuontladenenergie",
                "stat_energy_to": "sensor.essaccugeladenenergie"
            },
            {
                "type": "solar",
                "stat_energy_from": "sensor.totalsolaryield",
                "config_entry_solar_forecast": [
                    "14e03eae8ae29b501b9f7becc971bdbe"
                ]
            }
        ],
        "device_consumption": []
    },
    "stats": {
        "sensor.totalfromgrid": [
            {
                "statistic_id": "sensor.totalfromgrid",
                "start": "2021-10-05T21:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 145.3,
                "sum": 140.3
            },
            {
                "statistic_id": "sensor.totalfromgrid",
                "start": "2021-10-05T22:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 145.3,
                "sum": 140.3
            },
            {
                "statistic_id": "sensor.totalfromgrid",
                "start": "2021-10-05T23:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 145.3,
                "sum": 140.3
            },
            {
                "statistic_id": "sensor.totalfromgrid",
                "start": "2021-10-06T00:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 154.2,
                "sum": 149.2
            },
            {
                "statistic_id": "sensor.totalfromgrid",
                "start": "2021-10-06T01:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 163,
                "sum": 158
            },
            {
                "statistic_id": "sensor.totalfromgrid",
                "start": "2021-10-06T02:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 169.3,
                "sum": 164.3
            },
            {
                "statistic_id": "sensor.totalfromgrid",
                "start": "2021-10-06T03:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 169.3,
                "sum": 164.3
            },
            {
                "statistic_id": "sensor.totalfromgrid",
                "start": "2021-10-06T04:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 169.3,
                "sum": 164.3
            },
            {
                "statistic_id": "sensor.totalfromgrid",
                "start": "2021-10-06T05:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 169.3,
                "sum": 164.3
            },
            {
                "statistic_id": "sensor.totalfromgrid",
                "start": "2021-10-06T06:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 169.3,
                "sum": 164.3
            },
            {
                "statistic_id": "sensor.totalfromgrid",
                "start": "2021-10-06T07:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 169.6,
                "sum": 164.6
            },
            {
                "statistic_id": "sensor.totalfromgrid",
                "start": "2021-10-06T08:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 169.8,
                "sum": 164.8
            },
            {
                "statistic_id": "sensor.totalfromgrid",
                "start": "2021-10-06T09:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 170.1,
                "sum": 165.1
            },
            {
                "statistic_id": "sensor.totalfromgrid",
                "start": "2021-10-06T10:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 170.7,
                "sum": 165.7
            },
            {
                "statistic_id": "sensor.totalfromgrid",
                "start": "2021-10-06T11:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 170.9,
                "sum": 165.9
            }
        ],
        "sensor.totaltogrid": [
            {
                "statistic_id": "sensor.totaltogrid",
                "start": "2021-10-05T21:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 195.9,
                "sum": 4590.900000000001
            },
            {
                "statistic_id": "sensor.totaltogrid",
                "start": "2021-10-05T22:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 195.9,
                "sum": 4590.900000000001
            },
            {
                "statistic_id": "sensor.totaltogrid",
                "start": "2021-10-05T23:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 195.9,
                "sum": 4590.900000000001
            },
            {
                "statistic_id": "sensor.totaltogrid",
                "start": "2021-10-06T00:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 195.9,
                "sum": 4590.900000000001
            },
            {
                "statistic_id": "sensor.totaltogrid",
                "start": "2021-10-06T01:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 195.9,
                "sum": 4590.900000000001
            },
            {
                "statistic_id": "sensor.totaltogrid",
                "start": "2021-10-06T02:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 195.9,
                "sum": 4590.900000000001
            },
            {
                "statistic_id": "sensor.totaltogrid",
                "start": "2021-10-06T03:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 195.9,
                "sum": 4590.900000000001
            },
            {
                "statistic_id": "sensor.totaltogrid",
                "start": "2021-10-06T04:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 195.9,
                "sum": 4590.900000000001
            },
            {
                "statistic_id": "sensor.totaltogrid",
                "start": "2021-10-06T05:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 196,
                "sum": 4591.000000000001
            },
            {
                "statistic_id": "sensor.totaltogrid",
                "start": "2021-10-06T06:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 204.7,
                "sum": 4599.700000000001
            },
            {
                "statistic_id": "sensor.totaltogrid",
                "start": "2021-10-06T07:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 205,
                "sum": 4600.000000000001
            },
            {
                "statistic_id": "sensor.totaltogrid",
                "start": "2021-10-06T08:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 205.3,
                "sum": 4600.300000000001
            },
            {
                "statistic_id": "sensor.totaltogrid",
                "start": "2021-10-06T09:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 205.6,
                "sum": 4600.600000000001
            },
            {
                "statistic_id": "sensor.totaltogrid",
                "start": "2021-10-06T10:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 206,
                "sum": 4601.000000000001
            },
            {
                "statistic_id": "sensor.totaltogrid",
                "start": "2021-10-06T11:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 209.6,
                "sum": 4604.600000000001
            }
        ],
        "sensor.essaccuontladenenergie": [
            {
                "statistic_id": "sensor.essaccuontladenenergie",
                "start": "2021-10-05T21:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 782.8,
                "sum": 203.69999999999993
            },
            {
                "statistic_id": "sensor.essaccuontladenenergie",
                "start": "2021-10-05T22:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 783.2,
                "sum": 204.10000000000002
            },
            {
                "statistic_id": "sensor.essaccuontladenenergie",
                "start": "2021-10-05T23:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 783.5,
                "sum": 204.39999999999998
            },
            {
                "statistic_id": "sensor.essaccuontladenenergie",
                "start": "2021-10-06T00:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 783.5,
                "sum": 204.39999999999998
            },
            {
                "statistic_id": "sensor.essaccuontladenenergie",
                "start": "2021-10-06T01:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 783.5,
                "sum": 204.39999999999998
            },
            {
                "statistic_id": "sensor.essaccuontladenenergie",
                "start": "2021-10-06T02:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 783.5,
                "sum": 204.39999999999998
            },
            {
                "statistic_id": "sensor.essaccuontladenenergie",
                "start": "2021-10-06T03:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 783.8,
                "sum": 204.69999999999993
            },
            {
                "statistic_id": "sensor.essaccuontladenenergie",
                "start": "2021-10-06T04:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 784.2,
                "sum": 205.10000000000002
            },
            {
                "statistic_id": "sensor.essaccuontladenenergie",
                "start": "2021-10-06T05:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 784.6,
                "sum": 205.5
            },
            {
                "statistic_id": "sensor.essaccuontladenenergie",
                "start": "2021-10-06T06:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 794.5,
                "sum": 215.39999999999998
            },
            {
                "statistic_id": "sensor.essaccuontladenenergie",
                "start": "2021-10-06T07:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 794.6,
                "sum": 215.5
            },
            {
                "statistic_id": "sensor.essaccuontladenenergie",
                "start": "2021-10-06T08:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 794.6,
                "sum": 215.5
            },
            {
                "statistic_id": "sensor.essaccuontladenenergie",
                "start": "2021-10-06T09:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 794.6,
                "sum": 215.5
            },
            {
                "statistic_id": "sensor.essaccuontladenenergie",
                "start": "2021-10-06T10:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 794.8,
                "sum": 215.69999999999993
            },
            {
                "statistic_id": "sensor.essaccuontladenenergie",
                "start": "2021-10-06T11:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 794.9,
                "sum": 215.79999999999995
            }
        ],
        "sensor.essaccugeladenenergie": [
            {
                "statistic_id": "sensor.essaccugeladenenergie",
                "start": "2021-10-05T21:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 788.8,
                "sum": 193.89999999999998
            },
            {
                "statistic_id": "sensor.essaccugeladenenergie",
                "start": "2021-10-05T22:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 788.8,
                "sum": 193.89999999999998
            },
            {
                "statistic_id": "sensor.essaccugeladenenergie",
                "start": "2021-10-05T23:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 788.8,
                "sum": 193.89999999999998
            },
            {
                "statistic_id": "sensor.essaccugeladenenergie",
                "start": "2021-10-06T00:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 796.4,
                "sum": 201.5
            },
            {
                "statistic_id": "sensor.essaccugeladenenergie",
                "start": "2021-10-06T01:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 804.1,
                "sum": 209.20000000000005
            },
            {
                "statistic_id": "sensor.essaccugeladenenergie",
                "start": "2021-10-06T02:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 809.4,
                "sum": 214.5
            },
            {
                "statistic_id": "sensor.essaccugeladenenergie",
                "start": "2021-10-06T03:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 809.4,
                "sum": 214.5
            },
            {
                "statistic_id": "sensor.essaccugeladenenergie",
                "start": "2021-10-06T04:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 809.4,
                "sum": 214.5
            },
            {
                "statistic_id": "sensor.essaccugeladenenergie",
                "start": "2021-10-06T05:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 809.4,
                "sum": 214.5
            },
            {
                "statistic_id": "sensor.essaccugeladenenergie",
                "start": "2021-10-06T06:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 809.4,
                "sum": 214.5
            },
            {
                "statistic_id": "sensor.essaccugeladenenergie",
                "start": "2021-10-06T07:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 810.2,
                "sum": 215.30000000000007
            },
            {
                "statistic_id": "sensor.essaccugeladenenergie",
                "start": "2021-10-06T08:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 813.3,
                "sum": 218.39999999999998
            },
            {
                "statistic_id": "sensor.essaccugeladenenergie",
                "start": "2021-10-06T09:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 817.3,
                "sum": 222.39999999999998
            },
            {
                "statistic_id": "sensor.essaccugeladenenergie",
                "start": "2021-10-06T10:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 820.9,
                "sum": 226
            },
            {
                "statistic_id": "sensor.essaccugeladenenergie",
                "start": "2021-10-06T11:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 821.4,
                "sum": 226.5
            }
        ],
        "sensor.totalsolaryield": [
            {
                "statistic_id": "sensor.totalsolaryield",
                "start": "2021-10-05T21:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 1311.2,
                "sum": 77.20000000000005
            },
            {
                "statistic_id": "sensor.totalsolaryield",
                "start": "2021-10-05T22:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 1311.2,
                "sum": 77.20000000000005
            },
            {
                "statistic_id": "sensor.totalsolaryield",
                "start": "2021-10-05T23:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 1311.2,
                "sum": 77.20000000000005
            },
            {
                "statistic_id": "sensor.totalsolaryield",
                "start": "2021-10-06T00:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 1311.2,
                "sum": 77.20000000000005
            },
            {
                "statistic_id": "sensor.totalsolaryield",
                "start": "2021-10-06T01:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 1311.2,
                "sum": 77.20000000000005
            },
            {
                "statistic_id": "sensor.totalsolaryield",
                "start": "2021-10-06T02:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 1311.2,
                "sum": 77.20000000000005
            },
            {
                "statistic_id": "sensor.totalsolaryield",
                "start": "2021-10-06T03:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 1311.2,
                "sum": 77.20000000000005
            },
            {
                "statistic_id": "sensor.totalsolaryield",
                "start": "2021-10-06T04:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 1311.2,
                "sum": 77.20000000000005
            },
            {
                "statistic_id": "sensor.totalsolaryield",
                "start": "2021-10-06T05:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 1311.2,
                "sum": 77.20000000000005
            },
            {
                "statistic_id": "sensor.totalsolaryield",
                "start": "2021-10-06T06:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 1311.3,
                "sum": 77.29999999999995
            },
            {
                "statistic_id": "sensor.totalsolaryield",
                "start": "2021-10-06T07:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 1312,
                "sum": 78
            },
            {
                "statistic_id": "sensor.totalsolaryield",
                "start": "2021-10-06T08:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 1314.1,
                "sum": 80.09999999999991
            },
            {
                "statistic_id": "sensor.totalsolaryield",
                "start": "2021-10-06T09:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 1316.8,
                "sum": 82.79999999999995
            },
            {
                "statistic_id": "sensor.totalsolaryield",
                "start": "2021-10-06T10:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 1319.8,
                "sum": 85.79999999999995
            },
            {
                "statistic_id": "sensor.totalsolaryield",
                "start": "2021-10-06T11:00:00+00:00",
                "mean": null,
                "min": null,
                "max": null,
                "last_reset": null,
                "state": 1323,
                "sum": 89
            }
        ]
    }
}
`
