### ISSUE TITLE
Gas cost not calculating since moving to kWh

### ISSUE THREAD

**Issue by danielsmith89** [home-assistant/frontend#10187]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using the new Gas in kWh feature, the cost is not calculating even though the input entity value is set correctly and the consumption value is updating. It's just showing as £0.00 all the time. It worked perfectly when everything was in m3.

### Describe the behavior you expected

Gas cost to be calculated by the amount of kWh x input value (currently 0.028 for me)

### Steps to reproduce the issue

1. Check gas consumption working correctly
2. Set gas cost to entity value
3. Check energy dashboard which isn't updating the cost amount

### What version of Home Assistant Core has the issue?

core-2021.10.0

### What was the last working version of Home Assistant Core?

N/A new feature

### In which browser are you experiencing the issue with?

Chromium 93.0.4577.82

### Which operating system are you using to run this browser?

mac OS Big Sur

### State of relevant entities

```txt
input_number.current_gas_cost -> 0.028
```

**Comment by tmh88** [comment]
I’m having the same issue

**Comment by pbranly** [comment]
From version 2021.11, it is working
But from the time you moved to new version
Result from tomorrow !

**Comment by danielsmith89** [comment]
Can confirm it's now all working in 2021.11, thank you!
