### ISSUE TITLE
Input Number state not visible in preview (slider cut-off)

### ISSUE THREAD

**Issue by drthanwho** [home-assistant/frontend#10188]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Adding an input_number helper in a card doesn't show the state while picking up a number (in the preview circle). Either alone in a card or with other entities in an entities card the number is obscured 
![image](https://user-images.githubusercontent.com/22405505/136421817-a6408772-7bcd-46d8-889c-a66461668a5c.png)

### Describe the behavior you expected

I'd expect the number not to be obscured and to show up as it did in the past within the blue circle.

### Steps to reproduce the issue

1. Make an input_number helper
2. Add the helper in an entities card
3. Try to change the value from the slider
4.  Be disappointed

### What version of Home Assistant Core has the issue?

core-2021.10.0

### What was the last working version of Home Assistant Core?

core-2021.9.7 (I think)

### In which browser are you experiencing the issue with?

Google Chrome 94.0.4606.71 / Firefox 91.0.2

### Which operating system are you using to run this browser?

Windows 10 / Android

**Comment by OzGav** [comment]
Same problem. Appears to have been an issue a few years ago but was fixed but now has come back again? https://github.com/home-assistant/ui-schema/issues/150

**Comment by Raul-7-7** [comment]
Same issue here. on Chrome.

**Comment by cibernox** [comment]
Probably unnecessary at this point but I came here to report a similar thing. Here's a video:
https://user-images.githubusercontent.com/265339/137734434-b9cc76fd-e338-4131-88f8-232b04423b4a.mov
