### ISSUE TITLE
Input numbers are not displayed properly

### ISSUE THREAD

**Issue by dankarization** [home-assistant/frontend#10192]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have recently updated home assistant core from 6 to 10 version and Lovelace bug was found. I have a card with few input numbers settings. Previously all 3 of them showed a circle with currently selected number (like on the 2nd photo). On the latest version only the lowest works as intended and 2 other (on the 1st photo) show this circle cropped so I can't see anything there.
![photo_2021-10-07_23-15-00](https://user-images.githubusercontent.com/26330178/136455750-45618f8f-02b1-4b6d-ad5d-de1331089c77.jpg)
.
![photo_2021-10-07_23-14-55](https://user-images.githubusercontent.com/26330178/136455752-3cfc7857-acd7-4cdd-8a89-62727fd8d06c.jpg)

This bug is not presented on the android app. There all works like it was previously.

### Describe the behavior you expected

All circles show numbers like here
![photo_2021-10-07_23-14-55](https://user-images.githubusercontent.com/26330178/136455964-32847672-9c77-41fa-9c3f-ce222e5dcfb8.jpg)

### Steps to reproduce the issue

I will paste my card core here. You can copy it to test for yourself.

type: entities
entities:
  - entity: group.alarm_1
    icon: mdi:alarm-check
    name: Будильник
  - entity: sensor.alarm_1_time
    icon: mdi:clock-outline
    name: Время срабатывания
  - entity: input_number.alarm_1_hour
    icon: mdi:cog-clockwise
    name: Часы
  - entity: input_number.alarm_1_minutes
    icon: mdi:cog-clockwise
    name: Минуты
  - type: custom:fold-entity-row
    head:
      type: section
      label: Параметры
    entities:
      - entity: sensor.time_date
        name: Текущее время и дата
      - entity: sensor.alarm_1_time_minus_cover
        name: Время открытия шторы
      - entity: input_number.alarm_1_cover
        name: Шторы
      - entity: input_boolean.alarm_1_weekday
        name: Рабочие дни
      - entity: input_boolean.alarm_1_weekend
        name: Выходные дни
      - entity: input_boolean.alarm_1_lights
        name: Искусственный свет

### What version of Home Assistant Core has the issue?

core-2021.10.0

### What was the last working version of Home Assistant Core?

core 6.4

### In which browser are you experiencing the issue with?

Google Chrome 94.0.4606.61

### Which operating system are you using to run this browser?

Windows 10

**Comment by drthanwho** [comment]
Two issues down there is already an open issue for this #10188
