### ISSUE TITLE
Gas in kWh does not report correctly values

### ISSUE THREAD

**Issue by pbranly** [home-assistant/frontend#10207]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

- Energy coming from grid and coming from gas in kWh are not added in the Total

 - « non fossil » is only the one for grid ( so is wrong as gas is 100% fossil) and calculation should consider « non fossil »/« Total »
- Even with an unit price, gas price stays equal to 0

### Describe the behavior you expected

- Energy coming from grid and coming from gas in kWh should be added in the Total (Home)

 - « non fossil »  calculation should consider « non fossil »/« Home » values
 
- There should be Gas cost calculation

### Steps to reproduce the issue

no step necessary; situation after several hours

### What version of Home Assistant Core has the issue?

Home Assistant Container

### What was the last working version of Home Assistant Core?

 	core-2021.10.1

### In which browser are you experiencing the issue with?

All (Fiefox, Chrome, + Ipad Safari

### Which operating system are you using to run this browser?

Windows 11

**Comment by Eddie46848** [comment]
I have exactly the same issue.
The only thing I found was this error in the logs.
Found unexpected unit kWh for sensor.gas_consumption_today
2021-10-13 10:54:02 WARNING
I had no problem adding the sensor and it counts up the kWh but just won’t add up a static price.

**Comment by ColinRobbins** [comment]
Please note, the change above only takes into account the current daily rate for gas.
For the UK (and some other countries) we have a standing daily charge that is not taken into account.
There is a [feature request](https://community.home-assistant.io/t/energy-add-fixed-daily-cost/330609) for that.  Please add a `vote` to on [that page](https://community.home-assistant.io/t/energy-add-fixed-daily-cost/330609) if you’d benefit from standing charge being added.

**Comment by ColinRobbins** [comment]
PR created!
![gas](https://user-images.githubusercontent.com/13466873/139798969-b7f8e135-74f0-4d76-87ac-bf72e9238aa6.png)

**Comment by pbranly** [comment]
Thankkkkks a lot 
This will be wonderful 
Phil

**Comment by pbranly** [comment]
Hi it seems blocked 
What are the next steps ?
Phil

**Comment by townsmcp** [comment]
> Hi it seems blocked
> What are the next steps ?
> Phil

Have you installed 2021.11.0? Costs for gas are now showing with the new update

**Comment by pbranly** [comment]
Yes sure I did yesterday.
It is working
What surprises me is that price  calculation is not made from the total number of  kWh but from the total from the  time of installation .
This seems a little bit complicate. 
nevertheless I hope that this principle will permit cost/kWh changes with calculation from the change 
Phil

**Comment by ColinRobbins** [comment]
For info, the HA frontend folk have rejected the PR that correctly handles Gas in kWh…

> We've decided to not do this right now. We don't want to include gas until we have a proper plan how gas can work in energy management regardless of the unit.

Back to the drawing board.

**Comment by pbranly** [comment]
I just saw it and deeply regret that decision.
Thank you everybody for the work done 
Regards
Philippe

**Comment by pbranly** [comment]
This request should be kept for further releases
Phil

**Comment by ColinRobbins** [comment]
This issue is not resolved   - a PR was proposed and rejected, but no alternative solution yet provided.

**Comment by pbranly** [comment]
Hi
It is a pity that this issue is closed as fixed because the module still reports wrong total energy value .
Please re open
Regards
Philippe
