### ISSUE TITLE
After update to 2021.10.1 alarm panel icon not visible, just empty circle

### ISSUE THREAD

**Issue by IgorSimic** [home-assistant/frontend#10202]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After update to 2021.10.1 alarm panel icon not visible, just empty circle.
![alarm_panel_after](https://user-images.githubusercontent.com/44424256/136542830-62e86806-ae64-4c41-8bd1-183860c7f97d.png)

Edit:
Visible even at demo page: https://demo.home-assistant.io/#/lovelace/0

### Describe the behavior you expected

It should look like this:
![alarm_panel_before](https://user-images.githubusercontent.com/44424256/136542115-f155a6f4-038f-44bd-bb26-0c387729b69a.png)

### Steps to reproduce the issue

1. Upgrade
2. Refresh

### What version of Home Assistant Core has the issue?

core 2021.10.1

### What was the last working version of Home Assistant Core?

core 2021.10.0

### In which browser are you experiencing the issue with?

Mobile app, Chrome, Chromium, Edge, Firefox, Opera, Vivaldi

### Which operating system are you using to run this browser?

Android several versions, Linux Mint 19, Windows 10

**Comment by tomlut** [comment]
While testing this issue I tried adding badges to a view to see if their icons would be visible. None of the added badges were visible in the view.

**Comment by ausfas** [comment]
Thanks for the clarification.
