### ISSUE TITLE
Every add-on says "401: Unauthorized" in chrome

### ISSUE THREAD

**Issue by ttadam** [home-assistant/frontend#10229]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hello there,

Nowadays every time I try to open to an add-on I got 401. Only if I open HA in a private browser then can I access the addons. 
I enabled unsafe content in chrome settings, but doesn't solved it. 
On my IPhone the HA app works fine, also tried edge it works also fine. 

Thanks! :)

### Describe the behavior you expected

I would like to access my addons from my "main" browser

### Steps to reproduce the issue

1.  open HA UI in chrome
2. click any add-on from the left bar
3.
...

### What version of Home Assistant Core has the issue?

2021.10.2

### Which operating system are you using to run this browser?

windows 10

**Comment by spacegaier** [comment]
The fact that it works in private browsing mode makes it sound like a caching issue. In your normal browsing mode, open the browser dev tools (F12) and to to the "Network" tab and set the checkbox "Disable Cache" and then press Ctrl + F5 to trigger a complete refresh of the page. The checkbox will ensure that everything is loaded again.
