### ISSUE TITLE
HA badge overlaying entity value over entity_picture_template

### ISSUE THREAD

**Issue by faithless01** [home-assistant/frontend#10236]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Similar to bug #10197, (which is fixed in core_2021.10.3)

Badges with image icons as defined by entity_picture_templates are displaying the entity value overlaying the image.
The issue began with core_2021.10.1, where all badges with icons received a value overlay.
_The 'person' entity badges received the person mdi icon overlaid. This is fixed by ludeeus and spacgaier._

Other badges with icons and values, (not mdi icons, as per #10197), still have the value overlaid.

### Describe the behavior you expected

The icon would previously replace, or overwrite the entity value in the badge.
I would not expect the entity value to overlay the defined entity_picture_template entry.
Just as mdi icons overlaying a person entitys badge image was considered a bug.

### Steps to reproduce the issue

1.  Upgrade to core-2021.10.1
2.  Add a badge to Lovelace of an entity with an entity picture defined in the template

### What version of Home Assistant Core has the issue?

core-2021.10.3

### What was the last working version of Home Assistant Core?

core-2021.10.0

### In which browser are you experiencing the issue with?

Google Chrome 94.0.4606.81

### Which operating system are you using to run this browser?

Windows 10 Ver 21H1 OS Build 19043.1237

### State of relevant entities

```txt
-- Entity
sensor.car_present_icon
-- State
1.13
-- State Attributes (YAML optional)
1 friendly_name: BMO
2 entity_picture: /local/icons/badge_icons/bmo_home.png
```

### Problem-relevant frontend configuration

```yaml
# Garagedoor Sensors

  - platform: template
    sensors:
      car_present:
        friendly_name: 'BMO Home'
        value_template: >-
         {% set detect = states('sensor.car_sensor') | float %}

         {% if 0 < detect < 1.5 %}
           home
         {% elif 1.5 <= detect < 3 %}
           out
         {% else %}
           OFF
         {% endif %}
      
      car_present_icon:
        friendly_name: 'BMO'
        value_template: '{{ states.sensor.car_sensor.state }}'
        entity_picture_template: >-
         {% set detec = states('sensor.car_sensor') | float %}
         {% if 0 < detec < 1.5 %}
            /local/icons/badge_icons/bmo_home.png
         {% elif 1.5 <= detec < 3 %}
            /local/icons/badge_icons/road.png
          {% else %}
            /local/icons/badge_icons/alert.png
          {% endif %}
```

### Javascript errors shown in your browser console/inspector

```txt
n/a
```

### Additional information

The Entity Value 1.13 is overlaid in the badge.
The clean image can be seen in the Entity Card.
_(Note the **person** mdi icon has been fixed - #10197)_

![entity_picture_bug](https://user-images.githubusercontent.com/33531269/136821029-9944841c-8aa1-4f64-baf0-988d80d86add.png)

**Comment by Mariusthvdb** [comment]
please see https://community.home-assistant.io/t/after-upgrading-to-10-x-badge-photos-have-icon-over-them/345431/3?u=mariusthvdb

this is new behavior indeed, introduced when the Pr was merged
