### ISSUE TITLE
Editor unusable

### ISSUE THREAD

**Issue by pedolsky** [home-assistant/frontend#10240]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Editing code in Code Editor isn't possible. The first line stays marked grey, and the curser jumps back to pos. 1, see video.

https://user-images.githubusercontent.com/71203830/136858567-57f1ecc5-9f44-46ff-9ae8-91acea880c3c.mov

### Describe the behavior you expected

Editing code properly.

### Steps to reproduce the issue

Go to UI, choose edit UI, try to edit a card in code editor mode

or

go to Developer Tools -> Templates and try to edit code

...

### What version of Home Assistant Core has the issue?

2021.10

### What was the last working version of Home Assistant Core?

2021.9.7

### In which browser are you experiencing the issue with?

Google Chrome latest, Safari latest

### Which operating system are you using to run this browser?

iPadOS 15.0.1

**Comment by troponaut** [comment]
similar odd behavior described on #10102

**Comment by loeffelpan** [comment]
Fixed since 2021.12. Can be closed.
