### ISSUE TITLE
Cost doesn't show on energy tab

### ISSUE THREAD

**Issue by adizag** [home-assistant/frontend#10255]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Cost is defined per each phase, but aftersome HA version upgrade it stopped showing the cost (shows "0") on the energy tab.

![image](https://user-images.githubusercontent.com/17390016/137078414-16d16b47-c6b6-4298-9228-8df6f2f2fa03.png)

![image](https://user-images.githubusercontent.com/17390016/137078362-6b44be56-a6fe-49af-a0f1-b00173826fbd.png)

### Describe the behavior you expected

Cost should be shown

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.10.4

### Which operating system are you using to run this browser?

Windows/android/linux

**Comment by squio** [comment]
Just to be sure: how long did you wait to check back after adding the 'static price' to the grid consumption setting?

It take significant time to get the first results on the dashboard (I think I had to wait more than 2 hours, only after a full day the report started to show with all bar charts filled)

**Comment by adizag** [comment]
@squio can you help? whom shall I address it?

**Comment by squio** [comment]
Not sure what goes wrong here, settings look good. 

You may want to enable Developer Tools in HA and see if there is any error message in the tab "statistics", then the screen "Fix issue" might give more info.
See screenshot below

![Screenshot_20211117-112413](https://user-images.githubusercontent.com/169410/142183410-2f184366-eeb8-4a23-9f2e-f2292a84f60a.png)

**Comment by adizag** [comment]
That did it!
tnx!!!

____________________________________________
"יש המטביעים את צרותיהם - ויש המלמדים אותן לשחות..."
"אין מקום שהוא רחוק מדי"
