### ISSUE TITLE
Card "energy-distribution" does not reflect today

### ISSUE THREAD

**Issue by IntExCZ** [home-assistant/frontend#10269]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The independently used card does not reflect actual day (after midnight).
To change day of this card the card "energy-date-selection" must be additionaly used.

### Describe the behavior you expected

The "energy-distribution" should display today's consumption without "energy-date-selection" card on the dashboard.

### Steps to reproduce the issue

1.Place "energy-distribution" card on the dashboard
2.Wait until 0:00
3.The card still displays yesterday's consumption
...

### What version of Home Assistant Core has the issue?

core-2021.10.4

**Comment by mnestor** [comment]
I use this on a status display that has no inputs so I've just added a cronjob to force the window to reload for now. Having it always auto switch to the current day would be very handy.
