### ISSUE TITLE
Nanoleaf Status not visible when not using "dark mode"

### ISSUE THREAD

**Issue by Andy-Wismer** [home-assistant/frontend#10263]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Nanoleaf canvas element in Lovelace does not show anything in "light mode" - it's only visible in dark mode.
A few weeks ago, the default color was yellow, which worked in both modes. The new white is not visible against a white background, as in "light mode"...

![Bildschirmfoto 2021-10-13 um 13 33 38](https://user-images.githubusercontent.com/63340029/137125316-fcb741fd-1dde-4452-b7b5-0359b643b18f.JPG)

![Bildschirmfoto 2021-10-13 um 13 33 51](https://user-images.githubusercontent.com/63340029/137125331-4950cdf8-e716-419f-8caf-c6a8a6d5ec12.JPG)

### Describe the behavior you expected

The triangle used to be a default color of yellow, making this usable in both environments, Light & Dark-Mode.
With the new White color, this becomes invisible in the Light-Mode version...

Same issue also using mobile App on the latest iPhone iOS...

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.10.4

### In which browser are you experiencing the issue with?

92.0.1 (64-Bit), MacOS Version

### Which operating system are you using to run this browser?

MacOS 10.12.6

**Comment by spacegaier** [comment]
Sounds like a duplicate of #9197.
