### ISSUE TITLE
input datetime: seconds set to zero without input

### ISSUE THREAD

**Issue by tobi-bo** [home-assistant/frontend#10278]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When an input field for an input datetime entity is shown in the UI, the seconds of the datetime value is set to zero, without editing the value explicitly. Maybe one reason is, that with the default input field for time values seconds cannot be set at all.

### Describe the behavior you expected

The value of the input datetime entity should not be set to another value, when just showing the UI. Only when editing the value it should change.

### Steps to reproduce the issue

1. take any input_datetime entity with only time input
2. use service dev tools and call service input_datetime.set_datetime for that entity with time: '00:00:30'
3. check with states dev tools the state of the entity, it is '00:00:30'
4. Go to a lovelace dashboard and just view a control for this entity (for example the generated dashboard with all entities). Alternatively view the more info dialog, which shows the value of the entity from configuration -> entities.
5. go to states dev tools and check the state of the entity again, it is '00:00:00'

### What version of Home Assistant Core has the issue?

core-2021.10.4

### In which browser are you experiencing the issue with?

Chromium to 94.0.4606.81, Firefox 93.0

### Which operating system are you using to run this browser?

Win10

### State of relevant entities

```txt
After service call:

editable: true
has_date: false
has_time: true
hour: 0
minute: 0
second: 30
timestamp: 85
friendly_name: some time

After showing:

editable: true
has_date: false
has_time: true
hour: 0
minute: 0
second: 0
timestamp: 0
friendly_name: some time
```

**Comment by tobi-bo** [comment]
In core-2021.12.9 the issue is still present.

**Comment by tobi-bo** [comment]
With 2022.4.5 this issue no longer occurs.

**Comment by karwosts** [comment]
Closing as fixed.
