### ISSUE TITLE
Temperature sensor showing 5 or more decimals

### ISSUE THREAD

**Issue by user897943** [home-assistant/frontend#10288]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Temperature sensor from my Nest thermostat, the platform has more granularity for temperature reads but the frontend should not show more than 1 decimal point. This is not user-friendly at all and looks really weird. It has been a problem since several versions ago, I cannot really tell which because it's been like this for several months now, I reported to the Nest maintainer and he said it's a frontend issue. Indeed this was after a frontend update several months back. If the decimals are hard coded for temps then please make it just one decimal only i.e 60.5 instead of 60.53446. Otherwise please give an option on the general settings to specify how many decimals we would like, that way each user can customize for what is best for them. The 2nd floor sensor is from my Hue multisensor and is showing only 1 decimal as you can see.

![Screenshot_20211015_230228](https://user-images.githubusercontent.com/5891221/137559156-e2fdfab0-eb3f-4cb7-b1b4-5b7a1eca18b8.png)

### Describe the behavior you expected

I expect temperature to be 1 decimal point only, the way it used to be a few months back until the frontend was updated and this started happening.

### Steps to reproduce the issue

1. Add Nest thermostat using the new Google integration (not the old Works with Nest)
2. See weird temp appear, with more than one decimal which is not industry standard and definitely not user-friendly

### What version of Home Assistant Core has the issue?

core-2021.10.4

### In which browser are you experiencing the issue with?

All browsers (Edge Chromium, Edge MS, Chrome, Chromium, Firefox (both Linux and Windows), also Chrome and Edge on Android

### Which operating system are you using to run this browser?

Android 12, Windows 11, Windows 10, Debian 11

### State of relevant entities

```txt
state: 65.53398	
unit_of_measurement: °F
friendly_name: House Temperature
device_class: temperature
```

### Problem-relevant frontend configuration

```yaml
type: sensor
entity: sensor.house_temperature
graph: line
name: 1st floor
detail: 1
```

### Additional information

I already reported to the Nest maintainer he said it's not an issue with his integration but a frontend issue.

**Comment by spacegaier** [comment]
There is nothing hardcoded for temperatures. The frontend shows what the backend provides here, so if the backend provides 5 decimals, we currently show those. Your Hue sensor apparently only reports a single digit, hence only one is shown in the frontend.

I think there are ongoing discussions about how to handle decimals / rounding in general in one of the HA repositories (although I cannot seem to find them right now), but for now that is still up to the backend.
