### ISSUE TITLE
4 issues for a Script editing on iPhone

### ISSUE THREAD

**Issue by qoff** [home-assistant/frontend#10292]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Confirmed on iPhone SE (2020): Firefox and Opera and HomeAssistant app. Latest versions.
A video showing these issues is attached.

Issue 1: system preselects values for the user on moving an element up when editing a script
Issue 2: filtered list of i.e. devices not clickable when editing a script
Issue 3: auto-scrolling is too aggressive when editing a script
Issue 4: Leave button doesn't work when trying to abandon your modifications for automation or a script

### Describe the behavior you expected

For issue 1: preselection for the user doesn't sound right. Especially on two levels. Or this is expected as a random script functions generator?

For issue 2: filtering of the devices should be clickable. Filtering works, clickability doesn't. What's the use of a filtered list that you can only look at?

For the issue 3: automatic scrolling should not be so aggressive. Ok, let the system propose the desired element position on the screen - once - not always. When the user finds the position not usable and corrects it, let it be an override and not a constant fight between user vs. system - who's faster on correcting the page position on the screen.

### Steps to reproduce the issue
A video showing these issues is attached.

Issue 1:
1. Navigate to Scripts on the dashboard.
2. Click the script name > pencil/edit on some pre-existing script.
3. Scroll down to the bottom of the script.
4. Click Add Action.
5. The action type is now "Device" by default. Should it be like that? User didn't select it yet.
6. Click the arrow "UP" to move the element up in the order of elements.
7. Now the Action type is preselected to "Device" and the "Device" is preselected/filled with some device name from your system. Now it's two fields that the system preselected for the user. None of them user didn't want yet to select.

Issue 2:
1. When editing i.e. a script click on the Action type and select something (I chose Condition).
2. Choose Condition type.
3. Start typing fragment of an already existing device name so that it gets filtered for you to just have one option on your dropdown for a super easy just-click-on-it.
4. Do the just-click-on-it and you will win. No, you will loose. Not so easy. You cannot just click on it, the name disappears upon click. The field becomes empty.
5. In the meantime observe issue 3 - a scrolling hell of a devil. You scroll the page a bit up to just see the dropdown (well, how to click on a listed options from dropdown when you can't see them?) and the system thinks you are dumb and... scrolls down back for you to hide the dropdown options so that you couldn't click them.
6. Get into an infinite loop of issues 2 and 3 together.
7. Get furious and throw your phone over the wall. Or, if your device list is short enough just don't try to filter it, but scroll the full list down to select your desired device from among the full list of devices you have in your system as this is the only way to make it work correctly.

Issue 4:
Try to leave the Script or Automation that you were just editing a moment ago, without saving.
Literally, click the Back arrow at the top-left corner of the screen and confirm by clicking Leave.
You can't leave, it doesn't work. At least not for the first and second time of your attempts.

### What version of Home Assistant Core has the issue?

2021.10.4

### In which browser are you experiencing the issue with?

Firefox Focus 38.1, Opera 3.2.0

**Comment by spacegaier** [comment]
1. Please create separate tickets for separate issues, otherwise it just gets confusing and difficult to track.
2. Your issue #4 has already been fixed (https://github.com/home-assistant/frontend/pull/10211).
3. Title mentions "iPhone". Do they only apply to that platform? Did you try on others?
