### ISSUE TITLE
Temperature sensor card take graph of other sensor card

### ISSUE THREAD

**Issue by MansM** [home-assistant/frontend#10297]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When click a graph the sensor card takes
the graph of the other. When going to another tab and back it restores proper graph. 

this happens on iOS app and safari on mac

![144F5933-3133-4C09-B215-3A62455F9019](https://user-images.githubusercontent.com/14215294/137592221-cd3da516-2337-4001-9a87-91286b9387dd.jpeg)
![EF7A9E6B-F3D5-47E6-B906-F4D0D480CC27](https://user-images.githubusercontent.com/14215294/137592222-3d7de1cb-28ea-4204-adc9-12e73d479126.jpeg)

### Describe the behavior you expected

Not duplicated graphs

### Steps to reproduce the issue

1.  Add 2 different sensor cards
2. Click a graph
3. See the duplication
4. Click on another tab and return
...

### What version of Home Assistant Core has the issue?

2021.10.2 and 2021.10.4 (skipped .3) 

### In which browser are you experiencing the issue with?

Safari 

### Which operating system are you using to run this browser?

Latest Big Sur

**Comment by gedger** [comment]
I am seeing the same issue. I have a number of sensor cards in a grid displaying temperature and humidity. When you click on the sensor to display the the history graph all other sensor graphs display the graph from the last sensor displayed. This behaviour is seen on the iOS and iPadOS Apps.

![image](https://user-images.githubusercontent.com/8577703/146670746-3de807c7-01dd-40d2-b857-e040e8577b6f.png)

![image](https://user-images.githubusercontent.com/8577703/146670754-4af1063c-1086-4796-a447-378fd8b98684.png)

**Comment by danielhenaux** [comment]
I have the exakt same problem. Any updates on this?

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/issues/9134
