### ISSUE TITLE
Entity and Button card does not work properly with new tuya integration

### ISSUE THREAD

**Issue by CasaTepeji** [home-assistant/frontend#10305]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

using button card for entities from tuya integration you can turn on any switch (light or outlet) but you can't turn off. After toogle to turn on lights are on, but entity state if off and you never can turn off. Icon state color maintain in off

using entity card yo can turn on any entity, inmediatly button goes off but light (or outlet) still on. yo can't turn off by clicking entity, you have to double clik on entity to tunr off. Same thing with icon color state, still always off

claudio

### Describe the behavior you expected

you can turn on or turn of any switch entity just clicking a button or entity (entities) card, and icon color should show state 

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.10.5

### In which browser are you experiencing the issue with?

chrome or edge

### Which operating system are you using to run this browser?

windows 10

**Comment by spacegaier** [comment]
If I understood you correctly, the backend state is not correct after switching on the light? If that is the case, then this ticket would need to move to the backend/core repository.

Did you check in the HA dev tools (tab "State"), if that is the case?
