### ISSUE TITLE
Outline on mouseover broken in Firefox (again)

### ISSUE THREAD

**Issue by mwasowski** [home-assistant/frontend#10309]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Outline around items is Firefox is broken again when in Edit dashboard mode:

![firefox_FigahHpAXt](https://user-images.githubusercontent.com/1921808/93598583-2ac65e80-f9bd-11ea-8a0b-f8acd3a10e41.png)

Works fine in Chrome based browsers.

This is the same issue that I reported in #7050 fixed by @thomasloven in #7052. Previously this was reported/fixed in #5430 but broken again in #6132. Now I can't track what changed that it started to happen again.

### Describe the behavior you expected

![vivaldi_sknLUG6jVN](https://user-images.githubusercontent.com/1921808/93598575-28640480-f9bd-11ea-9c1d-a56b89d4a01d.png)

### Steps to reproduce the issue

Go to Edit Dashboard in Firefox and mouse over any of the cards.

### What version of Home Assistant Core has the issue?

2021.10.5

### In which browser are you experiencing the issue with?

Firefox 93.0

### Which operating system are you using to run this browser?

Windows 10 x64

**Comment by mwasowski** [comment]
Uhm, bump?

**Comment by mwasowski** [comment]
Bumb #2

**Comment by spacegaier** [comment]
Please don't bump unless the Github `stale` bot needs to be shooed away. I personally think this is really low prio issue, but independent of that: Until someone comes along who wants to fix it, this will remain open for now, no matter how often you bump it 😉 .

**Comment by mwasowski** [comment]
Right, my bad.

I get it's low priority and all. But at the same time the fact that something gets broken for the third time I believe, is just a sign of lack of some kind of unit/integration tests ;)

I think I'm just used to a process where resolving an issue means I fix the problem and write a test that both verifies my change is correct and saves me from wasting my time fixing it again after any kind of potentially unrelated change :)

**Comment by spacegaier** [comment]
Well, unit testing visual elements is as far as I know quite tricky (unit tests as the Python backend does are a lot easier to setup). So we do not have those for the frontend (apart from some non visual logic tests).

But feel free to propose a setup for such a thing in a discussion. Might be an interesting discussion, but not sure if that can be handled with the small frontend team.

**Comment by mwasowski** [comment]
Agreed, visual is tricky and this particular case is even trickier I think. It's not like after hitting Edit the card gets red or something ;)

So if sounded like a smart ass (or simply a dick) suggesting that you do not have test coverage for changes I'm sorry, this was definitely not intended because I wholeheartedly appreciate all the work you do ❤️
