### ISSUE TITLE
Filtered dropdown list for entity of edited script not always possible to select/apply by clicking on it

### ISSUE THREAD

**Issue by qoff** [home-assistant/frontend#10311]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Filtered dropdown values of the entities/devices while editing a script/automation should be clickable. Filtering works, while clickability does not always work.

The issue doesn't behave consistently for me. The most important is that it's been recorded.

### Describe the behavior you expected

Filtering of the devices should be clickable. Filtering works, while clickability does not always work.

### Steps to reproduce the issue

1. When editing i.e. a script click on the Action type and select something (I chose Condition).
2. Choose Condition type.
3. Start typing fragment of an already existing device name so that it gets filtered for you to just have one option on your dropdown for a super easy just-click-on-it.
4. Do the just-click-on-it and you will win. No, you will loose. Not so easy. You cannot just click on it, the name disappears upon click. The field becomes empty.
5. If your device list is short enough just don't try to filter it, but scroll the full list down to select your desired device from among the full list of devices you have in your system as this is the only way to make it work correctly.

### What version of Home Assistant Core has the issue?

2021.10.5

### Additional information

Confirmed on Opera mobile iOS and Firefox Focus, latest versions, on iPhone SE (2020)

**Comment by Stooovie** [comment]
Same. This is the case with my HA since my day one in 2019.

**Comment by spacegaier** [comment]
Works fine for me on my desktop and in the Android app. So perhaps only related to Safari/Webkit?

**Comment by qoff** [comment]
You are right, I cannot confirm this behavior on Android, neither on App nor on Firefox and Chrome.

But still, I have just confirmed the issue happening a minute ago on HA 2021.11.1 on iOS 15.1 on Firefox 39.0 (6519) and on Chrome 95.0.4638.50 and on App 2021.247.

**Comment by Stooovie** [comment]
HA has several big issues on Webkit (=on iPhone and iPad as all browsers have to run webkit internally). I guess majority of HA devs are Android users so issues go unnoticed/unfixed for a long time. I am reporting these things for two years and only one got fixed so far (Automations editor not closing when clicking "leave").

**Comment by Stooovie** [comment]
> I just checked https://en.wikipedia.org/wiki/Firefox_for_iOS and you are right, this time Firefox uses Webkit. So it's clear where to search for an issue.
> 
> Interestingly, I have reported the same, very annoying issue (Automations editor not closing when clicking "leave") lately, but it was already fixed in beta version. Currently it works like it should.

all browsers on iOS use webkit. Non-webkit browsers aren't allowed at all.
