### ISSUE TITLE
The default icon shows above the entity_picture in state badge (Lovelace UI)

### ISSUE THREAD

**Issue by cofw2005** [home-assistant/frontend#10346]
### The problem

I have some of my entities set with an "entity_picture" attribute so that in the badge I can see a picture instead of default icon.
And I use Picture-Element card of lovelace UI. Some entities are showed up as state badge.

Before everything was correct. The state badge in the Picture Element card shows up with the picture. But since I upgraded to 2021.10.2, the icon shows now also above the picture, which is ugly. The picture is used as a kind of background now.
See below picture, it used to be a sunshine picture, but now there is a icon above it.
![Capture](https://user-images.githubusercontent.com/32097699/138097939-e6c00ce0-cf9f-4c95-b759-ccdee67c8591.JPG)

I don't know since which core version this became as a problem, because I upgraded from 0.115 directly to 2021.10.2.

### What is version of Home Assistant Core has the issue?

core-2021.10.2

### What was the last working version of Home Assistant Core?

0.115

### What type of installation are you running?

Home Assistant Core

### Integration causing the issue

Lovelace UI

**Comment by frenck** [comment]
Fixes in 2021.10.3 (specifically PR #10201)
