### ISSUE TITLE
No entities with "timestamp" attribute listed when using "Time" trigger in automations

### ISSUE THREAD

**Issue by Gokux** [home-assistant/frontend#10356]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If I use "time" as trigger type, no entity with the attribute "device_class: timestamp" is displayed.
When I add the entity (in my case "sensor.samsung_s10_next_alarm" manual in the field or YAML the automation work. So ist seems frontend related issue.

### Describe the behavior you expected

When I use "time" as trigger type, all entities with the attribute "device_class: timestamp" should be displayed.

### Steps to reproduce the issue

1. Create/edit a automation.
2. Choose trigger type "Time" and check "Value of a date/time helper"
3. In "At time" field no entities found.

### What version of Home Assistant Core has the issue?

core-2021.10.6

### In which browser are you experiencing the issue with?

Chrome, Firefox, Android App

### Which operating system are you using to run this browser?

Windows 10/11

### State of relevant entities

```txt
Local Time: Thu Oct 21 17:00:00 GMT+02:00 2021
Package: com.android.providers.calendar
Time in Milliseconds: 1634828400000
friendly_name: Samsung S10 Next Alarm
icon: mdi:alarm
device_class: timestamp
```

**Comment by johansmitsnl** [comment]
This issue is still present in version `2021.12.7`, it also doesn't work anymore when I just set it.

**Comment by slarti42** [comment]
Would be nice to have an offset option in the UI for this as well. Like in the sun trigger. Would save a lot of time on template calculations.

**Comment by Gokux** [comment]
It still does not work (version 2022.4.7).

**Comment by filmkorn** [comment]
This is still an issue in 2022.9.6.

**Comment by Bluehawk83** [comment]
Still an issue in 2022.11.1

**Comment by bruvv** [comment]
This is as designed, when you set an alarm the entity is filled with a time and will be shown. If you did not set an alarm the entity is "unavailable" and will be hidden from the UI.

**Comment by karwosts** [comment]
> This is as designed, when you set an alarm the entity is filled with a time and will be shown. If you did not set an alarm the entity is "unavailable" and will be hidden from the UI.

If you see this line it does seem like the schema only accepts input_datetimes, not sensor. I know you could change the schema to be ["input_datetime", "sensor"], but then that would show all sensors, not just sensors with timestamp class. Not sure how that could be filtered based on class. 

https://github.com/home-assistant/frontend/blob/dev/src/panels/config/automation/trigger/types/ha-automation-trigger-time.ts#L29

**Comment by karwosts** [comment]
> Would be nice to have an offset option in the UI for this as well. Like in the sun trigger. Would save a lot of time on template calculations. Setting it in YAML works for me.

Are you saying you can use an offset key with a time trigger? If so that is undocumented, the time trigger page has no mention of a possible offset. 

https://www.home-assistant.io/docs/automation/trigger/#time-trigger

**Comment by karwosts** [comment]
PR linked above adds timestamp class sensors to the time trigger entity selector.
