### ISSUE TITLE
No "Update" button when editing device area from one of it's entities

### ISSUE THREAD

**Issue by Zorgino** [home-assistant/frontend#10401]
### The problem

![image](https://user-images.githubusercontent.com/22623598/138746621-2e44b298-6aed-4bdb-9836-d90fef6765d1.png)

How to reproduce:
1. Pick an entity that comes from a device either from "Developer Tools"
2. Open entity's settings
3. Expand "Advanced settings"
4. Click "change device area"
5. Select area from a dropdown.
6. No update button appears.

### What version of Home Assistant Core has the issue?

2021.10.5

### What type of installation are you running?

Home Assistant Supervised

**Comment by spacegaier** [comment]
I am not sure how to reproduce that. When I go to an entity from a device and select an area for it, I do not get a popup as you do in your screenshot. 

Can you please double check your steps to reproduce the issue?

**Comment by prof7bit** [comment]
I can confirm this problem. I cannot figure out how to change the device area of a shelly I just installed (through the shelly integration). Somehow I managed to initially put it into the wrong area during first detection of the device but now I find myself completely unable to change the area again.

### Steps to reproduce:

#### Method A:
Find a device in the device list, click on it, click the little pencil icon (top left next to its name), a dialog pops up that has cancel and ok buttons greyed out.

#### Method B (as per the OP of this issue):
Find an entity in the entities list, click on it, click on "advanced settings", click on "change device area",
both buttons are greyed out (OP had only one button, I have two buttons and both are greyed out).

I have not found any way to change the area for the device through the web UI, the only thing I have not yet tried is hacking the device registry file manually.

![grafik](https://user-images.githubusercontent.com/1401589/152641327-95577ead-b3c0-4f4f-935a-fa19b0c37272.png)

**Comment by prof7bit** [comment]
This might be related: https://github.com/home-assistant/frontend/issues/11558

**Comment by DanielNagy** [comment]
I have the same problem.. Not sure how to reproduce it, however, one thing that hasnt been noted is that the update button is actually there, and functional, it is just invisible. If you hover over it, you can see the outline.
![image](https://user-images.githubusercontent.com/1898365/168200907-3beab1e9-54af-4f0b-80db-d0af84f18a35.png)

Not sure if this is of help, but inspecting the "invisible" update button shows this. You can see Cancel text is there for secondaryAction, but Update text is missing from primaryAction
![image](https://user-images.githubusercontent.com/1898365/168201184-3a624db8-1194-4152-a4b5-3e513c2d3aa8.png)
