### ISSUE TITLE
weird looking "new automation" pop-up

### ISSUE THREAD

**Issue by leonardpitzu** [home-assistant/frontend#10436]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating a new automation one has to select the template from a drop-down or create a empty one. The pop-up you select the template from looks weird (see the image). This has happened on all Safari versions i have tried until now (and is present in the latest stable release as well
<img width="411" alt="Screenshot 2021-10-28 at 11 05 30" src="https://user-images.githubusercontent.com/4321813/139214455-3d8c5d99-2d37-41fb-8fdb-f1ea29b1ef41.png">
).

### Describe the behavior you expected

The rectangle around the select blueprint drop-down should fit the text or simply be removed.

### Steps to reproduce the issue

1. go to Configuration/Automations
2. click "Add automation"

### What version of Home Assistant Core has the issue?

2021.12.0.dev20211028

### In which browser are you experiencing the issue with?

Safari 15.1

### Which operating system are you using to run this browser?

macOS BigSur 11.6.1

### Additional information

ha-card outlined seems to have the wrong size

**Comment by Chupaka** [comment]
I disabled cloud integration and see the same weirdness in Chrome
