### ISSUE TITLE
I do not see icons and buttons in the menu APP android frontend

### ISSUE THREAD

**Issue by jirimitura** [home-assistant/frontend#10448]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

hello, I have a problem in the application, I do not see icons and buttons in the menu, I am attaching PrintScreen. I searched for help, and did and checked everything. light PrintScreen is a website, light is a mobile app

https://user-images.githubusercontent.com/73784790/136708540-305a6298-8d76-4a98-9f2d-4bafe5b7c566.png

https://user-images.githubusercontent.com/73784790/136708543-2e76739c-6723-4cca-b4fe-14bedca4f762.png

### Describe the behavior you expected

visible icons

### Steps to reproduce the issue

1. open app , 
2. not icon , only text 
3.
...

### What version of Home Assistant Core has the issue?

2021.10.0-full

### What was the last working version of Home Assistant Core?

2021.10.0-full

### In which browser are you experiencing the issue with?

mobile Chrome 94.0.4606.85

### Which operating system are you using to run this browser?

Android

### State of relevant entities

```txt
more info :
https://github.com/home-assistant/android/issues/1765
```

### Additional information

Home Assistant Android version:
2021.10.0-full

Android version:
8.1.0

Phone model:
meizuM8
M813H
Flyme 7.1.6.0G

Home Assistant version:
Supervisor
Verze
supervisor-2021.10.6
Nejnovější verze
supervisor-2021.10.6

**Comment by jirimitura** [comment]
the error in lovelace is in the chrome browser, after uninstalling to Default everything goes ok
Suffice it to say, just uninstall the chrome update ....

**Comment by spacegaier** [comment]
To make sure I understood correctly: Going back to an older Chrome version (which one)? works fine, but Chrome 94.0.4606.85 results in no icons being rendered for you?
