### ISSUE TITLE
Yaml editor not working on iOS 

### ISSUE THREAD

**Issue by rgerbranda** [home-assistant/frontend#10450]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When trying to edit yaml in the frontend on iOS and iPadOS, the cursor is always moving to the first line when typing a letter. Editing is almost not possible.

### Describe the behavior you expected

I expect it to work like it does on Windows and MacOS browsers 

### Steps to reproduce the issue

1. Open a script
2. Go to Edit as Yaml
3. Put the cursor on line 5
4. Type a letter
5. 
note: when going to line 5 with the cursor, line 1 is still “active” in a way that it is greyed 
...
![68BB9325-DC1B-4008-954D-B3C41E42C1BF](https://user-images.githubusercontent.com/11868439/139302752-634699f4-f833-44b6-982f-3435e4259ec7.png)

### What version of Home Assistant Core has the issue?

2012.10.6

### In which browser are you experiencing the issue with?

Home assistant app / safari / chrome / Firefox 

### Which operating system are you using to run this browser?

iOS 15.1

**Comment by LarsStegman** [comment]
I have run into this problem as well on my iPad.

**Comment by LarsStegman** [comment]
No this problem has not been solved

**Comment by LarsStegman** [comment]
Seems to have been solved
