### ISSUE TITLE
Non-admins can see "Remove Entity" button on more info dialog

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#10460]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When logged in as a regular user account (no admin privileges) you can still see the button for "Remove Entity" on unavailable items (screenshot below).

![remove-entity](https://i.imgur.com/dIZEXXA.png)

The good news is, that clicking on it doesn't actually delete anything, it just fails silently. But it's confusing to show user accounts options they cannot perform.

### Describe the behavior you expected

It should be grayed out / disabled (or hidden entirely) so that regular user accounts cannot interact with the Remove Entity button. Deleting entities is an administrator only thing.

### Steps to reproduce the issue

1. Create a test user without admin privileges and login with that account
2. Click on an unavailable entity as the regular user account
3. You'll see "Remove Entity" button and can click on it (although as mentioned, it does nothing but fail silently)

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:134
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:22:53 PM (1 occurrences)
Last logged: 10:22:53 PM

[281470294778208] Error handling message: Unauthorized
```

### What version of Home Assistant Core has the issue?

2021.11.0b0

### In which browser are you experiencing the issue with?

Version 95.0.4638.54 (Official Build) (x86_64)

### Which operating system are you using to run this browser?

macOS High Sierra

**Comment by zsarnett** [comment]
not stale
