### ISSUE TITLE
Non-admin accounts show (non-functional) edit buttons on Automations, Persons, Scripts, Scenes more info dialogs

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#10461]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Related to bug https://github.com/home-assistant/frontend/issues/10460 I just opened, also tested some other more info dialogs and encountered similar issues with a few.

Regular user accounts without admin privileges can see the pencil / edit icon for **Automations, Scripts, Persons, and Scenes**. Clicking on this silently fails, because regular user accounts don't have permission to view any of the Configuration panels, it is not possible for them to edit any of this stuff.

It does print an "Unauthorized" error (under Configuration -> Logs) but that is also not accessible to regular user accounts, so they would have no idea of what they did wrong or why things didn't work.

### Describe the behavior you expected

These buttons should be hidden from regular user accounts in the same way that the settings cog button is hidden.

Here's an example of a scene from my main admin account:

![admin](https://i.imgur.com/36s0Ocw.png)

And the same scene entity when viewed on a regular user account:

![user](https://i.imgur.com/5ZPUzVq.png)

You can see that it hides the settings cog button (which is good), however it does not do the same for the edit pencil icon. The behavior should be consistent.

### Steps to reproduce the issue

1. Create a test user without admin privileges and login with that account
2. Open the more info dialog for an Automation, Script, Person, or Scene
3. You'll see the edit / pencil icon and can click it, but since regular users cannot access Config panel it fails silently

### What version of Home Assistant Core has the issue?

2021.11.0b0

### In which browser are you experiencing the issue with?

Google Chrome Version 95.0.4638.54 (Official Build) (x86_64)

### Which operating system are you using to run this browser?

macOS High Sierra

**Comment by zsarnett** [comment]
Not stale
