### ISSUE TITLE
Nest Web-RTC issue in new beta

### ISSUE THREAD

**Issue by nikwilliamson** [home-assistant/frontend#10474]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Getting back error ```Failed to start WebRTC stream: Nest API error: Error from API: 400: FAILED_PRECONDITION: Precondition check failed.: Bad Request``` when trying to view the camera stream.

### Describe the behavior you expected

See live camera

### Steps to reproduce the issue

1. Update to newest beta
2. View Web-RTC camera on front-end

### What version of Home Assistant Core has the issue?

core-2021.11.0b1

### In which browser are you experiencing the issue with?

Google Chrome 95.0.4638.69

### Which operating system are you using to run this browser?

macOS Big Sur 11.6.1

### State of relevant entities

```txt
state: streaming
-----
access_token: [REMOVED]
model_name: Camera
brand: Google Nest
frontend_stream_type: web_rtc
stream_type: web_rtc
friendly_name: Garage Camera
entity_picture: >-
  /api/camera_proxy/camera.garage_camera?token=[REMOVED]
supported_features: 2
```

### Problem-relevant frontend configuration

```yaml
aspect_ratio: 50%
camera_image: camera.garage_camera
type: picture-entity
name: Garage
entity: camera.garage_camera
```

### Javascript errors shown in your browser console/inspector

```txt
camera.front_door_2:1 GET https://nikshouse.duckdns.org:8123/api/camera_proxy/camera.front_door_2?authSig=[removed]&width=962&height=481 500 (Internal Server Error)

Image (async)
k @ styles.ts:365
_$AI @ styles.ts:365
m @ styles.ts:365
T @ styles.ts:365
_$AI @ styles.ts:365
m @ styles.ts:365
T @ styles.ts:365
_$AI @ styles.ts:365
S @ styles.ts:365
update @ styles.ts:365
performUpdate @ styles.ts:365
scheduleUpdate @ styles.ts:365
_$EC @ styles.ts:365
async function (async)
_$EC @ styles.ts:365
requestUpdate @ styles.ts:365
set @ styles.ts:365
value @ hui-image.ts:37
async function (async)
value @ hui-image.ts:37
value @ hui-image.ts:37
value @ ha-camera-stream.ts:26
performUpdate @ styles.ts:365
scheduleUpdate @ styles.ts:365
_$EC @ styles.ts:365
async function (async)
_$EC @ styles.ts:365
requestUpdate @ styles.ts:365
set @ styles.ts:365
value @ ha-camera-stream.ts:26
```

**Comment by nikwilliamson** [comment]
@allenporter if you need anything on my end, LMK. I can set up a login for you if you need to take a closer look.

**Comment by allenporter** [comment]
Have you codnrined love stream works in the home app?

I've only seen this when the device is off.

**Comment by nikwilliamson** [comment]
Yep. It’s working in the app, and OG doorbell is working fine. 

It’s got permanent power, but still a battery camera. Anything I need to do settings wise in Home/Nest?

**Comment by nikwilliamson** [comment]
@allenporter one thing to note, it’s a floodlight camera

**Comment by nikwilliamson** [comment]
Sorry. Didn’t mean to close it.

**Comment by allenporter** [comment]
Perhaps you can enable logging and we can capture the WebRTC `offer` to determine next steps. Can you add this to your `configuration.yaml`?
```
logger:
  default: info
  logs:
    google_nest_sdm.auth: debug
```

**Comment by allenporter** [comment]
Hi, is this still an issue?

**Comment by andybjackson** [comment]
I'm experiencing this same issue, so yes it probably is.

**Comment by allenporter** [comment]
Removing milestone because this was for October beta.

**Comment by allenporter** [comment]
Removing and adding back again doesn't seem like a great experience however maybe we need diagnostics to figure this out. I recommend we reopen if this happens again and get the debug info above to diagnose.
