### ISSUE TITLE
Safari Mac: quick bar loses focus

### ISSUE THREAD

**Issue by Stooovie** [home-assistant/frontend#10486]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Upon opening the Quick bar ("e" shortcut), focus is immediately lost, so I can't type the actual search. Also (separate issue), the dialogue should be dismissable with Esc, which it isn't (Esc quits the Safari fullscreen mode).

### Describe the behavior you expected

Expected to be able to type my search, as it works in other (chromium-based) browsers.

### Steps to reproduce the issue

1. open quickbar with "e"
2. type - you can't
...

### What version of Home Assistant Core has the issue?

2021.10.6

### In which browser are you experiencing the issue with?

Safari 14 and 15

### Which operating system are you using to run this browser?

macOS Big Sur 11.6.1

### Additional information

I have never had this working in Safari since the Quickbar exists. Duplicate of https://github.com/home-assistant/frontend/issues/7799

**Comment by zacwest** [comment]
This affects both 'e' and 'c'. Something pulls focus from the input field; pressing the shortcut again causes it to gain focus, sometimes successfully.

Notably: the _first_ time you ever load the page in Safari, the keyboard shortcuts will work. Any subsequent load reproduces the issue as long as it's in cache, including the error:

```
[Error] ResizeObserver loop completed with undelivered notifications.
```
