### ISSUE TITLE
Dropdown select picker not clickable in Chrome on Windows

### ISSUE THREAD

**Issue by silverl** [home-assistant/frontend#10510]
### The problem

I'm on the latest/greatest HA OS/Supervisor/Core. I've been experiencing this issue for several months across many versions of Core and Google Chrome on Windows.

When using the Chrome browser (incognito or not, no extensions) on Windows, dropdown pickers are not selectable with the mouse. 

They seem to work fine in MS Edge and Firefox, however.

I'm attaching two animated GIFs, one showing Chrome and the other Firefox.

In any browser, I can type-to-search, and use cursor keys to select the choice, hit enter to select.

But I just can't use a mouse.

# Chrome

![chrome](https://user-images.githubusercontent.com/1398276/140167181-2ed64141-3c9f-47d7-93b7-7ca05786c68d.gif)

# Firefox

![firefox](https://user-images.githubusercontent.com/1398276/140167200-c342cee1-9757-4f33-85ca-b4e38b719c2a.gif)

### What version of Home Assistant Core has the issue?

core-2021.11.0

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
No, nothing. Checked Chrome Dev tools, not spotting the issue.
```

**Comment by spacegaier** [comment]
I cannot reproduce the issue. Works fine for me on Win 10 + Chrome 95.0.4638.69.

**Comment by silverl** [comment]
I feared others might have trouble reproducing. I have tried to eliminate as many variables as possible. I've tried incognito and also creating a separate Chrome user profile with no extensions.

The fact that it works fine in MS Edge (essentially Chrome) but not Google Chrome is really baffling me.

I'd appreciate any brainstorming on what could possibly make a browser not see the mouse hovering over the dropdown list.

**Comment by silverl** [comment]
I can't repro the issue on my Chromebook which, predictably, uses the Chrome browser. Still hunting for a cause.

**Comment by silverl** [comment]
I completely uninstalled Chrome from my Windows 11 PC. I am on Win11, but this problem was happening on Win10 as well.

I noticed during uninstallation that I've been using the 32-bit version of Chrome (was installed in C:\Program Files (x86)). Started to get excited, thinking maybe upon reinstalling 64-bit, the problem would be gone.

But nope. Clean install, no profiles being used, no extensions. Just vanilla 64-bit Chrome, cleanly installed, running as Guest in Chrome, and I still have the problem.

The last variable I can think of is display drivers. I'm using the Intel CPU integrated GPU, Intel(R) UHD Graphics 630, Driver Date 10/7/2021 version 30.0.100.9955.

I'm also running dual Dell U2717D monitors.

**Comment by silverl** [comment]
I tried remoting into my PC to eliminate the graphics drivers as a potential cause. I believe this uses a separate kind of graphics driver and not the machine's main GPU (not sure of that). The problem remains.

**Comment by silverl** [comment]
I tried from a separate Windows 10 PC in the home. The second PC works fine. This eliminates something network-related (inability to pull dependencies perhaps).

So it's definitely a problem with a single PC.

**Comment by silverl** [comment]
Tried disabling Hardware Acceleration in Chrome settings, and relaunched the browser. Didn't fix it.

**Comment by yuqianma** [comment]
I've encountered this bug for months.
The workaround is using keyboard arrow instead.
As a coder myself, it's not a big problem.
I thought it's a bug would be fixed quickly next release so I try to update it today but no lucky.
It's a bit weird that this kind of basic interaction has such a plain bug.

May do some debugs but I have no time these days. So attach some info first:

MacOS Big Sur 11.6 
Chrome 95.0.4638.69

## System Health

version | core-2021.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.75
arch | x86_64
timezone | Asia/Shanghai

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4935
Installed Version | 1.13.2
Stage | running
Available Repositories | 900
Installed Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.8
disk_total | 5.2 GB
disk_used | 3.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.9.0), MariaDB (2.4.0), File editor (5.3.3), Terminal & SSH (9.2.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

**Comment by silverl** [comment]
Here's my HA system info

## System Health

version | core-2021.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.75
arch | x86_64
timezone | redacted

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4959
Installed Version | 1.16.0
Stage | running
Available Repositories | 901
Installed Repositories | 14

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | November 22, 2021, 6:00 PM
relayer_connected | true
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | true
remote_server | redacted
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.8
disk_total | 282.8 GB
disk_used | 17.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Visual Studio Code (3.6.2), Log Viewer (0.12.0), Check Home Assistant configuration (3.9.0), Terminal & SSH (9.2.1), Home Assistant Google Drive Backup (0.105.2), Node-RED (10.0.1), phpMyAdmin (0.5.0), MariaDB (2.4.0), Z-Wave JS to MQTT (0.28.0), Zigbee2mqtt (1.21.2-1), chrony (2.2.1), AirCast (3.1.1), File editor (5.3.3), Portainer (2.0.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 19
-- | --
resources | 11
views | 23
mode | storage

</details>

**Comment by Vedeneb** [comment]
Still no news on this? I also have this exact bug since months. Also using Google Chrome on Windows 11 (issue was already present on Win 10). Happens on mutliple Home Assistant instances with different installation types (Core, Container, HA OS).

There are some drop downs where it works fine, for example all drop downs on the profile page. Pretty much all others don't work though...

**Comment by Mordevolt** [comment]
Same behavior for 3 different HA installs. Very annoying (. Any workaround except arrow keys?

**Comment by silverl** [comment]
No workarounds that I can see except arrow keys, or use a different browser when using HA.

**Comment by yuqianma** [comment]
Maybe I found the cause:

chrome://flags/#enable-experimental-web-platform-features

Disable it if it's enabled and try to select again.

**Comment by Vedeneb** [comment]
Yep!! Crazy, as soon as I disable the flag everything works as excpected. 
I just hope everything else is still working, I don't remember why I enabled the flag initially.

**Comment by silverl** [comment]
WOW! This was it. THANK YOU!
