### ISSUE TITLE
See more link actually shows less

### ISSUE THREAD

**Issue by SNoof85** [home-assistant/frontend#10511]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

With the new link "See more" in entity detail "history" tab the logbook shows by default only 3 hours.
But the History tab show states changes for the whole day.

This is quite strange to click on "see more" and getting less informations without another input...

BTW: this is same behaviour on history :)

### Describe the behavior you expected

It should at least diplay the same time period

### Steps to reproduce the issue

1. Click any entity
2. Go to history tab
3. Click in front of "Logbook" the new link see more
4. Logbook shows 3 hours

### What version of Home Assistant Core has the issue?

2021.11.0

### What was the last working version of Home Assistant Core?

N/A

### In which browser are you experiencing the issue with?

Not browser related

### Which operating system are you using to run this browser?

Not browser related

### Additional information

I think as the change has been done in the frontend I opened the issue here. I'm not sure it would be relevant in core repo.
See #9717

**Comment by spacegaier** [comment]
Adding that was always planned, but in the current release the MVP version was to add the navigation option as a starting point.
