### ISSUE TITLE
History graph doesn't load after deleting a new unused input_datetime

### ISSUE THREAD

**Issue by gregbradley** [home-assistant/frontend#10515]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Created a new input_datetime helper but ended up deleting it. Now the history graph doesn't load because of a JavaScript error as it tries to load the deleted helper and reference attributes that don't exist.
![image](https://user-images.githubusercontent.com/6867679/140246394-49612be3-8f31-4e37-ac61-6dac31e96d1a.png)
![image](https://user-images.githubusercontent.com/6867679/140246454-6605f9da-6dae-41c2-b25f-78ac05cd5e3f.png)

### Describe the behavior you expected

History graph should load.

### Steps to reproduce the issue

1. Create input_datetime helper.
2. Wait a bit but don't use the helper.
3. Delete the helper.
4. Try to access the history graph.

### What version of Home Assistant Core has the issue?

core-2021.11.0

### In which browser are you experiencing the issue with?

Google Chrome 94.0.4606.71

### Which operating system are you using to run this browser?

Windows 11

### Javascript errors shown in your browser console/inspector

```txt
Uncaught (in promise) RangeError: Invalid time value
    at c (0060b265.js:formatted:176)
    at l (0060b265.js:formatted:514)
    at 055925ab.js:1
    at 055925ab.js:1
    at Array.forEach (<anonymous>)
    at v (055925ab.js:1)
    at HTMLElement.<anonymous> (b081bb25.js:1)
    at l (core.4074643f.js:1)
    at Generator._invoke (core.4074643f.js:1)
    at Generator.next (core.4074643f.js:1)
```

**Comment by Nenodema** [comment]
Same problem here..

**Comment by Sholofly** [comment]
Same here, not related to browser_mod so it seems..

**Comment by travisrlh** [comment]
I added the shelly integration, added, deleted then added the device again (second time was after configuring device with username/password), and now I'm getting the same error when I look at the history page. 

`Uncaught (in promise) RangeError: date value is not finite in DateTimeFormat.format()
    s mwc-circular-progress-base.ts:156
    d mwc-circular-progress-base.ts:156
    p ha-chart-base.ts:20
    p ha-chart-base.ts:20
    p ha-chart-base.ts:20
    value a5e8cd62.js:54
mwc-circular-progress-base.ts:156
`
I removed the older device from the entities page but still getting the error.

**Comment by ncwp** [comment]
Same error here, started happening a couple hours after adding a Shelly switch. No browser_mod here.
```mwc-circular-progress-base.ts:156 Uncaught (in promise) RangeError: Invalid time value
    at s (mwc-circular-progress-base.ts:156:1)
    at d (mwc-circular-progress-base.ts:156:1)
    at ha-chart-base.ts:20:1
    at ha-chart-base.ts:20:1
    at Array.forEach (<anonymous>)
    at p (ha-chart-base.ts:20:1)
    at r.value (ha-panel-history.ts:111:1)```

**Comment by spacegaier** [comment]
I cannot reproduce the error, and I think that is because this PR already added some safeguards: https://github.com/home-assistant/frontend/pull/10237

However, that PR should have been I think part of 2021.11 which however is the reported problematic release according to the OP.

**Comment by spacegaier** [comment]
@ncwp Are you really talking about the same issue? How does a Shelly switch related to an input_datetime issue?

**Comment by ncwp** [comment]
@spacegaier I have no idea if it is actually related, but my history page has always been working fine, until today when I all of a sudden get that error, an hour or 2 after adding my first Shelly switch. And seeing as @travisrlh mentioned Shelly I figured maybe it's related and I should at least mention it.
It could of course be a total coincidence.

**Comment by dszabolcs** [comment]
I faced the same issue. When I renamed some entities (with renamed entity_id), and deleted devices from the HA, the history and logbook (also) is broken with **Range: Invalid Time Error.** 

I had to purge the DB to resolve this issue which is not so funny, because most data are lost in this case.

Please check this issue and solve it.
