### ISSUE TITLE
ha-icon-button no longer seems to show icons

### ISSUE THREAD

**Issue by mortenmoulder** [home-assistant/frontend#10521]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After 2021.11 update, all my custom cards from various integrations that uses the ha-icon-button no longer seems to work. I don't get any errors in the console, but I also don't see any obvious places the actual icon is being set (in the HTML).

### Describe the behavior you expected

I expect ha-icon-button to show the icon just like in the previous 2021.10 update.

### Steps to reproduce the issue

1. Install a card such as https://github.com/denysdovhan/purifier-card which uses `<ha-icon-button icon="hass:power"` for example
2. See that the card has no buttons

### What version of Home Assistant Core has the issue?

core-2021.11.0

### What was the last working version of Home Assistant Core?

core-2021.10.x

### In which browser are you experiencing the issue with?

Chrome latest (Incognito also tried)

### Which operating system are you using to run this browser?

Windows 11

### Additional information

The following 3 images shows 3 cards that all use the `<ha-icon-button>` element. Ignore the vacuum cleaner not showing any text - the author has not updated the new entities yet.

![image](https://user-images.githubusercontent.com/1304665/140282381-be31eb9c-9b90-44f0-9c99-b413a9abea1a.png)

![image](https://user-images.githubusercontent.com/1304665/140282419-2aa38f9e-ae62-4bbd-ab70-b1d1cffc1ca5.png)

![image](https://user-images.githubusercontent.com/1304665/140282450-0107145a-d236-4bfe-bb13-2a55b965481f.png)

**Comment by ludeeus** [comment]
This is correct <https://github.com/home-assistant/frontend/blob/dev/src/components/ha-icon-button.ts#L10>.
`ha-icon-button` does not support `icon` anymore, you have to supply the icon SVG path as  `path` or use `ha-icon` in the default slot of `ha-icon-button`

**Comment by mortenmoulder** [comment]
Hi @ludeeus and thanks for the reply. Sorry to ask, but isn't this a breaking change? I don't see it mentioned anywhere as a breaking change in the 2021.11 update. 

I read every update carefully, so I can decide whether or not I want to upgrade immediately or wait for the developers of the cards to update them. This **is** a breaking change that makes me want to revert to 2021.10 until they have all been fixed, because I'm basically clueless, when I don't know what my buttons do.

**Comment by ludeeus** [comment]
Yes but no. We don't support using our components in custom cards, while it might work now you should not do it.
Read more here <https://developers.home-assistant.io/blog/2020/10/02/lazyMoreInfo>

**Comment by mortenmoulder** [comment]
@ludeeus Okay, I see. I'll create an issue on all 3 repositories I know of, that I currently use, that uses the `ha-icon-button`. Thanks for clarifying.

**Comment by Junkbite** [comment]
Sweet, I'm going to save this thread so when I mention how HA devs don't care about their custom card creators who home assistant would be nothing without, I can show them this and why so many custom cards are abandoned - HA devs purposely make it hard for us. 

I was so disappointed when the big version 1.0 was announced hoping this would be the end of constant breaking changes but when I saw a last minute change to make the version system by month, I knew HA devs would continue their poor development practices. 👎

**Comment by mortenmoulder** [comment]
@Junkbite I agree that this is bad practise from the Home Assistant team. They could easily search for "ha-icon-button" on Github and find a lot of cards that use it. They should not have made a pretty significant breaking change, without notifying the entire community (or at least the developers of said cards).

**Comment by Junkbite** [comment]
Sadly, I've seen this play out many times. HA devs have made it clear, they don't care about custom card/integration creators. In their mind, if you cared about HA, you'd contribute to core.

**Comment by balbulator** [comment]
The update broke a lot of maps, I don't even know who and where to write now. Thanks to the team Home Assistant
