### ISSUE TITLE
Cannot add and configure integrations

### ISSUE THREAD

**Issue by lwh201314** [home-assistant/frontend#10520]
### The problem

Clicking the Add integration button, the integration options button, and the Configure integration button do not respond.
The following is a browser console error report.

### What version of Home Assistant Core has the issue?

20211101

### What was the last working version of Home Assistant Core?

20211007

### What type of installation are you running?

Home Assistant Core

### Anything in the logs that might be useful for us?

```txt
ha-svg-icon.ts:5 
        
       Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-slider" has already been used with this registry
    at http://192.168.1.209:8123/frontend_latest/app.707ed561.js:1243:6875
    at http://192.168.1.209:8123/frontend_latest/app.707ed561.js:1243:6890
    at a (http://192.168.1.209:8123/frontend_latest/app.707ed561.js:850:118198)
    at Object.69916 (http://192.168.1.209:8123/frontend_latest/c75951d1.js:146:3679)
    at u (http://192.168.1.209:8123/frontend_latest/app.707ed561.js:1243:29185)
    at Object.39715 (http://192.168.1.209:8123/frontend_latest/070d5e5c.js:81:42)
    at u (http://192.168.1.209:8123/frontend_latest/app.707ed561.js:1243:29185)
    at Object.68331 (http://192.168.1.209:8123/frontend_latest/070d5e5c.js:266:129)
    at u (http://192.168.1.209:8123/frontend_latest/app.707ed561.js:1243:29185)
    at Module.63118 (http://192.168.1.209:8123/frontend_latest/2f121cd3.js:178:9127)
```

**Comment by lwh201314** [comment]
Logger: frontend.js.latest.202111030
Source: components/system_log/__init__.py:190
First occurred: 2021年11月4日 21:12:37 (13 occurrences)
Last logged: 24:37:29

http://192.168.1.209:8123/config/devices/device/8b5fdb8b15f2041d4fdf805562a7e167:0:0 Uncaught
http://192.168.1.209:8123/lovelace/0:0:0 Uncaught
http://192.168.1.209:8123/config/devices/device/5872c532fd4effd9f22aa44a1b410613:0:0 Uncaught
http://192.168.1.209:8123/lovelace/edge:0:0 Uncaught
https://hassv6.136059.xyz:21234/config/integrations:0:0 Uncaught

**Comment by lwh201314** [comment]
Logger: frontend.js.latest.202111030
Source: components/system_log/__init__.py:190
First occurred: 2021年11月4日 21:12:37 (13 occurrences)
Last logged: 24:37:29

http://192.168.1.209:8123/config/devices/device/8b5fdb8b15f2041d4fdf805562a7e167:0:0 Uncaught
http://192.168.1.209:8123/lovelace/0:0:0 Uncaught
http://192.168.1.209:8123/config/devices/device/5872c532fd4effd9f22aa44a1b410613:0:0 Uncaught
http://192.168.1.209:8123/lovelace/edge:0:0 Uncaught
https://xxx.xxxx.xxx:xxxx/config/integrations:0:0 Uncaught

**Comment by joscha82** [comment]
Can reproduce in Home Assistant 
 2021.12.3 / Frontend version: 20211215.0 only in Microsoft Edge 96.0.1054.57.

Google Chrome 96.0.4664.110 and Android 12 WebUI are working fine.

**Comment by joscha82** [comment]
Edge Version 96.0.1054.62 seems to have fixed the issue for me (or the update process od edge Browser itself)

**Comment by lwh201314** [comment]
It happens almost every time, and I need to refresh it several times until the Add Integration button clicks.This happened to me using edge96.0.1054.62, chrome97.0.4692.56 and android apps.The latest version from 20211101 to now is the same problem.

**Comment by ciB89** [comment]
I had this issue occur when using the tuya v2 integration - but this might also be unrelated/coincidence.

**Comment by spacegaier** [comment]
I assume you are using custom cards and the issue probably stems from one of them, since it looks like something else was already registering `mwc-slider` before the HA frontend itself could. 

To verify you would need to remove all custom cards temporary, to narrow down which card causes the issue and then raise it with the card's author.
