### ISSUE TITLE
Reloading a local addon results in a 404

### ISSUE THREAD

**Issue by fabiopedrosa** [home-assistant/frontend#10534]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I'm running a local addon called `network-map`

If I open its WebUI on the `supervisor>container` page, I get redirected to this URL: `http://<local ip>:8123/hassio/ingress/local_network-map`

If I refresh the webpage, the page loads up fine.

If I open its WebUI using the sidebar, I get redirected to this URL: `http://<local ip>:8123/local_network-map/dashboard`

If I refresh this page, it just shows a `404 Not found` page

### Describe the behavior you expected

Being able to refresh the addon page.

### Steps to reproduce the issue

Explained above

### What version of Home Assistant Core has the issue?

all

### What was the last working version of Home Assistant Core?

never worked

### In which browser are you experiencing the issue with?

Chrome 88

### Which operating system are you using to run this browser?

Windows

**Comment by spacegaier** [comment]
Does `http://<local ip>:8123/local_network-map/dashboard` work the first time from the sidebar and only a refresh then gives you a 404?

**Comment by fabiopedrosa** [comment]
Closing, as this has been fixed.
