### ISSUE TITLE
Icon Picker - UI - list not consistently alphabetical

### ISSUE THREAD

**Issue by doddyprodger** [home-assistant/frontend#10532]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using the excellent new Icon Picker, the dropdown appears to show icons in alphabetical order, however once you scroll to 'z', it starts again at 'a'. Effectively a second alphabetical list.

### Describe the behavior you expected

All icon assets listed starting with A and ending with Z at the bottom.

### Steps to reproduce the issue

1. Go to Dashboard
2. Edit an entity / card to change icon
3. click Icon picker dropdown
4. List of available icons displayed.
5. Scroll down to half way through list and notice when it gets to 'z', starts again at 'a'.

### What version of Home Assistant Core has the issue?

core-2021.11.0

### In which browser are you experiencing the issue with?

95.0.1020.40

### Which operating system are you using to run this browser?

Windows 11

**Comment by bramkragten** [comment]
This is by design, home automation icons are at the top.

**Comment by doddyprodger** [comment]
Thanks @bramkragten - Just for clarity, see attached example using hue icons in list:

![hass-iconpicker](https://user-images.githubusercontent.com/90989109/140405145-77dabab4-0dce-49e8-b5a0-c01f3ee77e37.png)

**Comment by arallsopp** [comment]
Are they perhaps the hue "native" icons as featured in the hue app, followed by the hue custom drawn icons, created in response to community PRs?

If so, I should probably alpha sort the entire script's icons.

**Comment by doddyprodger** [comment]
thanks @arallsopp - confirmed fixed :))
