### ISSUE TITLE
Media control card not displayed

### ISSUE THREAD

**Issue by stezak77** [home-assistant/frontend#10536]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since version 2021.11, media control card is not displayed anymore in the front end.
Logs don't show any related error.

### Describe the behavior you expected

Media control card should be displayed

### Steps to reproduce the issue

Configure a media control card in the front end, for example:
```
type: media-control
entity: media_player.home_4_google_home
```

### What version of Home Assistant Core has the issue?

core-2021.11.0

### In which browser are you experiencing the issue with?

Google Chrome 95.0.4638.54, Microsoft Edge 88.0.705.81

### Which operating system are you using to run this browser?

Windows 10

**Comment by ranrinc** [comment]
Got the same problem which will be able to solve if we can edit lovelace which in this case is not available for update. Furthermore new insert without 'type: media-control' will solve it

with media-control
![Screen Shot 2021-11-05 at 5 44 35 PM](https://user-images.githubusercontent.com/15801696/140499076-bd3f7b12-6ff2-4716-a014-d81652a25158.png)

without media-control
![Screen Shot 2021-11-05 at 5 47 40 PM](https://user-images.githubusercontent.com/15801696/140499191-29ce4a9f-48e0-49b9-b1e5-348fb378c8a2.png)

**Comment by spacegaier** [comment]
If the issue also appears in private browsing mode, please try without the custom cards, since chances are that those interfere as they were not yet updated for the latest HA frontend version.

**Comment by stezak77** [comment]
> If the issue also appears in private browsing mode, please try without the custom cards, since chances are that those interfere as they were not yet updated for the latest HA frontend version.

yes, the issue also appears in private mode and with no custom cards on the view

**Comment by spacegaier** [comment]
I am not sure if it is enough to just not have any custom cards on the view or if they need to go completely to rule them out. Could you temporarily uninstall them?

Judging by the browser error log something seems to already register "mwc-linear-progress" and thus HA cannot do the same which however HA needs for the media player card.

**Comment by drjjr2** [comment]
I am having the same issue. Also when trying to add a new media control card to a new blank dashboard the visual editor is not displayed and the card information is blank. My dashboard with the media control cards only has media control cards.

**Comment by bramkragten** [comment]
It is caused by a custom card that registers `mwc-linear-progress` which is also used by Home Assistant. The custom card should not register `mwc-linear-progress` it self.

You have to find the card that uses `mwc-linear-progress` and create an issue for it.

**Comment by drjjr2** [comment]
> It is caused by a custom card that registers `mwc-linear-progress` which is also used by Home Assistant. The custom card should not register `mwc-linear-progress` it self.
> 
> You have to find the card that uses `mwc-linear-progress` and create an issue for it.

Turns out that for some reason HACS wasn't showing me the 6.0.0 version of **atomic-calendar-revive** which fixes this issue. Had to uninstall atomic-calendar-revive, restart HA and then I could see the new version.
Media control cards now properly display.

**Comment by stezak77** [comment]
In my case, after removing custom:bar-card, the media-control cards are shown again
