### ISSUE TITLE
Core 2021.11 Lovelace

### ISSUE THREAD

**Issue by FrankSchoene** [home-assistant/frontend#10545]
### The problem

After migration to 21.11 lovelace was not loading at all. Undefined problem with upper/lower case definitions.

This migration was done on a fresh (yesterday) installed Raspi4. So no customisations at all. Integration that were installed are
HUE
Google Cast
HACS
Miele
Opensprinkler
Synology
and a definition for a Yamaha receiver in config.yaml

Thats it. Backup/Fallback to core-2021.10.7 worked.

### What version of Home Assistant Core has the issue?

2021.11

### What was the last working version of Home Assistant Core?

2021.10.7

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Good question. This was a general failure regarding to the log.

### Anything in the logs that might be useful for us?

```txt
NO.
```

**Comment by spacegaier** [comment]
Please provide more details. What exactly are the errors you get in the browser log? So far we have not really anything to to go on.

**Comment by to-rhis** [comment]
I have almost the same problem, but only when using firefox. Chrome based webreaders work, (not tested with others).
It just open and wont load in firefox, just the loading wheel is showing, but if i click on an other "not working bokmark" and stop that load, it pop back and it starts to work normal again. Although time is still 1 hours behind in time..  (also only in firefox).
I live in Sweden

**Comment by spacegaier** [comment]
@to-rhis Any errors in your browser log? We need more to go on, to pinpoint a potential issue here.

**Comment by bramkragten** [comment]
Probably related to  https://github.com/home-assistant/frontend/issues/10548

**Comment by to-rhis** [comment]
It was related to old versions of Firefox. I had gone back to esr 78.X because of the Proton interface. Now I updated anyway to ESR 91.3 and problems has gone. Using .css to get rid of the too big "drop menus" instead! 
So it is depending on an old Firefox version.  So I think this tread can be closed now also!
