### ISSUE TITLE
"Invalid timeZoneName" – Intl.DateTimeFormat polyfill of Format.JS probably not initialized correctly

### ISSUE THREAD

**Issue by Jpsy** [home-assistant/frontend#10548]
### The problem

**Conditions to reproduce:**

- HA 2021.11.x
- Browser without `Intl.DateTimeFormat / timeZoneName` support, i.e Fully Kiosk Browser, or Firefox 78.15.0 as provided on Debian.
- Time zone in HA set to Europe/Berlin

**Problem:**

On browsers that do not support the `options.timeZoneName` feature of the `Intl.DateTimeFormat` object, a polyfill kicks in that HA imports from Format.JS.
HA initializes this polyfill (correctly) with the time zone that is set in the config of HA, by calling a special method `__setDefaultTimeZone()` of the polyfill. 

But this initialization step throws an error `"Invalid timeZoneName"` with most standard time zone settings (like "Europe/Paris", "Europe/Brussels",  "Europe/Berlin"). Some time zones seem to work (i.e. "Europe/Oslo") but probably only due to internal cross mappings within Format.JS.

The result is that on browsers without `Intl.DateTimeFormat` support the loading of the HA frontend stalls with the HA icon and the message "Loading data". The console at this point shows the error "Invalid timeZoneName" (see screenshot).

The reason for the polyfill failing is probably that another initialization step is not taken:
According to the [docs of Format.JS](https://formatjs.io/docs/polyfills/intl-datetimeformat/) a timezone list must be imported as well after the polyfill, like so:
```
import '@formatjs/intl-datetimeformat/polyfill'
import '@formatjs/intl-datetimeformat/add-all-tz'
```
When debugging the problem I found that the internal timezone list in the polyfill is empty. 
This is why I suspect that the second import (add-all-tz) has not taken place.

Here is a screenshot of a stalling system and the corresponding console output:

![image](https://user-images.githubusercontent.com/1806058/140557608-fd1ddcdc-a114-4d50-ab9c-4136489ad410.png)

### What version of Home Assistant Core has the issue?

core-2021.11.1

### What was the last working version of Home Assistant Core?

core-2021.10.7

### What type of installation are you running?

Home Assistant OS

### Example YAML snippet

```yaml
homeassistant:
  time_zone: Europe/Berlin
```

**Comment by Jpsy** [comment]
It looks like the `intl-datetimeformat` polyfill was definitely introduced on the way to 202111 in commit https://github.com/home-assistant/frontend/commit/1bccbd41738b655d99b318be3f58690907aa598b.

As suspected the commit only adds the dependency `intl-datetimeformat/polyfill` but not `intl-datetimeformat/add-all-tz`.

**Comment by Nardol** [comment]
I have this issue using Firefox 78.15.0, the version provided on Debian.
When logging in interface stays to "Loading data".
Sometimes, if I put the tab in the background and browser loses the connection, when coming back the connection is successful.
But when the interface stucks on "loading data", I have:
```
Uncaught (in promise) RangeError: Invalid timeZoneName
    __setDefaultTimeZone http://homeassistant.local:8123/frontend_latest/94a4fdf6.js:1
    hassConnected http://homeassistant.local:8123/frontend_latest/app.707ed561.js:1243
    s http://homeassistant.local:8123/frontend_latest/core.bba75532.js:1
    c http://homeassistant.local:8123/frontend_latest/core.bba75532.js:1
94a4fdf6.js:1:23438
```
In the browser console.

**Comment by Jpsy** [comment]
The basic DateTimeFormat object has been introduced in Firefox with version 29. But many methods of the object were added later. The following functions and parameters were added after 78:
* options.dateStyle
* options.dayPeriod
* options.fractionalSecondDigits
* options.timeStyle
* options.timeZoneName
* formatRange
* formatRangeToParts
(according to https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat)

So options.timeZoneName is one of those that were introduced later and it's obviously the part where the polyfill throws.

It is surely good to know that FF78 is an easy way to reproduce the issue.

**Comment by balloob** [comment]
Thanks for the thorough analysis + fix. We'll get it addressed and added to the next hot fix.
