### ISSUE TITLE
Code editor is unusable on iOS

### ISSUE THREAD

**Issue by Stooovie** [home-assistant/frontend#10547]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Editing Lovelace code with the cards' Code editor on iOS is impossible. Every keystroke anywhere makes the cursor jump to the very first place in the input field.  

### Describe the behavior you expected

Expected to be able to edit the code. 

### Steps to reproduce the issue

1. Edit dashboard 
2. Edit any card, go to Code editor
3. Type

### What version of Home Assistant Core has the issue?

2021.11.1

### What was the last working version of Home Assistant Core?

2021.9.x

### In which browser are you experiencing the issue with?

Safari, Edge, HA app

### Which operating system are you using to run this browser?

IOS 15.1

### Additional information

Only happens on mobile.

**Comment by GirzzlyAK** [comment]
I have been experiencing this too. At the moment, editing cards in iOS is impossible for me within the HA mobile app. I can place the cursor, but as soon as I type, the cursor jumps to position 1, top line, and enters the text there. Have found no workaround.

**Comment by bpottle1** [comment]
I have this issue as well. Based on what I've read and seen previously, it is an upstream issue with the editor (not sure on all the specifics but this is the issue: [codemirror issue #414](https://github.com/codemirror/codemirror.next/issues/414)).

I'm not skilled enough to know much about this and how to fix it, but does anyone know if it's possible to use the type of editor that the File Editor add-on uses? That one has always worked on mobile for me through any updates. Not sure if it's possible though.

**Comment by hagenuck1** [comment]
Issue is fixed when editing Lovelace cards in 2021.12.0b0. 
But it’s still present there in the options field when editing add on configurations.
