### ISSUE TITLE
HACS Addon suddenly appear and wont be uninstall

### ISSUE THREAD

**Issue by ranrinc** [home-assistant/frontend#10551]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This uninstall addon suddenly appear and wont go away. Uninstall and restart work sometimes, however it will return. The addon create problem on lovelace disappearing under media-control.

The Addon Atomic Calendar Revive

### Describe the behavior you expected

Addon being uninstall/not install should not be install automatically.

### Steps to reproduce the issue

1. Starts HA - Supervised
2. Check HACS
3. It say unloaded addon on lovelace
4. The addon seems to install with unloaded issue
..
On HACS startup screen
![aaf27f7de76393a4f7c66dd7ffc9670f1ab2a94a](https://user-images.githubusercontent.com/15801696/140596849-31a7d0b6-cd47-4f1d-a58c-eb6364e9f3ec.jpg)

On Frontend addon
![66fda2d6eb892c74dfa0afe28c937718e9facd02](https://user-images.githubusercontent.com/15801696/140596852-a7f7b25d-bbc9-4b25-a4b0-a2f3c3b52108.jpg)
.

### What version of Home Assistant Core has the issue?

2021.11.1

### What was the last working version of Home Assistant Core?

2021.10.7

### In which browser are you experiencing the issue with?

Brave, Chrome, Firefox, Edge

### Which operating system are you using to run this browser?

Debian 11

### State of relevant entities

```txt
HACS which cause issue on lovelace
```

### Problem-relevant frontend configuration

```yaml
media-control
```

**Comment by spacegaier** [comment]
That sounds like an issue for the HACS repository.

**Comment by ludeeus** [comment]
Not really, but this is certainly not the place.
<https://hacs.xyz/docs/faq/status_not_loaded>
<https://hacs.xyz/docs/issues>
