### ISSUE TITLE
Cannot restore a backup from the Onboarding screen with fresh import of HAOS_OVA-6.6

### ISSUE THREAD

**Issue by CleverCompiler** [home-assistant/frontend#10568]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I downloaded the latest ova file from Home-Assistant.io. (https://github.com/home-assistant/operating-system/releases/download/6.6/haos_ova-6.6.ova) and after importing it into my XCP-NG host HASS OS starts correctly.  Browsing to the IP Address assigned to the new VM presents me with the onboarding.html page which seems to have a bug that is preventing me from clicking the "Alternatively you can restore from a previous backup" link.  When I attempt to click to restore my backup I'm told that the Name field is required.  Filling in the Name field removes this error but I'm still unable to open the restore backup lin
![Screenshot_20211107_112248](https://user-images.githubusercontent.com/2355250/140659322-75d3c91c-c07e-4766-a847-51466859de58.png)
![Screenshot_20211107_113911](https://user-images.githubusercontent.com/2355250/140659396-72d86a5f-6797-4ff0-84e1-910ba507b81b.png)
k.

### Describe the behavior you expected

Clicking the backup restore link should bypass the Required field validations and take the user to the page to upload the tar file.

### Steps to reproduce the issue

1. Import haos_ova-6.6.ova and start the VM.
2. Browse to  http://<vmipaddress>:8123
3. Click the link to restore from backup and observer name required error.
4. Fill in the name field and click restore from backup again.
5. Observe that the user is still unable to restore a backup tar.

### What version of Home Assistant Core has the issue?

2021.11.1

### In which browser are you experiencing the issue with?

Google Chrome Version 95.0.4638.54 and Vivaldi	4.3.2439.63

### Which operating system are you using to run this browser?

Latest Manjaro KDE

### State of relevant entities

```txt
First boot.
```

### Problem-relevant frontend configuration

```yaml
Fresh install
```

### Javascript errors shown in your browser console/inspector

```txt
2dialog-hassio-backup-upload.ts:57 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'localize')
    at HTMLElement.value (dialog-hassio-backup-upload.ts:57)
    at HTMLElement.update (styles.ts:365)
    at HTMLElement.performUpdate (styles.ts:365)
    at HTMLElement.scheduleUpdate (styles.ts:365)
    at HTMLElement._$EC (styles.ts:365)
value @ dialog-hassio-backup-upload.ts:57
update @ styles.ts:365
performUpdate @ styles.ts:365
scheduleUpdate @ styles.ts:365
_$EC @ styles.ts:365
async function (async)
value @ hassio-upload-backup.ts:55
o @ ha-settings-row.ts:6
async function (async)
o @ ha-settings-row.ts:6
(anonymous) @ ha-settings-row.ts:6
i @ paper-tooltip.js:233
value @ onboarding-restore-backup.ts:43
handleEvent @ styles.ts:365
dialog-hassio-backup-upload.ts:57 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'localize')
    at HTMLElement.value (dialog-hassio-backup-upload.ts:57)
    at HTMLElement.update (styles.ts:365)
    at HTMLElement.performUpdate (styles.ts:365)
    at HTMLElement.scheduleUpdate (styles.ts:365)
    at HTMLElement._$EC (styles.ts:365)
value @ dialog-hassio-backup-upload.ts:57
update @ styles.ts:365
performUpdate @ styles.ts:365
scheduleUpdate @ styles.ts:365
_$EC @ styles.ts:365
async function (async)
_$EC @ styles.ts:365
requestUpdate @ styles.ts:365
set @ styles.ts:365
value @ hassio-upload-backup.ts:55
o @ ha-settings-row.ts:6
async function (async)
o @ ha-settings-row.ts:6
(anonymous) @ ha-settings-row.ts:6
i @ paper-tooltip.js:233
value @ onboarding-restore-backup.ts:43
handleEvent @ styles.ts:365
2dialog-hassio-backup-upload.ts:57 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'localize')
    at HTMLElement.value (dialog-hassio-backup-upload.ts:57)
    at HTMLElement.update (styles.ts:365)
    at HTMLElement.performUpdate (styles.ts:365)
    at HTMLElement.scheduleUpdate (styles.ts:365)
    at HTMLElement._$EC (styles.ts:365)
```

### Additional information

I'm still able to create a new user, sign in and install the Samba plugin, Upload the tar file and restore it so there is a work around for this bug.

**Comment by dereitz** [comment]
+1 for this being a bug
