### ISSUE TITLE
"User Input Malformed" error when re-configuring integrations in the front end GUI

### ISSUE THREAD

**Issue by randomlyalex** [home-assistant/frontend#10567]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On a few Integrations for me:
- adaptive-lighting: https://github.com/basnijholt/adaptive-lighting/issues/213#issuecomment-962667659
- programmable_thermostat: https://github.com/custom-components/climate.programmable_thermostat/issues/42

and for others:

- Homekit: https://community.home-assistant.io/t/homekit-error-user-input-malformed/353390/9

They allow to re-configure via the front end due to a GUI bug I think, there is some sort of non-front-end-existing field in the list being tracked that I can't edit, so I can't save the changes.
![image](https://user-images.githubusercontent.com/42281043/140659487-cf3221cb-00b9-434b-8153-b652aed466f7.png)

Rolling back and the inputs look slightly different too? 

### Describe the behavior you expected

I expected to be able to edit the fields in the pop up when configuring an integration, and so long as these fields are valid and complete, then to be able to save the changes.

### Steps to reproduce the issue

1. Install programmable thermostat, confirm it works fine.
2. Try and update the integration configuration, by clicking configure in the front end
3. Change any value in that form
4. click submit
...

### What version of Home Assistant Core has the issue?

2011.11

### What was the last working version of Home Assistant Core?

2011.10

### Which operating system are you using to run this browser?

Home Assistant OS

**Comment by Boggie** [comment]
Also breaks the adaptive lighting integration

**Comment by randomlyalex** [comment]
thanks, sorry @bramkragten I searched and couldn't find anything.
