### ISSUE TITLE
HASSIO 6.6 fresh install onboarding - restore from backup not working

### ISSUE THREAD

**Issue by buzzdev** [home-assistant/frontend#10560]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On new/fresh install of hassio 6.6 on rpi4 instead of creating an account i want to restore from previous backup.
Install image downloaded: https://github.com/home-assistant/operating-system/releases/download/6.6/haos_rpi4-64-6.6.img.xz
Local onboarding URL: http://192.168.0.120:8123/onboarding.html

Clicking on the "Alternatively you can restore from a previous backup." nothing happens.
Error in the browser console:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'localize') in dialog-hassio-backup-upload.ts:57

Tested with Brave, Chrome and Safari browsers - same error.

<img width="1438" alt="Screenshot 2021-11-06 at 21 30 06" src="https://user-images.githubusercontent.com/6644151/140623525-087dee32-2efc-44f1-839d-29c4ba2125e6.png">

<img width="1440" alt="Screenshot 2021-11-06 at 21 36 08" src="https://user-images.githubusercontent.com/6644151/140623529-ee93c764-a115-4b36-a6e0-c2bea6cb99f5.png">

### Describe the behavior you expected

I expect something like backup upload dialog and no error.

### Steps to reproduce the issue

1. Put hassio 6.6 image on SD card
2. Boot rpi4 with the SD card and wait until finished booting
3. On the onboarding screen click "Alternatively you can restore from a previous backup."
...

### What version of Home Assistant Core has the issue?

6.6

### In which browser are you experiencing the issue with?

Brave Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (x86_64), Safari Version 15.1 (16612.2.9.1.30, 16612)

### Which operating system are you using to run this browser?

macOS Big Sur 11.6.1 (20G224)

### Javascript errors shown in your browser console/inspector

```txt
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'localize') in dialog-hassio-backup-upload.ts:57
```

**Comment by ludeeus** [comment]
Fixed in https://github.com/home-assistant/frontend/pull/10523

**Comment by buzzdev** [comment]
@ludeeus Hi Joakim, i understand that it is fixed, but how does that fix my situation? Do you know, when it is going to be released in official image?
Thank you

**Comment by ludeeus** [comment]
No I don't, if we need help with workarounds, try reaching out on the [forums](https://community.home-assistant.io/) or [discord](https://discord.gg/c5DvZ4e)
