### ISSUE TITLE
Icons of buttons not showing

### ISSUE THREAD

**Issue by TheMrPhantom** [home-assistant/frontend#10566]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The icons of buttons (entity buttons) are not showing anymore in my Dashboards.
It is only the text of the button showed, the buttons also have the size of only the text.
It is only on my old ios device afaik.

### Describe the behavior you expected

Display icons

### Steps to reproduce the issue

Create entity button in dashboard

### What version of Home Assistant Core has the issue?

core-2021.11.1

### What was the last working version of Home Assistant Core?

core-2021.9.7 (last known working version)

### In which browser are you experiencing the issue with?

safari

### Which operating system are you using to run this browser?

iOS 9.x

**Comment by kliphleon** [comment]
I can confirm this as well. Icons were showing on 2021.10.7.
2021.11.3 still has this issue. I'm on iOS 9.3.5

![ipad](https://user-images.githubusercontent.com/86487951/141652650-c2355bd2-69fb-461e-9fa2-6baa2b7dd756.jpeg)
.

**Comment by groenmarsmannetje** [comment]
I also have this but I am on:
HassOs 2021.11.4
Companion app 2021.11.1 (2021.266)
iOS 15.02 (iPad)

In my case it is not all buttons but only some, but I do not see pattern which work and which not

**Comment by spacegaier** [comment]
Does the issue only appear on iOS but other system work fine? Do you use any custom cards?

**Comment by kliphleon** [comment]
This is just on my iPad 2. All other devices including a iPad 7 are fine.

**Comment by BachaSport** [comment]
I have the same on Chrome. Then tried Edge browser and it was okay. I updated some HACS components and it is not working on edge anymore.

**Comment by cdekesel** [comment]
Same here. Only iPad2 seems affected.
