### ISSUE TITLE
Incorrect service name referred to in a pop-up logbook as responsible for an action

### ISSUE THREAD

**Issue by qoff** [home-assistant/frontend#10573]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The pop-up Logbook displays wrong service name responsible for the action.
It displays "Turned off" by service "switch.turn_on".

### Describe the behavior you expected

Expected is to see the correctly displayed information, i.e.: 
"Turned on" by service "switch.turn_on" and "Turned off" by service "switch.turn_off".

### Steps to reproduce the issue

1. Click on Lovelace's entity that has a switch / is able to be turned on and off
2. The pop-up is displayed containing incorrect information for turn-offs
3.
...
![2021-11-08 10_24_20-Logbook - Home Assistant – Opera](https://user-images.githubusercontent.com/89920369/140721323-92557554-918c-4c68-932f-d9dfd652275a.png)

### What version of Home Assistant Core has the issue?

2021.11.1

### In which browser are you experiencing the issue with?

every browser / app

**Comment by spacegaier** [comment]
Similar or even identical to https://github.com/home-assistant/frontend/issues/9459

From the looks of it, those changes are done by a script or automation and not manually? Can you show the traces for those to see what was actually triggered?

**Comment by qoff** [comment]
I don't have such a huge status icons configured in my Lovelace dashboard as DoubtfulBadger from #9459 has, but I don't find any other issue with "status" elswere or with switch position indicating some state not true. Switches are always correct. My only finding is the incorrect log in the pop-up logbook.

Please take a look at the screenshot below.
The highlighted turn off action displayed to me, 2 minutes ago, correctly - as "switch.turn_off". I didn't take a screenshot then, just got searching for the trace for you. Then I found the trace and got back to take the screenshot, and yeah, now it displays "switch.turn_on". I have even logged in using another browser in private mode, but no - HA resists and stays with displaying incorrect summary.

![2021-11-08 14_06_09-Overview - Home Assistant – Opera](https://user-images.githubusercontent.com/89920369/140747685-5a49786e-ffdf-4214-b41d-d85301fcf6d7.png)

Here is the trace from this run:
[trace script.ogrzewanie_90_min_duplicate 2021-11-08T11_15_00.015079+00_00.json.zip](https://github.com/home-assistant/frontend/files/7497136/trace.script.ogrzewanie_90_min_duplicate.2021-11-08T11_15_00.015079%2B00_00.json.zip)
