### ISSUE TITLE
Entity names beginning with the Area they're in are being truncated on dashboard in 2021.11

### ISSUE THREAD

**Issue by tofurky** [home-assistant/frontend#10571]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Entity names such as "kitchen motion (motion)" located in the "Kitchen" area are no longer displaying properly on the auto-generated dashboard. It appears that if the device Area is at the beginning of the entity name, it is being removed, and the second word is then capitalized.

Examples from Area "Kitchen":
"kitchen filter (voltage)" -> "Filter (voltage)"
"kitchen motion (temperature)" -> "Motion (temperature)"

Examples from Area "Bedroom":
"bedroom motion (motion)" -> "Motion (motion)"
"bedroom filter (current)" -> "Filter (current)"
"bedroom filter" -> "Filter"

Examples from Area "Island":
"island (power)" -> "(power)"
"island (z-wave)" -> "(z-wave)"

etc.

### Describe the behavior you expected

Manually specified entity names should be displayed on the dashboard verbatim to how they are entered.

### Steps to reproduce the issue

1. Add entity (MQTT, Z-Wave, ...) to an Area with the first word of the entity name being the (lowercased?) Area name.
2. View auto-generated dashboard and note that the displayed entity name is not what was manually entered.

### What version of Home Assistant Core has the issue?

2021.11.1

### What was the last working version of Home Assistant Core?

2021.10.4

### In which browser are you experiencing the issue with?

Google Chrome 94.0.4606.81

### Which operating system are you using to run this browser?

Ubuntu 20.04

### Problem-relevant frontend configuration

```yaml
Auto-generated dashboard with manually specified entity names that are prefixed with the Area name.
```

### Additional information

Most likely a result of https://github.com/home-assistant/frontend/pull/10285 (https://github.com/home-assistant/frontend/commit/279f3e1183815abd82ded9b53fb5e04770b504a4) "Trim device name from entities on device page"

Not sure if the intention there was to prevent displaying the manually specified device names or if it was supposed to just affect a different portion of the UI ("device page") entirely.

Viewing websocket traffic makes this appear to strictly be a frontend / JS issue.

My workaround for the time being is to add a zero-width space to the end of Area names :)

See attached screenshot of manually specified entity name compared to what is displayed on the dashboard.

![image](https://user-images.githubusercontent.com/4065513/140691981-5ef45fa5-51a0-46e8-87e3-fd80be7dcdc6.png)

Another screenshot, showing a more unfortunate automatic rename ("island (power)" in the "Island" area becomes just "(power)"):
![image](https://user-images.githubusercontent.com/4065513/140693672-b10f40b3-951f-421b-bc85-f75e08687f38.png)

**Comment by balloob** [comment]
This logic has existed for generated Lovelace for a while now. The referenced PR added this to the device info page. The area name stripping is by design as we're grouping all entities by area, and so the header of the card shows the area.

**Comment by tofurky** [comment]
This is new behavior with 2021.11. The devices used to display properly as entered as recently as 2020.10.4.

**Comment by tofurky** [comment]
For anyone else who is affected by this: a workaround is to add a Unicode zero-width space to the end of the Area name. This prevents the Area names from being stripped from the beginning of entities on the auto-generated dashboard.

**Comment by tofurky** [comment]
@balloob I rebuilt the frontend (20211103.0) with that commit (https://github.com/home-assistant/frontend/commit/279f3e1183815abd82ded9b53fb5e04770b504a4 "Trim device name from entities on device page") reverted (running with development_repo: in configuration.yaml) and now all of the manually-specified entity names prefixed with the Area are displaying as they should on the auto-generated dashboard, so it is definitely the culprit, and is affecting more than just the "device page":

![image](https://user-images.githubusercontent.com/4065513/140781838-db2ed2d6-ed45-496f-80fa-ec13f76f09f6.png)
