### ISSUE TITLE
When creating a new automation the process can be aborted without confirmation

### ISSUE THREAD

**Issue by wildblue** [home-assistant/frontend#10576]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When the automation created is a little bit larger and was really time consuming, it is very frustrating when you accidentially tip on the wrong place on your dmartphone and all effort is lost because of a simple dialog confirming the cancellation of the current process.

Please add such a confirmation on all possible gui elements shown when creating an automation.

### Describe the behavior you expected

Gui dialog to confirm should pop up

### Steps to reproduce the issue

1.create an automation and tip on other options
2.
3.
...

### What version of Home Assistant Core has the issue?

2021-11

### In which browser are you experiencing the issue with?

Chrome, android app of HA

### Which operating system are you using to run this browser?

Android

**Comment by bramkragten** [comment]
This is not really a helpful issue, please provide a detail instruction of all steps you took, what went wrong and what you expected to happen.

**Comment by jtaseff-gfms** [comment]
I agree with this one, many a time I've accidentally clicked the wrong thing like a sidebar nav button while creating a big long automation, and it just poofs out of existence.

**Comment by jtaseff** [comment]
This is still an active problem in 2022.2.5

Steps to reproduce:
Create a new automation
Add lots of things to it
Don't save yet
Hit a sidebar menu to navigate elsewhere
All your work disappears without a trace

Expect a confirmation if you really want to navigate away with unsaved work
