### ISSUE TITLE
Use higher res favicon for splash screen

### ISSUE THREAD

**Issue by marcelodavanzo** [home-assistant/frontend#10583]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When Home Assistant loads, the icon being shown is a low-res png – `static/icons/favicon-192x192.png`, looking visibly blurry and pixelated. It's especially obvious when using high pixel density screens which are so common these days on laptops, phones and tablets. See below:

![image](https://user-images.githubusercontent.com/8631786/140909781-5e687e11-b921-404e-b7b5-7d12227d1410.png)

### Describe the behavior you expected

I'd expect a higher res version of the icon to be shown. I haven't tested but imagine something like `static/icons/favicon-512x512.png` would look much better and could be optimised to be very small.

### Steps to reproduce the issue

1. In a browser, open a new tab and load your HA instance.
2. A splash screen is displayed while Lovelace loads.

### What version of Home Assistant Core has the issue?

2021.11.1

### In which browser are you experiencing the issue with?

All browsers

### Which operating system are you using to run this browser?

Various OSs

**Comment by spacegaier** [comment]
The PNG icon has been replaced by a SVG in this already merged PR https://github.com/home-assistant/frontend/pull/10569.
