### ISSUE TITLE
Automation Debug Trace Graph not displaying right

### ISSUE THREAD

**Issue by fschaeck** [home-assistant/frontend#10581]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Display of an Automation Debug Trace shows broken lines in the graph. See attached picture
<img width="507" alt="Screenshot 2021-11-09 at 07 39 29" src="https://user-images.githubusercontent.com/15925142/140875224-67579047-36d4-4db9-955d-e3e3d0e33708.png">
.

### Describe the behavior you expected

The lines in the graph should be connected and not broken.

### Steps to reproduce the issue

The automation that exhibits this problem is

`id: '1628286984942'
alias: Licht Kellertreppe
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.pir_1_occupancy
    attribute: occupancy
    id: UpstairsMotion
  - platform: state
    entity_id: binary_sensor.pir_2_occupancy
    attribute: occupancy
    id: DownstairsMotion
  - platform: state
    entity_id: switch.esszimmer_2_l1
    id: Switch
  - platform: device
    type: turned_on
    device_id: ec8dd3ac612416481c7ca6952a28f17c
    entity_id: switch.kellertreppenlicht
    domain: switch
    id: SwitchOff
    for:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
condition:
  - condition: or
    conditions:
      - condition: template
        value_template: >-
          {{ trigger.from_state.attributes. occupancy !=
          trigger.to_state.attributes.occupancy }}
      - condition: template
        value_template: >-
          {{ trigger.from_state.attributes.state_l1 !=
          trigger.to_state.attributes.state_l1 }}
      - condition: trigger
        id: SwitchOff
action:
  - choose:
      - conditions:
          - type: is_no_motion
            condition: device
            device_id: c3405dd414fd424ad2e51b00adec6bb4
            entity_id: binary_sensor.pir_1_occupancy
            domain: binary_sensor
          - type: is_no_motion
            condition: device
            device_id: 96b6a7f969c1ab9d1330d73e2c20acc0
            entity_id: binary_sensor.pir_2_occupancy
            domain: binary_sensor
          - condition: or
            conditions:
              - condition: device
                type: is_off
                device_id: 3c17b3fb72b6b039bea5c6a44b09448d
                entity_id: switch.esszimmer_2_l1
                domain: switch
              - condition: trigger
                id: SwitchOff
        sequence:
          - type: turn_off
            device_id: ec8dd3ac612416481c7ca6952a28f17c
            entity_id: switch.kellertreppenlicht
            domain: switch
          - type: turn_off
            device_id: 3c17b3fb72b6b039bea5c6a44b09448d
            entity_id: switch.esszimmer_2_l1
            domain: switch
    default:
      - type: turn_on
        device_id: ec8dd3ac612416481c7ca6952a28f17c
        entity_id: switch.kellertreppenlicht
        domain: switch
mode: queued
max: 10`

### What version of Home Assistant Core has the issue?

2021.11.1

### In which browser are you experiencing the issue with?

Safari Version 15.0 (16612.1.29.41.4, 16612) on MacOS 11.6
and iOS Companion App (iOS Version 15.1, iPhone 12)

whereas Firefox 94.0.1 (64-bit) on MacOS 11.6 does not exhibit this problem and displays the graph okay

### Which operating system are you using to run this browser?

MacOS 11.6

### Javascript errors shown in your browser console/inspector

No messages at all in the console of the Safari Browser

**Comment by bramkragten** [comment]
Please share the trace (download button is in the top right)

**Comment by fschaeck** [comment]
Sorry for the late response, but I was busy with my job the last couple of days...

Here is the downloaded trace:

[trace automation.licht_kellertreppe 2021-11-12T05_16_41.813472+00_00.json.txt](https://github.com/home-assistant/frontend/files/7525164/trace.automation.licht_kellertreppe.2021-11-12T05_16_41.813472%2B00_00.json.txt)

**Comment by circa1665** [comment]
Same issue: Safari 15.1 (17612.2.9.1.20
<img width="1280" alt="Screenshot 2021-11-14 at 11 58 57" src="https://user-images.githubusercontent.com/33236082/141679887-9538776c-f5fb-4778-90e1-618f37930864.png">
)
 
[trace automation.last_person_leave_lock_front_door 2021-11-14T10_13_02.068793+00_00.json.txt](https://github.com/home-assistant/frontend/files/7533658/trace.automation.last_person_leave_lock_front_door.2021-11-14T10_13_02.068793%2B00_00.json.txt)

**Comment by spacegaier** [comment]
Seems to be a Safari specific issue, since in Chrome on Win 10 it renders fine (and according to OP also in FF on macOS):

![image](https://user-images.githubusercontent.com/114137/142750774-5ea7b7a4-5e85-4120-ab9c-b2a10274ea1c.png)

**Comment by circa1665** [comment]
Also affection companion app on iOS ![image](https://user-images.githubusercontent.com/33236082/143509735-b1fa54df-b984-48b1-ad42-f3638cd6fb97.png)

**Comment by WizBangCrash** [comment]
Things are still not rendering correctly within Safari:
I'm using Safari version 15.2 (15612.3.6.1.8, 15612)

![Screenshot 2022-02-24 at 08 20 11](https://user-images.githubusercontent.com/3075593/155485779-ea2210f8-4ef7-4621-831f-b4d536f582cf.jpg)

and here is the same trace rendered in Brave:
![Screenshot 2022-02-24 at 08 22 44](https://user-images.githubusercontent.com/3075593/155486122-7950119b-2516-4da1-b6b8-9527c83a90e7.jpg)

**Comment by manu3b1** [comment]
Same here.

**Comment by circa1665** [comment]
This is issue is still present.

**Comment by cree8** [comment]
I can confirm as well, and that the issue does not exist within Edge. 
<img width="1243" alt="Screen Shot 2022-05-27 at 12 59 25 PM" src="https://user-images.githubusercontent.com/40502425/170765629-177c09db-f37f-4684-98b1-921300cd1343.png">

**Comment by WizBangCrash** [comment]
I'm still seeing the issue on Safari 15.5

**Comment by manu3b1** [comment]
Still there.

**Comment by manu3b1** [comment]
Still here on Home Assistant Core 2022.8.7 & Safari 15.6.1

**Comment by WizBangCrash** [comment]
I'm still seeing it too with the same versions @manu3b1

**Comment by Stefano0042** [comment]
Following 2024.1.0 HA core update the described graphical issue, is for the first time in my HA experience, trasversal to all platforms, iOS, Android, PC (Chrome, Edge, ..), e.g. but only in complex automations with parallel branches generated by "choice" nodes, in my case. 

![Screenshot 2024-01-05 181653](https://github.com/home-assistant/frontend/assets/59331592/7a21c57f-6063-40ca-bd5c-4e5eeea72d7d)

**Comment by manu3b1** [comment]
No more issue on my side on Safari with HA 2024-01. Thx a lot!

**Comment by circa1665** [comment]
Hi this isn't actually completely fixed as noted here: https://github.com/home-assistant/frontend/issues/18135 - as well as the debug trace lines not being connected in Safari (that part is fixed).
Clicking on nodes does not provide any step details in Safari << this is still not working.
I'm only able to view the trigger and action step details - no other nodes display info when clicked.
