### ISSUE TITLE
Remember login Checkbox does not work with Firefox 78 (Debian)

### ISSUE THREAD

**Issue by Nardol** [home-assistant/frontend#10582]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When opening my Home-Assistant instance address, typing user name and password, check the checkbox to remember login then "Next" buton, Connection is successful but if I come back to HA, I still have to log in.
No error shown in HA log nor in the web console and I have not this issue with Firefox 94 or Chrome.

### Describe the behavior you expected

When comming back to Home-Assistant, I should have my first dashboard displayed instead of the authentication page.

### Steps to reproduce the issue

1. Clear all cookies, cache and site storage
2. Go to you HA instance
3. Type your username, password and check the checkbox to stay logged in
4. Close your browser
5. Go back to Home Assistant

### What version of Home Assistant Core has the issue?

2021.11.2

### What was the last working version of Home Assistant Core?

2021.10.7

### In which browser are you experiencing the issue with?

Firefox 78.15.0esr

### Which operating system are you using to run this browser?

Debian Buster 10.11

### Additional information

Because of the now fixed timezone issue, I had to clear my session to check if it was not the cause before discovering the real issue so I cannot say if this issue occurs with a previous session with auth remembered. All I can tel is I had no issue with Home Assistant 2021.10.
In the case it could be useful, I use 2FA authentication.

**Comment by Nardol** [comment]
I've just tried with a totaly fresh Firefox profile and the issue is still there so I can now be sure my profile itself is not the issue.
Unfortunately I don't know how I could give more information.

**Comment by Nardol** [comment]
As it is an important issue due to a regression, I wish to specify I have tried with the last version released some days ago with the same result.
Each time I wish to connect to Home Assistant, I have to type again my password and pass again 2FA. Disabling 2FA does not look like a good and real solution.

**Comment by elkarto** [comment]
Same problem here using chrome (Versión 95.0.4638.69)

Every time I refresh the page (F5) or open a new tab the login screen appears.

Tested in different computers, same result.
Tested dissabling 2FA. Same result.


Seems that if you change something in the user config (http://homeassistant.local:8123/profile) it starts to remember the session. But not sure at all about this behaviour.

**Comment by NullEnt1ty** [comment]
I always have to log in twice so that Home Assistant remembers my session.

Tested with:
- Firefox 94.0.1
- Brave 1.32.106 (Chromium: 96.0.4664.45)

**Comment by andreasuvoss** [comment]
I found that "Enhanced Tracking Protection" in Firefox made me have to login on every single tab. Disabling it for your home-assistant site will allow the `hassTokens` to be saved in local storage.

**Comment by Nardol** [comment]
Closing as Debian updated Firefox to 91.5.0esr.
