### ISSUE TITLE
Lovelace overview page won't load because of Media Control Card 

### ISSUE THREAD

**Issue by kovbalazs89** [home-assistant/frontend#10593]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The symptom is my home-control overview won't load fully, just the first 3 card. I have 9 card on this page. If I hit the F5 button, the page load completely, The problem is the [media control card](https://www.home-assistant.io/lovelace/media-control/). This is my 4th card on this page. If I delete the card from this overview, it load fully again and there is no error in the logs.

### Describe the behavior you expected

The overview page should load fully with all of the cards at first try.

### Steps to reproduce the issue

1.Load lovelace overview
2.Click on the second tab
3.The cards won't load 
...

### What version of Home Assistant Core has the issue?

core-2021.11.1

### What was the last working version of Home Assistant Core?

core-2021.10.7

### In which browser are you experiencing the issue with?

Google Chrome 95.0.4638.69

### Which operating system are you using to run this browser?

Windows 11

### Javascript errors shown in your browser console/inspector

```txt
Logger: frontend.js.latest.202111080
Source: components/system_log/__init__.py:190
First occurred: 00:00:23 (1 occurrences)
Last logged: 00:00:23

http://192.168.1.185:8123/lovelace/home-control:0:0 Uncaught
```

### Additional information

I have performed a recovery to Core 20211007 and tried the upgrade again, but I have got this issue again. The problem still exists on Core 20211102.

**Comment by bramkragten** [comment]
Update all your custom cards, if that doesnt help, remove all your custom cards.

**Comment by kovbalazs89** [comment]
Thanks, it worked. I have removed all my custom cards and the page fully loaded again. I have successfully detected the problematic add-on too.
