### ISSUE TITLE
Duplicate URL in view causes data corruption

### ISSUE THREAD

**Issue by poelzi** [home-assistant/frontend#10594]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a view in the default dashboard. I created a new dashboard with the contents of the old view.
If the url set to the absolute path of another view, lovelace breaks horrible.

### Describe the behavior you expected

I can still open the view in edit mode at least. Correct view is selected

### Steps to reproduce the issue

1. Create a lovelace view with url /lovelace/sleep
2. Create a second dashboard /lovelace-sleep/default
3. Set the url of the first view to: /lovelace-sleep/default

### What version of Home Assistant Core has the issue?

2021.11.3

### In which browser are you experiencing the issue with?

Chrome, Firefox

### Which operating system are you using to run this browser?

Linux NixOS

**Comment by ChristianLais** [comment]
I have exactly the same issue... Is there any solution yet?

**Comment by poelzi** [comment]
I edited the raw file which fixed the problem, but the frontend should pervent corruption
