### ISSUE TITLE
next_state attribute not available in attributes selector alarm_control_panel.home_alarm entity

### ISSUE THREAD

**Issue by monpelaud** [home-assistant/frontend#10603]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi,
With User Interface, next_state attribute is not available in the attribute selector of the alarm_control_panel.home_alarm entity.

Best regards

### Describe the behavior you expected

![UI_issue](https://user-images.githubusercontent.com/16806004/141289664-a39b75c4-4f7e-49b8-b041-6b73ccc8f58f.png)

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.11.2

**Comment by spacegaier** [comment]
The `next_state` attribute only exists for alarms from the `manual` integration. Is that the one you use?

**Comment by monpelaud** [comment]
Thanks for your reply,

I'm using alarm control panel:
[https://www.home-assistant.io/integrations/manual](url)

While the alarm_control_panel.home_alarm is arming I want to start one script if the next state is armed_away and an other script when next state is armed_night.

![Capture1](https://user-images.githubusercontent.com/16806004/142755401-e586b263-5615-423a-aa25-e1877078b303.JPG)

Here the two automations I use and work fine :

alias: ' Notifie activation alarme: Mode-Absent'
description: Notification de l'activation de l'alarme
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    attribute: next_state
    to: armed_away
condition: []
action:
  - service: script.notifier_activation_alarme_mode_absent
mode: single

and

alias: ' Notifie activation alarme: Mode-Nuit'
description: Notification de l'activation de l'alarme
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    attribute: next_state
    to: armed_night
condition: []
action:
  - service: script.notifier_activation_alarme_mode_nuit
mode: single

Best regards
