### ISSUE TITLE
All Entities Only Showing One Area

### ISSUE THREAD

**Issue by coyoteT** [home-assistant/frontend#10605]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After upgrading to core-2021.11.2 my system generated All Entities dashboard (still under Home Assistant control) is only showing one area. I’ve tried accessing it from multiple browsers, different computers, even the iOS app and they all have the same issue. I’ve also tried creating a new profile but that had the same results. I upgraded from core-2021.10.4. I'm not seeing any errors in the logs that would point to what is causing this issue.

Screenshot of All Entities dashboard:
<img width="1356" alt="Screen Shot 2021-11-11 at 09 06 46" src="https://user-images.githubusercontent.com/58957705/141321424-bf3ac567-1cbc-493a-8c23-25bed7b33066.png">

Screenshot showing multiple areas with multiple devices:
<img width="993" alt="Screen Shot 2021-11-11 at 09 20 16" src="https://user-images.githubusercontent.com/58957705/141323220-e4261679-2322-4ff7-b103-8c635bc90613.png">

### Describe the behavior you expected

The All Entities dashboard should show all areas with all entities.

### Steps to reproduce the issue

1. I used docker-compose to upgrade (homeassistant/home-assistant:stable)
2. Clicked on the All Entities dashboard

### What version of Home Assistant Core has the issue?

core-2021.11.2

### What was the last working version of Home Assistant Core?

core-2021.10.4

### In which browser are you experiencing the issue with?

Every browser used

### Which operating system are you using to run this browser?

macOS Catilina, iOS 15.1

**Comment by spacegaier** [comment]
So if you create a completely new dashboard via `/config/lovelace/dashboards`, it only contains a single card for a single area?

**Comment by coyoteT** [comment]
I don't have any `/lovelace` or `/lovelace/dashboards` in `/config`... I can create new dashboards through the UI and add all of the cards I want to it, but the "All Entities" dashboard that was system generated, used to show all of the entities in my system, but since upgrading it does not, it only shows the one area.

**Comment by spacegaier** [comment]
The path `/config/lovelace/dashboards` is the path to the UI where you create dashboards ([link](https://my.home-assistant.io/redirect/lovelace_dashboards/)). Sorry for the confusion.

If create a new dashboard there now, does it contain all entities or does a newly created one also have the issue you reported?

**Comment by coyoteT** [comment]
Creating a new dashboard gives me the same issue. It lists the same entities as the "All Entities" dashboard where it only contains a limited amount.

**Comment by spacegaier** [comment]
Ok, that is weird. Works fine for me.

Any errors in the browser console?

**Comment by coyoteT** [comment]
I have 2 errors:
`Unhandled Promise Rejection: NotSupportedError: Cannot define multiple custom elements with the same tag name`
`Unhandled Promise Rejection: [object Object]`

**Comment by coyoteT** [comment]
After updating to the latest version, Home Assistant 2021.12.7, my "All Entities" dashboard is now completely blank. When I create new dashboards, they are blank as well.

**Comment by coyoteT** [comment]
After coming across someone with a similar issue ([https://community.home-assistant.io/t/dashboard-completely-blank-after-update-media-control-card-the-culprit/360222](url)), I was able to pinpoint the cause. It looks like any device that is using the Media player is causing this. I disabled my Sonos Integration and all of my entities reappeared on the All Entities dashboard. I re-enbled the integration and all of the entities stayed however the devices that use the media player do not show up (I am fine with this but still seems to be a bug, maybe with the default media player card?).

**Comment by bramkragten** [comment]
Are you using custom cards?

**Comment by coyoteT** [comment]
I was running some custom cards including a mini media player card, I just removed all of them and the media player devices are still not showing up on the all entities page. Is there any log entries I can look for to pinpoint exactly what is causing it?
