### ISSUE TITLE
"User Input Malformed" error when re-configuring integrations with missing entries

### ISSUE THREAD

**Issue by poelzi** [home-assistant/frontend#10608]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This is related to #10567 which did not fix the problem completely. I still get "User Input Malformed" if the entry does not exist anymore.

### Describe the behavior you expected

No error message.
Either show the entry that is not in the selection and tick it, so it can be removed or remove the entry so a submit will not send items as selected that do not exist anymore.

### Steps to reproduce the issue

1. Install adaptive_lighting extension
2. Add a lamp to be controlled
3. Rename the lamp from a to be
4. Create a lightgroup with name a that includes b

The selection box still shows the lamp A in the list of controlled lamps, but the lamp is not in the selection list, making it impossible to deselect. Sending this form will cause the Malformed Input

### What version of Home Assistant Core has the issue?

2021.11.3

### What was the last working version of Home Assistant Core?

2021.10.x

### In which browser are you experiencing the issue with?

Chrome, Firefox

### Which operating system are you using to run this browser?

Linux NixOS

**Comment by SeLLeRoNe** [comment]
Had the same issue, only solution was to remove the integration and add it back.
The integration should check on startup maybe if the assigned lights all exists, and remove those that do not (if that's possible), or at least allow us to replace them in the config if they are no longer listed.

**Comment by SeLLeRoNe** [comment]
I've just noticed you've opened it directly in HA :D 
I am not sure this exactly is HA issue, might be adaptive-lighning itself that it's not "smart enough"

**Comment by randomlyalex** [comment]
> I've just noticed you've opened it directly in HA :D I am not sure this exactly is HA issue, might be adaptive-lighning itself that it's not "smart enough"

i tried uninstalling the integration and the even HACS repo, and reloaded everything and still got the same problem?

**Comment by SeLLeRoNe** [comment]
Sorry, I didn't mean uninstall the whole thing... You literally need to remove the config from the UI, and then add them again in the UI, it's not in HACS.

**Comment by randomlyalex** [comment]
> Sorry, I didn't mean uninstall the whole thing... You literally need to remove the config from the UI, and then add them again in the UI, it's not in HACS.

My Bad, I thought i'd updated core, but I hadn't 🙈   So this worked for adaptive, but itdidn'tt work for programmable thermostat.

**Comment by mikesdnielsen** [comment]
I also see this on the Homekit integration, when updated to 2021.11.3. There was a pull request to supposedly fix this and it seems like it should have been released with 11.3, but it has not solved the problem for me. 

It would such having to remove the Homekit setup as I would have to re-organize the whole thing again on the iPhone/Mac. 

Hoping for a solution soon for this.

**Comment by jseidl** [comment]
I'm experiencing the same on my integration. Removing the config entry through the UI and re-setting it up works. First time setup works. Re-configuring gives `User Input Malformed`.

**Comment by nilskuehme** [comment]
Experienced same issue. Added a new lamp and had to rename it's entity name. Then the new name appeared in the drop-down menu with deselected hook. Adding the entity again caused the same error as mentioned above.

**Comment by nilskuehme** [comment]
Experienced same issue. Added a new lamp and had to rename it's entity name. Then the new name appeared in the drop-down menu with deselected hook. Adding the entity again caused the same error as mentioned above.

**Comment by poelzi** [comment]
still a problem and should be fixed on the widget to fix all usages. I still have problems when renaming a entry

**Comment by chdefrene** [comment]
I had the same problem. Managed to work around it by opening the file `/config/.storage/core.config_entries` inside the Home Assistant container, and editing the "Adaptive Lighting" entry to remove/replace any obsolete entity IDs.

**Comment by peter--s** [comment]
This still needs to be fixed.
It seems very unfortunate that the dropdown can neither show nor purge obsolete entries, nor does it offer a YAML editor to remove them manually.

**Comment by Crare** [comment]
got similar issue. I get this error message: "Message malformed: must contain at least one of below, above." when using ruuvitag(bluetooth beacon) and using "movement counter value changed" as trigger. When saving it gives that error. There's no options to setup below and above values in this case nor there should be if I understand how it should work. YAML editor would be pretty much appreciated.

**Comment by poelzi** [comment]
reopen
