### ISSUE TITLE
ecobee integration page should have links to climate integration page

### ISSUE THREAD

**Issue by zolstarym** [home-assistant/frontend#10636]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Feedback

Feedback

For a user with an ecobee thermostat who installs the integration and then looks at the ecobee integration page for info on service calls, there should be a link to the climate page (https://www.home-assistant.io/integrations/climate/), since that has service calls listed in it that control ecobee thermostats that might otherwise be unknown to the user, since it might not be obvious that a different integration would control the ecobee thermostat or that a different integration page would have that info.

Also, climate.set_fan_mode used to be able to be used with hold_hours for ecobee thermostats, but that broke in an update and it's not clear to me if you can still set how long the ecobee fan will run, so adding documentation for that would be useful.
URL

https://www.home-assistant.io/integrations/ecobee/
Version

2021.11.0
Additional information

No response

### Describe the behavior you expected

 .

### Steps to reproduce the issue

1.
2.
3.
...
.

### What version of Home Assistant Core has the issue?

2021.11

**Comment by spacegaier** [comment]
Both points you raised are not frontend issues:
1. The first one seems to be about the Ecobee integration's documentation => please raise that [here](https://github.com/home-assistant/home-assistant.io)
2. The services and their fields are controlled by the backend. The frontend just renders what the backend requests. `set_fan_mode` indeed does not have a parameter `hold_hours`. I also cannot see a PR that removed it. The `ecobee` integration itself contains coding for `hold_hours` (see https://github.com/home-assistant/core/pull/40520).
