### ISSUE TITLE
ZHA: Missing args textbox to issue zigbee commands

### ISSUE THREAD

**Issue by seblu** [home-assistant/frontend#10633]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The `Issue Zigbee Command` UI in `Manage Clusters` is missing an `Args` textbox.
As a consequence, all Zigbee commands requiring arguments are failing with an error message.

![Screenshot_20211117_145157](https://user-images.githubusercontent.com/615816/142213720-f94c15c2-fd75-4ebc-a3ea-7a936c55c7ff.png)

### Describe the behavior you expected

An `Args` textbox like the box `Manufacturer Code Override` to specifies clusters commands args.

Here is a screenshot of the interface in Devtools->Service for the underlying ZHA service.
![Screenshot_20211117_145825](https://user-images.githubusercontent.com/615816/142214401-f0bac766-c5c3-4436-a8b3-b262a7624472.png)

### Steps to reproduce the issue

1.Go the device page of a **ZHA** device
2.Click on `Manage Clusters`
3.Choose a clusters with commands with args (e.g `OnOff`)
4. Under `Clusters Commands` choose a command with args. (e.g: `on_with_timed_off`)
5. Press `Issue Zigbee Command`
...

### What version of Home Assistant Core has the issue?

core-2021.11.4

### In which browser are you experiencing the issue with?

Firefox 94.0.1 / Chromium 96.0

### Which operating system are you using to run this browser?

Arch Linux

**Comment by seblu** [comment]
Issue is still present in `2022.2.9`.

**Comment by Hedda** [comment]
Tip; temporary workaround until these get added nativly to ZHA's UI could be to experiment with automations using the framework for generic exposure of device configuration attributes by @dumpfheimer as well as "ZHA Toolkit". See -> [https://github.com/zigpy/zigpy/discussions/934](https://github.com/zigpy/zigpy/discussions/934) and/or [https://github.com/mdeweerd/zha-toolkit](https://github.com/mdeweerd/zha-toolkit) + https://community.home-assistant.io/t/zha-toolkit-toolkit-providing-low-and-high-level-zigbee-commands-through-zha-zigpy/373346 but that is probably more work than extending zha component cover support.

**Comment by cremor** [comment]
This issue is still relevant for version 2022.6.6

**Comment by cremor** [comment]
This issue is still relevant for version 2022.9.4

**Comment by steffen890** [comment]
![image](https://user-images.githubusercontent.com/52309513/196872906-bb0c707e-764f-42db-a3de-fe6140b694c7.png)
Same here
