### ISSUE TITLE
Auto preset mode doesnt stick on Tradfri Fan more-info

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#10639]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

<img width="401" alt="Schermafbeelding 2021-11-17 om 19 48 58" src="https://user-images.githubusercontent.com/33354141/142263652-c57035e6-e09c-4364-b707-8dfa6d9a752d.png">

### Describe the behavior you expected

have the attributes box move down, so we can see the actual selection, which was visible when clicking the select:

<img width="394" alt="Schermafbeelding 2021-11-17 om 19 49 06" src="https://user-images.githubusercontent.com/33354141/142263750-f24bc11b-e25a-47eb-bc8a-ad53c1e7a897.png">

### Steps to reproduce the issue

1. add a fan to the Lovelace view
2. click it to reveal more-info
3.
...

### What version of Home Assistant Core has the issue?

2021.11.3

### What was the last working version of Home Assistant Core?

never

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

monterey 12.01

### Problem-relevant frontend configuration

```yaml
- type: entity
    entity: fan.luchtreiniger_woonkamer
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

btw, regarding the attributes

<img width="874" alt="Schermafbeelding 2021-11-17 om 19 53 50" src="https://user-images.githubusercontent.com/33354141/142264447-efbd99fc-808d-4674-9d2b-637457ebb034.png">

only Auto is selectable, and 'speed' is not displayed at all.

the other attributes probably are in the slider and the select box?

**Comment by spacegaier** [comment]
According to your state screenshot, this entity only has a single preset "Auto" so there can only be one entry in the dropdown. If there were more they should be rendered above the attribute panel anyway.

Or am I missing your point?

**Comment by matthiasdebaat** [comment]
If there is no option to choose from it's maybe better to just hide the dropdown

**Comment by Mariusthvdb** [comment]
this might make it more visible: the attributes drop down box is too high so it seems. We can not see what is selected. In the forst screen shot you see what is looks like without activating the select:

<img width="439" alt="Schermafbeelding 2021-11-18 om 16 23 56" src="https://user-images.githubusercontent.com/33354141/142444601-bbbff235-3984-4a46-8c68-5f7ccbaf942c.png">

Auto is selected, but it is not displayed (or probably covered by the attributes dropdown box)

below, you can see what happens when one activates the select:

<img width="447" alt="Schermafbeelding 2021-11-18 om 16 24 55" src="https://user-images.githubusercontent.com/33354141/142444770-f4c9f6cd-a50d-4858-90f0-d92039989f63.png">

The options list overflows the attributes dropdown, because it is too close.

I would expect it so show like this:

<img width="508" alt="Schermafbeelding 2021-11-18 om 16 28 01" src="https://user-images.githubusercontent.com/33354141/142445055-032b1072-53b6-4776-b2ca-03347bea4383.png">

where the select show the currently selected option And has enough space for the next item in the card

**Comment by Mariusthvdb** [comment]
so essentialy I might need to rename this in Auto mode doesnt stick ?
running 2022.2.0.dev20220110 now, and while that allows us to turn on using auto-mode, clicking more-info still doesnt show Auto being selected

**Comment by spacegaier** [comment]
If the backend provides a set mode, then it should be rendered. In your previous screenshot of the entity state `preset_mode` is `null`, so in that case nothing will be selected in the mode input field.

Have you verified that the backend actually sets/keeps the preset mode?

**Comment by Mariusthvdb** [comment]
no! it doesnt! created an issue for that

**Comment by Mariusthvdb** [comment]
guess I need to close this, as the correct backend does show Auto in frontend fixed....
thanks!
