### ISSUE TITLE
Unifi integration does not render site picker

### ISSUE THREAD

**Issue by robertmain** [home-assistant/frontend#10642]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When trying to integrate my unifi controller into home assistant, the final configuration step does not render correctly.

I enter the controller info into the initial form and hit submit:
![image](https://user-images.githubusercontent.com/537684/142327163-67a3863d-c3ec-4ace-87bc-afbb79757a38.png)

That info is accepted and replaced with this:
![image](https://user-images.githubusercontent.com/537684/142327828-0300c9fb-4b63-43af-ad25-427e0b7594f6.png)

Digging into this in chrome inspector, I see this JSON coming back from the server: 

```json
{
   "type":"form",
   "flow_id":"1e7bf0fa8f9f444da429b31ab2d0360f",
   "handler":"unifi",
   "step_id":"site",
   "data_schema":[
      {
         "type":"select",
         "options":[
            
         ],
         "name":"site",
         "required":true
      }
   ],
   "errors":{
      
   },
   "description_placeholders":null,
   "last_step":null
}
```

That would suggest to me that the server is instructing Lovelace to render a `<select>` box (presumably for me to pick the unifi site I want to integrate with, if the data there is anything to go by) and Lovelace for one reason or another is failing to do so(perhaps because of the empty options?)

Clicking "Submit" on that box simply gets me a validation error:

![image](https://user-images.githubusercontent.com/537684/142330028-b241f60d-812b-452c-abdf-11d7db9e62aa.png)

### Describe the behavior you expected

I expected to be able to choose the unifi site I wanted to monitor

### Steps to reproduce the issue

1. Click "Add New Integration"
2. Choose "Unifi"
3. Enter unifi controller info.
4. Click "Submit"

### What version of Home Assistant Core has the issue?

core-2021.11.4

### In which browser are you experiencing the issue with?

Google chrome 94.0, Firefox 78, HomeAssistant Android app 

### Which operating system are you using to run this browser?

Debian 9

### Additional information
- Unifi Controller version: 6.4.54.0

**Comment by spacegaier** [comment]
Are there any errors in your browser console?

**Comment by robertmain** [comment]
Nope, looks clear

**Comment by robertmain** [comment]
Moved to Closed and moved to https://github.com/home-assistant/core/issues/60571 since that repo seems to be where all the other integration issues are.
