### ISSUE TITLE
System Health mode incorrectly being reported

### ISSUE THREAD

**Issue by kaizersoje** [home-assistant/frontend#10641]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

My main lovelace panel and other dashboards are all in `yaml` mode. I have also created a dashboard from the UI for DEV purposes. However, the system health reports that my lovelace mode is `storage`. Due to this, when I try to download any frontend repositories in HACS, it throws the error below. 

## System Health

version | core-2021.11.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.17-v7
arch | armv7l
timezone | Australia/Sydney

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4286
Installed Version | 1.17.2
Stage | running
Available Repositories | 996
Installed Repositories | 112

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.8
disk_total | 219.4 GB
disk_used | 20.0 GB
healthy | true
supported | failed to load: Unsupported
board | rpi3
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Dropbox Sync (1.3.0), SQLite Web (2.3.2), AppDaemon 4 (0.4.4), File editor (5.3.3), Check Home Assistant configuration (3.9.0), MQTT Server & Web client (1.2.0), Log Viewer (0.12.1), AirCast (3.2.0), Glances (0.14.0), Home Assistant Google Drive Backup (0.105.2), Grafana (7.3.1), Terminal & SSH (9.2.1), Duck DNS (1.14.0), Let's Encrypt (4.11.0), InfluxDB (4.3.0), AdGuard Home (4.2.0), SSH & Web Terminal (9.1.0), Signal Messenger (0.42.0), Portainer (2.0.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 7
-- | --
resources | 62
views | 46
mode | storage

</details>

### Describe the behavior you expected

I would have assumed I can have a mix of yaml and UI dashboards and HACS would work as normal as well.

### Steps to reproduce the issue

1. Open HACS and click on Frontend.
2. Select any repository to download (does not matter new or existing)
3. Click on download. The icon keeps going round and round.
...

### What version of Home Assistant Core has the issue?

core-2021.11.4

### In which browser are you experiencing the issue with?

Google Chrome Version 96.0.4664.45

### Which operating system are you using to run this browser?

Windows 10

### Javascript errors shown in your browser console/inspector

```txt
c.e523f276.js:53 Uncaught (in promise) {code: 'unknown_command', message: 'Unknown command.'}
value @ c.e523f276.js:53
await in value (async)
handleEvent @ main-8113c4f2.js:1
```

**Comment by spacegaier** [comment]
I assume this has been fixed by this backend PR already https://github.com/home-assistant/core/pull/59835

**Comment by spacegaier** [comment]
@kaizersoje Do you have a dev/nightly environment where you can confirm that the backend PR fixes the issue?

**Comment by kaizersoje** [comment]
> issue

Unfortunately I don't.

**Comment by spacegaier** [comment]
Okay, I will then close the issue for now, since the backend PR should have resolved that. If you still face the issue in the next HA release, let us know and we will reopen it.

**Comment by kaizersoje** [comment]
Sure, thanks
