### ISSUE TITLE
Deleting a area doesn't bring me back to the area overview

### ISSUE THREAD

**Issue by matthiasdebaat** [home-assistant/frontend#10648]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I delete an area I get an extra screen with a button `Go back`.
![Schermopname 2021-11-18 om 13 04 06](https://user-images.githubusercontent.com/20203284/142412847-48fa4d63-7bb4-4d2f-a11e-a6bb55d700de.gif)

 

### Describe the behavior you expected

Skip this step and go back to the overview directly.

### Steps to reproduce the issue

1. Go to `Areas`
2. Open an `Area`
3. Hit the `Cog` icon
4. Delte it

### What version of Home Assistant Core has the issue?

core-2021.11.4

**Comment by spacegaier** [comment]
Seems to already be fixed with the PR that changed the area table to use cards instead. Can you re-test on the latest dev version?

**Comment by matthiasdebaat** [comment]
Yeah it's fixed. Though I had to search for the delete button, because it's moved to a dialog. 🙈
