### ISSUE TITLE
When creating a new helper the `Name` input is already in error state

### ISSUE THREAD

**Issue by matthiasdebaat** [home-assistant/frontend#10649]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating a new helper the `Name` input is already in error state without any user interaction.
![Schermopname 2021-11-18 om 13 33 03](https://user-images.githubusercontent.com/20203284/142416372-86b20628-6b00-4267-a28f-b6cfebf6fa36.gif)

### Describe the behavior you expected

Only show the error when the user makes this error.

### Steps to reproduce the issue

1. Go to `Helpers`
2. Create a new helper, for example `Dropdown`

### What version of Home Assistant Core has the issue?

core-2021.11.4

**Comment by ildar170975** [comment]
I do not consider this as a bug. The “Name” field is mandatory, the error state shows that the field is empty.

**Comment by matthiasdebaat** [comment]
This is still an issue, even with the new inputs. Without a user interaction the name field is in error state.
<img width="416" alt="CleanShot 2022-07-11 at 10 47 28@2x" src="https://user-images.githubusercontent.com/20203284/178225363-9fdc4964-8334-4b8d-beef-b0216a882744.png">

**Comment by matthiasdebaat** [comment]
Still an issue

**Comment by silamon** [comment]
Looked into this and the error message is always being set on those textfields. It should be undefined if no error message exists at the time. Textfields that are required should be marked with a required so they have an * behind their label.

**Comment by karwosts** [comment]
Filed a fix.
