### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'map') in climate

### ISSUE THREAD

**Issue by geirsf** [home-assistant/frontend#10682]
### The problem

When trying to open the climate planel for the Zwave device ZXT-600 by Remotec it triggers an TypeError: Cannot read properties of null (reading 'map') error.  Screenshot attached. 

![sc](https://user-images.githubusercontent.com/24475820/142742645-1d57a315-5903-49ef-8925-7d1cedb9dbe4.png)

### What version of Home Assistant Core has the issue?

core-2021.11.5

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

Climate

### Link to integration documentation on our website

[https://www.home-assistant.io/integrations/climate](https://www.home-assistant.io/integrations/climate)

### entity state 
```
hvac_modes:
  - 'off'
  - heat
  - cool
  - heat_cool
min_temp: 17
max_temp: 30
fan_modes: null
preset_modes:
  - none
  - Resume (on)
  - Fan
  - Dry
current_temperature: 21.5
temperature: 22
target_temp_high: null
target_temp_low: null
fan_mode: null
preset_mode: none
friendly_name: Varmepumpe
supported_features: 27
```

### Anything in the logs that might be useful for us?

```txt
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'map')
    at HTMLElement.value (more-info-climate.ts:237)
    at HTMLElement.update (styles.ts:365)
    at HTMLElement.performUpdate (styles.ts:365)
    at HTMLElement.scheduleUpdate (styles.ts:365)
    at HTMLElement._$EC (styles.ts:365)
value @ more-info-climate.ts:237
update @ styles.ts:365
performUpdate @ styles.ts:365
scheduleUpdate @ styles.ts:365
_$EC @ styles.ts:365
await in _$EC (async)
requestUpdate @ styles.ts:365
set @ styles.ts:365
(anonymous) @ fcdd17d6.js:1
i @ fcdd17d6.js:1
value @ ha-more-info-logbook.ts:16
performUpdate @ styles.ts:365
scheduleUpdate @ styles.ts:365
_$EC @ styles.ts:365
await in _$EC (async)
requestUpdate @ styles.ts:365
set @ styles.ts:365
k @ styles.ts:365
_$AI @ styles.ts:365
m @ styles.ts:365
T @ styles.ts:365
_$AI @ styles.ts:365
M @ styles.ts:365
_$AI @ styles.ts:365
m @ styles.ts:365
T @ styles.ts:365
_$AI @ styles.ts:365
S @ styles.ts:365
update @ styles.ts:365
performUpdate @ styles.ts:365
scheduleUpdate @ styles.ts:365
_$EC @ styles.ts:365
await in _$EC (async)
requestUpdate @ styles.ts:365
set @ styles.ts:365
(anonymous) @ styles.ts:365
value @ styles.ts:365
value @ home-assistant.ts:66
_$AE @ styles.ts:365
performUpdate @ styles.ts:365
scheduleUpdate @ styles.ts:365
_$EC @ styles.ts:365
await in _$EC (async)
requestUpdate @ styles.ts:365
set @ styles.ts:365
value @ styles.ts:365
(anonymous) @ styles.ts:365
s @ core.2fe29b5a.js:1
(anonymous) @ core.2fe29b5a.js:1
(anonymous) @ core.2fe29b5a.js:1
_handleMessage @ core.2fe29b5a.js:1
(anonymous) @ core.2fe29b5a.js:1
```

**Comment by spacegaier** [comment]
Please add your complete climate entity state (from the HA dev tools) into the issue template.

From a first glance at the coding this issue could appear, that the entity reports it supports fan mode, but does not actually provide any fan modes in the entity.

**Comment by geirsf** [comment]
@spacegaier Thanx for your replay. I have added the climate entity  under "entity state".

**Comment by spacegaier** [comment]
Okay, as I suspected. The entity says it supports fan modes, but then does not actually provide any.

=> Which integration is this climate entity created by? Perhaps there is something wrong there.

Independently of that: I will push a frontend fix that captures those scenarios and gracefully renders the rest of the more-info dialog.

**Comment by geirsf** [comment]
It's a Z-wave device. More info [here ](http://manuals-backend.z-wave.info/make.php?lang=en&sku=ZXT-600EU&cert=ZC10-17085735)

I use zwavejs2mqtt with the new Z-Wave ingration for Z-Wave JS.

I also added some more info here on the Z-wave device.  
[node19.txt](https://github.com/home-assistant/frontend/files/7590223/node19.txt)

**Comment by spacegaier** [comment]
You could consider creating an issue in the backend with the Z-Wave JS integration (and reference to this issue) so that they can check if everything works correctly (not sure if a climate entity that supports fan modes should at least provide a "None" default value or not, but they would know). 

Either way the frontend will in the future react gracefully once my PR is merged.

**Comment by geirsf** [comment]
@spacegaier Great, will do! :)
