### ISSUE TITLE
SolarEdge Entities disabled

### ISSUE THREAD

**Issue by AndrewTapp** [home-assistant/frontend#10684]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

For a while now the SolarEdge integration has only been showing 2 entities as available (seensor.solaredge_current_power & sensor.solaredge_lifetime_energy).

The remaining 19 entities are shown as disabled by the integration.

I'm currently using core-2021.11.5 & supervisor-2021.10.8.

I've tried deleting & re-adding the integration, restarting the core etc. etc. but nothing seems to work.

Any advice would be gratefully received.

![Screenshot 2021-11-22 124941](https://user-images.githubusercontent.com/83402277/142867156-076b3ead-2ed2-47f1-951c-6e07db1ede4b.jpg)
.

### Describe the behavior you expected

That all 21 SolarEdge entities should be available and not disabled.

### Steps to reproduce the issue

1) Add the SolarEdge integration.
2) Enter the SiteID & APIKey and submit.
3) Integration shows 'success'.
4) On the list of installed integrations, select the hyperlink '21 entities' under SolarEdge.
5) sensor.solaredge_current_power & sensor.solaredge_lifetime_energy are available
6) the remaining 19 entities all show 'unavailable' & 'disabled by integration.

### What version of Home Assistant Core has the issue?

core-2021.11.5

### In which browser are you experiencing the issue with?

Microsoft Edge Version 96.0.1054.29 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11 Pro for Workstations 21H2 22000.348

**Comment by frenck** [comment]
This is not a bug. Please make sure you read the breaking-changes section in the release notes, before upgrading.

![image](https://user-images.githubusercontent.com/195327/142870212-c110cbad-1128-4ad1-ae5a-b9f3929c839f.png)

<https://www.home-assistant.io/blog/2021/11/03/release-202111/#breaking-changes>

You can enable the entities you'd like to use, by toggling the "Enable entity" switch.

![image](https://user-images.githubusercontent.com/195327/142870355-e05d537f-41f2-453a-b4e4-1bf1dbb4a60d.png)

**Comment by AndrewTapp** [comment]
Many thanks for your information, and apologies for not seeing it earlier.
