### ISSUE TITLE
"Check Configuration" incorrectly reporting "Configuration valid!"

### ISSUE THREAD

**Issue by b4dpxl** [home-assistant/frontend#10690]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The "Check Configuration" button under "Server Controls" incorrectly reports "Configuration valid!" when there are problems with automations which cannot be loaded. An easy to miss notification is raised instead. (I woke up to a cold house this morning due to missing the notification and not realising an automation had a typo!)

While the old message wasn't very user friendly when there was an error, at the least there should be an obvious warning like "configuration mostly valid, but some automation could not be loaded", instead of stating that everything was fine and relying on a notification (which I didn't notice until much later). The message currently returned is factually wrong.

### Describe the behavior you expected

Either the old message describing the issue in the configuration file, or a generic message saying that there was a problem loading some automations.

### Steps to reproduce the issue

1. Create an invalid automation in a YAML file (e.g. change "trigger" to "rigger")
2. Click "Check Configuration" under "Server Controls"
3. Observe the response which incorrectly states "Configuration valid!"

### What version of Home Assistant Core has the issue?

core-2021.11.5

### What was the last working version of Home Assistant Core?

2021.10

### In which browser are you experiencing the issue with?

Chrome 96.0.4664.45 

### Which operating system are you using to run this browser?

Windows 10

**Comment by ildar170975** [comment]
Some automations may cause errors only during runtime.

**Comment by b4dpxl** [comment]
That wasn't the case here, the automation being edited wasn't scheduled to run until the following morning. Also, the log file immediately showed a warning as soon as the "check configuration" button was clicked. 

Previous versions of HA identified similar typos.

**Comment by coverthembrow** [comment]
bump
