### ISSUE TITLE
Energy Dashboard Showing Incorrect Data

### ISSUE THREAD

**Issue by Hajman** [home-assistant/frontend#10697]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Beginning on or about 12 Nov, the Energy dashboard  has been reporting incorrect usage data.  As shown in the attached is showing little or negative use of energy.  I do not have any generation capability at my home.  I use sensor.daily_usage from a Sense monitor for the usage data.  The usage data from the Sense sensor is correct (see screen shot) but the Energy dashboard is not.[](url
![Sense Data](https://user-images.githubusercontent.com/21141807/143092985-7ec821cd-bb9f-4d9f-bee7-648dad9237f3.jpg)
![Energy Dashboard](https://user-images.githubusercontent.com/21141807/143092992-d2f25e02-306a-4fb5-84ef-2ceba2d7ac15.jpg)
)

### Describe the behavior you expected

The Dashboard to correctly show daily usage.

### Steps to reproduce the issue

1.  Click on Energy Dashboard
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.11.5

### In which browser are you experiencing the issue with?

Behavior is the same on Safari, Chrome, Edge and HA app

**Comment by Hajman** [comment]
I switched to the day view and this revealed further info.  Since November 12, every new day begins with what looks like an erroneous negative usage number or perhaps an erroneous generation number.  It doesn't look like the Sense data is providing this erroneous starting point.  See screen shot from November 12.  All subsequent days have the same issue.
![Energy Dashboard](https://user-images.githubusercontent.com/21141807/143274315-d535595f-91da-4638-91c8-96b49759c111.jpg)

**Comment by randriksen** [comment]
I've got the same issue, though for me it started on December 14th...
![energy consumption](https://user-images.githubusercontent.com/1292372/146838432-91d69bcb-3a09-464e-bf0c-5d0173f1a0bb.png), 
e

**Comment by Hajman** [comment]
This issue is fixed for me as of core-2022.2.  It didn't fix all of the broken day since 12 November but since updating to 2022.2, the panel is no longer registering a huge negative usage value at the beginning of each day.

![image](https://user-images.githubusercontent.com/21141807/152574938-43903b18-a04a-465f-92ff-bf9b47ff1f7d.png)
