### ISSUE TITLE
Area picker (e. g. in Device dialog) doesn't work in Chrome

### ISSUE THREAD

**Issue by rakragh** [home-assistant/frontend#10700]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Area input (e. g. in Device dialog; component 'ha-area-picker') doesn't work in Chrome.

Before reporting here I updated to latest version of Chrome - it doesn't work before and it doesn't work with latest version.

It works in FireFox and it works in Chrome for Android but not for Chrome desktop.

### Describe the behavior you expected

Picked area is taken by input field.

### Steps to reproduce the issue

1. Open HA frontend in Chrome
2. Choose a device and use pen or settings icon
2. Try to assign a area

There is nothing (to see) inside console (of Chrome DevTools).

### What version of Home Assistant Core has the issue?

2021.11.5

### Which operating system are you using to run this browser?

Linux

**Comment by spacegaier** [comment]
I cannot reproduce that issue in Win 10 + latest Chrome (neither on HA dev version nor with 2021.11.2).

Can you please explain in more detail what "doesn't work" mean? Is there no input field, is it disabled, are there no entries, does the dropdown not open, are the items not clickable, ... ?

**Comment by rakragh** [comment]
As described in "Describe the behavior you expected", I expect that picked area (value) is taken by input field.
It works only if I type to input field and filter the list to one result - that result can be choosed.

![LJ9pu23SI4](https://user-images.githubusercontent.com/40203782/143656686-824cd47b-394c-40c9-a8a6-c90ab07fb6f3.gif)

**Comment by ildar170975** [comment]
Cannot reproduce it too.
HA in Docker.
2021.11.5
Chrome 96.0.4664.45, Win10x64.

**Comment by rakragh** [comment]
Then maybe Chrome for Linux!? Pls try it inside Linux.

![image](https://user-images.githubusercontent.com/40203782/143721771-d166fb2f-d886-414e-b26f-e93d4fd46783.png)

![image](https://user-images.githubusercontent.com/40203782/143721778-f5a49f4e-0c4c-43da-ba1b-2aec214b1482.png)

I notice also clicks which do not work - during filtering the list by 'K' and click on 'Küche', first click isn't considered or went wrong (unexpected long delay) and results in not considering selected/clicked item.

I face these issues only in component 'ha-area-picker'.

In my opinion something in direction of:
Event.preventDefault()
Event.stopImmediatePropagation()
Event.stopPropagation()

Everything else of HA FE works fine, therefore it must be related to something tricky or hacky in the component and is not related to Material.

At the moment, I am using Firefox for HA to get around this issue but my browser is Chrome.

**Comment by rakragh** [comment]
Closed because: It was my environment (and my fault). After reading the version details of Chrome, I saw that the flag --enable-experimental-web-platform-features was set - I wasn't aware of that (anymore). Since I disabled that, it works.
