### ISSUE TITLE
[UX][Minor] With dark theme, sortable header looks the same as table entries

### ISSUE THREAD

**Issue by mrand** [home-assistant/frontend#10718]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Minor UX/UI issue.
When using the dark theme, the "header" row for a few of the sortable screens (backups, as well as lovelace dashboards, lovelace resources, adding a lovelace card "by entity", and the Unused entities screens) doesn't really stand out compared to the remainder of the sortable entries.  It actually looks to me like the entries (2021.10, for example) are semi-bolded when they don't really need to be.  Alternative would be to have the header row be a different color (via a theme):

![image](https://user-images.githubusercontent.com/435987/143789488-c3cf8c80-7b3f-4496-9b62-f26d7c444e35.png)

### Describe the behavior you expected

In the light theme, it's obvious that the header row  is a header row because the bolding is noticeable: 

![image](https://user-images.githubusercontent.com/435987/143789572-0802232f-8344-4bdd-9cf3-dc536c2e76a6.png)

Unrelated, I also note a difference that helps make the search bar stand out more on the unused entities screen than it does on the backups or lovelace related screens: the search field has a underline/divider, and no line above it:

![image](https://user-images.githubusercontent.com/435987/143802101-7394e714-f6c5-4a5d-9c6b-1c09c0d8a5d3.png)

### Steps to reproduce the issue

http://homeassistant/hassio/backups

### What version of Home Assistant Core has the issue?

2021.11.5

**Comment by matthiasdebaat** [comment]
It's a minor accessibility issue in my opinion, but it could indeed improve. We have implemented [Material Design](https://material.io/components/data-tables) for our tables and they recently released [Material Design 3](https://m3.material.io). Data Tables haven't been updated yet so I want to wait and see what they do with them and follow their guidelines.
