### ISSUE TITLE
--ha-chip-text-color can't be themed in alarm control panel card

### ISSUE THREAD

**Issue by mrand** [home-assistant/frontend#10712]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

#10393 introduced chips to the alarm control panel, but it doesn't appear to inherit the theme variables, instead it overrides --ha-chip-text-color with --text-primary-color.

Inspector seems to confirm it's ignoring my color request:

![image](https://user-images.githubusercontent.com/435987/143614787-d1b5f86a-1dac-484b-b725-3a5fa18e75c2.png)

### Describe the behavior you expected

Chip text color should change based on theme.

### Steps to reproduce the issue

On my dark theme, I have:

`  ha-chip-text-color: "#000000"`

### What version of Home Assistant Core has the issue?

2021.11.5

**Comment by mrand** [comment]
@ludeeus, I greatly appreciate the response, but wasn't exactly what I was referring to.

The text color on my theme is a light green and doesn't contrast well with the default background color(s) of chips.
For the chips below badges, I adjust --ha-label-badge-label-color to be dark, and I was hoping to be able to do the same for the text of this chip.  Is there a reason not to have this chip use the same --ha-label-badge-label-color, or worst case, introduce a new color variable (which is what I had thought --ha-chip-text-color was - but now it's been removed altogether).

Thanks!

**Comment by ludeeus** [comment]
It's not removed. It's now usable.
