### ISSUE TITLE
[UX][Minor] Certificate Info text seems to use light theme colors rather than dark

### ISSUE THREAD

**Issue by mrand** [home-assistant/frontend#10719]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using the default dark theme, the colors and contrast seems wrong:

![image](https://user-images.githubusercontent.com/435987/143791287-eaae8eba-c1be-496e-93d2-34adade9cf73.png)

### Describe the behavior you expected

Certificate Info should use the text colors from the dark theme rather than the light theme.

### Steps to reproduce the issue

Just browse to http://homeassistant/config/cloud/account and click "Certificate Info."

### What version of Home Assistant Core has the issue?

2021.11.5

### Additional information

Don't quite understand why it's doing this.  I don't see anything overriding the text color [in the code.](
https://github.com/home-assistant/frontend/blob/dev/src/panels/config/cloud/dialog-cloud-certificate/dialog-cloud-certificate.ts)

**Comment by matthiasdebaat** [comment]
Good catch!
