### ISSUE TITLE
text cut off from name & entity_id in developer tools - statistics

### ISSUE THREAD

**Issue by mneuron** [home-assistant/frontend#10732]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The text is cut off if the name and/or entity_id is  long (see screenshot).  
![image](https://user-images.githubusercontent.com/17382871/144029230-213b8eaf-7cf4-476c-8b23-25b9441884fb.png)

### Describe the behavior you expected

as the information is presented as a table make the column size customizable. 
Another option would be the full name in a tooltip when hovering above the item.

### Steps to reproduce the issue

1.  have a entity with a long name or id and open the developertools - statistics tab
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.11.0

### State of relevant entities

```txt
not relevant
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

-

**Comment by spacegaier** [comment]
We could add a tooltip, but the question is if that really helps on it own or whether the table should change for smaller screens similar to what the "States" tab does.
