### ISSUE TITLE
Close button in ha-picture-upload in dialog-person-details does not work

### ISSUE THREAD

**Issue by ondras12345** [home-assistant/frontend#10751]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Close button next to the picture in dialog-person-details (Configuration > People > someone) only removes the picture in the dialog window, but does not modify the person when saved. This makes it completely useless because the picture is still present after you click Update and reopen the same person's details.

### Describe the behavior you expected

The Close button removes the picture and Update stores the change, i.e. the person's picture is removed.

### Steps to reproduce the issue

1. Go to Configuration > People and click on Add person.
2. In the dialog form, click on picture and upload one (click on Crop in the popup). Also give the person a name.
3. Click on Close next to the uploaded picture. See it disappear.
4. Click on Create.
5. In the list of people, observe that the newly created person has the profile picture you uploaded while the form was showing no picture when you clicked Create.

### What version of Home Assistant Core has the issue?

core-2021.11.5

### In which browser are you experiencing the issue with?

Firefox Browser 94.0 (64-bit)

### Which operating system are you using to run this browser?

Ubuntu 20.04.3 LTS

### Additional information

A similar issue has been raised in core: https://github.com/home-assistant/core/issues/59843
However, I don't think this has anything to do with core. It seems to be a frontend problem.

This issue was also discussed on the forums: https://community.home-assistant.io/t/person-yaml/361819/

**Comment by spacegaier** [comment]
Same issue also applies tot he area config dialog. Fix incoming.
