### ISSUE TITLE
Energy graph has only 4 different colours

### ISSUE THREAD

**Issue by wonderiuy** [home-assistant/frontend#10750]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After the 4th device added to energy monitoring, the colour is the same (dark grey). example here: [Image](https://imgur.com/a/ipXKLEO)
I have 12 devices and the latter 8 has all the same colour.
The best would be that they pick the same colour used in single device energy monitoring
Is possible to assign a custom colour the single electric network devices?

### Describe the behavior you expected

Each device with its colour, possibly the same colour used in single device energy monitoring

### Steps to reproduce the issue

1.add more than 4 devices in energy monitoring

### What version of Home Assistant Core has the issue?

2021.11.5

**Comment by bramkragten** [comment]
This is not supposed to be used for devices, but for different sources of energy or different tarrifs.

**Comment by wonderiuy** [comment]
Why not? It's the only graph where you can check hour by hour the power consumption of the variuos sections of the house. My whole house sits in those 12 electrical sections. I find it very useful indeed

**Comment by wonderiuy** [comment]
So please transform this in a feature request with these different solutions:
- Have the graph coloured so we have a nice detailed hourly report of the consumption of each appliances (same colour as the single device)
- OR put an option in single device to add them aggregating in the total consumption graph
- OR put and option to aggregate different sources directly in the total consumption

WIth deces like Shelly 4 Pro EM (or SHelly 3EM) ppl are installing them on top of their power grid, resulting in measuring all the electri zones of their houses. From this, the needs
Thank you in advance

**Comment by bramkragten** [comment]
Please start a discussion
