### ISSUE TITLE
Viewing integrations on desktop is a worse user experience than on mobile

### ISSUE THREAD

**Issue by poldim** [home-assistant/frontend#10752]
### The problem

When viewing things on mobile, I get a better experience than when viewing them on desktop.  This seems counter-intuitive given the larger display (ignoring pixel density).

I've poked around at Chrome's inspect feature to see if I could make it better, and have included those as possible solutions below.  I sure there are better cleaner ways to solve this problem, but any step forward in the right direction would be good

Some examples:
Forecast solar integration:
- On mobile - I can see the full sensor name and their values 
- On desktop - Part of the sensor name with the relevant part (end of the sensor name) not visible.
- Desktop possible solution - change `/html/body/home-assistant//home-assistant-main//app-drawer-layout/partial-panel-resolver/ha-panel-config/ha-config-devices/ha-config-device-page//hass-tabs-subpage/div` from `max-width: 1000px;` to `max-width: 1500px;`

List of integrations:
- On mobile - I can see the full screen list of all of my esphome devices 
- On desktop - Most of the devices are not visible, only 2 devices are seen
- Desktop possible solution - change `/html/body/home-assistant//home-assistant-main//app-drawer-layout/partial-panel-resolver/ha-panel-config/ha-config-integrations//hass-tabs-subpage/div[2]` from `repeat(auto-fit, minmax(250px, 1fr))` to `repeat(auto-fit, minmax(500px, 1fr))` and add `height: 90%;` to force it to use more of the screen

![image](https://user-images.githubusercontent.com/16869713/144152371-8d209e91-abec-4b66-bf34-53e01143a592.png)

![image](https://user-images.githubusercontent.com/16869713/144152623-06128ff1-013a-4719-85ac-6f0ac93fbf31.png)

![image](https://user-images.githubusercontent.com/16869713/144153530-25df43f8-dbb3-4b68-b790-16916806722b.png)

![image](https://user-images.githubusercontent.com/16869713/144152425-727ae53a-6128-4b13-94ee-205c3abc5f19.png)

![image](https://user-images.githubusercontent.com/16869713/144153727-69a4153d-7dca-491b-83ae-580a40ea91ae.png)

![image](https://user-images.githubusercontent.com/16869713/144155757-61bff464-3bb1-4820-b137-bd2fdb9c07cf.png)

### What version of Home Assistant Core has the issue?

core-2021.11.5

### What was the last working version of Home Assistant Core?

n/a

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

core

### Link to integration documentation on our website

core

**Comment by spudsmac** [comment]
Any chance this issue can be reviewed?  It is still happening.
