### ISSUE TITLE
The gauge card doesn't render correctly on Safari 15.1 on macOS / iOS

### ISSUE THREAD

**Issue by raducotescu** [home-assistant/frontend#10766]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In Safari or Safari web-views (e.g. the Home Assistant iOS/macOS companion apps) the `gauge` card doesn't correctly render its dial.

<img width="511" alt="Screenshot 2021-12-02 at 15 00 01" src="https://user-images.githubusercontent.com/170911/144436986-193a5907-e5e0-4c0f-9a73-78dd260ce796.png">

This seems to be due to the way the rotation transformation is applied, via the `transform` SVG attribute [0]:

1. https://github.com/home-assistant/frontend/blob/2a5fc5181e4d1c39588499ac62c4a4fd818508f3/src/components/ha-gauge.ts#L116
2. https://github.com/home-assistant/frontend/blob/2a5fc5181e4d1c39588499ac62c4a4fd818508f3/src/components/ha-gauge.ts#L129

In my test on macOS Safari it seems that the rotation point is not needed anymore (i.e. the transform could be written like: `transform="rotate(<angle>)"`). Furthermore, Safari supports CSS transform rotate, so this could be treated the same like for other browsers.

[0] - https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform

### Describe the behavior you expected

The gauge cards should render correctly, like in all the other browsers (e.g. Firefox, Chrome).

### Steps to reproduce the issue

Have a `gauge` card configured like:
```yaml
- type: gauge
   entity: sensor.temperature
   min: 0
   max: 100
   severity:
     green: 20
     yellow: 22
     red: 25
   name: ' '
```

### What version of Home Assistant Core has the issue?

core-2021.11.5

### In which browser are you experiencing the issue with?

Safari 15.1

### Which operating system are you using to run this browser?

macOS 12.0, macOS 12.1, iOS 15.1, iOS 15.2

### Additional information

The card works correctly on iOS 14.8.1.

**Comment by bls0n** [comment]
Same problem (ios 15.2). Top image is windows and bottom is ios. 

![windows](https://user-images.githubusercontent.com/43529510/146946503-6b189cae-f6fa-4897-9b63-aef8a35b9b77.png)

<img width="414" alt="ios" src="https://user-images.githubusercontent.com/43529510/146946515-d425dc79-fcfb-4090-9e50-9d8f4b82c854.png">

**Comment by mribeiro** [comment]
This clearly is a problem in Apple's Webkit engine.

Safari (Mac/iPhone), App (Mac/iPhone) and Chrome (iPhone does not render this properly).
Chrome on Mac does render it well.

**Comment by northrup** [comment]
Just dropping my render error here as well. Running iOS 15.2 ![image](https://user-images.githubusercontent.com/11050/149131929-d1f73336-5252-4708-928e-5260d40217fd.jpeg)

**Comment by del13r** [comment]
I am having the same issue with chrome 97.0.4692.84 on iOS 15.2.1 
also having the same issue with latest Home Assistant iOS app.
https://github.com/home-assistant/frontend/issues/11421

**Comment by MHerweijer** [comment]
Updates to HA 2022.2.0 and updated the iOS app to version 2022.2 and the gauges are shown correctly again! 

Thanks for your support!
