### ISSUE TITLE
New "Add-ons & Backups (Supervisor) Create backups, check logs or reboot your system" page does not have a back button

### ISSUE THREAD

**Issue by urbozz** [home-assistant/frontend#10791]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

All configuration pages have a back button to get back to http://homeassistant.local:8123/config/dashboard

When visiting "Add-ons & Backups (Supervisor)" the page has no back button

### Describe the behavior you expected

The "Add-ons & Backups (Supervisor)" page has a back button

### Steps to reproduce the issue

1. Visit "Add-ons & Backups (Supervisor) http://homeassistant.local:8123/hassio/dashboard
2. <img width="1286" alt="Screenshot 2021-12-04 at 08 34 23" src="https://user-images.githubusercontent.com/26883465/144703335-f07b4e46-d39c-4edc-be8e-73c5c5aece50.png">

### What version of Home Assistant Core has the issue?

core-2021.12.0b0

### In which browser are you experiencing the issue with?

Google Chrome 96.0.4664.55

### Which operating system are you using to run this browser?

MacOS BigSur 11.5.2 (20G95)

**Comment by ludeeus** [comment]
Your Supervisor version needs to be on 2021.12.0, it was implemented to that version.
