### ISSUE TITLE
Hitbox issue in 2021.12

### ISSUE THREAD

**Issue by hunterjm** [home-assistant/frontend#10790]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the iOS app, mobile Safari, and Chrome rendered as mobile, the switch hitbox is bringing up the More Info dialog instead of toggling the switch.

### Describe the behavior you expected

The switch should toggle and More Info should only appear when clicking on the name.,

### Steps to reproduce the issue

1. Switch chrome to mobile
2. Try clicking a switch entity

https://user-images.githubusercontent.com/747670/144697679-41f984a9-a980-44ba-befb-79f2f301e34a.mp4

### What version of Home Assistant Core has the issue?

core-2021.12.0b0

### What was the last working version of Home Assistant Core?

core-2021.11.x

### In which browser are you experiencing the issue with?

Mobile Safari and Desktop Chrome in Mobile mode.

### Which operating system are you using to run this browser?

Windows 10

**Comment by hunterjm** [comment]
After further testing, this works on lights, but is broken for switches in the entities card.

**Comment by zsarnett** [comment]
I was able to reproduce when toggling switches. Not when toggling lights

**Comment by spacegaier** [comment]
Issue confirmed and fix is on its way
