### ISSUE TITLE
Bulb color for RGBW light

### ISSUE THREAD

**Issue by Aohzan** [home-assistant/frontend#10814]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The color of the bulb is black for a RGBW light with low white level

### Describe the behavior you expected

I expect a white bulb, maybe a little dark to show the low level

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

202111

### In which browser are you experiencing the issue with?

All

### State of relevant entities

```txt
supported_color_modes: rgbw
color_mode: rgbw
brightness: 26
hs_color: 0, 0
rgb_color: 26, 26, 26
rgbw_color: 0, 0, 0, 26
xy_color: 0.323, 0.329
supported_features: 32
```

**Comment by Aohzan** [comment]
![image](https://user-images.githubusercontent.com/2736322/144897833-0de8c0be-a097-4bb1-bfad-099428af2dec.png)

**Comment by Aohzan** [comment]
Up :)

**Comment by zsarnett** [comment]
I believe this is more a backend issue than frontend. RGB 0, 0, 0 is black. We are only showing what is told to us

**Comment by Aohzan** [comment]
For RGB yes, but for RGBW, 0,0,0,26 means White, exactly like 26,26,26 for RGB

**Comment by Aohzan** [comment]
Maybe you can read `rgb_color` attribute to get color and not the first three elements of `rgbw_color`:
```
rgb_color: 26, 26, 26
rgbw_color: 0, 0, 0, 26
```

**Comment by Aohzan** [comment]
still here :+1:

**Comment by Aohzan** [comment]
Maybe the HTML code can help ? rgb(26, 26, 26) is black with the conversion, is the brightness ok ?

html code
```html
<ha-state-icon style="color: rgb(26, 26, 26); filter: brightness(54.2%);" data-domain="light" data-state="on"></ha-state-icon>
```

state
```yaml
supported_features: 32
color_mode: rgbw
brightness: 26
hs_color: 0, 0
rgb_color: 26, 26, 26
rgbw_color: 0, 0, 0, 26
xy_color: 0.323, 0.329
```

**Comment by Aohzan** [comment]
no :pray:

**Comment by Aohzan** [comment]
I tried a modification in this PR
Otherwyse I saw that it work on new tile
![image](https://github.com/home-assistant/frontend/assets/2736322/300870b7-5147-4de5-9712-bddd7a86fc6b)
![image](https://github.com/home-assistant/frontend/assets/2736322/3163ecd6-065e-4b3c-ab1d-bef6c7fe089c)


Example with color
![image](https://github.com/home-assistant/frontend/assets/2736322/fa7422bf-d314-42a9-8439-41e6845b01d1)
![image](https://github.com/home-assistant/frontend/assets/2736322/8e2cd171-2858-4371-a428-3c60557e05a8)

**Comment by Aohzan** [comment]
As the new tile entity doesn't have the issue, I can be satisfied with that
Thanks
