### ISSUE TITLE
Mobile theme is not getting applied to android app since 2021.12 (Not an app issue)

### ISSUE THREAD

**Issue by LasseRosenow** [home-assistant/frontend#10823]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I just updated home assistant frontend etc. to 2021.12 and now when I start the android app, it is not coloring the navigation and status bar like the rest of the app anymore. 
But if I navigate to the settings page it works.

This is not a bug of the android app, as I did not update the android App.

The android app is listening on POST events of the webview and checks for a json object with the type "config/get" to trigger a painting of the navigation bars, so I guess the issue is, that the frontend used to do something with "config/get" on startup, but does not do so anymore.

The relevant part in the android app is [here](https://github.com/home-assistant/android/blob/ab6cf026719c1a1c25bb6818a6dbc9782c5f3bc0/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L478) and [here](https://github.com/home-assistant/android/blob/ab6cf026719c1a1c25bb6818a6dbc9782c5f3bc0/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L502)

### Describe the behavior you expected

The status and navigation bars in the android app should be colored => The json object of type "config/get" event should be send

### Steps to reproduce the issue

1. Update home assistant frontend to 2021.12
2. Open android app preferably in light mode, as its easier to tell
3. See that the status bar is black.
4. Open frontend settings
5. See that the status bar is now colored
...

### What version of Home Assistant Core has the issue?

2021.12.0b3

### What was the last working version of Home Assistant Core?

2021.11.5

### In which browser are you experiencing the issue with?

Android App

### Which operating system are you using to run this browser?

Android

**Comment by balloob** [comment]
We no longer call `config/get` on page load because we no longer show the app configuration as a sidebar entry, it's now part of the config panel. 

I'm surprised Android uses this to trigger the coloring. I guess it used to be safe indicator that the user was logged in because the sidebar wouldn't be shown otherwise. 

CC @JBassett @dshokouhi

**Comment by balloob** [comment]
Workaround and future event to have a fix added in #10819
