### ISSUE TITLE
Update screen is showing previous version number of Home Assistant

### ISSUE THREAD

**Issue by pimw1** [home-assistant/frontend#10826]
### The problem

While updating the home assistant beta, it is showing the version number of the previous beta.
For example: updating from 2021.12.0b3 to 2021.12.0b4

![image](https://user-images.githubusercontent.com/74881023/145279369-18d1e48a-f9ad-423a-aeb9-86973b918209.png)

![image](https://user-images.githubusercontent.com/74881023/145279411-20f077e1-ee59-44c6-9d6f-95270718d880.png)

### What version of Home Assistant Core has the issue?

core-2021.12.0b4

### What type of installation are you running?

Home Assistant Supervised

**Comment by balloob** [comment]
Fixed in latest supervisor beta.
