### ISSUE TITLE
Release note link for Supervisor/Core update available references installed version

### ISSUE THREAD

**Issue by alandtse** [home-assistant/frontend#10830]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When the Supervisor has a new update, (myhass/hassio/update-available/supervisor) the release notes link points to the version I'm on and not the new release.
For example, the UI reports:
```
You have 2021.12.0 installed. Click update to update to version 2021.12.1
```
And the `Open Release Notes` button goes here: https://github.com/home-assistant/supervisor/releases/tag/2021.12.0

### Describe the behavior you expected

Release notes should point to latest version

### Steps to reproduce the issue

1. Wait for Supervisor updates
2. Click on Update available
3. Click on Open Release Notes

### What version of Home Assistant Core has the issue?

core-2021.12.0b4

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

macOS Big Sur

**Comment by alandtse** [comment]
I can also confirm the same error for HA core updates.

**Comment by mpgoebel** [comment]
I do not believe it is referencing the installed version.  In my case i am on 2021.12.0b2 but my release notes opens to the most recent stable version release notes [https://next.home-assistant.io/blog/2021/11/03/release-202111/](url) for what I just clicked.

**Comment by mpgoebel** [comment]
The link for the update when installing a beta still pulls us into the previous stable releases notes as opposed to directing to the beta release notes.

Matt Goebel, Inventory Manager
Building Materials Division
3700 W Irving Wichita, KS 67213
M 316.680.8442
***@***.******@***.******@***.***<https://twitter.com/starlumber>
