### ISSUE TITLE
Key 'id' is not expected or not supported by the visual editor.

### ISSUE THREAD

**Issue by ridderr** [home-assistant/frontend#10866]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In automation defining a trigger on a State, the Trigger ID which can be defined to be used in a Choice, is not accepted anymore. An error "Key 'id' is not expected or not supported by the visual editor." is given.
Editing in YAML is possible but this was working in Visual mode.

When a new trigger is defined and something is entered in the Trigger ID field, the editor switches over to YAML editing.

### Describe the behavior you expected

Editing of the trigger-id was be possible with the visual Editor when entering a state trigger. Enter something in the trigger-id field a the error is given. 

### Steps to reproduce the issue

1. Open automation script
2. Create a State trigger and enter a Trigger ID. As soon something is entered in the trigger-id field the visual editor flips to YAML editing and showing the error message "Key 'id' is not expected or not supported by the visual editor."

![image](https://user-images.githubusercontent.com/12719238/145675170-65d0ac1c-670b-4c39-937b-d32c2ca73ae8.png)

### What version of Home Assistant Core has the issue?

core-2021.12.0b6

### What was the last working version of Home Assistant Core?

core-2021.11

### In which browser are you experiencing the issue with?

Chrome Version  96.0.4664.93 (Officiële build) (64-bits)

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
platform: state
entity_id: binary_sensor.keukenraam_access_control_window_door_is_open
id: door_sensor
```

**Comment by frenck** [comment]
fixed in #10851
