### ISSUE TITLE
Microsoft Edge - Always have to provide login data twice

### ISSUE THREAD

**Issue by hklages** [home-assistant/frontend#10862]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When login with Microsoft Edge Version 96.0.1054.43 (Official build) (64-bit) I always have to provide login user name and password twice. After entering the first time, the login screen (without entered data) shows up again and I have to login again. 
It is interesting that the Notification panel does not show the "login failed" information.  

This is related to Microsoft Edge! Firefox works as expected.

### Describe the behavior you expected

Obvious.

### Steps to reproduce the issue

1. enter "homeassistant.local:8123 in Browse
2. enter login credentials

### What version of Home Assistant Core has the issue?

core-2021.11.5

### In which browser are you experiencing the issue with?

Microsoft Edge, Version 96.0.1054.43 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Microsoft Windows

### State of relevant entities

```txt
n/a
```

### Problem-relevant frontend configuration

```yaml
n/a
```

**Comment by sarunyu** [comment]
chrome is issue too

**Comment by hklages** [comment]
> chrome is issue too

Do you have either "I don't care about cookies" or "Microsoft Editor: Spelling & Grammar Checker" installed. 

When I disable both the problem does not occur.
