### ISSUE TITLE
`undefined is not an object (evaluating 'this._map.layerPointToLatLng')` in Zone editor

### ISSUE THREAD

**Issue by beaulebens** [home-assistant/frontend#10874]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I see this in Safari (and the macOS app), but not in Chrome or Firefox.

When I edit a Zone, I get an error showing up in the top of the zone details dialog (although the changes do seem to change).

### Describe the behavior you expected

I expected it to save without error, and display a "success" message, and/or close the dialog.

### Steps to reproduce the issue

1. Click on Map in the sidebar
2. Click Edit (pencil icon, top-right)
3. Select a zone to edit (pencil icon next to a zone)
4. Modify the radius
5. Click Update
6. Observe error `undefined is not an object (evaluating 'this._map.layerPointToLatLng')`

### What version of Home Assistant Core has the issue?

2021.12.0

### In which browser are you experiencing the issue with?

Safari Version 15.1 (16612.2.9.1.30, 16612)

### Which operating system are you using to run this browser?

macOS Big Sur 11.6.1 (20G224)

**Comment by spacegaier** [comment]
Seems to be Safari specific. I just tested it on Win 10 + Chrome and there it works fine (as does Chrome on macOS according to OP).

**Comment by northrup** [comment]
Conformation of this happening as well. I'm running `2022.2.9` via the Docker Image and this happens when using Safari, of which I am using the latest Safari version (`Version 15.3 (17612.4.9.1.8)`)

**Comment by Tezzlicious** [comment]
Still around on 2022.5.5 on a VM with Safari 15.4 (17613.1.17.1.6).

**Comment by rubythetor** [comment]
Confirmed still happening.  Safari Version 15.5 (17613.2.7.1.8)

**Comment by kolafson777** [comment]
Still happening on Safari 15.6.1, HA 2022.9.4
