### ISSUE TITLE
"Visual editor is not supported for this configuration" after a state field is filled in, and then deleted.

### ISSUE THREAD

**Issue by Chunkywolf** [home-assistant/frontend#10884]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating or editing Automations with a State condition, if the State field is filled in, and then deleted, it gives an error.
"Visual editor is not supported for this configuration
You can still edit your config in YAML."
The condition then needs to be deleted completely and re-added to edit it with a GUI again.
I have tried this in both Firefox and Chrome.
This seems to have just occurred in the latest update.

### Describe the behavior you expected

It should have just finished deleting text in the field, and stopped there without pulling me out of the GUI.

### Steps to reproduce the issue

1. Create or edit an automation 
2. Create a state condition.
3. Type into state field.
4. Delete all text in state field

### What version of Home Assistant Core has the issue?

2021.12.0

### In which browser are you experiencing the issue with?

Chrome - 96.0.4664.93, Firefox -  95.0

### Which operating system are you using to run this browser?

Windows 10 -  20H2

**Comment by JeroenTuinstra** [comment]
Similar error here after update to 2021.12.0. State triggers seem to generate this error: 

```
Visual editor is not supported for this configuration 

    The provided value for 'for' is not supported by the visual editor. We support (string) but received ({"hours":0,"minutes":0,"seconds":0,"milliseconds":0}).
    Key 'for.milliseconds' is not expected or not supported by the visual editor.

You can still edit your config in YAML.
```
The yaml is very simple:

```
platform: state
entity_id: sensor.jeroens_apple_watch_room_presence
to: bedroom
for:
  hours: 0
  minutes: 0
  seconds: 0
  milliseconds: 0
id: jeroen.watch.inroom
```

**Comment by JeroenTuinstra** [comment]
Sorry for me the issue was that from 2021.11.5 `milliseconds: 0` is added to all state triggers and somehow this no longer supported in 2021.12.0, deleting `milliseconds: 0` takes care of the problem.

**Comment by emontnemery** [comment]
@JeroenTuinstra Your problem should be fixed by https://github.com/home-assistant/frontend/pull/10879
