### ISSUE TITLE
The system time is broken

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#10887]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

System time is 2 hours behind even though I have set the time zone correctly in the settings

![IncorrectTime](https://user-images.githubusercontent.com/74879713/145725643-c1c65ad7-8a52-41a5-8fd0-b3b61e22109b.png)

### Describe the behavior you expected

The system time must be correct

### Steps to reproduce the issue

1. 
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.12.0

### In which browser are you experiencing the issue with?

Chrome 96.0.4664.93

### Which operating system are you using to run this browser?

Windows 10

**Comment by WRoss7** [comment]
Related to #3354?

**Comment by agners** [comment]
It seems that the OS installation has problems reaching the NTP server to synchronize time. This is unlikely a frontend issue. Closing.
