### ISSUE TITLE
Frontend errors when loading initially on iOS 12

### ISSUE THREAD

**Issue by zacwest** [home-assistant/frontend#10885]
If you are currently experiencing this issue, pull-to-refresh will resolve it each time it occurs.

---

### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When the frontend initially loads, it errors; secondary loads work.

### Describe the behavior you expected

n/a

### Steps to reproduce the issue

Launching the frontend on iOS 12 initially gives (43011179ebb650f0fd4b2b010dedace1d94a8325, but reproduces in the latest):

```
[Error] ReferenceError: Can't find variable: regeneratorRuntime
	(anonymous function) (reactive-element.js:575)
	(anonymous function) (reactive-element.js:628)
	Eval Code (reactive-element.js:1187)
	eval
	./node_modules/@lit/reactive-element/development/reactive-element.js (app.js:2237)
	__webpack_require__ (app.js:2560)
	./node_modules/lit/index.js (app.js:2520:99)
	__webpack_require__ (app.js:2560)
	Eval Code (home-assistant.ts:5)
	eval
	./src/layouts/home-assistant.ts (app.js:1787)
	__webpack_require__ (app.js:2560)
	Eval Code (app.ts:3:101)
	eval
	./src/entrypoints/app.ts (app.js:1721)
	__webpack_require__ (app.js:2560)
	(anonymous function) (app.js:2822)
	Global Code (app.js:2824)
[Error] Unhandled Promise Rejection: ChunkLoadError: Loading chunk src_external_app_external_auth_ts failed.
(error: http://10.0.10.177:8123/frontend_es5/src_external_app_external_auth_ts.chunk.js)
	(anonymous function)
	promiseReactionJob
```

Reloading makes it work.

### What version of Home Assistant Core has the issue?

core-2021.12

### What was the last working version of Home Assistant Core?

core-2021.10 (based on user reports, I believe)

### In which browser are you experiencing the issue with?

iOS 12.x

**Comment by MidnightRacer99** [comment]
same issue for me too!

**Comment by pspeirs** [comment]
Any thoughts, is this being worked on at all.  It only started happening after an update on HA.

_"Seeing the same issue on the wifes phone this morning. She’s running iPhone 6 and stuck at 12.5.5 but hasn’t used the app for a couple of weeks."_

**Comment by Cerize110** [comment]
same issue for me too! I'm running HA core 2021.12.7 in a docker container and ipad ios 12.5.5. and the latest version of the app on the apple store

**Comment by sparment** [comment]
Same issue for me too... updating to HA core 2021.12.8 now hoping maybe this issue was fixed; but I don't see any mention of a front end update in the 2021.12.8 release notes.

**Comment by JSAnyone** [comment]
I have the same issue, maybe the video [here](https://github.com/home-assistant/iOS/issues/1909#issuecomment-1013366221) helps you to better understand the problem.

**Comment by KidA001** [comment]
Same issue here, on v2022.3 - More screenshots/details here: https://community.home-assistant.io/t/ios-app-stuck-at-splash-screen/405235

**Comment by Camatobe** [comment]
It's closed by stale. That's sad. @zacwest Any chance someone can look into this and we can reopen the issue?

I am following reports of this issue for like several months in the community and this git issue.
When I can help or provide any log or debug files let me know!

**Comment by Pix13** [comment]
I also have the issue, no js from HACS is loaded too, making the custom card useless on ios 12+.

**Comment by sircoynie** [comment]
Any update on this?
