### ISSUE TITLE
Non-Administrator Users dont have access to the Companion App Settings

### ISSUE THREAD

**Issue by danielang** [home-assistant/frontend#10894]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since the union of the settings in 2021.12 users which are not assigned to admin role can no longer go to the app configuration since it is hidden in the not accessible settings screen now.  

### Describe the behavior you expected

As a non admin user I still want to configure my cpmpanion app settings.

### Steps to reproduce the issue

1. Log in as a non admin user
2. No settings are shown in the sidebar

### What version of Home Assistant Core has the issue?

core-2021.12.1

### What was the last working version of Home Assistant Core?

core-2021.11.x

### In which browser are you experiencing the issue with?

Android Web View

### Which operating system are you using to run this browser?

Android 12

**Comment by spacegaier** [comment]
Will be fixed by https://github.com/home-assistant/frontend/pull/10890.
