### ISSUE TITLE
Automation tracer for choose shows different number in step details and trace timeline

### ISSUE THREAD

**Issue by scop** [home-assistant/frontend#10895]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Rather minor UI thing, but the automation tracer shows different number of the chosen option in step details vs trace timeline. Step details appears to use 0 for the first one, trace timeline uses 1.

![Screenshot from 2021-12-13 14-35-02](https://user-images.githubusercontent.com/109152/145814181-788d41f6-e115-41a6-b293-7c81b055a67c.png)
![Screenshot from 2021-12-13 14-35-20](https://user-images.githubusercontent.com/109152/145814217-6ee3c8b5-d57c-4b84-b332-d7762dd82c69.png)

### Describe the behavior you expected

In this particular case, either 0 for both, or 1 for both. But more generally, the same number for both.

### Steps to reproduce the issue

Look at the trace for an automation containing a "choose" action.

### What version of Home Assistant Core has the issue?

core-2021.12.1

**Comment by emontnemery** [comment]
Please download and attach the trace here too

**Comment by emontnemery** [comment]
I've a trace from one of my own automations.
Screenshots:
![image](https://user-images.githubusercontent.com/14281572/146792285-f88f67d0-963e-4c67-8074-7dea48b4b4fc.png)
![image](https://user-imag

[trace automation.spdif_switch_lego_room 2021-12-20T14_52_13.354265+00_00.json.zip](https://github.com/home-assistant/frontend/files/7746321/trace.automation.spdif_switch_lego_room.2021-12-20T14_52_13.354265%2B00_00.json.zip)
es.githubusercontent.com/14281572/146792316-c744a2de-a3fc-4b11-9001-ba07a55b9225.png)

**Comment by scop** [comment]
Yep, that's the issue: "Result: choice: 1" vs "Choose: Option 2 executed"

**Comment by spacegaier** [comment]
That one is a bit tricky. We had adjusted the user-friendly timeline view to match the automation editor UI and showing 1..n (https://github.com/home-assistant/frontend/pull/10059).

But the technical returned data from the run itself is using the technical values 0..n for debugging, to not interfere with the real technical trace data.

=> I understand the raised point here, but I am not sure if going back to showing 0/0 or 1/1 is really better.

**Comment by scop** [comment]
I don't think this is stale.

**Comment by emontnemery** [comment]
Do you have a suggestion for how to fix this? The problem is that we try to be user friendly in the graph but the "step details" just shows the trace data.
