### ISSUE TITLE
Met Office Integration Broke 

### ISSUE THREAD

**Issue by thorrrr** [home-assistant/frontend#10906]
![0D63AE22-0CF5-441E-9BF2-4B03745A430B](https://user-images.githubusercontent.com/8170673/145904682-50f14b8e-46f9-4656-8deb-eef940238d1c.jpeg)
![74B4F725-F996-4651-8351-00C3BB127EDA](https://user-images.githubusercontent.com/8170673/145904688-8f115341-30d1-41ae-a6ec-6191c09cd832.jpeg)
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I added it to forum here https://community.home-assistant.io/t/met-office-intergration-broke-on-latest-release/366609?u=thorrrr
This has photos but basically just broken the data display days and hours wrong 

### Describe the behavior you expected

To see the weather daily and by the hour

### Steps to reproduce the issue

1.Just look at it
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.12.1

### What was the last working version of Home Assistant Core?

Yes 

### In which browser are you experiencing the issue with?

Any

### Which operating system are you using to run this browser?

Win 11 , Win 10 IOS 15

**Comment by spacegaier** [comment]
Please add the state of your entity into the issue template. We need to see what the backend actually provides, to check whether it is a frontend or a backend issue.

**Comment by thorrrr** [comment]
![Dell - Screenshot 14-12-2021 - 02](https://user-images.githubusercontent.com/8170673/146002823-a42e02b8-8ab5-49a4-984f-d2c5db4de624.jpg)

**Comment by thorrrr** [comment]
temperature: 10
humidity: 86
wind_bearing: SW
wind_speed: 11
visibility: Good - 10-20
forecast: 
- datetime: '2021-12-15T12:00:00+00:00'
  condition: sunny
  precipitation_probability: 0
  temperature: 10
  wind_bearing: SW
  wind_speed: 11
- datetime: '2021-12-16T00:00:00+00:00'
  condition: cloudy
  precipitation_probability: 13
  temperature: 6
  wind_bearing: SE
  wind_speed: 2
- datetime: '2021-12-16T12:00:00+00:00'
  condition: cloudy
  precipitation_probability: 13
  temperature: 10
  wind_bearing: SW
  wind_speed: 4
- datetime: '2021-12-17T00:00:00+00:00'
  condition: cloudy
  precipitation_probability: 11
  temperature: 4
  wind_bearing: ESE
  wind_speed: 7
- datetime: '2021-12-17T12:00:00+00:00'
  condition: cloudy
  precipitation_probability: 12
  temperature: 7
  wind_bearing: ESE
  wind_speed: 4
- datetime: '2021-12-18T00:00:00+00:00'
  condition: cloudy
  precipitation_probability: 18
  temperature: 4
  wind_bearing: ESE
  wind_speed: 4
- datetime: '2021-12-18T12:00:00+00:00'
  condition: cloudy
  precipitation_probability: 11
  temperature: 6
  wind_bearing: SE
  wind_speed: 7
- datetime: '2021-12-19T00:00:00+00:00'
  condition: cloudy
  precipitation_probability: 17
  temperature: 2
  wind_bearing: ESE
  wind_speed: 4
- datetime: '2021-12-19T12:00:00+00:00'
  condition: cloudy
  precipitation_probability: 12
  temperature: 5
  wind_bearing: ESE
  wind_speed: 4

attribution: Data provided by the Met Office
friendly_name: Met Office Southport Daily



type: weather-forecast
entity: weather.met_office_southport_daily
show_forecast: true
secondary_info_attribute: temperature

**Comment by alkissack** [comment]
metOffice API provides a day and night set of data for a single day

**Comment by spacegaier** [comment]
With the upcoming release today, the weekday should be back in the more-info dialog which will provide some more clarity, but overall not a bug as the frontend correctly renders, what the backend integration provides as data.
