### ISSUE TITLE
Getting and setting the states of entities not working

### ISSUE THREAD

**Issue by owillems** [home-assistant/frontend#10901]
### The problem

After the latest core update core-2021.12.0 it's no longer possible to getting and setting the states of entities. In the Developer Tools section. It's not working with Firefox and Chrome.
 

### What version of Home Assistant Core has the issue?

2021.12.0

### What was the last working version of Home Assistant Core?

2021.11.5

### What type of installation are you running?

Home Assistant OS

**Comment by spacegaier** [comment]
Please provide some more information? What specifically is not working? Do you get errors in your browser log?

Is the whole table gone (since you said you cannot even see entity states anymore)?

**Comment by owillems** [comment]
Normally when tapping on an entity In the developer tools section you should be able to see the state of an entity on the top of the page, and it was possible to change the state of an entity. After updating to core-2021.12.0 I am still able to open the developer tools section, but when tapping on an entity the state of the entity is not showing up anymore. 

my browser log (Firefox) shows no errors, but only two warnings 
(The resource at “http://192.168.2.20:8123/static/fonts/roboto/Roboto-Medium.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly.). 

The browser log of Chrome does not show any errors or warnings.

**Comment by spacegaier** [comment]
Correct, so no bug.
