### ISSUE TITLE
Energy dashboard bar graphs displaying with wrong time-frame

### ISSUE THREAD

**Issue by junaid755** [home-assistant/frontend#10902]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

 I am using Home-assistant in a docker container which is running on Debian 11
My energy dashboard shows the graphs with wrong time frame (starts from 23:30 to 00:30) and also ends with (23:30 to 00:30)
The kwh sensor is an esphome sensor and it resets the daily power usage at the correct time.
This same issue is also displayed from the Home Assistant app running on android and also from a windows 10 machine with Firefox browser. 
 Also my docker container's /etc/localtime is in sync with the host which is done in docker-compose
![12](https://user-images.githubusercontent.com/47344977/145866778-de852359-3afe-43ff-9143-19bb099ee9e5.png)
![3](https://user-images.githubusercontent.com/47344977/145867426-08e2e06e-8366-4ad7-9ef6-cf1ff968d9c6.png)

### Describe the behavior you expected

 I expect my energy dashboard to have the bar graphs with correct time frames

#### 1. I used Docker-compose to start a **New** Home-Assistant instance

docker-compose.yml file
```
version: "3"
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant
    volumes:
       - /etc/localtime:/etc/localtime:ro 
```
#### 2. Added esp-home integration for power sensor

esphome.yaml file
```
sensor:
  - platform: adc
    id: analog
    pin: GPIO33
    attenuation: 11db
    update_interval: never
  - platform: ct_clamp
    name: Measured Current
    id: current
    sensor: analog
    update_interval: 5s

  - platform: total_daily_energy
    name: "Total Daily Power"
    power_id: my_power

  - platform: template
    id: my_power
    name: "Measured Power"
    lambda: return id(current).state * 230.0 / 1000; 
    unit_of_measurement: 'kW'
    update_interval: 5s
time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Asia/Kolkata
 
```
### The time frame is still skewed
![graph](https://user-images.githubusercontent.com/47344977/145872796-d6f00635-6114-4c7c-99df-522ce0ba7a75.png)

### If it helps I had similar issue with the previous HA version (2021.11.5)

![energy-dashboard](https://user-images.githubusercontent.com/47344977/145873413-8e6ed310-78d1-4f78-bbc1-c41d74bc6bd8.png)
### After updating to core.2021.12  the weekly and montly start from the correct date so now its only the daily view that's messed up
![betavsstable](https://user-images.githubusercontent.com/47344977/145873660-688ba7fc-24ca-412d-9419-64cb81c46d25.png)

### What version of Home Assistant Core has the issue?

core-2021.12.1

### In which browser are you experiencing the issue with?

Firefox 78.15.0esr (64-bit)

### Which operating system are you using to run this browser?

Debian 11 (bullseye)

## I am new to Github and this is my first issue report. I tried to include the necessary information, but if i have missed any please ask and I will provide ASAP. 
# Thanks.

**Comment by emontnemery** [comment]
Please confirm the timezone configuration of:
- The host running Home Assistant
- Home Assistant timezone (configured via YAML or frontend: https://www.home-assistant.io/docs/configuration/basic/)
- The computer on which you have collected the firefox screenshots

**Comment by junaid755** [comment]
- The Host and the computer with Firefox is the same computer
- There wasn't any timezone configuration in the yaml  file, I tested after adding one but still the same skew with different devices
``` 
homeassistant:
  time_zone: "Asia/Kolkata"
```
- I ran following commands both in the host and in the Home Assistant container
### Host (Debian 11)
```
root@llinux# date
Tuesday 14 December 2021 11:22:11 AM IST

```
```
root@linux# cat /etc/timezone
Asia/Kolkata
```
```
root@linux# zdump /etc/localtime 
/etc/localtime  Tue Dec 14 11:51:40 2021 IST
```
```
root@linux:/# timedatectl
               Local time: Tue 2021-12-14 11:49:31 IST
           Universal time: Tue 2021-12-14 06:19:31 UTC
                 RTC time: Tue 2021-12-14 06:19:31
                Time zone: Asia/Kolkata (IST, +0530)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

```
### Home Assistant Docker Container
```

```
```

```

**Comment by junaid755** [comment]
### Additional findings/information
- When I use the custom mini-graph-card with the consumed energy sensor, It shows everthing correctly
-  Also I don't if this is something of concern but I noticed that the  statistics in the sqlite database are saved in UTC timeframe like in the image from 00:00 to 01:00 (the values changes from 0.284 to 0.681) i.e 0.397 kWh, could it be using those values and adding +5:30 for timezone adjustment ?, or maybe I am looking in the wrong place?
- So far I can only assume that there is some obvious misconfiguration from my end, but sadly I just couldn't pinpoint on what it is.
Any help is greatly appreciated!
```
type: custom:mini-graph-card
entities:
  - sensor.total_daily_power
hours_to_show: 12
aggregate_func: delta
group_by: hour
show:
  graph: bar

```
![twographs](https://user-images.githubusercontent.com/47344977/145977649-fc94fc7c-acb7-43c9-ac09-c25887e6bc1a.png)
![database2](https://user-images.githubusercontent.com/47344977/145978815-f84b0af3-766f-4e14-828d-346e45cd4368.png)

**Comment by emontnemery** [comment]
@junaid755 You're right, everything is stored as UTC in the database, with statistics compiled hourly.
This is obviously a problem for timezones with 30m offsets, such as India.

That means this is most likely correct:, but not ideal:
![image](https://user-images.githubusercontent.com/14281572/145986049-b37d1a2b-e30e-49c3-b4e6-5ba2cf8c4b04.png)

Whereas this is incorrect:
![image](https://user-images.githubusercontent.com/14281572/145986126-4ddb8aef-8c7a-4256-965a-9041bf40e798.png)

**Comment by junaid755** [comment]
@emontnemery , Thanks for the reply. Aren't both graphs correct respective to their time-frame?
I assume the native graphs are correct to displayed time frame since it uses values from the database
and mini-graph-card is also correct to the displayed time-frame as it uses running values from the raw esp sensor and it divides it into correct time buckets, instead of using those divided values from the  database?
Being said that I wish there could be a fix that lets us save values with 30 min offset in the database.
 But I guess that wouldn't be preferable as it would break other things right?
For now I am using the card mini graph as it updates the values live. and I hope the values it displays is correct to the displayed time frame.

**Comment by emontnemery** [comment]
@junaid755 
> mini-graph-card is also correct to the displayed time-frame as it uses running values from the raw esp sensor and it divides it into correct time buckets, instead of using those divided values from the database

You're right, I somehow thought the 2nd graph was using the native statistics card: https://www.home-assistant.io/lovelace/statistics-graph/

> I wish there could be a fix that lets us save values with 30 min offset in the database.
> But I guess that wouldn't be preferable as it would break other things right?

The statistics doesn't necessarily have to be saved on the UTC hour, it could be saved on the local hour instead.
I'm not sure how to handle the user reconfiguring the timezone though.

We could also compile statistics every 30 minutes.

**Comment by emontnemery** [comment]
Since it's now clarified that the Home Assistant compiles statics on an hourly basis aligned with UTC, and the graphs are probably correct, does it cause any actual problem to have the statistics not aligned with local hours?

**Comment by junaid755** [comment]
I suppose I should also have the esp32 sensor using the UTC by removing the timezone line in the esphome yaml file, so that it now syncs with home-assistant's UTC time
```
time:
  - platform: homeassistant
    id: homeassistant_time
    t̶i̶m̶e̶z̶o̶n̶e̶:̶ ̶A̶s̶i̶a̶/̶K̶o̶l̶k̶a̶t̶a̶
```
and then I wouldn't  have such issues with accuracy when the esp sensor resets at the local time instead of UTC
![resettime](https://user-images.githubusercontent.com/47344977/146001703-0d42bfd2-9e3a-4c71-b7df-531e8651aff7.png)
>does it cause any actual problem to have the statistics not aligned with local hours?

But that would break my live total daily energy usage gauge card in the normal dashboard as it would reset  5:30 am everyday, that wouldn't be ideal right!?...

**Comment by emontnemery** [comment]
I don't think it matters if your esphome timezone is UTC or local, Home Assistant does not care when the sensor resets.

**Comment by junaid755** [comment]
@emontnemery Well in that case I would keep my esp home configured with local timezone and have my gauge card working accurately.
I don't think other than my energy dash board being offset and keeping be awake at night, there isn't any significant issue.

**Comment by emontnemery** [comment]
> keeping be awake at night

Do you mean it kept you awake at night debugging or did something else go wrong?

**Comment by junaid755** [comment]
"keeping me awake at night" as in I couldn't sleep but think how my energy dashboard not being recorded in the right time-frame maybe that was a wrong phrase to use for displaying  me accepting to live with this mild annoyance , lol.
