### ISSUE TITLE
Disabled entities name not displayed

### ISSUE THREAD

**Issue by ollo69** [home-assistant/frontend#10903]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In same case the name of disabled entities in device page is not show:

![image](https://user-images.githubusercontent.com/60491700/145884280-9ac9d6ca-4d9b-49d2-985d-3bc02eb5c120.png)

This seems related to the name of the sensor. If the entity name do not start with the same name of the device, the name is not displayed, otherwise it is.

### Describe the behavior you expected

See the name od disabled entity to better identify them

### Steps to reproduce the issue

1. Go to device page and select a device with disabled entities
2. Click on `+n disabled entities`

### What version of Home Assistant Core has the issue?

core-2021.12.1

### What was the last working version of Home Assistant Core?

core-2021.11.6

### In which browser are you experiencing the issue with?

Google Chrome 96.0.4664.93

### Which operating system are you using to run this browser?

Windows 10

**Comment by Drafteed** [comment]
Any progress on this? I`ve same issue. 


![2021-12-22_18-15-57](https://user-images.githubusercontent.com/11841379/147114445-a173feec-1ecc-46a9-9cc9-cbf8f70a5b0a.gif)

**Comment by spacegaier** [comment]
> Any progress on this? I've same issue.
> 

Given that no PR is linked and no one has been entered as assignee to this ticket => no. Feel free to tackle the bug, otherwise I am afraid you will have to wait until someone comes along who wants to.

**Comment by ildar170975** [comment]
Same as https://github.com/home-assistant/frontend/issues/11067
