### ISSUE TITLE
Two different 'names' for Dutch word 'Serverbeheer' in frontend

### ISSUE THREAD

**Issue by Acradavos** [home-assistant/frontend#10913]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the new settings menu it says "server beheer" with a space. 

![Server_Beheer_1](https://user-images.githubusercontent.com/62036858/145957723-a60859b5-eaa7-4345-9055-c94165272807.png)

### Describe the behavior you expected

In the menu behind the link it says 'Serverbeheer' without a space. This was always shown that way. 

![Server_Beheer_2](https://user-images.githubusercontent.com/62036858/145958610-5dd97cbe-8733-4950-9b86-88059ffc0408.png)

### Steps to reproduce the issue

1. Navigate in the Dutch menu.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.12.1

### In which browser are you experiencing the issue with?

Mozilla Firefox 95.0 x64

### Which operating system are you using to run this browser?

Windows 10 21H2

**Comment by spacegaier** [comment]
Translations are handled by the community => https://developers.home-assistant.io/docs/translations/
