### ISSUE TITLE
The radius of Home zone cannot be customized via new UI

### ISSUE THREAD

**Issue by qqaatw** [home-assistant/frontend#10912]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Due to the `Customizations` tab in `Configuration` removed since core-2021.12.0, I can no longer customize the radius of Home zone through Configuration -> Customizations -> Select Home entity -> Override Radius column.

Besides, because Home entity lacks of a unique ID, the radius cannot be overridden through the Home entity dialog either, which shows:

```
This entity ('zone.home') does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail.
```

This can still be customized via YAML, but I hope to use UI which is more intuitive for users.

### Describe the behavior you expected

Can have some ways to override it via UI.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.12.1

### What was the last working version of Home Assistant Core?

Before core-2021.12.0

### In which browser are you experiencing the issue with?

Google Chrome Version 95.0.4638.54 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

**Comment by spacegaier** [comment]
Not really a bug, since the customize UI was removed by design. So YAML for now is the way. 

And this is technically a duplicate of https://github.com/home-assistant/frontend/issues/3262

**Comment by qqaatw** [comment]
> Not really a bug, since the customize UI was removed by design. So YAML for now is the way.
> 
> And this is technically a duplicate of #3262

Thanks for the reply, and it's duplicate indeed. 

I'm wondering why #3262 has been opened for 3 years, and the radius of Home zone still cannot be overridden through the UI without any workaround. Is there any reason that this functionality has not been implemented?

**Comment by spacegaier** [comment]
Yes, the reason is, no one did so yet (plus for thsi particular point I don't know if there is also a backend reason for it). As an open-source project we depend on people donating their free time to implement and fix things. No one did so far for this feature request.

The current behavior is also correctly documented here: https://www.home-assistant.io/integrations/zone/

> Overriding the Home zone via the UI is not supported.

**Comment by qqaatw** [comment]
Got it. I leave this issue opened and maybe dive into this in case I have some time.
