### ISSUE TITLE
History page is not working / doesn't load

### ISSUE THREAD

**Issue by mlittle408** [home-assistant/frontend#10925]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When viewing the history page. All I see is the spinner and no information is displayed

### Describe the behavior you expected

history page to work

### Steps to reproduce the issue

visit the history page. Tried Chrome and Firefox. Page inspect displays the following in the console:

mwc-circular-progress-base.ts:156 Uncaught (in promise) RangeError: Invalid time value
    at s (mwc-circular-progress-base.ts:156)
    at d (mwc-circular-progress-base.ts:156)
    at ha-chart-base.ts:20
    at ha-chart-base.ts:20
    at Array.forEach (<anonymous>)
    at p (ha-chart-base.ts:20)
    at HTMLElement.value (ha-panel-history.ts:111)

### What version of Home Assistant Core has the issue?

core-2021.12.1

### What was the last working version of Home Assistant Core?

Unknown

### In which browser are you experiencing the issue with?

Chrome Version 96.0.4664.93 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 64bit / Android app as well

### Javascript errors shown in your browser console/inspector

```txt
mwc-circular-progress-base.ts:156 Uncaught (in promise) RangeError: Invalid time value
    at s (mwc-circular-progress-base.ts:156)
    at d (mwc-circular-progress-base.ts:156)
    at ha-chart-base.ts:20
    at ha-chart-base.ts:20
    at Array.forEach (<anonymous>)
    at p (ha-chart-base.ts:20)
    at HTMLElement.value (ha-panel-history.ts:111)
```

**Comment by mlittle408** [comment]
turns out it was an issue with browser_mod. Fixed in configuration.yaml

**Comment by vvarga01** [comment]
> turns out it was an issue with browser_mod. Fixed in configuration.yaml

Hi!
Could you please explain what was the fix in configuration.yaml? I have the same problem.
Thanks!

**Comment by mlittle408** [comment]
I originally had this in my configuration.yaml:

browser_mod:

and changed it to this:

browser_mod:
  prefix: 'browser_mod_'

**Comment by mlittle408** [comment]
make sure you indent prefix: 'browser_mod_'

**Comment by mlittle408** [comment]
> > turns out it was an issue with browser_mod. Fixed in configuration.yaml
> 
> Hi! Could you please explain what was the fix in configuration.yaml? I have the same problem. Thanks!

I originally had this in my configuration.yaml:

browser_mod:

and changed it to this:

browser_mod:
prefix: 'browser_mod_' (make sure you indent this line)

**Comment by vvarga01** [comment]
> > > turns out it was an issue with browser_mod. Fixed in configuration.yaml
> > 
> > 
> > Hi! Could you please explain what was the fix in configuration.yaml? I have the same problem. Thanks!
> 
> I originally had this in my configuration.yaml:
> 
> browser_mod:
> 
> and changed it to this:
> 
> browser_mod: prefix: 'browser_mod_' (make sure you indent this line)

Thank you! :)

**Comment by mlittle408** [comment]
> > > > turns out it was an issue with browser_mod. Fixed in configuration.yaml
> > > 
> > > 
> > > Hi! Could you please explain what was the fix in configuration.yaml? I have the same problem. Thanks!
> > 
> > 
> > I originally had this in my configuration.yaml:
> > browser_mod:
> > and changed it to this:
> > browser_mod: prefix: 'browser_mod_' (make sure you indent this line)
> 
> Thank you! :)

Did it fix your problem?

**Comment by cdrnet** [comment]
I seem to have the same problem in core-2021.12.6 - but I don't have/use browser_mod at all.

**Comment by Deejayfool** [comment]
Hello,
I've the same problem but I don't use browser_mod either. And I don't think it's related to the issue mentionned above because I didn't delete input_datetime.
If someone found a solution for this, I'ld be glad to hear it 😊 .

**Comment by cdrnet** [comment]
In my case the problem went away by itself once the problematic event/data went out of the time range of the history page. Not fixed, but I'm no longer affected by it.

**Comment by juame** [comment]
I had the same issue with v2021.12.7. After purging the recorder history with following script it is working again:
```
alias: Recorder CleanUp Script
sequence:
  - service: recorder.purge
    data:
      repack: true
      apply_filter: true
      keep_days: 0
mode: single
```
It's more a workaround than a solution...

**Comment by Deejayfool** [comment]
Thanks @juame ! I lost all my old energy values but at least history is now working again 👍 .

**Comment by vvarga01** [comment]
I don't know if it's the same bug, or not, but I figured out that in my case the problem occurs when the Start date or the End date time after 12:00 (13:00 for example). I use 24 hours time format, but I tried with 12 hours also.
I have the same error on Logbook page.
This problem occurs first in 2011.11.2 and still exists on 2022.2.1.
In the browser console I see the following:
```
Uncaught (in promise) RangeError: Invalid time value
    at s (frontend_latest/9f5922e0.js:1:1159)
    at d (frontend_latest/9f5922e0.js:1:4723)
    at frontend_latest/60601f58.js:56:1571
    at frontend_latest/60601f58.js:56:1684
    at Array.forEach (<anonymous>)
    at h (frontend_latest/60601f58.js:56:989)
    at r.value (frontend_latest/3c471dc4.js:54:1228)
```
