### ISSUE TITLE
Non existing entities can't be removed from the energy dashboard

### ISSUE THREAD

**Issue by gpgmailencrypt** [home-assistant/frontend#10933]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Entities that have been added to to the energy dashboard and don't exist any more can't be removed from the dashboard, because there is no remove button

### Describe the behavior you expected

Have a button with which a non-existent entity can be removed

### Steps to reproduce the issue

1. add a sensor to the energy dashboard (e.g. a z-wave sensor named sensor.my_energy_kwh)
2. remove the sensor from the integration (e.g. exclude it from z-wave)
3. you will still see sensor.my_energy_kwh in the energy settings with a yellow background and the information, that it doesn't exist. But there is no way to remove the entry
...

### What version of Home Assistant Core has the issue?

core-2021.12.2

### In which browser are you experiencing the issue with?

Firefox 95.0

### Which operating system are you using to run this browser?

Linux Mint 20.1

**Comment by owenglaze** [comment]
I am having the exact same issue with deleted utility meter energy sensors clogging up the drop-down menu on the energy dashboard. These zombie sensors do not exist in home assistant. They also appear to prevent new energy sensors that actually exist from appearing in the menu (the drop-down menu only shows 8 sensors no matter what). I had to change the name of one of my new sensors to a zombie sensor so I could actually select it (total_grid_energy_delivered for my "Grid Energy Returned" sensor).

![image](https://user-images.githubusercontent.com/90290773/146445429-9e0667bd-ffc6-4bfc-b0be-edfecf5ef1ff.png)
