### ISSUE TITLE
Frontend Error since 2021.12 on old device

### ISSUE THREAD

**Issue by JavierNR** [home-assistant/frontend#10931]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hello,

I have a device with an old operating system (Windows XP Embedded), and since 2021.12 this device doesn't load home assistant interface.
I know this is an old OS and chrome has stopped to update the browser, but it's a panel PC which have an control software and runtime on it, so.. it's difficult to replace with an upgraded PC.
The rest of the browsers that connect to the same instance works good.

I've tested ssl and non-ssl connection to HA instance.

I'm attaching a photo of the issue
![image](https://user-images.githubusercontent.com/1872120/146227726-58e0ba1f-5995-4606-9118-66f1f9210749.png)

### Describe the behavior you expected

Correctly load the frontend

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.12.1

### What was the last working version of Home Assistant Core?

core-2021.11.0

### In which browser are you experiencing the issue with?

Google Chrome 49.0.2623.112

### Which operating system are you using to run this browser?

Windows XP Service Pack 3 (Windows Embedded Standard)

### Javascript errors shown in your browser console/inspector

```txt
The key "viewport-fit" is not recognized and ignored.

Failed to set referrer policy: The value 'same-origin' is not one of 'always', 'default', 'never', 'no-referrer', 'no-referrer-when-downgrade', 'origin', 'origin-when-crossorigin', or 'unsafe-url'. This document's referrer policy has been left unchanged.

Uncaught SyntaxError: Unexpected token import

Uncaught SyntaxError: Unexpected token import

app.7d27b784.js:2 Uncaught ReferenceError: regeneratorRuntime is not defined
(anonymous function) @ app.7d27b784.js:2
o.37500 @ app.7d27b784.js:2
a @ app.7d27b784.js:2
(anonymous function) @ app.7d27b784.js:2
(anonymous function) @ app.7d27b784.js:2
(anonymous function) @ app.7d27b784.js:2
```

**Comment by mumlax** [comment]
I can confirm this behavior.

HA core-2021.12.1, visited with Google Chrome Version 56.0.2924.76 (64-bit) on Linux Mint 18.3.
