### ISSUE TITLE
Incorrect decimal separator used to show wind bearing

### ISSUE THREAD

**Issue by kyberias** [home-assistant/frontend#10939]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using Finnish language and related regional settings for number formatting, when an entity card for Home entity is added to a Lovelace dashboard and wind bearing is selected to be shown, the number uses "." as the decimal incorrectly. All other number shown in other types of entities use the correct comma "," as decimal separator.

![image](https://user-images.githubusercontent.com/958404/146321344-77340933-8938-47e1-baec-3dbc548d3fa2.png)

![image](https://user-images.githubusercontent.com/958404/146321416-4d7b5ba3-c824-42ba-ad16-fb4450ea5604.png)

### Describe the behavior you expected

I expect the correct "," to be used as a decimal separator for all decimal numbers.

### Steps to reproduce the issue

1. Use Finnish language
2. Select "automatic" as number formatting setting.
3. Add Home entity card with "wind bearing" selected.

### What version of Home Assistant Core has the issue?

core-2021.11.5

### In which browser are you experiencing the issue with?

Google Chrome Version 96.0.4664.110 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

**Comment by spacegaier** [comment]
Please provide the state from the HA dev tools. What value does the backend provide for the bearing? With comma or dot?

I ran a quick test with "Suomi" (which I assume is the language you use) and the formatting worked correct, but my system might do something different for "automatic". Can you please explicitly set the matching numbering format and let me know which one that is. Then I can try again.

**Comment by kyberias** [comment]
Sorry, I don't know how to do any of that.

**Comment by kyberias** [comment]
This is what the developer tools show:

![image](https://user-images.githubusercontent.com/958404/146655542-d4ce33b7-c73a-456f-8ff5-3882e236c8c7.png)

**Comment by kyberias** [comment]
As comparison, humidity is shown in Developer tools with the "." 

![image](https://user-images.githubusercontent.com/958404/146655640-192a68e4-2520-49df-84cb-d3a28e9d86d9.png)


Yet the UI shows it correctly with the comma "," everywhere (different entity but it's the same with all temperature and humidity entities):

![image](https://user-images.githubusercontent.com/958404/146655656-e316ac5c-0269-4339-bb7a-10e4316ff3ca.png)

**Comment by spacegaier** [comment]
I am not able to reproduce the issue, but all my instances are on newer HA versions (2021.12.8 and above) than you are, so perhaps this issue has already been resolved.

And just to confirm: The very first screenshot is an "Entity" card with weather attribute "Wind speed" selected as value, correct?

**Comment by kyberias** [comment]
This seems to have been fixed in the latest version I installed (2022.2.0).
