### ISSUE TITLE
New blank automation editor page won’t display in Firefox browser

### ISSUE THREAD

**Issue by Recte** [home-assistant/frontend#10946]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using Firefox on Win10 (last couple versions, currently 95 64bit).

When trying to create a new (blank) automation, by clicking 'Start with an empty automation'[1] it keeps returning to the list view of automations. Until v.11 there was a work-around by going to Blueprint and then skip, but with the new UI that option/trick is gone. It takes 5 to <who knows how many> attempts to get to a blank automation.

To see if I was the only one, I searched the community and noticed this topic: 
https://community.home-assistant.io/t/new-blank-automation-editor-page-wont-display-in-firefox-browser/366103/

 In Edge (Chromium based) things seem to work fine, but I never use Edge or any other browser, so it's just a one time test.

1. 
![image](https://user-images.githubusercontent.com/26491601/146355568-e791f258-b52a-48f8-8e30-8cb7779b7bf6.png)

### Describe the behavior you expected

Opening a blank automation

### Steps to reproduce the issue

1. In sidebar click Configuration
2. Click Automations & Scenes in Configuration menu
3. Click Add Automation
4. Click 'Start with an empty automation' in the pop-up

### What version of Home Assistant Core has the issue?

core-2021.12.2

### In which browser are you experiencing the issue with?

Firefox 95 64bit 

### Which operating system are you using to run this browser?

Windows 10

### Javascript errors shown in your browser console/inspector

```txt
none
```

**Comment by geeregman** [comment]
My OS is linux.
I have tried Midori browser with success.

**Comment by namadori** [comment]
I confirm the same erratic behavior on Firefox 95.0.1 on Mac Os 10.15.7

**Comment by atrooper** [comment]
I see the same behavior:
Firefox 95.0.1 (64-bit);  Workstation Ubuntu 20.04.3 LTS
Home Assistant OS 7.0; supervisor-2021.12.2; core-2021.12.3
The interface works correctly with Safari 14.1.2 Mac OS 10.14.6 and iPhone 11.

The Firefox browser console is presenting the following:
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features!

Error in parsing value for ‘padding-left’.  Declaration dropped. config:218:25
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. 2 config:1:362
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. dashboard:1:37
Ruleset ignored due to bad selector.
Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector.
Unknown pseudo-class or pseudo-element ‘-ms-reveal’.  Ruleset ignored due to bad selector. dashboard:62:7
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector.

**Comment by atrooper** [comment]
I have noticed that the new automation page paints partially and very briefly, before the automation list page reappears.
I had popups disabled previously in Firefox and now popups are enabled as an exception for the HA server address.
I just updated to core-2021.12.4.
No change in Firefox browser behavior, the new automation page is not displayed when requested.

**Comment by jprokopowich** [comment]
I experience the same issue.

**Comment by vlycop** [comment]
also same here since a couple day, really don't want to switch to chrome and this can be work around with yaml since the editor work on already existing automation

1. making a blank one manually in `automations.yaml`
2. reloading automation
3. editing said automation through the UI

I hop this is a bug from hass that Chrome silently deal with ... and not firefox doing bad work again, as they really don't have a good time right now and google is tempting.

**Comment by deosrc** [comment]
For those commenting "same here". Please hit the thumbs up on the first post as well. This is generally used to determine most frequently encountered issues and prevents everyone subscribed to this issue from being spammed by email.

Also for a UI workaround, you can duplicate an existing automation and delete all of the steps.

Unfortunately I'm not familiar with the UI framework and webpack seems to be preventing debugging.

**Comment by mdino-gh** [comment]
For me the following workaround works -> add the following path after your HA server URL /config/automation/edit/new. This opens the blank create automation editor directly.

**Comment by mjj4791** [comment]
same here: When I try to create an automation I briefly see the edit screen but it disappears immediately...
* Firefox 95.0.2 (64 bit) on Windows 10/64 bit
* Home Assistant 2021.12.5
* NOT having the issue on Chrome/portable: Version 96.0.4664.110 (Official Build) (32-bit)

HA Info

version | core-2021.12.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.83
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.0
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 115.7 GB
disk_used | 4.9 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Samba share (9.5.1), ESPHome (2021.12.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 2
mode | storage

</details>

**Comment by rednerd** [comment]
If you have two monitors hooked up, try moving the Firefox window to the primary screen, then add a new automation. This seems to fix it every time I encounter this.

**Comment by mjj4791** [comment]
I tried above potential workaround; but does not work for me
On neither monitor am I able to create a new blank automation with firefox....

## System Health

version | core-2021.12.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.83
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.0
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 115.7 GB
disk_used | 5.6 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Samba share (9.5.1), ESPHome (2021.12.1)

</details>

**Comment by atrooper** [comment]
> For me the following workaround works -> add the following path after your HA server URL /config/automation/edit/new. This opens the blank create automation editor directly.

Yes, this workaround does it with the Firefox Browser on Windows 10.  The problem does not appear in the MS Edge (Chromium).

**Comment by Recte** [comment]
For what it's worth, the issue occurs when using one monitor (Win10) and it doesn't matter if it's the build-in (of the laptop) or an external one.

**Comment by Joshndroid** [comment]
Been seeing this for a bit now...
The work around i had been using was duplicating an already set up automation until i got annoyed and started to search for a solution, leading me here....

**Comment by RosemaryOrchard** [comment]
A small and potentially useful (but sadly likely useless) data point: Firefox 95.0.2 on my Intel MacBook Pro does not have this issue, on the internal or primary external display.

**Comment by Eraser127** [comment]
@RosemaryOrchard Here the same software versions for FF and HA on Win10 and also faulty. No problems with Edge.

**Comment by balloob** [comment]
Fixed in https://github.com/home-assistant/frontend/pull/11152
