### ISSUE TITLE
Incorrect displaying gauge card

### ISSUE THREAD

**Issue by iStitch07** [home-assistant/frontend#10949]
## System Health

version | core-2021.12.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7

Hello. Last two front end version have issues with displaying gauge card. 
this issue affect mobile app version and web version on iPad 
On notebook gauge card displaying correct 

os_name | Linux
os_version | 4.4.180+
arch | x86_64
timezone | Europe/Moscow

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4945
Installed Version | 1.18.0
Stage | running
Available Repositories | 911
Installed Repositories | 9

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 5
views | 8
mode | yaml

</details>
![screen](https://user-images.githubusercontent.com/56363568/146420987-f724a9ea-1d49-4a0a-aa9f-01a0ee537dde.jpeg)

### What version of Home Assistant Core has the issue?

core-2021.12.2

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

lovelace

### Link to integration documentation on our website

https://www.home-assistant.io/lovelace/gauge/

**Comment by spacegaier** [comment]
If this is for Safari and/or iOS 15.2, then this has already been reported in https://github.com/home-assistant/frontend/issues/10766 and https://github.com/home-assistant/frontend/issues/10910.

**Comment by raducotescu** [comment]
See also #11041, which refers to the companion app that seems to be used by @iStitch07.
