### ISSUE TITLE
Can't create a new automation in firefox

### ISSUE THREAD

**Issue by Ulrar** [home-assistant/frontend#10945]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I go to the new automation menu in Firefox and try to create a new automation, regardless of choosing empty or from a template, the automation form blinks in and goes away immediately, bringing me back to the list of existing automation.
I can edit automation fine, I just can't create a new one.

Works fine on the mobile app and on edge, seems to be only an issue in FF.

### Describe the behavior you expected

Be able to access the form to create an automation

### Steps to reproduce the issue

1. Use Firefox 95
2. Try to create a new automation
3.
...

### What version of Home Assistant Core has the issue?

core-2021.12.2

### What was the last working version of Home Assistant Core?

Not sure, I don't create automations that often

### In which browser are you experiencing the issue with?

Firefox 95 64bit

### Which operating system are you using to run this browser?

Windows 11

### Javascript errors shown in your browser console/inspector

```txt
No output in the console when this happens
```

**Comment by floli** [comment]
Related forum thread with a couple of reports of this bug: https://community.home-assistant.io/t/cant-create-new-automation-in-web/367773

**Comment by dimitripb** [comment]
I have the same problem with Firefox 95 in Linux Mint and Windows 8.1. I suspect the Firefox upgrade to version 95. That's when i started. My older HA instance never had this problem but just after upgrading Firefox it started to show this behavior also.

**Comment by balloob** [comment]
Fixed in https://github.com/home-assistant/frontend/pull/11152
