### ISSUE TITLE
Issue with energy consumption after updating to 2021.12.1/2

### ISSUE THREAD

**Issue by henrikrox** [home-assistant/frontend#10954]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After updating to 2021.12.1, the energy tab shows like this

![2021-12-17 08_23_57-](https://user-images.githubusercontent.com/6884716/146505764-2a9163ba-5097-434c-9074-fdb8675d740c.png)

It seems something happens at midnight, and it messes up the energy consumption for the day/week/month. I havnt changed anything the last month.

How it used to be
![2021-12-17 08_24_51-Energi - Home Assistant](https://user-images.githubusercontent.com/6884716/146505852-eeb97ff8-75f0-425e-ae0b-29ebf5974e86.png)
 

### Describe the behavior you expected

Not show the consumption as negative at midnight. 

### Steps to reproduce the issue

1. Use energy tab
2. Update to 2021.12.1
3. Wait to midnight
...

### What version of Home Assistant Core has the issue?

core-2021.12.2

### What was the last working version of Home Assistant Core?

core-2021.11.X

### In which browser are you experiencing the issue with?

Chrome 96.0.4664.93

### Which operating system are you using to run this browser?

Windows, also tried OSX and iPhone

### State of relevant entities

```txt
All relevant kwh devices are correct, so it seems the issue with the UI.
```

### Additional information

![2021-12-17 08_27_07-](https://user-images.githubusercontent.com/6884716/146506183-c8451931-b2bc-4fdf-b4f6-2bce1ce86dc3.png)

Energy dashboard configuration.

**Comment by warfair1337** [comment]
Same issue here after upgrade from 2021.11.x to 2021.12.3. But for me this happened just before midnight.

<img width="1659" alt="Screenshot 2021-12-18 at 13 05 04" src="https://user-images.githubusercontent.com/29115004/146640373-7cd46d49-cf32-49bf-924d-e8101d785d87.png">

**Comment by henrikrox** [comment]
@warfair1337 ok glad im not alone, hopefully someone will look into this

**Comment by toffyrn** [comment]
Might be a duplicate of #61551?

**Comment by henrikrox** [comment]
@toffyrn good find, it is indeed, I thought it was a frontend issue, but I see its because of the timber sensor, closing this issue. thank you again
