### ISSUE TITLE
Back buttons are inconsistent in the media browser compared with the rest of the UI

### ISSUE THREAD

**Issue by SheaSmith** [home-assistant/frontend#10950]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Most of the Home Assistant UI returns to the previous page when the back button is pressed (including dialogs in many cases), however when navigating through the media browser, the back button returns to the previous non-media browser page.

### Describe the behavior you expected

The expected behavior would be that the back button returns up a level in the media browser (if you've navigated to a child item), rather than to the previous non-media browser page.

### Steps to reproduce the issue

1. Go to any page.
2. Go to the media browser and navigate to a directory.
3. Click the back button. You will now be back at the original page.

### What version of Home Assistant Core has the issue?

core-2021.12.2

### In which browser are you experiencing the issue with?

Firefox 95 and the HA Android App 2021.10.0-full

### Which operating system are you using to run this browser?

Windows 10 and Android 12

**Comment by matthiasdebaat** [comment]
Media Browser is indeed a different pattern. I'll take a look at it.

**Comment by matthiasdebaat** [comment]
<img width="1789" alt="Schermafbeelding 2022-01-06 om 15 31 11" src="https://user-images.githubusercontent.com/20203284/148398629-8cc795f5-9398-47bd-91d6-41c0d6bf8ef6.png">

Made a quick [Figma concept](https://www.figma.com/file/TWr4HYnSdCjnxlmcOxmH7g/Media-Browser?node-id=1%3A1254). What do you think?

**Comment by SheaSmith** [comment]
Looks great!
