### ISSUE TITLE
Climate is not displayed as unavailable

### ISSUE THREAD

**Issue by chemelli74** [home-assistant/frontend#10951]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Climate entities marked as unavailable, don't show their state on entities card.

### Describe the behavior you expected

Unavailable status displayed as for all other entities

### Steps to reproduce the issue

1. Install a device that create a climate entity
2. Disconnect the device from the network
3. Check representation on entities card

### What version of Home Assistant Core has the issue?

2022.1.0.dev20211213

### In which browser are you experiencing the issue with?

Microsoft Edge Version 96.0.1054.53 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 - 21H1 (build 10.0.19044.1415)

### Additional information

![image](https://user-images.githubusercontent.com/57354320/146463534-1c69537c-0cac-43f8-91f4-73d1b2d98d21.png)

**Comment by spacegaier** [comment]
Initial discussion in #dev_frontend https://discord.com/channels/330944238910963714/351047592588869643/938901045659193404

@chemelli74 Could you post the entity state from the HA dev tools in the unavailable state. Would be interesting to see what happens to the `hvac_action` and `hvac_mode` in that scenario.

**Comment by chemelli74** [comment]
![image](https://user-images.githubusercontent.com/57354320/152578991-6e579600-5a1c-418f-bc49-1c4d8e4a1bd7.png)

P.S.> There is also a display issue with the time in the upper right part of the screenshot.

**Comment by chemelli74** [comment]
Here the same device when is available:

![image](https://user-images.githubusercontent.com/57354320/155711206-ee054197-d0e2-445f-9b56-058bd2313488.png)

**Comment by chemelli74** [comment]
@spacegaier did you get time to take a look ?

Thx,

Simone
