### ISSUE TITLE
Developer Tools / States Tab – Poor performance, slow load times

### ISSUE THREAD

**Issue by marcelodavanzo** [home-assistant/frontend#10965]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Short version: States page is unresponsive for several seconds across various devices and browsers.

---

Detailed version:

Upon opening the Developer Tools on the left sidebar I am taken to the first tab on the Dev Tools area, which is States.

This page loads and lists out **all** available entities and their states at once, resulting in slow load times. Ranging from a few seconds on desktops/laptops to several seconds (30 in my case) on modern mobile devices.

While it's useful to be able to access all existing entities in one place I also think this experience could be improved. A couple of suggestions:

1. Switch the default of Developer Tools to a more performant tab, like Services or Template. This means only users with direct intention of using States would get there (and hopefully be okay with the long wait) – not ideal but improves the experience a bit for those who want to access Template, Services, Events without having to wait.

2. Presuming most users accessing State are after a specific entity, they will most likely rely on searching, not scrolling the list. This means this page could be optimised for this use case by being paginated instead of loading all entities in one place it would show something like 25-50 at a time. Perhaps with a dropdown to pick how many entities are displayed per page. Search would then override pagination and bring up the query results. And hopefully paginating this page would improve performance considerably.

I thought of filing this as a feature or enhancement but thinking better about it I consider the performance of this page a bug as I don't think this was intentionally meant to be slow and there has been work in the past aimed at speeding it up.

### Describe the behavior you expected

A speedier response time upon reaching the page, faster time to interaction.

### Steps to reproduce the issue

1. Simply click on Developer Tools on the left hand side menu
2. Wait
3. See entities listed out
...

### What version of Home Assistant Core has the issue?

2021.12.3

### In which browser are you experiencing the issue with?

All browsers

### Which operating system are you using to run this browser?

Various OSs

**Comment by gerard33** [comment]
You can uncheck the Attribute checkbox. Now the page is a lot faster and if you need the attribute details you can check the checkbox again. Just don't forget to uncheck it again after you leave the page as the last setting will be stored in the browser.
See [here](https://github.com/home-assistant/frontend/discussions/7537) for more details.
Maybe not exactly what you are looking for but it will at least improve the loading time of that page.

**Comment by noxhirsch** [comment]
Still an issue 🤷‍♂️
