### ISSUE TITLE
Incorrect cursor (pointer) on entity rows

### ISSUE THREAD

**Issue by benct** [home-assistant/frontend#10961]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The [code](https://github.com/home-assistant/frontend/blob/07cd68f5d067c0a9cf18c725832e124822e6e433/src/panels/lovelace/components/hui-generic-entity-row.ts#L53-L55) for determining the pointer cursor on entity rows is incorrect. It shows a pointer by default and when tap_action's `action` is `none`, but not when `action` is anything else.

### Describe the behavior you expected

Should show a pointer cursor by default and when `action` is NOT `none`.

### Steps to reproduce the issue

1. Set `tap_action` + `action: none` or `action: more_info` on an entity row.
2. Hover over the entity row.

### What version of Home Assistant Core has the issue?

core-2021.12.x

### What was the last working version of Home Assistant Core?

core-2021.11.x

### Additional information

Related to the same commit; The [change](https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/components/hui-generic-entity-row.ts#L147-L159) you made to generic-entity-row, adding a wrapper/action-handler on _some_ entity domains, is quite disruptive for those of us that use the generic-entity-row in our custom cards. The action handler is intercepting all clicks/touches on whatever we insert into the row, which is difficult to work around. Would appreciate if you could consider revising that change, or add an option to disable it.

**Comment by spacegaier** [comment]
Good catch. Not sure why I did not notice that when I created the original PR 🤦.

**Comment by spacegaier** [comment]
@benct I created PR #10971 which could solve the custom card dev issue you raised. With it you could override the default behavior (and we anyway need something like this in vanilla HA as well, hence the PR in the first place).

**Comment by benct** [comment]
Awesome! Thank you 🙂
