### ISSUE TITLE
Supervisor menu item is missing after the update

### ISSUE THREAD

**Issue by Haarolean** [home-assistant/frontend#10962]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Supervisor menu item is missing after the update

### Describe the behavior you expected

Menu item is present. Instead of that I have to click configuration and find the supervisor in the long list

### Steps to reproduce the issue

1. Update core from 2021.5.3 to 2021.12.3
2. ???
3. profit

### What version of Home Assistant Core has the issue?

2021.12.3

### What was the last working version of Home Assistant Core?

2021.5.3

### In which browser are you experiencing the issue with?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

### Which operating system are you using to run this browser?

Intel Mac OS X 10_14_6

**Comment by spacegaier** [comment]
If you mean missing from the sidebar, then this is not a bug but a conscious design change.

**Comment by Haarolean** [comment]
Would be nice to provide the user an ability to keep it there.

**Comment by spacegaier** [comment]
The option does exist, see the discussion in the [release thread](https://community.home-assistant.io/t/2021-12-new-configuration-menu-the-button-entity-and-gorgeous-area-cards/365680/50?u=spacegaier).
