### ISSUE TITLE
more-info focus issue with automation entities on iOS

### ISSUE THREAD

**Issue by bachya** [home-assistant/frontend#10969]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I'm noticing that in the latest HASS (2021.12.3) and iOS app (2021.12), `automation` entities (which present as toggle entities in the UI) show the same behavior as described in https://github.com/home-assistant/frontend/pull/10025: tapping the switch toggle opens the more-info dialog.

I spoke with the iOS dev channel and I was instructed to post here.

### Describe the behavior you expected

I expected `automation` entities to behave like other toggle entities (`switch`/`light`/etc.): tapping the toggle itself should alter the state of the entity.

### Steps to reproduce the issue

1. Create any automation
2. Show that automation in Lovelace
3. Open HA in iOS
4. Attempt to toggle the automation

### What version of Home Assistant Core has the issue?

core-2021.12.3

### What was the last working version of Home Assistant Core?

core-2021.11.x

### In which browser are you experiencing the issue with?

Mobile Safari

### Which operating system are you using to run this browser?

iOS 15.1

**Comment by spacegaier** [comment]
Will be fixed by PR #10940
