### ISSUE TITLE
Poss typo in Configuration/Server Controls Page?

### ISSUE THREAD

**Issue by jamespreedy** [home-assistant/frontend#10966]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the Configuration / Server Controls page, I think there's a grammatical typo in the list of things that can be reloaded.
Currently, everything is a plural ...

LOCATION & CUSTOMIZATIONS
AUTOMATIONS
GROUPS, GROUP ENTITIES, AND NOTIFY SERVICES
INPUT BOOLEANS
INPUT DATE TIMES
INPUT NUMBERS
INPUT SELECTS
INPUT TEXTS
PEOPLE
SCENES
SCRIPTS
TEMPLATE ENTITIES
ZONES

... except TIMER which is singular, even though many folks have multiple timers.
It's only a little thing, but thought I'd mention it in case someone missed it.

Thanks! 🎄

### Describe the behavior you expected

I believe TIMER should read TIMERS

### Steps to reproduce the issue

Go to your Home Assistant instance /config/server_control
Scroll down to the reload section, look at list? haha

### What version of Home Assistant Core has the issue?

core-2021.12.3

### In which browser are you experiencing the issue with?

Safari 15.2

### Which operating system are you using to run this browser?

Monterey

**Comment by spacegaier** [comment]
Even little things need to be fixed 😄. Thank for reporting. PR to fix created.
