### ISSUE TITLE
Button Card cannot operate with Button Entity

### ISSUE THREAD

**Issue by iu1jvo** [home-assistant/frontend#10975]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

A button card in lovelace, configured with a button entity and tap action "toggle".
when the button card is tapped ui return the message:"failed to call service button/turn_off".

### Describe the behavior you expected

The button card connected to a button entity with tap action "toggle" shall call service "button/press".

### Steps to reproduce the issue

1. configure a button entity
2. configure a button card connected to the button entity above and default action "toggle"
3. tap the button card.

### What version of Home Assistant Core has the issue?

core-2021.12.2 to core-2021.12.9

### What was the last working version of Home Assistant Core?

 core-2021.12.9

### Additional information

Workaround: instead using "Toggle" as default action, use "Call Service" configured to call service "button:press" to the entity.

**Comment by iu1jvo** [comment]
> Can confirm. I'm not skilled enough to see what the difference between 2021.12.1 and 2021.12.2. My work around is to use call service "button:press" but then you have to type in the name of your button twice.
> 
> #10504
> 
> @bramkragten

Yes, my work around too. I'm watingo for the next version with PR  #11346.

**Comment by chunkysteveo** [comment]
Can advise update to Home Assistant 2022.2.0 fixed this for me, good timing!
