### ISSUE TITLE
DateTime picker first day of week should follow locale

### ISSUE THREAD

**Issue by koying** [home-assistant/frontend#10970]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The datetime picker has Sunday as the first day of week

### Describe the behavior you expected

The datetime picker should follow my locale or, if not possible, fallback to ISO 8601 value of Monday

### Steps to reproduce the issue

1. Set my language to French
2. Go to logbook and open datetime picker
3. See that first day of week is Sunday
...

### What version of Home Assistant Core has the issue?

2021.12.3

**Comment by seanomat** [comment]
The issue still exists

**Comment by mundschenk-at** [comment]
Still exists in 2022.4.4

**Comment by TTLucian** [comment]
Same issue in 2022.5.5

**Comment by seanomat** [comment]
This issue has now extended to input_datetime as well

**Comment by slovdahl** [comment]
Still an issue.

**Comment by larena1** [comment]
@bramkragten @piitaya @emontnemery 
Unfortunately this is still an issue. Do you think this can be fixed?

**Comment by spacegaier** [comment]
There is not yet a reliable generic way to get the correct value, see https://github.com/home-assistant/frontend/issues/12635#issuecomment-1121469639

**Comment by chocomega** [comment]
I guess the best would be a setting in user's profile for the first day of the week regardless of the locale just like number format and time format settings. Then later add the option "auto" when the generic way to get the value from the locale is implemented.

**Comment by chocomega** [comment]
Similar issue #13789

**Comment by piitaya** [comment]
It will be fixed in the next beta 🙂
