### ISSUE TITLE
themes need extra refresh to fully load

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#10988]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

when changing themes, not all of the interface is correctly changing, and an extra reload of the page is needed, to have the cards follow the theme:

halfway there:
<img width="653" alt="Schermafbeelding 2021-12-21 om 11 06 54" src="https://user-images.githubusercontent.com/33354141/146911912-525f7794-a54a-4a86-b8ea-e9a440a612b7.png">

all correct:
<img width="595" alt="Schermafbeelding 2021-12-21 om 11 07 05" src="https://user-images.githubusercontent.com/33354141/146911945-fc3be144-037c-4de0-bd6c-157ca19320dd.png">

### Describe the behavior you expected

change correctly in 1 go

### Steps to reproduce the issue

1. change theme
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.2.0.dev20211221

### What was the last working version of Home Assistant Core?

not sure

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

MacOS 12.0.1

**Comment by ludeeus** [comment]
Fixed in <https://github.com/home-assistant/frontend/pull/10979>

**Comment by Mariusthvdb** [comment]
not sure this is fixed I that case, I am running 2022.2.0.dev20211221 and I can see eg #10941 in that same merge being effective.
Themes still not loading at once.

**Comment by ludeeus** [comment]
K...
Remove all custom cards and card mod and any custom modification you do on your instance and make sure that it's still an issue with a setup without _any_ custom modifications/cards.

**Comment by Mariusthvdb** [comment]
btw, can this be related, (I didnt see it before)

```
2021-12-21 12:06:32 ERROR (MainThread) [frontend.js.latest.202112200] https://mydomain/frontend_latest/core.47513876.js:1:6969 TypeError: n.callback is not a function. (In 'n.callback(s.event)', 'n.callback' is undefined)
```

**Comment by Mariusthvdb** [comment]
think I found a culprit:
If I take out:

```
# https://github.com/RomRider/apexcharts-card
- url: /local/lovelace/resources/apexcharts-card/apexcharts-card.js?v=1.10.0
  type: module
```

the themes change immediately.

**Comment by Mariusthvdb** [comment]
Anything else I could check to debug this? 

Can add it also happens on automated theme changes.

**Comment by muppie** [comment]
I have the same issue, but with the default theme. It requires a refresh for it to load. Both on the iOS app, the browser and on both internal and external addresses.

**Comment by crashmatt** [comment]
Another data point. I see the same problem with an entities card on chrome browser on an android tablet.
Lots of modifications already including card-mod, custom:slider-entity-row, custom:auto-entities, fully-kiosk, code-red and more.

Appears to happen when triggered from node-red by sun.  
Does not appear to happen when triggered through the gui which triggers node-red to do the same thing

The system is quite busy around sun state changes.  Tried adding a 10s delay after sun state change. Didn't see an improvement but could do with more testing.

```
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - type: entities
        entities:
          - type: custom:slider-entity-row
            entity: light.something_something_dark_side
            hide_state: true
            full_row: true
        title: Kitchen spotlights
        state_color: false
        show_header_toggle: true
```

**Comment by Mariusthvdb** [comment]
well, tbh, it happens on each of the above scenarios, manual theme selecting, backend, automation.

a refresh always helps. seems the entities cards need an extra nudge.

**Comment by crashmatt** [comment]
Agreed.  Just checked again and it happens whatever the trigger source is.

**Comment by Mariusthvdb** [comment]
do you have card-mod-theme at work?

**Comment by crashmatt** [comment]
I have card-mod on items in the view but not on this card.

**Comment by Mariusthvdb** [comment]
well, it was a bit of a guess, and I did check that before, after https://github.com/home-assistant/frontend/issues/10988#issuecomment-998686183

It's just that I noticed the themes change correctly when I disabled that single line

```
Dark blue:

  <<: &generic
    #card-mod-theme: custom-header
    rest of the generic theme settings
```

which as yo can see is valid for all my themes.... except for default obviously.
and exactly that is the odd thing, it also happens on default.

**Comment by crashmatt** [comment]
Just put the offending card in a new dashboard all on its own.  It behaves properly.
Now the original dashboard behaves properly also.
Deleted the extra dashboard.  The original dashboard is still ok.

Starting to not believe anything I am doing.

Is this something to do with having a theme set at the change of date? Like it gets stuck because a timestamp is wrong?
Need to test before and after midnight.  Maybe before and after 00:00 GMT.

**Comment by Mariusthvdb** [comment]
no, its nothing with the dates/timestamp. why would you think that, if the manual changing also triggers the issue...

**Comment by crashmatt** [comment]
It works perfectly now after a browser refresh.  In the morning that card is stuck on the night theme.  Does that mean that a date change does it?  Is there anything else that changes over that time?
Have not properly tested this after sunset but before midnight.
Could be tricking myself again.  Need more evidence.  This might take a few days.

Please try putting the card-mod back in to see if it works or not.

**Comment by crashmatt** [comment]
It has been a few days now and I have not seen this problem again.  Ever since I made the new view with entities card and no card-mod.  Even after deleting the new view.

**Comment by Mariusthvdb** [comment]
as documented in https://github.com/home-assistant/frontend/issues/10988#issuecomment-1052134096, the theme changing issue closely depends on the card-mod theme setting. And has nothing to do with any other HA lovelace setting you would test, so yes, what you write here is correct (but expected really).

Ill close this issue, since it isnt HA core Lovelace.
