### ISSUE TITLE
Viewing a sensor value in the history chart displays incorrectly formatted time (24:19:55 instead of 00:19:55)

### ISSUE THREAD

**Issue by Linqman** [home-assistant/frontend#10998]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When clicking on a entity in lovelace, that opens the history diagram, and then hovering the mouse along the chart, if you hover over a time between 00:00:00 and 00:23:59, the time is displayed as 24:MM:SS instead of 00:MM:SS. This only happens in a browser, not for example in the IOS app.

![image](https://user-images.githubusercontent.com/94689155/147044951-a1041f87-f98b-4587-a91f-a303d5104fa2.png)

### Describe the behavior you expected

I expect it to display 00:MM:SS as the formatted time.

### Steps to reproduce the issue

1. Open a Lovelace view in HA
2. Click on an entity with values logged in the time frame 00:00 to 01:00
3. Hover the mouse over the history chart in between the time frame 00:00 to 01:00
4. The displayed time is 24:MM:SS instead of 00:MM:SS

### What version of Home Assistant Core has the issue?

core-2021.12.4

### In which browser are you experiencing the issue with?

Google Chrome 95.0.4638.54, Microsoft Edge 91.0.864.67

### Which operating system are you using to run this browser?

Windows 10.0.19042

**Comment by ildar170975** [comment]
Still present

**Comment by ildar170975** [comment]
HA 2022.6.5 - seems to be fixed:
![image](https://user-images.githubusercontent.com/71872483/175182959-e4ca87dc-79c2-47e6-a617-adfdee5f2245.png)
