### ISSUE TITLE
core-2021.12.4 doesn't work with Firefox 95.0.2

### ISSUE THREAD

**Issue by colotroy1** [home-assistant/frontend#10997]
### The problem

The last build, I believe it was core-2021.12.3 worked fine with FF 95.0.2 but after the last update to core-2021.12.4 Firefox sits at the initial Loading Data screen with the blue HA icon.  My mobile devices work fine, and Chrome (Version 96.0.4664.110) also works, but I hate using Chrome.  Firefox has always worked fine for me up to this latest build.  Running on Windows 10 pro 19042.1415.

### What version of Home Assistant Core has the issue?

core-2021.12.4

### What was the last working version of Home Assistant Core?

core-2021.12.3

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
I'm not seeing anything in the logs that are interesting.
```

### Additional information

The last build, I believe it was core-2021.12.3 worked fine with FF 95.0.2 but after the last update to core-2021.12.4 Firefox sits at the initial Loading Data screen with the blue HA icon.  My mobile devices work fine, and Chrome (Version 96.0.4664.110) also works, but I hate using Chrome.  Firefox has always worked fine for me up to this latest build.  Running on Windows 10 pro 19042.1415.

**Comment by balloob** [comment]
I am unable to reproduce here. It works fine on Firefox 95.

Make sure you disable all custom cards and resources and try again.

> I'm not seeing anything in the logs that are interesting.

There should be nothing in the logs.

**Comment by Jaharmi** [comment]
I’m also seeing a similar problem — sitting at the “loading” screen — with 2021.12.4 in the HA app on iPhone and iPad. This happens when I launch the HA iOS app, and again after I quit and relaunch it. Not trying to hijack this issue, but wanted to add data. (In my case, I’m also seeing problems in Mobile Safari, but that’s after I log in and load my default dashboard, which is generated by HA.)

**Comment by colotroy1** [comment]
Very strange...   I tried multiple servers and had the same issue with FF.  This morning the Firefox browser window that was spinning on the loading screen for hours was at the dashboard and works, and now I can't reproduce.  I can't explain what magic made that work over night but it's working now.

Interesting that now with FF I can't create a new automation without a blueprint on this server, it's kinda like a popup being blocked, it just goes back to the automations screen.  It does work on Chrome and with FF on my other server now.   I'll clear cache and reboot and see if I see same.

**Comment by colotroy1** [comment]
After cache clear and reboot I'm still seeing the same with FireFox and automations.   If I use a blueprint it will open the new automation, if I select "Start with empty automation" I see the new automation for a fraction of a second, then I'm back to the main automation screen listing all my automations.  I'm seeing the same thing on multiple Win10pro OSs.

This works on fine on Chrome.  Not sure what's up with FF...

**Comment by scmmmh** [comment]
I'm seeing this as well. I can edit an existing automation and duplicate and edit an existing automation, but creating a new automation directly flashes the editor before going back to the automation listing.

**Comment by mjj4791** [comment]
Loading HA in firefox works fine for me; but I do see the issue mentioned above with creating a new blank automation....
This seems to be mentioned in another issue already: https://github.com/home-assistant/frontend/issues/10997

**Comment by thinkmassive** [comment]
> Loading HA in firefox works fine for me; but I do see the issue mentioned above with creating a new blank automation.... This seems to be mentioned in another issue already: #10997

This is issue 10997. Is there this bug also described somewhere else?

**Comment by mjj4791** [comment]
Yes it is; got the issue numbers mixed up apparently…..
It is in issue #10946; but i see you found it already….
