### ISSUE TITLE
fix needle in gauge card

### ISSUE THREAD

**Issue by magnetus26** [home-assistant/frontend#10995]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

needle in gauge cards are not centered

### Describe the behavior you expected

needle should comes from the center of the gauge and move accordingly

### Steps to reproduce the issue

1. create a gauge card
2.enable needle
![72085E9C-D178-4746-8A8F-7C209DC7EFF0](https://user-images.githubusercontent.com/22038983/146997569-d8b1f41f-c58e-4b79-b18d-79d070223f79.jpeg)

3.
...

### What version of Home Assistant Core has the issue?

core-2021.12.3

### What was the last working version of Home Assistant Core?

core-2021.11

### Which operating system are you using to run this browser?

IOS 15.2

**Comment by spacegaier** [comment]
The 6th or 7th duplicate by now 😆 

https://github.com/home-assistant/frontend/issues/10910
