### ISSUE TITLE
Click reload page will ask to login in again

### ISSUE THREAD

**Issue by BH1SCW** [home-assistant/frontend#11000]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After I login to home assistant, I click reload current page and it will ask me to input user and password again

### Describe the behavior you expected

It should remember current login user until I logout.

### Steps to reproduce the issue

1. Open home assistant page
2. Input user name and password
3. Reload current page
...

### What version of Home Assistant Core has the issue?

Newest version
2021.12.4

### What was the last working version of Home Assistant Core?

unkonwn

### In which browser are you experiencing the issue with?

safari

### Which operating system are you using to run this browser?

macOS mojave

### Additional information

It works on Google Chrome.

**Comment by spacegaier** [comment]
Please fill out the issue template, especially the HA version. There were some changes made recently, so potentially you are using an old version.

**Comment by BH1SCW** [comment]
> Please fill out the issue template, especially the HA version. There were some changes made recently, so potentially you are using an old version.

OK， I am using Newest version : 2021.12.4 from docker-compose.
Thanks

**Comment by feens** [comment]
I have this issue as well.  Using: `Frontend version: 20211229.0 - latest`.  It's one of the most annoying things tbh.  Doesn't matter which page I'm on, if I refresh, I'm kicked to the login.  Using Safari as my browser.
