### ISSUE TITLE
Enabling disable device, will not trigger reload of integration

### ISSUE THREAD

**Issue by elupus** [home-assistant/frontend#11009]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If you enable a disabled device. The device is enabled and potentially it's child entities. However, no prompt is shown that entities will be available in 30 seconds.

### Describe the behavior you expected

Prompt is displayed that entities will be available in 30 seconds, like when enabling an entity.

### Steps to reproduce the issue

1. Disable a Device
2. Enable same Device
3. Wait for entities to become available.
...

### What version of Home Assistant Core has the issue?

2021.12.4

**Comment by tdejneka** [comment]
> Prompt is displayed that entities will be available in 30 seconds, **like when enabling an entity.**

A deeper problem is that the message is misleading; disabled entities, like Helpers, aren't re-enabled after 30 seconds. It typically requires a restart to truly re-enable it.

FWIW, the inability to fully re-enable (without a restart) was reported over a year ago (for Helpers and also for other entities) but was never corrected (bounced from Frontend to Core with no traction in either repo). I just confirmed with 2021.12.7 that the problem still exists (disable/re-enable an input_boolean and, after waiting one or more minutes, it fails to be re-enabled). The outcome seems to vary based on the entity's integration.
