### ISSUE TITLE
Home Energy Management graph shows forcast PV incorrect

### ISSUE THREAD

**Issue by mvroosmalen1970** [home-assistant/frontend#11004]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the energy production graph I have two PV systems which both have a predicted production. The first shows correctly (lower graph in picture with max is 0.72), the second above is not matching with the scale (left) as the max value is 0.23, but depicted close to 1.0.

![image](https://user-images.githubusercontent.com/36565907/147115523-96a834c9-0c64-4a73-8380-60d4dfeb3239.png)

would be nice if it can be solved :-). Not very important though.

Mark

### Describe the behavior you expected

Both dotted line graphical predictions matching with the left scal.

### Steps to reproduce the issue

1.Add two PV systems in energy
2.check energy production of both systems
3.
...

### What version of Home Assistant Core has the issue?

2021.11.5

### In which browser are you experiencing the issue with?

Google Chrome Chrome is up to date Version 96.0.4664.110 (Official Build) (64-bit), Microsoft Edge Version 96.0.1054.62 (Official build) (64-bit)

### Which operating system are you using to run this browser?

windows10

**Comment by thomasdelaet** [comment]
@mvroosmalen1970 don't know if this is related but shouldn't the forecasts be summed up since the bar charts are also summed up?

**Comment by thomasdelaet** [comment]
still relevant :-)

**Comment by thomasdelaet** [comment]
still relevant :-)

**Comment by karwosts** [comment]
I think it makes sense to me that they are summed, but even if not, this is the same issue as reported in another ticket #15011.

I'll close this as a duplicate, as even though this is older, I think the other report has a little clearer description and images.
