### ISSUE TITLE
HLS stream bufferStalledError

### ISSUE THREAD

**Issue by allenporter** [home-assistant/frontend#11018]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I've noticed hls streams getting stuck with these problems:
`bufferStalledError`
`bufferAppendError`

These are apparently flagged as non-fatal errors, and may need the media restarted.

Hitting reload fixes the problem.

### Describe the behavior you expected

I'm expecting some sort of automatic recovery or retry.

### Steps to reproduce the issue

1. Using picture glance card
2. With `live` mode
3. Happens intermittently, likely caused by latency in my cloud based camera.
4. I'm using LL HLS
...

### What version of Home Assistant Core has the issue?

core-2021.12.5

### In which browser are you experiencing the issue with?

Chrome 88.0

### Which operating system are you using to run this browser?

MacOS Big Sur 11.1

### Javascript errors shown in your browser console/inspector

```txt
I did notice I saw some 404s bin the `playlist.m3u8` before this, but not sure how much they contribute to this.
```

### Additional information

<img width="303" alt="HLS errors" src="https://user-images.githubusercontent.com/6026418/147294160-5d131f23-cf5e-48da-8865-00dc00614814.png">

**Comment by allenporter** [comment]
@uvjustin for visibility since frontend related stream issues don't go to us automatically.

I see some discussion of how to handle this here:
https://github.com/video-dev/hls.js/issues/1255
https://github.com/clappr/clappr/issues/813

**Comment by allenporter** [comment]
https://github.com/video-dev/hls.js/blob/master/docs/API.md#fatal-error-recovery also discusses how we might try to recover from fatal errors.

**Comment by uvjustin** [comment]
Does it happen more with `live` mode than with `auto` mode?
As you noted, cloud cameras may pose a problem since the inputs themselves can be burst-y. The way we use hls.js allows the player to speed up to catch up to "live", so if the input bursts ahead, the player can follow it ahead too. When the input then lags again, the player may be ahead of the buffer and end up stalling while waiting for the input and stream worker to catch up.

**Comment by allenporter** [comment]
I haven't noticed this with auto.  Another factor is i had 3 camera streams in `live` at once, which could definitely put pressure on the network.

**Comment by allenporter** [comment]
I think there may still be some error handling improvements to make here, but need to test again.

**Comment by allenporter** [comment]
Going to close for now after the last found of improvements in Feb in https://github.com/home-assistant/frontend/pull/11672 -- we can re-open with new ideas.
