### ISSUE TITLE
Uncaught RangeError log message

### ISSUE THREAD

**Issue by stefanroelofs** [home-assistant/frontend#11019]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Every time I open my default (automatically generated) dashboard I get the following 2 errors in the log:
```log
2021-12-24 11:13:52 ERROR (MainThread) [frontend.js.latest.202112200] http://ha.local:8123/frontend_latest/3ac4c648.js:1:351 Uncaught RangeError: Value need to be finite number for Intl.RelativeTimeFormat.prototype.format()
2021-12-24 11:13:52 ERROR (MainThread) [frontend.js.latest.202112200] http://ha.local:8123/frontend_latest/3ac4c648.js:1:351 Uncaught RangeError: Value need to be finite number for Intl.RelativeTimeFormat.prototype.format()
```

Is there a way to pinpoint which element is causing these log messages?
Everything seems to work fine. 

### Describe the behavior you expected

No error messages

### Steps to reproduce the issue

Refresh the default dashboard.

### What version of Home Assistant Core has the issue?

2021.12.5

### In which browser are you experiencing the issue with?

Vivaldi 5.0.2497.32 and Chrome 96.0.4664.110 and Edge 96.0.1054.62

### Which operating system are you using to run this browser?

Windows 10

### Javascript errors shown in your browser console/inspector

```txt
3ac4c648.js:formatted:19 Uncaught RangeError: Value need to be finite number for Intl.RelativeTimeFormat.prototype.format()
    at RelativeTimeFormat.format (<anonymous>)
    at a (3ac4c648.js:formatted:19)
    at HTMLElement.value (3ac4c648.js:formatted:2242)
    at HTMLElement.value (3ac4c648.js:formatted:2227)
    at HTMLElement.value (3ac4c648.js:formatted:2188)
    at N.A (styles.ts:366)
    at N.S (styles.ts:366)
    at N.T (styles.ts:366)
    at N._$AI (styles.ts:366)
    at S (styles.ts:366)
```
```


### Additional information

_No response_

**Comment by ApriliaEdd** [comment]
I was getting the same error and I think I tracked it down to my Fully kiosk browser tablets.  they have a sensor for "Last App Start". 

![Screenshot 2022-01-04 112152](https://user-images.githubusercontent.com/30949027/148052557-9b8c9364-86e1-4a34-804b-6220a28cacda.png)

This was showing as "Invalid timestamp" when I disabled these entities on each of my tablets the errors went away.  
Hope this helps

**Comment by stefanroelofs** [comment]
Yeah, I also have a sensor with 'invalid timestamp'. I will look into that, thanks!

**Comment by stefanroelofs** [comment]
The problem was indeed a sensor with an invalid timestamp. Thanks for pointing me in the right direction.

I think I'll close this issue, as my problem is solved. 
But maybe the thrown RangeError could be handled nicer?

Thanks!

**Comment by spacegaier** [comment]
@stefanroelofs Can you please provide the value that your sensor had (you can see that in the HA dev tools) that lead to the exception?

**Comment by stefanroelofs** [comment]
Sure, the value of the sensor was: `25-01-2021'.
The device_class of the sensor is: timestamp.
So I think the value of the sensor is indeed not a valid ISO 8601 timestamp.

(see some screenshots here: https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/issues/279)
