### ISSUE TITLE
No notification for updates

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#11012]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Frontend no longer displays a notification, or sends a persistent notification about updates.

### Describe the behavior you expected

please add a notification for any updates available I the configuration menu:

<img width="1060" alt="Schermafbeelding 2021-12-23 om 13 41 00" src="https://user-images.githubusercontent.com/33354141/147241910-d062c0e6-dcc2-4ecf-8aed-21b9f857cb05.png">

on the configuration menu item:

<img width="276" alt="Schermafbeelding 2021-12-23 om 13 41 23" src="https://user-images.githubusercontent.com/33354141/147241957-ef3c5df7-bbfd-40f2-8e69-98d1bc1336a4.png">

### Steps to reproduce the issue

1. have an update available and see 
2. nothing
3.
...

### What version of Home Assistant Core has the issue?

2022.2.0.dev20211222

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

macOS Monterey 12.0.1 

### Additional information

We now have to explicitly check Configuration, while a notification made it standout.

**Comment by ludeeus** [comment]
It never did, this is not a bug.
