### ISSUE TITLE
No on/off icon for Switch entities with device_class in customize

### ISSUE THREAD

**Issue by guillermorueda** [home-assistant/frontend#11021]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When you set `device_class` in a `switch` entity, the icon changes:

- From:
  - generic `mdi:flash`
- To:
  - outlet: `mdi:power-plug-off`
  - switch: `mdi:toggle-switch-off`

Nice so far. However, unlike [other `device_class` customized entities](https://www.home-assistant.io/docs/configuration/customizing-devices#device-class), the icons for outlet and switch never change between on and off, only the color changes.

### Describe the behavior you expected

When you set `device_class` in a `switch` entity, the icon changes:

- From:
  - generic `mdi:flash`
- To:
  - When off:
    - outlet: `mdi:power-plug-off`
    - switch: `mdi:toggle-switch-off`
  - **When on:**
    - **outlet: `mdi:power-plug`**
    - **switch: `mdi:toggle-switch`**

### Steps to reproduce the issue

1. Have/Create a `switch`
2. In `configuration.yaml`, add `device_class: outlet` or `device_class: switch` under `homeassistant:`'s `customize:`, as indicated in [Manual Customization](https://www.home-assistant.io/docs/configuration/customizing-devices#manual-customization)
3. Add the switch from 1st step in a Lovelace view
4. Turn on/off the switch and notice how the color changes but the icon remains unchanged

### What version of Home Assistant Core has the issue?

core-2021.12.5

### In which browser are you experiencing the issue with?

All browsers (Edge, Chrome, Safari)

### Which operating system are you using to run this browser?

Desktop (OS) and mobile (iOS) versions

### State of relevant entities

```txt
entity_id: switch.switch_switch
state: on
attributes:
  friendly_name: Switch - Switch
  device_class: switch

entity_id: switch.switch_outlet
state: on
attributes:
  friendly_name: Switch - Outlet
  device_class: outlet
```

### Problem-relevant frontend configuration

```yaml
type: entities
  entities:
    - entity: switch.switch_switch
      name: Switch - Switch
    - entity: switch.switch_outlet
      name: Switch - Outlet
```

### Additional information

The expected behavior would set `switch` entities at parity with `binary_sensor`, `sensor`, and `cover`, where each of the icons change depending on their current `state` value depending on their `devices_class`.

Here's an example of how different entities' icons look by default depending on their `device_class` (note: `battery` device class doesn't have an on/off state given its values aren't binary, instead, it changes icon based on the number the current `state` is on):

![image](https://user-images.githubusercontent.com/1143812/147375201-437e728b-4cfa-40c5-a4b9-e8834461c00c.png)

![image](https://user-images.githubusercontent.com/1143812/147375279-6d70e726-2f12-4b25-833f-eb17c9e4e759.png)

The expectation would be that the last 2 icons from the example change to these instead:

![image](https://user-images.githubusercontent.com/1143812/147375296-ca26f6e6-0493-4526-88a3-da6f5a1f1d23.png)

**Comment by mbo18** [comment]
Same issue here:
![16D50237-F467-4D01-9A56-7A69CEEDBB11](https://user-images.githubusercontent.com/12999535/147834912-ac0ca6f3-b31a-4d4d-b3ea-bf0e72a13622.jpeg)
![848375AB-E39D-4CEE-BF66-418DD38743CC](https://user-images.githubusercontent.com/12999535/147834914-08bdc2df-8ca3-4a5e-91e7-a2a3ea74e762.jpeg)

**Comment by mbo18** [comment]
Seems related to https://github.com/home-assistant/frontend/pull/10475
Or
https://github.com/home-assistant/frontend/pull/3096

**Comment by Mariusthvdb** [comment]
seems an issue indeed. though I checked the file and it should be ok. not sure whats happening .
guess I have to re-instate my old customization.....

**Comment by mbo18** [comment]
Oh wow 🤩 
Thank you!

**Comment by guillermorueda** [comment]
Yay! Awesome! Thank you 🥳
