### ISSUE TITLE
Gauge looks wrong in Safari and IOS App. Working fine in Google Chrome

### ISSUE THREAD

**Issue by rhoddan** [home-assistant/frontend#11022]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Check the needles
IOS App:
![IMG_0870](https://user-images.githubusercontent.com/33499995/147390707-cc1cbc35-9948-450e-afe1-f2428684c842.jpeg)
macOS Safari:
![Skärmavbild 2021-12-25 kl  18 45 28](https://user-images.githubusercontent.com/33499995/147390716-6061f7f7-fe52-4723-bc5f-5b60177dcb5d.png)
macOS Chrome:
![Skärmavbild 2021-12-25 kl  18 45 47](https://user-images.githubusercontent.com/33499995/147390718-f776b5e1-ff76-4fba-90c2-788409709599.png)

### Describe the behavior you expected

The needles is placed in wrong positions when using IOS App and macOS Safari.

### Steps to reproduce the issue

1. create gauges (I have a 4 in a horizontal line)
2. test in IOS App and Safari
3.
...

### What version of Home Assistant Core has the issue?

2021.12.5

### In which browser are you experiencing the issue with?

Safari Version 15.2 (17612.3.6.1.6)

### Which operating system are you using to run this browser?

macOS Monterey 12.1

**Comment by slvwolf** [comment]
Looks like duplicate to #10910
