### ISSUE TITLE
Font color does not change on Theme switch

### ISSUE THREAD

**Issue by nenadmilano** [home-assistant/frontend#11026]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When a theme change is initiated by an automation the font color does not change to the new value set in the new theme. Only a manual refresh (pull-down) adjusts the font color to the new value.

### Describe the behavior you expected

Font color should adapt without having to interact manually (as it did before 2021.12)

### Steps to reproduce the issue

1. Create two Themes with different font colors
2. Create automation to toggle between them
3. Watch Dashboards
...

### What version of Home Assistant Core has the issue?

core-2021.12.5

### What was the last working version of Home Assistant Core?

core-2021.11.x

### In which browser are you experiencing the issue with?

iOS Companion App 2021.12.1 and Safari

### Which operating system are you using to run this browser?

iOS 15.2

### Additional information

Was functioning before 2021.12 flawlessly but since the update I have to manually refresh all iPads in the house after the Theme switches from Night to Day (iOS Dark and iOS Light Themes from HACS are used)

**Comment by Mariusthvdb** [comment]
do you recognize this in any way: https://github.com/home-assistant/frontend/issues/10988 
seems related to the theme switching issue I experience?

**Comment by nenadmilano** [comment]
Yeah sounds similar but strange as in my case the background color updates properly and only the font color seems stuck - but in general the issue could be related.

**Comment by mrand** [comment]
Standard question associated with frontend issues: does it still happen if you remove all custom cards, and card mod, and any custom modification you do on your instance? If not, then re-add them one-by-one to figure out the cause and then notify the person responsible for that custom item.
