### ISSUE TITLE
Missing some mdi icons

### ISSUE THREAD

**Issue by coolhansen** [home-assistant/frontend#11032]
### The problem

After the update I'm missing some icons in HA. For instance: HACS, mdi:bottle-wine, mdi:card
I'm able to choose the icon but it will be not shown. Not a big problem but I want to report it.
![C02FA61F-E49D-4FB3-BA53-147964BA6051](https://user-images.githubusercontent.com/77995245/147484103-93e034f8-beba-4fd5-8028-b4122e5d5673.jpeg)

### What version of Home Assistant Core has the issue?

2021.12.5

### What type of installation are you running?

Home Assistant OS

**Comment by bramkragten** [comment]
Please clear your cache, and check for errors in the console.

What browser are you using?

**Comment by coolhansen** [comment]
> Please clear your cache, and check for errors in the console.
> 
> What browser are you using?

It helps. Everything is okay now.
