### ISSUE TITLE
Problem with values not updating in frontend since update to core-2021.12.6

### ISSUE THREAD

**Issue by haseat** [home-assistant/frontend#11039]
### The problem

Since updating to core-2021.12.6 the frontend seems to lose the connection to core after a couple of minutes of inactivity. This happens on chrome as well as the HA companion app. 

For easier understanding I made a video: https://watch.screencastify.com/v/k0KSmahcCPBdQdRNzkwd

When I change the target temperature in this video, the values are actually sent to the backend (as the thermostat behind me turns on/off accordingly), but the values in the frontend do not change. After hitting F5 in the browser everything works again.

### What version of Home Assistant Core has the issue?

core-2021.12.6

### What was the last working version of Home Assistant Core?

core-2021.12.5

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
I could not find anything that seems relevant
```

**Comment by Efekent** [comment]
@Mpgod80 and @AmoebeLabs your issues are not same as this one, this has to do with frontend, it just freezes at the state of that moment, and the problem appeared since 2021.12.6 before that me and @haseat did not have this problem. There was also a update on frontend in  2021.12.6 I think it has to do with that but I am not sure.

**Comment by AmoebeLabs** [comment]
> @Mpgod80 and @AmoebeLabs your issues are not same as this one, this has to do with frontend, it just freezes at the state of that moment, and the problem appeared since 2021.12.6 before that me and @haseat did not have this problem. There was also a update on frontend in 2021.12.6 I think it has to do with that but I am not sure.

I will check again what I'm seeing, and on which version. But it is in the frontend, as the entities do change state in the backend.

**Comment by Mothamoz** [comment]
Having the same issue since 2021.12.6

**Comment by borft** [comment]
I'm on 2021.12.6, after about 20 minutes the UI doesn't get updated anymore. From what I can tell, the websocket that's used for communication between HA and the UI is closed after about 1000 events. A new socket is opened, but that doesn't seem to subscribe to all events.

**Comment by quaqo** [comment]
> I confirm this bug. I was looking for issues with core. But it's the frontend.

I actually think this is the problem:

https://github.com/home-assistant/home-assistant-js-websocket/commit/f45c5cded6239d5ecca723ac9d66227a25dde7f2

**Comment by ASNNetworks** [comment]
Applies to Android app as well. No issues before 12.6 release. So has to do with the latest 12.6 release.

**Comment by balloob** [comment]
Will be fixed in 12.7 with https://github.com/home-assistant/frontend/pull/11042
