### ISSUE TITLE
Can't activate links or navigation bar items using VoiceOver in web UI. 

### ISSUE THREAD

**Issue by digitaldarragh** [home-assistant/frontend#11034]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using VoiceOver, the screen reader for people who are blind on IOS and Mac OS devices, it is not possible to activate links in the navigation menu or the configuration menu.  

It seems that this is because it expects the enter key to be pressed in order for the link to be activated. Tapping on the item sets focus to it.  I'm informed that visually, this results in the expected focus colour change but it doesn't let me move to that page. 

Please keep in mind that this UI works beautifully on Windows.   Aside from a few niggling things that are quite minor, I really have no complaints when using HomeAssistant in Windows. 

If you are interested, I am blind.  I'm a senior systen engineer and have worked with technology to pay the bills for 20 years. I only started using HomeAssistant about 2 months ago.  Since then I have spent *way too much* on smarg home tech and I have loved every minute of working on it.  I'm thrilled by how accessible HomeAssistant has been right out of the box and I have actually Emailed the maintainers to highlight this.  Well done to you all for doing such an amazing job.  If I can be of any assistance to you please let me know. 

### Describe the behavior you expected

When you double tap on a navigation item, the associated page should open. 

### Steps to reproduce the issue

1.  Open a browser in IOS. It doesn't matter what one. 
2.  Open the homeAssistant web UI. 
3.  Try to move to one of the items in the navigation menu. 
4.   If you are in a dashboard, you will notice that you can toggle buttons etc. But the navigation menu doesn't work as expected. 

Expected result.  When you double tap on a navigation item, the associated page should open. 

### What version of Home Assistant Core has the issue?

2021.12.6

### In which browser are you experiencing the issue with?

Safari

### Which operating system are you using to run this browser?

IOS 15

**Comment by steverep** [comment]
Take a look at #8178. There is a pool request pending that should fix this.
