### ISSUE TITLE
cloud shows button entities as scene

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#11045]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

in the /config/cloud/google-assistant panel, I accidentally noticed that all entities of domain button are displayed as scene.

### Describe the behavior you expected

show as domain Button

### Steps to reproduce the issue

1. open given page and check under scene to find button
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.2.0.dev20211229

### What was the last working version of Home Assistant Core?

dk

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

MacOS Monterey 12.0.1

**Comment by frenck** [comment]
That is correct behavior, not a bug, and not frontend related :)

**Comment by Mariusthvdb** [comment]
ok, thanks
its just very confusion to find out, because even when clicking the details of the entity, there's no mentioning of a scene. Had to debug the HA/GH connection today because of an issue, and all of these Scenes were suddenly there, while I have excluded the domain Scene...

Some hint to them being of domain Button would be very nice to have in the frontend because of that.
