### ISSUE TITLE
Customizing entities via the UI no longer exist

### ISSUE THREAD

**Issue by digi303** [home-assistant/frontend#11048]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Up to version 2021.11, you could change the entity properties via Settings / Customisation. This point has disappeared in 2021.12 with the new layout. A setting is only possible via customize.yaml.
Is this a bug or a feature?

### Describe the behavior you expected

I like the possibility to change the device-classes etc. over the UI

### Steps to reproduce the issue

1. see above
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.12.x

### What was the last working version of Home Assistant Core?

2021.11.5

**Comment by frenck** [comment]
That is correct, see: <https://www.home-assistant.io/blog/2021/12/11/release-202112/#breaking-changes>

![image](https://user-images.githubusercontent.com/195327/147743843-3718e45c-d47c-466f-98d3-31e48cb563da.png)

**Comment by digi303** [comment]
Sorry, haven't seen / read that. And I always thought I read the changelog carefully. :-)

**Comment by PocketMiner82** [comment]
So now it is impossible for entities without uuids to be customized via the ui @frenck? or is there still a way to do it? I think the Customize UI was a useful feature for such entities...

**Comment by frenck** [comment]
> So now it is impossible for entities without uuids to be customized via the ui @frenck? or is there still a way to do it? I think the Customize UI was a useful feature for such entities...

The customization feature still exists in YAML.

**Comment by PocketMiner82** [comment]
> > So now it is impossible for entities without uuids to be customized via the ui @frenck? or is there still a way to do it? I think the Customize UI was a useful feature for such entities...
> 
> The customization feature still exists in YAML.

Ok, I understand. I liked it more to be able to customize entities without UUIDs (like the one's from the modbus integration) from **_the UI_** and not from yaml, because it was way easier. I don't really understand, why editing entities without UUID is now impossible @frenck...

**Comment by spacegaier** [comment]
> > > So now it is impossible for entities without uuids to be customized via the ui @frenck? or is there still a way to do it? I think the Customize UI was a useful feature for such entities...
> > 
> > 
> > The customization feature still exists in YAML.
> 
> Ok, I understand. I liked it more to be able to customize entities without UUIDs (like the ones from the modbus integration) from **_the UI_** and not from yaml, because it was way easier. I don't really understand, why editing entities without UUID is now impossible from the UI @frenck...

This has been discussed and explained multiple times, e.g. in the release notes post itself. Hounding _frenck_ here will not change that 😉.

**Comment by PocketMiner82** [comment]
Ok, I just thought, there must be a way to still do this from the UI, but it's ok.

**Comment by PocketMiner82** [comment]
Also, this documentation: https://www.home-assistant.io/faq/unique_id confused me a bit. Sorry for asking that much xD

**Comment by spacegaier** [comment]
> Also, this documentation: https://www.home-assistant.io/faq/unique_id confused me a bit. Sorry for asking that much xD

Good point, that FAQ page needs to be updated indeed.

**Comment by NODeeJay** [comment]
@frenck Can you please let us know which pull request or commit it was, I am unable to find it with the search function for custom* back till Dec 2021?

**Comment by frenck** [comment]
@NODeeJay See the release notes.
