### ISSUE TITLE
Text alignment issue on Server Controls page

### ISSUE THREAD

**Issue by jamespreedy** [home-assistant/frontend#11051]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On the Server Control pane within Configuration => Settings the text “Groups, Group Entities, and Notify Services” is centre aligned. All other options are left aligned - “Automations”, “HomeKit” etc.

This is the case on my iPhone 13 Pro in both Mobile Safari and the iOS app of Home Assistant.

### Describe the behavior you expected

It should be left aligned like the other list items.

### Steps to reproduce the issue

Go to Configuration => Settings => Server Controls => YAML Configuration Reloading.

### What version of Home Assistant Core has the issue?

core-2021.12.7

### What was the last working version of Home Assistant Core?

core-2021.11.x

### In which browser are you experiencing the issue with?

Safari on iOS 15.2

**Comment by bram-pkg** [comment]
Any update on this?

Currently it looks like this: 
![chrome_BgIrCCc94N](https://user-images.githubusercontent.com/13304739/156901702-dfa54e37-7efd-4b4d-908e-833359d205b3.png)

Adding a `text-align: start` to the button fixes it.
