### ISSUE TITLE
No devices listed in device panel

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#11068]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

originally posted in https://github.com/home-assistant/core/issues/63160 I believe this is a Frontend issue after all

### Describe the behavior you expected

have the devices listed

### Steps to reproduce the issue

1. navigate to integration
2. click listed devices
3.
...

### What version of Home Assistant Core has the issue?

2022.2.0.dev20220101

### What was the last working version of Home Assistant Core?

not sure

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

MacOS 12.0.1 12.0.1 Monterey 12.0.1 

### State of relevant entities

```txt
na
```

### Problem-relevant frontend configuration

```yaml
na
```

### Javascript errors shown in your browser console/inspector

<img width="621" alt="Schermafbeelding 2022-01-01 om 02 02 22" src="https://user-images.githubusercontent.com/33354141/147841933-98ee346a-6c83-4bb0-b5da-3057be6b2674.png">

### The problem

as title. for several integrations, core and custom, devices are avalable in the integrations panel, like:

<img width="291" alt="Schermafbeelding 2022-01-01 om 01 57 50" src="https://user-images.githubusercontent.com/33354141/147841893-b59a967c-f53a-446f-81b2-d585ce0e3c67.png">

clicking devices, and navigating to the devices page shows an empty page

Affected integrations:

Core:
  Zwave-Js
  Unifi
  Google cast

Custom:
  Tahoma

**Comment by Mariusthvdb** [comment]
I now notice that when navigating directly to config/devices/dashboard no devices are listed either.....
<img width="1054" alt="Schermafbeelding 2022-01-02 om 15 52 07" src="https://user-images.githubusercontent.com/33354141/147879635-c1839dde-3f0c-48ef-8b9d-8cc60e369d8a.png">

**Comment by Mariusthvdb** [comment]
Still happening on dev 0103 so no previous fluke, but a major issue tbh…

**Comment by Mariusthvdb** [comment]
fond hat was causing this, and the 'object (evaluating 'p[e.area_id].name')' was the hint:

apparently some of my devices for which I had changed an Area got the 'wrong' area_id set. In this particular case I had changed the name of the area from Keuken to Kitchen, and the area_id was still set to `keuken`. 

I checked device_registry for these, and the mentioned 4 integrations all had a single entity for which the transition hadnt gone well.
Manually edited the device_registry for those devices. All devices are back...!

Not sure if this is supposed to be, but a single edit fluke shouldn't prevent showing any device in the device_panel shouldnt it?

**Comment by spacegaier** [comment]
How had you changed the area? Renaming an area through the UI should not change its ID so that should have no impact on the device registry and therefore not result in any unresolved areas (and hence exceptions) in the frontend rendering.

**Comment by Mariusthvdb** [comment]
I think I did that manually where eg my formerly name Area Audio  had the id audio, and I later renamed that area to Auditorium, but the id hadnt changed along. My templating logic desires the id's to be identical but slugged Names, so I had changed that id to auditorium in the .storage.

I know that is a user error, and reported that as such above.

Still it seems a bit surprising that would break the full  devices page.

**Comment by spacegaier** [comment]
Not surprising from coding perspective since if we have an area ID provided from a device we expect that we also do have that area and can read its info (e.g. the name), which was not the case here, hence the exception and that of course breaks the page.

From my perspective this is not something we should need to account for in the frontend coding and I would vote to close this issue therefore. We could of course in theory check if the area actually exists, but where do we draw the line? Do we also need to check each other read access e.g. to the domain value of entities of devices?

**Comment by Mariusthvdb** [comment]
Agree in closing , thanks for you elaborate response!

Some guard for only breaking the individual device page and not the full devices page might still be an idea, but I can see you don't want/need to account for all user errors ;-)
