### ISSUE TITLE
Cast background always white

### ISSUE THREAD

**Issue by dbrown8674** [home-assistant/frontend#11077]
### The problem

When casting to a nest hub the background is always white.

![image](https://user-images.githubusercontent.com/47458312/147622972-dcf626d9-e4c6-413c-b35f-f100fe48aefb.png)

### What version of Home Assistant Core has the issue?

2021.12.6

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

cast

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/cast

**Comment by nschwing** [comment]
I have the same problem. The service call set_theme does not work for me @pascalwinters 

In Google Home-App i have set "Dark" as theme. 
When the cast is running and i go to Google Home-App and set theme to "White" and back to "Dark" again, it's finally dark. 
But everytime i recast it's white again...
