### ISSUE TITLE
Misleading alert title

### ISSUE THREAD

**Issue by quantummobile** [home-assistant/frontend#11076]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After 2FA re-authetication to Synology NAS HA pops out aler that reads:

Title: Aborted
Description text: Re-authentication was successful

The title should read as "Success", but not "Aborted".

### Describe the behavior you expected

After 2FA re-authetication to Synology NAS HA pops out aler that reads:

Title: Aborted
Description text: Re-authentication was successful

### Steps to reproduce the issue

1. Go to Cofiguration > Integrations;
2. Look for Synology integration, press button "Reconfigure";
3. Follow the instructions.

### What version of Home Assistant Core has the issue?

core-2021.12.7

### Additional information

<img width="401" alt="Screenshot 2022-01-03 at 08 58 37" src="https://user-images.githubusercontent.com/47085307/147906093-f8034dd8-7981-43fe-a93e-cde9690bc94d.png">

**Comment by spacegaier** [comment]
Yeah, it's a known issue, that seems easy to fix, but the proper solution requires changes to both the backend and the frontend. I actually started on a possible fix some time ago, but never brought it to completion so far...

**Comment by matthiasdebaat** [comment]
Could we change the title as a quick fix?
