### ISSUE TITLE
statistics-graph card shows "Loading statistics..." when using a dynamic variable for days_to_show

### ISSUE THREAD

**Issue by jantoney** [home-assistant/frontend#11085]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using a statistics-graph card and trying to place a dynamic value into ```days_to_show```, the card shows ```Loading statistics...```
The following lines have all been tried within the card.
Full card config later in the issues post.

```yaml
'{{states("input_select.lovelace_temperature_day_picker")}}'
```
```yaml
{{states("input_select.lovelace_temperature_day_picker")}}
```
```yaml
'{{states("input_select.lovelace_temperature_day_picker")|int}}'
```
```yaml
{{states("input_select.lovelace_temperature_day_picker")|int}}
```
```yaml
"{{states('input_select.lovelace_temperature_day_picker')|int}}"
    # This last line is updated to the following after you hit save
    '{{states(''input_select.lovelace_temperature_day_picker'')|int}}'
```

### Describe the behavior you expected

The card to display the graph

### Steps to reproduce the issue

1. Setup a helper with entiry_id ```input_select.lovelace_temperature_day_picker```
    - The entity ```input_select.lovelace_temperature_day_picker``` is a Dropdown helper with just the number 1, 2, 7, 14, 30
    - Screen shot & config from Dev Tools below
2. Add a **statistics-graph** card to LoveLace
3. Update the config of the card to the configuration shown under **Problem-relevant frontend configuration**
    - remembering to change the temp entities to ones in your environment:
4. View the card
    - Screen shot below

### What version of Home Assistant Core has the issue?

core-2021.12.7

### In which browser are you experiencing the issue with?

Microsoft Edge Version 96.0.1054.62 (Official build) (64-bit) && Firefox 95.0.2 (64-bit)

### Which operating system are you using to run this browser?

Windows 11 21H2 (OS Build 22000.376)

### State of relevant entities

```txt
Entity: input_select.lovelace_temperature_day_picker
State: 7

State attributes:
options:
  - '1'
  - '2'
  - '5'
  - '7'
  - '14'
  - '30'
editable: true
icon: mdi:calendar-month
friendly_name: 'Lovelace: Temperature Day Picker'
```

### Problem-relevant frontend configuration

```yaml
type: statistics-graph
entities:
  - entity: sensor.ble_humidity_ensuite_temp
    name: Ensutie
  - entity: sensor.ble_humidity_kitchen_temp
    name: Kitchen
  - entity: sensor.ble_humidity_study_temp
    name: Study
days_to_show: '{{states("input_select.lovelace_temperature_day_picker")|int}}'
```

### Javascript errors shown in your browser console/inspector

```txt
Uncaught (in promise) RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at f (ha-chart-base.ts:20)
    at HTMLElement.value (hui-statistics-graph-card.ts:134)
    at HTMLElement.value (37c07fdc.js:1)
    at HTMLElement.performUpdate (styles.ts:366)
    at HTMLElement.scheduleUpdate (styles.ts:366)
    at HTMLElement._$EC (styles.ts:366)
```

### Additional information

I also tried running Windows Sandbox so there were 100% no caching issues.

Also found another user with the same problem on a community forum post back from October 2021: 
https://community.home-assistant.io/t/dynamic-days-to-show-on-a-statistics-graph/347139

## Screen shot of issue as shown in Love Lace
![image](https://user-images.githubusercontent.com/3225331/148007089-e6650f19-5d1a-49eb-b967-0aead19e960c.png)

## Screen shot of dropdown helper configuration
![image](https://user-images.githubusercontent.com/3225331/148007056-076b5428-9ee9-4a7f-a37e-9f841a73a6b0.png)

**Comment by spacegaier** [comment]
This is not supported. The docs state that you have to provide a numeric value in the card configuration, but you are providing a string and hoping that the frontend will evaluate that provided template into a number, which is not the case (not for this card, nor in general...with the exception of the markdown card).

You could raise a feature request, if you think that this is a needed feature, but then the next question would be: Why this configuration variable and not others and where do we draw the line then?
