### ISSUE TITLE
Frontend not reachable after 1-2 days

### ISSUE THREAD

**Issue by pacoso81** [home-assistant/frontend#11092]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I had some problem after i installed second docker (miner) on my PC.
After installing of the second docker my HASS didn't run any more.
I trued to restore my VM image to early point but that did not help, so i update my VirtualBox to latest version and HASS was working.
I then restore the HASS from my latest backup and updated HASS to 12.6/12.1/7.0 (before this latest version).
After everything started working again i noticed that after a day or two i can't log into HASS by web.
In the console i wound that it is frozen at "ha >" and have to do shutdown command and then gives me 
"rcu: INFO:  rcu_sched detected stalls on CPU/tasks: " and a lot of other info,
then i have to do another shutdown command to actually shut down the docker.

Strange thing is that after i start it again and go to log i can see that all the sensors and switches wore working wile i can't access the frontend.

i'm running HASS on VirtualBox 6.1.30 on Windows 10.
core-2021.12.7
supervisor-2021.12.2
Home Assistant OS 7.1

So now i can't tell is it the HASS or VirtualBox problem.
Can you help, please?

### Describe the behavior you expected

Continue to work

### Steps to reproduce the issue

1. Start the HASS
2. Wait for 1-2 days

### What version of Home Assistant Core has the issue?

2021.12.7

**Comment by Driekes** [comment]
I have this issue as well since some time. I have used a fresh install, but it keeps happening. I don't know if this came from a Virtualbox update or HA OS as it happened gradually. 
I have been running fine for months, then I had an issue (I assume unrelated) and decided to freshen up my install (updated OS/Virtualbox etc).
<img width="1030" alt="Schermafbeelding 2021-12-30 om 17 06 06" src="https://user-images.githubusercontent.com/688578/149498942-473d1334-5a46-4712-8ba3-298f93228e9b.png">

**Comment by pacoso81** [comment]
> I have this issue as well since some time. I have used a fresh install, but it keeps happening. I don't know if this came from a Virtualbox update or HA OS as it happened gradually. I have been running fine for months, then I had an issue (I assume unrelated) and decided to freshen up my install (updated OS/Virtualbox etc).

I think that i solved my problem, it is running now for 4-5 days whitout freezing.

When it freezes i click Pause (2 times) on VM, first time it unfreezes HA and second Pause to resume VM, and it worked.
But that was not a good solution so i started poking around.

What i did was i made backup of HA and snapshot of VM, than i reinstall the VirtualBox to earlier version, but i had problem whit the current snapshot so i reverted to earlier snapshot which was unable to recover by that VB version.
I upgraded to befor last version, same thing.
So i ended up upgrading again to newest version of VB and HA backup from November or December 2021, and than i upgrade to newest HA 12.9.
Since last Sunday i have no problem.

**Comment by pacoso81** [comment]
i seams to happen when cpu is heavily utilized. 
it happens even if i install HD camera in motioneye or if i compile ESPHome file.
i have disconnected serial port, sound card and the things got little bit better, now i resized the storage space and i will see if there is any improvement.
