### ISSUE TITLE
Problem Energy entity last_reset

### ISSUE THREAD

**Issue by Mick51** [home-assistant/frontend#11107]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The daily cycle seems corrupted or buggy, it should normally reset every 24 hours but don't do it at all, my electrical readings are ditch. Why such bugs on things so important ???

Screen 1 => [https://zupimages.net/viewer.php?id=22/01/n79v.jpg]
Screen 2 => [https://zupimages.net/viewer.php?id=22/01/guyw.jpg]

### Describe the behavior you expected

Logically a Dailly or daily cycle must be reset to 00H each day, it continues without this reset for several days, there is a big problem with the cycles .........

### Steps to reproduce the issue

1.Do as in my screenshots above, I brought you the proof in pictures that the cycles do not reset ....
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.12.8

### In which browser are you experiencing the issue with?

Google Chrome Version 97.0.4692.71 (Build officiel) (64 bits)

### State of relevant entities

```txt
sensor.energie_journaliere
state_class: total_increasing
last_reset: '2022-01-04T23:00:00.016877+00:00'  <== What ???????? Not 00h ????
source: sensor.index
status: collecting
last_period: 694
meter_period: daily
cron pattern: 0 0 * * *
unit_of_measurement: Wh
device_class: energy
icon: mdi:counter
friendly_name: energie_journaliere
```

**Comment by deathcult456** [comment]
Same hère.

**Comment by spacegaier** [comment]
@Mick51 Can you please inline the image in the ticket here. Most people (or at least me😄) are not keep clicking on links going to some strange image page.

Also this seems to duplicate https://github.com/home-assistant/frontend/discussions/11106 so that could be closed?

All in all this however sounds more like a backend/core issue rather than the frontend.
