### ISSUE TITLE
"Button" entities are saved in scene created by device in UI

### ISSUE THREAD

**Issue by koying** [home-assistant/frontend#11108]
### The problem

"Button" entities are saved in scene created by device in UI.
As those have no state, it makes no sense and produce a Warning when applying the scene

### What version of Home Assistant Core has the issue?

2021.12.7

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

Button

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/button/

### Anything in the logs that might be useful for us?

```txt
2022-01-06 13:53:10 WARNING (MainThread) [homeassistant.helpers.state] Integration button does not support reproduce state
```
```


### Additional information

_No response_

**Comment by frenck** [comment]
Thanks, @koying 👍 
Opened up a PR to address the issue.

**Comment by koying** [comment]
FWIW, I created a FR with other issues/inconvenience/inconsistencies in scenes: https://community.home-assistant.io/t/do-not-save-read-only-attributes-unknown-unavailable-states-in-scenes/376089

IMHO, those are all issues, but if you would be so kind as to give your opinion...
Thanks

**Comment by frenck** [comment]
> FWIW, I created a FR with other issues/inconvenience/inconsistencies in scenes
Issues belong in the issue tracker, not the forums.

**Comment by koying** [comment]
Question was whether you consider those are issue or FR, but nevermind. Thx
