### ISSUE TITLE
Sidebar items randomly reset all the time

### ISSUE THREAD

**Issue by Stooovie** [home-assistant/frontend#11115]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Items shown in Sidebar always ultimately reset to defaults. I don't need History, Media Player or Developer Tools on many of my end devices.

### Describe the behavior you expected

Sidebar items stay as I have configured them.

### Steps to reproduce the issue

1. configure sidebar items from the User icon menu -> "Change the order and hide items from the sidebar"
2. it resets to default after an arbitrary amount of time

### What version of Home Assistant Core has the issue?

2021.12.8

### In which browser are you experiencing the issue with?

Edge Mac 94.0.992.38, Safari 14 Big Sur 11.6, all browsers

### Which operating system are you using to run this browser?

Windows 10, MacOS Monterey, iOS 15

### Additional information

I have this issue for more than two years now. End device OS or browser/app does not make any difference.

**Comment by spacegaier** [comment]
Those settings are stored locally in your browser/login session. Could that getting reset in your case?

**Comment by Stooovie** [comment]
I don't know but if ALL my Windows, MacOS and iOS devices do it, it's probably not the end-device issue, is it?

**Comment by spacegaier** [comment]
You could try to check in your browser dev tools in the "Local Storage" of the "Application" tab if there is a `sidebarHiddenPanels`, should be updated every time you change the sidebar items.

**Comment by Stooovie** [comment]
It is there in both Safari and Edge (Chromium) on both Win and Mac, I guess it gets reset somehow. I don't usually clear browser caches unless required, so that should not be it. I use Apple devices more, so I probably notice this more on their platforms, but it happens like several times a week, or at very least once a week.

**Comment by Stooovie** [comment]
Happened again, in the official HA app... It is beyond annoying.
