### ISSUE TITLE
2021.12 "Triggering on any, but only state changes" feature breaks the UI editor

### ISSUE THREAD

**Issue by nvx** [home-assistant/frontend#11121]
### The problem

The new feature in 2021.12 to trigger on only state changes as per https://www.home-assistant.io/blog/2021/12/11/release-202112/#triggering-on-any-but-only-state-changes enables this syntax:

```
automation:
  trigger:
    - platform: state
      entity_id: media_player.living_room
      to: ~
```

Unfortunately setting an automation in the UI to have ~ as the to field results in the yaml `to: '~'` which does not seem to work.

Editing in YAML mode to remove the quotes to have `to: ~` works, but reloading the UI results in the following error message:

```
The provided value for 'to' is not supported by the visual editor. We support (string) but received (null).
```

And worse the `to: ~` is silently changed to `to: null`

### What version of Home Assistant Core has the issue?

core-2021.12.8

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Automation

**Comment by bdr99** [comment]
This should not be marked as stale; the issue still exists in 2022.4.

**Comment by nvx** [comment]
Still an issue in 2022.7

**Comment by nvx** [comment]
Just updated to 2022.10.1, issue still remains.

**Comment by melyux** [comment]
Having multiple "to" and "from" states also breaks the UI editor. The UI editor should be updated at the same time to handle changes like this.

**Comment by karwosts** [comment]
Created a pull request to handle the null issue. 

Briefly looked at multiple states as well, but that fix would be more involved, since there doesn't currently exist a selector type that can handle multiple states, that would have to be added. If this gets closed for the original request being fixed, you can open a new feature request if multiple states is important to you.
