### ISSUE TITLE
Subscription not found error in Chrome console --> Card NOT updating

### ISSUE THREAD

**Issue by AmoebeLabs** [home-assistant/frontend#11132]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Some cards are not updating after switching to another view and back.

A refresh helps, but also clicking another card for the "more-info" dialog: suddenly the card in question starts updating again...

### Describe the behavior you expected

Cards always update!

### Steps to reproduce the issue

1. Select a view
2. Switch to another view
3. Switch back, and see card is NOT updating
...

Not all views do this, so the steps are easy, but the problem doesn't for every view.

### What version of Home Assistant Core has the issue?

core-2021.12.8

### What was the last working version of Home Assistant Core?

core-2021.12.5 if I'm right.

### In which browser are you experiencing the issue with?

Chrome (PC) and Safari on iPad/iPhone

### Javascript errors shown in your browser console/inspector

```txt
See Additional information for screenshot.

The browser shows an uncaught error, "Subscription not found."
```

### Additional information

![HA Subscription not found](https://user-images.githubusercontent.com/7996307/148697321-252ca1a0-c2cf-4629-b4d0-a89583c4a953.png)

**Comment by spacegaier** [comment]
Is this in relation to specific cards (so issue always appears with the same ones)? Any custom cards being used here?

With the current information it is nearly impossible to pinpoint and replicate the issue.

The error from your screenshot is actually raised by the HA backend when something tried to unsubscribe from HA events for which there is not actually any subscription to begin with (`/components/websocket_api/commands.py`, method `handle_unsubscribe_events`).

**Comment by AmoebeLabs** [comment]
> The error from your screenshot is actually raised by the HA backend when something tried to unsubscribe from HA events for which there is not actually any subscription to begin with (/components/websocket_api/commands.py, method handle_unsubscribe_events).

At least the error explains why a card is not updating :smile:

> Is this in relation to specific cards (so issue always appears with the same ones)? Any custom cards being used here?

It is random and in most cases affects the last card in the view.

> With the current information it is nearly impossible to pinpoint and replicate the issue.

It happened randomly, so I could not reproduce it easily.

However, since updating to the currently latest version of HA, I can't reproduce it anymore.

So, @spacegaier , close this issue, and re-open it again if I see this again and can reproduce it? Seems no use of letting this issue open from my point of view.
