### ISSUE TITLE
Devices and entities in area view are not sorted

### ISSUE THREAD

**Issue by eikowagenknecht** [home-assistant/frontend#11148]
### The problem

In the new Area view, devices and entities are not sorted. That makes it rather hard to read when there are lots of devices and/or entities. An alphabetical sorting would be expected.

Example:
![image](https://user-images.githubusercontent.com/1475672/148819022-398c5758-8e58-45a8-a6fb-ab2c19e331f1.png)

### What version of Home Assistant Core has the issue?

core-2021.12.8

### What type of installation are you running?

Home Assistant OS

**Comment by frenck** [comment]
Transferred as this is a frontend suggestion/issue. Not core.
