### ISSUE TITLE
Inconsistent handling of spaces before unit

### ISSUE THREAD

**Issue by eikowagenknecht** [home-assistant/frontend#11149]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Config: No space
![image](https://user-images.githubusercontent.com/1475672/148821562-a402932d-519c-4fa6-918b-d8e2f102d527.png)
Lovelace: No space in entity list card, space in entity card:
![image](https://user-images.githubusercontent.com/1475672/148821598-ce676f28-7c78-43f4-9e4d-cb31ad3acc1c.png)

### Describe the behavior you expected

Spacing should be similar in all places. There are various possibilities, but I would suggest to just go with a single space as it looks cramped without any spacing for most units.

See e.g. https://english.stackexchange.com/questions/2794/punctuation-with-units for a longer discussion about the "correct" spacing.

### Steps to reproduce the issue

1. Create helper with unit
2. Add cards to lovelace
3. Look at the cards
...

### What version of Home Assistant Core has the issue?

core-2021.12.8

**Comment by spacegaier** [comment]
The target is to have the space consistently. In some areas we have already fixed that, but it needs to be added indeed for the input elements.
