### ISSUE TITLE
Can't press <tab> to move past icon picker

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#11146]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When adding a new dropdown helper I am unable to use the <tab> key to move to the option field

![image](https://user-images.githubusercontent.com/1444314/148816644-38992761-8c6d-4183-8825-57d86d054120.png)

It keeps the foucs on the icon picker.

### Describe the behavior you expected

It should move to the next field.

### Steps to reproduce the issue

1. Add helper
2. Pick dropdown
3. Try to tab to option field

### What version of Home Assistant Core has the issue?

all

### In which browser are you experiencing the issue with?

Firefox

### Which operating system are you using to run this browser?

MacOS

**Comment by spacegaier** [comment]
Sounds like a known issue with the `vaadin-combo-box-light` according to this https://github.com/vaadin/web-components/issues/1368.

**Comment by eikowagenknecht** [comment]
Seems to be fixed as far as I can tell?
