### ISSUE TITLE
Notifications tray doesn't close on back button press

### ISSUE THREAD

**Issue by lindhe** [home-assistant/frontend#11141]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The notification tray for persistent notifications do not close if I press the back button on my phone. I can only close it by pressing the little arrow in the top right.

### Describe the behavior you expected

Expected behaviour is for any panel that pops-up or slides out like that to close on a back button press.

### Steps to reproduce the issue

1. Get a persistent notification.
2. Open the notification tray.
3. Press the back button on your phone.

### What version of Home Assistant Core has the issue?

core-2021.12.8

### In which browser are you experiencing the issue with?

Home Assistant Android app version 2022.1.1-full. Also confirmed with Chrome on Android.

### Which operating system are you using to run this browser?

Android 12

### Additional information

Related to https://github.com/home-assistant/android/issues/2129

**Comment by spacegaier** [comment]
@matthiasdebaat

**Comment by matthiasdebaat** [comment]
I've check this with some users and they would love this. Thanks for reporting @lindhe

**Comment by spacegaier** [comment]
And this should then apply to both mobile and desktop?

**Comment by matthiasdebaat** [comment]
Yes, it's kind of dialog. And for dialogs we close it on browser back

**Comment by lindhe** [comment]
Issue still persists.

**Comment by vojtechj** [comment]
and if you close it and open some sensor card and the press the back button on android phone, the notification tray shows up again, which is very annoying.

**Comment by vojtechj** [comment]
What happens if I press the Overview menu in the panel? because after that, the notification drawer doesnt show up anymore when < (back button) pressed.

**Comment by vojtechj** [comment]
@balloob any idea? notification drawer always shows up when pressing back button (<) when previously clicked on Notifications on sidebar ... it's really annoying.

**Comment by lindhe** [comment]
Keep open.

**Comment by lindhe** [comment]
What, is this fixed now?? I tried it just now and the back button does close the notification tray. Which PR did that? 😄
