### ISSUE TITLE
Group of persons is not behaving as espected

### ISSUE THREAD

**Issue by mwthrane** [home-assistant/frontend#11318]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have created a group containing two persons. The persons have a mobile android device with device tracker. 

If one device is away, the group state is away.
Device away:
![S9 away](https://user-images.githubusercontent.com/3908460/149287273-900428a1-4a03-49a9-8221-3d6444826286.png)
Another device home:
![S10 home](https://user-images.githubusercontent.com/3908460/149287814-41939df9-6bf6-43ed-91a3-4ae7cdf43aff.png)
Group goes away:
![residents](https://user-images.githubusercontent.com/3908460/149310338-7895744a-a7aa-4814-87f3-a573ce8252ed.png)

While writing this post, the group went away, with both devices at home:
![away](https://user-images.githubusercontent.com/3908460/149310691-26df6a65-8bbe-4067-ad81-69e6010ad322.png)

```
residents:
  name: Residents
  entities:
    - person.michael
    - person.josefine
```

### Describe the behavior you expected

When either device is home, i espect the group to be home per docs 
https://www.home-assistant.io/integrations/group/

### Steps to reproduce the issue

1. Create a group and add persons with device trackers
2. monitor group and persons
3.
...

### What version of Home Assistant Core has the issue?

core-2021.12.9

### In which browser are you experiencing the issue with?

Firefox 96.0 (64-bit), edge Version 97.0.1072.55 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
entity_id:
  - person.michael
  - person.josefine
order: 0
friendly_name: Residents

editable: false
id: josefine
latitude: removed
longitude: removed
gps_accuracy: 12
source: device_tracker.josefine_s9
user_id: 645c8d75812f4b51b9728a9ba1c730b3
friendly_name: Josefine

editable: false
id: michael
latitude: removed
longitude: removed
gps_accuracy: 13
source: device_tracker.thranes_s10
user_id: c13d333e720c47e9981dea9a946b1dbf
friendly_name: Michael

source_type: gps
latitude: removed
longitude: removed
gps_accuracy: 12
altitude: 105
course: 187
speed: 0
vertical_accuracy: 1
friendly_name: Josefine

source_type: gps
latitude: removed
longitude: removed
gps_accuracy: 13
altitude: 105
course: 0
speed: 0
vertical_accuracy: 1
friendly_name: Thrane
```

**Comment by mwthrane** [comment]
Heres someone with the same issue:
https://community.home-assistant.io/t/group-home-not-home-behaviour/244440

But adding
`All: true`
or
`All: false`

Does not solve it for me.

**Comment by mdegat01** [comment]
I don't think this issue is in the right place, this:

> While writing this post, the group went away, with both devices at home: ![away](https://user-images.githubusercontent.com/3908460/149310691-26df6a65-8bbe-4067-ad81-69e6010ad322.png)

Should never happen with a group. And frontend is just showing the state things are in, the group itself is what's broken.

Can you turn on debug logging for `homeassistant.components.group`? I can't really explain from your config what's going on. I have an almost identical group in my setup and have never seen anything like this.

**Comment by mwthrane** [comment]
I figured it out a few hours ago.
I called my home zone "Home", instead of home. (i used capitol H). This caused the device trackers to be updated with Home instead of home.
I renamed my home zone to "home" instead of "Home".
All good now.

Dont know if this is by design or not.
