### ISSUE TITLE
Add-on Store Repositories stop getting loaded

### ISSUE THREAD

**Issue by richard-scott** [home-assistant/frontend#11328]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since the supervised store was merged into the Configuration menu I have not had reliable usage of the Add-on Store, and I no longer get updates for add-ons already installed. When you look at the list of Managed add-on repos, you do not see ones you have added before (and have installed from before such as the Official Add-ons repo:

![Screenshot 2022-01-14 at 09 47 12](https://user-images.githubusercontent.com/5149834/149495122-1d138864-98f6-41df-ac69-d0c46b68b936.png)

As you can see in this screen shot above, I have things like Mosquitto installed that is no longer available for updates.
To make this worse, when you try and add the repo back in you get told that you can't as its already there:

![Screenshot 2022-01-14 at 09 50 02](https://user-images.githubusercontent.com/5149834/149495338-0ecf2ee9-a588-40a4-903c-438085453300.png)

### Describe the behavior you expected

I'd expect the repos not to change or get removed.

### Steps to reproduce the issue

I don't have any steps to reproduce this other than adding new repos to your setup and waiting.

### What version of Home Assistant Core has the issue?

core-2021.12.9

### What was the last working version of Home Assistant Core?

Maybe core-2021.11.5

### In which browser are you experiencing the issue with?

Chrome, Safari, FireFox

### Which operating system are you using to run this browser?

macOS, Windows 10, Linux, iPhone

**Comment by richard-scott** [comment]
While trying to add back in https://github.com/zigbee2mqtt/hassio-zigbee2mqtt I got this error:

![Screenshot 2022-01-14 at 09 57 53](https://user-images.githubusercontent.com/5149834/149496485-7cac77cd-c363-43b0-b09d-da1d9f8ec498.png)

and when I go out the screen and back in, I see this:

![Screenshot 2022-01-14 at 09 59 45](https://user-images.githubusercontent.com/5149834/149496791-c1991aac-68bf-4898-8a6d-1285fa7121dc.png)

**Comment by ludeeus** [comment]
This has nothing to do with this move (and not related to the frontend).
You will have error logs in your supervisor log.
Please open an issue in the supervisor repo where you fill out the entire issue template in that repo. Thanks 👍

**Comment by richard-scott** [comment]
All I get in the logs is this:
```
2022-01-14 10:23:10 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /supervisor/options - Invalid Add-on repository!
```

But it is a valid repo.

**Comment by ludeeus** [comment]
That is the home assisant log, not the supervisor log, please do as I instructed and open an issue in the supervisor repo 👍
