### ISSUE TITLE
Unable to access minimum light brightness through the UI slider

### ISSUE THREAD

**Issue by jd1900** [home-assistant/frontend#11335]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using the 0-255 values it is possible to access the minimum light brightness (0% brightness in the UI, != 0 value, which means off) for lights in the UI (which corresponds to 1 brightness value). However, using the UI slider the minimum achievable value is 1% (which is equal to 3 absolute brightness), which is not the absolute minimum. 

I attach a few screenshots.

Minimum brightness when set via bound remote of numeric "1" of 0-255 value:
![0-b](https://user-images.githubusercontent.com/63632981/149658351-ddfcc7c5-62a8-4d0e-a0c4-2a6dbd5e6170.png)

Minimum value able to set using the UI slider:
![1-slider](https://user-images.githubusercontent.com/63632981/149658354-1c0952bd-f33a-4c67-ac4c-5be24b143adf.png)

And shown value:
![0-b](https://user-images.githubusercontent.com/63632981/149658363-fab512f7-03ae-4452-9b06-a6b5bf16d9e7.png)

In some of my devices there is a huge difference in brightness between 0% and 1%.

### Describe the behavior you expected

Be able to access the minimum brightness (1, or 0%).

### Steps to reproduce the issue

Open a light. Use the slider to set the minimum brightness. See that it is unable to access the minimum brightness.

### What version of Home Assistant Core has the issue?

core-2021.12.9

### In which browser are you experiencing the issue with?

All, and in the mobile app

### Which operating system are you using to run this browser?

all

**Comment by spacegaier** [comment]
But if we hard-code that the slider value of 1% should be equal to brightness 1, then the jump to 2% (= 5) would be rather big.

So I don't really see a good solution currently. Also I have never come across a device where the brightness level difference between 1 and 3 (out of 255) is noticeable, but then again, I rarely play around with those extremely low values and it probably depends on the device defined curves.

**Comment by jd1900** [comment]
I see a few options.

1.- Add a new step in the UI scroll of value 0 as minimum corresponding to 1 brightness.
2.- The one you said. Despite being a bigger jump, people who uses the minimum brightness are seeking for the darkest. 
3.- Let 1 be 1, 2 be 4, 3 be 7.

**Comment by spacegaier** [comment]
> I see a few options.
> 
> 1.- Add a new step in the UI scroll of value 0 as minimum corresponding to 1 brightness. 2.- The one you said. Despite being a bigger jump, people who uses the minimum brightness are seeking for the darkest. 3.- Let 1 be 1, 2 be 4, 3 be 7.

1. That option is out from my point of view. We excluded 0 by design, to not give the impression to the user that the slider could be used to switch of a light.
2. n/a
3. That somehow feels weird to me if we start to hardcode brightness values, even if only the bottom three (but I would be fine with that). Curios what others think...

**Comment by mdegat01** [comment]
I actually like this idea too. I have an night light automation which sets absolute brightness of a light to `1` and I remember noticing that was just a bit dimmer then what I could get on the slider.

I get why it works the way it does but I think as a user I would expect that if I slide it all the way to the left the light becomes as dim as it could possibly be. The same as how it gets as bright as it could possibly be if I slide it all the way to the right.

**Comment by Karatzie** [comment]
Hi at all,
That is now my first post in GITHUB.

I have the same issue.
I try to use a H801 light controller with 5 channels with 5 seperate white LED stripes.
I have installed ESPurna on the H801 and configured it for 5 seperate channels.
This device has a common brightness and a common command topic for all 5 channels.
I tried different configuration for the 5 channels.
At the end, I configured one device with the common brightness and command topic,
and I configured an own device with the common command topic and a own brightness control for each of the 5 channels.
If I switched off the command topic , all of the 5 channels switched off.
That is not usefull for me.
I want to control each of the 5 channel individually.

I have add an automation for each channel.
`
- id: '1642964787927'
  alias: Name_of_the_automation
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: light.h801_83_ch1
    attribute: brightness
    **above: '0'
    below: '9'**
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: /HOME/H801_83/channel/1/set
      **payload: '0**'
  mode: single
`
This automation set the brightness of ch1 to '0' if the brigthness is set manually in the range of '1' up to '9'.
This automation works and the light is swiched off but the icon color switched to the same color like a 100 % brightness. 

I am very intrested in a solution in Home Assistant for supporting multy channel light controller for 5 or seperatly white LED stripes. You have a control for a RGB, RGBW or RGBWWCW device but not for a WWWWW device
The device should be used for the common command and the common brightness.
Additional should the device offer a slider for each of the 5 or channels. 

I have an additional question is for the brightness slider.
Why is the slider hardcoded for a range of 1...100 %?
My device allows values from 0...255.
If I set the slider to 1%, the device displays me a 3 of 255.
Why is it not possible to use the full range 0...255 instead 1...100%?

**Comment by spacegaier** [comment]
@Karatzie Most of your post seems to be about something completely different (new device types, and such). Please do not mix those points into this specific issue here. It just gets confusing.

> If I set the slider to 1%, the device displays me a 3 of 255.

That is what this issue here is about. Potentially changing that to mean 1 % = 1 brightness.

> Why is it not possible to use the full range 0...255 instead 1...100%?

You can with this one limitation at the lower end discussed in this issue (FYI 100 % = 255).

> For my point of view is the visible difference of the light between brightness 0% and 1% very strong.

Brightness 0 % means the light is off, so of course that might be different compared to 1 % where the light is (barely) on.

**Comment by jd1900** [comment]
It would be great to implement this change and don't forget it.

**Comment by zsarnett** [comment]
I dont think we should start hard coding brightness. You can create a script, scene, or automation for this
