### ISSUE TITLE
Can't login with Samsung Browser

### ISSUE THREAD

**Issue by LivArt01** [home-assistant/frontend#11332]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Starting about a month ago, login with Samsung Internet browser is impossible. Described here: https://community.home-assistant.io/t/samsung-internet-cant-log-in/362295

### Describe the behavior you expected

Succesfully login. 

### Steps to reproduce the issue

1. Grab an Android phone. 
2. Install latest Samsung Internet 
3. Try to log in. 
...

### What version of Home Assistant Core has the issue?

core-2021.12.9

### In which browser are you experiencing the issue with?

Samsung Internet > 16.0.1.57

### Which operating system are you using to run this browser?

Android 11

**Comment by spacegaier** [comment]
I can confirm the issue. An initial quick remote debugging session turned up the following error. But not really sure how to proceed from here.

@zsarnett @balloob Any pointers? The error is inside the HA JS Websocket library.

![image](https://user-images.githubusercontent.com/114137/150135710-d1758d1e-d291-4542-8bfd-d646d3fe5a5f.png)

**Comment by balloob** [comment]
That looks like you're connecting with `ws://` to a host that runs HTTPS on port 8123. It should connect with `wss://`.

What is the URL  you are on, HTTP or HTTPS? Do you use HTTPS?

**Comment by spacegaier** [comment]
> That looks like you're connecting with `ws://` to a host that runs HTTPS on port 8123. It should connect with `wss://`.
> 
> What is the URL you are on, HTTP or HTTPS? Do you use HTTPS?

In the case of my test instance here it is HTTP at 8123. I don't have HTTPS configured.

**Comment by balloob** [comment]
This looks like a bug in Samsung https://forum.developer.samsung.com/t/cannot-make-websocket-connection-without-ssl/18080

**Comment by balloob** [comment]
Created an alert to notify other users https://alerts.home-assistant.io/#samsung_internet.markdown

**Comment by balloob** [comment]
This is fixed.
