### ISSUE TITLE
Picture elements scaling incorrect

### ISSUE THREAD

**Issue by Pelicans-git** [home-assistant/frontend#11342]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Image elements do not scale correctly

### Describe the behavior you expected

When images are overlaid, I would expect then to scale in the same proportion as the card when the card is scaled

### Steps to reproduce the issue

1. Make a Picture-elements card with a background of 300 x 300 pixels.
2. Make a mask image 300 wide and 1 pixel high
3. Position the mask as a image element at, say, 50% from the top and transform scale it to be 100 pixels high.
4. Copy and paste two of these cards into a custom:vertical-stack-in-card card.
5. The scale of the image element changes

Here is an example of an image with three masks:
![image](https://user-images.githubusercontent.com/87899896/149680351-49103873-4ccf-4e47-afbc-db81be483245.png)

Here the two cards are side-by-side in a custom:vertical-stack-in-card
![image](https://user-images.githubusercontent.com/87899896/149680377-3382367e-1824-4356-a6c8-122c99f9a45c.png)

Notice the levels change dramatically.

...

### What version of Home Assistant Core has the issue?

core-2021.12.9

### Which operating system are you using to run this browser?

Win 10

### Problem-relevant frontend configuration

```yaml
A full simplified example is here: https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/2663
Also one post further down at: https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/2665
```

### Additional information

A full simplified example is here: https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/2663

**Comment by Pelicans-git** [comment]
> _No response_

Chrome, Opera, Firefox

**Comment by ildar170975** [comment]
Probably related: https://github.com/home-assistant/frontend/issues/10609

**Comment by ildar170975** [comment]
Problem still exists.

**Comment by ildar170975** [comment]
2022.7.4 - still there

**Comment by ildar170975** [comment]
https://github.com/home-assistant/frontend/issues/10609
https://github.com/home-assistant/frontend/issues/11342
https://github.com/home-assistant/frontend/issues/12404
https://github.com/home-assistant/frontend/issues/12434
There is no need to create issues about the same.
