### ISSUE TITLE
Horizontal Stack not working anymore with the new Update 

### ISSUE THREAD

**Issue by pickonedev** [home-assistant/frontend#11357]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

With the new update, any lovelace dashboard which contains Horizontal Stack card, it will not work anymore

### Describe the behavior you expected

I should see the graphic dashboard

### Steps to reproduce the issue

1. Update to core-2021.12.10
2. Go to a lovelace dashboard which contains Horizontal Stack Card

### What version of Home Assistant Core has the issue?

core-2021.12.10

### What was the last working version of Home Assistant Core?

core-2021.12.9

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

Windows 10 Pro

**Comment by spacegaier** [comment]
Please provide more details ("will not work anymore" is really vague).

What exactly happens? Any errors in your browser console? Please provide a small frontend configuration example that can be sued to reproduce the issue.

**Comment by pickonedev** [comment]
:-( I have rollback to the previews version.

All I remeber is that the error was "Custom element doesn't exist: horizontal-layout"

**Comment by spacegaier** [comment]
Well, there is your answer already 😄. `horizontal-layout` is not a HA frontend component, but a custom one. HA frontend only has `horizontal-stack`.

**Comment by pickonedev** [comment]
Oh... sorry. I thought is the same. Thank you for your time.
