### ISSUE TITLE
iOS app/mobile Safari displays "invalid timestamp"

### ISSUE THREAD

**Issue by gvssr** [home-assistant/frontend#11351]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Timestamp entities with with format yyyy-mm-dd HH:MM:SS displays correctly in HA on a desktop browser, but displays "invalid timestamp" on the iOS apps and mobile safari.

### Describe the behavior you expected

iOS app and mobile Safari should display the same timestamp as on a desktop browser

### Steps to reproduce the issue

1. Add entity with yyyy-mm-dd HH:MM:SS to lovelace glance card
2. Look at the state displayed on mobile

### What version of Home Assistant Core has the issue?

2021.12.09

### In which browser are you experiencing the issue with?

Safari iOS 15.1

### Which operating system are you using to run this browser?

iOS 15.1

### State of relevant entities

```txt
Example entity used:

Entity: sensor.hvc_gft
State: 2022-01-18 00:00:00

Wastecollector: hvc
Hidden: false
Sort_date: 20220118
Days_until: 0
unit_of_measurement: ''
device_class: timestamp
entity_picture: >-
friendly_name: hvc gft
```

### Problem-relevant frontend configuration

```yaml
type: glance
entities:
  - entity: sensor.hvc_gft
    name: GFT
  - entity: sensor.hvc_papier
    name: Paper
  - entity: sensor.hvc_pmd
    name: PMD
state_color: false
```

### Additional information

Proper display on desktop:
![image](https://user-images.githubusercontent.com/61377476/149922780-edc96c95-316a-406f-b89e-10f9e0a15eac.png)

Incorrect display on mobile:
![image](https://user-images.githubusercontent.com/61377476/149923097-de0cb129-c1d4-4b8b-8a64-51fbad0148d4.jpeg)

**Comment by spacegaier** [comment]
Apple strongly enforces ISO 8601 compliant timestamps, meaning the "T" between the data and time need to be there.

See the warning here: https://www.home-assistant.io/docs/configuration/templating/

Where are those entities from? Are they template entities that you created? If yes, you can adjust the timestamp yourself (see link above), otherwise the integration author should take care of that.

**Comment by gvssr** [comment]
@spacegaier Thank you, that completely explains it. It’s an entity from a different integration, so I’ve reported it there. Closing this one.
