### ISSUE TITLE
`Helper` objects have strange history graphs

### ISSUE THREAD

**Issue by mrkeuz** [home-assistant/frontend#11355]
### The problem

Helper object history graphs have displays history graphs that using "approximation" approach. 

- Lines between dots are drawn from point to point. Instead, just "step-by-step" graph as in regular values used. 
- History graphs have "backward loops" on graph

![image](https://user-images.githubusercontent.com/6247921/147520338-75d47f72-5b12-4e33-ad3e-332aee24e81d.png)

![ha_helper_history](https://user-images.githubusercontent.com/6247921/147520921-b038ce4d-68a1-479b-b061-c26d88a27c8c.gif)

Regular history graph:  

![Ha_normal_graph](https://user-images.githubusercontent.com/6247921/147520901-1af404a2-a531-44f8-a621-1461e4446433.png)

### What version of Home Assistant Core has the issue?

core-2021.12.6

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

recorder

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/recorder/

### Example YAML snippet

```yaml
recorder:
  db_url: !secret pg_db_url
```

**Comment by balloob** [comment]
This is because of interpolation. I think it happens when there is no unit of measurement.

**Comment by mrkeuz** [comment]
@balloob, In my setup it has unit of measurements:

![image](https://user-images.githubusercontent.com/6247921/150003580-8c74bb74-f9ce-4f20-a05e-a84f6412c713.png)

**Comment by mrkeuz** [comment]
Fixed at least on 2022.4.5 

Same screenshot 
![image](https://user-images.githubusercontent.com/6247921/163899530-04443f63-7712-49f2-b60d-1b8d107b099d.png)

Will close due resolved. 
Thanks everyone involved! 🚀🚀🚀
