### ISSUE TITLE
Temperature input field deleting value on typing a dot

### ISSUE THREAD

**Issue by eikowagenknecht** [home-assistant/frontend#11379]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In automation, set_climate service on typing in the temperature field, after pressing the "." button, the field is cleared.

I'm using HA in german on a system with german locale, maybe that is related.

![issue](https://user-images.githubusercontent.com/1475672/150538706-91e54202-d5a5-4ce8-80b6-472692cd11da.gif)

### Describe the behavior you expected

Typing "." in the temperature field either correctly adds the symbol, does nothing (if only "," is supported) or converts from "." to ",".

### Steps to reproduce the issue

0 (set ha and system to german)
1. Create automation
2. Select climate.set_temperature service as an action
3. type 12.3 in the input field 
...

### What version of Home Assistant Core has the issue?

core-2021.12.10

### In which browser are you experiencing the issue with?

Chrome latest

### Which operating system are you using to run this browser?

Windows 10 latest

**Comment by spacegaier** [comment]
I cannot reproduce it. No matter what language I select, the behavior does not change (it should not, since I have a specific number format selected in my profile). But that seems not to be taken into account for the number input field (it still enforces dot a decimal separator).

**Comment by eikowagenknecht** [comment]
Interesting, no matther what I choose in my profile the behaviour also stays the same way. But for me it's stuck in the state I described (deleting everything on ".").

Another thing I notices: typing ".1" in the previously empty field autocorrects to "0,1" (dot replaced by comma).

**Comment by eikowagenknecht** [comment]
Still current

**Comment by eikowagenknecht** [comment]
Nothing fixed yet.
