### ISSUE TITLE
Thermostat card does not enforce temperature differential requirement for Nest when in Heat and Cool mode.

### ISSUE THREAD

**Issue by clarinetJWD** [home-assistant/frontend#11395]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Nest Thermostat requires a range of at least 3 degrees F between the "heat" and "cool" points when using the "Heat and Cool" mode. For example, "heat to 70, cool to 73" is valid, while "heat to 71, cool to 73" is not. However, there is not setting or protection for this on the Thermostat card, so by dragging the handles too close together, it generates this error:

`Failed to call service climate/set_temperature. Error from API: 400: INVALID_ARGUMENT: Temperature setpoint range is smaller than minimum 1.666700 in FAHRENHEIT.: Bad Request`

### Describe the behavior you expected

First, either the card should be aware of the supported thermostats' Heat/Cool setpoint ranges or have an option for the user to set one manually.

Now, one of the following two behaviors would be expected:

1. When dragging the handle, it stops allowing movement once it meets the range restriction. This is similar to the current behavior where it stops once it reaches the other handle (difference in value equals 0), it would simply be substituting the new value (3 in Nest's case) instead of zero.
2. The preferred solution would be when the user drags the handle within the restricted range, the card moves the other handle to enforce the rule BEFORE calling the API to set the dragged bound.

Example of #2:

1. Temperature is set to Heat/Cool, Cool point at 70, heat point at 74.
2. User moves Heat point to 71.
3. [No action]
4. User moves the Heat point to 72.
5. [Card detects range violation, and performs the following: 1) Cool point is moved to 75. 2) Heat point is moved to 72. 3) API call to change the Cool point. 4) API call to change the heat point. (3 and 4 may be a single call, I don't know the API)]

This is my preferred solution because it is how the Nest thermostat acts when setting it directly.

### Steps to reproduce the issue

1. Use a temperature card and connect it to a Nest thermostat.
2. Change the mode to Heat/Cool.
3. Move the Heat point or the Cool point within 3 degrees F of the other point.
4. See error message.

### What version of Home Assistant Core has the issue?

core-2021.12.10

### In which browser are you experiencing the issue with?

Edge (Chromium) Version 97.0.1072.62, Android apps

### Which operating system are you using to run this browser?

Windows 10 x64 (10.0.19043)

### Javascript errors shown in your browser console/inspector

```txt
`Failed to call service climate/set_temperature. Error from API: 400: INVALID_ARGUMENT: Temperature setpoint range is smaller than minimum 1.666700 in FAHRENHEIT.: Bad Request`
```

**Comment by javawizard** [comment]
Related to homeassistant/core#47009

**Comment by zsarnett** [comment]
This is a Core issue I believe. The frontend doesn't know the required information here

**Comment by javawizard** [comment]
Yes, this is still an (ongoing and frustrating) issue. Is there a way to reopen this issue?

**Comment by clarinetJWD** [comment]
@zsarnett - Can this be re-opened? It is not solved.

**Comment by javawizard** [comment]
Commenting to prevent this from being closed - this is very much still an issue.

**Comment by javawizard** [comment]
Is there any specific action besides commenting that I should take in order to keep this issue open?

**Comment by allenporter** [comment]
@javawizard My impression is there needs to be a new spec defined for how to represent minimum distance between heat and cool since this is not a concept that exists in core yet.  The specific action is that someone needs to do that work.

I maintain the nest integration so i could be in a good position to do this. However, i personally haven't found this frustrating enough to do the work to make it happen since I have never had a need to use heat cool mode and set the two limits within 3 degrees of each other. (e.g. someone motivated needs to do it)

Also, adding these types of things happen when they benefit multiple integrations. If we are aware of other integrations besides nest that could help clarify that it's more important. Are we aware of other thermostats that could benefit from a minimum heat cool temperature range?

**Comment by allenporter** [comment]
We have two issues open for this and I don't think we should have both. Since we need more information from core to do this, let's just use #69614. Updating both is confusing.
