### ISSUE TITLE
Button card does not support new stateless button component

### ISSUE THREAD

**Issue by msp1974** [home-assistant/frontend#11404]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am not 100% sure if this is a UI issue or a core issue or both.

If an integration uses the new button component but you wish to use the UI button card instead against the button entity, there is no option for press.  The only option is toggle (ie for a switch) and this creates and error of failed to call service. button/turn_off service not found.  Which is correct as a button entity does not support this function.  You can use the call-service option and call the button.press service on the entity but should the UI now have the option for press to support this new component?

### Describe the behavior you expected

Expected an ability to use a button card on a button entity and it call the press service not just the turn_off/turn_on service.

### Steps to reproduce the issue

1.  Add a button card to the UI and select a (as of 2021.12) button entity.
2. Leave the action on toggle and you get the turn_off function not found error
3. No option to select press as the action
...

### What version of Home Assistant Core has the issue?

2021.12.0 onwards

### What was the last working version of Home Assistant Core?

NA

### In which browser are you experiencing the issue with?

Google Chrome Version 97.0.4692.71 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

**Comment by spacegaier** [comment]
I already fixed that a few days ago via https://github.com/home-assistant/frontend/pull/11346.

**Comment by msp1974** [comment]
Super thanks and sorry searched issues but not PRs.

**Comment by spacegaier** [comment]
> Super thanks and sorry searched issues but not PRs.

Well, there also was a raised issue https://github.com/home-assistant/frontend/issues/10975, but doesn't matter now 😉
