### ISSUE TITLE
Backend theme selection not working on desktop browsers.

### ISSUE THREAD

**Issue by Fabrizz** [home-assistant/frontend#11405]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The frontend does not respect the backend-selected theme. This is strange because it behaves correctly on the mobile app _(See video below)_.

Tested on both Edge and Google Chrome and a **even a different computer**, only works on mobile. The theme selected in the profile tab is backend-selected. Also tried with different themes/default theme.

It seems to be stuck on another theme, changing the theme on the profile to a static one and then selecting backend-selected makes no difference.

### Describe the behavior you expected

The theme to change accordingly to what I set using the set_theme service. This is not an issue on the theme/automation/service, it works as expected mobile. 

### Steps to reproduce the issue

1. Select backend_selected as the theme on your profile.
2. Use the dev tools to fire the set_theme service selecting a theme
3. The theme is applied on the mobile web view but not on desktop browsers

### What version of Home Assistant Core has the issue?

core-2021.12.10

### In which browser are you experiencing the issue with?

Google Chrome 97.0.4692.71 | Microsoft Edge 97.0.1072.69

### Which operating system are you using to run this browser?

Windows 11 21H2

### Additional information

(Left is phone mirroring. Cleaning cache, refreshing or using other computer has no effect)

https://user-images.githubusercontent.com/65259076/150655406-63699918-4fe8-46da-9c71-b32ac8096cb7.mp4

**Comment by mrand** [comment]
If you refresh the browser does the correct theme appear?

If so, seems likely duplicate of #10988.

**Comment by Fabrizz** [comment]
> If you refresh the browser does the correct theme appear?
> 
> If so, seems likely duplicate of #10988.

No, refreshing, clearing cache or deleting all page data makes no different. Its strage

**Comment by mrand** [comment]
The other standard question: does it still happen if you remove all custom cards, and card mod, and any custom modification you do on your instance?  If not, then re-add them one-by-one to figure out the cause and then notify the person responsible for that custom item.

**Comment by flixlix** [comment]
I'm having exactly the same issue, it stopped working since the last release

**Comment by Fabrizz** [comment]
> The other standard question: does it still happen if you remove all custom cards, and card mod, and any custom modification you do on your instance?  If not, then re-add them one-by-one to figure out the cause and then notify the person responsible for that custom item.

Sorry for the late response, disabling every custom card does not make any difference. The issue persists, I tried everything, for some reason it does not change the theme on any browser (apart from the mobile webview that works).

**Comment by Olum-hack** [comment]
Hello,
I have the same topic. 
After some playing I found out with the developer tool that the light mode is working. So you can change the theme always with the light mode.
If you select the dark mode, it is not working. So maybe it helps to fine the issue.
Version: core-2022.2.9

**Comment by hmmbob** [comment]
core-2022.3.5 still has this issue

**Comment by Zerwin** [comment]
I wanna add that changing the Dark/Light mode on my OS seemed to change the theme more reliable than changing it via the set_frontend service call. 
Which seems like a bug to me as if I set a specific theme via service call I would expect that to be of higher priority than whatever the client has set. Though maybe that's just me.

**Comment by hmmbob** [comment]
No, that's exactly what this issue is about. As to darkmode on the client, I _always_ have dark mode on in Windows, but I prefer HA in light theme during daytime ;-)

**Comment by brhahlen** [comment]
This still doesn't work in HA 2022.8.5

Just making sure it doesn't go stale

**Comment by f-bor** [comment]
Same issue here (HA 2022.9.7)

**Comment by karwosts** [comment]
I've been poking at this a little bit trying to understand it, just sharing some thoughts. 

First thing to understand is that home assistant core always tracks two themes, a light theme and a dark theme.

Calling set_theme with no mode, or mode:light sets the default light theme. 
Calling set_theme with mode: dark sets the default dark theme.

Calling set_theme with light or dark option selected *does not change* whether your client is in light mode or dark mode. 

Your clients light/dark mode setting comes from the profile page, there is a radio selector for Auto/Light/Dark. Auto means it takes light/dark mode setting from your browser settings or your OS settings. Light or Dark tell HA that you want to be in light or dark mode. 

So once you know what mode you are in (light mode or dark mode), know that you cannot change it with set_theme service. 

If your browser is in dark mode, then calling set_theme with mode: light will do nothing. You must specify mode: dark when you call set_theme if you want to see a change. 

Now that you know you must set mode: dark in the service call, know you can still change the theme to themes that are light mode only. So for example if you set the dark mode theme to a theme that only has light mode, that will make your client render a light mode theme, even though it is still in "dark mode". 

If you have a theme that supports light and dark modes, you can only see the dark_mode variant of the theme. 

If anything is not working, it kind of feels like there is a missing service that would allow you to change this auto/light/dark mode:

![image](https://github.com/home-assistant/frontend/assets/32912880/e383acc0-2864-4660-bc62-9f30804391be)

But without that you must always specify a set_theme mode that matches your client's mode.
