### ISSUE TITLE
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 't.entity.state')

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#11442]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

updated to dev 20220126 earlier today, but because of fundamental issues https://github.com/home-assistant/core/issues/64972 which seems to be solved in https://github.com/home-assistant/core/pull/64973 I downgraded to 0125. the mentioned issue was solved by downgrading, but maybe this has left its traces in the system anyway.

Because, after that downgrade,  when I click on entities of several integrations in the integration panel, eg Z-Wave JS, I get this:

<img width="486" alt="Schermafbeelding 2022-01-26 om 17 19 25" src="https://user-images.githubusercontent.com/33354141/151203325-414be26d-1df2-45ea-87b4-9555624239b5.png">

while when going to that integrations device list and then check its entities, all seems ok.

Its not happening on all integrations, and has nothing to do with core/custom.

also, eg Buienradar has the errors in inspector, but shows the entities nonetheless though a bit weird:

<img width="1629" alt="Schermafbeelding 2022-01-26 om 17 35 06" src="https://user-images.githubusercontent.com/33354141/151205749-42eb3e20-e546-47c2-ae2a-c1c6ae4ccd11.png">

### Describe the behavior you expected

show entities when clicking entities...

### Steps to reproduce the issue

1. integrations panel
2. click entities in z-wave card
3. see none listed
...

### What version of Home Assistant Core has the issue?

2022.2.0.dev20220125

### What was the last working version of Home Assistant Core?

dk

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

MacOS 12.0.1 12.0.1 Monterey 12.0.1 

### Javascript errors shown in your browser console/inspector

```txt
ha-config-entities.ts:174 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'state')
    at Object.template (ha-config-entities.ts:174:1)
    at ha-data-table.ts:427:1
    at Array.map (<anonymous>)
    at renderItem (ha-data-table.ts:397:1)
    at o.dt (lit-virtualizer.ts:18:1)
    at o.update (lit-virtualizer.ts:18:1)
    at o._$AS (styles.ts:366:1)
    at D (styles.ts:366:1)
    at D (styles.ts:366:1)
    at N._$AI (styles.ts:366:1)
```

**Comment by spacegaier** [comment]
Already fixed by https://github.com/home-assistant/frontend/pull/11439.

**Comment by Mariusthvdb** [comment]
Super, I missed that, my apologies. Glad it had nothing to do with the up/downgrade....
Thanks once again!
