### ISSUE TITLE
Trigger ID's are missing in automations for new triggers, but are displayed for existing triggers

### ISSUE THREAD

**Issue by pimw1** [home-assistant/frontend#11448]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Trigger ID's are missing in automations for new triggers, but are displayed for existing triggers. This happens since 2022.02b0.

See the picture below
![image](https://user-images.githubusercontent.com/74881023/151258061-ceee17e7-f88d-4d66-a525-17fad864a1a1.png)
The top trigger is an existing trigger, the bottom trigger is a new trigger.

### Describe the behavior you expected

Trigger id's should be displayed

### Steps to reproduce the issue

1. Go to automations
2. create a new automation
3. add a trigger
4. No trigger id -field is displayed.

### What version of Home Assistant Core has the issue?

core-2022.2.0b0

### What was the last working version of Home Assistant Core?

core-2021.12.10

### In which browser are you experiencing the issue with?

Google Chrome 97.0.4692.99 (64-bit)

### Which operating system are you using to run this browser?

Windows 11

**Comment by balloob** [comment]
That's by design. THey are in the overflow menu.
