### ISSUE TITLE
Done button in Lovelace edit bar has wrong color

### ISSUE THREAD

**Issue by pimw1** [home-assistant/frontend#11446]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In Home Assistant 2022.02b0, the top bar of lovelace is chaning color (from blue to grey) a after pressing the edit button

From blue
![image](https://user-images.githubusercontent.com/74881023/151255525-16131e56-74fe-46fc-8a48-94ef1aedeb75.png)

To grey
![image](https://user-images.githubusercontent.com/74881023/151255604-7bf9b4eb-e6f9-40c8-9e55-6f52639e0f44.png)

As a side-effect, the " done"  button is camouflaged.

### Describe the behavior you expected

The color of the bar should not change while editing
The "Done"  button could be made more obvious/standing out

### Steps to reproduce the issue

1. Look at the current color of the top bar
2. Press edit
3. See the top bar chaning in color
...

I tested this in Google Chrome. In Microsoft Edge, something similar is happening: the orignal color is dark (dark-theme?), but that color also changes to grey after pressing edit.

### What version of Home Assistant Core has the issue?

core-2022.2.0b0

### What was the last working version of Home Assistant Core?

core-2021.12.10

### In which browser are you experiencing the issue with?

Google Chrome 97.0.4692.99 (64-bit)

### Which operating system are you using to run this browser?

Windows 11

**Comment by spacegaier** [comment]
The bar color change is by design (and was always there to signify that you are in edit mode), but the button has the wrong colors.
