### ISSUE TITLE
Graphs not plotting properly when clicking "History" - it goes backwards in time between two points due to rendering(?)

### ISSUE THREAD

**Issue by henrikeri** [home-assistant/frontend#11457]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![image](https://user-images.githubusercontent.com/35510093/151362461-5bfffcbe-43b6-49ba-a69c-6bcd24122655.png)
As can be seen from the attached figure, the line drawn between points is not drawn properly.

### Describe the behavior you expected

With reference to the figure above, when a line is plotted between two points, it should be straight, not bend backwards and forwards indicating there is data present when the fact is that there are not.

### Steps to reproduce the issue

1. Click any value that historical sensor data to observed the skewed plotting. It is visible on all plots, but easier to spot on vertical changes.

### What version of Home Assistant Core has the issue?

2022.2.0b0

### What was the last working version of Home Assistant Core?

2021.12

### In which browser are you experiencing the issue with?

Edge 97.0.1072.69. Also tried latest chrome and firefox

### Which operating system are you using to run this browser?

Windows 10 20H2

### Additional information

The misplotting seems to be evident on browsers and through the Home Assistant iOS app. It is most evident on low density data sets.

**Comment by zsarnett** [comment]
This is due to the graphing library that we are using
