### ISSUE TITLE
overridden Overview (default) still listed as Yaml, while it now is auto-generated

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#11456]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

<img width="1644" alt="Schermafbeelding 2022-01-27 om 12 01 25" src="https://user-images.githubusercontent.com/33354141/151357916-7905ef31-1e96-4522-905a-30edf6ba7495.png">

after selecting

<img width="597" alt="Schermafbeelding 2022-01-27 om 12 21 04" src="https://user-images.githubusercontent.com/33354141/151358041-a94dc366-a994-451c-9a06-ce9e0584cfc2.png">

the default Overview is auto-generated, as we can clearly when landing on it, showing all entities in Lovelace.

### Describe the behavior you expected

have to not show YAML file I the configured column

### Steps to reproduce the issue

1. select another view as default Overview
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.2.0b0

### What was the last working version of Home Assistant Core?

not sure

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

MacOS Monterey 12.0.1

**Comment by bramkragten** [comment]
But you still have your lovelace setup as YAML, so we will try to load that, if it doesnt exist we will auto generate your dashboard
