### ISSUE TITLE
Energy dashboard listed even when energy: is not enabled in configuration

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#11453]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

as title

<img width="1642" alt="Schermafbeelding 2022-01-27 om 13 02 57" src="https://user-images.githubusercontent.com/33354141/151356677-1451a70e-7bf6-4024-8390-2eeb21dcd524.png">

clicking Open, navigates to Overview.

### Describe the behavior you expected

- dont list the dashboard if not configured

### Steps to reproduce the issue

1. check /config/lovelace/dashboards
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.2.0b0

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

MacOS Monterey 12.0.1

**Comment by bramkragten** [comment]
#11458
