### ISSUE TITLE
Climate display only shows one option in dropdown

### ISSUE THREAD

**Issue by erik1988** [home-assistant/frontend#11466]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![image](https://user-images.githubusercontent.com/3375321/151445328-d53a4052-31ce-464a-93e1-b963617d12e6.png)
When selecting the climate view (see screenshot) on my electrical heater (Mill gen3), it only shows one operation, this means that you cannot turn it off. If the heater is off then the dropdown is blank and I am able to turn it to heating again, but I can not turn off the heater. 
Not sure if this is related to the Mill integration https://www.home-assistant.io/integrations/mill/, or something else since this is the only electrical ovn I have in HA.

### Describe the behavior you expected

I expected to be able to turn off the heating, not just turn it on if it is off.

### Steps to reproduce the issue

1. Use a Mill Gen 3 Wifi electrical heater and integrate it with HA
2. Open the UI and try to change the operation.
3.
...

### What version of Home Assistant Core has the issue?

2021.12.10

**Comment by spacegaier** [comment]
Can you please post the entity state from the HA dev tools.

**Comment by erik1988** [comment]
Is this what you need?
![image](https://user-images.githubusercontent.com/3375321/151757033-e12dcf53-fa3c-4ffd-a128-b60061226dd5.png)

**Comment by spacegaier** [comment]
Yes, you can see in your screenshot that the backend only provides a single mode `heat` int `hvac_modes` so the frontend can only show that one in the dropdown list. To verify, you can add some in the HA dev tools, where you took the screenshot and press "Set State" and they will appear in the dropdown.

Real fix has to come from the backend end integration that creates this climate entity.
