### ISSUE TITLE
Markdown card does not render custom URLs correctly

### ISSUE THREAD

**Issue by igrybkov** [home-assistant/frontend#11476]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a markdown card with a link referring to an app on my devices that has a custom Url scheme. Couple of examples of such URLs:
Devonthink: `x-devonthink-item://B9D22E3C-F567-4F3C-8E8D-2424817CC2B2`
OmniFocus: `omnifocus:///inbox`

When I put such link in a markdown card as a valid markdown, it renders with empty href tag.
Example of the markdown:
```markdown
[OmniFocus](omnifocus:///inbox)
```

Rendered html:
```html
<p><a href="">OmniFocus</a></p>
```

### Describe the behavior you expected

I expect it to render as a correct URL such as

```html
<p><a href="omnifocus:///inbox">OmniFocus</a></p>
```

So I'd be able to have links to my own notes in various apps. 

### Steps to reproduce the issue

1. Create a markdown card
2. Put `[OmniFocus](omnifocus:///inbox)` in the card body
3. Save the card
4. Check HTML of the link to validate the result (or just click the link if you have OmniFocus installed)

### What version of Home Assistant Core has the issue?

core-2021.12.10

### In which browser are you experiencing the issue with?

Google Chrome 97.0.4692.99 (Official Build) (x86_64)

### Which operating system are you using to run this browser?

macOS Monterey 12.1

### Problem-relevant frontend configuration

```yaml
type: markdown
content: '[OmniFocus](omnifocus:///inbox)'
title: Test Custom URLs
```

**Comment by igrybkov** [comment]
Hello, I just reproduced the issue on the latest home assistant version. It's still there.

**Comment by thedanbob** [comment]
I just ran into this. It looks like URLs with non-standard schemes are being stripped out by the xss package which is used by HA's [markdown worker](https://github.com/home-assistant/frontend/blob/dev/src/resources/markdown_worker.ts#L5). I believe the fix would be to customize the [safeAttrValue function](https://github.com/leizongmin/js-xss/blob/master/lib/default.js#L171).
