### ISSUE TITLE
Automation Page Won’t Scroll

### ISSUE THREAD

**Issue by fiservedpi** [home-assistant/frontend#11495]
**iOS device model, version and app version**

Model Name: IPhone 12 Pro Max
Software Version: 15.4 beta
App version: 2022.2(2022.345)

**Home Assistant Core Version**

2021.12.10
**Describe the bug**
The automations page won’t scroll to the bottom
**To Reproduce**
1. Open automatons
2. Try to scroll to the bottom

**Expected behavior**
To scroll
**Screenshots**

https://giphy.com/gifs/TSV5nHeUObpDxbvCpU
**Additional context**

**Comment by bramkragten** [comment]
:tada: another iOS version, another bug

**Comment by bradich** [comment]
This also affects Safari Version 15.4 (17613.1.14.1.7) on MacOS Version 12.3 Beta (21E5196i).

**Comment by lukaaars** [comment]
Same here! I'm also not able to scroll through the logbook with Safari on Mac or the iOS App. Chrome works.

**Comment by bramkragten** [comment]
Can anyone check if it also doesn't work here? <https://polymerlabs.github.io/uni-virtualizer/>

**Comment by lukaaars** [comment]
> Can anyone check if it also doesn't work here? https://polymerlabs.github.io/uni-virtualizer/

Scrolling also doesn't work here expect basic example at "scroll directive".

**Comment by ICULikeMac** [comment]
Same on Safari Version 15.4 (17613.1.14.1.7) on MacOS Version 12.3 Beta!

**Comment by chrisron95** [comment]
I have the same problem here, I'm unable to scroll on any of the main list pages, such as entities, automations, etc. anything that has that layout of the whole page list. I'm able to scroll on Lovelace dashboards, developer tools, really anywhere that's not a list (embedded lists are fine, such as picking an entity or a service).

**Comment by bramkragten** [comment]
Logged: https://github.com/PolymerLabs/uni-virtualizer/issues/113

Temp fix: #11623
