### ISSUE TITLE
Energy config link disappeared when I added tibber Grid consumption

### ISSUE THREAD

**Issue by seagri** [home-assistant/frontend#11521]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Energy link on the configuration page is gong
https://YOUR_HOME_ASSISTANT/config/energy

I can access the link when writing it in manually.

Tested multiple browsers so it is not that.

### Describe the behavior you expected

The link should be here
![image](https://user-images.githubusercontent.com/12122654/152315199-1c76d2bb-59c0-47d2-a7fa-dee37b81719d.png)

### Steps to reproduce the issue

1. Add tibber (or maybe something else) on the Grid consumption
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.2.0

### What was the last working version of Home Assistant Core?

Not sure if it was working before as tibber integration added some statistic sensors in 2022.2.0 but I was using 2021.12.10 before

**Comment by bramkragten** [comment]
It is in dashboards now:

![image](https://user-images.githubusercontent.com/5662298/152353434-db7eeeac-6c2f-479a-969d-f17bda65eb42.png)

**Comment by seagri** [comment]
aah, sorry.
