### ISSUE TITLE
2022.02.0 - Doubled diagnostics menu on some devices

### ISSUE THREAD

**Issue by chemelli74** [home-assistant/frontend#11532]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Some devices show diagnostics menu 2 times, some others only 1 as it should be.

### Describe the behavior you expected

Have only 1 link to download diagnostics

### Steps to reproduce the issue

1. Open devices page
2. Inspect all devices
3. 10%-15% has double menu

### What version of Home Assistant Core has the issue?

2022.02.0

### In which browser are you experiencing the issue with?

Microsoft Edge Version 97.0.1072.76 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 21H2

### Additional information

![image](https://user-images.githubusercontent.com/57354320/152409023-d99ae1ac-9551-4837-8f50-4f7c2429aecd.png)

**Comment by bramkragten** [comment]
https://github.com/home-assistant/frontend/pull/11523
