### ISSUE TITLE
2022.2.0 all list are blink, not stay opened. Android Homeassistant app

### ISSUE THREAD

**Issue by shirou93** [home-assistant/frontend#11537]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

All list working like this videos:
![Record_2022-02-03-22-05-42](https://user-images.githubusercontent.com/59237288/152430189-33b7ab2a-3cad-4a3f-99d4-519707bdf8b9.gif)

On chrome on windows 11 all working fine.

### Describe the behavior you expected

Open devices with list and click list to show up.

### Steps to reproduce the issue

1.Open devices with list and click list to show up.

### What version of Home Assistant Core has the issue?

2020.2.0

### What was the last working version of Home Assistant Core?

latest 2019

### Which operating system are you using to run this browser?

Android with Homeassistant app

**Comment by bramkragten** [comment]
This is a duplicate and already fixed in dev.
