### ISSUE TITLE
Energy Configuration missing

### ISSUE THREAD

**Issue by LordShelmchen** [home-assistant/frontend#11541]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The menu entry "Energy Configuration" is missing since the latest update. The only way to find it, is to use the "search" field within the "Configuration" menu.

### Describe the behavior you expected

Add "Ernergy Configuration" under "Configuration"

### Steps to reproduce the issue

1. Click "Configuration"
2. Menu point "Energy Configuration" is missing

### What version of Home Assistant Core has the issue?

core-2022.2.1

### In which browser are you experiencing the issue with?

Microsoft Edge 97.0.1072.76 (Offizielles Build) (64-Bit)

### Which operating system are you using to run this browser?

Windows 11 21H2

### State of relevant entities

```txt
na
```

### Problem-relevant frontend configuration

```yaml
na
```

### Javascript errors shown in your browser console/inspector

```txt
na
```

### Additional information

na

**Comment by spacegaier** [comment]
See https://github.com/home-assistant/frontend/issues/11521#issuecomment-1029000369.
