### ISSUE TITLE
SDIST archive is missing for 20220203.0

### ISSUE THREAD

**Issue by onkelbeh** [home-assistant/frontend#11542]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

SDIST archive is missing on Pypi for 20220203.0, we use this for Redistribution.
We could use the archive from Github, but the pathnames differ.

### Describe the behavior you expected

Would expect a valid archive on https://files.pythonhosted.org/packages/source/h/home-assistant-frontend/home-assistant-frontend-20220203.0.tar.gz

### Steps to reproduce the issue

```
>>> Downloading 'http://distfiles.gentoo.org/distfiles/de/home-assistant-frontend-20220203.0.tar.gz'
--2022-02-04 13:45:25--  http://distfiles.gentoo.org/distfiles/de/home-assistant-frontend-20220203.0.tar.gz
Resolving ampx.in.edevau.net... 172.16.2.4
Connecting to ampx.in.edevau.net|172.16.2.4|:3128... connected.
Proxy request sent, awaiting response... 404 Not Found
2022-02-04 13:45:26 ERROR 404: Not Found.

>>> Downloading 'https://files.pythonhosted.org/packages/source/h/home-assistant-frontend/home-assistant-frontend-20220203.0.tar.gz'
--2022-02-04 13:45:26--  https://files.pythonhosted.org/packages/source/h/home-assistant-frontend/home-assistant-frontend-20220203.0.tar.gz
Resolving ampx.in.edevau.net... 172.16.2.4
Connecting to ampx.in.edevau.net|172.16.2.4|:3128... connected.
Proxy request sent, awaiting response... 404 Not Found
2022-02-04 13:45:27 ERROR 404: Not Found.

!!! Couldn't download 'home-assistant-frontend-20220203.0.tar.gz'. Aborting.
!!! Fetch failed for home-assistant-frontend-20220203.0.tar.gz, can't update Manifest
!!! Unable to generate manifest for '/usr/portage/homeassistant/dev-python/home-assistant-frontend'.
  ebuild.notadded               1
  manifest.bad [fatal]          1
   dev-python/home-assistant-frontend/Manifest
```

### What version of Home Assistant Core has the issue?

core-2022.2.1

<img width="831" alt="grafik" src="https://user-images.githubusercontent.com/42828703/152532753-7ba71a19-81dd-4723-92bb-98b06607775f.png">

### What was the last working version of Home Assistant Core?

core-2022.2.0

<img width="839" alt="grafik" src="https://user-images.githubusercontent.com/42828703/152532810-969b1844-bf9f-4ac8-a6c3-0308b7637a2a.png">

### In which browser are you experiencing the issue with?

all

### Which operating system are you using to run this browser?

all

**Comment by onkelbeh** [comment]
As a workaround, I [use the file from Github](https://github.com/onkelbeh/HomeAssistantRepository/commit/f02c45240d2d21b4ea278b9ef2f64a2e2bde97be) for now, but I would prefer a SDIST, because this way the packagemanager could use Gentoo's mirroring system.

**Comment by bramkragten** [comment]
We ran out of space on pypi, so can not upload both the wheel and the sdist. We choose the wheel.

**Comment by bramkragten** [comment]
CC @cdce8p

**Comment by cdce8p** [comment]
@onkelbeh I recommend the wheel as it's much faster to install for a normal users. I could look into how I can add the built artifacts to the Github release assets. Would that work for you?

**Comment by onkelbeh** [comment]
I can comprehend choosing the wheel in this place, but unfortunately I was using the SDIST for [Home Assistant for Gentoo](https://github.com/onkelbeh/HomeAssistantRepository) for a long time, because Gentoo's packagemanager `portage` has no capabilities to use the wheel.

I tried to change the source to the archive from Github (which I use in roundabout 250 other Ebuilds), where I first ran into the different path names.

I am now recieving tickets that frontend could not be loaded, which is correct:
```
root@g18-hasstest:/usr/lib/python3.9/site-packages # cat /var/log/homeassistant/server.log | grep frontend
2022-02-05 12:28:18 ERROR (MainThread) [homeassistant.setup] Error during setup of component frontend
  File "/usr/lib/python3.9/site-packages/homeassistant/components/frontend/__init__.py", line 339, in async_setup
    root_path = _frontend_root(repo_path)
  File "/usr/lib/python3.9/site-packages/homeassistant/components/frontend/__init__.py", line 314, in _frontend_root
    import hass_frontend
ModuleNotFoundError: No module named 'hass_frontend'
2022-02-05 12:28:19 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of map. Setup failed for dependencies: frontend
2022-02-05 12:28:19 ERROR (MainThread) [homeassistant.setup] Setup failed for map: (DependencyError(...), 'Could not setup dependencies: frontend')
2022-02-05 12:30:58 WARNING (MainThread) [homeassistant.bootstrap] Detected that frontend did not load. Activating safe mode
2022-02-05 12:30:58 ERROR (MainThread) [homeassistant.setup] Error during setup of component frontend
  File "/usr/lib/python3.9/site-packages/homeassistant/components/frontend/__init__.py", line 339, in async_setup
    root_path = _frontend_root(repo_path)
  File "/usr/lib/python3.9/site-packages/homeassistant/components/frontend/__init__.py", line 314, in _frontend_root
    import hass_frontend
ModuleNotFoundError: No module named 'hass_frontend'
2022-02-05 12:30:58 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of safe_mode. Setup failed for dependencies: frontend
2022-02-05 12:30:58 ERROR (MainThread) [homeassistant.setup] Setup failed for safe_mode: (DependencyError(...), 'Could not setup dependencies: frontend')
```

Somehow something in setuptool's build process goes wrong with the source from Github, at first, it seems to compile fine from Githubs source:

```
root@g18-hasstest:/usr/lib/python3.9/site-packages # emerge -1tv home-assistant-frontend

Local copy of remote index is up-to-date and will be used.

These are the packages that would be merged, in reverse order:

Calculating dependencies... done!
[ebuild   R    ] dev-python/home-assistant-frontend-20220203.0::HomeAssistantRepository  USE="test" PYTHON_TARGETS="python3_9 -python3_8 -python3_10" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB

>>> Verifying ebuild manifests
>>> Emerging (1 of 1) dev-python/home-assistant-frontend-20220203.0::HomeAssistantRepository
>>> Installing (1 of 1) dev-python/home-assistant-frontend-20220203.0::HomeAssistantRepository
>>> Jobs: 1 of 1 complete                           Load avg: 0.40, 0.24, 0.49
>>> Auto-cleaning packages...

>>> No outdated packages were found on your system.
```

but somehow then the component's directory is then missing in `site-packages`:
```
root@g18-hasstest:/usr/lib/python3.9/site-packages # l | grep frontend
drwxr-xr-x   2 root root   4096 Feb  5 12:42 home_assistant_frontend-20220203.0-py3.9.egg-info/
root@g18-hasstest:/usr/lib/python3.9/site-packages #
```
when I compile it (exactly the same way) from Pypi's last `SDIST` this is OK:
```
root@g18-hass:/usr/lib/python3.9/site-packages # l | grep frontend
drwxr-xr-x   6 root root   4096 20. Jan 23:19 hass_frontend/
drwxr-xr-x   2 root root   4096 20. Jan 23:19 home_assistant_frontend-20211229.1-py3.9.egg-info/
root@g18-hass:/usr/lib/python3.9/site-packages #
```

During install_phase setuptools is generating an interesting warning:
```
python3.9 setup.py install --skip-build --root=/var/tmp/portage/dev-python/home-assistant-frontend-20220203.0/image/_python3.9
running install
/usr/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running install_egg_info
running egg_info
creating home_assistant_frontend.egg-info
writing home_assistant_frontend.egg-info/PKG-INFO
writing dependency_links to home_assistant_frontend.egg-info/dependency_links.txt
writing top-level names to home_assistant_frontend.egg-info/top_level.txt
writing manifest file 'home_assistant_frontend.egg-info/SOURCES.txt'
listing git files failed - pretending there aren't any
reading manifest file 'home_assistant_frontend.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no directories found matching 'hass_frontend'
warning: no directories found matching 'hass_frontend_es5'
warning: no previously-included files matching '*.py[co]' found under directory '*'
adding license file 'LICENSE.md'
writing manifest file 'home_assistant_frontend.egg-info/SOURCES.txt'
Copying home_assistant_frontend.egg-info to /var/tmp/portage/dev-python/home-assistant-frontend-20220203.0/image/_python3.9/usr/lib/python3.9/site-packages/home_assistant_frontend-20220203.0-py3.9.egg-info
running install_scripts
 * Using python3.9 in global scope
 * python3_9: running distutils-r1_run_phase distutils-r1_python_install_all
>>> Completed installing dev-python/home-assistant-frontend-20220203.0 into /var/tmp/portage/dev-python/home-assistant-frontend-20220203.0/image

 * Final size of build directory: 29352 KiB (28.6 MiB)
 * Final size of installed tree:     24 KiB
```
In fact, the include in `setup.cfg`s `options.packages.find` must be incorrect, because after compile_phase, there is no directory matching the include.

Any ideas?

**Comment by cdce8p** [comment]
The assets you currently see are only the pure source code. I have not implement anything which would upload the `sdist` / `wheel` yet. My question was more along the lines: If I do implement it, would you be able to use the `sdist` from Github release at all?

Regarding your error log, you can't use the source code directly. To be able to build the `sdist`, you would first need to [build the frontend](https://github.com/home-assistant/frontend/blob/20220203.0/script/release#L9-L12) itself. That wouldn't be necessary though, once the `sdist` is added for releases. That would be exactly what would have been uploaded to PyPI.

**Comment by onkelbeh** [comment]
Thanks for that fast response, I have no experience in including yarn builds into a portage Ebuild, this has not been neccesary up to now. Would be glad to find an archive including the files built by node (as the SDIST was).

And sure, no matter where it comes from, I would immediatley try to implement it.

In addition, I have to grump a little that such a fat **breaking change** should have be done in (the month-long) beta phase, having a bunch of users now waiting for the release, currently this change breaks installing homeassistant-2022.2.2 for us (and is also breaking our year-long established release stabilization process).

**Comment by onkelbeh** [comment]
Parallel, I will try to manage the node/yarn part into the Ebuild. This way appears somehow cleaner to me anyway.

**Comment by onkelbeh** [comment]
Seems I have to add net-libs/nodejs as a build dependency for the frontend. Very bad.

**Comment by frenck** [comment]
>  that such a fat breaking change

Let's be really clear on this one.

This is not a breaking change; you are offering an installation method that is not supported by the Home Assistant project. Thus this is not something we take into account when making decisions.

Unless there is a breaking use case in our supported methods, there isn't a direct need for us to address this at all.

**Comment by cdce8p** [comment]
> And sure, no matter where it comes from, I would immediatley try to implement it.

Great! I'll work on it then. Should be able to have it ready later today I think.

**Comment by onkelbeh** [comment]
Thanks @cdce8p, and to @frenck, thats the reason I reduced it to "a little".  Sorry if you get that wrong. There will always be guys who love their own distro's package manager. As I mention on my [README.md](https://github.com/onkelbeh/HomeAssistantRepository/blob/master/README.md), my intention is private use, in no way I want to interfere or set up a competition to your installation methods. And I just share my work, isn't this the spirit of open source? And I believe the resulting repo isn't bad anyway. And I can tell it runs very stable on Gentoo. Some users I know have big installations, my own installation currently reports 'state_count': 1539, 'automation_count': 237, 'integration_count': 96, 'user_count': 12

As far as I know I am not the only one who tries to run core natively on a distribution which is not on your list with success.
I hope you all don't mind.
And thanks for your awesome work.

**Comment by frenck** [comment]
> thats the reason I reduced it to "a little". Sorry if you get that wrong. 

Don't worry about it ❤️ 
I'm just trying to ensure those terms/boundaries are clear.

> or set up a competition to your installation methods.

It is not about competition for us. It's about heaving to carry support. This issue, for example, would not exist if you used our supported method. Yet, we are now all spending time on something we don't support.

These boundaries are set here, to avoid having issues and discussions like these in the first place.

**Comment by onkelbeh** [comment]
As Frank Abagnale Jr. would say, I am d'accord :-)

Looks like I underestimated the volume of 'home-assistant-frontend', my biggest machine spends over 20 minutes compiling from source. Wish I'd know more about building with yarn, currently I am stuck at the forbidden network access in Gentoo's build sandbox. Think I have to explore this matter deeper, we are still lacking Ebuilds for zwavejs2mqtt and zigbee2mqtt.

**Comment by cdce8p** [comment]
I just opened #11566. If merged, the next tagged release will include the build assets. Here an example from my fork: https://github.com/cdce8p/ha-frontend/releases/tag/v0.1.3 (Please ignore the tag version, that was just for testing.)

To download the `sdist`, you might want to look into the Github API docs. Especially this one https://docs.github.com/en/rest/reference/releases#get-a-release-asset

Useful endpoints could be
* [Get a release by tag name](https://docs.github.com/en/rest/reference/releases#get-a-release-by-tag-name)
* [List release assets](https://docs.github.com/en/rest/reference/releases#list-release-assets)
* [Get a release asset](https://docs.github.com/en/rest/reference/releases#get-a-release-asset)

**Comment by onkelbeh** [comment]
Thank you very much. Great work. In the meantime, I've added an [Ebuild](https://github.com/onkelbeh/HomeAssistantRepository/commit/1f22ba3b3d1640ef9a2cb4c3a0711f9b3d7ffc47) building the node stuff in the sandbox (with networking turned on).

**Comment by onkelbeh** [comment]
@cdce8p Marc, gave up on the idea on building during installation, this eats up too much cpu and requires a lot of (otherwise unneeded) stuff, some pinching from your build scripts helped building an [own archive with the neccesary pre-built files](https://hasf.edevau.net/h/home-assistant-frontend/home-assistant-frontend-20220203.0.tar.xz) for [our Ebuild](https://github.com/onkelbeh/HomeAssistantRepository/commit/ce2d37ebe89f0d5e92430da963d0f79193481946). It is 30% smaller than the orginal SDIST, Gentoo's portage allows strong compression. Would be nice if you could take a short look on it, I am not a node/yarn expert. In fact, (except for zwavejs2mqtt and zigbee2mqtt) this is my first yarn build. But it seems to work again, ~50 downloads since yesterday night, and no new tickets. Hope this will stay like that for future releases. And, as a side effect, this file is downloaded during installation, so I'll get an overview of the 'real' usage, greetings from german data privacy law ;-)

BTW, fyi: [your last build](https://github.com/cdce8p/ha-frontend/releases/download/v0.0.15/home-assistant-frontend-20220205.0.tar.gz) cannot be unpacked, seems something went wrong packing the archive.

Thanks again for your work and your time :-)

This ain't an issue anymore, if it's OK for you, please close the ticket.

**Comment by onkelbeh** [comment]
Did not pay any attention on the translations, tried to keep the path names identical to the former SDIST, checked what I could in some running installs, everything looks good, just check a couple of languages, all fine. 

I have sys-apps/yarn-1.22.17 and net-libs/nodejs-14.17.6 on the build machine.
 
This is what finally made the current file:
```bash
#!/bin/bash

# needs internet access, sys-apps/yarn and net-libs/nodejs on build machine

set -e
version="${1}"

# download a clean release and build the node stuff
if true; then
    [ -f "${version}.tar.gz" ] && rm "${version}.tar.gz"
    wget "https://github.com/home-assistant/frontend/archive/refs/tags/${version}.tar.gz"

    [ -d "frontend-${version}" && rm -R "frontend-${version}"
    tar -xvf "${version}.tar.gz"

    cd "frontend-${version}"
    rm -rf dist home_assistant_frontend.egg-info
    yarn install
    ./script/build_frontend
    cd ..
fi

[ -d "home-assistant-frontend-${version}" ] && rm -Rf "home-assistant-frontend-${version}"

# try to do what wheel would do:
cp -av _template "home-assistant-frontend-${version}"
echo "generating home-assistant-frontend-${version}"
for item in hass_frontend README.md MANIFEST.in pyproject.toml setup.cfg setup.py; do
    echo ${item}
    cp -av "frontend-${version}/${item}" home-assistant-frontend-"${version}" > /dev/null
done
echo "packing home-assistant-frontend-${version}.tar.xz"
tar -Jcvf "home-assistant-frontend-${version}.tar.xz" "home-assistant-frontend-${version}" >/dev/null
echo "copy home-assistant-frontend-${version}.tar.xz to webserver"
scp "home-assistant-frontend-${version}.tar.xz" dmzspider:/var/www/hasf.edevau.net/htdocs/h/home-assistant-frontend/
```
The _template directory contains LICENSE.md & PKG-INFO.
If it survives the next release, I'll add some error catchers and include it in the 'big' release script.

**Comment by onkelbeh** [comment]
@cdce8p Since this one here looks stuck to me, we took a closer look at the release script you changed in #11566 today. Thought about putting the build process in a Github action in our repo. One thing we are currently missing are the translations fetched by `script/translations_download`? Is there a way to access them? Can we get an accout at lokalise.co with access to?

**Comment by cdce8p** [comment]
Hi @onkelbeh, yeah sadly I don't think this will go anywhere. Just from a technically point of view, your install method is officially unsupported and thus there isn't any incentive to change anything. Even with my PRs being ready.

If you like to start a boarder discussion, you could open a discussion in https://github.com/home-assistant/architecture. Just be prepared to argue about [ADR0012](https://github.com/home-assistant/architecture/blob/master/adr/0012-define-supported-installation-method.md). An idea could be to suggest uploads of both sdist and wheels to either PyPI, Github, or something else. To be honest though, I'm not sure what the general opinion would be.

Regarding the translation download. You're free to create an Localise account. The issue would be to get download privileges for it as those are not enabled by default. A workaround, although not ideal, would be to use the `translations` from the `wheel`. It might be as simple as copying the `static/translations` folder into `build/translations` (after the `script/build_frontend` run). Then followup with `python3 -m build --sdist` to actually build it.
https://github.com/home-assistant/frontend/blob/cc27ddb3628577b8d0476625c3aa7e276bd665a4/script/translations_download#L12-L16

**Comment by cdce8p** [comment]
@onkelbeh Check out https://github.com/home-assistant/frontend/releases/tag/20220322.0
The release notes from now on include both the sdist and wheel. Hope that helps.
