### ISSUE TITLE
not able to export diagnostics (button is not shown)

### ISSUE THREAD

**Issue by Schrumpelgurke** [home-assistant/frontend#11548]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

With the current version it should be possible to download diagnostics of some integrations (eg. the Z-Wave JS Integration).
I am using the German UI and there is no button to download this. See the images:
![image](https://user-images.githubusercontent.com/36893396/152559464-095fd2bc-4d62-4e7d-a332-12ad109bd3fd.png)
![image](https://user-images.githubusercontent.com/36893396/152559501-065a8213-0282-4141-a36a-507134c2ed3d.png)

Besides this, there is an error that occures quite often - I think, every time it should show the diagnostics button:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:96
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:02:20 (63 occurrences)
Last logged: 16:50:13

[1807944480] Received invalid command: diagnostics/get
[1808028120] Received invalid command: diagnostics/get
[1804490688] Received invalid command: diagnostics/get
[1813271096] Received invalid command: diagnostics/get
```

### Describe the behavior you expected

I should be able to see the new Diagnostics download button, when I click on the three dots of the Z-Wave JS Integration

### Steps to reproduce the issue

1. Go to the Integrations overview
2. Find Z-Wave JS, click on the three dots menu
3. Find the "Download Diagnostics" button.

### What version of Home Assistant Core has the issue?

core-2022.2.0

### In which browser are you experiencing the issue with?

Version 97.0.4692.99 and latest Edge

### Which operating system are you using to run this browser?

Windows 10 Pro 21H2 19044.1466

**Comment by zsarnett** [comment]
I believe this should be resolve in the latest hotfix

**Comment by Schrumpelgurke** [comment]
I updated right now to `core-2022.2.1` without a change. So the issue persists.

**Comment by bramkragten** [comment]
Zwave js has diagnostics in its own panel

**Comment by Schrumpelgurke** [comment]
That was the issue. Thanks!
