### ISSUE TITLE
WLED

### ISSUE THREAD

**Issue by kambiumdt** [home-assistant/frontend#11550]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

when loading WLED addon, i get these error:

Logger: homeassistant.components.wled
Source: components/wled/__init__.py:28
Integration: WLED (documentation, issues)
First occurred: 19:35:26 (1 occurrences)
Last logged: 19:35:26

WLED device 'wled-0a9f70' has a CCT channel, which is not supported by this integration

On previous version of HA it was OK

### Describe the behavior you expected

I have the same addon, without any change from 3months.

### Steps to reproduce the issue

Logger: homeassistant.components.wled
Source: components/wled/__init__.py:28
Integration: WLED (documentation, issues)
First occurred: 19:35:26 (1 occurrences)
Last logged: 19:35:26

WLED device 'wled-0a9f70' has a CCT channel, which is not supported by this integration

### What version of Home Assistant Core has the issue?

2022.2.1

### What was the last working version of Home Assistant Core?

2021.12

### In which browser are you experiencing the issue with?

newest firefox, newest chrome

### Which operating system are you using to run this browser?

WIN10

**Comment by frenck** [comment]
> WLED device 'wled-0a9f70' has a CCT channel, which is not supported by this integration

☝️ The reason is in that description.

We currently do not support WLED devices with CCT channels. This is not a bug.
