### ISSUE TITLE
Energy configuration page missing after upgrade to 2022.2.0

### ISSUE THREAD

**Issue by smithbill17** [home-assistant/frontend#11551]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Sometime after upgrading to Home Assistant v2022.2.0, my Energy dashboard has stopped displaying any new gas/electricity consumption. This looks like it has lost the Cost per kWh.

However, I can't seem to find the configuration page for Energy data to re-enter the costs per kWh - where has it gone?

(I am NOT referring to the side menu Energy dashboard with graphs, it is visible. I can't find the *config* page)

I have "default_config:" in my configuration.yaml and have even tried adding "energy:" too

### Describe the behavior you expected

There used to be a configuration allowing users to enter the cost per kWh for gas and electric - where has it gone?

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.2.1

### What was the last working version of Home Assistant Core?

2021.x.x

### In which browser are you experiencing the issue with?

Chrime

### Which operating system are you using to run this browser?

Android

**Comment by bramkragten** [comment]
Check Breaking changes and search issues first, you are the umpteenth...

**Comment by smithbill17** [comment]
Okay, thank you for the pointer. I've now found it. I had searched issues and found only those relating to the Dashboard itself & "default_config:". I have to say it's a seriously dumb & well hidden place to move the config to - it's no wonder I'm the umpteenth person as it's essentially been 'hidden' and without warning. But thank you for answering my issue.

**Comment by spacegaier** [comment]
The move is clearly noted in the release notes, even as the very first breaking change: https://github.com/home-assistant/frontend/issues/11521#issuecomment-1029000369
