### ISSUE TITLE
Trigger-IDs are gone

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/frontend#11559]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I create a new automation or load an automation which has no trigger ids, the field for trigger ids is not shown.

![Trigger-ID is gone](https://user-images.githubusercontent.com/614929/152641509-d31c1555-1c0c-4b56-aa47-6508211b7390.png)

### Describe the behavior you expected

Trigger ids fields should be visible at all times.

### Steps to reproduce the issue

1. create a new empty automation
2. observe bug

### What version of Home Assistant Core has the issue?

core-2022.2.2

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Chromium: 98.0.4758.87 / Firefox 95.0.2

### Which operating system are you using to run this browser?

Windows 11

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/152641774-a52b1639-f00b-4088-b408-52122cb195bf.png)

<https://www.home-assistant.io/blog/2022/02/02/release-20222/>
