### ISSUE TITLE
Chromium: Dropdown menus doesn't work with the mouse

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/frontend#11561]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.

### Describe the issue you are experiencing

When I want to use a dropdown, like this one in the example, the mouse doesn't seem to work properly. It clicks "behind" the dropdown and either just closes it or select the item behind.

# Example one 

https://user-images.githubusercontent.com/614929/152645965-d5395b5d-2e32-4061-8bf3-f71c3f663034.mp4

# Example two

https://user-images.githubusercontent.com/614929/152646165-1ec14c47-bf4b-4b3c-8474-8293e3be0f35.mp4

### Describe the behavior you expected

normal mouse click behavior 

### Steps to reproduce the issue

1. click on a dropdown menu
2. observe bug

### What version of Home Assistant Core has the issue?

core-2022.2.2

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Chromium: 98.0.4758.87

### Which operating system are you using to run this browser?

Windows 11

**Comment by lezmaka** [comment]
I'm having the same issue when using Microsoft Edge Dev _Version 103.0.1264.2 (Official build) dev (64-bit)_ on Windows 10 Enterprise _Version 21H1 (OS Build 19043.1586)_.  It's not just this build of the dev branch, it's been happening for a while.  

However, when I try the same using the release version of Microsoft Edge _Version 101.0.1210.53 (Official build) (64-bit)_ on the same computer, it works fine.

**Comment by zsarnett** [comment]
Fixed in the current beta release. Its a Chrome Version that broke the dropdowns. Only fixed with an upgrade of HA
