### ISSUE TITLE
Error loading automation page since 2022.2.x with Safari 13.x

### ISSUE THREAD

**Issue by xfader2018** [home-assistant/frontend#11563]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since 2022.2.x the automation page is not available anymore in Safari 13.x
It is not latest Safari but I can't upgrade and I see no reason why this doesn't load anymore.
In Chrome it is still working fine.

Resetting safari, emptying cache didn't help and it always worked fine before.

### Describe the behavior you expected

Just loading page with all my automation

### Steps to reproduce the issue

1. Upgrade to 2022.0
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.2.x

### What was the last working version of Home Assistant Core?

2021.12.x

### In which browser are you experiencing the issue with?

Safari 13.1.2 (High Sierra)

### Which operating system are you using to run this browser?

MacOS 10.13.6 (High Sierra)

**Comment by xfader2018** [comment]
<img width="417" alt="Screen Shot 2022-02-05 at 16 11 33" src="https://user-images.githubusercontent.com/42482961/152648396-24b20c5e-8a08-4434-a6fc-bad5d49f6665.png">

**Comment by bramkragten** [comment]
Check your browser console for errors please

**Comment by xfader2018** [comment]
> Check your browser console for errors please

Error in console is pretty much same as error in HA log

<img width="645" alt="Screen Shot 2022-02-05 at 21 36 44" src="https://user-images.githubusercontent.com/42482961/152658104-e438ab53-be74-4c08-a450-0f9efab65f6d.png">


<img width="674" alt="Screen Shot 2022-02-05 at 21 36 58" src="https://user-images.githubusercontent.com/42482961/152658111-db278155-150c-4227-8410-3a910983ebe5.png">

**Comment by bramkragten** [comment]
Have you tried clearing your cache?

**Comment by xfader2018** [comment]
> Have you tried clearing your cache?

Yes as I checked in the upper checklist and described in my first post. 😉

**Comment by chuyfeng** [comment]
I had exact same issue with Firefox.

**Comment by chuyfeng** [comment]
It seems Chrome works without any problem.

**Comment by xfader2018** [comment]
> It seems Chrome works without any problem.

Also mentioned in my first post. But it makes no sense to rely on Chrome only.

**Comment by xfader2018** [comment]
This is not implemented/released yet, right?
