### ISSUE TITLE
Dropdowns don't expand on touch

### ISSUE THREAD

**Issue by kongo09** [home-assistant/frontend#11567]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I touch on a dropdown in the companion app on Android or in Edge on Android to expand it, it only briefly flashes and then collapses again. It is almost impossible to select an item. Sometimes, however, it drops.

### Describe the behavior you expected

The dropdown should expand so that I can select an option.

### Steps to reproduce the issue

1. Open hass in the Android companion app or Edge browser on Android
2. Click on any dropdown in lovelace
3. Observer
...
https://user-images.githubusercontent.com/640121/152444047-762d8dbd-a44d-49f2-ae87-52c8333789d7.mp4

### What version of Home Assistant Core has the issue?

core-2022.2.2

### What was the last working version of Home Assistant Core?

core-2021.12.1

### In which browser are you experiencing the issue with?

Edge 97.0.1072.78 / Android Sytem WebView 97.0.4692.98

### Which operating system are you using to run this browser?

Android 12

**Comment by kongo09** [comment]
Previously reported here https://github.com/home-assistant/android/issues/2235 but apparently not app related.

**Comment by bramkragten** [comment]
This should have been fixed in 2022.2.1, please try clearing your cache

**Comment by kongo09** [comment]
yes, fixed, thanks
