### ISSUE TITLE
Automations: Deleting an entry won't properly reset the view (yaml or graphical)

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/frontend#11579]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If one element is in yaml view and it is removed, the next item will move up and switch its view to yaml unexpectedly.

https://user-images.githubusercontent.com/614929/152683756-6d74c4b6-774a-478b-b275-9b891028440d.mp4

### Describe the behavior you expected

The deleted element should be removed and other elements shouldn't change it's view.

### Steps to reproduce the issue

1. Add two elements to a automation
2. Select yaml view on the upper one
3. Delete the upper one
4. View of the second one (now the first one) will change to yaml

### What version of Home Assistant Core has the issue?

core-2022.2.2

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Chromium: 98.0.4758.87 / Firefox 95.0.2

### Which operating system are you using to run this browser?

Windows 11

**Comment by RubenKelevra** [comment]
I can confirm this for HA 2022.6.6

**Comment by karwosts** [comment]
I tested and no longer see this behavior. If you still can reproduce this, please leave a comment and I can reopen. 
Closing.
