### ISSUE TITLE
No longer possible to change the device name

### ISSUE THREAD

**Issue by binksjj** [home-assistant/frontend#11581]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When you try to change the name and/or the place of a device, HA freeze.

### Describe the behavior you expected

The name or the place of the device is modified.

### Steps to reproduce the issue

1. Open a device
2. Click on the pencil icon 
3. Change the name and or the place
4. Click on update

### What version of Home Assistant Core has the issue?

Core-2022.2.2

### In which browser are you experiencing the issue with?

HA Companion 2021.12.1

### Which operating system are you using to run this browser?

iOS 15.2.1

**Comment by fjulian79** [comment]
More or less the same here. Right now I'm playing with my own MQTT sensors. Just have got the discovery to work as desired, then I noticed that the place of my sensor is not set. Setting the place does not work (at least in the way described above) but triggers the following log message:

        2022-02-07 00:18:26 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
        Traceback (most recent call last):
          File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
            await func(hass, connection, msg)
          File "/usr/src/homeassistant/homeassistant/components/config/device_registry.py", line 66, in websocket_update_device
            msg["disabled_by"] = DeviceEntryDisabler(msg["disabled_by"])
          File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
            return cls.__new__(cls, value)
          File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
            raise ve_exc
        ValueError: None is not a valid DeviceEntryDisabler
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 29, in _handle_async_response
            connection.async_handle_exception(msg, err)
          File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 143, in async_handle_exception
            self.send_message(messages.error_message(msg["id"], code, err_message))
        KeyError: 'id'

Info on my setup:
## System Health

version | core-2022.2.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.63-v8
arch | aarch64
timezone | Europe/Vienna

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 29.0 GB
disk_used | 4.7 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2022.1.3), Mosquitto broker (6.0.1), Check Home Assistant configuration (3.9.0), File editor (5.3.3), Terminal & SSH (9.3.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

Finally .. Im using Safari on MacOS 12.2

**Comment by emontnemery** [comment]
Fixed by https://github.com/home-assistant/core/pull/65934

**Comment by ludeeus** [comment]
Fixed with https://github.com/home-assistant/core/pull/65934 included in 2022.2.3
