### ISSUE TITLE
No sound in media browser when playing to safari browser

### ISSUE THREAD

**Issue by erkr** [home-assistant/frontend#11580]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I select browser as destination in either the iOS companion app or iOS Safari on my iPhone XR there is no sound. As I also doen't see the title and no play/pause buttons it seems it even didn't accept the selected media
Doing the same on my PC (Chrome/Edge and Firefox) it works (media title and buttons are displayed and there is sound)!

### Describe the behavior you expected

I expect that it will play the selected media.

### Steps to reproduce the issue

1. open media browser in the iOS Companion App of Safari
2. (select web browser as player, seems the default)
3.  select a mp3 file
...

### What version of Home Assistant Core has the issue?

core=2022.2.2

### In which browser are you experiencing the issue with?

iOS Safari

### Which operating system are you using to run this browser?

iOS 15.3

**Comment by engrbm87** [comment]
same here

**Comment by erkr** [comment]
It's fixed in 2022.3
