### ISSUE TITLE
History page doesn’t load

### ISSUE THREAD

**Issue by 01110011011001010111100001111001** [home-assistant/frontend#11608]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

My history page does not load. Specifically, it only loads in Chrome on a desktop PC. Will not load on any other browser on the PC and likewise, won’t load on any browser (including HA app) on iPad Pro.

The data loads. And the charts in the second half of the page load on HA if I scroll down, but the bars do not appear and on hover (on a black screen) I can see the pop ups for each sensor, so this is likely a styling/browser issue. Also, when I reduce screen size to 30% width of screen I can see the coloured bars, but the page is unreadable because titles are truncated.

I have had this issue for months, searched high and low and the existing threads I have seen on the issue (4 years old) do not seem to relate to my issue. My history page is heavy, many sensors, switches and automations. Used to be my fave page on HA.

Everything is up-to-date. Running HA on RPi 4 (8G RAM).

Creating issue since others experience same issue on HA community.

### Describe the behavior you expected

Bars do not appear. Seems browser dependent.

### Steps to reproduce the issue

1. Load history page on HA app, or Safari, or Firefox and Chrome on an iPad Pro. Only seems to work on chrome on desktop pc.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2022.2.3

### What was the last working version of Home Assistant Core?

June 2021

### In which browser are you experiencing the issue with?

All recent

### Which operating system are you using to run this browser?

IPad Pro  OS 15.3

### State of relevant entities

```txt
All
```

### Problem-relevant frontend configuration

```yaml
Source of problem unknown
```

### Javascript errors shown in your browser console/inspector

```txt
None known
```

**Comment by emufan** [comment]
Same here. Never saw a bar chart on any ipad, iphone, ... No bar char is shown, but every hover is working.

Perhaps it is loading, but at least the bar charts are not displayed (correclty).

![image](https://user-images.githubusercontent.com/22775515/152998549-7f5ed9b2-586e-418d-a5aa-ba0b5b8dfa34.png)

If I scoll down to other entity types, which are display in charts, every is displayed correctly and without problems.

![image](https://user-images.githubusercontent.com/22775515/152998512-ed72f424-5501-4a8e-90e3-25a19606fe9c.png)

**Comment by emufan** [comment]
No, unfortunately if was not a solution, but a suggestion for the developers from my side. I have the problem as well and only saw that zacwest assuemes, that this is because of the canvas/picture size and Safari (Mobile) has problems/limitations with this.

So I thought that it shouldn't be that much effort to implement such kind of improvement.
