### ISSUE TITLE
When selecting the initial_option from a template select entity (from ESPHome) in the frontend, the service call is not sent

### ISSUE THREAD

**Issue by bramwalet** [home-assistant/frontend#11607]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Platform: 
Home Assistant 2022.2.3 (supervised)
ESPHome 2022.1.3
Browser: Firefox 96.0.3 (64-bit) and Chrome 97.0.4692.99 (64-bits) on Windows 10

I have an ESPHome device (ESP8266 based) and configured a template select configuration entry as follows:

```
select:
  - platform: template
    name: "DUMMY"
    id: dummy
    options: 
     - Opt1
     - Opt2
     - Opt3 
    set_action: 
      - logger.log:
          format: "set_action DUMMY: Chosen option: %s"
          args: ["x.c_str()"]
```
I have not specified an initial_value so the default value of the select in Home Assistant will be 'Opt1'. 

When I deploy this configuration to my ESPHome device, a new entity select.dummy is configured through the ESPHome integration on Home Assistant, showing 3 available options and the Opt1 is selected by default. This is all expected and correct.

When I change the value of the entity select.dummy to Opt2, the frontend sends a servicecall to the backend. I've checked this by using the Web Developer Tools and inspecting the api/websocket responses. The following data is sent:
```
{"type":"call_service","domain":"select","service":"select_option","target":{"entity_id":"select.dummy"},"service_data":{"option":"Opt2"},"id":25}
```
which is correct. I also validate on the ESPHome side, while inspecting the logs of the ESP8266 device that the selected option is correctly received and logged:
```
[14:01:28][D][select:010]: 'DUMMY' - Setting
[14:01:28][D][select:025]:   Option: Opt2
[14:01:28][D][main:1095]: set_action DUMMY: Chosen option: Opt2
```
Now here's the actual problem: 
When I then change the value of the select.dummy to Opt1 (the default value or initial_value), **NO DATA** is sent through the websocket. The ESP8266 device will not receive it and it will not be logged.

I then checked if the actual service call would work using Developer Tools in Home Assistant. 
When I manually trigger the servicecall with the following configuration: 
```
service: select.select_option
data:
  option: Opt1
target:
  entity_id:
    - select.dummy
```
then the data is sent through Home Assistant to the ESP8266 device and the device is logging the value correctly: 
```
[14:03:31][D][select:010]: 'DUMMY' - Setting
[14:03:31][D][select:025]:   Option: Opt1
[14:03:31][D][main:1095]: set_action DUMMY: Chosen option: Opt1
```
This confirms that Home Assistant correctly sends both options to the ESP8266 device.

No matter what I've tried, Opt1 (the default selected option) will not be sent by the frontend to the HA backend. I also tried using different names but that does not matter. 

It appears that the frontend will not send a servicecall to the backend when the value of the entity is changed to the initial value. 

### Describe the behavior you expected

I would expect the frontend to send the service call to the backend when the default/initial value is selected.

### Steps to reproduce the issue

1. Configure the ESPHome device with the given configuration YAML snippet
2. Add the select.dummy entity to a dashboard or navigate to the ESPHome add-on and to the device.
3. Change the option from Opt1 to Opt2 of entity select.dummy, data **is sent** from frontend to backend and the value is logged on the ESP8266.
4. Change the option from Opt2 to Opt1 of entity select.dummy, data **is not sent** from frontend to backend, no value is logged on the ESP8266.

### What version of Home Assistant Core has the issue?

core-2022.2.3

### In which browser are you experiencing the issue with?

Firefox 96.0.3 (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### Javascript errors shown in your browser console/inspector

```txt
None
```

**Comment by bramwalet** [comment]
Retested in latest HomeAssistant release:
Home Assistant Core 2022.5.3
Home Assistant Supervisor 2022.05.0
Home Assistant OS 7.6
Kernel version 5.10.103-v8

Windows 10, Firefox 99.0.1 (64-bit), issue still persists.

**Comment by bramwalet** [comment]
Still an issue with 
Home Assistant 2022.8.6 
Supervisor 2022.08.3 
Operating System 8.4 
Frontend 20220802.0 - latest 

Win 10, Firefox 102.0.1 (64-bit)

**Comment by pdudits** [comment]
Same problem persists on latest version:

Home Assistant 2023.5.2
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest
ESPHome version 2023.4.4

Win 10, Edge, also a ESP8266 based device.

**Comment by pdudits** [comment]
Turns out it is related to this note in Template select documentation:

> If you don’t set a lambda and optimistic is false (default), updates to the select component state will need to be taken care of as part of your set_action using `id(my_select).publish_state(x);` (in a lambda).

Adding `publish_state` in did fix that for me, though I'm having hard time imagining how :)
