### ISSUE TITLE
Safari on Mac - Can not edit Lovelace cards

### ISSUE THREAD

**Issue by kartcon** [home-assistant/frontend#11614]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After updating to HA 2022.2.3 I noticed that I can not edit a Lovelace Card. After selecting [Edit Dashboard] the frontend changes to the 'editing' theme and the Edit button appears in the left lower corner, BUT when I click on the button nothing happens. I have duplicated this on two browsers and confirmed that it does work on a Chrome browser. All three browsers are running on 3 separate Mac desktop machines. 

### Describe the behavior you expected

I expected that the EDIT button would being me to the UI Lovelace editor.

### Steps to reproduce the issue

1. Navigate to any Lovelace page.
2. Click the 3 eclipses in the top rihjt corner
3. Click Edit Dashboard
4. Scroll down to the Edit button at the lower right and Click on it
5. Nothing happens
6. Scroll back to top of page
7. Click 3 eclipses again
8. Select Raw Configuration Editor > This works.
9. Click X to exit Raw Configuration
10. Click Done to return to Lovelace page.
...

### What version of Home Assistant Core has the issue?

core-2022.2.3

### What was the last working version of Home Assistant Core?

2021.12.x

### In which browser are you experiencing the issue with?

Safari Version 13.1.3 (15609.4.1

### Which operating system are you using to run this browser?

)macOS Catalina version 10.15.7

**Comment by bramkragten** [comment]
Any errors in the browser console?

**Comment by bramkragten** [comment]
OK, I just fixed this one in #11629 :-)

**Comment by kartcon** [comment]
Bram,
Thank you for the quick work! 

Art Davis, Sr FCE
