### ISSUE TITLE
Inconsistent results when attempting to move a card between views

### ISSUE THREAD

**Issue by dm7500** [home-assistant/frontend#11613]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I attempt to move a card to a different view, I get very inconsistent results. For example, If I'm trying to copy a card from one view to another, the duplication will work fine, but the move will do one of the below things:

- Nothing. I will select the new view, and the card will stay in place.
- It will move the card to the Home view, and navigate me there. When this happens, I normally have no problem moving the card to the correct view after.
- It will move the card to the intended view. Recently (since about 2021.12), this has been very rare.

What I've noticed is that if it's going to move the card correctly, it will do it on the first attempt, or throw it to the Home view. Otherwise, it requires a `CTRL+F5` to fully reload the page and get it moving again. Most of the time, this solves the issue, but not always.

[I've included a video sample of the issue to demonstrate](https://youtu.be/VJ9sRS0mG10)

### Describe the behavior you expected

The card should move to the selected view.

### Steps to reproduce the issue

1. Enter `Edit Dashboard` mode
2. Click the ellipses on the card you wish to move
3. Click `Move to View`
4. Select the view you want to move the card to.

From that point, it's a guess as to which result if any I get.
...

### What version of Home Assistant Core has the issue?

2022.2.3

### In which browser are you experiencing the issue with?

Firefox 96 and Brave 1.35 / iOS Companion App

### Which operating system are you using to run this browser?

Windows 10 / iOS

**Comment by ronschaeffer** [comment]
Same issue with Chrome on Android, Chrome on Windows 11 and Edge on Windows 11.

Currently on 2022.2.9 but was happening on earlier 2022.2.x versions. I don't know if it was happening before. 2022.2.x.
