### ISSUE TITLE
Dropdown menus don't open properly

### ISSUE THREAD

**Issue by mat4444** [home-assistant/frontend#11624]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Input_select dropdown menus do not display properly when they are at the bottom of a view. The dropdown always opens downwards, and given the limited space until the bottom of the browser; just a very narrow text space is available to display the options. One needs to scroll to see all the possible options. See the video below that illustrates the issue.

https://user-images.githubusercontent.com/53400792/153241323-d7e5962d-9f89-409f-a98e-900bb98530d9.mp4

### Describe the behavior you expected

The input_select entity should be aware of its position in the browser and in such cases, it should open upward if there is not enough space to display all the options.

### Steps to reproduce the issue

1. set an input_select at the bottom of a lovelace view
2. resize the browser window so there no space between the input_select and the bottom of the windows
3. click the input_select and observe

### What version of Home Assistant Core has the issue?

core-2022.2.5

### What was the last working version of Home Assistant Core?

never

### In which browser are you experiencing the issue with?

Google Chrome 97.0.4692.99 (64-bit)

### Which operating system are you using to run this browser?

Windows 10 20H2

**Comment by bramkragten** [comment]
This element was replaced with a new element in dev.
