### ISSUE TITLE
Default to YAML editing when there are multiple IDs in trigger condition

### ISSUE THREAD

**Issue by sillvva** [home-assistant/frontend#11659]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Currently, when you enter multiple IDs in a trigger condition, it defaults to the visual editor, but does not display any trigger IDs.

### Describe the behavior you expected

It should default to the YAML editor and display a warning that the visual editor is not available for multiple trigger IDs.

### Steps to reproduce the issue

1. Create a trigger condition.
2. Switch to the YAML editor.
3. Add multiple trigger IDs.
4. Save the Automation/Script.
5. Reload the page.
6. Observe that the visual editor is shown with an empty ID field.

### What version of Home Assistant Core has the issue?

core-2022.2.5

### In which browser are you experiencing the issue with?

Microsoft Edge 98.0.1108.43

### Which operating system are you using to run this browser?

Windows 11 (Build 22000.493)

**Comment by frenck** [comment]
Hey @sillvva 👋 

Could you provide an example (via YAML) that we can use to reproduce the issue you are reporting?

../Frenck

**Comment by sillvva** [comment]
It would look something like this
```
  condition: trigger
  id:
    - event_1_trigger
    - event_2_trigger
```
When refreshing the page after saving, it would switch to the visual editor and the id's would not be shown.

I switched to node red since then, so I don't currently have an example.

**Comment by ondras12345** [comment]
Still a problem in 2022.11.1
