### ISSUE TITLE
Generated Lovelace card config seen as invalid

### ISSUE THREAD

**Issue by J3173** [home-assistant/frontend#11668]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The automatically generated Lovelace configuration for an Entities Card with a script (in the footer) and another entity is seen as invalid and cannot be edited (both visually and with YAML) except by the 'Raw configuration editor'.

### Describe the behavior you expected

The automatically generated Lovelace configuration should be considered valid and it should be possible to edit, preview and save the configuration in the Lovelace editor. Or the generated configuration should be changed to be accepted by the validator.

At a minimum, editing the YAML should work. Editing in the visual editor would be nice.

### Steps to reproduce the issue

1. Create a new Lovelace card. In the 'By Entity' tab, select a script and another non-script entity. 
![step1](https://user-images.githubusercontent.com/983821/153706768-0c729e5e-a2a8-4cef-bb34-d468a62896d6.png)
2. Accept the suggestion with the script as a button in the footer.
![step2](https://user-images.githubusercontent.com/983821/153706786-3ced05ab-147e-4ed0-b481-92fbf46b89a9.png)
3. Click on Edit for the newly added card. This will open a YAML editor for the card with the error message:
  > Configuration errors detected:
  > * Required key 'footer.image' is missing.
  > * Required key 'footer.entity' is missing.

![step3](https://user-images.githubusercontent.com/983821/153706921-783eb180-254c-4766-819d-d2165cebc914.png)
  Note that the newly added card was working fine despite these errors.

4. When editing the YAML configuration, loading the preview will fail and the Save button will be disabled.
![step4](https://user-images.githubusercontent.com/983821/153706928-d32c1d96-2e51-4bfe-924e-73377b92e8bc.png)

### What version of Home Assistant Core has the issue?

core-2022.2.6

### In which browser are you experiencing the issue with?

Firefox 96.0 (64-bits)

### Which operating system are you using to run this browser?

Kubuntu 18.04

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - binary_sensor.updater
footer:
  type: buttons
  entities:
    - entity: script.some_script
      show_icon: true
      show_name: true
```

**Comment by xamadevp** [comment]
Still an issue in Home Assistant 2022.3.7

**Comment by bubusworld** [comment]
Seems to be still an issue
