### ISSUE TITLE
Button card doesn't execute button, shows more info

### ISSUE THREAD

**Issue by kds69** [home-assistant/frontend#11699]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

if embedded into entity card, button cards do not trigger buttons as compared to button cards embedded in card footer

### Describe the behavior you expected

When clicked button cards should behave as button pressed.

### Steps to reproduce the issue

1. click on button icon in an entity card
2. instead of triggering button message (button entity) it does show info

### What version of Home Assistant Core has the issue?

core-2022.2.7 (and at least previous core-2022.2.6)

### Additional information

see example of a card with both button entity section and footer with buttons.
Button in footer will behave as expected, button in the body of the card not

    type: entities
    entities:
      - type: buttons
        entities:
          - entity: button.get_schedule
            name: get schedule
            icon: mdi:download
    
    footer:
      type: buttons
      entities:
        - entity: button.get_schedule
          name: get schedule
          icon: mdi:download
    title: Configuration

**Comment by Torok42** [comment]
Still the problem with the beta version : core-2022.3.0b3

**Comment by kds69** [comment]
up

**Comment by Torok42** [comment]
The error is always present
