### ISSUE TITLE
Theme selection field disappears, when selected theme is deleted

### ISSUE THREAD

**Issue by emufan** [home-assistant/frontend#11701]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If you select a theme, e.g. 

![image](https://user-images.githubusercontent.com/22775515/154277284-9fab86b0-4b5e-4d6e-a960-06ac7688d056.png)

and delete this theme and reload themes/restart server, the selection box disappeared and you cannot set a new.

![image](https://user-images.githubusercontent.com/22775515/154277426-e844f723-7139-4bfb-8119-d20546be3b17.png)

### Describe the behavior you expected

Theme selection field should be always there, esp. in this case.

### Steps to reproduce the issue

see above.

### What version of Home Assistant Core has the issue?

core-2022-02-07

### In which browser are you experiencing the issue with?

all

### Which operating system are you using to run this browser?

all

### Javascript errors shown in your browser console/inspector

```txt
e,g,

styles.ts:368 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'modes' in undefined
    at F.value (ha-pick-theme-row.ts:28:1)
    at F.value (ha-pick-theme-row.ts:83:1)
    at F.update (styles.ts:368:1)
    at F.performUpdate (styles.ts:368:1)
    at F.scheduleUpdate (styles.ts:368:1)
    at F._$EC (styles.ts:368:1)

ha-pick-theme-row.ts:28 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'modes' in undefined
    at F.value (ha-pick-theme-row.ts:28:1)
    at F.value (ha-pick-theme-row.ts:83:1)
    at F.update (styles.ts:368:1)
    at F.performUpdate (styles.ts:368:1)
    at F.scheduleUpdate (styles.ts:368:1)
    at F._$EC (styles.ts:368:1)
```

**Comment by av8fs** [comment]
I have this exact same problem

**Comment by andbad** [comment]
I confirm the bug.

By(t)e

**Comment by eximo84** [comment]
Can confirm I have same issue. Recently changed themes and deleted my original one. 

Browser appears fine but companion apps loose the theme selection on the user profile. 

Interestingly to get this back for iOS I added an internal address for my HA server which once saved brought back the theme selector.

No such look on my kindle tablet using the android companion app though.

When I tried to set a theme via calling the service I got an error saying theme cannot be found.

**Comment by ZephireNZ** [comment]
I'm also seeing this on HA 2022.3.1, app version beta-2142-2a2422b6-full

**Comment by ZephireNZ** [comment]
Also seeing it on the web UI too - I just opened it on a PC I previously have opened HA on.

Error in the Console logs:

```
Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'modes' in undefined
    at F.value (ha-pick-theme-row.ts:27:1)
    at F.value (ha-pick-theme-row.ts:77:1)
    at F.update (styles.ts:368:1)
    at F.performUpdate (styles.ts:368:1)
    at F.scheduleUpdate (styles.ts:368:1)
    at F._$EC (styles.ts:368:1)
```

```
styles.ts:368 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'modes' in undefined
    at F.value (ha-pick-theme-row.ts:27:1)
    at F.value (ha-pick-theme-row.ts:77:1)
    at F.update (styles.ts:368:1)
    at F.performUpdate (styles.ts:368:1)
    at F.scheduleUpdate (styles.ts:368:1)
    at F._$EC (styles.ts:368:1)
```

**Comment by bls0n** [comment]
This just happened to me. I fixed it by logging out and then logging back in on each of my devices. Upon logging in, the theme selection box was back. Note that I did restore my theme names before the logout/login, so you may need to try that if the logout/login doesn't work without it.

**Comment by eximo84** [comment]
I reverted back to previous release. Restored my theme from my gitea repo then all was ok. I then switched my theme to backend selected on all devices and upgraded back to latest release and my selection box is always available now.
