### ISSUE TITLE
Log error lovelace default_view:0:0 Uncaught

### ISSUE THREAD

**Issue by thorrrr** [home-assistant/frontend#11713]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After latest update i am getting a constant error in logs 
Logger: frontend.js.latest.202202030
Source: components/system_log/__init__.py:190
First occurred: 08:45:38 (1 occurrences)
Last logged: 08:45:38

http://192.168.23.137:8123/lovelace/default_view:0:0 Uncaught

### Describe the behavior you expected

The above error keeps generating after clearing cache in any browser or after restart

### Steps to reproduce the issue

1.Clear cache 
2.Restart HA
3.
...

### What version of Home Assistant Core has the issue?

core-2022.2.8

### In which browser are you experiencing the issue with?

Edge or Chrome

### Which operating system are you using to run this browser?

Win 10 Pro

### State of relevant entities

```txt
Not known
```

## System Health

version | core-2022.2.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.98
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.22.0
Stage | running
Available Repositories | 977
Downloaded Repositories | 25

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 30.8 GB
disk_used | 16.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Check Home Assistant configuration (3.10.0), SSH & Web Terminal (10.0.2), Home Assistant Google Drive Backup (0.105.2), Studio Code Server (4.1.0), MariaDB (2.4.0), InfluxDB (4.3.0), Grafana (7.4.1), Mosquitto broker (6.0.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 16
views | 75
mode | storage

</details>

**Comment by bobloadmire** [comment]
I have this exact same thing today

**Comment by berner64** [comment]
Same error here, HA 2022.9.0

**Comment by GC1950** [comment]
Same here HA core 2022.9.5 on X86 OS 9.0

**Comment by Gawronnek** [comment]
Same here 
Home Assistant 2022.10.3
Supervisor 2022.10.0
Operating System 9.2

**Comment by Tyrian81** [comment]
Same here , somehow annoying not knowing what it is ....

Home Assistant 2022.12.1
Frontend-versie: 20221208.0 - latest

**Comment by warlordattack** [comment]
Same here :) 

Logger: frontend.js.latest.202212131
Source: components/system_log/__init__.py:256
First occurred: 10:45:12 (6 occurrences)
Last logged: 10:59:50

http:// ... /lovelace/default_view:0:0 Uncaught

**Comment by MnemoBRMC** [comment]
Same error

Logger: frontend.js.latest.202212131
Source: components/system_log/__init__.py:256
First occurred: 20:02:10 (3 occurrences)
Last logged: 20:02:10

https://.../lovelace-hogar/default_view:0:0 Uncaught

**Comment by albanleandri** [comment]
This issue shouldn't be closed, I think. Same error for me:

Logger: frontend.js.latest.202301040
Source: components/system_log/__init__.py:256
First occurred: 13:56:27 (9 occurrences)
Last logged: 21:18:54

http://192.168.1.XX:8123/lovelace/default_view:0:0 Uncaught
https://myexternalurl.com/lovelace/default_view?external_auth=1:0:0 Uncaught
https://myexternalurl.com/lovelace/default_view:0:0 Uncaught

Seems it is happening when I open the default dashboard, and one of the sensors is unavailable. Not quite sure.

**Comment by oywino** [comment]
Same for me:

```
Logger: frontend.js.latest.202301040
Source: components/system_log/__init__.py:256
First occurred: 8:35:59 PM (2 occurrences)
Last logged: 8:35:59 PM

http://192.168.1.8:8123/lovelace/default_view:0:0 Uncaught
```

**Comment by Mika255** [comment]
Same for me.

http://192.168.1.75:8123/dashboard-home/0:0:0 Uncaught

**Comment by tsigalkos** [comment]
same

Logger: frontend.js.latest.202211080
Source: components/system_log/__init__.py:256
First occurred: January 21, 2023 at 23:57:59 (6 occurrences)
Last logged: 00:09:48

http://192.xxx.xxx:8123/lovelace/default_view:0:0 Uncaught

**Comment by oywino** [comment]
Check dashboard resources and delete duplicates.

**Comment by MnemoBRMC** [comment]
I don't know what is the meaning exactly of deleting duplicates.
I can have one entity showed in different shapes in one dashboard, isn't it? Is it a duplicated?

**Comment by oywino** [comment]
Throw in a screen cap.

**Comment by Qruxat** [comment]
Can you tel me where find duplicates?

**Comment by oywino** [comment]
Settings ---> Dashboards ---> click on the 3 dots in the upper right corner and choose ---> Resources.
Then just delete any duplicates from the list.

**Comment by oywino** [comment]
The probably one of those integrations are unavailable, or has been uninstalled or just broken.
