### ISSUE TITLE
History graph not available for unit-less numeric value

### ISSUE THREAD

**Issue by richardwonka** [home-assistant/frontend#11723]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

A vibration sensor reports vibration_strength, which is a unit-less quantifier (similar to the Richter scale’s numbers for earthquakes, which also do not have a unit_of_measurement). 

Default behaviour is that the history graph for this sensor entity shows up as banded colours, which doesn’t make sense. 

### Describe the behavior you expected

A numerical value’s history graph should show an x/y graph value(y) over time(x), regardless of whether it has a unit_of_measurement defined or not. 

### Steps to reproduce the issue

1. Use xiaomi zigbee vibration sensor
2. Look at history graph for the entity
3. 
![AB4C963F-8927-4725-8BE3-BF1D088749CD](https://user-images.githubusercontent.com/304005/154661209-0a28f410-21fe-463c-a19a-c6474a4c5252.jpeg)
![491A78F2-0C4D-4150-B00F-42F4E6EDF953](https://user-images.githubusercontent.com/304005/154661213-ea938a45-8673-4ed2-8b33-d08e5d80f255.jpeg)

### What version of Home Assistant Core has the issue?

core-2022.2.8

### In which browser are you experiencing the issue with?

Safari, chrome, firefox

### Which operating system are you using to run this browser?

iOS 15.3.1, MacOS, Windows 10

### State of relevant entities

```txt
action: null
angle: 5
angle_x: 10
angle_x_absolute: 80
angle_y: 6
angle_y_absolute: 84
angle_z: 78
battery: 100
linkquality: 114
sensitivity: high
strength: 9
vibration: false
voltage: 3045
friendly_name: Tremor strength
```

### Problem-relevant frontend configuration

```yaml
type: history-graph
entities:
  - entity: sensor.tremor_strength
hours_to_show: 24
refresh_interval: 0
```

**Comment by ildar170975** [comment]
Look at the problem from the other side:
1. There is a sensor with values like "good", "bad", "not bad", "awesome" etc - w/o unit_of_measurement.
2. You want a history-graph for this sensor.
3. Should the graph have X,Y axis?

If some sensor returns a numerical value w/o a unit, now you should create a template sensor a specify a unit by yourself.
**Probably the integration should have the units.**

**Comment by emontnemery** [comment]
Your sensor needs to set its `state_class` to "measurement", it will then show up as a line graph instead of discrete values.

**Comment by ildar170975** [comment]
As far as I see now, the `state_class` cannot be set for template sensors.
So, if some template sensor does not have a `unit_of_measurement` then the history-graph will be of "bar" type.
The only solution is to define an empty uom:
```
unit_of_measurement: ''
```

**Comment by richardwonka** [comment]
Hmm. Thank you. An empty uom is a better workaround  than some random uom for something that shouldn’t have one, but I would definitely consider the current behaviour as inconsistent with reality. 

I’ll customize my entity and see how that goes until - hopefully- there is a more consistent solution. 🙂
