### ISSUE TITLE
Error loading the view strategy: TypeError: n[0] is undefined

### ISSUE THREAD

**Issue by heinemml** [home-assistant/frontend#11789]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I was toying with my Tradfri Devices (setting rooms) when suddenly the auto generated Overview stopped working and presented me this screen:

![image](https://user-images.githubusercontent.com/1272630/155298478-3d22d567-5919-4d43-a48d-6b1d98daf47f.png)

This is persistent and happens in the iOS App as well as on a PC with latest Firefox.

The HA Log shows no error message at all.
I tried disabling the Tradfri Integration with no effect.

There is a thread on the community board created in November 21 so this issue seems to come up for people from time to time. Sadly no successful debugging approach was found:

https://community.home-assistant.io/t/cannot-view-overview/354101

### Describe the behavior you expected

Seeing the Overview Dashboard

### Steps to reproduce the issue

I have no clou what triggered this...

### What version of Home Assistant Core has the issue?

core-2022.2.9

**Comment by zsarnett** [comment]
Are you changing the strategy of the view?

Can you paste your YAML LL code?

**Comment by heinemml** [comment]
This is happening in the default "Overview" Board. Is there any way I can see what yaml it generates/uses? 

The only option I have is "Edit Dashboard > Take Control".

**Comment by zsarnett** [comment]
Gotcha. Thanks for the response. No need to get the YAML

**Comment by zsarnett** [comment]
Would you be able to help me with getting a screenshot or copy of your console logs from your browser? Below is a guide on how to get to the console

https://support.monday.com/hc/en-us/articles/360002197259-How-to-Open-the-Developer-Console

**Comment by heinemml** [comment]
Sure!

This is what I get when loading the Page:
```js
TypeError: n[0] is undefined
    s 3a3101c9.js:1
    p 3a3101c9.js:1
    f 3a3101c9.js:1
    f 3a3101c9.js:1
    generateView 3a3101c9.js:1
    o ha-app-layout.js:101
    s ha-app-layout.js:101
    value hui-masonry-view.ts:44
    value hui-masonry-view.ts:44
    performUpdate app.1bcfdc44.js:1248
    scheduleUpdate app.1bcfdc44.js:1248
    _$EC app.1bcfdc44.js:1248
    requestUpdate app.1bcfdc44.js:1248
    o app.1bcfdc44.js:1248
    b app.1bcfdc44.js:1248
    i hui-masonry-view.ts:44
    value 38188e47.js:335
    value 38188e47.js:335
    setTimeout handler*96151/i/< 686c0a6e.js:1
    requestAnimationFrame 5180cdb1.js:1
    requestAnimationFrame 5180cdb1.js:1
    i 686c0a6e.js:1
    value 38188e47.js:335
    _$AE app.1bcfdc44.js:1248
    performUpdate app.1bcfdc44.js:1248
    scheduleUpdate app.1bcfdc44.js:1248
    _$EC app.1bcfdc44.js:1248
    requestUpdate app.1bcfdc44.js:1248
    o app.1bcfdc44.js:1248
    b app.1bcfdc44.js:1248
    w app.1bcfdc44.js:1248
    _ 38188e47.js:58
    p app.1bcfdc44.js:1248
    T app.1bcfdc44.js:1248
    _$AI app.1bcfdc44.js:1248
    S app.1bcfdc44.js:1248
    update app.1bcfdc44.js:1248
    performUpdate app.1bcfdc44.js:1248
    scheduleUpdate app.1bcfdc44.js:1248
    _$EC app.1bcfdc44.js:1248
    requestUpdate app.1bcfdc44.js:1248
    set app.1bcfdc44.js:1248
    value 38188e47.js:58
    value 38188e47.js:58
    value ha-icon-button-arrow-next.ts:8
    value hass-loading-screen.ts:11
ha-app-layout.js:101
```

**Comment by heinemml** [comment]
I just noticed that in the iOS App the error is slightly different:

![image](https://user-images.githubusercontent.com/1272630/155618064-39fadebd-9fad-4426-b2b5-3688fb1eac1f.jpeg)

**Comment by heinemml** [comment]
I found the time to install the dev frontend into my setup and trace the bug.

it goes wrong in `src/common/entity/strip_prefix_from_entity_name.ts`

![image](https://user-images.githubusercontent.com/1272630/156228498-2341882f-f46a-47a7-994c-a84a02658e0a.png)

Notice how "Abstellraum " has a space at the end?

I managed to fix my setup by renaming the Room and loosing the space at the end.

I suppose the code should add a check if the Name is actually longer than `${lowerCasedPrefix}${suffix}`. Or maybe strip the `entityName`. I'm not sure what the naming conventions are here...

**Comment by SidShetye** [comment]
@balloob Can this issue be reopened? It's still present in the latest version of Home Assistant. The code should be more resilient to naming convention of the devices.

**Comment by mschmiedel** [comment]
The same issue happened to me also these days, no idea why. Before I was playing around with some automations and added a new Room with 3 devices. None of the elements seem to have any undefined values that I could think of... 

Here the error: TypeError: undefined is not an object (evaluating 'e[0].toUpperCase')

I tried disabling the automations with no result, the new Room should be no issue, has only 3 devices, they are working properly, were already shown on the default dashboard anyway...

**Comment by metaxis** [comment]
I just had this problem after changing a light group helper location .  "Living room" was the name of both.  After adding the location, I got the above error.  Changing the name of the group to "living room lights" fixed it.  I think it's a bug in the dashboard rendering engine that removes common prefixes, in this case leaving empty string which maybe type promoted awry.

**Comment by ben174** [comment]
This issue absolutely needs to be reopened. It can be triggered when multiple entities have the same name (completely normal in a Hue setup) - or when an entity has a trailing space (less normal, but still absolutely allowed by Hue).

**Comment by balloob** [comment]
If you are experiencing this issue, please open a new issue. Make sure you test on the latest Home Assistant version and include exact steps to reproduce.
