### ISSUE TITLE
Energy Dashboard - incorrect calculations after correcting statistics via database update

### ISSUE THREAD

**Issue by marc4s** [home-assistant/frontend#11811]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I had to correct some statistics in the database due to a bug in pysma and some others due to resetted values of the fritzbox internal kWh measurement.
I fixed the tables
statistics and statistics_short_term

for example like that
`
SELECT * FROM statistics WHERE metadata_id='5' AND created BETWEEN '2022-02-23' AND '2022-02-24' and sum > 1997 ORDER BY start ASC;
| 313535 | 2022-02-23 12:00:12.650761 | 2022-02-23 11:00:00.000000 | NULL | NULL | NULL | NULL       | 695.639 |  605.615 |           5 |
| 313638 | 2022-02-23 13:00:12.674732 | 2022-02-23 12:00:00.000000 | NULL | NULL | NULL | NULL       | 695.912 |  605.888 |           5 |
| 313740 | 2022-02-23 14:00:13.134609 | 2022-02-23 13:00:00.000000 | NULL | NULL | NULL | NULL       | 695.936 | 1997.784 |           5 |
| 313842 | 2022-02-23 15:00:11.008766 | 2022-02-23 14:00:00.000000 | NULL | NULL | NULL | NULL       | 696.026 | 1997.874 |           5 |
SELECT * FROM statistics_short_term WHERE metadata_id='5' AND created BETWEEN '2022-02-23' AND '2022-02-24' and sum > 1997 ORDER BY start ASC;
| 2766823 | 2022-02-23 13:50:12.521401 | 2022-02-23 13:45:00.000000 | NULL | NULL | NULL | NULL       |       0 |            605.912 |           5 |
| 2766925 | 2022-02-23 13:55:12.765407 | 2022-02-23 13:50:00.000000 | NULL | NULL | NULL | NULL       | 695.936 |           1997.784 |           5 |
| 2767027 | 2022-02-23 14:00:12.621084 | 2022-02-23 13:55:00.000000 | NULL | NULL | NULL | NULL       | 695.936 |           1997.784 |           5 |
| 2767129 | 2022-02-23 14:05:12.441496 | 2022-02-23 14:00:00.000000 | NULL | NULL | NULL | NULL       | 695.916 | 1997.7640000000001 |           5 |

update statistics SET sum = sum - 1392.169 WHERE metadata_id='5' AND created BETWEEN '2022-02-23' AND '2022-02-24' and sum > 1997 ORDER BY start ASC;
update statistics_short_term SET sum = sum - 1391.872 WHERE metadata_id='5' AND created BETWEEN '2022-02-23' AND '2022-02-24' and sum > 1997 ORDER BY start ASC;
`
the graphs at all look great now. the cost calculations doesnot seems to get affected.

https://ibb.co/yPKN9C0 
https://ibb.co/z50zZtp
https://ibb.co/5BSNhQv
https://ibb.co/WDdR482

how could this be corrected.
And another question is How can I fix the graphs/information which the energy dashboards got from the table statistics_short_term table because the data are still somewhere but the table itself seems to hold the data for ~14 days

by the way - the calculatuion on the right side "Self-consumption" has to be extended by the more interesting "Autarkie/self-sufficiency"

Degree of self-sufficiency [%] = self-consumed solar power / total power consumption.

The share of self-used solar electricity in the produced solar electricity is the self-consumption quota.
The share of self-used solar electricity in total electricity consumption is called the self-sufficiency ratio.

see the feature request
https://community.home-assistant.io/t/energy-dashboard-add-calculate-self-sufficiency-autarkie-of-the-photovoltaik-system/364535

### Describe the behavior you expected

the calculation must be adjusted if the underlying statistical data change

### Steps to reproduce the issue

1. 
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2022-02-09

### In which browser are you experiencing the issue with?

firefox

### Which operating system are you using to run this browser?

linux

**Comment by bramkragten** [comment]
So you issue is the cost is not correct now? You should correct the statistics for the cost sensors too.

But this is not a frontend issue.

**Comment by marc4s** [comment]
statistics for an cost-sensor - sounds like bullshit for me. 

it should be like that:
database-table:
start date(date x) - Xcost/kwH 
end-date(date x = FAR in Future 2100) - X cost/kwH
and IF the cost has changed from beginning of a specific date the END Date will bne corrected and another new entry will be set.
start-date(date y) - Ycost/kWh
end-date(date y = FAR in Future 2100) - Ycost/kWh
so at all not to much thought about at the moment. but makes more sense then the current setup
