### ISSUE TITLE
Energy dashboard stopped working

### ISSUE THREAD

**Issue by princzkeljanos** [home-assistant/frontend#11829]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Changing energy monitoring time interval have no effect on displayed data.
Day:
![image](https://user-images.githubusercontent.com/6016442/155523692-61ff152a-aa0b-4420-81a5-4d14c7667356.png)
Week:
![image](https://user-images.githubusercontent.com/6016442/155523773-94641547-2785-4e8d-a30b-9394bff728b1.png)

On mobile app it is working correctly.

### Describe the behavior you expected

Show the energy usage for the selected interval.

### Steps to reproduce the issue

1.Select Energy Dashboard
2.Switch View Drom Day to Week (Month, ...)
3.Check displayed data
...

### What version of Home Assistant Core has the issue?

core-2022.3.0b1

### What was the last working version of Home Assistant Core?

core_2022.2.9

### In which browser are you experiencing the issue with?

Google Chrome Version 98.0.4758.102 / Microsoft Edge Version 98.0.1108.56

### Which operating system are you using to run this browser?

Windows 10

**Comment by bramkragten** [comment]
I dont think this is a frontend issue, are statistics generated for you sensor?

**Comment by princzkeljanos** [comment]
This is a default dashboard auto-generated after the Energy configuration in the Configuration section. The Energy counters have a history if it matters.
![image](https://user-images.githubusercontent.com/6016442/155562912-82b84cb0-2c86-4137-bc2a-ca768b5b8881.png)
Please do not close the ticket, as it came up right after Beta Core install.

**Comment by bramkragten** [comment]
That is history, not statistics, check the statistics dev tools for errors

(and this issue should probably more to core)

**Comment by princzkeljanos** [comment]
The statistics are OK. In issue column in every line there is "No Issue."
I have looked for core support and on https://rc.home-assistant.io/blog/2022/02/23/release-20223/ and it seemed this issue fall into frontend category.

**Comment by koying** [comment]
I *think* I have the same.
On b3

Steps:
1) Go to energy dashboard once after refresh: Time selector is inoperative; time changes on the header but not the graphs
2) Go to another dashboard and back to energy: All fine

**Comment by drthanwho** [comment]
I have the same problem here too

Stable Instance
![energy_stable](https://user-images.githubusercontent.com/22405505/155846492-7b268412-0b28-4188-98d5-86cc590ff45b.gif)

Beta Instance
![energy_beta](https://user-images.githubusercontent.com/22405505/155846495-211b24a4-4f30-4ad9-8331-e17db7a2fa7f.gif)
