### ISSUE TITLE
Energy cards in lovelace: link_dashboard: true has no effect, does not link to energy dashboard

### ISSUE THREAD

**Issue by prof7bit** [home-assistant/frontend#11827]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have this in my lovelace:
```yaml
  - type: energy-gas-graph
    entity: sensor.template_gas_kubikmeter
    link_dashboard: true
```
It is showing my hourly gas usage perfectly fine but it does not create a link to the energy dashboard.

### Describe the behavior you expected

I would expect according to the documentation that if I click or tap the graph it would link to the energy dashboard. Or (if the documentation is interpreted differently) it would place some element (href, button) inside the graph that is a clickable link. None of the above is happening. Tested on Firefox and also in the android app.

### Steps to reproduce the issue

1. place an energy-gas-graph card somewhere in lovelace and give it the `link_dashboard: true` property
1a. (if it is of any relevance, I did this inside a vertical stack, did not test outside of this)
2. show the dashboard in the normal (non-editing) view
3. click the energy card - nothing happens.

### What version of Home Assistant Core has the issue?

2022.2.9

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Firefox on PC, Home Assistant App on Android

### Which operating system are you using to run this browser?

Ubuntu, Android

**Comment by bramkragten** [comment]
Only the distribution card supports the link to dashboard option.
