### ISSUE TITLE
2022.3.0b1 browsing media sources has console errors

### ISSUE THREAD

**Issue by apaperclip** [home-assistant/frontend#11849]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using the new dlna server source feature in media I get two errors in the browser console logs.

1. For each click to navigate the hierarchy there is an uncaught error
2. When at the album level there many 404s for album art. (expected I guess for when there is no art, but the browser is asking anyway and for large collections this results in hundreds to thousands of 404s )

### Describe the behavior you expected

No errors

### Steps to reproduce the issue

1. Click media and browse to a dlna server provided source 
2. Navigate through the hierarchy of media (e.g. albums or artists)

### What version of Home Assistant Core has the issue?

2022.3.0b1

### In which browser are you experiencing the issue with?

Version 99.0.4844.35 (Official Build) beta (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
Media Server and Browser playback do not have states that I can see. 

Browsing the radio station feature shows the uncaught errors logs as well.
```

### Problem-relevant frontend configuration

```yaml
No cards, just using the native media feature to navigate a dlna server source or other sources.
```

### Javascript errors shown in your browser console/inspector

```txt
[Violation] Forced reflow while executing JavaScript took 35ms
:8123/media-browser/…%3A%2F%2Fdlna_dms:1 Uncaught (in promise) Error: The message port closed before a response was received.
:8123/media-browser/…%3A%2F%2Fdlna_dms:1 Uncaught (in promise) Error: The message port closed before a response was received.
:8123/media-browser/…compy8%2F%3A0%2F1:1 Uncaught (in promise) Error: The message port closed before a response was received.
:8123/media-browser/…y8%2F%3A0%2F1%2F1:1 Uncaught (in promise) Error: The message port closed before a response was received.
c2e07e1acf4deee75e61ec5183449ac6:1          GET http://192.168.1.3:56923/albumart/c2e07e1acf4deee75e61ec5183449ac6 404 (File Not Found)
:8123/media-browser/…3A0%2F1%2F1%2F870:1 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
342b1f64578b1dcccf9d936e6c944f2c:1          GET http://192.168.1.3:56923/albumart/342b1f64578b1dcccf9d936e6c944f2c 404 (File Not Found)
a7986878a9481c0677f550c8c27039ad:1          GET http://192.168.1.3:56923/albumart/a7986878a9481c0677f550c8c27039ad 404 (File Not Found)
c2e47d96c92b26fadc1c89b9e3e53170:1          GET http://192.168.1.3:56923/albumart/c2e47d96c92b26fadc1c89b9e3e53170 404 (File Not Found)
e04ef7a32fa66e641fb7bc08ddd5555d:1          GET http://192.168.1.3:56923/albumart/e04ef7a32fa66e641fb7bc08ddd5555d 404 (File Not Found)
:8123/media-browser/…3A0%2F1%2F1%2F870:1 Uncaught (in promise) Error: The message port closed before a response was received.
```

**Comment by spacegaier** [comment]
I cannot reproduce any errors in the latest dev version. Does the issue still persists for you in current versions?
