### ISSUE TITLE
the 2 dots in an input_date that only has the time are black instead of white when the theme is dark

### ISSUE THREAD

**Issue by Torok42** [home-assistant/frontend#11859]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The 2 dots in an input_date that only has the time are black instead of white when the theme is dark

![image](https://user-images.githubusercontent.com/58152695/155820851-18fdfc4a-f18d-40c9-a818-98e5400c2ef2.png)

### Describe the behavior you expected

The 2 dots must be white when the theme is dark

### Steps to reproduce the issue

Put an input_datetime which only has time in lovelace

### What version of Home Assistant Core has the issue?

core-2022.3.0b3

### In which browser are you experiencing the issue with?

Google Chrome Version 98.0.4758.102

**Comment by GigaTech** [comment]
There have been a lot of CSS changes/additions, so themes are breaking. which is fine, things need to be updated

but there is no (I cannot find) official source for CSS values or even documentation of the 'paper' elements being removed and getting replaced with... just hours of searching through random threads piecing info together

<img width="676" alt="image" src="https://user-images.githubusercontent.com/3658357/156673304-66546d52-c887-4688-afdb-3d598e420bd8.png">

Thanks

**Comment by spacegaier** [comment]
Was already solved via https://github.com/home-assistant/frontend/pull/11907
