### ISSUE TITLE
Automation and Script Error "Translation Error: The intl string context variable "type" was not provided to the string"

### ISSUE THREAD

**Issue by zer010gic** [home-assistant/frontend#11868]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am seeing an error when clicking on adding an "Automation" or "Script" on any device.
<img width="599" alt="Screen Shot 2022-02-26 at 12 34 23 PM" src="https://user-images.githubusercontent.com/73259984/155865433-d2c0a8ac-dd38-4c74-9412-a2a482105445.png">
<img width="605" alt="Screen Shot 2022-02-26 at 12 34 04 PM" src="https://user-images.githubusercontent.com/73259984/155865434-20051aeb-a5f8-4f1d-96f2-8e7eff75b03a.png">

### Describe the behavior you expected

No error in top of dialog box.

### Steps to reproduce the issue

1. Go to any device
2. Click to add script or animation 
3.
...

### What version of Home Assistant Core has the issue?

2022.2.9

### In which browser are you experiencing the issue with?

Firefox 95.0.2 (64-bit) and Chrome 98.0.4758.109

### Which operating system are you using to run this browser?

MacOS 12.1

**Comment by bramkragten** [comment]
Oh, yeah, I know why this is happening, will be fixed in the next release.

**Comment by revelephone** [comment]
I Also find the same error when try to add new script.
is the script still working, if I add new script ?

![image](https://user-images.githubusercontent.com/100608808/156138803-846a4d50-a57a-4181-bffe-a782cf72ffdc.png)
