### ISSUE TITLE
input_text and input_datetime alignment

### ISSUE THREAD

**Issue by Torok42** [home-assistant/frontend#11860]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

For the following items:
input_text
input_datetime with date only
input_datetime with date and time

The alignment is on the left while for the other elements the alignment is on the right

![image](https://user-images.githubusercontent.com/58152695/155821517-26d82cbf-c057-4088-925d-9eb1e00fd087.png)

### Describe the behavior you expected

For the following elements the alignment must be on the right:
input_text
input_datetime with date only
input_datetime with date and time

### Steps to reproduce the issue

Add in lovelace the following :
input_text
input_datetime with date only
input_datetime with date and time

### What version of Home Assistant Core has the issue?

core-2022.3.0b3

### In which browser are you experiencing the issue with?

Google Chrome Version 98.0.4758.102

### Which operating system are you using to run this browser?

Windows 10

**Comment by Torok42** [comment]
The error is always present

**Comment by GigaTech** [comment]
Still the same issue, things just done align.

This is displaying last activity/data, it does not need to allow input

Home Assistant 2022.8.6
Supervisor 2022.08.3
Operating System 8.5
Frontend 20220802.0 - latest

![image](https://user-images.githubusercontent.com/3658357/186390191-cb727763-747b-4a6d-8d40-c59a661e7ea0.png)
