### ISSUE TITLE
Automations: Entities can be selected multiple times

### ISSUE THREAD

**Issue by eikowagenknecht** [home-assistant/frontend#11879]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Entities can be selected multiple times in the "selection widget", but removing one copy then removes *all* entries.

![issue](https://user-images.githubusercontent.com/1475672/155941256-62cef819-64ef-4269-b5cc-0618e7ed2c65.gif)

### Describe the behavior you expected

Entities can either not be selected twice (what would that do?) or only one copy would be removed on removal.

### Steps to reproduce the issue

1. Select entity
2. Select entity again
3. Remove entity

### What version of Home Assistant Core has the issue?

core-2022.3.0b4

### In which browser are you experiencing the issue with?

Google Chrome, latest stable

### Which operating system are you using to run this browser?

Windows 10

**Comment by eikowagenknecht** [comment]
Still current

**Comment by eikowagenknecht** [comment]
Still current

**Comment by karwosts** [comment]
This looks related to my fix here:

https://github.com/home-assistant/frontend/pull/14882

I made this fix, but only for the history graph picker, but it could easily be applied here to the automation editor as well. I will do so if/when the first PR gets approved.

**Comment by eikowagenknecht** [comment]
As far as I can see the PR still only fixes this for the history picker, not for the automation editor. Is this really included there @bramkragten ?

**Comment by karwosts** [comment]
Yes this fixes for the automation editor as well. I was asked in code review to apply it globally to all ha-target-pickers.

**Comment by eikowagenknecht** [comment]
Nice, thanks for the clarification!
