### ISSUE TITLE
Energy dashboard displays duplicated energy consumption with battery storage

### ISSUE THREAD

**Issue by vantech14** [home-assistant/frontend#11886]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi,

I am using the energy dashboard, and have a grid feed sensor and a battery storage system with charge and discharge sensors. These report correctly into the energy dashboard.

There does appear to be however an issue with the way in which data is reported.

If I charge the battery to its 11kW capacity from the grid, the grid shows 11kW, and so does “Home”. When the battery discharges, it then increases the amount of consumption used by the “Home”. This then means that “Home” displays the energy used to charge the batteries and the energy discharged thereafter. 

In essence, “Home” reports the total amount of power used to charge the battery, and also reports the discharging of the battery as additional consumption, whereas actually if the battery is charged from the grid, it should not display this under “Home” until the battery discharges.

Image below also shows additional power used by the home in addition to that taken from the battery. Approx. 3.9kW.

![73992FA9-5DB6-4949-8B00-B70A29639052](https://user-images.githubusercontent.com/76781626/156060194-a47c84e5-3135-45ff-8ee8-7a9200adbe04.jpeg)

### Describe the behavior you expected

Charging from grid to battery = increased consumption under GRID and with house showing zero.

Discharging from battery into house = increased consumption under HOUSE 

### Steps to reproduce the issue

1. Add battery storage and charge from grid 
2. Watch house increase in usage as battery charges 
3. Watch house increase again as battery discharges 

### What version of Home Assistant Core has the issue?

	core-2022.2.9

### In which browser are you experiencing the issue with?

All browsers

### Which operating system are you using to run this browser?

All platforms

**Comment by jensuffhaus** [comment]
This is definitely still an issue as the dashboard does not understand that some of the grid usage went to the battery and not to the home ... the grey color of the line seems to show this ... it is a problem for pure grid/battery storage systems which are very common.

![image](https://user-images.githubusercontent.com/1774160/219936690-fbba1305-5e26-4bb9-9efa-e1e7e681090d.png)

Grid: 3.1 is correct
Battery: 1.2 IN / 0.8 OUT is correct
Home 3.9 is wrong

- Home should be: Grid 3.1 - Battery 1.2 IN + Battery 0.8 OUT = 2.7
- The grey line from grid to battery should be "Pink" in color.

**Comment by vantech14** [comment]
@jensuffhaus I have since added solar and the issue disappears so indeed it is specific to installs that have battery storage and no solar. As you say, an increasingly common setup.

**Comment by jensuffhaus** [comment]
@vantech14  Just sad that this and your other issue are "closed" and seemingly not going to be looked at. It clearly is a bug that "charging from grid" is not correctly accounted for ... is it accounted for on your install now when solar is "not enough" and you charge from grid?

Are you able to re-open this issue so it gets back on the radar? I tried to look in the code but have no idea where to start as there are several repo's and I have no understanding of HA code base structure.

**Comment by devinmitchell** [comment]
Still an issue

**Comment by Mik145** [comment]
Same problem. The line from the mains to the battery is always gray. The total amount of energy at home is not correct.
