### ISSUE TITLE
Rendering of debug flow on Mac app / Safari browser out of whack

### ISSUE THREAD

**Issue by felix63** [home-assistant/frontend#11896]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When rendering a debug flow of an automation in de native app or in safari more complex flows are not rendered correctly. In Chrome the same flow is shown correctly.

### Describe the behavior you expected

straight lines!

### Steps to reproduce the issue

not all debug flows have this issue.

### What version of Home Assistant Core has the issue?

2202.2.9

### What was the last working version of Home Assistant Core?

n.a.

### In which browser are you experiencing the issue with?

Safari and Home Assistant Companion 2022.345

### Which operating system are you using to run this browser?

Mac OS 12.1

### State of relevant entities

```txt
n.a.
```

### Problem-relevant frontend configuration

```yaml
n.a.
```

### Javascript errors shown in your browser console/inspector

```txt
n.a.
```

### Additional information

IN Safari:
<img width="609" alt="Schermafbeelding 2022-03-01 om 20 17 10" src="https://user-images.githubusercontent.com/16501940/156235515-dabec887-ec5c-43d0-9f30-f7f465effba3.png">

In Chrome
<img width="480" alt="image" src="https://user-images.githubusercontent.com/16501940/156235346-dce38e01-0348-42d5-b0ff-34a049186d76.png">

**Comment by felix63** [comment]
Problem is still there on latest version 2022.5

**Comment by felix63** [comment]
Problem still exists on 2022.8 both on Mac OSX and iPad OS

**Comment by sensei73** [comment]
Stil present on 2022.12.6!
