### ISSUE TITLE
12pm showing as 0pm - 12hr time showing incorrectly for 12pm, showing as 0pm

### ISSUE THREAD

**Issue by Arikshten** [home-assistant/frontend#11891]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am seeing in multiple places the time being displayed as 0pm when it should be 12pm. I use the 12hour clock and there is no such time as 0pm but it keeps showing up for any time that is during the 12pm hour. 
I see this displayed in the history for each entity and also in the last activation of any automation (that happened during that time frame). 

I noticed this a few weeks back 

### Describe the behavior you expected

I expect this to show as 12pm   not 0pm

### Steps to reproduce the issue

View any device history or automation history for something that ran in the hour after mid day.

### What version of Home Assistant Core has the issue?

Latest

### In which browser are you experiencing the issue with?

Crome

### Which operating system are you using to run this browser?

Mac

### Additional information

Not sure what more details you need.
I can replicate/see this on multiple devices and browsers as well as in the mobile app. 

It does seem to be just a display error and not impacting any function as far as I know.

**Comment by KX-T308** [comment]
I'm also seeing the same issue.

If you set a start time frame in History as 12:00pm, it shows up as 0:00 pm.

System running latest version.

**Comment by sym0nd0** [comment]
I've the same issue, it's been like this for a few versions now.

![image](https://user-images.githubusercontent.com/55590428/167138963-380c88ab-981c-4a94-bcda-46b58d42334f.png)

![image](https://user-images.githubusercontent.com/55590428/167139035-6b1b2a9d-d871-4b14-a624-ccf5582152ee.png)

Also affecting the Android companion app.

Running all the latest versions, at time of writing.

**Comment by KX-T308** [comment]
Just updated to 2022.6.0 and issue is still there

![image](https://user-images.githubusercontent.com/15967610/171502866-295fa205-104d-48db-84d7-8ecf5a97d2d5.png)

**Comment by tidusjar** [comment]
Still an issue in 2022.08.3

**Comment by KX-T308** [comment]
Still an issue in 2022.9.7

**Comment by sym0nd0** [comment]
https://community.home-assistant.io/t/wth-ha-energy-graph-should-be-12-00pm-not-00-00pm-for-midday/479342?u=sym0nd0

**Comment by ChristophCaina** [comment]
hm... still an issue in 2022.12 ...
Unfortunately, still ignored by the dev team ... :-(
(👎 )

**Comment by markkeny** [comment]
Yes, also just come across this.

**Comment by bramkragten** [comment]
https://github.com/home-assistant/frontend/pull/16805
