### ISSUE TITLE
Dashboard selector not showing currently selected non-default dashboard

### ISSUE THREAD

**Issue by gadgetchnnel** [home-assistant/frontend#11897]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Dashboard selector in the profile page is allowing selection of a default dashboard but, after refreshing or returning to the page, the dropdown is empy making it impossible to tell which dashboard is selected.

### Describe the behavior you expected

The Dashboard selector should show the currently selected dashboard for any dashboard.

### Steps to reproduce the issue

1. Go to the Profile page
2. Select a dashboard other than Overview (default)
3. Reload the page or navigate to another page and back to Profile
...

### What version of Home Assistant Core has the issue?

core-2022.3.0b5

### In which browser are you experiencing the issue with?

Google Chrome 98.0.4758.109

### Which operating system are you using to run this browser?

macOS Catalina 10.15.7

### Additional information

Dropdown with default dashboard

<img width="599" alt="image" src="https://user-images.githubusercontent.com/2099542/156243820-ba0a7892-c47d-48b0-b85a-e242264eef4b.png">

Dropdown immediately after selecting other dashboatd
<img width="601" alt="image" src="https://user-images.githubusercontent.com/2099542/156243410-e361a047-efc6-4962-8ea9-f96711353940.png">

Dropdown after refreshing or returning to page

<img width="606" alt="image" src="https://user-images.githubusercontent.com/2099542/156243525-58c970b9-c528-4383-a29b-09c8a9913b3f.png">

**Comment by gadgetchnnel** [comment]
This is still an issue as of HA 2022.6.0b1

**Comment by karwosts** [comment]
This bug appears to be fixed in my testing, and nearly a year stale. Closing.
