### ISSUE TITLE
Area Card gives error when click buttons

### ISSUE THREAD

**Issue by Photogad** [home-assistant/frontend#11903]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I try to click the light/switch buttons on the area card, they give an error message:

`**Failed to call service light/turn_on. must contain at least one of entity_id, device_id, area_id.**`

`Failed to call service switch/turn_on. must contain at least one of entity_id, device_id, area_id.`

`Failed to call service fan/turn_on. must contain at least one of entity_id, device_id, area_id.`

### Describe the behavior you expected

To toggle the lights/switches.

### Steps to reproduce the issue

1. Add area card to Lovelace UI
2. Click buttons on area card
3. wait for error message
...

### What version of Home Assistant Core has the issue?

2022.3.0b6

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

All

### State of relevant entities

```txt
they work when controlled individually but not with this card
```

**Comment by daften** [comment]
I have the same problem.

**Comment by kine90** [comment]
Same problem here, the buttons stopped working few days ago.

**Comment by daften** [comment]
Unfortunately, this issue is still present for me, I still see this message when I click a button or the card:
```
Failed to call service light/turn_on. must contain at least one of entity_id, device_id, area_id.
```

**Comment by RayLation** [comment]
Have had the exact same problem for a while.
