### ISSUE TITLE
Darkmode bug with Version: 2022.3.0

### ISSUE THREAD

**Issue by python4lyfe** [home-assistant/frontend#11918]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I updated my Home Assistant to the latest version this morning and went into the Automations to check out the new changes. I noticed that the input fields are no longer in darkmode (see below).

![image](https://user-images.githubusercontent.com/56479548/156571863-e29afb50-d8a6-49db-bffa-f661a2a022bf.png)

### Describe the behavior you expected

Darkmode for the input fields

### Steps to reproduce the issue

1. Change to Darkmode
2. Upgrade to the latest HA version
3. Navigate to Automations and either create/edit an automation
...

### What version of Home Assistant Core has the issue?

2022.3.0

### What was the last working version of Home Assistant Core?

2022.2.9

### In which browser are you experiencing the issue with?

Brave Version 1.36.109 Chromium: 99.0.4844.51 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
Input fields are no longer in darkmode
```

**Comment by XalaTheShepard** [comment]
The issue is in particular with the input select fields using a dark theme. The input select fields all have since the update to HA Core 2022.3.0 a white background and no longer use the theme. Was working fine in 2022.2.9. Please find enclosed an image as example of the issue.

**Comment by XalaTheShepard** [comment]
![Uploading Screenshot_20220303_162416_io.homeassistant.companion.android.jpg…]()

**Comment by bramkragten** [comment]
Please update your theme, or base your theme on the dark mode HA theme, and not the light mode.

You can use the following variables:

<https://github.com/home-assistant/frontend/blob/dev/src/resources/ha-style.ts#L115-L127>
