### ISSUE TITLE
Config edit window background

### ISSUE THREAD

**Issue by dvanhoose53** [home-assistant/frontend#11917]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The edit windows are now white with grey text. Occurs in all themes.

### Describe the behavior you expected

Edit windows follow theme.

### Steps to reproduce the issue

1.Editing config windows
2.
3.
...

### What version of Home Assistant Core has the issue?

3.0

### What was the last working version of Home Assistant Core?

2.9

### In which browser are you experiencing the issue with?

Safari and IOS

**Comment by bramkragten** [comment]
Can you add a screenshot?

**Comment by dvanhoose53** [comment]
![](https://community-assets.home-assistant.io/original/4X/7/9/0/7904b474ecb7d70c5ef302b7bc50379200162563.png)
