### ISSUE TITLE
input select fields dont work anymore

### ISSUE THREAD

**Issue by compujunk** [home-assistant/frontend#11913]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

all the inputselects no longer work. previously you had a down arrow that you could click on and then you got a list from which to choose. Now all arrows are selected at the same time, so that all lists remain open. (see attached screenshots)
![image](https://user-images.githubusercontent.com/50024099/156484151-374a37d1-40d9-4def-a2c6-11e01609993d.png)
![image](https://user-images.githubusercontent.com/50024099/156484265-df1ddbd1-5b89-4254-b071-2edf3f013d15.png)

### Describe the behavior you expected

like before

### Steps to reproduce the issue

1.custom:mini-media-player has the problem
2.custom:light-entity-card has the problem
3.
...

### What version of Home Assistant Core has the issue?

core-2022.3.0

### What was the last working version of Home Assistant Core?

2022.2.9

### In which browser are you experiencing the issue with?

Google Chrome 98.0.4758.102, Opera 83.0.4254.62, Vivaldi 5.1.2567.57

### Which operating system are you using to run this browser?

Windows 10, Ubuntu 20.04.4, debian 11.2

**Comment by bramkragten** [comment]
These are custom cards I guess? Please raise an issue in the repo of the custom card.
