### ISSUE TITLE
Contact sensor, can't choose Window - Door etc

### ISSUE THREAD

**Issue by Chreece** [home-assistant/frontend#11916]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Contact Sensors:
Choosing one item from the "show as" (I hope it is the right name in English because that's not my lovelace language) throws you out of this menu. 
Tried with app and Chrome browser.

### Describe the behavior you expected

Should allow you to save the changes and would change the device_class and icon. 

### Steps to reproduce the issue

1. Select a contact sensor entity
2. Settings
3. Try to select a device class (Window, door etc. )
...

### What version of Home Assistant Core has the issue?

2022.03.0

### In which browser are you experiencing the issue with?

App / chrome

### Which operating system are you using to run this browser?

Android 12

**Comment by hellcry37** [comment]
Up for this!

Go in to your ha HA and try to change on a Aqara door window sensor the type from "door" to "window" or from whatever is set to something else. the window will just disappear and nothing will be changed.
I think this happens with all binary sensors, just tried a Samjin (smartthings) one, does the same.

**Comment by ssaenger** [comment]
This is something I've noticed as well.

**Comment by callacomp** [comment]
Same here. Select window from door and the window dissappear.

## System Health

version | core-2022.3.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.98
arch | x86_64
timezone | Europe/London

**Comment by rodrigogbs** [comment]
Same problem here using Zigbee2mqtt, trying to change the device class but the window just closes without saving the settings...

![Uploading 2022_03_07_11_48_55_AdobeCreativeCloudExpress.gif…]()

**Comment by Chreece** [comment]
Fixed in https://github.com/home-assistant/frontend/pull/12010
