### ISSUE TITLE
Cards showing full drops downs over other cards

### ISSUE THREAD

**Issue by cloudbr34k84** [home-assistant/frontend#11912]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Drop down options for cards is showing the whole drop down, which overlapping other cards. See screen shot
![image](https://user-images.githubusercontent.com/58960644/156483173-d5112b77-07da-4ce5-990a-bb1dc91ff984.png)

### Describe the behavior you expected

It shouldnt be doing. It was fine before the upgrade

### Steps to reproduce the issue

1. Im using the Sonos Lovelace Card
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.3.0

### What was the last working version of Home Assistant Core?

2022.2.9

### In which browser are you experiencing the issue with?

Google Chrome Version 98.0.4758.102 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Zorin OS 16

**Comment by bramkragten** [comment]
This is a custom card, please raise an issue at the repo of this card.
