### ISSUE TITLE
Error in Automation editor code

### ISSUE THREAD

**Issue by bschatzow** [home-assistant/frontend#11936]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Tried creating a new automation with time and before sunrise. Automation created does not create this as an or condition.
This is the code produced:
```
condition:
  - condition: time
    before: '00:00:00'
  - condition: sun
    before: sunrise
```

### Describe the behavior you expected

Create automation with correct code. Had similar problem in beta. Fixed and broke again.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.

### What was the last working version of Home Assistant Core?

2022.3.1

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

Android 12, windows 10

**Comment by zsarnett** [comment]
I cant replicate this in the latest. Could you get a screen recording of this changing?

**Comment by bschatzow** [comment]
I just did this.
   I added a condition, ran the trace, then deleted the condition and re-ran the trace.  The condition that I deleted is still in the trace. This causes saved automations to be built incorrectly.

Don't know what screen shot you need? Sometimes is shows an after 11PM and before 0000 when I only checked after. Going back and forth between ui and yaml or trace causes all types of issues for me

**Comment by bschatzow** [comment]
@zsarnett
Another bug with the automation editor is if you change the time and run a trace it keeps the old time in the trace.  Must be a cache issue, but the editor should be smart enough that if it is making the change it would clear the old data?  This makes it very difficult to troubleshoot using the automation editor tool.
