### ISSUE TITLE
Error when creating a statistic card

### ISSUE THREAD

**Issue by mkuess** [home-assistant/frontend#11930]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

hello :) i have an error when i am coosing a entity in the statistic card. here are also the screenshots

https://ibb.co/qn5dYF0
https://ibb.co/L5sdRgs

### Describe the behavior you expected

i expect no error when i choose this card

### Steps to reproduce the issue

1. create a statistic card
2. choose a entity
3. get an error
...

### What version of Home Assistant Core has the issue?

core-2022.3.1

**Comment by 0n3man** [comment]
I have the same error.  When you add an entity it clears all the other records associated with this card. If I select code editor and then replace
entities: []
with the desired entities it works fine.

**Comment by spacegaier** [comment]
@zsarnett Perhaps related to https://github.com/home-assistant/frontend/pull/11942?
