### ISSUE TITLE
Radio Browser locks up (IOS/Android) when selecting USA

### ISSUE THREAD

**Issue by milnergroup** [home-assistant/frontend#11932]
### The problem

When browsing by country and selecting USA.  Mobile app locks up (on IOS and Android) presuming it is because of the large number of stations.

### What version of Home Assistant Core has the issue?

2022.3.1

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Radio Browser

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/radio_browser

**Comment by Raukze** [comment]
In the mentioned issue I also included a screen recording where the locking up is shown

**Comment by emufan** [comment]
I have the same for Germany. In ios as well.

**Comment by emufan** [comment]
> I have the same for Germany. In ios as well.

Still the case.
