### ISSUE TITLE
quick bar no longer works

### ISSUE THREAD

**Issue by Torok42** [home-assistant/frontend#11939]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When you select a page in the quick bar, nothing happens. We do not change the page and the system searches with the wheel that turns next to the selected element

Documentation : 
https://www.home-assistant.io/docs/tools/quick-bar/

### Describe the behavior you expected

When a page is selected in the quick bar, the selected page is displayed.

### Steps to reproduce the issue

1. click hotkey c
2. Register Developer tools
3. click on the Developer tools item

The Developer tools page is not displayed and the quick bar is looking.

![image](https://user-images.githubusercontent.com/58152695/156858883-be0d5f89-1919-4778-a7c4-f55ff6e1752f.png)

### What version of Home Assistant Core has the issue?

Core-2022-03-1

### In which browser are you experiencing the issue with?

Chrome Version 99.0.4844.51

### Which operating system are you using to run this browser?

Windows 10

### Javascript errors shown in your browser console/inspector

```txt
ha-quick-bar.ts:78 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'action')
    at F.value (cf7c6579.js:229:123)
    at F.value (cf7c6579.js:229:2480)
    at F.handleEvent (:8123/frontend_latest/app.41ffbdd2.js:1248:19755)
DevTools failed to load source map: Could not load content for http://192.168.0.103:8123/hacsfiles/lovelace-home-feed-card/lovelace-home-feed-card.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by spacegaier** [comment]
Already fixed in dev via https://github.com/home-assistant/frontend/pull/11900.
