### ISSUE TITLE
ha-time-input ":" not readable in dark themes

### ISSUE THREAD

**Issue by emufan** [home-assistant/frontend#11933]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The : between hour and minutes is set fixed to an unreadable color and is not using a themeable variable:

![image](https://user-images.githubusercontent.com/22775515/156786431-ecdf0b31-abaa-45e3-9dc0-c0a7ff97e3a3.png)

```
.mdc-text-field:not(.mdc-text-field--disabled) .mdc-text-field__affix--suffix {
    color: rgba(0, 0, 0, 0.6);
}
```

### Describe the behavior you expected

Assign a themable variable-color as for the other parts of the I element, e.g. as for hour-span

```
:host(:not([disabled])) .mdc-text-field .mdc-text-field__input {
    color: var(--mdc-text-field-ink-color, rgba(0, 0, 0, 0.87));
}
```

### Steps to reproduce the issue

1. Select a custom dark theme or darkmode of standard theme.

2. Place time field in an entity card.

### What version of Home Assistant Core has the issue?

core-2022.3.1

### What was the last working version of Home Assistant Core?

core.2022.2.x

**Comment by Torok42** [comment]
Same bug that https://github.com/home-assistant/frontend/issues/11859

**Comment by spacegaier** [comment]
Was already solved via https://github.com/home-assistant/frontend/pull/11907
