### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by sean-yao** [home-assistant/frontend#11944]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Logger: frontend.js.latest.202202031
Source: components/system_log/__init__.py:190
First occurred: 9:43:54 PM (4 occurrences)
Last logged: 9:43:54 PM

http://nas:8123/frontend_latest/b20c13a8.js:245:519 Uncaught TypeError: Cannot read properties of undefined (reading 'get')

### Describe the behavior you expected

This error appears in the log several times.

### Steps to reproduce the issue

1. Run HA container
2. check the logs
3.
...

### What version of Home Assistant Core has the issue?

	core-2022.2.9

**Comment by spacegaier** [comment]
Does the issue still persist with current HA versions?
