### ISSUE TITLE
Dropdown lists empty in Z-Wave device configuration panel

### ISSUE THREAD

**Issue by zglurb** [home-assistant/frontend#11951]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The dropdown lists in the Z-Wave device configuration panel are left empty since the 2022.3 update. Changing the values doesn't apply the change on the device despite a message saying otherwise.

![image](https://user-images.githubusercontent.com/1644062/156885441-8045d7dc-4db2-4c5d-9ff9-1c403b2cc5b4.png)

### Describe the behavior you expected

The dropdown should be initialized with the actual value. The device configuration should be updated when I select a value.

### Steps to reproduce the issue

1. Go the a Z-Wave device page
2. Click on Configure Device.

### What version of Home Assistant Core has the issue?

core-2022.3.1

### What was the last working version of Home Assistant Core?

core-2022.2.x

### In which browser are you experiencing the issue with?

Google Chrome 99.0.4844.51

### Which operating system are you using to run this browser?

Windows 11

### Javascript errors shown in your browser console/inspector

```txt
No JS error in the console.0
```

### Additional information

I'm also experimenting the same issue with the default dashboard dropdown in the profile page. An issue is already opened for this :  #11897.

Could be related to the material update in 2022.3 ?

**Comment by Mattie112** [comment]
Yes exactly I also have this issue!

I have a https://qubino.com/products/flush-1d-relay/flush-1d-relay-tech/ that I needed to activate the '2nd' input to be a motion detect. That requires sending a configure command, then exclude and then include (yeah....). I was really frustrated that I could not get it to work.

So to make a long story short:

![image](https://user-images.githubusercontent.com/662896/157745289-3ddffcb1-3724-41e6-bd0c-b89189260d33.png)

When I select a value from the list the following is send:

```
2022-03-10T19:50:02.372Z SERIAL » 0x010c00132a05700464010025bb40                                      (14 bytes)
2022-03-10T19:50:02.374Z DRIVER » [Node 042] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      187
                                  └─[ConfigurationCCSet]
                                      parameter #:      100
                                      reset to default: false
                                      value size:       1
                                      value format:     UnsignedInteger
                                      value:            0
```

However it should not send 0!

![image](https://user-images.githubusercontent.com/662896/157745379-5e79b114-ef7b-419b-b051-9c40f8ab8074.png)


When manually doing a `call service: Z-Wave JS: Set a Z-Wave device configuration parameter` and then using `1` as the value I was able to set this. 

Just thought reporting it, not sure if it's an UI bug or not but this is the one I found :)

## System Health

version | core-2022.3.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.92-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.3
docker_version | 20.10.9
disk_total | 111.1 GB
disk_used | 8.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.3.0), Grafana (7.4.1), InfluxDB (4.3.0), Z-Wave JS (0.1.54), File editor (5.3.3), Glances (0.14.2), Studio Code Server (4.1.0), AppDaemon 4 (0.8.1), Mosquitto broker (6.0.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>
