### ISSUE TITLE
Humidifier more-info dialog doesn't properly display humidifier modes

### ISSUE THREAD

**Issue by alexanv1** [home-assistant/frontend#11955]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

More-info dialog for Humidifier entities doesn't properly display Humidifier modes and doesn't allow selecting a mode. When clicking the mode is highlighted in the UI but it doesn't actually propagate to the entity.
![Humidifier](https://user-images.githubusercontent.com/44785744/156909583-f2ea57f3-f6c8-42ee-b9ca-8ff1f81d8f66.png)

### Describe the behavior you expected

Expect the more-info dialog for Humidifier entities to be similar to more-info for Water Heater or Climate where a mode selector (drop-down) is shows. That's how it used to behave prior to 2022.3 release so this is a regression in 2022.3

### Steps to reproduce the issue

1. Open more-info dialog for a Humidifier entity that exposes multiple modes. Observe that a mode drop-down isn't properly displayed and modes can't be selected.

### What version of Home Assistant Core has the issue?

2022.3.1

### What was the last working version of Home Assistant Core?

2022.2.9

### In which browser are you experiencing the issue with?

Google Chrome 99.0.4844.51, Microsoft Edge

### Which operating system are you using to run this browser?

Windows, Android (both browser and companion app)

**Comment by spacegaier** [comment]
Could you please post the entity state info from the HA dev tools here. That helps us to recreate the issue, since not everyone as a real humidifier in their setup to test with.

**Comment by alexanv1** [comment]
Sure:
![state](https://user-images.githubusercontent.com/44785744/156921055-e0fa5579-5c58-4a81-b92e-8e53d049b7a3.png)

**Comment by Kirmas** [comment]
Looks like commit that changing this [more-info-humidifier.ts](https://github.com/home-assistant/frontend/commit/a0aed9112c2d2aa92b8400aa9128f6efe56fb2bd#diff-83d6afbf092b932130f98951123da4d05ce1c1d09cdecead0d83f4e8d24274ea) line 79-88

**Comment by rytilahti** [comment]
That change was done in #11626, maybe @bramkragten has an idea what's the best way to debug this?

**Comment by spacegaier** [comment]
@alexanv1 As copy-able text please, I'd rather not have to type all that manually 😉.

**Comment by kirintwn** [comment]
Can confirmed the problem with a `Hitachi RD-200HH`. The version `latest` is not working while `2022.2` work just fine
@spacegaier below is the copy-able text for the entity state

| Entity              | State | Attributes                                                                                                                                                                                                                                                         |
|:------------------- | ----- |:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| humidifier.rd_200hh | on    | min_humidity: 40<br/>max_humidity: 70<br/>available_modes: Auto, Custom, Clothes Dry, Air Purify, Mold Prev, Low Humidity, Eco Comfort<br/>humidity: 30<br/>mode: Clothes Dry<br/>device_class: dehumidifier<br/>friendly_name: RD-200HH<br/>supported_features: 1 |
