### ISSUE TITLE
Automation edit page malformed

### ISSUE THREAD

**Issue by blasebast** [home-assistant/frontend#11953]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Issue is about malformed automation edit page, when there is longer template as a condition, or trigger.
As visible in the attachment elements that are not supposed to, cover the text box content.
<img width="890" alt="Screenshot 2022-03-06 at 4 49 52" src="https://user-images.githubusercontent.com/25853397/156908460-58a40f1b-9f2b-4392-9183-cb00c8ad8dc0.png">

### Describe the behavior you expected

Page fields should be visible and not covering one another.

### Steps to reproduce the issue

1. create dummy automation
2. add extended jinja2 as a template
3. save the automation
4. see if during the edit whole template is visible without being blocked, while creating automation you can use above attachment as an inspiration
...

### What version of Home Assistant Core has the issue?

2022.3.1

### What was the last working version of Home Assistant Core?

2022.2.*

### In which browser are you experiencing the issue with?

OPERA: Version:84.0.4316.21 (arm64), CHROME: Version 98.0.4758.109 (Official Build) (arm64)

### Which operating system are you using to run this browser?

macOS Monterey

**Comment by ibreek** [comment]
I also have some strange layout issues @ automations
I don't know how to show this gif in this post so a link has to suffice :)
https://i.imgur.com/p7Fze4G.gif
