### ISSUE TITLE
Users missing from People & Zones

### ISSUE THREAD

**Issue by krauser70** [home-assistant/frontend#11962]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am running 2022.3.2 on an Odroid device and went to update a user in Configuration->People & Zones and all users are missing except the original Admin account I created.  I thought I would try to add one again, but it returns that the user already exists.  I can login as every user account even though they do not show in the People & Zones UI
[HA Missing Users.pdf](https://github.com/home-assistant/frontend/files/8194598/HA.Missing.Users.pdf)
.  Not sure when they actually went missing from the UI and not sure where to check via configuration files for them.  

### Describe the behavior you expected

I expected to see my admin account and 3 additional user accounts.

### Steps to reproduce the issue

1. Open HA
2. Go to Configuration
3. Go to People & Zones
...

### What version of Home Assistant Core has the issue?

2022.3.2

### In which browser are you experiencing the issue with?

Version 99.0.4844.51 (Official Build) (64-bit), MS Edge, Companion App on Android

### Which operating system are you using to run this browser?

Windows 10 and Windows 11

**Comment by bramkragten** [comment]
Users are only available in advanced mode, otherwise user management is limited to people.

**Comment by krauser70** [comment]
I was able to add a test user account and it does show in the People tab of People & Zones but other accounts still not showing.

**Comment by bramkragten** [comment]
Have you enabled advanced mode? If so, you will have a new tab `users` where you can find them.
