### ISSUE TITLE
Timezone error in Energy dashboard

### ISSUE THREAD

**Issue by Morflo** [home-assistant/frontend#11976]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Time error displaying used energy bar in Energy dashboard.
The timed bars are 1 hour offset what it should be. 
Example energy used bar for hour 02:00- 03:00 should actually be shown as 01:00 - 02:00
![Energy chart](https://user-images.githubusercontent.com/84277259/157192635-5b031fb6-c53f-411b-ae8a-933bc358a62e.png)
![Actual used energy pr  hour](https://user-images.githubusercontent.com/84277259/157192653-558ecec6-c1b0-4c35-9d85-19111a3e2cf5.png)

### Describe the behavior you expected

The dashboard should show energy used correctly pr. hour

### Steps to reproduce the issue

1. show energy dashboard.
2. Timezone Europe/Oslo
3. 
4.
5.
...

### What version of Home Assistant Core has the issue?

core-2022.3.2

### In which browser are you experiencing the issue with?

Google Crome, Edge, safari, Companion app IOS

### Which operating system are you using to run this browser?

macOS Monterey 12.2.1 , Windows server 2019, IOS 15.3.1

**Comment by bramkragten** [comment]
is your backend and frontend timezone the same?

**Comment by Morflo** [comment]
> is your backend and frontend timezone the same?

Same Timezone on frontend and backend.
All good when using ApexCharts-card to show data. Only Energy show wrong data offset one hour.

**Comment by Morflo** [comment]
Did not mean to close
