### ISSUE TITLE
UI is showing supervisor-2022.01.1 as the latest when 2022.03.2 is the latest on GitHub

### ISSUE THREAD

**Issue by Intecpsp** [home-assistant/frontend#11972]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The UI is showing supervisor-2022.01.1 as the latest when 2022.03.2 is the latest on GitHub. I used to be on the beta channel (so I have received a few updates past what I'm seeing now), but recently flipped to stable and now Supervisor updates are not being displayed for me to update. Note: I have received Core updates since flipping.

### Describe the behavior you expected

2022.03.2 should be displayed as the newest version

### Steps to reproduce the issue

1. Open 'Configuration'
2. Click 'Add-ons, Backups, & Supervisor'
3. Click System
...

### What version of Home Assistant Core has the issue?

core-2022.3.2

### In which browser are you experiencing the issue with?

Google Chrome 98.0.4758.109 and Safari 12.1.2 (14607.3.9)

### Which operating system are you using to run this browser?

MacOS Mojave 10.14.6

### Additional information

![Screen Shot 2022-03-07 at 12 56 37 PM](https://user-images.githubusercontent.com/1164012/157090758-37e7acfa-27d8-41b7-9ffd-ab3ea67ef3c6.png)

**Comment by ludeeus** [comment]
<https://version.home-assistant.io/stable.json> `2022.01.1` is the newest stable version of the Supervisor.

**Comment by Intecpsp** [comment]
> https://version.home-assistant.io/stable.json `2022.01.1` is the newest stable version of the Supervisor.

[2022.3.2](https://github.com/home-assistant/supervisor/releases) is showing as the latest release on GitHub. How does the stable.json file get updated?
