### ISSUE TITLE
Unable to edit and save Dashboards

### ISSUE THREAD

**Issue by ranrinc** [home-assistant/frontend#11983]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When you are editing the Dashboard it will be missing URL form, so when you want to save it will create error

### Describe the behavior you expected

Editing dashboards then any changes or not will be able to save

### Steps to reproduce the issue

1. Edit Dashboards
2. Update
3.
...

### What version of Home Assistant Core has the issue?

2022.3.3

### In which browser are you experiencing the issue with?

Brave Version 1.36.109 Chromium: 99.0.4844.51

### Which operating system are you using to run this browser?

macOS Monterey

### Additional information

Creating New Dashboards
<img width="403" alt="Screen Shot 2022-03-08 at 8 31 59 PM" src="https://user-images.githubusercontent.com/15801696/157265268-ff847e95-938c-4352-8c70-356149efcb74.png">

Updating Dashboards
<img width="599" alt="Screen Shot 2022-03-08 at 8 32 22 PM" src="https://user-images.githubusercontent.com/15801696/157265388-2aa7f667-6740-4b08-b65c-c5f0d5c0458f.png">

**Comment by maretodoric** [comment]
Just came here to report this issue and find that it's already reported.
I claim to experience the same issue. I cannot update any dashboards once created. Old dashboard are also affected.
