### ISSUE TITLE
Media playback bar positions badly against bottom safe area inset on iPhone

### ISSUE THREAD

**Issue by zacwest** [home-assistant/frontend#11985]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Often when loading the media pages, the bar underlaps the home indicator, which makes it difficult to interact with or read:

<img width="350" src="https://user-images.githubusercontent.com/74188/157289679-2d8a7106-b898-4474-b94c-a1388802660f.PNG">

Other times it's above it (usually the first load of the page), but it doesn't draw the background underneath so it looks off:

<img width="350" src="https://user-images.githubusercontent.com/74188/157290113-f2d1d1da-2964-44f5-8fda-83595110f66e.PNG">

### Describe the behavior you expected

See above

### Steps to reproduce the issue

See above

### What version of Home Assistant Core has the issue?

core-2022.3.2

### What was the last working version of Home Assistant Core?

n/a

### In which browser are you experiencing the issue with?

iOS app

### Which operating system are you using to run this browser?

iOS 15.4

**Comment by zacwest** [comment]
Still an issue

**Comment by matthiasdebaat** [comment]
Still an issue
