### ISSUE TITLE
Color picker not matching entity selected color

### ISSUE THREAD

**Issue by thecode** [home-assistant/frontend#11996]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This one is a little bit tricky but can be reproduced easily :-)
When a light entity changes color not by using the color picker, the color picker will show the selected color as white while the entity icon show the correct color:
![image](https://user-images.githubusercontent.com/1858925/157511496-911b97d4-39e3-4cf2-af3d-a52b27ab0457.png)
The tricky part here is that it looks like it does not happen to colors from the red scale.
How to reproduce easily:
The following service call will show the correct color on the color picker:
```yaml
service: light.turn_on
data:
  color_name: red
target:
  entity_id: light.test_shelly_duo_rgbw
```
![image](https://user-images.githubusercontent.com/1858925/157511843-7880e5df-0016-4797-817a-6b58d3e1d399.png)

Replacing the color with a greenish color will show the picker in the center as white, for example:
```yaml
service: light.turn_on
data:
  color_name: blue
target:
  entity_id: light.test_shelly_duo_rgbw
```
![image](https://user-images.githubusercontent.com/1858925/157513050-cf98e5db-25f4-4685-8898-651d7522e15b.png)

Note that the icon shows the correct color, also if the color picker is left open is will switch to the correct color until it is closed and opened again.

Entity attributes for the above call with `blue`:
```
min_mireds: 153
max_mireds: 333
effect_list: Off, Meteor Shower, Gradual Change, Flash
supported_color_modes: color_temp, rgb
color_mode: rgbw
brightness: 74
hs_color: 240, 100
rgb_color: 0, 0, 255
rgbw_color: 0, 0, 255, 0
xy_color: 0.136, 0.04
effect: Off
friendly_name: Test Shelly Duo RGBW
supported_features: 36
```

I have shown for Shelly bulb, but it is also reproduced for `Deconz` light

### Describe the behavior you expected

Color picker should match the entity color

### Steps to reproduce the issue

Use the following service call with an RGB bulb:
```yaml
service: light.turn_on
data:
  color_name: blue
target:
  entity_id: light.test_shelly_duo_rgbw
```
Color picker will show incorrect color while icon will show the correct color.

### What version of Home Assistant Core has the issue?

core-2022.4.0.dev20220308

### In which browser are you experiencing the issue with?

Google Chrome 98.0.4758.102 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
min_mireds: 153
max_mireds: 333
effect_list: Off, Meteor Shower, Gradual Change, Flash
supported_color_modes: color_temp, rgb
color_mode: rgbw
brightness: 74
hs_color: 240, 100
rgb_color: 0, 0, 255
rgbw_color: 0, 0, 255, 0
xy_color: 0.136, 0.04
effect: Off
friendly_name: Test Shelly Duo RGBW
supported_features: 36
```
```


### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

**Comment by thecode** [comment]
cc @chemelli74

**Comment by thecode** [comment]
Still broken (2022.10.0.dev...)

**Comment by karwosts** [comment]
I tested this with the new color picker in 2023.6 and it works as expected, the picker tracks the current color. 

Feel free to comment if you still see that it is broken.
