### ISSUE TITLE
Drag drop ordering cards not working in Firefox

### ISSUE THREAD

**Issue by ericmuijs** [home-assistant/frontend#11994]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I'm unable to drag items within a card in the lovelace UI in Firefox. Works with Chrome.

### Describe the behavior you expected

Expected Chrome behavior, be able to order the entities in a card with Firefox.

### Steps to reproduce the issue

1. Open firefox + hass
2. Edit cards
3. Reorder entities with dragging.
...

### What version of Home Assistant Core has the issue?

core-2022.3.3

### In which browser are you experiencing the issue with?

Firefox 98.0 (64-bits)

### Which operating system are you using to run this browser?

Windows 11

**Comment by zsarnett** [comment]
This became an issue in Firefox 98.0... Version 97 worked. Will research what changed..

**Comment by progman32** [comment]
Still happening for me on latest stable.

**Comment by ndng28** [comment]
Can confirm, still happening in FF latest.

**Comment by trunneml** [comment]
Same Problem here

**Comment by Duetting** [comment]
Also still happening for me.

**Comment by philoepp** [comment]
Same problem still here with FF 103.0.2 (64-Bit)

**Comment by ast0815** [comment]
I am also not able to move entities around. Firefox 104.0 (64-bit)

**Comment by progman32** [comment]
Now working for me on 2022.9.0!

**Comment by karwosts** [comment]
Given that it's working for me, and multiple reports of it now working, I will close this as completed.
