### ISSUE TITLE
Input field of markdown card doesn't use full available height.

### ISSUE THREAD

**Issue by werra11** [home-assistant/frontend#12006]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When editing large amounts of text the markdown card doesn't extend the input field to accomodate for that. Even when there is quite a lot of room left below the input field. Editing larger amounts of text is a bit harder now since it displays less text at once.
![image](https://user-images.githubusercontent.com/60671716/157728684-3d575232-0ba8-48e8-bb62-ab811e43fb88.png)

### Describe the behavior you expected

I expected the input field to take all the room it can.

### Steps to reproduce the issue

1. Edit a markdown card with large amounts of text.

### What version of Home Assistant Core has the issue?

2022.3.3

### What was the last working version of Home Assistant Core?

2022.2.4

### In which browser are you experiencing the issue with?

Google Chrome 99.0.4844.51

### Which operating system are you using to run this browser?

Windows 10

**Comment by zsarnett** [comment]
You could just switch to the code editor for long editing

**Comment by zsarnett** [comment]
The text area is for everyday users to write text and use quick variables. The Code editor should be used for other use cases.

**Comment by werra11** [comment]
> You could just switch to the code editor for long editing

Yea I used to do that but that doesn't play very well with lists, tends to jump around quite a lot.

Since the input field was quite a bit bigger before the recent MWC update I assumed it was not intended and a bugg.
