### ISSUE TITLE
Scenes execute when starting edit

### ISSUE THREAD

**Issue by RudiKlein** [home-assistant/frontend#12005]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When starting editing a scene by clicking the pen tool (Configuration/Scenes), the scene is executed when the editor screen is loaded. 

### Describe the behavior you expected

The expectation is that when the editor is started, the scene is not executed.

### Steps to reproduce the issue

1. In W10, any browser, navigate via the HA sidebar to Configuration
2. Navigate to Automations & Scenes
3. Select the Scene tab
4. Click the pen tool to edit a scene
...

### What version of Home Assistant Core has the issue?

core-2022.3.3

### What was the last working version of Home Assistant Core?

Unknown, but the issue came up recently

### In which browser are you experiencing the issue with?

EDGE  99.0.1150.36 (Official build) (64-bit) and Chrome 99.0.4844.51 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

W10

**Comment by zsarnett** [comment]
This is by design for editing scenes
