### ISSUE TITLE
Lovelace dashboard does not appear when casted

### ISSUE THREAD

**Issue by joepotato04** [home-assistant/frontend#12012]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Unable to cast Lovelace dashboard to original model Chromecast 

### Describe the behavior you expected

White screen for 20-30 seconds and then Chromecast disconnects

### Steps to reproduce the issue

1.attempt to cast a Lovelace dashboard to Chromecast 
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.3.3

### In which browser are you experiencing the issue with?

N/A

### Which operating system are you using to run this browser?

N/A

### Javascript errors shown in your browser console/inspector

```txt
Logger: homeassistant.util.logging
Source: util/logging.py:114
First occurred: 22:54:05 (1 occurrences)
Last logged: 22:54:05

Exception in _handle_signal_show_view when dispatching 'cast_show_view': (<pychromecast.controllers.homeassistant.HomeAssistantController object at 0x7ff908154ac0>, 'media_player.joe_s_bedroom_tv', 'default_view', None) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 875, in _handle_signal_show_view self._hass_cast_controller.show_lovelace_view(view_path, url_path) File "/usr/local/lib/python3.9/site-packages/pychromecast/controllers/homeassistant.py", line 118, in show_lovelace_view self._send_connected_message( File "/usr/local/lib/python3.9/site-packages/pychromecast/controllers/homeassistant.py", line 129, in _send_connected_message self._connect_hass( File "/usr/local/lib/python3.9/site-packages/pychromecast/controllers/homeassistant.py", line 102, in _connect_hass raise PyChromecastError() pychromecast.error.PyChromecastError
```

**Comment by smartroad** [comment]
I have found the same here. Only just discovered the ability to cast a Lovelace panel to a Chromecast. I have the first gen Google Chromecast, sending audio works and pictures display, text to speech works great to. However when trying to send a dashboard to it I get the same white screen then disconnect.
