### ISSUE TITLE
Picture Glance cannot configure Tap Action

### ISSUE THREAD

**Issue by tangix** [home-assistant/frontend#12024]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Configuring Tap Action on a Picture Glance card no longer works. Instead destroys config and displays:
```
Configuration errors detected:
No type provided.
```
All other configuration options are gone.

### Describe the behavior you expected

Being able to set Tap Action as before.

### Steps to reproduce the issue

1. Create a new card, choose Picture Glance
2. Change Tap Action from `Toggle` to anything `More Info`
...

### What version of Home Assistant Core has the issue?

2022.3.3

### What was the last working version of Home Assistant Core?

2021.12.9

### In which browser are you experiencing the issue with?

Chrome 99.0.4844.51 and Edge 99.0.1150.39 

### Which operating system are you using to run this browser?

macOS Big Sur 11.6.4

**Comment by tangix** [comment]
![2022-03-12_12-39-30 (1)](https://user-images.githubusercontent.com/1013635/158016565-63498fdc-3eca-48cb-a624-218b8b4bab71.gif)

**Comment by moviele** [comment]
Same problem with me. But when I work in Yaml mode, the card works. After saving the card you can continue working in UI mode.

**Comment by breakthestatic** [comment]
This is still an issue. It's definitely a pain having to switch back & forth from yaml mode just to change the action.

**Comment by RyanWor** [comment]
Can anyone share what the yaml lines would look like for the two options ("tap action" and "hold action") should look like? I don't see those options listed in the picture-glance docs page.

**Comment by moviele** [comment]
camera_view: auto
type: picture-glance
title: Seite
entities:
  - entity: binary_sensor.blink_seite_motion_detected
  - entity: camera.blink_seite
camera_image: camera.blink_seite
entity: camera.blink_seite
tap_action:
  action: call-service
  service: script.seite
My example …….

**Comment by RyanWor** [comment]
Thank you @moviele got it working now

`    tap_action:
      action: navigate
      navigation_path: /lovelace/master
    hold_action:
      action: toggle`

**Comment by moviele** [comment]
Great! You are welcome!

**Comment by breakthestatic** [comment]
FYI all, looks like this has been inadvertently fixed in 2022.11. Not sure if it was something upstream from the LitElement library or refactoring done within HA, but I can once again use the UI to edit picture-glance actions:

https://user-images.githubusercontent.com/9346314/200047079-5a46fb80-75fb-4851-a907-714a753201b3.mov
