### ISSUE TITLE
unable to edit automation name through UI (Cannot read properties of undefined)

### ISSUE THREAD

**Issue by ktechies** [home-assistant/frontend#12033]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

after updating to 2022.3.4 from 2022.3.1 i'm unable to edit the automation name through UI. After changing the name the save button also doesn't show up.

Frontend version: 20220301.1 - latest

logs contain the following error

Logger: frontend.js.latest.202203011
Source: components/system_log/__init__.py:190
First occurred: 6:02:54 PM (3 occurrences)
Last logged: 6:02:59 PM

http://192.168.100.15:8123/frontend_latest/79839f50.js:186:1051 Uncaught TypeError: Cannot read properties of undefined (reading 'value')

### Describe the behavior you expected

a changed name upon saving and a save button after changing the input field.

### Steps to reproduce the issue

1. create new automation, make change the name
2. save
3. go back to automation overview
4. expect name to be changed into the chosed one
5. notice its still named "New Automation"
...

### What version of Home Assistant Core has the issue?

2022.3.4

### What was the last working version of Home Assistant Core?

2022.3.1

### In which browser are you experiencing the issue with?

Google chrome 99.0.4844.51 (64-bit)/Firefox 98.0 (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### Javascript errors shown in your browser console/inspector

```txt
blueprint-automation-editor.ts:28 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at n.value (blueprint-automation-editor.ts:28:1)
    at F.handleEvent (styles.ts:368:1)
    at HTMLLabelElement.<anonymous> (fffc75be.js:2:2186)
```

**Comment by huettenwirt** [comment]
I was just about to raise this as well. 

Interesting fact to add: 

If you create a new automation, the name of the automation will be stored once, but no change on update as described by @ktechies. 
If you create a new automation based on a blueprint, the name is even not stored in the first place. The automation is listed as "New automation".

Thanks for investigating and keep up the great work!

**Comment by wildekek** [comment]
+1. I experience the issue 2 different instances of HASS 2022.3.4. Fun fact is that it does seem to work when I create an automation from scratch (not using a blueprint).
