### ISSUE TITLE
Automation > Actions > Choose > Actions > kebab menu text truncated

### ISSUE THREAD

**Issue by Fulch** [home-assistant/frontend#12032]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The text in the kebab menu is truncated in any of the Actions sections when Action type of Choose is selected.

![Screenshot 2022-03-13 at 14-40-29 Configuration – Home Assistant](https://user-images.githubusercontent.com/26844642/158065770-92bc96cc-a548-4d14-8276-512acb7e5c9c.png)

### Describe the behavior you expected

Full text to be displayed.

### Steps to reproduce the issue

1. Edit an automation with an Action type set to Choose.
2. In the Actions section click on the kebab menu to reveal the truncated menu text.
3.
...

### What version of Home Assistant Core has the issue?

2022.3.4

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Firefox 98.0 (64-bit) and Edge Version 99.0.1150.39 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Debian Buster 4.19.0-18-amd64

**Comment by spacegaier** [comment]
I traced the issue down to CSS class "root" of `<ha-form>` which prevents the `overflow` here. Haven't found good solution yet though...
