### ISSUE TITLE
Lovelace Area Card - Show live view as background not woring

### ISSUE THREAD

**Issue by raidnet-ms** [home-assistant/frontend#12048]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

While using the area card option that should show the camera streaming as background instead of a fixed image, the video stream is not working while If i use an image entity card and I set it to “live”, I can correctly see the rstp stream of motioneye camera (but if i set it to “auto” I get the same behaviour of the area card: no stream).

### Describe the behavior you expected

See the camera stream instead of the image as card background

### Steps to reproduce the issue

1. add lovelace area card
2. select show camera instead of image

### What version of Home Assistant Core has the issue?

core-2022.3.4

### In which browser are you experiencing the issue with?

edge, chrome and firefox

### Which operating system are you using to run this browser?

windows 10

### State of relevant entities

```txt
The camera is an rstp stream provided by motion eye. The stream works properly on image cards if the stream is set to "live" while with "auto" is not working.

In the area card is not possible to set it to live so I suppose is behaving like the "auto" setting is configured for it.
```

### Problem-relevant frontend configuration

```yaml
type: area
area: frontdoor
show_camera: true
```

**Comment by raidnet-ms** [comment]
Issue still happening

**Comment by raidnet-ms** [comment]
Problem still happening with 2022.9

**Comment by ziptbm** [comment]
Still present in 2023.06.2

Is the lack of response an indicator of it being by design?  If so, then it seems like the documentation should be updated to reflect that.  https://www.home-assistant.io/dashboards/area/#show_camera

```
show_camera boolean (optional, default: false)
Changes the area picture to a live feed of the camera set for the area.
```

Or if "live feed" means update every 10 seconds, then would be accurate.  

Either way, I really wish the area cards were live feeds as it'd be far more useful.

**Comment by raidnet-ms** [comment]
I'm using the default settings for the card.

**Comment by ziptbm** [comment]
This still does not work as I believe it should.

**Comment by karwosts** [comment]
#18643 proposes for area card to support the `camera_view: live` similar to how other picture cards can do.
