### ISSUE TITLE
Entity.sensor name too long, exceed default card in energy, trashbin dissapears 

### ISSUE THREAD

**Issue by boheme61** [home-assistant/frontend#12051]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In ENERGY Dasboard

[quote="Telectroboy, post:17, topic:335849, full:true"]
![Capture d’écran 2022-03-14 à 22.53.53](upload://lB0L9tOFJAU8G2iM9jUJOvgw1YE)

Hello Guys,
I’ve got same kind of problem. A sensor name is too long and make disapear the trash bin for this input.

How can I delete it by hand?

Thanks :slight_smile:
[/quote]

### Describe the behavior you expected

I just report because i saw this in above post, i have access to terminal and samba, so it's really no issue for me, if o for some reason needs to delete the sensor from energy

### Steps to reproduce the issue

1.
2.
3.
...
Look at above "post"

### What version of Home Assistant Core has the issue?

Home Assistant 2022.3.4

### In which browser are you experiencing the issue with?

latest EDGE , latest FireFox

### Which operating system are you using to run this browser?

Windows 10

**Comment by boheme61** [comment]
PS: Sorry, just noticed the small letters now ... Move it to frontend (you should really have a link there instead, as it's not obvious for "first-timer" in here and HA community

**Comment by boheme61** [comment]
And obviously also same "behavior" in HA-App on Android

**Comment by Telectroboy** [comment]
Thank you for the bug report !

I've been able to delete the sensor by using inspect function of the browser. But anyway it's a bug.
![image](https://user-images.githubusercontent.com/8759967/158328228-7e02ccc6-1bd5-4993-8f44-a2db4dd5bde8.png)

**Comment by jpcasta** [comment]
Hello,
I got the same issue today.
The entity name was too long and then the trash bin was hidden by the solar panel card.
Thanks

**Comment by pciechanowski** [comment]
Same here in 2023. I use integration which adds full serial number of energy meter in it's name and also can't remove

**Comment by Chaoscontrol** [comment]
Still happening. A workaround for those affected is to manually edit the HTML, shorten the text, and you'll be able to click the delete button.

**Comment by karwosts** [comment]
Addressed in #15786
