### ISSUE TITLE
Navigating to an automation through Related tab of a device doesn't close the pop up

### ISSUE THREAD

**Issue by drthanwho** [home-assistant/frontend#12090]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Unless it's intended to to do this, navigating to an automation through entity pop up --> Related Tab --> automation --> automation entity pop up --> Edit button the original entity pop up doesn't go away when the automation editor opens up.

![related_bug](https://user-images.githubusercontent.com/22405505/159297227-346bf56e-636a-49ea-83b4-8165bdfee5a5.gif)
 

### Describe the behavior you expected

After clicking on the edit button I'd expect both popups to go away, not just the automation entity's pop up.

### Steps to reproduce the issue

1. Open up an entity pop-up
2. Go to Related tab
3. Click on an automation
4. Click on edit button
...

### What version of Home Assistant Core has the issue?

core-2022.3.3

### What was the last working version of Home Assistant Core?

unsure

### In which browser are you experiencing the issue with?

Google Chrome Version 99.0.4844.51 / Microsoft Edge Version 99.0.1150.46

### Which operating system are you using to run this browser?

Windows 10

**Comment by drthanwho** [comment]
Still the case

**Comment by drthanwho** [comment]
Still happening

**Comment by karwosts** [comment]
Just tested this and I don't observe it occuring anymore. Leave a comment if you still see an issue.
