### ISSUE TITLE
Integrating Modbus Climate

### ISSUE THREAD

**Issue by pesh000** [home-assistant/frontend#12092]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After successful integrating of modbus climate, everythings work but cannot set the temp. I found that you use modbus FC17 (write multiple registers) to set the temp, but most termotates doesn't support it. They support FC6 (write single register). Whit setting temp we change only one register you don't need FC17

### Describe the behavior you expected

Changing the set_temp to use modbus FC6, not FC17

### Steps to reproduce the issue

1. Add modbus climate
2. Try to change temp (you'll see it use FC17)
3.
...

### What version of Home Assistant Core has the issue?

core-2022.3.6

### What was the last working version of Home Assistant Core?

core-2022.3.6

### Which operating system are you using to run this browser?

Windows 10 x64

**Comment by elupus** [comment]
Please reopen issue on core repo.
