### ISSUE TITLE
? in success panel after setting up Threshold binary

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#12105]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing
docs icon: https://github.com/home-assistant/frontend/pull/11651

see: https://github.com/home-assistant/core/issues/68549

<img width="399" alt="Schermafbeelding 2022-03-23 om 09 29 49" src="https://user-images.githubusercontent.com/33354141/159659340-2ae96558-cd7c-4d7c-b68c-06bae60d6226.png">

### Describe the behavior you expected

NO ?

### Steps to reproduce the issue

1. setup new integration
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.4.0.dev20220323

**Comment by spacegaier** [comment]
I cannot reproduce this issue. I see no help icon on latest dev and beta 3.

**Comment by Mariusthvdb** [comment]
you're right, its gone:

<img width="405" alt="Schermafbeelding 2022-04-03 om 16 15 47" src="https://user-images.githubusercontent.com/33354141/161432304-000c77d6-c454-4c1b-88a2-1a1c8dfb1c11.png">

thanks for reminding me, closing.
