### ISSUE TITLE
buienradar does not show temperature or humidity

### ISSUE THREAD

**Issue by MPJK77** [home-assistant/frontend#12107]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Buienradar does not show temperature or humidity anymore (NaN)?
But it does show the condition?
Is there anyone who can solve this?

I tried to reload the integration but no difference.
I tried to remove and re-add the integration but no difference.
I tried to re-add the integration with different coordinates but no difference.

Always clearing the browser cache before restarting core or rebooting host.
Nothing seems to help.

![image](https://user-images.githubusercontent.com/35330802/159681174-697582e2-ada3-4025-a3dd-d3067e241c4a.png)
![image](https://user-images.githubusercontent.com/35330802/159681230-777e051f-0e1c-4307-a547-fc4792a0dbc0.png)
![image](https://user-images.githubusercontent.com/35330802/159681108-755fd056-ca19-4588-8812-88d2fde901df.png)
![image](https://user-images.githubusercontent.com/35330802/159681885-135fe30b-c52b-4463-b78d-281318eb8ea9.png)
![image](https://user-images.githubusercontent.com/35330802/159681944-af6cd6d0-d942-4c6e-90ed-d11fe9b44a02.png)

### Describe the behavior you expected

I would expect to see the current temperature and humidity

### Steps to reproduce the issue

I really don't know

### What version of Home Assistant Core has the issue?

core-2022.3.6

### In which browser are you experiencing the issue with?

Google Chrome

### Which operating system are you using to run this browser?

Google Chrome 99.0.4844.82

### State of relevant entities

```txt
Buienradar Temperature --> sensor.buienradar_temperature --> state = unknown
Buienradar Humidity --> sensor.buienradar_humidity --> state = unknown

but:

Buienradar Condition --> sensor.buienradar_condition --> state = cloudy!? This one works normally?
```

**Comment by MPJK77** [comment]
I changed the coordinates to the exact point of the station and now it works.
The coordinates used to be my home address wich is not the exact same place as the weather station.

**Comment by jurgen2005** [comment]
Mine still does not work with coordinates 51.57,4.93 for Gilze Rijen

**Comment by MPJK77** [comment]
Hi Jurgen2005,

You need to change the coördinaties to 51.94 and 5.56 for station Gilze Rijen (6350).
Don't forget to clear your cache and reload HA.

Gr Maarten

**Comment by jurgen2005** [comment]
Hi Maarten, thx! Works perfectly! Strange as this xml says:
<weerstation id="6350">
<stationcode>6350</stationcode>
<stationnaam regio="Gilze Rijen">Meetstation Gilze Rijen</stationnaam>
<lat>51.57</lat>
<lon>4.93</lon>

https://data.buienradar.nl/1.0/feed/xml

**Comment by MPJK77** [comment]
If you look a little bit lower in the xml you will find the correct coordinates

![image](https://user-images.githubusercontent.com/35330802/160613496-76d302d0-1213-4f2d-9e46-75ad76da6a14.png)
