### ISSUE TITLE
Wrong Device Logo

### ISSUE THREAD

**Issue by MaxK99** [home-assistant/frontend#12123]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

A Ubiquity logo is shown for this Shelly device.  All other Shelly devices are showing the correct Shelly logo.

![wronglogo](https://user-images.githubusercontent.com/60298864/159940452-4a97c24c-d295-4a29-b63d-8a1b82f46449.jpeg)
.

### Describe the behavior you expected

A Shelly logo should be shown for the Shelly device.

### Steps to reproduce the issue

1. Login to HA via a browser on the local network or through the mobile app.
2. Navigate to Configuration
3. Navigate to Devices & Services
4. On the Integrations tab, select the device in the Shelly integration.

### What version of Home Assistant Core has the issue?

2022.3.7

### In which browser are you experiencing the issue with?

Google Chrome Version 99.0.4844.82 (Official Build) (64-bit), Microsoft Edge Version 99.0.1150.46 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
N/A
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

**Comment by spacegaier** [comment]
Can you please try again after you cleared your browser cache. The frontend is simply loading the brand logo that matches the device domain which is `shelly` here so I would assume this is a caching issue.

**Comment by MaxK99** [comment]
As noted in the checklist above, I have cleared the cache, completely, on both MS Edge and Chrome and still get this behavior.  I did this again just now and still have the same result.  

Also, I am now running on:
core-2022.3.8
supervisor-2022.03.5
Home Assistant OS 7.6
Chrome 100.0.4896.60 (Official Build) (64-bit)
Edge Version 99.0.1150.46 (Official build) (64-bit)

**Comment by spacegaier** [comment]
I also just realized that in your screenshot you have both diagnostics downloads for Shelly and Unifi, so this looks like an "interesting" device.

**Comment by MaxK99** [comment]
I noticed that too and asked about this on another issue:  https://github.com/home-assistant/core/issues/66444.
I think I understand the reason for the diagnostic "feature" but I don't think it explains the logo issue (it is the wrong logo - period).

**Comment by spacegaier** [comment]
Okay, that linked core issue explains why two integrations cover that device. As a result there are probably multiple config entries covering your device entry, hence multiple domains. Not sure how we currently decide which one "wins" for the logo.

**Comment by MaxK99** [comment]
I there a way to remove the device from the Unifi Network integration and keep it with the Shelly integration?

Should the logo be derived from the device info and not the integration/domain info?

**Comment by MaxK99** [comment]
Solved by removing and reinstalling Unifi Integration.
