### ISSUE TITLE
Yamaha Musiccast  TTS fails since the Media

### ISSUE THREAD

**Issue by umtauscher** [home-assistant/frontend#12130]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Speak funktion on Musiccast devices doesn#t work any more since the speak function moved to media.

### Describe the behavior you expected

I expeced it to work

### Steps to reproduce the issue

1. Musiccast device don't apear for selction when TTS is selected
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2022.3.7

### What was the last working version of Home Assistant Core?

core-2022.3.3

### In which browser are you experiencing the issue with?

Firefox 98.0.1

### Which operating system are you using to run this browser?

macOS all Versions, iOS

**Comment by spacegaier** [comment]
You need to provide some more details, for someone to have a chance at looking at this issue. Where exactly is your device not appearing? In `/media-browser/browser/app%2Cmedia-source%3A%2F%2Ftts`?

**Comment by umtauscher** [comment]
Thanks for getting back to me.
The problem is, that musiccast speakers etc are not available when the are in standby. This is unusual, because they normally come online automatically when something is played on them. Using the old tts control sending a text they automatically woke up. But using the new media tab, they are not selectable when they are in standby.
Cheers
