### ISSUE TITLE
UI editor Response error: 500

### ISSUE THREAD

**Issue by nicoema** [home-assistant/frontend#12131]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The UI editor is locking up and give me an Response error: 500 when trying to save changes.
This is when I use " !include exempel.yaml " .
I can't put it in via UI or UI yaml. I use an other editor for putting it in.
Same goes for if I manipulerar  script yaml in other editors.
But if I undo what I did in an other editor I can save in UI aging.

### Describe the behavior you expected

Super green. Just played whit HA 5 month.

### Steps to reproduce the issue

1. build a tts script in UI
2. include a yaml file for dynamic message " !include exempel.yaml "
3. Or edit an script in Atom.
...
Now get a "Response error: 500" when you try to save back in UI.

### What version of Home Assistant Core has the issue?

core-2022.3.7

### What was the last working version of Home Assistant Core?

core-2022.3.7

### In which browser are you experiencing the issue with?

Chrome 

### Which operating system are you using to run this browser?

windows 10

**Comment by nicoema** [comment]
I have also notes that if you use a "!secret alarm_password" to code in to HA ALARM throe Automation it doesn't take.
If you use an editor like Studio Code or other, you can put it in but the UI wont start "error:500"

**Comment by robharman** [comment]
I agree that this should be re-opened, or at least a suggested workaround. I don't want to have sensitive strings sitting in my automations yaml file. I check my configuration, but not sensitive values, into GitHub. Forcing us to hard-code these values in files other than the main configuration.yaml is a bummer.

**Comment by SenMorgan** [comment]
Having the same problem. Bump

**Comment by Igor122017** [comment]
when trying to save the script created in the UI, it gives an error 500. updated to the latest version. I assume this is related to the update

**Comment by johntdyer** [comment]
This is super annoying, please fix this issue

**Comment by trosendo** [comment]
Still happening. Please address this
