### ISSUE TITLE
Notification not auto-dismissed after configuring new device

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#12145]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

as title, notification tray remains populated

<img width="480" alt="Schermafbeelding 2022-03-29 om 09 01 33" src="https://user-images.githubusercontent.com/33354141/160552817-18c94362-f032-4bcf-9a91-928c4d6ca592.png">

<img width="248" alt="Schermafbeelding 2022-03-29 om 09 01 40" src="https://user-images.githubusercontent.com/33354141/160552822-7852fda4-26d7-4a59-acd6-2d5ad9930211.png">

even though the new device has been configured correctly, and is visible in the integration panel now

clicking  the link provided takes one to the integrations panel, where now no new device is displayed (which is correct ofc)

### Describe the behavior you expected

auto-dismissal

### Steps to reproduce the issue

1. see above
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.4.0.dev20220329

### What was the last working version of Home Assistant Core?

dk

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

MacOS  Monterey 12.2.1

**Comment by spacegaier** [comment]
Not really a frontend topic IMHO, since the notifications are created by the backend. And the backend would need the place to decide if everything has been setup (or ignored).

But I think that is a quite low prio FR personally.

**Comment by matthiasdebaat** [comment]
Would be nice to have this

**Comment by Mariusthvdb** [comment]
added to that, if one skips an update, the update info pane remains in view too. All in all this is a bit of a mixed experience, and I am not going to argue whether  its a frontend or backend thing. It seems it's a team thing....

**Comment by Mariusthvdb** [comment]
Check

**Comment by Mariusthvdb** [comment]
Still wacky now and then. Will check and maybe find specifics

**Comment by Mariusthvdb** [comment]
Keep
