### ISSUE TITLE
Energy tooltips don't work on mobile

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#12141]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The ℹ️ icon on energy cards show a tooltip on hover on desktop, on mobile it doesn't work.

https://user-images.githubusercontent.com/1444314/160428015-1184c167-e6ed-4687-a83e-8bbe406d0a47.mov

### Describe the behavior you expected

Show the tooltip

### Steps to reproduce the issue

1. Open energy dashboard on mobile
2. Tap the ℹ️ on one of the cards in right column

### What version of Home Assistant Core has the issue?

nightly-20220327

### What was the last working version of Home Assistant Core?

don't know

### In which browser are you experiencing the issue with?

Safari

### Which operating system are you using to run this browser?

iOS

**Comment by wtadler** [comment]
These still don't work.

**Comment by wtadler** [comment]
This is still a problem.

**Comment by wtadler** [comment]
Still not fixed.
