### ISSUE TITLE
Usability regresion with new MWC components

### ISSUE THREAD

**Issue by raqua** [home-assistant/frontend#12144]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After update from 2022.2.x to latest version 2022.3.7, the theme changed to MWC as stated in the release notes. 
Those new input boxes now take obscene amount of screen space and therefore the usability took significant hit in my opinion. Please see these screenshots, it's the same screen, for comparison:
![Screenshot_20220328-213533_Home_Assistant](https://user-images.githubusercontent.com/1541886/160480540-fe9fda58-2a0f-47fa-a425-5ca3e773e353.png)
![Screenshot_20220328-213549_Home_Assistant](https://user-images.githubusercontent.com/1541886/160480557-41bdfa39-56f1-4f90-a55a-77f75199bf9c.png)

This is on mobile, but in my browser the issue is similar, just a tiny bit better. 

The screen estate usable for item description on mobile decreased from 29 chars (maybe more, haven't tried what is the max.) to 11 characters.

### Describe the behavior you expected

Suggestion: Those huge grey boxes look really bad in my opinion, but I can live with that. I would prefer them to be the same color as background. 

Request: Please make the input boxes the same size as with the previous theme, so I can actually see what values am I putting in and the input box does not obscure the text. As seen on the screenshots above, currently it is barely usable in many places.

### Steps to reproduce the issue

1. Add a, input_datetime field, some text for it.
2. See that there is only few letters of text displayed. 
3. Cry. :)
...

### What version of Home Assistant Core has the issue?

core-2022.3.7

### What was the last working version of Home Assistant Core?

core-2022.2.x

### In which browser are you experiencing the issue with?

Firefox 98.0.2, Brave Version 1.36.122 Chromium: 99.0.4844.88, Mobile app

### Which operating system are you using to run this browser?

Linux, Android

**Comment by raqua** [comment]
I am also not keen about the date format change, but it was also off in previous version and it seems that it is tied to language used. I want to use HA in English, but have my local date format.

**Comment by raqua** [comment]
It has been 2 months since I reported this and there is nothing happening here. I know people are probably busy working on stuff, but I would at least like to get some response, like, yeah, we will think about it or nope, this is how we want this. 
Am I the only one who is bothered by this ? 
I want to report another issue, but it seems like it makes no sense to even report it.

**Comment by zsarnett** [comment]
We aren't moving from MWC Components. There may be some additional styling we can do

**Comment by raqua** [comment]
@zsarnett , thank you for the response. 
I am not really suggesting any technical solution, I just want to see the text that is there. If styling will do that, fine with me.

**Comment by raqua** [comment]
This is still an issue, should not be closed.

**Comment by raqua** [comment]
This is still an issue, should not be closed.

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
up

**Comment by nagtegaal** [comment]
This is still an annoying thing, even in 2025.3 beta...
Could we please fix this in core code?

I updated this to re-open, because this and [#11852](https://github.com/home-assistant/frontend/issues/11852) are now both closed, without the fact that this issue is solved or fixed properly.
The solution is already in the card_mod threat by Ildar_Gabdullin, see the link to the [forum post](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/3385), but needs to be updated inside the frontend (CSS) code.
