### ISSUE TITLE
Device selector acts differently when deselecting devices (design website)

### ISSUE THREAD

**Issue by Misiu** [home-assistant/frontend#12147]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Browsing the **design website** (https://design.home-assistant.io/#components/ha-selector) I've noticed that the Device picker acts differently than the Entity and Area picker.
You can select all the devices, but when you deselect a device the dropdown (select) stays visible:
![image](https://user-images.githubusercontent.com/1741838/160576050-c2ad8ae3-777c-4bdf-9bf6-8d984d957876.png)

### Describe the behavior you expected

When we deselect a device the component should behave the same way as Entity and Area selectors.

### Steps to reproduce the issue

1. Go to https://design.home-assistant.io/#components/ha-selector
2. Select all devices in `Multiples` section
3. Deselect all (using `X`)

### What version of Home Assistant Core has the issue?

https://design.home-assistant.io/#components/ha-selector

**Comment by zackbcom** [comment]
I am seeing the same issue using multiple devices in my blueprint. This is causing me to not be able to delete devices from the list. It does not register that they have been removed.

### Before
![image](https://user-images.githubusercontent.com/1888323/175789248-3e7adb4e-2e31-4e1b-8f0b-a5f2622d126f.png)

### After Remove (Save does not show up)
![image](https://user-images.githubusercontent.com/1888323/175789257-1ad645e2-48f2-487e-b2b0-b82cdc21b3fb.png)

**Comment by gonzotek** [comment]
This still seems to be an issue.  I'm trying to create a blueprint and coming across the same problem that zackbcom reported.  Misiu's steps to reproduce still causes the same result in the Home Assistant design website as well as my live 2022.6.6 instance (I know I'm a few versions behind now, so if it's been fixed, I'll update and this issue could be closed).
