### ISSUE TITLE
Media Player service call kills automation

### ISSUE THREAD

**Issue by hesspoint** [home-assistant/frontend#12150]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have 2 automations that I noticed do not complete as intended. I looked into the debug info and both show the same error

Stopped because an error was encountered at March 29, 2022, 07:51:58 (runtime: 6.87 seconds)

Stop failed: SendError=ApplicationNotFound, HandlerReturnStatus=Success

I looked into this more and noticed that for both the last action was to turn off my Sonos speakers. The action after that was never executed. In fact the Sonos speakers do stop / pause as they should. But everything afterwards stops. It is for sure this part because I moved the media stop service up and down in the automation and it always fails after this service call and it also does not matter what the next automation task is.

This is the service call in the automation:

service: media_player.media_stop
target:
  area_id:
    - bedroom
    - living_room
    - dining_room
data: {}

Btw: the automations used to work just fine until a while ago.

### Describe the behavior you expected

I would expect that after the media player service call is done that the next action in the automation continues 

### Steps to reproduce the issue

1. Run the automation
2. Check debug
3.
...

### What version of Home Assistant Core has the issue?

core-2022.3.8

### In which browser are you experiencing the issue with?

Safari on Mac, iOS and iPadOS

### Which operating system are you using to run this browser?

macOS 12.3, iOS 14.5

**Comment by Stooovie** [comment]
It is supremely annoying but try to use Pause instead of Stop. I know Spotify used to support Stop but now it requires Pause for some reason.
