### ISSUE TITLE
Allow Location Selector to place pin on Map instead of only allowing Dragging

### ISSUE THREAD

**Issue by KNXBroker** [home-assistant/frontend#12175]
### The problem

I have tested the new Tankerkoenig config flow. It uses the new location selector, nice! I have one issue which is a little bit annoying: The selector can only be moved on the map via drag and drop, it can not be placed somewhere else. Intuitive I would expect to be able to place the selector somewhere else by just clicking in the map.  This would be very helpful if the target coordinates are far away from the home location.

I think it is a core issue, if it is a Tankerkoenig or frontend issue please advise. 

Reproducing the issue:
- Add Tankerkönig integration.
- Try to select a station which is 1000km away

### What version of Home Assistant Core has the issue?

core-2022.4.0b0

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Core

**Comment by frenck** [comment]
This is indeed frontend related, moved the issue.
