### ISSUE TITLE
Casting energy metrics throwing error.

### ISSUE THREAD

**Issue by Bengarman** [home-assistant/frontend#12179]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using google cast to cast a dashboard we get the following error:
ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139963937655824] Received invalid command: recorder/get_statistics_metadata

After research it looks like its related to this PR.
https://github.com/home-assistant/frontend/pull/11892#issue-1155232086

### Describe the behavior you expected

The screen to be able to cast the energy dashboard.

It worked before updating today.

### Steps to reproduce the issue

1.Create a dashboard with energy cards
2.Cast the dashboard to a google cast device
3.Device doesnt show these cards correctly

### What version of Home Assistant Core has the issue?

2022.3.8

### What was the last working version of Home Assistant Core?

2022.1.?

### In which browser are you experiencing the issue with?

Google cast

**Comment by pszafer** [comment]
This API is available in 2022.4, not in 2022.3.x. I don't know the reason for it.

**Comment by Bengarman** [comment]
Thanks yep now I have updated issue resolved.
