### ISSUE TITLE
Everything is crooked after going to Lovelace

### ISSUE THREAD

**Issue by Xitee1** [home-assistant/frontend#12187]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I don't really know how to describe this. I have added screenshots below.
Everything just "hangs around".

Yesterday, everything was fine. Today I started up my PC and opened HA. Since then it is completely bugged.
I have updated HA yesterday, but it had no problems until today.

### Describe the behavior you expected

That HA is looking normal.

### Steps to reproduce the issue

1. Update HA core to the newest version
2. Turn off PC
3. Go to sleep
4. Power on PC the next day
5. Open HA
6. Go to Lovelace (It only happens if you go to Lovelace. In all other tabs like settings it does not occur. However, it will persits on the other sites like settings if you navigate to it, but will disappear on a site reload while in settings.)

### What version of Home Assistant Core has the issue?

core-2022.3.8

### What was the last working version of Home Assistant Core?

core-2022.3.7

### In which browser are you experiencing the issue with?

Google Chrome Version 99.0.4844.51 (Offizieller Build) (64-Bit), Firefox 98.0.2 (64-Bit)

### Which operating system are you using to run this browser?

Windows 10

### Additional information

![Screenshot_11](https://user-images.githubusercontent.com/59659167/161246889-4d06585f-2177-4bc1-bd17-185fcde3dc58.jpg)
![Screenshot_13](https://user-images.githubusercontent.com/59659167/161246910-1829b074-4656-4d72-b71c-865bce6e13db.jpg)
![Screenshot_14](https://user-images.githubusercontent.com/59659167/161246916-6cbc90eb-20a0-480c-a66b-546d08056102.jpg)

**Comment by stefanomosca1980** [comment]
April fools

**Comment by Xitee1** [comment]
> April fools

Just realised it. Completely forgot about that 😂😂
