### ISSUE TITLE
2022.4.0b1 dashboard elements are crooked

### ISSUE THREAD

**Issue by jsiemek** [home-assistant/frontend#12189]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Dashboard element are crooked as on attached images:
![crooked-1](https://user-images.githubusercontent.com/36767404/161255067-2e9aab80-757d-487f-a0dc-c6063dbed4c5.png)
![crooked-2](https://user-images.githubusercontent.com/36767404/161255069-d8edc3fe-49e0-422b-b077-2cfdf41040dd.png)
.

### Describe the behavior you expected

all elements to be straight ;)

### Steps to reproduce the issue

1. It just looks crooked after beta upgrade
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.4.0b1

### In which browser are you experiencing the issue with?

Chrome Version 100.0.4896.60 (Official Build) (64-bit) and FireFox 98.0.2

### Which operating system are you using to run this browser?

MacOS 12.3 and Windows 10 12H2 19044.1586

**Comment by drthanwho** [comment]
This is not becuase of beta but rather coming from card-mod

Thomas was explained why and apologised (not everyone found it funny unfortunately)

https://github.com/thomasloven/lovelace-card-mod/releases/tag/3.1.4

**Comment by frenck** [comment]
Closing, as this is not an Home Assistant bug or issue.
