### ISSUE TITLE
2022.4: unable to change the icon for update.* entities in the frontend

### ISSUE THREAD

**Issue by mbo18** [home-assistant/frontend#12198]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If I change the icon for update.* entities, it is not changed in the frontend

<img width="480" alt="Capture d’écran 2022-04-02 à 14 36 57" src="https://user-images.githubusercontent.com/12999535/161383648-3173481c-9522-45f3-b22c-03560dbf0d69.png">
<img width="408" alt="Capture d’écran 2022-04-02 à 14 37 25" src="https://user-images.githubusercontent.com/12999535/161383651-b64ae2f8-6c20-41a3-9910-a71586637614.png">

### Describe the behavior you expected

The displayed icon should be "mdi:update" instead of
<img width="54" alt="Capture d’écran 2022-04-02 à 14 38 56" src="https://user-images.githubusercontent.com/12999535/161383699-05c264ff-850f-4b9c-a41a-ce0d9ef471e2.png">
 

### Steps to reproduce the issue

1. Edit the UI
2. Edit an entity card and add an update.* entity
3. Change its icon
...

### What version of Home Assistant Core has the issue?

core-2022.4.0b3

### In which browser are you experiencing the issue with?

Safari and Firefox

### Which operating system are you using to run this browser?

macOS Big Sur

### State of relevant entities

```txt
auto_update: false
installed_version: 2022.4.0b3
in_progress: false
latest_version: 2022.4.0b3
release_summary: null
release_url: https://rc.home-assistant.io/latest-release-notes/
skipped_version: null
title: Home Assistant Core
entity_picture: https://brands.home-assistant.io/homeassistant/icon.png
icon: mdi:update
friendly_name: 'Home Assistant Core: Update'
supported_features: 11
```

**Comment by spacegaier** [comment]
This entity has an `entity_picture` set which takes precedence over the icon. Where is this entity coming from? Which integration?

**Comment by mbo18** [comment]
From the supervisor integration in 2022.4.0b3:
<img width="285" alt="Capture d’écran 2022-04-02 à 15 40 48" src="https://user-images.githubusercontent.com/12999535/161385968-2411e988-39aa-4cf8-a1b5-67dcfa5e86ed.png">

**Comment by mbo18** [comment]
Not really an issue, I've found that I can changed its icon from the UI:
<img width="494" alt="Capture d’écran 2022-04-02 à 15 50 49" src="https://user-images.githubusercontent.com/12999535/161386316-024ed198-7786-4433-8c1c-c9bffbe23997.png">

**Comment by spacegaier** [comment]
Yes, overall that is the intended behavior. The `entity_picture` by default has the priority, but you can enforce an icon in the dashboard card editor. So as you said, not an issue but working as designed.
