### ISSUE TITLE
tab refreshes without warning causing loss of info

### ISSUE THREAD

**Issue by magiva** [home-assistant/frontend#12200]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This happens on all pages but is most relevant for nodered and editing config pages.
If i decide that i need other information and then open another chrome/edge tab to find out how to do x or y then that takes a little time, when i click back onto the home assistant tab, it refreshes and current state is lost.
Saving is not always an option, and sometimes isnt possible for a lovelace card that doesnt validate.

### Describe the behavior you expected

i dont want it to refresh

### Steps to reproduce the issue

1. open nodered, config page or a lovelace card
2. open another tab and simulate time looking for something
3. after 5 minutes (ish) click back onto the home assistant tab, see it refresh 
...

### What version of Home Assistant Core has the issue?

2022.3.8

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

chrome & edge

### Which operating system are you using to run this browser?

windows 11

**Comment by mbo18** [comment]
Is this setting enabled in your profile: ` Automatically close connection `?

**Comment by magiva** [comment]
where do i see that ?
i checked in configuration.yaml, settings, server settings etc but i dont
see this ?

**Comment by mbo18** [comment]
Under notification in the menu:
![693D4A1B-5DA4-48D1-9C57-BD38A002190A](https://user-images.githubusercontent.com/12999535/161396339-ef393778-78a5-4e89-9eb1-395973cefa59.jpeg)
Where you can find the advanced setting:
![406EA780-2350-4A22-82DE-791B60EFFB51](https://user-images.githubusercontent.com/12999535/161396367-b418f4a1-da80-4c4c-9635-cbf8f4c0a71b.jpeg)

**Comment by magiva** [comment]
thanks for the pointer, yes that was ticked....now unticked.
many thanks
