### ISSUE TITLE
History graph shows wrong duration (1 month selected shows 1 week only)

### ISSUE THREAD

**Issue by g6094199** [home-assistant/frontend#12209]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

today (4/3/2022) when i set the history to show complete march (3/1/22 - 3/31/22) the history shows only the last week in march (3/24/22 - 3/31/22).

![Bildschirmfoto vom 2022-04-03 12-52-03](https://user-images.githubusercontent.com/37833326/161424309-040dbecc-7fd2-463e-b2c1-4fab4639d437.png)

### Describe the behavior you expected

the whole set time should be shown in the single graph and not only partial duration

### Steps to reproduce the issue

1. go to any history graph (tested with a power and temperature input)
2. set the beginning and end date to the last month and apply
3. only the week of the selected month will be shown 
...

### What version of Home Assistant Core has the issue?

2022.3.7, 2022.3.8

**Comment by ildar170975** [comment]
For how long does your Recorder keep the data?
Does it keep it for a month?
https://www.home-assistant.io/integrations/recorder/#purge_keep_days
