### ISSUE TITLE
Cannot Edit any Dashboards using Configuration/Dashboards

### ISSUE THREAD

**Issue by rmurfster** [home-assistant/frontend#12210]
### The problem

Get the error, "extra keys not allowed @ data['mode']. Got 'storage' extra keys not allowed @ data['url_path']. Got 'lovelace-...'".

If I try to modify any Dashboard through the Configuration/Dashboard menu (such as the Title, "Admin Only", or "Show in sidebar", I get the error, "extra keys not allowed @ data['mode']. Got 'storage' extra keys not allowed @ data['url_path']. Got 'lovelace-...".

I am using the GUI for Dashboard Configuration

**Replication Steps:**

1. Choose "Configuration" from Side Menu
2. Press "Dashboards"
3. Choose any Dashboard (except for "Overview")
4. Press "Update"

### What version of Home Assistant Core has the issue?

core-2022.3.2

### What type of installation are you running?

Home Assistant OS

### Additional information

I have the following Resources Installed:

- /hacsfiles/button-card/button-card.js?hacstag=146194325342
- /hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=303101606172
- /hacsfiles/lovelace-auto-entities/auto-entities.js?hacstag=1677445841101
- /hacsfiles/slider-button-card/slider-button-card.js?hacstag=3754399611103

The problem started after installing "slider-button-card" using HACS.  I cannot confirm that this caused the issue, only that I have edited my Dashboard Information before installing this add-on.

**Comment by Intecpsp** [comment]
I am no longer having this issue as of 2022.4.0/1
