### ISSUE TITLE
There are variables for Card Header font family and font size, but not font weight (--ha-card-header-font-weight)

### ISSUE THREAD

**Issue by melyux** [home-assistant/frontend#12211]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I'm writing a theme and wanted to make the Card Headers bold. For some reason, they are normal weight by default. However, I saw that there's no way to do this with themes! You can set `--ha-card-header-font-family` and `--ha-card-header-font-size`, but there is no `--ha-card-header-font-weight`.

See the default CSS below for the Header.

### Describe the behavior you expected

`--ha-card-header-font-weight` should be available as a theme variable.

### Steps to reproduce the issue

1. Look at the CSS for Card Headers.
2. See there is `--ha-card-header-font-family` and `--ha-card-header-font-size` but no `--ha-card-header-font-weight`.
3. That's it.
...

### What version of Home Assistant Core has the issue?

2022.3.8

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

All

### State of relevant entities

```txt
.card-header {
    color: var(--ha-card-header-color, --primary-text-color);
    font-family: var(--ha-card-header-font-family, inherit);
    font-size: var(--ha-card-header-font-size, 24px);
    font-weight: normal;
}
```

**Comment by zsarnett** [comment]
Feature requests should be moved to discussions. Thanks
