### ISSUE TITLE
Helpers lost some values to configure by UI compared to yaml

### ISSUE THREAD

**Issue by dreimer1986** [home-assistant/frontend#12214]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I need a few input_number values with a initial value. This can not be set by UI but very well by yaml. I got them by editing around in /.storage/input_number, but that is no real solution. This value is availbale for a few more you now can find in the new helpers section. Maybe these need some love too.

### Describe the behavior you expected

That all values can be edited.

### Steps to reproduce the issue

Just create a new helper like a input_number and try to select the initial value.

### What version of Home Assistant Core has the issue?

2022.4.0b4

### In which browser are you experiencing the issue with?

Any

### Which operating system are you using to run this browser?

Windows 11

**Comment by zsarnett** [comment]
This is a core issue. The configuration is create by the backend

**Comment by frenck** [comment]
Its not, core supports it. It lacks frontend UI.

**Comment by dreimer1986** [comment]
Exactly. Manually editing the value into the newly created config file for input-number, it works. But the UI does not allow to set it

**Comment by alvinchen1** [comment]
Hi, sorry, I am very new, and trying to learn, but not confident in contributing or submitting yet.  I believe the setting we are looking for would be in here:

[https://github.com/home-assistant/frontend/blob/dev/src/panels/config/helpers/forms/ha-input_number-form.ts](https://github.com/home-assistant/frontend/blob/dev/src/panels/config/helpers/forms/ha-input_number-form.ts)

input_number helper form should have an initial value option which matches the configuration implemented in core for the value initial

https://www.home-assistant.io/integrations/input_number/#initial
![image](https://user-images.githubusercontent.com/26409535/166172179-d1e1869e-b8da-4887-9897-dcdfffac482f.png)

This value sets a default value on reboot/shutdown. 

The counter helper form looks like it has a similar value

[https://github.com/home-assistant/frontend/blob/dev/src/panels/config/helpers/forms/ha-counter-form.ts](https://github.com/home-assistant/frontend/blob/dev/src/panels/config/helpers/forms/ha-counter-form.ts)
Relevant code includes line 30, line 43, line 51, and lines 110 - 117

An example of how counter renders shows the initial field.

![image](https://user-images.githubusercontent.com/26409535/166171742-61fefda6-8662-4a29-8dfe-edd723db21c9.png)

I've attached the code I think is right [input_number_initial.zip](https://github.com/home-assistant/frontend/files/8600245/input_number_initial.zip)
, but again, sorry, I'm not very confident.

After that, it also looks like we would need translations.
[https://github.com/home-assistant/frontend/blob/dev/translations/frontend/en.json](https://gith
ub.com/home-assistant/frontend/blob/dev/translations/frontend/en.json)

at line 1118 to copy line 1100 (basically copying the localized wording from Counter over to Input Number)

![image](https://user-images.githubusercontent.com/26409535/166172581-e9e364e0-7b1c-499b-b2ed-24821dd78176.png)

Of course, this would need to occur on all supported localizations.  I included en.json in the above zip file.

**Comment by erkr** [comment]
Yes, for example the 'Initial' option is missing in UI for several input helpers (Boolean, date time and number).
This forces me to continue using the yaml versions.

**Comment by bramkragten** [comment]
We explicitly choose not to include all possible options in the frontend. Some options are just to hard or confusing and can be better solved with other solutions.

If you want to still use it, you can always define them in YAML (you can use YAML and the UI at the same time)

**Comment by erkr** [comment]
@bramkragten 
I don't consider the initial value as confusing. That is the most prominent missing option for several helpers. 

> If you want to still use it, you can always define them in YAML (you can use YAML and the UI at the same time)

Don't understand? Helpers added via configuration.yaml are marked as read only in the UI helper menu.

**Comment by alvinchen1** [comment]
@erkr, as the person who wrote the code (my first submission!), and then got it reverted 😢, I can see both sides of this.  Now that @bramkragten and @frenck have explained the thought process behind it, I get it and understand why Frontend chose to omit this open (not just because it also caused a bug that I didn't foresee).  I didn't understand that before I wrote the code and committed it.


But I too was excited to see this come to UI and to be rid of it in YAML.  I can see the whole project is moving more and more towards UI, so I was happy to try and contribute and move this forward before realizing WHY this option wasn't chosen to be in UI.


Let me suggest as a workaround for you.  You CAN move these to UI from YAML and leave out the INITIAL value.  Then you could use an automation with the Trigger When Home Assistant ... Starts. to reset the values that you would have put in INITIAL.  I am with you, I have specific input_number entities that I want to have some flexibility with, but want them to revert to a set value at HA startup REGARDLESS of what their value was when HA shutdown.  I can totally see this being a very specific scenario and difficult to articulate.  


Hope that helps!

**Comment by erkr** [comment]
@alvinchen1 
I considered automations to initialise, but then maintaining these helpers in yaml is much easier. Additional automations like that just make the configuration more difficult to understand.

Both defining a fixed initial value at startup, or opt for restoring the value at shutdown, are both valid, mutual exclusive, use cases. Not hard to understand.

I advocate to not abandon them from the UI, but just clearly document the difference
