### ISSUE TITLE
input_number is truncated in UI at small step sizes

### ISSUE THREAD

**Issue by soxhi8** [home-assistant/frontend#12220]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Small step sizes (made possible by https://github.com/home-assistant/core/pull/56211) on input_number helpers are not displayed correctly in detail-cards in the frontend. Numbers are truncated to two decimal places.
![grafik](https://user-images.githubusercontent.com/4319345/161641550-0378b8ec-4a9f-4457-836c-6c997e27c03e.png)
![grafik](https://user-images.githubusercontent.com/4319345/161641567-41b8296a-b4f9-4f32-98bc-4f64cd3e7d73.png)

### Describe the behavior you expected

I expect to see the complete number with all decimal places that are populated/according to the given step size.

### Steps to reproduce the issue

1. Create helper input_number with a step size < 0.01, p.e. 0.0001.
2. Add the entity to a dashboard and change the value (change from slider to box-input for easier edit) to a number with more than two decimal places populated, p.e. 0.3116.
3. Close the detail-card and re-open it. The detail-card will only show two decimal places.

Notice: The error will not occur with two leading zeros in decimal places (0.001 will be shown correctly).

### What version of Home Assistant Core has the issue?

core-2022.3.8

### In which browser are you experiencing the issue with?

Firefox 98.0.2 (64-Bit)

### Which operating system are you using to run this browser?

Windows 10 21H2

### State of relevant entities

```txt
Initial state:
0.0
Initial attributes:
initial: null
editable: true
min: 0
max: 1
step: 0.0001
mode: box
friendly_name: SMALLnumber

Error state:
0.3116
Error attributes:
initial: null
editable: true
min: 0
max: 1
step: 0.0001
mode: box
friendly_name: SMALLnumber
```

**Comment by ildar170975** [comment]
Do not confirm:
```
input_number:
  test_number_very_small:
    min: 0
    max: 5
    step: 0.000001
    mode: box
    icon: mdi:car
```
![image](https://user-images.githubusercontent.com/71872483/177328601-c845f9bb-51d0-449b-8c10-6f514c84bcc9.png)

![image](https://user-images.githubusercontent.com/71872483/177328655-5bffff71-1992-434c-ad9d-8ae934d3e489.png)

![image](https://user-images.githubusercontent.com/71872483/177328774-0f715770-14c9-459b-a974-4b6083fdf2d4.png)

![image](https://user-images.githubusercontent.com/71872483/177328829-9062f151-fa96-4f66-9f76-da59dabf6585.png)

**Comment by soxhi8** [comment]
Thank you for testing my issue. @ildar170975 tested with leading zeros though, and as I noted in my initial report, leading zeros function correctly.
`Notice: The error will not occur with two leading zeros in decimal places (0.001 will be shown correctly).`
It still isn't completely resolved:
Testing on Home Assistant 2022.8.3 truncates the number in the input box, but shows the correct value next to it.
![grafik](https://user-images.githubusercontent.com/4319345/190901162-8aec7162-46af-4c89-a1b8-ca09bbba95b5.png)

Please consider reopening the issue.

**Comment by soxhi8** [comment]
The frontend also rounds up numbers while entering them:

1. Try to enter 0.2673
2. GUI will round from 0.26 to 0.27 when the 7 is entered after the 6

![grafik](https://user-images.githubusercontent.com/4319345/190901597-047bc63d-b4ee-4caa-bbd0-14c15abc2d9d.png)

**Comment by karwosts** [comment]
I can reproduce this. It works on some screens, but not others. For example it works as expected in an entities card, but when you click the input_number to bring up the more info, it uses the 2 digit truncation. 
![number](https://user-images.githubusercontent.com/32912880/207503057-9a3f277c-8c97-4874-9dd3-26edad8dc7d3.gif)

**Comment by karwosts** [comment]
Yeah this gets pretty bizarre. Here is me entering 0.5555555555.
![number2](https://user-images.githubusercontent.com/32912880/207507375-e58e2378-bc44-4b07-ba57-bd6cd3f05d71.gif)
