### ISSUE TITLE
ICON Picker shows no MDI Icon Preview since HA 2022.04.0

### ISSUE THREAD

**Issue by LuckyTriple7** [home-assistant/frontend#12239]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The MDI Icons are no longer visible in the ICON Picker ...

![image](https://user-images.githubusercontent.com/60685158/162044007-39fe6bff-51fe-4939-92ed-b312e550fb15.png)
![image](https://user-images.githubusercontent.com/60685158/162044319-f2579ca3-0a5f-4e7d-90ff-f7f9b96f7782.png)

when click and hold left Mouse Button,  Icon is visible ...

![image](https://user-images.githubusercontent.com/60685158/162045622-216ad93b-232e-43eb-ae8d-ef8fec67c0c9.png)

Tried with Chrome and Edge.
The Chrome Browser cache has been cleared.
EDGE Browser never used before to Access HA.

### Describe the behavior you expected

https://www.home-assistant.io/blog/2021/11/03/release-202111/#the-icon-picker

### Steps to reproduce the issue

1. Click on ITEM in Dashboard
2. Click on the Gear (Settings)
3. Click on Symbol
...

### What version of Home Assistant Core has the issue?

core-2022.04.0

### What was the last working version of Home Assistant Core?

core-2022.03.8

### In which browser are you experiencing the issue with?

Chrome 100.0.4896.60

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
All Entities are avaliable
```

### Problem-relevant frontend configuration

```yaml
NA
```

### Javascript errors shown in your browser console/inspector

```txt
no
```

### Additional information

no

**Comment by Plawasan** [comment]
Same issue for me:

![image](https://user-images.githubusercontent.com/73796046/162605945-fadf1538-c7f7-4e6c-b53e-14d0dc065a50.png)

**Comment by LuckyTriple7** [comment]
Works now in 2022.5.0b4
