### ISSUE TITLE
Updates appears multiple times

### ISSUE THREAD

**Issue by oz9els** [home-assistant/frontend#12240]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

update to WLED shows up 3 times ;-) 
Not a serious bug, just cosmetical..

### Describe the behavior you expected

Updates appears multiple times

### Steps to reproduce the issue

1. navigate to Configurations
2. waite for update
3. install update
4. still x-1 updates remains.

![image](https://user-images.githubusercontent.com/61284428/162055123-a547a626-f650-44f3-b31d-8970bc1ef378.png)

### What version of Home Assistant Core has the issue?

core-2022.4.0

### What was the last working version of Home Assistant Core?

core-2022.3.x

### In which browser are you experiencing the issue with?

Chrome - newest

### Which operating system are you using to run this browser?

Windows 10

**Comment by spacegaier** [comment]
Aren't those just three different WLED devices that each need the update or are you 100% sure that those are indeed all the same one?

**Comment by oz9els** [comment]
DOH.. @spacegaier, you are right ;-)
