### ISSUE TITLE
"Exclude"is not available in Homekit

### ISSUE THREAD

**Issue by Eirperuier** [home-assistant/frontend#12243]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I use "bridge" in homekit integration, I find that the "exclude" function is no longer available on most devices
![image](https://user-images.githubusercontent.com/60021832/162096564-88dbe9ba-c2be-4dc9-b9d1-6479e83370bf.png)
![image](https://user-images.githubusercontent.com/60021832/162096743-a40c20cc-c7ad-4161-a301-e982e46de205.png)

### Describe the behavior you expected

It should have been like this (there will be no such problem in using the include mode)
![image](https://user-images.githubusercontent.com/60021832/162096975-06eecd69-930c-42ed-bc1d-b7219d097677.png)

### Steps to reproduce the issue

1.Create a homekit integration
2.select "bridge" and "exclude" mode

### What version of Home Assistant Core has the issue?

core-2022.4

### What was the last working version of Home Assistant Core?

core-2022.3

### In which browser are you experiencing the issue with?

Edge 102.0.1216.0

### Which operating system are you using to run this browser?

Windows11

### Additional information

This is the information output from the console, but I don't know if it is related to the problem
![image](https://user-images.githubusercontent.com/60021832/162097598-55889150-6f70-422e-b5eb-6b1545300af4.png)

**Comment by rosshays** [comment]
I'm not seeing a dropdown at all to exclude specific entities.

**Comment by galbartal** [comment]
Not seeing the dropdown either
