### ISSUE TITLE
Firefox dashboard (lovelace) edit

### ISSUE THREAD

**Issue by jamesking210** [home-assistant/frontend#12255]
### The problem

when editing the dashboard in Firefox, you can't re-arrange entities but you can in chrome. (tested on Linux and Windows 10)

core-2022.4.0
supervisor-2022.03.5
Home Assistant OS 7.6

### What version of Home Assistant Core has the issue?

core-2022.4.0

### What type of installation are you running?

Home Assistant Core

**Comment by spacegaier** [comment]
I can confirm the issue, but have no idea why. There wasn't any recent change on the related source files. Also the dragging still works fine in Firefox in other areas, such as the shipping list card.

No errors in the browser log either.

**Comment by progman32** [comment]
Per request: Checked, still happening with latest release. Can't rearrange entries in Firefox - I've been manually editing the YAML as workaround.
