### ISSUE TITLE
No icon titles in 'Add-ons, BackUps & Supervisor' on mobile view

### ISSUE THREAD

**Issue by KNXBroker** [home-assistant/frontend#12263]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Menu 'Add-ons, BackUps & Supervisor' does not show icon titles in the menu tab on mobile view. 

![image](https://user-images.githubusercontent.com/25910703/162440456-7b0fa099-fa50-448b-8031-8fcc607b6e44.png)

### Describe the behavior you expected

Icon titles should be displayed

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2022.4b1

### In which browser are you experiencing the issue with?

Companion App

### Which operating system are you using to run this browser?

Android

**Comment by spacegaier** [comment]
Looks like the translation / lokalizeFunc fails here and therefore reverts to using the page name of the current page, which is why only the active tab has a name shown.

https://github.com/home-assistant/frontend/blob/dev/src/layouts/hass-tabs-subpage.ts#L93

**Comment by erkr** [comment]
I intermittently see something similar when re-opening my iOS app. But not only in the menus, also in the main page:
![image](https://user-images.githubusercontent.com/4363599/162616314-7a38d4be-32d3-4cbc-9af1-0f8931a72af0.jpeg)

**Comment by ludeeus** [comment]
Before we did not show it for the tabs that were not open, this has changed and it's shown always.
The frontend of the supervisor has been updated (but not yet released), and this will show there as well in an upcoming release of the supervisor.
