### ISSUE TITLE
Lovelace edit dashboard, add by entity crashes browser

### ISSUE THREAD

**Issue by benv666** [home-assistant/frontend#12264]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I'm trying to add a new card to my dashboard and was hoping to add by entity to see if HA would suggest a nice card for me.
However, when I go to the add by entity tab and type in a few letters to search, nothing seems to happen. After a while (while  my CPU goes hot) it crashes the entire HA tab.
![image](https://user-images.githubusercontent.com/165034/162441951-a2e90c71-0bcb-4896-af45-f63cd5568bdb.png)

### Describe the behavior you expected

The entity filter should be snappy and give me the filtered result without crashing.

### Steps to reproduce the issue

1. Edit Lovelace dashboard
2. Add card
3. Click the 'By Entity' tab
4. Enter a few characters in the search field and wait
...
![image](https://user-images.githubusercontent.com/165034/162442810-3db22d61-d0e4-48a8-9acd-93f6e8ff8475.png)

### What version of Home Assistant Core has the issue?

core-2022.4.1

### In which browser are you experiencing the issue with?

Google Chrome 100.0.4896.75 (Official Build) (64-bit) (cohort: Stable) 

### Which operating system are you using to run this browser?

Windows 11

### Additional information

Note that I have a LOT of entities due to Unifi generating rx/tx sensors for all connected devices etc, so I'm sure there are thousands of entries in that entity list.

**Comment by spacegaier** [comment]
What is "a LOT"? I have around 300 in my prod instance and that works fine (= instantly) in the same browser and browser version.

**Comment by benv666** [comment]
I'm not sure what the proper way is to count entities, didn't see it in the info pane, so I went to my HA docker container and did this:
```
bash-5.1# cat /config/.storage/core.entity_registry | jq -r '.data.entities | length'
2700
```
If there's a better way let me know, but I think it's a good indication.

The browser console doesn't show much, if I clear it and then open up the edit dashboard and go to the add by entities page (and wait for a few minutes):
![image](https://user-images.githubusercontent.com/165034/162567198-b3fb6fbe-0f56-470c-a295-c06ff81f9314.png)

Tried it in Firefox today, but doesn't seem to matter either.
Chrome:
![image](https://user-images.githubusercontent.com/165034/162567341-dbf9b88a-7391-4b76-ada1-0b8c61ca7966.png)

**Comment by spacegaier** [comment]
To count the easiest is to go to the HA dev tools "Template" tab and use that template:

`{{ states | count }}`

**Comment by spacegaier** [comment]
Your first screenshot shows that the exception was raised by a markdown card, so I assume that on the dashboard view where you wanted to add a new card, there was an existing markdown card shown?

**Comment by benv666** [comment]
The template gives me `3168`.
Just tried the same experiment with a fresh dashboard, same errors, so not sure if the the markdown card is causing issues. 
It seems a bit random, since just one of the three broke on that card - think it's just a matter of what triggers the OOM first.

That said, I can't find that specific file, thought I'd turn it off to see if it improves the situation, but don't know what card to disable. I'll give it a try with all custom frontend entries disabled, I'll post back once I've tried.

**Comment by benv666** [comment]
Well, I disabled all resources in `ui-lovelace.yaml` and restarted HA, tried again.
At first glance the entity search was instant, so I thought "Well, problem found!", but while I was typing in this tab my CPU was at 100% and memory was still spiking up until the HA tab died again from memory exhaustion:
![image](https://user-images.githubusercontent.com/165034/162573194-a3cb7609-14e5-4947-9d7e-97b72ddb99b6.png)
(note that the top of that screenshot shows the memory after crashing the tab, it was several GB before becoming unresponsive and getting killed)

So not sure if there's still stuff being loaded through different channels (since I didn't take them out of my dashboards), please advise if there's a "safe mode" or something to do this in a better way.
