### ISSUE TITLE
Basic "Group" missing from 2022.4 Helpers

### ISSUE THREAD

**Issue by HVR88** [home-assistant/frontend#12262]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Specific types of groups were added in 2022.4, including Lighting Groups, but basic Group (generic groups able to add any type of entity) is missing, making it impossible to combine Lights and Switches (and/or anything else) into the same group.

### Describe the behavior you expected

In addition to entity-specific groups, I expect to see "Basic Group" or "Generic Group" or "Group" (whatever you'd like to use as a label) for the base Group type in the Helpers.

### Steps to reproduce the issue

1. Select Helpers tab
2. Add New Helper
3. In list of helpers, select Group
4. Note in the list of group types there is no basic "Group" but only entity-specific groups

### What version of Home Assistant Core has the issue?

2022.4.1

**Comment by KNXBroker** [comment]
I'm also missing this 👍 But I'm afraid it's done on purpose...

**Comment by HVR88** [comment]
I'm looking to a future where 100% of HA's functionality is exposed through the UI. It doesn't make sense to me to add Groups to the UI but skip the base Group type. I'd also prefer to see Gouups moved out of helpers and into their own tab next to Scenes, but that's a battle for a different thread...

**Comment by emontnemery** [comment]
This is on purpose, the use of mixed groups is not encouraged because their state is very non-intuitive.
Note that it's now possible to make a switch appear as a light from the UI by changing the "show as" option.

You're welcome to open a feature request here: https://community.home-assistant.io/c/feature-requests/13

**Comment by HVR88** [comment]
I'll open a feature request instead.  There's nothing inherently non-intuitive about a group of devices each having on/off states being grouped together.

A coffee machine or air conditioner (on switches) are not lights, so it wouldn't make sense to convert their entities.  An actual light switch being marked by Home assistant as a Switch however is non-intuitive and having to manually add a helper to convert them to lights is equally non-intuitive - though I'm glad it's possible to apply such a fix nonetheless.

**Comment by emontnemery** [comment]
> I'll open a feature request instead.

👍 

>  I don't expect the base type is going to be removed from HA, is it

No, it won't be removed.

> There's nothing inherently non-intuitive about a group of devices each having on/off states being grouped together.

The problem is that you can't tell that group to, for example, dim all its lights to 50%.
For grouping devices by their location, you can consider using areas, which can then be used as a target in service calls.
