### ISSUE TITLE
TypeError: undefined is not an object

### ISSUE THREAD

**Issue by erkr** [home-assistant/frontend#12273]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since the 2022.4 update I noticed type errors in my log file. They appear when navigating in the UI.

### Describe the behavior you expected

I have seen the :0:0 Script error before, but  these type errors are new

### Steps to reproduce the issue

I don’t need to do anything special. Just opening the generated UI and going back to the log file seems enough

### What version of Home Assistant Core has the issue?

Core-2022.4.1

### What was the last working version of Home Assistant Core?

Core-2022.3.8

### In which browser are you experiencing the issue with?

iOS app

### Which operating system are you using to run this browser?

iPhone

### Additional information

Error in homeassistant.log:
Logger: frontend.js.latest.202204050
Source: components/system_log/__init__.py:190 
First occurred: 16:52:09 (43 occurrences) 
Last logged: 20:16:52

http://192.168.178.47:8123/frontend_latest/0d323de4.js:245:29110 TypeError: undefined is not an object (evaluating 'this._clusterConfigurationStatuses.get')
:0:0 Script error.

**Comment by spacegaier** [comment]
That has to be "zha" specific since `dialog-zha-reconfigure-device.ts` is the only place in the frontend coding where "_clusterConfigurationStatuses" appears.

**Comment by spacegaier** [comment]
@dmulcahey Could you have a look at that? You seem to the be author of that dialog. Looks there are scenarios where `_clusterConfigurationStatuses` is actually undefined.

**Comment by erkr** [comment]
I can confirm my initial addition was wrong. It's not related to navigating in the UI. After a few hours these errors stopped to occurred.
I had one zigbee device (ikea power plug) that didn't immediately reconnect after the update. It took hours before it was working normally.
I tried to operate the switch many times in the overview UI. Can that trigger the failing scenario?
Eric
