### ISSUE TITLE
Text Alignment Issue in Settings => Server Controls

### ISSUE THREAD

**Issue by jamespreedy** [home-assistant/frontend#12278]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In Configuration => Settings => Server Controls, the item "Groups, group entities and notify services" is centre aligned on Safari on iOS and also on the iOS app. All other items in the list are left aligned. On Safari on Mac it's correctly left aligned. I've included images from iPhone (wrong) and Mac (right) below.

![IMG_1154](https://user-images.githubusercontent.com/559531/162581519-84ab169b-e8e5-4165-8137-8c2b62729f2a.jpeg)

![Screenshot 2022-04-09 at 4 52 49 pm](https://user-images.githubusercontent.com/559531/162581555-e10ded1d-f7df-4ce5-baef-1047c76ee356.png)

### Describe the behavior you expected

The items "groups, group entities and notify services should be left aligned".

### Steps to reproduce the issue

Go to Configuration => Settings => Server Controls => YAML configuration reloading, look at items in the "YAML configuration reloading" section.

### What version of Home Assistant Core has the issue?

core-2022.4.1

### In which browser are you experiencing the issue with?

Safari on iOS 15.4.1

### Which operating system are you using to run this browser?

iOS 15.4.1

**Comment by spacegaier** [comment]
Nothing we can really do about that (other than centering all buttons by enforcing them to use the whole screen width), see my explanation here: https://github.com/home-assistant/frontend/issues/9910#issuecomment-913225154
