### ISSUE TITLE
Test button generates an error for valid template conditions

### ISSUE THREAD

**Issue by Plawasan** [home-assistant/frontend#12279]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The following condition works as expected and parses correctly in the template sandbox in developer tools

```
condition: template
value_template: >-
  {{((as_timestamp(now()) - as_timestamp(trigger.from_state.last_changed)) |
  int) > 5 }}
```

EDIT: Better example:
`{{((as_timestamp(now()) - as_timestamp(states.binary_sensor.door_terrace_contact.last_changed)) | int / 60 ) | int < 20 }}`

however using the new test button in visual editor generates an error:

**Error occurred while testing condition
template value should be a string for dictionary value @ data['value_template']. Got None**

### Describe the behavior you expected

Display correct test results

### Steps to reproduce the issue

1. create a template condition in an automation (can be as simple as {{ 1 == 1 }})
2. click the test button

### What version of Home Assistant Core has the issue?

core-2022.4.1

### What was the last working version of Home Assistant Core?

N/A

### In which browser are you experiencing the issue with?

Chrome Version 99.0.4844.84 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Linux 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by frenck** [comment]
This is expected behavior. As there is no trigger to get that variable information from.

**Comment by Plawasan** [comment]
My bad, wrong example used in the first report, but the issue is still valid

this should work irrespective of context, same as e.g. {{ 1 == 1 }} - still generates an error
`{{((as_timestamp(now()) - as_timestamp(states.binary_sensor.door_terrace_contact.last_changed)) | int / 60 ) | int < 20  }}`

**Comment by Plawasan** [comment]
Found an earlier report of this, closing as duplicate of https://github.com/home-assistant/frontend/issues/12282
