### ISSUE TITLE
2/3 of the Zones page is wasted with unused space.

### ISSUE THREAD

**Issue by sym0nd0** [home-assistant/frontend#12285]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Zones page is mostly wasted unusable space.

![HA_zone](https://user-images.githubusercontent.com/55590428/162623235-ae461f87-1572-4cdd-993e-2c6a52d23391.png)

### Describe the behavior you expected

The page real estate to be used efficiently, e.g. the map filling the page.

### Steps to reproduce the issue

1. Configuration
2. People & Zones
3. Zones

### What version of Home Assistant Core has the issue?

core-2022.4.1

### In which browser are you experiencing the issue with?

Microsoft Edge Version 100.0.1185.36 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11 Home 21H2

### Additional information

If the map did fill the full page, it would be far easier for users when defining zones, especially their radius.

**Comment by mcv93us** [comment]
I also have the same problem.
This bug has existed since version 2022.4.0, even with the latest version 2022.4.6 nothing has changed.
I use Chrome 100.0.4896.127 under Windows 10 (21H2) but even switching to Firefox the problem remains.

**Comment by kirillovserg** [comment]
And I have the same problem.
I checked in different browsers - Yandex, Firefox, Chrome.
Home Assistant 2022.4.7

**Comment by zsarnett** [comment]
This will be fixed in 2022.5
