### ISSUE TITLE
Removing device_tracker from person does not work on iOS 

### ISSUE THREAD

**Issue by LarsStegman** [home-assistant/frontend#12280]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Removing a device from a person does not work in iOS companion app and in iOS mobile Safari. 

### Describe the behavior you expected

Device can be removed

### Steps to reproduce the issue

1. Open person pop up
2. Tap on the X in the field to remove the device 
3. The field is cleared, but does not disappear
4. Close the pop up
5. Open the person pop up again
6. The field has the "removed" value again and the device is still used to track the person

### What version of Home Assistant Core has the issue?

2022.4

### In which browser are you experiencing the issue with?

Safari on iOS 15.4.1 and Home assistant companion app

### Which operating system are you using to run this browser?

iOS 15.4.1

### Additional information

On macOS removing the device works properly

**Comment by Thauxeeb** [comment]
I'm experiencing the same issue, with iOS and iPadOS Safari, Firefox on Win11 seems to work.

**Comment by TrixieMango** [comment]
Same issue here. It is also a problem when trying to remove a sensor from one of the new helpers (min/max/median etc)

**Comment by LarsStegman** [comment]
No, not solved

**Comment by LarsStegman** [comment]
It's fixed!
