### ISSUE TITLE
Inconsistent close button placement on media picker

### ISSUE THREAD

**Issue by bmesuere** [home-assistant/frontend#12297]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

All dialogs in home assistant have the close button op the top left. The new media picker, however, has the close button on the top right of the dialog.

In addition, existing dialogs close if you click on the backdrop but the media picker doesn't.

### Describe the behavior you expected

A consistent experience, especially for newly added features.

### Steps to reproduce the issue

n/a

### What version of Home Assistant Core has the issue?

core-2022.4.1

### In which browser are you experiencing the issue with?

Chrome 101.0.4947.0 (Official Build) dev (arm64)

### Which operating system are you using to run this browser?

MacOS Monterey 12.3

**Comment by bmesuere** [comment]
This is still an issue.

**Comment by matthiasdebaat** [comment]
More details about more consistent dialogs https://github.com/home-assistant/frontend/issues/13084

**Comment by bmesuere** [comment]
Things have greatly improved over HA as a whole, but the 2 issues reported here are still present.
