### ISSUE TITLE
Unable to select members of 2022.4 Groups Helper in Chrome

### ISSUE THREAD

**Issue by Mattie112** [home-assistant/frontend#12307]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am unable to select group members in Chrome. I seem to interact with the 'background'.

### Describe the behavior you expected

I expect the dropdown to work.

### Steps to reproduce the issue

Config -> Automation & Scenes -> Helpers -> Add -> Group -> Light group

Then I can open the entity dropdown but I cannot select an entry. Whenever I click (in the dropdown) in the same place as where the question mark icon is in the background I go to the help page.

### What version of Home Assistant Core has the issue?

core-2022.4.2

### In which browser are you experiencing the issue with?

Chrome 100.0.4896.75

### Which operating system are you using to run this browser?

Windows 11

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

![gifje](https://user-images.githubusercontent.com/662896/162800246-bcdcde6d-5fae-408a-9a93-8ce6226df849.gif)

Chrome 100.0.4896.75
It DOES work in Edge for example.

## System Health

version | core-2022.4.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.103-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.04.0
docker_version | 20.10.9
disk_total | 111.1 GB
disk_used | 13.8 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.3.0), Grafana (7.5.2), InfluxDB (4.4.1), Z-Wave JS (0.1.55), File editor (5.3.3), Glances (0.15.0), Studio Code Server (4.2.0), AppDaemon (0.8.2), Mosquitto broker (6.0.1), ESPHome (2022.3.1), Log Viewer (0.13.0), TasmoAdmin (0.17.0), SSH & Web Terminal (10.1.1), Home Assistant Google Drive Backup (0.106.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

**Comment by spacegaier** [comment]
Works fine for me in Chrome 100.0.4896.127 with 2022.4.3 or the latest HA frontend dev version. So either already fixed or not reproducible for me 😄

**Comment by zsarnett** [comment]
Can you upgrade to the lastest patch and see if this is still an issue?

**Comment by Mattie112** [comment]
Yes it seems to be resolved, thanks!
