### ISSUE TITLE
Error with timezone?

### ISSUE THREAD

**Issue by Smandurlo** [home-assistant/frontend#12302]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am in Italy and I was checking the log of another HA istance in Portugal. Portugal timezone is -1 hour.
Timezone is ok into the configuration.yaml (time_zone: Europe/Lisbon), the system shows correct time, but when I check the log of my entity status, I see the status have the Rome timezone.

I think with a pic is more clear:
![2022-04-11](https://user-images.githubusercontent.com/36647269/162740712-c44bda49-1ce2-4ec4-9208-6a9a92aad5c4.png)

In Italy (windows clock) it is 14:29 (2:49 p.m.) and the system log (portugal timezone) shows the same time. It is impossible, in Portugal is 13:49 (1:49 p.m.).

### Describe the behavior you expected

The log should be in Portugal/HA timezone.

### Steps to reproduce the issue

Just open a history log from a computer with different timezone.

### What version of Home Assistant Core has the issue?

2022.4

### What was the last working version of Home Assistant Core?

no idea, I noticed it only today.

### In which browser are you experiencing the issue with?

I tried different browser and Android app

**Comment by Smandurlo** [comment]
well, I still have the same issue... no one took care of it.

**Comment by frenck** [comment]
Why didn't you respond to the bot 7 days ago? 🤷

**Comment by Smandurlo** [comment]
I am sorry, I am on holiday. I saw it while going to the beach and I totally forgot to reply. Could you please open it again?
I am in Spain now, same timezone as Italy: 15:43 (3:43 p.m.) and the log in the pic is from Portugal (one hour less 14:43 2:43 p.m.)
<img width="256" alt="2022-07-17" src="https://user-images.githubusercontent.com/36647269/179401275-88996200-abeb-42dd-beec-0f58e210085c.png">

**Comment by Smandurlo** [comment]
I am on 2022.7.5 now

**Comment by Smandurlo** [comment]
UP, still the same issue

**Comment by mrfixit1** [comment]
Anyone with programming skills prepared to pick this up? This issue is still open and it's also a FR in the forum, see e.g. https://community.home-assistant.io/t/wth-is-there-no-option-for-using-the-server-timezone/467371. I was recently away from home and noticed that the energy dashboard was shifted to local time, in my case by several hours. In my opinion this is a bug, not new functionality.

**Comment by Smandurlo** [comment]
Finally someone saw my problem 😅

**Comment by SgtBatten** [comment]
Lots of us saw it, we just responded to a forum post not this bug report.

**Comment by Smandurlo** [comment]
Actually, to me it is a bug, not something to discuss in a forum post.

**Comment by Lenbok** [comment]
Isn't this fixed as of 2023.7 release?

**Comment by bramkragten** [comment]
Yep!
