### ISSUE TITLE
Dateselector don't let you select a date before 01.01.1970

### ISSUE THREAD

**Issue by edenhaus** [home-assistant/frontend#12329]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The custom component [bodymiscale](https://github.com/dckiller51/bodymiscale/) uses the new selectors for the config flow.
To insert the birthday, I choose to use the date picker, but unfortunately it don't let you select a date before 01.01.1970.
This bug was originally reported in https://github.com/dckiller51/bodymiscale/issues/78

This min value is hardcoded in the source code:
https://github.com/home-assistant/frontend/blob/4fc2c3ef059827e858192d626ae58c495a21c9ef/src/components/ha-date-input.ts#L59

@bramkragten Is there a technical reason for this specific min value?

### Describe the behavior you expected

I expected to select any valid date also a date before 01.01.1970

### Steps to reproduce the issue

1. Open https://design.home-assistant.io/#components/ha-selector
2. Scroll down to date picker
3. Try to select the date 01.01.1950

Another way:
1. Install custom component [bodymiscale](https://github.com/dckiller51/bodymiscale/) via HACS
5. Start to setup up the component via UI
6. Try to select the date 01.01.1950

### What version of Home Assistant Core has the issue?

core-2022.4.3

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

OS-indepented

### Additional information

I think the best is, when we add the `min/max` config options to the date selector, so the component developer can decide, which date range he would allow.
E.g. In the usecase above of the birthday, I could limit that the user is only allowed to insert a date from the past.

**Comment by lazodar** [comment]
Sorry, I should have made a proper issue with all the data included. My apologies!

**Comment by steverep** [comment]
i'm sure this restriction had something to do with the [JavaScript `date` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date), which measures time from 1/11970 UTC, but yeah a silly limitation.
