### ISSUE TITLE
Zigbee Visualization Issues

### ISSUE THREAD

**Issue by alexruffell** [home-assistant/frontend#12322]
### The problem

Lately I have been working on fixing Zigbee issues that started with 2022.4 update. I changed from a Conbee II coordinator to the Sonoff Zigbee 3.0 USB Dongle Plus. I added back all my devices and I now have some devices that repeatedly drop off the network in the same area of the house so I am hunting for what I am guessing is a bad repeater using the visualization screen. This issue is not new but is now more annoying given how frequently I look at the visualization screen.

The issue is that when you access the visualization page from a device, it stop working shortly after. In other words, you cannot zoom in and out, move the map, or drag the devices. What appears to work is to immediately click on groups and then back to Visualization as that clears the "Zoom to device". If you try to X the device, it simply comes back... I tried a dozen times and it kept popping back up. I also did not know what "Enable Physics" was as it rarely worked. Now that I access it using the trick above, I see it work. Disabling the "Auto Zoom" seemed to help at times but it ends up failing.

Using the scroller on the mouse to zoom in and out stops working as well and it just makes the screen twitch for lack of better words.

Sometimes, if you try to drag a device in the middle of the map, it takes you to full zoom in showing one device in the middle of the screen that you cannot move or if you can, it is really not responding to the commands from the mouse (such as zoon out)... it just wobbles while you try to drag it.

Please let me know what technical details are needed to troubleshoot this. For obvious reasons it is hard to use the visualization on a mobile phone, however I seem to have the same issue there (or similar).

Glad to share a screen recording but I would prefer to do so privately.

### What version of Home Assistant Core has the issue?

core-2022.4.3

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

ZHA

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/zha/

**Comment by alexruffell** [comment]
I shared the video recording of the bug to you privately. I emailed you at the email on your Github profile. Hope you don't mind me doing so.

**Comment by alexruffell** [comment]
I just noticed that if you enter the visualization screen without a device zoomed in, and you then pick a device it appears to work properly. When you pick the device from the drop down, it is not persistent (as in the device name vanishes from "Zoom to device" box once it zoomed to it) and does not appear to suffer from the bug. When you access the screen from a device, the device is persistent in the "Zoom to device" drop down and the bug manifests.

**Comment by alexruffell** [comment]
bump... to keep it from getting closed for inaction.

**Comment by schattenphoenix** [comment]
As of today I still have this issue
Even when not going from a device selected, it sometimes happens after clicking a few devices that zoom and pan resets to the original position of the device that was last clicked and it's basically impossible to navigate.
![image](https://user-images.githubusercontent.com/22476644/222994124-185dd0be-447c-4372-a7f0-ba0e952b7aaa.png)

Sorry to necro this, but I felt it was appropriate given the issue is described in

**Comment by alexruffell** [comment]
Yes, I still have the issues too. I just gave up using the visualization tool for more than a quick look.

**Comment by udivankin** [comment]
Maybe It would be possible AutoZoom and Physics checkboxes to keep their states? I find this issue very annoying.

**Comment by AndySymons** [comment]
So what does "enable physics" actually mean?

**Comment by MedicoreV8** [comment]
> So what does "enable physics" actually mean?

I have been wondering the same thing. What the hell is the reasoning behind adding this functionality?

why not cluster/group based on either LQI or hierarchy or maybe even estimated location in physical space on a 2D plane

**Comment by lindhe** [comment]
> So what does "enable physics" actually mean?

It seems that, when physics is enabled, nodes in the graph will collide with each other and slide away if you click-and-drag them into each other. And maybe also some "gravity" that pulls the network apart so it's somewhat spread out. At least this is what it looks like to me.

**Comment by lindhe** [comment]
I still think that the visualization page is not a great user experience. @balloob should I post a new issue or do we reopen this one?

**Comment by alexruffell** [comment]
@lindhe I agree, the issue got even worse where my phone, and my browser both freeze up after a short while when moving stuff around. I like to review the visualization but the autozoom and physics, with the current issues, make it impossible to use. Instead of autozoom, I would prefer the UI would highlight the node and let me do what I need to (usually I have to move it around to see the various paths so highlighting those would be nice too). The physics feature is fun but unnecessary other than repositioning the nodes so you don't end up with a mess when reviewing and/or moving stuff around. A simple button press to lay the nodes out again would be even better albeit less fun to watch.
