### ISSUE TITLE
Can't add new card via GUI

### ISSUE THREAD

**Issue by Luki72** [home-assistant/frontend#12335]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I click on the + ADD CARD button the cards list is empty:

![image](https://user-images.githubusercontent.com/22493116/163625855-eaf0b659-b638-4492-9961-6f46e636199d.png)

### Describe the behavior you expected

I expect the list of all cards installed via the base system or via HACS.

### Steps to reproduce the issue

Just click on + ADD CARD button.

### What version of Home Assistant Core has the issue?

2022.4.4

### In which browser are you experiencing the issue with?

Brave Browser Version: 1.37.116 Chromium: 100.0.4896.127

### Which operating system are you using to run this browser?

Debian GNU/Linux testing

### Additional information

This happens on my android tablet and android phone too.
Existing cards on all dashboard and tabs cab be edited via GUI.

**Comment by spacegaier** [comment]
Any errors in your browser log? Do you have any custom cards installed that could potentially interfere here?

**Comment by Luki72** [comment]
I can not check browser's log, but there's nothing in HA's log related to this error. There are many custom cards installed in my HA but which one is stupid? I have no idea. I removed some unused and unnecessary cards but still the same situation.

**Comment by schmic79** [comment]
I have the same issue (HA 2022.11.2 on HAOS 9.3 raspi3) ... and I also have no solution.

Installed Add-ons:
HACS
Glances
RaspberryMatic CCU
Samba Backup
Samba Share
SSH & Web Terminal
Studio Code Server

Tested in 2 Browsers: Firefox & MS Edge (Chromium) - even after deletion of cache no success

"Add by Entity" shows a list, but "Add by card" shows nothing. Not even the search field ....
