### ISSUE TITLE
Copying the long lived is harder than it looks

### ISSUE THREAD

**Issue by erwinlem** [home-assistant/frontend#12341]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have trouble copying the long-term access token.
It's hard to copy, if you select it the entire token might not be selected. And since the input field  is so small that is not clear.  I think my browser sees the period or other symbols as a separator.

### Describe the behavior you expected

To have the token on my clipboard

### Steps to reproduce the issue

1. User -> long-lived access token -> generate
2. Copy the token

### What version of Home Assistant Core has the issue?

7.6

### Additional information

Could you make it a text area or something? Or add a copy button.
I was not the first one to make this mistake (Thank god, I almost fell like a simpleton.)

https://community.home-assistant.io/t/simpleton-help-with-api-access-401-unauthorized/320119/2

**Comment by matthiasdebaat** [comment]
Would be nice to have a `mdi:copy-content` icon in the input

**Comment by Syntoxr** [comment]
Agree,
double click copies only one part (separated by period). Which is how double click should work: marking the current sentence, but is unfortunate for long JWT's.
There already is a "Generate QR-Code" button, so a copy button should be a no-brainer...

**Comment by LAB02-Admin** [comment]
+1

Multiple users of HASS.Agent (Windows HA client) experienced difficulties with this, thinking they selected the entire key with CTRL+A or doubleclicking.
