### ISSUE TITLE
Vacuum state missing in the more-info dialog

### ISSUE THREAD

**Issue by yangqian** [home-assistant/frontend#12342]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Should show  `Status: Docked `
<img width="390" alt="correctscreenshot" src="https://user-images.githubusercontent.com/5144644/163992094-4a410a29-9954-4bee-acea-33fe035a866e.png">

### Describe the behavior you expected

Instead show `Status:  `. 
There is no way of knowing the current state of the vacuum if StateVacuumEntity is implemented instead of the legacy VacuumEntity.
<img width="374" alt="wrongscreenshot" src="https://user-images.githubusercontent.com/5144644/163912664-0f183aa6-746f-46c6-ad50-be52dabaf077.png">
### Steps to reproduce the issue

1.  add a vacuum entity via mqtt
2. add it to the dashboard
3. click on icon to get to the more-info dialog

### What version of Home Assistant Core has the issue?

core-2022.4.4

### In which browser are you experiencing the issue with?

Firefox 99

### Which operating system are you using to run this browser?

macOS Montery 12.3.1

### State of relevant entities

```txt
vacuum.valetudo_XXX
State: docked
Attributes:

fan_speed_list: min, low, medium, high, max
battery_level: 100
battery_icon: mdi:battery-charging-100
fan_speed: medium
friendly_name: robovac
supported_features: 8956
```

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - vacuum.valetudo_XXX
```

### Additional information

Somehow, the more-info is trying to show the status attribute of the vacuum.
See:
https://github.com/home-assistant/frontend/blob/511368da13fb07d12d1fc7d217dbd9a7ff68736c/src/dialogs/more-info/controls/more-info-vacuum.ts#L122

Replacing the above line with 
```html
<span><strong>${stateObj.attributes.status || this.hass.localize("component.vacuum.state._."+stateObj.state) || stateObj.state}</strong></span>
```

solved the problem for me and is a nonbreaking change.

The mqtt vacuum I use shows the state through the state of the vacuum and there is no status attribute.

**Comment by zsarnett** [comment]
The Vacuum should not support status in this case so that it will not be shown. We check if it supports using Supported Features Attribute.

**Comment by yangqian** [comment]
My current understanding is that the status attribute is deprecated and has been replaced by the state.
So it is not a legacy vacuum, it should show the state instead of the status.

**Comment by yangqian** [comment]
@zsarnett 
My current understanding is that the “status” attribute is deprecated and has been replaced by the “state”.
The StateVacuumEntity should eventually replace the legacy VacuumEntity.
So if it is not a legacy VacuumEntity, it should show the state instead of the status.

**Comment by zsarnett** [comment]
We should fall back to the status then. Still if your vacuum is saying it supports status when it shouldn't that is still an issue
