### ISSUE TITLE
Script Editor UI Bug

### ISSUE THREAD

**Issue by Daniel-dev22** [home-assistant/frontend#12347]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am expecting to see all of the options clearly. In the automation editor If I create an action for ```light.turn_on``` I see all of the options. However when I do create an action in a script the bottom options are just ```*```. 

Initially this appeared to only occur on the android app however it is also occuring on chrome.

I say initially because I have a screenshot from a few days ago of it working on chrome but not the app and now both don't work. I didn't modify anything to cause that.
![Screenshot_20220418-052218_Home Assistant](https://user-images.githubusercontent.com/47092714/163788025-945e9612-5417-4fc4-9f30-daac2d95d14a.jpg)
![Screenshot_20220418-052224_Home Assistant](https://user-images.githubusercontent.com/47092714/163788031-475074a0-bf3c-4a70-9028-5d8afbef92bc.jpg)
![Screenshot_20220418-052246_Home Assistant](https://user-images.githubusercontent.com/47092714/163788032-cc44520f-9fb2-4400-af50-19937b4da423.jpg)
![Screenshot_20220418-052254_Home Assistant](https://user-images.githubusercontent.com/47092714/163788034-249b4729-dfcb-4dd9-a542-b6a722da69ec.jpg)
![Screenshot_20220418-052307_Home Assistant](https://user-images.githubusercontent.com/47092714/163788036-8f99fae3-67d8-47b2-a68d-01e765087a59.jpg)
![Screenshot_20220418-052313_Home Assistant](https://user-images.githubusercontent.com/47092714/163788037-5d74850f-3ab3-46da-8547-fbbd09ca2916.jpg)
![Screenshot_20220418-052323_Home Assistant](https://user-images.githubusercontent.com/47092714/163788040-ed248906-5ec9-4937-853c-cb99615a7422.jpg)
![Screenshot_20220418-052327_Home Assistant](https://user-images.githubusercontent.com/47092714/163788041-90ebf5c5-236a-4fe7-9a78-5c9d1c71c73d.jpg)
![Screenshot_20220418-052332_Home Assistant](https://user-images.githubusercontent.com/47092714/163788043-39bf041e-910c-4963-b496-ff9ea838fad7.jpg)

When it worked on the browser. Now it looks the way the app does.
![Screenshot_20220416-194546_Chrome](https://user-images.githubusercontent.com/47092714/163788186-6ded5d69-bfa2-4f25-b5d1-cc51cd64d525.jpg)

### Describe the behavior you expected

To be able to read every option in the script Editor. This only occurs in the app.

### Steps to reproduce the issue

1.Open Mobile App
2.Go to Script Editor
3.Action -> Service -> Light.turn_on -> scroll to view the options
...

### What version of Home Assistant Core has the issue?

2022.4

### Which operating system are you using to run this browser?

Android 12

**Comment by zsarnett** [comment]
This should be resolved in the next major release. https://github.com/home-assistant/frontend/pull/12241

**Comment by tgcowell** [comment]
All,

I'm not sure if there is something else specific to HA going on here? I cannot replicate this issue across any browser or app... I'm running v2.2.0 of Waves.

Cheers
