### ISSUE TITLE
Area not available after being created in integration, only after retry is it available

### ISSUE THREAD

**Issue by fribse** [home-assistant/frontend#12353]
### The problem

When you create a new Area in an integration drop down, the area is not available until next time you open the integration.
I just created a HA on a RPi4-4GB as a demo, and when setting up a device in an integration, the area can be set, if the area is not created yet, there is an option to create area. When you use that option, the area is not available until next time you open the device.
In my case it was chromecast, but it's a general issue I think.

### What version of Home Assistant Core has the issue?

core-2022.3.1

### What was the last working version of Home Assistant Core?

Unknown

### What type of installation are you running?

Home Assistant Core

### Integration causing the issue

Chromecast

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/cast/

**Comment by fribse** [comment]
Hi @emontnemery
You beat me to it, yes, that is exactly the issue.
I'm not able to retest it for a few days, as I'm currently traveling.

**Comment by jmerdich** [comment]
This also seems to be an issue for the Hue integration.
