### ISSUE TITLE
 null is not an object (evaluating 'e.hass.config.location_name')

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#12372]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

error in the Inspector console

### Describe the behavior you expected

no error

### Steps to reproduce the issue

1. really dont know, happening on all pages
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.5.0.dev20220421

### What was the last working version of Home Assistant Core?

?

### In which browser are you experiencing the issue with?

Safari, Chrome

### Which operating system are you using to run this browser?

MacOS  Monterey 12.2.1

### Javascript errors shown in your browser console/inspector

```txt
TypeError: null is not an object (evaluating 'e.hass.config.location_name')
(anonieme functie) — 14f311db.js:1:12122
asyncFunctionResume
(anonieme functie) — ha-app-layout.js:101
asyncFunctionResume
(anonieme functie)
promiseReactionJobWithoutPromise
promiseReactionJob
```

### Additional information

Safari:
<img width="954" alt="Schermafbeelding 2022-04-21 om 11 54 17" src="https://user-images.githubusercontent.com/33354141/164429957-939e4bd3-31a8-4b6e-a549-c8764c13ec23.png">

Chrome:
<img width="675" alt="Schermafbeelding 2022-04-21 om 11 59 24" src="https://user-images.githubusercontent.com/33354141/164430904-bfcffe33-ec07-43e7-a0f0-2e924364b491.png">

might be related to Browser_mod, though not sure of the cause/messenger

see: https://github.com/thomasloven/hass-browser_mod/issues/318

**Comment by zsarnett** [comment]
This could be due to the configuration menu changes I have making. Ill see if I can reproduce with the new changes

**Comment by Mariusthvdb** [comment]
thanks!

its not a very new error I am afraid, but unfortunately I cant find an earlier posting of mine on the subject...
really sorry about that, let men know if I can help to debug/test

**Comment by Mariusthvdb** [comment]
this is new (in error-badge)?:
<img width="1164" alt="Schermafbeelding 2022-04-27 om 13 43 20" src="https://user-images.githubusercontent.com/33354141/165511048-c7674cde-d54c-4a23-a82c-32eb5eb699e2.png">

**Comment by Mariusthvdb** [comment]
<img width="1167" alt="Schermafbeelding 2022-04-28 om 22 40 44" src="https://user-images.githubusercontent.com/33354141/165841958-76e392ab-61f2-4875-8144-d64b67fc9dd3.png">

I just tried once more to tie it to a card or menu item, but even with a completely empty view, and all card-mod-themes disabled, the error persists....

**Comment by bramkragten** [comment]
This seems related to `browser_mod` please create an issue in the repo for that integration.
