### ISSUE TITLE
Change and update popup

### ISSUE THREAD

**Issue by alex2beard** [home-assistant/frontend#12371]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The pop-up window with data about changing and updating object data on mobile devices (browser and application) has ceased to be displayed.
![image](https://user-images.githubusercontent.com/77844696/164396527-1af67ba7-a365-4e2c-b8ef-15af09d6fef6.png)

### Describe the behavior you expected

When you clicked on the data change time object, a pop-up window appeared with the data update time.

### Steps to reproduce the issue

1. Open object
2. Open its control
3. Click on change time

### What version of Home Assistant Core has the issue?

core-2022.4.5

### In which browser are you experiencing the issue with?

Edge 100.0.1185.43 and Home Assistant Companion for Android 2022.3.0-full

### Which operating system are you using to run this browser?

Android  12

### Additional information

I first created isue in Home Assistant Companion for Android, but it was closed and advised to create it here, since the problem also manifests itself in the browser
https://github.com/home-assistant/android/issues/2409

**Comment by spacegaier** [comment]
Yes, currently none of our `paper-tooltips` work on mobile / touch based devices. We need to discuss how to handle that.

Similar to https://github.com/home-assistant/frontend/issues/12141.

**Comment by alexfrolkin** [comment]
It was possible to achieve the appearance of a window, it is necessary to set it for selection, after that the window may appear, but it does not always work.  It also does not respond to pressing.

https://user-images.githubusercontent.com/77844696/165896255-348af649-3248-4e0f-afb8-c2eab2e4b456.mp4

**Comment by alexfrolkin** [comment]
The problem is still relevant, the pop-up window does not appear when clicking.  I have attached a video in a previous comment.  Updating to the latest version does not solve the problem.

**Comment by alexfrolkin** [comment]
Обновление до последней версии так и не помогает решить проблему.

**Comment by alex2beard** [comment]
Any ideas ?

**Comment by alex2beard** [comment]
Updating to the latest version still doesn't fix the issue.
