### ISSUE TITLE
Dropdown Overlays too tall

### ISSUE THREAD

**Issue by smiller171** [home-assistant/frontend#12376]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When enough entries are present, dropdown overlays can be too tall, creating a visual bug, and I believe overflowing the first entry entirely behind the address bar

### Describe the behavior you expected

Dropdown Overlay should not extend beyond the height of the viewport

### Steps to reproduce the issue

1. Open the settings for badges on a dashboard
2. Click the `Entity` text box`
3. Observe that the dropdown overlay extends beyond the viewport.

### What version of Home Assistant Core has the issue?

2022.4.6

### In which browser are you experiencing the issue with?

Google Chrome Version 100.0.4896.88 (Official Build) (x86_64)

### Which operating system are you using to run this browser?

macOS Monterey (12.3.1)

### Problem-relevant frontend configuration

```yaml
- title: Basement
    path: basement
    badges: []
    cards:
      - type: media-control
        entity: media_player.50_tcl_roku_tv
```

### Javascript errors shown in your browser console/inspector

```txt
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

__patchWheelOverScrolling	@	vaadin-combo-box-scroller.js:51
ready	@	vaadin-combo-box-scroller.js:51
_enableProperties	@	typography.js:181
connectedCallback	@	typography.js:181
connectedCallback	@	typography.js:181
t.connectedCallback	@	typography.js:181
e.renderer	@	vaadin-combo-box-dropdown.js:38
requestContentUpdate	@	vaadin-overlay.js:188
ready	@	vaadin-combo-box-dropdown.js:38
_enableProperties	@	typography.js:181
_enableProperties	@	typography.js:181
connectedCallback	@	typography.js:181
connectedCallback	@	typography.js:181
connectedCallback	@	typography.js:181
connectedCallback	@	typography.js:181
t.connectedCallback	@	typography.js:181
_attachDom	@	typography.js:181
_readyClients	@	typography.js:181
_flushClients	@	typography.js:181
_propertiesChanged	@	typography.js:181
_flushProperties	@	typography.js:181
ready	@	typography.js:181
ready	@	typography.js:181
ready	@	vaadin-combo-box-dropdown.js:38
ready	@	vaadin-combo-box-dropdown.js:38
ready	@	vaadin-combo-box-dropdown.js:38
ready	@	vaadin-combo-box-light.js:92
_enableProperties	@	typography.js:181
connectedCallback	@	typography.js:181
connectedCallback	@	typography.js:181
connectedCallback	@	vaadin-combo-box-light.js:92
t.connectedCallback	@	typography.js:181
M	@	styles.ts:368
S	@	styles.ts:368
T	@	styles.ts:368
_$AI	@	styles.ts:368
S	@	styles.ts:368
update	@	styles.ts:368
performUpdate	@	styles.ts:368
scheduleUpdate	@	styles.ts:368
_$EC	@	styles.ts:368
```

### Additional information

![image](https://user-images.githubusercontent.com/3587913/164511966-807ed2cc-26dc-4c4e-aa9c-4aa694eb2d5d.png)

**Comment by jeserga** [comment]
+1

**Comment by bvhme** [comment]
This is sadly still a thing. I can often not select entities or buttons as they are outside of the viewport or their container. This means that in some cases like the script overview I can't edit properties of things.
