### ISSUE TITLE
input_number showing both slider and box in more info dialog

### ISSUE THREAD

**Issue by jostie123** [home-assistant/frontend#12396]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

when opening a more info dialog from a input_number in slider mode both the slider and de box are shown.

in box mode the slider disappears as expected. 

### Describe the behavior you expected

when a input_number is configured in slider mode only the slider and the current state should be shown.

### Steps to reproduce the issue

1. set input_number in slider mode
2. open more info dialog

### What version of Home Assistant Core has the issue?

core-2022.4.6

### In which browser are you experiencing the issue with?

Google chrome, microsoft edge

### Which operating system are you using to run this browser?

Windows 10

### Additional information

screenshot:

![image](https://user-images.githubusercontent.com/8819339/164974601-3ea305f4-5e37-4ac8-bf03-558897aa80aa.png)

**Comment by spacegaier** [comment]
I can confirm the issue, but cannot find the reason for it. The respective coding hasn't changed recently and looks correct and should hide the input field.
