### ISSUE TITLE
please make Tips (in dev tools set state) optional

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#12406]
just noticed the new Pr https://github.com/home-assistant/frontend/pull/12355 in Frontend latest, introducing the Tip on Set State. Is there any rationale behind this? It feels really out of place on a developers tools page, not to mention it simply takes costly screen estate:

Unknown to any other open discussion on the matter, I ofc don't know if this is going to be implemented in other places. If so, please have some public polling on this, or at least allow it to be optional.

It coincides with the same frontend experience as the Magnifier we now have on All (!) our views, which might be nice for some, but really distracting for others. https://github.com/home-assistant/frontend/discussions/12384

<img width="570" alt="Schermafbeelding 2022-04-25 om 09 23 41" src="https://user-images.githubusercontent.com/33354141/165040219-69298bbc-f810-4d77-9566-9a797972e267.png">

especially on mobile:

![20220425_072526000_iOS](https://user-images.githubusercontent.com/33354141/165040617-7c97f73e-f24d-4ac9-a84e-d00354a59890.jpg)

_Originally posted by @Mariusthvdb in https://github.com/home-assistant/frontend/discussions/12022#discussioncomment-2627542_

**Comment by Mariusthvdb** [comment]
this was supposed to be a new Discussion, not an Issue, could a dev please move it?

**Comment by zsarnett** [comment]
Tips aren't going to be set as optional

**Comment by Mariusthvdb** [comment]
That is really too bad. They at least should be made device aware, because we can not even follow the hint on mobile;

![image](https://user-images.githubusercontent.com/33354141/165465991-7cd60c0d-efeb-4688-8dca-aa6dda03e434.jpeg)

**Comment by emufan** [comment]
> Tips aren't going to be set as optional

Why not? At least a "Don't show me again" or whatever. If I'm a experienced HA admin and now, why I'm in developer tools and know ... (I think you got it) I don't need and want tipps there (always displayed).
