### ISSUE TITLE
No matching My link found for 

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#12469]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

clicking M key following the new tip about it
in frontend 20220427.0

### Describe the behavior you expected

see the link

### Steps to reproduce the issue

1. click M key
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.5.0.dev20220427

### In which browser are you experiencing the issue with?

Safari, Chrome

### Which operating system are you using to run this browser?

macOS  Monterey 12.3.1

### Additional information

also noticed an error on a popup window , but only once, in the browser url 

the toast message is on each M key

**Comment by ludeeus** [comment]
"see the link"?
Where are you when trying?

**Comment by Mariusthvdb** [comment]
On any view... no matter where I hit the key

**Comment by spacegaier** [comment]
Dashboard views are not supported for My HA links, only general HA pages., e.g. history, config, ...

**Comment by Mariusthvdb** [comment]
yes, I checked the PR and see that now. Still, for an omnipresent quickbar, the use of the key M seems very narrow in functionality.

Not an issue maybe, as in 'bug', more a matter of 'why expose everywhere'..

closing on my behalf, sorry for my misunderstanding.
