### ISSUE TITLE
Back option from Backup menu returns to config instead of system

### ISSUE THREAD

**Issue by dougiteixeira** [home-assistant/frontend#12478]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The option back from the Backups menu returns you to the configuration menu instead of the system menu.

### Describe the behavior you expected

It is expected that the back button of the Backups menu behaves like the other children of the System menu, returning to the System menu.

### Steps to reproduce the issue

1. Acesse o menu Configurações > Sistema.
2. Access the Backups menu.
3. Click the back icon of the Home Assistant interface.

### What version of Home Assistant Core has the issue?

2022.5.0b0

### In which browser are you experiencing the issue with?

Google Chrome 100.0.4896.127

### Which operating system are you using to run this browser?

Windows 10

**Comment by ludeeus** [comment]
This has been adjusted and will be a part of the next supervisor version
