### ISSUE TITLE
Back button on backup config page does not lead back to parent page

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/frontend#12471]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Just noticed in the dev channel, that pressing the back button on the new backup config page (`/hassio/backups`) does not take the user back to the parent menu (`/config/system`) but instead to (`/config/dashboard`). I'll create an issue for this

### Describe the behavior you expected

Go back to `/config/system` instead of `/config/dashboard` when pressing back buttoon

### Steps to reproduce the issue

1. Go to new backup config page
2. Press back button

### What version of Home Assistant Core has the issue?

core-2022.5.0.dev20220427

### In which browser are you experiencing the issue with?

Edge 100.0.1185.50

### Which operating system are you using to run this browser?

Win11

**Comment by ludeeus** [comment]
This has been adjusted, and is pending an update of the supervisor panel.
