### ISSUE TITLE
Supervisor System My link does not work

### ISSUE THREAD

**Issue by wrt54g** [home-assistant/frontend#12488]
When the M key is pressed on /config/system page, it just makes a link for areas. Not for the System config page.

**Comment by wrt54g** [comment]
![image](https://user-images.githubusercontent.com/85389871/165714714-1eaaea90-7b0d-4522-9ab9-c25cd1fc7dca.png)

![image](https://user-images.githubusercontent.com/85389871/165714654-e26fdb11-9878-48c2-8b71-53c30ea80b5e.png)

**Comment by wrt54g** [comment]
I run version 2022.5.0b2

**Comment by zsarnett** [comment]
This will be fixed when the next frontend release goes out

**Comment by wrt54g** [comment]
> This will be fixed when the next frontend release goes out

Thanks, great!

**Comment by wrt54g** [comment]
> This will be fixed when the next frontend release goes out

It's still not fixed in the new Home Assistant 2022.5.0b2. And the system health does not work too.
