### ISSUE TITLE
Markdown card live preview doesn't recover from template error

### ISSUE THREAD

**Issue by frenck** [home-assistant/frontend#12489]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

A video says more than a thousand words:

https://user-images.githubusercontent.com/195327/165724041-e153ef21-0208-4fc5-8514-7cfa8e97fd5a.mp4

### Describe the behavior you expected

I expected it to pick up the preview after the template was valid again.
Also, some feedback on why the template was incorrect the first place would be nice (bit similar to what we show in the developer tools).

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2022.5.0b0

### What was the last working version of Home Assistant Core?

unkown

### In which browser are you experiencing the issue with?

Google Chrome Version 100.0.4896.88 (Official Build) (x86_64)

### Which operating system are you using to run this browser?

macOS Monterey 12.2.1

### Javascript errors shown in your browser console/inspector

```txt
hui-markdown-card.ts:77 Uncaught (in promise) {code: 'template_error', message: "TemplateSyntaxError: unexpected 'end of template'"}
value @ hui-markdown-card.ts:77
await in value (async)
value @ bf871d53.js:1
value @ 334a76c1.js:1
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (async)
requestUpdate @ styles.ts:368
set @ styles.ts:368
k @ styles.ts:368
_$AI @ styles.ts:368
m @ styles.ts:368
T @ styles.ts:368
_$AI @ styles.ts:368
S @ styles.ts:368
update @ styles.ts:368
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (async)
requestUpdate @ styles.ts:368
set @ styles.ts:368
value @ hui-dialog-edit-card.ts:49
handleEvent @ styles.ts:368
i @ typography.js:181
value @ hui-generic-entity-row-editor.ts:29
value @ hui-generic-entity-row-editor.ts:29
value @ hui-element-editor.ts:51
(anonymous) @ hui-element-editor.ts:51
i @ typography.js:181
value @ hui-markdown-card-editor.ts:43
handleEvent @ styles.ts:368
i @ typography.js:181
(anonymous) @ ha-form.ts:33
i @ typography.js:181
value @ ha-selector-text.ts:69
handleEvent @ styles.ts:368
hui-markdown-card.ts:77 Uncaught (in promise) {code: 'template_error', message: "TemplateSyntaxError: unexpected 'end of template'"}
value @ hui-markdown-card.ts:77
await in value (async)
value @ bf871d53.js:1
t.disconnectedCallback @ typography.js:181
_$AR @ styles.ts:368
S @ styles.ts:368
T @ styles.ts:368
_$AI @ styles.ts:368
S @ styles.ts:368
update @ styles.ts:368
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (async)
requestUpdate @ styles.ts:368
set @ styles.ts:368
value @ hui-dialog-edit-card.ts:49
```
```


### Additional information

_No response_

**Comment by zsarnett** [comment]
This is failing here:
https://github.com/home-assistant/frontend/blob/6be6c711d07735034954347acf2641c97044309a/src/panels/lovelace/cards/hui-markdown-card.ts#L155-L158

I am not familiar enough with this code but will continue to see why its not unsubing after config is no longer in error mode

**Comment by frenck** [comment]
This issue is current, thanks bot 🤖
