### ISSUE TITLE
Kodi Music library Artist and Album buttons combined together.

### ISSUE THREAD

**Issue by wrt54g** [home-assistant/frontend#12495]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Album and Artist button on the Kodi music library in the Media Browser are combined together.See the screenshot below:
![image](https://user-images.githubusercontent.com/85389871/165746176-ec3e1651-e342-44a1-a7b9-b734b51b836a.png)

### Describe the behavior you expected

The buttons just being 2 seperate buttons.

### Steps to reproduce the issue

1. I went to the Media Browser tab.
2. I selected my Kodi RPI from the device list.
3. I clicked on the Music folder.
The buttons are now combined together. If I click the button, it will always take me to Artists.

### What version of Home Assistant Core has the issue?

core-2022.5.0b1

### In which browser are you experiencing the issue with?

Firefox 99.0.1 and Chrome 100.0.4896.127

### Which operating system are you using to run this browser?

Windows 10 version 21H2

**Comment by wrt54g** [comment]
Any update on this?

**Comment by Bluhme1** [comment]
Same happens when showing Sonos favorite tracks

**Comment by spacegaier** [comment]
I can confirm the issue. It is not Kodi or Sonos specific, but also appears for simple local media in HA.

**Comment by wrt54g** [comment]
> I can confirm the issue. It is not Kodi or Sonos specific, but also appears for simple local media in HA.
> 
> In my case I do see more than one line (I think around 7) but still many list items are stacked on top of each other.
> 
> ![image](https://user-images.githubusercontent.com/114137/166451621-7d036084-d1fb-4978-b62d-987247f7d47e.png)

Yes I see that in my local media library too. I can barely see the text:
![image](https://user-images.githubusercontent.com/85389871/166452392-45dcd1da-03e0-410b-b5c5-4a45d8c5b173.png)
