### ISSUE TITLE
[HA 2022.5.0b1] Settings -> System -> Backup return arrow goes to Settings instead to System]

### ISSUE THREAD

**Issue by katiuskt** [home-assistant/frontend#12497]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

New configuration layout in 2022.5.0b1 has a little glitch regarding the backup screen (Settings -> System -> Backup): 
When you click on its "go back arrow" it should leave you at System (that is the behaviour you get if you do the same for Settings -> System -> Logs, Settings -> System -> Analitics,...).

However, clicking in the "go back arrow" leaves you into Settings screen.

![HA2002 5 0b1_Backup_GoBack](https://user-images.githubusercontent.com/75622100/165754761-a532a97a-440c-435e-a6c4-4c2defc15f58.gif)

### Describe the behavior you expected

Go back arrow in the Settings -> System -> Backup section should go to System, not Settings

### Steps to reproduce the issue

1. Go to Settings -> System -> Backup
2. Click in the "go back" arrow
3. You will be into Settings instead System

### What version of Home Assistant Core has the issue?

core-2022.5.0b1

### In which browser are you experiencing the issue with?

Edge 100.0.1185.50, Firefox 99.0.1

### Which operating system are you using to run this browser?

Windows 11

**Comment by ludeeus** [comment]
This has already been adjusted and will be a part of the next supervisor version
