### ISSUE TITLE
Home Assistant Demo Energy not working

### ISSUE THREAD

**Issue by wrt54g** [home-assistant/frontend#12500]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Demo energy dashboard (I mean the demo at demo.home-assistant.io) seems to be broken. See screenshot below:
![image](https://user-images.githubusercontent.com/85389871/165841097-f56ff278-85c4-406f-ae11-f3c6c7c96d35.png)

### Describe the behavior you expected

I expected the Energy dashboard to just show the stats.

### Steps to reproduce the issue

1. I opened the Home Assistant demo
2. And I clicked on Energy
And then the issue occoured

### What version of Home Assistant Core has the issue?

Just the demo

### In which browser are you experiencing the issue with?

Firefox 99.0.1 and Chrome 100.0.4896.127

### Which operating system are you using to run this browser?

Windows 10 version 21H2

**Comment by wrt54g** [comment]
Any update on this?

**Comment by zsarnett** [comment]
If nothing is posted. There is no update 😉

**Comment by wrt54g** [comment]
> If nothing is posted. There is no update 😉

It's still broken:
![image](https://user-images.githubusercontent.com/85389871/167686338-f9541df7-ed58-4aae-a3d1-19580c1ce505.png)
Any fix for this soon?

**Comment by anoblet** [comment]
I am also getting this error.

**Comment by wrt54g** [comment]
Its still broken now. Any fix for it coming soon?

**Comment by wrt54g** [comment]
Fixed by #12906
