### ISSUE TITLE
History Graph - State mismatch

### ISSUE THREAD

**Issue by dgomes** [home-assistant/frontend#1251]
**Home Assistant release with the issue:** 0.70

**Last working Home Assistant release (if known):** NA

**Browser and Operating System:** All

**Description of problem:**

This is hard to replicate, but unfortunately common. A binary sensor that has been in a given state for >24h will show the history graph in an incorrect state.

<img width="366" alt="screen shot 2018-06-02 at 23 52 02" src="https://user-images.githubusercontent.com/137684/40881529-b07fb978-66c0-11e8-9ee5-4ac757dccb2f.png">

The screenshot show's such case, but another binary sensor in the same conditions shows up correctly...

**Javascript errors shown in the web inspector (if applicable):**
None
```

```

**Additional information:**

**Comment by c727** [comment]
the problem is that we don't update the history on state change. reopening the dialog shows the update

**Comment by dgomes** [comment]
No

I can reopen the dialog as many times and still the state is wrong

**Comment by kunago** [comment]
I am experiencing very similar issues with some sensors. While the sensor status is corrent, the history graph does not correspond with it no matter what I try.

**Comment by quazzie** [comment]
Maby there is a query for states < 24h to render the history.
But if a sensor has been in the same state for > 24h it would return nothing.

**Comment by cgarwood** [comment]
Can anyone test and verify if this is still an issue as of 0.80?

**Comment by dgomes** [comment]
still an issue

**Comment by dgomes** [comment]
still an issue...

**Comment by zsarnett** [comment]
@dgomes Would you be able to provide more detail on this issue? Lovelace Config? What card are you using to click to show the graph popup? Can you confirm what version of HomeAssistant you are on

**Comment by dgomes** [comment]
@zsarnett this has been like this since pre-lovelace

The bug is clearly associated with history graph generation.

**Comment by zsarnett** [comment]
@dgomes out of all of those I asked the only thing you answered was it wasn't lovelace....

We use the same history graph. If you are using states UI then that is okay. But if you could attach a gif of the issue and confirm the version of Home Assistant you are on. This is clearly not happening to a lot of people so trying to get more info is the only way to help you...

**Comment by dgomes** [comment]
I'm currently using lovelace, but the issue existed before lovelace (read my initial issue report!). You have the image of the error in my original issue submission too.

But here is another screenshot I just took from my 0.104 version (using lovelace):

<img width="367" alt="Screenshot 2020-02-05 at 21 42 48" src="https://user-images.githubusercontent.com/137684/73885900-7d08a400-4860-11ea-8412-de6d152906de.png">

This is an **mqtt.switch** auto-discovered:

```
homeassistant/switch/dafang/rtsp_h264_server/config 

{"name": "dafang h264 rtsp server", "unique_id": "34ce00aebdff-h264-rtsp-server", "device": {"identifiers": "34ce00aebdff", "connections": [["mac", "34:ce:00:ae:bd:ff"]], "manufacturer": "Xiaomi", "model": "Dafang", "name": "Xiaomi Dafang", "sw_version": "Dafang Hacks"}, "icon": "mdi:cctv", "state_topic": "devices/dafang/rtsp_h264_server", "command_topic": "devices/dafang/rtsp_h264_server/set"}

```

The switch has been on since forever (I never turn off the rtsp server)

Many other switch/binary sensors in my setup, but this only happens to those who have been in the same state for >24h (as I reported in previous comment)

**Comment by zsarnett** [comment]
Is this still an issue? Also, I am going to politely tag @bdraco to see if he has any insight. We pull the data from the backend for the history graph I am wondering if maybe the data is coming back incorrectly?

**Comment by dgomes** [comment]
Still an issue (running 0.114)
![Screenshot 2020-09-19 at 17 49 33](https://user-images.githubusercontent.com/137684/93672149-8584b680-faa0-11ea-9353-99d0f8473b4a.png)

But this only happens in very few situations, I had to check +10 binary sensors before finding this one with the bug...

I can't even make any sense of when does this happen :(

**Comment by bdraco** [comment]
Probably the initial state request returns nothing so we need to assume the current state in that case

**Comment by dgomes** [comment]
still happens :(

but I think @bdraco comment is a good hypothesis.

**Comment by dgomes** [comment]
No... still happens...
