### ISSUE TITLE
Scene editor is activating scene being edited

### ISSUE THREAD

**Issue by w35l3y** [home-assistant/frontend#12519]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Every time when I access Scene editor, it activates the scene being edited.

It doesn't matter whether I press the "pencil" or access the url directly.
![image](https://user-images.githubusercontent.com/963510/166008023-174f2d77-781a-4b1e-b106-67df840f1996.png)
`http://homeassistant.local:8123/config/scene/edit/xxxxxxxxxxxxx`

### Describe the behavior you expected

I expected to edit the scene **without activating** it automatically.

### Steps to reproduce the issue

1. Access http://homeassistant.local:8123/config/scene/dashboard
2. Press the pencil to EDIT any scene

### What version of Home Assistant Core has the issue?

core-2022.4.7

### In which browser are you experiencing the issue with?

Chrome 96.0.4664.45 / Firefox 90.0.2

### Which operating system are you using to run this browser?

Ubuntu 18.04 LTS

**Comment by spacegaier** [comment]
Not a bug, but working as designed. See similar raised issues here in the repository for a more detailed explanation.

**Comment by w35l3y** [comment]
Thanks for the quick answer!
For future reference: #12005, #4965, #4360 (I searched but couldn't find more)

I still didn't understand the reason, it just doesn't make sense to me, but that's ok.
I will simply ignore the existence of `Scenes Editor` and manipulate the `/config/scenes.yaml` directly.

I thought it was most like `Automation Editor` as they are in the same group "Automations & Scenes"
`Automation Editor` has "test button" and "run action" to be clicked when needed.
