### ISSUE TITLE
Display Issue: Automations/Scripts > Time Conditions > "Weekdays" > None Selected

### ISSUE THREAD

**Issue by SergeantPup** [home-assistant/frontend#12522]
### Describe the issue you are experiencing

There's a display issue in the Time Conditional 'days' box for the default display.  The default display reads "Weekdays" but when you click into it, no days are selected.  It's just confusing verbiage.  It should default to read "Days of Week" or default to "Every Day".  Displaying "weekdays" is an inaccurate representation of the field configuration at that time.

Very low priority

### What is the used version of the Supervisor?

supervisor-2022.04.3

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

8.0.rc3

### What version of Home Assistant Core is installed?

core-2022.5.0b0

### Steps to reproduce the issue

1.Create any automation/script in UI > Add Condition of Time > Days is displayed as "Weekdays"; no days will be selected.

### Anything in the Supervisor logs that might be useful for us?

```txt
I think this is just a display issue
```

### Additional information

N/A

**Comment by sykong** [comment]
Related to the issue I reported

https://github.com/home-assistant/frontend/issues/12608
