### ISSUE TITLE
Attempting to re-enable disabled integrations never sends a websocket message

### ISSUE THREAD

**Issue by AskAlice** [home-assistant/frontend#12546]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

in /config/integrations, clicking on the `Enable` button or the three dots has no effect.
<img src="https://emu.bz/vy0.gif" />

No websocket traffic is seen that should have made the call to enableIntegration

One possible reason could be that it returns without logging an error here: https://github.dev/home-assistant/frontend/blob/3b6b4d76640fa73dc336a9a6875ff036fe45033f/src/panels/config/integrations/ha-integration-card.ts#L528-L535

### Describe the behavior you expected

To re-enable the config entry

### Steps to reproduce the issue

not sure how to reproduce entirely, but I simply just went to config/integrations, showed disabled integrations, then tried to enable one.

https://discord.com/channels/330944238910963714/672220541343760384/960745641099812934
https://discord.com/channels/330944238910963714/672220541343760384/970715074916405299

### What version of Home Assistant Core has the issue?

core-2022.4.7

### What was the last working version of Home Assistant Core?

core-2022.4.7

### In which browser are you experiencing the issue with?

Google Chrome Version 100.0.4896.127 

### Which operating system are you using to run this browser?

windows 11 and raspbian

### Javascript errors shown in your browser console/inspector

```txt
no js logs and nothing in hass logs
```

**Comment by AskAlice** [comment]
is there an alternate way to edit this data? Where is it stored?

**Comment by emontnemery** [comment]
@AskAlice You can manually edit `.storage/core.config_entries` and set `disabled_by` to `null` for the config entry you want to enable:

1. Stop Home Assistant
2. Edit `.storage/core.config_entries` as needed
3. Start Home Assistant

Make a backup of `.storage/core.config_entries` first to make sure you can recover if you make a mistake when editing.

**Comment by emontnemery** [comment]
@AskAlice I can't reproduce the problem, are you sure this is not an issue with a stale browser cache?

**Comment by AskAlice** [comment]
> @AskAlice I can't reproduce the problem, are you sure this is not an issue with a stale browser cache?

Yeah I've tried it on a few different browsers. I also tried right clicking refresh with dev tools to empty cache & hard reload, as well as going to the 'Application' tab in the chrome dev tools and clearing all storage. 

Another user in discord reports this to also be occurring. The first one that doesn't enable

**Comment by AskAlice** [comment]
I left my phone open on the page for a few minutes with disabled integrations shown, and while it didn't initially work, tapping it again after that duration did work.

In that time I did run `ha core stop` and `ha core start`, but i'm unsure if that has anything to do with it working now.

**Comment by emontnemery** [comment]
> In that time I did run `ha core stop` and `ha core start`, but i'm unsure if that has anything to do with it working now.

OK, so is it now working again and you can disable and enable integrations?

**Comment by AskAlice** [comment]
One I had re-enabled in the config, and the other has `disabled_by` set to null in the config but after leaving my browser open for 10+ minutes and restarting HA core it seemed to let re-enable the one that had `disabled_by` set to null.

**Comment by AskAlice** [comment]
It seems this is a bug that requires more investigation. 

A day after I was able to re-enable a disabled integration, I refreshed, and disabled a new integration for the first time since it worked. Disabling an integration yields the same bug as seen in the video I linked.

**Comment by emontnemery** [comment]
> after leaving my browser open for 10+ minutes and restarting HA core it seemed to let re-enable the one that had disabled_by set to null

That doesn't make sense, `"disabled_by": null` means the config entry is not disabled.
Changes to config entries are not immediately updated though, meaning data in `.storage/core.config_entries` may be stale until it's flushed to disk.
If you stop Home Assistant, a flush is guaranteed, then you can open the file for editing.

It could also be that the the enabling works, but the UI is just not updated.
Are you 100% sure there's no WS traffic?

You can enable WS logging in core like this:
´´´yaml
logger:                                                          
  default: info                                                  
  logs:                                                          
    homeassistant.components.websocket_api.http.connection: debug
```

**Comment by loopy321** [comment]
I too am having this problem (HA 2022.06.0).  The buttons do nothing - like disabling is a one-way ticket:
![Recording 2022-06-03 at 10 48 34](https://user-images.githubusercontent.com/1026345/171900587-270a27df-117c-4216-9651-31ed87167d7f.gif)

**Comment by loopy321** [comment]
Also see here:
https://community.home-assistant.io/t/cannot-re-enable-a-disabled-integration-honeywell-lyric/427395

**Comment by prageeth** [comment]
I've had this issue too, seems like the button click on the UI is not actually clicking the button. I'm a frontend dev (Angular, React, Vue, etc) and I had a quick look and noticed that selecting the button on dev tools (by right-clking the button and selecting "Inspect Element") actually shows me another element. It could be a rendering issue on the UI.

However, I managed to trigger the button click via Javascript on the dev tools console using the following command:

```
document.querySelector('home-assistant').shadowRoot.querySelector('home-assistant-main').shadowRoot.querySelector('app-drawer-layout ha-config-integrations').shadowRoot.querySelector('ha-integration-card[data-domain="ui_lovelace_minimalist"]').shadowRoot.querySelector('ha-card.disabled .actions mwc-button')
```

NOTE: Since the HA frontend uses web components, you have to manually query the `shadowRoots`, so it's not a simple `document.querySelector('foo').click()`

However, if anyone else has the same issue, maybe this will help. In the above command, you can change the integration name (`ui_lovelace_minimalist` in `data-domain="ui_lovelace_minimalist"`) to you integration name.

You can find this by inspecting the integration cards.

**Comment by Seliah** [comment]
@prageeth Nice! That actually activates the component again.
So it's an UI problem and I think this could be an easy fix.

For now I want to give an alternative method to activate the component which I find a little bit easier to execute:
1. Open DevTools (in Chrome via F12).
2. Activate the Element selection Tool (top left in DevTools or press Ctrl+Shift+C in Chrome).
3. Click on the `Activate`-Button of the Integration the you want to enable.
4. Make sure you have the `mwc-button` selected - **not** the `button`:
![image](https://user-images.githubusercontent.com/52240180/186925915-5b007251-fa94-49ae-ac5f-cb72e4c83b38.png)
5. Go to the Console-Tab in DevTools.
6. Type `$0.click()`

Now the integration should be activated again. I hope this helps.

**Comment by drthanwho** [comment]
Still seeing this now on Google Chrome either Desktop (Version 106.0.5249.119) or Mobile but does work fine on Microsoft Edge.

**Comment by loopy321** [comment]
> 6\. $0.click()

This worked for me.  But was easiest to do a CTRL-F and search for the integration name first.  Thanks!
