### ISSUE TITLE
Network config in addons is confusing

### ISSUE THREAD

**Issue by swk** [home-assistant/frontend#12563]
### Describe the issue you are experiencing

after installing the ssh add-on, it does not listen automatically. ok, no problem, lets just go enable that in the config. 

The expectation either toggle to enable listening on port 22 with a possible port number over ride.

However once you navigate to the ssh addon's configuration page you are presented with a networking block that has a header
```
Container   Host   Description
```

followed by  tcp/22 and disabled... no hint of what goes into the disabled box... 

This UI needs some attention

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Terminal & SSH

### What is the version of the add-on?

9.4.0

### Steps to reproduce the issue

1.
2.
3.
...

### Additional information

![image](https://user-images.githubusercontent.com/363703/166340884-8c12ce77-7305-41a3-858a-a92aca00dfba.png)

**Comment by ludeeus** [comment]
This was changed last week.

**Comment by ludeeus** [comment]
It can still be confusing @zsarnett that change happened before this issue where created
