### ISSUE TITLE
Can't drag to reorder entities in Entity Card using Firefox Windows > 97

### ISSUE THREAD

**Issue by jeffalperin** [home-assistant/frontend#12562]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Trying to reorder entities in a standard Entities Card by clicking and dragging, but while the cursor correctly changes to a 4-headed arrow when hovering over the rectangular target icon on the left side of each listed entity, the entity cannot be dragged up or down into a new position.                I’m using the current version of Firefox Windows (99) Same behavior when launching Firefox in safe mode (without add-ins). I downgraded to Firefox 98 and observed the same behavior. I downgraded to Firefox 97 and the click and drag functionality worked correctly.

### Describe the behavior you expected

After clicking, I should be able to drag the entity up or down in the list of entities.

### Steps to reproduce the issue

1. Add an Entities Card with at least two entities to a dashboard.
2.  Enter edit mode for the dashboard and edit the Entities Card.
3. Click and hold on the "drag" target on the left side of an entity row.  While hovering over the target, the cursor will correctly change to the four-arrow cursor indicating that the row can be moved.
4. Try to drag the row and notice that nothing happens.
...

### What version of Home Assistant Core has the issue?

core-2022.4.7

### In which browser are you experiencing the issue with?

Firefox 99.0.1 (64-bit)

### Which operating system are you using to run this browser?

Windows 11

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - entity: sensor.aqara_multisensor_den_humidity
  - entity: sensor.aqara_multisensor_den_pressure
  - entity: sensor.aqara_multisensor_den_temperature
title: Aqara Multisensor Den
```

### Javascript errors shown in your browser console/inspector

```txt
Every time I click on the "drag" icon on the left side of an entity row, this error appears in the Firefox Developer tool console:

Error in parsing value for ‘will-change’.  Declaration dropped.
```

### Additional information

Same incorrect behavior when launching Firefox in safe mode (without add-ins). I downgraded to Firefox 98 and observed the same behavior. I downgraded to Firefox 97 and the click and drag functionality worked correctly.  Tested with current version of Google Chrome which works perfectly.  So, the problem seems to have occurred beginning with Firefox 98.

**Comment by Xitee1** [comment]
I have the same problem. I always have to switch to chrome to move the entities.

**Comment by robertronq** [comment]
Im having the same problem with Firefox v101 on both Linux Mint and Windows 10. It works on Chrome v 102.0 and the Android app.

**Comment by luckyjay** [comment]
Having the same problem. 2022.6.4 on fully patched Windows 10 with Firefox 101.01. No console errors. Just doesn't work.

**Comment by Tscherno** [comment]
Same issue. Firefox Windows / Mac stopped working.

**Comment by lululombard** [comment]
Same issue

**Comment by jeffalperin** [comment]
Does anyone know how to get the attention of the developers?

**Comment by ildar170975** [comment]
> I always have to switch to chrome to move the entities.

Isn't it a bit more complex action instead of simple editing of a code?

**Comment by aw-jansen** [comment]
Experiencing the same problems for about a month now. Other users reporting similar issues here as well: https://community.home-assistant.io/t/cant-drag-to-reorder-entities-in-entities-card-with-firefox-windows-97/417829 
Any solution would be greatly appreciated!

**Comment by warbringer** [comment]
Same problem on 2022.8.1 and the latest version of firefox.

**Comment by MaxVonEvil** [comment]
Still there in 2022.8.4 and FireFox 103.0.2 (x64)
A temporary workaround is to click Show Code Editor link at the bottom and move things around with cut and paste.

On that note; at some point HA changed to show the Entity friendly names instead of switch.whatever_blah - is there a way to get the original behavior back where the entity names are listed when editing cards?

**Comment by Gat0zor** [comment]
I'm also experiencing this even testing Firefox 104.0 (x64) 
Home Assistant 2022.8.5
