### ISSUE TITLE
Media Browser list squashed

### ISSUE THREAD

**Issue by uvjim** [home-assistant/frontend#12568]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When launching the media browser from the media player card the list opens but is squashed to the size of two items.  All items are repeated over the top of each other.

![image](https://user-images.githubusercontent.com/8431065/166553500-e7738c7e-aae0-4654-baf2-0df8b0d98593.png)

### Describe the behavior you expected

Expected the list to be full height in the popup with items evenly spaced as per previous versions. (repeated icons previously raised in #11482)

![image](https://user-images.githubusercontent.com/8431065/166553422-84a95a06-5262-4ddf-9b41-07e184625454.png)

### Steps to reproduce the issue

1. Open the media browser from a media card

### What version of Home Assistant Core has the issue?

2022.5.0b7

### What was the last working version of Home Assistant Core?

2022.4.7

### In which browser are you experiencing the issue with?

Firefox 98.0.1 and Edge 101.0.1210.32

### Which operating system are you using to run this browser?

Windows 10 21H2

### Problem-relevant frontend configuration

```yaml
type: media-control
entity: media_player.living_room_tivo
```

### Javascript errors shown in your browser console/inspector

```txt
None
```

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/issues/12495
