### ISSUE TITLE
Missing translation in settings menu

### ISSUE THREAD

**Issue by itkama** [home-assistant/frontend#12579]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

A screenshot shows it best:
<img width="692" alt="image" src="https://user-images.githubusercontent.com/37951363/166643248-ab1cee5f-1057-4826-96b0-20d06653708a.png">

### Describe the behavior you expected

No error message of such kind.
It also happens in Chrome and the app regardless.

### Steps to reproduce the issue

1. Open settings in the app or a browser.

### What version of Home Assistant Core has the issue?

core-2022.5.0b7

### In which browser are you experiencing the issue with?

Google Chrome 101.0.4951.41

**Comment by spacegaier** [comment]
Translations are handled by the community. At the time when beta 7 was released, the German translation was not yet up-to-date, but by now that has already been fixed. So with the final release today the issue should be gone.
