### ISSUE TITLE
Gauge card not showing "green", "yellow" or "red" field data in visual editor and is inconsistent with data in code editor.

### ISSUE THREAD

**Issue by chrisuk-web** [home-assistant/frontend#12572]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Coded a card as follows:

![image](https://user-images.githubusercontent.com/81539509/166582545-bb90c392-f5f1-4580-bd29-8ff18e0497d1.png)

Code editor has "green" starting at 1 rather than 0 (and graph between 0 and 1 % is blue)

![image](https://user-images.githubusercontent.com/81539509/166583129-dc95c0de-392d-4e60-b902-0663a1298a8f.png)

If I save and then go back into an edit, the visual editor does not display field data for "green", "yellow" or "red":

![image](https://user-images.githubusercontent.com/81539509/166583993-f3974dd6-7532-4229-980a-30812b55adcc.png)

The code editor is unchanged. 

### Describe the behavior you expected

As above

### Steps to reproduce the issue

As above

### What version of Home Assistant Core has the issue?

core-2022.5.0b7

### What was the last working version of Home Assistant Core?

Unknown. Same issue exists in core-2022.4.7

### In which browser are you experiencing the issue with?

Version 100.0.4896.127 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10.0.19044 Build 19044

### State of relevant entities

```txt
state_class: measurement
unit_of_measurement: '%'
icon: mdi:cpu-64-bit
friendly_name: Processor use
```

### Problem-relevant frontend configuration

```yaml
type: gauge
entity: sensor.processor_use_percent
needle: true
severity:
  green: 1
  yellow: 45
  red: 85
min: 0
max: 100
unit: '%'
```

### Additional information

If I code different values, e.g. 10, 20, 30 instead of 1, 45, 85, there is no inconsistency when looking at this data in the code editor, but the fields are still blank if data is saved and then a re-edit is done using the visual editor.

I can manually change   green: 1 to   green: 0 in the code editor and save that value with no issues.

**Comment by yavinmaster** [comment]
This issue still persists on 2022.9.1.

**Comment by thomaszlow** [comment]
This issue still persists in 2022.10.4!
