### ISSUE TITLE
Update entity dialog doesn't change when the update is finished

### ISSUE THREAD

**Issue by raman325** [home-assistant/frontend#12586]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Testing this on HA OS (core v2022.5.0b7), when using the update entity to install an update via the update modal, the modal implies that the update is still in progress well after the update is actually done. Per Paulus, this is somewhat expected because we use the More Info dialog, but to me the behavior does not make sense.

Observations:
- Underneath the modal, the update notification eventually disappears so it seems that the installation is complete
- The modal stays open
- The modal implies that the update is still in progress (the behavior of the modal doesn't change after clicking Install and before/after the update is complete)

### Describe the behavior you expected

Either the modal should be closed or it should change to indicate that the installation is done

### Steps to reproduce the issue

1. Have an update available in Settings panel
2. Open update
3. Click install
4. Wait

### What version of Home Assistant Core has the issue?

2022.5.0b7

### What was the last working version of Home Assistant Core?

2022.4.x

### In which browser are you experiencing the issue with?

Google Chrome 100.0.4896.88

### Which operating system are you using to run this browser?

macOS Monterey (12.3.1)

### State of relevant entities

```txt
I did not check this
```

**Comment by frenck** [comment]
We now the `in_progress` state attribute goes from `true` or `<int>` -> `false`. Thus we could just show an installation complete message 🤷  Heck, we could even trigger a party popper shooting confetti 🎉

**Comment by frenck** [comment]
Missed the bot. IMHO still relevant.

**Comment by raman325** [comment]
is this still relevant? Now it's at least more obvious that the installation is done because there is no more progress and the buttons are still greyed out, but I think it could still be improved with more explicit messaging
