### ISSUE TITLE
Missing "Import from USB" in 2022.5b7

### ISSUE THREAD

**Issue by katiuskt** [home-assistant/frontend#12585]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

According to https://developers.home-assistant.io/docs/operating-system/debugging/#ssh-access-to-the-host it is expected to have a "Import from USB" option (From the UI, navigate to the Supervisor system page and choose "Import from USB")

I'm aware in 2022.5 there is a major change in settings page so that's why I just went page by page trying to find it out with no luck (beta 7).

### Describe the behavior you expected

An "Import from USB" option should be available to be able to follow up official guide https://developers.home-assistant.io/docs/operating-system/debugging/#ssh-access-to-the-host

Or maybe guide needs to be updated because that "Import from USB" is expected to be removed. If that is the case, please let me know where should I raise the ticket.

### Steps to reproduce the issue

Just trying to find the "Import from USB" option among all the menus into settings as they are completely modified from previous versions so documentation can't be followed literally.

### What version of Home Assistant Core has the issue?

Home Assistant Core 2022.5.0b7

### In which browser are you experiencing the issue with?

Edge 101.0.1210.32; Firefox 100.0

### Which operating system are you using to run this browser?

Windows 11

**Comment by zsarnett** [comment]
This is possible now only via CLI. An issue needs to be raised in the Developers.home-assistant repo
