### ISSUE TITLE
Volumio integration: artwork is not showing up in media

### ISSUE THREAD

**Issue by olympia** [home-assistant/frontend#12615]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Artwork (artist/album, etc.) is not showing up when browsing a Volumio device via HA media browser:

![image](https://user-images.githubusercontent.com/1816315/167205183-8dacb777-8e6a-46ba-bd82-9befaedba14e.png)

### Describe the behavior you expected

Expected behavior is that media artwork is showing up as in other integrations (e.g. Spotify)

### Steps to reproduce the issue

1. Go to HA media browser
2. Browse a Volumio source/ device
3.
...

### What version of Home Assistant Core has the issue?

core-2022.5.1

### In which browser are you experiencing the issue with?

Version 100.0.4896.127 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

**Comment by zsarnett** [comment]
Nothing in your Browser Console?

**Comment by olympia** [comment]
Sorry:
![image](https://user-images.githubusercontent.com/1816315/167207674-dae3055a-7b7e-4bbd-9287-fcda184e09d9.png)

**Comment by xisio78** [comment]
I can confirm this bug, from few weeks we have problem with media browser.
Icon are working, but there is no any artwork and ex. internet radio description and icons.

![image](https://user-images.githubusercontent.com/63660194/167843000-6f5a0f95-675c-481d-b9f7-6b15f090e11e.png)

![image](https://user-images.githubusercontent.com/63660194/167843120-75df1f9b-c4fd-4c32-92e4-911b1ca333d4.png)

**Comment by koles142** [comment]
I have the same problem, HA 2022.5.4. Any chance to correct it? @balloob

**Comment by zsarnett** [comment]
I am going to look into the issue for next week.

**Comment by balloob** [comment]
volumio uses JSON blobs as content IDs. This makes everything more complicated.

**Comment by xisio78** [comment]
> I am going to look into the issue for next week.

Any progress? My wife has been nagging me that she can't use the radio and I'll have to move out soon or kick out the Home Assistants, well... I'll miss my wife...

**Comment by zsarnett** [comment]
Ill look to get this into beta. I started looking yesterday
