### ISSUE TITLE
Very minor typo in new Insteon control panel

### ISSUE THREAD

**Issue by tviapiano** [home-assistant/frontend#12610]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the new Insteon control panel (very much appreciated! ), when viewing the all-link database for any device, the column header appears to have a typo: "Tartet Address" instead of "Target Address"

### Describe the behavior you expected

"Target Address"

### Steps to reproduce the issue

1. Go to the Insteon control panel
2. Click on any device
3. Click on "All-Link Database"

### What version of Home Assistant Core has the issue?

2022.5.1

### What was the last working version of Home Assistant Core?

N/A

### In which browser are you experiencing the issue with?

Google Chrome 100.0.4896.127

### Which operating system are you using to run this browser?

Windows 10

**Comment by spacegaier** [comment]
That is not coding directly from this HA frontend repository, but should be coming from another repo where I just raised this PR https://github.com/teharris1/insteon-panel/pull/11
