### ISSUE TITLE
Can't update location using map on general config page

### ISSUE THREAD

**Issue by jackwilsdon** [home-assistant/frontend#12621]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am unable to update my "Home" location using the map on the General -> Config page.

I can drag the pin to a new location but pressing save does not update the location - reloading the page displays the pin back at its previous location

### Describe the behavior you expected

I can update my home location using the map.

### Steps to reproduce the issue

1. Visit `/config/general`
2. Drag the pin on the map
3. Press "Update"
4. Reload the page
5. Note that the location is not updated

### What version of Home Assistant Core has the issue?

2022.5.2

### In which browser are you experiencing the issue with?

Firefox 99.0.1

### Which operating system are you using to run this browser?

macOS Monterey (12.3)

### Additional information

This only seems to happen when the browser is narrower than 871px - wider than that just takes me to the zone edit page instead of allowing me to edit the location inline.

It looks like the new location is not passed to `saveCoreConfig`:
https://github.com/home-assistant/frontend/blob/ce77ddf3659f082de8f1aaf9a710149da4281bbc/src/panels/config/core/ha-config-section-general.ts#L277-L283

It gets saved in `this._location` when the pin is moved but it doesn't seem to get used outside of that:
https://github.com/home-assistant/frontend/blob/ce77ddf3659f082de8f1aaf9a710149da4281bbc/src/panels/config/core/ha-config-section-general.ts#L265-L267

**Comment by aptonline** [comment]
I’m seeing the same issue with latest Home Assistant Core 2022.5.5.

**Comment by RickeyWard** [comment]
Bump
Still there in 2022.6 also there's NO ui to set the long/lat for home, clicking the edit that would normally bring up the pop up takes you to the general/home editor which only has an edit location in zone editor link. No way to set long/lat for "home" in 2022.6
