### ISSUE TITLE
Unable to edit location via desktop browser

### ISSUE THREAD

**Issue by dougiteixeira** [home-assistant/frontend#12626]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

It is not possible to edit the location using the desktop browser.  When accessing Settings > System > General, the map does not appear to perform the edit, when clicking on the edit button, it is redirected to the map page, however, when clicking on edit the zone, it is redirected to the general configuration page, staying in this loop.

https://user-images.githubusercontent.com/31328123/167285640-9be58b85-1d9f-4848-93f8-899f458d3db3.MOV

### Describe the behavior you expected

The same behavior as in previous versions was expected.  Using the mobile app, the edit map is shown in Settings > System > General.

https://user-images.githubusercontent.com/31328123/167285842-fef60141-8588-4a9f-8d07-57eece4ee6c5.MOV

### Steps to reproduce the issue

Attempt to edit the home assistant location.

### What version of Home Assistant Core has the issue?

core-2022.6.0.dev20220508

### What was the last working version of Home Assistant Core?

2022.4

### In which browser are you experiencing the issue with?

Google Chrome 101.0.4951.54

### Which operating system are you using to run this browser?

Windows 10

**Comment by zsarnett** [comment]
Move the icon on the map it redirects you to

**Comment by dougiteixeira** [comment]
> Move the icon on the map it redirects you to

But shouldn't the experience be the same regardless of the device (mobile or desktop)?
