### ISSUE TITLE
Bad values in lovelace

### ISSUE THREAD

**Issue by proasnet** [home-assistant/frontend#12638]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hello, today, I try add your integration to last version of Home Assistant after one year about, when I removed, because integration had bad values. The problem still persists...
Actual values I have 22,4°C inside, 20,1°C outside.
In lovelace, integration shows -5,3°C outside, -6,7°C outside.

### Describe the behavior you expected

Values in the lovelace the same as a values in BSB Lan interface

### Steps to reproduce the issue

1. Working BSB Lan
2. Working HA
3. Install integration

### What version of Home Assistant Core has the issue?

all

**Comment by spacegaier** [comment]
This does not sound like a frontend rendering issue, but a problem with the integration itself (by providing wrong state values)? Is that understanding correct? If it is, then please raise a bug with the backend instead: https://github.com/home-assistant/core
