### ISSUE TITLE
Opening Group helper dialog doesn't select correct tab when opened.

### ISSUE THREAD

**Issue by mltiede** [home-assistant/frontend#12630]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Related information is shown for the Settings tab on the Group of lights dialog.

### Describe the behavior you expected

If the dialog shows the Settings tab as selected, it should show the Settings information and not the Related information.

### Steps to reproduce the issue

1. Click on a Group of lights Helper entity
2. Dialog has Settings tab selected and shows Settings information
3. Click on the Related tab
4. Close the dialog
5. Re-open the dialog

Now the dialog shows Setting as selected, but the information is from the Related tab.  If you then click Related and then back to Settings, then the Settings information is shown.
...

### What version of Home Assistant Core has the issue?

core-2022.5.0

### In which browser are you experiencing the issue with?

Version 101.0.1210.32 (Official build) (64-bit) and Firefox 100.0(64-bit)

### Which operating system are you using to run this browser?

Windows 11 Pro Version	10.0.22000 Build 22000

**Comment by steverep** [comment]
What you are seeing is that the Settings tab is focused, not selected.  The Related tab is the one selected.

Regardless, yes it should focus the selected tab when opened.  This is a duplicate of #12523.
