### ISSUE TITLE
Move Logs refresh to the top

### ISSUE THREAD

**Issue by matthiasdebaat** [home-assistant/frontend#12637]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When selected Home Assistant Core we show an `Refresh` button at the bottom of the page
<img width="220" alt="CleanShot 2022-05-09 at 11 11 12@2x" src="https://user-images.githubusercontent.com/20203284/167378552-c38d1d85-9183-4282-86b8-841cb865f415.png">

On other selections we show a refresh icon at the top right.
<img width="208" alt="CleanShot 2022-05-09 at 11 12 48@2x" src="https://user-images.githubusercontent.com/20203284/167378833-e1ef49a5-a173-4cc4-989f-65e5319abd4d.png">

### Describe the behavior you expected

We should make this consistent with an reload icon in the top bar. Like we have on the updates page.
<img width="285" alt="CleanShot 2022-05-09 at 11 13 19@2x" src="https://user-images.githubusercontent.com/20203284/167378935-8ca44cfb-8ccd-4556-a2ac-55e3bf148829.png">

### Steps to reproduce the issue

1. Open settings
2. Open System
3. Open Logs
4. Switch log type

### What version of Home Assistant Core has the issue?

core-2022.5.2

**Comment by habuild** [comment]
I think it would be better to make all the other log pages the same as the **home assistant core** log with refresh down the bottom.
In long logs like supervisor you have to scroll up from the bottom of the page back up to the top, to refresh, and then scroll all the way back down to view the latest entry. 

or the swirl could be added to the search bar where it floats over the logs and always visible.

Would be nice to get the load full logs buttons back also.

**Comment by somenewaccountthen** [comment]
It would be nice if windows like this scroll you just have a button that is always in view at the top and the bottom.
I guess many devs use tail -f and other log look methods that this does not annoy the hell out of them.

**Comment by ildar170975** [comment]
IMHO the https://github.com/home-assistant/frontend/pull/15382 does NOT close this issue.

![изображение](https://user-images.githubusercontent.com/71872483/217687237-6293b96e-62c2-48ae-a0cb-40ded01e909a.png)

Here the "Refresh" button will become not visible if a page is scrolled down.
Also please check https://github.com/home-assistant/frontend/discussions/15402
