### ISSUE TITLE
Entity Card shows duration as decimal hours

### ISSUE THREAD

**Issue by sevorl** [home-assistant/frontend#12645]
While the entites card shows history stats durations in hh:mm:ss, the entity card shows the same sensor value as decimal hours. 

![image](https://user-images.githubusercontent.com/81764300/167487970-56f07e80-2bfb-4aaa-8781-4755f37de790.png)

This becomes more of an issue since this change: https://github.com/home-assistant/core/pull/70720 which took away the pretty-formated duration attribute

_Originally posted by @sevorl in https://github.com/home-assistant/core/issues/71530#issuecomment-1121524417_

**Comment by bdraco** [comment]
It looks like this is by design per #7763 #10459

**Comment by bdraco** [comment]
Its the only one that seems to override `computeStateDisplay` and call `formatNumber` if its `isNumericState`

**Comment by bdraco** [comment]
It looks like badges also override `computeStateDisplay`
<img width="82" alt="Screen Shot 2022-05-10 at 08 39 38" src="https://user-images.githubusercontent.com/663432/167642070-44109681-21ee-4abc-8492-98f81743860d.png">

**Comment by bdraco** [comment]
I'm not sure how to proceed here as I don't know why it works that way and if there is a historical reason why its different.
