### ISSUE TITLE
Templates not supported for template selector of custom script

### ISSUE THREAD

**Issue by EnochPrime** [home-assistant/frontend#12646]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When attempting to write a template string in a template selector of a custom script the UI reports "The UI does not support templates, you can still use the YAML editor." This occurs for the `Call service` action in both the automation and scripts editors as well as the Services page in the Developer Tools.

### Describe the behavior you expected

The UI to allow template strings to be written like the template trigger or condition.

### Steps to reproduce the issue

1. Create script using template selector
2. Write template string in the template selector field

### What version of Home Assistant Core has the issue?

2022.5.3

### In which browser are you experiencing the issue with?

Brave 1.38.111 (Chromium 101.0.4951.54)

### Which operating system are you using to run this browser?

Linux Mint 20.3

### Problem-relevant frontend configuration

```yaml
alias: New Script
fields:
  message:
    name: Template
    required: true
    selector:
      template: null
sequence: []
```

### Additional information

![image](https://user-images.githubusercontent.com/1175190/167532277-6b366f33-fb8d-491a-ba94-003dd0ac692e.png)

**Comment by EnochPrime** [comment]
This is still an issue with 2022.8.2

**Comment by EnochPrime** [comment]
Still present in 2022.9.4

**Comment by gjgeary** [comment]
2022.9.7 also.  I am trying to put together some scripts with service calls that will require some templating.  It is frustrating that this is documented to work, but actually doesn't in practice.  I would like to confirm that this issue is not longer considered stale.

**Comment by EnochPrime** [comment]
Still present in 2022.12.8

**Comment by karwosts** [comment]
Filed a PR to fix.
