### ISSUE TITLE
Changing services in developer tools doesn't clear errors

### ISSUE THREAD

**Issue by EnochPrime** [home-assistant/frontend#12647]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If an error occurs in the services tab of the developer tools that causes a fallback to yaml mode, the error will not be cleared by switching which service is selected. A page refresh is required to return to UI mode.

### Describe the behavior you expected

Errors should be cleared and returned to UI mode when switching services.

### Steps to reproduce the issue

1. Select a service from the drop down menu
2. Cause a fallback to yaml mode (i.e. type '{{' in the message field of notify.notify)
3. Select another service from the drop down menu

### What version of Home Assistant Core has the issue?

2022.5.3

### In which browser are you experiencing the issue with?

Brave 1.38.111 (Chromium 101.0.4951.54)

### Which operating system are you using to run this browser?

Linux Mint 20.3

**Comment by EnochPrime** [comment]
Still present in 2022.7.5

**Comment by EnochPrime** [comment]
Still present in 2022.8.2

**Comment by EnochPrime** [comment]
Still present in 2022.9.4

**Comment by EnochPrime** [comment]
Still present in 2022.12.8

**Comment by karwosts** [comment]
Filed a bugfix to clear the error on switching service or filling example data. 

Note this will not switch back to UI-mode, but you can easily click the button to toggle back to it.
