### ISSUE TITLE
Search menu item on Mobile doesnt get an aria-label

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#12659]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

<img width="1265" alt="Schermafbeelding 2022-05-11 om 09 55 02" src="https://user-images.githubusercontent.com/33354141/167805186-85df3c50-e7da-4b52-953b-a5e708c4fe4f.png">

### Describe the behavior you expected

aria-label='Search'

### Steps to reproduce the issue

1. see above
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.6.0.dev20220511

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

macOS  Monterey 12.3.1

### Additional information

for some adaptation of the frontend, we need

`mwc-list-item[aria-label="Search"]`, just like we can mod on `mwc-list-item[aria-label="Edit Dashboard"]`

please add the label?
thanks!

**Comment by Mariusthvdb** [comment]
please let me ask this the search item in the Narrow menu (on mobile): as of Frontend 20220516.0 , we now have https://github.com/home-assistant/frontend/pull/12671 which [adds a label to the search](https://github.com/spacegaier/frontend/blob/ff1dee1effdd455ac151293ba77c28f9b04a9c11/src/panels/lovelace/hui-root.ts#L306) item.
However, this is still no area-label, which we are able to filter on in our card-mods, and which the other menu items all have. 
Is there some specific reason we can not use aria-label in the narrow menu?

**Comment by spacegaier** [comment]
@steverep Do you know if adding an explicit `aria-label` for list items is the correct approach even if the individual items do carry a text already? I see some places where we are adding those labels, but not sure if that is indeed correct.

**Comment by steverep** [comment]
No, adding `aria-label` on `mwc-list-item` is not an appropriate fix for anything.  The text inside the element provides the accessible name.

I cannot provide any other guidance because there is no detailed description of the problem, and the graphic doesn't tell me much (I'm blind).  @Mariusthvdb can you please provide a text description of the issue with steps to reproduce?

**Comment by Mariusthvdb** [comment]
thanks for re-opening!

my goal here is to optionally show the search icon and menu-item, which shows when in narrow mode/mobile.

we can control the appearance of the other menu-items, with card-mod with this:

```
        /* Hide several option menu items. */

        mwc-list-item[aria-label="Configureer UI"] {
          {% if is_state('input_boolean.hide_edit_dashboard','on') %}
          display: none;
          {% endif %}
        }
        mwc-list-item[aria-label="Ongebruikte entiteiten"] {
          {% if is_state('input_boolean.hide_unused_entities','on') %}
          display: none;
          {% endif %}
        }
```

my hope was to also be able to do that with:
```
        mwc-list-item[aria-label="Zoeken"] {
          {% if is_state('input_boolean.hide_search','on') %}
          display: none;
          {% endif %}
        }
```

but since the Search item doesnt have a aria-label (yet) we can not do it, and have to maybe find other ways, whihc are not as exact aas this, like tracking down the DOM path on that item. Ofc, that is prone to errors when the path changes. An aria-label would always be valid.

Please let me know if you need more?
thx!

**Comment by Mariusthvdb** [comment]
sure, appreciate that.

Its just the this was the only menu-item without a label, so I would hope the consistency aspect in HA alone would justify adding that tiny line... 

Il, have to read on the use for aria-label in a wider sense, because all I use it for, and the many users of card-mod-theming in the HA user base, is for customizing the menu items. I'll give you one more example:

```
      paper-tab[aria-label='Alarm'] ha-icon$: |
        ha-svg-icon {
          --card-mod-icon: {{states('sensor.alarm_panel_icon')}};
          color: {{states('sensor.alarm_panel_icon_color')}};
        }
```

so you see, its all very functional, and greatly enhances functionality and visability aspects too.

for brevity's sake, here is my [gist](https://gist.github.com/Mariusthvdb/9069c8c4dcad6324035a679244bbfdf1#file-themes_card_mod-yaml) with more than a few options I set to the menu-bar and its items.

**Comment by emufan** [comment]
I think the purpose of the area label is valid here as well

> aria-label
The aria-label attribute defines a string value that labels an interactive element.

>
> [Description](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label#description)
Sometimes the default [accessible name](https://w3c.github.io/accname/#dfn-accessible-name) of an element is missing, or does not accurately describe its contents, and there is no content visible in the DOM that can be associated with the object to give it meaning. A common example is a button containing an SVG or [icon font (which you shouldn't be using)](https://www.youtube.com/watch?v=9xXBYcWgCHA) without any text.

That is valid for a seach icen as well as for the edit ui button directly below existing already. afaik I don't see a difference to these both buttons/menu items.

Is is is not even related to the purpose, Marius would like to sse this implemented. 😉

**Comment by steverep** [comment]
I have to completely agree with @spacegaier here.  The `aria-label` attribute affects real users using assistive technology, and is translated so users can consume the label in their language of choice.  It cannot be added inappropriately just for the purpose of CSS selection.  That is what `id` and `class` attributes are for.

> my goal here is to optionally show the search icon and menu-item, which shows when in narrow mode/mobile.

Which specific menu are we talking about?  Please provide either steps to get there or a code reference.

> It's just that this was/is the only menu-item without a label, so I would hope the consistency aspect in HA alone would justify adding that tiny line.

I don't know why they were added in the first place, but I have been making changes in other places of the frontend to remove them as they are not needed for accessibility.  Keeping them is just more code to be executed and is burdensome on development and prone to error.

**Comment by emufan** [comment]
Regardless of the purpose vom Marius. Why do you say/evaluate, that these assistive helper are not needed for these two buttons/list for accessibility?

**Comment by steverep** [comment]
> Regardless of the purpose vom Marius. Why do you say/evaluate, that these assistive helper are not needed for these two buttons/list for accessibility?

Again, it would help if I knew exactly what buttons you are talking about.

**Comment by Mariusthvdb** [comment]
this is the top right menu, when clicking the 3 dots menu. we are presented with the 5 options, as listed above for
- Search
- Refresh
- Unused entities
- Reload resources
- Edit dashboard.

Of those menu-items, only the Search item does not have an aria-label.

**Comment by emufan** [comment]
> Again, it would help if I knew exactly what buttons you are talking about.

Ah. Sorry. Thought this was clear as a screenshot is in the first post and the DOM in another posting. Thought you know, what buttons are ment because of your answer above.

**Comment by steverep** [comment]
Thank you for putting me on the same page now...

> Of those menu-items, only the Search item does not have an aria-label.

Actually, there are several that do not depending on the configuration of the menu, and a couple that added a `label` property instead (which does nothing).  This just proves the point I and @spacegaier are making - it's prone to error.

> I would disagree on them not being helpful, required even, for accessibility. On the contrary I would say. Access to these menu items is of utmost importance and being able to control that is now left to custom solutions. 

I'm sorry but that's simply not correct.  As I stated above, the accessible name for the menu options are given by the rendered text.  No additional accessibility is gained by adding it.

> Taking the aria-labels out without an alternative would be a major let down. Even though the original purpose would be for assistive technology, why not just embrace the fact it can be used for other goals also.

Because it's simply the wrong tool for the job, and could have adverse effects on users with assistive technology when coding errors occur.  

The right tool to customize these things with CSS theming is the `id` attribute, which also would obviously not be subject to translation revision either.  And I would say that's more of a feature request than an issue which comes with it's own development burden.  I would defer that decision to @bramkragten.

**Comment by bramkragten** [comment]
We are definitely not keeping `aria-labels` around for these purposes, we don't support this use case and will not actively make sure this keeps working.
