### ISSUE TITLE
Automation From Blueprint - Impossible to Save a "Falsy" Value in the UI

### ISSUE THREAD

**Issue by SuperMrBlob** [home-assistant/frontend#12657]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When trying to edit an input for an automation created from a blueprint in the UI, it is impossible to save a falsy value. For example:

- **Setting a selector: boolean input to false will not save it as false - it will remain as the original value (e.g., of true)**
- Setting a text field as an empty string will not save it as such - it well remain as the original value
- Setting a selector: number (slider) to 0 will not save it - it will remain as the original value (of some number)
- Ditto for entity selector... you get the point

### Describe the behavior you expected

When saving a falsy value, these are often legitimate values the UI should save! I should be able to choose 0 on my slider. **I should be able to choose false for my checkbox!** _(Juuuust barely suppressing my desire to launch into a rant about python and static typing 😅)_

For an empty string or an empty entity selector etc., there are two options:
- Treat the empty string as a valid value. Save the empty string as a value in the YAML. The empty string would be distinct from a 'null' value. Issue: would likely need to add some sort of button to 'reset to default' (to delete the entry from the YAML entirely) as doing so in the UI would otherwise be impossible.
- Treat the empty string as a null, removing the entry for that selector from the YAML entirely. Issue: it would not be possible to provide a value of an empty string to a selector that actually wants to provide that as an option, because using an empty string would just reset to default _always_, which is arguably undesirable.

But IN EITHER CASE - if by whatever mechanism decided about the value provided is null - selector should either reset to the default value if one is provided in the blueprint, or if no default exists, show an error on trying to save the automation (that a required selector is not provided).

### Steps to reproduce the issue

1. Load up any blueprint
2. Make a value falsy
3. Refresh the page and see if it saved to the new falsy value

### What version of Home Assistant Core has the issue?

core-2022.5.3

**Comment by crkochan** [comment]
Still present in current release.

```
Home Assistant 2022.7.3
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.0 - latest
```

**Comment by zsarnett** [comment]
Should be fixed soon. Fixed in https://github.com/home-assistant/frontend/pull/13173
