### ISSUE TITLE
:0:0 Script error.

### ISSUE THREAD

**Issue by erkr** [home-assistant/frontend#12651]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Intermittently, I observe `:0:0 Script errors.`. This can be just one, or burst of dozens of them. According the logging it’s originating from the frontend. Can’t put a finger what triggers them. The logging message itself doesn’t help either.

### Describe the behavior you expected

These errors don’t help. No clue

### Steps to reproduce the issue

I just spot them now and then

### What version of Home Assistant Core has the issue?

Core-2022.5.3

### What was the last working version of Home Assistant Core?

Not a new problem

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

All

### Javascript errors shown in your browser console/inspector

```txt
Logger: frontend.js.latest.202205041
Source: components/system_log/__init__.py:190 
First occurred: 16:38:43 (31 occurrences) 
Last logged: 16:45:26

:0:0 Script error.
```

**Comment by pedolsky** [comment]
I get this error message as soon as I edit an automation (via UI or YAML, doesn't matter).

**Comment by erkr** [comment]
> I get this error message as soon as I edit an automation (via UI or YAML, doesn't matter).

I have seen that also. But there are other triggers as well. 
It's strange there is no other information in these errors

**Comment by INVADIA666** [comment]
I have the same issue and it started once I migrate HA to an ssd last night .

**Comment by ColinRobbins** [comment]
I regularly see these, but can’t find a pattern to it.

**Comment by pedolsky** [comment]
Would be nice to get any response why this error message permanently is popping up.

**Comment by erkr** [comment]
Yes, typically I see one after I was doing something in the settings menu

**Comment by sparment** [comment]
I see this too. Whenever I navigate to entities via a specific integration. If I view all entities with no filter or not through an integration interface there is no error.

**Comment by llamafilm** [comment]
I see this happen pretty often, usually multiple times per day.  I don't notice any pattern about what triggers it.  It's been happening for a few weeks at least, currently on version 2023.1.2.

**Comment by marceloaf** [comment]
+1

**Comment by PatrickGlesner** [comment]
Hello,
I have too.
HA 2023.3.4, HAOS 9.5

**Comment by erkr** [comment]
I disagree. Since 2023.9 the error text seems to be changed a little:
``` 
Logger: frontend.js.latest.202309110
Source: components/system_log/__init__.py:269 
First occurred: September 20, 2023 at 21:51:42 (2 occurrences) 
Last logged: September 20, 2023 at 21:51:42

Uncaught error from WebKit 605.1.15 on iOS 16.6.1 Script error. null @:0:0
``` 
Didn't see the previous error anymore since I have these. The frequency is the same
