### ISSUE TITLE
YAML dashboard has edit menu option, but cannot be edited

### ISSUE THREAD

**Issue by sciurius** [home-assistant/frontend#12660]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I have a YAML dashboard, and click on the dashboard menu (vertical dots top right), I have the choice "Edit Dashboard". However, when clicking on it, I only get a dialog "The edit UI is not available when in YAML mode."

### Describe the behavior you expected

I would expect no menu choice "Edit Dashboard", or it to be disabled.
But preferrably I would expect "Edit Dashboard" to open the raw configuration (YAML) editor.
Better still, open a VSCode browser tab with the dashboard YAML.

### Steps to reproduce the issue

1. Open a YAML dashboard
2. Click on the top right menu dots
3. Select "Edit Dashboard"

### What version of Home Assistant Core has the issue?

2022.5.3

### What was the last working version of Home Assistant Core?

n/a

### In which browser are you experiencing the issue with?

Firefox 99

### Which operating system are you using to run this browser?

Fedora 35

**Comment by sciurius** [comment]
Still in 2022.8.1.

**Comment by pedjas** [comment]
Still in 2022.10.5

**Comment by Crushless** [comment]
Still in 2022.11.0b5

**Comment by sciurius** [comment]
It is a pity that HA seems to value flashy innovations (often for a limited group of users) over basic human interface issues.
