### ISSUE TITLE
No create backup on OS update

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#12678]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

<img width="397" alt="Schermafbeelding 2022-05-13 om 12 32 58" src="https://user-images.githubusercontent.com/33354141/168266140-a0023d66-1e74-4310-bcfa-77a21b270489.png">

### Describe the behavior you expected

offer a backup check, like on Core?

### Steps to reproduce the issue

1. click the settings available updates 
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.5.4

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

macOS  Monterey 12.3.1

**Comment by frenck** [comment]
This is not a bug, but correct, the OS itself does not have a backup functionality.

**Comment by Mariusthvdb** [comment]
hmm, shouldn't it offer to backup though, before updating the OS? Seems something people might forget, and could be helpful, if not the advised thing to do.
