### ISSUE TITLE
Impossible to reset limits on the Counter Helper

### ISSUE THREAD

**Issue by grossqx** [home-assistant/frontend#12670]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I created a Helper of type Counter from the interface. I set min max and initial values to any numbers. 
After the helper is created I want to edit it and remove the limits max or min for it to be unlimited. I open the helper, remove the values and press UPDATE. The change is not applied. If I change to other values, it saves and changes like it should, but it is impossible to get rid of the values entirely to have an unlimited counter.
Removing the helper and creating it again doesn't work if the name of the entity is the same. The problem will remain unless you chose to create a helper with a different name.

### Describe the behavior you expected

I expect for changes to apply when I edit the counter and remove max or min values.

### Steps to reproduce the issue

1. Settings > Devices & Services > Helpers
2. Add Helper > Counter
3. Set Minimum value and Maximum value to some values
4. Create
5. Open the helper to edit it
6. Remove values from Minimum value and Maximum value fields
7. Press Update
8. Open to edit again and values remain as there.

### What version of Home Assistant Core has the issue?

2022.5.3

### What was the last working version of Home Assistant Core?

core-2022.5.3

### In which browser are you experiencing the issue with?

Chrome Version 101.0.4951.54 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Linux

**Comment by grossqx** [comment]
Just updated to 2022.5.4. The problem persists

**Comment by karwosts** [comment]
Tested this in 2023.6 and it appears fixed. Closing.
