### ISSUE TITLE
IP bans due to access to camera_proxy

### ISSUE THREAD

**Issue by RoboMagus** [home-assistant/frontend#12679]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

See core issue [70057](https://github.com/home-assistant/core/issues/70057). Opening this issue here, as it does not seem to be something that can be fixed in core and just belongs here.

When opening a dashboard that contains a live camera stream access to `camera_proxy` with an outdated token causes IP ban to instantaneously block the IP of the device.

This seems to be related to how the access token that's used with the `camera_proxy` and that upon the first failure the UI just keeps trying.

### Describe the behavior you expected

When the page gets loaded the access token should be updated **before** it's used and causing authorization errors.

### Steps to reproduce the issue

1. Open a dashboard that contains a live camera stream
2. Put the app to sleep (mobile works best, but can be reproduced on other apps too)
3. Re-open the app. This defaults to the same dashboard page, which immediately causes the IP ban to trigger due to the outdated access token.

### What version of Home Assistant Core has the issue?

core-2022.5.3

### What was the last working version of Home Assistant Core?

Has been an issue since at least 4 months

### In which browser are you experiencing the issue with?

Android companion app 2022.3.0-full

### Which operating system are you using to run this browser?

Android 12

### Additional information

I'm more in touch with back-end related issues so this is not within my comfort zone, but I would expect the issue should be resolved by modifying [`render()` in ha-camera-stream.ts](https://github.com/home-assistant/frontend/blob/72a36fb1cdba310ff713a15c42fd9c94cb68a763/src/components/ha-camera-stream.ts#L73) to not *RenderMJPEG* until a valid token is available.

**Comment by rforbessr** [comment]
I am having the same issue. I am seeing it when using the companion app - I have two UniFi Ortega cameras and wondering if this might be the cause. 

Logger: homeassistant.components.http.ban
Source: components/http/ban.py:125 
Integration: HTTP ([documentation](https://www.home-assistant.io/integrations/http), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+http%22)) 
First occurred: May 17, 2022, 10:55:01 AM (132 occurrences) 
Last logged: 1:58:14 PM

Login attempt or request with invalid authentication from localhost (127.0.0.1). (Home Assistant/2022.3 (io.robbie.HomeAssistant; build:2022.358; iOS 15.5.0) Alamofire/5.4.4)

**Comment by RoboMagus** [comment]
**Update:**

After playing around with [CrowdSec](https://github.com/crowdsecurity/crowdsec) for additional insight (and eventually my replacement for HA's IP ban altogether), I found that though access to the *camera_proxy* is definitely the most problematic it is **Not** the only culprit of "unauthorized" API access!

I've also found various attempts to access `/api/hls/*.m3u8` and `/api/history/period/*` using outdated tokens. These however aren't as problematic as they don't throw a big burst of requests at once.

Seems like a more generic solution is required to block API access after waking up the UI until a valid API-Token is verified.

**Comment by RoboMagus** [comment]
Awesome!
I was looking into purging the access tokens used by the camera streams on the Frontend side, but solving this in Core is very much appreciated. Thanks 😄
