### ISSUE TITLE
Translations don't update

### ISSUE THREAD

**Issue by wrt54g** [home-assistant/frontend#12685]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The translations on GitHub do not seem to really update from lokalise:
![image](https://user-images.githubusercontent.com/85389871/168443011-4689528c-f2b0-4958-a01d-b674bc96d075.png)

### Describe the behavior you expected

"[ci skip] Translation update" 1 day ago

### Steps to reproduce the issue

Not required since it's a backend issue.

### What version of Home Assistant Core has the issue?

core-2022.5.4

**Comment by ludeeus** [comment]
This is correct, they are fetched on build to make sure they are as up to date as possible.
https://github.com/home-assistant/frontend/blob/dev/.github/workflows/release.yaml#L46
