### ISSUE TITLE
Can't make selections/scroll drop-down menus with mouse/trackpad via FrontEnd UI in Safari or Firefox - Mac OS 12

### ISSUE THREAD

**Issue by HVR88** [home-assistant/frontend#12695]
### The problem

It's not possible to scroll the contents of or change/make a selection in a drop down-menu such as the area of a device or entity via the frontend UI  - menu selection resets or edit window closes when a selection is made. The menu behaves as expected, scrolls and any entry can be selected, when using the keyboard as input.

Tested in MacOS 12.4. Problem present in Safari 15.5 and Firefox up to 101.0b6 (not sure which version problem started with). Chrome works as expected.

### What version of Home Assistant Core has the issue?

2022.5.4

**From About**
Frontend version: 20220504.1 - latest 
Home Assistant Core 2022.5.4
Home Assistant Supervisor 2022.05.2
Home Assistant OS 8.0
Kernel version 5.15.38
Agent version 1.2.1

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
No errors are logged in System/Logs/Core
```

### Additional information

I've also rolled back all the way to my earliest full backup of HA 2022.3.4 and still duplicated the issue.  I recall this working in the past couple of months, I just can't remember in what version of HA and don't know when it first stopped working.

**Workaround**
If the Area drop-down menu is selected with the mouse, then manipulated with the cursor keys on the keyboard to scroll through list items, the selected area will "take" if enter/return is pressed.

**Comment by HVR88** [comment]
Added more version info to OP:

**From About**
Frontend version: 20220504.1 - latest
Home Assistant Core 2022.5.4
Home Assistant Supervisor 2022.05.2
Home Assistant OS 8.0
Kernel version 5.15.38
Agent version 1.2.1

**Comment by bl8demast3r** [comment]
I have the same issue here but I'm using Edge Dev 103.0.1255.0 everything works fine in Firefox 100.0.2

**Comment by kwithus** [comment]
> Menu selection and scrolling work as expected in Firefox 100.0 in Windows 10 and seems to be fixed in 101.0b7 for MacOS. Safari still broken.
> 
> Added more version info to OP:
> 
> **From About** Frontend version: 20220504.1 - latest Home Assistant Core 2022.5.4 Home Assistant Supervisor 2022.05.2 Home Assistant OS 8.0 Kernel version 5.15.38 Agent version 1.2.1

It’s the same issue under IOS/IPadOS (however only since 15.5) regardless whether I use Safari, Chrome or the Home Assistant App.
Under iOS 15.4 it does work

**Comment by JohnTF4423** [comment]
Having the same issue with IOS 15.5 on both iPhone and iPad.  Works fine with IOS 15.4.

**Comment by auggy** [comment]
I’ve noticed this behavior with the iOS mobile app as well.

**Comment by werra11** [comment]
I might be wrong but I believe I have the exact same issue using the latest version of Chrome. Firefox seems to be working fine...
Using the keyboard arrows the selection menu works as expected. When using the mouse it somehows clicks behind the selection menu and so closes it. 
GIF showing the issue: https://gyazo.com/244c221b35b52182317d92193e3e7a04

**Comment by zsarnett** [comment]
Fixed in 2022.6b2
