### ISSUE TITLE
Lokalise Translate Project Reviewer permission

### ISSUE THREAD

**Issue by DamdaIoT** [home-assistant/frontend#12697]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I would like to apply for ''reviewer'' permission of project
[Home Assistant - frontend](https://app.lokalise.com/project/3420425759f6d6d241f598.13594006/)
in language Korean.

Because the exist reviewer haven't been active for a long time(about 1 years).
Some entries were locked before while it requires unlocking for modify now.
And some entries should be locked to prevent casually edits.

I have been using Home Assistant since 2017 and I'm managing HomeAssistant Korean User community(over 8,000 user),
so I can do well.

I'll waiting for your reply. Thank you.

### Describe the behavior you expected

Lokalise locked.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.5.4

### State of relevant entities

```txt
-
```

### Problem-relevant frontend configuration

```yaml
-
```

### Javascript errors shown in your browser console/inspector

```txt
-
```

### Additional information

-

**Comment by zsarnett** [comment]
Hi, can you please reach out to an admin on Facebook from our community group/page so that we can confirm your identity? We can then talk about becoming a reviewer. 

Thanks

**Comment by GuGu927** [comment]
@zsarnett Hi, what should I do at "https://www.facebook.com/groups/HomeAssistant/"
I just joined group.

**Comment by DamdaIoT** [comment]
@GuGu927 is also my account.

**Comment by GuGu927** [comment]
@zsarnett Is there a memeber name "Ashton / Congneato" ?
I can not find the member name "Ashton / Congneato", "Ashton Congneato", "Ashton" or "Congneato".
![K-20220528-161318](https://user-images.githubusercontent.com/37651268/170814941-45e17d9b-8607-4c25-80d4-8f0857ba371e.png)
![K-20220528-161326](https://user-images.githubusercontent.com/37651268/170814943-8bab824f-5154-4e54-a036-6905c2f71be8.png)
