### ISSUE TITLE
Broken localization of logbook messages (and others)

### ISSUE THREAD

**Issue by kukulich** [home-assistant/frontend#12698]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Log messages are created as concatenating words. It may work in some languages but it does not work in others. The sentence does not make any sense eg. in Czech. We don't need any "by" or "from" words in sentences. We have different word order. There are other problems like https://en.wikipedia.org/wiki/Grammatical_case

The same problem was already reported before:

- https://github.com/home-assistant/frontend/issues/7179
- https://github.com/home-assistant/frontend/issues/11509

### Describe the behavior you expected

I understand it's hard to solve it but I think there are two ways:

- Table/List - each part of the sentence as a label with value.
- Prepare whole sentences with placeholders (eg. for user) so the translator can change word order etc.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

master

**Comment by bdraco** [comment]
This is a broader problem with logbook in general as all the messages from the backend are not localized.

There has been some progress in 2022.6 to move all the logbook descriptions to the same method so localization could be possible in the future.

Someone needs to teach all the logbook integration platforms about translations in core before we can make additional progress.

**Comment by bdraco** [comment]
https://github.com/home-assistant/core/pull/72222

We also need to localize all the triggers
