### ISSUE TITLE
Move data modal disappear when selecting storage location

### ISSUE THREAD

**Issue by istornz** [home-assistant/frontend#12700]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I want to move data to my SSD in a Raspberry PI 4. I have a fresh install of Home Assistant, plug my formatted SSD (exFAT) in USB 3.0 port and try to move data to my SSD.
When I click on my SSD on the list, modal disappear, so I can't validate moving...

Note: Data modal are not persistant, so when I reopen modal, all data are gone, I tried on Brave, Chrome (no extensions) & Safari.

### Describe the behavior you expected

When I select "/dev/sda" in the list, modal don't dismiss automatically, I should be able to click on "Validate"

### Steps to reproduce the issue

- Log in to Home assistant
- Go to Configuration in side bar, System, Storage
- Click on three dots at upper left, then click on Move data
- A new modal appear, I select my SSD (/dev/sda) in the list.
- Just when I click on /dev/sda, the modal disappear (so I can't click on validate).
...

### What version of Home Assistant Core has the issue?

2022.5.4

### In which browser are you experiencing the issue with?

Google Chrome 101.0.4951.64 | Safari (latest) | Brave (latest)

### Which operating system are you using to run this browser?

macOS BigSur 11.6.5 | iPad OS 15

### Javascript errors shown in your browser console/inspector

```txt
no error in console
```

**Comment by istornz** [comment]
As a workaround:
- Opening move storage modal
- Click on dropdown (list of disk appear)
- Without using mouse just tap on "enter" on the keyboard.

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/pull/12749
