### ISSUE TITLE
Media Control Card displays InputMethod instead of title

### ISSUE THREAD

**Issue by mvv588** [home-assistant/frontend#12719]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The media control card would always display the title of what is playing. Now it always says "InputMethod):" 

### Describe the behavior you expected

The title of the media being played

### Steps to reproduce the issue

1. Add a media control card to the dashboard
2. Assign it to a NVIDIA Shield player
3. Play media
...

### What version of Home Assistant Core has the issue?

2022.5.4

### What was the last working version of Home Assistant Core?

2022.3.x (?)

### In which browser are you experiencing the issue with?

Vivaldi 5.2.2623.46

### Which operating system are you using to run this browser?

Linux Mint 20.3 Una 

### State of relevant entities

media_player.living_room_nvidia_shield

playing

source_list: com.nvidia.tegrazone3:PersonalGridService, com.android.systemui, com.google.android.gms.persistent, com.google.android.gms, com.google.android.ext.services, com.google.android.tv.remote.service, com.google.android.katniss:interactor, com.nvidia.blakepairing, com.nvidia.shieldtech.accessoryui, com.nvidia.shield.remote.server, com.nvidia.osc, com.nvidia.app.messaging, com.android.providers.media.module, Android TV Launcher, com.google.android.katniss:search, com.android.providers.tv, com.nvidia.shield.ask, Google Cast, Netflix, YouTube, com.nvidia.bbciplayer, com.plexapp.mediaserver.smb:sambaserver, com.google.android.apps.mediashell:privileged_process0, de.cyberdream.androidtv.notifications.google, com.google.android.leanback.ime, com.nvidia.tegrazone3:telemetry, com.nvidia.ota, NLZIET, com.google.android.youtube.tv.recommendations, com.google.android.tvrecommendations, Play Store, com.google.process.gapps, com.android.vending:background, com.google.android.permissioncontroller, com.plexapp.mediaserver.smb, com.google.process.gservices
volume_level: 0.4
is_volume_muted: false
app_id: InputMethod}:
app_name: InputMethod}:
source: InputMethod}:
adb_response: Starting: Intent { act=android.intent.action.VIEW dat=https://youtu.be/... }
hdmi_input: null
entity_picture: /api/media_player_proxy/media_player.living_room_nvidia_shield?token=40e4c4bca48cb518109caef55f3b86e13540f15d5454aa97fe3b06c31308aff1&cache=1653506501.926724
friendly_name: Living Room NVIDIA Shield
supported_features: 23997

### Additional information

![Screenshot from 2022-05-17 23-10-58](https://user-images.githubusercontent.com/56486445/168910875-43a9ee88-338b-441a-8fc7-c397063bb396.png)

**Comment by spacegaier** [comment]
Can you please fill in the media player entity state from the HA dev tools in the issue template (the state when you are playing and face the reported issue).

**Comment by mvv588** [comment]
Added, wasn't sure was required before but found it.
