### ISSUE TITLE
Temperature slider is inconsistent with icon color

### ISSUE THREAD

**Issue by alessandroias** [home-assistant/frontend#12727]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Homeassistant behaves rather inconsistently.
The background color of the temperature slider does not match the color returned by the `rgb_color` attribute when the bulb changes color therefore the bulb icon shows a different color.
![image](https://user-images.githubusercontent.com/46724443/169175152-7c1390c8-b22a-4655-9764-6c27dec3902e.png)
![image](https://user-images.githubusercontent.com/46724443/169175167-26b5364e-4aa6-444b-8ca1-7e01d754e845.png)
As you can see, the color shown by the icon and the color shown by the slider are different.

### Describe the behavior you expected

I was expecting a color match.
![image](https://user-images.githubusercontent.com/46724443/169175282-40cdc29a-e8b2-4030-b508-dda16f46f017.png)
![image](https://user-images.githubusercontent.com/46724443/169175578-fbf29b83-bca3-4110-952c-11e2328cbe6c.png)

### Steps to reproduce the issue

1. Navigate to a temperature capable light's `more-info` panel.
2. Change the lamp temperature to use the left side of the slider.

### What version of Home Assistant Core has the issue?

core-2022.5.4

### In which browser are you experiencing the issue with?

Google Chrome 101.0.4951.6 - Firefox 99

### Which operating system are you using to run this browser?

Pop!_OS 21.10

### State of relevant entities

```txt
`rgb_color: 255, 200, 156` on temperature `263` which is shown as 'rgb(213, 233, 255)' on the slider.
```

**Comment by hcoohb** [comment]
As suggested, I think that having the icon color mirroring the color temp slider would indeed be the expected behavior for a consistent UI.
