### ISSUE TITLE
Move datadisk dialog disappears when selecting entry

### ISSUE THREAD

**Issue by agners** [home-assistant/frontend#12729]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When trying to select a data disk, the dialog to move to datadisk disappears.

https://user-images.githubusercontent.com/34061/169243950-9bb8d07c-3a80-454e-b859-6e01e15210c3.mp4

### Describe the behavior you expected

The dialog to stay there when selecting an entry.

### Steps to reproduce the issue

1. Attach an external disk to the system
2. Go to Disk, select three dots then Move to datadisk
3. Select the entry
4. Observe the dialog disappearing.
...

### What version of Home Assistant Core has the issue?

core-2022.05.5

### In which browser are you experiencing the issue with?

Chromium 101/Firefox 100

**Comment by theChemist6** [comment]
I have the same issue. Also on core-2022.05.5.
