### ISSUE TITLE
new logbook in Areas: all recorded entities in all areas

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#12737]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

after https://github.com/home-assistant/frontend/pull/12715 the new logbook panel shows all recorded items in all areas 

there's no difference between any of the areas concerning the logbook panel

### Describe the behavior you expected

would expect only to show area entities in the logbook panel

### Steps to reproduce the issue

1. check 2 areas and see the same logbook panel
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.6.0.dev20220519

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

macOS  Monterey 12.3.1

### Additional information

none of the displayed entities is in that Area

<img width="926" alt="Schermafbeelding 2022-05-19 om 23 12 28" src="https://user-images.githubusercontent.com/33354141/169405508-3646a140-d769-4c7f-a873-3a28928aafd3.png">

this Area (Alarm) has even less, only 1 device. and yet:

<img width="1091" alt="Schermafbeelding 2022-05-19 om 23 14 17" src="https://user-images.githubusercontent.com/33354141/169405811-fb706016-0f50-402a-bee3-a58ff0794479.png">

same logbook

**Comment by bdraco** [comment]
Fixed via https://github.com/home-assistant/frontend/pull/12728

Please confirm when you have a chance.

Thanks

**Comment by Mariusthvdb** [comment]
Confirmed! Great, thanks. Working very fine indeed

**Comment by bdraco** [comment]
Thanks for confirming
