### ISSUE TITLE
Energy dashboard low values become unreadable when there is a much higher value bar visible

### ISSUE THREAD

**Issue by s-i-m-s** [home-assistant/frontend#12734]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have several electric meters on the same dashboard graph, I changed a multiplier causing an apparent 57,000 kWh usage increase in an hour.

As a result it is no longer possible to hover over the usage for other hours to see details as the difference in scale makes all the other hours bars so small they no longer have a hitbox.

### Describe the behavior you expected

Hourly bars to have a minimum size so even if the usage is just 0.5 kWh I should still be able to see the details on hover even if the previous hour was 50,000 kWh.

### Steps to reproduce the issue

1. Have any hour in the graph some astronomical high value vs normal

### What version of Home Assistant Core has the issue?

2022.5.5

### In which browser are you experiencing the issue with?

Chrome 101.0.4951.67, Firefox 100.0.1, Edge 101.0.1210.47

### Which operating system are you using to run this browser?

Windows 10 21H2

### Additional information

![energy usage HA](https://user-images.githubusercontent.com/27518110/169386230-e3e7eace-6273-492f-aade-8b918219f320.png)

**Comment by spacegaier** [comment]
Is that really a valid use case? Faking the bar sizes does not sound like a good approach to me.

Also, there is the option in HA to fix those wrong values in `/developer-tools/statistics`.

**Comment by s-i-m-s** [comment]
Displayed size doesn't need to change but the hitbox that allows detailed statistics to be displayed when you hover over the bar needs to always be big enough to trigger.

Thank you!! That's exactly what I was looking for, I couldn't find anything like that with google and finally ended up deleting the database so I could reset without having to wade through SQL, now I have to go figure out how to close that feature request.
