### ISSUE TITLE
Aqara Smart Plug (SP-EUC01) doesnt show data after new update

### ISSUE THREAD

**Issue by TomNett** [home-assistant/frontend#12768]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have few Aquara smart plugs, the ones I connected in January 2022 are working fine but new ones I connected lately just doesn't work. I successfully connect them using my Sonoff Zigbee USB dongle and everything seems to be fine but I cannot see any data on dashboard. I have version of HA core and OS and also ZHA.
Thanks for helping me out
Tomas

### Describe the behavior you expected

Connecting the smart plug and see incoming data immediately

### Steps to reproduce the issue

1. Connect smartplug trough ZHA
2. Assign the icon to device
3. Go to device detail and in sensors find measurements and display receiving data
...

### What version of Home Assistant Core has the issue?

latest

### What was the last working version of Home Assistant Core?

latest

### In which browser are you experiencing the issue with?

Chrome 101.0.4951.54

### Which operating system are you using to run this browser?

Windows 11

**Comment by zsarnett** [comment]
This is an issue with the integration ZHA. Most likely not yet integrated for those device details
