### ISSUE TITLE
Move Entity does not work 

### ISSUE THREAD

**Issue by theeogflip** [home-assistant/frontend#12774]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Move some Entity to another position dont work ( Sorry for my bad englisch)
![grafik](https://user-images.githubusercontent.com/71273867/170208001-3d1bee78-2818-4f50-85c2-af7ec056bbea.png)

### Describe the behavior you expected

A list of Entities, try to move one to another Position

### Steps to reproduce the issue

1. Open some Elemente List
2. Try to move some Element to another Position
![grafik](https://user-images.githubusercontent.com/71273867/170208336-d606b200-cf8d-474c-89e3-640d97bb0172.png)

( This error is in the Browser Console, maybe something about this:
![grafik](https://user-images.githubusercontent.com/71273867/170210311-e377f723-13ca-4d98-b476-9a92a54fc9cd.png)
)

### What version of Home Assistant Core has the issue?

2022.5.5

**Comment by spacegaier** [comment]
Please fill in in which browser you experience the issue, since I seem to remember we had (or have) an issue in one of them, but it worked fine in all others.
