### ISSUE TITLE
Media-control card cant find Apple HomePod image

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#12776]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

<img width="823" alt="Schermafbeelding 2022-05-25 om 15 40 29" src="https://user-images.githubusercontent.com/33354141/170279089-7c96d44c-663b-4dfc-bbb2-0062f7826af8.png">

### Describe the behavior you expected

have the card show the correct file, which is available in the link 
![](https://is5-ssl.mzstatic.com/image/thumb/Podcasts126/v4/85/22/10/852210ed-3653-93d5-fd68-ddfaa3bb7268/mza_15656445976366504695.jpg/600x600bb.jpg)

### Steps to reproduce the issue

1. play anything on HomePod
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.6.0.dev20220524

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

macOS  Monterey 12.3.1

### State of relevant entities

```txt
volume_level: 0.562
media_content_id: POMS_NOS_16901468
media_content_type: music
media_duration: 1353
media_position: 88
media_position_updated_at: '2022-05-25T13:10:01.923984+00:00'
media_title: 'S10: veelzijdig, eigenzinnig, experimenteel'
media_artist: De Dag
media_album_name: 13 mei 2022
media_episode: '1099'
app_id: com.apple.podcasts
app_name: AirPodcasts
entity_picture: >-
  /api/media_player_proxy/media_player.homepod_keuken?token=d9eb6303redactedde60&cache=https://is5-ssl.mzstatic.com/image/thumb/Podcasts126/v4/85/22/10/852210ed-3653-93d5-fd68-ddfaa3bb7268/mza_15656445976366504695.jpg/600x600bb.jpg
friendly_name: HomePod Keuken
supported_features: 448439
```
```


### Problem-relevant frontend configuration

```yaml
- type: media-control
    entity: media_player.homepod_keuken
```

### Additional information

<img width="510" alt="Schermafbeelding 2022-05-25 om 15 40 06" src="https://user-images.githubusercontent.com/33354141/170280209-8487eeff-00a0-4a92-9874-22852085bfc1.png">

**Comment by spacegaier** [comment]
Frontend tries to render image from `entity_picture`. If that fails, then it sounds as if the backend integration is providing the wrong URL?

**Comment by Mariusthvdb** [comment]
not sure, but the url is correct...as the image proves.

agreed the backend has several very serious issues with the AppleTV (HomePod) library handling. Enough to make these devices useless in current HA.
Not sure whether this case is the backend or the frontend though, but given the error source, the mentioned media-control-card, I had to post here.

Please move to core if you feel to should be issued there.

**Comment by Mariusthvdb** [comment]
keep

**Comment by cuillincollective** [comment]
Did anyone find a solution to this? I've got 3 homepod minis and they are all displayed in a different way

![Screenshot 2023-08-13 212032](https://github.com/home-assistant/frontend/assets/131537050/e8e19c86-1bfb-4cd7-918c-ab2b1b159c0c)
