### ISSUE TITLE
Entity Card Entity Picker does not work correctly in Brave Browser also chrome

### ISSUE THREAD

**Issue by DavidFW1960** [home-assistant/frontend#12771]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I click in the entity picker to select an entity from the dropdown list. It almost looks like Brave isn’t seeing the actual list so when you click it thinks you are clicking outside the list, This is obvious in the entity card as when you move the mouse around over the list the pointer changes depending on what is underneath. Then if you click it goes to the field underneath without selecting the entity you clicked on.

### Describe the behavior you expected

Expect it to select the entity I click on and add to the card

### Steps to reproduce the issue

1. Use the Brave browser
2. edit or add an entity card
3. open the entity picker and click on an entity
...

### What version of Home Assistant Core has the issue?

2022.5.5

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Brave  Version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11 Pro 22H2

### State of relevant entities

```txt
-
```

### Problem-relevant frontend configuration

```yaml
-
```

### Javascript errors shown in your browser console/inspector

```txt
-
```

### Additional information

-

**Comment by Makin-Things** [comment]
I have observed the same problem using the latest Brave on W10.

**Comment by se1exin** [comment]
Also experiencing this on:

```
Chrome 102.0.5005.61 (Arch Linux)

Home Assistant Core 2022.5.5

Frontend version: 20220504.1 - latest
```

**Comment by Makin-Things** [comment]
Chrome just updated to 102.0.5005.63 (Official Build) (64-bit) and it is now broken on W10 as well.

**Comment by DavidFW1960** [comment]
frenck has the same error and Zac Barrett said will be fixed in b2 of 2022.6

**Comment by DavidFW1960** [comment]
Looks like this is fixed in https://github.com/home-assistant/frontend/pull/12805 should be in b2

**Comment by zsarnett** [comment]
Yep!
