### ISSUE TITLE
History graph showing "no state history found" for some entities whose history *is* visible in "History"

### ISSUE THREAD

**Issue by chrisuk-web** [home-assistant/frontend#12809]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

History graph showing "no state history found" for entities whose history *is* visible in "History" after upgrading from core 2022.5.5 to core 2022.6.0b1

### Describe the behavior you expected

Data to be shown as it was in previous working release

### Steps to reproduce the issue

1. Upgrade to 2022.6.0b1
2. Create following card:
type: history-graph
entities:
  - entity: sensor.maria_db_size
  - entity: sensor.influxdb_database_size
title: Database size
hours_to_show: 99
refresh_interval: 5

### What version of Home Assistant Core has the issue?

core-2022.6.0b.1

### What was the last working version of Home Assistant Core?

core-2022.5.5

### In which browser are you experiencing the issue with?

Chrome Version 102.0.5005.61 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Home Assistant OS 8.1

### State of relevant entities

```txt
sensor.maria_db_size
Maria DB size
233.3	database: homeassistant
value: 233.3
unit_of_measurement: MB
icon: mdi:database-search
friendly_name: Maria DB size
```

### Problem-relevant frontend configuration

```yaml
type: history-graph
entities:
  - entity: sensor.maria_db_size
  - entity: sensor.influxdb_database_size
title: Database size
hours_to_show: 99
refresh_interval: 5
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

### Additional information
Data not shown in history graph:
![image](https://user-images.githubusercontent.com/81539509/170600374-0565ba58-f761-419a-834b-80ee567cf04b.png)
Data is shown in history section:
![image](https://user-images.githubusercontent.com/81539509/170600519-3f73299f-77c1-4b25-bc31-8a1015802968.png)

![image](https://user-images.githubusercontent.com/81539509/170601092-aa2be559-5083-4eb4-baac-520e0a97979c.png)

**Comment by zsarnett** [comment]
Duplicate: https://github.com/home-assistant/frontend/issues/12767

Fixed in B2
