### ISSUE TITLE
MyQ integration for garage door is not displaying the up and down arrows buttons

### ISSUE THREAD

**Issue by eroji** [home-assistant/frontend#12811]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Previous the cover entity for MyQ garage door showed an up/down arrow button to open or close the garage door. However, it does not display the button anymore. The UI is actually rendering the button elements but it has no arrow icons.

![image](https://user-images.githubusercontent.com/13228540/170616346-7d5a9b46-47ca-47aa-82a6-57e08fb54f15.png)

Here is the Lovelace UI code I have.

```
entities:
  - entity: binary_sensor.door_window_sensor_158d000312f8c2
    map_state:
      'off':
        value: mdi:garage-variant
      'on':
        value: mdi:garage-open-variant
  - attribute: state
    entity: cover.garage_door
  - entity: cover.garage_door
heading: 🚘 Garage Door
row_size: 3
style: |
  ha-card {
    overflow: hidden;
  }
  ha-card .heading {
    color: white;
    font-size: 18px;
    font-weight: 350;
    margin-top: 15px;
    margin-bottom: 12px;
  }
  ha-card .entities {
    margin-top: 5px;
    margin-bottom: 5px;
  }
  ha-card .entity-state {
    box-shadow: none;
  }
  ha-card .entity-name {
    display: none;
  }
  ha-card .entity-value {
    font-size: 14px;
    text-transform: uppercase;
  }
  ha-icon-button {
      margin-top: -10%;
  }
type: custom:banner-card
```

### Describe the behavior you expected

The entity should display the button icons in Lovelace UI.

### Steps to reproduce the issue

1. Add MyQ integration
2. Create a custom banner-card using the code above

### What version of Home Assistant Core has the issue?

core-2022.5.5

**Comment by zsarnett** [comment]
Please remove custom care code and try again. If the issue persist, I can reopen

**Comment by eroji** [comment]
@zsarnett I assume you mean "CSS"? I tried that before and it's the same thing.

![image](https://user-images.githubusercontent.com/13228540/170750049-284fe869-9026-4f89-929c-7588c08a41c6.png)

**Comment by zsarnett** [comment]
I mean the custom card

**Comment by zsarnett** [comment]
You are using card mod yes?

**Comment by eroji** [comment]
What do you recommend using? I'm using horizontal-stack inside vertical-stack. And the one with the buttons are just an entity card type. Even if I create a entity card outside of the horizontal/vertical stack cards, it does not show. I also tried a couple other cards but none of which works.
