### ISSUE TITLE
Individual devices not added in Energy dashboard

### ISSUE THREAD

**Issue by bekovan** [home-assistant/frontend#12827]
### The problem

Trying to add an Energy sensor in Individual devices in the energy config, in this case a shelly plug S (sensor.dish_washer_energy), seems not to bbe working.
Sensor can be looked up, selected but is not added to the selection pop up

Selecting it from the drop down list will not add it to the window
copying the sensor name will keep the safe grayed out
![image](https://user-images.githubusercontent.com/72280782/170478734-40a3599f-7f7c-407b-852e-b9112585471d.png)
 

### What version of Home Assistant Core has the issue?

Home Assistant Core 2022.6.0b0

### What was the last working version of Home Assistant Core?

unknown, find out after beta upgrade

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

native shelly integration - Energy dashboard

**Comment by EnochPrime** [comment]
This is also happening on 2022.5.5 with Brave (~Chrome). Firefox work for me as well.
