### ISSUE TITLE
Energy Dash - No drop down menus are selectable

### ISSUE THREAD

**Issue by kcoffau** [home-assistant/frontend#12832]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When configuring any entity on the Energy Dashboard such as Grid Consumption, Return To Grid, Battery Systems, or Individual Devices, any config item that involves a drop-down selector menu doesnt allow you to actually select an entity.  They show, you click and then it clears and doesnt save.

### Describe the behavior you expected

The entity selected is chosen, shown on the config popup and then saved.

### Steps to reproduce the issue

1. Login
2. Settings
3. Dashboard
4. Energy
5. Edit on Grid Consumpion
6. Use an entity with current price
7. type "amber" to find entity sensor.amber_general_price
8. Select entity
9. Drop down closes, and nothing is shown in UI.

Repeatable for individual devices (not an amber integration/entity)

Attempted on latest HA App on ios, latest ios.
Safari on latest ios (local connection)
Safari on latest MacOS
Chrome on MacOS

### What version of Home Assistant Core has the issue?

2022.5.5

### In which browser are you experiencing the issue with?

Chrome on Macos Version 102.0.5005.61 (Official Build) (x86_64)

### Which operating system are you using to run this browser?

Big Sur 11.6.6

### State of relevant entities

```txt
state_class: measurement
duration: 30
date: '2022-05-31'
per_kwh: 0.46
nem_date: '2022-05-31T09:00:00+10:00'
spot_per_kwh: 0.31
start_time: '2022-05-30T22:30:01+00:00'
end_time: '2022-05-30T23:00:00+00:00'
renewables: 29
estimate: true
spike_status: none
channel_type: general
unit_of_measurement: $/kWh
attribution: Data provided by Amber Electric
icon: mdi:transmission-tower
friendly_name: Grid Price
```

### Javascript errors shown in your browser console/inspector

```txt
Unsure if this is relevant:

Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.
1 source
energy?auth_callback=1&code=4245211…&state=eyJoYXNz…ODE6ODEyMyIsImNsaWVudElkIjoiaHR0cDovLzE5Mi4xNjguMTAuODE6ODEyMy8ifQ%3D%3D:1
Learn more: User-Agent String Reduction
Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute
Because a cookie’s SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being sent in a cross-site request. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.
Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie should be sent in cross-site requests. This enables third-party use.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be sent in cross-site requests.
4 cookies
```

### Additional information

![image](https://user-images.githubusercontent.com/35386534/171065862-61b4b689-23d2-41cf-8002-2f16e891592f.png)
  then

![image](https://user-images.githubusercontent.com/35386534/171065890-46d74288-a048-40b9-ba00-57261235d6db.png)

**Comment by kcoffau** [comment]
Unsure if its relevant, but in Automations, I can select the entity in the automation drop downs under condition rules.  So it appears the issue is isolated to the energy dash.

**Comment by davewasthere** [comment]
I think nearly every dropdown is b0rked.

A simple replication:

-  Go to dashboard, 
- click Add Dashboard.
- In the Icon* dropdown, I can navigate with keyboard (up down arrow) and filter (typing in icon name), but I can't acquire the scroll handle as the dropdown immediately closes, and I can't use mouse to scroll (which I think is normal behaviour).

There are system dropdowns that seem to work as expected. e.g. /config/general both the timezone and currency dropdowns are perfect.

My guess, it's every ha-combo-box that is broken. I've yet to find one that works normally.

**Comment by kcoffau** [comment]
i also found the arrow up down to select working as well, gets me by for a bit, but yeah, ive since found a few other areas that are not normal.  So its definately a class or library thats gone boo boo

**Comment by jvrijn** [comment]
Same issue in Safari Version 15.5 (17613.2.7.1.8) on macOS Monterey Version 12.4. Cannot select entities drop downs with mouse / touchpad. For example: try assigning a new area to an entity.

**Comment by OldShaterhan** [comment]
It doesn't working for editing dashboards too (I'm not sure if it was mentioned here).

**Comment by OldShaterhan** [comment]
I wonder if this commit by @bramkragten : https://github.com/home-assistant/frontend/commit/a72fd19b7305ac029f72f7322f5b1afba74cba38 fixes the issue, as it looks like the same component...
![image](https://user-images.githubusercontent.com/1622866/171295127-6720d1bd-d962-4099-bb30-1e55ed47ee0b.png)

**Comment by OldShaterhan** [comment]
Thank you!
