### ISSUE TITLE
Shopping List Enter on Android skips to next field instead of submitting

### ISSUE THREAD

**Issue by bernikr** [home-assistant/frontend#12849]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On Android in the Home Assistant app as well as the chrome browser the shopping list as well as the shopping list card behave unexpectedly: When adding an item to the list pressing enter does not add the item to the list but instead skips the curser to the first item in the list, leaving the entered text in the "add" textfield.

### Describe the behavior you expected

When pressing "enter" while the curser is in the first textfield, the item should be added to the shopping list, the textfield cleared and the curser remain in the now empty textfield. (same behaviour as in other browsers)

### Steps to reproduce the issue

1. Setup the Shopping List integration
2. Use Chrome on Android or the Home assistant app
3. Go to the shopping list
4. Enter text into the first textfield
5. Press "Enter" on the keyboard

### What version of Home Assistant Core has the issue?

2022.6.0

### In which browser are you experiencing the issue with?

Google Chrome 102.0.5005.78 / Home Assistant Android 2022.3.0-full

### Which operating system are you using to run this browser?

Android 11 / EMUI 12

**Comment by bernikr** [comment]
I can confirm that the issue is still present in 2022.8.7

**Comment by hamishfagg** [comment]
In version 2022.9.1 using the android app 2022.8.0-full, the shopping list works correctly when first opened if there are no items on the list. My on-screen keyboard displays a 'tick' icon in the bottom right instead of the enter 'arrow' and hitting enter adds an item to the list.

This works until I click anywhere else on the screen. When I return to enter another item the on screen keyboard shows the normal enter key, and hitting enter does **not** add an item to the list.

**Comment by bernikr** [comment]
@hamishfagg Now that you point it out I can confirm the behavior with an empty list.

**Comment by bernikr** [comment]
I just found out that this could be solved by adding `enterkeyhint="done"` as an attribute to the `<input>` element, however I am not sure how to do this with the `ha-textfield` abstraction in between.

**Comment by bernikr** [comment]
this bug still exists in the current version
