### ISSUE TITLE
Reopening browser window shows offline toast for less than a second

### ISSUE THREAD

**Issue by matthiasdebaat** [home-assistant/frontend#12841]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When my Safari browser is in sleep mode and I reopen the window it shows a offline toast for less than a seconds. This gives an unnecessary flicker in my screen. Can't screenshot it because it flips too fast.

### Describe the behavior you expected

Add a delay of a second to the offline toast, so it doesn't flicker.

### Steps to reproduce the issue

1. Let your browser sleep
2. Reopen the window with Home Assistant

### What version of Home Assistant Core has the issue?

core-2022.6.0b7

### In which browser are you experiencing the issue with?

Safari 15.4 (17613.1.17.1.13)

**Comment by piitaya** [comment]
Should be fixed with https://github.com/home-assistant/frontend/pull/17595
