### ISSUE TITLE
history-graph: do not show a name if only ONE graph is displayed (like it was before 2022.6.1)

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#12860]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If only one sensor is used in history-graph - then do NOT show a sensor's name - like it was before 2022.6.

Starting from 2022.6.1:
![изображение](https://user-images.githubusercontent.com/71872483/171844209-8d652523-c6a3-4e18-9065-96283734514b.png)

### Describe the behavior you expected

Was before:
![изображение](https://user-images.githubusercontent.com/71872483/171844512-97f7a67a-74bb-4b6f-870b-abe9b1cc5889.png)
the 2nd picture was taken from Web.

### Steps to reproduce the issue

1. Add a history-graph with ONE sensor.

### What version of Home Assistant Core has the issue?

20220.6.1

### What was the last working version of Home Assistant Core?

2022.6

### In which browser are you experiencing the issue with?

Chrome 102.0.5005.63 

### Which operating system are you using to run this browser?

Win10x64

**Comment by ildar170975** [comment]
Yes, I do know about this:
![изображение](https://user-images.githubusercontent.com/71872483/171847577-3a8aef7a-5538-4b7c-9819-6c1586b86c04.png)
But there is a useless space on the left.

**Comment by bdraco** [comment]
This will restore the the lack of label.
```
diff --git a/src/panels/lovelace/cards/hui-history-graph-card.ts b/src/panels/lovelace/cards/hui-history-graph-card.ts
index a94a1b521..917002a94 100644
--- a/src/panels/lovelace/cards/hui-history-graph-card.ts
+++ b/src/panels/lovelace/cards/hui-history-graph-card.ts
@@ -144,7 +144,6 @@ export class HuiHistoryGraphCard extends LitElement implements LovelaceCard {
             .historyData=${this._stateHistory}
             .names=${this._names}
             up-to-now
-            no-single
           ></state-history-charts>
         </div>
       </ha-card>
```

However `noSingle` has been set since #4882 so this change looks like it was a bugfix and its now working as designed.  Its also really confusing when you have multiple graphs if they don't have labels.

<img width="643" alt="Screen Shot 2022-06-04 at 13 58 12" src="https://user-images.githubusercontent.com/663432/172029408-dd6f5487-b708-4896-8994-b591bd075e11.png">

I don't think we should change it back

**Comment by ildar170975** [comment]
> Its also really confusing when you have multiple graphs if they don't have labels.

For me, the OLD design was perfect:

1. I usually placed a `history-graph` card with ONE sensor in the places where it was clear what sensor is displayed on the graph.
There was NO need to display a name for the only sensor.
Example (on your picture):
![изображение](https://user-images.githubusercontent.com/71872483/172030542-b6937e25-cdfd-4750-8150-0625164ba3f1.png)

2. Also, it was useful to have a `history-graph` card with ONE sensor below a `custom:mini-graph` ([described here](https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/1959)):
![изображение](https://user-images.githubusercontent.com/71872483/172030612-908f69c4-37a2-4bb9-92d8-e91036de697e.png)
Surely these graphs may NOT be horizontally aligned in some cases (like between 00:00 & 01:00) but that was OK.

3. I also used a `history-graph` card with MANY sensors, it is RIGHT that names ARE displayed:
![изображение](https://user-images.githubusercontent.com/71872483/172030695-2e26cf12-cf3f-47dc-8203-e5b81468c488.png)

**Comment by bdraco** [comment]
> The ideal way could be adding an option:
> show_name: true/false
> whether to display a name or not (also, the name is always displayed in a tooltip).

That's probably the one way to accommodate the use cases here. 

Anyways I didn't make this change, and the above lands this into feature request territory so I'll wait for other members to comment on this as they haven't had a chance to weigh in.

**Comment by ildar170975** [comment]
Thank you very much for support!

**Comment by parautenbach** [comment]
I would give my support for a new setting like that. Like Ildar, I have also such use cases.

**Comment by ildar170975** [comment]
Bump

**Comment by ildar170975** [comment]
up

**Comment by spacegaier** [comment]
I agree that adding this option makes sense and is a low risk/effort thing. PR as a proposal is coming in a minute.
