### ISSUE TITLE
Missing/Truncated digits in configuration setting

### ISSUE THREAD

**Issue by baitinghollow** [home-assistant/frontend#12874]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Raspberry Pi4  running HA 2022.6.1
HS-FLS100+ by HomeSeer Technologies Firmware: 1.4  zwave
Issue: Configure Device window - Trying to enter a number for  Luminance Report Interval
 In Firefox: **Only** the Up/Down scroll arrows appear in the entry box. Digits are cut off.
 In Chrome: Next to the Up/Down arrows, the right half of the last digit is visable, the other digits are cut off

### Describe the behavior you expected

would like to see the digits along with the scroll arrows

### Steps to reproduce the issue

1.Settings
2.Devices
3.Click the HomeSeeker Floodlight device
4.Click Configure
5.choose Luminance Report Interval
6.try to enter the number 60
...

### What version of Home Assistant Core has the issue?

core-2022.6.1

### In which browser are you experiencing the issue with?

Chrome and Firefox

### Which operating system are you using to run this browser?

Win 10

**Comment by glaserud** [comment]
Would like this bug to be re-opened as it is still an issue. Settings for ZWave devices is also not showing digits in web view. 

Only shows up-down arrows and a fraction of the digit.

Home Assistant 2022.8.7
Supervisor 2022.08.5
OS 8.5
Frontend 20220802.0 - latest
![Bug_Configuration_ZWave Entity_2022 09 07](https://user-images.githubusercontent.com/111847594/188797547-5f1a8f3a-487a-4b16-90bc-0fee76a3ba1f.png)

**Comment by BebeMischa** [comment]
Just to keep the thread alive, I also have this issue.

**Comment by sarahmva** [comment]
I am facing the same issue. As a workaround, I can set the mdc_text_field width css attribute to a fixed value and it works. There are a few other CSS values that can be adjusted to make it work. Or just make the browser window small enough to force skinny mode. 

![image](https://user-images.githubusercontent.com/68161487/207116885-f3cf0f3b-41eb-4959-bb16-c7dd5de558da.png)


![image](https://user-images.githubusercontent.com/68161487/207115246-adde9d52-8971-48b2-831f-22fee3c34bd3.png)

**Comment by BebeMischa** [comment]
https://github.com/home-assistant/frontend/pull/14788
