### ISSUE TITLE
ESPHome - number component - entity logbook shows records for all devices at once

### ISSUE THREAD

**Issue by gorbunovav** [home-assistant/frontend#12879]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have 8 ESPHome devices.
Some of them have the number component defined and the corresponding entity with the slider in the Home Assistant interface.
Entity card contains logbook, which loads logbook entries for all entities of all my ESPHome devices.
The logbook section on the device page has the same issue.

### Describe the behavior you expected

The logbook entries are correctly filtered.

### Steps to reproduce the issue

1. Connect several ESPHome devices at least one of which exposes a number comopent.
2. Wait some time to gather state changes in the logbook.
3. Open device page of the device with the number component.
4. Observe presence of extra records in the "Logbook" section.
5. Open card for the number entity - observe extra records in the "Logbook" setcion there.
...

### What version of Home Assistant Core has the issue?

2022.6.2

### What was the last working version of Home Assistant Core?

2022.5.x ?

### In which browser are you experiencing the issue with?

Google Chrome 102.0.5005.63

### Which operating system are you using to run this browser?

Windows 11

**Comment by gorbunovav** [comment]
Actually, the behaviour on the primary Logbook page.
It is possible to select the corresponding entity in the filter, but I think it just shows all entries.

**Comment by gorbunovav** [comment]
Probably related to home-assistant/core#73044

**Comment by bdraco** [comment]
Please include state dumps from the developer tools states of the entities in question as well as screen shots. Thanks 👍

**Comment by gorbunovav** [comment]
I've taken another look and it seems that the "Logbook" on the device page shows entries for the current device only. 
It just includes value changes for the "Uptime" sensor (which is updated every minute) for the past 24 hours. 
This creates a huge list of items.

Entity card:
<img width="296" alt="Entity card" src="https://user-images.githubusercontent.com/2665015/172042767-28e00a1a-b475-41e8-9683-a66894b1abb1.png">

Logbook page, "filtered" by entity:
<img width="674" alt="Logbook page" src="https://user-images.githubusercontent.com/2665015/172042773-43337eef-862c-4168-ba19-e55a14a75b9f.png">

Device page:
<img width="242" alt="Device page" src="https://user-images.githubusercontent.com/2665015/172042776-4164210d-b5ec-4514-b10b-47c12a290139.png">

Entities state:
<img width="721" alt="Number entity state" src="https://user-images.githubusercontent.com/2665015/172042777-3d1fbefe-cdde-4bb2-bd06-70ccbc59c598.png">
<img width="731" alt="Uptime entity state" src="https://user-images.githubusercontent.com/2665015/172042778-c09f7a02-7699-40fd-9594-6ef84c32965c.png">

Diagnostic data for the device:
[config_entry-esphome-697781abef6b6e53b521673cdf0dc65c.json.txt](https://github.com/home-assistant/frontend/files/8839601/config_entry-esphome-697781abef6b6e53b521673cdf0dc65c.json.txt)

**Comment by bdraco** [comment]
It looks like the problem stems from the entity have an empty unit of measurement

```
      "number": [
        {
          "object_id": "living_room_people_counter_people_counter",
          "key": 2350149366,
          "name": "Living Room People Counter people counter",
          "unique_id": "living-room-people-counternumberliving_room_people_counter_people_counter",
          "disabled_by_default": false,
          "icon": "mdi:counter",
          "entity_category": 0,
          "min_value": 0.0,
          "max_value": 10.0,
          "step": 1.0,
          "unit_of_measurement": "",
          "mode": 0
        }
      ],
```

**Comment by bdraco** [comment]
Actually scratch that, its your Human readable one that is showing up
```
        {
          "object_id": "living_room_people_counter_uptime_human_readable",
          "key": 4149855183,
          "name": "Living Room People Counter Uptime Human Readable",
          "unique_id": "living-room-people-countertext_sensorliving_room_people_counter_uptime_human_readable",
          "disabled_by_default": false,
          "icon": "mdi:clock-start",
          "entity_category": 0
        }
```

It has no unit of measure so it will show up on the devices page.  The devices pages only filters away entities that have UOM or state class. Since the device panels request their own filter, that filter wins out of your yaml filter.  In short, it does not look at your logbook filter as that only affects the logbook panel.

If you add it to your logbook filter it should disappear from the logbook panel at `/logbook`

**Comment by gorbunovav** [comment]
@bdraco wait, the primary issue is not with the "Device" page - it works ok, and you are right - I need to exculde the `Human readable` sensor from the logbook configuration manually, since Home Assistant has no way to know that it doesn't need to log it.

But for the `/logbook` page and the entity card it seems that filter is disabled completly - it shows records not just for other entities, but for other devices as well (and it happens if I am trying to view/filter the `living-room-people-counternumberliving_room_people_counter_people_counter` entity ).
It seems that the issue is similar to #73044 - it is just more generic, you don't need the `logbook` card, it happens in pre-defined areas too.
Plus in contrast with the description in #73044 my `living_room_people_counter_uptime_human_readable` as filter option on the `/logbook` page.

**Comment by gorbunovav** [comment]
https://github.com/home-assistant/core/issues/73044 fix has resolved desribed issues for me.
