### ISSUE TITLE
Entities hidden by an integration cannot be disabled/enabled by a user

### ISSUE THREAD

**Issue by dermotduffy** [home-assistant/frontend#12887]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When an integration has an entity that is hidden by default (e.g.):

```py
  self._attr_entity_registry_visible_default = False
```

The UI appears to not allow the user to enable (which presumable also unhides it) or disable it. Note how the controls are disabled in the below screenshot:

![ui-bug](https://user-images.githubusercontent.com/1136829/172070841-62476eb3-8737-4721-8319-24fa6dbf5688.png)

This appears to be intentional ([source](https://github.com/home-assistant/frontend/blob/dev/src/panels/config/entities/entity-registry-settings.ts#L491), written by @zsarnett ). It's unclear why this is desirable as effectively this means if an integration lists any entity as hidden, it can never be unhidden or disabled by the user via these controls -- but I suppose this could be WAI if integrations are not expected to hide entities that the user could subsequently unhide / enable / disable.

For my usecase (Frigate), allowing a user to disable entities is occasionally useful, so this would deter my usage of hidden entities at all.

Related PR: https://github.com/blakeblackshear/frigate-hass-integration/pull/273

### Describe the behavior you expected

The HA frontend should allow entities hidden by an integration to be disabled or unhidden.

### Steps to reproduce the issue

1. Use any integration that creates hidden entities (or just set `hidden_by` for an entity registry entry to `integration`).
2. Navigate to the entity: `Settings -> Devices & Services -> Entities Tab`
3. Ensure `Show hidden entities` is selected in the filter.
4. Open the hidden entity
5. Open the `Advanced Settings` expansion panel.

Observe Enabled / Hidden / Disabled controls are all disabled.

### What version of Home Assistant Core has the issue?

2022.7.0.dev20220604

### In which browser are you experiencing the issue with?

Google Chrome 101.0.4951.54 (Official Build) (64-bit) 

### Which operating system are you using to run this browser?

Ubuntu 20.04.3 LTS

**Comment by felipecrs** [comment]
I would say that this issue is still valid.

**Comment by felipecrs** [comment]
@zsarnett can you please help us understand the reasoning behind it? Or would you accept a PR changing this behavior?

**Comment by austwhite** [comment]
Just weighing in on this.   An Integration can disable an entity, but this is meant to be fully under our control.  If we decide we want to expose an entity, we should be allowed to do so.  We always were allowed to re-enable entities until recently.
An example I have is an Aqara Motion Sensor.   It has motion and occupancy.  The motion entitiy is hidden by the integration, and I want that to be fully exposed as I don't use the "occupancy" entity.
Thanks :)

**Comment by felipecrs** [comment]
I believe this is still relevant.

**Comment by someonewating** [comment]
Do you have any temporary solution?

**Comment by NickM-27** [comment]
Bump

**Comment by karwosts** [comment]
@NickM-27 - are you sure this is still valid?

I checked entity hidden by integration and it allows me to enable/disable it with the toggle. 

![image](https://github.com/home-assistant/frontend/assets/32912880/bf7a5c84-e220-4586-94eb-9e09e6d72532)


Suggest this to be closed unless you have a counterexample.

**Comment by NickM-27** [comment]
This screenshot is missing the most important part which is the visibility switch

**Comment by karwosts** [comment]
> This screenshot is missing the most important part which is the visibility switch.
> 
> Not with my computer to test, can do that later next week

Ok I understand what you mean now. Yes the visibility switch is still disabled. The PR title said you can't *enable/disable* the entity, so I was focused on the `Enabled` switch. 

I was going to say that I didn't think the backend supported users overriding hidden by integration visibility, though just now I tried it on a chance and it did seem to take effect. I'll look into this a bit more and see if that's really possible or not.

**Comment by karwosts** [comment]
On inspection I can't see any reason why we would not allow user to override visibility for entity hidden by integration. It seems supported fine in the backend. 

I have rolled a fix for this into an existing PR I had for visibility settings.

**Comment by NickM-27** [comment]
That's awesome 👌
