### ISSUE TITLE
Logbook gets frontend stuck when an entity has ~10000+ state changes in a 24 period

### ISSUE THREAD

**Issue by to4ko** [home-assistant/frontend#12886]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Frontend can easily get unresponsive and even can crash with new automatically opening logbooks in 2022.6.x

### Describe the behavior you expected

Toggle in UI or somekind of settings in configuration.yaml if "logbooks everywhere" to be opened automatically

### Steps to reproduce the issue

1. get yourself entity with high refresh rate
2. wait for a few hours (depending on your hw setup)
3. open entity details
...

### What version of Home Assistant Core has the issue?

core-2022.6.2

### What was the last working version of Home Assistant Core?

core-2022.5.5

### In which browser are you experiencing the issue with?

Google Chrome 102.0.5005.63 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 x64

### Additional information

![logbook_2](https://user-images.githubusercontent.com/45161980/172066574-2a74ea87-88d4-4b3f-a4e2-ad3d704ae66e.gif)
![logbook_1](https://user-images.githubusercontent.com/45161980/172066582-6a2ed815-bfa2-4d12-8e70-8210262dd606.gif)

**Comment by bdraco** [comment]
Loading 35,000 states is going to do that.  You can avoid logbook loading these entities by adding a unit of measurement to the entity.

**Comment by to4ko** [comment]
Thanks for letting me know this "option"...not sure if counter has unit of meaurement. But what if there will be rpi (kinda recommended platform) and not 10k in 24h...2k? or even less..or simply user do not need this kind of pre-set behaviour? man, we wiil decide when to switch you lights, right now or in some time once all the logbooks are ready?

this is realy cool and interesting feature but from my point of view - this should be optional.

**Comment by bdraco** [comment]
I don't think this is a new problem as the logbook has been on the more info card for years


Two options stand out to fix this on the frontend.

1. Virtualization of the logbook on the more info card (might be a bad idea because of scrolling)
2. Add some type of circuit breaker to refuse to render more than 10k rows


The backend hardware doesn't matter so much in this case since the problem is the browser can't keep up
