### ISSUE TITLE
Unsupported File Format when selecting upload file for restoration. (backup file)

### ISSUE THREAD

**Issue by MeanderingWanderer** [home-assistant/frontend#12895]
### The problem

Was migrating Raspberry OS to 64 bit.  I installed a fresh copy of HA, and was restoring from a backup file.
At two different points I encountered the same error/prompt.  
First time was during initial setup of HA, by selecting _"Alternatively you can restore from previous..."_. 
When selecting the backup file to upload (e5733797.tar) I was incorrectly prompted with 
_Unsupported file format.  Please choose a Home Assistant backup file. (.tar)_

Same error after creating a new temporary user, then trying to upload backup file from settings>system>backup

I was able to bypass this error by manually putting tar file into HA backup directory.   Once the file appeared on the settings>system>backup page I was able to restore the file.

Other then that, the restoration was easy and flawless!

### What version of Home Assistant Core has the issue?

Home Assistant Core 2022.5.4

### What was the last working version of Home Assistant Core?

Home Assistant Core 2022.5.4

### What type of installation are you running?

Home Assistant Supervised

### Integration causing the issue

Home Assitant Front-end

### Additional information

Home Assistant Supervised System Health
Version | core-2022.5.4
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.9
Operating System Family | Linux
Operating System Version | 5.10.103-v7l+
CPU Architecture | armv7l

Home Assistant Supervisor
Host Operating System | Raspbian GNU/Linux 10 (buster)
Update Channel | stable
Supervisor Version | supervisor-2022.05.2
Docker Version | 20.10.16
Healthy | true
Supported | Unsupported
Supervisor API | ok
Version API | ok

**Comment by MeanderingWanderer** [comment]
Seemed to resolve when I moved the backup file to ha backup folder.
File picker limiting by location, and not just file type?

**Comment by odignal** [comment]
This seems to be a Firefox problem. FF produced the same error for me, but Chrome just worked fine (on Windows). I guess, FF is sending a different MIME header than Chrome.

**Comment by MeanderingWanderer** [comment]
Thank you for researching this issue and getting back to me.   I've had
other problems using FF with HA, but I can't bring myself to start using
chrome.
Hopefully if others experience same problem they'll find this thread.

Thanks again!
