### ISSUE TITLE
Calendar card in month view and panel type does not vertically fill the screen

### ISSUE THREAD

**Issue by GitHubGoody** [home-assistant/frontend#12891]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a view set to `type: panel` with a calendar card. When set to month view, the calendar only fills ~50% of the available vertical space resulting in hidden ("+X more") events that could be displayed if the calendar were configured to use all of the available space.

### Describe the behavior you expected

The default calendar view (accessed via the sidebar) fills all of the available space and is how the calendar card should work as well.

### Steps to reproduce the issue

1. Create a new view and set it to `type: panel`
2. Add a calendar card
3. Set the calendar card to Month view
4. Tap the Sidebar Calendar | Month view to compare

### What version of Home Assistant Core has the issue?

N/A

### What was the last working version of Home Assistant Core?

N/A

### In which browser are you experiencing the issue with?

Multiple

### Which operating system are you using to run this browser?

N/A

**Comment by GitHubGoody** [comment]
This is still an issue that I hope can be addressed in a future update.

**Comment by vanderdude** [comment]
I was able to reproduce the issue.
Bump for hoping this gets adressed.
