### ISSUE TITLE
Historical Graph card doesnt update with refresh interval post 2022.6.2 upgrade. 

### ISSUE THREAD

**Issue by stk21** [home-assistant/frontend#12894]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

historical cards would always update in 2022.5, stopped working in 2022.6.0...  changed the refresh rate from zero (worked in 2022.5) to five in 2022.6.0.  started working again.  Stopped working again in the 2022.6.2 update

tested with both chrome and safari

### Describe the behavior you expected

Historical card will update as per refresh rate like the gauge cards do.

I have gauge cards on the same dashboard as the historical graph, and while the gauges do update, the graph does not.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.6.2

### What was the last working version of Home Assistant Core?

2022.5.x

### In which browser are you experiencing the issue with?

Chrome 102.0.5005.61, Safari 15.4

### Which operating system are you using to run this browser?

Mac 12.3.1

**Comment by ildar170975** [comment]
Isn't it same as https://github.com/home-assistant/frontend/issues/12859 ?

**Comment by stk21** [comment]
Yes it is.  My bad.  I search, and I didnt see that one.
