### ISSUE TITLE
Window sizing - small window regardless of available estate; not resizable; forced to use horizontal scroll bar

### ISSUE THREAD

**Issue by alexruffell** [home-assistant/frontend#12907]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I see this issue a lot when editing dashboard cards where I have tons of lateral space but I cannot resize the window I am working in (card editor). This gets very tedious when you have to keep scrolling back and forth during the editing, and even worse when the preview causes everything to shift.

In the example below, I was trying to reconfigure a zigbee motion sensor (important as it causes the table to enlarge to the right compared to simpler zigbee devices) that had dropped off the network as doing so often revives it. Please note in the screenshot how the results are partially shown as they do not fit in the window, and that the user can only scroll sideways as resizing is not enabled.

<img width="1747" alt="image" src="https://user-images.githubusercontent.com/4006944/172506570-81d7524f-48c9-4781-97e0-f78e6b325f4f.png">

On an unrelated note... why does it say the device failed reconfiguration if all the elements have a green checkmark??

### Describe the behavior you expected

I would expect to be able to resize most child (is this the term for windows inside the main one?) windows within Home Assistant, or at the very least for them to use the available space more efficiently. The screenshot above shows the wasted space.

### Steps to reproduce the issue

Edit a dashboard card (YAML editing) or run a reconfiguration of a zigbee motion sensor (or any zigbee device that causes the resulting table to enlarge to the right)

### What version of Home Assistant Core has the issue?

core-2022.6.3

### In which browser are you experiencing the issue with?

Google Chrome Version 102.0.5005.63 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

**Comment by matthiasdebaat** [comment]
Dialogs should reach a maximum height and width of 560px on large screens, as written in the [Material guidelines](https://m3.material.io/components/dialogs/guidelines#9d723c7a-03d1-4e7c-95af-a20ed4b66533). In case more screen space is needed it should open a new page.

In this particular example, I'd recommend using something other than a table in this dialog. Or use a responsive table.

**Comment by alexruffell** [comment]
Great way to solve stuff... gets stale and closed automatically. Problem solved. Nope. Ant the latest revision made this issue even worse by addint the top 3 tabs
