### ISSUE TITLE
Zones cannot be created in the dialog-entity-editor

### ISSUE THREAD

**Issue by philippwaller** [home-assistant/frontend#12902]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When trying to create a new zone in the Entity Dialog, this command cannot currently be executed by a mouse click, as the dropdown collides with the "Advanced Settings / Erweitere Einstellungen" button. See the screen recording for a better explanation 😉.
 
![glitch](https://user-images.githubusercontent.com/1090452/172361599-7ec5c127-fee7-4892-91d8-945426acea0f.gif)

### Describe the behavior you expected

Clicking on the dropdown entry "Create Zone XYZ" should create a new zone. 

### Steps to reproduce the issue

1. Go to settings -> devices & services
2. Go the the entity tab
3. Open/edit an existing entity
4. Update the zone input with non existing zone id
5. Try to click on "Create Zone XYZ"

### What version of Home Assistant Core has the issue?

core-2022.6.3

### What was the last working version of Home Assistant Core?

core.-2022.X.X

### In which browser are you experiencing the issue with?

Google Chrome 102.0.5005.61

### Which operating system are you using to run this browser?

macOS 12.3.1

**Comment by GSzabados** [comment]
Meanwhile you can use the `Add new area...` option at the end of the drop down list.

Otherwise it is called `Area` and not `Zone`.
