### ISSUE TITLE
SQL error clears form

### ISSUE THREAD

**Issue by sciurius** [home-assistant/frontend#12903]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When adding SQL integration, filling in the form and press SUBMIT. When a problem occurs (e.g. SQL is invalid) the whole form is cleared and **all** fields must again be filled in. This is annoying.

### Describe the behavior you expected

I'd expect all fields to be filled in as they were, so content can be modified to fix the problems.

### Steps to reproduce the issue

1. Add SQL integration
2. Fill in all fields but make a mistake in the SQL
3. SUBMIT
...
An (rather unhelpful) error message is given and all fom fields are cleared.

### What version of Home Assistant Core has the issue?

2022.6.2

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Firefox 100
Chromium Version 101.0.4951.64 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Fedora 35

### State of relevant entities

N/A

### Problem-relevant frontend configuration

N/A

### Javascript errors shown in your browser console/inspector

N/A

**Comment by sciurius** [comment]
On a related note: An SQL sensor defined in YAML is now imported into the UI:

Configuration of the SQL sensor platform in YAML is deprecated and will be removed in Home Assistant 2022.6; Your existing configuration has been imported into the UI automatically and can be safely removed from your configuration.yaml file

Integrations show a new device (SQL).
However, when I click on configure I get a blank form. Where did my YAML configured SQL sensor go?
Another restart and the SQL integration is also gone...

**Comment by romlisrl** [comment]
Just my 5cents to the SQL UI.
Not possible provide just unit_of_measurement without providing template values in SQL integration.  It's possible to create the sensor providing only database address and query (in my case MariaDB). The same issue happens when you try to edit query in SQL integration. I'm not using template, therefore I'm unable to set unit of measurement for the query result separately.
Sorry posting here, was extremely hard to find how to report new issue for SQL integration.
