### ISSUE TITLE
Using an input_datetime on the entities card renders the date in m/d/y format instead of d/m/y format

### ISSUE THREAD

**Issue by gregbradley** [home-assistant/frontend#12918]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The entities card renders the date in an input_datetime in the wrong format.

### Describe the behavior you expected

Should be rendered in browser region format or based on some user preference.

### Steps to reproduce the issue

1. Edit dashboard
2. Add an entities card
3. Add an input_datetime entity to the entities card

### What version of Home Assistant Core has the issue?

core-2022.6.3

**Comment by ildar170975** [comment]
I proposed a FR - "Add a "Date format" user setting".
https://community.home-assistant.io/t/user-settings-add-date-format/458068

Currently a date format is automatically set (at least supposed to) dependingly on selected language.
