### ISSUE TITLE
Inconsistent Home Assistant Cloud setting

### ISSUE THREAD

**Issue by sam-ward** [home-assistant/frontend#12919]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have Home Assistant running with Nabu Casa cloud enabled and working.  I have just noticed that in the new(er) settings -> system -> network menu, under home assistant URL it shows Use Home Assistant Cloud as not enabled; where as in settings -> Home Assistant Cloud it is showing as enabled.

Unless these settings are refering to 2 different things, in which case maybe the labeling needs to be ammended to be clear.

settings -> system -> network menu
![network settings](https://user-images.githubusercontent.com/765012/172757152-dc033e24-5268-4591-a3ae-3ad66ffa7d9b.png)

settings -> Home Assistant Cloud
![ha cloud settings](https://user-images.githubusercontent.com/765012/172757166-a7c93820-0ec4-47eb-a2e7-ee647c81a4c9.png)

### Describe the behavior you expected

I would have expected both sets of settings to be showing the same value.

### Steps to reproduce the issue

1. Go to  settings -> system -> network menu, under home assistant URL note the value of "Use Home Assistant Cloud"
2. Go to  settings -> Home Assistant Cloud and note whether it is enabled.
3.
...

### What version of Home Assistant Core has the issue?

2022.6.4

### In which browser are you experiencing the issue with?

Firefox 100.0.2 and Chrome 102.0.5005.63

### Which operating system are you using to run this browser?

Win10

**Comment by frenck** [comment]
> Unless these settings are refering to 2 different things, in which case maybe the labeling needs to be ammended to be clear.

They do. One can use multiple external routes to get to ones instances. For example, I'm using both the Nabu Casa cloud, but also have made it externally available on my custom domain and VPN (tailscale, wireguard & zerotier).

The network setting uses Nabu Casa cloud by default, but in my case, I've overridden it to use my custom domain.

This means HA will use that for the external URL, while I can still access my instance over Nabu Casa cloud (or other methods).

**Comment by sam-ward** [comment]
Ok thats good information to know.  But then the question is, what state is my HA instance in at the moment (based on those screen shots)? 
It is connected to Nabu Casa but its using a custom URL that just happens to be the same as my nabu casa URL??  

I'm just trying to understand what the settings are saying about my system.  And then the other question is should that toggle be on by default when you connect to Nabu Casa Cloud? I have never (to the best of my knowledge) configured a custom URL, so I'm just not sure why its in this state.

**Comment by frenck** [comment]
> It is connected to Nabu Casa but its using a custom URL that just happens to be the same as my nabu casa URL??

If you enter your Nabu Casa URL as a custom URL, it will effectively be the same as not setting it (and thus enable the toggle). In that case, you can just turn on the toggle instead and the system will auto-detect your URL for you.

> And then the other question is should that toggle be on by default when you connect to Nabu Casa Cloud?

It is on by default.

>  I have never (to the best of my knowledge) configured a custom URL, so I'm just not sure why its in this state.

At some point, you did :) By default, the external URL has no value (and thus auto-detects) and the toggle is on. This has been the default since these options have spawned.

There is 1 exception if you have an installation that is from before the introduction of the internal/external URL (which was introduced 3 years ago or something), at the time we had to migrate older options to the new format from YAML configuration (but that means it was manual at the time in YAML as well).

**Comment by sam-ward** [comment]
> There is 1 exception if you have an installation that is from before the introduction of the internal/external URL (which was introduced 3 years ago or something), at the time we had to migrate older options to the new format from YAML configuration (but that means it was manual at the time in YAML as well).

I suspect that may well have been the case then,  as I do remember when that change was introduced. Either way thank you for the explanation.
