### ISSUE TITLE
energy-date-selection card comparison does not work when added manually to a custom dashboard.

### ISSUE THREAD

**Issue by White-Goblin** [home-assistant/frontend#12926]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The compare button doesn't do anything when energy cards are added to a custom dashboard.
![image_2022-06-09_171829769](https://user-images.githubusercontent.com/22333293/172965921-ee9d3808-e676-4e55-a4e1-b64c83f3e546.png)

### Describe the behavior you expected

The compare button should change other energy cards to show the comparisons, same as the real energy dashboard.

### Steps to reproduce the issue

1. Add energy cards to a new dashboard, at least the energy-date-selection and one other
2. Toggle comparison button on energy-date-selection card
3. Nothing changes.
...

### What version of Home Assistant Core has the issue?

2022.6.4

### In which browser are you experiencing the issue with?

Firefox 101.0, Opera 87.0.4390.45

### Which operating system are you using to run this browser?

Windows 11

**Comment by Tommatheussen** [comment]
Interesting note, when you toggle the compare mode on the manual dashboard, it actually toggles the comparison mode on the auto generated Energy dashboard.

**Comment by Mrtenz** [comment]
I'm running into this issue too.

**Comment by Tommatheussen** [comment]
It looks like this is now correctly working for me in version 2022.10.3 (didn't try earlier versions of 2022.10)

**Comment by Motik68** [comment]
This is still not working for me (2022.10.5).

**Comment by lfrlucas** [comment]
I'm running into this issue too, using 2022.10.5.

**Comment by karwosts** [comment]
Created PR #16579 with the bugfix for this issue.
