### ISSUE TITLE
input_number (mode: box): more-info looks weird

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#12945]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If an `input_number` helper created with a "mode: box" option, then it is displayed weirdly in a more-info popup:
![изображение](https://user-images.githubusercontent.com/71872483/173267032-dff02c43-be3a-4204-8446-efdf22fc4e97.png)
There is no need to display same info "value unit" TWICE - in a box and on the right side.
Also, the current value "16" is not fully displayed since the box is too narrow.

Code for the helper:
```
  min: 1
  max: 60
  step: 1
  mode: box
  unit_of_measurement: мин
  icon: mdi:clock
```

### Describe the behavior you expected

The "value + unit" should be displayed in the box only.

### Steps to reproduce the issue

1. Create a helper.
2. Open more-info for the helper.

### What version of Home Assistant Core has the issue?

2022.6.5

### In which browser are you experiencing the issue with?

Chrome 102.0.5005.115

### Which operating system are you using to run this browser?

Win10x64

**Comment by Mariusthvdb** [comment]
as reported today in #beta, this also happens on the number entity, which is created in a core integration

<img width="455" alt="Schermafbeelding 2022-07-31 om 20 48 01" src="https://user-images.githubusercontent.com/33354141/182042973-a84ee056-eb3e-48da-bfc1-0b16966a97c9.png">

so let me add to this issue, as it seems its identical.

- names are illegible if a bit longer than a single word
- up/down arrows are way too tiny
- and covering the number it is supposed to set
- number is displayed twice.
