### ISSUE TITLE
Step size/min/max in decimals incorrectly showing Red

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#12943]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

<img width="405" alt="Schermafbeelding 2022-06-13 om 10 28 54" src="https://user-images.githubusercontent.com/33354141/173346393-88b9da62-f9e7-4131-a1ee-e3b62c9742db.png">

turns out this works after all, when clicking on Create

Shouldn't turn red though, indicating an error

### Describe the behavior you expected

dont show red

### Steps to reproduce the issue

1. create Input number in UI
2. use decimals in the step size
3.
...

### What version of Home Assistant Core has the issue?

2022.7.0.dev20220612

### In which browser are you experiencing the issue with?

Any

### Which operating system are you using to run this browser?

macOS 12.4

### Additional information

Result, is showing correctly, and also working as it should
<img width="404" alt="Schermafbeelding 2022-06-12 om 21 05 50" src="https://user-images.githubusercontent.com/33354141/173254297-57f0e9ea-e94f-4b99-8bf9-f434be90dfbc.png">

**Comment by spali** [comment]
Can confirm this on 2022.8.3.
Testing my integration with step smaller than 0.001 does a wrong validation in the UI but allows to save.

There is also a bug with more info dialog and number entities where you can't enter fractions that start with a leading 0. They are corrected to rounded values... but embedding the number entity in an entities card works.

**Comment by Mariusthvdb** [comment]
not fixed,

we now cant even use any decimal at all in the max value.
when typing the . after an initial number, the field returns to 0 immediately 

also, there's no cancel button, only a back button

**Comment by karwosts** [comment]
I tested this and it seems to be working for me. I entered several decimal values without a problem and the fields did not show red. I guess this is probably fixed. Comment if you still see an issue.
