### ISSUE TITLE
Developer > Current Entities picks wrong entity

### ISSUE THREAD

**Issue by iprak** [home-assistant/frontend#12955]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Developer Tools  > Current entities lookup seems to force search by name even though one might have picked an entity by entity id.

### Describe the behavior you expected

I would expect the entity which I picked to stay in view and not get replaced.

### Steps to reproduce the issue

I happened to have 2 entities with the name "Living Room".
![image](https://user-images.githubusercontent.com/6459774/173470948-2b11b754-a539-4d56-9382-584d375d5b11.png)

Searching by climate. gives the only climate entity which I have.
![image](https://user-images.githubusercontent.com/6459774/173470719-cb754661-b101-4166-a8a9-0365c463f506.png)

Picking this shows correct entity; the focus is still in the field at this point
![image](https://user-images.githubusercontent.com/6459774/173470779-3017d4a8-7ed0-4c63-a35e-b0e7cb125f7b.png)

But clicking anywhere brings the first result based on "Living Room" which is very confusing:
![image](https://user-images.githubusercontent.com/6459774/173470897-54349326-afa5-4ff0-b067-998fbd428ed6.png)

### What version of Home Assistant Core has the issue?

2022.6.5

### Which operating system are you using to run this browser?

Win11

**Comment by jojpero** [comment]
I'm experiencing the same issue under "history".

After selecting proximity.home and clicking anywhere in the application/browser window the selection changes to zone.home

The issue appears whenever entities with different domains share the same name.
