### ISSUE TITLE
:0.0 Script error

### ISSUE THREAD

**Issue by JachinY** [home-assistant/frontend#12986]
### The problem

Logger: frontend.js.latest.202206010
Source: components/system_log/__init__.py:190 
First occurred: 11:59:04 (6 occurrences) 
Last logged: 13:12:21

:0:0 Script error.

### What version of Home Assistant Core has the issue?

2022.6.6

### What type of installation are you running?

Home Assistant OS

**Comment by pedolsky** [comment]
up
