### ISSUE TITLE
Please reopen #11579

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/frontend#12980]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The stale bot closed the ticket, but the bug has never been fixed.

#11579

### Describe the behavior you expected

Stale bot should be deleted :)

### Steps to reproduce the issue

1. Follow the steps in #11579
2. See the bug

### What version of Home Assistant Core has the issue?

core-2022.2.2,core-2022.3,core-2022.4,core-2022.5,core-2022.6

### In which browser are you experiencing the issue with?

Firefox 101.0.1 / Chromium Version 102.0.5005.61 (Official Build, ungoogled-chromium)

### Which operating system are you using to run this browser?

Windows 11 / Linux

**Comment by RubenKelevra** [comment]
@zsarnett it's still locked :/

**Comment by zsarnett** [comment]
done
