### ISSUE TITLE
Reboot guidance in settings is misleading

### ISSUE THREAD

**Issue by RonSpawnson** [home-assistant/frontend#12983]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I want to report a rough-edge in the UI experience with latest version of Home Assistant (2022.6.6)

When I click “Settings” in bottom left nav-bar, the “System” item mentions “Create backups, check logs or reboot your system”. But when I click that “System” item, the option to reboot the system is nowhere to be found. I clicked into each of the sub-sections within System and none of them had an option to reboot. Per https://community.home-assistant.io/t/ha-restart-new-update/419830/8 it appears the Reboot option has been moved to the Dev Tools -> YAML.  

I propose we should either (A) have a clear and obvious way to reboot after clicking the "Settings -> System" section or (B) remove verbiage about being able to reboot from the system item. I personally prefer (A) but if that conflicts with other initiatives, then (B) is acceptable as well.

### Describe the behavior you expected

I expected to be able to find a way to reboot after clicking Settings -> System per the description of System on the Settings page. 

### Steps to reproduce the issue

1. Click on Settings.
2. Observe the description for "System" mentions you can reboot in that section
3. Click on System
4. Notice there is no clear/obvious way of rebooting from here
...

### What version of Home Assistant Core has the issue?

2022.6.6

**Comment by RonSpawnson** [comment]
Update - I see the reboot button is in the top right of "System" section. I'm not sure why it took me so long to see that, I'm assuming because I wasn't expecting there to be a button in the header.

You can either resolve this issue since there is a reboot button, or take it as feedback that button an action button in the top-right is a confusing location with the new UI. Thanks!

**Comment by tomlut** [comment]
Yeah that is not a "reboot". Booting involves "pulling yourself up by your bootstraps", i.e. a low level hardware "reboot". This is actually restarting the Home Assistant server and should be changed to:

![Screenshot 2022-06-20 at 08-53-45 Settings – Home Assistant](https://user-images.githubusercontent.com/10679300/174503388-d5c9360e-ced3-4f69-949c-0c9119402c04.png)
