### ISSUE TITLE
Change in knx select shows error

### ISSUE THREAD

**Issue by bernji** [home-assistant/frontend#12995]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This bug is a follow up from https://github.com/home-assistant/core/issues/73751

When I choose something from knx select I get the error "failed to call service select/select_option. must contain at least one of entity_id, device_id, area_id"

Nothing is send via KNX bus and no errors are logged which concludes that this is a frontend issue. Incoming messages from KNX reflect correctly in the UI but sending (changing the drodown) does not work and shows the error above

### Describe the behavior you expected

I expect that no errors are shown and a message of the chosen option is sent via KNX

### Steps to reproduce the issue

That's a hard one. In the ticket https://github.com/home-assistant/core/issues/73751 @farmio  said that the configuration I used works for him. I would appreciate some help so that you can reproduce the issue

### What version of Home Assistant Core has the issue?

2022.6.7

### In which browser are you experiencing the issue with?

Google Chrome Version 102.0.5005.115 and Microsoft Edge Version 102.0.1245.44

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
select.lueftung_luftungsstufe
Lueftung.Lüftungsstufe
Stufe 2	options: Abwesend, Stufe 1, Stufe 2, Stufe 3
friendly_name: Lueftung.Lüftungsstufe
```

### Problem-relevant frontend configuration

```yaml
cards:
  - type: entities
    entities:
      - select.lueftung_luftungsstufe
```

### Javascript errors shown in your browser console/inspector

```txt
styles.ts:369 Uncaught (in promise) 
Object
code: "invalid_format"
message: "must contain at least one of entity_id, device_id, area_id."
[[Prototype]]: Object
constructor: ƒ Object()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
__proto__: (...)
get __proto__: ƒ __proto__()
set __proto__: ƒ __proto__()
```

### Additional information

knx:
  select:
    - name: Lueftung.Lüftungsstufe
      address: "4/0/0"
      state_address: "4/0/1"
      payload_length: 1
      options:
        - option: "Abwesend"
          payload: 0
        - option: "Stufe 1"
          payload: 1
        - option: "Stufe 2"
          payload: 2
        - option: "Stufe 3"
          payload: 3

**Comment by spacegaier** [comment]
Do you still face the reported issue? I just tested it in my dev instance (2022.9) and same as @farmio I was not able to reproduce the issue. I get no errors and can see telegrams arriving in ETS.

**Comment by csanner** [comment]
This issue still exists.
