### ISSUE TITLE
iFraming Home Assitant.

### ISSUE THREAD

**Issue by EricFROL** [home-assistant/frontend#12994]
### The problem

I'm using organizr, and I would like to iFrame HA.
Lovelace works, but when trying to get into some addon (such as LogViewer) I get:
 `401: Unauthorized`. 

What should I do?

### What version of Home Assistant Core has the issue?

core-2022.6.5

### What type of installation are you running?

Home Assistant Core

**Comment by zsarnett** [comment]
iFrame's will most likely not work well with Ingress Addons. Make sure to use an https URL. Otherwise please ask in the community forums for more guidance

**Comment by zsarnett** [comment]
iFrame's do not like Cross Origin Requests. Please research iFrame rules
