### ISSUE TITLE
All Add-ons show without color, and seem Inactive

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#12993]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

<img width="1263" alt="Schermafbeelding 2022-06-22 om 14 49 25" src="https://user-images.githubusercontent.com/33354141/175033951-f2de5d63-d19e-41e3-86de-a7b25813fdad.png">

while the actual add-ons panel shows correctly:

<img width="1071" alt="Schermafbeelding 2022-06-22 om 14 53 42" src="https://user-images.githubusercontent.com/33354141/175033893-fe7f0971-dbfc-4fa5-ad90-32892e5332cd.png">

<img width="1048" alt="Schermafbeelding 2022-06-22 om 14 55 24" src="https://user-images.githubusercontent.com/33354141/175034197-1e1837e3-9ec9-4468-97ed-7855d14c5722.png">

etc 

### Describe the behavior you expected

show the Active add-ons to be colored

### Steps to reproduce the issue

1. check hassio/dashboard
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.7.0.dev20220622

Supervisor 2022.06.dev2101

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

macOS 12.4

**Comment by Mariusthvdb** [comment]
right, if you can move that, please feel free

**Comment by ping-localhost** [comment]
After doing a fresh install of Home Assistant Supervised and restoring my full backup, I'm encountering this issue as well. Let me know if I can help in any way. Uninstalling/reinstalling does not seem to help nor does running `ha supervisor repair`.

**Relevant information**:
- Home Assistant Core 2022.6.7
- Home Assistant Supervisor 2022.06.0
- Frontend version: 20220601.0 - latest

**System information**:

<details>
  <summary>Click to expand</summary>
  
| Version 	| core-2022.6.7 	|
|---	|---	|
| Installation Type 	| Home Assistant Supervised 	|
| Development 	| false 	|
| Supervisor 	| true 	|
| Docker 	| true 	|
| User 	| root 	|
| Virtual Environment 	| false 	|
| Python Version 	| 3.9.12 	|
| Operating System Family 	| Linux 	|
| Operating System Version 	| 5.10.0-15-amd64 	|
| CPU Architecture 	| x86_64 	|
| Timezone 	| Europe/Amsterdam 	|

</details>

**Home Assistant Supervisor**:

<details>
  <summary>Click to expand</summary>

| Host Operating System 	| Debian GNU/Linux 11 (bullseye) 	|
|---	|---	|
| Update Channel 	| beta 	|
| Supervisor Version 	| supervisor-2022.06.0 	|
| Agent Version 	| 1.2.2 	|
| Docker Version 	| 20.10.17 	|
| Disk Total 	| 232.2 GB 	|
| Disk Used 	| 22.5 GB 	|
| Healthy 	| true 	|
| Supported 	| true 	|
| Supervisor API 	| ok 	|
| Version API 	| ok 	|
| Installed Add-ons 	| Duck DNS (1.15.0), MariaDB (2.4.0), Mosquitto broker (6.1.2) |

</details>
