### ISSUE TITLE
When multiple entities have same friendly name, entity selector dropdown changes between them

### ISSUE THREAD

**Issue by wigster** [home-assistant/frontend#13000]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have two entities with the same friendly name: cover.blind_kids and switch.blind_kids both with friendly name "Blind Kids". Entity selector dropdown lists do not preserve the chosen one, but pick the other.

### Describe the behavior you expected

The selected entity should stay selected.

### Steps to reproduce the issue

The bug is easiest to reproduce in Developer Tools/States.

Enter "cover.blind_kids" in the Set State field, select the entity with the keyboard. Click outside the field. The selected entity will switch to "switch.blind_kids".

This also happens in the UI for the entities card and whenver else I have the entity selector dropdown.

### What version of Home Assistant Core has the issue?

2022.6.7

### In which browser are you experiencing the issue with?

Edge 102, Safari iOS 15

### Which operating system are you using to run this browser?

Windows 11, iOS 15

**Comment by calisro** [comment]
Dup of 

https://github.com/home-assistant/frontend/issues/12889

I believe
