### ISSUE TITLE
Theme is not applied to HACS and SETTINGS menu

### ISSUE THREAD

**Issue by rodrigogbs** [home-assistant/frontend#13003]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After 2022.5 version, where Settings menu where created and the YAML validation where moved to new places, the themes are not applied to SETTINGS and HACS menu.

### Describe the behavior you expected

The whole system must follow the theme applied (font, size, color, etc.).

### Steps to reproduce the issue

1. Create a new theme
2. Apply to the system
3. Check if dashboards are following the new theme, just fo confirm that the theme was applied
4. Check the SETTINGS and HACS menu, both are not following the theme applied.

### What version of Home Assistant Core has the issue?

core-2022.6.7

### What was the last working version of Home Assistant Core?

core-2022.4.7

### In which browser are you experiencing the issue with?

Google Chrome 102.0.5005.115

### Which operating system are you using to run this browser?

masOS Monterey (12.4)

**Comment by frenck** [comment]
Hi there @rodrigogbs 👋 

HACS is a custom integration, not supported by the Home Assistant project. Please report your issue with the HACS project instead.

Thanks! 👍 

../Frenck

**Comment by rodrigogbs** [comment]
@frenck tks! Ok about HACS menu, but what about the SETTINGS menu?
