### ISSUE TITLE
incorrect anchors not correctly displayed (since json helper?)

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#13017]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

using anchors in dashboard files has always worked nicely, especially when making a mistake… it would simply state things like ‘missing anchor’ or ‘anchor not defined’ Not exactly sure.

And, it did show the card yaml in a placeholder in the Dashboard view.

With the new yaml checker however, this turns into a cryptic
<img width="524" alt="Schermafbeelding 2022-06-27 om 14 13 07" src="https://user-images.githubusercontent.com/33354141/175946975-d11bd002-8107-47b2-957c-69eef12dfe53.png">

which is simply not true, and an even odder error in the inspector, see below.

<img width="757" alt="Schermafbeelding 2022-06-27 om 14 34 52" src="https://user-images.githubusercontent.com/33354141/175947468-279ad348-8421-40aa-8e92-e1839d24b24f.png">

the test card I use hasn’t even got a logbook card configured.

### Describe the behavior you expected

more concise error description and a placeholder with the card yaml in the dashboard (like before)

### Steps to reproduce the issue

1. use an incorrect yaml anchor in the dashboard view
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.7.0.dev20220627

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

macOS 12.4

### Problem-relevant frontend configuration

simply do: 

```yaml

type: entities
title: Alarmclock settings
show_header_toggle: false
state_color: true
entities: *entities
```

without having declared a &entities anchor

### Javascript errors shown in your browser console/inspector

<img width="774" alt="Schermafbeelding 2022-06-27 om 15 01 50" src="https://user-images.githubusercontent.com/33354141/175947911-1831f7e0-c41d-4068-8ca9-036d91e7ed30.png">

### Additional information

related to: https://github.com/home-assistant/core/pull/73874

**Comment by bdraco** [comment]
<img width="971" alt="Screen Shot 2022-06-27 at 10 40 47" src="https://user-images.githubusercontent.com/663432/175979523-4d58e41a-139b-4ad8-8d99-55ef59e0c199.png">
<img width="547" alt="Screen Shot 2022-06-27 at 10 39 10" src="https://user-images.githubusercontent.com/663432/175979526-fe199477-873b-4f0f-b5fe-76cb71c2b1e5.png">
This is what I see on dev with two different systems

**Comment by Mariusthvdb** [comment]
detail: I am using yaml mode and dont use the UI editor

**Comment by bdraco** [comment]
<img width="841" alt="Screen Shot 2022-06-27 at 14 27 04" src="https://user-images.githubusercontent.com/663432/176020375-62400493-9694-441d-b4a1-8f5405054278.png">

Editing in the YAML editor also shows the error

**Comment by bdraco** [comment]
```
found undefined alias 'entities' in "/Users/bdraco/home-assistant/config/ui-lovelace.yaml", line 370, column 19
```
Here is what I get in yaml mode as well

**Comment by Mariusthvdb** [comment]
yes, thats what I saw before.
Currently al I am seeing is what I posted above in Inspector and the Frontend .
Even the home_assistant.log are quiet, both in Log viewer, and in the log itself.

**Comment by bdraco** [comment]
Since I'm having trouble reproing, can you post exact replication steps/video?

**Comment by Mariusthvdb** [comment]
first:
in my ui configured dashboard for testing purposes I indeed see:

<img width="1008" alt="Schermafbeelding 2022-06-28 om 07 12 31" src="https://user-images.githubusercontent.com/33354141/176098648-fbce2559-2cb8-432f-be50-65d4c97aceb3.png">

as for the Yaml based dashboards:


![Jun-28-2022 07-17-21](https://user-images.githubusercontent.com/33354141/176098552-9cccf82f-fab4-45c4-8967-3ed13e7434db.gif)

**Comment by Mariusthvdb** [comment]
just as a related yaml issue, I yesterday was struggling to have several entities in a package go unavailable, without any reasonable clue...

turned out, they we're a;; inside a singel package, with also had an automation with yaml issue.

before, this did error out on that single automation, and didnt block the full package...Could this be a side effect of the new yaml interpreter?
