### ISSUE TITLE
Lovelace history-graph is not refreshing after upgrade to 2022.6.7

### ISSUE THREAD

**Issue by peterk6502** [home-assistant/frontend#13012]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After upgrading to the latest version 2022.6.7 the lovelace history graph does not auto refresh anymore, only a browser refresh will display the correct data. It did work correctly before the upgrade. (I don't know which version I had before the upgrade, it was more then 1 year old).

### Describe the behavior you expected

I expect the graph to be auto refreshed when new data becomes available or when refresh_interval expires.
I have experimented with different values for refresh_interval, but with no effect.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2022.6.7

### In which browser are you experiencing the issue with?

Firefox 88.0.1 (64-bit)

### Which operating system are you using to run this browser?

Fedora 32: 5.11.22-100.fc32.x86_64

### Additional information

Version | core-2022.6.7
Installation Type | Home Assistant Core
Development | false
Supervisor | false
Docker | false
Virtual Environment | true
Python Version | 3.9.9
Operating System Family | Linux
Operating System Version | 5.14.18-100.fc33.x86_64
CPU Architecture | x86_64
Timezone | Europe/Amsterdam

**Comment by ildar170975** [comment]
same as https://github.com/home-assistant/frontend/issues/12859, https://github.com/home-assistant/frontend/issues/12999
