### ISSUE TITLE
Devices | Integration can't get to three dots for Integration options

### ISSUE THREAD

**Issue by al-jimenez** [home-assistant/frontend#13014]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In my integration with "TP-Link Kasa Smart" I have many devices and the integration window scrolls up and down for the list of devices,  but the three vertical dots that are available on all other integrations is not accessible.   I need to "reload" the integration and cannot access that or any of the other options.   

There may be another way to access this or this integration may not support this option but the all other integrations have the three vertical dots except this one.   It looks like a UI issue because the device list scrolls within the window and is not available anywhere else that I can tell.

### Describe the behavior you expected

When view all the integrations, they all have the "three vertical dots" on the lower left hand side of the integration dialog box.  But with TP-Link Kasa Smart devices are listed within this window and no other UI components are available (CONFIGURE link or "three vertical dots".

This was tried on macOS Safari & Google Chrome

### Steps to reproduce the issue

1. Go to "Settings" | "Devices & Services" under "Integrations" tab
2. Scroll down to "TP-Link Kasa Smart" integration dialog box
3. Look for "three vertical dots" on the lower left hand side of the integration dialog box...  not available
4. You can scroll down the lone list of my available devices but at the end of the list there is no other UI elements available.5. 
1st image shows "TP-Link Kasa Smart" integration dialog box with start of list...
2nd image shows "TP-Link Kasa Smart" integration dialog box with list scrolled down all the way (show part of scroll bar) 

<img width="553" alt="TP-Link Kasa-1" src="https://user-images.githubusercontent.com/8145253/175828014-6e15013d-8c7f-4564-b5ca-275f20f04f37.png">
<img width="281" alt="TP-Link Kasa-2" src="https://user-images.githubusercontent.com/8145253/175828016-59a3f511-9b2b-4ae5-8782-00b68ae6b894.png">

### What version of Home Assistant Core has the issue?

Home Assistant Core 2022.6.7  

### In which browser are you experiencing the issue with?

Safari Version 15.5 (16613.2.7.1.9, 16613) & Google Chrome Version 94.0.4606.61 (Official Build) (x86_64)

### State of relevant entities

```txt
Not related to state of entities
```

### Problem-relevant frontend configuration

```yaml
n/a
```

### Javascript errors shown in your browser console/inspector

```txt
n/a
```

### Additional information

I could not find this issue listed anywhere when I searched.  It it was and I missed it.  My apologies. 

Thanks for an awesome software package.  Good Job to all !

**Comment by zsarnett** [comment]
Click into each one to get the 3 dots

**Comment by al-jimenez** [comment]
Thanks for looking at this Zach.
