### ISSUE TITLE
Add-on Store does not show install state

### ISSUE THREAD

**Issue by tjorim** [home-assistant/frontend#13015]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The add-on STORE does not show the state (installed or not) of add-ons (introduced in supervisor 2022.06.0).

### Describe the behavior you expected

Be able to see in the add-on store which add-ons are already installed.

### Steps to reproduce the issue

1. Go to Add-on Store
2. Notice no add-ons have the installed tag/color/bar

### What version of Home Assistant Core has the issue?

core-2022.6.7

### In which browser are you experiencing the issue with?

Various

### Which operating system are you using to run this browser?

Various

### Additional information

What is the used version of the Supervisor?
supervisor-2022.06.1

What type of installation are you running?
Home Assistant OS

Which operating system are you running on?
Home Assistant Operating System

What is the version of your installed operating system?
8.2

![image](https://user-images.githubusercontent.com/1294876/175833131-41b4a006-76e6-40b3-817c-77727e794294.png)

Already had issue https://github.com/home-assistant/supervisor/issues/3697 open but got closed.
However, it's not a duplicate, it's different behaviour: started add-ons vs. installed add-ons not showing.

**Comment by steverep** [comment]
#13004 should fix this. The problem is an incorrect translation key.

**Comment by ludeeus** [comment]
I reopened https://github.com/home-assistant/supervisor/issues/3697, there is currently nothing in the store API that indicates that its installed, so its not possible for the forntend to guess.
