### ISSUE TITLE
entity history show up twice when I select a device

### ISSUE THREAD

**Issue by jweston2112** [home-assistant/frontend#13037]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I select a device and it displays the entity history just fine but I have a scroll bar and when I scroll down it is duplicated below... including the graph (if any)  

### Describe the behavior you expected

just see the history once

### Steps to reproduce the issue

1. select a device with multiple entites in history 
2. scroll down
3.
...

### What version of Home Assistant Core has the issue?

2022.7b0

### What was the last working version of Home Assistant Core?

2022.6.7

### In which browser are you experiencing the issue with?

Google Chrome, Firefox , Microsoft Edge

### Which operating system are you using to run this browser?

Kali Linux and Windows 10

### Additional information

More entites make the effect much worse

**Comment by zsarnett** [comment]
PLease provide screenshots

**Comment by jweston2112** [comment]
Sorry this is about the best I can do at my resolution
![image](https://user-images.githubusercontent.com/70152549/176553960-6228df0d-6bf5-451e-a08c-a12840fac56c.png)



I have also seen what looks like a second scroll bar (vertical) like it created a iframe or opened a second window... if that makes sense

**Comment by jweston2112** [comment]
please do not consider any of these "reports" a criticism of your work... I think you all are awesome... I am just trying to help

**Comment by jweston2112** [comment]
No problem... just wanted to make sure I didnt miss something

**Comment by jweston2112** [comment]
I believe this was corrected at Release 2022.7 (post beta)
