### ISSUE TITLE
Area selector on history tab doesn't function

### ISSUE THREAD

**Issue by drthanwho** [home-assistant/frontend#13035]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Going to history tab and selecting a specific area doesn't return all the entities of that area but instead shows nothing. Only if the area is expanded to its devices it will return entities' history.

![image](https://user-images.githubusercontent.com/22405505/176519870-f42542c9-fc3e-4d39-bda3-570397ca8f84.png)

![image](https://user-images.githubusercontent.com/22405505/176519907-54094ed3-4d93-4ad4-b62d-4ec52dc392f3.png)

### Describe the behavior you expected

To show the history of all the entities of that area

### Steps to reproduce the issue

1. Go to history
2. Select an area
3.
...

### What version of Home Assistant Core has the issue?

core-2022.7.0b0

### What was the last working version of Home Assistant Core?

N/A

**Comment by D3v01dZA** [comment]
Fixed in https://github.com/home-assistant/frontend/pull/13045 - please validate once it is merged
