### ISSUE TITLE
Datepicker in e.g. statistics adjuster not always working

### ISSUE THREAD

**Issue by slovdahl** [home-assistant/frontend#13038]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The datepicker used in e.g. the "Adjust statistic" developer tool doesn't always work. It usually works the first time it's opened, but after that, nothing happens when I click a date. It's possible to switch to another month view, but selecting a date still doesn't work. It usually helps to close the datepicker and open it again.

### Describe the behavior you expected

The datepicker should always work.

### Steps to reproduce the issue

1. Open the "Adjust statistic" dialog in Developer Tools -> Statistics -> Find an entity with statistics.
2. Open the datepicker by clicking on the date.
   ![bild](https://user-images.githubusercontent.com/1417619/176534884-a2662598-5160-40af-a1fa-ad8ece3d53fd.png)
3. Select another date.
4. Change the time, maybe open an entry, click "Back"
5. Select another date.
6. Repeat until a date cannot be selected.

### What version of Home Assistant Core has the issue?

2022.6.7 and 2022.8.0.dev0

### In which browser are you experiencing the issue with?

Firefox 102.0, Firefox 101.0.1, Chromium 103.0.5060.53

### Which operating system are you using to run this browser?

Firefox 102 on macOS 12.4, Firefox 101 and Chromium 103 on Ubuntu 20.04

**Comment by slovdahl** [comment]
Still an issue.

**Comment by slovdahl** [comment]
Interesting, I tried to reproduce this with 2022.12.7, but I cannot seem to do so. @billyburly are you still able to reproduce it with 2022.12?

**Comment by karwosts** [comment]
Given this is fixed for OP, and no new comments in half a year, gonna mark this as resolved. Feel free to add a comment or open a new issue if it shows up again.
