### ISSUE TITLE
Graph label capitalization of entity names is inconsistent in new history panel

### ISSUE THREAD

**Issue by krazos** [home-assistant/frontend#13043]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using the new selectors to select entities in the history panel, the graph labels showing the entity names are all lower case, as shown in the first screenshot of the history panel view.  My guess is that the labels are being generated using the entity_id, with underscores changed to spaces, rather than using the proper entity name.  However, this behavior is not entirely consistent, as using the area and device selectors sometimes results in labels with the proper capitalization.

### Describe the behavior you expected

Graph labels should show entity names with the proper capitalization based on the entity name, as shown in the second screenshot of the history graph card. 

### Steps to reproduce the issue

N/A

### What version of Home Assistant Core has the issue?

core-2022.7.0b0

### In which browser are you experiencing the issue with?

Google Chrome 102.0.5005.115

### Which operating system are you using to run this browser?

Pop!_OS 22.04

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
N/A
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

### Additional information

History Panel:

![Screenshot from 2022-06-29 17-12-04](https://user-images.githubusercontent.com/18428022/176546653-1de233c5-5ff6-4d90-9b67-a8efabe253b0.png)

History Graph Card:

![Screenshot from 2022-06-29 17-24-41](https://user-images.githubusercontent.com/18428022/176547574-edad945b-47f2-41ab-9598-5e74cb128230.png)

**Comment by hmmbob** [comment]
Seeing this too - When I mentioned it in beta channel on Discord was pointed towards this issue

![image](https://user-images.githubusercontent.com/33529490/177584169-3f91a8cd-b684-43aa-8fa0-37c8910a3530.png)

**Comment by BoneheadFraggle** [comment]
And it would be better/more user friendly if the friendly name was used, not a "trimmed" version of the entity name. 
After all, the friendly name is supposed to be more friendly :-)

![image](https://user-images.githubusercontent.com/2287810/177592068-98c1d306-3f4c-4838-9db5-f9d9cb207257.png)

**Comment by krazos** [comment]
I believe this was fixed by https://github.com/home-assistant/frontend/pull/13179. I am fine closing this issue, assuming no one else has lingering concerns?

**Comment by hmmbob** [comment]
Nope, confirming fixed.
