### ISSUE TITLE
Energy Dashboard on mobile missing last bar on week/month view

### ISSUE THREAD

**Issue by GSzabados** [home-assistant/frontend#13065]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Last bar of the dashboard is missing for week/month and possibly year views on mobile devices, both in the accompanying app and browser.

![20220702_134724](https://user-images.githubusercontent.com/35445496/177001676-eacaa167-e1bd-4d41-8553-1feeca4acffb.jpg)

![Screenshot_20220702-135135_Home Assistant](https://user-images.githubusercontent.com/35445496/177001690-4ff86b57-6d9e-451c-a176-56f219ae43cf.jpg)

### Describe the behavior you expected

Display the last days of the week and last day of the month as well.

### Steps to reproduce the issue

1. Open Energy Dashboard in the Mobile app. (Android)
2. Change the display to week or month.
...

### What version of Home Assistant Core has the issue?

core-2022.6.7

### In which browser are you experiencing the issue with?

Google Chrome Mobile 103.0.5060.70

### Which operating system are you using to run this browser?

Android 10

### Problem-relevant frontend configuration

```yaml
Default Energy Dashboard
```

### Additional information

I believe it was working on 2022.5.X before the compare option has been added, but result with comparison turned on is the same, last bar is missing.

**Comment by dshokouhi** [comment]
> but it might be a WebView (Android) issue generally.

you mention in the ticket that both the app and the browser on the same device have the issue

`Last bar of the dashboard is missing for week/month and possibly year views on mobile devices, both in the accompanying app and browser.`

 so it is not a webview issue but more a general frontend issue impacting mobile devices.

I dont use the energy dashboard so I won't be able to check anything from my end.

**Comment by GSzabados** [comment]
> so it is not a webview issue but more a general frontend issue impacting mobile devices

I generally use the app, but tried from the Chrome (Android) browser as well. Both shows the same issue. I am, to be honest, not 100% sure that how much they are differing from each other regarding rendering. That's why I tagged you, hoping that you might have range of resources to cross check the Android app. Thanks for the reply!

I will pop-in to Discord then to ask somebody there to confirm the same behavior, as it used to be working an HA version before 2022.6.X, I am a bit away to update to 2022.7.X yet.

**Comment by GSzabados** [comment]
It seems to be fixed in 2022.8.2. Issue closed!

![Screenshot_20220809-165025_Home Assistant](https://user-images.githubusercontent.com/35445496/183681147-633631c3-5de6-4275-a0b6-fb20b57eb461.jpg)
