### ISSUE TITLE
Area Automations / Scripts / Scenes incorrectly labeled?

### ISSUE THREAD

**Issue by Spookster** [home-assistant/frontend#13074]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Labels used in the 'Area' UI appear to be wrongly labeled.
If there are no automations / scenes/ scripts assigned to an area, they are displayed with correct headings:

- Devices
- Entities
- Automations
- Scenes
- Scripts

![image](https://user-images.githubusercontent.com/982535/177227334-e52ae25a-6d44-4d96-a4d4-050660d3f61b.png)

If there is an automations / scene/ script, then the heading is changed to 'Targeting this area:' which is less intuitive than displaying the actual heading

![image](https://user-images.githubusercontent.com/982535/177244535-a2039cb2-3c56-4818-bb58-92e70e9cf287.png)

### Describe the behavior you expected

I would expect the headings not to change as they relate to the content of the automations / scene/ script container box

### Steps to reproduce the issue

1. Settings
2. Area / Zones
3. User UI
...

### What version of Home Assistant Core has the issue?

Core 2022.6.7

### What was the last working version of Home Assistant Core?

Core 2022.6.7

### In which browser are you experiencing the issue with?

Chrome / Firefox / Android

### Which operating system are you using to run this browser?

Windows / Android

**Comment by Spookster** [comment]
If you check settings > devices & services > devices > (single device) the headings are logical and as expected.

![image](https://user-images.githubusercontent.com/982535/177244354-b5c933a1-3b44-48bb-9d17-db9d5c8cb1d9.png)

**Comment by Spookster** [comment]
This issue still remains in version:

 Home Assistant 2022.9.7 Supervisor 2022.09.1 Operating System 9.0 Frontend 20220907.2 - latest

**Comment by bramkragten** [comment]
I can not reproduce?

![CleanShot 2022-10-03 at 11 24 16](https://user-images.githubusercontent.com/5662298/193543946-8efbfe98-7b65-4ee1-a283-c8c054c737e8.png)

**Comment by bramkragten** [comment]
https://github.com/thomasloven/lovelace-card-mod/issues/222
