### ISSUE TITLE
Cannot close the shutter via Aeotec Nano Shutter V.3 and ZwaveJSMQTT

### ISSUE THREAD

**Issue by Arthedian** [home-assistant/frontend#13071]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I had Aeotec Nano Shutter V.2 and I could open a close the shutters without the problem. The problem was, that it wasn't able to stop in the middle. So I made software update to Aeotec Nano Shutter V.3, Sadly now I can only close the shutters via GUI, but even in the middle. If I want to open the shutter, I need to go the zwaveJSMQTT panel, go to the device, "Configuration v4" and manually open the shutter through the value, so definitely its not hardware issue. The button for closing is always grey

### Describe the behavior you expected

Open and close the shutters via GUI

### Steps to reproduce the issue

1. Connect the Aeotec Nano Shutter V.3 via zwavejsmqtt to HA
2. Add control to GUI for this device
3. Try to open and close the shutters

### What version of Home Assistant Core has the issue?

Home Assistant Core 2022.6.6

**Comment by Arthedian** [comment]
@raman325 could you please have a look at it?

**Comment by raman325** [comment]
did you try restarting HA? we've heard that after a firmware update, HA stops receiving updates from the node - still investigating, but apparently a restart fixes it.

**Comment by Arthedian** [comment]
the node itself is responding, through HA GUI only in one direction, but through zwaveJS GUI (I have zwavejsmqtt plugin) it is working precisely as it should

**Comment by spacegaier** [comment]
Can you please post the entity YAML state of the cover into the ticket template.

**Comment by raman325** [comment]
> the node itself is responding, through HA GUI only in one direction, but through zwaveJS GUI (I have zwavejsmqtt plugin) it is working precisely as it should

this is resolved in https://github.com/home-assistant/core/pull/77915 and will be released with 2022.9 tomorrow/today

**Comment by Arthedian** [comment]
It's fixed
