### ISSUE TITLE
Inconsistent Naming in Climate card presets

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#13082]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

see: https://community.home-assistant.io/t/plugwise-core-and-custom-component/236250/213?u=mariusthvdb
![image](https://user-images.githubusercontent.com/33354141/177280765-1423b512-da5d-44bf-8aec-942a0d456594.png)

### Describe the behavior you expected

All using |capitalize, and all displayed without underscore, so

No frost
Vacation
Asleep (or Sleep)
Home
Away

### Steps to reproduce the issue

1. click climate card
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.8.0.dev20220704

### In which browser are you experiencing the issue with?

Any

### Which operating system are you using to run this browser?

macOS 12.4

### Additional information

this is for the core Plugwise integration

**Comment by frenck** [comment]
This is not a frontend issue, but a known backend limitation.
Presets are not translatable, except for the built-in presets (which causes the inconsistency).

**Comment by Mariusthvdb** [comment]
sorry for the wrong repo..

as Bouwe says:

> Plugwise preset asleep could be renamed to match HA Core preset sleep.
> But preset for vacation and no_frost would need to be added to HA Core.

could that be added in core then?

**Comment by frenck** [comment]
> Plugwise preset asleep could be renamed to match HA Core preset sleep.
But preset for vacation and no_frost would need to be added to HA Core.

> could that be added in core then?

You are missing the point, the answer was in my previous message.

Presets are not translatable

**Comment by Mariusthvdb** [comment]
missing it, probably..
you said: can not translate what is not built-in. thats clear as cristal.

my question is, can those be built in, which is also what Bouwe seems to suggest?

**Comment by frenck** [comment]
> my question is, can those be built in

No. The list is limited to the most generic ones, we cannot built-in every preset in the world.
Instead, it would be nice if someone added support for translating them.

**Comment by Mariusthvdb** [comment]
Ok thanks. Frenck, appreciated.

Must admit I found it surprising that presets like vacation and no frost are no default modes on all systems but I take your word for it, and understand the issue alright.

If the translation support could be added, that would be a great streamlining + .

Anything we can do to get that scheduled or at least in the list of things to do?

**Comment by Mariusthvdb** [comment]
right, somehow I knew that coming ;-)

could you please point me in the right direction? I have no high hopes, but could at least have a stab at it.

**Comment by frenck** [comment]
> could you please point me in the right direction? What files need adapting.

I don't know. That needs to be investigated. We currently have no support anywhere in our translation system to translate attributes. That needs to be designed and created.

**Comment by Mariusthvdb** [comment]
right. there go my hopes for doing this....


Ill at least add a FR to the repo in the community for adding that, and see what gives. So it is noted. thanks Frenck, closing on that.
