### ISSUE TITLE
State History Sensor shows "No History" at first load - refresh fixes it

### ISSUE THREAD

**Issue by Anto79-ops** [home-assistant/frontend#13097]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi!

Using Home Assistant 2022.7.0b0, when I want to see the sensor history (any sensor), by clicking on 'show more' I'm presented with a blank history:

![no_history](https://user-images.githubusercontent.com/79593761/177365995-913e123c-a8bf-4bea-9703-3f3a6118818d.jpg)

Then I press refresh, it shows the history.

![refresh_history](https://user-images.githubusercontent.com/79593761/177366093-cbb53905-42db-4da1-bcb7-3f26cf032ba3.jpg)

### Describe the behavior you expected

to show the history on first load

### Steps to reproduce the issue

1. click Settings
2. Click devices and services
3. click entities
4. Pick any sensor
5. press control
6. press show more
7. blank history presened
8. press HA refresh button (not browser refresh button)
9. history correctly shown

### What version of Home Assistant Core has the issue?

Home Assistant 2022.7.0b0

### What was the last working version of Home Assistant Core?

Home Assistant 2022.6

### In which browser are you experiencing the issue with?

Google Chrome and Edge

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
all sensor entites
```

### Javascript errors shown in your browser console/inspector

```txt
no errors
```

**Comment by zsarnett** [comment]
This will be fixed in b5
