### ISSUE TITLE
Selected tag disappears from frontend in automation after save

### ISSUE THREAD

**Issue by smarthomejunkie** [home-assistant/frontend#13100]
### The problem

If you create an automation with a tag trigger, the selected tag disappears in the frontend after you save the automation, close the automation and open it again. It's still there in YAML. 

### What version of Home Assistant Core has the issue?

core-2022.7.0b3

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

tag

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/tag/

### Additional information

_No response
![Screenshot_26](https://user-images.githubusercontent.com/67226335/177365888-b54a02a6-bd7a-47e4-bea8-e71929376f84.png)
![Screenshot_27](https://user-images.githubusercontent.com/67226335/177365902-c62821b6-1276-4fec-ad21-9607ed325006.png)
_

**Comment by spacegaier** [comment]
Can you please check if the issue still occurs for you? I cannot reproduce it on 2022.9 (beta).

**Comment by smarthomejunkie** [comment]
Yes, this seems to be solved!
