### ISSUE TITLE
Sensor history plot shows up twice AND no text box for adding second sensor to plot

### ISSUE THREAD

**Issue by Anto79-ops** [home-assistant/frontend#13101]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When viewing sensor history for 1 sensors, plot shows up twice

![image](https://user-images.githubusercontent.com/79593761/177382996-d7c29729-28a1-4166-8e88-c77f23a877d5.png)

Scroll down on same page:

![image](https://user-images.githubusercontent.com/79593761/177383123-8975e520-b1b3-4808-9fd0-8dd34bbc4a0f.png)

same plot reappears below:

![image](https://user-images.githubusercontent.com/79593761/177383249-83e3b2c3-71b7-4f71-b6e8-c5d9b4997550.png)

Also, when I want to compare to sensors, I press "+ choose entity " a list appears. I can start typing for the sensor I want, but it doesn't show me what I'm typing BUT the list does update to what I'm typing:

![image](https://user-images.githubusercontent.com/79593761/177383568-6813d027-7ce0-4dfe-9e23-807946162189.png)

### Describe the behavior you expected

1. only 1 sensor plot
2. When adding a second sensor to compare, a text box showing what i'm typing

### Steps to reproduce the issue

Please see photos above

### What version of Home Assistant Core has the issue?

Home Assistant 2022.7.0b3

### In which browser are you experiencing the issue with?

Google Chrome and Edge

### Which operating system are you using to run this browser?

Windows 10

**Comment by zsarnett** [comment]
Will be fixed in B5
