### ISSUE TITLE
History page throws error when selecting one of my areas

### ISSUE THREAD

**Issue by krzysztofsk** [home-assistant/frontend#13127]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After selecting one of areas in history the page is just showing a spinner and in console I get error:
ha-panel-history.ts:209 Uncaught (in promise) TypeError: i is not iterable
    at r.value (ha-panel-history.ts:209:1)
    at r.value (ha-panel-history.ts:209:1)
    at r.value (ha-panel-history.ts:209:1)
    at r._$AE (styles.ts:369:1)
    at r.performUpdate (styles.ts:369:1)
    at r.scheduleUpdate (styles.ts:369:1)
    at r._$EC (styles.ts:369:1)
    at async r._$EC (styles.ts:369:1)

### Describe the behavior you expected

Should load history

### Steps to reproduce the issue

1. go to history
2. select specific area
3. page is loading all the time
4. error in console
...

### What version of Home Assistant Core has the issue?

2022.7.0

### What was the last working version of Home Assistant Core?

2022.6.x

### In which browser are you experiencing the issue with?

Chrome 103

### Which operating system are you using to run this browser?

macOS Monterey

### Javascript errors shown in your browser console/inspector

```txt
ha-panel-history.ts:209 Uncaught (in promise) TypeError: i is not iterable
    at r.value (ha-panel-history.ts:209:1)
    at r.value (ha-panel-history.ts:209:1)
    at r.value (ha-panel-history.ts:209:1)
    at r._$AE (styles.ts:369:1)
    at r.performUpdate (styles.ts:369:1)
    at r.scheduleUpdate (styles.ts:369:1)
    at r._$EC (styles.ts:369:1)
    at async r._$EC (styles.ts:369:1)
```

**Comment by Mraedis** [comment]
I have the same issue, with the same error. This only happens with 2 specific areas AND loading each individual area's devices DOES work.

Clicking on the "Clear filters" button works though, and then you can refresh the page.

One of my areas has these devices:
-Goodwe (from Goodwe integration)
-P1 Meter (from HomeWizard integration)
-Sagem internet gateway device (from upnp)
-Solar production forecast
-Zigbee Coordinator (Conbee II)

**Comment by krzysztofsk** [comment]
To fix this issue before we will have a permanent fix, you can just remove devices that has no entities from the area. In my case I had to remove Z-Wave stick from the area.
