### ISSUE TITLE
Update Restore backup dialog 

### ISSUE THREAD

**Issue by matthiasdebaat** [home-assistant/frontend#13136]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Our settings dialogs aren't consistent. Also we're workin towards a Material Design 3 dialog design https://github.com/home-assistant/frontend/issues/13084 
<img width="1396" alt="CleanShot 2022-07-07 at 13 54 09@2x" src="https://user-images.githubusercontent.com/20203284/177767222-0f03f3ea-ca7b-42f3-a7f7-f3328b5c6e9e.png">

### Describe the behavior you expected

Content changes:
- Let the background shadow also overlap the sidebar
- Use sentence case for the title
- Change title to `Restore backup`
- Add subtitle `[backup name]`
- Change password input to new component with eye icon to show/hide password
- Change subtitle to `Select what to restore`
- Radio buttons vertical order
- Add `Cancel` button
- Move `Restore` button to the right and change it to warning
- Move delete and download to the table and delete overflow menu

<img width="1393" alt="CleanShot 2022-07-07 at 13 54 13@2x" src="https://user-images.githubusercontent.com/20203284/177767245-c0ed0157-a280-4a46-8d82-0ad84467117f.png">

### Steps to reproduce the issue

1. Settings
2. System
3. Backups
4. Open backup

### What version of Home Assistant Core has the issue?

core-2022.6.7

**Comment by matthiasdebaat** [comment]
Stil an issue

**Comment by ChrisCarini** [comment]
@matthiasdebaat the latest version seems to have some (all?) of the items specified taken care of; is this issue still relevant?

**Comment by matthiasdebaat** [comment]
Just checked. Only the rounded corners changed.

These changes are still open:
- Let the background shadow also overlap the sidebar
- Use sentence case for the title
- Change title to Restore backup
- Add subtitle [backup name]
- Change password input to new component with eye icon to show/hide password
- Change subtitle to Select what to restore
- Radio buttons vertical order
- Add Cancel button
- Move Restore button to the right and change it to warning
- Move delete and download to the table and delete overflow menu
