### ISSUE TITLE
History page not responding

### ISSUE THREAD

**Issue by zigomatichub** [home-assistant/frontend#13141]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing
Thank you Zack for this big work. It's awesome and my little contribution is to open this ... omg.
I'm selecting an area and the page never response.  Restart HA not helping.

If I'm filter by device and add one by one device that are in this area, it works.
Not all area are not responding but it is always the same that are failing vs displayed ok.

To remove the selection, I use F12 -> remove the historyPickedvalue from the local storage.
I check the area id : some have string and some have hexa number but apparently it's not link to that.

example: 
device selection is ok:
![image](https://user-images.githubusercontent.com/60198279/177844184-d608242d-9584-4061-9e5c-11cac5c73631.png)

area "bureau" which contain the same devices keep the page not responding.

I'm having the same issue on the compagnion app android.

### Describe the behavior you expected

The page should answer or give a timeout or a way to cut the execution

### Steps to reproduce the issue

1. no idea how to reproduce this in another HA instance
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2022.7.0

### What was the last working version of Home Assistant Core?

NA

### In which browser are you experiencing the issue with?

Version 103.0.5060.114 

### Which operating system are you using to run this browser?

Windows 11

### Javascript errors shown in your browser console/inspector

```txt
From developper tools - console: 
ha-panel-history.ts:209 Uncaught (in promise) TypeError: i is not iterable
    at r.value (ha-panel-history.ts:209:1)
    at r.value (ha-panel-history.ts:209:1)
    at r.value (ha-panel-history.ts:209:1)
    at r._$AE (styles.ts:369:1)
    at r.performUpdate (styles.ts:369:1)
    at r.scheduleUpdate (styles.ts:369:1)
    at r._$EC (styles.ts:369:1)
    at async r._$EC (styles.ts:369:1)
```

**Comment by zsarnett** [comment]
Fixed in 2022.07.1
