### ISSUE TITLE
Unable to load history page after 2022.7.0 update

### ISSUE THREAD

**Issue by zengshengliu** [home-assistant/frontend#13147]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the history page, after I select an area, the history page is stuck in "loading".
![image](https://user-images.githubusercontent.com/2967322/177938416-3eaa47ff-617b-4737-a7d4-a0e93201ead4.png)

### Describe the behavior you expected

History page should load correctly with entity in the area shown (or error page if not able to load)

### Steps to reproduce the issue

1. Open history page
2. Select an area (in my case, I pick "My Bedroom")
3. The screen stuck in loading
4. I also tried the same step in Home Assistant android app with same "issue"

### What version of Home Assistant Core has the issue?

2022.7.0

### What was the last working version of Home Assistant Core?

2022.6

### In which browser are you experiencing the issue with?

Google Chrome 103.0.5060.114

### Which operating system are you using to run this browser?

Windows 11 (x64)

### Javascript errors shown in your browser console/inspector

```txt
Uncaught (in promise) TypeError: i is not iterable
    at r.value (ha-panel-history.ts:209:1)
    at r.value (ha-panel-history.ts:209:1)
    at r.value (ha-panel-history.ts:209:1)
    at r._$AE (styles.ts:369:1)
    at r.performUpdate (styles.ts:369:1)
    at r.scheduleUpdate (styles.ts:369:1)
    at r._$EC (styles.ts:369:1)
```

### Additional information

![image](https://user-images.githubusercontent.com/2967322/177939148-c1d23769-7f19-4601-81ff-0fa5df79780e.png)

**Comment by jmsprsns** [comment]
This issue persists in 2022.7.3, 2022.7.4 and 2022.7.5 - rolling back to old backups didn't resolve this bug.

**Comment by nottledim** [comment]
This issue persists in 2022.9.2  Is it not possible to fix it?  It seems fairly serious to me when when a basic side panel is completely non-functional.

```
9f5922e0.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'unit_of_measurement')
    at o (9f5922e0.js:1:5308)
    at d (9f5922e0.js:1:3481)
    at state-history-charts.ts:17:1
    at state-history-charts.ts:17:1
    at Array.forEach (<anonymous>)
    at h (state-history-charts.ts:17:1)
    at r.value (ha-panel-history.ts:115:1)
```
