### ISSUE TITLE
Weather Forecast Card - Timezone problem

### ISSUE THREAD

**Issue by Makin-Things** [home-assistant/frontend#13145]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If you create a Weather Forecast card and select an hourly weather entity for that is in a different timezone it shows the wrong times on the card. Here are some examples (I am located in the timezone ``Australia/Sydney`` where it is currently 3:20pm).

![image](https://user-images.githubusercontent.com/91187456/177922548-44c3e572-0ff4-44c8-95ff-30a6d9ee1de7.png)
This is Canada/British Columbia where the current local time is currently 10:20pm

![image](https://user-images.githubusercontent.com/91187456/177922843-cea99365-0eaa-47af-a129-0509b01459ec.png)
And this is Netherlands/Amsterdam where it is currently 7:20am.

Both cards show the times using my local timezone.

### Describe the behavior you expected

For this card I would expect it to display the times in the timezone of where the sensor is located, not the timezone of the HA server.
The examples above might be a little extreme, but it is wrong. A more realistic example might be for someone that commutes between adjacent time zones for work etc (ie US east coast to US west coast). I have friends that do this in Australia.

### Steps to reproduce the issue

1. Add a weather integration for a timezone different to where the HA server is located (make sure to enable the hourly forecast).
2. Create a Weather Forecast card and use the new hourly weather entity.
3. Observe that the times are shown in local time rather than sensor time.
...

### What version of Home Assistant Core has the issue?

2022.7.0

### What was the last working version of Home Assistant Core?

N/A

### In which browser are you experiencing the issue with?

Firefox and Chrome (latest versions)

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
The current attributes of the weather.vancouver_hourly entity.

temperature: 15
temperature_unit: °C
humidity: 100
pressure: 1018
pressure_unit: hPa
wind_bearing: 46
wind_speed: 6
wind_speed_unit: km/h
visibility: 32.2
visibility_unit: km
precipitation_unit: mm
forecast: 
- datetime: '2022-07-08T06:00:00+00:00'
  condition: partlycloudy
  precipitation_probability: 0
  temperature: 15
- datetime: '2022-07-08T07:00:00+00:00'
  condition: partlycloudy
  precipitation_probability: 0
  temperature: 15
- datetime: '2022-07-08T08:00:00+00:00'
  condition: partlycloudy
  precipitation_probability: 0
  temperature: 14
- datetime: '2022-07-08T09:00:00+00:00'
  condition: partlycloudy
  precipitation_probability: 0
  temperature: 14
- datetime: '2022-07-08T10:00:00+00:00'
  condition: partlycloudy
  precipitation_probability: 0
  temperature: 14
- datetime: '2022-07-08T11:00:00+00:00'
  condition: partlycloudy
  precipitation_probability: 0
  temperature: 14
- datetime: '2022-07-08T12:00:00+00:00'
  condition: partlycloudy
  precipitation_probability: 0
  temperature: 14
- datetime: '2022-07-08T13:00:00+00:00'
  condition: partlycloudy
  precipitation_probability: 0
  temperature: 14
- datetime: '2022-07-08T14:00:00+00:00'
  condition: partlycloudy
  precipitation_probability: 0
  temperature: 14
```
```


### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

For entities/sensors that aren't located in the same timezone as the HA server there should probably be an option to include the timezone as an attribute to ensure times/dates can be display correctly.

**Comment by lone-cloud** [comment]
https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/cards/hui-weather-forecast-card.ts was coded incorrectly where it frequently calls `new Date()` which just uses the browser's timezone.

**Comment by Makin-Things** [comment]
This is still an issue.
