### ISSUE TITLE
Consumption placed in the wrong hour in Energy Dashboard

### ISSUE THREAD

**Issue by magnusoverli** [home-assistant/frontend#13151]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have one of the most common electricity meters in Norway, the Kaifa MA304. It has a HAN-port that I use to read out data on the electricity, consumption and such. The meter transmits consumption every hour, 13 seconds past the hour to be exact. I then have a reader that decodes the data and transmits that to my MQTT broker. The data is hitting my HA at the same time, 13 seconds past the hour.

The problem is the 13 seconds! Say that I get a report on energy consumption at 09:00:13. This leads HA to beleive that the energy consumption has happened between 09:00:13 and the next report at 10:00:13. Conversely, this consumption is displayed as used in the wrong hour in the Energy Dahboard.

### Describe the behavior you expected

To have consumption being interpreted as having been used in the correct hour.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.7

### In which browser are you experiencing the issue with?

Google Chrome 103.0.5060.114

### Which operating system are you using to run this browser?

Windows

### Additional information

The data as recorded by the reader on the meter:
![image](https://user-images.githubusercontent.com/3475247/178021020-d34b017e-0b7c-411f-8e55-9439a2ba6d0f.png)
The data as displayed in the Energy Dashboard:
![image](https://user-images.githubusercontent.com/3475247/178020923-b5bc1546-533d-486f-8602-e371ee588724.png)

The state change as recorded by HA:
![image](https://user-images.githubusercontent.com/3475247/178021362-21306ed5-bc32-4cc7-94f0-8774db9dbf6b.png)

**Comment by Wesley-Vos** [comment]
This is not a frontend issue but an issue related to your data. Home Assistant builds statistics on the data available at xx:00:00 every hour. However, your data is sent at xx:00:13 and therefore used in the statistics of next hour introducing a delay of one hour. Your meter should send the data more often in order to fix this (and even then, it will be of by a bit because of polling rates)

**Comment by magnusoverli** [comment]
I realise that it is the timing of the data that causes the problem. But we will never have a global supplier of meters change their timing beacuse it causes a problem in HA.
I am quite certain that quite a few electricity meters reports the hourly consumption just after the hour.
Mind you, it is not my reader that is the problem, it is the meter supplied by the electricity company.
A possible solution to this would be to identify if the energy consumption reports are coming in on an hourly basis, and if so allow data that comes in within the first minute of th next hour to be calculated as the previous hour consumption.

**Comment by Wesley-Vos** [comment]
I agree that more meters has this problem. My gas meter has the same issue which I fix by running a scheduled procedure in the database to reset it. Personally, I think that it is not a frontend related bug but a HA core related wish
