### ISSUE TITLE
Text fields &  menus truncated in Automation editor, Z-wave parameter config and elsewhere

### ISSUE THREAD

**Issue by HVR88** [home-assistant/frontend#13150]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Many clickable drop-down lists/menus and their resulting text fields are truncated in the UI, making it difficult or sometimes impossible to see what list items are being selected or displayed/set.

The fields are fixed width and don't change size to accommodate their contents, nor can they be enlarged by resizing the web browser window.

This issue has previously been described in this issue: https://github.com/home-assistant/core/issues/67765 and was addressed for the specific parameter for the specific device. A permanent solution needs to be put in place for all list items across the entirety of the front end UI, as trying to address specific controls piece-meal with fixed-size formatting is always going to break in the future depending on the contents inserted into the lists. 

### Describe the behavior you expected

List boxes and text fields need to resize to show the full contents of their text items, otherwise the usability of the controls can be significantly compromized.

### Steps to reproduce the issue

1. Open the configure UI (paameter settings) of a Zooz Zen22 switch
2. Note that multiple parameters values are truncated within their list boxes/menus
3. See attached screen shots for specific details/examples

### What version of Home Assistant Core has the issue?

2022.7

### In which browser are you experiencing the issue with?

Mozilla Firefox 102.0b8

### Which operating system are you using to run this browser?

MacOS Monteray 12.5

### Additional information

**Z-Wave "Configure" Parameters for various switch devices**

**Zooz Zen22**
![zen22](https://user-images.githubusercontent.com/33399216/178015503-74ff8421-0b42-4722-8607-3fe02748c674.png)

![zen22-2](https://user-images.githubusercontent.com/33399216/178015526-3890b354-fb35-468d-8dab-985d1cae6389.png)

![zen22-3](https://user-images.githubusercontent.com/33399216/178015544-9d856425-e2dc-4da7-9ab3-43720421b065.png)

![zen22-4](https://user-images.githubusercontent.com/33399216/178015561-933fbd32-d5b7-42aa-bca4-0428b2f02673.png)

**Note here in this example, the size of the text box gets smaller to truncate even more text when the success message is displayed.**

![zen22-5](https://user-images.githubusercontent.com/33399216/178015593-1a5c46fd-3836-4e03-879e-84138101de28.png)

**Zooz Zen27 - there's no way to tell what's being set here**

![zen27](https://user-images.githubusercontent.com/33399216/178015717-c5944aca-bc78-44ae-b8a9-c927f7d46bb3.png)

![zen27-2](https://user-images.githubusercontent.com/33399216/178015737-e170c60d-3d44-4d9e-a9c8-69650712e368.png)

**Zooz Zen15**

![zen15](https://user-images.githubusercontent.com/33399216/178015758-3f2f2fd1-f734-4c35-8ab5-7c82d4a54f82.png)

**Zooz Zen21**

![zen21](https://user-images.githubusercontent.com/33399216/178015804-d81a7982-8548-40ea-b430-16f5220fb97b.png)

**Trigger names/IDs in Automation Editor UI**

![trigger text](https://user-images.githubusercontent.com/33399216/178118783-ab340094-6d29-4026-9684-01fe4038b9d9.png)

![trigger text 2](https://user-images.githubusercontent.com/33399216/178015858-483ee365-3ddf-490b-a4a4-fe7faf3ae217.png)

**Comment by HVR88** [comment]
Still an issue

**Comment by mark-lunarg** [comment]
👍, this issue still manifests.  Because of this, I am unable to configure several configuration items through the UI.  Is there a workaround for setting these values manually?

**Comment by HVR88** [comment]
There's no one assigned to this issue so it's unlikely it'll be fixed any time soon unfortunately.

**Comment by karwosts** [comment]
May be partially fixed by #14788

**Comment by karwosts** [comment]
Thsi has been much improved, though technically I guess some of the longest fields do still get cut off. 

![image](https://github.com/home-assistant/frontend/assets/32912880/b804ffc5-bf94-451e-841a-e91e18342801)

**Comment by karwosts** [comment]
Related #13070

**Comment by HVR88** [comment]
Still some truncation problems in various fields for various devices.
