### ISSUE TITLE
Can not choose all entities on history view

### ISSUE THREAD

**Issue by PetriKarjalainen** [home-assistant/frontend#13158]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The new history view with filters is excellent, but there is no way to show all entities or select a group of entities.

### Describe the behavior you expected

Can not choose all entities

### Steps to reproduce the issue

1. Choose History view
2. Try to select all entities, all areas or all devices is not possible
3.
...

### What version of Home Assistant Core has the issue?

core-2022.7.2

### What was the last working version of Home Assistant Core?

core-2022.6.x

### In which browser are you experiencing the issue with?

Version 103.0.5060.66 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

**Comment by 3ative** [comment]
**+1**
Agreed, Plus, this feature/function would allow displaying only entities that have a "history" set...
-  E.G. Listed in "Recorder:" within _(configuration.yaml)_

_Additional:
As this new History Panel is Per Browser, it would make it a lot easier to set among multiple browser devices, like Tablets / Phone Apps / Etc._

**Comment by zsarnett** [comment]
Please use the discussion: https://github.com/home-assistant/frontend/discussions/13146
