### ISSUE TITLE
Login Attempt Failed notification, but not in logs

### ISSUE THREAD

**Issue by whinis** [home-assistant/frontend#13162]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have recently been getting notification that a login attempt has failed whenever I load up home assistant in the browser or the app. The login attempt is always of the current ip and user agent that is using the dashboard (app or browser) however said attempt is not reflected in any logs that I can find. The failed attempt also does not notify other sessions.

### Describe the behavior you expected

No login failed notification should happen.

### Steps to reproduce the issue

1. Open Home Assistant
2. Get Login Failed Notification
3. Missing from Logs
...

### What version of Home Assistant Core has the issue?

2022.7.3

### In which browser are you experiencing the issue with?

Chrome, Firefox, Home Assistant App

### Which operating system are you using to run this browser?

Android, Windows 7

**Comment by gdgeist** [comment]
FWIW - these login notifications are appearing for me each time a WEBRTC element is loaded (which isnt working right now due to another bug)
