### ISSUE TITLE
Energy Dashboard handles timezone incorrectly v.a.v. data collection timezone

### ISSUE THREAD

**Issue by dolfs** [home-assistant/frontend#13164]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

My home assistant instance runs (on a Kubernetes cluster) at my home in CA, PST timezone. It collects energy data for my home and PV installation, also using sense. Everything always seemed OK in the energy dashboard until I was now looking at it from a location in MT (via a VPN into my home).
I have discovered that the energy dashboard seems to present data according to the viewer's timezone, rather than the timezone in which the data is being collected. Looking back at past days, recording reported totals, and then switching the timezone to PST (from MST) causes the graph to be shifted by one hour, and the totals are subtly different (not for PV production since all of that still falls within the same day). Shifting the timezone back and refreshing the page causes the "other" graph and numbers to be prepared.

### Describe the behavior you expected

I would argue that, generally, totals and graph should be related to the locale where the data is collected. If I happen to look at it while traveling I would still expect peak solar production to be around solar noon. With only 1 hr different time zones this shift is subtle and perhaps not noticed, but if I had been in Europe now, peak production would have been presented 8 hours or so different and totals would straddle two days in large part.
I can see that, perhaps, but a much lesser use case, the current behavior is desired, but I would argue it should not be default and should perhaps be subject to a user controllable switch.

### Steps to reproduce the issue

1. Collect data in a particular time zone and wait for a complete day's worth of data in that timezone
2. Use the energy dashboard, with computer set in same timezone, and look at that day. Note totals in each our and for day
3. Change timezone to something drastically different and refresh page4. 
4. Observe everything quite different

### What version of Home Assistant Core has the issue?

2022.3.7

### What was the last working version of Home Assistant Core?

None

### In which browser are you experiencing the issue with?

All (Safari/Chrome)

### Which operating system are you using to run this browser?

macOS Monetary 12.4

### Additional information

The solar production prediction feature does seem to be plotted in the correct time zone (meaning where the house actually is).

**Comment by rbauman70** [comment]
I noticed the same problem while travelling in Europe last week where there was a 6-hour time difference (CEST vs EDT).  This is an example screenshot of my energy production graph as seen in Europe:

![Screenshot_20220714-222234](https://user-images.githubusercontent.com/79720569/179987591-b0e4b92f-5c79-4576-bea4-3e1e4d4d3bbf.png)
This is the screenshot of the same day's production when displayed in my home:

![Screenshot_20220720-085050](https://user-images.githubusercontent.com/79720569/179987780-ebc5430f-8724-49d3-a58f-2e0345ca172d.png)

Home Assistant Core 2022.6.4
Frontend version: 20220601.0
