### ISSUE TITLE
History graphs are not aligned

### ISSUE THREAD

**Issue by sciurius** [home-assistant/frontend#13176]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When multiple entities/devices are selected in a history graph, the x-axes of the graphs are not properly aligned, making comparison difficult.

### Describe the behavior you expected

I'd expect the x-axes to be aligned so identical timestamps are right under each other.

### Steps to reproduce the issue

1. Click on an entity
2. Clik on "show more". The history tab appears.
3. Add another entity to the graph. 
4. See attachment.
![scrot20220711223615](https://user-images.githubusercontent.com/1118804/178354545-6cf5071f-cd58-441e-a81f-7b0da0dfad42.png)

...

### What version of Home Assistant Core has the issue?

2022.7.3

### In which browser are you experiencing the issue with?

Firefox 101, Chromium 103

### Which operating system are you using to run this browser?

Fedora 35

**Comment by theonteg** [comment]
+1 with this Issue / Feature Request.

Also mentioned before on discussions and community:
https://github.com/home-assistant/frontend/discussions/11265
https://github.com/home-assistant/frontend/discussions/10296

https://community.home-assistant.io/t/request-common-or-aligned-time-axis-on-all-history-graphs/246613

**Comment by ildar170975** [comment]
https://github.com/home-assistant/frontend/issues/3707
https://github.com/home-assistant/frontend/issues/11011
https://github.com/home-assistant/frontend/issues/10234
https://github.com/home-assistant/frontend/issues/10508
