### ISSUE TITLE
Make background gradient in picture entity and glance cards consistent with area-card

### ISSUE THREAD

**Issue by matthiasdebaat** [home-assistant/frontend#13180]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The picture entity and glance cards have a background bar:
![picture_entity](https://user-images.githubusercontent.com/20203284/178448167-f8918edc-557d-4aa0-a2a7-199d4ca5605a.gif)
![picture_glance](https://user-images.githubusercontent.com/20203284/178448182-20b10895-7798-495b-b91c-cf91a4da2cd9.gif)

The area-card got a newer, more seamless, background gradient:
![area-card](https://user-images.githubusercontent.com/20203284/178448279-1ef23f2c-720b-46b9-bc1f-a9b10f7943a2.png)

### Describe the behavior you expected

Use the same gradient in the picture entity and glance cards.

### Steps to reproduce the issue

1. Create new dashboard
2. Add these cards

### What version of Home Assistant Core has the issue?

core-2022.7.3

**Comment by matthiasdebaat** [comment]
Still an issue

**Comment by romanr** [comment]
The background bar serves two purposes:
- in case of selected background being bright and close to white icons and text it creates necessary separation making controls more visible.
- provides organised layout and creates more confidence in product

This ticket does not describe why gradient is better. That makes the report subjective to person who wrote it.

**Comment by matthiasdebaat** [comment]
> This ticket does not describe why gradient is better. That makes the report subjective to person who wrote it.

It does: make it consistent and more seamless.
