### ISSUE TITLE
History shows nothing initially, very tedious to add stuff

### ISSUE THREAD

**Issue by phippodoplis** [home-assistant/frontend#13181]
### The problem

Upgraded to 2022.7.3 from 2022.6.? and the new history filter starts with nothing included. I would like a button to add everything or to turn filtering off. I'm not against the new history style, but I would like to be able to add everything easily

### What version of Home Assistant Core has the issue?

2022.7.3

### What was the last working version of Home Assistant Core?

2022.6.?

### What type of installation are you running?

Home Assistant Core

### Integration causing the issue

history

**Comment by zsarnett** [comment]
Please use the already created discussion https://github.com/home-assistant/frontend/discussions/13146
