### ISSUE TITLE
Privacy settings not translated 

### ISSUE THREAD

**Issue by BrianFr88** [home-assistant/frontend#13194]
### The problem

Hi,

 Settings > System > Data analysis

This page is not translated in french :-/ 

### What version of Home Assistant Core has the issue?

2022.7.4

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

![Screenshot_20220714-131825_Home Assistant](https://user-images.githubusercontent.com/77700229/178972717-6b75c63d-12ce-46c3-a281-328280cb34c8.jpg)

**Comment by frenck** [comment]
Seem like these can not be translated at this point. Moved the issue to the frontend repository issue tracker
