### ISSUE TITLE
iOS Safe Area not considered in Dashboard 

### ISSUE THREAD

**Issue by OSonntag** [home-assistant/frontend#13203]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The safe area of the iPhone is not handled correctly. When scrolling all the way to the bottom, controls still lies inside the safe area.

![35380EAC-B741-4A9B-AAC1-1F61D3963EDB](https://user-images.githubusercontent.com/55790463/179308398-6ed8ec83-389f-4e45-9df4-0c5847935dca.jpeg)

### Describe the behavior you expected

The expected result would be an empty padding that can be scrolled to, so that the last card isn’t anymore below the safe area

### Steps to reproduce the issue

1. fill dashboard to have more content than one screen
2. Scroll all the way to the bottom

### What version of Home Assistant Core has the issue?

2022.7.5

### Additional information

![59B93E7A-6D22-4DF4-B622-08D38F6C0AA4](https://user-images.githubusercontent.com/55790463/179308564-bff67e54-68a0-4385-9618-b003aeb7b0b9.jpeg)

**Comment by KTibow** [comment]
Are you sure this isn't an issue with the companion app?

**Comment by OSonntag** [comment]
Oh yeah it's in the app did. I posted the issue on the wrong repo?

**Comment by KTibow** [comment]
I would say so. See if you could get someone from https://github.com/home-assistant/iOS to transfer the issue.
