### ISSUE TITLE
Dev tools -> Set state: selector keeps setting wrong entity

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#13211]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The "Set state" selector changes itself to an entity which was not selected by me.

Go to the "Dev tools" -> "Set state" page.
Start inputting a sensor's entity_id.
The list of entities is reduced accordingly selected mask.
Then select the entity "sensor.tracker_common_iphone_5s".

![изображение](https://user-images.githubusercontent.com/71872483/179431374-d3d6fe18-71fe-4329-bd6c-1673937667cb.png)

The page now contains data for the selected entity:

![изображение](https://user-images.githubusercontent.com/71872483/179431404-b17f30aa-1560-46b1-8cff-896909fcb5e6.png)

Then put the mouse into the "state" field (or just click on some empty area).
Now the selector suddenly changes - it selects another entity (probably with a same friendly name):

![изображение](https://user-images.githubusercontent.com/71872483/179431438-95a592a7-340a-4cde-95cc-780e0792506b.png)

I just hate this new method of selecting entities introduced a few months ago.

### Describe the behavior you expected

The selector should keep the entity which was selected by a user.

### Steps to reproduce the issue

Steps are described above.

### What version of Home Assistant Core has the issue?

2022.7.4

### In which browser are you experiencing the issue with?

Chrome 103.0.5060.114 

### Which operating system are you using to run this browser?

Win10x64

**Comment by KTibow** [comment]
Consider closing as a duplicate of #12889.

**Comment by ildar170975** [comment]
Yes, closing as duplicate of https://github.com/home-assistant/frontend/issues/12889
