### ISSUE TITLE
On mobile devices, tapping on the "cross" next to a field doesn't delete it, it just empties it

### ISSUE THREAD

**Issue by Crocmagnon** [home-assistant/frontend#13226]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In Home Assistant, there are multiple instances of UI which map to YAML lists. Usually, these lists are displayed in the UI using a text field and a gray cross (or `X`) on the right.

On iOS/iPadOS in Safari and in the companion app, tapping on the `X` only empties the field and doesn't remove the entry.
Using a trackpad/mouse works though.

### Describe the behavior you expected

When tapping on this `X`, the entry should be removed.

### Steps to reproduce the issue

1. Create a user
2. Add a device tracker to the user
3. Try to remove it using your finger to tap the `X`
    * It doesn't work
4. Connect a bluetooth or other mouse/trackpad to the device
5. Try to remove it using the pointing device to click on the `X`
    * It works

### What version of Home Assistant Core has the issue?

2022.7.5

### In which browser are you experiencing the issue with?

Safari on iPadOS/iOS 15.5 / Also happens in the companion app

### Which operating system are you using to run this browser?

iPadOS/iOS 15.5

### Additional information

I'm on iOS so I can't really try other browsers. This also affects the companion app for which we can't change the browser.

https://user-images.githubusercontent.com/3630554/179747667-ef2ad0d6-c5c2-4fce-a225-48f0ae216ffd.mp4

**Comment by klaernie** [comment]
I found the same issue under Android, both in the Companion App and Chrome.
My description and screenshots are in https://github.com/home-assistant/android/issues/2741 as I wasn't aware that it's a frontend issue.

**Comment by Crocmagnon** [comment]
I updated the title of the issue to reflect the fact that all mobile devices seem affected.

**Comment by Crocmagnon** [comment]
Seems fixed on my iPhone running Home Assistant Companion 2022.10.1 (2022.424) + iOS 16.1.2

@klaernie could you check on your side?

**Comment by Crocmagnon** [comment]
Ok thanks, I'm closing this issue then.
