### ISSUE TITLE
Map card, dark theme: icon's background doesn't follow "dark_mode" option

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#13236]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The map card has a [`dark_mode` option](https://www.home-assistant.io/dashboards/map/#dark_mode) to change a map's color in a theme's dark mode.

Compare these cards:

1. `dark_mode: false`:
```
type: map
entities:
  - entity: device_tracker.ipad_air_2_companion
dark_mode: false
```
![изображение](https://user-images.githubusercontent.com/71872483/179902258-ea297118-3845-4fcc-9c8f-a4c84c4d4381.png)

2. `dark_mode: true`:
```
type: map
entities:
  - entity: device_tracker.ipad_air_2_companion
dark_mode: true
```
![изображение](https://user-images.githubusercontent.com/71872483/179902369-760c72d3-3d6b-4738-9fd0-23abbf420082.png)

In the 1st case the entity icon's background does not follow the map's color - it is black instead of white.

### Describe the behavior you expected

The icon's background should be black if `dark_mode: true`.
The icon's background should be white if `dark_mode: false`.

### Steps to reproduce the issue

1. Select a default theme, dark mode.
2. Create a card:
```
type: map
entities:
  - entity: device_tracker.ipad_air_2_companion
dark_mode: false
```
3. Check if the icon's background is black.

### What version of Home Assistant Core has the issue?

2022.7.5

### In which browser are you experiencing the issue with?

Chrome 103.0.5060.114 

### Which operating system are you using to run this browser?

Win10x64

**Comment by Mariusthvdb** [comment]
+1, same on 2022.8 dev
