### ISSUE TITLE
No controls to restore a backup (HA in Docker)

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#13232]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I do not see any controls to restore a backup:

![изображение](https://user-images.githubusercontent.com/71872483/179835345-a85facc0-9b25-4418-8b1c-e346d06596a9.png)

Selecting a backup from the list does not help - no controls appeared.

Some details are here - https://community.home-assistant.io/t/how-to-move-or-clone-ha-installation/441742

### Describe the behavior you expected

Some controls are available to restore a backup.

### Steps to reproduce the issue

1. Goto to the System -> Backup page
2. See that no controls are available.

### What version of Home Assistant Core has the issue?

2022.7.5

### In which browser are you experiencing the issue with?

Chrome 103.0.5060.114 

### Which operating system are you using to run this browser?

Win10x64

**Comment by hellcry37** [comment]
this is very true, you have download but that's it, you will have to restore backup manually if you want to restore, fix the permissions etc.

**Comment by frenck** [comment]
It's a compressed zip file, you can just unpack it when you want to restore it.
The backup integration provides 3 things:

- Ensure all parts needed are packaged and backup up properly
- Provide services to create backups on a schedule or any event wished for
- Allow restoring them on a Home Assistant Operating System (in case of a migration to such a setup)
