### ISSUE TITLE
Entities Card Button Row Alignment on Mobile Devices

### ISSUE THREAD

**Issue by coolhand72** [home-assistant/frontend#13234]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

https://community.home-assistant.io/t/entities-card-button-row-alignment-on-mobile-devices/441885

When a button row is displayed via the Entities Card on a web browser, the entire row is displayed over multiple lines if necessary.  However, when the row is displayed on a mobile device, the row is displayed in a single row. The user is required to scroll to find the remaining buttons. Sometimes, the buttons aren’t even visible unless the user goes looking.

Browser:
![browser](https://user-images.githubusercontent.com/15070005/179997961-ca41112d-5e3b-4680-bce3-02ad6475c3e2.PNG)

iPhone:
![IMG_20220719_210011](https://user-images.githubusercontent.com/15070005/179998112-9a4a837b-837b-4d0a-9426-393d31dd6810.JPEG)

Testing Companion App:
iPad - chips button are wrapped to the next row (like in web browser).
iPhone - chips buttons are NOT wrapped.

### Describe the behavior you expected

Entities Card chips buttons should be wrapped on mobile device.

### Steps to reproduce the issue

1. Create an entities row card button row
2. Add numerous entities
3. Look how the row is displayed via iPhone mobile app.
...

### What version of Home Assistant Core has the issue?

2022.7.5

### What was the last working version of Home Assistant Core?

unkown

### In which browser are you experiencing the issue with?

Apple iPhone

**Comment by Quentame** [comment]
I like this behavior: with an iPad I am expecting a desktop class website, not a phone style one.

As there is more space on the iPad screen, it's normal to get all information. The space is limited on smartphone screens, and the finger more accessible and willing to scroll.

**Comment by coolhand72** [comment]
You make a good point @Quentame .  Perhaps it could be an option, wrap = true ?
