### ISSUE TITLE
Wrong units on thermostat temperature

### ISSUE THREAD

**Issue by Holonium** [home-assistant/frontend#13248]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

While attempting to set up a Trane XR524 thermostat, the card displays everything but the current temperature in Fahrenheit, ignoring unit settings.
![image](https://user-images.githubusercontent.com/18223315/180046714-ac492418-f736-4fa9-9393-448237dd0419.png)
As shown, the current temperature is labeled as Fahrenheit, but displays in Celsius.

### Describe the behavior you expected

I would have expected that the temperature is displayed according to the unit settings.

### Steps to reproduce the issue

1. Install and configure Z-Wave JS.
2. Integrate a Trane XR524 thermostat.
3. Add a thermostat card pointed at it.

### What version of Home Assistant Core has the issue?

core-2022.7.5

### In which browser are you experiencing the issue with?

Mozilla Firefox 102.0

### Which operating system are you using to run this browser?

Arch Linux 5.18.8

### State of relevant entities

```txt
State: 21.0
Attributes:

state_class: measurement
unit_of_measurement: °C
device_class: temperature
friendly_name: Thermostat: Air temperature
```
```


### Problem-relevant frontend configuration

```yaml
type: thermostat
entity: climate.touchscreen_comfort_control_thermostat
```

### Additional information

After a call with Trane support, it was determined that the receiving device should perform the conversion between Celsius and Fahrenheit.

**Comment by KTibow** [comment]
Could you send the state and attributes of the climate entity, not the sensor entity?

**Comment by Holonium** [comment]
Here are the states and attributes.
```
cool
```
```
hvac_modes: off, heat, cool, heat_cool
min_temp: 44.6
max_temp: 95
fan_modes: Auto low, Low, Circulation
preset_modes: none, Auxiliary
current_temperature: 21
temperature: 74
target_temp_high: null
target_temp_low: null
fan_mode: Auto low
hvac_action: cooling
preset_mode: none
fan_state: Running / running low
friendly_name: Thermostat
supported_features: 27
```

**Comment by KTibow** [comment]
That's the fault of the integration for being inconsistent, not the frontend.

**Comment by Holonium** [comment]
@KTibow I really appreciate your help.
To be sure based on the information, I should be submitting this issue to the Z-Wave JS team instead, or is that still the wrong one?

**Comment by KTibow** [comment]
That sounds correct.

**Comment by Holonium** [comment]
Issue submitted to the wrong team.
