### ISSUE TITLE
Duplicate Trigger Ids in Trigger Condition

### ISSUE THREAD

**Issue by EnochPrime** [home-assistant/frontend#13260]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Experiencing the same issue as described in #10793. If multiple triggers define the same value the value is repeated in the trigger condition drop down menu.

### Describe the behavior you expected

I expected the list to be consolidated to unique values only.

### Steps to reproduce the issue

1. Create automation with multiple triggers with the same trigger id
2. Add a 'Triggered by' condition
3. Open drop down menu

### What version of Home Assistant Core has the issue?

2022.7.6

### In which browser are you experiencing the issue with?

Brave Version 1.41.96 Chromium: 103.0.5060.114 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Linux Mint 20.3 Cinnamon

**Comment by EnochPrime** [comment]
This is still valid for 2022.10.4

**Comment by bdr99** [comment]
This is fixed in https://github.com/home-assistant/frontend/pull/14122.
