### ISSUE TITLE
Create Helper dialog shows incorrect form

### ISSUE THREAD

**Issue by thedanbob** [home-assistant/frontend#13274]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Under certain conditions, the Create Helper dialog opens a different helper's form than the one selected.

### Describe the behavior you expected

Create Helper should always open the form for the helper type selected by the user.

### Steps to reproduce the issue

1. Settings > Automations & Scenes > Helpers > click Create Helper
2. Select a helper type that opens a new dialog box for its form (e.g. "Change device type of a switch", "Derivative sensor", etc). This will throw an error in the console, pasted below.
3. Close the dialog box and click Create Helper again.
4. Select a helper type that reuses the Create Helper dialog box for its form (e.g. "Button", "Counter", etc). A new dialog box for the first helper type will open instead.
5. Repeating steps 3 & 4 a second time will correctly show the form for the second helper type.

### What version of Home Assistant Core has the issue?

2022.7.6

### In which browser are you experiencing the issue with?

Multiple

### Which operating system are you using to run this browser?

Multiple

### Javascript errors shown in your browser console/inspector

```txt
Uncaught TypeError: Cannot read properties of undefined (reading 'dialogClosedCallback')
    at F.value (dialog-helper-detail.ts:48:1)
    at F.handleEvent (styles.ts:369:1)
    at a.fireRequestSelected (mwc-list-item-base.ts:224:1)
    at a.<anonymous> (mwc-list-item-base.ts:224:1)
    at d79e126a.js:2:2776
    at Map.forEach (<anonymous>)
    at e.updated (d79e126a.js:2:2702)
    at a._$AE (styles.ts:369:1)
    at a.performUpdate (styles.ts:369:1)
    at a.scheduleUpdate (styles.ts:369:1)
```

### Additional information

I believe this was introduced in a recent version of the frontend, though I don't know exactly which. I first saw the issue in the iOS app and attempted to reproduce it in a desktop browser. I was unable to at first, however the "new version of the frontend is available" popup appeared and after loading that I was able to reproduce it.

**Comment by inytar** [comment]
I can reproduce this with core version `2022.8.0b3` & front-end version:  `20220728.0`. Both in my browser (Firefox 102) and in the Android companion app.
