### ISSUE TITLE
Threshold limits must be filled in and deleted to allow saved empty field

### ISSUE THREAD

**Issue by AndersWestman** [home-assistant/frontend#13277]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

To be able to edit and save a Threshold Sensor Helper in UI with one of the upper or lower limits emtey, the field must be filled with something and then deleted to be allowed to save the settings with a empty field.

If the field was already empty, the error "User input malformed: expected float for dictionary value @ data['upper']" 
is showed when tried to save.

### Describe the behavior you expected

Saving the settings for a Threshold Sensor Helper with upper or lower limit empty should be possible without edit and delete the value.

### Steps to reproduce the issue

1. Create a Threshold Sensor Helper with upper or lower limit empty
2. Edit the sensor and save without touching the empty field
3.
...

### What version of Home Assistant Core has the issue?

2022.7.6

### In which browser are you experiencing the issue with?

Chrome 103.0.5060.114 and HA-app on Android

### Which operating system are you using to run this browser?

Windows 10 / Android HA-app

**Comment by straybiker** [comment]
I confirm the issue
