### ISSUE TITLE
Bluetooth discoveries can't be ignored

### ISSUE THREAD

**Issue by pascalwinters** [home-assistant/frontend#13288]
### The problem

With the new bluetooth integration my Switchbot curtains are detected. But because I have 2 groups, in total 4 devices not all devices are necessary to add in HA. So I will ignore 2 devices but I can't.

### What version of Home Assistant Core has the issue?

core-2022.8.0b0

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

bluetooth

### Link to integration documentation on our website

https://rc.home-assistant.io/integrations/bluetooth

### Additional information

![image](https://user-images.githubusercontent.com/69316923/181280432-248698fd-952f-449f-9d22-b898bc943ac5.png)

**Comment by bdraco** [comment]
Just forgot the list of ones that can be ignored is hard coded in the frontend.  We don’t add new discovery types frequently so it’s easy to forget it needs to be added there as well
