### ISSUE TITLE
Uncaught (in promise) {code: 'not_found', message: 'Subscription not found.'}

### ISSUE THREAD

**Issue by hmmbob** [home-assistant/frontend#13304]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![image](https://user-images.githubusercontent.com/33529490/181766372-2194e41d-32e0-40b0-aa6b-fe5a29591888.png)

2022.8.0b2 (was there since b0), see https://discord.com/channels/330944238910963714/427516175237382144/1002164966700367922

### Describe the behavior you expected

No console errors

### Steps to reproduce the issue

1. open repairs section in settings, 
2. click the three dots -> system information, 
3. close this popup: error appears upon closure

### What version of Home Assistant Core has the issue?

core-2022.8.0b2

**Comment by ildar170975** [comment]
Seeing this error in browser's console in Lovelace dashboard.
2022.9.4, Chrome, Win10x64

**Comment by jimmyeao** [comment]
Seeing this also, seems related to mushroom cards?
![image](https://user-images.githubusercontent.com/5197831/194762660-15773e78-36b0-4bdd-859e-867738dc818e.png)

**Comment by hmmbob** [comment]
![image](https://user-images.githubusercontent.com/33529490/211259820-71a81f9c-cbe8-45db-adce-45d8ce1c4cfb.png)

Still happening on 2023.1.1

**Comment by ildar170975** [comment]
Same in 2023.2.2

**Comment by leonelsr** [comment]
...And guess what? Still the same bug on `2023.3.1`. It happens both on Chrome and Microsoft Edge (Chromium).

I'll be testing it on Firefox soon...

But please, pay some attention here!!!

**Comment by james-1987** [comment]
Same here. Edge, 2023.5.2, W11.
