### ISSUE TITLE
"regeneratorRuntime is not defined" error on Chromium webview 61

### ISSUE THREAD

**Issue by dictcp** [home-assistant/frontend#13312]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Home assistent WebUI is not load on my android-based ebook reader browser (Blank screen is shown instead)
After attaching developer tools, there are error like "regeneratorRuntime is not defined" in the error console.

### Describe the behavior you expected

The UI loaded properly, instead of a blank screen.

### Steps to reproduce the issue

1. Pick a device with Chromium Webview 61 
2. Go to the home assistant UI (eg. http://xxxxx:8123)
3. Blank screen is shown
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.7.6 Frontend 20220707.1 - latest

### In which browser are you experiencing the issue with?

Chromium Webview 61

### Which operating system are you using to run this browser?

Android 8.1

### Javascript errors shown in your browser console/inspector

```txt
regeneratorRuntime is not defined
```

**Comment by dshokouhi** [comment]
Webview 61 is very very old isn't it? You should try to update Webview on that device to fix this issue. They are at version 104 now I believe.

**Comment by dictcp** [comment]
https://www.home-assistant.io/docs/frontend/browsers/
I saw the doc saying it work on Android Chrome 50.0.2661.89.
