### ISSUE TITLE
Uncaught (in promise) when loading page

### ISSUE THREAD

**Issue by TheAceMan** [home-assistant/frontend#13323]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Firefox will occasionally hang on loading https://homeassistant.xxxx.duckdns.org/lovelace 

In the debug output of firefox it reports Uncaught (in promise) 1.
![Untitled](https://user-images.githubusercontent.com/5782712/182275243-db573fb1-e6bf-4f05-9777-e262cc48f26b.png)

The page may load a few hours later when I try the site again. Seems to happen randomly. Appears to be occurring after a recent upgrade.

### Describe the behavior you expected

Page should load.

### Steps to reproduce the issue

1. Login to homeassistant with firefox.
2. Later lovelace will hang when refreshing page.

### What version of Home Assistant Core has the issue?

Frontend 20220707.1 - latest

### What was the last working version of Home Assistant Core?

Don't recall but worked a week ago

### In which browser are you experiencing the issue with?

Firefox 102.0.1

### Which operating system are you using to run this browser?

Windows

### Additional information

Running HomeAssistant as a docker.

**Comment by powerpaul17** [comment]
I have the same problem, seems to be related with the service worker not finding some chunks.

**Comment by Elinvention** [comment]
Same issue here. Any clues? This is really annoying.

**Comment by m1n3nfux** [comment]
I have the same issue. Only with firefox, other browsers work fine. 

Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.2
Frontend 20230608.0 - latest

I am using Firefox 114.0.2, though this issue has persisted for quite some time for me.

**Comment by Elinvention** [comment]
The issue still persists in Frontend 20230503.3 - latest.

**Comment by Ulrar** [comment]
Just randomly started getting this now

**Comment by hackersoft13** [comment]
Hi there,
Getting this issue aswell on direct hardware and only with firefox.
 Core 2023.11.3
Supervisor 2023.11.6
Operating System 11.1
Frontend 20231030.2

**Comment by Elinvention** [comment]
In my case the issue seems to have disappeared after I had to delete my local storage from my Firefox profile because of corruption. If I remember correctly, to do that you have to move/delete `.mozilla/firefox/profiles/<something>/storage{,.sqlite}`. Note: you may loose some data from some websites or extensions.
