### ISSUE TITLE
Shopping list add-on 

### ISSUE THREAD

**Issue by dari0** [home-assistant/frontend#13337]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I try to add second *shopping list* card to the dashboard then the contents of the first shopping list is duplicated to newly created one. I wanted to have two different shopping list but I can't and I don't know if that behavior is made by design or not.

### Describe the behavior you expected

Having multiple shopping list with different contents.

### Steps to reproduce the issue

1.Add new shopping list to the dashboard and add some list elements.
2. Add second shopping list.
3. New elements from the second shopping list will be added to the first one and both shopping list will have the same content list.

### What version of Home Assistant Core has the issue?

2022.8.0

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

Windows 21H2

**Comment by frenck** [comment]
This is not a bug, but the current feature set. It is a single list.

<https://www.home-assistant.io/integrations/shopping_list/>
