### ISSUE TITLE
Street has wrong name on map

### ISSUE THREAD

**Issue by raf10gh** [home-assistant/frontend#13338]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

A street on the map has the wrong name. The town is Tiverton RI in the US. In the attached picture the street partially cover in orange named Adams Street is really Lee Way.
![Map](https://user-images.githubusercontent.com/73025561/182939477-358caf50-a52d-43f8-8697-df964cd8eebb.png)
 

### Describe the behavior you expected

Name of street needs to be changed.

### Steps to reproduce the issue

1.Go here 41.66186445199486, -71.14508878465836 and see the name of the street should be Lee Way not Adams Street. Adams street is one street over.
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.8.0

### In which browser are you experiencing the issue with?

All browsers

### Which operating system are you using to run this browser?

Windows 11

**Comment by zsarnett** [comment]
Not something we can fix. This is based on a map library
