### ISSUE TITLE
Maps are not showing 'houses' and 'buildings'

### ISSUE THREAD

**Issue by bearhntr** [home-assistant/frontend#13334]
### The problem

I have just installed the 2022.8.0 install and went to look at the MAP - as this was mentioned it was improved.  Not sure what I am seeing now is an "improvement" -- there are no buildings showing.  

I am running a nearly brand new install of HASS OS 8.4 (formerly on 2022.7.6).  This is what I am seeing now - using CHROME on Windows 10 computer:  

In LIGHT mode:  
![image](https://user-images.githubusercontent.com/100164602/182704654-64ba9042-65f0-4e4b-b8e1-1b7c37b2d31a.png)

In DARK mode:
![image](https://user-images.githubusercontent.com/100164602/182704919-5d16e944-212c-41f0-96d4-2c75010c37cf.png)

There are approximately 54 homes in my subdivision - and they all used to be visible in nearly ALL zooming levels.  

### What version of Home Assistant Core has the issue?

2022.8.0

### What was the last working version of Home Assistant Core?

2022.7.6

### What type of installation are you running?

Home Assistant OS

**Comment by ildar170975** [comment]
I can see buildings:
![image](https://user-images.githubusercontent.com/71872483/182720303-7c4d3854-9d29-46cb-8626-24dfba050a50.png)

HA 2022.8, HA Container
Chrome, Win10x64

**Comment by bearhntr** [comment]
Very Odd here --  I cleared the Browser Cache and even rebooted --  If I ZOOM OUT - there are houses and buildings (in other areas) in the area where my home is - there are about 1000 homes and buildings not showing.

![image](https://user-images.githubusercontent.com/100164602/182846566-cfd805de-cda0-4ed7-b2f3-7d4d222a1721.png)

**Comment by bearhntr** [comment]
This truly weird.  I shut downt the HA Computer - and the MODEM and ROUTER - then booted all back up.  Now it looks like it has moved me to a completely different 'map' - and zooming in...I find my house.  

![image](https://user-images.githubusercontent.com/100164602/182847716-a7dc32d7-8f86-4b49-952c-c347d4f31f3a.png)

**Comment by bearhntr** [comment]
Someone please notify Rod Serling 🤣
