### ISSUE TITLE
Selecting target entity missing in GUI mode, forces to use yaml mode

### ISSUE THREAD

**Issue by Anto79-ops** [home-assistant/frontend#13332]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi,

When i try to use the service template to send ADB commands to my AndroidTV (integration), it does not give me the option to pick a target entity when in GUI mode. Switching to yaml mode, allows me to type and use the entity, and it works properly.

![image](https://user-images.githubusercontent.com/79593761/182641508-ecf02fb1-bbfa-4943-bdd7-d1e59649b0c3.png)

### Describe the behavior you expected

to see a list of entities as my target

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.8

### In which browser are you experiencing the issue with?

Google Chrome

**Comment by chertvl** [comment]
Same
![image](https://user-images.githubusercontent.com/38353584/183123339-f8d0acab-26ba-4d49-aefb-7b4d2e524033.png)
![image](https://user-images.githubusercontent.com/38353584/183123345-8822dfd8-8056-4cf8-aaa9-0feb7dfc0c21.png)

**Comment by Lvecsei** [comment]
Same behavior using Hue integration.

**Comment by RogerSelwyn** [comment]
Same using my custom integration. The use of `integration` parameter in services.yaml for entity targeting doesn't seem to work anymore.

**Comment by Lvecsei** [comment]
Tried reverting to 2022.7.7 and updating to 2022.8.1 and got the same problem. 2022.7.7 works fine.

**Comment by Lvecsei** [comment]
Persists on 2022.8.2.

**Comment by chertvl** [comment]
I can confirm about 2022.8.2
![image](https://user-images.githubusercontent.com/38353584/183476998-33e8dde1-1dd8-41b8-9ec3-8979eabaa8e0.png)

**Comment by Asom-Velz** [comment]
The problem still exist. 
The latest working OK version is 2022.7.7
Latest version 2022.8.1 | Problem with HUE Targets Selection - Removed
Latest version 2022.8.2 | Problem with HUE Targets Selection - Removed
Latest version 2022.8.3 | Problem with HUE Targets Selection - Removed
Latest version 2022.8.4 | Problem with HUE Targets Selection - Removed
[https://github.com/home-assistant/core/issues/76508](url)

**Comment by marcelveldt** [comment]
Confirmed that this is a frontend specific issue. The "target selector" is no longer accepting the "integration" filter.
It breaks on both service calls (target specified in services.yaml description file) and blueprints.

**Comment by marcelveldt** [comment]
fixed in https://github.com/home-assistant/frontend/pull/13380 which should be available in one of the next (path) releases which includes a new build of the frontend.

**Comment by dtspinella** [comment]
Is there an estimate of when a new build that would include this update might be scheduled?

**Comment by Lvecsei** [comment]
The current 2022.9 beta has the fix. Should be out soon.

**Comment by Asom-Velz** [comment]
Thank you

**Comment by chertvl** [comment]
I just paste it here...

@marcelveldt @zsarnett 

![image](https://user-images.githubusercontent.com/38353584/189061778-925d995c-7030-4636-a8fa-42f49dec7270.png)

![image](https://user-images.githubusercontent.com/38353584/189061815-f552bf54-1ae6-4970-a6d3-e212a8050461.png)

![image](https://user-images.githubusercontent.com/38353584/189061835-4edd27d6-6d1a-4b3f-80e5-c23d5f039260.png)

**Comment by nickrout** [comment]
Can you translate please? Particularly pic 2

**Comment by chertvl** [comment]
Issue still persist in 2022.10.0.
