### ISSUE TITLE
configuration validation stays hanging

### ISSUE THREAD

**Issue by aramanrique** [home-assistant/frontend#13340]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![Screenshot 2022-08-05 134955](https://user-images.githubusercontent.com/33544935/183071666-c2d2a852-da72-4e79-8337-c9ed5f11ec67.jpg)
The configuration validation doesn't execute and stays turning without result.

### Describe the behavior you expected

I expected that the configuration valid gives a result: valid or invalid

### Steps to reproduce the issue

1. Go to Developer tools, YAML configuration
2.  Click on Check Configuration
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.8.1

### Which operating system are you using to run this browser?

Windows 10

**Comment by spacegaier** [comment]
Are there any errors/exceptions in the browser console or in the HA logs?
