### ISSUE TITLE
Entity selector selects wrong entity

### ISSUE THREAD

**Issue by thomascandrian** [home-assistant/frontend#13346]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have multiple entities with the same name, e.g. named "Alea".

![grafik](https://user-images.githubusercontent.com/35242940/183246451-4f87e700-4db8-4135-aded-adb97ae335d0.png)

If I select in conditions dropdown any "Alea" entry, it always chooses the first entity. You cannot see it, because the dropdown shows only the friendly name, but if you click on it you see that still the wrong entity is selected.

I found no workaround for that, except using YAML editor.

I noticed that earlier, it seems since 2022.08 it is not possibvle to choose the right entity on the GUI.

### Describe the behavior you expected

The dropdown selects the entity you click on.

### Steps to reproduce the issue

1. Create multiple eintities named the same (i.e. temperature and humidity sensor)
2. Create an Action/Script with a condition
3. select in entity dropdown the second entity. The first one is chosen.
...

### What version of Home Assistant Core has the issue?

2022.08.01 on HAOS 8.4

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

both Chrome/Firefox

### Which operating system are you using to run this browser?

WIn10

**Comment by ildar170975** [comment]
https://github.com/home-assistant/frontend/issues/12889
https://github.com/home-assistant/frontend/issues/13211

**Comment by thomascandrian** [comment]
Sorry, duplicate - did not find them :-(
