### ISSUE TITLE
Shopping List doesn’t update when adding items using a service call

### ISSUE THREAD

**Issue by laszlojakab** [home-assistant/frontend#13345]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I add an item to shopping list by a service call the shopping list hasn't been updated.

### Describe the behavior you expected

When I add an item to shopping list by a service call I would expect that the shopping list updated without refreshing the page.

### Steps to reproduce the issue

1. Open a page with the shopping list card
2. Open an other page with developer tools/services
3. Call shopping_list.add_item:

```yaml
service: shopping_list.add_item
data:
  name: bread
```
4. Check the shopping list card, it is not updated

### What version of Home Assistant Core has the issue?

Home Assistant 2022.8.0

### In which browser are you experiencing the issue with?

Google Chrome 103.0.5060.134

### Which operating system are you using to run this browser?

Windows 10 20H2 build: 19042.1165

### Additional information

Issue already reported in core (https://github.com/home-assistant/core/issues/72123) but I think it is a UI related problem. The service call event received on client side so the shopping list card probably not listens to it.

It would be nice to fix the error to be able to build a dashboard where you can see the shopping list and add items to shopping list only by tapping on icons.

**Comment by laszlojakab** [comment]
Problem solved in 2022.10.5 (or previously, I haven't checked before).

**Comment by pedromirallesmorey** [comment]
Sorry. how did you solve it?
