### ISSUE TITLE
Entity selector changes on its own

### ISSUE THREAD

**Issue by renaiku** [home-assistant/frontend#13350]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

All these screenshot are taken in the devtools / states but are reproduced on the entity dropdown selector while adding / editing a card.
It may not be a frontend issue because two entities have the same friendly name.

### Describe the behavior you expected

Two entities with the same friendly name from a same device should not swap after selecting one of them in a dropdown list, or should be merged as one entity.

### Steps to reproduce the issue

1. Search an entity:
![image](https://user-images.githubusercontent.com/17033907/183283335-efe90fca-c05c-4a00-bbeb-2b8206cf4431.png)

2. As you can see, 2 entities have the same friendly name because it's the same device. The first is the routeur integration that is created with the mac adress of the device. The second one is the Xiaomi Miio integration of the vacuum. The device page shows indeed two integrations like it would normally do for device with many integrations: 
![image](https://user-images.githubusercontent.com/17033907/183283610-c1c82483-bbc3-4a0c-a5a0-bf1403225251.png)

3. Select the second entity: **(note here that the focus is still on the text field)**
![image](https://user-images.githubusercontent.com/17033907/183283647-fb979bb5-fe4b-4aaa-8d6e-3c252612bd5d.png)

4. Clicking outside the text field choose the first entity of the dropdown with the same friendly name 
![image](https://user-images.githubusercontent.com/17033907/183283700-90eac495-24db-4270-87ba-0bc7cd2f2098.png)

### What version of Home Assistant Core has the issue?

2022.8.1

### In which browser are you experiencing the issue with?

Firefox 103.0.1

### Which operating system are you using to run this browser?

Windows 10

**Comment by ildar170975** [comment]
https://github.com/home-assistant/frontend/issues/13346
https://github.com/home-assistant/frontend/issues/12889
https://github.com/home-assistant/frontend/issues/13211

**Comment by renaiku** [comment]
Duplicate of https://github.com/home-assistant/frontend/issues/12889
