### ISSUE TITLE
Trigger ID's with the same ID popups als multiply choices 

### ISSUE THREAD

**Issue by evanlaar01** [home-assistant/frontend#13359]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When you have multiply trigger id's with the ID "on", you see al those "on" choices in the conditions.
![triggerid](https://user-images.githubusercontent.com/70329556/183438156-b38d5a3e-cf5e-4301-b9e3-204eb840a61f.png)

### Describe the behavior you expected

When multipy id's, one "triggered by" choice.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.8.2

### What was the last working version of Home Assistant Core?

2022.7.x

### In which browser are you experiencing the issue with?

Chrome, Firefox, etc

### Which operating system are you using to run this browser?

Windows 11

**Comment by EnochPrime** [comment]
Duplicate of #13260

**Comment by EnochPrime** [comment]
Fixed in #14122
