### ISSUE TITLE
Code Based Emojis doesnt work anymore since 2022.7.5

### ISSUE THREAD

**Issue by pimp1310** [home-assistant/frontend#13361]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Emoji Code doesnt work anymore  `{{'\uD83D\uDDD1'}}` .

in the configuration.yaml and in the automations.

### Describe the behavior you expected

i had templates and automations with the emoji code, but this is broken.

Notifys doesnt work anymore too with emojis.

### Steps to reproduce the issue

create a automation with this code

`message: |
    {{'\uD83D\uDDD1'}} Die Bio Tonne muss heute raus.`

or test it in the developer console.

### What version of Home Assistant Core has the issue?

2022.8.0

### What was the last working version of Home Assistant Core?

2022.7.5

### In which browser are you experiencing the issue with?

not relevant

### Which operating system are you using to run this browser?

not relevant

### Additional information

https://community.home-assistant.io/t/emoji-hack-for-lovelace/85964/7

here you see the confirmed bug from [Ildar_Gabdullin](https://community.home-assistant.io/u/Ildar_Gabdullin)

**Comment by ildar170975** [comment]
> here you see the confirmed bug from [Ildar_Gabdullin](https://community.home-assistant.io/u/Ildar_Gabdullin)

Technically, I just confirmed that using "\uXXXXX" in a code like this does not work:
![изображение](https://user-images.githubusercontent.com/71872483/183487740-5742954f-6c8d-4ba8-b011-d3f39177983e.png)
Cannot say whether it is a bug or not, never used emoji before.

A "dog" emoji was added from [here](https://emojipedia.org/dog-face/) by "copy/paste".
