### ISSUE TITLE
Unable to view disabled helpers

### ISSUE THREAD

**Issue by TwoWheelDev** [home-assistant/frontend#13379]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Disabling a helper from the frontend, removes it from the helpers list and leaves no way to view it.

The same issue was also reported on the forum in 2020: https://community.home-assistant.io/t/helper-for-input-entities-disappear-when-disableling/201576

### Describe the behavior you expected

Fro disbaled helpers to be visible in the helpers list (maybe filtered in the same way integrations are)

### Steps to reproduce the issue

1. Disable a helper from the frontend
2. You are now unable to see/get back this helper
...

### What version of Home Assistant Core has the issue?

core-2022.8.4

### In which browser are you experiencing the issue with?

Google Chrome + others

### Which operating system are you using to run this browser?

Windows 10

**Comment by pedolsky** [comment]
You can reactivate it in the „Entities“ section (check the box „Display disabled entities“).
