### ISSUE TITLE
Non existent entities shown at the energy dashboard

### ISSUE THREAD

**Issue by danysahne96** [home-assistant/frontend#13371]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I refer to Bug #10933.  I got exactly the same issue:

Entities that have been added to to the energy dashboard and don't exist any more, are continue shown in the energy dashboard.

### Describe the behavior you expected

Deleted entities should not bei listed here anymore.

### Steps to reproduce the issue

1. add a sensor to the energy dashboard (e.g. a HomeMatic, Shelly or virtual sensor named sensor.my_energy_kwh)
2. remove the sensor from the integration or deleted the whole integration

3. You will still see sensor.my_energy_kwh in the energy settings and are able to add it. After adding it will marked as non existing anymore on the energy dashboard. 

### What version of Home Assistant Core has the issue?

2022.8.3

### In which browser are you experiencing the issue with?

Google Chrome 104.0.5112.81

### Which operating system are you using to run this browser?

Windows 11 and/or HomeAssistant App on Android 12

**Comment by danyshane96** [comment]
So, since there is nobody responde to that. Here is the way i could fix that for me:

1. Stop HA by running "HomeAssistant Stop" from Developer Tab 
2. Run SQLite Explorer on your Linux, OSX or Windows and open up the database file
3. Delete all records from the tables called "statistics_*". 
4. Boot HA again, my Sensors are working fine now and all old not existing entities are gone.

This seems to be a HA issue and needs to be resolved.

**Comment by Santanachia** [comment]
I think it is very good that this is happening.
I had the meter replaced with a new one. The integration started to show the new entity. I don't want to lose the data collected so far (it will be useful, for example, to compare years).

in the solution you propose, you write about deleting everything from `statistics_*`, that is, wanting to improve the display of current consumption you will delete the record of production from PV panels, gas consumed and many other collected data.
It would be worth adding a step `0.`, and in it: 'create backup'
