### ISSUE TITLE
Statistic Chart stays empty

### ISSUE THREAD

**Issue by bjoern79de** [home-assistant/frontend#13387]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I'm trying to add a statistical chart to depict the max output per day of my solar plant.
The raw sensor data looks like this:
<img width="1420" alt="Bildschirmfoto 2022-08-15 um 21 11 54" src="https://user-images.githubusercontent.com/7832694/184865574-f8bf7d90-59df-41c2-a05f-a09850b43a44.png">

The chart stays empty for `min, max, mean` but shows bars for `sum`.

### Describe the behavior you expected

I expect to see bars for each day which represents the peak power of that day.

### Steps to reproduce the issue

My yaml looks like this:
`chart_type: line
period: month
days_to_show: 30
type: statistics-graph
entities:
  - sensor.default_yieldday
stat_types:
  - max`
 
### What version of Home Assistant Core has the issue?

2022.8.5

**Comment by Xitee1** [comment]
If you add the sensor to your Energy dashboard it should work in there, that's how I do it.
