### ISSUE TITLE
Xiaomi BLE LYWSD03MMC / bindkey not accepted

### ISSUE THREAD

**Issue by anico64** [home-assistant/frontend#13391]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The bindkey is never accepted. I always have the answer that it is wrong.

### Describe the behavior you expected

The bindkey should be accepted

### Steps to reproduce the issue

1. Power on the Xiaomi sensor (not reflashed)
2. Wait time until HA recognize the sensor
3. Wait time until HA show a warning with the request of the bindkey
4. Run Telink flasher. Do the connection. Do the activation to have the bindkey
5. Copy the bindkey created in Telink to HA
6. HA report that the bindkey is wrong

![Screenshot_20220816-190717](https://user-images.githubusercontent.com/111300797/184988161-4d3e3caf-2aa5-4c5d-a06a-6e00319b63ce.png)

### What version of Home Assistant Core has the issue?

2022.8.(0,1,2,3,4)

### Additional information

The same hardware was working perfectly with ble_monitor

**Comment by zsarnett** [comment]
This is a core issue.
