### ISSUE TITLE
Entities with same Friendly Name cause problems

### ISSUE THREAD

**Issue by sevorl** [home-assistant/frontend#13412]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

when multiple entities have the same friendly name, UI dropdowns may change to a different entity with the same friendly name

### Describe the behavior you expected

Once I selected an entity from a drop down list, this entity should be kept selected. The dropdown list should not switch to a different entity with the same friendly name. 

### Steps to reproduce the issue

1. Create an entity person.johndoe, friendly name = "john"
2. Create an entity media_player.johndoe, friendly name = "john" (same as above)
3. Go to developer-tools/state. 
4. In the "set state" area, in the drop down list, type "john" and select the entity media_player.john
5. -> Observe that the status attributes of the media player are displayed
6. Click somewhere on the page, so that the drop down list is no longer in focus
7. The attributes will change to the attributes of person.john.
8. Expected: The dropdown list should remember the selected entity, it should not select the first entity with the friendly name "John"

Same can be observed in other areas of the system, e.g. when selecting an entity in an automation

### What version of Home Assistant Core has the issue?

2022.8.6

### In which browser are you experiencing the issue with?

Google Chrome 103.0.5060.114

### Which operating system are you using to run this browser?

Windows 10

**Comment by ildar170975** [comment]
https://github.com/home-assistant/frontend/issues/12889

**Comment by danielbrunt57** [comment]
> Seems that people are "happy" about using friendly names instead of entity_ids.

I'm not!  The friendly names are now not so friendly!

**Comment by ildar170975** [comment]
> If the only way to fix this is to rename the friendly name to be unique then HA needs to enforce unique friendly names, or allow disabling the whole feature...

About "happy" that was a sarcasm.
I absolutely agree with you.
Friendly names should not be used as a default "select an entity" method since they are not unique.

I guess this issue should be closed as a duplicate.
Please continue this discussion in the open issue.

**Comment by sevorl** [comment]
I agree this is a duplicate of [#12889 ] and will close this case.
