### ISSUE TITLE
calendar does not populate 

### ISSUE THREAD

**Issue by stovedoctor** [home-assistant/frontend#13414]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Calendar will not show events until you un check and then check the Calendars in the left side bar..
Also my automations that use calendar events take up to 24 hours to run  

### Describe the behavior you expected

calendar events to show

### Steps to reproduce the issue

1. open calendar in side bar
2. see nothing in events
3. un check then re check the calendar
4. then events populate. 
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.8.5 Supervisor 2022.08.3 Operating System 8.4 Frontend 20220802.0 - latest

### In which browser are you experiencing the issue with?

chrome Version 104.0.5112.81 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

windows home 11 21H2

**Comment by giejay** [comment]
I have the same issue. Only when deselecting the calendar and selecting it again

**Comment by stovedoctor** [comment]
As if this week this still has same effect.
I need to un check and re check each calendar for them to show up
