### ISSUE TITLE
Button automation dashboard incorrect toggle

### ISSUE THREAD

**Issue by szyper-sakrona** [home-assistant/frontend#13439]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have 3 automation (buttons) on my dashboard.
Just my two gateway doors (1 horizontal, 1 vertical and combined 1+1 open/close).
Single automations is triggered normally, but the third automation instead of toggle (run) just enable/disable automation.
When I choose "more information" and click run it is ok, but when I choose "toggle" it wrongly enable/disable that instead of running.
Thx

### Describe the behavior you expected

Correctly run toggle automation (run).

### Steps to reproduce the issue

Just maybe it depends on combined automation, not single one?

### What version of Home Assistant Core has the issue?

Home Assistant 2022.8.6 Supervisor 2022.08.3 Operating System 8.4  UI 20220802.0 - latest

### What was the last working version of Home Assistant Core?

month ago?

**Comment by spacegaier** [comment]
We need more info to try to reproduce. Please post your relevant dashboard YAML and the problematic automation.

**Comment by szyper-sakrona** [comment]
Ok, but just to get deeper - what is different
Single automation actions (one garage door or another gate door) - in YAML "action: toggle" it not disabling automation - just do the action.
Double automation actions (my 2 garage doors) -   "action: toggle" just disabling/enabling automation not running it.
Just the logic of this button in dashboard is broken. The automation action is running fine using swtches (remote etc.)
Where could I find it in debug log?

**Comment by spacegaier** [comment]
As said before, we need more info. Please provide as requested the relevant dashboard YAML and perhaps a screenshot to illustrate. Otherwise, there is nothing we can do here.
