### ISSUE TITLE
Area of Automation not filtered correctly

### ISSUE THREAD

**Issue by rgerbranda** [home-assistant/frontend#13449]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have assigned Automations to Areas. But when I apply an Area filter the wrong Automations are shown.

For example, the Automations in the screenshot are assigned to 'Zolder'  area. But when I filter on 'Gang beneden', the are shown.

When I go to Areas > 'Gang beneden' they also are showed, while the are not assigned to that area.

![afbeelding](https://user-images.githubusercontent.com/11868439/186096036-4d220f0d-851d-4c13-9251-7e6b17c50a34.png)
![afbeelding](https://user-images.githubusercontent.com/11868439/186096089-7e4cbc5a-426a-4ace-9477-bf359038600d.png)
![afbeelding](https://user-images.githubusercontent.com/11868439/186097142-250389f4-a38b-45f0-bb36-d1df4adddc81.png)

### Describe the behavior you expected

Automations should be filtered correctly

### Steps to reproduce the issue

1. Go to Areas
2. Select an Area
3. View the Automations

### What version of Home Assistant Core has the issue?

2022.8.6

**Comment by frenck** [comment]
This is correct, the filter in the automation tab doesn't filter on the "area" the automation is in, it filters on the areas the automation affects (e.g., the area the used entities, and devices used in an automation are in).


../Frenck

**Comment by rgerbranda** [comment]
That is a pitty. It gives odd results.
I have for example an automation that I assigned to Frontdoor area, because the trigger is the frontdoor bell. 
When the bell is triggered, the automation flashes the lights in all areas.

Result of filter: the automation appears in the Kitchen area. 

Why do we assign automations to areas, while Home Assistant does not 'listen' to it?

**Comment by frenck** [comment]
> I have for example an automation that I assigned to Frontdoor area, because the trigger is the frontdoor bell.

> Result of filter: the automation appears in the Kitchen area.

That is correct, the automation is using something in that area. Automation filters are there to filter by the things they use.

> Why do we assign automations to areas, while Home Assistant does not 'listen' to it?

You are now generalizing it for your use case, that is fine. But entities can be targeted for areas. Including automation entities, which is why you can assign them to areas.
