### ISSUE TITLE
Scripts & Automations using the UI creates a name ID with a number which is hard to reference later.

### ISSUE THREAD

**Issue by al-jimenez** [home-assistant/frontend#13459]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Scripts & Automations using the UI creates a name ID with a number which is hard to reference later.   This makes it very difficult to reference a specific script in an automation or a specific script in the UI.   I know that has been talked about in the community forum but I have not found a solution to it.   I am adding this here as a placeholder / reminder to get this issue resolved as it makes it difficult to create automations using the UI and causes a lot of extra work to clean up after this.

I have tried to edit scripts.yaml & automations.yaml and change the numbers to "name_item" for each but this causes havoc in the UI where it creates duplicates names,etc.  Maybe I am approaching it the wrong way... ¯\_(ツ)_/¯

If there is a simple solution to this I am not aware.   My only thought is that I edit the scripts.yaml and/or automations.yaml and change these ID numbers to explicit "name_item" before I reference them later.    This is an extra step that I am sure it was not intended.

### Describe the behavior you expected

Expectation is that when you use a name in a script or automation creation in the ui,  then that name becomes the reference and not something else.

### Steps to reproduce the issue

1. Create a script using the UI editor
2.Add the script as a service in a Dashboard View and it may be added correctly.
3.But later when you edit that same Dashboard View the name may change to an ID number.
4. From then on the script it referenced only as the ID number. 

Another scenario:
1. After creating a script: create an automation that references it as a called service and it will be referenced by an ID #

### What version of Home Assistant Core has the issue?

core-2022.8.6

### What was the last working version of Home Assistant Core?

core-2022.8.5

### In which browser are you experiencing the issue with?

Safari 15.6.1

### Which operating system are you using to run this browser?

macOS Big Sur

### State of relevant entities

```txt
Below script can only be referenced with this name '1651422675482':
```

### Problem-relevant frontend configuration

```yaml
SCRIPT SOURCE AFTER USING UI EDITOR:
'1651422675482':
  alias: View Apple TV
  sequence:
  - service: remote.send_command
    data:
      device: AMP
      command: Apple TV
    target:
      entity_id: remote.broadlink_remote
  mode: single
  icon: mdi:apple
```

### Additional information

Forgive me if this has already been reported or submitted.  I am new to this process and trying to understand it.  I did not find a reference to this  issue before I submitted it; but I have found references to it in the community forum.   

The complexity of this software and its support is overwhelming...  but I am in awe of the work and development that has gone into it.   It is one of the best offerings I have seen.  Thanks for your good work.

**Comment by frenck** [comment]
The ID is an internal reference and not meant for consumption (its a mapping between the internal registry and configuration files). If you need a consumable reference, use an `alias`. Every automation as a whole accepts it and so do each trigger, action, and condition individually (additionally) as well.

Besides the alias, an automation description is supported too.

**Comment by al-jimenez** [comment]
Thanks Franck, I was aware of the aliases and descriptions and I use them; but as I mentioned they are showing up with ID #s as the ONLY reference for the scripts.   I have verified this with my iPhone as well, when I create an NFC tag automaton and look to add a Service Call  to a script, then the script only shows up as an ID number with no alias or description or name.   The iPhone is only an example, it also happens on a card in a  Dashboard View.  I add the script as a Service Call to the card, then it enters it in as a ID # in the card. (The call to the script works).  The name only lasts until I save the card.  Maybe there is something wrong with my confg and it's only happening to me ¯\_(ツ)_/¯.   But it has been consistent even after a restart and a restore from backup.    Don't need anyone to help me troubleshoot it, just want to register this as an issue,  since others have also mentioned it in the community forum as well and suggested workarounds that don't seem to work.  Thanks again for your work and efforts.
