### ISSUE TITLE
Analytics config page doesn't use translation keys

### ISSUE THREAD

**Issue by dougiteixeira** [home-assistant/frontend#13463]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Analytics configuration does not use translation keys:
![image](https://user-images.githubusercontent.com/31328123/186305056-067b746e-dff3-41f4-a21c-cfd4720382cb.png)

Excerpts without translation keys:
* https://github.com/home-assistant/frontend/blob/be169f9c83222962b37f6e3d808d2e0feab80d39/src/panels/config/core/ha-config-analytics.ts#L44-L48

* https://github.com/home-assistant/frontend/blob/be169f9c83222962b37f6e3d808d2e0feab80d39/src/components/ha-analytics.ts#L12-L23

* https://github.com/home-assistant/frontend/blob/be169f9c83222962b37f6e3d808d2e0feab80d39/src/components/ha-analytics.ts#L43-L46

* https://github.com/home-assistant/frontend/blob/be169f9c83222962b37f6e3d808d2e0feab80d39/src/components/ha-analytics.ts#L76-L79

* https://github.com/home-assistant/frontend/blob/be169f9c83222962b37f6e3d808d2e0feab80d39/src/components/ha-analytics.ts#L87-L90

* https://github.com/home-assistant/frontend/blob/be169f9c83222962b37f6e3d808d2e0feab80d39/src/components/ha-analytics.ts#L87-L90

* https://github.com/home-assistant/frontend/blob/be169f9c83222962b37f6e3d808d2e0feab80d39/src/components/ha-analytics-learn-more.ts#L5-L11

### Describe the behavior you expected

It was expected that the frontend would use translation keys and they would be available in Lokalise.

### Steps to reproduce the issue

1. Change the system language to one other than English.
2. Access the analytics settings page: Settings > System > Analytics

### What version of Home Assistant Core has the issue?

2022.8.6

### What was the last working version of Home Assistant Core?

None

### In which browser are you experiencing the issue with?

104.0.5112.102

### Which operating system are you using to run this browser?

Windows 10

**Comment by spacegaier** [comment]
@balloob I am pretty sure I had raised (or perhaps even had a PR for that) some time ago, but I think your (?) decision was that those texts should not be translated as someone mentioned the risk of potentially incorrect/unclear community translations which were deemed a problem for such a touchy topic as data sharing?

Does this decision still hold up or would you be fine with translations now that this feature is more established (although not sure if that really matters in light of the original reasoning)?

**Comment by dougiteixeira** [comment]
Still pending.

**Comment by dougiteixeira** [comment]
Still pending.

**Comment by piitaya** [comment]
Hi 👋. As the feature is understood now and active some time, we decided to translate the analytics like any other page. I opened a PR for that.
