### ISSUE TITLE
Error every time I open HA app on android

### ISSUE THREAD

**Issue by rossbate** [home-assistant/frontend#13476]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Everytime i open the app since 2008.1 i get an error along with my phone vibrating multiple times
Error: Failed to call service system_log/write. undefine
![Screenshot_20220824-185234_Home Assistant](https://user-images.githubusercontent.com/39503487/186494709-d2d64914-89d2-42ce-8ae7-7d30255526fb.jpg)
d

### Describe the behavior you expected

As previous versions, never had this happen before

### Steps to reproduce the issue

1. Open the app on android v12 
2. Open browser for HA Microsoft Edge
3.
...

### What version of Home Assistant Core has the issue?

2022.8.6

### What was the last working version of Home Assistant Core?

2022.7.7

### In which browser are you experiencing the issue with?

App + Microsoft Edge

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
N/A
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

**Comment by Quentame** [comment]
As you described it don't seems only Android related.

First, why was the issue created in the frontend and not Android ?

Second, I think the issue is more backend related (core), and you should move the issue there.
