### ISSUE TITLE
Cannot edit Home Zone as enter UI loop

### ISSUE THREAD

**Issue by vaderag** [home-assistant/frontend#13471]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

It was suggested to resolve and issue that I change my Home Zone area from 100 to 150m

However, there is now no way to reach this in the UI as you end up in a loop

### Describe the behavior you expected

There is no way to edit your zone radius. Apparently this used to exist
Thread: https://community.home-assistant.io/t/pros-and-cons-of-using-geocoded-location/385701/10

### Steps to reproduce the issue

Map --> edit zone -> edit -> back to map

Same via Settings -> area & zones

### What version of Home Assistant Core has the issue?

22.8.6

**Comment by Quentame** [comment]
You are talking about the home zone, not all zones, please update the title accordingly.

**Comment by vaderag** [comment]
> You are talking about the home zone, not all zones, please update the title accordingly.

I'm not sure if I am - I only have a home zone so haven't tested others

**Comment by Quentame** [comment]
I do have multiple zones, and indeed we can edit the range, with a white dot on the edge of the zone circle, or with a radius property (at the end of the form), see screenshot:

![image](https://user-images.githubusercontent.com/14821482/186915048-17f000e2-6e55-4839-86bf-62d78b6ea3b1.png)

I don't understand why it's not possible with Home zone, it's also making me crazy ...
I think I saw issues created about this

Let's try adding your work/sport/grocery zones !

PS: Frenck asked a feature that he would build for 2022.4, and I asked him that, multiple other people did too, and editing groups, that last one was chosen https://twitter.com/Quanta74/status/1505060708970545155

**Comment by eprouty** [comment]
Encountering this issue as well, editing non-home zones works fine. But the Home zone edit creates an infinite loop in the UI.

**Comment by vaderag** [comment]
Not stale still an issue

**Comment by CTParkinson** [comment]
+1 

Had the message saying I can't edit the home zone since it was defined in the `configuration.yaml`  - it was not...

Removed the whole `homeassistant` block from the configuration, and set the config that was removed via the other UI config options, but now I get the loop when trying to edit the Home zone. Just can't win.

**Comment by rmeekers** [comment]
Same issue here. Is there a workaround to fix this (apart from adding it to configuration.yaml)?

**Comment by YoinkZed** [comment]
+1

Previously I had this configured in the configuration.yaml file, but I removed most of it. Now I am able to edit everything under "General". But when I click "Edit location" and then edit next to the "Home" zone, then it loops back to "General" again.

The only "fix" I've found so far, is to state this under homeassistant in the configuration.yaml file, but then it greys out the rest of the options in the UI.

**Comment by bramkragten** [comment]
You can drag your home zone on the map on the page `/config/zone`

**Comment by rmeekers** [comment]
> You can drag your home zone on the map on the page `/config/zone`

Hmm, indeed. But there is no way to adjust the radius? Or did I overlook that possibility?

**Comment by bramkragten** [comment]
No, that is not possible atm unfortunately

**Comment by rmeekers** [comment]
FYI: The radius can be overwritten via the configuration without loosing access to the rest of the configuration via the interface.

```
homeassistant:
    packages: !include_dir_named packages
    customize:
        zone.home:
          radius: !secret ha_home_radius
```

**Comment by snerdish** [comment]
> You can drag your home zone on the map on the page `/config/zone`

Sadly, there's no way to save that. It simply reverts to the default location (somewhere in Amsterdam)

**Comment by ariekraakjr** [comment]
Same problem here.

**Comment by ddanielww** [comment]
Moved house and can’t change my home location, when will this be fixed?

**Comment by Quentame** [comment]
> Moved house and can’t change my home location, when will this be fixed?

This issue isn't related to the home location but to the size of the zone.

To change your Home location, go to Settings -> General -> change the pointer on the map.

**Comment by ddanielww** [comment]
![image](https://github.com/home-assistant/frontend/assets/26042496/4a0bab0e-9ef6-44aa-b07b-b4a24a419690)

I do not want to drag the location 500 miles, and try to zoom into the correct address.

Why can you not change latitude and longitude for your home location but you can for other zones?

**Comment by flintiii** [comment]
Greetings,
What is the URL to change the map home location?
