### ISSUE TITLE
No core backup in partial backup menu after Supervisor 2022.08.x

### ISSUE THREAD

**Issue by modestpharaoh** [home-assistant/frontend#13483]
### The problem

After upgrading to V2022.08, home assistant core partial backup is missing. I can’t include home assistant core config in the backup … only other folders and addons are available for backup!?

Seems that a few people reported that 
https://community.home-assistant.io/t/after-upgrading-to-v2022-08-supervised-version-home-assistant-core-partial-backup-is-missing/450452

I am not expert, but suspecting that could be a supervisor container bug, as I had a home assistant instant was running 2022.7.x version and got same issue, after recent report. so it might be the Supervisor updated to 2022.08.x during that update.

![image](https://user-images.githubusercontent.com/30378999/185932760-a4068cee-eec8-4606-9276-03ae87d5dbac.png)

Here are the home assistant version that running:
Home Assistant 2022.8.6
Supervisor 2022.08.3
Frontend 20220802.0 - latest

### What version of Home Assistant Core has the issue?

2022.8.6

### What was the last working version of Home Assistant Core?

2022.8.6

### What type of installation are you running?

Home Assistant Supervised

**Comment by ludeeus** [comment]
As a workaround, until a fix is released, you can use the service.

[![Open your Home Assistant instance and show your service developer tools with a specific service selected.](https://my.home-assistant.io/badges/developer_call_service.svg)](https://my.home-assistant.io/redirect/developer_call_service/?service=hassio.backup_partial)

```yaml
service: hassio.backup_partial
data:
  homeassistant: true
```
