### ISSUE TITLE
RFXTRX: Doesn't work with RTS (SIMU screens)

### ISSUE THREAD

**Issue by HuubClaassen** [home-assistant/frontend#13501]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Followed the documentation on https://www.home-assistant.io/integrations/rfxtrx to add 3 RTS devices 1 sunscreen (Somfy) and 2 Shutters (SIMU). In the RFX mngr they all work. In home assistant I can add all 3 devices but only the sunscreen works. 

### Describe the behavior you expected

I expected the shutters would respond

### Steps to reproduce the issue

1. follow the steps on the original documentation
2. 
3.
...

### What version of Home Assistant Core has the issue?

Supervisor 2022.08.3 Operating System 8.5

### In which browser are you experiencing the issue with?

Tried in Multiple browsers (safari mobile and desktop, edge and chrome

### Which operating system are you using to run this browser?

Ios, Mac OSX and windows 10

**Comment by elupus** [comment]
Can you please reopen this issue in core repo instead. Its likely need backend support too.
