### ISSUE TITLE
Energy dashboard not working with Slimmelezer

### ISSUE THREAD

**Issue by SanderBroek** [home-assistant/frontend#13505]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The slimmelezer sensors are reading values correctly, but the dashboard isn't showing any results. 

### Describe the behavior you expected

Energy dashboard should describe 

### Steps to reproduce the issue

1. Integrate SLimmelezer
2. Setup dashboard
3. Wait at least 2 hours

Detailed information and screenshots are in the HA Forum: 
https://community.home-assistant.io/t/how-to-setup-the-energy-dashboard-correctly/410284

### What version of Home Assistant Core has the issue?

2022.8.7

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

Windows 10

### Additional information

Marcel from Slimmelezer investigated the issue and concluded there's a problem in HA itself.

**Comment by spacegaier** [comment]
> Detailed information and screenshots are in the HA Forum:
https://community.home-assistant.io/t/how-to-setup-the-energy-dashboard-correctly/410284

There seems to be, but not in English 😉 Can you please provide the details here in EN, I fear otherwise the chances of someone looking at that are quite a bit lower.
