### ISSUE TITLE
Automation traces open outside of the mobile apps

### ISSUE THREAD

**Issue by dmulcahey** [home-assistant/frontend#13549]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On 2022.09.b1 the automation traces menu item opens in a new browser window instead of where it was toggled in the mobile app. 

https://share.icloud.com/photos/012gtbxbNCwToGKDV3_5C5piQ

### Describe the behavior you expected

The traces should open in the app

### Steps to reproduce the issue

1. Go to an automation in the iOS app
2. In the 3 dots menu select traces

### What version of Home Assistant Core has the issue?

2022.09.b1

### Which operating system are you using to run this browser?

iOS

**Comment by Anto79-ops** [comment]
As the title suggests, this is also true for the Android-Chrome combination.

**Comment by dmulcahey** [comment]
Resolved in 2022.09.b3
