### ISSUE TITLE
All weekly schedules disappearing 

### ISSUE THREAD

**Issue by tomlut** [home-assistant/frontend#13547]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When adding a weekly schedule on Sunday it disappears from the schedule view. 

Attempting to add the schedule again causes a warning of duplicate schedules. 

![1](https://user-images.githubusercontent.com/10679300/187879208-e6f3bdf6-be3b-4750-a446-084a1819644f.png)

![2](https://user-images.githubusercontent.com/10679300/187879551-7e53b4c3-63db-42e7-be28-e1dfed447ff7.png)

### Describe the behavior you expected

Schedules on Sunday not to disappear.

### Steps to reproduce the issue

1. Create a weekly schedule helper
2. Add a schedule on Sunday
3. Focus the cursor outside the schedule
4. Attempt to re-add the missing Sunday schedule
5. Attempt to save the helper
...

### What version of Home Assistant Core has the issue?

core-2022.9.0b1

### In which browser are you experiencing the issue with?

Firefox 104.0.1, Chrome 104.0.5112.102

### Which operating system are you using to run this browser?

Windows 10 21H2

**Comment by tomlut** [comment]
Still an issue on 2022.9.0b2.

**Comment by tomlut** [comment]
2022.9.0b3 - Now happening with schedules on any day. They all disappear from the frontend but are still set:

![Untitled](https://user-images.githubusercontent.com/10679300/188294125-c3860ca7-1c85-42c6-9b4a-c312ba4b4c99.png)

**Comment by tomlut** [comment]
TIme zone as requested by balloob:

UTC +10
Australia/Hobart

**Comment by ccorderor** [comment]
> 2022.9.0b3 - Now happening with schedules on any day. They all disappear from the frontend but are still set:

Found the same problem in 2022.9.0b3.
My time zone is UTC+2 (Europe/Madrid)

**Comment by tomlut** [comment]
Fixed in 2022.9.0b4.
