### ISSUE TITLE
Schedule helper loses half hour settings

### ISSUE THREAD

**Issue by woodmj74** [home-assistant/frontend#13544]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When editing a schedule helper, if it was originally set to end or start on half past the hour, when you return to edit the helper the UI is showing it running on whole hours not the original set half past the hour.

### Describe the behavior you expected

UI allows you to set by the half hour, this should be displayed as such when you reload it

### Steps to reproduce the issue

1: create a new schedule helper
2: set an "on" time for 21:00 to 21:30 (screen shot 1)
3: create the helper

...wait for the time to come around to check the scheduled end time...

4: at 21:05 checked the state of the helper and state is 'on' with attribute next event is 21:30
5: edit the helper the time is blocked out as 21:00 to 22:00 (screen shot 2)
6: save the helper

7: checking the attributes the next event is still 21:30 

![image](https://user-images.githubusercontent.com/68328701/187769181-3252b9db-ddae-4d72-b205-21c86ad09f1b.png)
![image](https://user-images.githubusercontent.com/68328701/187771371-263ff4b0-0a89-4262-9d38-e1ec4f454db6.png)

### What version of Home Assistant Core has the issue?

2022.9.0b0

### In which browser are you experiencing the issue with?

Google Chrome 104.0.5112.102, Edge 104.0.1293.70

### Which operating system are you using to run this browser?

W11

**Comment by nicedevil007** [comment]
https://github.com/home-assistant/frontend/issues/13865#issuecomment-1258385996

same here and some screens from my site in the above issue

**Comment by sldewit** [comment]
Same here, also opened this ticket for it: #13877.
