### ISSUE TITLE
Entity Icon Filter/Search not working

### ISSUE THREAD

**Issue by tube0013** [home-assistant/frontend#13550]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When attempting to change and Entities' Icon in it's setting, attempting to filter/search the icons is not usable, it shows the results for a flash then resets to the top of the list. Tested iOS app and Chrome.

https://user-images.githubusercontent.com/11084412/187907747-22fcc57c-6a29-409e-83fc-fb38329c9d95.mov

### Describe the behavior you expected

list shows filtered items

### Steps to reproduce the issue

1. go to an entities settings
2. click in Icon box 
3. type something
...

### What version of Home Assistant Core has the issue?

2022.9.0b1

### In which browser are you experiencing the issue with?

iOS 15.6.1 (HA App/Safari) / Chrome 104.0.5112.101

### Which operating system are you using to run this browser?

iOS and Mac 12.5.1

**Comment by pgsylvestre** [comment]
I experienced this same issue with the new 'schedule' helper in 2022.09.0b3.


![image](https://user-images.githubusercontent.com/61101978/188268654-2610734d-d310-4c90-849a-e161047da0cf.png)

**Comment by pgsylvestre** [comment]
I have experienced the same issue in 2022.09.0b3

![image](https://user-images.githubusercontent.com/61101978/188268775-6cb53e38-169a-414c-b3c3-50cec001e97d.png)
