### ISSUE TITLE
Kodi integration: Cannot set a target/device_id

### ISSUE THREAD

**Issue by Grandma-Betty** [home-assistant/frontend#13566]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This issue is related to the Kodi integration of HA.
When creating an action within an automation it is not possible to set a target/device_id as the input mask is completely missing:

![Capture](https://user-images.githubusercontent.com/48346793/188123770-05c31878-30cf-4db3-829a-a2a84227e488.JPG)

This results in the following error when executing the action:
```
Error running action
must contain at least one of entity_id, device_id, area_id.. Got {'type': 'execute_script', 'sequence': [{'service': 'kodi.call_method', 'data': {'method': 'System.Shutdown'}}], 'id': 41}
```
It is indeed possible to set the according target/device_id manually via **automations.yaml** by using the following two lines...
```
    target:
      entity_id: media_player.example
```
...which makes the action working but I guess this is not intended to be configured manually by yaml.

### Describe the behavior you expected

It should be possible to set a Kodi target/device_id directly via the automations input mask.

### Steps to reproduce the issue

1. Set up the Kodi integration
2. Create an automation via the GUI and for action choose "_Call service_" --> "_kodi.call_method_"

There you will mention that no possibility is given to set the according Kodi target/device_id.

### What version of Home Assistant Core has the issue?

core-2022.8.7

**Comment by spacegaier** [comment]
I don't have a Kodi setup, so I cannot reproduce that myself, but looking at the service definition of `call_method` from the Kodi integration, it requires the target entity to be a `media_player` from `kodi`. 

You mentioned that via a manual automation it works, but is that media player you used manually actually from `kodi`? If it just a random other media player, then the manual automation might accept it, but the UI potentially correctly is not showing any values?
