### ISSUE TITLE
Camera Info PopUp > Too big

### ISSUE THREAD

**Issue by KNXBroker** [home-assistant/frontend#13581]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

My Generic Camera Image is displayed in XXXL when opening the more info popup menu, even scroll bars are displayed. This was not the case in the last stable version. Original camera size: 320x240.  Tested with two browsers. 

![image](https://user-images.githubusercontent.com/25910703/188320951-14f1ac50-7f7f-4c7b-acf1-929bc3487461.png)

Here my camera setup:
![image](https://user-images.githubusercontent.com/25910703/188321109-76e38577-74f4-49d3-a99b-79c509916a55.png)

### Describe the behavior you expected

Display much more smaller.

### Steps to reproduce the issue

1. Create generic camera is shown above
2. Open entity popup 
...

### What version of Home Assistant Core has the issue?

2022.8.7

### What was the last working version of Home Assistant Core?

2022.9.0b3

### In which browser are you experiencing the issue with?

Chrome 104.0.5112.102  // Edge 105.0.1343.27

### Which operating system are you using to run this browser?

Windows 11

**Comment by agneevX** [comment]
Yes, this does not let me view the entire camera image.

**Comment by avehome** [comment]
Even better, get rid of those menus like before. If je need to change anything you can find the menu in home assistant settings -> entities. I meen, how many times are you using this menu anyway? I only use it ones when I setup de camera and that's it.

**Comment by agneevX** [comment]
Wow it's been a month and camera popups are still broken.

**Comment by NobleKangaroo** [comment]
Thank you for your report, @KNXBroker!

After being stuck on 2022-06 due to work being super busy and just recently having the chance to upgrade and fix the things that I knew would be broken and need addressing, this issue - the camera dialogs being way too big - was driving me nuts. I took some time to deep dive into it and figured out what happened, why, and submitted PR #14179 which should fully address this.

**Comment by cscoppafox** [comment]
@NobleKangaroo   I just update to 2022.11 beta5 which has the updated frontend, and the `90vw` doesn't seem to be working.  It's stuck at a static size, close to the same size as the settings dialog:

![image](https://user-images.githubusercontent.com/111901305/199149475-18f86fed-ae8f-4497-a3c2-af5bd4bf2b77.png)

**Comment by NobleKangaroo** [comment]
@cscoppafox Did you click the title text to toggle larger view? I kind of just reinstated the previous code so unsure why it wouldn't work. I'll try to familiarize myself with how to run Home Assistant beta and take a look at it today or tomorrow and see what's going on.

**Comment by cscoppafox** [comment]
> @cscoppafox Did you click the title text to toggle larger view? I kind of just reinstated the previous code so unsure why it wouldn't work. I'll try to familiarize myself with how to run Home Assistant beta and take a look at it today or tomorrow and see what's going on.

Hi, yes I've tried single and double clicking both the title bar and the video itself, it simply won't change size at all.  I remember the old behavior you're talking about, but it's not working like that ATM.

**Comment by NobleKangaroo** [comment]
> > @cscoppafox Did you click the title text to toggle larger view? I kind of just reinstated the previous code so unsure why it wouldn't work. I'll try to familiarize myself with how to run Home Assistant beta and take a look at it today or tomorrow and see what's going on.
> 
> Hi, yes I've tried single and double clicking both the title bar and the video itself, it simply won't change size at all. I remember the old behavior you're talking about, but it's not working like that ATM.
> 
> EDIT: If you happen to be running Docker, the tag to use is:
> 
> [homeassistant/home-assistant:beta](https://hub.docker.com/r/homeassistant/home-assistant/tags/)

Got it. I just backed up my main instance and enabled beta there. I really need to get around to setting up a full beta instance for more than just dev work. :)

It looks like [my changes](https://github.com/home-assistant/frontend/pull/14179/files) aren't reflected in the file for either [the dev branch](https://github.com/home-assistant/frontend/blob/dev/src/dialogs/more-info/ha-more-info-dialog.ts) or [the master branch](https://github.com/home-assistant/frontend/blob/dev/src/dialogs/more-info/ha-more-info-dialog.ts) right now, though I don't understand why as the PR was accepted then subsequently mentioned in #14203 (for 2022-10-26).

@bramkragten do you have any idea? Might be that I'm just missing something, but looks like code from approved PR #14179 isn't in dev or master right now. Thank you!

**Comment by Scope666** [comment]
> **Edit:** It Looks like #14246 removed the CSS that fixes the camera dialog - [the `auto` line](https://github.com/home-assistant/frontend/commit/17ac81a7081d671449c7c4a9f8bb6a2b002faecd#diff-c0249419a6c5313fc87eea15a137565a4bca34413bc10fbab222bac7938657fcL300-L303) that allows the video to be as tall as the screen - which results in the camera dialog being always set to a fixed width ([580px](https://github.com/home-assistant/frontend/blob/e2104c1591f8daad81838feda7a4ec7f41eae8e4/src/dialogs/more-info/ha-more-info-dialog.ts#L307)). May want to revisit this as the reversion of this code reintroduces bug #13581.

Yeah, I'm not a coder but I know a little, and I reviewed your PR, I could tell that something changed because the window wasn't huge anymore, but at the same time it wasn't doing the 90% of the viewport thing that I saw in your code.  I know something went wrong with the merge...

**Comment by NobleKangaroo** [comment]
> > **Edit:** It Looks like #14246 removed the CSS that fixes the camera dialog - [the `auto` line](https://github.com/home-assistant/frontend/commit/17ac81a7081d671449c7c4a9f8bb6a2b002faecd#diff-c0249419a6c5313fc87eea15a137565a4bca34413bc10fbab222bac7938657fcL300-L303) that allows the video to be as tall as the screen - which results in the camera dialog being always set to a fixed width ([580px](https://github.com/home-assistant/frontend/blob/e2104c1591f8daad81838feda7a4ec7f41eae8e4/src/dialogs/more-info/ha-more-info-dialog.ts#L307)). May want to revisit this as the reversion of this code reintroduces bug #13581.
> 
> Yeah, I'm not a coder but I know a little, and I reviewed your PR, I could tell that something changed because the window wasn't huge anymore, but at the same time it wasn't doing the 90% of the viewport thing that I saw in your code. I know something went wrong with the merge...

No worries, it looks like there was just a mistake made with another PR that removed the "full height of screen" size of the camera dialogs (like it was in the past, but I guess some people don't like that) but also had a typo in the code that broke the resizing of all dialogs. I sent a PR, which should hopefully clear this up for good. :)

**Comment by Scope666** [comment]
Thanks, I’d love to have it work like it used to.    😉

**Comment by cscoppafox** [comment]
THANK YOU @bramkragten, that is a thing of beauty:     :) 

![image](https://user-images.githubusercontent.com/111901305/199498065-fc4291ea-d12b-421c-9466-fb8eb2af0a1c.png)

**Comment by agneevX** [comment]
This still seems to be an issue although it's probably a result of the merged PR:

https://reddit.com/r/homeassistant/comments/ync5a4/2022111_camera_window_size_issue/

**Comment by NobleKangaroo** [comment]
Yes it should be resolved. It takes a cache clear or reboot sometimes to wipe out the old CSS. Try that and report back. I've confirmed the new 2011.1 is working as intended locally on a fresh install but there could be edge cases.

On November 6, 2022 5:14:35 AM EST, Agneev Mukherjee ***@***.***> wrote:
>This still seems to be an issue although it's probably a result of the merged PR:
>
>https://reddit.com/r/homeassistant/comments/ync5a4/2022111_camera_window_size_issue/
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/home-assistant/frontend/issues/13581#issuecomment-1304765901
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>

Regards,

Chris
--
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kicker10BOG** [comment]
Is there a way to have it default to the big view?

**Comment by NobleKangaroo** [comment]
> Is there a way to have it default to the big view?

**Short answer** - Not as far as I know, at least not in Home Assistant natively. It defaults to the same width as other cards now. I think the idea is to unify the UI as much as possible, which means bringing the camera dialog along for the ride.
**Long answer** - Yes, but it takes quite a bit of work. I'm personally running Home Assistant supervised on Debian, and have access to all of the repos to install everything needed to follow the [frontend development](https://developers.home-assistant.io/docs/frontend/development/) guide. The gist of it is that you have to:
  1. Clone the frontend repo to your local machine.
  2. Add the [frontend integration](https://www.home-assistant.io/integrations/frontend), defining [development_repo](https://www.home-assistant.io/integrations/frontend#development_repo) as your local copy.
  3. Install Node.js and nvm and Yarn.
  4. Use nvm to download dependencies and start the development script.
  5. Make the changes in your local copy, clear every device's cache, and the changes should take effect.

It's not as easy as changing a setting or modifying a card with [card-mod](https://github.com/thomasloven/lovelace-card-mod). I wish there were a way to do it without having to keep a local copy of the frontend, as it's prone to fast updates and breaks as Home Assistant often changes things even between minor versions.

If anyone else has another way to do this, feel free to comment.

**Comment by kicker10BOG** [comment]
> > Is there a way to have it default to the big view?
> 
> **Short answer** - Not as far as I know, at least not in Home Assistant natively. It defaults to the same width as other cards now. I think the idea is to unify the UI as much as possible, which means bringing the camera dialog along for the ride.
> 
> **Long answer** - Yes, but it takes quite a bit of work. I'm personally running Home Assistant supervised on Debian, and have access to all of the repos to install everything needed to follow the [frontend development](https://developers.home-assistant.io/docs/frontend/development/) guide. The gist of it is that you have to:
> 
> 1. Clone the frontend repo to your local machine.
> 2. Add the [frontend integration](https://www.home-assistant.io/integrations/frontend), defining [development_repo](https://www.home-assistant.io/integrations/frontend#development_repo) as your local copy.
> 3. Install Node.js and nvm and Yarn.
> 4. Use nvm to download dependencies and start the development script.
> 5. Make the changes in your local copy, clear every device's cache, and the changes should take effect.
> 
> It's not as easy as changing a setting or modifying a card with [card-mod](https://github.com/thomasloven/lovelace-card-mod). I wish there were a way to do it without having to keep a local copy of the frontend, as it's prone to fast updates and breaks as Home Assistant often changes things even between minor versions.
> 
> If anyone else has another way to do this, feel free to comment.

Yeah, I don't feel like going through all of that. On a computer, it's just really annoying to click a stream and have it open up either slightly bigger or sometimes even smaller than it already was. On my tablet though, the large view requires a bit of scrolling (I think due mostly to the menu at the top of the popup). A middle ground where it doesn't go so big it needs scrolling would be perfect. I know from experience that can be difficult to get right though.
