### ISSUE TITLE
Schedule helper disappears when editing out of order

### ISSUE THREAD

**Issue by pbulteel** [home-assistant/frontend#13583]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating a schedule helper, the schedule disappears when you edit items out of order and gives an error once you add another schedule at the SAME time or overlap of time

### Describe the behavior you expected

Schedule shouldn't disappear when changing fields

### Steps to reproduce the issue

Steps to reproduce bug 1
1. Go to helpers
2. Create new helper
3. Select schedule
4. Click and drag a timeframe
5. Click on name and give it a name
6. Schedule disappears
7. Bug 2 - Click and drag another timeframe within the originally created (now not visible) timeframe.
8. Click save
9. Error appears on top

![schedule-error](https://user-images.githubusercontent.com/5732473/188327861-ad090beb-55a4-41aa-8a2d-94766cc8cb9a.gif)

### What version of Home Assistant Core has the issue?

Home Assistant 2022.9.0b3

### In which browser are you experiencing the issue with?

Version 104.0.5112.101 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Linux Pop!OS 22.04

**Comment by spacegaier** [comment]
Should be fixed now via https://github.com/home-assistant/frontend/pull/14529
