### ISSUE TITLE
picture entity cards showing a camera picture should default to 16:9 while loading

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#13605]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When a `<hui-picture-entity-card>` is showing a camera entity (as is done by generated Lovelace), we should show the card with a 16:9 aspect ratio while loading to avoid the interface jumping in most cases. If camera is not 16:9, it will still jump, but it would also do that now as there is now just height for the name toolbar.

### Describe the behavior you expected

The card has a 16:9 aspect ratio until it knows it's unavailable, the picture fails to load or the ratio is set by loading the image.

### Steps to reproduce the issue

1. Configure camera
2. Open LL dashboard on a slower connection (ie mobile data)

### What version of Home Assistant Core has the issue?

all

**Comment by piitaya** [comment]
Fixed by https://github.com/home-assistant/frontend/pull/14245
