### ISSUE TITLE
Large numbers are not handled well

### ISSUE THREAD

**Issue by JamesOsborn-SE** [home-assistant/frontend#13612]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Numbers changes without error or warning and caused confusion.

### Describe the behavior you expected

change the large number to a string or display a warning/error

### Steps to reproduce the issue

1. Go to /developer-tools/service and choose a service with an input like notify.notify
2. enter 1111111111111111111 without double quotes and click Go to YAML Mode  it's now 1111111111111111200
3. or 9111111111111111111 without double quotes and click Go to UI Mode  it's now 9111111111111111000

### What version of Home Assistant Core has the issue?

2022.8.7

### In which browser are you experiencing the issue with?

FireFox 104.0.1 (64-bit)

### Which operating system are you using to run this browser?

Ubuntu 22.04

**Comment by bdr99** [comment]
This issue still exists in 2022.11.5.

**Comment by bdr99** [comment]
Issue still exists in 2023.7.3.

**Comment by bdr99** [comment]
Issue still exists in 2023.10.5.

**Comment by JamesOsborn-SE** [comment]
Issue still exists in 2024.1.5

**Comment by JamesOsborn-SE** [comment]
Issue still exists in 2024.4.4

**Comment by JamesOsborn-SE** [comment]
I think they are waiting for a release with the metadata… I don't thin it's necessary, but I don't think there's a need to be in a hurry either. 
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14910

**Comment by JamesOsborn-SE** [comment]
Issue still exists
