### ISSUE TITLE
Generated (default) dashboard rendering issue

### ISSUE THREAD

**Issue by spf13** [home-assistant/frontend#13625]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After adding the Big Ass Fans integration (I'm pretty sure that was the culprit) the generated dashboard was instead replaced with an error:

> Error loading the view strategy:
> TypeError: Cannot read properties of undefined (reading 'toUpperCase')

### Describe the behavior you expected

Expect the generated dashboard to render. 

### Steps to reproduce the issue

1. Add integration BAF
2. Add some devices to that integration
3. Dashboard is now broken

This happened to on instance of Home Assistant I had so I killed that Virtual Machine and started again from scratch. I believe that the culprit was the BAF integration as the dashboard worked before I added that integration and was broken after I did (though I wasn't intending to troubleshoot this so I wasn't isolating all of my steps). 
...

### What version of Home Assistant Core has the issue?

 2022.8.7

### In which browser are you experiencing the issue with?

Chrome, Vivaldi, Firefox (all recent versions)

### Which operating system are you using to run this browser?

macOS, Linux, Windows.

**Comment by spacegaier** [comment]
Indeed it is, but nothing jumps out at me and just copying that over to a demo test fan entity, does not result in any exceptions on my end in the current dev version.

**Comment by spf13** [comment]
Hmm. I'm not positive it was that integration that did it, I was checking the dashboard somewhat regularly as I set things up and did notice it right after adding BAF. Is there any other information I could provide? Would it help to create dashboards myself and add a few entities until I recreate the error? Are there logs specific to the frontend?

**Comment by spacegaier** [comment]
> Would it help to create dashboards myself and add a few entities until I recreate the error? Are there logs specific to the frontend?

With that you could confirm with certainty which entity is actually causing the issue and in which state it has to be for the exception to appear. That might then lead to a reproducible setup that we can then have a look at from the code perspective as to why it happens.
