### ISSUE TITLE
White space and other formatting issues on area pages

### ISSUE THREAD

**Issue by krazos** [home-assistant/frontend#13624]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After core-2022.9.0b5 and frontend-20220905.0, area pages are missing leading white space in boxes, and Automations/Scripts header text.  See screenshots from both web and mobile app views. 

I have reset frontend cache on both browser and iOS app, but formatting issues persist.

### Describe the behavior you expected

Boxes on area page should include white space above header, and missing headers for Automations/Scripts boxes should be restored.

### Steps to reproduce the issue

N/A

### What version of Home Assistant Core has the issue?

core-2022.9.0b5

### What was the last working version of Home Assistant Core?

core-2022.9.0b4

### In which browser are you experiencing the issue with?

Google Chrome 104.0.5112.102

### Which operating system are you using to run this browser?

Windows 11

### Additional information

Web:

![image](https://user-images.githubusercontent.com/18428022/188679213-41299657-a0f1-4984-a561-d4f72040e71e.png)

Mobile:

![area_laundry_room_iphone](https://user-images.githubusercontent.com/18428022/188679252-6a3053c6-1ceb-4d0b-9265-16245e88791a.png)

**Comment by balloob** [comment]
I am unable to reproduce this on iOS.

**Comment by krazos** [comment]
This may be an interaction between a custom theme and the frontend cache not totally clearing when I switch the theme back to default. I'll try to confirm, and I'll close the issue if I conclude that's indeed the problem.

**Comment by jackwilsdon** [comment]
This was caused by [`card-mod`](https://github.com/thomasloven/lovelace-card-mod) for me - I've raised https://github.com/thomasloven/lovelace-card-mod/issues/222 for it.
