### ISSUE TITLE
xiaomi_miio.vacuum_goto service does not allow to choose Target

### ISSUE THREAD

**Issue by wrobelda** [home-assistant/frontend#13632]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When trying to create an Automation Script via the UI, the xiaomi_miio.vacuum_goto  does not show the usual Target tags to choose from — it's blank instead. 

### Describe the behavior you expected

Regular entity selection widget should be shown

### Steps to reproduce the issue

1. Create a new automation
2. Choose `xiaomi_miio.vacuum_goto` as the service
3. Notice the target widget is not shown

<img width="1271" alt="Screen Shot 2022-09-06 at 11 29 13 PM" src="https://user-images.githubusercontent.com/1702435/188745712-d760cbe8-b259-49aa-ac84-dd4a220c5257.png">

### What version of Home Assistant Core has the issue?

2022.8.7

### In which browser are you experiencing the issue with?

Safari

### Which operating system are you using to run this browser?

macOS 12.5.1

**Comment by spacegaier** [comment]
Any errors in the browser log? You did not fill that out in the issue template, so not sure if you had verified that.

**Comment by wrobelda** [comment]
Don't see any errors in JS Console. I also tried the same in HA iOS app, to no avail.

**Comment by wrobelda** [comment]
Just checked and it is no longer an issue.
