### ISSUE TITLE
Add application credentials dialog not opened

### ISSUE THREAD

**Issue by rvandick** [home-assistant/frontend#13647]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

when you want to add an application credential the window will not open to enter credentials. This happens when you want to enter authentication credentials when configuring an integration, but also when you want to add it manual via the 3 dots in the integration menu. 

The problem occurs in google chrome and edge on Windows OS, but also in the companion app on IOS

### Describe the behavior you expected

This window has to presented
![image](https://user-images.githubusercontent.com/37018074/188943513-023f4c75-4bed-41a1-957c-efbb498cce5a.png)

### Steps to reproduce the issue

add manual
1. navigate to setting -> devices & services -> integrations 
2. click the 3 dots -> application credentials
3. click application credential. at this step nothing happens

add through integration (nest)
1. Nest: Create and configure Cloud Project -> submit
2. Setting up Nest requires configuring application credentials. Do you want to do that now? -> OK. at this step nothing happens

also tried with other integrations (husqvarna automower) with the same result

I can't find any errors in logging

### What version of Home Assistant Core has the issue?

core-2022.9.0b6

### What was the last working version of Home Assistant Core?

I'm not aware if it worked for me sinds it is was introduced in 2022.6

### In which browser are you experiencing the issue with?

Versie 104.0.5112.102

### Which operating system are you using to run this browser?

 Microsoft Windows 10 Enterprise 10.0.19044 N/A Build 19044

**Comment by rvandick** [comment]
just updated to 2022.9.0 and give it a try. One time the dialog has been opened, but after that no succes. Same problem then before updating

**Comment by rvandick** [comment]
No one else this issue? I can't get it working

**Comment by rvandick** [comment]
Still the same issue. I have updated to the latest versio of Home Assistant en I even have started with a fresh install of HA. Then I restored a backup to get mij config back. Before the restore I could create application credentials after restore I could not. So it has to be anything in combination with my config.

**Comment by rvandick** [comment]
finally found a solution. it was a HACS addon that I no longer used that caused the problem. after i removed it everything works fine.

**Comment by rvandick** [comment]
.

**Comment by UndIch** [comment]
Would be helpful to share the name of the add-on causing the problem ;) so others with the same problem could find a solution. Thanks.

**Comment by rvandick** [comment]
It was the Husqvarna robot mower app
