### ISSUE TITLE
"People" settings: misaligned text

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#13653]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Assume that all persons are managed via yaml.
Then the Settings -> People shows this:
![image](https://user-images.githubusercontent.com/71872483/188999318-ea8d2c25-6436-4496-9f5e-df1b1db46a01.png)

Note that the "Looks like you..." is vertically misaligned respectively to the "Create person" button.
Propose to align them vertically centered.

### Describe the behavior you expected

Text is aligned.

### Steps to reproduce the issue

1. Have all persons created via yaml.
2. Go to Settings -> People.

### What version of Home Assistant Core has the issue?

2022.9.0

### In which browser are you experiencing the issue with?

Chrome 105.0.5195.102

**Comment by piitaya** [comment]
@matthiasdebaat It can be good to improve this empty state with image 🙂

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
Up
