### ISSUE TITLE
Automations save despite closing the save modal to cancel saving

### ISSUE THREAD

**Issue by TimeBomb** [home-assistant/frontend#13666]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating a new automation (via duplicating an existing automation or creating a new empty one), when attempting to cancel saving that automation by clicking the "X" in the save modal, the automation is instead created.

### Describe the behavior you expected

Upon clicking the "Save" button and then clicking the "X" in the save automation modal that appears, I expect the automation to not be saved and instead keep me on the unsaved automation creation form.

### Steps to reproduce the issue

1. Go to existing automation
2. Duplicate it
3. Click Save button
4. Click top right "X" in the save modal that appears
5. Notice that automation is now saved and appears in the main automations list
...

### What version of Home Assistant Core has the issue?

2022.9.0

### What was the last working version of Home Assistant Core?

2022.8.7

### In which browser are you experiencing the issue with?

Chrome 105.0.5195.102

### Which operating system are you using to run this browser?

Windows 11

**Comment by TimeBomb** [comment]
I can confirm this still happens.

**Comment by karwosts** [comment]
Still an issue.
