### ISSUE TITLE
New scripts are called 'New Script' regardless how I name them (v2022.9.0)

### ISSUE THREAD

**Issue by tozzke** [home-assistant/frontend#13663]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating a new script, I put a name in the 'Name' field but when hitting 'Save', Home Assistant stores it as 'New Script' regardless of the name I entered

### Describe the behavior you expected

The script should be saved with the name I gave it

### Steps to reproduce the issue

1. create new script
2. name script
3. add actions @ sequence
4. save script
...

### What version of Home Assistant Core has the issue?

2022.9.0

### What was the last working version of Home Assistant Core?

2022.8.7

### In which browser are you experiencing the issue with?

Chrome 104.0.5112.102, Firefox 104.0.1 (64-bits)

### Which operating system are you using to run this browser?

Windows 11 Pro

**Comment by mopro1985** [comment]
Same problem in the App.

**Comment by yavinmaster** [comment]
Same issue in 2022.9.1 but this time, I don't see a save button unless I edit in YAML mode.  Doing this allows me to change the script name.  You can't set an icon either.

**Comment by dannycab** [comment]
Same setup; chrome and firefox on Mac OS X; same issue.

**Comment by datebo** [comment]
I am having the exact same issue. Also when creating a script from a blueprint.
