### ISSUE TITLE
Dropdown box does not show entire entity name

### ISSUE THREAD

**Issue by dajomu1** [home-assistant/frontend#13671]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

As you can see in the enclosed image I cannot see the entire name of the entity which makes it hard to choose right the first time. There are more than enough space to widen the dropdown and if the lack of horizontal space should have been an issue the GUI should be accomodated. This is probably one of the most used parts of HA and it should be easy to identify the entities.

![image](https://user-images.githubusercontent.com/98491691/189300434-c988e5b4-262b-46bb-94ad-eddbbc25f535.png)

### Describe the behavior you expected

dropdown box should be wider to see the entire name of entities.

### Steps to reproduce the issue

1. I believe all dropdown boxes suffer the same issue. The image enclosed if from the History and is selfexplanatory
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.9.1

### In which browser are you experiencing the issue with?

All of them

### Which operating system are you using to run this browser?

Win10, Linux

**Comment by ildar170975** [comment]
Similar case - https://github.com/home-assistant/frontend/discussions/13648

**Comment by ildar170975** [comment]
up

**Comment by bergdahl** [comment]
This issue still persists. I was meaning to add an issue but found this.

**Comment by karwosts** [comment]
Linked pull request increase the entity selector width to 400px.

**Comment by itssimon** [comment]
I was also going to add an issue about this. It's really annoying if you have a lot of entities that begin with the same strings, almost impossible to select the one you're after.

**Comment by karwosts** [comment]
This is going to be fixed in 2023.3 - coming tomorrow!

**Comment by ildar170975** [comment]
I wonder why is it closed???
![image](https://github.com/home-assistant/frontend/assets/71872483/d5970e5e-ebd7-4fb6-9cc9-0765d53f93cf)
