### ISSUE TITLE
Inconsistency with scrollbars in popup windows (different and duplicating scrollbars)

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#13676]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The window for adding integrations has two progressbars and the close button (X) on the right; all other windows have the X on the left

### Describe the behavior you expected

One progressbar and the (X) close button on the left

### Steps to reproduce the issue

1. Settings
2. Devices & Services
3. Add integration
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.9.1

### What was the last working version of Home Assistant Core?

Home Assistant 2022.8.0 ?

### In which browser are you experiencing the issue with?

Google Chrome 105.0.5195.102

### Which operating system are you using to run this browser?

Windows 10

### Additional information

![Image](https://user-images.githubusercontent.com/74879713/189397378-14454b77-41b5-47f0-8ebf-83cce721352c.png)

**Comment by ildar170975** [comment]
1. This is a scrollbar, not progressbar. Rename the issue.
2. Chrome, Win10 - see only one scrollbar.

**Comment by WRoss7** [comment]
Home Assistant 2022.9.4


![Image](https://user-images.githubusercontent.com/74879713/190200418-10066e43-d771-4182-991f-c1d5a0fdad09.png)

**Comment by WRoss7** [comment]
Umh... then the bug is about more info: large screen but X on the left side


![Image2](https://user-images.githubusercontent.com/74879713/190201708-93c32c79-8b6c-47b4-a601-d83beca272c1.png)

**Comment by ildar170975** [comment]
> hen the bug is about more info: large screen but X on the left side

These "X" will be placed on the same side one day, already posted https://github.com/home-assistant/frontend/issues/13691

**Comment by ildar170975** [comment]
Is it windows?
Double scrollbar - do you have some edited Windows settings like "size 125%"? Or similar browser's settings?

**Comment by WRoss7** [comment]
> do you have some edited Windows settings like "size 125%"? Or similar browser's settings?

No, 100% only

**Comment by WRoss7** [comment]
More-info also has the incorrect scrollbar

![more info](https://user-images.githubusercontent.com/74879713/190827649-4856e13e-1c47-4163-b9c9-06db823d79e5.PNG)

**Comment by Misiu** [comment]
same with seach windows (on demo).
steps to reproduce:
1. goto https://demo.home-assistant.io/#/lovelace/0
2. click on search icon (top right):
![image](https://user-images.githubusercontent.com/1741838/192232022-a5897b05-b1d0-4c7f-b628-bd839873e376.png)

WIndows 10, Chrome 105.0.5195.127, Edge 105.0.1343.50, Firefox 105.0.1

**Comment by ildar170975** [comment]
Win + Chrome
2022.9.7

Confirm with "Search":
![image](https://user-images.githubusercontent.com/71872483/192664453-602b6f82-9761-41fa-a942-b757fd012d2d.png)

Not observed with "Add integration":
![image](https://user-images.githubusercontent.com/71872483/192664509-b2761c67-8f22-47bf-a09e-b189e334e29e.png)

Not observed with more-info:
![image](https://user-images.githubusercontent.com/71872483/192664714-fd36b2d9-fe9f-4610-ad9b-cd55a2436398.png)

**Comment by ildar170975** [comment]
I propose to rename the issue to "Inconsistency with scrollbars in popup windows (different scrollbars, duplicating scrollbars)".
A bit longer but covers all cases.

**Comment by WRoss7** [comment]
Update with Home Assistant 2022.10.1

- search window shows only the correct scrollbar
- more info is showing the "old style" scrollbar
- add integration popup is no longer affected by the double scrollbar, but when you scroll down the page, the scrollbar is partially covered (see the screenshot below)

![Img](https://user-images.githubusercontent.com/74879713/194711633-f6fbc53e-35fe-4aa4-a629-174c072ed94c.png)

**Comment by WRoss7** [comment]
In 2022.11.0 things got worse:
in addition to the above, the more info popup opens with the content scrolled down slightly.

![Img1](https://user-images.githubusercontent.com/74879713/199755299-aa04a8b0-aa99-4f5a-9c95-cf4d01778fcc.png)

**Comment by ildar170975** [comment]
@WRoss7 
There is a fresh issue, you may add your observations there:
https://github.com/home-assistant/frontend/issues/15673
