### ISSUE TITLE
Threshold not supporting decimals in the UI

### ISSUE THREAD

**Issue by edwardtfn** [home-assistant/frontend#13677]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the UI (Settings > Devices & Services > Helpers and then open or create a new Threshold helper) is supporting only integers, making this unusable for small numbers:

![image](https://user-images.githubusercontent.com/94725493/189415527-037491b9-25d4-4447-b3dc-455e3c713f12.png)
![image](https://user-images.githubusercontent.com/94725493/189417010-07e9af49-e260-47a3-b854-a9c693c67b2c.png)

### Describe the behavior you expected

I would expect the dialog accepting decimals when the user is typing. It's ok to go on on integers when using the arrows, but when entering in the text field it should accept decimals.

### Steps to reproduce the issue

1. Go to Settings > Devices & Services > Helpers
2. Open or create a new Threshold helper
3. Try to type a non-integer value in any of the numeric fields

![image](https://user-images.githubusercontent.com/94725493/189416407-f1c8ca88-41f0-47b6-ac7f-f4fe96a8b786.png)

### What version of Home Assistant Core has the issue?

Frontend 20220907.0

### What was the last working version of Home Assistant Core?

This issue is prior to this version. I don't know when it started or even if it worked properly before.

### In which browser are you experiencing the issue with?

Microsoft Edge Version 105.0.1343.27 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 (Version 10.0.19042.1889)

### Additional information

Decimals are OK when setting up the threshold thru YAML.

**Comment by eminphi** [comment]
I don't know how to fix it but I think it's because the ha-selector-number field has a step size of `1`.

See https://github.com/home-assistant/frontend/blob/dev/src/components/ha-selector/ha-selector-number.ts

`.step=${this.selector.number.step ?? 1}`

**Comment by eminphi** [comment]
If I am not mistaken, the issue is resolved in the latest core update:

https://github.com/home-assistant/core/pull/78137

**Comment by edwardtfn** [comment]
I can confirm this was fixed. Thanks!!!
