### ISSUE TITLE
Some icons in the logboock are not proportionate to other icons

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#13675]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Some icons in the logboock (e.g., Add-Ons icons) are not proportionate to other icons

### Describe the behavior you expected

All icons should be the same size

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.9.1

### What was the last working version of Home Assistant Core?

Home Assistant 2022.9.1

### In which browser are you experiencing the issue with?

Google Chrome 105.0.5195.102

### Which operating system are you using to run this browser?

Windows 10

### Additional information

 
![Image](https://user-images.githubusercontent.com/74879713/189396964-89741264-07cb-459f-b4fd-4a5b65bd98c8.png)

**Comment by ildar170975** [comment]
Some rows have icons, some have "images" - see here for "Home Assistant Supervisor".

**Comment by WRoss7** [comment]
Not the best graphically, but I can accept it

**Comment by WRoss7** [comment]
You are right, many icons are tiny compared to the area.

**Comment by WRoss7** [comment]
If I understand correctly, the problem lies in the fact that the image is round while the icon is square: if you superimpose the square icon on the round image (the ones in the Logbook), will the icon overflow the circumference of the image?
