### ISSUE TITLE
Automation editor renders [object Object] instead of time helper name

### ISSUE THREAD

**Issue by thedanbob** [home-assistant/frontend#13680]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the new automation editor (very nice by the way) when you have a Time trigger set to the value of a time helper, the panel is titled "When the time is equal to [object Object]".

### Describe the behavior you expected

The panel should be titled something like "When the time is equal to Time Helper Name".

### Steps to reproduce the issue

1. Create / edit an automation
2. Add a Time trigger
3. Select "Value of a date/time helper"
4. Select a time helper entity

### What version of Home Assistant Core has the issue?

2022.9.1

### In which browser are you experiencing the issue with?

Multiple

### Which operating system are you using to run this browser?

Multiple

**Comment by supermarkert** [comment]
I'm also seeing this in Home Assistant 2022.9.4
