### ISSUE TITLE
Home Assistant Cloud - documentation

### ISSUE THREAD

**Issue by hklages** [home-assistant/frontend#13688]
### Feedback

It would be nice to have on the Home Assistant cloud page `http://<ha>/config/cloud/account` on every card a link to the according documentation topic. There is already a link "learn how it works" for the "remote control card" but it is missing for google `https://www.nabucasa.com/config/google_assistant/` and alexa card `https://www.nabucasa.com/config/amazon_alexa/`.

### URL

https://www.home-assistant.io/integrations/google_assistant/

### Version

2022.9.1

**Comment by balloob** [comment]
This is a good idea. @piitaya could you do this?

**Comment by piitaya** [comment]
Yep! Good idea! 👍

**Comment by piitaya** [comment]
![image](https://user-images.githubusercontent.com/5878303/189596965-1982ec1f-ba23-4c0c-b7aa-c0f3073d88f8.png)

There is already 2 actions in the footer for Alexa and Google. I will look to move the sync action inside the card so we can add learn action like the remote control.

![image](https://user-images.githubusercontent.com/5878303/189596941-1f236af6-8937-49a0-8bfa-8103b51877ae.png)
