### ISSUE TITLE
Camera entity going off screen on desktop

### ISSUE THREAD

**Issue by zagi988** [home-assistant/frontend#13682]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When opening camera entity the image that gets loaded goes off screen (needs to be scrolled).
Even tho the image is 1024x768, it goes off screen even on 1080p monitor. It never happened before, it was always in margins of screen. Since 2022.9.0 it goes off screen.

![image](https://user-images.githubusercontent.com/24916202/189489990-00e96563-d4e3-4f51-8adc-3abbc59f33ab.png)

### Describe the behavior you expected

Camera entity to load inside of screen, without needing to scroll it.

### Steps to reproduce the issue

1. Create camera entity.
2. Open camera entity on desktop.

### What version of Home Assistant Core has the issue?

2022.9 >

### What was the last working version of Home Assistant Core?

2022.8.7

### In which browser are you experiencing the issue with?

Google Chrome 105.0.5195.102

### Which operating system are you using to run this browser?

Win 10 64bit

**Comment by Herbs851** [comment]
The same here.

**Comment by zagi988** [comment]
Any update on this? It has made most of cameras and picture entities unusable.

**Comment by zagi988** [comment]
New version out... still no fix?

**Comment by xbmcnut** [comment]
Same here. No issue on 2022.8.6

**Comment by zagi988** [comment]
OK, will this be fixed? This is not a small problem and it's annoying as hell.

**Comment by zagi988** [comment]
@balloob are you all even aware of this?

**Comment by balloob** [comment]
Please stop spamming this issue or developers. Respect us please.
