### ISSUE TITLE
Map card shows blank if either panel is true or if in a vertical-stack 

### ISSUE THREAD

**Issue by darrynlowe** [home-assistant/frontend#13681]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The map card sometimes shows as empty, with just the "crosshairs" icon visible and the rest blank. 
See the picture below.

![image](https://user-images.githubusercontent.com/52084403/189456915-62964d5d-5b3d-47fa-88a4-698569b4decf.png)

### Describe the behavior you expected

Map card should show correctly.

### Steps to reproduce the issue

The extract below causes the map card to show blank. It can be made to work if: (a) `panel` is set to `false`; OR (b) the `vertical-stack` is removed; OR (c) I enter the "Edit Raw YAML" and exit back to the dashboard; OR (d) I change the YAML and use the 'soft refresh' that appears in the bottom left to reload the page. 

Note that (c) and (d) here are only temporary, and a hard "F5" refresh causes the card to disappear again -- only (a) and (b) above are permanent fixes (albeit insufficient ones, given I need the card to appear in a panel and in a vertical stack).

```
views:
  - title: Home
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: map
            entities:
              - entity: device_tracker.blue_jay_location_tracker
```

### What version of Home Assistant Core has the issue?

2022.9.1

### In which browser are you experiencing the issue with?

Google Chrome 104.0.5112.102 (Windows) + other browsers on Linux and Raspbian)

### Which operating system are you using to run this browser?

Windows (plus Linux and Raspbian)

### Javascript errors shown in your browser console/inspector

```txt
None. Here's the console log - nothing shows as awry.

BROWSER_MOD 2.1.3 IS INSTALLED    
card-mod.js:5 CARD-MOD 3.1.5 IS INSTALLED
kiosk-mode.js?hacstag=497319128173:64 ≡ kiosk-mode            ⋮ 
version 1.7.3            
vacuum-card.js:4  VACUUM-CARD  2.6.2
```

**Comment by ildar170975** [comment]
This bug is since 2022.9.0.
Same with horizontal stack + panel=true.

panel:
![изображение](https://user-images.githubusercontent.com/71872483/190174534-4e8407d6-3725-400a-955d-e77d309aa24e.png)

masonry:
![изображение](https://user-images.githubusercontent.com/71872483/190174567-a325254d-387a-477d-8703-3c116d7fe007.png)

**Comment by rwunsch** [comment]
I have the same problem with the map-card in vertical-and-horizontal stack in a panel.
Sometimes (rarely) the map loads, more often than not, it does not.

![image](https://user-images.githubusercontent.com/662448/191136095-bc36fec3-f47b-4711-8ca5-bb7530ddd335.png)

could this have something to do with this?

![image](https://user-images.githubusercontent.com/662448/191136260-5cbd50f1-db13-404a-9295-25e8701c444c.png)

**Comment by jweston2112** [comment]
<html>
<body>


:raising_hand_man:&nbsp;Me Too!
--



</body>
</html>

**Comment by bakerkj** [comment]
Same problem here.
