### ISSUE TITLE
Drop down entity selector in automation editor chooses wrong entity with duplicate names in different domains.

### ISSUE THREAD

**Issue by janegilv** [home-assistant/frontend#13692]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have similarly named entity_id in different domains created by the unifi-integration.
These are the names:
- switch.client1
- device_tracker.client1

I have created an automation which triggers on the device_tracker.client1 entity attributes. When I reopen this automation in the GUI editor and click entity selector the wrong entity is selected (switch.client1). This breaks the automation if it is then saved as it uses the wrong entity.

### Describe the behavior you expected

The entity selector should select the correct entity_id when editing an existing automation.

### Steps to reproduce the issue

1. Create two entities in different domains with similar/equal names. e.g. status.client1 and device_tracker.client1
2. Create an automation which triggers on one of the entities. (in my case device_tracker)
3. Save and close the automation. 
4. Reopen the automation editor for the automation
5. Open the entity selector in the trigger. The wrong entity is now selected.

### What version of Home Assistant Core has the issue?

Home Assistant 2022.9.2

### In which browser are you experiencing the issue with?

Version 104.0.5112.101 (Official Build) (x86_64)

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
> When I reopen this automation in the GUI editor and click entity selector the wrong entity is selected (switch.client1)

What see now - none of entities is selected in the list, impossible to find out which entity was selected (unless you go to yaml mode):

1. Create a new automation, select some entity:

![image](https://github.com/home-assistant/frontend/assets/71872483/34359356-a8c0-4d02-b08c-b0fa92b2355d)


2. Save the automation.

![image](https://github.com/home-assistant/frontend/assets/71872483/f00cd41b-68c9-4d23-a11e-19800f16ec96)


3. See what entity was selected - hmmm, where is it???

![image](https://github.com/home-assistant/frontend/assets/71872483/5e831fbe-6e68-4ad7-aacf-44737a17bb30)


4. Scroll down to "iPhone ****" entities - our entity is not selected:

![image](https://github.com/home-assistant/frontend/assets/71872483/aec0a0d6-46c6-4410-b6a3-9e4fc012543e)

5. The only way to know is in YAML mode:

![image](https://github.com/home-assistant/frontend/assets/71872483/34fbcdcf-757f-4349-8d9c-25a6dcc58329)

**Comment by ildar170975** [comment]
Seems to be a common problem: https://github.com/home-assistant/frontend/issues/16179

**Comment by karwosts** [comment]
> What I see now - none of entities is selected in the list, impossible to find out which entity was selected (unless you go to yaml mode):


I just opened an issue #17395 for the "no entity selected" problem. I think that's probably unrelated to this aliasing issue between two entities (which yes has existed for much longer).

**Comment by ildar170975** [comment]
@karwosts 
Since this issue seems to be only one left opened, I will leave here a link to a probably related issue:
https://github.com/home-assistant/frontend/issues/17473
Fill free to close it to have everything in THIS issue as related to the problem.

**Comment by ildar170975** [comment]
For the record:
in 2023.11.2 the previously selected entity is not selected after reopening a list.
https://github.com/home-assistant/frontend/issues/17395
