### ISSUE TITLE
Opposing Close icons on dialogs

### ISSUE THREAD

**Issue by hankanman** [home-assistant/frontend#13691]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The 'X' to close a dialog is on the left in one dialog, and the right in another. Clunky and confusing for the user.

Example here is a helper config dialog with it's options open

![image](https://user-images.githubusercontent.com/3953290/189595390-185372af-899a-4e93-a62c-9437abc050e0.png)

### Describe the behavior you expected

All Close crosses to be on the same side (preferably right)

Additionally, ability to click in the "Empty space" around a dialog to dismiss it (making no changes to any settings in the dialog)

### Steps to reproduce the issue

1. Create a min/max helper
2. edit helper
3. click "min/max options

### What version of Home Assistant Core has the issue?

2022.9.2

**Comment by matthiasdebaat** [comment]
I've created a number of issues to improve our dialogs: https://github.com/home-assistant/frontend/issues?q=is%3Aissue+is%3Aopen+dialogs+label%3Aux

We're using Material Design 3 for our dialogs. On mobile the `X` icon should be on the top left, on larger screens on the top right. Our dialogs guidelines can be found here https://design.home-assistant.io/#components/dialogs
