### ISSUE TITLE
Cannot Change Unit of Measure on Entities

### ISSUE THREAD

**Issue by cptskippy** [home-assistant/frontend#13709]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I noticed that since updating the v2022.9.2, I am unable to change the Unit of Measure on any entity.  I've tried from both the Dashboards and Settings menus in the Android App, Firefox, and Edge.  When you hit the Update button on the Settings Tab of the Entity the Window closes but the changes are lost.  The UoM doesn't update and upon re-opening the settings the change is reverted.

### Describe the behavior you expected

I expect when the Unit of Measure is changed and the Entity updated, that the change persists.

### Steps to reproduce the issue

1. Navigate to an Entity from the Settings Menu
2. Change the Unit of Measure
3. Click the Update button
4. Reopen the Settings Menu
5. Observe that the change was not saved
...

### What version of Home Assistant Core has the issue?

2022.9.2

### In which browser are you experiencing the issue with?

Android App, Firefox, Edge

### Which operating system are you using to run this browser?

Android 11, Windows 10

### State of relevant entities

```txt
State: 1013.3

State Attributes:

state_class: measurement
unit_of_measurement: hPa
device_class: pressure
friendly_name: Weather Station 1 Pressure
```

**Comment by emontnemery** [comment]
Sorry about that @cptskippy, fixed by the linked PR.
