### ISSUE TITLE
Home assistant automatically capitalising known list of states in if statement, causing if statement to be false

### ISSUE THREAD

**Issue by Jordenjj** [home-assistant/frontend#13715]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

As shown below, when using the new (super handy) dropdown menu of known states, the states seem to be autocapitalized:
<img width="981" alt="Screenshot 2022-09-13 at 11 47 26" src="https://user-images.githubusercontent.com/14220294/189870611-047ed8be-4ae0-4228-91a5-e37f57b705b5.png">

While the actual states are not:
<img width="637" alt="Screenshot 2022-09-13 at 11 46 43" src="https://user-images.githubusercontent.com/14220294/189870684-141445b9-aa28-409c-8e72-87c362e0b093.png">

Resulting in false if statements, that are expected to be true:
<img width="292" alt="Screenshot 2022-09-13 at 11 48 42" src="https://user-images.githubusercontent.com/14220294/189870732-b4b653ae-4696-41d1-b427-72db6abcb5d9.png">

### Describe the behavior you expected

Drop down menu of expected states, should be true to the capitalisation of the actual states.

### Steps to reproduce the issue

1. Create automation using if statement
2. Use auto dropdown to select a state
3. Check if condition becomes true whether the if statement thinks the same

### What version of Home Assistant Core has the issue?

core-2022.9.2

### State of relevant entities

```txt
At least person home/not_home state, expectedly much more.
```

**Comment by ildar170975** [comment]
You are wrong.
Displayed names differ from actual names.
May depend on a `device_class` too.

Examples:
1. Internally `binary_sensor`, `input_boolean`, `switch` entity have states `on` / `off` - but in UI you see `On` / `Off`.
2. `unavailable` -> `Unavailable`.
3. `off` -> `Disconnected`.
4. `not_home` -> `Away`.

**Comment by Jordenjj** [comment]
> You are wrong. Displayed names differ from actual names. May depend on a `device_class` too.
> 
> Examples:
> 
> 1. Internally `binary_sensor`, `input_boolean`, `switch` entity have states `on` / `off` - but in UI you see `On` / `Off`.
> 2. `unavailable` -> `Unavailable`.
> 3. `off` -> `Disconnected`.
> 4. `not_home` -> `Away`.

I fail to understand why I'm wrong, suggested states without caps will always be better since it can't get the wrong comparison don't you think?

**Comment by ildar170975** [comment]
I do not see a wrong comparison.
Assume there is a `device_tracker.maria` entity which may be internally "home", "not_home".
Then your templates in automations may be:
```
{% if is_state('device_tracker.maria','home') %}
{{ ...}}
{% elif is_state('device_tracker.maria','not_home') %}
{{ ...}}
{% endif %}
```
and you will see in UI values like "Home" & "Away".

**Comment by Jordenjj** [comment]
> > I do not see a wrong comparison. Assume there is a `device_tracker.maria` entity which may be internally "home", "not_home". Then your templates in automations may be:
> > ```
> > {% if is_state('device_tracker.maria','home') %}
> > {{ ...}}
> > {% elif is_state('device_tracker.maria','not_home') %}
> > {{ ...}}
> > {% endif %}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and you will see in UI values like "Home" & "Away".
> 
> I think you're talking about different things. Check the trace screenshot above, it throws false when it should be true when the UI text is used.

Im not talking about the UI displaying it, im talking about the UI profiling it in automations causing the automation not to wok as expected.

**Comment by Jordenjj** [comment]
> The dropdown list contains possible states for `device_tracker` - which are "UI versions" of "real internal values".

_I get that... Again, different thing._

The problem is that it fills the backend with the caps as well which doesn't work.

**Comment by ildar170975** [comment]
> The problem is that it fills the backend with the caps as well which doesn't work.

What do you mean by "fills the backend"?

**Comment by Jordenjj** [comment]
The point is, using the drop down menu doesn't work, since it will put "Home" in the yaml, and the if statement will not work since it will say expected: home, got: Home as seen in the trace above.

**Comment by ildar170975** [comment]
This is very strange.

Create a new automation:
trigger: if `device_tracker` changes from Home to Away -> notify.

![image](https://user-images.githubusercontent.com/71872483/190266413-00754d84-511e-4370-a165-14d294c5f9b0.png)

Go to Yaml mode - it creates a correct code:
```
description: ""
trigger:
  - platform: state
    entity_id:
      - device_tracker.vmmac
    from: home
    to: not_home
condition: []
action:
  - service: notify.persistent_notification
    data:
      message: mac is away
mode: single
```
And this automation works.

**Comment by confuserated** [comment]
I found that it was card-mod causing the problems for me, removing card-mod made everything work as expected.

**Comment by ildar170975** [comment]
Magic, how card-mod could auto-capitalize letters ))))))))))))

**Comment by confuserated** [comment]
Absolutely, but that’s what I have observed. No changes were made except to remove card-mod, but the problem is now resolved for me. I’ve opened an issue for card-mod but I don’t hold out much hope for it to even be looked at as the list of issues is quite long for it.

**Comment by ildar170975** [comment]
If you install card-mod - will the issue return?
Could you test it?)

**Comment by confuserated** [comment]
I’ll give it a go

**Comment by confuserated** [comment]
I gave it a go and saw the following:

After uninstalling card-mod the problem immediately went away and now when I alter or create an automation with the same entities and attributes it works ok.

I re-installed card-mod and the problem did not come back...

I've tried adding new automations with the same entities and attributes too monitor and everything works as expected.

I can't understand why this would be as nothing else has changed.

I'm at a loss to explain what is happening here, but, I do have a backup I could use to test when I was getting the problem and could go through this process again but is it worthwhile?

**Comment by BillyFKidney** [comment]
I am experiencing this same issue, it took me a while to debug:

Manually written YAML snippet:
```
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.eagle_200_meter_power_demand
            state: unavailable
        alias: Current Power Demand Available?
```
<img width="1057" alt="image" src="https://github.com/home-assistant/frontend/assets/65253277/14b85abc-99fd-4e0b-9a0b-edab65917db5">

Convert to visual editor:
<img width="1007" alt="image" src="https://github.com/home-assistant/frontend/assets/65253277/47a027cf-a89a-4818-9943-fce0e16453b6">

Click dropdown, text is capitalized, select value (DO NOT SAVE):
<img width="1271" alt="image" src="https://github.com/home-assistant/frontend/assets/65253277/0c45f1dd-8bbc-4171-b178-39e698dabe90">

When the entity is unavailable while creating the automation it would save it "Unavailable"
