### ISSUE TITLE
In automations losing edits if you hit traces after you've forced a run

### ISSUE THREAD

**Issue by Jeffreyjelly** [home-assistant/frontend#13714]
### The problem

The issue seems to be after making multiple edits in the latest automation editor and you hit the three buttons in the top right to run the automation and swiftly hit "traces" just to the left of that you'll lose all the changes you just added since you've last saved.

### What version of Home Assistant Core has the issue?

2022.9.1

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Automation

### Link to integration documentation on our website

https://www.home-assistant.io/docs/automation/

### Diagnostics information

N/A ? not sure 

### Example YAML snippet

```yaml
N/A
```

### Anything in the logs that might be useful for us?

```txt
no errors reported, just data lost.
```

### Additional information

Not sure if OS is the right type of install for the one I have on my raspberry pi.

**Comment by frenck** [comment]
Transferring this issue to the frontend repository as it is not a core issue.
