### ISSUE TITLE
Unable to change a numeric helper to set without an inital value

### ISSUE THREAD

**Issue by lenwar** [home-assistant/frontend#13711]
### The problem

I am defining a number of numeric helpers (input_number) via the web interface. I first created them with an initial value. I  however want them to be persistent over reboots so I tried to remove the initial value. The interface however doesn't allow me to do so. I have to fill something in and it always defaults to 0 (zero).

As a workaround I am currently deleting and recreating the numeric helpers without an initial value. (the GUI still shows 0 in the fields, but it gets a 'null' value in reality)

### What version of Home Assistant Core has the issue?

core-2022.9.2

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

input_numer or frontend (not sure if it's only the GUI that prevents me)

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/input_number/

### Diagnostics information

N/A

### Example YAML snippet

```yaml
N/A
```

### Anything in the logs that might be useful for us?

```txt
N/A
```

### Additional information

I can't say if this issue exists in the input_numer or frontend integration. (maybe it's just the GUI that doesn't allow me to change it?)

**Comment by emontnemery** [comment]
Fixed by https://github.com/home-assistant/frontend/pull/13713
