### ISSUE TITLE
Editing Statistics Graph Card Configuration via code editor automatically removes code

### ISSUE THREAD

**Issue by emwolf1** [home-assistant/frontend#13727]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Attempting to edit via the code editor but the code gets checked on keystroke and modified immediately. Entering any character under the entities indentation removes the entire entity. Mistyping anywhere generates notifications such as 
_"Visual editor is not supported for this configuration:
Key 'amchart_type' is not expected or not supported by the visual editor.
You can still edit your config in YAML."_ 
This is within the code editor, not via the visual editor.
![codeedit1](https://user-images.githubusercontent.com/39592650/190025357-2b5e7f55-7693-4f16-8c89-cae4b5a68a5d.jpg)
![codeedit1](https://user-images.githubusercontent.com/39592650/190025380-cc1dcab1-2f10-43f9-a07c-53645984e594.jpg)
![codeedit2](https://user-images.githubusercontent.com/39592650/190025384-d2688b01-f008-4749-9781-24b4647bf0e4.jpg)
![codeedit3](https://user-images.githubusercontent.com/39592650/190025385-feea5ccf-c8f3-44d6-8463-6f903049310e.jpg)

### Describe the behavior you expected

Allow editing and not modify code unless requested by user.

### Steps to reproduce the issue

1. enter Statistics Graph Card Configuration
2. select show code editor
3. create new line under first entity under -entities:
4.  start typing - enter multiple spaces to reach indentation
5.  type any alphanumeric key
6.  the previous entity will be removed and cursor will move to the top left
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.9.2

### In which browser are you experiencing the issue with?

google chrome Version 105.0.5195.102 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 Home 21H2

### Problem-relevant frontend configuration

```yaml
chart_type: line
period: hour
days_to_show: 30
type: statistics-graph
entities:
  - sensor.power_usage_801054
  - sensor.power_usage_687593
stat_types:
  - mean
title: Power usage
```

**Comment by ildar170975** [comment]
Confirm the issue.
Also, sometimes while typing a cursors suddenly jumps to the code's beginning.
