### ISSUE TITLE
Do not re-render the whole page when switching orientation in video full-screen

### ISSUE THREAD

**Issue by felipecrs** [home-assistant/frontend#13726]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When a card enters in full-screen directly from the dashboard, while still in full-screen, switching the orientation of the device causes the whole page to re-render and therefore exits from full-screen.

### Describe the behavior you expected

Ideally, the card should remain in full-screen. Effectively, it would allow me to simply switch my device's orientation and take advantage of the aspect ratio for viewing a camera stream.

### Steps to reproduce the issue

1. This issue can be only triggered with a custom card, like the Frigate Hass Card.
   - Because none of the built-in cards (like Picture Glance) have the ability of going full-screen while still in the dashboard. Picture Glance requires you to open the entity's more info page, which does not trigger this issue.
2. With a custom card like Frigate Hass Card, click in the full-screen button, while still in Portrait orientation.
3. Change the device orientation to Landscape. You'll notice the whole page gets re-rendered, causing the card to exit from full-screen.

### What version of Home Assistant Core has the issue?

It always had.

### What was the last working version of Home Assistant Core?

None.

### In which browser are you experiencing the issue with?

Google Chrome 105

### Which operating system are you using to run this browser?

Android 12

### Additional information

This problem happens when using both Google Chrome and the Android app, so I decided to report it here.

This problem was initially discovered in:

- https://github.com/dermotduffy/frigate-hass-card/issues/590

And after several rounds of research and tries, we found out that something else in the frontend would be preventing the card from achieving this goal.

Demonstration:

https://user-images.githubusercontent.com/29582865/190018741-8f015c67-0b7e-4761-a09d-9e1f2aec8987.mp4

**Comment by felipecrs** [comment]
This is still valid. I can reproduce it.

**Comment by bramkragten** [comment]
The issue is that we need to rebuild the dashboard when the width changes, otherwise we don't show the correct columns. This results in briefly removing and the re-adding the elements. Im not sure if there is an easy way around that.

**Comment by felipecrs** [comment]
Ok, I don't know how it works under the hoods, but if it was possible to NOT re-render the elements if orientation is changed AND some card is currently displaying in full-screen, that would already be enough.

When in full-screen, no other element needs to be rendered anyway.

The part of rebuilding the dashboard could be delayed to when the full-screen closes.

**Comment by thornygravy** [comment]
Have this issue as well. I can confirm when dashboard only has one column, the issue goes away.

**Comment by felipecrs** [comment]
Not stale

**Comment by TheDescender** [comment]
> Ok, I don't know how it works under the hoods, but if it was possible to NOT re-render the elements if orientation is changed AND some card is currently displaying in full-screen, that would already be enough.
> 
> When in full-screen, no other element needs to be rendered anyway (because they are not visible).
> 
> The part of rebuilding the dashboard could be delayed to when the full-screen closes.

This is actually a serious problem when viewing security camera's on the mobile app, and it reduces the user experience.

This would actually be a nice implementation. I don't see any issues with always doing the re-render when exiting a fullscreen card paired with having the ability to disable orientation based re-rendering per dashboard.
