### ISSUE TITLE
ZWave config parameter value not saved in automation when set to zero

### ISSUE THREAD

**Issue by petercogen** [home-assistant/frontend#13729]
### The problem

When using the visual automation editor, selecting the first option "illumination turned off completely" for the ZWave config parameter 41 of a Fibaro plug results in the following, viewed in Yaml

device_id: 123123123123123123123
domain: zwave_js
type: set_config_parameter
parameter: 41
bitmask: null
subtype: 41 (LED ring colour (device is ON))

The editor should have generated an additional line stating

value: 0

A workaround is of course to add this line manually using Yaml but it took me quite some time to figure out why I could select any option from the visual editor, except for the first.

I don't know if this issue predates Core 9.2 as I didn't use the ZWave config parameter until recently.

### What version of Home Assistant Core has the issue?

2022-9-2

### What type of installation are you running?

Home Assistant Core

### Integration causing the issue

Z-wave JS

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/zwave_js/

**Comment by raman325** [comment]
just to add here, this is a device action that supports action capabilities (e.g. addition of new fields). Those fields don't handle 0 properly
