### ISSUE TITLE
Home Assistant 2022.9.3 update breaks Settings-System page

### ISSUE THREAD

**Issue by ioctl2** [home-assistant/frontend#13728]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After upgrading Home Assistant running on HAOS to 2022.9.3, clicking on Settings then System results in a blank page.
Versions:  Home Assistant 2022.9.3 Supervisor 2022.08.6 Operating System 8.5 Frontend 20220907.1 - latest 
Environment: ova
Clearing browser cache did not help.

### Describe the behavior you expected

Was expecting to see the System UI elements.

### Steps to reproduce the issue

1. Update to Home Assistant 2022.9.3
2. Go to Settings -> System

### What version of Home Assistant Core has the issue?

2022.9.3

### In which browser are you experiencing the issue with?

Firefox 91.13.0esr 

### Which operating system are you using to run this browser?

Windows 10

**Comment by Fenceeater** [comment]
I am having same problem

**Comment by pbranly** [comment]
Same issue here

**Comment by cllatser** [comment]
Same issue here.

**Comment by Claudio1L** [comment]
same here

**Comment by frenck** [comment]
## 🤚 I have the same issue! 👇 Read below

Hi there! Sorry to read you are experiencing the same issue as more people here. Nobody likes having issues 😞

Finding an issue on a GitHub issue tracker that matches your problem is kinda nice: At least you know you are not alone. So, let's leave a commit with: "Yeah, I have the same issue", or "+1!!!". 🚫 **No!**

### Please do not create "I have the same issue" comments!

Not just this issue or this project, but anywhere on GitHub or any issue tracker on the internet even. It doesn't add to triaging the issue. It only generates noise when reading / triaging the case. 

### What to do instead?

Instead, go to the top of the issue, and add a 👍 emoji reaction. That way, we can still see that you (and how many others) experience this issue while keeping the issue threads nice and clean.

Thanks! ❤️

../Frenck

**Comment by NikosSprocket** [comment]
Tested also not working with:
Windows 11 Home version 21H2 built 22000.856
Edge Version 105.0.1343.33 (Official build) (64-bit)

**Comment by zhuykovkb** [comment]
same here

**Comment by Sangoku** [comment]
This is the console output from chrome when you try to go to the page
`typography.js:181 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'language')
    at i (typography.js:181:1)
    at r.value (ha-state-icon.ts:20:1)
    at r.performUpdate (styles.ts:370:1)
    at r.scheduleUpdate (styles.ts:370:1)
    at r._$EC (styles.ts:370:1)
i @ typography.js:181
value @ ha-state-icon.ts:20
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
o @ styles.ts:370
b @ styles.ts:370
w @ styles.ts:370
r @ ha-state-icon.ts:20
E @ typography.js:181
t @ typography.js:181
p @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
S @ styles.ts:370
update @ styles.ts:370
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
o @ styles.ts:370
b @ styles.ts:370
w @ styles.ts:370
r @ ha-list-item.ts:7
E @ typography.js:181
t @ typography.js:181
window.CustomElementRegistry.define @ typography.js:181
finisher @ styles.ts:370
runClassFinishers @ ha-list-item.ts:7
(anonymous) @ ha-list-item.ts:7
(anonymous) @ ha-list-item.ts:7
u.a @ styles.ts:370
99417 @ ha-list-item.ts:7
u @ styles.ts:370
Promise.then (async)
load @ 312c80d9.js:1
value @ hass-loading-screen.ts:11
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
set @ styles.ts:370
value @ app-drawer-layout.js:189
value @ hass-loading-screen.ts:11
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
set @ styles.ts:370
k @ styles.ts:370
_$AI @ styles.ts:370
m @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
S @ styles.ts:370
update @ styles.ts:370
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
set @ styles.ts:370
k @ styles.ts:370
_$AI @ styles.ts:370
m @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
S @ styles.ts:370
update @ styles.ts:370
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
set @ styles.ts:370
t @ home-assistant.ts:32
(anonymous) @ home-assistant.ts:32
i @ typography.js:181
s @ typography.js:181
value @ ha-navigation-list.ts:50
handleEvent @ styles.ts:370
notifyAction @ mwc-list-base.ts:270
setSelectedIndexOnAction_ @ eb39b60a.js:2
handleSingleSelection @ eb39b60a.js:2
onRequestSelected @ mwc-list-base.ts:270
handleEvent @ styles.ts:370
fireRequestSelected @ mwc-list-item-base.ts:224
onClick @ mwc-list-item-base.ts:224
cb @ 25f1190c.js:2
ha-config-system-navigation.ts:140 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at HTMLElement.value (ha-config-system-navigation.ts:140:1)`

**Comment by StayPirate** [comment]
The following are the logs I got from the container during its first run after the broken update. I'm not sure that could help.

```
> docker container logs -f homeassistant
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun home-assistant (no readiness notification)
s6-rc: info: service legacy-services successfully started
2022-09-14 09:15:43.248 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration miele which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-09-14 09:15:43.252 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-09-14 09:15:43.255 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-09-14 09:15:55.539 ERROR (MainThread) [aiohttp.server] Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1191, in _sendfile_fallback
    read = await self.run_in_executor(None, file.readinto, view)
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 514, in start
    resp, reset = await task
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 460, in _handle_request                                                                  reset = await self.finish_response(request, resp, start_time)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 613, in finish_response                                                                  await prepare_meth(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_fileresponse.py", line 286, in prepare
    return await self._sendfile(request, fobj, offset, count)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_fileresponse.py", line 99, in _sendfile
    await loop.sendfile(transport, fobj, offset, count)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1170, in sendfile
    return await self._sendfile_fallback(transport, file,
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1200, in _sendfile_fallback
    await proto.restore()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 268, in restore
    self._transport.resume_reading()
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 343, in resume_reading
    self._ssl_protocol._transport.resume_reading()
AttributeError: 'NoneType' object has no attribute 'resume_reading'
2022-09-14 09:19:13.663 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: miele, mqtt, radio_browser
2022-09-14 09:20:29.747 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: alexa_media
```

the container image is `ghcr.io/home-assistant/qemux86-64-homeassistant:2022.9.3`

**Comment by Steephsel** [comment]
Curious how HA wants us to update the bugfix with no System page...

**Comment by zzaal** [comment]
a have some problem too(
backup to 2022.9.2
work perfectly!

**Comment by gopheridze** [comment]
> Curious how HA wants us to install the bugfix with no System page...

Terminal/ssh
`ha core update`

or downgrade to 2022.9.2
`ha core update --version 2022.9.2`

**Comment by OmegaX-NL** [comment]
Went back to 2022.9.2 with "ha core update --version 2022.9.2" but in this version the Settings-System page is also gone

**Comment by zzaal** [comment]
you must restore backup from SSH

**Comment by Pliggen** [comment]
How do I fix this? I did a backup when updating but how do I revert to this backup without  getting into systempage? How do I restore from SSH?

**Comment by OmegaX-NL** [comment]
I did this via the add-on "Terminal & SSH". And system is back to 2022.9.2 (I've got the message to update to 2022.9.3 again). But the system page is still blank (https://xxxx.duckdns.org:8123/config/system)

**Comment by zzaal** [comment]
> How do I fix this? I did a backup when updating but how do I revert to this backup without getting into systempage? How do I restore from SSH?

terminal/ssh

`ha sn list`
find youre "slug"
`ha backup restore <slug> --homeassistant`

**Comment by JokeRsevilla** [comment]
> Hice esto a través del complemento "Terminal y SSH". Y el sistema volvió a 2022.9.2 (recibí el mensaje para actualizar a 2022.9.3 nuevamente). Pero la página del sistema aún está en blanco ( https://xxxx.duckdns.org:8123/config/system )

clear cache with ctrl+F5

**Comment by d3sp3rados13** [comment]
What will be the solution if there is no previous backup? Will there be a future update soon?

**Comment by daballiemo** [comment]
I am running Home Assistant container. After updating my settings-system page was also empty. Starting my docker container with label 2022.9.2 brought the settings-system page back.

**Comment by oopiicaa** [comment]
> How do I fix this? I did a backup when updating but how do I revert to this backup without getting into systempage? How do I restore from SSH?

Press 'c' on frontend > the command pop-up shows up > type 'backups' and click on it.

![image](https://user-images.githubusercontent.com/24246157/190105578-5486d82d-5392-498b-81bc-a0239b2fc790.png)

**Comment by piitaya** [comment]
Incoming 2022.9.4 will fix the issue

**Comment by Ra7t0r** [comment]
Hello. General question here. 
I have the same issue, on MAC OS 
Although I see that both **frontend: 20220907.2**  and  **core: 2022.9.4** has already been released, when I check for an update via HA, there are no update available at this time.
How much time does it needed in order for HA to fetch the new content available for download?

**Comment by Z0472** [comment]
HA core to 2022.9.4 version is not available after checking the available updates.

**Comment by BebeMischa** [comment]
Fix confirmation, installed 2022.9.4 now, problem gone.

**Comment by mugnor** [comment]
> Confirmación de corrección, instalado 2022.9.4 ahora, problema desaparecido.
Hello, how do I install version 20229.4 without having access to system page?

**Comment by Z0472** [comment]
> > Confirmación de corrección, instalado 2022.9.4 ahora, problema desaparecido.
> > Hello, how do I install version 20229.4 without having access to system page?

Settings > three dots menu in the right up corner next to find.

**Comment by danwooller** [comment]
Trying to update to 2022.9.4, the install hangs and the VirtualBox VM dies. I haven't been able to find anything in the logs
