### ISSUE TITLE
The page Setting/System doesn't load after 2022.9.3 update

### ISSUE THREAD

**Issue by mcanteri** [home-assistant/frontend#13745]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After the last update to 2022.9.3 the page Setting/System is empty with Chrome, Edge and with the app on various devices.
I see these errors inspecting the page:
![image](https://user-images.githubusercontent.com/52449704/190131728-868b4ca3-d1ab-4a64-bba7-983541ed4fad.png)

### Describe the behavior you expected

The page to visualize the content.

### Steps to reproduce the issue

1. update HA to the last version
2. refresh the frontend page
3. delete all data related to the site

### What version of Home Assistant Core has the issue?

2022.9.3

### What was the last working version of Home Assistant Core?

2022.9.2

### In which browser are you experiencing the issue with?

Google Chrome Version 105.0.5195.102 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 Enterprise

### Javascript errors shown in your browser console/inspector

```txt
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'language')
    at i (typography.js:181:1)
    at r.value (ha-state-icon.ts:20:1)
    at r.performUpdate (styles.ts:370:1)
    at r.scheduleUpdate (styles.ts:370:1)
    at r._$EC (styles.ts:370:1)
ha-config-system-navigation.ts:140 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at HTMLElement.value (ha-config-system-navigation.ts:140:1)
```

**Comment by ludeeus** [comment]
Update to 2022.9.4
