### ISSUE TITLE
Apple Watch iOS 9 Complications not available

### ISSUE THREAD

**Issue by tux43** [home-assistant/frontend#13756]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi,
I’ve just updated to Apple Watch iOS 9 and my Complications have stopped working as per image below. Do I need to do anything to get them going again?

file:///home/bhales/Downloads/watch.png

### Describe the behavior you expected

I would expect the three complications circled to be numbers as per the setup within the Home Assistant app. It did work on iOS 8.

 file:///home/bhales/Downloads/watch.png

### Steps to reproduce the issue

1. Upgraded Apple Watch from iOS 8 to iOS 9
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.9.4

### What was the last working version of Home Assistant Core?

2022.9.4

### In which browser are you experiencing the issue with?

Apple Watch iOS 9

### Which operating system are you using to run this browser?

Apple Watch iOS 9

### State of relevant entities

```txt
Home Assistant Complication formula (works in the app)
```

### Problem-relevant frontend configuration

```yaml
Nil
```

### Javascript errors shown in your browser console/inspector

```txt
Nil
```

### Additional information

Here is a screenshot of the Home Assistant App formula and setup.

![Screenshot 2022-09-15 at 08 11 34](https://user-images.githubusercontent.com/53364421/190275676-b066aaaa-a233-4d23-a16b-534e43bde16f.png)

Through the Apple Watch App on the iPhone I have tried deleting and recreating the Complication. What I have noticed is that the new Complication (screen shot above) is not showing up in the available Complications as per below. I expected to see a 'People' option as per screen capture above.

![Screenshot 2022-09-15 at 08 17 30](https://user-images.githubusercontent.com/53364421/190276626-6ae9c788-0c8b-4a92-b00e-9141bed58780.png)

**Comment by mclssk** [comment]
Any news??? Thanks!

**Comment by Drun555** [comment]
I'm also having this issue. None of my complications appears after upgrade.

**Comment by Drun555** [comment]
Ok. I used an Legacy complications, and they are don't supported by watchOS 9 anymore. You can find the legacy complications list [here](https://developer.apple.com/design/human-interface-guidelines/components/system-experiences/complications/#legacy-templates). It really sucks there's no any note / alert about this by devs - there's definitely should be one.

**Comment by AneticsUK** [comment]
Same issue here, nothing but a "Placeholder" in the list

It's my first apple watch/config so theres definitely no remnants of any old configs interfering, they just don't show up

**Comment by Drun555** [comment]
@AneticsUK look at the link from my comment above. I'm pretty sure you are using legacy complication.

**Comment by AneticsUK** [comment]
> @AneticsUK look at the link from my comment above. I'm pretty sure you are using legacy complication.

Ah, i see, i'l have another play around, i've managed to get a rectangle one to show up, but nothing else
