### ISSUE TITLE
Reloading `/lovelace/default_view` does not work properly on Chrome for Android

### ISSUE THREAD

**Issue by felipecrs** [home-assistant/frontend#13752]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

https://user-images.githubusercontent.com/29582865/190215165-bd8d7ee0-5c64-4d0a-8713-ac4e770ff183.mp4

### Describe the behavior you expected

To properly load my default dashboard, just the way it works when I navigate to `https://my-home-assistant.com/`.

### Steps to reproduce the issue

1. Chrome for Android
2. Enter your HA instance from the homepage, everything works normally
3. Refresh the page. It should enter in the mentioned faulty state.

### What version of Home Assistant Core has the issue?

2022.9.4

### In which browser are you experiencing the issue with?

Google Chrome for Android 105

### Which operating system are you using to run this browser?

Android 12

### Additional information

This issue doesn't trigger in my Windows, but triggers in both my phone and my tablet, where one runs Fully Kiosk and phone in my Chrome browser.

**Comment by dshokouhi** [comment]
Do you have any custom cards on that dashboard?

**Comment by felipecrs** [comment]
I have one switch-state card, which displays an additional button only in my kitchen tablet. I have recently introduced it in my dashboard, but the issue I described was observed since always. Removing it does not help in anything as well:


https://user-images.githubusercontent.com/29582865/191031424-e5fed6b7-1a90-46f6-8a53-98c5d670d152.mp4

**Comment by gydavid** [comment]
I have the same error (desktop chrome, iphone safari, HA app)

JS error in console:
<img width="897" alt="image" src="https://user-images.githubusercontent.com/6553547/195950411-3d8f08df-3e52-4ef9-b3dd-5405fa802f03.png">

<img width="458" alt="image" src="https://user-images.githubusercontent.com/6553547/195950459-1a171f5b-4fd1-4bec-8143-114425ef0768.png">

**Comment by felipecrs** [comment]
I have a tablet in kiosk mode in my kitchen, and I live with my parents already advanced in age, and when this happens they simply can't do anything and they get extremely frustrated (so I do). Sometimes someone is waiting on the outside and they need to open the gate. Reloading the page not always fixes the issue. Actually in the tablet it never fixes the issue. What usually fixes is going to "Map" on the sidebar, then reloading, then going back to Dashboard.

Or if I type in the HA URL by myself, but my parents can't do that because it's in kiosk mode.

**Comment by felipecrs** [comment]
It turns out that this error is not only when loading the `default_view`. It can happen for any view. I was able to capture the browser logs too:

```
hui-root.ts:263 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'id')
    at hui-root.ts:263:1
    at Array.some (<anonymous>)
    at hui-root.ts:263:1
    at Array.map (<anonymous>)
    at x.value (hui-root.ts:259:1)
    at x.update (styles.ts:372:1)
    at x.performUpdate (styles.ts:372:1)
    at x.scheduleUpdate (styles.ts:372:1)
    at x._$EC (styles.ts:372:1)
```

Which is the same as @gydavid had pointed.
