### ISSUE TITLE
Scheduler in Lovelace doesn't keep half hour

### ISSUE THREAD

**Issue by yashijoe** [home-assistant/frontend#13757]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In Lovelace I create a scheduler that start at half a hour.
I save it
I reopen it and it start at o clock

If I check the /config/.storage/schedule everything is ok
So it is just a visualization mistake

### Describe the behavior you expected

I expect Lovelace and /config/.storage/schedule show the same values

### Steps to reproduce the issue

1. In Lovelace create a schedule that starts at 6.30 and end at 00.00
2. save it
3. reopen it
4. the start is now 6.00.
![lovelace](https://user-images.githubusercontent.com/12962680/190330229-f31ebef5-4ab0-4238-aedc-914dec15397a.png)
![schedule](https://user-images.githubusercontent.com/12962680/190330232-a8b2d144-8247-4c2d-bc90-3ccbf828c6ae.png)

### What version of Home Assistant Core has the issue?

2022.9.4

### In which browser are you experiencing the issue with?

Safari 15.6.1 - Chrome 105.0.5195.102

### Which operating system are you using to run this browser?

macOS Monterey 12.0.1 - Windows 11

**Comment by smoki3** [comment]
https://github.com/home-assistant/frontend/issues/13544

**Comment by mvoehringer** [comment]
see #13877

**Comment by amitfin** [comment]
Issue was fixed by https://github.com/home-assistant/frontend/pull/13929.
