### ISSUE TITLE
Testing a template in a condition inside an automation always returns an error

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#13781]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Even the most trivial of templates that in /Developer Tools/Template returns a consistent (true/false) result here gives error

![Template](https://user-images.githubusercontent.com/74879713/190741620-9bd7f3cc-56e7-4fe7-ad5a-7d9dfa13af8c.png)

### Describe the behavior you expected

If it passes in /Developer Tools/Template there is no reason for it not to pass here

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.9.4

### In which browser are you experiencing the issue with?

Google Chrome 105.0.5195.125

### Which operating system are you using to run this browser?

Windows 10

**Comment by frenck** [comment]
Fixed in https://github.com/home-assistant/core/pull/78570

Will be part of 2022.9.5 or 2022.10.0.

../Frenck

**Comment by WRoss7** [comment]
Thank you Frenck for the quick response.
At first glance I hadn't found any other reports of the problem (I'm not an expert here)

**Comment by frenck** [comment]
Don't worry! With the number of issues and PRs going through this project, things are easy to miss 👍
