### ISSUE TITLE
Statistics Graph card: non-existing entities are present in picker (and keep stored in DB)

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#13795]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Add a new Statistics Graph card via UI.

Open a dropdown list to select an entity, scroll it down.
I see lots of non-existing entities:

![image](https://user-images.githubusercontent.com/71872483/190868648-6f288e8d-caae-4e20-854e-3a1d96b78b35.png)

and even can select them.
Mostly these are entities-duplicates (with a "_2" suffix) which were made accidentally or by mistake then removed, then (probably) automatically restored, then removed again from "Settings -> Entities" list.
And seems that these "dead entities" are still available in DB (or somewhere else).

Usually selecting a "dead entity" shows an empty graph around 04:00:
![image](https://user-images.githubusercontent.com/71872483/190868751-72528b29-5e10-4342-a5fd-026405cfc026.png)

And there is one more related issue - **some ALIVE entities cannot be found, the picker gives a DEAD entity instead**:
![Untitled Project](https://user-images.githubusercontent.com/71872483/190869527-4d307e91-87d6-46fb-97f5-d3aa02da5cff.gif)
Assume I need to add a "sensor.iiyama_ohm_ssd_corsair_temperature" (for which there is a removed entity "iiyama_ohm_ssd_corsair_temperature_2"):
1. Start typing "sensor.", then add (from a clipboard) "iiyama_ohm_ssd_corsair_temperature".
2. The removed "sensor.iiyama_ohm_ssd_corsair_temperature_2" is selected.
3. Remove "sensor." part - now both entities are shown.

### Describe the behavior you expected

No removed entities are available in the picker.

### Steps to reproduce the issue

Described above.

### What version of Home Assistant Core has the issue?

2022.9.4

### In which browser are you experiencing the issue with?

Chrome 105.0.5195.127 

### Which operating system are you using to run this browser?

Win10x64

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
Still I see stats for old deleted sensors.
And this data are kept in DB.

For instance, this sensor was added and then was deleted - but it still occupies a space in DB:

![image](https://user-images.githubusercontent.com/71872483/219953522-ed2bb4f4-2dbd-4f1c-9a02-8853e369e1ce.png)

**Comment by ildar170975** [comment]
Still in 2023.3.4

**Comment by karwosts** [comment]
I think if anything this should maybe be reported against core/recorder. 

To get the list of options for the picker, the frontend just calls the core function `recorder/list_statistic_ids`. The core returns a list of ids, and that directly influences what shows up in the dropdown box. 

I don't believe there's enough data in the return from that function to determine if any of those ids are "dead" or "non-existing". We don't actually request the statistic _data_ until after it is picked.

**Comment by karwosts** [comment]
Closing per my previous comment, I believe this is intentional behavior. 

If you want to clean out the old statistics, you can delete them in developer-tools/statistics using the `Fix Issue` flow. Otherwise the LTS are intentionally retained unless user decides to delete them. e.g. perhaps they have old energy data that user wants to keep.

**Comment by ildar170975** [comment]
Cannot reproduce it right now since my DB was damaged after some glitch and re-created. 
Not 100% sure, but I have a habit to check this “Dev tools - Statistics” table; I think I would have noticed a presence of these “dead” entities there. 
Anyway, the issue is not closed in my own registry , I will keep monitoring and will reopen the issue here if it happens again.
