### ISSUE TITLE
The valid configuration warning is persistent

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#13791]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After pressing the "check configurations" button, the validation warning "Configuration valid!" appears and remains persistent until I refresh the page from the browser.
But if I do not refresh it, and resume editing the Configuration.yaml file, when I then return to the validation page, I still find the "Configuration valid!" warning. This can be confusing to a novice user

### Describe the behavior you expected

Imo, the "Configuration valid!" warning should disappear after a few seconds (e.g., after 3 sec. with fading effect), and also it should be more prominent

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.9.4

### In which browser are you experiencing the issue with?

Chrome 105.0.5195.127

### Which operating system are you using to run this browser?

Windows 10

**Comment by WRoss7** [comment]
Again

**Comment by WRoss7** [comment]
Persistente 😄

**Comment by WRoss7** [comment]
Up

**Comment by karwosts** [comment]
Fix pr filed.

**Comment by WRoss7** [comment]
Thank you...little things that can confuse new users
