### ISSUE TITLE
Unable to login through external access

### ISSUE THREAD

**Issue by DarkCoocky** [home-assistant/frontend#13804]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I installed HASS this afternoon and wanted to set secure external access.
But I had issues while setting up duckdns+letsencrypt (due to my synology NAS that already uses the 80 port, so LE challenge KO).

So I created a certificate on my nas and then linked it to my HASS server + configured reverse proxy on my nas so that my 443 request is forwarded to HASS server on 8123. I have the login portal, but when the login page should disappear to the dashboard I have the message "Unable to connect to home assistant" 
![image](https://user-images.githubusercontent.com/68286576/190924474-0561467d-3e7b-454b-baf1-580f6a52ad3b.png)
And I've got a message in the system's logs (access through local network):
_Login attempt or request with invalid authentication from lfbn-nan-1-1964-128.w90-105.abo.wanadoo.fr (90.105.137.128). Requested URL: '/auth/token'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0)_

### Describe the behavior you expected

I was expecting to reach the dashboard, like when I log in through the local network

### Steps to reproduce the issue

PREREQUISITE : SYNOLOGY NAS
1.Use a synology NAS and add specific certificate for the hass server
2.Configure reverse proxy from 443 port on the NAS to 8123 on the HASS server
3.Access the UI through external access
4.Log In

### What version of Home Assistant Core has the issue?

2022.9.4

### In which browser are you experiencing the issue with?

Firefox 104.0 + Microsoft Edge 105.0.1343.42

### Which operating system are you using to run this browser?

Windows 11

### Additional information

Configuration.yaml

#Loads default set of integrations. Do not remove.
default_config:

#Text to speech
tts:
  - platform: google_translate
  
automation: !include automations.yaml
script : !include scripts.yaml
scene: !include scenes.yaml

#Enable python scripts
python_script:

#Enable reverse proxy
http:

  use_x_forwarded_for: true
  trusted_proxies:
    - ipv4.address.of.nas #Add the IP address of the proxy server
	- ipv6:address:of:nas:::::

#Enable trusted login sources
homeassistant:
  auth_providers:
    - type: homeassistant
	- type: trusted_networks
	  trusted_networks:
	    - ipv4.address.of.nas #Add the IP address of the proxy server
	    - ipv6:address:of:nas:::::
		- ipv4.adress.of.InternetBox

**Comment by elupus** [comment]
Proxy cant be trusted server for authentication. Please remove trusted_networks authentication.

**Comment by DarkCoocky** [comment]
> Proxy cant be trusted server for authentication. Please remove trusted_networks authentication.

Well I already removed these lines because they didn't allow me to solve the problem. But I'll keep that in mind in the future.

**Comment by DarkCoocky** [comment]
Hi, I finally found what's wrong using the documentation talking about the reverse proxy. It's just that in my synology NAS, I forgot to enable the websocket service. My bad
