### ISSUE TITLE
Ugliness with helpers showing up in cards with misaligned labels

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#13800]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the image below, the misalignment between the binary sensor label and the input select label is clearly visible, and it is even more visible if the input select background is made the same color as the card.
Also the right side of the button does not align with the background of the input select.
It also affects other Helpers, for example, the text box.

![Image](https://user-images.githubusercontent.com/74879713/190910713-7677a38c-d0af-4b3f-a283-1038aa13bb9d.png)

### Describe the behavior you expected

The labels should be aligned, as well as the button

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.9.4

### In which browser are you experiencing the issue with?

Chrome 105.0.5195.127

### Which operating system are you using to run this browser?

Windows 10

**Comment by WRoss7** [comment]
Again

**Comment by ildar170975** [comment]
Temporarily can be fixed by card-mod:
![image](https://user-images.githubusercontent.com/71872483/208269946-26f4f108-942e-4099-a664-b4dfa56a8148.png)
```
type: entities
entities:
  - entity: sun.sun
  - entity: input_select.test_value
  - entity: input_select.test_value
    card_mod:
      style:
        ha-select $: |
          .mdc-select__anchor {
            padding-inline: 16px 0px !important;
          }
          .mdc-select__anchor span#label {
            inset-inline-start: 16px;
          }
```

**Comment by WRoss7** [comment]
Thanks for the tip

**Comment by ildar170975** [comment]
Let it be active

**Comment by WRoss7** [comment]
I also point out here the other visible ugliness: the red lines for vertical alignments, and the green lines for horizontal spacing


![Image](https://github.com/home-assistant/frontend/assets/74879713/78e48fa6-2bdc-4cc9-b946-e6c2d2136f65)

**Comment by ildar170975** [comment]
up

**Comment by WRoss7** [comment]
Up

**Comment by WRoss7** [comment]
_

**Comment by WRoss7** [comment]
Well, the cards will be adapted at some point to the new guidelines, so it no longer makes sense for this report to remain open.

**Comment by WRoss7** [comment]
Well, the cards will be adapted at some point to the new guidelines, so it no longer makes sense for this report to remain open.
