### ISSUE TITLE
Automation/Scripts: card headers are not translateable

### ISSUE THREAD

**Issue by sevorl** [home-assistant/frontend#13820]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Home assistant 2022.9 introduced colapsible cards. The headline of these cards are not translated to German, and the strings do not seem to appear in Lokalise (frontend). 
I'd be happy to contribute to the translations but the strings don't seem to be translateable yet. 

![image](https://user-images.githubusercontent.com/81764300/191186167-9ca10347-f459-4b40-a702-b0309e6ba7b0.png)

### Describe the behavior you expected

Strings in card headlines in Automations and strings are translateable

### Steps to reproduce the issue

1. Use Home assistant in German (or other non-english language)
2. Open Automations
3. Observere that headlines at the collapsible cards are not translated and are displayed in english
...

### What version of Home Assistant Core has the issue?

2022.09.1

### In which browser are you experiencing the issue with?

Chrome 104.0.5112.102

### Which operating system are you using to run this browser?

Windows 10

**Comment by bdr99** [comment]
This is not stale, the issue still exists in 2022.12.
