### ISSUE TITLE
Energy Dashboard Not Aggregating Usage

### ISSUE THREAD

**Issue by CHARL13is** [home-assistant/frontend#13838]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have my energy dashboard configured and displaying gas and electricity usage, apart from the Energy Distribution graphic which while it displays both gas and electric going into the home it is only showing the electric usage as the total.

![583182909b2b9a7724d4c4c859b0b18d9e491653](https://user-images.githubusercontent.com/51113094/191480764-25525360-a963-4b44-961f-8da982d8d66e.png)

### Describe the behavior you expected

The home figure is a combination of the gas and electricity value.

### Steps to reproduce the issue

Unknown

### What version of Home Assistant Core has the issue?

2022.9.5

### In which browser are you experiencing the issue with?

Chrome 105.0.5195.127 and Edge 105.0.1343.42

### Which operating system are you using to run this browser?

Windows 10

**Comment by jonathh21** [comment]
I am seeing exactly this - It was closed with no action?

![image](https://github.com/home-assistant/frontend/assets/13969744/03bd5e8b-3394-49f8-8743-f2a775f57f29)
