### ISSUE TITLE
State names 

### ISSUE THREAD

**Issue by Nubstex** [home-assistant/frontend#13861]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![image](https://user-images.githubusercontent.com/91033840/192121213-7243a896-a87a-4f2e-8e12-a4bcdf6ed48c.png)

Polish translations provided by HA are not capitalised correctly, can you change it in https://github.com/home-assistant/frontend/blob/dev/translations/backend/pl.json file? It just looks very ugly

### Describe the behavior you expected

Capitalized letters

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.9.6

**Comment by frenck** [comment]
Translations are managed via the Lokalise translation plaform. Anybody can contribute/help out translating Home Assistant.

For more information on how and where to go, check out the translation documentation:

<https://developers.home-assistant.io/docs/translations>

../Frenck
