### ISSUE TITLE
Scheduler not adjustable on android

### ISSUE THREAD

**Issue by Scorpoon** [home-assistant/frontend#13865]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When trying to create the new scheduler helper the time is not adjustable at all in the browser. In the companion app the time is only adjustable when you are on top of the time grid so it won't scroll up.

### Describe the behavior you expected

Time should be adjustable, maybe disable scrolling on the grid when on mobile.

### Steps to reproduce the issue

1. Open HA App or open HA in the Browser
2. Go to Settings, Devices & Services, Helper
3. Create a new scheduler helper
4. Try to adjust the time

### What version of Home Assistant Core has the issue?

2022.9.6

### In which browser are you experiencing the issue with?

Google Chrome 105.0.5195.136 / Companion App 2022.9.1-full

### Which operating system are you using to run this browser?

Android 13

**Comment by nicedevil007** [comment]
Same on here, If I open an already configured timer from some days ago I can't see the selected times. It is just empty like this:
![image](https://user-images.githubusercontent.com/17103076/192134157-6488e29c-cbca-4aaa-a658-b3fe73678851.png)

Also if I try to setup a new timer I can only select one time and on saving this timer I get an error message like this:

```
Overlapping times found in schedule for dictionary value @ data['tuesday']. Got [{'from': '9:00', 'to': '9:30'}, {'from': '9:00', 'to': '9:30'}, {'from': '9:00', 'to': '9:30'}, {'from': '8:30', 'to': '9:00'}]
```

**Comment by IgnacioHR** [comment]
The overlapping error is raised because the start and end periods are correctly stored and your edit to the current schedule generates overlap periods, this means, the error is legitime. The root cause of the error is the UI not displaying the periods set in the schedule.

I opened the front-end in debug mode and I can see the front-end is receiving the json from the backend, but it is not properly represented.
<img width="778" alt="Window" src="https://user-images.githubusercontent.com/16385090/192142449-8eff1c10-7107-4139-a2bf-e457bbce0b1d.png">

<img width="613" alt="Window" src="https://user-images.githubusercontent.com/16385090/192142490-6fed413b-5920-4dda-8dc3-0ccb8692342d.png">

**Comment by nicedevil007** [comment]
May I add that the overlapping error generates on a completly new test timer?
In my opinion it was/is possible to generate multiple timer helpers that can turn on or off by the same time. Am I be wrong at this point?

**Comment by rp3tya** [comment]
It doesn't work for me either. Tried Firefox and Chromium on desktop, Schedule Settings is always empty, newly added entries disapear if you click away, though they are saved in the backend. This is why you can get overlapping errors if you delete and then create a new schedule with the same name.

**Comment by Scorpoon** [comment]
I guess the overlapping bug and that one which does not display well should have it's own thread because my issue is a complete different.
Maybe i'm wrong 😂

**Comment by rp3tya** [comment]
It is the same thing, one creates overlapping entries because cannot see what is already configured.

**Comment by itsmartinho** [comment]
Same is happening to me so I assume it's a generalized bug that'll be fixed eventually.

**Comment by armageddon421** [comment]
I have the same issue on Windows/Chrome as well as on Android in the App. I did not try other browsers yet.

**Comment by IgnacioHR** [comment]
@armageddon421 Look at this screen capture of my debug session. It looks to me the values set to the calendar are out of the calendar thus, not displayed. Maybe tomorrow they will pop-up. There is cleanly a bug somewhere!

<img width="553" alt="Window" src="https://user-images.githubusercontent.com/16385090/192155954-13a1013d-41cc-467c-8e8c-3aa1f72aa993.png">

**Comment by IgnacioHR** [comment]
And the bug is here:

The _events() getter is generating dates from the start-end ranges (that only contains hour, minute and seconds) set for every week day using a "distance" from currentDay. On Sunday, that current day is 0. Events are created for the following week because distance is a positive number. I tried to change the calculation of "distance" by subtracting 7 days and it works today (it is Sunday) but I'm not sure it will work tomorrow. This method requires a deep review from the author.

<img width="501" alt="Window" src="https://user-images.githubusercontent.com/16385090/192157201-33895d30-1cdb-4142-ae5a-8f6a3fb267e5.png">

**Comment by vanderdude** [comment]
> And the bug is here:
> 
> The _events() getter is generating dates from the start-end ranges (that only contains hour, minute and seconds) set for every week day using a "distance" from currentDay. On Sunday, that current day is 0. Events are created for the following week because distance is a positive number. I tried to change the calculation of "distance" by subtracting 7 days and it works today (it is Sunday) but I'm not sure it will work tomorrow. This method requires a deep review from the author.
> 
> <img alt="Window" width="501" src="https://user-images.githubusercontent.com/16385090/192157201-33895d30-1cdb-4142-ae5a-8f6a3fb267e5.png">

I think you have correctly identified the issue. Well done.

**Comment by veitw** [comment]
> Maybe there is an edge case where the UI breaks specifically on sundays?

I can confirm this. The issue appeared on Sunday on all my client platforms (Firefox, Chromium, HA app on Android), while it worked perfectly on Saturday and Friday. Today, on Monday, 0:00 o'clock it started working again.

**Comment by IgnacioHR** [comment]
I've created a pull request to fix this!

https://github.com/home-assistant/frontend/pull/13876

**Comment by Scorpoon** [comment]
The problem with the adjustable time on android would still be there after your fix.

**Comment by nicedevil007** [comment]
btw today I was able to see the schedules again as others already figured out here.... I will create a new issue for this but just for you as well

I setup a timer with 30min so from 4pm to 4:30pm:
![image](https://user-images.githubusercontent.com/17103076/192343022-07dd38e0-5d46-4958-88d1-7f82130ec220.png)

after hitting the update button and opening the timer again it tells me this:
![image](https://user-images.githubusercontent.com/17103076/192343210-32a62e1e-d6f9-4c2b-bbbd-a80766340ac9.png)

**Comment by Scorpoon** [comment]
It is working now, but users have to know that they have to press a timeslot and pull into the right direction. If there is no other solution for it a help text would be great.
