### ISSUE TITLE
Scheduler doesn't work when filling time on half hour

### ISSUE THREAD

**Issue by sldewit** [home-assistant/frontend#13877]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I use the scheduler and fill in times on the whole hour like 7:00 to 8:00 all goes well, but this morning I wanted to change the schedule to 6:30 to 7:30 and first it seemed to work, but once I re-open the screen it shows 6:00 to 7:00 in stead. 

Next to this in the Home Assistant android App this doesn't work at all. 

### Describe the behavior you expected

Use of the timestamp I filled in, or give an error if it is incorrect

### Steps to reproduce the issue

1. Make new schedule helper
2. Set time to 6:30 to 7:30
3. Save
4. Reopen the screen and it shows 6:00
...

### What version of Home Assistant Core has the issue?

2022.09.1

### In which browser are you experiencing the issue with?

Google Chrome Version 105.0.5195.127 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

**Comment by amitfin** [comment]
Issue was fixed by https://github.com/home-assistant/frontend/pull/13929.
