### ISSUE TITLE
Custom icons do not work in all places

### ISSUE THREAD

**Issue by frenck** [home-assistant/frontend#13875]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The use of custom icon only works on dashboards. Any place outside of that, simply doesn't work. They don't show anywhere and aren't available in the icon picker at that point either.

Device page:

![image](https://user-images.githubusercontent.com/195327/192223191-13f19e11-a578-4990-83ed-bed8daa6940b.png)

![CleanShot 2022-09-26 at 09 55 31](https://user-images.githubusercontent.com/195327/192223235-34fcd37c-d6d9-4e9f-89c8-1503e3c94ac8.png)

Dashboard:

![CleanShot 2022-09-26 at 09 56 38](https://user-images.githubusercontent.com/195327/192223466-8fb7701d-83b8-48b6-8b37-e14ab491fcc7.png)

![CleanShot 2022-09-26 at 09 57 06](https://user-images.githubusercontent.com/195327/192223545-98cc5b66-c554-40fa-b53d-aed9aa923224.png)

### Describe the behavior you expected

I expected the behavior to be consistent across all places in Home Assistant.

### Steps to reproduce the issue

1. Install a custom icon pack (e.g., Hue icons) from HACS
2. Try setting an `hue:lily` icon on a dashboard somewhere, confirm it works
3. Try changing the icon of an entity from a device page -> doesn't work.

### What version of Home Assistant Core has the issue?

2022.10.0.dev20220926

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Version 105.0.5195.125 (Official Build) (x86_64)

### Which operating system are you using to run this browser?

macOS Monterey (12.2.1)

**Comment by frenck** [comment]
It is actually documented in the Hue icons:

![CleanShot 2022-09-26 at 11 52 21](https://user-images.githubusercontent.com/195327/192247357-31c5dd41-43a6-49f2-aabe-844241cdeac9.png)

<https://github.com/arallsopp/hass-hue-icons#hacs-recommended>

However, it is kinda unexpected that it works this way, I guess?

**Comment by frenck** [comment]
Alright, this seems like a Hue icons thing.
It should register itself as integration to register the extra module (instead of its current approach).

Closing it on this end.

**Comment by ildar170975** [comment]
These icons are installed similarly:
https://github.com/elax46/custom-brand-icons
[And it is also specified to declare as `extra_module_url` in the docs.](https://github.com/elax46/custom-brand-icons#install)
