### ISSUE TITLE
Unable to change entity_id of nspanel switch

### ISSUE THREAD

**Issue by pploume** [home-assistant/frontend#13892]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When trying to change an auto-generated entity_id by something more "human readable", I get an error message "Invalid entity ID"

ie:
auto-generated id : switch.mqtt_31f12c_rl_2 (switch #2 on a SonOff NSPanel, tasmota 10.0.2)
to
switch.nspanel1-2 (or anything else ... changing only 1 letter generate the error message)

same problem with switch #1 ....

![image](https://user-images.githubusercontent.com/36375648/192594178-28a73db4-f2ad-44d0-95cd-a794a402c7f5.png)

### Describe the behavior you expected

be able to change the entity_id

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

OS 9.0

### What was the last working version of Home Assistant Core?

?

### In which browser are you experiencing the issue with?

Chrome latest

### Which operating system are you using to run this browser?

Raspberry

### State of relevant entities

```txt
Home Assistant 2022.9.7
Supervisor 2022.09.1
Operating System 9.0
Interface utilisateur : 20220907.2 - latest
```

### Additional information

not a big problem ...

**Comment by frenck** [comment]
`switch.nspanel1-1` is not a valid entity ID. Entity ID can only contain `a` - `z`, `0` - `9` and underscores `_`. They can only be lowercase and must start with a letter.

Looking at your entity ID, it contains a dash (`-`), which isn't allowed as per above.

../Frenck
