### ISSUE TITLE
Scheduler helper

### ISSUE THREAD

**Issue by iwojima1** [home-assistant/frontend#13899]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

hello i found that if I set schediler visually to 8:30 and save it, it will show number and also visual bar from 8:00.
In atributes to next change is correct 8:30. I thing it is bug that it shows 8:00

Off topic: is it possible to edit it in yaml for exaple to 8:12??

Thanks
![1664349494669](https://user-images.githubusercontent.com/58654060/192724870-7e628bae-f543-4329-b6b6-61a19c2531d0.jpg)
![1664349494682](https://user-images.githubusercontent.com/58654060/192724882-8a50dfa7-d656-4d87-ab40-938d83b33989.jpg)

Ivan

### Describe the behavior you expected

hello i found that if I set schediler visually to 8:30 and save it, it will show number and also visual bar from 8:00.
In atributes to next change is correct 8:30. I thing it is bug that it shows 8:00

### Steps to reproduce the issue

hello i found that if I set schediler visually to 8:30 and save it, it will show number and also visual bar from 8:00.
In atributes to next change is correct 8:30. I thing it is bug that it shows 8:00

### What version of Home Assistant Core has the issue?

2022.9.4

### In which browser are you experiencing the issue with?

chrome

### Which operating system are you using to run this browser?

chrome

**Comment by mvoehringer** [comment]
see #13877

**Comment by amitfin** [comment]
Issue was fixed by https://github.com/home-assistant/frontend/pull/13929.
