### ISSUE TITLE
Related logbook entries delays trace UI.

### ISSUE THREAD

**Issue by Petro31** [home-assistant/frontend#13901]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When a trace has logbook entiries, it can take upwards of 5 minutes on a powerful machine to display the trace even if the Related logbook entries tab is not selected and visible.

You can test this out yourself by creating an automation with an entity that doesn't have logbook entries vs a trace with logbook entries.

### Describe the behavior you expected

I'd expect the UI to do nothing with logbook entries unless the user is displaying the logbook entries tab.  This way, viewing traces is instant.  When clicking on the Related logbook entries, the system will then perform the database queries and possibly display a "Getting entries" spinning wheel.

### Steps to reproduce the issue

1. Create an automation that references entities that are not stored in logbook
2. Create an automation that references entities that are stored in logbook.  Let these entities collect days of data.
3. Compare loading times between the 2 traces on the automations.

### What version of Home Assistant Core has the issue?

Every version that uses traces and displays logbook entries

### What was the last working version of Home Assistant Core?

the version where logbook entries were not displayed (if ever)

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

Doesn't matter

**Comment by scaarup** [comment]
I am seeing the same issue. Captured this SQL statement while trying to retrieve an automation trace:

`SELECT events.event_id AS event_id, events.event_type AS event_type, events.event_data AS event_data, events.time_fired AS time_fired, events.context_id AS context_id, events.context_user_id AS context_user_id, events.context_parent_id AS context_parent_id, event_data.shared_data AS shared_data, 0 AS state_id, NULL AS state, NULL AS entity_id, NULL AS icon, NULL AS old_format_icon, NULL AS context_only 
FROM events 
LEFT OUTER JOIN event_data ON events.data_id = event_data.data_id WHERE events.time_fired > '2022-09-28 09:20:43.085626' AND
events.time_fired < '2022-09-28 11:35:44.400510' AND events.event_type 
  IN ('call_service', 'logbook_entry', 'homeassistant_stop', 'homeassistant_start', 'zwave_js_notification', 'zwave_js_value_notification', 'deconz_alarm_event', 'deconz_event', 'hue_event', 'script_started', 'shelly.click', 'automation_triggered', 'ios.zone_entered', 'ios.zone_exited') AND events.context_id = '01GE1PBZJDQQGG2HTN2FZ3D279' 

UNION ALL 
SELECT NULL AS event_id, NULL AS event_type, NULL AS event_data, states.last_updated AS time_fired, states.context_id AS context_id, states.context_user_id AS context_user_id, states.context_parent_id AS context_parent_id, NULL AS shared_data, states.state_id AS state_id, states.state AS state, states.entity_id AS entity_id, CASE JSON_EXTRACT(CAST(state_attributes.shared_attrs AS CHAR), '$.\"icon\"') WHEN 'null' THEN NULL ELSE JSON_UNQUOTE(JSON_EXTRACT(CAST(state_attributes.shared_attrs AS CHAR), '$.\"icon\"')) END AS icon, CASE JSON_EXTRACT(CAST(states.attributes AS CHAR), '$.\"icon\"') WHEN 'null' THEN NULL ELSE JSON_UNQUOTE(JSON_EXTRACT(CAST(states.attributes AS CHAR), '$.\"icon\"'))
END AS old_format_icon, NULL AS context_only 
FROM states 
LEFT OUTER JOIN states AS old_state ON states.old_state_id = old_state.state_id 
LEFT OUTER JOIN state_attributes ON states.attributes_id = state_attributes.attributes_id WHERE states.last_updated > '2022-09-28 09:20:43.085626' AND states.last_updated < '2022-09-28 11:35:44.400510' AND old_state.state_id IS NOT NULL AND states.state != old_state.state AND states.state IS NOT NULL AND ((states.entity_id NOT LIKE 'proximity.%' AND states.entity_id NOT LIKE 'counter.%' AND states.entity_id NOT LIKE 'sensor.%') OR ((states.entity_id LIKE 'sensor.%') AND (state_attributes.shared_attrs NOT LIKE '%\"unit_of_measurement\":%' OR states.attributes NOT LIKE '%\"unit_of_measurement\":%'))) AND (states.last_updated = states.last_changed OR states.last_changed IS NULL) AND states.context_id = '01GE1PBZJDQQGG2HTN2FZ3D279' 

UNION ALL 
SELECT events.event_id AS event_id, events.event_type AS event_type, events.event_data AS event_data, events.time_fired AS time_fired, events.context_id AS context_id, events.context_user_id AS context_user_id, events.context_parent_id AS context_parent_id, NULL AS shared_data, states.state_id AS state_id, states.state AS state, states.entity_id AS entity_id, CASE JSON_EXTRACT(CAST(state_attributes.shared_attrs AS CHAR), '$.\"icon\"') WHEN 'null' THEN NULL ELSE JSON_UNQUOTE(JSON_EXTRACT(CAST(state_attributes.shared_attrs AS CHAR), '$.\"icon\"')) END AS icon, CASE JSON_EXTRACT(CAST(states.attributes AS CHAR), '$.\"icon\"') WHEN 'null' THEN NULL ELSE JSON_UNQUOTE(JSON_EXTRACT(CAST(states.attributes AS CHAR), '$.\"icon\"')) END AS old_format_icon, NULL AS context_only 
FROM events 
 LEFT OUTER JOIN states ON events.event_id = states.event_id 
 LEFT OUTER JOIN state_attributes ON states.attributes_id = state_attributes.attributes_id 
   WHERE (states.last_updated = states.last_changed OR states.last_changed IS NULL) AND ((states.entity_id NOT LIKE 'proximity.%' AND states.entity_id NOT LIKE 'counter.%' AND states.entity_id NOT LIKE 'sensor.%') OR ((states.entity_id LIKE 'sensor.%') AND (state_attributes.shared_attrs NOT LIKE '%\"unit_of_measurement\":%' OR states.attributes NOT LIKE '%\"unit_of_measurement\":%'))) AND events.time_fired >
    '2022-09-28 09:20:43.085626' AND events.time_fired < '2022-09-28 11:35:44.400510' AND events.context_id = '01GE1PBZJDQQGG2HTN2FZ3D279' 

ORDER BY time_fired, time_fired;`
Explaining the query, reveals that we are table scanning the states table:

`+----+--------------+------------------+------------+--------+-----------------------------------------------------------------------------------------------------+----------------------+---------+-----------------------------+----------+----------+------------------------------------+
| id | select_type  | table            | partitions | type   | possible_keys                                                                                       | key                  | key_len | ref                         | rows     | filtered | Extra                              |
+----+--------------+------------------+------------+--------+-----------------------------------------------------------------------------------------------------+----------------------+---------+-----------------------------+----------+----------+------------------------------------+
|  1 | PRIMARY      | events           | NULL       | range  | ix_events_time_fired,ix_events_event_type_time_fired                                                | ix_events_time_fired | 9       | NULL                        |       60 |     5.00 | Using index condition; Using where |
|  1 | PRIMARY      | event_data       | NULL       | eq_ref | PRIMARY                                                                                             | PRIMARY              | 4       | hassio.events.data_id       |        1 |   100.00 | NULL                               |
|  2 | UNION        | states           | NULL       | ref    | ix_states_last_updated,ix_states_entity_id_last_updated,ix_states_old_state_id,ix_states_context_id | ix_states_context_id | 147     | const                       |        1 |     5.00 | Using where                        |
|  2 | UNION        | state_attributes | NULL       | eq_ref | PRIMARY                                                                                             | PRIMARY              | 4       | hassio.states.attributes_id |        1 |   100.00 | Using where                        |
|  2 | UNION        | old_state        | NULL       | eq_ref | PRIMARY                                                                                             | PRIMARY              | 4       | hassio.states.old_state_id  |        1 |    90.00 | Using where                        |
|  3 | UNION        | states           | NULL       | ALL    | ix_states_entity_id_last_updated,ix_states_event_id                                                 | NULL                 | NULL    | NULL                        | 31921591 |    73.54 | Using where                        |
|  3 | UNION        | events           | NULL       | eq_ref | PRIMARY,ix_events_time_fired                                                                        | PRIMARY              | 4       | hassio.states.event_id      |        1 |     5.00 | Using where                        |
|  3 | UNION        | state_attributes | NULL       | eq_ref | PRIMARY                                                                                             | PRIMARY              | 4       | hassio.states.attributes_id |        1 |   100.00 | Using where                        |
| NULL | UNION RESULT | <union1,2,3>     | NULL       | ALL    | NULL                                                                                                | NULL                 | NULL    | NULL                        |     NULL |     NULL | Using temporary; Using filesort    |
+----+--------------+------------------+------------+--------+-----------------------------------------------------------------------------------------------------+----------------------+---------+-----------------------------+----------+----------+------------------------------------+`

**Comment by Petro31** [comment]
I was just navigating around the new beta, and I noticed that area's pages' logbook entry does exactly what we need in trace.  Just reuse that code.  The logbook loads slower while automation, entities, and devices load instantly.  This is the behavior that's expected in traces.

**Comment by Petro31** [comment]
I'm seeing this on pages that don't have logbook entities.  So it's possible my testing is incorrect.  Regardless, on some traces there's a 2 to 5 minute delay.  I'm running on a i5 nuc, a page shouldn't take that long to load.  Something is causing the page to have a significant delay.
