### ISSUE TITLE
Not able to delete Energy consumption when sensor name is too long

### ISSUE THREAD

**Issue by MagnusErler** [home-assistant/frontend#13906]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The delete button is not visible when choosing and adding an entity to the Electricity grid whose name is too long. The delete button is visible by the other consumptions which have a shorter name

### Describe the behavior you expected

The delete button should be visible

### Steps to reproduce the issue

1. Settings -> Dashboards -> Energy
2. Choose and add an entity which has a long entity name to the Electricity grid
3. View that the delete button can't be seen [(Picture)](https://ibb.co/0Gym9Bm)

### What version of Home Assistant Core has the issue?

2022.9.7

### In which browser are you experiencing the issue with?

Google Chrome Version 105.0.5195.125 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Ubuntu 20.04.5 LTS 64-bit

**Comment by MagnusErler** [comment]
The issue is still present in 2022.12.0

**Comment by karwosts** [comment]
Addressed in PR #15786
