### ISSUE TITLE
Cmd + click menu items in the sidebar to open the link in a new tab (Google Chrome)

### ISSUE THREAD

**Issue by ndbroadbent** [home-assistant/frontend#13910]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I like to open pages in different tabs, and I usually do this by holding down the Cmd key (on Mac) and then clicking a link. This doesn't work with links in the Home Assistant sidebar menu, so I always need to right click the menu item and choose "Open Link in New Tab".

I haven't looked at the JS code, but I assume you are calling something like `event.preventDefault()`. Would it be possible to check for a modifier key (Cmd on Mac, and Ctrl on Windows/Linux), and then allow links to be opened in a new tab?

### Describe the behavior you expected

I expect to be able to Cmd + click on menu links and open the page in a new tab

### Steps to reproduce the issue

1. Visit the Home Assistant UI in Google Chrome
2. Hold down Cmd (Mac) or Ctrl (Windows/Linux)
3. Click a menu item in the sidebar (Overview, Settings, Developer Tools, etc.)

### What version of Home Assistant Core has the issue?

2022.9.7

### In which browser are you experiencing the issue with?

Google Chrome

(Works in Safari and Firefox)

### Which operating system are you using to run this browser?

macOS

**Comment by frenck** [comment]
> This doesn't work with links in the Home Assistant sidebar menu

It works for me. Could you please update the issue with your browser information and such?

**Comment by ndbroadbent** [comment]
Oops sorry I should have tested other browsers. It's working in Safari and Firefox, but not working in Google Chrome. Thanks!

**Comment by piitaya** [comment]
I just tested in Chrome 106.0.5249.61 (latest version) on macOS. I don't have the issue.

**Comment by frenck** [comment]
I'm on Chrome Version 105.0.5195.125 (Official Build) (x86_64), also on macOS (12.2.1), and cannot reproduce either.

**Comment by ndbroadbent** [comment]
Argh sorry @piitaya and @frenck!!! I finally figured out that this was a misbehaving Chrome extension called Wikiwand (Wikipedia theme): https://chrome.google.com/webstore/detail/wikiwand-wikipedia-modern/emffkefkbkpkgpdeeooapgaicgmcbolj

It looks like they've had a few Ctrl/Cmd click bugs: https://wikiwand.uservoice.com/search?query=command%20click%20links

Sorry to waste your time!
