### ISSUE TITLE
Map card: input helpers should not be permitted to add

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#13922]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

IMHO only entities with geo goord (`latitude`, `longitude`) should be added on the Map card:
- `device_tracker` entities (note that some of them may not have geo coords);
- `person` entities (note that some of them may not have geo coords);
- entities of other domains (like `sensor`) with geo coords.

But currently even input helpers may be added:
1. Start adding a new Map card.
2. Type any helpers's domain (which is w/o geo coords) - like `input_number`, `input_select` etc.
3. Note that the list is filled by eniities of the selected domain.

![image](https://user-images.githubusercontent.com/71872483/193162304-68f64d76-9cbc-4e72-a93c-0eb492c5b57b.png)

### Describe the behavior you expected

As above

### Steps to reproduce the issue

As above

### What version of Home Assistant Core has the issue?

2022.9.7

### In which browser are you experiencing the issue with?

Chrome 106.0.5249.62

### Which operating system are you using to run this browser?

Win10x64

**Comment by ildar170975** [comment]
Not only `input_helper`s - other entities w/o coords may be added too.
Here is an example with `sun.sun`:
![image](https://user-images.githubusercontent.com/71872483/202577825-a100c94d-4bd7-46c1-a2a7-fa211d6c804b.png)

**Comment by ildar170975** [comment]
Up

**Comment by karwosts** [comment]
Floated a PR to add a filter to the list.
