### ISSUE TITLE
Frontend reloads randomly

### ISSUE THREAD

**Issue by Sirs0ri** [home-assistant/frontend#13978]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I'm experiencing a weird issue where the frontend reloads randomly, affecting both lovelace dashboards, and the settings ui.

Every couple of seconds, the "main panel" of the layout (meaning everything but the sidebar) is reloaded, causing popups to disappear, the current scroll position is reset to the top, etc. 

See the attached video for an example in the Dashboards settings ui: I'm manually reloading the whole page (first 2 seconds), then the error closes the "new dashboard" dialog repeatedly (at 10, 20 and 27 seconds).

https://user-images.githubusercontent.com/6765536/193640082-b55552b7-0d77-495c-9d92-6064c23ac6b8.mp4

I am noticing the error most prominently in Chrome, on two different PCs, but I've also seen it happen in Firefox sporadically.

I've seen the error with all my custom components/integrations turned off, and with browser extensions turned off (ie an "unmodified" HASS instance).

### Describe the behavior you expected

The frontend should not reload automatically.

### Steps to reproduce the issue

1. Open any Lovelace Dashboard
2. Scroll down or open a dialog to make a reload more obvious
3. Wait for the scroll position to reset/the dialog to close

### What version of Home Assistant Core has the issue?

2022.9.7

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

107.0.5304.18 (Offizieller Build) beta (64-Bit)

### Which operating system are you using to run this browser?

Win10 21H2, Win11 22h2

### State of relevant entities

```txt
Not applicable, since the error happens in settings pages as well as lovelace frontends.
```

### Problem-relevant frontend configuration

```yaml
Not applicable, since the error happens in settings pages as well as lovelace frontends.
```

### Javascript errors shown in your browser console/inspector

```txt
None
```

### Additional information

Please LMK if there's additional logs I can supply, I haven't seen anything relevant in the main logs.

**Comment by leroyloren** [comment]
I'm seeing the same issue, but I feel like this started with Chrome (107) beta. According to the commit, nothing major happened in the frontend that should be related to this.

**Comment by Sirs0ri** [comment]
I haven't been able to observe the error recently :)
