### ISSUE TITLE
Battery status not ordered correctly

### ISSUE THREAD

**Issue by Sholofly** [home-assistant/frontend#13986]
### The problem

When I sort my devices ascending on battery percentage in the devices dashboard the order isn't right. The 100% items are shown on the bottom everything with less percentage seems out of order :). EDIT (Same counts for ordering descending... except for the fact that 100% items are shown on top)

### What version of Home Assistant Core has the issue?

2022.10.0b0

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Default devices dashboard

**Comment by adrianrdzv** [comment]
Issue still happening. Here is a video of the weird sorting states when clicking on Battery sorting:


https://user-images.githubusercontent.com/4851625/209971158-9ca5c1f2-103b-431a-bf40-0ad96cfd93d9.mov

**Comment by karwosts** [comment]
Duplicate of #10973. These were being sorted by string value, not by numeric value. Linked pull request changes the sort order to numeric.

**Comment by steverep** [comment]
Duplicate of #10973
