### ISSUE TITLE
Unable to add zwave_js or zha config entry in 2022.10.b6

### ISSUE THREAD

**Issue by raman325** [home-assistant/frontend#13996]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When attempting to add a Z-Wave or ZHA config entry, the user is told that "this device cannot be added from the UI." Screenshots below

### Describe the behavior you expected

n/a

### Steps to reproduce the issue

1. Add Integration
2. Select Z-Wave or ZHA
3. Select Z-Wave or ZHA in the "What do you want to add" dialog
4. Observe the error
...

### What version of Home Assistant Core has the issue?

2022.10.b6

### Additional information

<img width="485" alt="image" src="https://user-images.githubusercontent.com/7243222/193934391-00cd4959-83d6-4e23-bc19-f37a2868a868.png">

(ignore the fact that it looks like I am clicking on the first entry, I clicked on the second one)
<img width="496" alt="image" src="https://user-images.githubusercontent.com/7243222/193934399-9783cc6c-24bf-4640-87ff-e172b31970b8.png">

<img width="544" alt="image" src="https://user-images.githubusercontent.com/7243222/193934409-3517f3e8-0a20-40c7-919d-657098a4c72c.png">

**Comment by dmulcahey** [comment]
I think this was fixed by https://github.com/home-assistant/frontend/pull/14001
