### ISSUE TITLE
Automation editor overflow menu missing text label for duplicate action

### ISSUE THREAD

**Issue by krazos** [home-assistant/frontend#14004]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the overflow menu at the top of the automation editor, the duplicate action shows an icon but is missing the text label. I am seeing this on both my production and dev environments, on web and iOS mobile app, and [confirmed by another user on Discord](https://discord.com/channels/330944238910963714/427516175237382144/1026875122369441953). 

I believe the text label may have disappeared in connection with recent changes to show read only automations (i.e., YAML-configured outside of automations.yaml) in the automation picker (e.g., https://github.com/home-assistant/frontend/pull/13900).

For read only automations, the relevant action has been changed from duplicate to migrate, and the Migrate label appears as expected for read only automations.

See screenshot below showing the missing label. 

### Describe the behavior you expected

Duplicate label should appear

### Steps to reproduce the issue

1. Open automation in automation editor.
2. Click overflow menu icon at top right of screen.

### What version of Home Assistant Core has the issue?

core-2022.10.0b6

### What was the last working version of Home Assistant Core?

core-2022.10.0b1/2 (?)

### In which browser are you experiencing the issue with?

Google Chrome 106.0.5249.91 and iOS App

### Which operating system are you using to run this browser?

Windows 11 / iOS 16

### Additional information

Missing Text Label:

![image](https://user-images.githubusercontent.com/18428022/194068648-4a1ec345-cb2a-4c12-9eaf-be8ba5b96da5.png)

HTML from Chrome Dev Tools Inspector:

![image](https://user-images.githubusercontent.com/18428022/194078180-2ee3fd18-27ae-4ff9-bf17-9948585ccdf0.png)

**Comment by RosemaryOrchard** [comment]
I was able to make this happen in Safari on macOS by clicking the three dots on a brand new unsaved automation. The rendered HTML looks like this (in case that helps someone).

```html
        <ha-button-menu corner="BOTTOM_START" slot="toolbar-icon">
          <ha-icon-button slot="trigger"></ha-icon-button>

          <mwc-list-item graphic="icon" mwc-list-item="" tabindex="0" disabled="" aria-disabled="true" role="menuitem">
            <!--?lit$781337219$-->Information
            <ha-svg-icon slot="graphic"></ha-svg-icon>
          </mwc-list-item>

          <mwc-list-item graphic="icon" mwc-list-item="" tabindex="-1" disabled="" aria-disabled="true" role="menuitem">
            <!--?lit$781337219$-->Run
            <ha-svg-icon slot="graphic"></ha-svg-icon>
          </mwc-list-item>

          <!--?lit$781337219$-->

          <mwc-list-item graphic="icon" mwc-list-item="" tabindex="-1" disabled="" aria-disabled="true" role="menuitem">
            <!--?lit$781337219$-->Rename
            <ha-svg-icon slot="graphic"></ha-svg-icon>
          </mwc-list-item>

          <!--?lit$781337219$-->
                <mwc-list-item graphic="icon" mwc-list-item="" tabindex="-1" aria-disabled="false" role="menuitem">
                  <!--?lit$781337219$-->Change mode
                  <ha-svg-icon slot="graphic"></ha-svg-icon>
                </mwc-list-item>
              
          <!--?lit$781337219$--><mwc-list-item graphic="icon" mwc-list-item="" tabindex="-1" aria-disabled="false" role="menuitem">
                <!--?lit$781337219$-->Re-order
                <ha-svg-icon slot="graphic"></ha-svg-icon>
              </mwc-list-item>

          <mwc-list-item graphic="icon" mwc-list-item="" tabindex="-1" disabled="" aria-disabled="true" role="menuitem">
            <!--?lit$781337219$-->
            <ha-svg-icon slot="graphic"></ha-svg-icon>
          </mwc-list-item>

          <li divider="" role="separator"></li>

          <mwc-list-item graphic="icon" mwc-list-item="" tabindex="-1" aria-disabled="false" role="menuitem">
            <!--?lit$781337219$-->Edit in visual editor
            <!--?lit$781337219$--><ha-svg-icon class="selected_menu_item" slot="graphic"></ha-svg-icon>
          </mwc-list-item>
          <mwc-list-item graphic="icon" mwc-list-item="" tabindex="-1" aria-disabled="false" role="menuitem">
            <!--?lit$781337219$-->Edit in YAML
            <!--?lit$781337219$-->
          </mwc-list-item>

          <li divider="" role="separator"></li>

          <mwc-list-item graphic="icon" mwc-list-item="" tabindex="-1" disabled="" aria-disabled="true" role="menuitem">
            <!--?lit$781337219$-->Disable
            <ha-svg-icon slot="graphic"></ha-svg-icon>
          </mwc-list-item>

          <mwc-list-item graphic="icon" class="  " mwc-list-item="" tabindex="-1" disabled="" aria-disabled="true" role="menuitem">
            <!--?lit$781337219$-->Delete
            <ha-svg-icon slot="graphic" class="  ">
            </ha-svg-icon>
          </mwc-list-item>
        </ha-button-menu>
```

![image](https://user-images.githubusercontent.com/16113535/194077694-c6f7331c-2d4f-431b-a0ec-0affb08f9726.png)
