### ISSUE TITLE
Camera preview stretches popup window

### ISSUE THREAD

**Issue by gigatexel** [home-assistant/frontend#14017]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After clicking the sensor representing my doorbell:

![image](https://user-images.githubusercontent.com/65073191/194310078-48b17fef-c951-4312-91c2-6d3ba70f8a7d.png)

The entity-detail window pops up with a preview of the current camera view. 
This preview is not scaled, causing the popup to fill the whole screen.

![Uploading image.png…]()

### Describe the behavior you expected

Scale the image so the popup size stays normal

### Steps to reproduce the issue

1. Add camera/doorbell with picture preview
2. Go to the integration (in my case Netatmo) and click the sensor

### What version of Home Assistant Core has the issue?

core-2022.10.0

**Comment by KNXBroker** [comment]
Duplicate? https://github.com/home-assistant/frontend/issues/13581
