### ISSUE TITLE
Picture glance shaking (only visible in very high refresh rate)

### ISSUE THREAD

**Issue by felipecrs** [home-assistant/frontend#14011]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have four cameras displaying at the same time the live feed in my dashboard. All them using WebRTC as stream provider. It's very weird that they keep shaking while in the dashboard view. I hope you can notice by the following screen recording.

EDIT: Wow I just realized that the video does not shows the problem. After some additional testing, it seems that the problem can only be observed in very high refresh rate monitors (mine has 144Hz).

Perhaps there is some logic in frontend which refreshes the container a given times per second (not according to the current refresh rate), and that's why I can only observe it in high frequency monitors.

https://user-images.githubusercontent.com/29582865/194188797-8a589217-8291-4199-be21-9ec7e1e2a075.mp4

### Describe the behavior you expected

Not to shake?

### Steps to reproduce the issue

I'm so sorry, but I don't know if the issue can be reproduced elsewhere. But if someone is interested in trying to fix it, I can create temporary credentials to my HA instance where the issue can be easily reproduced.

### What version of Home Assistant Core has the issue?

2022.10.0

**Comment by user897943** [comment]
Eu sabia que você era brasileiro só olhando pro vídeo uahauhauha saudades do Brasil <3

**Comment by felipecrs** [comment]
> Eu sabia que você era brasileiro só olhando pro vídeo uahauhauha saudades do Brasil <3

hahahaha 😋

**Comment by felipecrs** [comment]
I was able to capture a slow-motion video showing the issue:


https://user-images.githubusercontent.com/29582865/200678511-9c5d01bc-353e-4625-a903-353c9039abfe.mp4
