### ISSUE TITLE
Automation: disabling action shows "Key 'enabled' is not expected or not supported by the visual editor."

### ISSUE THREAD

**Issue by VikingKing** [home-assistant/frontend#14021]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Disabling action in GUI in automation shows "Key enabled is not expected or not supported by the visual editor."
Enabling it agains show the same error.
It does not understand the line containing "enable". 
I have to switch to yaml editor and remove the line.

### Describe the behavior you expected

Since the visual editor inserts the line, it should also understand what is means. :)

### Steps to reproduce the issue

1. Open an existing automation
2. Expand and dIsable a action in the automation. 
3. The visual editor inserts "enabled: false"
4. This causes the message "Key enabled is not expected or not supported by the visual editor."
5. Changing back to "enabled" in visual editor changes the line to "enabled: true"
6. Still shows the message.
7. Switch to YAML editor and remove the "enabled: " line 
8. Switch back to visual editor
9. Message gone

![image](https://user-images.githubusercontent.com/4415981/194324235-f3d6cdc7-dd43-425a-9c15-20662688f6b4.png)

EDIT:
It looks like this happens only on actions that runs a script:
![image](https://user-images.githubusercontent.com/4415981/194496413-c9caeee9-0158-4d91-a5b1-1d645ae9f92d.png)

### What version of Home Assistant Core has the issue?

core 2022.10.0

**Comment by Shulyaka** [comment]
Not only script, I also have this issue for calling a service:

![изображение](https://user-images.githubusercontent.com/2741408/202672082-71f9e5b6-2bd6-47d2-a36b-dd53806dea12.png)

**Comment by karliemeads** [comment]
This should be resolved in https://github.com/home-assistant/frontend/issues/14532
