### ISSUE TITLE
UI - date is not localised

### ISSUE THREAD

**Issue by HarvsG** [home-assistant/frontend#14038]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![image](https://user-images.githubusercontent.com/11440490/194590251-44708ad7-70bd-4146-b891-eac5b14a7bf3.png)

I am UK based and being given the date in mm/dd/yyyy

~To be fair it may be a general UI issue - I just can't find any other dates presented in anything other than ISO yyyy-mm-dd~

Similarly it is not localised in the energy dashboard:
![image](https://user-images.githubusercontent.com/11440490/194592134-8512886f-23b5-48e6-95e4-d27efcc18d67.png)
UK would put the number before the month (I think), although not ambiguous here.

### Describe the behavior you expected

Date to be presented in the ISO format or a localised format

### Steps to reproduce the issue

1. Induce a repair
2. See date
3.
...

### What version of Home Assistant Core has the issue?

2022.10.1

### In which browser are you experiencing the issue with?

Chrome Version 106.0.5249.91 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/11440490/194594652-bf7546eb-394c-48eb-b709-02042041af9e.png)

### Which operating system are you using to run this browser?

Windows 10

**Comment by HarvsG** [comment]
Possibly linked to https://github.com/home-assistant/frontend/issues/12635

**Comment by karliemeads** [comment]
Duplicate 13963

**Comment by HarvsG** [comment]
Probably fixed in #13964
