### ISSUE TITLE
Can t activate Google Assistant anymore

### ISSUE THREAD

**Issue by martin82private** [home-assistant/frontend#14034]
### The problem

Hi

some month ago i activated google assistant after i wasn t happy with it i deactivated again.
Now i want to setup it again (through nabu casa cloud) but i can t switch on the google assistant.
![Screenshot 07 10 2022 um 15 48 51 PM](https://user-images.githubusercontent.com/53186904/194569087-5b3e90a7-4c13-4350-ba3c-6c790adb7994.png)

in the logs i get only following message if i want to turn it on:
2022-10-07 15:43:39.436 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140238961947408] Error handling message: extra ke
ys not allowed @ data['']. Got True (invalid_format)  

### What version of Home Assistant Core has the issue?

2022.10.1

### What was the last working version of Home Assistant Core?

can t remember

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

Google Assistant

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/google_assistant/

**Comment by balloob** [comment]
@martin82private we'll try to include this in the next hot fix release 👍

**Comment by martin82private** [comment]
Thanks for your fast support

 

Von: Paulus Schoutsen ***@***.***>
Antworten an: home-assistant/frontend ***@***.***>
Datum: Freitag, 7. Oktober 2022 um 16:21
An: home-assistant/frontend ***@***.***>
Cc: Martin Tschanun ***@***.***>, Mention ***@***.***>
Betreff: Re: [home-assistant/frontend] Can t activate Google Assistant anymore (Issue #14034)

 

@martin82private we'll try to include this in the next hot fix release 👍
