### ISSUE TITLE
Script ID change... again

### ISSUE THREAD

**Issue by chertvl** [home-assistant/frontend#14048]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Peviously we couldn't change entity_id of script because we missed the opportunity of edit script with GUI,
that was fixed in https://github.com/home-assistant/frontend/issues/13748 .

But now, If we change entity_id of the script (for example, from ```script.123123123``` (default) to ```script.myownid```) script doesnt re-register himself as service.
In service-calls (in automations or developer tools) we still have ```script.123123123``` in services list (which was supposed to disappear), and there is no ```script.myownid``` in that list.

### Describe the behavior you expected

Script ID and service-call name must be the same 

### Steps to reproduce the issue

1. Create any script with default ID
2. Change ID to any your own
3. Search for old and new IDs in services list

### What version of Home Assistant Core has the issue?

2022.10.1

### What was the last working version of Home Assistant Core?

2022.08 probably

**Comment by fraintt** [comment]
I´m not that good in coding, but I think the issue is somewhere here:

[https://github.com/home-assistant/frontend/blob/dev/src/dialogs/more-info/ha-more-info-dialog.ts](url)

```
private _gotoEdit() {
    const stateObj = this.hass.states[this._entityId!];
    const domain = computeDomain(this._entityId!);
    let idToPassThroughUrl = stateObj.entity_id;
    if (EDITABLE_DOMAINS_WITH_ID.includes(domain) || domain === "person") {
      idToPassThroughUrl = stateObj.attributes.id;
    }

navigate(`/config/${domain}/edit/${idToPassThroughUrl}`);
    this.closeDialog();
  }

```
It fetches the "wrong" entity id only for scripts, maybe caused by this: 
```
export const EDITABLE_DOMAINS_WITH_ID = ["scene", "automation"];
/**
 * Entity Domains that should always be editable; {@see shouldShowEditIcon}.
 * */
export const EDITABLE_DOMAINS = ["script"];

```

from here: 
[https://github.com/home-assistant/frontend/blob/dev/src/dialogs/more-info/const.ts](url)

If somebody better than me could do a PR, it would be perfect, I hope I helped a little bit.

**Comment by chertvl** [comment]
Any news please? :(
