### ISSUE TITLE
Selecting target in service call missing... again

### ISSUE THREAD

**Issue by chertvl** [home-assistant/frontend#14049]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I still sometimes cant select targets with GUI for services in automation actions and in developer-tools page.
There is no fix for that issue in https://github.com/home-assistant/frontend/issues/13332 .

Sometimes target selection buttons wasnt displayed for light.* services, sometimes for switch.* or any other.
For example, there is some screenshots taken at different days on 2022.10.х release.

``` light,  camera``` services doesnt show targets, but ```switch.``` is works,  taken  3 days ago:

![image](https://user-images.githubusercontent.com/38353584/194708326-29916ba3-1cad-40ba-86bc-6a596d3bfcd1.png)

```switch, counter``` doesnt not show targets for today, but ```light, camera``` today works instead of previous screenshot.

![image](https://user-images.githubusercontent.com/38353584/194708420-774b726b-1823-4874-af48-1ba481872d41.png)

### Describe the behavior you expected

It would be great to have target selectors in all services.

### Steps to reproduce the issue

1. Get some luck
2. Try to make automation with UI, try several different services (light, switch, camera, counter, etc...)

### What version of Home Assistant Core has the issue?

2022.10.1

### What was the last working version of Home Assistant Core?

2022.7 probably

**Comment by brightdroid** [comment]
I can confirm this issue in HA 2022.12.4

**Comment by chertvl** [comment]
![image](https://user-images.githubusercontent.com/38353584/230468589-59c86461-3165-4914-9b7a-bd1823fa3da0.png)
![image](https://user-images.githubusercontent.com/38353584/230468725-17795bc2-31b9-4940-bd3d-de39c5914c47.png)
![image](https://user-images.githubusercontent.com/38353584/230468817-598ab854-1397-428a-a7fd-18301da4e2ea.png)

Still persist.
Today camera.*, alarm_control_panel.*, input_boolean.* services didnt show selectors with areas/devices/entities.

Home Assistant 2023.4.0
Supervisor 2023.04.0
Operating System 10.0.rc2
Frontend 20230405.0 - latest

**Comment by GvdbW** [comment]
This looks the same as #15885

**Comment by chertvl** [comment]
Issue isnt persist in 2023.5,
will look into it and will close issue in several weeks.

**Comment by chertvl** [comment]
> Issue isnt persist in 2023.5, will look into it and will close issue in several weeks.

Looks like its gone.
