### ISSUE TITLE
Tags save in UI. However, viewing them shows no actions. 

### ISSUE THREAD

**Issue by iambucketdotcom** [home-assistant/frontend#14044]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Created Tag
Assigned action to tag
Wrote tag to phone/home assistant using Home Assistant companion app
Decided to change the action for that tag
changed the action
saved it
tag worked
decided i liked the old action better - noticed tag action was blank - tested tag... Tag worked, despite no action.
created new action, tried to verify action - action was missing. However scanning the tag, would fire the NEWLY assigned action.
Checked entities to find many entries because like a dumby i just kept retrying and retrying.

### Describe the behavior you expected

Expected TAG Actions to display when the tag properties are opened. Expect to be able to save tag without having to rename it when it's brand new.

### Steps to reproduce the issue

Discovered this while editing the action of an already existing tag. However, this occurs for new or existing tags. 
1.Settings
2.Tags
3.Add Tag
4.Name Tag - Blink
5. Create Automation with Tag
6. Click - Create Automaiton with tag
7. TRIGGERS: - When a tag is scanned - Choose Tag named Blink for example.
7. Condition - No Condition required, does not change outcome.
8. Actions -> Add Action -> Device - Master Bedroom Light - Action - Turn off Master Bedroom Light
9. Click Save
10. Asked to rename - Keep the same name or rename as new - doesn't matter
11. Re-Enter rag properties for "Blink" - Saved properties are missing. 
12. Lather - Rinse Repeat
13. . Search by "tag_" - find MULTIPLE copies of the same tag that I've tried to save over and over because it's missing.
...
![2022-10-07_18-04-16](https://user-images.githubusercontent.com/95238513/194669451-af50bb50-c386-4dd3-9905-927581074657.png)
![2022-10-07_18-03-47](https://user-images.githubusercontent.com/95238513/194669462-d67204fc-83f0-441c-a982-8cb351649ec0.png)

### What version of Home Assistant Core has the issue?

Home Assistant 2022.10.1

### In which browser are you experiencing the issue with?

Mac Companion 2022.387, PC edge 105.0.1343.53, MAC firefox 105.0.2, iPhone Companion App 2022.8 

### Which operating system are you using to run this browser?

macOS Monterey, Windows 10 21h2, iOS16

### Additional information

Have rebooted HA multiple times, tried multiple computers and devices to ensure I wasn't going nuts. The same occurs on a virtual home assistant install i tested on a synology docker.

**Comment by sowbug** [comment]
Same here. Raspberry Pi HA installation.
