### ISSUE TITLE
Helper - Integration - Riemann sum integral sensor - Cannot change method after creation (left, right, trapezoidal)

### ISSUE THREAD

**Issue by chadbaldwin** [home-assistant/frontend#14066]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating a new Helper using the "Integration - Riemann sum integral sensor" helper you can set

- Integration Method (left, right, trapezoidal)
- Precision (integer)
- Metric prefix (none, k, M, G, T)
- Time unit (s, min, h, d)

However, once the helper has been submitted and the entity created, the only setting you can view or edit is the "Precision". All other settings are hidden and cannot be viewed or changed.

![image](https://user-images.githubusercontent.com/16479446/195183817-e778d0f5-0fb7-4d48-84cb-dc967707d7d7.png)

### Describe the behavior you expected

I expect the ability to _at least_ see the settings, if for some reason those cannot be edited after creation. However, if they are editable, then there should be the ability to change those settings.

### Steps to reproduce the issue

1. Navigate to Settings > Devices & Services > Helpers
2. Click "+ Create Helper"
3. Click "Integration - Riemann sum integral sensor"
4. Fill out form and click submit
5. Select newly created helper from list of helpers
6. Select "Settings" tab
7. Click "Integration - Riemann sum integral sensor options"

There you will find the _only_ option available is the "Precision"

### What version of Home Assistant Core has the issue?

2022.10.3

### In which browser are you experiencing the issue with?

Google Chrome 105.0.5195.127 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Microsoft Windows 10 Enterprise (10.0.19044)

**Comment by karwosts** [comment]
I believe this issue needs to be reported against core, specifically the `integration` component,  not frontend. 

Based on my understanding individual integrations publish a ConfigFlow that is run when it is first created, and they may optionally have an OptionsFlow that runs when user wants to change options after the fact. 

All the frontend can do when you push that button is call up the OptionsFlow form published by the Riemann sum integration. It is that integration that decides what fields to populate in its OptionsFlow, and it is that integration that has decided only to include the precision on that form. A change to the core integration would be required for it to support more OptionsFlow options. 

```

OPTIONS_SCHEMA = vol.Schema(
    {
        vol.Required(CONF_ROUND_DIGITS, default=2): selector.NumberSelector(
            selector.NumberSelectorConfig(
                min=0, max=6, mode=selector.NumberSelectorMode.BOX
            ),
        ),
    }
)

CONFIG_SCHEMA = vol.Schema(
    {
        vol.Required(CONF_NAME): selector.TextSelector(),
        vol.Required(CONF_SOURCE_SENSOR): selector.EntitySelector(
            selector.EntitySelectorConfig(domain=SENSOR_DOMAIN)
        ),
        vol.Required(CONF_METHOD, default=METHOD_TRAPEZOIDAL): selector.SelectSelector(
            selector.SelectSelectorConfig(options=INTEGRATION_METHODS),
        ),
        vol.Required(CONF_ROUND_DIGITS, default=2): selector.NumberSelector(
            selector.NumberSelectorConfig(
                min=0,
                max=6,
                mode=selector.NumberSelectorMode.BOX,
                unit_of_measurement="decimals",
            ),
        ),
        vol.Required(CONF_UNIT_PREFIX, default="none"): selector.SelectSelector(
            selector.SelectSelectorConfig(options=UNIT_PREFIXES),
        ),
        vol.Required(CONF_UNIT_TIME, default=UnitOfTime.HOURS): selector.SelectSelector(
            selector.SelectSelectorConfig(
                options=TIME_UNITS, mode=selector.SelectSelectorMode.DROPDOWN
            ),
        ),
    }
)
```

**Comment by heimwege** [comment]
cross link to the respective core issue: https://github.com/home-assistant/core/issues/100650
