### ISSUE TITLE
Devices with suggested areas do not have the area selected in newly added devices window

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#14089]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When you add a new integration, it will show you a list of all new devices and you can add them to areas. If those devices had suggested areas, those areas are selectable in the dropdown, but they are not selected in the UI, they are set correctly in device registry. Not changing an area will keep them correct.

### Describe the behavior you expected

The dropdown should have the current area selected.

### Steps to reproduce the issue

1. Add Hue integration
2. See how lights are not set to an area
3. Click finish and see in device registry how they have an area assigned.

### What version of Home Assistant Core has the issue?

latest

**Comment by piitaya** [comment]
It seems to be fixed with https://github.com/home-assistant/frontend/pull/14383 ?
