### ISSUE TITLE
Number entry form fields cut off / numbers invisible in  http://[ha host]/config/zwave_js/node_config/[device ID]

### ISSUE THREAD

**Issue by Chef-de-IT** [home-assistant/frontend#14096]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Sine update to Home Assistant 2022.10.3 Frontend 20221010.0 - latest, certain numerical entry fields are out of alignment (regardless of browser window) and don't show the actual number. If I click on the field, hit CTRL+A (select all), I can type in the new number "blind" and it appears to take effect

In addition, the various numbered device config options on this screen appear out-of-numerical-order, and even in varying orders among devices of the same type.

![Screenshot 2022-10-14 at 15-04-40 Settings – Home Assistant](https://user-images.githubusercontent.com/115595180/195931997-26a32c58-dde1-4fc1-89da-f29c8b74e388.png)

### Describe the behavior you expected

I want to see what value I'm editing :)

### Steps to reproduce the issue

1. in HA UI, open settings
2. devices and settings
3. click on device count under Z-Wave JS add-on
4. pick any Z-Wave device
5. under Device Info, click Configure
6. See any numerical entry fields

### What version of Home Assistant Core has the issue?

2022.10.3

### What was the last working version of Home Assistant Core?

1 month ago it was fine - not sure as to the last working version

### In which browser are you experiencing the issue with?

Firefox 104.0.2

### Which operating system are you using to run this browser?

Windows 10

### Javascript errors shown in your browser console/inspector

```txt
none
```

**Comment by karwosts** [comment]
Fixed by #14788
