### ISSUE TITLE
Incorrect Time in Home Assistant

### ISSUE THREAD

**Issue by towerberlin** [home-assistant/frontend#14091]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Incorrect time display in the Home Assistant log

Left Chrome 106.0.5249.119
Right LibreWolf 105.0.3.-1

The difference is two hours.

![image](https://user-images.githubusercontent.com/1484427/195760921-66c2b43b-9201-4077-876e-09c970a7e601.png)

### Describe the behavior you expected

Correct Time logged

### Steps to reproduce the issue

Open Log in different browser

### What version of Home Assistant Core has the issue?

Home Assistant 2022.10.3

### In which browser are you experiencing the issue with?

LibreWolf 105.0.3.-1

### Which operating system are you using to run this browser?

Win 11

**Comment by Quentame** [comment]
As the time is working on Chrome and not in LibreWolf, maybe LibreWolf isn't sending your TimeZone to HA so it fallback to UTC ?

Perhaps, are your browser timezone settings the same ?

**Comment by towerberlin** [comment]
Thanks, good hint. I have solved the problem for me with: 

https://addons.mozilla.org/en-GB/firefox/addon/spoof-timezone
