### ISSUE TITLE
computeRTL exception breaking ZHA configuration editing

### ISSUE THREAD

**Issue by ahaverty** [home-assistant/frontend#14106]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On trying to update my ZHA configuration, by editing a field, and clicking "update configuration", nothing happens.
When I refresh the page, the configuration hasn't been updated.
The reason I'm reporting as a UI issue is because it seems to be an exception with computeRTL [here](https://github.com/home-assistant/frontend/blob/0a3fa3e218ab7213bde003c28399eb81c070491f/src/panels/config/integrations/integration-panels/zha/zha-config-dashboard.ts#L210).

Perhaps this exception is preventing the form from submitting?

<img width="700" alt="image" src="https://user-images.githubusercontent.com/2920947/196053137-85bcd4a5-e4ea-44c3-9b42-64f674996498.png">

### Describe the behavior you expected

The ZHA configuration to update, or report an error.

### Steps to reproduce the issue

1. Open ZHA integration
2. Modify a config field such as 'default light transition time'
3. Click "update configuration" button

### What version of Home Assistant Core has the issue?

2022.10.4

### In which browser are you experiencing the issue with?

Google Chrome Version 106.0.5249.119 (Official Build) (arm64)

### Which operating system are you using to run this browser?

macOS Ventura 13.0 Beta 

### Javascript errors shown in your browser console/inspector

```txt
zha-config-dashboard.ts:210 Uncaught (in promise) {code: 'unknown_error', message: 'Unknown error'}code: "unknown_error"message: "Unknown error"[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
value @ zha-config-dashboard.ts:210
await in value (async)
handleEvent @ styles.ts:370

```
```


### Additional information

_No response_

**Comment by dmulcahey** [comment]
Do you have an alarm control panel paired?
