### ISSUE TITLE
Edge refreshing UI constantly

### ISSUE THREAD

**Issue by stephenmhall** [home-assistant/frontend#14103]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On Edge since yesterday the UI is constantly refreshing be it in Overview or Energy pages. This does not happen in Firefox. The UI will refresh over and over then finally give a blank page needing a F5 to get the page back.

### Describe the behavior you expected

not to refresh all the time

### Steps to reproduce the issue

1. Just go to a page
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.10.4

### In which browser are you experiencing the issue with?

Edge 107.0.1418.8 (Official build) dev (64-bit)

### Which operating system are you using to run this browser?

Win 11

**Comment by vladyspavlov** [comment]
I can confirm it.
Edge 107.0.1418.8 (Official build) dev (64-bit)

**Comment by backerman** [comment]
Does not happen on dev channel but clicking a tab in a card or typing a key in e.g. the add an integration search causes the modal to disappear with p=0.5-ish.

I do see this backtrace generated:
ncaught (in promise) Error: getTranslators: detection is already running
    at Zotero.Translate.Web.<anonymous> (translate.js:1091:45)
    at Zotero.Translate.Web.getTranslators (promise.js:36:17)
    at Object.init (inject.js:105:25)
    at Object.historyChanged (inject.js:705:21)
    at messageListener (messaging_inject.js:122:50)
    at messaging_inject.js:132:6

108.0.1438.1 (Official build) dev (64-bit) 
Home Assistant 2022.10.4
Supervisor 2022.10.0
Operating System 9.2
Frontend 20221010.0 - latest

**Comment by PublicCodeRobin** [comment]
Same here on Opera v 93.0.4575.0. Chromium 107.0.5304.18.
Very annoying when doing things that need careful configuration.

**Comment by vladyspavlov** [comment]
Seems to be fixed in 108.0.1462.2 dev
