### ISSUE TITLE
Wrong redirection to scripts editor 

### ISSUE THREAD

**Issue by fraintt** [home-assistant/frontend#14115]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After updateing from 2022.09.04 to 2022.10.04 I noticed that when I wanted to edit an script (not happening with scenes, or automations) it redirects me to the wrong url…

WORKING: Redirect from within Settings->Automation&Scenes->Scripts
https://fqdn/config/script/edit/<entity_id>

NOT WORKING: (wrong URL)
From within the “search” top right, or when displaying the entity information in the dashboard.
[https://FQDN/config/script/edit/script.<entity_id](https://fqdn/config/script/edit/script.%3Centity_id)>

I´m very confident in 2022.09.4 it worked.

### Describe the behavior you expected

Correct redirection to the script editor without getting the message "Only scripts inside scripts.yaml are editable.”

### Steps to reproduce the issue

1. Search for any script in the top right corner with the search tool or try to edit an script from within an dashboard entity information dialog
2. Go to the pencil in the top right corner to edit the script
3. You will be redirected to the wrong url. 
...

### What version of Home Assistant Core has the issue?

2022.10.04

### What was the last working version of Home Assistant Core?

2022.09.04

### In which browser are you experiencing the issue with?

Firefox 105.0.3 (64-Bit), Edge Version 106.0.1370.42

### Which operating system are you using to run this browser?

Windows 10 21H1

**Comment by fraintt** [comment]
I´m not that good at coding but maybe the issue is here:
[https://github.com/home-assistant/frontend/blob/dev/src/dialogs/more-info/ha-more-info-dialog.ts](url)
```
 private _gotoEdit() {
    const stateObj = this.hass.states[this._entityId!];
    const domain = computeDomain(this._entityId!);
    let idToPassThroughUrl = stateObj.entity_id;
    if (EDITABLE_DOMAINS_WITH_ID.includes(domain) || domain === "person") {
      idToPassThroughUrl = stateObj.attributes.id;
    }

    navigate(`/config/${domain}/edit/${idToPassThroughUrl}`);
    this.closeDialog();
  }
```
Which fetches the wrong entity id for scripts maybe from here:
[https://github.com/home-assistant/frontend/blob/dev/src/dialogs/more-info/const.ts](url)
```
export const EDITABLE_DOMAINS_WITH_ID = ["scene", "automation"];
/**
 * Entity Domains that should always be editable; {@see shouldShowEditIcon}.
 * */
export const EDITABLE_DOMAINS = ["script"];
```

If somebody better than me would do a PR, it would be perfect.

**Comment by sdrapha** [comment]
I'm very suspicious of the root cause been this commit: #13817

When it dropped the use of ```ComputeObjectId```

![image](https://user-images.githubusercontent.com/25059996/197049883-7ea6bf04-daef-4934-8b70-c551e273a7f4.png)


Which was previously responsible for splitting the **domain** from the **entity_id** string
![image](https://user-images.githubusercontent.com/25059996/197050251-68abd084-3541-45b2-ad79-9dea45f00d38.png)

The new ```sriptId``` that was put in place, doesn't seem to have any domain splitting method anywhere

**Comment by sdrapha** [comment]
I usually see a BOT that tags the codeowners, but that didnd't happened in this issue, so I hope I'm helping (and not bothering) by taging @piitaya and @bramkragten whoom made and reviewed the PR which seems the cause of the issue

**Comment by fraintt** [comment]
Mhm, thanks for testing this, really appreciate it. 
I thing I remember that everytime I wanted to edit a script, it worked, for sure for the automations, and I think I edited also some scripts this way. Anyway if it worked or not, it should be fixed as it is redirecting wrong.
Thank you again!

**Comment by piitaya** [comment]
We don't use script entity id anymore but unique_id (and it's the key of the script in yaml). 
I thought I made the changes everywhere but I forgot to change it in the more-info. We will fix that! Thanks for sharing and debugging!
