### ISSUE TITLE
Non-unique trigger IDs displayed multiple times in the "Triggered by" dropdown

### ISSUE THREAD

**Issue by jakubka** [home-assistant/frontend#14111]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When multiple triggers in an automation use the same trigger ID (that's a supported feature), the UI of the "Triggered by" condition shows that ID multiple times:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/4806497/196262601-6254aea0-e4de-4c7c-a001-f6e5edb1a593.png">

That's confusing.

### Describe the behavior you expected

It should just show unique trigger IDs.

### Steps to reproduce the issue

1. Create automation with multiple triggers with the same ID. Such as this one: 
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/4806497/196263059-88ba97dd-3d87-4af6-9052-a5d6d3abacbb.png">

2. Add a trigger condition 
<img width="308" alt="image" src="https://user-images.githubusercontent.com/4806497/196263154-9314b929-d3b5-47e1-a2f6-f7c4f0d2a7b6.png">

### What version of Home Assistant Core has the issue?

2022.10.1

**Comment by bdr99** [comment]
Opened https://github.com/home-assistant/frontend/pull/14122 to fix this issue.
