### ISSUE TITLE
Light icons not respecting state_color: false in entities card

### ISSUE THREAD

**Issue by krisnoble** [home-assistant/frontend#14129]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If I have a light being displayed in an entities card, the icon always reflects the light's colour even if I have the state_color option set to false. Other entities such as switches do respect the setting.

In this screenshot the slideshow and air purifier are switches, the DJ screen and printer light are lights - in this case RGBW strips running WLED but the same thing happens with other lights including non-RGB ones.

<img width="750" alt="Screenshot 2022-10-19 at 14 44 59" src="https://user-images.githubusercontent.com/872971/196709749-dfdfa2a0-3eb6-4a88-a940-d5b24869ba2f.png">

### Describe the behavior you expected

Expected behaviour is for the light icons to be the default colour as with other entities

### Steps to reproduce the issue

1. Add a light icon to an entities card
2. Set the state_color option to false
3. Change the light colour / state
4. See that the icon changes to match despite the setting

### What version of Home Assistant Core has the issue?

Home Assistant 2022.10.4

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - entity: light.printer_light
  - entity: switch.air_purifier
state_color: false
```

**Comment by krisnoble** [comment]
Still happening on 2023.1.5 / Frontend 20230110.0 - latest

**Comment by Flavien** [comment]
Still happening on 2023.2.

**Comment by krisnoble** [comment]
Still occurring in 2023.4.6 / 20230411.1, I'm liking Piitaya's suggestion in Flavien's PR though

**Comment by bdr99** [comment]
This issue still exists in 2023.7.

![image](https://github.com/home-assistant/frontend/assets/2292715/3fbce63d-7427-4ae7-b01f-ab50d468ce94)

**Comment by krisnoble** [comment]
Still occurs in 2023.10.5 / Frontend 20231005.0

**Comment by krisnoble** [comment]
Still present in 2024.1.5

**Comment by steverep** [comment]
Just to confirm, is `state_color` explicitly set to false as in the yaml above, or is it left undefined because the default is documented as false?

**Comment by ildar170975** [comment]
@steverep 
In examples above the `state_color` option is explicitly set to `false`.

**Comment by steverep** [comment]
@ildar170975 yes I understand - I was simply asking for confirmation.  The badge has an exception for lights when it's undefined, but it's supposed to work when false.

Also, is the issue the same in 2024.2?

**Comment by ildar170975** [comment]
@steverep 
> Also, is the issue the same in 2024.2?

I myself cannot consider the current behaviour as an "issue".
Currently in 2024.2 in Entities card an icon of a `light` entity does not depend on `state_color` (`true` or `false`).
An icon's color depends only on a corresponding `light` entity.

**Comment by ildar170975** [comment]
@steverep 
There is a nuance:
1. If the `state_color: false` is defined on a card's level - it does not affect on a `light` icon.
2. The the `state_color: false` is defined on a row level - it does affect: the icon becomes "dark-blue" (if either ON or OFF).

**Comment by steverep** [comment]
@ildar170975 thanks for pointing out the nuance.  Yes, `false` is incorrectly not propagated to the entities.  I'll submit a fix.
