### ISSUE TITLE
Pasting Icon Text name in Entity Icon Field Causes Freeze of Dashboard.

### ISSUE THREAD

**Issue by Pole04** [home-assistant/frontend#14147]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When adding an entity card to a grid I copied the text name for an icon from another entity card and attempted to paste it in the new one.  This causes the dashboard to hang up and become unresponsive.  The browser will timeout and I need to refresh and reopen the dashboard and edit it.

### Describe the behavior you expected

You should be able to paste the text name for an entity into the Icon field of the entity card.

### Steps to reproduce the issue

1. Add grid to dashboard with 2 columns
2. Add entity card to to column 1 and pick an icon
3. Copy the text for the icon name
4. Add entity card to column 2.
5. Attempt to paste the text name in your clipboard to the icon field.
6. Browser hang and you must refresh to regain control.
...

### What version of Home Assistant Core has the issue?

Frontend 20221010.0

### In which browser are you experiencing the issue with?

Chrome, Firefox

### Which operating system are you using to run this browser?

Windows 10 Pro 10.0.19044 Build 19044

### State of relevant entities

```txt
none
```

### Problem-relevant frontend configuration

```yaml
none
```

### Javascript errors shown in your browser console/inspector

```txt
none Freezes
```

**Comment by steverep** [comment]
Upgrade for dependency didn't always fix so reopening.  Issue fix is still in progress.
