### ISSUE TITLE
Automation State and Attribute value auto-completion only works on some entities

### ISSUE THREAD

**Issue by yavinmaster** [home-assistant/frontend#14150]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The State and Attribute value auto-completion function which was introduced in 2022.9 only appears to work on certain entities types. I have serval entities which only show options of "unavailable" and "unknown" where they have many other states. These are the entities where autocomplete would be most useful. Some examples of entities which don't work are:
Wallbox Portal Status Description, IKEA 5 way remote action (coming from Zigbee2MQTT), Aqara smart home cube action (coming from Zigbee2MQTT), date and time senors.

Are these limitations in how the integrations have been coded (does something need to be added to declare all states)? Can the system create a list of autocomplete options based on historic states (ie the way we have to do it manually)?

### Describe the behavior you expected

All possible states to be available from auto-complete within automation, maybe using historical values to populate the list.

### Steps to reproduce the issue

1.Create New Automation, selecting blank template
2. Select a trigger of "state"
3. Select an entity from a Zigbee2MQTT device (or any others I mention above)
4. Select the dropdown next to "To" - you will see that the only options are "Unavailable" and "Unknown".
...

### What version of Home Assistant Core has the issue?

2022.10.4

### What was the last working version of Home Assistant Core?

Never

### In which browser are you experiencing the issue with?

Google Chrome Version 106.0.5249.119

### Which operating system are you using to run this browser?

Windows 10, Android App

### Additional information

This was originally raised as #80428 but it was suggested that it wasn't a backend issue.

**Comment by HeedfulCrayon** [comment]
This is still an issue and should not be closed
