### ISSUE TITLE
Menu is missing on the helper page (Integrations/Devices/Entities are fine)

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/frontend#14167]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I want to reactivate helpers I've disabled in the past, but I cannot open the corresponding menu, since the button isn't there.

![Screenshot from 2022-10-23 08-26-39](https://user-images.githubusercontent.com/614929/197377552-133eafd3-2f39-4ae7-b08a-ba53739a2d79.png)

The other tabs (Integrations/Devices/Entities) are fine:

![Screenshot from 2022-10-23 08-26-16](https://user-images.githubusercontent.com/614929/197377589-7ee37f85-c839-4a75-b5e5-c0b55e268344.png)

![Screenshot from 2022-10-23 08-26-55](https://user-images.githubusercontent.com/614929/197377612-93cfa711-ab61-4e1c-acea-15f0bd6b012a.png)

![Screenshot from 2022-10-23 08-26-48](https://user-images.githubusercontent.com/614929/197377621-56fbfd38-4fb6-4098-88ad-95d64c5b9382.png)

### Describe the behavior you expected

The menu button should be rendered like on the other tabs, which allows to deactivate the filter and thus show the deactivated elements in the list.

### Steps to reproduce the issue

1. Switch to the helpers page.
2. No menu button appears on the page.

### What version of Home Assistant Core has the issue?

core-2022.10.5

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Firefox 106.0 / Chromium 106.0.5249.119 (official builds)

### Which operating system are you using to run this browser?

Arch Linux latest

### State of relevant entities

```txt
None
```

### Problem-relevant frontend configuration

```yaml
None
```

### Javascript errors shown in your browser console/inspector

_None:_

![Screenshot from 2022-10-23 09-27-52](https://user-images.githubusercontent.com/614929/197379779-5ed7e30b-7c12-47ab-b17b-17499b85aef2.png)

### Additional information

This has been [reported in the forum](https://community.home-assistant.io/t/helper-for-input-entities-disappear-when-disableling/201576) as early as Jun '20.

**Comment by karwosts** [comment]
Note you can reactivate disabled helpers from the entities page, just not from the helpers page. 

While a filter menu for helpers would certainly be nice, it looks like no code exists yet for that, so it would probably be a non-trivial amount of work to implement it. Just noting that it's not a "bug" that it is missing, it's just that nobody has implemented such a feature yet.

**Comment by gravelfreeman** [comment]
I'm having this exact same issue, why would this even get close? I mean it must be a quick fix.

**Comment by gravelfreeman** [comment]
The issue remains closed even we both replied. Anyone looking for a quick fix is that you can find your disabled/hidden Helpers in the Entities page.

**Comment by EugenMayer** [comment]
Not sure  why this issue is ignored for such a long time. The names workaround is at best a work-around.

Not showing disabled entities is something that is most probably useful by default, since one deactivates not needed sensors/buttons for a longer time.

Deactivating helpers is most probably something temporary, showing them, even if disabled, should be the default.

Beside the discussion what the default handle should be, one should be able to select "show disabled" in the filter at least.

Is there any way to move this issue forward?

**Comment by aisbergde** [comment]
I see the use of bots that automatically close issues without the issues being resolved or anyone dealing with them as a lack of respect for those who report issues. Closing issues should be done deliberately by a human. It is demotivating to give feedback that ends up in the trash without being processed. Then you can save yourself the trouble.
