### ISSUE TITLE
related entities, group link should take you to the specific group

### ISSUE THREAD

**Issue by crackers8199** [home-assistant/frontend#14190]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

i have several switch groups set up to help control my security lighting and holiday lights. these groups may change, depending on the season or holiday light show i'm running.

when i click the switch on my dashboard, i can go to related entities and see that it is a group switch - however, when i click on that group link, it takes me to the integrations page and stops there rather than take me to the actual group settings. 

### Describe the behavior you expected

this link should take me to the helper page at a minimum, and taking it one step further should also open the window for editing the group in question (to make it easier to add / remove members from the group, or change group settings).

### Steps to reproduce the issue

1. create a switch group
2. add switch group to dashboard
3. view dashboard, click title for switch group
4. in popup, click related
5. in related section, click the link for the group

### What version of Home Assistant Core has the issue?

Home Assistant 2022.10.3
Frontend 20221010.0 - latest

**Comment by karwosts** [comment]
Still an issue.
