### ISSUE TITLE
2022.11 b0 - Ugly white card borders

### ISSUE THREAD

**Issue by mehhhhhhhhhhhhhhhhhhhhhhhhhh** [home-assistant/frontend#14204]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Cards now have white borders in dark mode, which negatively impact the aesthetic of front end dashboards. 

### Describe the behavior you expected

All front end cards have white borders when in dark mode. 

### Steps to reproduce the issue

1. None
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.11 b0

### What was the last working version of Home Assistant Core?

2022.10.5

### In which browser are you experiencing the issue with?

Safari & Chrome

### Which operating system are you using to run this browser?

MacOS Big Sur, Ubuntu

**Comment by SmarterHomeLife** [comment]
I'm also getting a thin border around all elements on my dashboards after upgrading to 2022.11.0b0, also showing in Chrome on Android and the HA app on Android.

**Comment by Mincka** [comment]
I don't know if it's the `border-style: solid` that's breaking all my dashboards or something else.
All the cards are now taking more place. This should not be the case in my opinion.

```
:host {
    background: var( --ha-card-background, var(--card-background-color, white) );
    box-shadow: var(--ha-card-box-shadow, none);
    box-sizing: border-box;
    border-radius: var(--ha-card-border-radius, 12px);
    border-width: var(--ha-card-border-width, 1px);
    border-style: solid;
    border-color: var( --ha-card-border-color, var(--divider-color, #e0e0e0) );
    color: var(--primary-text-color);
    display: block;
    transition: all 0.3s ease-out 0s;
    position: relative;
}
```
Before:
![image](https://user-images.githubusercontent.com/6184289/198206999-283d688e-cc67-4a90-83e5-ec9e74fa7c8c.png)

After:
![image](https://user-images.githubusercontent.com/6184289/198207069-692e1e3b-1040-4f11-a1ac-9189e0af5b04.png)

**Comment by SmarterHomeLife** [comment]
If you add 'ha-card-border-width: 0px' to your theme file it will remove all the borders until a permanant fix is released.

**Comment by Kertz1954** [comment]
This change of appearance is due to the removal of the default box-shadow and the increase of the default border-radius from 4px to 16px (in most cases).

This results in a unwanted visable border-radius and destroys the alignment of height and width sizes.

For the dev (name withheld) that decided to make these changes, I hope you have a good place to hide when this is released today in 2022.11.0 as you are about to upset a very very high percentage of existing users who are not going to appreciate that there dashboards/tabs are no longer in alignment.

**Comment by ildar170975** [comment]
Now users will have to create a custom theme only to fix the new design.
This is not a good practice.

**Comment by Mincka** [comment]
I think they were stuck with the old design and now they want to introduce mushroom cards (starting with Tile), they need to change global styling with small touches. It must be complicated for them to take such choices since they know that any little change will break dashboards of users. Still, I personally think that the new default border radius is way to big.

**Comment by Imoriarty** [comment]
I just hate that the onus is always on the users to figure out what changed, and how to revert or fix the changes. A simple addition to the patch notes about a breaking change to the design would go a long way. Even better, provide some simple CSS in the patch notes to revert the change in a custom theme until people have the time to migrate.

But, no, instead it's a surprise to most users who haven't been following the design changes, and a sudden realization that what was supposed to be a simple version update I didn't expect to spend time on is (was) yet another fiddly task, for really no reason.

**Comment by CumpsD** [comment]
![image](https://user-images.githubusercontent.com/1201644/199706686-6b1767cd-88f5-47b6-a012-d72344c030a8.png)

Sometimes borders also appear on container cards like `custom-mod-card`

**Comment by bkr1969** [comment]
Same problem here. The borders are stupid.  There has to be a way to remove them.

**Comment by Imoriarty** [comment]
@bkr1969 

SmarterHomeLife's hack worked for me:
> If you add 'ha-card-border-width: 0px' to your theme file it will remove all the borders until a permanent fix is released.

I placed it in my themes file (the filename might vary based on your particular setup), and refreshed my themes by going to Developer Tools > Services > Home Assistant Frontend: Reload themes option, and hitting the Call Service button.

You may need to experiment to find the best place for the hack for you, and I suggest making a comment about it in your file, should you want to revert it sometime in the future.

**Comment by bkr1969** [comment]
That didn't do anything for me.  Where exactly did you place that line?  I tried it in the Global and Cards section with no luck.

**Comment by InfinityATX** [comment]
> That didn't do anything for me. Where exactly did you place that line? I tried it in the Global and Cards section with no luck.

I had to restart HA for the change to take effect, but keep an eye on your theme repository, they are updating with the fix pretty quickly.

**Comment by mehhhhhhhhhhhhhhhhhhhhhhhhhh** [comment]
Worked for me.  It doesn't require a restart if you use the frontend.reload_themes service.

**Comment by mehhhhhhhhhhhhhhhhhhhhhhhhhh** [comment]
> I've restarted both just the themes and entire HA. No difference. Please tell me where in the code you placed the line.

I placed the line directly under the name of each theme.  I’m using iOS-themes, which has several different themes listed.  

To make it easy, I used text replace to replace the "# Global" comment with "ha-card-border-width: 0px" then saved & reloaded my themes.

**Comment by bkr1969** [comment]
That did it.  Thanks!

**Comment by jvcsw** [comment]
In general I'm very happy with the HA, but these changes break designs that have cost many hours to thousands of users. I think this change has not been well thought out.

**Comment by ildar170975** [comment]
Removing shadows and adding borders. 
Huge radius for corners. 
Icons with a background of “mushroom style”. 
This is a new glory future (facepalm).

**Comment by ildar170975** [comment]
I mean - there is a big probability that this may happen. 
The corresponding issue “why the new tile card look different?” was closed. 
Also, some users are agree with new changes. 
Some users think that there is no need to worry about changes - “may be customized by themes and card-mod”. 
Surely I am worried about this trend.

**Comment by ltjessem** [comment]
This is just business as usual. For years. There's a major disconnect between what the devs like and what the majority of the userbase want.
The insistence on not allowing users options other than third-party themes etc. just makes for more things to break in a future update.

Strap in, we're just in for the ride.

**Comment by andige** [comment]
This is really unbelievable.
Was it really so hard to at least warn the users about this unnecessary change?

btw: this is not only affecting user themes but also the standard theme, which looks completely awful now. Are you deliberately trying to scare new users away?

**Comment by ildar170975** [comment]
> Was it really so hard to at least warn the users about this unnecessary change?

I consider these changes as BREAKING.

**Comment by mehhhhhhhhhhhhhhhhhhhhhhhhhh** [comment]
> I consider these changes as BREAKING.

Agreed.  I’m baffled that they didn't add it to breaking changes.

**Comment by jvcsw** [comment]
What is really sad is that they ignore us.

**Comment by jvcsw** [comment]
Hi,

all this borders are new:

![imagen](https://user-images.githubusercontent.com/37216513/200566360-ce1b6b11-ff97-44a2-b04a-73da386f2eda.png)

This is just one example of many.

How can I get back to the previous view without borders?

**Comment by ltjessem** [comment]
> This is just preference and I think it would be very nice to have option to choose one from all three options.

The devs have said on multiple occasions that they don't like giving people options... So we're stuck with either whatever they like, or a third-party/self made theme that will eventually break in a future update.

**Comment by Aasikki** [comment]
> > This is just preference and I think it would be very nice to have option to choose one from all three options.
> 
> The devs have said on multiple occasions that they don't like giving people options... So we're stuck with either whatever they like, or a third-party/self made theme that will eventually break in a future update.

Which is perfectly reasonable as giving more options means more effort to keep all of the options up to date.

**Comment by ltjessem** [comment]
I understand that, especially in the context of theming. Heck, I even like the new look. This release however brought with it another unpopular change, the horribly inaccurate history card. Mine can travel backwards in time... 
![image](https://user-images.githubusercontent.com/10084953/200659777-0204a7b8-692d-431c-a02a-23e1a8307e61.png)

Both of these issues are basically told "this is how we like it, so that's how it going to be". The theming issue is cosmetic, and I can understand not wanting to maintain an old theme, though leaving it in as a legacy option for the time being shouldn't have been an issue. The graphing, now that is worse due to actually degrading functionality. The old graphs are still there so it costs them absolutely nothing to give the option to keep them in "more info". 

The community can only be treated that way for so long before it come back to bite them in the butt.

**Comment by ildar170975** [comment]
I repeated the same many times in Community. 
Once again. 
To restore the old look may - using a custom theme with old radius, old shadows and without a border - may NOT work. The latest changes in HA are not only about changing some themable variables - they are also about handling a border and shadow in cards. 
As a result - some custom cards now got a wrong border - for instance, mod-card, bar-card, stack-in-card (the latter has an “unofficial” fix, which only useful in SOME cases).
These three cards - are what I use and where I noticed bugs. Probably the latest HA changes resulted bugs in more cards. 
Ok, these are merely custom cards - which are not a headache for devs...

**Comment by jvcsw** [comment]
Hi,
Which solution has stack-in-card?

**Comment by ildar170975** [comment]
Go to stack-in-card repo, there is a PR.  
As I said, in some cases may not help.

**Comment by ildar170975** [comment]
Go to stack-in-card repo, there is a PR.  
As I said, in some cases may not help.

**Comment by darmach** [comment]
I also found new design with outline less appealing. To be honest - such borders on everything feel so designed 20 years ago...  Anyways, here's a fork of the old theme, you cna install that with HACS - works well so far.

https://github.com/ChristophCaina/home-assistant-theme-outline-edge

**Comment by jvcsw** [comment]
Interesting....

**Comment by piitaya** [comment]
I close the PR as the issues are about stack in card and PR has been open : https://github.com/custom-cards/stack-in-card/pull/47

**Comment by jvcsw** [comment]
In my case, this works.

https://github.com/custom-cards/stack-in-card/pull/47#issuecomment-1449475086
