### ISSUE TITLE
Venezuela Time Zone Not Correct

### ISSUE THREAD

**Issue by carival1960** [home-assistant/frontend#14205]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hey guys,

My name is Carlos Rivas. I' live in Caracas, Venezuela.

I've installed Home Assistant 2022.10.5 Frontend 20221010.0 - latest, on Ubuntu Server 22.04

FYI, since 1 May 2016, Venezuela is sharing a time zone with most of the Caribbean countries, at UTC -4.

Caracas, the capital of Venezuela, is currently almost exactly aligned with apparent solar time. 

In settings, Venezuelan (Caracas) time is UTC -4:30, which is incorrect. Please, correct that in a future update.

Thanks in advance...

Carlos A.

### Describe the behavior you expected

Venezuela (Caracas) Time Zone: UTC -4.

### Steps to reproduce the issue

1. Installation, local time settings.
2. 
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.10.5 Frontend 20221010.0 - latest

**Comment by leodrivera** [comment]
https://github.com/home-assistant/frontend/blob/dev/src/panels/config/core/ha-config-section-general.ts

The problem occurs because the HA front-end gets the timezone info from this json, which is out of date.

`import timezones from "google-timezones-json"`

**Comment by leodrivera** [comment]
Any updates?

**Comment by karwosts** [comment]
Have you tried submitting a change to google-timezones-json? It looks probably abandoned, but if you at least tried (and failed) to get a change accepted, that would probably give a good impetus to get this project to switch to something else. 

Possibly https://github.com/omsrivastava/timezones-list seems to be actively updated.

**Comment by karwosts** [comment]
I submitted the move to -4 into the upstream repository. It should be fixed next time it releases and we update the dependency.

**Comment by karwosts** [comment]
Believe this was fixed by https://github.com/home-assistant/frontend/pull/17321
