### ISSUE TITLE
"Scheduled maintenance" notice for non Nabu Casa users

### ISSUE THREAD

**Issue by Ex0danify** [home-assistant/frontend#14215]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Today a 'Scheduled maintenance' notice popped up in my Home Assistant instance in the settings menu.
Upon viewing the message it states something about 'a scheduled update of the Home Assistant Cloud infrastructure'.
I'm not a subscriber of Nabu Casa (I guess that it is related to it), so why should this maintenance Info pop up in my instance of Home Assistant.

Also it seems that I'm not the only one wondering about this ([Home Assistant forums](https://community.home-assistant.io/t/wth-is-this-scheduled-maintenance/480747))

### Describe the behavior you expected

Don't show information about Nabu Casa releated maintenance stuff to non-subscribers or at least state that it is related to Nabu Casa somewhere in the popup.

### Steps to reproduce the issue

1. Open Home Assistant
2. Go to the settinigs menu
3. Notice is right on top (as of 27th October 22)

### What version of Home Assistant Core has the issue?

core-2022.10.5

### In which browser are you experiencing the issue with?

Google Chrome  105.0.5195.127

### Which operating system are you using to run this browser?

Windows 10 21H2

### State of relevant entities

```txt
-
```

### Problem-relevant frontend configuration

```yaml
-
```

### Javascript errors shown in your browser console/inspector

```txt
-
```

**Comment by akula3** [comment]
one addition: independent nabucasa user or not, the message should disappear after scheduled time, but it didn't.
