### ISSUE TITLE
Long-term statistics in the entity dialogs - revert to old style?

### ISSUE THREAD

**Issue by TimoJJ** [home-assistant/frontend#14218]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using long term statistics for entity dialogs looks bad and confusing. Is there a selection/option to revert back to the old way? 

### Describe the behavior you expected

Just one clear (and sometimes boxy) line, like before.

### Steps to reproduce the issue

Open entity.

### What version of Home Assistant Core has the issue?

2022.11 b0

**Comment by ildar170975** [comment]
Probably statistics graph should present on a separate tab.

**Comment by tankdeer** [comment]
Something that I haven't seen mentioned is that history, by definition, is series of events that actually happened. Not a statistical analysis of said events. While that can certainly be useful in some scenarios, it is not a replacement for actual, unchanged history.

Personally I like the idea of having both available. Either on a separate tab, or as a "raw" data point on the same graph. But losing that raw data is a big oversight.

**Comment by martinhoess** [comment]
I think there are normally fewer use cases for the new representation than for the old representation.

In the thread there are some examples where you can see that it doesn't work or doesn't make much sense. 
Like this: https://community.home-assistant.io/t/2022-11-a-heck-of-a-release/483295/140?u=marh

Unfortunately, I don't know what the best solution would be to make "everyone" happy.

But I would have liked it much better if this had been built into the actual history page. This is where I often look at a long period of time (my recorder is set to 365 days), so it would be nice to have "min/max/mean/raw" but there is only "raw"
But this clashes again with the behavior that several entities are displayed in one chart (like if you select 3 temperature entities)

**Comment by tankdeer** [comment]
Another issue with this approach. I now have several sensors that have history, but not long term statistics. And so clicking on them yields a completely useless screen

![image](https://user-images.githubusercontent.com/48227886/200036361-808d37a9-a371-4c95-80d4-c91a42e7cbb9.png)

Clicking show more works as expected. 
![image](https://user-images.githubusercontent.com/48227886/200036584-9f3e4c5f-a7bb-49f7-b4e3-1c072c077385.png)

I assume this is because the sensor does not have a state_class, which frankly a lot don't, depending on the integration

**Comment by ildar170975** [comment]
> . I now have several sensors that have history, but not long term statistics. And so clicking on them yields a completely useless screen

This is strange.
Here my 2 template (if it is important) sensors:
-- both are enabled for Recorder;
-- one is with `state_class: measurement`

This one does not have LTS - it shows real "old-style" data:
![изображение](https://user-images.githubusercontent.com/71872483/200078882-db8eb949-138b-4462-97dd-473e0d7b8de3.png)

This one does have LTS - it shows stats:
![изображение](https://user-images.githubusercontent.com/71872483/200078904-415e4375-71ad-419d-8b89-7263329c59e3.png)

I do not agree to show LTS in more-info.
It should be displayed in a different tab (if available).

**Comment by CarlosGS** [comment]
Found some issues that may be related:
- https://github.com/home-assistant/frontend/issues/14295
- https://github.com/home-assistant/core/issues/81691
- https://github.com/home-assistant/core/issues/82309
- https://github.com/home-assistant/core/issues/82411
- https://github.com/home-assistant/core/issues/81756

Also, the interpolation on the new graphs is often distorted and overshoots, crossing the vertical axis.

**Comment by bigboban** [comment]
I have next issue with this "new" graph style here: https://github.com/home-assistant/frontend/issues/14688

**Comment by CarlosGS** [comment]
Sorry to insist, but these statistics graphs have downgraded the day-to-day usability of HASS :(

Often it's necessary to check the recent values of a sensor (i.e. see if temperature has increased in the last couple minutes), and this is completeley masked by the new statistics, it now takes 5+ minutes to update the graph.

Then the only option is to click "show more" for the old style... but that's the raw history of two days! so you must manually select a shorter period, overall adding many steps that just weren't needed before.

Can't put it better than @tankdeer: _"History, by definition, is series of events that actually happened. Not a statistical analysis of said events. While that can certainly be useful in some scenarios, it is not a replacement for actual, unchanged history."_

**Comment by TimoJJ** [comment]
Looks like it's going to be like this forever. 
Install History Explorer card and set it up. Besides showing separate graphs, it can also completely replace HA's default graphs with many tweak options. 
https://github.com/alexarch21/history-explorer-card
https://community.home-assistant.io/t/new-interactive-history-explorer-custom-card/369450/378

**Comment by melyux** [comment]
This is the worst. We now have to go into "Show more" to see usable data for anything.

**Comment by melyux** [comment]
No

**Comment by saschaludwig** [comment]
> Another issue with this approach. I now have several sensors that have history, but not long term statistics. And so clicking on them yields a completely useless screen
> 
> ![image](https://user-images.githubusercontent.com/48227886/200036361-808d37a9-a371-4c95-80d4-c91a42e7cbb9.png)
> 
> Clicking show more works as expected. ![image](https://user-images.githubusercontent.com/48227886/200036584-9f3e4c5f-a7bb-49f7-b4e3-1c072c077385.png)
> 
> I assume this is because the sensor does not have a state_class, which frankly a lot don't, depending on the integration

I also have the same issue, before the update all my entities had statistics in the entity view, and that was very handy to quick check the history of a certain entity.
Now I always have to click on "Show More" to see graphs. That's totally odd because the data is there obviously. Why isn't it displayed like in the version before?

**Comment by karwosts** [comment]
> I also have the same issue, before the update all my entities had statistics in the entity view, and that was very handy to quick check the history of a certain entity. Now I always have to click on "Show More" to see graphs. That's totally odd because the data is there obviously. Why isn't it displayed like in the version before?

Could you help check what is going on with a specific entity that says "No statistics found"? I believe the code is supposed to fetch both statistics and history, and show the statistics if there are statistics, and show the history if there is not. I'm not sure in your case why it is choosing statistics but not showing data. 

Maybe check for that entity, if you have an entry in devtools/statistics, and see if there's some kind of issue reported there.

**Comment by ildar170975** [comment]
Up

**Comment by saschaludwig** [comment]
still a problem

**Comment by terba** [comment]
The History explorer card is EOL, so this has to be solved. It is very annoying to just fire up the more-info dialog to click immediately on **Show more** to see the data. I don't need the whole LTS thing at all by the way. If someone wants old data but doesn't want to store old data he will not have old data. Bon mot by me :)

I've seen that _No statistics found_ problem too. I set the the state_class of entities to None in customize.yaml to get rid of LTS, went to Development tools/Statistics, deleted the stats of those entities and somehow that came up once or more. But don't remember what happened exactly.

**Comment by melyux** [comment]
I specifically avoid using long term statistics for all my entities just to avoid the annoying statistics view in the More Info. I want to see real data. The statistics are useful for seeing history long past the recorder rollover, but I can't use it because of this. Not great

**Comment by terba** [comment]
So do I. My customize.yaml has a ton of ```state_class: None``` entries. Hard to maintain...

I don't get the concept: you spend hundreds or thousands of dollars on home automation devices and the core component of the system runs on a $35 computer with an SD card storage? And Home Assistant engineers degrade their fabulous software to support this scenario and make the life harder for those who use this software as it should be (low-power but powerful HW, redundancy, UPS).

If you have a lot of data where long-term statistics should help, then you have a lot of devices for a lot of money, most probably the system is important to you, so you won't be running Home Assistant on a Raspberry Pi and an SD card, ergo you don't need long-term statistics as the hardware is able to handle the data easily.

If you have two light bulbs and a LED strip using a rPi, than you don't need LTS either as there is not much data.

Let's get rid of it. Or make it configurable at least. It has a lot of bugs anyway: actual state not shown on the graph, No statistics found, empty graph, chaos graphs in some cases, incomprehensible popup (max-min-mean of what interval?)...
