### ISSUE TITLE
Simple color definition for gauges does not show in the config dialog

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/frontend#14227]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Opening the visual config editor on a gauge does not show the values for red / yellow / green:

![Screenshot from 2022-10-28 13-58-48](https://user-images.githubusercontent.com/614929/198583531-983b39f8-0694-4f6b-89ed-3edecde7746c.png)

The yaml config has values for all three:

![Screenshot from 2022-10-28 13-59-21](https://user-images.githubusercontent.com/614929/198583147-a6c14382-c6d2-4b5f-b75c-0ebe777a6e83.png)

The gauge does show the colors correctly:

![Screenshot from 2022-10-28 13-59-00](https://user-images.githubusercontent.com/614929/198583187-c9242a48-4bac-49d7-8271-4bde6848e2f2.png)

### Describe the behavior you expected

The config in the yaml should be correctly rendered in the visual editor.

### Steps to reproduce the issue

1. Open the config in the visual editor for a gauge.
2. Observe the issue.

### What version of Home Assistant Core has the issue?

core-2022.10.5

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Firefox 106.0 / Chromium 106.0.5249.119 (official builds)

### Which operating system are you using to run this browser?

Arch Linux latest

### State of relevant entities

```txt
type: grid
cards:
  - type: gauge
    entity: sensor.u_s_air_quality_index
    min: 0
    max: 100
    name: Luft-Qualität
    unit: Index
    needle: true
    severity:
      green: 0
      yellow: 35
      red: 55
```

**Comment by ChristophCaina** [comment]
I can confirm this case - it is there for quite a long time now... Unfortunately, I don't remember if there was "ever" a working version... :-(
