### ISSUE TITLE
False warning about valid values for step size in input_number-helper

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/frontend#14230]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The smallest valid value according to the docs is 0.001 for the step size of input_number-helpers.

![Screenshot from 2022-10-28 16-36-18](https://user-images.githubusercontent.com/614929/198651945-86cde533-b59d-4177-b498-1e31a5ec61b3.png)

If 0.001 is entered an error pops up and tells the user that the closest valid numbers are 0 and 1. This is false, 0 is **not** a valid number and 0.001 **is**.

![Screenshot from 2022-10-28 16-37-18](https://user-images.githubusercontent.com/614929/198652008-2e7cd8d8-678a-45a7-8109-2f2d02aa3c7a.png)

### Describe the behavior you expected

Have either no warning or the correct one.

### Steps to reproduce the issue

1. Try to create an input_number-helper with the minimal valid step size.
2. Observe misleading, false warning.

### What version of Home Assistant Core has the issue?

core-2022.10.5

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Firefox 106.0 / Chromium 106.0.5249.119 (official builds)

### Which operating system are you using to run this browser?

Arch Linux latest

**Comment by karwosts** [comment]
Believe this was fixed with #14121
