### ISSUE TITLE
Translation Error: The intl string context variable "naam" was not provided to the string "{naam} verwijderen?"

### ISSUE THREAD

**Issue by Jozziej** [home-assistant/frontend#14238]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When trying to remove a Person via Settings > Persons, there is a translation error. I'm using the Dutch language and I do not know if it's also the case for different languages.

### Describe the behavior you expected

I expected to see, Do you want to remove (persons name) ?

### Steps to reproduce the issue

1. Go to Settings
2. Persons
3. Try delete a person and look at the Popup
...

### What version of Home Assistant Core has the issue?

2022.10.5

### In which browser are you experiencing the issue with?

Google Chrome 107.0.5304.88

### Which operating system are you using to run this browser?

Windows 11

**Comment by jbouwh** [comment]
Updated the Dutch translation `{naam}` -> `{name}`
