### ISSUE TITLE
The new Tile card does not match design of other cards

### ISSUE THREAD

**Issue by kukulich** [home-assistant/frontend#14241]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The new Tile card is nice but it does not match design of other native HA cards.

- I'm not able to choose the color `#44739e` used by default in other cards.
- There's no background below icon in other cards so it looks inconsistent.

![tile](https://user-images.githubusercontent.com/260445/198969496-41ab25db-1b0e-495a-af22-8c0d97e87ce6.png)

### Describe the behavior you expected

I would expect native HA cards design to be consistent. 

1. I understand that the default color is "Default color (state)" but user should have the option to choose `#44739e`. Or the default color of icons in other cards should be "Primary".

2. The default icon design may be without background (to be consistent with other cards) and there could be option to modify/enable it.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.11.0b3

**Comment by piitaya** [comment]
The new tile card brings in a new style of card into Home Assistant. It's a first iteration. It can look inconsistent for now but it will be improved with future updates 🙂

**Comment by kukulich** [comment]
@piitaya Ok, looking forward to future 👍

**Comment by ildar170975** [comment]
If that means that the future Frontend will have round corners, round icons - I strongly disagree.
