### ISSUE TITLE
No longer able to expand more info pop-up on 2022.11.0b5 

### ISSUE THREAD

**Issue by drthanwho** [home-assistant/frontend#14252]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When you open the more info pop up of an entity you were able to click on the title and the graph would expand to fill the screen. This is no longer possible on 2022.11.0b5.

### Describe the behavior you expected

To be able to expand the more info popup

### Steps to reproduce the issue

1. Open any entity
2. Click on the title
3. Watch in disbelief as the popup doesn't expand 😮
...

### What version of Home Assistant Core has the issue?

core-2022.11.0b5

### What was the last working version of Home Assistant Core?

core-2022.11.0b4

### In which browser are you experiencing the issue with?

Chrome and Edge

**Comment by bramkragten** [comment]
#14256
