### ISSUE TITLE
Sensor graph SVG overflows card's rounded corner

### ISSUE THREAD

**Issue by kevinkorte** [home-assistant/frontend#14275]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The sensor card with a line graph has the svg graph overflowing the rounded corners of the card

### Describe the behavior you expected

I expect that the svg graphs at the bottom of sensor cards would be contained or clipped within the container of the card as to not overflow the border.

### Steps to reproduce the issue

1. Create a sensor card using the UI card builder with a line graph.

### What version of Home Assistant Core has the issue?

2022.11.0

### In which browser are you experiencing the issue with?

Google Chrome Version 107.0.5304.88, Mozilla Firefox 106.0.4

### Which operating system are you using to run this browser?

Windows 10 Version 21H2 Build 19044.2130

### State of relevant entities

```txt
Ex: SpeedTest Download
state: 75.15
state_class: measurement
server_name: Seattle, WA
server_country: United States
server_id: 6057
bytes_received: 95519002
unit_of_measurement: Mbit/s
attribution: Data retrieved from Speedtest.net by Ookla
icon: mdi:speedometer
friendly_name: SpeedTest Download
```

### Problem-relevant frontend configuration

```yaml
type: sensor
entity: sensor.speedtest_download
graph: line
detail: 2
icon: mdi:download
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

### Additional information

Screenshot attached. Issue persists among browser zoom. Easier to notice when zoomed in of course.

![Home Assistant Cards](https://user-images.githubusercontent.com/4381361/199788276-00d3ec7f-d490-4ba2-a582-d94fd8cf2e7c.JPG)

**Comment by ildar170975** [comment]
The issue was closed automatically, the author did not raise it.
Had to create a new issue: https://github.com/home-assistant/frontend/issues/15401
