### ISSUE TITLE
Unit of measurement of water on the energy panel

### ISSUE THREAD

**Issue by Blacksli** [home-assistant/frontend#14270]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Good day!
In the panel, the energy in the new functionality of water statistics is displayed in LITERS, although the original sensors take into account in cubic meters.
Since water bills are paid in cubic meters, water meters are also in cubic meters - it is more convenient to look at statistics in cubic meters as well.
And the conversion to liters knocks down visual perception.

How can you make statistics in cubic meters?
![image](https://user-images.githubusercontent.com/74769766/199694199-fa5a4b9e-6fe9-4623-ab45-718d4733b820.png)
![image](https://user-images.githubusercontent.com/74769766/199694218-abe0438a-c22d-4c64-902b-ba50568f90fb.png)
![image](https://user-images.githubusercontent.com/74769766/199694282-3ac29555-9805-46a9-a4a3-af38776e65fe.png)
![image](https://user-images.githubusercontent.com/74769766/199694298-e867a616-397f-4c51-959b-1c7298d069a7.png)

### Describe the behavior you expected

Statistics in sensor units

### Steps to reproduce the issue

Add m3 water sensor to energy panel

### What version of Home Assistant Core has the issue?

2022.11.0

**Comment by andrewjswan** [comment]
It should display and count in sensor units, or have a global setting in the energy panel in which to count and display.
@bramkragten ? :)

**Comment by frenck** [comment]
We originally used m3, but it imposed all kinds of other issues, and changed it to liters in the beta based on all the user feedback we got.

The reason is fairly simple, 0.127m3 doesn't read well and isn't user-friendly either. 127 liters, however, does.

**Comment by andrewjswan** [comment]
It looks strange, if m³ is accepted in my country, then I would like to see the water consumption in m³, I can convert liters to m³, but for those who have consumption records in gal or ft³, it seems to me that liters are not convenient at all, and they do not show real, understandable picture of water consumption. All the same, the display setting (as we assume it is done in the weather) would be just right. And satisfy everyone.

PS: I decided to call the author of PR, maybe he will offer some options.

**Comment by g470258** [comment]
The resource of the water filter is in liters, so I count in liters. I have input data in liters. got *1000. Create an additional sensor in m3?

**Comment by frenck** [comment]
> It looks strange, if m³ is accepted in my country, then I would like to see the water consumption in m³, I can convert liters to m³

That is a different discussion not an bug.
Some background was given above, it originally displayed m3 in the UI during beta, but has been changed to liters based on user feedback, as m3 is too large for the daily quantity used.

But as said, not part of our issue trackers, as that is not a bug.

> PS: I decided to call the author of PR, maybe he will offer some options.

Yes, I kindly asked you not to do that. Thanks 👍

**Comment by frenck** [comment]
> The resource of the water filter is in liters, so I count in liters. I have input data in liters. got *1000. Create an additional sensor in m3?

@g470258 That is not related to this issue, so off-topic, but yet. Sensors for use with the water feature on the energy dashboard need to be either in m3 or gallons, as also mentioned on the page itself.

**Comment by andrewjswan** [comment]
> But as said, not part of our issue trackers, as that is not a bug.

Well, how to look, if all sensors show the same numbers in which they count, but in energy I see completely different numbers that do not match the sensor readings.  That is a bug.

**Comment by frenck** [comment]
It does match the sensor readings, it is just displayed in a different unit. That doesn't change its actual water usage in terms of volume.

As a next possible step that has been discussed, is changing the units based on the quantity. For example, when looking at a yearly view, units like MWh and m3 probably make lots more sense. But when looking at the hour (daily view), units like L and kWh are more fitting. It is all about the magnitude at that point.

**Comment by andrewjswan** [comment]
The simplest solution is to add a setting in what to display.

It is more convenient for me in those units in which the sensor counts for me.

**Comment by frenck** [comment]
> The simplest solution is to add a setting in what to display.

It might be a simple solution in your eyes, but adding tons of options is never simplifying things...

**Comment by andrewjswan** [comment]
I read this about weather settings and about mmHg.

**Comment by frenck** [comment]
> I read this about weather settings and about mmHg.

That is not related to the energy dashboard.

**Comment by andrewjswan** [comment]
![image](https://user-images.githubusercontent.com/3609660/199721010-5aad7c02-4c9b-49f0-8efc-87db6b96e4d9.png)
10 000 L - It's wonderful!

Sensor:
![image](https://user-images.githubusercontent.com/3609660/199721434-34c7c57a-5906-4416-adfb-ee3511f66e69.png)

**Comment by andrewjswan** [comment]
![image](https://user-images.githubusercontent.com/3609660/199721623-a9ca422d-895e-49ad-a1ec-a2bf1ba02249.png)

**Comment by frenck** [comment]
> 10 000 L - It's wonderful!

I agree, see also my comment here: https://github.com/home-assistant/frontend/issues/14270#issuecomment-1301948631

**Comment by pergolafabio** [comment]
> We originally used m3, but it imposed all kinds of other issues, and changed it to liters in the beta based on all the user feedback we got.
> 
> The reason is fairly simple, 0.127m3 doesn't read well and isn't user-friendly either. 127 liters, however, does.
> 
> @andrewjswan Please don't just ping people to get their attention. It can come across as demanding someone's attention (I'm sure you don't mean it that way, but... still, please withhold from doing that).

Hi @frenck , I can indeed "L" to dashboard as entity, but on the energy dashboard itself, its still presented with 3 decimals... Like 75.000 Liter. Is this a bug ? Or how can I remove/hide the decimals in energy dashboard?

**Comment by tomdee** [comment]
I may have misconfigured something, but my water sensor is in gallons but the energy page is in liters. That's pretty inconvenient since I'm always thinking about water usage in gallons.

**Comment by henkiejan1** [comment]
Hmm, never fixed? I added a water meter and get an entity with litres and with m3. I like to add m3 so that i can setup the tarif and it shows up in the energy dashboard. Sadly the m3 is automatically converted to litres and is so not showing the price i have consumed... ☹️

**Comment by Darkyputz** [comment]
Same here...liter instead of gallons...
Would correct it in the code, but where can i find it.
