### ISSUE TITLE
Creating an automation triggered with value=0 does not persist

### ISSUE THREAD

**Issue by uberchris2** [home-assistant/frontend#14279]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating a automation through the UI, if the device triggering the automation has a value = 0, then the automation that is saved to automations.yaml will not include the value at all. This results in the automation triggering for _any_ value on that device.

### Describe the behavior you expected

I would expect the output yaml to include "value: 0"

### Steps to reproduce the issue

1. Create a new automation via the UI
2. Add a trigger of type Device
3. Under Device, select an applicable device (in my case, Minoston MR40Z)
4. Under Trigger, select a scene (in my case, Central Scene action on Endpoint 0 Scene 001)
5. Select a value that maps to 0 (in my case, KeyPressed)
6. Click Save
7. Enter a name (Test Automation 1)
8. Reopen the automation and expand the trigger
9. Observe that the KeyPressed value is no longer selected
10. Open automations.yaml
11. Observe that the created automation does not include a value field in the trigger

### What version of Home Assistant Core has the issue?

2022.11.0

### In which browser are you experiencing the issue with?

Google Chrome 107.0.5304.87

### Which operating system are you using to run this browser?

Windows 11 2H22

### Additional information

I suspect that somewhere in the process of saving automations, falsey values get pruned. I'm assuming that a value of 0 is a victim of this process, when it is actually a valuable part of the trigger.

Note that editing the automations.yaml to include "value: 0" fixes the problem for an individual automation.

**Comment by chrisjenx** [comment]
Probably related too: https://github.com/home-assistant/frontend/issues/14307
