### ISSUE TITLE
Picture elements card - not rendered correctly

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#14282]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Light mode (correct):
![Img0](https://user-images.githubusercontent.com/74879713/199818587-93d23081-ff1d-4150-9b1f-453736af5f43.png)

Dark mode (incorrect):
![Img1](https://user-images.githubusercontent.com/74879713/199818287-c3f348ed-8055-40b8-8150-cbebc7f74ab4.png)

My image for dark mode:
![Roborock S5 - Dark](https://user-images.githubusercontent.com/74879713/199818940-cb848f7f-3f08-4cf1-83b9-3177487f3c00.png)

Also, the "Chips 1.png" image (see code posted below) is not longer visible.
Explained better in #14297

### Describe the behavior you expected

I expect everithing to return as it was in 2022.10.x

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.11.1

### What was the last working version of Home Assistant Core?

2022.10.x

### In which browser are you experiencing the issue with?

Chrome 107.0.5304.88

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
type: picture-elements
image: /local/Roborock S5 - Light.png?v=1
dark_mode_image: /local/Roborock S5 - Dark.png?v=1
title: Roborock S5
elements:
  - type: image
    image: /local/Roborock S5 Chips 1.png?v=1
    tap_action: none
    style:
      transform: translate(0%, 0%)
      top: 69.4%
      left: 19.8%
      pointer-events: none
```

**Comment by spacegaier** [comment]
Did you rule out any data loading issues? E.g. no network errors in the browser logs while trying to access the dark mode image (so you can actually see it loaded there)?

**Comment by WRoss7** [comment]
Sorry but unfortunately I wouldn't know how to debug through Chrome, however I can say that if I refresh the browser page, the image magically appears.
For Home Assistant I almost never use dark mode, but now I noticed that the bug occurs even when switching from light to dark mode.

**Comment by WRoss7** [comment]
It should be similar to #14297.
Surely you can find people there who know how to debug in Chrome
