### ISSUE TITLE
Manually adding a device is not working when there are discovered devices for an intergration

### ISSUE THREAD

**Issue by thecode** [home-assistant/frontend#14288]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When there are discoved devices waiting to be configured and you are manually tying to add a device the frontend will offer to check if it is one of them, clicking on "Setup another instance of..." is broken. If the devices are ignored it is possible to manually add a device.

### Describe the behavior you expected

"Setup another instance of" should work

### Steps to reproduce the issue

1. Try to manually add a device:
![image](https://user-images.githubusercontent.com/1858925/200003331-f36d4c5b-93a4-4beb-984b-10a8019924a9.png)
2. Click on "Setup another instance of"
3. Button does not work and exception is shown in browser console
![image](https://user-images.githubusercontent.com/1858925/200003564-615acc4d-d7a3-45a9-9614-25b6559bda44.png)

### What version of Home Assistant Core has the issue?

core-2022.11.1 (also broken in latest dev core)

### What was the last working version of Home Assistant Core?

core-2022.10?

### In which browser are you experiencing the issue with?

Chrome 107.0.5304.88 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### Javascript errors shown in your browser console/inspector

```txt
integrations:1 Autofocus processing was blocked because a document already has a focused element.
ha-domain-integrations.ts:200 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'supported_by')
    at F.value (ha-domain-integrations.ts:200:1)
    at F.handleEvent (styles.ts:371:1)
    at n.fireRequestSelected (mwc-list-item-base.ts:224:1)
    at n.<anonymous> (mwc-list-item-base.ts:224:1)
    at 01055a0b.js:2:1798
    at Map.forEach (<anonymous>)
    at e.updated (01055a0b.js:2:1724)
    at n._$AE (styles.ts:371:1)
    at n.performUpdate (styles.ts:371:1)
    at n.scheduleUpdate (styles.ts:371:1)
value @ ha-domain-integrations.ts:200
handleEvent @ styles.ts:371
fireRequestSelected @ mwc-list-item-base.ts:224
(anonymous) @ mwc-list-item-base.ts:224
(anonymous) @ 01055a0b.js:2
e.updated @ 01055a0b.js:2
_$AE @ styles.ts:371
performUpdate @ styles.ts:371
scheduleUpdate @ styles.ts:371
_$EC @ styles.ts:371
await in _$EC (async)
requestUpdate @ styles.ts:371
set @ styles.ts:371
setSelectedStateForElementIndex @ mwc-list-base.ts:270
setSingleSelectionAtIndex_ @ 342ceb2d.js:2
setSelectedIndexOnAction_ @ 342ceb2d.js:2
handleSingleSelection @ 342ceb2d.js:2
onRequestSelected @ mwc-list-base.ts:270
handleEvent @ styles.ts:371
fireRequestSelected @ mwc-list-item-base.ts:224
onClick @ mwc-list-item-base.ts:224
cb @ mwc-circular-progress-base.ts:156 
```
```


### Additional information

_No response_

**Comment by uvjim** [comment]
Also seeing this in frontend `20221102.1`.  I seem to remember this happening in the HA betas as well, but then it disappeared when updated to a later beta.

![image](https://user-images.githubusercontent.com/8431065/200590759-52ef087d-3cbb-4f8d-a7ae-6d2b702ab1e7.png)
