### ISSUE TITLE
Google Sheets: Cannot see the config_entry

### ISSUE THREAD

**Issue by danielbrunt57** [home-assistant/frontend#14285]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I cannot see the config_entry where is supposed to be. The integration creates the document in google sheets but HA doesn't show the config_entry so I can't do any automation without it:
![image](https://user-images.githubusercontent.com/49846893/199904617-6d2c951d-c7dd-4fc0-87ab-ce93e6d02f22.png)

### Describe the behavior you expected

The config_entry should be populated.

### Steps to reproduce the issue

1. Dev Tools, Services, google_sheets.append_sheet no longer populates the entity
2. Automation, Call Service, google_sheets.append_sheet no longer populates the entity.

### What version of Home Assistant Core has the issue?

core-2022.11.1

### What was the last working version of Home Assistant Core?

2022.10.x

### In which browser are you experiencing the issue with?

Edge-latest

### Which operating system are you using to run this browser?

Windows 11

**Comment by tkdrob** [comment]
@bramkragten  I've found the frontend version where it started. 20221010.0 was working fine. 20221020.0 broke the selectors.

**Comment by emonteroe** [comment]
Another question @tkdrob :

Even with the config_entry that I got in n /config/.storage/core.config_entries the integration is failing to find the worksheet, could this be also related or it is a particular error of something I'm doing wrong?

`File "/usr/src/homeassistant/homeassistant/components/google_sheets/__init__.py", line 94, in _append_to_sheet
    worksheet = sheet.worksheet(call.data.get(WORKSHEET, sheet.sheet1.title))
  File "/usr/local/lib/python3.10/site-packages/gspread/spreadsheet.py", line 341, in worksheet
    raise WorksheetNotFound(title)
gspread.exceptions.WorksheetNotFound: Home Assistant Montero`

**Comment by danielbrunt57** [comment]
@emonteroe I'd also post your yaml for the service call and verify that the worksheet does exist...

**Comment by emonteroe** [comment]
Sorry, my bad. Done, Edited my original comment with the service call yaml.

**Comment by tkdrob** [comment]
`worksheet` is optional. That is for a sheet inside the document, not a document by that name.

**Comment by emonteroe** [comment]
Ohh I totally missed that, sorry for that. Now it worked.
Thanks a lot.

**Comment by cbhiii** [comment]
Has anyone heard of any updates on this issue?

For someone who just loaded this new integration (me) and now can't use it (also me), it is very frustrating.

I wish I had the knowledge to dig into the cause of it to find the solution.

**Comment by danielbrunt57** [comment]
No updates yet.  The new UI version seems to have broken a lot of things...

**Comment by Rubbervdh** [comment]
Having the same issue. I have the newest version of HA. Created like 3 different projects in cloud console without result. Let’s wait for an update I guess.

**Comment by danielbrunt57** [comment]
> Having the same issue. I have the newest version of HA. Created like 3 different projects in cloud console without result. Let’s wait for an update I guess.

I also am still waiting for a fix...

**Comment by danielbrunt57** [comment]
Yay!

![image](https://user-images.githubusercontent.com/49846893/206601848-a7f9ec36-8b1d-46c0-b095-9ee26c65c1a9.png)

**Comment by Rubbervdh** [comment]
> Looks like the current release has this fixed. Give it a try now.

Already noticed and It did!
