### ISSUE TITLE
change of sidebar doesn't work since core 2022.11.0

### ISSUE THREAD

**Issue by scxs535** [home-assistant/frontend#14296]
### The problem

if I display or hidden some items in sidebar, after refreshing the browser(or close the browser and open it again), the sidebar changes back as it was before, 
i.e. I can't make any change in sitebar.
this issue is since core 2022.11.0, it still works with core 2022.10.5.

### What version of Home Assistant Core has the issue?

core-2022.11.0

### What was the last working version of Home Assistant Core?

core-2011.10.5

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

core

**Comment by ildar170975** [comment]
> if I display or hidden some items in sidebar, after refreshing the browser(or close the browser and open it again), the sidebar changes back as it was before,
> i.e. I can't make any change in sitebar.

Do not confirm it with:
-- HA in docker (if important)
-- Win10x64 + Chrome (107.0.5304.88 )

**Comment by scxs535** [comment]
i use HAos, have the issues with android app, chrome, edge and Firefox browser

**Comment by scxs535** [comment]
i found the cause, it was the browser mod integration, if i disable the integration, then i can edit the sidebar without any problems.
