### ISSUE TITLE
Logbook page displays entries that should be excluded

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#14291]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I see in the logbook entries that should not be there since I excluded them in configuration.yaml

![Img](https://user-images.githubusercontent.com/74879713/200014420-dec669d8-b586-4d7a-8310-c3f93ad53614.png)

### Describe the behavior you expected

In the logbook there should not be all those entities that were excluded in configuration.yaml
I have included these entities in the Registry
I also tried excluding the weather domain but to no avail.

configuration.yaml example:

logbook:
  include:
    entities:
      - sensor.mysensor
      ...
  exclude:
    entities:
      - weather.casa
      - weather.openweathermap

Am I doing something wrong here?

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.11.1

### In which browser are you experiencing the issue with?

Chrome 107.0.5304.88

### Which operating system are you using to run this browser?

Windows 10

**Comment by ildar170975** [comment]
> I see in the logbook entries that should not be there since I excluded them in configuration.yaml

What do you mean by "Logbook" - is it a Logbook card or a Logbook page?
If you are talking about a card - check this: https://github.com/home-assistant/core/issues/72844#issuecomment-1145104227

**Comment by WRoss7** [comment]
Hi ildar170975,

> What do you mean by "Logbook" - is it a Logbook card or a Logbook page?

Logbook page.

I also tried to exclude the weather domain, but without success. However, the problem is not only inherent to the weather entities, but also to several other entities. The above was just an example.

**Comment by ildar170975** [comment]
> You do not experience the same bug?

I have no exclusions from Logbook, only from a Recorder.

**Comment by WRoss7** [comment]
Persistent in Home Assistant 2023.2.0

**Comment by karwosts** [comment]
Openweathermap creates dozens of sensors, and your exclude list is only excluding one weather entity, but owm creates many sensor.xxx entities in addition to weather.openweathermap.

Is that maybe what is showing up in your logbook? Hard for me to tell due to the language, but can you look in developer tools and add all sensor.openweathermap* sensors to your exclude list as well, and see if that makes a difference?

**Comment by WRoss7** [comment]
Simplifying I have a logbook similar to this:
```
history:
  include:
    entities:
      - my entity 1
      - ...
      - ...
  exclude:
    entities:
      - sensor.meteo_oggi
```
So I excluded sensor.meteo_oggi that I don't want to see it in the Logbook.
But as you see below the exclusion has no effect. Am I doing something wrong?

![Image](https://user-images.githubusercontent.com/74879713/217648428-8347d99c-d7a9-4c8b-8c76-71c9ae8fc2f6.png)

**Comment by karwosts** [comment]
Doesn't that exclude need to be under `logbook:` or `recorder:`, not `history:`?

> By default, the logbook will use the same filter as the recorder. 

History, logbook, and recorder are 3 different things.

https://www.home-assistant.io/integrations/logbook/
https://www.home-assistant.io/integrations/recorder/
https://www.home-assistant.io/integrations/history/

**Comment by karwosts** [comment]
I just did a test to exclude an input_boolean from my logbook, and I no longer see it there (unless I specifically select that entity in the entity search box, then it shows up)

**Comment by WRoss7** [comment]
Sorry, you are right, I wrote History, but I meant Logbook; I corrected the example code.
In the Recorder I logically have the same code, otherwise how could it work?
I've done some more testing and many things don't add up; for example, now in the configuration.yaml file I've included sensor.meteo_oggi and excluded weather.casa, but I don't see either of them. Over the weekend I will try to format everything, maybe there is a problem in the database?

**Comment by WRoss7** [comment]
Recorder is a software component that records in a database anything it is not instructed to exclude while Logboock takes data it is not instructed to exclude from the same database. So I have to include what I need in Recorder and also in Logboock, and exclude from the former or the latter (or both) what I don't need. Is this correct or am I doing something wrong?
