### ISSUE TITLE
Water usage via Flume doesn't appear in Energy Dashboard

### ISSUE THREAD

**Issue by jeffkibuule** [home-assistant/frontend#14309]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Energy Dashboard has not updated to show contribution of water usage with data coming from my Flume Water sensor on HomeAssistant 2022.11.1. The data is present as an entity I can view however.

### Describe the behavior you expected

Water usage would be a new field populated with data from my Flume Water sensor.

### Steps to reproduce the issue

1. Install HomeAssistant 2022.11.1
2. Setup Flume Water Sensor
3. Add Flume Water Sensor integration with valid credentials
5. Have HomeAssistant automatically detect sensor bridge on network

### What version of Home Assistant Core has the issue?

20221102.1

### In which browser are you experiencing the issue with?

Safari 16.2

### Which operating system are you using to run this browser?

macOS Ventura 13.1

### State of relevant entities

```txt
unit_of_measurement: gal/m
attribution: Data provided by Flume API
friendly_name: Flume Sensor Current
```

### Additional information

<img width="686" alt="Screenshot 2022-11-05 at 4 16 17 PM" src="https://user-images.githubusercontent.com/734509/200146693-e285d6b3-8920-4d6d-aff3-146a3ed03f06.png">
<img width="579" alt="Screenshot 2022-11-05 at 4 17 05 PM" src="https://user-images.githubusercontent.com/734509/200147056-50d31e40-e5e2-4bc3-893d-567c6022cf94.png">

**Comment by tonesto7** [comment]
I've been experiencing the same issue... I was hoping there was an update on this :(

**Comment by wtadler** [comment]
Have you made sure to add it to the dashboard? Settings > Dashboards > Energy > Add Water Source. Since it looks like your units are configured right, you should then be able to add a source like "Current Day."

**Comment by tonesto7** [comment]
I didn't even know you had to set that up.  I made the changes and it's showing for me now
Thanks for the info

**Comment by jeffkibuule** [comment]
Meant to follow up, this issue was resolved for me. For new users adding this add-on, it didn't automatically appear.
