### ISSUE TITLE
Map card in more-info for persons became not square

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#14306]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The map card for a person's more-info became not square - which is not good for a map.
This is a MAP - not a CAMERA view or something.

![изображение](https://user-images.githubusercontent.com/71872483/200136068-f535ef95-f7dc-446f-a70c-6787f8d0e0a0.png)

Here is a look from 2022.7.4 - here the map is "almost square" (1920x1200 monitor):
![изображение](https://user-images.githubusercontent.com/71872483/200136262-9f3a81c2-f407-4744-8ae1-9108c612bff7.png)

The more-info pop-up now has more tabs - so it became wider as it was earlier; but I propose to keep a square (-ish) aspect ratio for a map.

### Describe the behavior you expected

The map should be square.

### Steps to reproduce the issue

Open a more-info pop-up for a person.

### What version of Home Assistant Core has the issue?

2022.11.1

### In which browser are you experiencing the issue with?

Chrome 107.0.5304.88 

### Which operating system are you using to run this browser?

Win10x64

**Comment by WRoss7** [comment]
I am having the same problem with the map of the robot hoover, now completely out of proportion.
I am not familiar with TypeScript, but perhaps the problem is due to #14246.

**Comment by ildar170975** [comment]
Could you post a screenshot of your problem?
Not sure that these issues are related - probably your vacuum's map is of `camera` domain.

**Comment by WRoss7** [comment]
Hi ildar170975

> probably your vacuum's map is of `camera` domain.

Yes, but imo the problem lies in how the images are reproportioned after the latest UI changes

The card:
![Img](https://user-images.githubusercontent.com/74879713/200177013-5db40aec-7b59-4a63-a41d-08e6b9ebb033.png)

A piece of code:
type: picture-elements
camera_image: camera.xiaomi_cloud_map_extractor
camera_view: live
title: Roborock S5
elements:
  - type: icon
    icon: mdi:play
    title: Avvia la pulizia
    tap_action:
      action: call-service
      service: vacuum.start
      service_data:
        entity_id: vacuum.roborock_s5
    style:
      transform: translate(0%, 0%)
      left: 30%
      bottom: 3%
      color: rgb(0, 0, 0)

**Comment by ildar170975** [comment]
When zoomed:

![изображение](https://user-images.githubusercontent.com/71872483/215337948-bb245747-c584-4ea5-be08-bf96ddd4e346.png)

**Comment by ildar170975** [comment]
up

**Comment by matthiasdebaat** [comment]
> The map card for a person's more-info became not square - which is not good for a map. This is a MAP - not a CAMERA view or something.

Please add some rationale why a map needs to be square.

**Comment by ildar170975** [comment]
OK, it may not be exactly square - but it should not be as "low" is it is now:

![изображение](https://user-images.githubusercontent.com/71872483/235935244-bede5add-cc60-42c6-8145-80319b5d849e.png)

Especially when the window is stretched out:
![изображение](https://user-images.githubusercontent.com/71872483/235935281-fa8123f0-41cf-487c-bcac-b0456b683374.png)

When watching a map, a user expects to see where the person is located, and respectively to other objects/points too.
When a map is a "band" (a low rectangle) - it is less convenient to use it.

Earlier the map was more "squarish" and it was more convenient - check a picture from the 1st post:

![изображение](https://user-images.githubusercontent.com/71872483/235935818-b0091818-4f75-48d6-a5c4-e77a30b42231.png)

**Comment by ildar170975** [comment]
up

**Comment by matthiasdebaat** [comment]
> When watching a map, a user expects to see where the person is located, and respectively to other objects/points too. When a map is a "band" (a low rectangle) - it is less convenient to use it.

I find it hard to understand why the shape is the problem here. For example, Google Maps on your phone is a portrait rectangle and works perfectly. Is it more about the default zoom, that you can see other objects/points?

**Comment by ildar170975** [comment]
Phone is a different case.
Will have to be a rectangle (a small screen), less information can be shown.
But for a large desktop monitor there is a possibility to show MORE information.

**Comment by ildar170975** [comment]
Still think that this should be improved.

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
Up

**Comment by ildar170975** [comment]
Decided to close it... Not critical.
