### ISSUE TITLE
Compare Water Consumption not aligned- Energy Dashboard

### ISSUE THREAD

**Issue by aboogerd** [home-assistant/frontend#14303]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When enable the compare feature the water consumption card the previous compare data isn't shown correct. It shows the "now" data double and offset. 

For example: This week shows 2x monday 31 october instead of monday 31 october and monday 24 october. The previous data shows offset.

![image](https://user-images.githubusercontent.com/9293098/200114006-a149669b-c545-47d8-a458-beb629ebec27.png)

 And noticed different units shown in the summary when enable the compare

![image](https://user-images.githubusercontent.com/9293098/200114141-8c6b3634-2527-4325-a3d1-0e015bbb675c.png)

### Describe the behavior you expected

Compare data with previous and align timeframes

### Steps to reproduce the issue

1. Open energy dashboard
2. Enable compare
3. scroll to the water card
...

### What version of Home Assistant Core has the issue?

2022.11.1

### In which browser are you experiencing the issue with?

Chrome 107.0.5304.88 

### Which operating system are you using to run this browser?

Win10

**Comment by aboogerd** [comment]
version 2022.12.1 the alignment issue still exist. The units issue is fixed.
![image](https://user-images.githubusercontent.com/9293098/206899744-50edd63c-0d73-4bf8-a76c-34b6c2b7ed1c.png)

**Comment by rklomp** [comment]
Same issue here. It look like it is displaying the both the history and current data in the more transparent compare graph. This causes twice as many data points and thus the spacing is incorrect. To fix it I guess the range for the compared data should be fixed.

**Comment by dzik87** [comment]
Same here. When comparing day to day it shows previous and actual day in background.
Exactly as it is shown on snippet above.

Like it compares 24h from today to 48hours from yesterday

**Comment by dzik87** [comment]
Can be closed. Issue has been resolved.
