### ISSUE TITLE
Weird & inconstistent black frame around a chip button

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#14305]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Sometimes after closing a more-info popup a **black frame** is displayed around a chip button.

Test code:
```
type: entities
entities:
  - type: buttons
    entities:
      - sun.sun
      - sun.sun
```

The card before tapping a button:
![изображение](https://user-images.githubusercontent.com/71872483/200121764-89b996f3-bb0a-4f5b-99b3-db7aef714a7f.png)

After tapping a button a more-info popup is displayed.
After closing the popup - **sometimes** that frame is displayed:
![изображение](https://user-images.githubusercontent.com/71872483/200121792-ca8516f4-287b-4f5b-a2e6-62552b09f19a.png)

It happens not every time (inconsistency).

Proposal - DO NOT display the frame at all.

### Describe the behavior you expected

No frame is displayed.

### Steps to reproduce the issue

As described avove.

### What version of Home Assistant Core has the issue?

2022.11.0

### In which browser are you experiencing the issue with?

Chrome 107.0.5304.88 

### Which operating system are you using to run this browser?

Win10x64

**Comment by spacegaier** [comment]
That is the browser focus marker (you can tab through the UI). I had a quick look and tried to see which two elements get the tab focus in a chip but failed to spot that.

**Comment by ildar170975** [comment]
But strange that this frame is displayed inconsistently:
> After closing the popup - sometimes that frame is displayed:

**Comment by spacegaier** [comment]
I can make that frame appear pretty reliably, but doesn't matter as I just found a generic solution to suppress it.

**Comment by ildar170975** [comment]
Thank you, Phil!
