### ISSUE TITLE
History Graph not showing complete

### ISSUE THREAD

**Issue by scns** [home-assistant/frontend#14311]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When i open the entity card, the history graph is not showing completely. (right side is missing a bit)
![image](https://user-images.githubusercontent.com/7148071/200161481-021107be-e057-42e9-86ef-6f0db3e51d05.png)

### Describe the behavior you expected

Showing the complete graph

### Steps to reproduce the issue

Open the entity card with recording enabled device. (eg. Temperature)

### What version of Home Assistant Core has the issue?

Home Assistant 2022.11.1

### In which browser are you experiencing the issue with?

Chrome, Edge, Firefox (all latest versions)

### Which operating system are you using to run this browser?

Windows 11 22H2

### State of relevant entities

```txt
All entity's with an history graph
```

**Comment by ildar170975** [comment]
Currently 12:44, here is a graph (btw, this is NOT a history graph - it's a statistics graph, approximate data):
![изображение](https://user-images.githubusercontent.com/71872483/200164089-480bbd0a-00c0-40f1-ab78-cf1d0c9ad069.png)
The right "13:00" line probably will be shown after 13:00.
