### ISSUE TITLE
not all sensors from fronius are on the list

### ISSUE THREAD

**Issue by lakusz1github** [home-assistant/frontend#14317]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi

This sensor are not visible on Energy dashboard:
sensor.fronius_house_load
sensor.fronius_panel_status
sensor.fronius_ac_power
sensor.fronius_grid_usage

### Describe the behavior you expected

to be visible in Energy

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.11.1

**Comment by farmio** [comment]
Only entities whose state represents `energy` can be used for the energy dashboard. 
See https://www.home-assistant.io/docs/energy for more information.
