### ISSUE TITLE
Graphical frontend for creating/editing schedules is broken in 2022.11.1

### ISSUE THREAD

**Issue by martienpoels-bank2loyalty** [home-assistant/frontend#14312]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Only the column that has a yellow tinted backgroundbar (current day) is able to display the schedule, the other days are not displayed anymore.

This is new in this version. Has worked like a charm before. 

Very nasty bug, showing or editing schedules has become impossible

### Describe the behavior you expected

It should show the actual schedule.
And you should be able to edit it.

### Steps to reproduce the issue

1. (Try to) Create a new schedule or open an existing one.

2. When a new schedule is selected, you can only edit the local day. Other days you see what you enter but when you move your cursor away the entry is not shown anymore, although it seems to be there.

### What version of Home Assistant Core has the issue?

2022.11.1

### In which browser are you experiencing the issue with?

Google chrome Versie 107.0.5304.88

### Which operating system are you using to run this browser?

Windows11 but also on Android 12

### Additional information

I think every user will suffer from this.

**Comment by bachya** [comment]
Confirmed – here's a quick GIF to show:

![CleanShot 2022-11-06 at 11 22 52](https://user-images.githubusercontent.com/47216/200188248-27e0d68b-43f1-4659-8b73-9520e8232995.gif)

FWIW, the schedule data still appears in `/config/.storage/schedule`, so this appears to be an issue with the UI component.

**Comment by spacegaier** [comment]
Issue was down to the selected language/locale. E.g. in German everything was fine, but in English US where the week starts on Sunday and not Monday, the issue occurred. I just pushed a PR that should address that.

**Comment by martienpoels-bank2loyalty** [comment]
Thanks for your effort and time. Top!
