### ISSUE TITLE
Addon Configuration - Can't add list items

### ISSUE THREAD

**Issue by coreGreenberet** [home-assistant/frontend#14325]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Some addons like Grafana, Sambashare are having some list entries as input fields which are later stored as "Bubbles".
At the moment you can see the current configuration and the list of the bubbles, but you are not able to add any new item.

![grafik](https://user-images.githubusercontent.com/3853374/200406238-1b94b7c8-8330-4da0-ba26-8f8837cdfa83.png)

### Describe the behavior you expected

There should be an input field to add more entries to the list.

### Steps to reproduce the issue

1. Open the configuration Tab of the Grafana/Samba addon
2. Try to add a new item to the plugin list (Grafana) or hidden folders list(Samba)

### What version of Home Assistant Core has the issue?

2022.11.1

### In which browser are you experiencing the issue with?

Firefox 106.0.5 (64-Bit), Edge 107.0.1418.35

### Which operating system are you using to run this browser?

Windows 11

**Comment by patman15** [comment]
I can confirm the issue
```
Home Assistant 2022.11.2
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest
Firefox Browser 107.0
```
Occurs with all add-ons that have list items, e.g. `core-mariadb`, `core-configurator`

**Comment by coreGreenberet** [comment]
Still not working

**Comment by patman15** [comment]
```
Home Assistant 2022.11.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20221108.0 - latest
Firefox 109.0.1
```
I do not know what helped, but for me it works again.
