### ISSUE TITLE
More info - Settings - Advanced settings: corners of the title bar come out of the frame

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#14336]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![Img](https://user-images.githubusercontent.com/74879713/205442701-b6d536d9-3eaa-48a4-80d6-534dcb23effe.png)

### Describe the behavior you expected

The title bar should not come out of its frame

### Steps to reproduce the issue

1.More info
2.Settings
3.Advanced settings
...

### What version of Home Assistant Core has the issue?

2022.11.2

### In which browser are you experiencing the issue with?

Chrome 107.0.5304.88

### Which operating system are you using to run this browser?

Windows 10

**Comment by spacegaier** [comment]
I don't follow your issue. Can you please highlight e.g. in the screenshot where something is off?

**Comment by WRoss7** [comment]
Done.
2022.10.0 ha modificato il raggio delle card e altri elementi UI, con il rovescio della medaglia, che diversi elementi adesso presentano imperfezioni.

I have also done other inherent bag reports:   #14282   #14278   #14277

**Comment by spacegaier** [comment]
Now it is clear, thank you.

**Comment by WRoss7** [comment]
Thanks to you.

oh, I had missed it, but the same problem also affects automation screens, for example when I open an action by clicking the down arrow

**Comment by spacegaier** [comment]
> Thanks to you.
> 
> oh, I had missed it, but the same problem also affects automation screens, for example when I open an action by clicking the down arrow

Those also use the same expansion panel component, so they will implicitly be covered with my code fix as well.

**Comment by WRoss7** [comment]
Excellent 👏
