### ISSUE TITLE
Memory leak in energy-distribution card

### ISSUE THREAD

**Issue by pvmil** [home-assistant/frontend#14349]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a dashboard running on a tablet (24/7) with the Android Companion App (on Galaxy Tab S2, Android 7.0). I really like the companion app, compliments for this!

This dashboard started crashing, caused (according to logs) by not being able to allocate memory (I see causes in multiple origins). I started logging memory usage in the developer settings of Android. The memory usage of io.homeassistant.companion.android keeps increasing over time. I do think I see a memory leak here.

By disabling parts of my dashboard I got to a clear indication the energy-distribution card is causing a memory leak. When that card is disabled, memory usage seems to be pretty stable (moving up and down a bit within a 28mb bandwith). When the card is enabled memory usage keeps growing, below 2 logs on memory usage over time (without any user activity)

How can I help in solving this? Too bad I am not a front-end programmer but I can help with logs, performing tests, etc.

(time in mm:ss)
Time   Memory usage (companion app)
00:30  274  MB
03.00  331 MB
15.20  587 MB
20.37  699 MB

Time   Memory usage (fully kiosk)
00:10  443 MB
00:30  441 MB
01:00  441 MB
01:30  486 MB
02:00  496 MB
06:37  611 MB
10:30  720 MB
16:30  862 MB
20:30  0,95 GB
30:20  1,2 GB
42:00  1,5 GB

### Describe the behavior you expected

I expected memory usage to be more or less stable. When the energy-distribution card is disabled memory usage seems to be pretty stable (moving up and down a bit within a 28MB bandwidth). 

### Steps to reproduce the issue

1. Create a dashboard with the energy-distribution card on it, configuration I use:
`type: energy-distribution
link_dashboard: false`

### What version of Home Assistant Core has the issue?

2022.11.2

### What was the last working version of Home Assistant Core?

I do not know, I think the issue has been in for multiple months (I did not use the card 24/7 before that)

### In which browser are you experiencing the issue with?

Companion app 

### Which operating system are you using to run this browser?

Android 7

### Problem-relevant frontend configuration

```yaml
Card configuration I use:
`type: energy-distribution
link_dashboard: false`
```

**Comment by pvmil** [comment]
In addition, I performed an additional test displaying the default energy dashboard as supplied in HA
I do see similar behavior there

hh:mm.ss  MB
1:13.00      320
1:16.50      380
1:20.36      423

**Comment by pvmil** [comment]
I'll retest this issue in 2023.2

**Comment by pvmil** [comment]
Retested in (on another tablet (Android 6 based)
Home Assistant 2023.3.5
Supervisor 2023.03.1
Operating System 9.5
Frontend-versie: 20230309.1 - latest

The memory leak is still there

**Comment by StefanoGiu** [comment]
I have the same crash issue with fully kiosk and companion app. How can I disable the energy card and try again?

**Comment by StefanoGiu** [comment]
btw, my tablet is now showing the standard energy card of HA, but my dashboard.
