### ISSUE TITLE
Display glitch

### ISSUE THREAD

**Issue by inconsx** [home-assistant/frontend#14356]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The status for the entity volant is shown as '0%' when closed.
For all other entities if they're closed no percentage is indicated.

![image](https://user-images.githubusercontent.com/22166678/201066935-6787a6be-5108-4dc4-83da-181503a23e79.png)

### Describe the behavior you expected

for entity 'volant' it shouldn't be shown percentage indicator as well.

### Steps to reproduce the issue

1.close volant
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.11.2

### What was the last working version of Home Assistant Core?

2022.11.2

### In which browser are you experiencing the issue with?

Google Chrome 107.0.5304.107

### Which operating system are you using to run this browser?

windows 10

**Comment by spacegaier** [comment]
We need a lot more info to have a chance at reproducing that. For starters, please fill in the entity states of the two entities from your screenshot as well as the frontend card configuration.
