### ISSUE TITLE
Back button cycles between Add-ons page and specific add-on page

### ISSUE THREAD

**Issue by Sticky12** [home-assistant/frontend#14355]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If you go to Settings - Add-ons and go back once, it will go back to Settings, so this works as intended.

When going to Settings - Add-ons  and then click on any add-on and click the back button, it will cycle between the add-on page you clicked and the main Add-ons page, it will never go back to Settings.

This issue is annoyting on mobile, but it is possible to come back to settings, when using the back functionality on the phone (physical button or gesture).

### Describe the behavior you expected

I expect, when I go to Settings - Add-ons - Node-Red  and click back twice I will end up in Settings again.

### Steps to reproduce the issue

1. Go to Settings
2. Go to Add-ons
3. Go to any add-on
4. Use back button
5. Use back button

### What version of Home Assistant Core has the issue?

2022.11.2

### In which browser are you experiencing the issue with?

Google Chrome  107.0.5304.88

### Which operating system are you using to run this browser?

Windows 10 21H1

**Comment by KarlStrachan** [comment]
I have the exact same issue.

**Comment by CFenner** [comment]
Same here

**Comment by docwisdom** [comment]
Same experience on iOS app. I have to force quit the app and relaunch to get out of the add-ons screen.

**Comment by XanderTenBoden** [comment]
Same here in the app

**Comment by Mariusthvdb** [comment]
still happening on 2022.11.4

**Comment by dcmartin** [comment]
I don't think the behavior is unexpected due to the underlying navigation that is performed to access the add-on.

That being said, a potential solution would be to provide a "long-press" behavior when the back button is pressed in which the potential dashboard could be displayed OR jump back to the "top-level" or Overview.

**Comment by Mariusthvdb** [comment]
why is this not unexpected? it is faulty, introduced lately  and should be fixed.

**Comment by belkop-ghb** [comment]
The problem occurs with lower screen resolution where the main menu is hidden. Tested on iOS, desktop firefox and chrome displayed only on one half of the monitor. No hamburger menu will be displayed, only back arrow in an neverending loop

**Comment by Mariusthvdb** [comment]
this happens on any resolution. For the sake of it, I just full screened my desktop browser and even then there's no way out.
Just got confirmation though the Frontend team is aware.

**Comment by doddyprodger** [comment]
I found that turning iphone to landscape revealed the sidebar enabling navigation menu, but now this doesnt work either.

**Comment by doddyprodger** [comment]
Workaround (for iOS anyway): switch off Wifi and then back on again. Once it finds the network it'll default back to the Dashboard page automatically.

**Comment by belkop-ghb** [comment]
In iOS swipe from left screen edge to the right. This will show the main menu.

**Comment by doddyprodger** [comment]
WORKAROUND: swiping from left to right brings up the dashboard menu.

**Comment by Mariusthvdb** [comment]
tested the issue itself, and as far as I can see, the navigating has been fixed. can go deep into add-on's, and clicking back bring us where we are supposed to go, and finally also out of the add-on menu.

**Comment by hgregorian** [comment]
Just re-tested myself because of this comment.  Definitely broken when using HomeAssistant Companion in iOS and Chrome/Safari browsers on Mac OS.

Home Assistant 2022.12.8
Supervisor 2022.11.2
Frontend 20221213.1 - latest

Settings > add-ons > any add-on
Press back once, goes to add-ons, press back again, goes back to the specific add-on I just navigated away from.

> tested the issue itself, and as far as I can see, the navigating has been fixed. can go deep into add-on's, and clicking back bring us where we are supposed to go, and finally also out of the add-on menu.
> 
>

**Comment by ludeeus** [comment]
Fixed in https://github.com/home-assistant/frontend/pull/14555 which is a part of the next supervisor release that is currently in need testing.

**Comment by hgregorian** [comment]
Can confirm that post Supervisor 2022.12.1 update, this issue is no longer present.  Thanks @ludeeus
