### ISSUE TITLE
Sidebar Map not showing zones or persons

### ISSUE THREAD

**Issue by Xlinx64** [home-assistant/frontend#14357]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I open the map from the sidebar there are no zones or persons on the map. The map is also completely zoomed out.

![Bildschirmfoto 2022-11-10 um 14 13 11](https://user-images.githubusercontent.com/14150988/201106084-b9aa8e7e-27fe-4bc9-927f-3551b5ca4de5.png)

### Describe the behavior you expected

I expect the map from the sidebar to show my gps trackers and zones.

### Steps to reproduce the issue

1. Open Home Assistant
2. Navigate to the map in the left sidebar

### What version of Home Assistant Core has the issue?

2022.11.2

### In which browser are you experiencing the issue with?

Google Chrome 107.0.5304.110, Firefox 106.0.5

### Which operating system are you using to run this browser?

macOS 12.6.1

**Comment by Lockie85** [comment]
I'm also getting this issue.
