### ISSUE TITLE
Error in translation to Portuguese in Thermostat card

### ISSUE THREAD

**Issue by luisfmrosa** [home-assistant/frontend#14353]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

There is a typo in the Thermostat card in Portuguese translation: state 'Idle' is showing as 'O**s**cioso'. The correct would be 'Ocioso'.

### Describe the behavior you expected

The correct would be 'Ocioso'.

### Steps to reproduce the issue

You need to have a card in the dashboard of type Thermostat. In my case, it was automatically added for a Netatmo valve.

### What version of Home Assistant Core has the issue?

2022.11.2

### In which browser are you experiencing the issue with?

Google Chrome 107.0.5304.106

### Which operating system are you using to run this browser?

Windows 10

**Comment by luisfmrosa** [comment]
Just a precision: this affects only pt_BR, as in pt, 'Idle' is translated to a different but equivalent expression, 'Em espera'.

**Comment by steverep** [comment]
Translations are managed outside the source code by Lokalise.  See the [contributing translations page](https://developers.home-assistant.io/docs/translations/).  Please join the project and make comments or corrections there.  Thanks!
