### ISSUE TITLE
map: sidebar: false stopped working after 2022.11.2 release

### ISSUE THREAD

**Issue by dwd1** [home-assistant/frontend#14350]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Title says it all.
The map sidebar button reapperared after 2022.11.2 release, but I have the following configuration.yaml:
```
map:
  sidebar: false
```

### Describe the behavior you expected

-

### Steps to reproduce the issue

-

### What version of Home Assistant Core has the issue?

2022.11.2

### What was the last working version of Home Assistant Core?

2022.11.1

**Comment by spacegaier** [comment]
I have never seen anything like that and also cannot find anything related in the coding or docs. Is that something that really worked? Any references?
