### ISSUE TITLE
Automation Edit in YAML changes formatting for templates

### ISSUE THREAD

**Issue by segfaultex** [home-assistant/frontend#14368]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When editing an Automation in the gui selecting "Edit in YAML" applies unwanted formatting to templates after saving.

```
  - service: notify.gmail
    data_template:
      message: >
        {%- for entity_id in states.binary_sensor.leak_sensors.attributes.entity_id -%}
        {%- set domain, device = entity_id.split('.') -%}
        {%- if states[domain][device].state == 'off' -%} 
        Water Leak Sensor [{{device}}] Detected a Leak!
        {% endif -%}
        {%- endfor %}
        Shutting off the Water.
      title: WATER LEAK DETECTED
```

```
Water Leak Sensor [basement_bathroom_leak_water_leak] Detected a Leak!
Water Leak Sensor [downstairs_bathroom_leak_sensor_water_leak] Detected a Leak!
Water Leak Sensor [laundry_room_leak_water_leak] Detected a Leak!

Shutting off the Water.
```

Turns into

```
  - service: notify.gmail
    data_template:
      message: >
        {%- for entity_id in
        states.binary_sensor.leak_sensors.attributes.entity_id -%} {%- set
        domain, device = entity_id.split('.') -%} {%- if
        states[domain][device].state == 'on' -%}  Water Leak Sensor [{{device}}]
        Detected a Leak! {% endif -%} {%- endfor %} Shutting off the Water.
      title: WATER LEAK DETECTED
```

```
Water Leak Sensor [basement_bathroom_leak_water_leak] Detected a Leak! Water Leak Sensor [downstairs_bathroom_leak_sensor_water_leak] Detected a Leak! Water Leak Sensor [laundry_room_leak_water_leak] Detected a Leak! Shutting off the Water.
```

### Describe the behavior you expected

I would expect the "Edit in YAML" option to not format the text of the yaml different from how it was input.

### Steps to reproduce the issue

1. Create an Automation using "Edit in YAML"
2. Use a multi line template
3. Save the Automation
4. Edit the Automation
5. Formatting is different from what was initially input

### What version of Home Assistant Core has the issue?

2022.11.2

### In which browser are you experiencing the issue with?

Google Chrome 107.0.5304.107

### Which operating system are you using to run this browser?

Windows 11

**Comment by AlfaBravoX** [comment]
Same problem here
