### ISSUE TITLE
History: binary sensors and graphs are not displayed in sync

### ISSUE THREAD

**Issue by tk5011** [home-assistant/frontend#14363]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I add a binary sensor and a graph to the HA history view, the entities are quite a bit out of sync. 
(Sorry I'm new to HA and I don't have the exact technical terms at hand - but the screenshot makes it clear :-) )

![2022-11-11 08_22_29-History – Home Assistant](https://user-images.githubusercontent.com/73420901/201288687-70b4d84f-d43b-4309-80a0-02717ba7fd7d.png)

### Describe the behavior you expected

It would be great, if the upper and lower area (see screenshot) would be synchronized in terms of time

![image](https://user-images.githubusercontent.com/73420901/201289016-f74a37a0-65d6-4885-9bf3-2fff2a6796da.png)

### Steps to reproduce the issue

1. Go into History
2. Add a Binary Sensor 
3. Add a entity that is displayed as graph
...

### What version of Home Assistant Core has the issue?

2022.10.2

### In which browser are you experiencing the issue with?

Google Chrome 107.0.5304.63

### Which operating system are you using to run this browser?

Windows 10 Enterprise 22H2

**Comment by ildar170975** [comment]
https://github.com/home-assistant/frontend/issues/3707
https://github.com/home-assistant/frontend/issues/11011
https://github.com/home-assistant/frontend/issues/10234
https://github.com/home-assistant/frontend/issues/10508
https://github.com/home-assistant/frontend/issues/13176
https://github.com/home-assistant/frontend/discussions/10296
https://github.com/home-assistant/frontend/discussions/11265
https://community.home-assistant.io/t/request-common-or-aligned-time-axis-on-all-history-graphs/246613
https://github.com/home-assistant/frontend/discussions/13355
