### ISSUE TITLE
Light color temperature setting not remembered in scenes

### ISSUE THREAD

**Issue by il0** [home-assistant/frontend#14370]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When editing a scene with Light entity, the light color temperature is not saved. There's been discussion about this [here](https://community.home-assistant.io/t/rgbw-lights-temperature-not-working/322311).

[Screen recording ](https://www.youtube.com/watch?v=QUrjZzU_DBY)of the bug.

### Describe the behavior you expected

After the color temperature slider has been moved and you close the light dialog, the new color temperature value should have been saved to the entity.

### Steps to reproduce the issue

1. Create a new scene
2. Add Light entity
3. Click the entity to open settings
4. Click to turn the light on
5. Click temperature tab
6. Move the color temperature slider
7. Close the entity
8. Save the scene
9. Click the entity again
10. Click temperature tab
...

### What version of Home Assistant Core has the issue?

2022.11.2

### In which browser are you experiencing the issue with?

Google Chrome, Brave, Companion app for iphone

### Which operating system are you using to run this browser?

MacOS, iOS

**Comment by spacegaier** [comment]
I am not able to reproduce the issue in the current development version. I tried both a light that only supports color temperature and one that has both color and color temperature. In both instances the color temperature was correctly written to the scene and recalled when loading the scene.

**Comment by il0** [comment]
@spacegaier that's great to hear that this has been fixed in the dev version!
