### ISSUE TITLE
Yaml only integrations in submenus error with Config flow could not be loaded: {"message":"Invalid handler specified"} 

### ISSUE THREAD

**Issue by eelcohn** [home-assistant/frontend#14376]
### The problem

Configuring ~~the Telegram Bot integration~~ for multiple integrations through the GUI (**Settings** -> **Devices & Services** -> **Add Integration**) fails:
```Config flow could not be loaded: {"message":"Invalid handler specified"}```

### What version of Home Assistant Core has the issue?

Hone Assistant Core 2022.11.1
Hone Assistant Core 2022.11.2

### What was the last working version of Home Assistant Core?

Unknown

### What type of installation are you running?

Home Assistant Container (docker)

### Integration causing the issue

Telegram Bot

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/telegram_bot/

### Diagnostics information

Not available since I could not set up the Telegram Bot integration

### Anything in the logs that might be useful for us?

```txt
Details from the logger:

Logger: homeassistant.config_entries
Source: config_entries.py:809
First occurred: November 5, 2022 at 10:27:27 PM (3 occurrences)
Last logged: 10:23:06 AM
Error occurred loading configuration flow for integration telegram_bot: No module named 'homeassistant.components.telegram_bot.config_flow'
```

### Additional information

Currently I've set up the Telegram Bot integration by using a yaml file, but I want to switch to the GUI installation. I've already tried to remove that part of the yaml config, restart Home Assistant and then add the Telegram Bot integration in the GUI, but it throws the same error.

-EDIT 8 nov 2022-:
Apparently this issue isn't limited by the Telegram Bot integration. Other integrations seem to be affected as well. The following integrations seem to have this problem:

- Applie iTunes (@RoganDawes @eelcohn)
- Aruba (@LordNex)
- Cisco iOS (@LordNex)
- Cisco Mobility Express (@klmi)
- Ffmpeg (@LordNex)
- Google TTS (@alabammaham)
- Lidarr (@philou669)
- OpenWRT luci (@GuyKh, @eelcohn, @RoganDawes, @louisguiot)
- QNap (@mcclown home-assistant/core#81827)
- Radio Browser (@keithellis74)
- Telegram (@alabammaham)
- Telegram Bot (reported by @eelcohn)

The following integrations have been reported as still working:
- Generic Camera (@RoganDawes)
- Radio Browser (@eelcohn @keithellis74)

**Comment by fballiano** [comment]
I still get Error occurred loading configuration flow for integration telegram_bot: No module named 'homeassistant.components.telegram_bot.config_flow' when trying to install telegram_bot

**Comment by riddertommie** [comment]
FYI 

I'm getting it (today) when i tried to install better thermostat.

First installed it via HACS, that went OK
After that, via hassio > settings > integration and that gave me the error;  _Config flow could not be loaded: {"message":"Invalid handler specified"}_

**Comment by jtwild** [comment]
I am getting the same error for the [Renault integration](https://www.home-assistant.io/integrations/renault/), 
I tried to do it via the mobile app and via browser, same error. Also a reboot had no effect.

Versions:
Home Assistant 2022.11.3
Supervisor 2022.10.2
Operating System 9.3 (running on Raspberry Pi 4)
Frontend 20221108.0

**Comment by Niceman35** [comment]
Same error with the Atrea integration from HACS.

**Comment by jtwild** [comment]
This issue is closed, but it is still present for me,. Currently on version 2022.12.1, OS 9.3.
@eelcohn is it fixed for you?

**Comment by EnochPrime** [comment]
I just ran into this as well on 2022.12.0 when pressing "change device type of a switch options".

**Comment by eelcohn** [comment]
I haven't seen this issue yet in v2022.12.0.
@jtwild @EnochPrime can you tell me which integration is causing problems for you?

**Comment by jtwild** [comment]
For me it is the Renault Integration, versions:
OS 9.3
HA v2022.12.0 (sorry, commented wrong version in my prev post. This is the correct one)
Supervisor 2022.11.2
Frontend 20221207.0

**Comment by EnochPrime** [comment]
> I haven't seen this issue yet in v2022.12.0. @jtwild @EnochPrime can you tell me which integration is causing problems for you?

I'm seeing it with change device type (formally switch-as-x). 

https://user-images.githubusercontent.com/1175190/206859950-7d2f06f2-3f96-4348-8a25-a2f178d3397c.mp4

**Comment by xhemp** [comment]
This also just happened to me with the Google Nest integration.

**Comment by TxemaMLL** [comment]
This still happens to me on Gateway 3 integration on the lastest version:
Home Assistant 2023.1.5
Supervisor 2022.12.1
Operating System 9.4

**Comment by jtwild** [comment]
For me, it stopped occurring with the Renault integration after the latest update 2023.1.5.
