### ISSUE TITLE
Temperature for Tuya thermostat wrong

### ISSUE THREAD

**Issue by F8VPE** [home-assistant/frontend#14399]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using a Tuya thermostat with the temperatures of 22 and 21 degree in Tuya gives me 4.4 and 4.2 degree in H.A.
Type thermostat DXstring 006 (Amazon)

### Describe the behavior you expected

Correct temperatures displayed

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

all

### What was the last working version of Home Assistant Core?

2022.11.2

### In which browser are you experiencing the issue with?

all

### Which operating system are you using to run this browser?

Windows 10 pro and Android 10

**Comment by frenck** [comment]
This is not a frontend issue. Please report issues with integrations in the core issue tracker:

<https://github.com/home-assistant/core/issues>

Please make sure you check if your issue has been reported previously already before creating a new one.

Thanks! 👍 

../Frenck

**Comment by F8VPE** [comment]
Tks, found #77736 but cannot find files concerning to change them
