### ISSUE TITLE
Energy tab - missing translations

### ISSUE THREAD

**Issue by dolenec** [home-assistant/frontend#14400]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After 2022.11.xx there is missing translation for the text:
Water consumption
Water
Low-carbon
Solar total
Water total
Low-carbon energy consumed

![Screenshot_20221117_112805_Home Assistant](https://user-images.githubusercontent.com/16633222/202422690-34c90d7e-fb67-4324-b599-e191254b1527.jpg)

![Screenshot_20221117_112835_Home Assistant](https://user-images.githubusercontent.com/16633222/202422705-2f289ca8-98db-416d-8fe7-4b6dce33e25f.jpg)

![Screenshot_20221117_112855_Home Assistant](https://user-images.githubusercontent.com/16633222/202422751-74782576-7ff4-4645-8a59-961c96a3481b.jpg)

### Describe the behavior you expected

All text to be translated..

### Steps to reproduce the issue

1. Simply open Energy dashboard in Slovenian (Slovene) language..

### What version of Home Assistant Core has the issue?

2022.11.3

### What was the last working version of Home Assistant Core?

2022.10.xx

### In which browser are you experiencing the issue with?

Firefix, Chrome, Samsung Browser, in-App

### Which operating system are you using to run this browser?

Windows 11, Android

**Comment by joddye2** [comment]
2022.11.2 has the translations but it cause issues with alignment.
https://github.com/home-assistant/frontend/issues/14286

**Comment by steverep** [comment]
Did you check to make sure they are actually translated in Lokalise?  If they haven't been, it defaults back to English.

**Comment by dolenec** [comment]
![Screenshot_20221208_185606_Home Assistant](https://user-images.githubusercontent.com/16633222/206709144-18de96b5-f77a-4950-a827-1f1fba79deee.jpg)

![Screenshot_20221208_185547_Home Assistant](https://user-images.githubusercontent.com/16633222/206709196-26eaa7b0-74a8-4633-93a9-2f90acdb1efe.jpg)

![Screenshot_20221208_185508_Home Assistant](https://user-images.githubusercontent.com/16633222/206709230-e28519d9-7feb-4d0c-897a-53f7e91e643d.jpg)

**Comment by steverep** [comment]
> if translation is missing then please provide me link where I can make proper Slovenian translation.

Follow the instructions here: https://developers.home-assistant.io/docs/translations/

Your issue notes that these translations existed in 2022.10 - is that correct?  I do not see them translated in the Slovenian.

**Comment by dolenec** [comment]
I made now missing translations..

When it can ne expected this to be published?

**Comment by steverep** [comment]
I believe they need to be reviewed in Lokalise first, but they would be in the next release once that happens.
