### ISSUE TITLE
Updating the HVAC Temperature (and nothing else) won't bring up the save disk.

### ISSUE THREAD

**Issue by haydonryan** [home-assistant/frontend#14444]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

It recently went from summer to winter in Texas, and I wanted to update the HVAC parameters for my scenes.  However I found that I changed the mode from cool to heat and adjusted the temp and wasn't able to save.

I was able to save by adding a new light and deleting it.

### Describe the behavior you expected

Save temp only changes to the HVAC system.

### Steps to reproduce the issue

1. Create a scene with a hvac unit in it (I'm using google nest  and carrier (via infinitude) integrations)
2.  Go in and edit the scene.
...

### What version of Home Assistant Core has the issue?

 2022.11.4

### In which browser are you experiencing the issue with?

Firefox + chrome

### Which operating system are you using to run this browser?

Linux (arch) and windows 10

**Comment by spacegaier** [comment]
I cannot reproduce the issue in the latest dev version. After changing the target temperature it takes a second until the frontend sends the new target value to the backend and then the save button for the scene appears.

The other HVAC params I tested (e.g. mode and target humidity) were instant and also resulted in the save button being shown.
