### ISSUE TITLE
statistic or statistic graph doesn't support ruuvi-hass.io integration

### ISSUE THREAD

**Issue by zeminator** [home-assistant/frontend#14441]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

statistic or statistic graph doesn't support ruuvi-hass.io integration. Can't add sensors

### Describe the behavior you expected

I could add RuuviTags from HA integration to statics card. 

### Steps to reproduce the issue

1. Get HA
2. Get RuuviTag
3. Configure 
4. Try to add statics card with RuuviTag
...

### What version of Home Assistant Core has the issue?

2022.11.4

### What was the last working version of Home Assistant Core?

none

### In which browser are you experiencing the issue with?

all

### Which operating system are you using to run this browser?

win

### State of relevant entities

```txt
n/a
```

### Problem-relevant frontend configuration

```yaml
n/a
```

### Javascript errors shown in your browser console/inspector

```txt
n/a
```

### Additional information

n/a

**Comment by spacegaier** [comment]
Not a frontend bug. The integration has to provide the statistics, see https://github.com/ruuvi-friends/ruuvi-hass.io/issues/36.
