### ISSUE TITLE
Color Temperature Selector not working

### ISSUE THREAD

**Issue by HarvsG** [home-assistant/frontend#14440]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I assume since the transition to Kelvin the Mireds color temperature slider does not render in the call service UI or in template inputs.
The color temperature (Kelvin) does render but only as a number slider.
![image](https://user-images.githubusercontent.com/11440490/203618653-aa3760b5-ee31-4e7c-8888-d35509924cc2.png)

### Describe the behavior you expected

1. The slider to appear for color temperature
2. For Kelvin selection to use color temperature slider (with color gradient inverted) and not the number slider
![image](https://user-images.githubusercontent.com/11440490/203624102-846fe0e4-3304-4006-a774-d1f359b96875.png)

### Steps to reproduce the issue

1. Developer Tools
2. Service
3. Light: Turn On
...

### What version of Home Assistant Core has the issue?

2022.11.4

### In which browser are you experiencing the issue with?

Chrome and Edge

### Which operating system are you using to run this browser?

Windows 10

### Additional information
Docs on the color temperature selector https://www.home-assistant.io/docs/blueprint/selectors/#color-temperature-selector

**Comment by spacegaier** [comment]
I cannot confirm the issue with the missing Mired color temperature selector. That one worked fine for me. But for Kelvin we did not yet have support (neither in frontend nor backend) which I now added.

**Comment by HarvsG** [comment]
Seems at least one other user is having the issue:
https://community.home-assistant.io/t/automatic-circadian-lighting-match-your-lights-color-temperature-to-the-sun/472105/4?u=harvsg

**Comment by HarvsG** [comment]
Still an isssue
