### ISSUE TITLE
Energy dashboard - bad values for water in comparison 

### ISSUE THREAD

**Issue by PetrMa** [home-assistant/frontend#14442]
### The problem

Hello,

If I choise the data comparison in Energy dashboard, the water previous values are the same as current values independently on compared period. 

### What version of Home Assistant Core has the issue?

2022.11.4

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Energy dashboard

**Comment by RoboMagus** [comment]
Just figured I found the same issue. After looking into the code added to the energy dashboard for the water consumption it seems some copy-paste mistakes were made by @bramkragten.

Created a PR that should fix these issues :)
