### ISSUE TITLE
Automation actions modify unavailable with NFC tags

### ISSUE THREAD

**Issue by lexhobbi** [home-assistant/frontend#14457]
### The problem

Steps to show the bug in the mobile application:
1. Create and write an NFC tag on Tags page (NFC, QR codes)
2. Automate that with second icon (also create automation actions)
3. Save that and step back to Tags page
4. Try to modify your automation with second icon again
5. The automation actions disappeared and you can not change those anymore, you have to create steps again

### What version of Home Assistant Core has the issue?

2022.11.3

### What type of installation are you running?

Home Assistant Supervised

### Integration causing the issue

Automation with NFC tag

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/tag/

### Additional information

Mobile application version: beta-2914-23e65c49-full

Please forgive me if I forgot something! This is my first bug report :) ..

**Comment by balloob** [comment]
The robot icon creates a new automation. It doesn’t allow editing a single automation tied to this tag.

**Comment by remyderuysscher** [comment]
The new automation is not saved when writing a new tag. The action is not saved, nor an error in the logfile.

**Comment by balloob** [comment]
When you hit the robot tag, you are sent to the automation editor to create a new automation. You can hit “save automation” in bottom right as usual in the automation editor. 

I am not sure if I understand your issue. Can you add some screenshots?

**Comment by remyderuysscher** [comment]
![Screenshot_20221126-191147_Home Assistant](https://user-images.githubusercontent.com/13978423/204103237-022189c5-b0ea-4a04-baf7-b406195e075e.png)
![Screenshot_20221126-191225_Home Assistant](https://user-images.githubusercontent.com/13978423/204103240-0ce4753e-5305-442f-88df-d10e71a3caa7.png)

Sure, when selecting an action. The screen rename tags pops up and when saving the tag automation the action is empty.

**Comment by remyderuysscher** [comment]
So you have a new written tag with no working automation.

**Comment by balloob** [comment]
did you press "Voeg actie toe"?

**Comment by remyderuysscher** [comment]
> did you press "Voeg actie toe"?

Yes I did but this is the result after a new tag is written and saved. Can you reproduce it?  @lexhobbi can you confirm you still have this issue?

**Comment by hwurst2** [comment]
I have this issue too. Also just started using the NFC Tags

**Comment by remyderuysscher** [comment]
I've found out that the bug is in the flow of writing the tag.  The tag is written successful but the action of the automation is not saved. 

Workaround: If you go to automations and edit the action of the automation the tag is working.

**Comment by olivierdj** [comment]
In either the companion app or in the HA browser version there is only an option to create new automation. Not to edit the existing automation. Every time I do click on the robot icon to create a new one the automation is added to the automations.yaml file. So then you will end up with several automations under the same tag ID. The result is that the automation for the tag does not work  anymore.
The only way to edit an existing tag automation is to directly edit in the automations.yaml file.

**Comment by collinthorn** [comment]
Was trying to program a tag myself, having problems re-opening the tag's GUI design/programming upon saving. I think my problem matches this one and it is still present in the most recent version of HA. The YAML for the tag is present in automations.yml, but it is not appearing in the HA NFC tag GUI interface after saving.

**Comment by SportsApps** [comment]
I have the same issue with tag.
Imposible edit automations but in the automations.yaml.
The configurariton desapear once an automation is created, but the tag still working.

**Comment by TMogdans** [comment]
I can replicate that.

But as I understand this feature, it's not a technical bug, it's wrong expectations of the UI.

New NFC tags can be created under "Settings->NFC tags" and the editor for "new automations" is then called up with the "robot icon".
This button never calls up the created automation to edit it, only the editor for new automation. The tooltip of the button also describes this.
The created automation can then be edited via "Settings->Automations & Scenes". 

And that confused me too. :)

**Comment by sirfalo** [comment]
I have latest release and this issue still exists.
2023.11.3

I can create automation with NFC tag, it is stored in automations.yaml, can be executed, but it is NOT visible in UI (just TRIGGER).

**Comment by mathieuruellan** [comment]
Still exists with the latest docker at this day.
Core 2024.2.1
Frontend 20240207.1

**Comment by RedsGT** [comment]
Ran into this as well and had to Google it to find this item. Needs some work.

**Comment by mathieuruellan** [comment]
Actually, it creates an automation. I can edit it in the automation menu and save it. So i can do what i want, but there is an "ux" problem. The first interface is not clear or wrong.

**Comment by julienaltieri** [comment]
+1 to the above on expection
My immediate intuition was that I could edit the automation I just had created for this tag and went to find it by the same route I created it from (NFC menu)
It seems that the intention was to add multiple automation to 1 tag, but that seems confusing and hard to maintain without a proper UI to see the list of automation a tag is attached to.

**Comment by monza21** [comment]
Is it possible to reopen this issue.  My reaction was the same as others have described.  Having the robot icon create a new automation and not edit previously created automations attached to the NFC tag is confusing.
