### ISSUE TITLE
Energy graphs not showing meter history

### ISSUE THREAD

**Issue by cure1245** [home-assistant/frontend#14450]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am reading my energy meter's AMR signal using an SDR that reports to an MQTT broker. About a week ago, the bar graphs showing usage per time period are no longer appearing, although the graph scaling and amounts below the graph are accurate:
![image](https://user-images.githubusercontent.com/4430996/203820251-a11c6ebe-ffc4-4ac8-acee-fa5fd4a82126.png)
Here's a picture of the raw meter sensor:
![image](https://user-images.githubusercontent.com/4430996/203820858-ef1f280e-d070-4555-a662-eb709238af90.png)

### Describe the behavior you expected

I expect there to be bars showing on the graph.

### Steps to reproduce the issue

1. Use MQTT to connect an energy meter entity
2. 
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.12.0.dev20221124

### In which browser are you experiencing the issue with?

All broswers

### Which operating system are you using to run this browser?

Any OS

**Comment by ZsBT** [comment]
same here, 2022.12.0.dev20221119 in docker

**Comment by cure1245** [comment]
So I updated my docker container to 2023.1.0.dev20221202 about 24 hours before writing this, and within the last 15 minutes as of writing this the bars returned. I was looking at the energy dashboard, I went to the meter sensor history and set the history graph to a three hour window, and when I went back to the dashboard it was all there!

**Comment by ZsBT** [comment]
> same here, 2022.12.0.dev20221119 in docker

I had to purge tables `statistics` and `statistics_meta`. After HA started to collect new sensor data, it appears again on the dashboard. I don't get what could caused incompatibility, but at least I have graphs again.

**Comment by cure1245** [comment]
Well, I guess since we were the only two people who mentioned having it and we're both good now I'll close the issue out.

**Comment by cure1245** [comment]
So I just updated to 2022.12.4 and the issue has returned...
