### ISSUE TITLE
Sensor Card doesn't show in Google Nest Hub

### ISSUE THREAD

**Issue by chiahsing** [home-assistant/frontend#14465]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The value of the sensor card shows correctly. The graph is the one that is not loading. The loading circle is spinning all the time.

### Describe the behavior you expected

The card shows the graph.

### Steps to reproduce the issue

1. Add a sensor card with graph to a dashboard
2. DashCast it to a Google Nest Hub (with force=true)
3. Login (will need to set up trusted_network and trusted_user as you cannot type username and password in Nest Hub. There's no virtual keyboard)

### What version of Home Assistant Core has the issue?

2022.11.4

### In which browser are you experiencing the issue with?

Google Chrome 90.0.4430.225

### Which operating system are you using to run this browser?

Google Nest Hub (Linux; Android)

### Problem-relevant frontend configuration

```yaml
title: Home
views:
  - theme: Backend-selected
    path: default-view
    title: Home
    badges: []
    cards:
      - type: sensor
        entity: sensor.disk_use_percent
        graph: line
      - hours_to_show: 24
        graph: line
        type: sensor
        entity: sensor.study_temperature
        detail: 1
```

### Javascript errors shown in your browser console/inspector

```txt
styles.ts:371 GET https://xxx.xxx.xxx:8123/api/history/period/2022-11-27T14:06:24.849Z?filter_entity_id=sensor.disk_use_percent&end_time=2022-11-28T14:06:24.849Z&minimal_response 401 (Unauthorized)
styles.ts:371 GET https://xxx.xxx.xxx:8123/api/history/period/2022-11-27T14:06:24.882Z?filter_entity_id=sensor.study_temperature&end_time=2022-11-28T14:06:24.882Z&minimal_response 401 (Unauthorized)
hui-graph-header-footer.ts:104 Uncaught (in promise) {error: "Response error: 401", status_code: 401, body: "401: Unauthorized"}
hui-graph-header-footer.ts:104 Uncaught (in promise) {error: "Response error: 401", status_code: 401, body: "401: Unauthorized"}
```

### Additional information

While this happens to Nest Hub, other platforms (e.g. my desktop) work just fine.

I managed to attach Chrome remote debugger to my Nest Hub (by registering a Cast SDK account, paying $5, cloning DashCast as my own application, and using that to cast the dashboard). I checked the log and found the javascript error above. There's also a relevant log on the server side:
`2022-11-28 14:06:24.875 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.2.0.103 (10.2.0.103). Requested URL: '/api/history/period/2022-11-27T14:06:24.849Z?filter_entity_id=sensor.disk_use_percent&end_time=2022-11-28T14:06:24.849Z&minimal_response'. (Mozilla/5.0 (Linux; Android) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.225 Safari/537.36 CrKey/1.56.500000)
`
where 10.2.0.103 is my Google Nest Hub internal IP.

I am not very familiar with frontend debugging, but I found that if I go to DevTools in the Chrome remote debugger, and click Application > Storage > Clear site data (with only "unregister service workers" checked and everything else unchecked), it will trigger the browser to reload, and after it logs back in (automatically if keep-me-logged-in is selected) the sensor card will work again! But, after like 3 seconds, the dashboard would "crash" and reloads itself. And after that the sensor card will stop working again.

Another thing I noticed is that if I click "Clear site data" with everything checked, the service worker will busy loading a bunch of files with 8-byte long hex-digit file names, like ffb6139a.js, starting with 00xxxxxx and ending with ffxxxxx. And at the end right after loading the last file or so, it would "crash" the dashboard which triggers reloading. And after that, the sensor no longer works. And since scanning from 00 to ff takes some time, if I log in before it crashes, the sensor card works just fine. But the crash is still inevitable.

I am happy to provide more information. Please let me know what I can do. Thanks!

**Comment by chiahsing** [comment]
I probably should rephrase. It's probably not a "crash". It's more like a spontaneous reload. This reload also happens on the desktop browser, but the sensor card works just fine on the desktop.

**Comment by chiahsing** [comment]
One more thing, for the failed HTTP request that get 401 unauthorized, the "authorization" header was set with a value that looks valid.

**Comment by bramkragten** [comment]
Why do you use dashcast and not the official Home Assistant cast app? <https://cast.home-assistant.io/>

Can you try that? We don't support using other tools to cast dashboards.

**Comment by chiahsing** [comment]
Back to the original issue, even though this is not officially support, I still want to put some findings and updates here in case other people run into the same problem in the future. (I hope not!)

So, from chrome debugger, it seems that the successful request was sent directly (without the service worker) to the server, while the failed one was sent via the service worker. It seems that the service worker dropped the 'authorization' header, and hence the server rejected the request.

**Comment by chiahsing** [comment]
It seems to be a box in workbox or Chrome. Also filed https://github.com/GoogleChrome/workbox/issues/3135

**Comment by chiahsing** [comment]
Since we have a `supportsServiceWorker()` function in `register-service-worker.ts`, can we add some logic to disable it on certain conditions? For example, by checking CrKey in the user agent and disable service workers for all Chromecast devices, or maybe a less intrusive one by checking some args in the URL (I am not sure if this works).

Another workaround with any code change would be to fallback to http instead of https, but it's less ideal.
