### ISSUE TITLE
Nobo Integration Preset state when in Auto not showing

### ISSUE THREAD

**Issue by mjfear** [home-assistant/frontend#14470]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When updating to Heat mode remotely (e.g. through phone app), home assistant Nobo Integration shows updates to preset mode instantaneously. When in Auto mode, preset does not update - e.g. schedule change from away to eco remains visible in home assistant as away, rather than updating to eco.

### Describe the behavior you expected

When schedule changes preset mode, that updated preset mode to be visible on home assistant.

### Steps to reproduce the issue

1. Set up Nobo integration
2. In a given zone using Nobo phone app, set schedule to change from one preset to another (e.g. eco to away, away to comfort).
3. Monitor preset as read in home assistant
4.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.11.4

### In which browser are you experiencing the issue with?

Chrome Version 106.0.5249.134 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Chrome OS Version 106.0.5249.134 (Official Build) (64-bit)

**Comment by spacegaier** [comment]
Can you check in the HA dev tools, if the state of the entity changes and the frontend is just not updating/showing it in your dashboard or whether the integration itself does not get notified in your scenario with "Auto" mode.

**Comment by mjfear** [comment]
I've checked HA dev tools and can confirm that:

Phone app reads: mode = Auto, preset = away
HA dev tools entity search reads: mode = Auto, preset = eco
HA dashboard reads: mode = Auto, preset = eco

**Comment by mjfear** [comment]
@spacegaier have checked the above - any further info required from me?
