### ISSUE TITLE
Tile Card slider min brightness not 0

### ISSUE THREAD

**Issue by pedolsky** [home-assistant/frontend#14498]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Testing the new slider feature of Tile Card, the min brightness is 1% and not 0. Because of this the light doesn’t turn off. 

### Describe the behavior you expected

Brightness setting to 0

### Steps to reproduce the issue

1. Create a new frontend card by selecting Tile
2. Select function -> brightness (don’t know how it is labelled in English)
3. Try to turn off the light by moving the slider to the left.
...

### What version of Home Assistant Core has the issue?

core-2022.12.0b0

### In which browser are you experiencing the issue with?

Safari 16.1.1, Chrome 108.0.5359.52

### Which operating system are you using to run this browser?

iPadOS 16.1.1

### Additional information

[https://www.home-assistant.io/integrations/tile/](https://www.home-assistant.io/integrations/tile/)

**Comment by piitaya** [comment]
Hi 🙂 You can toggle the light using the icon.
There is the inverse issue in Mushroom : https://github.com/piitaya/lovelace-mushroom/issues/847 😅

**Comment by bramkragten** [comment]
This is consistent with the other brightness sliders in Home Assistant. So by design 🙃
