### ISSUE TITLE
Calendar editor date/time picker inconsistencies

### ISSUE THREAD

**Issue by allenporter** [home-assistant/frontend#14497]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The video below was reported in #beta but i haven't had a chance to reproduce it yet.

I also see a few inconsistencies with time zones. Ideally we'd be dealing with everything in the local timestamp, but its using UTC. This has issues when then converting back to an all day event: The date is not the correct date when you truncate of the time and timezone offset.

Additionally, an all day even should be sent to the server without a time.

### Describe the behavior you expected

Ideally all the date manipulations in the frontend could be all done in local or floating date/times but this seems super hard in javascript dates

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

dev / beta

### Additional information

Uploading Video_1.mov…

**Comment by allenporter** [comment]
When creating an event at Dec 1st 10pm:
<img width="426" alt="Dec 1st Create Dialog" src="https://user-images.githubusercontent.com/6026418/204986222-e81614ee-b35b-4a2f-b70e-144312586594.png">

It sends this request
```
dtend: "2022-12-01T23:00:00.000Z"
dtstart: "2022-12-01T22:00:00.000Z"
summary: "Dec 1st 10pm"
```

And this is the end result:
<img width="384" alt="Dec 1st 10pm" src="https://user-images.githubusercontent.com/6026418/204986220-5b7e2b8f-2d54-47a9-8664-79b8ee63f84d.png">

**Comment by pedolsky** [comment]
No chance on IOS to add an event at all. Should I raise a new issue?
