### ISSUE TITLE
[OVERKIZ] Atlantic Divali Heater (overkiz) not reconized correctly and without climate entity

### ISSUE THREAD

**Issue by Loic691** [home-assistant/frontend#14512]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Atlantic Divali heater isn't recongnized as climate. So we can't use climate lovelace card because there is no climate entity
Instead Atlantic Serenis heater is OK.

### Describe the behavior you expected

Atlantic Divali device should be recognized as climate and we should use climate entity and so climate lovelace card

### Steps to reproduce the issue

1. Configure Overkiz integration
2. Detecting automaticaly device on cozytouch hub
3. Divali are found automaticaly but without climate entity

H'ere is capture which show difference between Serenis and Divali heaters

Divali which is KO
![image](https://user-images.githubusercontent.com/60837526/205246983-81016af7-260b-4a41-abc5-c2db6c9bd919.png)

Serenis wich is OK
![image](https://user-images.githubusercontent.com/60837526/205246896-ffbafe26-3a39-4e99-9023-c0c862144740.png)

### What version of Home Assistant Core has the issue?

2022.11.5

### In which browser are you experiencing the issue with?

Chrome last version

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
No climate entity is created with DIVALI.
Instead with Serenis Heater we have the climate entity
```

**Comment by Loic691** [comment]
Please can you move this issue to Core ?

**Comment by ludeeus** [comment]
The requested information in the core issue template is completely different from the frontend, so its much better if you close this and open a new one for Core so the correct information is in place 👍

**Comment by Loic691** [comment]
Here's the issue in the core
https://github.com/home-assistant/core/issues/83102
