### ISSUE TITLE
"homeassistant_stop" is not an option for Automation

### ISSUE THREAD

**Issue by Coolie1101** [home-assistant/frontend#14511]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Built-In Events is not represented in the Automation UI as documented.

"[HOMEASSISTANT_STOP](https://www.home-assistant.io/docs/configuration/events/#homeassistant_stop-homeassistant_final_write-homeassistant_close)" is not an option.

### Describe the behavior you expected

Display options as documented.

### Steps to reproduce the issue

1. Create new Automation with Home Assistant Trigger and choose "stop" as the event.
...
![image](https://user-images.githubusercontent.com/28989417/205209039-e224faab-1df4-4079-bd3e-9717a252e33b.png)
 

### What version of Home Assistant Core has the issue?

2022.11.4

### In which browser are you experiencing the issue with?

Google Chrome 107.0.5304.123

### Additional information

Automation is not triggered with event "shutdown"

**Comment by Coolie1101** [comment]
😕

So, it should be as pictured below?

![Screenshot_20221202-224901_(1)](https://user-images.githubusercontent.com/28989417/205421312-4a338a07-bb5f-4942-875e-5ba93bca5628.png)

Also, the Home Assistant event "shutdown" doesn't trigger either.

**Comment by spacegaier** [comment]
> So, it should be as pictured below?

I think so, although why would you be using that instead of the recommended HA trigger?

**Comment by Coolie1101** [comment]
Which recommended HA trigger?

**Comment by spacegaier** [comment]
The one from your initial screenshot in this issue. The recommendation is written in the docs where also your link from the issue points to.

Either way, not a bug. If you need further support for your scenario, please use the various [help ](https://www.home-assistant.io/help/) channels.
