### ISSUE TITLE
"Statistic characteristic" not displayed for helper sensors

### ISSUE THREAD

**Issue by pimw1** [home-assistant/frontend#14513]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi,

The new helper "Combine the state of several sensors"  is not displaying the "Statistic characteristic" when editing the sensor.
![image](https://user-images.githubusercontent.com/74881023/205348980-bf3830dc-7a6f-4275-a199-15ddd9bca474.png)

Could this be fixed?

### Describe the behavior you expected

The field "Statistic characteristic" should be displaying the used statistics characteristic

### Steps to reproduce the issue

1. create the helper (in my case with a summation)
2. press e ->select your helper 
3. press settings
4. press "Combine the state of several sensors"
5. you'll see that the field is displayed blank
...

### What version of Home Assistant Core has the issue?

core-2022.12.0b1

### In which browser are you experiencing the issue with?

107.0.5304.123

### Which operating system are you using to run this browser?

Windows 11 Pro

**Comment by krazos** [comment]
Same issue here on 2022.12.0b1.

**Comment by spacegaier** [comment]
Do you also see an error in the browser console along the lines of "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')"?

If yes, then that is the same bug that I am currently trying to hunt down...

**Comment by pimw1** [comment]
Yes, i do get that very same error.
