### ISSUE TITLE
Impossible to Adjust a statistic

### ISSUE THREAD

**Issue by bekovan** [home-assistant/frontend#14519]
### The problem

Changing an incorrect measurement via the Developer tools -> Adjust a statistic, select editable statistic generates error
"
Error adjusting sum: extra keys not allowed @ data['start_time_iso']. Got '2022-12-02T15:30:00.000Z' required key not provided @ data['start_time']. Got None
"
I am sure it was working on the latest stable version, not sure it worked on 2022.12.0b0

### What version of Home Assistant Core has the issue?

Home Assistant 2022.12.0b1

### What type of installation are you running?

Home Assistant OS

**Comment by balloob** [comment]
CC @emontnemery
