### ISSUE TITLE
Error when timezone is not set on new install and general settings page updated

### ISSUE THREAD

**Issue by MikeGuest** [home-assistant/frontend#14520]
### The problem

On a brand new install, added 2022.12.0b0

Repair highlighted that my country was not set. I used the link to get through to the general settings page and set the country. After hitting update:

![country](https://user-images.githubusercontent.com/12844043/205000560-ee1c5211-7d37-4bf9-a455-bca37320466a.PNG)

As suggested by the error, timezone had not been set. However I believe

1) The timezone not being set should be picked up in repairs
2) A more user-friendly error message for being unable to set the timezone would be a UI improvement

Regards

### What version of Home Assistant Core has the issue?

2022.12.0b0

### What type of installation are you running?

Home Assistant OS

**Comment by bramkragten** [comment]
What is the content of the time zone field?

**Comment by bramkragten** [comment]
I'll make the error a bit more user friendly and add a repair issue for the time zone
