### ISSUE TITLE
Calendar date picker is one day behind

### ISSUE THREAD

**Issue by allenporter** [home-assistant/frontend#14539]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When selecting a date from the calendar date picker the resulting day is one day behind.

### Describe the behavior you expected

The day in the text box is the day selected in the calendar date picker widget

### Steps to reproduce the issue

1. Create a new event
2. Select the date picker
3. Pick a date e.g. Sunday Dec 4th
...

Expected: Dec 4th is selected
Actual: Dec 3rd is selected

### What version of Home Assistant Core has the issue?

core-2022.12.0b2
20221201.1 - latest

### Javascript errors shown in your browser console/inspector

```txt
None
```

### Additional information

https://user-images.githubusercontent.com/6026418/205459663-6b4a92a2-088e-4bba-9730-ac5f9c4c41a8.mov

**Comment by spacegaier** [comment]
In #beta @allenporter mentioned he is in timezone PST-7 and the event editor uses `Date.toISOString()` so I was wondering if that might play a role and we are crossing accidentally over midnight somehow?

**Comment by krazos** [comment]
I had previously reported the same bug in the date picker in the statistics adjustment tool:

https://github.com/home-assistant/frontend/issues/14411

I am seeing the same thing in the new calendar event creation panel.

**Comment by allenporter** [comment]
I don't have an answer yet for a solution, and need to run to work but wanted to share what I found so far.

**Comment by allenporter** [comment]
Oh i think the bug is in `ha-date-input`:
```formatDateNumeric(new Date(this.value), this.locale)```

If i run this code in my javascript console it does this:
```
new Date('2022-12-07')
Tue Dec 06 2022 16:00:00 GMT-0800 (Pacific Standard Time)
```
My impression is you can't create a date like this, since its creating it at 2022-12-07 midnight UTC, then converting it to a local date because javascript dates are wild. I think we need to split the date into parts and create it directly with numbers or something, or somehow create this at midnight local, or maybe date-fns parsing makes it possible to create a local datetime.

**Comment by spacegaier** [comment]
This might be related https://github.com/home-assistant/frontend/pull/14587

In my setup it occurs when using start date around midnight since my German timezone is only one hour away from UTC. Based on your mentioned dates and timezone it sounds like the same issue?

**Comment by allenporter** [comment]
@spacegaier I actually started with actually changing all of that and it did not seem to fix my issue.
