### ISSUE TITLE
Double (and different) logo at Android's app start 

### ISSUE THREAD

**Issue by waazdakka** [home-assistant/frontend#14560]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using the Android app (last version I could have find, 2022.11.0-full), the boot shows 2 different logos, the first very rounded and the second more squared as you can see in the video.
Dumb question: why do we have two logos at start, and different ones (I guess one of them take the system settings)
Thanks!! 

https://user-images.githubusercontent.com/9380081/205726846-b4288622-3a6a-424b-aef5-9c90522e4a6c.mp4

### Describe the behavior you expected

Click on Home assistant icon on Android, see the app opening and have only one logo, then land on dashboard

### Steps to reproduce the issue

1. Click on Android app
2. Watch the application starts
3. Seeing 2 different logos with a black screen between

### What version of Home Assistant Core has the issue?

core-2022.11.5

### Which operating system are you using to run this browser?

Android 13

**Comment by spacegaier** [comment]
Sounds like a topic for https://github.com/home-assistant/android

**Comment by dshokouhi** [comment]
the first logo is from the android apps splash screen and yes its slightly different, completely different as well if you are running a debug build since it will be in red. This is to be expected so not a bug IMO.

The flow is app splash screen > Load HA frontend. Don't expect to match browser behavior here as its an app and not a browser tab :)
