### ISSUE TITLE
Problem when selecting services in the user interface

### ISSUE THREAD

**Issue by Anton-Ka** [home-assistant/frontend#14569]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

There is no choice of additional settings after selecting services.
![image](https://user-images.githubusercontent.com/74901464/205881299-89e4b215-80b3-4de4-945c-33b74f9ee8dd.png)

### Describe the behavior you expected

Buttons for selecting objects, entities and other.

### Steps to reproduce the issue

1. Create a new script, automation, select the Services tab in the developer panel;
2. Select add action (for automations and scripts);
3. Select "Services" from the list;
4. Select any service, e.g. homeassistant.turn_off.

### What version of Home Assistant Core has the issue?

2022.11.5

### What was the last working version of Home Assistant Core?

I can not say exactly

### In which browser are you experiencing the issue with?

Google Chrome 108.0.5359.73

### Which operating system are you using to run this browser?

Windows 8.1

### Additional information

Exactly the same behavior is observed in the mobile application for Android.

**Comment by piitaya** [comment]
Hello 🙂
Is it only with this service ? Or others too ? I'm on the beta 2022.12 and I can not reproduce the issue.

**Comment by spacegaier** [comment]
I cannot reproduce it either on 2022.12.0b5

@Anton-Ka Any errors in the browser console?

**Comment by Anton-Ka** [comment]
> Hello 🙂 Is it only with this service ? Or others too ? I'm on the beta 2022.12 and I can not reproduce the issue.

Hi.
I checked all turn_off services in mobile app and only switch.turn_off, script.turn_off, input_boolean.turn_off works.  The rest of the services don't work.

**Comment by Anton-Ka** [comment]
This problem is actually.

**Comment by GvdbW** [comment]
This looks the same as #15885

**Comment by Anton-Ka** [comment]
> This looks the same as #15885

Yes, it looks like it.
Please elaborate on what you did in the post https://github.com/home-assistant/frontend/issues/15885#issuecomment-1522163968 . I didn't understand what is "minimalist" in your post?

**Comment by GvdbW** [comment]
Minimalist is a dashboard for Home Assistant https://github.com/UI-Lovelace-Minimalist/UI

I didn't do anything other than updating it to the latest version in HACS and it worked after a reboot.

**Comment by Anton-Ka** [comment]
I undestand. But i don't have this addon in my HA.
All other is updated.
