### ISSUE TITLE
Statistics Graph card - bars nearly invisible if days > 35

### ISSUE THREAD

**Issue by S-Przybylski** [home-assistant/frontend#14561]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After upgrading to Home Assistant 2022.12.0b4 my 90 days gas comsumption view presented by statistics graph card cannot be read any longer. The bars are nearly transparent. If I reduce the number of presented days to less then 36 it is visible then. Especially the step between 35 and 36 changes the behaviour.

### Describe the behavior you expected

The bars need to be visible with contrast (not in transparent mode).

As described the bars should be visible for more then 35 days

### Steps to reproduce the issue

Create a statistics graph card with the following details:
Entity: engergy [kwh]
Window in Days: 90 ; 36 (not working)   35 (working)
Set digram options to days, state and bar

![statisticsgraphcard-90days](https://user-images.githubusercontent.com/45458593/205743441-519bf76c-4e8a-4612-ae5e-d5d507aad47e.png)
![statisticsgraphcard-36days](https://user-images.githubusercontent.com/45458593/205743454-ce7276e2-1b7d-4885-bc4d-6ae0a3520982.png)
![statisticsgraphcard-35days](https://user-images.githubusercontent.com/45458593/205743462-ba969460-4063-441a-93ba-0d0b6b715983.png)

### What version of Home Assistant Core has the issue?

Home Assistant 2022.12.0b4

### What was the last working version of Home Assistant Core?

Home Assistant 2022.11.5

### In which browser are you experiencing the issue with?

Firefox 107.0.1 (64-Bit); MS Edge Version 107.0.1418.62 (Offizielles Build) (64-Bit)

### Which operating system are you using to run this browser?

Windows 11 64 bit

### State of relevant entities

```txt
state_class: total_increasing
source: sensor.energy_consumption_gastherme
status: collecting
last_period: '70.338'
meter_period: daily
cron pattern: 0 0 * * *
last_reset: '2022-12-04T23:00:00.010905+00:00'
unit_of_measurement: kWh
device_class: energy
icon: mdi:counter
friendly_name: Energiebedarf Gastherme [d]
```

### Problem-relevant frontend configuration

```yaml
chart_type: bar
period: day
days_to_show: 90
type: statistics-graph
entities:
  - sensor.gastherme_energy_consumption_sum_daily
stat_types:
  - state
title: Energie Gas
```

### Javascript errors shown in your browser console/inspector

```txt
na
```

**Comment by infestdead** [comment]
Can confirm this is also the case on official 2022.12.0, for me - anything more than 38 days turns the bars into thin lines as show above.

**Comment by S-Przybylski** [comment]
Is there any news to that issue?
