### ISSUE TITLE
Cannot select dates in 2023 via the date pocker

### ISSUE THREAD

**Issue by devinhedge** [home-assistant/frontend#14574]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

SITUATION:

When I go to select a date in 2023 for a date helper, I cannot.

### Describe the behavior you expected

Using the date picker, navigate to 2023 and select a date. The date then appears in the input_datetime helper’s field.

### Steps to reproduce the issue

1. Via iPhone Home Assistant app
2. Create a date helper
3. Add new date helper entity to Lovelace dashboard by adding the entity via the “Add Entity to Dashboard” using the default suggested cards.
4. Navigate to the date entity in the dashboard
5. Click the Date Picker widget
6. Attempt to select a date in 2023 (you cannot)

### What version of Home Assistant Core has the issue?

2022.11.5

### What was the last working version of Home Assistant Core?

Don’t know

### In which browser are you experiencing the issue with?

iPhone Home Assistant App 2022.10.1

### Which operating system are you using to run this browser?

iOS 16.1.2

### Additional information

Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest

**Comment by devinhedge** [comment]
May be related to #12329

**Comment by spacegaier** [comment]
Does this only apply to iOS or also e.g. on desktop browsers? Works fine for me in Chrome on Windows for example.
