### ISSUE TITLE
Back arrow in settings doesn't play nice with device windows

### ISSUE THREAD

**Issue by Ulrar** [home-assistant/frontend#14571]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The back arrow at the top of every page in the settings works well as long as you don't open any "more info" style pop ups.

For example in the devices page if you click on a device, then on the top left arrow you're brought back to the devices page as expected - great.
But if you click on a device then on any of the sensor to see the graphs, then click out of that and try the back arrow again nothing happens. You have to click it twice to be brought back : once to get 'out' of the pop up which is already gone, and once to get out of the devices.

So it seems the arrow needs to be clicked once for any pop up info you may have seen, which sometimes means tapping on the arrow 10 times to get back. Particularly problematic on phones but also happens on regular desktop browsers.

### Describe the behavior you expected

I'd expect the back arrow to bring me back from the page I'm on, not counting any intermediate pop ups that have already disappeared.
Not sure how this is implemented but I'm guessing dismissing those info pop ups should pop one element out of the history.

### Steps to reproduce the issue

1. Go to any device page
2. Click on a sensor
3. Dismiss the info pop up
4. Try the back arrow

I'm using the devices page as an example but this happens with any page that uses those little window pop up things, whatever they're called. They can be found in integrations configs, by clicking on specific log messages in the viewer ..

### What version of Home Assistant Core has the issue?

2022.11

### In which browser are you experiencing the issue with?

Android app, Firefox Windows, Firefox Linux

### Additional information

It's been like that for a very long time, this is not new behavior.
I assumed there would already be a report of this somewhere here but I couldn't find it, apologies if there is already an issue that I missed. Not knowing how any of these elements are called probably isn't helping.

**Comment by Ulrar** [comment]
Not stale

**Comment by Ulrar** [comment]
Not stale

**Comment by mill1000** [comment]
Also experiencing something like this. I find it hard to replicate but seems to occur when I used the swipe gesture on my Pixel 6a. So perhaps its related to #15507.

**Comment by Ulrar** [comment]
I don't think so, it's certainly also a problem but that other issue is mobile only, since it's gesture related.

This issue is for everything, happens on PC as well and I suspect is caused by the history filling up with device windows but not removing them when they get closed / dismissed, making the back button popping non existing elements.

**Comment by Xitee1** [comment]
I also have this problem. Especially when I'm in a new device and disable lots of entities that I don't need. To navigate back I have to spam click the back button really often. Often I then accidentally go further back that I wanted to.

This problem also exists on the Android App when navigating trough the dashboards. The App should close when I'm on a dashboard, no popups open and I click on the back button twice. However it navigates me trough all the pages I have been in that session.
Also to get out of the settings after doing something it's faster to force quit the App & reopening it than clicking the back button hundred times.

**Comment by gzone156** [comment]
+1, still present in 2023.8.3.

Here is an example GIF:

![HA back](https://github.com/home-assistant/frontend/assets/62515544/3e719592-55a8-4982-aaae-36422f35ff09)

**Comment by daniel-dona** [comment]
Same here, looks like history is not managed properly, have to click back a lot of times to make it really go back...

**Comment by jshatch** [comment]
This happens to me all the time in the iOS app.  Glad to see there is an issue related to it, sad that nobody is doing anything about it.

**Comment by RonaldRegister** [comment]
can confirm, issue is still present and pretty annoying. Also present in the iOS.app

**Comment by Ulrar** [comment]
Still an issue, not stale

**Comment by jshatch** [comment]
Yes still an issue.

**Comment by Ulrar** [comment]
Not stale
