### ISSUE TITLE
Popup in the Log has unneeded scrollbars

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#14583]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

1. Open the Log.
2. Select an error or a message.
3. Popup is displayed with a scrollbar which is not required.

![изображение](https://user-images.githubusercontent.com/71872483/205967317-6923a47e-48f5-408f-a224-7ebc9566e978.png)

### Describe the behavior you expected

Two possible solutions:
1. A scrollbar is not displayed at all, all info should be word-wrapped.
2. A scrollbar is displayed only when necessary.

### Steps to reproduce the issue

As above.

### What version of Home Assistant Core has the issue?

2022.11.4

### In which browser are you experiencing the issue with?

Chrome 107.0.5304.123 

### Which operating system are you using to run this browser?

Win10x64

**Comment by ildar170975** [comment]
@spacegaier 
Here is the latest example (2023.3.0) with a scrollbar:

![изображение](https://user-images.githubusercontent.com/71872483/223228220-c183227c-d6d7-4590-a0fc-d02d2179acca.png)

I would say that HERE a scrollbar is needed.
There is one more glitch ("imperfection") here on this screenshot caused by round borders, but this glitch is NOT related to the current issue, it is related to [another issue](https://github.com/home-assistant/frontend/issues/15664#issuecomment-1456979197).

------------

But here is an example with a NOT needed horizontal scrollbar:

![sc](https://user-images.githubusercontent.com/71872483/223230039-26b67edf-36e2-4e01-943a-b6ae84857eea.gif)

**Comment by ildar170975** [comment]
Still in 2023.6.0:

![image](https://github.com/home-assistant/frontend/assets/71872483/b5fdf5a5-5a73-4740-8cba-825c7fb1c56a)

**Comment by dnestico** [comment]
Even the light popups on my Pixel 7 Pro have an annoying scroll bar now, really want an option to disable it....

**Comment by ildar170975** [comment]
2023.9.3
Cannot reproduce the glitch.
Usually I reproduced it with Waze errors. But since some Waze update these errors are not displayed.
So, may be the problem is still there - I just cannot reproduce it(((.

Closing the issue.
If someone seen it again - please let me know.
