### ISSUE TITLE
Binary sensor state_color: true doesn't work anymore

### ISSUE THREAD

**Issue by gieljnssns** [home-assistant/frontend#14599]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When a binary sensor turns on and when `state_color: true` is enabled, the icon of the binary sensor used to turn yellow.
Now it doesn't 

### Describe the behavior you expected

It should turn yellow

### Steps to reproduce the issue

```
type: entities
entities:
  - entity: binary_sensor.douchen
state_color: true
show_header_toggle: false
```

### What version of Home Assistant Core has the issue?

core-2022.12.0b7

### What was the last working version of Home Assistant Core?

core-2022.11.x

### In which browser are you experiencing the issue with?

Vivaldi	5.5.2805.50 (Stable channel) (x86_64) 

### Which operating system are you using to run this browser?

macOS 12.6.1 (21G217)

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - entity: binary_sensor.douchen
state_color: true
show_header_toggle: false
```

### Additional information

<img width="446" alt="Schermafbeelding 2022-12-07 om 11 07 55" src="https://user-images.githubusercontent.com/17234951/206150253-3473044c-cce1-4f1a-b613-b18bc40109de.png">

<img width="561" alt="Schermafbeelding 2022-12-07 om 11 05 00" src="https://user-images.githubusercontent.com/17234951/206149363-be991bb0-c593-4ea3-acaa-32f6089d8408.png">

**Comment by spacegaier** [comment]
@piitaya

**Comment by piitaya** [comment]
Oh I think I found the issue :
I think your theme is using `--primary-color` for  `--paper-item-icon-color`.

**Comment by gieljnssns** [comment]
@piitaya 
Can you tell me how do I have to change the state color of my binary sensor when it is on?
In my theme…

**Comment by gieljnssns** [comment]
Thanks
