### ISSUE TITLE
Schedule Helper will not add events to Sundays

### ISSUE THREAD

**Issue by themanieldaniel** [home-assistant/frontend#14591]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When adding or editing a helper schedule, events can be added to any day except Sundays.

### Describe the behavior you expected

I expect to be able to add events to any day of the week including Sundays.

### Steps to reproduce the issue

1. Go to Settings > Devices & Services > Helpers
2. Create a helper schedule.
3. Add an event to Sundays.
4. Add an event to any other day and the Sunday event disappears.

### What version of Home Assistant Core has the issue?

2022.11.5

### In which browser are you experiencing the issue with?

Safari 16.1

### Which operating system are you using to run this browser?

macOS Ventura 13.0

**Comment by themanieldaniel** [comment]
I believe there was an issue similar to this that was resolved in a previous build, but I suspect that when the change was made in 2022.11.5 to allow a user to set which day is the first day of the week, this issue returned.

**Comment by spacegaier** [comment]
This issue will be fixed in 2022.12. that is going to get released later today.
