### ISSUE TITLE
Can't remove WiFi details from the UI

### ISSUE THREAD

**Issue by nschloe** [home-assistant/frontend#14601]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

For the fun of it, I once added Wifi credentials to my HomeAssistant installation. Now it connects to the Wifi every time it boots up, and I have no way to prevent that from the UI:

![screenshot](https://user-images.githubusercontent.com/181628/206208814-59a0acc4-51d6-47d1-bd00-b4a934c6e28d.png)

### Describe the behavior you expected

See above.

### Steps to reproduce the issue

See above.

### What version of Home Assistant Core has the issue?

2022.11.5

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

Linux

**Comment by matthiasdebaat** [comment]
I've made a quick [prototype](https://www.figma.com/proto/yuSSQdNTRJYF7GWUS7vzaf/Configure-network-interfaces?page-id=1%3A7&node-id=1%3A2385&viewport=567%2C1750%2C0.59&scaling=min-zoom&starting-point-node-id=1%3A2385) how we could improve the `Configure network interfaces` card. The current one I find a bit to technical orientated. This mockup is based on what other manufactures are doing.

Specifically for this issue, I would suggest adding a `Forget this network` button on the left of the save button.

**Comment by spacegaier** [comment]
Looks good to me. Now we just need someone to come along to implement that :)

**Comment by nschloe** [comment]
Not fixed yet.

**Comment by nschloe** [comment]
Not fixed yet.

**Comment by nschloe** [comment]
Not fixed yet.

**Comment by nschloe** [comment]
Not fixed yet.

**Comment by nschloe** [comment]
Not fixed yet.

**Comment by nschloe** [comment]
Not fixed yet.

**Comment by nschloe** [comment]
Not fixed yet.

**Comment by nschloe** [comment]
I'm getting tired of adding "Not fixed yet." to this bug. This will be my last comment.

**Comment by matthiasdebaat** [comment]
Recently it was added
https://github.com/home-assistant/frontend/pull/22471

We want to improve it in a later stage.
