### ISSUE TITLE
"temperature_unit" must be read-only in UI if defined in "configuration.yaml"

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#14614]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If some setting is defined in YAML, it is supposed to be read-only in UI.
I see it for all options except settings for units - "unit_system", "temperature_unit":
![изображение](https://user-images.githubusercontent.com/71872483/206329405-0fd8c4fc-ad88-4e7c-a93d-dcca19bae691.png)

Also, here there is some misunderstanding on my side: there are [two settings](https://www.home-assistant.io/docs/configuration/basic/#configuration-variables) related to units but UI has only one some "consolidated" setting for "Celsius, kilograms".

configuration.yaml:
```
homeassistant:
  unit_system: metric
  temperature_unit: C
```

### Describe the behavior you expected

The setting for "temperature_unit" must be read-only in UI.

### Steps to reproduce the issue

As above

### What version of Home Assistant Core has the issue?

2022.12.0

### In which browser are you experiencing the issue with?

Chrome 108.0.5359.95 

### Which operating system are you using to run this browser?

Win10x64

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
Up

**Comment by kristof-mattei** [comment]
up
