### ISSUE TITLE
Color of states Off and Unavailable are the same in History graph card in release 2022.12

### ISSUE THREAD

**Issue by bmarr** [home-assistant/frontend#14619]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In release 2022.12, the gray color of the Off and Unavailable states are not distinctly different, as seen in the History graph card, such as in the History sidebar dashboard.

In previous releases, Off state was red and Unavailable state was gray, but now they are both gray. Because of this new color assignment, I can no longer easily spot a lightbulb, for example, that has changed state from On or Off to Unavailable, such as is often the case when using the LocalTuya custom_component, or if an esphome lightbulb has poor WiFi behavior.

I like the new color scheme, but I think the Off state set to gray was maybe unintentional. Would it not be better for consistency to have the Off state color match the lightbulb color, dark blue, and gray for Unavailable?

### Describe the behavior you expected

I expected the colors of the Off state and the Unavailable state to be distinctly different as they were in previous releases.
I was hoping the colors would match other cards in dashboards and their icons for the same states, such as dark blue for Off and gray for Unavailable shown on icons, such as the mdi-lightbulb.

### Steps to reproduce the issue

1. Update Home Assistant Core to 2022.12
2. Click on the History sidebar item to show the History dashboard
3. While in the History dashboard, add a Room, Device, or Entity that have states that may change to Unavailable from On or Off
4. Observe that the Off state and the Unavailable state are both gray, and that while they are separated by a dark gray bar at the transition point, this may not be visible at-a-glance, and not visible at all using the mobile device Frontend app.

### What version of Home Assistant Core has the issue?

2022.12.0

### What was the last working version of Home Assistant Core?

2022.11.0

### In which browser are you experiencing the issue with?

Google Chrome 108.0.5359.71 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 Pro

### Additional information

Please refer to 

- Kids Bedroom Ceiling 3 (LocalTuya lightbulb) and the multiple transitions from On-Unavailable-On
- Kids Bedroom Reading Light 1 (LocalTuya lightbulb) and the multiple Off-Unavailable-Off transitions
- The Unavailable state above the hover message at Dining Room Ceiling 3 (ESPHome lightbulb) normally in the Off state

![image](https://user-images.githubusercontent.com/4461221/206371877-1375d8de-cb15-4461-98bc-37aa03bfa30f.png)

**Comment by piitaya** [comment]
Or may be we have 2 different grey to have distinction between state ?

**Comment by prof7bit** [comment]
Off should not be represented by grey at all. Grey has traditionally been the color of unavailable, not only in Home Assistant but in most other user interfaces too, this metaphor is so commonplace that it already made its way into our language: something (a button for example) can be "greyed out" to mean it is unavailable, etc.

Grey should really continue to mean only this one thing it used to mean since the beginning of computer GUI.

"off" should be a represented as a non-grey color.

**Comment by piitaya** [comment]
"off" state must stay grey, we already discussed that with the UX team. It's the less distracting color.
For reference : https://www.figma.com/proto/ZPRTON7huEj9kyXzPNxNgK/Future-concept?node-id=263%3A7391

**Comment by piitaya** [comment]
That's why we have an indicator for that in the tile card for example : https://github.com/home-assistant/frontend/pull/14582

**Comment by prof7bit** [comment]
But does this badge help with the problem of this particular issue (history graph)?

It was very confusing for me to see a lot of my sensor suddenly appearing as offline after the update, because this is the meaning of grey. Every time I look at one of these history bars now it has the appearance as if something were broken, because they look like offline when in reality they are just in the off state. 

This is extremely confusing.

An "UX-Team" should begin to rethink their decisions and their priorities  (because obviously they did something wrong) when after they made a change people are more confused than before the change, because this means it degraded in usability, which is the exact opposite of what they are supposed to do.

**Comment by piitaya** [comment]
I appreciate your feedback, we will find a solution. 
But just don't say "you're doing shit", it's not constructive.

**Comment by prof7bit** [comment]
Where are these colors defined? I had a look into https://github.com/home-assistant/frontend/blob/dev/src/resources/ha-style.ts but there I can still see the old colors. How can I override the new colors?

**Comment by matthiasdebaat** [comment]
Grey is used for off and disabled in UI's, for example our switches:
<img width="76" alt="CleanShot 2022-12-08 at 15 24 33@2x" src="https://user-images.githubusercontent.com/20203284/206471123-7420ba8b-e909-408b-b296-59d592047c13.png">

And we use it in our entity picker:
<img width="275" alt="CleanShot 2022-12-08 at 15 30 18@2x" src="https://user-images.githubusercontent.com/20203284/206472592-32f1d36a-2083-4073-b5c6-f5f8630b57b6.png">

With the introduction of our new card and improving the UI we changed off state to grey. Thanks for pointing out that we didn't fix the history graph yet. We will update this with the according grey.

**Comment by prof7bit** [comment]
> we changed off state to grey

I always perceived the off state on entity cards as just having some shade of the normal foreground color, not explicitly grey, although for the default theme this happens to be grey. If the theme had blue text I would have expected the off color to be some shade of blue also.

And I also see the color on the history chart as completely decoupled from the color of the switches and icons on the entity cards, these should be configurable separately, the history graph can have colors that have good contrast against each other because this view is used for a different purpose, here the main priority should be maximum contrast between all possible states.

**Comment by Mariusthvdb** [comment]
just let me chime in this please:

I do hope the UX team does not focus solely on the new title card, but remains focussed too on the regular entities cards and representation of entities in the dashboard. 
Just like Matthias posts [here](https://github.com/home-assistant/frontend/issues/14619#issuecomment-1342827770), that would still be The default card for entities.

Personally I only need the Tile card in a few spots. The fact there is an unavailable badge for that card doesnt imply its usability on an entities card..

No issue at all with Grey for normal state, (my main theme is grayish and uses that for primary color). The unavailable should however be much lighter indeed, again, as in the Mattias post. that looks very nice.

keep up the good work!

**Comment by emufan** [comment]
> That's why we have an unavailable badge for that in the tile card for example : #14582

Hm. You see that the difference is not there or too less and develop a solution for a single card. O.k. But what about all the other cards?

Should not be the perhaps better solution to solve the problem, that it is not good to distinguish to choose more different colors in generals here and not only to have a work-around for one single card? For me even the example above from Matthias is far from being different enough in terms of fast visibility and accessibility. And this should really be considered,

**Comment by TekFan** [comment]
I totally agree with this PR, grey is the universal color for unavailability in All UI I've ever seen.
So an OFF state should never been reported as gray in the history.
With the last update, I see gray everywhere in the history, this is dramatically confusing.
The new color scheme is a real mess, but at least I progressively find means to revert back to usable (I mean previous) colors with a theme, even though I never had to use them before today.
But I don't know how to change the history colors.

**Comment by ildar170975** [comment]
Some people have problems with distinguishing shades of colors.
Some use tablets with not as good quality as a brand new iPad.
Some use wall-mounted tablet in light rooms or outside a house where brightness do not allow, again, to distinguish shades.
Some people just have problems with eyes.

So - please - use different colors for ON/ OFF/unknown/unavailable, not some shades.

**Comment by prof7bit** [comment]
Off-color should be configurable. The off/unavailable-states in the history-graph have a different importance than in the entity icon  color UI, and they also have different requirements regarding the colors: 

The off/inactive Icon on the entity card should nicely blend in with the theme colors (background, foreground), choose a color that makes it not sticking out of the surrounding, for example some shade of dark blue on the blueish dark theme. These icons are used to immediately differentiate active states from all the rest from only a quick look. And they should  always have colors that harmonize with the entire theme to make it look beautiful. Which it did until now.

The Off/Inactive Bar fill colors on the history chart have a different purpose, here ALL possible states should contrast against each other as much as possible. They are mainly viewed with the intention to analyze historic state changes, there is no need for the off color to "not be distracting" or stand back behind the other colors, these charts are primarily viewed with the eyes of the engineer who wants to inspect what has been going on in the system, and it is of critical importance to easily see the difference between "offline" and all other states.

The UX team mainly looks at it from the perspective of harmonic colors and "not distracting", looking nice and beautiful, etc. And they did a great job so far making the UI look indeed very beautiful and harmonic. But unfortunately they did not look at it with the eyes of the engineer who wants to hunt down intermittent problems in his ZigBee network, causing his gas meter counter losing a few pulses every week, or switches that mysteriously drop off the wifi when the garage door is in the position "open" and shielding the car port wifi repeater from the garage door shelly.

**Comment by piitaya** [comment]
We are preparing a fix for that. Inactive and unavailable state will be two different colors on the dashboard, more-info, logbook, history. It will be 2 shades of grey and will be configurable with themes.

**Comment by emufan** [comment]
> and will be configurable with themes.

Thx Paul. 👍

**Comment by TekFan** [comment]
> We are preparing a fix for that. Inactive and unavailable state will be two different colors on the dashboard, more-info, logbook, history. It will be 2 shades of grey and will be configurable with themes.

Ok, that is comforting news, thank you !
Do you confirm that history will be configurable with themes ?
Will it be documented somewhere ?

**Comment by piitaya** [comment]
Yes I will propose a community guide for the state colors.

**Comment by prof7bit** [comment]
@piitaya  

regarding your commit:

please try to combine a switch, a binary sensor and a numeric sensor on the same entity card and activate state colors. Like in the example below:
![off-colors](https://user-images.githubusercontent.com/1401589/206725875-9b8554e8-4e94-4f27-a364-7747eaede58b.png)
![off-colors-2](https://user-images.githubusercontent.com/1401589/206725901-1a5d96ef-93dd-4d6e-bf2c-f130c4405d84.png)

I would very much like to keep all 3 icons blue in the off state, no matter what colors the have in the history chart.

That was the reason these colors have been separate in the first place all the time and everything was perfectly fine! I don't understand why you are insisting on trying to break something that was not broken before? Who asked for the colors of icons to become messed up and inconsistent?

**Comment by prof7bit** [comment]
I suggest following logic:

* add the code for the new color variables and make sure it is working
* set their default values all to "undefined" or "default" or something alke
* make the code use the old theme colors for everything the user did not willingly configure his own color for

That way you have solved both problems:

* the user can now configure every color he wants
* users that don't change their theme will not notice any change

**Comment by RobSmyth** [comment]
On updating to latest I too found the off state gray color very confusing. It does appear that devices are off-line. A light gray is a long standing convention for disabled/unavailable. Using a similar gray for "off" is poor UX as it makes it hard to use. Being inactive or off is very different to being dead/disabled.

Glad to hear this will be fixed but the colors must be clearly distinct and light gray MUST be used for dead/disabled/unavailable/gone-to-another-place.

**Comment by piitaya** [comment]
And what about using transparent for unavailable ? Easy to find when the device is unavailable.
![CleanShot 2022-12-10 at 22 09 32@2x](https://user-images.githubusercontent.com/5878303/206875455-071abbdf-219a-4a67-a3ac-832406cd9a79.png)

**Comment by ildar170975** [comment]
> what about using transparent for unavailable

Currently, if some entity is absent in DB , we can see a "missing" graph for this period.
Assume that you are displaying a graph 01.12 .. 07.12 for a set of entities, and one of them was created on 03.12. So yo will see a gap for 01.12 .. 07.12 - i.e. "transparent graph".
Let's not mix "unavailable" case with "entity does not exist" case.

**Comment by matthiasdebaat** [comment]
> Let's not mix "unavailable" case with "entity does not exist" case.

From all proposed and discussed options I find this style the best. It's not that common an entity doesn't exist, only a first time. Unavailable being transparant communicates a correct message, saying it's not a value like on, off, clear, etc.

**Comment by ildar170975** [comment]
> It's not that common an entity doesn't exist, only a first time.

But this happens.
Especially with people who are developing some changes.
And we should distinguish these "does not exist" & "unavailable" cases.

Next, we also should distinguish "unavailable" & "unknown" cases too.
Assume that "unavailable" becomes "transparent" - then what we'll have for "unknown"?

But actually this is not just about particular colors.
This is about ignoring users' ideas/observations & doing smth on your own.
This is a common child, we all must respect each other.

**Comment by RobSmyth** [comment]
> @RobSmyth What color would you use for `off`? Red should be reserved for alerting things (unlocked lock, triggered alarm, etc..)
> 
> And what about using transparent for unavailable ? Easy to find when the device is unavailable.
> 
> ![CleanShot 2022-12-10 at 22 09 32@2x](https://user-images.githubusercontent.com/5878303/206875455-071abbdf-219a-4a67-a3ac-832406cd9a79.png)

Hi, I'm not great at UI design so I would rather decline to suggest a colour as it would need to fit so many wider design considerations. However, from a UX point of view it is absolutely clear that I need to be able to see "unavailable" consistently intuitively and clearly. Showing an arbitrary of "last known" value when the device is know to be unavailable is unusable for me as I would need to manually code in something to show an "unknown" symbol instead of value for any value from and off-line device. Show "false" or last know can result in a door unlocked, flooding, fridge door left open, or the nuclear launch missile under my house exploding.

FYI: This became immediately apparent when I updated. I do have several devices off line as I have some building work happending and suddenly it looks like most things were off-line.

Thanks for reaching out.

**Comment by RobSmyth** [comment]
> > what about using transparent for unavailable
> 
> Currently, if some entity is absent in DB , we can see a "missing" graph for this period. Assume that you are displaying a graph 01.12 .. 07.12 for a set of entities, and one of them was created on 03.12. So you will see a gap for 01.12 .. 07.12 - i.e. "transparent graph". Let's not mix "unavailable" case with "entity does not exist" case.
> 
> ![image](https://user-images.githubusercontent.com/71872483/206887613-f14f630b-e51f-4475-9aad-ba5ab91befd6.png)
> 
> Here it seems that "unknown" states (usually observed during HA reboot) for binary sensors also have a transparent color.

Good point. To give a use case here ... I have some devices that have not worked well and I'm wanting to know how long they have been installed. I can tell when I first installed/configured it by when data appears in the history. That is, after the last "gap". I was trying to do that just recently.

To say it is not needed as things generally work well is like saying logs/debugging/documentation are needed as things just work well. The most important time this is needed when first configuring a system. Ignoring newbies needs would be an unusual option.

**Comment by prof7bit** [comment]
Please revert everything to 2022.11.x

Use a development branch for new features or major rewrites such as this and DO NOT merge half-baked, unfinished, UNTESTED work into the release branch!

maybe the project owner or the boss of Nabu Casa or whoever is responsible should step in and do something before home assistant is completely destroyed.

**Comment by RobSmyth** [comment]
As I said earlier I'm not good at UI design, but were I've been left on my own to come with a UI style (poor customers) I have often referred to the Material Design guidelines  like this:

  https://m2.material.io/design/usability/accessibility.html#color-and-contrast

I see another person posted a link one of the other accessibility guidelines. I hope this helps form the basis of low level design guidelines on which styles are based/validated so it can both look great and be useful too. (I'm thinking of a melding of Zoolander and Macgyver, "the Mac-Zoo-ber (MZB) user interface that blends style and usability)

Hope that helps.

**Comment by franco-101** [comment]
I am reporting the same issue, only on state appears correct. Unavailable and Off colours appear broken.
![image](https://user-images.githubusercontent.com/60199752/207862072-fc644510-11f0-44d4-82ad-fb1f68f24d38.png)

**Comment by balloob** [comment]
This issue has been resolved in latest release. If you have still experience it, please open a new issue.
