### ISSUE TITLE
Missing Date Picker for input_datetime Helper (2022.12)

### ISSUE THREAD

**Issue by zubir2k** [home-assistant/frontend#14616]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing date picker for input_datetime helper

### Describe the behavior you expected

The date picker was available for all Date Time helper. Since the 2022.12 release, it seems to have disappeared.

Screenshot:
![image](https://user-images.githubusercontent.com/1905339/206336378-a83ae045-1c94-45a5-a978-bd412dc46a5b.png)

### Steps to reproduce the issue

1. Create input_datetime helper with any preferred name.
2. Locate the helper in the Developer Tools > States
3. Try update the date to the helper (no date picker is shown).

### What version of Home Assistant Core has the issue?

2022.12.0

### What was the last working version of Home Assistant Core?

2022.11.5

### In which browser are you experiencing the issue with?

Firefox Browser 107.0.1 (64-bit)

### Which operating system are you using to run this browser?

Windows 10 Pro 21H2

**Comment by AleXSR700** [comment]
Can confirm. Same behavior here.

**Comment by tobias-kuendig** [comment]
Here's a stack trace:

![grafik](https://user-images.githubusercontent.com/8600029/206406007-313c0076-8403-4d1e-a36a-9c26bddfa119.png)

It looks like the time part of the date value is hard-coded, so when the sensor value is inserted, the `Date` is initialized with an invalid timestamp:

![grafik](https://user-images.githubusercontent.com/8600029/206406237-913886cf-09df-4745-ab65-4f33a4b3087a.png)
