### ISSUE TITLE
Unable to edit settings - general while a homeassistant: entry is in configuration.yaml

### ISSUE THREAD

**Issue by MrOzzOnline** [home-assistant/frontend#14628]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On the page settings - general I'm getting the message "Editor disabled because config stored in configuration.yaml."

In my configuration.yaml file I have an entry for my https configuration:

homeassistant: 
  external_url: https://****
  internal_url: http://homeassistant:8123

Removing it enables the configuration page after restart.

### Describe the behavior you expected

The options in the general settings page should be enabled when there isn't a related option in the configuration.yaml file.

You can consider the full page is enabled with a warning that some settings could be overwritten by configuration.yaml entries.

### Steps to reproduce the issue

1. add a homeassitant: entry in the configuration.yaml page (in my case I added internal_url: and a external_url: option
2. go to settings - general. this page is disabled
3. removing the homeassistant: entry in configuration.yaml enables the page again after a HA reboot
...

### What version of Home Assistant Core has the issue?

2022.12.0

### Which operating system are you using to run this browser?

Windows 11

**Comment by MrOzzOnline** [comment]
> We can't mix this, the yaml would always overrule the settings set in the frontend.
> 
> Why don't you just remove it from your YAML and set it all up in the UI? The external/internal urls are on `/config/network`

Yes, this fixes it for me. The point is if you have part of the settings in YAML, everything is disabled. This is confusing and isn't communicated in the UI. If you go down this road and keep locking everything if there is an homeassistant: entry in the YAML file then there should be a very clear warning in the UI.

Sometimes YAML configuration is still needed, for example if you want to reduce your home zone size which isn't configurable from the UI at the moment.

**Comment by steverep** [comment]
@MrOzzOnline, just FYI, the issue of home zone radius has been mentioned as ancillary to #5991.
