### ISSUE TITLE
Tile card cover: 100% percent displayed instead of open

### ISSUE THREAD

**Issue by KNXBroker** [home-assistant/frontend#14621]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Great new tile card features. I'm wondering why 100% percent is displayed for cover in open state whereas closed is displayed for closed state. 

With respect to this topic I would appreciate displaying open instead of 100%, ,: 
https://community.home-assistant.io/t/why-the-heck-cant-we-freely-configure-a-cover-to-interpret-its-percentage-value-as-percentage-open-or-percentage-closed/225453?u=knxbroker

Furthermore it would be consistent with closed.

Thanks

### Describe the behavior you expected

Tile card cover: display open instead of 100%

### Steps to reproduce the issue

1. Create tile çover card
2. Press open

### What version of Home Assistant Core has the issue?

2022.12.0

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

Windows and android

**Comment by piitaya** [comment]
100% Open and 0% Closed is a standard for cover entity (used by Apple Home, Google Home, etc..). 
The information that the cover is partially open is missing. Maybe we can have : 
- Closed
- Open
- Open - xx% (if not completely open)

**Comment by KNXBroker** [comment]
I know the HA logic will never change (unfortunately...), your proposal would be great and avoid any confusion.
