### ISSUE TITLE
device tracker (or person) state colors (home/not home) different for some persons

### ISSUE THREAD

**Issue by prof7bit** [home-assistant/frontend#14627]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

See this screenshot (these are two device trackers, both tracking the companion app on a Samsung S10 (my wife and I both have the exact same phone), so both trackers should be the exaxt same type and class of entity, yet they have different colors now:
![state-colors](https://user-images.githubusercontent.com/1401589/206423361-ba4db15f-6810-4b21-8004-46845ae12de5.png)

### Describe the behavior you expected

Like it used to be in the previous version (both green/red)  they both should have the same pair of colors. I do not care so much which colors these are, but they should at least be the same for all instances of the same type of sensor.

### Steps to reproduce the issue

I don't know if this will be reproducible for everyone, but in my case it is just two installs of the companion app on two identical Samsung phones which will make two device tracker entities appear. For me they suddenly have two different colors.

### What version of Home Assistant Core has the issue?

core-2022.12.0

### What was the last working version of Home Assistant Core?

core-2022.11.x

### In which browser are you experiencing the issue with?

Firefox

### Which operating system are you using to run this browser?

Linux

### State of relevant entities

both entities are reporting the states "home" or "not_home", so they are clearly operating in the correct mode, I also cannot see any difference in the developer tools, regarding their attributes, both look pretty much the same, both entity-ids are prefixed with "device_tracker.".

These device trackers are assigned to persons and the persons home/not_home state also have the same different colors as in the screenshot above.

**Comment by piitaya** [comment]
Fixed by #14626
