### ISSUE TITLE
this.recognition.lang = "en-US" change option in config. 

### ISSUE THREAD

**Issue by exotsk** [home-assistant/frontend#14625]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

this option hardcoded, but  need the ability to configure this option in the config. To be able to change the recognition language. It`s can be used by Yandex Station add on.
https://github.com/home-assistant/frontend/blob/efda2ab626ff59e5937d67cea50e7a0886635b5e/src/dialogs/voice-command-dialog/ha-voice-command-dialog.ts#L214

### Describe the behavior you expected

if it is possible, it will be possible to fix the recognition language

### Steps to reproduce the issue

1. Only EN lang in chrome language recognition
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.12

### Which operating system are you using to run this browser?

Win 11

**Comment by seb81** [comment]
I need this option too

**Comment by adisik** [comment]
And I need this option too.

**Comment by hellad** [comment]
Please add this option to the system
