### ISSUE TITLE
Can't add event to local calendar in the companion app

### ISSUE THREAD

**Issue by Ziepoeskenetnie** [home-assistant/frontend#14642]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Am i missing something here? I can't add an event to the local calendar in the app.

![Screenshot_20221208_144531_Home Assistant](https://user-images.githubusercontent.com/108867885/206463020-1f52314a-607e-4853-8f39-dd495242049a.jpg)

### Describe the behavior you expected

I want to add events through the app in the local calendar.

### Steps to reproduce the issue

1.
2.
3.
...
Not sure what to fill in here.

### What version of Home Assistant Core has the issue?

2022.12.0

**Comment by spacegaier** [comment]
Events can only be added through the calendar panel (from the menu/sidebar). Is that where this screenshot is from? Just want to rule out that the screenshot is from a calendar card, since that is a read-only view on the calendar.

**Comment by Ziepoeskenetnie** [comment]
> Events can only be added through the calendar panel (from the menu/sidebar). Is that where this screenshot is from? Just want to rule out that the screenshot is from a calendar card, since that is a read-only view on the calendar.

Missed that one, i'm sorry.
Working now,

Thank you!
