### ISSUE TITLE
Color option is gone after last update

### ISSUE THREAD

**Issue by Rotil66** [home-assistant/frontend#14654]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi HA developers,

After the last update yesterday the color option in the Button card is gone.
I have a setup with a lot of button that where yellow now they are basic blue  (kind of inactive color) which is not very 
good visible. Would be nice if I could color the button again.

### Describe the behavior you expected

just the color be Yellow  (or able to set)

### Steps to reproduce the issue

1. just make a button, it will be blue and there is no coloroptionin the gui
2.
3.
...

### What version of Home Assistant Core has the issue?

??

### What was the last working version of Home Assistant Core?

the one before 2022.11.2

### In which browser are you experiencing the issue with?

all

### Which operating system are you using to run this browser?

win11, Android 12

**Comment by spacegaier** [comment]
Are you talking about buttons that have an entity assigned (because there were coloring logic changes in this release)? Can you please post the YAML of one such button card in the issue template.

**Comment by Rotil66** [comment]
Hi Philip,

Thanks for this incredible fast response !!!!!

 

Down you see a part of the Yaml (one button)

I have a horizontal stack with several buttons.

I believe the button changes color on activity before…….

But this option is gone.

 

 

- type: horizontal-stack

      cards:

        - show_name: false

          show_icon: true

          type: button

          tap_action:

            action: call-service

            service: lghorizon.remote_key_press

            data:

              entity_id: media_player.mediabox_2

              remote_key: MediaTopMenu

          entity: media_player.mediabox_2

          name: Hoofdmenu

          icon: mdi:home-circle

 

 

Thanks,

 

By the way: It would be great if there would be an option in the

Is card where you could set color for parts and a corner radius….

(custom buttoncard can do this but it’s to complex for me at this moment)

 

Van: Philip Allgaier ***@***.***> 
Verzonden: donderdag 8 december 2022 19:53
Aan: home-assistant/frontend ***@***.***>
CC: Rotil66 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [home-assistant/frontend] Color option is gone after last update (Issue #14654)

 

Are you talking about buttons that have an entity assigned (because there were coloring logic changes in this release)? Can you please post the YAML of one such button card in the issue template.

**Comment by Rotil66** [comment]
OK, for what I read in the community thus change is not seen as an improvement.But do you have a link where I can learn how to make a custom theme ??Thanks I'llOutlook voor Android downloaden

**Comment by spacegaier** [comment]
@Rotil66 https://www.home-assistant.io/integrations/frontend/#defining-themes

**Comment by LuxStatera** [comment]
It seems even the custom themes have been altered with this new update. Is there a way to downgrade just the frontend portion?

**Comment by spacegaier** [comment]
> It seems even the custom themes have been altered with this new update. 
As there are now new dedicated color CSS variables, custom themes indeed need to adopt to use those.

> Is there a way to downgrade just the frontend portion?
I think in theory you could point your HA core to a dedicated frontend folder, but that is mainly there for frontend dev, and not sure if that is officially supported.
