### ISSUE TITLE
Default dashboard broken after update.

### ISSUE THREAD

**Issue by killa198921** [home-assistant/frontend#14662]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After HA Update default dash wont load. error message.

 Error loading the view strategy:

    TypeError: i is undefined

### Describe the behavior you expected

dashboard displays error message only.
![Screenshot from 2022-12-08 13-14-16](https://user-images.githubusercontent.com/31766389/206571418-acb6e597-beda-4c02-b7bc-e8804ce06a12.png)

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.12.0

### What was the last working version of Home Assistant Core?

core 2022.11 frontend 20221207.0

### In which browser are you experiencing the issue with?

Chrome / Firefox

### Which operating system are you using to run this browser?

MacOS/iOS ZorinOS Windows11

### State of relevant entities

```txt
Nothing is shown in dashboard.
```

### Problem-relevant frontend configuration

```yaml
Default generated layout
```

### Javascript errors shown in your browser console/inspector

```txt
TypeError: i is undefined
    m http://192.168.1.6:8123/frontend_latest/82bed80e.js:1
    generateView http://192.168.1.6:8123/frontend_latest/82bed80e.js:1
c2cb8a35.js:9:8646
    o http://192.168.1.6:8123/frontend_latest/c2cb8a35.js:9
```

**Comment by spacegaier** [comment]
@killa198921 Can you check if the issue still persist in the current HA version? There were a few fixes around that dashboard that might have also resolved your raised issue.

**Comment by killa198921** [comment]
> @killa198921 Can you check if the issue still persist in the current HA version? There were a few fixes around that dashboard that might have also resolved your raised issue.

Just updated to 2022.12.5 issue persists. With a different message on iOS. ![image](https://user-images.githubusercontent.com/31766389/207444802-c5540f36-d352-45c3-995d-b73eb6ff6e70.png)

**Comment by spacegaier** [comment]
Can you please check your browser log, and open the JS file that is listed as an error and copy it in here (plus the line/position of the error). That might help us narrow down where the issue is coming from.

As a reference see https://github.com/home-assistant/frontend/issues/14750#issuecomment-1349410693

**Comment by killa198921** [comment]
is this what your looking for?
[84af2551.js.txt](https://github.com/home-assistant/frontend/files/10222668/84af2551.js.txt)
<img width="1325" alt="Screenshot 2022-12-13 at 2 38 34 PM" src="https://user-images.githubusercontent.com/31766389/207460278-9de70c82-9062-482c-94a0-010f11325b10.png">

**Comment by spacegaier** [comment]
Yes that was what I was looking for.

**Comment by Thrasher2020** [comment]
Issue exists in 2022.12.7. 2022.12.6 was fine.

Happening on all devices and browsers. 

![image](https://user-images.githubusercontent.com/65713394/208672904-4063554c-dc00-47dd-ac77-8590d6a98edf.png)

**Comment by Birillo71** [comment]
I have the same issues also after the 2022.12.8 upgrade. 
it happens on any device
