### ISSUE TITLE
Can't set default dashboard on any device after 2022.12 update

### ISSUE THREAD

**Issue by TimBeekman** [home-assistant/frontend#14668]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If I open the mobile app or desktop webbrowser, and go to profile settings I can select a default dashboard to launch. This setting jumps back to "Dashboard" on every device after you leave the profile page.

### Describe the behavior you expected

I expect the change of dashboard to launch will be saved and applied.

### Steps to reproduce the issue

1. Open mobile app or browser
2. Click on profile to open profile settings
3. Select a dashboard to launch at startup
4. Refresh the page

Now the setting has shifted back to "Dashboard"

### What version of Home Assistant Core has the issue?

2022.12

### In which browser are you experiencing the issue with?

Google Chrome 108.0.5359.94

### Which operating system are you using to run this browser?

Windows 11 22H2

**Comment by spacegaier** [comment]
I can confirm the issue, but cannot spot why. At runtime in the `render()` of `ha-pick-dashboard-row.ts` everything seems fine. The active dashboard value is filled and the dashboard select items are all there. At runtime the chosen dashboard is also used in general for rendering, so it is just the pre-selection that does not work in that row.

**Comment by spacegaier** [comment]
Not sure if related https://github.com/material-components/material-web/issues/1493

**Comment by killa198921** [comment]
I'm having the same issue. #14662
