### ISSUE TITLE
All zones are green on device_tracker and person entities in history graphs

### ISSUE THREAD

**Issue by PimDoos** [home-assistant/frontend#14661]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The history graphs for my device trackers and person entities are showing green for all zones the entity is in, except 'away' which is gray.
This makes it hard at first glance to see if a device tracker has left a zone at all:
![image](https://user-images.githubusercontent.com/17709721/206560592-e10f1dc7-c65d-4771-bb37-216092602365.png)

The two states in the middle are in fact where my device tracker is in the 'Work' zone. The color is the same:
![image](https://user-images.githubusercontent.com/17709721/206560841-7e70270c-32bd-4192-8c78-a549ca318edb.png)

### Describe the behavior you expected

In earlier versions, different zones had different colors. This makes it easier to see the history of a device tracker over time.

### Steps to reproduce the issue

1. Call the `device_tracker.see` service with `location_name` = home
2. Call the `device_tracker.see` service with `location_name` = work
3. Open the history graph for the device tracker and notice the colors are the same
...

### What version of Home Assistant Core has the issue?

core-2022.12.0

### What was the last working version of Home Assistant Core?

core-2022.11.5

### In which browser are you experiencing the issue with?

Microsoft Edge 108.0.1462.42

### Which operating system are you using to run this browser?

Windows 10 22H2 19045.2251

### State of relevant entities

```txt
States:
home
work

Attributes:
source_type: gps
latitude: #REDACTED
longitude: #REDACTED
gps_accuracy: 15
altitude: 59
course: 0
speed: 0
vertical_accuracy: 1
friendly_name: #REDACTED
```

### Problem-relevant frontend configuration

```yaml
type: history-graph
entities:
  - entity: person.pim
hours_to_show: 24
refresh_interval: 0
```

### Javascript errors shown in your browser console/inspector

```txt
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'addEventListener')
    at 528ad133.js:2:43246
    at pt (528ad133.js:2:43271)
    at ft.addEventListener (528ad133.js:2:44258)
    at 528ad133.js:2:83979
    at 528ad133.js:2:84011
    at w (a2435d78.js:1:2310)
    at Jt.bindUserEvents (528ad133.js:2:83946)
    at Jt.bindEvents (528ad133.js:2:83733)
    at Jt.update (528ad133.js:2:79237)
    at l.value (0156f10e.js:1:10327)
```

**Comment by piitaya** [comment]
Can you update to `2022.12.1`? It should be fixed.

**Comment by PimDoos** [comment]
Updating to 2022.12.1 fixed it for me. My work zone now has different colors to the home zone. Other zones have the same colors as the work zone, but this isn't as big of a deal to me.
