### ISSUE TITLE
Fix thresholds for battery colors

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#14664]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Not exactly a bug - just a correction.
Looking at here:
https://github.com/home-assistant/frontend/blob/99a69d3a70063083affe596be30cc675f46090ed/src/common/entity/color/battery_color.ts
```
export const batteryStateColor = (state: string) => {
  const value = Number(state);
  if (isNaN(value)) {
    return "sensor-battery-unknown";
  }
  if (value >= 70) {
    return "sensor-battery-high";
  }
  if (value >= 30) {
    return "sensor-battery-medium";
  }
  return "sensor-battery-low";
};
```
Why not using thresholds "67" & "34"?
These values are usually used.

Also, these thresholds could be defined in a theme as variables...

### Describe the behavior you expected

described above

### Steps to reproduce the issue

described above

### What version of Home Assistant Core has the issue?

2022.12.0

### In which browser are you experiencing the issue with?

Chrome 108.0.5359.95 

### Which operating system are you using to run this browser?

Win10x64

**Comment by piitaya** [comment]
Closed according to https://github.com/home-assistant/frontend/pull/15243
