### ISSUE TITLE
2022.12.0 (zigbee2mqtt) entities are not grouped by type anymore

### ISSUE THREAD

**Issue by bartplessers** [home-assistant/frontend#14676]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Lovelace autogenerated dashboard: since 2022.12.0 my zigbee2mqtt entities are not placed in the correcsponding domain card, i.e. "lights":
- individual Z2M lightbulb (1) (mqtt integration)
- automatic created group of lightbulbs (2) (shows here lightbulbs from other integrations)
- 
![2022-12-09_17-28-57](https://user-images.githubusercontent.com/10470708/206747783-81356f14-faf2-4fa6-a3e0-91666d1f0afa.png)

This results in a cluttered dashboard 

### Describe the behavior you expected

lightbulbs/switches/sensors/... will go to corresponding domain-group

### Steps to reproduce the issue

1. add light to Z2M
2. install MQTT integration
3. observe autogenerated lovelace dashboard

### What version of Home Assistant Core has the issue?

2022.12.0

### What was the last working version of Home Assistant Core?

2022.11.x

### In which browser are you experiencing the issue with?

all

### Which operating system are you using to run this browser?

dietpi

**Comment by spacegaier** [comment]
Sounds like https://github.com/home-assistant/frontend/issues/14556 introduced probably by https://github.com/home-assistant/frontend/pull/14577 and https://github.com/home-assistant/frontend/pull/14577

**Comment by codyc1515** [comment]
Please close this ticket as completed in #14707

**Comment by bartplessers** [comment]
Please re-open, because this is NOT solved 
https://github.com/home-assistant/frontend/pull/14707 as about sortorder.

As mentioned in initial post: zigbee2mqtt entities are not placed in the correcsponding domain card, i.e. "lights", but generate an own card per device, i.e.:
![2022-12-13_13-34-11](https://user-images.githubusercontent.com/10470708/207319475-113d0c1c-c35f-4b18-bfac-a2b714d0c768.png)

**Comment by spacegaier** [comment]
@bramkragten Is that behavior correct? If those are not in an area or a group, then one card per device is the new logic you had added?

**Comment by suawek2** [comment]
@bramkragten @spacegaier any progress on this?

**Comment by suawek2** [comment]
bump so the issue isn't closed

**Comment by codyc1515** [comment]
I think this might still be an issue. Can anyone confirm?

**Comment by suawek2** [comment]
yes, it is still an issue

**Comment by codyc1515** [comment]
I don’t think I’m facing any issue anymore.

**Comment by suawek2** [comment]
The issue still persists on 2023.11.2

**Comment by bartplessers** [comment]
Confirm

**Comment by suawek2** [comment]
not working in 2024.2.2

**Comment by suawek2** [comment]
not working in 2024.5.4

**Comment by suawek2** [comment]
ot working in 2024.8.2
