### ISSUE TITLE
"Unavailable" state color in UI is the same as "Off" color

### ISSUE THREAD

**Issue by Cougar** [home-assistant/frontend#14677]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After 2022.12 update with the new state color schema, the default "Unavailable" and "Off" state colors are the same which makes it hard to see when some sensor is not working. Before "Unavailable" was gray and "Off" was red. Before "On" was green which is now a yellow. This is how it looks like with default light theme
![2022 12 state-colors](https://user-images.githubusercontent.com/60040/206749865-b8df1c8a-a047-4d55-a3df-2c81786a2f65.png)

In logbook the events are also using only two different colors now. It is impossible to see how much time it was off and how much time the sensor wasn't available.
![2022 12-boiler-log](https://user-images.githubusercontent.com/60040/206752874-e994cdb7-7084-4bae-b882-cc4ca3bcf3dc.png)

Colors also are sometimes still different in new release like here in history view
![2022 12-boiler-state](https://user-images.githubusercontent.com/60040/206752238-f20464ff-defe-49c7-aeb4-6eb574b30bf2.png)
First one is switch, last two are binary sensors.

Same problem is now in Android app too.

In state both look very similar
![2022 12 state-boiler](https://user-images.githubusercontent.com/60040/206753733-86536b3f-264f-4cee-877f-2de2dddc33f2.png)
![2022 12 state-boiler_relay](https://user-images.githubusercontent.com/60040/206753746-09faecee-99b2-430f-8068-89310de47724.png)

### Describe the behavior you expected

This is how it looks like in 2022.11 where all three colors are different

![2022 11 state-colors](https://user-images.githubusercontent.com/60040/206749949-7c4fed20-da7a-4764-af0e-ef63fedcc4e1.png)

### Steps to reproduce the issue

1. upgrade from 2022.11.x to 2022.12

### What version of Home Assistant Core has the issue?

2022.12.1

### What was the last working version of Home Assistant Core?

2022.11.4

### In which browser are you experiencing the issue with?

Firefox, Android app

### Which operating system are you using to run this browser?

Linux, Android

**Comment by spacegaier** [comment]
Already addressed via https://github.com/home-assistant/frontend/pull/14672
