### ISSUE TITLE
inconsitent color choices for "lock" status (lock vs. binary sensor)

### ISSUE THREAD

**Issue by ChristophCaina** [home-assistant/frontend#14680]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The color choice for lock entities vs. binary_sensor (locked / unlocked) are not consistent.

![grafik](https://user-images.githubusercontent.com/26391061/206776719-c7faf1cf-81f6-4acd-8d12-b9b9ace7691d.png)

1) usually, the state we want to be alerted is "unlocked" -> so when a lock entity is unlocked, it should be red, green if it is locked.

2) the lock entity in this example has the default icon color when it is unlocked, and the color does change when the entity is locked.
But for the binary sensor it is vice versa.
It is using the default color when it is locked, but "active" color when it is unlocked.
Also here, In my opinion the logic should be the oposit... - which would match the states from the lock entity.

This would allow a better visibility to the user, as he does not need to think about, if it is a "lock" or "binary_sensor"
![grafik](https://user-images.githubusercontent.com/26391061/206778884-ef806928-272c-4e93-89cc-82925ef5263c.png)

### Describe the behavior you expected

lock status: Green when locked, red when unlocked
binary_sensor: Green when locked, red when unlocked

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.12.1

**Comment by tankdeer** [comment]
Came here looking for this. I understand that the new colors are a work in progress, but defaulting to red for _locked_ seems like a really poor choice. Red should mean danger/warning/alert/etc. Eg, it would be far more appropriate to have red be color the _unlocked_ state. That's when you want to draw attention to it

**Comment by ChristophCaina** [comment]
@tankdeer : that's already implemented in PR #14633 and #14672

**Comment by piitaya** [comment]
It will be fixed with this PR : https://github.com/home-assistant/frontend/pull/14633
