### ISSUE TITLE
Missing "SAVE" button when editing a card

### ISSUE THREAD

**Issue by pablolassalle** [home-assistant/frontend#14693]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When editing a card, I can't see the save button on lower right corner.
If I create a new card, the SAVE button is there, but only when creating it, if aI edit this new card, the save button is also missing.

![image](https://user-images.githubusercontent.com/44057799/206870926-b0f9880d-7282-4f54-beba-d5a9fe041e76.png)

### Describe the behavior you expected

The save button must be there.

### Steps to reproduce the issue

1.click on the three dots on the upper right corner 
2.click on edit control panel
3.try to edit any card
...

### What version of Home Assistant Core has the issue?

2022.12.1

### What was the last working version of Home Assistant Core?

2022.11.1

### In which browser are you experiencing the issue with?

Google chrome Versión 108.0.5359.99 (Build oficial) (64 bits)

### Which operating system are you using to run this browser?

Windows 10

**Comment by jbouwh** [comment]
There should only be a save button after you change the content of the card.

**Comment by pablolassalle** [comment]
> There should only be a save button after you change the content of the card, I can not reproduce your issue. Try to open HA in a private browser session and see if your issue is solved.

You are right, I didn´t see that. As soon as I change anything on the card, the save button shows up.

Thanks!
