### ISSUE TITLE
Thermostat card: should use the Generic Thermostat preset temperature?

### ISSUE THREAD

**Issue by arnaudbreton** [home-assistant/frontend#14690]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

_Disclaimer: I'm reporting this as a bug as I don't see a consistent feedback but I'm not 100% sure what is the expected behavior_

I'm using the Thermostat card combined with Generic Thermostat.
Through the built-in scheduler help and automations, I'm setting the Generic Thermostat preset.

The preset name is shown as expected, however, the displayed target temperature remains different from the preset one.
From my understanding, the card is displaying the target temperature set for the entity in the configuration.

### Describe the behavior you expected

Here's one of my entity which is currently in the "away" preset, configured to 16C, while the card displays 18C:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/1361191/206864772-553828f8-e56e-4dfe-a9a2-5f5c5a2c6a94.png">

<img width="575" alt="image" src="https://user-images.githubusercontent.com/1361191/206864814-cea6b00b-0c6a-4340-8bbe-f9226d17f07f.png">

<img width="334" alt="image" src="https://user-images.githubusercontent.com/1361191/206864824-72cdd915-e0c0-4c49-b8cc-50035c66a4bf.png">

### Steps to reproduce the issue

1. Create a Generic Thermostat (climate) entity, and configure presets.
2. Add a Thermostat card associated to this entity
3. Switch between presets
...

### What version of Home Assistant Core has the issue?

2022.12.1

### In which browser are you experiencing the issue with?

Brave Version 1.46.134 Chromium: 108.0.5359.94 (Official Build) (x86_64)

### Which operating system are you using to run this browser?

macOS Venture

### State of relevant entities

```txt
hvac_modes: heat, off
min_temp: 15
max_temp: 20
target_temp_step: 0.1
preset_modes: none, away, comfort, home, sleep
current_temperature: 17.4
temperature: 18
hvac_action: idle
preset_mode: away
friendly_name: Chambre
supported_features: 17
```

**Comment by popiula** [comment]
I am experiencing a similar issue. 

In my case, I am using the Thermostat Card together with the Smart Thermostat integration. 
The prest comfort temperature that I define in configuration.yaml is not the one that appears in the card and it seems the one in the card is the one relevant for the task.

Smart Thermostat settings:

climate:
  - platform: smart_thermostat
    name: Termostato
    unique_id: smart_thermostat_pu
    heater: switch.calefaccion
    target_sensor: sensor.fibaro_salon_air_temperature
    outdoor_sensor: sensor.aemet_temperature
    ac_mode: False
    min_temp: 15
    max_temp: 25
    target_temp: 21.0
    sleep_temp: 17.0
    comfort_temp: 21.0
    away_temp: 17.0
    min_cycle_duration: 00:15:00
    # PID settings:
    keep_alive: #time before update of PID controller
      seconds: 60
    kp : 25
    ki : 10
    kd : 50
    ke : 0.6 # opcional
    # duration of cycle in seconds
    pwm : 00:15:00

Card:

<img width="239" alt="image" src="https://user-images.githubusercontent.com/23246420/215352168-5c62f9ac-7a31-4435-85c5-f76302747f11.png">

**Comment by karwosts** [comment]
I don't see a bug here, at least not one in the frontend. 

The temperature on the climate card is the one that it is currently trying to reach. When you flipped your thermostat to away mode, the target temperature should have changed to 16C. 

The fact that your entity has a temperature attribute of "18" means to me that something changed the target temperature to 18 after away mode was set. 

In my generic thermostat I set an away_temp, and then every time I flip it into away mode the target temperature resets to that value. I can change the target temperature afterward, in which case the climate card will reflect the new temperature I set. Nothing says that the target temperature in away mode must always and forever be equal to 16, that's just the initial value when you turn on away mode (or at least it should be). 

Do you see anything in your system that disagrees with what I've said here? We can look further at it if that is the case.
