### ISSUE TITLE
I don't think the not equal filter is working

### ISSUE THREAD

**Issue by pauljrich1** [home-assistant/frontend#14692]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I attempted to use the following filter but it doesn't appear to be working. It still shows values that are equal to 0. If I change the operator to '=', it does filter for just the zero values.
state_filter:

operator: '!='
value: '0'

### Describe the behavior you expected

I expect the != operator to exclude any 0 values.

### Steps to reproduce the issue

1. Create an entity filter card that contains some zero values
2. Use the != operator and use value = 0
3. See if 0 values still show up

### What version of Home Assistant Core has the issue?

2022.12.0

### In which browser are you experiencing the issue with?

Chrome Version 107.0.5304.110 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Chrome

**Comment by karwosts** [comment]
I wonder if there's some integer/float comparison issue here.

I notice that if I take an input number which has a value of '0.0', it does not recognize that as equal to '0', but it does recognize it as equal to '0.0'. Seems like it's doing a strict string compare, not a numeric comparison. 

Does that possibly explain some of what you are seeing?
