### ISSUE TITLE
Tile card does not show color state when used in vertical stack card configuration

### ISSUE THREAD

**Issue by owillems** [home-assistant/frontend#14702]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using the Tile card normally in a view the color of the icon changes correspondingly with the status of the light. But when i use the Tile card in a vertical stack card configuration the icon does not change color and stays white. This problem is happening in different browsers and phone and the Home Assistant app.

### Describe the behavior you expected

That the Tile card is working properly in different default Home assistant card configurations.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.12.1

### State of relevant entities

```txt
entity: light.houten_wand_lights
State: On/Off

min_color_temp_kelvin: 2000
max_color_temp_kelvin: 6666
min_mireds: 150
max_mireds: 500
effect_list:
  - blink
  - breathe
  - channel_change
  - finish_effect
  - okay
  - stop_effect
supported_color_modes:
  - color_temp
  - xy
entity_id:
  - light.houten_wand_1
  - light.houten_wand_2
icon: mdi:lightbulb-group
friendly_name: houten wand lights
supported_features: 44
```

**Comment by ChristophCaina** [comment]
I cannot confirm this issue.
I have configured a tile card in a vertical stack and directly on my dashboard.
Both are set to the same entity - and both are changing their color value according to the setting of the light:

Warm white:
![grafik](https://user-images.githubusercontent.com/26391061/206925566-80c9dc16-bf66-41fa-b0df-0a8b6e0da9f9.png)

Cold white:
![grafik](https://user-images.githubusercontent.com/26391061/206925576-83b838d6-9844-43b3-8a8d-da363752a204.png)

I need to prepare another test with an RGB LED light... will update asap

**Comment by piitaya** [comment]
Do you have any custom cards installed ? There could be side effects...

**Comment by owillems** [comment]
I finally figured out what went wrong with the Tile card in the vertical stack card configuration, some how i made a mistake with the color token that i used for the Tile card. By replacing the color token with a valid name resolved the problem, the Tile card is now working correctly.
