### ISSUE TITLE
The color of binary sensors never changes (regardless of state)

### ISSUE THREAD

**Issue by smonesi** [home-assistant/frontend#14701]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Starting from 2022.12, the color of the icon of a binary sensor (eg. a motion sensor) is always the same color, even ifs state changes (unlike shown here: https://www.home-assistant.io/integrations/binary_sensor/#device-class and unlike versions before the new "Shiny new state colors" feature).

This same color is displayed in history graphs, so at the moment I have graphs with bars of the same color although the "On" and "Off" string is shown on the bar itself, which makes the  rather hard to understand and use.

<img width="1679" alt="Screenshot 2022-12-11 at 18 36 03" src="https://user-images.githubusercontent.com/63957397/206919417-833aa003-b49b-4088-9b5b-4948ca7bbc73.png">

### Describe the behavior you expected

I expected the binary sensor to have different icons and different color for on and off, but only the icon changes since 2022.12.

### Steps to reproduce the issue

```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: binary_sensor.any_motion_sensor

```

### What version of Home Assistant Core has the issue?

2022.12.1

### What was the last working version of Home Assistant Core?

2022.11.5

### Additional information

I also tried with latest git version of home-assistant/frontend.

**Comment by ildar170975** [comment]
Are you using a default theme?
With a default theme I see this:
![image](https://user-images.githubusercontent.com/71872483/206919723-581ce2a1-1af0-4ad8-bda0-02aac0cc7fe4.png)

**Comment by smonesi** [comment]
Yes, I use the default theme. However, hoping to find a solution in more recent commits, I am using the latest development version of frontend (which I believe changed the default color to yellow).

Is it true that your motion sensor keeps detecting motion for so many minutes? 😄 

I am specifically talking about `binary_sensor` with `device_class: motion` (for example, but I tried different classes with the same result), not about `input_boolean` (that does look like yours also on my system, in fact).

**Comment by ildar170975** [comment]
> motion sensor keeps detecting motion for so many minutes?

> `binary_sensor` with `device_class: motion`

For testing colors of binary sensors I am using this solution:
https://community.home-assistant.io/t/i-dislike-the-2022-12-color-changes/499890/163?u=ildar_gabdullin
There are testing `binary_sensor` entities with different `device_class` and a testing card:
https://community-assets.home-assistant.io/original/4X/1/8/0/18010f8c14c2c6d45796d3a5b8b357415b6c547c.png

**Comment by ildar170975** [comment]
> I am using the latest development version of frontend (which I believe changed the default color to yellow).

Do not see this updated, I am using the latest version too (HA in Container):
![image](https://user-images.githubusercontent.com/71872483/206923756-28c27f3e-5129-4cb5-b286-b73e6f8a3ea0.png)

**Comment by ildar170975** [comment]
OMG, got same with 2022.12.4:

binary_sensor, device_class: cold

![image](https://user-images.githubusercontent.com/71872483/207236968-dbf4487b-cc83-48b2-b8fe-cee0f0c2453f.png)

**Comment by KennethLavrsen** [comment]
I also see yellow on yellow now on a history for motion sensor. How is this possible? It has to be a bug
