### ISSUE TITLE
Cannot enter tariffs in utility meter

### ISSUE THREAD

**Issue by Bascht74** [home-assistant/frontend#14703]
### The problem

I would like to create an utility meter with tariffs. 
if I enter the tariffs in the field for that and press enter, nothing happens anymore. 
Becore, the tariffs was added to a list shown.

### What version of Home Assistant Core has the issue?

core-2022.12.1

### What was the last working version of Home Assistant Core?

core-2022.11.5

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

utility meter

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/utility_meter/

### Diagnostics information

are there any?

### Example YAML snippet

```yaml
no yaml, UI stuff
```

### Anything in the logs that might be useful for us?

```txt
no, because UI bug
```

### Additional information

See discussion about that here: 
https://discord.com/channels/330944238910963714/857346526527094814

**Comment by lyricnz** [comment]
Per the discord thread, I reproduced the problem with local checkout, then reverted to core-2022.11.5 which didn't have the issue. core-2022.12.0 did - and there was quite a bump in frontend version. between these.

**Comment by lyricnz** [comment]
Problem is very simple to reproduce:
- go to http://homeassistant.local:8123/config/helpers
- click "create helper" -> "Utility Meter"
- click the "supported tariffs" field
- type "one" hit enter. 

This _should_ have created a tariff/tag above the text entry field, and cleared the field so you can enter another. However, nothing happens, and if you Tab away, the field remains empty.

**Comment by shammysha** [comment]
There truble with config_flow selector, that have "multiple" option set to "true"
Have same trouble.. 
#14667

**Comment by lyricnz** [comment]
Update frontend to 20221201.1 (#83062) FAIL
    Update frontend to 20221130.0 (#83014) FAIL
    Update frontend to 20221108.0 (#81787) FAIL
    Update frontend to 20221108.0 (#81787) WORKS

**Comment by dincojazz** [comment]
Same to me.
Cannot add any tariff. When I hit enter nothing happens. The written letters at tariffs row disappears and when I hit button to create the helper it create it, but its not with clock icon but with counter icon and entity for it is not select.xxxxx but sensor.xxxx
Reverting to core-2022.11.5 to see if its OK.

**Comment by zipitrik** [comment]
Hi all , I don't know what I'm doing wrong but I still can't enter anything in the "Supported tariffs" field

**Comment by lyricnz** [comment]
The change is not yet in a frontend release.  Wait a few days for a new frontend release, then the core release that makes use of it.  

I have confirmed by running -dev versions of both (core+frontend) that the tariff function works again now.

<img width="599" alt="image" src="https://user-images.githubusercontent.com/122371/209022305-25d71146-e67e-4f78-a18b-8dbb7b5ee564.png">

**Comment by zipitrik** [comment]
Oh I see. 
Thank you very much for helping !
Learning a bit more everyday. Thanks again

**Comment by Bascht74** [comment]
Checked it with new beta. Works again. Thx!
