### ISSUE TITLE
History Graph and History only show 2 decimals of precision when hovering over points

### ISSUE THREAD

**Issue by melyux** [home-assistant/frontend#14706]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Until sometime this year, the graph used to show as many decimals as the sensor provided. A change earlier this year changed this to limit it to 2 decimal points, in both the History Graph card and its More Info pop-up, and the History viewer.

This is bad for things like pressure (inches of mercury) where most of the detail is behind the decimal point (e.g. 29.92). My pressure sensor has effectively become only precise to 2 decimal points when it provides 5 decimal points of precision, because I can only see the live data with 5 decimal points but not past data. There is no other way to browse this data other than make a manual connection to the database.

### Describe the behavior you expected

I should see as many decimals points as the sensor provides when hovering over graphs. If I want less precision, I can modify the template sensor (or make one) to round it. Better yet, there'd be an option in the history graph entity row and the History viewer to adjust this, but if that's not an option, it's better to be too precise than not enough.

### Steps to reproduce the issue

1. Have a sensor that provides >2 decimals of precision.
2. View it in a History Graph or the History viewer.

### What version of Home Assistant Core has the issue?

core-2022.11

### What was the last working version of Home Assistant Core?

core-2021-xx

### In which browser are you experiencing the issue with?

Safari

### Which operating system are you using to run this browser?

macOS, iPhone HA app

### State of relevant entities

```txt
29.36853

unit_of_measurement: inHg
device_class: pressure
friendly_name: OMG Pressure
```

### Problem-relevant frontend configuration

```yaml
- type: history-graph
    entities:
      - entity: sensor.pressure
```

**Comment by Youpimatin** [comment]
Still the same problem here with Home Assistant 2023.1.4 (and for a long time now)
One of the many reasons I'm still on Home Assistant 2021.6.6

**Comment by linuxdep** [comment]
Still the same problem here with Home Assistant 2023.2.2... too bad, that would be immensely important for the evaluation of my cell voltages, the 3 digit after the decimal point is decisive.

**Comment by ildar170975** [comment]
It shows ZERO number of digits after a point  

![изображение](https://user-images.githubusercontent.com/71872483/218234024-db07d623-5eb7-43eb-b905-520b9a5b4cab.png)

This is a Number:

![изображение](https://user-images.githubusercontent.com/71872483/218234064-864352cb-0bb5-4e4f-b0b5-fe3503518f33.png)

**Comment by Youpimatin** [comment]
Still the same problem here with Home Assistant 2023.6.2 (and for a long time)
One of the reasons I must keep an OLD Home Assistant 2021.6.6 server AND an up-to-date version at the same time

**Comment by karwosts** [comment]
PR #17648 will use a sensor's precision value when rendering the chart tooltip. 

Won't help for number or input_number entities, but at least it should be an improvement for sensors.
