### ISSUE TITLE
Tile Card with blinds

### ISSUE THREAD

**Issue by mxwi** [home-assistant/frontend#14719]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am not 100% sure if my topic is a feature request or a bug - maybe the behaviour is wanted, maybe not. Let's discuss..

I was very pleased with the tile card and would like to use it for my blinds. They are set up with KNX. They can be opened, closed and tilted.

I set up two tile cards. One to open/close them and one for tilting. 
![image](https://user-images.githubusercontent.com/32883521/207062788-1c0af697-39df-44a6-9b63-ae040fccdebc.png)

No matter what tile card I would use in default, the blinds would open/close - not tilt

### Describe the behavior you expected

Imho the 

```
features:
  - type: "cover-tilt"
```
 
feature is not very useful because it does not really do the "tilt" job. You have to set
  
```
tap_action:
          action: call-service
          service: cover.open_cover_tilt
          data: {}
          target:
            entity_id: cover.kuchenjalousie
```
that it does the tilt job. The "[slider-entity-row](https://github.com/thomasloven/lovelace-slider-entity-row)" for example implements it this way.

```
  - type: custom:slider-entity-row
    entity: cover.kuchenjalousie
    name: Lamellen
    attribute: tilt
```

In addition the status of the "Tilt" card doesn't show the tilt state, but the open/closed state (See on the picture).

### Steps to reproduce the issue

1. Use tile card and try to tilt blinds
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.12.3

### In which browser are you experiencing the issue with?

Microsoft Edge Version 108.0.1462.42

### Which operating system are you using to run this browser?

Windows 10

**Comment by piitaya** [comment]
Can you send the complete state of your entity? You can get it here using [developer tools](https://my.home-assistant.io/redirect/developer_states/).

**Comment by mxwi** [comment]
Yes, of course.

![image](https://user-images.githubusercontent.com/32883521/207278083-1ace7fca-c6e7-4bf1-8c02-3d67b80914b3.png)

state: open

current_position: 2
current_tilt_position: 51
device_class: shutter
friendly_name: Küchenjalousie
supported_features: 255

**Comment by piitaya** [comment]
And the current tilt position doesn't change when using the tilt buttons ?

**Comment by badwicky** [comment]
Hallo benötige Hilfe für die Anzeige der Lamellenposition. Wie habt ihr das gelöst? Bei mir wird nur die Auf Ab Position angezeigt.
