### ISSUE TITLE
Energy Dashboard stops showing Solar Production with bad solar forecast

### ISSUE THREAD

**Issue by sam-ward** [home-assistant/frontend#14729]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have been experimenting with using the Solcast HACS integration (as it seems more accurate for my location) as the solar forecast to use in the energy dashboard. Just recently I have hit upon an issue where the Solcast API stops returning data because i've hit an API limit (which I understand). 

However what I have noticed is that when the Solcast forecast is bad/invalid, my energy dashboard stops showing data in the Solar Production graph. I just get the "There is no data to show. It can take up to 2 hours for new data to arrive after you configure your energy dashboard." message showing.  This is for both the current day, as well as historical data; and also for different time periods (daily, weekly, monthly etc). 

### Describe the behavior you expected

I would still expect the Solar Production to display (expecially for historical data) regardless of whether the forecast was available or not.

### Steps to reproduce the issue

1. Note the Solar Production is missing from the energy dashboard.
2. Go into the Energy Dashboard configration
3. edit the solar panels
4. uncheck the Solcast Forecast production
5. the Solar Production data will re-appear in the dashboard
6. Similarly if I go back and select the forecast again, then the data will disappear again.
...

### What version of Home Assistant Core has the issue?

core-2022.12.3

### In which browser are you experiencing the issue with?

Firefox 107.0

### Which operating system are you using to run this browser?

Win10 22H2

### Javascript errors shown in your browser console/inspector

```txt
INS: content-ads.js loaded:  http://homeassistant.local:8123/energy content-scripts.js:1:108429
TSS: content-tss.js loaded:  http://homeassistant.local:8123/energy content-scripts.js:1:118223
INS: content-blocked-items.js loaded:  http://homeassistant.local:8123/energy content-scripts.js:1:138261
CONTENT_SHELL: Page allowed. Skipping shell injection blocks content-scripts.js:1:137923
GET TAB ID RESPONSE:  
Object { tabId: 726 }
content-scripts.js:1:119759
TSS: excluded result:  
Object { excluded: true }
content-scripts.js:1:128944
TSS: Excluding content tss (trigger: send-mesage) content-scripts.js:1:120296
CARD-MOD 3.2.0 IS INSTALLED card-mod.js:5:247
Uncaught (in promise) TypeError: can't convert undefined to object
    value hui-energy-solar-graph-card.ts:94
    value hui-energy-solar-graph-card.ts:94
    value hui-energy-solar-graph-card.ts:94
    value hui-energy-solar-graph-card.ts:94
    value 3038bf29.js:1
    r app.f8884e15.js:1366
    c app.f8884e15.js:1366
    promise callback*c app.f8884e15.js:1366
    d app.f8884e15.js:1366
    subscribe app.f8884e15.js:1366
    subscribe app.f8884e15.js:1366
    subscribe b57627f3.js:1
    value b57627f3.js:1
    value ha-settings-row.ts:78
    value ha-settings-row.ts:78
    value b57627f3.js:1
    connectedCallback typography.js:181
    M app.f8884e15.js:1366
    S app.f8884e15.js:1366
    T app.f8884e15.js:1366
    _$AI app.f8884e15.js:1366
    S app.f8884e15.js:1366
    update app.f8884e15.js:1366
    performUpdate app.f8884e15.js:1366
    scheduleUpdate app.f8884e15.js:1366
    _$EC app.f8884e15.js:1366
    requestUpdate app.f8884e15.js:1366
    o app.f8884e15.js:1366
    b app.f8884e15.js:1366
    w app.f8884e15.js:1366
    F ha-app-layout.js:103
    E typography.js:181
    t typography.js:181
    value hass-loading-screen.ts:84
    value hass-loading-screen.ts:84
    _currentLoadProm hass-loading-screen.ts:84
hui-energy-solar-graph-card.ts:94
The resource at “http://homeassistant.local:8123/static/fonts/roboto/Roboto-Regular.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. energy
The resource at “http://homeassistant.local:8123/static/fonts/roboto/Roboto-Medium.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. energy
```

**Comment by oziee** [comment]
would be better talking about issues like this with the integration issues
https://github.com/oziee/ha-solcast-solar/issues

**Comment by sam-ward** [comment]
> would be better talking about issues like this with the integration issues
> https://github.com/oziee/ha-solcast-solar/issues

The thing is bad data happens for various reasons, but software should still handle it correctly. One piece of bad data should not stop the whole dashboard from displaying the rest of the data that is still available. 

Hence I believe it’s a bug in HA (I’m just not sure whether it’s a front end bug or a backend bug).

**Comment by sergeBoisse** [comment]
I have the same problem. 
Using forecast.solar in energy dashboard and trying to display the energy graph in a custom view.
From time to times the graph  gets "broken" and only shows "There is no data to show. It can take up to 2 hours for new data to arrive after you configure your energy dashboard." Note that the energy dashboard is _still_ correct. 
The solution is to go back to energy dashboard, deselect forecast solar, switch to my custom view which now shows energy production but no forecast, go back again to energy board and re-check the solar prediction entity.  Ennoying.
