### ISSUE TITLE
Date settings doesn't work. It is always enforcing only US. 

### ISSUE THREAD

**Issue by andjelatomic** [home-assistant/frontend#14739]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Even with the new Country field in the general settings, UI doesn't change data to be formatted like it is in most parts of the planet DD-MM-YYYY, and time to be 23:59:59. It is really annoying, since it is stored in the database and data as timedate value that can be presented as anything.

Even in the sensors graphs, any other UI aspect, it is always US. I hope you agree that US is not representing the planet in general.

Warm regards
Andjela Tomic

### Describe the behavior you expected

Not possible to get the proper time date format.

### Steps to reproduce the issue

1. Change country into any EU or any other non US country
2. check dates and time how they are shown in any UI part
3.
4.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.12.4 Supervisor 2022.11.2 Operating System 9.3 Frontend 20221212.0 - latest

### Which operating system are you using to run this browser?

Linux (Mint, Kali), Windows.

**Comment by spacegaier** [comment]
The new country field does not yet have any effect but was added for future usage (see release notes). The date format is controlled via the selected language of your user profile and that should be then sued consistently throughout the UI. If you find any place where that is not he case, please raise an issue for that.
