### ISSUE TITLE
door sensor now yellow in both states (open/closed) (in the history graph)

### ISSUE THREAD

**Issue by prof7bit** [home-assistant/frontend#14734]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

since the latest release tonight all my door sensors show yellow color for all possible states in the history graph.

### Describe the behavior you expected

Would have hoped for partial fix of the 12.0 mess, instead it is getting worse

### Steps to reproduce the issue

1. upgrade to 12.04
2. look at what has happened to door sensors in the history graph

### What version of Home Assistant Core has the issue?

core-2022.12.4

### What was the last working version of Home Assistant Core?

core-2022.11.x

### Additional information

Seriously, do you even TRY to test your code before you release? Do you know what dev branches are used for?

It is getting worse with every new release! Can the project owner please step in and withdraw the commit rights from this person who is destroying home assistant and revert everything to 2022.11.x?

![door-yellow-always](https://user-images.githubusercontent.com/1401589/207258072-05db82ba-f840-4f84-a4fe-f81faf7a9575.png)

**Comment by piitaya** [comment]
Duplicate #https://github.com/home-assistant/frontend/issues/14701
