### ISSUE TITLE
Shiny new state colors are gone with 20221212.0

### ISSUE THREAD

**Issue by northalpha** [home-assistant/frontend#14738]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

<strike>a</strike> two picture is worth a thousand words:

pre 20221212.0:

![pre-20221212 0](https://user-images.githubusercontent.com/6721009/207275258-30d7b792-49ce-42d4-a5fa-c8261c3ce143.jpg)

20221212.0:

![20221212 0](https://user-images.githubusercontent.com/6721009/207275289-5eff7785-3244-4692-aa0d-6e5a520b93f3.jpeg)

### Describe the behavior you expected

Well, at least two different colors for different states, best to bring the state colors as seen before the update ;)

### Steps to reproduce the issue

1. Update to 20221212.0 as part of 2022.12.4
2. done

### What version of Home Assistant Core has the issue?

2022.12.4

### What was the last working version of Home Assistant Core?

2022.12.3

### In which browser are you experiencing the issue with?

Google Chrome Version 108.0.5359.98 (Offizieller Build) (arm64)

### Which operating system are you using to run this browser?

macOS Ventura 13.0.1

### Additional information

Dark or Light Mode makes no difference, testet also with Firefox 107.0.1 (64-Bit) and Safari, same behaviour

**Comment by ildar170975** [comment]
Same as https://github.com/home-assistant/frontend/issues/14701
