### ISSUE TITLE
History-graph: do not make a graph for "unavailable" sensor transparent

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#14731]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since 2022.12.4 a graph for "unavailable" entity is shown of transparent color.
![image](https://user-images.githubusercontent.com/71872483/207236044-7627594a-a756-402c-bf9f-8f1f5f69cc63.png)

This is confusing:
1. No graph for some entity may be considered as bug.
2. Transparent color = gap, but currently a gap is displayed in cases when an entity does not exist.

And when within the selected period the entity is `unavailable` - then no graph is displayed at all:
![image](https://user-images.githubusercontent.com/71872483/207235463-713f0be2-e06f-42e6-9cdc-bad99cb15bb9.png)
which is super-confusing.

### Describe the behavior you expected

Graph for "unavailable" sensor must not be transparent.
Better to use some theme variable like `--history-state-color-unavalailable`.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2022.12.4

### In which browser are you experiencing the issue with?

Chrome 108.0.5359.99 

### Which operating system are you using to run this browser?

Win10x64

**Comment by ildar170975** [comment]
> communicates a correct message,

But many people in Community disagree.



> It's not that common an entity doesn't exist, only a first time.

Unclear, what do you mean?
The "entity does not exist" is a very common case.
Especially when HA is on development stage (which may be a permanent state for some people).



> Note that your example is of 4 minutes, that's not a regular use case in my opinion.

Not sure what "4 minutes" you are talking about. But if you mean the 1st screenshot - this is a test case which is used for testing (a term we are missing a lot).

**Comment by ChristophCaina** [comment]
I have to disagree to the following statement:

> It's not that common an entity doesn't exist, only a first time. 

unfortunately, "Unknown" happene every time, when you have a cloud-based integration and the connection could not be established - or, if the integration could not be loaded, or similar...

Let me show you an example:
![grafik](https://user-images.githubusercontent.com/26391061/207362619-7aab64b5-0f18-4795-afca-2f32414b9034.png)

While I can fully agree with missing information in the Graph -> no data to record at all, the STATE should at least indicate SOME information.

Unfortunately, with only a lable, it does not work in all cases, because probably, on several occurances there's not the required space to write the label.

**Comment by ildar170975** [comment]
A label on a transparent bar may be not even noticeable.
Not to mention already described reasons like
- absence of a graph treated by many people as a bug;
- will not be possible to distinguish `unavailable` case & "does not exist" case;
- since icon color = history color, it is meaningless to use transparent icon color for `unavailable`.

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
May be closed - as long as `--history-unavailable-color` var is supported.
