### ISSUE TITLE
Edit a helper

### ISSUE THREAD

**Issue by dneumerk** [home-assistant/frontend#14759]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Once I created a helper, there is no way to view/edit it later.
![Screenshot Helper dialog](https://user-images.githubusercontent.com/67758034/207404063-e6d13344-d110-4fb7-a314-4d052a767ea5.jpg)

### Describe the behavior you expected

I expect to get an Edit button on the shown dialog.

### Steps to reproduce the issue

1. Goto Einstellungen / Geräte & Dienste 
2.  Select the tab Helfer
3. Select the helper you want to edit
4. You get the dialog popup I attached. But there is no button to view/edit the helper's definition, e.g. in order to see the entity the operation uses as input
...

### What version of Home Assistant Core has the issue?

2022.12.4

### In which browser are you experiencing the issue with?

Google Chrome Version 108.0.5359.99 (Offizieller Build) (64-Bit)

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
Home Assistant 2022.12.4
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221212.0 - latest
```

**Comment by karwosts** [comment]
Related #14066

**Comment by igorsantos07** [comment]
This is similar to not being able to edit the options of a `input_select` entity. Not sure if this should become a separate issue or not.

**Comment by igorsantos07** [comment]
@dneumerk, it seems this is not the right place anymore for feature requests. There's a discussion about this same topic at #14276, I would strongly suggest you to vote there :) (I also opened #16568 for my scenario with dropdowns).
