### ISSUE TITLE
Tile Card, setting "color: ..." -> color doesn't turn on/off on entity state

### ISSUE THREAD

**Issue by raphael303** [home-assistant/frontend#14751]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Tile Card, setting "color: ..." -> color doesn't turn on/off on entity state
Since last or one before last update.

Tried original theme, different browser

### Describe the behavior you expected

The color of the icon should toggle with entity state.

It does change color on default, if "color: " is not set.

### Steps to reproduce the issue

1. Create tile card
2. Use a switch or light entity
3. Set color: to any color
...

### What version of Home Assistant Core has the issue?

2022.12.4

### What was the last working version of Home Assistant Core?

2022.12.1 or 2022.11.x

### In which browser are you experiencing the issue with?

Safari, Chrome

**Comment by piitaya** [comment]
Fixed with #14744
