### ISSUE TITLE
Duplication of Horizontal Stack Card created Entities Card

### ISSUE THREAD

**Issue by pedjas** [home-assistant/frontend#14758]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I added new Temperature and humidity sensor. As I already have Horizontal Stack Card cards for such use, I decided to duplicate existing card and just replace entities with new ones.

But instead of Horizontal Stack Card I got duplicate as Entities Card. 

So I ended up having to delete it and create new Horizontal Stack Card and set it from scratch.

### Describe the behavior you expected

I expected if I duplicated specific card, duplicate would be the same type.

### Steps to reproduce the issue

1. Click on three dot menu of Horizontal Stack Card you want to duplicate
2. Click Duplicate
3. Duplicate is created but as Entities Card

### What version of Home Assistant Core has the issue?

 2022.12.4

### In which browser are you experiencing the issue with?

Firefox 107.0.1

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
I tried to reproduce this but could not. Duplicating a horizontal stack card pulled up an editor prefilled with the exact same horizontal stack card. Clicking save gave me exactly two duplicate horizontal stacks, as expected.


Maybe post your exact yaml to investigate further?

**Comment by ChristophCaina** [comment]
I've tried to reproduce the issue, too - but everything was working as expected...

**Comment by pedjas** [comment]
Now even I cannot reproduce it.
