### ISSUE TITLE
History Graph and History show the same color for on and off states

### ISSUE THREAD

**Issue by PatrickGlesner** [home-assistant/frontend#14752]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since version 2022.12.4, History Graph and History show the same color for on and off states.

### Describe the behavior you expected

Red for off and green for on.

### Steps to reproduce the issue

N/A

### What version of Home Assistant Core has the issue?

2022.12.4

### What was the last working version of Home Assistant Core?

2022.11.5

### In which browser are you experiencing the issue with?

App and Chrome

### Which operating system are you using to run this browser?

iPadOS 15.6.1

**Comment by piitaya** [comment]
Fixed with #14735
