### ISSUE TITLE
Calendar - event mouse-over activates scrollbars

### ISSUE THREAD

**Issue by ChristophCaina** [home-assistant/frontend#14771]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When you open a Calendar-Item (screenshot 1)
![grafik](https://user-images.githubusercontent.com/26391061/207574596-333f975e-e98e-4b4c-858b-c540f743eda3.png)

And hovers over the information when this event has been created - it will add scrollbars to the left (edge & firefox) and to the bottom (firefox). (screenshot 2)
![grafik](https://user-images.githubusercontent.com/26391061/207574841-b30dc188-135e-4967-94ad-390629ca303d.png)
![grafik](https://user-images.githubusercontent.com/26391061/207574989-44dc9283-2140-4a82-b2d4-e79fd215f342.png)

### Describe the behavior you expected

there shouldn't be any scrollbars at all, seems not be required

### Steps to reproduce the issue

1. create an calendar event
2. open the information dialog
3. hover mouse-cursor over the information "last changed"
...

### What version of Home Assistant Core has the issue?

2022.12.5

**Comment by spacegaier** [comment]
The scrollbars are required so you can see all the info in the appearing popup, although that is indeed fiddly.

**Comment by ChristophCaina** [comment]
but:
As soon as I leave the hovered element to "scroll" - the scrollbars disappear.
Also, I've just checked one example event - and could not see any additional information... which info should that be?
Something I can add to the event?

In addition to that.... when I start scrolling, the window always jumps back to the top:

![2022-12-14_14h29_34](https://user-images.githubusercontent.com/26391061/207608215-37d6a702-9b3d-4659-b3e6-50d68b5ce082.gif)

**Comment by spacegaier** [comment]
You should see the "last updated" and "last changed", same as in any more-info dialog.
![image](https://user-images.githubusercontent.com/114137/207608998-70b2fd31-2877-40e6-872e-7ead8ac59c77.png)

**Comment by ChristophCaina** [comment]
btw:

ALL calendar events are showing "2 hours ago" at the moment.
I think, that was when I restarted HomeAssistant...

So, in the image from the description, it could be, that the last HA Reboot was taken (for getting the 12hrs ago) information

**Comment by spacegaier** [comment]
Yes, I can confirm that FF does not show it for some reason, Chrome however does.

The "last updated" and "last changed" values do not survive a HA restart in general.

**Comment by ChristophCaina** [comment]
then: what's the purpose of having this information at all ?

**Comment by spacegaier** [comment]
> then: what's the purpose of having this information at all ?

If you mean in the context of the calendar then we can discuss that (see also comments from @allenporter in the backend ticket you raised). If it is in general, then I refer you to the lengthy and heated discussions about that topic in general over the years int he forums (e.g. see "WTH" section). Not going to rehash that here 😉 

For the calendar, we are reusing an existing frontend component that by default shows the icon, name and that time info as text and hover popup. But that is probably confusing if it is not the event's own time info (not sure that even exists currently?).

**Comment by ChristophCaina** [comment]
yes, I meant the purpose of the information itself (if it doesn't survive a restart of HA, and so on... :)
If this frontent component does show the information "by default" - it might be better to disable it at all... I don't think that it does show any relevant information :)

**Comment by allenporter** [comment]
It's telling you the last time the state was changed. It's not a modification time. This is a resided widget shared in other contexts.

I acknowledge the feedback.
