### ISSUE TITLE
Tuya power sensor (Zigbee -- MQTT) power level sensor readings gone wrong. 

### ISSUE THREAD

**Issue by TieskeC** [home-assistant/frontend#14781]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Tuya power sensor shows irratic values. 
Every  4 minutes and 30 seconds the sensor readout is 0W (in stead of real value) for 00:00:05 (5 seconds). 
This yields a very remarkable power curve readout. Two sensors (same type) do this. 

 ([TS011F_plug_1](https://www.zigbee2mqtt.io/devices/TS011F_plug_1.html#tuya-ts011f_plug_1)

### Describe the behavior you expected

continuous readou

### Steps to reproduce the issue
Cannot really tell... bit of a noob tooo!!
1.
2.
3.
...

### What version of Home Assistant Core has the issue?

22.12.3 and 22.12.4

### What was the last working version of Home Assistant Core?

22.11.5

### Which operating system are you using to run this browser?

Windows 

### State of relevant entities

```txt
state_class: measurement
unit_of_measurement: W
device_class: power
friendly_name: TPower T1 power

state_class: measurement
unit_of_measurement: W
device_class: power
friendly_name: TPower T1 power

friendly_name: TPower T1 child lock
supported_features: 0

state_class: total_increasing
unit_of_measurement: kWh
device_class: energy
friendly_name: TPower T1 energy
```

### Problem-relevant frontend configuration

```yaml
Zigbee2mqtt
  '0xa4c13887f78ad444':
    friendly_name: TPower T1
    description: Computer vermogen schakelaar
```

### Javascript errors shown in your browser console/inspector

```txt
no issues
```

### Additional information

![irratic power tuya](https://user-images.githubusercontent.com/97561312/207650100-ed7b12bb-0bd2-4cb6-b8e2-545ac54a79dc.PNG)

**Comment by ChristophCaina** [comment]
I think, that should go into the CORE repository?
Also, you should provide the information with which integration you are using the device... Zigbee (ZHA), Zigbee2MQTT, Tuya, LocalTuya (then it depends, if this is a core issue or an issue with a custom integration)

**Comment by TieskeC** [comment]
I do not think I can move it..
ZigBee 2 mqtt is stated in title.
