### ISSUE TITLE
Calendar event properties dates off by one day

### ISSUE THREAD

**Issue by rparenton** [home-assistant/frontend#14786]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When clicking an all-day event on the calendar that's from the Local Calendar integration, the start and end dates displayed on the event properties dialog are one day prior than the actual dates.

<img width="1079" alt="Calendar Event Properties Issue" src="https://user-images.githubusercontent.com/3348060/207673158-8c1ee2c6-62fc-49d3-b3d4-0169b0973984.png">

Here's the local_calendar ICS content for the event in the screenshot above:

    BEGIN:VEVENT
    DTSTAMP:20221214T174139
    UID:90545bf6-7bd6-11ed-92ed-52540009e893
    DTSTART:20231001
    DTEND:20231007
    SUMMARY:Test
    CREATED:20221214T174139
    DESCRIPTION:
    SEQUENCE:0
    END:VEVENT

This occurs on both single-day and multi-day all day events.

### Describe the behavior you expected

The dates displayed on the event properties dialog match the actual event dates.

### Steps to reproduce the issue

1. Create a new all day (i.e., enable the All Day option) calendar event using the Local Calendar integration
2. Click the event on the calendar

### What version of Home Assistant Core has the issue?

core-2022.12.5

### In which browser are you experiencing the issue with?

Firefox 107.0.1 (x64)

### Which operating system are you using to run this browser?

Windows 10 21H2

**Comment by allenporter** [comment]
@bramkragten i'm happy to take this also, i think it's similar to the issue i saw with https://github.com/home-assistant/frontend/issues/14539

@rparenton can you confirm what your home assistant timezone is?

**Comment by rparenton** [comment]
It's `America/Chicago`, which is the same as `CST6CDT`.  The devices accessing the frontend are using the same time zone.
