### ISSUE TITLE
(Change Request) Thermostat Cards should follow the same Color Logic as the Entity State colors for thermostats

### ISSUE THREAD

**Issue by ChristophCaina** [home-assistant/frontend#14784]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Right now, the Thermostat Card is using colors according to their HVAC_State - and not according to their current action.

Example:
Heating (Mode Auto) --> Green
Idle (Mode Auto) --> Green
Idle (Mode Heat) --> Orange
Heating (Mode Heat) --> Orange

![grafik](https://user-images.githubusercontent.com/26391061/207656270-2f2c99b2-f2cf-47c3-9dc0-5cc7c89c5c5c.png)
![grafik](https://user-images.githubusercontent.com/26391061/207656284-a84f4277-ef92-4640-be7f-35a38f7367c9.png)

With the recent changes from PR #14747 the state Icons have changed to reflect the current action of the Thermostat, which is independend to their current mode-setting:

![grafik](https://user-images.githubusercontent.com/26391061/207656541-571f47f3-0901-4bf1-b1f9-cc4c04fbfd88.png)

### Describe the behavior you expected

Thermostat Card should follow the same color-logic as the entity state

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.12.5

**Comment by piitaya** [comment]
As a user, I only have control on the mode and the target temperature so the color should reflect that (even for entity state color in other cards).
I don't care to know if it's heating or not. The thermostat does its job by heating/stoping to reach my target temperature.
I just want to know if I forgot to set the thermostat on the right mode.

How do you use the action information? What's your use case?

**Comment by ChristophCaina** [comment]
Well... If we need to discuss the usability of a UI in a Home Automation Software, we can keep that discussion in forever.
Why having colored states in entity cards?

Well Sure.
The Thermostat is something that should Work automatically, or by using the Hardware to Change the vent - or however...

But having a visual confirmation about the state would be more Important to me, because I don't use the modes at all.

It IS using Auto - profiles... I don't have any reason or clue what's the Differenzen between These states and why I can Set Them in the Software at all.

So, the current coloring ist more obsolete than the sugested one ;)
