### ISSUE TITLE
Clicking "show in sidebar" on dashboard-config page for Energy opens config, with no option to change sidebar

### ISSUE THREAD

**Issue by lyricnz** [home-assistant/frontend#14793]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Clicking a regular custom dashboard (on the "show in sidebar" icon FWIW) pops up a dialog with a "show in sidebar" toggle, so you can turn this off.  The energy dashboard doesn't seem to have this option, which is counter-intuitive (and users struggle to find how to hide the energy dashboard when they don't have any energy setup).

Yes, you can use the magic/hidden long-press on the sidebar title, and click on the X next to Energy, but that's rather hidden, and per-browser.

### Describe the behavior you expected

There should be a "show in sidebar" toggle on the energy config page (if there's no check-specific popup)

### Steps to reproduce the issue

1. open http://homeassistant.local:8123/config/lovelace/dashboards
2. click on "Energy" (in particular the "Show in sidebar" checkbox)
3. expecting to be able to change "show in sidebar" but no
...

### What version of Home Assistant Core has the issue?

2022.12.6

### In which browser are you experiencing the issue with?

Chrome, Safari

### Which operating system are you using to run this browser?

Mac

**Comment by lyricnz** [comment]
https://user-images.githubusercontent.com/122371/207740067-ee514997-4d53-4890-8e01-88c3d6058c81.mov

**Comment by cj89898** [comment]
Using chrome tested 2022.12.1, 12.2, 12.6. Upgraded OS to 9.4 as well still happening.

Workaround to hold on the heading on the sidebar to re-add energy worked.

**Comment by lyricnz** [comment]
Really, maybe instead of a check icon, maybe that should BE a toggle, so you can updated it directly on the dashboard list.

**Comment by lyricnz** [comment]
This is still an issue

**Comment by earto** [comment]
Experiencing the same problem with Energy dashboard. There's no way to change the "show in sidebar" setting because the toggle is missing.

**Comment by lyricnz** [comment]
@earto long-click on the word "Home Assistant" at the top of the sidebar.  After a second or two, it'll go "wiggle mode" and you can X the energy dashboard to remove it from the sidebar.

**Comment by earto** [comment]
> @earto long-click on the word "Home Assistant" at the top of the sidebar. After a second or two, it'll go "wiggle mode" and you can X the energy dashboard to remove it from the sidebar.

Thanks @lyricnz. Doing it at the device level is just a workaround though, right? Could be mistaken but I'm sure there used to be a toggle somewhere to turn it off system-wide like the other tabs. I thought only "Overview" was mandatory.

**Comment by Spookster** [comment]
Likewise here - I would prefer to turn it off at a system level, not a per user level

**Comment by sudomax** [comment]
Any update on this?

**Comment by TeoTN** [comment]
Nine major upgrades later the issue still prevails in 2023.9

**Comment by averater** [comment]
Still no way to disable energy dashboard? Except then some quite bad workarounds like doing it on each device for every user or disabling the entire integration by copypasting all except energy from default_config to configuration.yaml...

**Comment by averater** [comment]
Issue is still there in latest version. There is no way on system levels to get rid of energy from sidebar (same for to-do and some other items).

**Comment by averater** [comment]
Still no reasonable way to get rid of it. Except disabling it for every user in each browser after each time cache is cleared.

**Comment by averater** [comment]
There is still no reasonable way to not have this clutter the sidebar.

**Comment by brian-maher** [comment]
A workaround I've found for this (not ideal, but it's the best thing I've found that removes this crap properly without having to remove the  `default_config`).

1. Install https://github.com/arturpragacz/hass-cc-early-loader and https://github.com/arturpragacz/hass-cc-default-config-exclude using HACS.
2. Add the following to your `configuraton.yaml`:
```
default_config_exclude:
  early_loader_hook: true
  exclude:
    - energy
```

**Comment by frstep** [comment]
The bot must be getting a bit bored by now... but WTF this issue has not been addressed.

**Comment by lewmilburn** [comment]
> A workaround I've found for this (not ideal, but it's the best thing I've found that removes this crap properly without having to remove the `default_config`).
> 
> 1. Install https://github.com/arturpragacz/hass-cc-early-loader and https://github.com/arturpragacz/hass-cc-default-config-exclude using HACS.
> 2. Add the following to your `configuraton.yaml`:
> 
> ```
> default_config_exclude:
>   early_loader_hook: true
>   exclude:
>     - energy
> ```

This worked perfectly! Also works with other default dashboards if you're wanting to hide them as well.

**Comment by patricknelson** [comment]
At the very least, improve the UI a bit if it can't be disabled. Maybe graying the checkbox or putting a dash under "Show in sidebar" so it's less confusing.

p.s. I wonder if the bot will reopen this if I comment. I doubt it, but at least everyone knows why I'm really posting. 😅
