### ISSUE TITLE
Charts are cut off in History modal

### ISSUE THREAD

**Issue by domoritz** [home-assistant/frontend#14795]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The chart in the details modal is cut off on the right. 

<img width="556" alt="Screenshot 2022-12-15 at 01 19 55" src="https://user-images.githubusercontent.com/589034/207787549-3f9099d6-37e7-4234-8038-108a01c7f9f3.png">

### Describe the behavior you expected

I expect the full chart to be visible. In the History view, the full chart is visible. 

<img width="1171" alt="Screenshot 2022-12-15 at 01 20 04" src="https://user-images.githubusercontent.com/589034/207787759-500cf489-5d6a-48e9-a065-a27659bfb6ac.png">

### Steps to reproduce the issue

1. Click on details of an entity that has stats

### What version of Home Assistant Core has the issue?

2022.12.6

### What was the last working version of Home Assistant Core?

2022.12.6

### In which browser are you experiencing the issue with?

Safari Version 16.1

### Which operating system are you using to run this browser?

macOS

**Comment by ildar170975** [comment]
These are absolutely different graphs - precise actual data in History & approximate statistical data in more-info.
They are not obliged to look same.

**Comment by PeteRager** [comment]
I have the same problem.  This used to work fine in the pop up dialog.
