### ISSUE TITLE
Color of states Off and Unavailable are the same in History Graph Card in release 2022.12.6

### ISSUE THREAD

**Issue by franco-101** [home-assistant/frontend#14799]
I am reporting the same issue, only on state appears correct. Unavailable and Off colours appear broken.
![image](https://user-images.githubusercontent.com/60199752/207862072-fc644510-11f0-44d4-82ad-fb1f68f24d38.png)

_Originally posted by @franco-101 in https://github.com/home-assistant/frontend/issues/14619#issuecomment-1353005686_

**Comment by spacegaier** [comment]
What kind of entities are those? You write about "Off" and "Unavailable" but your screenshot shows "Clear". So overall this issue is not "Clear" 😉

**Comment by franco-101** [comment]
https://github.com/home-assistant/frontend/issues/14805

**Comment by franco-101** [comment]
https://github.com/home-assistant/frontend/issues/14805
