### ISSUE TITLE
Local Calendar Date fields missing

### ISSUE THREAD

**Issue by bolderbast** [home-assistant/frontend#14798]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using Chromium browser (Version 108.0.5359.124 (Official Build) Arch Linux (64-bit)), the date fields are missing when creating events in the local calendar. Result is that the event cannot be saved with the following error:

```
Could not parse date for dictionary value @ data['event']['dtend']. Got '12/15/2022T16:00:00' Could not parse date for dictionary value @ data['event']['dtstart']. Got '12/15/2022T15:00:00'
```

See screenshot

In Firefox, the fields are there and the event can be created properly
![2022-12-15_15-30-22_Selection](https://user-images.githubusercontent.com/78593849/207887634-0a31392a-4a46-4749-8e9e-f93a726a6426.png)

### Describe the behavior you expected

Expected the date fields to be there, and that the calendar event can be saved without error.

### Steps to reproduce the issue

Using Chromium browser (Version 108.0.5359.124 (Official Build) Arch Linux (64-bit):

1. Navigate to Calendar
2. Click "Add Event"
3. Fill in the available fields
4. Click "Add Event"

### What version of Home Assistant Core has the issue?

2022.12.6

### In which browser are you experiencing the issue with?

Chromium browser (Version 108.0.5359.124 (Official Build)

### Which operating system are you using to run this browser?

Arch Linux (64-bit)

### Additional information

Frontend-version: 20221213.0 - latest

**Comment by allenporter** [comment]
@bolderbast could you let me know what your home assistant locale settings are to reproduce this?  `Settings > System > General` in particular timezone, language, etc. Thank you for the report

**Comment by bolderbast** [comment]
Sure!
![Screenshot_2022-12-16-18-25-26-101_com android chrome](https://user-images.githubusercontent.com/78593849/208154693-cc8b76aa-3927-4cac-94c7-3e73a809a7b2.jpg)

**Comment by allenporter** [comment]
Thanks for the detail on this. I have not yet been able to reproduce this. I think it may have more to do with browser locale settings than home assistant settings. However, i tried changing locales and was not able to reproduce it. How about:
- you can tell me any details about language or locale settings in Chrome
- see if changing settings temporarily makes it work, so we can at least confirm that is the issue

**Comment by bolderbast** [comment]
Hi, please see below:
![image](https://user-images.githubusercontent.com/78593849/208374957-745c0c52-fe94-477b-b2f4-49037a9ed485.png)

Tried changing them to the following, but it made no difference:
![image](https://user-images.githubusercontent.com/78593849/208375092-6e16432b-f2f3-485c-a4bc-dbaa12413ea8.png)

**Comment by allenporter** [comment]
Weird that #14674 has conflicting information about the state of this bug

**Comment by bolderbast** [comment]
Don't know if it helps, but these are my system locales:
```
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=nl_NL.UTF-8
LC_TIME=nl_NL.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=nl_NL.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT=nl_NL.UTF-8
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

**Comment by allenporter** [comment]
@bolderbast is this still an issue that you're able to reproduce on a newer version of home assistant? I'm still not able to find the set of steps, so just thought I would check in.

**Comment by bolderbast** [comment]
Sorry, didn't test it for a long time, kind of abandoned it.
But, just tested and it seems to work now (running HA 2023.3.5):
![image](https://user-images.githubusercontent.com/78593849/226595671-929d48c4-27a5-42d1-8c17-4f6f23bcf499.png)
