### ISSUE TITLE
input_datatime Bug in RTL languages  like HEBREW 

### ISSUE THREAD

**Issue by moshiko2312** [home-assistant/frontend#14803]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi when I create input_datatime there is no information of days and dates
This happens only in languages that start from right to left like Hebrew or Arabic

<img width="457" alt="image" src="https://user-images.githubusercontent.com/48163773/207957534-8962d94b-1208-4269-98d2-639359b2d36f.png">

<img width="457" alt="image" src="https://user-images.githubusercontent.com/48163773/207957673-d3c81dca-af33-40cf-8d7c-00d6d3de05af.png">

### Describe the behavior you expected

<img width="459" alt="image" src="https://user-images.githubusercontent.com/48163773/207958145-8b08cbab-ae2b-4f35-9218-2c1a00de955a.png">

### Steps to reproduce the issue

1. Create  input_datatime
2. no data in tab

### What version of Home Assistant Core has the issue?

2022.12.6

### What was the last working version of Home Assistant Core?

2022.10.4

**Comment by adizag** [comment]
Here also

**Comment by tomerbenaharonintel** [comment]
Same here

**Comment by Roei639** [comment]
Same here

**Comment by moshiko2312** [comment]
@bramkragten

**Comment by moshiko2312** [comment]
?

**Comment by karwosts** [comment]
Would you be satisfied if the picker worked, but it was in ltr mode? Looks like the underlying library does not support RTL, see 

https://github.com/motss/app-datepicker/issues/190

It looks simple to add dir="ltr" to the app-datepicker, but then it will not be in rtl. 

![image](https://user-images.githubusercontent.com/32912880/226197868-ff901bd8-4c96-4aeb-be22-b4b41ddb2411.png)

If you want you can open a new issue in app-datepicker to inquire about rtl support.

**Comment by adizag** [comment]
I believe that would be fine.
@moshiko2312 what do you think?
