### ISSUE TITLE
Missing translation string "Solar total"

### ISSUE THREAD

**Issue by dolenec** [home-assistant/frontend#14801]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have problem that translation string of word "Solar total" is not listed for translation from English to Slovenian language.

https://app.lokalise.com/project/3420425759f6d6d241f598.13594006/?view=single&reference_lang_id=640&single_lang_id=920&search=Solar%20total

So how to translate this?

### Describe the behavior you expected

No info.

### Steps to reproduce the issue

No info.

### What version of Home Assistant Core has the issue?

2022.12.6

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
No info.
```

**Comment by dolenec** [comment]
![Screenshot_20221215_234905_Home Assistant](https://user-images.githubusercontent.com/16633222/207983530-5903c298-e644-4aff-9f48-ec7a4187d2c7.jpg)

**Comment by dolenec** [comment]
![Screenshot_20221215_235201_Samsung Internet](https://user-images.githubusercontent.com/16633222/207983911-114f4533-ffa2-4957-bd34-75d72b47fa21.jpg)

**Comment by dolenec** [comment]
Nobody responsible to fix the problem?

**Comment by jbouwh** [comment]
What I can see is that the text  `Solar total` is plain text in the source.

**Comment by jbouwh** [comment]
Attached PR should (after being merged) add the ability to add translations.

**Comment by dolenec** [comment]
Great.. thank you..
