### ISSUE TITLE
Error message during onboarding when country or language is not filled in

### ISSUE THREAD

**Issue by DCSBL** [home-assistant/frontend#14810]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

During onboarding when setting up location, an error is triggered.

### Describe the behavior you expected

A nicer error (visual feedback) or allowing an empty country field.

### Steps to reproduce the issue

1. Fresh install with latest changes in dev branch (https://github.com/home-assistant/core/commit/d9903c4cf985381002de8b923815b05dd24e0651)
2. Create account
3. Location screen: Click next
4. 
<img width="472" alt="Screenshot 2022-12-17 at 14 13 40" src="https://user-images.githubusercontent.com/74970928/208243629-17be4273-e67d-4c4c-8d9c-a5926aa26e4f.png">

5. Fill in country, click next
6.
<img width="465" alt="Screenshot 2022-12-17 at 14 14 40" src="https://user-images.githubusercontent.com/74970928/208243668-f5f196a2-aa04-48ff-b47b-534f091456c0.png">

### What version of Home Assistant Core has the issue?

2023.1.0.dev0 at commit https://github.com/home-assistant/core/commit/d9903c4cf985381002de8b923815b05dd24e0651

### What was the last working version of Home Assistant Core?

2022.12.x

### In which browser are you experiencing the issue with?

Version 15.6.1 (17613.3.9.1.16)

### Which operating system are you using to run this browser?

MacOS 12.5.1

### State of relevant entities

```txt
None relevant
```

### Problem-relevant frontend configuration

```yaml
Fresh install (empty config folder)
```

### Javascript errors shown in your browser console/inspector

```txt
No JS erros.

Home Assistant log:

2022-12-17 13:07:24.394 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139647343370976] Error handling message: invalid ISO 3166 formatted country for dictionary value @ data['country']. Got ''
invalid RFC 5646 formatted language for dictionary value @ data['language']. Got '' (invalid_format) from 172.17.0.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15)
2022-12-17 13:13:33.329 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139647984775808] Error handling message: invalid ISO 3166 formatted country for dictionary value @ data['country']. Got ''
invalid RFC 5646 formatted language for dictionary value @ data['language']. Got '' (invalid_format) from 172.17.0.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15)
2022-12-17 13:14:10.280 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139647984775808] Error handling message: invalid RFC 5646 formatted language for dictionary value @ data['language']. Got '' (invalid_format) from 172.17.0.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15)
```

### Additional information

Seems to be introduced in https://github.com/home-assistant/frontend/pull/14478

**Comment by gigatexel** [comment]
Still present, seeing same problem.

**Comment by DCSBL** [comment]
Last week this issue was still present.

**Comment by douglasfl** [comment]
still present on fresh install 2023.7.0

**Comment by DCSBL** [comment]
Yeah seems to be fixed in latest onboarding flow improvement 👌
