### ISSUE TITLE
Icon Colors for Update Sensors are not working (?)

### ISSUE THREAD

**Issue by ChristophCaina** [home-assistant/frontend#14822]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

With the December Updates new Icon Colors for Update Entities have been introduced.

![grafik](https://user-images.githubusercontent.com/26391061/208321593-7da7ee99-66ec-40ef-946b-ab1a8c2dcde0.png)

But - it seems that this isn't working correctly...
RIght now, my System is showing that a new Version of HACS is available:
![grafik](https://user-images.githubusercontent.com/26391061/208321668-89a24a6f-1a70-4d88-9039-4151111dc57b.png)

But the Entity in my Dashboard does not show any colorization for the Icon (The icon was set per yaml)
![grafik](https://user-images.githubusercontent.com/26391061/208321713-4a7392b5-f3ec-484c-8b1b-15551f2f30ff.png)

In fact, it CAN'T work for all update entities, because by default, they are using the Integration Icon or another Icon instead of the default one:

![grafik](https://user-images.githubusercontent.com/26391061/208321829-87f638e8-489d-4447-9879-1b76bfa435ad.png)
![grafik](https://user-images.githubusercontent.com/26391061/208321878-29b9c801-7b59-4266-a43b-bab4fbb3cce7.png)
![grafik](https://user-images.githubusercontent.com/26391061/208321984-cccc800e-9c71-4bee-808c-814e577c7fc5.png)

It would only work by custom cards, where the default icon will be used, because there is no addon, integration or other icon that would be used instead.
![grafik](https://user-images.githubusercontent.com/26391061/208322240-f449a3bc-1924-4dfc-b671-1bd0fd4eef6a.png)

So... the error:

1. If I use custom icons - they do not reflect the entity state (if an update is available)
2. the update entities are basically using icons that don't support different colors at all - and core integrations don't have any "update" entity, because they are part of the core...

### Describe the behavior you expected

update entities should support the icon color state as mentioned in the documentation: https://design.home-assistant.io/#misc/entity-state

It needs to be considered, if the Icons for update.xzy should always be a default Icon instead of using an integration Icon as it is right now

### Steps to reproduce the issue

1. none
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.12.7

**Comment by piitaya** [comment]
Hello.
What card do you use when installed and available version? Looks like a custom card.
In there is an `entity_picture` the icon (and so the color) is not display in entities list. But in entity-card, button-card, tile-card it should work. We have the same behavior for person entities.

**Comment by ChristophCaina** [comment]
it is the default entities (list) card - no customization.

![grafik](https://user-images.githubusercontent.com/26391061/208652907-51d2d26d-019a-4809-8a3d-51cb9e6918c8.png)

![grafik](https://user-images.githubusercontent.com/26391061/208652949-7609cfbe-276a-4963-b762-f2032de42ed5.png)

The only customization I did - when creating my dashboard:
Was to change the default icon (by default the entity_picture) in the card configuration with a default icon - but this doesn't change it's color - even if I have set the option to show the icon colors)...

Here I've created an update for my theme... since themes and custom: cards don't use an entity_picture, the icon colors are working.
But for all custom components, Addons and the HomeAssistant Core elements, the entities card is using the entity_picture instead of an icon.

As soon as there is another update (integration, addon, what ever) I will check the icon states again an update the comments

**Comment by piitaya** [comment]
As I understand you request, you want to use icon everywhere instead of entity picture, right ?

**Comment by ChristophCaina** [comment]
I think, it is a bit inconsistent to use the entity-pictures in the entities card, and everywhere else the icon... ?
The strange thing here is in fact:

I've changed the icon within my setup... and did not see any change of the color.
I've even tried it by removing the custom elements that I've used in my card...

I will re-evaluate this as soon as another update for such an element is available.

**Comment by ChristophCaina** [comment]
edit:

OK, I am sorry - indeed, it seems to be related to a custom element that I've used here :-(
![grafik](https://user-images.githubusercontent.com/26391061/208657383-4bbafd57-797b-48a7-8402-52c138fa2ee4.png)

issue can be closed :)

**Comment by ildar170975** [comment]
> entity-pictures in the entities card, and everywhere else the icon... ?

The Entities card shows an `entity_picture` (if present) - but you may show a default icon.


> custom: cards don't use an entity_picture

In your example I noticed `custom:multiple-entity-row` which DOES support `entity_picture`.

```
type: entities
entities:
  - entity: person.ildar
  - entity: person.ildar
    image: null

  - type: custom:multiple-entity-row
    entity: person.ildar
  - type: custom:multiple-entity-row
    entity: person.ildar
    image: null
```
![image](https://user-images.githubusercontent.com/71872483/208657599-a4470649-ffe5-4ea3-914b-4aa140c61cda.png)

**Comment by ChristophCaina** [comment]
Then, please explain me why I'm getting the entity Pictures for the Update entities when I use the Default Card with no custom elements... As shown in my other Screenshot...

**Comment by ildar170975** [comment]
> I'm getting the entity Pictures for the Update entities when I use the Default Card

If some entity has `entity_picture` specified, if this entity is shown in the Entities card - then an image is displayed (not icon).
This is what I said earlier and demonstrated with an example.

As far as I understood, you are " getting the entity Pictures for the Update entities when I use the Default Card" - this is exactly what is supposed to happen.
My example was with `person` entities with `entity_picture` specified; guess with `update` entities it will be same if these entities have `entity_picture` specified - cannot check it by myself since do not have any `update` entities right now.

**Comment by ChristophCaina** [comment]
OK, sorry Then I read your Comment wrong.
