### ISSUE TITLE
Automations in entities-card show false state after toggle

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/frontend#14844]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When an automation is added to an entities card, it is shown with a toggle. When you toggle the automation (e.g. from off to on) the card continues to show the initial state (i.e. it switched the state and then jumps back to the initial state).
![20221220_202035.gif](https://user-images.githubusercontent.com/57034871/208749296-b8331a86-347e-4aac-a2ae-3418c1affb9d.gif)
https://user-images.githubusercontent.com/57034871/208745215-cfa5ab56-c4a1-422c-8a5d-1d8f82c125de.mp4
### Describe the behavior you expected

When you toggle, the toggle remains in the new position (just like it does for e.g. lights).

### Steps to reproduce the issue

1. Create automation
2. Add automation to entities card
3. Toggle automation on/off
...

### What version of Home Assistant Core has the issue?

2022.12.7

**Comment by karwosts** [comment]
Cannot reproduce, mine works fine.

Does it fail for all of your automations, or just one?
Does it only fail on one direction (on to off, vs off to on)?
Does it work if you click on it and click the slider in the more-info popup that appears?

**Comment by AleXSR700** [comment]
> Cannot reproduce, mine works fine.
> 
> Does it fail for all of your automations, or just one?

For all I tested. 
![20221220_213756.gif](https://user-images.githubusercontent.com/57034871/208762065-06a5fad1-98df-411e-8e27-6e84deb5dc56.gif)
> Does it only fail on one direction (on to off, vs off to on)?
Both. See above gif.

> Does it work if you click on it and click the slider in the more-info popup that appears?
Yes, it does.
But as you can see, the entities card does not seem to refresh properly as the state is not correct.

So here you can see that the toggle works (because the state changed in the more-info) but does not refresh properly. Also, when toggling via more-info, the state changes and shows only in the more-info, not the dashboard.

![20221220_214130.gif](https://user-images.githubusercontent.com/57034871/208762672-abc7b703-17b0-4301-95f2-1fe49d8a6250.gif)

It shows the correct state in the card when I switch dashboards. So if I leave that dashboard, open a different one and then return, the state changed.

Observed both on Android and iPhone.

**Comment by AleXSR700** [comment]
Apologies!
As you can see, the behavior was observed. And I had this in multiple dashboards and plattforms.
However, I deleted the cards in question (combination of vertical-stack-card, auto-entities and entities-card) and recreated them from scratch.
Now this behavior seems to be gone.
I will test further but I cannot yet explain what was the cause as I now cannot force create it again -.-
