### ISSUE TITLE
Z-Wave/Zigbee mixed up in "missing_zwave_zigbee" dialog

### ISSUE THREAD

**Issue by TheJulianJES** [home-assistant/frontend#14847]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When the ZHA component is loaded, an "Add Zigbee device" option always shows up (even if the ZHA integration isn't actually set up).

When clicking that option without the integration being set up, the following dialog is shown:
![Bildschirm­foto 2022-12-21 um 02 15 28](https://user-images.githubusercontent.com/6409465/208797897-008acd38-5556-4dd4-8e65-fb9b0cd57128.png)

Here, Z-Wave is used as the "brand", even though it should be Zigbee.

Relevant string/translation:
https://github.com/home-assistant/frontend/blob/50f089fd4fb18319ec41722e526eb925a8651575/src/translations/en.json#L3126
Relevant code:
https://github.com/home-assistant/frontend/blob/50f089fd4fb18319ec41722e526eb925a8651575/src/common/integrations/protocolIntegrationPicked.ts#L47

### Describe the behavior you expected

Show "Zigbee" instead of "Z-Wave" when trying to add a Zigbee device.

### Steps to reproduce the issue

1. Load the ZHA component (for example by adding the ``zha:`` entry to your config or just setting up the ZHA integration and then deleting the integration -> component also stays loaded and "Add Zigbee device" still shows up)
2. Click "Add Integration"
3. Click "Add Zigbee device"
4. Observer wrong message

### What version of Home Assistant Core has the issue?

core-2023.1.0.dev0 / Frontend 20221213.1 (latest frontend commit: https://github.com/home-assistant/frontend/commit/50f089fd4fb18319ec41722e526eb925a8651575, core: https://github.com/home-assistant/core/commit/ba94485ca1911be7170a6c94767616fcde0007e0)

### In which browser are you experiencing the issue with?

Google Chrome 108.0.5359.94

### Which operating system are you using to run this browser?

macOS Ventura (13.1)

**Comment by karwosts** [comment]
https://github.com/home-assistant/frontend/pull/14892
