### ISSUE TITLE
Calendar display not showing all calendars/not scrolling calendar-list

### ISSUE THREAD

**Issue by kgroshert** [home-assistant/frontend#14861]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The list of calendars in the calendar-frontend is cut off with no option to scroll. The cutoff point depends on the screen-resolution. For narrow screens the list of calendars is located below the grid-view calendar, so there it works.

### Describe the behavior you expected

Give option to scroll the calendar-list.

### Steps to reproduce the issue

1. Integrate too many calendars
2. Open calendar-view <URL>/calendar in a desktop (landscape) browser

### What version of Home Assistant Core has the issue?

2022.12.8

### In which browser are you experiencing the issue with?

Microsoft Edge (Version 108.0.1462.54)

### Which operating system are you using to run this browser?

macOS Ventura (13.1)

### Additional information

<img width="535" alt="image" src="https://user-images.githubusercontent.com/60856997/209109760-f755be05-c427-4073-acd9-d1361d7e4868.png">

**Comment by Pulpyyyy** [comment]
To avoid issue to be Closed. 2023.4 still concerned
