### ISSUE TITLE
Red green color blind example

### ISSUE THREAD

**Issue by jazzmonger** [home-assistant/frontend#14866]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Red green color blindness

### Describe the behavior you expected

Red green color blindness  

### Steps to reproduce the issue

1. look at red and green
2.
3.
...

### What version of Home Assistant Core has the issue?

Red green color blindness

### What was the last working version of Home Assistant Core?

Red green color blindness

### In which browser are you experiencing the issue with?

Red green color blindness

### Which operating system are you using to run this browser?

Red green color blindness

### State of relevant entities

```txt
Here's a REALLY good example of red/green deficiency.  
The gauge on the left, I see NO difference in the 2 colors.  I know they are red/green only bc my wife tells me so.
Because the colors are right next to each other on the right gauge, I can barely make out they are different, but only where they meet exactly.

<img width="798" alt="image" src="https://user-images.githubusercontent.com/52110065/209171376-bb51261d-e53c-4153-9475-af58c695c407.png">

EDIT: interesting observation.... once I published this message, the graphic was set against a white background.  I can now see the red/green.  in HOME ASSISTANT, I have a dark theme and bc the surrounding screen is all black, I cant make out the difference.  So strange.
```

### Additional information

Here's a REALLY good example of red/green deficiency.  
The gauge on the left, I see NO difference in the 2 colors.  I know they are red/green only bc my wife tells me so.
Because the colors are right next to each other on the right gauge, I can barely make out they are different, but only where they meet exactly.

<img width="798" alt="image" src="https://user-images.githubusercontent.com/52110065/209171376-bb51261d-e53c-4153-9475-af58c695c407.png">

EDIT: interesting observation.... once I published this message, the graphic was set against a white background.  I can now see the red/green.  in HOME ASSISTANT, I have a dark theme and bc the surrounding screen is all black, I cant make out the difference.  So strange.

**Comment by karwosts** [comment]
If you use the segments: option in the gauge card configuration, you can choose whatever colors you want for the different sections. 

https://www.home-assistant.io/dashboards/gauge/

**Comment by piitaya** [comment]
I close the issue as color can be customized using `segments`.
