### ISSUE TITLE
history-graph: states for binary_sensor with "device_class" specified are not displayed sometimes 

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#14865]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If `history-graph` contains binary sensors with `device_class` specified - then SOMETIMES states are NOT displayed:

![image](https://user-images.githubusercontent.com/71872483/209152331-aaeb8005-a9ce-44c6-acb8-4d252b61eefe.png)

~This glitch is ERRATIC.
It is visible on the screenshot - all 4 sensors are with `device_class = connectivity`, and states are displayed only for the 4th sensor.~
~For binary sensors w/o `device_class` specified - I do not observe this glitch.~

This is not a BUG - it happens since long states like "Connected" cannot be displayed if an area is too narrow.

**Proposal**: add a new option like "show_device_class_states" (or whatever) - if "true then show "connected", if "false" - show "off".
Default could be "show_device_class_states: true".

### Describe the behavior you expected

States are displayed.

### Steps to reproduce the issue

see above

### What version of Home Assistant Core has the issue?

2022.12.7

### In which browser are you experiencing the issue with?

Chrome 108.0.5359.125 

### Which operating system are you using to run this browser?

Win10x64

**Comment by piitaya** [comment]
It depends of the language. In french for example, the device class translation can be shorter than the default one: 

On/Off is Activé/Désactivé 
Open/Closed is Ouvert/Fermé (window device class)

Also, it was a bug to have On/Off. in some cases. It doesn't make sense to display "On" for a window.

**Comment by ildar170975** [comment]
> We will not add an option to restore a buggy behaviour.

This is NOT a "restoring buggy behaviour" - this is called "adding a flexibility".

**Comment by ildar170975** [comment]
Also, with a new color schema for "on" / "off" - how users are supposed to distinguish cases "off" & "unknown" (different shades of grey) when no states are displayed?
A new option like "show_device_class_states" (described above) add a possibility for users (who knows what they are doing) to show short names.

**Comment by ildar170975** [comment]
what a jerk ))
