### ISSUE TITLE
buttons missing in group options from frontend

### ISSUE THREAD

**Issue by crackers8199** [home-assistant/frontend#14873]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

if you look at group options via settings > devices > helpers > group > group options, all buttons are available (notably the submit button at bottom right).

<img width="593" alt="Screenshot 2022-12-23 at 12 37 34 AM" src="https://user-images.githubusercontent.com/288927/209302335-f0a00adf-7851-467f-8218-5371e67e49af.png">

if you view these same group options by clicking a group in a dashboard view, then group options, the submit button is missing. 

<img width="609" alt="Screenshot 2022-12-23 at 12 35 11 AM" src="https://user-images.githubusercontent.com/288927/209302342-636ee3f9-626c-4195-9672-7143c380b7f0.png">

it's still there and you can click it if you know where it is, but otherwise you have no way of knowing where to go from here...

<img width="602" alt="Screenshot 2022-12-23 at 12 35 25 AM" src="https://user-images.githubusercontent.com/288927/209302338-bb943ab7-a01a-4215-9d29-0f561747c897.png">

### Describe the behavior you expected

expecting (obviously) to see the submit button, so that i can modify the group via the dashboard rather than having to go into the settings to do so.

### Steps to reproduce the issue

1. add a group to your lovelace dashboard
2. refresh the page
3. click that group
4. click the settings tab
5. click group options
6. note that there is no submit button - it's there, but the text is not visible and the button is not visible. if you know where it is you can click it, but if you don't know it's there you have no idea where to go next.
...

### What version of Home Assistant Core has the issue?

2022.12.8

### In which browser are you experiencing the issue with?

Version 108.0.5359.124 (Official Build) (arm64)

### Which operating system are you using to run this browser?

macOS Ventura 13.1 (22C65)

### Additional information

the interesting thing is that if you go into the settings and hit group options that way, then go back to the dashboard, then into group options from the dashboard as described, the submit button becomes visible...but as soon as you reload the page, the submit button is missing if you hit it from the dashboard.

**Comment by karwosts** [comment]
Can confirm. It looks like when going through the frontend, the translation for "ui.panel.config.integrations.config_flow.submit" is missing from the localization dictionary, so it returns a blank string instead of "Submit". 

Haven't figured out yet what causes some translations to get loaded in the dictionary and not others.
