### ISSUE TITLE
History page: removing a duplicate entity -> removing both entities

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#14875]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Sometimes I need to watch a History for 2 and more related entities.
Since dropdown-list fields are too narrow (https://github.com/home-assistant/frontend/issues/13671) - sometimes **I select wrong entities.**
And sometimes ONE entity may be selected TWICE:

![image](https://user-images.githubusercontent.com/71872483/209336442-c1db4a24-3250-4c45-b3e7-82d89579eb67.png)

When I try to delete a mistakenly selected duplicating entity - BOTH are deleted:

![image](https://user-images.githubusercontent.com/71872483/209336555-24284c61-0132-46f7-ab69-bb77307a2e7f.png)

### Describe the behavior you expected

If some entity is selected 2 or more times - deleting this entity must delete only this one entity, not all of them.

### Steps to reproduce the issue

1. Go to History.
2. Add an entity.
3. Add the same entity.
4. Delete the last entity.

### What version of Home Assistant Core has the issue?

2022.12.7

### In which browser are you experiencing the issue with?

Chrome 108.0.5359.125

**Comment by karwosts** [comment]
Maybe just make sense to remove an item from the picker list once it is displayed, probably should not allow the same entity to be chosen twice anyway?

**Comment by ildar170975** [comment]
Imho this is a good alternative way.
