### ISSUE TITLE
Lock not longer in color

### ISSUE THREAD

**Issue by XalaTheShepard** [home-assistant/frontend#14878]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In HA Core 2022.12.0 the color of the locks was red when they were locked and green when they were unlocked.  After a later update the locks no longer have a color for whichever state they have. 

### Describe the behavior you expected

When the lock is locked, the lock is in the color red. When the lock is unlocked, the lock is in the color green. 

### Steps to reproduce the issue

1. Downgrade to HA Core 2022.12.0
2. The locks have colors again depending on their state.
3. Update to the latest HA Core
4. The locks have no colors anymore, whichever their state is. 

### What version of Home Assistant Core has the issue?

2022.12.8

### What was the last working version of Home Assistant Core?

2022.12.0

### In which browser are you experiencing the issue with?

Chrome, Firefox and Android app

### Which operating system are you using to run this browser?

Linux, Windows, Android

### State of relevant entities

```txt
Entity lock.lock state locked / unlocked
```

**Comment by dshokouhi** [comment]
I don't think this is a bug, to many users a red icon means they need to take action upon it and in this case it means to unlock the door but nobody wants to sleep with unlocked doors. I'm actually happy they changed it.

**Comment by marcforn** [comment]
I think they should at least allow the modification by state-lock-unlocked-color. If people wants to keep it as default they do not need to touch nothing but the ones that we had it 1 month ago working right now we have a bad UI on our Dashboards. For me it's a breaking change in the last version and any new release should have retrocompatibility unless a major change was bumped.

**Comment by XalaTheShepard** [comment]
If the users don't want any color for their locks, they can just disable in the lovelace dashboard the color state. So can everyone choose whether they want it in color or not
