### ISSUE TITLE
Cover opening/closing state set incorrectly to is_opening/is_closing

### ISSUE THREAD

**Issue by LukasPieger1** [home-assistant/frontend#14883]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I was configuring an automation for my cover through the GUI and it wouldn't check if the cover was currently closing or opening. I fixed this by manually editing the automations.yaml and changing the state-check "is_closing" or "is_opening" to "opening" or "closing". It wouldn't let me change it in the yaml editor of the GUI though and I had to use the VSCode plugin to do so.

![Screenshot from 2022-12-25 23-05-01](https://user-images.githubusercontent.com/65824984/209483057-d350179a-8fea-433c-ac84-35c243221834.png)

This also seems to be wrongly documented on the cover_entity page ( https://developers.home-assistant.io/docs/core/entity/cover/ )

I am using this curtain module through a ZHA integration:
 https://moeshouse.com/products/zigbee-diy-curtain-switch-module?_pos=10&_sid=ff861061f&_ss=r&variant=39293510090833

### Describe the behavior you expected

The given gui option correctly sets the state to "opening" and closing"

The GUI yaml-editor doesn't stop me from editing this.

### Steps to reproduce the issue

1. create a condition in an automation
2. select device -> &lt;curtain device&gt;
3. select &lt;curtain device&gt; is opening/&lt;curtain device&gt; is closing
4. inspect yaml

### What version of Home Assistant Core has the issue?

Home Assistant 2022.12.8 Supervisor 2022.11.2 Operating System 9.4 Frontend 20221213.1 - latest

### In which browser are you experiencing the issue with?

chromium through rambox

### Which operating system are you using to run this browser?

Ubuntu 20.04

**Comment by karwosts** [comment]
Looking at components/cover/device_conditions.py it does seem like "is_closing" is the right thing to check for a device. Don't quite understand all of this but I'm not confident this is a frontend bug. 

Have you tried maybe triggering on the entity state, instead of a device "is_closing" condition? I think the entity state is "closing", and the device_condition type is "is_closing".

**Comment by LukasPieger1** [comment]
You're correct. After some more investigation my device reported its state incorrectly ...when closing it while fully open its state is 'is_closing' for a split second and jumps right back to 'open'.

Sorry for the wrong report seems my investigation wasn't thorough enough.

**Comment by LukasPieger1** [comment]
Is that a homeassistant bug or the maufacturers fault? I'm not sure on where to go next with this issue😅

**Comment by karwosts** [comment]
Well lets debug a little more to see. For one thing lets correct the terminology. Devices don't have state. Devices have entities, and entities have state. 

The entity that represents your cover, if you go through a full open -> close -> open cycle, what states does it cycle through?

I would expect "open" -> "closing" -> "closed" -> "opening" -> "open".
