### ISSUE TITLE
"Choose Area" shows incomplete list of areas

### ISSUE THREAD

**Issue by ndoggac** [home-assistant/frontend#14885]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating a new automation/script/scene, the "Choose Area" button does not display every area created.  If I type in a missing area, it does not appear.

### Describe the behavior you expected

Believe the "Choose Area" menu should include every area created.  It should be a scrollable list, and it should show those areas when I start typing.

### Steps to reproduce the issue

1.  Settings > Automations & Scenes > Scripts > Add Script (or automation - same behavior)
2.  Sequence > Add Action > Call service
3.  light.turn_off
4.  click the "Choose Area" button
5.  the menu only shows 6 areas (I have 17 created), isn't scrollable, and doesn't list the missing areas when I type them.
6. I can select one of the six areas shown, then switch to "Edit in YAML", change the area id to the missing name I want, and then switch back to "Edit in Visual Editor" as a workaround.
7. Once back in visual editor, and I can click on the <> arrows in the target area to split devices properly, even though it was previously missing.

### What version of Home Assistant Core has the issue?

2022.11.2, OS 9.4, Frontend 20221213.1

### In which browser are you experiencing the issue with?

Chrome, Firefox, Edge

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
none
```

### Problem-relevant frontend configuration

```yaml
none
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

none

**Comment by karwosts** [comment]
Looks like it maybe only is selecting areas that have at least one device in that area. Does that match what you see?

The code may also be attempting to select areas that have an entity as well, but I there may be a typo that cause that to not work, not quite sure yet.

**Comment by ndoggac** [comment]
Thanks for taking a look at this!

That does not match what I'm seeing.  Here's some [screenshots](https://drive.google.com/drive/folders/11_rfCNywbeokUVUOQy9Kw89W8ks2xhVA?usp=sharing).

01 shows attempt to create new script with service "Light: Turn Off".  Clicked the choose area button.  Note no scroll bar in menu, six areas are all that appear.

02 shows me typing "k" to try and get kitchen to come up, with no result

03 shows all 17 zones (including Kitchen which should have shown with "k" typed, with 6 entities)

04 shows the Kitchen area menu, note the "Single Can" entity

05 shows the single can is a "light" entity, which means kitchen should have populated with the "Light: Turn Off" service selected in the script.  

(Only edits I made to the images were to remove usernames)

**Comment by karwosts** [comment]
I believe the intention was for the areas list to only show areas that had a device or entity that could be the target of the service you were calling. 

However unfortunately both are broken. The entities Filter was not filtering correctly, so it ignored all entities. The devices filter is not working correctly either, so it includes all devices, even those which are not a target for the service. 

I believe my pull request will at least fix the entities part. The list will still include too many items that don't belong, but at least now nothing will be incorrectly excluded.

**Comment by ndoggac** [comment]
Thanks for the super fast response time!  Much appreciated.
