### ISSUE TITLE
Accuweather integration setup, unable to enter negative latitude or longitude 

### ISSUE THREAD

**Issue by troyweber** [home-assistant/frontend#14904]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Unable to enter negative values so I get a location in the wrong hemisphere or Europe instead of USA. Also, can’t update location after entering it on initial setup requiring removing and re-adding the integration to change location. Input appears to be filtered to positive numbers.

### Describe the behavior you expected

Enter -95.12345 in longitude.

### Steps to reproduce the issue

1. Press negative sign in chrome or try on android app, no - available.
2.
3.
...

### What version of Home Assistant Core has the issue?

Core-22-5-2

**Comment by karwosts** [comment]
I didn't have any problem inputting negative number into Chrome. I didn't have an api key so I couldn't go through the full setup, but it didn't obviously complain about the negative sign. 

You clicked the checkbox to claim you're on latest version, but you also say Core-22-5-2, which sounds old, do you really have 2022.12.8?

**Comment by troyweber** [comment]
Confirmed resolved in Core-22-12-8. I didn't realize I had tagged my container to the specific version as I don't usually do that until I have services all working the way I like. Thank for your quick response that helped me out!
