### ISSUE TITLE
Camera Flickering using Picture Cards

### ISSUE THREAD

**Issue by twright5** [home-assistant/frontend#14928]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Two camera streams on same dashboard page flickering, look as if the flicker is caused by them swapping frames between the two streams. I have screen captured this behaviour and documented it here: https://www.reddit.com/r/homeassistant/comments/z5iijq/cameras_flickering_on_ha_dashboard/

### Describe the behavior you expected

Smooth/non-flickering stream from each camera displayed in two separate picture entity/glance cards.

### Steps to reproduce the issue

1. Create picture entity card or picture glance card and add Camera Stream as target entity
2. Select camera stream from camera stream menu
3. Set mode to live
4. Repeat for second camera stream

### What version of Home Assistant Core has the issue?

core-2022.12.8

### What was the last working version of Home Assistant Core?

core-2022.4.7

### In which browser are you experiencing the issue with?

Brave Version 1.46.144 Chromium: 108.0.5359.128 (64-bit)

### Which operating system are you using to run this browser?

Windows 11 x64 22621.525

### State of relevant entities

```txt
access_token: 230f40b5bf....
model_name: C310
brand: TP-Link
motion_detection: on
frontend_stream_type: hls
ffs: false
device_type: SMART.IPCAMERA
device_model: C310
device_name: C310 1.0
device_info: C310 1.0 IPC
hw_version: 1.0
sw_version: 1.3.2 Build 220901 Rel.74359n(4555)
device_alias: Driveway Camera
avatar: Garage
longitude: 0
latitude: 0
has_set_location_info: 0
features: 3
barcode: 
mac: B4-B0-24-E6-F1-CF
dev_id: 80218360F61C613D363FE3C14CBB58CD1F6BB45C
oem_id: 15483C2A4CF035EA06109A2782F10C2C
hw_desc: 00000000000000000000000000000000
is_cal: true
alarm: off
user: admin
presets: 
{}

entity_picture: /api/camera_proxy/camera.driveway_camera_sd?token=230f40b5bf230a4a3b9f4d8e5916.....
icon: mdi:cctv
friendly_name: Driveway Camera SD Stream
supported_features: 3
```

### Problem-relevant frontend configuration

```yaml
show_state: false
show_name: true
camera_view: live
type: picture-entity
image: https://demo.home-assistant.io/stub_config/bedroom.png
entity: camera.driveway_camera_sd
camera_image: camera.driveway_camera_sd
```

### Javascript errors shown in your browser console/inspector

```txt
Only 1 error, I believe related to a custom card so un-related:

Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "light-entity-card-editor" has already been used with this registry
```

### Additional information

No issue viewing the same dashboard configuration via the iPhone app, or via Chrome on MacOS. I have tried viewing in Firefox on my machine and seems to be okay but my main browser is Chromium with this issue.

https://user-images.githubusercontent.com/96025791/210093404-b1040664-3325-445e-84c4-019843807c3b.mp4

**Comment by GoldenEyes78** [comment]
I have the same problem recently, the same mobile was working fine with the same setup no wrong till I factory reset to my mobile and install home assistant again, but comes with this problem. Please if anyone find the solution just update me.

**Comment by Machtendrg** [comment]
No fix yet ....
