### ISSUE TITLE
Dashboard view showing 1 card in panel mode still rounds corners

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#14945]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When you set a card to be in panel mode, so we only show 1 card in a view, the corners are still rounded and show in the edges.

![CleanShot 2022-12-31 at 15 16 21](https://user-images.githubusercontent.com/1444314/210154894-750946bb-a795-40e9-a28f-154a417deb37.png)

### Describe the behavior you expected

I would expect there to be no rounded corners, so it behaves more like a UI component than a stretched out card.

### Steps to reproduce the issue

1. Create dashboard
2. Edit
3. Add card
4. Enable panel mode in edit view

### What version of Home Assistant Core has the issue?

nightly

**Comment by mvdwetering** [comment]
Still exists in:

Home Assistant 2023.3.6
Supervisor 2023.03.3
Operating System 9.5
Frontend 20230309.1 - latest

**Comment by mvdwetering** [comment]
Still exists in:
Home Assistant 2023.6.3
Supervisor 2023.06.4
Operating System 10.3
Frontend 20230608.0 - latest
