### ISSUE TITLE
Energy tab is not showing 1.january right

### ISSUE THREAD

**Issue by Hadatko** [home-assistant/frontend#14956]
### The problem

I am expecting that i should see Jan1 on graph bellow instead of January
<img width="681" alt="image" src="https://user-images.githubusercontent.com/13130700/210235478-b364ca16-967c-4486-a4e8-ba0493749454.png">

### What version of Home Assistant Core has the issue?

core-2022.12.8

### What was the last working version of Home Assistant Core?

unknown

### What type of installation are you running?

Home Assistant Supervised

### Integration causing the issue

Home Energy Management

### Link to integration documentation on our website

https://www.home-assistant.io/docs/energy/

**Comment by jackwilsdon** [comment]
It's worth noting that Home Assistant does this for all months, not just January:
![Screenshot of energy graph showing 1st of December](https://user-images.githubusercontent.com/1843197/210285869-3a5f7785-a4e3-4024-8f40-d30316c67332.png)

**Comment by jackwilsdon** [comment]
After doing some digging, it seems like Chart.js is configured to use the major unit for major tick marks (days in this case). The major unit is decided by just taking the next "common" interval after the configured one, which in this case is months (the next common interval after days).

The code to decide the major unit is here: https://github.com/chartjs/Chart.js/blob/51441272a781ba575149b214933f0c5b4bafb6ab/src/scales/scale.time.js#L126-L132

And the major unit is used in this function for major tick marks: https://github.com/chartjs/Chart.js/blob/51441272a781ba575149b214933f0c5b4bafb6ab/src/scales/scale.time.js#L505-L531

We could possibly write our own tick formatting function to override this behaviour, or we could just disable major ticks altogether.

**Comment by Hadatko** [comment]
It is doing that also for months view (month replaced with year)

**Comment by jackwilsdon** [comment]
![Screenshot showing the problem](https://user-images.githubusercontent.com/1843197/229393315-759771db-0ad0-4bc5-8306-5087a1ae59bc.png)

This is still happening on frontend 20230309.1.

**Comment by Hadatko** [comment]
It looks like it is solved in current release
