### ISSUE TITLE
Energy dashboard not showing month/year bar correctly

### ISSUE THREAD

**Issue by TyzzyT** [home-assistant/frontend#14950]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Today is January 1st, and when I look at the month view of January or the year view of 2023, there is only one bar showing on the energy dashboard. But this bar is not showing correctly, it's aligned too far to the left.
On desktop, I only experience this for the month view. On the iOS app, I experience this weird alignment on both month and year view.

### Describe the behavior you expected

I expect the bar to show on the correct location

### Steps to reproduce the issue

1. Open energy dashboard
2. Set view to month
3. Watch the bar be aligned wrong

### What version of Home Assistant Core has the issue?

core-2023.1.0b3

### What was the last working version of Home Assistant Core?

never

### In which browser are you experiencing the issue with?

Brave version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11 22H2 and iOS 16.2

### Additional information

![IMG_3819](https://user-images.githubusercontent.com/80623729/210179568-e5f798fc-8aea-49c0-8990-797fa6773f00.png)
![wyaeiyQWHEqwayeh3iuqwkheqn23k](https://user-images.githubusercontent.com/80623729/210179575-d0ef52ab-e59e-4634-8b96-6c52416c0ef5.png)

**Comment by TyzzyT** [comment]
Still the same with 2023.3.6

**Comment by TyzzyT** [comment]
Still the same with 2023.6.3

**Comment by morgantic** [comment]
Same issue here with a 14 day graph with multiple values per day.

<img width="1149" alt="image" src="https://github.com/home-assistant/frontend/assets/126607370/486ef700-beab-4a07-8d25-d09b678b2e44">

For reference, here's the preview in the configuration GUI, how it should look:

![image](https://github.com/home-assistant/frontend/assets/126607370/71361b4e-fd19-47e4-a1cb-58faa1ee29a7)

v 2023.10.3
