### ISSUE TITLE
Bug Automation 2022.12 with trigger id and Triggered by ID on actions tab

### ISSUE THREAD

**Issue by S1M8N** [home-assistant/frontend#14962]
### The problem

Hello everyone,

With the "Event" element in the "Triggers" options we can add a "Trigger ID". Then in the actions it is possible to add a "Triggered by ID" and it works perfectly.

However when the "Event" element has a "Trigger ID" but is used in "Actions", it is not found by the "Triggered by ID".

Here is an example of the "problem" encountered:

![image](https://user-images.githubusercontent.com/75216525/207976804-2ccf10d9-b2cf-48af-b56b-fa4422c3b67a.png)

Thanks in advance for your help

Simon

### What version of Home Assistant Core has the issue?

core-2022.12.6

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Automations

### Link to integration documentation on our website

https://www.home-assistant.io/docs/automation/

**Comment by uowis** [comment]
Hi i have exactly same issue.

**Comment by uowis** [comment]
But i have successfully trigger ID in select when id define at the Main automation Trigger,...
