### ISSUE TITLE
Switching service should clear all fields remote.send_command

### ISSUE THREAD

**Issue by TRusselo** [home-assistant/frontend#14968]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

service: remote.delete_commandGUI editor missing checkbox for "command"
unable to create automation / use service dev tool using GUI.
remove existing text from command text feild and retype same word, or switch to yaml. add command manually, it works.

same issue for send_command

remote.learn_command is working as expected.

![image](https://user-images.githubusercontent.com/1154815/210299810-0ec2bdaa-bdbe-4d98-832b-62380bbaa8a9.png)

### Describe the behavior you expected

there should be a checkbox beside Command in GUI editor for service.delete_command, 

### Steps to reproduce the issue

If you use any of the 3 above commands, and have text in the command box, change commands, it leaves text in the Command Text box, but wont work until you delete the text, retype text.

Step 1 dev tools/ service
2. service remote.learn command
3. fill in field for "commands", ect build a working service call.
4. change service to send.command
5. attempt to build a send.command while leaving the command text field alone from last step.

you wont be able to action service until you remote the text from "commands" and retype the same word.

same if switching from learn_command to delete_command
same if you try to build automation, script, not tied to dev tools.

### What version of Home Assistant Core has the issue?

core-2022.12.9

**Comment by TRusselo** [comment]
Nevermind.  slightly different bug.

If you use any of the 3 above commands, and have text in the  command box, change commands, it leaves text in the Command Text box, but wont work until you delete the text, retype text.

Step 1 dev tools/ service
2.  remote learn command
3. fill in feild for "commands"  
4. change service to send command
5. attempt to build a send command while leaving the command text feild alone from last step.

you wont be able to action service until you remote the text from "commands" and retype the same word.

**Comment by piitaya** [comment]
`command` is required for `send` and `delete` but optional for `learn`. That's why there is a checkbox or not.

Switching service should clear all fields but it's not the case (it's cleared in the yaml but not the GUI) : That's the bug

**Comment by TRusselo** [comment]
kinda figured that out after posting
but i found something...
i feel good about myself. thank you. lol

**Comment by karwosts** [comment]
I believe this is the same bug that I triaged on a different issue (#14988)

Should be fixed by #15022
