### ISSUE TITLE
Thermostat card does not reflect values sent by MQTT climate module

### ISSUE THREAD

**Issue by mbisak** [home-assistant/frontend#14961]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Thermostat card sometimes does not reflect target temperature value sent by the MQTT module. It reflects MQTT target temperature value in place where the ciphers are but does not reflect it in the point/ball position.

Point/ball usually stucks at position set by user even if it receives different value through MQTT. So for example user sets 21 degrees, it is displayed in the UI, MQTT publishes 21 degrees as confirmation but when MQTT publishes next value, for example 30 degrees, target temperature is changed but point/ball position stucks at 21.

For details, please check:
https://github.com/home-assistant/core/issues/84745

### Describe the behavior you expected

Ball/point position should always reflect values sent by MQTT

### Steps to reproduce the issue

import paho.mqtt.client as mqttc

def on_message(client, userdata, msg):
    print("Received",msg.topic+" "+str(msg.payload))
    print("Publishing",MQTTSTATETOPIC,msg.payload)
    mqttSession.publish(MQTTSTATETOPIC, msg.payload)
    print("Publishing temp that HVAC set and decided internally", MQTTSTATETOPIC, 35)
    mqttSession.publish(MQTTSTATETOPIC, 35)
    print("------------")

MQTTBROKER = '192.168.2.10'
MQTTPORT = 1883
MQTTCMDTOPIC = 'etatherm/1/temperature/target/set'
MQTTSTATETOPIC = 'etatherm/1/temperature/target'
MQTTMODETOPIC = 'etatherm/1/mode'

print("Start")
mqttSession = mqttc.Client(client_id='test', protocol=mqttc.MQTTv311, transport='tcp')
mqttSession.connect(host=MQTTBROKER, port=MQTTPORT, keepalive=60)
mqttSession.subscribe(topic=MQTTCMDTOPIC)
mqttSession.on_message = on_message
mqttSession.publish(MQTTSTATETOPIC, 10)
mqttSession.publish(MQTTMODETOPIC, 'auto')

while True:
    mqttSession.loop()

----------------------------------------------------------

The MQTT object is defined like this:

    name: "Pracovna"
    object_id: etatherm_pracovna_topeni
    unique_id: etatherm_pracovna_topeni
    current_temperature_topic: "etatherm/1/temperature/real"
    temperature_unit: "C"
    precision: 1.0
    min_temp: 6
    max_temp: 35
    initial: 19
    temp_step: 1
    temperature_state_topic: "etatherm/1/temperature/target"
    mode_state_topic: "etatherm/1/mode"
    mode_command_topic: "etatherm/1/mode/set"
    temperature_command_topic: "etatherm/1/temperature/target/set"

climate.etatherm_pracovna_topeni:
hvac_modes:

    auto
    'off'
    heat
    friendly_name: Topení v pracovně

### What version of Home Assistant Core has the issue?

2022.12.8

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

Windows, Android

**Comment by jbouwh** [comment]
I can confirm the state is updated, but MQTT updates the state to the original value of the climate UI element, not to the value set in the UI. That UI change is not written as state. Somehow this sate update is not recognized as a change because the entry state is not compared to the actual UI element state.

**Comment by mbisak** [comment]
> Can you provide the state of your entity using dev tools? Thermostat card just reflect the `temperature` attribute from state.

Hello, I'm not familiar with that so could you please provide me any link that would show me how?

Thank you, Martin

**Comment by msp1974** [comment]
@jbouwh I read this before logging and issue with this thermostat card and have now re-read and think this is the same issue I am having.  Does the more-info dialog reflect the state correctly?

See issue #15483 - is this the same problem different symptom?

**Comment by mbisak** [comment]
Hello,
more info dialog works strange as well. In auto mode, I set target temp by point to e.g. 35 degrees, point stucks at 35 even if MQTT says 21. More info shows 21, but point is still stuck at 35. From this perspective more info works well. But if I change target temp using more info, I click on arrows and set 35, it should change back to 21, which is sent back by MQTT. But it stucks at at set target temp as well most of the time.

**Comment by karwosts** [comment]
@mbisak - I think a screen recording may help show what you're seeing. I think I understand what you're saying but it's hard for me to imagine how that is happening, would be nice to visualize it. If you don't have one, I like https://www.screentogif.com/

I'm not convinced your issue is the same as 15483... sounds a bit different to me, but maybe I'm just not understanding what you're saying.

**Comment by jbouwh** [comment]
> @jbouwh I read this before logging and issue with this thermostat card and have now re-read and think this is the same issue I am having. Does the more-info dialog reflect the state correctly?
> 
> See issue #15483 - is this the same problem different symptom?

It looks like it.

**Comment by karwosts** [comment]
Is this working now in 2023.3?

**Comment by jbouwh** [comment]
From what I can see, values set in the UI will be reset (after a short delay) to their initial state if the state is not confirmed. I think that is the expected behavior.

**Comment by jbouwh** [comment]
I believe this can be closed.

**Comment by mbisak** [comment]
Yes, everything is fine now.


Martin

Dne 06.06.2023 v 13:29 Jan Bouwhuis napsal(a):
