### ISSUE TITLE
Water meter yearly cost showing far too much

### ISSUE THREAD

**Issue by Sabreu** [home-assistant/frontend#14960]
### The problem

I did setup water meter monitoring a little while back and it seems that energy dashboard is showing yearly water cost badly wrong for some reason (see pic below). Monthly & daily cost is showing correctly.

Yearly:
![kuva](https://user-images.githubusercontent.com/1567864/209175035-b80f2e8e-5350-4c4d-9a31-f955d1ece3d4.png)

Monthly:
![kuva](https://user-images.githubusercontent.com/1567864/209175105-c9c6d136-124b-4640-bb0c-f42ca247517c.png)

### What version of Home Assistant Core has the issue?

2022.12.8

### What type of installation are you running?

Home Assistant Container

**Comment by frenck** [comment]
I suspect this is a frontend issue (which does smart things with year views), so transferred the issue.

**Comment by karwosts** [comment]
@frenck - I think this might really be a backend issue.

I looked in the frontend code for this energy table and the cost number is coming from a sensor entity, not from a computation in the frontend:

![image](https://user-images.githubusercontent.com/32912880/227047769-99b88862-83f3-45b2-b2d2-31564c1edf1f.png)

I created the water consumption sensor, and I think the "cost" sensor was created when I added it to energy dashboard.

![image](https://user-images.githubusercontent.com/32912880/227048346-6a73b72e-f6c4-415c-93f8-ff38fdd99d14.png)

The water consumption is in units of CCF, and the price in energy dashboard is 0.15 USD/CCF.

The cost sensor is converting CCF to gallons ( 1 CCF = 748 gallons ), and then charging me 0.15 USD/gallon, it should be 0.15 USD/CCF.

Energy dashboard setting: 
![image](https://user-images.githubusercontent.com/32912880/227048957-3db235c0-a9ba-481c-8afa-b905cb9f27d1.png)

**Comment by karwosts** [comment]
Probably related to this. Frontend says the static price is in USD/CCF, but in the energy integration the `default_price_unit` is gallons.


```
    @callback
    def _update_cost(self) -> None:
        """Update incurred costs."""
        if self._adapter.source_type == "grid":
            valid_units = VALID_ENERGY_UNITS
            default_price_unit: str | None = UnitOfEnergy.KILO_WATT_HOUR

        elif self._adapter.source_type == "gas":
            valid_units = VALID_ENERGY_UNITS_GAS
            # No conversion for gas.
            default_price_unit = None

        elif self._adapter.source_type == "water":
            valid_units = VALID_VOLUME_UNITS_WATER
            if self.hass.config.units is METRIC_SYSTEM:
                default_price_unit = UnitOfVolume.CUBIC_METERS
            else:
                default_price_unit = UnitOfVolume.GALLONS
```

**Comment by karwosts** [comment]
I believe what is happening here is that when you choose "static price" for water, the frontend shows the unit of the static price based on the chosen sensor (so if I have sensor in CCF it shows USD/CCF). However in backend this doesn't seem to be supported, and static price sensors are always priced based on the default_price_unit, which is gallons.
