### ISSUE TITLE
Addon configuration option/array seems to be broken

### ISSUE THREAD

**Issue by atownsend247** [home-assistant/frontend#14972]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This half related to the ring-mqtt addon, but have noticed it on other configuration items.

When entering configuration for an array/list on the addon page, it displays in the UI as a dropdown but I'm unable to add/amend options. For ring-mqtt I'm trying to enter a specific location for the addon, but no matter what way I try it seems to clear the field when I go to save or move focus.

I've attached a recording/gif of the interaction.

### Describe the behavior you expected

I would expect to be able to enter a array of strings as per the documentation and not to loose the input upon changing focus.

### Steps to reproduce the issue

1. Go to an addon that has one of these multi field drop downs
2. Enter the list of configuration
3. Click out of the field or move focus 
4. Your input has been removed from the field

### What version of Home Assistant Core has the issue?

Home Assistant 2022.12.9 Supervisor 2022.12.1 Frontend 20221213.1 - latest

### In which browser are you experiencing the issue with?

Chrome 108.0.5359.124 (Official Build) (x86_64), Safari Version 16.0 (17614.1.25.9.10, 17614)

### Which operating system are you using to run this browser?

macOS Monterey 12.6

### Javascript errors shown in your browser console/inspector

```txt
none that I can see
```

### Additional information

![Screen Recording 2023-01-03 at 12 42 03](https://user-images.githubusercontent.com/3439514/210360691-eccae58a-4bed-49d4-a8a3-8ef9b37e5877.gif)

**Comment by aegjoyce** [comment]
Also having this issue which appears to be specific to Safari and the iOS app. Currently running 2023.3.6 on HAOS.

Safari:
<img width="1912" alt="Screenshot 2023-04-04 at 08 21 00" src="https://user-images.githubusercontent.com/47081267/229720936-527ad4c1-3a71-4573-a3be-ea88d1eddedf.png">
<img width="1912" alt="Screenshot 2023-04-04 at 08 21 20" src="https://user-images.githubusercontent.com/47081267/229720953-d7307a14-4f4b-4431-85aa-6983967f556a.png">

Chrome:
<img width="1912" alt="Screenshot 2023-04-04 at 08 21 35" src="https://user-images.githubusercontent.com/47081267/229721029-a99addca-8f89-4804-bb76-970b097dc8be.png">
<img width="1912" alt="Screenshot 2023-04-04 at 08 21 47" src="https://user-images.githubusercontent.com/47081267/229721055-f3581e5b-d261-47dd-a6b3-22f01e693914.png">


As you can see the array boxes render correctly in Chrome. This wasn't an issue in Safari previously but I can't recall the last time I had to edit an array box in an addon config.

The same rendering problems occur in the iOS app.

In addition, clicking the option to open a YAML editor in the config does not render an editing box:
<img width="1912" alt="Screenshot 2023-04-04 at 08 37 22" src="https://user-images.githubusercontent.com/47081267/229721555-3a5cc9c7-b6d3-46b7-b0db-64d0b51c4795.png">
