### ISSUE TITLE
Color selection for lights is missing from visual editor

### ISSUE THREAD

**Issue by LuxStatera** [home-assistant/frontend#14971]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I can't turn on lights and set them to a specific color in the visual editor. The only option is to edit the yaml to change the colors. The visual editor has been slowly removing options. Some of the options still appear to be there but they do not work. Still must be edited in the yaml. I mainly noticed this with lights but I'm pretty sure this has also been happening with other service actions when creating automations or scripts.

### Describe the behavior you expected

Before I was able to create a new script or automation and in the actions section I would call a service to turn on a light. From there I was given other options like color, temperature, brightness, etc. There was an option that showed a wide spectrum of colors to choose from that looked like a rainbow and was lighter at the top and darker at the bottom so you could select the color by eye. This has been removed for some reason and the other options for choosing colors do not work

### Steps to reproduce the issue

1. create new automation
2. when adding an action choose "call service"
3. choose "light.turn_on"
4. look for color graph to adjust colors
5. see it is not there
6.  try other options to adjust color
7.  save the automation
8.  run the automation
9.  the automation fails to turn on the lights and change the colors
...

### What version of Home Assistant Core has the issue?

all of them for the past few months

**Comment by LuxStatera** [comment]
![96eNV](https://user-images.githubusercontent.com/73693443/210413624-d9796124-1af9-4918-81cb-f8fe56d49492.png)

This is not a screenshot from Home Assistant but the option looked somewhat like this. Also the color option you mentioned is visible in the visual editor but does not actually work

**Comment by karwosts** [comment]
You said the color picker is not there. and I confirmed that it is. 

Now you're saying it is there, but it does not work. I don't agree. When I pick a color, I can immediately flip over to yaml mode and I see it reflected in the yaml:

```
action:
  - device_id: 24d923c8f42a21f75dfa8f50e3dc6f8d
    domain: climate
    entity_id: climate.thermostat
    type: set_preset_mode
    preset_mode: Auxiliary
  - service: light.turn_on
    data:
      rgb_color:
        - 24
        - 71
        - 180
```

If I click on the box next to color I get the color picker to popup with the rainbow selector. Still not clear to me what your actual issue is.

![image](https://user-images.githubusercontent.com/32912880/210414482-ccfaac0c-6e57-4e08-b0ff-7849cd4a8c3e.png)

**Comment by LuxStatera** [comment]
I said the options for colors are there but thr color graph is not and also that those color options are not turning on the light or changing the color. That option you are showing only allowed text to be entered which did not do anything. I got a notification to update to the latest core this morning and now I am not seeing any options for lights at all. 

I apologize if I am not explaining the situation very well.

I mentioned this issue on the HA Facebook page and the HA forum and other people also mentioned they were having the same issue so I must not be saying this correctly

![Screenshot_20230103_110817](https://user-images.githubusercontent.com/73693443/210416335-aead5cce-3b79-416f-96ea-61db2122f7e1.jpg)

**Comment by LuxStatera** [comment]
![FB_IMG_1672770056450](https://user-images.githubusercontent.com/73693443/210417759-852f1791-ccb6-47da-be10-fa6de7719602.jpg)


This was the screenshot I posted to the HA Facebook when the light_on action changed to "activate" and the all of the options were missing. It came back but they did not work and also the full rainbow graph was gone

**Comment by karwosts** [comment]
Thanks for the screenshots, that helps to show what you're actually seeing. Those do look unusual for the missing fields.

I assume you're on a mobile app, can you make sure the app's cache is cleared if you just updated?

Also would be good to try a computer web browser if you have one.

**Comment by LuxStatera** [comment]
I deleted cache and also tried a new broswer on a seperate computer but all the options are still missing. An update or 2 before this I did see color options but they did not work and that color graph was not visible

**Comment by karwosts** [comment]
Hm, I'm stumped sorry. All I can suggest is fill out a little more details in the request:

Your core version, install type (os/container/other), OS version, frontend version, etc).

**Comment by LuxStatera** [comment]
HA OS on a Raspberry Pi 4 using a SSD

![Screenshot_20230103_121131](https://user-images.githubusercontent.com/73693443/210425107-bd419f8d-2f13-4cdc-9848-2734e4a839aa.jpg)
(current info)

These settings isssues have been going on for like a month or 2. I always update everything immediately but I did wait for a little bit maybe a week ago so I could handle some front-end theme problems. The settings issues began before that and continued after so I don't think the delay of the update was the cause

**Comment by karwosts** [comment]
I see you've got an interesting color scheme going I haven't seen, maybe if you've got some kind of HACS stuff or integrations installed that mess with how the pages render, might try removing some of that for testing, see if its related.

**Comment by spacegaier** [comment]
@LuxStatera I also cannot reproduce the issue, but your screenshots also look weird to me. In one it initially looks as if you did select the `light.turn_on` service, but the describes talks about activating a scene.

=> Can you please post the YAML of the automation that causes the issue for you. That might help narrow it down further. Also is this automation based on a blueprint or created completely standalone/new?
