### ISSUE TITLE
Climate mode localizations not working

### ISSUE THREAD

**Issue by schotime** [home-assistant/frontend#14981]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Fan modes and Swing modes both aren't translating the raw values and are left in lower case. 

<img width="423" alt="image" src="https://user-images.githubusercontent.com/202923/210481888-9502ac24-f035-41be-98d3-9965b0e43827.png">

The Operation dropdown is getting translated correctly using the following.

https://github.com/home-assistant/frontend/blob/dev/src/dialogs/more-info/controls/more-info-climate.ts#L201-L209

Whereas the Fan mode and swing are using the following that isn't working.

https://github.com/home-assistant/frontend/blob/dev/src/dialogs/more-info/controls/more-info-climate.ts#L267-L275

### Describe the behavior you expected

Should be using the translated Title case values as found in here.

![image](https://user-images.githubusercontent.com/202923/210482197-d7b59b26-2913-479e-aaa8-f8486743f7ac.png)

https://github.com/home-assistant/core/blob/dev/homeassistant/components/climate/translations/en.json

### Steps to reproduce the issue

1. Click on the more info dots for a climate control.

### What version of Home Assistant Core has the issue?

2022.12.9

### In which browser are you experiencing the issue with?

Edge 108.0.1462.54

### Which operating system are you using to run this browser?

Win10

**Comment by steverep** [comment]
Please provide any code in actual text instead of images, which are more difficult to read, not accessible to screen readers, and not searchable.

**Comment by schotime** [comment]
Seems to be fixed in 2023.2.3
