### ISSUE TITLE
Incorrect target_humidity_min is shown if target_humidity is not set

### ISSUE THREAD

**Issue by jbouwh** [home-assistant/frontend#14995]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

With #14575 the target_humidity is always shown. To solve that now the `target_humidity_min` shows when `target_humidity` is `None`. This is not correct. In cases where `target_humidity` I would like to see a similar behaviour as where the climate control has no actual temperature. It can be set from the UI.

### Describe the behavior you expected

I do not expect to see `target_humidity_min` as active `target_humidity`, in cases where the mode of the humidifier not supports a `target_humidty` and sets it to `null` (`None`).

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.1.0.dev6

**Comment by Shulyaka** [comment]
Sorry, I think I have missed this issue.
The https://github.com/home-assistant/frontend/pull/14575 only fixes a layout issue on certain conditions (a humidifier card didn't show the value in 'panel' mode while showing in non-panel mode), it wasn't supposed to bring any functionality change.

I think we don't actually support humidifiers (or modes) that don't allow setting target humidity, so the behavior in this case is undefined and not documented.
We may think of a proper way to support those. Is a null target humidity a proper way to communicate to the frontend that setting of a target humidity is not supported? Could there be downsides? For example, what if we have "write-only" humidifiers that don't provide their target humidity but allow setting one?

**Comment by jbouwh** [comment]
> I think we don't actually support humidifiers (or modes) that don't allow setting target humidity, so the behavior in this case is undefined and not documented.

Well some humidifiers have an `auto` mode, and then the target humidity can become unknown. In that case we do not want to show the minimum humidity.

**Comment by jbouwh** [comment]
Another case where it goes wrong is where the device is switched off. The target humidity then is no longer exposed and set to None (unknown) but the UI shows the minimum humidity when the target humidity is set to `None`

**Comment by Shulyaka** [comment]
If by 'off' you mean it is unavailable, then it is actually the issue in the backend integration, it should report the correct state as `unavailable`.

**Comment by jbouwh** [comment]
When the device is off the `target_humidity`  is not set as an attrubute

**Comment by jbouwh** [comment]
@Shulyaka Do you think you can solve this issue, may be we should not show `min_humidity` and `max_humidity` if `target_humidity` is `None`?
