### ISSUE TITLE
Time condition UI bug - unselecting all weekdays, leaves yaml, breaks automation

### ISSUE THREAD

**Issue by TRusselo** [home-assistant/frontend#14991]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Condition > Time > Weekdays

Select any weekday, unselect all weekday
yaml will still contain  weekday: [ ]
condition will fail

### Describe the behavior you expected

when removing all weekdays from UI editor, it should remove weekdays yaml.

### Steps to reproduce the issue

1. Create automation with time condition
2. Select any weekday
3. Unselect all weekdays
4.Yaml conains line weekdays: [ ]
5.Contiton fails.
...

### What version of Home Assistant Core has the issue?

core-2022.12.9

**Comment by karwosts** [comment]
Linked PR fixes this issue, thanks for the report.
