### ISSUE TITLE
CO2 Signal and Energy Dashboard show different value for January and for 2023

### ISSUE THREAD

**Issue by Alllfff** [home-assistant/frontend#15008]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I use Signal CO2 integration to show low-carbon energy consumption % in my energy Dashboard. However I have noticed that my January % is 78.77% (this roughly matches days and weeks within the January) but the year 2023 shows as 100%

Anyone else seeing this?

### Describe the behavior you expected

January to have same value as  the year 2023

### Steps to reproduce the issue

1. check monthly value %
2. check yearly value %
3. compare results from 1. and 2.

### What version of Home Assistant Core has the issue?

Home Assistant 2023.1.0

**Comment by mcfly2283** [comment]
+1 Same here
