### ISSUE TITLE
Badge with sensor.moon show text state instead icon

### ISSUE THREAD

**Issue by andrewjswan** [home-assistant/frontend#15001]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Badge with sensor.moon show text state instead icon
![image](https://user-images.githubusercontent.com/3609660/210738108-1be92d2e-beeb-4163-a137-0fee1db84c7d.png)
![image](https://user-images.githubusercontent.com/3609660/210738218-4884e533-8061-432b-ab75-fb14768432e2.png)

### Describe the behavior you expected

Badge with sensor.moon ahould show state icon

### Steps to reproduce the issue

1. Add Badge with sensor.moon sensor
2. Look

### What version of Home Assistant Core has the issue?

core-2023.1.0

### What was the last working version of Home Assistant Core?

core-2022.12.8

### In which browser are you experiencing the issue with?

Google Chrome 108.0.5359.125 

### Which operating system are you using to run this browser?

Windows 10

**Comment by bbr111** [comment]
Same Problem here
