### ISSUE TITLE
Forecast.Solar is summed up for multiple systems in Energy Dashboard-view (intentional?)

### ISSUE THREAD

**Issue by B1rdEater** [home-assistant/frontend#15011]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have three seperate solar systems; for each system I have added a forecast using the Forecast.Solar integration in the Energy dashboard. The dotted lines that are added to the Energy dashboard are displaying the wrong way (summed up).

EDIT: Is this intentional?

See picture:

System 1: 0.85 kWh
System 2: 0.16 kWh
System 3: 0.30 kWh

Line system 1: 0.85 kWh
Line system 2 (sum of 1 and 2): 1.01 kWh
Line system 3 (sum of 1, 2 and 3): 1.31 kWh

![image](https://user-images.githubusercontent.com/114749726/210878289-9b7f8e54-be65-4942-9266-b4b91d8a3a3e.png)

### Describe the behavior you expected

I expect three dotted lines; to represent EACH forecast. Not additions should be done.

See picture:

System 1: 0.85 kWh
System 2: 0.16 kWh
System 3: 0.30 kWh

Line system 1: 0.85 kWh
Line system 2: 0.16 kWh
Line system 3: 0.30 kWh

### Steps to reproduce the issue

1. Add several Forecasts.Solar using the Energy Dashboard
2. Check expected yield in Energy Dashboard
3. Dotted lines are projected wrong
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.1.0

### In which browser are you experiencing the issue with?

Brave Browser

### Which operating system are you using to run this browser?

Windows 10 Home

**Comment by B1rdEater** [comment]
Or is this intentional?

**Comment by bramkragten** [comment]
I think it should show just 1 line, with the sum of all three?

**Comment by 0000vt** [comment]
Yeah same issue. We should have lines for every single system and a seperate line with other formatting to show the sum of all systems.

**Comment by MarcelMester** [comment]
I have a similar issue. I have 2 strings of PV: 8 panels East facing is PV1 and 12 panels West facing is PV2. On the Energy Dashboard I have configured 2 solar production sources pv1 sum and pv2 sum. Pv1 sum has a solar forecast configured with the parameters of the East facing panels and similarly for the pv2 sum.

The pv1 sum and pv2 sum stacked bar plots are correct as is the forecast line for pv1 sum. For pv2 sum, the data in the key when you hover over the bar is correct but the plot line on the chart for pv2 forecast is the =(pv1 sum + pv2 sum) 

The attached figure shows the forecast pv1 sum data point as 2.31 and plots it here. The forecast pv2 sum data point is 1.19 but plots it at (2.31+1.19)= 3.5. This is a bug.
![Solar Forecast Incorrect plot](https://github.com/home-assistant/frontend/assets/138401662/db8a699f-63c5-4dd3-9f61-cd681e70d6f2)

Would be wonderful to be able to configure the colour of the plot lines as a feature request.
