### ISSUE TITLE
Thermostat Card startup status

### ISSUE THREAD

**Issue by sky7176** [home-assistant/frontend#15018]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a "Thermostat Card" for heating my office.
I noticed that after a restart following the updates, the thermostat does not restart with the previous status, if it was active before the restart, I would like it to return to being active, instead the status at restart is always inactive.
Do I have to put something in the xml configuration?
Thank you

Giuseppe

### Describe the behavior you expected

when I reboot, I would like the state to reflect the one before the reboot

### Steps to reproduce the issue

1. Create a Thermostat Card
2. Set on state
3. Restart Homeassistant
...

### What version of Home Assistant Core has the issue?

 Home Assistant 2023.1.1 Supervisor 2022.12.1 Operating System 9.4 Frontend 20230104.0 - latest

**Comment by karwosts** [comment]
This is a /home-assistant/core issue, not a frontend issue. The cards don't manage the state of the thermostat, they just reflect the state and call services. 

I'd imagine there are probably several feature requests, and issues reported regarding startup state for generic_thermostats already.

**Comment by sky7176** [comment]
Ok many thanks,
I opened the issue in a wrong place.

I re-posted the issue in a core forum

Giuseppe
