### ISSUE TITLE
"More Info" popup for Groups contains a meaningless "related" link

### ISSUE THREAD

**Issue by karwosts** [home-assistant/frontend#15023]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If user creates a group helper, and brings up the more info card for that group, the final tab in the popup says "Related". On that tab will be a link that seems completely meaningless:

![image](https://user-images.githubusercontent.com/32912880/211133004-ecd4f3fa-c881-4765-b69f-846c733cb8bb.png)

In my case the link goes to:

 http://homeassistant.local:8123/config/integrations#config_entry=ead7fe0c0e0d96b81253451de3c3db6b
 
Clicking it takes you to the integrations page, though it's not clear why, there's nothing on that page pertaining to groups. Also the #config_entry parameter at the end of the link doesn't seem to do anything either. 

I have no idea why this link is here, it doesn't take you anywhere useful having anything to do with the group.

### Describe the behavior you expected

Link should go to somewhere relevant, or be omitted. 

### Steps to reproduce the issue

1. Create a group (e.g. of lights)
2. Click on the group in the helpers menu (or from anywhere in the dashboard)
3. Click "Related" tab on the popup
4. Follow the link to nowhere. 

### What version of Home Assistant Core has the issue?

2023.01

**Comment by aryatalathi** [comment]
I would like to work on this issue. Please assign me!

**Comment by karwosts** [comment]
In general I don't really see assignments being used in this repository. If you want to work on an issue, you would just create a PR when you have a change ready that you want to submit, you would probably not get any feedback from a mod before you have one ready.  Good luck!
