### ISSUE TITLE
[local calendar] multiple days of weekly recurrence not working

### ISSUE THREAD

**Issue by vpsouza** [home-assistant/frontend#15029]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I try to create/update an event with multiple days of week recurrence only the event at selected date is created and no other recurrence events are created.

### Describe the behavior you expected

If I create an event that happens every mon + wed + fri starting at 2023-1-9 I expected recurrent events every next mon + wed + fri the same time.

### Steps to reproduce the issue

1. Create an event starting 2023-1-9
2. Select the weekly repeat option 
3. Choose mon + wed + fri days of week
4. Only the event at 2023-1-9 will be created without any recurrence 

### What version of Home Assistant Core has the issue?

Corr-2023.1.1

### In which browser are you experiencing the issue with?

Companion for iPad OS 15.2, iOS 16.2, Edge 108.0.1462.62

### Which operating system are you using to run this browser?

iPadOS 15.2 and iOS 16.2

**Comment by bducha** [comment]
Hello, I can confirm that I have the same issue, 2023.1.2 container, Chrome  108.0.5359.124 on Ubuntu 22.04
[Here's a video if that helps resolving the issue](https://user-images.githubusercontent.com/45042181/211645141-584b0e15-f39b-4b8d-b21d-069cfa11567b.webm)

You can see that there is a "lag" when selecting days of repetition, and same when editing the event, the list of days takes time to load.
