### ISSUE TITLE
node red call service node missing line breaks with multiple entities

### ISSUE THREAD

**Issue by stasjminister** [home-assistant/frontend#15036]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This is visible in Node-red. 

When having multiple entities in a list in the call service-node. They appear side by side instead of under each other in a list.

I tried to add in <br> in the code with chrome devtools, then they are listed as they should.. If this could be fixed in CSS or maybe it is messed up with some stray CSS-files, please give me a pointer to where I can find these.
I have not found any other nodes where I can list more entities, so I can not say if it is limited to the call-service-node only..

Before editing code:

![207621671-8b12c8c2-4319-4ad6-84e7-37a979a077c4](https://user-images.githubusercontent.com/11752970/211172375-64944361-b579-4dee-b203-b34ac718bda0.png)

After adding <br>

![207621339-43c778d8-d213-4dc1-8f93-b19f192660df](https://user-images.githubusercontent.com/11752970/211172366-dd5e8af0-9043-4f50-ad26-a6cd826db73c.png)

I tried a new install on a vdi. And imported incremental and then a full backup. 
The partial restores of: 
1. Folders (all available)
2. Addons (all available) 
3. Core 
did not see this issue
But with the full restore, I had the issue again.. Not sure what is omitted with the 3 partials and not the full one..

### Describe the behavior you expected

See the entities under each other and not side by side.
Not: listed sequentially, creating a long list stretching out to the right

### Steps to reproduce the issue

I have not seen anyone else have this issue.. But I cant make it go away. Tried reinstalling Node red several times.
Issue has been present for about 6months. Uncertain when it was introduced.

### What version of Home Assistant Core has the issue?

2022.12.9

### What was the last working version of Home Assistant Core?

minus 6mths at least

### In which browser are you experiencing the issue with?

Chrome, safari, edge

### Which operating system are you using to run this browser?

Tried on MACos, Windows 11,10 android

### State of relevant entities

```txt
Not an entity issue
```

### Problem-relevant frontend configuration

```yaml
Config for Node red is pretty standard. No startup options etc.
```

### Javascript errors shown in your browser console/inspector

```txt
NA
```

### Additional information

Tried to report this in the node-red addon-page but got this back from Frenck:

This is not an add-on issue, but an issue with the Home Assistant node for Node-RED. Please report he issue upstream with them.

From an add-on perspective, there is nothing I can do.

Thanks 👍

../Frenck

**Comment by CrallH** [comment]
@stasjminister did you ever solve this? i have the same problem and it drives me mad!

**Comment by stasjminister** [comment]
This was resolved as some css was included i the tibber api contrib-package. Upgrade that one to 6.0.1 and it should be ok
