### ISSUE TITLE
2023.1.0 broke entity state display in local language in custom button card

### ISSUE THREAD

**Issue by Opontios** [home-assistant/frontend#15039]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After the 2023.1.0 update the display of the entity state in local language reverted to default (English), no local language any more. I guess it has to do with specific changes in HA core that affected the custom bar card only, or at least I haven't noticed other cards to be affected. I reported the issue to the custom button card github, but no one is reading the issues chapter, I guess there's no support lately.

### Describe the behavior you expected

To display the state strings in local language, used by the UI, as it was before.

### Steps to reproduce the issue

1. Just check any entities state in a custom button card.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.1

### What was the last working version of Home Assistant Core?

2022.12.8

### In which browser are you experiencing the issue with?

Google Chrome 108.0.5359.125, FireFox Browser 108.0.2 , Yandex Browser 22.11.5.715

### Which operating system are you using to run this browser?

Windows 11

**Comment by piitaya** [comment]
Can you post some example or screenshot? It looks like a custom card issue.
