### ISSUE TITLE
Color Mismatch on History Graph Card

### ISSUE THREAD

**Issue by SolarCzar** [home-assistant/frontend#15032]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

History graph card was set for Red = Off, Green = On.  Now color is Yellow = On, Grey = Off without user interaction.

### Describe the behavior you expected

To stay as I had set it up and the card's default

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.1.1

### In which browser are you experiencing the issue with?

Safari 16.1

### Which operating system are you using to run this browser?

macOS Big Sur 11.7.1

**Comment by piitaya** [comment]
It's a change in `2022.12` release : https://www.home-assistant.io/blog/2022/12/07/release-202212/#shiny-new-state-colors
