### ISSUE TITLE
Light Groups Not Available in Scene Editor

### ISSUE THREAD

**Issue by ekobres** [home-assistant/frontend#15046]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I create a scene using the scene editor, light groups are not available as entities.

### Describe the behavior you expected

Light groups should be accessible as entities when creating scenes in the editor. Some searching forums suggests this has been broken and fixed in the past.

### Steps to reproduce the issue

1.Create a light group using the group helper with at least 2 lights.
2.Create a new scene.
3.Search for light group - it is not in the list.

Home Assistant 2023.1.1
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230104.0 - latest
...

### What version of Home Assistant Core has the issue?

2023.1.1

### In which browser are you experiencing the issue with?

Safari, Firefox (Latest)

### Which operating system are you using to run this browser?

macOS Monterey 12.6.2

### State of relevant entities

```txt
Here is an example of a group that does not show up in the scene editor:

min_color_temp_kelvin: 6493
max_color_temp_kelvin: 6493
min_mireds: 154
max_mireds: 154
supported_color_modes:
  - color_temp
  - hs
color_mode: hs
brightness: 174
hs_color:
  - 208.75
  - 94.25
rgb_color:
  - 14
  - 139
  - 255
xy_color:
  - 0.143
  - 0.155
entity_id:
  - light.game_room_windows
  - light.bar_windows
icon: mdi:led-strip-variant
friendly_name: Basement Windows
supported_features: 0
state: 'on'
```

**Comment by karwosts** [comment]
I had no problem just now adding a group of lights to a scene. If you try making some other groups of lights, maybe with different lights, do any of them work?

![image](https://user-images.githubusercontent.com/32912880/211228306-0fb014ce-5695-4179-8831-90edf86fa4b8.png)

![image](https://user-images.githubusercontent.com/32912880/211228426-87208c64-78a3-4f45-923d-101494127376.png)

**Comment by ekobres** [comment]
Okay, I'm an idiot. I totally missed that there was an entity list right under the device list.

Thanks!
