### ISSUE TITLE
{"message":"Invalid handler specified"} when want to edit options for switch device type change helper

### ISSUE THREAD

**Issue by Mr-Groch** [home-assistant/frontend#15044]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I want to try edit option for my light entities creted from switch device type change helper error message with "{"message":"Invalid handler specified"}" appears and options are not showed. Creating new helpers works.

### Describe the behavior you expected

Helper option window should appear

### Steps to reproduce the issue

1. Go to helpers
2. Create new helper of type switch device type change
3. Edit new helper entity and click on switch device type change options
4. Observer error message

### What version of Home Assistant Core has the issue?

2023.1.1

### What was the last working version of Home Assistant Core?

2022.12.1

### In which browser are you experiencing the issue with?

Google Chrome 108.0.5359.125

### Which operating system are you using to run this browser?

Windows 11

### Javascript errors shown in your browser console/inspector

```txt
styles.ts:372          POST https://hass.groch.cloud/api/config/config_entries/options/flow 404
I @ styles.ts:372
(anonimowa) @ styles.ts:372
callApi @ styles.ts:372
o @ ha-icon-picker.ts:218
createFlow @ ha-icon-picker.ts:218
value @ step-flow-progress.ts:49
c @ ha-svg-icon.ts:44
await in c (asynchronicznie)
(anonimowa) @ ha-svg-icon.ts:44
i @ typography.js:181
o @ ha-icon-picker.ts:218
d @ ha-icon-picker.ts:218
value @ entity-registry-settings.ts:882
handleEvent @ styles.ts:372
```

### Additional information

I'm using polish translation of HA fronend, and I have translated helper name by myself, it can be different in english HA frontend

**Comment by karwosts** [comment]
I reproduced this. The helper type in english is "Change device type of a switch".

![image](https://user-images.githubusercontent.com/32912880/211237494-2ea5587e-6e9b-44f6-a5ca-5e8aa5f9702f.png)

**Comment by stefanroelofs** [comment]
I have the same issue.

**Comment by maddox** [comment]
✋ confirmed, just ran into this.

I had originally set a Kasa smart `switch` to a `light`, and can't change it back to `switch`.

**Comment by csanner** [comment]
+1

**Comment by edgauthier** [comment]
Seeing this as well.

**Comment by cgallred** [comment]
Still repros on 2023.3.2.

**Comment by ssewell** [comment]
I can repro on Home Assistant 2023.3.6
- Supervisor 2023.03.2
- Operating System 9.5
- Frontend 20230309.1 - latest

**Comment by tjhorner** [comment]
I can reproduce here as well:

- Home Assistant 2023.4.0
- Supervisor 2023.04.0
- Operating System 9.5
- Frontend 20230405.0 - latest

**Comment by Zamily84** [comment]
I am experiencing the same issue on 2023.5.2

**Comment by rinyheuvelman** [comment]
Still experiencing the sam issue
<img width="1440" alt="Scherm­afbeelding 2023-12-19 om 14 08 03" src="https://github.com/home-assistant/frontend/assets/30094071/2d30e661-8149-49c1-aca2-5370e2a0065d">
