### ISSUE TITLE
Rename Gas on energy dashboard to "Heating"

### ISSUE THREAD

**Issue by thomwiggers** [home-assistant/frontend#15059]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Energy dashboard supports tracking heating sources, such as gas consumption, but also city heating sources. The latter are obviously not gas. 

### Describe the behavior you expected

Renaming "gas" to "heating" or something similar would be more accurate for those in houses that don't get gas but still get heating delivered in a non-electric way.

### Steps to reproduce the issue

![afbeelding](https://user-images.githubusercontent.com/974662/211349270-a1f0d796-ff3a-4950-8676-9e33e8585db7.png)

### What version of Home Assistant Core has the issue?

2023.1.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
