### ISSUE TITLE
Water heater entities have the current temperature displayed twice

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/frontend#15066]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I received a report from a user of one of my integrations that the `water_heater` entity is reporting the current temperature twice in an Entities card, once explicitly with a "Currently:" label and once alongside the target temperature.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/860888/211437298-08cf6507-f698-4a74-bc62-7aa437f33355.png">

It looks like it's been that way for a while, but I don't normally display the entity that way and haven't seen it.  It's not wrong, per se, but it looks weird and unnecessary to repeat that information (89.1 F in that image).

### Describe the behavior you expected

I would expect the current temperature to be displayed once in an Entities card, either next to the target (where, admittedly, it's not obvious what the number represents) or in the `Currently:` line, but not in both places.

### Steps to reproduce the issue

Add a `water_heater` entity to an `entities` card and observe that the current temperature is displayed in two different locations.

### What version of Home Assistant Core has the issue?

core-2023.1.2

### In which browser are you experiencing the issue with?

Google Chrome 108.0.5359.124

### Which operating system are you using to run this browser?

MacOS Ventura 13.2

### State of relevant entities

```txt
State:
water_heater.buzz_coffee: 88.7

Attributes:
min_temp: 188.6
max_temp: 212
coffee_heating_element_hours: 1492
current_temperature: 88.7
temperature: 201.9
icon: mdi:water-boiler
friendly_name: Buzz Coffee
supported_features: 1
```

**Comment by karwosts** [comment]
Looking at the demo water heater, it looks like the "state" of a water heater is expected to be the operation mode, not a temperature. Similar to how the state of a thermostat is "off" or "heat", not the current temperature. 

Maybe the water_heater is not providing the expected state?

![image](https://user-images.githubusercontent.com/32912880/211438736-bc9e556c-c0a2-49a5-b43f-3b789c173f20.png)

**Comment by piitaya** [comment]
Yes, the state must be the mode : https://developers.home-assistant.io/docs/core/entity/water-heater/
The integration should be fixed.

**Comment by rccoleman** [comment]
Oh, fair enough.  I did that on purpose, but I agree that it's not how `water_heater` is expected to behave.
