### ISSUE TITLE
Insteon Heat Pump Thermostat 2732-242

### ISSUE THREAD

**Issue by azoner2965** [home-assistant/frontend#15060]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a few of the Intseon Heat Pump thermostats and I am unable to change the set point from Home Assistant. Home Assistant is at version 20230104. The error I receive when I try to change the setpoint is: 
Logger: pyisy
Source: components/isy994/climate.py:201
First occurred: 7:32:05 AM (3 occurrences)
Last logged: 10:44:35 AM

Failed to set heat setpoint on 39 3A 66 1, it is not a thermostat node.

### Describe the behavior you expected

I would like to be able to use Home Assistant to change the setpoint.

### Steps to reproduce the issue

1. Change the setpoint from the Lovelace card.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.1.2

### In which browser are you experiencing the issue with?

Microsoft Edge

### Which operating system are you using to run this browser?

Windows 11

### Additional information

Logger: pyisy
Source: components/isy994/climate.py:201
First occurred: 7:32:05 AM (3 occurrences)
Last logged: 10:44:35 AM

Failed to set heat setpoint on 39 3A 66 1, it is not a thermostat node.

**Comment by frenck** [comment]
Hi there @azoner2965 👋 

It seems like you want to report an issue with an Home Assistant integration. However, you have submitted a bug report for the Home Assistant frontend instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
