### ISSUE TITLE
Map card: Visual editor is not supported for this configuration (person.someone)

### ISSUE THREAD

**Issue by alhemicar86** [home-assistant/frontend#15083]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hello,

I ran across a bug wtih Map card, if I try adding or removing entities (device_tracker. or person.) the card editor goes into code editor with warning "Visual editor is not supported for this configuration (person.someone)." When creating new map the card shows ok in Visual editor, until first change is made. It reacts the same way both to adding or removing the new entity. The card otherwise works fine (except for the error with centering of marker at the bottom). Editing in code provides functioning card for all entities.

### Describe the behavior you expected

Adding or removing entity in visual editor such as device_tracker.phone, or person.someone should update preview of the card and list of entites in visuall editor.

Instead card falls back to the code editor with "Visual editor is not supported for this configuration (person.someone).", but functions properly both in preview and dashboard.

### Steps to reproduce the issue

1. Create new Map card in dashboard and edit it. By default it shows two trackable devices (in my case, but there are more).
2. Adding or removing trackable device causes editor to instantly fall back to textual code editor.
3. Editor will remain in textual editor.
...

### What version of Home Assistant Core has the issue?

2023.1.2

### In which browser are you experiencing the issue with?

Google Chrome 108.0.5359.125

### Which operating system are you using to run this browser?

Windows 11 Version 10.0.22621 Build 22621

**Comment by karwosts** [comment]
Submitted PR for the fix.
