### ISSUE TITLE
Calendar pane locks up mobile app (iOS and android)

### ISSUE THREAD

**Issue by alecgt95** [home-assistant/frontend#15094]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When opening the calendar pane on the left side navigation, the iOS app completely freezes. It requires restarting the app and quickly navigating off the calendar page (in less than second) or the app will freeze again. This does not occur on the web browser version.

### Describe the behavior you expected

The calendar page to open showing all events for the month

### Steps to reproduce the issue

1. Open iOS app
2. Select Calendar on the left navigation
3.
...

### What version of Home Assistant Core has the issue?

core 2023.1.0 and earlier

### In which browser are you experiencing the issue with?

iOS 2022.10.1

### Which operating system are you using to run this browser?

iOS 16.2

**Comment by danielholm** [comment]
Same here. Unsure if before adding the local calendar integration.

**Comment by alecgt95** [comment]
I currently only have the google calendar integration loaded. Waiting on this issue to be fixed before using local.

**Comment by danielholm** [comment]
Tried it again by deactivating local calendar, but no change.

**Comment by phillprice** [comment]
Sadly I have the same, I use ical and local calendar and app is stuck.

**Comment by glautz** [comment]
I have the same issue. 

Last month it worked when showing January, but when I switched to February it would lock up if I didnt switch to day/week/list view before going to February. 

And now when it is February it just locks up as soon as I press calendar in the side bar since the default view is month. 

I have 65 events in Februarys month view and only had 27 events in January. 
All events are spread over 3 different calendars.

**Comment by AshtonKem** [comment]
Just had this happen to me on iOS and iPad. Only using the custom ICS calendar. Worked fine before adding the integration.

Hard reset does not fix the issue, presumably because when re-opening it returns to the same page and crashes again.

**Comment by AshtonKem** [comment]
**Temporary Workaround**

To unfreeze your companion apps.

1. Comment out all calendar configuration
2. Restart HA
3. Hard kill all companion apps
4. Re-open all companion apps, this should send you to the home page
5. (Optional) Re-enable calendar and restart HA again

This will leave your calendar working on the web and in any automations. It will still leave your companion apps vulnerable to freezing if you dare touch the calendar button again until a real fix is completed.

**Comment by cliffjao** [comment]
I'm running into this same issue on Android. Works on desktop but broken in mobile Chrome on Android and Android app. Still broken with 2022.2.5.

**Comment by AshtonKem** [comment]
Can no longer reproduce on 2023.1.7. Works on both iOS and in my XCode Debugger.

**Comment by VPsych** [comment]
Also confirming the same issue. 

Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

As an easier workaround if your app gets stuck. Use the Open in Home Assistant button on any of the docs. For example the EspHome integrations page. It should prompt you to open it up in the app. If the app still doesn’t load a force close and reopen should load up the corresponding page. 

https://www.home-assistant.io/integrations/esphome/

**Comment by cliffjao** [comment]
FWIW: This issue only happens in the mobile view. Under Mobile Chrome, it works if I have it Use Desktop version

**Comment by davidjac** [comment]
For me locks up in Android App (latest builds) but fine in chrome Android browser.

**Comment by oneofthemany** [comment]
Same here on Android. Completely locks the app and won't recover without rebooting the container.

**Comment by PapaMater** [comment]
Any chance this will see some attention in the near future? This has been an issue for me since the inception of localcalendar.

**Comment by NitriKx** [comment]
On iOS I've managed to leave the calendar view by spamming in the top left corner during the app loading (after having killing it)

**Comment by ikeurb** [comment]
Yes, the iOS app locks up when viewing the calendar view. Confirmed that spamming the top left corner during app load-in allowed me to select another view.

**Comment by oneofthemany** [comment]
> Yes, the iOS app locks up when viewing the calendar view. Confirmed that spamming the top left corner during app load-in allowed me to select another view.

You can't spam in android, only force quit.

It also seems to self right itself when an app update happens but then randomly breaks

**Comment by schale01** [comment]
Confirmed this is occurring in 2023.5.2
Running android companion app
Frontend 20230503.3 latest
HA OS 10.1
Supervisor 2023.04.1

**Comment by oneofthemany** [comment]
is anyone from HA going to take this issue on

it is easily reproduce-able:

1. Open chrome browser
2. Enable Developer options
3. set screen size to mobile
4. select calendar from the side panel dashboards
5. hit a few buttons
6. crash...

**Comment by oneofthemany** [comment]
@alecgt95 can you change the title header so that we umbrella iOS and Android here as it affects both ecosystems

**Comment by Ewoodster** [comment]
Still the same issue for months and no one takes care. The Calendar function is vital…

**Comment by drizztguen77** [comment]
I'm also receiving this same issue. HA remembered where I was when I killed the app so I couldn't even kill and restart HA. I had to reboot my phone to be able to get back in to  the app.

**Comment by allenporter** [comment]
I initially was unable to reproduce this.

Here are a couple scenarios i've tried:
- Home Assistant Companion App `2023.3.0-full` on Android
- Home Assistant Web on Chrome Android 114.0.5735.52 Androird 13.
- Desktop Chrome on Mac with with a Screen Size set to Mobile. On Chrome `113.0.5672.126 `

I've tried across a few different versions of Home Assistant:
- Core 2023.5.4, Fronted 20230503.3
- Latest dev builds of both from head


However, then I was finally able to reproduce this by pressing a lot more buttons before scrolling away. In all of the initial tests I didn't see the issue since things appeared to work just fine.  I'll take a closer look.

**Comment by allenporter** [comment]
I was able to attach to a remote debugger in chrome with the help of some other devs. 

It seems like something is hanging the main thread, and the stack trace appears to be inside of [full-calendar](https://github.com/fullcalendar/fullcalendar). Something is getting stuck when rendering:

```
renderInnerContent$1 (internal-common.js:7067)
render (internal-common.js:2416)
M (index.js:197)
H (children.js:137)
M (index.js:230)
H (children.js:137)
M (index.js:230)
H (children.js:137)
O (index.js:436)
M (index.js:264)
H (children.js:137)
M (index.js:230)
H (children.js:137)
M (index.js:230)
H (children.js:137)
M (index.js:230)
H (children.js:137)
M (index.js:230)
H (children.js:137)
O (index.js:436)
M (index.js:264)
H (children.js:137)
M (index.js:230)
H (children.js:137)
M (index.js:230)
H (children.js:137)
O (index.js:436)
M (index.js:264)
H (children.js:137)
O (index.js:436)
M (index.js:264)
H (children.js:137)
O (index.js:436)
M (index.js:264)
H (children.js:137)
M (index.js:230)
H (children.js:137)
M (index.js:230)
H (children.js:137)
M (index.js:230)
H (children.js:137)
M (index.js:230)
H (children.js:137)
O (index.js:436)
M (index.js:264)
H (children.js:137)
M (index.js:230)
$ (component.js:133)
flushSync (internal-common.js:2216)
(anonymous) (index.js:2011)
drained (internal-common.js:136)
tryDrain (internal-common.js:118)
resume (internal-common.js:107)
batchRendering (index.js:2064)
changeView (internal-common.js:4759)
value (ha-full-calendar.ts:344)
handleEvent (lit-html.ts:2003)
fireEvent (fire_event.ts:76)
value (ha-button-toggle-group.ts:63)
handleEvent (lit-html.ts:2003)

```

**Comment by lionslair** [comment]
Same issue and cause on Android. Always from left menu. Most time it doesn't even load the items just shows an empty calendar

**Comment by x-Felix** [comment]
This issue may relate to iOS / iPadOS browser as well. If not using the Home Assistant mobile app, just access through mobile browser (tried Safari, Bing, Chrome), the calendar page also hangs. 
However, I have no issue to view the calendar page when using Brave browser on iOS. Probably because Brave browser won't load some problematic js.

**Comment by glasoline** [comment]
Same issue here on Android. Empty calender, app freezes.

**Comment by bsleep** [comment]
I'm having this same issue on iOS 16.5 using Home Assistant Companion 2023.4 (2023.460) and Home Assistant version 2023.6.1. When trying to load the calendar view, the app freezes and I can't see any of my local calendar items. I can load the calendar on my laptop using Firefox (only browser I have tried, I'm sure other browsers work).

**Comment by zacolly** [comment]
Same Issue
- works fine on PC browser
- hangs on android using app or browser (App 2023.6.0)
- 2 x local calendars
- 4 x google calendars
- hangs even if i remove all calendars and leave blank

**Comment by allenporter** [comment]
I'm still able to reproduce this using the remote view (so no additional bug reports needed, i think we have enough data there).

However, I am not sure how to fix this issue yet.

**Comment by miketarg** [comment]
I have the same issue. I have 21 calendars. Works fine on pc but the app just locks up.

**Comment by allenporter** [comment]
We currently have enough reports of the issue, just need to find the solution. (No additional reports are needed)

**Comment by ArcaEge** [comment]
It seems that the issue is caused by themes - I've tested Google Theme, Catppuccin, Caule and Graphite - they all cause a hang, every time.

**Comment by broyuken** [comment]
I’m using the default theme and it happens

**Comment by ArcaEge** [comment]
I've cleared local storage, cache and cookies and it seems that the issue has become harder to comprehend. Here's a quick summary:
 - After local storage (+ cache, cookies etc.) cleared the calendar locks up, as soon as page opened/window resized to a smaller size.
 - Then if you change the theme to something else, it doesn't hang straight away but as soon as you toggle one of the checkboxes it locks up. The rest of the UI is still usable.
 - If you go back to the default theme after switching to another theme, it has the same exact behaviour as the third party theme (usable except checkboxes)

**Comment by miketarg** [comment]
I have never used themes.

I am using default theme and it happens.

**Comment by oneofthemany** [comment]
It's certainly not themes

**Comment by allenporter** [comment]
No fixes on my end.

**Comment by oneofthemany** [comment]
> No fixes on my end.

Any idea how it can mysteriously start working again?

**Comment by huntsman95** [comment]
> > No fixes on my end.
> 
> Any idea how it can mysteriously start working again?
> 
> What I have at the moment is functionality in the current month but the second I move to another month I get the crash

Do you have appointments that span across multiple days in those months? I noticed it locks up for me only in month view and it stops rendering and freezes around appointments that span overnight. Every other calendar view works fine if you keep hitting the right or left button through different days/weeks/etc.

**Comment by huntsman95** [comment]
You can reproduce this issue with Firefox dev-tools (F12) on desktop by placing it into "Responsive Design Mode" then going into the Calendar pane. It only happens when the screen width is small enough to remove the sidebar entirely which also appears to switch how the calendar renders events (dots for events vs. a dot with the event title to the right of it as is shown on desktop). If you adjust the width of the window in "Responsive Design Mode" to be wide enough to accommodate the left-hand side-bar, it causes the rendering mode for full-calendar to change back to the default and then there is no issue.

**Comment by allenporter** [comment]
I was also able to reproduce and get the stack trace but it's pretty unreadable and I'm not sure who's to find the root cause. (Not a real web dev)

**Comment by oneofthemany** [comment]
> > > No fixes on my end.
> > 
> > Any idea how it can mysteriously start working again?
> > 
> > What I have at the moment is functionality in the current month but the second I move to another month I get the crash
> 
> Do you have appointments that span across multiple days in those months? I noticed it locks up for me only in month view and it stops rendering and freezes around appointments that span overnight. Every other calendar view works fine if you keep hitting the right or left button through different days/weeks/etc.

I have appts that span multiple days on both months but I crash on June and not in July

**Comment by GeoViljoen** [comment]
Same problem with the latest Android app 2023.7.5.

**Comment by oneofthemany** [comment]
I have noticed that in my desktop browser in June I have a notice saying that a certain calendar no longer exists and when I move to this month on my mobile the app crashes and doesn't show any error

Could this be part of the problem?

**Comment by marc-gist** [comment]
On desktop, with Chrome, Brave, Firefox browsers, panels with calendars on them crash.  Sometimes within seconds, sometimes it takes an hour or so.  I like to have a calendar always open on one of my displays.  This started happening with 2023.7.x

**Comment by Someguitarist** [comment]
I know it's mentioned that you've got enough reports, but same thing here with the newest versions on both iOs and Android.  

This *really* needs to be looked at, more than Year of Voice or anything else.  It's a core function with a separate tab that completely locks up the app.  On iOs in particular it's difficult to recover since you can't just force-close it.  This is a huge factor for the non-technical people in families of people that use HA.  At the very least, include an easy way to remove it from the left hand tab until this can get resolved.

**Comment by Menz01** [comment]
I have something strange to add to this. My Google calendar integration works just fine. I can click the calendar on the left navigation and my calendar opens without issue

Here is the strange part, today I add the "national day calendar" to my personal Google calendar via a .ics link on my desktop computer. I went to HA on my PC and reloaded the integration and the new calendar added. I clicked the link in the navigation and it opens fine. If I now go to my pixel 7 and open the companion app and click the calendar on the left navigation it locks up the app and I have to force close. If I remove the added caledar and reload the integration my companion app works again too

**Comment by lionslair** [comment]
> I have something strange to add to this. My Google calendar integration works just fine. I can click the calendar on the left navigation and my calendar opens without issue
> 
> Here is the strange part, today I add the "national day calendar" to my personal Google calendar via a .ics link on my desktop computer. I went to HA on my PC and reloaded the integration and the new calendar added. I clicked the link in the navigation and it opens fine. If I now go to my pixel 7 and open the companion app and click the calendar on the left navigation it locks up the app and I have to force close. If I remove the added caledar and reload the integration my companion app works again too

Have you got another calendar or feed. So you went from one to two items. Or this is just one that came from a manual import?

**Comment by curtash** [comment]
For those on iOS wanting to get back in after a crash. 

1) Create a HA iOS widget with a link to any other dashboard.
2) Force close HA app
3) Click the widget .

**Comment by Someguitarist** [comment]
I just had my issue resolved accidentally, but may be useful to others; apparently the issue has to deal with long calendars, or ones with multiple entries spanning several months.  In my case, my 115h automower was struck by lightning.  I was currently using a HACS integration to incorporate it into Home Assistant, and it looks like it generates a 'Calendar' of all of the start and stop dates.  When the mower died and the integration was removed along with it's calendar, calendar now works flawlessly on both IOS and Android HA apps.

**Comment by oneofthemany** [comment]
> I have noticed that in my desktop browser in June I have a notice saying that a certain calendar no longer exists and when I move to this month on my mobile the app crashes and doesn't show any error
> 
> Could this be part of the problem?

@allenporter:  I am thinking this potentially is one of the issues causing the crash.

**Exploration**

In May I removed a certain calendar from my Google account, as it was no longer in use and was not able to pull any data.

At present I can move freely from now to any future calendar month, but the app locks up when I try and go to May where I deleted that old calendar.

Spanning for me is certainly not the issue as I have events that span across months this month and in future month: I have even tried to crash by means of event creation and have no issue at all with event span.

https://github.com/home-assistant/frontend/assets/44924639/f135981d-d50d-4322-9c96-b649d1198d10

**Comment by allenporter** [comment]
I spent a few hours diagnosing this today and there seems to be a loop inside the day grid full calendar component. I am not that familiar with react, but it seems like it is violating one of the rules by updating state while `componentDidUpdate`.

The code says:
https://github.com/fullcalendar/fullcalendar/blob/7481ac9c119948640f3322ad31c9af76bb50d588/packages/daygrid/src/TableRow.tsx#L359
```
        // HACK to prevent oscillations of events being shown/hidden from max-event-rows
        // Essentially, once you compute an element's height, never null-out.
```

It may go away when playing with `dayMaxEventRows` but i'm not sure yet.

(As i mentioned before we have plenty of reports and know where the problem is with the stack trace above)

**Comment by allenporter** [comment]
Seems possibly related to these issues:
- https://github.com/fullcalendar/fullcalendar/issues/7146 which 
- https://github.com/fullcalendar/fullcalendar/issues/7116

Removing `dayMaxEventRows` prevents the crash, but makes it so that unlimited events are shown on desktop requiring scroll.

**Comment by allenporter** [comment]
I tried to reproduce this with a full calendar minimal example and was not able to.

I've narrowed this down to be tickled by some home assistant CSS that applies to mobile browsers:
```
        :host([narrow])
          .fc-dayGridMonth-view
          .fc-daygrid-dot-event
          .fc-event-time,
        :host([narrow])
          .fc-dayGridMonth-view
          .fc-daygrid-dot-event
          .fc-event-title,
        :host([narrow]) .fc-dayGridMonth-view .fc-daygrid-day-bottom {
          display: none;
        }
```

I think what this i sdoing is making the event name and event time disappear which messes with some of the rendering logic in full calendar which causes oscillation.
