### ISSUE TITLE
Sensors incorrectly reported/categorised as diagnostic. 

### ISSUE THREAD

**Issue by kiwizznz** [home-assistant/frontend#15098]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have some switches (via zigbee2mqtt) which report power use (watts/amps/voltage) but these sensors get categorized as 'diagnostic' so don't show up as expected. Here is one of the entities that is affected:

`state_class: measurement
current_left: 0
device:
  applicationVersion: 74
  dateCode: ''
  friendlyName: Deck Power Plug
  hardwareVersion: 1
  ieeeAddr: '0x84fd27fffedaf6db'
  manufacturerID: 4098
  manufacturerName: _TZ3210_7jnk7l3k
  model: SPP02GIP
  networkAddress: 35099
  powerSource: Mains (single phase)
  stackVersion: 0
  type: Router
  zclVersion: 3
energy: 70.49
last_seen: '2023-01-13T00:41:49.166Z'
linkquality: 65
power_left: 0
state_left: 'OFF'
state_right: 'ON'
voltage_left: 245
unit_of_measurement: W
device_class: power
friendly_name: Deck Power Plug power left`

### Describe the behavior you expected

Sensors for wattage, amps, voltage etc should show up in the 'sensor' section for the entity and not 'diagnostic'

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/35387790/212211314-e796a79b-bea7-417a-8514-39235b0c9909.png)

### What version of Home Assistant Core has the issue?

2023.1.2

### What was the last working version of Home Assistant Core?

2023.1.2

### State of relevant entities

```txt
`state_class: measurement
current_left: 0
device:
  applicationVersion: 74
  dateCode: ''
  friendlyName: Deck Power Plug
  hardwareVersion: 1
  ieeeAddr: '0x84fd27fffedaf6db'
  manufacturerID: 4098
  manufacturerName: _TZ3210_7jnk7l3k
  model: SPP02GIP
  networkAddress: 35099
  powerSource: Mains (single phase)
  stackVersion: 0
  type: Router
  zclVersion: 3
energy: 70.49
last_seen: '2023-01-13T00:41:49.166Z'
linkquality: 65
power_left: 0
state_left: 'OFF'
state_right: 'ON'
voltage_left: 245
unit_of_measurement: W
device_class: power
friendly_name: Deck Power Plug power left`
```

### Additional information

Home Assistant 2023.1.2
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230104.0 - latest

**Comment by elupus** [comment]
This is by design. We consider that diagnostic. Nothing stopping you from adding them to a dashboard anyway. We just don't want to auto add all possible values to auto generated dashboards.
