### ISSUE TITLE
Solar Consumed not displayed in week or month but is for daily graphs

### ISSUE THREAD

**Issue by rubylou1** [home-assistant/frontend#15107]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When looking at the Energy Dashboard in Day view I can see solar consumed
![Daily](https://user-images.githubusercontent.com/122701571/212498295-74edd31e-e079-470e-9c86-7b3db1fd8792.png)

When looking at the Energy Dashboard in Week/Month View it does not show the solar consumed even though solar has been generated and used each day.
![image](https://user-images.githubusercontent.com/122701571/212498287-4efcdc26-570b-426f-a544-1ee1d3276934.png)

### Describe the behavior you expected

I would expect to see the solar consumed in the week view and the month view

### Steps to reproduce the issue

Click on Day View, Week View, Month View

### What version of Home Assistant Core has the issue?

2023.1.4

### In which browser are you experiencing the issue with?

Google Chrome 109.0.5414.75 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 22H2

**Comment by ChristophCaina** [comment]
Hi, I cannot confirm this - but MAYBE the values for your self-consumed solar production are too small to be shown in the graph?
What Info do you have when you hover with the mouse over one of the graphs?
![image](https://user-images.githubusercontent.com/26391061/217447935-25ff28e8-fe5a-4aa7-8faa-e7b8e7ff0258.png)
![image](https://user-images.githubusercontent.com/26391061/217448052-029cb978-465f-4ec0-8028-02f8ee3e72bf.png)
