### ISSUE TITLE
Wrong format in sensor

### ISSUE THREAD

**Issue by Chrulf** [home-assistant/frontend#15103]
### The problem

My sensors are showing me travel time in clock format (15:00) instead of normal minutes (15 min). This suddenly happened a few months ago after it worked fine, but I haven't got it working since.

![image](https://user-images.githubusercontent.com/109205257/211826159-398d9a61-efb1-42db-be1e-22cbc6b9f2c0.png)

### What version of Home Assistant Core has the issue?

2023.1.2

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Waze Travel Time

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/waze_travel_time

**Comment by karwosts** [comment]
I also find this unintuitive for other duration measurements (like from history_stats). 

Sub-minute durations just show as a number, with no context. Here is 36 seconds. But in the dashboard, you would be left wondering, "36 what?"

![image](https://user-images.githubusercontent.com/32912880/212360367-880bec1d-9c51-46e7-9e56-59b0b1817da1.png)

6 minutes - shows as mm:ss, but it's not immediately clear to the user if this is mm:ss, or hh:mm

![image](https://user-images.githubusercontent.com/32912880/212360468-c4ff3515-6191-4475-88f8-a7fc95e8ff02.png)

2 hours - greater than 1 hour, probably more intuitive. 

![image](https://user-images.githubusercontent.com/32912880/212360523-bb1f1d5d-a209-4f0a-9bdd-39a7e9f3f520.png)

**Comment by eifinger** [comment]
Related: https://github.com/home-assistant/core/issues/86695

**Comment by e3e6** [comment]
This issue might be also reproduces via template sensors

`template:
  - sensor:
      - name: "Duration display issue OK"
        state_class: measurement
        unit_of_measurement: "min"
        state: "15"
      - name: "Duration display issue FAIL"
        state_class: measurement
        device_class: duration
        unit_of_measurement: "min"
        state: "10"` 

<img width="899" alt="Screenshot 2023-04-20 at 15 00 34" src="https://user-images.githubusercontent.com/841910/233359904-90eff1a5-8945-4ec0-a1e5-dc7ea3543c33.png">
<img width="539" alt="Screenshot 2023-04-20 at 15 00 27" src="https://user-images.githubusercontent.com/841910/233359911-6f8f9d30-f55a-49ce-a5c1-c154cc3beab5.png">
<img width="540" alt="Screenshot 2023-04-20 at 15 00 17" src="https://user-images.githubusercontent.com/841910/233359916-c61c38ca-ea9b-4160-925c-62f14036ae66.png">

**Comment by igorsantos07** [comment]
Sad to see so many bugs being closed as stale simply for not having been worked on. Reporters have to repeatedly comment to not allow bugs to get closed.

This seem to have been reported multiple times, such as in the forum, at #18151 and #18561.

**Comment by thecobra666** [comment]
This is still an issue today... A new item is set to hours and minutes instead of minutes..

**Comment by igorsantos07** [comment]
@thecobra666 comment on #18151. If they hardly interact with open issues, imagine these that got forcibly closed.

**Comment by retrography** [comment]
#18151 is unfortunately deleted, and this issue still exists…

**Comment by thecobra666** [comment]
Correct, this issue is still there. Wonder why this isn't picked up.
