### ISSUE TITLE
Graph of sensor state is severely lagging behind

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/frontend#15106]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When loading a graph of a sensor (the first time this day), I often see that the graph isn't representing the newest values, but looks like it's 5–10 Minutes lagging behind.

Example:

![Screenshot from 2023-01-14 18-56-23](https://user-images.githubusercontent.com/614929/212488169-ef6fb142-df55-4302-884f-7c5ff2659ddc.png)

### Describe the behavior you expected

Because the loading/generating of this graphs takes a second or two I think it's generated in real time. So there seems to be a problem with the displayed timeframe here (I think).

The graph should in any case show the latest value of this sensor, when it's generated a second or two after the new sensor value was recorded.

### Steps to reproduce the issue

1. Having a sensor value rapidly change
2. Opening the graph for the sensor value a minute after a value gets recorded
3. Observe the issue

### What version of Home Assistant Core has the issue?

2023.1.1

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Firefox 108.0.2 / Chromium 109.0.5414.74

### Which operating system are you using to run this browser?

Arch Linux

**Comment by ildar170975** [comment]
I wonder how not-precise statistics graph may be not lagged...
Surely it will be inaccurate. This is not a normal history-graph, this is just a statistics.
The right question is "WTH a non-precise statistics graph is displayed instead of a normal history-graph????"
