### ISSUE TITLE
Error rendering graph in Automation

### ISSUE THREAD

**Issue by MityaDVG** [home-assistant/frontend#15125]
### Describe the issue you are experiencing

This is what it shows me in the automation trace:
Error rendering graph. Please download trace and share with the developers.
[trace automation.gaz_utechka 2023-01-15T15_38_30.929957+00_00.json.txt](https://github.com/home-assistant/supervisor/files/10421338/trace.automation.gaz_utechka.2023-01-15T15_38_30.929957%2B00_00.json.txt)

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Steps to reproduce the issue

1. Fix trace display
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
No response
```

### System Health information

No response

**Comment by MityaDVG** [comment]
The problem hasn't been resolved yet. I have the latest versions. Attached is the latest trace.
[trace automation.gaz_utechka 2023-04-11T11_35_29.778932+00_00.json.txt](https://github.com/home-assistant/frontend/files/11260275/trace.automation.gaz_utechka.2023-04-11T11_35_29.778932%2B00_00.json.txt)

**Comment by copacetic82** [comment]
Same problem for me, see attached trace. I have the latest HA version installed.
![image](https://user-images.githubusercontent.com/45660618/232768450-27309eef-ce15-4088-a502-5fb9c7a2fb15.png)
[trace automation.evcc_set_phases 2023-04-18T11_28_53.006845+00_00.json.txt](https://github.com/home-assistant/frontend/files/11261367/trace.automation.evcc_set_phases.2023-04-18T11_28_53.006845%2B00_00.json.txt)
