### ISSUE TITLE
Calendar card only shows "Day" initial view

### ISSUE THREAD

**Issue by FiByr** [home-assistant/frontend#15144]
### The problem

When I add a calender card to my dashboard even though I selected month view after it's been added it will only show the day with no option to select the other views

![cal1](https://user-images.githubusercontent.com/118131429/213481831-7c89546f-833f-4005-8862-c6894a33eb50.jpg)
![cal2](https://user-images.githubusercontent.com/118131429/213482408-a4ec3730-82b5-4bb5-9d09-2f508922b94a.jpg)

### What version of Home Assistant Core has the issue?

 Home Assistant 2023.1.5 Supervisor 2022.12.1 Operating System 9.4 Frontend 20230110.0 - latest 

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

local_calendar

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/local_calendar/

**Comment by allenporter** [comment]
Perhaps we can give this issue a new title like: Calendar card only shows "Day" initial view
(I don't have permission)

**Comment by FiByr** [comment]
Done
