### ISSUE TITLE
Unable to Cast: Error: Cannot show Lovelace because we're not connected to the same Home Assistant instance

### ISSUE THREAD

**Issue by michaelrobgrove** [home-assistant/frontend#15147]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Whenever I try to cast from my phone, computer, tablet, I get a screen that shows HA and then shows Connected but when I chose the dashboard, i get "Error: Cannot show Lovelace because we're not connected to the same Home Assistant instance". It used to work. I have rebooted, cleared cache, tried multiple devices, tried Chrome and Firefox. 

### Describe the behavior you expected

It should have loaded te dashboard.

### Steps to reproduce the issue

1. Open https://cast.home-assistant.io/
2. Enter my HA address ( have tried nabu casa address, Cloudflared address and DuckDNS address)
3. Clicked Cast
4. Clicked Dashboard
5. Error shows
...

### What version of Home Assistant Core has the issue?

core 2023.1.6

### In which browser are you experiencing the issue with?

Chrome Version 109.0.5414.94, Firefox 109.1.1

### Which operating system are you using to run this browser?

ChromeOS, Android 12, FireOS

**Comment by millardoj1** [comment]
i have this as well
