### ISSUE TITLE
Apple TV 4K Volume Down doesn't work

### ISSUE THREAD

**Issue by lprawita** [home-assistant/frontend#15163]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

It's funny when my Apple TV 4K (configured automatically from Home Assistant) cannot decrease the volume on my TV. It can increase volume from the HA UI, but not decrease the volume.
My Apple TV 4K is connected wirelessly to my access point and the Apple TV 4K is directly connected to my Philips TV via HDMI.

Please advise!

### Describe the behavior you expected

I am wondering I should upgrade my Apple TV 4K to the latest generation.

### Steps to reproduce the issue

1. 
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.1.7

**Comment by jasonkelly214** [comment]
I'm also having this issue

**Comment by martin18d** [comment]
See this post:
https://community.home-assistant.io/t/appletv-remote-working-except-with-volume-up-volume-down/394267

Looks like Apple stopped supporting CEC is the short answer (unless using the physical remote).
