### ISSUE TITLE
All zones are same color on device_tracker and person entities in history graphs

### ISSUE THREAD

**Issue by Sese-Schneider** [home-assistant/frontend#15165]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

All zones are the same color on 
- device_tracker
- person entities

in the history section.

![image](https://user-images.githubusercontent.com/14337484/214100794-79eb8736-5923-438e-9340-b682f4fbb23c.png)

According to @piitaya this should be fixed in `2022.12.1`(https://github.com/home-assistant/frontend/issues/14661#issuecomment-1344348127), but I still can reproduce the issue on my setup.

### Describe the behavior you expected

Home, other zones and away should have different colors.

### Steps to reproduce the issue

Unknown. I can provide any logs requested.

### What version of Home Assistant Core has the issue?

2023.1.7

### What was the last working version of Home Assistant Core?

2022.11.X

### In which browser are you experiencing the issue with?

Google Chrome 109.0.5414.75

### Which operating system are you using to run this browser?

Windows 11 22H2

**Comment by piitaya** [comment]
Do you have the issue with the default HA theme ? I unable to reproduce it.

**Comment by Sese-Schneider** [comment]
@piitaya I appologize, working with default -> it looks like a theme issue to me.
