### ISSUE TITLE
Allow to Airplay Dashboards similar to chromecasting them to TVs

### ISSUE THREAD

**Issue by kaystrobach** [home-assistant/frontend#15167]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

As a user I would like to cast a lovelace view to a TV. It does support airplay, but no chrome cast API.

### Describe the behavior you expected

Allow to use airplay to display lovelace views on supported devices 

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

latest stable -2023.01

### What was the last working version of Home Assistant Core?

2023.01

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

Mac and Linux

**Comment by kaystrobach** [comment]
Still an open feature request

**Comment by kaystrobach** [comment]
Still a wish. Thnk you

**Comment by milesroper** [comment]
I’d support this to

**Comment by karwosts** [comment]
I'm going to go ahead and close this issue, as this is a large feature request. and not an appropriate topic for Issues, which is for bugs only. 

Even accepting that this is a feature request, I'm not sure if frontend is the right repository for it. Google cast of dashboards is handled by the `Cast` integration in home assistant core, if something similar was to exist for Airplay it would probably need core support as well. 

For now I'll redirect you to add your `+1`s to this feature request topic, which I believe aligns with what this is asking for. 

https://community.home-assistant.io/t/wth-why-cant-we-stream-to-airplay-only-to-privacy-sensitive-googles-chromecast/472026
