### ISSUE TITLE
Script editor GUI asks to save changes in read only mode

### ISSUE THREAD

**Issue by TheFes** [home-assistant/frontend#15178]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have all my scripts in YAML, in separate files, so I don't use the GUI to create scripts.
So when I click on a script in the list under Settings > Scripts it is opened in a read only mode.
However, if i then leave the screen, for example by pressing the traces button, it asks for confirmation, stating unsaved changes will be lost.
There is also a Save button, if I press it first, I don't get the popup.

For automations this popup doesn't appear (and there is no save button)
![image](https://user-images.githubusercontent.com/28803438/214292588-322885a6-79b3-40ba-b0cd-d2e2f1419d3e.png)

### Describe the behavior you expected

No popup, no save button

### Steps to reproduce the issue

1. Go to settings > automations & scenes > scripts and open a script which is stored outside scripts.yaml
2. Press the traces button

### What version of Home Assistant Core has the issue?

2023.1.7

### In which browser are you experiencing the issue with?

Google Chrome 109.0.5414.75 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 Pro

**Comment by TheFes** [comment]
issue still persists.

**Comment by karwosts** [comment]
Does this happen with every script, or just some? I made a trivial read-only script but it doesn't show me the save button or ask for confirmation to leave. I suspect there's something specific to your yaml file that's making it think its dirty. 

Do you mind to share an example of a script that has this issue?

**Comment by TheFes** [comment]
No, not every script, let me see if I can find some common thing for when it happens
