### ISSUE TITLE
Battery sorting not right

### ISSUE THREAD

**Issue by duhow** [home-assistant/frontend#15182]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On **Zigbee > List devices**:

Battery sorting not right - seems that it is sorting by "text" instead of "numeric value".

![image](https://user-images.githubusercontent.com/1145001/214318442-f3123216-666c-4602-a4d1-8a52f5e20eeb.png)

### Describe the behavior you expected

Sorting is properly done 100 > 80 > 77

### Steps to reproduce the issue

- List Zigbee Devices
- Sort by Battery

### What version of Home Assistant Core has the issue?

2023.1.6

### In which browser are you experiencing the issue with?

Brave 1.46.144  Chromium: 108.0.5359.128 (Build oficial)  (64 bits)

### Which operating system are you using to run this browser?

Debian 11

**Comment by karwosts** [comment]
This has been fixed, will be released in 2023.02
