### ISSUE TITLE
Automations BROKEN Front End incorrect handling of device/service state option capitalised/uncapitalised

### ISSUE THREAD

**Issue by confuserated** [home-assistant/frontend#15201]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This problem occurs on **Safari** and **Chrome** on MacOS for me.

I have noticed this problem for the last 4 months or so and have been updating regularly to see if it gets fixed, but it has not. I can't quite believe that no-one else is seeing this issue as it basically stops automations from working properly.

What happens is, I create a new Automation, in this example one to test the state of the heating scheduler after restart as a restart basically stops the climate from keeping the previous state, and I put in a condition to test the state of some service or  switch or device, then I select the condition state I want from the list of available ones for that entity and then continue onto the next task.

Unfortunately, when testing the new automation, the trace shows that the automation never completes because the first letter of the state should be capitalised (as can be seen in the pull-down list of available states) but that the returned state from the condition has no capitalised entry.

What is happening here is very confusing since I can see from editing the automation that the states' first letter is capitalised even though the trace says it is not.

Below is my configuration in yaml, a screenshot of the gui and the output text from the trace:

Trace:

Executed: 25 January 2023 at 15:12:22
Result:
result: false
entity_id/0
Executed: 25 January 2023 at 15:12:22
Result:
result: false
state: 'on'
wanted_state: 'On'

In yaml edit mode:

alias: Startup Heating reset
description: Reset the scheduler after system restart
trigger:
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: switch.schedule_79b82e
    state: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 0
action:
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.schedule_79b82e
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.schedule_79b82e
mode: single

PLEASE IGNORE THE WAY THE TEXT IS FORMATTED IN THE EDIT ABOVE, IT IS NOT SHOWING CORRECTLY IN THE BROWSER BUT THE SYNTAX IS CORRECT IN THE YAML, THAT IS NOT THE PROBLEM.

### Describe the behavior you expected

I would expect the automation to run successfully after checking the states I have set.

### Steps to reproduce the issue

1.
2.
3.
...
I have put the steps to reproduce in the original error description. I happens consistently with every automation I add that has a condition to check

### What version of Home Assistant Core has the issue?

Home Assistant 2023.1.7

### In which browser are you experiencing the issue with?

Safari  Version 16.1 (18614.2.9.1.12)

### Which operating system are you using to run this browser?

macOS Ventura 13.0.1

### State of relevant entities

```txt
Home Assistant 2023.1.7
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230110.0 - latest
```

### Additional information

<img width="1228" alt="Screenshot 2023-01-25 at 15 15 46" src="https://user-images.githubusercontent.com/90400964/214608787-90273e41-043a-4149-ad42-047a88f0e016.png">

**Comment by confuserated** [comment]
Is no-one else seeing this problem? I have it on all automations where the state can be selected from a pull down menu.

**Comment by karwosts** [comment]
I have not been seeing it, but I'm willing to look a little closer. 

I do notice that the state combobox always seems to capitalize the first letter of the states. However, if you flip over to the yaml, they are always saved as lowercase in the yaml, even though they are displayed as uppercase in the combobox. 

Does your yaml carry over the uppercase first letter of the state? I see that in what you posted it does seem like it's looking for lowercase:

```
condition: state
entity_id: switch.schedule_79b82e
state: "on"
for:
```

If you were to switch to yaml editing mode, and make a trivial change and save it, does the problem persist? It's odd that it's showing as lowercase in the yaml for you, but your trace seems to be looking for uppercase. 

Do you have any kind of mods or such installed that might interfere with the ui (browser mod, card mod, anything like that?)

**Comment by confuserated** [comment]
Firstly, if I edit the automation in YAML mode can change the switch state to "On" from "on" the change persists, if I do it in Visual mode the change does not persist.

I think you may be seeing the same problems as me from your example.

The problem persists in all automations that look for a state change on any entity, I use the same method looking for a boolean state change on another automation and it fails in the same way.

Lastly, I do have carmon and browser mod installed, should I try this with them uninstalled?

Thanks and regards

**Comment by karwosts** [comment]
> I think you may be seeing the same problems as me from your example.

I don't have a problem though, everything is working as expected.

> Lastly, I do have cardmod and browser mod installed, should I try this with them uninstalled?

I think it would be a reasonable idea to try removing or somehow turning them off to see if it makes a difference. I have no idea of what ways they can mess with the page.

**Comment by confuserated** [comment]
Hmm, so I uninstalled card-mod and the problem has gone away.

Interesting, I guess I should close this thread?

**Comment by karwosts** [comment]
I suppose you probably won't get any more support here in this repository, so yeah maybe I would close it out. 

I would suggest reinstall and confirm the issue, and then maybe find the card-mod repository and report it there. Make sure you have the latest versions of all your plugins too, sometimes if they get old and aren't updated, they might lose compatibility with your HA version and need an update. 

Glad to hear its at least somewhat working now.
