### ISSUE TITLE
History graphs from entitys not working and energy dashboard

### ISSUE THREAD

**Issue by RemCom** [home-assistant/frontend#15211]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After upgrading to 2023.2.0b1 the energy dashboard graphs are not working anymore and also history graph from entities. This is happing on phone/tablet/laptop. also after clearing all cache

![Screenshot 2023-01-26 at 07 12 13](https://user-images.githubusercontent.com/3468852/214769636-724423f5-d4dc-4484-a318-39b51b815a59.png)
![Screenshot 2023-01-26 at 07 12 27](https://user-images.githubusercontent.com/3468852/214769661-8004817e-2e3d-4bb8-b357-78e76d01772e.png)

### Describe the behavior you expected

That the graphs are back

### Steps to reproduce the issue

1. Update to beta 2023.2.0b1
2. After update graphs are not working anymore

### What version of Home Assistant Core has the issue?

2023.2.0b1

### What was the last working version of Home Assistant Core?

2023.1.7

### Javascript errors shown in your browser console/inspector

```txt
Dont know of this one is related but this are the console errors

GET https://p.typekit.net/p.css?s=1&k=vnd5jzb&ht=tk&f=24537.24539.24541.24545.24547.24549.24550&a=38518465&app=typekit&e=css net::ERR_CONNECTION_REFUSED

0:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

**Comment by leroyloren** [comment]
the same problem, and I can see in the dev console.

`typography.js:181 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'language')
    at i (typography.js:181:1)
    at d.value (ha-chart-base.ts:134:1)
    at d.update (styles.ts:372:1)
    at d.performUpdate (styles.ts:372:1)
    at d.scheduleUpdate (styles.ts:372:1)
    at d._$Ej (styles.ts:372:1)`

![obrazek](https://user-images.githubusercontent.com/57643470/214798277-ba5074a7-9338-49f4-8f96-3bf642883667.png)

**Comment by Jc2k** [comment]
I have the same error in console as @leroyloren, history graphs not visible, tested in Safari and Chrome on macOS Ventura, and in iOS Home Assistant app too.

**Comment by Jc2k** [comment]
There was a proposed fix for it here which was closed, more context there: https://github.com/home-assistant/frontend/pull/15204.

**Comment by digi303** [comment]
some behavor here, the energy-dashboard ist empty.

**Comment by FrancoLoco** [comment]
My energy dashboard is invisible as well

![image](https://user-images.githubusercontent.com/37370192/214846654-1c254c7c-9352-4547-ad05-0318fb9b315f.png)

**Comment by Salamandar** [comment]
Went here to report. Now i'll wait :D

**Comment by Salamandar** [comment]
It works on 2023.2b4, but for some entities the graph still doesn't shows : "Chargement des statistiques" in french, i guess "Statistics loading"…
