### ISSUE TITLE
"Ignore non-numeric" not available during creation of sensor group

### ISSUE THREAD

**Issue by Skeletorjus** [home-assistant/frontend#15214]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The toggle for "Ignore non-numeric" is not visible when creating a sensor group. To toggle it you have to go to the group settings after the group has been created.

### Describe the behavior you expected

The toggle should be present

### Steps to reproduce the issue

1. Create a new sensor group from helpers
2. Observe that the toggle is missing

### What version of Home Assistant Core has the issue?

core-2023.2.0b1

### In which browser are you experiencing the issue with?

Google Chrome 109.0.5414.75

### Which operating system are you using to run this browser?

Windows 10

**Comment by frenck** [comment]
This is not a frontend issue.

However, this is done by design. The creation flows for new devices, services or entities are always a minimal as possible. Moving additional controls and options into option/configuration flows later on.

../Frenck

**Comment by Skeletorjus** [comment]
OK, I see. It's confusing since the text at the top of the form refers to a setting that is not yet available to the user.
But thanks for clarifying why it's not there.
