### ISSUE TITLE
2023.2 (beta): empty hardware tab

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#15215]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

/config/hardware is completely empty, not even a menu bar to click the overflow to go to all hardware

### Describe the behavior you expected

hardware visible

### Steps to reproduce the issue

1. install 2023.2
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.2.0b1

### What was the last working version of Home Assistant Core?

2023.1

**Comment by piitaya** [comment]
I tested on my yellow and dev container and I'm unable to reproduce. Do you have some logs in the console to share ? What hardware are you using ?

**Comment by Mariusthvdb** [comment]
Just noticed I didn't share a screenshot. Here is some 'proof'

Nothing in log I believe , but can't check now as I am on mobile.

My hardware is a MiniPC Mele. 

![image](https://user-images.githubusercontent.com/33354141/214937888-053c2896-fa01-41b6-85c4-1b8ec007a7e1.png)

**Comment by arenasa70** [comment]
Same issue on a Proxmox VM:
 
Home Assistant 2023.2.0b1
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230125.0 - latest

**Comment by Klangen82** [comment]
Same issue on Generic x86-64 aka NUC

Home Assistant 2023.2.0b2
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230125.0 - latest

**Comment by kulmegil** [comment]
I got this one as well on VirtualBox VM
Home Assistant 2023.2.0b2
Supervisor 2023.01.1
Operating System 9.4
Frontend 20230125.0 - latest

**Comment by Petro31** [comment]
Same issue


## System Information

version | core-2023.2.0b1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.10.0-11-amd64
arch | x86_64
config_dir | /config

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | beta
supervisor_version | supervisor-2023.01.1
agent_version | 1.2.0
docker_version | 20.10.12
disk_total | 220.0 GB
disk_used | 19.0 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok

**Comment by cogneato** [comment]
I can confirm it works on a Yellow for 2023.1.0b2, but updating a minipc running HAOS Generic x86-64 to the same version, the hardware page is blank.

When using beta 0b1 it returns.
<img width="1419" alt="CleanShot 2023-01-27 at 12 07 50@2x" src="https://user-images.githubusercontent.com/2456810/215174363-c2a4637a-bb2b-4de9-b6b4-dcf8c0128804.png">

**Comment by albb2010** [comment]
I'm having the same issue. HA running on a VM and need it resolved to connect the zigbee dongle.

**Comment by LukaszP2** [comment]
Some for me:
core-2023.2.0b4
Home Assistant Supervised
<img width="959" alt="Zrzut ekranu 2023-01-29 084704" src="https://user-images.githubusercontent.com/44735995/215313046-a350af59-5fe2-4fa4-81d0-a09fa6d6dd06.png">
