### ISSUE TITLE
Energy/dashboard graphs disappear

### ISSUE THREAD

**Issue by Nemesis24** [home-assistant/frontend#15231]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hello, 
The graphs in energy/dashboard have disappeared.
![image](https://user-images.githubusercontent.com/25956796/215036999-94122480-3a49-42c9-9b4c-fa45a664847b.png)

### Describe the behavior you expected

I would have the graph like before

### Steps to reproduce the issue

1. Go to dashboard energy
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.2.0b2

### In which browser are you experiencing the issue with?

Chrome 109.0.5414.120

### Which operating system are you using to run this browser?

windows 11

**Comment by skgsergio** [comment]
I've come here looking for the same issue and I've found that the issue was already reported: #15211 

Looks like a fix was made and probably the next beta will include the fix.

**Comment by Nemesis24** [comment]
Ok that's fine, so i could close this one, Thank you.
