### ISSUE TITLE
Energy Dashboarg: graphics is incorrect in Lithuanian version

### ISSUE THREAD

**Issue by Darsma** [home-assistant/frontend#15234]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the Energy Dashboard -> Energy distribution graph lines do not point to circles (like in English version)
Lithuanian version
![image](https://user-images.githubusercontent.com/118769586/215064170-f335341c-ebc8-4055-98eb-5cee2b597620.png)
English version
![image](https://user-images.githubusercontent.com/118769586/215064032-625594d7-e0d9-4c1f-9aa2-2b4a36033a2e.png)

### Describe the behavior you expected

Graphic in every language should be the same

### Steps to reproduce the issue

1. Open Energy dashboard in lithuanian language
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.1.7

### What was the last working version of Home Assistant Core?

Home Assistant 2022.12.9

### Additional information

I would change "Mažai anglies dvideginio" into "Mažai CO2"

**Comment by karwosts** [comment]
Does seem like this is probably related to the string being too long. I don't know if/when a dev will work on fixing the graphic to handle any length of string, but in the meantime if you want to suggest a change to translations, you can follow the process here to contribute translations:

https://developers.home-assistant.io/docs/translations/

Changing of translations is not generally handled by github issue tracker, but through lokalize.

**Comment by Darsma** [comment]
Thank you for explanation. Made fix in translation.
