### ISSUE TITLE
Energy dashboard does not show graphs for Energy Usage, Solar Production, Gas consumption and Monitor individual devices

### ISSUE THREAD

**Issue by ronaldwigman** [home-assistant/frontend#15235]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When starting the Energy dashboard, I do not see graphs for Energy Usage, Solar Production, Gas consumption and Monitor individual devices. 

### Describe the behavior you expected

In the non-beta version I used to see these

### Steps to reproduce the issue

1. Click on Energy dashboard
This also happens in the app on iPad and iPhone and on Chrome
![Energy issue](https://user-images.githubusercontent.com/57071451/215070942-1bf89cd4-2d5f-4d77-96c9-04b6eed79967.jpg)

### What version of Home Assistant Core has the issue?

core-2023.2.0b2

### What was the last working version of Home Assistant Core?

core-2023.1.7

### In which browser are you experiencing the issue with?

Version 109.0.1518.61 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 Enterprise 21H2 19044.2486

**Comment by frenck** [comment]
fixed in #15218
