### ISSUE TITLE
when selecting the edit with YAML option on any page of lovlance it does not present the code as it should

### ISSUE THREAD

**Issue by Dazzlly** [home-assistant/frontend#15237]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

when selecting the edit with YAML option on any page of lovlance it does not present the code as it should 
![image](https://user-images.githubusercontent.com/87374930/215154821-72c03ae3-4252-4810-b79e-7b865996a5ea.png)

### Describe the behavior you expected

I expected / the interface should: show me the YAML code

### Steps to reproduce the issue

1.go to edit panel from any lovlance view page or control panel as you prefer to call it
2.select the pencil (edit button) on the page you want to edit
3.when selecting the edit with YAML option in the 3 stacked squares in the upper right corner, it does not present the code as it should
...

### What version of Home Assistant Core has the issue?

core-2023.1.7

### In which browser are you experiencing the issue with?

Version 109.0.5414.120

### Which operating system are you using to run this browser?

Windows 10 22h2

### Additional information

[Bug_Lovlance-YAML.zip](https://github.com/home-assistant/frontend/files/10521523/Bug_Lovlance-YAML.zip)
in the additional information I added a windows step recorder zip file in case you want to see how to reproduce the bug in steps

**Comment by Dazzlly** [comment]
apparently after installing the latest update of
Operating System Host Home Assistant OS 9.5
made today, the problem has been fixed, here is a screenshot with the demonstration

![image](https://user-images.githubusercontent.com/87374930/215274940-ad4428ad-c8bf-4e85-885b-ad3545796a76.png)

**Comment by Dazzlly** [comment]
apparently after installing the latest update of
Operating System Host Home Assistant OS 9.5
done today, I went to test it and at first glance it worked but I just reloaded the page and the problem came back, I tested the browser cache again and tested it on another device but the problem persists

**Comment by Dazzlly** [comment]
here is a print screen of the moment it worked
![image](https://user-images.githubusercontent.com/87374930/215275654-3cc900e9-bbbe-4f33-9aa4-0827ca166dd5.png)

**Comment by piitaya** [comment]
I unable to reproduce. Can you provide browser logs when you are able to reproduce the bug ? 🙂
