### ISSUE TITLE
Integer value in slider still displayed as a float

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#15238]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

An `input_number` helper with integer `max`, `min` & `step` is presented as a float:
![изображение](https://user-images.githubusercontent.com/71872483/215229034-c6033731-ea9b-448e-bee2-f8b750084f2c.png)

Helper:
```
input_number:
  battery_level_critical:
    min: 0
    max: 100
    step: 1
    unit_of_measurement: '%'
    mode: slider
```
Entities card:
![изображение](https://user-images.githubusercontent.com/71872483/215229299-d31d6113-bb67-4547-9009-2f7bdc6302db.png)

more-info:
![изображение](https://user-images.githubusercontent.com/71872483/215229624-f6f676dd-0eeb-4170-a7f2-6bcc11dccb30.png)

Earlier there were issues & PRs related to this problem - but they were closed:
https://github.com/home-assistant/frontend/issues/9224
https://github.com/home-assistant/frontend/pull/14076
https://github.com/home-assistant/frontend/pull/14112

### Describe the behavior you expected

If a `min`, `max` & `step` values are integer - then present the helper's value as integer.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.1.6

### In which browser are you experiencing the issue with?

Chrome 109.0.5414.120 

### Which operating system are you using to run this browser?

Win10x64

**Comment by karwosts** [comment]
I think features are coming in 2023.02 that will address this: 

https://rc.home-assistant.io/blog/2023/01/25/release-20232/#sensor-precision

**Comment by KNXBroker** [comment]
Just tested this in my beta, will be solved!
