### ISSUE TITLE
Sensor.moon_phase has no locale translations

### ISSUE THREAD

**Issue by blamaz** [home-assistant/frontend#15247]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After the 2023.1 update the sensor.moon_phase has no locale translations for my language (french), it displays english language instead of mine. If I change default profile language to deutsch, it's working but not in french. 

### Describe the behavior you expected

Change sensor language base on profile setup.

### Steps to reproduce the issue

1.Change profile language to french - sensor.moon_phase show in english
2.Change profile language to deutsch - sensor.moon_phase show in deutsch
3.Change profile language back to french - sensor.moon_phase show in english
...

### What version of Home Assistant Core has the issue?

2023.1.7

### In which browser are you experiencing the issue with?

Firefox 109.0 - Google Chrome 109.0.5414.120

### Which operating system are you using to run this browser?

Windows 10 22H2 19045.2486

### State of relevant entities

```txt
options: first_quarter, full_moon, last_quarter, new_moon, waning_crescent, waning_gibbous, waxing_crescent, waxing_gibbous
device_class: enum
icon: mdi:moon-waxing-gibbous
friendly_name: Lune
```

### Problem-relevant frontend configuration

```yaml
No YAML configuration.
```

### Additional information

I can see the translation file is there in github.
https://github.com/home-assistant/core/blob/dev/homeassistant/components/moon/translations/fr.json

**Comment by piitaya** [comment]
The translations are not available in 2023.1 : https://github.com/home-assistant/core/blob/2023.1.7/homeassistant/components/moon/translations/fr.json
but they are available in 2023.2 : https://github.com/home-assistant/core/blob/2023.2.0b0/homeassistant/components/moon/translations/fr.json

It's fixed with the current beta (and will be fixed Wednesday with the 2023.2 release)
