### ISSUE TITLE
Integration filter check boxes do not update

### ISSUE THREAD

**Issue by tomlut** [home-assistant/frontend#15244]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The filter check boxes in the Deceives and Services page do not update correctly:

![Untitled](https://user-images.githubusercontent.com/10679300/215305615-15829703-fbd6-4a7c-ab78-3d7e59cdc904.png)

In Chrome they are never shown as checked. 

In Firefox the disabled integrations filter is always shown as checked and the ignored check box is always shown as un-checked. 

### Describe the behavior you expected

Check boxes to toggle state when clicked, to represent the filter state. 

### Steps to reproduce the issue

1. Go to Settings -> Devices & Services
2. Click on the filter icon
3. Click on a check box in the drop-down menu. 
...

### What version of Home Assistant Core has the issue?

core-2023.1.7

### In which browser are you experiencing the issue with?

Firefox 109.0, Chrome 109.0.5414.120

### Which operating system are you using to run this browser?

Windows 10 build 22H2

**Comment by ildar170975** [comment]
Chrome 109.0.5414.120 
Win10x64
HA 2023.1.6
HA container

![изображение](https://user-images.githubusercontent.com/71872483/215335888-1b094b8e-59b7-41d2-97ca-6aae8878fa27.png)

**Comment by karwosts** [comment]
Duplicate of #11995

**Comment by tomlut** [comment]
Dang it. I did search but did not find anything relevant.
