### ISSUE TITLE
Precision / rounding: -0.3 displayed as -0

### ISSUE THREAD

**Issue by KNXBroker** [home-assistant/frontend#15240]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Amazing new precision feature! I noticed during beta testing that rounding of -0.4 for example is displayed as -0 which does not exists ..

![IMG-20230128-WA0001](https://user-images.githubusercontent.com/25910703/215253251-737eaa63-3246-45b9-8d41-eb45389a686a.jpg)

### Describe the behavior you expected

-0.4 should be displayed as 0

### Steps to reproduce the issue

1.  Round sensor with -0.4 value with precision 0
2.
3.
...

### What version of Home Assistant Core has the issue?

 2023.2.0b3

### In which browser are you experiencing the issue with?

chrome 109.0.5414.118

### Which operating system are you using to run this browser?

Android 13

**Comment by piitaya** [comment]
I think it's a core issue. Frontend only display the state value.
