### ISSUE TITLE
Editing lovelace tab as YAML broken

### ISSUE THREAD

**Issue by benedikt-bartscher** [home-assistant/frontend#15246]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Editing a Lovelace Tab in YAML does not work. I want to edit my Palettes in YAML.

### Describe the behavior you expected

The yaml editor shows me the Tabs YAML and let me edit it.

### Steps to reproduce the issue

1. Open you HA UI
2. Start editing your UI via the 3-dot menu at the upper right
3. Edit a specific lovelace tab by clicking the edit/pen button next to the tab name/icon
4. Open the three-dot menu of the modal which just openend and click on "Edit as YAML"

### What version of Home Assistant Core has the issue?

2023.1.7

### In which browser are you experiencing the issue with?

latest google chrome + qutebrowser

### Which operating system are you using to run this browser?

arch linux 6.1.7-arch1-1

### Javascript errors shown in your browser console/inspector

```txt
styles.ts:372 Uncaught (in promise) TypeError: t.setValue is not a function
    at HTMLElement.value (hui-entity-editor.ts:192)
    at HTMLElement._$AE (styles.ts:372)
    at HTMLElement.performUpdate (styles.ts:372)
    at HTMLElement.scheduleUpdate (styles.ts:372)
    at HTMLElement._$EC (styles.ts:372)
value @ hui-entity-editor.ts:192
_$AE @ styles.ts:372
performUpdate @ styles.ts:372
scheduleUpdate @ styles.ts:372
_$EC @ styles.ts:372
async function (async)
_$EC @ styles.ts:372
requestUpdate @ styles.ts:372
set @ styles.ts:372
(anonymous) @ styles.ts:372
value @ styles.ts:372
value @ home-assistant.ts:66
_$AE @ styles.ts:372
performUpdate @ styles.ts:372
scheduleUpdate @ styles.ts:372
_$EC @ styles.ts:372
async function (async)
_$EC @ styles.ts:372
requestUpdate @ styles.ts:372
set @ styles.ts:372
value @ styles.ts:372
(anonymous) @ styles.ts:372
s @ core.d18ed81d.js:1
(anonymous) @ core.d18ed81d.js:1
e.subscribeMessage.type @ core.d18ed81d.js:1
(anonymous) @ core.d18ed81d.js:1
_handleMessage @ core.d18ed81d.js:1
```

![image](https://user-images.githubusercontent.com/31854409/215329682-1c2dfd42-a362-4350-bdaa-e95f07b804b1.png)

### Additional information

Screenshot of the broken Modal to edit the Tabs YAML:
![image](https://user-images.githubusercontent.com/31854409/215329629-913eb701-3af7-45ac-ab8a-9132ac5e20e0.png)

**Comment by KLucky13** [comment]
Still no fix for this issue? I have the same problem

**Comment by MatthiasLohr** [comment]
No, still not fixed.

**Comment by MatthiasLohr** [comment]
Finally!!! Thanks!
