### ISSUE TITLE
Inspector Safari no longer shows all resources

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#15258]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On Mac Safari when right clicking for Inspector, not all to the custom resources are displayed any longer.

<img width="503" alt="Scherm­afbeelding 2023-01-30 om 12 00 11" src="https://user-images.githubusercontent.com/33354141/215459396-38e62119-7de1-47ad-94e2-cf76b040a15c.png">

Chrome Mac seems to behave as expected.

<img width="539" alt="Scherm­afbeelding 2023-01-30 om 12 00 34" src="https://user-images.githubusercontent.com/33354141/215459430-d96908a7-7d71-488f-9465-f922c3bca7f0.png">

### Describe the behavior you expected

show all resources

### Steps to reproduce the issue

1. Safari, right click Inspector / console
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.2.0b4

### In which browser are you experiencing the issue with?

Versie 16.3 (18614.4.6.1.5)

### Which operating system are you using to run this browser?

Ventura 13.2

### Additional information

Frontend-versie: 20230128.0 - latest

**Comment by piitaya** [comment]
These logs are generated with `console.log` from custom cards. Front-end do not have any actions on that point.

**Comment by Mariusthvdb** [comment]
could it be the Mac OS update changed anything in the Safari browser in that regard?

**Comment by piitaya** [comment]
Don't know. May be you have filters in Safari. I don't have any difference between Safari and Chrome in my side.

**Comment by Mariusthvdb** [comment]
no. no filters, wouldn't even know what those were.
believe closing is too fast.
