### ISSUE TITLE
In addons store search, the letter "m" is caught by "Create new link" function

### ISSUE THREAD

**Issue by clarjon1** [home-assistant/frontend#15272]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In endpoint `/hassio/store`, searching for an addon with the letter "m" makes hass enter a 'm' into the search field while also firing off the "Create a link" in a new tab at `https://my.home-assistant.io/create-link/?redirect=supervisor_store`

### Describe the behavior you expected

I was expecting to be able to continue typing in the search field, not be taken to a new browser tab.

### Steps to reproduce the issue

1. Browse to `/hassio/store` manually in your install or go to https://my.home-assistant.io/redirect/supervisor_store/ to redirect to your install
2. Click in search bar at top
3. Type the letter "m"

### What version of Home Assistant Core has the issue?

2023.2.0b4

### In which browser are you experiencing the issue with?

Firefox 109.0 and Chrome 109.0.5414.120

### Which operating system are you using to run this browser?

Windows 10 21H2

**Comment by balloob** [comment]
Fixed in https://github.com/home-assistant/frontend/pull/15269
