### ISSUE TITLE
No way to delete a RFXtrx device

### ISSUE THREAD

**Issue by rhoddan** [home-assistant/frontend#15276]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The delete function is not visible any more so it's impossible to remove a RFXtrx device

### Describe the behavior you expected

be able to click remove and remove a device

### Steps to reproduce the issue

1. go to settings
2. RFXTRX
3. Press configure
4. No remove alternative
...

### What version of Home Assistant Core has the issue?

2023.1.7

### What was the last working version of Home Assistant Core?

not sure

**Comment by benganellison** [comment]
delete button is still there, just in a new place. but i would still love to delete more than one device at a time. is the old way of doing this good enough for you?

here you find delete
<img width="518" alt="Screenshot 2023-02-05 at 20 22 17" src="https://user-images.githubusercontent.com/23585524/216840242-823faf1a-63fc-4567-8a12-d4931409d8a9.png">

**Comment by rhoddan** [comment]
Ahh - thanks a lot! I though these dots were related to "Download Diagnostiscs". The rfxtrx documentation was not updated either...
