### ISSUE TITLE
Not all entities quickgraphs are showing

### ISSUE THREAD

**Issue by horstefan** [home-assistant/frontend#15277]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Some entities (W, KwH, %) show correct history graph when clicking an entity
<img width="556" alt="Scherm­afbeelding 2023-01-30 om 20 39 47" src="https://user-images.githubusercontent.com/23259607/215578841-f543cd67-e4a5-4b8d-923f-62c1836df50f.png">

others do not show: (min, L)
<img width="544" alt="image" src="https://user-images.githubusercontent.com/23259607/215578992-99f2d3b4-cd02-4f71-9201-2ef0d33c10b6.png">

Clicking "show more" does reveil the correct history:
<img width="1513" alt="image" src="https://user-images.githubusercontent.com/23259607/215580105-931f45c7-f048-4344-b061-f43972fbee14.png">

Energy dashboard also stopped working at the same time:
<img width="1593" alt="image" src="https://user-images.githubusercontent.com/23259607/215579277-0b2b3c39-8f84-48f1-836d-fdfe141eb627.png">

### Describe the behavior you expected

History to work as intended

### Steps to reproduce the issue

NA

### What version of Home Assistant Core has the issue?

2023.2.0b5

### What was the last working version of Home Assistant Core?

2023.1

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
N/A both from Dashboards and Entities.
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

### Additional information

No logbook errors

**Comment by karwosts** [comment]
Can you double check that you're certain you're on 0b5, cleared cache and everything? This was a known issue and was fixed in 0b4, and confirmed fixed by many users.

**Comment by horstefan** [comment]
> Can you double check that you're certain you're on 0b5, cleared cache and everything? This was a known issue and was fixed in 0b4, and confirmed fixed by many users.

You are correct! apologies for wasting your time! clearing the cache on 0b5 did it.
