### ISSUE TITLE
2023.2 not working with Old Android 4.3 browsers

### ISSUE THREAD

**Issue by roblamoreaux** [home-assistant/frontend#15303]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a few old Rooted Wink Relays which run Android 4.3. Using Chrome and Firefox these have shown the HA frontend fine until the 2023.2 betas. With 2023.2 they hang with the logo screen, and after clearing the browser data they hang before giving the log in screen. I suspect something was added that the old browser can't do and would like to find a work around for these devices since it is nice having a simple button screen on them.

### Describe the behavior you expected

I would expect to see the same browser screens I see in devices with newer browsers.

### Steps to reproduce the issue

1. Update to 2023.2.xxx
2. open Home assistant in Android 4.3 browser (I think they are Chrome 76 and earlier, but are the latest I could get to work with Android 4.3)
3. Screen is just HA Logo
...

### What version of Home Assistant Core has the issue?

2023.2.0bx (it seemed to appear in 0b0 and is still there in 0b9

### What was the last working version of Home Assistant Core?

2023.1.x

### In which browser are you experiencing the issue with?

Google Chrome 76.xxxx and early Firefox (Android 4.3)

### Which operating system are you using to run this browser?

Android 4.3

**Comment by steverep** [comment]
Nothing in the console?

**Comment by roblamoreaux** [comment]
> Nothing in the console?

I'll check when I get home. I assume that is the HAOS console, but I'll see if there is anything on the Chrome side that would help. All my other devices with newer browsers work fine.

**Comment by steverep** [comment]
Fixes are in work.

Dependencies have been upgraded quite a bit since 2023.1 and looks like there were some inadvertent breakages for older browsers.

**Comment by roblamoreaux** [comment]
Awesome. I meant to post yesterday but got busy with work. Glad I'll be able to keep using the Wink Relays and won't have to replace them with something better (they were paid for years ago).

Rob

**Comment by steverep** [comment]
The PR I just linked should fix this - I'll reopen if not.  Hang on for 2023.2.1.

**Comment by roblamoreaux** [comment]
I can confirm that my devices with old browsers work again with 2023.2.1. 

Thanks for the quick update

Rob
