### ISSUE TITLE
Unifi POE switch's Port's POE on/off switch not working propely

### ISSUE THREAD

**Issue by RASBR** [home-assistant/frontend#15308]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Unifi USW Pro 48 POE switch has 48 POE sitches to turn of/off POE supply for the ports. in 'auto entities' card the switches when pressed turn the POE off, but on the UI they go back to indicate on while the port POE is really off.

to turn POE on again on the port it has to be done via the Unifi controller

### Describe the behavior you expected

When port POE is on/off the UI switch should indicate that properly.

### Steps to reproduce the issue

1. List all USW POE switch entities in an Auto Entities card.
2. Try turning some Pot's POE power off/on
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.2.0

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
Is this limited to auto entities card, or is anything else in the frontend broken? 

This repository does not handle issues with custom cards, you would have to report this to the repository for that card instead (assuming it is limited to custom:auto-entities).

**Comment by RASBR** [comment]
I think it is related to the integration it self and how it exchanges this piece of data. I tried it with Mushroom entity card with Toggle option. This was noticed while I had Core 2023.1.7.
Now with 2023.2.0 the switch entity has the same issue, and the sensor reporting the power consumption on the port also doesn't update when switching the port POE off.

**Comment by RASBR** [comment]
Hello,
If you turn off POE on a port from HA it responds from Unifi and the POE is off. however the switch status in HA front end reverts to on although the POE is still off on the Unifi switch.
