### ISSUE TITLE
Light card not showing correct color when light is on

### ISSUE THREAD

**Issue by Runesmacher** [home-assistant/frontend#15319]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Light Card no longer shows state color.

### Describe the behavior you expected

When light is ON, color needs to be the "accent collor" now it turns White (dark mode) or Black (Light mode)

### Steps to reproduce the issue

1. Install HA 2023.2.0
2. add light card for light

### What version of Home Assistant Core has the issue?

core-2023.2.0,core-2023.2.1

### What was the last working version of Home Assistant Core?

core-2023.1.7

### In which browser are you experiencing the issue with?

Google Chrome Version 109.0.5414.120, Firefox 109.0.1, HASS android app

### Which operating system are you using to run this browser?

Windows 10, android 13

### State of relevant entities

```txt
Lights are on
```

### Problem-relevant frontend configuration

```yaml
type: light
entity: light.shelly_bureau
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

Light card top left not working, button card bottom left is working
![image](https://user-images.githubusercontent.com/979451/216358551-23e15a7f-bc3a-4a74-8973-7388f6fa4ca8.png)

**Comment by joedogg** [comment]
I am seeing the same issue.

**Comment by p-nightmare** [comment]
same, both in 2023.2.0 and 2023.2.1

**Comment by Duke-Box** [comment]
Glad the re is an issue open for this as I was about to report it.
I can confirm it works ok in 2023.1.7 but not in 2023.2.x
