### ISSUE TITLE
Re-order button in Automation Editor missing

### ISSUE THREAD

**Issue by morremeyer** [home-assistant/frontend#15324]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the automation editor, the “Re-order“ button that allowed reordering of actions is gone.

### Describe the behavior you expected

The re-order button should be there to allow reordering of actions.
I tried drag and drop, but that did not work either

### Steps to reproduce the issue

1. Open any Automation in the Automation Editor
2. Click the three dots on top
3. See that the „re-order“ button is missing (see also the Screenshot)

![image](https://user-images.githubusercontent.com/7683567/216440544-d6f94748-b85d-43f9-8b94-1cc73176c4de.png)

### What version of Home Assistant Core has the issue?

2023.2.0, Frontend 20230201.0

### In which browser are you experiencing the issue with?

Firefox 109.0

### Which operating system are you using to run this browser?

macOS Ventura 13.1 (22C65)

**Comment by karwosts** [comment]
I think you're looking in the wrong place. If you click the triple dot on any of the individual items in triggers, conditions, or actions list, you will find re-order option there.

**Comment by morremeyer** [comment]
Oh well. Hadn't noticed that. Thank you!
