### ISSUE TITLE
Change of units in entity settings not consistent

### ISSUE THREAD

**Issue by tramperb** [home-assistant/frontend#15327]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

2023.2.0 added the ability to change the units of sensors.  However, after units are changed (eg from B to GB), the history pop-up shows vertical axis in B (but labels the axis with GB).  See attached jpg - with red highlighting the issue.
Note that changing a sensor from Wh to kWh works as expected - ie does not have this issue - the history pop-up does change the vertical axis values as expected.

Also (although I guess this is a feature request), when changing units (eg from B to GB) it would be very useful to be able to specify the precision (3.519873308 GB would be more useful as, say, 3.52 GB)
![units](https://user-images.githubusercontent.com/85221759/216492043-e254bce9-1e0c-4773-a87a-30a61cd739f0.jpg)

### Describe the behavior you expected

I expected the history graph to show data in the new units specified.

### Steps to reproduce the issue

1. Select settings / devices & services / entities
2. Select a sensor
3. Change the default unit to another option
4. Navigate to a card showing the sensor and click to view the history
...

### What version of Home Assistant Core has the issue?

2023.2.0

### In which browser are you experiencing the issue with?

Chrome Version 109.0.5414.120 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Win 10 Home 22H2 build 19045.2486

**Comment by karwosts** [comment]
You might check if release 2.1 solves this (just released tonight). It has some fixes related to unit conversions from this PR: https://github.com/home-assistant/core/pull/87137

**Comment by tramperb** [comment]
Version 2023.4 addresses both the vertical scale issue & the precision feature request - thanks, works well.
