### ISSUE TITLE
The "Precision" tab does not exist in update 2023.2

### ISSUE THREAD

**Issue by RH-Dreambox** [home-assistant/frontend#15320]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The "Precision" tab does not exist in update 2023.2 so I cannot change the number of decimal places on my sensors.
Do I need to enable that feature or is it missing from my update?
The installation is Generic x86-64 (Dell Optiplex) Swedish language.

Home Assistant 2023.2.0
Supervisor 2023.01.1
Operating System 9.5
Frontend-version: 20230201.0 - latest

### Describe the behavior you expected

The "Precision" tab does not exist for sensors

### Steps to reproduce the issue

1. Open a temperature sensor
2. Open Settings
3. The "Precision" tab is missing
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.2.0

### Which operating system are you using to run this browser?

Windows 10

**Comment by ubarni** [comment]
Same issue here on my MAC with Chrome Version 109.0.5414.119 (Offizieller Build) (arm64)

**But it works with Safari Browser!**

**Comment by frenck** [comment]
The precision feature has not been released/does not exist in the current stable. I'm not sure what the issue is you are reporting, could you clarify?

../Frenck

**Comment by ubarni** [comment]
THX for clarifying @frenck 
Most YTbers showed this feature in there 2023.2 feature list.
So i assumed the precision feature should work in this release.

**Comment by ubarni** [comment]
<img width="973" alt="Bildschirm­foto 2023-02-03 um 09 15 43" src="https://user-images.githubusercontent.com/5228490/216547911-5e2dad6d-a9a6-4333-8eb8-9f4883a07062.png">

**Comment by frenck** [comment]
> Most YTbers showed this feature in there 2023.2 feature list.

That is possible, looks like they created videos based on the Beta version of Home Assistant.

The fact is, we have pulled the feature during the beta period as it manifested issues we want to research before we mark it stable.

Please check our release announcement for new features released on our website.

../Frenck
