### ISSUE TITLE
missing translation for new "Sensors group" helper

### ISSUE THREAD

**Issue by ChristophCaina** [home-assistant/frontend#15333]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The "sensor group" that has been introduced with the recent version of HA does not yet have any translation.
![image](https://user-images.githubusercontent.com/26391061/216528229-d7a5cf75-bfd1-4e44-baa0-c13ee202c9f6.png)

While it's not a big issue within the dialog where you select the group, it might be an issue for some when it comes to the configuration - in this case, the complete dialog needs to be translated:
![image](https://user-images.githubusercontent.com/26391061/216528121-f87fbf61-eb2f-432b-87f8-c5f1349898c8.png)

I would start with the translation and submit an PR for it, if I knew where this needs to be done :)

### Describe the behavior you expected

translate new implemented elements - or at least start with the translation before they will be rolled out.

### Steps to reproduce the issue

1. switch ui language to any "non english" language
2. create a new helper -> add helpers -> group
3. check translation for sensor group + sensor group configuration dialog
...

### What version of Home Assistant Core has the issue?

core-2023-02-2

**Comment by karwosts** [comment]
If you want to learn about, or contribute to translations, you can check here:

https://developers.home-assistant.io/docs/translations/

Translations are done through lokalize, not through issues or pull requests. 

These strings you are looking at I believe are in core, not frontend. I believe the normal flow is for new strings to get added with english translation only, and then contributors through lokalize add translations, and those translations are then released in subsequent minor releases. So it's possible that this has already been translated, depending on what language you are using, and you will pick it up in the next release. You can check on lokalize if you want.

**Comment by ChristophCaina** [comment]
Thanks :)
