### ISSUE TITLE
Warrnings of sensors

### ISSUE THREAD

**Issue by mariusnauj** [home-assistant/frontend#15335]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hello,

After last update I noticed warrnings:

Entity sensor.taked_from_grid_energy_kwh (<class 'homeassistant.components.template.sensor.SensorTemplate'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+template%22
Entity sensor.returned_to_grid_energy_with_12_kwh (<class 'homeassistant.components.template.sensor.SensorTemplate'>) is using state class 'measurement' which is impossible considering device class ('energy') it is using; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+template%22

Entity configurations:

 - name: "Taked from grid energy kWh"
        unit_of_measurement: "kWh"
        state_class: measurement
        device_class: energy

- name: "Returned to grid energy with -12% kWh"
        unit_of_measurement: "kWh"
        state_class: measurement
        device_class: energy

### Describe the behavior you expected

.

### Steps to reproduce the issue

1. After reboot HA, warrnings appear.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.2.1

**Comment by ChristophCaina** [comment]
The state_class should probably be total_increasing

https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes
