### ISSUE TITLE
Cannot read properties of undefined (reading 'loadBackendTranslation')

### ISSUE THREAD

**Issue by flatsiedatsie** [home-assistant/frontend#15343]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If the onboarding is interupted by a browser reload, Home Assistant becomes unusable.

I was going through the onboarding process of the hoas disk image. At a certain point it was showing my a popup about integrations, and the ones it had already found (bluetooth, etc). At this point I clicked on the (+) icon, which gave the page an overlay, but content didn't load into it. I was stuck, so I figured a privacyprotecting browser plugin was to blame. I disabled DuckDuckGo's addon, which causes the page to be reloaded. I was hoping that the system was smart enough to continue where I left off.

Instead I had to log back in (white background), and then I suspect it tried to get me back to the same step (onboard was in the URL), but then the page diddn't finish loading. I saw a javascript error in the console, see below.

I have not cleared the browser cache and haven't tried another browser, because I decided to flash the SD card again before I went to this issue page.

### Describe the behavior you expected

I hopes the onboarding process could recover from a browser refresh.

### Steps to reproduce the issue

See above.

### What version of Home Assistant Core has the issue?

Cannot access this. The disk image name is: haos_rpi4-64-9.5.img.xz

### In which browser are you experiencing the issue with?

Brave 1.47.171

### Which operating system are you using to run this browser?

Mac OS Monterey

### Javascript errors shown in your browser console/inspector

```txt
Uncaught TypeError: Cannot read properties of undefined (reading 'loadBackendTranslation')
    at HTMLElement.value (integration-badge.ts:86:1)
    at finisher (styles.ts:372:1)
    at Object.runClassFinishers (integration-badge.ts:86:1)
    at integration-badge.ts:86:1
    at 31261 (integration-badge.ts:86:1)
    at Function.u (styles.ts:372:1)
value @ integration-badge.ts:86
finisher @ styles.ts:372
runClassFinishers @ integration-badge.ts:86
```
```


### Additional information

_No response_

**Comment by jamalex** [comment]
Getting the same thing here, on a fresh install of Home Assistant on the Yellow, using the RPi Imager with the image for the Yellow. It got through most of the onboarding wizard, then is getting stuck with just this on the screen:

![image](https://user-images.githubusercontent.com/618416/216836295-6d82e2dc-2a00-495a-82ff-26f672d4f17e.png)

![image](https://user-images.githubusercontent.com/618416/216836310-7a2429fd-c293-468d-85a5-a13f29a53de3.png)

(Browser: Chrome on Ubuntu: Version 108.0.5359.124 (Official Build) (64-bit))

**Comment by jamalex** [comment]
I ended up there for similar reasons... I got to the screen below, clicked "More", and the page froze with a gray overlay, so I refreshed the page, re-logged in, and ended up with the page and error shown above.

![image](https://user-images.githubusercontent.com/618416/216836445-b84706db-4194-44c1-8044-31ee72b71796.png)

I loaded the URL in Firefox, got this screen again, and then was able to "Finish".

**Comment by joschi** [comment]
Same issue here with a fresh installation of [Home Assistant OS 9.5](https://github.com/home-assistant/operating-system/releases/tag/9.5) (Generic x86-64).

**Comment by theHacker** [comment]
Same here. Fresh installation with image `haos_rpi4-64-9.5.img.xz` and Chromium version 110.0.5481.100.

I tried logging in with Firefox. There I was landed back on the page showing the different integrations. This time, I did NOT press "More" (better safe than sorry :wink:), and I could finished the onboarding workflow. Hope that helps somebody. Used Firefox version 110.0.

**Comment by marianomd** [comment]
Same here. Supervised install on fresh Debian 11.6.

**Comment by andrej-vasilj** [comment]
Same here. Fresh install on a RPi 4. Any mitigations?

**Comment by martin-schoen** [comment]
sadly i can report that i have the same problem with a fresh install on my pi with docker

**Comment by Sonorpearl** [comment]
Same issue here on my Synology NAS. I clicked "More", and it hung, refreshed, and now this error.
Using the current stable image.
