### ISSUE TITLE
Missing unit configuration in the derivative sensor helper

### ISSUE THREAD

**Issue by seblu** [home-assistant/frontend#15345]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The derivative sensor creation and edition interfaces lack of [unit](https://www.home-assistant.io/integrations/derivative/#unit) configuration parameter.

Creation UI:
![Screenshot_20230205_013253](https://user-images.githubusercontent.com/615816/216795436-31469007-07c3-4b88-a485-a6a129f8423b.png)

Edition UI:
![Screenshot_20230204_191346](https://user-images.githubusercontent.com/615816/216795343-8b403e15-337f-4a4d-b1c6-c833c1c9ce5a.png)

This parameter is useful to display units correctly if they are not simply deducted by other parameters.
For example a derivative of kWh is displayed as `mkWh/h` instead of `W`.

![Screenshot_20230204_191621](https://user-images.githubusercontent.com/615816/216795479-7c17d7db-b486-431d-8230-e86a7784a2e6.png)

Related: https://github.com/home-assistant/core/issues/87418.

### Describe the behavior you expected

Be able to set all the [configuration variables](https://www.home-assistant.io/integrations/derivative/#configuration-variables) in the frontend.
 
The missing parameters are : `unit` and  `time_window`. 

### Steps to reproduce the issue

1. Goes to Settings -> helpers
2. Create a Derivative
3. Cannot set the `unit` parameter

### What version of Home Assistant Core has the issue?

core-2023.2.1

### In which browser are you experiencing the issue with?

Firefox, Chrome

### Which operating system are you using to run this browser?

Arch Linux

**Comment by cronjevh** [comment]
May be related...

I was busy configuring a new derivative sensor in the UI while upgrade from ha core 2023.2.0 -> 2023.2.2. When I reloaded the frontend after update completed, I couldn't see the [Time window](https://www.home-assistant.io/integrations/derivative/#time-window) input field anymore. 

After reverting the upgrade and restoring the backup, I'm able to see the Time Window input field again.  As the time window is still referenced in the docs, it doesn't look like this was removed on purpose.

**Comment by charlesdagenais** [comment]
> I was busy configuring a new derivative sensor in the UI while upgrade from ha core 2023.2.0 -> 2023.2.2. When I reloaded the frontend after update completed, I couldn't see the [Time window](https://www.home-assistant.io/integrations/derivative/#time-window) input field anymore.
> 
> After reverting the upgrade and restoring the backup, I'm able to see the Time Window input field again. As the time window is still referenced in the docs, it doesn't look like this was removed on purpose.

Same here: no more time_window input field in GUI for derivative helper in 2023.2.2

**Comment by MattBavaria** [comment]
Hello,
Might be connected to this issue:
[CORE/DERIVATIVE](https://github.com/home-assistant/core/issues/87515)
Regards,
MattBavaria

**Comment by seblu** [comment]
Issue is still relevant in HomeAssistant `2023.06.0` and frontend `20230607.0`

**Comment by karwosts** [comment]
You can always override the unit with `customize` 
 
 https://www.home-assistant.io/docs/configuration/customizing-devices/

**Comment by seblu** [comment]
Ah nice workaround.

Is possible to move this issue from frontend to core?

**Comment by karwosts** [comment]
I don't have permissions to move it, and nobody else seems to be taking up the effort to do so, so I'll just suggest you file a new issue there if you want to pursue this (you can reference this in the description if you want).

Closing as off topic for this repo.
