### ISSUE TITLE
Automation trace timeline is empty 

### ISSUE THREAD

**Issue by pedolsky** [home-assistant/frontend#15348]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The behaviour described in [#13557](https://github.com/home-assistant/frontend/issues/13557) seems to be back. 

When using a short form condition like:

```

  trigger:
    - …


  condition:
    - "{{ false if trigger.id == 'light' and trigger.to_state.state == 'on' and states(input_select) in optionen else true }}"


```

the trace timeline is empty.

Using

```

  trigger:
    - …


  condition:
    - condition: template
      value_template: |-
        {{ false if trigger.id == 'light' and 
        trigger.to_state.state == 'on' and 
        states(input_select) in optionen
        else true }}

```

the timeline is displayed.

### Describe the behavior you expected

A visible trace timeline 

### Steps to reproduce the issue

1. Use a short form template condition in your automation.
2. Trigger that automation.
3. Check the trace timeline.
...

### What version of Home Assistant Core has the issue?

core-2023.2.2

### In which browser are you experiencing the issue with?

Chrome 109.0.5414.112, Safari 16.3

### Which operating system are you using to run this browser?

iPadOS 16.3, IOS 16.3

**Comment by pedolsky** [comment]
Not solved.

**Comment by rhopkins7428** [comment]
I just experienced this myself.  All trace tabs completely empty for one automation, (but working for all other automations) 

As a workaround, I was able to download the trace clicking Traces, then the three dots "..." and then download trace.  
That was very helpful.

Core
2023.12.3
Supervisor
2023.11.6
Operating System
11.2
Frontend
20231208.2
