### ISSUE TITLE
Alarm Control Panel

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#15351]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Alarm Control Panel in PopUp dont have other arm buttons only arm home away and disarm, please add other button for this.

![image](https://user-images.githubusercontent.com/42905545/216847370-40dbc767-a0b9-4f5d-bcf8-4d2d9e2f2065.png)
![image](https://user-images.githubusercontent.com/42905545/216847378-12d6b437-a4b6-4a94-9a38-1453213bc131.png)

### Describe the behavior you expected

*

### Steps to reproduce the issue

*

### What version of Home Assistant Core has the issue?

2023.2.2

**Comment by karwosts** [comment]
Addressed in #15452
