### ISSUE TITLE
Binary Sensor Options for Addon Running Status Incorrect in Automation GUI

### ISSUE THREAD

**Issue by kcTodd** [home-assistant/frontend#15350]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I use the binary sensor for addons running state (e.g., binary_sensor.wireguard_running) inside of a script as a trigger or an IF condition, the GUI expects options of "Running", "Not running", "Unavailable" and "Unknown". However, the conditions only work if I use "on" or "off" as conditions for the sensor, which means I have to override the pulldown in the menu when editing the condition in the GUI.

### Describe the behavior you expected

I expect the condition to work by using the state of "Running" or "Not running" that is provided in the GUI pulldown options, OR I expect the GUI to provide "on" or "off" conditions in the pulldown. Either would be acceptable behavior. 

Note that when viewing the actual sensor state in the GUI, it shows either "Running" or "Not running" (not "on" or "off").

### Steps to reproduce the issue

1. Create a script or an automation with a condition that uses the binary sensor for an installed addon. These have the name 'binary_sensor.<ADDON_NAME>_running'. 
2. In the automation or script GUI, choose one of the pulldown options for the condition of the binary sensor. You will see "Running" and "Not running" as the two primary options. Select one of them to test out the trigger.
3. Start or stop the particular addon and see how the automation or script interprets the condition.
...

### What version of Home Assistant Core has the issue?

2023.2.2

### In which browser are you experiencing the issue with?

Microsoft Edge Version 109.0.1518.70 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
binary_sensor.wireguard_running
WireGuard Running: on
device_class: running
friendly_name: WireGuard Running
```

**Comment by karwosts** [comment]
I set this up and I see yes it has "Running" and "Not running" in the UI editor. 

However if I select from "Running" to: "Not Running", these, and change over to yaml to inspect the automation, the actual yaml has:

```
from: "on"
to: "off"
```

If you look at your yaml, does it say on/off, or "Running"/"Not running"?

I'll note that someone recently reported this exact same issue, and he said that after he uninstalled card-mod the problem went away. Perhaps you are hitting the same thing, if you use the same plugins.
