### ISSUE TITLE
No state color on light card

### ISSUE THREAD

**Issue by Ziepoeskenetnie** [home-assistant/frontend#15352]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The state color of a light card is not showing up

![Screenshot_20230205_231742_Home Assistant](https://user-images.githubusercontent.com/108867885/216849263-a1c1b8e2-edd5-44e5-91df-f718169a4fa9.jpg)

### Describe the behavior you expected

That it's showing the right color again

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.2.2

**Comment by kenlasko** [comment]
Already reported on #15319

**Comment by Ziepoeskenetnie** [comment]
Didn't see that one.
Can i close it?

**Comment by piitaya** [comment]
I close this one as it's a duplicate of #15319
