### ISSUE TITLE
Energy Dashboard - Monitor Individual Devices - Wording error

### ISSUE THREAD

**Issue by CaptainKarma** [home-assistant/frontend#15353]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Clicking on the Day / Week / Month / Year bar on the top row, doesn't change the Monitor Individual Devices text wording which still says x ENERGY Today

### Describe the behavior you expected

Monitor Individual Devices wording should change to Week or Month or Year to reflect the selection

### Steps to reproduce the issue

1.  Open the energy page
2.  Click on the Week / Month or Year buttons
3.  Monitor Individual Devices does not change
...

### What version of Home Assistant Core has the issue?

2023.2.2

### Additional information

![image](https://user-images.githubusercontent.com/1750450/216853555-c8cd64f2-ca6c-488e-b474-8454b7fff00f.png)

**Comment by ChristophCaina** [comment]
the wording of "Monitor individual devices" isn't provided by the energy dashboard itself.
It just displays the sensors name:

![image](https://user-images.githubusercontent.com/26391061/217446924-948e8a96-068d-4dd6-8828-8640f5660cef.png)
