### ISSUE TITLE
Add integration > Search ignores first letter

### ISSUE THREAD

**Issue by eikowagenknecht** [home-assistant/frontend#15361]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The search dialog ignores the first letter. E.g. "instar" searches for "nstar" instead.

![image](https://user-images.githubusercontent.com/1475672/216948603-3190d0f7-7757-48ad-af15-552f1d8a2234.png)

Another example:
![image](https://user-images.githubusercontent.com/1475672/216948790-7bc4b09c-fc22-4c66-bed8-b56f313155c7.png)

### Describe the behavior you expected

The first letter should be included in the search query.

### Steps to reproduce the issue

1. Click add integration
2. enter "instar"
3. see that "venstar" is shown
...

### What version of Home Assistant Core has the issue?

core-2023.2.2

### In which browser are you experiencing the issue with?

Google Chrome 109

### Which operating system are you using to run this browser?

Windows 10

**Comment by Himanshu-Vishwas** [comment]
okay so its basically not taking the string[0] search query parameter
is there any for loop for searching words which begins from 1. this may be the issue of skipping the 0th-index.

**Comment by karwosts** [comment]
I don't think it's anything specific to the first letter, I think it's just some kind of fuzzy search matching that tries to be helpful in the presence of typos. 

xbode, axode, abxde, aboxe, and abodx all bring up Abode as a result.

**Comment by piitaya** [comment]
I confirm, it's a fuzzy search feature to avoid spelling mistake and have a better matching 🙂
