### ISSUE TITLE
Energy Dashboard color gradients make it very hard to distinguish between tarifs

### ISSUE THREAD

**Issue by mathieucarbou** [home-assistant/frontend#15384]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the case where several utility meters are required, a sort of color gradient is applied for the tarifs:

![](https://user-images.githubusercontent.com/61346/217260373-270f5475-8dcd-423b-9f02-e9e5f8fe7c92.png)

but the problem is having a lot of meters (like it may be the case here in France), causes the graph to be really unreadable since the bars are not easily distinguished

![image](https://user-images.githubusercontent.com/61346/217261397-18e09ec2-dfc9-44e3-b212-6adb3e489ea0.png)

### Describe the behavior you expected

To solve this, one of the solutions would be to implement feature request https://github.com/home-assistant/frontend/discussions/12397

### Steps to reproduce the issue

Add several utility meters in energy dashboard

N/A

### What version of Home Assistant Core has the issue?

core-2023.2.2

**Comment by Mosher23** [comment]
I would like to support these request

**Comment by antoineguilbert** [comment]
Good idea, also want this request !

**Comment by Binifada1956** [comment]
it would be really great if you could customise the energy-dasbord with colours. I also use a Tariff with 6 different Prices. The visual result ist no good!

 
![C31A26DA-4F31-426C-8B59-D5BD4F3A2E7C](https://user-images.githubusercontent.com/99736262/221364876-5489551a-c2f3-4a83-b8c8-95299d76873d.jpeg)

**Comment by RipDem0n06** [comment]
It would be amazing ! Please add color choice !

**Comment by tgtechy** [comment]
I would like to see this also.

**Comment by Olaf-fi** [comment]
being able to choose the colours would be very helpful.
Even some information on where to change it in some .config would be a good start. To re-write a whole Theme seems excessive.
A item in the Grid Consumption UI page would be ideal
![image](https://github.com/home-assistant/frontend/assets/108768546/f917df58-e151-41e6-a835-00d3149cf46b)

**Comment by Olaf-fi** [comment]
hi there, any news on this?
is there a guide to dive into the code somewhere to achieve this?

**Comment by Binifada1956** [comment]
No change in 2023.10
Colors in the grid work, but not in the sources!?

My Colors for RTE-Tempo:
 # Energy Dashboard
  energy-grid-consumption-color-0: '#FFFAFA'                                    #snow
  energy-grid-consumption-color-1: '#CDC9C9'                                    #snow3
  energy-grid-consumption-color-2: '#00BFFF'                                    #deepskyblue
  energy-grid-consumption-color-3: '#00008B'                                    #darkblue
  energy-grid-consumption-color-4: '#FF0000'                                    #red
  energy-grid-consumption-color-5: '#8B0000'                                    #darkred

The Result:
![grafik](https://github.com/home-assistant/frontend/assets/99736262/7ba2f982-832f-476f-b8cb-3ce9dd6a9641)

Does anyone know anything?

**Comment by karwosts** [comment]
The update for that card (sources table) wasn't merged yet, you need to wait for https://github.com/home-assistant/frontend/pull/17826
