### ISSUE TITLE
History dashboard - it is possible to add non existing entity, that results infinite load without abort option

### ISSUE THREAD

**Issue by luzik** [home-assistant/frontend#15393]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In history view I started to search for entity writing first two letters, and I did not choice any of suggested entities - just pressed enter. Now all history tab buttons are disabled, and page is loading.
Removing  historyPickedValue from browser fix issue. Removing entity_id from GET url do not fix it

### Describe the behavior you expected

I am not able to select non existing entity by pressing enter

### Steps to reproduce the issue

1. go to /history
2. write random letters in entity selector 
3. do not choice any, just press enter
4. try to select other entity, or remove selected

### What version of Home Assistant Core has the issue?

2023.2.3

### In which browser are you experiencing the issue with?

Chromium

### Which operating system are you using to run this browser?

Linux

**Comment by luzik** [comment]
It can be related to https://github.com/home-assistant/frontend/issues/15386

**Comment by ildar170975** [comment]
Confirmed (2023.2.2, HA container)
