### ISSUE TITLE
Sensor graph SVG overflows card's rounded corner (#2)

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#15401]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Instead of a closed issue: https://github.com/home-assistant/frontend/issues/14275

The conventional Sensor card has filling which overflows rounded corners:

![изображение](https://user-images.githubusercontent.com/71872483/217684494-3ced82ce-788f-4e31-9af4-0d5586d9becb.png)

Zoomed:
![изображение](https://user-images.githubusercontent.com/71872483/217684656-62eca393-187a-484b-a0ee-4604cb3ce343.png)

### Describe the behavior you expected

Filling does not overflow card's corners.

### Steps to reproduce the issue

1. Add a Sensor card.
2. Check bottom corners.

### What version of Home Assistant Core has the issue?

2023.2.2

### In which browser are you experiencing the issue with?

Chrome 109.0.5414.120 

### Which operating system are you using to run this browser?

Win10x64

**Comment by ildar170975** [comment]
up

**Comment by domnantas** [comment]
This is still relevant. Adding `overflow: hidden` on `ha-card` fixes the issue. Will try to open a PR
