### ISSUE TITLE
Incorrect status for Bosch WAV28EA9II

### ISSUE THREAD

**Issue by Riccardi72** [home-assistant/frontend#15415]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The status of device is not syncronized with reality. When I turn on the device and it goes to the end, the status remain always on. If I reboot the home assistant it comes back ok. I notice that Program Progress arrives at 98% and never 100%.

### Describe the behavior you expected

I expect that when device has finished the status becomes off

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2023.2.3

### In which browser are you experiencing the issue with?

Google Chrome 109.0.5414.12

### Which operating system are you using to run this browser?

Windows 10

**Comment by Riccardi72** [comment]
Issue still open

**Comment by karwosts** [comment]
Please close this and open an issue in the homeassistant/core repository against the bosch integration (whichever one controls your dishwasher). 

This repository is for the frontend, which has no control over the status of entities.

**Comment by karwosts** [comment]
Tracked in https://github.com/home-assistant/core/issues/94146
