### ISSUE TITLE
Missing January title on energy graph

### ISSUE THREAD

**Issue by bigboban** [home-assistant/frontend#15421]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing January title, year number is there instead. See pic.

![image](https://user-images.githubusercontent.com/7159224/218168792-90522a9c-727f-48c1-b065-486256347c54.png)

### Describe the behavior you expected

All 12 months labels on right plase and year label on some other place.

### Steps to reproduce the issue

1. Open energy dashboard.
2. Click YEAR button.
3.
...

### What version of Home Assistant Core has the issue?

2023.2.2

**Comment by Moshkopp** [comment]
Can confirm it, same behavior here

**Comment by doudz** [comment]
Additionnally where comparing years, January of previous year is missing !
2023 vs 2022
![image](https://user-images.githubusercontent.com/1262548/222543584-606e56dd-a106-4a33-9b8c-d233fa8356a6.png)

2022
![image](https://user-images.githubusercontent.com/1262548/222543641-9bdf1df8-fd37-4768-b1f4-909fade7099d.png)

**Comment by doudz** [comment]
up
