### ISSUE TITLE
trigger.from_state.state in state-trigger using entity+attribute gives wrong value

### ISSUE THREAD

**Issue by RichardvanGestel** [home-assistant/frontend#15426]
Unfortunately I can't find a better place for my problem...excuse me.

### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

this script:
alias: tijdelijk
description: ""
trigger:
  - platform: state
    entity_id:
      - climate.speelkamer
    attribute: current_temperature
condition: []
action:
  - service: input_text.set_value
    data:
      value: "{{ (trigger.from_state.state) }} "
    target:
      entity_id: input_text.tijdelijk
mode: single

gives the value of clime.speelkamer but not the value of current_temperature

### Describe the behavior you expected

I expected to get the current_temperature

### Steps to reproduce the issue

create the automation and wait until the temperature of climate.speelkamer changes.

### What version of Home Assistant Core has the issue?

Home Assistant 2023.2.3 Supervisor 2023.01.1 Operating System 9.5 Frontend 20230202.0 - latest

### What was the last working version of Home Assistant Core?

?

### In which browser are you experiencing the issue with?

_all

**Comment by karwosts** [comment]
Try `value: "{{ (trigger.from_state.attributes.current_temperature) }} "`

**Comment by RichardvanGestel** [comment]
Thank you very much! I tested it and it works!
