### ISSUE TITLE
Unable to remove unit of measurement in Picture Elements Card, State Label

### ISSUE THREAD

**Issue by chrismaki** [home-assistant/frontend#15455]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using a state-label to overlay sensor data on a picture element card, it is not possible to exclude the unit of measurement. Specifically, for _sensor.indoor_temperature_ provided by my Daikin One+ thermostat, the element's state value is the current temperature with one decimal. It also has four attributes:
unit_of_measurement
device_class
icon
friendly_name

When entering the YAML for this specific label, as the UI starts to auto-complete the name of the sensor, it also shows the current state value and there is no suffix displayed. Once there is enough YAML to display the data on the dashboard, it includes the unit_of_measurement and there's no way that I have found to remove this natively although there does exist a way to add suffixes (ie: suffix: ).

I have confirmed this shortfall exists for other entities that have a _unit_of_measurement_ attributes, including input_numbers and energy sensors.

### Describe the behavior you expected

I would expect that the displaying of a suffix should be a choice, failing that I would hope there is an option, possibly within _style:_ to remove it or truncate a certain amount of characters.

### Steps to reproduce the issue

1. Deploy a Picture Card Element
2. create a state label for an entity with a numeric state value and a unit_of_measurement attribute
3. profit
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.2.3

### In which browser are you experiencing the issue with?

Google Chrome	109.0.5414.119

### Which operating system are you using to run this browser?

Ventura 13.1

### State of relevant entities

```txt
Entity has numeric state value with the following attributes:

unit_of_measurement
device_class
icon
friendly_name
```

### Problem-relevant frontend configuration

```yaml
type: picture-elements
elements:
  - type: state-label
    entity: input_number.library_target_temperature
    style:
      top: 50%
      left: 85%
image: local/images/Level01-4pm-c.png
```

**Comment by geoffbon** [comment]
I'm also hitting this same issue, and the existing workarounds all seem to be messy.  Would be great to have this.

**Comment by ildar170975** [comment]
@geoffbon 
No sense to post here; suggest to open a new issue.

**Comment by geoffbon** [comment]
@ildar170975 would it not be better to just reopen this issue that exactly describes the problem?

**Comment by ildar170975** [comment]
@geoffbon 
> would it not be better to just reopen this issue

Probably you are right; please ask someone of Dev team to reopen.

**Comment by chrismaki** [comment]
@bramkragten @balloob @homeassistant Can someone please re-open this issue?

**Comment by rjp** [comment]
Can confirm this is still a problem in 2024.8.2
