### ISSUE TITLE
state of Stookwijzer integration is translated to English (while config is set to Dutch)

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#15451]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

as title.
Even though the dev tools states is actually showing Dutch too (should that state really be 'rood' and not be English 'red' as system language)

<img width="1051" alt="Scherm­afbeelding 2023-02-14 om 17 22 13" src="https://user-images.githubusercontent.com/33354141/218870480-86b375ca-b423-4f2d-afb6-7ebc2319179f.png">

frontend shows 'Red'

<img width="512" alt="Scherm­afbeelding 2023-02-14 om 22 52 44" src="https://user-images.githubusercontent.com/33354141/218871596-cd3b6d52-4179-42b9-ad6d-a8c285cd20c7.png">

### Describe the behavior you expected

Have the Frontend show 'Rood' which would be the capitalized state

### Steps to reproduce the issue

1. install Stookwijzer 
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.2.4

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

Ventura 13.2

### State of relevant entities

<img width="931" alt="Scherm­afbeelding 2023-02-14 om 22 50 13" src="https://user-images.githubusercontent.com/33354141/218871200-8ca8c0a4-c1f9-430f-871c-bbabbd972bc2.png">

### Problem-relevant frontend configuration
```
type: entities
title: Weer waarschuwingen
state_color: true
entities:
  - sensor.stookwijzer
```

**Comment by frenck** [comment]
This means the Dutch translation isn't available yet.

The lower caps states you see like `rood` are the raw states, what you see in the UI are the translations "Red". Someone has to translate "Red" into "Rood" (as English is our translation source).

THis might have been done at this point, if so, it would end up in the next release, if not, feel free to contribute a translation.

Read more about contributing to translations here:

<https://developers.home-assistant.io/docs/translations>

../Frenck

**Comment by Mariusthvdb** [comment]
will check.
shouldnt the states themselves be in English though? given the fact all core coding is, it is somewhat surprising these states are enumerated in Dutch

**Comment by frenck** [comment]
> shouldnt the states themselves be in English though

Nope, state represents the raw state of a device or service.
