### ISSUE TITLE
Hard to adjust multiple statistics values

### ISSUE THREAD

**Issue by junior013** [home-assistant/frontend#15489]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I adjust a statistics value in developer tools, the "Adjust" button closes the popup windows, and for another value I need to start over from pick date, time, etc.

### Describe the behavior you expected

After "Adjust" go back to the date/time picker pop-up with the same list. (like "Back" button does without saving the new value)

### Steps to reproduce the issue

1. Go to Developer Tools -> Statistics
2. Select an entity and press the "Adjust" button at the end of the line
3. Set a date and time and pick a timeslot value from the list
4. Modify the value in the new pop-up window and apply it with the "Adjust" button
...now modify the next timeslots value!

### What version of Home Assistant Core has the issue?

core-2023.2.5

### What was the last working version of Home Assistant Core?

none

### In which browser are you experiencing the issue with?

Google Chrome 109.0.5414.120

### Which operating system are you using to run this browser?

HassOS 9.5

**Comment by ildar170975** [comment]
up
