### ISSUE TITLE
UI gets unresponsive for some mobile devices when swiping backwards

### ISSUE THREAD

**Issue by jjmonteiro** [home-assistant/frontend#15507]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Some Samsung and Pixel users are reporting that using swipe gestures to navigate backwards on the UI will cause the frontend cards and buttons to become unresponsive.

The issue can be also reproduced when using the Chrome web browser and doesn't seem to matter what side of the screen is used to back-swipe.

The solution is then swipe up/down or open/close the left panel to go back to normal.

Details can be found in this [Reddit post](https://www.reddit.com/r/homeassistant/comments/115llg1/ui_issues_on_galaxy_s20/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button) 

### Describe the behavior you expected

Navigating the UI using back swipping gestures should behave exactly as pressing the back button.

### Steps to reproduce the issue

1. Open the left pane
2. Swipe backwards to close
3. Notice the UI top buttons and cards get unresponsive 
4. Swipe up/down to recover
...

### What version of Home Assistant Core has the issue?

2023.2.5

### In which browser are you experiencing the issue with?

Chrome 110.0.5481.65

### Which operating system are you using to run this browser?

Android 13

**Comment by skandalfo** [comment]
Seeing the same on 2023.5.0 on Chrome and the Android companion app on a Pixel 6.

Sometimes you can just click three times on the back button to make it work, others you need to click/scroll the view vertically to make the button work again.
