### ISSUE TITLE
Gauge card Define Severity behaviour

### ISSUE THREAD

**Issue by fredd589** [home-assistant/frontend#15538]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When toggling Define Severity? on a gauge card that has the severity already defined, the gauge preview goes full red, then full blue - rather than defining the severity.

### Describe the behavior you expected

I expect the gauge card preview to update to show the defined severity, rather than a full red or blue bar

### Steps to reproduce the issue

1. Create a gauge card that has severity defined, and come out of the edit window.
2. Edit the card again, and toggle ' define severity' 
3.  Notice how the preview on the right does not update correctly.
4.
...

### What version of Home Assistant Core has the issue?

2023.2.5

### What was the last working version of Home Assistant Core?

NA

### In which browser are you experiencing the issue with?

109.0.5414.119

### Which operating system are you using to run this browser?

10.13.6 (17G14042)

### State of relevant entities

```txt
I am using a numeric sensor with a degree's c value
```

### Problem-relevant frontend configuration

```yaml
type: gauge
entity: sensor.water_tank_temperature
needle: true
severity:
  green: 37
  yellow: 22
  red: 0
min: 15
max: 45
name: Water heater capacity
```

### Javascript errors shown in your browser console/inspector

```txt
None
```

### Additional information

NA

**Comment by karwosts** [comment]
Seems to work as expected for me. 

The first time you toggle severity from on->off, the gauge turns blue, because a gauge with no severity defined is blue. 

If you toggle severity back on again, the red/yellow/green values are all 0. So I guess this is sort of undefined behavior when they all have the same value, but once you enter new severity values, it should work as expected.
