### ISSUE TITLE
Rework ha-form boolean subtype to allow for helpers to be displayed

### ISSUE THREAD

**Issue by kaechele** [home-assistant/frontend#15536]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

As described in https://github.com/home-assistant/frontend/pull/14165#issuecomment-1362211618 the boolean subtype for `ha-form` currently does not render a helper.

As requested by @steverep this is the issue to track this.

### Describe the behavior you expected

A helper is rendered under the boolean form element.

### Steps to reproduce the issue

1. Access a form (eg. in a config flow) where `data_description` is defined for `data` elements.
2. No helper will be rendered if the schema type for a field is `bool`.

### What version of Home Assistant Core has the issue?

core-2023.3.0.dev0

**Comment by elupus** [comment]
This is still fully valid.
