### ISSUE TITLE
Opening or saving an Automation with a timer.start can corrupt duration argument

### ISSUE THREAD

**Issue by eric** [home-assistant/frontend#15554]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Visual Editor is causing template values for the `duration` of a `timer.start` to become `[object Object]` instead of not allowing the Visual Editor to work at all.

### Describe the behavior you expected

I expected the Visual Editor to no longer be allowed.

### Steps to reproduce the issue

1. Open or create an Automation or Script
2. Add a Service Call to "timer.start"
3. Edit the yaml for the Service call to:
```
data:
  duration: {{ 5 }}
```
4. Change to Visual Editor
5. Change back to YAML editor

### What version of Home Assistant Core has the issue?

2023.2.5

### Additional information

![screenshot-2023-02-22-11 09 01@2x](https://user-images.githubusercontent.com/470/220733910-ba5d116b-af90-4631-b5d9-2afe2038d863.png)
![screenshot-2023-02-22-11 09 06@2x](https://user-images.githubusercontent.com/470/220733949-7ac0311e-f125-482b-9e11-a6e461c32e60.png)
![screenshot-2023-02-22-11 09 10@2x](https://user-images.githubusercontent.com/470/220733975-51f5927a-d243-4bd9-a0ab-604eeb0bf766.png)

**Comment by karwosts** [comment]
For what it's worth you're missing quotes around your template. If you had `duration: "{{ 5 }}"` you would get the warning you are expecting about visual editor not supported for templates. Without the quotes, I'm not sure what that syntax means, but I don't think it's something that's caught.

**Comment by eric** [comment]
Ah! Thank you for the explanation!
