### ISSUE TITLE
zwave.js UI update to 1.6.3

### ISSUE THREAD

**Issue by stefpeeters** [home-assistant/frontend#15559]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Upgrade zwave.js UI from 1.6.2 to 1.6.3 will result in : setup none in the device section
Zwavejs UI is fully functional, zwave addon is working, but no longer available in the Home Assistant UI
A system reboot did not solve the issue, supervisor repair didn't fix the issue.
Restore the previous configuration 1.6.2 did not solve the issue. I had to restore a full backup to get it working again

### Describe the behavior you expected

As usual, zwave integration fully working

### Steps to reproduce the issue

1. upgrade to 1.6.3
2. restart Home Assistant
3. Zwave addon in the device section stating "Setup: None"
...

### What version of Home Assistant Core has the issue?

2023.2.5

### What was the last working version of Home Assistant Core?

2023.2.5

### In which browser are you experiencing the issue with?

110.0.5481.104

### Which operating system are you using to run this browser?

Windows 11

**Comment by frenck** [comment]
This is not a frontend issue, please file an report in the Core issue tracker if you experience integration issues.

Thanks 👍 

../Frenck
