### ISSUE TITLE
New areas are not shown in the device page

### ISSUE THREAD

**Issue by luca-angemi** [home-assistant/frontend#15562]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Create new areas and try to assign a device to any of them.

### Describe the behavior you expected

Being able to select the new area.

### Steps to reproduce the issue

1. Create an area
2. Go to a device page
3. Add the device to the recently createad area.

No areas are found even after a system restart

![image](https://user-images.githubusercontent.com/9977955/220907665-357e53a9-fa1d-41a2-a8e4-79c5512bab8f.png)

This error appears in the console.

![image](https://user-images.githubusercontent.com/9977955/220907401-ed53b35e-f2fa-4da4-80f5-3af5597ccd37.png)

### What version of Home Assistant Core has the issue?

2023.3.0b0

### In which browser are you experiencing the issue with?

Chrome 110

### Which operating system are you using to run this browser?

Windows 10

**Comment by frenck** [comment]
I've reproduced this issue, by trying to create an area directly from the area selector.
