### ISSUE TITLE
Lock Attributes Bug Fix

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#15568]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Look at the Attributes
![image](https://user-images.githubusercontent.com/42905545/220938493-5c2959da-220b-472e-9d6f-759376f5f6aa.png)

### Describe the behavior you expected

*

### Steps to reproduce the issue

*

### What version of Home Assistant Core has the issue?

Beta

**Comment by piitaya** [comment]
I just tested on an older version and I have the same issue. Can you confirm this bug was present before the beta ?

**Comment by milandzuris** [comment]
> 

no sorry
