### ISSUE TITLE
View locks after setting precision

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#15563]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

somehow I have to constantly reload the page view in Safari Mac to be able to scroll vertically 
its reproducible by clicking an entity, open more-info, change precision, click Update, and get stuck

### Describe the behavior you expected

non lock 

### Steps to reproduce the issue

1. as described above
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.3 beta 0

### In which browser are you experiencing the issue with?

Safari Mac

### Which operating system are you using to run this browser?

Ventura 13.2

**Comment by Mariusthvdb** [comment]
Ive just noticed this to happen also after clicking the new Restart button. Window freezes.

**Comment by dreimer1986** [comment]
And after doing a entity search in Dev Settings.
