### ISSUE TITLE
Entities of UI created light groups not shown in new more-info

### ISSUE THREAD

**Issue by Wesley-Vos** [home-assistant/frontend#15560]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The new more-info pop-up has the great feature that the individual lights of a light group are shown below the group toggle.

### Describe the behavior you expected

However, this is not the case for light groups that are created through the UI in the helper section. Those ‘child’ entities are not shown below the group toggle. I expected this to work for UI created groups as well.

### Steps to reproduce the issue

1. Open HA, go to Settings > Devices & Services
2. Open the ‘Helpers’ tab
3. Click on ‘Create helper’ > Group > Lightgroup
4. Give it a name and add at least two entities
5. Do not check the ‘Hide entities’ toggle
6. Click on ‘Save’ (or ‘Submit’, don’t know the English translation)
7. Click on the recently created helper to open the more-info pop-up
8. Observe that the child entities are not shown below the main toggle

### What version of Home Assistant Core has the issue?

core-2023.3.0b0

### In which browser are you experiencing the issue with?

Not browser related

### Which operating system are you using to run this browser?

iOS Companion but not OS related

### State of relevant entities

```txt
effect_list:
  - blink
  - breathe
  - channel_change
  - finish_effect
  - okay
  - stop_effect
supported_color_modes:
  - brightness
  - onoff
entity_id:
  - light.bank
  - light.lantaarns
icon: mdi:lightbulb-group
friendly_name: Woonkamer
supported_features: 44
```

**Comment by bramkragten** [comment]
For a light group, we never show the members of a group. It is handled as just another light

**Comment by Wesley-Vos** [comment]
Ahh okay but for a group of lights created in the YAML Config we do show them, which is kind of confusing. Maybe we can also show the members of a light group depending on the ‘Hide members’ toggle? Because if the hide members toggle is off, the members are still enabled and the group is in the end just a light with the same behaviour as a group configuration in YAML

**Comment by bramkragten** [comment]
That is a group entity, it is a completely different thing and unrelated to YAML, you can also create a light group in YAML.

I think your request is to add the creation of group entities to the UI?

**Comment by Wesley-Vos** [comment]
I released that I'm mixing up two different scenarios, so let me try to rephrase it.

If I'm checking the [Group page]( 
https://www.home-assistant.io/integrations/group/] on the home-assistant.io docs, I notice that there are two different styles to create a group.

First of all, the platform dependent way, where in YAML you use `platform: light` inside a root-level `light` object or you create it through the helper section. This creates entities like `light.` and do not show-up as groups in the more info pop-up.

There is also a second way, which is referred to as old and 'do not use'. This is the root-level `group` object in which you setup specific domains like `light`. This config can only be created through YAML and creates entities with ids like `group.`. The members of those entities do show-up as groups in the more info pop-up.

So in the end, I'm concluding that only old, deprecated group's member entities will show up in the more info pop-up resulting in different frontend interactions depending on which style you use for the same integration.

Hope that this makes the point a bit clearer.

**Comment by holymountain92** [comment]
I'm also really looking forward to this functionality. I really like the new design of the lights, the more info etc but a major flaw at this moment is that the groupmembers that are created through group helpers don't appear in the more info. So when I create a group of lights through the helper, it doesn't show the members of the group when enabling the light group which doesn't allow me to change individual lights in a group.

This feature was on the milestone plan for 2023.3, will it be moved to 2023.4?

**Comment by danielo515** [comment]
This not only affects the light groups. Groups of other entities created using the UI have the same behavior, while regular groups created in Yaml do not.
For example, groups of motion sensors show the global state and the state of individual entities within the group. This is very useful for debugging scenarios where you have multiple sensors be part of a group to know which one needs adjusts or which one is not triggering.

**Comment by slashbv** [comment]
I also want to have the ability to see and turn on off individual members of the group. By the way what is "Hide members" in group setting is supposed to do? I was assuming it is doing just that, hiding or showing group members, but for me it seems it does nothing. 
![image](https://user-images.githubusercontent.com/59421121/232712041-22eebf4b-47d7-48c3-bbb5-927a326c4dd3.png)

**Comment by eric10k93** [comment]
Any status on this?  I started migrating to light groups forever ago, but stopped doing it when I realized the behavior of the new groups is to not show the member entities.  The old group method was much better in that regard.  So I have been hoping this behavior would be fixed.

**Comment by holymountain92** [comment]
I’ve worked my way around this issue. I’m working a lot with auto-entities as I want it to be scalable and found the solution today (after I did some careful reading).

I’ve created light groups through the UI and have those filtered with https://github.com/thomasloven/lovelace-auto-entities. On top of this I’m using a pop -up card with browser_mod https://github.com/thomasloven/hass-browser_mod. On a tap/hold action I open up the pop-up card which is populated with the lights from the group which is clicked from the auto-entity group, this is made possible by the functionality this.entity_id. Up till now I didn’t know about this functionality and this has made me to solve this, as it is fully scalable now.

On top of the above I’ve used https://github.com/piitaya/lovelace-mushroom to make the layout nice and shiny and the added value of this is that you can fully customize the look and feel together with the interaction as you’re not tied to the ‘more-info’ menu.

The code I’ve used in my card, the trick is to use the right filters for your situation.

`type: custom:auto-entities
card:
  type: grid
  columns: 2
  square: false
card_param: cards
filter:
  include:
    - domain: light
      entity_id: /group/
      options:
        type: custom:mushroom-light-card
        use_light_color: true
        show_brightness_control: true
        show_color_control: false
        collapsible_controls: false
        show_color_temp_control: true
        fill_container: true
        layout: horizontal
        hold_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              title: ' '
              content:
                type: custom:auto-entities
                card:
                  square: false
                  columns: 1
                  type: grid
                filter:
                  include:
                    - group: this.entity_id
                      options:
                        type: custom:mushroom-light-card
                        use_light_color: true
                        show_brightness_control: true
                        show_color_control: true
                        collapsible_controls: false
                        show_color_temp_control: true
                        fill_container: false
                        layout: horizontal
                        hold_action:
                          action: more-info
                sort:
                  method: name
                show_empty: true
                card_param: cards
  exclude: []
show_empty: true
`

**Comment by eric10k93** [comment]
This should not be stale, as it has not been resolved.  The old method of setting up groups from yaml allows you to see all entities within the group in the UI.  The current UI method of setting up groups hides all the entities that are part of the group.  The only way to see the entities that are part of the group is to enter the 'configuration' page for the created group.

**Comment by eric10k93** [comment]
> I’ve worked my way around this issue. I’m working a lot with auto-entities as I want it to be scalable and found the solution today (after I did some careful reading).
> 
> I’ve created light groups through the UI and have those filtered with https://github.com/thomasloven/lovelace-auto-entities. On top of this I’m using a pop -up card with browser_mod https://github.com/thomasloven/hass-browser_mod. On a tap/hold action I open up the pop-up card which is populated with the lights from the group which is clicked from the auto-entity group, this is made possible by the functionality this.entity_id. Up till now I didn’t know about this functionality and this has made me to solve this, as it is fully scalable now.
> 
> On top of the above I’ve used https://github.com/piitaya/lovelace-mushroom to make the layout nice and shiny and the added value of this is that you can fully customize the look and feel together with the interaction as you’re not tied to the ‘more-info’ menu.
> 
> The code I’ve used in my card, the trick is to use the right filters for your situation.
> 
> '''

@holymountain92 
Any chance you could share a formatted version of your code?  I started pasting your snippet to YAML, but it's kinda a PITA to figure out all the proper spacing.  I'd like to play around with your workaround, as it sounds like it could be quite useful.

**Comment by melyux** [comment]
Can an admin reopen this?

**Comment by zsostaric** [comment]
Can this be reopened? I'm having the same issue
