### ISSUE TITLE
No "All hardware" menu (or hamburger menu) in Hardware submenu

### ISSUE THREAD

**Issue by nepozs** [home-assistant/frontend#15578]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Settings -> System -> Hardware -> only new "Restart Home Assistant" menu, no possibility to reach "All hardware"

![No_all_hardware_here_2023-02-23_22-12](https://user-images.githubusercontent.com/56661567/221031581-e1a9e6b6-6f28-4248-93a0-4405adc04f2f.png)
![No_all_hardware_here2_2023-02-23_22-12](https://user-images.githubusercontent.com/56661567/221031600-144ff8d1-ba1a-46b7-bf8d-90a2e1d46279.png)

### Describe the behavior you expected

Settings -> System -> Hardware -> some kind of menu with "all hardware"

like old "hamburger menu"
![old_good_hamburger_menu_2023-02-23_22-08](https://user-images.githubusercontent.com/56661567/221031815-58d17c51-3ed5-4919-b774-1a659d2f05e4.png)

### Steps to reproduce the issue

1. Update to Home Assistant 2023.3.0b0

### What version of Home Assistant Core has the issue?

core-2023.3.0b0

### What was the last working version of Home Assistant Core?

core-2023.2.5

### In which browser are you experiencing the issue with?

not browser related

### Which operating system are you using to run this browser?

Win11, Android6, Adroid12

### State of relevant entities

```txt
## System Information

version | core-2023.3.0b0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.90
arch | x86_64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.30.1
Stage | running
Available Repositories | 1227
Downloaded Repositories | 82

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | pending
can_reach_cloud | pending

</details>

<details><summary>GIOŚ</summary>

can_reach_server | pending
-- | --

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | beta
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 58.0 GB
disk_used | 20.0 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.5.0), SSH & Web Terminal (13.0.2), ZeroTier One (0.16.0), Mosquitto broker (6.1.3), Zigbee2MQTT (1.30.1-1), Tasmota Device Manager (2022.6.0), HDD Tools (1.1.0), Z-Wave JS UI (1.6.3), Scrutiny (Full Access) (2ab714f5-ls35-2), ESPHome (2023.2.4), FTP (4.6.2), MQTT Explorer (browser-1.0.1), Glances (0.17.2), motionEye (0.18.0), Samba share (10.0.0), VLC (0.1.3), Tailscale (0.7.0), CUPS Print Server (2.0.2), go2rtc (1.2.0), Matter Server (4.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 42
views | 26
mode | storage

</details>

<details><summary>NextDNS</summary>

can_reach_server | pending
-- | --

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 14, 2023 at 13:31
-- | --
current_recorder_run | February 23, 2023 at 13:54
estimated_db_size | 1106.21 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Sonoff</summary>

version | 3.4.0 (5406fa7)
-- | --
cloud_online | 0 / 0
local_online | 0 / 0

</details>

<details><summary>Żadnego Ale</summary>

can_reach_server | ok
-- | --

</details>
```

**Comment by piitaya** [comment]
Hi 👋
The button has been moved to the hardware card. Unfortunately, there is a bug in your case so I pushed a fix for that.

<img width="634" alt="CleanShot 2023-02-23 at 22 50 27@2x" src="https://user-images.githubusercontent.com/5878303/221038471-e28efcab-ae50-4385-a491-26d4c82f3c0a.png">
