### ISSUE TITLE
Z-Wave Device configuration dialog is truncated

### ISSUE THREAD

**Issue by joe-colorado** [home-assistant/frontend#15580]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![image](https://user-images.githubusercontent.com/60592288/221081360-fc741e65-4147-471f-a924-aa0560ae1615.png)

The dialog for the device configuration does not show the parameters properly.
This happens only on the PC. On the Android phone it looks correct.
There is no way to set the auto turn on or turn off parameters on the PC

### Describe the behavior you expected

![Screenshot_20230223_200111_Home Assistant](https://user-images.githubusercontent.com/60592288/221081676-a27aa691-9c4e-49cc-b38a-23afa471afb6.jpg)

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.2.5

### What was the last working version of Home Assistant Core?

probably never worked correctly

### In which browser are you experiencing the issue with?

Version 110.0.5481.104 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 Enterprise

**Comment by karwosts** [comment]
This dialog was redesigned a few versions ago and it looks very different now. Are you sure you really cleared your browser cache? Can you try another browser? 

The new dialog looks like this, your screenshot looks exactly like the issue I remember from a few months ago. 

![image](https://user-images.githubusercontent.com/32912880/221083082-750915b9-51fe-4553-9b52-cb0eadb1c50d.png)

**Comment by joe-colorado** [comment]
Thank you for the quick response.  I cleared the cache a couple of days ago and tried MS Edge today.  No differenceSent from my Galaxy
-------- Original message --------From: karwosts ***@***.***> Date: 2/23/23  20:13  (GMT-07:00) To: home-assistant/frontend ***@***.***> Cc: joe-colorado ***@***.***>, Author ***@***.***> Subject: Re: [home-assistant/frontend] Z-Wave Device configuration dialog is truncated (Issue #15580) 
This dialog was redesigned a few versions ago and it looks very different now. Are you sure you really cleared your browser cache? Can you try another browser?
The new dialog looks like this, your screenshot looks exactly like the issue I remember from a few months ago.
