### ISSUE TITLE
Display Precision adjustments not reflecting on cards

### ISSUE THREAD

**Issue by chicknlil** [home-assistant/frontend#15582]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Changing the display precision via settings is not being reflected on the actual cards. (see screenshots)

### Describe the behavior you expected

Cards to adjust to reflect the correct precision level, which they were doing the last time display precision was (briefly) implemented...last month? I think it was last month.

### Steps to reproduce the issue

1. On dashview, click on a card with a item that has something where display precision can be applied.
2. Click the settings (gear) icon to bring up the settings, including display precision.
3. Adjust the display precision to your preference
4. Update and back out of settings.
5. Check card for changes (in this case, no changes have been applied).

### What version of Home Assistant Core has the issue?

core-2023.3.0b1

### In which browser are you experiencing the issue with?

Microsoft Edge 110.0.1587.50 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11 Home 22623.1325

### Additional information

![image](https://user-images.githubusercontent.com/100124187/221178596-9dc20400-0616-42a8-83d5-9a9b768103de.png)

![image](https://user-images.githubusercontent.com/100124187/221178717-cd646bb9-aee1-4f50-8619-b6e8edc66281.png)

**Comment by chicknlil** [comment]
Nope, as indicated, I tried clearing cache etc, restarting, using different browsers (latest version of Brave as well as companion app on phone) and issue persists.

**Comment by karwosts** [comment]
Tried other card types, other entities? Does it work for any of them? I see a tile card, any other card types you tried?

This feature is working for me, so just trying to guess what might be different in your case.

**Comment by chicknlil** [comment]
It does display properly with a "regular" entity card, so I guess I need to hook in with the mushroom folks to make them aware this is an issue with the mushroom cards.

**Comment by kuges** [comment]
I've got a number of custom cards like this. I wonder if it would be possible for the precision setting to apply globally to the entity state value?
