### ISSUE TITLE
Riemann sum not displaying method

### ISSUE THREAD

**Issue by Frankster-NL** [home-assistant/frontend#15592]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If you have created a Riemann Sum sensor via settings -> helpers there is no way to see which method you used (left, right, trapezoidal). By clicking the "Riemann sum options" you can only change the amount of decimals, but I would expect to also see the method.

### Describe the behavior you expected

I would have expected that in the frontend you would also be able to see the Riemann Summ method

### Steps to reproduce the issue

1. Create a Riemann sum sensor through UI
2. Click the Riemann sum sensor

### What version of Home Assistant Core has the issue?

Home Assistant 2023.2.5

### In which browser are you experiencing the issue with?

Google Chrome 110.0.5481.105 (Officiële build) (64-bits)

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment]
I don't think this is something that frontend can control. The riemann integration defines what options are available in config_flow (initial setup), and options_flow (post-setup click on entity settings). 

I've seen a few issues related to this, I wish there were more options too, but I think the issue has to be logged against core for the 'integration' component.

**Comment by karwosts** [comment]
Also duplicate of #14066
