### ISSUE TITLE
Motion Blinds discovering incorrect devices

### ISSUE THREAD

**Issue by gourdo1** [home-assistant/frontend#15594]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Motion Blinds integration insists that I have many Motion Blinds devices in my environment, despite not having any. In fact, many of the devices it says I have are already tied to ESPHome or other integrations. The integration's [manifest.json](https://github.com/home-assistant/core/blob/dev/homeassistant/components/motion_blinds/manifest.json) suggests that it will match a few hostnames with some wildcards (like motion_\*, brel_\*, connector_*), but none of my devices fit these patterns.

I can ignore specific devices, but over time, it finds more and more devices, all of which are actual IPs in my environment, but are not motion blinds. I would disable the integration altogether, however, I can't seem to do that because I don't have a motion blind that would allow me to access an integration card to disable it in the first place.

<img width="1505" alt="Screenshot 2023-02-25 043726" src="https://user-images.githubusercontent.com/13145881/221357165-6d553d4c-d88c-47a4-ae69-e4d91ecdd534.png">

### Describe the behavior you expected

I expect the motion blinds integration not to falsely discover devices.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.2.5

### In which browser are you experiencing the issue with?

Firefox 110

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
Integration specific behaviors need to be reported to home-assistant/core repository, not the frontend. I would suggest to move this there.
