### ISSUE TITLE
Sun triggers don't work if offset is default

### ISSUE THREAD

**Issue by williamsdyyz** [home-assistant/frontend#15601]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

A new automation with a Sun trigger never runs.

### Describe the behavior you expected

I would expect the automation to run at sunrise every day.

### Steps to reproduce the issue

1. Using the UI (not the YAML editor) create a new automation with a Sun trigger & save. The YAML will look like this. Note that offset is a number:
```
platform: sun
event: sunrise
offset: 0
```
2. Add a simple action to turn on a light & save.

3. This automation will never run.
4. Edit the automation with the UI, change the offset to 00:01:00 and save. The YAML will look like this. Note that offset is a string:
```
platform: sun
event: sunrise
offset: "00:01:00"
```
5. The automation will now run correctly

Note that

### What version of Home Assistant Core has the issue?

2023.2.5

### In which browser are you experiencing the issue with?

Chrome 110.0.5481.178, FireFox 110.0, ...  - it's not a browser issue

### Which operating system are you using to run this browser?

Windows 11

### Additional information

I *think* the problem is caused by a couple of things

- The interface for `SunTrigger` is wrong - `offset` is defined as a number when it should be a string
- The `defaultConfig` for the `HaSunTrigger` element is also wrong - it sets offset to 0 when it should be "" (or maybe undefined?)

My Python is a bit sketchy so I haven't been able to figure out how the backend handles offsets but it seems that string values are correctly handled but numeric values are not.

**Comment by karwosts** [comment]
I'm not seeing the same problem you are, `offset: 0` works fine for me. Tested in 2023.2.5.

![image](https://user-images.githubusercontent.com/32912880/221466417-c0546cac-288c-4ad6-980e-f02875728519.png)
