### ISSUE TITLE
Timer helper bug

### ISSUE THREAD

**Issue by figorr** [home-assistant/frontend#15602]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have several timers I created using the helpers.  I didn't see the following bug at Home Assistant 2023.2.4, the bug started with HAS 2023.2.5.

The bug is the following one:

I start any of the timers and the card is showing 13 seconds less than the time that was set in the timer.

For example ... If I set a timer for 1h ... the timer starts at 59:47 ... and once the timer arrives to 00:00 it is shown as "active" during 13 more seconds untils it becomes to idle.

The curious thing ... if I paused the timer while it is running... the timer shows the correct time as paused ... So if I paused the timer when the card shows 59:05 ... then the card ... is showing 59:18 (paused). 

Some pictures to see the issue:

![timer_01](https://user-images.githubusercontent.com/77553975/221422524-f9267df5-ed9e-49c0-badd-ea06b3bd7018.jpg)
![timer_02](https://user-images.githubusercontent.com/77553975/221422527-5f7cb7de-f7ad-40b3-93dc-7a7a53e77207.jpg)
![timer_03](https://user-images.githubusercontent.com/77553975/221422529-60c0c8f3-9d20-4b43-9f8f-fb845415df30.jpg)
![timer_04](https://user-images.githubusercontent.com/77553975/221422530-7654aad0-5a72-4901-9ed3-b326b7f7f807.jpg)

Very weird.

### Describe the behavior you expected

The behaviour was correct in previous versions.

The timer seems to work properly, but the time is not being shown correctly.

### Steps to reproduce the issue

1. Start the timer ... and It will start showing 13 seconds less than the time that it was set at the timer.
2. If you pause the timer ... the timer will show the correct time remaining (so the time that it is being shown until the pause + 13 seconds)
3. If you continue the timer after the pause ... then it will start with 13 seconds less than the paused time.
...

### What version of Home Assistant Core has the issue?

2023.2.5

### What was the last working version of Home Assistant Core?

2023.2.4

### In which browser are you experiencing the issue with?

Google Chrome 110.0.5481.177 (Build oficial) (64 bits)

### Which operating system are you using to run this browser?

Windows 10 Pro

**Comment by figorr** [comment]
Strange behaviour, but after a restart of HA … timers are being shown OK again at the frontend.

**Comment by figorr** [comment]
Sorry, but it is not really solved.

I restarted HA and I tried the timers through the IOS app, and they are shown OK at the app.

But when I checked the timers under Google Chrome and Firefox ... they are not being shown OK, they are buggy as I described above.

So ... it looks like it is something related to the web explorers.

**Comment by karwosts** [comment]
Mine look fine to me in web browser. Is it possible maybe your PC is a few seconds out of sync with the hass server? Maybe check that the time is the same in both, maybe it's off by a couple seconds.

**Comment by figorr** [comment]
> Mine look fine to me in web browser. Is it possible maybe your PC is a few seconds out of sync with the hass server? Maybe check that the time is the same in both, maybe it's off by a couple seconds.

You are right, there is something wrong with that PC, because I just checked timers in a Mac running Safari and also Chrome and in both cases … the timer is being shown Ok. It is showing the countdown from the start.

The weird thing is that timers are working OK and it is only a visual bug in that PC. Because when the timer arrives at the end in that PC … it continues (it changes from 00:00 to active) and it is shown as “active” during those 13 seconds that were not shown at the beginning of the countdown. Then after of those 13 seconds of being shown as “active” it goes to “idle”.

I will keep the thread open just a couple more of days just for the case I find what is the cause or the solution for this particular issue in that PC. Because in that PC the timers were shown OK just a couple of weeks ago.

**Comment by iMiMx** [comment]
@figorr Now, I'm only seeing/testing on a Mac... and it's not 13 seconds for me, its about 2 minutes 20 seconds.

I also see the weird 'active' state, rather than idle, so timer.finished never fires the event based on the UI countdown.

... it's all very odd.  I see you closed this, so it's no longer impacting you?
