### ISSUE TITLE
Missed "All entities" option in Advanced Group Option (Helpers).

### ISSUE THREAD

**Issue by gfreccia** [home-assistant/frontend#15648]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missed "All entities" option in Advanced Group Option (Helpers).
![Schermata del 2023-03-01 11-49-48](https://user-images.githubusercontent.com/35954627/222118428-fa04ade5-ab21-4c06-a9a5-b952974e330a.png)

### Describe the behavior you expected

This from Home Assistant 2022.11.5 Supervisor 2023.01.1 Frontend 20221108.0 - latest.
![Schermata del 2023-03-01 11-43-26](https://user-images.githubusercontent.com/35954627/222118177-633dfdc3-404f-4fff-852d-8c8c53838aa5.png)
 

### Steps to reproduce the issue

1. Create Helpers ---> Group
2. Edit it
3. Settings ---> Group Options
...

### What version of Home Assistant Core has the issue?

 Home Assistant 2023.2.5 Supervisor 2023.02.dev1502 Frontend 20230202.0 - latest

**Comment by karwosts** [comment]
Is this something related to the language change? I'm on 2023.2.5 and I still see "All entities" toggle in the group options.

**Comment by gfreccia** [comment]
Thanks for answering!
I've just tried to switch to English, but still the same issue.

--
Giacomo Trovato
Email: ***@***.***
Tel: +39 0418623244

Il giorno Mercoledi, Marzo 01, 2023 15:26 CET, karwosts ***@***.***> ha scritto:
 
 
Is this something related to the language change? I'm on 2023.2.5 and I still see "All entities" toggle in the group options.

**Comment by karwosts** [comment]
What type of group is it?

**Comment by frenck** [comment]
Please note, this option is only shown in the UI if you have "Advanced mode" enabled on your user profile.

**Comment by gfreccia** [comment]
Thanks Frenck, you lighted me, "Advanced mode" was disabled!
It works now!

Thanks again!
