### ISSUE TITLE
Dialogs: scrollbars + round borders = imperfection

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#15664]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When a dialog window has a scrolbar, the bottommost part is displayed not nice:

![image](https://user-images.githubusercontent.com/71872483/222267651-13bca8c1-d83c-429b-840f-88126fab01d9.png)

### Describe the behavior you expected

The "down" button should be visible fully.
Probably there must be some padding-bottom.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.3.0

### In which browser are you experiencing the issue with?

Chrome 110.0.5481.178 

### Which operating system are you using to run this browser?

Win10x64

**Comment by olylak** [comment]
It would be even better to have customized scrollbar instead of standard one for all dialogs. 

Like it is here:

![image](https://user-images.githubusercontent.com/3715218/222367929-5b0938e3-5a6a-43ac-bd2a-81ce97a926dd.png)

**Comment by ildar170975** [comment]
One more example - with a Log:

![изображение](https://user-images.githubusercontent.com/71872483/223228573-60b50d00-c0c1-4a0a-acbc-37a470383062.png)

**Comment by christophwen** [comment]
I wanted to look at the issue, but could not reproduce the behavior on the dev branch. There is a possibility that this has already been fixed/resolved differently. For example, long lines in the log details are broken/wrapped into multiple line. If someone can give me more information about this, I would appreciate it.

**Comment by ildar170975** [comment]
HA 2023.4.5:

Any lovelace view -> loupe button:

![изображение](https://user-images.githubusercontent.com/71872483/234360616-6d65166e-4822-416d-8e54-488130585319.png)

Log -> tap on a line (entry must contain long lines):

![изображение](https://user-images.githubusercontent.com/71872483/234360775-03dcecbc-7665-4854-9b2a-a09919ebab30.png)

**Comment by christophwen** [comment]
I tried to find a solution for scrollbar in the dialog window like described in the [M3 Dialog Guidelines -> Scrolling](https://m3.material.io/components/dialogs/guidelines#de17dbd2-7ecf-459e-af95-0f7132a55e40), but I couldn't come up with a good solution, without destroying other the dialogs which use the same component. Maybe somebody with more CSS experience can solve this issue.

**Comment by dnestico** [comment]
I only get scrollbars on the mobile app in the light popups and I agree it looks bad, they should be hidden since its pretty obvious when you can scroll and also doesn't look good.

**Comment by ildar170975** [comment]
As for the initial issue with "New automation" dialog:
probably may be fixed in "src/panels/config/automation/dialog-new-automation.ts":
this style should be added for `.mdc-dialog__surface`:
```
padding-bottom: var(--ha-dialog-border-radius,28px);
```
which causes this look:

![image](https://github.com/home-assistant/frontend/assets/71872483/cfe917f4-f744-476c-8ff3-ff66fea0dafc)

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
Up

**Comment by SVNKoch** [comment]
> It would be even better to have customized scrollbar instead of standard one for all dialogs.

What even is the reason for the different scrollbars? Why not use he custom ones on all dialogs?
I created an issue for android, as there the default scoll bars are not visible (https://github.com/home-assistant/android/issues/4604)


Left: Settings > Devices & Services > Helper > Create Helper
Right: Settings > Devices & Services > Integration > Add Integration
In Firefox on Windows:
![grafik](https://github.com/user-attachments/assets/20a19680-a768-498e-9888-375d19e826cd)

In the Android companion app:
![grafik](https://github.com/user-attachments/assets/4df81cf3-aa40-4752-bc93-acee05b667a7)

**Comment by ildar170975** [comment]
Dev guys, please reopen
