### ISSUE TITLE
The new precision feature does not work at all when Number Format for the user is set to None. Both UI and rounding is broken

### ISSUE THREAD

**Issue by KennethLavrsen** [home-assistant/frontend#15667]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The new precision feature is great  - except it does not work.
But the UI has a small problem
If the value of a sensor happen to be a round number - the UI is not very user friendly in showing the choices in the pull down

See pictures below. Price is close to 2 and rounded off the first 2 decimals are zeros

And EDIT

The feature does not seem to work at all. Nothing happens no matter what value my sensors have

EDIT EDIT

The trigger is that the user has Number Format set to None which is a valid value and one I like to use. See discussion below.
As temporary work around people can set one of the other number formats

### Describe the behavior you expected

The UI should show the zeros after the decimal

Like 
2
2.0
2.00

and not
2
2
2

### Steps to reproduce the issue

Have a sensor with a value that is with zeros like 2.000 or 1.99998
This will show
2
2
2
2
2
1.99998

Should be
2
2.0
2.00
2.000
2.0000
1.99998

Here is an actual example

![image](https://user-images.githubusercontent.com/8373419/222281921-6dd4aa65-8e03-4de6-adb2-94f0c6f46f6e.png)

I even had a sensor where the choices were
2
2
2
2
2
2

### What version of Home Assistant Core has the issue?

core-2023.3.0

### What was the last working version of Home Assistant Core?

new feature

### In which browser are you experiencing the issue with?

Google Chrome

### Which operating system are you using to run this browser?

Windows

**Comment by ildar170975** [comment]
I always see same options:

![image](https://user-images.githubusercontent.com/71872483/222282638-5953e7fa-2ede-4872-b89c-aa602643e940.png)

![image](https://user-images.githubusercontent.com/71872483/222282674-1e1df993-e002-4089-aa4e-3075868c05bc.png)

![image](https://user-images.githubusercontent.com/71872483/222282731-4bc34919-6e02-405c-b775-c79e2f5fb9f9.png)

**Comment by KennethLavrsen** [comment]
It is worse

Even when you have a number with real random decimals the feature does nothing.

This is some sensors where I set the value to 2 decimals. And it ignores it and display the info like it was. It does not append 0. And it does not round off numbers.  I cannot see that this feature works at all

![image](https://user-images.githubusercontent.com/8373419/222284123-d7298817-6b89-4048-a491-b926ab5431fd.png)

**Comment by ildar170975** [comment]
May be it is better to rename it to just "The UI for the new precision feature does not work well" ?

**Comment by ildar170975** [comment]
> And it ignores it and display the info like it was

Confirmed.
Here is a sensor from a standard system monitor integration:
![image](https://user-images.githubusercontent.com/71872483/222286362-8777fbe0-67bb-4b19-bf01-a9e88caabf7e.png)

![image](https://user-images.githubusercontent.com/71872483/222286420-0e87305e-bb07-42e8-927e-5d559b5fb83c.png)

After this:
![image](https://user-images.githubusercontent.com/71872483/222286531-da66b3b5-9f8b-4f16-9b4b-ad03f6a99994.png)

we still get:
![image](https://user-images.githubusercontent.com/71872483/222286574-5a7dc772-e8f6-4b3a-8b14-4ee495733867.png)

**Comment by piitaya** [comment]
Do you have the issue in another browser (mobile)? I'm not able de reproduce it on my browser. 

![image](https://user-images.githubusercontent.com/5878303/222287965-a306270a-956a-4a9a-a682-9fb2f6d5d545.jpeg)

Display precision formatting is done client side so maybe your browser does format it right.

**Comment by KennethLavrsen** [comment]
The feature does not work in Safari on my iPad either. 

And also tried Firefox on Windows. Same problem with the feature now not working at all.

And I am talking about the actual feature not working. The numbers are not rounded no matter what I pick in the UI. In 3 different browsers

**Comment by ildar170975** [comment]
Does not work in my iOS Companion App (iOS 15.x).
Frontend cache was reset.

**Comment by ildar170975** [comment]
Does not work in my iOS Companion App (iOS 15.x).
Frontend cache was reset.

Also checked in FF 110.0.1 (64-bit).

**Comment by KennethLavrsen** [comment]
I tested on a Linux box. All my computers are with English OS and Danish keyboard. My decimal symbol is dot like in English. But I wonder if those that have it working have different locale on their computers. Paul is French. France, Germany and Denmark uses comma for decimal points. Can this influence something?

My locale is setup to be English UK. And with Danish keyboard because I need ÆØÅ to write to Danes

**Comment by ildar170975** [comment]
@KennethLavrsen 
You are genious!

If I use my current settings:
![изображение](https://user-images.githubusercontent.com/71872483/222293238-14740867-cc91-477c-8baf-004ca2eb5386.png)

then I get this:
![изображение](https://user-images.githubusercontent.com/71872483/222293368-261bb9ec-e416-4767-b61b-62b37d1d9f8b.png)

If I set this settings:
![изображение](https://user-images.githubusercontent.com/71872483/222293079-93980df4-d844-4f19-a486-3fedc373baee.png)

I get this:
![изображение](https://user-images.githubusercontent.com/71872483/222293158-72589d3b-ed3d-4e5a-b4cc-a3f5cd0f73af.png)

**Comment by KennethLavrsen** [comment]
Last input before I go to bed. I checked the core entity register and the precision value gets stored correctly when I change it. It just does not do anything in the frontend

**Comment by KennethLavrsen** [comment]
Yes. I just saw the posting before mine.

My number format (which I never noticed before) was set to none. If I set it to Auto - then the feature works. 

So Paul. That should help. I wonder why the None value exist. But you probably need to deal with it somehow.

But it surely works now.  That was a strange one

**Comment by KennethLavrsen** [comment]
Just tried to set the number format to comma and it still works.  It is only the None value that causes the issue.

**Comment by ildar170975** [comment]
> I wonder why the None value exist

I is a very useful option )))
Should not be excluded.
![изображение](https://user-images.githubusercontent.com/71872483/222294358-0610063f-b9af-4cd9-84f9-b099b2ecb1da.png)

**Comment by KennethLavrsen** [comment]
No I see now. It removes the 1000s feature which I prefer not being used. But now that Paul has the info he should also be able to reproduce it and fix it. And if he is sain - he is in bed now (same timezone as I). And now it is bedtime. Good teamwork
