### ISSUE TITLE
Entity Filter showing two scrollbars

### ISSUE THREAD

**Issue by olylak** [home-assistant/frontend#15673]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Entity Filter opened from Overview dashboard shows two scrollbars.

### Describe the behavior you expected

Standard browser scrollbar should not be shown.

### Steps to reproduce the issue

1. Navigate to Overview Dashboard
2. Click Search icon on the top right corner
3. Entity Filter is shown with two scrollbars
4. Close Entity Filter
5. Navigate to the Settings page
6. Navigate back to the Overview Dashboard
7. Click Search icon on top right corner
8. Entity Filter is shown correctly (no default browser scrollbar)
9. Refresh the page to get issue back again

![image](https://user-images.githubusercontent.com/3715218/222364064-e7a16a7f-33f6-4d81-b747-0a90e4193a96.png)

![image](https://user-images.githubusercontent.com/3715218/222365303-4afa1fed-0ff8-4770-b06c-92c257bde0f5.png)

### What version of Home Assistant Core has the issue?

2023.3.0

### In which browser are you experiencing the issue with?

 Google Chrome 110.0.5481.178 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### Additional information

I am able to reproduce it in Microsoft Edge Version 110.0.1587.57 (Official build) (64-bit) as well.

**Comment by ildar170975** [comment]
Seems to be same as https://github.com/home-assistant/frontend/issues/13676 (which was closed as a stale)
