### ISSUE TITLE
Calendar shows wrong time format for lunar phases

### ISSUE THREAD

**Issue by timothybuchanan** [home-assistant/frontend#15685]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have HA time format preference set to 24-hour. All times in automations, cards or elsewhere are in 24-hour with one exception. I use the Google calendar integration. In Google calendar, I have 24-hour set and all times are displayed that way. This includes the phases of the moon. For example, the moon will be full at 0540 on the 7th of March. However, in the HA Calendar, both as a card in Overview and as a separate dashboard, the time is shown as 5:40am.

### Describe the behavior you expected

The time should display in 24-hour format.

### Steps to reproduce the issue

1. Install the calendar integration.
2. In Google, add the Moon Phases calendar.
3. View the calendar in HA.
...

### What version of Home Assistant Core has the issue?

2023.3.0

### In which browser are you experiencing the issue with?

Brave 1.48.171

### Which operating system are you using to run this browser?

windows 11

### Additional information

![google calendar](https://user-images.githubusercontent.com/28636147/222552091-4c03183a-e712-44a7-ab4c-2d86577d84ac.PNG)

![HA calendar](https://user-images.githubusercontent.com/28636147/222552133-26c1f73b-c356-430a-8b95-9716d93de46e.PNG)

**Comment by spacegaier** [comment]
Unless I am interpreting the screenshots incorrectly, the "5:40am" is part of the textual description of the event and therefore not something that HA will interfere with by design.

You would need to look for a way inside Google to have its lunar calendar in 24-hours format so that the event descriptions match what you want to see.

**Comment by timothybuchanan** [comment]
The first screenshot is how it appears on google.com, on the calendar app on my tablet and on my phone. Google calendar is set to use 24 hour format and all events are displayed that way on all my devices except in HA. HA calendar displays events in 24 hour except the moon phases, which display in 12 hour. That's the second screenshot. HA calendar changes the lunar phase time from 24 to 12 hour. Google is already set to use 24 format and it does. It is the HA calendar that changes it to 12 hour and it does this only for the lunar phases.
