### ISSUE TITLE
Number slider bubble / Value not readable in entity detail dialog

### ISSUE THREAD

**Issue by Celphor** [home-assistant/frontend#15684]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In HA 2023.3 the bubble showing the value of a number input slider is too big, So the number value is not readable in an entity detail dialog. It is stll working in Lovelace cards and it also worked for me in HA 2023.2 

See image for better understanding

![image](https://user-images.githubusercontent.com/22246844/222542083-dec799a5-d950-42bd-b0ef-95c92d409316.png)

### Describe the behavior you expected

Readable value

### Steps to reproduce the issue

1. Open any entity dialog for a number slider
2. Move the slider and watch the bubble

### What version of Home Assistant Core has the issue?

Frontend 20230301.0 

### What was the last working version of Home Assistant Core?

latest Frontend 2023.2

### In which browser are you experiencing the issue with?

Chromium 109.0.5414.74 

### Which operating system are you using to run this browser?

Linux

**Comment by EndreOlah** [comment]
Hi,

is anybody working on this? I think it could be solved with a z order setting for the bubble to appear above the rest of the content on the dialog. 

It is a real problem as if in the automation I try to set a value, I need to play until I find the correct value blindly.

Thanks

**Comment by karwosts** [comment]
I poked at it for a half hour but no matter what I did I could not solve it, tried setting overflow, z-index on all the various layers of div between the bubble and the top level, nothing seemed to work for me =\. But I'm not that css experienced. Might have something to do with `position`, not sure.

**Comment by ildar170975** [comment]
@karwosts 
Try this:
![изображение](https://user-images.githubusercontent.com/71872483/226122277-13040681-b238-44b5-90fd-7371d097ef02.png)

**Comment by karwosts** [comment]
Oh neat, that does seem to work. Thanks!

I was lost, kept trying to modify things under <div class="content"> <ha-more-info-info>, <state-card-content> etc, none of those worked. 

I'm very confused what it means for all these divs to exist in their own parallel hierarchies, I don't understand the relationship. 

But this is probably enough of a breadcrumb that I can figure out how to fix it next time I get a chance.

**Comment by ildar170975** [comment]
Alternatively - set `padding-bottom: 32px` to this non-shadowRoot element:
![изображение](https://user-images.githubusercontent.com/71872483/226122899-76b6aebe-6bfc-4ea0-8f28-e6359109bfd4.png)

**Comment by karwosts** [comment]
PR filed.

**Comment by EndreOlah** [comment]
Thanks for the update on this topic. How these developments go into the release? I thought this will be in this newest one, but it is not.

**Comment by ildar170975** [comment]
Even with the [merged PR](https://github.com/home-assistant/frontend/pull/15888) we'll have some clipping.

**Comment by EndreOlah** [comment]
With the earlier version the bubble was not fully visible either, but at least the number was readable to the level that I could see what I am setting. Today the number fully covered. So anything would be better than today. But why the top padding is not a solution, until the number is fully visible?

**Comment by piitaya** [comment]
The fix will be available in the `2023.4` beta release.
We reverted to the previous padding value so the number will be visible and readable but clipped. The number is only visible when using the slider so adding extra padding for a temporary element isn't a good solution. Also, we want to move away from paper UI element because it's unmaintained, we should find a new component that doesn't have this issue.
