### ISSUE TITLE
Found a major bug in automations editor in 2023.3

### ISSUE THREAD

**Issue by Opontios** [home-assistant/frontend#15690]
### The problem

After the 2023.3 (can't say for sure if it was the  2023.3.0 or  the 2023.3.1, because I'm on 2023.3.1 now and don't want to revert back) update when you enter an automation that has a condition of the below type, for example
```
- condition: numeric_state
  entity_id: light.ikea_bulb
  attribute: brightness
  above: 130
```
the "attribute" line disappears if the light is off, so the brightness attribute doesn't exist at that time in the particular entity. And as soon as you enter the automation for editing, even though you haven't done any changes, the "Save" button appears, as if the automation was edited, because from what I can tell, the editor considers that as long as the "attribute: brightness" has been removed, the automation has been altered. If the light is on the "attribute: brightness" is appearing normally and you don't see the "Save" button.

### What version of Home Assistant Core has the issue?

2023.3.1

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Automation

**Comment by frenck** [comment]
Transferring this issue to the frontend, as this is originating from there.

**Comment by Opontios** [comment]
> Disable` attribute validation on initial load of ha-selector-attribute #15697

How can I do this?

**Comment by karwosts** [comment]
That's not something you *do*, it's a link to a pull request. It's just to inform you that a bugfix has been proposed. 

If that pull request is accepted, this will be fixed in a future HA version. But for now you just have to live with this behavior, or downgrade back to 2023.2.
