### ISSUE TITLE
New light entity card is missing color temperature.

### ISSUE THREAD

**Issue by chrisbklein** [home-assistant/frontend#15696]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Sengled Zigbee E11-N1EA color lightbulb offers [Color temperature], [Color], [brightness] and [ON/OFF].

I tested the following Lovelace cards.

Lovelace: Light
Custom light entity card
Custom: Mushroom light card.

The custom light entity card as well as the mushroom light card both display the Color, brightness and temperature on the same screen.

The Lovelace: Light card only displays Brightness and color and in order to get to the temperature one needs to click the 3 dots top right and then in the next display on the color chart (bottom of card) to get to another menu that offers color or temperature. The temperature is only available after clicking through all those steps whereas both custom cards offer the color and temperature icons on the first main card.

![new light card](https://user-images.githubusercontent.com/35237162/222773013-ad88780d-70f8-4eb4-af80-5cd9cfa8d961.png)

The new release video did introduce the new styled card which did show the light card including color and temperature on the bottom of the slider.

### Describe the behavior you expected

According to the release notes it supposed to look like this.

![New slider](https://user-images.githubusercontent.com/35237162/222774035-c4645085-4853-4210-98ad-7c928f6a945c.png)

When I tested to reproduce the same light entity I am missing the third icon button under the slider as I mentioned above.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.3.1

### In which browser are you experiencing the issue with?

BING, Microsoft Edge, Android

### Which operating system are you using to run this browser?

Win 11 and Android 13

**Comment by karwosts** [comment]
The third icon is bulb effects, not color temperature.

**Comment by chrisbklein** [comment]
Thank you for the quick answer.
The 2 custom cards do display the color temperature and naturally I was hoping that the new light card would do the same.
I believe that the color temperature would be a more useful feature than the effect feature.
May be the icon and functionality for color temperature could be added in some future update.

**Comment by karwosts** [comment]
Yeah that makes sense to me, but it's not my decision to make :)

I guess when I see a paint pallette it really makes me think of RGB, and I don't immediately associate that with color temp in my mind. If you want to make a feature suggestion over in *Discussions* to show a pallete and a thermometer icon, I'll vote for it. Could probably be room for a 4th icon. 

Though in that case I don't know what it should show if you clicked the color temp icon, and you had an RGB color currently selected.

**Comment by chrisbklein** [comment]
There even could be check boxes for which feature you like to see on the bottom and which one you don't.
The icon to show would be the same that is already there in the other cards.

![Temperature](https://user-images.githubusercontent.com/35237162/222792530-72abf29f-7390-4f7f-a417-c7cbbc3d7cbc.png)
This one for temperature. (the little thermometer)

And ...

![color](https://user-images.githubusercontent.com/35237162/222792660-5f88dabd-e4f6-47cf-8e29-7af58ff1cfd0.png)
This one for color (the little color pallet)

And in the settings menu for each of those different features of check-box to decide what is to be displayed and what will not show up on the first display.

What do you think?

**Comment by karwosts** [comment]
Open a new discussion for feature request. This is not the place to discuss. 

And I don't mess with the UI design anyway, so my opinion is not relevant.

**Comment by chrisbklein** [comment]
I will do that and include as well a request for smart switches to be included in the ui of the lamp in order to switch a smart switch on which will supply power to the bulb since the bulb is not really smart when it has no power.

**Comment by chrisbklein** [comment]
I did create a feature request: Lovelace light card: Include light temperature and a field for entity Light Switch
