### ISSUE TITLE
Automation editor keeps checking boxes for onvif.ptz service parameters

### ISSUE THREAD

**Issue by atx32** [home-assistant/frontend#15706]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using the automation visual editor and editing an ONVIF:PTZ service call, the editor keeps checking the boxes for distance, speed, continuous duration, and preset even if those parameters aren't relevant to the move mode or can be the default value. If I uncheck the boxes for parameters I don't need and save, when I return to edit the automation those boxes are checked again. This causes me to get the stay/leave prompt when trying to exit as the automation is now marked as modified and unsaved. The example YAML provided is for a GotoPreset move that was manually edited and shows the issue when subsequently using the visual editor.

### Describe the behavior you expected

I would think that the visual editor should honor the parameters that have been saved and not add previously unchecked ones simply because the automation was opened in the editor.

### Steps to reproduce the issue

1. Create automation with ONVIF:PTZ action, GotoPreset move mode, and uncheck the distance, speed, continuous duration parameters.
2. Save
3. Edit the automation again and without making any changes try to exit. You will get the stay/leave prompt as the unchecked parameters are now checked.

### What version of Home Assistant Core has the issue?

2023.3.1

### Problem-relevant frontend configuration

```yaml
action:
  - service: onvif.ptz
    data:
      preset: '000'
      move_mode: GotoPreset
    target:
      device_id: 9d9118a8e90a4869526a594ced1b1129
```

**Comment by karwosts** [comment]
I think I have a PR that will fix this. In the past I have thought that this was an unavoidable result of having services with optional fields with defaults, but I think I found a way to make it not load defaults other than the very first time.

**Comment by atx32** [comment]
I would think that you could just have everything unchecked the first time (since the default values should be used by the service anyway) and then when editing an existing automation leave everything not already in the YAML unchecked. The first time would then look like the screenshot below. I don't know if that creates an inconsistency elsewhere in the front end, but I don't think so.

![image](https://user-images.githubusercontent.com/13008809/222979360-59790744-107e-4a7a-9c57-2cb8111b0d6d.png)
