### ISSUE TITLE
"MQTT info" is cropped and buggy in the HA app

### ISSUE THREAD

**Issue by Stooovie** [home-assistant/frontend#15748]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Clicking "MQTT info" on any MQTT entity opens a dialogue that is cropped, zoomed in, doesn't display the "cancel" button, cannot be zoomed out manually, and the only way to dismiss it is to force-quit the app. The t has been happening for multiple years. 

![IMG_4339](https://user-images.githubusercontent.com/10572373/223052355-0c537781-34d6-4083-b713-1fbbbdc98552.png)

### Describe the behavior you expected

To have a proper view.of the MQTT info dialogue with visible buttons. 

### Steps to reproduce the issue

1. Open any MQTT entity details in Devices and Services menu
2. Tap MQTT INFO
3.
...

### What version of Home Assistant Core has the issue?

HA 2023.3

### In which browser are you experiencing the issue with?

HA app for iOS, all mobile browsers

**Comment by karwosts** [comment]
Looks like duplicate of #15151

**Comment by Stooovie** [comment]
Yes, it's the same issue, sorry.

**Comment by piitaya** [comment]
I will close it to only keep one issue. Thanks for reporting.
