### ISSUE TITLE
Entity IDs are not always renamed when renaming a device

### ISSUE THREAD

**Issue by AndreKR** [home-assistant/frontend#15757]
### The problem

When I rename a Zigbee device there is a dialog that asks me to if I want to change the entity IDs as well. If I say yes, the entity IDs are not changed.

Here is a screen recording:

https://user-images.githubusercontent.com/1188538/196586382-af10dcee-ebb9-48f6-ab20-c4f74e09fba4.mp4

### What version of Home Assistant Core has the issue?

Home Assistant 2022.9.6 Frontend 20220907.2 - latest

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

It's a ZHA device, but renaming entities might be a core feature

### Diagnostics information

[zha-e44f7ca51ed6bada21b888b7b0c6b6c0-LUMI lumi.weather-08fe1d02a16a83e6e6930e325da2cc71.json (1).txt](https://github.com/home-assistant/core/files/9816469/zha-e44f7ca51ed6bada21b888b7b0c6b6c0-LUMI.lumi.weather-08fe1d02a16a83e6e6930e325da2cc71.json.1.txt)

**Comment by BillyFKidney** [comment]
> Having the same issue here. Renaming Aqara devices does nothing to the Entitiy IDs. So having 29 devices and 159 entities, this manual work is going to be annoying and take some time. I'm not a developer but I don't see how hard it would be to capture the results after clicking 'RENAME' to trace where the issue is?

I am rapidly expanding my ZigBee network and not being able to rename ZigBee devices is making management difficult.

I'm reluctant to build automations because they will all need to be updated when the EntityID is changed.

**Comment by Loeffelmaster** [comment]
> > Having the same issue here. Renaming Aqara devices does nothing to the Entitiy IDs. So having 29 devices and 159 entities, this manual work is going to be annoying and take some time. I'm not a developer but I don't see how hard it would be to capture the results after clicking 'RENAME' to trace where the issue is?
> 
> I am rapidly expanding my ZigBee network and not being able to rename ZigBee devices is making management difficult.
> 
> I'm reluctant to build automations because they will all need to be updated when the EntityID is changed.

I have solved my problem by moving my ZigBee network from ZHA to ZigBee2MQTT. I needed to exchange my dongle to a [ZBDongle-E](https://www.zigbee2mqtt.io/devices/ZBDongle-E.html#sonoff-zbdongle-e) to make it work. In ZigBee2MQTT you can rename the device and with that also change all IDs that correspond to that device.
There it is no problem, but still this is a bug in HA even though the developers see that otherwise.

**Comment by AndreKR** [comment]
> I have solved my problem by moving my ZigBee network from ZHA to ZigBee2MQTT.

That was my solution as well.

> I'm reluctant to build automations because they will all need to be updated when the EntityID is changed.

Yes, and by the way, you should also avoid those `device` type triggers like the plague, because they break with the usual "the entity ID is the rendezvous point" principle of Home Assistant. Use `event` or `mqtt` triggers instead.

**Comment by BillyFKidney** [comment]
> > > Having the same issue here. Renaming Aqara devices does nothing to the Entitiy IDs. So having 29 devices and 159 entities, this manual work is going to be annoying and take some time. I'm not a developer but I don't see how hard it would be to capture the results after clicking 'RENAME' to trace where the issue is?
> > 
> > 
> > I am rapidly expanding my ZigBee network and not being able to rename ZigBee devices is making management difficult.
> > I'm reluctant to build automations because they will all need to be updated when the EntityID is changed.
> 
> I have solved my problem by moving my ZigBee network from ZHA to ZigBee2MQTT. I needed to exchange my dongle to a [ZBDongle-E](https://www.zigbee2mqtt.io/devices/ZBDongle-E.html#sonoff-zbdongle-e) to make it work. In ZigBee2MQTT you can rename the device and with that also change all IDs that correspond to that device. There it is no problem, but still this is a bug in HA even though the developers see that otherwise.

Actually I went the other direction because I wanted less points of failure (MQTT was unstable for a few months).

**Comment by sharkpunch5** [comment]
yes this issue is a massive blocker to scaling the use of ZHA, if you have many devices have to individually manage names of both the device, the entity and the entity id's is a pretty confusing activity and prone to error

**Comment by bdraco** [comment]
This was reported in https://github.com/home-assistant/core/issues/77150 as well but its working as expected for me which lead here since this is a frontend issue as already discovered [above](https://github.com/home-assistant/frontend/issues/15757#issuecomment-1456743299).

It would be helpful to know what happens when you try to rename and it fails

Open the Dev Tools in your browser.
Switch to the network tab
shift + reload to make sure the websocket is there.
Do the rename.
You should see websocket messages calling `config/entity_registry/update`

<img width="1084" alt="Screenshot 2023-07-10 at 7 33 39 PM" src="https://github.com/home-assistant/frontend/assets/663432/28397802-d41c-42e1-90cb-fb39fafb4fc9">

Look for any errors in the response or errors in the log

**Comment by genebean** [comment]
@bdraco The websocket message list is empty before and after a page reload and after doing a rename.

![image](https://github.com/home-assistant/frontend/assets/966789/d571e5dd-94f1-441e-9807-ed9a7c25e3f3)

**Comment by bdraco** [comment]
Check the latest websocket connection, there is another one right below it in your screenshot.  Scroll to the bottom and go up until you find the latest websocket after reloading.  Once you confirm you see the messages coming in, do the test

**Comment by AndreKR** [comment]
I don't think the issue is resolved, but personally I'm not using ZHA any more. I have switched to zigbee2mqtt with MQTT discovery and it works flawlessly, including renaming of entities.

**Comment by Hedda** [comment]
Is this not still an issue?

**Comment by Caius-Bonus** [comment]
For all devices with dots in the device name, the current code will not work, because of different behaviour of slugify between the backend and frontend. The dots are removed in the frontend and replaced in the backend. This causes the entity names not to be detected. 

A workaround working right now is rename the device to a name with all dots replaced with spaces (it doesn't matter if you rename entities or not, because it won't do anything). Then rename it to the name you want. This will work if the device name doesn't contain any other edge-cases.

I created a pull-request to solve this.

**Comment by Loeffelmaster** [comment]
Didn't mentioned that dot problem. None of my devices ever had dots in their names so, that seem to be a different more special problem when renaming?

**Comment by Caius-Bonus** [comment]
In this thread there are many references to Aqara (LUMI) devices with dots in their names. These can be explained by the dot. If there are other cases, these should also be investigated.

@Loeffelmaster You mention Tuya devices that work (Bulb) and don't work (Switch). Could you give examples of the device and entity names of the devices that don't work?

@AndreKR You mention that this also happens with a Tasmota device. Could you give examples too?

**Comment by Loeffelmaster** [comment]
The Tuya power switches are all
Zigbee Model:   TS011F
Zigbee Manufacturer:  _TZ3000_gjnozsaz

**Comment by Caius-Bonus** [comment]
@Loeffelmaster could you give an example of a device id and an entity id?

**Comment by Loeffelmaster** [comment]
@Caius-Bonus Not anymore, as I switched to ZigBee2MQTT and there I have no problems with the names as I can change them in Z2M and everything is renamed in HA accordingly so I don't need to use the renaming in HA anymore.
Normally only the device was renamed when I used to function in HA, but all connected entities still had the old name and needed to be renamed manually.

**Comment by Caius-Bonus** [comment]
Okay, that's fine. If you do get more information, it might be better to open a new issue with that information, because this issue seems to be more about the LUMI device shown in the video, which seems unrelated to the TuYa Switch issue you describe.

**Comment by nightah** [comment]
So I've noticed a similar issue that the linked PR hasn't seem to have resolved.
In my case, it's Meross MSS310 smart plug devices that will after accepting the prompt to rename entities do not do so.

@Caius-Bonus did you want me to provide the device and entity names for you to see if there's anything specific that stand out?

**Comment by Caius-Bonus** [comment]
@nightah This issue is about the cause of it not working for LUMI devices, which was inconsistent slugify between backend and frontend. Let's first take a look at the device and entity names. If those are not consistently slugified between backend and frontend, it would fit this issue, otherwise it is a new issue.

**Comment by nightah** [comment]
Sure thing so an example for a device in question is as follows:

**Device Name:** `Coffee Machine`

**Entities:**
```
sensor.smart_plug_2303132058002451070248e1e9bdcec0_current
light.smart_plug_2303132058002451070248e1e9bdcec0_dnd
sensor.smart_plug_2303132058002451070248e1e9bdcec0_energy
sensor.smart_plug_2303132058002451070248e1e9bdcec0_energy_estimate
switch.smart_plug_2303132058002451070248e1e9bdcec0_outlet
sensor.smart_plug_2303132058002451070248e1e9bdcec0_power
sensor.smart_plug_2303132058002451070248e1e9bdcec0_sensor_protocol
sensor.smart_plug_2303132058002451070248e1e9bdcec0_signal_strength
sensor.smart_plug_2303132058002451070248e1e9bdcec0_voltage
```

Clearly, the device names are generated based on some criteria that aren't immediately discernable to me. However, when attempting to rename the device it asks if all associated entities should be renamed and clicking yes results in nothing but the device itself being renamed.

**Comment by Caius-Bonus** [comment]
Thanks for the IDs. However, I need to know the device name and entity ids before renaming. Could you also supply the IEEE number of the device? I do however think that this is indeed a different bug and should have its own issue.

**Comment by chansearrington** [comment]
Why is this issue marked as closed? It's still very much not fixed.

I just experienced it again today with the GE Appliance integration. 

Here's a video showing it happening.

https://1drv.ms/v/s!AjcUU9ZDJWosvdtkDzP51boZt9bNfQ?e=KoBkD9

**Comment by bdraco** [comment]
The original problem was resolve. If there is still an issue please open a new issue with reproduction steps.
