### ISSUE TITLE
Zigbee Sengled Light Bulbs E11-G13 unavailable after HA restart

### ISSUE THREAD

**Issue by txwindsurfer** [home-assistant/frontend#15763]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Sengled E11-G13 Zigbee light bulbs fail with this error:
`DeliveryError('Failed to deliver message: <EmberStatus.DELIVERY_FAILED: 102>')`
when Home Assistant is restarted.  Other devices and bulbs work correctly.  If I switch the actual switch to the bulbs off then back on the light bulb is found and works correctly until the next restart of Home Assistant.

### Describe the behavior you expected

Light bulb should be able to be turned off and on after a restart of home assistant

### Steps to reproduce the issue

1.  Test this specific light bulb: https://www.amazon.com/gp/product/B01N7I4X94/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
2. Restart home assistant
3.
...

### What version of Home Assistant Core has the issue?

2023.3.1

### In which browser are you experiencing the issue with?

Microsoft Edge Version 110.0.1587.63 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows  11

### State of relevant entities

```txt
supported_color_modes:
  - brightness
off_with_transition: false
off_brightness: 255
icon: mdi:ceiling-light-outline
friendly_name: Shop Light
supported_features: 40
```

**Comment by karwosts** [comment]
This should be filed in home-assistant/core, not in the frontend.
