### ISSUE TITLE
History graphs don't line up with "show_names: false"

### ISSUE THREAD

**Issue by kchiem** [home-assistant/frontend#15768]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The time scales on the graphs don't line up when "show_names: false" is set.

![ScreenClip](https://user-images.githubusercontent.com/17679003/223808722-9e416973-9483-4cc0-b4d2-c2a3269b7070.png)

### Describe the behavior you expected

The time scales should line up.

### Steps to reproduce the issue

1. create a history-graph card
2. add a mix of sensor and binary_sensor entities
3. set "show_names: false"

### What version of Home Assistant Core has the issue?

2023.3.1

### In which browser are you experiencing the issue with?

Google Chrome 110.0.5481.178

### Which operating system are you using to run this browser?

Windows 10

**Comment by ildar170975** [comment]
Post here a sketch design of how you expect these different graphs to be aligned.

**Comment by karwosts** [comment]
> Post here a sketch design of how you expect these different graphs to be aligned.

Assume it just means in the way that it was done in #14919 . That PR accidentally just missed this case where there was no labels. 

![image](https://user-images.githubusercontent.com/32912880/223840135-f92f3b5f-5dbe-4233-bc9c-5ed1611ba59d.png)

**Comment by ildar170975** [comment]
Using “show_names: false” should not cause adding a left padding - at least when used w/o “linear” graphs. Probably this padding should only be added in case of presence at least one “linear” graph.

**Comment by kchiem** [comment]
> Post here a sketch design of how you expect these different graphs to be aligned.

I suppose it should look more like this.

![ScreenClip](https://user-images.githubusercontent.com/17679003/223842930-b5292272-2392-4dda-8f08-59d71a223f89.png)

**Comment by karwosts** [comment]
Submitted pull with a fix.

**Comment by ildar170975** [comment]
@karwosts 
Was this considered ?
https://github.com/home-assistant/frontend/issues/15768#issuecomment-1460834004 &

**Comment by karwosts** [comment]
It does not add any unnecessary padding. The behavior is when you have multiple chart objects, find the one with the widest axis, and then pads all the other charts to that same width to match. 

It doesn't add any fixed extra space, and it doesn't have any effect when you just have a single timeline chart alone.

**Comment by ildar170975** [comment]
@karwosts 
Thank you, looking forward to it!
