### ISSUE TITLE
Statistics Adjust window date picker date is not localised

### ISSUE THREAD

**Issue by oziee** [home-assistant/frontend#15770]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The date in the `Adjust a statistic` window is US format, it is not displaying in localised date format

### Describe the behavior you expected

displayed in my localised region format

### Steps to reproduce the issue

1. open `Adjust a statistic`
2. look at date format

### What version of Home Assistant Core has the issue?

2023.3.2

### In which browser are you experiencing the issue with?

Safari, Chrome

### Which operating system are you using to run this browser?

macOS latest

### Additional information

<img width="457" alt="Screenshot 2023-03-09 at 7 23 04 am" src="https://user-images.githubusercontent.com/1471841/223855351-87699736-e014-43a7-a348-304cfa33d0f0.png">

**Comment by karwosts** [comment]
The locale setting is passing into the datetime picker, so it seems like it should take effect. 

What is your locale setting that should be producing 9/3? I can try setting that to test.

**Comment by christophwen** [comment]
I also wanted to check this behavior and try to fix it if there is a problem, but I can't find the `Adjust a statistic` dialog. 
Is there any way to simulate a sensor device that has the ability to adjust the statistics?

I would be very grateful if someone could help me to get the wanted dialog.

**Comment by karwosts** [comment]
> I also wanted to check this behavior and try to fix it if there is a problem, but I can't find the `Adjust a statistic` dialog. Is there any way to simulate a sensor device that has the ability to adjust the statistics?
> 
> I would be very grateful if someone could help me to get the wanted dialog.

From the helpers menu, create a `Integration - Riemann sum integral sensor`. Use anything as the source sensor, shouldn't matter. After some time (maybe after a couple changes in the source sensor), you should find the riemann sum sensor under Developer Tools -> Statistics, and the rightmost column has a button for adjust statistic.

**Comment by christophwen** [comment]
I found out that the format of the date is based on the language which is used by the user. If you use "English" as the interface language, the date always will be shown as month/day/year. In the profile settings there is no possibility to change that without changing the language. Other settings like time and number format can be changed individually.
![Example](https://user-images.githubusercontent.com/43651938/236680013-bdc9f742-a57e-4ccb-af29-cc27af530885.png)

An improvement would be to add a "Date Format" setting. Is that something you would like to have? If yes, I will try to implement this.

**Comment by bramkragten** [comment]
Change the language in your HA profile to `English (GB)`
