### ISSUE TITLE
"Number of selected entities" covers "entity search" box

### ISSUE THREAD

**Issue by captainzoom** [home-assistant/frontend#15771]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

on the /config/entities/ screen, while one or more entities are selected, a user is unable to see/modify/clear the entity filter box because it is covered by the UI element that indicates how many entities are selected

### Describe the behavior you expected

With one of more entities selected on /config/entities, a user should still be able to edit / modify / clear the "Search entities" filter box

### Steps to reproduce the issue

1.  Click "Settings" in the left Nav bar
2. Click "Devices & Services"
3.  Select "Entities" at the top of the screen
4. Click within the "Search Entities" box and input a filter string
5. Select one or more of the entities on screen
6. Attempt to access the "Search Entities" dialog box
...

### What version of Home Assistant Core has the issue?

core-2023.3.2

### In which browser are you experiencing the issue with?

Chrome 110.0.5481.178 & Firefox 110.0.1 confirmed

### Which operating system are you using to run this browser?

Windows 11 22H2

**Comment by ildar170975** [comment]
Still present.

![image](https://github.com/home-assistant/frontend/assets/71872483/64d330e5-7e20-445c-b6b5-8b0e83fac906)

![image](https://github.com/home-assistant/frontend/assets/71872483/b5c5540d-3583-4a5f-944f-7a29c765d6f1)

**Comment by captainzoom** [comment]
Still Present

![image](https://github.com/home-assistant/frontend/assets/53795556/ee4e8d52-10ee-400c-9225-788a38fc9d21)

**Comment by captainzoom** [comment]
Still present in 2023.9.1, which is the version from my screenshot in my previous comment

**Comment by captainzoom** [comment]
I have updated to 2023.12.1 and this behavior is still present

**Comment by ildar170975** [comment]
Let's keep it open.
May be a nice solution will be found.

**Comment by ildar170975** [comment]
Can be closed due to changes in 2024.4.
