### ISSUE TITLE
ZHA is not recognizing the state correct from Shutter/Curtain Module BSEED - TS0601 from _TZE200_yenbr4om 

### ISSUE THREAD

**Issue by marc4s** [home-assistant/frontend#15772]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

ZHA is not recognizing the state correct from Shutter/Curtain Module BSEED - TS0601 from _TZE200_yenbr4om.

I can control the curtain module after adding it via ZHA. 
But the state of the module is not changing "in time". it hangs in mode "will be closed" or "will be opened". the curtain module is finished but in HA the state is not changing. so it is not able anymore to change the state to up/down. 
![Bildschirmfoto vom 2023-03-09 07-54-28](https://user-images.githubusercontent.com/93420756/223944199-0cb87743-dd43-40f0-9726-a48ac1fe78d2.png)

as you can see I closed it:
```
RolladenFlur wird geschlossen ausgelöst durch Dienst cover.close_cover
19:12:27 - Vor 13 Stunden 
```
then was nothing happening for hours(which means the up and down control is not available in HA "greyed out")
then I clicked on the "stop" button. and the current state is changing to the opposite of the real position.
"was opened" but it is closed, so it has to be "was closed".
```
RolladenFlur wurde geöffnet ausgelöst durch Dienst cover.stop_cover
20:31:55 - Vor 11 Stunden 
```

only good thing is that even the UI button for opening is greyed out. the automation is able to trigger cover.

![Bildschirmfoto vom 2023-03-09 08-02-09](https://user-images.githubusercontent.com/93420756/223945513-62749479-5d4d-4430-a49b-a79d75d47e37.png)

### Describe the behavior you expected

After the curtain modul has finished(got in position) ZHA should change the current state to the state which was triggered.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

OS 2023.3.2

### What was the last working version of Home Assistant Core?

OS 2023.3.2

### In which browser are you experiencing the issue with?

Firefox

### Which operating system are you using to run this browser?

Linux Mint

### State of relevant entities

```txt
current_position: 100
device_class: shutter
icon: mdi:window-shutter
friendly_name: RolladenFlur
supported_features: 15

state: "opening" (for hours... not changing even not after reboot)
```

**Comment by marc4s** [comment]
link to the product: 
https://de.aliexpress.com/item/1005005170756403.html?spm=a2g0o.order_list.order_list_main.5.a2e95c5f1wPNLw&gatewayAdapt=glo2deu

**Comment by karwosts** [comment]
Frontend does not control device states. If you have an issue with the behavior of the device, you probably need to file an issue in home-assistant/core.
