### ISSUE TITLE
Code editor not loading in Safari

### ISSUE THREAD

**Issue by P-Verbrugge** [home-assistant/frontend#15785]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I am changing my dashboard by adding/editing cards, I sometimes prefer the "code editor" view. However, when I switch to the code editor view, it's not loaded. The card or screen stays blank. Nothing is loaded. I can only switch back to the visual editor.

### Describe the behavior you expected

I except to see the yaml editor when I switch to the code editor for editing a card, etc.

### Steps to reproduce the issue

1. Open HA in Safari (Version 16.4 (18615.1.24.110.1)) on the back
2. Added card elements on the dashboard
3. Switch from the virtual editor to the code editor.

### What version of Home Assistant Core has the issue?

Home Assistant 2023.3.2

### What was the last working version of Home Assistant Core?

Not sure

### In which browser are you experiencing the issue with?

Safari Version 16.4 (18615.1.24.110.1)

### Which operating system are you using to run this browser?

MacOS Ventura 13.3 (a)

### State of relevant entities

```txt
This issue happens on all cards only in Safari. Other browsers don't have this problem.
```

### Javascript errors shown in your browser console/inspector

```txt
[Error] Unhandled Promise Rejection: TypeError: Type error

	h (fd40dd8c.js:1:266441)
	mount (fd40dd8c.js:1:266193)
	mountStyles (fd40dd8c.js:1:207077)
	_i (fd40dd8c.js:1:201068)
	(anonieme functie) (4b1b6a29.js:1:12161)
```

**Comment by karwosts** [comment]
duplicate #15496
