### ISSUE TITLE
Setting Display Precision to "Default" causes state/entity to not show in Dialogue

### ISSUE THREAD

**Issue by birdwing** [home-assistant/frontend#15780]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I click on my Utility Meter Helper sensor to open the dialogue, I noticed that the State is not shown.
![image](https://user-images.githubusercontent.com/6484397/224038578-746b0b4b-1473-4dab-a081-a892cc4e6d4f.png)

After playing around with it I realized that the issue only occurs when the Display Precision is set to Default.
![image](https://user-images.githubusercontent.com/6484397/224038804-87e97daa-ae68-4d79-ac08-78c4bbd17b66.png)

If I change the Display Precision from _Default (7.707)_ to simply 7.707
![image](https://user-images.githubusercontent.com/6484397/224038981-bf47968d-1b2f-4d0d-b58a-cde234f0d4aa.png)

The state is properly shown in the dialogue window:
![image](https://user-images.githubusercontent.com/6484397/224039087-a6231872-8be0-419e-9be2-a3b28a44e8b9.png)

In both cases the precision is set to 3 digits, but when it is the default, the state doesn't display.

### Describe the behavior you expected

I expected the popup window to display the state no matter what Display Precision is selected.

### Steps to reproduce the issue

1. Set Utility Meter Helper display precision to default.
2. Click the entity in the list to open dialogue.
3. State is missing

### What version of Home Assistant Core has the issue?

2023.3.2

### In which browser are you experiencing the issue with?

Google Chrome 110.0.5481.178, and the HA Android Companion App 2023.1.1-full

### Which operating system are you using to run this browser?

Windows 11, Android 13

### Additional information

I know this is typically related to the frontend issue on the web, but this issue also shows up in the Android Companion App.

**Comment by birdwing** [comment]
Having a good look at my screenshots, I just realized it's not the State that is missing from the dialogue, but the entire Entity itself.
![image](https://user-images.githubusercontent.com/6484397/224043008-3a59e6be-8522-4642-afab-683097db843c.png)

Vs. when precision is not set to default:
![image](https://user-images.githubusercontent.com/6484397/224043305-9442e245-83d7-4386-a296-047eff46f22d.png)

**Comment by karwosts** [comment]
I couldn't reproduce this personally. Do you have an exception in your browser console?

**Comment by birdwing** [comment]
I do not believe so, I did not think to look at the time.

I have since updated to HA Core 2023.3.4

Now instead of not displaying, it just isn't applying the precision.
Here is an animation:
![precision](https://user-images.githubusercontent.com/6484397/225422946-57b65aa9-bf7b-4d43-82e5-e29d5affc9ee.gif)

**Comment by ildar170975** [comment]
> Now instead of not displaying, it just isn't applying the precision.

This is a different issue and here is what I noticed:
1. First in more-info we see an accuracy ".xxx".
2. You went to precision settins - we see that it is set to ".xxx" (seems to be same as it was displayed on step 1).
3. You changed precision to default.
4. We see in more-info an accuracy ".xxxxxxx..." - which seems to be NOT conflicting to step 3 since you set the "default" option.

**Comment by birdwing** [comment]
> Surely, a "Default (.xxx)" label is confusing since a default value seems to be "untouched" raw ".xxxxxxxx...". But this is another issue, not related to the issue described in the 1st post.

You're right. The label confused me because I was expecting an issue to happen. It does appear though that the issue I first reported is no longer occuring.
