### ISSUE TITLE
Pencil edit not working correctly

### ISSUE THREAD

**Issue by kelos-01** [home-assistant/frontend#15794]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Pencil edit not working correctly on tabs on the dashboard.

![image](https://user-images.githubusercontent.com/39430720/224503955-f49b1706-0f6f-41d1-ae02-aa0f7b1ef37d.png)

### Describe the behavior you expected

System should delete the dashboard that the tab selection and pencil relate too.

### Steps to reproduce the issue

On overview, selecting the ellipsis on the right > edit dashboard > select the tab of the dashboard (more than two dashboards should exist) > click the pencil of the selected tab/dashboard (other than Home) click delete view. 

THIS WILL DELETE YOUR FIRST TAB & adjacent tabs

### What version of Home Assistant Core has the issue?

2023.3.1

### In which browser are you experiencing the issue with?

Chrome Version 111.0.5563.64

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
NA
```

### Problem-relevant frontend configuration

```yaml
NA
```

### Javascript errors shown in your browser console/inspector

```txt
NA
```

**Comment by karwosts** [comment]
I feel like I can remember having seen this happen sometime, though I don't think it always happens. I just tried twice and the correct tab was deleted both times. 

Have you played around with it a bit to see if you can identify a consistent sequence of clicks that always cause this to happen?

**Comment by ildar170975** [comment]
@kelos-01 
Are all views' paths are unique?
