### ISSUE TITLE
Multiple entity History Graph card don't work

### ISSUE THREAD

**Issue by mansellrace** [home-assistant/frontend#15801]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I create a history-graph card with more than one entity I don't see the correct data
![image](https://user-images.githubusercontent.com/23330590/224562487-55a53425-5aa0-4cb3-8356-c44a4dfc3134.png)
![image](https://user-images.githubusercontent.com/23330590/224562579-1ceefffd-65e9-49f9-a8e4-76e61bc65e27.png)

### Describe the behavior you expected

The data is not displayed correctly

### Steps to reproduce the issue

Create a card with more than one sensor

### What version of Home Assistant Core has the issue?

2023.3.3

### What was the last working version of Home Assistant Core?

2023.2.0

**Comment by piitaya** [comment]
Do you have any error in the console?
I'm unable to reproduce the issue 😞
![CleanShot 2023-03-13 at 16 03 59](https://user-images.githubusercontent.com/5878303/224742245-2a8c218b-ebc7-4744-b871-8cf4b8455d95.png)

**Comment by mansellrace** [comment]
After restarting the virtual machine now everything seems to be working as it should
