### ISSUE TITLE
Current month not selected in history

### ISSUE THREAD

**Issue by GigiPompieru** [home-assistant/frontend#15817]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When opening the date picker in history it does not select the current month.

### Describe the behavior you expected

When clicking the date picker today, 13th of March, the month of March should be visible, but it opens February

### Steps to reproduce the issue

1. Open History.
2. Select Start Date
3. Wrong month is displayed.
![image](https://user-images.githubusercontent.com/28728401/224940736-69b5c276-3209-4caa-9643-2eba4cfe3731.png)

### What version of Home Assistant Core has the issue?

2023.3.4

### In which browser are you experiencing the issue with?

Firefox and Android App

### Which operating system are you using to run this browser?

Windows 10 and Android

**Comment by karwosts** [comment]
Duplicate #15800
Will be fixed in future release.
