### ISSUE TITLE
input_number didn't show current value when moving slider

### ISSUE THREAD

**Issue by dylan09** [home-assistant/frontend#15828]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After update to 2023.3 my `input_number` fields didn't show the current value when moving the slider.
I try to change the value from the more info dialog. But no feedback when moving

### Describe the behavior you expected

Before 2023.3 the value shown beneath the slider changed when slider is moved.

### Steps to reproduce the issue

1. Create new `input_number` helper and set display mode to `slider`
2. Open more info  dialog for the input_number
3. Move the slider using the mouse.
4. The current value shown beneath the slider will be only updated, when the slider is released
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.3.4, Operating System 9.5

### In which browser are you experiencing the issue with?

Safari, Chrome, iOS Companion App

### Which operating system are you using to run this browser?

macOS Ventura 13.2, iOS 16.3.1

**Comment by ildar170975** [comment]
> 4\. The current value shown beneath the slider will be only updated, when the slider is released

It was ALWAYS this.
A value is only set after a mouse release.

**Comment by dylan09** [comment]
Sorry. Couldn't check it because I am unable to get back to the old version.

But I am relatively sure that before 2023.3 the changes were displayed while moving the slider.
Otherwise I would not have been able to set exact values with the slider. With a value range of 100 - 7000 and 50 step size, it is impossible to set exact 1000s (2000, 3000, 5000) in the new version. This was possible before without any problems. 
So for me the slider is useless. And I will have to change all `input_number` to display mode input field.

**Comment by ildar170975** [comment]
Well, first from your description I understood that you mean a value of the CURRENT value which is displayed on the right from the slider:
![image](https://user-images.githubusercontent.com/71872483/225444629-6477fcd1-37e9-4fce-99a9-15193e471b07.png)
because the value in the blue baloon is a PROPOSED value (not a current entity state).
If you mean a problem with a clipped baloon - then your issue is a duplicate of https://github.com/home-assistant/frontend/issues/15684, consider closing this issue.

**Comment by dylan09** [comment]
Yes you are right. I mean the value in the bubble. So Its a direkt duplicate of #15684. Closing this one.
