### ISSUE TITLE
Strange pop-up window resizing when clicking on the Title of the card

### ISSUE THREAD

**Issue by fabio-garavini** [home-assistant/frontend#15834]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

https://user-images.githubusercontent.com/54480927/225668030-0a99e1cb-6136-4cf1-8ccf-a97d2c5dc451.mp4

### Describe the behavior you expected

stay the same size

### Steps to reproduce the issue

1. open any pop-up window

### What version of Home Assistant Core has the issue?

2023.3.4

### In which browser are you experiencing the issue with?

Mozilla Firefox

### Which operating system are you using to run this browser?

Windows 11

**Comment by TillFleisch** [comment]
This is by design and useful for viewing graphs.

Implementation reference:
https://github.com/home-assistant/frontend/blob/24f167780917675bbebe127bafbe53878b608e4d/src/dialogs/more-info/ha-more-info-dialog.ts#L270-L277
