### ISSUE TITLE
History and Logbook Start Date and End Date Calendar Selector Defaults to the Incorrect Month

### ISSUE THREAD

**Issue by bakerkj** [home-assistant/frontend#15838]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I click on the History and Logbook start date and end date calendar selector it defaults to the previous month (it is March, and it displays February).

![logbook_selector](https://user-images.githubusercontent.com/5491232/225758532-010831d2-e5d2-45b6-8789-06e3de0cfe96.png)

![history_selector](https://user-images.githubusercontent.com/5491232/225758533-b7cebeed-3671-47d3-9d95-b67120a6ac72.png)

### Describe the behavior you expected

I would expect it to default to the date range that overlaps with the current date range selected (in this case March - since the date selected is March 16th 1pm to March 16 4pm)

### Steps to reproduce the issue

1. Open up the Logbook tab
2. Click on the Start (or end) Date
3. The month is incorrect

or

1. Open up the History tab
2. Click on the Start (or end) Date
3. The month is incorrect

### What version of Home Assistant Core has the issue?

core-2023.3.4

### In which browser are you experiencing the issue with?

Google Chrome 111.0.5563.64 

### Which operating system are you using to run this browser?

Ubuntu Linux 22.04

**Comment by karwosts** [comment]
Duplicate #15800. Fix is coming.

**Comment by bakerkj** [comment]
@karwosts thank you so much!
