### ISSUE TITLE
ZHA group not switching all devices off (on dashboard)

### ISSUE THREAD

**Issue by John-H-Smith** [home-assistant/frontend#15842]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I've created a group within ZHA with different devices (some lights and some plugs). I did that in ZHA, because HAOS Groups do not support cross-type groups.
So I added a button for every single device to the dashboard and also a button that toggles the whole group.
But when toggling the whole group, only the tiles of the lights are changing correctly. Physically, the plugs are toggled too, but the frontend still shows them in the old state, even if they already were toggled.

### Describe the behavior you expected

All device tiles should be updated with the new state

### Steps to reproduce the issue

1. Create a ZHA group, containing lights and plugs
2. Add all devices as single tiles to the dashboard
3. Add a tile to the dashboard which switches the group (not all devices at once, really the zha group!)
4. Toggle the whole group

### What version of Home Assistant Core has the issue?

2023.3.5

### In which browser are you experiencing the issue with?

Mobile app and also mobile brave browser

**Comment by Hedda** [comment]
Frontend does/should not actually control the states of devices or groups. So therefor I believe that if you have an issue with the behaviour of a device or group, you probably instead need to open an issue in home-assistant/core -> https://github.com/home-assistant/core/issues

For that be sure to also include info on Zigbee Coordinator hardware and its firmware + debug logs as well as ZHA diagnostics:

https://www.home-assistant.io/integrations/zha#reporting-issues

https://www.home-assistant.io/integrations/zha#debug-logging

**Comment by John-H-Smith** [comment]
> Frontend does/should not actually control the states of devices or groups. So therefor I believe that if you have an issue with the behaviour of a device or group, you probably instead need to open an issue in home-assistant/core -> https://github.com/home-assistant/core/issues


Thanks for your reply! 
The behaviour is as expected, only the tile seems not to get updated in the ui.
