### ISSUE TITLE
History and calendar

### ISSUE THREAD

**Issue by DravenSA** [home-assistant/frontend#15844]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

So i have noticed over the last few weeks that when  enter History for an entity and i select "Start Date" the calendar opens up but with Feb 2023 instead of the current month March, Anyone else getting this? I thought updating to the latest everything would fix it, but it has not. Any ideas?

### Describe the behavior you expected

Open History for an entity and when selecting the start date, for the calendar to open on current month with today's date highlighted.

### Steps to reproduce the issue

1. Select any entity that has a history graph
2.select Show More
3. on history page select Start Date
4. calendar opens in February
...

### What version of Home Assistant Core has the issue?

2023.3.5

### In which browser are you experiencing the issue with?

all browsers

### Which operating system are you using to run this browser?

Windows 10 22h2

**Comment by karwosts** [comment]
Duplicate #15800. Fix is coming.

**Comment by allenporter** [comment]
Looks like the referenced issue was fixed. Re-open if I got that wrong.
