### ISSUE TITLE
Energy Dashboard in Android App does not report cost

### ISSUE THREAD

**Issue by TheCodeJanitor-dotcom** [home-assistant/frontend#15861]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When viewing the Energy dashboard in the Android app, energy cost is not displayed, only kWh.

On a web browser, cost is displayed correctly

### Describe the behavior you expected

Energy dashboard on mobile app should display cost.

### Steps to reproduce the issue

1. Open HA app on an Android device
2. Navigate to the Energy dashboard.
3. Cost is not displayed.
![Energy Dashboard - Firefox for Windows](https://user-images.githubusercontent.com/111010697/226115902-475cf664-acdd-4bbd-98f0-6361d4437de6.png)
![Energy Dashboard - HA for Android](https://user-images.githubusercontent.com/111010697/226115903-a278307c-b4df-428e-a752-f32d7141e5c1.png)

...

### What version of Home Assistant Core has the issue?

2023.3.5

### In which browser are you experiencing the issue with?

Android app 2023.1.1-full

### Which operating system are you using to run this browser?

Android v. 13

### State of relevant entities

```txt
Note: there is NO 'States' item in Developer Tools.
```

**Comment by karwosts** [comment]
Have you tried swiping left/right inside the sources table? When in a browser if I shrink the page horizontally the sources table adopts a horizontal scrollbar so I can swipe left/right to view all the columns of the table.

**Comment by TheCodeJanitor-dotcom** [comment]
THANK YOU.  I can't shrink the page (it's the app, not a browser window), there's no scroll bar visible, but it _does_ scroll, and the data was there!
