### ISSUE TITLE
Missing options in UI editor of "Call service" "light.turn_on/off/toggle"

### ISSUE THREAD

**Issue by sneakythr0ws** [home-assistant/frontend#15885]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi!
I don't see any options in UI editor of "Call service"
HA 2023.3.5
Tried Chromium 111, Firefox 111
![issue](https://user-images.githubusercontent.com/1594945/226311635-16c89fd4-dc40-4ca1-a45a-2b1fd0d8246f.png)

### Describe the behavior you expected

Earlier I saw the constructor for selecting entities, zones and other settings.

### Steps to reproduce the issue

1. Create automaion/open developer tools
2. choose call service
3. choose light.turn_off

...

### What version of Home Assistant Core has the issue?

2023.3.5

### What was the last working version of Home Assistant Core?

don't know

### In which browser are you experiencing the issue with?

Chromium 111, Firefox 111

### Which operating system are you using to run this browser?

Ubuntu 22.10

**Comment by sneakythr0ws** [comment]
> Any errors in your browser console?

Warnings only
```This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features!```

```The resource at “https://host:8123/static/fonts/roboto/Roboto-Medium.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly.```


> Is it for **all** services? Your comment says `light.turn_off`, but your screenshot shows `light.toggle`.

light.*

> If you switch to yaml mode, what are the contents of the yaml, if anything?

![image](https://user-images.githubusercontent.com/1594945/226361379-4e5462f6-cd50-48ed-b51a-76b58beb5345.png)

**Comment by karwosts** [comment]
Hm, not sure then, it's working fine for me.

**Comment by sneakythr0ws** [comment]
> Hm, not sure then, it's working fine for me.

how can I help to debug it?

**Comment by GvdbW** [comment]
I have the same issue and I can't find what is causing it. It seems to be coming from the server side as I tried various browser and the apps on different devices with the same outcome. 

What is odd is that it's not all services that are impacted. Fan for example works well, TTS or Home Assistant Core Integration. Though the majority have that issue. 

I have the same issue when I try to create automations. Though any automation already created works well. Another weird behaviour is that if I look at an existing automation the editor would be blank and it would be the same in YAML. 

I can't find anything in my logs that point to any issue.

**Comment by karwosts** [comment]
@GvdbW - nothing in the browser developer console logs?

Just curious, do you use any kind of non-standard plugins like card-mod, browser-mod, anything like that? I've seen before people who had an old version of honeycomb-menu installed it would break like all the service call fields, so now any kind of plugins are suspect to me when I see this issue.

**Comment by GvdbW** [comment]
Yes I have card mod and browser mod (needed for minimalist UI). They are all using the latest version though.

**Comment by GvdbW** [comment]
I just redownloaded minimalist and restart home assistant and now everything is back to normal. 

I will keep an eye to see if the previous behaviour comes back.

**Comment by Eleengineer** [comment]
I have had this and happened to have errors in the logs and high memory usage at the time. It seems to affect many possible services called when it does this.

**Comment by GvdbW** [comment]
The issue is back. Not sure what is causing it this time.
