### ISSUE TITLE
Light Temperature Slider Flickers back and forth when dragging

### ISSUE THREAD

**Issue by mark007** [home-assistant/frontend#15889]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I use the colour temperature slider for my lights to move from eg 3500K to 2700K, as my finger drags the temperature down the slider flickers back to 3500K every second or so as I drag closer to 2700K. It's as if it's refreshing its current state mid way through the drag.

### Describe the behavior you expected

I would expect when dragging the slider, the element should not refresh it's state from the actual lights state until I release my finger.

### Steps to reproduce the issue

1. Set a light, eg a lifx bulb to 3500K
2. Drag the colour temperature towards 2700K slowly
3. Watch the slider revert to 3500K every second or so as the drag of the finger draws closer to 2700K.
...

### What version of Home Assistant Core has the issue?

2023.3.5

### In which browser are you experiencing the issue with?

The companion app on Android

### Which operating system are you using to run this browser?

Na

### State of relevant entities

```txt
Simply the colour temperature of the light.
```

### Problem-relevant frontend configuration

```yaml
This is on the normal temperature slider that comes when clicking on a light entity.
```

**Comment by karwosts** [comment]
I see what you describe in desktop Chrome. 

In desktop Firefox its even worse; the slider is completely frozen while mouse is being held, it doesn't move at all until the mouse button is released.
