### ISSUE TITLE
Thermostat card temperature control slider knob missing

### ISSUE THREAD

**Issue by thejonesyboy** [home-assistant/frontend#15898]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The thermostat card circular slider no longer shows a draggable knob. This seems to have changed within the past few months.

![image](https://user-images.githubusercontent.com/885571/226800732-8c9fffa2-0530-413a-8f3e-b25e7aa2e748.png)

### Describe the behavior you expected

![image](https://user-images.githubusercontent.com/885571/226800876-640b4131-0d74-44b9-9338-3668045e308f.png)

### Steps to reproduce the issue

1. Add the thermostart card to the front end.
2. Attempt to adjust the target temperature slider.

### What version of Home Assistant Core has the issue?

2023.3.0

### In which browser are you experiencing the issue with?

Google Chrome 111.0.5563.65

### Which operating system are you using to run this browser?

Windows 10 21H2 19044.2604

### Problem-relevant frontend configuration

```yaml
type: thermostat
entity: climate.daikin_ac
```

**Comment by ildar170975** [comment]
Update to the latest ver.
