### ISSUE TITLE
Cannot change weather units

### ISSUE THREAD

**Issue by zhuodong45** [home-assistant/frontend#15928]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After updated to 2023.3, I cannot change the unit for the weather service. I can change the unit in my aqara temperature sensor, but not the weather. This only happen in weather, I tried both the default weather service in HA and another weather service (tomorrow.io) ,both have issue. The dropdown doesn't show any options.

### Describe the behavior you expected

When i open weather entity, go to setting, i should be able toupdate unit

### Steps to reproduce the issue

1. Open weather entity
2. Go to setting of the entity
3. Click the dropdown
4. Nothing show up in the dropdown

### What version of Home Assistant Core has the issue?

2023.3.2

### What was the last working version of Home Assistant Core?

2023.2.x

### In which browser are you experiencing the issue with?

Chrome, my phone app

### Which operating system are you using to run this browser?

Mac, Android 13

**Comment by messiuw** [comment]
What do you mean by "changing the unit for the weather service"? Do you mean temperature, percipitation or something else? If possible, please provide a screenshot.

**Comment by zhuodong45** [comment]
The issue was only happened in 2023.4, the current version 2023.5 fixed it. I am going to close it
