### ISSUE TITLE
History-graph: currently "hours_to_show" may be defined as "0.0833" or "1.25" - but UI does not allow to input these values (and docs are not updated too)

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#15933]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since some HA version it is possible to use a value with fractional part for `hours_to_show`:

1:
![image](https://user-images.githubusercontent.com/71872483/227696157-76807e44-b9fd-4fe7-a77f-381fad2d8255.png)

0.25 (15 minutes):
![image](https://user-images.githubusercontent.com/71872483/227696195-04046079-4d28-473a-9181-9f1ec2883579.png)

0.08333 (5 minutes):
![image](https://user-images.githubusercontent.com/71872483/227696229-27ed740e-e732-4c1d-89ef-a7ea21ec0706.png)

1.25 (1 hour 15 minutes):
![image](https://user-images.githubusercontent.com/71872483/227696255-14cfda28-43d3-4bec-9a03-364df2d4e73b.png)

This is a GREAT change!!!

But in UI it is still impossible to input similar values:
![image](https://user-images.githubusercontent.com/71872483/227696318-9138c2c2-8fc0-4172-a18e-84526521fda8.png)
This in in Russian; although HA uses English, this standard component seems to be using local language; it means "incorrect values; select nearest values 1 or 2".

Also, docs are not updated:
![image](https://user-images.githubusercontent.com/71872483/227696394-e013675a-f84a-4544-a8ca-71914517ed31.png)

### Describe the behavior you expected

as above

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.3.5

### In which browser are you experiencing the issue with?

Chrome 111.0.5563.111 

### Which operating system are you using to run this browser?

Win10x64

**Comment by Istria1704** [comment]
Just an addition: I ran into the same. But the GUI actually does allow using decimals. Also smaller than 1. The field turns red, but you can still click save and it works.

So I guess the warning should just me removed. The functionality is there.

**Comment by ildar170975** [comment]
up

**Comment by Istria1704** [comment]
> Just an addition: I ran into the same. But the GUI actually does allow using decimals. Also smaller than 1. The field turns red, but you can still click save and it works.
> 
> So I guess the warning should just me removed. The functionality is there.

It works fine. There is just an unnecessary warning which can be removed.

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
Up

**Comment by ildar170975** [comment]
up

**Comment by RubenKelevra** [comment]
@karliemeads why isn't it fixed then? The bot on the other hands seems to be there just to annoy users who report bugs.

**Comment by ildar170975** [comment]
Up

**Comment by RubenKelevra** [comment]
Still not fixed.

**Comment by Istria1704** [comment]
You guys do realise this has been working for months or even years now? Keep upping this thread for nothing without reading the posts.
It's just the warning (field turning red) that is wrong. You can simply enter a decimal number and click save.

**Comment by ildar170975** [comment]
@Istria1704 
> You guys do realise this has been working for months or even years now? Keep upping this thread for nothing without reading the posts.

Suggest YOU to read the thread from the beginning.

**Comment by RubenKelevra** [comment]
> You guys do realise this has been working for months or even years now? Keep upping this thread for nothing without reading the posts. It's just the warning (field turning red) that is wrong. You can simply enter a decimal number and click save.

Nope, it doesn't. I suggest changing your tone.

Here's the current HA with Frontend 20241106.2 not working correctly:

![Screenshot_20241201_170358](https://github.com/user-attachments/assets/88a396e6-2a49-4db3-9ea8-0b6130074721)
