### ISSUE TITLE
Custom element using Angular not working

### ISSUE THREAD

**Issue by silentbil** [home-assistant/frontend#15936]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I know i can develop using lit-element a custom card, i did and its working well.
i tried to develop using Angular 15, i bundled into main.js, and mange to inject it to other frameworks for example React.
But i couldnt use it inside homeassistant.
When debugging, i see the custom element is indeed created. but the component constructor isnt called.
and then getting the `i.setConfig is not a function` error. ( i do have a setConfig method waiting in the component).

### Describe the behavior you expected

Im expecting the component to work, same as lit-element, but with Angular.

### Steps to reproduce the issue

1. build an basic Angular application
2. bundle it to a single .js file
3. add this js to resources
4. create a custom card, with type: `custom:my-angular-element`

### What version of Home Assistant Core has the issue?

2023.3.6

### In which browser are you experiencing the issue with?

Chrome 111.0.5563.65 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

### Javascript errors shown in your browser console/inspector

```txt
card custom:standalone-element TypeError: i.setConfig is not a function
```

### Additional information

i didnt mange to find an example of Angular custom element, working with homeassistant.
appriciate the help

**Comment by steverep** [comment]
Closing as this is not a frontend issue with HA.  I would suggest posting to the forum and/or Discord for help.
