### ISSUE TITLE
Can't see slider value for number

### ISSUE THREAD

**Issue by albinmedoc** [home-assistant/frontend#15937]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Can't see the value when using the slider on a number entity.

### Describe the behavior you expected

I expect to see the value when I'm using the slider.

### Steps to reproduce the issue

1. Open the more-info dialog for a number entity
2. Use the slider to change value
3. Check if you can see the value
...

### What version of Home Assistant Core has the issue?

2023.3.6

### In which browser are you experiencing the issue with?

Google chrome (111.0.5563.64), Safari (16.3)

### Which operating system are you using to run this browser?

macOS Ventura (13.2.1)

### Additional information

<img width="1162" alt="Skärmavbild 2023-03-25 kl  11 16 02" src="https://user-images.githubusercontent.com/7331299/227711409-ce446e2e-6fe5-4e54-bee8-7c241651e1e4.png">

**Comment by karwosts** [comment]
Duplicate #15684

**Comment by piitaya** [comment]
It will be fixed in `2023.4` version 🙂 (the PR is merged)
