### ISSUE TITLE
All Cameras no longer Work on any Computer or IOS Device

### ISSUE THREAD

**Issue by thorrrr** [home-assistant/frontend#15947]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi
I had to change my Hik Connect password last week.
No issue on any of my Hik Apps or devices it picked up new password.
But i notice all my rstp & still feeds now show no longer available.
I have gone into VLC all work when i add new password.
Soon as i try in HA the fail so it looks like it knows password changed
So i obviously try entering password in the rstp path and in the password box.
But on every camera i tried it fails BUT works on everything else like VLC or Hik Apps!!!
Not sure why it is not acepting new password?

### Describe the behavior you expected

Add new updated password to each camera and they start working

Home Assistant 2023.3.6
Supervisor 2023.03.2
Operating System 9.5
Frontend 20230309.1 - latest

### Steps to reproduce the issue

1. Open Dashboard with camera display on
2.No longer showing on IOS or any Desktop Browser
3.
...

### What version of Home Assistant Core has the issue?

2023.34

### What was the last working version of Home Assistant Core?

2023.36

### In which browser are you experiencing the issue with?

Brave Safari Firefox 

### Which operating system are you using to run this browser?

Windows 11 - Fedora KDE 37 v-  IOS 16.3

### Additional information

Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input) rtsp://****:****@192.168.23.180:554/Streaming/channels/101
10:22:25 – (ERROR) Stream - message first occurred at 26 March 2023 at 23:11:41 and shows up 39 times
Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input) rtsp://****:****@192.168.23.180:554/Streaming/channels/701
10:22:07 – (ERROR) Stream - message first occurred at 26 March 2023 at 23:12:24 and shows up 22 times
Error getting camera image from http://192.168.23.180:81/ISAPI/Streaming/channels/701/picture: HTTPStatusError
10:21:57 – (ERROR) Generic Camera - message first occurred at 26 March 2023 at 23:12:24 and shows up 11 times
Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input) rtsp://****:****@192.168.23.180:554/Streaming/channels/301
10:21:53 – (ERROR) Stream - message first occurred at 26 March 2023 at 23:08:22 and shows up 45 times
Error getting new camera image from Front Drive Right: Client error '401 Unauthorized' for url 'http://192.168.23.180:81/ISAPI/Streaming/channels/101/picture' For more information check: https://httpstatuses.com/401
10:20:57 – (ERROR) Generic Camera - message first occurred at 26 March 2023 at 23:11:38 and shows up 82 times

**Comment by thorrrr** [comment]
Hello any update please ?

**Comment by bramkragten** [comment]
This is not a front-end issue. Please create an issue for the integration you are using.
