### ISSUE TITLE
Supervisor entrypoints are too big ?

### ISSUE THREAD

**Issue by toxic0berliner** [home-assistant/frontend#15956]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Entrypoint.something.js has grown beyond 1.4MB and is being truncated by default reverse proxy settings in nginx

Took me a while to fix and another while to unregister the service workers that cache this file.

Now it's working for me but I'm guessing many a reverse proxy user will struggle.

Maybe something can be done to compress the file or split it up or refactor and maybe nothing can be done, just wanted to report here this will probably cause some headaches...

Using HAOS and all updated to the latest stable version.

### Describe the behavior you expected

No file above 1MB should be needed for the UI?

### Steps to reproduce the issue

Load the UI over a nginx reverse proxy 
Observe entrypoint.xxxxx.js is truncated 

### What version of Home Assistant Core has the issue?

2023.3.6

### What was the last working version of Home Assistant Core?

2023.3.4 or 5

### In which browser are you experiencing the issue with?

all, not a browser issue but nginx default max body size

### Which operating system are you using to run this browser?

all

### Javascript errors shown in your browser console/inspector

```txt
Depends where the file gets truncated, can vary a bit
```

**Comment by steverep** [comment]
> Depends where the file gets truncated, can vary a bit

Please paste it anyway.

I would assume you're talking about the supervisor entrypoint, but it's not clear without the full error and URI.

**Comment by steverep** [comment]
@toxic0berliner I determined the biggest culprit here is that polyfills for `Intl` in JS are being included in the entrypoints (which is certainly not desired).  I fixed this for the ES5 frontend build in #16349 but a little more work is needed to fix for the supervisor builds.

**Comment by toxic0berliner** [comment]
Thanks a lto @steverep  ! My new boysize limit is 5MB so that leaves room & time to fix but I fear others with reverse proxies might not find it as easy to fix so thanks for the nice effort of optimization !

**Comment by bramkragten** [comment]
> Thanks for confirming.  I agree it's too big (and the ES5 entry is insanely big at 4 MB).
> 
> 
> 
> @bramkragten this needs some strategic dynamic importing IMO, but I see several comments wishing not to split code... ❓ 

Since we only use a small portion of the supervisor panel in normal use now, and the rest is just legacy, I think it makes sense to optimize for the small path. I'll look into it tomorrow

**Comment by steverep** [comment]
> Since we only use a small portion of the supervisor panel in normal use now, and the rest is just legacy, I think it makes sense to optimize for the small path. I'll look into it tomorrow

Excellent.. that'll hopefully drop the total bundle size a good amount.  I already have a simple maneuver ready to get rid of all entrypoint size issues across the board, but I need to do some simple performance testing first.

**Comment by bramkragten** [comment]
<https://github.com/home-assistant/frontend/pull/16379>

**Comment by toxic0berliner** [comment]
Thanks to all for the efforts and congrats for the great optim already done !
