### ISSUE TITLE
Always wrong month on start date press.

### ISSUE THREAD

**Issue by RPiNut** [home-assistant/frontend#15955]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Go to History and click on the start date. It give me always February 2023.

### Describe the behavior you expected

I would like to see, if I click that button, I see the current month and the current date number bold marked.

### Steps to reproduce the issue

1. Click on History
2. Click on start-date or end-date
![Screenshot from 2023-03-27 22-31-42](https://user-images.githubusercontent.com/76691078/228060424-bd3a906d-4cca-4147-87b2-25f5bebda4f7.png)

### What version of Home Assistant Core has the issue?

2023.3.6

### What was the last working version of Home Assistant Core?

2023.2.x

### In which browser are you experiencing the issue with?

Home-assistant app

### Which operating system are you using to run this browser?

iOS 16.3.1

### Additional information

It doesn't matter if I use the app or a webbrowser. Tried with Firefox, Chrome, Safari, Epiphany and chromium.

**Comment by karwosts** [comment]
Duplicate #15800. Will be fixed in 2023.4
