### ISSUE TITLE
Slider on input numbers hidden by title bar

### ISSUE THREAD

**Issue by Tiwing1** [home-assistant/frontend#15959]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

the popup bubble on top of an input variable that shows the actual value being selected is hidden by the title bar of the popup box, making it impossible to accurately select a value in the slider.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/48974306/228272970-100b0a26-6dc9-4c25-b6dd-92d6383a538e.png">

### Describe the behavior you expected

I don't remember the previous behaviour where the popup occurred. Expected behaviour would be equivalent to raising the z-index value higher than the title bar.

### Steps to reproduce the issue

1. click on a input_number from an spot on the dashboard which opens a popup
2. click on the slider to drag left or right
3.
...

### What version of Home Assistant Core has the issue?

2023.3.6 (?) I'm using HAOS. Frontend 20230309.1 - latest

### What was the last working version of Home Assistant Core?

Last known was 2023.2.x. I don't know if I tried to adjust an input slider in 2023.3.x

### In which browser are you experiencing the issue with?

Chrome Version 111.0.5563.111 (Official Build) (64-bit) and Edge Version 111.0.1661.54 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 Version 10.0.19044 Build 19044

**Comment by piitaya** [comment]
Hello 👋 It's fixed in the 2023.4 beta version (https://github.com/home-assistant/frontend/pull/15888)
