### ISSUE TITLE
Person picture impossible to remove

### ISSUE THREAD

**Issue by joakimjalden** [home-assistant/frontend#15962]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Under settings->people, when clicking on a person one can set a picture for that person. However, one cannot remove the picture. The problem is that even though there is an x that appears in the picture selector field (which is similar to the x that appears when selecting entities in cards etc.), there does not seem to be any way to hit this x with the mouse without triggering the (image) file selector.

### Describe the behavior you expected

That it should be possible to click on the x and remove the picture.

### Steps to reproduce the issue

1. Add a picture to a person under settings->person
2. Try to hit the x to remove the picture just added

### What version of Home Assistant Core has the issue?

2023.3.6

### In which browser are you experiencing the issue with?

Microsoft Edge on Windows, Safari on Mac, and iOS app on iPhone

### Which operating system are you using to run this browser?

Windows 10, Mac OS X, and iOS respectively

### Additional information

I have tested this on a Windows PC with both Edge and Chrome, a Mac with Safari, and the HA app on iOS. All platforms behave the same way.

**Comment by karwosts** [comment]
If you're stuck trying to remove, I see that it can be activated if you use Tab key to move the focus to the X (you'll see it highlighted), and then press Enter. But yes it does seem broken for mouse events.
