### ISSUE TITLE
Automation trace graph is skewed on Safari browser

### ISSUE THREAD

**Issue by Kimble8650** [home-assistant/frontend#15965]
### The problem

When investigating the traces of my automations, the graph for the automations is broken.
<img width="461" alt="Screenshot 2023-03-16 at 9 12 16" src="https://user-images.githubusercontent.com/9073143/225542357-7c19bce6-5e78-482d-92cc-65246ee7ddaf.png">

When I view the same trace with chrome, it looks fine.
<img width="252" alt="Screenshot 2023-03-16 at 9 12 07" src="https://user-images.githubusercontent.com/9073143/225542424-d9fa9d02-6b38-4def-a0b8-bdb66c954237.png">

I'm using Version 16.3 (18614.4.6.1.6) of Safari on Mac OS

### What version of Home Assistant Core has the issue?

2023.3.3

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Automation

### Link to integration documentation on our website

https://www.home-assistant.io/docs/automation/

### Additional information

I don't know when this has worked, as I've just started using automations.

**Comment by Kimble8650** [comment]
This is still very much an issue on Safari even with the latest version of HA Core.

**Comment by Stefano0042** [comment]
Following 2024.01 HA core update the described graphical skew, is for the first time, trasversal to all platforms, iOS, Android, PC (Chrome, Edge, ..), e.g. but only in complex automations with parallel branches generated by "choice" nodes, in my case. 

![Screenshot 2024-01-05 181653](https://github.com/home-assistant/frontend/assets/59331592/7a21c57f-6063-40ca-bd5c-4e5eeea72d7d)
