### ISSUE TITLE
Bar

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#15975]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Look at the top Bar
![image](https://user-images.githubusercontent.com/42905545/228812424-9e08222b-6486-4082-bd41-921df1bd82fd.png)

### Describe the behavior you expected

.

### Steps to reproduce the issue

.

### What version of Home Assistant Core has the issue?

2023.4.0b0

**Comment by ildar170975** [comment]
No description is provided & absolutely non-informative title.

**Comment by milandzuris** [comment]
> No description is provided & absolutely non-informative title.

open eyes OK?

**Comment by ildar170975** [comment]
> open eyes OK?

Absolutely rude.
Watch you manners, too bold when online.

**Comment by frenck** [comment]
> > No description is provided & absolutely non-informative title.
> 
> open eyes OK?

Sorry, but that is just unacceptable. Feel free to open up a new issue and describe the issue. I'm going to close this one, as nothing is described, nor is your response/behavior acceptable.

../Frenck

**Comment by milandzuris** [comment]
I don't know what else to write about this problem on the screen is it good to see where the problem is or does the UI have a debug log?

**Comment by frenck** [comment]
I don't seen anything on that screen. Please describe the issue.

**Comment by ildar170975** [comment]
Detailed description is needed since this is a bug reporting in a software development.
Not to mention a fact that some users are BLIND and rely on a text description which may be spelled by a browser.

**Comment by milandzuris** [comment]
![image](https://user-images.githubusercontent.com/42905545/228818062-d10a288f-c835-4f07-bbe9-dcda49b2dcd9.png)
