### ISSUE TITLE
Profile page does not display correctly

### ISSUE THREAD

**Issue by anybody84** [home-assistant/frontend#15997]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Profile page does not display correctly

![image](https://user-images.githubusercontent.com/37036776/229121221-8f30383c-ac26-4f85-a51c-0d0f5f7a5c14.png)

### Describe the behavior you expected

Profile page displays correctly

### Steps to reproduce the issue

1. Open HA
2. Go to the `/profile` page

### What version of Home Assistant Core has the issue?

2023.4.0b2

### In which browser are you experiencing the issue with?

Google Chrome 111.0.5563.111, Firefox 111.0.1

### Which operating system are you using to run this browser?

Windows 10

**Comment by piitaya** [comment]
It will be fixed in the next frontend release
