### ISSUE TITLE
New alarm control panel does not work with long translations

### ISSUE THREAD

**Issue by kukulich** [home-assistant/frontend#15992]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

New alarm control panel does not work with long translations, see screenshot

![alarm](https://user-images.githubusercontent.com/260445/229037686-4ca36edb-97e6-403a-b91b-aba8b55da853.png)

### Describe the behavior you expected

I expect the design would work even with long translations :)

The used traslation is really the best that can be used. There's no change to find a short word. And I don't to use some shortcut.

### Steps to reproduce the issue

1. Switch to Czech language
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2023.4.0b2

**Comment by piitaya** [comment]
We can split words :
![CleanShot 2023-03-31 at 15 47 50](https://user-images.githubusercontent.com/5878303/229138022-77685bd5-715d-434c-a0cc-9b8a8609ca71.png)
or with can add ellipsis
![CleanShot 2023-03-31 at 15 50 42](https://user-images.githubusercontent.com/5878303/229138669-de1aa888-b039-470a-bc77-a5b56f860390.png)

**Comment by kukulich** [comment]
> We can split words

This version looks better to me because there's some padding about the text. And I think it's better to see the whole text. However it still looks like a hotfix, not a permanent solution... I don't know how the width has been chosed but it looks there a lot of space on both right/left sides...

**Comment by piitaya** [comment]
The width is the width on the vertical slider to have a consistent UI. It's `100px`. Even if we put `150px` there can be translation that overflows so it always nice to have this fix.

I agree, may be moving it to 120px or 130px can avoid truncate word in some languages.
