### ISSUE TITLE
Error message on most 

### ISSUE THREAD

**Issue by Trouble-51** [home-assistant/frontend#15994]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

since the beta release of today I get the following messages: null is not an object (evaluating 't.config)

this is the full error message in the log: 

like on the screen shot below:

<img width="508" alt="Screenshot 2023-03-31 at 10 48 30" src="https://user-images.githubusercontent.com/26715092/229087159-19fa5ce2-3e89-43d6-8235-66aa082219ad.png">

Logger: frontend.js.latest.202303300
Source: components/system_log/__init__.py:254 
First occurred: 10:18:28 (9 occurrences) 
Last logged: 10:42:16

http://192.168.68.54:8123/hacsfiles/lovelace-layout-card/layout-card.js?hacstag=156434866244:13:3316 TypeError: undefined is not an object (evaluating 'this._observer.disconnect')
http://192.168.68.54:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128173:1:5301 TypeError: null is not an object (evaluating 'i.querySelector')

### Describe the behavior you expected

I have tried restart Home Assistant twice but the result is the same

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.4.0b2

### What was the last working version of Home Assistant Core?

versio 2023.4.0b1

### In which browser are you experiencing the issue with?

safari Version 16.3 (18614.4.6.1.6)

### Which operating system are you using to run this browser?

macOs ventura 13.2.1

**Comment by ludeeus** [comment]
Report that to the authors of those custom cards.
