### ISSUE TITLE
Extra, sticky scrollbar and empty space when dashboard with Button Card is visited [2023.4.0b3]

### ISSUE THREAD

**Issue by kulmegil** [home-assistant/frontend#16006]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Whenever any dashboard containing any [Button Card](https://github.com/custom-cards/button-card) is visited:
- a small space is added at the bottom of the page. 
  It pushes any content (`<home-assistant>` element) including sidebar up by ~24px
- outer scrollbar appears on window

those elements will stick and follow user (including going to config) until app is reloaded.

### Describe the behavior you expected

No extra scrollbar or empty space

### Steps to reproduce the issue

1. Visit any dashboard with Button Card

### What version of Home Assistant Core has the issue?

2023.4.0b3

### What was the last working version of Home Assistant Core?

2023.3.6

### In which browser are you experiencing the issue with?

Chromium 110, Firefox 111, Companion App 2023.3

### Which operating system are you using to run this browser?

Windows 10, Android 11

### Problem-relevant frontend configuration

```yaml
views:
  - title: Test
    path: test
    cards:
      - type: custom:button-card
```

### Additional information

![2023 4 0b3](https://user-images.githubusercontent.com/570575/229260446-cfae23c0-7bcb-4989-b9d7-7403eff65a85.png)

![Screenshot_20230401-032809](https://user-images.githubusercontent.com/570575/229260326-e379c444-7224-440c-909a-62fc6ad4d785.jpg)

**Comment by kulmegil** [comment]
This change is related to the new layout

While the native `<action-handler>` element that is now positioned as fixed instead of absolute,

However Button Card is creating it's own, similar`<button-card-action-handler>` element that is still positioned as absolute and it's breaking the layout.

**Comment by bramkragten** [comment]
This should be fixed in custom button card

**Comment by kulmegil** [comment]
@ bramkragten 
My bad. Because the issue breaks layout even when user was navigates from dashboard I thought this was something that could/should be handled on your end.
