### ISSUE TITLE
Fan preset mode Medium pushes High instead of Medium with 2023.4.x beta

### ISSUE THREAD

**Issue by pimw1** [home-assistant/frontend#16022]
### The problem

The new fan card of the home assistant beta (2023.4.0b3), seems to be sending speed mode 3 when pressing medium. I'm testing this with an esphome device (ifan03), with speed_count = 3 in esphome.

![image](https://user-images.githubusercontent.com/74881023/229306781-1a8203c7-06b9-4a81-a14f-210de9e17e53.png)

When not setting speed_count = 3 in esphome (thereby defaulting back to speed_count=100), the normal % slider is displayed, and i have no issues to switch from low, medium and high when using that slider.

### What version of Home Assistant Core has the issue?

core-2023.4.0b3

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Fan

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/fan/

**Comment by piitaya** [comment]
Can you provide your entity attributes ? The new preset selector component is based on the `percentage_step` attribute.

**Comment by ildar170975** [comment]
Same `percentage: 100` for the `Main` & `High` modes.
