### ISSUE TITLE
Alarm control panel still does not work with long translation in some browsers

### ISSUE THREAD

**Issue by kukulich** [home-assistant/frontend#16021]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Follow-up of https://github.com/home-assistant/frontend/issues/15992

The solution introduced in https://github.com/home-assistant/frontend/pull/16000 works only in Chrome. It does not work in Firefox or Safari.

### Describe the behavior you expected

It should work in all browsers :)

### Steps to reproduce the issue

1. Use Firefox or Safari
2. Switch language to Czech
3.
...

### What version of Home Assistant Core has the issue?

2023.4.0b4

### In which browser are you experiencing the issue with?

Firefox 111.0.1, Safari 16.4

### Which operating system are you using to run this browser?

Windows (Firefox), iOS (Safari)

**Comment by piitaya** [comment]
It will be fixed by https://github.com/home-assistant/frontend/pull/16034 for Safari. We need to find a solution for Firefox.
