### ISSUE TITLE
Dashboard Background theme changed in 2023.4.RC

### ISSUE THREAD

**Issue by roblamoreaux** [home-assistant/frontend#16028]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have one dashboard that is all dark, where the rest are light. The default theme is for the light background where the dark dashboard uses the dark-blue theme. Up until 2023.4.rc0 this worked well. 

Now the dark dashboard always takes the light background from the default theme so I get white lines around all the cards.

### Describe the behavior you expected

The dashboard theme should override the default theme for that dashboard background

### Steps to reproduce the issue

1. use dark theme on one dashboard with a default theme that has a light background
2. update to 2023.4.0bx
3.
...
Home Assistant 2023.4.0b5
Supervisor 2023.03.3
Operating System 10.0.rc2
Frontend 20230401.0 - latest

### What version of Home Assistant Core has the issue?

2023.4.0b5

### What was the last working version of Home Assistant Core?

2023.3.5

### In which browser are you experiencing the issue with?

Chrome, Edge and older Android 4 Chrome

### Which operating system are you using to run this browser?

Windows, Android

**Comment by ofredi** [comment]
I am experiencing what I believe is the same issue where the --lovelace-background css variable is not being applied from the theme. 

I'm using:
Home Assistant 2023.4.0
Supervisor 2023.04.0
Frontend 20230405.0 - latest

Could this be related to #15977 ?

**Comment by bramkragten** [comment]
Please provide some config example

**Comment by bramkragten** [comment]
nvm, I see the issue
