### ISSUE TITLE
Lost scrollbar on panel view

### ISSUE THREAD

**Issue by jazbraz** [home-assistant/frontend#16031]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since beta my front panel view dont show scrollbar to the right. but on the other view that is not panelview it shows. 

### Describe the behavior you expected

![image](https://user-images.githubusercontent.com/45979781/229505214-fbed6cb3-b4c3-4c93-b551-000ec2a2d352.png)

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.4.0b5

### What was the last working version of Home Assistant Core?

Home Assistant 2023.3.6

### In which browser are you experiencing the issue with?

Google chrome Version 111.0.5563.147 (Officiell version) (64 bitar)

### Which operating system are you using to run this browser?

Windows 10 Business

**Comment by OsipovOV** [comment]
In the browser and in the android application, it is impossible to scroll picture-elements that are not included in the screen:
https://community.home-assistant.io/t/my-views-no-longer-scroll-after-2023-4-0/556623/3

**Comment by BebeMischa** [comment]
HA supervised latest, Win 10 pro, Firefox latest: same issue

Android app latest: same issue

Android 8, Fully Kiosk latest: same issue

**Comment by Sparky5050** [comment]
I am having the same issue.  
iPhone companion app.
Galaxy tab7 fully kiosk.
There is enough room on the iPad to display without needing to scroll.

**Comment by tOkra28** [comment]
Same Problem for me.
Cant scroll since Patch 2023.4.1.
The Hardware doesnt matter. It doesnt work at my Handy, Desktop-PC or Tablet.

With 2023.3.6 all works fine.

**Comment by tOkra28** [comment]
Hello again.
Today i installed the latest version 2023.4.5 and i still have the same problem.
Is the fix still not in this version or do i something wrong?

**Comment by pisti222** [comment]
Still have a problem, but version are changed to 2023.4.5. I tested all version when it was available, but did not work 2023.4 wersin. I just downgrade back. 
![image](https://user-images.githubusercontent.com/48616638/233032758-bfe68207-e6f4-43fb-ae51-a0f51f0bfe77.png)

**Comment by GroenZoom** [comment]
I am having the same problem.  PIcture elements card representing the house floorplan has lost its scrollbars.
Home Assistant 2023.4.5
Supervisor 2023.04.0
Frontend-versie: 20230411.1 - latest
Thank you for your efforts.
Martin

**Comment by digi303** [comment]
According to my information, the bugfix will be included in 2023.5.0.b0.
For normal users, therefore, this will happen on 03.05.2023 with the regular release of 2023.5.

**Comment by giabett** [comment]
same here no scroll in panel view

**Comment by giabett** [comment]
just insalled new version and it is not fixed in 2023.05

**Comment by GroenZoom** [comment]
I am happy with version 2023.5.0. Scollbars back under WIn10 and MS Edge

**Comment by BebeMischa** [comment]
Yes, thanks for the fix, works again ;-)

**Comment by tOkra28** [comment]
Same for me - thanks

**Comment by dtspinella** [comment]
Same here, thanks!

**Comment by pisti222** [comment]
Version 2023.5.0. is solved srollbar issue. Thank you for your effors :)

**Comment by GroenZoom** [comment]
Unfortunately our joy didn't last for long.
With 2023.5.1 scrollbars have disappeared again.
Please help HA

bye

**Comment by dtspinella** [comment]
Still working on all OS after 5.1 update.

**Comment by GroenZoom** [comment]
Scrollbars back after restart on 2023.5.2. Seems unstable since scrollbars tends to get lost while developping.
So far a restart brings them back again. Fingers crossed.

**Comment by claymccauley** [comment]
Scroll bars are back on initial login with 2023.5.2, but they go away if you click away from the overview dash.  Nothing brings them back except full page refresh and logging in again.

**Comment by wallyto** [comment]
I have the same issue on 2023.5.4 on ios 16.5
The left side menu does scroll, the right does not.
killing the app and restarting the app resolves it until the next time.

**Comment by gauthig** [comment]
Issue still there, not consistent. I can run fine for a few minutes and then all of a sudden scrolling stops.  It even happens using the HA App on and android tablet, not just my Windows 11 PC (Edge and Chrome).

**Comment by gauthig** [comment]
Issue still there, not consistent. I can run fine for a few minutes and then all of a sudden scrolling stops. 

It even happens using the HA App on android tablet, not just my Windows 11 PC (Edge and Chrome).
