### ISSUE TITLE
Misleading translation in SolarEdge component (ID)

### ISSUE THREAD

**Issue by danielholm** [home-assistant/frontend#16047]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Just got solar panels and wanted to hook up the SolarEdge component. The Swedish translation in the UI integration guide stated that I ought to input the "webbplats-ID" (which I thought wrongful should be the API address), where the facility ID should be inputted. 

I found nothing in while searching, as for the component documentation at the HA website could as well be updated regarding the specifics info that should be inputted for this component.

### Describe the behavior you expected

Hence, the Swedish translation should be changed, and the documentation for the component could add some more info.

The integration UI guide should state that it is the facility ID, not the webbplats-ID (SWE), that should be inputted for the SolarEdge integration.

### Steps to reproduce the issue

1. Open integrations
2. Add SolarEdge
3. Wrongfully input the credentials.
...

### What version of Home Assistant Core has the issue?

2023.03.*

**Comment by karwosts** [comment]
This is the wrong place for this request. If you want to suggest translation changes, you need to register for lokalize (select "join the backend translation team" link) below, and then you can contribute or change language translations for your language. 

https://developers.home-assistant.io/docs/translations/

I see this one here in the core/backend project: 
![image](https://user-images.githubusercontent.com/32912880/229826714-3a95f818-9972-419b-ba9e-d219938c0f9b.png)
