### ISSUE TITLE
Issue with March on energy dashboard

### ISSUE THREAD

**Issue by Kratax** [home-assistant/frontend#16058]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have an issue with March on energy dashboard. Although I can see in detail normal on monthly detail, in yearly detail, there is no March and the values are included in Apr. Second issue I have (not sure if related) is one missing day in March corresponding to date when time has moved to summer time by 1 hour. I have checked on Facebook group and it seems that I am not the only one. Energy stat delivered via Goodwe integration, i.e. with solar production as visible from the charts.

![1](https://user-images.githubusercontent.com/25452697/229898106-56c85089-551b-45a6-85ab-3db5e88417e9.jpeg)
![2](https://user-images.githubusercontent.com/25452697/229898114-ba83697e-253f-477c-8bce-84be89dc68fe.jpeg)
![3](https://user-images.githubusercontent.com/25452697/229898118-caa3f7fe-43cd-4273-9fc7-dfa7d8486e9e.jpeg)

### Describe the behavior you expected

Sum up of Mar values included in Mar on yearly chart
No issue with DST within March

### Steps to reproduce the issue

Go to energy dashboard - select Month - March; then Month - April; then Year

### What version of Home Assistant Core has the issue?

2023.3.6

### In which browser are you experiencing the issue with?

Firefox 111.0.1 (64 bit); Chrome Version 111.0.5563.146 (Official Build) (x86_64)

### Which operating system are you using to run this browser?

macOs Monterey 12.6.4

### Additional information

![1](https://user-images.githubusercontent.com/25452697/229899025-37e5dcd2-6ed7-4f8a-b9b9-d6050feb405f.jpeg)
![2](https://user-images.githubusercontent.com/25452697/229899028-62f46ed1-ad6d-479d-b878-96fa7235e0d1.jpeg)
![3](https://user-images.githubusercontent.com/25452697/229899034-56fef0d8-f382-4079-a1c4-0bfa7e5cea4e.jpeg)

**Comment by Kratax** [comment]
One more point that I have found, apparently, what is visible on the chart (yearly) is March number in April column and nothing for April... again, I checked the database and on an examaple of sensor feeding PV production, there is no inconsistency in data, using this script, I can see hourly values, daily ok as well, ... is it the one (table and column) used for creating the chart?

`SELECT datetime(start_ts, 'unixepoch'), datetime(created_ts, 'unixepoch'), state, sum
from statistics
where 
   metadata_id == 237
   and date(start_ts, 'unixepoch') between '2023-02-01' and '2023-04-22'`

**Comment by Kratax** [comment]
Adding info to database - I ran
`sqlite3 home-assistant_v2.db "PRAGMA quick_check"` 
no issue identified (result OK)

**Comment by Kratax** [comment]
Adding one more info, in statistics chart, I have the following lines... aparently there is some issue with Mar data, reported the same number as for Feb. But in statistics database, this is not the case... could you advice me from which table is this value calculated?
![Screenshot 2023-04-14 at 23 30 42](https://user-images.githubusercontent.com/25452697/232161043-47772b28-4d9f-49e2-a1fb-9bda76c19655.png)
![Screenshot 2023-04-14 at 23 29 41 1](https://user-images.githubusercontent.com/25452697/232161046-66b6dc88-fa82-4c21-ba64-fc9be2fb661d.png)

**Comment by Kratax** [comment]
Anybody has any advice / view on this? Thanks a lot.

**Comment by Kratax** [comment]
After Apr moth end looks like this...

![image](https://user-images.githubusercontent.com/25452697/235490349-a2f0bca6-203b-4eb6-8e6a-8a5ecc116899.png)

**Comment by Kratax** [comment]
Still nobody can help? June works and continues well, ie really seems to be connect DST and the way how data are interpreted by frontend...

**Comment by karwosts** [comment]
It's going to be pretty hard to remotely debug what issues you're having on your specific system with your specific dataset. 

If you _really_ want to dig into this further, I would suggest attaching a development frontend onto your HA and start digging into the debugging to see where things are going off. 

I'm happy to work with you to offer advice if you want to go down that road, but without having access to your system and seeing the actual data in the frontend debugger it's difficult for me to really say what's going on. My month looks fine. 

Here's some info if you feel like going down that path. 
https://developers.home-assistant.io/docs/frontend/development/

**Comment by Kratax** [comment]
I can try that ... I a bit hoped that sharing data / database backup would be possible and sufficient as well to replicate on developer side but if not, I will go through the link you provided.

**Comment by karwosts** [comment]
Well I guess if you did want to make a backup and upload all your data somewhere I might take a look at it out of curiousity, but I'm not sure where you would host that, or how to deal with any privacy implications, and I can't promise I would actually spend any significant time on it or claim I can provide a fix. 

You'll be your own best advocate if you have the ability to look into it yourself, you've noticed by now that there's not a huge developer attention paid to bug reports that don't affect a large number of people.

**Comment by Kratax** [comment]
Hi @karwosts ,
thanks a lot for the offer, I managed to duplicate my production system on testing HW, i.e. install on raspberry HAOS, still I can see the same issue as described above, i.e. specifically on energy tab, for year, there is missing March. On monthly view, I can see all days in March... 
I.e. how to debug? Any help with that? The reference you mentioned goes to forking development version of frontend...
Thanks a lot for any help!

**Comment by Kratax** [comment]
Hi @karwosts , any further advice how to proceed? Thanks a lot!!

**Comment by Kratax** [comment]
Well, as I noted above, I have already testing environment on separate HW... i.e. I have there separate HA with restored dtb... and see the same behaviour. Not sure how can I use debugger or share more info ...

Regarding export of data - I did that already - you can see it below... the point is that there does not seem to be anything strange...

https://github.com/home-assistant/core/issues/91033

**Comment by karwosts** [comment]
Sorry don't know how to help you further.

**Comment by karwosts** [comment]
Maybe check out the community forums to see if anyone else has hit this issue.

**Comment by Kratax** [comment]
I tried that as well but the same - no response / explanation. I have only bunch of people on facebook forum seeing the same behaviour. Unfortunatelly no one being developer...

**Comment by GiZMoSK1221** [comment]
hi, I have same problem.
I tried to look at the data, found only one suspicious thing:
![obrazek](https://github.com/home-assistant/frontend/assets/74879551/469aee8d-5856-4d85-80e6-83898fd961d7)

when you decode unixtimes, there is a hole in create and start time, but in different rows

```
SELECT from_unixtime(s.created_ts) as cr, from_unixtime(s.start_ts) as st, s.* FROM `statistics` s where metadata_id=35 and start is not null and EXTRACT(YEAR FROM start)=2022 and EXTRACT(month FROM start)=3 and EXTRACT(day FROM start) in (26,27)
order by id asc;

```
maybe someone, who doesn't have this problem, could post his data. Just change metdadata_id to one, you are using in energy dashboard

**Comment by Kratax** [comment]
@GiZMoSK1221  have opened another issue in core as I was not sure where the problem is, there is as well dump of my database...

https://github.com/home-assistant/core/issues/91033

**Comment by karwosts** [comment]
> maybe someone, who doesn't have this problem, could post his data.

I tried your SQL query in SQLIte Web but it's not liking it, can you double check it? (I'm not as much of a SQL expert).

![image](https://github.com/home-assistant/frontend/assets/32912880/70b74199-194d-489a-b42b-ca1d8667ff03)

**Comment by GiZMoSK1221** [comment]
@karwosts i'm running mariadb
this is the query for sqlite default db:
`SELECT datetime(s.created_ts,  'unixepoch', 'localtime') as cr, datetime(s.start_ts,  'unixepoch', 'localtime') as st, s.* FROM statistics s where metadata_id=35 and start is not null and strftime('%Y', start)='2022' and strftime('%m',start)='03' and strftime('%d',start) in ('26','27')
order by id asc;`

**Comment by karwosts** [comment]
That didn't quite work for me, but I think I figured it out (replaced start with st in the strftimes.

SELECT datetime(s.created_ts,  'unixepoch', 'localtime') as cr, datetime(s.start_ts,  'unixepoch', 'localtime') as st, s.* FROM statistics s where metadata_id=56 and strftime('%Y', st)='2023' and strftime('%m',st)='03' and strftime('%d',st) in ('11','12') order by id asc;

Also I realize my DST is on March 12, not March 27, but here's my data from my DST window:


<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 14">
<link id=Main-File rel=Main-File
href="file:///C:\Users\Tim\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\Tim\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



cr | st | id | created | metadata_id | start | mean | min | max | last_reset | state | sum | created_ts | start_ts | last_reset_ts
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
3/11/2023 21:00 | 3/11/2023 20:00 | 1153942 |   | 56 |   |   |   |   |   | 2965.345 | 2965.345 | 1678597210 | 1678593600 |  
3/11/2023 22:00 | 3/11/2023 21:00 | 1154076 |   | 56 |   |   |   |   |   | 2965.865 | 2965.865 | 1678600810 | 1678597200 |  
3/11/2023 23:00 | 3/11/2023 22:00 | 1154208 |   | 56 |   |   |   |   |   | 2965.865 | 2965.865 | 1678604410 | 1678600800 |  
3/12/2023 0:00 | 3/11/2023 23:00 | 1154340 |   | 56 |   |   |   |   |   | 2965.865 | 2965.865 | 1678608010 | 1678604400 |  
3/12/2023 1:00 | 3/12/2023 0:00 | 1154472 |   | 56 |   |   |   |   |   | 2965.865 | 2965.865 | 1678611610 | 1678608000 |  
3/12/2023 3:00 | 3/12/2023 1:00 | 1154604 |   | 56 |   |   |   |   |   | 2965.865 | 2965.865 | 1678615210 | 1678611600 |  
3/12/2023 4:00 | 3/12/2023 3:00 | 1154736 |   | 56 |   |   |   |   |   | 2967.062 | 2967.062 | 1678618810 | 1678615200 |  
3/12/2023 5:00 | 3/12/2023 4:00 | 1154868 |   | 56 |   |   |   |   |   | 2967.062 | 2967.062 | 1678622410 | 1678618800 |  
3/12/2023 6:00 | 3/12/2023 5:00 | 1155000 |   | 56 |   |   |   |   |   | 2967.418 | 2967.418 | 1678626010 | 1678622400 |  



</body>

</html>

Chart for March 12:
![image](https://github.com/home-assistant/frontend/assets/32912880/fdbdf6c8-8b55-4e8f-981b-f6e8371076c5)

Chart for March:
![image](https://github.com/home-assistant/frontend/assets/32912880/778c7eb4-b5d9-4c7a-9073-1c846cbfdd2d)

**Comment by Kratax** [comment]
Just an update from this DST change - the issue is persisting... btw not related to one integration but seems to be general issue how database is solving DST... see couple of charts showing that... ie CO2 sensor, temperature sensor, and energy sensor


![obrazek](https://github.com/home-assistant/frontend/assets/25452697/88156280-8cb3-43b8-ae23-41a7ee97c85c)
![obrazek](https://github.com/home-assistant/frontend/assets/25452697/0fa1fa71-7ee9-4a17-8b21-dca918ed45e0)
![obrazek](https://github.com/home-assistant/frontend/assets/25452697/dfeca6e4-79dd-4b8d-80c6-7dcdf21afdb8)
