### ISSUE TITLE
Markdown card not rendering on older browsers

### ISSUE THREAD

**Issue by mitchellross** [home-assistant/frontend#16063]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

FireHD10 Tablet (which can't be upgraded from old webview version) is not rendering markdown cards since 2023.3.X. ie, no text is shown on markdown cards.

Issue appears with HA companion and Fire Kiosk Browser. 

### Describe the behavior you expected

Text to appear on markdown cards as per other instances.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Frontend 20230309.1 - latest

### In which browser are you experiencing the issue with?

Various

### Which operating system are you using to run this browser?

FireOS

**Comment by mitchellross** [comment]
Turns out you can upgrade the webview on the old Fire tablets - which addresses this issue.

https://amazon-system-webview.en.uptodown.com/android/download/101847171

**Comment by spudje** [comment]
I have this issue as well on my hacked Lenovo Smart Clock, for which I cannot update the webview. So please make this work again on older versions!

**Comment by gleber** [comment]
I'm also affected by this problem with a tablet I can't upgrade without a buying a new one. Are there any workarounds here?
