### ISSUE TITLE
Map doesn't show any zone or person

### ISSUE THREAD

**Issue by calidux** [home-assistant/frontend#16068]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I try to access to the map feature, it appears as worldwide map. If I make zoom in to my location, it doesn't appear and neither the configured zones (also home zone)

![Capture](https://user-images.githubusercontent.com/125813757/230079730-e5d3a192-48e1-42e4-a3e2-eecffad55af2.PNG)

### Describe the behavior you expected

Before this bug, I could see the configured zones and my location.

### Steps to reproduce the issue

1. Access to map feature in the left panel

### What version of Home Assistant Core has the issue?

Home Assistant OS

**Comment by HAEK2023** [comment]
I have the same problem since 2023.4.2. Now running on 2023.4.5, problem not solved. If I go to Settings -> Zones I can see the map with all the zones. If I create a card map (lovelace) no problem showing zones. The problem is only with Map in the left panel/menu.
