### ISSUE TITLE
Kiosk mode not working anymore

### ISSUE THREAD

**Issue by mesut3000** [home-assistant/frontend#16064]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I use kiosk mode addon. But it is not working anymore. Removed and installed many times but it didn't work.

### Describe the behavior you expected

I want to use it again.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.4.0b7

### What was the last working version of Home Assistant Core?

Home Assistant 2023.3

### In which browser are you experiencing the issue with?

All platforms

**Comment by piitaya** [comment]
There are open issues in the kiosk mode repository : https://github.com/NemesisRE/kiosk-mode/issues
This must be resolve in the kiosk mode repository, not in HA frontend. Some others custom cards are already updated (e.g. card_mod, button-card)
