### ISSUE TITLE
Conditional card error "entities.2.conditions.0.entity"

### ISSUE THREAD

**Issue by dflvunoooooo** [home-assistant/frontend#16062]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I want to set the condition of a conditional card to a attribute of a sensor, but I keep getting the `Required key "entities.2.conditions.0.entity" missing`. I have no idea what this means. I got the code from here [Home Assistant docs](https://www.home-assistant.io/docs/scripts/conditions/#sun-elevation-condition). Here is my card:

```
type: entities
entities:
  - sun.sun
  - type: conditional
    conditions:
      -  condition: template
         value_template: "{{ state_attr('sun.sun', 'elevation') < -6 }}"
    row:
      entity: media_player.mopidy_wc_6681
      type: custom:mini-media-player
      artwork: cover
      name: Mopidy-WC
      group: true
      hide:
        power: true
        progress: true
        controls: false
        prev: true
        next: true
        volume: true
        source: true
      info: scroll
      state_filter:
        - playing
```

![Screenshot_20230405_003109](https://user-images.githubusercontent.com/32816598/229936968-f7dbcc89-5cb5-4787-b3ee-a6825d558aed.png)

### Describe the behavior you expected

I wold expect the code to work and apply my template.

### Steps to reproduce the issue

1. Create card.
2. Insert code
3. Stare at error

### What version of Home Assistant Core has the issue?

2023.3.6

### What was the last working version of Home Assistant Core?

None

### In which browser are you experiencing the issue with?

firefox 111.0.1 

### Which operating system are you using to run this browser?

Arch-Linux

**Comment by ildar170975** [comment]
> . I got the code from here [Home Assistant docs](https://www.home-assistant.io/docs/scripts/conditions/#sun-elevation-condition)

You are using a code supported by a SCRIPT inside a CARD.
Read docs for Entities card, what you are trying to do is not supported.

**Comment by dflvunoooooo** [comment]
I see, thanks for the clarification.
