### ISSUE TITLE
Translation to Ukranian does not work propertly after upgrade to 2023.4.0

### ISSUE THREAD

**Issue by dance12r** [home-assistant/frontend#16079]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

All statuses of devices, entities, weather etc shown on English when choose Ukrainian language.

### Describe the behavior you expected

All should be diplayed in Ukranian

### Steps to reproduce the issue

1.Set Ukranian in settings
2.Check statuses

### What version of Home Assistant Core has the issue?

core-2023.04.0

### What was the last working version of Home Assistant Core?

core-2023.03.6

**Comment by shirou93** [comment]
Same isssue on Polish Translations.

**Comment by bramkragten** [comment]
Have they been translated? 
Translations are provided by our community:
<https://developers.home-assistant.io/docs/translations>

**Comment by shirou93** [comment]
> Have they been translated? 
> Translations are provided by our community:
> <https://developers.home-assistant.io/docs/translations>
> 
> And the integration providing the entities should be updated to opt in to translations as well. So not all entities will be translatable yet.

Hi, on previous version they had been translated correctly.

**Comment by karwosts** [comment]
I believe I saw in the beta chat that some translation keys got renamed in the latest version, so updated translations would need to be contributed to lokalize. Once the new keys are translated it should work again.
