### ISSUE TITLE
Fan dialog not showing speed buttons for template fan

### ISSUE THREAD

**Issue by fzenasni** [home-assistant/frontend#16072]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The new fan dialog and tile seem not to be working correctly with a fan templete
The dialog is not showing the 4 speed buttons
The tile does not allow to select de preset feature
![4C3B0CB7-3219-4D38-8F0A-243EE5E856EC](https://user-images.githubusercontent.com/88903192/230198003-fb424071-caf5-49c7-9ad6-f27ef8ce9fb9.jpeg)

### Describe the behavior you expected

Speed preset buttons for the templatte fan

### Steps to reproduce the issue

Create a template fan and put the fan in lovelace
![0829F3D4-75AD-474C-8047-5FD9783EDE3C](https://user-images.githubusercontent.com/88903192/230198730-d35f3b33-3202-4926-9fbe-8acf6b0c5034.jpeg)

### What version of Home Assistant Core has the issue?

2023.4.0

**Comment by piitaya** [comment]
Hello 👋 Your doesn't seem to support speed because you do not have `set_percentage` in your template. The speed buttons are for speed. Presets are in the bottom.

**Comment by fzenasni** [comment]
Thanks for the feedback, i will try to emulate a set_percentage in my template
