### ISSUE TITLE
History page: scrollbar appears, tooltip clipped

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#16084]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Go to History page, add some sensors.
A scrollbar appears when graphs are hovered, a tooltip is clipped:

![image](https://user-images.githubusercontent.com/71872483/230363644-595d2b08-a36e-43a4-a513-f68fd27890be.png)

![image](https://user-images.githubusercontent.com/71872483/230363696-3cf27d97-2b11-4534-8abc-f69d991418b1.png)

### Describe the behavior you expected

see above

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.4.0

### In which browser are you experiencing the issue with?

Chrome 111.0.5563.147 

### Which operating system are you using to run this browser?

Win10x64

**Comment by piitaya** [comment]
Thank's for reporting the issue. However, there is no need to linked others issues 😅

**Comment by ildar170975** [comment]
Did not want them to be linked, just thought could it be related.
