### ISSUE TITLE
Button-Card fails to render when unit of measurement is '%'

### ISSUE THREAD

**Issue by cyriax** [home-assistant/frontend#16099]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When trying to display an entity with the unit of measurement set to '%' the card failes to render as soon as show_state is set to true (card completely disappears)
show_state: false
![image](https://user-images.githubusercontent.com/66515198/230433049-9e321a17-dcfa-473d-9a79-dc3053569eb1.png)

Show_state: true
![image](https://user-images.githubusercontent.com/66515198/230432825-64de98a6-d2a1-4689-af31-ec5599a82fdf.png)

### Describe the behavior you expected

The state of the entity is displayed as in previsious versions of HA.

### Steps to reproduce the issue

1. Use button_card with an enttiy of said unit of measurement
2. enable show_state

### What version of Home Assistant Core has the issue?

2023.4.0

### What was the last working version of Home Assistant Core?

2023.3.0

### In which browser are you experiencing the issue with?

Microsoft Edge 111.0.1661.62, Google Chrome 112.0.5615.49

### Which operating system are you using to run this browser?

Windows 11 22H2

### State of relevant entities

```txt
state: 37

state_class: measurement
unit_of_measurement: %
device_class: humidity
friendly_name: DECT440 Arbeitszimmer Luftfeuchtigkeit
```

### Problem-relevant frontend configuration

```yaml
show_name: true
show_icon: true
show_state: true
type: button
entity: sensor.dect440_arbeitszimmer_humidity
```

### Javascript errors shown in your browser console/inspector

```txt
blank_before_percent.ts:7 
        
    Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'language')
    at i (blank_before_percent.ts:7:25)
    at y (compute_state_display.ts:90:9)
    at m (compute_state_display.ts:34:3)
    at i.value (hui-button-card.ts:220:17)
    at i.update (lit-element.ts:160:24)
    at i.performUpdate (reactive-element.ts:1331:14)
    at i.scheduleUpdate (reactive-element.ts:1263:17)
    at i._$Ej (reactive-element.ts:1235:25)
```

**Comment by theone11** [comment]
All my button cards have disappeared.

They are all by chance of type **input_boolean** (I have no other types)

**Comment by kksligh** [comment]
I'm having the same issue but it's not related to humidity. For some reason it is was close stating these were custom buttons but that's not what is missing - they are all standard button cards. 

https://github.com/home-assistant/core/issues/91124

**Comment by theone11** [comment]
Still no button cards in 2023.4.3

**Comment by robertwigley** [comment]
ALL button cards, not just those with a percentage measurement, have disappeared after update to 2023.4.3.
