### ISSUE TITLE
Hard or soft reloading of the page adds chevrons to the header when they are not needed.

### ISSUE THREAD

**Issue by Petro31** [home-assistant/frontend#16091]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have 1 view included on my header, i.e. 1 icon.  Therefore there is no need for left/right navigation arrows.

Clearing cache & reloading the page creates 2 arrows on the header.
Reloading the page does the same thing.
Clicking on the arrow makes them go away.

Clearing cache and reloading the page brings them back.  Same with a quick reload.

### Describe the behavior you expected

The arrows should only appear if you have more then the screen allows.

### Steps to reproduce the issue

1.  Make a single view dashboard with a single icon and no name.
2.  Reload the dashboard.
3. Arrows appear.

### What version of Home Assistant Core has the issue?

2023.4

### What was the last working version of Home Assistant Core?

2023.3

### In which browser are you experiencing the issue with?

All.

### Which operating system are you using to run this browser?

Windows, iOS, Android.  Have not checked macOS.

**Comment by Petro31** [comment]
![image](https://user-images.githubusercontent.com/35082313/230399811-aee6cb55-1d7e-4bfd-b695-4ab38b1ed191.png)

**Comment by Petro31** [comment]
![image](https://user-images.githubusercontent.com/35082313/230400174-bddef42e-48fb-4d5a-8720-d938dadb9164.jpeg)

iOS / companion app

**Comment by Mariusthvdb** [comment]
thanks for the writeup. As discussed elsewhere, in #beta we noticed this, and Dev's mentioned it to be a race condition.
not sure if action was taken, good to have this marked now.

**Comment by KennethLavrsen** [comment]
I see it is Safari on iPad also.

**Comment by erikgeurts** [comment]
As mentioned in the other issue that I opened (apologies for the duplicate), this happens to me on the Android companion app and also in Chrome OS v112.

**Comment by nima-1102** [comment]
Still on 2023.5.2

**Comment by LeoCal** [comment]
Same here on 2023.5.4 on iPhone app

**Comment by tmcb82** [comment]
Still present on 2023.6

**Comment by gabrymed** [comment]
Still present on 2023.6 on Windows/Chrome

**Comment by dwd1** [comment]
fkin` annoying in the android app. if i want to click on the 4th view i cant because the chevron is here. pls get rid of it!

**Comment by tmcb82** [comment]
> fkin` annoying in the android app. if i want to click on the 4th view i cant because the chevron is here. pls get rid of it!

It’s been this way for at least 3 months and doesn’t seem to be getting any love from the HA team.

**Comment by ambroseus** [comment]
not only Safary but also in Chome browser and Android companion app
https://github.com/home-assistant/frontend/issues/16123#issuecomment-1502925818
https://github.com/home-assistant/frontend/issues/16123#issuecomment-1502919675

![Screenshot from 2023-07-27 08-44-43](https://github.com/home-assistant/frontend/assets/380645/36aba5df-39ec-496c-8801-bfae68f81418)

**Comment by benblb** [comment]
This is interfering with one of the ways I use HA. I have an Android device with a physical keypad. I've remapped some buttons to change tabs (by simulating a screen press) and the arrows shift the tabs and break this functionality.

**Comment by RoboMagus** [comment]
Seems to be an issue also reported on the ancient polymer base for the `ha-tabs`: https://github.com/PolymerElements/paper-tabs/issues/241.

Interesting that it only popped up here at the beginning of this year though.
