### ISSUE TITLE
lovleace animated backround 

### ISSUE THREAD

**Issue by lviciedo** [home-assistant/frontend#16092]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

lovleace animated backround broken home assistant release 2023.4

### Describe the behavior you expected

lovleace animated backround 

### Steps to reproduce the issue

1.
2.
3.
...
lovleace animated backround 

### What version of Home Assistant Core has the issue?

core

### What was the last working version of Home Assistant Core?

core

### In which browser are you experiencing the issue with?

google chrome

### Which operating system are you using to run this browser?

windows 11

### State of relevant entities

```txt
lovleace animated backround is broken
```

### Problem-relevant frontend configuration

```yaml
lovleace animated backround
```

### Javascript errors shown in your browser console/inspector

```txt
lovleace animated backround
```

### Additional information

lovleace animated backround

**Comment by bramkragten** [comment]
I guess that is a custom thing or something? Create an issue is the repo of it then.
