### ISSUE TITLE
Onboarding page is blank

### ISSUE THREAD

**Issue by uhthomas** [home-assistant/frontend#16100]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I've tried this with both chromium and firefox. I just created the account and see a bunch of toggles which have no description.

![image](https://user-images.githubusercontent.com/9749173/230440022-bd7b9a5c-1ef0-4769-9ea5-c710377097e3.png)

### Describe the behavior you expected

There should be some text explaining what the toggles mean.

### Steps to reproduce the issue

1. Create a new instance of home assistant.
2. Create an account.
3. Onboard.

### What version of Home Assistant Core has the issue?

[homeassistant/home-assistant:2023.4.0@sha256:18f250ff617861f7e66724cf20e7906581588311e2e2863877659ef982c4b5d7](https://hub.docker.com/layers/homeassistant/home-assistant/2023.4.0/images/sha256-18f250ff617861f7e66724cf20e7906581588311e2e2863877659ef982c4b5d7?context=explore)

### In which browser are you experiencing the issue with?

Chromium 111.0.5563.146 and Firefox 111.0.1

### Which operating system are you using to run this browser?

Arch Linux

**Comment by bramkragten** [comment]
Has been fixed in https://github.com/home-assistant/frontend/pull/16086
