### ISSUE TITLE
New Tile Card for Fan No Features for Tasmota IFAN 2

### ISSUE THREAD

**Issue by Gliebig** [home-assistant/frontend#16111]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Added a new tile card for my ceiling fan trying out the new features in 2023.4.1 but the features are not available for this entity type. 
![CaptureTile](https://user-images.githubusercontent.com/35844174/230696452-9a5397ed-27f4-4097-96b2-9d1dcbb42464.PNG)

### Describe the behavior you expected

Expected to get the new fan speed control. I'm using tasmota to control my fan and there are 4 speed controls 0-Off,1-33%,2-67%, 3-100% and one additional toggle for the light on/off

![Screenshot Capture - 2023-04-07 - 19-48-32](https://user-images.githubusercontent.com/35844174/230696484-1fd6ea3b-c308-4ae0-bee3-a99acefd4667.png)

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.4.1

### Which operating system are you using to run this browser?

Windows 10 Pro 22H2

### State of relevant entities

```txt
fan.living_room_fan
Living Room Fan
off	
preset_modes: null
percentage: 0
percentage_step: 33.333333333333336
preset_mode: null
friendly_name: Living Room Fan
supported_features: 1
```

### Problem-relevant frontend configuration

```yaml
The fan works fine using the toggle buttons on the tasmota integration. But I cannot add the controls to the tile card as expected with this core release.
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

**Comment by alex-savin** [comment]
Same here.

I have no speed control buttons for iFan03 setup via mqtt

**Comment by alex-savin** [comment]
bump

**Comment by pgross41** [comment]
I have the same problem, mine is a Template Fan (https://www.home-assistant.io/integrations/fan.template/)

**Comment by sbasmanov** [comment]
I got same problem - speed list in tile card is not compatible with fan entity. I'm not familiar with frontend, but it looks like it expects speed_list property which was removed recently. Now there is no low, medium, high speeds.

**Comment by marsteel** [comment]
My Zigbee 0-10V dimmer is recoginzed as eWeLight ZB-DL01

Here is my config following the post https://erikdevries.com/posts/automate-combofan-s-mechanical-ventilation-with-home-assistant

The Tile Card works.
<img width="1220" alt="截屏2023-12-22 21 42 54" src="https://github.com/home-assistant/frontend/assets/4281409/d79b80f4-ddfe-4c59-ba27-affdf7ca3ef8">

configuration.yaml

`fan:
- platform: template
  fans:
    central_ventilation:
      friendly_name: 'Central Ventilation'
      unique_id: attic_ventilation
      value_template: "{{ states('light.central_ventilation') }}"
      percentage_template: "{{ (state_attr('light.central_ventilation','brightness')/255*100) }}"
      speed_count: 3
      set_percentage:
        service: light.turn_on
        entity_id: light.central_ventilation
        data_template:
          brightness_pct: '{{percentage}}'
      turn_on:
        service: homeassistant.turn_on
        entity_id: light.central_ventilation
      turn_off:
        service: homeassistant.turn_off
        entity_id: light.central_ventilation
`

tile card code
`features:
  - type: fan-speed
type: tile
entity: fan.central_ventilation
tap_action:
  action: toggle
`

**Comment by sbasmanov** [comment]
Ugh, silly me :) I didn't provide percentage_template. So, defining value_template, turn_on/off, speed_count: 3, set_percentage and percentage_template makes that tile card work as expected. Thanks to MA Gang.
