### ISSUE TITLE
Card editor: dropdown list is displayed beyond accessible area

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#16113]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I open a Map card in the UI editor, I see that the bottommost part od a dropdown list is not accessible:

![image](https://user-images.githubusercontent.com/71872483/230717861-7aa8e8b8-648c-4be4-b83f-8fee72b77257.png)

Probably it may happen with other cards too.
This is an example with Entities card:

![image](https://user-images.githubusercontent.com/71872483/230717827-333d9738-ecf9-4b73-be93-3592aabfdb63.png)

### Describe the behavior you expected

The bottommost part of the dropdown list is accessible.

### Steps to reproduce the issue

1. Add a new Entities card.
2. Open a dropdown list with MANY entries.
3. Check if the bottommost part of the list is accessible.

### What version of Home Assistant Core has the issue?

2023.4.0

### In which browser are you experiencing the issue with?

Chrome 

### Which operating system are you using to run this browser?

Win10x64

**Comment by karwosts** [comment]
I looked at this once, I feel like it is somewhat related to this PR, but I'm a bit out of my depth.

https://github.com/vaadin/web-components/pull/5432

When I looked at what is happening in the debugger, we seem to have a hardcoded "requiredVerticalSpace" of 200. 

```

    __shouldAlignStartVertically(targetRect) {
      // Using previous size to fix a case where window resize may cause the overlay to be squeezed
      // smaller than its current space before the fit-calculations.
      const contentHeight =
        this.requiredVerticalSpace || Math.max(this.__oldContentHeight || 0, this.$.overlay.offsetHeight);
      this.__oldContentHeight = this.$.overlay.offsetHeight;
```

The fact that this variable is nonzero overrides the calculation based on the actual measured overlay size. If I force it to zero, the dropdown seems to behave much better, but I don't know if that's appropriate or the right way to do it or not.
