### ISSUE TITLE
IKEA Starkvind fan setting wrong

### ISSUE THREAD

**Issue by arnowelzel** [home-assistant/frontend#16116]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The fan setting for IKEA Starkvind was originally the same as on the device: off, auto, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5

However with one of the latest updates the fan setting was changed to a percentage slider from 0% to 100% where 10% seems to represent "auto" and the other values are somehow linked to the different fan speed settings. This is at least confusing since you do not expect that "10%" means "automatic". But I see this as a bug since the IKEA Starkvind is not controlled with a speed setting between 0 and 100%.

![image](https://user-images.githubusercontent.com/6613614/230727321-83b65734-ead5-4175-bff4-70304debd044.png)

### Describe the behavior you expected

The IKEA Starkvind fan setting behaves as before with a choice between the following values: off, auto, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5

### Steps to reproduce the issue

1. Link IKEA Starkvind with Zigbee integration
2. Add a card in a dashboard with the following code below:

```
type: glance
entities:
  - entity: fan.ikea_starkvind_ikeafan
```

Where `fan.ikea_starkvind_ikeafan` is the fan of the IKEA Starkvind.

### What version of Home Assistant Core has the issue?

2023.4.1

### In which browser are you experiencing the issue with?

Vivaldi 5.7.2921.65 (Stable channel) (64-Bit) 

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
preset_modes: auto, Speed 1, Speed 1.5, Speed 2, Speed 2.5, Speed 3, Speed 3.5, Speed 4, Speed 4.5, Speed 5
percentage: 20
percentage_step: 10
preset_mode: Speed 1
friendly_name: IKEA STARKVIND black Ikeafan
supported_features: 1
```

### Problem-relevant frontend configuration

```yaml
type: glance
entities:
  - entity: fan.ikea_starkvind_black_ikeafan
```

### Javascript errors shown in your browser console/inspector

```txt
n/a
```

**Comment by arnowelzel** [comment]
The latest version still has that issue. No change planned here?

**Comment by karwosts** [comment]
If you want I can discuss this further, but I feel there's probably nothing wrong here in the frontend. 

A fan that has this attribute `percentage_step: 10` indicates that it can set its speed in percentage increments of 10%, so a slider is shown and you can set the fan to 10%, 20%, 30%, etc. 

When you move the slider it calls the fan.set_percentage service. If your fan is somehow interpreting fan at 10% as auto mode, that feels like it's probably a backend bug in the integration, not frontend. 

If you want to investigate further turn on debug logging for your fan's integration and see what services are called when the slider is moved, and see if the fan responds in the way you expect to those service calls.

**Comment by arnowelzel** [comment]
The problem is - there is no "percentage". The IKEA Starkvind has the following settings:

OFF -  Auto - 1 - 1.5 - 2 -  2.5 - 3 - 3.5 - 4 - 4.5 - 5

So it makes no sense at all to provide a slider for that. The former version did just provide a drop down menu with the settings above. Why is it not possible just to return to the previous version?

**Comment by karwosts** [comment]
I think you need to file an issue in the core repo (the backend). The entity model for the fan seems wrong. 

Your fan says it has supported_features = 1. That indicates it does not support preset_mode:

```
class FanEntityFeature(IntFlag):
    """Supported features of the fan entity."""

    SET_SPEED = 1
    OSCILLATE = 2
    DIRECTION = 4
    PRESET_MODE = 8
```

If it had supported_features = 8, that would enable preset mode, and remove the slider, and then your control would get a dropdown picker. 


![image](https://github.com/home-assistant/frontend/assets/32912880/44899053-8e55-44a5-b80e-a73db99b61cc)
![image](https://github.com/home-assistant/frontend/assets/32912880/2f00d668-4d5c-48aa-84b7-d7724f6beffd)

So there doesn't seem anything wrong in the frontend, its your integration providing the wrong entity details.

**Comment by arnowelzel** [comment]
I don't provide the integration - I am just a user of Home Assistant. But thanks for the hint anyway.

**Comment by karwosts** [comment]
Well if you want it fixed, that's where you need to go next. This is the wrong repo. 

Good luck.

**Comment by arnowelzel** [comment]
What is the correct repo?

**Comment by karwosts** [comment]
[home-assistant/core](https://github.com/home-assistant/core/issues)

**Comment by arnowelzel** [comment]
Thanks - then I'll post the issue there as well.
