### ISSUE TITLE
Left/right scroll arrows show up on the view icons row of a dashboard

### ISSUE THREAD

**Issue by erikgeurts** [home-assistant/frontend#16123]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I'm reporting this here, even though I'm not entirely sure it's related to the frontend. However, the issue I'm reporting started after the 2023.4 update of HA, with the same version of the Android app before and after that update. As such, it is my suspicion that this is related to what's occurring on the server, and that the app is only reacting to this.It's the most recent version of the Android app. If I should have reported this in the repo for the app, feel free to let me know.

I have a dashboard with several views. The row of icons used to fit just fine at the top of the page while viewing the dashboard in the latest version of the Android companion app, with HA 2023.3.x.

However, after the update to HA 2023.4 (and its 2 bug fix releases), there are left and right arrows appearing next to the view icons in the app:
![image](https://user-images.githubusercontent.com/5102461/230868279-1c3cbfda-6400-441f-8d43-b44fc3004663.png)

After moving the icon row a little bit left and right, the arrows disappear and the icons fit nicely again:
![image](https://user-images.githubusercontent.com/5102461/230868117-efc1a911-c158-44be-9c99-58ebfd67bab6.png)

This occurs on my Google Pixel 5 phone in portrait orientation.

### Describe the behavior you expected

I would expect that the row of icons fits without the need for left/right arrows, just like it did before 2023.4.

### Steps to reproduce the issue

1. Create a dashboard with 5 views
2. View the dashboard in the Android companion app on a Google Pixel 5.

### What version of Home Assistant Core has the issue?

2023.4.2

### What was the last working version of Home Assistant Core?

2023.3.x

### In which browser are you experiencing the issue with?

Android Companion app v2023.3.0

### Which operating system are you using to run this browser?

Android 13

**Comment by erikgeurts** [comment]
At first, I assumed this was something related to available space in the limited dimensions of a mobile phone, but now I also see this happening in the views row while on a Chromebook:
![image](https://user-images.githubusercontent.com/5102461/230930835-3d6016e6-d8ec-431e-bd4f-bd78c0211b2a.png)

Simply clicking either the left or right arrow seems to trigger some sort of recalculation, making them disappear (as on the phone).

**Comment by ambroseus** [comment]
confirm the same issue: extra arrows on first opening HA companion app (latest HA version, Andriod 12, phone Poco F4)

it disappears after reloading view page or clicking on arrows
![1681202372338](https://user-images.githubusercontent.com/380645/231105063-6097cdd6-4e3c-419a-a8ff-4eba48172a63.jpg)

**Comment by ambroseus** [comment]
upd: reproducing on desktop Chrome via mobile view (dev tools)
![Screenshot from 2023-04-11 11-44-18](https://user-images.githubusercontent.com/380645/231106301-8aa062c3-856f-4fab-9c23-12622a919955.png)

**Comment by Mariusthvdb** [comment]
duplicate of https://github.com/home-assistant/frontend/issues/16091

**Comment by erikgeurts** [comment]
> duplicate of #16091

Thanks for making that important note. I don't know how I could have overlooked that. Good to see there's some ongoing investigative work. Please let me know if I can contribute in any way.

**Comment by Mariusthvdb** [comment]
hehe.
well, +1 the other post ;-)
