### ISSUE TITLE
2023.4 Removed Common iOS Gesture Functionality from the iOS App

### ISSUE THREAD

**Issue by ziptbm** [home-assistant/frontend#16130]
### The problem

Since the 2023.4 upgrade (and 2023.4.1 and 2023.4.2), the iOS app appears to have lost the ability to tap at the top of the screen to scroll automatically at the top AND it appears it's losing data when the app is the background and the reopened.

Screen Tap - the repo is:
- Open HA App
- Go to a view that is large or long, scroll down to the bottom
- Tap the top of the screen (nothing happens, it previously would scroll all the way to the top)

Reliability - the repro is:
- open HA App
- Navigate away for a bit (maybe 10 min)
- re-open the HA app
- Many of the icons are missing from my main dashboard.  Workaround is to pull down to refresh the page, which restores the icons.  The data appears to be correct, but some of the icons are just missing.

Both of these may be related to the original issue with 2023.4 that removed the left swipe gesture to bring out the menu from the left, which the mobile app update solved almost immediately after 2023.4 was released.

### What version of Home Assistant Core has the issue?

2023.4.2

### What was the last working version of Home Assistant Core?

2023.3.6

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Home Assistant for iOS

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/mobile_app/#apps-that-use-mobile-app

### Additional information

Please let me know what specific information I should provide that would be helpful.

**Comment by ziptbm** [comment]
@bramkragten just to clarify, does this mean that the PR it was merged into will be in a future release?  e.g. it's not in 2023.4.4?

I can confirm that in 2023.4.4, tapping the top of the screen in the mobile app on iOS does NOT scroll all the way to the top of the screen.   I haven't been on this build long enough to repro the icons missing issue.

**Comment by bramkragten** [comment]
it is not part of 2023.4.4, it will be in a future release
