### ISSUE TITLE
Camera widgets in android 2023.4.2 do not work 

### ISSUE THREAD

**Issue by ppchris2** [home-assistant/frontend#16149]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The camera widgets do not appear to be working in my android phone
I can create the, select the entity ID but they appear transparent at all times.
Samsung S20 FE 
Home Assistant 2023.4.2

### Describe the behavior you expected

Should be able to see latest image 

### Steps to reproduce the issue

1. Create a widget in android and use the entity id of a camera
2. Observe that the image is not displayed. 

### What version of Home Assistant Core has the issue?

2023.4.2

**Comment by dshokouhi** [comment]
This is fixed in the latest beta of the android app
