### ISSUE TITLE
Light entities show wrong brightness value

### ISSUE THREAD

**Issue by nikoroxy** [home-assistant/frontend#16146]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I've configured a bunch of lights through knx integration, but in the UI ( bashboard cards and entity brief window too ) brightness value are shown as in range 0-255 and not 0-100. Taken an entity which have brightness value set to 100%, cards shows it to 39%.

![immagine](https://user-images.githubusercontent.com/16979271/231444893-7ea17c7f-1597-4ae8-970c-30d3e7bb96ae.png)

![immagine](https://user-images.githubusercontent.com/16979271/231444989-f8dd3be9-02df-4671-9166-027a614122ce.png)

### Describe the behavior you expected

Get correct values into dashboard cards

### Steps to reproduce the issue

1. Add a light entity
2. Create a card which shows newly created entity attributes

### What version of Home Assistant Core has the issue?

2023.4.2

### In which browser are you experiencing the issue with?

Mozilla Firefox 111.0.1, Chromium 112.0.5615.49, Android App 2023.3.0-full

### Which operating system are you using to run this browser?

Manjaro Linux, Android

### State of relevant entities

```txt
entity_id: light.postazione_1_salone
supported_color_modes:
  - brightness
color_mode: brightness
brightness: 100
```

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/231445418-9d8434e3-2f65-4161-86ab-b9ecd723cda6.png)

Please note, a brightness value ranges from 0-255.

☝️ Brightness 100 to a percentage is: 100/255 * 100% = 39,2156862745% -> 39%

The UI is correct.

../Frenck

**Comment by nikoroxy** [comment]
So is knx integration who doesn't convert it correctly?

**Comment by frenck** [comment]
I'm not aware of how brightness works with KNX. If you suspect an issue, please file an issue against KNX in the Core repository.
