### ISSUE TITLE
`Edit Dashboard` Offers `SHOW CODE EDITOR` Instead of `SHOW VISUAL EDITOR` When Code Editor is First View

### ISSUE THREAD

**Issue by The00Dustin** [home-assistant/frontend#16144]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Whenever the code editor is shown first while editing a card, the option to switch between the visual editor and the code editor indicates `SHOW CODE EDITOR` even if clicking it can (and will) switch to the visual editor.

### Describe the behavior you expected

Whenever I'm looking at the code editor, I expect the switcher to say `SHOW VISUAL EDITOR` as it does when I've switched to the code editor from the visual editor.  If it is detectable that this isn't possible, then perhaps the option should be greyed out, but then it should update and enable when it becomes possible.

### Steps to reproduce the issue

1. Select a dashboard you control
2. Edit dashboard
3. Add Card
4. Choose `Manual` from bottom of list
5. Witness issue, `SHOW CODE EDITOR` under YAML editor
6. Paste any card code supported by visual editor in YAML editor
7. Click/tap `SHOW CODE EDITOR`
8. Witness switch visual editor
9. Click/tap `SHOW CODE EDITOR`
10. Witness normal, `SHOW VISUAL EDITOR` under YAML editor

### What version of Home Assistant Core has the issue?

2023.4.2

### In which browser are you experiencing the issue with?

Safari 16.4, iOS App 2023.4

### Which operating system are you using to run this browser?

Monterey 12.6.4, iOS 16.3.1

### Problem-relevant frontend configuration

```yaml
While I have witnessed this problem in the past other under circumstances, I was never certain it wasn't a cache issue.  As I have now noticed the problem is reproducible without any configuration, and am reporting it under those circumstances, I don't really have relevant YAML.  Any existing card's code can be copied and pasted for step (6) during reproduction, but the issue is present before that step, and the remaining steps to see normal behavior could also be performed separately from an existing card that supports visual editor.
```

### Additional information

HAOS
Home Assistant 2023.4.2
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230309.1 - latest

**Comment by The00Dustin** [comment]
This issue still exists at the following version level:

Home Assistant 2023.7.1
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

**Comment by karwosts** [comment]
posted a fix PR
