### ISSUE TITLE
show_name option for entity cards not working in latest core version

### ISSUE THREAD

**Issue by smartypantsuk** [home-assistant/frontend#16150]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In an entities card or glance card, nott tried others, the **show_name: false** option doesn't work.
The **show_state: false** option does.

### Describe the behavior you expected

**show_name: false** should hide the entity name from the card.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

latest

### What was the last working version of Home Assistant Core?

na

**Comment by ildar170975** [comment]
For Glance card, the `show_name` option does work:
![image](https://user-images.githubusercontent.com/71872483/231590043-418c0265-edd0-4a5e-8e1e-9fcb7c62e72f.png)

For Entities card, the `show_name` option is only available for "type: buttons" special row - and it does work too:
![image](https://user-images.githubusercontent.com/71872483/231591632-20f5b27a-f50c-4a81-8500-93a846b43c34.png)

The only issue here is a [WRONG DOCS](https://www.home-assistant.io/dashboards/entities/#show_name):
it is specified that a default value is `true` - but seems that a default value is `false`.

**Comment by karwosts** [comment]
I kind of feel like maybe the source should be fixed to make the show name default work, rather than changing the doc. I would expect that showing the name would be the default, it seems to be the default for all other cards that have this option.

This is the source that governs it, it does seem like true is intended to be the default. 

```
          const name =
            (entityConf.show_name && stateObj) ||
            (entityConf.name && entityConf.show_name !== false)
              ? entityConf.name || computeStateName(stateObj)
              : "";
```

**Comment by karwosts** [comment]
Filed the PR to fix the default behavior (#16152).

**Comment by smartypantsuk** [comment]
> Filed the PR to fix the default behavior (#16152).
> 
> Agree it's not necessarily the same issue as OPs.
> 
> @smartypantsuk - if you're having issues, can you post the card yaml that you claim is not working correctly?

Apologies, it's my implementation that's wrong.
Although, I can use show_state: false like below but show_name: false/true doesn't work here, which I thought was odd and which caused me to think it was a bug.

`entity: sensor.yahoofinance_amazon
name: amazon
show_state: false
show_name: false`

**Comment by smartypantsuk** [comment]
> > type: custom:multiple-entity-row
> 
> This is not related to the core frontend. Also, the `show_name` option is NOT supported for `multiple-entity-row`.

True. I put in in the wrong place.

**Comment by ildar170975** [comment]
@smartypantsuk 
Probably you should this current issue then.
As for the "default value for show_name" problem discussed above - I hope the corresponding [PR](https://github.com/home-assistant/frontend/pull/16152) will be merged to make docs & core consistent.
