### ISSUE TITLE
Entity state translation broken in 2023.4.3

### ISSUE THREAD

**Issue by fsevilla3** [home-assistant/frontend#16162]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since upgrading from 2023.4.2 to 2023.4.3, entity states are no longer reported using their friendly names. Below are some examples that I was able to replicate using standard entity cards but also show up with multiple row entity cards from HACS:

- `binary_sensor.aqara_room_occupancy`: 2023.4.2 reports `Clear` or `Detected`. 2023.4.3 reports `off` or `on`.
- `water_heater.heat_pump_hws`: 2023.4.2 reports `Off` or `Heat Pump`. 2023.4.3 reports `off` or `heat_pump`.

There were no other changes other than upgrading from 2023.4.2 to 2023.4.3. This was confirmed using a web browser, iOS mobile app, and Android mobile app, all the latest available versions. The problem goes away when I revert back to 2023.4.2.

### Describe the behavior you expected

Entity states should be reported in the UI using their friendly name.

### Steps to reproduce the issue

1. Set up an entity card similar to examples above.
2. Upgrade to 2023.4.3.
3. View entity card

### What version of Home Assistant Core has the issue?

2023.4.3

### What was the last working version of Home Assistant Core?

2023.4.2

### In which browser are you experiencing the issue with?

Firefox 112.0, iOS Companion 2023.460

### Which operating system are you using to run this browser?

Linux Mint 11, iOS 16.4.1

### State of relevant entities

```txt
For occupancy entities, 2023.4.2 shows the friendly name `Clear` when state is `off` and `Detected` when state is `on`. 2023.4.3 shows `off` or `on`.

For water heater entities, 2023.4.2 shows the friendly name `Off` when state is `off` and `Heat Pump` when state is `heat_pump`. 2023.4.3 shows `off` or `heat_pump`.
```

### Problem-relevant frontend configuration

```yaml
type: entity
entity: binary_sensor.aqara_room_occupancy

type: entity
entity: water_heater.heat_pump_hws
```

### Javascript errors shown in your browser console/inspector

```txt
None
```

**Comment by vincedh** [comment]
Same here, problem exists in 2023.4.4. as well.

**Comment by vincedh** [comment]
Updated the mushroom cards from HACS fixed the problem

**Comment by fsevilla3** [comment]
Thanks @vincedh. For what it's worth, I'm not using the Mushroom cards from HACS. My issue can be reproduced using standard entity cards.

**Comment by gabrymed** [comment]
Same here,  in 2023.4.4. as well.

**Comment by Alan010-2** [comment]
Same problem on the mushroom entity card but it works on the standard entity card

**Comment by ildar170975** [comment]
1. mushroom cards are NOT supposed to be discussed here, they are CUSTOM.
2. Does anyone experience any issues with conditional cards like Entities, Entity etc?

**Comment by fsevilla3** [comment]
@ildar170975 -- Thanks. I upgraded to 2023.4.4 and confirm that I'm no longer able to reproduce this problem on standard entity, entities and tile cards.

**Comment by sheminasalam** [comment]
I am still facing this issue with my custom:swipe-card card

**Comment by ildar170975** [comment]
@sheminasalam you are using a CUSTOM card, it is not the right place to ask about it.
