### ISSUE TITLE
Picture elements card state_filter not behaving as it should 

### ISSUE THREAD

**Issue by 26tajeen** [home-assistant/frontend#16174]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I'm using the picture elements state_filter to desaturate images of householders as they leave the house. This used to work really well until a few years ago and it got broken by an update to Home Assistant.

I've read the docs and tried rewriting my state_filters but to be honest nothing was wrong with them, they matched the docs.

Anyway what I've found is in the CSS (accessed using the inspect feature of Chrome) the CSS seems to contradict itself

`<div style="filter: brightness(50%) brightness(150%);" class="container"> <!--?lit$14372226$--> <img id="image" src="https://frankfurt.duckdns.org:8123/local/images/mary.png" style="display:block;">  <!--?lit$14372226$--> </div>`

### Describe the behavior you expected

That the CSS would show brightness of 50% only because 'mary' is not home 

```
          - entity: sensor.mary_status
            filter: brightness(50%)
            image: /local/images/mary.png
            state_filter:
              "Home": brightness(150%)
              "Just Arrived": brightness(150%)
```

### Steps to reproduce the issue

1. Configure a picture elements card as shown above
2. Test
3. Observe that the picture does not reliably follow the states it should
...

### What version of Home Assistant Core has the issue?

2023.4.0

### What was the last working version of Home Assistant Core?

not sure. Sometime in 2019 maybe?!

### In which browser are you experiencing the issue with?

Chrome and Safari

### Which operating system are you using to run this browser?

Mac OS Catalina 

### State of relevant entities

```txt
n/a
```

### Problem-relevant frontend configuration

```yaml
n/a
```

### Javascript errors shown in your browser console/inspector

```txt
n/a
```

### Additional information

n/a

**Comment by ildar170975** [comment]
Check this card:

![image](https://user-images.githubusercontent.com/71872483/231823551-e9ad4bb5-ed12-4472-a87f-5b5af01f472f.png)

Seems that you should omit the `filter` option & use the `state_filter` only...

**Comment by 26tajeen** [comment]
Seems to work fine as a workaround, I just changed it to:

```
          - entity: sensor.mary_status
            image: /local/images/mary.png
            state_filter:
              "Home": brightness(150%)
              "Just Arrived": brightness(150%)
              "Away": brightness(50%)
              "Just Left": brightness(50%)
```

note how I had to add in the other possible conditions, whereas with filter, I wouldn't need to do this. That's fine of course, but this is a bug, right?

**Comment by ildar170975** [comment]
> That's fine of course, but this is a bug, right?

Cannot confirm since docs do not say explicitly "do not use these options together".
![image](https://user-images.githubusercontent.com/71872483/232130915-d4210f01-0511-43d4-a413-a9728a59b847.png)
