### ISSUE TITLE
[Password manager] username / password not registered during login 

### ISSUE THREAD

**Issue by yanivf38** [home-assistant/frontend#16186]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the login screen, I use password manager (keeper security) to fill the username and password for me. The fields getting filed up properly. However, when clicking login it doesn't accept them. When I inspect the post payload, both fields are not populated.

It seems like an update to the fields are not registered. If I type something let say in the user than autofill using the app the value in the post will be what I typed originally.

My current workaround is after the autofill, I delete and re-enter a character from both username and password fields. This triggers an update and everything works fine.

I can't recall at what version of HA it started to break but it worked sometime early this year

### Describe the behavior you expected

After autofill, I would be able to login but clicking on the login button

### Steps to reproduce the issue

1. go to home assistant instance (I used both edge and chrome)
2. using password manager auto-fill the fields
3. click login
...

### What version of Home Assistant Core has the issue?

2023.4.4

### In which browser are you experiencing the issue with?

any chromium browser (edge / chrome)

### Which operating system are you using to run this browser?

Win11

**Comment by Alexivia** [comment]
I can confirm that this also happens in macOS Safari using the builtin iCloud password manager. Also cannot recall in which version of HA it started happening.
When I fill in things manually it works, but if done solely by the manager then login fails since the password is not registered by HA.

**Comment by steverep** [comment]
Duplicate of #16976 

Please subscribe and track this there, but good to know that this is not limited to Safari and/ord Keychain. 👍🏻
