### ISSUE TITLE
Multi-line input text boxes on add-on configuration do not show on iPadOS 16.4.1

### ISSUE THREAD

**Issue by uphillbattle** [home-assistant/frontend#16187]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Cannot configure add-ons because multi-line input boxes do not show. Problem appears both in companion app and Chrome browser. The problem is the same for all add-ons, but picture below shows the configuration page for WireGuard.

![IMG_0696](https://user-images.githubusercontent.com/15340540/232144709-7d33e7a2-d67d-47d9-9ede-76a802925d49.png)

### Describe the behavior you expected

I expect the multi-line boxes to show.

### Steps to reproduce the issue

1. Open add-on configuration page

### What version of Home Assistant Core has the issue?

2023.4.4

### In which browser are you experiencing the issue with?

Chrome 112.0.5615.46 and Companion App 2023.4

### Which operating system are you using to run this browser?

iPadOS 16.4.1

**Comment by fi-sch** [comment]
Same here – Safari on macOS. I think this error in browser's console may be related:
```
[Error] Unhandled Promise Rejection: TypeError: Type error
```
