### ISSUE TITLE
problem with DSM integration, "loosing" authentication couple of times per day

### ISSUE THREAD

**Issue by helmarw** [home-assistant/frontend#16201]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The DSM integration regularly (every few hours) "loses" authentication.
especially the part responsible for the Surveillance Station.

It happens after I updated to 2023.4.1.
Now I am on 2023.4.4 and it still does not work properly!
I have not updated anything on Synology. I have installed the latest Surveillance Station
which worked fine before 2023.4.1 along with HA. 

To fix this, sometimes reloading the integration helps or I am prompted to authenticate again.
This has never happened, only when I did some updates on Synology that required a new login or a change of the SSL certificate

```
Logger: homeassistant.components.synology_dsm.coordinator
Source: helpers/update_coordinator.py:193 

Integration: Synology DSM (documentation, issues) 
First occurred: 15. April 2023 um 20:14:35 (4 occurrences) 
Last logged: 09:38:20

Error fetching 192.168.100.102 SynologyDSMCameraUpdateCoordinator data: Error communicating with API: {'api': 'SYNO.SurveillanceStation.Camera.Event', 'code': 105, 'reason': 'Insufficient user privilege', 'details': None}
Error fetching 192.168.100.102 SynologyDSMCameraUpdateCoordinator data: Error communicating with API: {'api': 'SYNO.SurveillanceStation.Camera', 'code': 105, 'reason': 'Insufficient user privilege', 'details': None}

```

### Describe the behavior you expected

cant say anything here, only that it should NOT happen many time per day

### Steps to reproduce the issue

1) wait a few hours and check the video feed/still images on HA
2) they will be not available
3) then reload DSM integration
4) GOTO 1)

### What version of Home Assistant Core has the issue?

2023.4.4

### In which browser are you experiencing the issue with?

Safari Version 16.4 (18615.1.26.11.23)

### Which operating system are you using to run this browser?

Ventura 13.3.1 (22E261)

**Comment by helmarw** [comment]
does anyone have the same problem ?
Maybe someone can give me a tip on how to fix this annoyance. 
thnx a lot !

**Comment by karwosts** [comment]
You need to file this in home-assistant/core, this is the frontend repository. 

Once it's there it will tag the DSM integration owner.

**Comment by frenck** [comment]
This issue is indeed filed in incorrect place. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
