### ISSUE TITLE
Media library icons flicker while scrolling

### ISSUE THREAD

**Issue by donghaoren** [home-assistant/frontend#16218]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The icons in the media library browser flicker quite often while scrolling up/down.

In the developer console, I can see that the browser is fetching the images when the flicker happens. I guess while scrolling, the frontend is occasionally recreating some of the `<img>` elements?

### Describe the behavior you expected

The icons shouldn't flicker.

### Steps to reproduce the issue

1. Add a media integration (I'm using Volumio), that populates icons (e.g., albums) in the media library. 
2. In the front end, navigate to the media library.
3. Scroll up/down to observe the issue.

I'm using a MacBook with Google Chrome 112.0.5615.49 (Official Build). This issue also happens in iOS app.
My front end version is `Frontend 20230302.0 - latest`.

### What version of Home Assistant Core has the issue?

2023.3.1

### In which browser are you experiencing the issue with?

Google Chrome 112.0.5615.49

### Which operating system are you using to run this browser?

macOS Ventura (13.3.1)

**Comment by donghaoren** [comment]
I've updated to the latest version (on Docker), with:

```
Home Assistant 2023.7.2
Frontend 20230705.1 - latest
```

Looks like the flickering behavior is still happening.

**Comment by hamishfagg** [comment]
This is still happening for me on docker, home assistant 2023.12.1
