### ISSUE TITLE
URLs present in attributes no longer working.

### ISSUE THREAD

**Issue by dipanghosh** [home-assistant/frontend#16227]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If a sensor or entity has an URL as its attribute, it was possible before to visit the URL.

As of frontend version 20230405.0, this seems to have stopped working. There is some issue which makes it so that the a tags no longer has any href attribute associated with them.

### Describe the behavior you expected

If a sensor or entity has an URL as its attribute, it should be possible before to visit the URL.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.4

### What was the last working version of Home Assistant Core?

2023.3 was definitely working.

### In which browser are you experiencing the issue with?

All major browsers, Companion app is unaffected.

### Which operating system are you using to run this browser?

Windows

### Javascript errors shown in your browser console/inspector

Nothing relevant.

**Comment by ildar170975** [comment]
There is a sensor with an attribute which keeps url:
```
template:
  - sensor:
      - name: test_demo_yandex_time_home_yamki
        state: 34
        attributes:
          mapurl: "https://www.google.com"
          jamsrate: 5
```
Test card:
```
type: entities
entities:
  - entity: sensor.test_demo_yandex_time_home_yamki
    type: attribute
    attribute: mapurl
```
![image](https://user-images.githubusercontent.com/71872483/232914145-eb0f9750-74a9-4933-b7ec-6edf68d2b872.png)

Testing with 2022.7.4:
after tapping a link - more-info window is open:
![image](https://user-images.githubusercontent.com/71872483/232927958-7ffcbfba-18ea-4a68-9177-c4908163afe0.png)
and here you may tap on a link.

Testing with 2023.4.5:
after tapping a link - more-info window is open:
![image](https://user-images.githubusercontent.com/71872483/232928049-9d3a8313-79af-4371-bde1-811f27902b46.png)
and here you may tap on a link.

So , I see no difference.

**Comment by dipanghosh** [comment]
Okay, there definitely is an issue with this version. I took a completely separate installation, which was at 2022.7 and was working fine. 
![2023-04-19_10-29](https://user-images.githubusercontent.com/5004441/233019420-551b5b4c-8428-4c5a-a0a5-1e9f0fc649c5.png)
The same installation, with everything exactly the same, reproduces the problem after upgrading to 2023.4.5
![2023-04-19_10-39](https://user-images.githubusercontent.com/5004441/233019656-150ad24a-5551-46d1-b327-14abf9fe5007.png)

**Comment by dipanghosh** [comment]
Looking at the HTML:

## 2023.4
```html
<div class="data-entry"> <div class="key"> <!--?lit$9697354296$-->Testurl </div> <div class="value"> <!--?lit$9697354296$--><a target="_blank" rel="noreferrer" href=""><!--?lit$9697354296$-->https://dipan.de</a> </div> </div>
```

##2023.3 and before
```html
<div class="data-entry"> <div class="key"><!--?lit$409346741$-->Url</div> <div class="value"> <!--?lit$409346741$--><a target="_blank" rel="noreferrer" href="https://dipan.de"><!--?lit$409346741$-->https://dipan.de</a> </div> </div>
```

The href attribute is not set correctly, causing the issue.

**Comment by ildar170975** [comment]
> The link is there, but I looked at the source code, where the href attribute is missing, causing the link to point to the dashboard itself.

Strange, this is what I see in Win+Chrome:
![image](https://user-images.githubusercontent.com/71872483/233044433-490c9d3b-d772-4a75-b2b2-07d0f1c0dfd2.png)

Same in Win+FF:
![image](https://user-images.githubusercontent.com/71872483/233044738-6dacdc85-f523-490f-bdcb-47c78e30a8eb.png)

**Comment by pailloM** [comment]
I have the same issue. URL in attribute redirect to the dashboard.
Web links are working fine.
Looking back it seems to have stopped working in 2023.4

**Comment by dipanghosh** [comment]
@pailloM Yes, I have downgraded to 2023.3 and that has taken care of it for now. I want this issue to be noticed so that it can be fixed. I don't know why @ildar170975 does not see the issue.

**Comment by lcavalli** [comment]
I have the same issue both with both web brosers and Android companion app. Link's href property is empty. I'm using Home Assistant 2023.4.6 and Frontend 20230411.1 - latest.

**Comment by Bikonja** [comment]
Same issue here, broken since Home Assistant 2023.4, currently on 2023.5.1 and still broken. Using Chrome.
I have a card defined like this:
```
type: entities
entities:
  - entity: binary_sensor.x
  - entity: binary_sensor.y
  - entity: sensor.home_assistant_website
  - entity: input_boolean.z
title: Binary sensor
```
The sensor.home_assistant_website entity is the sensor from Home Assistant Version.
When I click on the entity, the dialog opens like this:
![image](https://user-images.githubusercontent.com/7753243/236568636-b13be298-181e-4158-8400-d5d85b0a5563.png)

but like dipanghosh, the href attribute is empty and the link therefore just goes to the same page.

Opening the sensor from the Devices/Services page results in the same behaviour.

**Comment by dipanghosh** [comment]
This issue must be brought to the notice of the developers. 
I am unable to update homeassistant because of this.
Anyone know developers that we can tag?
