### ISSUE TITLE
Addon configuration broken in Safari

### ISSUE THREAD

**Issue by vturekhanov** [home-assistant/frontend#16232]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Some addon configuration options cannot be edited in Safari.

### Describe the behavior you expected

All addon configuration options can be edited in Safari.

### Steps to reproduce the issue

1. Open addon configuration page of Mosquitto Broker (pay attention to logins and customize sections).
<img width="1039" alt="Screenshot 2023-04-19 at 12 47 17" src="https://user-images.githubusercontent.com/5890453/232990079-9344c945-f7a0-4625-89f6-b95ffdcf3bab.png">

2. Try to switch to the YAML mode.
<img width="1043" alt="Screenshot 2023-04-19 at 12 47 29" src="https://user-images.githubusercontent.com/5890453/232990107-2e91430c-9e53-4e7e-a753-577bff41ead1.png">

### What version of Home Assistant Core has the issue?

core-2023.4.5

### What was the last working version of Home Assistant Core?

Unknown

### In which browser are you experiencing the issue with?

Safari 16.4 (18615.1.26.11.23)

### Which operating system are you using to run this browser?

macOS Ventura 13.3.1 (22E261)

**Comment by JTP335d** [comment]
I had this exact issue today with the SSH add-on. Also on Safari. Works fine in Firefox.
