### ISSUE TITLE
Scrolling is not possible with view type picture-elements

### ISSUE THREAD

**Issue by hsguyue** [home-assistant/frontend#16239]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The 2023.4 version starts to select picture-elements as the view type and cannot scroll

### Describe the behavior you expected

picture-elements view scrolling

### Steps to reproduce the issue

1.  Dashboard view type select picture-elements
2. View will not be scrollable

### What version of Home Assistant Core has the issue?

2023.4.5

### In which browser are you experiencing the issue with?

all

### Which operating system are you using to run this browser?

macOS windows Android

**Comment by kumarunster** [comment]
@hsguyue why closed? In which version was it fixed?

**Comment by hsguyue** [comment]
@kumarunster The issue has been fixed in Home Assistant Core version 2023.5.2.

**Comment by kumarunster** [comment]
@hsguyue great, thank you!
