### ISSUE TITLE
Forecast.Solar time offset due to daylight Saving Time ?

### ISSUE THREAD

**Issue by AMajland** [home-assistant/frontend#16243]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

It seems that the forecast is an hour early compared to the registered production.

![image](https://user-images.githubusercontent.com/97510471/233089516-fd0e4d9c-50e0-4cb7-911f-b0112a6b4023.png)

The front end shows the time correct both in history and the energy display.
Timezone is set to GMT+1 Copenhagen and i run it HA with language English  but Country to Denmmark

### Describe the behavior you expected

I expect the peak production of the forecast to match real peak produktion

### Steps to reproduce the issue

Add forecast to energy display 
Observe peak will be between 12 and 13:00 Central European Summer Time (CEST)
Observe that real production will peak between 13:00 and 14:00  (CEST)

### What version of Home Assistant Core has the issue?

2023.4.5

### In which browser are you experiencing the issue with?

Google Chrome

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
Cant's seem to find the the values for forecast as entities. Current hour and next hours as ell as today and tomorrew is easily visible - but not the per hour values as drawn in energy dashboard.
```

**Comment by AMajland** [comment]
Seems to be similar to https://github.com/home-assistant/frontend/issues/10394 - but that is shifted the other way

**Comment by dbwarrior1975** [comment]
I had also started to use this integration. Clearly seen that there is some kind of ofset issue. 
My location is chooced from Home Assistant /config/general/location my coordinates. 
Also time zone configured from /config/general/Timezone to GMT+2 Finland
If compared real solar production and forecast. Levels are correc, but 2hours offset
![kuva](https://github.com/home-assistant/frontend/assets/80710485/2ba2917c-cb42-44d1-879c-f4519c537643)

**Comment by AMajland** [comment]
I'm in GMT+1 (GMT+2 and DST) and see about 1 hour difference while[dbwarrior1975] in GMT+2 sees a 2 hour. So it seems to be timezone - DST related

**Comment by AMajland** [comment]
Not sure - so far i've just seen that the energy card is off and that the peak production time seems totally weird (i would use that to prohibit change to 3 phase ev charging if production is already decreasing before it has been high enough to switch from 1 to 3
