### ISSUE TITLE
When setting up a new automation I am now unable to select actions for existing defined Light Groups

### ISSUE THREAD

**Issue by fuzzysb** [home-assistant/frontend#16287]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I currently have a number of Light groups defined in home assistant, and have been using these successfully.

I am trying however to make a new rule that I wish to turn off the light group. I do have existing automation rules that have been created in previous versions of HA and these still operate correctly.

but i cannot specify any actions for any light groups, once i add the light group, the list of actions is empty, in the piucture below Orangery Lights is a light group

![image](https://user-images.githubusercontent.com/16162689/233973298-54beab74-43e0-43ab-8b8b-6781a7b5bbe9.png)

this group has a number of lights as shown 

![image](https://user-images.githubusercontent.com/16162689/233973666-ce510bb7-3d1f-46d4-80a3-55a314e556cc.png)

### Describe the behavior you expected

I expect to to select the action to switch on/off the light group, but this dropdown is empty

### Steps to reproduce the issue

1. Create a new automation Rule
2. Under Actions, click on New Action
3. Select Device
4. Enter the Light group name and select the group
5. Try and select the action list and this does not display
...

### What version of Home Assistant Core has the issue?

 2023.4.6

### In which browser are you experiencing the issue with?

Brave V1.49.132 and Microsoft Edge (Chromium) v112.0.1722.58

### Which operating system are you using to run this browser?

Windows 1122H2 (Build 22621.1555)

### State of relevant entities

```txt
Entity: light.orangery_lights
Current State: off

	min_color_temp_kelvin: 2000
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 500
effect_list: colorloop
supported_color_modes: color_temp, hs, xy
entity_id: light.extended_color_light_28, light.extended_color_light_16, light.extended_color_light_29, light.extended_color_light_17, light.extended_color_light_56, light.extended_color_light_7, light.extended_color_light_57, light.extended_color_light_62, light.extended_color_light_8, light.extended_color_light_58, light.extended_color_light_15, light.extended_color_light_55, light.extended_color_light_9, light.extended_color_light_53
icon: mdi:lightbulb-group
friendly_name: Orangery Lights
supported_features: 44
```

### Javascript errors shown in your browser console/inspector

```txt
legacy-support.js:16  WARNING: Polymer will be removed from window in Home Assistant 2023.5. More info: https://developers.home-assistant.io/blog/2023/04/04/deprecating_polymer
get @ legacy-support.js:16
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by karwosts** [comment]
So to be clear, now there are no errors in your console? Maybe want to remove them from the original post in that case to avoid confusion. 

I'm not certain if group helpers are supposed to be actionable as "devices" or not. 

Instead of device action, can you just use call-service action with light.turn_off service? Usually using service calls are much more flexible than using device actions, which are more limited.

**Comment by fuzzysb** [comment]
I have updated the original post with the only one error in the browser now. 

as for your comment about group helpers, this is a change as I have automation configured historically in this way. and to be fair IMHO they should be treated as any light as this is the point.

for an update calling the service does work for these devices in the automation, but to me this causes confusion.

**Comment by fuzzysb** [comment]
This is still not working in the latest versions, the only option is to use the services like Light: Turn on. it just makes no sense that a light group would not expose the same actions as a light, but feel free to close if you think this is wrong.
