### ISSUE TITLE
Part of voice assistant detail dialog is not translatable

### ISSUE THREAD

**Issue by dougiteixeira** [home-assistant/frontend#16329]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The "Set as preferred" and "Debug" buttons do not work with translations.

https://github.com/home-assistant/frontend/blob/0c36600a812e5115d9eda33b8c18e47473930f39/src/panels/config/voice-assistants/dialog-voice-assistant-pipeline-detail.ts#L161-L167

https://github.com/home-assistant/frontend/blob/0c36600a812e5115d9eda33b8c18e47473930f39/src/panels/config/voice-assistants/dialog-voice-assistant-pipeline-detail.ts#L155-L160

### Describe the behavior you expected

That it is possible to translate all parts of the user interface.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.5.0b0

**Comment by piitaya** [comment]
Hello 👋
The design on the buttons is temporary. We will add the translations when we will find a better position for these buttons.

**Comment by piitaya** [comment]
We can keep it for now. I will close it once it's done.

**Comment by piitaya** [comment]
Here we go
![image](https://user-images.githubusercontent.com/5878303/234867152-2e679cd3-7980-4276-b936-94d0972988ee.png)
