### ISSUE TITLE
Ecobee no "hazy" image

### ISSUE THREAD

**Issue by MV1707** [home-assistant/frontend#16334]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Ecobee integration : The "hazy" weather condition does not have an associated image/icon. 

Hint : The actual term on the Ecobee thermostat is "haze"

![Ecobee - No hazy image](https://user-images.githubusercontent.com/130404931/234853236-73f271ab-5662-42ac-9bef-76d1f5c57b5d.jpg)

### Describe the behavior you expected

Should have an associated image/icon

### Steps to reproduce the issue

1.Edit a custom Dashboard
2.Add a Card
3.Select Entity : wheather.<<your thermostat name>>
4.Weather condition must be "haze" on your Ecobee
...

### What version of Home Assistant Core has the issue?

2023.4.6

### In which browser are you experiencing the issue with?

Firefox, Edge

### Which operating system are you using to run this browser?

W11 Family 22621.1555

### State of relevant entities

```txt
haze
```

**Comment by karwosts** [comment]
I guess this map in the ecobee core integration is probably the reason:

```
# Translates ecobee API weatherSymbol to Home Assistant usable names
# https://www.ecobee.com/home/developer/api/documentation/v1/objects/WeatherForecast.shtml
ECOBEE_WEATHER_SYMBOL_TO_HASS = {
    0: ATTR_CONDITION_SUNNY,
    1: ATTR_CONDITION_PARTLYCLOUDY,
    2: ATTR_CONDITION_PARTLYCLOUDY,
    3: ATTR_CONDITION_CLOUDY,
    4: ATTR_CONDITION_CLOUDY,
    5: ATTR_CONDITION_CLOUDY,
    6: ATTR_CONDITION_RAINY,
    7: ATTR_CONDITION_SNOWY_RAINY,
    8: ATTR_CONDITION_POURING,
    9: ATTR_CONDITION_HAIL,
    10: ATTR_CONDITION_SNOWY,
    11: ATTR_CONDITION_SNOWY,
    12: ATTR_CONDITION_SNOWY_RAINY,
    13: "snowy-heavy",
    14: ATTR_CONDITION_HAIL,
    15: ATTR_CONDITION_LIGHTNING_RAINY,
    16: ATTR_CONDITION_WINDY,
    17: "tornado",
    18: ATTR_CONDITION_FOG,
    19: "hazy",
    20: "hazy",
    21: "hazy",
    -2: None,
```

These are the only conditions that have images in the frontend for weather:
```
export const weatherIcons = {
  "clear-night": mdiWeatherNight,
  cloudy: mdiWeatherCloudy,
  exceptional: mdiAlertCircleOutline,
  fog: mdiWeatherFog,
  hail: mdiWeatherHail,
  lightning: mdiWeatherLightning,
  "lightning-rainy": mdiWeatherLightningRainy,
  partlycloudy: mdiWeatherPartlyCloudy,
  pouring: mdiWeatherPouring,
  rainy: mdiWeatherRainy,
  snowy: mdiWeatherSnowy,
  "snowy-rainy": mdiWeatherSnowyRainy,
  sunny: mdiWeatherSunny,
  windy: mdiWeatherWindy,
  "windy-variant": mdiWeatherWindyVariant,
};
```

There are no icons for hazy, tornado, or snowy-heavy. 

I know NWS integration maps haze to "exceptional", which displays a circle with an exclamation mark in it. Not claiming that's the right answer or not, but it's what another integration is doing. Meteo seems to map haze to cloudy. 

Not sure what the solution should be, but this will just give some breadcrumbs to chase.

**Comment by karwosts** [comment]
Some of the history of these design decisions seems to be captured here:

https://github.com/home-assistant/architecture/issues/292
https://github.com/home-assistant/architecture/issues/263

https://github.com/home-assistant/frontend/pull/3726

**Comment by piitaya** [comment]
MDI have `snowy-heavy`, `hazy` and `tornado` icons now. But this needs a core change to support these conditions (see architecture link above)
Most weather integrations map these condition to `ATTR_CONDITION_EXCEPTIONAL`. The ecobee integration should do this as long as the other conditions are not added
