### ISSUE TITLE
Here is a working solution: iOS 9.3.5 (iPad2) and Homeassistant

### ISSUE THREAD

**Issue by 555wolfman** [home-assistant/frontend#16355]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

actual homeassistant does not work with old iPads (ios 9.3.5)

### Describe the behavior you expected

a working solution using safari on old iPads

### Steps to reproduce the issue

after login on the browser nothin happens because of browser/javascript engine to old

### What version of Home Assistant Core has the issue?

docker 2023.1

### What was the last working version of Home Assistant Core?

docker 2020.1

### In which browser are you experiencing the issue with?

safari 9

### Which operating system are you using to run this browser?

iOS 9.3.5

### State of relevant entities

```txt
(TODO: add to wiki !)

Many had the same troubles like me:
Old iPads mounted to the wall are good enough as a touchscreen BUT
Lovelace UI is incompatible with iOS 9.3.5 the latest version for old iPads.

Behavior: you can connect to the homeassistant but after login you see "initializing" and wait forever.

Reason: Lovelace UI uses Polymere Javascript framework which needs newer browsers like Safari 11

Updating to the last 2 supported Browsers (Dolphin (tested), iCab (not tested €€€)) do not work because Dolphin uses iOS builtin Webkit Browserengine.

What works for some people: install homeassistant app on an iphone of a family member and then on the old ipad in appstore under family sharing (de: Familienfreigabe) you can download the latest compatible version of that app.

Solution: 2 steps

1) the last version of homeassistant docker container that kind of works with workaround is: 2021.12
Next version 2022.1 does not, even with workaround.  2021.12 has working knx integration

2) login token does still not work with 2021.12 so you need to switch to an alternatin authentication method, like trusted networks

---------------------------------------------------------

Here is what you need to do (in this order !!!)

1)
sudo docker pull homeassistant/home-assistant:2021.12

2)
sudo docker run -d \
 --restart unless-stopped \
 --name=homeassistant \
 -h homeassistant \
 -e PUID=1001 \
 -e PGID=1001 \
 -e TZ=CET \
 --net=host \
 -v homeassistant:/config \
    homeassistant/home-assistant:2021.12

3) connect on a PC and configure a user (doesn't work with trusted networks)
http://homeassistant.local:8123

4) enable trusted networks in configuration.yaml (insert first 5 rows end change to your net adress)
sudo nano /var/lib/docker/volumes/homeassistant/_data/configuration.yaml

----------------------------------------
homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.8.0/24

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
knx: !include knx.yaml      # if you need knx integration

-------------------------------------------------------------

5) (optional) add your knx configuration (no need for configuring IP interface or IP router)
this is my knx.yaml:
--------------------------------------------------------------

---
#knx:

  light:
  - name: Deckenlicht_Glastüre
    address: 0/0/4
  - name: Bar_Licht1
    address: 0/0/10
  - name: Wandlicht_Glastüre_Stiege
    address: 0/0/11

  cover:
  - name: Raffstore_Küche_Hoch_Tief
    move_long_address: 1/0/12
  - name: Raffstore_Küche_Stop
    move_long_address: 1/0/13
  - name: Raffstore Küche Pos1
    position_address: 1/0/27
  - name: Raffstore Küche Pos2
    position_address: 1/0/28

  switch:
  - name: Sofa_Stehlampe_steckdose_rechts
    address: 0/0/3
  - name: Alles_Aus1
    address: 0/5/1
  - name: Stiege_Steckdose_Christbaum
    address: 2/0/11

  sensor:
  - name: Strommessung_all_abfragen
    state_address: 5/0/0
    type: "active_energy"
    state_class: "total_increasing"
 
----------------------------------------------------------

6)  restart homeassistant
(ether via web browser on PC or via:
docker restart homeassistant 
)

7)  open safari on your iPad2 (iOS 9.3.5) and open the url:
http://homeassistant.local:8123
select your user and have fun!
```

### Problem-relevant frontend configuration

```yaml
iPad2 iOS 9.3.5
```

### Additional information

This is the solution so many people are looking for.
please add here to issues as well as to wiki to make it findable in the future

**Comment by steverep** [comment]
Is this an actual frontend issue?  If so, please paste errors you are getting in the browser console and give a better description of the behavior.

If you are just sharing an experience to help others, the community forum is the perfect place for that.

**Comment by 555wolfman** [comment]
> Is this an actual frontend issue? If so, please paste errors you are getting in the browser console and give a better description of the behavior.
> 
> If you are just sharing an experience to help others, the community forum is the perfect place for that.

No issue, but a solution / workaround to make it usable on all iOS 9 iPads.  As i didn’t find a solution after googeling for hours i want to help others to find this information in one thread.

**Comment by xinmans** [comment]
maybe not support battery metrics update？

**Comment by ThePolarCat** [comment]
So you only installed an older version of hass?

**Comment by tomadan1968** [comment]
> ### Verificare
> * [x]  Am actualizat la cea mai recentă versiune disponibilă de Home Assistant.
> * [x]  Am golit memoria cache a browserului meu.
> * [x]  Am încercat un alt browser pentru a vedea dacă are legătură cu browserul meu.
> 
> ### Descrieți problema pe care o întâmpinați
> Homeassistant real nu funcționează cu iPad-urile vechi (ios 9.3.5)
> 
> ### Descrieți comportamentul la care vă așteptați
> o soluție funcțională folosind Safari pe iPad-uri vechi
> 
> ### Pași pentru reproducerea problemei
> După conectarea în browser, nimic nu se întâmplă din cauza browserului / motorului JavaScript
> 
> ### Ce versiune de Home Assistant Core are problema?
> Docker 2023.1
> 
> ### Care a fost ultima versiune funcțională a Home Assistant Core?
> Docker 2020.1
> 
> ### În ce browser întâmpinați problema?
> Safari 9
> 
> ### Ce sistem de operare utilizați pentru a rula acest browser?
> iOS 9.3.5
> 
> ### Starea entităților relevante
> ```
> (TODO: add to wiki !)
> 
> Many had the same troubles like me:
> Old iPads mounted to the wall are good enough as a touchscreen BUT
> Lovelace UI is incompatible with iOS 9.3.5 the latest version for old iPads.
> 
> Behavior: you can connect to the homeassistant but after login you see "initializing" and wait forever.
> 
> Reason: Lovelace UI uses Polymere Javascript framework which needs newer browsers like Safari 11
> 
> Updating to the last 2 supported Browsers (Dolphin (tested), iCab (not tested €€€)) do not work because Dolphin uses iOS builtin Webkit Browserengine.
> 
> What works for some people: install homeassistant app on an iphone of a family member and then on the old ipad in appstore under family sharing (de: Familienfreigabe) you can download the latest compatible version of that app.
> 
> Solution: 2 steps
> 
> 1) the last version of homeassistant docker container that kind of works with workaround is: 2021.12
> Next version 2022.1 does not, even with workaround.  2021.12 has working knx integration
> 
> 2) login token does still not work with 2021.12 so you need to switch to an alternatin authentication method, like trusted networks
> 
> ---------------------------------------------------------
> 
> Here is what you need to do (in this order !!!)
> 
> 1)
> sudo docker pull homeassistant/home-assistant:2021.12
> 
> 2)
> sudo docker run -d \
>  --restart unless-stopped \
>  --name=homeassistant \
>  -h homeassistant \
>  -e PUID=1001 \
>  -e PGID=1001 \
>  -e TZ=CET \
>  --net=host \
>  -v homeassistant:/config \
>     homeassistant/home-assistant:2021.12
> 
> 3) connect on a PC and configure a user (doesn't work with trusted networks)
> http://homeassistant.local:8123
> 
> 4) enable trusted networks in configuration.yaml (insert first 5 rows end change to your net adress)
> sudo nano /var/lib/docker/volumes/homeassistant/_data/configuration.yaml
> 
> ----------------------------------------
> homeassistant:
>   auth_providers:
>     - type: trusted_networks
>       trusted_networks:
>         - 192.168.8.0/24
> 
> # Configure a default setup of Home Assistant (frontend, api, etc)
> default_config:
> 
> # Text to speech
> tts:
>   - platform: google_translate
> 
> group: !include groups.yaml
> automation: !include automations.yaml
> script: !include scripts.yaml
> scene: !include scenes.yaml
> knx: !include knx.yaml      # if you need knx integration
> 
> -------------------------------------------------------------
> 
> 5) (optional) add your knx configuration (no need for configuring IP interface or IP router)
> this is my knx.yaml:
> --------------------------------------------------------------
> 
> ---
> #knx:
> 
>   light:
>   - name: Deckenlicht_Glastüre
>     address: 0/0/4
>   - name: Bar_Licht1
>     address: 0/0/10
>   - name: Wandlicht_Glastüre_Stiege
>     address: 0/0/11
> 
>   cover:
>   - name: Raffstore_Küche_Hoch_Tief
>     move_long_address: 1/0/12
>   - name: Raffstore_Küche_Stop
>     move_long_address: 1/0/13
>   - name: Raffstore Küche Pos1
>     position_address: 1/0/27
>   - name: Raffstore Küche Pos2
>     position_address: 1/0/28
> 
>   switch:
>   - name: Sofa_Stehlampe_steckdose_rechts
>     address: 0/0/3
>   - name: Alles_Aus1
>     address: 0/5/1
>   - name: Stiege_Steckdose_Christbaum
>     address: 2/0/11
> 
>   sensor:
>   - name: Strommessung_all_abfragen
>     state_address: 5/0/0
>     type: "active_energy"
>     state_class: "total_increasing"
>  
> ----------------------------------------------------------
> 
> 6)  restart homeassistant
> (ether via web browser on PC or via:
> docker restart homeassistant 
> )
> 
> 7)  open safari on your iPad2 (iOS 9.3.5) and open the url:
> http://homeassistant.local:8123
> select your user and have fun!
> ```
> 
> ### Configurare frontend relevantă pentru probleme
> ```yaml
> iPad2 iOS 9.3.5
> ```
> 
> ### Erori JavaScript afișate în consola/inspectorul browserului
> _Niciun răspuns_
> 
> ### Informații suplimentare
> Aceasta este soluția pe care o caută atât de mulți oameni. Vă rugăm să adăugați aici la probleme, precum și la wiki pentru a le face găsibile în viitor

Does anyone know if this method still works?

**Comment by 555wolfman** [comment]
As it is a dedicated version it surely works.  But it could be possible that an update in one of the used polyfiller libraries (compatibility to oder browsers) fixed the issue in between. 

If you have problems with the latest image try the 2021 image i was successful with. 

The alternative is a newer used ipad those prices have fallen a lot. 

Ipad 2 was from 2011 and uses ios 9
Ipad Air 1 was from 2013 and updates to ios 12 which is great with the latest homeassistant.

As it is 11 years old you get it for a penny.

Olaf

**Comment by tomadan1968** [comment]
Ok, thank you !

**Comment by 555wolfman** [comment]
Here is a list of iPads and their latest IOS version:

https://maconline.de/blog/post/apple-ios-systemvoraussetzungen-iphone-ipad-watch-ios-version?srsltid=AfmBOop7uLcOVs6RaaV1HgTZLF-zdBgEryRkY8RStj9GnLMYaMQx6iAG

**Comment by 555wolfman** [comment]
Here is a list of iPads and their latest IOS version:

https://maconline.de/blog/post/apple-ios-systemvoraussetzungen-iphone-ipad-watch-ios-version?srsltid=AfmBOop7uLcOVs6RaaV1HgTZLF-zdBgEryRkY8RStj9GnLMYaMQx6iAG

**Comment by beren12** [comment]
Yeah auth has been broken for a few months on my 9.x iphone I use as an alarm clock and home controller on my nightstand. The home-dashboard app worked until I updated hass last week and now that can’t login either to get a token. Really miss using that.
