### ISSUE TITLE
UX Improvement: Move "Save" button in the automation edit dialog and similar dialogs

### ISSUE THREAD

**Issue by CodingSpiderFox** [home-assistant/frontend#16350]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I was editing an automation and wanted to save the changes. I was desperately looking for the save button as I am not familiar with the UI.
I am using a very large screen. After searching and searching, I realized that Windows 11 had opened a notification tile in the bottom right corner. After clicking away that tile, the button appeared behind it.

### Describe the behavior you expected

I would find it more intuitive when the button would be at the bottom right corner right under the edit area.
This would result in less searching on the screen and less mouse movement required.

Should look like this (awesome MSPaint Skills ;) )

<img width="1295" alt="homeassistant" src="https://user-images.githubusercontent.com/25173078/235301930-ec52fd0a-2348-42fc-8820-eeab60acd5d5.png">

### Steps to reproduce the issue

Install a large 4k screen, use windows with notifications enabled, start editing automations while notifications appear

### What version of Home Assistant Core has the issue?

core-2023.4.6

### In which browser are you experiencing the issue with?

112.0.5615.138

### Which operating system are you using to run this browser?

Windows 11

**Comment by matthiasdebaat** [comment]
We use the material guidelines for the FAB. I agree that on larger screens the button is too far away from the content. Introducing the[ Bottom app bar](https://m3.material.io/components/bottom-app-bar/overview) could fix this.

**Comment by christophwen** [comment]
Do you (all participating in this discussion) think that there are some needed changes here, or can this issue be closed?

**Comment by CodingSpiderFox** [comment]
> I tried to find an alternative, but I couldn't think of anything better. I agree with @bramkragten about the bottom app bar.
> 
> > I'm not against moving the FAB on bigger screens, but it might have some unforeseen consequences. What do you think?
> 
> In my opinion, the position of the button should remain as it is, since this design is used in many areas of HA.

Of course if this is changed, that should be changed consistently across the UI

> I think users of very large screens who use web browser windows in full screen mode are used to having the elements spread out on most websites (especially with user interface websites in contrast to content "only" websites).

I can't name any app that spreads the buttons so far away from their context. Even if most other people are used to using apps doing it like current Home Assistant UI, I don't think that the current behaviour allows an efficient workflow.

> I also think that a Windows notification should not affect the design, because if you were to assume that, then you would have to factor in many other types of notifications and positions of them. An example would be macOS, which displays notifications on the top right.

That is a very good point. Still I think that it might help many people because I don't think there are many desktops which would display notifications in the center of the screen. Most ubuntu-based distros also display their notifications in the top right corner. So having the buttons in the center, aligned to the right bottom corner of the form, it will be better for all windows users but might not bother many other OS users.

**Comment by christophwen** [comment]
> I can't name any app that spreads the buttons so far away from their context. Even if most other people are used to using apps doing it like current Home Assistant UI, I don't think that the current behaviour allows an efficient workflow.

Could you give an example of an app that uses M3 (or similar) as a design guide and makes better use of the FAB?
That would be very helpful, thank you.

**Comment by CodingSpiderFox** [comment]
What is M3 and FAB?

**Comment by CodingSpiderFox** [comment]
Thanks for the clarification.
Unfortunately, I don't know any official resources on that topic. I would just do it like I suggested in the picture I included in the initial issue description,

**Comment by bramkragten** [comment]
![image](https://github.com/home-assistant/frontend/assets/5662298/b875113d-2e04-4571-908b-fba9d9afa167)
