### ISSUE TITLE
friendly_name template not correctly shown in more-info card

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#16361]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

<img width="590" alt="Scherm­afbeelding 2023-05-01 om 14 36 52" src="https://user-images.githubusercontent.com/33354141/235453848-c500a893-1b50-43ed-8803-a155544f7809.png">

Shows the correct name atop of the card, but None in the name field (which is the spot of the template in the yaml config)

even the main card of this entity shows the correct Friendly name:

<img width="556" alt="Scherm­afbeelding 2023-05-01 om 14 40 08" src="https://user-images.githubusercontent.com/33354141/235453956-67391a6d-29a6-4753-8fe4-3d6ca34bd7a8.png">

And dev tool templates returns correctly:

<img width="655" alt="Scherm­afbeelding 2023-05-01 om 14 46 30" src="https://user-images.githubusercontent.com/33354141/235453978-543cd045-850b-402e-a5dd-f4a6286da474.png">

This is all a bit surprising, because Ive had these covers for a long time, and tbh, only now moved to add aliases via the UI, so noticed this for the first time.

Moreover, the [documentation](https://next.home-assistant.io/integrations/cover.template/#friendly_name) does Not mention templates on this config option for friendly_name.

### Describe the behavior you expected

show the correct friendly_name

### Steps to reproduce the issue

1. create template and set yaml like in example
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.5.0b5

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

Ventura 13.2 Mac

### State of relevant entities

```txt
current_position: 100
device_class: shutter
friendly_name: Rolluik Logeerkamer template
supported_features: 15
id: logeerkamer
```

### Javascript errors shown in your browser console/inspector

```txt
no error in Inspector, nor in homeassistant.log
```

### Additional information

yaml for the template covers:

```
cover:

  - platform: template
    covers:

      rolluik_studenten_template:
        unique_id: rolluik_studenten_template
        <<: &config
          device_class: shutter
          friendly_name: >
            Rolluik {{this.attributes.get('id')|title}} template
          open_cover:
            service: cover.open_cover
            target: &cover
              entity_id: >
                {% set id = this.attributes.get('id') %}
                {% set silent = states('input_boolean.discrete_covers') %}
                {% if silent == 'on' %} cover.rolluik_{{id}}_low_speed
                {% else %} cover.rolluik_{{id}}
                {% endif %}
          position_template: >
            {% set id = this.attributes.get('id') %}
            {{state_attr('cover.rolluik_'~id,'current_position')}}
          close_cover:
            service: cover.close_cover
            target: *cover
          stop_cover:
            service: cover.stop_cover
            target: *cover
          set_cover_position:
            service: cover.set_cover_position
            target: *cover
            data:
              position: '{{position}}'
          availability_template: >
            {% set id = this.attributes.get('id') %}
            {{state_attr('cover.rolluik_'~id,'current_position')|is_number}}

      rolluik_logeerkamer_template:
        unique_id: rolluik_logeerkamer_template
        <<: *config
```

and id's are set in customize

```
homeassistant:

  customize:

    cover.rolluik_studenten_template:
      id: studenten
    cover.rolluik_logeerkamer_template:
      id: logeerkamer
```

have several more of these

<img width="663" alt="Scherm­afbeelding 2023-05-01 om 14 58 26" src="https://user-images.githubusercontent.com/33354141/235454714-14266519-0546-480d-9446-10769fbf5176.png">

and

<img width="1040" alt="Scherm­afbeelding 2023-05-01 om 14 59 16" src="https://user-images.githubusercontent.com/33354141/235454785-a9e6d791-04ed-4924-a890-b1c847749ea0.png">

Note friendly_name is populated correctly..

I did suspect the cloud config on these entities at first, but that cant be it, because those look like:
```
      cover.rolluik_logeerkamer_template:
        name: Rolluik guestroom
#         aliases:
#           - Luik Gastkamer
#           - Luik Logeerkamer
        room: Logeerkamer
```

(commented aliases are now in the UI)

Final test, changing the template to 

```
          friendly_name: >
            Rolluik {{this.attributes.get('id')}} template
```
so, take out the `|title` results in

<img width="553" alt="Scherm­afbeelding 2023-05-01 om 15 06 17" src="https://user-images.githubusercontent.com/33354141/235455572-9874d1f4-19e4-4543-ab09-92aec38732e7.png">

<img width="580" alt="Scherm­afbeelding 2023-05-01 om 15 06 25" src="https://user-images.githubusercontent.com/33354141/235455575-f68e576c-b46a-415c-8c5f-2ac85ccab19c.png">

which proves the template does in fact work, and set the friendly_name correctly.

**Comment by piitaya** [comment]
According to the documentation, `friendly_name` is not a template but a string 🤔 (source: https://www.home-assistant.io/integrations/cover.template/)

**Comment by Mariusthvdb** [comment]
Yes that is what I posted in the opening topic.
However it does work correctly as you can see in my example ( have more) and in dev tools (states And templates)

In any case, this is the only spot in the Frontend where the friendly name is Not correct.

I did have a quick look at the source code and no template is mentioned specifically in the cover.

That could (should?) be amended also ..

**Comment by Mariusthvdb** [comment]
Keep open not resolved
