### ISSUE TITLE
Battery sensors not colored in device list, or entities overview

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#16367]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

as title, battery entities are not colored:

<img width="1229" alt="Scherm­afbeelding 2023-05-01 om 22 41 23" src="https://user-images.githubusercontent.com/33354141/235527677-237a43c6-f056-4e16-bdf0-0caca8e5a052.png">

or clicking to navigate to that device entities list:

<img width="355" alt="Scherm­afbeelding 2023-05-01 om 22 43 18" src="https://user-images.githubusercontent.com/33354141/235527826-e935e6f9-55a5-430f-acd6-56518e90d076.png">

while clicking that entity itself, shows the colored icon in the more-info pane:
<img width="592" alt="Scherm­afbeelding 2023-05-01 om 22 44 04" src="https://user-images.githubusercontent.com/33354141/235527924-ac09e738-4298-4fc9-9040-16260807dad4.png">

### Describe the behavior you expected

olor all battery entities accordingly

### Steps to reproduce the issue

1. navigate device page (in this case Z-Wave)
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.5.0b5

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

Mac OS 13.3

**Comment by Mariusthvdb** [comment]
btw, when adding those diagnose entities to the suggested add-to-dashboard the battery entity gets omitted... ;-)

<img width="560" alt="Scherm­afbeelding 2023-05-01 om 22 47 05" src="https://user-images.githubusercontent.com/33354141/235528547-ca425311-3475-497e-96e6-2dafb71e5076.png">

**Comment by Mariusthvdb** [comment]
I know how to color those icons in the dashboard and they are automatic in the more-info.

My pointing, they are not automatically colored in the device overview, nor can we set the state_color: true.

seems a strange discrepancy, especially on the Diagnose panel.
compare:

colors in the sensors panel:

<img width="336" alt="Scherm­afbeelding 2023-05-02 om 14 45 10" src="https://user-images.githubusercontent.com/33354141/235669876-6b942e16-3807-4131-a51a-b7f160d0b622.png">

or for another sensor the Diagnose:

<img width="333" alt="Scherm­afbeelding 2023-05-02 om 14 45 17" src="https://user-images.githubusercontent.com/33354141/235669967-8f66b8fd-e645-4b1e-af6a-65c269e90579.png">

Aware these are set using custom-ui, but given the fact battery entities are colored in HA core/frontend, a simple `state_color: true` option would be very welcomed, and make these panels give way more direct visual impact (and informative power)

**Comment by piitaya** [comment]
It's a config/setting screen so it's uncolored to keep it simple and clear. In general list are uncolored in the app (except for entities card the user can set the option to `true`.

I'm not again changing it should be discussed and if we do this, we need to do it for all entities, not just batteries.

**Comment by Mariusthvdb** [comment]
sure, agreed, and appreciated, thanks

**Comment by ildar170975** [comment]
I think that there are places in UI where colors should NOT be state-dependant.

For instance, Settings -> Devices & Services -> Entities: all entities' icons (incl. unavailable) have same color (for me this is OK):
![изображение](https://user-images.githubusercontent.com/71872483/235947197-b677f942-f647-4651-9a4f-798e1e9bfda1.png)

Device page:
unavailable entities have a grey color; entities with "home" &  "not_home" states have same color (again OK for me):
![изображение](https://user-images.githubusercontent.com/71872483/235947132-691f020f-821f-4ff7-a796-c39ca0c7b6fb.png) 
![изображение](https://user-images.githubusercontent.com/71872483/235947305-791c32e6-3862-4415-8ba3-814657029258.png)

**Comment by Mariusthvdb** [comment]
sorry bout that,

was typing while I clicked the close..

seems we agreed above, so for me I can close this.

**Comment by ildar170975** [comment]
> so for me I can close this. ok?

Dear Marius, not sure who are you asking...
My personal opinion - "yes, this issue may be closed".

**Comment by piitaya** [comment]
Thanks for closing it. BTW, here's the fix for the "add to dashboard" feature for battery entity: https://github.com/home-assistant/frontend/pull/16373
