### ISSUE TITLE
Dashboard Security-Cam-View keeps reloading and is not starting

### ISSUE THREAD

**Issue by Finnlife** [home-assistant/frontend#16374]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

For some weeks, I have an error with the Homeassistant Dashboard “MoreInformation”-View.

I use my old Android-Tablet with the Fully Kiosk Mode App.

That all works great. But when I try to load an RSTP-Stream by clicking on the Dashboard-Card, the first image shows up but the Video-Box keeps reloading / loading.
The max-length of the video keeps getting longer, but the current-video-position keeps being stuck at 0.

### Describe the behavior you expected

The Stream of the RSTP-Stream schould play.

### Steps to reproduce the issue

Not really reproducible. Seems like a Version Bug to me.
1. Create a picture-enity card in a Homeassistant Dashboard
2. Use a Camera RSTP-Stream as Source.
3. Click on the Picture and wait for the Stream to load.

### What version of Home Assistant Core has the issue?

2023.4.6

### In which browser are you experiencing the issue with?

Google Chrome 112.0.5615.135

### Which operating system are you using to run this browser?

Android 8.1.0; SM-T585 Build/M1AJQ

### Javascript errors shown in your browser console/inspector

```txt
I tried to get more information by connection to the tablet via USB and try to read the Console output and the Connections via the Chrome Inspector DevTool.

But the Console keeps empty. Some request are being cancelled, but I can’t figure out why and how they are cancelled.
The cancelled request are relevant requests, so I think the cancelation is the problem. But I can’t figure out why they are being cancelled.

I also tried to do the same in Chrome on the device, but it’s the same problem.

In my PCs browser, there is no problem at all.
So it might a Version Problem?
```

### Additional information

Home Assistant 2023.4.6
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230411.1 - latest

**Comment by Finnlife** [comment]
Unfortunately not.
I already asked in the LTT Forum, Subreddit, Discord and multiple other Forums.
A "Homeassistant Expert" on Fiverr asked me to reinstall HA.
But I hope there is another solution for this.

**Comment by danielputschoegl2** [comment]
Sorry to hear that, got the same problem - no solution.

**Comment by Finnlife** [comment]
Yeah, I thought if there is a platform where I could set a money reward for the solution to this problem.
Would be a great way to support the fix of these Problems and finance features.

How long is your Instance of HA installed?

**Comment by danielputschoegl2** [comment]
About 1,5 years on a then new RPI 4

**Comment by Finnlife** [comment]
Yeah, mine is like 1–2 Years old.
So we will just be able to wait for any help, I think.
