### ISSUE TITLE
Connection status messages in the ESPHome dashboard do not display correctly.

### ISSUE THREAD

**Issue by Murianwind** [home-assistant/frontend#16405]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The ESP device is connected, working fine, and I can even see the logs, but the dashboard display OFFLINE.

![image](https://user-images.githubusercontent.com/6447460/236102683-e7fb7ac5-5349-4e59-97e9-c955e33b93b7.png)

### Describe the behavior you expected

I want it to be visible online.

### Steps to reproduce the issue

1. Launch the Web UI from the ESPHome add-on.
2. After a period of time, the connected ESP device will be marked as ONLINE.
3. Some devices are connected but still show as OFFLINE.

### What version of Home Assistant Core has the issue?

Home Assistant 2023.5.0

### Additional information

ESPHome Current version: 2023.4.4
The connected ESP is 8266 and the ESP marked as offline is ESP32.

**Comment by bramkragten** [comment]
Please create this issue in the repo of ESPHome, this is just for the frontend of Home Assistant
