### ISSUE TITLE
Icelandic language shows english weekdays and months in Chrome

### ISSUE THREAD

**Issue by kristjanbjarni** [home-assistant/frontend#16403]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Switching to Icelandic language in the frontend doesn't show correct weekdays, months and other date formatting text correctly like "x hours ago". This only happens with Chrome. Other browsers like Firefox and Edge show the correct text. This seems to be related to Chrome only supporting limited number of languages for their ECMAScript Internationalization API (Intl).

There is a bug report for this in Chromium here, however this seems to be a wontfix. Already 4 years and counting.
https://bugs.chromium.org/p/chromium/issues/detail?id=956072

So the only fix would be to use a shim or some kind of fixed date handling library.

### Describe the behavior you expected

The calendar card should show the localized names of weekdays and months.

### Steps to reproduce the issue

1. Use Chrome browser on desktop
2. In Home Assistant frontend go to profile and change language to "Íslenska"
3. Add calendar card
4. The calendar card displays english weekdays instead of Icelandic weekdays

### What version of Home Assistant Core has the issue?

2023.4.6

### In which browser are you experiencing the issue with?

Google Chrome 113.0.5672.64

### Which operating system are you using to run this browser?

Windows 10 Pro

**Comment by brebtatv** [comment]
I think I have the same problem in the Czech language. Part of the entities is in Czech and part in English.

**Comment by spacegaier** [comment]
> I think I have the same problem in the Czech language. Part of the entities is in Czech and part in English.

I am not certain if you are talking about the same scenario. OP's topic is localization data through the browser such as date and time formats and names of days. Do you observe the same issue for Czech or are you talking about missing translations of texts inside HA in that language (which would be a separate topic)?

**Comment by spacegaier** [comment]
@bramkragten We are already using `formatjs` in the frontend. So might it therefore be an option to include a polyfill for Islandic, e.g. as shown in this Chromium comment: https://bugs.chromium.org/p/chromium/issues/detail?id=956072#c25
