### ISSUE TITLE
onboarding.html no any settings just showing title after configuring home setting.

### ISSUE THREAD

**Issue by Innei** [home-assistant/frontend#16413]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

No any setting.

<img width="1522" alt="image" src="https://user-images.githubusercontent.com/41265413/236253195-fbd004ee-f567-4570-9533-400c341397cb.png">

After refresh browser, got login page.

After login, redirect /onboarding.html and loop.

<img width="1535" alt="image" src="https://user-images.githubusercontent.com/41265413/236253426-78482963-0fb6-4451-87e5-a20c8a2a058c.png">

### Describe the behavior you expected

Go to dashboard.

### Steps to reproduce the issue

1. sudo docker run -d \
                    --name hass \
                    --privileged \
                    --restart=unless-stopped \
                    -e TZ=Asia/Shanghai \
                    -v ~/docker/hass/config:/config \
                    --network=host \
                    docker.io/homeassistant/home-assistant:latest
2. go to configure hass.
3. after configure home setting and next prviate setting.
4. will loop onboarding.html and auth page
...

### What version of Home Assistant Core has the issue?

2023.5

### In which browser are you experiencing the issue with?

Every browser, between chrome and safari, even claer any cache.

**Comment by shaonianzhentan** [comment]
add in “integration” after “analytics” 

https://community.home-assistant.io/t/stuck-on-onboarding-html/567695/12

![image](https://user-images.githubusercontent.com/5294022/236432473-f5055d2b-cf0e-499a-8d86-e96628618562.png)

**Comment by bramkragten** [comment]
Fixed
