### ISSUE TITLE
Area in new expose panel wrong

### ISSUE THREAD

**Issue by jeroenvdd** [home-assistant/frontend#16415]
### The problem

I think I might have found (a little) bug.

I have a device (relais board) that post all relais as switches.

I’ve 'converted the ones that are lights to lights and added the light to the correct area.

When I go through entities it is in the correct area:
![image](https://user-images.githubusercontent.com/6975276/236264710-e2e15345-6ce5-4015-be11-ed8894372de9.png)
now when i look for the exact same device trough the expose panel:
the area is the original location of the ‘before type of a switch change’
![image](https://user-images.githubusercontent.com/6975276/236264760-7ea8623b-1a46-4605-aae4-7a8aec09aa08.png)

### What version of Home Assistant Core has the issue?

core-2023.5.0

### What was the last working version of Home Assistant Core?

core-2023.4.0

### What type of installation are you running?

Home Assistant OS

**Comment by bramkragten** [comment]
This should be fixed, can you confirm?

**Comment by jeroenvdd** [comment]
> This should be fixed, can you confirm?

Yes, I updated to latest build and it seems to be correct now
