### ISSUE TITLE
Lovelace 20230503.1 z-index faulty

### ISSUE THREAD

**Issue by ohkaja** [home-assistant/frontend#16418]
### The problem

Hello,

just updated to 2023.5.0. Therefore the frontend gets updatet too to  20230503.1. Since that the z-index in picturecards is faulty.

A Screenshot from before reloading to new version:
<img width="675" alt="image" src="https://user-images.githubusercontent.com/93218188/236297416-cc3b97f9-344b-4b20-9228-a5e9360dce41.png">

A Screenshot after reloading with new version:
<img width="874" alt="image" src="https://user-images.githubusercontent.com/93218188/236297581-ee605143-3eaf-496a-a9b8-379df7ec1dd3.png">

It´s platform un-idependet. Noticed this on mobile and went to my pc to check.

A code snippet from one item in question from my picturecard:
´´  - type: state-icon
    entity: light.grp_f2_bad
    icon: mdi:light-recessed
    style:
      opacity: 0.5
      background: white
      border: 1px dotted gray
      border-radius: 100px
      top: 11%
      left: 26%
      z-index: 50
      transform: scale(75%, 75%)
    tap_action:
      action: toggle´´

### What version of Home Assistant Core has the issue?

core-2023.5.0

### What was the last working version of Home Assistant Core?

core-2023.4.5

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

lovelace

**Comment by bramkragten** [comment]
Why do you have a z-index of 50? That is way too high. If you make it lower that will fix it.

**Comment by ohkaja** [comment]
Thanks for the Reply. I use this high index in case of importand things to display this „above all“. This worked the last 2 years and there is no reason why this should not work now. 
also if i use indexes from 1-10 the behavoir comes up sometime. So there must be a problem in the rendering engine.

**Comment by ohkaja** [comment]
Again, i must insist. On the actual 2023.11.0 the shown behavoir pops up on z-index´es > 3.
