### ISSUE TITLE
Cant select installed Piper or Whisper

### ISSUE THREAD

**Issue by Lux315** [home-assistant/frontend#16422]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I installed Piper and Whisper, activated the wyoming integration.

If i go to voice assistant and try to create a new pipeline, both piper and whisper are greyed out and cant be selected.

Tried on different systems and multiple reboots.

### Describe the behavior you expected

Piper and Whisper selectable

### Steps to reproduce the issue

1. install piper and whisper
2. go to voice assistants
3. create new
...

### What version of Home Assistant Core has the issue?

2023.5.1

### What was the last working version of Home Assistant Core?

x

### In which browser are you experiencing the issue with?

IOS app, Android app, Safari, Chrome etc

**Comment by Lux315** [comment]
![IMG_5163](https://user-images.githubusercontent.com/67388320/236387203-370f3636-9cf5-4615-97a5-5685e1bab70c.jpeg)

**Comment by EnerGeh** [comment]
Add `assist_pipeline:` to your `configuration.yaml` if you don't use default config.

**Comment by Lux315** [comment]
I did it, but didnt change anything. What else do i have to add to the configuration.yaml?

**Comment by EnerGeh** [comment]
Reboot?!

**Comment by Lux315** [comment]
Yes both addons configured and wyoming aswell. 

But theyre still greyed out. If i change the language to english, i can select piper and whisper, but not with german.

Is "assist_pipeline:" the only thing i need im configuration.yaml?
Only this section shouldnt change anything or not?

**Comment by Lux315** [comment]
After a few restarts and complete system restarts its working with your solution. Thanks a lot!

**Comment by buffcode** [comment]
I had the exact same problem.

The default configs only work if your language is English. Otherwise the addons will be detected but greyed out as they do not match your Assist language.

1. Open `Piper Addon -> Configuration` and select a voice matching your language (eg. `de-....`)
2. Open `Whisper Addon -> Configuration` and select your language (eg. `de`)

Reload both integrations from the integration overview, after that both addons are selectable in the Assist dialog.
