### ISSUE TITLE
Log Entry: Logger: frontend.js.latest.202305032 error

### ISSUE THREAD

**Issue by gb095666** [home-assistant/frontend#16431]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have upgraded to the latest version and have seen the following error in the System log area

Logger: frontend.js.latest.202305032
Source: components/system_log/__init__.py:257
First occurred: 17:46:39 (1 occurrences)
Last logged: 17:46:39

http://homeassistant:8123/frontend_latest/14971-y8cnXictt9k.js:1:1507 Uncaught NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://homeassistant:8123/frontend_latest/1827-Gpeacx_K1Lw.js' failed to load.

### Describe the behavior you expected

I have not seen this error before.

### Steps to reproduce the issue

It seemed to happen when I went into

"Settings" --> "System" --> "Repairs" 

But I cant be sure if it was just a coincidence. 

### What version of Home Assistant Core has the issue?

2023.5.1

### What was the last working version of Home Assistant Core?

Probably 2023.4, I noticed it after upgrading to 2023.5

### In which browser are you experiencing the issue with?

Google Chrome Version 112.0.5615.139 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Edition	Windows 10 Pro Version	22H2 Installed on	‎31/‎05/‎2020 OS build	19045.2846 Experience	Windows Feature Experience Pack 120.2212.4190.0

**Comment by steverep** [comment]
Please find the corresponding browser console error and paste it with your issue.  Ulike the core log, it has more info and the full JS stack trace.
