### ISSUE TITLE
Automations Scroll Bug

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#16451]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi when im Scrolled all the way down in Automations and something type to Searach Bar won't show me Automation only if Scroll back Up.
![image](https://user-images.githubusercontent.com/42905545/236635297-f351bbb4-86ad-4ef4-9f93-d7b6eda5ed01.png)

### Describe the behavior you expected

*

### Steps to reproduce the issue

*

### What version of Home Assistant Core has the issue?

*

**Comment by ildar170975** [comment]
Cannot confirm this.
1. Open Automations list.
2. Note the 1st entry in the list (let it be `automation.xxx_co2`).
3. Scroll down to the last row.
4. The 1st entry is not displayed.
5. Type "co2" in the "search" field.
6. The 1st entry is displayed (along with other matches).

Consider closing the issue as resolved.
