### ISSUE TITLE
Security issue - search button allows unauthorized access to all entities

### ISSUE THREAD

**Issue by gednet** [home-assistant/frontend#16457]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Placing an **search button at the top of dashboard** and not being able to disable this icon is a **major security issue** in Home Assistant. Any person with access to the wallpanel **_can make an unauthorized change to any entity or read its state._** This excludes the possibility of safely placing the wallpanel in a place to which unauthorized persons, such as children, may have access. Despite the limited view of the dashboard (with only needed entities), any person can make intentional or accidental changes in all available entities (e.g. related to alarms, garage doors, turno on or off automation, etc.).

### Describe the behavior you expected

The possibility of disabling this icon at the user level should be made as soon as possible. Users without administrator rights cannot have this icon visible.

### Steps to reproduce the issue

Click on the search button at the top of the dashboard on the wallpanel.

### What version of Home Assistant Core has the issue?

Home Assistant 2023.5.2 Supervisor 2023.04.1 Operating System 10.1 Interfejs użytkownika: 20230503.3 - latest

### In which browser are you experiencing the issue with?

Fully Kiosk Browser

### Which operating system are you using to run this browser?

Android

**Comment by gednet** [comment]
And the same  problem is with shortcut key "e" - it is possible to open the search window. It's very big issue. If it's possible to  hide "tgree-dots button" for users without admiistrators privilegs that is possible to hide the search window and search button simply users.

**Comment by CheezyDotDev** [comment]
I have just encountered the same problem. This is a major security vulnerability that can cause a lot of damage and should be fixed as soon as possible.

**Comment by gednet** [comment]
There is solution for this issue? I must have turn off wallpanel, because it's possible to change everything in HA without privileges :/

**Comment by frenck** [comment]
This is not a bug or security issue. Every user has effectively "owner" rights. This has been actively documented forever as well:

https://www.home-assistant.io/docs/authentication/#user-accounts

<img width="731" alt="CleanShot 2023-05-29 at 19 37 43@2x" src="https://github.com/home-assistant/frontend/assets/195327/ab436e9e-b7f7-4bcb-b293-8b01ef23c818">

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck

**Comment by gednet** [comment]
In my opinion, this is a serious mistake, because if you can hide the
"three dots" button for a group of non-admin users, then there is no
problem to hide the "magnifying glass button" for normal users as well. Any
person (guest, outsider) can make any changes via a tablet with a
wallpanel! You don't even need to create new accounts - if the tablet with
the application is an integral part of home automation systems, you must
not allow any person to make changes at the administrator level!

It's very serious issue.

With best regards
Chris

pon., 29 maj 2023 o 19:38 Franck Nijhof ***@***.***>
napisał(a):

**Comment by frenck** [comment]
> In my opinion, this is a serious mistake

You are not alone, as pointed out above, we have the community forums for raising such concerns/feature requests.

> It's very serious issue.

At this point is not an issue, but by design. You don't have to agree with it, however, it is not a bug.

../Frenck
