### ISSUE TITLE
Recent changes to fan entities prevents you from setting air purifiers to auto mode through the UI.

### ISSUE THREAD

**Issue by 10Thirty** [home-assistant/frontend#16468]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The recent changes to fan entities has removed the ability to set operating mode to auto on air purifiers.

![image](https://user-images.githubusercontent.com/58256824/236797551-7402b2e7-e08f-49c6-b001-e9b9bde1c1b8.png)

![image](https://user-images.githubusercontent.com/58256824/236798031-6edbb13b-1fb0-4f03-b148-de51e95acca2.png)

### Describe the behavior you expected

On previous versions you could select the fan speed you wanted or auto from the drop down list. 

### Steps to reproduce the issue

1. Have an air purifier that has an auto mode.
2. Open the entity card for the device.
3. Not have auto mode as an option anywhere in the UI

### What version of Home Assistant Core has the issue?

2023.5.2

### What was the last working version of Home Assistant Core?

2023.3

### In which browser are you experiencing the issue with?

Version 112.0.5615.139 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 Pro 19044.2846

### State of relevant entities

```txt
preset_modes: auto, sleep
percentage: null
percentage_step: 33.333333333333336
preset_mode: auto
active_time: 0
screen_status: on
mode: auto
friendly_name: Study Levoit 131S Air Purifier
supported_features: 1

preset_modes: auto, sleep
percentage: null
percentage_step: 25
preset_mode: auto
screen_status: false
child_lock: false
night_light: off
mode: auto
friendly_name: Living Room Core 400s Air Purifier
supported_features: 1
```

**Comment by mt0321** [comment]
Can confirm this capability was lost in 2023.4.

The ability to change preset mode via the UI used to look like this: https://user-images.githubusercontent.com/1765921/117100878-82da8700-ad3a-11eb-97c6-99b0e074c057.png
