### ISSUE TITLE
9684 Uncaught TypeError: e.toFixed is not a function

### ISSUE THREAD

**Issue by dave-code-ruiz** [home-assistant/frontend#16467]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Bug: Here http://ha-ip:8123/config/entities with climate entities it only allows to reduce temp, not to increase it, in log show:

2023-05-08 09:07:54.514 ERROR (MainThread) [frontend.js.latest.202305033] https://homeassistant.patopatojum.duckdns.org/frontend_latest/10448-qZspSHl3CNU.js:1:9684 Uncaught TypeError: e.toFixed is not a function

I only have climate entities of custom HACs integration:

https://github.com/dave-code-ruiz/uhomeuponor

But i think error is in all climate entities

Please verify it , with steps to reproduce the issue, thanks

### Describe the behavior you expected

climate entities should be reduce temp and increase it

### Steps to reproduce the issue

1. Go to http://ha-ip:8123/config/entities
2. Search climate entity
3. Reduce temp, and increase it

### What version of Home Assistant Core has the issue?

Home Assistant 2023.5.2

### What was the last working version of Home Assistant Core?

Home Assistant 2023.5.2

### In which browser are you experiencing the issue with?

Google Chrome Versión 112.0.5615.138 (Build oficial) (64 bits)

### Which operating system are you using to run this browser?

windows 10

### Problem-relevant frontend configuration

```yaml
Version Frontend 20230503.3 - latest
No frontend or lovelace configuration i use built in page http://ha-ip:8123/config/entities
```

### Javascript errors shown in your browser console/inspector

```txt
ha-climate-control.ts:70 Uncaught TypeError: e.toFixed is not a function
    at F.value (ha-climate-control.ts:70:36)
    at F.value (ha-climate-control.ts:74:27)
    at F.handleEvent (lit-html.ts:2003:29)
value	@	ha-climate-control.ts:70
value	@	ha-climate-control.ts:74
handleEvent	@	lit-html.ts:2003
```

**Comment by dave-code-ruiz** [comment]
i forget comment i have same error in my mobile phone S21 with Chrome App and with Homeassistant App

**Comment by pakillo77** [comment]
Why did you refunded my coffee?

**Comment by dave-code-ruiz** [comment]
I have refunded it by mistake, hehehe

**Comment by pakillo77** [comment]
Ok, I paid a new persistent one

**Comment by dave-code-ruiz** [comment]
ok, not is needed , buy thanks a lot, this motivates me to continue develop
