### ISSUE TITLE
Sensor Card doesn't show zero value

### ISSUE THREAD

**Issue by darynwilkinson** [home-assistant/frontend#16481]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Looking at a history graph shows zero values for sensors with zero, but the sensor graph never shows the graph go down to zero. It always looks like there are some lights on in the example below.

<img width="501" alt="image" src="https://user-images.githubusercontent.com/22393914/237062854-15ef9102-6e88-40de-94d8-a8886da95505.png">

### Describe the behavior you expected

I would expect to see the sensor card graph go down to zero when the value is zero.

### Steps to reproduce the issue

Add a sensor card to a dashboard with an entity that has zero values.

### What version of Home Assistant Core has the issue?

2023.5.2

### What was the last working version of Home Assistant Core?

NA

**Comment by Xitee1** [comment]
I have the same issue. It seems like this is the lowest possible level it can get to. I use it for showing my solar production and at night it would not go below that level.

**Comment by ildar170975** [comment]
This is a Sensor card.
https://www.home-assistant.io/dashboards/sensor/
It shows INTERPOLATED line:
![image](https://github.com/home-assistant/frontend/assets/71872483/1d49b09b-0d8c-4142-a4f6-06b3ea9663da)
No wonder it misses some values.
Suggestion: if you need a more precise graph - do NOT use the Sensor card.
