### ISSUE TITLE
overflow:hidden not removed from body when notifications panel closed

### ISSUE THREAD

**Issue by Peter-HVD** [home-assistant/frontend#16498]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When the notifications panel is expanded "overflow:hidden" is added to the body element, but when it is closed it is not being removed, so the main window is not scrollable.

### Describe the behavior you expected

overflow:hidden should be removed when the panel is closed

### Steps to reproduce the issue

1. Open inspector palette in Chrome or Safari
2. Click the Notifications button
3. Observe the overflow:hidden being added to the body element
4. Click the close button to hide the notifications panel
5. Observe that overflow:hidden has not been removed
...

### What version of Home Assistant Core has the issue?

2023.5.2

### What was the last working version of Home Assistant Core?

don't know

### In which browser are you experiencing the issue with?

Google Chrome Version 112.0.5615.137 (Official Build) (x86_64), Apple Safari Version 16.4 (18615.1.26.110.1) and macOS app 2023.4 (2023.460)

### Which operating system are you using to run this browser?

macOS Ventura 13.3.1 (a)

### Javascript errors shown in your browser console/inspector

```txt
None
```

**Comment by messiuw** [comment]
Apparently, the Material Design Drawer never finishes the closing animation. As such, the MDCDrawerAdapter in ha-drawer.ts never calls the releaseFocus() Method to remove the overflow: hidden from the document body. Might be a material design bug?
