### ISSUE TITLE
Statistics Graph Card Order of entities

### ISSUE THREAD

**Issue by erkr** [home-assistant/frontend#16500]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Statistics Graph Card order representing the entities in the legend is magically (seems the order of when the entities were added to HA).
This makes it hard to have homogeneous colour coding screens different cards.

### Describe the behavior you expected

I expect that the legend is ordered according the order of declaration the entities in the card.

### Steps to reproduce the issue

Change the order of declaring the entries in the card and observe that the legend doesn’t change at all.

### What version of Home Assistant Core has the issue?

Core 2023.5.1

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

Mobile, windows…

**Comment by karwosts** [comment]
Submitted a PR with a fix.
