### ISSUE TITLE
Sure Petcare - State of locked sensors is always unlocked

### ISSUE THREAD

**Issue by PPCM** [home-assistant/frontend#16503]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I scheduled the surepet device to automatically during the day, and it works
But in HA, locked_all, locked_in and locked_out are always with the state unlocked, even if the device is locked

I tryed to force the lockdown, and sensors are style unlocked in HA

### Describe the behavior you expected

When the device is locked, the corresponding sensor should indiques locked

There is no problem (except the delay - but Sure is responsable for that) with the pet sensor

### Steps to reproduce the issue

1. Change the state of the device on Sure website
2. The state of sensors doesn't change
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.5.2

### In which browser are you experiencing the issue with?

all browsers

### Which operating system are you using to run this browser?

Windows 11

**Comment by gjohansson-ST** [comment]
This is not a frontend issue in itself but in that case a problem in core.
Please report the issue there https://github.com/home-assistant/core/issues/new?assignees=&labels=&projects=&template=bug_report.yml
