### ISSUE TITLE
Tuya integration doesn't show or support scenes

### ISSUE THREAD

**Issue by mabusdogma** [home-assistant/frontend#16528]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Tuya v2 Integration doesn't show scenes since HA 2023.5 so in order to have them available I had to downgrade to 2023.4.6

### Describe the behavior you expected

The scenes made on the Tuya or smart life app shold be available in HA, there's an infrared remote controller that is not shown as a device and the only thing that I can use on HA are the scenes I made on the Smart Life App.

### Steps to reproduce the issue

1. Made an scene in smart life app
2.upgrade HA to 2023.5
3. You'll see the scene now is gone from HA
4. Downgrade to 2023.4.6 and you'll have it again
...

### What version of Home Assistant Core has the issue?

2023.5 and later

### What was the last working version of Home Assistant Core?

2023.4.6

### In which browser are you experiencing the issue with?

Chrome, Firefox, android app

### Which operating system are you using to run this browser?

Android, windows

**Comment by JarbasAl** [comment]
Not sure if related, I was just setting up some scenes to control a IR Air Conditioner, they show up in HA until i add the 5th scene, then all entities disappear, if i delete the 5th scene from Smart Life app then the other 4 show up again in HA

**Comment by karwosts** [comment]
If you're talking about a `scene` entity that used to exist but now doesn't, that would be a core issue with the tuya integration, not a frontend issue.
