### ISSUE TITLE
Error when using simple-entity type in entities card

### ISSUE THREAD

**Issue by itsadamslife** [home-assistant/frontend#16526]
I had some simple dashboards set up via the visual editor. After adding this to my entities card in the YAML configuration, I am seeing this error in the visual editor for the card:

```
Key 'entities.25.type' is not expected or not supported by the visual editor.
The provided value for 'entities.25' is not supported by the visual editor. We support (string) but received ({"entity":"input_number.xxxx","name":"xxxx","type":"simple-entity"}).
```

I understand that this is not supported by the visual editor, but neither are some other types (divider, section, etc.) and you can still go back to the visual editor rather than just using YAML. I'm fine with using YAML (I'm very comfortable with it and have used it for several other things) but I have some things set up via the UI for simplicity purposes and being able to make changes on my phone easier.

_Originally posted by @itsadamslife in https://github.com/home-assistant/frontend/discussions/16508#discussioncomment-5898432_

**Comment by karwosts** [comment]
This workaround was provided on the discord server a while back. 

```
LeiChat — 04/06/2023 2:03 PM
Ah, ok. Thank you. The visual editor was happy until I added the type: simple-entity. Is it an issue with the integration definition for the entity?

Kulmegil — 04/06/2023 2:51 PM
yeah, it's one of the pains of overvalidation
if it bothers you can workaround this by wrapping it in "empty" condition row
  - type: conditional
    conditions: []
    row:
      type: simple-entity
      entity: <entiy>
[2:52 PM]
or:
- type: custom:hui-simple-entity-row
  entity: <entity>
 ```

**Comment by ildar170975** [comment]
```
type: custom:hui-element
entity: ...
```
