### ISSUE TITLE
Logbook does not show a state for a newly created sensor

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#16533]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Not sure if it is a core or a frontend issue; please move it to a core if needed.

I just created a sensor with a state "xyz".
And a Logbook card (and a Logbook page as well) does not show a history for this sensor:
![image](https://github.com/home-assistant/frontend/assets/71872483/27e33393-74a8-4673-9d6f-6ba39ab057a4)

Assume that Logbook card only shows CHANGES.
That means that for ANY sensor which was not changed within `hours_to_show` the Logbook will be empty - and this is true (and logical):
![image](https://github.com/home-assistant/frontend/assets/71872483/6d38898b-02c5-47b5-a597-b62d82dc1fa9)
This "only show changes" logic is correct since for every state a "time of state change" is displayed; if this time is beyond `hours_to_show` - nothing to report.
A simple test: go to Dev tools and manually set `sun.sun` to anything else, then restore a previous state - these entries will be displayed in the Logbook:
![image](https://github.com/home-assistant/frontend/assets/71872483/40f668be-9433-4a14-91c8-62d736045b7b)

But a sensor's creation is also a state CHANGE, that is why it is logical to **show this very 1st state in the Logbook**.

### Describe the behavior you expected

as above

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.5.0

### In which browser are you experiencing the issue with?

Chrome 113.0.5672.93 

### Which operating system are you using to run this browser?

Win10x64

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
Up.
2023.11.2.
Here is a new created entity:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/32e8aeea-300e-4d3b-bd04-536fab68a275)

The history shows a correct graph - the sensor was created at ~23:25.

And same is for History page - the graph is OK:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/67b0b63b-6b1c-4320-82aa-3b4c1225e1db)

But the logbook is EMPTY, and I find it inconsistent:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/c6a3b75e-db5b-4596-917c-bfe9cbab8792)

**Comment by karwosts** [comment]
I think if you want to pursue this it is going to have to be a core issue. Frontend just calls `logbook/event_stream` in the websocket API. 

It is core logbook integration that returns an empty list for this query, when the entity was created in the time window of the query.

**Comment by ildar170975** [comment]
@karwosts 
Thanks you for the advice!
Created https://github.com/home-assistant/core/issues/104056

BTW, in the 1st post here I wrote "Not sure if it is a core or a frontend issue; please move it to a core if needed."
So, finally we moved it to the core)).
