### ISSUE TITLE
Scroll bar disappearing after viewing the notifications section

### ISSUE THREAD

**Issue by GSVerspecht** [home-assistant/frontend#16530]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi
I am new here … and proudly running Home Assistant 2023.5.2 since 2 weeks.
Currently in a very simple configuration … no add-ons, few integrations.

I seem to have an issue with the vertical scrollbar disappearing.

I saw some topics on other platforms about this but most of them were closed, so that is why i start this new one …

The scroll disappears as soon as you have opened the notifications section and the side window
pops up, then the scrollbar is no longer visible in none of the sections on the home screen …

Logging out and in again, solves the problem …

I was able to reproduce the problem on windows 10 on 3 browsers (chrome, edge, explorer).
Problem is non existing on iOS devices.

### Describe the behavior you expected

I would like to have the scroll bar back again .. 

### Steps to reproduce the issue

1. log in  to homescreen home assistant .. check scrolbar in the integrations section 
2. go to the (non empty) notifications section  and see how scroll bar disappears .
3. no scrollbar untill you log out and log in again 
...

### What version of Home Assistant Core has the issue?

2023.5.2

### What was the last working version of Home Assistant Core?

2023.5.2

### In which browser are you experiencing the issue with?

Chrome , Edge and explorer 

### Which operating system are you using to run this browser?

Windows 10

**Comment by tk627** [comment]
I can confirm this is happening on my Pi4 system as well.
Home Assistant 2023.5.3
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest
I have to reload the webpage to get the scrollbar back

**Comment by WallyDW** [comment]
Add Firefox to the list

**Comment by HumanSkunk** [comment]
Same for me. I just lose the scroll bar and unable to move down dashboard views. Happens on all devices and in multiple browsers. Only way to get it working again is to force quit the app (refreshing the page does nothing as you cant scroll) or by closing and reopening the webpage.

**Comment by booroondook-eng** [comment]
Hi all.
I have the same problem in any browser.
But I found another workaround for this problem (in addition to the one described above by other users). This works even if your scrollbar has already disappeared.
1) Select the "Notifications" menu on the left panel.
2) Do not close the notification panel with the Close or "<" button!!! Instead, click on the main Home Assistant window outside of the notifications panel.
3) Wow! You see the scroll bar again.
