### ISSUE TITLE
Energy dashboard total in wrong when adding Gas and electricity

### ISSUE THREAD

**Issue by PhilippeAB** [home-assistant/frontend#16552]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hello
I'm have added a gaz counter in kWh to the energy dashboard but the home total is only taking grid energy total.

### Describe the behavior you expected

The home energy total should sum the energy sources 

### Steps to reproduce the issue

1. add an electricity source to energy dashboard
2. add a gas source to energy dashboard
3. the total does not sum the sources

### What version of Home Assistant Core has the issue?

2023.5.3

### What was the last working version of Home Assistant Core?

unknow

### In which browser are you experiencing the issue with?

Firefox mac/windows, safari IOS/mac

### Which operating system are you using to run this browser?

Windows 10, Macos Montery, IOS 16

### State of relevant entities

```txt
what can I provide about this ?
```

### Problem-relevant frontend configuration

```yaml
no
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

**Comment by karwosts** [comment]
If you still want to pursue this, can you show a screenshot of what you mean?
