### ISSUE TITLE
Energy dashboard generates fake values daily for solar and gas

### ISSUE THREAD

**Issue by alviskums** [home-assistant/frontend#16560]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since may version (first one), something went wrong with statsics data from Energy dashboard.
Firstly - after new upgrade - it generated on one period all previous daily solar energy 70kwh. Fixed that under STATISCS tab, found wrong value, set to 0.
After that it started almost (but not every day), at times 06:00-07:00 and 07:00 to 08:00 generating wrong values. It feels like, it sums all daily values to every 5 minute statistics record. After that, works everything fine. 
With GAS is more strange, it just randomly adds some m3. Every day, I manually fix those values under STATISTICS. 

![image](https://github.com/home-assistant/frontend/assets/19961611/3e9a5036-9b92-4957-90f0-08d02444319e)
![image](https://github.com/home-assistant/frontend/assets/19961611/19a94a27-7f90-4c0d-b794-8b4ff179eb9a)
![image](https://github.com/home-assistant/frontend/assets/19961611/3ef0b45f-34c0-477b-8975-566ecfc4bc15)
At 07:00 there should be only 0.52 kwh totally
![image](https://github.com/home-assistant/frontend/assets/19961611/4f6fe0c0-77f9-4b27-be0a-58134b7f1add)

And this is how it should look from previous day
![image](https://github.com/home-assistant/frontend/assets/19961611/3f21e668-c99d-43fa-bdbe-32114f7c4373)

### Describe the behavior you expected

![image](https://github.com/home-assistant/frontend/assets/19961611/9213d5de-0412-42f2-ad74-349d60d01755)

### Steps to reproduce the issue

1. Not sure, it can be reproduced. Maybe there i some ideas, what could be the problem. It never had before MAY version. And I have more than year HA runing.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.5.3

### What was the last working version of Home Assistant Core?

2023.4.X

**Comment by alviskums** [comment]
Today happened first day "joke". It added yesterdays total consupmtion
![image](https://github.com/home-assistant/frontend/assets/19961611/b3401d61-33a6-42d5-982c-f291eba6aad7)
![image](https://github.com/home-assistant/frontend/assets/19961611/4ba509c0-da56-4da1-8fdc-bd6f83ec9b2b)

**Comment by karwosts** [comment]
The frontend does not ever add any values to the statistics database, it only displays the data as it exists. If you have bad data in your statistics, that's a problem for home-assistant/core, so please file your issue there.
