### ISSUE TITLE
The links generated in attribues are broken after installing latest

### ISSUE THREAD

**Issue by tichaonax** [home-assistant/frontend#16599]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

My esp8266 devices register config with HA, configuration information that includes links to navigate back to the device admin UI. After upgrading to the latest UI and CORE the links are now broken. I have reported the bug under UI but it could be the backend.

The link text is correct but the link behind is wrong, in my example 
```
http://192.168.0.180:8123/lovelace/0
```
Previously the link and text matched and allowed navigation to the constructed URL. now it just loads a new browser instance of HA.

Before the upgrade the link was correct.
``` http://192.168.0.172/p/a/3?d=192.168.0.153&c=Master%20Bedroom ```

### Describe the behavior you expected

I expect the link generated to match the link text so I can navigate to the device admin UI as before.

### Steps to reproduce the issue

Have device sent configuration information with attributes that has navigable link.
![image](https://github.com/home-assistant/frontend/assets/1031407/c65afbf6-be6c-468e-a7d1-2cc10d27beae)

### What version of Home Assistant Core has the issue?

Home Assistant 2023.5.3 Supervisor 2023.04.1 Operating System 10.1 Frontend 20230503.3 - latest

**Comment by ildar170975** [comment]
same?
https://github.com/home-assistant/frontend/issues/16227
https://github.com/home-assistant/frontend/issues/16519

**Comment by karwosts** [comment]
Closing this as fixed, as it is fixed in the related issues mentioned above. Feel free to update if you find more problems.
