### ISSUE TITLE
Missing description for dropdowns and checkboxes in Data Flows

### ISSUE THREAD

**Issue by rumbu13** [home-assistant/frontend#16594]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Descriptions are no displayed for `vol.In` schemas when options are rendered as `dropdown`:

![no descriptions combo](https://github.com/home-assistant/frontend/assets/3045864/93e3fe60-0962-4c80-af60-ef7591959c47)

On the contrary, when the same `vol.In` constraint is displayed as `radio group` (having less than 6 items), the description is clearly visible:

![descriptions radio](https://github.com/home-assistant/frontend/assets/3045864/8cca973c-5661-48ee-a471-47d78512b128)

The same issue appears also for comboboxes:

![no description checkbox](https://github.com/home-assistant/frontend/assets/3045864/5c09e3b3-ece5-4a8b-8ee3-82ce268bb221)

Relevant code from `strings.json`:

![checkbox code](https://github.com/home-assistant/frontend/assets/3045864/f29e0f45-f4d1-4a6b-91aa-1ffb3ab81225)

### Describe the behavior you expected

Description of fields should be displayed irrespective of the rendered control (`dropdown` or `radio group`). Also, description should be displayed also for `checkboxes`.

### Steps to reproduce the issue

Spawn any data flow (config/options) with `vol.In` constraint. Description is not visible if it's rendered as `dropdown` (less than 6 items).

For the checkbox issue, since the description is never displayed, it can be reproduced only with custom code.

### What version of Home Assistant Core has the issue?

2023.5.3

### What was the last working version of Home Assistant Core?

Probably never

### In which browser are you experiencing the issue with?

Chrome 113.*/Edge 113.*

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment]
Any chance you know a more specific/easy reproduce step? Like in the default frontend installation, do you know of any specific helper flow or stock integration we can click on to expose/observe this?

"spawn a dataflow with Vol.In" is not something obvious to do, and it would be easier to fix if a dev don't have to go hunting for where to observe it.
