### ISSUE TITLE
Descriptions in Data Flows are not visually attached to the right field

### ISSUE THREAD

**Issue by rumbu13** [home-assistant/frontend#16593]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Description of the fields (`mdc-*-helper-line`) from any data flow (config, options) are visually bound to the next field instead of the current one:
![screenshot data flow](https://github.com/home-assistant/frontend/assets/3045864/de6c47cc-4a15-4371-99e6-bb815f524a5e)

### Describe the behavior you expected

The helper line should be visually bound to the right control. Probably it's better to put it on top or maybe closer to the referred control.

### Steps to reproduce the issue

Spawn any data flow (config, options, etc)

### What version of Home Assistant Core has the issue?

2023.5.3

### What was the last working version of Home Assistant Core?

Probably never

### In which browser are you experiencing the issue with?

Chrome 113.*/Edge 113.*

### Which operating system are you using to run this browser?

Windows 11

**Comment by christophwen** [comment]
@rumbu13 could you tell me which flow you used in your screenshot?

Thats what I found:
![image](https://github.com/home-assistant/frontend/assets/43651938/9ab6a338-7cb3-4f73-ae65-e9c58be10d4e)
There the fields don't look that bad/misplaced.
