### ISSUE TITLE
Automation editor: dropdown list is displayed beyond accessible area

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#16619]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Probably same reason as here - https://github.com/home-assistant/frontend/issues/16113

![изображение](https://github.com/home-assistant/frontend/assets/71872483/e8c88f3a-6e0e-43d1-a7f4-7548130a06d6)

### Describe the behavior you expected

-

### Steps to reproduce the issue

-

### What version of Home Assistant Core has the issue?

2023.5.0

### In which browser are you experiencing the issue with?

Chrome 113.0.5672.127 

### Which operating system are you using to run this browser?

Win10

**Comment by Arn0uDz** [comment]
Have the same issue in my Chrome browser. While creating an automation the bottom of my entity list is outside of my reachable area.

**Comment by ildar170975** [comment]
Seems to be fixed in 2023.6.0
