### ISSUE TITLE
Device "Enable Device" toggle disabled. Unable to re-enable device.

### ISSUE THREAD

**Issue by Klakurka** [home-assistant/frontend#16628]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

A device (LIFX Switch) has somehow become disabled and I'm unable to re-enable it. I don't remember disabling it manually but it is possible that it was done accidentally. It's also possible that it happened automatically when messing with related devices/entities.

![image](https://github.com/home-assistant/frontend/assets/4713204/24c26911-2f76-4ea2-b136-4ab2b3dba507)

![image](https://github.com/home-assistant/frontend/assets/4713204/12ef796a-88dd-4c06-8cb9-d936ac2de8c5)

Attempting to submit the device update form shows this: 
![image](https://github.com/home-assistant/frontend/assets/4713204/f3759ae0-2c99-4cf2-af7b-7469b3e7987a)

The entity behind the device does exist.

### Describe the behavior you expected

The "Enable device" toggle should be clickable.

### Steps to reproduce the issue

1. Disable a device (to be honest, I'm not sure how to get it into a state where this will break).
2. Try to enable the device and notice that the toggle has been disabled.

### What version of Home Assistant Core has the issue?

core-2023.5.4

### In which browser are you experiencing the issue with?

Brave 1.51.114 Chromium: 113.0.5672.92 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment]
Disabled by config entry means the integration that provides this device is disabled, so you cannot enable the device. You have to first navigate to the integration page and enable the integration. 

That specific error message you show was fixed in #17464.

Closing this as completed.
