### ISSUE TITLE
Profile -> Language: glitch on changing a language

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#16642]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

1. Go to Profile.
2. Select a "Russian" language from a selector.
3. See that another language ("Vietnamese") is selected after some time.
4. Select "English" language.
5. See that another language ("Esperanto") is selected after some time.

![ala](https://github.com/home-assistant/frontend/assets/71872483/a7fa55d7-7d1e-4326-ace9-f232a0fc3c80)

### Describe the behavior you expected

Selected language must not change after selection.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.5.4

### In which browser are you experiencing the issue with?

Chrome 113.0.5672.127 

### Which operating system are you using to run this browser?

Win10

**Comment by karwosts** [comment]
This is still valid. Issue is that for some locale changes, the sort order of the languages changes. (some non-ascii characters get sorted to the top of the list in some languages, and in the bottom in others). When user pick an item in the list, say item #10, if the sort order changes, on next render the picker will still show item #10, even though that's no longer the one you initially selected. Not sure why it's not working right, something internal to the material select box I guess.
