### ISSUE TITLE
Energy dashboard doesn't show sum of two Solar systems

### ISSUE THREAD

**Issue by TyzzyT** [home-assistant/frontend#16669]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I hoover over the Energy usage bars, I get a sum of total consumed and total returned power at the bottom. This is expected
![image](https://github.com/home-assistant/frontend/assets/80623729/a470bf66-8667-45c0-8645-8ba519c6e86b)

But when I hoover over the Solar production bars, I only get the individual data. I expected that this would also show a sum of total energy produced
![image](https://github.com/home-assistant/frontend/assets/80623729/6a507a69-1d7e-486c-b894-9a0989d05746)

### Describe the behavior you expected

I expected the Solar production bars to also show a sum of all Solar production systems, so I can read how much energy was produced instead of calculating it myself

### Steps to reproduce the issue

1. Add at least 2 solar production systems to your Energy dashboard
2. Wait for the Energy dashboard to start showing data
3. See only the individual data and miss the sum of Solar production

### What version of Home Assistant Core has the issue?

core-2023.5.4

### What was the last working version of Home Assistant Core?

never

### In which browser are you experiencing the issue with?

Brave version 1.51.118 Chromium: 113.0.5672.126 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11 22H2 and iOS 16.5

**Comment by karwosts** [comment]
Filed an enhancement to sum these.
