### ISSUE TITLE
Energy dashboard can't process price in cents

### ISSUE THREAD

**Issue by valexi7** [home-assistant/frontend#16663]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using the Nordpool Spot integration for hourly electricity price per kWh as energy price source Home Assistant processes price as EUR/kWh.

Here is the Nordpool sensor attributes::
```
state_class: total
average: 4.325125
off_peak_1: 2.66175
off_peak_2: 0.318
peak: 6.76975
min: 0.014
max: 14.627
mean: 1.463
unit: kWh
currency: EUR
country: Finland
region: FI
low_price: false
price_percent_to_average: 2.5818906968006705
today: 0.374, 1.063, 0.999, 1.121, 1.042, 1.448, 6.334, 8.913, 14.627, 13.471, 11.167, 10.214, 8.713, 7.997, 7.113, 2.434, 1.624, 1.478, 1.184, 1.215, 0.738, 0.305, 0.215, 0.014
tomorrow: 
tomorrow_valid: false
raw_tomorrow: 
current_price: 11.167
additional_costs_current_hour: 0
price_in_cents: true
unit_of_measurement: c/kWh
device_class: monetary
icon: mdi:flash
friendly_name: Spot
```

### Describe the behavior you expected

`unit_of_measurement: c/kWh` should be taken into account, when processing hourly cost of energy

### Steps to reproduce the issue

1. Add energy source to Energy dashboard
2. Create template sensor for energy price for example with value of 1
3. Play with 'unit_of_measurement' attribute to see any effect
...

### What version of Home Assistant Core has the issue?

2023.5.4

**Comment by karwosts** [comment]
This is not frontend issue, the price calculation is done by the energy integration in /core/. 

You can see here how when using a cost price sensor, only the denominator of price sensor is used, the numerator is not considered and thrown away. 

https://github.com/home-assistant/core/blob/dev/homeassistant/components/energy/sensor.py#L322

**Comment by karwosts** [comment]
Possibly relevant discussion: https://github.com/home-assistant/architecture/discussions/857

Seems likely this would not be fixed (even if it was reported in the right repository), rather you should create a template sensor that has your price in whole currency units, not cents.
