### ISSUE TITLE
Can not delete alias, or?...

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#16675]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Trying to delete an alias on a zwave integration  entity, there seems to be no way to confirm.

going back from that panel to the voice assistant  shows the deleted alias to still be there.

### Describe the behavior you expected

Deletion of alias

### Steps to reproduce the issue

1. Select alias 
2. Click bin
3. (Can’t confirm so) go back to voice assistant

5. open desktop browser and see alias is deleted after all.... (bottom image in dark theme)
...

### What version of Home Assistant Core has the issue?

2023.4.5

### In which browser are you experiencing the issue with?

iOS app

### Additional information

<img width="546" src="https://github.com/home-assistant/frontend/assets/33354141/607c5f39-3616-44dd-8a62-b7b051777968">

<img width="546" src="https://github.com/home-assistant/frontend/assets/33354141/69cca4d2-75fa-4af2-af8c-b428437b9e39">

**Comment by sweetpants** [comment]
Latest HA (2023.11.1) seems to have the same issue, can't delete the aliases.

**Comment by Caroline-Thies** [comment]
I have the same issue with the web interface, but it works in the android app

**Comment by tdufaud** [comment]
Same issue latest HA (2024.5.5)
