### ISSUE TITLE
Energy Dashboard suddenly inverts its color scheme and reports fake energy spikes

### ISSUE THREAD

**Issue by framerate** [home-assistant/frontend#16682]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I've been finally using the amazing energy dashboard, and I check it all the time because I'm a nerd. Today it got SUPER weird. Its always "blue for grid use", "purple for data sent back to the grid" and "orange for solar generation" (as seen below).

Today I woke up and it claims my 3.5kwh panels made and consumed 45kwh in basically ONE HOUR and I pulled ~100kwh from the grid.

And even stranger, purple has changed to "grid use" and blue changed to "power sent back to the grid" (inverted). The dial to show net use is the same colors, but now it moves to the left instead of the right.

SUPER weird. If I got back to yesterday or any other day, the dial and the colors (and the data) appears correct.

### Describe the behavior you expected

I would expect the grid consumption data would match my solar invert (it does not, but isn't that where it gets the data?) and the colors would remain consistent (they are inverted today)

### Steps to reproduce the issue

1. login to my HA
2. notice data is wrong
3. notice colors are inverted
4. get confused

### What version of Home Assistant Core has the issue?

10.2

### What was the last working version of Home Assistant Core?

10.2

### In which browser are you experiencing the issue with?

113.0.5672.129 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

### Additional information

I would love to diagnose this further, but to my limited knowledge I don't have much control over the energy dashboard. I can provide more info if someone directs me to what would be helpful!

<img width="356" alt="image" src="https://github.com/home-assistant/frontend/assets/74291/b99cb70a-6c6d-4334-8dfe-90b397e26d48">

Yesterday (notice colors and net dial direction)
<img width="904" alt="image" src="https://github.com/home-assistant/frontend/assets/74291/b6d797da-92cd-49ba-be78-90fe6a9fecc3">

Today (everything is backwards)
<img width="917" alt="image" src="https://github.com/home-assistant/frontend/assets/74291/a81b3f63-c4f6-425f-b5bb-ceabb30dc38d">

**Comment by karwosts** [comment]
If the bars are going in the wrong direction it's likely you have some corrupted datapoint in your statistics database where a large negative value got reported where it shouldn't. 

If you want to debug further, pick one of these entities with the wrong bars, and please create a `statistics-graph-card` showing the entity for the time range where you see the problem (include all of sum, state, and change in the graph). 

When we see what data is there we can go from there. If the data is bad in the statistics database, will have to close this as off topic though as that's not a frontend issue, but you can still follow up the issue in core going forward.
