### ISSUE TITLE
Device settings overview page shows integration-generic options

### ISSUE THREAD

**Issue by pimw1** [home-assistant/frontend#16702]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The new [Device settings overview page] shows integration-generic options, which are not related to the specific device at hand:
![image](https://github.com/home-assistant/frontend/assets/74881023/9303b676-5848-48fa-b35f-5b2e658152f6)

In my example, it is a light bulb connected via the deconz integration.

### Describe the behavior you expected

I would only expect device-specific settings in the device settings page.

### Steps to reproduce the issue

Open a random light and navigate to its settings page.

### What version of Home Assistant Core has the issue?

core-2023.6.0b0

### In which browser are you experiencing the issue with?

Google Chrome 113.0.5672.127 

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
.
```

### Problem-relevant frontend configuration

```yaml
.
```

### Javascript errors shown in your browser console/inspector

```txt
.
```

### Additional information

.

**Comment by piitaya** [comment]
Fixed by https://github.com/home-assistant/frontend/pull/16704
