### ISSUE TITLE
"Define variables" from GUI is not working

### ISSUE THREAD

**Issue by pimw1** [home-assistant/frontend#16701]
### The problem

The new option "Define variables" from GUI is not working for scripts and automations. When clicking on that option, nothing is happening. 

![image](https://github.com/home-assistant/core/assets/74881023/0cf9747c-ae51-4d9d-8f91-6bd9363efec1)

Closely related to this, when looking specifically to automation, i would expect that this option would show both at the trigger, condition and action part. But it only shows at the action part.

### What version of Home Assistant Core has the issue?

core-2023.6.0b0

### What type of installation are you running?

Home Assistant OS

**Comment by piitaya** [comment]
I pushed a fix for the issue.

BTW, by trigger variables, do you refer to [this](https://www.home-assistant.io/docs/automation/trigger/#trigger-variables) ?
For condition variables, I don't think that exist.

**Comment by pimw1** [comment]
Great work, thanks! Coming back to your question: i'm honestly not sure. Within scripts, i am using stuff like:
![image](https://github.com/home-assistant/frontend/assets/74881023/8e8fe0fe-6bfc-411c-9ba9-a0952c9b4a1b)

Following this as an example, i would think that it is possible to use color_temp_woonkamer at three places:

- trigger: if color_temp_woonkamer > 3000 kelvin
- condition: color_temp_woonkamer < 6000 kelvin
- action: set color of light with color temperature = color_temp_woonkamer
