### ISSUE TITLE
Awning icons are wrong for an awning

### ISSUE THREAD

**Issue by rstrouse** [home-assistant/frontend#16706]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

There are a bunch of issues submitted on this but every time it gets dismissed that is it correct.  But the dismissal is based on how a gate works not an awning.  Perhaps it is correct in the context of a gate but it is not in the context of an awning.  To retract an awning you should be pressing the icon that looks like this. 
![image](https://github.com/home-assistant/frontend/assets/47839015/0c5d7fa1-3bbd-4806-8c2f-e423d22af19a)

Typically this also corresponds with the up button on nearly every remote out there and in fact if you invert it with a wind/sun sensor you are in peril because it will submit an up command to retract the awning.

To extend an awning one would expect to press an icon that looks something like this.
![image](https://github.com/home-assistant/frontend/assets/47839015/b6ca353d-82ac-41ec-88b9-c1d02dafe7cb)

But alas these icons are reversed.  The fix for this is very straightforward.

In `src/common/entity/cover_icon.ts` line 132 of computeOpenIcon change the method to this.
```
export const computeOpenIcon = (stateObj: HassEntity): string => {
  switch (stateObj.attributes.device_class) {
    case "awning":  // Awnings do not open like a gate.
      return mdiArrowCollapseHorizontal;
    case "door":
    case "gate":
    case "curtain":
      return mdiArrowExpandHorizontal;
    default:
      return mdiArrowUp;
  }
};
```

And in `src/common/entity/cover_icon.ts` line 132 of `computeCloseIcon` change the method to this.
```
export const computeCloseIcon = (stateObj: HassEntity): string => {
  switch (stateObj.attributes.device_class) {
    case "awning":
      return mdiArrowExpandHorizontal;
    case "door":
    case "gate":
    case "curtain":
      return mdiArrowCollapseHorizontal;
    default:
      return mdiArrowDown;
  }
};

```

### Describe the behavior you expected

In the end this will equate to the collapse icon meaning `retract` and the expand icon meaning `extend` for the awning.  Once again this is not a gate or a garage door.

![image](https://github.com/home-assistant/frontend/assets/47839015/b9d7fe56-402c-4490-baee-63525c9d9951)

### Steps to reproduce the issue

1.  Create an entity that is an awning.
2.  View the new entity using the entity card

### What version of Home Assistant Core has the issue?

2023.5.4

### In which browser are you experiencing the issue with?

Any Browser

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
Here it is retracted
current_position: 100
device_class: awning
icon: mdi:storefront-outline
friendly_name: My Awning
supported_features: 15

Here it is extended
current_position: 0
device_class: awning
icon: mdi:storefront
friendly_name: My Awning
supported_features: 15
```

**Comment by rstrouse** [comment]
I am working around this so will just close it.

**Comment by elupus** [comment]
I fully agree here. Up/down symbols are also reversed for behavior, as is the percentages.

**Comment by 36grad** [comment]
I would also really like to see the icons changed.
