### ISSUE TITLE
Dashboard yaml editor is silently reformating/wrapping my templates

### ISSUE THREAD

**Issue by cniry** [home-assistant/frontend#16718]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Manual yaml editor of dashboard - please disable hard line wrapping and template reformating during yaml save, it's **really annoying** for manual editing.

I'm trying to save the following part of my dashboard's yaml:
```
              - type: custom:mushroom-template-card
                primary: Bedroom
                multiline_secondary: false
                layout: vertical
                secondary: >-
                  {% set valve_name = 'climate.netatmo_local_bedroom' %}
                  {% set current_temperature = state_attr(valve_name, 'current_temperature') | float %}
                  {% set target_temperature = state_attr(valve_name, 'temperature') | float %}

                  {{ current_temperature }} ˚C 
                  {% if current_temperature < target_temperature %}
                    / {{ target_temperature }} ˚C
                  {% endif %}
                badge_icon: >-
                  {% if state_attr('climate.netatmo_local_bedroom', 'hvac_action') == 'heating' %}
                    mdi:thermometer-chevron-up
                  {% endif %}
                badge_color: orange
                icon: mdi:bed
                icon_color: >-
                  {% if (is_state('switch.bedroom_tv_screen_state', 'off') and is_state('light.bedroom_tv_ambilight', 'on')) or (is_state('light.bedroom_bulb', 'on')) %}
                    yellow
                  {% endif %}
                tap_action:
                  action: navigate
                  navigation_path: /lovelace/bedroom
                double_tap_action:
                  action: none
                entity: light.bedroom_tv_ambilight
                hold_action:
                  action: none
```

When I save it, I don't see instantly, that it has beed reformated - the code in editor didn't changed. But after page refresh, my yaml has been changed to this (there are some line wraps in templates and some expressions were moved to previous lines):

```
              - type: custom:mushroom-template-card
                primary: Bedroom
                multiline_secondary: false
                layout: vertical
                secondary: >-
                  {% set valve_name = 'climate.netatmo_local_bedroom' %} {% set
                  current_temperature = state_attr(valve_name,
                  'current_temperature') | float %} {% set target_temperature =
                  state_attr(valve_name, 'temperature') | float %}

                  {{ current_temperature }} ˚C  {% if current_temperature <
                  target_temperature %}
                    / {{ target_temperature }} ˚C
                  {% endif %}
                badge_icon: >-
                  {% if state_attr('climate.netatmo_local_bedroom',
                  'hvac_action') == 'heating' %}
                    mdi:thermometer-chevron-up
                  {% endif %}
                badge_color: orange
                icon: mdi:bed
                icon_color: >-
                  {% if (is_state('switch.bedroom_tv_screen_state', 'off') and
                  is_state('light.bedroom_tv_ambilight', 'on')) or
                  (is_state('light.bedroom_bulb', 'on')) %}
                    yellow
                  {% endif %}
                tap_action:
                  action: navigate
                  navigation_path: /lovelace/bedroom
                double_tap_action:
                  action: none
                entity: light.bedroom_tv_ambilight
                hold_action:
                  action: none
```

### Describe the behavior you expected

Yaml editor should keep the content of templates without reformating/line wrapping.

### Steps to reproduce the issue

Open raw yaml editor of dashboard and use templates in it like is mentioned in description.

### What version of Home Assistant Core has the issue?

2023.5.4

### In which browser are you experiencing the issue with?

Google Chrome

### Which operating system are you using to run this browser?

Brave 1.52.118

**Comment by emandtf** [comment]
Up.

It's not a new "issue" but it starts to became very frustrating especially when a template/script/automation is long and complicated.
After few nested IF/CHOOSE all is wrapped within firsts 80 columns (or something like that) so something written as:

> - service: light.turn_off
        target:
          entity_id: >-
            {% set entities = [] %}
            {% set entities = entities + [dst_dimmer_1_entity_id if ((dst_dimmer_1_entity_id is defined) and (dst_dimmer_1_entity_id is not none)) else None] %}
            {% set entities = entities + [dst_dimmer_2_entity_id if ((dst_dimmer_2_entity_id is defined) and (dst_dimmer_2_entity_id is not none)) else None] %}
            {{ entities | unique | reject('eq', None) | list }}

is wrapped in:

> - service: light.turn_off
        target:
          entity_id: >-
            {% set entities = [] %} {% set entities = entities +
            [dst_dimmer_1_entity_id if ((dst_dimmer_1_entity_id is defined) and
            (dst_dimmer_1_entity_id is not none)) else None] %} {% set entities
            = entities + [dst_dimmer_2_entity_id if ((dst_dimmer_2_entity_id is
            defined) and (dst_dimmer_2_entity_id is not none)) else None] %} {{
            entities | unique | reject('eq', None) | list }}

where 3 "set" +1 for the output easy-to-read rows are wrapped in 6 hard-to-read ones for the next edit.
