### ISSUE TITLE
Language selection in General Settings not sticking (2023.6 beta)

### ISSUE THREAD

**Issue by RobertD502** [home-assistant/frontend#16722]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Currently on Beta 2023.6.0b2.

I am unable to test some entity name translations as changing the language from English to another language does not stick. See below:

![ezgif com-video-to-gif](https://github.com/home-assistant/frontend/assets/52541649/3421f39a-7da1-4622-a969-d60f35094455)

Edit:
Just checked on Home Assistant 2023.5.4: Changing the language works as expected. So, it seems like the bug was introduced starting with 2023.6.0b0

### Describe the behavior you expected

Expected newly selected language to remain selected.

### Steps to reproduce the issue

1. Go to general settings
2. Select new language
3. Click on update
4. Exit general settings and return back to general settings

### What version of Home Assistant Core has the issue?

2023.6.0b0, 2023.6.0b1, 2023.6.0b2

### What was the last working version of Home Assistant Core?

2023.5.4

### In which browser are you experiencing the issue with?

Edge Chromium (113.0.1774.57), Safari (16.4.1), iOS Home Assistant app

### Which operating system are you using to run this browser?

macOS Monterey 12.6.5

**Comment by ildar170975** [comment]
There is a similar issue: https://github.com/home-assistant/frontend/issues/16642
But there the selected language changes by itself even w/o leaving/returning to the page:
https://user-images.githubusercontent.com/71872483/241425474-a7fa55d7-7d1e-4326-ace9-f232a0fc3c80.gif
This glitch still occurs.
Could it have a similar origin than this closed one?
