### ISSUE TITLE
Loading view with safari based browser

### ISSUE THREAD

**Issue by Strangehadron** [home-assistant/frontend#16725]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi,
With last core beta (2023.6.0) and with a safari based browser, when loading view look compressed.
It can take couple of seconds (or click/tap) to behave without issue.

Tested with the default dashboard to exclude any potential issue with custom cards. With firefox for example, i have no issue (or maybe firefox faster and the issue have no time to show up?).
Other discord users got the same problem with safari based browser on beta chan.

Thanks !

### Describe the behavior you expected

The view should load without this weird compressed look.

### Steps to reproduce the issue

1. Update to beta (core 2023.6.0 or .1)
2. Go to ha with a safari based browser
3. Load any view.

### What version of Home Assistant Core has the issue?

core-2023.6.0

### What was the last working version of Home Assistant Core?

core-2023.5.4

### In which browser are you experiencing the issue with?

Safari Version 16.4 (18615.1.26.110.1) - Last ios app, last mac app

### Which operating system are you using to run this browser?

macOS Ventura 13.3.1 (a) (22E772610a) / iOS 16.5 (20F66)

### State of relevant entities

```txt
/
```

### Problem-relevant frontend configuration

```yaml
/
```

### Javascript errors shown in your browser console/inspector

```txt
/
```

### Additional information

<img width="1079" alt="Capture d’écran 2023-06-01 à 17 20 08" src="https://github.com/home-assistant/frontend/assets/38626456/b3186c79-4164-4466-acb2-503bfcf58e09">

**Comment by Quentame** [comment]
Having the same

HA: core-2023.6.0b3
UI: 20230601.1
