### ISSUE TITLE
Error thrown when input_datetime changed or shown

### ISSUE THREAD

**Issue by OzGav** [home-assistant/frontend#16744]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Full details are here: https://community.home-assistant.io/t/input-datetime-fails-on-simple-ui-change/576604/23

In short this error is thrown
![image](https://github.com/home-assistant/frontend/assets/19848947/8b511bd2-97e7-4ea9-95e3-08c130c02542)

whenever I change the time picker or if I load or refresh the page that the picker is on. I will continue to test but I think that it is actually working despite the error

### Describe the behavior you expected

input_datetime is updated when the value is changed without an error message shown at the bottom of the screen

### Steps to reproduce the issue

1. Add input_datetime to a view
2. Load the view

### What version of Home Assistant Core has the issue?

2023.5.4

### In which browser are you experiencing the issue with?

Version 113.0.5672.129 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
Entity:
input_datetime.hannah_alarm_time

State:
11:10:00

Attributes:
has_date: false
has_time: true
editable: false
hour: 11
minute: 10
second: 0
timestamp: 40200
friendly_name: Hannah Alarm Time
```

### Problem-relevant frontend configuration

```yaml
- type: entities
        show_header_toggle: false
        entities:
          - entity: input_datetime.hannah_alarm_time
          - entity: automation.hannah_alarm_clock
```

### Javascript errors shown in your browser console/inspector

```txt
{code: 'invalid_format', message: "Invalid time specified: {'hours': 6, 'minutes': 10…'amPm': 'AM'} for dictionary value @ data['time']"}
code
: 
"invalid_format"
message
: 
"Invalid time specified: {'hours': 6, 'minutes': 10, 'seconds': 0, 'milliseconds': 0, 'amPm': 'AM'} for dictionary value @ data['time']"
```

**Comment by karwosts** [comment]
Very strange behavior, can't explain it. 

What is supposed to happen when you change a value in the entities row, the UI control there is an HA time input. 

When the value is changed, this function is called and the value is converted from the yaml format `{ hours: x, minutes: y }` to a string representation of the time, and that string representation is passed up to the entities row for further processing, and used to call the service with. Here's an example:

![image](https://github.com/home-assistant/frontend/assets/32912880/868139c4-848f-4b4b-a83b-4fb7dd13cac8)


It is not legal to call set_datetime with that yaml structure of time, if you try calling that in developer tools you will get the same error. It's puzzling to me how this function could fail to perform this conversion.

**Comment by OzGav** [comment]
Is there anything else I can try or test to get more info to track this down?

**Comment by karwosts** [comment]
Aside from my suggestion to try a fresh install of HA, sorry I can't think of anything. Maybe someone else will come by with an idea.

**Comment by OzGav** [comment]
I have tried a fresh install and still the same problem... I have reverted to my original install now...

**Comment by OzGav** [comment]
Finally tracked it down to a problem with a custom component. Thanks for all the ideas.

**Comment by parautenbach** [comment]
> Finally tracked it down to a problem with a custom component. Thanks for all the ideas.

Enlighten us.

**Comment by OzGav** [comment]
I have been working with the developer of ha-floorplan to introduce some new functionality and thus I am running a beta version of that component. Something, not sure exactly what yet, is causing a bunch of front end weirdness.
