### ISSUE TITLE
custom:stack-in-card not loading sometimes

### ISSUE THREAD

**Issue by kubusiaasty** [home-assistant/frontend#16753]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

During loading dashboard, custom:stack-in-card cards are not loading complitely. Especially for mobile but sometimes also in web browser.
Successfully loaded card (on the left): should have this chip cards at the bottom and same colors for card background
![image](https://github.com/home-assistant/frontend/assets/49375273/5401c84a-5d07-495b-9761-e6c64e2e3a33)

Wrongly loaded cards examples:
![image](https://github.com/home-assistant/frontend/assets/49375273/b3515c72-2697-4eda-bb8a-75fd9a388ba7)
![image](https://github.com/home-assistant/frontend/assets/49375273/bb1a80e5-8288-40e1-b5a7-f829af00eacb)

Sometimes I have to multiple refresh dashboard to work.

Sample of code for one card:

type: custom:stack-in-card
cards:
  - type: custom:mushroom-template-card
    primary: Entrance
    secondary: temp + hu
    icon: mdi:door
    tap_action:
      action: navigate
      navigation_path: /dashboard-futurehome/entrance
    hold_action:
      action: none
    icon_color: '{{ ''amber'' if is_state(''light.entrance_lights'', ''on'') }}'
    fill_container: true
    layout: horizontal
    multiline_secondary: false
  - type: custom:mushroom-chips-card
    chips:
      - type: template
        entity: light.entrance_lights
        icon: |
          {% if is_state('light.entrance_lights','on') %}
            mdi:lightbulb-on
          {% else %}
            mdi:lightbulb-off
          {% endif %}
        icon_color: |
          {% if is_state('light.entrance_lights','on') %}
            amber
          {% else %}
            grey
          {% endif %}
        tap_action:
          action: toggle
        hold_action:
          action: more-info
      - type: conditional
        conditions:
          - entity: binary_sensor.door_sensor_contact
            state: 'on'
        chip:
          type: template
          icon_color: green
          icon: mdi:door-open
          tap_action:
            action: none
          card_mod:
            style: |
              ha-card {
                animation: blink 2s linear infinite;
              }
              @keyframes blink {
                50% {opacity: 0;}
              }
      - type: conditional
        conditions:
          - entity: binary_sensor.motion_sensor_occupancy
            state: 'on'
        chip:
          type: template
          icon_color: green
          icon: mdi:motion-sensor
          tap_action:
            action: none
    alignment: end
    card_mod:
      style: |
        ha-card {
          --chip-box-shadow: none;
          --chip-background: none;
          --chip-spacing: 1px;
        }
card_mod:
  style: |
    ha-card{
    height: 109px;
    }

### Describe the behavior you expected

Successfully load every time.

### Steps to reproduce the issue

1. Load code to your dashboard
2. Refresh page couple of times

### What version of Home Assistant Core has the issue?

Home Assistant 2023.5.4

### In which browser are you experiencing the issue with?

Google Chrome 113.0.5672.129

**Comment by karwosts** [comment]
I would suggest raise this in the repo where this card is developed. Note the frontend issue report template says:

> **Please not not report issues for custom cards.**
