### ISSUE TITLE
[Netatmo] Netatmo integration is discovered as a Media Source. 

### ISSUE THREAD

**Issue by lboue** [home-assistant/frontend#16756]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Netatmo integration is discovered as a Media Source. 
I don't understand what my thermostat would do in this section.

![image](https://github.com/esphome/issues/assets/938089/66880731-f4e8-4ad1-8bee-4b056af7d44c)
![image](https://github.com/esphome/issues/assets/938089/c5306996-8e6e-415d-9415-1cb21fc1c37e)

### Describe the behavior you expected

Do not display Netatmo in _Media Sources_ section. It has no use because it does not contain an entry.

### Steps to reproduce the issue

1. Add Netatmo integration
2. Go to _Media Sources_ section.

### What version of Home Assistant Core has the issue?

Home Assistant 2023.6.0b4

### In which browser are you experiencing the issue with?

Chrome Version 114.0.5735.91 

### Which operating system are you using to run this browser?

Windows 11

**Comment by Quentame** [comment]
I think it’s a core issue, not a frontend one, try to open an issue in the core project.

**Comment by lboue** [comment]
Done with [core issue #94054](https://github.com/home-assistant/core/issues/94054).
