### ISSUE TITLE
Wrong text when adding HomePod Mini

### ISSUE THREAD

**Issue by obzocker** [home-assistant/frontend#16751]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The confirm dialog displays the text for adding an "Apple TV" but it should display one for adding a "HomePod Mini" (see picture for bug).

![Homeassistant bug](https://github.com/home-assistant/frontend/assets/30628274/55415950-4a47-4959-b158-36d229c1a8b3)

### Describe the behavior you expected

Add a custom dialog for adding "HomePod Mini"

### Steps to reproduce the issue

1. Click "Configure" of the HomePod Mini in Settings -> Devices and Services -> Integrations

### What version of Home Assistant Core has the issue?

 Home Assistant 2023.5.4 Frontend 20230503.3 - latest

**Comment by Quentame** [comment]
This is a core issue not a frontend one, please create an issue there + as I configured HomePods in HA few days ago, there is no PIN code with HomePod mini
