### ISSUE TITLE
Lifx themes do not appear via ui.

### ISSUE THREAD

**Issue by Bitwolfies** [home-assistant/frontend#16765]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

[The documentation for Lifix implies there is meant to be a gui to apply the themes.](https://www.home-assistant.io/integrations/lifx/), "To apply a theme interactively, use the theme selection drop-down box found on the device configuration screen."

This does not appear to exist.
![Screenshot_20230604_233400](https://github.com/home-assistant/frontend/assets/65789901/9b3d8118-db96-4dba-80ef-d56394642c9c)
(The stars are for effects, the very old and slow method)

### Describe the behavior you expected

A ui option to pick the themes.

### Steps to reproduce the issue

1. Have LIFX A19 US
2. Update the bulb and HA to latest firmware, and remove and reintegrate the bulb.
3. Where gui

### What version of Home Assistant Core has the issue?

core-2023.5.4

### In which browser are you experiencing the issue with?

Firefox, HA app, does not matter.

### Which operating system are you using to run this browser?

Linux, Android.

**Comment by bramkragten** [comment]
you have added a screenshot of an entity of the device, you will find the dropdown you are looking for on the device page, click the overflow menu on the top right and click "Device info"

![CleanShot 2023-06-05 at 13 50 17](https://github.com/home-assistant/frontend/assets/5662298/94bd4455-f622-4ee5-aed5-5746f77bef15)

**Comment by bramkragten** [comment]
This isn’t a frontend issue to begin with, probably a support one, or if really an issue it should be for the lifx integration.
