### ISSUE TITLE
# Text editor; random RTL input in stead of LTR

### ISSUE THREAD

**Issue by AriaanBruinsma** [home-assistant/frontend#16771]
> Issue is still very alive here, would still love a fix!

Was actually fixed today: https://github.com/home-assistant/frontend/pull/11419

_Originally posted by @spacegaier in https://github.com/home-assistant/frontend/issues/9601#issuecomment-1021376582_

Great, issue is locked... but the problem persists, how am I suppose to report this?
            
```[tasklist]
### Tasks
```

**Comment by steverep** [comment]
Duplicate of #10458
