### ISSUE TITLE
Media Browser unusable as not displaying controls at the bottom

### ISSUE THREAD

**Issue by LeoCal** [home-assistant/frontend#16818]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After updating to HA 2023.6, Media Browser is not usable anymore as it's missing all controls at the bottom (see screenshot attached here below).
As a side note, I'm running HomeAssistant Core in a Python 3.11 virtual environment. Also, during update to 2023.6 last night, I had an issue installing ha-av because of a dependency on ffmpeg - my RPI4 had ffmpeg4.3.6, while minimum required version is now 4.4. So I went ahead and manually compiled ffmpeg 4.4.4 and then I could go ahead with the installation.

<img width="1726" alt="Screenshot 2023-06-08 at 08 02 49" src="https://github.com/home-assistant/frontend/assets/25389602/ce361a39-aa3f-4c38-bfe2-6f099ea6d933">

### Describe the behavior you expected

All media browser controls should be visible.

### Steps to reproduce the issue

1. Click Media Browser icon
2. Select an option (e.g. local media)
3. Notice how all controls at the bottom are missing (play icon, device selection, volume, etc).

### What version of Home Assistant Core has the issue?

core-2023.6.0

### What was the last working version of Home Assistant Core?

core-2023.5.4

### In which browser are you experiencing the issue with?

Safari (MacOS), Google Chrome (MacOS), iPhone HA app

### Which operating system are you using to run this browser?

macOS Ventura (13.4)

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
N/A, regular config
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

### Additional information

See all the info and the screenshot attached in the problem description.

**Comment by LeoCal** [comment]
After digging a bit more, it seems that the issue occurs when the system (RPI4) is running mopidy as a service. When I stop the service, the web controls of the media browser are back.

Was there a recent change to the media browser in this regard?
I've checked the media_source component, but it doesn't seem to have recent changes related to this.
Can anybody point to the code handling the media browser so that I can have a look? 

What is weird is that HA still seems to be correctly handling a mix of media_players going to the same audio hardware. For instance, when sending a Google TTS to the VLC-telnet integration while Mopidy is reproducing music, it correctly handles all that.

**Comment by wildoracle** [comment]
I'm also encountering this same problem. I only use media browser/player to use ytube_music_player from HACS. Now I can't select any source so I can't use that player, or anything else for that matter. Media is not usable until I can access the controls.

**Comment by psleutel** [comment]
Same problem here. Debian 11 supervised with latest available Home Assistant version. Different browsers tried

**Comment by jurgenweber** [comment]
Yeah, a few people are talking about this on the discord server #frontend

I run core on docker, debian 11, the media controls disappeared with 2023.6. MIssing in the OSX App, andrdoid app (2023.6), osx firefox, osx chrome, osx safari.

**Comment by jtary** [comment]
Copying this over from #16931:

I think I have a bit of context that applies to this issue.

The content is failing to display due to an exception in `_mediaPlayerEntities()` method from `ha-bar-media-player.ts`

```
ha-bar-media-player.ts:467 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'hidden')
    at ha-bar-media-player.ts:467:47
    at Array.filter (<anonymous>)
    at i.value (ha-bar-media-player.ts:463:45)
    at i.value (ha-bar-media-player.ts:351:20)
    at i.value (ha-bar-media-player.ts:277:14)
    at i.update (lit-element.ts:160:24)
    at i.performUpdate (reactive-element.ts:1331:14)
    at i.scheduleUpdate (reactive-element.ts:1263:17)
    at i._$Ej (reactive-element.ts:1235:25)
```

Specifically this error is occuring because (at least in my install) there seems to be entities that are in `this.hass.states`, but not `this.hass.entities`. For me, those entities are:

```
[
    "zone.home",
    "sun.sun",
    "media_player.ytube_music_player"
]
```

```ts
  private get _mediaPlayerEntities() {
    return Object.values(this.hass!.states).filter(
      (entity) =>
        computeStateDomain(entity) === "media_player" &&
        supportsFeature(entity, MediaPlayerEntityFeature.BROWSE_MEDIA) &&
        !this.hass.entities[entity.entity_id].hidden // <-- there should be a check here to ensure the entity exists before resolving hidden
    );
  }
  ```

**Comment by bdraco** [comment]
Looks like it needs a guard for entities that are not in the registry
