### ISSUE TITLE
Arrows showing for hidden tabs

### ISSUE THREAD

**Issue by j6s33m** [home-assistant/frontend#16826]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

My Lovelace dashboard continues to show left and right arrows to scroll to hidden tabs when the dashboard first loads up or is refreshed. This started with 2023.5 and the bug persists on 2023.6

![IMG_4615](https://github.com/home-assistant/frontend/assets/17929290/dd927a65-511f-4c23-aa92-eeff0c2e787b)

### Describe the behavior you expected

I don’t expect arrows since I don’t have enough non-hidden tabs to scroll left or right. 

### Steps to reproduce the issue

1. Refresh or open Lovelace on any browser, device or app
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.6.0 and 2023.5.x

### What was the last working version of Home Assistant Core?

2023.4.x

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

Pc and Mac and iOS 

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
N/A
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

### Additional information

None

**Comment by ildar170975** [comment]
duplicate
https://github.com/home-assistant/frontend/issues/16091
https://github.com/home-assistant/frontend/issues/16521
