### ISSUE TITLE
Energy dashboard [use an entity to keep the total cost]: cannot select template monetary sensor

### ISSUE THREAD

**Issue by panzer-v** [home-assistant/frontend#16824]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On the energy dashboard, when I want to select a template montetary sensor as input for the [use an entity to keep the total cost] I see only energy sensors. There are no other sensors available.

### Describe the behavior you expected

I was expecting to be able to choose the template monetary sensor I've created which calculates the total costs.

Code for the sensor I've created. It's placed in the template.yaml:

- sensor:
    # Kosten gas verbruik per dag
    - unique_id: kosten_gas_verbruik
      name: "Kosten gas verbruik"
      state: >-
        {{ ((states('sensor.electricity_dagelijks_gas_verbruik')|float(default=0) * states('input_number.gas_prijs')|float) + states('input_number.vaste_kosten_gas')|float) | round(6)}}
      unit_of_measurement: "EUR"
      device_class: monetary

### Steps to reproduce the issue

1. Create the template sensor to calculate the energy cost. 
2. Go to settings - dashboards - energy
3. Edit excisting gas or energy input.
4.  Choose [use an entity to keep the total costs (second from above)
5.  Try to choose the sensor you've created at step 1. It will not be there. There will only be energy sensors to choose from.
6. Which is strange....because you'd expect to choose a monetary sensor.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.6.0

### In which browser are you experiencing the issue with?

Microsoft Edge Version 114.0.1823.37 (Officiële build) (64-bits). As well as the iPadOS Companion app!

### Which operating system are you using to run this browser?

Windows 10 x64 22H2

**Comment by karwosts** [comment]
Think you might need a state_class as well. Maybe try adding `state_class: total` to the sensor?

**Comment by panzer-v** [comment]
> Think you might need a state_class as well. Maybe try adding `state_class: total` to the sensor?

Wow!!! That did the trick. I've been asking this on many forums....but you got is spot-on!

I guess I should close this ticket now.....
