### ISSUE TITLE
Missing integration icon, making the new layout messy

### ISSUE THREAD

**Issue by mm98** [home-assistant/frontend#16827]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When an (custom) `Integration` doesn't have a valid icon url (404 - ex https://brands.home-assistant.io/amplifi/icon.png), the `<img .. >` tag gets `style="visibility: hidden;"` set.

https://github.com/home-assistant/frontend/blob/8580d3f9bf59ffbcbe4187a0d7a58cc23d9822df/src/components/ha-config-entry-picker.ts#L102-L104

This makes the orange (info) icons look a bit misaligned in the new layout of version `2023.6.0`.

![image](https://github.com/home-assistant/frontend/assets/992714/339bfcd8-6d6e-42ad-aebe-8f8c93190303)

### Describe the behavior you expected

Would it maybe be better to change the `src` of the image to a default placeholder image (on 404). This would make the listing a bit more consistant. 

![image](https://github.com/home-assistant/frontend/assets/992714/09220e75-058e-470c-8a5c-cc1cd9651928)

### Steps to reproduce the issue

1. Install a `Integration` with none existing icon image.

### What version of Home Assistant Core has the issue?

core-2023.6.0

### What was the last working version of Home Assistant Core?

core-2023.5.4

### In which browser are you experiencing the issue with?

All browsers

### Which operating system are you using to run this browser?

Windows 11 H2

### State of relevant entities

```
N/A
```

### Problem-relevant frontend configuration

```
N/A
```

### Javascript errors shown in your browser console/inspector

```
N/A
```

### Additional information

```
N/A
```

**Comment by ildar170975** [comment]
Probably for integrations which do not have an icon we should display some default icon to avoid this misalignment.

**Comment by christophwen** [comment]
Do you have an integration example with no icon which I can use here to reproduce?

**Comment by christophwen** [comment]
>EDIT: This might be a bit hacky, but it looks like the icons have external URL's. Which means, you could add brands.home-assistant.io to your host file and just point it to another IP (temporary - would return 404 on all icons, and they would all become marked as visibility: hidden, since it is done by the client/browser).

True that, I will try that. (When I have some available time to work on this issue)

**Comment by spacegaier** [comment]
Note, the layout of those cards is going to change soon: https://github.com/home-assistant/frontend/pull/17061

Then an empty/missing icon will look less weird as the badges will move to the footer.

**Comment by mm98** [comment]
> Note, the layout of those cards is going to change soon: #17061

True, that would solve the _inconsistency_.
