### ISSUE TITLE
visual editor expands area to devices not assigned to the area (or duplicates), when attempt to split area into separate devices and entities

### ISSUE THREAD

**Issue by tyloch** [home-assistant/frontend#16836]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Expands to all  devices (not only for selected area) when attempt to split area into separate  devices and entities in automation visual editor.

The same behavior for expanding device - it expands to all entities.

### Describe the behavior you expected

For  action "_split area into separate devices and entities_"  only devices **from selected** area are expanded.

### Steps to reproduce the issue

1. go to automation visual editor
2. select area
3. click "_split area into separate devices and entities_" 

example: 
to replicate it, I have to use call service (e.g. Light Turn off)  in my automation. 
sometimes I need to add also **more than one area** and **save** automation. 
when I continue editing, it "explodes" with all devices and entities.  

Please note in `Garderoba` area there is only single device!

<img width="745" alt="Screenshot 2023-06-09 at 16 32 03" src="https://github.com/home-assistant/frontend/assets/783887/6bb2359a-a085-422b-892b-5791bcfec0d6">

and after clicking expand `Garderoba` area I see all devices expanded

<img width="720" alt="Screenshot 2023-06-09 at 16 32 20" src="https://github.com/home-assistant/frontend/assets/783887/f9e12603-36e4-4f02-b35a-89ea34134ef9">

### What version of Home Assistant Core has the issue?

core-2023.6.0
and
core-2023.6.1
Supervisor 2023.06.1
Operating System 10.2
Frontend 20230608.0 - latest

### In which browser are you experiencing the issue with?

Google Chrome and Safari

### Which operating system are you using to run this browser?

macOS 13.4 (22F66)

### Additional information

this bug is also present in
Home Assistant 2023.6.1
Supervisor 2023.06.1
Operating System 10.2
Frontend 20230608.0 - latest

**Comment by karwosts** [comment]
Hmm I don't see this in my install, it still expands to the correct devices and areas. 

Is it for _all_ areas and devices that you see this? What particular trigger/condition/action were you using when you observed this?

**Comment by tyloch** [comment]
to replicate it, I use call service (e.g. Light Turn off)  in my automation. 
sometimes I need to add also **more than one area** and **save** automation. 
when I continue editing, it "explodes" with all devices and entities.

**Comment by tyloch** [comment]
Issue still present in:
Home Assistant 2023.6.1
Supervisor 2023.06.1
Operating System 10.2
Frontend 20230608.0 - latest

**Comment by ma10as123** [comment]
i have the same issue
![Skjermbilde 2023-06-14 17 14 26](https://github.com/home-assistant/frontend/assets/112497181/59906e05-ade6-4f8d-9341-291bd81a75b9)

**Comment by karwosts** [comment]
> _*sometimes*_ I need to add also more than one area and save automation.

Does that 'sometimes' mean it doesn't always happen? Even with the same area it sometimes works and sometimes not?

> when I continue editing, it "explodes" with all devices and entities.

What do you mean "continue editing"? Like touching unrelated things? Or clicking the expand button?

**Comment by tyloch** [comment]
ad.1 - yes sometimes means always.

ad.2 "continue editing" means I click the expand button for another area. It causes more devices and entities to be expanded (sometimes not even from the area for what I'd clicked the expand button)

**Comment by karwosts** [comment]
Few more follow up questions. 

- Does every area do this, or just some of them?

- When you say it expands to all devices, do you really mean _all_, or just a lot? Is it possibly only including devices that are not assigned to an area, or does it also add devices that are definitely assigned to different areas?

- For an area that has this issue, if you go to Settings->Areas->(Area), does it look correct? Does it list the correct devices assigned there? What is the name of the area in the header bar, and what is the full URL displayed in the web browser? Trying to see if somehow the area_id is corrupt or null. Or just see if anything looks off here. 

Can't really see anything in the code that would cause this yet.

**Comment by ma10as123** [comment]
https://github.com/home-assistant/frontend/assets/112497181/4b7e16d7-0bd0-4840-8293-c793bf5c46b8

here is a video if that helps

**Comment by ma10as123** [comment]
https://github.com/home-assistant/frontend/assets/112497181/567364bc-25f5-4a9b-a010-cb909ee3adf7

and this

**Comment by tyloch** [comment]
> Few more follow up questions.
> 
> * Does every area do this, or just some of them?

most or all of them when editing areas for call service entry

> * When you say it expands to all devices, do you really mean _all_, or just a lot? Is it possibly only including devices that are not assigned to an area, or does it also add devices that are definitely assigned to different areas?

devices from the area, and sometimes (most times) also devices from other areas. 



> * For an area that has this issue, if you go to Settings->Areas->(Area), does it look correct? Does it list the correct devices assigned there? What is the name of the area in the header bar, and what is the full URL displayed in the web browser? Trying to see if somehow the area_id is corrupt or null. Or just see if anything looks off here.

e.g. for 'garderoba' area: 
http://homeassistant.local:8123/config/areas/area/garderoba

there is only one device in this area
<img width="565" alt="Screenshot 2023-06-22 at 20 04 35" src="https://github.com/home-assistant/frontend/assets/783887/1c1d3917-8e91-41b9-a1a2-ace16240770f">



> 
> Can't really see anything in the code that would cause this yet.

**Comment by silamon** [comment]
I've got a reproduction, I think: 
With 3 lamps: Assign first lamp to zone1, second lamp to zone2, and third lamp to zone1 and zone2. 
Then use the call service action, add zone1 and zone2. Then expand zone2: first, second and third lamp show as expansion of zone2 whereof the first lamp in zone1 shouldn't be there and third lamp shows twice. 

So the devices not assigned to the just expanded area are the devices which are in the other zones added.

**Comment by karwosts** [comment]
> and third lamp to zone1 and zone2

What does it mean to assign a device to multiple areas? Can't it only have one?

**Comment by silamon** [comment]
> > and third lamp to zone1 and zone2
> 
> What does it mean to assign a device to multiple areas? Can't it only have one?

I've updated the comment. Device can have one area indeed.
