### ISSUE TITLE
ZHA Network Settings no longer show "Network key" since Home Assistant 2023.6

### ISSUE THREAD

**Issue by Hedda** [home-assistant/frontend#16845]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

"Network key" can be found in the ZHA integration under Network Settings in Home Assistant 2023.5 but as mentioned in https://github.com/home-assistant/frontend/pull/16731 PR, since Home Assistant 2023.6 the Network Settings no longer show "Network key" under Network Settings in the ZHA integration. 

Instead, it looks like "Network key" for Zigbee network have been replaced with the device path for the serial port and Baudrate.

#### Now in Home Assistant 2023.6 

Now in Home Assistant 2023.6 release which does no longer show "Network key":

![image](https://github.com/home-assistant/frontend/assets/6320001/0522b657-a58b-4bfd-89a5-c7eb584cbdb8)

#### Before in Home Assistant 2023.6

Now in Home Assistant 2023.5 and previous releases which did show "Network key":

![image](https://github.com/home-assistant/frontend/assets/6320001/764086dd-5e1d-43ce-a01d-b01907afe033)

### Describe the behavior you expected

Expect to see "Network key" under Network Settings in the ZHA integration.

### Steps to reproduce the issue

1. Select "CONFIGURE" on "Zigbee Home Automation" (ZHA integration) under Devices & Services.
2. Look under "Network Setting".
3. There "Network key" is no longer shown.

### What version of Home Assistant Core has the issue?

2023.6

### What was the last working version of Home Assistant Core?

2023.5

### In which browser are you experiencing the issue with?

Google Chrome Version 114.0.5735.110 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 (64-bit)

### Additional information

The same issue is seen in the Home Assistant Companion app for iOS.

**Comment by vinerz** [comment]
+1. Following this issue

**Comment by karwosts** [comment]
Based on this commit this seems to be intentional:

https://github.com/home-assistant/frontend/pull/16381/commits/975a5af375f8fa61b0b49cb07bb9d1bae838d916
