### ISSUE TITLE
Add-Ons / Backup Page is empty (only rotating loading cycle) on 2nd access

### ISSUE THREAD

**Issue by MisterT87** [home-assistant/frontend#16859]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If I am opening the Add-Ons or Backups page the second time I only see the animated loading cycle.
Doesnt matter if I access Add-Ons page first and then Backups page (or vice versa) or just open Add-Ons page two times (on same tab)... I only see the animated loading cycle.

On the first access both Pages working as expected.
Issue only occur on same session (Browser tab) - when opening a new tab the issue will be "resetted" till second access.

Friends told me the exact same issue on Firefox 114.0.1 and MacOSX

Clearing my firefox cache -> didnt solved issue
seems issue only related with firefox -> no issues with Microsoft Edge Browser (chromium based)

### Describe the behavior you expected

Add-Ons and Backups page loads flawless and can see my backups / addons.

### Steps to reproduce the issue

Just open a new firefox tab and access addons or backups page two times.

### What version of Home Assistant Core has the issue?

core-2023.6.1

### What was the last working version of Home Assistant Core?

core-2023.5.4

### In which browser are you experiencing the issue with?

Firefox 114.0.1

### Which operating system are you using to run this browser?

Windows 11 22H2

### Javascript errors shown in your browser console/inspector

```txt
Got following Errors from Firefox while accessing Add-Ons page second time:
NS_ERROR_NOT_INITIALIZED at entrypoint-G81gb268sps.js - line 6
```

**Comment by kulmegil** [comment]
I was just going to report this as 2023.07 beta bug but it appears it was introduced sooner.

Yeah it happens with Firefox only.
