### ISSUE TITLE
Acceptance of Invalid URL

### ISSUE THREAD

**Issue by houren928** [home-assistant/frontend#16864]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When the user inputs an invalid url in the view configuration form, he / she is still able to add view details and save it.

<img width="494" alt="Screenshot 2023-06-11 at 7 16 22 PM" src="https://github.com/home-assistant/frontend/assets/75327464/919b838e-178f-46f4-ba2c-b3b53dbc4014">

### Describe the behavior you expected

The system pop-up an error message that the url must be in the correct format and does not allow users to add or edit the view’s details.

### Steps to reproduce the issue

1. Click the “+” icon below the title of the edit dashboard page. 
2. Fill in the url in the view configuration form.
3. Click the “SAVE” button.
4. 

### What version of Home Assistant Core has the issue?

Core-2023.5.3

**Comment by ildar170975** [comment]
Still here.
Reproduced.

Created a view with this URL:
```
some-title^^%%^^some-title
```
![изображение](https://github.com/home-assistant/frontend/assets/71872483/96faa570-e486-4d77-8dd7-785fc7492ada)

Can be selected:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/a2aa2512-d3b1-400b-bf33-cd5326e23cd5)

Described in Raw editor:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/4ddcdd5a-f0a6-4dd9-bb5c-abb9e2431e08)
