### ISSUE TITLE
Missing Sun card on default dashboard after upgrade to 2023.6.1

### ISSUE THREAD

**Issue by miskor-bgd** [home-assistant/frontend#16887]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After upgrade to 2023.6.1 I do not have Sun panel (from Sun integration) shown on default dashboard. Even if I try to add it manually - it does not show up. It does show on other custom dashboards that I created. But I want to fix why it is not available any more on default dashboard as it it a part of default config...?

### Describe the behavior you expected

Sun panel should be displayed

### Steps to reproduce the issue

1. upgrade to 2023.6.1
2. check if sun panel is shown on default dashboard
3.
...

### What version of Home Assistant Core has the issue?

core-2023.6.1

### What was the last working version of Home Assistant Core?

core-2023.5.1

### In which browser are you experiencing the issue with?

Edge, Chrome, FireFox

### Which operating system are you using to run this browser?

Win 11 Pro

### State of relevant entities

```txt
sensor.sun_next_dawn
Sun Next dawn
2023-06-14T02:14:23+00:00	device_class: timestamp
icon: mdi:sun-clock
friendly_name: Sun Next dawn
sensor.sun_next_dusk
Sun Next dusk
2023-06-13T19:02:33+00:00	device_class: timestamp
icon: mdi:sun-clock
friendly_name: Sun Next dusk
sensor.sun_next_midnight
Sun Next midnight
2023-06-13T22:38:38+00:00	device_class: timestamp
icon: mdi:sun-clock
friendly_name: Sun Next midnight
sensor.sun_next_noon
Sun Next noon
2023-06-13T10:38:19+00:00	device_class: timestamp
icon: mdi:sun-clock
friendly_name: Sun Next noon
sensor.sun_next_rising
Sun Next rising
2023-06-14T02:52:09+00:00	device_class: timestamp
icon: mdi:sun-clock
friendly_name: Sun Next rising
sensor.sun_next_setting
Sun Next setting
2023-06-13T18:24:46+00:00	device_class: timestamp
icon: mdi:sun-clock
friendly_name: Sun Next setting
sun.sun
Sun
above_horizon	next_dawn: 2023-06-14T02:14:23.086926+00:00
next_dusk: 2023-06-13T19:02:33.552327+00:00
next_midnight: 2023-06-13T22:38:38+00:00
next_noon: 2023-06-13T10:38:19+00:00
next_rising: 2023-06-14T02:52:09.907361+00:00
next_setting: 2023-06-13T18:24:46.527038+00:00
elevation: 16.64
azimuth: 73.54
rising: true
friendly_name: Sun
```

### Problem-relevant frontend configuration

```yaml
none
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

**Comment by TheGoblinHero** [comment]
I have the same problem.
