### ISSUE TITLE
Person / User picture not updated on other UIs

### ISSUE THREAD

**Issue by GeraldPape** [home-assistant/frontend#16882]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I changed the picture for a user on my system already two weeks ago. In Settings-Persons the correct picture is shown. On the dashboard for tracking and map the old picture is still shown.

yes, I did delete the browser cache and yes, I even started up Edge which I never use on this PC. 

### Describe the behavior you expected

Use the current picture of the person

### Steps to reproduce the issue

1. add a person, add a picture
2. after some days of usage with that user, change the picture
3. old picture still shown on presence in dashboard,....
...

### What version of Home Assistant Core has the issue?

Supervisor 2023.06.1

### In which browser are you experiencing the issue with?

FireFox 113.0.2 (64-bit), MS Edge, iOS App

### Which operating system are you using to run this browser?

Windows 11, iOS

**Comment by karwosts** [comment]
I can't reproduce, when I change the image I see it updated immedately everywhere. 

What happens if you just remove the image completely and have no image?
