### ISSUE TITLE
Device trackers show not_home state instead of Away in UI

### ISSUE THREAD

**Issue by nsnui0** [home-assistant/frontend#16883]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Device trackers show "not_home" state instead of "Away" in UI

### Describe the behavior you expected

As far as I know, "not_home" is the "under the hood" setting for any location beside "Home".
In the UI I'm supposed to see "Home", "Away" or a friendly zone name. Instead of "Away" I get "not_home" state and instead of "Home" I get "home" state.

### Steps to reproduce the issue

I have no knowledge of code so I'll leave it to you.

### What version of Home Assistant Core has the issue?

2023.6.1

### In which browser are you experiencing the issue with?

Google Chrome 113.0.5672.92 and Companion app for android 

### Which operating system are you using to run this browser?

Windows 11 Pro

### State of relevant entities

```txt
device_tracker.yotamphone = not_home
```

**Comment by nsnui0** [comment]
![Screenshot_20230613_013101_Home Assistant](https://github.com/home-assistant/frontend/assets/120796728/9ae7ef4c-0cd9-4e33-b0a4-724dcbb9d271)

**Comment by ildar170975** [comment]
Your family is beautiful ))))

Could you post a code for THIS part:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/023bd61b-3062-4015-a1b4-439cb3305bb7)
?

I wonder is it a conventional Tile card or a custom mushroom-card...

**Comment by karwosts** [comment]
Must be a custom card, the tile card does not have a battery indicator like that. Closing as off-topic for this repo.
