### ISSUE TITLE
Android overlayed beginning of x-axis of history graph (screenshot attached)

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#16889]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Android overlayed beginning of x-axis of history graph (screenshot attached)

### Describe the behavior you expected

No overlay the date and time

### Steps to reproduce the issue

1. 
![1686637885447](https://github.com/home-assistant/frontend/assets/61636045/57297d99-4303-431f-a243-fe01ee88dc04)
![1686637885453](https://github.com/home-assistant/frontend/assets/61636045/7d1e5baf-7cc4-4e12-b059-5224abc75701)

### What version of Home Assistant Core has the issue?

2023.6.1

**Comment by ildar170975** [comment]
Duplicate
https://github.com/home-assistant/frontend/issues/9815
https://github.com/home-assistant/frontend/issues/9851

**Comment by karwosts** [comment]
Closing as duplicate of #9815
