### ISSUE TITLE
Can’t set advance settings in new MQTT integration 

### ISSUE THREAD

**Issue by rdeveen** [home-assistant/frontend#16886]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I try to create a new MQTT integration on a brand new Home Assistant installation I can’t set the advanced settings like protocol version, certificates, etc. Only the Host, Port, Username and Password fields are visible. Because my broker does only support certificate authentication I can’t validate the settings and continue to the next step. 

### Describe the behavior you expected

Enable advanced settings on the first screen of the wizard.

### Steps to reproduce the issue

1. Create a new MQTT Integration 
2. Try to set advanced settings. 
3. Can’t do because this is missing:

![image](https://github.com/home-assistant/frontend/assets/5731724/bd890a40-7b0b-4269-b879-16cd7d2d8295)

...

### What version of Home Assistant Core has the issue?

Latest

**Comment by rdeveen** [comment]
Hey there @emontnemery, @jbouwh, mind taking a look at this issue as it has been labeled with an integration (mqtt) you are listed as a [code owner](https://github.com/home-assistant/core/blob/dev/CODEOWNERS#L777) for? Thanks!

**Comment by jbouwh** [comment]
Did you enabled advanced mode in your personal settings profile?

**Comment by jbouwh** [comment]
![image](https://github.com/home-assistant/frontend/assets/7188918/1feb0241-ea6f-4567-9938-9f40bec3c793)

![image](https://github.com/home-assistant/frontend/assets/7188918/b4c64740-cdea-40e5-987c-3e7ec5cd09ff)

**Comment by rdeveen** [comment]
> Did you enabled advanced mode in your personal settings profile? 

🤯 No I did not do that on the new installation. Enable the advanced mode in my personal settings profile enabled the advanced options in the MQTT wizard.

Thank you for pointing me to this setting. 

Have a nice day.

**Comment by crazyminecuber** [comment]
I have the exact same problem, but the proposed solution does not work for me. I am running home assistant as a container on linux. Tried on both brave an on firefox.

**Comment by crazyminecuber** [comment]
I have to click next to get to the advanced options which is very unintuitive. I get connection errors and think I have to specify a server certificate to get it to work.
