### ISSUE TITLE
Add Network Storage: Password validation is too restrictive for strong passwords

### ISSUE THREAD

**Issue by revinatedave** [home-assistant/frontend#16884]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Adding a samba network storage with a password that uses a comma and/or equals sign fails the regex. There should be no character restriction for passwords at all.

If you enter in certain passwords that contain an equals (=) or comma (,) you get this error:
`does not match regular expression ^[^,=]+$ for dictionary value @ data['password'].`

### Describe the behavior you expected

Any password should be valid, including equal sign and comma.

### Steps to reproduce the issue

1. Try to add a network share
2. Select samba
3. Enter in a password with an equals sign or a comma.
...

### What version of Home Assistant Core has the issue?

2023.6.1

### What was the last working version of Home Assistant Core?

2023.5.x

### In which browser are you experiencing the issue with?

Any

### Which operating system are you using to run this browser?

Mac

**Comment by listlesslife** [comment]
I'm having the same issue while using 2023.6.2.

**Comment by jonnybergdahl** [comment]
Same here
