### ISSUE TITLE
Can't add new helper 

### ISSUE THREAD

**Issue by Marc1200** [home-assistant/frontend#16896]
### The problem

The button add helper is unresponsive, i can't add an new helper.

### What version of Home Assistant Core has the issue?

core-2023.6.1

### What was the last working version of Home Assistant Core?

core-2023.5.4

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

helper

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/input_boolean/

**Comment by ronald3060** [comment]
No, no other errors

**Comment by Marc1200** [comment]
![image](https://github.com/home-assistant/frontend/assets/68737063/716dd8c1-2270-4667-96da-cd7917af6f3b)

**Comment by rjodwyer** [comment]
same issue, same error in console here when trying the button

**Comment by daschmidt1994** [comment]
here also the same Problem

**Comment by MartinHjelmare** [comment]
Please don't comment unless you have new information. You can react to the top post with 👍 to show that you're also affected.

**Comment by silamon** [comment]
Based on the error description: 
This comes from the upgrade to full calendar v6.1.8 which changes the way the styling is done. 
https://github.com/fullcalendar/fullcalendar/commit/8a03db7e9d7e8e6598531a5b2fd9ccc6de30716b
Seems to me that it's something in the browser that doesn't allow it. What browsers are you using? 
I'm unable to reproduce unfortunately. All I can add is that a downgrade to v6.1.7 would fix this for now. 
Last working release as mentioned in this issue is v6.1.5

**Comment by daschmidt1994** [comment]
Have the problem in the App also not only in the browser. A clear from the app cache doesen't help.

**Comment by ronald3060** [comment]
Chrome, with safari on iPhone no issues.

Verstuurd vanaf 06 28422438

**Comment by karwosts** [comment]
I actually ran into this by accident in my dev instance, so I got the full unobfuscated stack trace:

```
internal-common.js:46 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'cssRules')
    at appendStylesTo (internal-common.js:46:1)
    at eval (internal-common.js:10:1)
    at Map.forEach (<anonymous>)
    at injectStyles (internal-common.js:9:1)
    at eval (internal.js:6:1)
    at ./node_modules/@fullcalendar/timegrid/internal.js (vendors-node_modules_date-fns_esm_isSameDay_index_js-node_modules_date-fns_esm_isSameWeek_ind-f98b95.js:79:1)
    at __webpack_require__ (app.js:1934:41)
    at eval (index.js:6:70)
    at ./node_modules/@fullcalendar/timegrid/index.js (vendors-node_modules_date-fns_esm_isSameDay_index_js-node_modules_date-fns_esm_isSameWeek_ind-f98b95.js:69:1)
    at __webpack_require__ (app.js:1934:41)
```

I'm not sure what caused it, and once I refreshed the page one time it started working again.

**Comment by dmpohlmann** [comment]
Team, just had the same issue. Would not work in Chrome, works in Firefox!

**Comment by Marc1200** [comment]
I got the errors with the Chrome browser on pc and phone and Microsoft Edge browser at desktop pc

**Comment by Boromore** [comment]
For me it works with Edge but not with Chrome

**Comment by Marc1200** [comment]
On edge i have this error:
![image](https://github.com/home-assistant/frontend/assets/68737063/924c3853-080f-4c9c-ab1d-c35b3975548f)

**Comment by bramkragten** [comment]
I tracked this down to an issues in full calendar used for the schedule helper. I refactored this in the beta so it doesn't impact the other helpers at least. Not sure if it completely fixes the problem.

**Comment by Turmoil1112** [comment]
Adding new helpers is working again in
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1
On Firefox and the Android App.

**Comment by Boromore** [comment]
I can confirm that it is working on Chrome too.

Home Assistant 2023.7.1
Supervisor 2023.07.1
Operating System 10.3
Frontend-versie: 20230705.1 - latest

**Comment by pcwii** [comment]
I missed updating this. It began working again in 2023.7.1. Confirmed it is still good in 2023.10.1

**Comment by DanielHabenicht** [comment]
> Still happening to me in 2024.1.2.
> 
> <img alt="Screenshot 2024-01-11 at 10 38 30" width="907" src="https://private-user-images.githubusercontent.com/7204152/295863719-2f80e229-7ee5-4a9c-ad44-cd69564a7753.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMzg5NzMsIm5iZiI6MTcwNTIzODY3MywicGF0aCI6Ii83MjA0MTUyLzI5NTg2MzcxOS0yZjgwZTIyOS03ZWU1LTRhOWMtYWQ0NC1jZDY5NTY0YTc3NTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMTMyNDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDA3YWYxODIyOGQ3MjlkNjQyNzUwZDdmMzRhYzBjMjZhYmM3NDQ3MjRjYzg2ZWRjN2VmZDkwMTI0MTRlMTk2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MEY3fNXGGxsV8htXpj3Cy8qohfkm5_FylIUnftOW7CQ">

For me its working again after upgrading to 2024.1.3 with Frontend `20240104.0`

**Comment by maddingamer** [comment]
I have a similar issue, but when klicking on the "schedule" button within the helpers list (after klicking add helper)
Running Core 2024.1.5, SV 2023.12.1, OS 11.4, Frontend 20240104.0

Issue is only in chrome, firefox works just fine.

**Comment by nmwael** [comment]
fyi, had similar issue, turned out to be stale css cache in chrome 135, after ctrl+f5 issue was gone.
