### ISSUE TITLE
'History' states not same as 'Developer tools' states

### ISSUE THREAD

**Issue by CyberFlexie** [home-assistant/frontend#16898]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The history interface capitalizes the first letter of states/strings and replaces underscore characters with spaces. This is confusing because if you try to make an automation, it will not work if using a capital for the first character of the string and/or spaces. 

### Describe the behavior you expected

States should be the same no matter where you look in the interface to avoid confusion. 

### Steps to reproduce the issue

1. Go to 'Developer Tools/States'
2. Filter for 'sun'
3. Notice the State column, it should say 'above_horizon' or 'below_horizon'
4. click on 'sun.sun', scroll up and click on date field just below 'Last Changed'
5. Notice how the states are now 'Above horizon' and 'Below horizon'
6. Agree with me that this is confusing for beginners that are struggling to make automations work? 
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.6.1

### In which browser are you experiencing the issue with?

Firefox 113.0.2

### Which operating system are you using to run this browser?

Windows 11 22H2

**Comment by ildar170975** [comment]
The `history-graph` shows localized values, like (for English):
-- Below horizon / Above horizon
-- Connected / Disconnected.

This behaviour may cause TWO problems:
1. If a time interval is short & a localized label is long - then it may not be displayed on a graph which may confuse a user.
2. Your example - "inexperienced person sees values which do not conform actual ones".

Probably there should be a checkbox like "Show raw values" (could be unset by default) & a corresponding option for `history-graph`.
There was my issue (https://github.com/home-assistant/frontend/issues/14865) which was closed by some Dev person w/o any discussion.
Also you may vote / comment here - https://community.home-assistant.io/t/history-graph-add-an-option-to-manage-labels/536266.

**Comment by bramkragten** [comment]
That's why one is called developer tools, as in meant for development, and the other is called dashboard, as in showing and interacting with devices.

**Comment by ildar170975** [comment]
From other side, even for experienced users it could be rather convenient to see raw values in history-graph - specially for debugging automations.
