### ISSUE TITLE
statistics-graph: cannot find entities by entity_id (also noticed on Energy view)

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#16901]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

`statistics-graph`:
Sometimes it is impossible to select entities by typing a part of it `entity_id`.
Seems that a search is performed for names, not `entity_id`s.

For instance, start inputting a "sensor" word:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/9eeae1dd-e637-49f1-bebe-f04bcae09af8)
In my case it proposes only entities with a "sensor" in a name.

Or this - I cannot find entities by inputting "wind_bearing":
![изображение](https://github.com/home-assistant/frontend/assets/71872483/7d23a606-10b8-4ed4-bfb6-b649670813fa)

IMHO search should be performed for names AND `entity_id`s as well.

### Describe the behavior you expected

Entities must be found by `entity_id` too.

### Steps to reproduce the issue

1. Start adding a new statistics-graph.
2. Start inputting "sensor"

### What version of Home Assistant Core has the issue?

2023.6.0

### In which browser are you experiencing the issue with?

Chrome 114.0.5735.110

### Which operating system are you using to run this browser?

Win10

**Comment by ildar170975** [comment]
In 2023.7 it seems to be more weird:
the list proposes possible matches - but is reset after a delay:

![1](https://github.com/home-assistant/frontend/assets/71872483/7d289112-2b75-43e7-83a8-c9e09715f397)

**Comment by jtaseff** [comment]
Just found the same happening when trying to select entities for the Energy dashboard. Searching in the list either adding to individual devices for monitoring, or the total energy draw and price tracking.  Same as above, it does briefly show the search results, but after about a second or on mouseover it reverts to the full list.  It doesn't even filter by valid entities -- the price per kWh input box usually only showed entites with units of $/kWh, but now lists every sensor entity. Noticed on 2023.7.1, tried updating to 2023.7.2 and still doing it.

![image](https://github.com/home-assistant/frontend/assets/8671969/dc2fd1a8-b4b3-4596-ae04-6e3fc2fdda5d)

**Comment by jtaseff** [comment]
@ildar170975 I think we have the same issue but more widespread to many entity selectors - would you mind updating the issue title to reflect?

**Comment by WegnerDan** [comment]
It used to work like this: If you enter an entity id completely (with sensor. or whatever) then only this one entity would be found.
Now if I do this, the suggested items are all over the place. 

I've had this issue for at least a month now.

**Comment by ildar170975** [comment]
> @ildar170975 I think we have the same issue but more widespread to many entity selectors - would you mind updating the issue title to reflect?

Cannot reproduce it with Energy - have no energy entities; but I edited the title as you asked.

**Comment by karwosts** [comment]
This issue should be fully resolved now. 

#17098 enhanced the filter search to search for both name or entity_id (but it kind of broke the filter box in the attempt)
#17453 fixes the bugs introduced from #17098

**Comment by karwosts** [comment]
> It doesn't even filter by valid entities -- the price per kWh input box usually only showed entites with units of $/kWh, but now lists every sensor entity.

This would be a good topic for a new issue, that's unrelated to this one.

**Comment by jtaseff-gfms** [comment]
I'll try it once this was released - the behavior seemed similar that it used to auto filter by entities with matching units but the filter was disappearing.
Thanks for the main fix!
