### ISSUE TITLE
Developer Statistics Date picker not displaying in locale format

### ISSUE THREAD

**Issue by Spookster** [home-assistant/frontend#16914]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Developer tools > Statistics > Adjust a statistic

The date picker shows the date as mm/dd/yy which does not match the locale setting of dd/mm/yy

![image](https://github.com/home-assistant/frontend/assets/982535/51c70b1f-084c-4533-a195-8bd728fc8240)

### Describe the behavior you expected

Display the date picker based on locale setting

### Steps to reproduce the issue

No steps to reproduce, standard display 

### What version of Home Assistant Core has the issue?

All

### What was the last working version of Home Assistant Core?

None

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
Thought maybe this was fixed by #15770 ?

Are you on 2023.6?

**Comment by Spookster** [comment]
Sorry, it is sorted, my mistake
