### ISSUE TITLE
Uncaught (in promise) ChunkLoadError

### ISSUE THREAD

**Issue by bifbaf** [home-assistant/frontend#16919]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since a few updates it happens from time to time that my dashboard is no longer working correctly.
The overview page is working fine but some other elements are no longer working due to errors.

For example editing Dashboard is not working and the settings page neither.

I see this errors in the Debug console of my browser

`app-2AP83Z-w0C8.js:sourcemap:6 Uncaught (in promise) ChunkLoadError: Loading chunk 43642 failed.
(timeout: http://172.16.0.17:8123/frontend_latest/43642-emUifZxmJaw.js)
    at d.f.j (app-2AP83Z-w0C8.js:sourcemap:6:57001)
    at app-2AP83Z-w0C8.js:sourcemap:6:43923
    at Array.reduce (<anonymous>)
    at d.e (app-2AP83Z-w0C8.js:sourcemap:6:43901)
    at 26633-LBky4SQ5XzM.js:sourcemap:1:4849
    at o.value (26633-LBky4SQ5XzM.js:sourcemap:1:4908)
    at o.value (26633-LBky4SQ5XzM.js:sourcemap:1:4639)
    at o._$AE (app-2AP83Z-w0C8.js:sourcemap:6:40592)
    at o.performUpdate (app-2AP83Z-w0C8.js:sourcemap:6:40394)
    at o.scheduleUpdate (app-2AP83Z-w0C8.js:sourcemap:6:39976)`

`Failed to load resource: the server responded with a status of 404 (Not Found)`

Does anyone know what is causing this error?
After a complete restart it is working for a while and then the same is happening again.

It also looks like that Chrome Version 114.0.5735.133 has more problems with this issue.
In Firefox more parts of the UI are working but not all.

It maybe has something todo with a HACS plugin?

### Describe the behavior you expected

Home Assistant Dashboards and menus are working without issues

### Steps to reproduce the issue

Can't explain the steps. It happens suddenly

### What version of Home Assistant Core has the issue?

2023.6.1

### Which operating system are you using to run this browser?

Doesn't matter, MAC OS or Windows

**Comment by steverep** [comment]
> It maybe has something todo with a HACS plugin?

Disable any external resources, then test.  If the problem does not occur, please close this and file an issue with the plugin causing the problem.

**Comment by erkr** [comment]
I had a frondend freeze as well. In the error log the same app file was mentioned:
``` 
Logger: frontend.js.latest.202306080
Source: components/system_log/__init__.py:257 
First occurred: 08:45:15 (17 occurrences) 
Last logged: 11:03:45

:0:0 Script error.
http://192.168.178.47:8123/frontend_latest/app-2AP83Z-w0C8.js:2:48217 SecurityError: Attempt to use history.pushState() more than 100 times per 30 seconds
```

**Comment by bifbaf** [comment]
With the latest updates this error is fixed for me so I will close the issue.
