### ISSUE TITLE
Plant button is not displayed in case of problem

### ISSUE THREAD

**Issue by Matze89x** [home-assistant/frontend#16928]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

No icon is displayed on problem with plant in white frontend. In black frontend it is okay.

`<ha-state-icon tabindex="-1" data-domain="plant" data-state="problem" style="color: var(--state-plant-problem-color, var(--state-plant-active-color, var(--state-active-color))); height: 50px; filter: brightness(11350%);"></ha-state-icon>`

It is probably due to the "brightness(11350%)"

![Screenshot 2023-06-16 090628](https://github.com/home-assistant/frontend/assets/75788739/684b925b-edc6-4a3a-8759-d173d85c3e0e)

### Describe the behavior you expected

No Icon

### Steps to reproduce the issue

1.Plant with problem
2.new cards
3.button with plant entity
4. white theme
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.6.2

**Comment by karwosts** [comment]
Which card is this not working in? I checked button card and glance card and plant shows fine in a light theme; green when OK, red when problem.

**Comment by Matze89x** [comment]
It was corrected in 2023.6.3. Thanks.

**Comment by Matze89x** [comment]
Strange. I had no problem with the display at night. During the day, regardless of whether it is light or dark, it does not display. I have to open the problem again.

**Comment by karwosts** [comment]
`filter: brightness(11350%)`

Is this coming from your theme or some kind of custom cards? Do you know where that came from? I don't believe it's part of the default behavior, my plant has no brighness filter.

**Comment by Matze89x** [comment]
I don't use any other integrations or other templates - just actually from the original Home Assistant.

![image](https://github.com/home-assistant/frontend/assets/75788739/c763202d-09d8-4dd8-a766-3c0a967fbc79)

![image](https://github.com/home-assistant/frontend/assets/75788739/adcd43cf-2974-4f05-b4df-6bbac109d6d8)

**Comment by karwosts** [comment]
Ah ok I figured out why this happens. The brightness of the icon is derived from the brightness of the plant property. Maybe that needs to be clamped at some amount.

**Comment by Matze89x** [comment]
Okay but do I have to change anything or is it the home assistant? Should I still provide info on the plant entity?

![image](https://github.com/home-assistant/frontend/assets/75788739/0e50d991-38da-423a-af70-879a66eacdd6)

Ahhhhhhh!

Am I seeing right? That is the entity and the max_brightness? Oh dear...

**Comment by karwosts** [comment]
I don't think you need to do anything, probably a frontend bug. 

HA seems to be incorrectly interpreting the lux brightness as a brightness on a scale of 0-255 like a light, when normally 100,000 lux is a reasonable value. So when it sees high lux values it's computing a brightness property in the thousands of percentages, which is like pure white. 

Fix should not be too hard, I'll try to look into it some more.

**Comment by karwosts** [comment]
Filed a bugfix for this issue that should resolve it.
