### ISSUE TITLE
Homessistant web interface stuck with this error in console Uncaught (in promise) {code: 'unknown_error', message: 'Unknown error'}

### ISSUE THREAD

**Issue by magnum** [home-assistant/frontend#16920]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

starting some weeks ago my homeassistant (supervised, on a raspberry pi4) stopped randomly responding via web interface; this is the error i can see in web inspector:
```
Uncaught (in promise) {code: 'unknown_error', message: 'Unknown error'}
```

in the resources panel of the browser inspector i can i see it fails to get resources such as
```
https://[my-personal-id].ui.nabu.casa/frontend_latest/no-source/node_modules/home-assistant-js-websocket/dist/collection.js (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)
```
and a lot more others similar;

it happens most of the times after an upgrade of homeassistant core; sometimes if i try and try to reboot it works, it goes of for some hours, and then boom! when i try to use the web interface is doesn’t load returning me the error cited above (“Uncaught (in promise) etc.”)

### Describe the behavior you expected

i expected the dashboard to load

### Steps to reproduce the issue

1. reboot homeassistant instance
2. open the dasboard

### What version of Home Assistant Core has the issue?

2023.6

### Javascript errors shown in your browser console/inspector

```txt
dashboard:1 Uncaught (in promise) {code: 'unknown_error', message: 'Unknown error'}
```

**Comment by al-one** [comment]
Same errors.

**Comment by al-one** [comment]
```
2023-06-21 15:40:06.809 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281472549668176] Error handling message: Unknown error (unknown_error) Alone from 10.10.10.9 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 351, in handle_get_services
    descriptions = await async_get_all_descriptions(hass)
    domain_yaml = loaded[domain]
KeyError: 'input_number'
```

**Comment by al-one** [comment]
After I disabled the [`Remote Home-Assistant`](https://github.com/custom-components/remote_homeassistant) integration it returned to normal.
