### ISSUE TITLE
Script Editor does not have Feature Parity with Automation Editor.

### ISSUE THREAD

**Issue by SirGoodenough** [home-assistant/frontend#16924]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Recently (2023.3) the automation editor received some love that changes the add new button function to bring up a list of BluePrints with the Author names.  This is a great feature and should be extended to the Script editor.
https://www.home-assistant.io/blog/2023/03/01/release-20233/#new-create-automation-dialog

As it is, the Author tag https://www.home-assistant.io/docs/blueprint/schema/#author can be added to Scripts, however nothing is currently done with the information.

I added this as a feature request  but a developer recently suggested I add feature parity concerns as issues instead, IE the automation editor does it so the script editor should as well.

My feature request: https://community.home-assistant.io/t/add-scripts-built-from-blueprints-similar-to-new-automation-from-bp-feature/561560

### Describe the behavior you expected

Selecting add a script button should open a list of scripts and an option to create a blank script in the same manner that the automation editor add button does.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.3

### What was the last working version of Home Assistant Core?

n/a

### In which browser are you experiencing the issue with?

n/a

### Which operating system are you using to run this browser?

n/a

### Additional information

Release 2023.3 introduced the changes to the automation editor, but these changes were not extended to the script editor and now a big Feature Parity issue exists.

Since these 2 functions are very close in code, should steps be taken to insure feature parity between the 2 code sets?  Alternatively can they be merged?  That might make things easier to manage long term.

**Comment by karwosts** [comment]
PR filed to implement the new dialog.
