### ISSUE TITLE
Disappeared horizontal bar content in media-browser

### ISSUE THREAD

**Issue by evlas** [home-assistant/frontend#16931]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After the update to Home Assistant 2023.6.0 the content of the horizontal bar of the media browser page has disappeared

### Describe the behavior you expected

I expect: playing item, progress bar and select for the media_player

### Steps to reproduce the issue

1. Update  to Home Assistant 2023.6.0

### What version of Home Assistant Core has the issue?

core-2023.6.*

### What was the last working version of Home Assistant Core?

core-2023.5.*

### In which browser are you experiencing the issue with?

Chrome 114.0.5735.134 64 bit

### Which operating system are you using to run this browser?

Linux Debian 11.2

**Comment by jtary** [comment]
I think I have a bit of context that applies to this issue.

The content is failing to display due to an exception in `_mediaPlayerEntities()` method from `ha-bar-media-player.ts`

```
ha-bar-media-player.ts:467 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'hidden')
    at ha-bar-media-player.ts:467:47
    at Array.filter (<anonymous>)
    at i.value (ha-bar-media-player.ts:463:45)
    at i.value (ha-bar-media-player.ts:351:20)
    at i.value (ha-bar-media-player.ts:277:14)
    at i.update (lit-element.ts:160:24)
    at i.performUpdate (reactive-element.ts:1331:14)
    at i.scheduleUpdate (reactive-element.ts:1263:17)
    at i._$Ej (reactive-element.ts:1235:25)
```

Specifically this error is occuring because (at least in my install) there seems to be entities that are in `this.hass.states`, but not `this.hass.entities`. For me, those entities are:

```
[
    "zone.home",
    "sun.sun",
    "media_player.ytube_music_player"
]
```

```ts
  private get _mediaPlayerEntities() {
    return Object.values(this.hass!.states).filter(
      (entity) =>
        computeStateDomain(entity) === "media_player" &&
        supportsFeature(entity, MediaPlayerEntityFeature.BROWSE_MEDIA) &&
        !this.hass.entities[entity.entity_id].hidden // <-- there should be a check here to ensure the entity exists before resolving hidden
    );
  }
  ```

**Comment by LeoCal** [comment]
Hello, 

I think this is a duplicate of [#16818](https://github.com/home-assistant/frontend/issues/16818)

**Comment by wildoracle** [comment]
> I think I have a bit of context that applies to this issue.
> 
> The content is failing to display due to an exception in `_mediaPlayerEntities()` method from `ha-bar-media-player.ts`
> 
> ```
> ha-bar-media-player.ts:467 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'hidden')
>     at ha-bar-media-player.ts:467:47
>     at Array.filter (<anonymous>)
>     at i.value (ha-bar-media-player.ts:463:45)
>     at i.value (ha-bar-media-player.ts:351:20)
>     at i.value (ha-bar-media-player.ts:277:14)
>     at i.update (lit-element.ts:160:24)
>     at i.performUpdate (reactive-element.ts:1331:14)
>     at i.scheduleUpdate (reactive-element.ts:1263:17)
>     at i._$Ej (reactive-element.ts:1235:25)
> ```
> 
> Specifically this error is occuring because (at least in my install) there seems to be entities that are in `this.hass.states`, but not `this.hass.entities`. For me, those entities are:
> 
> ```
> [
>     "zone.home",
>     "sun.sun",
>     "media_player.ytube_music_player"
> ]
> ```
> 
> ```ts
>   private get _mediaPlayerEntities() {
>     return Object.values(this.hass!.states).filter(
>       (entity) =>
>         computeStateDomain(entity) === "media_player" &&
>         supportsFeature(entity, MediaPlayerEntityFeature.BROWSE_MEDIA) &&
>         !this.hass.entities[entity.entity_id].hidden // <-- there should be a check here to ensure the entity exists before resolving hidden
>     );
>   }
> ```

@jtary would be great to consolidate this feedback into the other posted issue #16818

**Comment by jtary** [comment]
> @jtary would be great to consolidate this feedback into the other posted issue #16818

@wildoracle added it here https://github.com/home-assistant/frontend/issues/16818#issuecomment-1604637077
