### ISSUE TITLE
Glance card toggle and entity card slider highlit stuck

### ISSUE THREAD

**Issue by Andrea9530** [home-assistant/frontend#16935]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using a mouse to toggle a glance card entity that has the attribute tap_action: set in yaml produces this effect where the background color stays stuck and the entity box shifts down, unless you click somwhere else. This effect it's not present at all using touchscreen.
![ha problem glance](https://github.com/home-assistant/frontend/assets/65161045/d2c7bf12-2b60-4b6a-9b2a-ac96dcd83684)
This also happens with entity cards contaning switches
![immagine](https://github.com/home-assistant/frontend/assets/65161045/10aaecbb-aa78-4f12-a8fa-abf40fd79136)
This issue is similar to the #4788 but it seems like the button card doesn't have this problem anymore
The glance card problem only happens with mouse whereas the switch one also happens with touchscreen

### Describe the behavior you expected

The animation doesn't get stuck
![immagine](https://github.com/home-assistant/frontend/assets/65161045/f215309d-3d8b-4306-8669-1d8c3a8dca2b)

### Steps to reproduce the issue

glance card:
1. create a glance card, add an entity and set
`tap_action:`
 `  action: toggle`
2. toggle the created entity using a mouse

switch:
1. create an entity card and select an entity that is a switch
2. toggle the switch

### What version of Home Assistant Core has the issue?

core-2023.6.2

**Comment by ildar170975** [comment]
Confirm this:
```
type: glance
entities:
  - entity: input_boolean.test_boolean
    tap_action:
      action: toggle
```
![a1](https://github.com/home-assistant/frontend/assets/71872483/dee5692b-913d-4b50-8058-62ef8ffadfd1)

**Comment by ildar170975** [comment]
[Seems that this is a reason](https://github.com/home-assistant/frontend/blob/bf18deb83cde79ad84e281ee236af785dc156518/src/panels/lovelace/cards/hui-glance-card.ts#L213)
Can be fixed by card-mod:
```
type: glance
entities:
  - entity: input_boolean.test_boolean_6
    tap_action:
      action: toggle
  - entity: input_boolean.test_boolean_6
    tap_action:
      action: toggle
  - entity: input_boolean.test_boolean_6
    tap_action:
      action: toggle
  - entity: input_boolean.test_boolean_6
    tap_action:
      action: toggle
  - entity: input_boolean.test_boolean_6
    tap_action:
      action: toggle
  - entity: input_boolean.test_boolean_6
    tap_action:
      action: toggle
  - entity: input_boolean.test_boolean_6
    tap_action:
      action: toggle
card_mod:
  style: |
    .entity:focus {
      padding: 0px 4px !important;
      margin: 0 0 12px 0 !important;
    }
```
![a1](https://github.com/home-assistant/frontend/assets/71872483/99d38549-46a4-4a8e-947e-6b586fd594aa)

![a2](https://github.com/home-assistant/frontend/assets/71872483/70b1f106-66ce-427f-a4ab-79f7f87e2d60)

**Comment by Andrea9530** [comment]
Thanks, don't want to bother you too much but what about the switch one? Looks like the focus option gets stuck, noticed that in other buttons too, such as all the calendar buttons in the area of this photo, they all get that circle that doesn't go away, this also happens with touchscreen though
![immagine](https://github.com/home-assistant/frontend/assets/65161045/c122e3a6-532a-40bc-a91f-3b45560d7d99)

**Comment by ildar170975** [comment]
Suggest you to create a separate issue.
