### ISSUE TITLE
Memory leak when keeping the dashboard open on a tablet or mobile (narrow) device

### ISSUE THREAD

**Issue by VinceRMP** [home-assistant/frontend#16952]
### The problem

The memory leak seems to have started after updating HAOS to 10.2 or core 2023.6 beta (coming from a dev build in the early stage of 2023.5, so it could also be related to a late 2023.5 specific version).
What I have noticed is that my memory increase is caused by my tablet which shows the dashboard 24/7. 
I can reproduce the start of the memory leak and stop it aswell after some testing.
Bdraco had a look in my (profiler) logs and he said there are no obvious task leaks in the them, so I'm not sure if it is an issue in core or frontend. 

![image](https://github.com/home-assistant/core/assets/31448122/d501e24f-59d5-465d-a51f-188c1bd81354)
At the first drop in memory I did a restart of Home Assistant, but didn't refresh the webapp running on my tablet.
This causes the memory to increase as you can see. Around 08:00 I restarted the webapp on the tablet.
The memory stays the same, so no memory leak visible.
Around 09:00 I did another restart of Home Assistant without restarting the webapp on the tablet and there is the memory leak again.

This is also reported in the logs:
`[139928754006096] Tablet from  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.43): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":22632,"type":"result","success":true,"result":null} [139928813456528] Tablet from  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.43): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":20399,"type":"result","success":true,"result":null} [139928532840656] Tablet from  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.43): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":20538,"type":"result","success":true,"result":null} [139928688859152] Tablet from  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.43): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":70314,"type":"result","success":true,"result":null} [139928776142096] Tablet from  (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.43): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":30737,"type":"result","success":true,"result":null}`

### What version of Home Assistant Core has the issue?

core-2023.6.2

### What was the last working version of Home Assistant Core?

core-2023.5.0?

### What type of installation are you running?

Home Assistant OS

**Comment by bdraco** [comment]
confirmed thats where its coming from

**Comment by bdraco** [comment]
<img width="333" alt="Screenshot 2023-06-17 at 6 13 46 PM" src="https://github.com/home-assistant/frontend/assets/663432/9432c27b-130f-4fcf-b0ec-e7e58c2664a8">

**Comment by backcountrymountains** [comment]
Where is ```ha-menu-button``` used in the frontend and how do I kill it with fire?

**Comment by bdraco** [comment]
> Bdraco had a look in my (profiler) logs and he said there are no obvious task leaks in the them, so I'm not sure if it is an issue in core or frontend.

@VinceRMP Your initial suspicions were correct and `frontend` turned out to be the winner here.

**Comment by ondras12345** [comment]
Why doesn't core release the memory it had allocated after the `persistent_notification/subscribe` messages stop coming? I have tested this by disabling Wi-Fi on the mobile phone I use for 24/7 dashboard display. The 1GB extra memory usage never decreased.

**Comment by bdraco** [comment]
> Why doesn't core release the memory it had allocated after the `persistent_notification/subscribe` messages stop coming? I have tested this by disabling Wi-Fi on the mobile phone I use for 24/7 dashboard display. The 1GB extra memory usage never decreased.

I think it’s because we suppress the cancellation https://github.com/home-assistant/core/pull/94780

**Comment by ondras12345** [comment]
With the patch from https://github.com/home-assistant/core/pull/94780 applied, I let it leak about 400MB and then killed the misbehaving client.
Memory usage hasn't decreased yet:
![image](https://github.com/home-assistant/frontend/assets/44524735/c8aae6f6-ce35-4c9e-befe-87e12cbd4ecb)
I'll leave it like this overnight and report if it does release the extra memory.

**Comment by bdraco** [comment]
@ondras12345 Please continue in https://github.com/home-assistant/core/pull/94780 (trying the latest commit) since this issue was for the frontend and that problem has already been fixed.
