### ISSUE TITLE
Invalid Icon Bug

### ISSUE THREAD

**Issue by KyangTan** [home-assistant/frontend#16950]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The system does not produce an error indicating that the icon chosen is invalid, leading to an empty icon at the entity. The user is able to delete some of the characters after selecting the icon.

### Describe the behavior you expected

The user cannot update the entity with the new entity icon. An error pops out indicating the entity ID is invalid.

### Steps to reproduce the issue

1. Click on the “Home Precipitation” entity on the “Overview” page.
2. Click on the Settings icon in the top right corner.
3. Fill in “Precipitation” on the name text field.
4. Fill in “mdi:weather-fo” on the Icon text field.
5. Fill in “mm/h” on the Unit of Measurement text field.
6. Fill in “Default (0)” on the Display precision text field.
7. Fill in “sensor.home_precipitation” on the Entity ID text field.
8. Click on the “Update” button.

### What version of Home Assistant Core has the issue?

core-2023.4.6

### In which browser are you experiencing the issue with?

Google Chrome, Version 114.0.5735.110 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 Pro with Oracle VM VirtualBox Manager, Version 7.0.4 r154605 (Qt5.15.2)

**Comment by christophwen** [comment]
I don't think this is a bug. If you you want an icon and no icon is shown, than you can go back in the settings of the card reselect the wanted icon. If in the future new icons are added or some are removed (which hardly will happen) you don't want your dashboard to be broken. 

Additionally when creating a card and the icon input is invalid you directly see that no icon is shown in the preview and on the left side of the icon field/dropdown.

If someone else has a other opinion on that topic, I can create validation for the icon field.

**Comment by ildar170975** [comment]
Many users intentionally define a non-existing icon like `mdi:none`, `mdi:blank` etc.
