### ISSUE TITLE
Energy Dashboard not displaying data in Consumption tab intermittently

### ISSUE THREAD

**Issue by cmer81** [home-assistant/frontend#16985]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Energy Dashboard in Home Assistant occasionally fails to display information in the Consumption tab, including energy sources. However, the Devices Monitored section continues to function properly. After a certain period of time, all the missing entries suddenly appear.

We can see that after two days it displays the energy consumption and calculates the consumption of the empty days.

![](https://zupimages.net/up/23/25/jp4r.png)

Same problem Today

![](https://zupimages.net/up/23/25/lj41.png)

### Describe the behavior you expected

I expected the Energy Dashboard to consistently display all relevant information, including energy sources, in the Consumption tab. The data should be continuously updated and not experience intermittent gaps.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.6.2

### In which browser are you experiencing the issue with?

Brave v1.52.122

### Which operating system are you using to run this browser?

Arch Linux

### Additional information

I have exactly the same problem with the mobile application.

![](https://zupimages.net/up/23/25/o2gc.png)

**Comment by cmer81** [comment]
After some Google research, other people seem to have the same problem. 

https://community.home-assistant.io/t/energy-dashboard-not-working-anymore/542979

**Comment by karwosts** [comment]
Could you expand a bit on your issue? I don't think there's enough here to debug. 

What do you mean "fails to display information"? 

Are you referring to the fact that there is no energy consumed on June 14 / June 15?

What does the source sensor say for those days? Do you have any evidence that whatever source provides this data to you reported any consumption on those days?
