### ISSUE TITLE
Cannot fix invalid energy dashboard data

### ISSUE THREAD

**Issue by swa72** [home-assistant/frontend#17010]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a sensor for my gas usage (ESPhome) which has been working nicely with the Energy dashboard until about a week ago. At that day the Energy dashboard shows a huge negative value (I may have updated HA on that day, now running 2023.6.2).

![image](https://github.com/home-assistant/frontend/assets/17599763/46c18663-b8c4-4240-8dd2-64dc09f26b0c)

This should be quick to fix, by going to to Developer | Statistics and remove any bad reading. 

However, there is no such reading in that timeframe ;-/

![image](https://github.com/home-assistant/frontend/assets/17599763/18248ff1-a394-4c61-88b8-3294f6f2961b)

I've searched that evening in 5min steps to no avail. Do I have to go into HA's internals to fix this? 

Here is my ESP config, just in case ...

```
# gas meter
  - platform: pulse_counter
    pin: 21
    name: "Gasverbrauch"
    update_interval : 60s
    filters:
      - lambda: |-
          static float total_value = 0.0;
          total_value += x * 0.01;
          return total_value;
    unit_of_measurement: "m³"
    accuracy_decimals: 2
    icon: 'mdi:fire'
```

### Describe the behavior you expected

I can correct all values thru Developers | Statistics of that particular entity.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.6.2

### Which operating system are you using to run this browser?

Win 10

**Comment by karwosts** [comment]
Does the sensor have `state_class: total` ?

I'm not sure how to fix it now, but I don't think it would have happened if it was `total_increasing`, which is probably more correct.

**Comment by karwosts** [comment]
Ah ok, nevermind then. I was hoping that was the issue, but it must be something else.

**Comment by karwosts** [comment]
Unfortunately what you have is not a "bad sensor reading", which could be fixed in the statistics ui, but the result of a HA bug wherein the cumulative sum for a statistics sensor got accidentally reset when it should not.

I believe the underlying bug has been fixed, but you're left with a corrupted database. 

It is possible to fix this but you will have to do it in raw SQL, which is possible in haos if you install the sqlite addon. 

If you want me to walk you through the steps to do so let me know if you want to take that approach once you have the addon installed (or if you already know how to access the database in another way).

**Comment by karwosts** [comment]
I'm going to leave some notes here on how I fixed this, assuming a sensor with `state_class: total_increasing` that is not supposed to decrease in value.

1. Install SQLite addon, go to the addon UI page. In my case it was http://homeassistant.local:8123/hassio/ingress/a0d7b954_sqlite-web
2. Select `statistics_meta` table, and `Query`. 
3. Run this command:
```
SELECT * FROM "statistics_meta"
WHERE statistic_id is "sensor.YOUR_SENSOR_NAME_HERE"
```
4. You will get a result with one record. Note the value in the `id` column. 
5. Select `statistics` table, and `Query`. 
6. Run this command, with `<id>` being the value from step 4. 
```
SELECT * FROM "statistics"
WHERE "metadata_id" IS "<id>"
```
e.g.
```
SELECT * FROM "statistics"
WHERE "metadata_id" IS "279"
```
7. You will get a result with hundreds/thousands of records. Note the sum column should be continually increasing as it goes down. You are looking for a row where the sum column drops suddenly, it should correspond with the time in your graph where the big negative drop occurs. 
Note here the column where the sum drops from 725 to 1.87777. The value in the row with the drop is not important, just note that it has significantly reset or decreased, it could be 0 or a small number. 
![image](https://github.com/home-assistant/frontend/assets/32912880/09905240-6e5f-447c-bcc0-e03791d96783)

From here you want to note two things, the `id` field for the first row containing the drop, and note the value of the `sum` from before it decreased. 

8. Now that you have this information, you can run the following query. Be careful with this as you can blow up your data if you don't do it right.
```
UPDATE "statistics"
SET sum = sum + <sum from step 7>
WHERE "metadata_id" IS "<id from step 4>" 
AND 
"id" >= <id from step 7>
```
e.g.:
```
UPDATE "statistics"
SET sum = sum + 725.243
WHERE "metadata_id" IS "279" 
AND 
"id" >= 1382082
```

After you run this you should get a terse result like "N rows updated".

At this point you can refresh your web browser, and the negative spike should be gone.

**Comment by rrozema** [comment]
To find the row that has the drop (step 6), better use a query like below, that finds the row(s) where the value for sum is smaller than that on the last row before it.
`select t.*, t.sum - t.sum_previous as difference from (select s.*, lag(s.sum) over (partition by s.metadata_id order by s.start_ts) as sum_previous from statistics s) t where t.metadata_id = <id> and t.sum < t.sum_previous order by t.start_ts desc;`

**Comment by swa72** [comment]
Ok, many thanks for @karwosts and @rrozema, I fixed it although me setting was a bit different. 

I use **mariadb** and **phpMyAdmin** and can confirm that the above steps work here as well.

My steps (see https://github.com/home-assistant/frontend/issues/17010#issuecomment-1615267071) were ...

4)
```SELECT * FROM `statistics_meta` WHERE `statistic_id`="sensor.gasverbrauch"``` 
Note the form of the quotes. Result in my case 117.

6 and 7)
Use https://www.epochconverter.com/ to get correct time for the > (narrows down the table to the faulty ones)
```SELECT * FROM `statistics` WHERE `metadata_id`="117" AND `start_ts` > 1686700800```
The `1686700800` is the day/time where trouble began.
Or use @rrozema approach to find the id field for the first `row` containing the drop

8)
Last step in my case was
```
UPDATE `statistics`
SET sum = sum + 5816.840000004125
WHERE `metadata_id`="117" 
AND 
`id`>=2992418
```

**Comment by swa72** [comment]
> 
> I believe the underlying bug has been fixed, but you're left with a corrupted database.
> 

Do you happen to have a link to the bug?

**Comment by karwosts** [comment]
Actually now I'm not so sure it has been fixed. I was thinking of some issue specifically related to riemann sums being reset when they shouldn't, but now I'm wondering if this could happen to any sensor. I'm not sure yet what's triggering it.

**Comment by rrozema** [comment]
Following query can give you some more insight in what exactly the contents of the statistics and the statistics_short_term table are. The query lists all data points recorded on a particular day for one particular statistic, adding to the rows properties the previous row's state and sum, plus the difference between this row and the previous one for each data point.
```
select *, strftime('%Y-%m-%d %H:%M:%f', start_ts, 'unixepoch') as start_dt, lag(state, 1) over (partition by metadata_id order by start_ts) as state_previous, state - lag(state, 1) over (partition by metadata_id order by start_ts) as state_difference, lag(sum, 1) over (partition by metadata_id order by start_ts) as sum_previous, sum - lag(sum, 1) over (partition by metadata_id order by start_ts) as sum_difference from main.statistics where metadata_id = 118 and start_ts >= (julianday('2023-07-01T00:00:00.000') - 2440587.5)*86400.0 and start_ts < (julianday('2023-07-02T00:00:00.000') - 2440587.5)*86400.0 order by start_ts;
```
I have seen examples where a device was temporary unavailable. Depending on the timing I think this can sometimes make the recorder behave strangely: It seems to sometimes reset the running total to 0, and then when the device comes back available and again reports the previous value the recorder can record a very large difference. I think a scenario like this can somehow result in the recorder registering a difference in a single step that is as large as the difference between the reset value (0 most of the times) and the current value of the continuously increasing meter value. I have reported an [issue](https://github.com/MindFreeze/ha-sankey-chart/issues/118) like this for the HACS sankey-card (a very nice, but so far un-official energy card). In that situation I could exactly explain what happened. I have however not yet found a clear example yet where I could catch the the official energy cards doing something similar. But I too do see some un-explainable spikes plus negative growing values sometimes (the negative growth seems like rounding errors to me, as they are usually very small values).
So, by no means I think I can give an explanation of the behavior you observed, but I thought I'd give you the query so you can have a better look at the underlying data the recorder produces and the energy cards read.

**Comment by swa72** [comment]
Ok, having run the SQL queries once did not do the job :-/. If the sensor reports data again after a while, the energy dashboard again shows a huge negative value. Given that I‘ve upgraded to 2023.07 in the meantime, I doubt that any bug has been fixed.

I cannot run the query in https://github.com/home-assistant/frontend/issues/17010#issuecomment-1616018071 as it reports errors. „main.statistics“ does not exist - I fixed that by just using „statistics“. The next error was „Function homeassistant.strftime does not exist“ and here ends my SQL knowledge ;-)

Do I have to fix anything in `statistics_short_term`?

**Comment by rrozema** [comment]
@swa72 : I would not recommend making too much changes in the statistics table based on the above info. The information from me (and probably that from karwosts as well) is derived from looking at the contents of the database tables mostly, not from intimate knowledge of the workings of the recorder component. i.e. There may be other functionalities involved that were not known to me (or karwosts) at the time of writing. At the very least do make proper backups of your tables if you make any changes!
b.t.w. do you happen to have another database than sqlite configured for your home assitant instance? Because that is the only thing I can think of that explains why you had to remove the "main." from the query and do not have the strftime() function.

**Comment by swa72** [comment]
@rrozema Thanks for the infos and you were right in assuming I use another db. I switched to MariaDB some time ago.
In general I do not mind rounding errors and somesuch but if you have a reading of -6.000kW on one day, the scale of the graph gets messed up (for the month and the year). Makes the entire thing useless ;-/

**Comment by roumano** [comment]
Hi,
i got the same kind of issue on my energy dashboard due to nearly 2 days of unavailable sensor.
when the sensor come back, i got a huge postive spick on 3 sensors.

The "new" sensor value is exactly the same as before the unavailable (i can see it on mqtt browser ) ( so i don't get any row where the value for sum is smaller than that on the last row before it.)

- i can't use Developer | Statistics and remove any bad reading as they bad value are not in
- i try but it's not working the trick with first adjust the statistic into some fictive value like for example 123, then later re-edit it to the value I actually want it to have, like 0 for example.

- i've update the sqlite database to remove the spick, it's working
  - but a new spick (with same value) is coming at the date of the modification

  - The first spick : 
![7_july](https://github.com/home-assistant/frontend/assets/6402894/9a0054ec-693a-49cf-94ca-b4c97dee457b)
  - after removing the spick of 6 july, a new spick appear when the modification was done : 
![21_july](https://github.com/home-assistant/frontend/assets/6402894/834c7fbe-3552-40dd-9f95-599cc8e65c1c)

- any idea why remove previous spick create a new spick with the same value as old one ? 

ps : i use this sqlite command to modify ( my sensor value doesn't change since may as it's used only in the winter)
```
UPDATE `statistics`
SET sum = 244.383
WHERE `metadata_id`="565" 
AND 
`sum`=488.764
```
on another sensor, i use this kind of sqlite command: 
```
UPDATE `statistics`
SET sum = sum-10.317
WHERE `metadata_id`="567" 
AND
`id`>=2176544
```

**Comment by rrozema** [comment]
> * any idea why remove previous spick create a new spick with the same value as old one ?

The graph shows the difference between the [sum] values for one entry and its 'previous' entry. When you delete one entry, the next available entry before that will become the new 'previous' entry. Because this new 'previous' entry has (almost) the same data as the one you just deleted, you'll get exactly the same spike, only over a somewhat longer time frame.

**Comment by karwosts** [comment]
@lolmachine4 - Can you expand your comment with some thorough datapoints? I'd be curious exactly what data is in your SQL table each hour, and exactly what you mean by a "0 entry".

**Comment by karwosts** [comment]
For now I think I will suggest lets stop trying to modify the SQL tables directly, I think the same thing can be achieved by using the "fix a statistic" dialog in developer tools. 

Lets let everything rest for a few hours, then take a picture of your dashboard graph that shows the erroneous datapoint. We can then see if there's an update we can make in statistics devtools that will remove it.

**Comment by swa72** [comment]
Having run the DB fix a couple of times, I sadly can confirm that the error re-appears:

![image](https://github.com/home-assistant/frontend/assets/17599763/9cc11927-80cd-4003-a377-9efe7c8521d6)

It is a gas sensor that doesn't do much these summer days. But once some gas gets consumed, HA records it incorrectly (6.3499) resulting in a huge negative spike from the previous sum 

I should add that the entire thing worked flawlessly for more than a year, including reboots, updates and somesuch.

Checking Developer | Statistics doesn't help (e.g. removing the 0.03 reading) either.

I would like to try the following: 
- turn off the gas sensor device
- fix all sum entries (zero them first, then run something like sum = previous sum + state)
- reboot HA (flushing any caches)
- reboot gas sensor device

and see if that works. 

Sadly my SQL knowledge is not sufficient to create that query.

**Comment by karwosts** [comment]
@lolmachine4 - so if you do "fix statistic" dialog at ~21:40 for august 6, it shows a 0 there? 

And if you look on energy dashboard, in the 21-22 hour for august 6 it shows a bar for +30kWh at 21-22pm?

If that's the case you can try "fixing" the 0 to change it to -30, and I think that may remove the erroneous bar.


Note that we're actually straying pretty far from a frontend issue here since all this is actually wrong in the backend database. I'll try to finish up getting a bandaid on some of these issues but this probably should be closed and moved to a core issue.

**Comment by karwosts** [comment]
Try change the datapoint at 22:00 from `0` to `30.05`. My guess is that will make the bad point go away.

**Comment by karwosts** [comment]
For now I'm going to close this as all the issues reported here are actually core issues with statistics, which is not really something can be fixed in frontend. 

If you get future cases of seeing long term statistics values getting reset unintentionally, I would open a core issue for long term statistics.

**Comment by swa72** [comment]
I noticed by accident that my huge negative spike of -5800m3 suddenly showed up in Developer | Statistics. I zero'ed that value and, fingers crossed, everything looks good. Odd.

**Comment by taitadam-eng** [comment]
> I'm going to leave some notes here on how I fixed this, assuming a sensor with `state_class: total_increasing` that is not supposed to decrease in value.
> 
> 1. Install SQLite addon, go to the addon UI page. In my case it was http://homeassistant.local:8123/hassio/ingress/a0d7b954_sqlite-web
> 2. Select `statistics_meta` table, and `Query`.
> 3. Run this command, specifying your sensor name you want to fix:
> 
> ```
> SELECT * FROM "statistics_meta"
> WHERE statistic_id is "sensor.YOUR_SENSOR_NAME_HERE"
> ```
> 
> 4. You will get a result with one record. Note the value in the `id` column.
>    ![image](https://user-images.githubusercontent.com/32912880/250211700-d893870a-840b-4406-8a79-0e12e3d767cb.png)
> 5. Select `statistics` table, and `Query`.
> 6. Run this command, with `<id>` being the value from step 4.
> 
> ```
> SELECT * FROM "statistics"
> WHERE "metadata_id" IS "<id>"
> order by start_ts asc
> ```
> 
> e.g.
> 
> ```
> SELECT * FROM "statistics"
> WHERE "metadata_id" IS "279"
> order by start_ts asc
> ```
> 
> 7. You will get a result with hundreds/thousands of records, depending on the age of your sensor. Note the sum column should typically be continually increasing as you scroll down through the rows. You are looking for a row where the sum column drops suddenly, it should correspond with the time in your graph where the big negative drop occurs.
>    Note here the column where the sum drops from 725 to 1.87777. The value in the row with the drop is not important, just note that it has significantly reset or decreased, it could be 0 or a small number.
>    ![image](https://user-images.githubusercontent.com/32912880/250211206-09905240-6e5f-447c-bcc0-e03791d96783.png)
> 
> From here you want to note two things, the `id` field for the first row containing the drop, and note the value of the `sum` from before it decreased.
> 
> 8. Now that you have this information, you can run the following query. Be careful with this as you can blow up your data if you don't do it right.
> 
> ```
> UPDATE "statistics"
> SET sum = sum + <sum from step 7>
> WHERE "metadata_id" IS "<id from step 4>" 
> AND 
> "id" >= <id from step 7>
> ```
> 
> e.g.:
> 
> ```
> UPDATE "statistics"
> SET sum = sum + 725.243
> WHERE "metadata_id" IS "279" 
> AND 
> "id" >= 1382082
> ```
> 
> After you run this you should get a terse result like "N rows updated".
> 
> At this point you can refresh your web browser, and the negative spike should be gone.

This really helped me, thankyou.

**Comment by roumano** [comment]
> > I'm going to leave some notes here on how I fixed this, assuming a sensor with `state_class: total_increasing` that is not supposed to decrease in value.
> > 
> > 1. Install SQLite addon, go to the addon UI page. In my case it was http://homeassistant.local:8123/hassio/ingress/a0d7b954_sqlite-web
> > 2. Select `statistics_meta` table, and `Query`.
> > 3. Run this command, specifying your sensor name you want to fix:
> > 
> > ```
> > SELECT * FROM "statistics_meta"
> > WHERE statistic_id is "sensor.YOUR_SENSOR_NAME_HERE"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 4. You will get a result with one record. Note the value in the `id` column.
> >    ![image](https://user-images.githubusercontent.com/32912880/250211700-d893870a-840b-4406-8a79-0e12e3d767cb.png)
> > 5. Select `statistics` table, and `Query`.
> > 6. Run this command, with `<id>` being the value from step 4.
> > 
> > ```
> > SELECT * FROM "statistics"
> > WHERE "metadata_id" IS "<id>"
> > order by start_ts asc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > e.g.
> > ```
> > SELECT * FROM "statistics"
> > WHERE "metadata_id" IS "279"
> > order by start_ts asc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 7. You will get a result with hundreds/thousands of records, depending on the age of your sensor. Note the sum column should typically be continually increasing as you scroll down through the rows. You are looking for a row where the sum column drops suddenly, it should correspond with the time in your graph where the big negative drop occurs.
> >    Note here the column where the sum drops from 725 to 1.87777. The value in the row with the drop is not important, just note that it has significantly reset or decreased, it could be 0 or a small number.
> >    ![image](https://user-images.githubusercontent.com/32912880/250211206-09905240-6e5f-447c-bcc0-e03791d96783.png)
> > 
> > From here you want to note two things, the `id` field for the first row containing the drop, and note the value of the `sum` from before it decreased.
> > 
> > 8. Now that you have this information, you can run the following query. Be careful with this as you can blow up your data if you don't do it right.
> > 
> > ```
> > UPDATE "statistics"
> > SET sum = sum + <sum from step 7>
> > WHERE "metadata_id" IS "<id from step 4>" 
> > AND 
> > "id" >= <id from step 7>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > e.g.:
> > ```
> > UPDATE "statistics"
> > SET sum = sum + 725.243
> > WHERE "metadata_id" IS "279" 
> > AND 
> > "id" >= 1382082
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After you run this you should get a terse result like "N rows updated".
> > At this point you can refresh your web browser, and the negative spike should be gone.
> 
> This really helped me, thankyou.

yes it's working for negative spick but not in case of a bug ( see my comment in https://github.com/home-assistant/frontend/issues/17010#issuecomment-1645450065 )
