### ISSUE TITLE
No more Zigbee2MQTT shown in Companion App

### ISSUE THREAD

**Issue by gatonero** [home-assistant/frontend#17016]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The screen in companion app for z2m is blank.

### Describe the behavior you expected

Present all z2m devices as a table

### Steps to reproduce the issue

1. Start companion app on android device
2. Click Zigbee2MQTT

### What version of Home Assistant Core has the issue?

2023.6.3

### What was the last working version of Home Assistant Core?

2023.5

### In which browser are you experiencing the issue with?

Companion app 

### Which operating system are you using to run this browser?

Android

**Comment by spacegaier** [comment]
I think we need more info to assist. Is this issue only appearing on Android? I think "Zigbee2MQTT" is an addon, so not sure if the panel you seem to be clicking on is part of the HA frontend itself or provided by the addon...

**Comment by gatonero** [comment]
Out of a sudden it appeared again. Thnak you!
