### ISSUE TITLE
Error loading the view strategy: TypeError: n[0] is undefined

### ISSUE THREAD

**Issue by maltetgh** [home-assistant/frontend#17019]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After migrating Shelly from HACS to the built in integration and the required renaming/ordering of the entities, I was not able to access the automatically generated Dashboard anymore

Error loading the view strategy:

TypeError: undefined is not an object (evaluating 'n[0].toUpperCase')

See other users: https://github.com/home-assistant/frontend/issues/11789

This pointed me in the right direction... after copy&pasting all my shelly entities into BBEdit and making invisible characters visible, I discovered, that one Area had an space at the end.

After removing it, the Dashboard worked again. 

<img width="210" alt="Bildschirmfoto 2023-06-24 um 14 08 09" src="https://github.com/home-assistant/frontend/assets/20049060/5dbdc4ff-17df-4a9f-a5d4-38ff7508624e">

### Describe the behavior you expected

Dashboard should work

### Steps to reproduce the issue

I cannot reproduce how the character space was added at the end of the area name, it seems HA tries to filter this out in the frontend. But at some-point it seems to be possible and it is hard to identify.

If you have an area with a SPACE at the end of the name... the Dashboard will break down. 

### What version of Home Assistant Core has the issue?

2023.6.2

**Comment by karwosts** [comment]
Possibly same as #16645. Thanks for the detailed report.

**Comment by karwosts** [comment]
What do you mean exactly when you say 

> After removing it, the Dashboard worked again.

How did you remove the space? Did you go to settings->Areas->Kuche, and clicked the pencil to rename the HA area? And it let you enter the same name again, but without a space this time?

Do you mean the HA Area had a space in the name, or something specific in the entity/device had a space in the name? 

What screen did you copy this from, exactly?

![image](https://github.com/home-assistant/frontend/assets/32912880/8f945cef-b37a-4de6-865b-17e2dd78816f)


Sorry for the detailed questions, just trying to understand how I might reproduce this.

**Comment by karwosts** [comment]
Starting to partially find a way to reproduce this, but not all the way there yet. 

* Add a shelly device, assign it to an area like "Kitchen".
* Go to developer tools, and use the override panel to force the friendly name of the switch to "Kitchen ".
* The overview panel will be broken with the following call stack:

```
get-strategy.ts:88 TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at stripPrefixFromEntityName (strip_prefix_from_entity_name.ts:23:1)
    at computeCards (generate-lovelace-config.ts:194:1)
    at generateDefaultViewConfig (generate-lovelace-config.ts:503:1)
    at OriginalStatesStrategy.generateView (original-states-strategy.ts:38:1)
    at async generateStrategy (get-strategy.ts:84:1)
    at async HUIView._initializeConfig (hui-view.ts:192:1)
```

So far I've only been able add a trailing space to the friendly name in devtools set state panel, I'm not sure yet how an entity could get that added without this, maybe it has to have a space in the name in the shelly device itself before importing.
