### ISSUE TITLE
New Frontend view named "1" creates bug

### ISSUE THREAD

**Issue by antstyl** [home-assistant/frontend#17060]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a dashboard with 6 cards.
As soon as I created a new view named "1" it happened the following bug:

When clicking on this new view, it doesn't go to this view but just to the second view of this dashboard (which has an Icon not any name on it).

Same behavior from different browsers and also from mobile application.

### Describe the behavior you expected

When clicking on the name of this view, should go to this view

### Steps to reproduce the issue

1.Create a new view named "1" (without quotation marks)
2.Click on it
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.6.2

### In which browser are you experiencing the issue with?

Chrome, Edge

### Which operating system are you using to run this browser?

Windows 11

**Comment by bramkragten** [comment]
I assume you are talking about views, and not cards?

**Comment by spacegaier** [comment]
I can confirm the issue. Your new view "owns" the URL `/lovelace/1`, but there seems to be some frontend logic that then interprets that as showing view with index 1 which means the second defined view. I will see if I can quickly spot that.

**Comment by antstyl** [comment]
Also the problem with this is that as I cannot go to this view I also cannot delete it.

**Comment by antstyl** [comment]
Problem remains in:
Core 2024.10.0
Supervisor 2024.09.1
Operating System 13.1
Frontend 20241002.2
