### ISSUE TITLE
Binary sensor status spelling and consistency issue

### ISSUE THREAD

**Issue by squirtbrnr** [home-assistant/frontend#17081]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I've noticed on binary sensors when they clear to the off state, they say "Cleared (no detected)".  I've noticed this on my motion, occupancy, and even a zwave door lock jammed status.  This appears to be a misspelling and the "no" should be "not".  Furthermore, on the lock jammed status, the history and the logbook are not consistent with each other.  The logbook says "Detected" while the history and the state of the entity on the frontend says "Problem" and when the logbook says "Cleared (no detected)" the history says "OK". Another similar inconsistency is on the motion and occupancy sensors where the logbook says "Cleared (no detected)" while the history says "Clear", but they match when it says "Detected".
![image](https://github.com/home-assistant/frontend/assets/35356217/58d16611-bc47-4503-b0cf-2f868a022921)
![image](https://github.com/home-assistant/frontend/assets/35356217/973b3ddc-5f6a-4dcf-a69b-80229b9bd526)
![image](https://github.com/home-assistant/frontend/assets/35356217/571ca9fd-f4e9-414e-a613-dc7f9a3d6ea2)

### Describe the behavior you expected

the cleared status should either say "Cleared (not detected)" or just "Cleared" to be consistent with the single word "Detected".  Additionally, the history and logbook states should be consistent with each other

### Steps to reproduce the issue

1. find a binary sesnor
2. open the entity card to view history and logbook

### What version of Home Assistant Core has the issue?

2023.6.3

**Comment by spacegaier** [comment]
I fixed that a few days ago. Will be in the upcoming beta and release: https://github.com/home-assistant/frontend/pull/17034
