### ISSUE TITLE
Utiliy Meter Integration page is only accessible via "Related"

### ISSUE THREAD

**Issue by pimw1** [home-assistant/frontend#17095]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Utility Meter Integration is accessible via "Related", but is not displayed when going directly to "Integrations". This is not consistent: imho, it should either be accessible via both methods, or not be accessible at all.

Access via "Related":
![image](https://github.com/home-assistant/frontend/assets/74881023/00bbdbe6-e86b-44fd-8fe4-a866bd68acc1)
![image](https://github.com/home-assistant/frontend/assets/74881023/e9324bee-9e25-4c24-92ac-f98dda7e6383)
![image](https://github.com/home-assistant/frontend/assets/74881023/b543cb36-1ae7-4d5e-9135-4cdade004842)

No access via Integrations page (it's neither visible under show disabled / show ignored filter):
![image](https://github.com/home-assistant/frontend/assets/74881023/01ba7240-0d4f-40a5-a435-5721ed8d4855)
 

### Describe the behavior you expected

It should either be accessible via both methods, or not be accessible at all.

### Steps to reproduce the issue

1. Update to Home Assistant 2023.7.0b0
2. Follow the clicks in the provided printscreens

### What version of Home Assistant Core has the issue?

core-2023.7.0b0

### In which browser are you experiencing the issue with?

Google Chrome 114.0.5735.134

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment]
I observe on 2023.6.3 also, so not a beta issue. Also the same for riemann, group, and min_max.

**Comment by dougiteixeira** [comment]
This is expected behavior, helper integrations are not displayed on the integrations page, but in Settings > Devices & Services > Helpers tab.

I opened a feature request to improve this helpers page, if you want you can vote for it at https://github.com/home-assistant/frontend/discussions/16927.
