### ISSUE TITLE
Assist: greeting language is inconsistent with Assist language

### ISSUE THREAD

**Issue by pimw1** [home-assistant/frontend#17106]
### The problem

Hi,

My Assist is set to Dutch and my user language is set to English. This creates a funny scenario: it starts in English ("how can i assist?") and then switches to Dutch. 

![image](https://github.com/home-assistant/core/assets/74881023/328f54b1-6c8f-4d46-b92b-f52573869d84)
![image](https://github.com/home-assistant/core/assets/74881023/cc41c50d-296a-46e5-8c74-1e5864932041)
![image](https://github.com/home-assistant/core/assets/74881023/803b5344-5525-48b1-8364-17eb67ea0b73)

Expected behaviour: the greeting sentence should match the language as set in the Assist.

I'm currently on core-2023.7.0b0, but i think this problem is not related to the beta. That's why i mapped it to core-2023.6.3.

### What version of Home Assistant Core has the issue?

core-2023.6.3

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Assist

### Link to integration documentation on our website

https://www.home-assistant.io/voice_control/

**Comment by balloob** [comment]
The sentence is based on your current UI language, not on the pipeline.

**Comment by pimw1** [comment]
Indeed. That behaviour is weird in the context of the Assist.
