### ISSUE TITLE
Automation 'current' attribute state automatically set to string, not integer

### ISSUE THREAD

**Issue by vocalplatypus** [home-assistant/frontend#17101]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When selecting the attribute 'Running Automations (current)' for an automation, the state type populates as a string, rather than an integer. For this specific attribute, the values are meant to be 0 or 1. If these are written as a string, the condition will never pass if used in an automation. The only way to correctly populate the state, is to edit it as YAML, rather than the frontend.

### Describe the behavior you expected

When setting a condition, and populating the State for the attribute 'Running Automations (current)' for an automation (eg. automation.motion_on), if using the frontend to write the condition, the State populates as a string, but for this attribute, it needs to be an integer. This can be fixed in the YAML file, but automatically populates as a string every time if using the frontend.

### Steps to reproduce the issue

1. Select an automation (eg. automation.motion_on)
2. Add a condition
3. Select type 'State'
4. For the Entity, select an automation (eg. automation.motion_off)
5. Select 'Running Automations' as the attribute.
6. Type 0 as the State.
7. Click 'Test' on the three dots in the top right corner of the condition.
8. If automation.motion_off is not running, the state should be 0, and the condition should pass. However, the condition does not pass if the above steps are followed.
9. Click 'Edit in YAML' on the three dots in the top right corner of the condition. Note that the state of the attribute is shown as a string.
10. Convert the 0 from a string to an integer.
11. Click 'Test' again.
12. If the automation.motion_off is not running, the condition should now pass.
...

### What version of Home Assistant Core has the issue?

2023.6.3

### In which browser are you experiencing the issue with?

Google Chrome 114.0.5735.134

### Which operating system are you using to run this browser?

Windows 11 v22H2

**Comment by karwosts** [comment]
Related: #16807
