### ISSUE TITLE
ha-service-control displays unsupported values in selector

### ISSUE THREAD

**Issue by gbleaney** [home-assistant/frontend#17122]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This issue manifested as the bug described [here](https://github.com/RobertD502/home-assistant-flair/pull/59), where I set up a script to call the `climate` service to set the `mode` to `off`. The UI picker displayed an `off` mode option and allowed me to do it, but in reality the flair integration I'm using [correctly advertises supported HVAC modes](https://github.com/RobertD502/home-assistant-flair/blob/efd18de96e514c4f62950587448d6ab44a70e643/custom_components/flair/climate.py#L586-L613). This resulted in me setting up a script that called an unsupported mode in the background.

### Describe the behavior you expected

I believe `ha-service-control` should only be displaying values that are actually supported by the devices that are being configured. I _think_ this information is already available in the front end via `capabilities in `ExtEntityRegistyEntry` and that it's just a matter of filtering:
https://github.com/home-assistant/frontend/blob/ff59e31530f45af2a6557e821fbf20088a71dafa/src/data/entity_registry.ts#L58-L64

I understand that this is borderline between a bug and a feature request, and I'm happy to do the work myself to address this, but I wanted to get buy in from the repo maintainers before I put in the effort to put up a PR.

### Steps to reproduce the issue

1. Set up an HVAC integration such as [home-assistant-flair](https://github.com/RobertD502/home-assistant-flair/tree/main)
2. Configure an HVAC system that supports only a subset of the [standard climate HVAC modes](https://github.com/home-assistant/core/blob/522d2496dff09a01f0309de0856609cb09667890/homeassistant/components/climate/services.yaml#L154-L167)
3. Create a script and edit through the UI at `/config/script/edit/SCRIPT_NAME`
4. Call the `climate.set_hvac_mode` service, and configure it for your device. Notice that the HVAC mode drop down shows unsupported modes

### What version of Home Assistant Core has the issue?

2023.6.3

**Comment by karwosts** [comment]
This kind of makes sense to me, but I think it feels like more than just a frontend change to do it correctly. 

You'll notice that the service control is not full of hardcoded behaviors for specific services, but rather all the information about how the controls are to be presented comes from the backend, based on the services.yaml of the integration providing the service. 

We have a something that feels similar for some services like `light.turn_on` where we don't show certain fields that are not supported by the light entity being targeted. That's not hardcoded in the frontend though for each service, you'll see that in the services.yaml for light.turn_on the yaml specificies which supportedFeatures flags or attributes are required for the target light to support to show that field. 

Unfortunately there's no existing syntax for applying a similar filtering to *individual items* in a select list. Maybe something like that could be added in the backend to the individual services, then we could use it to filter in the frontend.
