### ISSUE TITLE
"Return to grid" cost(compensation) is lost for the time HA is not running

### ISSUE THREAD

**Issue by Gitsarry** [home-assistant/frontend#17132]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When HA is not running (HA computer shutdown), in this example between 07:00 (7 am) and 19:00 (7 pm), and in this time produced energy (kWh) is returned to the grid, the energy counter for the "return to grid" is correct when starting HA again, but the "return to grid" energy cost (negative value, =compensation) is not counted for the time HA was shutdown, it is permanently lost.
E.g. here a screen shot of a day where I had supplied 2.49 kWh to the grid while HA was not running. I have a constant "return to grid" compensation of 0.082 €/kWh.
Dashboard says the money compensation for that would be -€0.00 while correctly it would be -2.49 * 0.082 = -0.20 €
![screenshot2](https://github.com/home-assistant/frontend/assets/131813959/6a05fbb4-1f29-4d83-adb1-9fa8691549c9)
The loss of the compensation value is permanent, meaning it persists in the later week/month/year statistics and cumulates for every time HA is not running while you return energy to grid.
See also this bug report with some more screenshots
https://community.home-assistant.io/t/bug-in-energy-dashboard-kwh-supply-compensation-0-00-when-ha-was-shutdown-some-hours-of-day/586947

### Describe the behavior you expected

The "return to grid" cost should be the product of the "return to grid" energy value multiplied with the "return to grid" compensation value for the time HA was not running.
Calculation is correct when HA is running.
Here an example of another day where it is correct -0.6 * 0.082 = -0.05
![screenshot2](https://github.com/home-assistant/frontend/assets/131813959/04121655-eb4a-419f-8556-27141d4d74cc)

### Steps to reproduce the issue

1. Produce electric energy [kWh] and return it to the grid
2. While producing and returning to grid, shut down HA
3. After some hours producing and returning to grid while HA was shutdown, start HA again

### What version of Home Assistant Core has the issue?

2023.6.3

### In which browser are you experiencing the issue with?

Google Chromium Version 114.0.5735.133

### Which operating system are you using to run this browser?

Debian GNU/Linux 11 (bullseye)

**Comment by karwosts** [comment]
The cost is not computed by the frontend. Cost comes from a monetary-class sensor created by the `energy` integration. 

It is not simply displayed as a multiplication of consumption times the price, but rather every time the sensor changes, the cost sensor is updated also. 

Therefore if that cost sensor has the wrong value, it needs to be filed as a home-assistant/core issue, not on the frontend.

**Comment by karwosts** [comment]
This may be the same issue an issue I personally myself filed, but I am not certain if it is the same. You might checkout if your cost sensor becomes "unavailable" after reboot HA, similar to my reported issue. 

#95922

**Comment by Gitsarry** [comment]
Just to mention when you select "Report a bug with Dashboards" on https://github.com/home-assistant/core/issues/new/choose you are redirected to https://github.com/home-assistant/frontend/issues . This bug manifests in the energy dashboard, so a simple user like me has no real reason to select something other than selecting "Report a bug with Dashboards".

**Comment by karwosts** [comment]
No worries, just wanted to help direct you to the place where you can hopefully get your issue fixed. Hope you find a resolution 👍
