### ISSUE TITLE
Color Temperature Selector uses Mireds when Core uses Kelvin

### ISSUE THREAD

**Issue by HarvsG** [home-assistant/frontend#17144]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing
See related core issue: https://github.com/home-assistant/core/issues/95762

https://github.com/home-assistant/core/pull/79591 Transitioned to using Kelvin instead of Mireds.
However the UI Color Temp selector uses Mireds still: https://www.home-assistant.io/docs/blueprint/selectors/#color-temperature-selector
The color temperature (Kelvin) renders but only as a number slider.
![image](https://github.com/home-assistant/frontend/assets/11440490/e9ff8a41-8183-4abd-869a-0386a772fbdb)

### Describe the behavior you expected

For Kelvin selection to use color temperature slider (with color gradient inverted) and not the number slider
![image](https://user-images.githubusercontent.com/11440490/203624102-846fe0e4-3304-4006-a774-d1f359b96875.png)

### Steps to reproduce the issue

1. Developer Tools
2. Service
3. Light: Turn On

### What version of Home Assistant Core has the issue?

2022.11.4 - 2023.6.3

### What was the last working version of Home Assistant Core?

 2022.10

### In which browser are you experiencing the issue with?

Chrome and Edge

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
Related: https://github.com/home-assistant/frontend/pull/14495

**Comment by schelv** [comment]
I don't think the color temperature should be inverted in the slider.
It might be a bit confusing.

Could this be solved by setting the step size to negative when using Kelvin?

**Comment by HarvsG** [comment]
Kevin is irritatingly inherently confusing - a higher temperature results in a cooler colour (and vice versa).
I would argue that it is less confusing to have a switch in the colour gradient (which is a directionless dimension) than it is to have a number that goes down when the slider goes up.

Also having the gradients go in opposite directions gives the user an immediate visual appreciation between the inverse relationship between Mireds and Kelvin.

**Comment by schelv** [comment]
> I would argue that it is less confusing to have a switch in the colour gradient (which is a directionless dimension) than it is to have a number that goes down when the slider goes up (which the user may not notice - and I have never seen before).

I think you're right. It is also a lot more practical to implement.
And on second thought, it could only be confusing if both Mireds and Kelvin are used at the same time.
And who would want to do that? (except the developer tools)

**Comment by HarvsG** [comment]
Fixed in #18627
