### ISSUE TITLE
Unable to change the size of zones

### ISSUE THREAD

**Issue by Skeletorjus** [home-assistant/frontend#17152]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I can't change the size of a zone by manipulating the "dot" at the edge of the circle.
The log says
`2023-07-03 23:12:07.130 ERROR (MainThread) [frontend.js.latest.202306300] https://xxxxxxxxxxx.ui.nabu.casa/frontend_latest/27716-nSckuYcUP6E.js:1:38551 ReferenceError: assignment to undeclared variable radius`

### Describe the behavior you expected

To be able to change the size

### Steps to reproduce the issue

1. Edit or create a new zone
2. Try to change the size of the zone

### What version of Home Assistant Core has the issue?

2023.7.0b4

### What was the last working version of Home Assistant Core?

2023.6.x

### In which browser are you experiencing the issue with?

Companion app beta-10230-b7c6be45-full, Chrome (Android), Firefox (Android)

### Which operating system are you using to run this browser?

Android 13

**Comment by karwosts** [comment]
+1

```
leaflet.draw.js:9 Uncaught ReferenceError: radius is not defined
    at NewClass._resize (leaflet.draw.js:9:6541)
    at NewClass._onMarkerDrag (leaflet.draw.js:9:2482)
    at NewClass.fire (Events.js:195:1)
    at NewClass._onDrag (Marker.Drag.js:143:1)
    at NewClass.fire (Events.js:195:1)
    at NewClass._updatePosition (Draggable.js:181:1)
    at NewClass._onMove (Draggable.js:167:1)
    at HTMLDocument.handler (DomEvent.js:108:1)
 ```

**Comment by silamon** [comment]
Bisecting brings me to #16849, although I'm not entirely sure. Had to rebuild from scratch several times to find a source.
