### ISSUE TITLE
When adding new cards - Uncaught TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by chertvl** [home-assistant/frontend#17172]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Every time when I press "Add cards" button in my lovelace page, I get 2 same logs errors:
```
Logger: frontend.js.latest.202306080
Source: components/system_log/__init__.py:257
First occurred: 19:41:27 (6 occurrences)
Last logged: 19:46:07

http://homeassistant:8123/frontend_latest/28922-mjI0iZwe1jc.js:2:14655 Uncaught TypeError: Cannot read properties of undefined (reading 'map')
```

In chrome browsed console errors looks like:
```
coordinates.ts:122 Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at a (coordinates.ts:122:63)
    at hui-graph-header-footer.ts:160:11
    at Object.callback (history.ts:254:18)
    at connection.js:23:34
    at Array.forEach (<anonymous>)
    at WebSocket._handleMessage (connection.js:15:26)
```

All seems to work ok, but that error is annoying

### Describe the behavior you expected

Fix that annoying error for always-clean HA log ;)

### Steps to reproduce the issue

1. Go to any lovelace page in edit-mode
2. Press "Add cards"
3. Check HA logs

### What version of Home Assistant Core has the issue?

2023.6.4

### What was the last working version of Home Assistant Core?

I dont know, I've been seeing this for half a year

### In which browser are you experiencing the issue with?

Any browser / HA client

**Comment by karwosts** [comment]
Assuming you don't have any custom cards installed (please clarify if you do), this seems likely to come from the "Sensor" card. That's the only card in my preview that renders the graph header-footer. 

In your add card dialog, if you look for the sensor card, what does it look like? Does it render correctly? If so, what entity is it showing?

**Comment by chertvl** [comment]
> Assuming you don't have any custom cards installed (please clarify if you do), this seems likely to come from the "Sensor" card. That's the only card in my preview that renders the graph header-footer.
> 
> In your add card dialog, if you look for the sensor card, what does it look like? Does it render correctly? If so, what entity is it showing?

![image](https://github.com/home-assistant/frontend/assets/38353584/306ec8e0-29a5-4f84-8314-1aa39e3b77ae)

Looks like it render correctly, but it shows entity ```sensor.memory_use``` from systemmonitor, **that entity excluded from recorder.**

**Comment by karwosts** [comment]
Yeah the card preview is not that smart. It just looks through all entities and returns the first one that has a non-NaN state and a unit_of_measurement. It doesn't know at this point that it doesn't have a recorder. 

The fix is probably to make sensor card behave better when it doesn't find a history for an entity.

**Comment by karwosts** [comment]
fix filed
