### ISSUE TITLE
2023.7 image entity does not work with /config/www/images/...

### ISSUE THREAD

**Issue by m-klecka** [home-assistant/frontend#17177]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using the new image template i cant use local image because /config/www/images /local/images/... does not work. Only external url pointing to website with image

### Describe the behavior you expected

For it to work:)

### Steps to reproduce the issue

1. setup new image template
2. `- image:
    url: /local/images/wifi.png
    name: "guestwifi"`

### What version of Home Assistant Core has the issue?

Home Assistant 2023.7.0

### In which browser are you experiencing the issue with?

Firefox 115.0

### Which operating system are you using to run this browser?

Windows 11

**Comment by bramkragten** [comment]
This is by design.
You should use an url, not a local path. Also this is not for the frontend repo, but the core repo, specifically the template integration.
