### ISSUE TITLE
"Duplicate card" and "Copy card" use the same phrase in Chinese

### ISSUE THREAD

**Issue by bbayu123** [home-assistant/frontend#17179]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Chinese translation for "Duplicate card" and "Copy card" in lovelace both use "複製面板" in Chinese (Traditional) and "复制卡片" in Chinese (Simplified).
While the translation is not wrong in itself, it causes confusion.

### Describe the behavior you expected

The two options should be distinguishable no matter the language used.

### Steps to reproduce the issue

1. Switch the UI language to Chinese (whether it's simplified or traditional doesn't matter)
2. Open the  ⋮  menu of any lovelace card

### What version of Home Assistant Core has the issue?

core-2023.7.0

### Additional information

![image](https://github.com/home-assistant/frontend/assets/26726381/b3b7dcb8-945d-4d14-b885-9c70ff64fbb1)

Normally, I would suggest an alternative translation, but as far as I know, I don't think there's a proper distinction in Chinese between "duplicate" and "copy" in everyday life. As such, I don't have a suggestion on how to resolve this issue.

[A certain blog post by Cheng-Chia Tseng](http://breezymove.blogspot.com/2023/04/copy-duplicate-clone.html) uses the phrase "複製" for copy and "再製" for duplicate. However, I can't say "再製" is a commonly used phrase at all, at least in Hong Kong. To me, "再製" has the meaning of "remake": 再 - again, and 製 - make, so I can't suggest this translation.

**Comment by karwosts** [comment]
Specific translations are generally not tracked in Github, but rather you would go on Lokalize and submit a suggestion there:

https://developers.home-assistant.io/docs/translations/
