### ISSUE TITLE
Weird language selection

### ISSUE THREAD

**Issue by KyangTan** [home-assistant/frontend#17189]
### The problem

I have found a vague language able to be selected in Profile -> Language -> Test.

All of the text will become unreadable and basically not legible. 

I think this language should be hidden from normal users.

### What version of Home Assistant Core has the issue?

core-2023.4.6

### What type of installation are you running?

Home Assistant OS

**Comment by spacegaier** [comment]
@bramkragten @steverep We seem to be shipping the "Test" language in production accidentally. I have not enough knowledge about the build/gulp process, but I think you do. I spotted a gulp task "create-test-metadata" that seems to be related.

**Comment by steverep** [comment]
It's a simple syntax mistake.  See linked PR.
