### ISSUE TITLE
Translation Error:   The intl string context variable "string" was not provided to the string "per {string}"

### ISSUE THREAD

**Issue by rednet1** [home-assistant/frontend#17183]
### The problem

( lang ITA ) When select Automation -> new action -> add time delay -> Ritardo Translation Error: The intl string context variable "string" was not provided to the string "per {string}"

Home Assistant 2023.7.0
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.0 - latest

### What version of Home Assistant Core has the issue?

2023.7

### What type of installation are you running?

Home Assistant Core

### Integration causing the issue

Automation

**Comment by bramkragten** [comment]
Was fixed in https://github.com/home-assistant/frontend/pull/17166
