### ISSUE TITLE
Backups not working - Cannot create / restore

### ISSUE THREAD

**Issue by flavioteuy** [home-assistant/frontend#17180]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When trying to generate a new backup, or to upload a existent to a new fresh instance, i get this message (tried with Chrome and Edge):

_Client error on api app/frontend_latest/8984-vQSGf91zIDY.js request 400, message='Can not decode content-encoding: gzip'_

The file is generated as a .tar in the /backup directory but seems cannot be read.

### Describe the behavior you expected

Backups working

### Steps to reproduce the issue

Go to Settings, System, Backups, Create Backup

### What version of Home Assistant Core has the issue?

2023.7.0

### What was the last working version of Home Assistant Core?

2023.6.2

### In which browser are you experiencing the issue with?

Chrome 114.0.5735.199 

### Which operating system are you using to run this browser?

Windows 11

**Comment by spacegaier** [comment]
Taking a full backup in Chrome 114 right now worked fine for me.
BTW: Inside the main TAR backup archive there are multiple sub archives that are GZIP compressed.
