### ISSUE TITLE
Lovelace broken with Firefox 115

### ISSUE THREAD

**Issue by jaromanda** [home-assistant/frontend#17182]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

With the recent release of Firefox version 115.0, lovelace dashboards often display incorrectly.

Refreshing the page sometimes fixes it.

Resizing the browser window to about 50% of current width then back always fixes the issue.

This is an example of the issue - it only affects lovelace pages, the rest of Home Assistant displays without issue

![ui-bad](https://github.com/home-assistant/frontend/assets/7315383/0648970f-8234-481d-9a51-e1800b39310b)

### Describe the behavior you expected

I expect a readable UI

![ui-good](https://github.com/home-assistant/frontend/assets/7315383/4b31cd52-e498-4ebd-8a06-ef58cb7be850)

### Steps to reproduce the issue

1. Open home assistant in Firefox 115.0

### What version of Home Assistant Core has the issue?

Home Assistant 2023.7.0

### What was the last working version of Home Assistant Core?

Home Assistant 2023.5.0

### In which browser are you experiencing the issue with?

Firefox 115.0 (64-bit)

### Which operating system are you using to run this browser?

Microsoft Windows 11 22H2 (OS Build 22621.1928)

### Javascript errors shown in your browser console/inspector

None

### Additional information

Firefox 114.0 and earlier worked without issue

Firefox Dev version 115.0 also produces this issue

Other browsers tested: Chrome and Edge - both work as expected

**Comment by spacegaier** [comment]
I also just updated to 115.0 on Win 10, but cannot spot any issues in my dashboards. In your screenshot there is a custom compass / wind direction card? Do the issues persist if you temporarily remove that?

**Comment by jaromanda** [comment]
> In your screenshot there is a custom compass / wind direction card? Do the issues persist if you temporarily remove that?

I did remove that before writing out this issue and restarted HA, I just forgot to update the screenshots. I noticed that even though I only use that card in one dashboard, that the code seemed to be loading in every dashboard, but it's safe to say, I've removed it, there's no evidence of it existing/loading

**Comment by bramkragten** [comment]
Everything looks good here too on 115 on Mac OS, got a specific repo?

**Comment by jaromanda** [comment]
> got a specific repo

Can you be more specific?

**Comment by jaromanda** [comment]
Perhaps some more insite

I use dev version of firefox regularly as part of my job, to preempt any issues with the work website

Last month (June) dev version was 115, and Home Assistant worked fine, until the first June release of - 2023.6.1

The release version of Firefox - 114.0 worked fine, only 115.0 was broken in HA

Now that Firefox 115 is the release version, both 115.0 and 116.0 have the display issue

Note 1: I also found I can "fix" the layout by simply collapsing/expanding the sidebar, so at least I can have a workable page easily

Note 2: there are a LOT of CSS warnings - unfortunately when ever I try to ascertain what the issue is, the page unbreaks! Same if I inspect any element in the dev tools

**Comment by jaromanda** [comment]
Sorry for the time waste - I see I enabled presumably a buggy feature in firefox

`layout.css.has-selector.enabled` was set to `true`

**Comment by aurorasmiles** [comment]
For those of you who are using Firefox and need to have the has-selector enabled, here is the issue on Bugzilla for `:has()` https://bugzilla.mozilla.org/show_bug.cgi?id=418039#c62
I assume it's one of the linked bugs there thats also causing this issue (might be https://bugzilla.mozilla.org/show_bug.cgi?id=1792501)

**Comment by barrelltitor** [comment]
Might be worth reopening this issue to investigate, as I have had this feature enabled in Firefox since the feature was added and it has absolutely never caused any problems until recent HA updates

**Comment by kleest** [comment]
Reverting 3fa3d33 fixes the problem when `layout.css.has-selector.enabled` is set to true. It looks like this commit break it on Firefox due to `:has`.

There is also b337074, but this does not seem to cause issues. The funny thing is that this commit is a fix for #16725 which looks similar to the problem we are facing here. :slightly_smiling_face:

**Comment by barrelltitor** [comment]
@jaromanda could you reopen this so we don't run into problems for opening duplicates? Would be great. This is very much still an issue

**Comment by jaromanda** [comment]
Reopened as requested

**Comment by karwosts** [comment]
Reported as still an active issue in discord on Sep 4.

**Comment by jaromanda** [comment]
Looks to be working correctly in Firefox 119 - i.e. current Developer version

**Comment by jonatino** [comment]
this is still an issue with 119.0 for me.

Current broken:
![image](https://github.com/home-assistant/frontend/assets/1808569/c944cac4-fc8a-4b84-b4fb-d64657ba7b76)


Expected:
![image](https://github.com/home-assistant/frontend/assets/1808569/28442f44-5436-46f6-bfee-86ea2bfd6526)
