### ISSUE TITLE
wrong information in total grid gauge

### ISSUE THREAD

**Issue by TobiasSchwarz74** [home-assistant/frontend#17188]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The gauge "total grid is wrong i think.
It alwys display the energy consumed from grid minus the feed in energy.
This is wrong, because you have to pay more for consumed energy and get payed less for feed in energy.

Let me give you an example:
When i consumed 5kWh from the grid and feed in 1kWh, the gauge will show 4kWh
But in the end you have to pay 5kWh. You earn money for the 1kWh feed in energy, but the price is less than the proce you pay for consumed energy.

### Describe the behavior you expected

I would like to see the real consumed energy as number.
The gauge should be devided into real consumed and feed in energy.

### Steps to reproduce the issue

add grid and solar information to energy board

### What version of Home Assistant Core has the issue?

2013.7.0

### What was the last working version of Home Assistant Core?

did never work as expected

### In which browser are you experiencing the issue with?

everywhere

### Which operating system are you using to run this browser?

win, android

**Comment by karwosts** [comment]
Can you add a screenshot and highlight specifically what you think is wrong? I don't know if I quite understand which component you're referring to. The energy dashboard sources table?

**Comment by TobiasSchwarz74** [comment]
![image](https://github.com/home-assistant/frontend/assets/66618167/7b108bdb-e743-474d-b148-4b86932528b2)
Consumed is not correct - i consumed 1,7kWh. Subtracting the 0,2kWh feed in energy is not correct.

![image](https://github.com/home-assistant/frontend/assets/66618167/58af47c2-a35e-4ea8-9fda-98547e602929)
Also the sum "grid total" (Netz gesamt) is not correct. A sum is not meaningful for grid consumption and feed in.

**Comment by karwosts** [comment]
I suspect that the label may be a slight mistranslation in your language. In english this gauge card is very explicitly "net" consumption. The tooltip says:

> This card indicates your net energy usage.
> If the needle is in the purple, you returned more energy to the grid than you consumed from it. If it's in the blue, you consumed more energy from the grid than you returned.

It is intentionally subtracting power outflow from power inflow.

**Comment by TobiasSchwarz74** [comment]
still not happy with this indicator!
the shown amount of energy is useless. at least in austria, i get only about half the price for outgoing energy compared to incoming energy.
