### ISSUE TITLE
Incorrect values for Battery Charge Energy in the Energy Dashboard

### ISSUE THREAD

**Issue by blue-bean** [home-assistant/frontend#17187]
### The problem

Sometimes in the Energy dashboard the value for Battery Charge Energy is wrong.
Today the Battery Charge shows in the time slot 05:00 - 06:00 AM a value of more than 4 kWh (see attached screenshot), that's impossible. See also the attached chart of the manufacturer chart today (it shows a value of 0.01 kWh from 00:00 - 08:06 AM).
Yesterday the energy chart was ok (see attached screenshot 1.6.2023).

Incorrect dashboard 2.6.2023:
![2 6 2023](https://github.com/home-assistant/core/assets/5843358/2b170d56-3184-452c-8f5c-66d6ec4cb22c)

Reference of the PV System 2.6.2023:
![Reference_E3DC](https://github.com/home-assistant/core/assets/5843358/b543aae4-33e2-410c-b546-42c15d48bf46)

Correct dashboard 1.6.2023:
![1 6 2023](https://github.com/home-assistant/core/assets/5843358/5ec03be6-7f5f-4fd7-96b3-28028a31fb67)

### What version of Home Assistant Core has the issue?

core-2023.5.2

### What was the last working version of Home Assistant Core?

core-2023.5.2

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

Energy dashboard

### Link to integration documentation on our website

https://www.home-assistant.io/dashboards/energy/

### Diagnostics information

-

### Example YAML snippet

```yaml
-
```

### Anything in the logs that might be useful for us?

```txt
no
```

### Additional information

-

**Comment by karwosts** [comment]
@spacegaier - I'm not so sure this is a frontend issue. I've been seeing this a lot in the energy chat lately, where people are getting random huge negative spikes in energy usage, (and it's happened to me as well).

When I dig into it it seems to be a statistics issue, where the "sum" statistic for a sensor that is supposed to be total_increasing seems to mysteriously reset to 0, and I don't think that's supposed to happen. I think it's something to do with the sensor being unavailable or maybe the first update after a long period of dormancy and all the previous history values are purged from the recorder. Not sure.
