### ISSUE TITLE
Can't set response_variable via UI

### ISSUE THREAD

**Issue by N1c093** [home-assistant/frontend#17186]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Currently it's not possible to set the `response_variable` via the Userinterface.
For example, you try to create an automation/script with the service `calendar.list_events` you can't set the `response_variable`. 

You simple can't input some text inside the input box. See example below:

![image](https://github.com/home-assistant/frontend/assets/59510296/a5b7a794-ee1d-4e25-aae0-1a42e9c09a2f)

### Describe the behavior you expected

The user should be able to input some text in the input box 

### Steps to reproduce the issue

1. Create automation/skript with service `calendar.list_events`
2. Try to input some text in input box "Response variable"

### What version of Home Assistant Core has the issue?

2023.7.0

**Comment by bramkragten** [comment]
This is fixed in https://github.com/home-assistant/frontend/pull/17171
