### ISSUE TITLE
Incorrent units displayed for energy dashboard

### ISSUE THREAD

**Issue by digdilem** [home-assistant/frontend#17185]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Changing the range in this dashboard (Top right: Day | Week | Month | Year) correctly changes the units below the graphs to reflect the chosen period, but every single value is shown as "Units used Today" regardless of whether the range is day, week, month. 

Example - my dashboard with the range set at "Day"

![image](https://github.com/home-assistant/frontend/assets/4052275/d8bfc895-250b-4e9a-ae2d-036ef22d9705)

The same tab, but with the range set at "Week"

![image](https://github.com/home-assistant/frontend/assets/4052275/fa8ad989-800f-48f3-ae5d-38a8cd2ffaee)

Note that the values have changed, but it is misleading and confusing to describe the usage as "Today" when it's not.

Last example - same tab, with range set at "Month"

![image](https://github.com/home-assistant/frontend/assets/4052275/3c400a29-2114-4538-9570-d53ee7803c74)

### Describe the behavior you expected

For the "Today" string to be replaced by the period chosen. Day, Week, Month, Year or Custom.  (Or, simpler and equally as valid; "for the period selected")

### Steps to reproduce the issue

1. Open sidebar link for energy dashboard: https://{server}/energy
2. Note units "Today" for default 'Day' period. 
3. Change period at top-right and see the units have changed, but they are still marked as 'Today'
...

### What version of Home Assistant Core has the issue?

2023.7.0

### In which browser are you experiencing the issue with?

Latest Chrome and latest Firefox

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
>  every single value is shown as "Units used Today"

That's because that's the name of the sensor you've added to the dashboard configuration. The energy dashboard does not add "Today" (or any other string) to the end of the name.

**Comment by digdilem** [comment]
Thanks for explaining that - I see it's not a core issue now. 

In case anyone else encounters this - "Today" is actually being generated by the Solar generating plugin I use, GivEnergy. I'll drop the developer a polite note.

**Comment by karwosts** [comment]
Its a bit tricky how this works, because "Today" might be a reasonable name for the sensor in a non-energy-dashboard context, if it resets to 0 every night. But it doesn't make sense once energy dashboard turns that sensor into a long term reading.
