### ISSUE TITLE
Dashboard Copy Paste Position

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#17192]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

https://github.com/home-assistant/frontend/discussions/17191

### Describe the behavior you expected

*

### Steps to reproduce the issue

*

### What version of Home Assistant Core has the issue?

*

**Comment by karwosts** [comment]
For a new feature request, the discussion is sufficient, doesn't need to be a duplicate issue as well.
