### ISSUE TITLE
Cut Card Delete Card??

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#17193]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Why Cards have Cut and Delete?, or something else makes the Cut?

### Describe the behavior you expected

*

### Steps to reproduce the issue

*

### What version of Home Assistant Core has the issue?

*

**Comment by karwosts** [comment]
Cut adds a copy of the card to the session clipboard, and removes the card. 

Delete simply removes the card. 

If you want to know more about the cut and paste feature, you can read the release notes for 2023.7 or watch the demo from the release party. 

https://youtu.be/r0DLyU-4nWo?t=3903
