### ISSUE TITLE
Ios Homeassistant app freezes after update to HA 2023.7.1

### ISSUE THREAD

**Issue by Kratax** [home-assistant/frontend#17206]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After updating to the latest HA version, app starts to be not responding when using power-flow-card-plus cards... was working well with the previous version (i.e. prior 2023.7.0).

### Describe the behavior you expected

No freezing

### Steps to reproduce the issue

1. Open HA ios app with card using power-flow-card-plus
2. Wait / scroll down
3. The page freezes... nothing like that happens on safari when opening the same page
...

### What version of Home Assistant Core has the issue?

2023.7.1

### What was the last working version of Home Assistant Core?

2023.6.3

### In which browser are you experiencing the issue with?

ios HA app

### Which operating system are you using to run this browser?

ios HA app on iphone

**Comment by Kratax** [comment]
https://github.com/home-assistant/frontend/assets/25452697/2d050ec9-3280-447a-8516-9a7be80019cd

**Comment by peterhoe** [comment]
@kratax - would you by any chance happen to have a history graph on that page with more than 8 entities?

https://github.com/home-assistant/frontend/issues/17203

**Comment by iz8mbw** [comment]
Hello. Since July 2023 version also on Android the interface freeze when I would like to see an entity chart.

**Comment by Kratax** [comment]
No, not such extensive but yes, several history charts are there...

**Comment by themex85** [comment]
I have the same issue. I think it is also think it is caused by the Power Card Plus HACS integration. 

Home Assistant 2023.7.1
Power Flow Card Plus v0.1.6.1
iOS 16.5.1
Home Assistant Companion App 2023.4
Safari Browser

**Comment by Kratax** [comment]
Just to add, it behaves strangely - it is normally working in the morning and freezing somewhere later in day...

**Comment by Kratax** [comment]
So I found for me the part causing the issue, it is history chart used in horizontal stack... 
Specifically this one is causing the freeze in ios app. After romoving works well... Because it is standard load cpu chart, it can be reproduced easily...

type: horizontal-stack
cards:
  - hours_to_show: 24
    graph: line
    type: sensor
    entity: sensor.processor_use
    detail: 2
    icon: mdi:speedometer
  - hours_to_show: 24
    graph: line
    type: sensor
    entity: sensor.processor_temperature
    detail: 2
  - type: history-graph
    entities:
      - entity: sensor.load_5m
      - entity: sensor.load_1m
    hours_to_show: 4
    refresh_interval: 20

**Comment by themex85** [comment]
I deactivated Power Flow Card Plus and also having freezes so it is also related to horizontal Stack cards?

<img width="1035" alt="Bildschirmfoto 2023-07-11 um 13 37 29" src="https://github.com/home-assistant/frontend/assets/139009805/bc7781eb-9c6d-4ddc-a250-2d2434913950">
