### ISSUE TITLE
Translation missing for HVAC Fan modes

### ISSUE THREAD

**Issue by Flappiee** [home-assistant/frontend#17200]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I recreated this issue. See also issue  #17175 which has been closed.
However, i think it is closed incorrectly.

@piitaya says this fan mode "quiet" is not supported by Home Assistant and is something that comes from ESPHome.
However, i found this change in the Home Assistant Core that added support for the quiet fan mode:
https://github.com/home-assistant/core/commit/d14000f7049f955a08b9c164798f5f78335e54b6

So there is a "quiet" fan mode in Home Assistant.
Still don't know if i'm posting this in the right repository.

Can someone from development take a look at this again and maybe this issue can me moved to the right repo.

### Describe the behavior you expected

Fan mode "quiet" should be translated.

### Steps to reproduce the issue

1. Add a device that supports "quiet" fan mode
2. Try to controle the fan mode. Set language to "dutch"
3. You will see fanmode "quiet" is not translated.
...

### What version of Home Assistant Core has the issue?

2023.7.0

**Comment by piitaya** [comment]
As I said in the previous PR, these translations are not managed by frontend but by backend. If esphome supports this mode, the esphome integration should provide the translation : https://developers.home-assistant.io/docs/internationalization/core#entity-state-attributes.

**Comment by frenck** [comment]
That is correct, this is not a frontend issue. The ESPHome integration can provide an translation for this case. That said, fan modes are not standardized in Home Assistant and free to provide.

Closing the issue on this end, as there is nowhere this can go from here.

../Frenck
