### ISSUE TITLE
Missing translations in IP details dialog

### ISSUE THREAD

**Issue by frenck** [home-assistant/frontend#17212]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Extracted from: https://github.com/home-assistant/core/issues/94345

![image](https://github.com/home-assistant/frontend/assets/195327/5a9c5941-3c33-4752-8a6c-63079658db78)

Ref: https://github.com/home-assistant/frontend/blob/3191801fa7c4bb5487dd08346f94bb304a9b669b/src/panels/config/network/dialog-ip-detail.ts#L44-L75

### Describe the behavior you expected

Those to be translateable.

### Steps to reproduce the issue

1. Open the network ip details dialogs

### What version of Home Assistant Core has the issue?

core-2023.8.0dev0

**Comment by dougiteixeira** [comment]
There are more items related to this without translation, more details in #13464.
