### ISSUE TITLE
Automation: Search for a device

### ISSUE THREAD

**Issue by vbueschken** [home-assistant/frontend#17248]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I search for a device (Search for 'friendly name') to use it as a trigger for an automation I didn't find it even though it is in the Picklist of all devices.

This happens with some devices (no matter what type of integration), not with all

### Describe the behavior you expected

Find the device by entering the first letters of the name

### Steps to reproduce the issue

1. Start to create a new automation
2. Select devices as a trigger
3. search for device by entering the name (friendly name)
4.
...

### What version of Home Assistant Core has the issue?

2023.7.1

### What was the last working version of Home Assistant Core?

2023.6

### In which browser are you experiencing the issue with?

Google CHrome Version 114.0.5735.199 / and other e.g.firefox

### Which operating system are you using to run this browser?

Win 10

**Comment by spacegaier** [comment]
Can you please provide some more details, so we have a chance to reproduce the issue. Anything special about that friendly device name (special characters or the likes)? Is it always the same device that does not work or different ones each time? You specifically mention the "first letter of the name" => does this mean if you type a second letter it then appears for you?

**Comment by Thorsten1982** [comment]
Hello I have the Same Problem. for me it seems to occur only with the ZHA devices.  No particular name, and it occurs on all ZGA devices.  Arbeitsplatte, Bodenlampe, Tischlampe etc. 

Even if I type the second or third letter it is not found

**Comment by vbueschken** [comment]
> Can you please provide some more details, so we have a chance to reproduce the issue. Anything special about that friendly device name (special characters or the likes)? Is it always the same device that does not work or different ones each time? You specifically mention the "first letter of the name" => does this mean if you type a second letter it then appears for you?

For the device name I dont use any special characters or special characters.
It always the same device(es) that does not work.
Sorry, its not only 1 letter I type the first x letters to clearly identify the device.
You can see a sample in the pictures posted above from Thorsten1982 who has the same issue or here:

![bug](https://github.com/home-assistant/frontend/assets/138365084/baf8fc0f-725a-4673-b631-0796b22dd97a)

**Comment by vbueschken** [comment]
Another sample....
If I search for "Shelly" I get 2 Shelly TRV, but 2 other Shelly TRV are missing ( have all the same name "Shelly [room name]"

The third device in the list (Licht Terrasse) has not the word 'Shelly in its name
![bug](https://github.com/home-assistant/frontend/assets/138365084/1e334a56-4717-4f1c-94cf-271faefd9c0d)

**Comment by vbueschken** [comment]
Another sample....
If I search for "Shelly" I get 2 Shelly TRV, but 2 other Shelly TRV are missing ( have all the same name "Shelly [room name]"

The third device in the list (Licht Terrasse) has not the word 'Shelly in its name

![shelly](https://github.com/home-assistant/frontend/assets/138365084/3eca1f12-946a-4551-9ed3-5cd293e1e470)

**Comment by vbueschken** [comment]
@emontnemery    Could this cause the issue ? 

https://github.com/home-assistant/core/pull/94995

**Comment by jurgen2005** [comment]
Can confirm this behaviour on Home Assistant 2023.7.3.

**Comment by rjmgmt** [comment]
Still the same issue on 2023.7.2. It affects all Z-wave (JS) and Shelly devices in my installation. I just noted the device search field used in editing the usage items on the energy dashboard is also broken.

**Comment by vbueschken** [comment]
@spacegaier - could you also reproduce the issue?

**Comment by vbueschken** [comment]
Still the same issue with 2023.7.3

**Comment by nicksears** [comment]
I have the same issue, documented here (before I knew the issue was that the search was broken, but that I could still scroll through the entire list)

https://community.home-assistant.io/t/devices-not-showing-in-dropdowns/418366/6

**Comment by puddly** [comment]
This is fixed by https://github.com/home-assistant/frontend/pull/17297, which will be in today's 2023.8.0 beta.
