### ISSUE TITLE
Security issues with dashboard desing 

### ISSUE THREAD

**Issue by zeminator** [home-assistant/frontend#17243]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Issue is that normal users who have only restricted dashboards and should not be able to control entities what is not in the theirs dashboards. Nowadays when we have search in dashboards right upper corner, they can search and find all the devices and control them!

### Describe the behavior you expected

normal users should not be able to see entities what is not listed in dashboards what they have. (maybe the search should be removed from normal user!)

### Steps to reproduce the issue

1. do restricted dashboard what has few entities
2. do normal user
3. log on with normal user
4. open the search from normal user dashboard, and find some device to control what user should not be able to control.
5. control the device
...

### What version of Home Assistant Core has the issue?

2023.6.3

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

All

**Comment by frenck** [comment]
This is expected and documented as such:

<https://www.home-assistant.io/docs/authentication/#user-accounts>

![CleanShot 2023-07-10 at 12 52 16](https://github.com/home-assistant/frontend/assets/195327/837c7ee1-bd7a-4fc0-b397-409ff51d642b)

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Please note that in the future, if you think you are reporting a security-related issue, this is not the path to take. You should never raise a security issue publicly in an public issue tracker in such cases, but use a responsible disclosure route: For more information, see <https://www.home-assistant.io/security>.

In this case, it is not a security issue and documented as intended behavior.

../Frenck
