### ISSUE TITLE
Custom cards not exist on IOS 12 after 2023.07 update

### ISSUE THREAD

**Issue by Moustik2002** [home-assistant/frontend#17256]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The custom cards shown "doesn't exist" error message since july 2023 update on **my ipad mini** running **IOS12**
Roll back to 2023.06 fixes the issue.

Tested either through Official App, Beta App (test flight), Safari and Firefox.

### Describe the behavior you expected

Shown proper dash board and entities.

### Steps to reproduce the issue

1. upadating from 2023.06.03 to 2023.07.00 or 01
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.7.1 and 2023.7.0

### What was the last working version of Home Assistant Core?

2023.6.3 

### In which browser are you experiencing the issue with?

Safari IOS 12 - Firefox IOS 12

### Which operating system are you using to run this browser?

IOS 12

**Comment by ildar170975** [comment]
> The custom cards shown "doesn't exist"

Is this error displayed for all custom cards or some particular?
Check with iPhone 5S (iOS 12.5.5), at least these custom cards do work: mini-graph-card, button-card, stack-in-card, multiple-entity-row. (yes, very slowly, but do work)

**Comment by Moustik2002** [comment]
Ok issue seems to be fixed w/  release 3.0.3 of mushroom which set compatibility w/ old browser.
