### ISSUE TITLE
Android screen objects overlay 

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#17267]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Overlay, 
![IMG_20230710_215217](https://github.com/home-assistant/frontend/assets/61636045/3ceb978a-6ac6-4da0-833e-4dba585ac2fe)
see the screenshot 

### Describe the behavior you expected

No overlay 

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2027.7.1

### What was the last working version of Home Assistant Core?

Not relevant

**Comment by ildar170975** [comment]
Could you elaborate what is wrong here?

**Comment by misa1515** [comment]
Text "Vlastné úložiská" (own repositories) is over underlayer rolet menu (it seems distracting).
