### ISSUE TITLE
Apple TV media player sends 'turn off' command when apple TV is in standby mode instead of 'turn_on'

### ISSUE THREAD

**Issue by Particpant** [home-assistant/frontend#17273]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I've noticed that that media player for an Apple TV is able to _turn off_ an apple tv, but not turn it on. 
After filing a bug in the core project, the code owner, @postlund, commented that this misbehavior is a frontend bug and not a bug in the apple tv integration. See here:
https://github.com/home-assistant/core/issues/96292#issuecomment-1630094987

### Describe the behavior you expected

Apple TV should be able to turn on and turn off via the media player.

### Steps to reproduce the issue

1. Add an AppleTV to a recent version of Home Assistant. 
2. Turn it on via the AppleTV's physical remote.
3. Turn it off via the media player's power button, note that the apple tv is powered down into standby mode.
4. Try the media player's power button to turn it back on. Note that the apple TV will not power up.
...

### What version of Home Assistant Core has the issue?

core-2023.7.1

### In which browser are you experiencing the issue with?

Firefox 114.0.2 (64-bit), HA companion app

### Which operating system are you using to run this browser?

windows 11, android 11

### State of relevant entities

```txt
media_player.apple_tv standby
```

### Problem-relevant frontend configuration

```yaml
This is broken even in the devices menu media player
```

**Comment by postlund** [comment]
As a clarification: `standby` should be treated as `off` and trigger `turn_on` instead.

**Comment by Particpant** [comment]
More generally, 'standby' is incorrectly treated as an 'on' state in the UI for apple TV devices. A button with its entity set to an AppleTV media player is displayed as 'on' in standby, whereas a button set to a android TV media player entity is marked as off when the tv is off.

**Comment by karwosts** [comment]
Can you point out all the areas in the UI you've seen this? Maybe media control card, and entities row have this issue, anywhere else?
