### ISSUE TITLE
CARTO map in HA outdated for a long time

### ISSUE THREAD

**Issue by AdmiralStipe** [home-assistant/frontend#17275]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The CARTO map is totaly outdated. I have made some changes in my city to OpenStreetMap one year ago, but they still don't reflect on the map in HA. 
Can we somehow force the map update from CARTO or is there any other solution?

### Describe the behavior you expected

Updated map. 

### Steps to reproduce the issue

Just check the HA map after changes made to OpenStreetMap.

### What version of Home Assistant Core has the issue?

core-2023.7.1

### In which browser are you experiencing the issue with?

All browsers

### Which operating system are you using to run this browser?

Windows 11 Pro

**Comment by ildar170975** [comment]
> OpenStreetMap

I would vote for this.

**Comment by Bnyro** [comment]
> Wouldn't it be better to use OpenStreetMap directly instead of carto?
> 
I agree, I think his would be the best way to handle maps in HomeAssistant :+1:
