### ISSUE TITLE
Double line in HA history (begin and end of line) 

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#17276]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In history graph is found double line on beggining and end of line (can be see in attached picture) 

### Describe the behavior you expected

Without double line

### Steps to reproduce the issue

Use history graph
![Screenshot](https://github.com/home-assistant/frontend/assets/61636045/84e3393f-122d-4fba-8c49-ff5f8e6b49fa)

### What version of Home Assistant Core has the issue?

2023.07.1

### What was the last working version of Home Assistant Core?

saw in previous version too (uknown version with not double line)

### In which browser are you experiencing the issue with?

Edge 116.0.1938.10

### Which operating system are you using to run this browser?

Win10 x64 22H2

**Comment by ildar170975** [comment]
Since some HA update the more-info popup shows a statistical graph (instead of a history graph) for entities which have a statistics.
Does this particular sensor have a statistics? If yes - then probably this "double line" is related to "min", "max" etc values.

**Comment by misa1515** [comment]
issue still exist
