### ISSUE TITLE
This page is slowing down Firefox. To speed up your browser, stop this page.

### ISSUE THREAD

**Issue by CHoerby** [home-assistant/frontend#17292]
### The problem

I don't know, since when, or what was the trigger, but HA react very slow. The browser front end and the android app. 

cpu load of host system is only minimal. 

Firefox pit this notification on the top of the site: 
"This page is slowing down Firefox. To speed up your browser, stop this page." 
Chrome: 
"site does not respond" 

The start page is build up very fast - as usual, but than hangs. Cannot click any button. 

When I open the /config/ page directly, It works smooth, as always. 

Same at the android app ... 
frozen after start up. 

beside my configuration, does anybody else has this effect? 

### What version of Home Assistant Core has the issue?

core-2023.7.1

### What type of installation are you running?

Home Assistant OS

**Comment by karwosts** [comment]
possibly could be this: #17203
