### ISSUE TITLE
Dev Tools / Statistics: Search is not consistent & alphabetizing by Issue is not accurate

### ISSUE THREAD

**Issue by Moosbrugger** [home-assistant/frontend#17300]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I find that searching for a term is not consistent in that all entities don't show up, refreshing the page sometimes helps, sometimes doesn't; it feels as though the search often does not do a regex search for strings within names.  It often can't find an entity that exists.  Sometimes, as I say, refreshing the page will bring it up but not always.

Also, alphabetization does not work on Issues. Feels inconsistent.  I wonder if there is a space (or two! or some other invisible character) before some of the issue names so the ordering is being done including the space, etc..

### Describe the behavior you expected

Searches should be consistent & show all entities with substrings of x
Issues when ordered should order properly.

### Steps to reproduce the issue

1.Go to Dev Tools / Statistics
2. Search for entities & substrings of entities, see what you get, inconsistent
3. Click on the top of the Issue column & see what you get, issues are out of order
...

### What version of Home Assistant Core has the issue?

2023.6 -> 2023.7.1 and maybe earlier, I wasn't paying attention

### What was the last working version of Home Assistant Core?

?

### In which browser are you experiencing the issue with?

Google Chrome (up-to-date & earlier) & Firefox (up-to-date & earlier)er) 

### Which operating system are you using to run this browser?

Chromebook, latest update; Windows 10 Pro 22H2

**Comment by karwosts** [comment]
Yeah looks like sorting and filtering is broken for issues. 

The issue is that that column data for issues contains an array/object of multiple potential issues, and not a simple string. The sorter/filterer has no concept of how to handle this. 

Fun side effect of this is if you enter `[Object object]` in the search box, it filters for all statistics with issues :)

**Comment by karwosts** [comment]
> I find that searching for a term is not consistent in that all entities don't show up, refreshing the page sometimes helps, sometimes doesn't; it feels as though the search often does not do a regex search for strings within names. It often can't find an entity that exists. Sometimes, as I say, refreshing the page will bring it up but not always.

I think this needs a little more specificity if you want it looked at. Can you come up with a specific example/screenshots?

**Comment by Moosbrugger** [comment]
I'll work on it.  Thanks for the other--

**Comment by karwosts** [comment]
#17545 fixed the search/sort on issue column. 

Still haven't seen any follow up on what "not consistant search" really means, but at this point I'll suggest you just open a new issue with more details if you want to pursue it.
