### ISSUE TITLE
Missing in lokalise "days"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#17348]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing in lokalise translation "days"
![1689774584151_days](https://github.com/home-assistant/frontend/assets/61636045/9db4929b-397f-47df-b8b5-14f099d5f0d2)

### Describe the behavior you expected

Add to lokalise missing word

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.07.1

### In which browser are you experiencing the issue with?

Edge 116.0.1938.10

**Comment by frenck** [comment]
Unit of measurement are not translatable (and are not provided by the frontend either).

../Frenck
