### ISSUE TITLE
Missing in lokalise "decimals", "none"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#17349]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing words in lokalise translation "decimals" and "none"
![1689774584143_DecimalsNone](https://github.com/home-assistant/frontend/assets/61636045/77bb8416-5faf-499a-a2c5-8514527527cc)

### Describe the behavior you expected

Add missing words to lokalise 

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.07.1

### In which browser are you experiencing the issue with?

Edge 116.0.1938.10

**Comment by frenck** [comment]
These are units which are not translatable.
