### ISSUE TITLE
ONVIF

### ISSUE THREAD

**Issue by webtownru** [home-assistant/frontend#17345]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Good afternoon.
Thank you for your hard work.
I want to describe my problem.
I have two identical Tuya cameras that work perfectly through the integration of TuyaLocal and Tuya.
In order to have a higher speed of work inside the network, I use your ONVIF integration for my cameras.
But when adding a second camera, I get a refusal to register the camera in HA with the message that such a camera has already been added earlier.
As I understand it, the reason is that ONVIF assigns the same name for both cameras <tds:Model>1234</tds:Model> and <tds:Serial Number>0123456789</tds:SerialNumber>
How to fix it? Is it possible to replace it with a mac address.
I'm sorry for my English

### Describe the behavior you expected

I expected the camera to be added with a unique name, but it didn't happen.
https://aliexpress.ru/item/1005005291939098.html?sku_id=12000032517004328

### Steps to reproduce the issue

1. Adding the first camera Tuya
2. I add a second, the same Tuya camera

### What version of Home Assistant Core has the issue?

Operating System 10.3

### What was the last working version of Home Assistant Core?

Operating System 10.3

### Additional information

2023-07-19 15:15:59.164 DEBUG (MainThread) [homeassistant.components.onvif] Camera R2: continuous PullMessages: 1 event(s)
2023-07-19 15:15:59.473 DEBUG (MainThread) [zeep.transports] HTTP Response from http://192.168.20.28:835/onvif/device_service (status: 200):
b'<?xml version="1.0" encoding="UTF-8"?>\n<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:e="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" ><s:Header></s:Header><s:Body><tds:GetDeviceInformationResponse><tds:Manufacturer>ipcam</tds:Manufacturer>**<tds:Model>1234</tds:Model>**<tds:FirmwareVersion>1.0.0</tds:FirmwareVersion>**<tds:SerialNumber>0123456789</tds:SerialNumber>**<tds:HardwareId>04-39-26-7A-DA-85</tds:HardwareId></tds:GetDeviceInformationResponse></s:Body></s:Envelope>'
2023-07-19 15:15:59.915 DEBUG (MainThread) [homeassistant.components.onvif] Camera R2: Pulling PullPoint messages timeout=0:01:00 limit=100
2023-07-19 15:15:59.917 DEBUG (MainThread) [zeep.transports] HTTP Post to http://192.168.20.28:835/onvif/pullpointsubcribe:
b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<soap-env:Envelope xmlns:soap-env="http://www.w3.org/2003/05/soap-envelope"><soap-env:Header xmlns:wsa="http://www.w3.org/2005/08/addressing"><wsa:Action>http://www.onvif.org/ver10/events/wsdl/PullPointSubscription/PullMessagesRequest</wsa:Action><wsa:MessageID>urn:uuid:09ce7f0d-7bf5-480f-826f-91fa1ad94909</wsa:MessageID><wsa:To>http://192.168.20.28:835/onvif/pullpointsubcribe</wsa:To><wsa:Action>http://www.onvif.org/ver10/events/wsdl/PullPointSubscription/PullMessagesRequest</wsa:Action><wsa:MessageID>urn:uuid:1791151a-cdf6-4e96-9341-8f58bb34d354</wsa:MessageID><wsa:To>http://192.168.20.28:835/onvif/pullpointsubcribe</wsa:To><wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><wsse:UsernameToken><wsse:Username>admin</wsse:Username><wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">ky0v+XOuzmwxQ1GTi5KTes6z6wo=</wsse:Password><wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">kruTHGwTuoYiWytF2XxL6w==</wsse:Nonce><wsu:Created xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2023-07-19T12:15:59+00:00</wsu:Created></wsse:UsernameToken></wsse:Security></soap-env:Header><soap-env:Body><ns0:PullMessages xmlns:ns0="http://www.onvif.org/ver10/events/wsdl"><ns0:Timeout>PT1M</ns0:Timeout><ns0:MessageLimit>100</ns0:MessageLimit></ns0:PullMessages></soap-env:Body></soap-env:Envelope>'

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
