### ISSUE TITLE
Missing in lokalise "Unknown Error Occurred"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#17354]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing phrase in lokalise translation
![1689781186841_UnknownErrorOccurred](https://github.com/home-assistant/frontend/assets/61636045/bd8ea519-4f78-4238-a788-a1ff94cb63fe)

### Describe the behavior you expected

Add phrase to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.07.1

**Comment by frenck** [comment]
This is not a frontend translation, nor is this technically translatable. We don't know what happened in this case.

../Frenck
