### ISSUE TITLE
Unable to activate HACS: submit button is missing 

### ISSUE THREAD

**Issue by Karelgil** [home-assistant/frontend#17358]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am using a fresh installation of home-assistant on a RPi 4 and I am trying to install HACS.
The installation hangs on the ‘waiting for device activation’ screen. According to the installation guide I have to click ‘submit’ after entering the code on GitHub, but this button is missing.

### Describe the behavior you expected

I was expecting a ‘submit’ button on the activation screen  according to the instructions 

### Steps to reproduce the issue

1. Go to integrations panel
2. Add integration 
3. Select HACS
4.  Click 4 buttons to accept usage
5. On device registrations panel there is no ‘submit’ button 
...

### What version of Home Assistant Core has the issue?

2023.7.3

### What was the last working version of Home Assistant Core?

N.a.

### In which browser are you experiencing the issue with?

All latest browsers on iOS and MacOS as well as in iOS app for iPad and iPhone and macOS app

### Which operating system are you using to run this browser?

Latest iOS versions for iPad and iPhone, latest version macOS

**Comment by Karelgil** [comment]
<img width="541" alt="image" src="https://github.com/home-assistant/frontend/assets/139581828/5280df33-4751-449a-b63c-a015c984fb47">

**Comment by karwosts** [comment]
HACS is a custom component, which is not supported in this repository. 

I would file this on the hacs integration github. 

https://github.com/hacs/integration

**Comment by frenck** [comment]
Custom integration are not supported by the Home Assistant project. Please report the issue with the custom integration instead, as pointed out above by karwosts.

../Frenck

**Comment by Karelgil** [comment]
Well, according to the HACS team this is an issue in the front end of HA and not an HACS issue as the user interface for this window is provided by HA. 

So what now? HA points to HACS and HACS points to HA../

**Comment by frenck** [comment]
> So what now?

As said, Home Assistant does not support custom integrations.

../Frenck

**Comment by karwosts** [comment]
If it could be definitively shown that this was due to some defect in the frontend code I would be willing to engage to see if it can be resolved, but I think some debug needs to take place first from the side of the custom component owner to point to exactly what they believe the problem is. 

Have you opened an issue in that repository?

**Comment by Karelgil** [comment]
Problem is solved. Don’t ask me how, but a fresh installation of HA did the trick, which is odd, because the previous installation was also a fresh one
