### ISSUE TITLE
Missing in lokalise "Loading data"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#17352]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing phrase in lokalise "Laoding data"
![1689781490527_LoadingData](https://github.com/home-assistant/frontend/assets/61636045/f346fc0d-d7b6-49f2-8703-3952e6744c51)

### Describe the behavior you expected

Add missing phrase to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.07.1

**Comment by karwosts** [comment]
AFAIK This cannot be translated because it is shown before your local language is loaded/determined.

**Comment by frenck** [comment]
Correct, no application is loaded at this point, so nothing can be translated yet.
