### ISSUE TITLE
Missing in lolakise "Confirmable Notification"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#17350]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing phrase in lokalise translation "Confirmable Notification"
![1689774584041_ConfirmableNotification](https://github.com/home-assistant/frontend/assets/61636045/0cd9b85e-e67c-4067-a866-4a35a8b449ae)

### Describe the behavior you expected

Add phrase to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.07.1

**Comment by frenck** [comment]
Blueprints cannot be translated, they are provided by the community (or sometimes shipped as a demo). As they are external, they are more part of our translation system.

../Frenck
