### ISSUE TITLE
Energy configuration: Already added devices still showing in dropdown

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/frontend#17359]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Please see https://github.com/home-assistant/core/issues/84852

I was asked to post here. 

### The problem

Hello,
we discussed this on the forum in the course of this thread https://community.home-assistant.io/t/wth-are-entities-not-added-to-energy-integration-automatically/467717 a while back but it seems the fix did not work (or maybe it was forgotten :) ).

When adding new devices to the energy monitoring (e.g. grid consumption) the added devices still show in the dropdown menu. They should be excluded from the dropdown as it is forbidden to re-add them.

As long as those are still being shown, adding devices remains a bit of a pain ;)

![image](https://user-images.githubusercontent.com/57034871/210085778-c6edf139-b828-4d62-990c-0d9ffbed2fd9.png)

### What version of Home Assistant Core has the issue?

2022.12.7

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Energy

### Diagnostics information

![image](https://user-images.githubusercontent.com/57034871/210085765-c5623f4b-a77e-4f97-bcef-9cc30d1a0518.png)

**Comment by AleXSR700** [comment]
In contrast to the statement in the original `core` issue thread, this problem is NOT solved and the issue is not closed.

**Comment by karwosts** [comment]
I am looking at this.

**Comment by AleXSR700** [comment]
Hmm, I just updated to 
```
Home Assistant 2023.8.3
Frontend 20230802.1 - latest
```
Is it not included yet? I still see all devices in the dropdown.

**Comment by karwosts** [comment]
It is not released. Check back in 2023.9.

**Comment by AleXSR700** [comment]
Seems to be working nicely, thank you very much! :-)
