### ISSUE TITLE
Missing in lokalise "Local Time", "Mon", "Jul", "Time in Miliseconds"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#17367]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing words and phrases in lokalise for translation
![1689858543240_LocalTime](https://github.com/home-assistant/frontend/assets/61636045/2e0c6c51-42c5-422a-93ad-17f0609787a3)

### Describe the behavior you expected

Add missing words and phrases to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.07.1

**Comment by frenck** [comment]
We can't read the language you are sharing, so you need to add some context here @misa1515.

What am I looking at?

../Frenck

**Comment by misa1515** [comment]
@frenck in this menu
Settings/Companion application (location and notifications)/Sensor management/Last restart sensor/Last restart/

**Comment by karwosts** [comment]
I don't think this is the right repo for this, those dialogs are specific to the companion app.
