### ISSUE TITLE
Missing in lokalise "IP Information"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#17365]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing phrase in lokalise for translation

### Describe the behavior you expected

add phrase to lokalise
![1689858543209_IpInformation](https://github.com/home-assistant/frontend/assets/61636045/dc8f3c80-80b8-40eb-a995-248ef243afcb)

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.07.1

**Comment by frenck** [comment]
Seems like you didn't actually check Lokalise before making this issue?

This was fixed in #17261, as you reported before... (so you are creating duplicates now).

../Frenck
