### ISSUE TITLE
Missing in lokalise "AutoConfigure", "Detected"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#17364]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing phrase in lokalise

![1689858543203_AutoConfigure](https://github.com/home-assistant/frontend/assets/61636045/95cc63d0-1987-420c-a633-7fe745c7fca4)

### Describe the behavior you expected

Add phrase to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.07.1

**Comment by misa1515** [comment]
![1689858543203_AutoConfigure_v2](https://github.com/home-assistant/frontend/assets/61636045/62564c00-32fc-47b5-8478-1142d820de56)

**Comment by frenck** [comment]
Fourth duplicate report you make for the same thing...

Now going to just close these.

..?Frenck

**Comment by misa1515** [comment]
"Auto Configure" and "Detected" still not translated

here is reference
![image](https://github.com/home-assistant/frontend/assets/61636045/a832ac11-9691-4370-98c0-5408f334252a)
