### ISSUE TITLE
Missing in lokalise "AuthetificatorApp"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#17363]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Found untranslated phrase, missing in lokalise "AuthetificatorApp"
![1689858543155_AuthetificatorApp](https://github.com/home-assistant/frontend/assets/61636045/cb15a35a-0d01-4cc6-a96a-36d081bb1ed3)

### Describe the behavior you expected

Add missing phrase to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.07.1

**Comment by karwosts** [comment]
Authenticator app is a string from backend, not frontend. An issue is already open for it.

https://github.com/home-assistant/core/issues/95033
