### ISSUE TITLE
jinja 'relative_time' doesn't localize return value

### ISSUE THREAD

**Issue by RoepLuke** [home-assistant/frontend#17373]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating the following Jinja Template and using it in the UI / Developer Template, the resulting return string is not localized.
I assume this is a Jinja Extension provided by Home Assistant, as i couldn't find it in the [jinja documentation](https://jinja.palletsprojects.com).

**Language Settings (Profile):**
- Language: German (de_DE)
- Time Format: Auto (use language setting)
- Date Format: Auto (use language setting)

**Template:** `{{ now() ~ ' - ' ~ (today_at('01:00') | relative_time()) }}`

**Result / Return string:**  `2023-07-21 04:24:03.678325+02:00 - 3 hours`

### Describe the behavior you expected

Result output in the User language.

In this case, this template would then return: `2023-07-21 04:24:03.678325+02:00 - 3 Stunden`

### Steps to reproduce the issue

1. Check Language in Profile / User Settings
2. Copy Template into Developer Tools > Template
3. Observe

### What version of Home Assistant Core has the issue?

core-2023.7.2

### In which browser are you experiencing the issue with?

Mozilla Firefox 115.0 64bit

### Which operating system are you using to run this browser?

Fedora Linux 38 (Workstation Edition)

**Comment by karwosts** [comment]
I think this probably needs to be a home-assistant/core issue, not frontend. 

Frontend doesn't parse the templates, it just sends it to backend (core). Then core sends back the string that the template renders to.
