### ISSUE TITLE
Helpers - there is no way to edit or delete "input_boolean toggle"

### ISSUE THREAD

**Issue by kyc1338** [home-assistant/frontend#17375]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I used helper Toggle function to create some input_boolean switches, it's easy to edit or delete other helpers such as light grouping but there is no way to edit or delete input boolean toggle switches.

### Describe the behavior you expected

It should be similar to other Helper such as light grouping, when click on the settings, the contains of the helper are shown which can be edited or deleted.

### Steps to reproduce the issue

1. Click "Create Helper"
2. Select "Toggle"
3. Input name and select icon
4. After the Input Boolean Toggle created, click on the entity
5. It will show up a window with the toggle switch 
6.Then click "settings"
7.The windows will be reduced and show only the name of the switch, without any option to edit of delete it.
...

### What version of Home Assistant Core has the issue?

2023.7.2

### In which browser are you experiencing the issue with?

Google Chrome and Safari

### Which operating system are you using to run this browser?

masOS ventura 13.4.1

**Comment by karwosts** [comment]
> 7.The windows will be reduced and show only the name of the switch, without any option to edit of delete it.

I don't get that, I get the full settings window with a delete button, rename options, etc. 

![image](https://github.com/home-assistant/frontend/assets/32912880/86a542d3-2834-44a8-b34b-242442459393)


Though I do feel like I may have seen this thing you describe where clicking on settings just gives you a blank tab with the header only, though I don't remember exactly when or how that occured. 

So there may be something more nuanced that cause it to break, may need further investigation.

**Comment by kyc1338** [comment]
Dear karwosts

Thanks for your prompt response. Just happened a new version of HA core released this morning and the problem solved after the update.
