### ISSUE TITLE
Missing in lokalise "IP address", "method"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#17378]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing phrases in lokalise
![1689918344600_IpInformation](https://github.com/home-assistant/frontend/assets/61636045/91468665-0a27-49c5-a2cd-8029f6836a70)

### Describe the behavior you expected

Add phrases to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.7.2

**Comment by frenck** [comment]
This is now the third time you are reporting these @misa1515. They are in Lokalise, but still need to be released in a stable release of Home Assistant. This was fixed in #17261

Please try to avoid creating duplicate issues.

../Frenck
