### ISSUE TITLE
Show current day more prominently when selecting a date span on /history

### ISSUE THREAD

**Issue by themorgantown** [home-assistant/frontend#17380]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On normal pixel density screens (non 2x), the boldness of the current date (represented as .today) is difficult to spot. It makes choosing a span of days including today's date difficult. 

Can I recommend adding an underline as well? 

This image shows the current UI with today's date (July 21) as bold: 
![Screenshot 2023-07-21 at 10 10 44 AM](https://github.com/home-assistant/frontend/assets/50146/0fa15f77-2e1e-4e42-842c-0047917c92b7)

This shows today's date both bold + underline 
![Screenshot 2023-07-21 at 10 10 28 AM](https://github.com/home-assistant/frontend/assets/50146/db356645-b6c5-4852-877b-8e2a2d7e2b65)

Code here: https://github.com/home-assistant/frontend/blob/0eebc9095c26cdcfa963dba8f07dde333890b2f5/src/panels/calendar/ha-full-calendar.ts#L459 

Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

### Describe the behavior you expected

An easier to spot current day

### Steps to reproduce the issue

1. Open History
2. Select first day
3. Scan back to current day + scan for today's date 
 

### What version of Home Assistant Core has the issue?

2023.7.2

### In which browser are you experiencing the issue with?

Chrome 115

### Which operating system are you using to run this browser?

Ventura 13.4

**Comment by matthiasdebaat** [comment]
Thanks for this PR! The underline is still a bit hidden. Can you make it into a circular line when its not selected?

**Comment by ildar170975** [comment]
Alternatively, the current date may have a different color.

**Comment by themorgantown** [comment]
I played around with this a bit, and I think a 100% border-radius circle around the date looks best in both light + dark theme. Using the primary color as the border and a 10% opacity fill, it'll would look like: 

![dark2](https://github.com/home-assistant/frontend/assets/50146/1f683a3b-f8ab-4942-863d-5806cf4ee4af)
![light2](https://github.com/home-assistant/frontend/assets/50146/b939a632-ef1f-45d3-a800-ce6c4d917473)

(as a reminder, the current only differentiating difference between any day and the current day, is that the current day is bold). 

This is setup in the `td.today` class 


````{
background: rgba(217, 217, 217, 0.1);
border: 1px solid #4BA6EE;
text-decoration:underline;
}````

**Comment by matthiasdebaat** [comment]
Thanks! Some minor changes based on [Material 3 guidelines](https://m3.material.io/components/date-pickers/specs#f25f68b7-1bb5-4248-829e-fe3cd3499dab):
- Both number and outline in primary color. No underlining, keep the same background color and no bold font size.
- In date selection, the first and last dates are circular. And the selection does not have a bold font size.
- Change the unselected day numbers to primary text color.
- Remove the gray background from dates outside the month. Change the text to secondary text color.

<img width="1024" alt="unnamed" src="https://github.com/home-assistant/frontend/assets/20203284/aea4bd9b-5dd1-49e6-b0d5-d304d5b401d9">
