### ISSUE TITLE
Missing Self-sufficiency

### ISSUE THREAD

**Issue by candrea77** [home-assistant/frontend#17394]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After upgrade to 2023.7 I didn't get the Self-sufficiency gauge in my Energy Dashboard

### Describe the behavior you expected

I have an energy dashboard configured with : 
 - Grid consumption
 - Grid carbon footprint
 - Solar production
 - Battery systems (discharge and charge)

After upgrading to 2023.7 I was expecting to view the Self-sufficiency guage on energy dashboard, but it's mssing.
The only gauge present is the "Low-carbon energy consumed" (that was already present)

### Steps to reproduce the issue

1.Upgrade to 2023.7
2.Openup the energy dashboard : Self-sufficiency is missing.

Tested with : 
 - Chrome
 - Edge
 - Android application

### What version of Home Assistant Core has the issue?

Home Assistant 2023.7.3 Supervisor 2023.07.1 Operating System 10.3 Frontend 20230705.1 - latest

### What was the last working version of Home Assistant Core?

Home Assistant 2023.7.3 Supervisor 2023.07.1 Operating System 10.3 Frontend 20230705.1 - latest

### In which browser are you experiencing the issue with?

Chrome 114.0.5735.199 / Edge 115.0.1901.183

### Which operating system are you using to run this browser?

WIndows 11 / Android 13

**Comment by karwosts** [comment]
Based on the code it looks like it only appears if you also have a return to grid sensor. That feels like it might be an unnecessary restriction, but I'm not that familiar with this concept.

**Comment by candrea77** [comment]
> Based on the code it looks like it only appears if you also have a return to grid sensor. That feels like it might be an unnecessary restriction, but I'm not that familiar with this concept.
> 
> Seems like maybe a comment about it here:
> 
> https://github.com/home-assistant/frontend/pull/15704/files#r1126873525

Hi there,
you are so right.

Added the return energy sensor and  Self-sufficiency gauge just showed up.

Thank you .!!!!
