### ISSUE TITLE
Erroneous 'WLED Update Available' for device which can't run the update

### ISSUE THREAD

**Issue by BGFHA** [home-assistant/frontend#17392]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

HA is telling me that there is an update available for a device which is running an "old" version.

WLED
Installed version
0.13.1
Latest version
0.13.3

However the device is correctly identified:
Firmware: 0.13.1
Hardware: esp8266

The ESP8266 cannot move past 0.13.1

### Describe the behavior you expected

Recognise that the ESP8266 cannot be updated.

### Steps to reproduce the issue

1. Connect a ESP8266 running WLED version 0.13.1
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.7.3 Supervisor 2023.07.1 Operating System 10.3 Frontend 20230705.1 - latest

### In which browser are you experiencing the issue with?

Google Chrome

### Which operating system are you using to run this browser?

Windows 10

### Additional information

The Android app is also showing this information.

**Comment by karwosts** [comment]
This is not a frontend issue, the update decisions come from core. Please file an issue in home-assistant/core repo against the wled integration, thanks!
