### ISSUE TITLE
Wrong label "self-sufficiency quota" in energy dashboard

### ISSUE THREAD

**Issue by robert2s** [home-assistant/frontend#17393]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On the energy dashboard, the self-sufficiency meter is labelled with a wrong term "self-sufficiency quota". The term "quota" means (Cambridge dictionary) "_a fixed, limited amount or number that is officially allowed_". The self-sufficiency is not a quota.

Note: the Dutch term "zelfvoorzieningsquota" is plural, but it only concerns one percentage, so that is wrong as well (in Dutch, _qoutum_ is singular, _quota_ is plural)

### Describe the behavior you expected

We could replace the word "quota" by "percentage", "portion", or "rate".

But simpler and better is to just remove the word "quota". The "%" sign in the diagram already clearly indicates that self-sufficiency is a percentage. In addition, it is consistent with other diagrams labels such as "self-consumed solar energy" (also without the word "quota" or "percentage").

So the labels become:
* English: _self-sufficiency_
* Dutch: _zelfvoorziening_

### Steps to reproduce the issue

Open the "energy" dashboard, look at the label below the self-sufficiency meter.

### What version of Home Assistant Core has the issue?

2023.7.3

**Comment by karwosts** [comment]
This was fixed for english in a recent PR #17241, that will be released in 2023.8. 

Translations are handled on Lokalize, not tracked in frontend issues. If you want to suggest an alternative translation you may learn about the steps here:

https://developers.home-assistant.io/docs/translations/
