### ISSUE TITLE
Disconnected web socket connection to backend is not detected

### ISSUE THREAD

**Issue by leonardmgh** [home-assistant/frontend#17409]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am using an IPad Pro as dashboard for HomeAssistant. After it has been running with the HomeAssistant App / Safari open for a few hours the frontend disconnects completely from the backend. Inspecting it i can see that the frontend still thinks that it has a open websocket to the HomeAssistant backend. Looking in the logs i can see that the web sockets usually has been disconnected hours ago on the backend side. I have been able to reproduce the same problem on a MacBook Pro M1 in Safari.

Now i have finally been able to reproduce the error by going out of the app and changing the wifi network. I am not sure if the device changing wifi networks in the background has been the cause of the problem the whole time or just one way to trigger it. 

### Describe the behavior you expected

The frontend should detect that the websocket connection to the backend is dead and create a new connection.

### Steps to reproduce the issue

IPad with HomeAssistant accessed over local network:
1. Open HomeAssistant(App or Browser)
2. Exit App(don't close it)
3. Go to wifi settings and change network. 
4. (You can now connect to the old wifi network again)
5. Open HomeAssistant again
6. Now all buttons "work", but commands are never received on backend.

### What version of Home Assistant Core has the issue?

Home Assistant 2023.7.1

### In which browser are you experiencing the issue with?

Safari/605.1.15

### Which operating system are you using to run this browser?

IPadOS 16.6

### Additional information

Inspecting the websocket connection when problem occurs. (Look at the timestamps)
https://pasteboard.co/JEbFwovEslEm.png

**Comment by leonardmgh** [comment]
I have been looking a bit into how this problem can be solved. In general does it seem like that webkit is unreliable to detect a broken websocket connection. Besides that did i also read about someone having the same (or similar) issue when his PC wakes up from sleep.

As far as i can see its only the backend that pings the frontend. So my thought for a potential workaround/solution for issues where the websocket disconnects could be a timeout in the frontend received from the backend for some time. Or maybe just pinging the backend from the frontend. However i could imagine this could have some other unforeseen side effects.

**Comment by leonardmgh** [comment]
In home-assistant/iOS#2219 the same issue is discussed. According to this comment 
https://github.com/home-assistant/iOS/issues/2219#issuecomment-1288357242 the connection should error out at some point. From what i have seen however this never occurs. 

Also i have found other similar issues, that might be caused by something else, but result in the same state of the HA frontend.
https://github.com/home-assistant/iOS/issues/1801
https://github.com/home-assistant/core/issues/57271

**Comment by WSchnee** [comment]
Can confirm this.

I have two iPads (Pro1, 2017),  as well as iPhones (SE 1, 6). They are wall mounted controllers with the display ‘always on’. When this happens a pull-down to refresh on all the devices is required to restore the connection, which seems to time out on a sporadic basis.

I am using the iOS App on all those devices.
Furthermore, no WIFI/Network outage was recorded on my network when this happened. Neither were any automatic updates run on the devices during this time  It seems to just timeout after some time.

**Comment by WSchnee** [comment]
This is still a problem.

**Comment by xuefer** [comment]
> [dev...leonardmgh:homeass-frontend:fix-halfopen-websocket](https://github.com/home-assistant/frontend/compare/dev...leonardmgh:homeass-frontend:fix-halfopen-websocket) Something like this will probably fix it. I haven't tested it though.

a active ping is exactly the fix as I suggested before i find this issue. please make it important priority. stability is required by screens that show home assistant as main and only UI. opening frontend for "manual" usage from time to time, is not "smart" way. any manual usage is not smart enough

**Comment by leonardmgh** [comment]
> > [dev...leonardmgh:homeass-frontend:fix-halfopen-websocket](https://github.com/home-assistant/frontend/compare/dev...leonardmgh:homeass-frontend:fix-halfopen-websocket) Something like this will probably fix it. I haven't tested it though.
> 
> an active ping is exactly the fix as I suggested before i find this issue. please make it important priority. stability is required by screens that show home assistant as main and only UI. opening frontend for "manual" usage from time to time, is not "smart" way. any manual usage is not smart enough

You are welcome to review my PR and give some feedback :)

**Comment by xuefer** [comment]
the patch works for me, it should be merged and polished later

**Comment by leonardmgh** [comment]
Should be fixed with #18934
