### ISSUE TITLE
Rain rate (precipitation_intensity) graph is not clear

### ISSUE THREAD

**Issue by LucaTNT** [home-assistant/frontend#17405]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Tain rate (`precipitation_intensity`) sensors currently show their history as a bar that changes color.

Take this as an example:
![Rain rate sensor history](https://i.imgur.com/LEcgTWl.png)
At a glance it is impossible to tell if it rained harder at 11 pm or at 8 am.

### Describe the behavior you expected

It would be much clearer if a standard line graph was used.

### Steps to reproduce the issue

1. Configure a sensor with class `precipitation_intensity`
2. Wait for some data to accumulate
3. Check the history graph

### What version of Home Assistant Core has the issue?

2023.7.3

### In which browser are you experiencing the issue with?

Safari 16.5 & Firefox 115.0.2

### Which operating system are you using to run this browser?

macOS Ventura 13.5 & Windows 11

**Comment by karwosts** [comment]
This occurs because your sensor does not have a `unit_of_measurement`. If you give it a proper unit, it will show with the line graph.

**Comment by ildar170975** [comment]
Probably this is not to be discussed here - I always wondered why a sensor with device_class cant have a default UoM?
For instance, some hypothetical device_class has possible W, kW, MW units - and one of them is default.

**Comment by LucaTNT** [comment]
> This occurs because your sensor does not have a `unit_of_measurement`. If you give it a proper unit, it will show with the line graph. 

That was it! Thank you.
