### ISSUE TITLE
images on entities buienradar condition are low res (compared to attributes on weather entity)

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#17404]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

<img width="389" alt="Scherm­afbeelding 2023-07-24 om 22 53 21" src="https://github.com/home-assistant/frontend/assets/33354141/47280081-cf0e-4d4e-b0fa-ae4add896239">

top is `sensor.buienradar_condition`
bottom is weather.buienradar entity.attributes.forecast[0].condition

### Describe the behavior you expected

have better pictures on integration entities for condition

### Steps to reproduce the issue

1. just install buienradar integration
2. compare weather entities conditions with integration condition entity
3.
...

### What version of Home Assistant Core has the issue?

2023.7.x

### Additional information

<img width="374" alt="Scherm­afbeelding 2023-07-24 om 22 56 50" src="https://github.com/home-assistant/frontend/assets/33354141/234cc79e-6420-472c-af41-e43b3515eda6">

conditions just changed, making it all the more obvious

this is very obvious in a button-card as posted above, but also a regular core entities card shows low res images:

<img width="497" alt="Scherm­afbeelding 2023-07-24 om 23 00 07" src="https://github.com/home-assistant/frontend/assets/33354141/de08ad54-4901-4c66-936d-1424f281ac64">

**Comment by joostlek** [comment]
Hey Marius,

As you can see in the developer tools, these pictures come from Buienradar itself. So this isn't an issue for the frontend. This might be a valid issue for the core to replace the buienradar icons with icons, but that's for the code owners or someone else to pick up.

![image](https://github.com/home-assistant/frontend/assets/7083755/49f3ffd8-59bf-4af6-bf97-95795ec92b48)

**Comment by Mariusthvdb** [comment]
tbh, not sure about that, seems a valid issue from a frontend perspective. Ha should not adopt images below a certain quality. 

Simply referring this to core, or probably a FR, (because its no technical issue and that will be rejected there), is not a very productive  response.

ofc it in the end would have to be implemented somewhere in core, but the start would be to acknowledge the frontend result is very much below what we should want.

**Comment by joostlek** [comment]
But the options the frontend can do are limited, in this instance it only received this URL from buienradar. The frontend can show it, or it can hide it since it's low quality. The only thing I can imagine it could do to make it high res is upscale it with AI, and that's just a fantasy at this point.

To fix this, the backend should provide better images.

**Comment by joostlek** [comment]
Oh and don't get me wrong, I agree that HQ images would be nice, but the frontend wouldn't be the place to fix this.
