### ISSUE TITLE
Entity Filter in Energy Dashboard config not working

### ISSUE THREAD

**Issue by AlainPeccable** [home-assistant/frontend#17415]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

All filters within the Energy dashboard config (/config/energy) are not working as expected.
When you type the name of an entity (name or alias) it briefly shows you what you want but then the filtered list return to the full list of valid entity (unfiltered)

example with the individual hardware selection:
![image](https://github.com/home-assistant/frontend/assets/132245586/eb5fdff9-5e78-4425-b87d-21e9ee7095b0)

When I type an entity name you see the filter working but it goes away even too fast to take a screenshot, and immediately show the whole list:
![image](https://github.com/home-assistant/frontend/assets/132245586/b0cde909-4034-4e25-ad9b-42051261499d)

### Describe the behavior you expected

Expectation is that the filter works like in all other screens:
![image](https://github.com/home-assistant/frontend/assets/132245586/ebb424a8-535e-4047-8207-912527ef17be)

### Steps to reproduce the issue

1. Navigate to energy configuration
2. Add an entity (to any category available on that page)
3. Try to filter

Tested in Chrome/Edge + iPhone & iPad

### What version of Home Assistant Core has the issue?

2023.7.3

### In which browser are you experiencing the issue with?

Google Chrome 115.0.5790.102

### Which operating system are you using to run this browser?

Microsoft Windows [version 10.0.22000.2176]

**Comment by ildar170975** [comment]
Same https://github.com/home-assistant/frontend/issues/16901

**Comment by BradleyFord** [comment]
Confirm I am also seeing the same.

It is quite frustrating as I see the item, then just as I go to click it, it then changes the whole list again

**Comment by BradleyFord** [comment]
https://github.com/home-assistant/frontend/pull/17381

**Comment by karwosts** [comment]
I don't believe #17381 addresses this issue.

**Comment by AleXSR700** [comment]
No, this issue is a new bug I also noticed recently.
This is not related.

**Comment by karwosts** [comment]
Believe I have a fix, just filed
