### ISSUE TITLE
Logbook uses current state for event entities

### ISSUE THREAD

**Issue by joostlek** [home-assistant/frontend#17416]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![ezgif com-video-to-gif](https://github.com/home-assistant/frontend/assets/7083755/0af6f000-d14e-46fa-ad48-6052c91f0549)

The logbook shown at the device page is always showing the latest state for event entities.

### Describe the behavior you expected

I would expect the previous event to be named "Initial press" and the second one "Short press" or "long press", whatever.

### Steps to reproduce the issue

1. Run the beta
2. Have an event entity with more than one event types
3. make it switch event types
4. profit

### What version of Home Assistant Core has the issue?

dev (nothing changed there since beta)

### In which browser are you experiencing the issue with?

Firefox

### Which operating system are you using to run this browser?

W10

**Comment by RosemaryOrchard** [comment]
Hopefully useful/relevant info: If I have the entity modal open when I trigger the event (example in my case was a Hue switch connected via the Hue integration) then the events come in correctly. It's when going to the logbook after that or re-opening the entity modal that they appear incorrectly.

**Comment by joostlek** [comment]
By the way, I took a look in the frontend and backend. And apparently the frontend doesn't receive the event types. It only receives the state (the time) but not the happened event type. So I'm not sure if the frontend should do a second call to get the event type for that moment or that it should get sent in the first message.

**Comment by frenck** [comment]
> And apparently the frontend doesn't receive the event types.

Yup, which is why I haven't resolved it yet. Will pick this up with the frontend team @ Nabu Casa tomorrow.

**Comment by joostlek** [comment]
Oh right, still needed to check this

**Comment by ildar170975** [comment]
@joostlek can you reopen it?
