### ISSUE TITLE
failure to change network settings due to "unknown setting name"

### ISSUE THREAD

**Issue by spaceserpent** [home-assistant/frontend#17421]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

received an error stating "Can't update config on enp1s0: device: unknown setting name" when attempting to cahnge network settings: IP, DNS, gateway, etc. Persist despite reboots, resets of network connections, etc. 

Currently running HA OS on generic linux

![image](https://github.com/home-assistant/frontend/assets/113296162/a77a7cae-72f1-417b-b9f1-41849a6a042a)

### Describe the behavior you expected

Expected to change network settings without issue 

### Steps to reproduce the issue

1. have pre-existing network config
2. attempt to change network config of an interface 
3. error recieved 
...

### What version of Home Assistant Core has the issue?

HA OS

### What was the last working version of Home Assistant Core?

2023.8.0b1

### In which browser are you experiencing the issue with?

Firefox DEV 116.0b8 (64-bit)

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
Issue occurred despite use of different browsers and client devices i.e. android, edge, iphone, etc.
```

**Comment by spaceserpent** [comment]
occurring regardless of auto network config or selecting the interface

**Comment by silamon** [comment]
What is the page url? Seems like I broke this somehow in my network pull request.

**Comment by silamon** [comment]
Could you explain the steps to reproduce this? More specificly if you are using the supervisor screen or the network screen. Or perhaps try if it works in any of those. 

I thought it would be due to my change in this page but the reviewing takes way longer these days and the pull request I thought would be it is still to be reviewed and not in the August beta.

**Comment by silamon** [comment]
Still not sure the cause of this, but it might be a supervisor issue seeing there are changes there too. https://github.com/home-assistant/supervisor/pull/4416

**Comment by spaceserpent** [comment]
as you might expect, it occurs with any attempted change to the network interface, i.e. from static to auto, IPs, etc. 

looks like occurring both in CLI and UI-- let me know if I should try a different CLI method. 

![image](https://github.com/home-assistant/frontend/assets/113296162/5331254b-cb8c-4d87-9f8b-833e79a93570)

**Comment by silamon** [comment]
Thank you for testing further, I would suggest to open an issue on the supervisor repository: https://github.com/home-assistant/supervisor.

**Comment by spaceserpent** [comment]
thank you, see after for newly written SU ticket, https://github.com/home-assistant/supervisor/issues/4459

**Comment by silamon** [comment]
This can be closed since the issue was due to a supervisor change.
