### ISSUE TITLE
Energy Dashboard: Currently allows the same device to be added multiple times

### ISSUE THREAD

**Issue by BradleyFord** [home-assistant/frontend#17447]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a huge list of individual devices and I am struggling to know what I have added to the list or not; just today I tried to add a device to the list and this was accepted. But then I realised later that it is already included in the "Individual Devices" list... hence it is duplicated.

More broadly this list is good for a couple of devices, but doesnt scale well. 

### Describe the behavior you expected

The list should filter out devices that are already in the list so we dont add duplicates; it should also be filtered to only show devices that are compatible

### Steps to reproduce the issue

1. Add a device
2. Add it again

### What version of Home Assistant Core has the issue?

2023.08

### In which browser are you experiencing the issue with?

Chrome latest

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment]
I'm planning to come back and do this once #17359 is done.
