### ISSUE TITLE
Energy dashboard total costs not visible when Water usage 0

### ISSUE THREAD

**Issue by TyzzyT** [home-assistant/frontend#17444]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I've setup the water costs sensor in the Energy dashboard, but when we have a day with 0 water usage the Total costs is not being shown.

![image](https://github.com/home-assistant/frontend/assets/80623729/89c4923f-f118-4673-ba45-045621d1620a)

![image](https://github.com/home-assistant/frontend/assets/80623729/182c13fd-73ad-43ac-87cb-dd0b0fbea468)

### Describe the behavior you expected

I expected the Total costs to always be shown, because Electricity & solar sensor is not 0

### Steps to reproduce the issue

Have any day/week with 0 water usage and switch the day view between a day with and without water usage. You'll see the Total costs row appear/disappear

### What version of Home Assistant Core has the issue?

core-2023.8.0b2

### What was the last working version of Home Assistant Core?

never

### In which browser are you experiencing the issue with?

Brave version 1.56.14 Chromium: 115.0.5790.114 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11 22H2

**Comment by karwosts** [comment]
Can you please include a screenshot of the entire energy table when the total is missing (not just snipping the water). I'd like to see the full picture of what's going on.

**Comment by TyzzyT** [comment]
Sure
![image](https://github.com/home-assistant/frontend/assets/80623729/dbcb7dc9-6ec2-42b1-83df-12db38a9cb6c)

**Comment by karwosts** [comment]
Looks like the current logic only shows the total if at least two out of three (energy, gas, water) have a nonzero value. I can kind of see where they were going with that logic, but I guess showing the total still makes sense in that case.

**Comment by TyzzyT** [comment]
I think so too. It makes sense to have the total costs always available, to see the difference between 2 days instead of moving your eyes around the screen when switching days.
