### ISSUE TITLE
Creating a custom color for the more-info color selectors doesn't work unless you select a color.

### ISSUE THREAD

**Issue by Petro31** [home-assistant/frontend#17446]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This process does not work:

1. Set a desired light color from a service call.
2. Open that lights more-info page.
3. Hold one of the swatches to enable adding a new quick select color patch.
4. In the new dialog box that appears, Click save (because you are already at the desired color).
5. No new swatch appears.

This process works:

1. Set a desired light color from a service call.
2. Open that lights more-info page.
3. Hold one of the swatches to enable adding a new quick select color patch.
4. In the new dialog box that appears, select a color thats REALLY close to the color you want.
5. Click save
6. New swatch appears.

### Describe the behavior you expected

Clicking save should add the currently set color on the light regardless if you click or not.

### Steps to reproduce the issue

See above

### What version of Home Assistant Core has the issue?

2023.8.0b2

**Comment by karwosts** [comment]
Proposed fix #17992
