### ISSUE TITLE
Lifetime production decreased in 5 min with 300 kWh

### ISSUE THREAD

**Issue by peliilep** [home-assistant/frontend#17455]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Between 01-08-2023 13:25 CET and  01-08-2023 13:30 CET the lifetime production dropped from 3730,95 to 3430,29 kWh.
When I looked in the Enphase app and on the enlighten website, the lifetime production didn't decrease, but increased with the production during the day. Currently, 02-08-2023 the lifetime production on the Enphase app is 3740 kWh versus HA 3441 kWh.
See also the HA graph.
There is no clue for this instant drop in HA alone.

### Describe the behavior you expected

<img width="685" alt="Scherm­afbeelding 2023-08-02 om 09 17 10" src="https://github.com/home-assistant/frontend/assets/23400538/41b2c9c6-5bd8-470e-85d4-872f0c24be53">

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.7.3

### What was the last working version of Home Assistant Core?

Home Assistant 2023.7.3

### In which browser are you experiencing the issue with?

Safari 16.6

### Which operating system are you using to run this browser?

macOS Ventura 13.5

**Comment by karwosts** [comment]
This is not a frontend issue, please file an issue in home-assistant/core so that the developers for the integration that provides this sensor can look into this.
