### ISSUE TITLE
Energy Dashboard rendering issue on Firefox 116.0

### ISSUE THREAD

**Issue by tomlut** [home-assistant/frontend#17458]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After updating to Firefox 116.0 the Energy dashboard bar graph renders incorrectly:

![Screenshot 2023-08-02 at 18-57-49 Energy – Home Assistant](https://github.com/home-assistant/frontend/assets/10679300/2653054d-ee46-4821-b4d6-d8321d5a8050)

### Describe the behavior you expected

Nice square bars without the top left teardrop on each column. 

### Steps to reproduce the issue

1. Update to Firefox 116.0
2. Open the energy dashboard
...

### What version of Home Assistant Core has the issue?

2023.7.3

### In which browser are you experiencing the issue with?

Firefox 116.0 (64bit)

### Which operating system are you using to run this browser?

Windows 10

### Additional information

Only affects Firefox. Safari and Edge are not affected.

**Comment by lordwizzard** [comment]
I just updated to FF 116.0 and have the same issue on my Windows 10 Pro 22H2 build 19045.3208 desktop PC

## System Information

version | core-2023.8.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1331
Downloaded Repositories | 13
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 1833.7 GB
disk_used | 6.5 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.1), Samba share (10.0.2), File editor (5.6.0), Node-RED (14.4.3), eWeLink Smart Home (1.4.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 7
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 27, 2023 at 12:51 AM
-- | --
current_recorder_run | August 3, 2023 at 12:09 PM
estimated_db_size | 468.64 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.2 (2ad1cd7)
-- | --
cloud_online | 9 / 9
local_online | 9 / 9
debug | failed to load: 

</details>

**Comment by tomlut** [comment]
Mozilla have fixed this, 

https://bugzilla.mozilla.org/show_bug.cgi?id=1846613
