### ISSUE TITLE
Updating the device failed

### ISSUE THREAD

**Issue by tjorim** [home-assistant/frontend#17460]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Trying to change the area of a disabled device I get the following popup:
`not a valid value for dictionary value @ data['disabled_by']. Got 'config_entry'`.

### Describe the behavior you expected

Allow me to change the area of a device, even if currently disabled (or don't allow me to try and change it).

### Steps to reproduce the issue

1. Go to your settings
2. Find a device of a disabled integration
3. Click on the pencil icon in the top right corner
4. Fill in an area and click update
...

### What version of Home Assistant Core has the issue?

core-2023.8.0b4

### In which browser are you experiencing the issue with?

Edge 113

### Which operating system are you using to run this browser?

Windows 11

### Javascript errors shown in your browser console/inspector

Nothing in browser but got this in HA logs:

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:208
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:37:31 (2 occurrences)
Last logged: 12:37:45

[546962383040] Error handling message: not a valid value for dictionary value @ data['disabled_by']. Got 'config_entry' (invalid_format) Jorim Tielemans from 127.0.0.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.57)
```

### Additional information

Got redirected from https://github.com/home-assistant/core/issues/97610.
Issue does not appear to happen with all disabled devices, only devices of disabled integrations.

**Comment by tjorim** [comment]
<img width="722" alt="Screenshot 2023-08-02 130349" src="https://github.com/home-assistant/frontend/assets/1294876/417297c6-355a-4c44-87b3-6f5c2b27bc53">

**Comment by karwosts** [comment]
I think this is a simple fix, and once made doesn't seem like there should be any problem changing the name or area when the device is disabled. 

PR #17464 has the fix.
