### ISSUE TITLE
Sensibo Integration not loading

### ISSUE THREAD

**Issue by drmjuae** [home-assistant/frontend#17471]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Sensibo Integration is not working for more than three months.

### Describe the behavior you expected

`Logger: homeassistant.components.sensibo
Source: components/sensibo/coordinator.py:49
Integration: Sensibo (documentation, issues)
First occurred: 2:22:23 PM (33 occurrences)
Last logged: 2:58:56 PM

Unexpected error fetching sensibo data: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensibo/coordinator.py", line 49, in _async_update_data
    data = await self.client.async_get_devices_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pysensibo/__init__.py", line 113, in async_get_devices_data
    hvac_modes = list(capabilities.get("modes", []))
                      ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
`

### Steps to reproduce the issue

I have updated to the latest available Home Assistant version. 
I have cleared the cache of my browser. 
I have tried a different browser to see if it is related to my browser.
I have removed the integration and installed it again.
I have tried manual installation for Sensibo.
I have removed the old API key and got a new one (three times)

### What version of Home Assistant Core has the issue?

Home Assistant 2023.8.0

### In which browser are you experiencing the issue with?

FireFox and Edge

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment]
This is not a frontend issue, please file this ticket in home-assistant/core instead.

https://github.com/home-assistant/core/issues
