### ISSUE TITLE
Standard precision not working correctly

### ISSUE THREAD

**Issue by eikowagenknecht** [home-assistant/frontend#17487]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![image](https://github.com/home-assistant/frontend/assets/1475672/c9cb6ce7-6a53-487c-8a2a-5a376b41181a)

Selecting Standard with a preview of "whole numbers only" leads to

![image](https://github.com/home-assistant/frontend/assets/1475672/bac87df9-375e-48b2-aa41-0dc9e4d78a19)

Selecting the precision manually

![image](https://github.com/home-assistant/frontend/assets/1475672/528ffaa5-90f0-4960-a9a7-d9e15041d9be)

works fine:

![image](https://github.com/home-assistant/frontend/assets/1475672/385c4b92-7e05-4aab-b9b9-a1c429c71a3e)

### Describe the behavior you expected

Either "Standard" text sould reflect the precision of 1 digit or the cards should show 0 digits when Standard is selected.

### Steps to reproduce the issue

1. View entity with default precision of 0
2. See that it is not reflected correctly in views
3. Change precision to 0 (manually) and see that it now works
...

### What version of Home Assistant Core has the issue?

core-2023.8.0

**Comment by ildar170975** [comment]
Not sure if it is related or not - but here is my test:

Sensor:
![image](https://github.com/home-assistant/frontend/assets/71872483/58b6e40e-09e5-442b-9ac0-084b57fc8391)

more-info:
![image](https://github.com/home-assistant/frontend/assets/71872483/a3b81bbb-96b4-46f0-85b5-e7017602e623)

Settings - note the "Default" setting:
![image](https://github.com/home-assistant/frontend/assets/71872483/b4791885-e2e6-4f6f-873b-fe08a67f1f82)

User settings:
![image](https://github.com/home-assistant/frontend/assets/71872483/6cc371ff-f0f1-4265-a29c-7d6b4427ee51)

**Comment by karwosts** [comment]
> I guess that "Default" setting should conform to "exact value stored for the entity".

Yeah looks like there is a subtle bug that cause the default value to be truncated in this picker (will try to fix that). Though I'm not sure yet if that's OPs issue, which seems maybe different.

**Comment by ildar170975** [comment]
@karwosts 
Shall I register a separate issue to avoid mixing things?

**Comment by karwosts** [comment]
For now I'll say you don't need to bother (unless you really want to for some reason).

**Comment by ildar170975** [comment]
My only intention is to eliminate a thing which looks like a bug...
I myself do not use precision settings at all.

**Comment by karwosts** [comment]
> 



> My only intention is to eliminate a thing which looks like a bug...
> I myself do not use precision settings at all.

#17491 is the fix for your issue.

**Comment by karwosts** [comment]
Ok I checked again and confirmed the PR fixes both of these bugs (they are the same root cause). 

Thanks guys, nothing further is needed.
