### ISSUE TITLE
Input_number View Reverting to Box View on Post Request with REST API

### ISSUE THREAD

**Issue by mishave** [home-assistant/frontend#17483]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When attempting to update the value of an input_number through a POST request using the REST API, the view unexpectedly changes from a slider view to a box view.

Here is the Python function where the issue is observed:
```
def set_input_number(state_id, state):
    url = f"http://127.0.0.1:8123/api/states/{state_id}"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {auth_token}"
    }
    data = {
        "state": state,
        "min": 0,
        "max": 100,
        "mode": "slider"
    }
    response = requests.post(url, headers=headers, data=json.dumps(data))
    return response.json()
```

Attempts to resolve this issue, such as adding min and max attributes to the request data, have not been successful.

### Describe the behavior you expected

When calling this function, I expect the mode to be set to slider. However, the view reverts to box view even after explicitly setting the mode to slider.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.6.3

### Which operating system are you using to run this browser?

Debian version: 11 (bullseye)

**Comment by karwosts** [comment]
Try this:

```
    data = {
        "state": state,
        "attributes": {
          "min": 0,
          "max": 100,
          "mode": "slider"
        }
    }
 ```

**Comment by mishave** [comment]
@karwosts, unfortunately no good still. Reverts back to box view when called.

**Comment by karwosts** [comment]
Please show or screenshot the state and attributes of your entity from developer tools both before and after you make that API call.

**Comment by mishave** [comment]
Sorry @karwosts was correct; I had not nested it within attributes:

        data = {
            "state": str(state),
            "attributes": {
            "mode": "slider",
            "min": 0,
            "max": 100,
            "step": 1,
            "unit_of_measurement": "Percent",
            "icon": "mdi:fan"
            }
        }
