### ISSUE TITLE
Unable to remove unavailable entity from scene

### ISSUE THREAD

**Issue by joostlek** [home-assistant/frontend#17495]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I was testing something for https://github.com/home-assistant/core/issues/97828 on my production environment and I added an automation to my scene as an entity. After I could reproduce his issue, I deleted the automation first, and then opened the scene.

In the scene, an empty list is visible.
![image](https://github.com/home-assistant/frontend/assets/7083755/406578a4-f2b5-4b96-9479-224055a4eaac)

Everytime I now open the scene I get a log message saying that the scene is unable to find the automation, which is true.

### Describe the behavior you expected

I would expect that I would have a way to delete this removed entity from the scene.

### Steps to reproduce the issue

1. Create automation
2. Create scene
3. Put automation in scene
4. Delete automation
5. Open scene
6. Profit

### What version of Home Assistant Core has the issue?

2023.8

### In which browser are you experiencing the issue with?

Firefox 116 and Edge (not sure which version)

**Comment by karwosts** [comment]
Not sure exactly what the correct behavior should be, though I'll note that if you modify the scene in some way (like add an entity) and save it, all deleted entities seem to automatically get pruned out.

**Comment by joostlek** [comment]
What about enabling the save button and a notice saying something like "If you press save, these entities will be removed from the scene as they don't exist anymore"?

**Comment by joostlek** [comment]
Still an issue

**Comment by joostlek** [comment]
Still an issue (maybe when I have time I'll dive in it)
