### ISSUE TITLE
UI Mode requires hyphens in "List of options"!

### ISSUE THREAD

**Issue by kerryland** [home-assistant/frontend#17512]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

UI Mode is supposed to be "easy mode", yet HA (and I) get horribly confused if options are not preceded with hyphens. 

Hyphens in this UI element make no sense:

![image](https://github.com/home-assistant/frontend/assets/398113/c4e1b688-e52d-4932-b4af-e0840d3adb0d)

This is what should work, but doesn't:

![image](https://github.com/home-assistant/frontend/assets/398113/aa77d06b-2549-4105-9c12-40126045c8ed)

Even worse, it doesn't produce any error, it just generates unexpected YAML
```
  options: Item A Item B Item C
```

### Describe the behavior you expected

I expect to be able to define a list without prefixing each item in the list with a hyphen.

Alternatively, if it's too hard, put some words on the screen telling the user to add hyphens because there is no way they are going to guess that it's required :-)

### Steps to reproduce the issue

1. Visit the Dev Tool, Service test page at `/developer-tools/service` (or define an Automation)
2. Select "Input select: Set options" service (in UI Mode)
3. Type values into the "Options" field as shown above.
4. Click "GO TO YAML MODE"
5. See the underlying YAML list is not desirable.

```
service: input_select.set_options
data:
  options: Item A Item B Item C
```

### What version of Home Assistant Core has the issue?

 Home Assistant 2023.8.1 Supervisor 2023.07.1 Frontend 20230802.0 - latest 

### In which browser are you experiencing the issue with?

Firefox 115.0.3 and Chrome 115.0.5790.111

### Which operating system are you using to run this browser?

Windows 10

**Comment by Xitee1** [comment]
This also confused me at the beginning. Now I've got used to it but for new users it's inconvenient to find the issue because everything appears to be correct.

**Comment by karwosts** [comment]
The field is yaml, so yes a list will require hyphens, and I don't think we can change that. 

However I am sympathetic to your confusion, so I proposed a PR adding a button to the object selector that allows it to fill example data, to hopefully better teach users how to fill out these selectors.

**Comment by kerryland** [comment]
How could an end user know that the field requires yaml? Some kind of visual indicator would be great.

>  I don't think we can change that.

This is software, you can change anything :-)

**Comment by karwosts** [comment]
> How could an end user know that the field requires yaml?

Well if you click the question mark in the dialog it will take you to the page where examples are given. But yes I agree with you that some more help would be helpful, which is why I linked that pull request with the example data.  

I didn't have any further ideas for ways to better educate the user, I would hope that is sufficient.

**Comment by kerryland** [comment]
I think that UI mode should be simple-mode. If the user wants to enter yaml then they should be in yaml mode. 

Random fields that arbitrarily require use of yaml for no obvious reason make no sense in UI mode, so don't offer them.
