### ISSUE TITLE
Can't scroll more info popups

### ISSUE THREAD

**Issue by martinj27** [home-assistant/frontend#17513]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On the more info popups for entities, there is no way to scroll to the bottom, this makes it impossible to edit entities on mobile devices 
(The same issue exists on the android companion app, and on Firefox and chrome on windows)

### Describe the behavior you expected

When clicking an entity and clicking either attributes or edit, there should be a way to scroll to the bottom to apply settings or view all the attributes 

### Steps to reproduce the issue

1. click an entity on a dashboard 
2. Click something that will make the popup longer (such as attributes or the cog on the top right to edit)
3. Try to scroll
...

### What version of Home Assistant Core has the issue?

2023.8.1

### In which browser are you experiencing the issue with?

all browsers, including the companion app

### Which operating system are you using to run this browser?

Android, Windows 11/10

**Comment by karwosts** [comment]
I don't have any problem scrolling. Can you show a screenshot of what you're looking at exactly?

![more-scroll](https://github.com/home-assistant/frontend/assets/32912880/120a2079-d2fd-4c94-a7d8-7b7f837c761e)

**Comment by martinj27** [comment]
I noticed that on windows, if the pop up is full screen, then I can't scroll at all, but if the popup is smaller, then the logbook can scroll.

No matter what, I can't scroll the settings
(I tried a clean install of a previous version and had the same issue also, I can try it again tonight with the latest version of ho.e assistant)

![Screenshot_20230807_180005_Microsoft Remote Desktop](https://github.com/home-assistant/frontend/assets/116453595/b588ed0c-888b-42f6-9747-decd71d8b5c2)
![Screenshot_20230807_175948_Microsoft Remote Desktop](https://github.com/home-assistant/frontend/assets/116453595/a3cab71a-8374-41dc-b721-95f900086f6b)
![Screenshot_20230807_175922_Microsoft Remote Desktop](https://github.com/home-assistant/frontend/assets/116453595/8befc981-1ccb-4bc9-adf0-9d2727291937)
![Screenshot_20230807_175613_Microsoft Remote Desktop](https://github.com/home-assistant/frontend/assets/116453595/3e88e410-3d8a-4b7b-a642-b1b1b451a1d1)
![Screenshot_20230807_173148_Home Assistant](https://github.com/home-assistant/frontend/assets/116453595/4775cb72-e3e8-4238-94d1-6e39f6de6103)
![Screenshot_20230807_173109_Home Assistant](https://github.com/home-assistant/frontend/assets/116453595/99ed4dfb-7661-4ede-a678-9e28fea19b5f)

**Comment by karwosts** [comment]
Are you using some kind of mods? Your screenshots look very different from how I expect stock HA to look, with the square corners and glowing halo effects.

**Comment by ildar170975** [comment]
@martinj27 
Please always test with a default theme first.

**Comment by martinj27** [comment]
Thanks, It works with other themes and the newest home assistant,
