### ISSUE TITLE
Dev Tools "CALL SERVICE" incorrectly disabled (but not actually disabled!)

### ISSUE THREAD

**Issue by kerryland** [home-assistant/frontend#17511]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using the Developer Service Tool I found that HA would not enable the "CALL SERVICE" button for valid YAML containing a template.

I think the "The UI does not support templates, you can still use the YAML editor" logic that disables the "GO TO UI MODE" button might be disabling the "CALL SERVICE" button by mistake.

### Describe the behavior you expected

I expect to be able to click the button when the code provided is valid. I would actually expect to always be able to click the button, even when it's not valid, because then I might get some useful feedback about what's wrong with it.

### Steps to reproduce the issue

Enter this code into the Developer Tools Service tester at `/developer-tools/service`
```
service: input_select.set_options
target:
  entity_id: input_select.skytv_channels
data_template:
  options: >
    [
    {%- for value in state_attr('input_select.skytv_source_list', 'options') -%}
      {% set elements = value.split('|') %}
      "{{ elements[1] }}",
    {%- endfor %}
    ]
```

See that there's an apparently disabled button, but that can actually still be clicked:

![image](https://github.com/home-assistant/frontend/assets/398113/beef90d8-7f50-437b-893c-58a93defd0f8)

### What version of Home Assistant Core has the issue?

Home Assistant 2023.8.1 Supervisor 2023.07.1 Frontend 20230802.0 - latest

### In which browser are you experiencing the issue with?

Firefox 115.0.3 and Chrome 115.0.5790.111

### Which operating system are you using to run this browser?

Windows 10

**Comment by kerryland** [comment]
I was also misled/confused by the wording of "The UI does not support templates, you can still use the YAML editor" because I know I am using the UI (because I'm not editing a configuration file). I wonder what is "the YAML editor"? I guess it's not the thing thing already on the screen because why would HA be telling me to use that if I already am using it? Perhaps it's something else, somewhere else?

I propose changing the wording to use terminology consistent with the other labels:

"UI Mode does not support templates, please use YAML Mode instead"

**Comment by karwosts** [comment]
Just for your reference the button is disabled because it is expecting a `data:` section, not `data_template:`

But yes I agree overall that some better error exposition and handling would be nice here.

**Comment by kerryland** [comment]
Huh. Thank you. 

I dug around a bit more and realised that the developer tool doesn't give *any* message for mildly invalid yaml. Given the following...
```
service: input_select.set_options
target:
  entity_id: input_select.skytv_channels
  wibble: 17
```
... the developer tool gives no message at all -- it just "disables" the **CALL SERVICE** button and leaves the user to guess at the problem :-(

The Automation editor, in contrast, is much more useful for both simple errors and the use of `data_template`:

![image](https://github.com/home-assistant/frontend/assets/398113/5245ee6a-47f0-48ea-af8d-9de7e19d9d19)

So I suggest...
1. Changing the `data_template`-specific error message to _"UI Mode does not support `data_template`, please use YAML Mode, or use `data:` instead"_
1. Adding a generic error message, like the automation editor's _"Key 'target.wibble' is not expected or not supported by the visual editor."_, or perhaps  _"UI Mode does not expect or support `target.wibble`, please use YAML Mode"_
