### ISSUE TITLE
Statistics graph card: nice & useful "fill" is not displayed when "mean" is not displayed

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#17517]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Consider this card:

![image](https://github.com/home-assistant/frontend/assets/71872483/b0102d04-f893-4d97-af9b-0c5f44c49194)

Look at this fill between MAX & MIN lines - they define an area of possible values.
Displaying this area is very USEFUL.

And let's not display MEAN values:

![image](https://github.com/home-assistant/frontend/assets/71872483/5d89d5b5-3811-4ac3-bca3-fc46e858a53f)

Here there is no fill.

May be this is not a bug, may be this is done intentionally.
IMHO this fill should be displayed always when both MIN & MAX are selected. 

```
chart_type: line
period: hour
type: statistics-graph
entities:
  - sensor.processor_use
stat_types:
  - min
  - max
  - mean
days_to_show: 1
```

### Describe the behavior you expected

Fill is displayed when MAX & MIN are selected.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.8.0

### In which browser are you experiencing the issue with?

Chrome 115.0.5790.171 

### Which operating system are you using to run this browser?

Win10

**Comment by karwosts** [comment]
PR created.
