### ISSUE TITLE
Picture glance live video card pauses audio on whatever device it is playing on, even if the audio is muted.

### ISSUE THREAD

**Issue by SpartanTech** [home-assistant/frontend#17516]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

It started happening sometime last year. Major glance worked fine before with live camera view. Now if any video stream has an audio stream, picture glass is designed to automatically mute the stream.

The problem is that even muted, it is still sending a signal to whatever device home assistant is running on to mute whatever audio is playing. (Home assistant app has this issue running on three devices: a kiosk, a fire tablet, Android device, and iPhone device,). If those units have audio playing already such as background music a background video, or for businesses business music, camera streams mute the device audio.

If you disable the audio stream entirely before it comes into the picture glance, there is no issue.

### Describe the behavior you expected

Picture glad should only turn off device audio if the camera audio is not needed, being that picture glance automatically mutes audio, no pause should happen.

Seems like an easy bug but do not know where to look. The only case with that it works correctly is opening the web page for home assistant on a Windows desktop using chrome. But then again, that might be Chrome not allowing device audio to be muted, I don't think I've ever seen a website that mutes my computer's audio

### Steps to reproduce the issue

1. Host a camera stream either using generic IP or frigate
2. Play audio on the background on your device
3. Once the camera stream is added to home assistant, add the camera to the picture glance card with live option selected
4. Other dashboards work fine, switching to the dashboard with the picture glance card causes your devices audio that's playing in the background to stop
5. You can go through the hassle of resuming your device audio, and everything works like normal.
...

### What version of Home Assistant Core has the issue?

2023.8

### What was the last working version of Home Assistant Core?

2022x

### In which browser are you experiencing the issue with?

Native app

### Which operating system are you using to run this browser?

Android and ios

**Comment by Kamamatoshy** [comment]
So show ne how I'm do far behind
