### ISSUE TITLE
Empty integration configuration popup

### ISSUE THREAD

**Issue by revolter** [home-assistant/frontend#17526]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The configuration popup of the Roborock and Dyson integrations get empty after the first step, and some errors are getting logged:

<img width="449" alt="image" src="https://github.com/home-assistant/frontend/assets/5748627/ced8be7c-7764-43af-a26f-185a5ed1395a">

```html
<ha-dialog open="" scrimclickaction="" escapekeyaction="" hideactions="">
    <div>
        <!--?lit$076773918$-->
        <div class="dialog-actions">
            <!--?lit$076773918$--> <a target="_blank" rel="noreferrer noopener" href="https://www.home-assistant.io/integrations/roborock">
                <ha-icon-button> </ha-icon-button>
            </a>
            <ha-icon-button dialogaction="close"></ha-icon-button>
        </div>
        <!--?lit$076773918$-->
        <step-flow-abort></step-flow-abort>
    </div>
</ha-dialog>
```

### Describe the behavior you expected

The configuration popups should show some form.

### Steps to reproduce the issue

1. Open http://homeassistant.local:8123/config/integrations/dashboard
2. Click `+ ADD INTEGRATION`
3. Search and select Roborock (the Dyson one requires more steps, and the HACS, but it seems to be the same issue)
4. Enter the email address
5. Click `SUBMIT`

### What version of Home Assistant Core has the issue?

Doesn't exist

### In which browser are you experiencing the issue with?

Safari 16.5 (18615.2.9.11.4) and Google Chrome 115.0.5790.170 (Official Build) (arm64)

### Which operating system are you using to run this browser?

macOS Ventura 13.4 (22F66)

### Javascript errors shown in your browser console/inspector

```txt
None
```

### Additional information

Errors from http://homeassistant.local:8123/config/logs:
- `Home Assistant Core`:
  ```
  Logger: frontend.js.latest.202308020
  Source: components/system_log/__init__.py:270 
  First occurred: 19:52:36 (1 occurrences) 
  Last logged: 19:52:36

  :0:0 Script error.
  ```
- `LOAD FULL LOGS`:
  ```
  2023-08-08 19:52:36.501 ERROR (MainThread) [frontend.js.latest.202308020] :0:0 Script   error.
  ```

Screenshot from [Settings -> About](https://my.home-assistant.io/redirect/info/) showing that there is no "Home Assistant Core" version, nor "core-*" value:

<img width="634" alt="image" src="https://github.com/home-assistant/frontend/assets/5748627/381ea9bf-2118-4d8d-95c0-956dfde850e9">

**Comment by karwosts** [comment]
This is somewhat difficult to triage as it requires a valid roborock account to get past the email form. 

If you had a dummy account that you could share that could get past that, it might help the process.

**Comment by revolter** [comment]
There's definitely something wrong with my setup, so, please let me know if I can "proxy debug" this for you, however advanced the steps are.

Regarding an account, here it is:

<details>
<summary>Account</summary>

- email: `drove.07-astray@icloud.com`
- password: `zocmuF-5hu&cso`

</details>

But I think that some time needs to pass until it gets discovered via the integration's API.

**Comment by karwosts** [comment]
I got the account info, I'll check later. For now it's telling me there's not an account associated with the email.

**Comment by revolter** [comment]
I tried it again, and now it finds the account and the issue gets reproduced.

**Comment by karwosts** [comment]
You're trying the roborock core integration? (not from HACS or anything?)

Every time I try with the initial email you posted I get:

"There is no account associated with the email you entered, please try again."

**Comment by revolter** [comment]
Yes. Even now it gives you that error?

**Comment by karwosts** [comment]
Yeah, first I start here:

![image](https://github.com/home-assistant/frontend/assets/32912880/62164d32-4767-4793-94fc-eea8b92f88f1)

Then I put in the icloud email address, then I get this:

![image](https://github.com/home-assistant/frontend/assets/32912880/d74f072e-3016-4e61-a7c7-848c82c79e82)

**Comment by karwosts** [comment]
Not helpful for a solution, but sounds similar to #17331

**Comment by BEFH** [comment]
I don't think this is just you. I initially had this issue just with thermostats, and I made a completely new HA install. Now it's doing it with all of my Zigbee lights.

https://github.com/georgezhao2010/midea_ac_lan/issues/315
