### ISSUE TITLE
Binary sensor with device class "power" shows wrong value format

### ISSUE THREAD

**Issue by Xitee1** [home-assistant/frontend#17522]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After upgrading to 2023.8.1 the text for binary sensors with device class "power" has been changed from On/Off to Detected/Normal (like motion sensors). That does not make much sense in my use-case. 
This is also the case for the german translation (Shows Erkannt/Normal instead of Ein/Aus).

```yaml
  binary_sensor:
    - name: "Pool - Heizung (Status)"
      device_class: "power"
      state: >
        {{ states('switch.pool_heizung') }}
```

![chrome_aJ4wXIDea4](https://github.com/home-assistant/frontend/assets/59659167/22afc168-c930-4103-a334-f2eace89c7a0)
![chrome_BrhPaZljtI](https://github.com/home-assistant/frontend/assets/59659167/2de59988-f3b6-4be0-803a-cdeeea68cd70)
Entity name in english: `Pool - Heater (State)`

### Describe the behavior you expected

It still shows On/Off after updating.

### Steps to reproduce the issue

1. Have a binary sensor of device class "power"
2. Update from 2023.7.3 to 2023.8.1

### What version of Home Assistant Core has the issue?

core-2023.8.1

### What was the last working version of Home Assistant Core?

core-2023.7.3

### State of relevant entities

```txt
State:
`on`

Attribute:

device_class: power
friendly_name: Pool - Heizung (Status)
```
```


### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

**Comment by karwosts** [comment]
This comes from core, specifically this recent PR:

https://github.com/home-assistant/core/pull/97084/files

Go ahead and file an issue in /core/ if you want this fixed, I don't think there's anything frontend can do.

**Comment by karwosts** [comment]
Ah I see it is already reported and it is being worked. In that case I think this can close as duplicate. 

Go ahead and follow the core issue for further updates:

https://github.com/home-assistant/core/issues/97783
