### ISSUE TITLE
Frontend should use accent color instead of primary color for form elements

### ISSUE THREAD

**Issue by asvacc** [home-assistant/frontend#17534]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The form controls should use the accent color provided, not the primary color. Light colors are not visible on light themes, same for dark.

### Describe the behavior you expected

Form controls use the accent color to be visible for all themes.

### Steps to reproduce the issue

1. Change primary theme color to white on a light background or black on a dark background.

### What version of Home Assistant Core has the issue?

core-2023.5.2

### Additional information

<img width="438" alt="Screenshot 2023-08-09 094430" src="https://github.com/home-assistant/frontend/assets/7175056/b200ee24-a441-466b-ae86-366367db3b30">

**Comment by karwosts** [comment]
> Change primary theme color to white on a light background or black on a dark background.

I'm confused, why would you do this?
