### ISSUE TITLE
msg mqtt 

### ISSUE THREAD

**Issue by responde** [home-assistant/frontend#17557]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

in log  this msg
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:405
Integration: Sensor (documentation, issues)
First occurred: 01:50:10 (5 occurrences)
Last logged: 02:15:10

Entity sensor.qsupply from integration mqtt has state class total_increasing, but its state is not strictly increasing. Triggered by state 189.8 (191.6) with last_updated set to 2023-08-11T23:47:47.180411+00:00. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
Entity sensor.sconsume from integration mqtt has state class total_increasing, but its state is not strictly increasing. Triggered by state 305.1 (315.0) with last_updated set to 2023-08-11T23:48:47.180277+00:00. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
Entity sensor.q1supply from integration mqtt has state class total_increasing, but its state is not strictly increasing. Triggered by state 189.8 (191.6) with last_updated set to 2023-08-11T23:47:47.205598+00:00. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
Entity sensor.s1consume from integration mqtt has state class total_increasing, but its state is not strictly increasing. Triggered by state 305.1 (315.0) with last_updated set to 2023-08-11T23:48:47.204979+00:00. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
Entity sensor.i1 from integration mqtt has state class total_increasing, but its state is not strictly increasing. Triggered by state 1.3 (1.4) with last_updated set to 2023-08-12T00:10:21.981628+00:00. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22

### Describe the behavior you expected

Advertence in log

### Steps to reproduce the issue

1.
2.
3.
...
mqtt, sma component

### What version of Home Assistant Core has the issue?

Home Assistant 2023.8.2

### What was the last working version of Home Assistant Core?

Home Assistant 2023.8.2

### In which browser are you experiencing the issue with?

chrome, firefox

### Which operating system are you using to run this browser?

windows 11

### State of relevant entities

```txt
no
```

### Problem-relevant frontend configuration

```yaml
no, is primer problem report
```

### Javascript errors shown in your browser console/inspector

```txt
no, is primer problem report
```

### Additional information

no, is primer problem report

**Comment by karwosts** [comment]
This is not a frontend issue. If anything it is home-assistant/core, but you seem to just have a sensor wrongly configured.
