### ISSUE TITLE
querying openstreetmap fails in Firefox

### ISSUE THREAD

**Issue by butonic** [home-assistant/frontend#17565]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I tried installing home assistant with firefox, but it gave me a CORS error. The code is trying to send a custom user-agent, which is prevented by the CORS headers. Strangely enough it worked with edge. I'm still opening this because in edge thge User-Agend header that actually got sent was unchanged from the browsers default. Firefox did change it to homassistant/something IIRC

I have to reproduce this from memory, so I cant give the exact URLs or User Agents, but I hope this is reproducible.

### Describe the behavior you expected

A successful request

### Steps to reproduce the issue

1. Try to install with Firefox. I used https://github.com/home-assistant/operating-system/releases/download/10.4/haos_odroid-xu4-10.4.img.xz
2. during onboarding search for a location on the openstreetmap
3. See an error in the UI and find the CORS error in the console.

### What version of Home Assistant Core has the issue?

Home Assistant 2023.8.2

### In which browser are you experiencing the issue with?

Firefox 116.0.2 (64-Bit)

### Which operating system are you using to run this browser?

Windows 11 Pro Insider Preview 23H2

**Comment by der-eismann** [comment]
I just reproduced this issue and for some reason it disappeared, after I disabled my adblocker uBlock Origin for the localhost address. Not sure why this is causing issues in Firefox only and not in Chrome for me. Do you have an adblocker enabled?
