### ISSUE TITLE
Timezone offset missing/wrong in developer tools / automation timeline etc.

### ISSUE THREAD

**Issue by Laho812** [home-assistant/frontend#17588]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the developer tools the time stamps of sun.sun are displayed with an offset of +00:00

![grafik](https://github.com/home-assistant/frontend/assets/119891233/e8613842-585f-4761-97b8-aef9dc60d444)

### Describe the behavior you expected

The offset should equal the timezones offset, in my case +02:00 (CEST).

### Steps to reproduce the issue

1. Select a different timezone than UTC
2. Set the home zone to a location in a different timezone than UTC
3. Go to developer tools and search for sun.sun
...

### What version of Home Assistant Core has the issue?

2023.08.02

### In which browser are you experiencing the issue with?

Firefox 116.0.2

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
entity: sun.sun
attributes:
next_dawn: 2023-08-16T03:32:47.262098+00:00
next_dusk: 2023-08-16T19:20:16.106725+00:00
next_midnight: 2023-08-15T23:27:10+00:00
next_noon: 2023-08-16T11:27:14+00:00
next_rising: 2023-08-16T04:10:19.423114+00:00
next_setting: 2023-08-16T18:42:57.235936+00:00
elevation: -18.45
azimuth: 323
rising: false
friendly_name: Sun
```

### Additional information

In automation traces it is very hard to figure out if the sun.sun condition worked correctly or not.
I just made a quick test:
- My timezone is CEST (UTC+02:00)
- The expected time for sunrise of the "home" zone is 06:11 (CEST) or 04:11+02:00
- The expecred time for sunset of the "home" zone is 20:42 (CEST) or 18:42+02:00
- The condition is before sunrise (06:11 CEST) or after sunset (20:42 CEST) with 3h offset = 23:42 CEST
- The triggered time is 22:55 (CEST)

**Expectation:** 
The condition is not fulfilled, so the action must not be executed, despite the fact the wanted_time_after is '2023-08-15T21:44:52.021012+00:00 which is before the trigger time (22:55 CEST).
![grafik](https://github.com/home-assistant/core/assets/119891233/35f5361f-85bb-43c9-911b-8ede6070bcf6)

**Result:**
 -> The timezone specific offset of the UTC time stamp seems to be wrong (+00:00 but must be +02:00).

**Comment by tdejneka** [comment]
Home Assistant stores datetime objects in ISO format using UTC timezone.

---

> the wanted_time_after is '2023-08-15T21:44:52.021012+00:00 which is before the trigger time (22:55 CEST).

`wanted_time_after` is `2023-08-15T21:44:52.021012+00:00` or 23:44:52 CEST. That means the time at which the automation executed must be after that time in order for the Sun Condition to be `true`.

According to the screenshot's trace, the automation executed at 22:55:25 CEST on August 15th. That's _before_ 23:44:52 CEST and so the Sun Condition evaluated to `false`.
