### ISSUE TITLE
Lighting Groups Not Being Detected By Scene UI

### ISSUE THREAD

**Issue by marshalltech81** [home-assistant/frontend#17599]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have defined a Lighting Group in the UI.  I want that Lighting Group as a basis for a Scene in the UI.  When I go to "Settings > Automations & Scenes > Scenes > Add Scenes" and try to define a Scene using the Lighting Group, the scene is only allowing me to use Devices and not the Lighting Groups defined by those devices.  This seems to be a bug.  

### Describe the behavior you expected

I would expect to be able to define a Scene in the UI using a Lighting Group.  

### Steps to reproduce the issue

1. Define a Lighting Group in the UI
2. Navigate to Settings > Automations & Scenes > Scenes > Add Scenes"
3. Attempt to Create a Scene Using the Lighting Group in 1
4. Lighting Group does not appear

### What version of Home Assistant Core has the issue?

2023.8.2

### In which browser are you experiencing the issue with?

Brave 1.26.20

### Which operating system are you using to run this browser?

macOS Ventura 13.4.1

**Comment by karwosts** [comment]
Light groups are entities, not devices. Did you look under "Add an entity" instead of "Add a device"?

My light groups appear there.

**Comment by marshalltech81** [comment]
<img width="1182" alt="Screenshot 2023-08-16 at 2 16 56 PM" src="https://github.com/home-assistant/frontend/assets/68938002/27f74d1e-36a6-4504-a278-7d7da339b918">

**Comment by marshalltech81** [comment]
The only option I get on "Add Scene" is to "Add a device" until there is something fundamental I am misunderstanding.  I guess I understand that there is a different between Lighting Groups as Entities and Lights as Devices but I figured that a Scene should be able to control both.

**Comment by karwosts** [comment]
Ah, yes now I recall that individual entities is hidden behind "advanced mode". If you go to your profile settings and enable advanced mode you should see it:

![image](https://github.com/home-assistant/frontend/assets/32912880/29ecd6c3-2c2f-4db0-87b9-348ee54e6685)

**Comment by marshalltech81** [comment]
That did it @karwosts, thank you!  I guess my question would be is there a fundamental assumption that lighting groups should be able to be controlled outside of an advanced mode?

**Comment by karwosts** [comment]
Admittedly the distinction for advanced mode is somewhat arbitrary, it just tries to hide some of the more complex concepts from beginners who won't understand them. 

Light groups are definitely not devices, so it doesn't make sense for them to appear in the device picker. 

I'm not sure when it was decided entities for scenes were advanced, but I don't have a strong opinion to agree or disagree with that decision. If you want to pursue it further maybe this could be moved or recreated as a discussion topic, as it's not really a bug.

**Comment by marshalltech81** [comment]
Thank you again @karwosts !
