### ISSUE TITLE
Z-Wave (Zooz 800) Firmware update succeeded, but reported as failed.

### ISSUE THREAD

**Issue by Darkknight33** [home-assistant/frontend#17605]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When updating the Zooz ZST39LR from 1.10 to 1.20 using the update feature in HA, it progresses normally to 100% then errors out with:

![image](https://github.com/home-assistant/frontend/assets/571187/e8eaf15e-7bef-488c-9cf2-a954e2683071)

However, the update does succeed, as ZwaveJSUI & HA both report Firmware is now 1.20. I did notice *something* reset immediately after it reached 100%. I think there is a timing issue where HA asks for confirmation while the driver is restarting maybe? It took about 5-10 seconds for the driver to report it was ready and go to status 'Scan Completed' in ZwaveJSUI after it reached 100%. If a wait state is added for a status update of maybe 10 -30 seconds, before reporting a failure, it would probably resolve this issue. Otherwise, based on the feedback in the UI, a user might believe that the firmware update failed and try to re-apply it. Since updating firmware is generally speaking, risky, we don't want users to needlessly repeat this process. 

### Describe the behavior you expected

UI should have correctly reported that the update succeeded. 

### Steps to reproduce the issue

1. Use the update device feature to update Zooz 800 Zwave hub to 1.20
2. Wait for 100%
3. Receive error message
4. Verify that update did succeed anyhow
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.8.1

### In which browser are you experiencing the issue with?

Firefox 116.0.2

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
This probably needs to be a core issue for zwave-js, I don't think the frontend handles this logic, it just reports the status of the API call it sends to the backend.

**Comment by Darkknight33** [comment]
If the frontend reports a timeout because the Zwave-JS API is unresponsive due to restarting, then how would they fix it from their end?On Aug 17, 2023, at 8:24 AM, karwosts ***@***.***> wrote:﻿
This probably needs to be a core issue for zwave-js, I don't think the frontend handles this logic, it just reports the status of the API call it sends to the backend.

**Comment by karwosts** [comment]
Sorry, I should clarifiy I mean its an issue in home-assistant/core for zwavejs integration, not an issue in zwave-js itself. I realize my first statement could be ambiguous. 

Frontend reports timeout because backend(core) tells it to report a timeout.

**Comment by Darkknight33** [comment]
Do you think I should repost this in the backend or can someone move it?On Aug 17, 2023, at 10:36 AM, karwosts ***@***.***> wrote:﻿
Sorry, I should clarifiy I mean its an issue in home-assistant/core for zwavejs integration, not an issue in zwave-js itself. I realize my first statement could be ambiguous.
Frontend reports timeout because backend(core) tells it to report a timeout.

**Comment by karwosts** [comment]
Probably just open a new issue, they have a different set of questions they want to fill out on the form.
