### ISSUE TITLE
Settings: "theme" selector may disappear

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#17610]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Not sure if it is a bug or an intended behaviour.

1. Create a custom theme (may have any name and any one variable):
```
cm_test_minimal:
  mdc-checkbox-disabled-color: rgba(255,255,0,1)
```

2. Reload themes.

3. Check the user settings - the "Theme" selector is displayed:

![image](https://github.com/home-assistant/frontend/assets/71872483/44e5825b-10b0-4386-aea8-18c83d7d5b35)

4. Select the created custom theme:

![image](https://github.com/home-assistant/frontend/assets/71872483/0bea6dca-9c37-4b8f-8b49-4aed49c64515)

5. Comment the only "variable" line in the theme file:
```
cm_test_minimal:
  # mdc-checkbox-disabled-color: rgba(255,255,0,1)
```
6. Reload themes.

7. Check the user settings - the "Theme" selector is NOT displayed:

![image](https://github.com/home-assistant/frontend/assets/71872483/2cfb61e7-ab9f-4ebc-b987-c27781f6d1e6)

8. Uncomment that line, reload themes - see that the "Theme" selector is displayed again.
9. Select the "Default" theme.
10. Again comment that line, reload changes - see that the "Theme" selector is still displayed and the custom theme may be selected.
11. Reload the page - see that the "Theme" selector is disappeared again.

Seems that a theme w/o variables is considered as "invalid" and causing the "Theme" selector disappear.

### Describe the behavior you expected

The "Theme" selector is always visible.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.8.0

### In which browser are you experiencing the issue with?

Chrome 115.0.5790.173 

### Which operating system are you using to run this browser?

Win10

**Comment by karwosts** [comment]
Note that a theme with no keys is considered invalid. If you run config check it will return an error, and if you reboot it will not boot the frontend due to error. 

I wonder if perhaps this should be a core issue for frontend integration, and the call service should return an error as the frontend themes are not valid. Perhaps it should be validating the yaml before attempting to reload them.

**Comment by ildar170975** [comment]
> Note that a theme with no keys is considered invalid

Agreed. Then at least we should see an error when calling "reload themes" service.
Also, an error in Log could be helpful too.

**Comment by karwosts** [comment]
> Shall I register an issue in the Core?

Yeah I think so, that's where the service calls get handled. When it asks for "which integration url", provide https://www.home-assistant.io/integrations/frontend/ to make sure it gets tagged correctly.

**Comment by ildar170975** [comment]
Closing as related to Core then....
Will post here a related core issue later.

**Comment by ildar170975** [comment]
Created a core issue:
https://github.com/home-assistant/core/issues/98708
