### ISSUE TITLE
Mac mobile app opens on reboot rather than starting in the background

### ISSUE THREAD

**Issue by mikesalz** [home-assistant/frontend#17626]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Not sure if this is a bug or intended behavior.  Hopefully not intended because it doesn't make sense.

The Mac mobile app must be running in order to fire events to HA.  Logically, one would want it to run in the background.  The option (screen shot) for "Show App in... Menu Bar" seems to indicate that upon launch i would show only in the menu bar.  Yet every time I restart my computer, the HA app pops up.  Not a very good UX. 

![image](https://github.com/home-assistant/frontend/assets/46855061/dadf35bc-7881-4f68-8430-e10c949bce86)

### Describe the behavior you expected

I would expect the app to run only in the background upon computer restart.

### Steps to reproduce the issue

1. Restart your Mac
2. Get annoyed when the app opens after restart

### What version of Home Assistant Core has the issue?

2023.8.3

### Which operating system are you using to run this browser?

macOS Ventura 13.4.1 (c)

**Comment by karwosts** [comment]
As far as I'm aware this is not a frontend issue... is there a reason you wanted to open this when there was already an issue in iOS repo?

**Comment by mikesalz** [comment]
@karwosts My apologies.  At the time I opened this, I didn't realize there was a separate iOS repo.  I happened to find that later, and referenced this issue.

**Comment by karwosts** [comment]
No worries. I'll go ahead and close this because I'm pretty sure this is outside of the scope of the frontend, I think its right to be tracked in iOS.

**Comment by mikesalz** [comment]
But out of curiosity - I am wondering why iOS would be the right place to track it if it is a native Mac app?

**Comment by karwosts** [comment]
It looks like that repo handles all mac platforms.
