### ISSUE TITLE
 After update to 2023.8.3, after 3-5 min in background - the visible field is compressed by about 2 times

### ISSUE THREAD

**Issue by shaman1010** [home-assistant/frontend#17636]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After update to 2023.8.3, after 3-5 min in background - the visible field is compressed by about 2 times.
Firefox 114 & 116. Bug - only in fullscreen mode.
When switching to windowed mode - the size is restored. When you return to full screen mode - after 3-5 minus the interface shrinks again.
About 2-3 years on firefox.

### Describe the behavior you expected

The dimensions of the panel do not change over time, only when the actual size of the window changes.

### Steps to reproduce the issue

1. Latest Firefox (116x)
2. 6 different panels on Overview screen
3. 3-5 min, panels resize and crop. (window mode-fullscreen mode - normalize panels for 3-5 min)
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.8.3

### What was the last working version of Home Assistant Core?

2023.8.2

### In which browser are you experiencing the issue with?

Firefox 114 & 116.0.3

### Which operating system are you using to run this browser?

Windows 10 (64bit)

**Comment by shaman1010** [comment]
I will clarify: The size is limited only after clicking on page refresh. (F5 or button in browser). In fullscreen or in windowed - does not matter. Click F5 - size limited. Resize the browser window - everything is restored. F5 - size limited.

**Comment by shaman1010** [comment]
On the other hand, the markup can be restored by clicking on the button "Sidebar Toggle", Moreover, recovery is possible both with a hidden panel and in the opposite direction.  Looks like the timeout is missing somewhere. Several refreshes in a row - restores / removes markup.  The problem is fixed only in the browser,  on the kiosk app, and HA app - everything is fine.

**Comment by ildar170975** [comment]
Please post a video, could be more useful.

**Comment by shaman1010** [comment]
https://youtu.be/pR0Vp6HAZfw

**Comment by shaman1010** [comment]
Only refrash page.

**Comment by ildar170975** [comment]
1. Post a code for this view.
2. Check with Chrome.

**Comment by shaman1010** [comment]
On Chrome work propertly.

**Comment by shaman1010** [comment]
I use https, maybe it matters

**Comment by shaman1010** [comment]
`title: HA kv
views:
  - path: default_view
    title: Home
    icon: mdi:air-filter
    subview: false
    theme: AMOLED Blue
    badges: []
    cards:
      - type: custom:simple-clock-card
        use_military: true
        hide_seconds: true
        font_size: 8rem
        paddingLeft_size: 32px
        paddingRight_size: 32px
        paddingTop_size: 52px
        paddingBottom_size: 12px
      - show_name: true
        show_icon: true
        show_state: false
        type: glance
        entities:
          - entity: switch.w1
          - entity: switch.proektor
          - entity: switch.ventiliator_1
          - entity: sensor.ventiliator_1_power
          - entity: binary_sensor.kiyivska_oblast_air
        state_color: true
        theme: AMOLED Blue
      - show_current: true
        show_forecast: true
        type: weather-forecast
        entity: weather.forecast_ha_kv
        secondary_info_attribute: wind_speed
        name: Київ
      - type: tile
        entity: binary_sensor.kiyivska_oblast_air
        show_entity_picture: false
        vertical: false
        tap_action:
          action: more-info
      - square: false
        type: grid
        cards:
          - type: gauge
            entity: sensor.datchik_temperature
            name: Стол
            theme: AMOLED Blue
            min: 10
            max: 40
            severity:
              green: 22
              yellow: 10
              red: 28
          - type: gauge
            entity: sensor.ble_temperature_bedroom
            name: Спальня
            theme: AMOLED Blue
            min: 10
            max: 38
            severity:
              green: 22
              yellow: 10
              red: 28
          - type: gauge
            entity: sensor.ble_temperature_bathroom
            name: Ванная
            theme: AMOLED Blue
            min: 10
            max: 40
            severity:
              green: 22
              yellow: 10
              red: 28
      - type: entities
        entities:
          - entity: sensor.ble_humidity_bedroom
            name: Спальня
            secondary_info: last-updated
          - entity: sensor.ble_humidity_bathroom
            name: Ванная
            secondary_info: last-updated
          - entity: sensor.datchik_humidity
            name: Стол
          - entity: sensor.datchik_pressure
            name: Стол
            secondary_info: last-updated
          - entity: switch.usb_udlinitel
            secondary_info: last-updated
        show_header_toggle: false
        state_color: false
  - theme: AMOLED Blue
    title: Sheduler
    path: sheduler
    icon: mdi:calendar
    badges: []
    cards:
      - initial_view: dayGridMonth
        type: calendar
        entities:
          - calendar.sheduler
        theme: AMOLED Blue
      - type: media-control
        entity: media_player.miwrt
        theme: AMOLED Blue
      - type: media-control
        entity: media_player.asus_nexus_7
        theme: AMOLED Blue
  - theme: AMOLED Blue
    title: Графики
    path: ''
    icon: mdi:apple-keyboard-command
    badges: []
    cards:
      - type: history-graph
        entities:
          - entity: sensor.ble_temperature_bathroom
          - entity: sensor.ble_humidity_bathroom
          - entity: sensor.ble_temperature_bedroom
          - entity: sensor.ble_humidity_bedroom
          - entity: sensor.ventiliator_1_power
  - theme: AMOLED Blue
    title: Alarm
    path: alarm
    icon: mdi:alarm-light-outline
    badges: []
    cards:
      - type: entity
        entity: binary_sensor.kiyivska_oblast_air
        theme: AMOLED Blue
        state_color: true
      - type: entities
        entities:
          - entity: binary_sensor.kiyivska_oblast_air
          - entity: binary_sensor.kiyivska_oblast_chemical
          - entity: binary_sensor.kiyivska_oblast_urban_fights
          - entity: binary_sensor.kiyivska_oblast_artillery
          - entity: binary_sensor.kiyivska_oblast_nuclear
        theme: AMOLED Blue
`

**Comment by shaman1010** [comment]
I`m add and remote theme: AMOLED Blue - doesn't matter.

**Comment by ildar170975** [comment]
1. The posted code is unformatted. Use TRIPLE "`".
2. Please always check with a DEFAULT theme.
3. Test w/o using custom cards in general; here - remove "custom:simple-clock-card" and re-test.

**Comment by bramkragten** [comment]
Between 2023.8.2 and 2023.8.3 nothing changed that could affect this, are you sure you didn't introduce something else?

**Comment by shaman1010** [comment]
1) Yes, only standart update from 2023.8.2 to 2023.8.3
2) removed the themes everywhere - the result is the same
3) removed "custom:simple-clock-card" - the result is the same

**Comment by shaman1010** [comment]
https://youtu.be/Ph1QK1tQwmY

**Comment by shaman1010** [comment]
refrash page - break or restore markup
resize window or show / hide panel - restore markup

**Comment by ildar170975** [comment]
See no issues here in FF 116.0.2 (64-bit), Win10x64.
Stable after many F5.

![image](https://github.com/home-assistant/frontend/assets/71872483/a2f1d039-a955-408f-ad76-12371ca9ec85)

**Comment by shaman1010** [comment]
Extender - work propertly?

https://youtu.be/enq-lw3Y_1Y

**Comment by shaman1010** [comment]
New update^
FF installed from local user - in local userspace - work propertly.
FF installed from admin - in local userspace - have bug.

**Comment by shaman1010** [comment]
New update^
FF installed from local user - in local userspace - work propertly.
FF installed from admin - in local userspace - have bug.

And Magic Mouse :)
https://youtu.be/G_lp7MYYhrs

**Comment by shaman1010** [comment]
When I watching - you are working.

https://youtu.be/BGWVakD9mAU

**Comment by ildar170975** [comment]
Advise to reset FF to default settings / reinstall (((

**Comment by shaman1010** [comment]
Resolved:

layout.css.has-selector.enabled  -> false
