### ISSUE TITLE
Dashboards created from UI are not opening

### ISSUE THREAD

**Issue by eps90** [home-assistant/frontend#17644]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am using Home Assistant installation on Docker on my server, version 2023.8.3. Couple of weeks ago I was able to create new dashboard to the UI, open it and create new views. In recent versions I am not able to do that anymore. Opening the dashboard created from the UI (from settings menu) redirect me to the main default dashboard (the one I do not manage and collects all the sensors available in the HASS instance). The dashboards created before encountering this issue work totally fine. I have never created dashboards using YAML configurations.

### Describe the behavior you expected

I should be able to open and edit newly created dashboard.

### Steps to reproduce the issue

1. Go to Settings/Dashboards
2. Create new dashboard by clicking the button at the bottom of the screen
3. In the modal set a random name, do not select administrator restriction. Select "show in the side bar"
4. New dashboard appears in the side bar as well as in the list of dashboards in settings
5. Open the dashboard either by clicking "View" in the settings or select it from the side bar
6. You are redirected to the default dashboard even though the URL points to a new dashboard name
...

### What version of Home Assistant Core has the issue?

2023.8.3

### In which browser are you experiencing the issue with?

Google Chrome 115.0.5790.170, Home Assistant Desktop for MacOS, latest iOS mobile companion app

### Which operating system are you using to run this browser?

MacOS Ventura 13.4.1

### Javascript errors shown in your browser console/inspector

```txt
No error logs, nor no trace in Network tab
```

**Comment by karwosts** [comment]
This works fine for me. 

> 6. You are redirected to the default dashboard even though the URL points to a new dashboard name

How are you establishing that you're on the "default dashboard"? Is the URL correct for your new dashboard? 
All new dashboards look similar to the "default dashboard" when they are first created, since they use the default strategy. However once you "take control" of the dashboard, you should be able to edit it however you want.

**Comment by eps90** [comment]
Okay, silly me. This time the problem was placed between the keyboard and a chair 🙃 Thank you for the support!
