### ISSUE TITLE
Energy dashboard showing incorrect Home consumption if ESS is feeding back to grid

### ISSUE THREAD

**Issue by Kudos50** [home-assistant/frontend#17674]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Energy dashboard Home item shows exactly the same value as the ESS battery has delivered to the house. I am unsure why as this does not happen if I'm not feeding back to grid (I did large feed-ins during a long holiday). So my best guess is that it only manifests if battery to home kWh is larger than Home kWh consumption.

The totals are therefore not correct either. Please see attached screenshot as an example:
<img width="272" alt="Screenshot 2023-08-22 at 19 10 34" src="https://github.com/home-assistant/frontend/assets/74932142/9aafb149-a8eb-45f7-a499-d16cfd535056">

### Describe the behavior you expected

During large grid feed-in, the losses will be severe (maybe even 30% in + out). That number will be easy to find as it is the delta between battery in and out and should be added to Home. Only than all totals will match like they normally do.

In the example from the screenshot:
in: 28.4 solar + 1.1 grid = 29.5
out: 19,8 (grid feed-in by solar and ESS)
total consumed somewhere (house, AC-DC-AC conversion losses, or simply still stored in battery): 9,7 kWh

To try and make an accurate estimate for Home: subtract battery in from battery out and subtract that from total consumed somewhere:
9.7 - (21.7in - 16.4out) = 4,4 kWh Home

Obviously this is not taking all other use-cases into account and needs a lot more work.

In this case, 4.4 is around the same value as other days when not feeding to grid. The 5.3kWh losses in this example seem to be very real as the feed-in stops at 40% SOC.

### Steps to reproduce the issue

1. Activate ESS grid feed-in thereby making sure feed to grid is larger than Home kWh for that day
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.8.3

### In which browser are you experiencing the issue with?

All, including mobile app for iOS

### Which operating system are you using to run this browser?

All, including iOS

**Comment by Kudos50** [comment]
Had a couple of upgrades and tested on a fresh install but problem remains. Once the energy taken from battery exceeds the amount of energy consumed on the house (cause of large grid feed-in amounts) the house consumption number "equals" the amount of energy taken from battery.

**Comment by karwosts** [comment]
I suspect this might be the same as this old stale issue: https://github.com/home-assistant/frontend/issues/11947

I think I've seen this reported a few times, and have observed and confirmed this issue myself, but the fix I think is beyond me, I suspect we just are not collecting enough datapoints to be able to accurately describe the power flows once batteries are involved. There are a lot of assumptions made regarding which sources are flowing to which destination, and once those assumptions are violated, the whole calculation falls apart. 

For now I think I can say that if you're transferring energy from your batteries to the grid, the calculations do not work.

**Comment by Maikel-K** [comment]
I am seeing the same as the opening post.

I have to monitor if before bigger feed in the house consumption seems "normal"
