### ISSUE TITLE
Integrations not properly loading since update

### ISSUE THREAD

**Issue by AnthCar** [home-assistant/frontend#17678]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since the last update integrations do not seem to be loading properly. My current issue is with my Google integration where it is failing to set up. This is not the first integration that has failed to set up since the update. 

![Screenshot 2023-08-22 151751](https://github.com/home-assistant/frontend/assets/142936518/9cc15018-5443-469f-8147-4b36e8e14d12)

### Describe the behavior you expected

I expected everything to relaunch like it normally did.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.8.3

### In which browser are you experiencing the issue with?

Chrome and Android App

**Comment by karwosts** [comment]
Please file an issue in home-assistant/core for the integration that is not setting up correctly. Frontend doesn't handle integration setup, so this is in the wrong place.
