### ISSUE TITLE
[Bug] Different tabs should not share the same session

### ISSUE THREAD

**Issue by marek-vrana** [home-assistant/frontend#17707]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I open Developer Tools -> Services in two different tabs, then it's impossible to set a different service in each tab. Tabs are synced. I bumped version from 2023.6.3 straight to 2023.8.4 and almost immediatelly noticed it.

### Describe the behavior you expected

I'd expect that these tabs are independent and I'm allowed to open infinite number of tabs with different services, so when I change a service in one tab, it keeps its value and it is not synced to the other tab.

### Steps to reproduce the issue

1. TAB1: open developer tools -> services
2. TAB2: open developer tools -> services
3. put both tabs next to each other
4. TAB1: pick service of your choice
5. TAB2: service picked from TAB1 is showed
6. works vice versa, also an issue when filling up parameters of a service

### What version of Home Assistant Core has the issue?

2023.8.4

### What was the last working version of Home Assistant Core?

2023.6.3

### In which browser are you experiencing the issue with?

Chrome 116.0.5845.111, Firefox 116.0.3

### Which operating system are you using to run this browser?

Windows 10

**Comment by ildar170975** [comment]
Cannot consider this as a bug, let's call it a "poor functionality".
It is very useful to have an ability to call different services from different tabs...

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
up

**Comment by ildar170975** [comment]
Although it is possible to make DIFFERENT services calls from tabs (see pics below) - I find the current implementation not good...

![изображение](https://github.com/home-assistant/frontend/assets/71872483/50177de0-1487-4b44-8551-15a17b40d503)

![изображение](https://github.com/home-assistant/frontend/assets/71872483/2a5a7585-3894-47ec-9b26-83dda45e8363)
