### ISSUE TITLE
Empty column under grid card

### ISSUE THREAD

**Issue by seblu** [home-assistant/frontend#17729]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The grid card fullfill a dashboard column leaving no place for others card to fit in.

![Screenshot from 2023-08-29 12-55-54](https://github.com/home-assistant/frontend/assets/615816/99d5daab-2d60-46a5-afe9-a07d8083bb7b)

As a consequence, other cards are out of the viewport while they could be in.

### Describe the behavior you expected

The grid card should be stacked like others cards.

### Steps to reproduce the issue

1. Create a grid card
2. Place it into a dasboard between other cards

### What version of Home Assistant Core has the issue?

core-2023.8.4

### In which browser are you experiencing the issue with?

Chromium 115.0.5790.170, Firefox 116.0.2

### Which operating system are you using to run this browser?

Arch Linux, Android

**Comment by seblu** [comment]
Ok I understand. I'm not CSS savvy enough, but I thought that with flex the components could organize themselves.

What's particularly embarrassing is that it's not an inappropriate placement, it's taking useful cards off the screen.
I didn't succeeded to get something under by adding cards, but enabling `Render cards as squares` does.

![Screenshot_20230829_215424-1](https://github.com/home-assistant/frontend/assets/615816/77db760a-4b89-43af-a8ec-eb872b72357a)

Quite ironically, smaller icons make less things displayed.

![Screenshot_20230829_215712](https://github.com/home-assistant/frontend/assets/615816/2e7f8062-9972-4466-937c-3412adbcb187)

**Comment by karwosts** [comment]
> Quite ironically, smaller icons make less things displayed.

Yes it is somewhat silly, but the "render as square" mode uses a different size calculation that is more correct. 

When in non square mode, we defer to the button card to report how big it should be, but the button doesn't know it is being rendered in a grid, so it reports its "full" size as if it was a full sized card, which is 3 times taller. 

I can imagine some fixes to the cardsize calculation that might help this case, but haven't got around to it.
