### ISSUE TITLE
missing wlan0 set in ui

### ISSUE THREAD

**Issue by kurtdefeyter** [home-assistant/frontend#17743]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

in the network config the wlan0 setup is missing
![afbeelding](https://github.com/home-assistant/frontend/assets/125728797/daf6c1d9-a853-4ce1-ae77-a6ffd110eb04)

### Describe the behavior you expected

should be able to configure wlan from UI

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.8.4 Supervisor 2023.08.1 Operating System 10.5 Frontend 20230802.1 - latest 

### In which browser are you experiencing the issue with?

Microsoft Edge Versie 116.0.1938.62 (Officiële build) (64-bits)

### Which operating system are you using to run this browser?

windows 11

**Comment by silamon** [comment]
There were some changes regarding network configuration that received bugfixes in Supervisor 2023.08.2. Perhaps upgrading would help you issue?

**Comment by kurtdefeyter** [comment]
Sorry this is Home Assistant 2023.8.4  as far as i can see there is no newer version

**Comment by silamon** [comment]
Yes, your Home Assistant is, but the supervisor isn't the latest version.

**Comment by kurtdefeyter** [comment]
weird
![afbeelding](https://github.com/home-assistant/frontend/assets/125728797/e66843df-c529-4745-b4cf-c35ecf51e247)

**Comment by silamon** [comment]
Seems like the update wasn't on stable releases yet at that time, now it is.
