### ISSUE TITLE
Individual device energy monitoring broken

### ISSUE THREAD

**Issue by TheJulianJES** [home-assistant/frontend#17742]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The UI for individual device energy monitoring is broken:
![image](https://github.com/home-assistant/frontend/assets/6409465/8c3f6556-69ce-44b4-9c7e-5265f8e64360)

It only shows a single bar with no names, whilst ~16 devices are monitored.

### Describe the behavior you expected

That all devices have a single bar with name in front (like previously).

### Steps to reproduce the issue

0. Have energy monitoring for individual devices set up
1. Open energy page
2. See bug

### What version of Home Assistant Core has the issue?

core-2023.9.0b0

### What was the last working version of Home Assistant Core?

core-2023.8.4

### In which browser are you experiencing the issue with?

Google Chrome 116.0.5845.96

### Which operating system are you using to run this browser?

macOS Sonoma (14.0) Dev Beta 6

**Comment by karwosts** [comment]
Not sure if helpful, but one thing I do notice is every time the graph gets disconnected and reconnected (like when masonry does teardown to change number of columns), the graph renders correctly for one frame only, you can see it briefly flicker here when I resize back and forth:

![devices-graph](https://github.com/home-assistant/frontend/assets/32912880/856e899d-5141-4f55-9706-2351b01db19e)
