### ISSUE TITLE
Tile Card for Climate is NOT showing upper and lower limits (Version: 2023.9.0b0)

### ISSUE THREAD

**Issue by reotto613** [home-assistant/frontend#17759]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am testing out the new Tile Card with the Honeywell Total Connect Comfort Integration.

When I click for more info on the climate I see the upper and lower limits, but I do not see it on the standard card. No values are even shown.

Here is the view when click More Info.

![image](https://github.com/home-assistant/frontend/assets/60767748/4454614a-d293-4eb6-b0c4-7832dd5fd0e7)

This shows the upper and lower limits.

Here is the card before I click it.

![image](https://github.com/home-assistant/frontend/assets/60767748/168e8f90-05d0-4b52-9509-70a6de6a7cf3)

NOTE: All of my heated floors (which only have a single limit) show correctly.

### Describe the behavior you expected

I expect based on the release notes for 2023.9b0 that I would see the upper and lower limits on the main view of the card.

### Steps to reproduce the issue

1. Upgrade to 2023.9b0
2. Use the tile card, select a climate entity using the Honeywell Total Connect Comfort Integration
3.
...

### What version of Home Assistant Core has the issue?

2023.9b0

### What was the last working version of Home Assistant Core?

N/A

### In which browser are you experiencing the issue with?

Edge Version 116.0.1938.54 (Official build) (64-bit) OR Chrome Version 116.0.5845.140 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 or Windows 11

### State of relevant entities

```txt
hvac_modes:
  - 'off'
  - heat_cool
  - cool
  - heat
min_temp: 40
max_temp: 99
fan_modes:
  - 'on'
  - auto
  - diffuse
preset_modes:
  - none
  - away
  - Hold
current_temperature: 75
temperature: null
target_temp_high: 78
target_temp_low: 63
current_humidity: 45
fan_mode: auto
hvac_action: idle
preset_mode: null
fan_action: idle
permanent_hold: false
dr_phase: -1
friendly_name: HOME
supported_features: 27
```

### Problem-relevant frontend configuration

```yaml
- type: tile
    entity: climate.home
    features:
      - type: climate-hvac-modes
        hvac_modes:
          - 'off'
          - heat_cool
          - cool
          - heat
      - type: target-temperature
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

**Comment by eosho** [comment]
Try cleaning your app cache.

**Comment by reotto613** [comment]
Ernest,

This occurs on the webpage and inside the app. If you mean something else please provide more detail on the how I can accomplish this.

Rick Otto
m 402.779.1042<tel:402.779.1042>

On Aug 31, 2023, at 4:00 PM, Ernest Oshokoya ***@***.***> wrote:

﻿

Try cleaning your app cache.
