### ISSUE TITLE
Cannot set electricity price when using an external statistic

### ISSUE THREAD

**Issue by bokub** [home-assistant/frontend#17807]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I created and add-on that inserts statistics in Home Assistant using the WebSocket API.

It's an external statistic, so the statistic id contains a `:` instead of a `.` as separator, as explained [here](https://data.home-assistant.io/docs/statistics/#statistics-meta).

In the statistics meta, the unit is "Wh".

However, when I try to add this statistic to my Energy Dashboard, I cannot choose the price, because the radio buttons are disabled:

![image](https://github.com/home-assistant/frontend/assets/17952318/10b3e071-3f37-4d31-9988-e5508ccb3395)

### Describe the behavior you expected

When I edit the statistic ID in database and replace the `:` with a `.`, the UI lets me choose a price:

![image](https://github.com/home-assistant/frontend/assets/17952318/679cdb93-7520-4a5b-b456-19a8d4b1865f)

### Steps to reproduce the issue

1. in the `statistics_meta `table, find any energy statistic that works well
2. replace the `.`  with a `:` in the `statistic_id ` (to mark it as "external")
3. Click "add consumption" in the Energy dashboard configuration
4. In the modal, you won't be able to set the electricity price if you choose this statistic !

### What version of Home Assistant Core has the issue?

2023.8.3

### In which browser are you experiencing the issue with?

Google Chrome, but also mobile app

### Which operating system are you using to run this browser?

Windows 10 or Ubuntu 22.04 or Android

### Javascript errors shown in your browser console/inspector

```txt
No error in the console
```

**Comment by karwosts** [comment]
This seems to be intentional, coming from this PR: https://github.com/home-assistant/frontend/pull/15205

Quote:
> A sensor or external statistics which tracks the total cost is supported both when the consumed gas is tracked by an external statistics or by a sensor. **A price entity or a fixed price is only supported when the consumed gas is tracked by a sensor.**

It sounds like for external statistics you are responsible for tracking the price yourself.

**Comment by bokub** [comment]
Oh, this wasn't explained in the Home Assistant developer documentation, so I thought it was a bug...
 
Thanks for finding this information !
