### ISSUE TITLE
Helpers: Not possible to reenable a disabled helper

### ISSUE THREAD

**Issue by BradleyFord** [home-assistant/frontend#17808]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When clicking on a device, entity, helper, etc a pop up window appears of which it is possible to Disable the entity.

But for entities it is possible to re-enable disabled entities... from the entities tab.

But for helpers you cannot do it in the helpers tab...you need to visit the entities tab to enable the helpers.

### Describe the behavior you expected

Some method to reenable a helper

### Steps to reproduce the issue

1. Disable Helper
2. Try to Enable helper

### What version of Home Assistant Core has the issue?

2023.9.0b2

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

Windows 11

### Additional information

<img width="1099" alt="image" src="https://github.com/home-assistant/frontend/assets/322815/6afd9639-a6ab-4d3a-a326-2cf2af9fdaf6">

**Comment by karwosts** [comment]
You say it's not possible to re-enable a disabled helper, but then you say you can re-enable it via the entities tab. 

Is the problem here that you don't feel that using the entities tab is sufficient, and you want _more_ ways to re-enable it? Or is re-enabling it not working at all for you for some reason?

**Comment by uhTWO** [comment]
You need to clear the filter when you go to the Entities tab. The disabled helper will show up there, and you can re-enable it.
