### ISSUE TITLE
New climate, humidifier, and water heater entity dialog design not available as card

### ISSUE THREAD

**Issue by heikone** [home-assistant/frontend#17845]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If noticed the new card design from release notes:
[https://www.home-assistant.io/blog/2023/09/06/release-20239/](url)
Great looking card!
But does anybody know how to update the card?

HA did the upgrade to 2023.9.0 this morning, so actual setup is:
- Home Assistant 2023.9.0
- Supervisor 2023.08.3
- Frontend 20230906.1 - latest

The card still stays the same (left part of picture), but when I click on it, the new design appears (right part of picture).
![Bildschirmfoto 2023-09-07 um 08 19 51](https://github.com/speleolontra/daikin_residential_altherma/assets/42500448/e324ca0b-33ab-4e1c-9e72-24899e271784)

The current code definition of the card looks simply like this:
`type: thermostat`
`entity: climate.altherma`
`name: Mandoka Wohnzimmer`

Any advice would be helpful.
Heiko

### Describe the behavior you expected

Same look of card in dashboard and device info box.

### Steps to reproduce the issue

Refer to picture of issue description.

### What version of Home Assistant Core has the issue?

2023.9.0

### In which browser are you experiencing the issue with?

Apple Safari 16.6

### Which operating system are you using to run this browser?

macOS Ventura 13.5.1

### Problem-relevant frontend configuration

```yaml
type: thermostat
entity: climate.altherma
name: Mandoka Wohnzimmer
```

**Comment by bramkragten** [comment]
This is not a card (yet) but only in the more info dialog.
