### ISSUE TITLE
Unable to navigate to newly created page in dashboard

### ISSUE THREAD

**Issue by raydorman** [home-assistant/frontend#17860]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After adding a new view configuration through the GUI (by using the “+” button), I am unable to navigate to that new page. However, the code is visible in the raw configuration editor.

### Describe the behavior you expected

1. Create new view configuration with “+” button
2. Successfully navigate to new blank configuration page

### Steps to reproduce the issue

1. In Lovelace, click the three dots in the upper right hand corner and select “Edit Dashboard””
2. Click the “+” button
3. Add a new view configuration and click “save” when complete
4. Attempt to navigate to this new view

### What version of Home Assistant Core has the issue?

2023.8.4

### In which browser are you experiencing the issue with?

iOS App and Safari 

### Which operating system are you using to run this browser?

IPad OS 16.2 and MacOS

**Comment by karwosts** [comment]
That's pretty basic functionality you're claiming is broken, it seems fine to me... could you give a little more detail about what is happening? 

Why can't you navigate to it? What happens when you click the tab?

Did you try refreshing the page? Clearng cache? 

Only time I've seen this behavior or something like it is if you accidentally give a tab the same name as an existing tab. You can create it but trying to navigate to it always takes you to the first instance.

**Comment by spacegaier** [comment]
There is a bug there that I remember having discussed with Bram a couple of months ago, but I guess never gotten around to fixing. The context was that if you give a view a numeric name such as "1" then during navigation that gets interpreted as the view index and you then end up on another view (the 2nd in this example).

Could potentially be related or the same issue that OP faces (as you said we need more details from OP to confirm).

**Comment by raydorman** [comment]
I agree this seems a little crazy. I have narrowed it down to if I name the view "test" I have this issue. If I use any other word there is no problem (thought it does show up normal in the raw configuration editor).  I guess we can chalk this one up to me, sorry for the trouble but thank you for the response.

**Comment by karwosts** [comment]
You're sure you don't have any other views with "test" as the URL? 

I did put up this PR #17871 to prevent user creating a second view with the same URL, I've done this myself more than once by accident 🤣
