### ISSUE TITLE
Climate dialog wrong dpi on PC

### ISSUE THREAD

**Issue by samuelolteanu** [home-assistant/frontend#17877]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![Captură](https://github.com/home-assistant/frontend/assets/85267083/b813ca5a-a068-4f93-a225-b9e561d0c99d)
The new climate dialog is too "zoomed in" on Windows in different scenarios.
This happens at 3840x2160 300% (recommended) scale, 1600x900 120% scale. All browsers (Chrome, Firefox, Edge) were at 100% zoom. This dissapears at 90% browser zoom but then there will be many empty spaces in the rest of the HA ui wich subjectivly is not visually appealing.

### Describe the behavior you expected

No scroll bar, all info should be on the dialog all the time. 

### Steps to reproduce the issue

Set Windows resolution and scale at settings described above.

### What version of Home Assistant Core has the issue?

 2023.9.x

### What was the last working version of Home Assistant Core?

2023.8.x

### In which browser are you experiencing the issue with?

Firefox 117.0, Chrome 116.0.5845.180, Edge

### Which operating system are you using to run this browser?

Windows 10 and Windows Server 2022

### Additional information

For those interested, I used [template climate](https://github.com/jcwillox/hass-template-climate) to switch to ir when normal way is unavailable (the ac checks for internet at startup).

**Comment by piitaya** [comment]
Can you send a screenshot of your entire screen? Also, do you have to issue with other more info dialog (e.g. light dialog)?

**Comment by samuelolteanu** [comment]
> Can you send a screenshot of your entire screen? Also, do you have to issue with other more info dialog (e.g. light dialog)?

Light component renders similarly. I suspect normal switch does not have anything to cut out so that's why it looks to be fine.
![Captură ecran (7)](https://github.com/home-assistant/frontend/assets/85267083/c101f55c-edf9-4b1d-adc5-8ec86b2c351e)

![Captură ecran (4)](https://github.com/home-assistant/frontend/assets/85267083/0d291931-05cf-44c1-a80c-5636345f320c)
![Captură ecran (5)](https://github.com/home-assistant/frontend/assets/85267083/a0990c29-702b-44f6-a32e-ab234afbe757)
![Captură ecran (6)](https://github.com/home-assistant/frontend/assets/85267083/245ee832-65a9-4859-a1d7-810cddf8bf4c)

**Comment by piitaya** [comment]
Ok, that the same issue for all new more-info. The screen height is too small for it.
@matthiasdebaat We should find a way to organize the more info with multiple columns on desktop.
