### ISSUE TITLE
History not using correct time for chart end time

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/frontend#17879]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When opening the history integration, the end time is sometime in the future rather than now()

<img width="1076" alt="image" src="https://github.com/home-assistant/frontend/assets/57034871/743926fa-07be-4ee1-aeca-e541a14d5ee6">

### Describe the behavior you expected

End time should be now() or next full hour from now.

### Steps to reproduce the issue

1. 
2. 
3.
...

### What version of Home Assistant Core has the issue?

2023.8.4

**Comment by karwosts** [comment]
Your post lacks a lot of information that could be helpful, e.g. 

What time was now() when the screenshot was taken?

Are you saying the chart is wrong, or the time picker is populated with the wrong value?

Is your server timezone the same as your browser timezone? If not, which one are you using in your settings?

**Comment by AleXSR700** [comment]
Well, the end of the chart, as you can see, is not identical to the time being shown as end in the selection in the top left.

The end of the chart is now(). The end time the system automatically selected was much later.

All time zone should be identical as the system time and the home assistant entity update times as well as the charts x-axis are in sync.

Only the end time the history graph uses as default is a few hours in the future.

**Comment by ildar170975** [comment]
In my experience, it is possible to select a future datetime for the right border - but the graph always ends at now(), and this is correct.

**Comment by AleXSR700** [comment]
Well,
a) it makes no sense to be able to select the future (especially not in a history graph :D)

b) even if you allow future selection, the default value for the end picker should be now() and not now() + x hours

**Comment by ildar170975** [comment]
It does have a sense to select a future datetime in the “right bound” picker because it allows to users to monitor entities:
— now it is 16:00, a user set “18:00” as a “right bound”;
— whenever a user switches to this browser’s tab - he can see a graph;
— ofc after 18:00 the graph will not reflect current state, so a user may re-set the “right bound” to 23:00 to continue monitoring.

**Comment by AleXSR700** [comment]
You could of course add a now() button ;-)

Apart from that, manual future selection is not the issue. It being the default makes no sense.

Your argument is fair,  but at 19:00 the user will need to change it again.

So better options would be

- default = now()
- future selectable but will either
  a) be reset to now() when leaving the dashboard
or
  b) can be reset to now() via a now button

**Comment by AleXSR700** [comment]
automatic close or really not planned?

**Comment by ildar170975** [comment]
it became "stale", then closed automatically
