### ISSUE TITLE
Schedule helper cannot have periods ending at midnight. 11:30 is max.

### ISSUE THREAD

**Issue by msageryd** [home-assistant/frontend#17888]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Schedule helper won't let me include the last half hour of the day. I can only drag the period to 11:30 PM.
Same problem in Chrome and Safari on Mac.

### Describe the behavior you expected

Seems reasonable to be able to drag the period all the way to midnight.

### Steps to reproduce the issue

1. Create a new scedule helper
2. Drag a period so that the end reaches midnight.
3. The period resets to whatever it was before draging
4. Drag the period 10 11:30 PM
5. Now the period sticks

### What version of Home Assistant Core has the issue?

2023-9.0

### Which operating system are you using to run this browser?

MacOS Ventura 13.5.2

**Comment by karwosts** [comment]
It looks like it actually does work to drag to 12:00a, even though it doesn't look like it. 

E.g.: 

- Drag an end to 12:00a
- (it will snap back)
- Save out and close the dialog
- Reopen the dialog
- See the event is scheduled to 12:00a
- check devtools and see that it really is scheduled to midnight

Though you're right the UI should definitely be improved...
