### ISSUE TITLE
Slow UI - Degraded performance.

### ISSUE THREAD

**Issue by deanfourie1** [home-assistant/frontend#17885]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

UI frontend is very slow. Can take 1 minute after launching the app to be able to scroll down to the bottom of my dashboard.

Attempting to open or click on any entities on the dashboard, takes ages to load and is very delayed.

### Describe the behavior you expected

A nice snappy UI like before ;)

### Steps to reproduce the issue

1. Im not sure, just updated to 2023.9.0 and this happened.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.9.0

### What was the last working version of Home Assistant Core?

2023.8.0

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

Windows, Ubuntu, Android.

### Additional information

Receiving the error since updating.

`Failed to call service system_log/write. unknown error`

**Comment by karwosts** [comment]
I saw someone else report something similar and they ultimately discovered it was some custom card slowing things down. 

Are you using any custom resources or mods?

**Comment by deanfourie1** [comment]
Yes, I'm using the following cards.

mini-graph-card
compass-card
search-card

Prior to that, no new cards before this issue occurred.

**Comment by kongjudas** [comment]
I have the same issue. It started in 2023.8 and got a lot worse in 2023.9. It is really slow and sometimes non-responsive in settings using the auto-fill entities search.

**Comment by Christian-PK** [comment]
I am experiencing the same. After update to .3 version it got a bit better but. But still slower than 2023.8.

**Comment by SeByDocKy** [comment]
Idem .... super super slow :( .... since .3

**Comment by Christian-PK** [comment]
> I am experiencing the same. After update to .3 version it got a bit better but. But still slower than 2023.8.

Rolled back to 2023.8.3 today. Hopefully this will get resolved soon.

**Comment by kylepyke** [comment]
I'm only having issues in the visual automation editor. YAML is fine, but trying to open a 'Choose' action, for example, takes 1-2 mins to respond.

**Comment by Christian-PK** [comment]
Just updated to 2023.10.3 seems like it has been fixed.

**Comment by issmirnov** [comment]
Take a look at your `known_devices.yaml`. If you have device tracking turned in, this file may be huge. Mine was 20mb and had 200k+ lines. Once I deleted it, performance instantly improved.

Source: https://community.home-assistant.io/t/very-slow-performance-from-lovelace-dashboard/551612/18

**Comment by deanfourie1** [comment]
> Take a look at your `known_devices.yaml`. If you have device tracking turned in, this file may be huge. Mine was 20mb and had 200k+ lines. Once I deleted it, performance instantly improved.
> 
> 
> 
> Source: https://community.home-assistant.io/t/very-slow-performance-from-lovelace-dashboard/551612/18

Yea I deleted that file already,

Ha is still chewing up 8gb of RAM which I'm not sure that's normal.

**Comment by Swerfer** [comment]
I have also a very slow UI response since a couple of months. I'm up to date with everything. Auto fill entities search takes 10 to 20 seconds, dashboard response also very slow. Opening yaml in dashboard editing takes sometimes over 30 seconds. After a restart the UI response is much better, but slows down over time (hours).

![Screenshot_20240104_205947_Home Assistant](https://github.com/home-assistant/frontend/assets/14137117/16eec50b-bf53-4d37-a70a-05cf96046657)
