### ISSUE TITLE
Include MQTT entities with geolocation in the map

### ISSUE THREAD

**Issue by vibrog** [home-assistant/frontend#17884]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Entities with latitude and longitude attributes set area expected to appear in the sensor map.
However MQTT entities don't according to [this discussion](https://community.home-assistant.io/t/sensors-on-a-map/540938/4).

### Describe the behavior you expected

MQTT entities with latitude and longitude attributes are not included on the map.

### Steps to reproduce the issue

Create an MQTT entity with attributes longitude and latitude included.

### What version of Home Assistant Core has the issue?

2023.9.1

### What was the last working version of Home Assistant Core?

-

### In which browser are you experiencing the issue with?

Firefox 117.0

**Comment by karwosts** [comment]
Which map are you referring to, map panel or map card?

For an entity which is not working, can you post the state and attributes from developer-tools/states? AFAIK it should work.

**Comment by ildar170975** [comment]
> all entities with `latitude` and `longitude` attributes are displayed on the map.

Actually - not, there are some exclusions (by design or due to bugs).
https://github.com/home-assistant/frontend/issues/17925
