### ISSUE TITLE
Schedule helper rendering issue

### ISSUE THREAD

**Issue by harry-bridge** [home-assistant/frontend#17910]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When editing a schedule helper and moving between the settings and summary page, the second time the schedule settings are viewed the 'weekly' view is rendered incorrectly. Tested on Firefox and Safari

### Describe the behavior you expected

Every time the settings button is pressed the 'week' view renders correctly

### Steps to reproduce the issue

1. Create a schedule helper (doesn't need to include any schedule items)
2. Click on the schedule helper to open the summary page
3. Click the setting icon to edit the schedule
4. Change nothing and click the 'Back to info' button
5. Click the settings icon again to see the schedule view rendered incorrectly
...

### What version of Home Assistant Core has the issue?

2023.9.1

### In which browser are you experiencing the issue with?

Firefox 117.0, Safari 16.4.1

### Which operating system are you using to run this browser?

macOS Monterey (12.6.5)

**Comment by karwosts** [comment]
I'm guessing this is probably the same issue as https://github.com/home-assistant/frontend/issues/16848 , as they both use the fullcalendar module. That one is similar, the second time calendar gets rendered it is like missing all the css styling or something. 

Adding a screenshot.

![image](https://github.com/home-assistant/frontend/assets/32912880/6d9f1a15-e9bc-4140-b6ea-bdc1d6e0156f)
