### ISSUE TITLE
Energy Dashboard is Showing negative Grid Consumption

### ISSUE THREAD

**Issue by MrFr33man123** [home-assistant/frontend#17919]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![image](https://github.com/home-assistant/frontend/assets/906150/d7d0b3ea-8d80-4bcb-8e1f-ff293feecb6e)
![image](https://github.com/home-assistant/frontend/assets/906150/44246858-d9c1-4288-acbe-1ef0fe66d20b)
No Matter the energy from grid consumption, the values are shown negative.
In statistics its a positive value.

Energy Dashboard Configuration
![image](https://github.com/home-assistant/frontend/assets/906150/7e63f791-3e58-4d35-adc7-13406bf7409e)
![image](https://github.com/home-assistant/frontend/assets/906150/ba595e24-9ce9-44cf-b19a-734bcbeb1e4d)
![image](https://github.com/home-assistant/frontend/assets/906150/ce4798cb-e6ee-41f8-8a3d-064a58fba76e)

### Describe the behavior you expected

I would expect a positive value in consumption and energy distribution.

### Steps to reproduce the issue

1. Have a consumption, production sensor in the energy dashboard.
2. Consumption is negative and house consumption is not shown only solar production
3.
...

### What version of Home Assistant Core has the issue?

core-2023.9.2

### What was the last working version of Home Assistant Core?

core-2023.8.4

### In which browser are you experiencing the issue with?

any browser chrome, edge, safari.

### Which operating system are you using to run this browser?

iOS, Windows, Linux, Android

### State of relevant entities

```txt
State is positive Value
```

**Comment by karwosts** [comment]
Try adjusting one of your statistics during that hour of the negative consumption to the positive amount of the negative bar (e.g. if your bar is -3.2kWh, change a "0 kWh" datapoint to "3.2 kWh". 

Believe that will make it go away. 

Note this is not really a frontend bug, but the data in your statsitic table reset unexpectedly when it should not, so the data got messed up.

**Comment by MrFr33man123** [comment]
To explain that missing graph. I have an energy provider named tibber that is pushing consumption data from my smartmeter to home assistant. If the integration fails, like in this example. Data is stale. On restart of the integration it has how ever always succsessfully added up those consumed kWh and send it summed up in the first hour of activating the integration.

The Statistics should not need to be manually manipulated by me. Also over the course of the day it is now counting negative in the blue circle of grid power.

What would be the right section to drop this issue into? Because the statistics is correct as in no negative values there.
The question is why is it shown as negative while statistics is correct!
Thats the reason I assumed frontend to be the bad guy. Is there anything i can look into deeper to help debug this?

**Comment by karwosts** [comment]
If you want to dig deeper you can open up your statistics table in SQL and look at it. The negative bar will be associated with a datapoint where the "sum" column decreases, it should not be decreasing. 

You can read this post, I went into a little more detail about it. I don't recommend actually executing the steps here anymore as this can be fixed by the adjust dialog, but this gives you some info about what is actually in the table.

https://github.com/home-assistant/frontend/issues/17010#issuecomment-1615267071

**Comment by MrFr33man123** [comment]
the linked issue #17934 is the wanted behavior. I think it's broken at the moment.If this is a core issue not an energy dashboard issue i can open an issue there.

**Comment by karwosts** [comment]
#17934 explains why you cannot _fix_ the issue in the dialog, but it does not explain why it happened to you in the first place. 

If you wanted to figure out _why_ this happened, that would be a core issue.

**Comment by MrFr33man123** [comment]
Thanks, Closed because it's seems to be a core issue.
