### ISSUE TITLE
Calendar events are displayed half a day too long

### ISSUE THREAD

**Issue by samuelru3** [home-assistant/frontend#17927]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Calendar events are displayed half a day too long
![Screenshot_20230915_141122_Home Assistant](https://github.com/home-assistant/frontend/assets/72190083/8653aae2-ae60-420d-a547-6c5f4500ad5b)
![Screenshot_20230915_141116_Home Assistant](https://github.com/home-assistant/frontend/assets/72190083/3c6517bd-66bd-41f4-9170-be28975279a6)

### Describe the behavior you expected

I expected it to end on the right day

### Steps to reproduce the issue

1.create a calendar event that lasts several days and ends at 12 p.m
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.9.2 Supervisor 2023.09.2 Operating System 10.5 Frontend 20230911.0 - latest

### In which browser are you experiencing the issue with?

Android App and Google Chrome

**Comment by karwosts** [comment]
Issue seems to be that it's flexing too wide as it's trying to fit the name of the event in the bar. 

This only happens in narrow mode, likely due to the `flex` applied in narrow mode. I'm not familiar enough with how this calendar CSS is constructed to suggest a change though. 

```
        :host([narrow]) .fc-dayGridMonth-view .fc-daygrid-day-events {
          display: flex;
          align-items: center;
          justify-content: center;
          flex-wrap: wrap;
        }
```
