### ISSUE TITLE
more-info: displaying "dictionary" attributes is broken

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#17932]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Consider a sensor:
```
template:
  - sensor:
      - name: test_long_attr
        state: ok
        attributes:
          dict_attr: >-
            {% set LONG_VALUE_1 = "xxx" %}
            {% set LONG_VALUE_2 = "yyy" %}
            {%- set DICT = {
              'value_1': LONG_VALUE_1,
              'value_2': LONG_VALUE_2
              } -%}
            {{DICT}}
```
which has a "dictionary" attribute:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/44ba07e6-9731-4ad1-a07a-56f1ec014ff4)

This is how it is displayed in more-info:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/70782bce-1aeb-4662-a243-4650b598bb0d)

**So far it is OK.**

Now consider a similar sensor with a LONGER values:
```
template:
  - sensor:
      - name: test_long_attr
        state: ok
        attributes:
          dict_attr_long: >-
            {% set LONG_VALUE_1 = "Morocco lies close to the Azores–Gibraltar Transform Fault." %}
            {% set LONG_VALUE_2 = "Morocco lies close to the Azores–Gibraltar Transform Fault." %}
            {%- set DICT = {
              'value_1': LONG_VALUE_1,
              'value_2': LONG_VALUE_2
              } -%}
            {{DICT}}
```
![изображение](https://github.com/home-assistant/frontend/assets/71872483/bcec7e13-abcf-4029-b71b-e218f4ae4c34)

But here more-info is corrupted:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/feaa2af5-9fa7-4565-a718-11da38154558)

Recently - at least in 2023.7 (or .8) it was OK.
Seems that this was broken in some of recent releases.

### Describe the behavior you expected

All info is fit in a window.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.9.2

### In which browser are you experiencing the issue with?

Chrome 117.0.5938.63

### Which operating system are you using to run this browser?

Win10x64

**Comment by Mariusthvdb** [comment]
seeing that too:

![Sep-26-2023 15-24-13](https://github.com/home-assistant/frontend/assets/33354141/e787aea2-af58-4e40-93c3-86b5287f3a72)

sorry for the duplicate.

**Comment by ildar170975** [comment]
@Mariusthvdb 
Proposed a fix for the font here: https://github.com/home-assistant/frontend/pull/18290#issuecomment-1807268735
