### ISSUE TITLE
ESPHome devices are appearing as "not loaded."

### ISSUE THREAD

**Issue by gaitolini** [home-assistant/frontend#17933]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have reported an issue where ESPHome devices are appearing as "not loaded." It seems there might be a connection issue or a failure in device initialization. I'm seeking assistance in resolving this problem as it affects the overall functionality of the system. Any guidance or solution would be greatly appreciated. Thank you!

![image](https://github.com/home-assistant/frontend/assets/24495176/f12914e5-64dd-45c6-8f6d-5e740df07c19)

### Describe the behavior you expected

I expected the system, after the penultimate version, to execute the automations of the ESPHome devices correctly.

### Steps to reproduce the issue

1.
![image](https://github.com/home-assistant/frontend/assets/24495176/cc75fb5e-71be-415f-956b-13737163175a)

2.
![image](https://github.com/home-assistant/frontend/assets/24495176/b662c393-c727-46c4-8975-90e24ff9bbac)

3.
 ![image](https://github.com/home-assistant/frontend/assets/24495176/f12914e5-64dd-45c6-8f6d-5e740df07c19)

![image](https://github.com/home-assistant/frontend/assets/24495176/e47d746d-ce06-4a92-b31c-9d4c2f627558)

### What version of Home Assistant Core has the issue?

2023.9

### What was the last working version of Home Assistant Core?

2023.9

**Comment by karwosts** [comment]
Please file an issue in core for the `esphome` integration, the frontend does not control this.
