### ISSUE TITLE
tuya can't show devices in more than 1 hub in the same time

### ISSUE THREAD

**Issue by sgabran** [home-assistant/frontend#17936]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi
I have 2 Tuya hubs integrated in HA. Each hub belongs to a Tuya account.
I can only display devices in hub at a time, and the other hub shows as "no devices or entities".
Is there a solution for this ?
thanks

![tuya](https://github.com/home-assistant/core/assets/27746449/da8ab341-d1f0-4cb4-9833-230e519df843)

### Describe the behavior you expected

I expect to be able to load all devices in all tuya hubs

### Steps to reproduce the issue

1. integrate tuya account 1
2. integrate tuya account 2
3. try to display devices in all accounts in the same time

### What version of Home Assistant Core has the issue?

web based HA

### What was the last working version of Home Assistant Core?

web based HA

### In which browser are you experiencing the issue with?

Chrome

**Comment by karwosts** [comment]
This needs to be filed in core for the `tuya` integration. The frontend does not control this.
