### ISSUE TITLE
UI won't load in Chrome

### ISSUE THREAD

**Issue by iamandymcinnes** [home-assistant/frontend#17947]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

UI doesn't fully load in chrome, I get half the dashboard load then it freezes and keeps saying wait.

Similar thing happening with the app on a pixel6.

Cleared cache and all site data and same happens again. Similar on the app too, but if I clear cache on that it works momentarily.

I can see a worker websocket request pending and that eventually fails.

No issues in edge, so perhaps something chrome related.

I'm on latest chrome and home assistant.

![image](https://github.com/home-assistant/frontend/assets/47521626/0b88dd1c-a89e-43bd-9035-4aaefb2c1bb4)

### Describe the behavior you expected

The ui to load

### Steps to reproduce the issue

Open home assistant in chrome
Try to click on anything

### What version of Home Assistant Core has the issue?

2023.9.2

### In which browser are you experiencing the issue with?

Google Chrome Version 116.0.5845.188

### Which operating system are you using to run this browser?

windows 10

### Problem-relevant frontend configuration

```yaml
Multiple pending requests for urls like:

https://home.domain.co.uk/static/mdi/892a846dbff0a6d1dbb5b08fc6afac527f3e49ba.json
```

### Javascript errors shown in your browser console/inspector

```txt
?auth_callback=1&code=f28210c56ec54ea4bddc1599ba0f040d&state=eyJoYXNzVXJsIjoiaHR0cHM6Ly9ob21lLmFuZGlzb2Z0LmNvLnVrIiwiY2xpZW50SWQiOiJodHRwczovL2hvbWUuYW5kaXNvZnQuY28udWsvIn0%3D:1     GET https://home.domain.co.uk/local/card-mod.js net::ERR_ABORTED 404
(anonymous) @ ?auth_callback=1&code=f28210c56ec54ea4bddc1599ba0f040d&state=eyJoYXNzVXJsIjoiaHR0cHM6Ly9ob21lLmFuZGlzb2Z0LmNvLnVrIiwiY2xpZW50SWQiOiJodHRwczovL2hvbWUuYW5kaXNvZnQuY28udWsvIn0%3D:1
/lovelace?auth_callb…nQuY28udWsvIn0%3D:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://home.domain.co.uk/local/card-mod.js
load_resource.ts:32     GET https://home.domain.co.uk/browser_mod.js?automatically-added net::ERR_ABORTED 404
(anonymous) @ load_resource.ts:32
o @ load_resource.ts:6
n @ load_resource.ts:37
(anonymous) @ load-resources.ts:30
n @ load-resources.ts:12
(anonymous) @ ha-panel-lovelace.ts:235
Promise.then (async)
value @ ha-panel-lovelace.ts:233
value @ ha-panel-lovelace.ts:153
_$AE @ reactive-element.ts:1376
performUpdate @ reactive-element.ts:1343
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
_ @ reactive-element.ts:931
A @ lit-element.ts:115
o @ ha-panel-lovelace.ts:66
C @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
value @ hass-router-page.ts:296
value @ hass-router-page.ts:316
_currentLoadProm.d.then._currentLoadProm @ hass-router-page.ts:214
Promise.then (async)
value @ hass-router-page.ts:205
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
_ @ reactive-element.ts:931
o @ hass-router-page.ts:48
r @ partial-panel-resolver.ts:44
C @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
G @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
_ @ reactive-element.ts:931
A @ lit-element.ts:115
a @ home-assistant-main.ts:52
C @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
G @ lit-html.ts:2183
update @ lit-element.ts:165
value @ home-assistant.ts:33
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ home-assistant.ts:208
await in value (async)
value @ home-assistant.ts:79
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ hass-base-mixin.ts:56
_updateHass @ context-mixin.ts:95
(anonymous) @ connection-mixin.ts:252
s @ store.js:19
(anonymous) @ collection.js:25
Promise.then (async)
d @ collection.js:25
u @ collection.js:27
(anonymous) @ collection.js:52
subscribe @ collection.js:96
S @ config.js:16
(anonymous) @ core.ts:118
Promise.then (async)
(anonymous) @ core.ts:113
(anonymous) @ core-fAiOncciMpo.js:1
load_resource.ts:13 Uncaught (in promise) https://home.domain.co.uk/browser_mod.js?automatically-added
```

**Comment by karwosts** [comment]
Seems to be some issue with your browser mod install. I would try remove that and see if problem goes away.

**Comment by iamandymcinnes** [comment]
I'll try removing it, but I don't think that is blocking tbh. I'm seeing it fail to even load the ui and getting the wait and exit message for chrome. I think it's more to do with those background worker threads that are timing out.  I'll post back shortly so I can rule out the browser mod.

**Comment by iamandymcinnes** [comment]
No you might have been right, seems better. I'll see how it goes, bit strange as I wasn't using browser mods on this dashboard but just had it installed. I'll post a question over on the browser_mod gh to see if anyone else has seen weirdness. Thanks :)

**Comment by iamandymcinnes** [comment]
Still seeing this behaviour even with browser mod completely removed. The issue is less obvious on desktop chrome, but seeing it constantly on mobile Chrome 117.0.5938.60 and the android app. Even when I completely clear site data, close chrome and reopen it the UI just won't completely load and I can't click anything. Currently on my mobile the only way I can access home assistant is briefly on the mobile app which will let you click something briefly straight after clearing the app cache. But then after you have it goes back to not working again.

**Comment by karwosts** [comment]
Last time you posted a call stack with browser mod errors. Now that it's gone, do you see any new errors?

I also see card_mod in your call stack. It seems whatever CDN its trying to download from (domain.co.uk?) is not responding.

**Comment by iamandymcinnes** [comment]
I've resolved all console errors and on windows chrome it's fine, however I've noticed other users having app and chrome freezing issues on mobile. I can confirm this now consistently happens in the App and in Android Chrome. I went through the android companion issues and as it also freezes in android chrome, they've sent me back here.

**Comment by iamandymcinnes** [comment]
This is the same problem I am seeing on Android 13 on a Pixel 6: https://github.com/home-assistant/frontend/issues/17967

**Comment by alexruffell** [comment]
What you describe sounds like my issue. My main dashboard often does not fully load. One of the persistent errors mentions browser_mod which I installed a long time ago and removed without ever really using it. Regardless, my Chrome console shows that it fails to load but it doesn't tell me what is trying to load it. Also, when using the Android companion app, the main dashboard freezes and takes a while to start responding again. I most often kill the app and open it again. I did not think these two issues were related but you mentioned both so now I wonder.

How in the world do I uproot browser_mod? I do use card_mod... but not browser_mod.

**Comment by karwosts** [comment]
> How in the world do I uproot browser_mod? I do use card_mod... but not browser_mod.

I would check and make sure the component is not installed in your `integrations` panel, and check the Dashboards/resources panel to make sure there are no browser_mod resources being loaded.

I do see that after removing the browser_mod custom component it still leaves a browser_mod.js module in the resources, and that will get automatically loaded on every page load regardless of whether you use it or not.

**Comment by iamandymcinnes** [comment]
You need to go in .storage and then remove the section for it in lovelace_resources, I've done that and no mention of browser_mod anymore but I still have this freezing issue. 

It feels like something has changed somewhere probably in the last 2-3 releases if it's HA side, I don't think this is chrome specific anymore as people are noting it on IOS and safari and firefox too. So either something has changed in one or more hacs addons people use, like the charts people keep mentioning. Or something has changed in home assistant somewhere and it's either having an effect on hacs addons or it's affecting HA itself. 

I can't narrow it down any further myself as I don't know where to look. I've tried the app and the frontend and provided all the logs I can and removed as many external factors like addons I don't use etc. I currently have no console errors and no weird things like browser_mods that seemed like a red herring at first.

Another guy seemed to be convinced the issue is something to do with the newest HAOS build and he setup a test rig on proxmox with the .4 and .5 version of HAOS showing slower loading. Some people are attributing it to history charts etc. 

My phone is the key way I interact and right now it's just painful and has been for sometime, but without some guidance to provide more specific info that could help resolve the issue I'm a bit stuck. I've also updated to latest beta today and I still get the issue.

**Comment by karwosts** [comment]
I guess if you want to narrow it down, what specifically do you mean "the UI" won't load. 

Does it happen on every page of every dashboard?
If it works on some dashboards/views but not others, can you narrow down specific cards that seem to be causing an issue?
Does it happen on an empty dashboard?
Does it happen every time or only sometimes?
Does it happen on non-dashboard pages like the settings page?

Lets narrow down specifically what works, and what doesn't.

**Comment by iamandymcinnes** [comment]
So on the app or mobile chrome, if I delete the cache / site data. I can load the HA. Obviously on the app it will load straight in to the dashboard at first.

This works and is response as it always was.

Consistently if I close the app from a dashboard then reopen the app, it half loads the dashboard and I cannot click on anything menu, or widget. It is completely frozen other than it will after about 10 seconds scroll up and down the half loaded dashboard.

I've just created a new dashboard and not added anything to it so it is just loading all my components is the vanilla way. Cleared the cached. Reopened the app, set the new dashboard as default.

This new dashboard seems to load, so this is clearly pointing to an issue with something on my normal dashboard.

I haven't changed the dashboard in ages, but I have removed browser_mode and card_mod and a few other things I am not using, but only after the issue presented.

Setting pages at least through android chrome if I went direct seemed ok too.

So I've got a little further but will have to do a lot more digging to workout what has broken on my original dashboard.

**Comment by alexruffell** [comment]
@iamandymcinnes - Thank you so much!! Indeed it was still listed in lovelace_resources even though it hasn't been on my system for over a year now. I removed it, rebooted, and I have no errors!

@karwosts this is my main dashboard:
<img width="1015" alt="image" src="https://github.com/home-assistant/frontend/assets/4006944/067e3553-c0ba-496d-8861-4b99a58fb0bf">

The 3rd column often has issues. Today I replaced the plotly graphs with appex cards to see if it made a difference. Both plotly and appex seem to generate a ton of errors in Chrome's console:

<img width="535" alt="image" src="https://github.com/home-assistant/frontend/assets/4006944/1ef23791-4b08-497f-847b-148c76fe9a06">

**Comment by karwosts** [comment]
If you want support here you need to get rid of the custom cards (temporarily), we don't support them in this repository. 

Don't switch plotly to apex, get rid of both of them (any other custom items) and see if you can still see the problem.

**Comment by TransRapid** [comment]
Some consideration, I had some similar issues that were related to SSL when running a reverse proxy. Running Bullseye, venv, and NGINX.

**Comment by canselcik** [comment]
I have no custom widgets, charts or anything. The only thing I have is a shell command that shouldn't be relevant at all and the UI freezes on Chrome right away on Dashboard. For some reason this doesn't happen in Incognito but it keeps happening despite clearing all site storage, making me think it is somehow related to an extension but all the potential culprits are disabled.

**Comment by canselcik** [comment]
Nothing too concrete but noticing sketchy details that perhaps could use more eyes.

When BitWarden extension is disabled, the page Lovelace dashboard loads fine. 
When BitWarden extension is enabled the page freezes.
