### ISSUE TITLE
Again

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#17950]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

https://github.com/home-assistant/frontend/issues/16572

### Describe the behavior you expected

*

### Steps to reproduce the issue

*

### What version of Home Assistant Core has the issue?

*

**Comment by ildar170975** [comment]
@milandzuris 
Please do not create issues like this one.
If you need to report a behaviour similar to described in https://github.com/home-assistant/frontend/issues/16572, just add a new comment to that issue.
