### ISSUE TITLE
Error message: "Failed to call service system_log/write. unknown error" after update 2023.9.2

### ISSUE THREAD

**Issue by majorhector** [home-assistant/frontend#17954]
### The problem

I have updated to 2023.9.2. After that the frontend give me the message "Failed to call service system_log/write. unknown error" and everything is blocked. After 30 second the message disappear, the front-end refresh and everything works fine. This happend every time I open the companion app.

I have HassOS on a Raspberry Pi 4B - RAM 4 Gb
OS 10.5
Frontend 20230911.0

### What version of Home Assistant Core has the issue?

core-2023.9.2

### What type of installation are you running?

Home Assistant OS

**Comment by steverep** [comment]
Okay I see the problem.  The errors during connection phases were stopped from going to the log by #17893, but `callService` has its own catch which displays the toast notification.  That needs to be circumvented.

**Comment by direx1** [comment]
Same issue with companion app and fully kiosk browser. I haven't noticed it in chrome browser

**Comment by twister36** [comment]
Same error for me. I've noticed that if the app stays open in the background and you leave phone for 5+ mins, when you return and open the app (still actively running) the error is thrown and "then" sensors are updated. However, if you force close the app, then let the phone go to sleep, the sensor will continue to update, but no error when you re-open the app 5+ mins later. 

For me the error is only when the app stays "open" in the background.

**Comment by realroywalker** [comment]
I can confirm seeing this issue in Chrome (Desktop) as well as in the Android companion app, when it happens the connection to HA seems to go unresponsive for a period of time (~30sec) then it comes back. I am on 2023.9.1 - don't recall encountering the issue before then.

**Comment by KentuckyMC** [comment]
Confirmed this error happening for me as well since this latest update. I've only noticed it during a idle time on my wall tablet. It's running Fully Kiosk.

**Comment by twister36** [comment]
> Okay I see the problem. The errors during connection phases were stopped from going to the log by #17893, but `callService` has its own catch which displays the toast notification. That needs to be circumvented.

Will this be a Companion App fix or a Home Assistant update that we should look for?

**Comment by ampersandru** [comment]
Same issue here with just the Android companion app after updating to 2023.9. I have a small chrome window open all day on a PC without issues

**Comment by steverep** [comment]
Just to be clear folks, the problem is well understood and someone just needs to get to it.  No need for the repeated confirmations.  It could occur on any browser or OS, but it's completely harmless.

**Comment by DaN66O** [comment]
The logs contain the following error:
`Uncaught error from Chrome WebView 113.0.5672.163 on Android 12 Uncaught 3 3 @http://192.168.13.1:8123/frontend_latest/core-fAiOncciMpo.js:1:8789`

**Comment by tiptap85** [comment]
Unfortunately, the 9.3 core update did not help to me.

**Comment by Zaphod360** [comment]
Is this for a future update as 2023.09.02 didn't fix the problem for me?

**Comment by steverep** [comment]
Fix will be in 2023.10.0

**Comment by nwithan8** [comment]
2023.12.1 and this is still happening. Good to know it's harmless though, mostly annoying and probably unnecessarily crowding the log files.

**Comment by joostlek** [comment]
Please open a new issue

**Comment by rcjkierkels** [comment]
This issue should not have been closed. Problem still occurs

**Comment by Mark7714** [comment]
2024.05 and still happening. Would it help if we listed the card types on page and try and narrow it down that way?

**Comment by andiukas** [comment]
2024.07 beta problem still happening

**Comment by FragMenthor** [comment]
Still got this after months.... 2024.7.2 now

**Comment by Mark7714** [comment]
Same. Perhaps if we list out our add-ons and HACS modules we might find a common thread?

**Comment by steverep** [comment]
Folks this is a closed issue, and thus not the best place to report further problems.  There is only one explicit spot in the frontend code that calls the `system_log/write` service, and that was fixed from creating a toast message in the UI in #18022 which closed the original issue as reported (and that change is still in place).

If you still experience these toast messages somehow, please open a new issue as @joostlek stated above.  Please make sure you can reproduce it without custom resources, and provide all details requested in the template in order to make finding the cause much easier.  Thanks.
