### ISSUE TITLE
Missing translation "Search", "Official add-ons"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#17952]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing translation "Search", "Official add-ons"

### Describe the behavior you expected

Add missing text "Search", "Official add-ons" to lokalise

### Steps to reproduce the issue

1.
2.
3.
...
![1695036784766_Search-Official add-ons](https://github.com/home-assistant/frontend/assets/61636045/1b5579e5-9474-4ea8-a554-70471352bd41)

### What version of Home Assistant Core has the issue?

2023.7.2

**Comment by misa1515** [comment]
Now with marked (red colour) issues
![1695036784766_Search-Official add-ons](https://github.com/home-assistant/frontend/assets/61636045/a1830f8b-627b-424b-b1d8-b063bbef8239)

**Comment by karwosts** [comment]
I think these strings are from the supervisor, not in the frontend. So I'm not sure if there's anything can be done in this repo.
