### ISSUE TITLE
The "Create Automation" button is hidden most of the time because of useless animation. It should always be visible.

### ISSUE THREAD

**Issue by altimac** [home-assistant/frontend#17963]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Today I wanted to create a new automation. After more than 5 minutes (!) to look for a "+" or "create" or "add" button, I had to read the documentation.
I was looking for such button at the right place but it was invisible, totally hidden because of a useless animation that is more or less not working. 
Please look at the attached video capture.

### Describe the behavior you expected

Such button should always be visible. Only their state (enabled/disabled) should be used to deactivate the action.
You'll see with the attached video that it's quite obvious there's a bug with this button visibility even on large screens.

### Steps to reproduce the issue

1. Settings
2. Automations & Scenes
3. Try to create a new automation by looking for the "Create automation" button

It's not always visible

### What version of Home Assistant Core has the issue?

Home Assistant 2023.9.0

### Which operating system are you using to run this browser?

macOS Ventura 13.5

### Additional information

Had to zip the movie.
[bug HA buttons.mov.zip](https://github.com/home-assistant/frontend/files/12656967/bug.HA.buttons.mov.zip)

**Comment by karwosts** [comment]
You've got some kind of funky zoom thing going on in your browser that I think it not related to HA. 

For example between 0:00:09 and 0:00:10 like your screen "pans" to the right. I don't know what's doing that but that's not a HA feature, I think you've got some weird browser zoom plugin installed or something.

**Comment by altimac** [comment]
I'm afraid you don't know macOS/iOS "rubber band" scrolling (at least this is what I think you saw between 00:00:09 and 00:00:10). It's the normal Apple scrolling style since it appeared on the iPhone.

**Comment by altimac** [comment]
The rubber band scrolling is both vertical and horizontal, you can basically scroll beyond the borders of the window.
Anyway when reloading the page, it seems to behave differently (aka correctly).
I'll report if I can reproduce it.
