### ISSUE TITLE
App and WebUI freeze in iOS 17

### ISSUE THREAD

**Issue by bvarick** [home-assistant/frontend#17967]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In both the Home Assistant App and in Safari, the dashboard freezes. Usually it shows a few cards properly before freezing. When I cleared the cache, it loaded more cards at first, but eventually froze. The WebUI works great on other devices

### Describe the behavior you expected

The dashboard cards to load without freezing

### Steps to reproduce the issue

1. Update to iOS 17
2. Open Home Assistant app
3. Navigate through various cards and dashboards
...

### What version of Home Assistant Core has the issue?

2023.9.2

### In which browser are you experiencing the issue with?

Home Assistant iOS app 2023.4

### Which operating system are you using to run this browser?

iOS 17

**Comment by nrm94ee330** [comment]
Same issue for me as well. frontend does not work in app, or safari or firefox or chrome. I reverted back to 2023.9.0, and everything (fronend) is working normally in both app as well as safari and firefox.

**Comment by gepatto** [comment]
Had the same issue. Tracked it down to the history graphs being slow. Seeing all lot of cpu usage in javascript and rendering. Feels like ( I'm not an expert ) drawing to canvas 2d is slow on ios17 and is blocking.

**Comment by serrnovik** [comment]
As part of discussion in https://community.home-assistant.io/t/ios17-freeze/616618/12 it look like charts causing this issue. If there is no chart on the dashboard (tab) there is no problem. So I had to pull out all my charts from default tab to be able to load it on iphone is temporary workaround.

**Comment by bekovan** [comment]
same here, reaction on PC OK, Iphone 8 with IOS 16 OK, Iphone 13 with ios 17 : blocking.
Restarted HA (Raspberry pi 4) & phones, no change

**Comment by gepatto** [comment]
Slowdown/blocking is still present on ios 17.0.1
I think this is not a bug in the app but rather a quirk/bug in ios 17.

I don't know if the canvas 2d rendering is done on the main thread (that would explain the blocking)
but maybe something like OffScreenCanvas could be a thing to look into?

**Comment by hmatos-rogers** [comment]
I am experiencing the same issue.  I have 2 identical ipad air 5th gens.  One is running ipadOS 16.x without a problem, the one running 17.x is unusable. I installed a fresh copy of home assistant with no HACS, no add-ons and it still hangs.

**Comment by jcastro** [comment]
Same on iOS 17.0.2 on iPhone 15 pro

**Comment by Scialla** [comment]
Same problem here, with history-graph card, only on iOS17

**Comment by hakspiel** [comment]
no improvement with iOS17.02 & HA 2023.10.0b2 on iPhone 12

**Comment by Chatocampeon** [comment]
I have the same issue that is explained perfecto y in previos messages

**Comment by ryaaanmorgan** [comment]
Same issue here. Thought I was going insane at one point…

**Comment by SinnoTech** [comment]
Same

**Comment by leeoniya** [comment]
my offer to assist with uPlot integration [1] is still on the table. since that discussion, uPlot is now the main plotting library in Grafana, where we handle dashboards with millions of datapoints.

there is no animation or transition support though, so that may be a blocker here. not sure.

here's a demo: https://perf.rust-lang.org/, also https://play.grafana.org/

[1] https://github.com/home-assistant/frontend/issues/5587

**Comment by alsospacebar** [comment]
Adding my data points, I observe 100% cpu usage specifically with the history-graph card on the iOS companion app (latest, on iOS17), Mac companion app (latest, Sonoma), and Safari (latest, Sonoma). This certainly seems like an unfortunate interaction with webkit.

**Comment by rabit9** [comment]
Hello, now the same problem in Sonoma and Safari when opening the history chart

**Comment by arundalep** [comment]
I have the same issue with IOS 17.0.3

**Comment by StrohhutGit** [comment]
Same. 
iOS 17.0.3 - issue 
iOS 16.x.x - no problem

**Comment by lorenzo-deluca** [comment]
Same here, iPhone 13 mini, iOS 17.0.3 :/

**Comment by KJK-78** [comment]
Any idea if/when this will be fixed as currently HA is almost unusable with iOS?

**Comment by marcusn-fi** [comment]
Same problem with iOS 17.1

**Comment by mbeaudoin** [comment]
Same problem here as well with HA and iOS 17.x, but with a twist...

My HA platform is composed of many views or dashboards, and many of those dashboards are presenting information using history graphs spanning the last 24 hours (historic data from various sensors: temperature, humidity, current, voltage, etc.)

My iOS 16.x (HA app) and macOS Ventura (browser) clients are all behaving properly without freezing, no matter the HA dashboard I am visiting.

But when using an iOS 17.x client app (iPhone and iPad), I can navigate and visualize almost all of those history graphs, except one specific dashboard, where the history graphs are created from a bunch of  sensors generating a lot more data per day. This dashboard will cause all my iOS 17.x HA client to freeze completely.

In my case, the history graphs behaving properly with iOS 17.x are from sensors generating data once per minute.
On the specific dashboard where my iOS 17.x clients are completely freezing, the history graphs are displaying sensor data generated once per second.

So it looks like the freezing problem with iOS 17.x might be related to the amount of points or values one needs to vizualize from an history graph. 

Hope this helps...

**Comment by nicopret1** [comment]
Same problem on iOS 17.1.1 HA Core 2023.11.2, Supervisor 2023.11.3, Operating System 11.1, Frontend 20231030.2. If I click on my "Lights" dashboard (without graphs) all ok, if I go to my "Power" dashboard (with graphs) it freezes

**Comment by nicopret1** [comment]
I have now started to duplicate the cards one by one in the dashboard giving the problem to a new dashboard. The moment I added the first card with 24hr history graphs, it froze. I reduced the history period from 24hrs to 2 hrs and tried again and it then works fine.

**Comment by nicopret1** [comment]
> I have now started to duplicate the cards one by one in the dashboard giving the problem to a new dashboard. The moment I added the first card with 24hr history graphs, it froze. I reduced the history period from 24hrs to 2 hrs and tried again and it then works fine.

There are 2 specific cards with graphs with a high resolution of data points that are causing my issue. I have now increased the history period again for these from 2 to 4 hrs and my app is still working fine.

**Comment by nicopret1** [comment]
> > I have now started to duplicate the cards one by one in the dashboard giving the problem to a new dashboard. The moment I added the first card with 24hr history graphs, it froze. I reduced the history period from 24hrs to 2 hrs and tried again and it then works fine.
> 
> There are 2 specific cards with graphs with a high resolution of data points that are causing my issue. I have now increased the history period again for these from 2 to 4 hrs and my app is still working fine. If go to 8 hrs I can see that its starts to struggle.

The issue seems to be specific to high resolution data within a timeframe:

This graph is a problem if history is more than 4 hrs:
![Screenshot 2023-11-15 at 11 20 27](https://github.com/home-assistant/frontend/assets/130547447/9a2a1664-6d01-41dd-8370-3ab9ede42ba8)

But this graph works fine even though the history is for 240hrs
![Screenshot 2023-11-15 at 11 21 22](https://github.com/home-assistant/frontend/assets/130547447/b4e57af0-21b0-41dc-88f6-9c3146f0dae9)

**Comment by clickety** [comment]
I too see the issue on dashboards with graph cards. It struggles with those always, but anything > 2 hrs hard locks the browser or device (safari on Mac, any webkit browser including the Homekit Companion app on iOS/iPadOS)

**Comment by swainstm** [comment]
This issue is still happening for me in 2023.12.0. See : -
https://community.home-assistant.io/t/web-and-ios-app-frontend-hanging-on-complex-screens/651729/10

**Comment by 0mgithub** [comment]
I have the same problem on all my iOS devices after updating them to iOS 17. I moved the graphs to a different tab that caused the issue but I can never check them anymore on my phone which basically renders the whole setup useless. Im deeply disappointed to be honest.

**Comment by swainstm** [comment]
For what it is worth, the issue is still the same with 2023.12.1.

I am not a developer, but can assist with testing if that would help.

**Comment by mbeaudoin** [comment]
iOS 17.2 seems to fix the problem.

**Comment by swainstm** [comment]
I think 17.2 is an improvement for sure. But it is still flakey on my Overview page with lots of objects and the graph page. So I suspect there are some improvements that can be driven from the HA end.

The other thing that has started happening, is my windows 11 laptop has start blue screening which has never happened before. This might be coincidence until I collect more data. But so far it has only happened when I am viewing 1 of my busy HA screens, and has NEVER happened unless I am on one of these busy screens. Again, this might be a coincidence and I will get more data and history, but I have enough to be suspicious.

**Comment by rabit9** [comment]
Hello, looks like the problem with iOS17.2 and Mac OS14.2 is solved. Hallo, sieht so aus als wäre das Problem mit iOS17.2 und Mac OS14.2 behoben.

**Comment by gepatto** [comment]
I can confirm that on ios 17.2 the long delay and unresponsive ui with large datasets in graphs is gone. Seems like something got fixed in ios 17.2
