### ISSUE TITLE
Light entities not showing additional info - e.g. colour wheel, etc...

### ISSUE THREAD

**Issue by ianfretwell** [home-assistant/frontend#17979]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When clicking on any light entities in the dashboard (both Hue and Sonoff in my case) I no longer get any dialog to interact with.
The box opens with just the header bar - all other content is missing.

I think this has occured since 2023.9.2 but am not entirely sure.

### Describe the behavior you expected

I expect to see the usual interaction bars, e.g. brightness, colour-wheel etc.

### Steps to reproduce the issue

1. Open HomeAssistant  (browser or companion app)
2. Navigate to a dashboard with light entities on it
3. Click one
...

### What version of Home Assistant Core has the issue?

2023.9.2

### In which browser are you experiencing the issue with?

Chrome / Edge / Firefox / Companion App

### Which operating system are you using to run this browser?

Windows 11 / Android 12

### State of relevant entities

```txt
State of an example light entity:-

min_color_temp_kelvin: 2000
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 500
effect_list:
  - None
  - candle
  - fire
  - unknown
supported_color_modes:
  - color_temp
  - xy
mode: normal
dynamics: dynamic_palette
icon: hue:bulb-candle
friendly_name: Snug Lamp Top
supported_features: 44
```

### Additional information

Initially thought this was in some related to the Hue Bridge update to v1.60.xxxxxx but issue shows on a Sonoff dimmer switch that usually would show brightness sliders, etc.

**Comment by karwosts** [comment]
There were several users recently commenting on Discord about the same and it was caused by bad custom_components installed. Specifically "Better Thermostat" seemed to be causing issues.

**Comment by ianfretwell** [comment]
And you are absolutely right - many thanks.

Just went in to check that was the one I had installed - yes...but it was asking to update through HACS, done that (to v2.1.2) and now everything is working again.
