### ISSUE TITLE
Unfortunately, only a gas meter and a water meter are possible @ energy dashboard

### ISSUE THREAD

**Issue by Ingo-Klein** [home-assistant/frontend#17978]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Unfortunately I need more… when it comes to electricity as well as solar, more is possible…!

no further counter can be selected

### Describe the behavior you expected

same

### Steps to reproduce the issue

Unfortunately I need more… when it comes to electricity as well as solar, more is possible…!

no further counter can be selected

### What version of Home Assistant Core has the issue?

2023.09.2

### What was the last working version of Home Assistant Core?

2023.09.2

**Comment by karwosts** [comment]
I have no idea what this is asking for, you've not really given any details of what your issue is,

**Comment by Ingo-Klein** [comment]
https://ibb.co/30340QX
https://ibb.co/yX97VBS

No additional meters can be added for gas or water > Only one is allowed at a time...if I add more the list won't load

**Comment by karwosts** [comment]
You can definitely add multiple entities to gas and water sections. What do you mean "it won't load"? If you try to add a second entity it says no statistics found? How many statistics are available to choose from in the first case?

**Comment by Ingo-Klein** [comment]
There are 6 to choose from when I set up the first one... if I then want to add another one, I can't select anything... it doesn't do an automatic search and the list is empty too..

With solar and electricity it works wonderfully
