### ISSUE TITLE
Lights colors and intensities are no longer editable on Lovelace

### ISSUE THREAD

**Issue by Najihel** [home-assistant/frontend#17981]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since latest version, colors and intensities aren't editable through Lovelace (on Android, Firefox or others devices) but through Google Home it's ok

### Describe the behavior you expected

Normal behavior 😊

### Steps to reproduce the issue

1. Select any light from any integration
2. Try to open the light pabel

https://github.com/home-assistant/frontend/assets/1873677/7ef9925a-0dbc-439a-bffd-5f37d86a0139

### What version of Home Assistant Core has the issue?

Home Assistant 2023.9.2

### In which browser are you experiencing the issue with?

Firefox and Android Home Assistant Companion

### Which operating system are you using to run this browser?

MacOs and Android

### Additional information

Home Assistant 2023.9.2
Supervisor 2023.09.2
Operating System 10.5
Interface utilisateur : 20230911.0 - latest

**Comment by karwosts** [comment]
See if https://github.com/home-assistant/frontend/issues/17979 applies to you

**Comment by Najihel** [comment]
> See if https://github.com/home-assistant/frontend/issues/17979 applies to you

Oh ! Thank you very much !
