### ISSUE TITLE
SMA Integration Expected data source not listed

### ISSUE THREAD

**Issue by DaBe1812** [home-assistant/frontend#18002]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I'm missing a datasource in the energie tab configuration. I have the sma integration and everything looks fine. But for the value "Power sent to grid" I need the sensor sn_3015651417_metering_power_supplied and it isn't listed in the drop down menu.

### Describe the behavior you expected

The value must be selectable in the dropdown

### Steps to reproduce the issue

1. Use SMA integration
2. Try configuring the energie desktop

### What version of Home Assistant Core has the issue?

2023.9.2

### What was the last working version of Home Assistant Core?

2023.9.2

### In which browser are you experiencing the issue with?

Microsoft Edge Version 117.0.2045.36 

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment]
Please show the full attributes of the entity in question. 

Also check the statistics panel in devtools to make sure there is no reported issue there for that sensor.

**Comment by DaBe1812** [comment]
Statistics Tab is looking good. No issues and values looking correct.
But what do you mean with "full attributes"?

**Comment by karwosts** [comment]
Everything from developer tools/states in the right column, e.g.:

![image](https://github.com/home-assistant/frontend/assets/32912880/334dcd43-0455-411a-ad46-f86b03017f3a)

**Comment by DaBe1812** [comment]
Okay:
sensor.sn_3015651417_metering_power_absorbed: 
state_class: measurement
unit_of_measurement: W
device_class: power
friendly_name: SN: 3015651417 metering_power_absorbed

sensor.sn_3015651417_metering_power_supplied:
state_class: measurement
unit_of_measurement: W
device_class: power
friendly_name: SN: 3015651417 metering_power_supplied

I noticed that both aren't showing.

**Comment by karwosts** [comment]
You cannot show power sensors in energy dashboard, only energy sensors. 

Power is the rate of flow. You need an energy sensor (total accumulated power usage).

**Comment by DaBe1812** [comment]
Okay, those sensors are also in this integration but I can't relate which one is which value in the energy-board.
From the SMA integration I have:
sensor.sn_3015651417_metering_total_absorbed
sensor.sn_3015651417_metering_total_yield
sensor.sn_3015651417_pv_gen_meter
sensor.sn_3015651417_total_yield

**Comment by DaBe1812** [comment]
Correct, thought it was an issue with the integration. Thanks for the help.
