### ISSUE TITLE
Tomorrow.IO nowcast showing hourly data intead of 'minutely' 

### ISSUE THREAD

**Issue by Drew-Pinion** [home-assistant/frontend#18001]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Unable to see minute by minute data for nowcast

### Describe the behavior you expected

Expect for nowcast entity to store minute resolution data refreshed at interval chosen in configuration

### Steps to reproduce the issue

1. Install the integration and configure API Key and location
2. Configure refresh frequency in minutes and save
3. Load nowcast entity, which seems to contain hourly data only

### What version of Home Assistant Core has the issue?

Home Assistant 2023.9.2

### What was the last working version of Home Assistant Core?

Unsure - suspect link to refactor of forecast datatype

### In which browser are you experiencing the issue with?

Multiple (Chrome latest, Edge, IOS Safari)

### Which operating system are you using to run this browser?

Win 11, IpadOS, Android

**Comment by karwosts** [comment]
Are you saying that it used to have a separate forecast for each minute? I'm not sure that's suppored by the weather platform, according to the docs:

> Forecast data can be daily, hourly or twice_daily. An integration can provide any or all of them.

And also I'm not sure if this is a frontend issue, the data storage of an entity would be an issue for home-assistant/core.

**Comment by Drew-Pinion** [comment]
Thanks, karwosts.  Yes, it used to provide for each minute up to 300 minutes out.  This was super helpful.  Info [here](https://www.home-assistant.io/integrations/tomorrowio) for detail. 

I suspect you're right about it being a core issue.  I'll have to repost there.

**Comment by Drew-Pinion** [comment]
I have opened a bug on the Core thread [HERE](https://github.com/home-assistant/core/issues/100800), so closing this.
