### ISSUE TITLE
Home Assistant on mobile crashes when viewing History graph

### ISSUE THREAD

**Issue by jcastro** [home-assistant/frontend#18006]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When opening an history graph from an entity with many data points, like the Watts usage from Shelly (updated every 1 second) either the Home Assistant app or Safari crashes with a white screen and it's impossible to continue using it without completely restarting the app/browser

### Describe the behavior you expected

It should open the graph and not crash

NOTE: This seems to be a "bug" on iOS17 because on iOS16 it works fine. 

### Steps to reproduce the issue

1. Open a history graph from an entity with many data points
2. The browser/app will open the UI and immediately crash (white screen) and will become unresponsive

...

### What version of Home Assistant Core has the issue?

2023.9.2

### In which browser are you experiencing the issue with?

Safari, Chrome (both mobile latest version)

### Which operating system are you using to run this browser?

iOS 17 (on iOS 16 it works fine)

### Additional information

Recorded a video of the problem, again only happening on iOS17 while iOS16 not having this issue. Maybe it's just a bug from Apple and not from HA but just wanted to let you guys know!

**Comment by karwosts** [comment]
Likely same as #17967

**Comment by jcastro** [comment]
@karwosts yeah looks like it's the same

**Comment by karwosts** [comment]
Closing as duplicate.
