### ISSUE TITLE
Unable to edit or delete multiple helper types unless opened in second tab

### ISSUE THREAD

**Issue by c11umw** [home-assistant/frontend#18004]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Originally post (for issue history and evolution): [No longer able to edit or delete multiple helper types](https://github.com/home-assistant/core/issues/97996)

When going to the helpers page an opening a counter, I'm presented with the pop-up as normal, but when I click on the gear icon to edit the settings the pop-up shrinks with no editable information. The only option is <- back to the initial pop=up page.

Trying to edit in Developer Tools | states isn't persistent.
I created a new counter in case it was an upgrade issue, but I got the same results.

But opening in a second tab seems to "fix" it
Details of the Test/Workaround in the "Additional Information" section

### Describe the behavior you expected

To be able to view, edit, update and delete the helpers

### Steps to reproduce the issue

- Close browser
- Open browser and navigate to HA
- Settings | Devices and Services | Helpers
- Test editing one 

1 - helper page (filtered)
![image](https://github.com/home-assistant/core/assets/48920056/b5141815-5e48-4444-ad04-f64fb9a30eed)
2 - click on counter
![image](https://github.com/home-assistant/core/assets/48920056/d5ee36a2-c678-443c-9e4b-a312f606469e)
3 - click on settings
![image](https://github.com/home-assistant/core/assets/48920056/9b71b818-b366-44fd-ab01-916c6f9cbbc5)

...

### What version of Home Assistant Core has the issue?

From core-2023.8

### What was the last working version of Home Assistant Core?

core-2023.7.*

### In which browser are you experiencing the issue with?

Google Chrome 116.0.5845.188 (Official Build) (64-bit), Firefox v117.0.1 (64bit)

### Which operating system are you using to run this browser?

Win10 V22H2  (build 19045.3448)

### State of relevant entities

```txt
Helper Entities.
```

### Additional information

To workaround the issue I do the following steps and it re-enables edit and delete for me (and others)
Tested on Chrome and Firefox (both latest)

- Close browser
- Open browser and navigate to HA
- Settings | Devices and Services | Helpers
- Test editing one (it fails)
- Right click Settings to open in a new tab
- Devices and Services | Helpers
- Test editing one (it works)

I don't see why opening it in a new tab should be any different, but that's the current workaround atm

**Comment by c11umw** [comment]
Addendum - Launching the browser straight into the settings or helpers page also works.
Settings: http://homeassistant.local:8123/config/dashboard
Helpers: http://homeassistant.local:8123/config/helpers

When you instigate navigation from the default dashboard then it fails
Core URL: http://homeassistant.local:8123
Default Dashboard: http://homeassistant.local:8123/lovelace/default_view

**Comment by jwildman16** [comment]
Issue persists.

**Comment by J0k3r2k1** [comment]
Issue still presists, HA 2024.5.2
*workaround 
    - use android app to delete unwanted helpers

**Comment by beringtom** [comment]
Can confirm I just had the same issue right now, open in a new tab and it's back to working, next time I'll try an clear cache to if that fixes anything.

**Comment by juanmijm** [comment]
I have been trying to delete two helpers for several days and it is totally impossible, nothing works, not even accessing from Chrome, Edge, Opera, or the mobile app, not even deleting cache or ctrl+F5, not even an incognito tab, not even going directly to http://homeassistant.local:8123/config/helpers
I am totally desperate with this, I hope they fix it soon or I'm going to go crazy.

**Comment by juanmijm** [comment]
https://community.home-assistant.io/t/unable-to-delete-helper/682342/14

here is the solution to my problem :)
