### ISSUE TITLE
History-graph tool tip windows not closing on mobile

### ISSUE THREAD

**Issue by tomjhou** [home-assistant/frontend#18008]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

My problem is specific to the mobile version. When I click on any history graph, the tool tip window that pops up doesn't go away if I then click some other entity.

The first screenshot shows my dashboard after clicking inside the top history graph. As expected, a tool tip shows info at the selected point. Then I click the "garage" temperature entity (third from the bottom). A new page comes up, but the old tool tip is still there, covering the new page. There is no way to make it go away without exiting the garage entity.

First click in history graph         |  Second click on another entity (garage sensor)
:---------------------------------:|:-------------------------:
![image](https://github.com/home-assistant/frontend/assets/2946264/43850411-ff1e-4610-9f00-31e04b344831) | ![image](https://github.com/home-assistant/frontend/assets/2946264/7ab37e15-2afc-4747-a9a9-1fc8dac02a60)

### Describe the behavior you expected

The tool tip for a history graph should go away when navigating to some other entity.

### Steps to reproduce the issue

1. Click any point in any history graph in the mobile version. This pops up a tool tip for the selected time point.
2. Click any other entity in the dashboard, e.g. a temperature sensor.
3. Note that the tool tip is still there, often obscuring vital information.

### What version of Home Assistant Core has the issue?

2023.09.2 (latest)

### In which browser are you experiencing the issue with?

Mobile versions of Chrome and Opera

### Which operating system are you using to run this browser?

Android

**Comment by i-jk** [comment]
Looks like #18198 is the same thing

**Comment by tomjhou** [comment]
I updated to the latest version of Home Assistant and can unequivocally
confirm that it did NOT fix this issue.

- Tom

**Comment by tomjhou** [comment]
As the original poster here, I would not be bothered if this issue is closed, as it is mentioned in at least two other places:

https://github.com/home-assistant/frontend/issues/18198
https://github.com/home-assistant/frontend/issues/18016
