### ISSUE TITLE
New logo looks bad in update entity

### ISSUE THREAD

**Issue by mvdwetering** [home-assistant/frontend#18020]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I noticed there was an update for Home Assistant and the new logo looks bad the update entity. It kind of looks like a teardrop, not like a house. (I updated to 2023.9.3 after taking the screenshot and the issue is still there)

![image](https://github.com/home-assistant/frontend/assets/732514/4e56e234-7ccb-4cbb-8ae6-2ab9808fb421)

For reference the round icons on Discord and YouTube look fine
![image](https://github.com/home-assistant/frontend/assets/732514/bccf268f-2f2c-4f0a-8a73-5d82200c4e95)
![image](https://github.com/home-assistant/frontend/assets/732514/15ea5316-12b1-4405-a716-9db663c76732)

### Describe the behavior you expected

The new icon looking nice

### Steps to reproduce the issue

1. Look at the update entity for Home Assistant Core offered by Supervisor integration

### What version of Home Assistant Core has the issue?

2023.9.3

### In which browser are you experiencing the issue with?

Google Chrome Versie 116.0.5845.188 (Officiële build) (64-bits)

### Which operating system are you using to run this browser?

Windows 11

### Problem-relevant frontend configuration

```yaml
It is the integration page for the "Home Assistant Core" service offered by the Home Assitant Super Visor integration.
```

### Javascript errors shown in your browser console/inspector

```txt
None
```

**Comment by matthiasdebaat** [comment]
It will be fixed in 2023.10
https://github.com/home-assistant/frontend/pull/17972
