### ISSUE TITLE
background-image disappearing after few random seconds

### ISSUE THREAD

**Issue by Kedryn** [home-assistant/frontend#18030]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a card with person data for each member of the family:
![image](https://github.com/home-assistant/frontend/assets/12759632/4733adcc-884d-4f32-a4eb-ac5f7f9f0ee1)

This is the snippet that loads the backround image
```
  - variables:
      person: person.emanuela
      bg: |
        [[[
          let stringa = states['person.emanuela'].state;
          stringa = stringa.toLowerCase();
          return 'url(/local/images/zones/' + stringa.replace(" ","_")  + '.png);';
        ]]]
```
and it's used here:
```      item2:
        card:
          type: custom:button-card
          entity: "[[[ return variables.person ]]]"
          show_entity_picture: true
          show_name: false
          show_icon: false
          styles:
            card:
              - padding: 0
              - height: 120px
              - box-shadow: none
              - border-radius: 3px 3px 0 0
              - background: null
              - background-image: "[[[ return variables.bg  ]]]"
              - background-size: cover
              - background-position: center
              - overflow: visible
```

Images are there when the page is loaded, but then, after few random seconds, the image of some family member disappear
With chrome inspector, i saw that the background-image style simply disappear.
A page refresh will repopulate all images
Sometimes one gets "sticky" and doesn't disappear at all.

When there is the image:
![image](https://github.com/home-assistant/frontend/assets/12759632/c0806697-0a07-432a-9f77-a451e76ddb08)
When it disappear:
![image](https://github.com/home-assistant/frontend/assets/12759632/cfa57912-aceb-416f-82ca-8508fef10ce1)

When it disappear:

I really don't understand

### Describe the behavior you expected

That all images stays there

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

any

### What was the last working version of Home Assistant Core?

never

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

win 11

**Comment by karwosts** [comment]
Custom card usage is not covered in the frontend github repo. Please open an issue with the creator of your custom card.
