### ISSUE TITLE
Weird white bar Tile Display URL

### ISSUE THREAD

**Issue by Aftergit** [home-assistant/frontend#18040]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After the update to Home Assistant 2023.9.3 coming from 2023.9.2 the tile Display URL showing a white bar (2cm) below the url to display.

This is the url to display :
https://www.weerenradar.nl/weerradar?center=51%2C5.6&placemark=51.5555%2C5.0913&zoom=6&layer=wr

### Describe the behavior you expected

Before the update de white bar was not  visible

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.9.3

### What was the last working version of Home Assistant Core?

2023.9.2

### In which browser are you experiencing the issue with?

Google chrome 117.0.5938.114

### Additional information

![Screenshot 2023-09-27 105709](https://github.com/home-assistant/frontend/assets/88626814/b1a11fc6-3699-4481-9553-46dca2f16bca)

**Comment by karwosts** [comment]
If I visit that link, it has the same white bar in the source page. I think that's just part of the webpage.
