### ISSUE TITLE
Can't add the Escea integration when you had the earlier custom integration installed previously.

### ISSUE THREAD

**Issue by clowgg** [home-assistant/frontend#18044]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I can't add the new Escea integration - I get a pop-up msg "This device cannot be added from the UI. You can add this device by adding it to your 'configuration.yaml'. See the documentation for more information."

I previously had the earlier custom integration installed via an entry in configuration.yaml.
I have removed that entry and renamed the custom integration folder to try to remove all remnants of it.
I have restarted my HA OS server several times through troubleshooting this.

### Describe the behavior you expected

The new core Escea integration would install.

### Steps to reproduce the issue

1. [Add Integration]
2. Type 'Escea'
3. Select 'Escea' from list'
4. Get the pop up message 
...

### What version of Home Assistant Core has the issue?

2023.9.3

### In which browser are you experiencing the issue with?

Firefox 118.0 and Edge 117.0.2045.43 

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
I would file this in core, I don't think frontend has much influence over the install process of integrations.

**Comment by clowgg** [comment]
Moved to Core issues.
