### ISSUE TITLE
Urdu should be configured as right-to-left language

### ISSUE THREAD

**Issue by yousaf465** [home-assistant/frontend#18057]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![image](https://github.com/home-assistant/frontend/assets/83491212/1b486e8d-a3f8-42ef-af44-ae41f38fd91b)
![image](https://github.com/home-assistant/frontend/assets/83491212/7f096307-d4b6-4f93-ae93-f4e4d041c444)

If I am using right-to-left language in this case Urdu, the left side is left blank, and the edit dashboard button and some entities on right are also hidden. 
the 

### Describe the behavior you expected

The dashboard should move to the left if using right-to-left languages. 

### Steps to reproduce the issue

1. Change language to any right to language. 
2. The dashboard doesn't move to the left. 
3.
...

### What version of Home Assistant Core has the issue?

2023.10.0b2

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment]
I will say I'm a bit confused here as when I look at the langauge metadata, Urdu does not seem to be listed as an RTL language:

https://github.com/home-assistant/frontend/blob/5914a6c1a4bbd839e008c04c01873fe7ac00a9cb/src/translations/translationMetadata.json#L176-L178

Only Persian, Arabic, and Hebrew have "isRTL" flags. 

Though your dashboard looks partially RTL, and partially not, I'm not quite sure where that's coming from.

**Comment by yousaf465** [comment]
Urdu is written in Persian/Arabic script, in fact, Urdu itself is a Turkish word, meaning army.

https://en.wikipedia.org/wiki/Urdu

 it didn't work even before beta. 

We also need to add "isRTL" flags to Urdu. 
@AalianKhan

**Comment by yousaf465** [comment]
starting a pull request.

**Comment by karwosts** [comment]
Completed per #18063
