### ISSUE TITLE
Map label_mode doesn't render the state for `zone` entities

### ISSUE THREAD

**Issue by luca-angemi** [home-assistant/frontend#18054]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If I set an entity in the map card as described I can't see the state label, instead of the name

![image](https://github.com/home-assistant/frontend/assets/9977955/af2dd465-7126-480c-98f4-e91d8ccc0679)
![image](https://github.com/home-assistant/frontend/assets/9977955/628bdedb-0fc7-4f5a-a2a4-d34a92d7e7df)

### Describe the behavior you expected

The label should be the state of the entity, 0 in this case.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.10.0b2

### In which browser are you experiencing the issue with?

Chrome 117

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
This feature was more intended for `sensor` type entities, as `zone` entities already have their own special map renderer to show their MDI icon, so currently that option has no effect for `zone` entities. 

I guess this option could also override that, but I hadn't really considered that case before. 

Is that a feature you'd like to have, to show the number instead of the zone icon? Or were you just testing it for testing sake?

**Comment by luca-angemi** [comment]
I was just testing as currently on my map I've only persons and zones. 

So, just out of curiosity, you could have sensors with lat/long attributes then?

**Comment by karwosts** [comment]
Yep, _any_ entity with a latitude and longitude attribute can be displayed on a map.

**Comment by luca-angemi** [comment]
Interesting, thanks for your answer. 

I guess you can close the issue if nobody is interested in such a feature.

**Comment by karwosts** [comment]
I'll think about it for a bit. At very least the documentation could be clarified.

**Comment by ildar170975** [comment]
Imho domain-based limitations for the new `label_mode` option is not good.

**Comment by piitaya** [comment]
The label is the value display on the map. It's the main information. The tooltip (title) when hovering the information is only extra information. I'm not the `label_mode` should change that. 
Additionally, for other entities, `label_mode` will only change the displayed label, not the tooltip, we will still have an inconsistency if we change the tooltip for zone.

I agree @karwosts, we can explain in the documentation that zone are displayed differenty

**Comment by ildar170975** [comment]
Hmm, I noticed that you are talking about a tooltip - but the only thing I need is a value inside a badge (instead of currently composed from name's first letters). And frankly speaking I was not expecting a changed tooltip.

**Comment by piitaya** [comment]
I wasn't a response to your message. I saw the tooltip on the screenshot so that was to clarify the tooltip 😅
If someone has a use case for the state zone inside the zone, I'm not against adding the support to replace the icon but I'm not sure it can be useful.

**Comment by ildar170975** [comment]
> but I'm not sure it can be useful.

Agree. Useful for sensors mainly. Do not see other use-cases; may be someone else have them...

**Comment by piitaya** [comment]
I updated the documentation. @luca-angemi I close this issue because the `label_mode` is not supported for zone entities because zones are using icon.
