### ISSUE TITLE
Automation editor - repeat for_each erases alias

### ISSUE THREAD

**Issue by jfurtner** [home-assistant/frontend#18065]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using an alias on a repeat loop with for_each (list) configured, editing the for_each value erases the alias.

### Describe the behavior you expected

Keep the alias set by the user

### Steps to reproduce the issue

1. Add repeat foreach with alias:

```
alias: "Repeat for_each: item in static list"
repeat:
  for_each: "{{ [ 'a','b','c','d'] }}"
  sequence: []
```
3. Note the name on the Repeat box matches the alias above _Repeat for_each: item in static list_
4. Using the UI, make a change to the repeat for_each, such as add a service call, or change the jinja template content.
5. Note that the alias is reverted to the default _Repeat an action for every item: "{{ [ 'a','b','c','d'] }}"_
  This is unexpected, the alias should be kept.

### What version of Home Assistant Core has the issue?

core-2023.9.3

### In which browser are you experiencing the issue with?

All tried (Firefox 118, Edge 117)

### Which operating system are you using to run this browser?

Windows 11

**Comment by silamon** [comment]
Play Media, Call Service and Scene action have the same problem.

**Comment by piitaya** [comment]
@silamon I will do another PR for play media, call service and scene action

**Comment by jfurtner** [comment]
@piitaya 

Thank you!
