### ISSUE TITLE
Unable to define a Utility Meter sensors through the Helpers UI that uses a CRON setting instead of cycle/offset

### ISSUE THREAD

**Issue by vorkapps** [home-assistant/frontend#18076]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

While defining a Utility Meter through the Settings -> Devices & Services -> Helpers, there is no method to define a CRON setting for resetting the meter. Using the old YAML configuration you could.

For example I want a utility meter to reset every two months, starting from February, i.e. Feb, Apr, Jun, Aug, Oct and Dec.  The cycle "Every Two Months" starts on Jan and therefore resets on Jan, Mar, May, Jul, Sep, Nov.

The UI should let the user either specify a cycle & optional offset, OR a CRON string, the the yaml configuration properties.

### Describe the behavior you expected

The UI should let the user either specify a cycle & optional offset, OR a CRON string, the the yaml configuration properties.

### Steps to reproduce the issue

1. Define a Utility Meter through Settings -> Devices & Services -> Helpers

### What version of Home Assistant Core has the issue?

2023.9.3

### In which browser are you experiencing the issue with?

N/A

### Which operating system are you using to run this browser?

N/A

**Comment by karwosts** [comment]
This isn't a frontend thing, the fields shown in the UI during helper creation are a function of the `utility_meter` integration in core, the frontend has no control over it. 

So if anything, this would be filed as a core issue against `utility_meter` integration. However I believe it is accepted that UI creation offers less advanced options than yaml configuration, so I don't think this would be accepted as a bug or issue, but rather just a feature request, which will be directed to the community forums.
