### ISSUE TITLE
Frontend not being updated when requested value is rejected by ESPHome

### ISSUE THREAD

**Issue by VivantSenior** [home-assistant/frontend#18085]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Sensor data (ESPHome based) is not being updated on the frontend (device page).

### Describe the behavior you expected

Frontend being updated with the newest sensor data

### Steps to reproduce the issue

1. Create number template sensor in ESPHome.
2. In `set_action` of the sensor create lambda that will reject newly requested value (example in Additional information section).
3. Compile and connect to HA.
4. Change value in the HA frontend.
5. It will be rejected by the ESPHome (which is by design of the lambda statement).
6. Wrong value is presented on the HA frontend. Should be: old value, is: new value which has been requested in the 3rd step.
7. Bonus: After the user will refresh the page with device information UI will show correct (old value).

### What version of Home Assistant Core has the issue?

Home Assistant 2023.9.3

### In which browser are you experiencing the issue with?

Chromium 117.0.5938.140

### Which operating system are you using to run this browser?

Windows 10 22H2

### Additional information

```
number:
  - platform: template
    name: "${friendly_name} current temperature"
    id: current_temperature
    icon: mdi:thermometer
    optimistic: false
    initial_value: 16
    restore_value: true
    min_value: 16
    max_value: 37
    step: 1
    set_action:
      then:
        - lambda: |-
			ESP_LOGD("custom", "In set_action");
			if (false) //this is false just for the test purposes
			{
			  ESP_LOGD("custom", "In if statement");
			  ESP_LOGD("custom", "Old value: %f", id(current_temperature).state);
			  ESP_LOGD("custom", "Newly requested value: %f", x);
			  ESP_LOGD("custom", "Value in HA: %f", id(curr_temp_ha).state);
			  auto call = id(current_temperature).make_call();
			  call.set_value(x);
			  call.perform();
			  ESP_LOGD("custom", "Old value: %f", id(current_temperature).state);
			  ESP_LOGD("custom", "Newly requested value: %f", x);
			  ESP_LOGD("custom", "Value in HA: %f", id(curr_temp_ha).state);
			}
			else
			{
			  ESP_LOGD("custom", "In else statement");
			  ESP_LOGD("custom", "Old value: %f", id(current_temperature).state);
			  ESP_LOGD("custom", "Newly requested value: %f", x);
			  ESP_LOGD("custom", "Value in HA: %f", id(curr_temp_ha).state);
			  ESP_LOGD("custom", "Publishing old value (is it necessary?");
			  id(current_temperature).publish_state(id(current_temperature).state);
			  ESP_LOGD("custom", "Old value: %f", id(current_temperature).state);
			  ESP_LOGD("custom", "Newly requested value: %f", x);
			  ESP_LOGD("custom", "Value in HA: %f", id(curr_temp_ha).state);
			}
```
Sensor that reads data from HA:
```
sensor:
  - platform: homeassistant
    id: curr_temp_ha
    name: "Current temperature in HA"
    entity_id: number.bathroom_air_heater_current_temperature
```

**Comment by karwosts** [comment]
I think we can probably do something for this. For a toggle, when we hit it we wait two seconds, and then if the state hasn't updated in that time, we flip the toggle back to the original state. 

Could probably do a similar for a number input.

**Comment by VivantSenior** [comment]
> I think we can probably do something for this. For a toggle, when we hit it we wait two seconds, and then if the state hasn't updated in that time, we flip the toggle back to the original state.
> 
> Could probably do a similar for a number input.

If you are sure that this will help :) but I think 2 seconds is an arbitrary number and could not handle every use case. What if ESPHome has some delay in `set_action` or WiFi connection is poor.

**Comment by ssieb** [comment]
Then the ui will update when the value changes.

**Comment by karwosts** [comment]
This seems relevant: 
https://github.com/home-assistant/architecture/discussions/740
https://github.com/home-assistant/frontend/pull/16497#issuecomment-1752608794

**Comment by ssieb** [comment]
This isn't stale.
