### ISSUE TITLE
Sensibo / Climate Popup - Since updated climate popup, unable to set fan to strong

### ISSUE THREAD

**Issue by cathelest** [home-assistant/frontend#18105]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Ever since the recent climate card change, now when I try to set the fan speed to medium low or strong, i get a alert popup that states
Failed to call service climate/set_fan_mode. Climate fan mode strong is not supported by the intergration, please open an issue .

### Describe the behavior you expected

Should allow me to set fan speed to medium low, or strong like previous entity popup.

### Steps to reproduce the issue

Standard popup for the climate entity

### What version of Home Assistant Core has the issue?

2023.9.2

### In which browser are you experiencing the issue with?

Firefox (Desktop) and Chrome (Mobile)

### Which operating system are you using to run this browser?

Windows (Desktop) and Android (Mobile)

### State of relevant entities

```txt
hvac_modes: heat_cool, cool, dry, fan_only, heat, off
min_temp: 0
max_temp: 1
target_temp_step: 1
fan_modes: auto, high, low, medium, medium_high, medium_low, quiet, strong
swing_modes: rangefull, stopped
current_temperature: 25
temperature: null
current_humidity: 61.8
fan_mode: medium_high
swing_mode: stopped
friendly_name: Daikin
supported_features: 41
icon: mdi:air-conditioner
```

### Problem-relevant frontend configuration

```yaml
Not a particular card but the pop for the entity.

The 8 fan modes are detected correctly vs the sensibo app.
```

**Comment by cathelest** [comment]
![new card](https://github.com/home-assistant/frontend/assets/52036639/2b26875a-7ed9-486c-bcb7-83fa63a21d9e)
![popup](https://github.com/home-assistant/frontend/assets/52036639/8a3e7b3f-ee1c-471c-ba5b-bcbcf4bde189)

**Comment by cathelest** [comment]
![sensibo](https://github.com/home-assistant/frontend/assets/52036639/27ce2771-d8f4-43ab-959f-eae67ab4e39f)
![entity](https://github.com/home-assistant/frontend/assets/52036639/ae424688-526d-4dbf-9317-9981e11f9ec2)

**Comment by karwosts** [comment]
Does it work if you try to set fan_mode strong with just a service call, like from developer tools? Or from anywhere else in the frontend?

**Comment by cathelest** [comment]
Hello sorry for delayed response,

I have updated HA to 2023.10.0 Today, and the strong option is now working (Guessing something may have changed?)
But mediam_low still does not,

**Comment by cathelest** [comment]
![daikin med low](https://github.com/home-assistant/frontend/assets/52036639/807c756a-3d03-4ed9-b443-a29eb61cea75)

**Comment by karwosts** [comment]
I don't see that medium_low is a fan speed that this integration supports. Does it still show up in your fan_modes list after updating?

**Comment by cathelest** [comment]
Yes, Updated to 2023.10.1 few mins ago,

Just check and still shows

"fan_modes: quiet, low, medium_low, medium, medium_high, high, auto, strong"

Many thanks for your help and time, really appreciate it,

**Comment by karwosts** [comment]
I would suggest just open a core issue against Sensibo. That error message is a response from the integration, the core integration author would need to understand why core is returning that message. I don't think that's something can be solved in frontend.

**Comment by cathelest** [comment]
Moved to core. As strong fan speed was fixed in 
https://github.com/home-assistant/core/issues/100101

**Comment by gjohansson-ST** [comment]
I close this as it's duplicate and a fix has been made so will come shortly. https://github.com/home-assistant/core/pull/101883
