### ISSUE TITLE
IMG from URL in Picture Card not updating

### ISSUE THREAD

**Issue by brad-newman** [home-assistant/frontend#18108]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I’m using a Picture Card to pull in an image from a website to a dashboard. The image changes every other day but maintains the same URL. However, the image won’t update unless I clear my browser cache (or in the case of iOS companion app, until I go to debugging > reset frontend cache). This behavior is present on web and iOS.

### Describe the behavior you expected

Expect the image to be refreshed on-load or at a user-specified interval. 

### Steps to reproduce the issue

1. Add a Picture Card on a Dashboard
2. Use an external URL as the image source
3. Change the image at the source while maintaining the same URL
4. Reload Dashboard

### What version of Home Assistant Core has the issue?

Home Assistant 2023.9.3 Supervisor 2023.09.2 Operating System 10.5 Frontend 20230911.0 - latest

**Comment by steverep** [comment]
This is not something HA has control over.  The website serving the image tells the browser how to cache it via the [`Cache-Control` response header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control).  If you share the URL, I can probably explain in more detail by inspecting the headers.
