### ISSUE TITLE
Language 'Test' bricks UI

### ISSUE THREAD

**Issue by warddos** [home-assistant/frontend#18115]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On the user profile page (`<hass-domain>/profile>`), in the language dropdown select, there is a language called 'Test'. Out of curiosity, I picked it and it bricked the entire front end.
The side nav would not load, most of the pages would not load and the pages that did load only showed errors or certain parts of the UI.

![image](https://github.com/home-assistant/frontend/assets/82801973/3a1102e7-9534-4b30-a4d8-2c5e59a0506c)

![image](https://github.com/home-assistant/frontend/assets/82801973/46dac228-eeb8-453b-8f60-aab10dfaa5d1)

### Describe the behavior you expected

Either one of the two things:
- To not have 'Test' as a language
- To not brick the entire front end when the 'Test' language is selected

### Steps to reproduce the issue

Keep in mind that there is no way to fix this from within the UI, so reproduce at your own risk!

1. Go to your user's profile page.
2. Open the 'language' dropdown.
3. Select 'Test' as your new language.
4. Things start to break already (no translation labels), after a page reload the 'page' won't load and show an error instead.

### What version of Home Assistant Core has the issue?

2023.9.3

### In which browser are you experiencing the issue with?

Google Chrome 117.0.5938.92, FireFox 118.0.1

### Which operating system are you using to run this browser?

Windows 10, Windows 11

### Javascript errors shown in your browser console/inspector

```txt
(anonymous) @ logging-mixin.ts:66
provide_hass.ts:287 unmocked callService system_log write {logger: 'frontend.js.latest.DEMO-202310020', message: 'Unhandled promise rejection from Chrome 117.0.0.0 …tTimeout (src/state/translations-mixin.ts:449:12)', level: 'debug'}
provide_hass.ts:287 unmocked callService system_log write {logger: 'frontend.js.latest.DEMO-202310020', message: 'Unhandled promise rejection from Chrome 117.0.0.0 …tTimeout (src/state/translations-mixin.ts:449:12)', level: 'debug'}
provide_hass.ts:287 unmocked callService system_log write {logger: 'frontend.js.latest.DEMO-202310020', message: 'Unhandled promise rejection from Chrome 117.0.0.0 …tTimeout (src/state/translations-mixin.ts:449:12)', level: 'debug'}
provide_hass.ts:287 unmocked callService system_log write {logger: 'frontend.js.latest.DEMO-202310020', message: 'Unhandled promise rejection from Chrome 117.0.0.0 …tTimeout (src/state/translations-mixin.ts:449:12)', level: 'debug'}
provide_hass.ts:287 unmocked callService system_log write {logger: 'frontend.js.latest.DEMO-202310020', message: 'Unhandled promise rejection from Chrome 117.0.0.0 …tTimeout (src/state/translations-mixin.ts:449:12)', level: 'debug'}
provide_hass.ts:287 unmocked callService system_log write {logger: 'frontend.js.latest.DEMO-202310020', message: 'Unhandled promise rejection from Chrome 117.0.0.0 …tTimeout (src/state/translations-mixin.ts:449:12)', level: 'debug'}
provide_hass.ts:287 unmocked callService system_log write {logger: 'frontend.js.latest.DEMO-202310020', message: 'Unhandled promise rejection from Chrome 117.0.0.0 …tTimeout (src/state/translations-mixin.ts:449:12)', level: 'debug'}
provide_hass.ts:287 unmocked callService system_log write {logger: 'frontend.js.latest.DEMO-202310020', message: 'Unhandled promise rejection from Chrome 117.0.0.0 …tTimeout (src/state/translations-mixin.ts:449:12)', level: 'debug'}
provide_hass.ts:287 unmocked callService system_log write {logger: 'frontend.js.latest.DEMO-202310020', message: 'Unhandled promise rejection from Chrome 117.0.0.0 …tTimeout (src/state/translations-mixin.ts:449:12)', level: 'debug'}
provide_hass.ts:287 unmocked callService system_log write {logger: 'frontend.js.latest.DEMO-202310020', message: 'Unhandled promise rejection from Chrome 117.0.0.0 …tTimeout (src/state/translations-mixin.ts:449:12)', level: 'debug'}
```

**Comment by KTibow** [comment]
It's supposed to show what's translated and what's not. It's not supposed to be choosable in a prod build.

**Comment by karwosts** [comment]
Related: #17507 #17189

Oddly it claims this was removed in 2023.9, not sure why it's still showing.

**Comment by KTibow** [comment]
I bet that #17507 removed the code to generate the translation files but not remove the translation from the list of available languages.

**Comment by steverep** [comment]
> I bet that #17507 removed the code to generate the translation files but not remove the translation from the list of available languages.

Yup, I missed part of the fix.  I'll take care of it. 👍🏻

**Comment by warddos** [comment]
@steverep Thanks for resolving the issue!
