### ISSUE TITLE
Wrong translation to Danish in climate "more info" dialog

### ISSUE THREAD

**Issue by emkaywest** [home-assistant/frontend#18116]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The language I'm using in HA is Danish. When I use the more info dialog of a climate entity card, then in English it would say "Heating to target". The word "target" has been translated to "modtager" in Danish which does not make sense. 

### Describe the behavior you expected

It should rather be "indstilling" in Danish. So the full Danish sentence would be "Opvarmer til indstilling". 

### Steps to reproduce the issue

1. Set language to Danish
2. Use Climate entity card and select the more info dialog
3. Observe the word "modtager" (attempt to translate "target")
...

### What version of Home Assistant Core has the issue?

core-2023.9.3

**Comment by karwosts** [comment]
If you want to contribute an alternative translation, you can follow the directions here: https://developers.home-assistant.io/docs/translations/

Individual word translations are not tracked in this repository, you need to do it through localise.

**Comment by emkaywest** [comment]
I just found out that when the state is "not heating" then the translation is correct. So now the current behavior (if I translate to English):
When it's not heating: "Target"
When it's heating: "Heating to receiver" (Should say Heating to target).

Is this still just considered a matter of "translation preference"?
