### ISSUE TITLE
Scripts name updated via UI are not reflected in the yaml code and therefore in their frontend usage.

### ISSUE THREAD

**Issue by matteo-martinelli** [home-assistant/frontend#18111]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

A script name have been changed via the UI, and the result is the one depicted in the picture below: 

![image](https://github.com/home-assistant/frontend/assets/52628801/25962961-05c4-4211-bc73-f476e4ab6fb2)

Previous script name was "send_message_to_selected_alexa_speaker", modified script name via UI is "livingdot_play_alexa_music_on_selected_speaker".

The bug stands in the following: even if I restarted the server several time, and followed the checklist proposed in the Issues section, the script name have not been updated in the "backend", i.e. in the config files, as depicted in the image below.

![image](https://github.com/home-assistant/frontend/assets/52628801/ed78d466-0f74-4e51-a7fd-94bc5ea2e2ca)

The result is that if I try to call the script in the frontend, I need to use the "backend" name instead of the name declared via UI.

Even if I understood the problem, I believe that the ability to modify a script (or maybe any other entity/automation/anything else) name via UI is not clearly reflected in the actual result. 

In other words, I suspect that it is not the intended behaviour. 

(Nevertheless, HA still awesome!)
 

### Describe the behavior you expected

If I change an entity/automation/script name via UI, I expect to use the UI declared name in my dashboard, and not the old one. 

### Steps to reproduce the issue

1. create a script in the frontend
2. assign the script to a button/something that triggers the script
3. change the script name via UI
4. try to reassign the new name in the frontend to the button/something that triggers the script

The expected result is that is impossible for HA to find the script.

### What version of Home Assistant Core has the issue?

Home Assistant 2023.9.3 Supervisor 2023.09.2 Operating System 10.5 Frontend 20230911.0 - latest

### What was the last working version of Home Assistant Core?

Home Assistant 2023.9.3 Supervisor 2023.09.2 Operating System 10.5 Frontend 20230911.0 - latest

### In which browser are you experiencing the issue with?

Google Chrome 117.0.5938.132

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment]
Seems like a duplicate issue of #14140.
