### ISSUE TITLE
Slow UI on 2023.9/2023.10

### ISSUE THREAD

**Issue by cpuks** [home-assistant/frontend#18127]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This refers to https://github.com/home-assistant/core/issues/100005
Since I've upgraded to 2023.9 release along with 10.5 OS I have experienced very slow UI response although CPU usage and mem show nothing special - same as before. This shouldn't be an issue as a VM that runs HA has 2 x Intel 1240p cores and 4 GB RAM - so far for over a year on this machine experience has been flawless in terms of UI, now when I have to change anything via GUI it's really worse than RPi3B experience.

### Describe the behavior you expected

On such specs (CPU and MEM wise) UI should be very responsive.

### Steps to reproduce the issue

In the linked issue that was open for HA core I posted a video recording along with some logs that clearly show the issue (UI unresponsiveness)

### What version of Home Assistant Core has the issue?

2023.10.0

### What was the last working version of Home Assistant Core?

2023.8.2

### In which browser are you experiencing the issue with?

Edge 117.0.2045.47 (Windows) / Edge 117.0.2045.47 (Android) / Safar (iPadOS 17.1b2))

### Which operating system are you using to run this browser?

Android 13 / Windows 11 / iPadOS 17.1b2

**Comment by steverep** [comment]
@cpuks to avoid confusion for everyone, let's not have 2 issues open for the same problem.  If we determine there's a frontend cause on the referenced issue, we can always transfer it here to fix.
