### ISSUE TITLE
Automation Traces in Safari not working properly

### ISSUE THREAD

**Issue by schmuy** [home-assistant/frontend#18135]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When viewing traces for an automation in Safari, the flowchart...
1.  doesn't render properly
2. Clicking on nodes does not provide any step details

Screenshots showing the difference between Safari and Firefox on the same trace.
<img width="1093" alt="Screenshot 2023-10-06 at 10 20 36" src="https://github.com/home-assistant/frontend/assets/93694290/d8c42028-2cd4-42a1-949e-5a144f648eb8">
<img width="1197" alt="Screenshot 2023-10-06 at 10 20 27" src="https://github.com/home-assistant/frontend/assets/93694290/edf0aa63-18f0-4c26-ae7c-d43b23545a9d">

### Describe the behavior you expected

1. The flowchart to render as it does in other browsers
2. Clicking on nodes to provide step details

### Steps to reproduce the issue

1. View Traces in Automation in Safari

### What version of Home Assistant Core has the issue?

2023.10.0

### In which browser are you experiencing the issue with?

Safari 17.0

### Which operating system are you using to run this browser?

MacOS Sonoma 14.0

**Comment by avdbrink** [comment]
Duplicate of #10581
