### ISSUE TITLE
ZHA Configuration backup from companion app.

### ISSUE THREAD

**Issue by carlmidson** [home-assistant/frontend#18136]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the ZHA configuration panel you can select backup this works in the browser and doesn't in the companion app.  

### Describe the behavior you expected

Fair enough on a mobile device but it really needs to inform the user you need to be using a browser.  Not sure why it cannot from a companion app installed on a desktop machine.  in my case a Mac.

### Steps to reproduce the issue

1.install ZHA
2.On companion app enter ZHA configuration
3.Attempt backup
...

### What version of Home Assistant Core has the issue?

2023.9.3

### In which browser are you experiencing the issue with?

na

### Which operating system are you using to run this browser?

Sonoma 14.0

**Comment by carlmidson** [comment]
Not sure if this is the correct place to leave this....

**Comment by Hedda** [comment]
> Not sure if this is the correct place to leave this....

If the issue is in companion apps then this probably belongs in the `android` and/or `iOS` repository/repositories instead, see:

https://github.com/home-assistant/android

https://github.com/home-assistant/iOS
