### ISSUE TITLE
Allow device_class None to be set

### ISSUE THREAD

**Issue by CFenner** [home-assistant/frontend#18133]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have an integration running (`vicare`) that displays a sensor, that has in my eyes the wrong `device_class` (`POWER`). 

<img width="344" alt="Bildschirmfoto 2023-10-06 um 10 00 03" src="https://github.com/home-assistant/frontend/assets/9592452/98784d3c-1ca5-4937-9d8b-7b1bdccd50a2">

While this is already addressed in https://github.com/home-assistant/core/pull/101476 it would be nice to "fix" this via the ui by selecting `device_class` as `None`. When selecting "" in the dropdown, the default is used.

<img width="600" alt="Bildschirmfoto 2023-10-06 um 09 57 29" src="https://github.com/home-assistant/frontend/assets/9592452/ce4ad288-8b59-4e79-b78b-d6d49224e297">

### Describe the behavior you expected

I would like so be able to explicitly select `None` as `device_class`.

### Steps to reproduce the issue

1. take any entity that has a predefined `device_class
2. try to change the device_class to None
3.
...

### What version of Home Assistant Core has the issue?

core-2023.10.0

### In which browser are you experiencing the issue with?

Safari

**Comment by karwosts** [comment]
I'm not sure core supports this, it seems to always default back to `original_device_class` if device_class is not set. Probably a bigger scope change than just a frontend ui change.
