### ISSUE TITLE
Replacing NextBus YAML with new Integration in 2023.10 does not allow creating Entities for all Bus Routes

### ISSUE THREAD

**Issue by android52** [home-assistant/frontend#18140]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I was using NextBus via YAML prior to 2023.10 and had 3 different routes setup and working.  I commented out the YAML and loaded the new Integration, but am only able to load 1 of the 3 routes.  When trying to load other routes I can select the Agency, but when I select either of the 2 other routes from the dropdown list I get a message that an "Unknown error occurred".

I see no messages in the logs.

![image](https://github.com/home-assistant/frontend/assets/53939853/9e3dbb84-0743-4b48-8ee6-153caf11cec9)

It seems specific to the routes I am selecting (not posting them here as would clearly indicate my geographic location), as other routes do work. 

I've tried in Chrome and Chrome in Incognito, in Edge the Agency list does not even appear.

### Describe the behavior you expected

I expected that after selecting the agency and route the newly added route would appear as a new entity under the NextBus integration.

### Steps to reproduce the issue

1.  Load NextBus integration
2. Open Integration
3. Click Add Entry
4. Select Agency, and click Submit
5. Select Route and click Submit
...

### What version of Home Assistant Core has the issue?

2023.10 (container)

### What was the last working version of Home Assistant Core?

2023.9 with yaml configuration of NextBus

### In which browser are you experiencing the issue with?

Google Chrome 117.0.5938.149 (also Incognito) and Edge 117.0.2045.47

### Which operating system are you using to run this browser?

Windows 10

**Comment by android52** [comment]
I know since this is only happening to a specific routes I will need to provide that information, when investigating, I will share.

**Comment by karwosts** [comment]
This might be better filed in core and tagged with the integration, frontend doesn't deal much with integration specific logic. 

An issue in core will get you in contact with the NextBus codeowners who can help you.

**Comment by android52** [comment]
Moved to Core with issue #101581
