### ISSUE TITLE
Doesn't parse HTML multi escape sequence codes on templates

### ISSUE THREAD

**Issue by t3lmoazevedo** [home-assistant/frontend#18145]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The template parser doesn't recognize anymore the more-than-one escape sequence HTML codes.
Examples:
🔋 \uD83D\uDD0B
🐌 \uD83D\uDC0C
🌡️ \uD83C\uDF21\uFE0F

The error applies for Wear OS and companion app plugins also.

### Describe the behavior you expected

![image](https://github.com/home-assistant/frontend/assets/41584793/8b0897c2-d2bf-433b-9e93-96f12596de21)

Before this problem it was possible these template layout examples...

![image](https://github.com/home-assistant/frontend/assets/41584793/eca6f6ad-50ab-42d5-8891-6a401edc0df2)

![image](https://github.com/home-assistant/frontend/assets/41584793/57f825e9-2662-4747-aac6-5572b3fddd65)

### Steps to reproduce the issue

Try the templating at the /developer-tools/template
with  and without multi-escape sequences, like:

<html><body>
<p>{{"\u231B"}}</p>
</body></html>

and

<html><body>
<p>{{"\u231B"}}</p>
<p>{{"\uD83C\uDF21\uFE0F"}}</p>
</body></html>

### What version of Home Assistant Core has the issue?

Home Assistant 2023.10.1

**Comment by t3lmoazevedo** [comment]
The problem hasn't been fixed and still remains.
The escpae sequence characters break the template editor or any print using them.

<html><body>
<p></p>
</body></html>
... shows ok!

<html><body>
<p></p>
<p>{{"\uD83C"}}</p>
</body></html>
... shows nothing!

![image](https://github.com/home-assistant/frontend/assets/41584793/68a6d5e4-d1f0-425e-8a9f-dc006d66b2cf)

**Comment by karwosts** [comment]
I might suggest a home-assistant/core issue for this instead. I admit I don't really understand what you're doing, but when I put in this template I get an error from core:

```
2024-01-05 11:55:03.886 ERROR (MainThread) [homeassistant.components.websocket_api.messages] Unable to serialize to JSON. Bad data found at $.event.result=\ud83d\udc0c(<class 'str'>
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 155-156: surrogates not allowed
Call stack:
  File "/usr/lib/python3.11/threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
Message: "Unable to serialize to JSON. Bad data found at $.event.result=\ud83d\udc0c(<class 'str'>"
```

I'm not familiar with this kind of emoji rendering, but it would seem that core needs to do something differently if this is to work. Not sure what the frontend could do.

**Comment by t3lmoazevedo** [comment]
The template were working nice before, also with those html sequence charaters, like presented on the HA examples and plugins screens above, for Wear OS.

![image](https://github.com/home-assistant/frontend/assets/41584793/372d1e16-fbc1-4b76-99fb-5e58da49e907)

**Comment by karwosts** [comment]
> The template were working nice before

Ok, I believe that, but that doesn't change my answer. Frontend sends the template string that you entered to the backend. Backend tries to render a response and throws an exception instead.

I don't know what differently could be done in frontend to make this work, if it is the backend that is not able to process it. 

So I still suggest filing a core issue instead.

**Comment by t3lmoazevedo** [comment]
> So I still suggest filing a core issue instead.

Thanks for the sugestion! Will do so ;)

**Comment by t3lmoazevedo** [comment]
Issue open in /core:

https://github.com/home-assistant/core/issues/107328
