### ISSUE TITLE
Energy Dashboard Net Consumed Gauge text scaling

### ISSUE THREAD

**Issue by braamvh** [home-assistant/frontend#18149]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On the energy dashboard, in Day view, when moving from day to day, the text displayed in the Net consumed from the grid gauge changes scaling based on the length of the text. In some cases, the text does not scale down properly, causing text to be cut off.

I have only seen this in Day view, not Week and Month.

### Describe the behavior you expected

Text should not be cut off by the gauge itself.

### Steps to reproduce the issue

Will demonstratewith images

### What version of Home Assistant Core has the issue?

Home Assistant 2023.10.1

### In which browser are you experiencing the issue with?

Firefox 118.0.1

### Which operating system are you using to run this browser?

Windows 10 22H2

### Additional information

I see the same behaviour in the Android Companion App.

1) Moving between days in seqence, the scaling auto-adapts, but breaks if there are decimals.
a) October 4:  Correct display
![image](https://github.com/home-assistant/frontend/assets/18083894/533bc5ca-ab68-4b5d-bec2-77d741f690e1)

b) October 5: Correct display
![image](https://github.com/home-assistant/frontend/assets/18083894/3ea80909-6090-426b-8f58-66391f9054f0)

c) October 6: Text should read "8.3 kWh"
![image](https://github.com/home-assistant/frontend/assets/18083894/d33336fd-f3b5-42c8-8e6c-11fdd90d8f64)

2) After a reload of the dashboard, moving the opposite way:

a) October 8: 
![image](https://github.com/home-assistant/frontend/assets/18083894/bb953804-cccc-4abf-8781-25189e22b6a0)

b) October 7:  Should read 12.2 kWh
![image](https://github.com/home-assistant/frontend/assets/18083894/5337f59d-f009-4f64-bc0e-501c2de3065a)

c) October 6: This is displayed correctly, even though it was wrong in 1c above.
![image](https://github.com/home-assistant/frontend/assets/18083894/5f962bbf-fb43-4bc5-a260-c90fd7faddc3)

From what I can see, the text is either correct or incorrect for values with decimal places, but it uses the scaling from the previous entry, not an appropriate scaling for the current value. Values that have no decimals seems to work correctly.

**Comment by karwosts** [comment]
Hm I don't notice this. Is there anything non-standard about your setup maybe, any specific custom resources you are loading?


![gauge](https://github.com/home-assistant/frontend/assets/32912880/e91c90b7-635e-46d6-a6b9-1abbd5766d2e)

**Comment by braamvh** [comment]
I had 2 custom lovelace cards loaded, and have 7 active custom integrations. I removed the 2 lovelace cards, made sure my config/www directory is empty, and loaded HA in a new browser window where I have not loaded it before, using Chrome 117.0.5938.150. I am still seeing the same behaviour on my end, though.

**Comment by braamvh** [comment]
The latest version of the Frontend ( 20231030.1 ) resolved this issue for me. Thank you.
