### ISSUE TITLE
Dynalite integration not syncing devices when config edited

### ISSUE THREAD

**Issue by petehhhhh** [home-assistant/frontend#18173]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a Dynalite install with 200 entities. I setup original via configuration.yaml. I just noticed that one of my lights was missing. It is channel 5 in Area 23. There are a total of 10 channels in that area. The channel was setup there and I deleted the channel and re-created. The device/entity did not get created. I tried deleting the channel: the devices/entities did not get deleted. I then tried re-creating the entity. When created with 10 channels it just didn't show up. When I created with 3 entities it did show up but there was no changes to devices and entities. I am now stuck and cannot add that missing channel. 

### Describe the behavior you expected

When I edit/change the dynalite configuration, that the devies/entities are kept in sync with the config

### Steps to reproduce the issue

1. Per above, edit/change config. Devices/Entities are not synchronised. I have tried restarting, reloaded etc.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.10.1

### What was the last working version of Home Assistant Core?

2023.10.1

### In which browser are you experiencing the issue with?

Safari

### Which operating system are you using to run this browser?

13.4 (22F66)

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
Using in built dynalite configuration tool
```

### Javascript errors shown in your browser console/inspector

```txt
None
```

### Additional information

N/A

**Comment by karwosts** [comment]
I think you're in the wrong place, this seems like a home-assistant/core issue, not frontend.

**Comment by petehhhhh** [comment]
apols. I will close and open there.
