### ISSUE TITLE
Duplicate log entries show up in the more info view

### ISSUE THREAD

**Issue by apaperclip** [home-assistant/frontend#18170]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When viewing the logs of an entity in the more-info window if I click on a different tab, then come back to the HA tab, the og entries are duplicated. It appears like the logs window is refreshing and the same logs are retrieved and displayed with the logs already on the screen.

### Describe the behavior you expected

Log entires should not be duplicated when returning to the HA tab.

### Steps to reproduce the issue

1. Click on an entity
2. Click the little graph icon in upper right to display history/logbook (more-info?)
3. Click on a different tab in your browser and wait some time (10-15m should do it)
4. Periodically check back to the HA tab, the logs will be duplicated.

### What version of Home Assistant Core has the issue?

2023.10.1

### What was the last working version of Home Assistant Core?

something before 2023.8.4 but not sure what version.

### In which browser are you experiencing the issue with?

Google Chrome 119.0.6045.9  64bit 

### Which operating system are you using to run this browser?

Windows 10 

### Additional information

This exists in Chrome on an android phone as well and in the android app.  This also occurs on 2023.8.4

I also tested Edge and it happens there too.

**Comment by karwosts** [comment]
Likely duplicate of #17769

**Comment by apaperclip** [comment]
> Likely duplicate of #17769

bah! i even searched first!  I agree,  looks the same and that one has more info. I'll close this one

Thanks!
