### ISSUE TITLE
UI text does not correctly change for Numerical State Conditions when above or below is 0.

### ISSUE THREAD

**Issue by aredon** [home-assistant/frontend#18171]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When building an automation with a Numeric State Condition, for example, when home is above 1. The title changes to "When Home is above 1". 

However, when above is set to 0 the UI assumes that the condition is not configured and changes the title to "Numerical State Condition". This gives the impression that it will not work when it, in fact, will. This seems like the classic zero-is-null error to me. 

### Describe the behavior you expected

The title to change to "When Home is above 0"

### Steps to reproduce the issue

1. Create an Automation
2. Add a numerical state condition
3. Set either above or below to 0
...

### What version of Home Assistant Core has the issue?

2023.10.1

**Comment by silamon** [comment]
Fixed through #18171. Thanks for the report. It was a classic zero-is-null error.
