### ISSUE TITLE
Energy dashboard and History Graph Card not respecting locale setting for time line

### ISSUE THREAD

**Issue by rosch100** [home-assistant/frontend#18202]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The energy dashboard does not show the correct time of day, when browsing from a different time zone. The dashboard uses the time zone of the client, not the home assistant server.
In the example, the server is in Germany, the client in the Eastern US. Thus, the time is off by six hours.
<img width="931" alt="Bildschirmfoto 2023-10-12 um 14 17 45" src="https://github.com/home-assistant/frontend/assets/5745224/5d8de868-4fbf-4558-a7b5-75453586a7fc">

### Describe the behavior you expected

Dashboard presents time zone of server.

### Steps to reproduce the issue

Change the time zone of a client and browse to your dashboard. You will notice that the time of the client will be displayed.

### What version of Home Assistant Core has the issue?

Home Assistant 2023.10.2

### In which browser are you experiencing the issue with?

Safari 17.1

**Comment by rosch100** [comment]
It seems to be an issue with all time line dashboards. The History Graph Card shows the same behavior.

**Comment by rosch100** [comment]
Still an issue! Anyone?

**Comment by bramkragten** [comment]
What is your setting for timezone in your profile?

**Comment by rosch100** [comment]
The time zone of the HA server is set to:
Zeitzone
(GMT+01:00) Berlin
