### ISSUE TITLE
Radio Station names are truncated in Radio Browser in mobile app

### ISSUE THREAD

**Issue by dunxd** [home-assistant/frontend#18225]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When viewing the list of radio stations with the mobile app, the names are truncated cutting off everything after the first 9 characters in some cases. This makes it impossible to locate a specific radio station - e.g. [BBC has 109 entries in the  Radio Browser database starting with "BBC Radio"](https://www.radio-browser.info/search?page=11&order=name&reverse=true&hidebroken=true&name=BBC%20Radio). The icons for the radio station are often not helpful to identify the specific station, so the text needs to be.

![Screenshot_20231009-135910](https://github.com/home-assistant/core/assets/16608541/393f6b3a-1448-4c4b-8112-f6fd5b5f9556)

I expect this is an issue specific to smaller devices, as the truncation is less of an issue when viewing Home Assistant interface through a desktop browser where there is more width available.

### Describe the behavior you expected

It would be better if the entire name was wrapped if necessary rather than truncating away useful information. A list option would be nice, rather than limiting the number of items displayed based on an often empty or info free image.  In cases where multiple streams are available for the same station, it would be even more helpful to have some way of displaying additional info to tell the difference between the entries, such as the format, bitrate etc. For example,[ BBC Radio 6 Music has 6 entries in the Radio Browser database](https://www.radio-browser.info/search?page=1&order=name&reverse=false&hidebroken=true&name=BBC%20Radio%206%20Mus), all named the same, but with different qualities.

### Steps to reproduce the issue

1. Install Radio Browser app
2. Browse radio stations from any entry point, such as Media > Radio Browser > United Kingdom
3. Try and locate a specific radio station starting with "BBC Radio"
4. Same issue with radio stations in other countries

### What version of Home Assistant Core has the issue?

2023.10.3

### In which browser are you experiencing the issue with?

Companion App 2023.10.2-full

### Which operating system are you using to run this browser?

Android 13

### Additional information

Originally logged at https://github.com/home-assistant/core/issues/101704 where it was suggested I repost it here. Someone suggested it may be an issue with the media browser, and indeed the truncation happens there, so anything other than a short filename with most relevant info at the start of not useful.

**Comment by budius** [comment]
Reposting my comment here from the original core/issues/101704 to add the info here:

------------------------

Thanks for the nice bug report, I don't develop at home assistant, but as a developer I appreciate. 

I came to GitHub to file the same report, so, +1 here, following this and hoping for a fix soon.

The problem is also very noticeable on the German language stations. There are hundreds of them and stations often have multiple streams.

> I expect this is an issue specific to smaller devices, as the truncation is less of an issue when viewing Home Assistant interface through a desktop browser where there is more width available.

A correction, this is an issue everywhere! I got a medium/big phone (pixel 7) and also tested on my 15" laptop. On the bigger screen the grid is rendered in a dialog/popup that still truncate the names.

Thanks! Following the thread!

**Comment by karwosts** [comment]
I add a grid / list toggle option in #18256. 

I'm not much of a CSS designer so I'll leave dealing with the truncation for someone else, but this should help alleviate your difficulties.

**Comment by dunxd** [comment]
Following the PR in Media Browser (#18256), the suggestion was made that Radio Browser could just default to list view rather than requiring a change in Media Browser to allow users to switch views. How hard is that?

**Comment by bramkragten** [comment]
@dunxd not hard, the integration provides a media type, based on that type the layout is chosen currently:

https://github.com/home-assistant/core/blob/dev/homeassistant/components/radio_browser/media_source.py#L206-L207

Changing that to something else will change the layout, or maybe we even have to add a new one.

**Comment by budius** [comment]
Any updates here?
The changes shown by @bramkragten are perfect. What's the hold up?
