### ISSUE TITLE
icon color lock

### ISSUE THREAD

**Issue by Duese911** [home-assistant/frontend#18222]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

why is the lock icon displayed in red when the door is unlocked? Wouldn't it be more logical if open was green? Am I doing something wrong?

### Describe the behavior you expected

red is closed, you can't get in, it's occupied or something like that.
green means it is free and the door can be opened

### Steps to reproduce the issue

1. icon lock
2.
3.
...
![Unbenannt](https://github.com/home-assistant/frontend/assets/66550258/bc311e2d-19bd-4c56-9039-58ba85154508)

### What version of Home Assistant Core has the issue?

Home Assistant 2023.10.3

**Comment by ildar170975** [comment]
1. Please do not get offended, but I suggest you to provide screenshots in English. Then more people will understand you faster.

2. For a security point of view, an unlocked door is a "danger" - that is why it is red.
But I agree that SOME locks may be "normally open" - i.e. "open = good", "open = good".
A currently possible workaround for these particular cases is to re-define state colors (closed=red, open=green). This may be done by card-mod for a particular UI card (by re-defining corresponding theme CSS variables). Unfortunately, more-info dialog will still have default colors (closed=green, open=red).
Another possible away (currently not available) is either implementing a new device_class like "lock_normally_open" or adding an attribute to a "lock" entity like "normally_open: true/false".

**Comment by karwosts** [comment]
You don't need card mod, these values are themeable:

    mytheme:
      state-lock-locked-color: "#ff0000"
      state-lock-unlocked-color: "#00ff00"


![image](https://github.com/home-assistant/frontend/assets/32912880/32961b77-faf3-4029-a60d-0c46faa5fa22)

![image](https://github.com/home-assistant/frontend/assets/32912880/620b4b26-4731-49eb-b82e-9b7c596ce5fa)

**Comment by ildar170975** [comment]
> You don't need card mod, these values are themeable.

Unfortunately, card-mod is needed if a person needs to modify a particular element.
If some card has ONE lock - then it is enough to define a custom theme for this card (if this only lock should be customized).
If some card has more locks - and one of them is "normally open" - then probably a person may want to customize only one of them, then card-mod is needed.
If a custom theme is set globally, it will affect all locks, even locks which are "normally closed".

As for more-info: if a custom theme is set globally, it will affect all more-info for all locks, even for locks which are "normally closed".
There is a way to customize a more-info for a particular lock entity - it will need a card-mod-theme method.

**Comment by Duese911** [comment]
> mytheme:
>   state-lock-locked-color: "#ff0000"
>   state-lock-unlocked-color: "#00ff00"

where is the value inserted?

**Comment by karwosts** [comment]
> where is the value inserted?

https://www.home-assistant.io/integrations/frontend/#defining-themes
