### ISSUE TITLE
Missing in lokalise "presents", "library", "media library"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#18232]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing words in lokalise

Screen can be found in web version of Home Assistant integration 	Frontier Smart technologies

![1695034072563](https://github.com/home-assistant/frontend/assets/61636045/edc6aee6-40fd-40a8-9fde-94d582e6ba91)

### Describe the behavior you expected

add missing words to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.10.3

### What was the last working version of Home Assistant Core?

not relevant

### In which browser are you experiencing the issue with?

not relevant

**Comment by frenck** [comment]
These are provided by integrations and not the Home Assistant frontend. We cannot translate them here.

../Frenck

**Comment by misa1515** [comment]
@frenck but this integration is part of home assistant, not have own Github...
