### ISSUE TITLE
Missing in lokalise "Confirmable Notification"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#18236]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing in translation

Screen can be found in web version Settings/Automations and Scenes/Scripts/Add script

![1695710078523](https://github.com/home-assistant/frontend/assets/61636045/af415e21-aa2b-4f08-a205-8697b2306910)

### Describe the behavior you expected

Add to translation

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.10.3

### What was the last working version of Home Assistant Core?

not relevant

### In which browser are you experiencing the issue with?

not relevant

**Comment by frenck** [comment]
This is the name of a Blueprint, which is defined by the Blueprint creator and not translateable by Home Assistant
