### ISSUE TITLE
Missing in lokalise "presets"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#18233]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing text in lokalise

Screen can be found in web version of Home Assistant integration 	Frontier Smart technologies

![1695034072570](https://github.com/home-assistant/frontend/assets/61636045/868e390e-c0da-4e37-a06a-ebc16b50f3eb)

### Describe the behavior you expected

Add missing to tr

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.10.3

### What was the last working version of Home Assistant Core?

not relevant

### In which browser are you experiencing the issue with?

not relevant

**Comment by frenck** [comment]
This is provided by an integration and not the Home Assistant frontend. It cannot be translated here.

../Frenck
