### ISSUE TITLE
Missing in lokalise "No runs found"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#18239]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing in lokalise

![1695710078553](https://github.com/home-assistant/frontend/assets/61636045/f693fb10-8921-4bae-9cbb-714fb82119fe)

### Describe the behavior you expected

Add to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.10.3

### What was the last working version of Home Assistant Core?

not relevant

### In which browser are you experiencing the issue with?

not relevant

**Comment by silamon** [comment]
This was fixed through #17843 last week.
