### ISSUE TITLE
Missing in lokalise "balanced", etc.

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#18230]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing translation in lokalise

Screen can be found in web version of Home Assistant integration 	Frontier Smart technologies
![1695034072548](https://github.com/home-assistant/frontend/assets/61636045/17fe2572-4016-4cce-80cf-ef6c9dcd4b22)

### Describe the behavior you expected

Add missing words to translation process

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.10.3

### What was the last working version of Home Assistant Core?

not relevant

### In which browser are you experiencing the issue with?

not relevant

**Comment by frenck** [comment]
This is an translation provided by an integration, and cannot be translated by the Home Assistant frontend.

../Frenck
