### ISSUE TITLE
Missing in lokalise "Electricity maps", etc.

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#18240]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing in lokalise

Screen can be found in web version Settings/Controls Panel/click on text "Energie"/Add integration Electricity maps

![1695710138672](https://github.com/home-assistant/frontend/assets/61636045/47c75a17-0388-42e8-a970-f44c4f701e98)

### Describe the behavior you expected

Add to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.10.3

### What was the last working version of Home Assistant Core?

not relevant

### In which browser are you experiencing the issue with?

not relevant

**Comment by frenck** [comment]
Please note: "Electricity Maps" is a company/product name and should **not** be translated.

(just like we should never translate "Apple" for example).
