### ISSUE TITLE
Very slow interface update after leaving in background 

### ISSUE THREAD

**Issue by majorhector** [home-assistant/frontend#18247]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a wall mounted tablet. When I leave the tablet going standby, after 5 minutes, the interface take a while updating. The interface freezes for 10-15 seconds then update and everything work fine. 

I have opened a previous issue for a similar problem (Issue #17954). After last update the message that pops out from issue #17954 disappear but the problem remain. Before that issue the interface updated immediately.

In log file I don't see any error.

Same problem on smartphone. If I leave the app in background for 5 minutes or more I find the same problem.

I use companion app both on smartphone and tablet

Core 2023.10.3
Supervisor 2023.10.0
Frontend 20231005.0
OS 11.0

### Describe the behavior you expected

Faster interface update like before 2023.9.2 update

### Steps to reproduce the issue

-

### What version of Home Assistant Core has the issue?

2023.10.3

**Comment by karwosts** [comment]
Note beta 2023.12 is out today, and I believe it does fix several memory leaks which may be the cause of slow performance problems. I don't know if it will solve all things for all people, but I'm hopeful it will be a significant improvement.
