### ISSUE TITLE
Automation causes HA to restart

### ISSUE THREAD

**Issue by Max6993109** [home-assistant/frontend#18251]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hello, 

I’ve set up a “good night” automation that turns off all my lights, locks all doors and arms my security system.  Lately, when setting this automation on, it’s causing home assistant to restart.  Not sure what is causing this.  

### Describe the behavior you expected

Expected my automation to work, lock all the doors, turn off all lights.

### Steps to reproduce the issue

1. Tell google home good night
2. Google home will turn on a good night toggle connected to HA
3. Toggle is turned on, starting the good night automation
4. System reboots
...

### What version of Home Assistant Core has the issue?

Core-2023.8.4

### What was the last working version of Home Assistant Core?

Core-2023.8.4

**Comment by karwosts** [comment]
This would be a core issue, not frontend. Suggest reporting in home-assistant/core.
