### ISSUE TITLE
IOS Companion App Fullscreen Notch

### ISSUE THREAD

**Issue by DerRuedi0** [home-assistant/frontend#18277]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hello,

I am using the HomeAssistant Companion IOS app on my iPhone 15 Pro, I would like to use the full screen for my dashboard. Sort of move my dashboard into the notch of the iPhone. I have been trying this all evening without success.

Unfortunately, when I enable full screen mode under the app settings, only my status bar (cellular reception, wifi etc) is hidden.

Attached is a picture where you can see that my dashboard is "cut off" (fullscreen turned off in the settings).

![image](https://github.com/home-assistant/frontend/assets/75574356/261ed053-1f60-41b7-9d07-bac611db3f95)

And now a photo where my dashboard is still "cut off" but with the fullscreen enabled in the settings.

![image](https://github.com/home-assistant/frontend/assets/75574356/2e6bafef-a0d0-4630-8aa5-833ca74ccb75)

I use the dashboard from [Clooos](https://github.com/Clooos/), [Home Assistant - Mobile First Dashboard](https://github.com/Clooos/Home-Assistant-Mobile-First).

### Describe the behavior you expected

I expect my dashboard to start at the top of my display in fullscreen mode.

### Steps to reproduce the issue

Update your Home Assistant IOS to the current version (2023.7), then start it and go to the app settings, under General you will find the full screen mode, activate it. Then switch back to your dashboard and you can see the problem. I have tested everything on the iPhone 15 Pro.

### What version of Home Assistant Core has the issue?

core-2023.10.3

### In which browser are you experiencing the issue with?

Home Assistant IOS App Version 2023.7

### Which operating system are you using to run this browser?

IOS 17.0.3

**Comment by SvenSvensson86** [comment]
I tried hours to get the fullscreen working as you descripe it by setting `app-header-background-color: rgba(0, 0, 0, 0)`. The only effect it has is showing a black header instead.

**Comment by karwosts** [comment]
May want to open an issue for this in home-assistant/iOS. I don't know exactly where the responsibility lies for this, but those devs may have some ideas or input.

**Comment by SvenSvensson86** [comment]
You can set `<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">` in web apps to get exactly the effect we are looking for. But afaik there is no way to apply that to a theme or somewhere else to have an effect on the HA companion iOS app.

**Comment by atbostudio** [comment]
Perhaps the best solution would be to integrate the function into the app and make it controllable via the settings, just like the selection of the full screen?

**Comment by jockebq** [comment]
I have the exact same issue. The dashboard should start at the top without any bars.

**Comment by Nezz** [comment]
> You can set `<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">` in web apps to get exactly the effect we are looking for. But afaik there is no way to apply that to a theme or somewhere else to have an effect on the HA companion iOS app.

I tried this but no luck. In the app it didn't make a difference:
<img src="https://github.com/home-assistant/frontend/assets/431167/38edc38b-9b43-4afc-a9fd-04420021e71a" height="400">
When pinned to the home screen it did work but clearly the UI is not designed to support it:
<img src="https://github.com/home-assistant/frontend/assets/431167/22a0fdd7-e5e6-4aa6-8e24-325fd046ab36" height="400">

**Comment by jockebq** [comment]
> > You can set `<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">` in web apps to get exactly the effect we are looking for. But afaik there is no way to apply that to a theme or somewhere else to have an effect on the HA companion iOS app.
> 
> I tried this but no luck. In the app it didn't make a difference: <img alt="" height="400" src="https://private-user-images.githubusercontent.com/431167/328939250-38edc38b-9b43-4afc-a9fd-04420021e71a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODUzMzksIm5iZiI6MTcxNTY4NTAzOSwicGF0aCI6Ii80MzExNjcvMzI4OTM5MjUwLTM4ZWRjMzhiLTliNDMtNGFmYy1hOWZkLTA0NDIwMDIxZTcxYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxMTEwMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGRiODk1NGU5MDYyYzI1M2FlYzNlMmY1MGJiODQ4NzIxMzkwZTg0ZDY0ZTI4MTE1M2I2MDcyZjcwOTQ5OThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WRtu64T2XSNCsdu8N2jNgdRRlQ8CVzSbFifW758uXHA"> When pinned to the home screen it did work but clearly the UI is not designed to support it: <img alt="" height="400" src="https://private-user-images.githubusercontent.com/431167/328939244-22a0fdd7-e5e6-4aa6-8e24-325fd046ab36.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODUzMzksIm5iZiI6MTcxNTY4NTAzOSwicGF0aCI6Ii80MzExNjcvMzI4OTM5MjQ0LTIyYTBmZGQ3LWU1ZTYtNGFhNi04ZTI0LTMyNWZkMDQ2YWIzNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxMTEwMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODE4MjRmYzJiZTlmMWI5ZGRjMGIyNjI4YjQ5NjBlZmU2YmUwMTdlY2IzMGI1ZjA2ODBlNmYwZDU4ZDM1MjA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rk_28kT3O84OzFA-R-iIJ03TYX6djdJYYSVrapbQ9VI">

But that should work in full-screen? Because full-screen hides the clock and top iOS icons?

**Comment by Nezz** [comment]
See the first screenshot. Clock and iOS icons are hidden, but the app is not expanding into that area of the screen.

**Comment by jockebq** [comment]
Aha, second screenshot is a webapp saved from Safari? How come it is not possible to replicate this but hide clock and iOS icons in the app?
