### ISSUE TITLE
history-graph cards show more data than there is if hours_to_show exceeds avalable data

### ISSUE THREAD

**Issue by nabeelr** [home-assistant/frontend#18295]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If you create a history-graph with data from different sensors or whatnot, and set the hours_to_show to a value that exceeds the history available for any of the data in the list of entities, there is white space in the time before the first plot point of data.

### Describe the behavior you expected

In an older version of HA, the graph would simply zoom-in/scale up to show all the data, with minimal white space before the first available plot point.

e.g. Previously, if I have entities that have 5 hours worth of data, but I set the hours_to_show to 10 hours, the history chart would simply show the 5 hours of data in the past. It would exclude the part of the scale that's >5 (or number of hours of available data) and fill more of the scale as time passes, up to the 10 hours selected.
Whereas now, half the chart for the 5 hours to 10 hours, proceeding the first plot point of data will be blank.

The older way was handy for some charts that are being monitored that may not have the full amount of data at first, but will fill up over time.

However, since early this year, you're either stuck changing the hours_to_show as you go along, or deal with the scaling being not very useful.

Either the old formatting should be restored, or an option should be available to only show up to the maximum amount of data.

### Steps to reproduce the issue

1. Add new entities that are logging data
2. Add those entities into a history-graph
3. Set the hours_to_show to be > the number of hours of data available for the new entities.

### What version of Home Assistant Core has the issue?

2023.10.3

### What was the last working version of Home Assistant Core?

2023.3.4 (I believe)

### In which browser are you experiencing the issue with?

FireFox, Home Assistant app.

### Which operating system are you using to run this browser?

Windows 10/11, Android 12/13

**Comment by ildar170975** [comment]
When hours_to_show is more than an actual period when the entity is recorded - then a “white space” is shown before. 
This behavior is correct.
Otherwise imagine a picture: a user selected 2 or more entities in history-graph card or in History page; some entity (entities) has a smaller “recorded period” - then all graphs are misaligned and have different scale.

**Comment by nabeelr** [comment]
This is not how it used to work, and I built dashboards around this convention that had been established for quite a while before that. If this convention was going to change, users should have been given the option as to not undo their configurations and layouts.

Also, WRT: 

> If some of your entities have only 5 hours recorded - then define hours_to_show to 5 ????

While it may only be 5 hours of data now, in 5 more hours it will be 10. Also, this is completely besides the point because it was an example to illustrate the issue, hence the use of "e.g.".
