### ISSUE TITLE
Dark Mode not working in versions > 20231016.0.dev

### ISSUE THREAD

**Issue by pcartwright81** [home-assistant/frontend#18291]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Dark mode doesn't work even when manually selected.

### Describe the behavior you expected

For dark mode to work.

### Steps to reproduce the issue

1. Update version
2. Look at the dashboard

### What version of Home Assistant Core has the issue?

20231017.0.dev

### What was the last working version of Home Assistant Core?

20231016.0.dev

### In which browser are you experiencing the issue with?

Google Chrome & HA Companion app for Android

### Which operating system are you using to run this browser?

Windows\Android

**Comment by silamon** [comment]
I've seen this too yesterday. It must be a recent regression.  Thanks for making an issue.

**Comment by karwosts** [comment]
Believe this is now resolved.
