### ISSUE TITLE
Energy dashboard cost calculating glitch

### ISSUE THREAD

**Issue by arturschuetz1979** [home-assistant/frontend#18294]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

For unknown reason the cost calculation in the energy dashboard had a glitch by showing up huge numbers. I checked the entities for the correct values in the statistics and even deleted the data for Energy In without having an influence on the cost calculation. Before and after this day the cost calculation work fine. I really can't find the issue.

### Describe the behavior you expected

Correct calculation of the energy dashboard not given. On this day the cost are not related to the entity value. Even deleting the entity value in the statistics show no change.

<img width="539" alt="image" src="https://github.com/home-assistant/frontend/assets/111003002/89c50993-ce08-49a5-b555-cf6c8b04de36">

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.10.3

### What was the last working version of Home Assistant Core?

2023.10.1

### In which browser are you experiencing the issue with?

Google Chrome 102.0.5005.63 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Win11

**Comment by arturschuetz1979** [comment]
<img width="662" alt="image" src="https://github.com/home-assistant/frontend/assets/111003002/1828e3c4-4e12-4d90-ab83-d6d5e8b14480">
Energy out compensation is not seen any issues in the statistics, but shown wrong in energy dashboard (cost)

**Comment by karwosts** [comment]
Suggest make a `statistics-graph-card`, and plot your cost statistic over that time window, and I bet you'll see a big change in the data at this period. Maybe it got reset incorrectly. It can be fixed using the adjust-statistic dialog in developer-tools. 

What you're showing in your screenshot is the history graph, which doesn't capture what is going on in the statistics table, which is what energy dashboard uses.

**Comment by arturschuetz1979** [comment]
solved, thanks
