### ISSUE TITLE
Scene not saved correct states

### ISSUE THREAD

**Issue by Paddy3911** [home-assistant/frontend#18293]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Scenes do not work correctly. Whenever I create a scene, add a device, adjust the color and brightness, and then save the scene, the status is not established correctly. The light is always turned off.

### Describe the behavior you expected

The state (On/Off) as well as color and brightness should be saved correctly. It doesn't work correctly in either scenes or automations.

### Steps to reproduce the issue

1. Create new scene
2. Add Device (Light - Tuya GU10)
3. Set light color
4. Save scene
5. Turn off the light 
6. Activate the scene
7. The light remains off, even though you've previously set the colors. If you then turn the light back on via the app, it goes off again instead of switching to the correct color.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.10.3 Supervisor 2023.10.0 Operating System 11.0 Frontend 20231005.0 - latest

### What was the last working version of Home Assistant Core?

Home Assistant 2023.10.3 Supervisor 2023.10.0 Operating System 11.0 Frontend 20231005.0 - latest

### In which browser are you experiencing the issue with?

Google Chrome 118.0.5993.71

**Comment by karwosts** [comment]
I think this is probably not a frontend issue, which doesn't really handle any of the logic of running scenes. That's all handled in home-assistant/core.
