### ISSUE TITLE
Issues not fixed when clicked first time (Developer tools)

### ISSUE THREAD

**Issue by cris1** [home-assistant/frontend#18314]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When going to the /developer-tools/statistics I see several "FIX ISSUE" notifications , i.e.

Entity has no state
This entity has no state at the moment, if this is an orphaned entity, you may want to remove the long term statistics of it from your database.

Do you want to permanently remove the long term statistics of sensor.mikrotik_ha_ether6_tx_total from your database

https://github.com/home-assistant/frontend/assets/666701/e4275673-b9d5-4394-b0dc-71e33b060aba

When clicking "Remove" nothing happends. The "popup dissapears , but the issue is not removed. Clicking it again removes the issue. 

Since I have a LOT of issues to fix, i have to click all of them twice.

### Describe the behavior you expected

I expect the issue to be removed after first time clicking on remove.

### Steps to reproduce the issue

1. Go to your home asisstant URL --> developper Tools --> Statistics (/developer-tools/statistics)
2.  Click FIX ISSUE on the right
3. Click Remove

Now repeat step 2 and 3 to actually remove it.
...

### What version of Home Assistant Core has the issue?

2023.10.3

### In which browser are you experiencing the issue with?

Brave Browser v1.59.122 (Oct 20, 2023)

### Which operating system are you using to run this browser?

Linux Mint 21.2 Victoria

### Javascript errors shown in your browser console/inspector

```txt
No Errors in Console
```

### Additional information

I have tried with Chrome Browser too, but same result.

**Comment by karwosts** [comment]
I observed this myself, what is happening here is that the `clear_statistics` command to the backend just posts the delete request and then returns, it doesn't wait for the actual clear to finish. 

So the frontend is refreshing too soon, and it doesn't observe that the statistic got deleted. 

So if you just refreshed the page after the first fix, you would find the statistic now gone.
