### ISSUE TITLE
Download and delete backup are too hidden

### ISSUE THREAD

**Issue by matthiasdebaat** [home-assistant/frontend#18342]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When clicking on a backup, you are presented with a restore dialog. In this dialog, there is also an overflow menu with a download a delete backup option. These are very useful an to hidden now, in a dialog that does something else.

![CleanShot 2023-10-23 at 11 44 50@2x](https://github.com/home-assistant/frontend/assets/20203284/3475f92c-86bb-4101-8bdc-ff9c9590b93c)

### Describe the behavior you expected

We should move these functions to the table itself. For example, at the end of the row with a button `Download` and icon button `mdi:delete`.

### Steps to reproduce the issue

1. Stettings
2. System
3. Backups

### What version of Home Assistant Core has the issue?

core-2023.10.5

**Comment by wittelw** [comment]
Thanks for opening this, and I agree moving them to the table would be a huge improvement.

I had looked at the three dot menu on the main Backups page once I had selected a backup (but even that is obscure), but that or additional Blue buttons (is that allowed in the style guidelines?) that light up on selections would be better than now.

**Comment by tringenbach** [comment]
The Download button is still really hard to find.

It's only in the "..." menu after bring up a backup. It's much easier to find the Delete, and slightly easier to find Restore.

I always download my backups. What if something happens to my Pi? I had been assuming that downloading them is discouraged, though I have no idea why, because the option is so buried.
