### ISSUE TITLE
Missing in lokalise existing automation - "Topic"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#18355]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing in lokalise

Screen can be found in web version Settings/Automations and Scenes/ in existing automatisation

![Snag_Topic](https://github.com/home-assistant/frontend/assets/61636045/db32dbba-9545-4c76-960e-5b664e0278fe)

### Describe the behavior you expected

Add to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.10.5

### What was the last working version of Home Assistant Core?

not relevant

**Comment by silamon** [comment]
Key is already in localize as `ui::panel::config::automation::editor::triggers::type::mqtt::topic`. Feel free to improve the translation if you think that it's incorrectly translated. Here's the [documentation](https://developers.home-assistant.io/docs/translations/) to get started.

**Comment by misa1515** [comment]
Thank you.
