### ISSUE TITLE
Thermostat - current UI has no provision for EMheat mode or Aux control.

### ISSUE THREAD

**Issue by BenchmarkCreative** [home-assistant/frontend#18367]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Older thermostat UI block had an option to switch the Heat modes that seems to be missing from the current UI.  It can still be controlled from the developer console by issuing the correct calls.

### Describe the behavior you expected

Used to have a EMheat (AUX) mode toggle.  This is useful to control fuel source for the heating system dynamically based on outside temp or costs of electricity vs. natural gas.

### Steps to reproduce the issue

1.open thermostat - its not there??
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.10.5

### What was the last working version of Home Assistant Core?

?

### In which browser are you experiencing the issue with?

chrome

### Which operating system are you using to run this browser?

win 11

### State of relevant entities

```txt
hvac_modes: off, heat_cool, cool, heat
min_temp: 59
max_temp: 81
fan_modes: on, auto, diffuse
preset_modes: none, away, Hold
current_temperature: 69
temperature: 69
target_temp_high: null
target_temp_low: null
current_humidity: 56
fan_mode: auto
hvac_action: fan
preset_mode: null
aux_heat: on
fan_action: running
permanent_hold: false
dr_phase: -1
friendly_name: THERMOSTAT
supported_features: 91
```

### Problem-relevant frontend configuration

```yaml
- type: thermostat
    entity: climate.thermostat
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

I think this was simply removed

**Comment by matthiasdebaat** [comment]
It's indeed removed from the UI. In this approved [architecture discussion](https://github.com/home-assistant/architecture/discussions/932), you can find why it was removed and its proposal. 

> Instead, integrations that use it can use a switching entity and add it to the device, or, in case it is a read-only property, be exposed as a binary sensor.

**Comment by BenchmarkCreative** [comment]
Any change you can point me to a tutorial on setting up a switching entity for this purpose?  I am struggling to find direction on how to implement this.
