### ISSUE TITLE
Missing translation "Search", "Official add-ons"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#18366]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Please add missing text "Search", "Official add-ons" to lokalise

you can find it in Settings/Addons/Shop with addons/

![Snag_SearchOfficialAddons](https://github.com/home-assistant/frontend/assets/61636045/ae9e783c-581d-4aae-9d89-62939d0ea7c5)

### Describe the behavior you expected

Add to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.10.5

### What was the last working version of Home Assistant Core?

not relevant

**Comment by frenck** [comment]
Search you've already reported before, "Official add-ons" is not translateable.

Closing this issue for that reason.

../Frenck
