### ISSUE TITLE
Energy dasboard is not displaying consumed solar if battery was charged from grid.

### ISSUE THREAD

**Issue by Ben00793** [home-assistant/frontend#18400]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Energy dasboard is not displaying consumed solar if battery was charged from grid.

### Describe the behavior you expected

Display the solar consumption properly.

### Steps to reproduce the issue

1. Charege the solar batteries from grid over night on the cheap tariff.
2. Next day the solar consumpsion will not display properly in the energy dasboard.
3.
4.
...
![Capture3](https://github.com/home-assistant/frontend/assets/132856308/18b7bfda-8d22-4167-bfce-4ab9b563b692)
![Capture2](https://github.com/home-assistant/frontend/assets/132856308/d2a7b946-7b96-488b-86eb-54a1f7c3b900)
![Capture](https://github.com/home-assistant/frontend/assets/132856308/26285eac-18b5-46f1-b70f-fcc9a858f1bf)

### What version of Home Assistant Core has the issue?

all

### What was the last working version of Home Assistant Core?

none

### In which browser are you experiencing the issue with?

Chrome, opera

### Which operating system are you using to run this browser?

windows android

**Comment by Ben00793** [comment]
So this is a known problem since September last year and it's still not fixed?
Unbelievable!

**Comment by karwosts** [comment]
Yes it is unfortunate. You may track progress in the linked duplicate.
