### ISSUE TITLE
Dot Slider

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#18417]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Bigger Dot on Slider and Slider
![image](https://github.com/home-assistant/frontend/assets/42905545/96c97fec-b873-456f-ac0b-f346ebec9855)

### Describe the behavior you expected

*

### Steps to reproduce the issue

*

### What version of Home Assistant Core has the issue?

2023.11.0b0

**Comment by silamon** [comment]
The slider changed this release and matches more the guidelines of material design. It's not very clear in your description if there is an issue with it or are you just referring to the size of the dot?

**Comment by piitaya** [comment]
The previous dot size was `12px` and now it's `20px`.
IMO, it UI looks too cluttered with bigger size. 

![CleanShot 2023-10-26 at 12 02 43](https://github.com/home-assistant/frontend/assets/5878303/6bfe79a9-745e-46a7-8b4d-b807e33b4d1c)

I made a PR to reduce the size : https://github.com/home-assistant/frontend/pull/18427
What do you think @silamon?

**Comment by silamon** [comment]
Yeah, I agree and approved the PR. During testing I didn't had multiple sliders under eachother.

**Comment by piitaya** [comment]
@milandzuris Everybody agree that it does not look nice... It was never plan to keep the 20px size.
If you look at the thread, a PR is already created and approved with the fix. 
The sizes was changed because the slider was updated because the old one was deprecated and unmaintained. It was not done on purpose.

**Comment by milandzuris** [comment]
> @milandzuris Everybody agree that it does not look nice... It was never plan to keep the 20px size. If you look at the thread, a PR is already created and approved with the fix. The sizes was changed because the slider was updated because the old one was deprecated and unmaintained. It was not done on purpose.

ok thx
