### ISSUE TITLE
Energy Panel

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#18416]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Energy Panel on Left side
![image](https://github.com/home-assistant/frontend/assets/42905545/647873cd-22e9-4cd4-84d1-167f69055e56)

### Describe the behavior you expected

*

### Steps to reproduce the issue

*

### What version of Home Assistant Core has the issue?

2023.11.0b0

**Comment by ludeeus** [comment]
Already reported here https://github.com/thomasloven/lovelace-card-mod/issues/304
