### ISSUE TITLE
Custom cards doesn't load on 2023.11.0b0

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#18418]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Dashboard not work on Android but from browser no problem same on pc without problems
![image](https://github.com/home-assistant/frontend/assets/42905545/cd9529e2-68f7-4456-ac84-7b1c7c0b85c2)

### Describe the behavior you expected

*

### Steps to reproduce the issue

*

### What version of Home Assistant Core has the issue?

2023.11.0b0

**Comment by bschatzow** [comment]
Same issue with both of my Android devices.  No issue with Chrome on any device.

**Comment by SmarterHomeLife** [comment]
I'm having the same issue in Chrom on Android but only when accessing over https using Nginx proxy, dashboard loads fine when accessing over local network.

**Comment by bschatzow** [comment]
Still broke in B1.

**Comment by piitaya** [comment]
Can you reopen another issue with your logs? It should be another problem.

**Comment by silamon** [comment]
> Can you reopen another issue with your logs? It should be another problem. 

The fix simply didn't make it into b1. It should be fixed on next beta.

**Comment by bschatzow** [comment]
Very strange, it is now working correctly.  Several hours after the update.  I never had a HA log error.  Maybe in the android app logs, but I did not check there.
