### ISSUE TITLE
Multi-item history graph style 'bar' has values cut off

### ISSUE THREAD

**Issue by morgantic** [home-assistant/frontend#18415]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The rightmost, and maybe also leftmost set of item gets cut off roughly in the middle:

<img width="1149" alt="image" src="https://github.com/home-assistant/frontend/assets/126607370/486ef700-beab-4a07-8d25-d09b678b2e44">

For reference, here's the preview in the configuration GUI, how it should look:

![image](https://github.com/home-assistant/frontend/assets/126607370/71361b4e-fd19-47e4-a1cb-58faa1ee29a7)

v 2023.10.3

### Describe the behavior you expected

I expected to be able to see all values

### Steps to reproduce the issue

Set up a multi item history graph bar style.

### What version of Home Assistant Core has the issue?

2023.10.3

### In which browser are you experiencing the issue with?

Chrome Version 118.0.5993.89

**Comment by karwosts** [comment]
Duplicate #18415
