### ISSUE TITLE
Predefined time periods not displayed in History date picker

### ISSUE THREAD

**Issue by michalwoz** [home-assistant/frontend#18435]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Randomly predefined time periods are not displayed in History date picker. Sometimes I have to refresh browser 5-10 times before they appear. Sometimes they are displayed at the first try. I have 2 browser cards one with 13 entities and ome with 25 entities. It looks like some time-rece condition. Refreshing with or without cache clear doesn't seem to have impact.

![image](https://github.com/home-assistant/frontend/assets/31922455/eef03c18-71e2-4b6d-b643-270541966c43)
![image](https://github.com/home-assistant/frontend/assets/31922455/52425724-a120-4675-a933-123f3f1284c6)

### Describe the behavior you expected

![image](https://github.com/home-assistant/frontend/assets/31922455/09b2eddb-03a6-41f0-b241-a80cde778498)
![image](https://github.com/home-assistant/frontend/assets/31922455/c3522d4a-2cd4-4af2-88f3-5f3c6dad0ca3)

### Steps to reproduce the issue

1. Add 20 entities to you History card
2. Refresh page
3. Click calendar icon to check date picker.
4. Repeat steps 2 and 3 until you see datepicker without predefined timerange

### What version of Home Assistant Core has the issue?

2023.10.5

### In which browser are you experiencing the issue with?

Google Chrome 118.0.5993.89, Edge 118.0.2088.69

### Which operating system are you using to run this browser?

Windows 11

### Javascript errors shown in your browser console/inspector

```txt
No errors
```

**Comment by karwosts** [comment]
Fixed this last week 😁 (#18274)

Will be fixed in 2023.11.

**Comment by michalwoz** [comment]
@karwosts Thank you very much 😃 I've waited 6 months and did ~15 HA updates until I opened this issue... Perfect timing.
