### ISSUE TITLE
Top menu edit bar and developer bar not showing

### ISSUE THREAD

**Issue by cherryocola** [home-assistant/frontend#18449]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Top menu edit bar and developer bar not showing

### Describe the behavior you expected

Normal menu bars

### Steps to reproduce the issue

![2023-10-27 224411](https://github.com/home-assistant/frontend/assets/36471982/f07bd52d-4ab6-476d-bf3d-9a9d7de5ded7)
![2023-10-27 224609](https://github.com/home-assistant/frontend/assets/36471982/9b1f2e22-9249-4c00-a15c-f081bed75b83)

Home Assistant 2023.10.5
Supervisor 2023.10.1
Operating System 11.1
Frontend 20231005.0 - latest

### What version of Home Assistant Core has the issue?

2023.10.5

### What was the last working version of Home Assistant Core?

unknown

### Which operating system are you using to run this browser?

Windows Chrome

**Comment by brebtatv** [comment]
I confirm, it's happening to me too, all up to date. It does this a few versions back as well. Most often in the Android application.

**Comment by karwosts** [comment]
Ever tried [safe_mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) ?

I've never seen this. Does it always happen, or just occasionally?

**Comment by brebtatv** [comment]
It seems that in SAFE MODE the error does not appear.

**Comment by brebtatv** [comment]
It is interesting that the problem does not appear in Android via the Chrome browser, almost always in the application.  Clearing the cache won't help either.

**Comment by brebtatv** [comment]
![Screenshot_20240115_091213_Home Assistant](https://github.com/home-assistant/frontend/assets/10747062/76bd9370-8463-4638-8702-e6b0ac70a4ce)

It also occurs when trying to edit the Dashboard.

**Comment by karwosts** [comment]
If it's not a problem in safe mode, that's a likely signal that it's just some custom resource you are installing that is breaking it. 

You can try removing one at a time to see if you can isolate which one is the problem, but otherwise we don't support those types of issues here.

**Comment by brebtatv** [comment]
Thank you for your reply, I probably had a problem with the Lovelance Xiaomi Air Filter Card.  So problem solved for me.
![Screenshot_20240123_084747_Home Assistant](https://github.com/home-assistant/frontend/assets/10747062/156d0396-3293-4c3b-8057-e214a6ce91e8)

**Comment by brebtatv** [comment]
![Screenshot_20240123_085354_Home Assistant](https://github.com/home-assistant/frontend/assets/10747062/647dea3b-54c0-4c78-9c5c-5e8b734f38e0)

**Comment by brebtatv** [comment]
![Screenshot_20240123_085354_Home Assistant](https://github.com/home-assistant/frontend/assets/10747062/5c0ef493-b322-4e3b-9fa9-1f172f8a76d7)
