### ISSUE TITLE
Je n'est plus le tableau de bord sur HA? Quelqu'un peu il m'aidé. Merci

### ISSUE THREAD

**Issue by Foucher49740** [home-assistant/frontend#18467]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

J'ai installé intérgartion de atome direcy energie. Et quand j'ai voulu parametre mon tableau de bord energy. Je me suis aperçu qu'il ne faisait plus partie de mes tableau de bord. Comment le faire revenir.

Merci de votre aide

### Describe the behavior you expected

impossible de le réintegré

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.9.1

### What was the last working version of Home Assistant Core?

Home Assistant 2023.9.1

**Comment by frenck** [comment]
Hi there @Foucher49740 👋 

Unfortunately, we don't understand the language you've been using the report an issue. Please note, that Home Assistant is an English-only community. Please open up a new issue using the English language.

Thanks 👍 

../Frenck

**Comment by Foucher49740** [comment]
I installed the atom insertion directly into energy. And when I wanted to configure my energy dashboard. I noticed that it was no longer part of my dashboard. How to bring him back.

Thank you for your help

**Comment by Foucher49740** [comment]
I installed the atom insertion directly into energy. And when I wanted to configure my energy dashboard. I noticed that it was no longer part of my dashboard. How to bring him back.

Thank you for your help
