### ISSUE TITLE
Incorrect Sensor type showing for Binary sensor - Door and Window Contact Sensor

### ISSUE THREAD

**Issue by Scoff123** [home-assistant/frontend#18476]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After adding a new Aqara Door and Window Contact Sensor to HA, via Zigbee2MQTT, the device shows up in HA under the MQTT Integration list of devices, but the sensor shows as 'Door' instead of 'Window'.

### Describe the behavior you expected

I believe the device info page in HA should be showing 'Window' instead of 'Door' after either of the above two steps have been carried out. 

### Steps to reproduce the issue

1) Add new Contact sensor to Z2M.

2) IN HA, click on the new device in the list of MQTT devices, and it shows a list of 2 sensors for the device. 'Door' and 'Power outage count'. 

3) As I am using this particular sensor on a window, I click on the 'Door' sensor, then click the settings icon, and change the option for 'Show as' from 'Door' to 'Window'. The icon changes to that of a window, and I click 'Update'. 

4) The device info page in HA still shows the sensor as 'Door', even after a restart of Z2M, Mosquitto, and HA itself. 

I have also tried setting the device class manually via the customize.yaml file, and I can see that the device class is indeed correct, when using Developer tools to view the state of the sensor.  

<img width="404" alt="image" src="https://github.com/home-assistant/frontend/assets/96984460/96785b3d-3361-43a5-a652-eafb816ea15e">
<img width="224" alt="image" src="https://github.com/home-assistant/frontend/assets/96984460/75e756c1-5fbc-4fa6-92e4-c60caeb0dfdd">
<img width="219" alt="image" src="https://github.com/home-assistant/frontend/assets/96984460/78b02f03-c52b-498e-94af-6e87cb79a218">

### What version of Home Assistant Core has the issue?

2023.10.5

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Google Chrome 118.0.5993.118 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11 Pro

### State of relevant entities

```txt
state: off
device_class: window
icon: mdi:window-closed-variant
friendly_name: Spare Bedroom Window
```

### Additional information

```
{
          "device_class": "window",
          "disabled_by": null,
          "disabled": false,
          "entity_category": null,
          "entity_id": "binary_sensor.spare_bedroom_window_sensor_contact",
          "icon": "mdi:window-closed-variant",
          "original_device_class": "door",
          "original_icon": null,
          "state": {
            "entity_id": "binary_sensor.spare_bedroom_window_sensor_contact",
            "state": "off",
            "attributes": {
              "device_class": "window",
              "icon": "mdi:window-closed-variant",
              "friendly_name": "Spare Bedroom Window"
            },
            "last_changed": "2023-10-30T17:43:38.307537+00:00",
            "last_updated": "2023-10-30T17:43:38.307537+00:00"
          },
          "unit_of_measurement": null
        },
```

**Comment by karwosts** [comment]
Have you tried adding something to the `Name` field after clicking on the gear?

**Comment by Scoff123** [comment]
I hadn't, as I had already set the friendly name in customize.yaml. If i set the name as 'Window' in that field, 

<img width="226" alt="image" src="https://github.com/home-assistant/frontend/assets/96984460/8172d760-043d-43db-82e8-7869dea676f1">

It does then change from Door, on the device info page, and must then be getting the friendly name, as it appears as 'Spare Bedroom Window'

<img width="152" alt="image" src="https://github.com/home-assistant/frontend/assets/96984460/52ced515-f1e3-4783-aded-1744ae6eeab8">

Is this the expected behaviour/ It needs a name entered in that field, in order to be able to then use the friendly name set it customize.yaml?

**Comment by karwosts** [comment]
Changing device class doesn't change the entity name. If the integration initially provided it with the name "Door", then you need to name it something else instead to override that.

**Comment by claudiucismaru** [comment]
@karwosts , gotcha. Actually, when I renamed them, from the zigbee IDs to a name, I checked for the entity to be renamed in HA. The entity id doesn't contain any "door" in it. And I didn't provide it in the rename popup. So, I assumed it is automatically added at display time. It seems Z2M adds it automatically?

**Comment by karwosts** [comment]
I am not as knowledgeable about how the default entity name is picked by the backend.

**Comment by claudiucismaru** [comment]
I have renamed the entities, However, in the cards is still showing it as "Door". So, it's not only the naming. At least, we should have the option to choose where is that sensor placed, whether is a door or window one.

**Comment by brebtatv** [comment]
Interestingly, sometime earlier in the past the entities displayed correctly. It was changed by some change and it is still unresolved.
Changing the name doesn't solve it.
