### ISSUE TITLE
Dashboard code editor is too narrow, truncating code

### ISSUE THREAD

**Issue by askpatrickw** [home-assistant/frontend#18482]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The code editor is needlessly narrow and truncates the code making editing more difficult.

### Describe the behavior you expected

The code editor should be responsive and the width should expand in relation to the window width.

### Steps to reproduce the issue

1. Look at the code editor (see pic)

### What version of Home Assistant Core has the issue?

2023.10.5

### In which browser are you experiencing the issue with?

Edge Version 118.0.2088.76 (Official build) (arm64) (and Firefox)

### Which operating system are you using to run this browser?

MacOs Sonoma

### Additional information

![image](https://github.com/home-assistant/frontend/assets/4002194/43f6b912-069e-422c-9681-4e70d1781bd3)

**Comment by karwosts** [comment]
There's a bit of an easter egg implemented where if you click on the title of the card (`Vertical stack Card configuration`), it will expand wider. 

Not suggesting that this is the solution to this issue, but it's something you can use in the meantime if you need to.

**Comment by askpatrickw** [comment]
@karwosts, thank you for that!! 🤯 🙏

Suggestion: If you added an SVG expand icon somewhere in there (after the title, next to the "?", etc.) I'd call that a fix.

**Comment by karwosts** [comment]
I actually had a PR once to do just that, but designers didn't like the UI. 🤷‍♂️
