### ISSUE TITLE
can't add user 

### ISSUE THREAD

**Issue by rexyboi32** [home-assistant/frontend#18495]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

can locate anywhere to add user for Mosquitto broker on home assistant green as the option can not be found 

### Describe the behavior you expected

can locate anywhere to add user for Mosquitto broker on home assistant green as the option can not be found 

### Steps to reproduce the issue

1.try to add user
2. no location for option found
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.10.5 Supervisor 2023.10.1 Operating System 11.1 Frontend 20231005.0 - latest

**Comment by karwosts** [comment]
You might need to enable `Advanced Mode`, otherwise the users tab (next to people in settings) is hidden.
