### ISSUE TITLE
Automation Choose Not Allowing Adding Options

### ISSUE THREAD

**Issue by zpriddy** [home-assistant/frontend#18492]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When editing automation in the UI and adding an action of type choose.. It will only allow me to add 1 choose condition.. When adding a second option it will not allow me to add any conditions. 

![Screenshot 2023-10-31 at 10 46 59 AM](https://github.com/home-assistant/frontend/assets/1858679/461ac2c1-ffa9-4e22-b209-000825754ea1)

It does work if I edit it in YAML format

### Describe the behavior you expected

To be able to Conditions for any choose options

### Steps to reproduce the issue

1. Use frontend  20231030.0 
2. Use backend 2023.11.0b4
3. try to create automation in the UI
...

### What version of Home Assistant Core has the issue?

2023.11.0b4

### In which browser are you experiencing the issue with?

Firefox, Chrome, Safari

### Which operating system are you using to run this browser?

MacOS 14.0, IOS17

**Comment by karwosts** [comment]
Thanks for reporting! Fixed by #18493

**Comment by zpriddy** [comment]
I can confirm its fixed! Thank you!
