### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#18503]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Please someone fix this Choose Menu in Logs, same on Phone
![image](https://github.com/home-assistant/frontend/assets/42905545/73134a24-4d76-4875-9a39-87c743141383)

### Describe the behavior you expected

*

### Steps to reproduce the issue

*

### What version of Home Assistant Core has the issue?

*

**Comment by silamon** [comment]
It may be the same problem as can be seen in the automation editor: 
![image](https://github.com/home-assistant/frontend/assets/32477463/73450841-e8f1-4f12-a25f-fc055b517a5a)

**Comment by piitaya** [comment]
It's fixed with the 2023.11 release. Can you confirm this?
