### ISSUE TITLE
Few small issues with energy-date-selection in Safari after upgrade to 2023.11

### ISSUE THREAD

**Issue by mirekmal** [home-assistant/frontend#18526]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Energy date selector card does not diplay properly after update to 2023.11 in Safari. As far as I tested it is related to Mac OS, iOS 17 and includes companion App on iPhone (as it uses same web engine).
Issues observed:
- No TODAY button displayed in Safari
- Date format is different than configured
- Date alignment is different than it was (aligned left most of card instead of on the left, next to date selectors)
Following screenshots show differences.
Deafault Energy dashboard - everything as expected, even in Safari:
![Screenshot 2023-11-03 at 09 35 40](https://github.com/home-assistant/frontend/assets/6892816/fd7b131b-0bae-45d5-8759-157434c402b0)

Safari displaying Energy Date Selection card in custom dashboard (different alignment and formatting of date, lack of TODAY button):
![Screenshot 2023-11-03 at 09 36 07](https://github.com/home-assistant/frontend/assets/6892816/bba9399a-b0b1-499c-a878-b7158686ff8d)

Same card, same dashboard, but this time in Chrome, except of card title not being displayed expected display:
![Screenshot 2023-11-03 at 10 07 01](https://github.com/home-assistant/frontend/assets/6892816/2c0892d1-ab93-4635-9273-b810cb76d1f3)

### Describe the behavior you expected

Card being displayed consistently across browsers.

### Steps to reproduce the issue

Create dashboard with energy-date-selection card and display it in Safari on iOS or Mac OS.

### What version of Home Assistant Core has the issue?

2023.11

### What was the last working version of Home Assistant Core?

2023.10.5

### In which browser are you experiencing the issue with?

Safari

### Which operating system are you using to run this browser?

Mac OS Monterey, iOS 17

### Problem-relevant frontend configuration

```yaml
type: energy-date-selection
```
```


### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

**Comment by casperghst42** [comment]
I am seeing the same problem, though date is show as configured:
- firefox (macos) 
- safari (macos)
- chrome (macos)
- MacOS app
- IOS app
- iPad app
