### ISSUE TITLE
Wrong screen fit in HomeAssistant/Energy (to right side)

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#18527]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Wrong fit in HomeAssistant/Energy (marked by red in pictures)
tested on (issue in both cases)
- pc edge browser
- android web browser

![1699038258514](https://github.com/home-assistant/frontend/assets/61636045/6140bc02-f184-4db1-910f-d45acf4b4417)
![1699038258530](https://github.com/home-assistant/frontend/assets/61636045/7cec82b3-4db7-4c91-81e6-6b4250d3e580)

### Describe the behavior you expected

Energy screen on full screen (not cut from right side - "visible too big blank area")

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.11.0

### What was the last working version of Home Assistant Core?

previous versions

### In which browser are you experiencing the issue with?

Edge 120.0.2172.1

### Which operating system are you using to run this browser?

Win10 x64 22H2

**Comment by sebcaps** [comment]
In my case CTRL+F5 display is OK, but moving to another dashboard and moving back to energy still KO.
KO chrome as well

**Comment by silamon** [comment]
See #18514 for more information.

**Comment by misa1515** [comment]
Hello @karwosts, please look on one other found info regarding this issue, maybe will be helpful.

![6BD6095E-9C5D-45B8-AC3A-E87276D9210B](https://github.com/home-assistant/frontend/assets/61636045/67d2ebbe-a457-4528-ac8a-2eca51080bf8)

Thank you.
