### ISSUE TITLE
Energy dashboard is misaligned when custom date is selected and compare is selected

### ISSUE THREAD

**Issue by sbeukers** [home-assistant/frontend#18525]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Energy dashboard is misaligned when custom date is selected and compare is selected.
On all bar graphs the same behavior.

![image](https://github.com/home-assistant/frontend/assets/65311410/ef02dacf-cca7-45fe-a090-d6640bbaabb2)

### Describe the behavior you expected

Bar graphs of current and compared should be next to each other.

### Steps to reproduce the issue

1. go to energy dashboard
2. select random dates f.e. aug 11 2022 - aug 30 2023
3. select compare
4. this results in overlapping bar graphs
...

### What version of Home Assistant Core has the issue?

2023.11.0

### What was the last working version of Home Assistant Core?

2023.10.last

### In which browser are you experiencing the issue with?

Chrome 118.0.5993.118 (Official Build) (64-bit) - Edge Version 118.0.2088.76 (Official build) (64-bit)
Same result in the Android App

### Which operating system are you using to run this browser?

Windows 10 Version 10.0.19045.3570

### State of relevant entities

```txt
Frontend
20231030.1
```

### Javascript errors shown in your browser console/inspector

```txt
only some plotly-graph-card.js error unrelated
```

**Comment by sbeukers** [comment]
I also noticed this. The dates are not the same length.
![image](https://github.com/home-assistant/frontend/assets/65311410/eb953202-f664-4d6c-9d65-bc80b2fbc326)

**Comment by elax46** [comment]
I would like to point out that the cards also tend to align on the left and not occupy the entire window
![Screenshot 2023-11-03 155018](https://github.com/home-assistant/frontend/assets/55278049/21b2044e-7203-4801-bcfa-746eb36e4045)

**Comment by sebcaps** [comment]
@elax46 , you're rigth, reported in #18527 . This prb sound different and related to the graph itself.

**Comment by sbeukers** [comment]
> There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates. Please make sure to update to the latest Home Assistant version and check if that solves the issue. Let us know if that works for you by adding a comment 👍 This issue has now been marked as stale and will be closed if no further activity occurs. Thank you for your contributions.

Problem still exists. even in the demo
https://demo.home-assistant.io/#/energy
