### ISSUE TITLE
myQ API error: myQ API login anomaly detected

### ISSUE THREAD

**Issue by minidisco** [home-assistant/frontend#18531]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

myQ still doesn't allow login

### Describe the behavior you expected

cannot access myQ

### Steps to reproduce the issue

1. updated to Homebridge 4.51.2 this morning
2. restarted, then deleted myQ and reinstalled fresh myQ 3.4.3
3. restarted Homebridge again
4. tried logging into myQ again
5. got error "myQ API error: myQ API login anomaly detected" again
...

### What version of Home Assistant Core has the issue?

homebridge-config-ui-x v4.51.2

### In which browser are you experiencing the issue with?

Safari Version 17.1 (17616.2.9.11.9, 17616) as well as Chrome Version 111.0.5563.110 (Official Build) (x86_64)

### Which operating system are you using to run this browser?

MacOS Monterey 12.7.1 (21G920)

**Comment by karwosts** [comment]
Frontend doesn't have anything to do with integration logins.

Normally I would suggest to file this in core repo instead, but myQ seems to be permanently defunct now, so I'm not sure there's any point in doing so (myQ has cut off unauthorized third party API access).
