### ISSUE TITLE
Popup window to small, entries not readable

### ISSUE THREAD

**Issue by xstable** [home-assistant/frontend#18536]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![image](https://github.com/home-assistant/frontend/assets/1778068/1c74aba4-e18d-416f-a8b2-b7f7cb8c2b2c)

### Describe the behavior you expected

Double width of the popup window AND make it resizable if user need to adjust it

### Steps to reproduce the issue

1. open section Settings > devices > helper
2. add a new helper
...

### What version of Home Assistant Core has the issue?

2023.11.0

### What was the last working version of Home Assistant Core?

none

### In which browser are you experiencing the issue with?

Version 1.60.110 Chromium: 119.0.6045.105 (brave)

### Which operating system are you using to run this browser?

Linux

**Comment by KTibow** [comment]
There's an "easter egg" that if you click the title of the dialog, it gets bigger.
