### ISSUE TITLE
Energy dashboard does not fill the entire page

### ISSUE THREAD

**Issue by Symon84** [home-assistant/frontend#18545]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After 2023.11.0 update (but also after 2023.11.1 update), the energy dashboard does not fill the entire page (browser and iOS app).
![Schermata 2023-11-05 alle 17 16 46](https://github.com/home-assistant/frontend/assets/97830313/5b6e9b65-17c9-490c-8a71-5d9d627bffb7)

### Describe the behavior you expected

in previous versions the graph and information completely filled the width of the page making the data more readable

### Steps to reproduce the issue

1. Click on energy dashboard button

### What version of Home Assistant Core has the issue?

2023.11.1

### What was the last working version of Home Assistant Core?

2023.11.1

### Which operating system are you using to run this browser?

Firefox 119.0 (64 bit)

**Comment by karwosts** [comment]
This is caused by card mod, check it for an update.

**Comment by Symon84** [comment]
Problem solved!
Thank you!!!

![Screenshot 2023-11-06 082932](https://github.com/home-assistant/frontend/assets/97830313/a1c77fdf-f4ff-4600-a20f-f4191092f9be)
