### ISSUE TITLE
Warmtelink/DSMR: Incorrect energy classification for city heating

### ISSUE THREAD

**Issue by Ceaus** [home-assistant/frontend#18544]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I'm getting city heating as a utility. The measurements are reported by a Warmtelink module in DSMR format. An example of a Warmtelink telegram is:
```
/NWA-WARMTELINK
1-3:0.2.8(50)
0-0:1.0.0(231007104143W)
0-0:96.1.1(ADD3100000197602)
0-0:96.13.1()
0-0:96.13.0()
0-1:24.1.0(004)
0-1:96.1.0(724251192D2C340C)
0-1:24.2.1(231007104143W)(18.365*GJ)
!9456
```
As you can see the unit of measerement is GJ.

The DSMR integration correctly sets the unit of measurement to GJ.

The following issues are observed:

1. The sensor is named `sensor.gas_meter_gas_consumption_2`, which is odd, as it's not a gas meter, but a hot water meter.
2. In the Energy dashboard, there is no facility to support city heating. The Warmtelink can only be added as a Gas source. Which is again odd, as it's not a gas source.
3. The Energy dashboard converts to GJ to kWh. This may be technically correct, but it messes with the original reported measurements.

![Screenshot_20231105_110512-1](https://github.com/home-assistant/frontend/assets/13982083/87dfef3b-b1ce-4267-893d-0ee541f61ede)
![Screenshot_20231105_111039](https://github.com/home-assistant/frontend/assets/13982083/834eb7ca-e962-4786-b886-3a35928df9da)
![Screenshot_20231105_114512](https://github.com/home-assistant/frontend/assets/13982083/74569f3a-c41f-437f-add9-92db257e769d)

### Describe the behavior you expected

I would expect to have:

1. A specific panel for city heating in the Energy dashboard
2. The reported GJ remain as they are, and not converted to kWh.
3. The sensor named properly, such as sensor.cityheating.energy_consumption.

Optionally: The energy dashboard is very tuned towards a small selection of energy sources, such as electricity and gas. With multiple options for different countries, and an increase in energy developments where we may see different kinds of energy distribution, it might be useful to have the option to define your own category of energy source.

### Steps to reproduce the issue

1. Connect the P1 cable to the Warmtelink P1 port.
2. Add a device to the DSMR integration.
3. Select the new connection, and select the correct DSMR version.
4. Add the new sensor to the Energy dashboard.

### What version of Home Assistant Core has the issue?

core-2023.11.0

### In which browser are you experiencing the issue with?

Firefox 118.0.2

### Which operating system are you using to run this browser?

openSUSE Leap 15.4

### State of relevant entities

```txt
sensor.gas_meter_gas_consumption_2:

state_class: total_increasing
unit_of_measurement: GJ
device_class: energy
icon: mdi:heating-coil
friendly_name: Stadsverwarming verbruik
```

**Comment by karwosts** [comment]
The frontend does not create entity names, if you think one was named incorrectly please file a core issue for the integration that created the sensor.

Your other suggestion for additional utility types is a feature request and can be made in the appropriate section in the community forums.

**Comment by Ceaus** [comment]
Thank you for you response. My apologies for wasting your time. It will split up this bug report with the proper allocations.
