### ISSUE TITLE
shopping-list card doesn't show shopping list unless its already been opened from sidebar

### ISSUE THREAD

**Issue by kohlerryan** [home-assistant/frontend#18546]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Shopping list card does not display (blank) if I restart HA and have yet to open the shopping list from the new sidebar to-do activity.  Same thing happens in iOS - if I close the app and then open dashboard with shopping list card, it is blank.  If I then  navigate to the new to-do sidebar activity, then back to the dashboard the shopping list is visible.

### Describe the behavior you expected

I would expect the shopping list card to show without having to navigate to the sidebar to-do list first.

### Steps to reproduce the issue

1. Add shopping list integration and then add card to dashboard in yaml: "type: shopping-list"
2. restart
3. open dashboard and shopping-list card will not be visible
4. navigate to to-do list sidebar activity, which will open shopping-list
5. open dashboard again and shopping-list card will be visible
...

### What version of Home Assistant Core has the issue?

2023.11.1

**Comment by karwosts** [comment]
I can't reproduce, it's loading fine for me in a standalone card with caching disabled and a hard refresh. 

Does it have to be `shopping-list` type, or do you get similar with `todo-list` ? (both work fine for me)

**Comment by kohlerryan** [comment]
@karwosts i still could not get shopping-list type to work, but thank you for pointing out todo-list type.  That worked like a charm.

What's odd to me is that I only have the shopping list integration, I do not have todo list integration.  But when I updated ha my sidebar app changed to what the todo list integration is - the sidebar app is labeled "To-do Lists".

Happy it's working again- thank you!
