### ISSUE TITLE
Energy dashboard: Wh in devices is scaling wrong

### ISSUE THREAD

**Issue by Chris909090** [home-assistant/frontend#18550]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The issue is in the energy dashboard. If I have a value in kWh it displays correct. 

The valu of Wh are habe a wrong scaling in the frontend. In the statisticsit is write but in the frontend its about factor 10 to high.

The value shows 15,02kWh.
![image](https://github.com/home-assistant/frontend/assets/39734863/c29c4a95-380c-419e-9ecf-f416d355fa00)

But the real value is 3,185Wh.
![image](https://github.com/home-assistant/frontend/assets/39734863/c60deee4-3451-4fc8-9ea3-c1f6957578f3)

### Describe the behavior you expected

It should be displays in the correct scaling.

### Steps to reproduce the issue

1. Add a value with kWh to devices
2. Add a value with Wh to devices

### What version of Home Assistant Core has the issue?
2023.11.1

**Comment by karwosts** [comment]
I can't find anything wrong in my system with Wh sensors in devices, I think we'll need some more information here. 

You say it's off by 10x, but is it really more like 5x? It's displaying 15 kWh and you're expecting 3 kWh?

You're certain you have "today" selected? Is it also consistently wrong on other days, by the same factor, or different?

Do you have any unusual time zone settings that could be a factor, maybe it's not starting at midnight but some other time? Is your TZ consistent with the server's TZ?
