### ISSUE TITLE
Thermostat card behavior inconsistent

### ISSUE THREAD

**Issue by liquidat** [home-assistant/frontend#18572]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Currently, when the thermostat card main screen dial is used to change the thermostat value, and the thermostat is (Zwave) battery powered the dial jumps back after 2s to the old value. The value is only updated once the next sync with the device takes place:
![Kooha-2023-11-08-22-57-29](https://github.com/home-assistant/frontend/assets/1998084/097437f9-6b55-45e9-bd36-a2870a530c37)

However, the detailed view does not have this behavior: if I change the value there, the dial stays where it is:
![Kooha-2023-11-08-22-57-59](https://github.com/home-assistant/frontend/assets/1998084/a6ca9670-5ccf-4898-ba4e-ccee8403d9c7)

This behavior is inconsistent - both views should be behaving in the same way.

### Describe the behavior you expected

Both views of the same dial should behave in the same way.

### Steps to reproduce the issue

1. Have a Zwave, battery powered Thermostat, configure the thermostat card
2. Set the temperature in the main thermostat card view, see that it jumps back after two seconds
3. Open the detailed view, change the temperature in the detailed view, and observe that it does not jump back.
...

### What version of Home Assistant Core has the issue?

2023.11.1

### In which browser are you experiencing the issue with?

Firefox 119.0 (64-bit)

### Which operating system are you using to run this browser?

Fedora 38

### State of relevant entities

```txt
climate.devolo_thermostat_09356_5

heat

hvac_modes: heat
min_temp: 7
max_temp: 35
current_temperature: 19
temperature: 7
friendly_name: Living Room Door Heater
supported_features: 1
```

### Additional information

The inconsistency is caused by the changes due to https://github.com/home-assistant/frontend/pull/15497 - which should have never been merged, as outlined here: https://github.com/home-assistant/frontend/issues/15776#issuecomment-1802738431

The "jumping back after 2s" ONLY works for non-batter powered devices if I am not mistaken. I would bet that this is the less common use case! And just jumping back doesn't really help anyone:

- No indication that there was any mismatch. Users will have no idea why it jumped back (Did I really set the new temperature or did I just zone out for a second? Or was this a UI glitch?)
- No information what the difference between the value set and the value we currently still have is there, so I don't even know what it was set to until the next sync.

PR#15497 just glosses over underlying problems: if setpoints are never updated, than there are other bugs or setup problems that need to be fixed. This should not be "beautified" or hidden in the UI!

A better UI solution (no idea how to make this real with the underlying setup) would be to indicate in the card that there is a certain value set and that the communication to the device still takes place, that the newly set thing is not in effect as of yet.

**Comment by i-am-bloor** [comment]
I believe I may also be seeing this behaviour.

**Comment by liquidat** [comment]
With the recent update, the thermostat card does not behave like this anymore.
