### ISSUE TITLE
Logout deeply hidden

### ISSUE THREAD

**Issue by terba** [home-assistant/frontend#18578]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The logout function is deeply hidden on the profile page. I had to search the internet how to log out from Home Assistant. I think it's a UI problem and security vulnerability in one, as if a user can not logout easily, he/she won't.

### Describe the behavior you expected

The logout button should be next to the statement that the user is logged in on the top of the profile page.

### Steps to reproduce the issue

Try to logout without knowing where the button is.

### What version of Home Assistant Core has the issue?

2023.10.5

**Comment by terba** [comment]
The problem is still there.

**Comment by netdox** [comment]
And the problem becomes even more relevant as the "Keep me logged in" option has been enabled by default since the December update. In my opinion, this is a security problem, considering that different users with different authorization levels use the same workstation.

**Comment by karwosts** [comment]
Fixed by https://github.com/home-assistant/frontend/pull/20076

**Comment by draker42** [comment]
@karwosts I do not agree. New user. Tried to logout for the first time. Gave up and had to Google it. The logout button is still in a bad position and not at all obvious. To be fair the whole system is amazing and I'm beyond blown away, but with the influx of new information and the myriad of variations and just trying to get ssh so I can edit my configuration.yaml and it's VERY difficult... so to be stymied when trying to something as dead simple as logout is very frustrating. 
Recommend this be looked at again. 
Thanks.
