### ISSUE TITLE
Card-mod parameter is not applied

### ISSUE THREAD

**Issue by Opontios** [home-assistant/frontend#18573]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After upgrading to 2023.11.1 from 2023.10.5 the below code is not applied, the ":host" part of it:
```
type: entities
entities:
  - entity: input_number.living_room_shutter_position
    name: Жалюзи зала
    icon: mdi:window-shutter
    card_mod:
      style:
        hui-generic-entity-row:
          $: |
            .info {
              text-overflow: unset !important;
              white-space: unset !important;
              line-height: 15px;              
            }
            :host {
              {% if (is_state('input_boolean.living_room_shutter_choice_helper','off') or is_state('automation.otkrytie_zhaliuzei_po_budilniku', 'off')) %}
                --paper-slider-active-color: var(--disabled-text-color);
                --paper-slider-knob-color: var(--disabled-text-color);
                --paper-slider-container-color: var(--disabled-text-color);
                --paper-item-icon-color: var(--disabled-text-color);
                color: var(--disabled-text-color);
                pointer-events: none;
              {% endif %}              
            }
```
What could possibly have changed to make that not work?

### Describe the behavior you expected

The code to be applied as before.

### Steps to reproduce the issue

1. Add the code to an entities card
2.
3.

### What version of Home Assistant Core has the issue?

2023.11.1

### What was the last working version of Home Assistant Core?

2023.10.5

### In which browser are you experiencing the issue with?

Any browser

### Which operating system are you using to run this browser?

Windows, Companion App on Andorid and iOs

**Comment by karwosts** [comment]
Card mod is not supported here. If you need help with it, please head over to the card-mod repository.
