### ISSUE TITLE
Field not showing up when trying to add the Insteon Integration w/ PLM modem

### ISSUE THREAD

**Issue by Juror2372** [home-assistant/frontend#18570]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am trying to setup the Insteon integration using a PLM modem, however, the field to enter the path of the USB device is not showing in the Insteon PLM box
<img width="302" alt="insteon-add" src="https://github.com/home-assistant/frontend/assets/124649789/c0603ef4-75b2-4d92-af50-5d27949fcd22">
<img width="298" alt="insteon-submit" src="https://github.com/home-assistant/frontend/assets/124649789/329c1181-e48e-44d0-9c12-e0ce6f5d74f0">

### Describe the behavior you expected

I expected a field to be shown

### Steps to reproduce the issue

1. add insteon integration
2. choose PowerLink Modem
3.
...

### What version of Home Assistant Core has the issue?

2023.11.1

### In which browser are you experiencing the issue with?

Firefox 119.0

### Which operating system are you using to run this browser?

Windows 10, iPadOS 17.2 and Ubuntu 22.04

**Comment by karwosts** [comment]
While perhaps the frontend could do a better job explaining what is happening, I think what is really happening here is core is not finding any candidates for your USB device, and so it sends a select form to frontend with zero options to choose from.

You may want to open a backend issue for insteon integration to investigate why it is not finding your candidate usb device. 

For example I don't have any insteon device, and I see this same menu when I add the PLM, and I see this is the form data that is returned. Note how the "options" for the select selector is an empty array. So I guess nothing ends up being rendered. 

Could have frontend display a disabled select box with something like "No options", but that's not going to help you get your insteon working. 

```
{
    "type": "form",
    "flow_id": "72636ca5319e96c13ebc3c6e9ee4270a",
    "handler": "insteon",
    "step_id": "plm",
    "data_schema": [
        {
            "type": "select",
            "options": [],
            "name": "device",
            "required": true
        }
    ],
    "errors": {},
    "description_placeholders": null,
    "last_step": null,
    "preview": null
}
```

**Comment by Juror2372** [comment]
I tried a VM and passthrough my USB port. It works that way. I'll close this issue. Thanks for your comment @karwosts

**Comment by Juror2372** [comment]
I tried a VM and passthrough my USB port. It works that way. I'll close this issue. Thanks for your comment @karwosts
