### ISSUE TITLE
Thermostat card (and detailed view) send bad values to backend (conversion ?)

### ISSUE THREAD

**Issue by potens1** [home-assistant/frontend#18576]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

It seems the frontend is sending bad values to the backend when setting the temperature setpoint.

if I define 23.3°, the value sent  is 20.299999999999997, for 20.4, it's 20.400000000000002 but for 20.5, that's the good value, 20.5. This is not consistant, sometime the good value is sent (20.4 for 20.4)

You can see in the screenshot a capture of what is sent on the websocket

![image](https://github.com/home-assistant/frontend/assets/3988571/64efba26-3809-459b-8ec7-604736c070ad)

You can see the values are wrong, and, for example, the third (good) and the last (bad) values sent should be the same, 20.3

### Describe the behavior you expected

I expect the component to respect the step defined (0.1 in my case) and send the values it displays

### Steps to reproduce the issue

1. Open the thermostat card
2. open the browser dev tools works
3. on the network tab, go the the websocket and check values sent
4. change the temperature set point value in the card (either +/- on the detailed card, either moving the point)
5. values are not exactly the ones you asked for, and this is not consistant
...

### What version of Home Assistant Core has the issue?

2023.11.1

### In which browser are you experiencing the issue with?

Brave Version 1.59.117 (64-bit), Firefox 118.0.2 (64-bit), Edge (Linux) Version 119.0.2151.2 (Official build) dev (64-bit)

### Which operating system are you using to run this browser?

Arch Linux

### Problem-relevant frontend configuration

```yaml
No configuration, the component is added from MQTT auto-discovery
```

### Javascript errors shown in your browser console/inspector

```txt
None
```

### Additional information

I opened a bad ticket in the core about this [ home-assistant/core/issues/103675 ]

**Comment by karwosts** [comment]
It's not really a conversion issue, but just a quirk of how floating point math works with 0.1 step sizes. 

If you open up your browser console, and type in `20.3 + 0.1`, you'll see the result is `20.400000000000002`

Does this cause any particular problem in the end device when this occurs, or were you just pointing out that you noticed a discrepancy?

Given that HA says that temperatures are floats, it seems possibly expected that some rounding issues might need to be handled sometimes.

**Comment by potens1** [comment]
I understand what you said here, but I don't get why sometimes it will be 20.3, and sometimes 20.2999999999999997. Yes it is a problem because the end device expect to have 1 decimal, not twenty (and passing the real value received on the mqtt side is sent to the firmware), but I'm trying to modify the firmware of it. A possible fix could be to multiply everything by 10**precision(from step size) , and then divide again everything (i.e.(20.3*10**1+0.1*10**1)/10==20.4), or Number((20.3+0.1).toPrecision(3)) but, let's be honest, if I'm the only one having a problem with that, I understand it's not worth it  (but still interesting to keep in mind for future), even if I still think it would be nicer to have it this way and it is "easy" to correct it in the frontend (but with some computations that are unneeded for the majority)
