### ISSUE TITLE
Display of decimal places on chart Y-axis, even if they are turned off

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#18587]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hello,
decimal places are sometimes displayed (but mostly after exiting the menu and returning), even if they are disabled (attached pictures from behavior and settings).

![ShowedLotOfDecimalNumbers](https://github.com/home-assistant/frontend/assets/61636045/5fbca787-7a79-4332-b2cc-4e897e5339c3)

![SettingsOfDecimalNumbers](https://github.com/home-assistant/frontend/assets/61636045/c07d991f-f37e-40aa-8f01-cef187ab96f3)

### Describe the behavior you expected

When set of value haven´t decimal places, then show values without decimal places.

### Steps to reproduce the issue

Issue happened very rarely.

### What version of Home Assistant Core has the issue?

2023.11.1

### What was the last working version of Home Assistant Core?

also seen in previous versions

### In which browser are you experiencing the issue with?

screenshot from Android browser

### Which operating system are you using to run this browser?

Android 13

**Comment by karwosts** [comment]
Are you referring only to the values on the Y axis? I don't believe display precision is intended to control those, and I'm not sure how it would make any sense to do so for a line graph.

**Comment by misa1515** [comment]
@karwosts yes, referring only to the decimals places on the Y axis. Showed e.g. 132,00000000000003 instead 132 (but this is showed only sometimes and not found dependencies).

**Comment by misa1515** [comment]
not yet solved
