### ISSUE TITLE
Missing in lokalise - part of import plan

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#18589]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing in lokalise - part of import plan (screenshot attached)

![Screenshot](https://github.com/home-assistant/frontend/assets/61636045/a942776d-283d-46d0-a8bc-9677ab237469)

### Describe the behavior you expected

Please add missing text to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.11.1

### What was the last working version of Home Assistant Core?

not relevant

**Comment by karwosts** [comment]
This string comes from home-assistant/core, it would have to be localized there, not in frontend.
