### ISSUE TITLE
Users Tab missing with new User/Owner

### ISSUE THREAD

**Issue by KlaraJa** [home-assistant/frontend#18593]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I created a new user (a separate admin account), made it an admin, and under Settings --> People is the Users tab missing.
On the existing account with admin privileges it is still possible to access the Users tab.

Even after transferring the Owner of the System to the new user, the tab is still missing (but it is still accessible via the URL) and the old (existing) User still has the Users tab available.

### Describe the behavior you expected

Every User with admin privileges, should have the Users tab visible and does not have to use the URL.

### Steps to reproduce the issue

1. Create new **_User_** (not Person)
2. Give them Admin, Local only rights
3. Change the Owner of the System from the old owner to the new User (via /config/.storage/auth file) (it will be the same if the owner is not changed)
4. Reboot system
5. Login with new user
6. Goto Settings --> People
(7. Goto `https://*HASSURL*/config/users`) this is just to check if this is really available

### What version of Home Assistant Core has the issue?

2023.11.1

### In which browser are you experiencing the issue with?

Safari Version 17.1 (19616.2.9.11.7) and Chrome Version 119.0.6045.123

### Which operating system are you using to run this browser?

macOS Sonoma 14.1 (23B74)

**Comment by karwosts** [comment]
Users tab is an advanced-mode only feature. You forgot to enable advanced mode for your new admin account. 

Once you enable it, it should be visible.

**Comment by KlaraJa** [comment]
Oh yes you are right, advanced mode was off.

But why does with the advanced mode turned off the Developer Tools are shown and also why is it then accessible via the `/users` URL? shouldn't this be blocked if the advanced mode is off?

**Comment by karwosts** [comment]
> But why does with the advanced mode turned off the Developer Tools are shown 

Developer tools is not gated by advanced mode. I realize it is somewhat subjective what features should be considered "advanced" vs not, but that is what is currently programmed. 

> why is it then accessible via the /users URL? shouldn't this be blocked if the advanced mode is off?

Advanced mode is not intended to "block" anything, it's not a security feature, it's just to hide some advanced controls from beginner users to present a simpler UI. I guess there's no need to prevent a URL from loading if someone wants to access, probably nobody ever considered blocking that off.

**Comment by karwosts** [comment]
Closing as the original issue is resolved.
