### ISSUE TITLE
Attempting to save an automation for Tags pops up a rename dialog box and does not save the changes. See also #14139

### ISSUE THREAD

**Issue by Absoblogginlutely** [home-assistant/frontend#18604]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After adding a tag and then selecting the automation setting, creating an automation and hitting save does not save the automation but instead pops up a save dialog box.
If you rename the automation or hit cancel, the automation is not saved.
As a result, leaving the tag page loses the automation. 

Issue occurs on multiple browsers and computers.
Same as Issue #14139 but that was a different version.

### Describe the behavior you expected

Creating an automation for a tag does not get saved when hitting the save button.

### Steps to reproduce the issue

1. Scan a tag
2. Select automation with tag.
3. Add a device and action
4. Hit save
5. Rename prompt appears. Hit cancel or choose a new name
6. Hit the back arrow to navigate to the tags page
7. Select automation with tag - page has been wiped back to normal

### What version of Home Assistant Core has the issue?

Core 2023.11.1 Supervisor 2023.11.0 Operating System 11.1 Frontend 20231030.1

### In which browser are you experiencing the issue with?

Edge Dev 120.0.2186.2 

### Which operating system are you using to run this browser?

Windows 11 23H2

**Comment by karwosts** [comment]
AFAIK the tag page is not intended to show the automations for a tag. 

When I do your steps, you are right when you go back to tags page the automation you created is not shown. 

But if you then go to Settings -> Automations, you should see the automation you created there.

**Comment by Absoblogginlutely** [comment]
Thanks for the update @karwosts , I can confirm that the automations show up in the settings/automations - all 10+ of them after I kept trying to get this working, lol.
The Tag and automation is now working great. Thanks for your assistance.
