### ISSUE TITLE
Sliders lost numeric value on knob movement in 2023.11

### ISSUE THREAD

**Issue by ricarva** [home-assistant/frontend#18611]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Sliders (for lights, volume) used to have a numeric value over the knob when it was moved; this has disappeared woth HA 2023.11.

### Describe the behavior you expected

When moving slider, numeric value would appear over knob.

### Steps to reproduce the issue

1. Click on knob in slider, move up or down.
2. Numeric value is absent.
3.
...

### What version of Home Assistant Core has the issue?

2023.11

### What was the last working version of Home Assistant Core?

2023.10

### In which browser are you experiencing the issue with?

Chrome, Edge

### Which operating system are you using to run this browser?

Win11

**Comment by karwosts** [comment]
I'm on latest (2023.11) and I still see the knob:

![image](https://github.com/home-assistant/frontend/assets/32912880/1ac08565-dd7e-430c-ad57-c85e2ee69851)

If you use any custom resources on the frontend, maybe try out safe mode and see if that makes a difference?

**Comment by ricarva** [comment]
> I'm on latest (2023.11.1) and I still see the knob:
> 
> ![image](https://user-images.githubusercontent.com/32912880/282140974-1ac08565-dd7e-430c-ad57-c85e2ee69851.png)
> 
> If you use any custom resources on the frontend, maybe try out safe mode and see if that makes a difference?

@karwosts how do I enable Safe Mode? Can't find clear info on that anywhere.

**Comment by karwosts** [comment]
> > I'm on latest (2023.11.1) and I still see the knob:
> > 
> > ![image](https://user-images.githubusercontent.com/32912880/282140974-1ac08565-dd7e-430c-ad57-c85e2ee69851.png)
> > 
> > If you use any custom resources on the frontend, maybe try out safe mode and see if that makes a difference?
> 
> @karwosts how do I enable Safe Mode? Can't find clear info on that anywhere.

Settings -> Restart -> Advanced Options -> Restart in safe mode.

**Comment by ricarva** [comment]
> > > I'm on latest (2023.11.1) and I still see the knob:
> > > ![image](https://user-images.githubusercontent.com/32912880/282140974-1ac08565-dd7e-430c-ad57-c85e2ee69851.png)
> > > If you use any custom resources on the frontend, maybe try out safe mode and see if that makes a difference?
> > 
> > 
> > @karwosts how do I enable Safe Mode? Can't find clear info on that anywhere.
> 
> Settings -> Restart -> Advanced Options -> Restart in safe mode.

@karwosts rhank you for the pointer: indeed,the problem seems to be with frontend add-ons that use sliders.

On HA's native resources, the numeric indicator is still there.

Seems like some underlying change to sliders in HA broke 3rd party resources.

**Comment by ricarva** [comment]
Closed.
