### ISSUE TITLE
issue on automation trigger time

### ISSUE THREAD

**Issue by villar3** [home-assistant/frontend#18618]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![Capture d’écran 2023-11-10 à 21 32 28 (3)](https://github.com/home-assistant/frontend/assets/62641534/1705136f-41ea-451e-bdd3-1ec95c302ab6) the value on the title is not the same as the triggers

### Describe the behavior you expected

the same value in the title and in the trigger

### Steps to reproduce the issue

1.Create a new automation
2.add trigger "time"
3.assign 22 for the "hours"
...

### What version of Home Assistant Core has the issue?

2023.11.1

### In which browser are you experiencing the issue with?

Home assistant companion 2023.7 (2023.471)

### Which operating system are you using to run this browser?

macOS Catalina 10.15.7

**Comment by karwosts** [comment]
Can you share what is the country and language setting of your HA server? Seems like this must be related to locale settings.

**Comment by villar3** [comment]
![Capture d’écran 2023-11-15 à 21 29 00](https://github.com/home-assistant/frontend/assets/62641534/1545e415-d4a4-44b2-b356-d4888a947588)
Yaml says 22:00:00 !

**Comment by karwosts** [comment]
Is your server timezone different than your client timezone?

I see a similar shift in time when I change the server time zone to be different than my client, and I set "Use server time zone" in the profile, it must be trying to translate the time from server to client, or vice-versa, not sure which yet.

**Comment by villar3** [comment]
Client and server is on the same time zone (Paris UTC +1) . if i set "use server time zone" i see the same issue
