### ISSUE TITLE
Blank modal when trying to add Spotify service

### ISSUE THREAD

**Issue by Magic-Mayo** [home-assistant/frontend#18628]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I've recently run into an issue when trying to add a Spotify service that results in a modal being displayed with no information.  I found the problem I have in the logs but it would be nice if it actually displayed on the frontend and a user doesn't have to go digging thru logs to find the problem.  My specific problem was that I had yet to setup the developer app for the new account I was trying to add.  

![image](https://github.com/home-assistant/frontend/assets/49295328/9cd59227-e8eb-47af-add6-04ba1892548a)

### Describe the behavior you expected

I expect to see an error message instead of a blank modal.

### Steps to reproduce the issue

1. Add a new Spotify service from the frontend before setting up a developer app with the account you're adding
2. After you sign in to Spotify and click the link account button you are redirected back with a blank modal

### What version of Home Assistant Core has the issue?

2023.11.2

### In which browser are you experiencing the issue with?

Google Chrome 118.0.5993.88 

### Which operating system are you using to run this browser?

popOS 22.04

**Comment by karwosts** [comment]
Is this something you're still able to reproduce? If I try to add a spotify integration, the first thing I see is this form:

![image](https://github.com/home-assistant/frontend/assets/32912880/fef6ac93-a578-4c1e-8871-978aaba9b2c8)

I don't see how to get past this without "setting up a developer account". So I don't quite understand how you got where you are.

**Comment by Magic-Mayo** [comment]
Yes, this only happens when adding an _additional_ spotify service.  I have one setup already and I want to add another separate account.  I haven't been able to get the modal you've shown here with the additional account even after setting up the developer account.

**Comment by karwosts** [comment]
@joostlek - let me know if this is something up your alley. I tried to see if there was something wrong in the frontend, but I don't have any spotify accounts, so I never was able to reproduce it. Maybe you know why it might have a blank step flow, or have some clues what might have happened.

**Comment by joostlek** [comment]
Yep! Recently I've been debugging with someone else's Spotify credentials and encountered the same issue. I can take a look if we can raise a proper error here.

For your original question, about the empty models. I think whenever you encounter them it's a bug. This can mean a translation key for an abort is probably missing. Not sure how we can catch that (or where).
