### ISSUE TITLE
QNAP Integration

### ISSUE THREAD

**Issue by TheBelgarion** [home-assistant/frontend#18692]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

due to the newish QNAP integration and it automatically detected my old config setup and did some converting on it i now have the integration twice.

1 Integration with my QNAP in it - which seems to be the one converted from my old values and looks the sameish.
another Integration which is empty and i can configure it!?

But i cant remove the second one the only option on it is Documenation?

How to remove the second one ?

I removed all the code from the config page and reloaded that also didnt help much - but guess that no longer needed anyway now.

### Describe the behavior you expected

only haveing 1 QNAP Integration with my QNAP

### Steps to reproduce the issue

if only i knew why i have 2 ..

### What version of Home Assistant Core has the issue?

2023.10.5

### What was the last working version of Home Assistant Core?

2023.10.5

### Which operating system are you using to run this browser?

Win 11

**Comment by karwosts** [comment]
You might want to file an issue in core for the QNAP integration, as whatever you're seeing being displayed is likely due to what configuration information the core is sending to the frontend.

**Comment by TheBelgarion** [comment]
https://github.com/home-assistant/core/issues/104171
