### ISSUE TITLE
Link In Tibber Configuration Menu Is Wrong

### ISSUE THREAD

**Issue by tweimann** [home-assistant/frontend#18693]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Link in the Tibber configuration menu is wrong, probably because Tibber changed the URL
![image](https://github.com/home-assistant/frontend/assets/63401747/f7d99989-8261-4458-a106-f65577ac4e25)

### Describe the behavior you expected

The Link should be https://developer.tibber.com/settings/access-token

### Steps to reproduce the issue

1. Go to Settings>Integrations
2. Click on "Add Integration"
3. Click on Tibber

### What version of Home Assistant Core has the issue?

2023.11.2

**Comment by karwosts** [comment]
Please file this issue in home-assistant/core for the Tibber integration. Frontend does not control this link, this form that is being displayed comes from core and the `tibber` integration. 

Thanks!
