### ISSUE TITLE
Quick reload is not available for admin users only for owner

### ISSUE THREAD

**Issue by lieven121** [home-assistant/frontend#18703]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Quick reload option is not available for my user (who is an admin but not an owner)

### Describe the behavior you expected

The Quick reload to be available to all both admins and owners.

### Steps to reproduce the issue

1. Create another user that is an admin
2. Login as that user
3. The quick reload is not available

### What version of Home Assistant Core has the issue?

2023.11.2

### In which browser are you experiencing the issue with?

Microsoft Edge Version 119.0.2151.72 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Tested on Windows 10 and 11, Android

**Comment by karwosts** [comment]
I believe you need to enable `advanced mode` in your user profile for this to be shown, it has nothing to do with being the owner.

**Comment by lieven121** [comment]
My apologies, you are right, is this documented somewhere? I didn't find it but it's possible i overlooked it.

this is btw the link for advanced mode, not highly informative
![image](https://github.com/home-assistant/frontend/assets/7773244/c75905a9-47a1-4ee4-8e55-c66118fd2a94)
 
Should I close the issue or expand on it to better document this?

**Comment by karwosts** [comment]
I guess if you want to suggest to improve the website documentation, that would need to go in the [home-assistant.io](https://github.com/home-assistant/home-assistant.io/) repository, so probably this issue here would be closed regardless of if you want to pursue that or not.

I'm not sure if this is well documented anywhere.

**Comment by lieven121** [comment]
okay thanks :)
