### ISSUE TITLE
Ugly Text in HACS, when new repositories

### ISSUE THREAD

**Issue by MaxGroh8684** [home-assistant/frontend#18700]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When there are new repositories in HACS. The upper button to dismiss all the new repositories is huge because the Text of the button shows maxim 3 letters in width.

### Describe the behavior you expected

Maybe write the text above or below the buttons funktional text.

### Steps to reproduce the issue

1. Go to HACS
2. see if there are new repositories
3. if yes, you'll see the issue
4. if no return at a different time and start wirh one.

### What version of Home Assistant Core has the issue?

all

### What was the last working version of Home Assistant Core?

none

### In which browser are you experiencing the issue with?

all mobile browsers.

### Which operating system are you using to run this browser?

android 13, ios 16.6.1

**Comment by frenck** [comment]
> When there are new repositories in HACS. The upper button to dismiss all the new repositories is huge because the Text of the button shows maxim 3 letters in width.

Hi there @MaxGroh8684 👋 

HACS is a custom integration, which is not supported or maintained by the Home Assistant project. Please report issues with the custom integration project instead.

Thanks! 👍 

../Frenck
