### ISSUE TITLE
Lock card does not respect default code

### ISSUE THREAD

**Issue by oyvindwe** [home-assistant/frontend#18705]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using the lock card without entering a code does not work.

I have configured my lock with a default code, but when I use the lock card lock or unlock, I am still being asked for a code:
<img width="580" alt="image" src="https://github.com/home-assistant/frontend/assets/5984518/be22cd0d-b4a0-4cde-bb7e-cc1511730f33">

However, if try to lock or unlock without providing a code, the service call is not sent. Instead, I see this service call on the web socket:
```
{"type":"call_service","domain":"system_log","service":"write","service_data":{"logger":"frontend.js.latest.202310302","message":"Unhandled promise rejection from Firefox 118.0 on Mac OS 10.15\nError: Code dialog closed\nhass.localize (src/data/lock.ts:42:12)\n_callService (src/dialogs/more-info/components/lock/ha-more-info-lock-toggle.ts:71:6)\n_turnOff (src/dialogs/more-info/components/lock/ha-more-info-lock-toggle.ts:59:17)\n_valueChanged (src/dialogs/more-info/components/lock/ha-more-info-lock-toggle.ts:43:11)\ncall (src/lit-html.ts:2018:28)\ndispatchEvent (src/common/dom/fire_event.ts:76:7)\n_toggle (src/components/ha-control-switch.ts:61:14)\n_toggle (src/components/ha-control-switch.ts:118:13)\ndata (src/manager.js:334:18)\nemit (src/recognizers/tap.js:117:19)","level":"debug"},"id":40}
```
A similar log message is sent in Chrome.

I am not sure if HA should ask the user to enter a code or not when a default code is provided. Personally, I would favour _not_ asking the user for a code in this case.

Secondary, the lock slider transitions position (but not colour) when asking for the code, but if I cancel entering the code, it does not slide back. In this case, I think it should not change position until a code is submitted.

### Describe the behavior you expected

Lock should lock or unlock.

### Steps to reproduce the issue

1. Install an integration with a lock (e.g. Verisure)
2. Configure a default code on the lock
3. Use the lock card to lock or unlock

### What version of Home Assistant Core has the issue?

2023.12.0.dev0

### Additional information

Found during debugging https://github.com/home-assistant/core/issues/101404

**Comment by karwosts** [comment]
Please attach the full attributes of the lock entity. 

From what I can tell the backend does not provide any information to the frontend that a default code exists, so it has no way to know if it can/should bypass the dialog. The current dialog is displayed when the entity has a `code_format` attribute. 

If you want it to be bypassed in the frontend, either that attribute has to not be provided, or some other information must be made available to tell it so. 

That said, I think fixing to make the frontend pass an empty string as the code should be fixable, if you want to go that route.

**Comment by oyvindwe** [comment]
> Please attach the full attributes of the lock entity.

Where do I find those? I can see my default code is set in the options view, and it is being used in other service calls. That said, I would not share my actual code, and I also think the backend should not expose the actual code to the frontend once set; it should rather have a boolean attribute `default_code_set` or something like that.

**Comment by oyvindwe** [comment]
> That said, I think fixing to make the frontend pass an empty string as the code should be fixable, if you want to go that route.

This is currently incompatible with the backend, but a fix is on the way. See the discussion here: https://github.com/home-assistant/core/pull/103463/files#r1399255188

**Comment by karwosts** [comment]
The attributes are listed in developer-tools/states:

![image](https://github.com/home-assistant/frontend/assets/32912880/6ec9a960-e872-447f-9946-430f67591da0)

I don't expect the actual code is ever exposed to the frontend, and yes I would not suggest that. I'm just saying if you want the frontend to act on the presence of a default code, than something in the entity attributes needs to tell it that that code exists.

**Comment by karwosts** [comment]
I will say I am a little confused about the concept of a default code though. If opening without a code is accepted, why should the frontend _ever_ know anything about the code? Why are we passing a code_format at all?

**Comment by oyvindwe** [comment]
The default code is configured on the lock entity in the frontend, as discussed in https://github.com/home-assistant/architecture/discussions/870 

Here is how the lock entity options view looks like when opening after setting a code (not actual code):
<img width="581" alt="image" src="https://github.com/home-assistant/frontend/assets/5984518/886e91ff-3bb9-46f5-bda5-3cdd94e680bc">

It is _not_ listed as an entity attribute though. Here are the attributes for the lock entity:
```
changed_by: Home Assistant
code_format: ^\d{6}$
method: REMOTE
friendly_name: Hoveddør
supported_features: 0
```

**Comment by oyvindwe** [comment]
If something is needed in the backend, I'm happy to contribute!

**Comment by gjohansson-ST** [comment]
> Sounds like gjohanasson wants to look at this, so I'll just let him drive it. 

I will need all the help I can get @karwosts  😀 
Tried to take a look at this but can't understand why it's not passing the default of `""` when submitting the dialog. 😕

**Comment by karwosts** [comment]
I guess it's probably this, if the `response` from the dialog is `""`, that's a falsy value, so it throws the error instead of proceeding. 

```
export const callProtectedLockService = async (
  element: HTMLElement,
  hass: HomeAssistant,
  stateObj: LockEntity,
  service: ProtectedLockService
) => {
  let code: string | undefined;

  if (stateObj!.attributes.code_format) {
    const response = await showEnterCodeDialogDialog(element, {
      codeFormat: "text",
      codePattern: stateObj!.attributes.code_format,
      title: hass.localize(`ui.dialogs.more_info_control.lock.${service}`),
      submitText: hass.localize(`ui.dialogs.more_info_control.lock.${service}`),
    });
    if (!response) {
      throw new Error("Code dialog closed");
    }
    code = response;
  }
```

Instead of `if(!response)`, maybe try `if(response == null)`

**Comment by gjohansson-ST** [comment]
So simple... clearly couldn't see the forrest for all the trees. Will test shortly 😁

**Comment by oyvindwe** [comment]
@gjohansson-ST will you also look into:
1. Options form displaying the stored code
2. Not asking for code when default code is set
?

**Comment by gjohansson-ST** [comment]
> 1. Options form displaying the stored code
> 2. Not asking for code when default code is set

@oyvindwe 
1. What's the issue with that?
2. Not sure we should. Can there not be use-cases when someone wants another code than the default?

**Comment by oyvindwe** [comment]
> 1. What's the issue with that?
It would be a security best practice - possible information leak. But I would rate it as a low risk.

> 2. Not sure we should. Can there not be use-cases when someone wants another code than the default?
Good point - I don't know. Personally, I don't use that dialog, so I'm happy either way

**Comment by gjohansson-ST** [comment]
> > 1. What's the issue with that?
> 
> It would be a security best practice - possible information leak. But I would rate it as a low risk.

You mean it's there in clear text and not masked (password field)?
Can probably fix that in another PR

**Comment by oyvindwe** [comment]
> You mean it's there in clear text and not masked (password field)?

Exactly! Masking it in the frontend would be sufficient as I see it.

> Can probably fix that in another PR

Excellent!

**Comment by piitaya** [comment]
Should we add an attribute to inform the front-end that a default code is set? So we don't have to display the code prompt.

**Comment by gjohansson-ST** [comment]
> Should we add an attribute to inform the front-end that a default code is set? So we don't have to display the code prompt.

Yes. I think we should!

**Comment by piitaya** [comment]
Is the default code in the entity registry? If yes, we can use that information.

**Comment by gjohansson-ST** [comment]
> Exactly! Masking it in the frontend would be sufficient as I see it.

https://github.com/home-assistant/frontend/pull/18722
