### ISSUE TITLE
Notification - updating device deletes data

### ISSUE THREAD

**Issue by TurboJens** [home-assistant/frontend#18708]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When logging in with a new device (phone/tablet) this will be given new entity.

When updating automation with notifications via mobile app, selecting the new device delete all data from fields message, title, target and data.

### Describe the behavior you expected

I would expect all information to retain in the fields.

### Steps to reproduce the issue

1. Create a new automation with action "mobile app notification" fill inn some data, like message and title
2. Save
3. Edit action, select another device and everything is lost.
...

### What version of Home Assistant Core has the issue?

2023.11.1

### In which browser are you experiencing the issue with?

Brave (Version 1.60.118 Chromium: 119.0.6045.163 (Official Build) (64-bit))

### Which operating system are you using to run this browser?

Windows 11

### Additional information

I've had this issue for a long time, so it's tested on multiple instances of HA, different core versions, on different browsers and the error is also in the companion app on Android at least.

**Comment by karwosts** [comment]
May be related to #12325

Are you using the `Call service` action or a `Device` action?

**Comment by TurboJens** [comment]
Yes, seem to be pretty much the same issue as #12325 

I'm using the Call service function for this.

**Comment by karwosts** [comment]
Should be fixed by #18772 in 2023.12
