### ISSUE TITLE
Strange last column behaviour in Lovelace.

### ISSUE THREAD

**Issue by Teddy-Moeller** [home-assistant/frontend#18714]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The last column is squished/compressed. I can click another view/tab and then back again, then it usually fixes it. 
the error is only showing sometimes. and I have not been able to find a pattern. Except that it looks like it is ONLY the last column,
I have tried with Waterfox (Windows 11) and Firefox (Linux mint). also on a new install of home assistant. same behavior.
![Home assistant](https://github.com/home-assistant/frontend/assets/11791271/d479ae43-fe28-4343-8f28-77f9ed2e0da1)

### Describe the behavior you expected

all columns should be displayed correct.
I have tried to search to see if this has been seen before, but I have not been able to find anything. If it has, please close this and refer me to the original one.

### Steps to reproduce the issue

1. start firefox or waterfox
2. navigate to your HA
3. navigate arround (can take serveral tries) for me it is always the first "tab" and tends to be more provoked when the browser window is halfed (window key + arrow left/right key)
4. 
...

### What version of Home Assistant Core has the issue?

2023.11.2

### What was the last working version of Home Assistant Core?

unkown but at least 3 months prior

### In which browser are you experiencing the issue with?

waterfox G6.0.5

### Which operating system are you using to run this browser?

Windows 11

**Comment by Teddy-Moeller** [comment]
another view "distorted"
![Home assistant2](https://github.com/home-assistant/frontend/assets/11791271/3b4912cd-e3d5-43d1-834d-56be259ceadb)

**Comment by ildar170975** [comment]
You seem to have a lot of custom cards. 
Can you reproduce the glitch with a view containing conventional cards only?

**Comment by karwosts** [comment]
Maybe duplicate of https://github.com/home-assistant/frontend/issues/17182

Check and see if you have the `has-selector` enabled in firefox options.
