### ISSUE TITLE
Sequence inside a parallel automation shown as unknown in visual editor

### ISSUE THREAD

**Issue by tispokes** [home-assistant/frontend#18725]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using the visual editor and having a sequence inside a parallel action, the editor shows this as "Unknown"
Same issue when writing a script as mentioned in the docs
https://www.home-assistant.io/docs/scripts/#parallelizing-actions

### Describe the behavior you expected

Show actions like using parallel mode 

### Steps to reproduce the issue

sequence:
      - parallel:
          - sequence:
              - wait_for_trigger:
                  - platform: state
                    entity_id: binary_sensor.motion
                    to: "on"
              - service: notify.person1
                data:
                  message: "This message awaited the motion trigger"
          - service: notify.person2
            data:
              message: "I am sent immediately and do not await the above action!"

### What version of Home Assistant Core has the issue?

core-2023.11.3

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

Android 14, W11

**Comment by karwosts** [comment]
There is a current PR undergoing review which will address this issue.

**Comment by karwosts** [comment]
unstale
