### ISSUE TITLE
Card Visual Editor doesn't tell you the NAME of the card you are editing. 

### ISSUE THREAD

**Issue by dopeytree** [home-assistant/frontend#18737]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Visual Card Editor doesn't tell you the 'NAME' of the card you are editing.

<img width="1512" alt="Screenshot 2023-11-23 at 18 51 56" src="https://github.com/home-assistant/frontend/assets/103341262/c2d02705-7a5e-42e8-bb49-7fd3ff254f28">

As a new home-assistant user I do a lot of googling each card to find the documentation.

Users have to jump into YAML editor to see the card title and then go and google it to find the GitHub page. 

I suppose this is kind of a HACs issue but it would still be cool if Home-assistant could address it at source to help users out.

<img width="1512" alt="Screenshot 2023-11-23 at 18 56 16" src="https://github.com/home-assistant/frontend/assets/103341262/b5f2d48a-d1f4-40a7-874f-463627d5a404">

 
Proposed solution Would a simple piece of code to show the 'cards' name & possibly just generate a google search on click.

Visualisation of solution = SHOW { card.name } DOCUMENTATION
<img width="824" alt="Screenshot 2023-11-23 at 19 18 39" src="https://github.com/home-assistant/frontend/assets/103341262/cd143a60-3348-4e98-aca6-2984ebfb78f2">

It would either just print the { card.name } or could print the name and auto link to a google search link this:

Google uses this: https://www.google.com/search?client=safari&rls=en&q=plotly+graph+homeassistant+documentation

So it would just need to take the card. name and format any spaces as +

https://www.google.com/search?client=safari&rls=en&q= {card.name: format space = '+' }

I dont know how to code just yet so these are just IDEAS.

### Describe the behavior you expected

Expected at a minimum for visual editor to print the card's name.

### Steps to reproduce the issue

1. Choose a card using the VISUAL EDITOR
2. Add an entire etc.
3. Save.
4. Click Done on dashboard.
5. Edit dashboard.
6. Edit the card you have just created.
7. Wonder which card you used?
8. Have to click YALM editor.

### What version of Home Assistant Core has the issue?

Core: 2023.11.3  - Frontend: 20231030.2

### In which browser are you experiencing the issue with?

Safari Version 17.1 (19616.2.9.11.7)

### Which operating system are you using to run this browser?

MacOS (Sonoma) v14.1.1 (23B81)

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
N/A
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

### Additional information

N/A

**Comment by karwosts** [comment]
There is a mechanism for a custom card to add a documentation URL, when pushing the customCard object to the window, the card may include a `documentationURL` link, in which case it will add this to the Help button in the top right of the card, e.g.:

```
window.customCards = window.customCards || [];
window.customCards.push({
    type: 'grocy-chores-card',
    name: 'Grocy Chores and Tasks Card',
    preview: false,
    description: 'A card used to display chores and/or tasks from the Grocy custom component.',
    documentationURL: 'https://github.com/isabellaalstrom/lovelace-grocy-chores-card'
});
```

![image](https://github.com/home-assistant/frontend/assets/32912880/50f11f55-5dba-4829-95d5-cd2e6c07db43)

If this is missing on your favorite custom card, please add a suggestion in their repository to add this link.
