### ISSUE TITLE
'TODAY' button on Energy Dashboard does not switch back to today

### ISSUE THREAD

**Issue by doctordarko** [home-assistant/frontend#18743]
### The problem

After selecting any date option on the Energy Dashboard, clicking 'TODAY' button does not return the date to today. The only way to view today's data is choosing Today under the date picker. You'd expect those 2 button to act identically.

<img width="249" alt="image" src="https://github.com/home-assistant/core/assets/57649463/63282496-a41c-4dde-8147-9003e0fcd989">

### What version of Home Assistant Core has the issue?

2023.11.0

### What was the last working version of Home Assistant Core?

2023.10.x

### What type of installation are you running?

Home Assistant Core

**Comment by matthiasdebaat** [comment]
Let's change the label to 'Now'. This works for the different time periods and moves the history viewer to the present.

**Comment by doggkruse** [comment]
I think even changing the label to "now" its misbehaving.  If you click "today" repeatedly it keeps extending the date range by adding a previous day.

Additionally, if this "today" button is meant to snap the end date to now, its inconsistent with the behavior of "today" in the rest of the UI

**Comment by karwosts** [comment]
>  If you click "today" repeatedly it keeps extending the date range by adding a previous day.

I don't see this. If you can consistently reproduce this, please open a new issue for that, since that seems like a bug.

**Comment by speakradmin** [comment]
The today button still does nothing as of:

Core
2024.2.3
Supervisor
2024.02.0
Operating System
11.5
Frontend
20240207.1
