### ISSUE TITLE
Templates/Scripts/Automation YAMLs auto reformatting/wrapping

### ISSUE THREAD

**Issue by emandtf** [home-assistant/frontend#18774]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

_It's not a new (I mean of latest releases) "issue" but it starts to became very frustrating especially when a template/script/automation is long and complicated._

I.e all script/template code is wrapped within firsts 80 columns (or something like that) so a code written as:

> - service: light.turn_off
        target:
          entity_id: >-
            {% set entities = [] %}
            {% set entities = entities + [dst_dimmer_1_entity_id if ((dst_dimmer_1_entity_id is defined) and (dst_dimmer_1_entity_id is not none)) else None] %}
            {% set entities = entities + [dst_dimmer_2_entity_id if ((dst_dimmer_2_entity_id is defined) and (dst_dimmer_2_entity_id is not none)) else None] %}
            {{ entities | unique | reject('eq', None) | list }}

is automatically re-formatted/wrapped as:

> - service: light.turn_off
        target:
          entity_id: >-
            {% set entities = [] %} {% set entities = entities +
            [dst_dimmer_1_entity_id if ((dst_dimmer_1_entity_id is defined) and
            (dst_dimmer_1_entity_id is not none)) else None] %} {% set entities
            = entities + [dst_dimmer_2_entity_id if ((dst_dimmer_2_entity_id is
            defined) and (dst_dimmer_2_entity_id is not none)) else None] %} {{
            entities | unique | reject('eq', None) | list }}

Original 3 lines of "set variables" +1 for output = 4 easy-to-read lines that are wrapped in 6 hard-to-read ones that I need to re-format again each time I want to edit it.

It's very frustrating when you have 300+ "normal" rows and most of them are wrapped to let the total count goes over 800 lines....

### Describe the behavior you expected

Not have code reformatting nor wrapping but respect my carriage returns and indentation as I saw last time before leave the page after do a Save.

### Steps to reproduce the issue

1. write a script/automation using more than 100 chars in a single line
2. save it
3. reopen it

### What version of Home Assistant Core has the issue?

2023.11.3

**Comment by i00** [comment]
I hate the autoformatting too

**Comment by emandtf** [comment]
It would not be an issue if there is an Option to enable/disable this reformatting.....but there isn't 😅🤦‍♂️
