### ISSUE TITLE
Trekking fails when updating to a new version (The state is "always" at home).

### ISSUE THREAD

**Issue by Giuseppe-Palmucci** [home-assistant/frontend#18780]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In case of updating to a new version, device tracking does not work, resulting in it always being "at home"

### Describe the behavior you expected

Correct tracking depending on location (at/outside the home)

### Steps to reproduce the issue

1.update to a new version
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant OS

### What was the last working version of Home Assistant Core?

2023.11.3

### In which browser are you experiencing the issue with?

Microsoft EDGE

### Which operating system are you using to run this browser?

Versione 119.0.2151.72 (Build ufficiale) (64 bit)

### Additional information

I solved it this way:
1) uninstalling the Home Assistant Companion app on my phone;
2) restarting Home Assistant (Raspberry Pi 3 model B+);
3) reinstalling the Home Assistant Companion app on my phone.
But it becomes difficult to do this with every update

**Comment by karwosts** [comment]
I don't know what `trekking` is, but the state of entities are managed by the backend, so if this is related to an entity having the wrong state, please open an issue in home-assistant/core. This doesn't sound like a frontend issue.
