### ISSUE TITLE
Overflow in new number option for tile card

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#18818]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![IMG_3661](https://github.com/home-assistant/frontend/assets/33354141/91455804-dc7f-4fe8-90c5-0d998c301228)

### Describe the behavior you expected

No overflow 

also suggest different naming for the number option to Input or Mode, like in input_number documentation

### Steps to reproduce the issue

1. Add new tile 
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.11.0b0

**Comment by karwosts** [comment]
Can't reproduce, looks fine for me at all sizes:

![image](https://github.com/home-assistant/frontend/assets/32912880/37df7849-9caf-4cd2-83de-4f80fd7ea04e)

**Comment by Mariusthvdb** [comment]
sorry, was on mobile in a dark and quiet place when i posted...

this was on mobile, iOS app, hence the big image. Just checked and it's still there, even after the day theme hit.

**Comment by piitaya** [comment]
Looks like an overflow issue. I tested on my iPhone and I can not reproduce either. Which iOS version do you have?

**Comment by Mariusthvdb** [comment]
lets close, and if necessary, I can always re-open...


suppose it was a cache thing, as changing the themes no longer makes the editor overflow
thanks for the quick response
