### ISSUE TITLE
Tap Action for the Tile Card on iOS Doesn't Work (2023.12.0b0)

### ISSUE THREAD

**Issue by taljishi** [home-assistant/frontend#18823]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When taping on the tile card on the iOS app, the "Tap action" doesn't work. The "Icon tap action" works just fine.

### Describe the behavior you expected

After updating the beta version (2023.12.0b0), the tile card "Tap action" doesn't work. I usually set the "Tap action" to More info, however, nothing shows up. Even when I set it to Toggle, it doesn't work.

Other than being on the beta version 2023.12.0b0, the iOS app Version is 2023.7 (2023.471) which is also beta.

On the web browser it work as expected.

### Steps to reproduce the issue

1. I tap the tile card (Tap Action) and not Icon tap action.
2. More info or toggle do not work

### What version of Home Assistant Core has the issue?

2023.12.0b0

### What was the last working version of Home Assistant Core?

2023.11.2

**Comment by piitaya** [comment]
Can you share your card config? I can not reproduce. Also, can you restart Home Assistant in safe mode and try again?

**Comment by taljishi** [comment]
> Can you share your card config? I can not reproduce. Also, can you restart Home Assistant in safe mode and try again?

When restarting in safe mode, it works fine.

This is the card config as requested. Actions are set to default 
```
type: tile
entity: light.tv_room_spot_lights
name: Spot Lights
```

**Comment by taljishi** [comment]
Also, now after restarting Home Assistant in normal mode, I get the same issue when using the web browser (Firefox: Version 120.0 64-bit).

**Comment by piitaya** [comment]
So you should have a custom card that breaks this behavior. You can try removing/reinstalling your custom cards one by one to find which one causes the issue.

**Comment by taljishi** [comment]
> So you should have a custom card that breaks this behavior. You can try removing/reinstalling your custom cards one by one to find which one causes the issue.

Good call! It appears that Mushroom Themes is causing this issue. Thanks 🙏

**Comment by piitaya** [comment]
Ok I will look at this. I'll close this issue as it's not a frontend issue but a custom card issue.

**Comment by taljishi** [comment]
Specifically Mushroom Shadow and Mushroom Square Shadow
