### ISSUE TITLE
No way to log in once logged out.

### ISSUE THREAD

**Issue by Darrenh159** [home-assistant/frontend#18846]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After upgradinging to 2023.12.0b0 and logging out I am unable to log back in.  It does not give me option to select a user account like in the release notes, nor the option to enter a username.

### Describe the behavior you expected

to be able to click on a usernname, or enter a login.

### Steps to reproduce the issue

1. Upgrade to 12.0b0
2. Log out
3. try to log back in
...

### What version of Home Assistant Core has the issue?

2023.12.0b0

### What was the last working version of Home Assistant Core?

2023.11.3

### In which browser are you experiencing the issue with?

Chrome Version 119.0.6045.159

### Which operating system are you using to run this browser?

Big Sur 11.6.5

**Comment by karwosts** [comment]
This is fixed in beta .1, which I think just released, or is currently in the process.
