### ISSUE TITLE
Moon integration - wrong translation to German of “waning_gibbous” as “Drittes Viertel”

### ISSUE THREAD

**Issue by gupi** [home-assistant/frontend#18856]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

 wrong translation to German of “waning_gibbous” as “Drittes Viertel”

### Describe the behavior you expected

last quarter should be translated this way and “waning_gibbous” should become “abnehmender Mond”

### Steps to reproduce the issue

1. Set the language to German
2. use an entity card with the entity sensor.moon.phase
3.
...

### What version of Home Assistant Core has the issue?

2023.11.3

### In which browser are you experiencing the issue with?

Google Chrome Version 119.0.6045.160 (Offizieller Build) (64-Bit)

### Which operating system are you using to run this browser?

windows 11

### State of relevant entities

```txt
waning_gibbous
```

### Problem-relevant frontend configuration

```yaml
type: entity
entity: sensor.moon_phase
name: Mond
```

### Additional information

same behaviour with firefox browser 120.0 (64bit)

**Comment by karwosts** [comment]
Translations are not tracked as github issues. If you want to submit a correction, please review the guide for contributing translations. 

https://developers.home-assistant.io/docs/translations/
