### ISSUE TITLE
New dashboards do not have the title of dashboard in config

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#18850]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating a new dashboard, you can configure a title, icon and URL. 

![CleanShot 2023-12-01 at 00 09 19](https://github.com/home-assistant/frontend/assets/1444314/ff6e9192-9a14-4fa9-934b-1b94ecb031f2)

When I look at the generated config, the title is not stored in the dashboard config. If you started from scratch, it contains the following:

```yaml
views:
  - title: Home
```

### Describe the behavior you expected

I would expect the title of the dashboard to be stored in the config, since I just gave it a name. If I set the title to <my dashboard>, I would expect to see that.

```
title: <my dashboard>
views:
  - title: Home
```

### Steps to reproduce the issue

1. Go to dashboard config
2. Add new dashboard
3. Start from scratch
4. Give it a name and click create
5. Go to dashboard -> the toolbar is empty.
6. Edit config -> no title set

### What version of Home Assistant Core has the issue?

core-2023.11.4

### What was the last working version of Home Assistant Core?

Don't know

### In which browser are you experiencing the issue with?

Arc

### Which operating system are you using to run this browser?

MacOS

**Comment by piitaya** [comment]
These options are not part of the dashboard configuration.

In red : title from the dashboard config  (stored in `lovelace` file or yaml file). It will be the title of the dashboard if you have only one view.
in blue : title from the dashboard options (stored in `lovelace_dashboards` file). It will be the title on the sidebar.

![CleanShot 2023-12-04 at 09 30 08](https://github.com/home-assistant/frontend/assets/5878303/ea4a9961-906b-42ad-a6e0-ef46d573a432)

IMO, we should drop the name from the `config` and keep it in `lovelace_dashboards`.

**Comment by balloob** [comment]
Right, but since we already create a view named "Home", why wouldn't we also set the title of the whole dashboard to match the sidebar name when you start from scratch?

**Comment by qrockz** [comment]
> These options are not part of the dashboard configuration.
> 
> In red : title from the dashboard config (stored in `lovelace` file or yaml file). It will be the title of the dashboard if you have only one view. in blue : title from the dashboard options (stored in `lovelace_dashboards` file). It will be the title on the sidebar.
> 
> ![CleanShot 2023-12-04 at 09 30 08](https://private-user-images.githubusercontent.com/5878303/287635638-ea4a9961-906b-42ad-a6e0-ef46d573a432.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjIzMTAsIm5iZiI6MTcxNTgyMjAxMCwicGF0aCI6Ii81ODc4MzAzLzI4NzYzNTYzOC1lYTRhOTk2MS05MDZiLTQyYWQtYTZlMC1lZjQ2ZDU3M2E0MzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTZUMDExMzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDdiNGRhNGY0MGNjYzkxYWIzODA5YmVmN2QxZTVhZjE0M2I1MjIwYjFlOWZmMzZlMDI1YzhlMmNmMjQ5ODY4ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hI2Y4eV_NoEMnXCXZGLDLVAA-Jg77i6n78AYFsfi0Mg)
> 
> Also, what you describe is the name of the view, not the name of the dashboard.
> 
> We discussed in a meeting about renaming the title from the dashboard config to something like "Sidebar title" or "siderbar label"

Whats the point of having different titles (sidebar, dashboard title)?
Whats the point of hiding the title when there are multiple views?

**Comment by ashe0047** [comment]
I really think the sidebar name should be linked to the Dashboard title itself. Its pointless to separate them

**Comment by piitaya** [comment]
It was a legacy thing. The `title` in config was introduced when we have only one dashboard. Now, with multiple dashboards, it doesn't make sense. I open a PR the remove the title in lovelace config to use only the one for sidebar.
