### ISSUE TITLE
Energy Usage Graph Render Bug

### ISSUE THREAD

**Issue by Esprit1st** [home-assistant/frontend#18896]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Energy Usage Graph renders the blue graph (MainsFromGrid) negative if the preceeding bar consists of MainsFromGrid and consumed solar. It doesn't seem matter if that wrongly rendered graph has a MainsToGrid component or not. This error is consistant through my whole statistics of several months and seems to happen only in the mentioned scenario of the mentioned preceeding bar graph. See attached screenshot at the 10am and 2pm bar.
![Screenshot 2023-12-04 at 12-34-42 Energy – Home Assistant](https://github.com/home-assistant/frontend/assets/39107090/8f25d6d3-72c7-4ba4-8954-ec93acae0e3a)

It renders correctly if the preceeding bar is only MainsFromGrid or MainsFromGrid plus MainsToGrid as seen in second screenshot. (see 7am 3pm)
![Screenshot 2023-12-04 at 12-42-08 Energy – Home Assistant](https://github.com/home-assistant/frontend/assets/39107090/bb5d2586-c3b6-47aa-902a-d964c92f2b78)

### Describe the behavior you expected

It should render into the positive.

### Steps to reproduce the issue

1. System with MainsFromGrid and MainsToGrid (solar) setup. (not sure about different setups since I can't test)
2. Go to Energy Dashboard and go to a period that has MainsFromGrid & ConsumedSolar followed by a period that has MainsFromGrid, MainsToGrid & Consumed Solar

### What version of Home Assistant Core has the issue?

2023.11.2

## System Information

version | core-2023.11.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.21-v8+
arch | aarch64
timezone | America/Denver
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1420
Downloaded Repositories | 12
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 5
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 30, 2023 at 22:11
-- | --
current_recorder_run | December 2, 2023 at 18:58
estimated_db_size | 109.40 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by karwosts** [comment]
I'm skeptical this is a rendering issue versus just an issue with your source data, but if you want to confirm, I would do the following.

Enable `Developer_tools -> (3 dots overflow menu) -> Debug Tools -> Debug Connection` setting. 

Open browser developer tools, go to the console. Clear the logs. Refresh the page, and navigate to a day that shows this problem. In the logs you will see one or more `Received` messages that contain the statistics data for your energy panel. Copy this object, and upload it somewhere to review. 

There may be one or more of these objects, look for the one that contains the statistics that make up your energy graph.

Example: 
![image](https://github.com/home-assistant/frontend/assets/32912880/189c62ae-8814-4a41-9ea1-ad2fabced34d)

**Comment by Esprit1st** [comment]
I found the Debug Connection setting and enabled it, but I have a hard time finding the console / clear logs that you are talking about. Sorry about that.

**Comment by Esprit1st** [comment]
OK, got it. I thought it was a Home Assistant page.
Yeah, you are right. It is in the data, the question is why and how ...

![Received message](https://lh3.googleusercontent.com/pw/ADCreHc8RhsUfiaSvhKeT8m3lFF_muE0yGR9tc9OO6gg2i0bkf-38CpTisNQZEaR4U7WTRiKtYyUutE51PHHnEOvE-fLbsyg41RJhsXts_Uj7njZFbKxN2d4w1Y-VOM8MWKelPHp39-SDENIKWTtKA46CXNU3A=w984-h1142-s-no?authuser=0)
