### ISSUE TITLE
 High accuracy mode is on always, no working properly

### ISSUE THREAD

**Issue by DanielSzym11** [home-assistant/frontend#18898]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

 High accuracy mode is always in trybe on after start , can't go do off state if BL i disconect.
and 
 Not working properly funkcion on  High accuracy mode , if option enter to zone and connect BL is on.

### Describe the behavior you expected

High accuracy mode  go down if I disconnect BL. Properly start High accuracy mode if I have connect to BL and enter to zone.

### Steps to reproduce the issue

1.?
2.?
3./
...

### What version of Home Assistant Core has the issue?

HAOS and Mobile HA 

### What was the last working version of Home Assistant Core?

?

### In which browser are you experiencing the issue with?

Mozilla FF

### Which operating system are you using to run this browser?

server wind 10 and Virtual box for HA, and Android on mobile phone , Nabu Casa for conection serwer and mobilephone

### State of relevant entities

```txt
.
```

### Problem-relevant frontend configuration

```yaml
.
```

### Javascript errors shown in your browser console/inspector

```txt
?
```

### Additional information

?

**Comment by piitaya** [comment]
Your issue doesn't seem to be related with Home Assistant front-end. I will closed this issue as there is not step to reproduce it. You can re-open another with more details, screenshots and step to reproduce so we can investigate on it.

**Comment by DanielSzym11** [comment]
The problem is in the HA mobile application interface.

czw., 7 gru 2023 o 14:59 Paul Bottein ***@***.***> napisał(a):
