### ISSUE TITLE
Local To-Do List card not showing items when Casting

### ISSUE THREAD

**Issue by plasma2002** [home-assistant/frontend#18899]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using the standard card, of type todo-list, the list properly shows the individual to-do items when viewing the card in a web browser. But when casting the dashboard to a Google Nest Hub, the To-Do List card shows up with no items listed.
The card only shows the list title, and a row for entering a new list item (which does not work, since no keyboard support on device)

### Describe the behavior you expected

Expected behavior would be to show the To-Do list card with all the list items already entered on the Google Nest Hub. Clicking the items' check boxes should complete the item.

### Steps to reproduce the issue

1. Create a blank dashboard
2. Create a local To-Do list. Fill in some items
3. Put a card of type todo-list, and entity todo.yourListName
4. Cast the new dashboard to a cast device such as a Google Nest Hub. (Unknown if the issue exists on Chromecasts as well)

### What version of Home Assistant Core has the issue?

2023.11.3

### In which browser are you experiencing the issue with?

Google Nest Hub cast viewer

### Which operating system are you using to run this browser?

Google Nest Hub proprietary 

### State of relevant entities

```txt
todo.test_list
  State: 4
  friendly_name: Test list
  supported_features: 15
```

### Problem-relevant frontend configuration

```yaml
views:
  - title: Home
    cards:
      - type: todo-list
        entity: todo.test_list
        title: Things To Do
```

### Additional information

![blankGoog](https://github.com/home-assistant/frontend/assets/727979/bb2f8795-ca95-44f4-a819-66976d49b317)

**Comment by piitaya** [comment]
![IMG_2839](https://github.com/home-assistant/frontend/assets/5878303/a6838418-b566-460d-9a35-f43a66ade1a4)

No issue on my side (Nest Hub 2). I can check and clear completed items from the screen.

**Comment by plasma2002** [comment]
> No issue on my side (Nest Hub 2). I can check and clear completed items from the screen.

Oh, nice. That at least gives me some hope then.

I wonder how I can poke about this some more to get more details of why I'm not getting any items. 
Would casted media be put into a separate logfile maybe, etc

**Comment by plasma2002** [comment]
This issue is no longer happening as of version 2023.12.2
