### ISSUE TITLE
Missing text in translation - restart

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#18895]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing words in translation (screenshot attached)

![Snag_114339b7](https://github.com/home-assistant/frontend/assets/61636045/c907b461-1d5f-411e-b8bf-e5b56fb6af04)

### Describe the behavior you expected

Please add missind word to translation

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.11.3

### What was the last working version of Home Assistant Core?

not relevant

**Comment by karwosts** [comment]
This string is from home-assistant/core. Please open an issue there.
