### ISSUE TITLE
Missing text in translation - log in

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#18892]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing in translation (screenshot attached)

![1701698938048](https://github.com/home-assistant/frontend/assets/61636045/3477708a-89e5-4e26-85aa-1735f5bb7051)

### Describe the behavior you expected

Please add missing text to translation

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.11.3

### What was the last working version of Home Assistant Core?

not relevant

**Comment by frenck** [comment]
This is a persistent notification and is currently impossible to translate by the frontend.

../Frenck
