### ISSUE TITLE
New thermostat card design > Issues with scrolling 

### ISSUE THREAD

**Issue by KNXBroker** [home-assistant/frontend#18906]
### Checklist

- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have updated to the latest available Home Assistant version.

### Describe the issue you are experiencing

The new thermostat design is amazing, however it is not scrolling friendly. During beta testing I unintentionally changed often the temperature setting. This morning my corridor was a sauna for example :-) Discord discussion showed that this was noticed already by more people. I have tested this on an old installation as well, the old card was not that sensitive.

Potential solutions?! Some ideas....
-  Allow change of temperature only by clicking  and moving the dot
- Take temperature change as valid only if the finger stops at a certain position on the circle for a short time
- Evaluating the direction of swiping.

### Describe the behavior you expected

Srolling should have priority

### Steps to reproduce the issue

1. Create one or even more thermostat cards
2. Try to scroll on mobile phone
3.
...

### What version of Home Assistant Core has the issue?

2023.12.0b2

### In which browser are you experiencing the issue with?

Chrome Version 119.0.6045.160

### Which operating system are you using to run this browser?

Android 14

**Comment by piitaya** [comment]
The current slider has a touch zone to better handle touch interaction (I colored it in yellow on this screenshot).

![CleanShot 2023-12-05 at 09 25 02](https://github.com/home-assistant/frontend/assets/5878303/1ee620ef-1f1a-4926-b539-aa53b7457a13)

I created a PR to reduce it when the slider is used on a card : https://github.com/home-assistant/frontend/pull/18908. I should reduce the sensitivity.

![CleanShot 2023-12-05 at 09 25 13](https://github.com/home-assistant/frontend/assets/5878303/b6944ab2-6784-4969-a381-bf2b726cfaa5)

**Comment by Japing** [comment]
piitaya, add please this features to new humidifier card: https://github.com/home-assistant/frontend/discussions/18884

**Comment by piitaya** [comment]
@Japing Please don't ping dev on other issue. Your feature was only posted one day ago.

**Comment by Japing** [comment]
@piitaya Sorry, I wanted it to be in the new version with new humidifier card.

**Comment by Mariusthvdb** [comment]
would a confirmation. help here? on several of these sensitive settings I always prefer to have a second interaction to prevent accidental change

in regular cards we can do so with custom card additions, but on the thermostat we cant (I think). a core option would be grand. Id gladly write up a FR if you feel that would be a good idea

**Comment by tjorim** [comment]
I think it's best if the temperature adjustment does not happen when the users is dragging his finger outside of the thermostat card. I don't think the issue is the touch zone is too big but even if accidentally grabbing it, you can't just let go without cancelling the change.

**Comment by Mariusthvdb** [comment]
> I don't think a confirmation will be nice in term of UX. We will have 2 steps to change the temperature. You're better to add a button, tile, entity card and then change the temperature in the more info (it's 2 steps too).

though that is a creative work around, and indeed I have some of these (simply because of testing out various card for the climate entity) I dont particularly like the fact we get the more-info, that looks almost completely like the thermostat card itself. It might be a bit more detailed, but it does not change the fact we have twice the almost identical interface.

Also, Id much prefer a "are you sure?" on an action in the current thermostat, than being force to use one of the others and make for a less attractive front-end in the Dashboard.

Lastly, as this would be optional, I cant see the objection. If people dont want it, they doing set the conformation field (default). If they'd like a guard, just set
`confirmation: true`

and get the popup to confirm

**Comment by tjorim** [comment]
While it's less sensitive in 2023.12.0b4 (frontend version 20231205.0), it still happens sometimes. I just want to scroll down my page but accidentally grab the slider. I guess I could be more careful around the thermostat cards and avoid the 'danger zones'.
https://github.com/home-assistant/frontend/assets/1294876/0ab97d38-6771-4798-819e-8b9baa998cb9

**Comment by KNXBroker** [comment]
Same on my side, better but not satisfying.... My personal opinion:

- tested with the old style again, it was almost impossible to change anything
- taking care about where to touch while scrolling is not really nice
- adding confirmation is neither an option (scrolling would be disturbed by confirmations all the time)
- I think same UX change is required, worst case for all the elements...

**Comment by piitaya** [comment]
> Same on my side, better but not satisfying.... My personal opinion:
> 
> * tested with the old style again, it was almost impossible to change anything
> * taking care about where to touch while scrolling is not really nice
> * adding confirmation is neither an option (scrolling would be disturbed by confirmations all the time)
> * I think some UX change is required, worst case for all the elements...

The problem with the old design is that, it's very difficult to change the temperature using touch gesture... 😢 I don't think there is a good solution if we want to keep that UX.

**Comment by Mariusthvdb** [comment]
correct.
Heating replaces the Target , which then is no longer displayed verbally.
Which in itself is another odd change in the layout of the card. as if there is no longer a 'Target' (not translated?)

it's just that not showing a flame when heating portably unique in the industry.....

**Comment by KNXBroker** [comment]
Just an idea in addition: taking a new set point only as valid if the finger stops in the circle (or next to the circle).  Reacting all over the screen can make sense for a slider, but not sure if it make sense for a circle. Best regards

**Comment by piitaya** [comment]
@KNXBroker Even if we do this, it will be annoying because the screen will not scroll.

**Comment by amacdonel** [comment]
Maybe a little late to the conversation, I just installed a new thermostat and found that the climate card had this unsafe behaviour that allowed the set point to change without much effort. I like the proposal of making only the dot, or a larger area around it (not the whole slider) sensitive to the touch after the 60ms delay.

**Comment by SaberShip** [comment]
Just weighing in here.  I personally agree with @amacdonel. After installing 12.4 release recently my family and I have also noticed how easy it is to accidentally move the slider on mobile devices. 
 
I see a couple options:
1. The simple sledge hammer solution would seem to be an optional config to disable interaction with the slider arc as a whole, only relying on the +/- buttons and the arc would just be a visual.
2. Modify the slider arc so that valid input is only registered near the handle dot.  (Not sure of the use case of tapping a random location of the arc far from the handle without knowing the temperature value there anyway)

**Comment by KNXBroker** [comment]
I'm wondering a little bit about the amount of people complaining, not many, neither in the forum nor here.

Graping the dot would reduce the risk, but not solve it, however I agree, not sure if it is really necessary to make the complete arc tap sensitive. By instinct you are always graping the dot.

**Comment by metost** [comment]
9 out 10 times I'm changing the temperature while scrolling, defenetly it's not OK at the moment.

**Comment by svelho-personal** [comment]
It would be interesting to have an option that sets the selection in the arc:
- arc-behavior: read-only  -> can't do any changes using the arc; + and - buttons are used instead
- arc-behavior: dot -> can update temperature only by dragging the ball (default imo)
- arc-behavior: full -> touching any point of the arc will set the temperature

Likely names can be improved :), but just the idea

**Comment by piitaya** [comment]
We discussed that point with the UX team. 
Only the dot will be draggable on touch devices for the thermostat card and humidifier card to avoid interaction when scrolling. For mouse interaction, the full arc stays interactive. 
Here's the PR for that : https://github.com/home-assistant/frontend/pull/19423
