### ISSUE TITLE
Oddities/bugs in theme layout

### ISSUE THREAD

**Issue by Djelle** [home-assistant/frontend#18902]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On the Energy page there are “Back” and “Next” buttons.

“Next” is using var(–mdc-theme-primary) as background color. Which I believe is a text color. Though this could be intended, it makes it hard to make a new theme tho.
“Back” has no defined background color at all as far as I can see. And thus can’t be changed.
![HA_bad](https://github.com/home-assistant/frontend/assets/32912880/034d0e26-cf12-4a37-99e3-c1bec74cc0bb)

### Describe the behavior you expected

I expected it to have a background-color definition that can be changed from a theme.

### Steps to reproduce the issue

View page 2 to 6 of the Energy page. Showing the wizard for the first setup.

### What version of Home Assistant Core has the issue?

2023.11.3

### In which browser are you experiencing the issue with?

Both Chrome and Edge

### Which operating system are you using to run this browser?

Windows 10

### Additional information

Thanks for a wonderful product.

**Comment by ildar170975** [comment]
> Only the first image is relevant. Sry.

Why putting several pictures & then say "only 1st image is relevant"?
Same about https://github.com/home-assistant/frontend/issues/18903
