### ISSUE TITLE
Light-strip device icon has bad color definition on any card

### ISSUE THREAD

**Issue by Djelle** [home-assistant/frontend#18903]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On any card with a light-strip icon, the icon is baby-blue. Which seams to be hard-coded and thus can’t be changed by a new theme.
![HA_bad](https://github.com/home-assistant/frontend/assets/56372851/35329a03-46f8-49fa-a3c1-e333b1bf9fd8)
Only 2nd picture is relevant.

### Describe the behavior you expected

That it hase a color definition matching other similar icons.

### Steps to reproduce the issue

Add a card like Entity or Button with a light-strip entity, to a page.

### What version of Home Assistant Core has the issue?

2023.11.3

### In which browser are you experiencing the issue with?

Both Chrome and Edge

### Which operating system are you using to run this browser?

Windows 10

### Additional information

Keep up the good work.

**Comment by karwosts** [comment]
Light entities are generally colored by the color of the light they are emitting. So if you have a cool light bulb, that color might be that bluish color you describe. If you have a warm light bulb, it will be orangish. Or if its an RGB bulb it will be whatever color that is.

**Comment by Djelle** [comment]
That makes sense. I didn't think of that. Now I feel a little stupid. Sry to jump the gun :)
