### ISSUE TITLE
TOTP setup message is truncated

### ISSUE THREAD

**Issue by strugee** [home-assistant/frontend#18918]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The TOTP setup success message is truncated.

### Describe the behavior you expected

The dialog box says "Success! Setup done for \<my name>" or something like that

### Steps to reproduce the issue

1. Visit https://\<HA base URL>/profile
2. Scroll down to the MFA modules section
3. Click "Enable" next to TOTP
4. Go through the setup flow
5. Notice the success message is borked

### What version of Home Assistant Core has the issue?

core-2023.11.3

### In which browser are you experiencing the issue with?

Firefox Nightly 122.0a1 built 2023-12-04

### Which operating system are you using to run this browser?

macOS Sonoma 14.1.2

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
N/A
```

### Javascript errors shown in your browser console/inspector

```txt
Nothing in the JS console, and only 200s in the Network tab of devtools.
```

### Additional information

Screenshot:

<img width="431" alt="Screenshot 2023-12-05 at 17 09 04" src="https://github.com/home-assistant/frontend/assets/911174/af245a89-a7c2-44a4-a566-8a0e9e10ea9c">

Also reproducible on the same OS, Google Chrome 119.0.6045.199 (which, note, is _technically_ not the latest version of Chrome although it [basically is](https://chromereleases.googleblog.com/2023/11/early-stable-update-for-desktop.html)).

**Comment by codyc1515** [comment]
Yep, just reproduced this easily on Edge.

![image](https://github.com/home-assistant/frontend/assets/50791984/a9244358-dda5-4115-bfbd-473e217e5e70)

**Comment by KTibow** [comment]
Just because I'm in the blame doesn't mean I'm the one to blame - this is the same behavior as before. The issue must lie elsewhere.
![image](https://github.com/home-assistant/frontend/assets/10727862/fff556df-047a-4517-ab00-16ab35757307)
