### ISSUE TITLE
Displayed keyboard lacking characters on Safari or HA App

### ISSUE THREAD

**Issue by MHKnowles** [home-assistant/frontend#18915]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I originally opened this call in the iOS tracker and was told it was a a front-end issue and to open the issue here as it fails both in the app and in Safari:

When on an iPhone or iPad, trying to edit a numerical field within either an automation or a card (the problem probably extends further than this) then the on-screen keyboard that is opened does not have enough functionality to complete the field.  Specifically, for me it's lacking the minus key so I can't edit fields which require negative values inputting.  There's also no way of changing the keyboard.
Attached you'll find 2 examples of this happening - you only have 0-9 and a full-stop possible, yet the extended keyboard should be opened (I believe this is a function of the field the UI is focused on).
![pic1](https://github.com/home-assistant/frontend/assets/107808973/67fab97c-c553-4277-a6ba-9df76de736c4)
![pic2](https://github.com/home-assistant/frontend/assets/107808973/3b51aef5-7acd-4d7a-a975-03bf809c6681)

### Describe the behavior you expected

What *should* happen is that the extended keyboard with more alphanumeric keys (and +- etc) should open when you tap on a numeric field instead of the keyboard given.

### Steps to reproduce the issue

1. Open HA in Safari or in the App on iOS
2. Edit an automation or a card, probably easiest to attempt to edit or add a gauge card and try to enter a figure for minimum, maximum, severity, etc
3. Note the keyboard that is opened.  It is likely to be the same as my screenshots.
...

### What version of Home Assistant Core has the issue?

2023.11.3

### In which browser are you experiencing the issue with?

Safari on iOS (latest version), also HA App from App store (unsure but it probably uses the passthrough browser)

### Which operating system are you using to run this browser?

iOS 17.1.2 on an iPhone 15 Pro (latest version but it probably occurs elsewhere)

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
Not sure how I would go about this.
```

### Javascript errors shown in your browser console/inspector

```txt
None.
```

**Comment by codyc1515** [comment]
This is how the iOS keyboard works. The only alternative to my knowledge would be to just make it a free text keyboard which wouldn't work for numeric entities if someone entered letters.

**Comment by codyc1515** [comment]
This is an [iOS](https://github.com/home-assistant/iOS/issues) issue.

**Comment by MHKnowles** [comment]
Please fight it out amongst yourselves because I originally logged it as an iOS issue and was told that iOS inherited this from web and that I should relog it as a front end issue.

On 8 Mar 2024, at 00:18, Cody C ***@***.***> wrote:

﻿

This is an iOS<https://github.com/home-assistant/iOS/issues> issue.

**Comment by codyc1515** [comment]
Where’s the iOS ticket? Only the app can make a custom keyboard show.

**Comment by MHKnowles** [comment]
The guy looking after the iOS section closed it saying it wasn’t something that was dictated by iOS but by the web.

On 8 Mar 2024, at 07:13, Cody C ***@***.***> wrote:

﻿

Where’s the iOS ticket? Only the app can make a custom keyboard show.

**Comment by MHKnowles** [comment]
Just to point out this is still an issue.
