### ISSUE TITLE
Energy dashboard not showing chartTooltip after adding new sensors

### ISSUE THREAD

**Issue by krzysztofsk** [home-assistant/frontend#18917]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I added new sensors for energy production and consumption. I froze old sensor with static value. When graph shows bars with only old sensor and bars with new sensor then one type of bar has no tooltip on hover.
<img width="891" alt="Zrzut ekranu 2023-12-5 o 21 19 40" src="https://github.com/home-assistant/frontend/assets/15669227/0af16d59-8dee-4e51-90ad-39990bc22907">
In this case I can see tooltip only for first 10 months and next two bars are not working.
When picking smaller period then I could see tooltips for new sensor bars, but bars with only old sensor was not working

### Describe the behavior you expected

Tooltip should always show on hover

### Steps to reproduce the issue

1. Add new sensors for grid consumption/production of energy
2. Show graph with data before and after the change
3. Hover over all bars to check if tooltip works

### What version of Home Assistant Core has the issue?

2023.11.3

### In which browser are you experiencing the issue with?

Google Chrome 119.0.6045.199

### Which operating system are you using to run this browser?

Ventura (13.6.2)

**Comment by karwosts** [comment]
I have a similar issue which is fixed by pending PR #19031, I can't guarantee its the same issue you have, but it may be fixed by that.

**Comment by karwosts** [comment]
Should be fixed.
