### ISSUE TITLE
Missing words in translation - for Development tools

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#18928]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing words in translation (in attached screenshots)

![Snag_1a478ba5](https://github.com/home-assistant/frontend/assets/61636045/576a85ab-e037-435b-a458-2569e10f47d9)

![Snag_1a487394](https://github.com/home-assistant/frontend/assets/61636045/8e3b178e-330b-40c0-8230-744f6dc0351f)

### Describe the behavior you expected

Please add missing words to lokalize

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.11.3

### What was the last working version of Home Assistant Core?

not relevant

**Comment by karwosts** [comment]
You already opened an issue for these earlier this month and they have already been fixed pending the december release.
