### ISSUE TITLE
Drop-down list goes below bottom of browser frame in Chrome

### ISSUE THREAD

**Issue by JollyRgrs** [home-assistant/frontend#18938]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In Chrome on both Windows 11 and Ubuntu (never logged into HA before on that box until testing now) the same issue happens. On W11, I tested Firefox and Edge and both of those operated as expected (list in frame and pops up vs down if not enough space)

This has been happening for a while and I just haven't had time to submit when I'm reminded of the issue until now. I would say at least 6 months or longer it has been happening.

![image](https://github.com/home-assistant/frontend/assets/42019632/2a9f4f5f-0c87-40e7-8a20-f1c67e449e68)

### Describe the behavior you expected

I expect to see the entire drop down so I can view the last item and select it

### Steps to reproduce the issue

1. Use Chrome
2. Open a drop down list (I use automation "choose entity" options as it will be nice and long)

### What version of Home Assistant Core has the issue?

2023.12.0

### In which browser are you experiencing the issue with?

Google Chrome 119.0.6045.202 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

**Comment by codyc1515** [comment]
This can also happen in the mobile app on iOS.

**Comment by codyc1515** [comment]
Current.

**Comment by JollyRgrs** [comment]
This issue no longer affects me (it has been a little while, so I am not exactly sure when it stopped being an issue).
