### ISSUE TITLE
Use keychain on login screen

### ISSUE THREAD

**Issue by CFenner** [home-assistant/frontend#18940]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When logging into HA with the new login screen, I’m missing the ability to select stored credentials from the iOS key chain.
I’m unsure if this worked before (I think so) or if this should be a new feature request.

![IMG_4069](https://github.com/home-assistant/frontend/assets/9592452/8ab2e954-e639-4551-9b93-ad12d30a407d)

### Describe the behavior you expected

I would like to be able to open the keychain and select credentials or get suggestions of stored credentials for the url.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023-12

### Which operating system are you using to run this browser?

iOS 17.1.2

**Comment by CFenner** [comment]
Just tested this with Safari in a MacBook, there it works.

<img width="460" alt="Bildschirmfoto 2023-12-07 um 12 14 17" src="https://github.com/home-assistant/frontend/assets/9592452/a7a77896-8d9d-4957-9916-673eed6dbf87">

**Comment by codyc1515** [comment]
Yes it works in Safari on macOS but not on iOS I found.

**Comment by codyc1515** [comment]
Current.
