### ISSUE TITLE
Tap Action on Tile Card stopped working in 2023.12.0

### ISSUE THREAD

**Issue by sanctas** [home-assistant/frontend#18948]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have multiple tile cards set up in my dashboard. In previous versions of Home Assistant, I was able to set the Tap Action to “Navigate” and when I pressed on them I would be able to navigate to a specific dashboard screen. I can still set this, but since the update, tapping no longer does anything. The “tap” animation no longer plays when I tap it, however I can still click on the icon itself to open the more info screen. If I edit the card, I am able to successfully tap the tile in the editor preview, which will successfully navigate as well as play the animation. 

### Describe the behavior you expected

Tap actions for navigate no longer work.

### Steps to reproduce the issue

1. Create a tile card
2. Add a tap action for Navigate
3. Set a URL to navigate to
4. Save the tile card
5. Tap the card.

### What version of Home Assistant Core has the issue?

2023.12.0

### What was the last working version of Home Assistant Core?

2023.11.3

### In which browser are you experiencing the issue with?

Home Assistant iOS App (up-to-date), Google Chrome for iOS (up-to-date), and Safari for iOS.

### Which operating system are you using to run this browser?

iOS 17.1

**Comment by Kvasenok** [comment]
I have the exact same behavior. Basically half of Tile card's functionality doesn't work.

**Comment by Intecpsp** [comment]
@piitaya this is still an issue after updating to 2023.12.1

**Comment by piitaya** [comment]
Can you confirm it's fixed with 2023.12.1 ?

**Comment by sanctas** [comment]
> Can you confirm it's fixed with 2023.12.1 ? 

Yes, it is working now. I appreciate the quick work fixing this.
