### ISSUE TITLE
Deep linked to ToDo list always defaults to last opened To Do list and not the entity ID in the link

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/frontend#18947]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The user is taken to the last selected To Do entity  instead of the URL that was copied

### Describe the behavior you expected

the user should be taken to the copied entity ID and not hte last selected entity ID

### Steps to reproduce the issue

1. Open HA
2. Navigate to To Do
3. Select the 2nd or 3rd item
4. Copy URL
5. Select the 1st item
6. Open new browser tab
7. Paste URL

observe how the URL is shown the first item instead of the one they copied

### What version of Home Assistant Core has the issue?

2023.12.0

### What was the last working version of Home Assistant Core?

n/a

### In which browser are you experiencing the issue with?

119

### Which operating system are you using to run this browser?

Windows and Android

### Additional information

Reproducible using Android shortcut feature as well as on desktop, also reported by a user

https://community.home-assistant.io/t/deeplink-to-specific-shopping-list/651723

**Comment by dshokouhi** [comment]
possible duplicate of https://github.com/home-assistant/core/issues/105159 however not sure which location is valid, will let the team decide :)

**Comment by pdsccode** [comment]
There is also a core integration issue for this:
https://github.com/home-assistant/core/issues/105159
Not sure if it is resulting from core or Fronten.

**Comment by silamon** [comment]
It's a frontend issue. Feel free to close the core issue.
