### ISSUE TITLE
Thermostat Card - Removed ability to set heat/cool 

### ISSUE THREAD

**Issue by gnvdude** [home-assistant/frontend#18950]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

old card displayed cool vs heat and ability to set mode
new card removed ability to change between cool and heat modes

![image](https://github.com/home-assistant/frontend/assets/9097927/4cb2fb9f-0728-4d01-966a-114887b9b184)

### Describe the behavior you expected

that the cool and heat symbols would be there to control from single location 

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.12.0

### What was the last working version of Home Assistant Core?

2023.11

### In which browser are you experiencing the issue with?

iphone app and browser chrome

### Which operating system are you using to run this browser?

Windows 10

**Comment by tdejneka** [comment]
In the Release Notes for version 2023.12.0, refer to the [section that introduces the new Climate card](https://www.home-assistant.io/blog/2023/12/06/release-202312/#new-design-for-the-thermostat-card).

The second screenshot shows how to add features to the card.

![Screenshot_20231207-082659~2](https://github.com/home-assistant/frontend/assets/44732909/8738d785-17d7-4dd3-a5a1-b89d544231a8)

**Comment by codyc1515** [comment]
Pleased to see this reverted. It was a very clunky interface on mobile.

**Comment by piitaya** [comment]
New hvac mode controls are optional when creating manual dashboard. If you use the default dashboard, it will be included automatically.

**Comment by karwosts** [comment]
Believe this is now resolved, don't think there's any action left to take here.
