### ISSUE TITLE
Missing text in translation - notifications

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#18965]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Found missing words in translation.

![Screenshot](https://github.com/home-assistant/frontend/assets/61636045/a0d339a2-fba0-4885-9eb2-a2ae2ab7226a)

### Describe the behavior you expected

Please add missing words to translation.
Thank you.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.12.0

### What was the last working version of Home Assistant Core?

not relevant

**Comment by karwosts** [comment]
These strings are not from the frontend. Try core.
