### ISSUE TITLE
Missing text in translation - system status

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#18966]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Found missing word in translation (you can see in attached picture)

![Snag_240f9e40](https://github.com/home-assistant/frontend/assets/61636045/85ea0800-3f0b-4e4e-9d50-37da7ca02e19)

### Describe the behavior you expected

Please add missing words to translation.
Thank you.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.12.0

### What was the last working version of Home Assistant Core?

not relevant

**Comment by karwosts** [comment]
HACS is not part of home assistant and not tracked here. Maybe you can open in their repo.
