### ISSUE TITLE
Thermostat card font much too big

### ISSUE THREAD

**Issue by ic-dev21** [home-assistant/frontend#18977]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Font is now much too large making identification impossible at a glance. 

![IMG_0938](https://github.com/home-assistant/frontend/assets/108159253/d3de0477-40a5-4403-a37d-53e2ec8dfd43)

### Describe the behavior you expected

In the previous UI the complete name was visible. 

### Steps to reproduce the issue

Update to 2023.12.0

### What version of Home Assistant Core has the issue?

2023.12.0

### What was the last working version of Home Assistant Core?

2023.11.3

### In which browser are you experiencing the issue with?

Ios app

### Which operating system are you using to run this browser?

Ios 17

**Comment by greg520820** [comment]
Yes, I totally agree. In fact the entire card does not scale/size well.  On my tablet I had 3 thermostat cards in a horizontal card and all functions were readable and usable.  In the same space with just two new thermostat cards and most of the functions and information is hidden/gone.  I wish the new card would automatically scale.  

For a work-around on the title you can use card-mod:
``
card_mod:
      style:
        .: |
          .title {
          font-size: 15px !important; 
          }
``
