### ISSUE TITLE
Login screen: a user's avatar is not displayed

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#18978]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This user has an associated `person` entity with `entity_picture` defined:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/f1285ce5-e5db-4526-ad12-6b8227405b34)

The user's photo is displayed in HA:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/4b72f656-44c2-4306-89b1-eaf1150a2e30)

But in Login screen the photo is not displayed when logging in from the same LAN:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/0c352982-44fd-445b-8d41-e99b02f1c2f7)

P.S. I have not defined `auth_providers` option in configuration.yaml.

### Describe the behavior you expected

If a user has a photo - show it on a Login screen.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.12.0

### In which browser are you experiencing the issue with?

Chrome 119.0.6045.200

### Which operating system are you using to run this browser?

Win10x64

**Comment by karwosts** [comment]
As the new login screen has been killed, I don't believe this is relevant any further.

**Comment by ildar170975** [comment]
agreed
