### ISSUE TITLE
Update spinner appears broken in iOS Home Assistant since 2023.12

### ISSUE THREAD

**Issue by theheig** [home-assistant/frontend#18976]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When update is triggered from updates, the usual spinner animation is “broken.”  See video.

https://github.com/home-assistant/frontend/assets/1964829/9682c309-7864-4534-ae60-22994bf590e7

### Describe the behavior you expected

Usual circle spinner animation around component being updated.

### Steps to reproduce the issue

1. Locate updatable item in updates
2. Click into item and select update
3. Click out of dialog and observe spinner animation around item

### What version of Home Assistant Core has the issue?

core-2023.12

### What was the last working version of Home Assistant Core?

core-2023.11.3

### In which browser are you experiencing the issue with?

iOS Home Assistant

### Which operating system are you using to run this browser?

iOS 17.1.2

### Additional information

Let me know if this should be an issue in core.

**Comment by silamon** [comment]
It's an issue in the frontend. Most likely it's not everywhere broken, but just on a few places. If you come across more places, feel free to make an issue as well for each place.
