### ISSUE TITLE
Last empty scale division in Energy tab should be removed

### ISSUE THREAD

**Issue by Jordan87** [home-assistant/frontend#18985]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In energy tab on the end of each bar graph there is one empty division/scale, this looks like something missing in statistics. I think it would be nice to remove it and have clean look.
Day view
![image](https://github.com/home-assistant/frontend/assets/10414918/d58faabb-dd30-45a7-87e5-de87d8f01bb2)
Week view
![image](https://github.com/home-assistant/frontend/assets/10414918/5a27843e-60b8-47e8-973d-f1ad6ae8c66d)
Quarter view
![image](https://github.com/home-assistant/frontend/assets/10414918/9da1a982-16a7-440a-a956-337554327224)

All of the periods have that issue but ones with smaller number of samples is more visible.

### Describe the behavior you expected

All divisons of graph bar have some value.

### Steps to reproduce the issue

1. Collect energy, water or gas consumption in energy tab for at least one full period
2. Check bar graph

### What version of Home Assistant Core has the issue?

2023.12.1

### Which operating system are you using to run this browser?

Win 10 64 and Android app

**Comment by karwosts** [comment]
Looks like someone attempted this at one point, not sure if he's someing back to it or not:

#17390
