### ISSUE TITLE
Slider may miss a "state" part on a smaller viewport (incl. mobile clients)

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#18980]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Tested a slider in iOS Companion App (iOS 15.x, iPad Air 2, 1024x768):

2 columns: "State" is shown:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/b50ac20c-13b3-4a33-a732-47124ac747cf)

3 columns: "State" is not shown:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/7ef3e7d3-4878-4364-8c2b-978e49b5b301)

May be reproduced on a Windows desktop with a resized window (Win10x64 + Chrome, 704x497):

![изображение](https://github.com/home-assistant/frontend/assets/71872483/e28f5a43-9b7d-4ab7-a1e5-187a87251086)

Code Inspector shows `display: none` for the `.state` part:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/7d732115-5c3f-461d-876e-02d0d8da1941)

Managed to manually fix:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/95f0f480-3c37-4dd5-8f5b-194b9365ac39)

### Describe the behavior you expected

"State" part should be displayed.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.12.0

### In which browser are you experiencing the issue with?

Chrome 119.0.6045.200 

### Which operating system are you using to run this browser?

Win10x64

**Comment by silamon** [comment]
It's programmed that way to be not displayed if there's no space for it.

**Comment by ildar170975** [comment]
Having a possibility to see a value is more important than a possibility to move a knob with a finger. User may open a more-info window to move a knob if he experience problems with a knob. 
By using Code Inspector I demonstrated that a state can be shown with a slider, also I was able to move a knob. 
Please consider to show a state.
