### ISSUE TITLE
SkyConnect USB dongle, can't flash Zigbee+Thread firmware.

### ISSUE THREAD

**Issue by sblantipodi** [home-assistant/frontend#19009]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have received my SkyConnect USB dongle and it works well with Zigbee using zigbee2mqtt on docker.

I would like to add the "thread/matter" feature...
To do it I suppose that I need to change the firmware on my SkyConnect USB dongle.

When I try to do it here:
https://skyconnect.home-assistant.io/firmware-update/

it hangs on connecting:
![image](https://github.com/home-assistant/frontend/assets/4722227/90210df0-8122-4e21-90bd-fbb922e6fb76)

any idea?
Thanks!

### Describe the behavior you expected

be able to flash the thread+zigbee firmware

Using Chrome browser on Windows 11. 
I use the browser to successfully flash esp devices for other types of firmware.

When I click the "Update firmware" button, 
it asks me on which port connect, once clicked “Port 9” it shows the connecting loader and it hangs there…

**Comment by amoutiers** [comment]
Open your browser console, if it's like that, yes it is
https://github.com/darkxst/silabs-firmware-builder/issues/29

**Comment by darkxst** [comment]
Most probably that is the same issue. However you dont need the webflasher for SkyConnect for this. You can switch Skyconnect to the Multipan firmware from the HA hardware menu (which should not be affected by this bug)

**Comment by sblantipodi** [comment]
@darkxst that is only possible with HA OS, I'm using HA Container on Docker.

**Comment by darkxst** [comment]
yes true. puddly is working on a fix for this. should be resolved soon as that is merged.

**Comment by ildar170975** [comment]
How is this issue related to HA Frontend?

**Comment by darkxst** [comment]
Its not
https://github.com/NabuCasa/sl-web-tools/issues/11

**Comment by karwosts** [comment]
Closing as Off Topic.
