### ISSUE TITLE
Shopping list events user_id: null

### ISSUE THREAD

**Issue by Jonybat** [home-assistant/frontend#19001]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This is basically the same thing as https://github.com/home-assistant/frontend/issues/12308

When performing any action in a shopping list, the `user_id` is not sent along with the `shopping_list_updated` event.

I can replicate this in a fresh container

### Describe the behavior you expected

 `user_id` should be present in `shopping_list_updated` event

### Steps to reproduce the issue

1. Go to events tab in the Developer options.
2. Enter shopping_list_updated in to event type and click listen to events
3. In another tab, navigate to the shoping list and add/update/remove an item
4. Notice how the event fired has `user_id: null`

### What version of Home Assistant Core has the issue?

2023.12.1

### What was the last working version of Home Assistant Core?

Not exactly sure, but it worked fine a couple of months ago

### In which browser are you experiencing the issue with?

Multiple browsers, android app, ios app

### State of relevant entities

```txt
event_type: shopping_list_updated
data:
  action: add
  item:
    name: test
    id: cb0448f158cd462c88145f9cd3eeb3f8
    complete: false
origin: LOCAL
time_fired: "2023-12-10T21:17:10.941221+00:00"
context:
  id: 01HHASENWXENSCR7B5MAJN3AK6
  parent_id: null
  user_id: null
```

**Comment by karwosts** [comment]
I think you might want to open a home-assistant/core issue for this, as I don't think this is the responsibility of the frontend to handle this.

**Comment by Jonybat** [comment]
Alright, done, closing this then.
