### ISSUE TITLE
Markdown card only shows title on Samsung Family Hub

### ISSUE THREAD

**Issue by cyallater** [home-assistant/frontend#19000]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On a Samsung Family hub, only the title is shown of a Markdown card, but not the content. Content is shown correctly in other browsers/OS's and in the companion app. This is the case for markdown content as well as just plain text.

Fridge:
![IMG_2754](https://github.com/home-assistant/frontend/assets/43476478/7fa83ece-82c9-4ff4-98f5-ada36a98cf33)

Safari
<img width="943" alt="Screenshot 2023-12-10 at 20 08 00" src="https://github.com/home-assistant/frontend/assets/43476478/5b5c8a65-7036-4858-8d2d-90ec535591ac">

### Describe the behavior you expected

Expected to see the content on the fridge as well.

### Steps to reproduce the issue

1. Create dashboard with Markdown Card with title and content.
2. Load dashboard on Family Hub.
3. No content is visible
4.
...

### What version of Home Assistant Core has the issue?

2023.12.0

### In which browser are you experiencing the issue with?

unknown, version 8.0.27

### Which operating system are you using to run this browser?

TIZEN 6.0

**Comment by snairolf** [comment]
Same issue. This is reproducible with firefox 72.0.2

**Comment by SGXander** [comment]
fairly sure this has been an issue with mine since this years family hub update (roughly July) but can't be certain. Mine has shown blank markdown cards since at least HA 2023.9.x

**Comment by Tiwing1** [comment]
easily goes back to 2022.12 which is when we got our new fridge. Any updates on this issue, or any work-arounds?

additional info: card-mod css styles are reproduced fine for ha-card:

**Comment by cyallater** [comment]
No updates or work arounds currently. Did you want to add a link to ha-card?

**Comment by cyallater** [comment]
<any way to show an input_text entity on the family hub as a clickable link is much appreciated..>

**Comment by cyallater** [comment]
... any way to display a input_text as clickable link on the family hub is much appreciated. That way I can share a web page from my iPhone to the fridge...

**Comment by SGXander** [comment]
> ... any way to display a input_text as clickable link on the family hub is much appreciated. That way I can share a web page from my iPhone to the fridge...

You could use the mushroom template card with a template and the input_text state then the tap action as the url...

**Comment by Tiwing1** [comment]
switched to type: custom:mushroom-title-card and working beautifully. Only downside I found is you can't put an <a href= ></a> into the content like you can with Markdown. oh well, not a big deal. cheers.

**Comment by cyallater** [comment]
> > ... any way to display a input_text as clickable link on the family hub is much appreciated. That way I can share a web page from my iPhone to the fridge...
> 
> You could use the mushroom template card with a template and the input_text state then the tap action as the url...

unfortunately, the content of the input_text is the url, but the action does not allow for templating, only string (I'm looking for a way to share links from my iPhone browser to the fridge)

**Comment by Tiwing1** [comment]
quick update - did some work to make the card look like the standard card using custom:mushroom-title-card and card-mod.
[https://pastebin.com/HKD5SWZP](url)  Still the limitation of not being able to put a URL in there.

**Comment by cyallater** [comment]
The root cause is not solved: Markdown card content does not show on samsung family hub. It's probably a broader issue, since the custom Sonos card does not work as well.

**Comment by cyallater** [comment]
With the new update of the Samsung browser, this seems to be solved
