### ISSUE TITLE
"Delete all tokens" button looks like it only deleted 'refresh tokens' but also deletes 'long-lived access tokens'

### ISSUE THREAD

**Issue by Millio345** [home-assistant/frontend#19010]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On the user profile page, at the bottom of the box "refresh tokens" there's a button called "delete all tokens".
Since this button is very clearly attached to the "refresh tokens" box, I assumed this would only delete refresh tokens and not Long-lived access tokens which are in a separate box lower on the page.

However, when clicking this, it deleted all refresh tokens (as expected) AND all Long-lived access tokens, which was not my intention. 

There  should either be separate buttons for both type of tokens or if that's not possible, it should be clearer that Long-lived access tokens are also deleted by either moving this button outside of the refresh tokens box or changing the wording to "Delete all refresh and long-lived access tokens tokens"

### Describe the behavior you expected

Only refresh tokens to be deleted when I click "delete all tokens" button inside the refresh tokens box.

### Steps to reproduce the issue

1. Go to /profile
2. Make sure you have at least one long-lived access token and one refresh token
3. Click "delete all tokens" , which is part of the refresh token box
4. See how both refresh tokens and long-lived access tokens are deleted
...

### What version of Home Assistant Core has the issue?

core-2023.12.1

### In which browser are you experiencing the issue with?

Firefox 120.0

### Which operating system are you using to run this browser?

Linux PC 6.6.3-arch1-1

**Comment by piitaya** [comment]
Are you talking about long-lived access tokens ?

![CleanShot 2023-12-11 at 14 13 32](https://github.com/home-assistant/frontend/assets/5878303/7de2a2e0-d813-47f2-8909-bac604d2fc0f)

There are also refresh tokens but with a type `long_lived_access_token`. I agree, these tokens should not be deleted. Core doesn't support to pass the type to the websocket endpoint (`auth/delete_all_refresh_tokens`) but it should be possible to add it.

**Comment by karwosts** [comment]
Bleh I had no idea it would delete those :\

I don't suppose any WS change can happen anytime soon, should we just revert the button?

**Comment by karwosts** [comment]
https://github.com/home-assistant/core/pull/106119 to add filtering on the type of token that can be deleted by the WS call.
