### ISSUE TITLE
new login screen won't turn off

### ISSUE THREAD

**Issue by disconn3ct** [home-assistant/frontend#19011]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The login screen won't stop listing all of our users

### Describe the behavior you expected

I expected to not show a list of all of our users to everyone who opens the page

### Steps to reproduce the issue

1. Install 2023.12.0
2. Open the login page
3. File a CVE
...

### What version of Home Assistant Core has the issue?

core-2023.12.0

### What was the last working version of Home Assistant Core?

core-2023.11.1

### Additional information

User account enumeration is a valid, common CVE category:
https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=user+enumeration

**Comment by frenck** [comment]
If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
