### ISSUE TITLE
Header missing on first login

### ISSUE THREAD

**Issue by nickthediver** [home-assistant/frontend#19019]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I first access Home Assistant on any platform Windows, Android on Mac I have problems with the header display. After refreshing the browser it reappears.
![2023-12-12 11_30_24-Strumenti per sviluppatori – Home Assistant](https://github.com/home-assistant/frontend/assets/82773051/0f7a9663-5aee-48fe-9bb4-defd9d1e2526)

### Describe the behavior you expected

![2023-12-12 11_34_49-Strumenti per sviluppatori – Home Assistant](https://github.com/home-assistant/frontend/assets/82773051/de880ad4-8c6a-46c3-8539-c89e4eb41709)

### Steps to reproduce the issue

1.access both remotely and locally on my home assistant: https://xxx.duckdns.org
2.I haven't problem to use any entity,but there'snt header
3.
...

### What version of Home Assistant Core has the issue?

after 2023.11.1 at now

### What was the last working version of Home Assistant Core?

2023.10.3

### In which browser are you experiencing the issue with?

Chrome 120.0.6099.62 (Build ufficiale) (a 64 bit)

### Which operating system are you using to run this browser?

Microsoft Windows [Versione 10.0.19044.2604]

**Comment by karwosts** [comment]
Suggest trying safe mode and seeing if that makes a difference. 

https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode
