### ISSUE TITLE
Zone entity name shown on dashboard instead of friendly name if Privacy == Zone Name Only

### ISSUE THREAD

**Issue by tom-parkinson** [home-assistant/frontend#19015]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If "Zone Name Only" is set under the "Location Sent" setting of the Companion app, then the entity name of the zone gets shown on the person entity cards on the dashboard. This behaviour is inconsistent with the "Exact" location sent setting, which shows the friendly name of the zone. 

![234bd992d6527e6b11c354ad7a4ba01fa1076a9d](https://github.com/home-assistant/frontend/assets/40145982/9a545aa3-5606-45da-a374-baa2f82fffe1)

In this example, kids have the “Location Sent” to “Exact” under Privacy in the app and for adults to “Zone Name Only”.
The dashboard with simple person entities shows correctly “Home” and “Away” for all. However, once in a pre-configured zone:
- kids: it displays the zone’s friendly name, e.g. “School”
- adults: it displays the zone’s entity, like “kids_school” instead of “School”.

There's a [forum discussion thread](https://community.home-assistant.io/t/zone-entity-name-shown-on-dashboard-instead-of-friendly-name-if-privacy-zone-name-only-a-bug/519603) with several users about this.

### Describe the behavior you expected

The friendly name should be shown on the dashboard for all pre-configured zones in both "Exact" or "Zone Name Only" settings.

### Steps to reproduce the issue

1. Add a Person entity card to dashboard
2. Set 'Location Sent' to 'Zone Name Only' under Privacy section in the Server config of the Companion App settings
3. Leave Home zone

### What version of Home Assistant Core has the issue?

2023.12.1

### In which browser are you experiencing the issue with?

Safari 18615.3.12.11.2

### Which operating system are you using to run this browser?

macOS Ventura 13.5.2

**Comment by karwosts** [comment]
When this is happening, can you show the exact state and attributes of this privacy-enabled person from developer tools?

**Comment by karwosts** [comment]
Also lets grab the device_tracker entity information as well, just for completeness.

**Comment by tom-parkinson** [comment]
<img width="1092" alt="Screenshot 2023-12-12 at 10 26 08 am" src="https://github.com/home-assistant/frontend/assets/40145982/cc317b12-51b5-483b-878c-3bdab06ac203">
<img width="1134" alt="Screenshot 2023-12-12 at 10 26 31 am" src="https://github.com/home-assistant/frontend/assets/40145982/3a63d0f2-92cd-4dd8-89af-2a0fcc1bd693">
<img width="1030" alt="Screenshot 2023-12-12 at 10 27 06 am" src="https://github.com/home-assistant/frontend/assets/40145982/1d2a17ae-24b1-4cdf-a9f7-ef7bd39b27c7">

**Comment by karwosts** [comment]
Thanks. From what I'm seeing here I think your issue must be either a core issue or an app issue, not sure which. 

It looks like in the normal non-private case, the state of a person is the friendly name of the zone. The frontend does not do any friendly name lookup, except for the case where it is `home` or `not_home`. For other zones it just reports the state of the person directly with no translation.

If your person entities have `state` with a non-friendly zone name, that would need to be looked at as a core issue to understand why that was happening. But I'm not seeing a frontend bug here yet.

**Comment by tom-parkinson** [comment]
Makes sense - thanks for the quick response. I wasn't sure exactly where the issue lies, but it sounds like I should submit the issue to core?

**Comment by karwosts** [comment]
That's worth a try as the next step, see if you can engage someone there who can continue debug, or point you towards the companion app if that is believed to be related.

**Comment by tom-parkinson** [comment]
[Done](https://github.com/home-assistant/core/issues/105533) - thanks again for all your help.
