### ISSUE TITLE
Button card not showing in frontent at boot

### ISSUE THREAD

**Issue by bricololo44** [home-assistant/frontend#19020]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I use button card in Container with Header.
On the first load, on my default dashboard there are missing cards. To display them, I must select another dashboard and return to the default one.
Refreshing the Explorer is not enough.
Problem encountered on different versions of Chrome and also the companion application on Android.

### Describe the behavior you expected

I would like all cards to be displayed at startup
![Screenshot_good](https://github.com/home-assistant/frontend/assets/67336278/3c639962-f252-41ab-acd4-1c11be07c2cd)
![Screenshot_bad](https://github.com/home-assistant/frontend/assets/67336278/c411278c-d29b-4b74-9f51-f280d00bbcf6)

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.12.1

### In which browser are you experiencing the issue with?

Chrome Version 114.0.5735.110 (Build officiel) (64 bits)

### Which operating system are you using to run this browser?

Windows 10 10.0.19045 Build 19045

**Comment by ildar170975** [comment]
What is a "button card"?
Custom cards are not supposed to be discussed here.
If this is a custom:button-card - consider creating an issue in a corr. repo.

**Comment by karwosts** [comment]
You look to have a pretty heavily modded/custom UI, which we unfortunately cannot support here.

If you can show this error in safe mode, we can continue to debug it, but it looks like you may be using some kind of unsupported stack card which could likely be the cause of your issue.
