### ISSUE TITLE
Projekt Upload files with .knxproj filesize == 3.6MB

### ISSUE THREAD

**Issue by gillhofer** [home-assistant/frontend#19030]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Clicking on the KNX-BUS symbol on the left bar on the HASS default page allows one to upload the `.knxproj` file. However, this upload fails due to file size contraints. 

![image](https://github.com/home-assistant/frontend/assets/4135093/1097a31b-6ceb-42ee-bee4-3648d476a436)
The file is 3.5MB in size. 

### Describe the behavior you expected

The file gets uploaded just like it is described.

### Steps to reproduce the issue

1. Use a 3.5 MB file for uploading
2. If this works, it might be a Raspi 2 installation problem, for which I can expect no support (I know)

### What version of Home Assistant Core has the issue?

2023.12.1

### What was the last working version of Home Assistant Core?

never worked

### In which browser are you experiencing the issue with?

edge, chrome, firefox

### Which operating system are you using to run this browser?

Tried Linux and Windows in a VM

### Javascript errors shown in your browser console/inspector

```txt
Failed to load resource: The server responded with a status 413 - Request Entity Too Large
```

**Comment by silamon** [comment]
This is not a frontend issue, since the upload of the file is handled by the backend. The backend, located in this [repository](https://github.com/home-assistant/core), allows an upload of 100 MB. It may be something specific to your setup, if you're proxying requests through a proxy, you may want to check there.
