### ISSUE TITLE
Horizontal and Vertical Card appear as opposites

### ISSUE THREAD

**Issue by Goopdegooo** [home-assistant/frontend#19034]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Horizontal card is displayed as vertical and vertical card is displayed as horizontal

### Describe the behavior you expected

horizontal card to be horizontal.
![Screenshot 2023-12-14 054104](https://github.com/home-assistant/frontend/assets/147979249/1a1a0bfb-a092-4919-9822-6c4ae44506df)
![Screenshot 2023-12-14 054501](https://github.com/home-assistant/frontend/assets/147979249/3f15bdb1-69bd-4d1b-99c6-d0a48078087c)

### Steps to reproduce the issue

1. Created a conditional card with a horizontal stack, 1st card as gauge,  second as entity, preview shows as vertical.
2. Tested without conditional card, horizontal is shows an vertical and visa versa
3.
4.
...

### What version of Home Assistant Core has the issue?

2023.12.0

### What was the last working version of Home Assistant Core?

previous to 2023.12.0

### In which browser are you experiencing the issue with?

Brave ChromiuRelease Notes v1.61.101 (Dec 7, 2023) Upgradedm to 120.0.6099.71.

### Which operating system are you using to run this browser?

Windows 11

### Additional information

tested with google chrome latest download as of 5:50am Perth WST 14.12.2023

**Comment by karwosts** [comment]
I don't really understand what you are saying. Horizontal stack means the cards are placed side by side. 

Vertical stack implies the cards are placed one above the other. 

The preview looks correct.
