### ISSUE TITLE
Deconz Update Button missing

### ISSUE THREAD

**Issue by stoneubi** [home-assistant/frontend#19033]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This issue is linked to the deconz intergration. According to the documentation, deconz software and firmware for the conbee II stick can be update through the UI in the Phoscon App. 

My stick does not have the latest deconz version 2.24.2 and I wonder, why the update button is not shown in the UI.

### Describe the behavior you expected

My stick does not have the latest deconz version 2.24.2 and I wonder, why the update button is not shown in the UI.

![Screenshot_2023-12-13-18-46-53-87_4d38fce200f96aeac5e860e739312e76](https://github.com/home-assistant/frontend/assets/32926093/3f1d6dc0-9371-420b-a257-462dea13a702)

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.12.1

### Which operating system are you using to run this browser?

I tried from three different browsers with different operating systems. Same result.

**Comment by karwosts** [comment]
Are you asking about the Home Assistant Frontend UI or some other UI? I assume that screenshot is not from HA, in which case I don't quite understand why you opened this issue here. Could you elaborate a bit more?
