### ISSUE TITLE
no way to see color_temp value anymore in UI (except when sliding)

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#19066]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

no way to see Kelvin color_temp value anymore in UI
<img width="307" alt="Scherm­afbeelding 2023-12-17 om 11 11 36" src="https://github.com/home-assistant/frontend/assets/33354141/1e968a35-4f48-48a9-8154-fbdacff9314b">

aware you believe showing the brightness on the color_temp page is the right thing to, and we had a discussion on that I the below linked and closed issue.

Not showing the value anymore at all is a bug though and takes that one step beyond.

### Describe the behavior you expected

click a light more-info, open color_temp view and find the color_temp.
its gone, no longer in the header of the slider either.
We need to actually slide the handle to reveal a value in the popup of the handle. Which is bad, because it only starts showing when already sliding, so no idea where it was exactly before. Or to have it not change but only check

### Steps to reproduce the issue

1. see above 
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.12.3

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

Sonoma 14.1.2

### Additional information

Picking up from https://github.com/home-assistant/frontend/issues/17870

**Comment by Mariusthvdb** [comment]
side post:

Ive just discovered this
<img width="257" alt="Scherm­afbeelding 2023-12-17 om 13 33 23" src="https://github.com/home-assistant/frontend/assets/33354141/90e85412-f99c-40f2-a074-99b2e4957006">

hoping the color_temp and brightness might have popped up on hover those buttons.
Instead they show an incorrect number on the first button (index value probably)

**Comment by mwav3** [comment]
If it helps this is a recording of the current behavior - I would say it would be ideal when the user clicks the "color temp" mode at the bottom that instead of showing brightness percentage at the top, it shows the color temp value instead

![color temp](https://github.com/home-assistant/frontend/assets/65051965/92f1c032-3b3f-4aff-8805-44d339eb5d0d)

**Comment by VDRainer** [comment]
It's also unusable in Dark mode.
Or is there any theme variable that must be set?
![20231218_114031](https://github.com/home-assistant/frontend/assets/26381449/7fbea9af-d664-4a60-8ded-038f5349d528)

**Comment by karwosts** [comment]
@VDRainer - mine looks fine in dark mode. You must have some other issue going on. Anyway that is off-topic for this thread. 

![image](https://github.com/home-assistant/frontend/assets/32912880/3102358a-8d0d-4876-95b2-db15663c3dae)
