### ISSUE TITLE
Default dashboard no longer sorts alphabetically anymore

### ISSUE THREAD

**Issue by kmichels** [home-assistant/frontend#19060]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Rooms in the default dashboard used to be sorted alphabetically. This is no longer the case.

### Describe the behavior you expected

Rooms in default dashboard should be sorted alphabetically.

### Steps to reproduce the issue

1. Log into HA
2. Click on "Overview"

### What version of Home Assistant Core has the issue?

core-2023.12.3

### In which browser are you experiencing the issue with?

Safari 17.2

### Which operating system are you using to run this browser?

macOS Sonoma 14.2

**Comment by karwosts** [comment]
Already fixed by #18989 and will release in the next version with a frontend bump.

**Comment by karwosts** [comment]
If you are impatient to wait, you can use the new areas picker in the overflow menu and they will be put back to sorted order.
