### ISSUE TITLE
New thermostat card blocking/slowing down UI

### ISSUE THREAD

**Issue by janrothkegel** [home-assistant/frontend#19074]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The new thermostat card of the December roll-out is slowing down the UI in web as well as in iOS app. Often I have to kill the app and restart.

### Describe the behavior you expected

Same performance as before the update

### Steps to reproduce the issue

1. Put some thermostat controls to a dashboard
2. See it slow down

### What version of Home Assistant Core has the issue?

2023.12.3

### What was the last working version of Home Assistant Core?

2023.12.1

### In which browser are you experiencing the issue with?

Firefox

### Which operating system are you using to run this browser?

Windows 10

**Comment by piitaya** [comment]
Is it only when the thermostat is off? There was an issue open, may be your issue is related : https://github.com/home-assistant/frontend/issues/18999

**Comment by marc4s** [comment]
I also got affected here with 2023.12 and my thermostats are off yes. the dashboard containing other thermostats which are ON seems not to be affected

**Comment by piitaya** [comment]
Next patch release should fix your issue. It's a duplicate of #18999.

**Comment by janrothkegel** [comment]
[#18999](https://github.com/home-assistant/frontend/issues/18999) is marked as closed. However, I still suffer from slow pages containing the thermostat cards :-(

**Comment by piitaya** [comment]
> @piitaya [#18999](https://github.com/home-assistant/frontend/issues/18999) is marked as closed. However, I still suffer from slow pages containing the thermostat cards :-(

Are you on beta version? It should be fixed on beta.

**Comment by janrothkegel** [comment]
> > @piitaya [#18999](https://github.com/home-assistant/frontend/issues/18999) is marked as closed. However, I still suffer from slow pages containing the thermostat cards :-(
> 
> Are you on beta version? It should be fixed on beta.

Ah ok, I will try tomorrow when I am back home. Thank you very much for your swift response and have a happy new year :-)

**Comment by janrothkegel** [comment]
Works now with 2024.1
Thank you very much!

**Comment by janrothkegel** [comment]
Works now with 2024.1
Thank you very much!
