### ISSUE TITLE
Cover tile card position bar shows wrong info.

### ISSUE THREAD

**Issue by AAWi** [home-assistant/frontend#19091]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I got a tile card that shows a cover entity. I enabled the cover position feature, which shows a bar representing the percentage of the cover that is open. The problem that I'm experiencing is that the bar shows that the cover is 100% open when it is closed and that it is 0% open when is fully open. So it's showing the opposite of what the real situation is (except at 50% ;) ).

![Screenshot 2023-12-19 201814](https://github.com/home-assistant/frontend/assets/25462684/fa1b7358-68ed-4510-aaf6-e2105eb1b9f3)

Here is a screenshot of the tile card on my dashboard. You can see that the retract button is grayed out, so the cover is fully closed. But the bar shows like it's fully open.

### Describe the behavior you expected

I expect the bar to show 0% when the cover is closed and 100% when it is fully open.

### Steps to reproduce the issue

1. Add a tile card
2. Set a cover entity
3. Enable the cover position feature
...

### What version of Home Assistant Core has the issue?

2023.12.2

### In which browser are you experiencing the issue with?

Google chrome 120.0.6099.72 

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
When fully closed: 
current_position: 0
device_class: window
friendly_name: Solar screen
supported_features: 15

When fully open:
current_position: 100
device_class: window
friendly_name: Solar screen
supported_features: 15
```

### Problem-relevant frontend configuration

```yaml
type: tile
entity: cover.solar_screen
features:
  - type: cover-open-close
  - type: cover-position
```

### Additional information

The issue is shown on different dashboard and in de android app as well.

I use the tile card also for showing a fan entity. There I also show a bar as a feature and there the bar shows the correct value.

**Comment by karwosts** [comment]
I will point out this was discussed and debated pretty extensively as part of the original PR ( https://github.com/home-assistant/frontend/pull/16110 ), so I would say this is intended and not a bug, as it seems the primary HA designers want it to be this way. 

You can read the thread if you'd like more information on the history.

**Comment by AAWi** [comment]
Ah I see, thanks for pointing that out. I will go and look for a cover card that shows it the (in my opinion) correct way. This way is just too confusing.
