### ISSUE TITLE
Themes are not properly applied

### ISSUE THREAD

**Issue by Alex1wd** [home-assistant/frontend#19099]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

i installed HAOS on a mini PC, and after i did all the configuration i previous had on a VM, i'm not able to apply the any themese as before. I install the themes using HACS, but when i select the theme from Profile, it only changes the top bar, nothing happens to the cards or background. 
until now i: - deleted HACS,
- install everything again
- checked on a VM and the themes are applying there
- tried different themes with no results

### Describe the behavior you expected

when a theme is applied the cards and background of the dashboard should change as well

### Steps to reproduce the issue

1.install HACS
2.download iOS theme
3.Apply theme from profile
4.Confirm theme applied succesfully

### What version of Home Assistant Core has the issue?

2023.12.3

### What was the last working version of Home Assistant Core?

2023.3.6

### In which browser are you experiencing the issue with?

MOzilla 120.0.1 64 bit

### Which operating system are you using to run this browser?

Windows 11

**Comment by ildar170975** [comment]
1. HACS is a custom plugin. If some particular issue caused by HACS - report in HACS repo.
2. All themes installed by HACS = custom. If some custom theme does not work - report in a repo of this custom theme. Or ask people in Community.
