### ISSUE TITLE
Blocking and unblocking of Networking Devices not working proberly like before

### ISSUE THREAD

**Issue by leleo73** [home-assistant/frontend#19096]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I don´t know if the update of the unifi Console to 3.2.7 and the network application  to 8.024 produce the problems or the update of HA 2023.12. After a restart network device can block and unblocked with a switch in HA. But after a few minute the state of the switch doesn´t change and i cannot use the switch anymore to change from blocked to unblocked state.

### Describe the behavior you expected

Changing state from blocked to unblocked or unblocked to blocked

### Steps to reproduce the issue

1. restart HA
2. use a UI switch for a device
3. after a while the state doesn´t change anymore
...

### What version of Home Assistant Core has the issue?

2012.12.3

### What was the last working version of Home Assistant Core?

2012.11.xx

### In which browser are you experiencing the issue with?

Microsoft Edge Version 120.0.2210.77 

### Which operating system are you using to run this browser?

MAc OS 14.2.1 (23C71)

**Comment by karwosts** [comment]
If this is specfiically related to toggles for the Unifi integration, please open an issue in home-assistant/core for the unifi integration. 

Frontend doesn't really have any integration-specific logic.

**Comment by leleo73** [comment]
thank you
