### ISSUE TITLE
No available Actions on Mac OS Widget under Sonoma

### ISSUE THREAD

**Issue by etruscan** [home-assistant/frontend#19090]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When trying to edit the Mac OS Widget to add an action, the actions dropdowns are empty. 

<img width="368" alt="image" src="https://github.com/home-assistant/frontend/assets/6545500/fa75fb16-ef13-44cb-8d40-5d65dbca01e2">

### Describe the behavior you expected

Expect to open Actions and see a list of available actions.

### Steps to reproduce the issue

1. click notifications area
2. right click on HA widget and choose "Edit 'Home Assistant'"
3. click "Choose" on any of the empty action slots

### What version of Home Assistant Core has the issue?

Home Assistant 2023.3.3

**Comment by karwosts** [comment]
Think you might want to start this in the [iOS](https://github.com/home-assistant/iOS/) repository, this seems like something related to the app, not the HA frontend.

**Comment by etruscan** [comment]
It's not iOS related though, it's Mac OS. Should I still start it over there?

**Comment by karwosts** [comment]
Are you using a home-assistant app from an app store? I'm not super familiar with the mac ecosystem, but that landing page does advertise as "Home Assistant for apple platforms". If it uses the same app then I think that would be the place to go. If not they'll tell you otherwise.

**Comment by tomkerswill** [comment]
I managed to get this to work in MacOS, by going to preferences in the Macos companion app. I was able to add actions there, and they then appear in the Macos widget.
