### ISSUE TITLE
Energy graph not showing "Tooltips" detailing breakdown of usage for any hour when only battery usage and export occurred

### ISSUE THREAD

**Issue by bashers222** [home-assistant/frontend#19106]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On the daily energy chart, there are no tooltips showing details of power consumption when using battery AND exporting to grid
![291653361-e1af20d2-9c4d-4c9e-b1df-2efa9618f30e](https://github.com/home-assistant/frontend/assets/22331682/e1c2711f-48c5-42df-8b5a-f783bbee524c)

It works fine on all hours around when there is a diferent mix of consumption:
![291653713-3c52658c-21d9-4b5c-8e44-c18f79800230](https://github.com/home-assistant/frontend/assets/22331682/93f7c2a2-e17a-433f-86cc-d3c93110f7f5)

### Describe the behavior you expected

pop ups / tooltips available over all hour slots in Energy dashboard

### Steps to reproduce the issue

Hover over an hour with only export and battery usage. no solar or consumption from grid - NO tooltips shown
Hover over any other hour, tooltips are shown

### What version of Home Assistant Core has the issue?

core-2023.12.3

### Which operating system are you using to run this browser?

win11 22H2

**Comment by karwosts** [comment]
Should be fixed by #19031
