### ISSUE TITLE
Overview Dashboard Sorting

### ISSUE THREAD

**Issue by DocDrydenn** [home-assistant/frontend#19100]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The autogenerated Overview dashboard has stopped sorting alphabetically.

### Describe the behavior you expected

The autogenerated Overview dashboard used to sort the cards alphabetically by their titles.

### Steps to reproduce the issue

View the Overview dashboard.

Even tested creating a new dashboard... `+ Add Dashboard --> Default Dashboard`. New dashboard is also not sorted. It matches the Overview dashboard.

### What version of Home Assistant Core has the issue?

2023.12.3

### In which browser are you experiencing the issue with?

Google Chrome 120.0.6099.110 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11 Pro v23H2 Build 22631.2861

### State of relevant entities

```txt
Cards and entities are showing and working as expected. The actual cards (containing the entities) are no longer in alphabetical order by card title.
```

### Problem-relevant frontend configuration

```yaml
Default system controlled Overview Dashboard.
```

### Javascript errors shown in your browser console/inspector

```txt
None.
```

### Additional information

This seems to be exactly like [#14556](https://github.com/home-assistant/frontend/issues/14556)

I don't use the Overview dashboard all that much, so I can't even be sure as to which update brought this back. My guess is that it was sometime within the last three updates.

Current Setup:
Core - 2023.12.3
Supervisor - 2023.12.0
Operating System - 11.2
Frontend - 20231208.2

Checked on multiple computers/laptops with Edge and Chrome browsers.

**Comment by DocDrydenn** [comment]
Of course, after I submit this Issue, I started to play around some more and stumbled onto a fix (?)...

Overview --> `Edit Dashboard` --> `Areas` ... The list opens up and shows all Areas in alphabetical order, so (without changing anything) I just clicked on `Submit`.  The list closes and the default Overview dashboard refreshes... now with everything in the proper alphabetical order. Go figure...

**Comment by karwosts** [comment]
Already fixed by https://github.com/home-assistant/frontend/pull/18989 and will release in the next version with a frontend bump.
