### ISSUE TITLE
Sensor has state class total_increasing but its state class is not strictly increasing

### ISSUE THREAD

**Issue by orgebar** [home-assistant/frontend#19104]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I found a log entry in the log viewer, which kindly asks me to report a bug here, so I do of course ;). It seems there is an issue of some kind with the measuring of the zha plug consumption, but I don’t know exactly.

`2023-12-21 01:40:10.246 WARNING (Recorder) [homeassistant.components.sensor.recorder] Entity sensor.plug_lidl_balkon_zusammenfassung_geliefert_2 from integration zha has state class total_increasing, but its state is not strictly increasing. Triggered by state 61.59 (61.6) with last_updated set to 2023-12-21T00:37:12.151839+00:00. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+zha%22`

### Describe the behavior you expected

Im just reporting as wished in the log. The sensor itself seems ok:
![IMG_2307](https://github.com/home-assistant/frontend/assets/77870103/e0d77ce6-9fcd-4df0-bcf4-2ed667cb139c)

### Steps to reproduce the issue

None. Entry just showed up

### What version of Home Assistant Core has the issue?

2023.12.3

**Comment by karwosts** [comment]
Hi, thanks for reporting but you're in the wrong repository.

The log message requests to file an issue in home-assistant/**core**. This is the frontend, which has nothing to do with that message.
