### ISSUE TITLE
Gauge text label for Energy net consumption not scaling correctly

### ISSUE THREAD

**Issue by MaumauMC** [home-assistant/frontend#19114]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The text isn't scaling correct if it is 4 digits or more
![Screenshot_20231221_201052_Home Assistant](https://github.com/home-assistant/frontend/assets/145475791/5dd08e68-484e-4bca-ad65-5dd099ac4aa0)

### Describe the behavior you expected

It should scale to the size it has to be to fit in the empty space. 

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.12.3

### In which browser are you experiencing the issue with?

HA App on a Samsung galaxy tab s7 plus 

### Which operating system are you using to run this browser?

Android 13

**Comment by karwosts** [comment]
Does it always look wrong, or only sometimes? Do you ever see the label changing size?

There is code in the gauge to resize the label to fit, and in my installation I see it resizing correctly every time the number changes. Not sure why it wouldn't be working for you. I will say I have seen another user once reported this same issue, but he said it started working again at some point.

**Comment by ChristophCaina** [comment]
asumtion: it might be some cache-related thing?
It might "fix" itself when the page will be reloaded... 

I was just going through the previous days on my setup, and the size of the label did change as expected.

<img width="258" alt="image" src="https://github.com/home-assistant/frontend/assets/26391061/8b3919f6-1407-4ccb-9238-a24872249246">
<img width="254" alt="image" src="https://github.com/home-assistant/frontend/assets/26391061/3f820e48-1bd2-46d7-93c9-12b75feb09ec">

**Comment by Sunfllower** [comment]
![Energy dashboard size kWh](https://github.com/home-assistant/frontend/assets/33829884/4cc4c926-d39d-4c01-a2c0-881e73102f43)
I do have the same  incorrect scaling when scrolling back in time in the energy dashboard. From left to right in my uploaded jpg file, (today, yesterday, 2days ago, yesterday). When you have you have a kwh value in the energy dashboard lower then 10 kWh as 'net comsumed from the grid' the displayed value is in a larger font. if you view data from the previous day and then the value is 10kWh or larger the value is incorrect displayed. Scrolling further to older data in the energy dashboard corrects the size of the displayed value and then it stays in the correct size. 
To reproduce go back to the current day with a consumed value lower then 10 kWh so the font is larger, switch to the overview view and then back to the energy dashboard.  When you look again at the energy data of the previous days its in the incorrect font size when data from that day is larger then 10kWh.

**Comment by karwosts** [comment]
Thanks for that detailed reproduce instruction. Unfortunately I personally still can't reproduce that though, I tried chrome, firefox, edge, and my android app, and on every one resizes the label correctly each time the value changes 😕 

Are you also on an android app like OP, or is that in a browser? Can you try an alternative browser or client and see if you get the same?

**Comment by Sunfllower** [comment]
![Capture 6 july font size difference](https://github.com/home-assistant/frontend/assets/33829884/9312e9ed-a0c8-439b-aae2-da2f13eb921d)
![Capture HV 7 july scaling text](https://github.com/home-assistant/frontend/assets/33829884/f70ec997-72e9-4665-9426-1f7d40b58f64)
I have this issue in both chrome and edge during testing. See my screenshots scrolling through data from 9 to 5 july does not show any incorrect kwh format. However when i scroll 5 to 9 july the format for 7july is incorrect. What i do notice when the format changes from 4 digits (like xx.xx) to 2 digites (xx or x.x)  the font increases more then from 3 digits format to 2 digits format. Resulting in de xx or x.x number written larger however still within the gauge.  See the jpg with the same value "9,6 kWh" however in a different font size.   
When scrolling through data is guess this issue is only visible when following digit sequence is matched. 
first syntact xx.xx followed by x.x or xx digits and last number xx.x or x.xx format.

**Comment by Sunfllower** [comment]
![Capture 14 jan font size difference](https://github.com/home-assistant/frontend/assets/33829884/e1c89bf4-4958-4520-a049-771ffe3397ae)
Another test with the text size. Top row in jpg is view after scrolling through data of the last days. Currently today consumption is of x.x format and size is large for 14 januari, when i scroll to previous days layout is ok. 
Bottow row jpg: started at 14 januari data view however did switch console to overview and back to the energy dashboard. Now i do notice that the "6,8 kWh" text is larger then before. When i do scroll to data from the previous days the text size is now to large to until we encounter a xx.xx data format which lowers the font size. 

So to simulate first data x.x or xx format, switch to overview screen and back to energy dashboard, is next data is xx.x of x.xx format  than size is to large, When xx.xx data format is displayed, font size is set again low enough for all formats to display correctly.

**Comment by jkoljo** [comment]
I am having the exact same issue with Core 2024.3.1, Frontend 20240307.0. Both Chrome on PC and HA companion app on Android.

**Comment by karwosts** [comment]
Solved by #23536
