### ISSUE TITLE
battery column not wide enough  to show the battery icon for states using a decimal

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#19119]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

not wide enough to show the battery icon

<img width="332" alt="Scherm­afbeelding 2023-12-22 om 10 43 27" src="https://github.com/home-assistant/frontend/assets/33354141/799f114c-8a1c-4c2a-8b5e-6d5c0362fb7e">

### Describe the behavior you expected

show the icon
maybe even adjust the column width

### Steps to reproduce the issue

1. check battery column
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.12.3

### What was the last working version of Home Assistant Core?

never

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

Sonoma 14.1.2

### Additional information

we can probably adjust the precision, but that is besides the issue.

we can Not adjust the common width, which would be the solution. or make that auto happen... there's plenty of space

**Comment by matthiasdebaat** [comment]
`100,0 %` should be `100 %`, as you can't have `100,8 %` And I think we should remove the decimal when it's `0`. For example `59,0 %` should be `59 %`.

**Comment by karwosts** [comment]
I fixed this a year ago in #14927, but then it looks like the fix was removed in #17631😕

**Comment by Mariusthvdb** [comment]
Agree with the 0 and 100 scenario.

When in between the decimal should not cause the icon to be killed...

Make the column a bit wider and all is set ?

**Comment by silamon** [comment]
I will open a PR since I broke it again after your PR @karwosts .

**Comment by Mariusthvdb** [comment]
just mentioning that not all battery sensors report a rounded number.

<img width="582" alt="Scherm­afbeelding 2023-12-23 om 10 54 18" src="https://github.com/home-assistant/frontend/assets/33354141/2ac3f462-e84e-4593-bb01-53fdde74b864">

it would not be good if we couldnt get the exact value I the Dashboard anymore because of some generic rounding. 
In stead if fixing the column width.

Personally I feel we should always accommodate the true raw value. (and let the user decide how to round it with the precision setting we already have)

**Comment by silamon** [comment]
I've opened a PR to increase the width with 10px, so it can show the battery state completely.
