### ISSUE TITLE
hidden entity stay hidden if the integration is delete

### ISSUE THREAD

**Issue by Nemesis24** [home-assistant/frontend#19142]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have create a group of fan 
choose  "hide the entities"
i delete the group
i can't now "show entities"

### Describe the behavior you expected

When delete group who hide entities give a message to show entities, or show entities directly or let the the possibility to show entities again.

### Steps to reproduce the issue

1. create a group
2. hide entities
3. delete group
4. go to entities " still hidden" " and unable to change that

### What version of Home Assistant Core has the issue?

2023.11.3

### What was the last working version of Home Assistant Core?

2023.11.3

### In which browser are you experiencing the issue with?

chrome

### Which operating system are you using to run this browser?

windows 11

**Comment by karwosts** [comment]
This is not the expected behavior of groups, if they hide entities when they are created the entities are supposed to be unhidden when it is deleted, so I'm not sure how that process went wrong in your case (but that's a core issue, not a frontend issue). 

If we merge #19123 that will allow you to unhide it manually.
