### ISSUE TITLE
energy dashboard stops working unexpected - restart HA solves it for then next veiw houry - then i stops unexpected again 

### ISSUE THREAD

**Issue by kriger1965** [home-assistant/frontend#19151]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

when I have a look on my energy dashboard (daily view) then I was surprised of stopping the coninuing dsiplaying of recourses. 
- gasconsumtion
- solar energy production
- - water consumtion
.... and so on

in this picture you can see that the dashboard stopped report datas in the holes where i pointed to the "missing Data"

![energy dashboard  problem00](https://github.com/home-assistant/frontend/assets/124938310/19ef751a-6c08-44cf-b805-b4f325eb6f4e)

and another example:

![energy dashboard problem](https://github.com/home-assistant/frontend/assets/124938310/07287a6c-973b-4267-be03-bdd2f6cfd757)
 

### Describe the behavior you expected

I don´t kow what information you need to support me and track this issue.
Just when I restart HA the system works properla again ...til lthe next stop is recognized

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

 Core 2023.12.3 Supervisor 2023.12.0 Operating System 11.2 Frontend 20231208.2

### In which browser are you experiencing the issue with?

there is no differenc ob what browser I used

### State of relevant entities

```txt
This entitys are involved: 
- EVG Zähler Shelly3EM channel A energy
- EVG Zähler Shelly3EM channel B energy
- EVG Zähler Shelly3EM channel C energy

- EVG Zähler Shelly3EM channel A energy returned
- EVG Zähler Shelly3EM channel B energy returned
- EVG Zähler Shelly3EM channel C energy returned

------------------------------------------------------------------------

- Benning WR1 Energy Total
- Benning WR2 Energy Total

-------------------------------------------------------------------------

- ESP02 Gas& Water (MQTT) Wasserverbrauch

-------------------------------------------------------------------------

ESP02 Gas& Water (MQTT) Gasverbrauch Energy

----------------------------------------------------------
```

### Problem-relevant frontend configuration

```yaml
I don´t know what information do you need for analysis ?
```

**Comment by karwosts** [comment]
The population of data for energy is not a frontend issue, that is handled by the core. Frontend only displays the data that was recorded. 

It seems possible that just one of your devices stop working or lost connection, I would check the history for that individual device and see if it is still reporting and updating correctly. Otherwise check your logs for errors, or head over to the forums/discord to ask for support help.

But I think this is off topic for this repo.

**Comment by kriger1965** [comment]
ok thanks. I will have a look.
