### ISSUE TITLE
Missing in translation - Login attempt failed

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#19162]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Missing in translation - Login attempt failed (marked in shared screenshot).

![LoginAttemptFailed](https://github.com/home-assistant/frontend/assets/61636045/96a06922-aa68-46b6-a999-366c6863cef0)

### Describe the behavior you expected

Please add to lokalise missing text.
Thank you.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.12.3

### What was the last working version of Home Assistant Core?

not relevant

**Comment by karwosts** [comment]
Not a string from frontend.
