### ISSUE TITLE
Automation description strings are truncated

### ISSUE THREAD

**Issue by karwosts** [home-assistant/frontend#19166]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

New automation element description strings are too long and truncated. 

![image](https://github.com/home-assistant/frontend/assets/32912880/6ef2617b-4cd8-4d7f-9b0d-35c603012ef0)

### Describe the behavior you expected

Maybe it should wrap? I don't think there's anywhere else in the UI to read what this string says, and I don't think there's any way to make the popup wider, so whatever sentence was written here will likely never be fully readable by anyone. 

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.1.0b0

**Comment by bramkragten** [comment]
I don't think we should wrap, but agree it is hard to keep the description fitting in all languages...

**Comment by silamon** [comment]
Mobile experience also ends up with shortened descriptions.

**Comment by bramkragten** [comment]
Yes, we will implement `md-list-item` that supports three-line items

**Comment by silamon** [comment]
Using md-list-items: 
![image](https://github.com/home-assistant/frontend/assets/32477463/cdf970f5-4b34-498a-8db4-46428ce11df8)

Unfortunately, there's a bug with the new material lists that you can't activate items when you tabselected an item making accessibility impossible.
