### ISSUE TITLE
utility_meter helper supported tariffs broken

### ISSUE THREAD

**Issue by BoxedBrain** [home-assistant/frontend#19164]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When creating a Utility Meter helper, the dropdown “Supported tariffs” seems to be broken. It shows `[object Object]`

![image](https://github.com/home-assistant/frontend/assets/7748392/507261b3-093d-4caa-9ffc-b606565d8734)

### Describe the behavior you expected

Working dropdown menu.

### Steps to reproduce the issue

1. Navigate to Devices & services -> Helper
2. Create Utility Meter helper

### What version of Home Assistant Core has the issue?

2023.12.4

**Comment by karwosts** [comment]
Might be fixed by https://github.com/home-assistant/frontend/pull/19154

**Comment by karwosts** [comment]
Yeah looks like that did it. Seems ok in the beta.
