### ISSUE TITLE
Enphase wrong data after power failure

### ISSUE THREAD

**Issue by LudoARN** [home-assistant/frontend#19175]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Still the wrong data problem after a power failure with the enphase integration :

![image](https://github.com/home-assistant/frontend/assets/81586322/4e4ecc80-d03d-4bca-af81-41f0eacee14e)

![image](https://github.com/home-assistant/frontend/assets/81586322/90312a0f-c6ba-484e-9413-ff6ce7c4bdbc)

### Describe the behavior you expected

Is it possible to add a feature to correct it directly ?

### Steps to reproduce the issue

Nothing exept a power failure

### What version of Home Assistant Core has the issue?

2023.12.4

### What was the last working version of Home Assistant Core?

2023.12.4

**Comment by karwosts** [comment]
Frontend is not involved with data collection. This should be a core issue.
