### ISSUE TITLE
MonoPrice 6 channel amp integration breaks after a day

### ISSUE THREAD

**Issue by TopoTop1** [home-assistant/frontend#19177]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The integration works well for about a day if not used or about 2 hours if used. Then it stops communicating with the amp and I have to restart the integration. 

### Describe the behavior you expected

HA loses connection to the amp and fails to pull zone updates, fails to send commands to operate the zones, sources, volumes, etc.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.11.3

### What was the last working version of Home Assistant Core?

None

### In which browser are you experiencing the issue with?

chrome, Edge

### Which operating system are you using to run this browser?

Win11

### State of relevant entities

```txt
Logger: homeassistant.components.monoprice.media_player
Source: components/monoprice/media_player.py:158
Integration: Monoprice 6-Zone Amplifier (documentation, issues)
First occurred: December 19, 2023 at 11:17:56 PM (645802 occurrences)
Last logged: 10:01:47 PM

Could not update zone 15
Could not update zone 16
Could not update zone 21
Could not update zone 22
Could not update zone 26


and this one


Logger: homeassistant.util.async_
Source: util/async_.py:140
First occurred: December 25, 2023 at 7:34:55 AM (3 occurrences)
Last logged: 5:22:34 PM

Detected blocking call to sleep inside the event loop by integration 'monoprice' at homeassistant/components/monoprice/__init__.py, line 61: hass.data[DOMAIN].pop(entry.entry_id), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+monoprice%22
```

**Comment by karwosts** [comment]
This sounds like an issue should be filed in home-assistant/core, not a frontend issue.
