### ISSUE TITLE
New Automations: `Play Media` lost the media picker

### ISSUE THREAD

**Issue by karwosts** [home-assistant/frontend#19183]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

`Pick media` selector is no longer present in automation action, it is less easy to use now.

The `Play Media` action in 2023.12:

![image](https://github.com/home-assistant/frontend/assets/32912880/298a7903-ee17-4702-859a-73f4f2228f60)

`Play Media` in 2024.1:

![image](https://github.com/home-assistant/frontend/assets/32912880/cb1766b9-71d3-419e-9995-bca68044976c)

### Describe the behavior you expected

Keep the media picker. 

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

frontend 20231228.0

**Comment by karwosts** [comment]
May be similar issue around `Activate Scene`, the displayed form is not the same, though that probably matters less.

**Comment by bramkragten** [comment]
`Activate Scene` was removed on purpose, because it is similar to the service. Play media was restored.
