### ISSUE TITLE
New thermostat card missing optimistic state timeout/reset

### ISSUE THREAD

**Issue by harristom** [home-assistant/frontend#19181]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Previously, when setting a temperature on the thermostat card, the set temperature would revert to the old one after a couple of seconds until the thermostat is next polled for the set temperature (usually not long after) by the backend. With the new card the behaviour has been changed so that the set temperature is kept by the frontend and it does not seem to check with the backend if the temperature was actually successfully updated.

If the temperature fails to be set the frontend will now be out of sync and will show the wrong set temperature and the user does not know that setting the temperature failed. It will also end up showing 2 different temperatures: 1) the new one on the card itself and 2) the old one on the more info for the card.

Aside from causing this inconsistency the old behaviour was quite useful for devices with spotty connections since you would effectively get a confirmation as to whether the change was successful.

### Describe the behavior you expected

The set temperature shown in the card should reflect the current value in the backend (after some short period to allow the user to finish adjusting the slider).

### Steps to reproduce the issue

1. Remove battery from smart TRV (to simulate poor connection)
2. Set a new temperature on new thermostat card
3. The thermostat card shows the "new" temperature. The more-info shows the correct, old temperature.

As far as I can tell the card will not show the correct temperature until you force reload the page.

### What version of Home Assistant Core has the issue?

2023.12.4

### What was the last working version of Home Assistant Core?

2023.11

### In which browser are you experiencing the issue with?

Edge Version 120.0.2210.77 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
I'll say this is somewhat of a contentious request, and probably tied up with architecture discussion https://github.com/home-assistant/architecture/discussions/740

Way back we had this timeout/reset in some, but not all, places in climate control, and many users were unhappy (as you are currently) about the state of the control being out of sync with the actual device, which did not receive or rejected the command. 

Then we added this timeout/reset feature to climate card, and a different set of users became unhappy, as they had battery thermostats which would take several minutes to acknowledge a climate change, and they didn't want it to reset on a timeout, because it looked like their command failed, when actually it would be successful many minutes later. 

So I'll say there's probably not a good solution that will make everyone happy, so I'm probably inclined to see if we get some guidance from that arch discussion before attempting to do anything here.

**Comment by harristom** [comment]
Sorry I never got back on this one because I couldn't follow all of the architecture discussion as I don't know the workings of the state machine well enough. Nonetheless it still feels to me to be an issue that you can issue a command and never get an indication that it has failed. At least with the opposite approach (assuming failure until next state update) the worst case scenario is that you run a command again that will have no impact because it already succeeded (i.e. you again switch on something that was already switched on and nothing happens).

It's funny you mention battery thermostats because that's actually the issue I'm having - when the batteries are weak or there is lots of interference (from routers/other bluetooth devices) setting the temperature sometimes fails and because it's not exposed in the UI I have no way to tell if it has worked. I have to say it feels a bit odd in 2024 to have to manually refresh a page to see if something went through or not. I agree the old flip flop is also weird and it makes sense to assume success at least for a limited period of time.

If I followed the thread and understood Paulus' suggestion correctly the point is more about allowing the backend to indicate in some way that a state is optimistic so the frontend can do with that info what it will and so that reloading the frontend doesn't give you a different result.

At any rate even without an architecture decision I think there should at least be _some_ timeout as a temporary fix even if it's crazy long for now (like 5-10 mins or something) until a firm decision is made. I don't think it's unreasonable that at some point a lack of update from the device can be taken as an indication that the command failed, but equally I can understand why a timeout in the range of seconds rather than minutes was causing problems for some people.

It's also worth noting that this was a change that happened only in November/December while the architecture discussion hasn't progressed since June so the change was made despite that not being resolved. I will try and track down when exactly the behaviour changed.

**Comment by harristom** [comment]
> I will try and track down when exactly the behaviour changed.

Oops nvm haha I forgot this was from when the new card was introduced
