### ISSUE TITLE
Calendar multiple events editing issue

### ISSUE THREAD

**Issue by lpispek** [home-assistant/frontend#19180]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I use the HA calendar to enter the waste collection schedule events manually. This schedule is entered as multiple repeating events. An issue arises when I edit events from "All Day events" to some time frame events. This can be visible in the pictures: 

Original created event: 
![image](https://github.com/home-assistant/frontend/assets/64278282/471eb9c8-553f-40e9-b16a-a7df826f0626)

Error after event change:
![image](https://github.com/home-assistant/frontend/assets/64278282/5a80b637-866c-4848-ace3-1efb315f8c2e)

![image](https://github.com/home-assistant/frontend/assets/64278282/5bf1447e-e63b-4717-aa3d-a8ec6536729a)

Error in the GUI Frontend:

![image](https://github.com/home-assistant/frontend/assets/64278282/4d00c36d-5604-4783-bdbd-a86bb67db549)

### Describe the behavior you expected

To change all the events from "All Day" to a specified time range.

### Steps to reproduce the issue

Just try to edit the "All day" property on recurring events to a specific time range.

### What version of Home Assistant Core has the issue?

core-2023.12.4

### In which browser are you experiencing the issue with?

Firefox 121.0, Chrome 120.0.6099.130 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11 23H2

**Comment by NateEaton** [comment]
I have not specifically seen this issue but I was checking on calendar front-end issues to see if the one I plan to report was already out here and found this one. It is similar enough that I will start by sharing the problem I am having in the event that it is related to the same code issue causing this one. If it becomes apparent that it is not related, I'll submit a separate issue. 

The issue I am having is when trying to change the time of a recurring appointment to a different time, after being prompted for whether to change the current event or all future events, if I select the current event the change is successfully made but if I select the option to update all future events it appears to work but once back in calendar view, the time has not changed on either the current event or any future events. Unlike the issue above reported by Zeljko, I am not seeing any error message and nothing shows up in the logs.

I am running Core 2023.12.4 and the issue occurs in Chrome on my Pixel Slate as well as in the app on my Android (Pixel 7). 

Below is a series of screenshots from when I retested this earlier today.
![Screenshot_20231229-124059](https://github.com/home-assistant/frontend/assets/185155/275fdd40-5a75-45b6-a204-00650c2121ef)
![Screenshot_20231229-124109](https://github.com/home-assistant/frontend/assets/185155/3551c526-7d43-4c74-98f6-11b8198bc9f5)
![Screenshot_20231229-124120](https://github.com/home-assistant/frontend/assets/185155/ecdb97b3-3706-4bb0-881b-90e3052d749c)
![Screenshot_20231229-124133](https://github.com/home-assistant/frontend/assets/185155/0825ee9e-433d-4170-9090-8b1083cbbf94)
![Screenshot_20231229-124139](https://github.com/home-assistant/frontend/assets/185155/562f2f7e-b5bb-4472-a096-5f77c9dbcc55)
![Screenshot_20231229-124154](https://github.com/home-assistant/frontend/assets/185155/f467b296-f2c8-40c6-90b4-e94085af2aaa)
![Screenshot_20231229-124233](https://github.com/home-assistant/frontend/assets/185155/f7a16c65-9b44-463d-9199-351e0627fa29)
![Screenshot_20231229-124243](https://github.com/home-assistant/frontend/assets/185155/758b13ab-cc1b-45f7-b509-d1d73006db7c)
![Screenshot_20231229-124252](https://github.com/home-assistant/frontend/assets/185155/95019505-ff01-47a5-bc9f-934e63e90b09)
![Screenshot_20231229-124316](https://github.com/home-assistant/frontend/assets/185155/1d78b517-f718-4e36-8b05-0cad10a10e33)
