### ISSUE TITLE
Calendar Edit

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#19190]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hi please add some button or something for edit Calendar
![image](https://github.com/home-assistant/frontend/assets/42905545/59963ee6-b2d7-43d4-ad2d-e00fdc0499b5)

### Describe the behavior you expected

*

### Steps to reproduce the issue

*

### What version of Home Assistant Core has the issue?

*

**Comment by karwosts** [comment]
Requests for new features go into [discussions](https://github.com/home-assistant/frontend/discussions). 

Also if you do decide to re-file this in the correct place, please write a little more detail about what you're looking for. From this single sentence it is not clear.
