### ISSUE TITLE
Rflink integration not working with latest RFLink Gateway V1.1 - **R50**

### ISSUE THREAD

**Issue by akicker** [home-assistant/frontend#19195]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Rflink integration not working with latest Nodo RadioFrequencyLink - RFLink Gateway V1.1 - **R50**
the only reply is: **dropping invalid data: 20;00;Nodo RadioFrequencyLink - RFLink Gateway V1.1 - R50**
back to R48 works fine!

### Describe the behavior you expected

R50 working

### Steps to reproduce the issue

2023.12.4

### What version of Home Assistant Core has the issue?

2023.12.4

### In which browser are you experiencing the issue with?

latest Chrome

### Which operating system are you using to run this browser?

Win10

### State of relevant entities

```txt
-
```

### Problem-relevant frontend configuration

```yaml
-
```

### Javascript errors shown in your browser console/inspector

```txt
-
```

### Additional information

-

**Comment by karwosts** [comment]
This sounds like a core issue, not frontend. Please open in home-assistant/core repo.
