### ISSUE TITLE
Navigating Issue - Back Arrow

### ISSUE THREAD

**Issue by Goopdegooo** [home-assistant/frontend#19196]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Clicking back button may not be functioning correctly. 

### Describe the behavior you expected

To go back to the previous menu on the first click back.

https://github.com/home-assistant/frontend/assets/147979249/9d4dab3d-f490-4ba5-ba7f-570ae8599fd9

### Steps to reproduce the issue

1.Added a picture to an area card.
2.Updated
3.Click back, not happened. (Visually Anyway)

took recording to show.

### What version of Home Assistant Core has the issue?

2023.12.4

### In which browser are you experiencing the issue with?

Brave v1.61.109 (Dec 21, 2023)  and Google Chrome Version 120.0.6099.130 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

### Additional information

This is also occurring with my companion app, in different screens etc.  I have to touch the back arrow twice in random menu sometimes more.  App version is 2023.12.4-full

**Comment by mill1000** [comment]
Possible duplicate of #14571 and #17820
