### ISSUE TITLE
RGBW light sliders disabled

### ISSUE THREAD

**Issue by jackwilsdon** [home-assistant/frontend#19209]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

"Colour brightness" and "White brightness" sliders are disabled for devices with `supported_color_modes: rgbw`:

![image](https://github.com/home-assistant/frontend/assets/1843197/4006412a-a16e-4082-8bd0-bc305fececf5)

### Describe the behavior you expected

Sliders should not be disabled.

### Steps to reproduce the issue

Open "more info" for an RGBW device and switch to the colour picker.

### What version of Home Assistant Core has the issue?

2024.1.0b2

### Additional information

This looks to be a bug in `@material/web` 1.1.0. I've reported the issue upstream in https://github.com/material-components/material-web/issues/5357. HA updated to use 1.1.1 in #19064. I'm not sure if we can just downgrade again without extra changes as #18983 has now been merged which sounds like it might depend on 1.1.1 (although I can't be sure from the discussion on there).

**Comment by silamon** [comment]
Nice find. I guess instead of downgrading, it might be better to just force disabled to false if it's not provided in ha-labeled-slider:

https://github.com/home-assistant/frontend/blob/6b5e9bf87c0764dff8555be2881947b9a5eeeee2/src/components/ha-labeled-slider.ts#L13-L15
```ts 
  @property({ type: Boolean }) public disabled = false; 
  @property({ type: Boolean }) public required = true;
```

If you want, you can open a pull request to fix.

**Comment by silamon** [comment]
I've went ahead and opened a PR, since stable will be released tomorrow.
