### ISSUE TITLE
"Edit dashboard" button is needlessly hidden behind kebab menu

### ISSUE THREAD

**Issue by lindhe** [home-assistant/frontend#19219]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The "Edit dashboard" button is needlessly hidden from view. The user has to click a non-descript kebab menu to reveal this single item:

![Screenshot from 2024-01-01 17-52-58](https://github.com/home-assistant/frontend/assets/7773090/01d0307b-defa-472f-afb3-a430a8c19159)

### Describe the behavior you expected

Since this is only a single item, I would expect to be able to click the button directly instead of going through a menu.

### Steps to reproduce the issue

1. Go to a dashboard.
2. Look at the top right corner.

### What version of Home Assistant Core has the issue?

2023.12.4

### In which browser are you experiencing the issue with?

Firefox 120.0

### Which operating system are you using to run this browser?

Ubuntu 22.04

**Comment by lindhe** [comment]
Maybe it's some sort of dynamic thing that is not smart enough.

This is what it looks like on my laptop:

![image](https://github.com/home-assistant/frontend/assets/7773090/efdc6435-634c-456c-8ec7-b25df7e255e3)

And in mobile view:

![image](https://github.com/home-assistant/frontend/assets/7773090/fa905753-fccb-4de4-a2ae-4a2e98ffecf8)


As you can see, the kebab menu is useful when the space is tight. But keeping a single menu item in the wide view seems bad.

**Comment by ildar170975** [comment]
This is not a bug report & should be posted in "Discussions".

> As you can see, the kebab menu is useful when the space is tight. But keeping a single menu item in the wide view seems bad.

Hard to believe but some people even have to scroll the menu:

![image](https://github.com/home-assistant/frontend/assets/71872483/5d4d1c4b-70b2-4ddc-ac3e-de4335916e74)

Also, the "kebab menu" may have other available buttons:

![image](https://github.com/home-assistant/frontend/assets/71872483/060b65ff-b37f-453f-b1cc-7a463d99fec5)

**Comment by ChristophCaina** [comment]
question: how can I get the "refresh" option here? ^^

**Comment by lindhe** [comment]
> This is not a bug report & should be posted in "Discussions".

Thanks for trying to keep down the volume of Issues, that's probably needed.

Frequently, people disagree about what is a bug or not, because it is hard to say objectively and people may have different perspectives. One definition of "bug" that I like is that it is some functionality that does not behave as the authors/owners intended. Do you think that the intention was for the kebab menu to sometimes hold only a single item? I do not think that was the intention, thus it is a bug in my eyes.

> ![image](https://private-user-images.githubusercontent.com/71872483/293605929-5d4d1c4b-70b2-4ddc-ac3e-de4335916e74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODYwOTYsIm5iZiI6MTcwNDE4NTc5NiwicGF0aCI6Ii83MTg3MjQ4My8yOTM2MDU5MjktNWQ0ZDFjNGItNzBiMi00ZGRjLWFjM2UtZGU0MzM1OTE2ZTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA4NTYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMzVlNjY1ZGE0NWNmYjFhMzZkYmU5MTdmYmI3ZDAzNjZlOWE4MjNiMGRkOGZkYjhhOTM3YzBjYTgzYWE1YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YInCLr2s8kOBkjhyII-eF1HLgPWicjzpu2avYQM1qwg)

Your image here highlights another point that I hadn't noticed before: why are the "Search" and "Assist" elements not collapsed into the menu when it's cramped on space? If the logic for hiding menu elements dynamically is rewritten, maybe that can also be taken into consideration.

> Also, the "kebab menu" may have other available buttons:
> 
> ![image](https://private-user-images.githubusercontent.com/71872483/293605992-060b65ff-b37f-453f-b1cc-7a463d99fec5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODYwOTYsIm5iZiI6MTcwNDE4NTc5NiwicGF0aCI6Ii83MTg3MjQ4My8yOTM2MDU5OTItMDYwYjY1ZmYtYjM3Zi00NTNmLWIxY2MtN2E0NjNkOTlmZWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA4NTYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MGY3YWE3OTJlNGRkZDdiZjY4N2Y5OGVmNTM2ZDA1NmEzMzEyYzZlMGQ3NjVkMDUwOGI4YTg5NjUzNDA5NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w6jr_ZkWz8miR7UjQuYIoPLxRldQlSKJ5BK3WAassgY)

Thanks for clarifying. I suspected that was the case, but I did not know how to add them. In the example you show, I think it is very useful to hide the items inside a menu – because there are multiple elements! The issue I try to highlight is that the menu sometimes only holds a single element. And since the menu button itself is a single element, the menu button could be replaced by that single element and thus saving us a click every time the element is used.

I would probably expect the menu to fully disappear when there is plenty of space and only appear when the space is so cramped that _at least two_ elements should be hidden. Hiding a single element saves no space and is useless.

I know little of how the frontend is made, so I really have no idea if this is a very hard thing to accomplish or a very easy thing. But I hope someone more knowledgeable than me can help explain that. If the burden of implementing a more dynamic menu is very high, it might not be worth the effort. But if it's relatively easy, I think this improvement is a no-brainer.

**Comment by karwosts** [comment]
> question: how can I get the "refresh" option here? ^^

Refresh is for YAML mode dashboards. It's for when you modify the yaml and need to reload to see the changes. 

It wouldn't do anything for storage mode dashboard, which is why you don't see it.

**Comment by steverep** [comment]
@matthiasdebaat can you comment on the UX of the single menu item?  I guess I tend to agree that if a menu is only going to have 1 item, we should just make it the button itself unless the item is destructive or needs a complex label.  Otherwise it's just extra unnecessary clicks.

**Comment by matthiasdebaat** [comment]
> @matthiasdebaat can you comment on the UX of the single menu item? I guess I tend to agree that if a menu is only going to have 1 item, we should just make it the button itself unless the item is destructive or needs a complex label. Otherwise it's just extra unnecessary clicks.

There are two reasons why we use an overflow menu:
1. When there are more icon buttons to display than can fit.
2. The single icon button needs a label so that a user can understand it.

A few icons require no explanation, including the pen icon. I think we can drop the overflow menu on larger screens.

**Comment by ildar170975** [comment]
Also, the "Edit" button should not be displayed for yaml-driven dashboards:

![image](https://github.com/home-assistant/frontend/assets/71872483/403fb161-3794-4234-9cdb-2996af747366)

since it just causes this msgbox:

![image](https://github.com/home-assistant/frontend/assets/71872483/5e7fa115-46cf-4a27-a61d-ad36f082ee09)
