### ISSUE TITLE
iPad IOS companion app broken with recent update

### ISSUE THREAD

**Issue by Joshbloam** [home-assistant/frontend#19213]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Woke up this morning to my dashboard iPad IOS companion app broken with the recent app store update from 2023.7 to 2023.12. I have tried clearing cache, uninstall/re-install, all the usual stuff. The companion app will just not open.

![ipad-fail](https://github.com/home-assistant/frontend/assets/10256258/51d264c9-3764-4e05-a1fa-6abdca994aab)

Apple iPad Air
IOS 12.5.7 
IOS companion app updated to v2023.12 overnight. (most recently worked with 2023.7)

Home Asisstant
Core: 2023.12.4
Supervisor: 2023.12.0
Operating System: 11.2
Frontend: 20231208.2

### Describe the behavior you expected

IOS App should open as normal.

### Steps to reproduce the issue

1. Download HA app from IOS store
2. Open HA App
3. App crashes and exists immediately.
...

### What version of Home Assistant Core has the issue?

2023.12.4

### What was the last working version of Home Assistant Core?

2023.12.4

### In which browser are you experiencing the issue with?

IOS companion app v2023.12 (most recently worked with 2023.7)

### Which operating system are you using to run this browser?

IOS 12.5.7 - Apple iPad Air

**Comment by karwosts** [comment]
This is probably more appropriate here: https://github.com/home-assistant/iOS/

**Comment by Joshbloam** [comment]
Got it, thanks.
