### ISSUE TITLE
Device "Add to Dashboard" button non

### ISSUE THREAD

**Issue by sandymac** [home-assistant/frontend#19228]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I am unable to add a colllections of sensors via the Device "Add to Dashboard" button

![image](https://github.com/home-assistant/frontend/assets/1621917/f4ba20f1-8964-45d3-ab5a-870e7a303e58)

### Describe the behavior you expected

I expect a wizard to help me add a list of sensors to a dashboard.

### Steps to reproduce the issue

1. On Mobile (android), Chrome or Firefox (Windows) navigate to Settings > Devices > an Integration > a Device
2. Click "Add to Dashboard"
3. ... nothing happens
...

### What version of Home Assistant Core has the issue?

2023.12.4

### In which browser are you experiencing the issue with?

Chrome 120.0.6099.130 Windows, Firefox 121.0 Windows, Android app

### Which operating system are you using to run this browser?

Windows 11 Home 23H2, Android 14

### Additional information

I have launched HA in safe mode with no change in behavior on Chrome.

**Comment by karwosts** [comment]
Do you see errors in the browser console?

Is your default view an autogenerated view, or something you created?

**Comment by sandymac** [comment]
@karwosts Chrome shows the lines below in the console when I click the 'Add to Dashboard' button.

When I'm clicking that button it is in the Settings > Devices > Integrations > Devices view and not a dashboard.

That said my default dashboards is currently autogenerated with the energy hidden: `type: original-states 
hide_energy: true`

Chrome Console Log lines:
`hui-dialog-select-view.ts:108 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at F.value (hui-dialog-select-view.ts:108:32)
    at F.update (lit-element.ts:160:24)
    at F.performUpdate (reactive-element.ts:1329:14)
    at F.scheduleUpdate (reactive-element.ts:1261:17)
    at F._$Ej (reactive-element.ts:1233:25)
value @ hui-dialog-select-view.ts:108
update @ lit-element.ts:160
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
_ @ reactive-element.ts:931
A @ lit-element.ts:115
F @ hui-dialog-select-view.ts:32
C @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
(anonymous) @ make-dialog-manager.ts:78
Promise.then (async)
c @ make-dialog-manager.ts:77
(anonymous) @ make-dialog-manager.ts:162
r @ fire_event.ts:76
n @ show-select-view-dialog.ts:23
d @ add-entities-to-view.ts:109
await in d (async)
value @ ha-device-entities-card.ts:229
handleEvent @ lit-html.ts:2018
log-message.ts:37 
        
        
       GET https://[a host name].ui.nabu.casa/unknown/src/lit-element.ts 404 (Not Found)
(anonymous) @ stacktrace-gps.js:37
r @ stacktrace-gps.js:23
(anonymous) @ stacktrace-gps.js:218
_get @ stacktrace-gps.js:195
(anonymous) @ stacktrace-gps.js:289
findFunctionName @ stacktrace-gps.js:287
(anonymous) @ stacktrace-gps.js:272
Promise.then (async)
(anonymous) @ stacktrace-gps.js:267
pinpoint @ stacktrace-gps.js:266
(anonymous) @ stacktrace.js:113
(anonymous) @ stacktrace.js:108
(anonymous) @ stacktrace.js:107
fromError @ stacktrace.js:105
t @ log-message.ts:37
(anonymous) @ logging-mixin.ts:66
Show 13 more frames
Show less
log-message.ts:37 
        
        
       GET https://[a host name].ui.nabu.casa/unknown/src/reactive-element.ts 404 (Not Found)`

**Comment by silamon** [comment]
I can reproduce this one with demo integration.

**Comment by karwosts** [comment]
Fixed by #19267

**Comment by karwosts** [comment]
Just to be clear, the fix here is to show a better error message, but just FYI you can't add cards to an autogenerated dashboard, those are fixed. 

You would need to have a user configured dashboard to add cards to it.

**Comment by sandymac** [comment]
I will revisit this behavior after the next HA updates roll out to me.

I was not even getting to a point where I could choose one of my custom dashboards. I'm aware of this aspect.

> You would need to have a user configured dashboard to add cards to it.
