### ISSUE TITLE
CalDAV - Integration via Frontend is not the same as manual

### ISSUE THREAD

**Issue by Shwamp** [home-assistant/frontend#19221]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If you try to add this integration via the front end it is mandatory for username, this is not true with the Manual configuration.

Username should be optional / same as the manual integration

https://www.home-assistant.io/integrations/caldav/[https://www.home-assistant.io/integrations/caldav/](url)

### Describe the behavior you expected

Same options as Manual configuration.

### Steps to reproduce the issue

1. Add integration CALdev from front end without username as the dokumentation states
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.12.4

**Comment by karwosts** [comment]
This should be filed in home-assistant/core for caldav integration. 

Integration setup via config flow is driven based on the spec defined in the integration backend. So any changes would need to be there.
