### ISSUE TITLE
Missing translation in lokalise - addons store - more words

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#19236]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hello,
found missing words in translation for lokalise (screenshot attached).

![AddOnsStore_more](https://github.com/home-assistant/frontend/assets/61636045/96ce107a-09d1-4e96-ba9c-dd56ec54f3ae)

### Describe the behavior you expected

Please add missing words to translation in lokalise.
Thank you in advance.

### What version of Home Assistant Core has the issue?

2024.1.0b3

### What was the last working version of Home Assistant Core?

not relevant

**Comment by karwosts** [comment]
Reported many times before.

**Comment by misa1515** [comment]
@karwosts "No repositories" wasn´t reported.

**Comment by karwosts** [comment]
I can't find that string anywhere in frontend anyway... so I guess it must be from some other repo...

**Comment by karwosts** [comment]
Ok sorry I found it in the hassio folder, wasn't familiar with that area.

I can let it reopen for that. 

https://github.com/search?q=org%3Ahome-assistant+%22No+repositories%22&type=code

**Comment by karwosts** [comment]
This is now duplicating with your other issue #18235, so suggest please either close that one and combine it with this, or crop your image to remove the items that you've duplicated in the other issue.

Otherwise it is confusing which issues are tracking which strings.

**Comment by misa1515** [comment]
thank you (for work and explanation) - now https://github.com/home-assistant/frontend/issues/18235 closed.

**Comment by misa1515** [comment]
not yet finished
