### ISSUE TITLE
Missing translation in lokalise - new automation - "Logbook", "Logger", "Recorder"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#19245]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hello,
found missing words in translation for lokalise (screenshot attached).

![Snag_5f1cd0](https://github.com/home-assistant/frontend/assets/61636045/ea9f9cb8-5a03-4c30-840d-67daa66b50bc)

### Describe the behavior you expected

Please add missing words to translation in lokalise.
Thank you in advance.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.1.0b3

### What was the last working version of Home Assistant Core?

not relevant

**Comment by frenck** [comment]
This isn't a frontend issue, but provided by the Core.

../Frenck
