### ISSUE TITLE
Missing translation in lokalise - log in page - "Show password", "Hidden password"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#19242]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hello,
found missing words in translation for lokalise (screenshot attached).

![ShowPassword](https://github.com/home-assistant/frontend/assets/61636045/b8a71567-7720-4b64-a10a-00405bc605e8)

### Describe the behavior you expected

Please add missing words to translation in lokalise.
Thank you in advance.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.12.3

### What was the last working version of Home Assistant Core?

not relevant

**Comment by Manmit124** [comment]
Can you assign it to me?

**Comment by karwosts** [comment]
Typically we don't assign issues (it is somewhat meaningless), but anyone is welcome to create a PR to fix them.
