### ISSUE TITLE
Missing translation in lokalise - system status - dashboards, recorder

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#19241]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hello,
found missing words in translation for lokalise (screenshot attached).

![SystemStatus_more](https://github.com/home-assistant/frontend/assets/61636045/55b90f1b-aeee-408d-a336-0f8fad34339e)

### Describe the behavior you expected

Please add missing words to translation in lokalise.
Thank you in advance.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.12.3

### What was the last working version of Home Assistant Core?

not relevant

**Comment by karwosts** [comment]
I don't know where this is from, but I don't think it is part of the frontend.

**Comment by karwosts** [comment]
I looked for this a little bit, and what I believe this is is that `Dashboards` is the core translation for `component.lovelace.title`, and `Recorder` is the core translation for `component.recorder.title`. 

I _think_ these come from the `title` key of the manifest.json for each respective component, but I'm not exactly sure if or how these get exposed to Lokalize. 

But I do think it would be backend that is responsible for translating these keys.

**Comment by silamon** [comment]
Feel free to close this one, since it's provided by core. It falls back to the manifest names from what I can tell and those aren't provided to lokalise.
