### ISSUE TITLE
Cut text of menu items in user settings

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#19247]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hello,
found cuted menu items text (showed on attached screenshots).

Tested on more web browsers - still showed same issue

Edge (EN and SK language) 121.0.2277.4 (oficial build) dev (64-bit version),
Firefox 123.0a1 (2023-12-31) (64-bit version),
Chrome 120.0.6099.130 (oficial build) (64-bit version).

### Describe the behavior you expected

Please set like visible whole menu item text.
Thank you in advance.

### What version of Home Assistant Core has the issue?

2024.1.0b4

### What was the last working version of Home Assistant Core?

don´t know

### In which browser are you experiencing the issue with?

Google Chrome 120.0.6099.130 (oficial build) (64-bit version)

### Which operating system are you using to run this browser?

Edge (EN and SK language) 121.0.2277.4 (oficial build) dev (64-bit version), Firefox 123.0a1 (2023-12-31) (64-bit version),

Edge (EN)
![Web_Edge_EN](https://github.com/home-assistant/frontend/assets/61636045/80d7b720-b3a0-43e9-99a1-389a21eed746)

Firefox (SK)
![Web_Firefox](https://github.com/home-assistant/frontend/assets/61636045/8091fae7-afe2-4aaf-8558-adccebf36df9)

**Comment by maxistviews** [comment]
![image](https://github.com/home-assistant/frontend/assets/17325179/2d279244-ed36-4ceb-830b-a9999fee9553)
I am seeing some similar cut offs with the dropdown menus

**Comment by ildar170975** [comment]
Confirm "Time zone" glitch.

But this is probably not what the OP asked for.
The OP wants to see the text fully seen in input fields:
![image](https://github.com/home-assistant/frontend/assets/71872483/af366dba-eee9-4d5d-b44f-75da3a54f034)
which is only possible by increasing their width.

So, the "Time zone" glitch deserves a dedicated issue.
