### ISSUE TITLE
Missing translation in lokalise - notification - "New devices discovered", etc.

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#19243]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hello,
found missing words in translation for lokalise (screenshot attached).

![Notofications_NewDevicesDiscovered](https://github.com/home-assistant/frontend/assets/61636045/b790ea96-df07-4874-bb8c-a672751f4c4d)

### Describe the behavior you expected

Please add missing words to translation in lokalise.
Thank you in advance.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.1.0b3

### What was the last working version of Home Assistant Core?

not relevant

**Comment by karwosts** [comment]
Not from frontend.
