### ISSUE TITLE
Google Nest Outdoor Floodlight Camera streaming preview is a black screen with grey "blob"

### ISSUE THREAD

**Issue by MarkTarry** [home-assistant/frontend#19251]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When building a dashboard, which includes entity cards for various Google Nest cameras, the card for a [Google Nest Cam with Floodlight](https://store.google.com/gb/product/nest_cam_floodlight?hl=en-GB) fails to render an image from the stream

![image](https://github.com/home-assistant/frontend/assets/155492324/3668cac9-e363-4aaf-8f22-e3a1559968df)

There is a similar issue when listing the camera entities to add to the dashboard:
![image](https://github.com/home-assistant/frontend/assets/155492324/5b7fd651-d1cf-4430-82ee-dbd43ca3d8a8)

The camera feed itself does work - when I click on the "Back Garden Camera" card, I can see a video feed:
![image](https://github.com/home-assistant/frontend/assets/155492324/3adfa6d2-310f-4131-b7aa-c22e0ebab83f)

### Describe the behavior you expected

All camera cards should show a preview image from the stream.

## Pre-Requisites

Have access to a Google Nest account with one or more Nest cameras installed. 

In the original instance, it appears that the issue was isolated to a Google Nest Cam with Floodlight. I'm unable to confirm if this is the only device type affected.

## Steps

1. Add Nest integration to HA server - following steps in [Integrations: Google Nest](https://www.home-assistant.io/integrations/nest#configuration)
2. Set up a dashboard within HA
3. Edit dashboard > Add Card > By Entity > search for `camera`
4. Check the image preview for each camera in the search results
5. Select all matching entities
6. Click "Continue"
7. Click "Add to Dashboard"

### What version of Home Assistant Core has the issue?

core-2023.12.4, frontend-20231208.2

### In which browser are you experiencing the issue with?

Google Chrome 120.0.6099.130

### Which operating system are you using to run this browser?

Windows 10 Home (19045.3803)

### State of relevant entities

```txt
camera.back_garden

streaming	

access_token: ***REDACTED***
model_name: Camera
brand: Google Nest
frontend_stream_type: web_rtc
entity_picture: /api/camera_proxy/camera.back_garden?token=***REDACTED***
friendly_name: Back Garden Camera
supported_features: 2
```

### Problem-relevant frontend configuration

Dashboard configuration:

```yaml
views:
  - title: Home
    cards:
      - type: picture-entity
        entity: camera.front_door
      - type: picture-entity
        entity: camera.conservatory
      - type: picture-entity
        entity: camera.back_garden
```

### Javascript errors shown in your browser console/inspector

```txt
No errors reported in console
```

**Comment by karwosts** [comment]
If you grab your entity  picture field: (`/api/camera_proxy/camera.back_garden?token=***REDACTED***`)

and tack it onto the end of your HA url in a web browser, does it look the same?
e,g.:
``` 
http://homeassistant.local:8123/api/camera_proxy/camera.back_garden?token=***REDACTED***
```

**Comment by MarkTarry** [comment]
Yes:
![image](https://github.com/home-assistant/frontend/assets/155492324/58bc0096-50b8-437c-a4b5-fd64c831df4e)

**Comment by MarkTarry** [comment]
I figured that would be the case shortly after posting the above. Thanks for reviewing the issue.

I've now raised this as https://github.com/home-assistant/core/issues/107178
