### ISSUE TITLE
State of Push Notification switch displaying incorrectly until page refresh

### ISSUE THREAD

**Issue by jonnywright** [home-assistant/frontend#19260]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When enabling push notifications from web browser, pressing Cancel on the Device Name dialog does not turn the switch off. Leaving the Profile page and returning to it resolves the issue.

https://github.com/home-assistant/frontend/assets/4968203/2f203743-279e-4ef6-9777-25060d8aaf6e

### Describe the behavior you expected

The switch should revert to the switched off state.

### Steps to reproduce the issue

With push notifications disabled...
1. Switch the Push Notifications switch to the on position
2. Click Cancel on the "What should this device be called?" dialog

### What version of Home Assistant Core has the issue?

2023.12.0

### In which browser are you experiencing the issue with?

Google Chrome 120.0.6099.130

### Which operating system are you using to run this browser?

Windows 11 22H2 (22621.2861)

**Comment by MrBlackGhostt** [comment]
@jonnywright i want to work on this issue can you assign it to me

**Comment by karwosts** [comment]
As far as I know users do not have sufficient permission to assign their issues. Anyway anyone is free to work on a pull request for any issue, we haven't typically assigned them to users.

**Comment by jonnywright** [comment]
> @jonnywright i want to work on this issue can you assign it to me

As @karwosts mentioned, I am unable to assign this issue to anyone as I am not an admin. But if you do resolve the issue and pull request it against this issue, if it get merged then the issue should close. Good luck!
