### ISSUE TITLE
Editing a Todo list item with a due date (but no time) + saving it immediately changes the duedate by -1

### ISSUE THREAD

**Issue by maxistviews** [home-assistant/frontend#19270]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

You can click on a todo list item to edit it, when you click "save item" dialogbox closes, but the date is changed to be a day earlier. Changing the description does not stop this bug.

### Describe the behavior you expected

I would expect that clicking save doesnt do anything if I didnt change anything. 
The correct behaviour only occurs if I add a time to the item, but this isnt always wanted.

### Steps to reproduce the issue

1. Create a new todo list item, but dont add a time.
2. Open the todo list item
3. Save the item
4. Now the date will be the day before.

### What version of Home Assistant Core has the issue?

2024.1.0

### In which browser are you experiencing the issue with?

Microsoft Edge Version 120.0.2210.91 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 22H2 19045.3803

### Additional information

This is probably because of how the due date is saved without the time. Because when I do set the time, the bug no longer occurs. Sometimes I dont want the time for my due dates.

**Comment by bramkragten** [comment]
Is the timezone of your HA system different that of your UI? What is your timezone set to?

**Comment by maxistviews** [comment]
Set to `Use your local time zone (America/Toronto) 1/3/2024 3:52 PM`

**Comment by bramkragten** [comment]
I'm having a hard time reproducing this (I love timezone issues!) in all my tests it works as expected, also with different timezones... 🤔

**Comment by bramkragten** [comment]
What integration is the todo list you are trying to add something to from?

**Comment by bramkragten** [comment]
Found it :-)
