### ISSUE TITLE
Risco utf8 error

### ISSUE THREAD

**Issue by liberomic** [home-assistant/frontend#19283]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hi all,

I use the latest version of Home Assistant

    Core 2023.12.3
    Supervisor 2023.11.6
    Operating System 11.2
    Frontend 20231208.2

Risco with local integration
Logger: homeassistant.components.risco
Source: components/risco/init.py:113
Integration: Risco (documentation, issues)
First occurred: (589 occurrences)
Last logged: 08:46:49

Error in Risco library: 'utf-8' codec can't decode byte 0x92 in position 32: invalid start byte
Error in Risco library: Timeout in command: CLOCK

Regards

### Describe the behavior you expected

Risco with local integration

### Steps to reproduce the issue

1.Risco with local integration

### What version of Home Assistant Core has the issue?

2024.1.0

**Comment by karwosts** [comment]
This is a home-assistant/core issue, not a frontend issue. Please file your ticket there.
