### ISSUE TITLE
Mobile Alerts/TFA Dostmann not working since 2024.1

### ISSUE THREAD

**Issue by newslettersns2000** [home-assistant/frontend#19299]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The Mobile Alerts/TFA Dostmann is not working since 2024.1

### Describe the behavior you expected

all devices and entities from Mobile Alerts/TFA Dostmann are not reachable

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

since 2024.1.0

### What was the last working version of Home Assistant Core?

latest 2023

### In which browser are you experiencing the issue with?

Chrome or Iphone/Safari

### Which operating system are you using to run this browser?

Win10 oder Ios

### State of relevant entities

```txt
This entity is no longer provided by the mobile_alerts integration.
```

**Comment by karwosts** [comment]
I don't think this is related to frontend, please file this in home-assistant/core.

**Comment by NaatuMik** [comment]
I experienced exactly the same issue. The first update in 2024 broke these sensors integration.

**Comment by Sput75** [comment]
Exactly same problem here too. Updated from 2023.4 to 2024.2 and all probes are now unreachable.

**Comment by karwosts** [comment]
Off topic for frontend.
