### ISSUE TITLE
Macbook App Cannot Scroll with Mouse or Cannot Copy text

### ISSUE THREAD

**Issue by NuvioDev** [home-assistant/frontend#19303]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I am trying to use code editor, visual studio code, or any other editor on the Macbook Home Assistant app but the problem is whenever I try to scroll with my bluetooth mouse or copy&paste with my keyboard it does not work. Whenever I switch to the browser they all work.

### Describe the behavior you expected

I should be able to scroll on text editors with my bluetooth mouse or copy & paste to the text edit areas with my keyboard on Macbook app.

### Steps to reproduce the issue

1. Open the Macbook Home Assistant app
2. Open any editor or text edit area 
3. Scroll with a bluetooth mouse (it won't work)
4. Try to copy any text from the text editor, or try to paste any text into the editor via Cmd + C / V (it won't work)
...

### What version of Home Assistant Core has the issue?

2024.1.0

### Which operating system are you using to run this browser?

macOS 14.2.1

**Comment by karwosts** [comment]
You may also want to check on https://github.com/home-assistant/iOS, which manages the mac and ios apps.

**Comment by NuvioDev** [comment]
Thanks. Created an issue there. Closing this one.

https://github.com/home-assistant/iOS/issues/2515
