### ISSUE TITLE
To Do List - struckthrough items hard to read

### ISSUE THREAD

**Issue by smarecki** [home-assistant/frontend#19312]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

First of all, welcome to the New Year.
I'm writing about changes in the "To-do list", specifically the lines for taged completed items. They make items become unreadable. They are harder to find and ummark again. This is what happens with a shopping list. 
PS: I have 4 shopping lists with repeating items for 4 different shops.
PS: If I wrote in the wrong section, I'm sorry. This is my first post here.

### Describe the behavior you expected

Maybe you can add options when creating a list list (with or without deletions).

### Steps to reproduce the issue

1. Create To Do list
2. add item
3. mark item
...

### What version of Home Assistant Core has the issue?

2024.1

### What was the last working version of Home Assistant Core?

2023.12

**Comment by karwosts** [comment]
Are you suggesting that you don't like that the completed item text has the strikethrough line through it? Couldn't quite understand the issue.

**Comment by smarecki** [comment]
Yes. Sorry for my English - I used translator.

**Comment by mcfly2283** [comment]
I have also problems with it. If you are using it as a shopping list and you want to readd the items, it is not good to read.

Fixed it for me with cardmod:

`card_mod:
  style: |
    .completed .summary {  text-decoration: none !important; 
    } `

**Comment by smarecki** [comment]
Hello
The annoying thing is that when I check an item as completed, it scrolls the page down and vice versa. I would like the shopping list to remain as it was in 2023.12. was great.

**Comment by mcfly2283** [comment]
> Hello card mod does not work for me. I don't know why. I added card-mod.js to resources and paste code to yaml card configurayion.
> 
> The annoying thing is that when I check an item as completed, it scrolls the page down and vice versa. I would like the shopping list to remain as it was in 2023.12. was great.

Oh, sorry this is only a fix for the Line-through of the Font feature of checked items, not for the main problem with following Item.

**Comment by smarecki** [comment]
ok, then how to turn off struckthrough lines.

**Comment by mcfly2283** [comment]
> ok, then how to turn off struckthrough lines.

With code above applied to the Card. Please check how to deal with Card-Mod.
