### ISSUE TITLE
Disabling a Config Entry causes Entities to move into Unavailable state instead of disappearing

### ISSUE THREAD

**Issue by codyc1515** [home-assistant/frontend#19317]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Previously, when a Config Entry was Disabled the entities associated would be removed from the Lovelace dashboard and be hidden accordingly. Now, they are being moved out of their Area's into the generic part of the Dashboard and marked as Unavailable.

### Describe the behavior you expected

The disabled config entry entities should not show in my default dashboard.

### Steps to reproduce the issue

1. Mark config entry as disabled
2. Go to default lovelace dashboard
3. Can see many unavailable entities showing at the bottom of the dashboard

### What version of Home Assistant Core has the issue?

core-2023.9.3

### What was the last working version of Home Assistant Core?

Maybe July or August 2023

### In which browser are you experiencing the issue with?

Edge, Chrome, Safari

### Which operating system are you using to run this browser?

macOS latest, Windows 10, iOS 17.3

### State of relevant entities

![image](https://github.com/home-assistant/frontend/assets/50791984/4cbc592c-93b4-47ee-944f-7c447e43b56b)

### Problem-relevant frontend configuration

In example above, both config entries have been recently disabled. On restart, they will be hidden again from the default dashboard (as expected) but not ever before a restart of core.

### Additional information

Not sure if this is a core or frontend issue but the issue manifests itself in frontend, so have lodged here. I have lodged a [separate core ticket](https://github.com/home-assistant/core/issues/101340).
```[tasklist]
### Tasks
```

**Comment by ste-fle** [comment]
Also just noticed this behavior in 2024.04.01, really annoying. Did you find any solution so far?
