### ISSUE TITLE
Cover entity's Icon not tracking position Open/Closed - Window Covering Horizontal Slats

### ISSUE THREAD

**Issue by tommyjlong** [home-assistant/frontend#19310]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

[2024.1.1] The entity icon for a cover, namely a cover based on ZWave/HA "Window Covering" currently always has state of` unknown`, and the `current_tilt_position` is kept current, but the entity's Icon is always showing as open.
Here one can see the "Tilt" down is grayed out meaning the front end is tracking the current tilt position = 0, but the icon shows as open.

![image](https://github.com/home-assistant/frontend/assets/35182132/a770341c-ce70-487e-913d-b9f5de417b2c)

Reference Core Issue on this subject - https://github.com/home-assistant/core/issues/106439/#issuecomment-1879899733

### Describe the behavior you expected

Expect the Window Icon to be shown as closed

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.1.1

**Comment by raman325** [comment]
no need for two issues to track this. Closing this in favor of the issue in core
