### ISSUE TITLE
Comments in same line not correctly interpreted in config.yaml after update to core 20245.1.1

### ISSUE THREAD

**Issue by ullibak** [home-assistant/frontend#19311]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I defined a sensor in configuration.yaml that has been working for a long time:

sensor:
  - platform: template 
    sensors:   
      strom_tarif:
        friendly_name: "Strom Tarif"
        unit_of_measurement: CHF/kWh
        value_template:  "
            {% if now().weekday() >= 0 
                and now().weekday() < 5 
                and now().hour >= 7
                and now().hour < 20 %} 0.3334  # This is a comment
            {% elif now().weekday() == 5 
                and now().hour >= 7 
                and now().hour < 13 %} 0.3334  # This is a comment 
            {% else %} 0.2719                           # This is a comment
            {% endif %}"

after updating to core 2024.1.1 yesterday, i got the error message that the sensor has a non-numeric value. After deleting the comments in the same line as the numbers, everything worked fine again. 
I was able to reproduce the behaviour by adding the comments again.  
Apparently, comments in the same line as a number are not interpreted correctly anymore.

### Describe the behavior you expected

I expected that comments are ignored when interpreting the yaml file.

### Steps to reproduce the issue

1. define a sensor and give it a numerical value
2. add a comment after the numerical value
3. restart Home Assistant and inspect the entity
...

### What version of Home Assistant Core has the issue?

2024.1.1

### What was the last working version of Home Assistant Core?

2023.12.4

### Which operating system are you using to run this browser?

Windows 11

**Comment by ullibak** [comment]
...sorry, typo: caption of issue should be "after update to core 2024.1.1" instead of after "update to core 20245.1.1"

**Comment by ildar170975** [comment]
1.  The posted code is not properly formatted - so it is impossible to analyze it. Compare your post with other issues containing a code. 
2. If you trying to use “#” inside a template - this is wrong. Template is a string. You cannot comment a part of a string.

**Comment by ildar170975** [comment]
Besides, this “issue” is not related to Frontend.

**Comment by karwosts** [comment]
Not a frontend issue.
