### ISSUE TITLE
Heater off switch removed from widget

### ISSUE THREAD

**Issue by lil5** [home-assistant/frontend#19322]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Previous versions had the option to turn on/off the heater now it's replaced by useless plus mins buttons (the circular range input does the same thing, adjusting the temp).

![Screenshot 2024-01-08 at 10 50 46](https://github.com/home-assistant/frontend/assets/17646836/bfbb1328-888a-4847-b74e-f4696985745c)

### Describe the behavior you expected

I found an example of how it used to work:

![](https://community-assets.home-assistant.io/original/4X/9/8/c/98c5853b1aa22a3f83e204a9407822298845afaf.png)

My heater would only have the fire icon (on) and power icon (off)

### Steps to reproduce the issue

1. open ha
2. go to a heater widget
3. try to turn it off in one click
4. Because there is no way of doing that you need to click the options button
5. Then the "Mode" button

https://github.com/home-assistant/frontend/assets/17646836/d7650dd7-f0eb-4655-8fa4-140715b680ad

### What version of Home Assistant Core has the issue?

2024.1.2

### Which operating system are you using to run this browser?

macOS 14.2.1

### State of relevant entities

```txt
`climate.princess_smart_infrared_heater`


hvac_modes: off, heat
min_temp: 0
max_temp: 37
target_temp_step: 1
current_temperature: 21
temperature: 24
friendly_name: Princess Smart Infrared Heater
supported_features: 1
```
```


### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

**Comment by matthiasdebaat** [comment]
You can add this feature while editing the card.

![CleanShot 2024-01-08 at 11 12 36](https://github.com/home-assistant/frontend/assets/20203284/54299c71-b92c-443d-ab62-ca68ce875b23)

**Comment by lil5** [comment]
Took me some time to figure out how you got there:

Dashboard -> vertical option menu -> Edit Dashboard -> "Edit" button of device card
