### ISSUE TITLE
Missing “display precision” for Shelly TRV valve position entity

### ISSUE THREAD

**Issue by skydado** [home-assistant/frontend#19328]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

impacted entities: all SHELLY TRV valve position entities: number.mytrvname_valve_position
The “display precision” field in the entity UI config card is not present, while it is in all the other TRV entity types.

### Describe the behavior you expected

I expect to define the “display precision” for the valve_position entities too.

### Steps to reproduce the issue

1. Go to the entity config page: Display Precision missing

### What version of Home Assistant Core has the issue?

all versions since I use it

**Comment by karwosts** [comment]
I don't believe any `number` entities ever have configurable display precision, only `sensor` entities.

**Comment by skydado** [comment]
You're right, I've checked a couple of other `number` entities and none of them have display precision. Why this choice?

**Comment by karwosts** [comment]
I couldn't say, I guess core only implemented this for `sensor`. But anyway I think changing this is out of scope for the frontend, as it would require core updates to enhance the number domain to support it. 

Would suggest making a feature request on the community forums if this is something you're interested in, but I think this ticket probably ought to be closed for now.
