### ISSUE TITLE
 Trend helper from UI is not working

### ISSUE THREAD

**Issue by Sived80** [home-assistant/frontend#19323]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The trend helper only works if you manually enter it in the config.yaml, if configured by UI it always remains unknown

### Describe the behavior you expected

Create the trend helper and see the value change.

### Steps to reproduce the issue

1. settings, devices and services, helpers
2. I create the helper following the wizard

### What version of Home Assistant Core has the issue?

2024.1.2

**Comment by karwosts** [comment]
Please file in home-assistant/core, for `Trend` integration. Frontend does not control entity states.
