### ISSUE TITLE
Glance card: errors in UI Editor

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#19325]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

1. Add a new Glance card.
2. Switch to yaml.
3. Type this code:
```
type: glance
entities:
  - entity: sun.sun
    show_state: false
```
4. See this error:
```
Visual editor is not supported for this configuration:
Key 'entities.0.show_state' is not expected or not supported by the visual editor.
The provided value for 'entities.0' is not supported by the visual editor. We support (string) but received ({"entity":"sun.sun","show_state":false}).
You can still edit your config in YAML.
```
![image](https://github.com/home-assistant/frontend/assets/71872483/6dd36117-e9db-4b73-8d7d-d243c0ce57fa)

The `show_state` option is officially supported per-entity ( [Docs](https://www.home-assistant.io/dashboards/glance/#options-for-entities)).

### Describe the behavior you expected

No errors

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2024.1

### In which browser are you experiencing the issue with?

Chrome 120.0.6099.200

### Which operating system are you using to run this browser?

Win10x64

**Comment by karwosts** [comment]
This is not an error, it is just telling you that the options you are using are not supported in the visual mode. Many cards have more advanced options that are not included in the visual editor, and it was never intended for every single yaml option to be included in the visual editor. 

While someone could PR to add more capabilities to visual editor here, I don't believe we should file issues just because some are missing, this is working as intended.

**Comment by ildar170975** [comment]
> Many cards have more advanced options that are not included in the visual editor, and it was never intended for every single yaml option to be included in the visual editor.

Agree - only if it is related to custom cards. Yes, many of them either do not have UI editor at all or only for some options.
But this is a standard card, and many beginners use UI mode only.
So, I would suggest to consider this behaviour as a bug.

**Comment by karwosts** [comment]
I'm not talking about custom; even for standard cards, not all yaml options are supported in visual editor, nor were they ever intended to be.

For beginners, UI editor shows some basic level of functionality. For more advanced options, editing in yaml is still required.

**Comment by ildar170975** [comment]
> even for standard cards, not all yaml options are supported in visual editor, nor were they ever intended to be.

May be you are right, I do not use UI editor in general, prefer yaml.
Well, it is up to Dev team then either to close the issue or keep it open...
