### ISSUE TITLE
Thermostat preset drop down inconsistant in behaviour

### ISSUE THREAD

**Issue by msp1974** [home-assistant/frontend#19334]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I maintain a custom integration that uses (amongst others) the climate entity and thus, the thermostat card.

Due to some custom functions on the heating system this supports, it uses custom presets.  In some cases, these custom presets do not maintain, ie after selection of the preset (eg Cancel overrides), the preset returns to None.

On the new thermostat card, if the preset dropdown is enabled in features and this preset is selected, it calls the set preset service twice.  Once when the preset is selected and again when it returns to None a few seconds later.

If you do the same thing via the more info dialog, the service is only called once and ignored for preset None.

Can the new thermostat card be made consistant in behaviour to not call the set preset servixe if the preset value is None to be consistant.

Thanks

### Describe the behavior you expected

Set preset is not called if preset mode value is None

### Steps to reproduce the issue

1. As above
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.1

### What was the last working version of Home Assistant Core?

2023.12

### In which browser are you experiencing the issue with?

All browsers

### Which operating system are you using to run this browser?

Android/Windows

**Comment by karwosts** [comment]
I think the problem is even a bit worse than you describe.

Given that the dropdown allows you to choose which presets to display, one could choose to display for example "Home" and "Eco" in the preset picker. 

Anytime the climate card is displayed and the preset changes to a value that is not one of those values (e.g. "Away") , it will trigger a spurious service call to set the preset to "", and log and display an error toast on the frontend.
