### ISSUE TITLE
Energy Dashboard shows Battery Day Charge as negative value

### ISSUE THREAD

**Issue by firebowl** [home-assistant/frontend#19357]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In the Energy Dashboard, the energy that has been charged into the battery is displayed as negative. However, the actual values are positive.

![image](https://github.com/home-assistant/frontend/assets/73579226/801d2f3a-ee2e-48f2-b975-093616bded33)

![image](https://github.com/home-assistant/frontend/assets/73579226/463f9d19-a5d4-4900-b051-16c0e0848b73)

![image](https://github.com/home-assistant/frontend/assets/73579226/8f525d0e-950d-4bf3-8d2d-eb8b14ef75c6)

### Describe the behavior you expected

I would expect a battery charge to be displayed as a positive value.

### Steps to reproduce the issue

Just configured the values for Battery Charge and Battery Discharge.

![image](https://github.com/home-assistant/frontend/assets/73579226/721ce3d2-a2df-44b5-832b-d1a8e4426f01)

### What version of Home Assistant Core has the issue?

2024.1.2

### In which browser are you experiencing the issue with?

Microsoft Edge Version 120.0.2210.121 (Offizielles Build) (64-Bit)

### Which operating system are you using to run this browser?

Windows 11 Microsoft Windows [Version 10.0.22631.3007]

**Comment by karwosts** [comment]
Believe this is intended. Positive values are inputs to your home energy, and negative values are debits from your home energy. 

Similarly to how energy from the grid is positive, and energy returned to the grid is negative.

**Comment by timaseth** [comment]
I have a similar, should I say 'issue'!
<img width="433" alt="image" src="https://github.com/home-assistant/frontend/assets/60132339/6715a748-28d3-4e80-ac51-9534224d6264">
Energy IN is what is stored in battery - may be from solar or grid (in which case, paid for).
This should be a negative value.
Out indicates energy from the battery to home grid (essentially, free) and this must be marked as positive to balance the equation.
IN - OUT = Effective cost
Just how I view it...

**Comment by tbrasser** [comment]
Same here, I don't have solar, and am testing a simulated battery. I would assume to see charging (into the battery) as consumption, but it shows negative.

**Comment by tbrasser** [comment]
Adding a dummy (always 0) solar production template sensor helped a bit. Only thing that seems to be missing now is my grid export, resulting in all energy out of the battery counted as house consumption.

![Screenshot_2024-03-06-19-07-46-004_io.homeassistant.companion.android.jpg](https://github.com/home-assistant/frontend/assets/2816560/e134ff21-f76b-4df2-acef-9530b8665359)

So is this the intended behavior (and thus my issue is with the simulated grid export of the battery_sim battery I'm testing)?

**Comment by Robinies** [comment]
Is there any update/news on this issue? I feel like I still want my usage to be positive when the battery is charging of the grid. Looking for solutions...

**Comment by AlexanderKryvyakyn** [comment]
Same problem. I just swapped charge and discharge in Energy Home Assistant settings and everything was fine.

**Comment by Kai9555** [comment]
Is there an update here? I also get negative values ​​when charging the battery. In addition, my self-sufficiency is also negative, which cannot be.
![Bildschirmfoto 2024-12-23 um 12 59 17](https://github.com/user-attachments/assets/b61c97d8-acfd-40d2-b2ee-11770d3c6146)

**Comment by jkoljo** [comment]
Looks like this is a closed ticket.

Charging a battery from grid has been designed to be displayed on the "export" side of graph. It's not always intuitive, but on the other hand using battery is like using solar, and so it makes sense that using battery is shown on the positive side.

I think I would prefer that HA would show battery charging as a large spike in the grid import, when charging from grid like you do.

No comment on the self sufficiency.. Looks like a bug related to storing energy in the battery.

**Comment by iamdevnull** [comment]
### 🛠 Warum zeigt das Energie-Dashboard Netzeinspeisung & Batterieaufladung negativ?  

Home Assistant **Energie-Dashboard** stellt **Verbrauch positiv** und **Einspeisung/Batterieladung negativ** dar. Dies ist **korrekt**, da:  
✅ **Verbrauch** (Haus, Netz, Batterie-Entladung) **immer positiv** ist  
✅ **Einspeisung** (Netz, Batterie-Aufladung) **immer negativ** ist  

### 📊 Beispiel:  
- **Hausverbrauch:** 4 kWh  
- **PV erzeugt:** 3 kWh  
  - **1 kWh direkt im Haus verbraucht**  
  - **1 kWh in die Batterie geladen (negativ)**  
- **Batterie entlädt nachts 1 kWh (positiv)**  
- **Netzbezug:** 1 kWh  

💡 **Das Dashboard rechnet alles saldierend:** Was ins Haus fließt, ist positiv, was rausgeht, negativ.

### ⚠ Wichtige Regel: Energiesensoren müssen absolute Werte liefern!  
❌ **Keine Tageswerte – Home Assistant berechnet Zeiträume selbst**  
✔ **State-Class:** `total_increasing` für Zähler, `total` für absolute Werte  
✔ **Kein tägliches Zurücksetzen – das Dashboard macht die Zeitberechnung**  

### ✅ Fazit:  
Kein Fehler – das ist so **designt**.

**Comment by jomach** [comment]
@iamdevnull  ich habe das gleiche Problem: 

<img width="1681" alt="Image" src="https://github.com/user-attachments/assets/93227f48-b469-4356-a1b7-102387aaed6d" />

**Comment by Commodoremdf** [comment]
In Austria, there are energy communities, meaning that in addition to my balcony solar system, I can also source affordable electricity from this community—essentially an extra electricity provider. That’s why I also draw a lot of additional electricity from the socket, and there are daily fluctuations in that as well. Visually, these negative values in the diagram don’t make much sense. At that moment, the battery is just another consumer. When energy is being discharged, it reduces grid consumption and shrinks the corresponding bar in the chart, which is then replaced by the battery’s contribution. That part is actually correct.

It might be how Home Assistant intended it, but that doesn’t matter to me. It would be great if users could decide how this is displayed, rather than having it dictated by someone else.

**Comment by nonamebrand** [comment]
> ### 🛠 Warum zeigt das Energie-Dashboard Netzeinspeisung & Batterieaufladung negativ?
> Home Assistant **Energie-Dashboard** stellt **Verbrauch positiv** und **Einspeisung/Batterieladung negativ** dar. Dies ist **korrekt**, da: ✅ **Verbrauch** (Haus, Netz, Batterie-Entladung) **immer positiv** ist ✅ **Einspeisung** (Netz, Batterie-Aufladung) **immer negativ** ist
> 
> ### 📊 Beispiel:
> * **Hausverbrauch:** 4 kWh
> * **PV erzeugt:** 3 kWh
>   
>   * **1 kWh direkt im Haus verbraucht**
>   * **1 kWh in die Batterie geladen (negativ)**
> * **Batterie entlädt nachts 1 kWh (positiv)**
> * **Netzbezug:** 1 kWh
> 
> 💡 **Das Dashboard rechnet alles saldierend:** Was ins Haus fließt, ist positiv, was rausgeht, negativ.
> 
> ### ⚠ Wichtige Regel: Energiesensoren müssen absolute Werte liefern!
> ❌ **Keine Tageswerte – Home Assistant berechnet Zeiträume selbst** ✔ **State-Class:** für Zähler, für absolute Werte ✔ **Kein tägliches Zurücksetzen – das Dashboard macht die Zeitberechnung**`total_increasing``total`
> 
> ### ✅ Fazit:
> Kein Fehler – das ist so **designt**.

Dann ist das aber extrem traurig mit einem argen Denkfehler. Somit stimmt ja die ganze Anzeige für Autarkie, CO2 neutralem Strom und PV Eigenverbrauch nicht mehr. Einzig mein bezogener Nettostrom stimmt. An sonnigen Tagen bin ich vollständig autark und das dämliche Ding zeigt mir so um die 60% an.... Auch keine Möglichkeit das irgendwie zu ändern. Hoffentlich wird das bald mal gefixt.

**Comment by dcollewaert** [comment]
> > ### 🛠 Warum zeigt das Energie-Dashboard Netzeinspeisung & Batterieaufladung negativ?
> > Home Assistant **Energie-Dashboard** stellt **Verbrauch positiv** und **Einspeisung/Batterieladung negativ** dar. Dies ist **korrekt**, da: ✅ **Verbrauch** (Haus, Netz, Batterie-Entladung) **immer positiv** ist ✅ **Einspeisung** (Netz, Batterie-Aufladung) **immer negativ** ist
> > ### 📊 Beispiel:
> > 
> > * **Hausverbrauch:** 4 kWh
> > * **PV erzeugt:** 3 kWh
> >   
> >   * **1 kWh direkt im Haus verbraucht**
> >   * **1 kWh in die Batterie geladen (negativ)**
> > * **Batterie entlädt nachts 1 kWh (positiv)**
> > * **Netzbezug:** 1 kWh
> > 
> > 💡 **Das Dashboard rechnet alles saldierend:** Was ins Haus fließt, ist positiv, was rausgeht, negativ.
> > ### ⚠ Wichtige Regel: Energiesensoren müssen absolute Werte liefern!
> > ❌ **Keine Tageswerte – Home Assistant berechnet Zeiträume selbst** ✔ **State-Class:** für Zähler, für absolute Werte ✔ **Kein tägliches Zurücksetzen – das Dashboard macht die Zeitberechnung**`` total_increasing``total ``
> > ### ✅ Fazit:
> > Kein Fehler – das ist so **designt**.
> 
> Dann ist das aber extrem traurig mit einem argen Denkfehler. Somit stimmt ja die ganze Anzeige für Autarkie, CO2 neutralem Strom und PV Eigenverbrauch nicht mehr. Einzig mein bezogener Nettostrom stimmt. An sonnigen Tagen bin ich vollständig autark und das dämliche Ding zeigt mir so um die 60% an.... Auch keine Möglichkeit das irgendwie zu ändern. Hoffentlich wird das bald mal gefixt.

Your reasoning seems wrong. I have the same issue. Electricity charged during the night has another price then the electricity during the day. At night i charge let's say 5KWH into a battery. This amount seems nowhere visible in the energy dashboard totals. (I'm missing this amount from my grid totals). This does not seem a think failure, but a real issue. Today I cannot use my battery inside my energy dashboard because of this.
