### ISSUE TITLE
Entering coordinates when creating a new zone doesn't pan the map to that location

### ISSUE THREAD

**Issue by thibaultmol** [home-assistant/frontend#19365]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If you type in coordinates manually, the map doesn't pan accordingly

### Describe the behavior you expected

What I would expect to happen is that the map to pan to where those coordinates are (assuming the marker on the map is no longer in view). But nothing happens

### Steps to reproduce the issue

1. got to [your HA url] /config/zone
2. click the button to create a new zone
3. Change/enter one of the coordinates in those fields on that window

### What version of Home Assistant Core has the issue?

2024.1.2

### In which browser are you experiencing the issue with?

Both Firefox 121.0.1 and chrome 120.0.6099.216

### Which operating system are you using to run this browser?

Garuda linux

**Comment by ildar170975** [comment]
confirmed
