### ISSUE TITLE
Brightness value not displaying in more-info box while dragging

### ISSUE THREAD

**Issue by murkumurdok** [home-assistant/frontend#19366]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

While in the more-info window of any light, I cannot see the brightness value while dragging the brightness slider, the only thing that appears is a white oval on the left side that presumably should have the brightness value, but doesn't display it.  This makes it difficult to make fine adjustments to brightness using the slider because you will only see the brightness value after you release the slider, leading to a lot of trial and error.  See the screenshot below for a demonstration:

![light](https://github.com/home-assistant/frontend/assets/26509777/97e84eb3-514a-49a5-a170-b428fe2a258c)

### Describe the behavior you expected

I expect that the brightness value is immediately displayed while grabbing and dragging the brightness value.

### Steps to reproduce the issue

1. Open the more-info dialogue on any light
2. Attempt to drag the brightness slider.

### What version of Home Assistant Core has the issue?

2024.1.2

### In which browser are you experiencing the issue with?

Microsoft Edge Version 120.0.2210.121; MacOS Safari, iOS Safari

### Which operating system are you using to run this browser?

Windows 10, MacOS 14.2.1, iOS 17.1.2

**Comment by karwosts** [comment]
Did you really try the safe mode?

I ask because you seem to have a non-standard theme in use which would be disabled in that case. 

Also the basic dark mode display here would be white text on a black bubble, and seeing as how you have a white bubble, I wonder if your theme is just displaying white text on a white background.
