### ISSUE TITLE
Shopping List - List jumps to bottom when marking an item as completed

### ISSUE THREAD

**Issue by titiviking** [home-assistant/frontend#19373]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In the shopping list, when marking an item as being completed (because added to the groceries basket), the list jumps towards then bottom of the list, following the item that was marked.
This means that every item marked, requires to manually scoll back all the way to the top to find back the remaining items that need to be picked up...
This is very inconvenient and not user friendly (at least for a shopping list).

A setting should be added (per list?) to either follow the item, or simply stay at the top of the list when an item is marked.

### Describe the behavior you expected

Items marks go to the bottom, but screen remains focused on unmarked items

### Steps to reproduce the issue

create a list, mark items

### What version of Home Assistant Core has the issue?

2024.1

**Comment by mcfly2283** [comment]
„screen remains focused on unmarked items“
+1

**Comment by bootyberry** [comment]
+1 Please remove this terrible "feature" added to follow the selected todo list item when checking items.

**Comment by mcfly2283** [comment]
> +1 Please remove this terrible "feature" added to follow the selected todo list item when checking items.
> 
> #19168
> 
> Pretty sure it's this PR that "broke" it.


Had a Tenditis from scrolling in my List

**Comment by JazekerXX** [comment]
+1 this really needs to be reverted asap!
se also [this discussion ](https://community.home-assistant.io/t/to-do-list-behaviour-change-in-2024-1/666769)...
i really hope next time they change stuff like this, they will add the option to choose the behaviour you want, because this is really bad for the WAF (Wife Acceptance Factor) and if the wife does not approve... then HA will loose.. if you know what i mean?..

**Comment by pauldcomanici** [comment]
Please revert or make it opt-in; when you have a long list, and you are scrolled to the bottom, the feature becomes useless.

**Comment by bramkragten** [comment]
https://github.com/home-assistant/frontend/pull/19472
