### ISSUE TITLE
Login no longer possible - JavaScript error

### ISSUE THREAD

**Issue by pefmeister** [home-assistant/frontend#19385]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I can no longer login to my HA instance. All existing sessions still work, but I can't get the user / password dialogue to show up. The following is displayed instead:

<img width="556" alt="Bildschirmfoto 2024-01-13 um 19 52 07" src="https://github.com/home-assistant/frontend/assets/18077793/24357ba9-8a98-4f1e-be02-21af54c1b7bc">

The JavaScript console throws the following error:

ha-authorize.ts:75 Uncaught (in promise) TypeError: e.filter is not a function
    at a.value (ha-authorize.ts:75:52)
    at a.update (lit-element.ts:160:24)
    at a.performUpdate (reactive-element.ts:1329:14)
    at a.scheduleUpdate (reactive-element.ts:1261:17)
    at a._$Ej (reactive-element.ts:1233:25)
value @ ha-authorize.ts:75
update @ lit-element.ts:160
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ ha-authorize.ts:327
await in value (async)
value @ ha-authorize.ts:266
_$AE @ reactive-element.ts:1376
performUpdate @ reactive-element.ts:1343
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
y @ reactive-element.ts:931
E @ lit-element.ts:115
n @ lit-localize-lite-mixin.ts:14
a @ ha-authorize.ts:46
finisher @ custom-element.ts:41
runClassFinishers @ decorate.js:237
d @ decorate.js:15
(anonymous) @ ha-authorize.ts:26
(anonymous) @ authorize.ts:9
Show 2 more frames
Show less
ha-authorize.ts:75 Uncaught (in promise) TypeError: e.filter is not a function
    at a.value (ha-authorize.ts:75:52)
    at a.update (lit-element.ts:160:24)
    at a.performUpdate (reactive-element.ts:1329:14)
    at a.scheduleUpdate (reactive-element.ts:1261:17)
    at a._$Ej (reactive-element.ts:1233:25)
value @ ha-authorize.ts:75
update @ lit-element.ts:160
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ lit-localize-lite-mixin.ts:92
await in value (async)
value @ lit-localize-lite-mixin.ts:27
finisher @ custom-element.ts:41
runClassFinishers @ decorate.js:237
d @ decorate.js:15
(anonymous) @ ha-authorize.ts:26
(anonymous) @ authorize.ts:9
Show 2 more frames
Show less
ha-authorize.ts:75 Uncaught (in promise) TypeError: e.filter is not a function
    at a.value (ha-authorize.ts:75:52)
    at a.update (lit-element.ts:160:24)
    at a.performUpdate (reactive-element.ts:1329:14)
    at a.scheduleUpdate (reactive-element.ts:1261:17)
    at a._$Ej (reactive-element.ts:1233:25)
2ha-authorize.ts:75 Uncaught (in promise) TypeError: e.filter is not a function
    at a.value (ha-authorize.ts:75:52)
    at a.update (lit-element.ts:160:24)
    at a.performUpdate (reactive-element.ts:1329:14)
    at a.scheduleUpdate (reactive-element.ts:1261:17)
    at a._$Ej (reactive-element.ts:1233:25)
value @ ha-authorize.ts:75
update @ lit-element.ts:160
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
(anonymous) @ lit-localize-lite-mixin.ts:60
Promise.then (async)
value @ lit-localize-lite-mixin.ts:59
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ lit-localize-lite-mixin.ts:92
await in value (async)
value @ lit-localize-lite-mixin.ts:27
finisher @ custom-element.ts:41
runClassFinishers @ decorate.js:237
d @ decorate.js:15
(anonymous) @ ha-authorize.ts:26
(anonymous) @ authorize.ts:9
Show 2 more frames
Show less

I cannot really say when this first hit me, since I usually use existing sessions, but today I wanted to login using a different browser. I'm running on a RPi5 and thus on the latest dev branch. 

### Describe the behavior you expected

Login screen should pop up

### Steps to reproduce the issue

1. Logout
2. Go to HA login screen

### What version of Home Assistant Core has the issue?

2024.2.0dev20240113

### In which browser are you experiencing the issue with?

Google Chrome 120.0.6099.216, MS Edge, Safari, all the same

### Which operating system are you using to run this browser?

macOS Ventura 13.6.3

### Problem-relevant frontend configuration

```yaml
I tried to put this into configuration.yaml, but to no avail:

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/16
        - fd00::/8
```

### Javascript errors shown in your browser console/inspector

```txt
ha-authorize.ts:75 Uncaught (in promise) TypeError: e.filter is not a function
    at a.value (ha-authorize.ts:75:52)
    at a.update (lit-element.ts:160:24)
    at a.performUpdate (reactive-element.ts:1329:14)
    at a.scheduleUpdate (reactive-element.ts:1261:17)
    at a._$Ej (reactive-element.ts:1233:25)
value @ ha-authorize.ts:75
update @ lit-element.ts:160
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ ha-authorize.ts:327
await in value (async)
value @ ha-authorize.ts:266
_$AE @ reactive-element.ts:1376
performUpdate @ reactive-element.ts:1343
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
y @ reactive-element.ts:931
E @ lit-element.ts:115
n @ lit-localize-lite-mixin.ts:14
a @ ha-authorize.ts:46
finisher @ custom-element.ts:41
runClassFinishers @ decorate.js:237
d @ decorate.js:15
(anonymous) @ ha-authorize.ts:26
(anonymous) @ authorize.ts:9
Show 2 more frames
Show less
ha-authorize.ts:75 Uncaught (in promise) TypeError: e.filter is not a function
    at a.value (ha-authorize.ts:75:52)
    at a.update (lit-element.ts:160:24)
    at a.performUpdate (reactive-element.ts:1329:14)
    at a.scheduleUpdate (reactive-element.ts:1261:17)
    at a._$Ej (reactive-element.ts:1233:25)
value @ ha-authorize.ts:75
update @ lit-element.ts:160
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ lit-localize-lite-mixin.ts:92
await in value (async)
value @ lit-localize-lite-mixin.ts:27
finisher @ custom-element.ts:41
runClassFinishers @ decorate.js:237
d @ decorate.js:15
(anonymous) @ ha-authorize.ts:26
(anonymous) @ authorize.ts:9
Show 2 more frames
Show less
ha-authorize.ts:75 Uncaught (in promise) TypeError: e.filter is not a function
    at a.value (ha-authorize.ts:75:52)
    at a.update (lit-element.ts:160:24)
    at a.performUpdate (reactive-element.ts:1329:14)
    at a.scheduleUpdate (reactive-element.ts:1261:17)
    at a._$Ej (reactive-element.ts:1233:25)
2ha-authorize.ts:75 Uncaught (in promise) TypeError: e.filter is not a function
    at a.value (ha-authorize.ts:75:52)
    at a.update (lit-element.ts:160:24)
    at a.performUpdate (reactive-element.ts:1329:14)
    at a.scheduleUpdate (reactive-element.ts:1261:17)
    at a._$Ej (reactive-element.ts:1233:25)
value @ ha-authorize.ts:75
update @ lit-element.ts:160
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
(anonymous) @ lit-localize-lite-mixin.ts:60
Promise.then (async)
value @ lit-localize-lite-mixin.ts:59
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ lit-localize-lite-mixin.ts:92
await in value (async)
value @ lit-localize-lite-mixin.ts:27
finisher @ custom-element.ts:41
runClassFinishers @ decorate.js:237
d @ decorate.js:15
(anonymous) @ ha-authorize.ts:26
(anonymous) @ authorize.ts:9
Show 2 more frames
Show less
```

**Comment by karwosts** [comment]
This should be resolved if you're on the latest dev frontend and latest dev core.

There was a codependent change a few days ago that necessitated updating them together.

**Comment by pefmeister** [comment]
I would love to update, but I guess, I'm already at the edge:

```
# ha refresh-updates
Command completed successfully.
# ha available-updates
available_updates: []
# ha core update
Error: Version 2024.2.0.dev20240113 is already installed
```

**Comment by karwosts** [comment]
What frontend version does config/info report? It should be fixed at 20240112.0. 

Also might be a browser caching issue, maybe try clear your caches.

**Comment by pefmeister** [comment]
OK, here I got 20240103.0.dev for the frontend. Any idea how to get this updated?

**Comment by silamon** [comment]
You may want to update from nightly to stable release in the meantime. It seems like it's not picking up the latest nightly build of the frontend. [The build logs](https://github.com/home-assistant/core/actions/runs/7509639833/job/20447031444) has a step "Download nightly wheels of frontend" which picks up  "20240103.0.dev" .

**Comment by silamon** [comment]
The nightly build made a few hours ago contains the fix. Thanks to the fast approval from Steve.

**Comment by nicolaspernoud** [comment]
Hello, anyone knows how to fix the issue for the devcontainer ? The lastest version seems not to have the fix (?)

**Comment by pefmeister** [comment]
It does work for me, at least after I upgraded this morning.

**Comment by nicolaspernoud** [comment]
I still have "version     = "2024.2.0.dev0" in pyproject.toml and the frontend constraint is home-assistant-frontend==20240104.0 
What do I do wrong ?
