### ISSUE TITLE
Typo in System Monitor Processor integration

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#19395]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Sensors with percentage units have an incorrect space before the unit itself

![image](https://github.com/home-assistant/frontend/assets/74879713/ab0203c6-3c04-4fc3-8712-eb9704c4048b)

### Describe the behavior you expected

In this case I would expect to see 2%.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.1.3

### In which browser are you experiencing the issue with?

120.0.6099.217

### Which operating system are you using to run this browser?

Windows 10

**Comment by ildar170975** [comment]
See no difference in Gismeteo, Mobile App & Systemmonitor:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/1cb7e2b2-6aa6-4600-a208-0dbdfd8c4d2e)

![изображение](https://github.com/home-assistant/frontend/assets/71872483/db31e437-0e6c-4965-9a21-19c9d9c45fb5)

![изображение](https://github.com/home-assistant/frontend/assets/71872483/e1dbfcbd-2a0a-4a14-ae83-7cb34751810a)

![изображение](https://github.com/home-assistant/frontend/assets/71872483/77ed40f6-4ade-4048-80fd-3c4f41dc928d)

> In this case I would expect to see 2%.

Check with any entity with "%".

**Comment by karwosts** [comment]
OP is correct. We have code to decide to display a space or not before `%` based on the language, but it had a bug in some cases, so it wasn't being honored.

**Comment by WRoss7** [comment]
Ok, thanks
