### ISSUE TITLE
 Translation error: INVALID_ARGUMENT_TYPE

### ISSUE THREAD

**Issue by Pajuris** [home-assistant/frontend#19398]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Lithuanian language, Automation > Conditions

### Describe the behavior you expected

Lithuanian translation

### Steps to reproduce the issue

Update Home assistant core to 2024.1

### What version of Home Assistant Core has the issue?

2024.1.3

**Comment by Pajuris** [comment]
![Screen Shot 2024-01-14 at 19 23 39](https://github.com/home-assistant/frontend/assets/156599470/ff71c5e4-4097-49a0-ba54-9aa06033a3dc)

**Comment by karwosts** [comment]
Can you include the full yaml of that condition?

**Comment by Pajuris** [comment]
eg in this

alias: my automation
description: ""
trigger:
  - platform: state
    entity_id:
      - light.tz3000_ltt60asa_ts0004_lempa
    from: "on"
    to: "off"
condition:
  - condition: state
    entity_id: light.tz3000_ltt60asa_ts0004_lempa_2
    state: "off"
  - condition: state
    entity_id: light.tz3000_ltt60asa_ts0004_lempa_3
    state: "off"
  - condition: state
    entity_id: light.tz3000_ltt60asa_ts0004_lempa_4
    state: "off"
  - condition: state
    entity_id: light.sonoff_01minizb_lempa_2
    state: "on"
action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
        - light.sonoff_01minizb_lempa_2
mode: single

**Comment by karwosts** [comment]
This key was translated badly in lokalize: https://app.lokalise.com/project/3420425759f6d6d241f598.13594006/?k=418661829

I have fixed it there, and it should be correct for next release.
