### ISSUE TITLE
When updated the core to the 2024.1.3 version EspHome devices stop working

### ISSUE THREAD

**Issue by SimoDesa** [home-assistant/frontend#19407]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Once I have updated the Home Assistant Core to the 2024.1.3 version the EspHome devices stop working: I can see them online in esphome web interface, I can also see logs and I see that they are successfully connected to the Home Assistant server but in Home Assistant I see that the entity is not available, in Italian "Non disponibile" and I can't activate it.
I have restored the previous backup and everything works properly

### Describe the behavior you expected

I hope that every device works :)

### Steps to reproduce the issue

1. update the core to the last version (2024.1.3)
2. EspHome devices became not available

### What version of Home Assistant Core has the issue?

2024.1.3

### What was the last working version of Home Assistant Core?

2024.1.2

### In which browser are you experiencing the issue with?

not a browser problem

### Which operating system are you using to run this browser?

not a browser problem

**Comment by karwosts** [comment]
This is not related to frontend, more a home-assistant/core issue.
