### ISSUE TITLE
No Ignore Option for RTSPtoWebRTC

### ISSUE THREAD

**Issue by c0nt4x** [home-assistant/frontend#19409]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

RTSPtoWebRTC is showing as a discovered integrations in Settings > Devices & Services > Integrations but there is no option to be able to ignore the integration therefore it persists to show as Discovered

### Describe the behavior you expected

Expected to see an option to ignore the integration

### Steps to reproduce the issue

1. Select the three dots inside the integration tile
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.1.3

### In which browser are you experiencing the issue with?

All browsers and HA Companion App

### Additional information

![image](https://github.com/home-assistant/frontend/assets/70321584/96b704ee-cfb3-4116-b02f-7075543896d1)

**Comment by karwosts** [comment]
This looks like what frontend requires to be able to show the ignore button:

```
        ${DISCOVERY_SOURCES.includes(this.flow.context.source) &&
        this.flow.context.unique_id
          ? html`<ha-button
              @click=${this._ignoreFlow}
              .label=${this.hass.localize(
                "ui.panel.config.integrations.ignore.ignore"
              )}
            ></ha-button>`
          : ""}

```

Don't know exactly what's going on here, but perhaps we don't have a unique_id for this item. Maybe you want to open up a core issue for RSTPtoWebRTC to investigate further, to see if someone there might know what is missing?
