### ISSUE TITLE
Calender bug

### ISSUE THREAD

**Issue by Rudi60** [home-assistant/frontend#19418]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1108
First occurred: 13. Januar 2024 um 21:31:18 (2 occurrences)
Last logged: 06:16:18

Updating state for calendar.feiertage_in_osterreich (<class 'homeassistant.components.google.calendar.GoogleCalendarEntity'>) took 0.586 seconds. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+google%22
Updating state for calendar.zaru1960_gmail_com (<class 'homeassistant.components.google.calendar.GoogleCalendarEntity'>) took 0.772 seconds. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+google%22

### Describe the behavior you expected

feedback from system

### Steps to reproduce the issue

1.feedback from system
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.1.3

### In which browser are you experiencing the issue with?

firefox

### Which operating system are you using to run this browser?

WIN 10

**Comment by karwosts** [comment]
This is the wrong repo, the link instructed you to open an issue in home-assistant/core, not home-assistant/frontend.
