### ISSUE TITLE
HA not receiving Owntracks localisation 

### ISSUE THREAD

**Issue by cedricdelecole** [home-assistant/frontend#19420]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have setup Owntracks following the documentation on the mobile phone and HA, but HA is showing wrong localisation of the mobile phone

### Describe the behavior you expected

The localisation of my child is always showned as he was home, although he is school

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2024.1.3

**Comment by karwosts** [comment]
This is not a frontend related issue. If you are needing some support, suggest checking out the community forums or the discord server to help troubleshoot.
