### ISSUE TITLE
Energy dashboard -  individual device made up of a template sensor can get misaligned with its measured value (after reboot/yaml reload)

### ISSUE THREAD

**Issue by dmtalon** [home-assistant/frontend#19425]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I am using the energy dashboard.  I am using Emporia Vues (flashed with esphome) to capture power usage at my two circuit panels.  My HVAC requires 2 240v circuit breakers (a pair of 45A and a pair of 65A).  I have a CT clamp on one leg of each and created a template sensor that combines their daily usage into a single sensor that is added as an individual device within the dashboard.   This is so I can quickly see how many kW my HVAC system has used.

If HA is restarted/reloaded, or the yaml files are reloaded the individual bar graph and "hover over" value will increase many times over the actual value.  

For instance, if my furnace has used 10kwh today, and I reboot, the below sensor will continue to show 10kw, however the energy dashboard bar graph will have doubled or tripled in length (showing many time more usage).  Hovering my mouse over the bar will also show this inflated reading.  However if I click on the bar and open the more-info of the sensor. The data that is reported for that sensor will be accurate.  Attached, below will show an example of today after I reloaded the yaml template file.

The non template sensors added to the energy dashboard do not appear to be affected by this.

My sensor:
`template:
  - sensor:
      - name: "Total Furnace Daily Energy"
        unique_id: "total_power_furnace_daily"
        unit_of_measurement: "Wh"
        device_class: energy
        state_class: total_increasing
        state: >-
          {{ ((states('sensor.emporiavue1_furnace_geothermal_daily_energy')|float(0)|round(2) ) + (states('sensor.emporiavue1_furnace_em_heat_daily_energy')|float(0)))| round(2) }}`

<img width="1258" alt="2024-01-16_11-39-28" src="https://github.com/home-assistant/frontend/assets/68720859/453dfef0-e5c9-4e3d-b774-dd546c8e0213">

  
<img width="1069" alt="2024-01-16_11-39-59" src="https://github.com/home-assistant/frontend/assets/68720859/15dc6d56-0e82-4678-a79a-ffcf3aec11be">

### Describe the behavior you expected

I would expect the bar graph to match the sensors value.  Right now I am not sure where/how it is calculating it's total daily value if it is not directly using the sensor that is tracking it.

### Steps to reproduce the issue

1. Use energy dashboard
2. create template sensor that totals two other sensors
3. add the new template sensor to the energy dashboard
4. after collecting data and have the dashboard displaying the individual values as well as total energy usage reboot/refresh template yaml files.
...

### What version of Home Assistant Core has the issue?

core-2024.1.3

### In which browser are you experiencing the issue with?

Firefox, Edge

### Which operating system are you using to run this browser?

macOS / Windows 10

### State of relevant entities

```txt
state_class: total_increasing
unit_of_measurement: Wh
device_class: energy
icon: mdi:heat-pump
friendly_name: Furnace (Total)

State: 33697.0
```

**Comment by karwosts** [comment]
Can you make a statistics graph card of this statistic for the last 24H, showing state/sum/change, and post what that looks like?

I'm fairly sure this isn't a frontend issue, but we can rule it out with that graph.

**Comment by dmtalon** [comment]
> Can you make a statistics graph card of this statistic for the last 24H, showing state/sum/change, and post what that looks like?
> 
> I'm fairly sure this isn't a frontend issue, but we can rule it out with that graph.

I believe I've created what you are asking for.


<img width="507" alt="image" src="https://github.com/home-assistant/frontend/assets/68720859/27909c30-689a-4410-b55e-a334a928ed41">

**Comment by karwosts** [comment]
Your statistics history is definitely showing a massive jump in the total there, so I guess what energy dashboard is showing is probably correct based on the data it is getting.

I think your problem is likely related to your template, when you have default filters like `float(0)` in a total_increasing template, what that means is that if on-startup the source sensor is not available, the output sensor will temporarily go from 30,000 -> 0 -> 30,000, and the 0 value will tell energy that that's a reset, and so then count the return to 30,000 as a massive new accumulation.

If you want to handle this correctly you need a template with an appropriate availability template, so that the value goes `unavailable` when the source is unavailable, instead of going to 0, which will break graphs in this way. This is a common issue.

**Comment by dmtalon** [comment]
Thanks for your reply.. I believe I added the default float when I was creating the template either because of an error in the log or while trying to create it.  I'll have to try to see if I can figure out why I did what I did.  Generally I'm just googling around and finding bits/pieces I need to get what I want done.  But I do remember needing to add the float(0) for some specific reason.

**Comment by karwosts** [comment]
Anyway, I would recommend to check out the community forum or discord server to look for some support for fixing your templates. That is off topic for this issue tracker. Best of luck.
