### ISSUE TITLE
Heatit Temp2 sensor new firmware V.1.2.1 require update of the z-wave js UI 

### ISSUE THREAD

**Issue by SIFI1971** [home-assistant/frontend#19440]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After Updating the Heatit Temp2 sensor to latest Firmware 1.2.1 the entities becomes undefined. 
![image](https://github.com/home-assistant/frontend/assets/118279887/cbd21108-1eec-4893-84da-447062a10b04)

### Describe the behavior you expected

Entities should have been mapped to HA and become availabele to use. See attached picture in the description
![Heatit temp2 sensor FW 1 2 1](https://github.com/home-assistant/frontend/assets/118279887/21207aa1-d5ff-47a9-83ee-3a26cf09b435)

### Steps to reproduce the issue

1. Flash the Heatit temp2 sensor with the attached firmware update 1.2.1 (obs not possible to revert to a lower version after update)
2. See result in z-wave js ui
3.
...

### What version of Home Assistant Core has the issue?

2024.1.3

### State of relevant entities

```txt
Humidity
Air temperature
Battery level
Low battery level
Setpoint (Heating)
```

**Comment by karwosts** [comment]
Frontend has nothing to do with the states of entities. This either needs to be a core issue or something in zwave.
