### ISSUE TITLE
Automation - Unable to distinguish devices in drop down list when names are the same but types are different

### ISSUE THREAD

**Issue by tiagodj** [home-assistant/frontend#19444]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have devices that have the same name, for example "Family Room", but under the hood they are different things: `climate`, `light`, `media_player`, `remote`.

The problem is that in the new UI, we can only see the Device Name in the drop down when searching for a Device, and I am unable to know which one is which.

Here's a screen shot of the example:

<img width="416" alt="Screenshot 2024-01-18 at 9 10 27 AM" src="https://github.com/home-assistant/frontend/assets/502627/cb54d3d9-569e-4fd2-9ef2-516006047745">

Only solution I have for now is to rename the entity, I don't want to do that.

Another option is to use YAML mode, but then I need to open the docs to see what is the syntax there. Very frustrating.

### Describe the behavior you expected

I would like to be able to distinguish the Devices. You can either display the type, or the actual ID next to it, for example:

`Family Room (remote)`

or 

`Family Room (remote.family_room)` (preferred)

### Steps to reproduce the issue

1. Click to Create a new automation
2. Select Device
3. Search for a name that matches multiple devices with same name, different type.

### What version of Home Assistant Core has the issue?

20240104.0

### In which browser are you experiencing the issue with?

Safari

### Which operating system are you using to run this browser?

macOS Sonoma 14.2.1

### State of relevant entities

```txt
light.family_room: off
min_color_temp_kelvin: 2000
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 500
supported_color_modes:
  - color_temp
  - xy
color_mode: null
brightness: null
color_temp_kelvin: null
color_temp: null
hs_color: null
rgb_color: null
xy_color: null
is_hue_group: true
hue_scenes:
  - Dimmed
  - Halloween 🎃
  - Read
  - Under the tree
  - Spring blossom
  - Savanna sunset
  - Nightlight
  - Rest
  - Relax
  - Energize
  - Girls
  - Bright
  - Morning
  - Concentrate
  - Arctic aurora
  - Tropical twilight
  - Natural light
hue_type: room
lights:
  - Floor Lamp Color
  - Table Lamp Color
dynamics: false
icon: mdi:lightbulb-group
friendly_name: Family Room
supported_features: 40


remote.family_room: on
attr:
climate.family_room: heat
attr:
hvac_modes:
  - heat
  - cool
  - heat_cool
  - "off"
min_temp: 10
max_temp: 32
fan_modes:
  - "on"
  - "off"
preset_modes:
  - none
  - eco
current_temperature: 18.7
temperature: 21
target_temp_high: null
target_temp_low: null
fan_mode: "off"
hvac_action: heating
preset_mode: none
friendly_name: Family Room
supported_features: 27


friendly_name: Family Room
supported_features: 0


climate.family_room: heat
attr:
hvac_modes:
  - heat
  - cool
  - heat_cool
  - "off"
min_temp: 10
max_temp: 32
fan_modes:
  - "on"
  - "off"
preset_modes:
  - none
  - eco
current_temperature: 18.7
temperature: 21
target_temp_high: null
target_temp_low: null
fan_mode: "off"
hvac_action: heating
preset_mode: none
friendly_name: Family Room
supported_features: 27
```

### Problem-relevant frontend configuration

```yaml
I can't make a configuration because I am unable to select the Device I need in the drop down list.
```

### Javascript errors shown in your browser console/inspector

```txt
No errors.
```

### Additional information

N/A

**Comment by ildar170975** [comment]
https://github.com/home-assistant/frontend/issues/11870
