### ISSUE TITLE
Missing in lokalise "Generate qr code"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#19458]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Found missing words in lokalise (in attached screenshot).

![1705572495731_GenerateQrCode](https://github.com/home-assistant/frontend/assets/61636045/cc86433b-1e04-464f-9871-446f340e0d0f)

### Describe the behavior you expected

Please add it to lokalise.
Thank you in advance.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.1.3

### What was the last working version of Home Assistant Core?

not relevant

**Comment by silamon** [comment]
This is a [frontend translation](https://github.com/home-assistant/frontend/blob/dev/src/panels/profile/ha-long-lived-access-token-dialog.ts#L77) that can be translated.
