### ISSUE TITLE
Missing in lokalise "Internal Server Error Server got itself in trouble"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#19459]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Found missing words in lokalise (in attached screenshot).

![1705572495833_InternalError](https://github.com/home-assistant/frontend/assets/61636045/507f4ff4-80b6-4ebc-9a0f-b0ed3739648d)

### Describe the behavior you expected

Please add it to lokalise.
Thank you in advance.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.1.3

### What was the last working version of Home Assistant Core?

not relevant

**Comment by silamon** [comment]
I don't think this is a frontend translation and I couldn't find it immediately in other repositories. It's most likely something that cannot be translated.
