### ISSUE TITLE
Missing in lokalise "Unable to load example. Response error:"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#19457]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Found missing words in lokalise (in attached screenshot).

![1705572495680_UnableToLoad](https://github.com/home-assistant/frontend/assets/61636045/2838e5df-7265-4206-94e4-622a5cd5f308)

### Describe the behavior you expected

Please add it to lokalise.
Thank you in advance.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.1.3

**Comment by silamon** [comment]
The first part of the sentence is a frontend translation [here ](https://github.com/home-assistant/frontend/blob/dev/src/panels/config/cloud/account/dialog-cloud-tts-try.ts#L201) and [here](https://github.com/home-assistant/frontend/blob/dev/src/dialogs/tts-try/dialog-tts-try.ts#L149).
