### ISSUE TITLE
Missing in lokalise "Failed to to call"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#19462]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Found missing words in lokalise (in attached screenshot).

![1705572495698_requiredKey2](https://github.com/home-assistant/frontend/assets/61636045/b41b940b-8664-4fc6-9eb7-a731350ea3f9)

![1705572495715_requiredKey](https://github.com/home-assistant/frontend/assets/61636045/f25d3a27-1d42-4ed1-9147-026ed456edff)

### Describe the behavior you expected

Please add it to lokalise.
Thank you in advance.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.1.3

### What was the last working version of Home Assistant Core?

not relevant

**Comment by silamon** [comment]
This is a translation in [core](https://github.com/home-assistant/core/blob/dev/homeassistant/components/hassio/websocket_api.py#L138).  Please open an issue in their [repository](https://github.com/home-assistant/core).

**Comment by frenck** [comment]
This ain't translatable, regardless of core or not.
