### ISSUE TITLE
Missing in lokalise "was used from" and others

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#19463]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Found missing words in lokalise (in attached screenshot).

![1705572495778_notification](https://github.com/home-assistant/frontend/assets/61636045/06370ef3-34a3-4155-a034-c4bd863282b1)

![1705572495747_alreadyInstalled](https://github.com/home-assistant/frontend/assets/61636045/822ab14f-81b7-4d29-b1c5-c503d2761aa0)

![1705572495762_plynomer](https://github.com/home-assistant/frontend/assets/61636045/6db73a32-2eba-42d4-8972-487ef61a465c)

### Describe the behavior you expected

Please add it to lokalise.
Thank you in advance.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.1.3

### What was the last working version of Home Assistant Core?

not relevant

**Comment by silamon** [comment]
This is a translation in [core](https://github.com/home-assistant/core/blob/dev/homeassistant/components/sensor/__init__.py#L551-L552).  Please open an issue in their [repository](https://github.com/home-assistant/core). 

Others are temporary messages or messages belonging to custom integrations.
