### ISSUE TITLE
History - Graphs with same unit of measure are not combined

### ISSUE THREAD

**Issue by creeve4** [home-assistant/frontend#19474]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When adding multiple entities to the History page for review, all with the same unit of measure, some will display on a separate graph. These same entities were previously shown all combined on the same graph, although I do not know the precise version of Home Assistant when the bug was introduced.

Example (Ecobee entities):
![Ex1](https://github.com/home-assistant/frontend/assets/1910130/f4738f4d-6fd0-4bc8-8787-f669710b0794)

### Describe the behavior you expected

Entities with the same unit of measure should all be displayed on the same history graph.

### Steps to reproduce the issue

Not all entities exhibit this bug. For me, this bug can be reproduced 100% using entities from the Ecobee Integration, although others have reported this bug occurring under other circumstances.
1. Open History
2. Add Ecobee Thermostat entity
3. Add Ecobee Sensor entities

### What version of Home Assistant Core has the issue?

2024.1.3

### In which browser are you experiencing the issue with?

Chrome Version 120.0.6099.217 / Edge Version 120.0.2210.121 

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
Thermostat
hvac_modes: heat_cool, heat, cool, off
min_temp: 44.6
max_temp: 95
target_temp_step: 0.5
fan_modes: auto, on
preset_modes: Home, Away, Sleep, Home Heat, Warm Night, Home Cool, Extra Cool
current_temperature: 68.5
temperature: 69
target_temp_high: null
target_temp_low: null
current_humidity: 33
fan_mode: on
hvac_action: fan
preset_mode: Home Heat
fan: on
climate_mode: Home
equipment_running: fan
fan_min_on_time: 15
friendly_name: Thermostat
supported_features: 27

Coles Room Temperature:
state_class: measurement
unit_of_measurement: °F
device_class: temperature
friendly_name: Coles Room Temperature

Master Bedroom Temperature:
state_class: measurement
unit_of_measurement: °F
device_class: temperature
friendly_name: Master Bedroom Temperature

Parker's Room Temperature:
state_class: measurement
unit_of_measurement: °F
device_class: temperature
friendly_name: Parker's Room Temperature

Outside Temperature:
state_class: measurement
unit_of_measurement: °F
icon: mdi:sun-thermometer-outline
friendly_name: Outside Temperature
```

### Problem-relevant frontend configuration

```yaml
See example screenshot above.
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

### Additional information

https://community.home-assistant.io/t/history-graphs-with-same-unit-of-measure-are-not-combined/671313

**Comment by karwosts** [comment]
I believe this was an intentional change to only combine units which were of the same device_class. I think it was thinking was it didn't really make sense to plot things like battery percentages on the same scale as relative humidity, etc. 

I can see that a special case that might be needed is for climate though, as they don't have a device_class the way temperature sensors do, but those might make sense to combine together...

**Comment by creeve4** [comment]
Thank you for the insight. I would really appreciate a special case for climate entities! For cases like my example it is much easier to compare when everything is on a single graph.

**Comment by glenviewjeff** [comment]
Me too. 

state_class: measurement
unit_of_measurement: µg/m³
attribution: Data provided by AirNow
device_class: pm25
friendly_name: AirNow PM2.5

state_class: measurement
unit_of_measurement: μg/m³
device_class: pm25
friendly_name: Kitchen Air Quality H5106-pm25

![image](https://github.com/home-assistant/frontend/assets/334914/0a967744-d633-4387-a8d9-090339fa258a)

**Comment by tiggit22** [comment]
> I believe this was an intentional change to only combine units which were of the same device_class. 
This change also broke usage of helpers. 

For instance, I have a chart that shows the power of two solar inverters together with the total power of both inverters. To calculate total power, I use a helper that sums up the power of the two inverters. Basically, I now have three values (all in Wh) 

The values were combined nicely in a single chart (HA 23.11, if I remember correctly)

So, one solution might to set a device_class for helpers, derived from the original entities in the same way it is done for the units already.

**Comment by ildar170975** [comment]
@tiggit22 
The issue is closed, suggest to open another one if it is crucial for you

**Comment by lakee911** [comment]
When making comparisons in data, I think it makes sense to have everything on a single graph. For the plotting battery percentages (%) on the same scale as relative humidity (%) example, above, I might want to know the impact of humidity in, say, how much does it impact charge time. I would even say that there can be a lot of totally mismatched units that make sense to plot together. None of the industrial automation graphical user interface software (i.e., human machine interface software) that I am familor with has this type of limitation.

**Comment by tvwerkhoven** [comment]
For reference, a manual solution is to customize in YAML (`configuration.yaml`), [source](https://community.home-assistant.io/t/helper-changes-device-class/511072/5), e.g. for a temperature sensor:

```yaml
homeassistant:
  customize:
    sensor.outdoor_temperature:
      device_class: temperature
```

See also [this thread](https://community.home-assistant.io/t/history-graphs-with-same-unit-of-measure-are-not-combined/671313) and [this thread](https://community.home-assistant.io/t/what-drives-temperature-sensors-not-to-show-in-the-same-history-graph/845889/3)
