### ISSUE TITLE
When creating a tag, the QR code corresponding QR only contains the Tag ID

### ISSUE THREAD

**Issue by henriklund** [home-assistant/frontend#19484]
### The problem

When creating a tag, the QR code corresponding QR only contains the Tag ID, ie. the 'https://www.home-assistant.io/tag/' part is missing and the QR code cannot be used in conjunction with the companion app .
- Go to Settings -> Tags
- Add Tag (provide a name) and Create
- Click on Gear right of newly created tag
- Scan QR code with camera (or a dedicated QR scanner app): The scanned value will be equal to the Tag ID and missing the 'https://www.home-assistant.io/tag/' part

Problem persists whether anything is written to an NFC tag or not.

### What version of Home Assistant Core has the issue?

2024.1.2

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Tags

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/tag/

**Comment by henriklund** [comment]
> Don’t know if this also affects NFC Tags as I was using this as a precursor to picking up NFC tags to test some automations

It does not. NFC tags work like a charm :)

**Comment by karwosts** [comment]
Likely broken by #19155

**Comment by abcrawford** [comment]
> > Don’t know if this also affects NFC Tags as I was using this as a precursor to picking up NFC tags to test some automations
> 
> 
> 
> It does not. NFC tags work like a charm :)

Good to know, thanks.

**Comment by samueldowd** [comment]
I’d like to add to this that it seems to extend beyond new codes. 

Attached are screenshots of the same code, but one (the one in dark mode) is from 12/7 (before 2024.1.2) and the second (in light mode) is from today on 2024.1.5. You can see that the id is the same, but the QR code is different. 

The dark mode code launches the HA companion app correctly, while the light mode only contains the tag id as described above. 

![Dark Mode from 12/7](https://github.com/home-assistant/frontend/assets/5603746/bbc5adde-a15c-4495-8aaa-cc5bfcb618b8)

![Light Mode from 1/25](https://github.com/home-assistant/frontend/assets/5603746/2a6d45df-1825-4edc-82f6-69f14b2d9a48)
