### ISSUE TITLE
Date last modified is not date last modified

### ISSUE THREAD

**Issue by Xorfor** [home-assistant/frontend#19487]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After an update to the latest version of HA, the sensors show a date last modified of the latest update, instead of the really date last modified! Please update the timestamp from the database (?). Example: I have a door sensor, the door is closed the whole day, but after an update of the software, it shows that the state is updated at the time of the update, which is not true because the door was closed that time!

### Describe the behavior you expected

I expect after an update of the software, that the last modfied date of a sensors is the real last modified date instead of the date time of the last update.

### Steps to reproduce the issue

1. Create an Entity chart
2. Add an entity
3. Specify in Secondary information to display the Last Modified 
4. Do a software update

### What version of Home Assistant Core has the issue?

Latest

**Comment by ildar170975** [comment]
1. If there is an issue - do not think this is a Frontend issue.
2. When was the last time you rebooted HA before this update? last_changed is usually changed on every HA reboot. When you updated HA - you restarted HA -> last_changed was changed too.
