### ISSUE TITLE
Scenes GUI Editor for existing scenes is empty - no devices or entities shown.

### ISSUE THREAD

**Issue by clowgg** [home-assistant/frontend#19493]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I go into the Scenes editor in the GUI for an existing scene (_not_ creating a new one) none of the devices or entities that are configured in that scene appear - so I can't edit the state of them.

Example:
![image](https://github.com/home-assistant/frontend/assets/145304547/ddaaacf4-ef01-439d-8d12-e5a6a185d472)

### Describe the behavior you expected

Devices and entities are listed and I can edit the state of them. This used to work fine, but broke sometime in January '24.

### Steps to reproduce the issue

1. Go to Settings/Automations/Scenes
2. Click on an existing scene
3. There it is - no devices or entities listed
...

### What version of Home Assistant Core has the issue?

2024.1.5

### What was the last working version of Home Assistant Core?

2023.12 ?

### In which browser are you experiencing the issue with?

Firefox, Edge, iOS Companion App on iPhone & iPad

### Which operating system are you using to run this browser?

Windows 10, iOS

### Additional information

The scenes.yaml file still has all the defined scenes present. I tried adding a new scene and that was appended to the scenes.yaml file but when I went into the GUI to edit it - no entities that I had added were shown. 
I tried an empty scenes.yaml file and got the same result.
I sent my scenes.yaml to a friend and he found that it worked fine on his instance of HA.

**Comment by karwosts** [comment]
Can you check if `Advanced Mode` is turned on in your profile settings, and if not, try turning that on, see if it makes a difference?

**Comment by clowgg** [comment]
YES!!! That's it! What??? 
Advanced Mode was turned off. 
Turned it on and Scene editing was back to normal.
Why is this an advanced feature? Weird.

Not sure why Advanced had gotten turned off either. Not something I would have knowingly done.

**Comment by clowgg** [comment]
Turning on 'Advanced Mode' in my User Profile fixed the issue.
