### ISSUE TITLE
Can't input decimal number on iOS if the decimal separator is not `.`

### ISSUE THREAD

**Issue by Cyberbeni** [home-assistant/frontend#19490]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

My iPhone's region is set to Hungary, which means the decimal separator is a `,` instead of a `.`, which results in "Message malformed" error when trying to input a decimal number into a `numeric state` field inside an automation.

### Describe the behavior you expected

Either take into account the decimal separator corresponding to the user's region or allow a larger set of decimal separators in numeric fields (don't know if other regions have anything else besides `.` and `,`) Using `.` as a separator should probably always work regardless of region, to not accidentally break anything.

### Steps to reproduce the issue

Described above.

### What version of Home Assistant Core has the issue?

2024.1.4

### In which browser are you experiencing the issue with?

iOS HA app, iOS Safari

### Which operating system are you using to run this browser?

iOS 17.2.1

**Comment by Cyberbeni** [comment]
![image](https://github.com/home-assistant/frontend/assets/8356175/b142b4f2-d154-41c5-8b6f-c15fcfda0b39)

**Comment by karwosts** [comment]
Related #18268, #18012

**Comment by karwosts** [comment]
unstale
