### ISSUE TITLE
Conditional cards with one condition always resolve true

### ISSUE THREAD

**Issue by robchandhok** [home-assistant/frontend#19492]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Was using a conditional card to show/hide information for a weather station based on it's availability, and noticed that the card was showing even when the condition failed. With some testing I believe it only is wrong when there is a single condition - I "test" the condition and it says it fails, but the card shows regardless.

I found the issue using a vertical stack card, but verified the same behavior with a simple markdown card.

<img width="962" alt="Screenshot 2024-01-20 at 10 56 43 AM" src="https://github.com/home-assistant/frontend/assets/10090570/6e9658e5-a453-4334-9701-67a3d7d3d503">

### Describe the behavior you expected

I expected the card to not be shown. 

### Steps to reproduce the issue

Even if the forecase is "unavailable", the card shows.  I tried with boolean sensors as the condition as well.

```
type: conditional
conditions:
  - condition: state
    entity: weather.forecast_woodhaven
    state_not: unavailable
card:
  type: markdown
  content: The Weather station is ok?
```

### What version of Home Assistant Core has the issue?

core-2024.1.4

### In which browser are you experiencing the issue with?

Chrome 121.0.6167.75 (Official Build) beta (x86_64)

### Which operating system are you using to run this browser?

MacOS 13.6.3

**Comment by karwosts** [comment]
Your example works as expected for me. Created the card, set the state to unavailable in devtools, and it instantly disappeared as expected.

Just to make sure, you're not in edit mode when you're seeing this? Conditional cards are always shown in edit mode.

**Comment by robchandhok** [comment]
Thanks for the prompt response! 

Not in Edit mode, I get why it always shows.  I was completely able to reproduce.

In the meantime, I updated to core-2024.1.5 and now I can't reproduce it either.

So I will close it.
