### ISSUE TITLE
Search in automations is diacritics sensitive

### ISSUE THREAD

**Issue by Dehumanizer77** [home-assistant/frontend#19504]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I believe this is a bug, as every other search does not do that.
The problem is that if I search among automations, it does differentiate between for example á and a. If an automation's name is ááá and I search for a, it does not show the automation which it should. Search among entities and at other places works as expected.

### Describe the behavior you expected

searching e.g. for "á" and "a" should produce the same results

### Steps to reproduce the issue

1. create an automation with a letter with diacritics, e.g. á
2. go to automation seach box and type "a"
3. the automation created in step 1 will not appear among the search results
...

### What version of Home Assistant Core has the issue?

2024.1.4

### What was the last working version of Home Assistant Core?

none

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

Linux Mint 21.3

**Comment by Dehumanizer77** [comment]
This is still an issue.

**Comment by piitaya** [comment]
Should be fixed with https://github.com/home-assistant/frontend/pull/21150. It's included in 2024.7 release. Don't hesitate to re-open the issue if it's not really fixed.

**Comment by Dehumanizer77** [comment]
Perfect, works fine, thank you!
