### ISSUE TITLE
Tuya integration does not support the Tuya smart Android application

### ISSUE THREAD

**Issue by ilguvat** [home-assistant/frontend#19539]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Tuya integration does not support the Tuya smart Android application. Adds only sensors from the Smart Life application. The site iot.tuya.com adds sensors from both applications without problems. The problem only occurs when adding sensors to the integration. The profile on iot.tuya.com has Individual Developer rights. I also noticed that when you restart the integration in HA, in the API log tab you can see that the request passes, but new or current devices do not appear. Can anyone help? Or point out what I'm doing wrong!?

### Describe the behavior you expected

After adding the Hub to the integration, sensors from the Smart Life application appeared within 3-5 minutes. I think that sensors should also be added with Tuya Smart.

### Steps to reproduce the issue

1.add a cloud project to iot.tuya.com
2.authorize the application via Add App Account.
3.After a new entry appears, the number of sensors connected to the application will become visible.
4.Add a Hub indicating the Access ID/Access Secret and login/pass of the Tuya application.

### What version of Home Assistant Core has the issue?

2024.1.5

**Comment by karwosts** [comment]
This has nothing to do with frontend, sounds like should be a core issue.
