### ISSUE TITLE
Costs are incorrectly calculated

### ISSUE THREAD

**Issue by lancealtena** [home-assistant/frontend#19538]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

![image](https://github.com/home-assistant/frontend/assets/47019816/6cce9880-5aec-4d34-97d0-c46e252a0217)

Costs are incorrectly calculated as evident from the screenshot. My meter is Wh, pricing is $0.32/kWh for consumption. $0.05/kWh for feed-in. It seems to be correct at first (see comparison), but then goes completely off the rails.

### Describe the behavior you expected

17kWh * 0.32 = $5.44, not $86

### Steps to reproduce the issue

1. Go to dash
2. Wait a while
3. Look at costs 
...

### What version of Home Assistant Core has the issue?

2024.1.5

### What was the last working version of Home Assistant Core?

never worked

### In which browser are you experiencing the issue with?

Safari Version 17.2.1 (19617.1.17.11.12)

### Which operating system are you using to run this browser?

Sonoma 14.2.1

**Comment by karwosts** [comment]
Cost sensor is generally created and maintained by the backend energy integration, this is not something the frontend really controls. 

If you find and load the cost statistic for this in a statistics graph card, does it show similar issue for that period?

**Comment by lancealtena** [comment]
This is the statistics sensor:

[A graph on a screen  Description automatically generated]

[A graph on a screen  Description automatically generated]

It is 9am here in Brisbane and this is the cost, which seems correct:

[A screenshot of a phone  Description automatically generated]


From: karwosts ***@***.***>
Date: Saturday, 27 January 2024 at 23:54
To: home-assistant/frontend ***@***.***>
Cc: Lance Altena ***@***.***>, Author ***@***.***>
Subject: Re: [home-assistant/frontend] Costs are incorrectly calculated (Issue #19538)

Cost sensor is generally created and maintained by the backend energy integration, this is not something the frontend really controls.

If you find and load the cost statistic for this in a statistics graph card, does it show similar issue for that period?

**Comment by karwosts** [comment]
Your pictures didn't make it to github. Better try commenting directly instead of email.
