### ISSUE TITLE
Map card does Not show entities without lat/long but does show their tracks

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#19549]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

person entities lose their lat/long when home and source is network tracker.

because of that, they can not be displayed in the Map card.

one would expect an empty Map because of that, but instead, this is showing:

<img width="226" alt="Scherm­afbeelding 2024-01-28 om 00 58 37" src="https://github.com/home-assistant/frontend/assets/33354141/cbd6176b-442f-4dad-9e6f-2b73f28fde14">

the tracks of the configured person trackers are displayed alright.

### Describe the behavior you expected

an empty Map.

Ofcourse, it would be much better if these entities would not lose lat/long, but apparently that is believed to be a correct situation.

and if that is the case, the tracks should nt be displayed either. this is just plain silly

### Steps to reproduce the issue

1. use person entities with wifi and gps trackers
2. check map
3.
...

### What version of Home Assistant Core has the issue?

2024.1.5

### In which browser are you experiencing the issue with?

anu

### Which operating system are you using to run this browser?

any

### Javascript errors shown in your browser console/inspector

```txt
no errors
```

### Additional information

issue in core: https://github.com/home-assistant/core/issues/61299

is closed being stale, though still persistent...

**Comment by karwosts** [comment]
I'm not really convinced that the traces should be removed just because the person has gone unavailable (or the geolocation equivalent of unavailable). 

E.g. we don't hide a sensors history graph just because it has become temporarily unavailable, and I would consider this somewhat equivalent. Someone may still want to view the history of a person, even if that person can't be currently located. 


If you're upset about your initial core issue being closed for stale, than please just reopen it as a new ticket so it is no longer stale.

**Comment by Mariusthvdb** [comment]
Tbh, at first I also figured keeping the traces might not be a fluke .

until you realize they can not be traced to a person anymore… they’re just lines now and no clue whose they are.

besides, these person are Not unavailable nor is their position unknown: they are home!

The core issue is lat/long is gone, but that shouldn’t stop a Map card from showing. 

But even while doing so, and keeping the traces, make these useful and meaningful by showing whose trace it is

**Comment by karwosts** [comment]
Yeah I agree adding the person name to the trace tooltip would be a reasonable request. 

I'm less sure about plotting entities where lat/lng is not present. Yeah you could just assume they are at the center of their current zone, but that could have weird/undesirable effects if user have big zones (city/country size), that could give wildly inaccurate representation of their position. I think that would be better addressed in core personally.

**Comment by Mariusthvdb** [comment]
> that could give wildly inaccurate representation of their position.

state 'home' would not be inaccurate I suppose....
