### ISSUE TITLE
Stiebel Eltron integration sensors showing as unavailable

### ISSUE THREAD

**Issue by jeffjsmith33** [home-assistant/frontend#19544]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since updating from2023.11.2 to 2024.1.5 I have a consistent problem with sensors showing as 'unavailable' rather than showing the correct values.  I reverted to 2023.11.2 and all worked again correctly. I tried the update again and and again sensors showed as 'unavailable'.  I reverted again, and they worked again. 

### Describe the behavior you expected

The sensors have been displayed correctly for over six months and the issue is reproducible.

### Steps to reproduce the issue

1. Update to 2024.1.5
2. Run HA with the STIEBEL ELTRON integration
3. Check the value of e.g. Actual buffer temperature
4. See it displays as unavailable.
...

### What version of Home Assistant Core has the issue?

Core 2024.1.5

### What was the last working version of Home Assistant Core?

Core 2023.11.2

### Which operating system are you using to run this browser?

Mac OS 14.2.1 (23C71)

**Comment by karwosts** [comment]
Frontend does not control sensor states. This needs to be filed as a core issue against the integration.

**Comment by jeffjsmith33** [comment]
My apologies - I don't know enough of the inner workings of the software.  How would I reassign this issue report?

Thanks, Jeff

**Comment by karwosts** [comment]
Just go to https://github.com/home-assistant/core/issues/ and fill out the form there.

**Comment by jeffjsmith33** [comment]
Ah - I see - thanks again.  Done.
