### ISSUE TITLE
Statistical Calculation for a weekly value doesn't account for the week start date

### ISSUE THREAD

**Issue by luissimoes** [home-assistant/frontend#19566]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have a sensor, which tracks the cumulative energy consumed.
When creating a statistics card, and choosing "week" for the report, it **counts the energy from Monday to Sunday.**
In my case:
- the calendar defines Sunday as start of the week
- the sensor has a CRON 00**7
so the sum should be from Sunday to Saturday

-- this problem is confirmed as if I create a graph in Plotly it shows the same result - but not in Apex, where I can manipulate the days to be counted

Files:
Result of the graph (wrong) and the sensor itself (resets correctly)
(I am adding screenshots with the mouse hovering so that the values are visible) - it is also clear that the counting starts eg on the 8th instead of the 7th

<img width="484" alt="Screenshot 2024-01-29 at 15 45 43" src="https://github.com/home-assistant/frontend/assets/42578174/848173cd-5e4b-47cd-8e28-f02d6c3db1db">
<img width="504" alt="Screenshot 2024-01-29 at 15 44 25" src="https://github.com/home-assistant/frontend/assets/42578174/4ea6e2d7-f8be-42a9-9b80-92ff7ec96e2c">
<img width="505" alt="Screenshot 2024-01-29 at 15 44 18" src="https://github.com/home-assistant/frontend/assets/42578174/e7522c79-06b1-4d65-b6e0-efb2a3a534a8">
<img width="467" alt="Screenshot 2024-01-29 at 15 44 09" src="https://github.com/home-assistant/frontend/assets/42578174/6168d2b7-a7b8-4e5c-b742-64776a4948cc">

The Sensor itself
<img width="1277" alt="Screenshot 2024-01-29 at 15 56 03" src="https://github.com/home-assistant/frontend/assets/42578174/02cde290-4014-4b4c-a011-c854f6fd1500">
<img width="1334" alt="Screenshot 2024-01-29 at 15 55 53" src="https://github.com/home-assistant/frontend/assets/42578174/ba5806d1-3146-47b5-ac59-13130dc940e3">
<img width="1303" alt="Screenshot 2024-01-29 at 15 55 41" src="https://github.com/home-assistant/frontend/assets/42578174/aecabc9b-2799-41df-a3d0-630ffe3a239e">

### Describe the behavior you expected

Expected: sum of the energy from Sunday to Saturday (as shown below, with a graph done with Apex, where the parameters were defined to counterbalance the problem) 

<img width="484" alt="Screenshot 2024-01-29 at 15 36 01" src="https://github.com/home-assistant/frontend/assets/42578174/14cec686-529f-4cba-abe6-54cc2035b009">

### Steps to reproduce the issue

1. create a sensor collecting info for a week
2. sensor should reset on Sunday i.e. Sunday 00:00:00 has a value 0 (zero)
3. define Sunday as start of the week in calendar
4. create a graph
...

### What version of Home Assistant Core has the issue?

2024.1.5

### In which browser are you experiencing the issue with?

Safari Version 17.2.1 (19617.1.17.11.12) and Firefox 121.0.1 (64-bit)

### Which operating system are you using to run this browser?

macOS Sonoma 14.2.1 - and iOS 17.3 and MacOS 17.3

### State of relevant entities

<img width="812" alt="Screenshot 2024-01-29 at 15 58 19" src="https://github.com/home-assistant/frontend/assets/42578174/24bebbbb-8279-444c-a58a-3a6d10ac6ce4">

### Problem-relevant frontend configuration

`mt1681_weekly_energy:
  unique_id: "mt1681-weeky"
  source: sensor.bitshake_smartmeterreader_mt681_total_in
  name: From netz weekly
  cron: "0 0 * * 7"`

**Comment by karwosts** [comment]
I think this is going to have to be a core issue. The frontend has a per-user control for preferred day of the week for showing calendars, but the backend statistics aggregation calculation for weeks is not configurable, it just uses simply the python time.weekday() function to compute the start of the week, so that's hardcoded to monday. 

If user is to be able to choose the statistics aggregation period for weeks, that would have to be an additional core setting, but there's nothing we can do from frontend.

**Comment by luissimoes** [comment]
Ok thanks  - since this prevents the system from giving correct information and in fact gives wrong information seems to me it should be resolved 

how does this move to core? Can you transfer?
Or do I have to copy and paste?

thanks

**Comment by luissimoes** [comment]
I opened a new bug for core
