### ISSUE TITLE
Helper: Combine the state of several sensors - does not transfer "device_class"

### ISSUE THREAD

**Issue by home409ca** [home-assistant/frontend#19605]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I used the helper to calculate the average temperature in the house.
Each sensor has a parameter: device_class: temperature

Unfortunately, the midfielder has no class...

Additionally, in the history graph, it is displayed on separate graphs, despite the same unit.

![image](https://github.com/home-assistant/frontend/assets/114701129/8de9e3c9-d8c6-4066-ace1-1917940bb608)

### Describe the behavior you expected

The input entities and the helper will be displayed in one chart.

### Steps to reproduce the issue

Create a helper that calculates the average temperature in your home. Add input and output sensors to the history graph.

### What version of Home Assistant Core has the issue?

2024.1.6

**Comment by karwosts** [comment]
This should be a home-assistant/core bug, The frontend is not responsible for setting the device_class of entities.
