### ISSUE TITLE
Blue icons in "Add action" popup in automation edit page

### ISSUE THREAD

**Issue by tetele** [home-assistant/frontend#19601]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When editing an automation and adding a new action, the popup with the available actions displays icons next to each action. Most are dark gray, but some are blue.

![add_action](https://github.com/home-assistant/frontend/assets/920098/f803723b-168a-46b2-9017-f33af4aba89f)

### Describe the behavior you expected

All icons are the same color

### Steps to reproduce the issue

1. Create a new automation or edit an existing one
2. Click "Add action"
3. Notice that some icons are blue

### What version of Home Assistant Core has the issue?

2024.2.0b0

### What was the last working version of Home Assistant Core?

2024.1.5

**Comment by bramkragten** [comment]
I'm not able to reproduce this, are there any errors in your logs?

**Comment by tetele** [comment]
No, but I can't reproduce it myself anymore 🤔 @karwosts [managed](https://discord.com/channels/330944238910963714/427516175237382144/1202390887121039462) to reproduce it and @piitaya talked about [what the cause might be](https://discord.com/channels/330944238910963714/427516175237382144/1202393449626603560).

Not sure if this helps

**Comment by piitaya** [comment]
If the domain icon is not found, we fallback to brand icon. @tetele Are you sure your system was ready when you experimented this issue? If a domain is not loaded, the icon will not be found and the front-end will fallback to brand image (and it's a blue icon).

**Comment by tetele** [comment]
I can't answer that, @piitaya. I don't know what domains/components were loaded and which not at the time. It was hours after booting up.

However, there's no guarantee that unused domains will be loaded until you start creating an automation, i guess.
