### ISSUE TITLE
Energy dashboard showing negative values after ~10 days without data

### ISSUE THREAD

**Issue by pablogonzalezalba** [home-assistant/frontend#19610]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have a Dutch dsmr device connected via P1 that shares my energy data via mqtt. On January 20th the device stopped informing but I noticed it today, February 1st. It was disconnected from mqtt and a simple reboot fixed it. This is not a problem with the device.

However, I didn't get energy data for ~10 days. And now my energy dashboard for today shows this graph:
<img width="977" alt="firefox_0ZVVdKDSoL" src="https://github.com/home-assistant/frontend/assets/3166499/d2be299c-7750-4e93-8ff2-9abba6f5323f">
A huge negative bar for both electricity and gas at the time it was reconnected, and no updates afterwards (It's 17hs currently, so there should be info from 10 to 16 at least).

To discard a wrong value being sent by the device, I checked the history of the entities:
<img width="757" alt="firefox_ISl1vamXAI" src="https://github.com/home-assistant/frontend/assets/3166499/7211e25a-a716-4872-bc80-c8be4f9e420a">

The graph (and the data) shows correctly what happened, stopped on the 20th, some random reading on the 23rd, then back on the 1st, and updating again. The new values are indeed higher than the last recorded values, so it seems the sensor has the correct data. This is why I think this is a frontend issue of the Energy Dashboard.

### Describe the behavior you expected

I expect today to see a huge bar in the positive side, that accumulates all the info from the 10 days it was disconnected. For all 3 entities: gas, electricity low and electricity high.

### Steps to reproduce the issue

Not sure how to reproduce it except by having my data.

### What version of Home Assistant Core has the issue?

core-2024.1.6

### In which browser are you experiencing the issue with?

Firefox 121.0.1 (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
These are the values of the entity `sensor.dsmr_consumption_gas_delivered` at the last point it received data before being disconnected on Jan 20th. And then the first one Feb 1st, and the last one on Feb 1st (it continues to grow so it received data correctly).

2024-01-20 15:00 - 491.12
2024-02-01 10:39 - 559.27
2024-02-01 17:11 - 561.27
```

**Comment by karwosts** [comment]
The energy board uses *statistics* not history. Can you please show those same graphs but with a statistics-graph-card instead of the history, and showing state/sum/change?

I would bet there is a statistics showing it being reset-to-zero in there, which would explain that. And that would be a core issue.

**Comment by pablogonzalezalba** [comment]
Thanks for the quick reply.

<img width="379" alt="firefox_apPIb9Sejs" src="https://github.com/home-assistant/frontend/assets/3166499/8931f524-72e0-42d3-ad1c-c270b925bf6c">
<img width="384" alt="firefox_au3xdS0qcL" src="https://github.com/home-assistant/frontend/assets/3166499/79ad2186-694e-4b6f-ae1e-c594cd73613c">
<img width="382" alt="firefox_op6d2wnXVw" src="https://github.com/home-assistant/frontend/assets/3166499/63615f7e-d4d5-42fc-b916-5e15a83d62f8">

---

<img width="377" alt="firefox_75zm6n7Pck" src="https://github.com/home-assistant/frontend/assets/3166499/fee62733-5fdf-4827-a699-28eb6896ed2c">
<img width="373" alt="firefox_DF5riTP5OO" src="https://github.com/home-assistant/frontend/assets/3166499/11c2b0cc-b261-4388-9584-e20ec57d46af">
<img width="382" alt="firefox_isjxHhIccl" src="https://github.com/home-assistant/frontend/assets/3166499/03bb5cfd-b715-4ba6-a412-39105e7e0c98">
<img width="373" alt="firefox_mVMlxkikNP" src="https://github.com/home-assistant/frontend/assets/3166499/22a2662a-56cd-4599-8387-d04cd53752fb">

Here they are, but I don't understand them. State looks correct, sum and change are negative and that must be the problem, then?

**Comment by karwosts** [comment]
Yeah I don't quite know what's happening there, but you do seem to have some bad data in your stats. 

In devtools/statistics you can use the adjust dialog to correct it, but as for the original source of the problem, that would be something in core, recorder integration.

**Comment by pablogonzalezalba** [comment]
Thanks for the help! I'll report it to core then and try to fix it in devtools.
