### ISSUE TITLE
Bluetooth failed upon start

### ISSUE THREAD

**Issue by moinahmed001** [home-assistant/frontend#19625]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

<img width="1015" alt="Screenshot 2024-02-02 at 9 43 52 am" src="https://github.com/home-assistant/frontend/assets/17249656/06d3b263-9536-44a7-883f-b72d5e868440">
Please see attached screen. Saw this in 2024.1.5 and now also exists in 2024.1.6.
I have attempted to use the Switchbot Bluetooth interface recently and started noticing this issue

### Describe the behavior you expected

Bluetooth to work

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.1.6

**Comment by karwosts** [comment]
Please file in home-assistant/core, bluetooth functionality is not related to frontend.
