### ISSUE TITLE
Button card Icons are light grey

### ISSUE THREAD

**Issue by pjannink** [home-assistant/frontend#19645]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Icons in buttons were black in 2024.1 but now most are light grey. Only some are still black

### Describe the behavior you expected

All icons remain black

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.2.0b3

### What was the last working version of Home Assistant Core?

2024.1.6

### In which browser are you experiencing the issue with?

Firefox 122.0

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
N/A. Concerns buttons. See attached PDF
```

### Additional information

[icon issue HA.pdf](https://github.com/home-assistant/frontend/files/14151089/icon.issue.HA.pdf)

**Comment by codyc1515** [comment]
Where are you seeing that?

**Comment by pjannink** [comment]
These are buttons on my dashboard. See the PDF.
I run 2023.1.6 in Docker and 2024.2.02b in a VM with HAOS

**Comment by karwosts** [comment]
I guess this was probably changed by https://github.com/home-assistant/frontend/pull/19591

I am not sure if it was intentional or accidental change or not. 


Some were discussing this in the beta channel as well (off entities used to have the light blue color, now they are grey). 
![image](https://github.com/home-assistant/frontend/assets/32912880/8b85b44b-2c28-4e25-890d-7e9c41ca68a6)

**Comment by karwosts** [comment]
I tag this for the Beta, maintainers can review and close if it was intentional or not.

**Comment by mikedahlgren** [comment]
> I guess this was probably changed by #19591
> 
> I am not sure if it was intentional or accidental change or not.
> 
> Some were discussing this in the beta channel as well (off entities used to have the light blue color, now they are grey). ![image](https://private-user-images.githubusercontent.com/32912880/302108603-8b85b44b-2c28-4e25-890d-7e9c41ca68a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNjcxMzksIm5iZiI6MTcwNzA2NjgzOSwicGF0aCI6Ii8zMjkxMjg4MC8zMDIxMDg2MDMtOGI4NWI0NGItMmMyOC00ZTI1LTg5MGQtN2U5YzQxY2E2OGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDE3MTM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0Y2MxMmVhYjU2YzU5OWYyOGViZGNiMDRmOWI1MGNkYjRmYzAwZTFjMzhkMjY5YzE1ODM3ZmRjMGNlZmE4ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.80leARHu3ly-lr5X0Kl22WBUC8mgzLRV_F1nN0lABsk)

In this screenshot the "South Door" is unavailable while the "South Lights" are just off.

**Comment by dmulcahey** [comment]
> > I guess this was probably changed by #19591
> > I am not sure if it was intentional or accidental change or not.
> > Some were discussing this in the beta channel as well (off entities used to have the light blue color, now they are grey). ![image](https://private-user-images.githubusercontent.com/32912880/302108603-8b85b44b-2c28-4e25-890d-7e9c41ca68a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNjcxMzksIm5iZiI6MTcwNzA2NjgzOSwicGF0aCI6Ii8zMjkxMjg4MC8zMDIxMDg2MDMtOGI4NWI0NGItMmMyOC00ZTI1LTg5MGQtN2U5YzQxY2E2OGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDE3MTM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0Y2MxMmVhYjU2YzU5OWYyOGViZGNiMDRmOWI1MGNkYjRmYzAwZTFjMzhkMjY5YzE1ODM3ZmRjMGNlZmE4ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.80leARHu3ly-lr5X0Kl22WBUC8mgzLRV_F1nN0lABsk)
> 
> In this screenshot the "South Door" is unavailable while the "South Lights" are just off. Extremely confusing.

Completely agree. This threw me off after I installed the beta as well. I first thought I had a ton of stuff offline 😬

**Comment by piitaya** [comment]
It was not intentional. Thank you for reporting the issue. I open a PR to fix the bug.
