### ISSUE TITLE
Automations Add Action Screen

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#19657]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Automations Add Action Screen
![image](https://github.com/home-assistant/frontend/assets/42905545/662870b2-3310-455d-b7b6-bf5d8938a319)

### Describe the behavior you expected

*

### Steps to reproduce the issue

*

### What version of Home Assistant Core has the issue?

2024.2.0b3

**Comment by codyc1515** [comment]
Raise here please https://github.com/frenck/spook/issues

**Comment by TheFes** [comment]
To me it's completely unclear what your actual issue is

**Comment by codyc1515** [comment]
If I had to guess, it’s the Spook icon falling to the next line - but this is a 3rd-party mod.
