### ISSUE TITLE
Wrapup messaging can show during onboarding

### ISSUE THREAD

**Issue by codyc1515** [home-assistant/frontend#19663]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

![image](https://github.com/home-assistant/frontend/assets/50791984/2ebe7512-0a3a-4db9-9c94-6634b0d2ffd1)

### Describe the behavior you expected

This messaging should not be shown.

### Steps to reproduce the issue

I believe this happened because it was in a Codespaces development environment and we started _after_ config folder was created (with defaults) but _before_ I had completed the UI set-up.

### What version of Home Assistant Core has the issue?

main

**Comment by silamon** [comment]
I think this is to be expected since integrations are loaded during startup if you're in onboarding or not. In the last onboarding step, integrations are shown with discovery or with an onboarding config flow. If you get there and it is still not started up, you may want to wait.

**Comment by codyc1515** [comment]
I have never seen this during onboarding before. I don't think it's a super-high priority to fix but seems an issue nonetheless. I also wonder if this could maybe cause other unexpected issues that are not immediately apparent because it is loading some integrations during onboarding that would normally not be.

**Comment by codyc1515** [comment]
I think this is expected.
