### ISSUE TITLE
Search box doesn't work for searching home assistant logs

### ISSUE THREAD

**Issue by alexd321** [home-assistant/frontend#19678]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Search box does not work on home assistant android app, or in chrome (or edge)

### Describe the behavior you expected

Tapping on search or the magnifying glass should show a text box and be able to type (like on desktop)

https://github.com/home-assistant/frontend/assets/69210910/8b50c212-5240-46c0-a9b6-3b8b11d3863c

### Steps to reproduce the issue

1. Open settings
2. Open system
3. Open logs - tapping search does nothing
...

### What version of Home Assistant Core has the issue?

2024.1.6

### What was the last working version of Home Assistant Core?

Unknown, has been broken for as long as i can remember

### In which browser are you experiencing the issue with?

Chrome 121.0.6167.143

### Which operating system are you using to run this browser?

Android 14

### Additional information

Logged initally as andorid bug, but it is frontend

**Comment by karwosts** [comment]
I can see this also in desktop browser, but only in narrow mode, and only when using a supervised install. 

Something about the way the supervisor log selection button overlays the search bar blocks its interaction.

**Comment by karwosts** [comment]
Ah I think this may have already been fixed by

https://github.com/home-assistant/frontend/pull/19355

**Comment by karwosts** [comment]
I believe this is fixed, let me know if it's still not working in 2024.2
