### ISSUE TITLE
State Badge in Picture Elements does not show label/legend with entity name any more (2024.2.0bx)

### ISSUE THREAD

**Issue by timiman** [home-assistant/frontend#19673]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

From 2024.2 betas and on, the state-badge object does not show the name of the entity if used inside a picture element object.

### Describe the behavior you expected

On previous versions like 2024.01 and earlier, there was a label with the full name of the entity attribute under the state badge.
Are there ongoing changes on picture element and/or state-badge that should hide/show that label ?  

### Steps to reproduce the issue

1. On the UI, add a new card based on a picture element
2. Add a state-badge for an entity attribute ( ex. temperature of a sensor )
3. View the card on UI

### What version of Home Assistant Core has the issue?

2024.2.0b5

### What was the last working version of Home Assistant Core?

2024.1.x

### In which browser are you experiencing the issue with?

Firefox

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
Oh sorry, actually as soon as I commented this I noticed that the text was there, but it was the same color as the background image, so I couldn't see it. Yes I see what you mean now.

**Comment by karwosts** [comment]
It's a bit odd, but looking at the code and the documentation, it seems like maybe this element was never intended to show a name below the badge, but it may have been an unintended bug that it was displaying. 

It has a configurable _tooltip_ which shows the name when you hover over it, which can be configured with the `title` option. 

I guess we could add an option to also show the name there, but I'm not 100% convinced, it seems kind of sloppily displayed and the line breaks don't work well. Is that some feature you want to see, something you were relying on?

**Comment by karwosts** [comment]
As for technically what changed, this was a case where a previously undefined boolean `showName` is now initialized to false in `ha-state-label-badge`.

This cause the badge to not attempt to show a name, which was autogenerated from the state object. The name was not previously configurable. The name used to only be hidden if showName was explicitly set to false.

**Comment by timiman** [comment]
Yes, it is sloppy to show so many characters under the state-badge but it was helpful in my usage scenario. I do have a map of the house that has on it state-badges showing temperatures, wattages, humidities, door sensors etc. The title object is ok on a PC, but on a mobile device like a cellphone there is no tooltip behavior like moving a mouse over the state-badge. I can tell that having the ability to have a custom text under the state-badge is the perfect solution. But I can live with a boolean attribute on state-badge to show/hide its entity name/attribute string.
