### ISSUE TITLE
Energy screen not streched to maximum size of axis x

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#19679]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In HA enter to Energy screen you can see (attached video from 00:00) the graphic aren´t stretch to maximum of axis x.
After click to .../compare data/ (video in 00:07) you can see page content is stretched more to maximum of axis x.
After reload the page by F5 (video in 00:23) is again whole graphic on not stretched visibility.

This was checked via PC Edge 122.0.2353.0 64bit and Android mobile phone.
Same issue happened for both testing systems.

https://github.com/home-assistant/frontend/assets/61636045/3ae73519-1af8-4bf7-b6fa-6d64218f094c

### Describe the behavior you expected

Energy screen extend to maximum size of x axis.

### Steps to reproduce the issue

1. showed in attached video

### What version of Home Assistant Core has the issue?

2024.1.6

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Edge 122.0.2353.0

### Which operating system are you using to run this browser?

Win10 + Android

**Comment by karwosts** [comment]
Can you confirm you _really_ tried safe mode? This was reported a lot last month and it was due to custom plugins.

**Comment by misa1515** [comment]
skiped, sorry. After checking I will share result here.

**Comment by misa1515** [comment]
@karwosts thank you for suggestion.
Run in safe mode - issue is gone.
Then restarted and issue is gone too.
I not understand it, why is now working again like is expected (no any unistall or upgrade...).
