### ISSUE TITLE
Add Entity Stuck

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#19695]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Add entity to dashboard is stuck, everything in UI is slow
![image](https://github.com/home-assistant/frontend/assets/42905545/1035c351-36b6-463f-a3da-d63d2b35aa34)

### Describe the behavior you expected

*

### Steps to reproduce the issue

*

### What version of Home Assistant Core has the issue?

2024.2.0b8

**Comment by karwosts** [comment]
Same as #19725
