### ISSUE TITLE
Virtual integration add button translation text is not visible on ha-config-integration-page

### ISSUE THREAD

**Issue by codyc1515** [home-assistant/frontend#19697]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

![2024-02-06 19_49_03-](https://github.com/home-assistant/frontend/assets/50791984/b0adda8b-6c62-4b82-95ab-9d55494eae96)

### Describe the behavior you expected

Text for the button should be showing

### Steps to reproduce the issue

Browse to /config/integrations/integration/bge

### What version of Home Assistant Core has the issue?

main

**Comment by silamon** [comment]
To add: 
* the title above "no entries" is also missing
* when you click the button with invisible text, the virtual integration is loaded and cannot be started, since we don't read supported by correctly on that page
