### ISSUE TITLE
Dashobard will show Templates

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#19710]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After few Hours when is Dashboard Opened make this will show templates, never this problem have before new beta release, and many other problems on every corner.
![image](https://github.com/home-assistant/frontend/assets/42905545/0eab97da-e19a-410c-bbe4-ed04b71d1027)

### Describe the behavior you expected

*

### Steps to reproduce the issue

*

### What version of Home Assistant Core has the issue?

2024.2.0b8

**Comment by bramkragten** [comment]
This is an issue with a custom card, not with core.
