### ISSUE TITLE
Multiple localized strings have reverted to English (despite being translated in Lokalise) [Multiple languages affected]

### ISSUE THREAD

**Issue by ulrikjo** [home-assistant/frontend#19713]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In the current beta (2024.2.0b11) multiple localized strings in Danish (Edit: It seems Ukrainian and Turkish are also affected) have reverted to English despite being translated in Lokalise for a long time. In the last stabile release (2024.1.6) there was no problems. I tested two other languages and it did not seem to affect them. The issue is seen in multiple browsers and in the mobile companion app.

The strings are:
"off" (`common::state::off`);
"closed" (`component::cover::entity_component::_::state::closed`);
"Latest version" (`component::update::entity_component::_::state_attributes::latest_version::name`);
"Installed version" (`component::update::entity_component::_::state_attributes::installed_version::name`)

Screenshots included of the strings in the UI. The "off" string can be seen in entity dialogs and in tiles in dashboards. The "closed" string can be seen in entity dialogs for covers. The "Latest version" and "Installed version" strings can be seen in the dialog when installing updates. The screenshot of "Latest version" and "Installed version" was taken when updating from 2024.2.0b10 to 2024.2.0b11, and I have not been able to trigger the update dialog after the update to 2024.2.0b11 but I assume the problem is still present as it has been in the last few β.

![TilesInDashboard](https://github.com/home-assistant/frontend/assets/53315889/ff928074-5fd0-4d8f-9382-972b4b3d39c8) _TilesInDashboard_

![TileInDashboard](https://github.com/home-assistant/frontend/assets/53315889/c4fdc6f4-8cc1-436c-a52a-8d03bd48b453) _TileInDashboard_

![LightEntityDialog](https://github.com/home-assistant/frontend/assets/53315889/289fc42b-7483-44b9-926d-cbdb32bf58b1) _LightEntityDialog_

![CoverEntityDialog](https://github.com/home-assistant/frontend/assets/53315889/1810fd12-fa36-4a99-b490-4cad3e9858d9) _CoverEntityDialog_

![UpdateDialog](https://github.com/home-assistant/frontend/assets/53315889/5bd68878-6d5f-4751-9487-dfb8c3dd48b5) _UpdateDialog_

Screenshots of the strings in Lokalise. The strings have been translated for a long time.

![StringsInLokalise](https://github.com/home-assistant/frontend/assets/53315889/54da3f64-570e-4923-aa3f-b06953b6adf5) _StringsInLokalise_

### Describe the behavior you expected

The strings are expected to still be in Danish in the beta as they were in the last stabile release and the strings have been translated in Lokalise for a long time.

### Steps to reproduce the issue

Prereqs: Home Assistant Core 2024.2.0b11; frontend language set to Danish; entities that can have the state "Off"; and an update available

1. Open an entity dialog for an entity that is "Off". Observe the string being shown as "off" and not "Fra"
2. Look at dashboard tiles of entities with the state shown as "Off". Observe the string being shown as "off" and not "Fra"
3. Open an entity dialog for a cover entity that is "Closed". Observe the string being shown as "closed" and not "Lukket"
4. With an update available, click the update to open the update dialog. Observe the strings being shown as "Latest version" and "Installed version", and not in Danish as "Nyeste version" and "Installeret version".

### What version of Home Assistant Core has the issue?

2024.2.0b11

### What was the last working version of Home Assistant Core?

2024.1.6

### In which browser are you experiencing the issue with?

Safari 17.3 (19617.2.4.11.8); Microsoft Edge 121.0.2277.106; Companion App

### Which operating system are you using to run this browser?

macOS Sonoma 14.3

**Comment by ulrikjo** [comment]
Adding that the problems are also present in the public release, 2024.2.0

**Comment by creasoftua** [comment]
I have the same problem with Ukrainian language

**Comment by ulrikjo** [comment]
> I have the same problem with Ukrainian language

Thank you for the report! I can confirm that I also see the issue when switching to Ukrainian. I tested a few other languages, and it seems that at least Turkish is also affected.

Have you found additional strings that are affected?

**Comment by ulrikjo** [comment]
Issue was fixed in 2024.2.1 for Danish, Ukrainian, and Turkish. As there was no mention of a fix in the release notes for the frontend or Core I'm leaving this issue open in case someone wants to find the root cause for the problem. Feel free to close the issue.

**Comment by karwosts** [comment]
I think if it's fixed we can close. I'm not aware of any translation changes in these releases, maybe just had a corrupted translation file attached to the release or something.

**Comment by silamon** [comment]
Since what you've mentioned are core translations, you most likely got hit by https://github.com/home-assistant/core/issues/109910. It was fixed by ignoring faulty translations, instead of just stopping. Latest release should log the faulty translations as mentioned. If you want to help out, update to the latest release and check for any messages "Error while parsing localized" in the system logging, then report in the mentioned issue.
