### ISSUE TITLE
Predicted Card not working

### ISSUE THREAD

**Issue by Nisbo** [home-assistant/frontend#19725]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If I go to the Dashboard --> create Card --> entity --> search for an entity --> select the entity --> go to next --> the recommended window is empty.

![grafik](https://github.com/home-assistant/frontend/assets/26260572/02332828-12f3-4451-97dc-84372722affd)

![grafik](https://github.com/home-assistant/frontend/assets/26260572/90b6a855-16f6-449c-90c6-d84c16d705a7)

### Describe the behavior you expected

working as before

### Steps to reproduce the issue

If I go to the Dashboard --> create Card --> entity ( --> search for an entity --> select the entity --> go to next --> the recommended window is empty.

![grafik](https://github.com/home-assistant/frontend/assets/26260572/02332828-12f3-4451-97dc-84372722affd)

![grafik](https://github.com/home-assistant/frontend/assets/26260572/90b6a855-16f6-449c-90c6-d84c16d705a7)

### What version of Home Assistant Core has the issue?

2024.2.0

### In which browser are you experiencing the issue with?

Firefox 122.0.1 (64-Bit) and Chrome 121.0.6167.161

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
Likely broken by #19528
