### ISSUE TITLE
Automations not showing correctly in the Automation List

### ISSUE THREAD

**Issue by NReiher** [home-assistant/frontend#19721]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In the Automation listing page, automations show up with a red error sign and shows as never being triggered.

![image](https://github.com/home-assistant/frontend/assets/53537686/2d731d6b-41e2-4f67-a2cb-67a734050ae6)

Clicking on the automations it says "Automation is unavailable" and devices are missing.

![image](https://github.com/home-assistant/frontend/assets/53537686/7e02511d-69cb-496d-9e9a-ad61142fd797)

The automations themselves actually work and checking the actual Automation.yaml 

![image](https://github.com/home-assistant/frontend/assets/53537686/2c3ee769-4245-413f-8e59-a26f38ecaa54)

When trying to leave the automation after selecting it, it prompts to save the automation. (I have not applied the changes out of fear it's going to override the settings in the yaml / break things further).

Also occurs on the mobile app as well.

![image](https://github.com/home-assistant/frontend/assets/53537686/4dadb194-0261-4fee-b70b-96eb49eccbe2)

![image](https://github.com/home-assistant/frontend/assets/53537686/a97be596-c61a-4215-a511-0b7bea71f6b3)

![image](https://github.com/home-assistant/frontend/assets/53537686/ae5b5bd4-d8da-456f-8d64-d1a0b1fe7ea7)

### Describe the behavior you expected

Automations list populate properly. Being able to see the same automations as in the configuration file.

### Steps to reproduce the issue

1. Visiting the automations listing.

### What version of Home Assistant Core has the issue?

2024.2.0

### In which browser are you experiencing the issue with?

Google Chrome Version 121.0.6167.161 (Official Build) (64-bit) / Home Assistant Android app

### Which operating system are you using to run this browser?

Windows 10 22H2

### Additional information

Not sure if this is the correct place to report this. I did notice there was a [similar report](https://github.com/home-assistant/frontend/issues/19694) which MIGHT be a related issue? I did notice this issue after having to mess around with Zigbee2MQTT so perhaps the missing items are not displaying correctly for some reason? I feel like these have not displayed correctly for awhile, I just haven't noticed as I haven't messed with automations in some time. I only noticed while troubleshooting another issue (Z2M no longer seeing a switch due to a recent update).

I had pending updates for both HomeAssistant Core and I think the OS. I JUST updated the Core version before posting this in hopes it would help. From what I remember, I manually fixed one automation (one that was related to the switch thinking that's what caused it) but would like to address this if necessary in case it happens/breaks again.

If any additional information is needed to troubleshoot this, please let me know. First bug report so hopefully I did it right.

Thanks in advance.

**Comment by codyc1515** [comment]
Please attach the automations.yaml

**Comment by NReiher** [comment]
@codyc1515 Hi,

Here is the snippet of the example I posted.

- id: '1650744923168'
  alias: 54 - Front Porch Light State On
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.front_porch_lights_state
    from: 'off'
    to: 'on'
  condition: []
  action:
  - type: turn_on
    device_id: e1e9ede55a961d63db42b6ab2454f8c4
    entity_id: light.szl06_sengled_e11_g13_level_on_off
    domain: light
  - type: turn_on
    device_id: 6aa6265a52e0782120b43ea219997225
    entity_id: light.szl07_sengled_e11_g13_level_on_off
    domain: light
  mode: single
- id: '1650745111851'
  alias: 54 - Front Porch Light State Off
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.front_porch_lights_state
    from: 'on'
    to: 'off'
  condition: []
  action:
  - type: turn_off
    device_id: e1e9ede55a961d63db42b6ab2454f8c4
    entity_id: light.szl06_sengled_e11_g13_level_on_off
    domain: light
  - type: turn_off
    device_id: 6aa6265a52e0782120b43ea219997225
    entity_id: light.szl07_sengled_e11_g13_level_on_off
    domain: light
  mode: single

And here is the full automations.yaml if that is necessary.

[automations.zip](https://github.com/home-assistant/frontend/files/14209895/automations.zip)


The other automations that are having this problem:

![image](https://github.com/home-assistant/frontend/assets/53537686/30e5c48f-bda9-416b-aa7e-205cc6c89f07)

![image](https://github.com/home-assistant/frontend/assets/53537686/2b3c0d8b-a6c7-458c-8787-f873167d1000)

![image](https://github.com/home-assistant/frontend/assets/53537686/939f18e9-1565-479a-bfd3-d990a2c113b3)

![image](https://github.com/home-assistant/frontend/assets/53537686/1e776c46-5d13-429b-8c19-52bab5ce4093)

![image](https://github.com/home-assistant/frontend/assets/53537686/7919fd5e-0175-4f9c-bcdb-3bbd289204d7)


This was an older screenshot of one that also stopped working.
![image](https://github.com/home-assistant/frontend/assets/53537686/20b75287-c855-4c68-81a1-94a986ac3ec9)

I had manually fixed this one.

So ultimately it's just a few automations, but still is concerning that it's happening. As I'm looking more closely now, two of the broken ones are saying "domain:ZHA" so I'm wondering if they are holdovers from before I switched from ZHA > Z2Mqtt. But the porch lights are definitely on the new Z2M as well as the temp sensor. From what I can tell the automations themselves run fine, just are not displayed properly in the UI.


If anything else is needed please let me know. Thanks!

**Comment by bramkragten** [comment]
This is not a frontend issue, so closing.

**Comment by codyc1515** [comment]
If you hit F12, did you see any errors?
