### ISSUE TITLE
Tuya integration fails

### ISSUE THREAD

**Issue by tybo611** [home-assistant/frontend#19722]
### The problem

Tuya tries to reconfigure with the new verification process, but the final step generating QR code to scan in the app fails to display with erorr "Invalid hex color: rgb(242, 242, 242)" no QR code is generated to complete login.

### What version of Home Assistant Core has the issue?

2024.2.8b

### What was the last working version of Home Assistant Core?

2024.1.6

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Tuya

### Link to integration documentation on our website

https://rc.home-assistant.io/integrations/tuya

**Comment by tybo611** [comment]
> Changing to default doesn't seem to work for me... is there anything else you needed to do? clear cache? reload browser etc.

No, in my case I was setting a theme via automation, used the set theme service to quickly set it to default, configured tuya, then reset theme via the automation.

**Comment by ntalekt** [comment]
More about using the `set_theme` service in HA: https://www.home-assistant.io/integrations/frontend/#service-set_theme
