### ISSUE TITLE
Custom integration overrides brand

### ISSUE THREAD

**Issue by joostlek** [home-assistant/frontend#19720]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In 2024.2 `govee_local_lights` got introduced, which added the `govee` brand since we already had `govee_ble`.

Except, `govee` is also the domain of a custom integration which is popular by a lot of users of the lights.

When you have the `govee` custom integration installed, the `govee` brand is completely hidden and can't be found.

<img width="517" alt="image" src="https://github.com/home-assistant/frontend/assets/7083755/ab6dd04f-36a3-47ed-815a-31ca7037a7cb">

### Describe the behavior you expected

I expect that both the brand and the custom integration is able to be selected from the list.

<img width="557" alt="image" src="https://github.com/home-assistant/frontend/assets/7083755/505f34a3-a4f6-45ef-ba27-3dab77724069">
<img width="594" alt="image" src="https://github.com/home-assistant/frontend/assets/7083755/95a7cd58-655c-4308-bb01-76180ee3710c">

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.2

**Comment by codyc1515** [comment]
You may need to clear browser cache.

**Comment by joostlek** [comment]
No, I even installed the integration especially to make screenshots for the issue.

I would expect it to override a core integration, but there is no `govee` core integration, only a brand. So it doesn't make sense for the custom integration to override a brand (and only in the menu)

**Comment by karwosts** [comment]
Commented in #109921 why I don't believe this is actually a frontend issue.

**Comment by ghostdevv** [comment]
I'm still running into this :pray:

**Comment by karwosts** [comment]
Someone needs to open a home-assistant/core issue for this, we can't fix this from the frontend. The one that was open was closed by the OP without a real resolution.
