### ISSUE TITLE
Unable to pick range using Schedule helper 

### ISSUE THREAD

**Issue by craigwitter** [home-assistant/frontend#19733]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After upgrading to 2024.2, I am unable to drag the time range down in the schedule helper. 

### Describe the behavior you expected

In the past, you can click on the day of the week, then move the mouse to the lower section of the box and drag it down to select a time range. Now this no longer works. 

### Steps to reproduce the issue

1. Create a new schedule helper
2. Click in the box to create a single time
3. Try to drag (expanding) the time down to cover a range of times.

### What version of Home Assistant Core has the issue?

2024.2

### What was the last working version of Home Assistant Core?

2024.1

### In which browser are you experiencing the issue with?

Chrome 121.0.0.0

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
Logger: frontend.js.latest.202402070
Source: components/system_log/__init__.py:306
First occurred: 8:12:06 AM (7 occurrences)
Last logged: 8:13:18 AM

Uncaught error from Chrome 121.0.0.0 on Windows 10 TypeError: Cannot read properties of undefined (reading 'publicId') publicId (node_modules/@fullcalendar/core/internal-common.js:4144:32) _handleEventResize (src/panels/config/helpers/forms/ha-schedule-form.ts:294:12) eventResize (src/panels/config/helpers/forms/ha-schedule-form.ts:205:40) apply (node_modules/@fullcalendar/core/internal-common.js:3678:20) trigger (node_modules/@fullcalendar/interaction/index.js:1663:32) apply (node_modules/@fullcalendar/core/internal-common.js:3678:20) trigger (node_modules/@fullcalendar/interaction/index.js:939:25) apply (node_modules/@fullcalendar/core/internal-common.js:3678:20) trigger (node_modules/@fullcalendar/interaction/index.js:816:21) callback (node_modules/@fullcalendar/interaction/index.js:327:12)
```

**Comment by karwosts** [comment]
It is mostly still working for me, though I'm seeing I need to click one time on the calendar after creating a time before it seems to be interactive.

First I create a time, and after hovering over it my cursor is still the default mouse pointer. If I click once on the box, then the cursor changes to the pointer hand, and if I move to the edge, it changes to the resize cursor, and I can resize. 

But always the most recently created time block needs 1 extra click to become focused.
