### ISSUE TITLE
No icons on Hue 'effect' selector, empty placeholder

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#19741]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

as title:
more-info Hue light:

<img width="279" alt="Scherm­afbeelding 2024-02-08 om 17 13 19" src="https://github.com/home-assistant/frontend/assets/33354141/d3255824-1244-4e01-bef5-da45ef7a84f6">

now click Effect button:

<img width="262" alt="Scherm­afbeelding 2024-02-08 om 17 13 27" src="https://github.com/home-assistant/frontend/assets/33354141/fba49d2c-2a01-4cb3-bacb-f5bfa25ca937">

### Describe the behavior you expected

show icons for each effect

### Steps to reproduce the issue

1. as above
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.2

### In which browser are you experiencing the issue with?

any

### Additional information

guess the only less obvious effect would be the Prism, which does not have a direct translation in MDI, though the 'creation' would seem fit for it (even though it is used for the Effects button itself.

the outer form for mdi: pyramid would do if must be..

**Comment by karwosts** [comment]
I kind of think the new icons flow wants these to be defined by the hue integration. Some maybe should be a core issue for hue integration?

**Comment by Mariusthvdb** [comment]
a yes, I guess that would make sense... 
can you move this? or do I need to recreate an issue there?

**Comment by karwosts** [comment]
Personally I can't move. Maybe someone can. IMO your best bet is just to recreate, the form fields requested to fill out are different.

**Comment by karwosts** [comment]
I guess if hue will not provide icons, you can reopen here if you want. Maybe we put the dot back there, or just center the text? Not sure if design guys have any plan for what to do with the empty space in that case. 

Do you recall what this looked like in previous version?

**Comment by Mariusthvdb** [comment]
Sure, thanks.

tbh I am lost because of lack of communication on this. How come Backend implements Frontend stuff without thinking about the user facing outcome..

Before: tbh I am not 100% sure. Didn’t we just have the selector without the placeholders? Wasn’t the box  just less oversized?

centering those would already be better, yet probably still ‘lost in space’ because of the missing icon.

best would be to have some default icon?

awaiting integration support providing useful icons.

**Comment by karwosts** [comment]
Found this image from a light in 2023.12

![image](https://github.com/home-assistant/frontend/assets/32912880/ea93bfe2-de3a-433b-a1c7-80d526ecc9f4)

**Comment by Mariusthvdb** [comment]
Probably not Hue. But the principle is the same of course
