### ISSUE TITLE
Icon is not visible on white background, when light is set to all white

### ISSUE THREAD

**Issue by matthiasdebaat** [home-assistant/frontend#19746]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

`Toverlamp` icon is not visible.
![CleanShot 2024-02-08 at 19 28 41@2x](https://github.com/home-assistant/frontend/assets/20203284/d469f33b-fc60-4996-a684-48dfaab94816)

On focus you can see it again.
![CleanShot 2024-02-08 at 19 31 04@2x](https://github.com/home-assistant/frontend/assets/20203284/075a7527-2508-4a44-b355-b4f682037dc6)

### Describe the behavior you expected

We could fix it the same as we do on the more info dialog, by making it a shade of grey.
![CleanShot 2024-02-08 at 19 33 22@2x](https://github.com/home-assistant/frontend/assets/20203284/bcfd6944-384e-4825-bdd8-9d1217b6d27b)

### Steps to reproduce the issue

1. Set color temperature of bulb to white

### What version of Home Assistant Core has the issue?

2024.2.0

### In which browser are you experiencing the issue with?

Safari 17.2.1 (19617.1.17.11.12)

### Which operating system are you using to run this browser?

macOS Sonoma 14.2.1 (23C71)

**Comment by karwosts** [comment]
Related: 
https://github.com/home-assistant/frontend/issues/14129
https://github.com/home-assistant/frontend/issues/19435

These colored bulbs seem to be sort of contentious, no matter what color we make it, it will conflict with somebody's theme color. If you make white bulbs grey, then it will just shift the problem and become invisible for anyone with a grey theme background.

Seems like there needs to be some kind of extra accent color or something if we're saying these icons can dynamically take any RGB value.

**Comment by Floris039** [comment]
Other idea might be to just give the light bulb a black / colored thin outline. That way a white bulb on a white screen will look colored on the outlines. And a white bulb on a black / colored theme is also visible.
