### ISSUE TITLE
Energy Dashboard Self-Sufficiency has negative percentage value

### ISSUE THREAD

**Issue by jonathanmmm** [home-assistant/frontend#19751]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

It seems when your battery consumes energy (battery is being charged) while there is no solar power production and you use energy from the grid in the house, that the `self-sufficiency` becomes negative. This didn't only happened ones.
If you have a battery that needs some battery and in the winter with not a lot of sun to keep the battery management system may charge the battery from the grid for it to not fall too low.

Think of the following values (values are gathered from the energy dashboard):
1.3 kWh of Solar Power generated
5.4 kWh of House consumption
6.15 kWh taken from grid (import)
0 kWh to the grid (export)
2.1 kWh into the battery (charging)
0 kWh from battery (discharging)
`self-sufficiency = -15%`

The relevant PR is this one: https://github.com/home-assistant/frontend/pull/15704

If I do the following: `1 - (6.1/ 5.3) * 100 = -15,09%` like you can find in file 
` value = (1 - totalFromGrid / totalHomeConsumption) * 100;`

The problem seems that the calculation doesn't work when you consume more power from the grid than the house consumes, because the battery consumes some energy.

### Describe the behavior you expected

I expect that the `self-sufficiency` never drops below 0%.

Maybe this is expected to drop below 0%, but it seems this shouldn't happen and is a bug.
Maybe this is correct, as now having the battery doesn't help (at least at this timeframe) to become more self-sufficient, but actually costs electricity and therefore is less good than without it (in the timeframe chosen).

### Steps to reproduce the issue

1. Have a not sunny day and maybe a bit sunny before
2. Have a battery be empty at the day (pretty early in the day) and need power to sustain the minimum charge level.

### What version of Home Assistant Core has the issue?

core-2024.2.0

**Comment by karwosts** [comment]
Looks like duplicate https://github.com/home-assistant/frontend/issues/18656

**Comment by jonathanmmm** [comment]
> Looks like duplicate #18656

True, will then close this.
