### ISSUE TITLE
Matter Ping keeps results cached

### ISSUE THREAD

**Issue by Veldkornet** [home-assistant/frontend#19752]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After you've done a ping, the result seems to be cached? Ie, I ping one device, get the result, then go to another device, say ping, and it still has the result from the previous ping. I need to refresh the browser to be able to ping the second device.
This is both on desktop browsers and the mobile app.

### Describe the behavior you expected

When going to the next device, the results should be cleared as if you were doing a ping for the first time.

### Steps to reproduce the issue

1. Go to the Matter integration
2. Open a device
3. From the menu, select ping device
4. Close the ping popup
5. Go back and select a new device
6. From the menu, select ping device
7. Results from the 1st device ping are immediately shown

### What version of Home Assistant Core has the issue?

2024.2.1

### In which browser are you experiencing the issue with?

Google Chrome 121.0.6167.161

### Which operating system are you using to run this browser?

Windows 10

**Comment by sblogoshs** [comment]
This problem also exists with the OS on the RaspberryPi with the app for IOS, pinged once and all other pings have the same IP and the result is immediately available.

**Comment by karwosts** [comment]
Nearly certain the answer is just to add `this._pingResult = undefined` here, but I don't have any matter so won't propose it without testing. Maybe someone who does have matter devices can try it and PR. 

https://github.com/home-assistant/frontend/blob/4ba4a28aa02f3ee67255383bc8fcb0600ba277df/src/panels/config/integrations/integration-panels/matter/dialog-matter-ping-node.ts#L137-L141

**Comment by Coder84619** [comment]
I'm seeing the same behavior.

**Comment by Veldkornet** [comment]
Fixed in 2024.3.0
