### ISSUE TITLE
State classes is not correct / Device classes is not correct

### ISSUE THREAD

**Issue by 1192410** [home-assistant/frontend#19759]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since the latest update to 2024.2.1 I’m getting the follwing error messages.  I posted that in the [forum ](https://community.home-assistant.io/t/state-classes-is-not-correct-device-classes-is-not-correct/687761) and Wally asked to file a bug about that.

![image](https://github.com/home-assistant/frontend/assets/73297737/06017f49-665f-4d8d-b7a6-7e28294bfc4e)
![image](https://github.com/home-assistant/frontend/assets/73297737/6c8bbdd4-e092-4cff-9f5e-91fe221d84bb)
![image](https://github.com/home-assistant/frontend/assets/73297737/6f232e14-0d07-4486-a655-35b35821211b)

### Describe the behavior you expected

I would have expected that the device names are shown in the brackets.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.2.1

### What was the last working version of Home Assistant Core?

2024.1.5

**Comment by silamon** [comment]
I have opened a PR to fix this. It may take a while before it will reach a stable release but when it does it will list exactly what group, the different state classes and/or device classes from the entities in that group, so it should be easy to understand what should be done.

**Comment by karwosts** [comment]
Closing as not a frontend issue. (Thanks for the fix though)
