### ISSUE TITLE
UI for Zigbee2MQTT is unreadable after 2024.2 update.

### ISSUE THREAD

**Issue by RonaldRentaCar** [home-assistant/frontend#19758]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Almost all text is purple on black background after update to 2024.2. Also after update to 2024.2.1.
![Zigbee2mqtt UI](https://github.com/home-assistant/frontend/assets/122536293/f5a4a305-0aea-412b-bce0-b6181662216d)

### Describe the behavior you expected

A more readable UI, please.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.2.1

### What was the last working version of Home Assistant Core?

2023

### Which operating system are you using to run this browser?

Windows 10 Pro 22H2. OS build 19045.3930

**Comment by silamon** [comment]
That's an UI provided by a custom resource. Follow the issue and workaround in https://github.com/Koenkk/zigbee2mqtt/issues/21320.
