### ISSUE TITLE
Battery state card not working

### ISSUE THREAD

**Issue by ork777** [home-assistant/frontend#19763]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Battery state card not working not dynamic icon

### Describe the behavior you expected

Change icon dynamic

### Steps to reproduce the issue

1.
2.
3.
...
no response

### What version of Home Assistant Core has the issue?

supervised

### What was the last working version of Home Assistant Core?

2024.1.6

### In which browser are you experiencing the issue with?

firefox

### Which operating system are you using to run this browser?

debian

**Comment by ork777** [comment]
`
![immagine](https://github.com/home-assistant/frontend/assets/97830863/7c532d7d-0785-4039-b2ce-acc492a12cac)
`

**Comment by ildar170975** [comment]
And no code provided...
What is "Battery state card"?

**Comment by ork777** [comment]
![Screenshot 2024-02-10 at 17-42-44 Panoramica – Home Assistant](https://github.com/home-assistant/frontend/assets/97830863/26a3b9d2-c799-4215-9979-6623b29f2063)

**Comment by ildar170975** [comment]
And the code?

**Comment by ork777** [comment]
`type: custom:battery-state-card
title: Level Battery
color_thresholds:
  - value: 35
    color: red
  - value: 45
    color: blue
  - value: 60
    color: orange
  - value: 100
    color: green
entities:
  - entity: sensor.desktop_6gnjinv_battery_charge_remaining_percentage`

**Comment by ildar170975** [comment]
> type: custom:battery-state-card

Custom cards are not discussed here.
Suggest to create an issue in the card's github repo.

**Comment by ork777** [comment]
ok thanks
