### ISSUE TITLE
Power tab isn't properly reporting usage.

### ISSUE THREAD

**Issue by DuckersMcQuack** [home-assistant/frontend#19764]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Don't know if it's just me who set it up all wrong, or a bug, but this is the current readings it gets from the han adapter.
![image](https://github.com/home-assistant/frontend/assets/9039370/4d7acbfe-e4d1-4e08-a04f-203128a6719e)

but when in dashboard, it's all out of whack vs price, suddenly showing 3 dollars per hour of power cost, and 33 kilowatt instead of closer to 1.7 kilowatt and instead of 10 cents it should be, it's at 10 nok, almost as if the sensor it reads from, it takes hourly as per day worth of power and displays that as per hour of usage. As average per day in my power company app is 31 kW. And the sensor it reads from is showing per second of wattage usage of 1.7kW. Is there a setting somewhere i've missed to change from read as one day reading to seconds?

![chrome_Tu6ps2vjmE](https://github.com/home-assistant/frontend/assets/9039370/e7450236-90c4-4cfa-8009-7d671de0c89c)

### Describe the behavior you expected

Expected energy tab to read live data sensor as "live per second" and calculate by itself total energy usage per hour for hourly graphs. 

### Steps to reproduce the issue

1. Install tibber HAN
2. Install tibber integration
3. Add accumulated consumption current hour to power sensor reading
4. Add price to it below
5. Enter energy tab and see the off numbers.

6. Also tried to enter safe mode, but no safe mode located in settings/system.

### What version of Home Assistant Core has the issue?

Frontend 20230302.0 - latest

### In which browser are you experiencing the issue with?

Version 121.0.6167.161 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 home 

### State of relevant entities

```txt
Tibber Pulse
by Tibber
```

**Comment by karwosts** [comment]
I'm not able to understand what you're exactly trying to say, but just wanted to comment that energy panel only reads hourly statistics. It does not do anything with "live readings", or the current state of entities. 

If the shown values that don't make sense to you, the thing to check would be to make statistics-graph-card plots of the relevant statistics datasets, and see what values are in those datasets. If the statistics do not have the values you expect, then you would have to investigate that to root cause further.
