### ISSUE TITLE
Energy cards can't be added to a dashboard through the UI

### ISSUE THREAD

**Issue by langestefan** [home-assistant/frontend#19779]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

None of the energy dashboard cards are available when pressing 'add card' in the dashboard editor. The only way to add them is via YAML. 

<img width="750" alt="image" src="https://github.com/home-assistant/frontend/assets/37669773/4d001d81-8b63-41af-9097-9e64621d8d5f">

### Describe the behavior you expected

I expect the cards to show up in the list 'by card'.

<img width="750" alt="image" src="https://github.com/home-assistant/frontend/assets/37669773/3734b24e-aca4-4dc3-b14c-f009ef9d888d">

### Steps to reproduce the issue

1. Go to any view
2. Top right 3 dots -> edit dashboard
3. Bottom right -> add card
4. Try adding any energy card

### What version of Home Assistant Core has the issue?

2024.2.1

### In which browser are you experiencing the issue with?

Google Chrome 121.0.6167.161 (Official build) (64-bits)

### Which operating system are you using to run this browser?

Windows 11

**Comment by langestefan** [comment]
Not stale

**Comment by ChopperRob** [comment]
same issue on 2024.8.2
