### ISSUE TITLE
Entity row secondary_info showing literal 'last-updated' instead of date of last update

### ISSUE THREAD

**Issue by mfschumann** [home-assistant/frontend#19774]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When setting the secondary_info of an entity in an entities card to "last updated" it shows the literal string 'last-updated' as secondary info. 

### Describe the behavior you expected

Secondary info shows the date of the last update.

### Steps to reproduce the issue

1. Add entities card.
2. Add entity to the entities card.
3. Set secondary info to "last updated" via the UI or in YAML.

### What version of Home Assistant Core has the issue?

2024.2.1

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - entity: light.licht_esstisch
    secondary_info: last-updated
```

### Additional information

The default "last changed" works as expected though.

I observe the issue with Chromium, Firefox and the Android companion app.

**Comment by ildar170975** [comment]
Cannot confirm (2024.2.1).
Win10x64, Chrome, FF.

![image](https://github.com/home-assistant/frontend/assets/71872483/d512ef78-cb6e-4953-9c97-bf3a2f2dafba)
