### ISSUE TITLE
Markdown cards not working in popup cards

### ISSUE THREAD

**Issue by LDprg** [home-assistant/frontend#19773]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Well Markdown cards are just empty when beeing used in a popup card. No static text or templates.

### Describe the behavior you expected

Markdown card working like everywhere else.

### Steps to reproduce the issue

1. Create Popup card
2. Add Markdown card to popup card
3. Open Popup

### What version of Home Assistant Core has the issue?

2024.2.1

### In which browser are you experiencing the issue with?

Firefox 122.1.0, Homeassitant App 2024.1.5-full, Chrome 121.0.6167.164

### Which operating system are you using to run this browser?

Android 13/14, Windows 11/10, Linux (Nixos 23.11)

**Comment by ildar170975** [comment]
> Create Popup card

Is it done by some custom card? If yes - it should not be reported here; create an issue in a corr. custom repo.

**Comment by LDprg** [comment]
whops, yeah its related to browser mod
