### ISSUE TITLE
Growatt INTEGRATION; MISSIG SERVER

### ISSUE THREAD

**Issue by r3n3R3N3** [home-assistant/frontend#19782]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The 3 avalebel servers do not work for europe.

"https://openapi.growatt.com/  "
or "https://server.growatt.com" 
 could be added 

### Describe the behavior you expected

more than 3 options , more options. 

### Steps to reproduce the issue

1.add new Integration Growatt
2.  servers do not work for europe
3.
...

### What version of Home Assistant Core has the issue?

2

**Comment by karwosts** [comment]
Please file this in https://github.com/home-assistant/core, this is not an issue with the frontend.
