### ISSUE TITLE
History Data not lining up with time

### ISSUE THREAD

**Issue by Blackshome** [home-assistant/frontend#19783]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The history data in not inline and hard to read because of this. Recommend the name be relocated or maybe something else can be done so the time line all lines up.

Best way is to show you, see below history data. Because the name is on the left it pushes the time line out.

![Data](https://github.com/home-assistant/frontend/assets/98072753/468c5376-8698-4234-ba0b-0101880d13e4)

Hope this helps you

Blacky :) 

### Describe the behavior you expected

All time lines to line up

### Steps to reproduce the issue

1. enter in a state
2. enter in history graph
3.
4.
...

### What version of Home Assistant Core has the issue?

2024.2.1

### What was the last working version of Home Assistant Core?

unsure

### In which browser are you experiencing the issue with?

Firefox 

### Which operating system are you using to run this browser?

windows

**Comment by Blackshome** [comment]
I would like it to line up in the history view as I would like to filter data with time.

Also in the history card can't see show names. This too should line up with names anyway, so I like to add that to the fix.

![data 2](https://github.com/home-assistant/frontend/assets/98072753/1d7c4e2d-d592-4d83-837e-39041234c49d)

**Comment by karwosts** [comment]
It did used to line up (in both history panel and history cards). I think something must have broken this in a recent update.

**Comment by ildar170975** [comment]
Hmm, seems to be an issue here.
On the below graph `show_names: false`:

![image](https://github.com/home-assistant/frontend/assets/71872483/898223b7-f149-4c80-9994-b1362462fcc5)

**Comment by Blackshome** [comment]
yep all the same. I know code but why do users have to know code, read through the documentation, have to know that this is an option..... So I would like to add a show name selection to.

![data 3](https://github.com/home-assistant/frontend/assets/98072753/be9a209c-4ee7-4e76-a949-b98a3f771fc8)
