### ISSUE TITLE
Markdown Card doesn´t support global settings for country-specific number format

### ISSUE THREAD

**Issue by Spartacus68** [home-assistant/frontend#19795]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

global settings:
![Screenshot 2024-02-13 233545](https://github.com/home-assistant/frontend/assets/121975453/d166e3cc-6301-463d-b299-17d24f679219)

in markdown card, the comma is shown als a point.
![Screenshot 2024-02-14 082443](https://github.com/home-assistant/frontend/assets/121975453/829d4257-0d34-444b-ae39-d15d155b3459)

### Describe the behavior you expected

Expectation is, that the number format will have a comma instead of a point 
like:
86,78% instead of 86.78%

### Steps to reproduce the issue

1.
2.
3.
...
```
|||||
|:---|---:|---:|---:|
<font size="4">🔆Klimadaten:</font>
||<font color="#f1c232"><ha-icon icon="mdi:home-thermometer-outline"></ha-icon></font>**Temperatur:**|{{'&emsp;'}}<font color="#2986cc"><ha-icon icon="mdi:water-percent"></ha-icon></font>**rel. Feuchte:**|{{'&emsp;'}}<font color="#66c2ff"><ha-icon icon="mdi:water-thermometer-outline"></ha-icon></font>**Taupunkt:**
<font color="#CD853F"><ha-icon icon="mdi:shovel"></ha-icon></font> Garten:|{{ '%.2f' | format(states("sensor.1w_ds2450t")|float)}} °C|{{'&emsp;'}}{{ '%.2f' | format(states("sensor.1w_ds2450h")|float)}} %|{{'&emsp;'}}{{ '%.2f' | format(states("sensor.1w_ds2450dew")|float)}} °C
<font color="#8B0000"><ha-icon icon="mdi:greenhouse"></ha-icon></font> Gartenhaus:|{{ '%.2f' | format(states("sensor.1w_ds2438t")|float)}} °C|{{'&emsp;'}}{{ '%.2f' | format(states("sensor.1w_ds2438h")|float)}} %|{{'&emsp;'}}{{ '%.2f' | format(states("sensor.1w_ds2438dew")|float)}} °C
<font color="#87CEEB"><ha-icon icon="mdi:fridge-outline"></ha-icon></font> Vorratskeller:|{{ '%.2f' | format(states("sensor.temperatur_vorrat")|float)}} °C|{{'&emsp;'}}{{ '%.2f' | format(states("sensor.luftfeuchte_vorrat")|float)}} %|{{'&emsp;'}}{{ '%.2f' | format(states("sensor.taupunkt_vorratsraum")|float)}} °C
<font color="#DEB887"><ha-icon icon="mdi:sofa-single-outline"></ha-icon></font> Hobbykeller:|{{ '%.2f' | format(states("sensor.temperatur_hobby")|float)}} °C|{{'&emsp;'}}{{ '%.2f' | format(states("sensor.luftfeuchte_hobby")|float)}} %|{{'&emsp;'}}{{ '%.2f' | format(states("sensor.taupunkt_hobbytaum")|float)}} °C
```

### What version of Home Assistant Core has the issue?

2024.2.1

### What was the last working version of Home Assistant Core?

worked never

### In which browser are you experiencing the issue with?

Edge Version 121.0.2277.112

### Which operating system are you using to run this browser?

Win 11 Pro

**Comment by karwosts** [comment]
I don't think there's anything we can do for you in the frontend. 

Markdown just sends your templates to the backend, and it returns the result string to frontend. I don't know if its at all possible for the template rendering engine to use these settings, but I guess you'd have to ask in home-assistant/core.

**Comment by ildar170975** [comment]
In my observations jinja templates always return same number format "xx.xx" independently on user settings in frontend, I call this behaviour "normal".
