### ISSUE TITLE
no front-end UI for explicit triggers in binary sensor template editor

### ISSUE THREAD

**Issue by wjcarpenter** [home-assistant/frontend#19801]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When creating a triggered binary sensor helper, HA does a reasonable job of parsing the trigger entities out of the template. But if you want to explicitly add trigger entities, the UI doesn't have a way to do that. And, since editor doesn't have an "edit in YAML" option, there is no way to enter those explicit triggers. You have to find the triggered binary sensor in the HA YAML files and add the triggers manually.

### Describe the behavior you expected

I expected there would either be a UI way to add triggers or there would be a way to edit the YAML fragment in the UI.

### Steps to reproduce the issue

1. Settings > Devices & services > Helpers
2. Create helper, select "Template", select "Template a binary sensor"

### What version of Home Assistant Core has the issue?

Core 2024.2.1 Supervisor 2024.01.1 Operating System 11.5 Frontend 20240207.1

### In which browser are you experiencing the issue with?

Chrome and Firefox

### Which operating system are you using to run this browser?

Linux (Ubuntu)

**Comment by karwosts** [comment]
I believe this was fairly intentional when templates were brought to the helpers UI. It was known that it only covered a very simple subset of possible template configurations, and users would still need to go to configuration.yaml for more complex setups.

**Comment by wjcarpenter** [comment]
While that may be true, the UI for creating/editing template sensors and template binary sensors is otherwise fairly complete. I think being able to list explicit triggers is the only missing piece.

**Comment by karwosts** [comment]
I'm going to close this, as in addition to being a feature request, this is not something that can be achieved in the frontend.

The core template helper integration defines what fields are shown here. That integration would need to be updated to add additional fields and options to the template helper. A feature request on the forum would be the right place for this request.
