### ISSUE TITLE
Zigbee Initialisation Failure

### ISSUE THREAD

**Issue by StagefireUK** [home-assistant/frontend#19808]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On Update 2024.2.1 the zigbee integration failed to initialise and after a full restart and a reinstall of the integration it still failed to initialise. Only when restoring to version 2024.1.6 it works again. 

### Describe the behavior you expected

Initialisation successful.

### Steps to reproduce the issue

1. Update to 2024.2.1
2. Restart HA
3. Zigbee integration initialisation failed
...

### What version of Home Assistant Core has the issue?

2024.2.1

### What was the last working version of Home Assistant Core?

2024.1.6

### In which browser are you experiencing the issue with?

Arc - Version 1.29.0 (46113)

### Which operating system are you using to run this browser?

macOS Sonoma 14.4

**Comment by karwosts** [comment]
You're in the wrong repository, this is for the frontend issues only. You were probably looking for home-assistant/core instead.
