### ISSUE TITLE
History showing terrible BAR instead of beautiful graph

### ISSUE THREAD

**Issue by marc4s** [home-assistant/frontend#19805]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since 2024.x the history graph changed for some sensors.
I have some sensors which are configured as a helper (group and sum) and both was shown correct as graph till 2023.12

now they were shown as bar

in general I have some more sensors where I would like to change the graph type. would be good if it is configurable via dev-tools

### Describe the behavior you expected

![Bildschirmfoto vom 2024-02-15 09-09-28](https://github.com/home-assistant/frontend/assets/93420756/21865fc1-2099-4dd8-8ae2-1e402a5f390c)
![Bildschirmfoto vom 2024-02-15 09-08-43](https://github.com/home-assistant/frontend/assets/93420756/0faa90bf-e4ff-4755-9a52-a18e5cf4fefb)
![Bildschirmfoto vom 2024-02-15 09-07-57](https://github.com/home-assistant/frontend/assets/93420756/ca8c33a5-8ed8-467d-9039-278d6cd95551)

should be like this : 
![Bildschirmfoto vom 2024-02-15 09-11-23](https://github.com/home-assistant/frontend/assets/93420756/47df5b27-b236-4b98-bb29-7b829d4b998d)

### Steps to reproduce the issue

1. create a sensor group / sum via helper
2. add sensors

### What version of Home Assistant Core has the issue?

core-2024.2.1

### What was the last working version of Home Assistant Core?

core-2023.12.4

### In which browser are you experiencing the issue with?

Firefox

### Which operating system are you using to run this browser?

Linux

**Comment by karwosts** [comment]
You simply need to add a `unit_of_measurement` to your sensor's attributes, and they will get the line graph.

If this used to work, than maybe a core issue caused those entities to drop their unit. You could file a core issue for that if desired.

**Comment by marc4s** [comment]
simply add ?

I know about this, but I cannot figure out where to put this?
GUI? no option
yaml? it is ignored

![Bildschirmfoto vom 2024-02-15 16-32-12](https://github.com/home-assistant/frontend/assets/93420756/1d9ddabe-e37e-43c0-8a20-b2a11a01d8d6)

![Bildschirmfoto vom 2024-02-15 16-35-40](https://github.com/home-assistant/frontend/assets/93420756/a620f6d6-5d31-4263-9fd5-dd9149363c0f)
![Bildschirmfoto vom 2024-02-15 16-35-05](https://github.com/home-assistant/frontend/assets/93420756/e4ce4b59-f25c-413a-8633-bbb0ff1bfbf5)

still no unit_of_measurement in dev_tools visible.
still the bar graph

**Comment by karwosts** [comment]
I'm just explaining that the behavior has always been to show a timeline ('bar') graph for entities without a unit_of_measurement or a numeric device class.

If you need support for how to configure your entities, suggest checking out one of the end user support options in the help page (forums, discord, etc):

https://www.home-assistant.io/help

**Comment by marc4s** [comment]
here is the root cause
