### ISSUE TITLE
Move up and move down functionality in automation doesn't work

### ISSUE THREAD

**Issue by pbulteel** [home-assistant/frontend#19800]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have an automation with several triggers and several actions. I can easily move them with the new drag and drop functionality but the "move up" and "move down" functionality doesn't work. The canvas seems to "move" as if something did happen, but nothing has changed. I saved the output of the whole automation into a file before and after doing move up and the diff says they're identical, meaning nothing actually moved. However, the save button is activated as if something did change.

I tried creating a new automation to reproduce, but I cannot. However, the automation that I have does show the issue. I have save as a file and attached.
[automation-move-up.zip](https://github.com/home-assistant/frontend/files/14284049/automation-move-up.zip)

### Describe the behavior you expected

I would expect the item that is selected to move up actually moves up and the item above it, moves below it. 

### Steps to reproduce the issue

1. Unzip the automation-move-up.zip
2. Insert the automation-1.yaml into an empty automation.
3. Expand "Choose between 5 actions"
4. Expand "Trigger when leave_home"
5. Expand "If phone battery"
6. On the "Open WiGLE app" click the hamburger menu and select Move Up option
7. Save button will appear, but nothing has changed.
...

### What version of Home Assistant Core has the issue?

2024.2.1

### In which browser are you experiencing the issue with?

Google Chrome 121.0.6167.160  and Firefox 122.0.1

### Which operating system are you using to run this browser?

Pop!_OS 22.04 LTS

### Additional information

I noticed this happening on the mobile app and thought it was an issue with the app. Confirmed it on desktop with Web browser.

**Comment by pbulteel** [comment]
I have realised that what happens is the whole thing moves. So... let me explain.

I have a delay, followed by a choose. There are 5 choices, those have conditions and actions. When I try to move one of the actions (bottom of 4) instead of moving that action, it moves the entire choose block. 

- delay
- choose
- - option 1
- - - condition
- - - action 1
- - - action 2
- - - action 3
- - option 2
- - - condition
- - - action 1
- - - action 2
- - - action 3

In the above example, if I try to move action 3 it actually moves the whole choose block. 

-P

**Comment by karwosts** [comment]
Yeah looks like probably missing a stopPropagation. 

I see if I move up Action 3, it moves action 3 above action 2, *and* moves the choose block above the delay at the same time.
