### ISSUE TITLE
Empty shopping list incorrect message

### ISSUE THREAD

**Issue by JoaoPedro13** [home-assistant/frontend#19802]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

the shopping list card when does not have any items, has the message: "You have no To-do items"

### Describe the behavior you expected

the message should have in consideration if is a to-do list or a shopping list, and replace "to-do items" with "shopping items", or the message should be configurable

### Steps to reproduce the issue

1.go to lovelace dashboard
2.add a shopping list card with a shopping list (that is empty)
3. check the message shown on the card when the list is empty

### What version of Home Assistant Core has the issue?

core-2024.2.1

**Comment by Swarga-codes** [comment]
Is anyone working or this?

**Comment by karwosts** [comment]
> Is anyone working or this?

I think it's safe to assume not at the moment, given that it shoud be relatively quick to do, and there's no pull for it. Are you asking because you'd like to do it?

**Comment by Swarga-codes** [comment]
I was exploring this repo and was willing to contribute to it so can I try working on this?

**Comment by karwosts** [comment]
Anyone is free to make pull requests for any issue, so sure give it a try if you like.
