### ISSUE TITLE
ICONS missing after upgrading to 2024.2

### ISSUE THREAD

**Issue by MuppetRus** [home-assistant/frontend#19819]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The issue is 90% of the ICONS disappear from all the entity cards on Dwain's Dashboard after upgrading from 2024 .1.6 to 2024.2.2 

### Describe the behavior you expected

All icons to still appear as they were before the update

### Steps to reproduce the issue

1. Upgrade from 2024.1.6 
2.90% of the icons disappear 
3. Restore 2024.1.6 backup and all icons return 
...

### What version of Home Assistant Core has the issue?

Core 2024.2

### What was the last working version of Home Assistant Core?

Core 2024.1.6 

### In which browser are you experiencing the issue with?

Microsoft Edge Version 121.0.2277.112 (Official build) (x86_64)

### Which operating system are you using to run this browser?

macOS Big Sur 11.7.10

**Comment by karwosts** [comment]
Custom plugins are not supported here. Please raise this issue with the developer of the plugin.

**Comment by MuppetRus** [comment]
Thank you

**Comment by letsautomatenet** [comment]
Is this definitely related to the custom plugin?

All icons that I have defined in the "customize" section of the config file have stopped working since upgrade.

Perhaps the plugin also leverages this?
