### ISSUE TITLE
 unifiprotect stacked NVR cameras not displaying properly

### ISSUE THREAD

**Issue by mplopez99** [home-assistant/frontend#19824]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

recently my cameras that are on the "stacked unit" intermittently update and acre completely unaccessible for live stream in HA dashboard (Overview) and in HomeKit. All cameras on the 1st NVR show up fine. Snap shots look ok in HomeKit, but streaming not available only for cameras attached to stacked NVR

### Describe the behavior you expected

I was expecting to see all cameras including all in stacked unit. 

### Steps to reproduce the issue

1.logged into HA
2.Looked at "Overview" Stacked NVR cameras shows up as unavailable 
3.1st unit cameras show up as recording
4. Try to stream any of the stacked cameras - will not work
5. Try streaming 1st UNVR cameras and they work fine
6. Refresh the integration.
7. All snapshots look ok
8. try to stream a stacked UNVR camera
9. Shows as unavailable again
...

### What version of Home Assistant Core has the issue?

2024.2.2

### In which browser are you experiencing the issue with?

Safari Version 17.2.1 (19617.1.17.11.12)

### Which operating system are you using to run this browser?

macOS Sonoma 14.2.1 (23C71)

### State of relevant entities

```txt
Unable to stream or update any of the cameras assigned to "stacked" UNVR.
```

**Comment by gjohansson-ST** [comment]
Closing this as this feature is not implemented and as such feature requests are asked to go to our forums so please post their in the future request forum https://community.home-assistant.io/c/feature-requests/13

Thanks

**Comment by robsonfelix** [comment]
same here.
