### ISSUE TITLE
Temperature in Celsius of an area (external sensor) is displayed with an offset

### ISSUE THREAD

**Issue by CrazyLukas98** [home-assistant/frontend#19837]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The Temperature is displayed correctly in the "area" card:
![Screenshot 2024-02-19 203733](https://github.com/home-assistant/frontend/assets/156589039/5c41dd62-cd83-43e3-9521-4e8a24164376)

If the temperature is configured in celcius unit, the temperature is displayed with an offset: 
![Screenshot 2024-02-19 203223](https://github.com/home-assistant/frontend/assets/156589039/18c0b08a-f032-4574-ba50-56adb5e42037)

I would expect that this is equal.

### Describe the behavior you expected

I would expect that temperature value in celcius of my external temp sensor is equal to the displayed in the area card.

### Steps to reproduce the issue

1.use external temperature sensor
2.create "area" card
3. change unit to celsius

### What version of Home Assistant Core has the issue?

2024.2.1

### In which browser are you experiencing the issue with?

Firefox 122.0.1

### Which operating system are you using to run this browser?

Win 11

**Comment by karwosts** [comment]
I'll guess you probably have another C temperature sensor in that area that you're not thinking of. 

Area card will average the sensors together, but it picks a unit from the first sensor it finds in that area and then ignores any other that don't match that unit.

So if you have a F temperature sensor, and a C temperature sensor, it might show only the F sensor, or if you change the F sensor to a C sensor, then it will show the average of the two if they are the same unit.

**Comment by CrazyLukas98** [comment]
Yes youre right. I used thermal comfort integration in addition for each sensor. So after deactivating the temperature values of this integration, the temperature is displayed correctly.
Thanks for your support!

**Comment by CrazyLukas98** [comment]
No issue here.
