### ISSUE TITLE
ZHA unable to create new network when manual backup is selected by accident

### ISSUE THREAD

**Issue by bruvv** [home-assistant/frontend#19856]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

when setting up a new ZHA network:
<img width="302" alt="image" src="https://github.com/home-assistant/frontend/assets/3063928/2c073a81-111a-4c77-af18-70568e24e5f7">
<img width="380" alt="image" src="https://github.com/home-assistant/frontend/assets/3063928/b8fa31a8-7aed-45cc-be32-9935d2c3dfd5">
Select: "Upload a manual backup", then you will not be able to get out of this menu anymore:
<img width="575" alt="image" src="https://github.com/home-assistant/frontend/assets/3063928/35f99a5e-477f-460a-9a21-c912393ddcc2">

### Describe the behavior you expected

I want a back button so I can create a new network instead of forcing me to restore the backup that i accidentally clicked.

### Steps to reproduce the issue

See photos

### What version of Home Assistant Core has the issue?

Core: 2024.2.2
Supervisor 2024.02.0
Operating System 11.5
Frontend 20240207.1

### In which browser are you experiencing the issue with?

Firefox version 123

### Which operating system are you using to run this browser?

14.3.1 (23D60)

**Comment by karwosts** [comment]
If you just click the X to close the dialog, and restart the configure, does that not work, or are you permanently stuck?

**Comment by bruvv** [comment]
It is permanently stuck. The only way I got it back was to ignore the newly discovered stick, restart home assistant, unignore (is that a word?) the stick, restart home assistant and restart the process.

**Comment by bruvv** [comment]
Cross posted: https://github.com/home-assistant/core/issues/111145. @karwosts do you want to leave this open?

**Comment by bruvv** [comment]
@karwosts reminder

**Comment by karwosts** [comment]
I think we can close, thanks.

**Comment by LordofMaps** [comment]
> It is permanently stuck. The only way I got it back was to ignore the newly discovered stick, restart home assistant, unignore (is that a word?) the stick, restart home assistant and restart the process.
I experienced the same thing as reported in this issue. These steps resolved the issue for me, thank you.

**Comment by andyjessop** [comment]
Any idea why the linked post in home assistant has been closed? It's an issue that still exists.
