### ISSUE TITLE
Number format is not used for numerical sensors w/o UoM

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#19866]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Consider these sensors of "aqi" & "ph" device classes:

![image](https://github.com/home-assistant/frontend/assets/71872483/992d00e7-e562-4ec0-a50e-4b3f6b38f416)

![image](https://github.com/home-assistant/frontend/assets/71872483/6d831457-2803-4d0b-a8ea-bfd95dbf1d40)

A user-defined number format is not followed for these sensors.
Compare with "power" device class: a sensor does have UoM, a proper number format is used.

![image](https://github.com/home-assistant/frontend/assets/71872483/1bb1ca49-2498-41bd-892c-630debf5b469)

![image](https://github.com/home-assistant/frontend/assets/71872483/6263eba0-3b3f-4ae9-94a6-cf90abf5b584)

![image](https://github.com/home-assistant/frontend/assets/71872483/0d1b92e2-a5db-4caf-ae7b-3011ce1550c9)

![image](https://github.com/home-assistant/frontend/assets/71872483/30d5b205-11f6-48b7-9227-24ce0bd549a3)

And same for a sensor w/o `device_class`:
```
template:
  - sensor:
      - name: testing_number_format
        state: 9999.99
```
Number format is always same:
![image](https://github.com/home-assistant/frontend/assets/71872483/f17e6825-4aeb-43c3-a387-a6955b4a61ed)

### Describe the behavior you expected

A user-defined number format is used.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2024.2.1

### In which browser are you experiencing the issue with?

Chrome 121.0.6167.185 

### Which operating system are you using to run this browser?

Win10x64

**Comment by karwosts** [comment]
I made a PR to fix for the `pH` and `AQI` cases. I disagree on the last point that a sensor with no state_class, uom, or device_class should be numerically formatted. When we don't have any information that the state is intended to be numeric, we just leave formatting exactly as provided by the backend. 

If you don't have a device_class or UoM, but want an entity to be numeric formatted, you can apply a state_class to achieve that as well.

**Comment by ildar170975** [comment]
I see your point. But if state_class is defined - the entity is supposed to be stored in LTS. What if a user does not want this? What if the user excluded the entity from Recorder?

**Comment by karwosts** [comment]
An entity excluded from recorder is also excluded from LTS, whether or not it has a state_class.

I see your point, but I believe we have always relied on entity attributes to tell us if an entity is numeric or not. I don't think we have any way to signal this for an entity that does not want a unit, does not want a device_class, and does not want a state class, those are the only attributes we have for this. 

I won't be addressing that, but I'll leave this open though in case else wants to figure out how to tackle that.

**Comment by ildar170975** [comment]
> An entity excluded from recorder is also excluded from LTS, whether or not it has a state_class.

In this case I see an "issue" in Dev tools -> Statistics with no possibility to purge this useless LTS data:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/574ed473-f0fb-4a1e-824b-d34a3d560504)
I hope we have already registered issue for this...

Also, as I said - "the entity is supposed to be stored in LTS. What if a user does not want this?"
A user just DOES NOT want storing LTS for this value.

> I don't think we have any way to signal this for an entity that does not want a unit, does not want a device_class, and does not want a state class, those are the only attributes we have for this.

Let's compare this to a known "my sensor - which is supposed to be numerical - has a timeline chart" issue.
```
template:
  - sensor:
      - name: numerical_value
        state: 1234.1234
```
![изображение](https://github.com/home-assistant/frontend/assets/71872483/991e9270-34b1-4052-81b1-a12062ebf8cc)

And number format is:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/fc3c26de-3181-4a60-9461-29ca72df72c0)

Currently we have to set an empty UoM:
```
template:
  - sensor:
      - name: numerical_value
        state: 1234.1234
        unit_of_measurement: ''
```
which gives a linear chart - but same "non-numerical" format:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/fed0b585-8009-4be7-ba8d-72720dfbb0d3)

So, if adding an empty UoM helps to get a nice graph - then is it possible to use same workaround (brute, not elegant, ...) to get a correct number format?

**Comment by karwosts** [comment]
> As for PR: will it process all device classes w/o UoM? I reported about aqi, ph. But I found this also: ![изображение](https://private-user-images.githubusercontent.com/71872483/307850201-4fc3987d-eb5e-4aaa-994d-aa318833d3c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjczMzMsIm5iZiI6MTcwODk2NzAzMywicGF0aCI6Ii83MTg3MjQ4My8zMDc4NTAyMDEtNGZjMzk4N2QtZWI1ZS00YWFhLTk5NGQtYWEzMTg4MzNkM2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDE3MDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NTg5M2NiM2NkMTYwN2Q5ZmEyY2M2MTM3MjQwMGE1MWE4ZWEzYjBiNDRmOWNkZmJmM2JjNTFiOGJhMjBjMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fJ1i-0Fwv8bMBsDpRTaxsbLpLufSMzqy9rp7G5TtGsE)
> 
> ```
>       - name: testing_device_class_power_factor
>         device_class: power_factor
>         # unit_of_measurement: "%"
>         state: ...
> ```
> 
> ![изображение](https://private-user-images.githubusercontent.com/71872483/307851233-2feab337-9db9-4b9d-aebb-db51b3c97fba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjczMzMsIm5iZiI6MTcwODk2NzAzMywicGF0aCI6Ii83MTg3MjQ4My8zMDc4NTEyMzMtMmZlYWIzMzctOWRiOS00YjlkLWFlYmItZGI1MWIzYzk3ZmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDE3MDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMmFlODE3MmQxMjE5NGFkZTBiY2RlMmJiZjdiZjc5MGRhMjg2ODY0MGY5NGZkMWJhYjVjM2YxYmQ5YzVhZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lklr0poNksDlRXbM7s4E0zw-nlDrMszZeEWvhh4Ackg)
> 
> ![307846371-fc3c26de-3181-4a60-9461-29ca72df72c0](https://private-user-images.githubusercontent.com/71872483/307851733-279b3fd8-1f8d-4245-91fe-361dd0075724.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjczMzMsIm5iZiI6MTcwODk2NzAzMywicGF0aCI6Ii83MTg3MjQ4My8zMDc4NTE3MzMtMjc5YjNmZDgtMWY4ZC00MjQ1LTkxZmUtMzYxZGQwMDc1NzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDE3MDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMzAyZThkNzIxZjZkNzVjMjgyYjhhNWQzYjcyYjNlOWQ2NDQ2NTg3YjUzN2ZiOTYwZWEzMmRiNjBiYjczNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d3KUxb6SLTvtZNYGmxdFnxNAdb82h_g0xhSaIOURqIM)
> 
> i.e. when set w/o UoM - same wrong number format.

The backend publishes a list of 48 device classes that it considers to be of numeric type for sensor, and any of those classes will be fixed by this PR. Yes `power_factor` is one of them.

**Comment by ildar170975** [comment]
waiting for https://github.com/home-assistant/frontend/pull/19878 to be released

**Comment by ildar170975** [comment]
Closing since sensors with uom-less device classes like "aqi", "ph" now are treated as numerical.
As for sensors w/o a `device_class` - let's discuss it in other place.
