### ISSUE TITLE
Dashboard view/refresh on IOS: Uncaught error from WebKit 605.1.15 on iOS 16.7.5 Script error.

### ISSUE THREAD

**Issue by mostdone** [home-assistant/frontend#19876]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

USING:
Model Name: IPhone8
Software Version: IOS 16.7.5
Home assistant App version: 2024.1

Each time I open or refresh a dashboard on IOS using the APP.
The following error appears in the Core logs:

2024-02-25 06:42:36.747 ERROR (MainThread) [frontend.js.latest.202402071] Uncaught error from WebKit 605.1.15 on iOS 16.7.5
Script error.
null
@:0:0

It does NOT happen using either Safari or Chrome on MACOS.
It happens when using Safari on IOS
It happes when using Home Assistant APP on IOS
My installation also has other dashboards. The error does NOT occur when the other dashboards are viewed or refreshed.
This issue was first entered in IOS repo. [Issue #2604](https://github.com/home-assistant/iOS/issues/2604)

### Describe the behavior you expected

The view should show/refresh without an uncaught error from WebKit.

### Steps to reproduce the issue

1. In Home Assistant create a Dashboard
2. ADD the dashboard to left pane
3. Edit the new dashboard and add a GRID card with 2 columns
4. In the grid ADD Two thermostat cards
5. Save and DONE
6. On IOS open the Home assistant app
7. Select the dashboard
8. Open the core logger and see the error log
Uncaught error from WebKit 605.1.15 on iOS 16.7.5 Script error.
The error occurs everytime the dashboard is viewed or refreshed
...

### What version of Home Assistant Core has the issue?

2024.2.3

### What was the last working version of Home Assistant Core?

Unknown

### In which browser are you experiencing the issue with?

IOS Safari and IOS Home Assistant APP

### Which operating system are you using to run this browser?

IOS 16.7.5

### Javascript errors shown in your browser console/inspector

```txt
2024-02-25 15:23:02.666 ERROR (MainThread) [frontend.js.latest.202402071] Uncaught error from WebKit 605.1.15 on iOS 16.7.5
Script error.
null
@:0:0
```

### Additional information

Further testing
1- Completely deleted the problematic dashboard

2- Recreated dashboard from scratch with only ONE GRID containing 2 THERMOSTAT card.
-The problem OCCURS when this dashboard is viewed in IOS. (Safari or APP)
I have grids in another dashboard (NOT containing "thermostat" entities) that do not cause the issue.

3- I deleted the grid and added just a thermostat card in the dashboard.
-The the problem DOES NOT OCCUR

Issue  [IOS repo issue #2439](https://github.com/home-assistant/iOS/issues/2439) occured with 20 x "Logbook cards" it's not clear whether they were in GRID or not.
and here with 2 x "Thermostat cards" in a GRID.

The following code is the "Raw configuration view". It was created using the UI.
The issue occurs with this dashboard config.

Code
views:

title: Home
   cards:
     square: false
        type: grid
          cards:
             type: thermostat
                entity: climate.th_solariumouest
               name: SolOuest
            type: thermostat
               entity: climate.th_solest
               name: SolEst
            columns: 2

**Comment by skrue** [comment]
Hi,
I am also seeing an error that might be related in my logs when I open my dashboard with my thermostat cards in the iOS app.
It seems that **for each card the error appears twice (12 thermostat cards = 24 errors)** whenever I load the dashboard in the app.

- HA Core 2024.5.4
- Frontend 20240501.1
- iOS 16.3.1
- HA iOS App 2024.4

```
2024-05-22 08:39:25.537 ERROR (MainThread) [frontend.js.latest.202405011] Uncaught error from WebKit 605.1.15 on iOS 16.3.1
TypeError: Right side of assignment cannot be destructured
ref (node_modules/element-internals-polyfill/dist/index.js:364:47)
this (node_modules/element-internals-polyfill/dist/index.js:776:41)
this (node_modules/element-internals-polyfill/dist/index.js:774:52)
this (src/scoped-custom-element-registry.js:248:47)
insertBefore ([native code]::)
t (src/lit-html.ts:1454:43)
i (src/lit-html.ts:1563:23)
t (src/lit-html.ts:1384:33)
t (src/lit-html.ts:2183:18)
i (src/lit-element.ts:165:30)
```
Not using a grid however...

**Comment by amordicus** [comment]
This happens to me too when using Companion on a Mac mini, running Ventura Mac OS 13.6.9 and selecting "Mac mini Storage" statistics. Home Assistant Core
2024.9.1
Supervisor
2024.08.0
Operating System
13.1
Frontend
20240906.0

2024-09-08 20:55:41.203 ERROR (MainThread) [frontend.js.modern.202409060] Uncaught error from WebKit 605.1.15 on Mac OS 10.15.7
Script error.
null
@:0:0

**Comment by Limezy** [comment]
I have the same bug too. It appeared after updating to 2024.9.1 on an iPhone running 16.3.1

**Comment by nzrutman** [comment]
Same with HA app on OSX
```
ERROR (MainThread) [frontend.js.modern.202410022] Uncaught error from WebKit 605.1.15 on Mac OS 10
.15.7
Script error.
null
@:0:0
```

**Comment by Emilef22** [comment]
same here on Iphone 18.1
