### ISSUE TITLE
QR code out of date when restoring from a backup

### ISSUE THREAD

**Issue by SRJohnston** [home-assistant/frontend#19872]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When you restore Home Assistant from a backup, you need to relink to your phone,  You are presented with a QR code, but when you scan the code it says it is out of date,

Thee does not seem any way of getting it to generate a new up to date QR code

### Describe the behavior you expected

When restoring from backup it would be good if it can generate a current QR code.  The only fix I can see is to delete the connection, then go through the setup again and get a current QR code.

This means having to configure any devices again and set them back up 

### Steps to reproduce the issue

1. Restore a Home Assistant backup (full) that is more than a few hours old
2. Get the need to reconnect Tuya integration
3. Use smart life app to scan the QR code and it will generate the error4.
...

### What version of Home Assistant Core has the issue?

2024.2.3

### What was the last working version of Home Assistant Core?

2024.2.3

### In which browser are you experiencing the issue with?

Latest Google Chrome

### Which operating system are you using to run this browser?

Android 14

**Comment by karwosts** [comment]
This feels like it should probably be a core issue tagged for the `Tuya` integration, frontend doesn't really have any integration specific logic for Tuya, so I'm not really sure if this issue is something that can be addressed here.

**Comment by SRJohnston** [comment]
Ah I thought I had done that, this is the first time I have logged an issue, so it is a learning curve.  How do I go about moving it?

**Comment by SRJohnston** [comment]
Incorrectly logged.
