### ISSUE TITLE
404 when trying to login with credentials 'Rest of the world'

### ISSUE THREAD

**Issue by Snipermods** [home-assistant/frontend#19873]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

404 error when logging in to use integration.

### Describe the behavior you expected

To login and get entities.

### Steps to reproduce the issue

Add integration BMW Connected drive
Enter credentials
Select rest of world
Submit
Success! dialogue box appear
"Retrying setup: Error communicating with BMW API: Client error '404 Resource Not Found' for url 'https://cocoapi.bmwgroup.com/eadrax-vcs/v2/vehicles' For more information chec..."
tried to reinitalise and fails contuinesly with same error message
![Error Message](https://github.com/home-assistant/frontend/assets/43371436/17e46c24-a8b7-4239-bbfa-e06be309e97d)

### What version of Home Assistant Core has the issue?

Home Assistant 2022.10.5 Frontend 20221010.0 - latest

### Which operating system are you using to run this browser?

WINDOWS 10 - 10.10.19045

**Comment by karwosts** [comment]
This isn't a frontend issue, for bmw specific issues you'll need to file a core issue for the bmw integration.

**Comment by Snipermods** [comment]
Apologies for incorrectly filing the bug.

**Comment by karwosts** [comment]
No problem! Just want to make sure you get to the right place. Good luck.
