### ISSUE TITLE
Unable to enter negative numbers on iOS or Andorid

### ISSUE THREAD

**Issue by lesma** [home-assistant/frontend#19893]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When using Chrome on Android, the App on Android, Safari on iOS or the App on iOS you are unable to enter negative numbers despite being able to on the desktop. I do wonder if it might be something to do with the regex validation but that is very much a guess on my part.

Interesting Samsung Internet on Android does not appear to have the issue, so I suspect that its not applying the validation on it which the others are.

Moved from iOS repo: [https://github.com/home-assistant/iOS/issues/2270](url)

**On Mobile Chrome on Android**
![Screenshot_20240226_171943_Chrome](https://github.com/home-assistant/frontend/assets/4517893/ecfc1b95-8004-4d24-8760-d0ca6f614239)

On Desktop Firefox on Windows 11:
<img width="778" alt="Screenshot 2024-02-26 185034" src="https://github.com/home-assistant/frontend/assets/4517893/c053e1ab-8f41-42e0-834f-88f4c9081c3a">

### Describe the behavior you expected

Be able to enter negative numbers

### Steps to reproduce the issue

1. In Chrome on Android, the App on Android, Safari on iOS or the App on iOS try and enter a negative number

### What version of Home Assistant Core has the issue?

2024.2.4

### In which browser are you experiencing the issue with?

Multiple

### Which operating system are you using to run this browser?

Multiple

**Comment by karwosts** [comment]
I don't think it's specifically an issue for all android, as my android number pad includes a `-` sign for these fields. Maybe just a thing with the speicific android manufacturer thing that they didn't include it in their numeric keyboard? Not sure about iOS. 

I don't necessarily think it's the pattern that's the issue here, as I see that also but I have no problem entering negative numbers in a `number` entity in my android mobile 😕

**Comment by lesma** [comment]
Something very odd certainly.

The Samsung Keyboard does not allow negative numbers in Chrome or The App but does in Samsung Internet. The SwiftKey Keyboard does allow negative numbers in Chrome and the app.

Seems to be a bit of an issue on the Samsung Keyboard https://stackoverflow.com/questions/21677695/input-type-number-not-possible-to-insert-negative-numbers-on-mobile-phone and https://stackoverflow.com/questions/72049280/how-to-solve-the-galaxy-numeric-keyboard-nightmare. Does seem very odd that it works on Samsung Internet with the Samsung Keyboard though.

I don’t actually have an iOS device to test it was one of the iOS maintainers bgoncal who confirmed it was an issue for them. Though https://forums.developer.apple.com/forums/thread/711839 and https://betterprogramming.pub/12-shades-of-keyboard-types-in-ios-a413cf93bf4f suggests its possbile to get this to work for iOS in a more robust way than with the Samsung Keyboard

**Comment by hansw96** [comment]
This is indeed an issue on iPhone. Only way to get a negative number in there is to copy paste from somewhere else. 

![IMG_2440](https://github.com/home-assistant/frontend/assets/11186734/1955f213-aae6-4e4a-af40-c44efa17f0c3)
