### ISSUE TITLE
Proximity ‐ Polish translation

### ISSUE THREAD

**Issue by Tomaszek77** [home-assistant/frontend#19909]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I think there is a problem with Polish translation to Proximity integration.

### Describe the behavior you expected

Wrong translations:
Moving in: oddalanie
Moving away: zbliżanie

Correct translations:
Moving in: zbliżanie
Moving away: oddalanie

### Steps to reproduce the issue

1. Run application with Proximity integration
2. Move in and out of your zone
3.
...

### What version of Home Assistant Core has the issue?

2024.2.4

### In which browser are you experiencing the issue with?

Application for Android

### Which operating system are you using to run this browser?

Android 14

**Comment by silamon** [comment]
Those translations are provided by the integration to the frontend. You will need to open an issue at https://github.com/home-assistant/core against the Proximity integration or you can also change the translations yourself using https://developers.home-assistant.io/docs/translations/ and join the backend team to find the Proximity translations.

**Comment by Tomaszek77** [comment]
Don't know how to do it.
Never mind...

Thanks

śr., 28 lut 2024, 17:58 użytkownik Simon Lamon ***@***.***>
napisał:
