### ISSUE TITLE
When View type list is a dropdown, Section type is greyed out

### ISSUE THREAD

**Issue by raman325** [home-assistant/frontend#19916]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have layout-card installed which adds support for additional view types. Because the list of view types expands, the View Type component switches from radio buttons to a dropdown. In the dropdown, sections remains greyed out, even when creating a new view. When I removed layout-card, the component switched back to radio and the sections option was available

### Describe the behavior you expected

see above

### Steps to reproduce the issue

1. Load enough view types that the view type component switches to a drop down
2. Create a new view
3. Try to set the view type to sections
...

### What version of Home Assistant Core has the issue?

2024.3.0b0

### Additional information

Radio:
<img width="559" alt="image" src="https://github.com/home-assistant/frontend/assets/7243222/41e29308-ceb2-4483-8c36-2a67c33415d8">

Dropdown:
<img width="334" alt="image" src="https://github.com/home-assistant/frontend/assets/7243222/5a61fccb-0bb6-43af-aaea-1b8a167ed1b1">

**Comment by raman325** [comment]
@piitaya FYI

**Comment by karwosts** [comment]
I might be suspecting layout card here. If I just add some fake types to the view, it changes to a dropdown, but nothing is greyed out.

![image](https://github.com/home-assistant/frontend/assets/32912880/52b10f59-9d03-498a-a548-bd4909d47d40)

**Comment by raman325** [comment]
CC @thomasloven ^^

**Comment by karwosts** [comment]
Yeah I think so, fairly certain this is an issue that needs to be corrected there.

I believe in layout-card it is not passing the new arguments (`this._type` and `this.isNew`) to _oldSchema, so the disable logic thinks it is not a new section and it can't be enabled.

From default hui-view-editor:
>     const schema = this._schema(this.hass.localize, this._type, this.isNew);

**Comment by raman325** [comment]
thanks for the quick response! I will open a new issue there
