### ISSUE TITLE
MJPEG Stream Not Loading in Safari Due to Service Worker Issue

### ISSUE THREAD

**Issue by aaronk6** [home-assistant/frontend#19913]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I’m using Home Assistant 2024.2.5 (running HAOS 12.0) and have installed the NGINX Home Assistant SSL proxy add-on to access HA via HTTPS. This is working fine, except that in Safari (v. 17.0 and 17.3.1), the MJPEG camera stream won’t load. It’s working fine in Chrome and the Home Assistant macOS app though.

The issue seems to be related to HA’s service worker. In Safari’s private browsing mode, in which service workers aren’t executed, it is working fine. Same without HTTPS, which also bypasses the service worker.

### Describe the behavior you expected

I expect the video stream to work in Safari.

### Steps to reproduce the issue

1. Set up the MJPEG camera component
2. Enter an MJPEG url (i.e. http://doorbird.myhostname.example.com/bha-api/video.cgi)
3. Enter username and password
4. Add the camera view to a dashboard using a picture-glance card

### What version of Home Assistant Core has the issue?

core-2024.2.5

### In which browser are you experiencing the issue with?

Safari 17.3.1 (19617.2.4.11.12)

### Which operating system are you using to run this browser?

macOS Sonoma (14.3.1)

### Problem-relevant frontend configuration

```yaml
- type: picture-glance
  camera_view: live
  entities:
    - binary_sensor.doorbird_motion
  camera_image: camera.doorbird_mjpeg
```

### Javascript errors shown in your browser console/inspector

In Safari, when I go to _Develop › Service Workers › myhostname.example.com_ in a non-private window, I see the following error:

```txt
Unhandled Promise Rejection: NetworkError:  A network error occurred.
Failed to load resource: the server responded with a status of 403 ()
```

### Additional information

<img width="1183" alt="Screenshot 2024-02-28 at 21 37 06" src="https://github.com/home-assistant/frontend/assets/446063/15af1173-caf5-46e5-b941-2aeec7b57989">

**Comment by marcoach** [comment]
Hello,

Same here, I 've tried all the buttons combination without success.  If i delete the cache loads the stream for some seconds and then reloads the page and the video is still missing again.

**Comment by noah-wardlow** [comment]
Seeing this too!

**Comment by x2110311x** [comment]
Also seeing this

Core 2025.1.4
Supervisor 2024.12.3
Operating System 14.2
Frontend 20250109.2

Running Safari on macOS 15.

**Comment by kubert96** [comment]
Any update? Thanks.
