### ISSUE TITLE
Sections dashboard: conditional cards occupying space

### ISSUE THREAD

**Issue by jorgwolski** [home-assistant/frontend#19925]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When using conditional cards with unmet conditions on a sections dashboard, the contents are hidden, but the space in the grid is still occupied.

### Describe the behavior you expected

Conditional card with unmet conditions is hidden and grid space is allocated to the next card.

### Steps to reproduce the issue

1. Create a sections dashboard
2. Create a section
3. Fill the section with some content
4. Create a conditional card with content
5. Create additional cards (optional)
6. Make the condition not met

### What version of Home Assistant Core has the issue?

core-2024.03.0b0

### What was the last working version of Home Assistant Core?

none

### In which browser are you experiencing the issue with?

Firefox 123.0, HA Companion App

### Which operating system are you using to run this browser?

Windows 11 Ver. 23H3 Build 22631.3155

**Comment by dshokouhi** [comment]
Just for the sake of completeness wanted to attach a screenshot here. I have a lot of stacked conditions that I like to see at the top of the page for items that need attention. I have rebuilt my conditions in the UI. Below is a before vs after comparison.

![image](https://github.com/home-assistant/frontend/assets/1634145/3eb161b1-62b9-49b8-a617-928ef30c1acb)
![image](https://github.com/home-assistant/frontend/assets/1634145/6fb50cda-7c2f-47fd-8ca9-efeff4cb63d1)

**Comment by piitaya** [comment]
@dshokouhi Are you using the latest version of HA (2024.3.1) ?

**Comment by dshokouhi** [comment]
@piitaya yup frontend version `20240307.0` I see the empty space in Chrome desktop as well

![image](https://github.com/home-assistant/frontend/assets/1634145/9fb12c7e-0d0d-4e0b-8ba3-14dff16838c2)

**Comment by piitaya** [comment]
Can you share the yaml code to reproduce it? 🙂

**Comment by dshokouhi** [comment]
@piitaya apologize I thought I was using conditional cards but apparently I misspoke and they are `entity-filter` type 😅 

here is a sample YAML from the above screenshots: https://pastebin.com/0YycyXzF

let me know if you prefer I create a new issue for this

**Comment by piitaya** [comment]
No it's ok to keep this issue open 🙂 thank you

**Comment by piitaya** [comment]
@Ali229 can you share the yaml code?

**Comment by Ali229** [comment]
type: vertical-stack
cards:
  - type: conditional
    conditions:
      - entity: sensor.washer
        state: 'on'
    card:
      type: custom:laundry-card
      entity: sensor.washer
  - type: conditional
    conditions:
      - entity: binary_sensor.washer_error_state
        state: 'on'
    card:
      square: false
      columns: 2
      type: grid
      cards:
        - type: entity
          entity: binary_sensor.washer_error_state
          name: Error State
          icon: mdi:washing-machine-alert
        - type: entity
          entity: sensor.washer_error_message
          name: Error Msg
          icon: mdi:message-alert

**Comment by piitaya** [comment]
Remove your vertical stack, it's not useful in sections. You can directly use conditional card in the section.

**Comment by Ali229** [comment]
That's what it was thank you!

**Comment by dshokouhi** [comment]
So I got a chance to update to 2024.4.1. Using the same YAML I [provided earlier](https://github.com/home-assistant/frontend/issues/19925#issuecomment-2002214278). I can see that there is still a gap in between a set of cards. So the top padding looks fixed but if the cards have an empty card in between them then it is still taking up space

![image](https://github.com/home-assistant/frontend/assets/1634145/be723a4e-dda0-469d-9132-7c31bc1b38fd)

![image](https://github.com/home-assistant/frontend/assets/1634145/fd81b776-774e-4fb9-a7ea-dc68db34f22a)
