### ISSUE TITLE
Using fire-dom-event action breaks cards UI editors.

### ISSUE THREAD

**Issue by kulmegil** [home-assistant/frontend#19926]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Setting action `type: fire-dom-event` forces entire card editor into yaml only mode.

### Describe the behavior you expected

Action `type: fire-dom-event` should be marked as valid as well as any custom data defined in this action config.
Only action config portion can be defined in yaml only mode.

### Steps to reproduce the issue

1. `fire-dom-event` actions are handled by 3rd party components such as [browser-mod](https://github.com/thomasloven/hass-browser_mod) so it's recommend to install it for testing. But it's not required since event can be captured in dev tools as well.
2. Create a card and setup `fire-dom-event` action type.
...

### What version of Home Assistant Core has the issue?

core-2024.2.1

### What was the last working version of Home Assistant Core?

core-2024.1.1

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

any

### Problem-relevant frontend configuration

```yaml
type: tile
entity: sensor.hydro_imgw_151170030
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.notification
    data:
      message: Test!
```

### Javascript errors shown in your browser console/inspector

```txt
Card-mod r: At path: tap_action.action -- Expected one of `"none","toggle","more-info","call-service","url","navigate","assist"`, but received: "fire-dom-event"
    r https://homeassistant.kozanow.duckdns.org:8123/frontend_latest/63428.qeC0nhk682k.js:1
    d https://homeassistant.kozanow.duckdns.org:8123/frontend_latest/63428.qeC0nhk682k.js:1
    f https://homeassistant.kozanow.duckdns.org:8123/frontend_latest/63428.qeC0nhk682k.js:1
    value https://homeassistant.kozanow.duckdns.org:8123/frontend_latest/79943.sJciNme-rVA.js:1
```

### Additional information

[HA-fire-dom-event.png](https://github.com/home-assistant/frontend/assets/570575/cb23c152-d153-46d3-ac17-f35bfde1f783)

**Comment by karwosts** [comment]
Related #19379 and #19390.
