### ISSUE TITLE
When renaming a device, dialogue box for auto renaming entitys is not displayed 

### ISSUE THREAD

**Issue by Alex-joomla** [home-assistant/frontend#19924]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When renaming a device, with the pencil tool top right, there should appear a dialogue box where the user will be asked if the entities shoul be renamed automaticaly.

### Describe the behavior you expected

Dialogue Box should appear, entities should be renamed

### Steps to reproduce the issue

Situation:
<img width="1501" alt="Bildschirmfoto 2024-02-29 um 20 56 17" src="https://github.com/home-assistant/frontend/assets/32268233/717c7a24-2ed0-4b4b-9bd6-3d204724f229">
Klick on edit, edit the device name
<img width="1703" alt="Bildschirmfoto 2024-02-29 um 20 56 27" src="https://github.com/home-assistant/frontend/assets/32268233/a36705b3-6e9f-4737-935a-64f81e7681bb">
Result after hitting update: (Device view)
<img width="1712" alt="Bildschirmfoto 2024-02-29 um 20 56 38" src="https://github.com/home-assistant/frontend/assets/32268233/045fd97e-455b-4897-a815-ad0ebbaf6dcf">

Entity: 
<img width="580" alt="Bildschirmfoto 2024-02-29 um 20 56 48" src="https://github.com/home-assistant/frontend/assets/32268233/302c0f64-0d2b-45ec-940f-a1121d9fcab1">

### What version of Home Assistant Core has the issue?

core-2024.2.5

### What was the last working version of Home Assistant Core?

--

### In which browser are you experiencing the issue with?

Safari Version 17.2.1 , Edge, Firefox

### Which operating system are you using to run this browser?

macOS Ventura 13.6.3

**Comment by matthiasdebaat** [comment]
Do you have `Advanced mode` turned on in your [profile](https://my.home-assistant.io/redirect/profile/)?

We're currently investigating the magic behind Advanced mode. We want to fix this.

**Comment by Alex-joomla** [comment]
No I even didn't know about this toggle. Now, as I turned it on, it works as i know it. NICE!
AND additionally i now have the button to reload yaml again, instead of rebooting HA completely!

**Comment by Alex-joomla** [comment]
Solved
