### ISSUE TITLE
Badges not correct aligned

### ISSUE THREAD

**Issue by gieljnssns** [home-assistant/frontend#19956]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since the update from 2024.3.0b3 to 2024.3.0b5 my badges are aligned to the left. 
![Scherm­afbeelding 2024-03-03 om 10 26 07](https://github.com/home-assistant/frontend/assets/17234951/bf3c40a3-d588-4474-a751-83223f159df9)

### Describe the behavior you expected

They should be in the center.

### Steps to reproduce the issue

1. Update to 2024.3.0b5

### What version of Home Assistant Core has the issue?

core-2024.3.0b5

### What was the last working version of Home Assistant Core?

core-2024.3.0b3

### In which browser are you experiencing the issue with?

Arc Versie 1.32.0 (46908)

### Which operating system are you using to run this browser?

14.4 bèta (23E5211a)

**Comment by silamon** [comment]
Most likely introduced by removing these lines in a recent PR: https://github.com/home-assistant/frontend/pull/19929/files#diff-bdbfba386fa5cdc890f61fbc4126992ccf6440126f77f3b66a8dcc632a16171bL294-L299
