### ISSUE TITLE
Area Card: Diagnostic binary sensor for battery are not shown

### ISSUE THREAD

**Issue by DanielHabenicht** [home-assistant/frontend#19951]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When specifying "battery" in the `alert_classes` of an area card with a known battery warning (meaning the binary_sensor of the battery entity is on):
![image](https://github.com/home-assistant/frontend/assets/13590797/4021488e-897c-4e14-9fe3-006e8973ef9b)

No alert is shown, as it would be with an open window. 

### Describe the behavior you expected

I would expect a battery symbol to be shown, as it would be the case for an open window: 
![image](https://github.com/home-assistant/frontend/assets/13590797/a36636f3-38f7-4fd9-bd19-6a22c4d87303)

### Steps to reproduce the issue

1. Configure a Device with a Diagnostic battery sensor (`binary_sensor`) and add it to an area 'X'. 
2. Configure an area card for area 'X'. 
3. Add the Battery class to alert_classes.
4. Set the state of the battery `binary_sensor` to on. 
5. No icon is displayed on the card.

### What version of Home Assistant Core has the issue?

core-2024.2.5

### In which browser are you experiencing the issue with?

Google Chrome Version 122.0.6261.69 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
A battery diagnostic sensor in the area:

binary_sensor.radiator_thermostat_1_battery_low: on
```

### Problem-relevant frontend configuration

```yaml
alert_classes:
  - window
  - battery
sensor_classes:
  - temperature
  - humidity
type: area
area: sekretariat
navigation_path: /dashboard-ubersicht/eg-sekretariat

```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

Seems like any sensor with a class is filtered from being displayed in the card: 
https://github.com/home-assistant/frontend/blob/94e70f81edb58bb8ad270a20d31cf9880be677e3/src/panels/lovelace/cards/hui-area-card.ts#L130-L137

As Diagnostic Devices already have `entity_category: "diagnostic"` set.

**Comment by karwosts** [comment]
I assume it's always been the intention for this card to hide diagnostic sensors, as they are sort of intended as not the "primary" sensors of interest for an area, but just secondary information. Admittedly its a grey area.

I've heard that there are some plans in the work for more configuration options for areas that might allow you to choose what sensors are relevant for your area, but I think that's a long term project.

If you really want this sensor shown, I guess the best way that could be achieved right now is just to make a new template sensor for it, and then it would not be tagged as diagnostic.

**Comment by DanielHabenicht** [comment]
Get it, but what's the benefit of not making them availabe here? One has to set which one to display anway. 

I would rather contribute that, than adding a template sensor for each of my battery sensors.

**Comment by karwosts** [comment]
I guess it's a question of if having those secondary sensors displayed would pollute the card or otherwise mess up the information that most people want to be shown. 

I guess I think it's probably mostly an issue for the sensors which do averaging (less so for binary sensors), where having a diagnostic sensor "averaged" with the primary sensor would mess up the result, like maybe where a device has a diagnostic temperature sensor that you don't want or expect to be averaged with a primary room temperature sensor. 

But specifically for the binary sensors, maybe an argument could be made to include the diagnostic ones as well.

If you're interested in contributing, feel free to make a pull request for the behavior you think would be correct, and you can get maintainer feedback to see if it's something they would accept. I was just pointing out why I believed it was designed this way.

**Comment by DanielHabenicht** [comment]
Yes, if contributing I would only include the binary sensors, but as I read it the current "alert_classes" only accept binary sensors anyway. I wouldn't change the "sensor_classes"
