### ISSUE TITLE
Ufh controller display

### ISSUE THREAD

**Issue by Rosshend69** [home-assistant/frontend#19950]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The temperature display in HA shows 4degC but device shows 24degC

### Describe the behavior you expected

Temperature should be the same as display

### Steps to reproduce the issue

1.add device
2.open entity
3.
...

### What version of Home Assistant Core has the issue?

2024.2.5

**Comment by spacegaier** [comment]
Please check in the developer tools in the "States" tab, what the backend provides as data for your entity. If what you see there is the same as is shown in the HA frontend, then the frontend behaves as expected and it might be a backend issue instead.

**Comment by Rosshend69** [comment]
Thanks for that. Yes it’s a backend issue. Same data is shown in developer section. Is it possible to apply calibrations to sensor and point values?RegardsRossOn 11 Mar 2024, at 19:03, Philip Allgaier ***@***.***> wrote:﻿
Please check in the developer tools in the "States" tab, what the backend provides as data for your entity. If what you see there is the same as is shown in the HA frontend, then the frontend behaves as expected and it might be a backend issue instead.

**Comment by spacegaier** [comment]
I can't answer that, but the backend team might. Please raise an issue here and fill in the required details such as the integration you are using, what controller/device, ... https://github.com/home-assistant/core
