### ISSUE TITLE
Tile card (climate) inconsistent Title Case for custom Fan modes.

### ISSUE THREAD

**Issue by CV8R** [home-assistant/frontend#19961]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When adding a Tile card for a climate entity with custom fan modes the first letter case of each word is inconsistent with types Auto, Low, Medium and High.  The auto is displayed as "Auto" and the remaining are "one", "two" and "three".

```
fan_modes:
  - auto
  - one
  - two
  - three
```

### Describe the behavior you expected

Items:

```
fan_modes:
  - auto
  - one
  - two
  - three
```

Should be displayed as "Auto", "One", "Two" and "Three".

### Steps to reproduce the issue

1. Create climate device with custom fan modes
2.Add a tile card for the climate device
3. Add Climate fan modes feature
4. Fan modes list has lower case first letter for custom modes and upper case for built-in fan modes

### What version of Home Assistant Core has the issue?

Core 2024.2.5 Supervisor 2024.02.1 Operating System 12.0 Frontend 20240207.1

### Additional information

May impact other lists in Tile cards.

**Comment by karwosts** [comment]
I believe the casing comes from the translations provided by the integration, it's likely that `auto` has a generic translation but the translation for the others are not provided. So I don't think there's anything to do in frontend.

**Comment by CV8R** [comment]
The inconsistency is the issue here, the integration could change the case, but then couldn't the result maybe different across OS depending on case sensitivity.

All the standard modes are treated the same. low becomes Low, high becomes High etc.
