### ISSUE TITLE
WLED only first 3 Presets show in select

### ISSUE THREAD

**Issue by Hulumanu** [home-assistant/frontend#19965]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

WLED integration will only show the first 3 presets in the select list.  I have tried to reload the configuration multiple times, but to no avail.  Entering the name of an unlisted preset in HA is not allowed.

### Describe the behavior you expected

Would like the ability to select more than the first 3 presets as defined in WLED native interface.

### Steps to reproduce the issue

1. Configure more than 3 presets in WLED
2. Perform reload of configuration in the WLED Integration for the device
3. Only 3 presets show in select list on device page
...

### What version of Home Assistant Core has the issue?

2024.2.5

**Comment by karwosts** [comment]
If you go to developer-tools/state, find your wled preset entity, does it show more than three presets in the attributes list?

E.g. under the options: key?

![image](https://github.com/home-assistant/frontend/assets/32912880/7296fb8a-769d-478c-a621-700eaa27c0ff)

**Comment by Hulumanu** [comment]
No, Just shows the 3....

**Comment by Hulumanu** [comment]
Ok, so I just re-installed HACS (I had experimental enabled and was getting GitHub page ;-p)... so I had to restart HA, and now all were there.  I then created a new preset, closed down the WLED page, went into HA WLED Device and Reloaded, resaved System options, ... new one is not there.  I then restarted HA again and new one showed up.  I then deleted the preset in WLED, same (old list, restart HA, new list).... seems have to restart HA to get any type of updated list.....  Is there some way to get the configuration from WLED without restarting HA?  Thanks for the help btw... new to HA and just feeling my way around and wasn't sure if I was doing things right....

**Comment by karwosts** [comment]
If only three options are listed in the attributes, than this isn't really a frontend issue, we just show what core provides. 

As for specifics of WLED and configuration reloading, those are core related questions, not for frontend. You can make a core issue for wled integration to follow up that issue.
