### ISSUE TITLE
Switching a group in the UI that contains valves does not work

### ISSUE THREAD

**Issue by qbushome** [home-assistant/frontend#19975]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Switching a group in the UI, containing valves does not work when clicking on the small switch (left to right), while the group can be switched in an automation.
The switch turns on for halve a second and goes off again.
When clicking on the name of the entity (the group), the big switch (up-down) appears. Clicking this one _does_ work.

### Describe the behavior you expected

Same behaviour in UI as in yaml-code

### Steps to reproduce the issue

1. Create a group containing multiple valve-entities.

`zv_woonkamer:
  name: ZV Woonkamer
  entities:
    - valve.zv_eetkamer_midden
    - valve.zv_eetkamer_raam
    - valve.zv_zithoek_midden
    - valve.zv_zithoek_raam`

2. Create an automation that calls a service valve.open_valve to that group, just to verify this is working

`- service: valve.open_valve
        entity_id:
          - group.zv_woonkamer`

3. Add the same group in lovelace

`- type: entities
    show_header_toggle: false
    title: Woonkamer group
    entities:
      - entity: group.zv_woonkamer`

### What version of Home Assistant Core has the issue?

2024.2.5

### Problem-relevant frontend configuration

```yaml
`- type: entities
    show_header_toggle: false
    title: Woonkamer group
    entities:
      - entity: group.zv_woonkamer`
```

**Comment by karwosts** [comment]
Seems this is because when we toggle a legacy group in entities, we call `homeassistant.turn_on` for each entity in the group, but that service is not valid for valves. 

Not sure what the right answer is yet.

**Comment by qbushome** [comment]
Sorry for the bad formatting, for some reason the break at the end of each line didn't work.
Some time ago I created a new topic on the community forum for this with better formatting:
[https://community.home-assistant.io/t/switch-on-a-group-with-valve-entities/688626](url)

About your findings, the logfile indeed shows:

`The service homeassistant.turn_on does not support entities valve.zv_eetkamer_midden, valve.zv_eetkamer_raam, valve.zv_zithoek_midden, valve.zv_zithoek_raam`

**Comment by qbushome** [comment]
Now on version 2024.11.1 and the issue is still present.
Not sure what the procedure is for cases like this, so I'm just reporting.
Thank you
