### ISSUE TITLE
UI re-ordering(dragging)  items in a select causes visual mayhem in Safari/Mac

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#19989]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

<img width="923" alt="Scherm­afbeelding 2024-03-05 om 08 16 12" src="https://github.com/home-assistant/frontend/assets/33354141/977b91c8-e263-4b2f-87cf-c15bae96f510">

only happening in Safari browser on the Mac, Chrome seems fine

### Describe the behavior you expected

only drag the item 

### Steps to reproduce the issue

0. go to /config/helpers and type a search phrase 
1. click cogwheel on entity
2. select item and drag to re-position
3. the search result of 0. shines through and gets dragged along
...

### What version of Home Assistant Core has the issue?

2024.3.0b6

### In which browser are you experiencing the issue with?

Safari 17.2.1

### Which operating system are you using to run this browser?

Sonoma 14.2.1

**Comment by SeanPM5** [comment]
Not stale, still an issue
