### ISSUE TITLE
in beta 2024.3.0b5 badges larger and left aligned

### ISSUE THREAD

**Issue by pjannink** [home-assistant/frontend#19981]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Badges seems larger and are left aligned instead of centered

### Describe the behavior you expected

Badges in old sizing and centered on the screen

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.3.0b5

### What was the last working version of Home Assistant Core?

2024.2

### In which browser are you experiencing the issue with?

Firefox 123.0

### Which operating system are you using to run this browser?

Windows 11

### Additional information

<img width="916" alt="2024 2 5" src="https://github.com/home-assistant/frontend/assets/85283776/0a783116-7050-4fdd-a17d-cb0a6c8333dd">
<img width="1096" alt="2024 3 0b5" src="https://github.com/home-assistant/frontend/assets/85283776/1ab48a9c-15b5-4e2b-9ca1-05640f0ab86c">

**Comment by karwosts** [comment]
Was already reported and fixed, thanks. #19956
