### ISSUE TITLE
History gets unloaded in History graph

### ISSUE THREAD

**Issue by joostlek** [home-assistant/frontend#19997]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I had one entity loaded in the history graph. I switched windows, did some stuff, then came back and the LTS of the entity loaded in, but not the recent history.
![image](https://github.com/home-assistant/frontend/assets/7083755/55867a95-2236-4593-878b-3ad23cb8d9c4)
![image](https://github.com/home-assistant/frontend/assets/7083755/c1d62dc6-72c4-4e7b-b578-ab12368df943)

### Describe the behavior you expected

I expect that after I come back it loads the recent history.

### Steps to reproduce the issue

1. Open an entity in the history
2. For time select this week
3. Then do some other stuff
4. Go back to home assistant
5. See it refresh
6. Now only the LTS are loaded, not the recent history

### What version of Home Assistant Core has the issue?

core-2024.3.b50

### In which browser are you experiencing the issue with?

macos app

**Comment by ildar170975** [comment]
@joostlek 
Did you open another History view while "doing some stuff"?

**Comment by joostlek** [comment]
Not that I know of, I think I also had 1 tab open, I'll double check when I'm back in my room

**Comment by joostlek** [comment]
Nope I do not

**Comment by joostlek** [comment]
Not saying I could not have opened one in the meantime or on my phone or something, but I am 95% sure I did not open another history view
