### ISSUE TITLE
Missing translation "Auto Configure", etc.

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#19996]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Found missing words in lokalise
![image](https://github.com/home-assistant/frontend/assets/61636045/d5dfc43b-00e5-4034-8c9a-88368d204a88)

Link to source code
https://github.com/home-assistant/frontend/blob/32e8d2043c3e3595880eea9d007db38768545908/src/components/ha-network.ts#L73

### Describe the behavior you expected

Please add found to lokalise.
Thank you.

### What version of Home Assistant Core has the issue?

2024.2.5

**Comment by karwosts** [comment]
duplicate https://github.com/home-assistant/frontend/issues/18234
