### ISSUE TITLE
history-graph is shown for an entity excluded from Recorder

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#20008]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

2024.3 changed `history-graph`:
it started showing graphs for entities which were excluded from Recorder:
```
type: history-graph
entities:
  - entity: sensor.service_zero_value
```
![image](https://github.com/home-assistant/frontend/assets/71872483/356e7bc1-d7c2-4b6c-ad06-c454f21e1d33)

The shown history could be absolutely wrong since this entity is not recorded.
Then there is no sense to show this history.

Earlier  for not-recorded entities a history was shown only in case of NEW changes made while displaying the history.
Showing a past history based on a last value spanning a whole period is meaningless.

### Describe the behavior you expected

Do not show past history for not-recorded entity.
Show only new changes if a user intentionally added this entity to `history-graph` or looks at a history in more-info.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2024.3

### What was the last working version of Home Assistant Core?

2024.2.5

### In which browser are you experiencing the issue with?

Chrome 122.0.6261.95

### Which operating system are you using to run this browser?

Win10x64

**Comment by Petro31** [comment]
HA has done this for a long time now in the more info page with excluded entities.  I'm not surprised it does the same thing in history-graph.

**Comment by ildar170975** [comment]
> I'm not surprised it does the same thing in history-graph.

Read my post again. In more info excluded entities did not have a history. It only started displayng when you have more-info open and a changing stated in parallel.

Guess this new behaviour related to https://github.com/home-assistant/frontend/pull/19176.

**Comment by WarC0zes** [comment]
Hi,
I noticed the same behavior. I excluded entities from the recorder and before I didn't see anything in history. Since core 2024.3.0, I see entity history that is excluded.

**Comment by ildar170975** [comment]
2024.4.3:
If entity is excluded from Recorder - it is shown in History starting from the last HA reboot:

![image](https://github.com/home-assistant/frontend/assets/71872483/f891a211-19b0-4ba9-ad54-737fe29b26b5)

More-info shows only this "false recorded part":

![image](https://github.com/home-assistant/frontend/assets/71872483/302ddfe9-3237-4bbc-8e82-3f1a29e25aa4)

Both graphs do not reflect that this entity could have changes within this period.
