### ISSUE TITLE
Energy dashboard navigation skips by 1 day

### ISSUE THREAD

**Issue by antamy** [home-assistant/frontend#20004]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have created an Energy dashboard with two sensors.  On entering the dashboard data is displayed for the current day.

If I click on the left and right arrows next to the date in the upper right of the page, the dashboard moves by two days.  So, on March 6, clicking the left arrow moves to March 4.  If I then click on Today, the dashboard shows March 5 - 6.  If I then click on the Calendar, the dates March 4-6 are highlighted.  If I select a single day, that day's data is displayed, but the navigation is still in increments of 2 days.

I I choose to display  a week's worth of data such as This Week, I see Mar 3 - Mar 9.  Clicking the left arrow displays Feb 24 - Mar 1.  It is off by 1 day.

NOTE:  the energy dashboard behaves correctly in the Android app against the same HA instance.

### Describe the behavior you expected

The navigation should decrement / increment by 1 day, 1 week, 1 month etc.

### Steps to reproduce the issue

See description above

### What version of Home Assistant Core has the issue?

2024.3

### In which browser are you experiencing the issue with?

Latest Firefox, Latest Edge

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment]
I've not seen this myself. Curious, what is your server time zone setting, your client local time zone setting, and is your client set to use server time or local time zone (in profile options)?

**Comment by antamy** [comment]
> I've not seen this myself. Curious, what is your server time zone setting, your client local time zone setting, and is your client set to use server time or local time zone (in profile options)?

I have the same issue on two machines, both set to US Central time accessing a HA instance in US Eastern time (so 1 hour difference).  In my user profile, I have that set to use the server time zone.  I use the same user profile on my Android phone and that works fine.

I spun up a WIndows sandbox and changed the time zone to match the HA server.  When accessing that using my same profile, the behavior is correct.  So there is some issue with how the time zone is handled on the browser UI.

**Comment by jtbnz** [comment]
This occurs when the timezone is set to server - rather than local.

**Comment by antamy** [comment]
> This occurs when the timezone is set to server - rather than local.

Yep.  It's an annoying bug.  I've never understood why a user would want to see data on an instance in a different timezone in their current timezone!

**Comment by karwosts** [comment]
Will be fixed by #20191
