### ISSUE TITLE
Adding a badge name through single dashboard YAML editor removes all badges

### ISSUE THREAD

**Issue by deosrc** [home-assistant/frontend#20009]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When a custom name is added to a dashboard badge through the "Edit in YAML" option on the dashboard, all of the badges are removed.

### Describe the behavior you expected

The badge along with it's custom name should be persisted and shown on the dashboard.

### Steps to reproduce the issue

1. Create a new dashboard adding an entity as a badge and save.
2. Click the edit pencil next to the dashboard tab.
3. In the 3-dot options menu, select "Edit in yaml"

    ![image](https://github.com/home-assistant/frontend/assets/50599779/1384c06f-6f5a-4599-9bdf-ab10b6d716ea)

5. Add a `name` property to the badge
6. Click save

The badge will have been removed from the dashboard and does not show in the edit dialog.

If the configuration is updated through "Raw configuration editor" instead (to edit all dashboards rather than a single dashboard), then the configuration is accepted and the badge displays with the custom name.

### What version of Home Assistant Core has the issue?

2024.3.0

### In which browser are you experiencing the issue with?

Firefox 119.0.1, Edge 122.0.2365.66

### Which operating system are you using to run this browser?

Windows 10

### Problem-relevant frontend configuration

```yaml
title: test
path: test
badges:
  - entity: sensor.living_room_humidity
    name: Humidity
cards: []
```

**Comment by ildar170975** [comment]
Confirmed.
