### ISSUE TITLE
Unable to edit line items in the shopping list card following the 2024.1 changes

### ISSUE THREAD

**Issue by Bilhix** [home-assistant/frontend#20006]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Following the 2024.1 changes users are unable to edit line items inside the shopping list card, however users can edit the line items when launching todo lists from the sidebar. Have replicated this across multiple clients including iOS app (2024.3 2024.587, iOS 17.4) android app and various web clients.

If you load todo lists from the sidebar you can click on a line item, the same pop up will load and you are able to edit the line item.

Have also seen similar posts from other users in the community forum. 

### Describe the behavior you expected

When selecting a line item in the shopping list (following the 2024.1 changes) a pop up now loads and the item is greyed out and unable to edit. Prior to 2024.1 you could click on the line item and edit without loading a pop-up.

### Steps to reproduce the issue

1. Add line item to shopping list
2. Click on line item in shopping list card 
3. Attempt to edit line item in popup
...
![IMG_5476](https://github.com/home-assistant/frontend/assets/32077476/2f7764de-a01f-4484-8c63-a1b6d2641693)

### What version of Home Assistant Core has the issue?

2024.1

### What was the last working version of Home Assistant Core?

2023.12

### In which browser are you experiencing the issue with?

Safari 

### Which operating system are you using to run this browser?

iOS 17.4

**Comment by silamon** [comment]
Can you specify what kind of integration is providing this todo-list. Your screenshot is missing a few buttons which indicate that the shopping list you're trying to edit is readonly.

**Comment by silamon** [comment]
Can you share the entity state attributes of the shopping list? The entity id of the shopping list is displayed in the URL when you visit the shopping list from the sidebar. Then using developer tools search for that entity id and a row should appear with the properties.

It should say something like this: 
```
friendly_name: Shopping List
supported_features: 15
```

**Comment by maorcc** [comment]
Hi @silamon, I experience the same issue. Here is a screenshot from the developer tools with the information you asked about:

<img width="700" alt="image" src="https://github.com/home-assistant/frontend/assets/255973/6465efc6-daa0-4b2e-9d8a-67f0c3ff53e4">

**Comment by silamon** [comment]
Can you check if any javascript errors are printed to the browser console when you can reproduce the bug? I haven't been able to find the cause of the bug so far.

**Comment by maorcc** [comment]
@silamon , I don't see errors that seem related to Todo or to shopping-list.  We can debug it together on my computer in a Discord session.  My discord username is `maorc`.

**Comment by maorcc** [comment]
Do notice that the bug is related to shopping-lists cards created in a previous version of home-assistant.  If you create a new card (with the exact same yaml) it will work fine.

**Comment by maorcc** [comment]
The bug is related to shopping-lists cards created in a previous version of home-assistant, as it did not set an `entity` in the card.  To fix it, just delete the card and recreate it. Or set `entity: todo.shopping_list` in the card's yaml.

**Comment by silamon** [comment]
Thank you for looking into this. I've opened a pull request to allow the legacy shopping cart to behave the same as the new todo list cart.
