### ISSUE TITLE
[2024.3.0] Editing visibility of a dashboard does not work anymore 

### ISSUE THREAD

**Issue by seppeel** [home-assistant/frontend#20010]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When trying to edit the visibility of an existing dashboard page. It is not possible to save my changes.
The slider just jumps back after some seconds.
 -> Changing visibility is not possible at all

### Describe the behavior you expected

I can change the visibility for all users and can save my changes

### Steps to reproduce the issue

1. Create new dashboard page with any visibility settings
2.  Try to edit them after saving it the first time (looks like initial save is ok)

### What version of Home Assistant Core has the issue?

2024.3.0

### What was the last working version of Home Assistant Core?

2024.5.4

### In which browser are you experiencing the issue with?

Google Chrome 122.0.6261.111

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
no relevant enitites
```

### Problem-relevant frontend configuration

```yaml
I created a experimental sections card. May the bug is related to this.
```

### Javascript errors shown in your browser console/inspector

```txt
hui-dialog-edit-view.ts:475 Uncaught TypeError: Cannot assign to read only property 'visible' of object '#<Object>'
    at F.value (hui-dialog-edit-view.ts:475:20)
    at F.handleEvent (lit-html.ts:2018:29)
    at r (fire_event.ts:76:8)
    at t.value (hui-view-visibility-editor.ts:136:5)
    at F.handleEvent (lit-html.ts:2018:29)
    at HTMLDivElement.<anonymous> (mwc-switch-base.ts:121:14)
```

**Comment by craigrouse** [comment]
I'm pleased this is fixed. I too was creating an experimental "sections" view, and wanted to hide it from other family members!
