### ISSUE TITLE
The Sections LOVELACE dashboard performance degradation! Becomes unusable!

### ISSUE THREAD

**Issue by MrHollowPS** [home-assistant/frontend#20023]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I left the editing dashboard option for the new SECTIONS style dashboard and after a while it becomes unusable. This happens when not editing as well on browsers and on the HA android app.

https://youtu.be/dRuoWf-mz7s

You can check the video to see the performance drop. A refresh will fix the problem

### Describe the behavior you expected

The performance should not drop and the dashboard should be perfectly usable.

### Steps to reproduce the issue

Add cards and wait a while for the performance to degrade.
I am using Mini Graph Cards, Mini Media Player Cards and Mushroom Cards all from HACS.

### What version of Home Assistant Core has the issue?

2024.3.0

### What was the last working version of Home Assistant Core?

2024.2.5

### In which browser are you experiencing the issue with?

Google Chrome Version 122.0.6261.111 (Official Build) (arm64)

### Which operating system are you using to run this browser?

macOS Sonoma 14.3 (23D56)

### Additional information

If there is any kind of other data i can provide please let me know.

**Comment by silamon** [comment]
Could you try safe mode and see if it remains to happen?

**Comment by ildar170975** [comment]
Guess these custom cards ("I am using Mini Graph Cards, Mini Media Player Cards and Mushroom Cards all from HACS.") will not work in safe mode.

**Comment by chatziko** [comment]
I had the same issue (sluggish performance after some time, solved by refreshing). After some digging the culprit seems to be `mini-media-player` with `info: scroll`. Removing it fixes the problem.

Note that in my case the problem also appears with masonry, I just happened to realize while experimenting with the new sections layout.

**Comment by MrHollowPS** [comment]
@chatziko interesting. I've set it to short and and i'll update the thread if this fixes it. Thanks

**Comment by rrooggiieerr** [comment]
I think the whole idea of switching to safe mode is so your custom cards won't work and those can be eliminated as (or proven to be) the reason of your performance degradation.

**Comment by MrHollowPS** [comment]
I can confirm that the mediaplayer card was the culprit. it's been working perfectly for the past 2-3 days.

**Comment by MrHollowPS** [comment]
I can confirm that the mediaplayer card was the culprit. it's been working perfectly for the past 2-3 days.

Issue can be closed.

**Comment by Emilef22** [comment]
Hi! I have the same problem, 
So you put the info: short and it fixed it?
Thanks!

**Comment by MrHollowPS** [comment]
Did you read my last message? my issue was caused by a mediacard
