### ISSUE TITLE
Last Triggered/Used Sorting Missing from Automations List

### ISSUE THREAD

**Issue by theantfarmer** [home-assistant/frontend#20026]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hi.  The last triggered or last used sorting option is intermittently missing from the automations sorting list.  This is regardless of the browser or computer I access the UI from.  I'm unsure the exact phrasing because because I cannot see the option now.  I also try resizing the text, some times spend several minutes reloading and to get that sorting option to appear.  Sometimes doing so works, sometimes it doesn't.  It is frustrating because I am often looking to see which automations just triggered, and when I am unable to sort this way, I miss the opportunity to bug fix before other automations trigger.  It is an intermittent problem and I am not sure when or what causes that option to disappear or reappear.  Ideally, i should be able to just have this before the default sorting option so I dont have to worry about it.   

![by default 2024-03-08 at 11 12 49 AM](https://github.com/home-assistant/frontend/assets/132718779/81e36638-5edc-4ae4-bb07-08885a547d6c)

### Describe the behavior you expected

I expect to load the automations page in the UI and see an option to sort by the most recently triggered.  

### Steps to reproduce the issue

1. Load settings -> automations when I want to find out what just triggered
2.Load and reload and resize text and change browsers
3. keep trying

### What version of Home Assistant Core has the issue?

I install all updates as soon as they appear

### In which browser are you experiencing the issue with?

firefox, safari, chrome

### Which operating system are you using to run this browser?

One Monterey, one Ventura machine

**Comment by karwosts** [comment]
Will be fixed by #20160
