### ISSUE TITLE
Seeing old version of translations of new installation 

### ISSUE THREAD

**Issue by madsnedergaard** [home-assistant/frontend#20025]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I am seeing "Add CO2 Signal integration" in a new installation, despite the string being changed in version`20230901.0`.

![Screenshot 2024-03-08 at 16 34 40](https://github.com/home-assistant/frontend/assets/3296643/1cbe0cec-37b4-445f-82a2-f34089f7eaeb)

![Screenshot 2024-03-08 at 16 33 27](https://github.com/home-assistant/frontend/assets/3296643/c094fc27-b2bd-4748-a3b2-f607688dc990)

### Describe the behavior you expected

It should say "Add Electricity Maps integration". 

PS. I work at Electricity Maps, so that is also why I thought it was worth asking about this 😅 

### Steps to reproduce the issue

1. Install latest version using [tteck HAOS VM script](https://github.com/tteck/Proxmox/blob/main/vm/haos-vm.sh) on Proxmox
2. Initialise installation (using English GB as language)
3. Open Energy tab

### What version of Home Assistant Core has the issue?

core-2024.3.0

### In which browser are you experiencing the issue with?

Safari 17.1

### Which operating system are you using to run this browser?

macOS Sonoma (14.1.1)

**Comment by karwosts** [comment]
That is the current translation in Lokalise for English UK, So it's not a frontend issue, someone just needs to update the translations. Some other languages seem to still refernece co2 signal as well. 

https://app.lokalise.com/project/3420425759f6d6d241f598.13594006/?view=multi&k=118884359::610&search=key::ui::panel::config::energy::grid::add_co2_signal

![image](https://github.com/home-assistant/frontend/assets/32912880/200f3012-667a-44a7-99e5-70f92069cfcd)

**Comment by madsnedergaard** [comment]
Ah great, that makes sense - thanks for helping! I'll make a PR for updating it on Monday :)

**Comment by madsnedergaard** [comment]
I'll close this issue again as it is not an actual bug then.

**Comment by karwosts** [comment]
Just FYI you don't make PRs for updating translations. You just sign into lokalise and just edit the strings.

**Comment by madsnedergaard** [comment]
> Just FYI you don't make PRs for updating translations. You just sign into lokalise and just edit the strings.

Thanks, I have made the change now :)
