### ISSUE TITLE
Fan widget does not allow to pan the fan. (zhimi.fan.za4)

### ISSUE THREAD

**Issue by DooMMasteR** [home-assistant/frontend#20021]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The "direction drop down" is weirdly indicating "forward" and "reverse" and either can only be selected once.
Once selected the fan moves a bit into the direction but the element is now selected and the can cannot be moved again into the same direction.

![Screenshot from 2024-03-08 00-13-54](https://github.com/home-assistant/frontend/assets/204733/1c9c77b9-0c29-4a5a-a0b5-834ad7dd357b)

![image](https://github.com/home-assistant/frontend/assets/204733/37149cb9-87e8-4575-a7e8-6a41e74c1070)

### Describe the behavior you expected

I would expect 2 buttons, that can be repeatedly pressed to move the fan further than just a tad.

### Steps to reproduce the issue

1. Open the Fan widget
2. click on direction
3. select forward or reverse
4. try to select the previous item again.
...

### What version of Home Assistant Core has the issue?

2024.3.0

### In which browser are you experiencing the issue with?

any browser

### Which operating system are you using to run this browser?

Linux, Windows, Mac OS 14

**Comment by pvxe** [comment]
Just my two cents, I also have a similar issue with a `dmaker.fan.p10` (though the exact model of fan may be irrelevant for this issue).

Before https://github.com/home-assistant/frontend/pull/17540 I could turn the fan left or right by pressing the relevant button multiple times from the older frontend, unfortunately this is no longer the case with the new frontend.

**Comment by karwosts** [comment]
Is that really the intended function of `set_direction`, to set the orientation? Feels almost like that integration is using it as a mis-appropriation of what the feature is supposed to mean. 

I don't know but I am assuming direction means whether the blades are spinning in a clockwise or counterclockwise fashion, not something that is intended to allow for changing the angle of the direction of the blowing.

**Comment by pvxe** [comment]
> Is that really the intended function of `set_direction`, to set the orientation? Feels almost like that integration is using it as a mis-appropriation of what the feature is supposed to mean.
> 
> I don't know but I am assuming direction means whether the blades are spinning in a clockwise or counterclockwise fashion, not something that is intended to allow for changing the angle of the direction of the blowing.

Well if we take a look at https://github.com/home-assistant/frontend/blob/7120ad99b9bdd3d6dc648deb6ae5285d986f8744/src/fake_data/demo_services.ts#L922-L932 then you are absolutely right.

I'm not aware of any domestic floor/pedestal fan that is intended to provide functionality such as to change the blade turning direction/orientation. This functionality strikes to me as something related to ceiling fans.

Just giving my two cents as a user here, maybe there should be some distinction between blade direction (for ceiling fans) and pedestal fan orientation, which seems to be the case for this particular issue.

Cheers!
