### ISSUE TITLE
water_heater.set_temperature validation says value must be less than or equal to 100. No such limitation exists.

### ISSUE THREAD

**Issue by skylyn** [home-assistant/frontend#20030]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When viewing water_heater.set_temperature while creating an automation or in Developer tools, attempting to set a value above 100 results in a red underline and a validation error "Value must be less than or equal to 100."
![image](https://github.com/home-assistant/frontend/assets/4708347/10bf8dc2-39e9-46a8-9dd1-778c8e5bf9c6)

Note that this validation doesn't stop you from saving or submitting the call, and the call does work. The 100 limit is likely an assumption based on Celsius, but Fahrenheit water heaters will nearly always have set points above 100.

### Describe the behavior you expected

Validation matches backend limitation, doesn't show error on valid value.

### Steps to reproduce the issue

1. Open Developer Tools > Services
2. Select `water_heater.set_temperature`
3. In Temperature text box, enter 101
4. Hover over temperature box - note red underline and validation error message

### What version of Home Assistant Core has the issue?

2024.3.0

### In which browser are you experiencing the issue with?

122.0.6261.95 (Official Build) (64-bit) (cohort: Stable) 

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment]
This is defined in the core water_heater integration, so this needs to be a home-assistant/core issue, not frontend.

https://github.com/home-assistant/core/blob/03e4a20cdf998c2be6c5e4f2b10ca00112a2c094/homeassistant/components/water_heater/services.yaml#L23

**Comment by skylyn** [comment]
Thanks, I submitted https://github.com/home-assistant/core/issues/112868
