### ISSUE TITLE
User dashboards configuration - Save button still greyed out while changing Visibility

### ISSUE THREAD

**Issue by MrXANA91** [home-assistant/frontend#20041]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When configuring a user created dashboard through the UI, trying to change the Visibility settings will not ungrey the Save button.

### Describe the behavior you expected

Changing something in the Visibility view configuration settings should ungrey the Save button.

### Steps to reproduce the issue

1. Go to an existing dashboard page or create a new dashboard (go to Settings -> Dashboards, and add a new Dashboard from scratch, then go to the newly created dashboard page)
3. Click on Edit Dashboard on the upper right corner
4. Edit a View by clicking on the default Home tab, or any other existing tab
5. In the View Configuration, go directly to the Visibility tab and try to change a setting

### What version of Home Assistant Core has the issue?

core-2024.3.0

### In which browser are you experiencing the issue with?

Google Chrome 122.0.6261.112

### Which operating system are you using to run this browser?

Windows 10 22H2

### Additional information

Existing workaround :
Any slight change in the Settings tab will ungrey the Save button. For example, adding a character in the title and remove it immediately after will keep the Save button ungreyed. Then you can change the settings in the Visibility tab, and save.

Home Assistant frontend version : 20240306.0

Issue also found on the Android app version 2024.1.5-full

**Comment by Cardy165** [comment]
I am also experiencing issues with this. When I try to select the user who I wish to make the dashboard not visible too I click the switch and then after a second the switch moves back to visible. 

At no point does the save button become available to click it remains grey.

**Comment by silamon** [comment]
This issue was fixed in 2024.3.1 (frontend 20240307.0).

**Comment by karwosts** [comment]
Duplicate https://github.com/home-assistant/frontend/issues/20010
