### ISSUE TITLE
Unable to select/unselect which users should see a view in View Configuration

### ISSUE THREAD

**Issue by rrooggiieerr** [home-assistant/frontend#20053]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When trying to assign, or un-assign, a view to a user the select returns to unset/set

https://github.com/home-assistant/frontend/assets/18603534/b0e58943-43d8-4d9c-a336-3d15d9ff72ab

Tested and confirmed in both Chrome and Safari

### Describe the behavior you expected

I expect to be able to allow/disallow a user visibility to the view

### Steps to reproduce the issue

1. Go to your dashboard
2. Click _Edit Dashboard_
3. Click _Edit view_
4. Got to the _Visibility_ tab
5. Try to set/unset visibility for a user
...

### What version of Home Assistant Core has the issue?

2024.3.0

### What was the last working version of Home Assistant Core?

2024.2.x

### In which browser are you experiencing the issue with?

Google Chrome 122.0.6261.94

### Which operating system are you using to run this browser?

macOS Sonoma 14.3

### Javascript errors shown in your browser console/inspector

```txt
hui-dialog-edit-view.ts:475 Uncaught TypeError: Cannot assign to read only property 'visible' of object '#<Object>'
    at F.value (hui-dialog-edit-view.ts:475:20)
    at F.handleEvent (lit-html.ts:2018:29)
    at r (fire_event.ts:76:8)
    at t.value (hui-view-visibility-editor.ts:136:5)
    at F.handleEvent (lit-html.ts:2018:29)
    at HTMLDivElement.<anonymous> (mwc-switch-base.ts:121:14)
value @ hui-dialog-edit-view.ts:475
handleEvent @ lit-html.ts:2018
r @ fire_event.ts:76
value @ hui-view-visibility-editor.ts:136
handleEvent @ lit-html.ts:2018
(anonymous) @ mwc-switch-base.ts:121
```

**Comment by ildar170975** [comment]
There were issues already, search by "visibility".

**Comment by karwosts** [comment]
Duplicate https://github.com/home-assistant/frontend/issues/20010

Will be fixed in .1 release
