### ISSUE TITLE
Reboot -> "Retrying in -[MINUS] [NUMBER] Secounds | Wrong Language

### ISSUE THREAD

**Issue by MickLesk** [home-assistant/frontend#20052]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

1. When I restarted Home Assistant, it now displays: "Unable to connect to Home Assistant" - "Try again in -{NUMBER} seconds...

Here I mean the "-" (minus) 

2. Another phenomenon, I was sure that this was always there in German, can that be? Now it is at least displayed in English. 

### Describe the behavior you expected

- 1.) No more negatives, just the correct number
- 2.) The correct language should be displayed again

### Steps to reproduce the issue

1. Open HA
2. Go to Reboot Section
3. Press "Reboot system" 
...

### What version of Home Assistant Core has the issue?

2024.3.0

### What was the last working version of Home Assistant Core?

2024.2.X

### Additional information

<img width="337" alt="image" src="https://github.com/home-assistant/frontend/assets/47820557/81878588-725e-4dad-bd90-0b0d1f2a3d85">

Core 2024.3.0
Supervisor 2024.03.0
Operating System 12.1.rc1
Frontend 20240306.0

**Comment by jackwilsdon** [comment]
1. I'm not sure how you're seeing a negative number here - the init component reloads the page when the counter hits zero: https://github.com/home-assistant/frontend/blob/9e81055070da9b3b75513524d61bc3f965eb3fd1/src/layouts/ha-init-page.ts#L70-L73
What browser are you using? Do you see this on other browsers too?
2. It looks like this error page has always been in English: https://github.com/home-assistant/frontend/blob/9e81055070da9b3b75513524d61bc3f965eb3fd1/src/layouts/ha-init-page.ts#L17-L35
