### ISSUE TITLE
Tile card does not respect the translation of `select` entity states

### ISSUE THREAD

**Issue by bieniu** [home-assistant/frontend#20050]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

`Tile` card does not display state translations for the `select` entity, as other cards do, e.g. the `sensor` card. In this case, it's the `select activities` entity from the Logitech Harmony integration, which has the `power_off` state translated.

![obraz](https://github.com/home-assistant/frontend/assets/478555/4a056a76-8c3c-416b-bb4b-300d7e1de707)

### Describe the behavior you expected

`Tile` card should display translated states for the `select` entity like other cards.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2024.3.0

### In which browser are you experiencing the issue with?

Firefox 123.1

### Which operating system are you using to run this browser?

Windows 11

**Comment by piitaya** [comment]
Hello 👋
Can you provide your cards configuration? I can not reproduce your issue.

```yaml
cards:
  - type: entity
    entity: select.speed
  - type: tile
    entity: select.speed
```

![CleanShot 2024-03-12 at 11 20 49](https://github.com/home-assistant/frontend/assets/5878303/95787fa0-3c62-4c44-94a7-0c2c08d437fc)

**Comment by bieniu** [comment]
Oh stupid me, I was using the wrong entity (`remote.harmony` with attribute instead of `select.harmony`), sorry I wasted your time 🤦‍♂️
