### ISSUE TITLE
Changing the default dashboard is not saved

### ISSUE THREAD

**Issue by stefankoehne** [home-assistant/frontend#20064]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When changing the default dashboard in profile settings the change is not saved. After logging out and logging in again, the global default dashboard is adopted to profile settings.

### Describe the behavior you expected

Global default-dashboard can be selected at config/lovelace/dashboards. 
Personal default dashboard can individually be changed at /profile.
Last one is not working after re-login.

### Steps to reproduce the issue

1. Create two lovelace-dashboards.
2. Select first as global default at config/lovelace/dashboards.
3. Select second as user default dashboard at /profile.
4. Relogin
5. Finally you will be on the first global default

### What version of Home Assistant Core has the issue?

2024.3.0

### In which browser are you experiencing the issue with?

Chrome v122.0 // Fully Kiosk v1.55

### Which operating system are you using to run this browser?

Windows 10 Pro 22H2 // Android 13.0

**Comment by stefankoehne** [comment]
Addition: The dashboard, which is defined as default under /config/lovelace/dashboards, is not saved permanently as well and is reset after a logout/login

**Comment by stefankoehne** [comment]
Duplicate of https://github.com/home-assistant/frontend/issues/18626 ?

**Comment by karwosts** [comment]
This is as designed. Many of the settings in /profile are not per-user settings, but just settings for the local device, and are reset on logout. PR https://github.com/home-assistant/frontend/pull/20076 reorganizes this to make it a bit more explicit.

You can make a feature request if you'd like it to behave differently.
