### ISSUE TITLE
Theme isn't applied when page is (re)loading.  Is there a way to resolve this?

### ISSUE THREAD

**Issue by mph070770** [home-assistant/frontend#20073]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When a HA page is refreshed, and particularly if the page loading suffers from a slow connection, the home assistant "loading data" screen is shown in the default light colours. 

![image](https://github.com/home-assistant/frontend/assets/508539/d950e31c-1658-4e2c-af35-b564d41a8eff)

(sorry for the image quality, i'm showing the android studio emulator and it was difficult to grab the image).  The problem exists on standard browsers too.

The dark mode theme is only restored/shown when the page loads:

![image](https://github.com/home-assistant/frontend/assets/508539/caff22b4-2c30-4991-aadf-0e49838ba73b)

### Describe the behavior you expected

If possible, the "data loading" page is shown in the chosen theme.  If this is not possible (as that's included in the data loading), can the page be transparent or dark?

### Steps to reproduce the issue

1.  Just refresh a browser showing a HA page with a dark theme.  The screen will go white until the dark theme is restored.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.2.5

### In which browser are you experiencing the issue with?

all tried but currently Version 120.0.6099.199 (Official Build) (64-bit) on ubuntu

### Which operating system are you using to run this browser?

Ubuntu 20.04.6 LTS

**Comment by karwosts** [comment]
I don't know the answer to your question, but anecdotally my loading screen always appears in dark mode. 

I believe it is driven by your OS or browser preference setting?

**Comment by mph070770** [comment]
Thanks @karwosts.  I'm targeting Android 9 so that my app can run on Fire TV - and I can't see how I can force dark mode on that platform/API level.  I'm trying to force dark mode on the webview (but I think it was introduced into Android at Android 10) to see if this helps but not having much luck.  If the developers can reach out and explain how I might achieve this i.e. can the URL for HA force dark mode etc, it would be greatly appreciated.
