### ISSUE TITLE
View Visibility pops back on (sections view)

### ISSUE THREAD

**Issue by MDLefevere** [home-assistant/frontend#20070]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When i de-select all the users in the experimental sections view, so they can't see the page header it just pops back off. When it is off and i want to turn it on it just turns back off.

When i change it in the RAW editor with below it works.
```
visible:
  - user: USERID
```

### Describe the behavior you expected

When i turn the view for a specific person on it should stay on.
When i turn it off it should stay off.

### Steps to reproduce the issue

1. On top of the page create a new VIEW
2. Go to visibility
3. Turn on/off the view for some users. The button just goes back to it's original state.

### What version of Home Assistant Core has the issue?

2024.03.0

### In which browser are you experiencing the issue with?

Chrome 122.0.6261.112

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment]
Duplicate https://github.com/home-assistant/frontend/issues/20010
