### ISSUE TITLE
Tile card status content "last triggered" not in relative time

### ISSUE THREAD

**Issue by HenkSnavel** [home-assistant/frontend#20089]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

‘last triggered’ as the state content on a tile card only shows in absolute time.
![afbeelding](https://github.com/home-assistant/frontend/assets/3749382/21000edc-7f7b-4357-82cc-96090248e9f7)

### Describe the behavior you expected

I expected it would show as relative time. Same as "last changed"
![afbeelding](https://github.com/home-assistant/frontend/assets/3749382/2fa86985-e1d9-4829-949f-0a2da2c21278)

### Steps to reproduce the issue

Add last triggered to state content i tile card

### What version of Home Assistant Core has the issue?

2024.3.1

### In which browser are you experiencing the issue with?

Firefox 123.0.1 (64-bits)

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
id: 1710017409091
last_triggered: 2024-03-15T07:17:34.413408+00:00
mode: restart
current: 0
icon: mdi:cloud-percent-outline
friendly_name: Badkamer moeilijk
```

### Problem-relevant frontend configuration

```yaml
type: tile
entity: automation.badkamer_moeilijk
color: primary
state_content:
  - last_triggered
  - last-changed
```

**Comment by ildar170975** [comment]
Probably unrelated: 
shouldn’t this
```
state_content:
  - last_triggered
  - last-changed
 ```
be written as
```
  - last-triggered
```
?

**Comment by Nezz** [comment]
The attribute is called `last_triggered`
