### ISSUE TITLE
wrong translation for Area in UI editor

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#20090]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

<img width="600" alt="Scherm­afbeelding 2024-03-15 om 09 56 11" src="https://github.com/home-assistant/frontend/assets/33354141/c3386312-4813-4092-82c0-47663272ec8f">

### Describe the behavior you expected

Should probably be

'Ruimte bijwerken'

in stead of 'Gebied bijwerken'

always a bit tricky when translating system terminology... this one is especially particular, as Zones can also be translated to 'Gebied' in Dutch.

### Steps to reproduce the issue

1. nothing to do here
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.4.0.dev20240314

### Problem-relevant frontend configuration

```yaml
20240308.0.dev
```

**Comment by karwosts** [comment]
Can you make the change in Lokalise? We don't typically track individual language translation strings here, but direct users to the translation platform to make their suggestions.

**Comment by Mariusthvdb** [comment]
well, I can check in Localize for sure. But with all the changes in areas/floors/zones etc, I wanted to. are sure the correct concept here was Ruimte. before adding more confusion via Lokalize ;-)
Maybe ask one of the Dutch devs first?

**Comment by silamon** [comment]
I've changed it since the majority of the translations uses "ruimte". The term "ruimte" describes it better than "gebied", although the direct translation engine suggested "gebied".

**Comment by Mariusthvdb** [comment]
Thx. These translations can be very silly or inconsistent indeed. Might be right in themselves, but in context rather off sometimes.

**Comment by silamon** [comment]
Those translations are mostly added or changed over time and then done by different contributors. When you come across more translations, fix them as you find them. If there's nothing more to be done in this issue, please to close it.

**Comment by Mariusthvdb** [comment]
Nice thanks . Only wrong Dutch word here is Refereren ‘naar’ which should be Refereren ‘aan’

Or use ‘verwijzen naar’…

![IMG_4090](https://github.com/home-assistant/frontend/assets/33354141/058085e3-5aaf-48a9-97f6-dc9c72ba5731)

**Comment by Mariusthvdb** [comment]
sorry, I hadn't yet fixed that in Lokalise.
I just did and changed it to 'verwijzen naar', which the more commonly used phrase
