### ISSUE TITLE
Logbook not always correct info

### ISSUE THREAD

**Issue by jenniferlee1818** [home-assistant/frontend#20096]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Logbook is not consistently giving me the "triggered by" information.  I am using the rest api to get logbook data but the UI gives the same result.
![LOGBOOK](https://github.com/home-assistant/frontend/assets/44507767/b7d267d8-8fe2-49c1-991e-f7e680cc68f0)

### Describe the behavior you expected

Would like to always get the "triggered by" info if it is available.

### Steps to reproduce the issue

1.  Unlock lock entity from within home assistant.
![Screenshot from 2024-03-15 09-24-47](https://github.com/home-assistant/frontend/assets/44507767/d28e429a-cd35-46ca-a448-2e44aaba95ce)
2.  Observe logbook

### What version of Home Assistant Core has the issue?

2024.3.1

**Comment by karwosts** [comment]
Do you mean to say that the rest API is also missing the attributions? In that case this should probably be filed as a core issue, not frontend.

**Comment by jenniferlee1818** [comment]
Moved to core.
