### ISSUE TITLE
Energy dashboard battery charging graph is one hour off and shows false dischage

### ISSUE THREAD

**Issue by AndersHoglund** [home-assistant/frontend#20091]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Started EV charging at 23:00 and bar graph shows grid consumption correctly but battery charge bar is one hour off.
Also a false battery discharge is shown in the last hour bar. I have a discharge null-device. Distribution graph and total summery shows this correctly as 0kWh. 
New behaviour of core 2024.3.1,loooked back at an older charge event and now that has the same problem.

### Describe the behavior you expected

Battery charge bars in sync with consumption from grid impot or solr production.

### Steps to reproduce the issue

1. Start charging a battery at some time.
2. Take look at the energy dash.
3.
...

### What version of Home Assistant Core has the issue?

2024.3.1

### What was the last working version of Home Assistant Core?

2024.3.0

### In which browser are you experiencing the issue with?

Firefox and Avast 

### Which operating system are you using to run this browser?

Win11

### Additional information

Charge start and stop times.
![EV charging 230314 - 230315](https://github.com/home-assistant/frontend/assets/15121917/c1d61578-2ce0-4e70-8667-fcfc5d078018)

Energy dashboards.
<img width="763" alt="Screenshot 2024-03-15 at 10-12-36 Energy – Home Assistant" src="https://github.com/home-assistant/frontend/assets/15121917/31211997-b7f0-482d-bb84-aa1d46a889b1">

HA versions
![Screenshot 2024-03-15 at 10-47-11 Settings – Home Assistant](https://github.com/home-assistant/frontend/assets/15121917/34020a99-3426-4476-9747-722815ed9b15)

**Comment by karwosts** [comment]
Might help to attach your csv export of this energy panel (from the overflow menu).

Are your server/client on the same timezone settings?

**Comment by AndersHoglund** [comment]
OK, energy.csv attached. 
Double checked timezones, Win11 client on UTC+1 and HA on CET. Should be the same. All Energy bar graphs are correct in time, except the battery bars.
/A 
[energy.csv](https://github.com/home-assistant/frontend/files/14622989/energy.csv)

**Comment by karwosts** [comment]
You said the battery in sensor is one hour delayed and showed a plot of your EHQ _power_ sensor, but your battery in sensor is the EHQ _lifetime_energy_. Maybe see what the plot of that looks like?

**Comment by AndersHoglund** [comment]
Aah, you nailed it. Energy sensor is only updating by the hour, and then of course the graphs will be one hour late .
I showed the power sensor to see exactly when charging started and stopped. 
Still, the false discharge is an issue.
/A 
![Screenshot 2024-03-16 at 14-38-38 History – Home Assistant](https://github.com/home-assistant/frontend/assets/15121917/e27354fa-ff92-413a-a86b-5d43f8c93866)

**Comment by karwosts** [comment]
Yeah that's a little strange. I'm not too surprised that its a little broken given that you're inputting a mathematically impossible situation (energy going into the battery, but coming from nowhere). Maybe there's a way to sanitize that, not sure.

**Comment by karwosts** [comment]
Since you have the power sensor and it looks pretty detailed, you may want to consider not using the ev charger energy sensor and replace it with a riemann sum helper. That will update instantly as the power changes. 

Assuming there's no way to make it update more frequently.

**Comment by AndersHoglund** [comment]
Using a Riemann left-sum integral solves both issues. 
So the root cause is of course EV charger sensor delivering data too late and at too low rate. Indicating a discharge is the result of the need to balance out supplied energy vs charging energy and consumed energy.
Thanks for excellent support, Case closed.
/A 
![EV charging 230317 - 230318](https://github.com/home-assistant/frontend/assets/15121917/316a516b-6c71-49f2-9fe1-e2ae5fd18016)

**Comment by AndersHoglund** [comment]
Should also add that even though it works better with Riemann, there is the problem that constant power levels do not trigger any integral computation and that still causes some late energy updates. Known issue with a possible fix: https://github.com/home-assistant/core/pull/110685
/A
