### ISSUE TITLE
Tracking via companion app no longer working 

### ISSUE THREAD

**Issue by BartKoopmans-private** [home-assistant/frontend#20106]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have a problem with the companion app on 2 iphones running the latest versions of everything.
I can still access the HA instance using the companion app and the companion app does properly register the location on a second HA instance (automations still get triggered), but on the first HA instance it no longer updates the location.

It may have a link with the fact that I had a trial period running of the HA cloud and that ended, however not sure. Even after the trial ended I still managed to connect to the first HA instance using the external IP address.

on the second HA instance I never had a trial running and there the same app still works fine both for location tracking as operating the HA functionalities.

Running all latest updates on both HA instances.
Phone alredy restarted several times
HA also restarted several times.

any idea?

### Describe the behavior you expected

HA tracking the location of the companion app and triggering the needed automations

### Steps to reproduce the issue

no specific steps needed.

### What version of Home Assistant Core has the issue?

2024.3.1

### What was the last working version of Home Assistant Core?

2024.3.1 (as it is working fine on a second HA instance with the same version)

### In which browser are you experiencing the issue with?

not related

### Which operating system are you using to run this browser?

not related

**Comment by karwosts** [comment]
This isn't a frontend issue, it's either something in the app itself or core. 

If you need troubleshooting help, suggest checking out some of the dedicated help resources: 
https://www.home-assistant.io/help

But this is off topic for here.
