### ISSUE TITLE
Integrations names are not loaded after refreshing "Devices & Services" page

### ISSUE THREAD

**Issue by aso824** [home-assistant/frontend#20110]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After navigating to Settings » Devices & Services and refreshing the page (hitting F5), visible integrations won't have valid name - label will fallback to internal one. Example: `Home Assistant Supervisor` will became `hassio`. For 90% of tries it happens like that; for rest 10% it loads without problems. 

It's annoying mostly because integrations will have different order when bug happens.
Note: it does not happen if devtools panel is open.

### Describe the behavior you expected

Labels will be valid, as like on first page opening.

### Steps to reproduce the issue

1. Have at least one integration
2. Navigate to Settings and Devices & Services
3. Hit F5 and see if integrations names are bugged; if not, hit F5 again and again

### What version of Home Assistant Core has the issue?

2024.3.1

### In which browser are you experiencing the issue with?

Latest Chrome and Firefox

**Comment by karwosts** [comment]
I can see this sometimes but it is very rare for me, not 90% of the time but maybe 2-4% of the time the translations don't load properly. Must be some kind of race condition.
