### ISSUE TITLE
Missing icons when returning to the app after a while

### ISSUE THREAD

**Issue by ondoteam** [home-assistant/frontend#20111]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Please, check this closed issue: https://github.com/home-assistant/android/issues/4225 

### What version of Home Assistant Core has the issue?

2024.3.1

### In which browser are you experiencing the issue with?

Android App 2024.1.5-full

### Which operating system are you using to run this browser?

Android  14

**Comment by ondoteam** [comment]
Still present on 2024.3.5-full.

**Comment by mdino-gh** [comment]
I have the same issue in my PocoX5
Android 14
APP Version 2024.6.1-full
Core 2024.6.1
Frontend 20240605.0

**Comment by janowakps** [comment]
same on 2024.7.1
