### ISSUE TITLE
UI crashed once a pop-up box appeared/triggers

### ISSUE THREAD

**Issue by galant-ho** [home-assistant/frontend#20126]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

UI seemed to be disabled (crashed).  Mouse action on the UI is disabled including clicking and scrolling.

### Describe the behavior you expected

Navigating my Mushroom dashboard has been working fine until when some pop-up box triggers.

Was running the most recent core version 2024.2.5.
Updated to 2024.3.1 did not resolve the issue.
Dashboard was not recreated to use the 2024.3.1 drag-and-drop feature.

### Steps to reproduce the issue

1. Clicking an entity for more info (or clicking any hyperlink to trigger a box pop-up)
2. Mouse pointer is disabled
3. No mouse scrolling can be performed
4. Reload the UI to reset the navigation ability

### What version of Home Assistant Core has the issue?

2024.2.5

### In which browser are you experiencing the issue with?

Firefox 123.0.1 (64-bit)

### Which operating system are you using to run this browser?

Win 10

### Javascript errors shown in your browser console/inspector

```txt
Systems -> logs

Uncaught error from Firefox 123.0 on Windows 10 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "button-card-action-handler" has already been used with this registry 3900/</window.CustomElementRegistry.prototype.define (src/scoped-custom-element-registry.js:44:14) /hacsfiles/button-card/button-card.js:1:24357
Uncaught error from Firefox 123.0 on Windows 10 Error: Permission denied to access property "localName" element (src/blocking-elements.ts:372:56) sibling (src/blocking-elements.ts:289:57) newParents (src/blocking-elements.ts:202:29) element (src/blocking-elements.ts:147:24) push (mwc-dialog-base.ts:249:25) trapFocus (foundation.ts:166:21)
Uncaught error from Firefox 123.0 on Windows 10 TypeError: t[a] is undefined element (src/blocking-elements.ts:259:19) oldParents (src/blocking-elements.ts:183:38) remove (src/blocking-elements.ts:159:26) remove (mwc-dialog-base.ts:381:23) createCloseHeading (src/components/ha-dialog.ts:28:21) apply (src/scoped-custom-element-registry.js:262:44) remove (src/lit-html.ts:1651:32) _$AR (src/lit-html.ts:1376:15) _$AI (src/lit-html.ts:2183:7) i (src/lit-element.ts:165:30)
Uncaught error from Firefox 123.0 on Windows 10 TypeError: i is undefined siblingsToRestore (src/blocking-elements.ts:237:8) oldParents (src/blocking-elements.ts:216:34) element (src/blocking-elements.ts:147:24) push (mwc-dialog-base.ts:249:25) trapFocus (foundation.ts:166:21)
```

### Additional information

Mushroom dashboard v3.5.2
card-mod: v3.4.3
button-card: v4.1.2

**Comment by karwosts** [comment]
The errors you list seem to be coming from custom cards, which are not supported in this repository.

```
 /hacsfiles/button-card/button-card.js
 ```
 
 Suggest opening an issue there instead, unless you can reproduce this issue without using them.

**Comment by galant-ho** [comment]
Removed button-card on HACS.  Able to replicate the issue.

`Logger: frontend.js.latest.202403070
Source: components/system_log/__init__.py:306
First occurred: 13:59:08 (20 occurrences)
Last logged: 16:38:42

Uncaught error from Firefox 123.0 on Windows 10 TypeError: t[a] is undefined element (src/blocking-elements.ts:259:19) oldParents (src/blocking-elements.ts:183:38) remove (src/blocking-elements.ts:159:26) remove (mwc-dialog-base.ts:381:23) createCloseHeading (src/components/ha-dialog.ts:28:21) apply (src/scoped-custom-element-registry.js:262:44) mainWindow.history.pushState (src/dialogs/make-dialog-manager.ts:129:7)
Uncaught error from Firefox 123.0 on Windows 10 TypeError: i is undefined siblingsToRestore (src/blocking-elements.ts:241:10) oldParents (src/blocking-elements.ts:216:34) element (src/blocking-elements.ts:147:24) push (mwc-dialog-base.ts:249:25) trapFocus (foundation.ts:166:21)
Uncaught error from Firefox 123.0 on Windows 10 TypeError: i is undefined siblingsToRestore (src/blocking-elements.ts:241:10) oldParents (src/blocking-elements.ts:216:34) element (src/blocking-elements.ts:147:24) trapFocus (src/components/ha-drawer.ts:21:25) trapFocus (foundation.ts:39:17) opened (foundation.ts:157:11) handleTransitionEnd (mwc-drawer-base.ts:150:51)
Uncaught error from Firefox 123.0 on Windows 10 Error: Permission denied to access property "localName" element (src/blocking-elements.ts:372:56) sibling (src/blocking-elements.ts:289:57) newParents (src/blocking-elements.ts:202:29) element (src/blocking-elements.ts:147:24) trapFocus (src/components/ha-drawer.ts:21:25) trapFocus (foundation.ts:39:17) opened (foundation.ts:157:11) handleTransitionEnd (mwc-drawer-base.ts:150:51)
Uncaught error from Firefox 123.0 on Windows 10 Error: Permission denied to access property "localName" element (src/blocking-elements.ts:372:56) sibling (src/blocking-elements.ts:289:57) newParents (src/blocking-elements.ts:202:29) element (src/blocking-elements.ts:147:24) push (mwc-dialog-base.ts:249:25) trapFocus (foundation.ts:166:21)`

**Comment by karwosts** [comment]
Can you give the safe mode a try.

**Comment by galant-ho** [comment]
Restarted my HA running safe mode (my first time) received the following message.

`Home Assistant is running in safe mode, custom integrations and modules are not available. Restart Home Assistant to exit safe mode.`

I am not able to click any side menu items or links on the UI.

**Comment by karwosts** [comment]
> Restarted my HA running safe mode (my first time) received the following message.
> 
> `Home Assistant is running in safe mode, custom integrations and modules are not available. Restart Home Assistant to exit safe mode.`

Yes that's the expected behavior of safe mode.

> I am not able to click any side menu items or links on the UI.

No idea what's going on with this. 

I'll let this open for now as you seem to be having some kind of issue, but I don't really know what's going on with your system. Safe mode should be pretty robust as far as I know.
 
But be aware for the future we can't support custom card/resource related issues here.

**Comment by galant-ho** [comment]
Launched Google Chrome in Win 10 (Version 122.0.6261.129 (Official Build) (64-bit).
Run HA under safe mode.

I am able to navigate around seeing a limited of function such as Map, Logbook, History and the simple view under my Dashboard without any custom code.

Is it safe to say the experienced issue isolated to FF 123.0?

**Comment by galant-ho** [comment]
One day later.  Firefox rolled out a new version; 124.0 to Windows Desktop.
Firefox has been completed with the latest version update.
I am no longer able to produce this issue in my HA.
