### ISSUE TITLE
Helper-timer doesn't count down (Sections view)

### ISSUE THREAD

**Issue by Resin00** [home-assistant/frontend#20133]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

My timer helper doesn't show remaining time in sections dashboard. Functionality is unaffected in masonry layout, works fine. I'm using the entity card

### Describe the behavior you expected

I'm using the entity card (as I do in masonry dashboards) to display a timer but it won't countdown when "remaining" attribute is displayed. Once the timer is triggered it goes from idle to just showing the timer duration but never counting down. When I click details I Can see the timer counting down though

### Steps to reproduce the issue

1. Create a sections page of a dashboard 
2.add by entity 
3.add timer
4.add to dashboard
5.edit entity
6. Select Appearance >state content >remaining
7. Start timer and it will only show the set time not the remaining 

...

### What version of Home Assistant Core has the issue?

2024.3.1

### In which browser are you experiencing the issue with?

Mobile chrome 122.0.6261.119, ha companion app 2024.1.5, desktop chrome 

### Which operating system are you using to run this browser?

Android 14

**Comment by ildar170975** [comment]
< I'm using the entity card
< Select Appearance >state content >remaining

Are you sure you are using the Entity card?

**Comment by karwosts** [comment]
This is expected behavior. 

The remaining attribute on the timer does not count down when it runs, so if you display that attribute it will also not count down. 

Entities card has special code to display the countdown timer. If you want a live countdown, you can add your timer to an entities card. 

Anything beyond that is a new feature request.
