### ISSUE TITLE
Login Page in Loop with "Start Over" message

### ISSUE THREAD

**Issue by Ap0ph1s-W4ite** [home-assistant/frontend#20136]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I did a Cookie clean on my browser and tried to log into my Home Assistant but without any success.
Sometimes when I add my credentials the login page will refresh and clean everything but in other cases, the login continues and after the 2-factor authentication the page gives me a button "Start Over".
Tried with Firefox and the problem continues to be the same.

### Describe the behavior you expected

To do the login.

### Steps to reproduce the issue

1. Login Page
2. Add Username and Password
3. Add 2-factor code
4. _**Webpage gives me a "Start Over"**_

### What version of Home Assistant Core has the issue?

core-2024.3.0

### In which browser are you experiencing the issue with?

Brave v1.63.174

### Which operating system are you using to run this browser?

Windows 10 v22H2 (OS Build 19045.4170)

### Javascript errors shown in your browser console/inspector

```txt
auth.ts:69 
        
        
       POST https://<home-assystant-address>/auth/login_flow/36176d3625c8ed387753af2c09b65d07 400 (Bad Request)
d @ auth.ts:69
value @ ha-auth-flow.ts:371
handleEvent @ lit-html.ts:2018
```

### Additional information

I still have access to my Home Assistant Apps from iOS and Android. Didn't try to perform a logout for fear of losing access to my home assistant.
Tried to do the login on my iPhone and got the same error.

Edit:
Home Assistant Log related to Firefox login try.
`Logger: homeassistant.components.http.ban
Source: components/http/ban.py:128
integration: HTTP ([documentation](https://www.home-assistant.io/integrations/http), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+http%22))
First occurred: 13:31:27 (5 occurrences)
Last logged: 13:54:34

Login attempt or request with invalid authentication from 172.64.238.141 (172.64.238.141). Requested URL: '/auth/login_flow/c062490ff3f06742d7693183a29a138b'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36)
Login attempt or request with invalid authentication from 172.64.236.129 (172.64.236.129). Requested URL: '/auth/login_flow/6838c888d753d1fb79d05a75f2a7424c'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36)
Login attempt or request with invalid authentication from 172.64.236.129 (172.64.236.129). Requested URL: '/auth/login_flow/36176d3625c8ed387753af2c09b65d07'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36)
Login attempt or request with invalid authentication from 172.64.238.107 (172.64.238.107). Requested URL: '/auth/login_flow/b7cc7ffadc25a0c4d134663d175f213f'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0)
Login attempt or request with invalid authentication from 172.70.57.138 (172.70.57.138). Requested URL: '/auth/login_flow/a575a5af2d2e24342acafe3e98e350be'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0)`

**Comment by Ap0ph1s-W4ite** [comment]
Now got access with Brave but still getting the same error on Firefox.

**Comment by elrnv** [comment]
This is still an issue. The only way I got to work around this is by checking and unchecking "keep me logged in".
