### ISSUE TITLE
Vicare Issues/ Duplicate DHW entry/ Labeling issues with consumed Energy

### ISSUE THREAD

**Issue by jojoac** [home-assistant/frontend#20134]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I'm using the ViCare integration with my Heat Pump from Viessmann Vitocal 200-s (2023).
It is set up with a 2 heating circuits, one for the floor heating and a second for the radiator heating. 

First, I see duplicated information from the DHW. I tested both, and it looks like they are connected to the same API.
<img width="329" alt="image" src="https://github.com/home-assistant/frontend/assets/29631830/965babf2-5bcf-4b3e-a91d-133f9dc9b9f5">
BTW: It would be nice if the both heating circuits have each a unique Name. In the debug log you could see the number or the Name giving in the heating circuit.

In addition, the sensors are also not labelled with the heating circuit number. Like Circulation pump, Frost protection.

The Energy consumption is labelled as Gas, but it is a heat pump so it is electricity/ powered. :-)

Attached also the Dump
[config_entry-vicare-50b99cd1da2509b36cbbb2a9a597ab68-4.json](https://github.com/home-assistant/frontend/files/14649726/config_entry-vicare-50b99cd1da2509b36cbbb2a9a597ab68-4.json)

Thank you so much for the great work!!

### Describe the behavior you expected

It would be nice if the duplicate entry isn't there for the DHW.

Also, it would be nice if the heating circuits are labelled unique.  The same for all the circulation pumps, frost protection. 

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.3.1

### In which browser are you experiencing the issue with?

Chrome/ Edge/ firefox, safari

### Which operating system are you using to run this browser?

MacOS bis sure

**Comment by jojoac** [comment]
Thank you for the quick answer.

I'm wondering since the naming is coming from the integration why should this be a core issue. 
I know I'm new and maybe I misunderstood how this is working. So any clarification will help me to understand.
Thx

**Comment by karwosts** [comment]
The vicare integration is part of home-assistant/core. All the code for deciding what entities to create, how to name them, is a function of core home assistant.

Frontend just displays what core tells it to display, which in this case is multiple entities with the same name.
