### ISSUE TITLE
Unable to remove users from Visibilty when Sections is enabled

### ISSUE THREAD

**Issue by cloudbr34k84** [home-assistant/frontend#20148]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When you use the new sections feature, you can update the visibility. The option to save is not there, nore can you edit in yaml mode.

### Describe the behavior you expected

I expected you could remove the user from visibility

### Steps to reproduce the issue

Go to tab
to visibility sub tab
toggle user

### What version of Home Assistant Core has the issue?

2024.3.1

### What was the last working version of Home Assistant Core?

Its to do with the Section feature

**Comment by silamon** [comment]
Can you post a screenshot and check if there are any errors in the Javascript errors in the browser console/inspector?
