### ISSUE TITLE
Missed links between Device and Automation

### ISSUE THREAD

**Issue by toxig** [home-assistant/frontend#20149]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After update HA from version 2023.08 to version 2024.3.1 missed linked information about existing Automation in GUI of devices.

Misseв old automations and even if create new automation for device.

In safe mode HA the same problem.

<img width="524" alt="image" src="https://github.com/home-assistant/frontend/assets/377486/f19df0d2-983d-4a35-832c-31384d1ccea9">

### Describe the behavior you expected

When opened interface with detailed information of device, the Automations part filled with all existing automations where used this device (as it worked in older version of HA).

### Steps to reproduce the issue

1. Open any device detailed information
2. Create new automation for this device, using this device inside automation, and save it
3. Refresh page device detailed information
4. Automation block don't show existing automation for this device
...

### What version of Home Assistant Core has the issue?

core-2024.3.1

### What was the last working version of Home Assistant Core?

core-2023.08.xx

### In which browser are you experiencing the issue with?

chrome, safari

**Comment by karwosts** [comment]
This really isn't a frontend responsibility. 

When you open this page, frontend calls the backend api "search/related" with your device ID, and backend returns a list of automations which are related to that device. 

So you would need to ask in home-assistant/core why it's not finding the automation. 

You can reproduce in your browser console by running the following command (replace with your device id)

```
document.getElementsByTagName("home-assistant")[0].hass.callWS({type: "search/related", item_type: 'device', item_id: '5af3f3de75eb953ef32c5ac583424743'})
```

The response will contain the list of related automations, e.g. 
```
{
    "config_entry": [
        "7a3ef9eef23aa2490102211a3701767d"
    ],
    "entity": [
        "sensor.cpu_speed"
    ],
    "automation": [
        "automation.cpu_speed_freq"
    ]
}
```

**Comment by toxig** [comment]
Created issue for Core - https://github.com/home-assistant/core/issues/116626
