### ISSUE TITLE
Switching from a sections view to a non-sections view and vice versa while in editing mode ends editing mode

### ISSUE THREAD

**Issue by cstmth** [home-assistant/frontend#20141]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When you are currently editing a sections/non-sections view and then switch to the opposite type (so for example if I was editing a sections view and switched to a non-sections view), the editing mode is exited automatically. 

This might be connected to # because it also has to do with switching views and editing mode.

### Describe the behavior you expected

I would expect that the editing mode stays enabled no matter the type of view I switch to.

### Steps to reproduce the issue

1. Have to views, one of type 'sections' and one of any other type (for example 'masonry') 
2. Enter editing mode in either of them
3. Switch to the other view: editing mode stops automatically
...

### What version of Home Assistant Core has the issue?

core-2024.3.1

### In which browser are you experiencing the issue with?

Google Chrome 122.0.6261.128

### Which operating system are you using to run this browser?

Ubuntu 23.10 64-Bit

**Comment by piitaya** [comment]
Hi 👋
Can you share a video or more information? I'm unable to reproduce it.
