### ISSUE TITLE
The status of entities as buttons is not shown on the dashboard.

### ISSUE THREAD

**Issue by mcv93us** [home-assistant/frontend#20166]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After updating to the latest version of HA 2024.3.3 I noticed that the status of the entities was no longer shown.
Previously the active entity was shown like this:
![image1](https://github.com/home-assistant/frontend/assets/9490541/d87d7ad0-6a3b-4725-a432-35b3883ac702)
Now it's like this:
![image2](https://github.com/home-assistant/frontend/assets/9490541/d5bb0e73-1fa7-4b33-8bc4-62c9c4a5b20c)

### Describe the behavior you expected

I expect that when I turn a button on/off the icon showing the on/off status will color.

### Steps to reproduce the issue

1. Create a new tab and paste the code below.

type: entities
entities:
  - type: buttons
    entities:
      - entity: switch.desktop_pc
        name: Desktop PC On/Off
        icon: hass:power
      - entity: light.strip_led_tv
        name: Strip Led On/Off
        icon: hass:power
      - entity: switch.stereo_onoff
        name: Stereo On/Off
        icon: hass:power
      - entity: switch.tv_onoff
        name: TV On/Off
        icon: hass:power
show_header_toggle: false
state_color: true

### What version of Home Assistant Core has the issue?

2024.3.3

### What was the last working version of Home Assistant Core?

2024.2.5

### In which browser are you experiencing the issue with?

Google Chrome 123.0.6312.59 a 64 bit

### Which operating system are you using to run this browser?

Windows 10 Home 22H2 (19045.4170)

### State of relevant entities

```txt
Entities: switch.desktop_pc
State: on
Attributes:
icon: mdi:desktop-tower
friendly_name: Desktop PC
```

**Comment by ildar170975** [comment]
Duplicate https://github.com/home-assistant/frontend/issues/20022
Suggest to use search before posting.
