### ISSUE TITLE
Invalid Config for default_config and logs somehow

### ISSUE THREAD

**Issue by dnestico** [home-assistant/frontend#20173]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

This is the issue that randomly started appearing after this months HA update, it luckily doesn't prevent me from restarting HA but still trying to figure it out. 

```
The following integrations and platforms could not be set up:

logs ([Show logs](http://192.168.2.176:8123/config/logs?filter=logs))
default ([Show logs](http://192.168.2.176:8123/config/logs?filter=default))
Please check your config and [logs](http://192.168.2.176:8123/config/logs).
```

### Describe the behavior you expected

Those errors shouldn't appear. 

### Steps to reproduce the issue

1. I updated HA
2. The errors started appearing
...

### What version of Home Assistant Core has the issue?

2024.3.3

### What was the last working version of Home Assistant Core?

2024.2

### In which browser are you experiencing the issue with?

Arc Browser aka Chromium

### Which operating system are you using to run this browser?

macOS Sonoma 14.3.1

### Additional information

```
Logger: homeassistant.helpers.translation
Source: helpers/translation.py:286
First occurred: 2:24:37 PM (2 occurrences)
Last logged: 2:24:37 PM

Failed to load integration for translation: Integration 'logs' not found.
Failed to load integration for translation: Integration 'default' not found.
```

```
Logger: homeassistant.setup
Source: setup.py:266
First occurred: 2:24:41 PM (2 occurrences)
Last logged: 2:24:41 PM

Setup failed for 'logs': Integration not found.
Setup failed for 'default': Integration not found.
```

**Comment by karwosts** [comment]
Frontend is not responsible for processing of configuration.yaml.

If this was a bug it would be in home-assistant/core, but I suspect most likely you just have something invalid in your config, I would ask for help in one of the social channels (forums or discord).
