### ISSUE TITLE
Script field defaults are not used in frontend

### ISSUE THREAD

**Issue by thomluther** [home-assistant/frontend#20182]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When Field descriptions with selectors are used for service or blueprints, the default: value is typically pre-filled in the field when the field is selected (in case its optional).
However, the script fields in the More Info dialog does not seem to get populated with with the default value in case defaults are defined.

### Describe the behavior you expected

I think that is a usefull feature to allow defining defaults for the script input fields and reduce the fields that must be filled in by user.
This should work the same way as for blueprint and service forms

### Steps to reproduce the issue

1 script with field definition. UI also supports setting the default value:
fields:
  service:
    required: true
    name: Service
    default: anker_solix.update_solarbank_schedule
    selector:
      select:
        mode: dropdown
        options:
          - label: Set schedule
            value: anker_solix.set_solarbank_schedule
          - label: Update schedule
            value: anker_solix.update_solarbank_schedule

2. When creating a lovelace entity card with the script as entity, the More Info Dialog does not pre-fill the field with the default value

### What version of Home Assistant Core has the issue?

2024.3.3

### In which browser are you experiencing the issue with?

Firefox 124.0.1 (64-bit)

### Which operating system are you using to run this browser?

Windows 11

**Comment by zhudhjen** [comment]
I encountered the same issue about that the default values are not populated for script fields. Especially for numbers with sliders, it appears that the field is populated with value 0, but the field would be undefined when running.

What it looks like: 
![script_fields](https://github.com/home-assistant/frontend/assets/3236031/3e556e2f-505e-4872-8621-b76f8f7179a3)

The error message: 
```
Failed to call service script/announce_tts. Error rendering data template: UndefinedError: 'volume_adjustment' is undefined
```


[The script](https://pastebin.com/yknqtfaV) is here.
