### ISSUE TITLE
Scripts are loaded from raw.githubusercontent.com

### ISSUE THREAD

**Issue by koisama** [home-assistant/frontend#20181]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Sometimes a bunch of requests to raw.githubusercontend.com is made. This does not seem to break anything if cache is cleared and there is no internet access.

### Describe the behavior you expected

No requests to destinations other than local homeassistant server are made. Especially when it's not static images, but actual code.

### Steps to reproduce the issue

1. Open energy dashboard in HA
2. Switch to a different browser tab for about 10 minutes
3. Switch back to HA tab with energy dashboard, inspect network log in dev tools

### What version of Home Assistant Core has the issue?

2024.3.3

### In which browser are you experiencing the issue with?

Firefox 115.8.0esr, Firefox 123

### Which operating system are you using to run this browser?

Debian 12, macos 14.2.1

### Additional information

A screenshot of firefox network inspector:
![image](https://github.com/home-assistant/frontend/assets/15140993/14bf5f7f-0e61-49a0-9d63-10aad55348f1)

I was unable to reproduce the issue in chromium 122.0.6261.94 running on same linux machine, however it is present in different firefox branches on different platforms - linux amd64 and mac aarch64. I replicated the issue using a clean firefox profile on both platforms.
When blocking all external network requests, for example by setting an explicitly invalid proxy configuration, the requests silently fail and there is no visible issue.
There are additional requests to homeassistant server that result in 404, however they are present in both firefox and chromium and don't seem to cause any visible issue.

**Comment by steverep** [comment]
There are no scripts loaded from GitHub.  The source maps simply point to GitHub to load original source files for viewing in browser developer tools, otherwise you'd see the minified and mangled bundle code.

If there's an error being thrown for you in the console, please file a specific issue for it.
