### ISSUE TITLE
Zone setup not accepting float for Lat and Lon

### ISSUE THREAD

**Issue by corvus2606** [home-assistant/frontend#20201]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When trying to set up a new zone, the new zone page fails to validate the latitude and longitude values if they are not integers.

### Describe the behavior you expected

Latitude and Longitude should be decimal values to allow for fine tuning locations

### Steps to reproduce the issue

1. Open the map
2. Choose Edit
3. Select Add Zone
4. Change the Latitude or Longitude from the set home location, on validation it specifies: "Please enter a valid value, the nearest valid values are # and #"

### What version of Home Assistant Core has the issue?

2024.3.3

### In which browser are you experiencing the issue with?

Fireefox 124.0.1 (64-bit), Google Chrome 123.0.6312.59

### Which operating system are you using to run this browser?

Windows 11 23H2 22631.3296

### State of relevant entities

```txt
n/a
```

### Problem-relevant frontend configuration

```yaml
n/a
```

### Javascript errors shown in your browser console/inspector

```txt
n/a
```

**Comment by karwosts** [comment]
I think this will be fixed by #19994 if it merges. 

But just to be clear, this is not actually any functional problem, it just makes the textbox erroneously red. You can still submit and bypass the validation.
