### ISSUE TITLE
Energy Solar Graph forecast not correctly drawn when using multiple forecasts

### ISSUE THREAD

**Issue by N3rdix** [home-assistant/frontend#20202]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After **adding a second forecast.solar integration** with much lower values than the main one I observed strange graph values in the solar-graph-forecast card.
It seems the forecast values are not interpreted correctly in the graph although the legend shows the correct values. As indicated on the screenshot both markers on the line seem to be wrong:
![image](https://github.com/home-assistant/frontend/assets/70015952/913277bc-1865-487b-ad4c-6f124052716a)

This does only happen with 2 forecasts, if I disable the main one the new one displays correct values (screenshot from test-system without production data):
![image](https://github.com/home-assistant/frontend/assets/70015952/01148abe-d756-4dc4-bb9e-941e61f90030)

### Describe the behavior you expected

the dotted lines should be correctly drawn also in case of multiple forecasts

### Steps to reproduce the issue

Not sure if this prob1. add a forecast.solar integration with relatively low production values (mine is 860 Wp, Azimuth 219°, 25° angle)
2. go to the energy dashboard and check if the solar forecast dotted line meets the values of the integration

### What version of Home Assistant Core has the issue?

2024.3.3

### In which browser are you experiencing the issue with?

Chrome, Edge, companion App

### Which operating system are you using to run this browser?

Windows, iOS

**Comment by karwosts** [comment]
AFAIK these are intended to "stack" in the same way that multiple solar productions stack. That way the height of your forecast(s) match with the height of your stack of productions. 

Is that what you're trying to say is "wrong" about them, that you don't think that is correct behavior?

**Comment by N3rdix** [comment]
I was not aware the lines are also "stacked" as they seem to be 2 separate lines. Of course the sum of both is represented by the top line, but from my perspective it is wrong to treat the lines as a stock unless they are not visually stacked like the production.

The line (in my example with a value of 0.17 Wh) has a value on the y-axis of >1.6. If I would sum up the individual values based on their y-axis value it would be wrong.

In case this is really the intended behavior maybe we can make it obvious that multiple forecasts are stacked/summed up as well?

**Comment by karwosts** [comment]
Looks like this has been discussed a bit before, but both stale'd out without resolution. 

https://github.com/home-assistant/frontend/issues/16192
https://github.com/home-assistant/frontend/issues/15011

**Comment by N3rdix** [comment]
Oh right, didn't see them before. 

At least @bramkragten made a [proposal](https://github.com/home-assistant/frontend/issues/15011#issuecomment-1499055291) which would at least display correct values. Downside: it's just one line and hides the details of individual forecasts.

Maybe we can continue the discussion on how it should look like in future, I'm pretty sure more and more people will have multiple forecasts for multiple solar production systems as they get cheaper and more "main-stream" due to Plug & Play...
