### ISSUE TITLE
Clicking on the overflow menu of a category on the filter pane selects it and the data gets filtered 

### ISSUE THREAD

**Issue by jlpouffier** [home-assistant/frontend#20225]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Clicking on the overflow menu of a category on the filter pane selects it and the data gets filtered 

https://github.com/home-assistant/frontend/assets/5878296/d97c610b-eda3-4666-a47f-71f460e2df77

### Describe the behavior you expected

Actual behavior: The table is filtered by this category
Wanted behavior: The table is untouched and you can access the overflow menu

### Steps to reproduce the issue

1. Open the filter pane
2. Click on the overflow menu of a category 

### What version of Home Assistant Core has the issue?

2024.4.0b0

### What was the last working version of Home Assistant Core?

Not applicable: New feature

### In which browser are you experiencing the issue with?

Arc Version 1.35.0 (47750)

### Which operating system are you using to run this browser?

macOS 14.4 (23E214)

**Comment by piitaya** [comment]
Fixed with https://github.com/home-assistant/frontend/pull/20215
