### ISSUE TITLE
Missing Label filtering on /config/entities and /config/devices/dashboard panels

### ISSUE THREAD

**Issue by Mincka** [home-assistant/frontend#20229]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since one can add labels to entities and devices, it should be possible to filter on `/config/entities` and `/config/devices/dashboard` panels.
However, it does not show up on these panels, even if at least one entity and one device have a label assigned.
![image](https://github.com/home-assistant/frontend/assets/6184289/1c638296-959d-48d0-8f95-06b10506016f)

![image](https://github.com/home-assistant/frontend/assets/6184289/df225fce-a139-46db-801f-832a52b8a8af)

### Describe the behavior you expected

Show the labels filter, like it's done on `/config/automation/dashboard`
![image](https://github.com/home-assistant/frontend/assets/6184289/6d3e3831-e4bc-4103-99e9-3040a0079bd0)

### Steps to reproduce the issue

1. Go to `/config/entities` or `/config/devices/dashboard` panel
2. Open filters

### What version of Home Assistant Core has the issue?

2024.4.0b0

### In which browser are you experiencing the issue with?

Latest version of Edge and Firefox

### Which operating system are you using to run this browser?

Windows 11 23H2

**Comment by jlpouffier** [comment]
This is planned ;) 
It did not make the cut of the first release of this beta, the `b0`
It will be available in a future beta release, definitely before the actual 2024.4 release ;) 

Let's keep this bug open to avoid duplicate for now
