### ISSUE TITLE
When creating a label on the fly, the input text is not use to pre-fill the form

### ISSUE THREAD

**Issue by jlpouffier** [home-assistant/frontend#20226]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

How to reproduce
- Try to add a label
- Start typing on the label selector a new label title (Something that does not exist yet)
- The only option available is "Create a new label"
- Click on it

Wanted behavior: The input text used to filter the labels is used to prefill the form
Actual behavior: The form is empty

https://github.com/home-assistant/frontend/assets/5878296/2f9137f4-6798-4597-94e4-0d6c8590b78e

### Describe the behavior you expected

Wanted behavior: The input text used to filter the labels is used to prefill the form
Actual behavior: The form is empty

### Steps to reproduce the issue

- Try to add a label
- Start typing on the label selector a new label title (Something that does not exist yet)
- The only option available is "Create a new label"
- Click on it

### What version of Home Assistant Core has the issue?

2024.4.0b0

### What was the last working version of Home Assistant Core?

Not applicable: New feature

### In which browser are you experiencing the issue with?

Arc Version 1.35.0 (47750)

### Which operating system are you using to run this browser?

macOS 14.4 (23E214)

**Comment by Mincka** [comment]
I think this will be superseded by the suggested option here:
https://github.com/home-assistant/frontend/issues/20218

That seems to be a better approach from a UX perspective.
