### ISSUE TITLE
Removing the assignment of a category to a menu item

### ISSUE THREAD

**Issue by MikeGuest** [home-assistant/frontend#20228]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

While it's possible to remove an entire category, It does not appear to be possible to remove that category from a menu item (a specific script or automation) once it's been assigned

### Describe the behavior you expected

I would expect that if i press the 3-dot menu at the end of a (script, automation...) and select "Edit category", then press X to clear the text from the category selection box and then save, that the category assignment would be removed from the script or automation. 

### Steps to reproduce the issue

1. Assign a category to a script and observe that the script is in the correct category
2. Select the script, press 3-dot menu and select "Edit Category"
3. Select 'X' to clear the category, then hit save
4. Observe that the script is still in the previously selected category
...

### What version of Home Assistant Core has the issue?

core-2024.4.0b0

### What was the last working version of Home Assistant Core?

n/a. Feature not in previous versions

### In which browser are you experiencing the issue with?

Chrome 122.0.6261.112 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows

### State of relevant entities

```txt
n/a
```

### Problem-relevant frontend configuration

```yaml
n/a
```

### Javascript errors shown in your browser console/inspector

```txt
n/a
```

### Additional information

.

**Comment by frenck** [comment]
For clarity:

![CleanShot 2024-03-28 at 10 08 27@2x](https://github.com/home-assistant/frontend/assets/195327/a2ef0d47-b27f-4b15-a81b-79e33e9cf295)
