### ISSUE TITLE
Can't uncategorize an automation

### ISSUE THREAD

**Issue by TyzzyT** [home-assistant/frontend#20238]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Once I assigned an category to an automation, I'm unable to un-categorize this automation. I can click on _Edit category_, click the cross (which empties the Category field), and hit Save. But the automation is still assigned to the category. The only way to take the automation out of the category, is by deleting the category by going to the filters menu and delete the category from there.

### Describe the behavior you expected

I would expect the category to be removed when I click the X button and hit Save.

### Steps to reproduce the issue

1. Assign a category to an automation
2. Click on the menu icon (three dots) of the automation
3. Click on Edit category
4. Click on the X button
5. Click SAVE
6. Nothing has happened, the automation is still categorized

### What version of Home Assistant Core has the issue?

2024.4.0b0

### What was the last working version of Home Assistant Core?

never

### In which browser are you experiencing the issue with?

Brave 1.64.113 (Chromium 123.0.6312.86)

### Which operating system are you using to run this browser?

Windows 11 23H2

**Comment by piitaya** [comment]
Fixed with https://github.com/home-assistant/frontend/pull/20235
