### ISSUE TITLE
Empty state page isn't aligned center

### ISSUE THREAD

**Issue by matthiasdebaat** [home-assistant/frontend#20244]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

![CleanShot 2024-03-28 at 14 50 33@2x](https://github.com/home-assistant/frontend/assets/20203284/696910be-9f71-478d-8356-bc31640007a5)

### Describe the behavior you expected

Align it center

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2024.4.0b0

**Comment by jlpouffier** [comment]
@matthiasdebaa I am not questioning the the validity of this issue, I am just removing the milestone and this empty screen is here since 2024.1 ;)

**Comment by matthiasdebaat** [comment]
This bug is created since introducing labels. It was in the center before.
