### ISSUE TITLE
`last_reported` not shown on devtools > states after selecting entity

### ISSUE THREAD

**Issue by TheFes** [home-assistant/frontend#20249]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

2024.4 adds a `last_reported` property on the state object. This is not shown on devtools > states like `last_changed` and `last_update`

<img width="834" alt="image" src="https://github.com/home-assistant/frontend/assets/28803438/448cd68f-5241-453d-917b-03651be0d960">

### Describe the behavior you expected

`last_reported` to be added below `last_updated`

### Steps to reproduce the issue

1. Go to devtools > states and open an entity

### What version of Home Assistant Core has the issue?

2024.4.0b0

### What was the last working version of Home Assistant Core?

NA

### In which browser are you experiencing the issue with?

NA

### Which operating system are you using to run this browser?

NA

**Comment by frenck** [comment]
Oh right, that isn't send, as to large in traffic/volume.

**Comment by TheFes** [comment]
Can be closed!
