### ISSUE TITLE
Labels is missing in the overflow menu

### ISSUE THREAD

**Issue by matthiasdebaat** [home-assistant/frontend#20241]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Adding a label is a bit cumbersome compared to categories. 
![CleanShot 2024-03-28 at 14 44 43@2x](https://github.com/home-assistant/frontend/assets/20203284/14b9ff86-17bc-41ae-bf39-5356a432d317)

### Describe the behavior you expected

Have an Assign label option in the overflow menu like categories

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2024.4.0b0

**Comment by cloudbr34k84** [comment]
Just about to add this as well!

**Comment by bramkragten** [comment]
There is no labels menu, we can add a shortcut to the entity settings though, where the labels are set:
![CleanShot 2024-03-30 at 13 27 53@2x](https://github.com/home-assistant/frontend/assets/5662298/7c531a19-a168-4832-997c-91e5c50db91e)
