### ISSUE TITLE
Remove filter icon-button doesn't have hint text

### ISSUE THREAD

**Issue by matthiasdebaat** [home-assistant/frontend#20245]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On hover it doesn't show alt text
![CleanShot 2024-03-28 at 14 51 47@2x](https://github.com/home-assistant/frontend/assets/20203284/3a151433-be17-4741-8786-a7f99b78f274)

### Describe the behavior you expected

Add hint text.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2024.4.0b0

**Comment by silamon** [comment]
Most of the times, it will refuse to remove filter values. I'm not sure if it's really intended to remove filter values.
