### ISSUE TITLE
When there is no label, keep the same font size as before

### ISSUE THREAD

**Issue by matthiasdebaat** [home-assistant/frontend#20243]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

We changed the font size to make it easier to read when there are labels. When there are no labels we should keep the font size as before.
![CleanShot 2024-03-28 at 14 48 34@2x](https://github.com/home-assistant/frontend/assets/20203284/9d3deded-e95f-456d-a2ba-4c4f23201059)

### Describe the behavior you expected

That was 12px?

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2024.4.0b0

**Comment by piitaya** [comment]
If at least one item has a label, we increase the font-size? What is the only item that has the label is at the bottom of the list?
I would prefer to keep the size the same in all cases.

**Comment by matthiasdebaat** [comment]
I agree
