### ISSUE TITLE
Flickering integration startup messages after HA boot

### ISSUE THREAD

**Issue by TheFes** [home-assistant/frontend#20248]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On HA boot on the 2024.4.0b0 beta, the messages of starting integrations are flickering. See screen recording:

https://github.com/home-assistant/frontend/assets/28803438/0cb77fab-7a29-4099-a0c2-3749ae67b24e

### Describe the behavior you expected

A non flickering message

### Steps to reproduce the issue

1. Restart HA
2. Look at bottom left corner

### What version of Home Assistant Core has the issue?

2024.4.0b0

### What was the last working version of Home Assistant Core?

2024.3.3

### In which browser are you experiencing the issue with?

Google Chrome / Android Companion app

### Which operating system are you using to run this browser?

Windows 10 / Android

**Comment by silamon** [comment]
That will most likely be introduced by #19579 since the old polymer toasts used to stick a few seconds even though another toast should already be shown.

**Comment by jlpouffier** [comment]
Subscribing to this, I also see that ;) Thx for reporting it
