### ISSUE TITLE
`label_id` is not recognized by the UI in the automation editor. It is in the Dev Tools

### ISSUE THREAD

**Issue by jlpouffier** [home-assistant/frontend#20247]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In the automation editor (And Script editor too)
Adding a label automatically falls back the bloc into YAML mode.
In the Dev Tools, the target selector is already handling this case.

Video of both behavior:

https://github.com/home-assistant/frontend/assets/5878296/006b0d45-5fb1-4d74-b194-9cb120f9085d

### Describe the behavior you expected

I would expect the bloc to stay in "Visual mode" when using a label as target

### Steps to reproduce the issue

1. Add a label to any of your light (If not done already)
2. Go to Dev Tool > Service
3. Select the service `light.turn_on`
4. Select your label as target
5. Notice that the whole block stays in visual ode
6. Go to the automation editor
7. Add a Light > Turn On action bloc
8. Add your label as target
9. Notice the bloc fallback to YAML mode

### What version of Home Assistant Core has the issue?

2024.4.0b0

### What was the last working version of Home Assistant Core?

NOT APPLICABLE, NEW FEATURE

### In which browser are you experiencing the issue with?

ARC Version 1.35.0 (47750) Chromium Engine Version 123.0.6312.59

### Which operating system are you using to run this browser?

14.4 (23E214)

**Comment by frenck** [comment]
fixed in #20213
