### ISSUE TITLE
Colour of applied filters

### ISSUE THREAD

**Issue by BradleyFord** [home-assistant/frontend#20259]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In the 2024.04b1 I notice that the certain filters are applied by default (this is ok), and we can add additional filters as per our needs.

But what took me by surprise was that the applied filter counts were in orange, I immediately went to see what the problem was. Typically orange or red in HA denotes something that you need to action (ie errors, updates, etc). But then I found that these will always be showing up in orange as there is always something filtered by default.

![image](https://github.com/home-assistant/frontend/assets/322815/ad038122-5949-4a81-991d-4e747d2ba5fe)

### Describe the behavior you expected

As the application of filters is the normal and default state, I would assume that these should be shown in grey, white, etc. Basically a color that shows that this is normal, but ensures that you are aware that a filter is applied and how many.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.04b1

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

Windows 10

**Comment by piitaya** [comment]
It uses the secondary color (which is orange). I agree, it looks like a thing to pay attention. I open a PR to set the primary color.
