### ISSUE TITLE
Bug Report: Tibber Feature in Home Assistant Not Collecting Negative Power Values

### ISSUE THREAD

**Issue by justnx** [home-assistant/frontend#20260]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Currently, the Tibber integration in Home Assistant does not properly collect negative power values. When the power sensor receives a negative value, the integration fails to draw any data, rendering certain automations, such as calculations based on differences in power consumption, ineffective. It just draws 0 instead of the negative value.

### Describe the behavior you expected

Ideally, the Tibber integration should accurately collect and process both positive and negative power values without any disruption in data collection or functionality. Negative power values are essential for accurately monitoring energy consumption, especially in scenarios where energy is being generated or stored. For example in cases where more energy produced than consumed.

### Steps to reproduce the issue

1. Integrate Tibber with Home Assistant.
2. Monitor a power sensor that occasionally registers negative power values.
3. Observe that when negative values are encountered, the Tibber integration fails to collect any data beyond that point, affecting subsequent automations and data processing.

### What version of Home Assistant Core has the issue?

2024.3.3

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

any

### State of relevant entities

```txt
sensor.power_*
state_class: measurement
unit_of_measurement: W
device_class: power
state: make this negative instead 0
```

**Comment by karwosts** [comment]
This should have been filed in home-assistant/core, this is not a frontend issue.
