### ISSUE TITLE
Stack cards missing border radius in panel view again

### ISSUE THREAD

**Issue by jeremynoesen** [home-assistant/frontend#20282]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Stack cards border radius is no longer working again. #20216 was fixed in 20240329.0, but broke again in 20240329.1.

### Describe the behavior you expected

Same as #20216

### Steps to reproduce the issue

Same as #20216

### What version of Home Assistant Core has the issue?

core-2024.4.0b3

### What was the last working version of Home Assistant Core?

core-2024.4.0b2

### In which browser are you experiencing the issue with?

Nest Hub 2 Cast 3.71.396338

### Which operating system are you using to run this browser?

Fuchsia 16.20231130.3.59

**Comment by piitaya** [comment]
Hi 👋 
Can you share the yaml of your dashboard so I can reproduce it? 🙂

**Comment by jeremynoesen** [comment]
Upon further testing, it appears that this is not a homeassistant frontend issue, rather it is an issue with card mod. Stack cards display the border radius just fine, but within a mod card, the border radius does not apply. I will open an issue in the card mod repo with more information.

**Comment by jeremynoesen** [comment]
The card mod issue us [here](https://github.com/thomasloven/lovelace-card-mod/issues/369).
