### ISSUE TITLE
Wled Sound Reactive Update Firmware

### ISSUE THREAD

**Issue by Yoanf26** [home-assistant/frontend#20290]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have just installed WLED Sound Reactive on ESP32. It's work very well. But Home Assistant send a update firmware notification. But it's isn't for WLED Sound Reactive. Just for standard WLED. 

### Describe the behavior you expected

For resolve the problème with WLED - Sound Reactive. The good link is here : https://github.com/atuline/WLED

### Steps to reproduce the issue

1. Just Add WLED - Sound Reactive

### What version of Home Assistant Core has the issue?

2024.3.3

**Comment by spacegaier** [comment]
This does not sound like a frontend / GUI issue to me. If your issue still persists, please raise it here with more details: https://github.com/home-assistant/core/issues
