### ISSUE TITLE
Filtering missing from Unused Entities data table

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#20302]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

All data tables were updated with filtering support, but the "Unused Entities" table from dashboard edit mode appears to have been missed (screenshot below).

The new filtering and organization features would be very useful here, some example use cases:
- Show all unused entities belonging to "Office" area when creating your office view
- Show all unused entities belonging to "Sun" and "Pirate Weather" integrations when making your weather view
- Show all unused entities with "Security" label (motion sensors, alarms, sirens, cameras etc) when creating a security dashboard

### Describe the behavior you expected

Filter support like all other tables

### Steps to reproduce the issue

1. Lovelace dashboard → Edit mode → Unused entities 

### What version of Home Assistant Core has the issue?

core-2024.4.0b3

### In which browser are you experiencing the issue with?

Chrome version 116.0.5845.187

### Which operating system are you using to run this browser?

macOS Sonoma

### Additional information

<img width="761" alt="Screen Shot 2024-03-31 at 2 31 49 PM" src="https://github.com/home-assistant/frontend/assets/9065557/b03a594b-6c58-44b7-8d67-fc31afb57b2e">

**Comment by bramkragten** [comment]
This table is using a different component, as it is not a config page. Filtering can be added in the future, but is probably not in scope for this release.
