### ISSUE TITLE
Value 0 shown as 0.0 or as 0.00

### ISSUE THREAD

**Issue by iz8mbw** [home-assistant/frontend#20324]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hello.
I have noticed that a value of 0 (zero) can be returned as 0 or 0.0 or 0.00 depending on the entity.
So, depending on the entity, the quantity of zero decimals are shown.

![image](https://github.com/home-assistant/frontend/assets/3474082/f656fbbd-49b5-48e9-871b-41571035be7e)

Well, a 0 (zero) value should not have others 0 decimals, so shown 0.0 or 0.00 as 0.

Thanks.

### Describe the behavior you expected

If/when a value is `0` I expect to see `0` without any decimals.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.3.3

### In which browser are you experiencing the issue with?

Chrome 123

### Which operating system are you using to run this browser?

Windows 10

**Comment by ildar170975** [comment]
I would not use a custom card to demonstrate a possible issue.
Suggest to post screenshots from Dev tools & with stack Entities card or more-info windows.

**Comment by iz8mbw** [comment]
Other screenshot:

0.0:
![image](https://github.com/home-assistant/frontend/assets/3474082/66064ef2-7c43-4e2a-8795-3c8f37b60bdf)


0.:
![image](https://github.com/home-assistant/frontend/assets/3474082/f179cd06-dcc4-4923-9afd-2042520dc703)

**Comment by joshmcrty** [comment]
This is the intended behavior for numbers on the front end. If the raw entity state has zeros after the decimal, those are displayed in Lovelace cards,etc.

**Comment by iz8mbw** [comment]
What I can tell is if I reboot Home Assistant, when it starts I can read "0.0":
![image](https://github.com/home-assistant/frontend/assets/3474082/f666f3c4-f26b-480d-8a05-e9744b6bc291)

Then I power-on this switch and I can read the Power:
![image](https://github.com/home-assistant/frontend/assets/3474082/1a5d3575-6449-491c-8aaa-0491b1fa2d4e)

Then I power-off this switch and Power is now "0" and not more "0.0":
![image](https://github.com/home-assistant/frontend/assets/3474082/46882555-ddfe-4fbe-8505-45bd7390449b)

I don't think the "intended behavior" is to show a differ quantity of 0 as decimals.
