### ISSUE TITLE
No loading indicator for backups

### ISSUE THREAD

**Issue by uberchris2** [home-assistant/frontend#20334]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

My backups are stored in a network location with high latency (several seconds). When I access the Backups settings page, I am shown the (incorrect) message "You don't have any backups yet" until the backups list loads. There is no indication that HA is loading the list of backups. 

### Describe the behavior you expected

I would expect to see a loading spinner or message until HA has decided if there are actually backups to show.

### Steps to reproduce the issue

1. Configure HA to use a NAS as the primary backup storage
2. Open Backups settings page (Settings > System > Backups)
3. Observe the message "Yon don't have any backups yet." for several seconds, until the list of backups populates.

### What version of Home Assistant Core has the issue?

core-2024.3.3

**Comment by ma10as123** [comment]
i'm having the same issue, no backups appear, but backups work

**Comment by uberchris2** [comment]
This issue still persists on the latest version.

On Jul 20, 2024, at 6:02 AM, github-actions[bot] ***@***.***> wrote:

﻿

There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.
Please make sure to update to the latest Home Assistant version and check if that solves the issue. Let us know if that works for you by adding a comment 👍
This issue has now been marked as stale and will be closed if no further activity occurs. Thank you for your contributions.

**Comment by uberchris2** [comment]
This issue still persists on the latest version.
