### ISSUE TITLE
Add label button fails to label all selected entities

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#20356]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On the Entities page, I used the "Integrations" filter to show all the entities from my two car integrations and then selected all 64 entities. I then used the "Add label" button in the top right to assign these entities with a "Car" label. 

But as you can see in the below screenshot, it only assigned the label to 7 of the 64 entities. The 8th entity in this screenshot is disabled, and that's where it fails to proceed.

After unchecking that one disabled entity, the "Add label" button worked fine for all the rest.

<img width="1268" alt="Screenshot 2024-04-03 at 2 49 23 AM" src="https://github.com/home-assistant/frontend/assets/9065557/4f9f6e9b-6ed2-498c-9b58-4f586e6bc2b3">

### Describe the behavior you expected

I would expect the disabled entities to be skipped over and for it to label everything else it's able to. Basically in this example it should have labeled 63 of 64 entities, rather than 7 of 64.

### Steps to reproduce the issue

1. Entities panel
2. Filter by integration, one with disabled entities in the mix
3. Select all entities, then use add label button. 
4. It will fail at the first disabled entity and not proceed with labeling all the other ones that come after it.

### What version of Home Assistant Core has the issue?

core-2024.4.0b7

### In which browser are you experiencing the issue with?

Google Chrome 123.0.6312.87

### Which operating system are you using to run this browser?

macOS Sonoma 14.4.1

**Comment by SeanPM5** [comment]
Indeed, was able to assign the label on that disabled entity through the more info dialog. Just fails to be assigned when on the data table.

**Comment by bramkragten** [comment]
Can you share the error you received?
