### ISSUE TITLE
Integration Filters: Bayesian does not filter the list correctly

### ISSUE THREAD

**Issue by teskanoo** [home-assistant/frontend#20357]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I filter entities by integration - specifically Bayesian, the list does not filter correctly despite me having 65 Bayesian entities

This is most likely a Case-Sensitivity issue in the matching as the integration is named 'bayesian' (lowercase)

### Describe the behavior you expected

I Expect the integration filters to match regardless of case-sensitivity

### Steps to reproduce the issue

1. Go to the entities list (assuming you have Bayesian Sensors)
2. Type bayesian into the search bar to confirm you have Bayesian sensors
3. Filter by integration - Bayesian
4. Observe that all the entities that matched the search term have now vanished despite stating they belong to the 'bayesian' (lowercase) integration
...

### What version of Home Assistant Core has the issue?

Core 2024.4.0b7

### Which operating system are you using to run this browser?

Windows 11

**Comment by teskanoo** [comment]
Have seen the same behaviour with 
RESTful
Alert

**Comment by bramkragten** [comment]
This has nothing todo with case, it is probably because there are setup in YAML and don't have config entries?

**Comment by bramkragten** [comment]
How are those entities setup? I'm not able to reproduce, the integration for my bayesian sensor is `Binary sensor`
