### ISSUE TITLE
customize under homeassistant in configuration.yaml, seems to not check syntax, and icon does not work?

### ISSUE THREAD

**Issue by larhedse** [home-assistant/frontend#20364]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have the last couple of days spent some time with my curtain's (cover). And to change icon depending on state/position. In one of my tries to master (will most likely never happen, but I will happily try anyway) Home Assistant, I resorted to:

homeassistant:
  customize:

    cover.gardin_utsikten_inner:
      device_class: curtain
      icon: >
        {%- if this.attributes.curxent_position == 100 -%} mdi:curtains
        {%- elif this.attributes.current_position == 0 -%} mdi:curtains-closed
        {%- elif this.attributes.current_position == 50 -%} mdi:star
        {%- else -%} mdi:cloud-off-outline
        {%- endif -%}

Now there are TWO problems with the above:
1) Misspelled curxent_position - I have done this to prove that I get no error or syntax problem with this. It should of course been spelled: current_position - but I get no notification of any kind for this "error".
2) icon simply never works. No matter how or what I write there seem to never catch and present an icon. The code works under for example development tools perfectly. So that is not an issue - however an icon I do not get. What I am after is the mdi:star icon when my curtains are in what is call "My Position" (which is a position stored inside the Somfy Glydea motor that drives the curtains). I can get the icon to change by doing a "cover template" - but I can not get this to work in cuztom section in configuration.yaml.

### Describe the behavior you expected

I would like to be able to control which icon is presented depending on attribute "current_position" from the device.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.3.3

### In which browser are you experiencing the issue with?

Firefox and Edge

### Which operating system are you using to run this browser?

Windows and Android tablet/mobile phone

### State of relevant entities

```txt
current_position: 50
device_class: curtain
friendly_name: Gardin_Utsikten_Inner
supported_features: 15
icon: >
  {%- if this.attributes.curxent_position == 100 -%} mdi:curtains {%- elif
  this.attributes.current_position == 0 -%} mdi:curtains-closed {%- elif
  this.attributes.current_position == 50 -%} mdi:star {%- else -%}
  mdi:cloud-off-outline {%- endif -%}
```

### Problem-relevant frontend configuration

```yaml
homeassistant:
  customize:

    cover.gardin_utsikten_inner:
      device_class: curtain
      icon: >
        {%- if this.attributes.curxent_position == 100 -%} mdi:curtains
        {%- elif this.attributes.current_position == 0 -%} mdi:curtains-closed
        {%- elif this.attributes.current_position == 50 -%} mdi:star
        {%- else -%} mdi:cloud-off-outline
        {%- endif -%}
```

### Additional information

I have tried multiple "syntax" version of icon under homeassistant: -> customize: - including the none supported "templates:" which of course did not work. I seem to either simply don't understand what I might be doing wrong here, but for sure the syntax checking should in some way at least work. Now I seem to be able to write anything I like and nothing happens. That can not be sure. 

I also noted, from my searches (internet and the HA forum) that some people have tried this before me, none seem to succeeded so this might be something of a challenge with "icon" in general maybe?

This is not a show stopper at all - it would just be nice to get it working :-)

**Comment by larhedse** [comment]
Regarding safe mode checkbox: No I have not tried this - I can not for the love of Home Assistant see how that can be a part of this challenge, sorry.

**Comment by ildar170975** [comment]
Customize do not support jinja templates.

**Comment by larhedse** [comment]
Sorry if I posted wrong. I simply fail to separate everything. For ME this is front end: I can not get the correct icon to be presented. On the way I tested, as I wrote, a lot of different syntax - that was just one of them. Remove the templates code and this will STILL not work.

Oh and just to be perfectly clear: the "device_class: curtain" works, so I know that the cuztom part of the configuration.yaml file is read - it is just icon that does not work, with or without templates.

**Comment by ildar170975** [comment]
1. All posted examples are with templates. 
2. Not sure you can customize bot device class and icon. Omit device class and try with icon only. Imho there is no sense to define device class and icon simultaneously.

**Comment by larhedse** [comment]
1. Okay - Not sure how to interpret that, since I am not using the code word template(s) - but it is template code then I guess, but without the syntax word of template. Not crystal clear, but it is okay.
2. No difference. Just tested by removing device_class (and yes I do agree, no need to set this if I can get icon to work except that the device_class should always present the correct value of course, a curtain is a curtain and not a garage door) - no icon showing up - just "space".

**Comment by ildar170975** [comment]
1. I do not understand what you wrote here. I meant that in all your code examples you are using jinja templates in "customize" to define an icon. And I said earlier that "customize" does not support jinja templates.
2. Not clear what you tried to do since you did not provide a code. If you omitted "device_class" and still tried to use templates to define an icon - it will not work, see pt. 1.

How to customize an icon by using "customize":
```
homeassistant:
  customize:
    cover.test_garage_door:
      icon: mdi:car
```
which adds a customized icon:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/591534c1-8355-4eb0-86f4-dd06bc02f03f)

![изображение](https://github.com/home-assistant/frontend/assets/71872483/eee3f021-8aa5-43b0-a90f-c1f39bfcef74)

but HA still shows a "default" icon in Settings->Entities:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/9c2154f7-aca4-46d4-b64e-e8fbd28109a7)

which could be a consequence of some recent icon-related changes.

As you understand, there is no sense to "customize" an icon to have ONE static icon.
Icons should reflect at least "open" & "closed" states.
This is done by default by using a corr. device_class.
Also, it can be done explicitly by using an [`icon_template` option for template covers](https://www.home-assistant.io/integrations/cover.template/). Never did it myself though; at least it is described in Docs.
If you need to define an icon dynamically for not-template covers - try using custom plugins like Custom UI on your own risk.

**Comment by larhedse** [comment]
So then I can conclude that changing icon depending on an attribute is impossible thru customize, since well there is no way to code that simply (jinja or template or what-ever-one-might-call-it). As you your self wrote, there is no use for ONE and ONE icon only - I need to show 3+1 states (open, close, my position and offline).

No worries, I requested an icon possibility in command_line implementation of cover (the code most likely already exists since sensor and switch already have them, and the comments on that PR seems to fix that whenever it will be released), that I hope will cover this.

So then this can be closed, since well I would like to be able to do what I need to do for dynamic icon - but that is simply not supported, which also means no syntax checking occur. I'm alright with that, not the ideal solution of course, but it is fine.

Thanks for your support and help! Have a good day!

**Comment by ildar170975** [comment]
Alternatively, you may define icons/icon_colors dynamically on a particular frontend card by using custom plugins like mushrooms, card_mod etc.
