### ISSUE TITLE
Cannot reorder sidebar icons in 2024.4.0 in Chrome on Windows 11

### ISSUE THREAD

**Issue by ShadowRep** [home-assistant/frontend#20391]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I click "edit" in my user profile to change the order in the sidebar the icons start to wiggle but I cannot move them up or down with the mouse.

It does still work in the IOS-app.

### Describe the behavior you expected

I should be able to reorder the sidebar as before.

### Steps to reproduce the issue

Install 2024.4.0 and try to reorder in Chrome in Windows 11.

### What version of Home Assistant Core has the issue?

2024.4.0

### In which browser are you experiencing the issue with?

Google Chrome 123.0.6312.88

### Which operating system are you using to run this browser?

Windows 11 23H2

**Comment by ildar170975** [comment]
Confirm a bug.
I can reorder - but changes are lost after F5.

Chrome + Win10
2024.4.0

Initial:
![image](https://github.com/home-assistant/frontend/assets/71872483/4a357a34-aace-43b2-b97e-c21aa9a04aa4)

Start reordering:
![image](https://github.com/home-assistant/frontend/assets/71872483/698bee04-68ba-4fe8-9eac-8619d01fd303)

Save reordered:
![image](https://github.com/home-assistant/frontend/assets/71872483/f244df24-3cd5-4442-8b0d-8bffa1abdb03)

Refresh (F5):
![image](https://github.com/home-assistant/frontend/assets/71872483/78632ed9-5fa2-4c41-a6bb-610d107823b9)

**Comment by ShadowRep** [comment]
Seems to work now. Don't really know why.
