### ISSUE TITLE
List of labels truncated despite enough space

### ISSUE THREAD

**Issue by ste-fle** [home-assistant/frontend#20398]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since the public release yesterday, I added categories and labels to all my automations - some contain quite a few labels but the list is truncated even with massive amounts of space available: 

<img width="1751" alt="Bildschirmfoto 2024-04-04 um 09 24 21" src="https://github.com/home-assistant/frontend/assets/78681069/b1cc44cb-68fa-4175-a425-4c0348564b5b">

### Describe the behavior you expected

If enough space is available, all labels should be shown.

### Steps to reproduce the issue

1. Add at least 3 labels to an automation
2. Label list is truncated

### What version of Home Assistant Core has the issue?

2024.4.0

### In which browser are you experiencing the issue with?

Safari 17.4.1

### Which operating system are you using to run this browser?

macOS 14.4

**Comment by bramkragten** [comment]
Yes, this is a design choice for now, we always show max 2, we will explore more responsive ways to show the labels.
