### ISSUE TITLE
Helpers and Zones have wrong or missing icons on Entities page

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#20399]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Entities page shows missing or incorrect icons for helpers:

<img width="906" alt="Screenshot 2024-04-04 at 4 28 38 AM" src="https://github.com/home-assistant/frontend/assets/9065557/209865b3-601b-4f69-941d-b0b2b8db3823">

Helpers page shows the correct icons:

<img width="903" alt="Screenshot 2024-04-04 at 4 29 00 AM" src="https://github.com/home-assistant/frontend/assets/9065557/0fc4b454-dbd8-42c2-a020-77ee5bc93cc9">

Not pictured here for privacy reasons, but Zones also appear to be missing icons on the Entities page. No icons show for any zones...

**Edit**: upon further testing, it's showing the wrong icons in lots of places... below pics is of the ChargePoint custom integration. On the Entities page it shows only the default domain icons for sensor, switch, select etc rather than the actual icons.

<img width="768" alt="Missing-Wrong-Icons-Entities" src="https://github.com/home-assistant/frontend/assets/9065557/766032d3-23d1-4b42-b8d3-d46c7e878243">

these are the actual icons (Device page)
<img width="349" alt="Normal-Icons-Device-Page" src="https://github.com/home-assistant/frontend/assets/9065557/37da139b-6ec9-4392-91f3-525be1f36265">

### Describe the behavior you expected

Show correct icons

### Steps to reproduce the issue

1. Visit Settings -> Entities, enter "input_ " in the search field to filter helpers
2. Notice the missing and/or wrong icons
3. Now visit Settings -> Helpers and see the correct icons

### What version of Home Assistant Core has the issue?

2024.4.0

### In which browser are you experiencing the issue with?

Chrome 123.0.6312.87

### Which operating system are you using to run this browser?

macOS Sonoma

**Comment by ildar170975** [comment]
Is this issue a duplicate of old https://github.com/home-assistant/frontend/issues/19896 ?
