### ISSUE TITLE
Filters sidebar - Status/State filter elements overlaps with Integrations filter

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#20400]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

**Entities** page filtering, when scrolling the integrations filter... the status filter has a missing background or something and the elements overlap:
![IMG_0303](https://github.com/home-assistant/frontend/assets/9065557/a2abe47b-1fc4-4ffa-a67a-3ca0030a3efa)

Same issue occurs on **Devices** page, but with "State" filter.
<img width="265" alt="Devices Page" src="https://github.com/home-assistant/frontend/assets/9065557/2d553bd5-c4b4-40e2-80ac-d4581a1b4ee2">

### Describe the behavior you expected

No overlapping

### Steps to reproduce the issue

1. Settings -> Entities, open Filter sidebar, expand Integrations filter. Then scroll it and pay attention to the Status filter below.
2. Settings -> Devices too, open Filter sidebar, expand Integrations filter. Then scroll it and pay attention to the State filter below.

### What version of Home Assistant Core has the issue?

2024.4.0

### In which browser are you experiencing the issue with?

Chrome 123.0.6312.87

### Which operating system are you using to run this browser?

macOS Sonoma

**Comment by bramkragten** [comment]
This was already fixed, thanks for reporting!
