### ISSUE TITLE
Imperfection with white labels

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#20409]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

White-colored labels do not have an outline that makes them stand out from the background in light mode, if the theme is the default one.
Also in dark mode, the white label turns gray.

### Describe the behavior you expected

The white label should have a black outline that makes it stand out. Also in dark mode I expect it to stay white

### Steps to reproduce the issue

Set the light mode, create a white label, observe how the white of the label blends with the white color of the background.
Now return to dark mode, and you will see the label turn gray

### What version of Home Assistant Core has the issue?

2024.4.0

### In which browser are you experiencing the issue with?

Chrome 123.0.6312.86

**Comment by ildar170975** [comment]
Imho this is about a label of ANY color - if a theme uses a similar color.

**Comment by WRoss7** [comment]
The problem persists
