### ISSUE TITLE
"Automations" table: a default grouping by "Category" with no categories existing (same for "Helpers" & 'Scripts')

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#20423]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

By default the "Automations" table is grouped by "Category" - but there is no "category" created:

![image](https://github.com/home-assistant/frontend/assets/71872483/9340cffd-2801-4b43-8eb4-ad524ab3e4a3)

### Describe the behavior you expected

Since we hove no "category" created - do not group by it.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2024.4

### In which browser are you experiencing the issue with?

Chrome 123.0.6312.105

### Which operating system are you using to run this browser?

Win10x64

**Comment by ildar170975** [comment]
Same about other tables supporting "categories" - at least for "Scripts" & "Helpers" (not using scenes)

**Comment by bramkragten** [comment]
What is the issue here? If there are no categories it will do no grouping, so the result will be the same as what your are proposing?

**Comment by ildar170975** [comment]
I agree, 
No categories + grouping is ON by categories = grouping is OFF by categories

But it seems to be strange to have "grouping is ON by categories" as a default setting for tables when no categories exist.
I may speculate that the current logic is:
1. Let's set a default state for these tables as "grouping is ON by categories" (even if no categories present after upgrade to 2024.4).
2. When a user adds some categories and associates automations with categories - then the table will be grouped by categories (since the grouping is already ON).

I.e. you do not want to check for presence of categories and just switch grouping ON anyway.

So, the current logic gives same result - but imho it is rather strange to see "grouping ON" if no categories present.

**Comment by ildar170975** [comment]
not critical, closing
