### ISSUE TITLE
Notification Badge isn't cleared upon restart

### ISSUE THREAD

**Issue by dimaguy** [home-assistant/frontend#20425]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I restart home assistant with unread/non-dismissed notifications, the unread badge remains in place until I refresh the page even if notifications are cleared on the server side.
This happens on both mobile and browser

### Describe the behavior you expected

When home assistant is restarting, the frontend should reload the notifications section in order to clean the badge

### Steps to reproduce the issue

1. Restart home assistant with a non-dismissed notification
2. Look at the notifications button
3. Notice the badge is still there

### What version of Home Assistant Core has the issue?

core-2024.4.0

### In which browser are you experiencing the issue with?

Firefox 125.0b8

### Which operating system are you using to run this browser?

Windows 11

### Additional information

This issue affects both web and mobile app

**Comment by dimaguy** [comment]
This is still an issue

**Comment by karwosts** [comment]
Fixed this a couple releases back with #21405
