### ISSUE TITLE
Inconsistent menu expansion methods

### ISSUE THREAD

**Issue by Kfrard** [home-assistant/frontend#20435]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In the 2024.04 release, there are new categorization and labeling possibilities, along with a change in the automation view, entities, etc.
After clicking the three dots, the list of possibilities expands slowly. In previous "three dots" there is no such long animation.

https://github.com/home-assistant/frontend/assets/52238753/190dd787-c79e-46a8-bbaa-2a9f67574fb2

https://github.com/home-assistant/frontend/assets/52238753/b4bd353a-156b-4ecb-954c-71e77e09ec4f

### Describe the behavior you expected

Standardize the unfolding method (personally I prefer the older one, no need for animation)

### Steps to reproduce the issue

The new look of the drop-down menu can be seen on the /config/automation/dashboard page and the previous one, e.g. on /energy. The previous one is used throughout the HA.

### What version of Home Assistant Core has the issue?

2024.4.0

**Comment by bramkragten** [comment]
We are in the process of migrating, and not everything can be done at once.
