### ISSUE TITLE
PIN for adding AppleTV does not allow leading zero

### ISSUE THREAD

**Issue by MathieuMonsecour** [home-assistant/frontend#20433]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Adding AppleTV and providing PIN, when first number is zero it will autoremove the leading zero.

### Describe the behavior you expected

Leading zero won't be deleted.

### Steps to reproduce the issue

1. Start AppleTV that is not paired
2. Add new AppleTV as new device
3. HA asks for PIN displayed on screen of AppleTV
4. If first number is zero, then zero dissappears.
![Screenshot 2024-04-05 130019](https://github.com/home-assistant/frontend/assets/15620079/46387d1e-501a-4095-90d2-e25c1c97f451)

### What version of Home Assistant Core has the issue?

core-2024.4.0

### In which browser are you experiencing the issue with?

Firefox 124.0.2 (64-bit)

### Which operating system are you using to run this browser?

Windows 10

**Comment by bramkragten** [comment]
This is not a frontend issue but an issue with a specific integration. It should probably change the input to a text input with a pattern.
