### ISSUE TITLE
WEB Card back-arrow targets the iframe instead of the Home Assistant main window

### ISSUE THREAD

**Issue by Paul1865** [home-assistant/frontend#20459]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I added a subview, 1card panel with a fullsized web-page in it.
When the subview is opened, there is a back-arrow op top of it. 

![image](https://github.com/home-assistant/frontend/assets/17167055/41ad5061-ff3d-46b5-a79e-a332f9887b46)

Browser:
Pushing it goes back in the history of the iframe, but not on the main window, so I can never go back and have to click an item in the left-sidebar to get another view.

Companion App:
I don't have the left-sidebar there. The web-card fills the entire screen on my mobile, and pushing back does not go back to the calling view-window. Have to close HA and open it again.

To make it possible to navigate back- and forward in the iframe, extra arrows could be added in the iframe maybe. 
Or, make it a popup like view with a cross to close it.

Don't know if this is by design or or just a rare combination :) .

### Describe the behavior you expected

Pushing the back-arrow goes back in history in the main window.

### Steps to reproduce the issue

1. Create new view
2. 1 panel
3. Subview
4. Add Web Card
5. Save
6. Navigate some links in webcard
7. push browser back and forward buttons

The iframe will go back and forward in history.
...

### What version of Home Assistant Core has the issue?

2024.4.1

### What was the last working version of Home Assistant Core?

2024.4.1

### In which browser are you experiencing the issue with?

Brave  1.64.113 

### Which operating system are you using to run this browser?

Windows 10

**Comment by TheStarFlow** [comment]
i got the same problem,back-arrow should be link to preious View , not go back web history
