### ISSUE TITLE
Statistic card - when period is rolling window it only access the last 11-12 days of data

### ISSUE THREAD

**Issue by Landiss** [home-assistant/frontend#20469]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When setting up a statistics card to show data based on long statistics sensor, and using rolling window as period, it only seems to include data from the last 11-12 days. That is, setting the rolling window to anything over 12 days does not change the displayed result, even though there is older data for the sensor.

Here's my specific configuration:

```
type: statistic
stat_type: change
entity: sensor.fv_today_production
period:
  rolling_window:
    duration:
      days: 365
```

At the moment, this produces a result of 272.84 kWh, same as if I change days to 12. However, from the energy dashboard that uses the same sensor, I can see the actual value from the last 365 days should be around 7500 kWh.

The issue was reproduced and confirmed by a couple other people on the forums, including a mod:

https://community.home-assistant.io/t/statistics-card-rolling-window-long-duration/713258

### Describe the behavior you expected

The card should produce the result based on the full data for the sensor, stored as long statistics. Same as it does when a fixed period is selected.

### Steps to reproduce the issue

1. Have a sensor with long statisics data from more than 12 last days.
2. Create a statistics card with rolling window period of 12 days. Observe the result.
3. Change the rolling window period to 13 days or more. Observe the result has not changed.

### What version of Home Assistant Core has the issue?

2024.4.1

### In which browser are you experiencing the issue with?

Firefox 124.0.2 

### Which operating system are you using to run this browser?

Windows 11

### Additional information

There are some more details in the forum thread:
https://community.home-assistant.io/t/statistics-card-rolling-window-long-duration/713258

**Comment by karwosts** [comment]
Might be a core issue. Frontend doesn't compute this number, it sends the request to backend. See I get same response for sending days:14 and days:15. 

![image](https://github.com/home-assistant/frontend/assets/32912880/feced35a-41b5-4abb-a864-086537baa099)

**Comment by karwosts** [comment]
I would suggest open an issue in home assistant core, and for integration use: https://www.home-assistant.io/integrations/recorder/

**Comment by Landiss** [comment]
Thank you @karwosts . I created the issue in core and will close this one.
