### ISSUE TITLE
Live Camera Streams Often Fall Behind

### ISSUE THREAD

**Issue by AngellusMortis** [home-assistant/frontend#20488]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The video player for live camera streams often falls behind if there is an interruption to video playback. Interruption to video playback can include (but not limited to):

* network issues
* switching to another tab and HA losing priority (Web browsers)
* switching to another app and HA losing priority (mobile apps)

### Describe the behavior you expected

Video players should detect and automatically correct when they are lagging behind more than expected. 

### Steps to reproduce the issue

1. Add picture entity card to any dashboard pointing to a camera with a live video stream, ideally one with a timestamp for comparison
2. Load the dashboard and watch the video stream for a few seconds. Note how many seconds the stream is behind
3. (on Web) Switch to another tab and then go to another application. (on mobile) Switch to another app.
4. Wait about 30 seconds
5. Go back to HA dashboard, camera should resume where it was when it was suspended/de-prioritized because it was put in the background. 

### What version of Home Assistant Core has the issue?

core-2024.4.2

### What was the last working version of Home Assistant Core?

Never

### In which browser are you experiencing the issue with?

Edge/Chrome/Firefox/everything

### Which operating system are you using to run this browser?

Windows 10/Windows 11/Android 12-14

### Additional information

This has been a long-standing Home Assistant frontend issue. The video player is not able to self-heal and realize when it has fallen behind in playback. This is often reported as [video delay](https://community.home-assistant.io/search?expanded=true&q=video%20delay), but this is _not_ related to the HLS video delay issue that causes a 15-30 second video delay. You can easily reproducible it with a LL-HLS setup that starts with an initial 1-2 second video delay that can easily become 30 seconds or even a few minutes. 

The only way to "solve" the delay is to reload the page. Which for mobile apps is not really possible. The video player itself should be able to auto-correct these delays.

**Comment by pedro639** [comment]
Yup, still a thing
