### ISSUE TITLE
MQTT HVAC is always publishing an old temperature value

### ISSUE THREAD

**Issue by jagko** [home-assistant/frontend#20498]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The climate entity of MQTT HVAC is publishing the old ("coming from") temperature, not the new target temperature.

### Describe the behavior you expected

Expect, the published temperature is equal state attribute "temperature"

### Steps to reproduce the issue

1. generate a climate entity
2.set a temperature_command_topic e.g. temperature_command_topic: "cmnd/zigbeeSchule/ZbSend"
3.set a temperature_command_template e.g. temperature_command_template: '{"device":"0x30A2","write":{"OccupiedHeatingSetpoint":{{state_attr("climate.schule_probenraum","temperature")|float}}}}'
4. try
...

### What version of Home Assistant Core has the issue?

2024.4.2

### What was the last working version of Home Assistant Core?

dont know

### In which browser are you experiencing the issue with?

all

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
Are you sure you meant this to be a frontend issue? Frontend doesn't 'publish' anything, unless I'm misunderstanding.

**Comment by jagko** [comment]
closed
