### ISSUE TITLE
Dashboard keeps reloading (like it has hiccups)

### ISSUE THREAD

**Issue by hmmbob** [home-assistant/frontend#20490]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On HA2024.4.2, ~~the energy dashboard~~ my dashboards keeps reloading 
The Energy dashboard throws lots of errors in console (see below).
The hiccups also notably raise the CPU cycles used by Chrome.

### Describe the behavior you expected

A nice and stable dashboard 😄 

### Steps to reproduce the issue

1. Navigate to Dashboard
2. Observe

### What version of Home Assistant Core has the issue?

core-2024.4.2

### What was the last working version of Home Assistant Core?

core-2024.4.0 (I skipped .1 initially, but test now indicate the issue is in .1 as well)

### In which browser are you experiencing the issue with?

Chrome v123.0

### Which operating system are you using to run this browser?

Win11

### Javascript errors shown in your browser console/inspector

Some of the errors in the console when on Energy dashboard:
![image](https://github.com/home-assistant/frontend/assets/33529490/73f6d9fd-d131-4aa7-840f-ddf9b87dea96)
![image](https://github.com/home-assistant/frontend/assets/33529490/28147790-2eff-45b2-b102-1e834c1dbf7f)
(blacked out info is my external URL to HA)

### Additional information

Video of the issue here: (note: i'm not doing anything to reload the dash or so, it all happens by itself)
https://github.com/home-assistant/frontend/assets/33529490/3418c3b6-0e5b-472f-8250-1474b4817de1

edit: now also my main dashboard has hiccups:
https://github.com/home-assistant/frontend/assets/33529490/e9b468b0-ed31-494f-8ca8-d13cecd5f9e6

- It does not happen on the settings screen, the developer tools, the media browser. 
- It does also occur inside the HA Android companion app
- Changing the theme to standard Home Assistant makes no difference

**Comment by hmmbob** [comment]
Whut, rollback to 2024.4.0 now also shows the hiccups there......

**Comment by silamon** [comment]
You may want to try out [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) as suggested in the checklist.

**Comment by hmmbob** [comment]
OK, it wasn't HA.... 

With Traefik v2.11+ the WSS connection seems to get reset every second or so, rolling back Traefik to v2.10.7 solved the issue.

**Comment by hmmbob** [comment]
Confirmed that Traefik is the culprit: https://github.com/traefik/traefik/issues/10589

**Comment by hsmade** [comment]
Traefik issue https://github.com/traefik/traefik/issues/10598 is a follow up on this issue. 
It seems the next version (2.11.2) should fix this.
