### ISSUE TITLE
Helper group precision option gone after HA restart

### ISSUE THREAD

**Issue by Arn0uDz** [home-assistant/frontend#20503]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I made a custom helper group adding the values of 4 sensors and i'm able to set the precision, but after a restart of HA this option is lost. I have to make a change in the group and save the settings and the precision option comes back. This happens after every restart of HA.

### Describe the behavior you expected

I expect the precision option to stay, even after a restart. 

### Steps to reproduce the issue

1. Start HA
2. Precision option is gone
3. Adjust group options and change something for example: "Ignore non-numeric" to on or off and save.
4. Precision option is back until next restart and is missing again.
...

### What version of Home Assistant Core has the issue?

2024.4.2

### In which browser are you experiencing the issue with?

Chrome and Android tablets

### Additional information

After a HA restart:
![image](https://github.com/home-assistant/frontend/assets/78048762/a44851e5-111f-46d8-8dd6-8dc5fa81d975)

If I make a change in the group, for example switch the "ignore non-numeric" on or off and save:
![image](https://github.com/home-assistant/frontend/assets/78048762/cc2e9935-e55e-44bb-af57-de628edde6c1)

Notice that the precision option in the 3rd row reappears and works again.

State of the entities:
![image](https://github.com/home-assistant/frontend/assets/78048762/0a7c02bc-c12e-4ead-867a-1f621f950eaa)
![image](https://github.com/home-assistant/frontend/assets/78048762/6a928c39-0eeb-44f1-9a24-f41da12c9eff)

My assumption is that the last entity "sensor.pvminrl3" is the root cause of this, since that is the only custom one manually configured in my configuration.yaml

Also noticing this in the startup log: 
```
Logger: homeassistant.components.group.sensor
Source: components/group/sensor.py:382
integration: Group (documentation, issues)
First occurred: 2:28:23 PM (1 occurrences)
Last logged: 2:28:23 PM

Unable to use state. Only numerical states are supported, entity sensor.pvminrl3 with value unknown excluded from calculation in sensor.huidigvermogenbruto
```

**Comment by karwosts** [comment]
When you boot HA and the precision option is missing, can you check what is the state and attributes of `sensor.huidigvermogenbruto` ?

Precision selector should be shown for any sensor that has a numeric device class, a state class, or a unit_of_measurement. Perhaps something is breaking the sensor that those are not getting set correctly on boot.

**Comment by Arn0uDz** [comment]
@karwosts 
Seems to already been fixed. I deleted the helper and re-created it and it works now even after a restart. The options for this helper are different now too. I don't have the Hide members option anymore. Not sure what changed.

**Comment by gsportelli** [comment]
I have a similar problem with HA 2024.5.5, but after restart also the "ignore non numeric" option must be cleared and set again to have a numeric sensor.
