### ISSUE TITLE
Pointed Brackets at new Filter Section have wrong orientation

### ISSUE THREAD

**Issue by mkcologne** [home-assistant/frontend#20514]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Not really an issue. More a cosmetic/design thing.

If you open the new filter u think everything is empty, because u think the menu is open, because the Pointed-Bracket points downwards.
Usually those menus point to the right if they are folded in and downwards if folded out.

![image](https://github.com/home-assistant/frontend/assets/25418164/82d16d11-ca93-4ba8-a3f7-abdcb0d8cc5c)

Looks empty!

### Describe the behavior you expected

Should face to the right if folded and down if unfolded.

### Steps to reproduce the issue

...

### What version of Home Assistant Core has the issue?

2024.4.3

**Comment by matthiasdebaat** [comment]
We follow Material guidelines and they have the following:
- Chevron pointing down is closed
- Chevron pointing up is open

Here is how Angular implemented it: https://material.angular.io/components/expansion/overview
