### ISSUE TITLE
Update of Supervisor

### ISSUE THREAD

**Issue by Browncd2000** [home-assistant/frontend#20528]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When trying to update supervisor (tried in safe made and also from terminal) I get the error message below:

Error: Update of Supervisor failed: Can't install ghcr. io/home-assistant/aarch64-hassio-supervisor: 2024 .04.0: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/home-assistant/aarch64-hassio-supervisor: 2024.04.0/json: Not Found ("No such image: gher. io/home-assistant/aarch64-hassio-supervisor:
2024.04.0"')

Would appreciate some help to resolve what this means and what I need to do

thanks

David

### Describe the behavior you expected

update of Supervisor from 2024.03.0 to 2024.04.0

### Steps to reproduce the issue

1. settings install update
2. terminal ha supervisor update
3.
...

### What version of Home Assistant Core has the issue?

2024.3.1

### What was the last working version of Home Assistant Core?

2024.3.1

### In which browser are you experiencing the issue with?

Safari 17.4.1 

### Which operating system are you using to run this browser?

MacOS 14.1.1

**Comment by karwosts** [comment]
This is not a support forum for supervisor issues. Suggest try one of the community support options listed at https://www.home-assistant.io/help
