### ISSUE TITLE
Linkage lines between zigbee nodes in Zigbee2MQTT's "Map"

### ISSUE THREAD

**Issue by E30M20B20** [home-assistant/frontend#20532]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I think there is an error with lines when the map of my network is drawing. If I uncheck "AsASibling", the net looks as two independent segments. There is missing an uplink line from thermostat to coordinator or to one of routers. 
![изображение](https://github.com/home-assistant/frontend/assets/167162523/4e2f6e84-d585-467a-9cdc-dae094c6fa23)

### Describe the behavior you expected

Anyway, two independent segments must never be.

### Steps to reproduce the issue

1.This is ordinary drawing of my network's map. No need any additional doings.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.4.3

### What was the last working version of Home Assistant Core?

?

### In which browser are you experiencing the issue with?

Firefox 124.0.2

### Which operating system are you using to run this browser?

Win10Pro 22H2

**Comment by E30M20B20** [comment]
The network has been visually broken when I added there thermostat, so I think a problem is somewhere around this thermostat.

**Comment by silamon** [comment]
That isn't something that is maintained in this repository. Open an issue at https://github.com/Koenkk/zigbee2mqtt.
