### ISSUE TITLE
Media Browser button not disabled on unavailable media players in more info dialog

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#20531]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

More info dialog for media players that are in unavailable state should disable the media browser button since it'll always fail.

Currently it lets you click it and _then_ shows you an error dialog, repeating information already shown on the more info dialog itself (that media player is unavailable). Feels like odd behavior when the user can just be prevented from clicking a non-functional button in the first place.

<img width="589" alt="Screen Shot 2024-04-15 at 10 30 00 PM" src="https://github.com/home-assistant/frontend/assets/9065557/fb2b23b1-a2ef-48d9-9020-75e19bb07fb8">

<img width="415" alt="Screen Shot 2024-04-15 at 10 30 08 PM" src="https://github.com/home-assistant/frontend/assets/9065557/bcf784cb-7175-4118-841e-79f421d4e4e8">

### Describe the behavior you expected

Media browser button should be disabled when media player entity is in unavailable state

### Steps to reproduce the issue

1. Have an unavailable entity (easy to reproduce with Plex clients)
2. open the more info of that unavailable media player, and then click "Browse Media" button (which will of course not work)
3. Get an error dialog 

### What version of Home Assistant Core has the issue?

2024.4.3

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

macOS Sonoma

**Comment by spacegaier** [comment]
I will push a PR in a minute that however goes one step further: It hides the button completely if the media player is not available. The same is already done for all other UI elements in the more-info dialog (such as source selection, volume buttons, ...) if the media player is not available.
