### ISSUE TITLE
Cannot read properties of undefined (reading 'click')

### ISSUE THREAD

**Issue by chemelli74** [home-assistant/frontend#20588]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I often get this log line when clicking on the update platform.

```
2024-04-22 18:47:32.257 ERROR (MainThread) [frontend.js.latest.202404042] Uncaught error from Edge 123.0.0.0 on Windows 10
TypeError: Cannot read properties of undefined (reading 'click')
click (node_modules/@polymer/iron-menu-behavior/iron-menubar-behavior.js:35:21)
call (node_modules/@polymer/iron-a11y-keys-behavior/iron-a11y-keys-behavior.js:479:22)
_triggerKeyHandler (node_modules/@polymer/iron-a11y-keys-behavior/iron-a11y-keys-behavior.js:465:13)
```

### Describe the behavior you expected

No error logged and a immediate start of the update.

### Steps to reproduce the issue

1. Try to click "install" on an update entity 

### What version of Home Assistant Core has the issue?

2024.4.3

### What was the last working version of Home Assistant Core?

-

### In which browser are you experiencing the issue with?

Edge Versione 123.0.2420.97 (Build ufficiale) (64 bit)

### Which operating system are you using to run this browser?

Windows 11 - 22H2 [Versione 10.0.22621.3296]

**Comment by karwosts** [comment]
I'm not really seeing any issue with updates. I've tried a few and they seem normal.

Maybe a little more information would help?

Is it some particular entity you're trying to update, or any of them are broken? Do you mean you click the `install` button in the more-info popup? Maybe attach a screenshot just for clarity?

**Comment by chemelli74** [comment]
Here the screenshot of the install I'm refering to:

![image](https://github.com/home-assistant/frontend/assets/57354320/18001fab-19bc-4db9-bc1a-3c94337070f3)

I updated to 2024.4.4 and now at at least the 2 Shelly still liste din the update, works fine.

**Comment by bramkragten** [comment]
The error is from a polymer element, there is no polymer element in the update dialog. Do you custom stuff maybe?

Since you mention it works fine now, I'm gonna close.
