### ISSUE TITLE
Constant Reconfiguration needed (log in with user and pass) and also Authentication expired 

### ISSUE THREAD

**Issue by thegeneraluse** [home-assistant/frontend#20592]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The HACS integration provides no problems at all.
The Official one has 2 issues
Under Integration is shows up all the devices (TP100, TP300) - 15x TP100 and 1x TP300 and i have to click reconfigure, enter username and password on one of them and then they all reconfigure. If HA is restarted they always show up, but now its happening more frequently, even without restarts. Logged in local or via nabucasa

The other issues is even when hitting reconfigure and entering user and pass, when going to Settings i still see all 16 repairs needed for the official tapo devices and they say "Authentication expired". When clicking on them i get the error
"Config flow could not be loaded: {"message":"Invalid flow specified"}"

### Describe the behavior you expected

not constantly need to be reconfigured... the HACS one works perfect. 

### Steps to reproduce the issue

1. Anytime HA is restarted
2. Each day i have to click reconfigure and log in using the app credentials 
3. The Authentication error i cant fix, just sits there under settings
...

### What version of Home Assistant Core has the issue?

2024.3.1

### In which browser are you experiencing the issue with?

Brave, android phone, Opera, more than one pc and mobile

### Which operating system are you using to run this browser?

Windows 11, Android (latest pixel android)

**Comment by karwosts** [comment]
This isn't a frontend issue, please file a core issue for the integration you're referring to (which you didn't mention exactly what it was, tplink I guess).
