### ISSUE TITLE
Misaligned Mode/Preset/Fan Mode Selectors in Thermostat / Climate More Info Dialog

### ISSUE THREAD

**Issue by krazos** [home-assistant/frontend#20607]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On smaller mobile screen sizes (e.g., iPhone 14 Pro), the bottom row of mode/present/fan mode button selectors are misaligned in the thermostat/climate more info dialog. 

Seeing the same issue in Chrome Dev Tools with smaller screen sizes. 

![thermostat-more-info-iphone-14-pro](https://github.com/home-assistant/frontend/assets/18428022/7d619a2e-01bc-47f7-b4c0-29dc77f0f983)

### Describe the behavior you expected

Bottom row of buttons should have equal margin/padding on left and right sides of screen. 

### Steps to reproduce the issue

N/A

### What version of Home Assistant Core has the issue?

core-2024.4.4

### In which browser are you experiencing the issue with?

Home Assistant Companion App 2024.4.1 (2024.650)

### Which operating system are you using to run this browser?

iOS 17.4.1

**Comment by bramkragten** [comment]
As discussed on discord, this is by design, it is a horizontal scroller.
