### ISSUE TITLE
Timer Helper cannot be edited

### ISSUE THREAD

**Issue by almighty059** [home-assistant/frontend#20608]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

This ha been an issue for a while. Once a Timer has been created with the Helper UI it cannot be later edited. It must be completely deleted and recreated if any changes need to be made.

### Describe the behavior you expected

Being able to edit a Timer Helper.

### Steps to reproduce the issue

1. Create a Timer in the Helper UI.
2. Go back and try to make a change.
3.
...

### What version of Home Assistant Core has the issue?

2024.4.3

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Firefox 125.0.2

### Which operating system are you using to run this browser?

Windows 11 Pro 22631.3447

**Comment by almighty059** [comment]
> The actual logic of timer counting and such is a core issue, not frontend.
> 
> If you no longer have frontend/display problems with the timer, this can be closed.

I just realized that the timer function seems to be adding 10 seconds to everything I set it to. Where is the proper place that I should submit this issue?

**Comment by karwosts** [comment]
Try testing a 3 second timer.

Does it count `13..12..11.10..9..8..7..6..5..4..3..2..1`?

Or does it display `13..12..11..Idle`?

If it's the latter the likely issue is that your frontend and backend clocks are slightly out of sync, which would cause that.

**Comment by almighty059** [comment]
https://github.com/home-assistant/frontend/assets/63380298/833abf38-e490-4fe3-a6ad-67ce1693007e

**Comment by karwosts** [comment]
Ok yeah that's just an issue with your system clocks, one of either the frontend or backend is 10 seconds ahead of the other.

**Comment by almighty059** [comment]
How can I fix that?

**Comment by almighty059** [comment]
@karwosts how do I get everything synced up correctly to avoid or to fix the issue?

**Comment by karwosts** [comment]
Sorry this is not a support forum, try one of the help channels. https://www.home-assistant.io/help#communication-channels

**Comment by almighty059** [comment]
Okay. Thanks.
