### ISSUE TITLE
Integration Setup Epic Games Store Stuck

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#20611]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hi, when i add integration epic games store it gets stuck in the set up and i don't see nothing only this

![image](https://github.com/home-assistant/frontend/assets/42905545/724e93a7-c814-4ca6-bb39-1779d991ecba)

### Describe the behavior you expected

*

### Steps to reproduce the issue

*

### What version of Home Assistant Core has the issue?

2024.5.0b0

**Comment by spacegaier** [comment]
We need more information to assist: What were your exact steps to reproduce the issue? Are there any errors in the browser console or the HA log?
