### ISSUE TITLE
Link "Aktiviere den Home Assistant-Skill für Google Assistant" -> Google Error 404

### ISSUE THREAD

**Issue by garnbleiche** [home-assistant/frontend#20637]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I click the link "Activate the Home Assistant Skill for Google Assistant" I get the Google error message 404.

![S5VIkHiAmE](https://github.com/home-assistant/frontend/assets/28215618/28aa6045-1c69-403c-a7c4-7870a5517f45)

### Describe the behavior you expected

To come to a page where I can set up the Assistant Skill.

### Steps to reproduce the issue

1. Einstellungen
2. Sprachassistenten
3. Click on "Aktiviere den Home Assistant-Skill für Google Assistant"

### What version of Home Assistant Core has the issue?

2024.4.4

### In which browser are you experiencing the issue with?

Google Chrome Version 124.0.6367.61 (Offizieller Build) (64-Bit)

### Which operating system are you using to run this browser?

Microsoft Windows [Version 10.0.22621.3447]

**Comment by silamon** [comment]
It seems the link is no longer working and there's not really a replacement. Found this on the community forum: 

Google Home App → Add Device → Works with Google Home → Search for ‘Home Assistant Cloud by Nabu Casa’ → And then logged in through Nabu Casa within the Google Home App

This only works if you have setup Nabu Casa paid service in Voice Assistants within Home Assistant. 

https://community.home-assistant.io/t/unable-to-link-google-assistant/419456/7
