### ISSUE TITLE
Map and Webpage dashboards appear in "Move to View" dialog, yet cards cannot be moved to them

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#20633]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When using the "Add to Dashboard" buttons on device page, or the "Move to View" option in Lovelace edit mode, there is a dropdown for selecting which dashboard it should be added/moved to. 

This dropdown shows the new Map dashboards and Webpage/iFrame dashboards (added in 2024.4 release), despite it being impossible to move cards into those (as they have just a single card and no views). 

IMO these should be filtered out completely, or give those dashboards disabled attribute so they're grayed out

<img width="431" alt="Screenshot 2024-04-26 at 1 33 08 AM" src="https://github.com/home-assistant/frontend/assets/9065557/e648fd7b-fe16-40e1-afeb-f04b66ecf15e">

### Describe the behavior you expected

Filter out dashboards that user cannot add entities to, like Map and Webpage

### Steps to reproduce the issue

1. First make a Webpage Dashboard (Settings > Dashboards > Add Dashboard > Webpage)
2. Then in a different dashboard, enter Lovelace edit mode and select the "Move Card" option ... OR ... from the devices page press the "Add to Dashboard" button
3. In the Dashboard dropdown, select your Webpage card

### What version of Home Assistant Core has the issue?

2024.4.3

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

macOS Sonoma

**Comment by karwosts** [comment]
I'm not sure if it makes sense to fix this as we populate the dropdown based on the list returned by the API `lovelace/dashboards/list`. 

Nothing returned in that API tells us if the dashboard has eligible views. Only after a dashboard is selected do we further issue an API request for the configuration of that particular dashboard, and only at that point do we find out what views are available. 

To fix this we would have to loop and request the detail configuration for all dashboards upfront, which is more queries than strictly necessary.

**Comment by SeanPM5** [comment]
I can't speak to any performance implications or backend considerations, so feel free to close if it doesn't make sense to fix it from that standpoint.

But strictly from a UX perspective it's not ideal to present the user with a bunch of non-working options that give an immediate error when clicking on it. And this will only become more of an issue in the future as additional specialized dashboards and auto-generated dashboards get added. 

Besides just these specialized Map and Webpage dashboards, this dialog is _also_ showing YAML-based dashboards, which are obviously ineligible as move targets for UI-based cards. If at least YAML dashboards could be filtered out from the dropdown more easily(?) it would help a bit.
