### ISSUE TITLE
Community tip - Rename Twitter to X

### ISSUE THREAD

**Issue by N1c093** [home-assistant/frontend#20634]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I just noticed that in the settings menu `/config/dashboard` the tip for joining the community is still pointing to twitter.
In July 2023 Twitter was renamed to X.

![image](https://github.com/home-assistant/frontend/assets/59510296/67d54c32-6bdf-420b-a6af-8dbcc97985ae)

Sadly I didn't found the right point in the code, where I can fix it myself.

### Describe the behavior you expected

The community tip should be pointing to X

### Steps to reproduce the issue

1. Open the settings menu in Home Assistant
2. See community tip is pointing to Twitter
3.
...

### What version of Home Assistant Core has the issue?

2024.4.4

**Comment by silamon** [comment]
It's in the translations file: https://github.com/home-assistant/frontend/blob/dev/src/translations/en.json

**Comment by spacegaier** [comment]
Changing that to the new name looks really weird (since they chose a s**p*d name 👿).

![image](https://github.com/home-assistant/frontend/assets/114137/a796409e-be67-425c-a138-8ee71b9cf3a1)

What do you think about this?

![image](https://github.com/home-assistant/frontend/assets/114137/7448c928-0d98-4c7e-848f-1fcfd2edb97c)

**Comment by matthiasdebaat** [comment]
> What do you think about this?
> 
> ![image](https://private-user-images.githubusercontent.com/114137/326126002-7448c928-0d98-4c7e-848f-1fcfd2edb97c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMDc2NDksIm5iZiI6MTcxNDMwNzM0OSwicGF0aCI6Ii8xMTQxMzcvMzI2MTI2MDAyLTc0NDhjOTI4LTBkOTgtNGM3ZS04NDhmLTFmY2ZkMmVkYjk3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQxMjI5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzA2ODliNTBmYTBhNTg1OGExZmQ5NmIwYzhmZTU1NzgyMDliNzk3YmQ2MjBhZTExYjJkYTQyNjY5ZDQxNjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._dCufzr2YnWL-gCYU7aie55B3qOQ_Hm6Kxm3fkDheIg)

I agree this one is better. Let's include the `(formerly Twitter)` part as a link.
