### ISSUE TITLE
_

### ISSUE THREAD

**Issue by trondtorsoe** [home-assistant/frontend#20672]

**Comment by trondtorsoe** [comment]
![2024-04-30 11 43 56](https://github.com/home-assistant/frontend/assets/50380501/511cf98e-8749-45bf-b326-823d012cfe3a)
![2024-04-30 11 58 28](https://github.com/home-assistant/frontend/assets/50380501/d60a0ecc-3dc2-4032-88b9-f765fd71b8b6)
![2024-04-30 11 57 04](https://github.com/home-assistant/frontend/assets/50380501/2d08d4f3-8ff6-41a9-bae3-77659544b9f2)

**Comment by karwosts** [comment]
?
