### ISSUE TITLE
Border radius not applying to energy setup wizard

### ISSUE THREAD

**Issue by Nezz** [home-assistant/frontend#20686]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Border radius, box shadow and border radius settings are not applying to energy setup wizard:
<img src="https://github.com/home-assistant/frontend/assets/431167/2f27e93a-c86c-439b-84e9-5f43bd7ee4e6" width="400">

This is a regression from
https://github.com/home-assistant/frontend/pull/20122
https://github.com/home-assistant/frontend/pull/20135

### Describe the behavior you expected

The theme settings should apply to this panel too:

<img src="https://github.com/home-assistant/frontend/assets/431167/8441b8e2-6092-48a2-90fc-924b8d1cdc23" width="400">

### Steps to reproduce the issue

1. Start a Home Assistant installation without the energy dashboard set up
2. Apply a theme:
```
  ha-card-border-radius: 20px
  ha-card-border-width: thick
  ha-card-box-shadow: 10px 5px 5px red
```

### What version of Home Assistant Core has the issue?

core-2024.5.0b4

**Comment by praneethgourla18** [comment]
Hey! Assign this to me.

**Comment by karwosts** [comment]
Typically I haven't seen assignments done to new contributors, but it is not necessary. 

If you would like to fix the issue, feel free to create your PR when you are ready.
