### ISSUE TITLE
area card configuration is showing a wrong power value

### ISSUE THREAD

**Issue by thoumsen** [home-assistant/frontend#20687]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If i add an "area card configuration" to the overview dashboard, the total power of the area is showing a wrong value. If i turn on an electrical device the area card is showing the power as factor 10 to less. For example de device has a power of 10W the area card is showing a power of 0.1W.

### Describe the behavior you expected

The total power should be correct

### Steps to reproduce the issue

1. Add a Shelly Plus 1PM to the Devices and add it to an area
2. Add an area card configuration to the dashboard
3. Turn on the Shelly
![iyJ6UEs2xc](https://github.com/home-assistant/frontend/assets/167649408/9a8f4141-f6f4-4bb3-a952-c38b7a9e4831)
4. Compare the power with the dashboard
![e5UWYy9cTh](https://github.com/home-assistant/frontend/assets/167649408/726263b9-d52a-4831-bdbf-811b4e0f94c3)
5. value ist wrong

### What version of Home Assistant Core has the issue?

2024.4.4

### In which browser are you experiencing the issue with?

Google Chromium Version 122.0.6261.89

**Comment by ildar170975** [comment]
Probably because Area card shows not a summary value for "power" sensors.

**Comment by thoumsen** [comment]
> Probably because Area card shows not a summary value for "power" sensors. A possible duplicate of #20014
In my opinion i just use one sensor in the area. So it's not a average as in #20014, it's definitly decimal point error.

**Comment by thoumsen** [comment]
> Probably because Area card shows not a summary value for "power" sensors. A possible duplicate of #20014

In my case i just use one sensor in this area. So it's not a average as in https://github.com/home-assistant/frontend/issues/20014 described, it's definitly decimal point error.

**Comment by thoumsen** [comment]
> Probably because Area card shows not a summary value for "power" sensors. A possible duplicate of #20014

Ok yes looks like you're right, but i doesn't make sense to me to show a average value
