### ISSUE TITLE
With conditional blocks the sections do not align properly

### ISSUE THREAD

**Issue by Gerard64** [home-assistant/frontend#20692]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

With conditional blocks, the sections do not align properly.

### Describe the behavior you expected

In the attached images you can see the behavior.

### Steps to reproduce the issue

1. I have several motion sensors (hue)
2. With the new experimental sections I created a conditional block that is only displayed wen the batterie level of one of the motion sensors is below 30%
3. Wen i close the Lovelace editor the space were the hidden block is added is a empty space i think should not be there.

![Untitled-1](https://github.com/home-assistant/frontend/assets/7952595/475dbf63-2e8d-4fc1-8fa0-c6096db5089e)
![Untitled-2](https://github.com/home-assistant/frontend/assets/7952595/5b546c5d-faa6-436f-9b6f-3fd37b928898)
![Untitled-3](https://github.com/home-assistant/frontend/assets/7952595/c96a99ee-4f42-452c-8267-60b0b5b4be6d)

### What version of Home Assistant Core has the issue?

2024.4.3, 2024.4.4, 2024.5.0

### What was the last working version of Home Assistant Core?

none

### In which browser are you experiencing the issue with?

Firefox 125.0.3, latest Edge and Vivaldi

### Which operating system are you using to run this browser?

Windows 10 pro

**Comment by Drun555** [comment]
It also happens with auto-entities custom card when there's no entities to show.

**Comment by Gerard64** [comment]
The problem is still with the latest version of Home-assistant.
![afbeelding](https://github.com/user-attachments/assets/7c9362a0-106b-42c7-8250-40d464ddf137)
