### ISSUE TITLE
Tags are not completely visible even if there is a space

### ISSUE THREAD

**Issue by dmitry-pervushin** [home-assistant/frontend#20698]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In "Automatizations" table, list of tags is not completely visible even if there is some space
(+1) [ or +2, etc ] icon is shown instead
![B](https://github.com/home-assistant/frontend/assets/1681210/9f88c530-075e-4a35-8f03-f65d3bd2d8a6)

### Describe the behavior you expected

I want to see full list of tags

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.5.0

**Comment by ildar170975** [comment]
https://github.com/home-assistant/frontend/issues/20398

**Comment by dmitry-pervushin** [comment]
Dup of the issue above
