### ISSUE TITLE
Lovelace dashboard content no longer loading on old Chrome version after upgrade to 2024.5.0

### ISSUE THREAD

**Issue by Taygeto** [home-assistant/frontend#20713]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I use an old iPad as a fixed dashboard in my home. Since it is rather old, it is also running an old version of Chrome (my dashboards never worked decently in Safari). 
Immediately after upgrading to 2024.5.0 my dashboard is not showing any content anymore on this device. The navigation UI elements are still showing, but the content is either blank or showing an error (cf. screenshots). On all other devices, everything is working fine. 
I expected there to come an end to the compatibility with older browsers at some point, but did not see anything hinting that I might expect this in the release notes. Is this something that can still be fixed or was some underlying change made that is simply not compatible with older browsers anymore?

![IMG_0103](https://github.com/home-assistant/frontend/assets/79874511/67877e56-718a-4c6d-9e6a-e3533ddd5f98)
![IMG_0104](https://github.com/home-assistant/frontend/assets/79874511/efad025a-3ed6-4d30-8802-44b30d1b470a)
![IMG_0105](https://github.com/home-assistant/frontend/assets/79874511/d9c21594-ec4e-45cf-ba18-363c842408ce)

### Describe the behavior you expected

Dashboard loading fine and showing content. 

### Steps to reproduce the issue

1. Run an any Lovelace dashboard in Chrome version 71 after upgrading Home Assistant core 2024.5.0.

### What version of Home Assistant Core has the issue?

core-2024.5.0

### What was the last working version of Home Assistant Core?

core-2024.4.4

### In which browser are you experiencing the issue with?

Google Chrome 71.0.3578.89

### Which operating system are you using to run this browser?

iOS 10.3.3

**Comment by silamon** [comment]
Duplicate, but thanks for writing it out. Feel free to join in #20697.
