### ISSUE TITLE
Solar production disappeared after 2024.5.1 upgrade

### ISSUE THREAD

**Issue by madbrain76** [home-assistant/frontend#20720]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Solar production, real-time or historical, no longer displays in the Energy tab.
The Energy usage part is still correct, and accounts for the solar production.

### Describe the behavior you expected

I expected my solar production not to disappear after upgrading.

### Steps to reproduce the issue

1. Install 2024.5.0 or earlier
2. Collect solar production with Enphase Envoy devices
3. Add it to the energy tab, and make sure it displays
4. Upgrade to 2024.5.1
5. See that it's no longer there
...

### What version of Home Assistant Core has the issue?

core-2024.5.1

### What was the last working version of Home Assistant Core?

2024.5.0

### In which browser are you experiencing the issue with?

Firefox 125.0.3 for Windows

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
N/A
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

### Additional information

I have 4 solar entities in my energy dashboard. 3 for currently active devices, 1 for historical device that has since been removed but still has history (or did, anyway, before my DB crashed a while ago). In any case, I deleted that dead entity, and the problem still occurs in the energy dashboard.

![image](https://github.com/home-assistant/frontend/assets/57333073/f34afeeb-e645-447a-943c-5a73d0158c6b)

Here is what the dashboard looks like for today so far :

![image](https://github.com/home-assistant/frontend/assets/57333073/1f5af26a-00b7-40d3-9653-aa8e079ee081)

I did upgrade fairly recently, less than 2 hours ago. I don't expect new solar production data to show up right away. But old data should be there, still. It's missing also for all previous time periods.

**Comment by karwosts** [comment]
Check your entity in developer-tools/statistics, it may have some issue that needs correcting.

**Comment by madbrain76** [comment]
@karwosts Thanks. I did a restore of my 2024.5.0 backup before your comment. The issue still showed up ! I then rebooted HA, and the problem was solved. Then, I upgraded to 2024.5.1 again. And the problem didn't reappear.
Very strange that it only showed up for one of the two 2024.5.0 -> 2024.5.1 upgrades I did .
Is it expected that one needs to reboot HAOS after a minor upgrade ?
