### ISSUE TITLE
Map card: map is not centered to a zone

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#20722]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Consider the config:
```
type: map
auto_fit: true
fit_zones: true
entities:
  - entity: zone.borovkovo
```
The `zone.borovkovo` is NOT a home zone.
But the map card is centered to a home zone.
Need to zoom/scroll to see the zone (icon `mdi:car`):
![image](https://github.com/home-assistant/frontend/assets/71872483/339b4771-8015-4a7f-bf4a-d05b0926035d)

According to [Docs](https://www.home-assistant.io/dashboards/map/):
![image](https://github.com/home-assistant/frontend/assets/71872483/c9030bb5-7fcc-4710-b4b1-eeb31bb2de8d)

### Describe the behavior you expected

The only zone is placed in the center.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2024.5

### In which browser are you experiencing the issue with?

Chrome 124.0.6367.92

### Which operating system are you using to run this browser?

Win10x64

**Comment by karwosts** [comment]
You are not wrong, but is there an actual usecase for a map with _only_ zones on it? Seems like that would just be a static picture of little use.

**Comment by ildar170975** [comment]
up
