### ISSUE TITLE
[ambient_network] Failed setup: Station XXX did not report a time stamp

### ISSUE THREAD

**Issue by mareksuski** [home-assistant/frontend#20737]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

![image](https://github.com/home-assistant/frontend/assets/18272118/f27518ac-e1c3-4028-9890-aec6a2d6fab4)

### Describe the behavior you expected

It would pull the data

### Steps to reproduce the issue

1. Browse to your Home Assistant instance.

2. Go to [Settings > Devices & Services](https://my.home-assistant.io/redirect/integrations).

3. In the bottom right corner, select the  [Add Integration](https://my.home-assistant.io/redirect/config_flow_start?domain=ambient_network) button.

4. From the list, select Ambient Weather Network.

5. Selected Warsaw in Poland

6. Selected Warsaw Chopin Airport

### What version of Home Assistant Core has the issue?

2024.5.1

### What was the last working version of Home Assistant Core?

NA

### Which operating system are you using to run this browser?

Windows 10 Pro Eng 

### Additional information

The Warsaw Chopin Airport weather station on https://ambientweather.net/dashboard/iata-waw works well.

![image](https://github.com/home-assistant/frontend/assets/18272118/63ed1600-c7ed-49b5-bbf9-ef9fe309efca)

**Comment by karwosts** [comment]
Integration configuration issues should be filed in home-assistant/core repo, not frontend.
