### ISSUE TITLE
Error communicating with API

### ISSUE THREAD

**Issue by Stonie70** [home-assistant/frontend#20734]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I want to use the ondilo integration for the first time. 
The Installation works with now problems (including the Logon on the API Site.)
But it seems that HA gets no connection:

![image](https://github.com/home-assistant/frontend/assets/90376181/fe7e57fe-bf29-44a1-af88-d8995d66aaa7)

### Describe the behavior you expected

I expected to get the informations from my Pool Sensor

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.5.1

### What was the last working version of Home Assistant Core?

none

### In which browser are you experiencing the issue with?

Microsoft Edge

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment]
Integration setup issues need to be filed in home-assistant/core, this is not something for frontend.
