### ISSUE TITLE
wds is not working

### ISSUE THREAD

**Issue by aundis** [home-assistant/frontend#20750]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

```
[06:57:33] Finished 'develop-app' after 7.82 s
Web Dev Server started...

  Root dir: /frontend
  Local:    http://localhost:8000/
  Network:  http://192.168.1.137:8000/
```
I visited http://localhost:8000/ and got 'Not Found'

### Describe the behavior you expected

I hope the frontend can work independently and then connect to the backend through a proxy.

### Steps to reproduce the issue

1. script/setup
2. script/develop-wds

develop-wds
``` bash
#!/bin/sh
# Run the frontend development server

# Stop on errors
set -e

cd "$(dirname "$0")/.."

export WDS=1
./node_modules/.bin/gulp develop-app

```

### What version of Home Assistant Core has the issue?

2024.4.3

### What was the last working version of Home Assistant Core?

2024.4.3

### In which browser are you experiencing the issue with?

edge 124.0.2478.80

### Which operating system are you using to run this browser?

win10

**Comment by steverep** [comment]
It's unclear what you are trying to do here, and your script is simply not correct.  You cannot connect to the frontend without HA core as the server unless you are only trying to run the demo/cast/gallery (and in those cases WDS is only for rollup, which is not production).  Please discuss this on Discord if you have more questions.
