### ISSUE TITLE
Source sensor not shown in configuration for Threshold Sensor helper

### ISSUE THREAD

**Issue by qvdm** [home-assistant/frontend#20768]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When creating a threshold sensor under Settings / Devices / Helpers, you define the input sensor for the helper.  

When EDITING a threshold sensor helper, the name or id of the input sensor is not shown anywhere in the user interface. 

### Describe the behavior you expected

Since the input sensor is THE core entity that is driving the helper, it does not make sense that it is not displayed when editing the helper.  I would expect to be able to at least see the input sensor name, but preferably be able to edit it because one might want to change the input sensor for a helper that is used in many automations.  Currently, the only way to change the input sensor is to create a new helper and change all the related automations. 

### Steps to reproduce the issue

1. Create a new Threshold Sensor in Helpers, based on an existing input sensor value
2. After saving the new Threshold Sensor, edit it.  
3. The input sensor is not accessible in the edit UI. 

### What version of Home Assistant Core has the issue?

2024.5.2

### What was the last working version of Home Assistant Core?

Never worked

### In which browser are you experiencing the issue with?

Several versions of Chrome, Firefox, and Safari.  

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
N/A
```

### Javascript errors shown in your browser console/inspector

```txt
None
```

**Comment by karwosts** [comment]
This needs to be filed in home-assistant/core for the `threshold` integration. 

Frontend does not control the UI for integration setup, the integrations themselves define what form fields they want to show during config flow and options flow. There's nothing we can do from here.
