### ISSUE TITLE
 LG webOS Smart TV Integration  Attribute freeze.  

### ISSUE THREAD

**Issue by boby51** [home-assistant/frontend#20770]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When switching back to normal tv after watching Netflix the attribute 'media_title:' updates  but stays stuck until integration is reloaded. 

### Describe the behavior you expected

Media title should stay in sync with TV 

### Steps to reproduce the issue

1. watch Netflix
2. exit Netflix 
3. change tv channel 
4.
5.
6.
...

### What version of Home Assistant Core has the issue?

2024.5.2

### In which browser are you experiencing the issue with?

Google chrome 124.0.6367.202

### Which operating system are you using to run this browser?

OS 10.15.7 (19H2026)

**Comment by karwosts** [comment]
Please file this in home-assistant/core, this is not a frontend issue.
