### ISSUE TITLE
riemann sum helper does not show source, unit and time in edit view

### ISSUE THREAD

**Issue by Me-xx** [home-assistant/frontend#20779]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When going to Settings-Devices-Helper( http://homeassistant.local:8123/config/helpers)  or to http://homeassistant.local:8123/config/integrations/integration/integration . I can only edit the accurancy not the source nor the time or the unitmulitplier

### Describe the behavior you expected

Edit all data fields that can be set during "create a new helper" or in data if the helper is put manual in configuration.yaml.

### Steps to reproduce the issue

1. Create Helper
2. Try to Edit helper
3.
...

### What version of Home Assistant Core has the issue?

core-2024.5.2

### In which browser are you experiencing the issue with?

FireFix 125.0.3 and MS Edge

### Which operating system are you using to run this browser?

Windows 11 Version	10.0.22631 Build 22631

**Comment by karwosts** [comment]
This is not a frontend issue, the core integration decides what settings are available. May be partially fixed by https://github.com/home-assistant/core/pull/116740, but otherwise this is a core issue.
