### ISSUE TITLE
Testing template in the UI does not provide any error or result

### ISSUE THREAD

**Issue by erjoalgo** [home-assistant/frontend#20780]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I'm new to using templates and I was trying to add a condition to limit an automation to run at most once daily.

Testing various other triggers in the UI appears to work with a popup green or yellow box indicating whether the automation succeeded or failed.

But nothing happens when clicking "Test" to testing the template:

I assume I'm doing something wrong but I expect at least an error message. I don't see anything in the console.

![11-May-2024-15:31:02](https://github.com/home-assistant/frontend/assets/5349288/86a5f39a-671f-46e6-9785-4fa555d98918)

I've included a screen recording of the issue.

Version info:

```
Home Assistant

Core 2024.5.2
Supervisor 2024.05.1
Frontend 20240501.1
```

### Describe the behavior you expected

Expect to see a popup when clicking on the `Test` button for a trigger while debugging.

### Steps to reproduce the issue

1. Try to create an automation and enter a template trigger with the value `{{ true }}`
2. Click `Test` on the drop-down menu for that trigger
3. Nothing happens. Expect to see a popup with an error or success message
...

### What version of Home Assistant Core has the issue?

2024.5.2

### In which browser are you experiencing the issue with?

124.0.6367.118 (Official Build) built on Debian 12.5, running on Debian 12.5 (64-bit) 

### Which operating system are you using to run this browser?

Debian

**Comment by karwosts** [comment]
Hmm working for me. Did you really try in safe mode? It's clear that your screen grab is not from safe mode. 

![image](https://github.com/home-assistant/frontend/assets/32912880/7c43b738-002a-4428-8749-97e8534d418d)

**Comment by rw-django-fan-2020** [comment]
The yaml editor for template automations or scripts is broken.

When I try:
`service: media_player.play_media`
`data:`
`  media_content_type: folder`
`  media_content_id: {{ ["2023", "2024"] | random }}`
`target:`
`  entity_id: media_player.mpd_homeassistant`

Then it does not work.

When I try:
`service: media_player.play_media`
`data:`
`  media_content_type: folder`
`  media_content_id: >-`
`    {{ ["2023", "2024"] | random }}`
`target:`
`  entity_id: media_player.mpd_homeassistant`

Then it works.

Where are many more examples like that.
