### ISSUE TITLE
Add warning when requesting user for code from TVs about the screen staying on.

### ISSUE THREAD

**Issue by thewan056** [home-assistant/frontend#20796]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

My OLED TV needed to be sent back for warranty so I decided to factory reset my TV. After that was done, HA decided to notify me that I needed to reconfigure my Android TV integration. I unintentionally clicked reconfigure and the integration requested me to input a new code. Since I needed to return the TV and only readd the replacement TV on my HA I decided to close and ignore the request. I didn't realize that the TV was on and still showing the code requested by HA until a few days later. The TV still works fine, were sending it in for dead pixels, but we decided to not watch TV until we get a new one so no one entered the TV room since I factory reset the TV. Now theres the code and the UI surrounding the code burned into my TV. 

### Describe the behavior you expected

I would like to see a warning in both the docs and the UI for anything that requests code from a TV that tells users the TV screen does not change or turn off without user intervention and therefore risks image retention or burn in especially if your TV is an  OLED.

### Steps to reproduce the issue

1. Add or Reconfigure Android TV integration
2. HA requests for code.
3. Close and ignore request for said code.
4. Forget to turn off TV screen for a few days
5.  Burn in happens
...

### What version of Home Assistant Core has the issue?

2024.5.3

**Comment by karwosts** [comment]
I believe this would need to be done as part of the androidTV integration in core, the frontend doesn't define integration specific configuration flows like this.

**Comment by thewan056** [comment]
Alright thanks. Its not really clear what issue goes where, and what is a feature request or not. I suggest making this more clear and simple for future influx of more normal less technical users since HA is planning to target the average Walmart shopper.
