### ISSUE TITLE
Short-lived toggles broken after 2024.5.0 front-end update

### ISSUE THREAD

**Issue by tyron** [home-assistant/frontend#20807]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have an automation that immediately turns off a toggle when it is turned on. Up until 2024.5.0 version, I could trigger the toggle in the UI and it would very quickly turned off. After this version, the toggle seems to not be updated anymore.
If I add a delay to my automation, then it works fine again.

Initially I thought this was related to `core`, but during my tests, it still worked well after HA was updated to 2024.5.0, and it only starts failing after I got the "there's a new frontend version" and I reloaded the scripts.

### Describe the behavior you expected

As before, I expected the toggle to be immediately switched off after turned on.

### Steps to reproduce the issue

1. Create a new Toggle Helper (e.g. `input_boolean.toggle_1`)
2. Create a new automation with the following:
```yaml
trigger:
- platform: state
  entity_id:
  - input_boolean.toggle_1
  to: 'on'
condition: []
action:
- service: input_boolean.turn_off
  metadata: {}
  data: {}
  target:
    entity_id:
    - input_boolean.toggle_1
mode: single
```
3. Open the entity window for the Toggle and turn it on. Up until 2024.5.0, the toggle would immediately turn off. Starting on this version, the toggle is not turned off anymore.
4. If you add a delay as the first step of the automation above, then everything works again.
...

### What version of Home Assistant Core has the issue?

core-2024.5.1

### What was the last working version of Home Assistant Core?

core-2024.4.4

### In which browser are you experiencing the issue with?

Google Chrome 124.0.6367.119

### Which operating system are you using to run this browser?

macOS Sonoma 14.4.1 

### Additional information

This shows the behaviour I'm seeing: https://imgur.com/a/TNinCtD
The first 50 seconds show the previous behaviour, then the last 10 seconds is after the frontend is refreshed.

**Comment by tyron** [comment]
@ildar170975 my tests show a result a little bit different.
If I inspect developer tools for the state of the toggles, the one misbehaving actually changes the state to "ON", and it stays like that forever. Then if I refresh the screen, the cards show as if it was turned off, but state still shows ON.
At that point, the only way to change it back to OFF is by restart HA altogether.

New video: https://imgur.com/a/mrjrN1q

**Comment by silamon** [comment]
Bisected to core, I've opened https://github.com/home-assistant/core/issues/117781 to track this issue further. Thank you both for the clear examples.

**Comment by silamon** [comment]
Closing since the core issue is solved.
