### ISSUE TITLE
Settings -> Repairs -> Integration startup time is shown as negative

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#20800]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Settings -> Repairs -> Integration startup time
a negative value is shown:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/7268b4e5-e3dd-4143-864e-d1b6313bc9b2)

### Describe the behavior you expected

Startup time >= 0

### Steps to reproduce the issue

see above

### What version of Home Assistant Core has the issue?

2024.5.3

### In which browser are you experiencing the issue with?

Chrome 124.0.6367.202

### Which operating system are you using to run this browser?

Win10x64

**Comment by karwosts** [comment]
These values just come from core in response to `integration/setup_info` WSAPI command. 

If there's a negative value, it must be coming from there.

**Comment by ildar170975** [comment]
Then I will open a core issue.
