### ISSUE TITLE
History & Logbook do not conform to "last-changed"

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#20813]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

There is a `device_tracker`.
Here is it's current state:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/4b0c718d-4d80-4a9d-86ad-b7831da73ac5)

Note that "last-changed" is "May 17, 2024 at 00:37:59".
Same may be got by 

![изображение](https://github.com/home-assistant/frontend/assets/71872483/cd1f60ed-e05a-4852-95f7-eb0be08effb3)

But here is a History - and the state was not changed since 23:55:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/2dd93299-7109-4a39-82fb-e8965e9af0d8)

Same with Logbook:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/90544613-e2a1-4f37-bec1-1f875ab7c235)

And same is shown by DB Browser:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/61d618aa-d863-4b2d-b2fa-c82f9bc89a0b)

The last change of a state was at same 23:55:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/c412a754-0685-4038-9afd-9e0cf033a278)

Now I wonder - why the last-changed value is shown differently?

### Describe the behavior you expected

explained above

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2024.5.3

### In which browser are you experiencing the issue with?

Chrome 124.0.6367.202 

### Which operating system are you using to run this browser?

Win10x64

**Comment by ildar170975** [comment]
Since this could be a core issue - here it is: https://github.com/home-assistant/core/issues/117596

**Comment by silamon** [comment]
Did you restart Home Assistant at 00:37? Anyway this is not a frontend issue as it is show as it is being received from core.

**Comment by ildar170975** [comment]
> Did you restart Home Assistant at 00:37?

If you mean 17.05 00:37 - not.
Uptime graph, no reboots:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/ebaafa99-5117-47e9-932b-906a06afc416)

**Comment by silamon** [comment]
Since it's a core issue, probably there's a reload of the state somewhere what causes the change to happen. We show the datetimes as how we receive them from core.

**Comment by ildar170975** [comment]
Do you know what causes `last-changed` to be updated?
Is it a "state was changed & it is different" event - or is it a "update of state is called" event?
I mean - could the `last-changed` be updated even when a state is same?

**Comment by silamon** [comment]
A restart of Home Assistant forced the last-changed to be changed even when the state is the same. Probably there are also other ways that result in the same, like reloading parts of the configuration, but there are more knowledge people to find that out that read the core issue tracker.

**Comment by ildar170975** [comment]
Thing is that there were no reboots / reloading integrations... Will keep observing.
