### ISSUE TITLE
 homeassistant.components.climate  - Does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method.

### ISSUE THREAD

**Issue by mojaki8286** [home-assistant/frontend#20824]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:363
integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 01:21:51 (24 occurrences)
Last logged: 01:21:51

Entity None (<class 'homeassistant.components.izone.climate.ZoneDevice'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+izone%22
Entity None (<class 'homeassistant.components.izone.climate.ZoneDevice'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+izone%22
Entity None (<class 'homeassistant.components.izone.climate.ZoneDevice'>) implements HVACMode(s): off, fan_only, heat_cool and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+izone%22
Entity None (<class 'homeassistant.components.izone.climate.ZoneDevice'>) implements HVACMode(s): off, fan_only and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+izone%22

### Describe the behavior you expected

Not sure what this is. This recently started showing in the log when I restart HA.

### Steps to reproduce the issue

Restart HA

### What version of Home Assistant Core has the issue?

core-2024.5.4

**Comment by silamon** [comment]
Like it says: Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+izone%22

Somebody else did already:  https://github.com/home-assistant/core/issues/116270
