### ISSUE TITLE
Option 'All entities' in helper 'light group' isn't showing.

### ISSUE THREAD

**Issue by Wolk9** [home-assistant/frontend#20827]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The Option 'All entities' in helper 'light group' isn't showing. This prevents the user from making the choice wether the group should represent only one entity state 'on' as 'on' or that all entities must me 'on' before the group is 'on'. 

### Describe the behavior you expected

I expected the toggle to be visible. 

### Steps to reproduce the issue

1. create helper
2. choose group
3. choose light
4. choose group options
5. See a perfect explenation.
6. miss the switch

### What version of Home Assistant Core has the issue?

2024.5.4

### In which browser are you experiencing the issue with?

Versie 124.0.6367.208 (Officiële build) (x86_64)

### Which operating system are you using to run this browser?

14.3.1 (23D60)

### State of relevant entities

```txt
na
```

### Problem-relevant frontend configuration

```yaml
na
```

### Javascript errors shown in your browser console/inspector

```txt
na
```

### Additional information

na

**Comment by karwosts** [comment]
Check if you have advanced mode on in your profile settings, I think that may be required.

**Comment by Wolk9** [comment]
> Check if you have advanced mode on in your profile settings, I think that may be required.

That would be rather unexpected. Why should a non-advanced user not be able to choose the behavior of its group state?

Beside that discussion: 
If 'behind' the advanced setting is correct, the accompanying text in the upper part of the dialog shouldn't mention the option when not in advanced mode either. In my opinion (As a UX/Ui Designer) it should be one way or the other.

**Comment by karwosts** [comment]
I agree that the message should not mention the option if it is not present. However this actually needs to be an issue for `home-assistant/core` as all the fixes would need to go there. Core defines which options exist for config flows, which options are hidden by advanced mode, and it contains the strings to display at the top of the form for config flow. 

So I don't disagree with you but there is nothing we can do in this repo. Would you be willing to refile your issue there targeting the `group` integration?
