### ISSUE TITLE
Wrong translation assigned to template binary sensor device class.

### ISSUE THREAD

**Issue by fox1047** [home-assistant/frontend#20830]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I'm creating template binary sensor and pick a device class "Присутсвие" (presence) appears twice.
Also "Занятость" (occupancy) is missing. Likely one of those classes is occupancy.
![image](https://github.com/home-assistant/frontend/assets/5703416/5fe59f19-f474-4e8c-a848-7379992b02d6)

### Describe the behavior you expected

I expect to have both "Присутствие" and "Занятость" options when i create template binary sensor.

### Steps to reproduce the issue

1. Switch language to Russian
2. Go to create template binary sensor in UI
3. Try to pick device class

### What version of Home Assistant Core has the issue?

2024.5.4

### In which browser are you experiencing the issue with?

Google Chrome 123.0.6312.106

### Which operating system are you using to run this browser?

Windows 10 22H2

**Comment by karwosts** [comment]
Incorrect translations are not tracked in the github repo.

If you want to review (and suggest corrections) to what translations exist for your language, check out the docs on Lokalise:

https://developers.home-assistant.io/docs/translations/

I'm not sure if these are frontend or backend translations, so check both.

**Comment by fox1047** [comment]
I already checked and translations on Lokalise for both frontend and backend seems to be correct. That's why I opened this issue.

**Comment by karwosts** [comment]
Looks like it used to be what you suggest, but someone changed it. I don't speak Russian so you'll have to make a suggestion there and come to a consensus. 

https://app.lokalise.com/project/130246255a974bd3b5e8a1.51616605/?view=multi&search=key::component::binary_sensor::entity_component::occupancy::name

![image](https://github.com/home-assistant/frontend/assets/32912880/2c43bd7f-2a62-4e8c-8c2c-e3682c422590)

**Comment by fox1047** [comment]
I'm sorry. I pressed [Join the backend translation team](https://lokalise.com/signup/130246255a974bd3b5e8a1.51616605/all/) link and didn't realized that on my screen was still a frontend translation project.
Anyway I restored translation and added a comment to warn others.
Thank you @karwosts
