### ISSUE TITLE
Energy Dashboard reports  to high battery import values

### ISSUE THREAD

**Issue by miltonkeans** [home-assistant/frontend#20849]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Some times the energy dashboard  is reporting  "Solax todays import energy" a very high value like 630 kWh although my battery has just a capacity of 6 kWh. The values are getting by modbus from solax.

### Describe the behavior you expected

reporting realistic values

### Steps to reproduce the issue

1.
2.
3.
...
?

### What version of Home Assistant Core has the issue?

2024.5.4

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Edge

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment]
Energy just reports the information your sensors give it. You would need to look closer at your sensor history and statistics to understand why your sensor is reporting this value. 

Suspect you may be running into this issue:

https://gist.github.com/langestefan/acbf7e42b15b302e9aacc08663039e57#4-my-energy-dashboard-shows-a-weird-spike-of-x-kwh-how-can-i-correct-it
