### ISSUE TITLE
Sidebar size issue with a statistic graph card on a Sidebar view 

### ISSUE THREAD

**Issue by mbo18** [home-assistant/frontend#20864]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

There is a bug with the sidebar view type : the sidebar on the left is really small compared to the energy dashboard when there is a statistic graph card in the view:

<img width="1555" alt="Capture d’écran 2024-05-24 à 14 52 24" src="https://github.com/home-assistant/frontend/assets/12999535/388d0344-18c0-4979-a892-83f8a70a86bf">

Size is OK when in edit mode:

<img width="1427" alt="Capture d’écran 2024-05-24 à 15 26 00" src="https://github.com/home-assistant/frontend/assets/12999535/0fdda1de-4cd1-44b1-94f7-2ee4d5f97eeb">

### Describe the behavior you expected

Size of the left bar/column should be the same size when there is a statistic graph card in the view or not

### Steps to reproduce the issue

1. Add a new view with View type set to "Sidebar"
2. Add a gauge and move it to the left
3. Add another card that is not a statistic graph card
4. Save the view, the size of the left column with the gauge card is OK
5. Edit the view, add a statistic graph card and save the view
6. The size of the left column with the gauge card is NOK

### What version of Home Assistant Core has the issue?

core-2024.5.4

### What was the last working version of Home Assistant Core?

don't know

### In which browser are you experiencing the issue with?

Firefox, Safari latest release

### Which operating system are you using to run this browser?

macOS and Windows 11

**Comment by ildar170975** [comment]
In my experience, a sidebar's width depends both on cards "on the left" & cards on the sidebar itself.
Managed to set a fixed width with a card-mod theme , kind of
```
  hui-sidebar-view:
    $: |
      .container div#sidebar {
        min-width: .........;
        width: -webkit-fill-available;
      }
```
