### ISSUE TITLE
Energy Dashboard not showing the correct data after restarting HA

### ISSUE THREAD

**Issue by marc965** [home-assistant/frontend#20886]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After restarting Homeassistant, the statistics in the energy dashboard are sometimes reset. As a result, the values displayed are not correct.
For me, this is always triggered by restarting Homeassistant. Then the statistics start counting again, hence these high values.
I have known this behavior since version 2024...

### Describe the behavior you expected

HA has to restart counting at the same position when shutting down, it seems HA is starting back at zero.

### Steps to reproduce the issue

1. restart HA
2. look at the energy dashboard 

### What version of Home Assistant Core has the issue?

2024.x.x

### What was the last working version of Home Assistant Core?

dont know whwn it began, but i tried many things, nothing works

### In which browser are you experiencing the issue with?

Chrome, Firefox, Safari

### Which operating system are you using to run this browser?

windows, iOS

### Additional information

Some picture show that:
This displays only one day:
![image](https://github.com/home-assistant/frontend/assets/85791333/002ce1df-b90e-4eef-bab1-a2fdf095122b)
![image](https://github.com/home-assistant/frontend/assets/85791333/32488c7a-e04e-4969-b5c7-e242d9a3915f)
![image](https://github.com/home-assistant/frontend/assets/85791333/198c90ef-a371-4d6c-a667-864de59609d0)

Without Restarting HA all statistics are ok:
![image](https://github.com/home-assistant/frontend/assets/85791333/875759c2-8c43-4c0b-b900-703b12bd9209)
![image](https://github.com/home-assistant/frontend/assets/85791333/35e50ba7-5b40-46fa-904c-71e9ec628f60)
![image](https://github.com/home-assistant/frontend/assets/85791333/6230dd94-ee87-4a7f-8bec-ae406bb5fa8d)

**Comment by karwosts** [comment]
FYI this has nothing to do with the energy dashboard, it's just bad data that got recorded in your entity statistics (look at a statistics graph card to confirm, you should see similar erroneous value). That would need a core issue to address that.

**Comment by zenz** [comment]
I met the same situation.
I have a gasmeter using AI on the edge project to recognize digital data and send to HA through mqtt. Every restart of HA will cause the sum field in statistics table become zero, then the state will become a huge number. had to fix it manually in the developer panel.

**Comment by marc965** [comment]
This is currently not solved. What a shame. Had tried to solve it with MQTT availability topics. No change. 
Error in Energy statistic still there

**Comment by karwosts** [comment]
As previously mentioned, it is a reponsibility of the core recorder to record statistics. Sometimes it doesn't work right and gets glitchy values, but that is a core problem, so needs to be a core issue. 

Nothing to do in frontend, closing.
