### ISSUE TITLE
Energy-Dashboard - first entry is reporting exorbitant value despite korrect value in the sensor data

### ISSUE THREAD

**Issue by beachbatsch** [home-assistant/frontend#20882]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The first value in the energy-dashboard shows an exorbitant consumption value.
I removed the sensor from the energy-dashboad and again the first entry showed the same symptoms.

I added the sensor again and the problem still exists:
![Bildschirmfoto vom 2024-05-27 12-38-52](https://github.com/home-assistant/frontend/assets/43178112/4944fb84-7239-4af1-8a3a-27d08ca75686)

The saved value of the sensor seems ok
![Bildschirmfoto vom 2024-05-27 12-44-22](https://github.com/home-assistant/frontend/assets/43178112/abe08b98-2a54-4403-a9d1-da87964ba697)

I've checked the consumption-gradient on two devices:
e-Book:
![Bildschirmfoto vom 2024-05-27 12-51-49](https://github.com/home-assistant/frontend/assets/43178112/82e6c9d4-2bbe-444b-ae4f-d1e2291a57af)

Cam:
![Bildschirmfoto vom 2024-05-27 12-53-15](https://github.com/home-assistant/frontend/assets/43178112/b524d6dc-456c-48f7-a961-48ecc22422ba)

Is it possible, that the reporting of 0 values may cause the Problem?

### Describe the behavior you expected

I expect the energy-dashboard to show the correct sum of the energy-consumption

### Steps to reproduce the issue

1. removed the sensor from the dashboard
2. added the sensor back to the dashboard
3.
...

### What version of Home Assistant Core has the issue?

2024.5.5

### In which browser are you experiencing the issue with?

Firefox 126.0

### Which operating system are you using to run this browser?

Fedora Linux

**Comment by karwosts** [comment]
Yes you need to fix your sensor so that it stops frequently glitching to zero. 

Every time it goes to/from 0 that increase is counted as new consumption. If you made a statistics graph card you would see the same. 

Removing/adding sensor from energy dashboard does nothing, the data is all stored in statistics, not in the energy panel specifically.
