### ISSUE TITLE
Energy dashboard does not show battery SOC of my PV

### ISSUE THREAD

**Issue by chrisb4711** [home-assistant/frontend#20904]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I would like to see how much capacity my battery has (SOC)

### Describe the behavior you expected

I would like to see how much capacity my battery has (SOC)

### Steps to reproduce the issue

1. open energy dashboard 
2.battery icon has no SOC % 
3.
...

### What version of Home Assistant Core has the issue?

Core

### In which browser are you experiencing the issue with?

App

### Which operating system are you using to run this browser?

iOS 17.5

**Comment by karwosts** [comment]
This is a feature request, not a bug.

**Comment by chrisb4711** [comment]
Added vote to 

https://github.com/home-assistant/frontend/discussions/12603
