### ISSUE TITLE
New data table feature that saves filters interferes with integration entities

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#20919]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

So the new release now saves your filters which is cool, but noticed a potential issue with it.. Because it saves your filters, some links like this on the integrations page may not work properly anymore. 

For example, if your Entities page is filtered by "Living Room" area, and then you click the link in this screenshot, it will not show any sun entities because none of them are in the living room area. So the user clicks something saying 9 entities and instead gets 0 entities and is wondering what's going on.

<img width="1016" alt="Screen Shot 2024-05-30 at 5 08 28 AM" src="https://github.com/home-assistant/frontend/assets/9065557/ae9b0f25-595e-48c7-9ab1-124710040bc3">

(There's an example below to reproduce)

### Describe the behavior you expected

Technically this is not a bug I guess, but I feel it's gonna be super confusing for some, especially those who don't read the release notes and aren't aware of the new behavior. It might be better for these links specifically to ignore the users saved filters if possible?

If the user clicks on something that says "9 entities" it should actually show those 9 entities, not 0 entities...

### Steps to reproduce the issue

1. Go to Entities page
2. Open filter sidebar and select "Domain: Binary Sensor"
4. Now go to Integrations page (can use the tabs at the top)
5. Click on an integration, for example "Sun"
6. On the next page click the "9 entities" button.
7.  Instead of showing those 9 entities it shows 0 entities because it's using saved filter from step 2, and the sun integration has no binary sensors. 

### What version of Home Assistant Core has the issue?

2024.6.0b1

### What was the last working version of Home Assistant Core?

2024.5.5

**Comment by SeanPM5** [comment]
To add another observation -- the user doesn't need to specify _any_ filter at all. Just the act of visiting one of those links filters by config entry for them. Filter then gets saved, so clicking on another integrations config entry afterwards you're seeing the previous one instead.

In below screen recording I cleared filters first, checked Apple TV and August back to back, the August link was showing me Apple TV entities. 

https://github.com/home-assistant/frontend/assets/9065557/2624af57-77d9-4b07-9646-f87a68ff323a

**Comment by ZephireNZ** [comment]
Can confirm I am also seeing this in `2024.6.0b4`.

I click into entities for one integration, and it filters by that integration as expected.

However when I click back and then click entities for a different integration, the previous one is still filtered.

**Comment by ZephireNZ** [comment]
One behaviour I have noticed - right click and open in a new tab does _not_ trigger this behaviour, the integration is filtered correctly (the URL has the config_entry in it).

So presumably is due to the internal router not setting the filter correctly based on the URL parameter.

**Comment by ZephireNZ** [comment]
FYI I'm going to take a look and see if I can fix this :blush:
