### ISSUE TITLE
ZHA - Zigbee Home Automation NO BACKUP

### ISSUE THREAD

**Issue by POUDZO** [home-assistant/frontend#20913]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I want to make a backup of my devices settings I get the following error: "Failed ti create backup - timeout"
This error was also recently encountered by... (look link down) 

https://github.com/home-assistant/core/issues/117859
https://community.home-assistant.io/t/recent-timeout-error-on-backup-job/729289
https://community.home-assistant.io/t/zha-backup-returns-failed-to-create-backup-timeout/731640

without finding solutions

Thanks for the attention

### Describe the behavior you expected

Before 10 days ago it downloaded a file to the desktop which I kept for possible restores.

### Steps to reproduce the issue

1. Integrations
2. Zigbee Home Automation
3. configure
4. Download backup
...

### What version of Home Assistant Core has the issue?

2024.5.5

### What was the last working version of Home Assistant Core?

2024.5.4

### In which browser are you experiencing the issue with?

Google Chrome Versione 120.0.6099.199 (Build ufficiale) (a 64 bit)

### Which operating system are you using to run this browser?

Windows 10

**Comment by puddly** [comment]
This isn't a frontend issue and is being tracked under https://github.com/home-assistant/core/issues/117859
