### ISSUE TITLE
Cannot disable or reload config entries after upgrading

### ISSUE THREAD

**Issue by jbouwh** [home-assistant/frontend#20912]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The buttons to disable or to reload a config entry do not work anymore. No dialog is shown.

### Describe the behavior you expected

Reload or disabling a config entry should work.

### Steps to reproduce the issue

1. Upgrade to HA Core 2024.6.0b0
2. Make sure frontend is updated
3. Try to disable a config entry.
...

After roling back to 2024.5.5. and refreshing de browser everything works again.

### What version of Home Assistant Core has the issue?

core-2024.6.0b0

### What was the last working version of Home Assistant Core?

core-2024.5.5

### In which browser are you experiencing the issue with?

Firefox 126.0.1 (64-bits)

### Which operating system are you using to run this browser?

Windows 11 pro

**Comment by ildar170975** [comment]
seems to be https://github.com/home-assistant/frontend/issues/20907

**Comment by piitaya** [comment]
Yep it's a duplicate and already fixed. The fix will be available in next beta.

**Comment by jbouwh** [comment]
thanx
