### ISSUE TITLE
Check for updates toast says "No new updates found" then update appears right after

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#20915]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Noticed this behavior for at least few weeks now -- toast will say "No new updates found" 10 seconds after the check for updates button is pressed, and the update then appears on screen while that toast is still visible (and incorrect).

This happens on both my main system and test system. Screen recording below.

https://github.com/home-assistant/frontend/assets/9065557/d8fc33ec-7bcd-4750-9430-9c1ce7efe04c

### Describe the behavior you expected

Bumping the "timeout" window from 10 seconds to 15 seconds would solve it, at least in my case. 

### Steps to reproduce the issue

1. When you know a new beta / OS version is released and don't see it in the settings screen yet, you do a manual check for updates....
2. . Pay attention to toast text and when update appears

### What version of Home Assistant Core has the issue?

2024.6.0b1

**Comment by matthiasdebaat** [comment]
Lol yes, Thanks for creating this one, had the same issue yesterday.

**Comment by piitaya** [comment]
There is no reliable way to know if there is all the update are done checking so we hardcoded a 10s timeout. Looks like the updates arrived few second later 😅 We can increase the timeout to 15s or 20s but it will not be a solution for all cases.

**Comment by SeanPM5** [comment]
I timed several update checks during this beta period, and it took consistently between 12-14 seconds for them to appear on two different systems. So I think increasing timeout to 15s would work pretty well, even if not always perfect.
