### ISSUE TITLE
Renaming a Timer prevents changing timer duration

### ISSUE THREAD

**Issue by screscenti** [home-assistant/frontend#20924]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When changing the name of a timer helper (including the entity ID), it breaks the ability to change the duration of the timer,

### Describe the behavior you expected

If you change the duration of the timer, it should be reflected when you start the timer. It shows as changed but the actual timer when run is using the old setting

### Steps to reproduce the issue

For example purposes, I will use durations of 10 min and 20 seconds for purpose of example, but the specific time is irrelevant

1. Create a helper timer with duration of 20 seconds and name it timer_test_20sec (I want to make sure the scenario I am testing is working before I change it to actual production time I want to use like 10 minutes)
2. Assign the timer to automations to start (for example a motion sensor or door sensor detected/opening)
3. Test the automation (should work normal and see the 20 seconds counting down
4. When satisfied your automation will work, change the name of the timer from timer_test_20sec to timer_bathmotion_10min (this will be the actual name I use because then looking at automations, I will know that the time interval is 10 min at a quick glance vs trying to decipher what is in the helper)
5. Change the duration of the helper timer from 20 seconds to 10 minutes (the changes will reflect in the settings)
6. Make changes to the automation because the entity_id is now changed and clean up your work
7. Execute the automation (open door or walk in a room - based on triggers we set in step 2)
8. You will notice that the timer still executes for the 20 seconds vs the new final duration of 10 minutes that we changed in step 5.
9. 
...

### What version of Home Assistant Core has the issue?

2024.5.5

### In which browser are you experiencing the issue with?

Safari - Version 17.5 (19618.2.12.11.6)

### Which operating system are you using to run this browser?

macOS Sonoma 14.5

**Comment by karwosts** [comment]
Can't reproduce, works fine for me. Suggest check your settings and try again.
