### ISSUE TITLE
2024.6.0b0: issue with conditional cards in sections view

### ISSUE THREAD

**Issue by mbo18** [home-assistant/frontend#20923]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When adding a conditional card to a section and when the condition is not met there is an empty space on the dashboard.

With 2024.5.4:
![IMG_9802](https://github.com/home-assistant/frontend/assets/12999535/ab4e0693-ceb7-45cc-b393-75fb7a50fd91)

With 2024.6.0b0 and b1:
![IMG_9803](https://github.com/home-assistant/frontend/assets/12999535/0d870e33-cb24-4ebe-b50e-5962f15401ae)

### Describe the behavior you expected

Same behavior as 2024.5.4 so no empty space

### Steps to reproduce the issue

1. add a section view to a dashboard
2. Add a section 
3. Add a conditional view with a condition which is false 
4. Save your view
...

### What version of Home Assistant Core has the issue?

core-2024.6.0b0

### What was the last working version of Home Assistant Core?

core-2024.5.x

### In which browser are you experiencing the issue with?

Safari, Firefox latest release

### Which operating system are you using to run this browser?

macOS and iOS

**Comment by andrewfluck** [comment]
<img width="473" alt="Screenshot 2024-05-30 at 14 13 48" src="https://github.com/home-assistant/frontend/assets/8619094/5e50d0bb-47ed-4003-a64c-d23255563469">


I have ran into this as well

**Comment by Revilo91** [comment]
Same as #20352?

**Comment by philipp-frank** [comment]
When sections where introduced in 2024.4 there was the same issue in the beginning - see https://github.com/home-assistant/frontend/issues/20479 - but it was fixed(?) and worked for me until 2024.6.0b0.

**Comment by mbo18** [comment]
I don’t think it is the same issue as it is working fine with release 2024.5. Also I do not use custom card at all

**Comment by piitaya** [comment]
We did some change in the dashboard with the 2024.6.

We introduced the visibility option on every card and section so the conditional card can be replaced with this new option.

But I will take a look to this issue to keep compatibility with conditional card too.

**Comment by RonnieRocket2** [comment]
Same experience for me since a recent update.

**Comment by RonnieRocket2** [comment]
Reverted to core 2024.5.4 it works correctly now but reading the comments it looks like there is a visibility option on every card so I guess I need to look for that and switch it off for the conditional cards.

**Comment by andrewfluck** [comment]
> We introduced the visibility option on every card and section so the conditional card can be replaced with this new option.

I must not have read the documentation hard enough, but could you link where it lets you show hide cards individually without the conditional card? Or did I misunderstand what you meant? 😅

**Comment by mbo18** [comment]
It is currently an open PR https://github.com/home-assistant/frontend/pull/20926

**Comment by piitaya** [comment]
The yaml part is merged (https://github.com/home-assistant/frontend/pull/20840) but the UI part needs to be merged (https://github.com/home-assistant/frontend/pull/20926).

You can test the feature but adding your conditions directly on the card config under the `visibility` key. For example : 
```yaml
type: entity
entity: light.bed_light
visibility:
  - condition: state
    entity: person.paul
    state: home
  - condition: state
    entity: light.kitchen_lights
    state: "on"
```
