### ISSUE TITLE
Unable to control config entries with HA 2024.6.0b1 

### ISSUE THREAD

**Issue by SukramJ** [home-assistant/frontend#20921]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Im not able to control a config entry.
Nothing happens (incl. no logs) when pressing reload, rename, system options, deactivate, delete.
Only item that works is download diagnostics.

Tested with mqtt, mobile app, ......

### Describe the behavior you expected

Feedback in the UI
Integaction with the backend

### Steps to reproduce the issue

1. Go to integrations page
2. Try any integration
3.
...

### What version of Home Assistant Core has the issue?

core-2024.6.0b1

### What was the last working version of Home Assistant Core?

core2024.5.5

### In which browser are you experiencing the issue with?

Chrome 125.0.6422.113, Firefox 126.0.1 

### Which operating system are you using to run this browser?

macOS 14 , ipados 17.5

### State of relevant entities

```txt
-
```

### Problem-relevant frontend configuration

```yaml
-
```

### Javascript errors shown in your browser console/inspector

```txt
-
```

**Comment by ildar170975** [comment]
https://github.com/home-assistant/frontend/issues/20907
