### ISSUE TITLE
HA Demo website - switching between demos broken

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#20946]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When switching configs in demo site ("next demo" button), it fails to work and throws error prompt which you can see below. 

I've not checked demo in a while so not sure how long it's been broken for. Might have to do with new dashboard additions like section visibility etc in 2024.6

https://github.com/home-assistant/frontend/assets/9065557/59b2eeb4-33f6-4d22-b401-5541eacb3b89

### Describe the behavior you expected

able to switch demos

### Steps to reproduce the issue

1. Visit https://demo.home-assistant.io/
2. Click "Next demo"
3. See error

### What version of Home Assistant Core has the issue?

2024.6 beta

**Comment by anscg** [comment]
I remember checking Demo on Monday and switching works fine, just noticed the issue also.

**Comment by silamon** [comment]
It's since the introduction of #20840, pretty recently. 

The demo is doing some patching, that is no longer working:  
https://github.com/home-assistant/frontend/blob/dev/demo/src/stubs/lovelace.ts#L22-L34
