### ISSUE TITLE
Scene editor - header title doesn't get updated when scene renamed

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#20959]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When you rename a scene from the scene editor, it does not update the header title. In this recording I renamed it twice, yet it still had the original name in the header title.

https://github.com/home-assistant/frontend/assets/9065557/bee1360d-0ce1-4e45-936a-cf1c6cf8324b

### Describe the behavior you expected

Update title to reflect new scene name

### Steps to reproduce the issue

1. Go to Settings → Scenes
2. Rename a scene
3. Title won't be updated in the header after saving, even though it is successfully renamed.

### What version of Home Assistant Core has the issue?

2024.6.0b4

**Comment by piitaya** [comment]
I removed the milestone as it's not beta related.

**Comment by SeanPM5** [comment]
Not stale

**Comment by SeanPM5** [comment]
Appears to be fixed now in 2024.12.0b3 👍
