### ISSUE TITLE
Webpage Card not fullscreen in 2024.6.0b4 

### ISSUE THREAD

**Issue by Hackashaq666** [home-assistant/frontend#20954]
### The problem

Webpage Cards in panel view are showing as half-screen windows insead of full-screen.

### What version of Home Assistant Core has the issue?

core-2024.6.0b4

### What was the last working version of Home Assistant Core?

core-2024.5.5

### What type of installation are you running?

Home Assistant Core

### Integration causing the issue

Webpage Card

### Link to integration documentation on our website

https://www.home-assistant.io/dashboards/iframe/

**Comment by silamon** [comment]
Can you post a screenshot of what you exactly mean or post the yaml related code of your dashboard? I've tried some things based on what you said, but cannot reproduce at this time. Also try safe mode to ensure this is not related to custom components or custom resources.

**Comment by Hackashaq666** [comment]
I looked into this a bit more into this problem with panel view of Webpage Cards.
The aspect ratio was set to 50%, which had no effect in 2024.5.5 and previous versions of homeassistant.  However in 2024.6.0b4 it creates black space at the bottom of the panel view, the amount of black space is inversely proportional to the aspect ratio percentage. For example 25% gives more black space than 50%, and 100% gives no black space and gives the desired result. This can be marked as closed if this is the expected behavior for panel view (not sure this is the case based on all previous version of homeassistant).

/[icon: mdi:bookmark-multiple](icon:%20mdi%3Abookmark-multiple%0Acards%3A%0A%20%20-%20type%3A%20iframe%0A%20%20%20%20url%3A%20https%3A//homepage.wirehackashaq.duckdns.org%0A%20%20%20%20aspect_ratio:%2050%25%0Atype:%20panel%0A)
[cards:](icon:%20mdi%3Abookmark-multiple%0Acards%3A%0A%20%20-%20type%3A%20iframe%0A%20%20%20%20url%3A%20https%3A//homepage.wirehackashaq.duckdns.org%0A%20%20%20%20aspect_ratio:%2050%25%0Atype:%20panel%0A)
 [ - type: iframe](icon:%20mdi%3Abookmark-multiple%0Acards%3A%0A%20%20-%20type%3A%20iframe%0A%20%20%20%20url%3A%20https%3A//homepage.wirehackashaq.duckdns.org%0A%20%20%20%20aspect_ratio:%2050%25%0Atype:%20panel%0A)
   [ url: https://homepage.wirehackashaq.duckdns.org](icon:%20mdi%3Abookmark-multiple%0Acards%3A%0A%20%20-%20type%3A%20iframe%0A%20%20%20%20url%3A%20https%3A//homepage.wirehackashaq.duckdns.org%0A%20%20%20%20aspect_ratio:%2050%25%0Atype:%20panel%0A)
   [ aspect_ratio: 50%](icon:%20mdi%3Abookmark-multiple%0Acards%3A%0A%20%20-%20type%3A%20iframe%0A%20%20%20%20url%3A%20https%3A//homepage.wirehackashaq.duckdns.org%0A%20%20%20%20aspect_ratio:%2050%25%0Atype:%20panel%0A)
[type: panel](icon:%20mdi%3Abookmark-multiple%0Acards%3A%0A%20%20-%20type%3A%20iframe%0A%20%20%20%20url%3A%20https%3A//homepage.wirehackashaq.duckdns.org%0A%20%20%20%20aspect_ratio:%2050%25%0Atype:%20panel%0A)

**Comment by Hackashaq666** [comment]
Aspect ratio 100%:
![Screenshot 2024-06-02 at 10 39 55 AM](https://github.com/home-assistant/frontend/assets/11585615/8d2a032c-1c37-421c-b2a2-dcae50a44407)

Aspect ratio 25%:
![Screenshot 2024-06-02 at 10 54 54 AM](https://github.com/home-assistant/frontend/assets/11585615/5bff7ff0-474f-4864-abbd-fc0079a587fe)

**Comment by Hackashaq666** [comment]
I switched to my phone, and the black space is present even when aspect ratio is set to 100%, so definitely a bug. Also, bug exists in safe mode.

**Comment by renarena** [comment]
same for me on pc, laptop and android tab.
with and without `aspect_ratio: 50%`
