### ISSUE TITLE
Latest beta series 2024.6.xx appears to worsen the issue where vertical stacks appear below each other instead of side-by-side

### ISSUE THREAD

**Issue by alexruffell** [home-assistant/frontend#20991]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I use up to 3 vertical stacks for all my dashboards depending on how many entities I need to display/control. On dashboards with 3 stacks, I've always had the issue that instead of appearing side by side, one of the stacks gets pushed down under another stack even though there is plenty of space on screen.

Ever since sections have been introduced it got worse, but with this latest round of betas it is worse than ever. Below is a snapshot of my main dashboard (set at 33% so I could capture it all):

<img width="272" alt="image" src="https://github.com/home-assistant/frontend/assets/4006944/4df16310-83bc-47ce-9e6b-19e92e1bc22e">

I had to reload the page 5 or 6 times before it decided to load properly (now shown at 90% to capture it entirely):

<img width="1033" alt="image" src="https://github.com/home-assistant/frontend/assets/4006944/692fddca-1b60-4590-9869-d0ce7e155582">

I use Chrome 99.9% of the time. I tested this in FireFox and in my brief tests it did not appear to have any issues. I'll keep testing it and report back if FF also has the issue. I always update Chrome so it may well be related to Chrome changes but never noticed a change in connection to an update.

### Describe the behavior you expected

3 vertical stacks normally appear side by side which is the expected behavior if there is enough screen real estate. There is tons of empty space on my 4K screens with 3 vertical stacks. When I first started using the 3 vertical stacks it would have this issue only if there was some issue with one of the cards (or at least there seemed to be some correlation with a card not loading or something, but now everything works fine except for the placement of the stack).

### Steps to reproduce the issue

1. Have 3 large vertical stacks side by side
2. Load dashboard in Chrome
3. Issue happens randomly
...

### What version of Home Assistant Core has the issue?

core-2023.6.0b7

### In which browser are you experiencing the issue with?

Chrome 125.0.6422.113 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

### Additional information

These are the errors I was seeing when the dashboard was misbehaving. The Plotly errors seem to always be there and I don't know whether I am making mistakes or it is just buggy. As for webRTC, I used to use it and I removed it. Why is it still showing up?? This seems like another case similar to "browser-mod" that haunted me for months after removing it as the system thought it should still be there and was giving errors related to it.

<img width="464" alt="image" src="https://github.com/home-assistant/frontend/assets/4006944/33464ce8-e3f1-4fad-a5e6-2fbd6c43531b">

Edit: I did try to migrate this to the new sectional view but it breaks the layout (minimum card height not respected) and the spacing between rows and columns is off.

Edit2: I removed webrtc from lovelace.resources and the error is no longer there. I reloaded the dashboard many times until the issue happened again and there were no errors so I am guessing they were unrelated.

**Comment by piitaya** [comment]
Hi 👋 Can you provide the yaml of your view? I'm unable to reproduce it.

**Comment by karwosts** [comment]
This sort-of feels related to what I thought I fixed with https://github.com/home-assistant/frontend/pull/19861, but that went into the May release, not the current beta.

**Comment by alexruffell** [comment]
@piitaya The issue seems to only happen on Chrome, not FF. While I have not used FF extensively, it is happening so often on Chrome that I would have expected to see it at least once on FF even with little use. Also, the issue is not specific to any particular view/dashboard. I've had it happen even in views that only have 2 vertical stacks.

How can I share a view? When I go into the raw editor there are 12k lines of YAML so it is all the 21 views for my main dashboard (4 dashboards). Is there any sensitive data in the dashboard YAML such as passwords, IPs, etc? For example, I've seen my IP cameras password in clear text in HA logs, just not sure whether it also appears in the dashboard YAML for example.

@karwosts - I took a look at the issue you referenced and to my untrained eye it would appear to be the same issue, or related. In case it helps, at times cards appear to get "stuck", meaning they don't load immediately. If this causes them not to report their size maybe it could be the same issue. Since the columns are pushed down, I can't see the cards and thus don't know whether they loaded or not when the issue happens (if I scroll down they could have loaded by the time I do so but I will try).

**Comment by alexruffell** [comment]
@piitaya @karwosts Here is a video of the issue: 

https://youtu.be/EIfRMPtUQxY

**Comment by 0rangutan** [comment]
My Vertical Stack layouts are broken in the same manner by 2024.6.
Good to see that it is a known issue.

**Comment by piitaya** [comment]
Also, if you like a column based dashboard, you can give a try to [section view](https://www.home-assistant.io/dashboards/sections/). It doesn't have this issue because you decide where the columns and card go.

**Comment by alexruffell** [comment]
@piitaya I have about 50 views and many use vertical stacks so I am waiting on the sections view to be more mature before I get myself into trouble. Also, my main view doesn't work well with the new sections view. I have tested it to see if it resolved the current issue but then never adopted it due to issues it appears to have with the height of cards. See the issue here:

https://youtu.be/on12Z38UQd0

**Comment by 500Foods** [comment]
2024.6 seems to have broken my vertical stacks. I just have one vertical stack and use the type: custom:layout-break card to break that up into 8 stacks across the page. But the breaking isn't happening, so it ends up as one really long vertical stack. Not so useful.

I took this as an opportunity to check out sections, but I can't figure out how to change the section width (doesn't even have to be per section, just make all the sections a bit wider?), so that isn't going to work particularly well at the moment either.

**Comment by sbochnak** [comment]
Hi,
my vertical stacks and custom:layout-break got broken too - everything is displayed in one column only. On iPhone one cannot notice, on iPad or on desktop - hard to miss. In all cases it if Safari browser.

As a test - I did rewrite (I have UI in YAML) one dashboard to section style - and it works much better, though not without problems yet so I will delay moving to sections views till they get improved.

BR,
Stan

**Comment by piitaya** [comment]
For issue about layout card, please look at layout card repository as it's a custom view, not a built-in view. This open issue is for the masonry view from HA.

There are some issues open in layout card repo : 
- https://github.com/thomasloven/lovelace-layout-card/issues/291
- https://github.com/thomasloven/lovelace-layout-card/issues/290

With `2024.6` card are now wrapped with a `hui-card` so the layout card custom card needs to support that.

On my side, I'm looking for the built-in masonry view issue.
