### ISSUE TITLE
Color Temperature Selector - inverted slider

### ISSUE THREAD

**Issue by SirYasko** [home-assistant/frontend#21002]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I've created blueprint with 2 inputs - color_temp selectors.
The first one works fine, but I wanted to swap colors on the frontend (warmer on the left) , so I swapped the min and max values. The colors have changed correctly but the default value and slider do not work

![image](https://github.com/home-assistant/frontend/assets/66648865/279481c3-c112-4a73-a682-4a8ad199b2fd)

`
blueprint:
  name: SirYasko's Test
  description: "selector color_temp"
  domain: automation
  author: SirYasko
        
  input:  
    i__color_1:
      name: Slider works - default 300
      description: Can move slider
      default: 300
      selector:
        color_temp:
          min: 153
          max: 500
          unit: "mired" 
          
    i__color_2:
      name: Slider does not work - default 300
      description: Can not move slider, default value not set
      default: 300
      selector:
        color_temp:
          min: 500
          max: 153
          unit: "mired" 
        
mode: restart
max_exceeded: silent
  
trigger:
- platform: event
  event_type: zha_event

action:
`

### Describe the behavior you expected

It should work like the first selector, but with the colors swapped - looks OK

### Steps to reproduce the issue

1. Create blueprint 
2. Add input selector color_temp: 
3. set min: 500 and max: 153
4. set default: 300
5. try to move slider on frontend

### What version of Home Assistant Core has the issue?

core-2024.5.5

### In which browser are you experiencing the issue with?

Google Chrome 125.0.6422.78 

### Which operating system are you using to run this browser?

Windows 10 Pro x64

**Comment by karwosts** [comment]
The max cannot be less than the min. If you want to invert the direction of the color gradient, I think the only option may be to use `unit: kelvin`

**Comment by SirYasko** [comment]
I understood, but why? After all, it inverts the gradient so why wouldn't it work - it's just a number range and a value.
