### ISSUE TITLE
Schedule helper no longer editable from UI

### ISSUE THREAD

**Issue by tomlut** [home-assistant/frontend#21005]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Existing schedules can no longer be edited correctly via the UI after updating to 2024.6.0.

New times can not be added.

Existing times can be deleted. 

Apparently this applies to newly created schedules too, see: https://community.home-assistant.io/t/schedule-unable-to-add-or-edit-anything-in-the-week-grid/736475

### Describe the behavior you expected

The ability to edit schedule helpers in the frontend by marking the daily time slots in the UI.

### Steps to reproduce the issue

1. Update to 2024.6.0
2. Attempt to edit a schedule helper by adding times. 
3.
...

### What version of Home Assistant Core has the issue?

core-2024.6.0

### What was the last working version of Home Assistant Core?

core-2024.5.5

### In which browser are you experiencing the issue with?

Firefox 126.0.1, Chrome 125.0.6422.142

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
Looks broken by #20869, it's fixed if I revert.

**Comment by Brazier85** [comment]
Same problem here!

**Comment by PatrickEekhout** [comment]
Same here, unfortunately.

**Comment by jul-fls** [comment]
Same problem here !

**Comment by Manic-Marley** [comment]
I'm having the same issue, tried on my laptop and iPhone and still can't select day or times, it just automatically highlights the whole day it's currently on

**Comment by blindeslakkie** [comment]
I have the same issue.
Is there any work around other than downgrading?

**Comment by tomlut** [comment]
Considering Bram has a fix in for this (look directly above your comment) I suspect it will be in the next patch release (2024.6.2).

**Comment by blindeslakkie** [comment]
Thank you, issue resolved after updating to 2024.6.2

**Comment by intuitiv-de** [comment]
Thank You. Works again.

**Comment by blindeslakkie** [comment]
Hi, looks like this is broken again.
Seems like every other release this stops working. Can this be tested before a release?

**Comment by tomlut** [comment]
Still working here. Same versions as you. Which web browser are you using?

Have you tried clearing your web browser cache?

Have you tried another web browser?

**Comment by blindeslakkie** [comment]
Apologies, cleared cache etc and it is working again.
