### ISSUE TITLE
Error while loading page lovelace. on 2024.6.0 was fixed #20741 previously

### ISSUE THREAD

**Issue by remoteassist** [home-assistant/frontend#21004]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Error - `"error while loading page lovelace"`

Issue exists on:

- the HA Companion app (2023.12.1) on an old ipad running iOS 12.5.7 (max for the iPad)

Issue does not exist on:

- the HA Companion app on new android tablet
- last version of 2024.5.x

### Describe the behavior you expected

To use the UI as per normal

### Steps to reproduce the issue

1.Upgrade to 2024.6.0
2.Logging into old ipad running iOS 12.5.7
see https://github.com/home-assistant/frontend/issues/20697 for previous issue 
...

### What version of Home Assistant Core has the issue?

2024.6.0

### What was the last working version of Home Assistant Core?

latest 2024.5.x

### In which browser are you experiencing the issue with?

home assistant companion 2023.2

### Which operating system are you using to run this browser?

iOS 12.5.7

**Comment by ccmacaluso** [comment]
Having this same issue on my Fire tablets used as dashboards around the house.

**Comment by rlause** [comment]
same issue on Galaxy S23+ (current Android and patches) and Galaxy Tab 9 (current Android and patches), starting with 2024.5 as far as I can remember
normal (user) dashboards work fine, settings won't work and show a page loading error

**Comment by ekkridon** [comment]
Same issue using Kiosker kiosk browser or iPad Safarai browser on an older iPad.  Error loading page on all pages after sign-in.

**Comment by apeiron69** [comment]
I have the same issue on iPad with 13.5.7 iOS and 2024.6.0 HA core installed. Lovelace no longer loads.

**Comment by steveworkman** [comment]
+1 - HAR file available for debugging in the duplicate bug #21015

**Comment by Madi0ne** [comment]
I am facing the same issue on iPad mini 2 (iPadOS 12.5.7) on 2024.6.0

**Comment by matorres86** [comment]
Same on older ipad mini, I kept this tablet specifically to access the HA app and not have another electronic device end up in a landfill. I hope they fix it.

**Comment by cayco** [comment]
Same here on old iPad Air

**Comment by oklih** [comment]
I have the same problem. After update to 2024.6.0. Before with the latest 2024.5.x it was no problem

**Comment by shovelheadman** [comment]
Same problem on old iPad - had to revert to a 2024.5.5 backup to be able to use my dashboard again.

**Comment by slipx06** [comment]
I can confirm this problem has started appearing on the IOS companion app after the last update

**Comment by OzMike63** [comment]
Sadly 2024.6.1 patch did not fix this.....roll back time again!

**Comment by deltazerorsan** [comment]
> Sadly 2024.6.1 patch did not fix this.....roll back time again!

Tx! So waiting...

**Comment by luq555** [comment]
After upgrade to 2024.6.1 

![WhatsApp Image 2024-06-08 at 14 07 44](https://github.com/home-assistant/frontend/assets/5399247/416e79f1-e815-4692-91c5-a1fe58ef5643)

<img width="667" alt="image" src="https://github.com/home-assistant/frontend/assets/5399247/126478e9-7bcf-4c43-97fa-cb1903a9970b">

**Comment by pichel3000** [comment]
I hope this gets a fix in upcoming patches.

**Comment by silamon** [comment]
If anyone could post the stack trace, similar to what was done in #20697, that would be helpful.

**Comment by apeiron69** [comment]
Ho do I acquire it from HA?

Il dom 9 giu 2024, 13:09 Simon Lamon ***@***.***> ha scritto:

**Comment by steveworkman** [comment]
> If anyone could post the stack trace of the error, similar to what was done in #20697, that would be helpful.

See #21015 for a HAR from my iPad mini

**Comment by ptfuzi** [comment]
Also had to downgrade to 2024.5.5

**Comment by ljsquare** [comment]
@steverep  , Could this be the same problem as before? Then the fix would be easy, wouldn't it?

**Comment by deltazerorsan** [comment]
> > If anyone could post the stack trace of the error, similar to what was done in #20697, that would be helpful.
> 
> See #21015 for a HAR from my iPad mini

Here you have my best...
![photo_2024-06-10_20-54-47](https://github.com/home-assistant/frontend/assets/53981858/78ec3ce3-44ed-44d0-a13c-d089858a5ddb)

**Comment by apeiron69** [comment]
Confirm, I'm on 2024.6.2 and still getting this error on iOS 12.5.7

**Comment by steverep** [comment]
Folks, I can look into this, but from a volunteer developer perspective, it would be helpful if:

1. Please paste the actual full text of the error and stack trace from the browser console (not a screenshot or zip file which just it harder or impossible to read and search for easily).  There's a reason our template asks for it when opening an issue and @silamon followed up asking for the same.  It pinpoints the exact lines in the code to debug.
2. Please avoid comments that just confirm the issue and don't contribute new information.  It's just more fluff for newcomers just arriving to the issue.  Just give the OP a thumbs up and subscribe to the issue instead.

**Comment by lispington** [comment]
2024-06-11 17:53:22.607 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [140410064355392] from 192.168.0.1 (Mozilla/5.0 (iPad; CPU OS 12_5_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148): Disconnected: Did not receive auth message within 10 seconds

No other messages or stack traces in the log, just plenty of these, when I refresh the iPad. I hope this adds something.

**Comment by steverep** [comment]
@lispington thank you for the text, but we're looking for the error and trace from the browser, not from the HA core log.  Try to open in the browser, press F12 to get the console, and the error(s) should be there.

**Comment by steveworkman** [comment]
> @lispington thank you for the text, but we're looking for the error and trace from the browser, not from the HA core log. Try to open in the browser, press F12 to get the console, and the error(s) should be there.

Here is the har file https://github.com/user-attachments/files/15685653/homeassistant.local.webarchive.zip

**Comment by steverep** [comment]
@steveworkman I get errors trying to load it.  Again, just the text of the error and stack would be appreciated.

**Comment by rlause** [comment]
I'm not sure if the reason for my error is the same, however...
2024.6.2 still shows `Error while loading page dashboard.` on a current Android (Samsung Galaxy S23+, Galaxy Tab 9) when using
- Home Assistant app
- Chrome
- Firefox 
All other dashboards (even the HA developer tools dashboard) work.
The settings dashboard is presented correctly using Chrome on a Windows 11 desktop.
Unfortunately the Android browsers don't have a developer mode. If anybody has an idea how to capture debug messages, stack traces or similar helpful output, please tell me.

**Comment by silamon** [comment]
For what it is worth, the error from the screenshot written in text: 
"Error loading page lovelace TypeError: (0, n.CoerceOptionsToObject) is not a function (In '(0, n.CoerceOptionsToObject)(e)','(0, n.CoerceOptionsToObject)' is undefined)"

**Comment by steveworkman** [comment]
> @steveworkman I get errors trying to load it. Again, just the text of the error and stack would be appreciated.

If I recall (as I'm on my phone) the error is that it is trying to load files from `http://homeassistant.local:8123/undefined/node_modules/some/file/that/doesn't/exist`

**Comment by silamon** [comment]
The webarchive you posted only included the web calls, which unfortunate don't contain any errors / stack traces. Still, we appreciate it a lot you're helping out finding the cause. 👍

**Comment by steverep** [comment]
> For what it is worth, the error from the screenshot written in text: "Error loading page lovelace TypeError: (0, n.CoerceOptionsToObject) is not a function (In '(0, n.CoerceOptionsToObject)(e)','(0, n.CoerceOptionsToObject)' is undefined)"

Thanks @silamon .  Yeah I already got that from running OCR on the image, but it's missing the file/line of the error and stack.  That narrows it down to something going on with loading the `@formatjs` `Intl` polyfills, but I don't know what specifically w/o the trace.

Another lesson I guess for folks, don't assume an issue is the same as another unless the errors and traces match.  This is not the same as #20697 at all.



> If I recall (as I'm on my phone) the error is that it is trying to load files from `http://homeassistant.local:8123/undefined/node_modules/some/file/that/doesn't/exist`


That's just an error from the debugger trying to load original source files from the source maps.  We purposefully don't ship them with the frontend.  It has nothing to do with the problem at hand.

**Comment by steverep** [comment]
@piitaya can you repro this on iOS 12 with stack as you did before?  I don't have the hardware to do it.  Based on the info so far, I suspect I need to tweak something from #20798.

**Comment by deltazerorsan** [comment]
> @piitaya can you repro this on iOS 12 with stack as you did before? I don't have the hardware to do it. Based on the info so far, I suspect I need to tweak something from #20798.

Hi steverep,

I have up and running a VM with 2024.6.2 and an Ipad 12.5.7 so I can reproduce the issue but the only thing I can capture is a screenshot of the Javascript console.

If you know something better please guide me and I do my best to help.

**Comment by nickcmaynard** [comment]
Folks,

This is what I have from a remote debug session to an iPhone running iOS 12.5.7.


```
[Error] Unhandled Promise Rejection: SyntaxError: Unexpected token '.'
	(anonymous function)
	rejectPromise
	promiseReactionJob

[Error] Error loading page – "lovelace"
TypeError: (0,n.CoerceOptionsToObject) is not a function. (In '(0,n.CoerceOptionsToObject)(e)', '(0,n.CoerceOptionsToObject)' is undefined)
a — index.js:309
y — utils.js:95
(anonymous function) — utils.js:151
forEach
(anonymous function) — utils.js:147
forEach
(anonymous function) — utils.js:143
m — BestFitMatcher.js:18
L — ResolveLocale.js:15
A — index.js:4
(anonymous function) — intl-polyfill.ts:24
h — regeneratorRuntime.js:45
(anonymous function) — regeneratorRuntime.js:133
r — asyncToGenerator.js:3
s — asyncToGenerator.js:17
promiseReactionJob
	(anonymous function) (app.HklW542yG5A.js:2:98761)
	promiseReactionJob

[Error] Unhandled Promise Rejection: TypeError: (0,n.CoerceOptionsToObject) is not a function. (In '(0,n.CoerceOptionsToObject)(e)', '(0,n.CoerceOptionsToObject)' is undefined)
	(anonymous function) (app.HklW542yG5A.js:2:328171)
	map
	a (app.HklW542yG5A.js:2:328139)
	(anonymous function) (45959.ZjjpSmFaFnU.js:1:35629)
	h (app.HklW542yG5A.js:2:268946)
	(anonymous function) (app.HklW542yG5A.js:2:270291)
	r (app.HklW542yG5A.js:2:255251)
	s (app.HklW542yG5A.js:2:255455)
	promiseReactionJob

[Error] Unhandled Promise Rejection: TypeError: (0,n.CoerceOptionsToObject) is not a function. (In '(0,n.CoerceOptionsToObject)(e)', '(0,n.CoerceOptionsToObject)' is undefined)
	(anonymous function)
	rejectPromise
	promiseReactionJob

[Error] Unhandled Promise Rejection: TypeError: (0,n.CoerceOptionsToObject) is not a function. (In '(0,n.CoerceOptionsToObject)(e)', '(0,n.CoerceOptionsToObject)' is undefined)
	dispatchException (app.HklW542yG5A.js:2:273130)
	(anonymous function) (app.HklW542yG5A.js:2:270222)
	r (app.HklW542yG5A.js:2:255251)
	c (app.HklW542yG5A.js:2:255491)
	promiseReactionJob

[Error] Unhandled Promise Rejection: TypeError: (0,n.CoerceOptionsToObject) is not a function. (In '(0,n.CoerceOptionsToObject)(e)', '(0,n.CoerceOptionsToObject)' is undefined)
	(anonymous function)
	rejectPromise
	promiseReactionJob

[Error] Unhandled Promise Rejection: TypeError: (0,n.CoerceOptionsToObject) is not a function. (In '(0,n.CoerceOptionsToObject)(e)', '(0,n.CoerceOptionsToObject)' is undefined)
	dispatchException (app.HklW542yG5A.js:2:273130)
	(anonymous function) (app.HklW542yG5A.js:2:270222)
	r (app.HklW542yG5A.js:2:255251)
	c (app.HklW542yG5A.js:2:255491)
	promiseReactionJob

[Error] Unhandled Promise Rejection: TypeError: (0,n.CoerceOptionsToObject) is not a function. (In '(0,n.CoerceOptionsToObject)(e)', '(0,n.CoerceOptionsToObject)' is undefined)
	(anonymous function)
	rejectPromise
	promiseReactionJob
```

**Comment by remoteassist** [comment]
![image](https://github.com/home-assistant/frontend/assets/115590002/04f2c7f6-2362-452c-a2af-dd12e07f6265)

**Comment by steveworkman** [comment]
<img width="378" alt="image" src="https://github.com/home-assistant/frontend/assets/994905/b1dfbce9-c876-42d1-b3d7-1995b6d9e389">

This is where the sourcemap resolves the error to the `@formatjs/intl-locale` package and it's looking for CoerceOptionsToObject which is provided by the `@formatjs/ecma402-abstract` package. I don't really understand why that wouldn't be there as [there's not much to it](https://github.com/formatjs/formatjs/blob/main/packages/ecma402-abstract/CoerceOptionsToObject.ts)

Its called from `var desiredLocale = new Intl.Locale(desired).maximize();` within `@formatjs/intl-localematcher/lib/abstract/utils.js` 

Futher down the stack it comes from this code in the `intl-polyfill`:
```js
  if (shouldPolyfillDateTimeFormat(locale)) {
    polyfills.push(
      import("@formatjs/intl-datetimeformat/polyfill-force").then(() =>
        polyfillTimeZoneData()
      )
    );
  }
```

**Comment by rarroyo6** [comment]
I have several Android tablets throughout the house running FullyKiosk, the tablets are running several different dashboards. As of 2024.6.0, some of the dashboards work on all the tablets, and the others don't work on any of the tablets. So there is something specific on some dashboards that is making them fail. All the dashboards use Browser-Mod and Custom Button Cards, everything else is pure HA.
I don't know how to get the log or the stack dump from FullyKiosk, so I can't help much more. But if someone can show me how to do it, I'll be happy to post it here.

**Comment by steveworkman** [comment]
Given that it's failing at `Intl.Locale()` and that #20798 the polyfill for Intl.Locale is now added for < iOS 14 it seems like that's the issue. I've got a debugger on it and it appears that the required ecma402-abstract library is still pending in a promise

<img width="1003" alt="image" src="https://github.com/home-assistant/frontend/assets/994905/a0f1b491-5160-4bdc-afb0-430c356c8dcd">

**Comment by steverep** [comment]
@nickcmaynard and @steveworkman that's the awesome info I needed.  I have some suspicions as to what's happening here but I won't be able to dig in until later tonight.  I think this is maybe a bug in the order we polyfill `Intl` that has been around for quite a while, but wasn't exposed until #20798.  That change basically will delay loading them until they are needed more so than before, so if the loading isn't perfect, errors would be expected.

**Comment by steverep** [comment]
Just a quick update.... I can reproduce the problem myself now, but still tracking down the root cause.  I'll pick it up again tomorrow.

**Comment by FA9US** [comment]
its not just ipad folks. it also seem to be affecting android. currently on Fuly remote admin.
Device info
px30_evb
by rockchip
Firmware: 1.50.1-play

**Comment by Maeckes89** [comment]
Same problem here. Also with latest update so far.

**Comment by steverep** [comment]
PR #21074 is in to fix this.  Should come in 2024.6.3.

**Comment by ekkridon** [comment]
Thank you for the work @steverep - sent a couple bucks your way to help in your efforts (which I now realize are broader and more amazing than this silly bug).  Kudos!

**Comment by matorres86** [comment]
Where do we donate, thank you so much!

**Comment by ekkridon** [comment]
Click his name and look for options to sponsor him. After reading about the cool accessibility work he's doing and feeling inferior for your own contributions to humanity.

**Comment by pvmil** [comment]
Thanks, found it, @steverep: thanks for your efforts!

**Comment by matorres86** [comment]
> Click his name and look for options to sponsor him. After reading about the cool accessibility work he's doing and feeling inferior for your own contributions to humanity.

Thank you, doing this now, it's so much appreciated, another device kept out of the landfills!

**Comment by sebastian3107** [comment]
Thanks a lot. Were some unit tests added so this bug doesn't show up a third time? 🧪

**Comment by jaymunro** [comment]
> Thanks a lot. Were some unit tests added so this bug doesn't show up a third time? 🧪

I was thinking the same too, but wasn't sure how to word it. Maybe to clarify, although these were "technically" different bugs, but main issue is that some of OS's are not being tested against. 

I hope this doesn't end up with older devices becoming unsupported. They are so useful for kiosk type uses.

**Comment by steverep** [comment]
> Thanks a lot. Were some unit tests added so this bug doesn't show up a third time? 🧪

As I said above, although the symptom looked the same, this was not a second regression of the same bug.  The first was an error in a dependency that I maintain which is now tested.  This one is more difficult to test.

> I was thinking the same too, but wasn't sure how to word it. Maybe to clarify, although these were "technically" different bugs, the main issue is that some of OS's are not being tested against.

Actually, none are tested.  Lack of end to end testing is something I'm working on right now.

> I hope this doesn't end up with older devices becoming unsupported. They are so useful for kiosk type uses. Mine is in the kitchen on the fridge and used by the whole family.

There's no plan to drop such support, and developers are well aware of such uses.  These bugs happened because of optimizing our legacy browser build for better performance (so the opposite of dropping support).

**Comment by deltazerorsan** [comment]
2024.6.3 WORKING with iOS 12.5.7

**Comment by apeiron69** [comment]
Confirm, it’s working now.Thank youInviato da iPhoneIl giorno 16 giu 2024, alle ore 00:55, Rsan ***@***.***> ha scritto:﻿
2024.6.3 WORKING with iOS 12.5.7

**Comment by rlause** [comment]
An error still exists on up-to-date Android devices like Samsung Galaxy Tab 9 or Samsung Galaxy S23+. The settings dashboard shows `Error while loading page dashboard.` It doesn't matter wether I use Chrome, Firefox or the Home Assistant app for Android.

All other dashboards (even the developer dashboard) work well.

As I already pointed out there seems to be no possibility to track the problem down, as neither the browsers nor the Home Assistand app provide any messages, trace logs or similar.

**Comment by rlause** [comment]
> @rlause if you are only experiencing a problem loading the Settings page and no others, then this is not the same issue. Please open a new one (or perhaps find another that better matches).

@steverep Fortunately, after an automatic reload of the frontend (Home Assistant app) this morning the settings dashboard works again (after a long time). Well, let me thank you for your efforts even if there is a chance that you are not responsible for this "sudden healing".

**Comment by aeonoea** [comment]
Anyone still experiencing issues with the homepage? I get the same error `Error while loading page lovelace.` on HA 6.4 (20240610.1) on Safari running on the latest iOS Beta. Everything else seems to work, it's just the homepage.
