### ISSUE TITLE
sonos not planning  Sonos favorites

### ISSUE THREAD

**Issue by wimweiss** [home-assistant/frontend#21019]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After I upgraded the Sonos app, Ann error message apears when I select a Sonos favorite station to be started. Error 402, invalid args from 192.168.x.x

### Describe the behavior you expected

Station should be started

### Steps to reproduce the issue

Install sonos app and use standard integration and ui
2.
3.
...

### What version of Home Assistant Core has the issue?

core

### In which browser are you experiencing the issue with?

google

### Which operating system are you using to run this browser?

android

### Problem-relevant frontend configuration

```yaml
Not applicatie
```

**Comment by silamon** [comment]
Consider reading [this issue](https://github.com/home-assistant/core/issues/117703). If that doesn't help, open a new issue at the [core repository](https://github.com/home-assistant/core) and tag the sonos integration.

**Comment by wimweiss** [comment]
Thx Sinon, this helpen. The favorit was not in the Sonos app anymore.

Rgs Wim

⁣BlueMail voor Android downloaden ​

Op 9 jun 2024 13:00, om 13:00, Simon Lamon ***@***.***> schreef:
