### ISSUE TITLE
Tuya Smart no longer Authorized, and Tuya reports HA generated Auth QR code is expired

### ISSUE THREAD

**Issue by HowdyKeith** [home-assistant/frontend#21013]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Tuya Smart no longer Authorized, and Tuya reports HA generated Auth QR code is expired

### Describe the behavior you expected

Before the update, was normal.

![QR_err](https://github.com/home-assistant/frontend/assets/105569003/99679f42-98b5-42ef-aae1-c04e0953b608)

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.6.0

**Comment by karwosts** [comment]
Please report your integration issues in `core` repo, frontend does not handle tuya authorization.
