### ISSUE TITLE
Azure data explorer integration doesn't have labels for all boxes

### ISSUE THREAD

**Issue by i-am-shodan** [home-assistant/frontend#21010]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

- What is the first text box for?
- What is the tick box for?

![image](https://github.com/home-assistant/frontend/assets/6901273/14db7132-6bd3-4eb1-b5f2-c4f53a94606b)

### Describe the behavior you expected

Labels

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.6.0

### In which browser are you experiencing the issue with?

Edge

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment]
If this is only an issue with one specific integration, that would need to be filed as a core issue for that integration. All the strings come from there.

**Comment by silamon** [comment]
Thank you for creating the [issue](https://github.com/home-assistant/core/issues/118991). This issue will be closed, since there's nothing left to do for the frontend repository.
