### ISSUE TITLE
Edit Sections dialog - cancel button doesn't work

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#21025]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When editing a section, the cancel button does nothing when clicked (on both settings and visibility tabs)

<img width="620" alt="Screen Shot 2024-06-07 at 1 21 23 PM" src="https://github.com/home-assistant/frontend/assets/9065557/e1575651-dd15-4f8d-9ca7-65a3a41e552b">

### Describe the behavior you expected

Cancel changes and close the edit section dialog

### Steps to reproduce the issue

1. Have a view using Sections 
2. Click the pencil icon in a section to edit it
3. In the "Edit section dialog" press cancel, it will not do anything

### What version of Home Assistant Core has the issue?

2024.6.0

**Comment by husjon** [comment]
Just updated to 2024.6.1, saw the sections and found the same issue.
