### ISSUE TITLE
Value ON or OFF in dictionary cause error loading blueprint

### ISSUE THREAD

**Issue by SirYasko** [home-assistant/frontend#21027]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

![image](https://github.com/home-assistant/frontend/assets/66648865/0032dda2-c731-4d81-a2f2-cb6a8570df6c)

blueprint:
  name: Sir Yasko's Dropdown Test
  description: Value ON or OFF cause error loading automation
  domain: automation
  input:
    action:
      name: Action
      description: Select the action to perform
      selector:
        select:
          mode: dropdown
          options:
            - value: ON
              label: Turn On
            - value: OFF
              label: Turn Off

### Describe the behavior you expected

When you change OFF / ON value to eg: TURN_OFF / TURN_ON  everything works like a charm

### Steps to reproduce the issue

1. As above

### What version of Home Assistant Core has the issue?

core-2024.6.0

**Comment by karwosts** [comment]
This isn't a frontend issue, but try putting quotes around on/off. I believe yaml interprets those bare words as booleans, and not strings, which are expected.
