### ISSUE TITLE
NWS stopedworking after update 

### ISSUE THREAD

**Issue by MikeK12** [home-assistant/frontend#21030]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

NWS stoped working after update from 2024-5-5 to 2024-6-0 

### Describe the behavior you expected

weather is not getting updated

### Steps to reproduce the issue

1.update to core-2024.6.0
2.rolled bacj to 2024.5.5
3.update to core-2024.6.0
4. update to core-2024.6.1 do not fix issue

...

### What version of Home Assistant Core has the issue?

core-2024.6.1

### What was the last working version of Home Assistant Core?

core-2024.5.5

### In which browser are you experiencing the issue with?

Google Chrome Version 125.0.6422.141 

### Which operating system are you using to run this browser?

widndows 11, Linux Mint, windows 10

### Additional information

rolling back to core-2024.5.5 fixes issue.

**Comment by karwosts** [comment]
Please file in home-assistant/core for NWS integration, not frontend.
