### ISSUE TITLE
Theme variable box-shadow / ha-card-box-shadow doesn't work with Dashboard view type 'panel'.

### ISSUE THREAD

**Issue by ASNNetworks** [home-assistant/frontend#21038]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When using the view type `panel` the theme variable `box-shadow` or `ha-card-box-shadow` doesn't work. So none of the cards have a box-shadow like declared in the theme.yaml Using inspect element you can add it manually. But for some reason Dashboard ignores box-shadow now. When changing the view to any other type, like `masonry` it all works again.

### Describe the behavior you expected

Panel type should still work with `box-shadow` variabel.

### Steps to reproduce the issue

1. change view type to `panel`
2. all box-shadows from cards are gone
3. change it to any other view type and it works as intended

### What version of Home Assistant Core has the issue?

2024.6.1

### What was the last working version of Home Assistant Core?

2024.3.x (last I tested ,skipped .4 and .5 releases)

### In which browser are you experiencing the issue with?

Edge, Chromecast (Desktop), HA Android app, HA MacOS app

### Which operating system are you using to run this browser?

macOS 14.5 (23F79) / Android 14

**Comment by ildar170975** [comment]
Starting from some recent updates (check https://github.com/home-assistant/frontend/pull/20122, https://github.com/home-assistant/frontend/pull/20135, https://github.com/home-assistant/frontend/pull/20264), a card on a panel view does not have `border-radius`, `border-width`, `box-shadow`.
Check this code:
https://github.com/home-assistant/frontend/blob/42b5fa696a8be5bac70e11bb959b0880d1dfd691/src/panels/lovelace/views/hui-panel-view.ts#L136

But for inner cards inside stack-like cards these variables still work:
```
type: entity
entity: sun.sun
card_mod:
  style: |
    ha-card {
      --ha-card-border-radius: 30px;
      --ha-card-border-width: 4px;
      --ha-card-box-shadow: 5px 5px 8px red, 10px 10px 8px green, 15px 15px 8px blue;;
    }
```
![изображение](https://github.com/home-assistant/frontend/assets/71872483/82d2885c-78e2-4270-b8fa-fd5c64151085)

**Comment by ASNNetworks** [comment]
Thanks for pointing out the changes. I get that in panel view the main card doesn't need a shadow, but the nested cards now also don't have shadows this way. I mean, I kinda get it, I guess panel view's intention is to actually just have one card. But a lot of people that use panel view, use that to create dashboards that fit the screen better.

So the options are basically: use card-mod for literally any cards you have (which is a complete mess of a job to maintain with changes, chances on performance issues) or think of a new approach and stop using panel view.

Well that sucks lol. But thank you for your explanation and links. Seems this is sadly the way forward and not a bug.

**Comment by ildar170975** [comment]
> but the nested cards now also don't have shadows this way

I think I see your point.
In my code & screenshot above you can see shadows applied since we defined variables for a particular card by card-mod.
But w/i card-mod it does not work.
How to reproduce:
1. Add a card on a panel view:
```
type: vertical-stack
cards:
  - type: entity
    entity: sun.sun
```
2. Define a theme:
```
test_minimal:
  ha-card-border-radius: 30px
  ha-card-border-width: 4px
  ha-card-box-shadow: 5px 5px 8px red, 10px 10px 8px green, 15px 15px 8px blue
```
3. See that all styles are applied - except shadow:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/1823fafe-42c8-43c0-9d08-6e961ea6667e)

4. See that shadow is applied only in a masonry or in Editor:
![изображение](https://github.com/home-assistant/frontend/assets/71872483/177e01ca-156c-4b83-9ac7-8ea04b2f1489)

**Comment by ildar170975** [comment]
I think there is an error here:
https://github.com/home-assistant/frontend/blob/42b5fa696a8be5bac70e11bb959b0880d1dfd691/src/panels/lovelace/views/hui-panel-view.ts#L133
Here it is used "--restore-card-box-shadow", but in other place it is defined as "--restore-card-border-shadow".
