### ISSUE TITLE
Android Navigation Back gesture activates buttons on dashboard

### ISSUE THREAD

**Issue by dbaq** [home-assistant/frontend#21042]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

There is a [long thread](https://github.com/home-assistant/android/issues/3565) (with reproducing steps, some troubleshooting, and even a solution) on the https://github.com/home-assistant/android repo but it looks like it is a home-assistant/frontend issue.

The android back gesture seems to activate the button which is present below the trace of the finger while performing the gesture (on finger lift-off).
This is not the case for other apps I tested (e.g outlook, twitter, calculator, etc), therefore it seems to be an issue with the app.

Could this please be prioritized as it is impacting all Android users that have Android gestures enabled?

Thank you.

### Describe the behavior you expected

Starting the swipe back gesture should not "activate" any cards.

### Steps to reproduce the issue

[See this https://github.com/home-assistant/android/issues/3565 and this specific comment
](https://github.com/home-assistant/android/issues/3565#issuecomment-1696064752)

### What version of Home Assistant Core has the issue?

2024.4.0

**Comment by metheos** [comment]
Would love if this was fixed. I just started using HA this year and find myself diving deep into customizing my dashboards every day!
I've had to avoid using subviews because of this issue, they're too hard to navigate out of with the back gesture getting 'caught' on dashboard elements.

**Comment by milnivlek** [comment]
This really needs to be fixed. I have a subview for light controls, and keep triggering lights accidentally while swiping to go back to the main view. Just last night, I accidentally turned on the nursery light while my baby daughter was sleeping. Please fix this for the sake of the next generation!

**Comment by strikeir13** [comment]
I encountered this recently when I changed some mushroom cards to tile cards. It is much, much more difficult to cause the false trigger when using mushroom cards than using tile cards. Maybe it's related to the fact that the tile card allows for different actions to be taken when tapping the icon vs the card itself (outside the icon), whereas mushroom does not.

**Comment by dbaq** [comment]
> I encountered this recently when I changed some mushroom cards to tile cards. It is much, much more difficult to cause the false trigger when using mushroom cards than using tile cards. Maybe it's related to the fact that the tile card allows for different actions to be taken when tapping the icon vs the card itself (outside the icon), whereas mushroom does not.

I am using mushroom cards (latest version) exclusively and still face the issue very frequently on my end.

**Comment by Lackmake** [comment]
There is a potential fix in the android issue thread mentioned above, just nobody able to setup the whole dev/test suite.
https://github.com/home-assistant/android/issues/3565#issuecomment-1906393991

**Comment by mattyway** [comment]
I tried debugging the code in [`action-handler-directive.ts`](https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/common/directives/action-handler-directive.ts) in Chrome running on an Android 15 device while intentionally triggering the bug. 

From what I can tell, when the `touchcancel` event is triggered, the [event handler on the element](https://github.com/home-assistant/frontend/blob/c7dae49c4204f8267a6983b343242017c92e6a1a/src/panels/lovelace/common/directives/action-handler-directive.ts#L150:L184) is being triggered before the [event handler that sets the cancelled field to true](https://github.com/home-assistant/frontend/blob/c7dae49c4204f8267a6983b343242017c92e6a1a/src/panels/lovelace/common/directives/action-handler-directive.ts#L73). So when the first event handler is triggered, the cancelled field is false so the early return is not triggered, and the handler proceeds as if a normal (ie. not cancelled) event occurred.

Treating a `touchcancel` event as a normal `touchend` event seems to perfectly explain what is happening with this bug.

I think the [proposed fix](https://github.com/home-assistant/android/issues/3565#issuecomment-1906393991) of ignoring the cancelled field for `touchcancel` events is correct. I will rebase the fix and open a PR.
