### ISSUE TITLE
August Home integration...

### ISSUE THREAD

**Issue by rggarner** [home-assistant/frontend#21055]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

This is in my log...Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:766 
integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22)) 
First occurred: 9:16:33 AM (2 occurrences) 
Last logged: 9:16:33 AM

Platform august does not generate unique IDs. ID 2D1CB798BF914F12BABC5A55865BAE06_device_battery already exists - ignoring sensor.garage_walk_in_door_battery
Platform august does not generate unique IDs. ID 2D1CB798BF914F12BABC5A55865BAE06_lock_operator already exists - ignoring sensor.garage_walk_in_door_operato

### Describe the behavior you expected

Removed august entry from config. yaml and used August Home integration.  This is the result.

### Steps to reproduce the issue

1.Removed august entry from config.yaml
2.Replaced with August Home Integration
3.
...

### What version of Home Assistant Core has the issue?

2024 6.1

**Comment by karwosts** [comment]
Please open this issue in home-assistant/core, this is not related to frontend.
