### ISSUE TITLE
Failed to format translation for key 

### ISSUE THREAD

**Issue by Anto79-ops** [home-assistant/frontend#21054]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

hello,

when I input my password for the Opower integration (with Enmax), it sucessfully accepts the password but this error gets logged

```
Logger: frontend.js.latest.202406050
Source: components/system_log/__init__.py:333
First occurred: 6:03:10 AM (4 occurrences)
Last logged: 6:03:21 AM

Failed to format translation for key 'component.opower.config.step.reauth_confirm.title' in language 'en'. Error: The intl string context variable "name" was not provided to the string "Authentication expired for {name}"
```

### Describe the behavior you expected

error gets logged, but still works

### Steps to reproduce the issue

1.just put password for Opower when it expires
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.6.1

### What was the last working version of Home Assistant Core?

not sure

### In which browser are you experiencing the issue with?

Google Chrome

### Which operating system are you using to run this browser?

Windows

**Comment by silamon** [comment]
Consider filing an issue against the https://github.com/home-assistant/core repository, more specifically for the opower integration, since the translation is maintained in that repository.

**Comment by Joao-Sousa-71** [comment]
I had that issue as weel and the problem was that in some automation actions had "service_template" and need to be changed by just "service".
