### ISSUE TITLE
Workday: UI explanation discrepancy

### ISSUE THREAD

**Issue by thatso** [home-assistant/frontend#21051]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The UI explanation of the `Workday` integration (UI itself and also [the documentation)](https://www.home-assistant.io/integrations/workday) reads:
"List of workdays to exclude, notice the keyword `holiday` and read the documentation on how to use it correctly"
while the pull-down selection entry is labeled `Holidays`.

### Describe the behavior you expected

Explanation and actual selection should be identical to avoid confusion.

### Steps to reproduce the issue

1. Open the `Workday` configuration dialogue UI.
2. Read the explanatory note.
3. Select the corresponding element in the pull-down menu.

### What version of Home Assistant Core has the issue?

2024.6.1

**Comment by silamon** [comment]
Consider to open an issue at https://github.com/home-assistant/core and label it for the workday integration. This is the issue tracker for frontend issues, and we leverage the workday descriptions provided by the core repo.
