### ISSUE TITLE
Cannot configure webhook URL 

### ISSUE THREAD

**Issue by TonyMontuna** [home-assistant/frontend#21056]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

My Smarthings integration has been failing for a few updates, I assumed it would be worked out but as I dive into the issue it's apparent that it's not. 

I disabled the integration then reenabled it but that didn't solve the issue.

I deleted and reinstalled the integration but when I try to reconfigure it, the webpage hook does not work. and I get this error. 

```
This site can’t be reached
The webpage at https://hooks.nabu.casa/gAAAAABmZw9iMhZqQJqaNii6DXuJP1KDQRtswCPoLwL0ZJMA6ChASwmFTvgfviiacWCwiIM4of9kd7rpyLCluprmhMOEH1I4zW2as5FJtvTg6W5HO9jqKeUHml8PXEzXFHSGXA7GSur2hgpSHCf_nn1z1h-FZy2t2_2diT6B6XAri7h3hgHX79U= might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE
```

I tried clearing my cache, hard reloading, and using incognito mode but did not find a way to get the url to work. 

In my logs, I get the following errors 

`2024-06-10 10:23:05.807 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Home for smartthings
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/smartthings/__init__.py", line 135, in async_setup_entry
    token = await api.generate_tokens(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pysmartthings/smartthings.py", line 209, in generate_tokens
    result = await self._service.generate_tokens(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pysmartthings/api.py", line 424, in generate_tokens
    raise APIInvalidGrant(data.get("error_description"))
pysmartthings.errors.APIInvalidGrant: Invalid refresh token: 79f6af8c-8451-437d-906c-1003ce11f926 requested by clientId: 86ad81e0-a6a8-47fb-ad24-497ccc53d586 with grantType: refresh_token, e.cause: no cause
`

### Describe the behavior you expected

I expected to go to the webpage and reconfigure the integration 

### Steps to reproduce the issue

1. settings 
2. smartthings config
3. setup 
...

### What version of Home Assistant Core has the issue?

core-2024.6.1

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

Windows 10

**Comment by silamon** [comment]
Consider filing an issue against the https://github.com/home-assistant/core repository for the smartthings integration. This issue tracker is for frontend issues related to Home Assistant, but reading the issue, it looks more like a specific smartthings integration error.

**Comment by mysterious1818** [comment]
My smartthings integration stopped working as well as of yesterday.
