### ISSUE TITLE
Device selector with filter removes devices without entities

### ISSUE THREAD

**Issue by Bre77** [home-assistant/frontend#21060]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The device selector with an integration filter does not show devices created by the specified integration if they have no entities.

### Describe the behavior you expected

The device selector has two configuration variables, `entity` and `filter`. 

When using `filter` I expect to be able to filter devices regardless if the device has associated entities or not.

When using `entity` I expect devices with no entities to be filtered as they cannot possibly match the conditions.

### Steps to reproduce the issue

1. Create a custom service with a device selector and integration filter in `services.yaml`:
```yaml
selector:
  device:
    filter:
      - integration: teslemetry
```
2. Create a device with no entities in the integration:
```python
device = DeviceInfo(
  identifiers={(DOMAIN, str(site_id))},
  manufacturer="Tesla",
  configuration_url="https://teslemetry.com/console",
  name=product.get("site_name", "Energy Site"),
  serial_number=str(site_id),
)

device_registry.async_get_or_create(
  config_entry_id=entry.entry_id, **device
)
```
3. Identify devices from the integration
![image](https://github.com/home-assistant/frontend/assets/2647914/78cfbd6f-a66e-4ee6-97f4-fa959c2feca7)

4. Use the device selector and observe a device is missing
![image](https://github.com/home-assistant/frontend/assets/2647914/ba4692c0-a826-4d59-977a-da6104821659)

...

### What version of Home Assistant Core has the issue?

2024.7.0.dev0

### In which browser are you experiencing the issue with?

Google Chrome 125.0.6422.141

### Which operating system are you using to run this browser?

Fedora Linux 40 (Workstation Edition)

### Additional information

Related to features for https://github.com/home-assistant/core/pull/119119

**Comment by karwosts** [comment]
Put up a PR to fix.
