### ISSUE TITLE
Web Dashboard - Freeze tabs

### ISSUE THREAD

**Issue by AudricSan** [home-assistant/frontend#21085]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since the last update 2024.6.2 on "Microsoft Edge Chromium," the interface freezes, making the "tab unresponsive" notification.

I've encountered this problem on several Chromium-based browsers except for Google Chrome (Opera, Edge, Brave...). Do you know what might be causing this and how to fix it?

### Describe the behavior you expected

not freezing.. 

### Steps to reproduce the issue

1. open web dashboard.
2. no more able to click anywhere, and a few secounds after browser popup "tab not responding" appeared

### What version of Home Assistant Core has the issue?

2024.6.2

### What was the last working version of Home Assistant Core?

2024.6.0

### In which browser are you experiencing the issue with?

Edge Chromium Version 126.0.2592.56

### Which operating system are you using to run this browser?

Windows 11 24H2

### Additional information

the bug not appeared on Google Chrome.

**Comment by genesispc** [comment]
I am seeing the same issue:
Microsoft Edge Version 125.0.2535.92 (Official build) (64-bit) on windows 11

**Comment by EpicLPer** [comment]
Same issue here since today, haven't had an issue the past few days despite updating to (2024.6.2).
I actually think this might be a Chromium Engine bug, but I'm not 100% certain.

DISCLAIMER: I'm neither a debugging guy nor a programmer, these are just my uneducated best guesses.

Going by the performance analysis in Edge it seems to be stuck at trying to process autofill information, further expanding the options below reveals it seems to try and detect if input fields are ready for autofill??? I'm not entirely sure... However I can consistently reproduce a ~20 second freeze whenever I load into the Helper page or my main dashboard.
![image](https://github.com/home-assistant/frontend/assets/8442196/eb84781d-a62c-4f75-a1f6-afedfb5ec5ac)
![image](https://github.com/home-assistant/frontend/assets/8442196/9a12b72b-ca84-4326-b0ac-c82e2b56fa42)

**Comment by ThePatricide** [comment]
For me it happens as well since today. I was on 2024.6.0 when it started. When I go directly to the local IP-address in Edge, all is well. On Android phone all is well. I tried updating to 2024.6.2 but to no avail. I've tried to reboot everything and clear caches to no avail. 
When accessing via domain (via Cloudflare and NGINX) it freezes after a second.

**Comment by caiphus2k22** [comment]
I have these issues since at least yesterday as well on Chrome 126.6478, 2024.6.2 and Frontend 20240610.0

Switching off the auto-fill function (or im my case the bitwarden extention to Chrome) does consistently solve the issue, switching it on again causes the issue to re-appear.

**Comment by ThePatricide** [comment]
> I have these issues since at least yesterday as well on Chrome 126.6478, 2024.6.2 and Frontend 20240610.0
> 
> Switching off the auto-fill function (or im my case the bitwarden extention to Chrome) does consistently solve the issue, switching it on again causes the issue to re-appear.

Can confirm the same workaround. Bitwarden is also the culprit here. Disabling it solves the freezing.

**Comment by sushain97** [comment]
I'm seeing this as well. I've started navigating directly to settings pages to avoid ever loading a dashboard.

Versions:
- Bitwarden 2024.6.0
- HA 2024.6.2
- Chrome 125.0.6422.142

@caiphus2k22 how did you disable Bitwarden's auto-fill to prevent this? I'd like to not entirely disable it (although that does fix things).

I have these settings and still experience the hang:

![image](https://github.com/home-assistant/frontend/assets/4211838/c7efd22d-e98f-4c34-a9bd-ddbee7909484)

**Comment by EpicLPer** [comment]
Can confirm it seems Bitwarden related, so this issue should be closed.

I've already mentioned them on Twitter to bring up the issue, I confirmed this by updating Bitwarden on Brave to 2024.6 (previously had 2024.5.something installed), now I also have the issue there.

**Comment by AudricSan** [comment]
a temporary solution seems to do this
default entry when loading => DEACTIVATE

![image](https://github.com/home-assistant/frontend/assets/29382102/7654deae-fb6c-4aa8-bbac-137326f82e75)

**Comment by AudricSan** [comment]
The source of the problem has been found, and a temporary solution has been identified. I am closing the issue.

**Comment by caiphus2k22** [comment]
@sushain97 - You should goto Chrome extension settings - you can disable Bitwarden there - not possible to do so w/i Bitwarden.

**Comment by birdwing** [comment]
Issue is being tracked on the bitwarden repository.
https://github.com/bitwarden/clients/issues/9617

**Comment by birdwing** [comment]
Turning off bitwarden's auto-fill doesn't seem to fix the issue for everyone.
Best workaround as of right now, is to Right click on the extension, mouse over "This can read and change site data" then change it to "When you click the extension".

![image](https://github.com/home-assistant/frontend/assets/6484397/81d40c36-44df-4c0f-bd4a-546556864238)

This will prevent the extension from loading on Home assistant, unless you click on it.
It solves the issue, and is way simpler to revert once Bitwarden fixes the issue.

**Comment by kspearrin** [comment]
Hi team. Kyle here from Bitwarden. I am also a homeassitant user. I use Brave browser and have not experienced this problem. Do you all have any further information on how I might reproduce the problem so I can get out engineers to look into how to fix it?

**Comment by johannes-z** [comment]
@kspearrin not all pages are hanging, e.g. the config page still works. Rolling back the extension from 2024.6.0 to 2024.5.2 also fixed the issue.

**Comment by birdwing** [comment]
@kspearrin 
It is also happening on: https://photoshop.adobe.com/id?learnid=7b050fa34872

So this isn't just a Home Assistant issue.
Someone in the thread (https://github.com/bitwarden/clients/issues/9617#issuecomment-2165798006) pointed out that it looks like bitwarden has an infinite recurse on Shadow dom elements. Which HA uses very heavily on dashboards.

This explains why the issue only happens on HA dashboards, but not on settings or config pages.

It also explains why it appears random on other websites as well. Shadow dom's aren't used all that often, so sites that do use them are affected.

**Comment by kspearrin** [comment]
If you are using Bitwarden cloud-hosted version, you can simply re-sync your vault and the problem should now go away. We are working on submitting a new version to the browser stores to address the issue for self-hosted Bitwarden users. You can also downgrade your browser extension client to 2024.5.x in the meantime to resolve the issue as well.

**Comment by broyuken** [comment]
How do you downgrade the extension?

**Comment by danielbrunt57** [comment]
> How do you downgrade the extension?

See https://github.com/bitwarden/clients/issues/9617
Specifically...
> > @raidolo Where do you find the older unpacked extension?
> 
> In the releases... https://github.com/bitwarden/clients/releases/download/browser-v2024.5.2/dist-chrome-2024.5.2.zip you have to unzip the file somewhere and open that directory with the "Load Unpacked" button (enable developer option in extensions)

The releases can be found here: https://github.com/bitwarden/clients/releases
Chrome 2024.5.2 is here: https://github.com/bitwarden/clients/releases/tag/browser-v2024.5.2

**Comment by kspearrin** [comment]
Version 2024.6.1 has been submitted to the chrome web store with the fox but will take some time for approval and rollout.

**Comment by broyuken** [comment]
> > How do you downgrade the extension?
> 
> See [bitwarden/clients#9617](https://github.com/bitwarden/clients/issues/9617) Specifically...
> 
> > > @raidolo Where do you find the older unpacked extension?
> > 
> > 
> > In the releases... https://github.com/bitwarden/clients/releases/download/browser-v2024.5.2/dist-chrome-2024.5.2.zip you have to unzip the file somewhere and open that directory with the "Load Unpacked" button (enable developer option in extensions)
> 
> The releases can be found here: https://github.com/bitwarden/clients/releases Chrome 2024.5.2 is here: https://github.com/bitwarden/clients/releases/tag/browser-v2024.5.2

thanks, downgraded

**Comment by danktankk** [comment]
one more to confirm the bitwarden auto-fill is the issue here.  I will roll back the release because I truly cant live without auto-fill lol

**Comment by danktankk** [comment]
> Version 2024.6.1 has been submitted to the chrome web store with the fix but will take some time for approval and rollout.

thank you!

**Comment by loryanstrant** [comment]
Just to throw a spanner in the works here I'm experiencing it currently on Firefox where there is no Bitwarden.
I mean, I am also experiencing it on Edge with the Bitwarden extension (whether locked or unlocked).
In Firefox I can navigate and use automations, dev tools, etc. But if I go to a dashboard or browser_mod, the tab will become unresponsive.

**Comment by danktankk** [comment]
2024.6.1 is still not available  :|  how long does it take?

**Comment by kspearrin** [comment]
Usually a day or so, but I guess Google isn't reviewing over the weekend. I would expect something tomorrow.

**Comment by ThePatricide** [comment]
On Edge with 2024.6.1 installed, the issue is gone. All works again as usual.

**Comment by cagonzalezcs** [comment]
@darnasii 

I'm a dev with Bitwarden. The changes in v2024.6.1 should have resolved the behavior that this thread describes. 

If you have time, could you please provide some details on this thread? https://github.com/bitwarden/clients/issues/9617

We'd appreciate your help in narrowing down the bug that is giving you trouble. Thank you.

**Comment by danktankk** [comment]
Updated and it did not work at first.  I needed to close the browser and reopen it.  It now works as expected so far.  Many thanks for this fix!

**Comment by cagonzalezcs** [comment]
@danktankk Thank you for the update, glad to hear things are working now.
