### ISSUE TITLE
Text display loss

### ISSUE THREAD

**Issue by zerosnsa** [home-assistant/frontend#21086]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I followed the steps to build and generate my own front-end page, but I found that the original text of my page was missing and the translation failed

### Describe the behavior you expected

Hope you can tell me how to solve it

### Steps to reproduce the issue

According to the Frontend development steps, https://developers.home-assistant.io/docs/frontend/development/

### What version of Home Assistant Core has the issue?

development

### In which browser are you experiencing the issue with?

All of it

### Additional information

![1718334715558](https://github.com/home-assistant/frontend/assets/152005489/461966d5-2ed4-4e74-95a5-db00cd29766c)
![1718334794630](https://github.com/home-assistant/frontend/assets/152005489/38f89456-4978-434b-988a-7a4abbeccbc7)

**Comment by ChristophCaina** [comment]
this is usually a cache issue.
I've seen this several times (but not too often) - and refreshing the page resolved the issue.

**Comment by zerosnsa** [comment]
> 这通常是缓存问题。我已经见过几次（但不是太频繁） - 刷新页面解决了这个问题。
Unfortunately, this is not the problem, I have tried every machine, and the browser has been changed, and this problem also occurs
