### ISSUE TITLE
FRITZ!DECT 301 vacation mode

### ISSUE THREAD

**Issue by florian-sabonchi** [home-assistant/frontend#21095]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hello, I own the radiator thermostats FRITZ!DECT 301 from AVM. The Fritzbox allows you to activate a vacation periode switch during this period, the manual switching of the thermostats is deactivated, it would be nice if HomeAssistant would recognize this setting and it would not be possible to set the temperature via the UI, because the setting has  no effect in this time

### Describe the behavior you expected

Temperature change should be locked because changing it has no effect to the thermostats

### Steps to reproduce the issue

1. enable vaction mode in FritzBox
2. change Tempratur in HomeAssistant
3.
...

### What version of Home Assistant Core has the issue?

2024.6.1

### What was the last working version of Home Assistant Core?

2024.6.1

**Comment by karwosts** [comment]
I think maybe the appropriate solution to this would be fritzbox to not advertise the TARGET_TEMPERATURE flag in supported features in this mode, if they don't want it settable (or viewable?)

Frontend doesn't know anything about this vacation mode or how to treat it, the controls that you get on the climate card just reflect the supported features flags that the entity advertises. 

So this should maybe be a core issue instead of frontend.

**Comment by florian-sabonchi** [comment]
> I think maybe the appropriate solution to this would be fritzbox to not advertise the TARGET_TEMPERATURE flag in supported features in this mode, if they don't want it settable (or viewable?)
> 
> Frontend doesn't know anything about this vacation mode or how to treat it, the controls that you get on the climate card just reflect the supported features flags that the entity advertises.
> 
> So this should maybe be a core issue instead of frontend.

thanks for your reply i will open a issue in core
