### ISSUE TITLE
Time Zone for Rome seems not corect (GMT+1) 

### ISSUE THREAD

**Issue by denisjoshua** [home-assistant/frontend#21125]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Time Zone for Rome seems not corect... is GMT+1
but Rome have GMT+2. 

### Describe the behavior you expected

 GMT+2

### Steps to reproduce the issue

Just go to see

### What version of Home Assistant Core has the issue?

last

### What was the last working version of Home Assistant Core?

last

### In which browser are you experiencing the issue with?

Google Chrome

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
related: #19318

**Comment by denisjoshua** [comment]
Ok thanks... I have just write there. 
I'll close this thread. 
Denis
