### ISSUE TITLE
missing fan_mode icons on daikin tile card

### ISSUE THREAD

**Issue by dmereu** [home-assistant/frontend#21143]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The daikin HVAC tile card doesn't show fan_mode icons when the relative feature is activated.
All modes are shown as dot icon

![image](https://github.com/home-assistant/frontend/assets/16898757/9becebc3-67e3-42a2-9d3d-cabe7255f080)

### Describe the behavior you expected

Unfortunately there are specific icons for fan speed from 1 to 3 (e.g. mdi:fan-speed-1) but not for 4 and 5
I suggest the following icons for fan_modes

auto: mdi:fan-auto
silent: mdi:weather-night
1: mdi:numeric-1 
2: mdi:numeric-2
3: mdi:numeric-3
4: mdi:numeric-4
5: mdi:numeric-5

### Steps to reproduce the issue

Configure a Daikin HVAC device
Add a tile card
Activate the fan_mode feature

### What version of Home Assistant Core has the issue?

2024.6.4

**Comment by karwosts** [comment]
Icons are set by the integration in core, not in frontend.

**Comment by dmereu** [comment]
Wrong section
