### ISSUE TITLE
Default Dashboard is unnecessarily magical and there's not option for advanced users to change it

### ISSUE THREAD

**Issue by danielskowronski** [home-assistant/frontend#21140]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The "Default Dashboard" is a resource that user cannot control with restrictiveness amount changing from version to version (on 2024.6.4 it's the worst so far, which manifests with "The default dashboard, Overview, cannot be edited from the UI. You can hide it by setting another dashboard as default."). That fact alone wouldn't be so painful (after all, we have Map and Energy dashboards), but because it's a default dashboard globally, you must change it on every device you add and from time to time, re-set it as those devices tend to forget sidebar settings. Additionally, it's "magical" because HA updates randomly decide to revert it to the default view showing *everything*.

I'm deeply grateful for the open-source software and I'd be very reluctant to migrate; however, IMHO, this is unacceptable behaviour, similar to what Microsoft does with shovelling random changes on Windows because:

1. Home Assistant is not a product for the average user, quite the opposite - at least the main admin of an instance must be a power user if they decided to even deploy HA; therefore arbitrary, undocumented features (I consider anything that's not at least as strong as "don't touch this dashboard, it'll be reverted" as insufficient)
2. I don't see a scenario where this dashboard would be useful to any degree, as its whole purpose is to show everything - even if filtering by are worked, I don't think most of the users would find useful looking at messy widgets every time they open the app/website
3. The dashboard is hardcoded as default, meaning you can't make a reasonable experience even for the main user as it's often reverted to be the default one - this is unavoidable if sidebar/dashboard settings for clients are stored on client-side and not server-side in their profiles
4. Tons of other people share workarounds for this "feature" that tend to stop working every few versions, showing it's not desired behaviour - at least in current state when you can't change it

I know there are plenty of similar issues raised (e.g. https://github.com/home-assistant/frontend/issues/18626, https://github.com/home-assistant/frontend/issues/11069), but they are all about specific aspects of the main issue, as opposed to hardcoded nature of "Default Dashboard"

### Describe the behavior you expected

I see those two as an ideal solution - preferably having both implemented, but just one would be sufficient to ease the pain:

1. Admin can set any dashboard as global default (i.e. not changing the contents of magical "Default Dashboard", rather pointing to a specific URL)
2. Each user can set any dashboard as their default - a setting stored server-side:
      - Ideally, it should be possible to let users store multiple variants matching different user-agents, so mobile app could be set to show one dashboard as default, while web/desktop client - something else)
      - However, the bare minimum is to add one more field to user profile that dictates what's default dashboard - something that neither HA updater nor admin can change (unless they manually go deep with low-level changes)

Those are alternative approaches, listed from most to least desirable ones:

1. Bring back the ability to edit the Default Dashboard from UI and ensure that HA updates respect admin overrides of the dashboard during any form of update
2. The above, but keep YAML mode
3. Improve Default Dashboard behaviour to be usable
4. Completely prohibit user from changing Default Dashboard and add suitable warnings

### Steps to reproduce the issue

1. Install HA
2. Attempt to change the default dashboard - either by selecting other dashboard or editing magical default one

### What version of Home Assistant Core has the issue?

core-2024.6.4

### Additional information

A few of use-cases that are completely broken by this behaviour:

- kiosk-mode
- adding any other user who's not expecting to see everything instead of curated dashboard 
- any mobile app use (huge number of resources make app slow and even if the current form of "Default Dashboard" was usable on desktop, on mobile it'd still be an extremely long list of everything with a high chance of accidentally clicking a button while scrolling)

Full list of similar issues:

- https://github.com/home-assistant/frontend/issues/5349
- https://github.com/home-assistant/frontend/issues/5353
- https://github.com/home-assistant/frontend/issues/5835
- https://github.com/home-assistant/frontend/issues/6415
- https://github.com/home-assistant/frontend/issues/7290
- https://github.com/home-assistant/frontend/issues/7742
- https://github.com/home-assistant/frontend/issues/7818
- https://github.com/home-assistant/frontend/issues/8359 
- https://github.com/home-assistant/frontend/issues/11069
- https://github.com/home-assistant/frontend/issues/12027
- https://github.com/home-assistant/frontend/issues/12990
- https://github.com/home-assistant/frontend/issues/17325
- https://github.com/home-assistant/frontend/issues/18626
- https://github.com/home-assistant/frontend/discussions/11278
- https://github.com/home-assistant/frontend/discussions/11316
- https://github.com/home-assistant/frontend/discussions/20852

**Comment by piitaya** [comment]
Having the overview dashboard as a default dashboard is a technical limitation and legacy support for now.
I agree with you, we should be able to remove it and set every other dashboard as default.

It's in the roadmap to improve the default dashboard (multiple views per room, etc...)

For now, as a quick fix : you can "take control" of the overview dashboard and configure it manually. It's not perfect but it should at least fix your daily issue.

![CleanShot 2024-06-25 at 14 23 25](https://github.com/home-assistant/frontend/assets/5878303/88f34e4c-f217-40ac-8c8c-7c7ee1cac8e1)

**Comment by dstengele** [comment]
The default dashboard is still magical.

**Comment by piitaya** [comment]
@dstengele What do you consider as "magical"? I answered by explaning how to take control of the default dashboard with latest release.

It is planned to improve the default dashboard. We are currently working on the foundation in the latest releases by adding some elements : 
- tile card
- section view
- new badges
- resizable section
- floors

The final goal is to have a great default dashboard while allowing user to customize it. But we first have to build the foundations.

**Comment by dstengele** [comment]
@piitaya And the workaround is fine and works for me (and probably most other people), so thank you for that. :) I just think that this issue should not yet be closed since the default dashboard still is kind of special. I think it would be most logical to just have a basic default dashboard that automatically shows "standard data" like temperature, humidity, thermostat, camera etc. of each available room, kind of like the Home apps do it on iOS, while not being able to be edited at all. This way, the default dashboard can be used for a general overview without needing to customize it. And if one wants to do it themselves, they can use the existing functionality of setting another dashboard as default and thereby hiding the normal default dashboard. I think much of the confusion comes from this half-customizability.

**Comment by Z3r0shin** [comment]
I'd like to pitch in and agree with the OP. Making a default dashboard available only to certain users would be great, but making sure that this default dashboard is NOT the current default dashboard would be excellent. So far, it is indeed magical in the sense that doing anything else than removing/adding entities to it is next to impossible.

**Comment by NikLuy** [comment]
I want my childs to use also HA with there Accounts and don't want them to controll ir see everything so set an default from admin to those users would be nice.

**Comment by nickdos** [comment]
The [suggested workaround](https://github.com/home-assistant/frontend/issues/21140#issuecomment-2188803901) no longer works, at least for me on my default dashboard. I can't get to the "Take control" option and I've tried every conceivable combination of menu/buttons/options.

I'd like to know how to make another dashboard the default, while still be able to select the old default dashboard in the left menu. As it stands, if I change the default dashboard, the old dashboard disappears from the menu and I can only access it via the edit dashboards page.

**Comment by lukshan13** [comment]
Hi, I too would like to voice my support for OP. The default global dashboard should be changeable, not just per device. HA should also allow us to disable the dashboard if we want to

**Comment by larsenpedersen** [comment]
Recently I have also experienced that even though I have selected another default dashboard for my user/devices, it is defaulting back to the "Overview"-dashboard.
I have now tried to take over the "Overview"-dashboard - but I can't even rename it or give it another icon.

**Comment by deezid** [comment]
> Recently I have also experienced that even though I have selected another default dashboard for my user/devices, it is defaulting back to the "Overview"-dashboard. I have now tried to take over the "Overview"-dashboard - but I can't even rename it or give it another icon.

same here.
Also had to take over because the default dashboard kept itself making the default again. Even when just changing from wifi to 5G when on the app on the phone. Basically copied all the yaml over from my actual dashboard and that worked fine.

Super annoying still and I wish there was an option to rename it and change the icon.
