### ISSUE TITLE
tile option last-changed does not see position% only open/close

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#21169]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

as title, the last-changed options does not register the position changes.
I open my cover to 15% closed when warm enough, so the state remains 'open'.

resulting in 

<img width="550" alt="Scherm­afbeelding 2024-06-26 om 10 49 20" src="https://github.com/home-assistant/frontend/assets/33354141/32599dfb-f16f-4b3d-93ea-9b5322617849">

changing to other positions are reflected in the %alright, but not in the last-changed, which is very inconvenient , because we can not check whether the cover automations have been working correctly. These are screens from a few minutes ago, not from 'eergisteren' (the day before yesterday)

<img width="558" alt="Scherm­afbeelding 2024-06-26 om 10 47 26" src="https://github.com/home-assistant/frontend/assets/33354141/94927c56-4138-4a92-a165-1a358a9d1abf">

<img width="580" alt="Scherm­afbeelding 2024-06-26 om 10 47 44" src="https://github.com/home-assistant/frontend/assets/33354141/4802a023-24d8-487a-8d4b-146ea9cb34e1">

### Describe the behavior you expected

have the last-changed change on position change too

### Steps to reproduce the issue

1. create yaml below
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.6.3

### In which browser are you experiencing the issue with?

all/any

### Which operating system are you using to run this browser?

Sonoma 14.5

### Problem-relevant frontend configuration

```yaml
type: tile
features:
  - type: cover-open-close
  - type: cover-position
state_content:
  - state
  - current_position
  - last-changed
entity: cover.slaapkamers
```

### Additional information

doing 
{{states.cover.slaapkamers.last_updated}}

makes it happen:

<img width="694" alt="Scherm­afbeelding 2024-06-26 om 11 19 00" src="https://github.com/home-assistant/frontend/assets/33354141/03226a7e-e1ed-4631-8e1c-9133b39edd13">

so, would then be a FR.... https://github.com/home-assistant/frontend/discussions/21170

**Comment by piitaya** [comment]
Last changed is only about state, not about attributes. We can of course add last updated to tile card if needed 🙂

**Comment by Mariusthvdb** [comment]
That would be magic! Please do so the display of covers makes more sense ;-)
