### ISSUE TITLE
Attempting to search for a new integration doesn't actually search and emits an error in the console log for each character typed

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/frontend#21173]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In 2024.7 beta, searching for an integration to add doesn't filter the list and instead generates an error in the browser console log for each character typed.

### Describe the behavior you expected

I expect the list of integrations to be successively filtered as I type characters.

### Steps to reproduce the issue

1. Hit "Add integration"
2. Type some characters to attempt to match an integration name
3. Observe that the list never changes and there's a repeating error in the console log for each character.

### What version of Home Assistant Core has the issue?

core-2024.7b0

### What was the last working version of Home Assistant Core?

core-2024.6.xx

### In which browser are you experiencing the issue with?

Google Chrome and Safari

### Which operating system are you using to run this browser?

macOS Sequoia

### Javascript errors shown in your browser console/inspector

```txt
strip-diacritics.ts:2 Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'normalize')
    at n (strip-diacritics.ts:2:7)
    at _.getFn (dialog-add-integration.ts:259:33)
    at fuse.mjs:399:53
    at Array.forEach (<anonymous>)
    at _._addObject (fuse.mjs:398:15)
    at fuse.mjs:350:14
    at Array.forEach (<anonymous>)
    at _.create (fuse.mjs:349:17)
    at v (fuse.mjs:462:11)
    at H.setCollection (fuse.mjs:1529:7)
n	@	strip-diacritics.ts:2
getFn	@	dialog-add-integration.ts:259
(anonymous)	@	dialog-add-integration.ts:271
value	@	dialog-add-integration.ts:296
value	@	dialog-add-integration.ts:310
update	@	lit-element.ts:160
performUpdate	@	reactive-element.ts:1329
scheduleUpdate	@	reactive-element.ts:1261
_$Ej	@	reactive-element.ts:1233
await in _$Ej (async)		
requestUpdate	@	reactive-element.ts:1208
set	@	reactive-element.ts:726
value	@	dialog-add-integration.ts:526
handleEvent	@	lit-html.ts:2018
n	@	fire_event.ts:76
value	@	search-input.ts:66
value	@	search-input.ts:70
handleEvent	@	lit-html.ts:2018
Show 8 more frames
```

### Additional information

<img width="564" alt="image" src="https://github.com/home-assistant/frontend/assets/860888/908772c1-0455-4c8a-a88d-60cadc19bbb6">

**Comment by karwosts** [comment]
Same issue in `Add Card` search box.
