### ISSUE TITLE
Users: wrong error when adding username that contains capital

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#21209]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If you attempt to add a new user, and the username contains a capital letter, it says "Username already exists" rather than what the error actually is (username must not contain capitals)

<img width="524" alt="Screen Shot 2024-06-28 at 3 00 41 AM" src="https://github.com/home-assistant/frontend/assets/9065557/64ef09ec-493e-46d6-b9d2-0e11244f03f6">

### Describe the behavior you expected

Error should say "username must not contain capital letters" or something. And ideally the error text should be underneath the username field rather than at the very top of the add user dialog.

### Steps to reproduce the issue

[![Open your Home Assistant instance and show your users.](https://my.home-assistant.io/badges/users.svg)](https://my.home-assistant.io/redirect/users/)

1. Add a new user, type "HanSolo" in username field and try to save
2. It will say "username already exists" when that's not true

### What version of Home Assistant Core has the issue?

2024.7.0b3

**Comment by silamon** [comment]
I've debugged into this specific issue and it appears to come from [the backend](https://github.com/home-assistant/core/blob/f4224a0327028324539244b25bdc9601eaf95081/homeassistant/components/config/auth_provider_homeassistant.py#L59-L60). Consider to open an issue against the auth integration at https://github.com/home-assistant/core.
