### ISSUE TITLE
Hide Energy not working

### ISSUE THREAD

**Issue by GingerStyle** [home-assistant/frontend#21228]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I am on the Overview tab and I click the edit icon in the top right corner, there is a feature that I believe should hide the energy information for my connected devices. It does not do this. What it did do is when I had it set to hide energy info and then added new devices, it hid the new device energy information, but I then set it to show the energy info and it showed everything. When I turned the energy info back off though, it would not turn off any of the energy info. 

### Describe the behavior you expected

I expected it to turn off all energy measurements when it is turned on, and show all energy measurements when it is turned off

### Steps to reproduce the issue

1. Be an awesome person that works to improve this software
2. please fix my issue
3. accept my gratitude!
...

### What version of Home Assistant Core has the issue?

2024.6.4

### In which browser are you experiencing the issue with?

Google Chrome

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment]
The only thing hide_energy option is currently coded to do is to remove this card from the generated dashboard:

![image](https://github.com/home-assistant/frontend/assets/32912880/8a1a6bf1-a46b-4296-8a8d-ba6af1555974)

I'm not sure exactly which "energy measurements" you are referring to, but I guess this option isn't intended to control them.

**Comment by harrislloydlevy** [comment]
Not original reporter but I'm having the same "issue".

I would have assumed that enabling hide_energy would also hide the per-area energy/power measurements as in the screenshot below:
![image](https://github.com/user-attachments/assets/dcb001d7-807f-4bc7-8a21-b4bb6473d55d)

**Comment by topka** [comment]
Hi! I have just updated to the latest Home Assistant Operating System 14.0 and Home Assistant version 2024.12.2

I experience the same issue as reported by @harrislloydlevy above. The energy info of my Shelly devices still shows up even with "hide energy" option ON, just like on the screenshot above. Happy to provide more info and hope it can help solve it. Thanks!

**Comment by racinmat** [comment]
I have the same issue, can someone re-open it? It's clearly still relevant.
