### ISSUE TITLE
Unable to use voice input microphone, prompt”. /“bug, 7.0b5

### ISSUE THREAD

**Issue by knoop7** [home-assistant/frontend#21234]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

<img width="702" alt="2024-06-30 15 37 04" src="https://github.com/home-assistant/frontend/assets/25675558/6cae4a43-5e7b-4083-b1cb-1285e43fd30c">

**Unable to use voice input microphone, prompt. /bug,7.0b5
audio-recorder.ts:40 TypeError: Failed to resolve module specifier "core-js/modules/es.array.iterator.js". 
Relative references must start with either "/", "./", or "../".**

<img width="393" alt="2024-06-30 15 39 45" src="https://github.com/home-assistant/frontend/assets/25675558/7969fed2-881e-4ce4-935b-139869b89fe3">

Hopefully, this resolves the issue with browser identification Mozilla/5.0 (Macintosh; Intel Mac OS

### Describe the behavior you expected

or

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2024.7.0b5

**Comment by silamon** [comment]
cc @steverep I see some imports of core-js into those audio related areas so I think it's related to #20676

**Comment by silamon** [comment]
I see a javascript file "recorder.worklet.js" under src/util where there are core-js imports being added after build. It's the first file under hass_frontend "_src_util_recorder_worklet_js.js".  

```js
import "core-js/modules/es.array.iterator.js";
import "core-js/modules/es.array-buffer.detached.js";
import "core-js/modules/es.array-buffer.transfer.js";
import "core-js/modules/es.array-buffer.transfer-to-fixed-length.js";
import "core-js/modules/es.typed-array.int16-array.js";
import "core-js/modules/es.typed-array.at.js";
(snip)
class RecorderProcessor extends AudioWorkletProcessor {
(snip)
``` 

I'm not sure if that's coming from there, since the stack trace points slightly different, but the imports in the "ha-voice-dialog" seem to start with "./node-modules/core-js/.."

**Comment by steverep** [comment]
Yeah, Webpack doesn't handle the audio worklet correctly. I'll fix it.

**Comment by knoop7** [comment]
> Yeah, Webpack doesn't handle the audio worklet correctly ([webpack/webpack#11543](https://github.com/webpack/webpack/issues/11543)). I'll fix it.

Thank you, thank you very much

**Comment by knoop7** [comment]
> I see a javascript file "recorder.worklet.js" under src/util where there are core-js imports being added after build. It's the first file under hass_frontend "_src_util_recorder_worklet_js.js".
> 
> ```js
> import "core-js/modules/es.array.iterator.js";
> import "core-js/modules/es.array-buffer.detached.js";
> import "core-js/modules/es.array-buffer.transfer.js";
> import "core-js/modules/es.array-buffer.transfer-to-fixed-length.js";
> import "core-js/modules/es.typed-array.int16-array.js";
> import "core-js/modules/es.typed-array.at.js";
> (snip)
> class RecorderProcessor extends AudioWorkletProcessor {
> (snip)
> ```
> 
> I'm not sure if that's coming from there, since the stack trace points slightly different, but the imports in the "ha-voice-command-dialog" seem to start with "./node-modules/core-js/.." and are correct.

Thank you, thank you very much
