### ISSUE TITLE
Inconsistent dialog when deleting tag

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#21240]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When deleting a tag, it has red "Delete" button at first (good)
<img width="621" alt="Screen Shot 2024-07-01 at 3 05 55 AM" src="https://github.com/home-assistant/frontend/assets/9065557/a0e4ede8-c96e-4e46-9caf-9f641abd5abf">

But then confirmation prompt shows it as "Remove" button and without red text
<img width="636" alt="Screen Shot 2024-07-01 at 3 06 01 AM" src="https://github.com/home-assistant/frontend/assets/9065557/15ef716b-41fe-4cc4-8de6-5ff361f8ffeb">

### Describe the behavior you expected

Consistent wording (Delete), and red text on confirmation prompt

### Steps to reproduce the issue

1. Go to Configuration → Tags
2. Create a test tag, then click the cog to delete it

### What version of Home Assistant Core has the issue?

2024.7.0b6

**Comment by matthiasdebaat** [comment]
As the tag would [still exist](https://design.home-assistant.io/#Text/remove-delete-add-create) after you remove it from Home Assistant, we should change the button tot `Remove`.

**Comment by silamon** [comment]
So we should use "remove" because the tag still physically exists or did I misunderstand that?

**Comment by matthiasdebaat** [comment]
Correct

**Comment by silamon** [comment]
I'm not sure if I would follow for that reason to make it "remove". It still deletes the tag from Home Assistant in a non recoverable way. "remove" mentions it is kept in existence, which means it's still somewhere around but no longer associated or referenced. 
We also use "delete" for floors and areas for example, which also exist physically, which is sort of the same example.  I think the line should be crossed to say that "delete" and "remove" apply for things in Home Assistant.

**Comment by matthiasdebaat** [comment]
I agree. I've researched it a bit more and come to the following conclusion:
`Delete` implies erasure from the system permanently, while `remove` means hiding from the user interface but retaining in the system. 

Will add this to our design docs.

**Comment by silamon** [comment]
I've opened a pull request for "delete" if you don't mind. Reading the design doc, I still interpret "delete" as delete everything that is known to the tag while "remove" to me is clear the associations, but keep the tag present in Home Assistant.  
In fact, everything is recoverable, depending on how much time you want to spend.

**Comment by silamon** [comment]
After reading these resources below, it follows your (previous) design documentation with the addition that "remove" can also be used if you delete something to the trash can. 

* https://adnanpuzic.medium.com/the-difference-between-remove-and-delete-7f6c1771e40f
* https://uxmovement.com/buttons/remove-vs-delete-when-to-use-which/
