### ISSUE TITLE
Connection lost when using microphone

### ISSUE THREAD

**Issue by Martinvdm** [home-assistant/frontend#21272]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When using microphone within the home assistant companion app on iOS, the app is losing connection.

### Describe the behavior you expected

Keep connection and accept en forward microphone input

### Steps to reproduce the issue

In companion app iOS or in safari (both) the connection is lost when using the microphone. In this usecase an webrtc Lovelace card. 

### What version of Home Assistant Core has the issue?

2024.6.4
Ios app 2024.5.1 and 2024.6

### In which browser are you experiencing the issue with?

Safari iOS 17.5.1

### Which operating system are you using to run this browser?

iOS 17.5.1

### Javascript errors shown in your browser console/inspector

```txt
No error vissable
```

### Additional information

Loosing connection 
No addition logging.
Mic is allowed in app iOS settings

**Comment by Martinvdm** [comment]
Perhaps relevant 
https://github.com/AlexxIT/WebRTC/issues/724

**Comment by Martinvdm** [comment]
And
https://github.com/home-assistant/iOS/issues/2420

**Comment by ph0nebooth** [comment]
@Martinvdm did you ever find a viable workaround? Changing the default browser from Safari to Chrome resolves the issue. However, that creates a new issue. I don't want to use Chrome...
