### ISSUE TITLE
2024.7 has broken grafana graphs in iframes

### ISSUE THREAD

**Issue by Makin-Things** [home-assistant/frontend#21279]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After updating the 2024.7 all of the grafana graphs that are displayed in iframe on my dashboard are completely screwed up.
Most of them are now scaled up so they no longer fit within the cards.
![image](https://github.com/home-assistant/frontend/assets/91187456/7fc53e3b-ddb1-4a9a-98f5-7fcb34c65d91)
One of them that is a vertical bar graph has somehow been turned into a horizontal bar graph (and scaled up)
![image](https://github.com/home-assistant/frontend/assets/91187456/998846aa-7ce7-487c-b84e-3481e92f46ba)
If I open any on the used grafana links in a separate tab they still display correctly, as an example here is the bar chart.
![image](https://github.com/home-assistant/frontend/assets/91187456/ed4414a7-665b-46b8-993a-af67b79a6258)

### Describe the behavior you expected

I would expect that the upgrade didn't break these cards and they would continue to display as they did pre-update.

### Steps to reproduce the issue

1. Upgrade to 2024.7
2. Observe completely mangled iframe/grafana images

### What version of Home Assistant Core has the issue?

2024.7

### What was the last working version of Home Assistant Core?

2024.6.latest

### In which browser are you experiencing the issue with?

Latest firefox. They are not mangled in chrome.

### Which operating system are you using to run this browser?

Windows 10, fully patched.

**Comment by piitaya** [comment]
What type of dashboard are you using (masonry, sections) ? Can you provide the `yaml`configuration?

**Comment by Makin-Things** [comment]
Using masonry. The grafana graphs are within a grid card.

`type: grid
cards:
  - type: custom:simple-thermostat
    entity: climate.heater
    step_size: 1
    control:
      hvac:
        _hide_when_off: false
        fan_only: false
    layout:
      mode:
        headings: false
        names: false
  - type: iframe
    url: >-
      https://redacted url
    aspect_ratio: 75%
    style: |
      ha-card {
        border-radius: 5px;
      }
columns: 1
square: false`

Interestingly I just extract the single iframe yaml out in put in it's own card and that displays properly as well, so it looks linke it might be something to do with grid cards on Firefox?

**Comment by piitaya** [comment]
Thank you. It's similar to this issue : https://github.com/home-assistant/frontend/issues/21280.
I tested with https://home-assistant.io and it seems to fix your issue too.

**Comment by Makin-Things** [comment]
Thank you for the quick response and analysis and fix.
