### ISSUE TITLE
Calendar Card is larger than max rows (and columns)

### ISSUE THREAD

**Issue by PhilippeP62** [home-assistant/frontend#21284]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Even when setting rows to max , the calendar still overflow to the next rows

![Screenshot_20240704_130135_Home_Assistant](https://github.com/home-assistant/frontend/assets/11553234/174ae855-7351-439a-aa10-f121effd3e79)

### Describe the behavior you expected

No overflow

### Steps to reproduce the issue

1. Use a calendar Card 
2. Set max rows and colulns
3. Enjoy
...

### What version of Home Assistant Core has the issue?

2027.7.0

### In which browser are you experiencing the issue with?

Ha app

### Which operating system are you using to run this browser?

Android

**Comment by piitaya** [comment]
Hi 👋 Some cards are optimized yet for grid and needs a redesign. For now, you can set the value to a bigger number using YAML (`grid_rows` under the `layout_options` property)

**Comment by PhilippeP62** [comment]
It works (and needs 8 rows)

**Comment by piitaya** [comment]
Do you have some error in the logs https://my.home-assistant.io/redirect/logs/?provider=core ?
