### ISSUE TITLE
Energy Dashboard showing Battery Discharge as a negative and missing used Solar.

### ISSUE THREAD

**Issue by siobhanellis** [home-assistant/frontend#21285]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

![Screenshot 2024-07-04 at 12 31 44](https://github.com/home-assistant/frontend/assets/33163141/81d68fa8-52a5-44b7-8d14-faba9c612aa7)

This used to work perfectly, but not since 9th June 2024.

You can see that Battery Discharge is showing as a negative, and also that Solar consumed is missing.

![Screenshot 2024-07-04 at 12 31 30](https://github.com/home-assistant/frontend/assets/33163141/ebe41007-76e1-4686-a106-97ffe3351dba)
This is battery discharge, and you can see there are no negative values.

### Describe the behavior you expected

I expect to see battery discharge as a positive.

### Steps to reproduce the issue

![Screenshot 2024-07-04 at 12 52 44](https://github.com/home-assistant/frontend/assets/33163141/5e2800f5-c7f5-4375-b28b-0eb88c021a0d)
My configuration.
Just go to Energy dashboard, and it always starts to go wrong around midday.

### What version of Home Assistant Core has the issue?

2024.7.0

### What was the last working version of Home Assistant Core?

2024.6.?

### In which browser are you experiencing the issue with?

MACOS Safari 17.5

### Which operating system are you using to run this browser?

MACOS Sonoma 14.5

### State of relevant entities

```txt
Set the current state representation of an entity within Home Assistant.
If the entity belongs to a device, there will be no actual communication with that device.

Entity
sensor.foxess_bat_discharge  

Tip!
Press 'e' on any page to open the entity search dialogue
State
1.2
State attributes (YAML, optional)

1 state_class: total_increasing
2 unit_of_measurement: kWh
3 device_class: energy
4 friendly_name: FoxESS - Bat Discharge
```

### Problem-relevant frontend configuration

```yaml
shown in problem description
```

### Javascript errors shown in your browser console/inspector

```txt
not seen any
```

### Additional information

none

**Comment by dbachats** [comment]
Similar problem for me
 no solar or batterydata to energy dashboard. need to reboot the system for it to restart loggibg data again

**Comment by ChristophCaina** [comment]
> Similar problem for me. System stops logging data during the night , no solar or battery data to energy dashboard. need to reboot the system for it to restart logging data again. hope gets resolved soon

please see this forum thread for your issue with stopped recorder:
https://community.home-assistant.io/t/psa-2024-7-recorder-problems/746428/1

**Comment by dbachats** [comment]
thanks... unfortunatelly  the problem persists even after the 2024.7.2 update

**Comment by christof62** [comment]
I have the same problem. It happens when the solar energy is lower than the energy which is feed to the grid + the energy charged to the battery. I assume that this accurs due to inaccurate measurements. The battery was never discharged at that moment in time.

**Comment by hrabbach** [comment]
Looks like this problem isn't solved yet - I just started to notice the same thing, now that the days are getting sunnier (I only recently added energy tracking to my HA instance), I see periods during the day where no solar energy consumption (actually, no consumption at all) is showing up in the energy dashboard, while both the battery charge and discharge amounts show a negative value (only in the energy dashboard - the values of the underlying sensors increase as expected). It ends up looking like this:

![Image](https://github.com/user-attachments/assets/653ee435-3b54-47dd-9bb4-8d21aba7ddf3)

Of course we continued to use electricity during those hours (our heat-pump takes care of that...), but the dashboard also claims negative untracked consumption:

![Image](https://github.com/user-attachments/assets/0b06614b-9535-48f9-a0dd-a264d560d3cc)
