### ISSUE TITLE
Timers remaning time not working in tile card

### ISSUE THREAD

**Issue by brocasm** [home-assistant/frontend#21288]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On a views of type section.
When the timer is running, the remaining stay at duration time and not countdown
![Capture d’écran 2024-07-04 153412](https://github.com/home-assistant/frontend/assets/56800814/3212fe5d-7381-4c81-997c-d2e56c64b88e)

### Describe the behavior you expected

The timer card in views section, with remaining time work as other type views with decremant time 
![Capture d’écran 2024-07-04 154053](https://github.com/home-assistant/frontend/assets/56800814/c4f0edb0-23e3-4a2e-a6d9-ae530d900bc5)

### Steps to reproduce the issue

1.Add a card by entity of an timer
2. Add State content: Remaining
3. Start the timer

### What version of Home Assistant Core has the issue?

2024.7.0

### In which browser are you experiencing the issue with?

Firefox 127.0.2 / Brave Version 1.67.123 Chromium: 126.0.6478.126

### Which operating system are you using to run this browser?

Windows 11 / Linux

### State of relevant entities

```txt
timer.name active
```

### Problem-relevant frontend configuration

```yaml
type: tile
entity: timer.auto_rearme
layout_options:
  grid_columns: 4
  grid_rows: 1
state_content:
  - remaining
  - duration
  - finishes_at
```

**Comment by MarcusCulverTHL** [comment]
I am also having this issue. The entity tile (single entity) display is no different when a timer helper is active between duration and remaining attributes. The remaining attribute should show the time the helper has remaining as per the Entities tile when the same configuration is applied.
![image](https://github.com/home-assistant/frontend/assets/89921053/493ba751-12e9-4781-8505-ea3c0ea4fa43)
![image](https://github.com/home-assistant/frontend/assets/89921053/06c4ea29-1ef8-4191-90fe-4653226fe286)
![image](https://github.com/home-assistant/frontend/assets/89921053/be03dcbb-9d26-4cad-ab2f-dacad43b3f4b)
