### ISSUE TITLE
Unable to delete helper

### ISSUE THREAD

**Issue by Beestkiller** [home-assistant/frontend#21305]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

There seems to be no option to delete helper exept for going into the configuration files to manualy delete them.

### Describe the behavior you expected

there should be e delete helper option.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

 2024.7.0

**Comment by karwosts** [comment]
Typically there is a delete button on the bottom left of the configuration page of the more-info for each helper.

If you claim that it is missing, please provide some more details about your specific helper, and maybe screenshots.

**Comment by matthiasdebaat** [comment]
There is no delete button on the helper table, I assume this is the issue.

**Comment by Beestkiller** [comment]
the latest update fixed my issue the delete button is back.
