### ISSUE TITLE
Keyboard input in search bar eats spaces

### ISSUE THREAD

**Issue by mikelward** [home-assistant/frontend#21325]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If I try to enter a search term on the Devices or Entities page in the Android app using GBoard, the preceding space sometimes gets deleted, turning the last two words into a single word.

This seems to happen when the keyboard auto-accepts a suggestion, e.g. I type " ac " and it turns into "AC".

### Describe the behavior you expected

It should let me type and not eat spaces.

### Steps to reproduce the issue

1. Go to Entities 
2. Type "Guest room ac "

It turns into "Guest roomAC".

### What version of Home Assistant Core has the issue?

2024.7.1

### In which browser are you experiencing the issue with?

Home Assistant 2024.6.1-full

### Which operating system are you using to run this browser?

Android 14

### Additional information

https://photos.app.goo.gl/91es3LXZwhZ2HeS5A

I don't experience this in other apps, e.g. Google Keep, so I'm guessing it's something on the HA side., possibly some options, hints, or auto complete data it's setting on the input field?

**Comment by mikelward** [comment]
Actually it's eating two spaces and it's triggered after the second space " ac ".

**Comment by mikelward** [comment]
This also happens accessing my HA UI in Chrome and Edge. 

This does not happen in a plain input field in the same browsers at https://www.w3schools.com/tags/tag_input.asp.

So again, seems to be HA specific.

**Comment by mikelward** [comment]
Possibly related to https://github.com/home-assistant/frontend/commit/2113cf528073c13e81567606251f88b5bc185043

**Comment by silamon** [comment]
Probably related to that commit. I'll see if I can get it fixed, but it shouldn't take spaces in the middle of words away.
