### ISSUE TITLE
Z-Wave Add Device by scanning QR code instantly crashes Android App

### ISSUE THREAD

**Issue by TheCodeJanitor-dotcom** [home-assistant/frontend#21323]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Z-Wave JS integration, selecting Configure / Add Device, and choosing Scan QR Code causes the Android app to immediately close.

### Describe the behavior you expected

It should have opened the Scan/Camera window.

### Steps to reproduce the issue

1. Open HA for Android 2024.6.1-full
2. Select Settings, Devices & Services, Z-Wave.
3. Select Configure, press blue + Add Device button.
4. Select SCAN QR CODE
5. See "Home Assistant has stopped" popup, or app simply closes.

### What version of Home Assistant Core has the issue?

2024.7.1

### In which browser are you experiencing the issue with?

Android 2024.6.1-full

### Which operating system are you using to run this browser?

Android 14

### Problem-relevant frontend configuration

```yaml
None available
```

**Comment by tmsteinhardt** [comment]
I'm having the same issue as you've described.  Very frustrating as I can't get devices to add.

**Comment by bborgignons** [comment]
I would like to comfirm that the same happens to me (exactly as described by TheCodeJanitor-dotcom).

**Comment by rpm452** [comment]
Same problem as described above.

**Comment by br0nd** [comment]
I am experiencing same issue and just created an issue in the HA android repo which is where I think this belongs. https://github.com/home-assistant/android/issues/4514
FYI you can use a mobile browser on android phone and add devices via QR code (please try that work around for now).

**Comment by dshokouhi** [comment]
This is fixed in the app beta and will be part of the next release.
