### ISSUE TITLE
Energy dashboard does not show any energy data after update to 2024.7.1

### ISSUE THREAD

**Issue by offlinehoster** [home-assistant/frontend#21336]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since some days the energy dashboard does not show all or any energydata.

Today there is nothing displayed, yesterday online until 6 in the morning, day before was complete, and day bevor about 20h were missing.

Is there a bug with the current energy dashboard? I did not change anything on my side, the shelly 3em is working fine on another home assistant, I can see all the date on grafana (published by home assistant to influx). But on the energy dashboard there is "nothing" to see....why? 

Also no real information inside the log file....

![Bildschirmfoto vom 2024-07-08 14-48-36](https://github.com/home-assistant/frontend/assets/1618359/aa7b4cdc-5638-4fc0-88b4-daf7afe140ad)
![Bildschirmfoto vom 2024-07-08 14-48-41](https://github.com/home-assistant/frontend/assets/1618359/29931f03-28f9-4069-851d-c05b05117c30)
![Bildschirmfoto vom 2024-07-08 14-48-45](https://github.com/home-assistant/frontend/assets/1618359/13817010-04d4-49b4-967c-87e02bee4811)
![Bildschirmfoto vom 2024-07-08 14-48-31](https://github.com/home-assistant/frontend/assets/1618359/5053189b-118b-486a-83ff-3acc70e7707a)

### Describe the behavior you expected

Display energy data :) 

### Steps to reproduce the issue

Check energy data

### What version of Home Assistant Core has the issue?

2024.7.1

### In which browser are you experiencing the issue with?

Firefox 127.0.2 (64-Bit)

### Which operating system are you using to run this browser?

archlinux

**Comment by silamon** [comment]
Can you check if other entities have statistics during those periods? Looks like you're having #21278 as well.

**Comment by offlinehoster** [comment]
Well....I did a restart of home assistant today...and than suddenly I saw some data again, it looks like, that home assistant just thought all the power was generated in that moment, and put everything to the graph

![grafik](https://github.com/home-assistant/frontend/assets/1618359/c3e6ba39-aca0-4ce5-a1e2-dc7087208c01)


Other graphs are also not working...like those, temperature from KNX....

![grafik](https://github.com/home-assistant/frontend/assets/1618359/e3e9341d-ad12-4cf5-aa1a-fdac99a7b6b0)

Also the shelly stats from shelly 3em are not right

![grafik](https://github.com/home-assistant/frontend/assets/1618359/08dcdfb8-ad64-4ec5-919e-57bd01032113)


Same datasource collected by home assistant and delivered to Grafana is fine....so maybe just something around with local home assistant graph stuff?

**Comment by ThomasDesloovere** [comment]
+1 it seems to be a entity lockup after backup, homeassistant at this moment is not usable with this bug. All my entities “hang” after my nightly backup.

**Comment by fideias** [comment]
+1 one. same thing I report here. https://github.com/home-assistant/frontend/issues/21278

**Comment by silamon** [comment]
Is the problem solved when you install 2024.7.2?

**Comment by ThomasDesloovere** [comment]
Partly the entity lockup thing is solved, for me it is just the shelly integration that still has a problem where when a backup is made some devices don't reconnect (i need to manually reload some devices) so i went back to 2024.6.4 again.....

**Comment by offlinehoster** [comment]
Well....about 5 days I just removed old backups from the HomeAssistant and did a full restart...after that the graphs came back...working.

Update to latest 2024.7.2 was just 2 days ago...and it was working already before...so maybe it was the full restart, whyever, or maybe some disk usage issues?

**Comment by fideias** [comment]
HI Update to latest 2024.7.2 looks all was fixed on my end. Thanks everyone.

**Comment by MaartenMol** [comment]
I see that this issue has been closed, but since yesterday I am having the same issue.
I had version 2024.7.2, I just updated to .4 to see if this resolved it, but it didn't.

I don't know how to resolve this. Kinda stuck :(
