### ISSUE TITLE
Statistic card preview broken

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#21340]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Statistic card preview does not work on current stable HA. When you first add card it shows an error (without any text) and no matter which entity you select or which radio button you select, nothing changes in regards to preview, just an error.

If you save and then edit the card, the preview works as expected. But it doesn't work when you're adding a fresh card.

See screen recording below.

https://github.com/home-assistant/frontend/assets/9065557/b3e78260-9a07-48f3-a522-6271be918f7e

### Describe the behavior you expected

Show preview when adding new statistic card

### Steps to reproduce the issue

1. Enter dashboard edit mode, add card, Statistic card
2. Look at preview, it will be a red warning (with no text), it doesn't display

### What version of Home Assistant Core has the issue?

2024.7.1

**Comment by piitaya** [comment]
I think it should be fixed by https://github.com/home-assistant/frontend/pull/21344. I will do some tests.

**Comment by piitaya** [comment]
I tested and it's not the same issue. I will take a look to fix it 🙂
