### ISSUE TITLE
[iOS] UI zooms in when displaying keyboard

### ISSUE THREAD

**Issue by Stooovie** [home-assistant/frontend#21349]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Every time I rotate my device or tap a text field, HA UI zooms in - and never zooms back out.

[Here’s a video](https://youtube.com/shorts/07K-iX5QgNQ?si=OyLwQX2z6g-lEpzg)

I do keep the view at 85% zoom but it doesn’t make any difference. Nor does SwiftKey or the default system keyboard.

HA app on iOS fully up-to-date, versions are irrelevant as this has been going on for me for  several years.

### Describe the behavior you expected

UI either zooms back out when keyboard closes, or doesn't zoom in in the first place. 

### Steps to reproduce the issue

1. Open either HA app or HA web in iOS
2. Tap any text entry field
3. UI zooms in and stays zoomed in

### What version of Home Assistant Core has the issue?

Core-2024.7.1

### In which browser are you experiencing the issue with?

Safari, HA app

### Which operating system are you using to run this browser?

IOS 17.5.1

**Comment by Stooovie** [comment]
Nobody? This is REALLY, REALLY bad and it's been happening to me for years. The worst happens when switching to another app and then back to HA:

[Video](https://youtu.be/jql-yhj9ecQ?si=t6jNnpLf0aUykCI9)

**Comment by luciancah** [comment]
Does original UI of HA triggers the same issue as well?
I don't think I can reproduce the same issue since I'm not using a custom dashboard.

![IMG_6892](https://github.com/user-attachments/assets/6fdf38af-92d4-4e5d-b558-157ceaa795eb)
![IMG_6891](https://github.com/user-attachments/assets/1bf6d376-8238-4502-8f36-f9222fee941f)

**Comment by Stooovie** [comment]
I'd say it's actually a bug with the Safari web view, I see it in many (but not all!) web apps and HA companion app is largely a packaged web view app. 

These links talk about the same issue:

[Link 1](https://www.reddit.com/r/PWA/comments/176vpj8/ios_safari_bug_fullscreen_pwa_zooms_in_to_the/?share_id=dxVcL2Q6hfg5kV-SKjlZd&utm_content=2&utm_medium=ios_app&utm_name=ioscss&utm_source=share&utm_term=1&rdt=54900)
[Link 2](https://discussions.apple.com/thread/252945522?sortBy=best)

 It goes back to at the very least 2019.

**Comment by luciancah** [comment]
I am aware that webkit has some problems causing unexpected zoom-ins, but I can't find any other issues that are occurring on HA web..
Perhaps you could share any theme or dashboard preferences you're using?

**Comment by Stooovie** [comment]
I use Noctis theme. I'll try using the default HA theme for a while and see if the issue occurs. I didn't think this could be caused by a theme. Thanks for your help so far!

**Comment by Stooovie** [comment]
Sadly no, it happens with the default theme as well. What can I do to help troubleshoot more?

**Comment by Stooovie** [comment]
It seems that removing the card-tools addon that hasn't been updated in three years fixed it. It didn't happen in more than a day. Too bad as it powers my favorite Search bar card, but oh well.

**Comment by luciancah** [comment]
Glad you finally fixed it anyway. I don't see any 'default' search bar on dashboard, maybe one you're using was [this one](https://github.com/thomasloven/lovelace-card-tools)?

**Comment by Stooovie** [comment]
This Search card. It enables you to directly control stuff from it. It's incredibly handy but it's built upon the addon that you linked to, that hasn't been updated for more than three years.

**Comment by luciancah** [comment]
Aah thanks for kindly pointing one out for me. I'll let you know if I can make a contribution or fork and refactor it.

**Comment by Stooovie** [comment]
> Aah thanks for kindly pointing one out for me. I'll let you know if I can make a contribution or fork and refactor it.

that would be absolutely amazing

**Comment by luciancah** [comment]
btw I think this issue should be closed since it's a problem of a 3rd party component, but I'm quite sure you can still get notifications from this threads after the issue is closed.
