### ISSUE TITLE
Some bugs with apexcharts last update 

### ISSUE THREAD

**Issue by LioBoul** [home-assistant/frontend#21352]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since the last Apexcharts update, I have a few small bugs:
- extrema shifts
- the chart is not displayed if one of the values ​​is show: in_chart: false (I got around this problem with full opacity)

Bugs only with Fullykiosk browser, not Chrome.
Cache cleared.

![Capture d’écran 2024-07-10 114038](https://github.com/home-assistant/frontend/assets/162896032/bd9b2170-2f84-4363-9c82-63e83954802c)

### Describe the behavior you expected

Bug with apexcharts

### Steps to reproduce the issue

1. display apexcharts

### What version of Home Assistant Core has the issue?

2024.7.1

### What was the last working version of Home Assistant Core?

2024.7.1

**Comment by silamon** [comment]
Those are custom resources, which are maintained elsewhere.

**Comment by LioBoul** [comment]
Problem only with Fullykiosk...?

**Comment by silamon** [comment]
You can report your issue over here: https://github.com/RomRider/apexcharts-card
If you can tick off the fourth checkbox and reproduce your bug with safe mode, we're happy to take a look.
