### ISSUE TITLE
Icons within thermostad card not recognised

### ISSUE THREAD

**Issue by TimBeekman** [home-assistant/frontend#21366]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The problem occurs within the thermostat card.

See the availible fan and swing modes:
![image](https://github.com/home-assistant/frontend/assets/89469564/f92399b6-458d-4ccd-a9f8-7c6ba312f300)

The UI translates it to:
![image](https://github.com/home-assistant/frontend/assets/89469564/391d166d-daf7-46ac-81fa-354d2964559e)

You can see that the icons like mdi:fan-speed-1 is not being applied. There is no way for me to manually define the icon.

### Describe the behavior you expected

I expected the proper icons to show up, or being able to self define the icons

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.7.2

### In which browser are you experiencing the issue with?

Most recent Chrome and Edge

### Which operating system are you using to run this browser?

Windows

**Comment by karwosts** [comment]
Icons are defined by the integration providing your climate entity. If they are missing, you would need to check with that integration author. There's no way for users to define or modify them.

**Comment by TimBeekman** [comment]
Thanks for pointing me in the right direction for reporting this issue at the right place. I will raise this issue at the integration maintainers. 

Would it be possible to allow the end user to define the icon within the card? HA has always been great with customization, and I believe this would be a valuable addition.

**Comment by karwosts** [comment]
I think overridable icons is a reasonable idea, there are many people who have this problem. 

I can't be sure the maintainers will go for it, but perhaps the best thing for that idea would be to open a feature request over in **Discussions** or in the community forum. (or check if one exists already).

**Comment by TimBeekman** [comment]
Thanks for the information. I will close this issue and open a feature request!
