### ISSUE TITLE
Edit ID causes visual issue (FireFox)

### ISSUE THREAD

**Issue by HA-Master-User** [home-assistant/frontend#21367]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When adding a "When" condition and minimizing it, clicking on the 3 "..." and select "Edit ID", the screen looks like this:

![grafik](https://github.com/home-assistant/frontend/assets/174940893/b74dc91b-b0ce-4fa4-a81d-b56566d695dd)

### Describe the behavior you expected

The menu should be expanded normally

### Steps to reproduce the issue

1. Create new blank automation
2. add a "When" condition and minimize it
3. click on the 3 dots
4. click "Edit ID"

### What version of Home Assistant Core has the issue?

2024.7.2

### What was the last working version of Home Assistant Core?

2024.7.1

### In which browser are you experiencing the issue with?

Firefox 127.0.2 and 128.0

### Which operating system are you using to run this browser?

Win 11 x64

### Additional information

This was fine in the previous version.
Edge is fine in both versions of HA

**Comment by tinyoverflow** [comment]
Unfortunately I cannot reproduce this on Firefox 128.0. Please test:

1. Does this also happen without any browser extensions (eg. use a private window).
2. Do you have any frontend theme installed or custom CSS enabled? Try disabling them.
3. Clear your browsers cache (eg. hard refresh with Ctrl+Shift+R) or:
https://support.mozilla.org/en-US/kb/how-clear-firefox-cache


https://github.com/user-attachments/assets/26eef887-b94b-4d60-bcd2-2c2bae31bc59

**Comment by HA-Master-User** [comment]
Hi @tinyoverflow 

This is strange, today I can no longer reproduce this. i had this for like 3 days and I was clearing the cache and trying different things. Now this is gone.

Thanks for checking
