### ISSUE TITLE
Name and Icons are not rendered for data entry flow sections

### ISSUE THREAD

**Issue by basbruss** [home-assistant/frontend#21378]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The UI does not show any name or icon set by the newly introduced data entry flows introduced with core-2024.7.0.
<img width="1053" alt="image" src="https://github.com/user-attachments/assets/c3616df5-6c7d-4c64-86d8-b1d0723007bd">

### Describe the behavior you expected

I expected to see the name of the section accompanied by an icon set in icons.json

### Steps to reproduce the issue

1. configure `kitchen_sink` 
2. click on configure on the integrations' page
3.
...

### What version of Home Assistant Core has the issue?

2024.7.2

**Comment by karwosts** [comment]
Related: https://github.com/home-assistant/core/issues/121110

I did discuss this briefly with Bram on discord and there seems to have been a miscommunication between frontend and backend about how this would work. He claimed he would look into it.
