### ISSUE TITLE
energy panel Sum kw Sources 

### ISSUE THREAD

**Issue by Thassoni** [home-assistant/frontend#21384]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

![Screenshot_20240710_014510_Home Assistant](https://github.com/user-attachments/assets/2f5b774f-ad4e-4f41-b5c4-30295b9c8a48)

### Describe the behavior you expected

You can see In the total energy consumption 12.24 kwh, there are already 5.11 kw included which is the consumption of one identity taken, and therefore the total 17.36 kw, not good It' Not good; therefore a flag must be applied that can tell the single entity to be added or excluded from the total sum of the source panel. 

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Ha Green

### State of relevant entities

```txt
Nn
```

### Problem-relevant frontend configuration

```yaml
Nn
```

### Javascript errors shown in your browser console/inspector

```txt
Nn
```

### Additional information

Nn

**Comment by karwosts** [comment]
This is a new feature request, not a bug. You can request new options and functionality under discussions or on the community forum.
