### ISSUE TITLE
Unable to edit dashboard view type from UI

### ISSUE THREAD

**Issue by nono313** [home-assistant/frontend#21395]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I am unable to change the view type or to create a new view on a newly created dashboard (not default dashboard).

I tried with Firefox in normal mode, Firefox in incognito mode, Chromium in normal mode and Chromium in incognito mode : I always get the same behavior.

### Describe the behavior you expected

A popup should open to choose the view type but nothing happens

### Steps to reproduce the issue

1. Create a new dashboard from the settings
2. Go to the new dashboard
3. Enter edit mode using ... menu
4. When I click on the pen next to 'Home' or on the + sign to add a new view, nothing happens

### What version of Home Assistant Core has the issue?

2024.7.2 and 2024.7.1

### In which browser are you experiencing the issue with?

Firefox 127 and Chromium 126

### Which operating system are you using to run this browser?

Archlinux

**Comment by karwosts** [comment]
Is there any error in the browser console?

**Comment by nono313** [comment]
I just checked and yes I have this error in my web console:

```
Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-linear-progress" has already been used with this registry
    define scoped-custom-element-registry.js:44
    n custom-element.ts:21
    n custom-element.ts:64
    s tslib.es6.mjs:58
    18971 mwc-linear-progress.ts:23
    a async module:49
    18971 mwc-linear-progress.css.ts:7
    Webpack 57
        c
        23011
        a
        23011
        c
        61327
        a
        61327
        c
        46182
        a
        46182
        c
        39223
        a
        39223
        c
        33078
        a
        33078
        c
        promise callback*dialogImport
        l
        registerDialog
        n
        s
        value
        handleEvent
        _$AI
        v
        g
        _$AI
        v
        g
        _$AI
        T
        _$AI
        v
        g
        _$AI
        v
        g
        _$AI
        q
        update
        performUpdate
        scheduleUpdate
        _$Ej
        requestUpdate
        set
        j
        _$AI
        v
        g
        _$AI
        q
        update
app.hoOvmAWTvos.js:2
```

**Comment by karwosts** [comment]
I would try safe mode. Seems like there might be some custom plugin you have installed that might be interfering.

**Comment by nono313** [comment]
It works in safe mode. How can I figure out which plugin causes the issue now ? Do I have to disable them one by one ?
