### ISSUE TITLE
I was stuck in kiosk mode

### ISSUE THREAD

**Issue by sdmorris1950** [home-assistant/frontend#21393]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I installed Kiosk Mode and enabled it, with kiosk: true, in one dashboard and then found that the header and sidebar were hidden for all my dashboards. I tried opening them with ?disable_km, but it did not help.
My browser is up-to-date 64-bit Chrome running on Win10 and HA is 2024.7.1
I edited the dashboard that I had added Kiosk Mode to and set kiosk: false, but that did not help.
I tried restarting HA; I tried restarting the browser; I tried clearing the cache.
Finally, I deleted my cookies from the previous hour and only then did the dashboards return to normal.

### Describe the behavior you expected

I expected that Kiosk Mode would only apply to the dashboard where I set it.

### Steps to reproduce the issue

1.add kiosk_mode: 
            kiosk: false
to one dashboard and refresh it.

### What version of Home Assistant Core has the issue?

2024.7.1

### In which browser are you experiencing the issue with?

Chrome Version 126.0.6478.127 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

windows 10 home

**Comment by karwosts** [comment]
AFAIK this is custom card functionality, you would need to discuss this with the developer of this feature, this isn't supported by frontend.
