### ISSUE TITLE
Can't add integrations

### ISSUE THREAD

**Issue by JHenzi** [home-assistant/frontend#21411]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When attempting to add an integration I get the following error message in the console and the dialogue shows the spinning circle.

`dialog-add-integration.ts:381 Uncaught (in promise)`

There is a PiHole on the network but this behavior is the same regardless of it being enabled or host/client using it to filter requests.

### Describe the behavior you expected

I expect the integration list to load or be searchable.

### Steps to reproduce the issue

1. Navigate to integrations page (/config/integrations)
2. Add Integration from lower right corner

### What version of Home Assistant Core has the issue?

2024.7.2

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

macOS, iOS

### Javascript errors shown in your browser console/inspector

```txt
See above uncaught exception on line 381.
```

**Comment by silamon** [comment]
Can you post the whole stack trace from the developer console?

**Comment by JHenzi** [comment]
This?

[Trace-20240719T145721.json](https://github.com/user-attachments/files/16316118/Trace-20240719T145721.json)

**Comment by silamon** [comment]
No, that's not what we're looking for to help you further. What browser are you using on Mac? If chrome, edge or firefox, you can open the dev tools, repeat the steps and copy the full stack trace.
