### ISSUE TITLE
Color Temperature Slider does not load in blueprint

### ISSUE THREAD

**Issue by HarvsG** [home-assistant/frontend#21412]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

See this stale issue: https://github.com/home-assistant/frontend/issues/14440

 ![image](https://github.com/user-attachments/assets/e19805a8-545a-4263-bb8b-7c458e70e0d7)

### Describe the behavior you expected

For it to look as it does in the service call ui
![image](https://github.com/user-attachments/assets/9c5c71f6-c40c-4c04-a177-ec462f2af3bc)

### Steps to reproduce the issue

Step 1: Import a blueprint that includes a color_temp selector such as this one: https://community.home-assistant.io/t/automatic-circadian-lighting-match-your-lights-color-temperature-to-the-sun/472105 that I maintain.
Step 2: See uglines

### What version of Home Assistant Core has the issue?

2024.7.2

### What was the last working version of Home Assistant Core?

2022.9

### In which browser are you experiencing the issue with?

Google Chrome and MS Edge

### Which operating system are you using to run this browser?

Windows 11

### Javascript errors shown in your browser console/inspector

None: 
![image](https://github.com/user-attachments/assets/0a41ceb5-1a38-443b-a978-ed5065122ff6)

### Additional information

When I inspect the css

Working slider
```css
linear-gradient( to var(--float-end), #ff890e 0%, #ff9d41 10%, #ffae67 20%, #ffbc84 30.000000000000004%, #ffc99d 40%, #ffd4b1 50%, #ffdec3 60.00000000000001%, #ffe7d3 70%, #ffefe1 80%, #fff7ee 90%, #fffefa 100%)
```
Broken slider
```css
linear-gradient( to var(--float-end), #ff1b00 0%, #ff1500 10%, #ff0d00 20%, #ff0500 30.000000000000004%, #ff0000 40%, #ff0000 50%, #ff0000 60.00000000000001%, #ff0000 70%, #ff0000 80%, #ff0000 90%, #ff0000 100%)
```

**Comment by karwosts** [comment]
I think your blueprint seems wrong, you seemingly have Kelvin for min and max but you have unit: mired. 
```
        color_temp:
          min: 1500
          max: 4500
          unit: mired
```

AFAIK mireds should be in like the 100-500 range? That's why it's a red bar, because it's off the charts to the low end of the color temperature scale.

**Comment by HarvsG** [comment]
> I think your blueprint seems wrong, you seemingly have Kelvin for min and max but you have unit: mired.
> 
> ```
>         color_temp:
>           min: 1500
>           max: 4500
>           unit: mired
> ```
> 
> AFAIK mireds should be in like the 100-500 range? That's why it's a red bar, because it's off the charts to the low end of the color temperature scale.

You're looking at the wrong gist, I hope, this is the one I am using, and has the issue https://gist.github.com/HarvsG/cc86381dc99169159d6d4cd870c36e46

**Comment by HarvsG** [comment]
> I think your blueprint seems wrong, you seemingly have Kelvin for min and max but you have unit: mired.
> 
> ```
>         color_temp:
>           min: 1500
>           max: 4500
>           unit: mired
> ```
> 
> AFAIK mireds should be in like the 100-500 range? That's why it's a red bar, because it's off the charts to the low end of the color temperature scale.

But you nailed it, the `unit: mired` was being added because it is the default. I thought that HA switched to using kelvin by default in 2022.9!

**Comment by karwosts** [comment]
Huh... hm not sure how I ended up with an old version or something.

Anyway just deleted and reimported and I see this:

![image](https://github.com/user-attachments/assets/5b17e1e5-57c5-47ac-8745-53fa41126e22)

**Comment by HarvsG** [comment]
> Huh... hm not sure how I ended up with an old version or something.
> 
> Anyway just deleted and reimported and I see this:
> 
> ![image](https://private-user-images.githubusercontent.com/32912880/349241096-5b17e1e5-57c5-47ac-8745-53fa41126e22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNTY4NjgsIm5iZiI6MTcyMTE1NjU2OCwicGF0aCI6Ii8zMjkxMjg4MC8zNDkyNDEwOTYtNWIxN2UxZTUtNTdjNS00N2FjLTg3NDUtNTNmYTQxMTI2ZTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE5MDI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5YTM3YjM2M2I1ZDlhYjM2OGRkMzg3ZDY3MGQ4NDYwN2UwN2E2ZmZhYzdhMGQxMWExNDBhYzM5OTM4ZDI5MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X5mIyCkU0YBMqK-nMlGyHcBhslPs9Q1y3YkySrZTlQ8)

See my comments above. Your point made me realise my mistake, thank you. I have now updated the Blue print which is why it is working.
