### ISSUE TITLE
Energy dashboard - resetting problem after midnight

### ISSUE THREAD

**Issue by AlfaBravoX** [home-assistant/frontend#21425]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In Energy dashboard I have wrong data in bar every day right after midnight. I'm using simple sensor from Tasmota. Total daily data are being send via mqtt telemetry with Teleperiod of 30 seconds for 3 phases L1,L2,L3 and at Home Assistant level they are merged to sensor Total daily.  Date and time from Tasmota are NTP synced, hass is NTP synced as well, they have 100% match.

It is clear that the VERY FIRST message that Tasmota device telemetry sends after midnight is correct. Dashboard shows nonsense in the first bar hour after midnight.

`{"Time":"2024-07-16T23:59:26","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.903,2841.010,2435.306],"Yesterday":[1.040,0.123,0.402],"Today":[1.192,0.124,0.400],"Period":[0,0,1],"Power":[62,5,17],"ApparentPower":[117,12,29],"ReactivePower":[100,10,24],"Factor":[0.53,0.46,0.57],"Frequency":[50,50,49],"Voltage":[235.2,234.1,234.4],"Current":[0.499,0.050,0.124]}}
{"Time":"2024-07-16T23:59:56","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.904,2841.010,2435.306],"Yesterday":[1.040,0.123,0.402],"Today":[1.193,0.124,0.400],"Period":[1,0,0],"Power":[62,5,17],"ApparentPower":[117,12,29],"ReactivePower":[100,10,24],"Factor":[0.53,0.46,0.57],"Frequency":[50,50,49],"Voltage":[235.8,234.6,234.8],"Current":[0.496,0.050,0.123]}}
{"Time":"2024-07-17T00:00:26","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.905,2841.010,2435.306],"Yesterday":[1.193,0.124,0.400],"Today":[0.001,0.000,0.000],"Period":[1,0,0],"Power":[62,5,17],"ApparentPower":[119,12,30],"ReactivePower":[102,11,25],"Factor":[0.52,0.45,0.56],"Frequency":[50,50,48],"Voltage":[235.7,234.4,234.5],"Current":[0.506,0.051,0.127]}}
{"Time":"2024-07-17T00:00:56","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.905,2841.010,2435.306],"Yesterday":[1.193,0.124,0.400],"Today":[0.001,0.000,0.000],"Period":[0,0,0],"Power":[61,5,17],"ApparentPower":[118,12,29],"ReactivePower":[101,10,24],"Factor":[0.52,0.46,0.58],"Frequency":[50,50,48],"Voltage":[235.6,234.2,234.5],"Current":[0.500,0.050,0.123]}}
{"Time":"2024-07-17T00:01:26","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.905,2841.010,2435.306],"Yesterday":[1.193,0.124,0.400],"Today":[0.001,0.000,0.000],"Period":[0,0,0],"Power":[61,5,17],"ApparentPower":[118,12,30],"ReactivePower":[101,11,25],"Factor":[0.52,0.44,0.56],"Frequency":[50,50,48],"Voltage":[235.6,234.4,234.6],"Current":[0.500,0.050,0.127]}}
{"Time":"2024-07-17T00:01:56","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.906,2841.010,2435.306],"Yesterday":[1.193,0.124,0.400],"Today":[0.002,0.000,0.000],"Period":[1,0,0],"Power":[61,5,17],"ApparentPower":[117,12,30],"ReactivePower":[100,11,25],"Factor":[0.52,0.44,0.55],"Frequency":[50,50,48],"Voltage":[235.6,234.5,234.6],"Current":[0.498,0.050,0.129]}}
{"Time":"2024-07-17T00:02:26","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.906,2841.010,2435.306],"Yesterday":[1.193,0.124,0.400],"Today":[0.002,0.000,0.000],"Period":[0,0,0],"Power":[62,6,17],"ApparentPower":[117,12,29],"ReactivePower":[99,11,23],"Factor":[0.53,0.46,0.58],"Frequency":[50,50,48],"Voltage":[235.1,233.9,234.0],"Current":[0.497,0.051,0.122]}}
{"Time":"2024-07-17T00:02:56","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.907,2841.010,2435.306],"Yesterday":[1.193,0.124,0.400],"Today":[0.003,0.000,0.000],"Period":[1,0,0],"Power":[62,6,17],"ApparentPower":[117,12,29],"ReactivePower":[99,11,24],"Factor":[0.53,0.47,0.57],"Frequency":[50,50,48],"Voltage":[235.0,233.8,233.8],"Current":[0.496,0.051,0.124]}}
{"Time":"2024-07-17T00:03:26","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.907,2841.010,2435.307],"Yesterday":[1.193,0.124,0.400],"Today":[0.003,0.000,0.001],"Period":[0,0,1],"Power":[61,5,17],"ApparentPower":[116,11,28],"ReactivePower":[99,10,23],"Factor":[0.53,0.44,0.58],"Frequency":[50,50,48],"Voltage":[234.7,233.8,233.8],"Current":[0.495,0.049,0.121]}}
{"Time":"2024-07-17T00:03:56","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.908,2841.010,2435.307],"Yesterday":[1.193,0.124,0.400],"Today":[0.004,0.000,0.001],"Period":[1,0,0],"Power":[62,5,17],"ApparentPower":[117,12,28],"ReactivePower":[99,10,23],"Factor":[0.53,0.45,0.58],"Frequency":[50,50,48],"Voltage":[234.9,233.8,234.1],"Current":[0.497,0.050,0.121]}}
{"Time":"2024-07-17T00:04:26","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.909,2841.010,2435.307],"Yesterday":[1.193,0.124,0.400],"Today":[0.005,0.000,0.001],"Period":[1,0,0],"Power":[61,5,17],"ApparentPower":[116,12,30],"ReactivePower":[99,11,25],"Factor":[0.53,0.45,0.55],"Frequency":[50,50,48],"Voltage":[235.2,234.1,234.3],"Current":[0.495,0.051,0.127]}}
{"Time":"2024-07-17T00:04:56","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.909,2841.010,2435.307],"Yesterday":[1.193,0.124,0.400],"Today":[0.005,0.000,0.001],"Period":[0,0,0],"Power":[62,6,17],"ApparentPower":[117,12,29],"ReactivePower":[100,11,24],"Factor":[0.52,0.46,0.57],"Frequency":[50,50,48],"Voltage":[235.3,234.1,234.2],"Current":[0.499,0.052,0.123]}}
{"Time":"2024-07-17T00:05:26","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.909,2841.010,2435.307],"Yesterday":[1.193,0.124,0.400],"Today":[0.005,0.000,0.001],"Period":[0,0,0],"Power":[61,5,17],"ApparentPower":[117,12,29],"ReactivePower":[99,11,24],"Factor":[0.53,0.44,0.56],"Frequency":[50,50,48],"Voltage":[235.2,234.1,234.1],"Current":[0.496,0.050,0.126]}}
{"Time":"2024-07-17T00:05:56","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.910,2841.010,2435.307],"Yesterday":[1.193,0.124,0.400],"Today":[0.006,0.000,0.001],"Period":[1,0,0],"Power":[61,5,17],"ApparentPower":[117,12,29],"ReactivePower":[99,11,24],"Factor":[0.53,0.44,0.56],"Frequency":[50,50,48],"Voltage":[235.1,233.9,233.9],"Current":[0.497,0.050,0.126]}}
{"Time":"2024-07-17T00:06:26","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.911,2841.010,2435.307],"Yesterday":[1.193,0.124,0.400],"Today":[0.007,0.000,0.001],"Period":[1,0,0],"Power":[61,6,17],"ApparentPower":[117,12,30],"ReactivePower":[99,11,25],"Factor":[0.53,0.47,0.56],"Frequency":[50,50,48],"Voltage":[235.7,234.4,234.5],"Current":[0.495,0.051,0.127]}}
{"Time":"2024-07-17T00:06:56","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.911,2841.010,2435.307],"Yesterday":[1.193,0.124,0.400],"Today":[0.007,0.000,0.001],"Period":[0,0,0],"Power":[61,5,17],"ApparentPower":[117,12,29],"ReactivePower":[99,10,24],"Factor":[0.53,0.45,0.56],"Frequency":[50,50,48],"Voltage":[235.0,233.7,233.8],"Current":[0.497,0.050,0.125]}}
{"Time":"2024-07-17T00:07:26","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.912,2841.011,2435.307],"Yesterday":[1.193,0.124,0.400],"Today":[0.008,0.001,0.001],"Period":[1,1,0],"Power":[61,5,16],"ApparentPower":[117,12,29],"ReactivePower":[100,10,25],"Factor":[0.52,0.46,0.56],"Frequency":[50,50,48],"Voltage":[234.9,233.6,233.8],"Current":[0.498,0.050,0.126]}}
{"Time":"2024-07-17T00:07:56","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.912,2841.011,2435.308],"Yesterday":[1.193,0.124,0.400],"Today":[0.008,0.001,0.002],"Period":[0,0,1],"Power":[61,5,17],"ApparentPower":[117,12,29],"ReactivePower":[100,10,24],"Factor":[0.52,0.45,0.57],"Frequency":[50,50,48],"Voltage":[235.3,234.0,234.1],"Current":[0.497,0.050,0.124]}}
{"Time":"2024-07-17T00:08:26","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.913,2841.011,2435.308],"Yesterday":[1.193,0.124,0.400],"Today":[0.009,0.001,0.002],"Period":[1,0,0],"Power":[61,5,17],"ApparentPower":[116,12,30],"ReactivePower":[98,11,25],"Factor":[0.53,0.44,0.55],"Frequency":[50,50,48],"Voltage":[235.2,234.0,234.2],"Current":[0.493,0.050,0.127]}}
{"Time":"2024-07-17T00:08:56","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.913,2841.011,2435.308],"Yesterday":[1.193,0.124,0.400],"Today":[0.009,0.001,0.002],"Period":[0,0,0],"Power":[61,6,17],"ApparentPower":[116,12,30],"ReactivePower":[98,10,25],"Factor":[0.53,0.47,0.55],"Frequency":[50,50,48],"Voltage":[235.4,234.1,234.3],"Current":[0.492,0.050,0.128]}}
{"Time":"2024-07-17T00:09:26","ENERGY":{"TotalStartTime":"2022-06-25T10:13:13","Total":[3711.914,2841.011,2435.308],"Yesterday":[1.193,0.124,0.400],"Today":[0.010,0.001,0.002],"Period":[1,0,0],"Power":[61,5,17],"ApparentPower":[117,12,30],"ReactivePower":[99,11,25],"Factor":[0.53,0.45,0.56],"Frequency":[50,50,48],"Voltage":[235.8,234.5,234.8],"Current":[0.495,0.050,0.127]}}`

etc.. more lines omited

<img width="704" alt="image" src="https://github.com/user-attachments/assets/2932f2fc-00ee-4bfc-9bf4-893d0dcaf8b1">

### Describe the behavior you expected

First bar in Enenrgy dashboard will match data sent in JSON telemetry according to key "Today"

### Steps to reproduce the issue

1. Define sensor sending telemetry with energy data incl. increasing Today 
2. Set this sensor in dashboard as consumption
3. Generate some consumption before midnight 
4. Wait till midnight
5. check Energy dashboard
...

### What version of Home Assistant Core has the issue?

2024.7.2

### What was the last working version of Home Assistant Core?

2024.7.2

**Comment by karwosts** [comment]
Energy dashboard just reports what the statistics platform provides. 

If the statistics is providing has the wrong data, that would need to be looked at as a backend issue. 

But to debug further from an energy perspective, you would need to look at what values the statistics is actually providing for this entity.

**Comment by AlfaBravoX** [comment]
OK, so another example from today (I already fixed stats from the graph above) 

<img width="480" alt="image" src="https://github.com/user-attachments/assets/afbf5e6f-d73b-47b7-acda-d6db877ccf80">

2.55kWh
between 00:00 - 00:05
<img width="386" alt="image" src="https://github.com/user-attachments/assets/eb75375d-d735-4620-8686-8375963fdfe4">

previous day finished at 1.83kWh

<img width="717" alt="image" src="https://github.com/user-attachments/assets/340a76c8-6557-4a4e-8f25-5d5b35c75be7">

there is no such consumption of 2.55kWh for whole previous day in total. so where the bigger data is coming from ??

**Comment by AlfaBravoX** [comment]
Issue resolved, details can be found here https://community.home-assistant.io/t/energy-dashboard-shows-false-consumption-every-day-right-after-midnight/750628?u=alfabravox
