### ISSUE TITLE
Can't use trigger selector in config flows

### ISSUE THREAD

**Issue by dougiteixeira** [home-assistant/frontend#21427]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When attempting to use a trigger selector in a config flow, the form is not displayed and some errors are displayed in the browser console.

### Describe the behavior you expected

Make it possible to use the trigger selector in configuration flows.

### Steps to reproduce the issue

-

### What version of Home Assistant Core has the issue?

core-2024.8.0.dev0 / frontend-20240710.0

### Javascript errors shown in your browser console/inspector

```txt
compute-initial-ha-form-data.ts:102 Uncaught (in promise) Error: Selector trigger not supported in initial form data
    at compute-initial-ha-form-data.ts:102:15
    at Array.forEach (<anonymous>)
    at o (compute-initial-ha-form-data.ts:8:10)
    at o.value (step-flow-form.ts:146:22)
    at o.value (step-flow-form.ts:50:27)
    at o.update (lit-element.ts:160:24)
    at o.performUpdate (reactive-element.ts:1329:14)
    at o.scheduleUpdate (reactive-element.ts:1261:17)
    at o._$Ej (reactive-element.ts:1233:25)
(anonymous) @ compute-initial-ha-form-data.ts:102
o @ compute-initial-ha-form-data.ts:8
value @ step-flow-form.ts:146
value @ step-flow-form.ts:50
update @ lit-element.ts:160
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
w @ reactive-element.ts:931
x @ lit-element.ts:115
o @ step-flow-form.ts:30
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
v @ lit-html.ts:1192
g @ lit-html.ts:1553
_$AI @ lit-html.ts:1384
v @ lit-html.ts:1192
g @ lit-html.ts:1540
_$AI @ lit-html.ts:1384
q @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ dialog-data-entry-flow.ts:388
await in value (async)
(anonymous) @ dialog-data-entry-flow.ts:341
n @ fire_event.ts:76
value @ step-flow-menu.ts:60
handleEvent @ lit-html.ts:2018
log-message.ts:36 
        
        
       GET http://127.0.0.1:8123/unknown/src/lit-element.ts 404 (Not Found)
(anonymous) @ stacktrace-gps.js:37
r @ stacktrace-gps.js:23
(anonymous) @ stacktrace-gps.js:218
_get @ stacktrace-gps.js:195
(anonymous) @ stacktrace-gps.js:289
findFunctionName @ stacktrace-gps.js:287
(anonymous) @ stacktrace-gps.js:272
Promise.then (async)
(anonymous) @ stacktrace-gps.js:267
pinpoint @ stacktrace-gps.js:266
(anonymous) @ stacktrace.js:113
(anonymous) @ stacktrace.js:108
(anonymous) @ stacktrace.js:107
fromError @ stacktrace.js:105
t @ log-message.ts:36
(anonymous) @ logging-mixin.ts:66
Show 13 more frames
Show less
log-message.ts:36 
        
        
       GET http://127.0.0.1:8123/unknown/src/reactive-element.ts 404 (Not Found)
(anonymous) @ stacktrace-gps.js:37
r @ stacktrace-gps.js:23
(anonymous) @ stacktrace-gps.js:218
_get @ stacktrace-gps.js:195
(anonymous) @ stacktrace-gps.js:289
findFunctionName @ stacktrace-gps.js:287
(anonymous) @ stacktrace-gps.js:272
Promise.then (async)
(anonymous) @ stacktrace-gps.js:267
pinpoint @ stacktrace-gps.js:266
(anonymous) @ stacktrace.js:113
(anonymous) @ stacktrace.js:108
(anonymous) @ stacktrace.js:107
fromError @ stacktrace.js:105
t @ log-message.ts:36
(anonymous) @ logging-mixin.ts:66
Show 13 more frames
Show less
```

**Comment by karwosts** [comment]
I guess probably we just want to add:

```
"trigger" in selector ||
"condition" in selector ||
```

right here: https://github.com/home-assistant/frontend/blob/dev/src/components/ha-form/compute-initial-ha-form-data.ts#L96

below the action selector. 

If you're not able to test it (don't know if you have a dev frontend), can you link a core PR# that uses this so it can be tested?

**Comment by dougiteixeira** [comment]
First of all, thank you very much for pointing out the solution.

I set up the frontend dev environment and was able to test, that's right. I opened PR #21431.

About a PR in the core to test the change, I don't have one yet, as I'm still studying it (the use case is to configure template entities with triggers via UI), if you want I can create a more generic PR just to test this change.

**Comment by dougiteixeira** [comment]
Another subject, but if you can help me with the direction to the solution, when the selector is defined as required in the config flow schema, the selector does not appear (only the field name appears). When changing to optional the selector works correctly.

**Comment by karwosts** [comment]
If you can put up just a generic draft core PR that can reproduces this error signature I can see why it's throwing errors. 

You can try this instead, but I'm not sure if it's correct or not, just a guess:

```
      } else if (
        "trigger" in selector ||
        "condition" in selector ||
        "action" in selector
      ) {
        data[field.name] = [];
      } else if (
        "media" in selector ||
        "target" in selector
      ) {
        data[field.name] = {};
      }
