### ISSUE TITLE
Inconsistent spacing offset for menu tab titles

### ISSUE THREAD

**Issue by kelilive** [home-assistant/frontend#21454]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

![Map](https://github.com/user-attachments/assets/4c48dad6-09a2-48f3-9e7e-315b110033a7)
![HACS](https://github.com/user-attachments/assets/5b103359-3740-4757-84fa-557dc89d5580)

### Describe the behavior you expected

Menu title styles should be consistent unless there are specific and insurmountable problems.

### Steps to reproduce the issue

If you look closely you will notice that the menu text of the tabs is slightly offset, this was discovered by pressing F12.

### What version of Home Assistant Core has the issue?

core-2024.7.3

**Comment by ildar170975** [comment]
Consider as closed due to https://github.com/home-assistant/frontend/pull/22568
