### ISSUE TITLE
Dev tools -> Services: calling a service with wrong data does not return an error

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#21473]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Dev tools -> Services:
Switch to yaml mode and call a service:
```
service: camera.snapshot
target:
  entity_id: camera.xxxxx
data:
  filename: /config/www/images/snapshots/1.jpg
```
with a non-existing `camera.xxxxx`.
The result SEEMS to be OK - note a green mark:
![изображение](https://github.com/user-attachments/assets/db4e7dca-05b6-491b-9f01-183ffdde21cf)

Log contains a warning:
2024-07-25 21:28:44.952 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities camera.xxxxx are missing or not currently available

### Describe the behavior you expected

1. This should be treated as an error, not a warning.
2. A red "error" mark should be shown instead of a green one.

### Steps to reproduce the issue

see above

### What version of Home Assistant Core has the issue?

2024.7.1

### In which browser are you experiencing the issue with?

Chrome 126.0.6478.127

### Which operating system are you using to run this browser?

Win10x64

**Comment by karwosts** [comment]
This would be a question for backend, frontend just calls the service and reports what errors are returned to it (which in this case there are no errors returned)

**Comment by ildar170975** [comment]
> It's not obvious to me you want any invalid entity to be a service error, as then if you have an automation action with 100 targets, and one of the entities is deleted, it will halt the entire automation. But this isn't really the place to debate it.

See your point.
This is not about "halting" - it's about informing a user about wrong input. Not all users have a habit to check a Log after every service call.

Will move this issue to core.
