### ISSUE TITLE
Template helpers erroneously display pencil-off indicating non editable (niet beheerbaar)

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#21531]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Btw very confusing on the helpers page is that many of the Yaml template sensors listed here are showing the pencil-off, indicating they are created in Yaml. 

But, it also indicates they are not editable, 
<img width="245" alt="Scherm­afbeelding 2024-08-01 om 13 22 38" src="https://github.com/user-attachments/assets/84f0220e-50c3-4dc9-9521-98231f0fe6ae">
which in fact they are. They all have a unique_id, as is demonstrated when opening the more-info

<img width="1156" alt="Scherm­afbeelding 2024-08-01 om 10 38 14" src="https://github.com/user-attachments/assets/7ab3539b-3355-469d-8895-661f9d0c911c">

<img width="590" alt="Scherm­afbeelding 2024-08-01 om 10 38 28" src="https://github.com/user-attachments/assets/c9e09c83-1504-4051-a455-7c56180af86c">

### Describe the behavior you expected

My suggestion for the pencil-off would be to use another icon to  indicate the entity is a Yaml configured entity or a UI entity.

right now, the pencil-off is used for both yaml, and not editable, and that is not correct. as is demonstrated above.

since this is in the release notes:

> Integrations originating from manual YAML configuration can be recognized by the  icon showing on their cards.

maybe a great idea to use that same icon here, for entities created in manual Yaml?
would make it consistent.

<img width="885" alt="Scherm­afbeelding 2024-08-01 om 16 50 41" src="https://github.com/user-attachments/assets/e0b7537e-4cb2-4205-b087-74849a4e86ad">

___
However:

given the fact the {} symbolize templates in HA, as is also demonstrated when you add a new helper, 

<img width="498" alt="Scherm­afbeelding 2024-08-01 om 16 53 17" src="https://github.com/user-attachments/assets/2b180ac0-df9c-4814-9d27-2ae1a9a656b3">

wouldnt it be more succinct to use another icon to indicate an entity/integration originates in Yaml? if we loosely translate Yaml to manual editing, wouldn't the pencil be a nice option? 

if yes, changing the pencil-off to pencil in the Helpers section on Yaml templates would also fix the issue'

### Steps to reproduce the issue

1. just open config/helpers
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.8.0b0

### In which browser are you experiencing the issue with?

any, Chrome, Safari on Mac

### Which operating system are you using to run this browser?

Sonoma 14.5

**Comment by silamon** [comment]
There's no indication in the helper table that a helper has been defined in yaml. The purpose is to the list them all in the UI whether or not they are made in configuration or not. 

From the release notes: 
Things set up manually using YAML are still managed using YAML. This means that if you want to change the configuration of these integrations or helpers, you will need to do so in the YAML configuration files.

Trying to explain, integrations setup in yaml pass the configuration to the integration which setups a series of entities (button, lights, ...) and the integration can provide an unique id for them, making them editable in UI. When you edit them, there are no changes to your configuration.yaml. 
Helpers do define an unique id in the configuration.yaml, therefore if yaml helpers would be editable in the UI given that they do have an unique id, it would be required to change your configuration.yaml when you edit in the UI.

**Comment by Mariusthvdb** [comment]
its a bit more complicates possibly than that.

What I do, is have the yaml config be as minimal as can be, with a unique_id.

that way I can edit Name, icon, object_id in the UI.

So my yaml entities are editable in the UI ;-) (yes, except for their base configuration, I am aware of that)

My point in the issue is that there is an inconsistency in the use of the pencil-off.

Right now, it shows to indicate one can Not edit them, while it should indicate they originate in Yaml.

Just like the {} in the integrations page now does

I believe it would be more consistent to have the same icon indicating an integration , or an entity originate in Yaml.

Second, I do also feel that shouldnt be {}, as that is used throughout Home Assistant to indicate Templates.

Hence my suggestion to instead use the mdi:pencil, indicating those Integrations or entities/helpers originate in Yaml

And, as a now possible result of that choice, use the pencil-off for those places in the UI ton indicate to the user an options can Not be edited in the UI (like the more-info of pure Yaml integrations, without unique_id)

**Comment by silamon** [comment]
The icon has been changed for yaml integrations. Thank you for helping. 
However, the pencil-off suggestion remains. Looking into this further, the entities table uses pencil-off for both things that originate from yaml as well as integrations that do not provide an unique entity_id. So, changing that would be incorrect.

**Comment by Mariusthvdb** [comment]
thanks. I guess I will leave it there.
however, you illustrate my ppint exactly:

> the entities table uses pencil-off for both things that originate from yaml as well as integrations that do not provide an unique entity_id. 

the single  icon having a double meaning, with in this case a rather substantial difference, should not be used imho.

For that I believe 

> 
So, changing that would be incorrect

should be exactly the opposite. Maybe you can reconsider that, taking into account the new file-code icon now used in the integrations overview (nice, thanks for that)
