### ISSUE TITLE
Frontend Discrepancy between PC (Chrome) and Android App

### ISSUE THREAD

**Issue by Anto79-ops** [home-assistant/frontend#21533]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hello,

Since updating to 2024.8.0b0, I've noticed some issues on the Android App frontend where

1. On the Android app, some screens will be blank, and compleletely white, for example, core addons. But works as expected on PC (Chrome)
2. New integrations introduced in 2024.8.0b0 are not showing in the app, but show up on PC Chrome
3. And the new "Proud Part of the open home foundation" does not show on the app, but shows up on PC.

I have already tried to clear the cache on the app, but that did not help

### Describe the behavior you expected

the fronted on the app to be synced/the same with the PC versions

### Steps to reproduce the issue

1. just use the app and compare with frontend
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.8.0b0

### What was the last working version of Home Assistant Core?

2024.7.4

### In which browser are you experiencing the issue with?

Android App

**Comment by ChristophCaina** [comment]
in addition to that, the new Badges are not working.
Not 100% sure, if this is an issue with the companion app itself, or with the frontend, since the frontend does not refresh...

![grafik](https://github.com/user-attachments/assets/8714971a-78c3-4f9e-a373-7d692961ae51)
 while using the companion app.

**Comment by Madelena** [comment]
Looks like your Android app need to flush the cache of the frontend?

**Comment by Anto79-ops** [comment]
Thanks Madelena is there another way to clear the cash for the app?

The way I did it was through this way here, but that didn't help:

![Screenshot_20240801_084052_Settings.jpg](https://github.com/user-attachments/assets/cb5895dd-56c9-40ab-af4d-f20645045fa3)

Also I rarely look into the Android app logs I see a bunch of these logs whenever I try to load a page which gives a white screen

![Screenshot_20240731_222026_Home_Assistant.jpg](https://github.com/user-attachments/assets/fd8ef18e-71c7-4b8d-a213-479c4fdbe7cd)

**Comment by ChristophCaina** [comment]
probably related with #21542 - since the frontend will not be updated

**Comment by bramkragten** [comment]
closing for #21542

**Comment by bschatzow** [comment]
Beta 1 did not fix this for me.

**Comment by ChristophCaina** [comment]
Unfortunately, I have to agree... :-(

**Comment by Anto79-ops** [comment]
just curious if you're using  2024.7.5-full version of the app

**Comment by ChristophCaina** [comment]
hm... let me check :)

**Comment by Anto79-ops** [comment]
ok, someone in beta said they have their Android and `2024.7.3-full` and its working for them.

I have `2024.7.5-full` so I thought maybe it was that but looks like not.

I'm not certain what the stable is, maybe you have it already installed?

**Comment by bschatzow** [comment]
I have 2024.7.5-full and it does not work for me
