### ISSUE TITLE
When editing a card, tabs (config, visibility, layout) are not displayed

### ISSUE THREAD

**Issue by mbo18** [home-assistant/frontend#21551]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When editing a card, tabs (config, visibility, layout) are not displayed. To make them appear, I need to click on the + to add a badge, then cancel, then edit a card and tabs are OK.
If I clear the browser cache, tabs are gone again

### Describe the behavior you expected

Tabs should be displayed every time

### Steps to reproduce the issue

1. Edit a card, no tabs
2. click on + to add a badge then cancel
3. Edit a card, tabs are ok
4. clear browser cache, tabs are gone
5. goto 1

### What version of Home Assistant Core has the issue?

core-2024.8.0b0

### What was the last working version of Home Assistant Core?

core-2024.7.4

### In which browser are you experiencing the issue with?

Firefox latest, IOS safari

### Which operating system are you using to run this browser?

MacOS, iOS app

**Comment by ChristophCaina** [comment]
thanks for confirming this:

```
Describe the issue you are experiencing
When editing a card, tabs (config, visibility, layout) are not displayed. To make them appear, I need to click on the + to add a badge, then cancel, then edit a card and tabs are OK.
If I clear the browser cache, tabs are gone again
```

i thought I am stupid - when I raised my ticket #21520 - and then, suddenly the options were available again.
I later recognized the same pattern as you - but did not had the time to further test it.
