### ISSUE TITLE
New 2024.8 Badge throws error when setting icon: []

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#21571]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

<img width="785" alt="Scherm­afbeelding 2024-08-03 om 09 42 20" src="https://github.com/user-attachments/assets/b34819d6-97dd-4121-ab2b-9b2ab2a6ff93">

### Describe the behavior you expected

no error

### Steps to reproduce the issue

1. see above
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.8.0b

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

sonoma 14.5

### Problem-relevant frontend configuration

```yaml
type: entity
entity: person.marijn
display_type: complete
icon: []
```

### Additional information

faking it with 
```
icon: ' '
```
 or any string probably like `icon: no` prevents the error..

**Comment by piitaya** [comment]
Icon only accepts an icon name (mdi:...). You should not put an array or an empty string. 
For now, there is no way to hide the icon (except of using mushroom template badge)
