### ISSUE TITLE
Failed to setup

### ISSUE THREAD

**Issue by Mlitz** [home-assistant/frontend#21582]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After adding Smartlife and linking it to my phone app last night everything was working great. Today I see that it failed to connect and not sure why. Here is a log file.

```
Logger: homeassistant.config_entries
Source: config_entries.py:586
First occurred: 6:09:22 PM (1 occurrences)
Last logged: 6:09:22 PM

Error setting up entry gg-103036689366060496376 for smartlife
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartlife/__init__.py", line 69, in async_setup_entry
    await hass.async_add_executor_job(smart_life_manager.report_version, __version__, smart_life_version, sharing_sdk)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tuya_sharing/manager.py", line 69, in report_version
    self.user_repository.user_version_report(ha_version, integration_version, sdk_version)
  File "/usr/local/lib/python3.12/site-packages/tuya_sharing/user.py", line 46, in user_version_report
    self.api.post("/v1.0/m/life/home-assistant/qrcode/versions", None, {
  File "/usr/local/lib/python3.12/site-packages/tuya_sharing/customerapi.py", line 192, in post
    return self.__request("POST", path, params, body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tuya_sharing/customerapi.py", line 121, in __request
    raise Exception(f"network error:({ret['code']}) {ret['msg']}")
Exception: network error:(-9999999) sign invalid
```

### Describe the behavior you expected

integration failed to connect

### Steps to reproduce the issue

1. linked the integration
2....
3. Nothing
...

### What version of Home Assistant Core has the issue?

2024.7.4

### What was the last working version of Home Assistant Core?

2024.7.4

### In which browser are you experiencing the issue with?

Chrome Version 127.0.6533.89

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment]
That is a core log, you should file this in home-assistant/core repository. Off topic for frontend.
