### ISSUE TITLE
Custom element doesn't exist - Lenovo tablet on Android 7.1.1

### ISSUE THREAD

**Issue by bromleyman** [home-assistant/frontend#21584]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

This issue ONLY applies to viewing HA on a Lenovo M10 tablet with Android 7.1.1 (no updates available for this device). The device is used as wall panel to view HA dashboards.
HA is running on a VM (VM Box on Optiplex PC) HAOS 12.4, Core 2024.7.2.
Very recently, the above tablet device is giving front end errors "custom element doesn't exist" for all dashboard elements that are in my /www/community folder.
This happens in both the app and also when accessing HA using Chrome browser on the tablet. I have no problems with other devices including a Pixel phone on Android 10.
Is this fixable or is Android 7.1.1 too old? 

### Describe the behavior you expected

Wouldn't have expected any change from long period of problem free operation.

### Steps to reproduce the issue

1. Problem might be device specific ..... could try another tablet with same android version
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.7.2

### In which browser are you experiencing the issue with?

not applicable

### Which operating system are you using to run this browser?

android 7.1.1

**Comment by steverep** [comment]
Android 7 is not too old for the HA frontend, but it sounds like your issue is with custom cards, in which case you need to open issues with those developers.  Please close this if that's the case.

**Comment by ChristophCaina** [comment]
can't this just be a chache-issue?

**Comment by steverep** [comment]
Nothing in your report suggests that, but you haven't even provided the actual error message.

**Comment by bromleyman** [comment]
Just to clarify, as I noted, the error message is "custom element doesn't exist" followed by the custom card name, for example : custom element doesn't exist: paper-buttons-row. This appears in place of the affected card followed by the code for that card segment.
For some reason the app and the browser can't find the path to the required custom resources even though they appear in settings / dashboards / resources. I don't think it is a problem with any of the custom resources as the same thing occurs with each of the eight custom resources that I have used in my dashboards.
I will close out for now while I try the following - re-installing the app on the tablet, re-installing HACS, manually installing selected custom components. If no success there, I guess I can just create a separate dashboard for the old tablet using only the standard dashboard elements.
Thanks for the feedback - useful to know that Android 7 should be still ok.

**Comment by steverep** [comment]
That message appears when HA detects a card  tag that is not defined in the [custom element registry](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry).  So my assumption is that there is an error somewhere running the custom element's JS.  I'm going to cc @piitaya to see if he thinks this could have been caused by recent HA changes.

Check your logs for any frontend errors.  And please report the HA frontend version installed, in particular whether the tablet in question is running the legacy or modern build (Settings > About).

**Comment by bromleyman** [comment]
App is 2024.7.3 full.

Found this error in the core log (looks useful :-) )

Logger: frontend.js.es5.202407100
Source: components/system_log/__init__.py:333
First occurred: August 6, 2024 at 3:59:01 PM (30 occurrences)
Last logged: August 6, 2024 at 4:02:59 PM

Uncaught error from Chrome WebView 56.0.2924.87 on Android 7.1.1 TypeError: document.getElementsByTagName(...)[0].computedStyleMap is not a function :1:43
Uncaught error from Chrome WebView 56.0.2924.87 on Android 7.1.1 TypeError: Failed to execute 'scrollTo' on 'Window': No function was found that matched the signature provided. Number (src/panels/lovelace/hui-root.ts:570:23)
Uncaught error from Chrome WebView 56.0.2924.87 on Android 7.1.1 TypeError: Cannot read property 'labels' of undefined labels (node_modules/element-internals-polyfill/dist/index.js:365:20) upgradeInternals (node_modules/element-internals-polyfill/dist/index.js:776:24) apply (node_modules/element-internals-polyfill/dist/index.js:774:46) apply (src/scoped-custom-element-registry.js:248:41) insertBefore (src/lit-html.ts:1411:52) k (src/lit-html.ts:1454:35) $ (src/lit-html.ts:1563:11) g (src/lit-html.ts:1384:11) _$AI (src/lit-html.ts:2183:7) i (src/lit-element.ts:165:30)
Uncaught error from Chrome WebView 56.0.2924.87 on Android 7.1.1 TypeError: Cannot read property 'labels' of undefined labels (node_modules/element-internals-polyfill/dist/index.js:365:20) upgradeInternals (node_modules/element-internals-polyfill/dist/index.js:776:24) apply (node_modules/element-internals-polyfill/dist/index.js:774:46) apply (src/scoped-custom-element-registry.js:248:41) _addCardToColumn (src/panels/lovelace/views/hui-masonry-view.ts:255:15) Promise.all (src/panels/lovelace/views/hui-masonry-view.ts:236:11) call (node_modules/@babel/runtime/helpers/esm/regeneratorRuntime.js:45:15) tryCatch (node_modules/@babel/runtime/helpers/esm/regeneratorRuntime.js:133:16) _invoke (node_modules/@babel/runtime/helpers/esm/regeneratorRuntime.js:74:20) c (node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:17)
Uncaught error from Chrome WebView 56.0.2924.87 on Android 7.1.1 TypeError: Cannot read property 'labels' of undefined labels (node_modules/element-internals-polyfill/dist/index.js:365:20) upgradeInternals (node_modules/element-internals-polyfill/dist/index.js:776:24) apply (node_modules/element-internals-polyfill/dist/index.js:774:46) apply (src/scoped-custom-element-registry.js:248:41) _createPanel (src/layouts/hass-router-page.ts:318:9) loadProm.then( (src/layouts/hass-router-page.ts:214:13)

**Comment by bromleyman** [comment]
Settings/About details:
Core 2024.7.2
Supervisor 2024.08.0
OS 12.4
Frontend is 20240710.0

**Comment by steverep** [comment]
Your device is on the legacy build, and running a really old version of Chrome web view (v56 as reported in the log).  Currently our legacy build targets browsers that are 7 years old or meet a minimum usage threshold (v60 for android web view at the moment).  So the error is not surprising.

However, I'm shocked you're running a version that old.  I think even android 5 supports newer.  I'm not an android expert, but maybe try installing [web view from the play store](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en_US) and see what version it gives you.

**Comment by steverep** [comment]
Also, please check whether the device has the problem only in the app, i.e. does it also occur using Chrome or Firefox on the same device.

**Comment by bromleyman** [comment]
The issue is the same on Chrome. One of my first tries was to use Chrome instead of the app but no luck there.
The tablet is a Lenovo TB-X704F - a nice device at the time with a good screen - but became of little use other than for a HA wall panel due to memory limitations and no firmware updates available beyond Android 7.
I clicked on the link on my PC in your email for android web view and did an install on the tablet .... but no difference.
If this is just something peculiar to this Lenovo device, please don't spend valuable time on something that has little impact for the vast majority of users - I can just do a separate dashboard to fix my own needs.
Thanks for the excellent help thus far.

**Comment by steverep** [comment]
Is the Chrome browser version also 56?  Maybe force an update via https://play.google.com/store/apps/details?id=com.android.chrome&hl=en_US.

**Comment by steverep** [comment]
FYI, android 7 should support up to Chrome 119 (they only ended support last year):

https://en.wikipedia.org/wiki/Template:Google_Chrome_release_compatibility#cite_note-5

So if I were you, I'd figure out how to get it upgraded rather than giving up on the device just yet.

**Comment by bromleyman** [comment]
I have worked out a fix :-)
I manually installed the custom elements (.js file in config/www folder, entry in config.yaml, and resource created in settings/dashboards/resources with url's of the form /local/xyz.js?v=nnn.n).
Appears that the old tablet didn't like the /hacsfiles/xyz-card/xyz.js?hacstag= .... resources that work for all my other devices and PC's. 
Regarding Chrome version etc, the tablet was fully up to date as far as the Play Store was concerned so no updates available. I also tried installing Firefox but that displayed exactly the same as Chrome.
Thanks for the prompt assistance - much appreciated.

**Comment by steverep** [comment]
Could you please verify the Chrome, Android web view, and Firefox versions installed as reported in android settings?  I want to at least verify that the version reported in the HA log is accurate (that's handled by a dependency that analyzes the user agent string).

I'm glad you found a work around, but this old Chrome version is still bothering me.  I've been doing a lot of work lately to improve our legacy build for old browsers, but I work under the assumption that these things get updated to their latest supported version (or at least come close!).  I'd like to understand what's going on here if you're willing to be a guinea pig.

**Comment by bromleyman** [comment]
Hi Steve,

Firefox is 128.0.3
Chrome is 119.0.6045.193

There is no Android web view app. Play store does not offer this app to my old XT Lenovo tablet.

My latest Lenovo tablet runs Android 13 and has Android System WebView 127.0.6533.64 installed.

If I go to the play store on this tablet it shows an Android System WebView Canary as being available ..... but not for install on the old tablet.

Just wondering on an un-related matter .....

I run HA on a VM VirtualBox on a Dell Optiplex mini format PC on Windows 10 with a 1 TB SSD, 70 GB provided to HA in the VM. I have been getting an issue with the VM window filling up with continuous rapidly repeating error messages:
Kernel:get-swap-device: bad swapfile entry <a hex number>. HA will be running fine for about a week and then I notice it getting slow and I look at the VM window and see the normal static info has been replaced with the rapidly scrolling error lines. If I don't abort the VM, HA will eventually crash. I have checked the SSD and no errors there.

Would you be able to point me in the right direction to get some clues on what might be wrong.

Regards,

David
