### ISSUE TITLE
thermostat card not powering on the device

### ISSUE THREAD

**Issue by StefanW86** [home-assistant/frontend#21596]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have configured a climate device through my knx integration. All service calls works like expected. 
If i want to power on my climate device through the thermostat card i click on "cool", because there is no extra "on" button. HA sends a cool command to the knx bus but the climate device ignores it. It needs a "on" command.
So after clicking multiple times on cool, at same time HA sends a on command and the climate devices powers on.

### Describe the behavior you expected

If clicking the cool button, HA should first send a on command if the deviced is powered off and then a cool command.

### Steps to reproduce the issue

Clicking on cool in thermostat card

### What version of Home Assistant Core has the issue?

2024.7.4 and all others below

**Comment by karwosts** [comment]
This feels like it should be reported in core for the KNX integration. Homeassistant climate devices don't have "on" buttons, you click the mode and it's supposed to go to that mode. 

If KNX requires extra steps to achieve this, it should be written into the KNX integration/library, it's not something we have to address in frontend.

**Comment by StefanW86** [comment]
ok, i opened there the issue. 
https://github.com/home-assistant/core/issues/124626
