### ISSUE TITLE
Area card shows humidity of weather entity instead of humidity sensor assigned to the area.

### ISSUE THREAD

**Issue by stebl27** [home-assistant/frontend#21614]
![IMG_2560](https://github.com/user-attachments/assets/b0c761f6-6e36-4767-8cb2-070f51afe44b)
![IMG_2561](https://github.com/user-attachments/assets/8cdea1be-30c6-482c-b7ad-0855281fc1e5)
![IMG_2562](https://github.com/user-attachments/assets/2180c80e-2336-4c5e-b0a1-39ad7afeede9)
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If I activate sensor class humidity for an area card, the area card shows the humidity value of the weather entity instead of the value reported by the humidity sensor of the area.

### Describe the behavior you expected

The area card should show the humidity value of the humidity sensor assigned to the area.

### Steps to reproduce the issue

1. Create a weather entity which reports a humidity value.
2. Create a humidity entity and assign it to an area
3. Create an area card and add sensor class humidity

### What version of Home Assistant Core has the issue?

2024.7.4

**Comment by stebl27** [comment]
![IMG_2560](https://github.com/user-attachments/assets/d9f97227-ffcd-469b-a00c-54348a9bc8c2)
![IMG_2561](https://github.com/user-attachments/assets/5f07892c-5c48-499e-982f-2901f37f8e8e)

**Comment by karwosts** [comment]
I don't believe that's the case, it's probably just a coincidence that they are both 64. The number on that card displays the _average_ of all your humidity sensors in that area. Please review your sensors in that area and make sure you don't have any additional entities that report humidity in that area. 

Unless you've also assigned your weather entity to that area?

**Comment by stebl27** [comment]
@karwosts 
But in my screenshots you can see that there is only one humidity entity assigned to this area. An if it would be the average of this and the weather entity then it would have a different value.
The weather entity has no assigned area currently and publishes no humidity sensor.

**Comment by stebl27** [comment]
@karwosts Sorry it was the mold indicator addon. Since I deactivated it, the humidity shows correct value.
