### ISSUE TITLE
Sections View Only 3 Columns

### ISSUE THREAD

**Issue by tibmeister** [home-assistant/frontend#21623]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Every update since 2024.7.x using a Sections View, I can only get 3 columns to show consistently.  If I edit the dashboard, change from 4 column to 3 columns and save, my 4th column will now show below in a new row.  If I again edit and change back to 4 columns, sometimes I can see the 4th column in the browser until a refresh occurs, which then my 4th column disappears again.
This occurs regardless of what cards are in the 4th column, what browser I'm using, and even across multiple machines and OS's.

### Describe the behavior you expected

In 2024.6.4 I was able to have 4 columns show consistently in the Sections View across all browsers and machines.

### Steps to reproduce the issue

1. Create Sections View
2. Set to 4 columns
3. Add content
4. Save
5. Refresh and observe
...

### What version of Home Assistant Core has the issue?

2024.7.0+

### What was the last working version of Home Assistant Core?

2024.6.4

### Which operating system are you using to run this browser?

Windows 10 22H2, Ubuntu 22.04, Debian 12, Android 10, iOS 17.6

### Additional information

Screenshots named with description

![4 column after refresh](https://github.com/user-attachments/assets/a1e8c4f2-159b-4267-8c17-71b174cc2ea3)
![4 Column edit mode](https://github.com/user-attachments/assets/a14249d0-04cb-4acd-a6ca-c640220f6b0e)
![4 Column not working](https://github.com/user-attachments/assets/8b858592-d2de-4c2c-99a2-a138328b5ccf)
![4 column working before refresh](https://github.com/user-attachments/assets/6e1cbf8d-cc30-4421-b8a0-dccf89f31988)
![Edit Change back to 4 column](https://github.com/user-attachments/assets/408abfcc-2038-42d0-ab35-e16a24e97714)
![Edit changed to 3 column](https://github.com/user-attachments/assets/d95e2b0b-781d-4270-8122-b0e6c7340c2b)

**Comment by charettepa** [comment]
I am getting the same issue while sing Masonry
if i use sections, i can get 4 but only if i zoom out the browser to 80% or less

what can be done to get 4 columns again
without zooming to 80% or less
and without closing the sidebar
