### ISSUE TITLE
Ghost 'Configurator' button just won't die!

### ISSUE THREAD

**Issue by ZhuDaHai** [home-assistant/frontend#21625]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have a HA install of many years old (probably 5 by now) and keep it updated religiously. But from the start, I had a Ghost button for Configurator that just won't move on. I want to remove it from the side bar,  but It's just stuck in purgatory and I don't know how to free it and let it die properly:

![image](https://github.com/user-attachments/assets/87b0cb73-ee8f-45f6-bcd7-fb559d8c3568)

### Describe the behavior you expected

Configurator: Do you expect me to talk?
Me: No, I expect you to DIE!

I have the 'config:' commented out in configuration.yaml, but this pesky poltrygeist just won't leave me alone!

```
# Enables configuration UI
#config:

```
I use 'File Editor' in both my HA setups, so don't need 'Configurator' with its disturbing Ghost Icon filling up my side-bar.
In my in install of HA, on another PI, it never had 'config:' in the configuration.yaml and does not have this Configurator Spector.

### Steps to reproduce the issue

1. Install a really old version of HA and enable 'config:' in configuration.yaml
2. Keep it updated throughout the years
3. Notice the Demonic Possession of your side-panel by a Ghostly 'Configuration' icon.
4. Try to exorcise (or even exercise it, I don't care) by commenting out 'config:' in configuration.yaml
5. Scream is Unholy Terror as it just won't DIE!!!!
6. Write a Screenplay and try to get Ryan Reynolds to Star. 
...

### What version of Home Assistant Core has the issue?

2024.8.0 and back many years

### What was the last working version of Home Assistant Core?

None that I know of, but does not seem to be an issue with new installs that never had 'config:' in configuration.yaml

### In which browser are you experiencing the issue with?

Chrome Version 127.0.6533.89 (Official Build) (64-bit) and older, and in incognitor mode, and Brave Version 1.68.134 Chromium: 127.0.6533.88 (Official Build) (64-bit) and older as far back as I can remember.

### Which operating system are you using to run this browser?

Windows 11 Pro 10.0.22631 Build 22631 and older

### State of relevant entities

```txt
"Configurator" - he ain't got no Icon, and he just won't die and sail to Stovokor like the brave Klingon that he was!!!

configuration.yaml
config:
```

### Problem-relevant frontend configuration

```yaml
configuration.yaml

  
# Enables configuration UI
#config:
```

### Javascript errors shown in your browser console/inspector

```txt
None
```

### Additional information

Thank you for your attention and time on this issue. 
May the Lords of Kobol be with you. So say we all!

**Comment by silamon** [comment]
That's specific to your installation and probably caused by a custom configuration that you had in the past. Try safe mode to see if it remains. If it remains, it's somewhere defined in your configuration yaml and you can remove it, else it must be a leftover added javascript that adds it to the sidebar.

**Comment by ZhuDaHai** [comment]
Dear Lord, I am blind. I was so focused on 'config:' that I totally looked right over 'panel_custom:'

```
panel_custom:
  - name: hassio-main
    sidebar_title: Configurator
    sidebar_icon: hass:settings
    js_url: /api/hassio/app/entrypoint.js
    url_path: configurator
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator    
```
Like I said, this install is really old and so this entry was probably added from the start. I've commented it out and the antagonist 'Configurator' is now gone. 

Thanks you!
