### ISSUE TITLE
"history_stats" helper: unable to edit all settings

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#21624]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Create a new `history_stats` sensor:
step 1:
![image](https://github.com/user-attachments/assets/b296b2d1-d869-450c-962f-5ad01f56cfdd)

step 2:
![image](https://github.com/user-attachments/assets/c444a376-8183-4e33-83af-e5513fc11bc2)

Then try to edit it:
![image](https://github.com/user-attachments/assets/a5f4d8b7-97cb-4c4c-ad62-c726502ead26)

Only the 2nd step is available:
![image](https://github.com/user-attachments/assets/1f2d51a0-f839-4e94-adb8-352e70a57bbe)

### Describe the behavior you expected

User may change settings defined on both steps.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2024.8

### In which browser are you experiencing the issue with?

Chrome 127.0.6533.89 

### Which operating system are you using to run this browser?

Win10x64

**Comment by silamon** [comment]
The config flow and its option flow are defined in the integration itself. You can open an issue to discuss at core.
