### ISSUE TITLE
Enabling any "Advanced Options" in light.turn_on kills the visual editor

### ISSUE THREAD

**Issue by karwosts** [home-assistant/frontend#21629]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

- In developer-tools/action, select light.turn_on (or maybe any service with "Advanced options").
- Expand advanced options.
- Enable and set a value for an advanced option.
- Visual editor will disappear and only a yaml editor will remain. 

![image](https://github.com/user-attachments/assets/ef4840b1-caa1-492c-a926-9ceeabecd6ae)

### Describe the behavior you expected

as above

### Steps to reproduce the issue

1. as above
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.7 & 2024.8

### Javascript errors shown in your browser console/inspector

```txt
none
```

**Comment by silamon** [comment]
The advanced_fields doesn't specify a selector in the service config. It's a core issue for the light integration.

**Comment by silamon** [comment]
The logic is here: https://github.com/home-assistant/frontend/blob/dev/src/components/ha-service-control.ts#L374
Every field that has a visual ui should be listed in the service data information we retrieve from backend. Currently, the advanced_fields is not listed as field, and their children not either. From as soon as you use one, it will revert to yaml.
