### ISSUE TITLE
Empty page when opening script with blueprint configuration

### ISSUE THREAD

**Issue by bluediamond1984** [home-assistant/frontend#21631]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

An empty page is shown when opening a script with a blueprint

### Describe the behavior you expected

The script editor show the title bar and the blueprint input fields

### Steps to reproduce the issue

Open any saved script with a blueprint configuration

### What version of Home Assistant Core has the issue?

2024.8.0

### What was the last working version of Home Assistant Core?

2024.7.4

### In which browser are you experiencing the issue with?

Google Chrome 127.0.6533.100

### Which operating system are you using to run this browser?

Windows 11 pro

### Javascript errors shown in your browser console/inspector

```txt
script.ts:436 Uncaught (in promise) 
TypeError: Cannot use 'in' operator to search for 'service' in undefined
    at $ (script.ts:436:7)
    at t.value (ha-script-editor.ts:491:23)
    at ha-script-editor.ts:500:29
```

### Additional information

Issue is only with scripts with a blueprint configuration. Other scripts are loading

**Comment by silamon** [comment]
Can you post the specific blueprint. The error is on the same line as #21615.

**Comment by karwosts** [comment]
> Can you post the specific blueprint?

I don't think the specific blueprint would matter, Don't think `sequence` is a valid key for any script blueprint config, so I believe any BP would fail the same here (all of mine do). Do you have any that work?

E.g.

{
    "alias": "Confirmable Notification",
    "use_blueprint": {
        "path": "homeassistant/confirmable_notification.yaml",
        "input": {
            "notify_device": "3bf677348c7e7d6ddc73f2261af9a424",
            "title": "",
            "message": "Message"
        }
    },
    "description": ""
}

**Comment by bluediamond1984** [comment]
It's not a specific blueprint. None of the blueprints works
I've done the same thing as @karwosts with the default blueprint and it also doesn't work
