### ISSUE TITLE
Only 4 devices found on HA when Govee shows 6

### ISSUE THREAD

**Issue by Jakesparrow** [home-assistant/frontend#21633]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have a Govee hub wall plug, and it connects to the wifi, and with bluetooth it connects to my (6) hygrometer/thermometers. 
In thr Govee app, I see all 6 just fine, but in HA, only the 4. When I try to add, it does not see any additional.

### Describe the behavior you expected

I expected the 6 attached to the Govee hub to populate

### Steps to reproduce the issue

1.Plugn in the govee hub
2.Sign in with credentials in the Govee app
3.Link to the Govee device in HA
...

### What version of Home Assistant Core has the issue?

core-

### What was the last working version of Home Assistant Core?

core-

### In which browser are you experiencing the issue with?

Chrome (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11 23H2

**Comment by karwosts** [comment]
This is not a frontend issue, you'll want to open an issue for Govee specifically in home-assistant/core.
