### ISSUE TITLE
Yamaha MusicCast media play does not show source and other controls

### ISSUE THREAD

**Issue by tomlut** [home-assistant/frontend#21641]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The Yamaha MusicCast media player does not display a source selection control. Compare it with the Yamaha network receiver media player:

**Yamaha MusicCast Integration:**

Attributes:
```
source_list: airplay, hdmi1, hdmi2, audio1
sound_mode_list: munich, vienna, chamber, cellar_club, roxy_theatre, bottom_line, sports, action_game, roleplaying_game, music_video, standard, spectacle, sci-fi, adventure, drama, mono_movie, 2ch_stereo, 7ch_stereo, surr_decoder, straight
group_members: media_player.lounge_zone
icon: mdi:speaker
friendly_name: Lounge Zone
supported_features: 1019788
volume_level: 0.4906832298136646
is_volume_muted: false
media_content_type: music
source: Lounge PC
sound_mode: 7ch_stereo
shuffle: false
repeat: off
```

Appearance:

![Screenshot 2024-08-09 at 14-49-30 Administration – Home Assistant](https://github.com/user-attachments/assets/e3c9a429-1bad-4fc9-92af-73a39a045630)

![musiccast](https://github.com/user-attachments/assets/017d66af-7704-4998-90ba-fe095a9fb363)

**Yamaha Network Receiver Integration:**

Attributes:
```
source_list: AirPlay, Kodi, Lounge PC, TV
sound_mode_list: Hall in Munich, Hall in Vienna, Chamber, Cellar Club, The Roxy Theatre, The Bottom Line, Sports, Action Game, Roleplaying Game, Music Video, Standard, Spectacle, Sci-Fi, Adventure, Drama, Mono Movie, Surround Decoder, 2ch Stereo, 7ch Stereo, Straight
friendly_name: Lounge AV RX
supported_features: 89021
icon: mdi:audio-video
volume_level: 0.5900000000000001
is_volume_muted: false
source: Lounge PC
sound_mode: 7ch Stereo
```
![Screenshot 2024-08-09 at 14-53-26 Administration – Home Assistant](https://github.com/user-attachments/assets/35675397-c956-479c-88f1-9bbdc6637dbb)

![networkrx](https://github.com/user-attachments/assets/f40e7faa-224d-449e-a913-85a0aa35b792)

### Describe the behavior you expected

To have a full set of controls as per the other media player integration. The attributes are there. 

### Steps to reproduce the issue

1. Configure Yamaha MusicCast Integration.
2. Add media player card to dashboard.
3.
...

### What version of Home Assistant Core has the issue?

core-2024.8.0

### Which operating system are you using to run this browser?

Firefox 127.0.2, Chrome 127.0.6533.100, Edge 127.0.2651.98

### Problem-relevant frontend configuration

```yaml
type: media-control
entity: media_player.lounge_zone
```

**Comment by tomlut** [comment]
This appears to have been my fault. I just discovered that at some point in the past I had attempted to use customize to alter the source list. Once this customization was removed the media players display as expected.

**Comment by mitchger** [comment]
I can do this, however; I can't set the device as a target in action > media player: select source; it's not showing up in the list of devices. I can select it as a target for other actions such as power on/off. Ideas?
