### ISSUE TITLE
Call Action not working correctly.

### ISSUE THREAD

**Issue by yestrdave** [home-assistant/frontend#21645]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When creating a new call action, the yaml is still showing service. 

### Describe the behavior you expected

UI breaks and defaults to yaml mode.  If I replace the service with action the UI corrects itself.  This is happening on a new script.  I have tried it in browser and app.

### Steps to reproduce the issue

1.new script
2.add action
3.other action 
4. Perform Action
...

### What version of Home Assistant Core has the issue?

2024.8.0

### What was the last working version of Home Assistant Core?

2024.7.xx

### In which browser are you experiencing the issue with?

App and Safari, Arc

### Which operating system are you using to run this browser?

iPad 

### Additional information

![image](https://github.com/user-attachments/assets/81896561-4038-4602-abd3-a6ea3fe8a385)

**Comment by silamon** [comment]
Fixed with #21650. Thank you for reporting!
