### ISSUE TITLE
Unable to add/edit actions/service in automation UI

### ISSUE THREAD

**Issue by CyberFlexie** [home-assistant/frontend#21655]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When creating an automation or script and adding a 'Perform action' (previously known as 'service'), the UI drops to yaml mode and states:

Visual editor is not supported for this configuration
Key 'service' is not expected or not supported by the visual editor.
You can still edit your config in YAML.

This used to work in the past before the name change of service ==> action.

### Describe the behavior you expected

To manage actions in the UI like before when actions were still called service.

### Steps to reproduce the issue

1. Start a new script or automation.
2. add action ==> Perform action

### What version of Home Assistant Core has the issue?

2024.8.0

### What was the last working version of Home Assistant Core?

2024.8.0

**Comment by silamon** [comment]
Thank you for reporting. It should be fixed in the next release.
