### ISSUE TITLE
New Badges, unable to remove state content mobile

### ISSUE THREAD

**Issue by djansen1987** [home-assistant/frontend#21652]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Tried out the new Badges today. Really excited! But there seems to be an issue with the sate content in edit mode. When I added some states and want to remove them it is not possible to click the x on the mobile app on Android. Drag and drop does work (the drag and drop seems to overwrite the close button

### Describe the behavior you expected

Unable to remove added state content to a badge

### Steps to reproduce the issue

1.add badge
2.add multiple state content attributes
3. Try to remove one
...

### What version of Home Assistant Core has the issue?

2024.8.0

### In which browser are you experiencing the issue with?

Companion app android

### Which operating system are you using to run this browser?

Android 14

**Comment by lionslair** [comment]
Can confirm this as well. Have to save the. Edit via yank to remove

**Comment by djansen1987** [comment]
Solved

**Comment by PeterBarker11** [comment]
Greetings.

How are you able to resolve this issue? Currently doing with the same thing.

**Comment by djansen1987** [comment]
With the latest update it was working for me
