### ISSUE TITLE
Daikin can't connect after router change

### ISSUE THREAD

**Issue by Aparow1989** [home-assistant/frontend#21663]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When trying to connect my Daikin AC's I get "unexpected error"

### Describe the behavior you expected

It should work without issues, like in the past with the old router

### Steps to reproduce the issue

1. click configure Daikin
2. Ip is autopopulated (or copy paste it manually)
3. hiting submit
<img width="431" alt="Screenshot 2024-08-11 104140" src="https://github.com/user-attachments/assets/6b50911b-a035-4490-b110-6a69e68f4a9a">

...

### What version of Home Assistant Core has the issue?

2024.8.1

### What was the last working version of Home Assistant Core?

2024.8.1

### In which browser are you experiencing the issue with?

Google chrome, android phone

### Which operating system are you using to run this browser?

windows 11

**Comment by silamon** [comment]
Open an issue at the core repository towards the daikin integration if none already exists.
