### ISSUE TITLE
Core Integration Repair UI

### ISSUE THREAD

**Issue by MarkRS-UK** [home-assistant/frontend#21660]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When HA detects core integration repairs are required it reports this on the settings page and it is obvious what to do with the options (good UI).
However selecting a repair provides a dialog with two options, neither have any text (see attached screenshot), so it is not obvious what to do with them.
What is not obvious is where the repair is being applied, presumably an integration has a problem, but which one?  No clue is offered.
Incidentally, what else is not obvious is what "repair" is applied and, since this keeps happening, I assume the repair (in this case at least) is not very effective.

### Describe the behavior you expected

Repair dialog shows text to indicate what the supplied options do.

### Steps to reproduce the issue

1. Click on a repair showing in the settings display
2.
3.
...

### What version of Home Assistant Core has the issue?

Core 2024.8.0 Supervisor 2024.08.0 Operating System 12.4 Frontend 20240806.1

### In which browser are you experiencing the issue with?

FireFox 128.0.3 (64-bit)

### Which operating system are you using to run this browser?

Fedora (Linux)

**Comment by MarkRS-UK** [comment]
Ooops, here's the screenshot (I think)

![haError](https://github.com/user-attachments/assets/f9e83a0e-0f0a-4cb9-825b-bd0ed25e36eb)

**Comment by silamon** [comment]
The options and the text are provided by the core repository. We just render them in the frontend. Do you mind opening an issue at core?

**Comment by MarkRS-UK** [comment]
Ok, will do.
