### ISSUE TITLE
History by tap of long tap (hold) display discrepancy

### ISSUE THREAD

**Issue by caitotheonlypotato** [home-assistant/frontend#21670]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I click om the information in Developer options  (States tab) or from within the dashboard
![image](https://github.com/user-attachments/assets/3d3e4e14-a737-4f27-a599-bedd817a6146)
![image](https://github.com/user-attachments/assets/ae70756d-1ffd-464f-8177-4b71fb6a273f)

I get the following graph

![image](https://github.com/user-attachments/assets/a5e4bc00-9dda-4a8f-bb47-f48b40d4f182)

whereas it used to look like this

![image](https://github.com/user-attachments/assets/2d16c86f-2602-49e1-a615-cc9524fdb69c)

It's the same data, different graph though and it's all messed up
It's like it ignores all the zero values

### Describe the behavior you expected

The new history graph doesn't accurately depict the data as it seems like it's not reflecting zero  or possibly unavailable values correctly.  Whilst the zoom function is appreciated, the cooky looking graph is not an accurate representation of the data.

### Steps to reproduce the issue

1. View the graph from Lovelace (or)
2. View the graph from developer options (States Tab)
3. Visually check
...

### What version of Home Assistant Core has the issue?

core- 2024.8.1

### What was the last working version of Home Assistant Core?

developer option (states tab) worked in core-2024.6.1

### In which browser are you experiencing the issue with?

Chrome is up to date Version 127.0.6533.100 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 22H2

### State of relevant entities

```txt
state_class: measurement
unit_of_measurement: W
device_class: power
friendly_name: Real HWS power in watts
```

### Problem-relevant frontend configuration

```yaml
N/A
```

### Javascript errors shown in your browser console/inspector

```txt
None
```

### Additional information

My companion app still uses the old history popup still works as it uses the old history format

**Comment by karwosts** [comment]
That graph you have shown is not part of home-assistant, you must have installed it through some kind of plugin or extra resource. We do not offer support for custom frontend plugins here.
