### ISSUE TITLE
Targets missing in automation 'Then Do' when selecting a switch, etc. 

### ISSUE THREAD

**Issue by lewisburgess** [home-assistant/frontend#21674]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since upgrading to 2024.8, I no longer see the target selection in the GUI when creating/editing automations and selecting a switch as a target. I am able to see it for a light target. 

I can edit the YAML and this works, but the 4 target buttons do not appear for a switch target.

![image](https://github.com/user-attachments/assets/87a3c2b1-c0d2-4815-9dd2-999b397043de)

### Describe the behavior you expected

I should be able to see switch target buttons

### Steps to reproduce the issue

Settings
Automations & Scenes
Automations
Create Automation
Create new automation
Add a trigger (eg. select a motion sensor)
Under 'Then do', select Add Action
Select Switch
Select Toggle or Turn off, or Turn on (none show the target selection)

### What version of Home Assistant Core has the issue?

2024.8.1

### What was the last working version of Home Assistant Core?

2024.7

### In which browser are you experiencing the issue with?

Google Chrome 127.0.6533.100, Edge 127.0.2651.98, Firefox 129.0

### Which operating system are you using to run this browser?

Windows 11 and Windows 10

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
N/A
```

### Javascript errors shown in your browser console/inspector

```txt
No error logs listed in the browser developer tools / console in each test of various browsers.
```

### Additional information

- Tried multiple browsers on multiple PCs. Clearing cache
- No errors in the browser console
- Target buttons do appear for lights but not switches
- Was working prior to 2024.8 upgrade
- Restarted HA
- Restarted HA server (RPi 5)
- Checked configuration (passed OK)
- All other aspects of HA seem to be working fine. Switches, lights, automations, scenes, blueprints, cards, controlling devices, etc.

**Comment by lewisburgess** [comment]
Restarted in Safe Mode
Target buttons now work
Restarted in 'normal mode'
Target buttons still working

Odd! I had already restarted HA and the server previously.

**Comment by karwosts** [comment]
Closing as this sounds resolved. Probably just a browser caching issue after an update. Please update if the problem returns.
