### ISSUE TITLE
Statistics helper: Unable to edit or even view the source entity and the state characteristic for the statistics sensor in the settings

### ISSUE THREAD

**Issue by Flox-Muc** [home-assistant/frontend#21675]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Neither in the helper settings nor there in the statistics options the source entity and the state characteristic for the sensor are shown. So they can't be looked after or changed.

### Describe the behavior you expected

There should be fields for the source entity and the state characteristic where they can be viewed and edited.

### Steps to reproduce the issue

1. Go to Settings -> Devices -> Helpers
2. Open the settings of a statistics helper.

### What version of Home Assistant Core has the issue?

2024.8.1

**Comment by karwosts** [comment]
This would have to be a core issue, not frontend. The settings menu you describe (the "options flow") is defined per the integration, and the integration code in core decides what is shown there.
