### ISSUE TITLE
Scripts disappearing from UI after a while

### ISSUE THREAD

**Issue by acenuke** [home-assistant/frontend#21678]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After the upgrade to 2024.8.0, the scripts were there for a few minutes, then all became unavailable (the UI does not list them anymore). The code is still available in scripts.yaml. If I restart HAOS, they come back for a few minutes then are unavailable again. I tried to create a brand new script from the UI and same behaviour. 
The script is also not available anymore when searching (but it is available in the script.yaml file).
I am NOT using notify in the script (it just turns off a bunch of lights).

After reboot (all normal)
![Script visible](https://github.com/user-attachments/assets/31b0256a-b919-45dd-9da1-f0225f7be0fe)

After a few minutes/hours (Script disappears from UI and search)
![Script disappeared from UI](https://github.com/user-attachments/assets/c700600c-df03-4ecf-be63-40f4f10a9567)
![Script can be found anymore when searching for it ](https://github.com/user-attachments/assets/c833d28f-7e5b-4b12-9942-a744859527e0)

The issue still happens with 2024.8.1

I originally posted this issue in Core (https://github.com/home-assistant/core/issues/123468), but it seems to be more UI related, as I can start the script from the Dev Tools.

### Describe the behavior you expected

Be able to see the scripts in UI and in search all the time

### Steps to reproduce the issue

1. Create a script via UI or editing script.yaml directly and reloading
2. Wait
3. Script is not in UI anymore
...

### What version of Home Assistant Core has the issue?

core-2024-08-01

### What was the last working version of Home Assistant Core?

core-2024-07-04

### In which browser are you experiencing the issue with?

Chrome 127.0.6533.100 Edge 127.0.2651.98

### Which operating system are you using to run this browser?

Windows 11, Android 14 and 15

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

**Comment by silamon** [comment]
Check off "I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources." just to be sure it's not a custom component. Also, under dev tools, use the state page to check if they are still provided there, not the action tab.

**Comment by acenuke** [comment]
Here is a screenshot of the Dev Tools state page (script is not found):
![image](https://github.com/user-attachments/assets/2db6b3d1-8f9b-4c44-bd42-d49093b20d7f)

I will try to run in safe mode, but I can't do that too long, as I need my Ha to be up and running. Since the issue can sometimes take hours to happen, not sure I will have enough time to reproduce

**Comment by acenuke** [comment]
By the way, if I run the script from Actions, then I can see the script again in States (until it disappears again):
![image](https://github.com/user-attachments/assets/c8f5a706-995c-4ef6-a6d7-2191a50100ab)

**Comment by silamon** [comment]
The safe mode is a requirement since I can't reproduce it and no one else has joined you in having this bug. Chances are big it is a core issue after all as it seems like the entity is removed somehow.

**Comment by acenuke** [comment]
It happened as well in safe mode. Just took almost 24h instead of a few hours

**Comment by zoechi** [comment]
I have a similar issue since updateing to 2024.08. 

No scripts are shown.

Also this sensor is always shown as `unavailable`

```
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: packages/bathroom_light.yaml
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ template:
   2   │ - binary_sensor:
   3   │   - name: "Illuminance Threshold Bathroom"
   4   │     unique_id: "illuminance_threshold_bathroom"
   5   │     state: >-
   6   │       {{ states('sensor.bathroom_motion_illuminance') | float(100.0) < 45 }}
   7   │ 
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

even though in Developer tools > TEMPLATE this results to `TRUE`

```
{{ states('sensor.bathroom_motion_illuminance') | float(100.0) < 45 }}
```

**Comment by silamon** [comment]
It must be related to something somehow, as it's not really the mass of replies in this report. I would appreciate it if somebody could debug into this further.

**Comment by zoechi** [comment]
It might not be a frontend issue because I get this error

```
The automation "blinds_manual_during_night" (automation.blinds_manual_during_night) has an unknown action: script.blinds_manual_turn_on.
```

So it's not just that the scripts don't show, they also can not be executed.

When I edit the automation no scripts are listed in actions to chose from.

**Comment by zoechi** [comment]
It looks like I messed up.

My setting vanished

```yml
homeassistant:
  packages: !include_dir_merge_named packages/
```
(from https://www.home-assistant.io/docs/configuration/packages/)
