### ISSUE TITLE
Not possible to change the USB-Port in EDL21-Integration

### ISSUE THREAD

**Issue by thoath2** [home-assistant/frontend#21681]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

First I installed the Add-on EDL21.
I added a smart meter device and indicated the general type /dev /ttyusb1 as a port.
The entities have been automatically recognized and data is received.
Now I would like to change the port specification because I would like to use the special form/dev/serial/by-id/...
Problem: There is no way (e.g. in Yaml) to change the port.
Where or how can I do this.
However, I don't want to delete and reinstalling the device because I would then also have to renew the templates and helpers based on it.
I ask you to solve this problem because we can no longer configure in Yaml. Or is there a Yaml position for it?

### Describe the behavior you expected

I expect a possibility to change the port via frontend or yaml

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.7.4

### In which browser are you experiencing the issue with?

firefox

### Which operating system are you using to run this browser?

windows 10

**Comment by silamon** [comment]
This is not the correct issue tracker to file your issue for.

**Comment by thoath2** [comment]
Hi Simon, where is the correct place to write my problem?
Thanks Thomas

**Comment by silamon** [comment]
Right here: https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+edl21%22

**Comment by thoath2** [comment]
Sorry Simon, when I use your link and after this the button "new Issue" then I land on the generally page with the issues:

**Report an issue with Home Assistant Core**
  Report an issue with Home Assistant Core.
**Report a security vulnerability**
  Privately report a security vulnerability.
**Report a bug with the UI, Frontend or Dashboards**
  This is the issue tracker for our backend. Please report issues with the UI in the frontend repository.
**Report incorrect or missing information on our website**
  Our documentation has its own issue tracker. Please report issues with the website there.
**I have a question or need support**
  We use GitHub for tracking bugs, check our website for resources on getting help.
**Feature Request**
  Please use our Community Forum for making feature requests.
**I'm unsure where to go**
  If you are unsure where to go, then joining our chat is recommended; Just ask!

What I have to do for starting a new issue in relation to integration:edl21 ?
Ciao Thomas
