### ISSUE TITLE
telechargement Energy.csv download energy.csv

### ISSUE THREAD

**Issue by Bydoochons** [home-assistant/frontend#21693]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Good morning, 

I noticed 2 errors when downloading the energy.csv file:

-Error 1: The dates and times in the header line are offset by -2 hours.

- Error 2: error in placement of the decimal on certain lines example 2024-08-13T11:00:00,000Z
176 100 000 000 042 instead of 1.76100000000042

For information, each day, the number of errors as well as the times concerned are never the same.2024.8.1

### Describe the behavior you expected

-

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.8.1

### In which browser are you experiencing the issue with?

brave

### Which operating system are you using to run this browser?

windows 11 pro

**Comment by karwosts** [comment]
> Error 1: The dates and times in the header line are offset by -2 hours.

Note that all times are reported in UTC. Is your time zone 2 hours from UTC?

> Error 2: error in placement of the decimal on certain lines

I'm not exactly understanding. Can you upload here an exact CSV that you downloaded that has this error?
