### ISSUE TITLE
Binary Sensor's with device_class: power do not translate properly.

### ISSUE THREAD

**Issue by Petro31** [home-assistant/frontend#21690]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

device_class: power binary sensors incorrectly say "Detected" for "on" and "Clear" for "off".  Historically this has not been the case, even the documentation mentions it should be "On" or "Off".

![image](https://github.com/user-attachments/assets/b2c5402e-5651-4f45-b36c-fe14d4397943)

### Describe the behavior you expected

I expect the translation to be `On` or `Off`

### Steps to reproduce the issue

1.  Look at any device_class: power binary sensor in HA.

### What version of Home Assistant Core has the issue?

2024-8-1

### In which browser are you experiencing the issue with?

All browsers

### Which operating system are you using to run this browser?

All OS's

**Comment by karwosts** [comment]
This translation is from core: https://github.com/home-assistant/core/blob/a50aeb0a660427303e13f6d07616f20988302b93/homeassistant/components/binary_sensor/strings.json#L243-L249

Seems like it has been this way for some time?

But closing as out of scope for frontend.
