### ISSUE TITLE
Hard-coded rounded corner values

### ISSUE THREAD

**Issue by JuliaSoriaSmith** [home-assistant/frontend#21701]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Rounded corners are hard coded in some components, such as the more info pane, as well as the hui-entity-badge. 

These are the variables that can control the border radius, but for the aforementioned they are hard coded.
```css
  ha-card-border-radius: "0px"
  border-radius: "0px"
  button-border-radius: "0px"
  ha-button-border-radius: "0px"
  input-border-radius: "0px"
  dialog-border-radius: "0px"
  paper-listbox-border-radius: "0px"
  paper-dialog-border-radius: "0px"
  entity-preview-border-radius: "0px"
```

This makes it so themes that want custom corners, or no corner radius, or reduced/increases cannot override the radius.

As an example, The light dialog hard codes the border radius to 24px [frontend/src/dialogs/more-info/controls/more-info-light.ts](https://github.com/home-assistant/frontend/blob/3f0f3affb6d8e33d4fe7eb7fb226d8fcff63f33d/src/dialogs/more-info/controls/more-info-light.ts#L354)

### Describe the behavior you expected

The corner radii should respect the theme.
![non-rounded-corners](https://github.com/user-attachments/assets/e6b02e6d-aeb2-42ca-8b0e-032f3b6b68c0)

### Steps to reproduce the issue

N/A

### What version of Home Assistant Core has the issue?

core-2024.8.1

### What was the last working version of Home Assistant Core?

core-2024.8.1

### In which browser are you experiencing the issue with?

Brave v 1.68.137

### Which operating system are you using to run this browser?

Windows 11

**Comment by JuliaSoriaSmith** [comment]
The same can be applied to the badges.

**Comment by ildar170975** [comment]
> such as the more info pane

Check `--ha-dialog-border-radius` variable.

**Comment by JuliaSoriaSmith** [comment]
That was the issue, i got it to work, thanks
