### ISSUE TITLE
Uncaught (in promise): home-assistant.ts:229

### ISSUE THREAD

**Issue by jandechent** [home-assistant/frontend#21707]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Lovelace stuck with "loading data". 

### Describe the behavior you expected

That I see at least the dashboard. Interestingly, all automation work, by zha network works. It seems just the dashboard that does not load. 

### Steps to reproduce the issue

Happens every time. I had rebooted several times, tried `ha core restart --safe-mode`. 

### What version of Home Assistant Core has the issue?

core 2024.8.1

### What was the last working version of Home Assistant Core?

not sure, the one before I guess

### In which browser are you experiencing the issue with?

Edge Version 127.0.2651.98

### Which operating system are you using to run this browser?

Windows 10

### Javascript errors shown in your browser console/inspector

The console shows `Uncaught (in promise) ` here: `home-assistant.ts:229`. As far as I see it, that is the `function protected async checkDataBaseMigration()`

```
Object
code
: 
"unknown_error"
message
: 
"Unknown error"
[[Prototype]]
: 
Object
constructor
: 
ƒ Object()
hasOwnProperty
: 
ƒ hasOwnProperty()
isPrototypeOf
: 
ƒ isPrototypeOf()
propertyIsEnumerable
: 
ƒ propertyIsEnumerable()
toLocaleString
: 
ƒ toLocaleString()
toString
: 
ƒ toString()
valueOf
: 
ƒ valueOf()
__defineGetter__
: 
ƒ __defineGetter__()
__defineSetter__
: 
ƒ __defineSetter__()
__lookupGetter__
: 
ƒ __lookupGetter__()
__lookupSetter__
: 
ƒ __lookupSetter__()
__proto__

```
![image](https://github.com/user-attachments/assets/60d65c06-9725-4185-a1e8-a3f422c469a6)

### Additional information
To be honest, I changed the recorder integration exclude values. But I can not find more information without access to the dashboard. I have keyboard and monitor attached, to execute further commands.

**Comment by karwosts** [comment]
Have you tried other browser, or clearing your browser cache?

**Comment by jandechent** [comment]
Yes. Tried Edge, Firefox and the HASS app (iOS) all hang on "loading data". And after your message, I freshly installed chrome on my iPhone. Also stuck "loading data".

**Comment by karwosts** [comment]
Seems like the recorder may be having some issue.

Can you view your home-assistant.log, see if there's anything showing up as errors for recorder?

Can you paste what are your settings for recorder in configuration.yaml?

**Comment by jandechent** [comment]
Sorry, I bailed out and simply restored the backup from two days ago. I had no SSH or SAMBA active. I close this issue and leave it to you to improve fronted error handling. But it seems a rare occasion.
