### ISSUE TITLE
Onboarding - icon not showing properly in dark mode

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#21709]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On the second or third step of onboarding where you select your home location, it's not showing the magnifying glass icon in dark mode properly. 

The "detect" icon on the right side (and part of the very same text field) displays in the correct color.

<img width="688" alt="Screenshot 2024-08-15 at 9 21 03 PM" src="https://github.com/user-attachments/assets/cbf0be41-57d5-44bf-bd12-5cd9245a8e83">

### Describe the behavior you expected

Icon should be visible in dark mode

### Steps to reproduce the issue

1. Do onboarding while in dark mode

### What version of Home Assistant Core has the issue?

2024.8.1

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

macOS Sonoma

**Comment by devendra0009** [comment]
Hi @SeanPM5 , can you please mention more specifically how to perform onboarding steps or maybe post a video?

**Comment by silamon** [comment]
This should be fairly easy, when creating your development environment, the first thing is the onboarding.
