### ISSUE TITLE
Dialog for removing dashboard config - no red button, wrong text

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#21717]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When deleting everything in your dashboard via raw configuration editor (which is the method to go back to an auto-generated dashboard) it lacks the red text button to indicate it's performing a destruction action. 

Additionally I think the dialog should use the word "Delete" rather than "Remove" as per the [UX guidelines](https://design.home-assistant.io/#Text/remove-delete-add-create), because it's not possible to reverse this change.

<img width="582" alt="Screen Shot 2024-08-16 at 2 29 17 PM" src="https://github.com/user-attachments/assets/78d36bff-ed06-4f0d-acdd-45cad7e0c14d">

### Describe the behavior you expected

Red "Delete" button (because it's performing a destructive action) instead of normal "Remove" button

### Steps to reproduce the issue

Recommend doing this from the [demo](https://demo.home-assistant.io/) just to be safe.

1. Edit Dashboard → three dots → Raw Configuration editor → Select all yaml → Save button top right
2. Dialog will be lacking the red/destructive/warning button

### What version of Home Assistant Core has the issue?

2024.8.1

**Comment by devendra0009** [comment]
Hi @SeanPM5 , can you assign it to me . 
From the statement i understood you want the text "Remove" to be replaced with "Delete" and its background should be red/danger.

**Comment by silamon** [comment]
You can open a pull request if you want to work on this. No need to be assigned.
