### ISSUE TITLE
Unable to use Assistant through browser

### ISSUE THREAD

**Issue by Roarrk** [home-assistant/frontend#21716]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since updating to HA 2024.8.x I can’t use voice assistants anymore when using a web browser. The message “This assistant cannot control your home” appears when selecting the assistant shortcut, while not being able to select any of the available assistants configured. 

<img width="396" alt="image" src="https://github.com/user-attachments/assets/6721cc97-4d9a-4607-881f-9682967af48b">

Notice no assistants are selectable in the drop down

This is both for Safari and Firefox. iOS works fine, and so does debugging the assistant through developer tools.

I have tried with official and unofficial assistant integrations, including deleting and re-adding them (Google AI, Anthropic AI etc). They worked before 8.x upgrade.

### Describe the behavior you expected

I should be able to comunicate with the assistant through the "Assist" window in a browser, as I was previously.

### Steps to reproduce the issue

1. Open "Assist" in a web browser
2. Watch it fail

### What version of Home Assistant Core has the issue?

2024.8.1

### What was the last working version of Home Assistant Core?

Before 2024.8.x

### In which browser are you experiencing the issue with?

Safari Version 18.0 (20619.1.26.11.3) and FireFox 130.0b5 (64-bit)

### Which operating system are you using to run this browser?

macOS Seqouia

### Additional information

https://community.home-assistant.io/t/this-assistant-cannot-control-your-home-since-2024-8-x/759320/8
Forum thread with additional screenshots, and multiple people with the same issue

https://github.com/home-assistant/core/issues/123340
Core repo issue that I did not previously find. I am keeping this issue open as it should probably be here rather than in core.

**Comment by IoSonoAndreaZ** [comment]
issue still present in 2024.8.3

**Comment by kp-bit** [comment]
> issue still present in 2024.8.3

Yes, but only when accessing HA by the local address, it now works in a browser when accessing the (https) Nabu Casa URL...
