### ISSUE TITLE
"History stats" created from the UI are in an undefined state and cannot be deleted

### ISSUE THREAD

**Issue by johnyb0y** [home-assistant/frontend#21722]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

- I tried to create a "history stats" helper via the UI
- I was able to complete the setup without any error message
- However afterwards the helper is in an undefined state. It doesn't have any Entity ID. You cannot delete it from the helpers page, and you cannot find it in the Entity list (all filters disabled)
- The helper also shows a red exclamation mark to indicate some kind of problem, but you are unable to read any error message.

### Describe the behavior you expected

- A helper which is not in an undefined state and can be deleted via the UI
- An error message which indiciates why the red exclamation mark is shown

### Steps to reproduce the issue

See this short video:

https://github.com/user-attachments/assets/15449e68-c381-4feb-849b-197a801b12c7

### What version of Home Assistant Core has the issue?

2024.8.2

### In which browser are you experiencing the issue with?

Firefox 129.0.1

### Which operating system are you using to run this browser?

Windows 11 24H1

**Comment by karwosts** [comment]
I'm not actually sure what's going on in the backend in this case, but what I can tell you from watching your video clip is that the templates you're supplying for start and end time should not have quotes around them. That's likely what's corrupting your entity. 

I get the same effect when I do that and yeah I'm not seeing anything in the logs or anywhere that indicates that that's the problem.

Good news I think if you just click on the entity, it provides the options menu, and if you just remove the quotes, save it, and wait a minute or two (and reboot), I think your entity will come to life. 


But I might encourage you to open issue in home-assistant/core against history-stats integration for some better error handling in this case. If the template with quotes isn't valid it should ideally reject that immediately.

**Comment by johnyb0y** [comment]
@karwosts Thank you. Will test this and create the issue in the other repo. Closing this issue.

**Comment by APoller1** [comment]
I have the same issue

**Comment by MarekW1966** [comment]
Same to me

**Comment by richardax** [comment]
I have the same issue

**Comment by Yorked16** [comment]
I have the same issue
