### ISSUE TITLE
Daikin integration still not working under 2024.8.2

### ISSUE THREAD

**Issue by RonFac** [home-assistant/frontend#21720]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

My Daikin integration has not worked since 2024.7.4 .  I use a SkyFi  adaptor BRP15A61 (skyFi)

### Describe the behavior you expected

Correct functioning of the Daikin integration

### Steps to reproduce the issue

Load 2024.8.2
Check Daikin integration

### What version of Home Assistant Core has the issue?

2024.8.2

### What was the last working version of Home Assistant Core?

2024.7.4

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment]
Not a frontend issue, please try home-assistant/core.
