### ISSUE TITLE
Cannot remove or re-enable disabled helper groups

### ISSUE THREAD

**Issue by jameskitt616** [home-assistant/frontend#21728]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Once a Helper Group is disabled, it cannot be re-enabled or even deleted anymore.

### Describe the behavior you expected

Add the ability to enable or 

### Steps to reproduce the issue

1. Open [Helpers Configuration](https://my.home-assistant.io/redirect/helpers/)
2. Select `CREATE HELPER`
3. Select `Group -> Light group`
4. Select lights and create Group.
5. After group is created click on it and select the settings-cog
6. Now you are presented with the `Enabled` option
![image](https://github.com/user-attachments/assets/5d6c9cfc-77de-4220-bcbc-eab46504c694)
7. Disable the `Enabled` option and click update
8. Now in the list there is disabled Groups, which you cannot re-enable or remove.
![image](https://github.com/user-attachments/assets/f4d2632c-471a-4c3b-8769-91b03033bbc7)
![image](https://github.com/user-attachments/assets/52c89df9-9422-415e-8d44-cb91d8a8515a)

### What version of Home Assistant Core has the issue?

2024.8.2

### In which browser are you experiencing the issue with?

Brave Version 1.68.137, Firefox 129.0, Chromium Version 127.0.6533.99

### Which operating system are you using to run this browser?

Fedora Linux 40

**Comment by jameskitt616** [comment]
I found a temporary workaround to re-enable them:
1. Edit `/usr/share/hassio/homeassistant/.storage/core.entity_registry`
2. Find the Group you disabled (probably by Name)
3. Find in the Line of your Group for `"disabled_by":"user"` and set it to `"disabled_by":null`
4. Restart Home Assistant

**Comment by karwosts** [comment]
You can reenable disabled helpers from the `Entities` table as a workaround, you don't need to mess with the registry. 

I'm not quite sure why it's not possible from Helpers page but I believe there are one (or several) open issues related to this already.
