### ISSUE TITLE
Google Calendar shows only 1 Event

### ISSUE THREAD

**Issue by duczz** [home-assistant/frontend#21730]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When i have 2 or more Events on one day, the Google Calendar Integration shows only one Event (last one)

Template Output:
{{ state_attr('calendar.geburtstage', 'message') }} = "Etienne xxxx Geburtstag"

Action Output:
calendar.geburtstage:
  events:
    - start: "2024-08-18"
      end: "2024-08-19"
      summary: Etienne xxxx Geburtstag
    - start: "2024-08-18"
      end: "2024-08-19"
      summary: Claudia xxxx Geburtstag

The Google Calendar Integration shows in the Attributes "Etienne xxxx Geburtstag" only too. so why only the Actions are correctly i have 2 Events today? Bug or some misstakes from me?

### Describe the behavior you expected

Normaly the Output should be "Claudia xxxx Geburtstag" & "Etienne xxxx Geburtstag"

### Steps to reproduce the issue

 Create 2 Events and check it

### What version of Home Assistant Core has the issue?

2024.8.2

### In which browser are you experiencing the issue with?

Chrome 127.0.6533.120

### Which operating system are you using to run this browser?

W11

**Comment by karwosts** [comment]
This doesn't seem like a frontend issue, or maybe I'm misunderstanding what you're trying to say. 

If a template is rendering a value that's not what you expect, that's a backend/core issue.
