### ISSUE TITLE
reolink integration does not allow bypassing the use of password

### ISSUE THREAD

**Issue by Menethoran** [home-assistant/frontend#21732]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

My cameras are set to default settings (user:admin, no password) as i have individuals who like to factory reset the cameras (back to factory default WHICH IS "admin" WITH NO PASSWORD). Because of the integrations REQUIREMENT for a password, i lose my cameras every time someone factory resets them. This is obviously a HUGE security flaw and should probably be addressed fairly quickly, you know... since catching people doing stupid shit is what the cameras are intended to do, so when they are factory reset and you REQUIRE a password, they stop being of any use and become nothing more than useless ornaments

### Describe the behavior you expected

I expect to be able to set no password BECAUSE THIS IS HOW THEY ARE FACTORY SET: WITHOUT A PASSWORD

### Steps to reproduce the issue

1.
2.
3.
...
try to integrate a camera using DEFAULT USER AND PASSWORD

### What version of Home Assistant Core has the issue?

any

### What was the last working version of Home Assistant Core?

any

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

any

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
this question and its explanation make absolutely no sense. this must be "case specific, and should probably be notated as so.
```

### Javascript errors shown in your browser console/inspector

```txt
na
```

### Additional information

i opened this issue about 60 days ago. it was closed. THIS IS STILL AN ISSUE.

**Comment by karwosts** [comment]
This is not a frontend issue, if Reolink integration wants optional password it needs to be configured as such in home-assistant/core.

**Comment by Menethoran** [comment]
Well, then, fix where it points to report an issue.

Because I'm going to keep submitting through the same process until my
issue or the underlying issue or your redirect are fixed.
  - Robert Burton Thompson V
    President: RnD Technologies
    Ph: (717)466-9069
