### ISSUE TITLE
Card out of range

### ISSUE THREAD

**Issue by kelilive** [home-assistant/frontend#21743]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

![{Y}V}L~EEKG8LM$ )(J~CI2](https://github.com/user-attachments/assets/9e11a966-1c94-4d3b-b282-dc171b0019c4)

### Describe the behavior you expected

Look at the picture above and you can see the problem

### Steps to reproduce the issue

None

### What version of Home Assistant Core has the issue?

2024.8.1

### What was the last working version of Home Assistant Core?

2024.8.1

**Comment by karwosts** [comment]
That is from HACS, not part of the HA frontend. You can report this in their github repository.
