### ISSUE TITLE
Unable to delete a wrongfully configured 'History Stats'-helper (no delete button in GUI)

### ISSUE THREAD

**Issue by Wendelstein7** [home-assistant/frontend#21749]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I use all kinds of helpers all the time, and they're doing great. However, I have noticed that the information dialog behaviour is different for helpers which have not yet 'initialised' (my wording for: done their first measurement or meaningful action). Until they are 'initialised' - they open the configuration dialog when clicked, rather than an entity or entity-settings dialog. Only the latter dialog contains a 'delete' button, meaning that you can not remove/delete helpers which could not meaningfully initialise, for example because you configured them wrong.

![image](https://github.com/user-attachments/assets/53df1d12-6894-467a-915c-8edbe7f1e69d)

### Describe the behavior you expected

I expect the pop-up dialog of an 'uninitialised' or wrongly configured helper to feature a 'delete'-button.

### Steps to reproduce the issue

1. Click 'Create Helper' in the Helpers overview.
2. Choose 'History Stats'.
3. In the first configuration dialog, enter a name, select any entity and type anything in the 'state' textbox. Click next.
4. In the second configuration dialog, enter garbage (any text) in the 'start' and 'end' templates. Click submit.
5. You will now find yourself with an non-deletable helper you just created that can not sucesfully 'initialise'.

### What version of Home Assistant Core has the issue?

2024.8.2

### In which browser are you experiencing the issue with?

Google Chrome 127.0.6533.119 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Ubuntu 24.04 LTS (x86-64)

### State of relevant entities

```txt
N.A. (entities can not be found there)
```

**Comment by ildar170975** [comment]
A similar issue - https://github.com/home-assistant/frontend/issues/21722
Agree that a `history_stats` helper must have a "Delete" button.
May be a core issue.

**Comment by Wendelstein7** [comment]
@ildar170975 Would you recommend me that I raise this issue in the core repository?

**Comment by ildar170975** [comment]
@Wendelstein7 
Since I am not a part of HA team, I may only give suggestions  based on my life experience)))
Let's wait for an official feedback from Devs.
