### ISSUE TITLE
Blank Actions tab

### ISSUE THREAD

**Issue by moicphil** [home-assistant/frontend#21741]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Good morning
I no longer have access to the "actions" tab with Chome browser. Ok with Firefox
same after restarting HA or clear cache.

![2024-08-20_08h02_01](https://github.com/user-attachments/assets/ae8c2ae1-26c9-4ed8-8f72-1c5473d1fffb)

### Describe the behavior you expected

access to the "actions" tab

### Steps to reproduce the issue

1. Open action tab

### What version of Home Assistant Core has the issue?

2024.8.2

### What was the last working version of Home Assistant Core?

2024.8.1

**Comment by moicphil** [comment]
Thanks

indeed there are errors but I can't understand the problem

![2024-08-20_22h31_14](https://github.com/user-attachments/assets/7631a9a5-35cc-4b76-9d5e-457cf4e9b0bb)



`log-message.ts:36 
        
        
       GET http://192.168.1.41:8123/unknown/node_modules/memoize-one/dist/memoize-one.esm.js 404 (Not Found)
(anonymous) @ stacktrace-gps.js:37
r @ stacktrace-gps.js:23
(anonymous) @ stacktrace-gps.js:218
_get @ stacktrace-gps.js:195
(anonymous) @ stacktrace-gps.js:289
findFunctionName @ stacktrace-gps.js:287
(anonymous) @ stacktrace-gps.js:272
Promise.then
(anonymous) @ stacktrace-gps.js:267
pinpoint @ stacktrace-gps.js:266
(anonymous) @ stacktrace.js:113
(anonymous) @ stacktrace.js:108
(anonymous) @ stacktrace.js:107
fromError @ stacktrace.js:105
t @ log-message.ts:36
(anonymous) @ logging-mixin.ts:66
Show 13 more frames
Show less
log-message.ts:36 
        
        
       GET http://192.168.1.41:8123/unknown/src/reactive-element.ts 404 (Not Found)
(anonymous) @ stacktrace-gps.js:37
r @ stacktrace-gps.js:23
(anonymous) @ stacktrace-gps.js:218
_get @ stacktrace-gps.js:195
(anonymous) @ stacktrace-gps.js:289
findFunctionName @ stacktrace-gps.js:287
(anonymous) @ stacktrace-gps.js:272
Promise.then
(anonymous) @ stacktrace-gps.js:267
pinpoint @ stacktrace-gps.js:266
(anonymous) @ stacktrace.js:113
(anonymous) @ stacktrace.js:108
(anonymous) @ stacktrace.js:107
fromError @ stacktrace.js:105
t @ log-message.ts:36
(anonymous) @ logging-mixin.ts:66
Show 13 more frames
Show less
log-message.ts:36 
        
        
       GET http://192.168.1.41:8123/unknown/src/lit-element.ts 404 (Not Found)
(anonymous) @ stacktrace-gps.js:37
r @ stacktrace-gps.js:23
(anonymous) @ stacktrace-gps.js:218
_get @ stacktrace-gps.js:195
(anonymous) @ stacktrace-gps.js:289
findFunctionName @ stacktrace-gps.js:287
(anonymous) @ stacktrace-gps.js:272
Promise.then
(anonymous) @ stacktrace-gps.js:267
pinpoint @ stacktrace-gps.js:266
(anonymous) @ stacktrace.js:113
(anonymous) @ stacktrace.js:108
(anonymous) @ stacktrace.js:107
fromError @ stacktrace.js:105
t @ log-message.ts:36
(anonymous) @ logging-mixin.ts:66
Show 13 more frames
Show less
154compute_domain.ts:2 Uncaught (in promise) TypeError: e.substr is not a function
    at n (compute_domain.ts:2:12)
    at i.<anonymous> (developer-tools-action.ts:375:22)
    at i.n [as _fields] (memoize-one.esm.js:37:35)
    at i.value (developer-tools-action.ts:106:37)
    at i.update (lit-element.ts:160:24)
    at i.performUpdate (reactive-element.ts:1329:14)
    at i.scheduleUpdate (reactive-element.ts:1261:17)
    at i._$Ej (reactive-element.ts:1233:25)`

**Comment by karwosts** [comment]
Thanks I think that's helpful. I think you might have put some corrupted yaml in the action editor at some point, like perhaps defining an action that is not a string. 

Can you try logging out on your profile page and log back in? I think that will clear your local session and reset the form.

**Comment by moicphil** [comment]
Thanks, problem solved. you gave me the solution
