### ISSUE TITLE
Reolink integration: disallowed password characters

### ISSUE THREAD

**Issue by kjkent** [home-assistant/frontend#21754]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Setting up a new entity in the Home Assistant android app, adding a doorbell is prevented by the device password entry box:

```
Password contains incompatible special character, only these characters are allowed: a-z, A-Z, 0-9 or @$*~_-+=!?.,:;'()[]
```

The password in question includes the character `&`, which is accepted by the device and Reolink systems.

Is this expected behaviour due to a limitation of HA, or are these password constraints designed to match Reolink's and no longer do so?

### Describe the behavior you expected

The existing device password is accepted and the new device added.

### Steps to reproduce the issue

1. Add Reolink integration to Android app and attempt to add new device
2. Enter device password containing an ampersand
3. Be prevented from adding device due to password error.

### What version of Home Assistant Core has the issue?

2024.8.2 / 20240809.0

### In which browser are you experiencing the issue with?

Android App

### Which operating system are you using to run this browser?

Android 14

**Comment by silamon** [comment]
Just open a new issue at https://github.com/home-assistant/core towards the integration: reolink. This is for frontend specific issues.

**Comment by kjkent** [comment]
@silamon thank you — I wasn't sure where the password restriction was implemented. Will open this in the linked repo.
