### ISSUE TITLE
Balanced entitie doesn't appear in RLC-510A

### ISSUE THREAD

**Issue by leocotes** [home-assistant/frontend#21756]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have 3 reolink cameras:

2 x RLC-520A
1 x RLC-510A

The cameras RLC-520A appear the video balanced option to enable and use, but in my RLC-510A just shows clear and fluent options but not the balanced

### Describe the behavior you expected

In my 510A appears the 3 entities like the reolink mobile app (clear,fluent and balanced)

### Steps to reproduce the issue

I tried every thing, like, remove the device and reinstall and update to the last firmware avaliable from reolink website, but without success.

### What version of Home Assistant Core has the issue?

2024.8.2

### In which browser are you experiencing the issue with?

127.0.6533.120 (Versão oficial) 64 bits (cohort: Stable)

**Comment by silamon** [comment]
Open an issue towards the reolink integration at https://github.com/home-assistant/core
