### ISSUE TITLE
open home foundation logo flows off the screen

### ISSUE THREAD

**Issue by CFenner** [home-assistant/frontend#21761]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On my NSPanel pro the loading screen has a glitch.

### Describe the behavior you expected

See everything

### Steps to reproduce the issue

1. restart the app on a small (rectangular?) screen
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.8.2

### Additional information

![tempImage3XRDB0](https://github.com/user-attachments/assets/1dd11be6-aef1-4148-a4a0-17730e62d976)
![tempImageM5VTXw](https://github.com/user-attachments/assets/c543bb76-acf5-4ab9-a619-a01ff264254a)

**Comment by gurglingtonic** [comment]
i'm facing the same. it would be great to hide the open home foundation logo on smaller screen.
