### ISSUE TITLE
Area card: average temperature - seems that devices are not accounted

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#21774]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

There is an area with 2 sensors with `device_class: temperature`:
![изображение](https://github.com/user-attachments/assets/0806124c-a426-4e65-9eea-1b3c139f98a7)
```
{% for SENSOR in states.sensor |
                  selectattr('entity_id','in',area_entities('Б комната')) |
                  selectattr('attributes.device_class','eq','temperature') |
                  map(attribute='entity_id') |
                  list -%} 
  {{state_attr(SENSOR,'friendly_name')}} = {{states(SENSOR)}} {{state_attr(SENSOR,'unit_of_measurement')}}
{% endfor %} 
```
Note that these sensors are not associated to any devices - these sensors are directly assigned to this area.
Here is how Area card is shown - an average value is "27.5" (as expected):
![изображение](https://github.com/user-attachments/assets/8badf9b1-90a9-4064-b7b1-ebcd68595fe1)

And another area has 4 sensors with `device_class: temperature`:
![изображение](https://github.com/user-attachments/assets/1afaca3c-3a18-46e0-9c2f-43005136161d)
```
{% for SENSOR in states.sensor |
                  selectattr('entity_id','in',area_entities('М комната')) |
                  selectattr('attributes.device_class','eq','temperature') |
                  map(attribute='entity_id') |
                  list -%} 
  {{state_attr(SENSOR,'friendly_name')}} = {{states(SENSOR)}} {{state_attr(SENSOR,'unit_of_measurement')}}
{% endfor %}   
```
Here 1 sensor is not associated to a device - this sensor is directly assigned to this area.
Another 3 sensors created by ASUSWRT integration & belong to some router - which is assigned to this area.
Here is how Area card is shown - an average value is "27.6" (i.e. equal to the 1st sensor):
![изображение](https://github.com/user-attachments/assets/755ddf31-ba09-45dd-987f-24cf8731a96d)

I would conclude that sensors associated with devices in this area are not accounted.
From one side - it gives a correct result in case of that "router case".
From another side - if a sensor belongs to some climate device like Air purifier and this device is assigned to the area - then this sensor is supposed to be accounted.
Am I missing something?

### Describe the behavior you expected

-

### Steps to reproduce the issue

-

### What version of Home Assistant Core has the issue?

2024.8.2

### In which browser are you experiencing the issue with?

Chrome 127.0.6533.100

### Which operating system are you using to run this browser?

Win10x64

**Comment by karwosts** [comment]
Area card excludes sensors which are `diagnostic` or `config` entity category. (you can see entity category on their devices page)

**Comment by ildar170975** [comment]
Thanks a lot for clarification.
Guess I should close it.
