### ISSUE TITLE
new Badges (and some other cards): last_changed may be displayed as "in xxx seconds" (countdown)

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#21787]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

As an old-fashioned man, I believe that that `last-changed` should be shown like "XX seconds ago".
Here is what I see in new badges:
```
type: entity
entity: sensor.xiaomi_cg_1_co2
state_content:
  - last_changed
  - state
```
![Untitled Project](https://github.com/user-attachments/assets/6b701cc2-cc0a-4d89-9aff-7de5f32cdc9a)
and this is a COUNTDOWN

### Describe the behavior you expected

see above

### Steps to reproduce the issue

see above

### What version of Home Assistant Core has the issue?

2024.8.2

### In which browser are you experiencing the issue with?

Chrome 127.0.6533.100

### Which operating system are you using to run this browser?

Win10x64

**Comment by ildar170975** [comment]
And seems that this has become a COMMON glitch - see the Entities card:
![изображение](https://github.com/user-attachments/assets/1bad19fb-3007-4556-90c5-6b242cbf8064)
where "in XXX sec" was shown initially - and then was changed to a proper "XXX sec ago" in Editor.

**Comment by karwosts** [comment]
Generally this indicates that time is out of sync between your frontend and backend. Last_changed is reported as a timestamp, and if your frontend sees that timestamp is in the future, it will show it as "in X seconds". Double check your time is correctly synced on all clients.

**Comment by ildar170975** [comment]
Good point about a possible issue with sync. Will check it.
But this glitch MAY appear with same sensor - and MAY not after F5 - within same update cycle.

**Comment by ildar170975** [comment]
Also, I believed that "relative_time" is calculated on a server side - then why a possible difference between server & client can influence?

**Comment by karwosts** [comment]
> Also, I believed that "relative_time" is calculated on a server side - then why a possible difference between server & client can influence?

No this countdown value is calculated in frontend. Backend sends timestamp of last_changed, frontend subtracts this from what frontend thinks is "now". If frontend time is behind reality (or backend is ahead of reality), last_changed can appear to be in the future. 

If you're thinking of relative_time in a template that is calculated in the backend, but that's not what's being used here.

**Comment by ildar170975** [comment]
I see. Thanks for explanations.
Although I do not see a major difference between NTP server's time & local time both on a server & client, this seems to be NOT a HA bug.
Will try to investigate the issue on my side.
Closing now.
