### ISSUE TITLE
Dev tools: prevoiusly selected "Assist" page is stuck

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#21781]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Select "Dev tools" on a sidebar:
![изображение](https://github.com/user-attachments/assets/426de355-cce3-4536-8deb-5888f13a9fa8)

See that "Dev tools -> yaml" page is open:
![изображение](https://github.com/user-attachments/assets/4dc81641-aa17-44e0-8c22-0a8681ef9d71)

Select "Assist" on a top toolbar.
See that "Dev tools -> assist" page is open:
![изображение](https://github.com/user-attachments/assets/c6c9e176-e4a3-4e5a-bb51-be0b0160daee)

Select "Dev tools" on a sidebar:
![изображение](https://github.com/user-attachments/assets/426de355-cce3-4536-8deb-5888f13a9fa8)

You are stuck on the "Assist" page.

Select "History" on a sidebar.
See that "History" page is open.
Select "Dev tools" on a sidebar - > again "Assist" page is opened.

Ofc this is not about a particular "Assist" page - same happens with any page inside "Dev tools".

### Describe the behavior you expected

Choosing the "Dev tools" button on a sidebar should cause navigating to "Dev tools -> yaml"

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2024.8.2

### In which browser are you experiencing the issue with?

Chrome 127.0.6533.100 

### Which operating system are you using to run this browser?

Win10x64

**Comment by ildar170975** [comment]
Let me remind that choosing some dashboard from the sidebar always opens the 1st view of this dashboard (which is correct & expected), not some last used.

**Comment by karwosts** [comment]
Not a bug, working as intended:

```
      if (!page || page === "not_found") {
        // If we can, we are going to restore the last visited page.
        return this._currentPage ? this._currentPage : "yaml";
      }
```

Developer tools isn't a dashboard so that argument is not applicable.

**Comment by ildar170975** [comment]
> Developer tools isn't a dashboard so that argument is not applicable.

Your statement is very questionable.
Dev tolls is the only "multi-tab" section of UI (not to mention dashboards).

> Not a bug, working as intended:

Good, but may be the initial logic is not appropriate in this case?

**Comment by ildar170975** [comment]
Created a discussion: https://github.com/home-assistant/frontend/discussions/21783
