### ISSUE TITLE
2024.9.0b0 - issue with new resize-sections: Displayed underneath each other

### ISSUE THREAD

**Issue by ChristophCaina** [home-assistant/frontend#21826]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The new section resize option is not showing the expected result as in the editor mode.

### Describe the behavior you expected

sections should be shown as in the designer.

### Steps to reproduce the issue

1. Created a three column section dashboard.
![grafik](https://github.com/user-attachments/assets/d48648f5-531b-4ef0-bf77-f455f47c9ffe)

2. set the first section to a width of two sections
![grafik](https://github.com/user-attachments/assets/f0fa0fb3-2370-4043-89ff-41facb4d9bad)

3. Saving the canges:
![grafik](https://github.com/user-attachments/assets/03b9ad2a-a22f-44e3-9b24-502e4d4243e8)

### What version of Home Assistant Core has the issue?

2024.9.0b0

### In which browser are you experiencing the issue with?

chrome 128.0.6613.114

**Comment by fightingmajor** [comment]
So in my test page, it's set to 2 columns and the section is set to 2 columns.  Top row is 4 tile cards and bottom is 2 button cards.  The button cards are set to 1 x 2 under size.  While in Edit, it looks as it should, but when hit done, it's squished.  I'm just playing around with the beta to see what it can do, but I don't think the sizing should be different from Edit and Done.
<img width="1460" alt="Screenshot 2024-08-28 at 1 16 11 PM" src="https://github.com/user-attachments/assets/d6d43e67-460f-47f1-9d60-4d503a606ef0">
<img width="1460" alt="Screenshot 2024-08-28 at 1 16 19 PM" src="https://github.com/user-attachments/assets/565032e3-d788-4a0c-845f-9d7599075e06">

**Comment by ChristophCaina** [comment]
I agree, the size shouldn't be different from the Editor...
What Happens, If you add a third section to your Layout? 

I guess, the two sections in the bottom should set the correct size for the top one

**Comment by piitaya** [comment]
There is a PR open to fix it. It will be fixed in the next beta.
