### ISSUE TITLE
August - integration

### ISSUE THREAD

**Issue by JanKraslice** [home-assistant/frontend#21821]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

August in conjunction with yale does not update the status of the opening sensor after the door has been open for a long time.

If you unlock the door (no matter which way) and then open it, the status of the opening sensor changes to "open", close the door and the sensor status changes to "closed".

However, if you leave the door open for a longer period of time, e.g. 10 minutes or more, and then close it, the opening sensor still reports ``open'' and does not change even if you open and close the door again! 

The status of the open sensor will only change when the door is locked, this is a major error that disables conditions that depend on the sensor status.
This bug is on the latest available version of the assistant

### Describe the behavior you expected

The state of the opening sensor must change within a short time and whenever the state changes

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.8.3

### What was the last working version of Home Assistant Core?

2024.8.3

**Comment by karwosts** [comment]
You're in the wrong place, this is a core issue, not a frontend issue.

Try https://github.com/home-assistant/core/issues/

**Comment by JanKraslice** [comment]
So it applies to all other integrations.

Do you have any more news about a possible fix for CORE itself?
