### ISSUE TITLE
Action "Counter: Reset" does not have an option to chose the entity ID

### ISSUE THREAD

**Issue by terierul** [home-assistant/frontend#21832]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

in frontend there is no option to chose entity id for Counter: Reset Action. you have to edit manually and add it in yaml
**But this issue is applicable for all actions of type Counter: * ** 

button missing
![image](https://github.com/user-attachments/assets/f89383bd-b86d-4b9f-a3dd-96584ec13b42)

yaml manual configuration of entity id
![image](https://github.com/user-attachments/assets/b7de35ee-3e98-4a3a-8266-97b6ed8df784)

### Describe the behavior you expected

There should be a button for adding entity id

### Steps to reproduce the issue

1. start a new automatization
2. Perform Add Action - Counter:Reset

### What version of Home Assistant Core has the issue?

2024.8.3

### In which browser are you experiencing the issue with?

Google Chrome Version 128.0.6613.8

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
Looks normal on my end. Make sure you really try clearing the browser cache, sometimes there are caching issues here I think.

**Comment by terierul** [comment]
I did a clear cache before opening the issue.
I tested now with MS Edge browser. Same result

**Comment by terierul** [comment]
same problem in action light
![image](https://github.com/user-attachments/assets/7c6e34ca-d6db-44e3-8fab-809a8293a3cc)

**Comment by karwosts** [comment]
Please also test in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode).

**Comment by terierul** [comment]
in safe mode is ok

![image](https://github.com/user-attachments/assets/96a280d7-c783-47a0-abfa-6dc620a562df)

after that I did a restart in normal mode and was failing again.
after that I decided to restart the full machie (RPI4) and...everything back to normal...
really very strange. 
I will close the issue and thanks for support

**Comment by terierul** [comment]
closed
