### ISSUE TITLE
Energy Dashboard exports data for a month one day off

### ISSUE THREAD

**Issue by B1rdEater** [home-assistant/frontend#21848]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In Energy Dashboard, montly overview --> download data to CSV. For the month August, the data is one day off. CSV contained information for 31. July upto 30. August. Also, low and hight tarifs are one day off!

### Describe the behavior you expected

Expected csv to include energy information from 1. August upto 31. August. Low tarif should be in the weekend, but is now on Friday / Saterday.

### Steps to reproduce the issue

1. Energy Dashboard
2. Select monthly view
3. Select august
4. Download data
5. Check CSV
...

### What version of Home Assistant Core has the issue?

2024.8.3

**Comment by karwosts** [comment]
Note the timestamps are UTC, so while it may say July31, in your local timezone that may correspond to midnight of August 1. Please review or upload your CSV to confirm.

**Comment by mdkeil** [comment]
I have decribed the same behaviour [here](https://community.home-assistant.io/t/bug-wrong-calculation-in-time-period-views/767139).. It depends on diffenrent timezones between HA-Server (docker for me) and the WebUI/App. At the moment, I'm working in another timezone as my HA-Server@home--  
At the WebClient/UI-- I get into the "problem", if I choose more then 3 days as time-frame.
