### ISSUE TITLE
Graphs are missing data since update

### ISSUE THREAD

**Issue by dshefman** [home-assistant/frontend#21866]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After the most recent update, the graphs in my history view are not connecting cleanly anymore.  I can confirm that the data has been available the whole time. 
<img width="929" alt="image" src="https://github.com/user-attachments/assets/5192dfd0-2c97-40aa-b59c-05c8008ecc84">

### Describe the behavior you expected

I expect to see continuous lines for the continuous data. This started breaking once I updated.

### Steps to reproduce the issue

1. I'm tracking my solar production and consumption via enphase's integration. 
2. Over the course of the day, it randomly doesn't appear to log data. 

### What version of Home Assistant Core has the issue?

2024.8.3

### State of relevant entities

```txt
sensor.envoy_121950047565_current_power_consumption
Envoy 121950047565 Current power consumption
unavailable	state_class: measurement
unit_of_measurement: kW
device_class: power
icon: mdi:flash
friendly_name: Envoy 121950047565 Current power consumption
sensor.envoy_121950047565_current_power_production
Envoy 121950047565 Current power production
unavailable	state_class: measurement
unit_of_measurement: kW
device_class: power
icon: mdi:flash
friendly_name: Envoy 121950047565 Current power production
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

**Comment by karwosts** [comment]
If there are gaps in the graph that likely means the sensor is going temporarily `unavailable` or `unknown`, which would be an issue with the integration, not with frontend.
