### ISSUE TITLE
Tailwind integration becomes unavailable every few minutes when disabling internet access

### ISSUE THREAD

**Issue by peterbarbosa** [home-assistant/frontend#21872]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I am running the Tailwind integration on HA, and have recently disabled internet access via my router for my Tailwind device. The integration continues to work, but periodically it will show as unavailable.

### Describe the behavior you expected

With internet access disabled, I am still able to perform all operations on my Tailwind device, but the espressif devices becomes unavailable every few minutes, and the Garage Door device becomes unavailable every few months

### Steps to reproduce the issue

1. Install fresh instance of HA
2. Install/configure Tailwind device (IP/local access key via Tailwind portal)
3. Test door open/close to confirm it is integrated correctly
4. Go to your router, disable internet access to Tailwind static IP
5. Go to HA, everything works.
6. A few seconds later, entities become unavailable
7
<img width="273" alt="Screenshot 2024-09-03 171627" src="https://github.com/user-attachments/assets/bd2aaaaa-5859-49a2-b0c8-0eac738fb43f">
<img width="293" alt="Screenshot 2024-09-03 171650" src="https://github.com/user-attachments/assets/69995a5b-728a-4ebb-881e-502dc4bb4461">
/unknown

### What version of Home Assistant Core has the issue?

2024.8.3

### In which browser are you experiencing the issue with?

Chrome (all versions)

### Which operating system are you using to run this browser?

Apple iOS, Windows 11, Mac OS

**Comment by karwosts** [comment]
Please report in home-assistant/core, this isn't a frontend issue.
