### ISSUE TITLE
Duplicated label in number selector

### ISSUE THREAD

**Issue by selvalt7** [home-assistant/frontend#21882]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Number selector in box mode has duplicated label outside of the input field
![number selector](https://github.com/user-attachments/assets/91290cd8-9208-4d81-a00c-e79dd52ca424)

### Describe the behavior you expected

Number selector in box mode should only have one label.

### Steps to reproduce the issue

1. Add new `sensor` card
2. Hours to show field has two labels

### What version of Home Assistant Core has the issue?

2024.9.0

**Comment by Nerwyn** [comment]
[Here's the PR that introduced it.](https://github.com/home-assistant/frontend/pull/21835#issuecomment-2330581620).
