### ISSUE TITLE
Config flow - translation section does not work properly

### ISSUE THREAD

**Issue by EnzoD86** [home-assistant/frontend#21887]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I noticed some strange behavior with the "section" object used in the config flow.

When I use the "section" in the config flow the header is translated correctly, however the content is not translated.

![image](https://github.com/user-attachments/assets/4090cb3f-3533-4db2-afee-c7f7208d8d3b)

If instead you use the "sections" inside the OptionsFlow then the display is correct.

![image](https://github.com/user-attachments/assets/0640b2ad-28df-486a-af7c-523ffe52eb18)

### Describe the behavior you expected

I would expect the contents of the section to always be displayed correctly.

### Steps to reproduce the issue

I created a simple example, very similar to the one in the official documentation

this is the config_flow.py
```
class ConfigFlowHandler(config_entries.ConfigFlow, domain=DOMAIN):
    async def async_step_user(self, user_input):
        data_schema = {
            vol.Required("username"): str,
            vol.Required("password"): str,
            "additional_options": section(
                vol.Schema(
                    {
                        vol.Required("test1", default=True): bool,
                        vol.Required("test2", default=True): bool,
                    }
                ),
                {"collapsed": False},
            )
        }
        return self.async_show_form(step_id="user", data_schema=vol.Schema(data_schema))

    @staticmethod
    @callback
    def async_get_options_flow(config_entry):
        return OptionsFlowHandler(config_entry)


class OptionsFlowHandler(config_entries.OptionsFlow):
    def __init__(self, config_entry):
        self.config_entry = config_entry

    async def async_step_init(self, user_input):
        return await self.async_step_user(user_input)
        
    async def async_step_user(self, user_input):
        data_schema = {
            vol.Required("username"): str,
            vol.Required("password"): str,
            "additional_options": section(
                vol.Schema(
                    {
                        vol.Required("test1", default=True): bool,
                        vol.Required("test2", default=True): bool,
                    }
                ),
                {"collapsed": False},
            )
        }
        return self.async_show_form(step_id="user", data_schema=vol.Schema(data_schema))
```
and this is the json file en.json

```
{
  "config": {
    "step": {
      "user": {
        "title": "Test configuration",
        "data": {
          "username": "Username",
          "password": "Password"
        },
        "sections": {
          "additional_options": {
            "name": "Additional options",
            "data": {
              "test1": "Test 1",
              "test2": "Test 2"
            }
          }
        }
      }
    }
  },
  "options": {
    "step": {
      "user": {
        "title": "Test configuration",
        "data": {
          "username": "Username",
          "password": "Password"
        },
        "sections": {
          "additional_options": {
            "name": "Additional options",
            "data": {
              "test1": "Test 1",
              "test2": "Test 2"
            }
          }
        }
      }
    }
  }
}
```

The json file is loaded correctly because as you can see, the textboxes outside the section are translated correctly (both in the config flow and in the options flow).
Am I doing something wrong?
Thank you

### What version of Home Assistant Core has the issue?

core-2024.9.0

### In which browser are you experiencing the issue with?

Google Chrome 128.0.6613.114 

### Which operating system are you using to run this browser?

Windows 11

### Additional information

In previous versions, the "section" in config flow does not work correctly. With the latest update it improved but still has this problem.

**Comment by karwosts** [comment]
Will be fixed by #21924
