### ISSUE TITLE
Frontend -> Button -> Perform Action -> Automation: Reload = Missing option to select entity / device / area in frontend

### ISSUE THREAD

**Issue by coalfield** [home-assistant/frontend#21906]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When creating a button in the front end using:

Frontend -> Button -> Perform Action -> Automation: Reload

There is no option to select the automation to reload.  It works for Automation Toggle, On, Off but not for Reload.  It can only be configured in YAML.

### Describe the behavior you expected

Show Targets option to select between Area, Device, Entity, Label.

![Screenshot 2024-09-06 014111](https://github.com/user-attachments/assets/9ca73691-a896-4907-8f09-4ee4a260689d)

### Steps to reproduce the issue

1. Add Card in frontend
2. Select button
3. Select entity (helper button)
4. Change **Tap** behaviour to 'Perform Action'
5. Change **Action** to 'Automation: Reload'

No option shows to select the automation to reload.

![Screenshot 2024-09-06 014048](https://github.com/user-attachments/assets/26f65a12-23f6-4a38-a18b-988cc9a819f4)

Changing step 5 to **Automation: Turn off** or **Automation: Turn on** for example shows correctly as expected.

![Screenshot 2024-09-06 014111](https://github.com/user-attachments/assets/62ad628f-1664-4f7a-9823-207d8a7e60a8)

### What version of Home Assistant Core has the issue?

2024.9.0

### In which browser are you experiencing the issue with?

Brave Version 1.69.162 Chromium: 128.0.6613.120 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11 (latest)

**Comment by ildar170975** [comment]
https://www.home-assistant.io/docs/automation/services/
![image](https://github.com/user-attachments/assets/7c2e91d4-0d1b-4eb2-99aa-d20a4de7656d)

**Comment by karwosts** [comment]
This is as intended, this service has no selectors.
