### ISSUE TITLE
Visual Script Editor not showing form

### ISSUE THREAD

**Issue by owingst** [home-assistant/frontend#21901]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When attempting to create a new script, no form is presented to be filled in. What I see is the following:

<img width="1596" alt="scriptissue" src="https://github.com/user-attachments/assets/6ce808d5-2667-4ab4-95b5-01476318c664">

### Describe the behavior you expected

I expected to be presented with a form to create the new script.

<img width="1046" alt="visualeditor" src="https://github.com/user-attachments/assets/b135c6d8-4860-43fc-a014-04c6179c630b">

### Steps to reproduce the issue

1. Create a new script....that's it.
2.
3.
...

### What version of Home Assistant Core has the issue?

Core 2024.9.0

### In which browser are you experiencing the issue with?

Chrome: 128.0.6613.119 (Official Build) (arm64)

### Which operating system are you using to run this browser?

Mac: Version 14.6.1 (23G93)

**Comment by karwosts** [comment]
The old form from your bottom screenshot is gone, the top picture is the current design of the script editor.

Name & icon are chosen when you save the script. 
The entity_id is automatically generated
The mode can be changed from the overflow menu.

**Comment by owingst** [comment]
Thank you!
