### ISSUE TITLE
Graph "Individual Devices" does not show up on energy dashboard (2024.9.1) 

### ISSUE THREAD

**Issue by coro1404** [home-assistant/frontend#21919]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Looking for untracked energy I noticed that the Graph "idividual devices" does not show up at all in my energy dashboard

### Describe the behavior you expected

Graph "individual devices" ist present at bottom of page

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2024.9.1

**Comment by karwosts** [comment]
Have you added individual devices in the energy settings page?

**Comment by coro1404** [comment]
yes 
![image](https://github.com/user-attachments/assets/e1b72273-55d7-4db5-b62c-1790c206cef0)

**Comment by karwosts** [comment]
Those I believe are not the individual devices, that is "Grid Consumption". 

For this feature "Individual devices" must be added to the box highlighted in green, not under "grid consumption"

![image](https://github.com/user-attachments/assets/fb10fc88-4d4b-4525-95e6-6f3738b9a722)

**Comment by coro1404** [comment]
ok obviously an oversight on my part - thanks for taking care. I'll close the issue
