### ISSUE TITLE
CarPlay entities

### ISSUE THREAD

**Issue by jackshaw20** [home-assistant/frontend#21920]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have hidden a lot of entities that I don’t want users to see like helpers etc that are used for automations.

however in CarPlay some of them still show in the control section, how can these be hidden please?

also some devices where I have changed the type from switch to light, CarPlay still shows both even though switch is hidden.

### Describe the behavior you expected

not to show hidden entities

### Steps to reproduce the issue

1. hidden entities in the settings
2. reboot HA

### What version of Home Assistant Core has the issue?

2024.9.1

### What was the last working version of Home Assistant Core?

none

**Comment by karwosts** [comment]
As far as I know frontend doesn't have anything special related to do with carplay. This might be in the wrong repo. Maybe you need one of the apple app related repositories.
