### ISSUE TITLE
TP-Link Missing Main Integration Entry

### ISSUE THREAD

**Issue by dropper99** [home-assistant/frontend#21937]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If I open tp-link in the Settings, Devices, it just lists the devices. There is not a way to configure or do anything with the main integration. You only see the Integration Entries list.

### Describe the behavior you expected

To see the main tp-link configuration button.

### Steps to reproduce the issue

1. Go to Settings
2. Devices & services
3. Select TP-Link Smart Home
...

### What version of Home Assistant Core has the issue?

2024.9.1

### What was the last working version of Home Assistant Core?

Unsure

### In which browser are you experiencing the issue with?

Chrome Version 128.0.6613.120 (Official Build) (64-bit), Microsoft Edge Version 129.0.2792.21 (Official build) stable app, beta channel (64-bit)

### Which operating system are you using to run this browser?

Windows 11 - 27686.1000

**Comment by karwosts** [comment]
Pretty sure this is how it's indended to be. I don't think there are any such options for the "main integration". Any options would be per-integration entity. 

What specifically do you feel like is missing?

**Comment by karwosts** [comment]
If TPLink had an options flow I guess it would be there, but I don't think it does. 

If you think some option is missing probably want to report a core issue for tplink integration. Frontend doesn't have any code specific to tplink. If something is missing that tplink author thinks should be there, they can let us know, but for now I don't think there's anything generically broken in frontend. 

Whatever options do or don't exist is dictated by the core integration code itself, frontend doesn't control that.

**Comment by dropper99** [comment]
Apologies, this was put in the wrong bucket, then.

    On Monday, September 9, 2024 at 04:33:16 PM CDT, karwosts ***@***.***> wrote:  
 
 


If TPLink had an options flow I guess it would be there, but I don't think it does.

If you think some option is missing probably want to report a core issue for tplink integration. Frontend doesn't have any code specific to tplink. If something is missing that tplink author thinks should be there, they can let us know, but for now I don't think there's anything generically broken in frontend.

Whatever options do or don't exist is dictated by the core integration code itself, frontend doesn't control that.

**Comment by karwosts** [comment]
I will close for now, but feel free to come back if you discover there is an error.
