### ISSUE TITLE
Red exclamation mark icon when a custom integration helper is created in helpers overview

### ISSUE THREAD

**Issue by kgn3400** [home-assistant/frontend#21931]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Red exclamation mark icon when a custom integration helper is created in helpers overview.

Below are a example of creating a [Spook inverse custom integration helper](https://github.com/frenck/spook/tree/main/custom_components/spook/integrations/spook_inverse):

<img width="411" alt="SCR-20240909-jqdm" src="https://github.com/user-attachments/assets/17aa65b6-7635-40dc-ad05-98be85fce61d">

<img width="1370" alt="SCR-20240909-jspg" src="https://github.com/user-attachments/assets/2cbba072-d090-4f9e-8dbe-e9f36c554579">

Clicking on the red exclamation mark icon opens the options dialog flow. Making changes or just click the send button doesn't change anything, the helper is still marked with a red exclamation mark icon. 

Refreshing the page removes the red exclamation mark icon and marks the helper as working correctly :

<img width="1186" alt="SCR-20240909-kibs" src="https://github.com/user-attachments/assets/6344dbda-f079-48e7-a866-f9e74507052e">

It seems to be a problem only for custom integration helpers.

### Describe the behavior you expected

No red exclamation mark icon when creating a custom integration helper.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2024.9.1

### What was the last working version of Home Assistant Core?

core-2024.8.3

**Comment by karwosts** [comment]
I see this sometimes for core integrations as well, like riemann sum. This indicates there is a config entry for a helper, but the entity does not exist (yet?).

**Comment by kgn3400** [comment]
You are right. I just tried it for the core Integral helper and it had the same problem. I have also tested Number, Counter and Text which do not have this problem.

I am very sure that this problem was not there for the custom helpers I use in version 2024.8.3...

But if it is as you described the problem, then should the frontend automatically update the status when the integration helper is fully in place/loaded. And not that you have to carry out a refresh yourself?.

**Comment by kgn3400** [comment]
I just tested on a version 2024.7.2 and here Integral, Spook invert and [Attribute as sensor](https://github.com/gjohansson-ST/attribute_as_sensor) worked without problems. No red exclamation mark when there were created.

**Comment by crhass** [comment]
I spotted this issue today when I created a generic hygrostat using the built in helpers, it has the red exclamation mark and if you try to assign a category it says it does not have a unique id. 

Version 2024.9.2
