### ISSUE TITLE
"Add New badge" tooltip in French

### ISSUE THREAD

**Issue by weaselchops** [home-assistant/frontend#21936]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When editing a dashboard, hovering over the add new badge "+" symbol shows:
**"Ajouter un badge"**
My Language is set English(GB)

![image](https://github.com/user-attachments/assets/ac0d5259-d0ac-439d-8154-a964c85cedd6)

### Describe the behavior you expected

The English version "Add a badge" to be displayed

### Steps to reproduce the issue

1.  Edit a dashboard, hovering over the add new badge option "+"

### What version of Home Assistant Core has the issue?

core-2024.9.1

### In which browser are you experiencing the issue with?

Microsoft Edge Version 128.0.2739.67 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

**Comment by Impact123** [comment]
Still happens with `2024.9.3`.
