### ISSUE TITLE
plural and singular are swapped for condition matching display

### ISSUE THREAD

**Issue by unclehack** [home-assistant/frontend#21930]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

"Test if 3 condition matches" is displayed when 3 conditions are used for an automation. This is incorrect in proper English. It should read "Test if 3 conditions match".

The following patch fixes the issue:
```
diff --git a/src/translations/en.json b/src/translations/en.json
index df4945647..84a60453f 100644
--- a/src/translations/en.json
+++ b/src/translations/en.json
@@ -3115,7 +3115,7 @@
                   "description": {
                     "picker": "Test if multiple conditions are true.",
                     "no_conditions": "Test if multiple conditions match",
-                    "full": "Test if {count} {count, plural,\n one {condition match}\n other {conditions matches}\n}"
+                    "full": "Test if {count} {count, plural,\n one {condition matches}\n other {conditions match}\n}"
                   }
                 },
                 "device": {
```

### Describe the behavior you expected

It should've been "Test if 3 conditions match".

### Steps to reproduce the issue

1. Create an automation
2. Add more than one condition
3. See that it says "Test if N condition matches"
...

### What version of Home Assistant Core has the issue?

2024.9.1

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

any

**Comment by silamon** [comment]
Feel free to make a pull request with your patch for this issue.
