### ISSUE TITLE
Webkit errors in sections

### ISSUE THREAD

**Issue by fredR142** [home-assistant/frontend#21944]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I set up a sections dashboard initially to control my media devices, mainly hifi , streamer etc. all was working fine until 2024.9 when using the dashboard on an older ipad running os 15.2 i started getting webkit errors. this occurred when trying to turn on a switch ,  the error showed a script error, which I could not fix, even by trying a switch I have been using for a couple of years successfully and still use daily on a non section dashboard. It seems that the error only occurs when using sections on an older OS version as my other Ipad on OS 17.2 doesn't get this error. I am about to create my media control card without sections but it would be a shame if I have to abandon sections completely. Is there a known fix for this?

### Describe the behavior you expected

I expect sections to work with older devices as well as newer ones !

### Steps to reproduce the issue

1.Use ipad os15.2
2.setup switch button card in sections
3.
...

### What version of Home Assistant Core has the issue?

2024.9.1

### What was the last working version of Home Assistant Core?

2024.8.5

### In which browser are you experiencing the issue with?

Safari

### Which operating system are you using to run this browser?

Ipad os 15.2

### Additional information

all relevant information is in the description

**Comment by szimszon** [comment]
Maybe related: https://github.com/home-assistant/frontend/issues/21945
