### ISSUE TITLE
Cannot load views with type "section" via handy

### ISSUE THREAD

**Issue by jahnenf** [home-assistant/frontend#21945]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I try to open a view that was configured with "section" home assistant is not able to load the page. Neither with the companion app nor with a browser. However this issue only appears with a mobile phone.

### Describe the behavior you expected

All pages should open properly.

### Steps to reproduce the issue

1. Each time I try to open a page with section view.
2. Even after restart with and without safe mode
3.
4.
...

### What version of Home Assistant Core has the issue?

2024.9.1

### In which browser are you experiencing the issue with?

Safari 16.7.10

### Which operating system are you using to run this browser?

iOS 16.7.10

**Comment by szimszon** [comment]
I have the same issue with my tablet.

**Comment by jahnenf** [comment]
Problem was solved with last update to 2024.9.2. Thanks
