### ISSUE TITLE
HA getting very slow reaction using iOS Safari.

### ISSUE THREAD

**Issue by Fatalmose** [home-assistant/frontend#21953]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I log into my HA using iOS Safari the hole thing gets very slow when programming into my dashboards.
I sometimes have a reaction time from 2 to 3 seconds before a typed letter or number becomes visible.
In selection windows I have to click for about 3 seconds before HA accept the change I want to make.
Also my iPhone gets warm by doing so.
My iPhone gets even hot when I do the same using the iOS HA application.
 I have the same effects using the HA application on my iMac Apple M1 OS Sonoma 14.6.1

### Describe the behavior you expected

Smooth reaction when programming things using the iPhone either with the HA iOS application or iOS Safari login.
Now it's working in slow-motion.

### Steps to reproduce the issue

1. log into HA using HA IOS Safari or HA IOS application.
2. Open up a dashboard and try to make some changes like copying a dashboard and changing the selected items
3. The same when doing so on my iMac Apple M1
4.
...

### What version of Home Assistant Core has the issue?

2024.9.1

### In which browser are you experiencing the issue with?

Safari iOS

### Which operating system are you using to run this browser?

iOS 17.6.1 and MAC OS Sonoma 14.6.1

**Comment by Fatalmose** [comment]
It’s a bit more reactive…
Is it possible that the system is slowing down while using more memory…?
I have the HA Green box.
Using 2 Gb of memory at the moment…

**Comment by wendevlin** [comment]
@Fatalmose 
Mhh 2gb of 4gb seems fine.

Does it work fine on your mac in Firefox or Chrome?
Can you maybe provide a video on how it behaves?

**Comment by Fatalmose** [comment]
I use the application HA on my Mac.

The HA application on Mac is very slow…
If you want to make an automatisation and need to type a sentence it takes
seconds before appearing.
The application on iPhone works better but stays slow to me regarding
reaction time and response.

Never really used the web version until now.

**Comment by wendevlin** [comment]
> Never really used the web version until now.

Okay, so please then try the web version. Because if it is fine there it is not frontend related, it would be then iOS/MacOS related which is handled in this repo: https://github.com/home-assistant/ios

**Comment by Fatalmose** [comment]
And yes…
It works really smooth using the web version.
How comme…?

**Comment by wendevlin** [comment]
:shrug: Strange I cannot reproduce it.

Checkout this issue in the iOS repo: https://github.com/home-assistant/iOS/issues/2066

I hope you find a solution there.
