### ISSUE TITLE
Duration-class badges do not respect unit of measurement 

### ISSUE THREAD

**Issue by mateuszdrab** [home-assistant/frontend#21967]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In 2024.8, a badge for a sensor with the configuration below displays '103 minutes'
![image](https://github.com/user-attachments/assets/5bb4c4c4-c3f5-4065-bfb2-4356f802aa02)

Changing unit of measurement from min to millisecond reflects immediately on the card.

### Describe the behavior you expected

In 2024.9, the preference for unit of measurement is ignored and the value displayed is '1:43:0'
Changing unit of measurement from min to millisecond does not reflect on the card.

### Steps to reproduce the issue

Downgrade to 2024.8.

### What version of Home Assistant Core has the issue?

core-2024.9.0

### What was the last working version of Home Assistant Core?

core-2024.8.3

### In which browser are you experiencing the issue with?

Edge

### Which operating system are you using to run this browser?

Mac OS/Windows/Android

**Comment by karwosts** [comment]
This is a side effect of removing https://github.com/home-assistant/frontend/pull/21755

We don't have a good solution for customizing duration formatting at this time.

**Comment by mateuszdrab** [comment]
Thanks for clarifying.

It's strange because the actual state of the entity shows as minutes, I'd hope it would just show that.

Is the output of the states in Dev Tools is already formatted?

**Comment by karwosts** [comment]
Developer-tools/states is always the raw state from the backend, that will be a number like `0.111`.

In frontend `device_class: duration` sensors are in many places then reformatted as human readable HH:MM:SS format. It is the latter that generally there is no specific control for, and display_precision does not affect this.

**Comment by timdream** [comment]
This regression has caused Ping integration entities to display ping round trip time in seconds even though "unit of measurements" is set to "ms".

**Comment by N3rdix** [comment]
Just observed the same and makes some entities more or less unusable when using "d" as unit of measurement...  Interesting enough that the configuration dialog respects the unit of measurement correctly (in my example `99`).
Hopefully there can be a fix.

![image](https://github.com/user-attachments/assets/104424dd-d201-4000-8678-0a2238bc97b7)

**Comment by mateuszdrab** [comment]
> Just observed the same and makes some entities more or less unusable when using "d" as unit of measurement...  Interesting enough that the configuration dialog respects the unit of measurement correctly (in my example `99`).
> Hopefully there can be a fix.
> 
> ![image](https://github.com/user-attachments/assets/104424dd-d201-4000-8678-0a2238bc97b7)

Agreed, it's a strange experience since the units are now inconsistent in various locations.
