### ISSUE TITLE
Back button doesn't work in browsers/companion apps after vewing a more info panel

### ISSUE THREAD

**Issue by tetele** [home-assistant/frontend#21976]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The back button (be it on Android or in a browser such as Chrome on Windows) doesn't take you to the previous view/page on the first press if a more info panel was opened in the current view/page and then closed. The more more info panels you've opened, the more times you have to press "back" for it to work.

### Describe the behavior you expected

One of the following 2 is acceptable:
1. (more desirable) pressing the back button in a view will take you to the previous view regardless of whether a more-info panel has been opened and closed.
2. (less desirable) pressing the back button in a view after having opened and closed a more-info panel should bring back the more-info panel which was recently closed in that view.

### Steps to reproduce the issue

1. Navigate to Settings > Devices & Services > Devices (tab)
2. Select a device from the list, making sure it has some entities associated
3. In the device page, click one of the associated entities
4. Close the entity more info panel using the X button
5. Press back (browser button or Android OS button)
6. Press back again

Expectation: I get to the Devices tab on the first press
Actual result: I get to the Devices tab on the second press

### What version of Home Assistant Core has the issue?

2024.9.1

### In which browser are you experiencing the issue with?

multiple, including companion app

### Which operating system are you using to run this browser?

multiple

**Comment by ildar170975** [comment]
Duplicate
https://github.com/home-assistant/frontend/issues/17820
