### ISSUE TITLE
Times on entities and tile card displayed incorrect

### ISSUE THREAD

**Issue by dhoeben** [home-assistant/frontend#21984]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

-- This is a duplicate from: https://github.com/home-assistant/core/issues/125830#issue-2522488723, which is been moved to here.

When using time entity (e.g. Waze) in a Tile card or entities card, it shows the time with seconds. This results in times shown with :00 at the end as this is always zero. See screenshot. Also in entity config, rounding is set to display without value behind comma (30 iso 30,x). Unit is also not showing.

![Screenshot_20240912-155340](https://github.com/user-attachments/assets/06681819-7e19-4357-9d9a-6eb5c33dd042)

### Describe the behavior you expected

To display correct time in minutes or hours without seconds and with units.

### Steps to reproduce the issue

Create a tile card
Use entity which shows time (e.g. Waze)
Experience behaviour

### What version of Home Assistant Core has the issue?

core-2024.9.1

### What was the last working version of Home Assistant Core?

core_2024.8.x

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

iOS, ChromeOS, macOS, Windows, Linux, Android

**Comment by karwosts** [comment]
This is how frontend formats all entities with `device_class: duration`. It would be nice to find some way to control this behavior, but I haven't figured out a good solution. The recent change you notice is due to https://github.com/home-assistant/frontend/pull/21755

**Comment by dhoeben** [comment]
> This is how frontend formats all entities with `device_class: duration`. It would be nice to find some way to control this behavior, but I haven't figured out a good solution. The recent change you notice is due to https://github.com/home-assistant/frontend/pull/21755

Maybe when using sensors with 'device_class: duration', i.s.o. showing the decimal rounding, show different time formats which can be used to display? I'd love to help of you point me to the right file!

**Comment by karwosts** [comment]
I've thought about that some times, but it has some complications. 

- Suggested display precision is an integer value from 0 to 10, and in the backend integrations already set a suggested_display_precision for these entities, so we would have to map this decimal to arbitrary formats which would be difficult to communicate with backend. 

- A few places in frontend still don't use the duration formatting and just show the raw state value (like I think Entity card and maybe when plotting on a graph), but those do still use the display_precision, so you'll have to pick a single value for display precision which is both a number of decimals in some places and an arbitrary format in another. 

- If someone doesn't want to use hhmmss formatting, then they won't be able to set the display_precision of the resulting decimal, because we've overloaded that field for something else. So how do we choose how many digits to display on this value? Unless we save like half the entries for duration formatting and the other half for decimals? Maybe could work.

And then on top of all that, I don't know if it would be approved to overload this field in such a way.

**Comment by dhoeben** [comment]
> I've thought about that some times, but it has some complications. 
> 
> - Suggested display precision is an integer value from 0 to 10, and in the backend integrations already set a suggested_display_precision for these entities, so we would have to map this integer to arbitrary formats which would be difficult to communicate with backend. 
> 
> - A few places in frontend still don't use the duration formatting and just show the raw state value (like I think Entity card and maybe when plotting on a graph), but those do still use the display_precision, so you'll have to pick a single value for display precision which is both a number of decimals in some places and an arbitrary format in another. 
> 
> - If someone doesn't want to use hhmmss formatting, then they won't be able to set the display_precision of the resulting decimal, because we've overloaded that field for something else. So how do we choose how many digits to display on this value? Unless we save like half the entries for duration formatting and the other half for decimals? Maybe could work.
> 
> And then on top of all that, I don't know if it would be approved to overload this field in such a way. 

Thanks for the reply. I understand the difficulties now.

I'll look into your second bullit, for streamlining this should be fixed anyway.

For the last bullit, I was thinking more like an input field, which follows Pythons standard time formatting (or Jinja2) with a default value of hh:mm:ss. This way, it is probably easier for backend to handle, as they can just translate it back to miliseconds (I believe they use) and not a lot of `if` and `else`'s.

**Comment by karwosts** [comment]
> For the last bullit, I was thinking more like an input field, which follows Pythons standard time formatting (or Jinja2) with a default value of hh:mm:ss. This way, it is probably easier for backend to handle, as they can just translate it back to miliseconds (I believe they use) and not a lot of if and else's.

If it's in the UI it's got to be pretty simple and broadly understood, not just by programmers. If you're asking users to understand and input strftime codes I don't think that will fly... we don't have anything like that anywhere else in the UI, just simple option selection dropdowns.

**Comment by dhoeben** [comment]
Oke, did not think about that. It feels like we would not reach the 10 options the dropdown menu has now, if we would create a dropdown.

I'm thinking of these options:
- hh:mm:ss
- hh:mm
- mm:ss
- mm
- ss:ms
- ms
it's got to be that, or we would have to work with checkboxes. e.g.:
[]show hours, []show minutes, []show seconds []show miliseconds.

I'm not sure which one is more foolproof/easier. A dropdown could be converted back to ms in frontend to send to backend.

**Comment by karwosts** [comment]
If you make checkboxes that will require updates in the entity registry in core, so consider that's a lot more work.

Also there are days to consider, some sensors have units in days and users complain when it was converted to hhmmss.

**Comment by karwosts** [comment]
If you're interested in changing what goes in the entity registry, you may want to start a discussion in home-assistant/architecture repo. I can't answer what would or wouldn't be accepted.

**Comment by dhoeben** [comment]
Maybe, even better. See: https://www.home-assistant.io/dashboards/entities/#format

If we add an option to the e.g. the tile card, that when sensor has `device_class: duration`, the format option is used. Just like the entities card. However,  with an addition that it supports a (yaml) custom strftime.

**Comment by parautenbach** [comment]
To add on, and unfortunately I don't have a proposal for how to handle this, I want to show that these ping sensor attributes that are now sensors aren't being displayed correctly in an entities card or on the device's own page. No unit, and there seems to be an implicit conversion factor. 

<img width="250" alt="Screenshot 2024-10-08 at 22 37 51" src="https://github.com/user-attachments/assets/7b1b8768-a4f0-444e-8fbb-b36847f3187e">

<img width="295" alt="Screenshot 2024-10-08 at 22 40 16" src="https://github.com/user-attachments/assets/02ce3cbc-28d4-41f0-a811-0f9531452455">

<img width="165" alt="Screenshot 2024-10-08 at 22 46 16" src="https://github.com/user-attachments/assets/8f606c19-3b32-44fa-909a-0112914995ad">

**Comment by dhoeben** [comment]
What worked for me as a workaround is using customize.yaml. There I changed the device class of the sensor to display as a number iso a time.
