### ISSUE TITLE
Sunrise time differences between "sensor.sun_next_dawn" and "Sun"

### ISSUE THREAD

**Issue by iz8mbw** [home-assistant/frontend#22004]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Different Sunrise time between "sensor.sun_next_dawn" and "Sun"

### Describe the behavior you expected

Have the same and correct Sunrise time

### Steps to reproduce the issue

1. Add into the dashbotd the Sun
2. Add into the dashbotd the sensor.sun_next_dawn
3.. Check the Sunrise time of the two entities

### What version of Home Assistant Core has the issue?

2024.9.2

### What was the last working version of Home Assistant Core?

No one

### In which browser are you experiencing the issue with?

Google Chrome 128

### Which operating system are you using to run this browser?

Windows 10

### Additional information

Hello.
I use both "sensor.sun_next_dawn" and "Sun"

See here:
![image](https://github.com/user-attachments/assets/f10fab51-cf30-4e69-8306-fa92c12106e1)

I noticed the Sunrise time is diffrent between "sensor.sun_next_dawn" and "Sun".

For example on my side:

Sunrise time for "sensor.sun_next_dawn" is at 06:18
![image](https://github.com/user-attachments/assets/0d482697-1242-4a3c-bc48-fc45c72cb334)

Sunrise time for "Sun" is at 06:45
![image](https://github.com/user-attachments/assets/e20b7ac4-00a2-4a31-b0fd-11cf395b4370)

According to the "real" Sunrise time for my location, the correct one is the time provided by "Sun" (so the wrong one is the time provided by "sensor.sun_next_dawn").

Please can you check and fix it?

Thanks.

**Comment by karwosts** [comment]
Dawn is not the same thing as sunrise, they measure different things. Sunrise is at 0 degrees on the horizon and I believe dawn is -6 degrees of the horizon.

You should have a different sensor `sensor.sun_next_rising` that matches the sun attribute for next rising.


And regardless, this is not a frontend issue, this would be an issue for sun integration in core. But it looks correct to me.
