### ISSUE TITLE
Safari spinners and websocket connections erroring out

### ISSUE THREAD

**Issue by holman** [home-assistant/frontend#22000]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Safari is unable to load `Devices & Services` as well as generally causing slow performance and spinners in HA.

### Describe the behavior you expected

For the last few weeks I've had issues with Safari — waited until 2023.9.2 and 20240909.1 to make sure it wasn't a recent tweak that was responsible. Primarily I have the most obvious problems with the `Devices & Services` tab, which no longer loads at all in Safari- just spins. Browser inspector potentially points towards errors in the websocket connection, but also has a number of general errors on a load as well. This is all in Safe Mode:

<img width="1349" alt="Screenshot 2024-09-16 at 1 28 47 PM" src="https://github.com/user-attachments/assets/7766db0a-057f-48d2-9f4f-d839d7ad7ae4">

### Steps to reproduce the issue

1. Boot into Safe Mode
2. Navigate towards `Devices & Services`
3. Spinner spins

### What version of Home Assistant Core has the issue?

2024.9.2

### What was the last working version of Home Assistant Core?

2024.8

### In which browser are you experiencing the issue with?

Safari 18.1 (20619.2.1)

### Which operating system are you using to run this browser?

macOS Sequoia (15.1)

### Javascript errors shown in your browser console/inspector

```txt
[Log] Websocket died, forcing reconnect... (app.HPzj1J8TwAk.js, line 2)
[Error] Unhandled Promise Rejection: [object Object]
	(anonymous function) (25473.JsPFMv_yptk.js:1:28148)
[Error] Unhandled Promise Rejection: [object Object]
	(anonymous function) (29669.YnIevaz7zWQ.js:2:17239)
[Error] Unhandled Promise Rejection: [object Object]
	(anonymous function) (29669.YnIevaz7zWQ.js:2:16785)
[Error] Unhandled Promise Rejection: [object Object]
	(anonymous function) (29669.YnIevaz7zWQ.js:2:17239)
[Error] Unhandled Promise Rejection: [object Object]
	(anonymous function) (29669.YnIevaz7zWQ.js:2:16785)
[Error] Unhandled Promise Rejection: [object Object]
	(anonymous function) (app.HPzj1J8TwAk.js:2:232670)
[Error] Unhandled Promise Rejection: [object Object]
	(anonymous function) (29669.YnIevaz7zWQ.js:2:16487)
[Error] Unhandled Promise Rejection: [object Object]
	(anonymous function) (29669.YnIevaz7zWQ.js:2:17040)
[Error] Unhandled Promise Rejection: [object Object]
	(anonymous function) (29669.YnIevaz7zWQ.js:2:16487)
[Error] Unhandled Promise Rejection: [object Object]
	(anonymous function) (29669.YnIevaz7zWQ.js:2:17040)
[Error] Unhandled Promise Rejection: [object Object]
	(anonymous function) (13255.4EVdx_9MOD4.js:1:27023)
```

**Comment by holman** [comment]
For what it's worth, I just nervously upgraded a second Home Assistant instance and... no issues. Which is really strange. They're both hosted approximately the same way, and I'd imagine Safe Boot would neuter any integration differences between the two. Any thoughts on digging into what might be different between the two instances to help diagnose what's happening in the broken one?

**Comment by silamon** [comment]
You'll need to check the logs if there's anything in there. There was a similar issue a while ago, I need to dig it up, probably you're having that on your instance.

**Comment by holman** [comment]
Absolutely could not figure this one out, but eventually looked up and noticed my Unifi integration had generated 800,000 entities. Eight hundred thousand. Yeah, I could see how that impacted the general stability of the system.

The logs had some additional hints where the websocket was delivering too many events to the client and in Safari it seems it just gives up earlier, which then nuked the interface. Crazy stuff. Working well again now, though.
