### ISSUE TITLE
ZHA send command via automation UX: fields in integers for hex values

### ISSUE THREAD

**Issue by neutrinus** [home-assistant/frontend#22035]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The "Manage Zigbee Device" provides numerical values like Endpoint ID: 0x0004 or AtributeId: 0x0013. That seems like a hex value to me. 
![image](https://github.com/user-attachments/assets/5e41a548-82e9-4a4f-a17a-45b789c19a61)

The Automation Creator provides ability to send custom commands via Zigbee cluster. 
![image](https://github.com/user-attachments/assets/e4d28064-1b27-416a-b13d-8a7fd061c98f)
There the ClusterID and AtributeID (commandId too?) have numerical input with sliders -> which looks like Base10 integer to me. 

### Describe the behavior you expected

That seems like poor ux for me :)

I would prefer to have it in the same base, either dec or hex. The sliders look kinda funny - I do believe such configuration is not done by sliding things.

### Steps to reproduce the issue

1. Configuration>Integrations>Zigbee>Device>Manage Zigbee Device
2 .Configurarion>Automations>Edit and try to add a Zigbee Command to Cluster

The values are in different format!

(sorry, I'm using Polish version and did the translation to English by myself)

### What version of Home Assistant Core has the issue?

2024.9.2

### What was the last working version of Home Assistant Core?

2024.9.2

### In which browser are you experiencing the issue with?

chrome, firefox, android browser

### Which operating system are you using to run this browser?

Fedora  40

**Comment by karwosts** [comment]
The fields and formats of the data for ZHA service calls is not controlled by the frontend, but by the ZHA integration in core. So this would need to be a home-assistant/core issue. 

The sliders could be removed by setting the number selector to box mode. 
https://www.home-assistant.io/docs/blueprint/selectors/#number-selector

**Comment by neutrinus** [comment]
thanks @karwosts, should I create another issue for  home-assistant/core issue or this one can be relocated?

**Comment by karwosts** [comment]
Probably just open new issue. A mod could move it but I don't have write permission there.
