### ISSUE TITLE
User agreement must be accepted again

### ISSUE THREAD

**Issue by eins2** [home-assistant/frontend#22036]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

System details:
- Core 2024.9.2
- Supervisor 2024.09.1
- Operating System 13.1
- Frontend 20240909.1

When trying to setup Roborock integration, entering the email and Verification code, the setup wizard throws an error: "There was an unknown roborock exception - please check your logs.". The logs give the following detailed info:

```
Logger: homeassistant.components.roborock.config_flow
Source: components/roborock/config_flow.py:109
integration: Roborock (documentation, issues)
First occurred: 20:15:56 (1 occurrences)
Last logged: 20:15:56

Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/roborock/config_flow.py", line 109, in async_step_code
    login_data = await self._client.code_login(code)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/roborock/web_api.py", line 172, in code_login
    raise RoborockInvalidUserAgreement(
roborock.exceptions.RoborockInvalidUserAgreement: User agreement must be accepted again - or you are attempting to use the Mi Home app account.
```

The system is a fresh install with only a couple of integrations configured.

### Describe the behavior you expected

I did expect a successful setup of the Roborock integration

### Steps to reproduce the issue

Described above

### What version of Home Assistant Core has the issue?

2024.9.2

### In which browser are you experiencing the issue with?

Safari 18.0, Chrome 129.0.6668.59

### Which operating system are you using to run this browser?

macOS 15.0

**Comment by silamon** [comment]
Open an issue at https://github.com/home-assistant/core against the roborock integration
