### ISSUE TITLE
Changing temperature by pressing plus/minus leads to wrong value being set 

### ISSUE THREAD

**Issue by ibezkrovnyi** [home-assistant/frontend#22048]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When the current temperature is 25.1 degrees (celcius), pressing `+` button on Thermostat card to increase temperature by 0.1 leads to temperature 25.200000000000003 being sent to device, then (what is worse) either ZWaveJS or ZWaveJS UI or device itself resets value to 25.0 (not to 25.1 and not to 25.2)

```
2024-09-21 22:33:47.669 DEBUG (MainThread) [zwave_js_server] Publishing message:
{'command': 'node.set_value',
 'messageId': '7ef4b533a709432aaf8ceab816763803',
 'nodeId': 65,
 'value': 25.200000000000003,
 'valueId': {'commandClass': 67,
             'endpoint': 0,
             'property': 'setpoint',
             'propertyKey': 1}}

2024-09-21 22:33:47.701 DEBUG (MainThread) [zwave_js_server.server] 2024-09-21T20:33:47.692Z:
2024-09-21T20:33:47.692Z DRIVER » [Node 065] [REQ] [SendDataBridge]
                                  │ source node id:   1
                                  │ transmit options: 0x25
                                  │ callback id:      51
                                  └─[Security2CCMessageEncapsulation]
                                    │ sequence number: 2
                                    │ security class:  S2_Authenticated
                                    └─[SupervisionCCGet]
                                      │ session id:      20
                                      │ request updates: true
                                      └─[ThermostatSetpointCCSet]
                                          setpoint type: Heating
                                          value:         25.200000000000003 °C
``` 

### Describe the behavior you expected

Pressing + or - on the thermostat card should round values to the precision of the step increment, or use a method that avoids floating-point inaccuracies (such as the well-known IEEE 754 precision issue).

### Steps to reproduce the issue
- Ensure the thermostat device has a increment/decrement step of 0.1°C.
- Press the + or - button on the thermostat card.
- Observe the values sent to the ZWaveJS server and how they are reset.

This issue doesn't occur when adjusting the temperature via the circular slider.

![image](https://github.com/user-attachments/assets/48545827-d800-4d2f-b620-4e16f6ea113d)

### What version of Home Assistant Core has the issue?

2024.9.2

### In which browser are you experiencing the issue with?

Edge 128.0.2739.79

### Which operating system are you using to run this browser?

Windows 11

### Additional information

Issue https://github.com/home-assistant/frontend/issues/1798 is related to wrong value being displayed. Not sure though if it was only fixed for displayed value, or for the value that is being sent to device too.

**Comment by GauravSahu891** [comment]
Hey there,

I’d like to take on this issue. Please assign it to me.

Additionally, I’d like to loop in @ADVi3pp and @ibezkrovnyi for their insights.

Thanks!

Feel free to modify it as needed!
