### ISSUE TITLE
Apple Watch buttons missing text 

### ISSUE THREAD

**Issue by jackyoung1** [home-assistant/frontend#22065]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Text buttons on Apple Watch for actions are all white, no readable text, using companion version 2024.9.1 (2024)
![IMG_0879](https://github.com/user-attachments/assets/ed9c54b8-1ac6-467a-af0c-80f0a2c904e7)

### Describe the behavior you expected

Should show labels on buttons (they are visible in the config screen on the app)
![IMG_0880](https://github.com/user-attachments/assets/5c6acbfd-1031-4c08-99a3-9ef8b7eb84cc)

### Steps to reproduce the issue

1.press the home assistant actions shortcut on Apple watch
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.9.2

### In which browser are you experiencing the issue with?

Apple watch

### Which operating system are you using to run this browser?

WatchOS10.6.1

**Comment by boom235** [comment]
I have the same problem, looking forward for a solution. I have tried everything in the past days… upgrading reconfiguration and restarting

**Comment by wendevlin** [comment]
Hello,
@jackyoung1, @boom235 

This is an specific iOS issue and we cannot fix it in the frontend.

Please recreate your issue here: https://github.com/home-assistant/iOS/issues

**Comment by boom235** [comment]
> Hello, @jackyoung1, @boom235
> 
> This is an specific iOS issue and we cannot fix it in the frontend.
> 
> Please recreate your issue here: https://github.com/home-assistant/iOS/issues

But wait @wendevlin who can fix it then? Somebody must have developed the iOS Frontend for the Apple Watch Home Assistant App and implemented this bug recently. This used to work one week ago.

**Comment by wendevlin** [comment]
@boom235 there is already an issue about this created: https://github.com/home-assistant/iOS/issues/3035

**Comment by boom235** [comment]
Thank you very much! Yes I also just found that. Great support!
