### ISSUE TITLE
The Tuya authentication period has expired

### ISSUE THREAD

**Issue by Vladimir-huligan** [home-assistant/frontend#22116]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have this problem almost every day. I asked other users for the same problem. Please decide

### Describe the behavior you expected

there was no such mistake before

### Steps to reproduce the issue

1.The problem appears itself with the integration of Tuya
![IMG_20240920_102329_273](https://github.com/user-attachments/assets/0b7ff13e-84dd-4f2c-89e8-45cfad90e6ab)

2.
3.
...

### What version of Home Assistant Core has the issue?

2024.9.3

**Comment by karwosts** [comment]
Please file in home-assistant/core, this is not a frontend issue.
