### ISSUE TITLE
Add "sunroof"on Volvooncall integration

### ISSUE THREAD

**Issue by crocobau** [home-assistant/frontend#22158]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

There is one missing sensor from the "volvooncall"integration.
On Volvo Developer site this entity is called "sunroof"

### Describe the behavior you expected

This "sunroof" should appear as entity (binary sensor)

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core/volvooncall

### In which browser are you experiencing the issue with?

Not related

### Which operating system are you using to run this browser?

Not related

### Additional information

Volvo specs are in here:
https://developer.volvocars.com/apis/connected-vehicle/v2/endpoints/doors-windows-locks/#get-window-status

Missing element:

sunroof.timestamp
(Timestamp in ISO-8601 format when the status value has been last retrieved from the vehicle.)

sunroof.value
(If available. Possible values: UNSPECIFIED, OPEN, CLOSED, AJAR.)

**Comment by silamon** [comment]
Open an issue at https://github.com/home-assistant/core. This is for frontend specific bug reports.
