### ISSUE TITLE
2024.10.0b4 - Heading card font size smaller than existing titles

### ISSUE THREAD

**Issue by woodmj74** [home-assistant/frontend#22153]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In the current beta the font size of the new header card is smaller than the previous title on sections which will be migrated into these. 

This may be deliberately done but feels a bit out of place, it appears to be smaller in size and heavier in font weight. 

![image](https://github.com/user-attachments/assets/99ce4ea1-8889-4be9-b4d2-cda270ff4b15)
![image](https://github.com/user-attachments/assets/528a8b72-98a5-459b-b4a9-7ac2fd44ba79)

### Describe the behavior you expected

I would expect the header card to replicate the style of the current Titles on sections (albeit without the icon and entities that the header card introduces).

This could be addressed by #22129 but not sure.

### Steps to reproduce the issue

1. Create new dashboard
2. set to sections
3. add header card 
4. compare to previous version with title on sections card

### What version of Home Assistant Core has the issue?

2024.10.0b4

### What was the last working version of Home Assistant Core?

n/a

### In which browser are you experiencing the issue with?

Microsoft Edge Version 129.0.2792.52 (Official build) (64-bit)

### Which operating system are you using to run this browser?

W11

**Comment by jhemak** [comment]
I agree, the Heading seems a bit small compared to the earlier section name and also Mushroom title card.

**Comment by piitaya** [comment]
Yeah you can change the font-size using theme variables. The default style change has been decided by the design team.

**Comment by woodmj74** [comment]
Closing as conscious design decision...

**Comment by woodmj74** [comment]
@piitaya I don't suppose you know the variable names for the header and sub-header? Had a quick look in the docs and can't see anything easily (but I'm probably looking in the wrong place!)

**Comment by piitaya** [comment]
Here's the variables (available in the PR you linked in the issue description https://github.com/home-assistant/frontend/pull/22129)

```
ha-heading-card-title-color
ha-heading-card-title-font-size
ha-heading-card-title-font-weight
ha-heading-card-title-line-height
ha-heading-card-subtitle-color
ha-heading-card-subtitle-font-size
ha-heading-card-subtitle-font-weight
ha-heading-card-subtitle-line-height
```

BTW, these variables are not officially supported because Home Assistant doesn't have a proper design system so it's hard to document and maintain all the variables. But that ones should not change in the future.

**Comment by jhemak** [comment]
I do not have any custom themes and have never overwritten a theme variable before.  I see lots online of how to create custom themes, etc.  But could anyone let me know what is the very minimum amount of changes one must make to continue using the default HA theme with auto light and dark mode changes and simply overwrite one of the variables that @piitaya mentioned above?

**Comment by michaelmarconi** [comment]
I appreciate that this was a conscious decision but for it’s worth, I think the headers look way to small compared to the rest of the items on my dashboard too. 

I feel compelled to override the style too. A guide would be much appreciated or perhaps you can point me in the right direction!

Otherwise, really enjoying the new sections layout!

**Comment by snarkDADMin** [comment]
Throwing in here as well to say that I understand that this was a conscious decision, but the inability to change the font size when the default is smaller than it should be compared to other headings and titles, is a misstep that should be corrected in the next release.

**Comment by freakyjoe8** [comment]
@woodmj74 I really like the HA design. It's modern and functional. But when I now started to use sections things are getting really hard to read with those new headings:

![image](https://github.com/user-attachments/assets/4a9b2e80-7a4a-462b-b3e1-6952eaf75a44)

it's very hard to distinguish the different rooms on the dashboard on first sight. On the mobile app it's even worse. Also the icons don't really help as they are very tiny too and have no colors. Not sure if this intended with a "heading". Personally I would assume a heading stands out and the current version feels more like a sub-header or even a sub-sub-header to me. Just my 2 cents.

**Comment by jhemak** [comment]
> I agree, the Heading seems a bit small compared to the earlier section name and also Mushroom title card.

I would actually like to retract my comment :-D  While my first impression was that they were way too small, the more I've been using them the more "right" they feel.  My old, larger headings now strike me as unnecessarily large.

So, good job design team!

**Comment by profucius** [comment]
I vote for making the text adjustable. Many other things in the HASS ecosystem are adjustable, it's arguably the ethos of HASS itself. Instead of making the Heading Title/Subtitle a fixed size, include a slider so the user can choose what _they_ are comfortable with in their own home design, rather than forcing them to be comfortable with what _you_ are comfortable with. Please and thank you.
