### ISSUE TITLE
shelly plus 1pm stopped working with HA

### ISSUE THREAD

**Issue by oshriphoto** [home-assistant/frontend#22186]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

shelly plus 1pm suddenly stopped working with HA
Apparently they were recently updated (they are in automatic update mode) and suddenly all shelly components plus 1pm stopped working, I have additional shelly components at home but they work fine and there are no problems.
![461947335_8143692805758427_7905709774428703971_n](https://github.com/user-attachments/assets/182e311b-68d1-495e-b2cf-362b4c4c5556)

### Describe the behavior you expected

shelly plus 1pm suddenly stopped working with HA
Apparently they were recently updated (they are in automatic update mode) and suddenly all shelly components plus 1pm stopped working, I have additional shelly components at home but they work fine and there are no problems.

### Steps to reproduce the issue

1. 
[home-assistant_shelly_2024-10-02T09-51-22.672Z.log](https://github.com/user-attachments/files/17227719/home-assistant_shelly_2024-10-02T09-51-22.672Z.log)
I uninstalled and installed the non-working components
2. I did a HA restart
3. I checked that the components are updated to the latest version
...

### What version of Home Assistant Core has the issue?

2024.5.5

### In which browser are you experiencing the issue with?

google crohme

### Which operating system are you using to run this browser?

google crohme

### Additional information

I have attached a log
[home-assistant_shelly_2024-10-02T09-51-22.672Z.log](https://github.com/user-attachments/files/17227735/home-assistant_shelly_2024-10-02T09-51-22.672Z.log)

**Comment by karwosts** [comment]
Please file in home-assistant/core, this is not a frontend issue.
