### ISSUE TITLE
Spacer mushroom chip doesn't work properly on sections dashboard

### ISSUE THREAD

**Issue by dnestico** [home-assistant/frontend#22203]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I am testing out the new sections dashboard and went to add custom mushroom chips, all work fine except if I add a "Spacer" chip it appears to show the spacer, the big problem is you can't actually edit or remove the spacer chip after adding them, here is a screenshot to show that the chip is there but can't be removed at all after adding it.

<img width="1200" alt="Screenshot 2024-10-02 at 4 45 29 PM" src="https://github.com/user-attachments/assets/941b44d1-4765-4347-8bda-857b22a85179">

### Describe the behavior you expected

The blank spacer mushroom chip should be able to be removed after being added via a custom chip in the sections dashboard.

### Steps to reproduce the issue

1. Add a new chip to sections dashboard chip header
2. Select manual under custom badges
3. Add the blew YAML code to add the "spacer" mushroom chip
...

```
type: custom:mushroom-chips-card
chips:
  - type: spacer
```

### What version of Home Assistant Core has the issue?

2024.10.0

### In which browser are you experiencing the issue with?

Arc Browser aka Chromium

### Which operating system are you using to run this browser?

macOS Sonoma 14.4.1

**Comment by piitaya** [comment]
Mushroom chips card is a card, not a badge so it's not really supported as badges. Also, it's a custom component and we don't support custom component issue in the front-end repository.
You can delete it by editing the yaml of the view.

**Comment by dnestico** [comment]
Thanks, I got them deleted by using YAML, I thought that was considered a badge tbh so I didn't know.
