### ISSUE TITLE
Password of AVM FRITZ!Box integrations cannot be updated

### ISSUE THREAD

**Issue by UrsulaHertzog** [home-assistant/frontend#22216]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The integrations "AVM FRITZ!Box Call Monitor" and "AVM FRITZ!Box Tools" require username and password to access the FRITZ!Box. After the password changed in the FRITZ!Box, it needs to be changed in Home Assistant, correspondingly. However, there is no option in the UI to change the username or password stored during the initial configuration.

### Describe the behavior you expected

I'd expect some way to update the username and/or password for accessing the FRITZ!box.

### Steps to reproduce the issue

1. Configure FRITZ!box user
2. Add the integrations "AVM FRITZ!Box Call Monitor" and "AVM FRITZ!Box Tools" -- their initial setup process asks for username and password.
3. Work with the integrations in Home Assistant.
4. Change the password in FRITZ!box
5. Try to update the password in Home Assistant via UI...

### What version of Home Assistant Core has the issue?

 Core 2024.10.0 Supervisor 2024.09.1 Operating System 13.1 Frontend 20241002.2

### In which browser are you experiencing the issue with?

Google Chrome Version 129.0.6668.72

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment]
This would have to be supported by the integration (not a frontend issue), so please report this in home-assistant/core for that integration.
