### ISSUE TITLE
Attribute condition missing from Dashboard visibility

### ISSUE THREAD

**Issue by Stutchbury** [home-assistant/frontend#22215]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The [Conditions documentation](https://www.home-assistant.io/docs/scripts/conditions/#numeric-state-condition) show 'attribute:' as a valid label for numeric state conditions but in Dashboard Cards and Badges, this label is ignored.

### Describe the behavior you expected

As per the Conditions documentation, when 'attribute:' is used in visibility conditions for Cards and Badges the specified attribute is used to compare Above/Below rather than the Entity value.

### Steps to reproduce the issue

1. Create a Badge in any Dashboard
2. Select the 'Visibility' tab
3. Add an 'Entity Numeric State' condition
4. Press 'SHOW CODE EDITOR'
5. Add 'attribute: <a valid numeric attribute for your entity> below the entity line
6. Save

### What version of Home Assistant Core has the issue?

2024.10.0

### In which browser are you experiencing the issue with?

Firefos 115.04

### Which operating system are you using to run this browser?

Debian 12

### Additional information

There is a brief discussion here: https://github.com/home-assistant/frontend/discussions/21550
bus as there is a mismatch between documentation and functionality, I thought it appropriate to raise an issue.

**Comment by Stutchbury** [comment]
Thank you for your reply and link to the 'alternative' conditions for Dashboards. Like most, I suspect people will search for 'Home Assistant conditions' and end up where I did.

I sincerely hope this is not intentional - an entity can currently have many attributes that would never normally be displayed but are essential for conditions. UI conditions are likely to be particularly reliant on non-visible attributes.

If the intention is to limit the use of attributes to values that are defined during configuration (such as UoM) and to move attributes that are set/changed at runtime to sensors, that would be logical but needs a roadmap - and the future usage of attributes communicated to developers.

**Comment by karwosts** [comment]
As this is not an issue but a feature request (and covered appropriately by https://github.com/home-assistant/frontend/discussions/21550), I will close this issue ticket.
