### ISSUE TITLE
smartthings integration

### ISSUE THREAD

**Issue by wvdb0** [home-assistant/frontend#22214]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

entities for washing machine no longer show up

### Describe the behavior you expected

energy monitoring and program selection. a month ago I could see this data. Since I installed the fridge this info is gone.

### Steps to reproduce the issue

1.look at entity for the washing machine 
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.10.0

### Which operating system are you using to run this browser?

raspberry pi ha 13.2.rc1

**Comment by karwosts** [comment]
Please file integration specific issues in home-assistant/core, this does not seem like a frontend issue.
