### ISSUE TITLE
Missing localization of "Login attempt failed" notification

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22262]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When the automatic re-connect of the browser fails a notification "Login attempt failed" is triggered.

![Screenshot 2024-10-04 17 51 11](https://github.com/user-attachments/assets/1b7c2577-084f-47c4-b23f-570b1cb933c2)

As you can see this results in a mishmash of English and the user's local language.

### Describe the behavior you expected

There should be an entry in Lokalise to translate it.

### Steps to reproduce the issue

This has happend several times since mid of September, not sure how the error is triggered.
But for adding the translation reproducing it should not be necessary.

### What version of Home Assistant Core has the issue?

core-2024.10.0

### In which browser are you experiencing the issue with?

Google Chrome 130.0.6723.25 beta (64-Bit)

### Which operating system are you using to run this browser?

Chrome OS

**Comment by karwosts** [comment]
This is a core string, please file in home-assistant/core, thanks. 

https://github.com/home-assistant/core/blob/dev/homeassistant/components/http/ban.py#L142

**Comment by NoRi2909** [comment]
@karwosts I just re-filed the issue under https://github.com/home-assistant/core/issues/131507 for the HTTP integration so it can get tracked.  In my first bug report I had to marked the HTTP integration as causing the issue (newbie error).

There is the same missing translation for the "New devices discovered" notification which is one of the most frequent in Home Assistant:

![image](https://github.com/user-attachments/assets/6211b27b-7043-4104-a8fb-6ae74e6bc7ad)

I searched for the string but did not find it, yet.

Do you have a hint if that is frontend or some Core integration, too?

**Comment by karwosts** [comment]
FYI github search had no problem finding this, if you haven't tried that. You can search across all HA repos in one query:

https://github.com/search?q=org%3Ahome-assistant+%22New+devices+discovered%22&type=code
