### ISSUE TITLE
Icons are not displayed correctly (Please help) 

### ISSUE THREAD

**Issue by PaveLGIL** [home-assistant/frontend#22264]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in completely clear hass instalation

### Describe the issue you are experiencing

I really sorry, if I created issue in not correct plase..
I have created icon pack for my home devices, but some of it not displayed correctly. It displayed correctly in Figma, Chrome, Firefox, Github, but not in Home Assistant. What I’m doing wrong?
Link to icons pack - [GitHub - PaveLGIL/hass-pg-icons](https://github.com/PaveLGIL/hass-pg-icons/tree/main)

And how it looks in my HA:
![a3b96f8f4546d703855761592915b4ea3235d9ab](https://github.com/user-attachments/assets/cc859d23-2db9-4c8f-92a7-ebf2718d1765)
![7243f503ccabb002d6dd511cdd41394cf24d9a52](https://github.com/user-attachments/assets/a2ae84a3-e0bd-41c4-8694-46c1c84a1a93)
<img width="212" alt="Screenshot 2024-10-06 at 15 57 33" src="https://github.com/user-attachments/assets/53214fc8-e83e-4ee1-ad34-50da056196bc">

Icons created with Figma.

### Describe the behavior you expected

How it should looks like:
![f087b05d16109801fe57201ab4455ea40714bd46](https://github.com/user-attachments/assets/0c7bed08-5045-4769-a25d-427360d3cc0f)
![f72ed18a5646afc38e2a538dc2b30e3df1ef4542](https://github.com/user-attachments/assets/790c35d8-9e50-42ca-b4ef-d5fedd8530e4)
<img width="154" alt="Screenshot 2024-10-06 at 15 58 19" src="https://github.com/user-attachments/assets/354d0666-8057-43a9-b35b-b045d779d7ce">

### Steps to reproduce the issue

1. Install icon pack throuhg HACS
2. Use convector-on icon for example

### What version of Home Assistant Core has the issue?

latest and previous

### In which browser are you experiencing the issue with?

All, and in Home Assistant APP

### Which operating system are you using to run this browser?

problem everywhere

**Comment by karwosts** [comment]
There is no support here for custom plugins, you might have more luck asking in community forum.

**Comment by PaveLGIL** [comment]
I have finaly solve it! I opened my icons with figma, select graphics, press on Path → Flatten and then export SVG file) And now it works as expected!
