### ISSUE TITLE
Time Tooltip in Notifications misplaced in Firefox

### ISSUE THREAD

**Issue by ximex** [home-assistant/frontend#22283]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If you hover over the time (red circle in attached image) a tooltip got shown but at the wrong place in Firefox (working in Chromium).
The gab increases for every next notification item

### Describe the behavior you expected

Tooltip is directly below the hovered time

### Steps to reproduce the issue

1. Have one or more notifications
2. Open notification panel
3. Hover over time
4. See misplaced tooltip

### What version of Home Assistant Core has the issue?

2024.10.1

### In which browser are you experiencing the issue with?

Firefox 131

### Which operating system are you using to run this browser?

Kubuntu 24.04

### Additional information

The difference what i saw between Chromium and Firefox is that Firefox has top/left setted in style attribute for simple-tooltip. This is not in Chromium

![image](https://github.com/user-attachments/assets/d7a151f8-9fdb-43f2-b46d-7b78db11f2bc)

**Comment by wendevlin** [comment]
Hey @ximex, good catch thanks
