### ISSUE TITLE
Tuya Bulb does not show power source on Front End

### ISSUE THREAD

**Issue by Merril-r** [home-assistant/frontend#22285]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have several Zigbee GU10/E14 5W smart bulbs that do not show an icon for power sorce. Instead they show a question mark.

The model number is : [TS0505B_2_2]

### Describe the behavior you expected

The icon should show that it is mains powered.

### Steps to reproduce the issue

Have no steps to reproduce. I have repaired the devices and they still show a question mark.

### What version of Home Assistant Core has the issue?

2024.10.1

### What was the last working version of Home Assistant Core?

Been like that since I added bulbs

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
const {light} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: ['TS0505B'],
    model: 'TS0505B',
    vendor: '_TZ3210_it1u8ahz',
    description: 'Automatically generated definition',
    extend: [light({"colorTemp":{"range":[143,500]},"color":{"modes":["xy","hs"]}})],
    meta: {},
};

module.exports = definition;
```

**Comment by karwosts** [comment]
Can you include a screenshot of the page with this icon? Not familiar with this power source indicator.

**Comment by Merril-r** [comment]
![Power Source](https://github.com/user-attachments/assets/0d4df9c6-7975-476b-8789-ea211e0970c8)

**Comment by Merril-r** [comment]
> Can you include a screenshot of the page with this icon? Not familiar with this power source indicator.

I have added a screen shot

**Comment by silamon** [comment]
That's a frontend of a different product zigbee2mqtt, you can open an issue here: https://github.com/Koenkk/zigbee2mqtt/issues
