### ISSUE TITLE
Automation editor adds `service` key when it should add `action` instead

### ISSUE THREAD

**Issue by tjhorner** [home-assistant/frontend#22293]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I add a "Play media" action to an automation with the UI then set the device or select the media to play, it adds `service: media_player.play_media` to the underlying YAML when it should only add `action: media_player.play_media`. This causes the UI to kick the user back to the text editor, and the automation fails to save because it uses both `action` and `service` keys.

I am only able to reproduce it with this specific action, but it's possible it happens with others.

### Describe the behavior you expected

The UI should not add a `service` key to the step.

### Steps to reproduce the issue

1. Create a new automation.
2. Press "+ ADD ACTION".
3. Add "Media player" > "Play media".
4. Select a media player entity from the dropdown.
5. Attempt to save the automation.

https://github.com/user-attachments/assets/43af15de-870a-4cc7-9866-da47df7f2b97

### What version of Home Assistant Core has the issue?

2024.10.1

### In which browser are you experiencing the issue with?

Arc Version 1.63.0 (54427) (Chromium Engine Version 129.0.6668.90)

### Which operating system are you using to run this browser?

macOS 15.1 Beta (24B5055e)

**Comment by tjhorner** [comment]
If I'm not mistaken, the only thing that needs to be changed is `service` -> `action` on this line:

https://github.com/home-assistant/frontend/blob/5877d69c8756f1b1f646f28701c338b70cfcbfcd/src/panels/config/automation/action/types/ha-automation-action-play_media.ts#L55

If someone with deeper knowledge can confirm this is the case, I can go ahead and whip up a quick PR 😄

**Comment by silamon** [comment]
Yeah, PR is welcome. 👍

**Comment by tjhorner** [comment]
@silamon done!

**Comment by tjhorner** [comment]
Just found #22254 which is the same thing but in a different action element.
