### ISSUE TITLE
Matter: Small typo in "End-device" string

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22292]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The string at

     ui::panel::config::matter::node_type::end_device

contains a small typo.

### Describe the behavior you expected

Should be "End device", but contains a wrong dash: "End-device"

### Steps to reproduce the issue

n/a

### What version of Home Assistant Core has the issue?

core-2024.10.1

### In which browser are you experiencing the issue with?

Google Chrome 130.0.6723.25 beta (64-Bit)

### Which operating system are you using to run this browser?

Chrome OS

**Comment by j4n-e4t** [comment]
Hi @NoRi2909.

I've opened a PR that fixes the issue. See #22390 

Viele Grüße 😉
