### ISSUE TITLE
Names for new tags (NFC or QR) not saved to database

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22302]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When creating a new Tag either on Desktop (QR code) or on Mobile (NFC tag) the name entered in the 'New tag' dialog is not saved to the database.
It does show up in the Tags list at first but is gone after refreshing or when checking on a different device.

### Describe the behavior you expected

The Name entered in the dialog should be saved.

### Steps to reproduce the issue

Same result  on Desktop or on Mobile:

1. Go to Settings > Tags and tap the "Add tag" button.
2. Enter a Name for the tag.
3. Enter an ID or just leave it blank to get a GUID instead.
4. Tap either "Create" or "Create and write" (Mobile only)
    (if you selected the latter proceed writing via NFC)

The tag will show up in the list with the name you just assigned:

![image 1 ](https://github.com/user-attachments/assets/14764db7-c78c-4f3b-965e-23e22b8f29a2)

5. Now check the Tags list on some other device or simply refresh the page.
The name will be gone, replaced with the ID that you entered in step 3 or that was auto-assigned.

![image 2](https://github.com/user-attachments/assets/2c6a0e8a-da2c-48ef-ae2f-a4837fa2e571)

I can reproduce this in Chrome on my desktop just as well, just already had the Android screen shots at hand.

### What version of Home Assistant Core has the issue?

core-2024.10.1

### What was the last working version of Home Assistant Core?

n/a

### In which browser are you experiencing the issue with?

Companion app / Google Chrome 130.0.6723.25 beta (64-Bit)

### Which operating system are you using to run this browser?

Android 15 / Chrome OS

**Comment by karwosts** [comment]
IIRC this is a core issue: https://github.com/home-assistant/core/issues/125361

**Comment by NoRi2909** [comment]
@karwosts OK, now it's moved from the Android app where I first discovered this bug via frontend to core. 8-)

Anything I can do on that extremely quiet front over there to push this towards a fix?

**Comment by karwosts** [comment]
Not really anything more you can do, unless you're inclined to try to publish a bugfix yourself.
