### ISSUE TITLE
Thread configure menu cant select "Add to preferred network"

### ISSUE THREAD

**Issue by darkxst** [home-assistant/frontend#22306]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On the Thread configure page, index of menu items seems to be broken.

If I select "Add to preffered network", "Change Channel" gets selected.
If I select "Change channel", "Reset BR" is selected.

### Describe the behavior you expected

Select "Add to preferred network" should invoke the correct action to add a secondary BR to the preferred network.

### Steps to reproduce the issue

1. Bring up a second Thread BR via add-on on second HA instance
2. Go to Configure page in Thread integration
3. Try select "Add to preferred network"
...

### What version of Home Assistant Core has the issue?

2024.10.1

### In which browser are you experiencing the issue with?

Chrome 129.0.6668.89

### Which operating system are you using to run this browser?

Ubunutu 24.04

### Additional information

![image](https://github.com/user-attachments/assets/23e1b691-cdf8-4d0f-bf38-6a1e01d7ac99)

**Comment by Narfmeister** [comment]
https://github.com/home-assistant/frontend/issues/22307 Same issue reported here

**Comment by Narfmeister** [comment]
I noticed in my testing that it's as though everything option seems shifted down by one.
The 'Change Channel' button seems to perform the 'Reset Border Router' function and 'Reset Border Router' seems to perform no function.

**Comment by darkxst** [comment]
This appears to be a regression from PR https://github.com/home-assistant/frontend/pull/22183.

**Comment by darkxst** [comment]
This appears to be a regression from PR https://github.com/home-assistant/frontend/pull/22183.

**Comment by agners** [comment]
@Narfmeister what OTBR are you using?

**Comment by Narfmeister** [comment]
@agners I'm using a Sonoff Zigbee Dongle with the community firmware installed.
