### ISSUE TITLE
Home-Assistant logo disappears on scoll of the website.

### ISSUE THREAD

**Issue by meetarora10** [home-assistant/frontend#22336]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Home-Assistant logo disappears on scroll of the website. 
![Screenshot (1132)](https://github.com/user-attachments/assets/7f1c8c67-79e0-40fa-ad76-62bc610f52b2)

### Describe the behavior you expected

Logo must be visible properly whether scroll is done or not.

### Steps to reproduce the issue

1. I can change the color of the logo when scroll is done.

### What version of Home Assistant Core has the issue?

http://homeassistant.local:8123

**Comment by silamon** [comment]
You can open an issue at https://github.com/home-assistant/home-assistant.io/ for this. This is for specific bug reports for the Home Assistant frontend.
