### ISSUE TITLE
EspHome the esp32dev sensors stop working every 3-5 days

### ISSUE THREAD

**Issue by alarmatwork** [home-assistant/frontend#22331]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In every 3-5 days atom sendsors stop giving the data in ESPHome integration. 
If I open the sensor by HTTP interface, then it works all right with all the data present.
If I remove device uder ESPHome and add it back, then it starts working and produces solid data for another 3-5 days

### Describe the behavior you expected

I expect it to keep working after 3-5 days and continue providing data.

### Steps to reproduce the issue

1. Add a esp32dev sensor ESPHome (based on atom lite esp32 board)
2. Use the data
3. Wait 3-5 days with all the data present
4. See no more data
...

### What version of Home Assistant Core has the issue?

2024.10.1

### What was the last working version of Home Assistant Core?

-

### In which browser are you experiencing the issue with?

Arc Version 1.61.2 (54148)

### Which operating system are you using to run this browser?

MacOS, Android

### State of relevant entities

```txt
sensor.plant_sensor_e3d1_moisture
Apelsin potis niiskus
unavailable	state_class: measurement
unit_of_measurement: %
device_class: moisture
friendly_name: Apelsin potis niiskus
```

**Comment by silamon** [comment]
This issue tracker is only for frontend bug reports.
