### ISSUE TITLE
Reolink led light unsynchronized with HA

### ISSUE THREAD

**Issue by ing-anaya** [home-assistant/frontend#22341]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

This month I bought my first 3 Reolink cameras (811A POE, Duo 3 POE and Trackmix POE), But I have a problem in 2 of the automations with Home Assistant. I need that when the cameras turn on their LEDs they also turn on some lights at the entrance of the house, but with the 3 cameras there is a random delay of between 15 seconds to 1 minute in which HA refresh the status of the leds. The motion sensor of the camera has instant refresh in HA, the problem is only with turning on and also with turning off the LED lights.

Thanks,
Regads,

### Describe the behavior you expected

The expected is that when the camera lights switch to on, the status of the LED will turn on in HA instantly, and this will make possible to trigger the automation. Same when turn off the LEDs.

### Steps to reproduce the issue

1. At night or in a controlled dark environment
2. Turn off the garage lights (or test lamp)
3. Check remotely that the camera has active IR sensors
4. Get closer so that the camera activates the LED lights
5. Check the time in which HA receives the signal to turn on the lights from the camera and changes the status to on in the HA summary
The test lamp turning on should be synchronized with the camera LED turning on (1 or 2 seconds difference would be acceptable, but it is taking up to 1 minute to notice the change)
6. Observe how the garage lights turn on with the automation.
7. Move away from the camera so that the camera lights turn off
8. Check the time when HA receives the lights off signal from the camera and changes the status to off in the HA summary
The test lamp turning off should be synchronized with the camera LED turning off (1 or 2 seconds difference would be acceptable, but it is taking up to 1 minute to notice the change)
9. Observe how the garage lights turn off with the automation.

### What version of Home Assistant Core has the issue?

2024.10.2

### In which browser are you experiencing the issue with?

it's a HA issue, not browser related. Chrome 129.0.6668.100 

### Which operating system are you using to run this browser?

Windows 10

**Comment by silamon** [comment]
Open an issue at https://github.com/home-assistant/core, this is for frontend specific bugs.
