### ISSUE TITLE
Popup with download link disappear before being able to see or click it

### ISSUE THREAD

**Issue by douloh** [home-assistant/frontend#22349]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On The HA software on a recent updated Mac using last version of home assistant. When I try to add a device in ESPHome and try to install the device plugged into the computer it compiles the program and then I briefly see a popup which disappears and I cannot see it again nor find a way to make sure the popup stays available

### Describe the behavior you expected

Seeing a popup, reading what is on it and be able to click on the button or link

### Steps to reproduce the issue

1. Add a new device in ESP HOME
2. Click on install
3. Chose install manually or through ESP home
4. Wait for the popup to appear after compiling and deiappearing right away
...

### What version of Home Assistant Core has the issue?

2024.10.2

### What was the last working version of Home Assistant Core?

it is my first one

### In which browser are you experiencing the issue with?

Not the browser, the software

### Which operating system are you using to run this browser?

14.6.1 (23G93)

**Comment by wendevlin** [comment]
Hi @douloh,

This issue is not related with home-assistant frontend, it is an issue with the esphome addon. Please create your issue here: https://github.com/esphome/issues/issues
