### ISSUE TITLE
SolarLog 500 and 2024.10.2: "timeout for http connection"

### ISSUE THREAD

**Issue by toyota-axel** [home-assistant/frontend#22343]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After jumping from 2024.9.3 to 2024.10.2, SolarLog integration runs into a timeout error for the http connection.

### Describe the behavior you expected

No timeout, clear connection to pull sensor data from SolarLog 500. Worked fine with 9.3.

### Steps to reproduce the issue

1. Update from 9.3 to 10.4
2. Voilá!
3. SL 500 has no password set for accessing the data (JSON, afair). Worked seamlessly with 9.3
4. even setting up SL-integration new didn't work (password request which is new was left aside as, no password is set)

### What version of Home Assistant Core has the issue?

2024.10.2

### What was the last working version of Home Assistant Core?

2024.9.3

### In which browser are you experiencing the issue with?

Firefox (multiple, this is not a browser problem)

### Which operating system are you using to run this browser?

Ubunto 22.04

### Javascript errors shown in your browser console/inspector

```txt
timeout connecting to http://solarlog.lan
timeout connecting to http://192.168.10.50
```

**Comment by silamon** [comment]
Open an issue at https://github.com/home-assistant/core, this is for frontend specific bugs.
