### ISSUE TITLE
#can add all the contributers github profiles to the readme

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [home-assistant/frontend#22351]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

no contributers list at readme

### Describe the behavior you expected

Can add contributors github proile to increase readme quality

### Steps to reproduce the issue

1.fork and clone repo
2.add changes in readme
3.raise a PR

### What version of Home Assistant Core has the issue?

2024.10.2

**Comment by silamon** [comment]
We credit the contributors in a different way on the website.
