### ISSUE TITLE
Periodically, you can't go back to the previous page

### ISSUE THREAD

**Issue by ChapayTv** [home-assistant/frontend#22376]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In a chaotic order, I periodically can't go back to the previous page of settings, integrations, and anything else in home assistant, whether it's a mobile app or some other browser. the problems started a couple of versions of naza maybe earlier noticed tiolko now. This problem is also observed in my friends.

### Describe the behavior you expected

Correct work so that you can normally return to the previous page in home assistant

### Steps to reproduce the issue

I definitely can't provide this as it occurs randomly 100 times a day.

### What version of Home Assistant Core has the issue?

2024.10.2

### In which browser are you experiencing the issue with?

впв

### Which operating system are you using to run this browser?

Windows 10

**Comment by ildar170975** [comment]
Same?
https://github.com/home-assistant/frontend/issues/17820
