### ISSUE TITLE
Dev tools -> Statistics: "INFO" issue has buttons like a "FIX"issue

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#22370]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Right after updating to 2024.10.2 I got similar strings in Dev tools -> Statistics:
![image](https://github.com/user-attachments/assets/4700a3de-99e0-4841-8b0b-cedc9318847a)

Before updating these strings were not shown here.

After pressing the "INFO" button:
![image](https://github.com/user-attachments/assets/c45c32da-bcdc-4efd-8691-b97a61645c73)

A content of this popup is same as I observed a month ago - but this issue had a "FIX" button.
I pressed a "DELETE" button and then never seen this issue in Dev tools.

### Describe the behavior you expected

"INFO" issues should not allow to be "fixed"

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2024.10.2

### In which browser are you experiencing the issue with?

Chrome 129.0.6668.100

### Which operating system are you using to run this browser?

Win10

**Comment by karwosts** [comment]
fix pending
