### ISSUE TITLE
Can't onboard, wrong currency for Venezuela

### ISSUE THREAD

**Issue by Lars** [home-assistant/frontend#22389]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I can't onboard as when I select my location either by auto detection, or via search, as Caracas Venezuela, on the next step I get a currency error:

invalid ISO 4217 formatted currency for dictionary value @ data['currency']. Got 'VEF'

VEF is an older currency for Venezuela, and it's listed inside HISTORIC_CURRENCIES in currencies.py, the current currency should be VED.

The oboard interface is not allowing me to hit "next" on the country selection screen.

### Describe the behavior you expected

I expected being able to finish the onboarding process.

### Steps to reproduce the issue

1. Install the HassOS 13.2 image in libvirt.
2. Start the onboarding process
3. Search for, or select Caracas Venezuela as the location.
4. Hit next onto the country selection screen.

### What version of Home Assistant Core has the issue?

2024.10.2

### In which browser are you experiencing the issue with?

Vivaldi 6.9.3447.54

### Which operating system are you using to run this browser?

Debian Trixie

**Comment by karwosts** [comment]
This error comes from home-assistant/core (not frontend), so you may be better off filing an issue there.

**Comment by Lars** [comment]
Shifted to core.
