### ISSUE TITLE
Small typographical glitches in the UI that carry over to translations

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22401]
### Describe the issue you are experiencing

Two small typographical issues, easy to fix:.

1. Remove the inconsistent point at the end:

![Add dashboard excessive dot](https://github.com/user-attachments/assets/69c47bf9-6e20-4647-b5db-42f19fe7e6ae)

https://github.com/home-assistant/frontend/blob/e01e31341b667c474e54867652acf73539008e58/src/translations/en.json#L2530-L2532

---

2. Change the point into a colon as this is the label for the edit fields below it:

![Select devices - colon missing](https://github.com/user-attachments/assets/8d365026-0182-497b-a563-89294c763898)

https://github.com/home-assistant/frontend/blob/e01e31341b667c474e54867652acf73539008e58/src/translations/en.json#L4224

### What version of Home Assistant Core has the issue?

core-2024.10.2

**Comment by j4n-e4t** [comment]
Hi @NoRi2909,

I've opened a PR for this. I've also spotted another "point" in your second screenshot ("Allow access using..."). Removed that as well. See #22402

**Comment by NoRi2909** [comment]
@j4n-e4t Very nice. That other point should be OK as this concludes a sentence.

In German just the use of periods (yes, those words … :-)) in headlines is not OK.

**Comment by j4n-e4t** [comment]
I've now added it back ;-)
Should be good to go now

**Comment by NoRi2909** [comment]
@j4n-e4t If you like to submit one more PR, I just updated this one here with the links to the source files, making it easier to proceed:

https://github.com/home-assistant/frontend/issues/22324

It's also just text changes so it should be no big deal to get this approved.

**Comment by j4n-e4t** [comment]
Thank you for the update. I think I'll do that tomorrow. It's late right now. 😉
