### ISSUE TITLE
Missing translation for "Current Version:" in Add-on details etc.

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22404]
### Describe the issue you are experiencing

While most of the Add-on details are translated and only those texts provided by the Add-on itself show up in English, the "Current version:" label has not been translated. Here with the German UI:

![Add-on - Current version](https://github.com/user-attachments/assets/9c84b393-fe3a-4934-89f8-cf4438a9f19e)

Especially as "Change log" is localized right next to it this should be fixed.

Note that "Core" is over-localized as "Kern" here, although this should remain "Core" in German, too.
I don't understand why this is the case because in Lokalise that string is correct since 2024-01-01:

![image](https://github.com/user-attachments/assets/fde34fd2-9e26-46c7-a1ca-8347a7b0dbbd)

While on this page this one could see a small improvement as well:

https://github.com/home-assistant/frontend/blob/6298534b9cb07a69ab0567711801ebb7af4870ed/src/translations/en.json#L7436-L7439

Should be "restart" or "relaunch" instead.

If you opt for "relaunch" also change this for consistency:

https://github.com/home-assistant/frontend/blob/6298534b9cb07a69ab0567711801ebb7af4870ed/src/translations/en.json#L7431-L7435

### What version of Home Assistant Core has the issue?

core-2024.10.2

**Comment by NoRi2909** [comment]
Regarding the issue with "Core" still showing up as "Kern" although this was already fixed in Lokalise on 2024-01-01 for German:

There seems to be a longer standing issue with this string and probably more in that area. I just checked in Spanish:

![Screenshot 2024-10-17 20 57 17](https://github.com/user-attachments/assets/bbf03dec-5554-48e2-9fbc-5879ad3da727)

As you can see it says "Núcleo" in that place, but according to Lokalise this was also fixed to say "Core" in 2023, over a year ago:

![Screenshot 2024-10-17 20 56 58](https://github.com/user-attachments/assets/fc61876a-e9c0-46aa-9555-ebf72817f136)

**Comment by silamon** [comment]
Open an issue at supervisor, since they track their own frontend version with ours, but hasn't been updated for over a year: 
https://github.com/home-assistant/supervisor/issues

**Comment by NoRi2909** [comment]
@silamon Posted an updated and compressed version of this bug at https://github.com/home-assistant/supervisor/issues/5362
