### ISSUE TITLE
Inconsistent and unnecessary  "Close selection mode" key

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22425]
### Describe the issue you are experiencing

There are two ways to exit selection mode in Settings:

- Select "Close selection mode" from the Select menu
- Click the X in the upper left

However, when you hover over the X icon the overlay says "Exit selection mode"

### Describe the behavior you expected

Both should be made consistent by using the same key for both elements in the UI.
This simplifies translations quite a bit, too.

There should be

https://github.com/home-assistant/frontend/blob/a04a449eb9059c097d5872fc44cb41659ed0a59a/src/translations/en.json#L532

used in both places and the following can be removed:

https://github.com/home-assistant/frontend/blob/a04a449eb9059c097d5872fc44cb41659ed0a59a/src/translations/en.json#L541

This also makes it consistent with all other "exit mode" keys like, e.g.:

https://github.com/home-assistant/frontend/blob/a04a449eb9059c097d5872fc44cb41659ed0a59a/src/translations/en.json#L1178

### Steps to reproduce the issue

1. Go to any list view in Settings
2. Enable selection mode using the button next to the Filter button.
3. Compare the menu item and the overlay for the X.

### What version of Home Assistant Core has the issue?

core-2024.10.2

**Comment by NoRi2909** [comment]
@j4n-e4t That's one for you. Note that here the fix is not just removing `close_select_mode` from the strings file, but also in the actual code replacing `close_select_mode` with `exit_selection_mode`.
I did not find that code myself, but you know your way around in github much better than me. 😃

**Comment by j4n-e4t** [comment]
I've now replaced all occurrences of `close_select_mode` with `exit_selection_mode`. Could you take a look? (#22434)

**Comment by NoRi2909** [comment]
Looks OK to me. Let's see if it goes through. Then we have a consistent UI in that area.
