### ISSUE TITLE
Malformed "storage" link in Media Management dialog

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22431]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The Tip in the Media management dialog contains a link to the Storage panel.

![Screenshot 2024-10-18 15 19 06](https://github.com/user-attachments/assets/13b67106-362a-4361-8007-4a6da051a00d)

There are two bugs:

1. The word should not be forced to lowercase
No big deal in English, although it is a name and should be capitalized as it is in the string that is used here.
But in translations like German the word is forced into lowercase (It's "Speicher" in the strings file) making this a bug.

https://github.com/home-assistant/frontend/blob/655ce05efedd2e82359e9713dc2f5882c5b331d6/src/components/media-player/dialog-media-manage.ts#L214

2. The link extends to the space character to the right of the word.
Only the word itself should be underlined and clickable.

That must be hidden in code here, too.

### Steps to reproduce the issue

1. In the sidebar click on Media.
2. Select My Media.
3. Click on Manage in the upper right.

### What version of Home Assistant Core has the issue?

core-2024.11.3

**Comment by NoRi2909** [comment]
I assume that this line needs to be removed to fix the forced lowercase:

https://github.com/home-assistant/frontend/blob/655ce05efedd2e82359e9713dc2f5882c5b331d6/src/components/media-player/dialog-media-manage.ts#L214

The space character that hangs over must be hidden in that code block, too.

**Comment by Kisty** [comment]
Spotted this too and trying to see if I can fix it. Not a web dev, Android dev by trade, but wanna have a go. Tried seeing if there was an issue with the lokalise string but I don't think there is. 
https://app.lokalise.com/project/3420425759f6d6d241f598.13594006/?view=multi&k=326793216&search=key::ui::panel::config::tips::media_storage&commentId=6395c343-478c-4aa8-897e-1286af45b54a&comments=1

I think it's an issue with the [`dialog-media-manage.ts`](https://github.com/home-assistant/frontend/blob/655ce05efedd2e82359e9713dc2f5882c5b331d6/src/components/media-player/dialog-media-manage.ts#L203) file.

**Comment by NoRi2909** [comment]
Hi @Kisty – I've edited my bug above to include the line `.toLowerCase()} ` that should be replaced with just a `}` .

Perhaps you can spot where the extension of the link underline to the adjacend space character comes from.

**Comment by NoRi2909** [comment]
Hi @Kisty - I think the problem with the URL extending to the space character is caused by the indentation of the last line here:

So if we change

```
                    ${this.hass
                      .localize(
                        "ui.components.media-browser.file_management.tip_storage_panel"
                      )
                      .toLowerCase()}

```

to

```
                    ${this.hass
                      .localize(
                        "ui.components.media-browser.file_management.tip_storage_panel"
                      )
                    }
```

that should fix both issues.

**Comment by Kisty** [comment]
Hey! I think that may work.

I was having problems with my dev envirnoment getting set up and figuring out how to mock out the HAOS requirement to test it properly. Did you manage to? I guess I can just force it in code while testing it, but wanted to do it properly. Lemme fireit up now and see where I got to.

**Comment by NoRi2909** [comment]
I usually do just strings fixes which I notice while working on the German translation in Lokalise.
There the web editor in GitHub works just fine as no local tests are necessary.
As you can see above I tried the idea above in a PR to see how far I could get but failed.

When you have a full dev environment up and running you should have more success than me.
So just give it another try.
