### ISSUE TITLE
Settings > Repairs: Fix two inaccurate messages 

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22450]
### Describe the issue you are experiencing

There are two messages in System > Repairs that should be slightly reworded:

https://github.com/home-assistant/frontend/blob/f05c204da38af322c3f7ef178ae859ec6b938bae/src/translations/en.json#L1968

This should say "pending" instead of "available". Repairs are not something you're happy to see becoming available, but rather something that has to be done at some point in time.

https://github.com/home-assistant/frontend/blob/f05c204da38af322c3f7ef178ae859ec6b938bae/src/translations/en.json#L1975

This dialog actually shows a list of the startup times for all individual integrations so that has to be plural "startup times".

![Screenshot 2024-10-21 08 05 47](https://github.com/user-attachments/assets/03ddd14a-e267-461a-8f49-2c9f12fb3241)

Noticed while going over the German translation where grammar really emphasizes what's wrong here.

### What version of Home Assistant Core has the issue?

core-2024.10.3

**Comment by shodhan-rai** [comment]
Assign me this
