### ISSUE TITLE
PV to Grid entity missing

### ISSUE THREAD

**Issue by hytrek** [home-assistant/frontend#22454]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hi there, for using the integration full one entity is missing, that the costal device provides: "PV to grid" that is available from Kostal and I am able to use this in other brokers like ioBroker... Could you please check and add this entity?

Thanks

### Describe the behavior you expected

An Entity Kostal offers is missing

### Steps to reproduce the issue

Entity is  missing

### What version of Home Assistant Core has the issue?

2024.10.3

### Additional information

Thank you

**Comment by karwosts** [comment]
I think you probably meant to report this to home-assistant/core? Doesn't seem like a frontend issue.

**Comment by karwosts** [comment]
If you are saying that an integration (Kostal) is not functioning properly, report that here:

https://github.com/home-assistant/core/issues/new?assignees=&labels=&projects=&template=bug_report.yml
