### ISSUE TITLE
Node-RED Add-on Not Functioning Inside Home Assistant

### ISSUE THREAD

**Issue by 1192410** [home-assistant/frontend#22462]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

This issue has already been filed [here](https://github.com/hassio-addons/addon-node-red/issues/1971), but it seems no one is picking it up. Essentially, the Node-RED add-on is not functioning from within Home Assistant, although it does work when accessed directly via port 1880. Given that Node-RED is likely one of the most widely used add-ons, I believe this should be addressed promptly. If this message is in the wrong place, I apologize.

Many thanks,
Andreas

### Describe the behavior you expected

I want a connection to Home assistant, but there is no connection, for example inject buttons are greyed out. 

### Steps to reproduce the issue

See here https://github.com/hassio-addons/addon-node-red/issues/1971

### What version of Home Assistant Core has the issue?

2024.10.3

### What was the last working version of Home Assistant Core?

2024.10.3

### Which operating system are you using to run this browser?

Win11

**Comment by silamon** [comment]
There's nothing we can do about it in this repository.
