### ISSUE TITLE
Roborock integration - multiple floors

### ISSUE THREAD

**Issue by goodsale** [home-assistant/frontend#22477]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I am using the official integration for Roborock and I have an S7 MAXV.

In the Roborock app I have configured 2 floors and 2 different maps.

With the integration I see both maps that are selectable via select.robot_xxx_map_xx and I see the correct images based on the selection.

Going as a developer to inqury the rooms as indicated in the instructions, when launching the command

```
action: roborock.get_maps
target:
  entity_id: vacuum.robot_xxxx

``` 
I get:

```
vacuum.robot_xxxx
  maps:
    - flag: 0
      name: Casa
      rooms:
        "16": Corridoio
        "17": Cucina
        "18": Ingresso
        "19": Sala
        "20": Bambini
        "21": Camera
        "22": Bagno
    - flag: 1
      name: Veranda
      rooms:
        "16": Corridoio
        "17": Cucina
        "18": Ingresso
        "19": Sala
        "20": Bambini
        "21": Camera
        "22": Bagno

``` 

You can see that the command extracts the "flag 0" which I suppose is the first floor (map 1) and the "flag 1" second floor.

However, the rooms are not extracted correctly, those of flag 0 are identical to flag1.

It would be possible to access the information correctly and also know how to launch the commands to manage the different floors.

Thanks.

### Describe the behavior you expected

Correct rooms listed by floor

### Steps to reproduce the issue

1. inquiry in developer tools

### What version of Home Assistant Core has the issue?

last version

**Comment by silamon** [comment]
Open an issue at https://github.com/home-assistant/core towards the Roborock integraiton
