### ISSUE TITLE
Tags: Missing translations of icon column names in the cogwheel menu

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22498]
### Describe the issue you are experiencing

Under Settings > Tags the last two menu items in the cogwheel menu for the icon columns are missing the strings:

![Screenshot 2024-10-23 15 59 22](https://github.com/user-attachments/assets/0e0fef38-0621-4d10-a939-87f01cc62e97)

Should be

     Create automation
     Edit

here for translation, too.

### What version of Home Assistant Core has the issue?

core-2024.11.3

**Comment by shodhan-rai** [comment]
Can you provide me the path to where that settings is located

**Comment by NoRi2909** [comment]
> Can you provide me the path to where that settings is located

I'm no programmer but I assume that this list needs to be extended:

https://github.com/home-assistant/frontend/blob/3a1a4ade68a02b195d422e1d0e00196def059709/src/translations/en.json#L2144-L2148

with

     "automation": "Create Automation",
     "edit": "Edit",

But don't trust me, please verify. 😃

**Comment by NoRi2909** [comment]
Closed as fixed by https://github.com/home-assistant/frontend/pull/23003
