### ISSUE TITLE
Duplicated Entries In Logbook Card

### ISSUE THREAD

**Issue by wormuths** [home-assistant/frontend#22503]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In the sidebar, I have a logbook card which shows key events for my dashboard views. The problem I have is that the card shows the entries, sometimes fine, sometimes duplicated, sometimes the same entry 4-6 times. I end up with a long list because each key event entry is shown more than once. The duplicates have the same timestamps, and are from the same event.

It changes on browser refresh. Sometimes refreshing fixes the duplicates, sometimes it creates more duplicates. I am wondering if it’s a browser cache issue, but it happens so often I don’t want to keep hitting refresh just to try and fix it.

![Screenshot_20241023_125903](https://github.com/user-attachments/assets/4bed6942-4c4e-4ce1-9d02-6889f0eb421c)

### Describe the behavior you expected

Each entry should appear only once.

### Steps to reproduce the issue

Just put a logbook card on the dashboard.

### What version of Home Assistant Core has the issue?

Ongoing

### What was the last working version of Home Assistant Core?

Ongoing

### In which browser are you experiencing the issue with?

Firefox, Currently 131

### Which operating system are you using to run this browser?

Ubuntu 24.04

### Additional information

This has been happening for several years.

**Comment by silamon** [comment]
Probably related to https://github.com/home-assistant/frontend/issues/17769
