### ISSUE TITLE
Trend Helper: Missing translations for standard attributes

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22505]
### Describe the issue you are experiencing

When creating a Trend Helper the second step asks for the option to track an attribute of the entity instead of the entity itself. In the list of attributes I've only seen "State class" show up localized. All other attributes show up in English only.

![Screenshot 2024-10-23 21 37 09](https://github.com/user-attachments/assets/724d426c-7ce6-4d69-9361-e2f9d1e05fca)

![Screenshot 2024-10-23 20 52 40](https://github.com/user-attachments/assets/038979b8-535f-4fa7-aa0e-69367fb94859)

As strings for most them should be available (I did not find "Friendly Name" so far) it should be possible to translate them just like it already happens for the State class.

_Note that I found it confusing that the dialog did not mention that selecting an attribute is optional. In the two samples above I picked a temperature and a water level entity which are to be monitored themselves. The attributes (see screen shots) don't change at all for those._

### What version of Home Assistant Core has the issue?

core-2024.10.3

**Comment by silamon** [comment]
You cna open an issue at core towards the sensor integration: https://github.com/home-assistant/core/blob/dev/homeassistant/components/sensor/strings.json#L119
Because they are missing, we seem to replace _ and uppercase the first letter.

**Comment by NoRi2909** [comment]
@silamon Thanks for figuring out the root cause of this issue.

I've opened [a bug for the sensor integration](https://github.com/home-assistant/core/issues/130778) so they can track this.
