### ISSUE TITLE
Rename "More info dialog" to just "Details view" to streamline translations

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22517]
### Describe the issue you are experiencing

Translating "More info dialog" into German is almost impossible without creating some word monster like

     "Weitere Informationen"-Dialogfeld

This is simply no working solution to cover even the very few string variations, so I came up with just calling this

     Detailansicht

instead which works remarkably well in all contexts. In English this translates back to

     Details View

 which also fits much better for complex lighting controls like the WLED example here:

![Screenshot 2024-10-24 14 29 11](https://github.com/user-attachments/assets/b7985091-c2ec-430d-905d-64c21c5a49cb)

That isn't "more information", it's really a more detailed view to interact with that device. Similar with locations that open a map or sensors that show more detailed history graphs.

Also this is just a view, not a dialog with "Submit", "Delete" or"Cancel" buttons either.

There are just six strings that need to be updated for this change:

https://github.com/home-assistant/frontend/blob/fc9a0958d44475335ce30fc4c8099fab113b79e8/src/translations/en.json#L1428

https://github.com/home-assistant/frontend/blob/fc9a0958d44475335ce30fc4c8099fab113b79e8/src/translations/en.json#L5416

https://github.com/home-assistant/frontend/blob/fc9a0958d44475335ce30fc4c8099fab113b79e8/src/translations/en.json#L5770

And the following three where "More info dialog" can be shortened to "Details view":

https://github.com/home-assistant/frontend/blob/fc9a0958d44475335ce30fc4c8099fab113b79e8/src/translations/en.json#L5381

https://github.com/home-assistant/frontend/blob/fc9a0958d44475335ce30fc4c8099fab113b79e8/src/translations/en.json#L5901

https://github.com/home-assistant/frontend/blob/fc9a0958d44475335ce30fc4c8099fab113b79e8/src/translations/en.json#L6162

And finally this one, where it's even inconsistent in English with "info" instead of "More info":

https://github.com/home-assistant/frontend/blob/311f221387c30b0a2c56015aae641131c134b128/src/translations/en.json#L1231

All other occurrences of "More info" or "More information" open the Help etc. and should not be changed.

### What version of Home Assistant Core has the issue?

core-2024.10.3

**Comment by iemafzalhassan** [comment]
Hi 
please assign me this issue, I would like to work on it
