### ISSUE TITLE
The TP-Link P340 power strip wasn't found automatically but could be added manually It doesn't report power for any of the sockets

### ISSUE THREAD

**Issue by domgiles** [home-assistant/frontend#22530]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The TP-Link P340 power strip wasn't found automatically but could be added manually. It doesn't report power 

### Describe the behavior you expected

The strip to be automatically found and that all of the sockets would report power consumption rather than "Unavailable"

### Steps to reproduce the issue

1. Configure Power Strip in Tapo App
2. Look for socket in HA with Tapo Integration
3. Manually add socket with IP, username and password
4. Put a load of the power strip. Check HA and see that it's not showing load
...

### What version of Home Assistant Core has the issue?

2024.9.3

### In which browser are you experiencing the issue with?

Safari and Chrome

### Which operating system are you using to run this browser?

Soma 14.5

### State of relevant entities

```txt
state_class: measurement
device_class: power
friendly_name: Unnamed P304M Current consumption

state: unavailable
```

**Comment by karwosts** [comment]
Please file this in home-assistant/core for tplink integration, this isn't a frontend issue.
