### ISSUE TITLE
Cannot adjust temperature in Intergas InComfort/Intouch Lan2RF gateway

### ISSUE THREAD

**Issue by webpatrick** [home-assistant/frontend#22533]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

JavaScript error:

'>' not supported between instances of 'NoneType' and 'float'

### Describe the behavior you expected

Adjusting the setpoint of the thermostat

### Steps to reproduce the issue

1. Add the thermostat to a dashboard
2. Adjust the slider
3. Message appears `'>' not supported between instances of 'NoneType' and 'float'`

### What version of Home Assistant Core has the issue?

2024.10.3

### In which browser are you experiencing the issue with?

Google Chrome 130.0.6723.60

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
State: 
Heat

Attributes:
hvac_modes: heat
min_temp: 5
max_temp: 30
supported_features: 1
current_temperature: 20
temperature: 20
hvac_action: idle
status: 
room_temp: 20
setpoint: 0
override: 20

friendly_name: Thermostat 2
```

### Javascript errors shown in your browser console/inspector

```txt
{
    "code": "unknown_error",
    "message": "'>' not supported between instances of 'NoneType' and 'float'"
}
```

**Comment by karwosts** [comment]
I believe that message comes from the integration itself, not from the frontend. So you might want to file a core issue for that integration. 

Do you get the same if you just call the `climate.set_temperature` action manually?

**Comment by webpatrick** [comment]
I think someone (who can) needs to assign the label `incomfort`

**Comment by webpatrick** [comment]
> I believe that message comes from the integration itself, not from the frontend. So you might want to file a core issue for that integration.

I think you are right, can the issue not be moved to core?

**Comment by webpatrick** [comment]
Wrong repo
