### ISSUE TITLE
Automations: and Scripts: Fix remaining inconsistent "Confirm …" condition for zones

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22542]
### Describe the issue you are experiencing

In https://github.com/home-assistant/frontend/pull/22497 all condition strings starting with "Confirm …" were changed to just "If …" for consistency – except for this one that was missed:

In automations:

![Screenshot 2024-10-26 10 54 39](https://github.com/user-attachments/assets/47ec2984-87bb-4198-9e2b-71dedef2d7ec)

In scripts:

![Screenshot 2024-10-26 10 56 22](https://github.com/user-attachments/assets/aa9b5b78-e917-4ce9-bd2f-846c7315b20f)

So here the remaining "Confirm" should also replaced by a simple "if":

https://github.com/home-assistant/frontend/blob/2daaa1cb9c93e51ea30d59c0cb73306d11ac431e/src/translations/en.json#L3270

For the final touch you should also change the temporary placeholder shown before an actual entity is selected by the user from

https://github.com/home-assistant/frontend/blob/2daaa1cb9c93e51ea30d59c0cb73306d11ac431e/src/translations/en.json#L3207

to

     If state confirmed

This will also allow a consistent translation of that last one.

### What version of Home Assistant Core has the issue?

core-2024.10.4

### Additional information

Note that the fixes from https://github.com/home-assistant/frontend/pull/22497 are not live yet as the PR was applied shortly after the current release was frozen.

**Comment by silamon** [comment]
Fixed by https://github.com/home-assistant/frontend/pull/22816
