### ISSUE TITLE
The lines in the chart are discontinuous

### ISSUE THREAD

**Issue by Cookie987** [home-assistant/frontend#22555]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The lines in the chart are discontinuous. However, in the history view, they are normal.

![discontinuous](https://github.com/user-attachments/assets/3baa1b20-e222-4da7-8b1a-1540a91f4a2f)

![continuous](https://github.com/user-attachments/assets/cf56610a-0469-4aa7-9199-6db6b721f77a)

video:

https://github.com/user-attachments/assets/93324177-ade5-4a9c-afcc-9a3329a56c57

### Describe the behavior you expected

I hope the lines can be connected.

### Steps to reproduce the issue

1.Reboot into safe mode and clean the browser cache.

2.The problem occurred.

Note: I also tried to install HA on another machine and the problem didn't happened on it.

### What version of Home Assistant Core has the issue?

2024.10.4

### In which browser are you experiencing the issue with?

Microsoft Edge 130.0.2849.56

### Which operating system are you using to run this browser?

Windows 11 Workstation 22631.4391

**Comment by karwosts** [comment]
The first chart you show with the discontinuities is a graph of your *statistics*, while the second graph from more detail is the history view. 

Seems like for some reason your statistics generation is having some issues? Is it exactly once per hour that it has the discontinuity? Almost looks like that but hard to tell.

**Comment by Cookie987** [comment]
I checked it again, and I think it is exactly once per hour.

**Comment by Cookie987** [comment]
Somehow it has been fixed now.
![image](https://github.com/user-attachments/assets/0f13bb4f-e6fb-4d14-8ae1-f3b097f25dec)
