### ISSUE TITLE
Random sensor Helper: "VOCs" duplicated in Device classes list

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22557]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When you create a Random sensor Helper the dropdown for selecting the Device class has two entries for VOCs:

![Screenshot 2024-10-27 18 31 31](https://github.com/user-attachments/assets/1d3f239b-f0c3-4a7b-bd14-46a556967e45)

### Describe the behavior you expected

There probably should be just a single menu item …

### Steps to reproduce the issue

1. Go to Settings > Devices & services > Helpers.
2. Create Helper
3. Select > Random > Random sensor
4. Click into the Device class field.

### What version of Home Assistant Core has the issue?

core-2024.10.4

**Comment by ildar170975** [comment]
This is not about only a Random helper - it seems to be about any place where a user selects a `device_class` (like creating a template sensor).
There are two classes related to tVOC (https://www.home-assistant.io/integrations/sensor#device-class):
![image](https://github.com/user-attachments/assets/1fc07438-2463-4bc2-bbd2-be1ba998721d)
But the 2nd class has a short name which is same as the 1st - check this here: https://github.com/home-assistant/core/blob/b1470fd9b8b7fe78589f58eb6f4ed4de62591bb1/homeassistant/components/sensor/strings.json#L267
which causes a confusion.

**Comment by NoRi2909** [comment]
Thanks @ildar170975 for digging deeper on this!

So we simply  need a separate short name for the second and replace all  references to the first.

The first needs no addendum as it is measured in µg/m³ like all other concentrations (PM1, PM2.5, PM10, NO₂, NO, NOₓ, SO₂, ozone). The second is in ppm/ppb which are only used for CO and CO₂ as well.

I suggest we pick `VOC particles`

So the first step is to replace the the occurrences in the Sensor component:

https://github.com/home-assistant/core/blob/b1470fd9b8b7fe78589f58eb6f4ed4de62591bb1/homeassistant/components/sensor/strings.json#L267

      "VOC particles"

https://github.com/home-assistant/core/blob/b1470fd9b8b7fe78589f58eb6f4ed4de62591bb1/homeassistant/components/sensor/strings.json#L46

      "Current {entity_name} volatile organic compounds particle concentration"

https://github.com/home-assistant/core/blob/b1470fd9b8b7fe78589f58eb6f4ed4de62591bb1/homeassistant/components/sensor/strings.json#L96

     "{entity_name} volatile organic compounds particle concentration changes"


On top of that there are the same wrong references in these four integrations where we can file bugs / PRs on top of that:

https://github.com/home-assistant/core/blob/9bf0cbd65937f9cf7abdd08a8e7c81972c52a0c8/homeassistant/components/random/strings.json#L128

https://github.com/home-assistant/core/blob/9bf0cbd65937f9cf7abdd08a8e7c81972c52a0c8/homeassistant/components/scrape/strings.json#L185

https://github.com/home-assistant/core/blob/9bf0cbd65937f9cf7abdd08a8e7c81972c52a0c8/homeassistant/components/sql/strings.json#L117

https://github.com/home-assistant/core/blob/9bf0cbd65937f9cf7abdd08a8e7c81972c52a0c8/homeassistant/components/template/strings.json#L334

All four above need to be changed to:

     "[%key:component::sensor::entity_component::volatile_organic_compounds_parts::name%]"


All of those are Core issues which need 5 separate bug reports or PRs as they are filed per component.
@ildar170975 can you do the PRs on those?

**Comment by NoRi2909** [comment]
For the German front-end the bug is now fixed as I replaced the Sensor entry with "VOC-Parts" and changed the four other to reference the first:

![Screenshot 2024-10-28 07 54 59](https://github.com/user-attachments/assets/55b9b62f-8013-443e-9256-b9fad8f5f9a8)

When the necessary changes in the five Core components trickle in we can simply mark them as "verified" without any further changes in Lokalise for German.

**Comment by ildar170975** [comment]
@NoRi2909 
> can you do the PRs on those?

I am very limited in time with access to PC. Besides, do not filly understand a purpose of each line...
