### ISSUE TITLE
WLED preset entity generates "Option is not valid..." error

### ISSUE THREAD

**Issue by esand** [home-assistant/frontend#22554]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have a tile card for my WLED presets. If I visit the dashboard with that card when WLED is on, leave it open in my browser, then revisit the browser after WLED has been turned off, I get an error logged saying "Option is not valid for entity select.wled_soundreactive_preset, valid options are: ...".

### Describe the behavior you expected

The UI shouldn't generate an error when refreshing information for WLED presets; it's as if it's attempting to set the preset and causes the error.

### Steps to reproduce the issue

1. Open HA in your browser in a tab/window
2. Have a tile card with the WLED preset entity in your current dashboard
3. Turn on WLED and have a preset enabled
4. Hide the browser tab/window, or just switch away from it
5. Have WLED turn off with an automation/automatically/another device
6. Revisit the HA browser tab/window - error will be generated 

### What version of Home Assistant Core has the issue?

2024.10.3

### In which browser are you experiencing the issue with?

Edge Version 130.0.2849.56 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

### Problem-relevant frontend configuration

```yaml
features:
  - type: select-options
type: tile
entity: select.wled_soundreactive_preset
hide_state: false
name: LED's Preset
```

### Additional information

I believe the issue happens because when the WLED device is turned off, the presets entity enters an "unknown" state. When the tab/window is revisited, it's as if the UI attempts to push the last preset state to the WLED device, but it doesn't work since WLED is off and it generates the error.

**Comment by karwosts** [comment]
Could be related #21459

**Comment by esand** [comment]
> Could be related #21459

Sounds like it's exactly that issue. I assume I should close this issue and follow that other one?

**Comment by karwosts** [comment]
Yeah I think that's the reasonable approach.

**Comment by esand** [comment]
https://github.com/home-assistant/frontend/issues/21459
