### ISSUE TITLE
Opentherm entities disappeared all from the default Lovelace after upgrading

### ISSUE THREAD

**Issue by hdehaseleer** [home-assistant/frontend#22572]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I'm using the OTGW integration for a long time. 
I recently updated everything of HA.  And after this upgrade, ALL the entities of OTGW were removed from the area “CV” in my default Lovelace interface.  
OK: In the history, I can still see all the "OTGW entities" and the values are still changing = the integration still works.
KO: But all the “OTGW entities” were automatically removed from the Lovelace interface. 
KO: I created a new area and moved the "OTGW entities" to this new area.  But the new area remains empty. 
KO: I moved some "OTGW entities" to an existing area -> they are not shown in this existing area.
OK: Moving other existing entities from area 1 to area 2 still works.

Problem: after the upgrade, all existing “OTGW entities”  were automatically removed from the Lovelace interface. And I cannot add them again to an area of the Lovelace interface.
What can I do?

### Describe the behavior you expected

OTGW enities should be visible in my default Lovelace interface

### Steps to reproduce the issue

1. I created a new area "OT - Boiler"
2. I moved an existing, non-otgw, entity to this new area "OT - boiler" -> this entity becomes visible.
3. I moved an OTGW entity to this new area "OT - boiler" -> this entity (entities) becomes NOT visible

### What version of Home Assistant Core has the issue?

Latest 10.4

### What was the last working version of Home Assistant Core?

Eveything still ok with 2024.3.3

### In which browser are you experiencing the issue with?

Firefox and Edge and ?

### Which operating system are you using to run this browser?

Latest MS 11

**Comment by karwosts** [comment]
Looks like maybe a significant change went into Opentherm: https://github.com/home-assistant/core/pull/124869

If you look at the opentherm device, are the entities you're looking for categorized as diagnostic? Diagnostic entities are intentionally not added to autogenerated dashboards. Or are they maybe set as hidden?

**Comment by hdehaseleer** [comment]
Thanks for your response.

I don’t know where I can see “categorized as diagnostic”
Most of the OT entities are (since long) disabled, because they have no value or are unavailable.  
This is screenshot 1 of the modulation ratio.  This entity is not hidden and is not disabled. The value changes.  But the entity (and all others) is not shown in Lovelace.
![Screenshot 1](https://github.com/user-attachments/assets/1918e57c-f7b4-4a4f-8c04-75dd5dd3ffc6)

 And screenshot 2  of the “settings”
![Screenshot2](https://github.com/user-attachments/assets/cf25ddee-da58-4064-8b2d-e1383d3206fb)

**Comment by karwosts** [comment]
> I don’t know where I can see “categorized as diagnostic”

It's on the device page. 

![image](https://github.com/user-attachments/assets/c3998dc8-8546-42f8-9249-5f3f9b235671)

**Comment by hdehaseleer** [comment]
Thank you.

Indeed, in the other integrations the entities are in "sensors". In the 3 OTGW devices, all is in diagnostics.  See screenshot.
How can I change this? 
As you can see in the screenshot, I cannot add them to the "default" view of my Lovelave.  Because I have no views. 
And when I try to create a new view, I receive the warning that new entities will no longer automatically be added to my Lovelace interface.  This makes me uncomfortable to start creating a view.
![{CC1A5A24-DB34-439C-A4DC-8ABD55C3F6A4}](https://github.com/user-attachments/assets/a9070d09-3dda-45d9-b074-9a3647db386a)

**Comment by karwosts** [comment]
There's nothing you can do as an end user. If you want to use the autogenerated dashboard, you're stuck living with its constraints, which is that diagnostic sensors are not added.

If you want to see these on a dashboard, you'll have to leave the auto dashboard behind and start learning how to make your own dashboards. 

You don't have to worry about breaking anything by experimenting, as you can always return back to an autogenerated dashboard easily if you want. But yes once you take control of managing a dashboard, it will no longer add new things for you.
