### ISSUE TITLE
No Cards displayed when I attempt to add a new element to a dashboard

### ISSUE THREAD

**Issue by sabolcik** [home-assistant/frontend#22582]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have found that when I try to add a new user interface card to a dash board the card view is empty.

See the screenshot below.  I rolled back to a backup using core 10.1 and the issue is not present.  Once I try my backup from core 10.2 the issue is present.

I tried deleting every card from both HACS and my custom repositories and it didn’t resolve the issue.  I also tried emptying my configuration.yaml file without any change to the behavior.
![IMG_5169](https://github.com/user-attachments/assets/3dd6a54a-567c-4130-818a-bff533b687a2)

### Describe the behavior you expected

Normally I see the list of all UI cards I can select.

### Steps to reproduce the issue

1. Happens everytime I boot
2.
3.
...

### What version of Home Assistant Core has the issue?

10.4

### What was the last working version of Home Assistant Core?

10.1

### In which browser are you experiencing the issue with?

Edge

### Which operating system are you using to run this browser?

Windows 11

**Comment by ildar170975** [comment]
> ### What was the last working version of Home Assistant Core?
> 
> 10.1
> ### In which browser are you experiencing the issue with?
> 
> Edge

Are you sure? Seems to be a mobile based on a scrrenshot.

**Comment by sabolcik** [comment]
I’ve tried on my mobile, edge, Firefox, and chrome.  Same behavior across
the board.

**Comment by karwosts** [comment]
Could be this bug: https://github.com/home-assistant/frontend/pull/22549

Any errors in browser console?

**Comment by sabolcik** [comment]
It certainly could be.  I’ll check the browser console.

**Comment by sabolcik** [comment]
I haven't done much website console debugging, but here is a dump of the console log.  I see several UI add ons that weren't found that I can try to correct.  I had an issue where I had installed some items prior to having HACS installed and that were duplicated.  In trying to debug the issue I removed any manually installed resources and reinstalled them through HACS.  I suspect that is causing the missing items in the log file.

Would appreciate any feedback on the log file that would aid in the debug.

[si18nwqe6ire4pkuwbs9owznwuvwmpj2.ui.nabu.casa-1730219883836.log](https://github.com/user-attachments/files/17560331/si18nwqe6ire4pkuwbs9owznwuvwmpj2.ui.nabu.casa-1730219883836.log)

**Comment by karwosts** [comment]
```
compute-unused-entities.ts:34  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'entity')
    at r (compute-unused-entities.ts:34:14)
    at compute-unused-entities.ts:53:38
    at Array.forEach (<anonymous>)
    at n (compute-unused-entities.ts:53:18)
    at compute-unused-entities.ts:59:33
    at Array.forEach (<anonymous>)
    at n (compute-unused-entities.ts:59:15)
    at compute-unused-entities.ts:68:39
    at Array.forEach (<anonymous>)
    at n (compute-unused-entities.ts:68:18)
```

Yep looks like the other issue I fixed. I will close this, it will be fixed in the next release.

**Comment by sabolcik** [comment]
Thank you!
