### ISSUE TITLE
Much too high Values for Homematic Sensors in Energy Dashboard

### ISSUE THREAD

**Issue by RamsukKockoi** [home-assistant/frontend#22584]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In my Energy Dashboard I have two values that are much to high, to be correct. One for example is 13.916.12 kWh for one day, for a fridge, that usually needs about 1kWh a day. Strange is, that "not recorded comsumption" has an almost similar value in the same time. 
I tried to delete that value, but without success, as I can not directly find it in the database. So i tried to delete the timespan, it occurs. 
If it occurs on 29.09.24 in 9-10 o clock, I can delete this timepsan an TADAA ist away, but second TADAA the wrong value went to one hour later! Now it is 10-11 o clock. If I delte that also, the error goes to 11-12. And so on.

These values are not in the statistics of the sensor. They are only in the Energy Dashboard.
![EnergyDashboard](https://github.com/user-attachments/assets/7cfa0319-a9ae-42a6-9e04-56484c3e912a)

### Describe the behavior you expected

I expect the correct values in the energy dashboard.

### Steps to reproduce the issue

I can not reproduce it. Its two wron values.

### What version of Home Assistant Core has the issue?

2024.10.4 and before

### What was the last working version of Home Assistant Core?

2024.8.x there it occoured for first time

### In which browser are you experiencing the issue with?

Chrome, Edge, in the Android an iOS Apps

### Which operating system are you using to run this browser?

Windows 10 22H2 19045.4894

### State of relevant entities

```txt
state_class: total_increasing
model_type: HMIP-PSM
connection_type: HMIP_RF
rssi_device: -70
rssi_peer: -69
id: 3014F711A00001DD89A44ECB
is_group: false
unit_of_measurement: kWh
device_class: energy
friendly_name: PR Kühlschrank Akt.

-

state_class: total_increasing
model_type: HMIP-PSM
connection_type: HMIP_RF
rssi_device: -40
rssi_peer: -45
id: 3014F711A00001DD89A452AF
is_group: false
unit_of_measurement: kWh
device_class: energy
friendly_name: Shield akutell
```

### Problem-relevant frontend configuration

```yaml
Its the Energy Dashboard, I do not know how to see it in YAML
```

### Javascript errors shown in your browser console/inspector

```txt
./.
```

### Additional information

I needed to migrate HAS from Docker to VM. Unfortunately I migrated it a second time from VM to Raspi5. I do not know the exact days, but the timespan seems to correlate with the error.

**Comment by RamsukKockoi** [comment]
Could you please decribe a little more how to use adjust-sum?

**Comment by karwosts** [comment]
Easiest thing to do is find your statistic, click adjust, click on the `Outliers` button, and see if you see a datapoint of ~13,000kWh. 

Click on it to adjust, and change it to 0. 

Should fix the graph AFAIK.

**Comment by RamsukKockoi** [comment]
Perfect, trying to find it. Thanks for the great help!

**Comment by RamsukKockoi** [comment]
That worked really good for me! Thank you very much!
