### ISSUE TITLE
Cloud Settings TTS: `ui::dialogs::tts-try::message` does not show up localized

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22605]
### Describe the issue you are experiencing

For Settings > Home Assistant Cloud > Text-to-speech > Try
the label "Message" is available in `ui::dialogs::tts-try::message`

https://github.com/home-assistant/frontend/blob/744cda39747b834277796fb4cdcb5d0f3f3d88d8/src/translations/en.json#L1706-L1708

but it does not show up in the user's language:

![Screenshot 2024-10-31 09 51 05](https://github.com/user-attachments/assets/200a8537-01ec-4b39-94d8-295cb66e71f1)

Tried in other languages, too.

### What version of Home Assistant Core has the issue?

2024.11.0b0

**Comment by silamon** [comment]
Is this related to https://github.com/home-assistant/frontend/issues/22442?

**Comment by NoRi2909** [comment]
Oh yes, I wrote so many bug reports in the last weeks regarding missing translations that I overlooked my own duplicate.

Sorry about that …

**Comment by silamon** [comment]
No problem.
