### ISSUE TITLE
No way to remove the ZBT-1 from Home Assistant

### ISSUE THREAD

**Issue by blueJack92** [home-assistant/frontend#22602]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have removed the ZBT-1 from my Home Assistant Green, but the entry for the ZBT-1 is still displayed under System > Hardware.
I cannot find a way to remove it.

### Describe the behavior you expected

It should also be possible to remove the device via this menu item.

### Steps to reproduce the issue

1. connect the ZBT-1 to the Home Assistant Green.
2. remove the ZBT-1.

### What version of Home Assistant Core has the issue?

2024.10.4

### In which browser are you experiencing the issue with?

Microsoft Edge 130.0.2849.56

### Which operating system are you using to run this browser?

Windows 11

**Comment by silamon** [comment]
Open an issue at https://github.com/home-assistant/supervisor/issues

**Comment by critical-tinkerer** [comment]
Same problem for me.

I built an external Thread Border Router (TBR) and was struggling to get it working so I installed a ZBT-1 USB stick in my HA Yellow.

I then worked out what the problem was with my external TBR and removed the ZBT-1.

Since then, it has been showing under hardware even though it is no longer installed in my HA Yellow.

**Comment by blueJack92** [comment]
I still have the problem. Please add the possiblity to remove an entry in "System > Hardware".
