### ISSUE TITLE
Roborock Integration: "Water Tank Empty" event

### ISSUE THREAD

**Issue by RBF-Martin** [home-assistant/frontend#22608]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Roborock Integration does not fire the docking stations event "water tank empty" .

### Describe the behavior you expected

The last boolean sensor in the Diagnose Panel should change and indicates an error. 
If this is not the correct sensor, the "water tank empty" entity/attribute is not implemented then.

### Steps to reproduce the issue

1. Drain your water tank
2. Roborock app will trigger the status 
3. HA.RoborockIntegration will not 

### What version of Home Assistant Core has the issue?

2024.10.4

### What was the last working version of Home Assistant Core?

2024.10.4

### In which browser are you experiencing the issue with?

Chrome

### State of relevant entities

```txt
Roborock Model: Qrevo Master
```

**Comment by silamon** [comment]
Open an issue at https://github.com/home-assistant/core/issues.
