### ISSUE TITLE
Nordpool device stop working

### ISSUE THREAD

**Issue by janiri85** [home-assistant/frontend#22607]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Nordpool device stop working and cannot add new nordpool device

### Describe the behavior you expected

Nordpool device stop working and cannot add new nordpool device.
i try delete the device and reinstall but nothing work.

### Steps to reproduce the issue

1. install nordpool
2. add new nordpool device

### What version of Home Assistant Core has the issue?

core-2024.11.0b0

### What was the last working version of Home Assistant Core?

core-2024.10.4

**Comment by silamon** [comment]
Open an issue at https://github.com/home-assistant/core/issues.
