### ISSUE TITLE
304 error on external companion app

### ISSUE THREAD

**Issue by Tan-tan-san** [home-assistant/frontend#22619]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Im trying to access my HAOS instance externally through an nginx proxy or web browser. This had worked previously, but is now no longer. I get a flurry of 304 errors and a retry countdown. Im using an iphone with the latest companion app and I've also tested it with the Brave mobile browser as well as Safari. When I login locally, I get the login screen, enter my OTP and then it does the retry countdown. If I access the instance by ip:port it works fine. I even get motion sensor alerts with video that streams via that same url, but I cant login to the app.

nginx logs:
```
08.147.176.66 - - [31/Oct/2024:20:38:32 +0000] "GET /api/websocket HTTP/1.1" 400 66 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2024.9.4 (io.robbie.HomeAs │
│ 108.147.176.66 - - [31/Oct/2024:20:38:32 +0000] "GET /frontend_latest/61060.jwthtMMtY2k.js HTTP/1.1" 304 0 "https://hass.doin.science/lovelace?external_auth=1" "Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit │
│ 108.147.176.66 - - [31/Oct/2024:20:38:32 +0000] "GET /frontend_latest/51431.if81ZRuVsH0.js HTTP/1.1" 304 0 "https://hass.doin.science/lovelace?external_auth=1" "Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit │
│ 108.147.176.66 - - [31/Oct/2024:20:38:32 +0000] "GET /frontend_latest/17590.c2vGM5vb47w.js HTTP/1.1" 304 0 "https://hass.doin.science/lovelace?external_auth=1" "Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit │
│ 108.147.176.66 - - [31/Oct/2024:20:38:32 +0000] "GET /frontend_latest/81625.Vy_yMeE9hfw.js HTTP/1.1" 304 0 "https://hass.doin.science/lovelace?external_auth=1" "Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit │
│ 108.147.176.66 - - [31/Oct/2024:20:38:32 +0000] "GET /frontend_latest/66419.ZexNGgQFfa0.js HTTP/1.1" 304 0 "https://hass.doin.science/lovelace?external_auth=1" "Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit │
│ 108.147.176.66 - - [31/Oct/2024:20:38:32 +0000] "GET /frontend_latest/73767.j54A6gg-wzE.js HTTP/1.1" 304 0 "https://hass.doin.science/lovelace?external_auth=1" "Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit │
│ 108.147.176.66 - - [31/Oct/2024:20:38:32 +0000] "GET /frontend_latest/3051.XrHQrxNifT8.js HTTP/1.1" 304 0 "https://hass.doin.science/lovelace?external_auth=1" "Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit/ │
│ 108.147.176.66 - - [31/Oct/2024:20:38:32 +0000] "GET /frontend_latest/71893.bfoVWJ-tO4g.js HTTP/1.1" 304 0 "https://hass.doin.science/lovelace?external_auth=1" "Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit 
```

### Describe the behavior you expected

The companion app to get to the login screen then show my dashboard after logging in.

### Steps to reproduce the issue

1. Cell connection on mobile
2.Open companion app
3. Can't connect to instance

1. go to external url on internal network(dns resolves it)
2. login screen comes up, login and put in OTP
3. countdown retry with 304 errors on ingress
...

### What version of Home Assistant Core has the issue?

2024.10.4

### What was the last working version of Home Assistant Core?

2024.10.4

### In which browser are you experiencing the issue with?

Version 1.71.121 Chromium: 130.0.6723.91 (Official Build) unknown (64-bit)

### Which operating system are you using to run this browser?

iOS 18.1, 6.6.54-2-MANJARO (64-bit), latest MacOS, iPad OS

### Problem-relevant frontend configuration

```yaml
k8s ingress manifest snippet. I have the nginx ingress controller proxying the traffic to a dedicated raspberry pi running HAOS.

nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/server-snippets: |
      location /api/websocket {
       proxy_set_header Upgrade $http_upgrade;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-Host $http_host;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_set_header Host $host;
          proxy_set_header Connection "upgrade";
          proxy_cache_bypass $http_upgrade;
```

**Comment by silamon** [comment]
This isn't related to anything this issue tracker is for. I would suggest to start of on the community forums: 
https://www.home-assistant.io/help/
