### ISSUE TITLE
Dialog Form (Create Number, Create Text) issue

### ISSUE THREAD

**Issue by alxhander** [home-assistant/frontend#22628]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Recently i create one new Virtual Machine in my proxmox server with Home Assistant OS. In this same server i have another HA instance create weeks ago. Both VMs are running the same version.

When creating Number or Text helper, the dialog box doesn't show all options in my new instance. In the old instance everything is all right.

### Describe the behavior you expected

expected to see the options to create text/number helper
![Screenshot 2024-11-01 160833](https://github.com/user-attachments/assets/17b79fa6-177a-4a78-a4bd-f65e6ec2922d)
![Screenshot 2024-11-01 160851](https://github.com/user-attachments/assets/c05d19f2-2d82-428f-b187-dfb5dde3a17a)
![Screenshot 2024-11-01 160926](https://github.com/user-attachments/assets/7fefd9b1-9cf8-416a-8844-0f0740c99d31)
![Screenshot 2024-11-01 160947](https://github.com/user-attachments/assets/0eab20b1-9788-49e0-a242-13b538fd6f46)

### Steps to reproduce the issue

1. Settings
2. Helpers
3. Create Helper
4. Text

### What version of Home Assistant Core has the issue?

2024.10.4

### In which browser are you experiencing the issue with?

Google Chrome 130.0.6723.70 - 64 bits, MS Edge Version 130.0.2849.56 (64-bit)

### Which operating system are you using to run this browser?

Win10, Win11

**Comment by ildar170975** [comment]
Not sure but may be one of your i ranches does not have “Advanced mode” checkbox set.

**Comment by alxhander** [comment]
> Not sure but may be one of your instances does not have “Advanced mode” checkbox set.

I am really sorry guys, it was my mistake. There is really an option called "Advanced Mode" and i forgot to turn it on. Thanks!
