### ISSUE TITLE
Fails to load logs of not-running addon

### ISSUE THREAD

**Issue by tjorim** [home-assistant/frontend#22641]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Rnning Core 2024.11.0b2, Supervisor 2024.10.4, Operating System 13.2 and Frontend 20241031.0. When I try to open add-on logs from settings > system > logs and select an add-on that's not running it keeps loading: "Loading full log…". After a while it will report an error.
![Screenshot_20241103-093416](https://github.com/user-attachments/assets/e6945151-7280-4047-84aa-95cf98796928)

### Describe the behavior you expected

Just tell me add-on is not running and/or no logs are available.

### Steps to reproduce the issue

1. Go to logs in settings 
2. Choose an add-on that is not running 
3. Wait and see the error
...

### What version of Home Assistant Core has the issue?

core-2024.11.0b2

### In which browser are you experiencing the issue with?

Google Chrome and Android Companion App

### Which operating system are you using to run this browser?

Windows and Android

**Comment by tjorim** [comment]
First a warning:
`The FetchEvent for "https://x.y.z/api/hassio/addons/core_silabs_flasher/logs/follow?lines=100" resulted in a network error response: the promise was resolved with an error response object.`
then an error:
`GET https://x.y.z/api/hassio/addons/core_silabs_flasher/logs/follow?lines=100 net::ERR_FAILED`

**Comment by wendevlin** [comment]
@tjorim can you please check which endpoint is used to download the logs and what error code is thrown?

**Comment by tjorim** [comment]
I also noticed once the add-on was run (once, e.g. after reboot, but stopped again) the logs will load in the settings>system>logs (but not on the add-on page logs tab, probably resolved by open PR).

**Comment by tjorim** [comment]
First a warning:
`The FetchEvent for "https://x.y.z/api/hassio/addons/core_silabs_flasher/logs/follow?lines=100" resulted in a network error response: the promise was resolved with an error response object.`
then an error:
`GET https://x.y.z/api/hassio/addons/core_silabs_flasher/logs/follow?lines=100 net::ERR_FAILED`

**Comment by wendevlin** [comment]
This should be fixed with Supervisor 2024.11.2
