### ISSUE TITLE
Automations: If/Then - "Else" action creates error after drag and drop

### ISSUE THREAD

**Issue by JpsCrazy** [home-assistant/frontend#22660]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Dragging and dropping an action into the 'Else' portion if an If/Then building block causes errors.
The action disappears visually. Attempting to save produces the below error. The YAML includes an erroneous `- null` line which when removed corrects the error. This does NOT occur for the 'Then' portion of the building block.

`Message malformed: expected dictionary @ data['actions'][0]['choose'][2]['sequence'][0]['else'][0]`

### Describe the behavior you expected

To be able to drag actions into the "Else" portion of If/Then building blocks without `- null` being inserted in the YAML

### Steps to reproduce the issue

1. Create If/Then building block in an Automation and click "Add Else"
2. Create an action outside of the Automation
3. Attempt to drag the action into the "Else" portion of the block
4. Attempt to save to have the error shown. 
5. Edit the YAML to remove the `- null` line to correct the issue.
6.
...

### What version of Home Assistant Core has the issue?

2024.10.4

### In which browser are you experiencing the issue with?

Google Chrome 130.0.6723.92

### Which operating system are you using to run this browser?

Windows 11

**Comment by wendevlin** [comment]
Hi @JpsCrazy,
This is fixed with https://github.com/home-assistant/frontend/pull/22291

Will be released today.
