### ISSUE TITLE
Tuya: "missing" Attribute to see is "heating" or not

### ISSUE THREAD

**Issue by berndthiel** [home-assistant/frontend#22680]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

in Tuya app you see a "flame" symbol which is a sign that it open the motor to heat
in HA-Tuya you dont have this information, you see "heat_cool/off" which is "on/off"
how can i get this information in and rename "heat_cool" to "on" ?

### Describe the behavior you expected

how can i get this information in and rename "heat_cool" to "on" ?

### Steps to reproduce the issue

open Tuya App, set e.g. 21° by current 19° it shows a "flame" symbol
in HA when you have a thermostate from Tuya Devices you dont have this "flame" symbol, cause "heat_cool" only means "on" and not that it is real heating.

### What version of Home Assistant Core has the issue?

2024.10.4

### What was the last working version of Home Assistant Core?

2024.10.4

**Comment by karwosts** [comment]
Having a hard time understanding what you're asking, but anything _specific_ to the Tuya integration is most likely going to need to be an issue for home-assistant/core, not frontend.

**Comment by berndthiel** [comment]
> Having a hard time understanding what you're asking, but anything _specific_ to the Tuya integration is most likely going to need to be an issue for home-assistant/core, not frontend.

@karwosts simple explained in the HA-TUYA Integration is one important attribute missing which show is thermostate heating or not ... the heat_cool is in real "on" which doesnt mean it is heating so opening the floor heating cycle motor

**Comment by silamon** [comment]
You can open an issue at https://github.com/home-assistant/core towards the tuya integration as mentioned before.
