### ISSUE TITLE
Labels List from Settings Dashboard Doesn't Filter Entities and Devices by Label

### ISSUE THREAD

**Issue by ttreker** [home-assistant/frontend#22683]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Under the Settings dashboard under Labels if you click the three-dot menu for a Label and select either Entities or Devices the Entities and Devices list will come up without being filtered for that Label. If you select Automations from this menu the Automations list does come up filtered.

In all three cases an URL with a query string comes up but in only the latter case does this query actually set the filters.

This brings up a broader related issue that is likely related:

When filtering was first implemented the filter appeared in the query string when you filtered a list (this is as I remember it anyways as I copied this URL to use in Navigate Buttons). Now it doesn't. I suspect this is due to fixing the issue of keeping persistent filtering which was an initial problem with filtering when it was first introduced and was addressed the following month I believe. Anyway, being able to use an URL with a filter query is very helpful as buttons can be used to navigate to this URL setting the filtering at the same time. It seems to me it should be able to use a query URL to set the filter but still keep that filter persistent if there is no query portion to the URL.

### Describe the behavior you expected

Either Entities or Device list filtered by the Label whose three-dot menu was used to select Entities or Device.

### Steps to reproduce the issue

1. Go to Settings Dashboard
2. Select Areas, Labels, Zones
3. Select Labels
4. At the end of an arbitrary existing Label select either Entities or Devices from the the Label's three-dot menu.

The resulting list will not be filtered by the Label. If instead you choose Automations from the three-dot menu the Automations list will be filtered.

### What version of Home Assistant Core has the issue?

2024.10.4

**Comment by wendevlin** [comment]
This will be fixed with the todays release.

https://github.com/home-assistant/frontend/pull/22447
