### ISSUE TITLE
Backups: List view broken in recent betas, column headers missing

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22698]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The column headers in the Backups list are broken in the recent betas:

![image](https://github.com/user-attachments/assets/ed4ed743-e3a4-4cf4-bc4a-33c9ca6976c4)

### Describe the behavior you expected

There should be the column headers and corresponding menu items in the Sort by menu.

### Steps to reproduce the issue

Go to https://my.home-assistant.io/redirect/supervisor_snapshots/

It looks like some race condition because on 1 out of 5 reloads the column headers come back.
But on subsequent reloads they disappear again.

But only when I go via HA cloud, for the direct local connection this race condition always results in a broken column header. Also tried on mobile: Enter the view: column headers missing. Leave it, reenter: Columns back.

I cannot trigger the same problem on any other list view like devices or entities, e.g.

### What version of Home Assistant Core has the issue?

core-2024.11.0

### What was the last working version of Home Assistant Core?

core-2024.10.xx

### In which browser are you experiencing the issue with?

Google Chrome Version 131.0.6778.29 beta (64-Bit)

### Which operating system are you using to run this browser?

Chrome OS

**Comment by wendevlin** [comment]
Hello @NoRi2909,
Which supervisor version do you have? Can you try to clear your browser cache and try again?

**Comment by NoRi2909** [comment]
Hello @wendevlin,
I went through all the betas where I already noticed that, now at Supervisor 2024.11.2.

Clearing the cache does not make a difference.

As I wrote I also have the same bug in the Android app:

![Screenshot_20241107-150159](https://github.com/user-attachments/assets/52075ac9-e019-469d-a551-a816cfc2d517)

The difference for me is just whether it's local on the LAN: always broken.
Or via Nabu Casa Cloud where it changes from OK to broken on every few retries or reloads:

![Screenshot_20241107-150500](https://github.com/user-attachments/assets/2522cb30-427d-4f7b-b350-ccc984397584)

**Comment by NoRi2909** [comment]
Here the same on desktop via Nabu Casa Cloud:

First load:

![Screenshot 2024-11-07 15 16 56](https://github.com/user-attachments/assets/0b240073-af9c-4011-ba71-9c7db54bbe8c)

Reload:

![Screenshot 2024-11-07 15 17 05](https://github.com/user-attachments/assets/4c7a6e8c-44db-4521-a762-fd025032c1d5)

Two reloads later back to the first screenshot.

**Comment by wendevlin** [comment]
Thank you, I can reproduce it and will find a solution.

**Comment by michaelarnauts** [comment]
Not sure if it's the same issue, but I also can't seem to remove multiple backups anymore. No remove button appears when selecting multiple backups.

**Comment by NoRi2909** [comment]
The new Backups UI in 2025.1.0 no longer has this issue.
