### ISSUE TITLE
SOLVED: after 2024.11 update in Chrome, Error while loading page lovelace and others

### ISSUE THREAD

**Issue by donburch888** [home-assistant/frontend#22703]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I just did the HAOS 2024.11 update, and when it rebooted my Chrome browser stated `Error while loading page.`

Firefox works OK; and in the Core Log, the only new error message is: 
```
Logger: homeassistant.components.hassio.issues
Source: components/hassio/issues.py:302
integration: Home Assistant Supervisor (documentation, issues)
First occurred: 9:02:16 am (1 occurrences)
Last logged: 9:02:16 am

Could not get suggestions for supervisor issue 32864ba8ffca4452a629006cf53739f0, skipping it
```
but despite pointing the finger at Supervisor, there are only INFO messages in the Supervisor log. 

I have updated my Ubuntu and rebooted to make sure I have latest browsers.
I have checked Chrome settings, and found only that Google have re-enabled the Ad tracking settings that I always turn off.  I use Firefox as my usual browser, so no extensions in Chrome.

After clearing Chrome's browsing history and another HA reboot - the left-hand menu appears, reset - but the other pages still "Error while loading page". No not quite ... some pages do show in the main window (Logbook, History, calendar, ESPHome, File Editor, HACS, Music Assistant, Node-RED, terminal and Developer Tools) but NOT Profile, Settings, To-do List, Media, Energy, Map or Lovelace. 

### Describe the behavior you expected

The same as it did yesterday ... browser shows lovelace display on Chrome, as it still does on Firefox.

### Steps to reproduce the issue

1. Update to 2024.11.0
2. set your Chrome browser to refresh the page you were previously looking at

### What version of Home Assistant Core has the issue?

Core 2024.11.0 Supervisor 2024.11.2 Operating System 13.2 Frontend 20241106.0

### What was the last working version of Home Assistant Core?

2024.10

### In which browser are you experiencing the issue with?

Chrome on linux:  Version 130.0.6723.116 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Ubuntu 22.04.5 LTS

**Comment by DarthGaymer** [comment]
I am experiencing the same issue with the iOS Companion app version 2024.9.4 on iOS 18.1 after updating to 2024.11.  Restarting the device and closing/reopening the app does not resolve the issue.

**Comment by haroldboom** [comment]
> I am experiencing the same issue with the iOS Companion app version 2024.9.4 on iOS 18.1 after updating to 2024.11. Restarting the device and closing/reopening the app does not resolve the issue.

I have the same issue but only on one of my devices (iPhone 13)

**Comment by DarthGaymer** [comment]
> > I am experiencing the same issue with the iOS Companion app version 2024.9.4 on iOS 18.1 after updating to 2024.11. Restarting the device and closing/reopening the app does not resolve the issue.
> 
> I have the same issue but only on one of my devices (iPhone 13). I can access the side menu and load my addons EVCC, Frigate etc but nothing on HA works except the companion app settings


You’re getting farther than me. I could not access either the side bar or the companion app settings. Was forced to rollback to 2024.10.4 to get everything working again.

**Comment by henrikbla** [comment]
I am experiencing this on one of the two iPhone devices in my household since HA 2024.11. The iPhone with iOS 18.1 seems to work fine (so far at least), but the one with iOS 17 gives this error. Have not tried reinstall yet, though.

**Comment by Anteus** [comment]
Force closing the app, and quickly tapping the settings cog in the lower right corner while opening the app then enter debugging settings and clear frontend cache fixed it for me.

**Comment by henrikbla** [comment]
> Force closing the app, and quickly tapping the settings cog in the lower right corner while opening the app then enter debugging settings and clear frontend cache fixed it for me.

Thanks, this did the trick for me as well.

**Comment by donburch888** [comment]
I **had already** used Chrome's Settings > Privacy and security > Delete browsing Data, and it got the sidebar back. 
After these last comments I tried again, and noticed Chrome defaulted to Time range of "Last Hour".  Changing this to "All Time" and [Delete Data] appears to have got full functionality back. Fortunately I only use Chrome for HA, so clearing all cookies shouldn't affect my other browsing much.

Thus it does seem to have been completely a browser cache issue, and should be closed.  However I suspect most users don't look in githubs closed issues tab, so maybe better to leave this open for a little while longer.

**Comment by jwhb** [comment]
This fixed it for me:

`rm -rf ~/Library/Containers/io.robbie.HomeAssistant/Data/Library/Caches/*`

**Comment by dangelomda** [comment]
I cleaned the history navigation and cash and work for me.
