### ISSUE TITLE
Derivative Sensor: Missing translation of "decimals" label

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22712]
### Describe the issue you are experiencing

When setting up a Derivative sensor helper everthing is perfectly translated, except for the "decimals" label:

![Screenshot 2024-11-07 10 39 15](https://github.com/user-attachments/assets/c53e02f7-3751-46d4-9768-d21e86b31f4c)

### Describe the behavior you expected

This should be in the strings.

Note that this is quite longer in some translations, in German it becomes

    Dezimalstellen

so make sure the area expands to accommodate for that.

### What version of Home Assistant Core has the issue?

core-2024.11.0

**Comment by silamon** [comment]
This is provided by the derivative integration. You can open an issue at https://github.com/home-assistant/core.

**Comment by NoRi2909** [comment]
@silamon Thanks!

> This is provided by the derivative integration. You can open an issue at https://github.com/home-assistant/core.

Done: https://github.com/home-assistant/core/issues/130302
