### ISSUE TITLE
Missing period in Beta channel warning

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22720]
### Describe the issue you are experiencing

There is a period missing at the end of the first sentence here:

![Screenshot 2024-11-07 14 25 34](https://github.com/user-attachments/assets/d510eece-84fc-4c90-ba1c-bd8988921c6e)

https://github.com/home-assistant/frontend/blob/2d8fbc652f481b1db2d6fb4cc1831e00e162767a/src/translations/en.json#L1697

### What version of Home Assistant Core has the issue?

core-2024.11.0

**Comment by wendevlin** [comment]
@NoRi2909 FYI, this needs to be merged into supervisor and released there, so it could take a while that you see the fix.

**Comment by NoRi2909** [comment]
@wendevlin No problem.

I just saw that much more often than regular because I spent most of the last weeks on the German translation.
