### ISSUE TITLE
Missing data since yesterday

### ISSUE THREAD

**Issue by markusklein01** [home-assistant/frontend#22742]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since yesterday no new prices are coming in. 

### Describe the behavior you expected

No issues in general, API key is uptodate. Any ideas?

### Steps to reproduce the issue

Reinstalled Tibber Integration

### What version of Home Assistant Core has the issue?

core

### What was the last working version of Home Assistant Core?

most recent

**Comment by karwosts** [comment]
This is not a frontend issue.
