### ISSUE TITLE
Home Assistant media browser is broken with >=2024.11

### ISSUE THREAD

**Issue by ivanjx** [home-assistant/frontend#22755]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

after my HA got updated to 2024.11 and 2024.11.1, frigate clips inside media browser does not play videos at all.

### Describe the behavior you expected

frigate clips can play.

### Steps to reproduce the issue

1. update HA to 2024.11 or later.
2. navigate to media browser -> frigate -> clips.
3. open a clip by clicking it.
4. clip never plays.

### What version of Home Assistant Core has the issue?

2024.11.1

### What was the last working version of Home Assistant Core?

2024.10.4

### In which browser are you experiencing the issue with?

firefox

### Which operating system are you using to run this browser?

ubuntu 24.04.1

**Comment by dermotduffy** [comment]
Possible theory which would suggest this is a HA frontend bug: https://github.com/blakeblackshear/frigate-hass-integration/issues/757#issuecomment-2466484128

**Comment by dermotduffy** [comment]
Despite "Frigate" being in the issue title, I suspect this impacts all users of the HA media browser.

**Comment by jtbnz** [comment]
On Click this is the error in the browser

ha-web-rtc-player.ts:159 Uncaught (in promise) 
{code: 'webrtc_get_client_config_failed', message: 'Camera does not support WebRTC, frontend_stream_type=hls'}
code
: 
"webrtc_get_client_config_failed"

message
: 
"Camera does not support WebRTC, frontend_stream_type=hls"

Also in the log is this line
        
       GET https://ha.local/webrtc/webrtc-camera.js?v=v3.5.2 net::ERR_ABORTED 404 (Not Found)


[1731462476083.log](https://github.com/user-attachments/files/17725005/1731462476083.log)

**Comment by dermotduffy** [comment]
@ivanjx If you still can, I'd recommend you re-title this issue "Home Assistant media browser is broken with `>=2024.11`" to try to increase the chances it gets noticed and the impact understood.

**Comment by seriousch** [comment]
Hi there,
This issue has a pretty big impact on folks using solutions like Frigate or others. We would very much appreciate any help in getting this fixed. I’m
Not familiar enough with the codebase to contribute directly, but if you need anything in terms of logs, repro steps or testing happy to do my best. Many thanks!

**Comment by ivanjx** [comment]
@dermotduffy would this work?

https://github.com/ivanjx/frontend/commit/0621e75e96a684f10eda0adf2b825794a2bffdb3

**Comment by steezeburger** [comment]
I just installed everything today for the first time, but I think I'm experiencing this same issue.
I've noticed that the url it's trying to get is `undefined` always

**Comment by kgiedrius** [comment]
same issue for me

**Comment by dermotduffy** [comment]
@ivanjx Something like that would probably work. I am not a HASS frontend maintainer though ;-) If you've tested this and it works, I'd go ahead and prepare a PR and wait for one of the maintainers to chime in.

**Comment by ivanjx** [comment]
i wanted to make a PR but i have no idea on how to attach the new frontend into my existing home assistant container

**Comment by Krutibhanu94** [comment]
Where is HA's configuration.yml file? I am unable to locate

**Comment by GrimSQL** [comment]
> Where is HA's configuration.yml file? I am unable to locate

When you open Studio Code Server in Home Assistant, it usually takes you directly to the folder with `configuration.yaml`. If you don’t see it, ensure you're in the correct folder.

If you don’t have Studio Code Server installed, you can add it via **Settings > Add-ons > Add-on Store** in Home Assistant. Search for _"Studio Code Server,"_ install it, and then start the add-on.

**Comment by jknoflook** [comment]
This fix needs to gain priority.

**Comment by dermotduffy** [comment]
@jknoflook This is already fixed. We're just waiting for a release.

**Comment by jknoflook** [comment]
I realize that. This is home security we are talking about, not a spelling error on a weather app. This should have been included in the release 2 days ago.

**Comment by D3v01dZA** [comment]
The known fix is to downgrade to 2024.10, nothing is forcing you to stay on .11
