### ISSUE TITLE
Enegy dashboard - Individual devices

### ISSUE THREAD

**Issue by mintgroen** [home-assistant/frontend#22754]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The data from the individual devices works, most of the time but every now and then everything is logged as untracked, and one or more days later it works again.

![Screenshot from 2024-11-09 19-38-52](https://github.com/user-attachments/assets/4ad912b3-c569-4533-80dc-cb538f1ff3a5)
![Screenshot from 2024-11-09 19-38-40](https://github.com/user-attachments/assets/d89f2267-eaf3-48d0-b4ff-c0b178578af0)

Individual devices
Tracking the energy usage of individual devices allows Home Assistant to break down your energy usage by device. [More information on how to get started.](https://www.home-assistant.io/docs/energy/individual-devices/)

Entity unavailable
The state of these configured entities are currently not available:
sensor.home_device_0_arotherm_plus_consumed_electrical_energy_domestic_hot_water (unavailable)
Entity unavailable
The state of these configured entities are currently not available:
sensor.home_device_0_arotherm_plus_consumed_electrical_energy_heating (unavailable)
Unexpected device class
The following entities do not have the expected device class:
sensor.evse_charged_energy
Entity unavailable
The state of these configured entities are currently not available:
sensor.home_device_0_arotherm_plus_earned_environment_energy_domestic_hot_water (unavailable)
Devices
WP cooling
WP SWW
Kona EV
WP heating

### Describe the behavior you expected

Don't skip a beat ;)

I never change anything on the input devices so why is the dashboard not processing the data anymore?

### Steps to reproduce the issue

1. open energy dashboard
2. view individual devices
3.
...

### What version of Home Assistant Core has the issue?

2024.11.1

### What was the last working version of Home Assistant Core?

-

### In which browser are you experiencing the issue with?

chrome v130.0.6723.116 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Ubuntu 24.04.1 LTS"

**Comment by karwosts** [comment]
You would need to find out why your entities are going unavailable, and on those days you just don't have any data for those devices. 

That is out of scope for frontend issue tracker. Suggest try one of the community resources (forum/discord) to ask for help with debug.
