### ISSUE TITLE
Automations: Broken singular vs. plural in description of AND condition

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22813]
### Describe the issue you are experiencing

There is a mismatch between singular and plural here:

![Screenshot 2024-11-13 20 22 30](https://github.com/user-attachments/assets/4b7617ab-8e6e-491f-baef-5016d1e44818)

![Screenshot 2024-11-13 20 22 37](https://github.com/user-attachments/assets/78bbe08e-a639-461a-ac2f-d165b0e9ceb0)

### Describe the behavior you expected

https://github.com/home-assistant/frontend/blob/7cbebfd60309dc5ba2f3181250858894fdf2ace4/src/translations/en.json#L3245

Needs to be changed to

    If {count} {count, plural,\n one {condition matches}\n other {conditions match}\n}

### Steps to reproduce the issue

That's what happens when translators silently fix such a glaring bug in Lokalise without writing a bug report about the English original. Just noticed this just by incident while scanning those translations …
According to the time stamps in Lokalise this is wrong since 2023-08-21.

### What version of Home Assistant Core has the issue?

core-2024.11.1

**Comment by NoRi2909** [comment]
And to make it worth a PR here an additional bug in conditions that must have slipped through during the last PRs to replace all "Confirm" with "If":

![Screenshot 2024-11-13 20 38 07](https://github.com/user-attachments/assets/13b0797c-e326-489f-a642-01e041a5539e)

That is the last one that is still not using "If" as all other:

https://github.com/home-assistant/frontend/blob/7cbebfd60309dc5ba2f3181250858894fdf2ace4/src/translations/en.json#L3355-L3356

Needs to be changed to

`If {entity} {numberOfEntities, plural,\n one {is}\n other {are}\n} in {zone} {numberOfZones, plural,\n one {zone} \n other {zones}\n}
`

Note this also removes the excessive space character at the end of the string!

**Comment by silamon** [comment]
Related to https://github.com/home-assistant/frontend/issues/21930

**Comment by NoRi2909** [comment]
@silamon  Ah, cool someone had noticed that earlier. 😄 

Note that his bug report is from before we replaced that duplicated "Test if" with just "if …"
That resulted in "Test Test if …" in Scripts, similar to the "Test Confirm …" in my comment above.
