### ISSUE TITLE
Timezone difference not accounted for in viewing data

### ISSUE THREAD

**Issue by Mishta** [home-assistant/frontend#22833]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Dear Support Team, 
Good day!

When showing data in all pages from computer with same timezone with the server there is no problem.
But, when the computer accessing the server has a different timezone set up, or using the Home Assistant App (Android), the difference is not accounted for. Instead of displaying the info in the server time, the data is displayed using accessing device's time.
![Screenshot_20241115_164041_Home Assistant](https://github.com/user-attachments/assets/5bfa113e-bf0f-4ff6-996d-260401758477)

### Describe the behavior you expected

The attached screenshot shows the Energy Dash, with data from a GMT+8 phone using Home Assistant App (v. 2024.10.3-full) from a server in Romania (HMT+3).

Taking into consideration the Sun production, this issue became obvious as the Sun rises much earlier than displayed in the graph.

### Steps to reproduce the issue

1.Start the App
2.Go to Energy Dash
3.Chech the graph
...

### What version of Home Assistant Core has the issue?

2024.7.2

### What was the last working version of Home Assistant Core?

2024.7.2

### In which browser are you experiencing the issue with?

Home Assistant App (Android) v. 2024.10.3-full

### Which operating system are you using to run this browser?

Android 14

### Problem-relevant frontend configuration

```yaml
UI Energy Dashboard
```

**Comment by karwosts** [comment]
Did you try the "User server time" setting in user profile settings? I don't actually know if that will fix or not, but it might.

**Comment by Mishta** [comment]
Dear karwosts,

Indeed, the suggested setting solved the display discrepancies.

Thank you, also for the fast reply!
