### ISSUE TITLE
Inconsistencies with "Create Automation" vs. "Add Script" and vice versa

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22830]
### Describe the issue you are experiencing

With Blueprints creating a (new) automation or script is just one option of adding one of them.

So the action button and dialog title for both should be

    Add automation   /    Add script

where 

    Create new automation   /   Create new script

are just suboptions in those dialogs besides picking some pre-made blueprints instead.

![Screenshot 2024-11-14 20 30 23](https://github.com/user-attachments/assets/37011ec3-f3fc-4e3e-8710-56808b671a35)

Currently there is quite some inconsistency here. For Automations we have the wrong "Create" in both places:

and for Scripts the button is correct with "Add", but the dialog title is using the wrong "Create":

![Screenshot 2024-11-14 20 31 10](https://github.com/user-attachments/assets/227835a2-200e-4961-b2ea-bf1f2c09968d)

### Describe the behavior you expected

Now this can be fixed easily by changing the following five strings to "Add …"

The wrong button:

https://github.com/home-assistant/frontend/blob/b83be385141a6d4513afc4848902745bcc31054f/src/translations/en.json#L2828

The dialog headers:

https://github.com/home-assistant/frontend/blob/b83be385141a6d4513afc4848902745bcc31054f/src/translations/en.json#L2873

https://github.com/home-assistant/frontend/blob/b83be385141a6d4513afc4848902745bcc31054f/src/translations/en.json#L3763

And from the menu under Blueprints (where this item is also illustrated with a "+" icon):

https://github.com/home-assistant/frontend/blob/b83be385141a6d4513afc4848902745bcc31054f/src/translations/en.json#L3693-L3694

BTW, this also makes them consistent with the third button in this area that is already "Add …":

![image](https://github.com/user-attachments/assets/c8fd6fe1-2236-4495-9bc3-4256748c4649)

### What version of Home Assistant Core has the issue?

core-2024.11.1

**Comment by NoRi2909** [comment]
Note that I also filed this bug because one German translator already changed part of this in German creating even more inconsistencies that I had to revert to get a clear picture of the whole issue.

So this bug is meant to bring full consistency in the English original that we can then follow in translations.

**Comment by silamon** [comment]
There's a design guideline to use "create" whenever something creates something new in the installation (create automation and create script) and we use "add" whenever something is added onto something that is already created (adding a card to an existing dashboard, add permissions to an user) => https://design.home-assistant.io/#Text/remove-delete-add-create

**Comment by NoRi2909** [comment]
@silamon I think this guideline backs all I suggested in my bug report above.

Keep "create" for "Create _new_ script" and "Create _new_ automation" as it is today, because they are made from scratch, but use "add" for turning an existing blueprint into an automation or script.

But if you prefer to use "create" for all of those then the current "Add script" button is the one that is to be fixed (see in the second screenshot above).

Regardless there is an inconsistency now that needs to be fixed.

**Comment by NoRi2909** [comment]
@silamon How do you think we should proceed?

Change "Add script" and "Add Scene" to "Create …" making everything consistent from that end?

**Comment by silamon** [comment]
I guess so. That's what the design mentions.
