### ISSUE TITLE
Unable to update home assistant past core 2024.10.2

### ISSUE THREAD

**Issue by Tmatz27** [home-assistant/frontend#22838]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

As the title states i am unable to update my home assistant instance past 10.2. There are no updates in the settings>system>updates. Ive cleared my browser, ive restarted the PC running the Home Assistant OC, and ive checked the box for ignored updates. Not sure how to get the system upated to the current version. 

I am running home assistant on a raspberry pi 5 on a m.2. 

### Describe the behavior you expected

I expect to see a new version of Home Assistant in the updates section.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Core 2024.10.2

### What was the last working version of Home Assistant Core?

Core 2024.10.2

### In which browser are you experiencing the issue with?

chrome, edge, home assistant app

**Comment by silamon** [comment]
Hi, this issue tracker is specifically for frontend bugs. I suggest to try over at the community forums or discord to get help for your specific situation and somebody to help you troubleshooting. https://www.home-assistant.io/help/
