### ISSUE TITLE
In Heading card - icons do not update such as battery to display their state

### ISSUE THREAD

**Issue by dopeytree** [home-assistant/frontend#22840]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In Heading card - icons do not update such as battery to display their state.

### Describe the behavior you expected

Expected the battery icon to change to reflect the actual battery level (as happens when you click the view more info etc).

### Steps to reproduce the issue

1. add heading card
2. add a title on left
3. add entity with battery
4. observe the icon is manual i.e non updating compared to other cards.
5. icon chosen is battery 30. 
6. other cards are using the icon 20 to reflect the 24% battery level.
7. Not fused about the colour as that can be CSS.
8. but a way to update icons would be ace.
...
<img width="608" alt="Screenshot 2024-11-16 at 00 20 46" src="https://github.com/user-attachments/assets/651ed888-1581-489e-bc84-e20c3c948f73">

### What version of Home Assistant Core has the issue?

2024.11.1

### In which browser are you experiencing the issue with?

safari 18.1

### Which operating system are you using to run this browser?

Mac os seqoia 15.1

### State of relevant entities

```txt
state_class: measurement
unit_of_measurement: "%"
device_class: battery
friendly_name: PowerStream-75 Battery Charge
```

### Additional information

<img width="608" alt="Screenshot 2024-11-16 at 00 20 46" src="https://github.com/user-attachments/assets/93738b60-35a4-490d-bf52-82c54a764de2">

Heading card just needs a bit of love, some small things like this to update icons to reflect state plus some formatting things.
If you have more than 3x entities they don't display properly on a mobile for some reason.

Really love the heading card though it's so neat!

<img width="1512" alt="Screenshot 2024-11-16 at 00 33 02" src="https://github.com/user-attachments/assets/f44bab81-83bc-42fa-abdb-5c43c315a0b5">

**Comment by ildar170975** [comment]
Do not confirm, icons for battery entities are shown properly.
![image](https://github.com/user-attachments/assets/5c97a95b-16f1-4de3-9b14-ae79aef2020e)
![image](https://github.com/user-attachments/assets/b17498eb-fad5-4bc0-a0c7-51a6874001f8)

**Comment by dopeytree** [comment]
Thanks it must've been my entity as like you show worked so bug closed.

Is it possible to associate an entity for icons on the left of the heading? As in the titles icon?

**Comment by dopeytree** [comment]
Am I able to close this report?
