### ISSUE TITLE
All addons logs are stuck on "Loading full log…"

### ISSUE THREAD

**Issue by elliottmarter** [home-assistant/frontend#23012]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

For all addons the log page just shows "Loading full log…"

![image](https://github.com/user-attachments/assets/b241920d-c40c-4472-9276-d4765f07d08f)

### Describe the behavior you expected

The addons show load logs

### Steps to reproduce the issue

Browse to the logs page for any addon

### What version of Home Assistant Core has the issue?

2024.11.3

### In which browser are you experiencing the issue with?

Chrome Version 131.0.6778.86 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

**Comment by elliottmarter** [comment]
This is now working again - no action taken by me.

**Comment by bevanting** [comment]
Can we re-open this? I have this same problem. I'm running Core 2024.12.5. 
I am also getting this error message after staying on the Log screen: Failed to get "de91e161_hassio_{{app name}} logs, Load failed"

**Comment by jflad17** [comment]
I have the same issue on some of my addons in my case it seems to be any addons I created pre 2024.10 updates. Currently been dealing with this since around then with no luck on finding the bug. Maybe the way this api runs? 

![Image](https://github.com/user-attachments/assets/24a338e3-189a-4c1a-88ec-a44db537001e)

**Comment by jebeke65** [comment]
also having the issue

**Comment by fabiosci** [comment]
i have the same issue, i tried also from another pc. same problem...
the strange thing is that the issue occurs only form browser (the companion app loads logs correctly).

has anyone found a solution?
