### ISSUE TITLE
GUI Input validator is not allowing entry of a second zero anywhere after 0. for a positive_float 

### ISSUE THREAD

**Issue by zestysoft** [home-assistant/frontend#23016]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I've created an integration that has configuration options. the data_schema has one of the fields defined with a config_validation.positive_float.

If I attempt to enter in a value like 0.0128, the GUI will not allow me to type in a second zero anywhere after the decimal point.  For instance if I type 0.0 it will erase both the second zero and the period.  If I attempt to type 0.103, it won't let me type in the second zero.  It will allow me to enter in any other digit.

### Describe the behavior you expected

I can enter in any valid positive float value.

### Steps to reproduce the issue

1. Click on CONFIGURE for the added integration
2. Attempt to enter a value for any positive_float field.

### What version of Home Assistant Core has the issue?

2024.11.2

### In which browser are you experiencing the issue with?

Both Safari Version 18.1.1 (20619.2.8.11.12) and Chrome Version 131.0.6778.86 (Official Build) (arm64)

### Which operating system are you using to run this browser?

macOS Sequoia 15.1.1

**Comment by ildar170975** [comment]
same? https://github.com/home-assistant/frontend/issues/22955

**Comment by zestysoft** [comment]
yep!
