### ISSUE TITLE
Target Picker: Duplicate overlapping tooltips

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#23064]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Target picker has two different styles of tooltips that overlap each other (on the remove/expand options):

<img width="514" alt="Target-Picker" src="https://github.com/user-attachments/assets/f6fb4370-4243-41a6-993d-934bca6aaef1">

Screen recording of the rest:

https://github.com/user-attachments/assets/ced29aff-b5bc-46fa-97c1-0adbfd863806

### Describe the behavior you expected

One tooltip

### Steps to reproduce the issue

1. Visit anything with target picker (logbook/history panel, automation/script editor, etc)
2. Hover over the expand/remove options and notice how tooltips overlap

### What version of Home Assistant Core has the issue?

2024.12.0b2

**Comment by ildar170975** [comment]
Same staled: https://github.com/home-assistant/frontend/issues/20730
