### ISSUE TITLE
All entities in an integration reenabling when enabling one in UI

### ISSUE THREAD

**Issue by oneseventhree** [home-assistant/frontend#23074]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have an integration that has 150+ entities but I only need 40 so I disabled the ones I don't need.
When I re-enable one of them ALL of them come back and I have to disable them all again.

I think this is a UI issue?

### Describe the behavior you expected

Re-enabling one of the disabled entities only brings that one back.

### Steps to reproduce the issue

1. Enable disabled entity
2. Wait 30 seconds
3. All entities in that integration come back online

### What version of Home Assistant Core has the issue?

2024.11.3

### What was the last working version of Home Assistant Core?

Not sure

### In which browser are you experiencing the issue with?

Chrome Version 131.0.6778.71 (Official Build) (x86_64)

### Which operating system are you using to run this browser?

Windows 11

### Additional information

Before:
<img width="510" alt="image" src="https://github.com/user-attachments/assets/6845ccf9-7f73-4f68-b35f-f52c39479319">

I enable rain amount:
<img width="346" alt="image" src="https://github.com/user-attachments/assets/4bcd57ec-779c-4e1f-bf4d-e9b27c0e88a5">

Then 30 seconds later all enties are enabled:
<img width="532" alt="image" src="https://github.com/user-attachments/assets/ac621719-6668-4d7e-b1c9-89f7751e30ee">

**Comment by karwosts** [comment]
I can't reproduce anything similar. How did you enable an entity, you clicked on the entity registry settings?

When you click the enable slider there it just sends a config registry update for a single entity, I can't see how other entities could get enabled in that case.

Have you tried to see if you see similar behavior on other devices of other integrations?

**Comment by oneseventhree** [comment]
> I can't reproduce anything similar. How did you enable an entity, you clicked on the entity registry settings?
> 
> When you click the enable slider there it just sends a config registry update for a single entity, I can't see how other entities could get enabled in that case.
> 
> Have you tried to see if you see similar behavior on other devices of other integrations?

You ae correct! I thought it was a UI bug but it seems its an issue with one integration only:
https://github.com/bremor/bureau_of_meteorology/issues/238
