### ISSUE TITLE
Connection refused, Invalid authentication

### ISSUE THREAD

**Issue by Mich-es** [home-assistant/frontend#23078]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

hi, since 2 days no more data comes and I get the request ‘reconfigure’. If I click on it, I have to enter my user name and password. If I enter the correct data, I get the message ‘invalid authentication’.

![grafik](https://github.com/user-attachments/assets/8286654b-aef1-4d9f-81ac-64d724f9c7a4)

If I log in to BMW directly, the login data works

### Describe the behavior you expected

when i enter the login data that it works again

### Steps to reproduce the issue

1. Homeassistant
2. Setings
3. BMW Connect
4. Enter Username and Passwort
...

### What version of Home Assistant Core has the issue?

2024.11.3

### In which browser are you experiencing the issue with?

Firefox 133.0 

### Which operating system are you using to run this browser?

Win10

### State of relevant entities

```txt
Log entry
2024-12-01 09:34:42.496 DEBUG (MainThread) [bimmer_connected.api.authentication] Authenticating with MyBMW flow for North America & Rest of World.
2024-12-01 09:34:42.978 ERROR (MainThread) [bimmer_connected.api.authentication] MyBMWAuthError due to HTTPStatusError: invalid_client - Client authentication failed (e.g., login failure, unknown client, no client authentication included or unsupported authentication method)
```

**Comment by silamon** [comment]
You will need to open an issue against the bmw connected drive integration at https://github.com/home-assistant/core.

**Comment by Mich-es** [comment]
Thanks, but the link you provided leads back here...
