### ISSUE TITLE
Issue with Copying YAML Code from Home Assistant Desktop App

### ISSUE THREAD

**Issue by shadigh92** [home-assistant/frontend#23085]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When using the Home Assistant desktop app, I cannot copy YAML code from the interface. This issue does not occur when using the Home Assistant web interface, where copying works as expected.

### Describe the behavior you expected

I expected to be able to copy YAML code from the desktop app just as seamlessly as I can from the web interface.

### Steps to reproduce the issue

1.	Open the Home Assistant desktop app (specify OS:macOS).
2.	Navigate to a YAML editor or configuration page.
3.	Highlight a block of YAML code and attempt to copy it.
4.	Paste the copied content elsewhere (e.g., in a text editor) and observe that the operation fails.
5.	Perform the same steps in a browser with the Home Assistant web interface, where the issue does not occur.

### What version of Home Assistant Core has the issue?

2024.11.3

### In which browser are you experiencing the issue with?

Google Chrome 131.0.6778.86

### Which operating system are you using to run this browser?

Sequoia‏15.0 ‏(24A335‏)

**Comment by karwosts** [comment]
I believe all mac apps are served by this repository: https://github.com/home-assistant/iOS/

This might be a better fit for there, the Apple desktop app isn't developed here.
