### ISSUE TITLE
Sensibo Integration fails to connect with correct API since update

### ISSUE THREAD

**Issue by petullam** [home-assistant/frontend#23093]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

HA newbie here...

I have upgraded to Core 2024.11.3.

The Sensibo Integration stopped working. I deleted and recreated...The Sensibo integration shows up automatically upon booting. However when I press configure and copy paste the API key, it always fails with error "fail to connect".

The same issue is present for the Ring Integration

### Describe the behavior you expected

Create the integration.
I have verified it is the correct API key

### Steps to reproduce the issue

1. I restored version and tried the same steps
2. Then updated to latest version again
3. I deleted the integration
4. Recreated a new API
5. Booted HA and proceeded to add Sensibo Integration
6. Upon configuration and copy/paste of API I get "Failed to Connect"

### What version of Home Assistant Core has the issue?

2024.11.3

### In which browser are you experiencing the issue with?

Bing

### Which operating system are you using to run this browser?

Windows 10

### Additional information

![Capture](https://github.com/user-attachments/assets/157ef73c-748b-4b10-8281-d55bf99b0d44)

**Comment by karwosts** [comment]
This is a core issue, not frontend. Please file it in home-assistant/core.
