### ISSUE TITLE
Core 2024.12: Durations are no longer displayed using any format but only their raw value and unit of measure

### ISSUE THREAD

**Issue by jxlarrea** [home-assistant/frontend#23154]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The latest HA Core update broke the way that durations are displayed on the frontend. Now all duration values are only being presented using the raw value followed by the abbreviation of its unit of measure.

![lol](https://github.com/user-attachments/assets/ec93b968-2b9e-4f75-8675-4845335c18d9)

![Overview-–-Home-Assistant-12-05-2024_04_31_AM](https://github.com/user-attachments/assets/556f1adf-dff3-4781-afd0-6bcde6d03183)

### Describe the behavior you expected

Duration should be presented as before the update to HA Core 2024.12 using a timer format (03:26:00), or ideally as stated in the changelog:

> The UI now displays durations using a timer format (like 03:26:00) in natural language (3h 26min). 

### Steps to reproduce the issue

1.- All durations are being displayed wrong.

### What version of Home Assistant Core has the issue?

core-2024.12.0

### What was the last working version of Home Assistant Core?

core-2024.11.3

### In which browser are you experiencing the issue with?

All Browsers

### Which operating system are you using to run this browser?

All OS

**Comment by piitaya** [comment]
Hi 👋 
Can you should the unit of the entity using entity settings? The UI will now respect the chosen unit.

**Comment by jxlarrea** [comment]
> Hi 👋 You can choose the unit of the entity using entity settings. The UI will now adapt according to the chosen unit.

Hey thanks, I see how it works now! Closing the issue.
