### ISSUE TITLE
Translation broken in HA 2024.12

### ISSUE THREAD

**Issue by Protoncek** [home-assistant/frontend#23153]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After installing HA 2024.12 translation is a mix of Slovenian (which is set to), English and Swedish (see picture: "uppdatera" is Swedish, while "preskoči" is slovenian). Clearing cache doesn't help. In developer tools "action" meni is also in swedish
![image](https://github.com/user-attachments/assets/d62e9e4d-349d-4ac3-9213-762d765764ed)
![image](https://github.com/user-attachments/assets/10ff3646-cdda-426a-ad75-7e785dd181d7)

### Describe the behavior you expected

Going back to 2024.11.3 solves the problem - all is back to Slovenian language

### Steps to reproduce the issue

1. install HA version 2024.12
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.12

### What was the last working version of Home Assistant Core?

2024.11.3

### Which operating system are you using to run this browser?

Windows 11

### Additional information

-

**Comment by bramkragten** [comment]
It seems like someone made some mistakes while translating, comment from Lokalise:

![CleanShot 2024-12-05 at 11 12 40](https://github.com/user-attachments/assets/2d4b5c41-3ab4-4f1c-9217-ced2a0150653)

If you want to help fix this, that would be great: https://developers.home-assistant.io/docs/translations

**Comment by Protoncek** [comment]
Auch... i saw that someone indeed wrote all swedish into slovenian... what a mess...
well, back to english for a while, i guess. 
I looked a quick... there are, if i see correctly over 3000 lines corrupted... there must be any restore, i guess...

**Comment by andrejs2** [comment]
What a mess :(

**Comment by Protoncek** [comment]
I’ve been told that devs are informed about that (tom_I from HA forums warned them, thanks, Tom!), so hopefully it will be corrected in next small HA update. It really IS a mess…

**Comment by dolenec** [comment]
Not even a close. What a fiasco.
I know that my contribution was complete energy data translate + many hours of translating other stuff.. how can be that everybody can translate every language.. this is a big security problem..

![Screenshot_20241206_210404_Samsung capture](https://github.com/user-attachments/assets/c8f58175-6624-40f7-8944-a5c93ba17614)

**Comment by Protoncek** [comment]
Agreed, not even close. I think that all what's been done is removed all swedish words, leaving blanks which resulted in tons of words in english.
Distaster... I can't believe that there's no proper backup...?

**Comment by andrejs2** [comment]
No worries about backup...it's actually PR which can be reverted :)
Lucky for me, I have backups and this release only installed on one instance of HA which is not production setup. 
But I can understand your anger.

**Comment by dolenec** [comment]
Maybe it's time to learn hard and to translate all other languages to Slovenian 😄 Then maybe some fix will come..

Also, not all swedish words are removed.. so this was no restore from backup but rather some half baked clicking job..

**Comment by dolenec** [comment]
@balloob Please check this, what is your opinion about this. Firstly my opinion is that all community job can be easily destroyed with some good AI script / bot, secondly - no backup in this case?

Solution:
If we check 2024.11.3 translation files then we should use strings translation of Slovenian language from this release and use it for 2012.12.x and forward..

**Comment by dolenec** [comment]
Also, this should be reopened as it is not resolved.

**Comment by frgazor** [comment]
Installed 2024.12.1today and it's still broken. Only this time it's mostly English instead of Swedish.

**Comment by Protoncek** [comment]
Hm... translate 2000-3000 words …again…  (appr. that much are empty now if i saw correct) if there were already translated? I don't think it's quite honest to first translator to ask this… It's not like one hour of work…

**Comment by frgazor** [comment]
Obviously there is no backup or version history on lokalise and no way to prevent honest mistakes or pure vandalism.

**Comment by dolenec** [comment]
Personaly.. I will rather translate all 45 languages to the bull***shit so that I will give A point of what you ask us to do..

Answer: NO! If strings are OK in 2012.11.3, then use from this source and replace it.. otherwise I'm completly done and will rather to fu**ck others to show what a security fiasco this is.

**Comment by Protoncek** [comment]
I kinda doubt that it's so, but if it is, then lokalise is very... how do i put this… primitive platform …
I think more that a proper guy on likalise site (admin … ?) is required for restoring backup.

**Comment by frgazor** [comment]
There are snapshots and translation history available according to lokalise website.  So someone with the right knowledge and access just needs to restore the translation history. Expecting us to translate thousands of translations again is just... funky.

**Comment by Protoncek** [comment]
And, as i said, very dishonest, if not offensive to original translator, who put hours, days, weeks… of his free work into this…

**Comment by dolenec** [comment]
I personally put more than 80 working hours .. so I am not only frustrated but getting angry as somebody tell me simple to translate it again. wtf? Did anybody contact somebody on localize with admin rights to solve this?

**Comment by dolenec** [comment]
And the biggest shame is that issue is closed as that it's resolved, but is not..

**Comment by frgazor** [comment]
open new ticket for 2024.12.1

**Comment by dolenec** [comment]
We do have the option to revert translation in the bulk menu, so now you will need to identify those keys first, select them, and then use this option

As long as you select the correct keys and make sure you are in Bilingual view in the right target language

**Comment by dolenec** [comment]
From localize support:

There is no direct way of doing that now. If you have contacted us that day or day after we can easily pick them with a filter we have in the projects

You can rely on Automatic Snapshots to recover the translations, let me explain to you how that works (it is not direct either)

You will need to identify the exact date you had the right translations before the changes were made, then recover that snapshot, that will create a new project named CURRENT PROJECT NAME + COPY

Then export your content from there and import it back to the original project

Snapshots can be checked from here https://app.lokalise.com/settings/3420425759f6d6d241f598.13594006/#snapshots

If you do not have any active integrations with the project, you can restore the Snapshot and start using the copy project as your main one

**Comment by dolenec** [comment]
And we need to contact paulus who has admin rights..

**Comment by frgazor** [comment]
We might have another problem or maybe I'm missing something

quickly comparing 2 missing translations in 2024.11.3 vs. 2024.12.2:

![2024 11 3](https://github.com/user-attachments/assets/73376eb8-4d7f-4682-871e-b48ea6baca12)
![2024 12 2](https://github.com/user-attachments/assets/5679e1c6-6988-4a6e-a8f2-6dc4ce719ce0)

but both translations are there and look fine to me in lokalise:
![2024-12-11_07-39](https://github.com/user-attachments/assets/84d14bf6-5340-4027-b1a7-beae7e33c643)
![2024-12-11_07-38](https://github.com/user-attachments/assets/52077dec-8254-46c0-9550-3939c90d0793)

**Comment by Protoncek** [comment]
Hm…perhaps this was not yet “imported” into ha…? I don’t know how this works - is it automatic or “manual”…
Btw…nothing was mentioned in neither of HA patches about correcting broken slovenian translation anyway…

**Comment by frgazor** [comment]
These translations are very old and were not restored from history as part of "swedish fiasco". But really I have no idea how importing from lokalise works.

**Comment by Protoncek** [comment]
What makes this whole thing even more bizarre is the fact that now it’s useless for anyone to translate (any further), because we don’t know what next… anything anyone translates now can be overwritten at any time with possible restores from backup… so, in short, we’re f**ked.

**Comment by dolenec** [comment]
It's time to contact:
![SmartSelect_20241210_125215_Samsung Internet](https://github.com/user-attachments/assets/c8ae44c0-c192-4a10-88f8-1c49cd6fc9ff)

**Comment by dolenec** [comment]
We must organize and contact Paulus... Who will do it?

**Comment by Protoncek** [comment]
I think that the person who contributed most of his hours into translation would be the best for contacting him...

**Comment by dolenec** [comment]
Today I will send him email and explain situation and ask him if it's possible to reverse translation to 2024.11.3 or 2024.11.2.

**Comment by dolenec** [comment]
Paulus reapond ❤️ and it's resolving now.

**Comment by bramkragten** [comment]
The backup was restored, and as you can see in Lokalise these keys have a translation. They are not verified however, this is a new requirement to make sure translations keep working after the source has changed. <https://github.com/home-assistant/frontend/pull/22844>

This is completely unrelated from the issue with the Swedish translator, a member of the Slovenian translator team will have to verify the unverified translations.

You can filter for unverified translations in Lokalise:
![CleanShot 2024-12-14 at 14 20 22@2x](https://github.com/user-attachments/assets/b4afa913-7a48-4d5d-859d-2ade26ae02c7)

**Comment by dolenec** [comment]
Will check it. Thank you..

**Comment by dolenec** [comment]
Sorry to say, but your claim are not true.

Just check these two strings...
![image](https://github.com/user-attachments/assets/78db5984-685d-4956-a2ca-2d45a2df1fe3)

Now check localize:
![image](https://github.com/user-attachments/assets/11b10fa7-1397-47ef-a9b8-e7f001ded4e0)

I do not see any translation?

Here no string...
![image](https://github.com/user-attachments/assets/cef1beca-13bc-4f84-9b03-dd0587bfa0ca)

So, what do you want from us, to translate again 3000 strings? Do not understand... How hard is to use snapshot from when 2024.11.3 release was?

![image](https://github.com/user-attachments/assets/4152dfd4-bd82-4a13-8792-b531b5d52d71)

**Comment by dolenec** [comment]
And why there is still Swedish translation?
![image](https://github.com/user-attachments/assets/edf56672-0a12-43b4-b4e8-1897dc2e1e5e)

**Comment by bramkragten** [comment]
> Now check localize:
>
> I do not see any translation?

You are looking in the wrong project, you need to look in the frontend project, not the core project. Those are translation strings from integrations, and not the thing that was cleared or restored.

The translation your are talking about is here:
![CleanShot 2024-12-14 at 17 38 02@2x](https://github.com/user-attachments/assets/605501d9-2c88-4bb8-a7ae-3b607ff0e01b)

**Comment by dolenec** [comment]
Is this then ready and will be OK with next release or not?
![image](https://github.com/user-attachments/assets/7a3a79d7-dcc1-4b39-a089-531881941cd5)

Also see that right now all Swedish string are back to Slovenian strings... so as seem this will be resolved on next release. Do I assume correct?

**Comment by bramkragten** [comment]
Yes, please review the unverified strings, https://app.lokalise.com/project/3420425759f6d6d241f598.13594006/?view=single&reference_lang_id=640&single_lang_id=920&filter=unsaved_9184b7152ef5a1271493769ff4a03bc5

**Comment by dolenec** [comment]
Nothing to review.. all strings empty.. probably this is OK.. we will see next HA release..

**Comment by sdotter** [comment]
I have same issue but with dutch language...
Happened after latest upgrade...

**Comment by bramkragten** [comment]
@sdotter you mean missing dutch translations and having english ones? Please make sure there are no unverified translations in Lokalise, as they are now no longer downloaded.

**Comment by dolenec** [comment]
@bramkragten 2012.12.4 and still some swedish and mostly english..
problem still not fixed?!

Can somebody cemheck this?

**Comment by dolenec** [comment]
Also.. how to review all unverified strings at once and conform it and not just one by one..?

**Comment by sdotter** [comment]
Yeah my dutch home assistant 2024.12.3 looks like:

<img width="1016" alt="image" src="https://github.com/user-attachments/assets/cf71b258-666e-4f9a-ac85-d721cf41d362" />

Updating in progress... lets see what 2024.12.4 does 😂👍
Ill report back in few minutes...

**Comment by frgazor** [comment]
> Also.. how to review all unverified strings at once and conform it and not just one by one..?

In theory you just create a filter to find all unverified translations, select all keys and apply bulk action to unset unverified status. Problem is you need to be admin to execute bulk actions :)

For us normal users the only option is clicking through all unverified keys (468 currently unverified in Slovenian translation). Some translations are weird and need fixing, but most are ok.

**Comment by frgazor** [comment]
After some more checking unverified Slovenian translations I must disagree with bulk action to verify all unverified translations. Too many of these translations are bad or just wrong. I already started reviewing and fixing these but it will take time. It's also quite hard to do translation without proper context.

**Comment by frgazor** [comment]
I managed to verify (and hopefully improve) most but there are still 42 non-empty translation keys left unverified in Slovenian language. I left these unverified for various reasons like consistency, translation quality etc. For example sometimes original english word "Supervisor" is used in Slovenian translation and sometimes "nadzornik"

**Comment by dolenec** [comment]
PS. I hope that next release string Water which currently is in Swedish "Vatten" will be replaced with "Voda" 😉

**Comment by frgazor** [comment]
I highly doubt verifying most translation keys I did today will help in any way. For example translation key "Developer tools" has been verified and properly translated into Slovenian "Orodja za razvijalca" for years and yet it still shows in English in all 2024.12.x versions. The same goes for "Automation & scenes". Also there is no string "Vatten" in Slovenian translation in lokalise.

I'm starting to think there is something terribly wrong in HA building process.

**Comment by dolenec** [comment]
2024.12.5:
Energy tab: Energija

Stil untranslated:
Energy usage
Vatten (still Swedish)

nothing related to strings changed?

**Comment by frgazor** [comment]
Energy usage is properly translated and verified:

![image](https://github.com/user-attachments/assets/f6a6e898-1696-42f6-9b94-ee0928dd8ff8)

Obviously strings from lokalise are not included at build time.

**Comment by Protoncek** [comment]
It's the same as before.  As frgazor said: there must be something terribly wrong elsewhere, but as it seems no-one really cares...

**Comment by dolenec** [comment]
Maybe @balloob can solve this as owner..

**Comment by Protoncek** [comment]
Perhaps something is finally moving into a good direction. I installed HA2025.01b1 on my test HA setup and majority of words are back (like "orodja za razvijalce", "avtomatizacije in naprave",...).

I'm keeping my fingers crossed...

**Comment by frgazor** [comment]
Installed 2025.1.0 today and it looks fine

**Comment by dolenec** [comment]
Yep.. same for me.. starting to translate untranslated strings again 💪

**Comment by frgazor** [comment]
still not 100%

![image](https://github.com/user-attachments/assets/4fc6c145-4f13-4a33-9011-dd52acaa667d)
![image](https://github.com/user-attachments/assets/6be726cb-768e-44b9-a412-f622c8f68e49)

this translation is from 2018 and verified

**Comment by dolenec** [comment]
Yea.. I saw many strings which are translated but shown in English.. don't know how to solve this..
