### ISSUE TITLE
Energy Dashboard - No price display for electricity

### ISSUE THREAD

**Issue by Herbert-Testmann** [home-assistant/frontend#23205]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

A sum is calculated in the automatically created and hidden entity. However, the display on the dashboard is always 0.00
(the calculation for gas consumption works.)

<img width="719" alt="Bildschirmfoto 2024-12-07 um 23 37 47" src="https://github.com/user-attachments/assets/2bdd340c-794d-4cf2-884a-8b0b5edec2c9">
<img width="986" alt="Bildschirmfoto 2024-12-07 um 23 38 56" src="https://github.com/user-attachments/assets/21680656-7203-4fdd-8154-fcb474cfcb8d">

### Describe the behavior you expected

The dashboard should display the total that is in the automatically created entity.

### Steps to reproduce the issue

1.Calculate costs
2.Fixed price or price from an entity
3.Wait 2 hours
...both options do not work

### What version of Home Assistant Core has the issue?

2024.12.1

### In which browser are you experiencing the issue with?

CHrome Version 131.0.6778.109 (Offizieller Build) (arm64) / Safari Version 18.1.1 (20619.2.8.11.12) 

### Which operating system are you using to run this browser?

macOS 15.1.1 (24B91)

**Comment by karwosts** [comment]
Please run the following two commands in your browser debug console, and copy the response object for each and paste it here. 

`document.getElementsByTagName("home-assistant")[0].hass.callWS({type: 'energy/get_prefs'})`

`document.getElementsByTagName("home-assistant")[0].hass.callWS({type: 'energy/info'})`


And they return something like:
```
{
    "cost_sensors": {
        "sensor.water_flow_utility_meter": "sensor.water_flow_utility_meter_cost",
        "sensor.total_gas_ft3": "sensor.total_gas_ft3_cost",
        "sensor.total_gas_m3": "sensor.total_gas_m3_cost",
        "sensor.template_water_consumption": "sensor.template_water_consumption_cost"
    },
    "solar_forecast_domains": [
        "forecast_solar"
    ]
}
```

**Comment by Herbert-Testmann** [comment]
ok, I hope this is, what you need

`[[PromiseResult]]
: 
Object
cost_sensors
: 
sensor.ccu3_webui_sv_w_counter_1
: 
"sensor.ccu3_webui_sv_w_counter_1_cost"
sensor.gas_zaehler_gas_gas_zaehler_1_gas_gas_energiezahler
: 
"sensor.gas_zaehler_gas_gas_zaehler_1_gas_gas_energiezahler_cost"
sensor.whirlpool_5_energiezahler
: 
"sensor.whirlpool_5_energiezahler_cost"
[[Prototype]]
: 
Object
solar_forecast_domains
: 
Array(0)
length
: 
0`

`[[PromiseResult]]
: 
Object
device_consumption
: 
Array(7)
0
: 
name
: 
"Whirlpool"
stat_consumption
: 
"sensor.whirlpool_5_energiezahler"
[[Prototype]]
: 
Object
1
: 
name
: 
"Server"
stat_consumption
: 
"sensor.zwstecker_server_2_energiezahler"
[[Prototype]]
: 
Object
2
: 
name
: 
"Bungalow_Heizung 1"
stat_consumption
: 
"sensor.zwst_ip_06_heizung1_zwst_ip_06_6_heizung1_energiezahler"
[[Prototype]]
: 
Object
3
: 
name
: 
"Bungalow_Heizung 2"
stat_consumption
: 
"sensor.zwst_ip_07_heizung2_zwst_ip_07_6_heizung2_energiezahler"
[[Prototype]]
: 
Object
4
: 
name
: 
"Bungalow_Heizung Bad"
stat_consumption
: 
"sensor.zwst_ip_14_heizung3_bad_6_energiezahler"
[[Prototype]]
: 
Object
5
: 
name
: 
"GetraenkeKuehlschrank"
stat_consumption
: 
"sensor.zwstecker_21_getraenkekuehschrank_energiezahler"
[[Prototype]]
: 
Object
6
: 
name
: 
"Waschmaschine"
stat_consumption
: 
"sensor.smart_plug_2303168338726151200348e1e9bfdc35_energy"
[[Prototype]]
: 
Object
length
: 
7
[[Prototype]]
: 
Array(0)
energy_sources
: 
Array(4)
0
: 
cost_adjustment_day
: 
0
flow_from
: 
Array(2)
0
: 
entity_energy_price
: 
"input_number.strompreis"
number_energy_price
: 
null
stat_cost
: 
null
stat_energy_from
: 
"sensor.ccu3_webui_sv_w_counter_1"
[[Prototype]]
: 
Object
1
: 
entity_energy_price
: 
"input_number.strompreis"
number_energy_price
: 
null
stat_cost
: 
null
stat_energy_from
: 
"sensor.whirlpool_5_energiezahler"
[[Prototype]]
: 
Object
length
: 
2
[[Prototype]]
: 
Array(0)
flow_to
: 
Array(0)
length
: 
0
[[Prototype]]
: 
Array(0)
type
: 
"grid"
[[Prototype]]
: 
Object
1
: 
entity_energy_price
: 
null
number_energy_price
: 
1.165
stat_cost
: 
null
stat_energy_from
: 
"sensor.gas_zaehler_gas_gas_zaehler_1_gas_gas_energiezahler"
type
: 
"gas"
[[Prototype]]
: 
Object
2
: 
config_entry_solar_forecast
: 
null
stat_energy_from
: 
"sensor.zwst_ip_02_solar_6_energiezahler"
type
: 
"solar"
[[Prototype]]
: 
Object
3
: 
config_entry_solar_forecast
: 
null
stat_energy_from
: 
"sensor.zwst_ip_pv_5_energiezahler"
type
: 
"solar"
[[Prototype]]
: 
Object
length
: 
4`

**Comment by Herbert-Testmann** [comment]
<img width="1012" alt="Bildschirmfoto 2024-12-08 um 16 57 06" src="https://github.com/user-attachments/assets/d2b4a3c4-84e4-4c10-a2a1-5ef7ed66e408">

**Comment by karwosts** [comment]
Hmm was hoping it would copy as something a little more readable. For example if I select the response in chrome and right click "Copy Object" I get this, which is much more readable. 

Having a hard time parsing the response you have there. 

```
{
    "energy_sources": [
        {
            "type": "water",
            "stat_energy_from": "sensor.water_flow_utility_meter",
            "stat_cost": null,
            "number_energy_price": 0.0003,
            "entity_energy_price": null
        },
        {
            "type": "gas",
            "stat_energy_from": "sensor.total_gas_ft3",
            "stat_cost": null,
            "entity_energy_price": null,
            "number_energy_price": 0.5
        },
        {
            "type": "gas",
            "stat_energy_from": "sensor.total_gas_m3",
            "stat_cost": null,
            "entity_energy_price": null,
            "number_energy_price": 0.2
        },
        {
            "type": "water",
            "stat_energy_from": "sensor.template_water_consumption",
            "stat_cost": null,
            "entity_energy_price": null,
            "number_energy_price": 0.001
        },
        {
            "type": "solar",
            "stat_energy_from": "sensor.demo_solar_energy_1",
            "config_entry_solar_forecast": null
        },
        {
            "type": "solar",
            "stat_energy_from": "sensor.demo_solar_energy_2",
            "config_entry_solar_forecast": [
                "59b2bb65a09808f043b081de886428f0"
            ]
        },
        {
            "type": "grid",
            "flow_from": [
                {
                    "stat_energy_from": "sensor.demo_grid_in_energy",
                    "stat_cost": null,
                    "entity_energy_price": null,
                    "number_energy_price": null
                }
            ],
            "flow_to": [
                {
                    "stat_energy_to": "sensor.demo_grid_out_energy",
                    "stat_compensation": null,
                    "entity_energy_price": null,
                    "number_energy_price": null
                }
            ],
            "cost_adjustment_day": 0
        },
        {
            "type": "battery",
            "stat_energy_from": "sensor.demo_battery_out_energy",
            "stat_energy_to": "sensor.demo_battery_in_energy"
        },
        {
            "type": "gas",
            "stat_energy_from": "kitchen_sink:gas_consumption_m3",
            "stat_cost": null,
            "entity_energy_price": null,
            "number_energy_price": null
        }
    ],
    "device_consumption": [
        {
            "stat_consumption": "sensor.to_battery_energy",
            "name": "Demo Device 1"
        },
        {
            "stat_consumption": "sensor.from_battery_energy",
            "name": "Demo Device 2"
        },
        {
            "stat_consumption": "sensor.breaker_1_sub_device_2_energy",
            "parent_stat": "sensor.breaker_1_energy"
        },
        {
            "stat_consumption": "sensor.breaker_1_sub_device_1_energy",
            "parent_stat": "sensor.breaker_1_energy"
        },
        {
            "stat_consumption": "sensor.breaker_1_energy"
        }
    ]
}
```

**Comment by karwosts** [comment]
Can you show a 24h graph of 

`sensor.ccu3_webui_sv_w_counter_1` and `sensor.ccu3_webui_sv_w_counter_1_cost` for a day you say is not working?

Note that cost is only calculated for the time _after_ you setup the entity, so if you're browsing back in history from before you set it up, that won't have a cost.

**Comment by Herbert-Testmann** [comment]
`{
    "energy_sources": [
        {
            "type": "grid",
            "flow_from": [
                {
                    "stat_energy_from": "sensor.ccu3_webui_sv_w_counter_1",
                    "stat_cost": null,
                    "entity_energy_price": "input_number.strompreis",
                    "number_energy_price": null
                },
                {
                    "stat_energy_from": "sensor.whirlpool_5_energiezahler",
                    "stat_cost": null,
                    "entity_energy_price": "input_number.strompreis",
                    "number_energy_price": null
                }
            ],
            "flow_to": [],
            "cost_adjustment_day": 0
        },
        {
            "type": "gas",
            "stat_energy_from": "sensor.gas_zaehler_gas_gas_zaehler_1_gas_gas_energiezahler",
            "stat_cost": null,
            "entity_energy_price": null,
            "number_energy_price": 1.165
        },
        {
            "type": "solar",
            "stat_energy_from": "sensor.zwst_ip_02_solar_6_energiezahler",
            "config_entry_solar_forecast": null
        },
        {
            "type": "solar",
            "stat_energy_from": "sensor.zwst_ip_pv_5_energiezahler",
            "config_entry_solar_forecast": null
        }
    ],
    "device_consumption": [
        {
            "stat_consumption": "sensor.whirlpool_5_energiezahler",
            "name": "Whirlpool"
        },
        {
            "stat_consumption": "sensor.zwstecker_server_2_energiezahler",
            "name": "Server"
        },
        {
            "stat_consumption": "sensor.zwst_ip_06_heizung1_zwst_ip_06_6_heizung1_energiezahler",
            "name": "Bungalow_Heizung 1"
        },
        {
            "stat_consumption": "sensor.zwst_ip_07_heizung2_zwst_ip_07_6_heizung2_energiezahler",
            "name": "Bungalow_Heizung 2"
        },
        {
            "stat_consumption": "sensor.zwst_ip_14_heizung3_bad_6_energiezahler",
            "name": "Bungalow_Heizung Bad"
        },
        {
            "stat_consumption": "sensor.zwstecker_21_getraenkekuehschrank_energiezahler",
            "name": "GetraenkeKuehlschrank"
        },
        {
            "stat_consumption": "sensor.smart_plug_2303168338726151200348e1e9bfdc35_energy",
            "name": "Waschmaschine"
        }
    ]
}`

`{
    "cost_sensors": {
        "sensor.ccu3_webui_sv_w_counter_1": "sensor.ccu3_webui_sv_w_counter_1_cost",
        "sensor.whirlpool_5_energiezahler": "sensor.whirlpool_5_energiezahler_cost",
        "sensor.gas_zaehler_gas_gas_zaehler_1_gas_gas_energiezahler": "sensor.gas_zaehler_gas_gas_zaehler_1_gas_gas_energiezahler_cost"
    },
    "solar_forecast_domains": []
}`

**Comment by Herbert-Testmann** [comment]
{
    "cost_sensors": {
        "sensor.ccu3_webui_sv_w_counter_1": "sensor.ccu3_webui_sv_w_counter_1_cost",
        "sensor.whirlpool_5_energiezahler": "sensor.whirlpool_5_energiezahler_cost",
        "sensor.gas_zaehler_gas_gas_zaehler_1_gas_gas_energiezahler": "sensor.gas_zaehler_gas_gas_zaehler_1_gas_gas_energiezahler_cost"
    },
    "solar_forecast_domains": []
}

{
    "energy_sources": [
        {
            "type": "grid",
            "flow_from": [
                {
                    "stat_energy_from": "sensor.ccu3_webui_sv_w_counter_1",
                    "stat_cost": null,
                    "entity_energy_price": "input_number.strompreis",
                    "number_energy_price": null
                },
                {
                    "stat_energy_from": "sensor.whirlpool_5_energiezahler",
                    "stat_cost": null,
                    "entity_energy_price": "input_number.strompreis",
                    "number_energy_price": null
                }
            ],
            "flow_to": [],
            "cost_adjustment_day": 0
        },
        {
            "type": "gas",
            "stat_energy_from": "sensor.gas_zaehler_gas_gas_zaehler_1_gas_gas_energiezahler",
            "stat_cost": null,
            "entity_energy_price": null,
            "number_energy_price": 1.165
        },
        {
            "type": "solar",
            "stat_energy_from": "sensor.zwst_ip_02_solar_6_energiezahler",
            "config_entry_solar_forecast": null
        },
        {
            "type": "solar",
            "stat_energy_from": "sensor.zwst_ip_pv_5_energiezahler",
            "config_entry_solar_forecast": null
        }
    ],
    "device_consumption": [
        {
            "stat_consumption": "sensor.whirlpool_5_energiezahler",
            "name": "Whirlpool"
        },
        {
            "stat_consumption": "sensor.zwstecker_server_2_energiezahler",
            "name": "Server"
        },
        {
            "stat_consumption": "sensor.zwst_ip_06_heizung1_zwst_ip_06_6_heizung1_energiezahler",
            "name": "Bungalow_Heizung 1"
        },
        {
            "stat_consumption": "sensor.zwst_ip_07_heizung2_zwst_ip_07_6_heizung2_energiezahler",
            "name": "Bungalow_Heizung 2"
        },
        {
            "stat_consumption": "sensor.zwst_ip_14_heizung3_bad_6_energiezahler",
            "name": "Bungalow_Heizung Bad"
        },
        {
            "stat_consumption": "sensor.zwstecker_21_getraenkekuehschrank_energiezahler",
            "name": "GetraenkeKuehlschrank"
        },
        {
            "stat_consumption": "sensor.smart_plug_2303168338726151200348e1e9bfdc35_energy",
            "name": "Waschmaschine"
        }
    ]
}

**Comment by Herbert-Testmann** [comment]
<img width="1071" alt="Bildschirmfoto 2024-12-08 um 18 22 18" src="https://github.com/user-attachments/assets/2cdde726-bc4d-4b6e-9c53-24fb67632e52">
<img width="1067" alt="Bildschirmfoto 2024-12-08 um 18 20 59" src="https://github.com/user-attachments/assets/defaa4e0-78c1-470c-8033-85102bb94f8b">

**Comment by karwosts** [comment]
Hmm, everything looks ok so far. The reset to 0 should not be an issue. 

Also check: 
 - find your cost statistic in developer-tools/statistics, and see if it has any issue reported. An issue may prevent statistics from being correctly recorded.
 
 - Using a statistics graph card, make an hourly plot of the cost statistic (showing `change`). See if that looks ok.

**Comment by Herbert-Testmann** [comment]
I think it's ok.
no problem in statistics
the costs increase evenly with each transmission of the meter reading

I don't understand why the current value in "sensor.ccu3_webui_sv_w_counter_1_cost" is not displayed on the dashboard.

the sensor has a customization in /homeassistant/customize.yaml
because it is a number that is imported. Not a physical sensor.
Could there be a mistake?

`sensor.ccu3_webui_sv_w_counter_1:
  state_class: total_increasing
  unit_of_measurement: "kWh"
  parameter: ENERGY_COUNTER
  device_class: energy
  name: w_counter_1
  friendly_name: Strom Zaehlerstand
`

<img width="944" alt="Bildschirmfoto 2024-12-08 um 19 45 16" src="https://github.com/user-attachments/assets/90aaab02-d053-4ff3-afd5-6be21aef2461">
<img width="687" alt="Bildschirmfoto 2024-12-08 um 19 48 17" src="https://github.com/user-attachments/assets/5646e6db-a38d-4d06-81db-b6471ce9a43a">

**Comment by karwosts** [comment]
I still want to see this:

> Using a **statistics graph card**, make an hourly plot of the cost statistic (showing change). See if that looks ok.

The dashboard does not simply "show the value of the sensor". It pulls the statistics stored in Long term statistics over the duration displayed in the energy date picker, and displays the total increase in the statistic over that window. It does not use the entity state, nor the history of the entity state, it uses the values stored in Long term statistics.

**Comment by karwosts** [comment]
The use of customize may very well be an issue.

**Comment by Herbert-Testmann** [comment]
I hope that this is, what you mean.
<img width="517" alt="Bildschirmfoto 2024-12-09 um 08 50 24" src="https://github.com/user-attachments/assets/0d787756-f8d0-45fd-9c07-c73254c17219">
<img width="527" alt="Bildschirmfoto 2024-12-09 um 08 52 15" src="https://github.com/user-attachments/assets/fbfcc951-2935-4d93-8c00-37025537f4ce">

**Comment by Herbert-Testmann** [comment]
Hello
I change the database from HA internal sql to external MariaDB. 
And now, I can see costs for electricity

Or the update of HA yesterday solve the problem.

**Comment by Herbert-Testmann** [comment]
solved for me
