### ISSUE TITLE
Can't Add any Integrations in 20241211.0.dev 

### ISSUE THREAD

**Issue by awptechnologies** [home-assistant/frontend#23252]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When going to devices and trying to add integration the window disappears and no setup options show up. This happens for pihole and others.

### Describe the behavior you expected

I expect to search for integration click it and get a window that is used to set up the specified integration. 

### Steps to reproduce the issue

1. Go to devices and integration
2. add integration

### What version of Home Assistant Core has the issue?

2025.1.0.dev202412110235

### In which browser are you experiencing the issue with?

Both Firefox and Chrome

### Which operating system are you using to run this browser?

Arch Linux

**Comment by tbrasser** [comment]
Workaround is using my home assistant links (eg from website)
