### ISSUE TITLE
data_description label is close to the wrong field

### ISSUE THREAD

**Issue by abmantis** [home-assistant/frontend#23274]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The data_description label is closer to the next field instead of being close to the field it belongs to. 
In the following example, it looks like it belongs to Port and not Host:

![image](https://github.com/user-attachments/assets/a8643b8f-dcca-4a6d-a45c-4a5acce0a27e)

### Describe the behavior you expected

The data_description label should be close to the field it belongs to. 

### Steps to reproduce the issue

1. Go to the Integrations page
2. Press "Add Integration"
3. Choose "Adguard Home"

### What version of Home Assistant Core has the issue?

2024.12.1

### In which browser are you experiencing the issue with?

Firefox 133.0. Also happens on the Android app

### Which operating system are you using to run this browser?

NixOS 24.11

**Comment by silamon** [comment]
Duplicate of https://github.com/home-assistant/frontend/issues/21312, the issue here is that rendering markdown using marked in the description adds a strange padding in the ha-textfield.

**Comment by abmantis** [comment]
Closing as duplicate of #21312
