### ISSUE TITLE
Music Assistant missing files

### ISSUE THREAD

**Issue by baulaergrungim** [home-assistant/frontend#23346]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

It seems like Music Assistant is too case-sensitive when it comes to extensions, which results in audio files with extensions that are not only in lowercase to be missing. On the other hand, HA itself sees those files and displays them in Media tab.
![Music_Assistant_–_Home_Assistant_-_Google_Chrome_2024-12-20_00-55-12](https://github.com/user-attachments/assets/2eb8dc06-b100-4f73-8291-3a6efe1befa4)

### Describe the behavior you expected

Music Assistant should see, play and list all the audio files in folders, regardless if they have extensions .mp3, .Mp3, .MP3 etc.  Just like HA's media.

### Steps to reproduce the issue

1. Add media to Music Assistant with extensions with uppercase letters in them, ie ".Mp3"
2. Go to Music Assistant to find those files - doesn't matter if by Artist, Album, Track, or using the Browser
3. See no files with extensions that are not just lowercase
...

### What version of Home Assistant Core has the issue?

2024.12.4

**Comment by karwosts** [comment]
I don't think Music Assistant is developed here, maybe they have their own github repository somewhere? I don't think it's part of HA frontend.

**Comment by baulaergrungim** [comment]
MA is officially part of HA since this month, And the links in MA integration lead to HA github, so I believe this is the place. THe question is if it's frontend or core, but this page also lead to HA github on the left https://www.home-assistant.io/integrations/music_assistant

**Comment by silamon** [comment]
I guess, you will need to open an issue at core: https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+music_assistant%22

**Comment by karwosts** [comment]
I guess this is from the MA add-on. I don't think that screenshot is rendering anything from the fronend.

**Comment by silamon** [comment]
On a closer look, it indeed comes from their add-on. Open an issue here: https://github.com/music-assistant/hass-music-assistant/issues 
(Looking more closely, the file extensions of your missing files are "Mp3" and not "mp3". )
