### ISSUE TITLE
Netmask is overwritten with incorrect data

### ISSUE THREAD

**Issue by marksteward** [home-assistant/frontend#23347]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The /config/network page allows setting of static IP addresses. When a user enters an IP with a prefix length, it automatically updates the netmask to match the prefix. However, when a prefix length is not included (the default), it replaces the netmask with 255.255.255.255, and it's not obvious that this has happened. A user who does this will probably find the change applies but they're unable to reach HA from the network afterwards.

### Describe the behavior you expected

The netmask should only be changed if the user supplied a prefix length. A user who only changed the last digit of an IP address would not expect to check the netmask afterwards. It won't work to only change the netmask if not already set, because 255.255.255.255 isn't a helpful default.

The prefix length is also not populated in the other direction - editing the mask to 255.255.255.0 does not append /24 to the IP address.

### Steps to reproduce the issue

1. Visit /config/network
2. Start configuring a Static IPv4 for one of the interfaces (you don't need to save the change)
3. Set the netmask to 255.255.255.0 (this may already be the case)
4. Set the IP address to 192.168.1.1 and click or tab out of the field
5. The netmask is replaced with 255.255.255.255, which is incorrect

### What version of Home Assistant Core has the issue?

2024.12.4

### In which browser are you experiencing the issue with?

Chrome 131.0.6778.109

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
You probably already have a network adapter with IPv4.
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

### Additional information

- `_handleInputValueChanged` calls `parseAddress` [when the address is changed](https://github.com/home-assistant/frontend/blob/2fe6203/src/panels/config/network/supervisor-network.ts#L658)
- `parseAddress` assumes the IP address is in CIDR notation and calls `cidrToNetmask` [on the prefix length](https://github.com/home-assistant/frontend/blob/2fe6203/src/data/hassio/network.ts#L120-L121)
- `cidrToNetmask`  calculates an undefined prefix as `NaN`, resulting in a `bits` of -1, which is the same as /32
- `_handleInputValueChanged` updates the netmask [to the result](https://github.com/home-assistant/frontend/blob/2fe6203/src/panels/config/network/supervisor-network.ts#L659-L660)

**Comment by marksteward** [comment]
See also #23246

**Comment by marksteward** [comment]
I think it's enough for `_handleInputValueChanged` to exit early if there's no `/` in the address. Treating `parseAddress` as opaque doesn't make sense because the rest of the code assumes a netmask has been provided, which isn't the case when first switching to Static IP. So a "complete" fix would involve allowing for a null netmask in `parseAddress`, `formatAddress`, and the internal interface state. Easier to just not update until both fields are filled.

**Comment by karwosts** [comment]
Maybe fixed by https://github.com/home-assistant/frontend/pull/23348 ?

**Comment by marksteward** [comment]
Ahh, thanks. That's not a great fix, it still overwrites the mask without warning, just with /24 instead of /32.

It would be better to do something like this:

```
  const [ip, cidr] = address.split("/");
  const isIPv6 = address.includes(":");
  mask = cidr ? cidrToNetmask(cidr, isIPv6) : null;
  return { ip, mask };
```

And then in `_handleInputValueChanged`:

```
      const { mask } = parseAddress(value);
      if (mask) this._interface[version]!.address![index] = formatAddress(value, mask);
```
