### ISSUE TITLE
German translation issue: "Obergrenze" ("Above mode") and "Untergrenze" ("Below mode") is incorrect / swapped (In automation if-then building block)

### ISSUE THREAD

**Issue by MattJanss** [home-assistant/frontend#23353]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Here we see an "If-then" building block in a "Then do" section of an automation in the german language.
The conditions are: `x > 25.9 && x < 26.1`.

The generated title ("Wenn Heizung (Schlafzimmer) über 25.9 und unter 26.1 ist") is absolutely clear and fine.
The labels for the fields ("Unter", "Über") are clear and fine.

However: The titles Obergrenze and Untergrenze make no sense in this context.

---

## Current UI

![automation if-then building block](https://github.com/user-attachments/assets/d1abc473-8f73-4235-8d39-e7b475410777)

### Describe the behavior you expected

Obergrenze should represent a high value that must not be exceeded (in order to produce `true`, and therefore execute the "Then*" action of the "If-then" building block).
Untergrenze should represent a low value that must not be undercut (in order to produce `true`, and therefore execute the "Then*" action of the "If-then" building block).

Currently, the semantic is swapped and incorrect.
Obergrenze and Untergrenze must be swapped to solve this.
Additionally, since the logic is currently only available in exclusive mode (`<` instead of `<=`, `>` instead of `>=`),
we should supply extra information that the value is exclusive, since the default semantic of "Obergrenze" and "Untergrenze" implies an inclusive behavior.

I am aware that this is a (german) language / translation specific problem.

That means:
- "Above mode" should be translated as "Untergrenze (exklusiv)" or "Untergrenze (exkludiert)" or "Untergrenze (exkludierend)". (Currently: "Obergrenze")
- "Below mode" should be translated as "Obergrenze (exklusiv)" or "Obergrenze (exkludiert)" or "Obergrenze (exkludierend)". (Currently: "Untergrenze")

---

## Example of how the expected UI should look

![expected ui](https://github.com/user-attachments/assets/a11cd99e-8f08-403c-9501-41c903da8b9f)

### Steps to reproduce the issue

1. Go to your profile [left sidebar, all the way at the bottom]
2. Change user language to "Deutsch" ("German") [first dropdown]
3. Click on "Einstellungen" ("Settings") [left sidebar, bottom section]
4. Click on "Automatisierungen & Szenen" ("Automations & scenes") [third button from the top]
5. Click on "Automatisierung erstellen" ("Create automation") [pill button on bottom right corner]
6. Click on "Neue Automatisierung erstellen" ("Create new automation") [first button]
7. Navigate to the "Dann" ("Then do") section [last section]
8. Click on "Baustein hinzufügen" ("Add building block") [second button]
9. Add the "Wenn-dann" ("If-then") building block
10. Inside the added building block, under "Wenn*" ("If*"), click on "Bedingung hinzufügen" ("Add condition") [first button]
11. Select "Entität" ("Entity"), then "Numerischer Zustand" ("Numeric state")

You can now see
- the "Numerischer Zustand" ("Numeric state") component.
- that "Above mode" has been translated to "Obergrenze", which is incorrect.
- that "Below mode" has been translated to "Untergrenze", which is incorrect.

### What version of Home Assistant Core has the issue?

2024.12.4

### Problem-relevant frontend configuration

```yaml
if:
  - condition: numeric_state
    above: 25.9
    below: 26.1
then: []
```

**Comment by karwosts** [comment]
I suggest you go to Lokalise (see [instructions](https://developers.home-assistant.io/docs/translations/)), and there you can make this change (or discuss it with the German translators). 

Generally we don't track individual language translation errors here, as we developers don't know all the languages.

**Comment by NoRi2909** [comment]
@MattJanss Thanks for reporting and fixing in Lokalise.

Bugfix is correct, I had these two swapped. Thanks!

You can close the issue as fixed.
