### ISSUE TITLE
Binary sensor does not refresh on "Reset all yaml configuration"

### ISSUE THREAD

**Issue by dhoeben** [home-assistant/frontend#23380]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I created a `tod` sensor using yaml. When I wanted to refresh the configuration to let it show in the UI and State tab. After refreshing in the Developer area, the `binary_sensor` did not show up. However, after a restart it did.

I also tried to make an error in the `tod` sensor, just to see if the "Check Configuration" checks the `binary_sensor`. This indeed gave an error that there was something wrong with my configuration. So that part works, just not the actual refreshing.

Correct yaml used for sensor:
```yaml
binary_sensor:
  - platform: tod
    name: Time Day
    after: "07:30"
    before: "18:00"
    unique_id: time_day
```

### Describe the behavior you expected

When I press the "All yaml configuration" button under Reload, that it reloads the binary sensor.

### What version of Home Assistant Core has the issue?

core-2024.12.5

### What was the last working version of Home Assistant Core?

core-2024.x.x

**Comment by karwosts** [comment]
This is more of a core issue than a frontend issue. 

But yes the hot reload only works for integrations that support reloading, and only once they have already been started. 

If you're adding a new integration to the config for the first time, you always need to restart.

**Comment by ildar170975** [comment]
> When I press the "All yaml configuration" button under Reload, that it reloads the binary sensor.

It affects only integrations listed under that "All yaml configuration" line.
The `tod` integration is not amongst them.

**Comment by dhoeben** [comment]
Ah never mind then, I figured it fell under `binare_sensor`. My bad!
