### ISSUE TITLE
automatic backup feature

### ISSUE THREAD

**Issue by Anto79-ops** [home-assistant/frontend#23411]
### The problem

hello!

I setup the automatic backup feature on 2025.1.0b0 (thanks for adding this!), and selected my settings and saved. It created a backup immediately, however, when checking the backup page, it shows that I have no automatic backups, but there is 1 listed. Does this mean it just didn't run for the first time on its own or perhaps a bug:

![image](https://github.com/user-attachments/assets/acc7fc66-bc24-4029-8873-9f9ee55422ba)

FYI, I originaly setup the backup locations to all possible locations, 3 local and 1 Nabu Casa cloud. However, the backup is 13.1 GB and it failed to upload to Nabu Casa, so I checked off Nabu Casa:

![image](https://github.com/user-attachments/assets/bb743e82-5b76-4b23-b0f0-df624cc05e58)

just in case those logs are here:

```
Logger: homeassistant.components.backup
Source: components/cloud/backup.py:173
integration: Backup (documentation, issues)
First occurred: 10:30:20 AM (1 occurrences)
Last logged: 10:30:20 AM

Error during backup upload - Failed to get upload details
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/cloud/backup.py", line 164, in async_upload_backup
    details = await async_files_upload_details(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/hass_nabucasa/cloud_api.py", line 75, in check_token
    return await func(cloud, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hass_nabucasa/cloud_api.py", line 280, in async_files_upload_details
    resp.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1161, in raise_for_status
    raise ClientResponseError(
    ...<5 lines>...
    )
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url='https://servicehandlers.nabucasa.com/files/upload_details'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/cloud/backup.py", line 173, in async_upload_backup
    raise BackupAgentError("Failed to get upload details") from err
homeassistant.components.backup.agent.BackupAgentError: Failed to get upload details
```

and

```
Logger: hass_nabucasa.cloud_api
Source: components/cloud/backup.py:164
First occurred: 10:30:20 AM (1 occurrences)
Last logged: 10:30:20 AM

Fetched https://servicehandlers.nabucasa.com/files/upload_details (400) NC-SH-FH-03 (b82da7663383417582fcb09aee097af3)
```

re-triggering the automatic backup with Nabu Casa clound option disabled, removes that error message on top and its a sucess:

![image](https://github.com/user-attachments/assets/2f2527ca-9fc5-47ef-bd36-61f7b71ada3a)

### What version of Home Assistant Core has the issue?

2025.1.0b0

### What was the last working version of Home Assistant Core?

n/a new feature

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

backup

**Comment by piitaya** [comment]
Moved it to frontend as it’s a frontend issue.

**Comment by bramkragten** [comment]
Fixed in https://github.com/home-assistant/frontend/pull/23430
