### ISSUE TITLE
Setup dialog for Authenticator app (TOTP) broken

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#23413]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When trying to set up TOTP the QR code does not come up anymore.

Instead the dialog looks like this (in browser and on mobile):

![image](https://github.com/user-attachments/assets/37aecad1-755e-42ee-ba3e-103ad1ddb2d5)

### Describe the behavior you expected

I'm not sure when I tried the last time and the QR code was still shown here.

### Steps to reproduce the issue

1. Go to your account page.
2. Tab Security.
3. Under Multi-factor authentication modules click on Enable.

### What version of Home Assistant Core has the issue?

2025.1.0b0

### What was the last working version of Home Assistant Core?

2024.12.x

### In which browser are you experiencing the issue with?

Google Chrome 132.0.6834.52 beta (64-Bit)

### Which operating system are you using to run this browser?

Chrome OS

**Comment by silamon** [comment]
There's also an issue with the dialog header.

**Comment by bramkragten** [comment]
@silamon whats with the header?

**Comment by silamon** [comment]
Margin is no longer applied when a scrollbar is given. (Pretty minor, but changed with https://github.com/home-assistant/frontend/pull/23284)
