### ISSUE TITLE
Automated backup option The number of backups that are saved has 'Days' option

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#23419]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

<img width="696" alt="Scherm­afbeelding 2024-12-23 om 22 33 03" src="https://github.com/user-attachments/assets/72222540-e1eb-4a61-bd4e-8697e04e7405" />

raised per discussion in #beta on Discord

### Describe the behavior you expected

Either show a different text, or dont have a Days count as option for Backups...

### Steps to reproduce the issue

1. check Screen shot
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.1.0b0

**Comment by frenck** [comment]
To clarify from the Discord discussion, the field data description says:

![CleanShot 2024-12-23 at 22 43 25](https://github.com/user-attachments/assets/2ff0537a-b6ef-4da3-ace6-da48e62cd400)

However, one can select the number of days, which is the confusing part. We should reconsider the text in the data description.

**Comment by matthiasdebaat** [comment]
I suggest to change the description to: `Based on maximum number of backups or maximum number of days`
