### ISSUE TITLE
Automatic Backup: The copy/paste icon in "Save current encryption key" doesn't work!

### ISSUE THREAD

**Issue by jodomi** [home-assistant/frontend#23414]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The copy icon in Save current encryption key doesn't work! Nothing to paste!

### Describe the behavior you expected

The copy icon in Save current encryption key works!

### Steps to reproduce the issue

1. Automatic Backup 
2. Configure Automatic Backups
3. Encryption Key
4. Change
5. Click on Copy icon
6. Paste elsewhere
...

### What version of Home Assistant Core has the issue?

core 2025.1.0b0

### In which browser are you experiencing the issue with?

Chrome est à jour Version 131.0.6778.205 (Build officiel) (64 bits)

### Which operating system are you using to run this browser?

Windows 11 23H2

**Comment by bramkragten** [comment]
Weird, I can not seem to reproduce this...

**Comment by jodomi** [comment]
Still in version 2025.1.0b1, copy/paste OK with "entityID"  but "change encryption key" not!

**Comment by silamon** [comment]
There's a possible fix in 2025.1.0b2. 
There was a similar report on discord for the button to not work in the backup onboarding, while it works in the developer tools.

**Comment by jodomi** [comment]
Core 2025.1.0b2: Still no copy with the button (the confirmation message is there!), selecting the new key works with copy/paste is OK.

**Comment by WoBBeLnl** [comment]
Have you enabled the right permissions for the page? AFAIK you can disable/enable those permissions. 

Maybe it only works via HTTPS but haven't tested that.

**Comment by jodomi** [comment]
What permission? I can copy and paste (the encryption key for example). I can also copy/paste an entity ID button and I'm not using HTTPS. Firefox or Google Chrome, same battle.

**Comment by karwosts** [comment]
I can also report it's not working for me. 

Every other "Copy to Clipboard" button in the frontend seems to work except this one. My windows clipboard is not modified when I press the button. Maybe something about how it's being used within a dialog makes it different?

**Comment by karwosts** [comment]
```
  const el = document.createElement("textarea");
  el.value = str;
  document.body.appendChild(el);
  el.select();
  document.execCommand("copy");
  document.body.removeChild(el);
```

I will guess that el.select() can't select the element because the dialog is preventing selecting something behind the dialog?

Note that if I highlight some other text in the dialog, and hit the copy button, that highlighted text is copied instead of the key. That suggests that the desired element is actually not being selected.

Not sure why it works for some people. 

![clipboard](https://github.com/user-attachments/assets/f3e0a785-af3c-4a89-9aa5-a0036e9fbf6c)

**Comment by silamon** [comment]
The dialog prevents cancellation, so it will prevent selecting anything outside including the textarea created when navigator.clipboard doesn't work.

**Comment by jodomi** [comment]
Still in version 2025.1.0b3, copy/paste OK with "entityID" but "change encryption key" not!

**Comment by silamon** [comment]
This issue is still unresolved as long as it is open. Good thing is that the cause is known.

**Comment by bramstroker** [comment]
I have the same issue in beta 3. Copying using the button doesn't work. 
Using Macbook Pro. Google chrome 131.0.6778.205
Selecting and just cmd C works fine.

Will see if I can get some more details when I have some more time.

**Comment by bramkragten** [comment]
> Not sure why it works for some people.

It will work in a secure context as it then uses the `navigator.clipboard` API :-)
