### ISSUE TITLE
Oauth credentials screen doesn't show up

### ISSUE THREAD

**Issue by joostlek** [home-assistant/frontend#23429]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

So when adding an integration that requires oauth credentials (fitbit/withings/spotify/husqvarna), the popup to add my application credentials does not show up after the popup that loads the config flow dissapears. It only shows up after I started another config flow (not necessarily with oauth).
<img width="529" alt="image" src="https://github.com/user-attachments/assets/56ff9d0b-b59d-4ba1-9dd6-8496a2c569e2" />

### Describe the behavior you expected

I would expect the oauth credentials popup to come up immediately

### Steps to reproduce the issue

1. Start a config flow for Husqvarna
2. See the spinner pop up dissapear
3. See the nothingness
4. Start a new flow for accuweather
5. Now see the husqvarna application credentials popup
6. profit

### What version of Home Assistant Core has the issue?

2025.1.0b0

### What was the last working version of Home Assistant Core?

2024.12 also has this issue

### In which browser are you experiencing the issue with?

Firefox 133

### Which operating system are you using to run this browser?

macOS something

**Comment by bramkragten** [comment]
Yeah it is a race condition...
