### ISSUE TITLE
Background "Transparency"

### ISSUE THREAD

**Issue by Chompy80** [home-assistant/frontend#23447]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The description of this setting does not match the functionality.  100% **transparent** would make the background clear/invisible.  The scale needs to be reversed, otherwise the setting should be called "Background **opacity**" to accurately describe the functionality.

<img width="568" alt="image" src="https://github.com/user-attachments/assets/f542f0b7-97c7-4b30-bbfc-c17a7c79a20c" />

### Describe the behavior you expected

I expected "100% transparent" to make the background invisible, however it does the opposite.

### Steps to reproduce the issue

N/A - Minor issue with feature name.

### What version of Home Assistant Core has the issue?

core-2025.1.0b1

### What was the last working version of Home Assistant Core?

core-2024.12.5

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

Sequoia 15.2

**Comment by silamon** [comment]
Fully agree, I've opened a PR to change it. (It will also change they key in the yaml to match better, so there's a breaking change coming in. )
