### ISSUE TITLE
Backups - manually deleting most recent automatic backup shows false "backup failed" error card

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#23483]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If you manually delete the most recent automatic backup and then return to your backup panel, it will say that "Last automatic backup failed"  and that it "wasn't successful" even though that's not true. The backup doesn't exist but in this case it was a manual delete action performed by the user and NOT a failed backup.

https://github.com/user-attachments/assets/a0f7d7d4-6490-4ee8-9657-851b2fed5bcd

### Describe the behavior you expected

Don't show backup failed when the user manually deletes a backup

### Steps to reproduce the issue

See screen recording above, but:

1. Create an automatic backup
2. Click into "My backups" and delete the most recent backup
3. After returning to the main backup page, it will say "Last automatic backup failed"  and that it "wasn't successful"

### What version of Home Assistant Core has the issue?

2025.1.0b2

**Comment by bramkragten** [comment]
We currently don't have the data available we need for this, will discuss this with core
