### ISSUE TITLE
Gas sensor in m³ not available in Energy Dashboard

### ISSUE THREAD

**Issue by M4v3r1cK87** [home-assistant/frontend#23509]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I've write a template sensor for convert the kWh sensor for Gas consumption, into a m³ template sensor with device class "gas" and state class "total_increasing", but this sensor is not available into the Energy Dashboard; is not possible to add this sensor into the Gas Consumption metering.

        - name: "Consumo Gas Giornaliero Acqua Calda Sanitaria"
            unique_id: "consumo_gas_giornaliero_acqua_calda_sanitaria"
            state: >
              {% set kwh = states('sensor.energy_hot_water') | float (default=0) %}
              {% set MJ_to_kwh = 0.2778 | float %}
              {% set coefficiente_correttivo_mc_to_smc = 1.017370 | float %}
              {% set potere_calorifero_MJ_to_mc = 39.9574 | float %}
              {{ (kwh / (MJ_to_kwh * potere_calorifero_MJ_to_mc * coefficiente_correttivo_mc_to_smc)) | round(4) }}
        unit_of_measurement: "m³"
        device_class: "gas"
        state_class: total_increasing
        icon: mdi:fire-circle

### Describe the behavior you expected

Possibility to add also the m³ sensor into the Gas Consumption Energy Dashboard

### Steps to reproduce the issue

1. Create a m³ template sensor
2. Try to add this sensor into the Gas Consumption Energy Dashboard

### What version of Home Assistant Core has the issue?

2024.12.5

**Comment by karwosts** [comment]
If that's an actual copy of your sensor the indentation is all wrong for the last 4 lines, but it may just be a copy/paste error into github?

**Comment by karwosts** [comment]
Gas can work with m3 but you can't mix and match watts and volume.

Your gas sensors have to all be energy or all be volume. Do you have other energy sensors already in the gas category?

**Comment by M4v3r1cK87** [comment]
> Gas can work with m3 but you can't mix and match energy and volume.
> 
> Your gas sensors have to all be energy or all be volume. Do you have other energy sensors already in the gas category?

Yes, the raw value not converted into m3 (in kWh measure -- it's the sensor that must be converted into m3)

**Comment by M4v3r1cK87** [comment]
Oh wow... I've deleted all the Gas Consumption energy sensor, and now the values admited are:
CCF, ft³, m³, cal, Gcal, GJ, GWh, J, kcal, kJ, kWh, Mcal, MJ, MWh, TWh, Wh.

There are some other measures...
In this way is forviant message... I think must be corrected in some way.
After deleting the old measure, now work..
