### ISSUE TITLE
LoveLace uses 'primary-color' on both foreground and background elements making theming difficult. (Especially dark themes)

### ISSUE THREAD

**Issue by OrangeFlick** [home-assistant/frontend#2709]
**Home Assistant release with the issue:**
0.86.4

**Last working Home Assistant release (if known):**
N/A

**Browser and Operating System:**
Hass.io
Chrome 71.0.3578.98 (Official)

**Description of problem:**
In developing a "night theme", the states view incorrectly uses "primary-color" to theme the text.  I believe it should use "primary-text-color" or one of the text variants.  This makes any dark theme difficult to read.  (foreground and background aren't different)

To reproduce, use this theme: (and browse to: "<your_url>/dev-state"

```
ThemeNighttime:
  # App Styles
  app-drawer-layout-content-transition: none
  app-drawer-width: 265px
  app-drawer-scrim-background: rgba(0, 0, 0, 0.5)
  app-toolbar-font-size: 20px
  # Primary Colors
  primary-text-color: '#cccccc'                  # app-toolbar, badge letter
  secondary-text-color: '#969696'
  disabled-text-color: '#646465'
  primary-background-color: '#1e1e1e'            # app-toolbar
  secondary-background-color: '#252526'          # more info header
  light-primary-color: '#252526'                 # badge background
  accent-color: '#cccccc'
  error-color: 'red'
  primary-color: '#252526'                       # Header bar background
  text-primary-color: '#cccccc'                  # Header bar falls back to white
  dark-primary-color: '#646465'
  # Dialogs
  paper-dialog-color: '#cccccc'                  # Falls back to primary-text-color
  paper-dialog-button-color: '#1e1e1e'           # Falls back to primary-color
  paper-dialog-background-color: '#1e1e1e'       # Falls back to primary-background-color
  # Sidebar
  sidebar-text-color: '#adadad'
  sidebar-icon-color: '#adadad'
  sidebar-selected-text-color: '#ffffff'
  sidebar-selected-icon-color: '#ffffff'
  sidebar-background-color: '#252526'            # Falls back to primary-background-color
  # Dividers
  divider-color: '#616162'
  # Items
  paper-item-min-height: 48px
  paper-item-selected-weight: bold
  paper-item-disabled-color: '#646465'           # Falls back to disabled-text-color
  paper-item-icon-active-color: '#ffe680'        # Falls back to #fdd835
  paper-item-icon-width: 56px
  paper-item-icon-color: '#5696d6'               # Falls back to #44739e
  # Icons
  paper-icon-button-ink-color: '#5696d6'         # Falls back to primary-text-color
  paper-icon-button-disabled-text: '#646465'     # Falls back to disabled-text-color
  paper-icon-button-active-color: 'fuchsia'      # Falls back to primary-color
  paper-icon-button-inactive-color: 'fuchsia'    # Falls back to primary-text-color
  # Toggles
  paper-toggle-button-invalid-ink-color: '#5696d6' # Falls back to error-color
  paper-toggle-button-invalid-button-color: 'fuchsia' # Falls back to error-color
  paper-toggle-button-invalid-bar-color: 'fuchsia' # Falls back to error-color
  paper-toggle-button-label-color: 'fuchsia'  # Falls back to primary-text-color
  paper-toggle-button-checked-bar-color: '#7f9340' # Fall back to primary-color
  paper-toggle-button-checked-button-color: '#ffe680' # Falls back to primary-color
  paper-toggle-button-checked-ink-color: '#5696d6' # Falls back to primary-color
  paper-toggle-button-unchecked-ink-color: '#5696d6'  # Falls back to primary-text-color
  paper-toggle-button-unchecked-button-color: '#1e1e1e' # Falls back to paper-grey-50
  paper-toggle-button-unchecked-bar-color: '#404040'  # Falls back to #000000
  # Tabs
  paper-tab-ink: '#5696d6'                       # Falls back to paper-yellow-a100 
  paper-tabs-selection-bar-color: '#5696d6'      # Falls back to text-primary-color
  # Listbox
  paper-listbox-color: '#cccccc'                 # Falls back to primary-text-color
  paper-listbox-background-color: '#252526'      # Falls back to primary-background-color
  # Cards
  paper-card-header-color: '#cccccc'             # Falls back to black
  paper-card-background-color: '#252526'         # Falls back to white
  # States
  state-icon-unavailable-color: 'fuchsia'
  # Toast
  paper-toast-background-color: '#1e1e1e'        # Falls back to #323232
  paper-toast-color: '#cccccc'                   # Falls back to #f1f1f1
  # Slider
  paper-slider-bar-color: transparent            # Falls back to transparent
  paper-slider-container-color: '#5696d6'        # Falls back to paper-grey-400
  paper-slider-font-color: '#cccccc'             # Falls back to white
  paper-slider-knob-color: '#1e1e1e'             # Falls back to google-blue-700
  paper-slider-active-color: '#5696d6'           # Falls back to google-blue-700
  paper-slider-secondary-color: '#5696d6'        # Falls back to google-blue-300
  paper-slider-disabled-active-color: '#646465'  # Falls back to paper-grey-400
  paper-slider-disabled-secondary-color: '#646465'  # Falls back to paper-grey-400
  paper-slider-height: 2px                       # Falls back to 2px

```
![darktheme](https://user-images.githubusercontent.com/47465166/52512392-6847f080-2bb9-11e9-98eb-7b936f37799a.JPG)

**Comment by OrangeFlick** [comment]
There are a few other place.  Here is another one on the Hass.io where
![darktheme2](https://user-images.githubusercontent.com/47465166/52513426-93354300-2bbf-11e9-8cc1-e560a77f15fa.JPG)
 the text is 'primary-color'.

**Comment by OrangeFlick** [comment]
BTW, I should have called out the issue, not the fix.  From what I can tell, if the header bar was another color (similar to how sidebar-background-color is) then that would solve it also.  The background to the header is primary-color, so if that was changed, then primary-color could be light (for dark themes) and all the places where it is used for text would be fine.

On another note: it would be great if each section had their own theme, with fall backs to a general one.  For instance, the header bar would have header-bar-background and fall back to primary-background-color if not defined.

**Comment by OrangeFlick** [comment]
To make this super clear (I'm a developer and know how unclear these bugs can be) here is a screen shot of the issue.  The background (fuchsia) at the top uses the same color as various text throughout the UI.  (See "reload core", etc... 
![darktheme3](https://user-images.githubusercontent.com/47465166/52514355-bfec5900-2bc5-11e9-8ce0-01484e6fd4d3.JPG)

**Comment by BaSoMaTiX** [comment]
I'm having problems creating themes because of this too. Let's hope they can be seperated. I think it would give the theming-community a little boost if it was solved because it seems like almost every dark style skin has the same problem with unreadable text in the configuration panels.

**Comment by wzwick** [comment]
+1 
it also makes entity sliders and section headers invisible on 50% grey

**Comment by 3ative** [comment]
@OrangeFlick Addthis line to your theme, it will give you control over the ##"Reload..."## text color
*** mdc-theme-primary: "#008685"***

**Comment by juhurus** [comment]
I'm stuck with the same issue as OrangeFlick. Is there any progress or solution to this issue?

**Comment by mstephens94** [comment]
Fixing the entities name text color on the state's page:
https://github.com/home-assistant/home-assistant-polymer/pull/3412

**Comment by mammuth** [comment]
Mostly this issue probably arises when people want to style the header in a more decent color than the primary color.

Thus, an improvement to the issue might be to introduce a dedicated variable for the background-color of the `app-header` (with a fallback on `--primary-color` eg.:
```
--app-header-background: var(--primary-color);

app-header, app-toolbar {
    background-color: var(--app-header-background);
}```

This decoupling seems to make sense anyway.

**Comment by juhurus** [comment]
In case you guys missed this: [https://github.com/home-assistant/home-assistant-polymer/pull/3412](https://github.com/home-assistant/home-assistant-polymer/pull/3412)

**Comment by TheLastProject** [comment]
This is also an issues for labels in the entity card, which use `--primary-color`: https://github.com/bbbenji/synthwave-hass/issues/3

**Comment by carlos-sarmiento** [comment]
@mammuth I like your idea, and would be happy to create a PR, but I don't know where the header background is being set. I've searched like crazy with no success

**Comment by brucehvn** [comment]
This is the same case for where the mdc-button is used for things like save buttons and most buttons in HACS.  The mdc-button ends up picking up the --primary-color as it's non-disabled text color which doesn't work well on dark themes either.
