### ISSUE TITLE
Create person button not visible when adding with multiple devices

### ISSUE THREAD

**Issue by traveaston** [home-assistant/frontend#2818]
**Home Assistant release with the issue:**

0.88

**Last working Home Assistant release (if known):**

**Browser and Operating System:** 

Chrome 73.0.3683.46 beta (64-bit), macOS 10.14.4

**Description of problem:**

When adding a new Person and adding 3 or more devices attached to that person, the Create button is pushed off the page and scroll is disabled.
[Okay with 2 devices](https://drive.google.com/open?id=18kGrIdb602tUaCBDyHc1Cf2UJAzH5Icq)
[Not okay with 3 devices](https://drive.google.com/open?id=1kB7TVimZ5c45mwH6E5or6x0r33GRVYM_)
Obviously these screenshots are captured to the bottom of my screen.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
My browser resolution is equal to 1280x800 (13" macbook, scaled)
There does seem to be a scrollbar added with 4 devices, but the button is outside the scope of the scroll area.
After resizing the browser window, the css calculations refresh (or something) and all is well. Maybe force this resize/recalc when adding additional devices?

**Comment by zsarnett** [comment]
This ahas been resolve by adding a scroll bar to this popup
