### ISSUE TITLE
While zooming on the map panel, zones scale incorrectly.

### ISSUE THREAD

**Issue by ryanwinter** [home-assistant/frontend#2853]
**Home Assistant release with the issue:**
0.88.1

**Last working Home Assistant release (if known):**

**Browser and Operating System:**

Windows 10, Chrome 72.0.3626.109

**Description of problem:**
When looking at the map panel and pinch zooming on my phone, my home zone scales incorrectly compared to the map. It moves location.

Once zooming has finished, the zone snaps back to the correct position.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by exxamalte** [comment]
I just tested this with Safari on an iPhone (iOS 12.1.4).
The zone moves while I am pinch zooming, and once I stop the zone jumps back to its correct location in the correct size.

**Comment by ryanwinter** [comment]
> I just tested this with Safari on an iPhone (iOS 12.1.4).
> The zone moves while I am pinch zooming, and once I stop the zone jumps back to its correct location in the correct size.

Yes sorry I didn't mention that, I have updated the description to include this detail.

**Comment by SeanPM5** [comment]
Still an issue on 0.104.3 (for stale bot)

**Comment by ryanwinter** [comment]
Fixed
