### ISSUE TITLE
Lovelace card title font size

### ISSUE THREAD

**Issue by eggman0131** [home-assistant/frontend#2946]
**Home Assistant release with the issue:**
0.89.0

**Last working Home Assistant release (if known):**
none

**UI (States or Lovelace UI?):**
lovelace

**Browser and Operating System:**
all

**Description of problem:**
It would be good if there were a single, consistent way to set lovelace card title font-size in themes.

Card Title font size set in themes is not applied to all of the "standard" cards.

I can use paper-font-headline_-_font-size to set the title font size in entities cards, although possibly paper-font-title_-_font-size would make more sense.

However, this variable is not used by either the picture-entity card, the glance card, or the history graph (that's all I've tried) which don't seem to provide any method of setting the title font height.

**Info from the web inspector :**

Font-size appears to be set directly rather than through the use of a variable.
```
.header:not(:empty) {
    font-size: 24px;
    letter-spacing: -0.012em;
    line-height: 32px;
    opacity: 0.87;
    padding: 24px 16px 16px;
}
```

**Additional information:**

**Comment by iantrich** [comment]
@balloob this probably doesn't even work in entities anymore now that we had to remove `@apply` in styles, right? Suggestions?

**Comment by iantrich** [comment]
Relevant https://github.com/Polymer/lit-element/issues/633

**Comment by balloob** [comment]
As the linked Lit issue states, `@apply` never got standardized. The only thing we can do is to expose certain parts as CSS Variables.

**Comment by KTibow** [comment]
You can style this via `--ha-card-header-font-size`, consider closing?
