### ISSUE TITLE
history-graph - Cancel and Save buttons are not visible/out of the screen

### ISSUE THREAD

**Issue by DominikPalo** [home-assistant/frontend#3215]
**Home Assistant release with the issue:**
0.93.1

**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
OS: macOS Mojave 10.14.4
Browser: Google Chrome 74.0.3729.157

**Description of problem:**
When I try to edit a history-card with 3 and more graphs the editor window is unusable - the bottom part of the editor with Cancel and Save buttons are rendered out of my screen (see the screenshot). I can't scroll, save or discard changes and I'm not even able to close the card editor using my keyboard (e.g. by Esc key) - only the browser refresh helps.

![image](https://user-images.githubusercontent.com/1623257/58349436-9a791780-7e63-11e9-81be-88858bab7f49.png)

**Comment by skullydazed** [comment]
I have also encountered this issue. You can watch a video of it happening here: https://www.youtube.com/watch?v=f8qgigYBuHU

As shown in the video you can work around the bug by clicking show code editor. This will bring the Save and Cancel buttons into view and properly scroll the window, even after switching back to the visual editor.
