### ISSUE TITLE
Handle missing manufacturer information

### ISSUE THREAD

**Issue by tetienne** [home-assistant/frontend#3216]
**Home Assistant release with the issue:** 0.93

**Description of problem:**
When the manufacturer of a device is not provided, several pages have incomplete text:
- Config flow success dialog (empty braces)
- Integration page (by is followed by an empty string)

**Additional information:**
https://github.com/home-assistant/home-assistant-polymer/blob/82e8ca2754e545f743352343803063d54c437c32/src/dialogs/config-flow/step-flow-create-entry.ts#L73
![image](https://user-images.githubusercontent.com/8216238/58357952-1c296f00-7e7d-11e9-8fe8-97f8d8b9e4cf.png)

**Comment by tomraithel** [comment]
I would like to take care about that one

**Comment by spacegaier** [comment]
@tetienne Is that still a current issue or can it be closed?

**Comment by tetienne** [comment]
Let me double check tomorrow, but I think it's a valid use case.

**Comment by silamon** [comment]
This one is fixed after so many years.
