### ISSUE TITLE
input_datetime: no leading zero for hh:00 on firefox

### ISSUE THREAD

**Issue by tomlut** [home-assistant/frontend#3246]
**Home Assistant release with the issue:**

0.93.2

**Last working Home Assistant release (if known):**

Possibly occurred after the merger of Thomas Loven's time-input-row into core Lovelace.

**UI (States or Lovelace UI?):**

Lovelace

**Browser and Operating System:**

Windows 10, firefox 67.0 (64bit)

**Description of problem:**

Leading zeros are not displayed for input_datetime minutes when minutes == 00
e.g:
![ipdt](https://user-images.githubusercontent.com/10679300/58877804-12252d00-8715-11e9-9ca0-6ef627647bd5.png)

Just noticed that times like `6:02` display as `6:2` as well. Looks like leading zeros for all minute values are not displayed.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

This only occurs in Firefox. Safari and Chrome display correctly.

**Comment by tomlut** [comment]
This is still an issue in v0.98

**Comment by skymoo** [comment]
This is still an issue with v0.104.3

**Comment by skymoo** [comment]
No longer seems to be a problem with 0.109, not sure of when exactly it was fixed...

**Comment by tomlut** [comment]
Yep, seems to be fixed.
