### ISSUE TITLE
Script Editor shortcut to test / run script

### ISSUE THREAD

**Issue by ProLoser** [home-assistant/frontend#3251]
**Home Assistant release with the issue:**
0.92.2

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Chrome 74.0.3729.169 (Official Build) (64-bit)
OSX 10.14.5

**Description of problem:**
It would be nice if there was a 'Run Script' button in the top-right corner of the script editor for testing purposes.

**Additional information:**
Maybe a 'Delete Script' button too?

**Comment by bramkragten** [comment]
This is in 0.115

**Comment by thomasloven** [comment]
#6957
