### ISSUE TITLE
MJPEG Camera stream does not stop after browsing to another lovelace tab or closing camera popup.

### ISSUE THREAD

**Issue by vandalon** [home-assistant/frontend#3314]
**Home Assistant release with the issue:**
0.95

**Last working Home Assistant release (if known):**
Unknown

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Mac OS 10.14.5 && Safari 12.1.1 && Chrome 75.0.3770.100

**Description of problem:**
I'm not quite sure if this is a browser issue, a polymer issue or maybe even a home-assistant issue.

When opening a ( or multiple on one lovelace page) zoneminder camera view and closing it again/browsing to another tab, the browser keeps pulling data for quite some time. I checked for pre-caching option in the settings, and as far as I can see all the obvious pre-load settings are off.

**Javascript errors shown in the web inspector (if applicable):**
No errors.

**Additional information:**

**Comment by vandalon** [comment]
Should this be in the latest beta? If so, I think it's not working :)

**Comment by balloob** [comment]
Make sure you are running the latest frontend. Your browser will download this in the background. If possible, try with a different browser.

**Comment by vandalon** [comment]
Is there a way I can see the current frontend version?

I've just tested with 3 browsers (safari, chrome and firefox) in which i cleared browser data. In all 3 browsers the results is the same. I can see that traffic keeps flowing after browsing away from the camera view.

**Comment by balloob** [comment]
The beta 0 had some publication issues, wait for b1 and try again. If the sidebar is not like in [the demo](https://demo.home-assistant.io/#/lovelace/0), it is not the latest version.

**Comment by vandalon** [comment]
Hey Paulus,

I've tested again with b1 on all 3 browsers and I see no different behaviour. I can confirm I have the latest frontend (love it btw). I waited for a minute on all test to see the datastream only stop after a full browser refresh. If I can do something more I would love to help out.

**Comment by balloob** [comment]
Looked at Zoneminder implementation. It's an MJPEG stream. There are a bunch of problems with MJPEG streams across browsers.

**Comment by iantrich** [comment]
@vandalon still an issue?

**Comment by vandalon** [comment]
@iantrich; just checked with 0.99.3 and the issue is  still there with zoneminder which does mjpeg afaik.

**Comment by deliantwo** [comment]
I can confirm the problem with firefox 75.0 and homeassistant 0.108.2.
Looking at the network I see the following:
* Going to the entity list ->  I get the preview. One frame downloaded
* Clicking to get the live stream -> request on getting the live stream
* Closing the live stream -> I see a refresh of the entities, a new (completed) request for the preview still frame but the previous request for the live stream is still there, pending on getting data.

This is confirmed on the cam side ( I see the client asking for frames )

No issue with Chrome 81.0.4044.92

Tell me if you need more info.
