### ISSUE TITLE
Custom CSS no longer works in themes.yaml 0.97.0

### ISSUE THREAD

**Issue by jimz011** [home-assistant/frontend#3464]
**Home Assistant release with the issue: 0.97
**Last working Home Assistant release (if known): 0.96.5
**UI (States or Lovelace UI?): Lovelace
**Browser and Operating System: Any Browser, All Operating Systems

**Description of problem:**
Hi, I have an issue which is not documented anywhere in the releasenotes of 0.97.0. In my `themes.yaml` file I have defined some custom CSS. Example given:
```
slate-theme:
  test-color: green
```
In my card I have set the following (I use card-mod and markdown-mod, but it does it for any other card where css can be defined)
```
- type: markdown
  style: |
    ha-card {
      background: var(--test-color);
    }
  content: Blablabla
```
This used to make the card green. The thing is, it still does make the card green, but ONLY if I do a service-call to set the frontend theme. So for example on startup I have an automation which sets the frontend theme to `slate-theme`. When I do this it will work (though it needs a refresh, whereas it was an instant change pre 0.97). When I change the theme via the sidebar, nothing happens at all and only the border-radius and wallpaper gets changed (as I guess that is not a custom property). This used to work perfectly fine pre 0.97.

**Additional information:**
For an example as to what it used to do check this video (fast forward to 01.58)
https://www.youtube.com/watch?v=Ng0EDltHujY
As you can see in this video the theme changes instantly (this is via a service-call) but doing it via the sidebar also used to work perfectly fine.

Did anything change on this matter? Is custom css no longer possible or is it just a bug?

**Comment by balloob** [comment]
You can use the Chrome inspector to see which theme variables are defined. I don't think that we changed anything there, but not 100% sure. Wonder if it's inside the markdown-mod ? Does it happen for every card?

**Comment by balloob** [comment]
In Chrome, see if it's defined on page load by doing so:

- Right click on your card and click inspect element.
- Open "Elements" tab, then inside the "Styles" subtab, fill in `test-color` in the filter field. You should see the value defined.

**Comment by jimz011** [comment]
So I have inspected some cards (btw yes it does it with all cards, not just markdown-mod/card-mod but as well with kuuji's/romriders button card and basically any other card where css can be defined). Though it does show me all the elements when I inspect it in chrome. When I change the theme and inspect it again, all the custom css colors stay the same. For example I have
```
--test-color: green;
```
in my 1st theme and:
```
--test-color: red;
```
in my 2nd theme.

When I change theme 1 to theme 2 the `--test-color: green;` will stay on that same color.
If I do the service call to change the frontend theme (and refresh afterwards) it does change and when inspecting all the colors are the way they should be.

**Comment by balloob** [comment]
So how do you define your themes, do you define them per view or do you only have a global theme?

**Comment by jimz011** [comment]
I define them globally via themes.yaml. It has come to my attention though that this is only the case when I use custom values. If I use known properties (e.g. —paper-card-backround-color) then it works fine. It only does not work if I want to override a known value with some properties that do not exist. Like in the example above I define a color in themes.yaml (e.g. myownproperty: blue), in this example var(—myownproperty) should override —paper-card-background-color.

Well I am actually not sure if it is normal to do it my way XD. It was just what worked for me in the past. I don’t think many people do it this way anyways and I’ll just probably have to use real properties xd.

**Comment by balloob** [comment]
Maybe the ordering in your YAML matters? define the custom variable before you use it?

**Comment by jimz011** [comment]
Ok, I have played around with it some more. And I found that it only does this when a frontend theme is set through a service-call or automation. If the frontend theme is set to default, the theme selector will work fine with all the themes I have set up.

This is what happens if I set a frontend theme on startup (through automations)
Video:  https://www.youtube.com/watch?v=Gn3BS5cUoTI

As you can see, the colors of the buttons are persistent no matter what theme I choose (it only seems to affect the colors within lovelace and not within the UI itself)

This is what happens if I set the frontend theme to default (through a service-call)
https://www.youtube.com/watch?v=pE9wYNjD850

As you can see here, the themes change fine just like they are supposed to do. I have tried many different properties like ha-card-background and paper-card-background-color. But they all behave the same.

You can find the code on which I talk about here:
https://github.com/jimz011/homeassistant/tree/master/configuration/themes.yaml
https://github.com/jimz011/homeassistant/tree/master/configuration/themes/

And some templates that have references to the colors in the themes
https://github.com/jimz011/homeassistant/blob/master/lovelace/decluttering_templates/climate-template.yaml
https://github.com/jimz011/homeassistant/blob/master/lovelace/decluttering_templates/switch-template.yaml

Sorry for not knowing exactly how it works, I am an hobbyist and I do not have great knowledge on this subject (I work in a bar with kids, so nothing of these sorts XD).

**Comment by DavidMStraub** [comment]
I am experiencing the same issue I believe. I am using the [clear theme dark](https://community.home-assistant.io/t/clear-theme-dark/100960) and if I switch to it using the UI or a service call, the CSS variables `--paper-card-background-color` and `--background-card-color` do not change w.r.t. the previously applied theme even though they are different in `configuration.yaml`, as I confirmed with the Firefox dev tools (Chrome is the same).

It worked fine until 0.96 or 0.97 (sorry, don't remember exactly). I tried to find the culprit in the code, but wasn't successful (not a frontend expert).

**Comment by DavidMStraub** [comment]
Update: I found that using `ha-card-background` (in addition) in the YAML file solves the issue for me. So I suspect it has something to do with the move away from `paper-card`, although based on the code I don't really see the problem (`--paper-card-background-color` *is* used in `ha-card.ts`) ...

**Comment by zsarnett** [comment]
Is this still an issue?

**Comment by bramkragten** [comment]
This should be fixed by https://github.com/home-assistant/frontend/pull/5232
