### ISSUE TITLE
Change upload order of Cast upload script

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#3472]
Cast is served from an S3 bucket. The upload script (`cast/script/upload`) currently lets the order be determined by the s3 sync utility. This means that during upload, we could overwrite the index.html file while the corresponding JS files have not been uploaded yet. 

We should break the upload script in 2 parts, one that has the assets+JS, one that contains just `index.html` and `receiver.html`.

**Comment by DavidFW1960** [comment]
Could this issue be why a custom weather card isn't displaying the amcharts animated weather icons? (animated svg files) Normal mdi icons are ok.

**Comment by bramkragten** [comment]
@DavidFW1960 No. That's because it can't resolve a relative path on the cast.

**Comment by balloob** [comment]
All paths need to be routed via `hass.hassUrl(url)`

**Comment by DavidFW1960** [comment]
Ok I have this working (in the web interface) and I swear it briefly worked for cast as well but it's not working now.

I tried substituting url(url) with hass.hassUrl(url) but it is still blank. The fullurl is returning the correct https url for the hass gui

```
// Cast Compatibility
    var fullurl = window.location.origin;   
```
left other stuff out
```
      <ha-card class = "card">  
        <span class="icon bigger" id="icon-bigger" style="background: none, url(${fullurl}/local/icons/weather_icons/${this.config.static_icons ? "static" : "animated"}/${this.weatherIcons[this.current.conditions]}.svg) no-repeat; background-size: contain;">${this.current.conditions}</span>
```

**Comment by balloob** [comment]
We could consider something like https://github.com/yvele/poosh#upload-ordering
