### ISSUE TITLE
Allow integrations to suggest Lovelace cards

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#3518]
Current release: Home Assistant 0.97

It would be great if integrations could suggest Lovelace UI that the user could add to their Lovelace with one click (or show as YAML for copy/paste if in YAML mode).

This dialog could be triggered from a button on the config entry page and when the user is done with setting up the integration, as an extra step after the put the devices in areas. 

During onboarding we would not ask this, but instead always add it to their Lovelace? (although that might mess with generated Lovelace mode  hmmmm)

**Comment by iantrich** [comment]
This would be very cool!

**Comment by balloob** [comment]
Ideally, we would be able to incorporate this into the automatically generated Lovelace, but I don't know how that would work.

**Comment by bramkragten** [comment]
From the device page you can add suggested cards to Lovelace for that device https://github.com/home-assistant/home-assistant-polymer/pull/4356
