### ISSUE TITLE
Dashboard view is not refreshed after checking for addon updates

### ISSUE THREAD

**Issue by casperklein** [home-assistant/frontend#3539]
**Home Assistant release with the issue:**
0.97.2 (with Firefox 68.0.2)

**Operating environment (HassOS/Generic):**
HassOS

**Description of problem:**
After refreshing/checking for updates in the add-on store, the dashboard view is not refreshed automatically.

**Reproduce / Workaround:**
Goto Hass.io - ADD-ON STORE. Click the refresh icon in the top-right corner. Now you probably see some addons that change the color to orange, indicating that there is an update available.
When you now click on DASHBOARD, you see all the addons in green (not updatable) again. Manually refreshing the page with "F5" will show the correct addon status.

**Comment by ludeeus** [comment]
If this is not fixed by #4398 I will look into it after.

**Comment by ludeeus** [comment]
This is still an issue.

**Comment by casperklein** [comment]
This is still an issue.
