### ISSUE TITLE
Allow setting user permissions from Add user screen

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#3604]
**Description of problem:**
The "Add user" dialog hasn't been updated since the introduction of permission system. Currently it always creates the account as an admin.

It should allow you to select which group the new user belongs to ("Administrators" or "Users"). And the default option should probably be set to user.

![add-user](https://i.imgur.com/kKlHapR.png)

Also, this button should probably say "Create User" or "Add User" instead of simply "Create."

**Comment by iantrich** [comment]
Started looking into this, looks like it will require a change to the backend create user call.
