### ISSUE TITLE
Add Stop Effect to Lights more-info dialog

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#3619]
**Description of problem:**
You can turn on light effects from the more-info dialog for Lights, but there is no apparent way to turn these effects off. Seems that you have to turn the light off and then back on again, which is not obvious and can be a little confusing. Some examples of community posts referencing this: [here](https://community.home-assistant.io/t/hue-light-effects-wont-stop/104340), [here](https://community.home-assistant.io/t/stopping-hue-colorloop-without-turning-off-lights/55083), [here](https://community.home-assistant.io/t/turn-off-colorloop/58657).

It seems that sending `effect: stop` will stop the effect and restore your lights. I've tested this with Hue and it seems to work, but I am not 100% positive if this is a standard Home Assistant thing that all light platforms support? 

I think that there should either be a "stop" option added inside of the dropdown when an effect is currently active like this (mockup 1):

![stopeffectmock1](https://i.imgur.com/pEmF9XL.png)

Or a stop button to the right of the "Effect" dropdown as pictured here (mockup 2):

![stopeffectmock2](https://i.imgur.com/BmHAg1N.jpg)

**Comment by balloob** [comment]
If we would go for a button, only show it if we know an effect is active. I think I prefer making it part of the dropdown.

**Comment by SeanPM5** [comment]
There is one minor discoverability issue with the dropdown idea however.

If the "stop effect" choice is hidden until an effect is active, the user doesn't see it when opening the dropdown menu and they wouldn't necessarily know it was added either because the dropdown closes immediately after they make their selection. 

So if this is possible, maybe have the "show effect" option be visible in the dropdown at all times but just in an unselectable/disabled until there is an active effect? And it probably should be at the very bottom of the effect list too.

**Comment by dshokouhi** [comment]
Maybe instead of "Stop Effect" we change it to "No Effect" and make that the default option?

**Comment by iantrich** [comment]
I like "No Effect"

**Comment by iantrich** [comment]
Looked at the code and it is just a list of effects, so for now just going to have "stop" for now. It will not be hidden.

**Comment by iantrich** [comment]
I only have the demo light to play with for this but it has an effect of 'none'. Do yours not?

![image](https://user-images.githubusercontent.com/1287159/64396703-16b6f580-d024-11e9-9aa8-47c6534219ae.png)

**Comment by dshokouhi** [comment]
This is what I got:

Lightify:
![image](https://user-images.githubusercontent.com/1634145/64397373-e4060080-d015-11e9-9ac8-3bcc2b33db88.png)

Hue:
![image](https://user-images.githubusercontent.com/1634145/64397387-e9fbe180-d015-11e9-9306-9795f52496a7.png)

Limitlessled:
![image](https://user-images.githubusercontent.com/1634145/64397420-0b5ccd80-d016-11e9-8d32-37f34d6f4b09.png)

**Comment by iantrich** [comment]
Can you check if there is an effect attribute after calling the turn_on with an effect of "stop"?

**Comment by BjoernPetersen** [comment]
As I understand the (partial) fix has been reverted in #3672, right? Could this issue be reopened then? I understand that there's no perfect solution for all devices right now, but having to cycle the light to turn off an effect is still annoying.

**Comment by iantrich** [comment]
I don't believe this is a frontend issue. The backend would have to change to have all integrations follow a similar method of stopping effects, if even possible before the frontend could support it.
