### ISSUE TITLE
Improve default behavior of Lovelace card previews

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#3642]
**Home Assistant release with the issue:**
0.98.4

**Description of problem:**
Currently most Lovelace card editors display a "broken" preview by default. The user clicks "Add card" and they are immediately greeted with the bright red warning card (`hui-error-card`) by default before they've even touched anything.

![example](https://i.imgur.com/h6NsKCF.png)

This can scare people off and make it seem like things are broken or unusable, when in reality, it's simply because there is no entity selected by default. But put yourself in the shoes of a brand new user to Home Assistant, or someone just browsing the demo website - seeing errors on literally everything you click isn't a good first impression.

1. Alarm Panel - red error with `Invalid card configuration` text.
2. Entity button - red error with `Invalid Entity` text.
3. Gauge - red error with `Invalid card configuration` text.
4. Light - red error with `Specify an entity from within the light domain.` text.
5. Media Control - red error with `No entity specified` text.
6. Sensor - red error with `Specify an entity from within the sensor domain.` text.
7. Thermostat - red error with `Specify an entity from within the climate domain.` text.
8. Weather Forecast - red warning with `No entity specified` text.

**Other notes**:
* In the eight cards I listed above, they all have the same "problem" (need to select an entity to generate the preview), but there are multiple different error messages. Some just say Invalid, others try to help the user. These messages should probably be consistent?
* Almost every other card type also launches into red errors, but those don't have GUI editors yet so that is to be expected. (These cards are: Conditional, Entity Filter, History Graph, Horizontal Stack, Picture Elements, Picture Entity, Picture Glance, Plant Status, Vertical Stack.)
* The only two cards which don't have this problem load example data by default - iFrame card and Picture card.

**Ideas on how to make this better**:
Came up with two different ideas on how this could maybe be improved:

1. Always select the first available entity by default. This would ensure that the preview window doesn't have an error, and it also gives the user an exact idea of how the card looks and functions. 
2. Create a generic "instructional" card, that basically tells the user something along the lines of "Please select an entity to begin." So rather than scaring users off with an error, they would see a friendly card that instructs them on how to proceed. 

I am not sure which approach I prefer. But maybe someone can come up with better ideas?

**Comment by dshokouhi** [comment]
Another great find and suggestion @SeanPM5 !

Since this does look like a form maybe we should properly label "required" fields and only render the card once all required fields are completed?  This way the user knows there is pending action on their end due to the incomplete form.

**Comment by SeanPM5** [comment]
Yeah that would be another option. Being able to clearly differentiate between required/optional fields is probably something that should be implemented regardless of whatever gets decided here.

-- 

Another thought on this. If there's only one available entity to select, it should just be pre-selected automatically. 

Here is the Media Control card on the default arsaboo demo: 

![single-entity](https://i.imgur.com/yNAdvWJ.png)

His demo only has a single `media_player` entity, but it still forces the user to select it, when there is not actually a choice that can be made. This causes the invalid config error in the preview along with two unnecessary clicks. Can also see this same behavior on the Thermostat card and the Alarm Panel Control card on the default demo.

**Comment by balloob** [comment]
The stub config method should fill the stub config with real entities. It should first look in unused entities for an appropriate entity, otherwise look at all entities and just pick one. 

That way the media player card would just pick a media player and sensor cards would be able to find an eligible sensor. Bonus if we could limit the entity dropdown to these entities, and have a "show all" button at the bottom of the dropdown to just see all entities.

**Comment by iantrich** [comment]
Yeah we always had this thought but never got around to implementing it

**Comment by balloob** [comment]
We should allow `getStubConfig` to optionally return a promise, which will be awaited by the caller.

**Comment by SeanPM5** [comment]
Closing since it's in 0.107 now (hooray)
