### ISSUE TITLE
Image resource uploader

### ISSUE THREAD

**Issue by iantrich** [home-assistant/frontend#3669]
per https://github.com/home-assistant/home-assistant-polymer/issues/3021#issuecomment-528617466

I imagine a dialog that can be presented on any editor that has an image option that allows you to upload to /www and populates the path for use.

Additionally, our editors could present available images already in /www to be selected

**Comment by balloob** [comment]
I don't think that it should be in `/www`. I think that it should be a new integration which can also take care of resizing it.

**Comment by balloob** [comment]
Frontend should allow cropping it too (that is not part of MVP though!)

**Comment by ludeeus** [comment]
This has been added in current dev.

**Comment by bramkragten** [comment]
> Frontend should allow cropping it too (that is not part of MVP though!)

Oops...
