### ISSUE TITLE
Entity picker in Lovelace configure UI doesn't use theme background variable

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#3676]
**Home Assistant release with the issue:**
0.98.5

**UI (States or Lovelace UI?):**
Lovelace

**Description of problem:**
The Entity Picker / Entity Dropdown in the Lovelace Configure UI mode card editors seems to always display in white, rather than using the users theme background color.

Besides the white dropdowns looking very out of place on dark themes, it also makes the icons invisible, as you can see in this screenshot of the third demo (kernehed).

![demo](https://i.imgur.com/H336bq4.png)

The "States" and "Services" panels under Developer Tools seem to use an identical(?) entity picker but those don't have this issue and work as expected / respect the users background color. 

![expected-behavior](https://i.imgur.com/CTDz65T.png)

**Comment by iantrich** [comment]
They are indeed the same but I get the same in dev tools

![image](https://user-images.githubusercontent.com/1287159/65066418-ecc9d100-d949-11e9-9ab2-14493ae524ec.png)

Can you include a link to your theme?

**Comment by SeanPM5** [comment]
Sure, I use the [Slate theme](https://community.home-assistant.io/t/slate-a-new-dark-theme-updated/86410).

**Comment by springstan** [comment]
I think it depends on the theme and which CSS variables they have set and it looks like this issue has been resolved, e.g

- Lovelace Configure UI mode card editors:

![grafik](https://user-images.githubusercontent.com/46536646/67711395-30d8d880-f9c2-11e9-9915-076275fc4ca7.png)

- Service:

![grafik](https://user-images.githubusercontent.com/46536646/67711600-94630600-f9c2-11e9-8429-eae3a08c60c6.png)

- States:
![grafik](https://user-images.githubusercontent.com/46536646/67711677-c5433b00-f9c2-11e9-8dd4-036f6e1a5f06.png)

**Comment by iantrich** [comment]
@SeanPM5 can you confirm? Thanks.

**Comment by SeanPM5** [comment]
Think I figured out what the problem is, or at least I might be on the right track...

When comparing my copy of the Slate theme to the one in the demo (https://github.com/home-assistant/home-assistant-polymer/blob/dev/demo/src/configs/kernehed/theme.ts) the demo is lacking all of the "lumo" variables. The Logbook menu is seemingly the same component used for the entity picker so I assume the fixes below here would apply:

```
# Changes to fix history/logbook menus
lumo-primary-text-color: '#2980b9'
lumo-secondary-text-color: '#2980b9'
lumo-primary-color: '#2980b9'
# Calendar day numbers
lumo-body-text-color: '#b58e31'
# Calendar/Date-Picker Background
lumo-base-color: '#222222'
# Month/Year header
lumo-header-text-color: 'var(--lumo-body-text-color)'
# DayOfWeek Header
lumo-tertiary-text-color: 'var(--lumo-body-text-color)'
lumo-shade: '#222222'
lumo-shade-90pct: 'rgba(34, 34, 34, .9)'
lumo-shade-80pct: 'rgba(34, 34, 34, .8)'
lumo-shade-70pct: 'rgba(34, 34, 34, .7)'
lumo-shade-60pct: 'rgba(34, 34, 34, .6)'
lumo-shade-50pct: 'rgba(34, 34, 34, .5)'
lumo-shade-40pct: 'rgba(34, 34, 34, .4)'
lumo-shade-30pct: 'rgba(34, 34, 34, .3)'
lumo-shade-20pct: 'rgba(34, 34, 34, .2)'
lumo-shade-10pct: 'rgba(34, 34, 34, .1)'
lumo-shade-5pct: 'rgba(34, 34, 34, .05)'
lumo-tint-5pct: '#222222'
```
So this is really more of a theming issue, I think. Most themes just aren't styling this part, which is understandable as this stuff doesn't appear to be documented anywhere. Seems fixed in "Slate" at least.

I was going to close this issue, but this could perhaps be considered a demo issue too since none of the demo configs have these variables defined. This issue occurs in 3/4 demos (all the non-default ones). So will leave it up to you...

**Comment by bramkragten** [comment]
Lumo will be removed soon (hopefully)

**Comment by zsarnett** [comment]
These are the primary variables that should be used:
```yaml
darkorange:
  primary-color: "#ff9800"
  light-primary-color: "#ffc947"
  dark-primary-color: "#c66900"
  text-primary-color: "#ffffff"
  primary-background-color: "#37464f"
  card-background-color: "#263137"
  secondary-background-color: "#263137"
  primary-text-color: "#ffffff"
  secondary-text-color: "#ff9800"
```
