### ISSUE TITLE
Weather Widget Pressure Units

### ISSUE THREAD

**Issue by charlesarmour** [home-assistant/frontend#3677]
**Home Assistant release with the issue:**
0.98.5 (Raspberry Pi 3B+)

**Last working Home Assistant release (if known):**
N/A

**UI (States or Lovelace UI?):**
Lovelace UI - Met.no Weather

**Browser and Operating System:**
Latest Chrome, FireFox, Safari on Win10

**Description of problem:**
Met.no weather widget shows "inHg" (inches of mercury) as the atmospheric pressure unit when the value appears to be in "hPa" (hectopascals) or "mbar" (megabars).  This may be due to lack of conversion (divide hPa by ~33.7) when using imperial pressure units.

It would be preferable to display the imperial value (i.e. "Air pressure: 30.12 inHg"), however changing the displayed unit abbreviation (i.e. "Air pressure: 1020.9 hPa") would also resolve this issue.

**Javascript errors shown in the web inspector (if applicable):**
N/A

**Additional information:**
https://en.wikipedia.org/wiki/Inch_of_mercury

**Comment by klejejs** [comment]
Met.no provides pressure only in hPa so if Home Assistant unit system is changed to Imperial, met.no sensor still provides pressure in hPa.

Knowing this should we do conversion to inHg when displaying this in card if imperial unit system is selected?

**Comment by klejejs** [comment]
Adding to this issue, wind speed is also constant and does not change based on unit system.
