### ISSUE TITLE
Missing tooltips on Script Editor panel

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#3802]
**Home Assistant release with the issue:**
0.99.2

**Description of problem:**
Another smaller issue for Hacktoberfest. Script Editor panel could use some improvements to tooltips - some are missing, some can be a little better.

**Add new tooltips**
* The pencil icon has no tooltip when hovered, it should say "Edit Script"
* The play icon for running scripts has no tooltip when hovered, it should say "Run Script"

**Tweak for better clarity**
* The tooltip when hovering over the plus button is "Add script" but I think that "Create New Script" is a bit more clear
* Similarly, the tooltip when hovering over the floating action button for SAVE is just "Save" when it should say "Save Script"

**Comment by Aaron-K-T-Berry** [comment]
I can have a look at this one :)

**Comment by iantrich** [comment]
If you run into issues hit us up on [Discord](https://discord.gg/XVcx2KX)
