### ISSUE TITLE
Refresh Supervisor snapshot list when entering Snapshots tab

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#3805]
**Home Assistant release with the issue:**
0.99.2

**Description of problem:**
Recently Bram added "Update logs on activate tab" https://github.com/home-assistant/home-assistant-polymer/pull/3716 and I was just thinking this exact same idea would be extremely useful on Hass.io Snapshots tab too.

Often when users attempt to restore Hassio snapshots it's not in their "Available snapshots" section until refreshing the snapshot list using the icon in the top right corner. This icon is very easy to miss especially on desktop screens. 

[Here is a forum thread about this](https://community.home-assistant.io/t/recovering-a-snapshot/44534) and I know that both @cogneato and @DavidFW1960 help people out with this fairly regularly in Discord too. Having the snapshot list refresh automatically when the user clicks the Snapshot tab would eliminate a lot of confusion.

**Comment by markus99** [comment]
Given that Supervisor 220 has an apparent bug that hides this button - why does it exist in the first place?  Seems the /snapshots page, when loaded, should simply refresh automatically.
