### ISSUE TITLE
Add link to Customize documentation on Customization panel

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#3819]
**Home Assistant release with the issue:**
0.99.3

**Description of problem:**
Several pages in the Configuration section (Automation, Cloud, Script etc) have links to the documentation on HA's website to help the user learn more. Customization does not have this yet, and it probably should.

Would link to this page:
https://www.home-assistant.io/docs/configuration/customizing-devices/#customization-using-the-ui

Good issue for Hacktoberfest.

**Comment by lucasheim** [comment]
I can work on this

**Comment by iantrich** [comment]
If you run into issues hit us up on [Discord](https://discord.gg/XVcx2KX)
