### ISSUE TITLE
Add link to Person documentation on Person panel

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#3820]
**Home Assistant release with the issue:**
0.99.3

**Description of problem:**
Several pages in the Configuration section (Automation, Cloud, Script etc) have links to the documentation on HA's website to help the user learn more. Person does not have this yet, and it probably should.

Would link to here: https://www.home-assistant.io/integrations/person/

Good issue for Hacktoberfest.

**Comment by lucasheim** [comment]
I can work on this

**Comment by iantrich** [comment]
If you run into issues hit us up on [Discord](https://discord.gg/XVcx2KX)
