### ISSUE TITLE
Make release notes link clickable in Updater more-info dialog

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#3822]
**Home Assistant release with the issue:**
0.99.3

**Description of problem:**
Super minor UX improvement - the `binary_sensor.updater` lists a release notes link, but it requires the user to copy and paste. This should be a clickable link. 

Hacktober candidate?

![image](https://i.imgur.com/bNBVh2z.png)

**Comment by bramkragten** [comment]
This is not as simple as it looks, it is just an attribute from a sensor, no simple way to see if it is a link, without some nasty checks.

**Comment by SeanPM5** [comment]
Hm, does it even need to be an attribute though? Since it's just a link to the generic "latest release notes" url, I assume the value would always remain the same? In which case it could probably just be hardcoded to display underneath the attributes.

Something along these lines (except the version attribute would be above the links):

![more-info](https://i.imgur.com/I3mwxQC.png)

I realize this might be worth more hassle than it's worth though, in which case feel free to close it.
