### ISSUE TITLE
Preview for badges on View Configuration UI editor

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#3825]
**Home Assistant release with the issue:**
0.99.3

**Description of problem:**
When adding badges using the "View Configuration" UI editor, a live preview would be very helpful. Users shouldn't be expected to know what a "badge" means, or how it looks and functions.

Most people aren't going to search the documentation (which doesn't help in this particular case anyway), and I suspect that most people probably aren't going to blindly add things either. By including a preview it solves all these problems and more. No confusion.

Here is a mockup:

![badge-previews](https://i.imgur.com/WoB6t70.jpg)

**Comment by bramkragten** [comment]
I like this idea! :-)

**Comment by tomraithel** [comment]
I can have a look at this
