### ISSUE TITLE
"Unable to connect to Home Assistant" - over PPTP VPN to home LAN

### ISSUE THREAD

**Issue by tiagofreire-pt** [home-assistant/frontend#3828]
**Home Assistant release with the issue:**
0.99.2

**Last working Home Assistant release (if known):**
N/A

**UI (States or Lovelace UI?):**
Both.

**Browser and Operating System:**
Chrome 76.0.3809.87 64bit
Windows 10

**Description of problem:**
The HA frontend returns "Unable to connect to Home Assistant", after a while, submitting the login credentials.

**Javascript errors shown in the web inspector (if applicable):**
Unknown.

**Additional information:**
The websocket connection somehow stalls: ws://192.168.10.185:8123/api/websocket

**Comment by tiagofreire-pt** [comment]
Any news on this, please?

**Comment by bramkragten** [comment]
This sounds like a problem with your connection. Check your logs and network traffic.
