### ISSUE TITLE
divider and weblink causing warning on UI editor

### ISSUE THREAD

**Issue by jensihnow** [home-assistant/frontend#3851]
**Home Assistant release with the issue:**

0.99.3

**Last working Home Assistant release (if known):**

Never?

**UI (States or Lovelace UI?):**

Frontend version: 20190919.1 - latest

**Browser and Operating System:**

Independent of Browser or Operating System as far as I can tell.

**Description of problem:**

The entity types divider and weblink (maybe others as well?) are not supported by the UI editor and are causing warning as follows:

> Expected a value of type {entity,name,icon} | entity-idforentities.0.typebut received"divider".

and

> Expected a value of type {entity,name,icon} | entity-idforentities.0.typebut received"weblink".

While this is officially not a bug, it should be tracked as a feature request as both are valid lovelance options.  To me this is a usability issue which should be resolved before 1.0, especially as divider and weblink are used in official example code and most likely will be copy/pasted a lot (see referenced issue for an example).

Unfortunately, this issue had been closed with not a bug before, what would be the correct way of adressing this as a feature request?

**Javascript errors shown in the web inspector (if applicable):**

-

**Additional information:**

* https://github.com/home-assistant/home-assistant.io/issues/9664
* https://github.com/home-assistant/home-assistant-polymer/issues/2325
* https://github.com/home-assistant/home-assistant-polymer/issues/2498

**Comment by iantrich** [comment]
We were previously trying to separate FRs and bugs but we've settled that both are valuable to have just here👍

Thanks
