### ISSUE TITLE
Accessible Background Div 

### ISSUE THREAD

**Issue by J-HB** [home-assistant/frontend#3894]
This might be a long shot, but here is my proposal:
A while back I stumbled over this reddit [thread](https://www.reddit.com/r/homeassistant/comments/9ak3yt/how_to_dynamic_weather_gif_as_lovelaceui/)
And I found it a neat idea to be able to influence the background of my lovelace instance. I tried the Gif option to give the background some life. Gifs are however a horrible option since they either explode in file size or lack in terms of quality. 
The best Alternative would be using an mp4. This solution would require some absolute positioned container in the background which could house the <video> element. Or maybe someone wants to use this container to create some css animations. 
And maybe someday a cinemagraph like [this](https://flixel.com/cinemagraph/bwpj86y9fiarqi2xo0hd/) or [this](https://flixel.com/cinemagraph/v26zyfd6yf0r33s46vpe/) could be our lovelace backgroud.

**Comment by bramkragten** [comment]
This is not something we will add to core. This can be done in a custom element.
