### ISSUE TITLE
Tooltips on Integrations page cut off

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#3903]
**Home Assistant release with the issue:**
0.100b0

**Description of problem:**
Tooltip text gets "cut off" on Integrations page, almost always for the first entity/icon.

![tooltip](https://i.imgur.com/LoAqOhQ.png)

Here I am hovering the second icon, the actual name of entity is
"Linear (Nortek Security Control LLC) WADWAZ-1 Door/Window Sensor"

What it shows is:
"y Control LLC) WADWAZ-1 Door/Window Sensor"

That's the first 22 characters cut off. This is the most extreme example on my setup, it's usually more like 2-3 characters cut off, but still...

**Comment by Reixko** [comment]
Hello, can I take this issue ?

(P.S. I would also like to add some unit tests if you know of something that you would like to have tested)
