### ISSUE TITLE
Re-order tabs in Hass.io panel

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#3931]
**Home Assistant release with the issue:**
0.100b

**Description of problem:**
I think that the tabs in the Hass.io panel could be re-ordered just a tiny bit.

Basic idea is to swap the placement of "Snapshots" and "Add-On Store", so that relevant sections are grouped together. This places the two add-ons sections (dashboard/store) next to each other, and the two system-related sections next to each other. 

This is a bit cleaner imo, and an unintentional side benefit is that (after the first tab) it's in alphabetical order too.

Here is a mockup I did a while ago showing how this would look:

![hassio-tabs](https://camo.githubusercontent.com/a0e06ca92b43249761aa7c3bd26492c694ce8f5e/68747470733a2f2f692e696d6775722e636f6d2f304c486b6b76422e706e67)

In this mockup I also renamed "Dashboard" to "Installed Add-Ons" and changed the heading for extra clarity.  That part isn't required for this issue but I think that re-ordering the tabs makes sense?

**Comment by trblackw** [comment]
I'd like to take this on if I can  👋🏻
If that's cool, please assign me!

**Comment by iantrich** [comment]
Hit us up on discord if you run into issues setting up a Hass.io dev environment

**Comment by trblackw** [comment]
Will do, thanks.
