### ISSUE TITLE
Display automation description in more places

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#3984]
**Home Assistant release with the issue:**
0.100.1

**Description of problem:**
Support for automation descriptions was added recently in https://github.com/home-assistant/home-assistant-polymer/pull/3723. At the moment this description can only be seen when editing an automation.

I think there are two more places where it would make sense to display this.

The first is the main Automation panel with your list of automations. The existing UI already accommodates this pretty well imo. If the automation has a description it'd show in place of the "Last triggered" timestamp. Clicking on the secondary text could toggle between them.

![automation-editor-config](https://i.imgur.com/MGCyAbt.png)

The other area would be more-info dialog for automations. The description can be displayed as an attribute. Then you can be sure it's the correct automation before hitting the trigger button.

![automation-description](https://i.imgur.com/oxAI1v4.png)

**Comment by theaquarium** [comment]
I can take a look at this. Other than in the more info dialog, where should this be. Is the last triggered replacement something people like?

**Comment by bramkragten** [comment]
The first step would be the secondary text in the automation config panel.

**Comment by iantrich** [comment]
This would require a backend change, we don't actually grab the automation's description for that states object.
