### ISSUE TITLE
Allow disabling actions in Automation and Script editors

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#3988]
**Home Assistant release with the issue:**
0.100.1

**Description of problem:**
This is a followup / companion to https://github.com/home-assistant/home-assistant-polymer/issues/3985. Idea is to close the gap between YAML and UI.

Not sure this is even possible on a technical level, but the idea here is to allow a user to temporarily **disable** a trigger or action instead of requiring them to delete it outright. Basically the UI equivalent of commenting out some lines of YAML in a text editor.

This would show up in the "3 dots" menu that's already on each card. Right now it shows Duplicate and Delete, but there'd be a third "Disable" option added to this list. If the card is disabled this menu option would say "Enable" instead.

 When a card is disabled there would be no user input allowed and it would appear in a disabled/grayed out state. The only thing you'd be able to do is click on the "3 dots" icon to either re-enable (or delete) it.

Half-assed mockup mostly showing where the Disable button would be:
![disable](https://i.imgur.com/bsmCFZr.png)

**Comment by bramkragten** [comment]
This is not possible right now, I would suggest copy the yaml and store it somewhere else.
