### ISSUE TITLE
Hide state of group in popup

### ISSUE THREAD

**Issue by circa1665** [home-assistant/frontend#3998]
**Home Assistant release with the issue:**
0.100.2

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
macOS Catalina 10.15, Safari 13.0.2

**Description of problem:**
Minor visual issue - would be nice if the state of a group could be hidden in the popup. something like controls or state: hidden would be great.
<img width="371" alt="group_popup" src="https://user-images.githubusercontent.com/33236082/66724101-5b9b2c80-ee19-11e9-9dc7-d0b065e2f2a8.png">
<img width="246" alt="group_yaml" src="https://user-images.githubusercontent.com/33236082/66724102-5b9b2c80-ee19-11e9-98fb-cffb6598170f.png">

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

**Comment by Misiu** [comment]
This should also hide toggle in entity row in the entities card. 
Currently, when you add a group to entities card You get a toggle by default. You can add `type: custom:hui-text-entity-row` but this will change toggle into status text.

Ideally, there should be an option to hide the state of the group in the popup (as @circa1665 suggested) and also a label template property that would allow us to define what label will be displayed in entity card.
Simple use case: I want to use a group to control scheduler of roller shutter, sample UI:
![image](https://user-images.githubusercontent.com/1741838/66738027-ca09da00-ee6d-11e9-915b-b4913b5b598d.png)
I've added that group to entities card

Ideally, I'd like to display (in entities card) "Scheduler disabled" when the scheduler is disabled or some info about days when the scheduler is active, something like "Mon,Tu,Wed,Th,Fri"

Not sure if this should be asked here or in https://github.com/home-assistant/home-assistant

**Comment by iantrich** [comment]
we're trying to get away from backend definitions impacting frontend display.

as it currently stands, more-info dialogs are not configurable. If you wish to customize the look and feel of it, I suggest you check out [popup-card](https://github.com/thomasloven/lovelace-popup-card). It is "archived" but still works.

**Comment by Misiu** [comment]
@iantrich thank You for the link., however, I want to stay away from packages that are archived as they won't get any support and features.

Are there any plans to extend (allow more customization) of more-info dialog? I think it is very useful but we should able to hide the state and be able to customize the group label - currently, it has a toggle which isn't very useful.

**Comment by iantrich** [comment]
No plans

**Comment by Misiu** [comment]
@iantrich can this be done with https://github.com/home-assistant/home-assistant-polymer/pull/4361 (as this is a continuation of https://github.com/home-assistant/home-assistant-polymer/pull/4124) My idea is to show an entity that will have config panel available for it (displayed after you click or double click on that entity).
A simple use case is a roller shutter system.

**Comment by iantrich** [comment]
No, you'd need something to listen for the event and create the dialog still

**Comment by Misiu** [comment]
@iantrich thanks for the info.
