### ISSUE TITLE
ffmpeg process still active after the "more info" window closed

### ISSUE THREAD

**Issue by MaximumSU** [home-assistant/frontend#4055]
**Home Assistant release with the issue:**
0.101.3

**Last working Home Assistant release (if known):**
0.87.1
**UI (States or Lovelace UI?):**
Lovelace UI

arch | armv7l
-- | --
dev | false
docker | false
hassio | false
os_name | Linux
python_version | 3.7.3
version | 0.101.3
virtualenv | true

**Browser and Operating System:**
any

**Description of problem:**
ffmpeg process still active after the "more info" window closed for any ffmpeg based camera. Every "new info" window forks one more ffmpeg process in the system, which is not closed till window refresh or browser tab closed. So, how many times you click the "more info", so many separate ffmpeg processes you have active (they are eating cpu and memory very heavy) in the system.

**Additional information:**
This issue was marked as "fixed" several times (for example, here #3018), but actualy yet not fixed.

**Comment by MaximumSU** [comment]
0.104.2 still not fixed

**Comment by ster1um** [comment]
0.108.1 Not fixed yet

**Comment by MaximumSU** [comment]
0.111.4 still not fixed

**Comment by NetAgentTV** [comment]
Can confirm, this issue is NOT fixed.

**Comment by ludeeus** [comment]
Can confirm, 0.113.2 is NOT the newest version.

How about you try to upgrade?

**Comment by kevinfoerster** [comment]
running 0.114.1 here, same issue…

ffmpeg is using lots cpu and my nuc fans are blowing 24/7 :(

i rarely use the stream on the website but the same issue can be observed when using homekit camera provided by HA

**Comment by MaximumSU** [comment]
not fixed yet...

**Comment by epruesse** [comment]
Experiencing this issue as well - ffmpeg processes are racking up until the box crashes.

**Comment by epruesse** [comment]
...

**Comment by fstap** [comment]
Same problem here, a fix would be great as it's occupying valuable resources

**Comment by dsaard** [comment]
2021.6.2 same here, also if you catch them via onvif
