### ISSUE TITLE
Sliding from the left into the screen to open the side bar doesn't work with gesture control

### ISSUE THREAD

**Issue by Santobert** [home-assistant/frontend#4063]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:** 0.100.2

**Last working Home Assistant release (if known):** Probably none

**UI (States or Lovelace UI?):** Lovelace

**Browser and Operating System:** Android 10 and Google Chrome

**Description of problem:**
Sliding from the left into the screen usually opens the sidebar. With the gesture control introduced with Android 10, it also triggers the browser button `back`.

The result is that the sidebar opens until Android recognizes the gesture. At this point, the sidebar was slid open a tiny bit. Now that the gesture has been recognized, the browser clicks `back` and goes to the previously opened page. The sidebar is still slightly open and disables all other controls on the page.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by bramkragten** [comment]
What do you suggest we do about this?

**Comment by Santobert** [comment]
Well, the easiest and maybe best solution would be to deactivate the sliding action completely. The side bar can be opened by the button anyways.

It looks like Android is capturing that action and preventing the website from noticing it. If this behavior can be deactivated by the website itself that would also be a solution. I'm not sure if we need the browsers back button...

**Comment by bramkragten** [comment]
I don't have Android 10, but do have the swipe to go back option, but it doesn't bite each other here, if I swipe in from outside the screen it goes back and the sidebar doesn't react, and if i start the swipe from inside the screen the sidebar reacts and it doesn't go back.

Seems a bit drastic to remove the function completely, and I don't really see the problem since we do have the button to open it?

**Comment by Santobert** [comment]
Oh sorry. I was not precise enough. I just suggested to remove the option to open the side bar by sliding. Not to remove the whole side bar 😂

I use Android One on a Nokia 8.1. The pixel phones may be also affected. It seems like the back button which was previously on the bar below moved into some sort of overlying virtual side bar that is triggered as soon as the swipe lasts long enough. I'll send you a video as soon as I'm home again.

**Comment by Santobert** [comment]
https://cloud.tobhaase.de/s/KtZjGe2pENDdNCT

**Comment by Santobert** [comment]
The problem is, that I can't go back anymore without messing around with the side bar.

**Comment by Santobert** [comment]
@bramkragten what are you suggesting? Do you still need the video? I'd like to take it offline.

**Comment by Santobert** [comment]
This is still a problem

**Comment by sanyatuning** [comment]
More info: 
https://www.androidcentral.com/android-q-back-gesture-going-be-pain-until-developers-update-apps

**Comment by bramkragten** [comment]
So we could disable the back gesture in our android app. I don't think we will disable the swipe in menu from our web app.

**Comment by Santobert** [comment]
Can't reprduce the issue with the current version. Thanks a lot!
