### ISSUE TITLE
Clarify toast text when restarting Home Assistant

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#4084]
When you restart Home Assistant, it displays a "Connection lost. Reconnecting..." toast in the bottom left.

![connection-lost](https://i.imgur.com/r64655y.png)

Although technically accurate, the wording here makes it appear like something went wrong and that the system is in an error state. I think this can be a little scary for new users. Especially since a lot of users will be running HA on a Raspberry Pi which can take several minutes to restart.

I think that it would be far more user friendly, and nicer looking, if it displayed "Restarting Home Assistant..." whenever the user invokes a restart (either from the Server Control panel or calling the `homeassistant.restart` service).

![restarting-ha](https://i.imgur.com/TKVNtfu.png)

The above "Connection lost" toast would still be used, just not for this scenario. Basically I think there should be differentiation between legitimate connection errors and routine restarts.

**Comment by bramkragten** [comment]
This would only work for the device that triggered the restart, the others would still show the normal message. I think this is not worth the trouble.
