### ISSUE TITLE
Display name of card being deleted in prompt

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#4091]
When deleting a Lovelace card, the "are you sure?" prompt is super generic. Based on this below screenshot, you wouldn't have any idea what card I was deleting. And if the user was not paying attention and selected the wrong card to delete, this prompt doesn't really let them know.

![delete-prompt](https://i.imgur.com/PNNbf07.png)

This prompt could be a little more informative, especially considering the user is about to perform a destructive and irreversible action. If there's ever a time to be super clear about something, it's when the user is about to delete data with no way of recovering it.

So I think that it would be helpful to display the name of the card being deleted in this prompt, if it has one. Something along the lines of: "Are you sure you want to delete your Doorbell card?"

If the card wasn't given a custom name by the user, it could instead use the card type. "Are you sure you want to delete this Thermostat card?"

And ideally the "OK" button should say "Delete Card"

**Comment by theaquarium** [comment]
I'll take a look.

**Comment by iantrich** [comment]
Prompts will be changing with this
https://github.com/home-assistant/home-assistant-polymer/pull/4053
Best to wait till that is merged

**Comment by theaquarium** [comment]
Oh yeah. Also nice finally custom dialogs.

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/issues/4555

This is a better approach as we don't have a name for each card on the view
