### ISSUE TITLE
Heading text truncated on 2FA dialog for mobile devices

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#4118]
On mobile devices the heading text gets truncated rather than wrapping to a second line. So you can only read half of the dialog title.

![2fa](https://i.imgur.com/imJ87at.jpg)

**Comment by SeanPM5** [comment]
Still an issue in latest, but very minor nitpick, and this is pretty much one of the few places it happens, so closing this.

**Comment by frenck** [comment]
We have a place for those minors now? Things like this would fit on the Cleanup & Polish board.

**Comment by SeanPM5** [comment]
Thx frenck, will re-open.
