### ISSUE TITLE
Setting a bool value to True in ZWave config sets it to False in OZW

### ISSUE THREAD

**Issue by electrofloat** [home-assistant/frontend#4134]
**Home Assistant release with the issue:**
Home Assistant
0.100.2

**Last working Home Assistant release (if known):**

**Operating environment (Hass.io/Docker/Windows/etc.):**
Linux

**Integration:**
https://www.home-assistant.io/integrations/zwave/

**Description of problem:**
So I was trying to configure the Aeotec Smart Switch 6 to report only on wattage changes. At first I thought the device was faulty, or that the documentation is false. BUT... many hours of debugging revaled that changing the `90: Enables/disables parameter 91/92` to `True` doesn't change it to true:
```
2019-10-23 20:46:06.038 Info, Node014, Value::Set - COMMAND_CLASS_CONFIGURATION - Enables/disables parameter 91/92 - 90 - 1 - False
2019-10-23 20:46:06.225 Info, Node014, Received Configuration report: Parameter=90, Value=0
```

Only when I manually called the service like this:
```
Service: zwave.set_config_parameter
Service Data: {"node_id": 14, "parameter": 90, "value": "True", "size":1 }
```
was I able to set it to really True:

```
2019-10-23 20:55:07.530 Info, Node014, Value::Set - COMMAND_CLASS_CONFIGURATION - Enables/disables parameter 91/92 - 90 - 1 - True
2019-10-23 20:55:07.719 Info, Node014, Received Configuration report: Parameter=90, Value=1
```
and now the switch really works as expected.

I'm assuming this is bug somewhere where the True value gets converted to 1 or something.
(maybe somehwere here: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/zwave/__init__.py#L658, or this is already getting the wrong value from the frontend)

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
**Traceback (if applicable):**

**Additional information:**

**Comment by electrofloat** [comment]
anti-stale

**Comment by electrofloat** [comment]
anti-stale

**Comment by crkochan** [comment]
Just chiming in to state that this is still an ongoing issue, so thanks to the OP for providing the means to get myself unblocked.

Home Assistant: 0.114.4
Frontend version: 20200811.0 - latest

**Comment by Joeviocoe** [comment]
Confirmed that this is still an issue in HA 0.115.2 with Frontend 20200918.0 - latest

**Comment by maivorbim** [comment]
This is still ongoing in latest HA 2020.12.7
