### ISSUE TITLE
Set view visibility from UI

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#4139]
I really love that we're able to hide views now in 0.101, and even on a per-user basis too. 

Currently this requires both YAML and User ID's which is more advanced. But by adding a third "Visibility" tab to the View Configuration UI this could be done in a really user friendly way by showing the list of users with toggles next to them. 

Here is a mockup:

![view-visibility](https://i.imgur.com/2ANoEQl.jpg)

**Comment by Misiu** [comment]
This would be an awesome improvement because not everyone is using YAML for views.

**Comment by Misiu** [comment]
Finding the correct place to add new tab was easy:https://github.com/home-assistant/home-assistant-polymer/blob/04f8f0f74f73cca61c94f756899b2f3f7a01837d/src/panels/lovelace/editor/view-editor/hui-edit-view.ts#L146
but the rest is much harder.
any hints on how to get a list of all users from HA and list of users that currently can access the specific view?

**Comment by Misiu** [comment]
I was able to set up a local dev environment.
Early WIP:
![image](https://user-images.githubusercontent.com/1741838/75047085-80d63080-54c6-11ea-9a74-ab0ff5437e35.png)
I must search for correct pieces I could reuse.
