### ISSUE TITLE
Add confirmation for HASSIO update button

### ISSUE THREAD

**Issue by Misiu** [home-assistant/frontend#4149]
**Is your feature request related to a problem? Please describe.**
Currently clicking on the update button equals immediate update and restart.
[Recent PR](https://github.com/home-assistant/home-assistant-polymer/pull/4053) added confirm dialog, so ideally clicking on `Update` should require confirmation.

**Describe the solution you'd like**
When clicking on the `Update` user should get clear info that a restart will be required and he should be able to confirm or cancel this action.

**Comment by Misiu** [comment]
I've looked into the source and I found these lines: https://github.com/home-assistant/home-assistant-polymer/blob/1e7497ad33b7377745cb33b4fdff0c88a24f6e72/hassio/src/dashboard/hassio-update.ts#L127-L131

How should I add confirmation dialog to `ha-call-api-button`?

I've looked at https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/components/buttons/ha-call-api-button.js but it doesn't have support for confirmation.
Should support be added in `ha-call-api-button`? This way all the places that use this component will benefit from this?
Maybe a property called `confirmText`? If set then the `ha-call-api-button` will ask for confirmation?

**Comment by bramkragten** [comment]
See <https://github.com/home-assistant/home-assistant-polymer/pull/3945>

**Comment by Misiu** [comment]
@bramkragten I missed that one :) unfortunately this one is using `window.confirm` and not `showConfirmationDialog`.
I'll try to set up the environment and will try to add the new confirmation dialog.

**Comment by bramkragten** [comment]
Be aware that the `confirmationDialog` will change with https://github.com/home-assistant/home-assistant-polymer/pull/4114

**Comment by Misiu** [comment]
I'll wait for #4114 to get merged and then start working on that.

**Comment by ludeeus** [comment]
This has been added in current dev.
