### ISSUE TITLE
Add arrows to input_number to allow easily editing the value

### ISSUE THREAD

**Issue by Misiu** [home-assistant/frontend#4151]
**Is your feature request related to a problem? Please describe.**
When editing the value of input_number on mobile devices You must "edit" the value manually.
We can specify min, max, and step, so it's an ideal place to use numeric up-down input, like this:
![image](https://user-images.githubusercontent.com/1741838/67759546-edbd4a80-fa3f-11e9-8ef1-195b74fd652a.png)

**Describe the solution you'd like**
Include up-down arrows near the input that will allow the user to increase/decrease the value of input by value of step parameter.
Reference component: https://ej2.syncfusion.com/javascript/demos/#/material/numerictextbox/range-validation.html

**Additional context**
It will allow easy changing value both on desktop and on mobile.

**Comment by bramkragten** [comment]
I think this would be a bad user experience on mobile. The browser should handle this.
