### ISSUE TITLE
Fonts not available without internet connection

### ISSUE THREAD

**Issue by casperklein** [home-assistant/frontend#4165]
**Home Assistant release with the issue:**
Home Assistant 0.101.1

**Operating environment (HassOS/Generic):**
hassio

**Description of problem:**

At least, the Hass.io dashboard page uses fonts from internet (fonts.googleapis.com).
Is that works-as-designed? Or should the font be locally, to even work without internet connection?

**Comment by bramkragten** [comment]
Our fonts are local, can you point me to where you see a font used from `fonts.googleapis.com`?

**Comment by casperklein** [comment]
Sure. Hope that helps:

![fonts](https://user-images.githubusercontent.com/590174/68038462-4bfd5e00-fcca-11e9-9038-afac3a55b120.png)

**Comment by bramkragten** [comment]
I don't see that in current dev, might be fixed as we have changed our build.

**Comment by ludeeus** [comment]
If I'm not mistaken the frontend of hassio runs a slightly older version so that _may_ be the reason it is still there.

**Comment by bramkragten** [comment]
Yeah it is part of the supervisor so isn't at the same schedule as HA. Will ask @pvizeli when there will a new release.

**Comment by casperklein** [comment]
fyi: Font and CSS are still loaded from the internet:

`Hass.io supervisor: 195`
`Home Assistant: 0.104.2`

**Comment by ludeeus** [comment]
The frontend that ships with Hass.io has not been updated in half a year.

**Comment by casperklein** [comment]
Thanks for clarification. I probably misunderstood @bramkragten. I thought, with a newer supervisor version it could be fixed, so I tested it again today.

**Comment by ludeeus** [comment]
It will need a newer SU version yes, but before that the submodule for the frontend inside home-assistant/hassio needs to be updated.

**Comment by casperklein** [comment]
Not solved with latest version Home Assistant 0.108.5 and Supervisor 217.

**Comment by casperklein** [comment]
Please reopen.

**Comment by merinleona** [comment]
According to my browser this happens because chunk.d660057100016e863290.js adds this resource:

  327: function(e, t) {
        const i = document.createElement("link");
        i.rel = "stylesheet",
        i.type = "text/css",
        i.crossOrigin = "anonymous",
        i.href = "https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic",
        document.head.appendChild(i)

to the document.
