### ISSUE TITLE
Lovelace warnings - make distinction between unavailable and disabled entities

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#4168]
When you disable an entity via the Entity Registry, the `hui-warning` stuff in Lovelace just says "Entity not available" like other truly missing entities. 

But in this case Home Assistant knows the exact reason _why_ the entity is not available (because the user personally disabled it), and it'd be helpful to tell the user that. Here is the idea:

![disabled](https://i.imgur.com/NO3C4TC.png)

Possible bonus perk of this: if you click on the "Entity disabled" warning row, it could open the same dialog you get when clicking on an entity in Entity Registry (so you'd be able to re-enable it or delete it entirely w/o leaving Lovelace).

**Comment by bramkragten** [comment]
We can't see if an entity is disabled as it is not in the states.
