### ISSUE TITLE
Dev Tools Service zwave.refresh_entity is not showing all usable entities

### ISSUE THREAD

**Issue by kpine** [home-assistant/frontend#4184]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.101.2

**Last working Home Assistant release (if known):**
Unknown

**UI (States or Lovelace UI?):**
Lovelace UI, Frontend version: 20191025.1 - latest

**Browser and Operating System:**
Both Chrome 77.0.3865.120 and Firefox 70.0
Windows 10

**Description of problem:**
In the Developer Tools -> Services page, the Z-Wave integration provides a `zwave.refresh_entity` service call with an entity ID as the data. The UI also provides a convenient drop-down list already populated with relevant entities. The problem is that the list is only filled with entities of the `zwave` domain. It does not populate with other valid entities like sensors (battery levels, alarm values, etc). You can manually type in alternate entities, and it works, but it would be much more useful if it was populated with the other valid entities. I am not sure refreshing the `zwave` entities actually does anything, since under the hood the zwave "values" (OZW terminology) are what need to be refresh, which are represented by the other entities.

Example:
![image](https://user-images.githubusercontent.com/791794/68145493-c3a9d380-feea-11e9-94d4-dd35c5faca4b.png)

Compare that to the Z-Wave Control panel, which offers the same functionality. When you select a node, it offers a list of the node's entities. There's a button "Refresh Entity" that does the same thing as the service call.
![image](https://user-images.githubusercontent.com/791794/68145638-1b483f00-feeb-11e9-99f2-bff455a633b7.png)

Clicking "Refresh Entity" in that screenshot results in the following in the `OZW_Log.txt` file, indicating the battery level refresh command has been queued.
```
2019-11-04 10:09:32.712 Info, mgr,     Refreshing node 19: COMMAND_CLASS_BATTERY index = 0 instance = 1 (to confirm a reported change)
2019-11-04 10:09:32.712 Detail,
2019-11-04 10:09:32.712 Detail, Node019, Queuing (WakeUp) BatteryCmd_Get (Node=19): 0x01, 0x09, 0x00, 0x13, 0x13, 0x02, 0x80, 0x02, 0x25, 0x87, 0xd4
```
Using the service call with service data `entity_id: sensor.front_door_sensor_battery_level` results in the same thing:
```
2019-11-04 10:11:20.087 Info, mgr,     Refreshing node 19: COMMAND_CLASS_BATTERY index = 0 instance = 1 (to confirm a reported change)
2019-11-04 10:11:20.087 Detail,
2019-11-04 10:11:20.087 Detail, Node019, Queuing (WakeUp) BatteryCmd_Get (Node=19): 0x01, 0x09, 0x00, 0x13, 0x13, 0x02, 0x80, 0x02, 0x25, 0x88, 0xdb
```

**Javascript errors shown in the web inspector (if applicable):**
N/A

**Additional information:**
None

**Comment by kpine** [comment]
The issue still exists in 0.104.3.

**Comment by brillb** [comment]
This still exists in 0.118.4, also the Automation GUI editor is the same interface as the developer tools screenshots, and it also does not allow all entities to be refreshed.
