### ISSUE TITLE
Add Unifi disable entity option on setup

### ISSUE THREAD

**Issue by decairn** [home-assistant/frontend#4235]
**Is your feature request related to a problem? Please describe.**
A good number of users want the Unifi integration simply for the presence detection of their phones and not for much else, current integration enables 10s or 100s of entities and requires user to manually go into every one to disable them (5 clicks each item?) after integration is added.

**Describe the solution you'd like**
Add a checkbox to the integration dialogue to have all entities disabled / enabled directly upon successful integration.  Bonus points if it includes other options like SSID that can be configured in YAML after integration is setup.

**Describe alternatives you've considered**
Using another solution like Owntracks for presence detection, but that requires adding software onto the mobile devices.

**Additional context**

**Comment by bramkragten** [comment]
This is an integration specific request and should be done on the core repo.
