### ISSUE TITLE
Entities Card: Icons based on state

### ISSUE THREAD

**Issue by Zefau** [home-assistant/frontend#4264]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
For the entities card it would be great to show a different icon based on the state of the switch or sensor, e.g. having the window open show a different icon than having it closed.

**Describe alternatives you've considered**

**Additional context**
Reads a bit like https://github.com/home-assistant/home-assistant-polymer/issues/3897, but this one does not change the color of the icon, but the icon itself.

**Comment by pascallj** [comment]
Although I agree this would be a nice feature, I think this should be a feature of the backend instead of the frontend. Please note that what you want is already possible in the backend (although being slightly cumbersome) using the [Template Sensor](https://www.home-assistant.io/integrations/template/) with the `icon_template` attribute.

An example of this which I used in the past:
```yaml
icon_template: >
  {% if not is_state('sensor.dewpoint_outside', 'unknown') %}
    {% if float(states('sensor.dewpoint_outside')) < 10 %}
      mdi:emoticon-neutral-outline
    {% elif float(states('sensor.dewpoint_outside')) >= 10 and float(states('sensor.dewpoint_outside')) < 12 %}
      mdi:emoticon-excited-outline
    {% elif float(states('sensor.dewpoint_outside')) >= 12 and float(states('sensor.dewpoint_outside')) < 16 %}
      mdi:emoticon-outline
    {% elif float(states('sensor.dewpoint_outside')) >= 16 and float(states('sensor.dewpoint_outside')) < 18 %}
      mdi:emoticon-happy-outline
    {% elif float(states('sensor.dewpoint_outside')) >= 18 and float(states('sensor.dewpoint_outside')) < 21 %}
      mdi:emoticon-neutral-outline
    {% elif float(states('sensor.dewpoint_outside')) >= 21 and float(states('sensor.dewpoint_outside')) < 24 %}
      mdi:emoticon-sad-outline
    {% elif float(states('sensor.dewpoint_outside')) >= 24 and float(states('sensor.dewpoint_outside')) < 26 %}
      mdi:emoticon-angry-outline
    {% else %}
      mdi:emoticon-dead-outline
    {% endif %}
  {% else %}
    mdi:help-circle-outline
  {% endif %}
```

This works everywhere in the frontend where the `icon` attribute is displayed.

**Comment by Zefau** [comment]
Thank you very much for your quick reply and the detailed answer.

I'm using ioBroker with an adapter (see https://github.com/ioBroker/ioBroker.lovelace) based on this repository (with a few changes adapting it to ioBroker).

This means that only the frontend that this repository provides is available. The backend solution you have provided is unfortunately not available to me.

Is there any chance for an implementation via frontend?

Thanks you and kind regards,
Zefau

**Comment by iantrich** [comment]
what the what?!? that is quite impressive that they are doing that in ioBroker. Very cool.

Anyways, as for your request, this can be done with my custom card [config-template]card](https://github.com/iantrich/config-template-card)

**Comment by Zefau** [comment]
Thanks for that hint. Looks like a great card, but unfortunately does not seem to work with ioBroker (not sure though if I'm too stupid to set it up).
Getting the error `No card type found` in the preview as well as ` this._configElement is undefined` just below the configuration box.

**Comment by zsarnett** [comment]
![f06d2cc9055f2b1c8206e1ca46865944](https://user-images.githubusercontent.com/18730868/94046205-063ffd00-fd96-11ea-9b92-a73114554066.gif)

This exists
