### ISSUE TITLE
UI does not render properly on Kindle Fire HD8

### ISSUE THREAD

**Issue by GeertKnapen** [home-assistant/frontend#4287]
**Checklist:**

- [x] I updated to the latest version available

- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.102.2

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
LovelaceUI

**Browser and Operating System:**

**Description of problem:**

![Screenshot_20191127-195404](https://user-images.githubusercontent.com/50683850/69777378-db285500-1154-11ea-80de-c304f2728376.png)

The Lovelace UI in the Overview view does not render properly on my 2 Kindle Fire HD8 tablets (most recent version). The farther to the right of the screen, the more jagged the characters look. See attached screen shot. All other views (developer, Hass.io, Configurator, etc.) render with very smooth fonts. I see the exact same behavior whether I use the home assistant app, or any browser (Silk, Fully Kiosk, ...).

One other observation: when I disable graphics hardware acceleration on Fully, the Overview view renders correctly, but of course, the response is very sluggish, so not really an option.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by ol3k** [comment]
I got the same issue, but looks like there aren't any others who face the same problem.

**Comment by GeertKnapen** [comment]
I solved it as follows:
Enable Developer Mode by going into Settings > About > tap 7 times on build number or serial number
In Settings > Device Options > Developer Options, go to Small Width setting. Set to 533

**Comment by ol3k** [comment]
thx! works like a charm :-)

**Comment by Ramonkagie** [comment]
@GeertKnapen Hi Geert,

Got the same issue, although I don't have an option 'Small width' in developer settings. I'm on a Amazon Fire HD 8. Any idea? Or another workaround?
