### ISSUE TITLE
IOS 10.3.3: Unable to switch toggle

### ISSUE THREAD

**Issue by williamgeurts** [home-assistant/frontend#4292]
I use several IOS devices. I have one ipad running on IOS 10.3.3. It only does Homeassistant and cannot be updated anymore. Since the 2.0 IOS APP update I have a strange problem: I cannot operate a switch (like a light switch or an input_boolean). The sensor status is correct updated. Also the notification menu is not working. Safari or Chrome on IOS give the same results. Al my other IOS devices are correct working. I did a complete re-install of the Ipad and I did the Beta testing cleaning between builds procedure. TomBrien suggested to add an issue. Any suggestions?

**Comment by bramkragten** [comment]
What version of home assistant are you running?

I just tested our demo (https://demo.home-assistant.io) on a iOS 10.3 iPad and that seems to work fine.

**Comment by williamgeurts** [comment]
0.102.2 - I use the IOS app, unfortunately I upgrade from 0.101 to 0.102 and at the same moment I upgraded the IOS app. After the upgrade I noticed that it was not working anymore. So I tried many things (fresh install), but later I discovered that Safari and Chrome are also not working correctly. I will post the result of the downgrade once I downgraded the HA.

The demo woks also on my old Ipad. I feels the same on my HA, but the lights are not switch on or off.

**Comment by bramkragten** [comment]
Wait, you can switch the toggle but nothing happens? Or you can't switch the toggle?

**Comment by williamgeurts** [comment]
I can toggle the switch but nothing happens.

**Comment by haxln** [comment]
I have exact the same issue. Also upgraded to 2.0 IOS app - latest ios version on ipad and iphone works perfectly. But I have an older ipad installed as a dashboard with ios version 10.3.3 that doesn’t work anymore.
Additionally, I figured out that DeveloperTools->logs loads forever and Configuration->Integrations and Configuration->Devices are empty on this device!?!
