### ISSUE TITLE
entities card with climate entity flows outside card

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#4301]
**Home Assistant release with the issue:**

102.2

**Last working Home Assistant release (if known):**

don't know
**Operating environment (Hass.io/Docker/Windows/etc.):**

Hassio rpi4
**Integration:**

entities card using a climate entity
**Description of problem:**

state of the card flows outside the lovelace borders when resizing

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
  - type: entities
    entities:
      - entity: climate.kantoor
```

**Traceback (if applicable):**
```

```

**Additional information:**
![Schermafbeelding 2019-12-01 om 17 21 30](https://user-images.githubusercontent.com/33354141/69921155-1053e080-1490-11ea-843a-475a5cb08fd4.jpg)

**Comment by iantrich** [comment]
How are you using this? I can't replicate. If I make it too small it gets truncated as expected in a horizontal-stack
![image](https://user-images.githubusercontent.com/1287159/72582737-639bba00-38a9-11ea-9e51-b1ea9ed31ef6.png)
