### ISSUE TITLE
Shading on Climate Card is Wrong

### ISSUE THREAD

**Issue by CaptTom9** [home-assistant/frontend#4311]
I’m running hass.io on a Raspberry Pi 3B+, HA version  0.102.3. I have three Honeywell thermostats. I display the climate data in Lovelace with a History Graph card.

I believe the wrong attribute is being used to display the shaded area of the graph.

Prior to about version 0.96, the graph used to show a shaded area under the line when the system was actively heating or cooling; red for heading, green for cooling. There were big changes in 0.96 to the climate integration,  most very beneficial, but one change apparently caused that shading feature to no longer display at all.

That was fixed, and I confirmed in a later release that I was seeing the green shading again when the hvac_action attribute was “cooling.” Of course, it was summer so I wasn’t looking for the red shading for heat.

Now that fall is here, I discovered that the graph isn’t showing the hvac_action attribute at all. Instead, it appears to be drawing green shading only when the fan_action is "running," and no shading when the fan is idle. It won't draw a red bar, even when hvac_action is "heating."

The fan_action is not the correct attribute to use to indicate either heating or cooling.

There is no fan for baseboard heaters. And for cooling, the fan is set to run for a while after the compressor stops. Finally, it’s possible to set the thermostat to run the fan in “continuous mode,” so it would always show the green shading, even if there was no cooling running all day.

I think this is a bug. The graph should shade red when hvac_action is “heating” and green when it is “cooling.” There should be no shading when just the fan is running.
![Heating Card Heating](https://user-images.githubusercontent.com/58441524/69985020-73815980-1508-11ea-89e4-c86804060a46.jpg)

As you can see, although the system is heating, the shading is green, indicating cooling.

Below are the attributes at the time the green shading is being displayed:
![Climate Attributes](https://user-images.githubusercontent.com/58441524/69985288-e68ad000-1508-11ea-9e6e-28dccb4e954e.jpg)

**Comment by bramkragten** [comment]
The fan doesn't seem to be used in the graph. Can you provide the raw data from the api command to get the history data?

You can find it in the network tab of the dev tools of the browser, something like:
<http://localhost:8123/api/history/period/2019-12-02T09:04:01.784Z?filter_entity_id=climate.hvac&end_time=2019-12-03T09:04:01.784Z>

**Comment by CaptTom9** [comment]
Thank you for looking at this!!

In my original testing it seemed consistent that the green shading appeared on the graph whenever the "fan_action" attribute was "running," regardless of whether the "hvac_action" was heating, cooling or idle. Also, even when in heating mode, the shading is always green, not red. Finally, on the two thermostats which have no fan mode, the shading never appears, even when heating. These symptoms are what led me to conclude the shading is based on the fan_action, not the hvac_action.

I don't see a network tab on the dev tools in Lovelace. HA is running on hass.io on a headless RPi, so I don't have a web browser on the device (localhost.) When I try that same URL with the appropriate IP address, I get "401: Unauthorized."

Sorry, I don't have a lot of experience with Linux, but I can follow directions and use Google pretty well.

**Comment by bramkragten** [comment]
The network tab is on the browsers dev tools (F12), not in Home Assistant. Refresh the page after you located the network tab.

The shading is green, also for heating that is correct.

**Comment by CaptTom9** [comment]
Ahh, my mistake. Here's the call:

```
Request URL: http://192.168.###.###:8123/api/history/period/2019-12-03T12:49:22.921Z?filter_entity_id=climate.1st_floor&end_time=2019-12-03T12:49:28.817Z&skip_initial_state
Request Method: GET
Status Code: 200 OK
Remote Address: 192.168.###.###:8123
Referrer Policy: same-origin
```

Where would I go to find the raw data it returned? It's been a while since I did any HTML debugging, and things were a lot simpler then!

You're right that the shading doesn't exactly follow the fan mode. I turned the thermostat heat off, waited a few minutes, and turned the fan on for a few minutes. The attribute changed, but the shading did not appear this time. The fact that the shading doesn't appear for the thermostats without a fan is what steered me down that path. But it still might be a clue.

So if it's supposed to be green shading, even for heat, then the question becomes: Why do two of my three thermostats never show the shading, while one appears to be working correctly?

Another clue is that the "working" thermostat controls both heat and cooling, while the two others only control heat. Otherwise, they're identical hardware, all communicating the same way.

**Comment by bramkragten** [comment]
Click on the `Response` tab

**Comment by CaptTom9** [comment]
> Click on the `Response` tab

Thank you for the quick replies, and your patience! When I record opening the history graph display, I get one response containing all the attributes for each change over the past 24 hours or whatever.

Below is the first entry. I only added a couple of carriage returns for clarity. There are 128 more in the data the browser received from HA:
```
{"attributes": 
{"current_humidity": 128, "current_temperature": 70, "dr_phase": -1, "fan_action": "idle", "fan_mode": "auto", "fan_modes": ["on", "auto"], "friendly_name": "1st Floor", "hvac_action": "heating", "hvac_modes": ["off", "cool", "heat"], "max_temp": 90, "min_temp": 40, "preset_mode": null, "preset_modes": ["none", "away"], "supported_features": 27, "target_temp_high": null, "target_temp_low": null, "temperature": 70},
 "context": 
{"id": "6f6460d2e6ae4fb8b15273e47e40ee74", "parent_id": null, "user_id": null},
 "entity_id": "climate.1st_floor", "last_changed": "2019-12-02T20:26:27.215320+00:00", "last_updated": "2019-12-02T20:44:33.763566+00:00", "state": "heat"},
```
