### ISSUE TITLE
mobile_app integrations are scattered/not listed together

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#4313]
**Home Assistant release with the issue:**

102.2

**Last working Home Assistant release (if known):**

never?
**Operating environment (Hass.io/Docker/Windows/etc.):**

Hassio Rpi4
**Integration:**

monile_app
**Description of problem:**

When having several mobile_app integrations, one would expect these to be listed together.
As it stands, they are scattered all through the list of integrations which is not a pretty sight, nor very easy in checking the integration set, especially when this list is longer than a current window view and one needs to scroll the list.....

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml

```

**Traceback (if applicable):**
```

```

**Additional information:**
Tbh, it is rather unclear how the list of Integrations is ordered, not alphabetically, nor sequentially in order of addition. Anyways, please consider grouping integrations of the same domain, in this case Mobile App.

a snippet to illustrate:
![Schermafbeelding 2019-12-03 om 01 31 59](https://user-images.githubusercontent.com/33354141/70006260-c3920780-156c-11ea-8dfb-72e1409f9aab.jpg)

**Comment by springstan** [comment]
@frenck thanks for moving this issue :) In addition this issue could be tagged with `feature request` for full transparency.

**Comment by SeanPM5** [comment]
As far as I can tell it's sorted alphabetically by device name. You can see in the boxes I highlighted, the green box is alphabetical: O, P, S, T ,T, Z... and then same for the bottom red box - h, iPa, iPh.

Problem is that it's making a distinction between uppercase and lowercase for some reason, which seems kinda arbitrary?

![sort](https://i.imgur.com/sKFoD6x.jpg)

I think the behavior that most would expect would be sorted alphabetically by integration first, and _then_ alphabetically by device name on top of that (and don't take into account case).

So in this instance, it should be:

Mobile App: iPad R
Mobile App: iPad v
Mobile App: iPhone
Mobile App: Telefo
Mobile App: Znorr

**Comment by Mariusthvdb** [comment]
not really sure, should have displayed the top of the intergrtions list also....:

![Schermafbeelding 2019-12-05 om 07 10 58](https://user-images.githubusercontent.com/33354141/70208671-7eb5ce80-172e-11ea-96a6-10f48aafbf0a.jpg)

do agree with what it should be like:

> sorted alphabetically by integration first, and then alphabetically by device name on top of that (and don't take into account case).

added to that, it should also be grouped by integration if possible. As an example: when configuring  zones through the integration, all zones are listed separately, while it would be much easier in the eye if they would all be listed like eg Hue or Ikea or iOS for that matter: 1 main integration title, with many individual entities in that integration.

Ive created an extra Zone to illustrate this, and it is appended to the bottom of the list...:

![Schermafbeelding 2019-12-05 om 07 16 40](https://user-images.githubusercontent.com/33354141/70208957-34811d00-172f-11ea-8be8-6ba5203e97f0.jpg)

while another Zone is halfway in the middle:

![Schermafbeelding 2019-12-05 om 07 17 39](https://user-images.githubusercontent.com/33354141/70209004-58446300-172f-11ea-8845-b7c2e719cf9a.jpg)
