### ISSUE TITLE
Logbook entries misaligned

### ISSUE THREAD

**Issue by quthla** [home-assistant/frontend#4326]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.103b0

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**

**Browser and Operating System:**
Android 10 latest Chrome stable

**Description of problem:**
Multiline entries misaligned and random icon sizing

Gap between time and icons could be a little smaller too imo
![Screenshot_20191206-135449](https://user-images.githubusercontent.com/30180109/70324827-cf155500-1830-11ea-9605-1f1957423750.jpg)

**Expected behaviour:**

**Relevant config:**

**Steps to reproduce this problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by quthla** [comment]
Not fixed yet

**Comment by bramkragten** [comment]
Yeah it is 
![Uploading image.png…]()
