### ISSUE TITLE
Problem with ifttt alarm control panel in 0.103.0

### ISSUE THREAD

**Issue by 03397** [home-assistant/frontend#4347]
After upgrade to version  0.103.0 the ifttt alarm control panel throws an error whenever I hit arm away/arm home/disarm. But the action is completed successfully 

https://xxxxxxxxxxxxxxxxxxxxxxxxx/frontend_latest/chunk.d5961ced1d8380ae21ba.js:2976:712 Uncaught TypeError: Cannot set property 'value' of null

arch | armv7l
-- | --
dev | false
docker | false
hassio | false
os_name | Linux
python_version | 3.7.3
timezone | Europe/Nicosia
version | 0.103.0
virtualenv | true

**Comment by SeanPM5** [comment]
The release notes for 0.103.0 mention a breaking change for IFTTT alarm control panel. Service was renamed from `alarm_control_panel.ifttt_push_alarm_state` to `ifttt.push_alarm_state` 

So I think you might simply need to update your webhook applets on the IFTTT website. 

this part of url:

`/api/services/alarm_control_panel/ifttt_push_alarm_state`

should be changed to:

`/api/services/ifttt/push_alarm_state`

**Comment by 03397** [comment]
@SeanPM5
I have already changed my body of the json to 
{ "action": "call_service", "service": "ifttt.push_alarm_state", "entity_id": "alarm_control_panel.myhome_alarm", "state": "disarmed" }

The states change just fine, I am just getting this error message

**Comment by 03397** [comment]
Just to add to  the ticket.
This happens only when  I press the button from the frontend.
No error message when automation is triggered or when I test the services.

**Comment by 03397** [comment]
After upgrade to 0.103.2 problem still there,

**Comment by iantrich** [comment]
@03397 unless this ticket has been closed or you find that it has been resolved, no need to comment that it still exists. Thanks.

**Comment by 03397** [comment]
After the upgrade to 0.104.2 the error changed to 
:0:0 Script error

**Comment by Halytskyi** [comment]
The same issue on 0.106.2, but only when "code" parameter not configured in config. With "code" defined - no issues.

**Comment by 03397** [comment]
The issue is still there. 
Why did you guys close the ticket?

**Comment by bramkragten** [comment]
Because it is fixed in https://github.com/home-assistant/frontend/pull/5291

**Comment by 03397** [comment]
It most fixed.
I can sent you logs if you want.

**Comment by 03397** [comment]
This is as my previous comment
Logger: frontend.js.latest.202003181
Source: components/system_log/__init__.py:209
First occurred: 5:00:01 PM (2 occurrences)
Last logged: 5:00:12 PM

:0:0 Script error.

**Comment by bramkragten** [comment]
It is fixed, but the fix is not released yet. It will be in 0.108.
