### ISSUE TITLE
Add ability to search for entity_id to customize UI

### ISSUE THREAD

**Issue by robin13** [home-assistant/frontend#4351]
**Home Assistant release with the issue:** 0.102.2

**Description of problem:**

On the `Configuration -> Customizations` UI you can only search / view the current name of the device.  If you have accidentally given two devices the same name, it is very difficult to correct them as you cannot see the entity_id related to each.  It would be great if it were possible to view (and search) on both the name and the entity_id here.

**Comment by bramkragten** [comment]
This should use the entity picker element.
