### ISSUE TITLE
Valid tap_actions in the UI produce warning in GUI editor.

### ISSUE THREAD

**Issue by Petro31** [home-assistant/frontend#4355]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Home Assistant release with the issue:** 0.103

**Last working Home Assistant release (if known):** Unknown

**UI (States or Lovelace UI?):** Lovelace, Editor

**Browser and Operating System:** All

**Description of problem:** When using valid tap_action yaml inside entities list in Glance and entities card (others possibly as well), there is a warning about unexpected value types.  It's only expecting 'entity', 'name', 'icon'.  'tap_action' should be expected with the correct underlying configuration fields.

**Expected behaviour:** No warning about possible incorrect format.

**Relevant config:**

```
type: glance
entities:
  - entity: light.kitchen_lights
    tap_action:
      action: toggle
```

**Steps to reproduce this problem:** I reproduced the issue in the demo.  So literally copy the yaml above and paste it into code editor in the GUI.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by iantrich** [comment]
The editors need a lot of love ;)

**Comment by Petro31** [comment]
This could still be considered stale, but yesterday I answered another post where the person was confused about the warning in yellow instead of looking at the preview.  Maybe this can be re purposed to address all the warnings?

**Comment by SeanPM5** [comment]
Still an issue in 0.111. 

It can be saved still, but I think the warning text will probably scare most people off from doing so.

**Comment by Petro31** [comment]
I think we should just get rid of the warning.  I can't count how many people make a forum post referencing those as errors.  They aren't understanding that its a warning.  Not to mention, its 100% valid configuration.

**Comment by iantrich** [comment]
@bramkragten I'm in favor of removing the warning as well
