### ISSUE TITLE
Make 'preview'/trigger of scenes in scenes editor optional

### ISSUE THREAD

**Issue by timmo001** [home-assistant/frontend#4360]
**Describe the solution you'd like**
So I've just converted to using the scenes editor which is really nice.

When editing a scene, the scene gets triggered and restored after editing. The issue I get here is I have some lights (old-school christmas lights toggled by plugs at the time of opening this issue) which should not really be turned off as they have to be manually changed (unfortunately) every time they are turned on. I also have some dummy scenes which trigger automations also.

The feature I am requesting, is to turn off this functionality for individual scenes which can be troublesome.

**Additional**
This might be an additional property in the yaml so this issue may be more suited to the backend, but I guess the functionality is from the frontend

**Comment by bramkragten** [comment]
The problem is that the scene editor only stores the current state of the entities in the scene. So the editor will not work if the entities are not in the state of the scene you are editing.

**Comment by timmo001** [comment]
I found an alternative for this using scripts and/or automations so will close since this
