### ISSUE TITLE
table width not adjustable developer tools/state

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#4363]
**Home Assistant release with the issue:**

103/2
**Last working Home Assistant release (if known):**
not sure, but seems to have gotten worse lately 

**Operating environment (Hass.io/Docker/Windows/etc.):**

Hassio Rpi4
**Integration:**

**Description of problem:**
Probably because of a state with a long  state entity_id, the table width is automatically focussed based on that length. depending on the screen real estate, this renders a practically empty window for many entities, especially the ones that have something to say in the attributes.

In fact, this is unworkable, hence Ive taken my previous feature request to a bug now. I am on a 15" MacBook and this is what I see

![Schermafbeelding 2019-12-18 om 10 53 32](https://user-images.githubusercontent.com/33354141/71076168-8beaa880-2185-11ea-8795-b7362f1a1406.jpg)

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml

```

**Traceback (if applicable):**
```

```

**Additional information:**

Allowing adjustable table width here could solve a lot. Imagine most of the states are on,/off, or at least something quite short, and now take most of the screen width....

![Schermafbeelding 2019-12-18 om 11 03 15](https://user-images.githubusercontent.com/33354141/71076460-09aeb400-2186-11ea-9c1f-918ac4d846f1.jpg)

if we could resize that column, it would give space to the attributes, and make the state page workable again.

deselecting attributes illustrates that, but, of course, is no solution. it btw also illustrates the unnecessarily allowed screen estate for filter states:

![Schermafbeelding 2019-12-18 om 11 05 14](https://user-images.githubusercontent.com/33354141/71076651-614d1f80-2186-11ea-948d-ff64194b6cf4.jpg)

please see FR https://community.home-assistant.io/t/adjustable-table-width-for-developer-tools-state/153125

**Comment by bramkragten** [comment]
What is making it so stretched?

**Comment by Mariusthvdb** [comment]
I can only imagine it auto fits the longest entity_id, and probably the longest state. But we should be able to override /adjust that, because now all attributes get crammed into the little space on the right side, which cause the huge vertical (empty) spacing issue.

**Comment by iantrich** [comment]
Could we add `word-break: break-all`? for the columns @bramkragten ?

**Comment by bramkragten** [comment]
I think that will have some nasty side effects, give it a try

**Comment by Spirituss** [comment]
Face  the same problem, attributes are unworkable in fact.
