### ISSUE TITLE
Smaller time ranges for logbook query

### ISSUE THREAD

**Issue by robin13** [home-assistant/frontend#4372]
**Is your feature request related to a problem? Please describe.**

Querying the logbook takes a very long time (>1 minute) to refresh.  I presume that this is due to the number of entries because if I change to 3 days it takes even longer. 

**Describe the solution you'd like**
Often when I am trying to debug a situation, I am only interested in the last hour, so it would be nice to have to have the ability to only query the last hour and not the last day(s) - presumably this would make the refresh faster too.

**Describe alternatives you've considered**
<none>

**Additional context**
<none>

**Comment by bdraco** [comment]
This was implemented in the last frontend

**Comment by frenck** [comment]
It was implemented in: https://github.com/home-assistant/frontend/pull/6192
And will be released with Home Assistant 0.112.0 🎉
