### ISSUE TITLE
Show map in more info dialog if entity has location

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#4388]
**Is your feature request related to a problem? Please describe.**
Not easy to see location of an entity on a map

**Describe the solution you'd like**
When I open more info dialog of an entity that has a location, let's show it on the map!

**Describe alternatives you've considered**
none

**Additional context**

**Comment by iantrich** [comment]
Anything besides device tracker and person that would qualify?

**Comment by balloob** [comment]
Just look if entity has latitude and longitude

**Comment by bramkragten** [comment]
This is done for person
