### ISSUE TITLE
Template support for weblink

### ISSUE THREAD

**Issue by vaidyasr** [home-assistant/frontend#4397]
**Is your feature request related to a problem? Please describe.**
I have dozens of smart devices which have their own web config page. My Mesh router doesn't support static IPs leading to find out the IP address from the properties of the device or from the router app and then browse to the respective link.

**Describe the solution you'd like**
The weblink right now supports only static text which is not possible for every time to edit my ip address to browse. Instead the device_tracker maintains the ip address field too. So, the weblink should support template so, I can define ip address from the device attributes.

**Describe alternatives you've considered**
Tried with Markup which was recently implemented the template option. But still I can't make the icons in the page. I need to download each image to show before the link icon similar to weblink and the alignment is not possible.

**Comment by bramkragten** [comment]
We will not implement this, it is expensive to listen for templates for every weblink. You should use markdown (you can use `<ha-icon icon="mdi:icon"></ha-icon>`) or a custom card.
