### ISSUE TITLE
Include Friendly Name in autocomplete for entity picker

### ISSUE THREAD

**Issue by Todilo** [home-assistant/frontend#4399]
**Is your feature request related to a problem? Please describe.**
It would be useful for the entity picker to filter not only on the identity name (like light.table) but also for the _Overridden name_ as defined under configuration.

**Describe the solution you'd like**
Include Overridden name in autocomplete filter method.

**Note from @thomasloven:** "Overridden name" = Friendly name

**Comment by bramkragten** [comment]
We should implement https://vaadin.com/components/vaadin-combo-box/java-examples/filtering in the entity picker
