### ISSUE TITLE
"Host system" Frontend Reboot and Shutdown buttons have no confirmation dialogue

### ISSUE THREAD

**Issue by jhollowe** [home-assistant/frontend#4417]
**Home Assistant release with the issue:** 0.103.5

**Operating environment (HassOS/Generic):** HassOS

**Supervisor logs:** None

**Description of problem:** I would expect the frontend buttons for shutting down or rebooting the host would have similar dialogues to the restart and stop Home Assistant ("Configuration>Server Controls"). It would seem that controlling the host should be even more guarded than the Home Assistant instance.

**Comment by frenck** [comment]
Move this issue to our frontend repository, as this is a frontend feature for the Hass.io panel

**Comment by ludeeus** [comment]
The same applies to the Update buttons on the main dashboards since those also will restart the instance.
I will look into it, but #4393 is needed first, and I really want to be done with #4398 before adding/changing more.

**Comment by ludeeus** [comment]
Not stale, in the works
