### ISSUE TITLE
Unable to get property 'state' of undefined or null reference

### ISSUE THREAD

**Issue by chemelli74** [home-assistant/frontend#4420]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:** 0.103.0

**Last working Home Assistant release (if known):** not known

**UI (States or Lovelace UI?):** Lovelace UI

**Browser and Operating System:** Microsoft Edge and Firefox - Windows 10  build 1903

**Description of problem:**

2020-01-04 19:27:35 ERROR (MainThread) [frontend.js.latest.201912041] https://www.yyyyyy.com:8423/frontend_latest/chunk.2da1c2f71dc0b6131553.js:484:860 Unable to get property 'state' of undefined or null reference
2020-01-04 19:29:23 ERROR (MainThread) [frontend.js.latest.201912041] https://www.yyyyyy.com:8423/frontend_latest/chunk.2da1c2f71dc0b6131553.js:484:860 Unable to get property 'state' of undefined or null reference

**Expected behaviour:** No error recorded in the log

**Relevant config:**

**Steps to reproduce this problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by ludeeus** [comment]
Go through your views, somewhere there you will have a reference to an entity_id that no longer exists with the defined name.

**Comment by chemelli74** [comment]
> Go through your views, somewhere there you will have a reference to an entity_id that no longer exists with the defined name.

You are right.
But I would expect the null reference to be catch and the entity_id name recorded in the log.

Simone

**Comment by iantrich** [comment]
What card was it in?

**Comment by chemelli74** [comment]
I created card using "groups.yaml", no custom card.

Simone

**Comment by ludeeus** [comment]
"groups.yaml"?
In your URL does it say /states or /lovelace?

**Comment by chemelli74** [comment]
> "groups.yaml"?
> In your URL does it say /states or /lovelace?

https://ha.xyz.com:8423/lovelace/default_view

**Comment by chemelli74** [comment]
Would love to have some feedback.

Simone

**Comment by bramkragten** [comment]
We need to know what card throws this error, check your browser console.

**Comment by chemelli74** [comment]
> We need to know what card throws this error, check your browser console.

Sorry for the late answer.
The affected card is "entities".

Simone

**Comment by chemelli74** [comment]
Any update ?

Simone

**Comment by bramkragten** [comment]
Do you still get this error with the latest Home Assistant version? If so, could you add a new stack trace here?

**Comment by chemelli74** [comment]
Updated to latest version and error is gone, cannot reproduce in last 4 days.

Simone
