### ISSUE TITLE
History and Logbook should respect the server's timezone instead of the client's

### ISSUE THREAD

**Issue by melyux** [home-assistant/frontend#4421]
**Checklist:**

- [Yes] I updated to the latest version available
- [Yes] I cleared the cache of my browser

**Home Assistant release with the issue:**  0.103.5

**Last working Home Assistant release (if known):** N/A

**UI (States or Lovelace UI?):** 20191204.1 - latest

**Browser and Operating System:** Safari client, Debian (docker) server

**Description of problem:**

The history graphs and the logbook should be respecting the server's timezone instead of the client's.

**Expected behaviour:**

The history graphs and the logbook show times in the browser/app's local timezone instead of the actual server site's.

**Relevant config:**

Default config

**Steps to reproduce this problem:**

Just have any accessories that show up in the logbook and history, and have the server be in a different timezone than the accessing client.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by bramkragten** [comment]
I think it makes more sense to have it using the client time zone, why would you not want it to do that?

**Comment by melikyuksel** [comment]
Why would it make more sense to use the client time zone? Automations run using the server time, and the history view for things that have happened “today” only make sense if that today starts at 12 am at the server, not the client (as it does now). Everything Home Assistant does is based on server time. Every remote management software I’ve seen either defaults to server time or allows a choice between site and browser time (UniFi, Blue Iris, AlarmDecoder, etc.).

**Comment by bramkragten** [comment]
Maybe I don't understand you, but I assume your client time is the right time, as in, the time zone you are in at the moment? So you want so see when the events happen relative to that time?

**Comment by melikyuksel** [comment]
I don’t understand. The client time is the time zone of the browser you access Home Assistant with, and the server time is the time zone of the actual server Home Assistant is running on. Right now, events and time stamps and charts on the client are based in the client’s timezone. I think it makes more sense for them to be based in the server’s timezone.

**Comment by drthanwho** [comment]
I'm also experiencing the same issue. In my use case HA runs on a +2 time zone, whereas I live abroad at a +1 timezone so when I'm on lovelace everything I see even though correct are adjusted for my timezone, which makes is complicated. It's easier for the brain to workout things knowing the time you see it's the time at home rather than having to calculate what time is at home given the time you see on your browser
