### ISSUE TITLE
Translation error in scenes.

### ISSUE THREAD

**Issue by JosepZ** [home-assistant/frontend#4458]
I've got the translation error in scenes editor after created a new scene "The intl string context variable "nombre" was not provided to the string 'escena activada{nombre}'. For Spanish frontend.

**Comment by frenck** [comment]
`{name}` should not have been translated.

You can help in translating Home Assistant and to fix this issue!

<https://developers.home-assistant.io/docs/en/internationalization_translation.html>

(No programming involved).

**Comment by JosepZ** [comment]
I register myself on lokalise and  tried, but I can't found where the translation error is.
