### ISSUE TITLE
Single repository for devices, lights, etc regardless of if they come from platforms, integration or elsewhere

### ISSUE THREAD

**Issue by mcinnes01** [home-assistant/frontend#4471]
**Is your feature request related to a problem? Please describe.**

Currently regardless of if I check integrations, entities or devices, I won't see any lights added by the built in platforms and this lack of a single repository for all "things" seem to make it difficult to manage things, especially I imagine for new or less technical users.

There are numerous instances where this causes a lack of clarity and inaccessibility, but perhaps a recent feature that suffers as a result, is the automation wizard with natural language. If you say something like: "turn the porch light on when the sun is set", the next step is "add a light entity". Unless your light came from an integration, you won't see anything and won't be able to select it.

As the purpose of this feature was to make things easier for less advanced users, it becomes confusing when they can see their lights in home assistant, but can't select it when they use the automation wizard.

There are obviously many more instances where this same problem occurs in home assistant as I'm sure you will know.

**Describe the solution you'd like**
Any "thing" be it a sensor, light, switch, media player, device, etc should go in to a single source of truth and call it what you will "entities", "devices", "integration", "things", etc. This should then allow people to easily see and manage (using the new tables with search) all of their devices, regardless of how they arrived in home assistant.

This single source of "things" can then be used for things like automation or even more simply, to check that the new thing you've got has been successfully added to home assistant and make any configuration changes (if available) or even customize e.g. name or show a switch as a light etc.

I could very happily envisage being able to see a "newly discovered devices" section at the top and be able to filter by source (integration/platform/etc). This doesn't seem a far cry from what is available with integrations.

**Describe alternatives you've considered**
You can search around the system, and look at the states, but it's not particular intuitive and it doesn't solve the issue present with the automation wizard, nor does it help improve usability.

**Comment by bramkragten** [comment]
For 1.0, in simple mode, Home Assistant will only support integrations that can be set up with a config flow and deliver devices so it can be used in device automations. To use other integrations, that need to be set up with YAML requires advanced mode. We introduced devices so we can group entities and make it clearer for the user where things come from, it will just take some time for every integration to adopt these new concepts.
