### ISSUE TITLE
Broken text config editing/selecting/copy & pasting on Safari iOS/iPadOS.

### ISSUE THREAD

**Issue by aptonline** [home-assistant/frontend#4482]
**Checklist:**

- [*] I updated to the latest version available
- [*] I cleared the cache of my browser

**Home Assistant release with the issue:**

Home Assistant 0.103.6

**Last working Home Assistant release (if known):**

All versions from my understanding

**UI (States or Lovelace UI?):**

Lovelace

**Browser and Operating System:**

Safari iOS/iPadOS 13.3 but potentially all previous versions too.

**Description of problem:**

Unable to easily select text within the card configuration code edit view (also raw config view) but when you do manage to select anything and you copy and paste it does not paste what was copied but a subset of that (first character for example)

**Expected behaviour:**

To be easily able to select, copy and paste code in the above editors.

**Relevant config:**

N/A

**Steps to reproduce this problem:**

See the below example gif:

![95507D89-D806-41C2-8F99-17395F9C0EFD](https://user-images.githubusercontent.com/190136/72426684-21c42400-3782-11ea-919e-497f8c0199b3.gif)

**Javascript errors shown in the web inspector (if applicable):**

N/A

**Additional information:**

**Comment by bramkragten** [comment]
This is an upstream problem of CodeMirror, we should either wait for the release of CodeMirror 6 https://codemirror.net/6/ or move to regular text boxes for mobile.

**Comment by aptonline** [comment]
> This is an upstream problem of CodeMirror

Out of interest is HA using the latest version of CodeMirror? How can I check?

**Comment by iantrich** [comment]
https://github.com/home-assistant/home-assistant-polymer/blob/dev/package.json#L78

**Comment by aptonline** [comment]
Thanks @iantrich , a few versions behind then. What’s the process for getting the updated version included?

**Comment by bramkragten** [comment]
There don't seem to be changes that are relevant to us or that will solve this, but a PR with an update is welcome.

**Comment by aptonline** [comment]
Considering we have no ETA for Codemirror 6 would it be worth looking into an alternative editor? I (and I’m sure others) do a great deal of my editing of Home Assistant on iOS/iPadOS and the current editor across the entirety of Home Assistant on these platforms is unusable.

https://js.libhunt.com/codemirror-alternatives

**Comment by hagenuck1** [comment]
Unfortunately still not fixed in 0.108.8.

**Comment by pipip** [comment]
still occuring. is there really no easy way to use a different editor (maybe even as addon or option)
Links to codemirror issues:
- https://github.com/codemirror/CodeMirror/issues/3545 
- https://github.com/codemirror/CodeMirror/issues/6349

Seems this will takes ages :(

**Comment by blizzrdof77** [comment]
Yeah, This is so incredibly frustrating for me personally (and a developer's nightmare 😱). Can we just use a textarea for mobile devices? I figured there had to be some kind of work around for this, ￼and I guess I'm just surprised more users aren't ￼complaining.

**Comment by theetron** [comment]
I complain! 
On iPhone it is not working the way it should be. Even placing the cursor somewhere and start typing from there isn’t working. The cursor jumps to the top. Aarrgghhh.

**Comment by spacegaier** [comment]
> 
> 
> I complain!
> On iPhone it is not working the way it should be. Even placing the cursor somewhere and start typing from there isn’t working. The cursor jumps to the top. Aarrgghhh.

Are you running the latest HA version 2021.5?

**Comment by theetron** [comment]
Running the latest 2021.4 at the moment. I normally wait for the 2021.x.1 
Is it fixed in 2021.5?

**Comment by WhatMeansGithub** [comment]
Still. It fixed. Running latest core version. How can something like this persist without anyone making any noise about it? I can’t find much on this topic but it’s really annoying to say the least.

**Comment by bramkragten** [comment]
This issue is fixed, so it was closed. If you believe you found an issue, please open a new issue.
