### ISSUE TITLE
Sort the Refresh Tokens card on profile page by Last used rather than creation date

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#4484]
On the user Profile page in Refresh Tokens card, tokens are currently sorted by creation date rather than last used date (screenshot below). I think that most users would prefer it be the other way around: sorted by Last used.

You want an easy way to see the current login sessions at the top, and you want an easy way to delete the older inactive login sessions. The current sort makes both of these tasks more difficult than they should be.

![refresh-tokens](https://i.imgur.com/1D1LbAi.png)

**Comment by aav7fl** [comment]
I'm going to look into this today to see if I can figure out how to do it in the frontend.
