### ISSUE TITLE
Media player UI card/dialogs do not honor STOP capabilities

### ISSUE THREAD

**Issue by frenck** [home-assistant/frontend#4489]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**

Currently working on Home Assistant 0.105dev

**Last working Home Assistant release (if known):** b/a

**UI (States or Lovelace UI?):** Lovelace

Frontend version: 20200108.0 - latest

**Browser and Operating System:**

Not related to the browser or operating system.

**Description of problem:**

TL;DR: The UI does not seem to honor the supported features of a media player.

I've been reworking the Spotify integration in:
<https://github.com/home-assistant/home-assistant/pull/30717>

Spotify has a free account tier, which is allowed to play music, however, the API doesn't have any controls.

Right now, the Spotify integration breaks on a free account, so I was addressing this issue in the rewrite.

What I do right now, if a user is a free account type of Spotify user, I'll set the supported_features for the media player to `0`.

This causes a "STOP" media button to still show up in the Lovelace card:

![image](https://user-images.githubusercontent.com/195327/72532581-fe79a180-3873-11ea-96cb-2cad80774b60.png)

And a small stop button in the more info dialog:

![image](https://user-images.githubusercontent.com/195327/72532644-10f3db00-3874-11ea-9833-9b5f3c718217.png)

**Please note** This only seems to apply to the stop button. As the media has stopped playing, the stop button disappears:

![image](https://user-images.githubusercontent.com/195327/72532865-6cbe6400-3874-11ea-9c17-bdef5759630e.png)

(also gone on the more info dialog).

**Expected behaviour:**

Not to have a stop button when the media player does not have stopping capabilities exposed.

**Steps to reproduce this problem:**

Set any media player to return `0` as the supported features.

**Javascript errors shown in the web inspector (if applicable):** n/a

**Additional information:**

Nope.

**Comment by zsarnett** [comment]
#4850  Should fix this in the Lovelace Card
