### ISSUE TITLE
Media information on media player card incomplete/inconsistent

### ISSUE THREAD

**Issue by frenck** [home-assistant/frontend#4503]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:** 0.105dev
**Last working Home Assistant release (if known):** ?
**UI (States or Lovelace UI?):** 20200108.0
**Browser and Operating System:** Not relevant

**Description of problem:**

Screen recording:

![2020-01-17 09 46 22](https://user-images.githubusercontent.com/195327/72597569-5238c900-390e-11ea-9470-df542de2476c.gif)

The first view seconds of the clip, there is music playing, which just a Spotify track, with an artist, track name, album name, playlist name that is playing, current media position and the `media_content_type` set to playlist.

As soon as I switch to playing an album, instead of a playlist, it changes. In this case, artist, track name, album name, current media position is provided and the `media_content_tupe` is set to music. (Playlist name is None/empty at this point).

Interesting is the behavior of the media information on the card. Even though, I was playing a playlist in the first few seconds, it shows the track title, not the provided playlist name property?

**Expected behaviour:**

The naming and display of things if weird. There are 4 properties that are interesting:

- Track title
- Artist name
- Album title
- Playlist title (in case of `media_content_type` = `playlist`)

All 4 of those properties aren't guaranteed to be provided, but if they are, it would be nice to display those. In general track, title & artist name would be something to display at any time.

The album title OR playlist name could be picked based on the `media_content_type` and/or whatever is provided/available.

**Additional information:**

Discovered while rewriting our Spotify integration: 

<https://github.com/home-assistant/home-assistant/pull/30717>

**Comment by zsarnett** [comment]
@frenck is this still an issue with the new Media Card in .106
