### ISSUE TITLE
Add "show info" and toggle for script configuration UI

### ISSUE THREAD

**Issue by oncleben31** [home-assistant/frontend#4525]
**Is your feature request related to a problem? Please describe.**
As the configuration UI is progressing. "Script" configuration is not at same maturity level than other. For example compared to "Automation" configuration UI, we can't access the script info panel and we don't have the information on/off for scripts with "wait_template" instructions. 

**Describe the solution you'd like**
Can you implement same features as in "Automation" configuration UI

**Describe alternatives you've considered**
I can do it in Lovelace.

**Additional context**

**Comment by zsarnett** [comment]
This is fixed in 0.116
