### ISSUE TITLE
Add quick search bar to quickly jump to an entity, device, area, integration, automation etc

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#4549]
Also add support for commands like reload yaml, navigate to pages, allow custom LL to add commands, integrations can register commands (ZHA pair)

Needs hotkey

**Comment by donkawechico** [comment]
Put up a PR for this: https://github.com/home-assistant/frontend/pull/7230. 

Still very much a draft, and needs cleanup. But it looks and feels great so far!

**Comment by basnijholt** [comment]
This issue is only partially solved.
> Also add support for commands like reload yaml, navigate to pages, allow custom LL to add commands, integrations can register commands (ZHA pair)

- [x] reload yaml
- [ ] navigate to pages
- [ ] allow custom LL to add commands

Maybe it should be reopened?
