### ISSUE TITLE
Expose function for loading builtin elements

### ISSUE THREAD

**Issue by Alxandr** [home-assistant/frontend#4564]
## The request

I'm trying to create a custom element for use in my home-assistant instance. However, while I'm so doing, I figured I might as well make it look and play nice, and maybe put it on HACS so that other people can use it if they want to. As part of that, I'm trying to create an editor component that uses the builtin `ha-entity-picker`. This works great *if* the `ha-entity-picker` has been loaded, but falls completely flat if not, and as far as I can find, there is no way for me to trigger the loading of the `ha-entity-picker` from code.

Without the component loaded:
![image](https://user-images.githubusercontent.com/112334/72936559-b8d34200-3d67-11ea-9e93-bf715d1957c5.png)

With the component loaded:
![image](https://user-images.githubusercontent.com/112334/72936593-ca1c4e80-3d67-11ea-9329-e6448e49afad.png)

To solve this, I suggest providing a function in the global scope, something along the lines of `ensureLovelaceComponentLoaded('ha-entity-picker')`. This function would look something like this:

```ts
window.ensureLovelaceComponentLoaded = (name: string): Promise<void> {
  switch (name) {
    case 'ha-entity-picker': return import('......');
    default: return Promise.reject(new Error(`No component found with the name '${name}'.`));
  }
}
```

The list also doesn't have to be exhaustive, but can be added to over time, though what's supported should maybe be documented somewhere.

## The alternatives

I've tried to work around this by grabbing the asset manifest (`frontend_latest/manifest.json`) and then injecting script nodes with `src` set to something like `/frontend_latest/chunk.492e1be2a0370f1dd964.js`. However, that doesn't work for chunks, since they do not carry the webpack runtime. The other alternative is recreating the elements in my project, but I imagine that everyone is served with the config elements being re-usable in custom elements, and having one copy of the config elements per project seems like a major waste. Beyond that, I don't know any better way to achieve this.

## Additional information

No additional information.

**Comment by Alxandr** [comment]
I managed to find a workaround that is usable. Calling `document.createElement('hui-media-control-card').constructor.getConfigElement()` loads everything required to edit a media control card. This is very internal API usage though, so I would prefer to be able to do this in a more straight forward manner.

**Comment by zsarnett** [comment]
Currently, this cant be done because you cant register two elements into the CUstom Element registry. Closing this in favor of https://github.com/home-assistant/frontend/issues/7098
