### ISSUE TITLE
Change "Name Override" to "Friendly Name Override" for clarity

### ISSUE THREAD

**Issue by RichardUUU** [home-assistant/frontend#4610]
## The request

In Developer Tools / States / More Info (for any entity) / gear icon / a modal pops up 
The first field suggests "Name Override" It would be more clear if it said "Friendly Name Override" 

The term "Friendly Name" is commonly used. Not using it here is confusing. What name are we overriding? If we don't use the word "Friendly" here, then why do we use it anywhere?

**Comment by SeanPM5** [comment]
How about just "Name" ?

Friendly name made sense when you were writing things out in YAML to differentiate between the entity ID and the more readable name that displays in your UI. But that distinction seems unnecessary here imo.

**Comment by RichardUUU** [comment]
I'm suggesting consistency. Getting rid of "Friendly" everywhere would be fine, but leaving it off here or there creates confusion.
