### ISSUE TITLE
Could not find the original style sheet.

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#4613]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

in inspector, the error in the title is displayed for most of the visited views.

## Expected behavior

not sure, nor do I understand why this is happening
## Steps to reproduce

No steps taken, at least not that I now of. It simply says so in inspector
## Environment

- Home Assistant release with the issue: 104.3
- Last working Home Assistant release (if known): not sure
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Safari, 13.0.4 Mac
- Operating system: Mac OS Catalina 10.15.2

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

<img width="608" alt="Schermafbeelding 2020-01-26 om 22 33 20" src="https://user-images.githubusercontent.com/33354141/73142158-e253dc80-408b-11ea-82ca-c10e4856af23.png">

**Comment by dcarranzafigue00** [comment]
You fix?

**Comment by jaburges** [comment]
confirming the same issue on chrome and edge (chromium)
HA 105.0

**Comment by bramkragten** [comment]
Have you tried this without custom cards?
