### ISSUE TITLE
Hassio - improve error when attempting to access a stopped add-on from sidebar

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#4617]
## The request

It is possible for the user to show a Hassio add-on to their sidebar using Ingress, but forget to toggle on "Start on boot." When you click on sidebar item without the add-on being active, it results in a not so user friendly `502: Bad Gateway` error: 

![502](https://i.imgur.com/Cxw6VBm.png)

Most normal folks will have zero clue what that error means, and because of the placement and tiny size of this error message, it appears like a blank page at first glance.  Furthermore, this error text doesn't use the themes primary text color so it's impossible to read at all on dark themes.

It should display a more informative / user friendly error, something along these lines:

"This page cannot be loaded since AdGuard Home is not currently started. You can avoid this in the future by enabling the "Start on boot" setting for this add-on. Would you like to start AdGuard Home now?" 

Or the first alternative I list below would also work well I think.

## The alternatives

* Hide the sidebar item until the add-on is started. Avoids an error message completely, and if user notices the sidebar item is missing they'll investigate the add-on settings and see it wasn't running. I think I might even prefer this to the above proposal, and I assume this would be the easiest to implement too?
* Disable the "Show in sidebar" toggle until "Start on boot" is enabled first?
* If "Show in sidebar" gets toggled on, also automatically toggle on "Start on boot" ?
* If "Show in sidebar" gets toggled on and "Start on boot" is not on, display some prompt explaining this

**Comment by frenck** [comment]
For the upcoming release, clicking on a add-on in the sidebar that is not started:  notification is shown that is should be started first. (Does not cover all your use cases, but it is something at least 😄 ).

**Comment by bramkragten** [comment]
(upcoming hassio supervisor release that is)
