### ISSUE TITLE
Entity management (single and multi select) does not work

### ISSUE THREAD

**Issue by zen** [home-assistant/frontend#4651]
## Checklist

- [ x] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

Selecting ANY number of entities in Configuration -> Entities is ignored. Cannot disable or delete any entities.

NUmber of selected entities is correctly marked at the select column header, but confirmation modal is displaying 0 entities. This applies to single as well as multiple selected entities.

[https://www.dropbox.com/s/cm31smkr3w701mc/Screenshot%202020-01-29%20at%2023.22.55.png?dl=0](url)

## Expected behavior

I'd like to be able to delete single or multiple entities

## Steps to reproduce

Try to use feature, nothing special

## Environment

- Home Assistant release with the issue:  0.104.3
- Last working Home Assistant release (if known): not known (fresh install on this host
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Version 79.0.3945.130 (Official Build) (64-bit) and Safari Version 13.0.1 (14608.2.11.1.11)
- Operating system: Mac OS X 10.14.6 (18G95)

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt
none
```

## Additional information

Happy to provide more when we have some ideas.

**Comment by bramkragten** [comment]
You can not delete entities that are still provided by the integration, I guess that is your problem.

**Comment by balloob** [comment]
We should improve our messaging.
