### ISSUE TITLE
Automation/Script/Card/View Editors: Share configuration option

### ISSUE THREAD

**Issue by iantrich** [home-assistant/frontend#4675]
## The request

Add a "share" button. MVP would be to put this in the user's clipboard to paste where they want.

## The alternatives

Toggling yaml view in Lovelace
No good alternative in UI for automation/scripts

## Additional information
I don't have a strong opinion on where it should be located. I think while editing would make most sense near the top in the automation/script editor as they are full panels.
For lovelace views/cards, an action in the overflow menu makes sense, I think.

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/issues/4527
