### ISSUE TITLE
Automation/Script Editors: Toggle YAML Editor

### ISSUE THREAD

**Issue by iantrich** [home-assistant/frontend#4676]
## The request

Option to toggle editing via YAML for advanced users.

## The alternatives

Have to use an IDE like the configurator or access the files directly

## Additional information
Make it an option at the top of the panel when editing a script/automation

**Comment by bramkragten** [comment]
it is already in there for each section

**Comment by iantrich** [comment]
Yes, this is for the full automation/script

**Comment by SeanPM5** [comment]
I like this idea, basically a "Raw Config mode" type of thing where you can just see the entire thing in YAML.

This would make it easier to copy and paste things from tutorials/documentation and would make it easier to troubleshoot and ask for help too if you had an easy way of posting your complete automation.

**Comment by bramkragten** [comment]
It was almost done, https://github.com/home-assistant/home-assistant-polymer/pull/3668

**Comment by thomasloven** [comment]
Fixed in #7273
