### ISSUE TITLE
Automation/Script Editors: Ability to duplicate

### ISSUE THREAD

**Issue by iantrich** [home-assistant/frontend#4677]
## The request

Add the ability to duplicate an automation/script from the editor.

## The alternatives

Have to go to your automations/scripts.yaml file and copy/paste and then manually update the id, then reload automations/scripts.

**Comment by Fritz4all** [comment]
Just seen the Duplicate card option in the 0.108 build and would be really great indeed if this could also be impleneted to Automations and Scripts

**Comment by spacegaier** [comment]
There is also now a duplicate function for automations, but not yet for scripts.

**Comment by zsarnett** [comment]
This has been done for Automations and the functionality can be copied
