### ISSUE TITLE
configuration overlays and navigation

### ISSUE THREAD

**Issue by ctalkington** [home-assistant/frontend#4680]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

On android chrome/official app, if you go to "Configuration > People" and click a person to edit, then use the back navigation, the person overlay remains open on top of the "Configuration" panel. I just tried on desktop (firefox) using the "back" button and the same behavior exists. I'm pretty sure this generally effects all overlays but haven't confirmed.

## Expected behavior

overlay should close on navigation back.

## Steps to reproduce

1. "Configuration > People" 
2. click a person to edit
3. use the back navigation (button or backspace)

## Environment

- Home Assistant release with the issue: 0.105.0b0
- Last working Home Assistant release (if known): N/A
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Android (official app 1.5; webview); Windows Firefox 72
- Operating system: 

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by iantrich** [comment]
I cannot replicate this. Are you sure you've cleared your browser cache after upgrading your release?

**Comment by ctalkington** [comment]
@iantrich heres a screen capture from firefox as its easier to show. notice the background changes as im hitting backspace:

![2020-01-30_13-11-03](https://user-images.githubusercontent.com/209757/73481811-313a9400-4362-11ea-9288-04e1ab8f789e.gif)

**Comment by bramkragten** [comment]
Yeah, this is probably true for every dialog except the more info (it has a hack) and entity registry.

**Comment by mikaellindemann** [comment]
The same issue exists for the Notifications overlay.
It's even more a problem on Android as the overlay takes up the entire screen, such that you cannot see that you are navigating below the overlay.
