### ISSUE TITLE
Device Info - Uneditable scripts are not shown in disabled state

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#4687]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

**NOTE**: This is very similar /  related to an issue I reported a few months ago here, https://github.com/home-assistant/home-assistant-polymer/issues/3563 But since this is a new section thought it's worth highlighting again. And I kinda consider this one a bit worse, cause this page is displaying uneditable things in two different ways on the same page as you'll see below...

In this below screenshot all of my scenes are in YAML and all of my scripts are in YAML.

The scenes display in a disabled / grayed out state to indicate they are not editable. However the Scripts do not, you can click on them and then get the annoying `Only scripts inside scripts.yaml are editable.` prompt.

![image](https://i.imgur.com/n4l5ngf.png)

## Expected behavior

Display scripts in a disabled state so users don't try to click on them only to be greeted with a frustrating error.

## Steps to reproduce

1. Have Scripts in YAML
2. Visit a device info page that uses those scripts
3. Click on it, only to be greeted with an error

## Environment

- Home Assistant release with the issue: 0.105.1b
- Last working Home Assistant release (if known): n/a 
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome
- Operating system: macOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Is not possible for scripts right now.

**Comment by iantrich** [comment]
Just needs a backend change still, right?

**Comment by SeanPM5** [comment]
Still an issue in 0.109

No longer seem to get the "Only scripts inside scripts.yaml are editable." prompt though, not sure if that was an intentional change or perhaps a bug?

**Comment by SeanPM5** [comment]
Still an issue but closing this one in favor of https://github.com/home-assistant/frontend/issues/3563 as it's really kind of the same thing.
