### ISSUE TITLE
Allow return key to save on "Add new area" dialog

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#4688]
## The request

Being able to create new areas on the area picker is awesome. The one tiny thing I wish it had support for is being able to simply hit Return/Enter key to save it. 

In this below screenshot, right after I type "Office" i want to be able to hit Return which should be the same as hitting the "Add" button. Since it's not possible to have multiple lines here, seems like there'd be no drawbacks to this, and it would make creating new areas faster and easier.

![image](https://i.imgur.com/pPkwq5j.png)

The dialog for Persons has this. Press the FAB in Persons config and enter a name and hit Return/Enter it will create that person. Just want the same thing here.

**Comment by zsarnett** [comment]
We should just use the prompt dialog for this instead and it would work automatically
