### ISSUE TITLE
Edit Person button on more info dialogs

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#4706]
## The request

Same idea as https://github.com/home-assistant/home-assistant-polymer/issues/4162 which was implemented in 0.105 for automations and scripts. It's very useful and should be expanded to a few other core areas where it makes sense.

![person](https://i.imgur.com/Yted34Z.jpg)

Current flow (which would still be possible):
1. Tap on hamburger menu to show sidebar
2. Tap Configuration
3. Tap Persons
4. Tap Bill Gates

New flow:
1. Tap on the badge or entity for that Person in your frontend
2. Tap pencil icon, get taken directly to that person

Just more efficient and convenient, with less chance of getting lost or distracted from your task.

**Comment by spencerwi** [comment]
Looking into this, I haven't yet figured out if I can navigate to the People page _and_ trigger opening the modal for editing that particular person.
