### ISSUE TITLE
Unresponsive buttons

### ISSUE THREAD

**Issue by masip85** [home-assistant/frontend#4707]
After updating to HA 104.3 , my cover arrows & stop buttons doesn't work as they should. And yes,I deleted cache. I haven't update my browsers by the way. Same versions didn't have the issue before HA upgrade(safari Versión 13.0.4 (15608.4.9.1.3) , Firefox 67.0.4 (64-bit)):

Works in firefox,not in safari
![Captura de pantalla 2020-01-31 a las 22 09 19](https://user-images.githubusercontent.com/12863854/73574663-8e276e80-4476-11ea-9c99-a8424638db59.png)
The sliders works in both browsers.

Doesn't work in firefox. Doesn't work in Safari:
![Captura de pantalla 2020-01-31 a las 22 09 45](https://user-images.githubusercontent.com/12863854/73574788-e199bc80-4476-11ea-9a80-42e0c56aa89a.png)

**Comment by bramkragten** [comment]
We have a bug template for a reason, please fill it out.

**Comment by zsarnett** [comment]
Bug template was never filled out
