### ISSUE TITLE
Adding new zone/person, immediate error message

### ISSUE THREAD

**Issue by tjorim** [home-assistant/frontend#4713]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When creating a new zone or person, HA immediately acts angry.
Before even having the time to fill out required fields, HA throws error messages in my face that some fields are required.
![image](https://user-images.githubusercontent.com/1294876/73582520-df8f2800-448d-11ea-9772-5226be8fa321.png)
![image](https://user-images.githubusercontent.com/1294876/73582524-e3bb4580-448d-11ea-8d9d-6f22e89515de.png)

## Expected behavior

I can simply take my time and fill out the fields, don't validate before I even tried.

## Steps to reproduce

Add a new zone or person.

## Environment

- Home Assistant release with the issue: 0.105.0b1
- Last working Home Assistant release (if known): 0.104.x
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome/HA app
- Operating system: Android

**Comment by ludeeus** [comment]
I personally like this, it makes me aware of the required fields.

**Comment by tjorim** [comment]
I disagree, there are other/better ways to make users aware of required fields.
Here is what the Material documentation suggests about this:
Required text indicator
To indicate that a field is required, display an asterisk (*) next to the label text and mention near the form that asterisks indicate required fields.

If some fields are required, indicate all required ones
If most fields are required, indicate optional fields by displaying the word “optional” in parentheses next to the label text
If required text is colored, that color should also be used for the asterisk

Required text with asterisk
