### ISSUE TITLE
Automations card in generated Lovelace not sorted

### ISSUE THREAD

**Issue by frenck** [home-assistant/frontend#4725]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I just noticed, in Lovelace generated mode, in all cards, entities are sorted by their name, except for the card containing the automations:

![image](https://user-images.githubusercontent.com/195327/73608234-d5217b00-45c0-11ea-8002-4ed877f40dc6.png)

## Expected behavior

My CDO brain wants it sorted 😉 

## Environment

- Home Assistant release with the issue: 0.105b4
- Last working Home Assistant release (if known): Unkown 
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Google Chrome (not really a factor I think)
- Operating system: macOS Mojave

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by danieljkemp** [comment]
Looks like the automations are sorted by ID; which is (nearly) invisible, and un-editable in the UI. Some additional discussion/confusion here: 
https://community.home-assistant.io/t/why-are-my-automations-not-sorted-alpabetically/182554/22

**Comment by fribse** [comment]
This seems to be changed behaviour, I see the problem here as well, and it makes it rather difficult to edit automations when they are not sorted, and searching doesn't work well on the automations page.
