### ISSUE TITLE
Changing page with browser back button does not close dialog

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#4735]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

If a dialog is open, for example the entity registry dialog, pressing the browser back button will change the page but it will keep the dialog open. 

If it's a modal dialog, we should confirm the popstate with the user: "Hey, going to the previous page will cause you to lose all your data, are you sure?". 

## Expected behavior

Dialog to be closed if the page is changed.

## Steps to reproduce

- Open UI on Lovelace
- Click on config -> entities
- Click on an entity
- Press browser back button

## Environment

- Home Assistant release with the issue: 
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): 
- Browser and browser version: 
- Operating system: 

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by balloob** [comment]
Still there.

**Comment by balloob** [comment]
Should be implemented by adjusting the more info dialog logic in [/src/state/url-sync-mixin.ts](https://github.com/home-assistant/frontend/blob/dev/src/state/url-sync-mixin.ts) to be called by every dialog that wants to open/close.

**Comment by bramkragten** [comment]
The base for this has been implemented, now all dialogs need to implement the `closeDialog` function that handle the close action.
