### ISSUE TITLE
Hass.io system tab -> Host system card is too low

### ISSUE THREAD

**Issue by bramkragten** [home-assistant/frontend#4739]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

The blocks are not displayed side by side

![image](https://user-images.githubusercontent.com/5662298/73668402-19d31200-46a6-11ea-99a4-6a5baab1880e.png)

## Expected behavior

That they are side by side:
![image](https://user-images.githubusercontent.com/5662298/73668519-45ee9300-46a6-11ea-84eb-92a6dd90d2f8.png)

## Environment

- Home Assistant release with the issue: 
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): 
- Browser and browser version: 
- Operating system: 

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ludeeus** [comment]
@bramkragten I can't replicate this, do you still have this issue?

**Comment by bramkragten** [comment]
Nope, I think I fixed that a long time ago...
