### ISSUE TITLE
Humidity display on the Thermostat Card

### ISSUE THREAD

**Issue by scarphin** [home-assistant/frontend#4740]
Humidity information is quite common with many different climate devices. I believe adding it to the card would render the card much more useful.

I'll try to create my own card including the humidity information.

A pool of created cards where people can submit may also be useful for everyone if it's not implemented yet.

Thank you...

**Comment by iantrich** [comment]
@scarphin can you provide a mockup of where you would add this functionality on the existing card?

**Comment by scarphin** [comment]
My personal preference would be just over the temperature display and below the temperature adjustment knob printed in smaller digits compared to the temperature digits.

**Comment by cturra** [comment]
i would really like to have the option to display the thermostat humidity reading on thermostat card. here is a mock up of what it could look like (i apologize in advance, i'm not really a graphic designer). note: my view is using the `Google Dark Theme` colours.

a couple tweaks that i made where:

 * lowered the position of: temperature (set point), hvac action and present mode.
 * added the humidity value right under the temperature reading with the `mdi:water-percent` icon.

<img width="388" alt="temperature-card-w-humidity-mock" src="https://user-images.githubusercontent.com/1562351/87858969-bef54600-c8e6-11ea-955d-ffa39c452a1a.png">


please let me know if there's anything more i can do to assist with the development of this feature request. i appreciate everyone who may be involved in helping make this happen 😄

**Comment by cturra** [comment]
> My personal preference would be just over the temperature display and below the temperature adjustment knob printed in smaller digits compared to the temperature digits.

this might be an example of what @scarphin had in mind (again, theme is Google Dark Theme).

<img width="388" alt="temperature-card-w-humidity-top-mock" src="https://user-images.githubusercontent.com/1562351/87859283-d5040600-c8e8-11ea-9eaf-186cacd574c3.png">

**Comment by KTibow** [comment]
Speaking of a list of cards:
https://home-assistant-cards.bessarabov.com/

**Comment by zsarnett** [comment]
I don't think this should be added to this Slider Card. Maybe a redesigned version of the card.

**Comment by bbr111** [comment]
> i would really like to have the option to display the thermostat humidity reading on thermostat card. here is a mock up of what it could look like (i apologize in advance, i'm not really a graphic designer). note: my view is using the `Google Dark Theme` colours.
> 
> a couple tweaks that i made where:
> 
> * lowered the position of: temperature (set point), hvac action and present mode.
> * added the humidity value right under the temperature reading with the `mdi:water-percent` icon.
> 
> <img alt="temperature-card-w-humidity-mock" width="388" src="https://user-images.githubusercontent.com/1562351/87858969-bef54600-c8e6-11ea-955d-ffa39c452a1a.png">
> 
> please let me know if there's anything more i can do to assist with the development of this feature request. i appreciate everyone who may be involved in helping make this happen 😄

Where can i find this card?

**Comment by kghandi** [comment]
I would also vote for adding humidity to the Thermostat card. This information is available from my Ecobee thermostats, and while I can display it separately in an entities card it would make for a much nicer dashboard to display it as shown in the above mock-ups.

**Comment by RyanHope** [comment]
Why was this issue closed? This feature is still need!

**Comment by guystreeter** [comment]
Apparently, somebody who didn't even do any development on this card can decide it shouldn't be changed.
