### ISSUE TITLE
RFC: Use media player entity row instead of media player card in generated UI

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#4746]
## The request

In generated UI, add the media player to the entities card instead of being its own card. That card is too big to be the default.

For example, in my case all Google Homes and Sonos players each have their own media player card. It's kinda wild ! 

I think that we should aim for generated UI to keep all entities in an area together in 1 card.

**Comment by SeanPM5** [comment]
10000% agree. This is the main reason I could never use generated for too long. I have 30 media players and it just dominates the entire view.

**Comment by iantrich** [comment]
Rows FTW

**Comment by SeanPM5** [comment]
Just to give an visual example of why the current behavior should be changed. This was a brand new instance that I only used for 20 minutes a few months ago. Google Cast was set up during onboarding process and then I added just one integration (Plex). The UI was a complete mess before I even had an opportunity to do anything.

![ss](https://i.imgur.com/mpC8vRC.jpg)

If I was a new user, I'd either be rushing to take control well before I was ready and facing a steep learning curve, or deleting both media player integrations just to have a usable UI.

**Comment by balloob** [comment]
Ugh. Plex should default to adding clients of other users to Home Assistant.

**Comment by jjlawren** [comment]
Fine 😉: https://github.com/home-assistant/home-assistant/pull/31738

**Comment by zsarnett** [comment]
@balloob Should we still do this? Media card is sexier and slimmer now 😉
