### ISSUE TITLE
Alphabetically sort entities grouped by their domain in generated UI

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#4747]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

In generated UI, if an entity is not part of a group or area, we will group them by domain. We should sort the entities alphabetically in that card.

## Environment

- Home Assistant release with the issue: 
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): 
- Browser and browser version: 
- Operating system: 

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by OleksandrBerchenko** [comment]
This issue is the only one that prevents me from switching from the Old States UI to Lovelace (I use HA UI only for debugging, adding new devices, verifying updates, etc.).
