### ISSUE TITLE
Better scaling on lovelace cards?

### ISSUE THREAD

**Issue by crobo1337** [home-assistant/frontend#4762]
## The request

When viewing my frontend on a high resolution desktop, the cards dont seem to scale out to fill the screen. 

## The alternatives

*polymer*/src/panels/lovelace/views/hui-view.ts

line 137:
```
.column {
          flex: 1 0 0;
          max-width: 500px; #If i update this to say...800 through my browsers debug menu 
          min-width: 0;         # everything scales out a bit better.
          /* on iOS devices the column can become wider when toggling a switch */
          overflow-x: hidden;
        }
```

But this is obviously only a workable solution for me specifically. Not sure how to write this value appropriately based on each user's rendered resolution.

**Comment by zsarnett** [comment]
I think the best option for this would be updating the panel configuration on a view. This would extend columns out to the max-width of the widow

**Comment by zsarnett** [comment]
Our card are not designed to be larger than 500px. This is something that can now be done using the Custom View feature added in 0.116 if you want this feature
