### ISSUE TITLE
[Supervisor 198] Addon page loading indicator is in the top left corner

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/frontend#4769]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The loading indicator for the addon page is placed in the top left corner:
![Screenshot_2020 02 05_19h47m43s_009_](https://user-images.githubusercontent.com/1368405/73872765-9e619400-4850-11ea-8ace-ec5bc4f5f2b5.png)

## Expected behavior

Place the loading indicator in the center of the screen.

## Steps to reproduce

Go to supervisor (Hassio) page, click on any installed addon, have a look at the top left corner

## Environment

- Home Assistant release with the issue: 0.105.0b7 (supervisor 198)
- Last working Home Assistant release (if known): Supervisor 196 (I skip 197, so not sure about this)
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome 80
- Operating system: Windows 10 Pro

## Problem-relevant configuration

```yaml
none
```

## Javascript errors shown in your browser console/inspector

```txt
none
```

**Comment by ludeeus** [comment]
This is center in the current version

**Comment by TheZoker** [comment]
@ludeeus I just retested this again today with version 0.112b1 and it seems to be still in the top left corner:
![Screenshot_2020 06 26_23h12m01s_012_](https://user-images.githubusercontent.com/1368405/85901702-b25b6180-b802-11ea-8423-76efc6fe195f.png)

(I was not able to catch the loading indicator fast enough, but at least I got a little piece of it 😅)

This happens when clicking on any addon from the addon overview page
