### ISSUE TITLE
Distance between addon options is to huge

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/frontend#4771]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The distance between addon settings items is (in my opinion) to huge:
![Screenshot_2020 02 05_20h04m22s_011_](https://user-images.githubusercontent.com/1368405/73873865-bb976200-4852-11ea-98b4-dc384edcde14.png)

It seems, that this PR changed the initial space:
https://github.com/home-assistant/home-assistant-polymer/pull/4633

The new value is 33px margin bottom, which seems like a strange number.

Another issue is, that the badges above are overlayed by the top margin of the first config item, as you can see here and in the above screenshot:
![Screenshot_2020 02 05_20h18m26s_013_](https://user-images.githubusercontent.com/1368405/73875008-c9e67d80-4854-11ea-9d85-ff9bf83ada2e.png)

This issue is called collapsing margin (if two elements have margin that would overlap - one top, one bottom - the bigger margin will be taken and since the bigger margin is now the bottom config item, this margin is winning):
https://css-tricks.com/what-you-should-know-about-collapsing-margins/

This leads to even more inconstancy. 

My suggestion would be, to use the following values:
```css
.security {
    margin-bottom: 30px;
}
.state {
    display: flex;
    margin: 20px 0px;
}
```

This leads to this result:
![Screenshot_2020 02 05_20h12m22s_012_](https://user-images.githubusercontent.com/1368405/73874471-dd451900-4853-11ea-9e85-316b6e8b2272.png)

While I agree, that it's important to have consistent spaces between items on different pages, in this case it just does not look right and feels off. The lovelace entity card (where this spacing was taken from) has icons and can have secondary information, so the "huge" spacing makes sense there, but not for these addon config items (in my opinion).

## Expected behavior

Have less spacing between config items.

## Steps to reproduce

Open an addon page, have a look at the config items.

## Environment

- Home Assistant release with the issue: 0.105.0b7
- Last working Home Assistant release (if known): 0.104.x
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome 80
- Operating system: Windows 10 Pro

## Problem-relevant configuration

```yaml
none
```

## Javascript errors shown in your browser console/inspector

```txt
none
```

**Comment by ludeeus** [comment]
The issue with just making them closer is that the trigger points will overlap, and you risk changing a neighbor option instead.
