### ISSUE TITLE
Cloud/Google Assistant 100 Entity Limitation

### ISSUE THREAD

**Issue by edwork** [home-assistant/frontend#4772]
## The problem
From the `Configuration > HASS Cloud > Google Assistant > Manage Entities` menu you are able to select more than 100 entities to sync to the Assistant service. The assistant seemingly has a limit of 100 devices, but the GUI never stops or warns the user of the limit. I did not see any errors in the log, but I've restarted since reducing the number of sync'd items and I was not in debug logging mode.

## Environment

- Home Assistant release with the issue: 0.104.3
- Last working Home Assistant release (if known): N/A
- Operating environment (Hass.io/Docker/Windows/etc.): Debian/Docker
- Integration causing this issue: Cloud/Google Assistant
- Link to integration documentation on our website: https://www.nabucasa.com/config/google_assistant/

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information
A fix could be a warning to the user at 100 sync'd entities and locking the entity switches from being sync'd past the limit from within the GUI. Also, when doing a configuration check a warning could be thrown at 100 devices listed in YAML.

**Comment by SeanPM5** [comment]
Another suggestion, currently in the top right corner it has text that says "24 selected" , well that could be changed to "24/100 selected" or something similar. 

Would make users aware of the limit well before they reach it, so no surprises.
