### ISSUE TITLE
Arabic translation

### ISSUE THREAD

**Issue by mohamedation** [home-assistant/frontend#4775]
English Name: Arabic
Native Name: العربية

**Comment by bramkragten** [comment]
We already have Arabic:

https://github.com/home-assistant/frontend/blob/dev/src/translations/translationMetadata.json#L5-L8

You can help us translate on Lokalise: https://developers.home-assistant.io/docs/internationalization_translation

**Comment by mohamedation** [comment]
yes I found the lokalise link and already contributed some. sorry for the opened issue.
