### ISSUE TITLE
Click shadow animation persistent 

### ISSUE THREAD

**Issue by Alex9779** [home-assistant/frontend#4788]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The problem is that when I click my button cards there is shadow animation presenting the click action but when the click finished the shadow stays in the card.
Due to some other issues I had with the default button card prior to the latest version related to changing the icon color I used "custom:button-card" from HACS.
Here is a direct comparison of both cards behavior:
![06-02-_2020_08-55-47](https://user-images.githubusercontent.com/6394581/73917319-70676880-48bf-11ea-8863-188ba84fc8eb.gif)
Both cards use the same input boolean entity.
This happens to me for every default button card connected to any entity.

This also affects the shadow when clicking switches in entity rows of an entity card.

## Expected behavior

Shadow disappearing after a click.

## Steps to reproduce

Just place a button card and connect to a switching entity.

## Environment

- Home Assistant release with the issue: 0.105.1
- Last working Home Assistant release (if known): this was there also last releases
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Google Chrome Version 79.0.3945.130, Safari on iOS13, Edge on Windows
- Operating system: Windows and iOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
Issue persists on other elements as well #4913

**Comment by bramkragten** [comment]
All mwc elements do the same, look at `mwc-button` for instance, or `mwc-icon-button` <https://mwc-demos.glitch.me/demos/icon-button.html>

If you want to change it, you would need [:focus-visible](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) but that has almost no support.

One other option is to wrap the content of the button card in a container that has `tabindex="-1"` so if you click that it will not set focus, but if you tab the parent will get focus. Like I did on the icon here:
![button focus](https://user-images.githubusercontent.com/5662298/74774847-c1e6fe80-5294-11ea-975b-e16a6e8ede58.gif)

**Comment by Alex9779** [comment]
sorry guys just my two cents form a users view: no idea what the problem is, a normal ‚light‘ card does not have that problem, the ‚custom:button-card‘ does not have that problem and also reacts much better on pushes on my iPad and iPhone.
The two cards I recorded the video in my first post show that very good to me, I push the lower one which is the custom one and it works no matter how long I push and the animation goes away, I turn it on some times and the upper default card stays off, no idea why, if I push the default card it goes on for a second then off again, also no idea why.

That‘s what I see from a users point of view, other default cards do not have those issues so...

**Comment by mikenabhan** [comment]
@Alex9779 I am going to be doing some work updating documentation for things, what tool are you using to create the recording of this?  Looks like Bram is also using something similar.

**Comment by Alex9779** [comment]
I used Camtasia by TechSmith, there you can export screen recordings as animated GIFs...

**Comment by mikemcduffie** [comment]
Issue still persists on latest as of Sep 6 on Microsoft Edge (Chromium/Mac, latest version) but not on HA Companion App (iOS 13.7, iPhone & iPad). Issue on both light and dark default themes.

**Comment by PrzemekSztandera** [comment]
The issue still persists on latest 07/11/2020 on Firefox.

**Comment by Derecho** [comment]
Issue still present on frontend version 20210127.7 . I notice it on pretty much anything I can click, that the buttons/links stay in their clicked state and don't pop back to their normal state. This is both in Firefox and Chromium.
