### ISSUE TITLE
Person photo zoom on click

### ISSUE THREAD

**Issue by Anonym-tsk** [home-assistant/frontend#4789]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Normal card view
<img width="184" alt="Home Assistant 2020-02-06 12-19-34" src="https://user-images.githubusercontent.com/1973755/73923152-6fdccb00-48db-11ea-8983-d5cb0b9ecd63.png">

Clicked card
<img width="184" alt="Home Assistant 2020-02-06 12-19-55" src="https://user-images.githubusercontent.com/1973755/73923177-79663300-48db-11ea-9916-ca9c1f3f9002.png">

After zoom:
Normal card
<img width="189" alt="Home Assistant 2020-02-06 12-21-36" src="https://user-images.githubusercontent.com/1973755/73923211-871bb880-48db-11ea-805d-6153a3518e8c.png">

Clicked card
<img width="190" alt="Home Assistant 2020-02-06 12-21-49" src="https://user-images.githubusercontent.com/1973755/73923224-8edb5d00-48db-11ea-9e07-0af72b4ba199.png">

## Steps to reproduce

Add person with photo to entities card. Click to him.

## Environment

- Home Assistant release with the issue: 0.105.1
- Last working Home Assistant release (if known): 0.104
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
- Operating system: macOS 10.15.2

## Problem-relevant configuration

```yaml
entities:
  - entity: person.kolia
    secondary_info: last-changed
show_header_toggle: false
title: Family
type: entities

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
What do you mean by `zoom`?

**Comment by Anonym-tsk** [comment]
> What do you mean by `zoom`?

Look at screenshots

**Comment by zsarnett** [comment]
Can not reproduce. OP is not giving any extra information. Closing until more info is given
