### ISSUE TITLE
It is difficult to find the correct scene name for use in scripts

### ISSUE THREAD

**Issue by Rep-Hueman** [home-assistant/frontend#4795]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

It is difficult to find the correct scene name for use in scripts.
It is not shown in de UI for scripts only the friendly name is shown.
in scripts.yaml there is only a nummer!

## Steps to reproduce

In scene ui:                  woonkamer gedimd relax
In scenes.yaml:            id: 1575144560005  name: Woonkamer gedimd relax
fot use in scrips etc:    woonkamer_gedimd ?!

## Environment

- Home Assistant release with the issue: 0.105.1

**Comment by iantrich** [comment]
I'm not sure I follow the exact issue here, but using the script UI, it is very easy to pick a scene to activate.
![image](https://user-images.githubusercontent.com/1287159/78098394-96335a00-73a4-11ea-99f2-7866ed933316.png)
