### ISSUE TITLE
mdi icons not displayed to non-administrator users

### ISSUE THREAD

**Issue by Tiitan** [home-assistant/frontend#4809]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When connected as a user without administrator rights, mdi icons are not displayed

## Expected behavior

same behavior with user and administrator right: icon displayed

## Steps to reproduce

1. with an administrator user in lovelace, edit a light card and change the icon to mdi:desk for example and validate
2. the new icon is displayed
3. reconnect to home assistant with a user without administrator right
4. the light icon is missing

## Environment

- Home Assistant release with the issue: 
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): 
- Browser and browser version: 
- Operating system: 

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Not able to reproduce.

**Comment by Misiu** [comment]
@Tiitan what browser and operating system do you use?
Did you clear the cache?
Any errors in the console?

**Comment by Tiitan** [comment]
I experience this on chrome android and chrome desktop. I did not clear the cache but tested on new devices. there is no error in the home assistant logs
