### ISSUE TITLE
media player card not supporting STOP

### ISSUE THREAD

**Issue by koying** [home-assistant/frontend#4822]
## The request
The media player card does not support STOP if the backend supports PAUSE.
I'm wondering if it's by design or if a PR would be accepted.

**Comment by iantrich** [comment]
what is your proposed change?

**Comment by koying** [comment]
To add a STOP button if STOP is supported ;)

**Comment by iantrich** [comment]
instead of pause...? or an additional button?

**Comment by koying** [comment]
*add*itional
Play/Pause would stay as a toggle

**Comment by iantrich** [comment]
would suggest a mockup first before coding anything

**Comment by koying** [comment]
Something like this

![](https://linx.semperpax.com/selif/88saa7gj.png)

**Comment by iantrich** [comment]
the circle background for the play/pause does not make sense if you're adding that

**Comment by koying** [comment]
That's the builtin play/pause according to my theme :)
What I want to add is the universally recognized symbol for "stop": the square

**Comment by zsarnett** [comment]
According to https://github.com/home-assistant/home-assistant/blob/05ecc5a1355c7af11b5d310470a6171528dc7a2b/homeassistant/components/media_player/const.py

we would need to add `SUPPORT_STOP = 4096` to the polymer media consts to check for support. if this is something we want to implement

**Comment by koying** [comment]
Implementation is not (yet) at hand.
I'm just wondering here why this obvious feature is not implemented, ie if there was an actual decision not to

**Comment by zsarnett** [comment]
This is something we will not add to the card. clicking the more info icon will give you this action
