### ISSUE TITLE
Allow changing icon in entity registry

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#4833]
## The request

With https://github.com/home-assistant/home-assistant/pull/31714 it becomes possible to update the icon in the entity registry. We should add a UI for that.

Note, in the entity registry we also store the original name/icon. We currently don't expose that to the frontend. If it makes the UI easier, we could include that data.

**Comment by bramkragten** [comment]
It would help to have that data to let the user know what the name would be when he would remove the overridden name, use it as a placeholder on the input field.

**Comment by balloob** [comment]
One thing that is a little annoying is that we're going to keep that all in memory for all entries even though we only need it for the settings screen. But let's address that in the future.

**Comment by timmo001** [comment]
Isn't this complete?

**Comment by balloob** [comment]
Yes
