### ISSUE TITLE
Add integration dialog not completely visible depending on the browser window height

### ISSUE THREAD

**Issue by bonanitech** [home-assistant/frontend#4864]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

As can be seen in the screenshots, depending on the height available in the browser window, the add integration dialog is not completely visible.

<img width="1280" alt="Screen Shot 2020-02-13 at 10 55 52 AM" src="https://user-images.githubusercontent.com/29807944/74452832-9658b400-4e4f-11ea-9613-d33f5fb7f9c7.png">

<img width="1440" alt="Screen Shot 2020-02-13 at 10 56 07 AM" src="https://user-images.githubusercontent.com/29807944/74452841-99ec3b00-4e4f-11ea-8f7d-b3bc8e06b18b.png">

<img width="1280" alt="Screen Shot 2020-02-13 at 10 56 13 AM" src="https://user-images.githubusercontent.com/29807944/74452853-9ce72b80-4e4f-11ea-885f-32d22dc93672.png">

## Expected behavior

Add integration dialog to be completely visible.

## Steps to reproduce

Simply resizing the browser window.

## Environment

- Home Assistant release with the issue: 0.105.3
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome 80.0.3987.100 and Safari 13.0.5
- Operating system: macOS Catalina version 10.15.3

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Duplicate of #5659 (other has more info)

**Comment by bonanitech** [comment]
You were faster than me. 🙂

I was just going to comment with "Please don't close, this problem still exists.".
