### ISSUE TITLE
Date Picker Display Issues on Chrome (Windows 10)

### ISSUE THREAD

**Issue by shbatm** [home-assistant/frontend#4866]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Google Chrome (desktop version, most recent, Windows 10) is adding webkit spinner arrow buttons to Date Time inputs causing display issues and cutting off part of the text from the dates on a Datetime entity:

![image](https://user-images.githubusercontent.com/18057952/74473599-7afaa280-4e69-11ea-88f3-0e8658244a0e.png)

## Expected behavior

Readable text in Chrome.

## Steps to reproduce

Add a datetime entity row to a standard lovelace card/theme in Google Chrome on Desktop.

## Environment

- Home Assistant release with the issue: 0.105.3
- Last working Home Assistant release (if known): (n/a, checked the git blame, looks like these lines haven't been changed, so it might be a Google Chrome update that broke it).
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Google Chrome | 80.0.3987.100
- Operating system: Windows 10

## Problem-relevant configuration

```yaml
  - type: entities
    title: Filter Status
    entities:
      - entity: input_datetime.hvac_filter_last_changed
```

## Javascript errors shown in your browser console/inspector

```txt
N/A
```

## Additional information
#3150 Addressed this issue for Firefox.  
Could also be related/resolved if #3920 is progressed.

**Comment by shbatm** [comment]
@thomasloven: looks like this was your card and you fixed a similar issue before (#3150) for Firefox, any thoughts on Chrome?

**Comment by shbatm** [comment]
Still an active issue for me.

**Comment by jncanches** [comment]
Still an issue here too. Why the date picker is not the same as the one in "more info" dialog which pop a great calendar ? I don't understand... It is way better

**Comment by shbatm** [comment]
Still an issue.

**Comment by jncanches** [comment]
Still an issue

**Comment by jaswalters** [comment]
Still an issue on 0.117.5
