### ISSUE TITLE
Shopping List card on demo site shows error, despite working fine

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#4868]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The Shopping List card on the [demo site](https://demo.home-assistant.io/#/lovelace/0) throws an error that the integration isn't set up. This will scare users off from trying it, but in reality it actually works perfectly fine. 

![demo](https://i.imgur.com/O8j9dT2.png)

It was added in this PR: https://github.com/home-assistant/home-assistant-polymer/pull/4523

## Steps to reproduce

1. Open [demo site](https://demo.home-assistant.io/#/lovelace/0)
2. Add a card, select Shopping List Card, look at the error there
3. You can still add/interact with the card perfectly fine, so error shouldn't show?

## Environment

- Home Assistant release with the issue: 0.105.X
- Last working Home Assistant release (if known): n/a
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome
- Operating system: macOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by balloob** [comment]
The error is correct, the fake HA instance just needs to get `shopping_list` added to the fake list of components that are loaded.
