### ISSUE TITLE
Add-on stage support. 

### ISSUE THREAD

**Issue by pvizeli** [home-assistant/frontend#4872]
Addon can have follow stages: stable, experimental, deprecated. It's up to frontend to make a decision what kind of add-on is show to user.

**Comment by frenck** [comment]
The `stage` property of an add-on reveals the current stage an add-on is in.

<https://github.com/home-assistant/supervisor/blob/dev/API.md#restful-for-api-add-ons>

`GET /addons/{addon}/info`

```json
{
  "name": "xy bla",
  "slug": "xdssd_xybla",
  ...
  "stage": "stable|experimental|deprecated",
  ...
}
```

This property allows us to show if the add-on is experimental, stable or deprecated.

Pascal and I have discussed how to show this in the frontend, but we actually have no idea.

I think in general, there are 2 options:

- Hide everything but stable, have an additional checkbox/setting somewhere to reveal them again.
- Mark the add-ons based on the stage in the UI.

**Comment by ludeeus** [comment]
Suggestion for the implementation:
Add it as a badge to the existing know row.
![image](https://user-images.githubusercontent.com/15093472/78700405-946a1900-7905-11ea-9ece-2234ba3c818a.png)
![image](https://user-images.githubusercontent.com/15093472/78700414-96cc7300-7905-11ea-98f5-322fc755256a.png)
![image](https://user-images.githubusercontent.com/15093472/78700417-97fda000-7905-11ea-8d38-2bdad6ae410a.png)


Suggestion for the "more-info" card when you click the badge:
![image](https://user-images.githubusercontent.com/15093472/78700450-a350cb80-7905-11ea-85dc-b553387d29a4.png)

**Comment by pvizeli** [comment]
I like it 👍

**Comment by frenck** [comment]
I like it as well!

However, could we use an MDI icon instead of the text? It is cut off, and unreadable. Maybe something like `mdi:flask` for experimental and... not sure on the others 🤷‍♂

**Comment by ludeeus** [comment]
The issue with using icons, is that you need to really nail it for it to make sense to the user.
At least now, with the cut-off they are more likely to click it to read more (i hope)?
