### ISSUE TITLE
Add-on Docs

### ISSUE THREAD

**Issue by pvizeli** [home-assistant/frontend#4873]
Add support to the new documentation API calls. Show this as a new Tab `Documentation` on the addon page.

**Comment by frenck** [comment]
There is a new endpoint on the Supervisor API that get fetch the add-on documentation:

`GET /addons/{addon}/documentation`

This allows us to separate the README (introduction text) from the more extensive documentation.

It would be great if the add-on details page would show a tab that reveals the documentation.

<https://github.com/home-assistant/supervisor/blob/dev/API.md#restful-for-api-add-ons>
