### ISSUE TITLE
Add-on support for standard/expert mode

### ISSUE THREAD

**Issue by pvizeli** [home-assistant/frontend#4875]
Add support for the new `advanced` (bool) property on the addon info page. Show this addon not with HA simple mode

**Comment by frenck** [comment]
The property is called `advanced` the API end, however, in Home Assistant terms, this should be called "Expert" towards the end user.

The `advanced` property of an add-on reveals if the add-on belongs to Expert users only.

<https://github.com/home-assistant/supervisor/blob/dev/API.md#restful-for-api-add-ons>

`GET /addons/{addon}/info`

```json
{
  "name": "xy bla",
  "slug": "xdssd_xybla",
  ...
  "advanced": "bool",
  ...
}
```

I think it would be great if this was coupled with the Expert mode setting of a user account in Home Assistant.

**Comment by ludeeus** [comment]
Nice!

I assume this will only apply in the store, if the user already have it installed we should continue to show it?

**Comment by frenck** [comment]
Correct, it only applies to the add-on store.
