### ISSUE TITLE
Allow for a less big weather card

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#4891]
## The request

Our default weather card is too big. Huge header, forecasts for the whole week. Air pressure, wind speed. All information available is shown. That's quite the opposite of how our other cards and rows work: we only show the most essential information and rest of the info is in the more info.

We need an alternative. I don't know if we should just gut our card or introduce a new one.

We could add options to the current card, but I think that in the end it will just render completely different DOM in that it might as well be another card.

Or maybe it should be a row?

I really like the [simple-weather-card](https://github.com/kalkih/simple-weather-card)

![image](https://user-images.githubusercontent.com/1444314/74600506-8b687400-5047-11ea-8d72-4d8fd1a13f34.png)

(this is pretty much a row)

**Comment by zsarnett** [comment]
The issue with this kind of view is the information that the HA Weather Component retrieves doesn't include High or Low Temps for the day or precipitation. Which in my opinion are the main points of data I would like to see 

Even Dark Sky has to have an extra sensor to get this data.

 What I think may be best is to move the condition as the secondary information, add the temperature to the first row far right and potentially (and this where it gets CRAAAAZY) add config for a secondary attribute that is set by the user for a data point under the Temperature ex (extrema)

![image](https://user-images.githubusercontent.com/18730868/74612770-6f5fe380-50d6-11ea-916a-b0d7679edfae.png)

**Comment by balloob** [comment]
So we need to add low/high/precipitation to the weather integration I guess…

**Comment by zsarnett** [comment]
I looked into that but with the API we currently use it doesn't return those data points

**Comment by balloob** [comment]
Can we extract it from the forecasts?

**Comment by zsarnett** [comment]
I don't know exactly but they don't give any High or Low temps for any days. I only glanced at the API results but will look further. First glance seems like no...

**Comment by zsarnett** [comment]
Actually looks like the data return is by hour for the day. So in theory we can min max that data and it does seem like precipitation is a part of the api

**Comment by iantrich** [comment]
I like this thought for updating the row, I think lots of people like the forecast in the card.

**Comment by bramkragten** [comment]
Precipitation and low/highs is part of weather platforms, but not all support it.

This is what my weather entity reports in a forecast:
```
datetime: "2020-02-19T00:00:00+01:00"
condition: "rainy"
templow: 4
temperature: 8
precipitation: 5
wind_bearing: 270
wind_speed: 20.4
```

**Comment by zsarnett** [comment]
Right. The first goal would be to get the HA Weather Platform to show the High lows and precipitation. The other platforms could follow.

**Comment by zsarnett** [comment]
I think the goal of the Row should be to show Extrama and precipitation by default but have a primary and secondary attribute option

**Comment by bramkragten** [comment]
No need to edit the backend, it already has the info we need. We just have to check if the entity provides the info and otherwise don't show it.

**Comment by zsarnett** [comment]
The overarching goal of the issue was to provide an alternative to adding the large Weather card to the demo. I get that the card can be made first and then the backend change after. I just need to find a platform that shows all the data points needed. Darksky doesn't show the high and lows unless the sensor is added. 

Will find a platform that works and create a PR. Backend change from someone else can come later 😉

**Comment by zsarnett** [comment]
I just wasn't sure the default of the row should be something that the HA Platform doesn't support

**Comment by bramkragten** [comment]
The HA Platform does support it. <https://developers.home-assistant.io/docs/en/entity_weather.html#forecast> Although precipitation is not in there...  but is in the code <https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/weather/__init__.py#L21>

**Comment by bramkragten** [comment]
Darksky in daily mode provides the info you need, just the hourly mode has no lows.

**Comment by zsarnett** [comment]
I will have to check again. Maybe I was looking at the wrong thing but when I looked at the data I was given from the State Object I didn't see Precipitation or a Temp Low. I also didn't realize that temp was the high for the day and not the temp currently

**Comment by bramkragten** [comment]
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/weather/__init__.py#L21

**Comment by bramkragten** [comment]
https://www.home-assistant.io/integrations/weather.darksky/#mode
