### ISSUE TITLE
Automations no longer sorted alphabetically after renaming

### ISSUE THREAD

**Issue by i00** [home-assistant/frontend#4897]
## The problem

Automations used to be listed alphabetically on the scripts page, now, after renaming a script the order is not changed

## Environment

- Home Assistant release with the issue: 0.105.4
- Last working Home Assistant release (if known): 0.104.3
- Operating environment (Hass.io/Docker/Windows/etc.): Docker
- Integration causing this issue: Scripts
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/script/

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by Misiu** [comment]
Same with 0.106.5

**Comment by i00** [comment]
I actually meant automations 😜

**Comment by Misiu** [comment]
this should be fixed in 0.108. Automations are shown in a grid.
