### ISSUE TITLE
Show restore progress while loading a snapshot

### ISSUE THREAD

**Issue by hagenuck1** [home-assistant/frontend#4905]
## The request

When restoring from a snapshot any kind of progress should be shown. Selecting a snapshot and not being able to see if it is really started brings along some issues.

Edit: Just found out, that a popup is shown, when you the restore is finished and you don't close the window. But it would still be handy if there was a hint in the snapshot mask that a recovery is still running.

## The alternatives

Show the same screen which is shown on onboarding, when flashed a new sd card to show, that the restore is still running.

**Comment by ludeeus** [comment]
@pvizeli Can we get the information from the supervisor that a restore is in progress?

**Comment by ludeeus** [comment]
This needs <https://github.com/home-assistant/supervisor/issues/1946> to be implemented first

**Comment by ludeeus** [comment]
https://github.com/home-assistant/frontend/discussions/9109
