### ISSUE TITLE
Supervisor - update host system card after changing hostname

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#4915]
## The request

When you change the hostname on Supervisor "System" tab, there is no indication that it actually worked until you refresh the page. Screen recording: https://gfycat.com/adeptdazzlingdikkops

After entering the hostname and saving, the new hostname should be reflected immediately in the "Host system" card to let the user know it was successfully changed.

**Comment by Misiu** [comment]
Also, the prompt window should be changed.
Currently, standard browser input shows up.
We have a new, shiny prompt (as shown here: https://github.com/home-assistant/home-assistant-polymer/pull/4114#issuecomment-552903787) so we should use it instead 🙂
