### ISSUE TITLE
RTL Languages

### ISSUE THREAD

**Issue by niraviry** [home-assistant/frontend#4922]
## Checklist

- [ V] I have updated to the latest available Home Assistant version.
- [V ] I have cleared the cache of my browser.
- [ V] I have tried a different browser to see if it is related to my browser.

## Environment

- Home Assistant release with the issue:  0.105.5
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Firefox ver. 73
- Operating system: Linux Mint 19.3

## Problem-relevant configuration

```yaml
Does not matter. Some is YAML and some are pure Lovelace.
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
Please add more information of the issue/bug you are experiencing. Examples, exact places you see the issue

**Comment by niraviry** [comment]
There are many visual issues with this. 
1. The main menu bar is showing on the right hand side so when opening the Lovelace UI editing it is covered.
2. Any live value in a card merge with the units field in the reverse order meaning 1111 Watt will show as Watt 1111. It is all over the place.
![Screenshot at 2020-02-25 18-36-12](https://user-images.githubusercontent.com/7404470/75267198-9b7a1380-57fe-11ea-8fcb-9bcfcf56bb6e.png)
![Screenshot at 2020-02-25 18-36-35](https://user-images.githubusercontent.com/7404470/75267214-a16ff480-57fe-11ea-8cd2-fa8d8d0f2e8c.png)

**Comment by bramkragten** [comment]
Please be aware that none of the members of our time currently know an rtl language, so we don't know exactly what the rules are and how it should look.

If you want this fixed you should help us by telling what is wrong and how it should be. Try to be as precise as possible with that.

Thanks.

**Comment by niraviry** [comment]
Hi.

The Hebrew (RTL) is OK but the non Hebrew when present with RTL languages
is not so you do not need this.
The problem is that when you merge fields that are LTR, you do that like it
is RTL or you use RTL even when it's not. Please see the temp units in the
middle of the climate card.

Thanks,

Nir

בתאריך יום ד׳, 26 בפבר׳ 2020, 22:42, מאת Bram Kragten ‏<
notifications@github.com>:

**Comment by niraviry** [comment]
Hi.
Just to clear thing, in the left side of every card there is a white space between the value and the units fields. At this point, the system handles this as RTL and not LTR. It should be handled as RTL if the units field is un RTL languages and LTR if the units are units are non LTR. Furthermore, in climate and generic thermostat, the actual temp is too big (I have no idea if it is related to RTL) and clipped at the top. I will send an image later today.

**Comment by niraviry** [comment]
I know there subject did not have much activity but the bug is still there. It is especially visible in the thermostat integration where the current temp is a mess.

**Comment by niraviry** [comment]
Hi.

In time notification. It seems like the Manual Alarm Panel is all revered
due to the wrong RTL implementation.
The keyboard is reversed along with the badge and name.

Any way of fixing it  as part of the Alarm integration or another tool.

‫בתאריך יום א׳, 4 באוק׳ 2020 ב-8:14 מאת ‪stale[bot]‬‏ <‪
notifications@github.com‬‏>:‬
