### ISSUE TITLE
Button Card visual editor inaccessible by default on 0.106

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#4928]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Default button card config has `state_color: true` listed, which prevents the visual editor for this card from loading by default. It loads into the code editor and with an orange warning message that most people won't understand:

Expected a value of type `undefined` for `state_color` but received `true`.

![button-card](https://i.imgur.com/3YiNJqr.png)

After deleting this line from the code editor, _then_ you can press the show visual editor button.

I think either the visual editor should have a "Show state color?" toggle so it loads into that by default, or remove the `state_color: true` line as it'll then use the default behavior for that card type? I notice Glance card doesn't have that line and it loads the visual editor by default.

## Expected behavior

Show visual editor by default

## Steps to reproduce

1. Enter Configure UI mode > Add Card
2. Select Button card

## Environment

- Home Assistant release with the issue: 0.106
- Last working Home Assistant release (if known): 0.105.X although it didn't support overriding the default `state_color` on Button card
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome
- Operating system: macOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by cezarq** [comment]
Same problem here!
