### ISSUE TITLE
Vizio Integration Cannot be Ignored

### ISSUE THREAD

**Issue by ghds514** [home-assistant/frontend#4930]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
Vizio Smartcast device is automatically detected as an integration and can be dismissed but cannot be ignored. Notification is regenerated on each re-start.

## Expected behavior
Integrations that are automatically detected normally have an ignore link/button.

## Steps to reproduce
Start HA with a Vizio Smartcast device

## Environment
Home Assistant Core on RPi4

- Home Assistant release with the issue: 0.105.4
- Last working Home Assistant release (if known): N/A
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome
- Operating system: Windows 10

## Problem-relevant configuration
Not applicable. Automatically detected integration.

```yaml

```

## Javascript errors shown in your browser console/inspector
Not applicable.

```txt

```

**Comment by bramkragten** [comment]
This has to be added to the Vizio integration, is not a frontend bug.
