### ISSUE TITLE
New Person More Info map (refreshes map and changes zoom)

### ISSUE THREAD

**Issue by stboch** [home-assistant/frontend#4934]
## Checklist

- [ X ] I have updated to the latest available Home Assistant version.
- [ X ] I have cleared the cache of my browser.
- [ X ] I have tried a different browser to see if it is related to my browser.

## The problem

With the new Map In the More Info view for a person, when you zoom out or move within a few seconds the map location is refreshed and the changes to the zoom or map position are reset. 

## Expected behavior

Update person location but do not change the zoom or map position 

## Steps to reproduce

Example:
1. Add person with GPS device tracker
2. Navigate to Developer Tools
3. Navigate to States
4. Filter by Person
5. Click "More info" i
6. Zoom out on map below
7. Wait 5 seconds. 

## Environment

- Home Assistant release with the issue: 106.0b0
- Last working Home Assistant release (if known): Not Applicable (New Feature)
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome 79.0.3945.130 (Official Build) (64-bit)
- Operating system: Windows 10

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by klejejs** [comment]
Also, relating to this, it would be really nice if map automatically fitted the person or the zone person is currently in. For now map is always fully zoomed in.
