### ISSUE TITLE
Move placement of Button card in Card Picker dialog so it's alphabetical

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#4946]
## The request

The "Entity Button" card was renamed to just "Button" however in the card picker screen it's still in the same spot as it was before - sandwiched between two cards starting with letter E.

Since this dialog is organized in alphabetical order, it should be moved between Alarm Panel and Conditional. 

![cardpicker](https://i.imgur.com/xzBW4yD.png)

**Comment by bramkragten** [comment]
You do realize that this is only for English? 😛

**Comment by iantrich** [comment]
There's other languages?
