### ISSUE TITLE
Add user dialog remembers its state

### ISSUE THREAD

**Issue by Misiu** [home-assistant/frontend#4968]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When adding a new user the add user dialog remembers its state, so when you want to add another user, validation state is remembered and the name of the previously added user:

![ha_add_user](https://user-images.githubusercontent.com/1741838/75141513-5f0cc180-56f1-11ea-9bf7-580aeb141caa.gif)

## Expected behavior

The state should be clear when the user is added or/and when the dialog gets closed

## Steps to reproduce

1. Go to configuration -> users
2. Add new user
3. Click on back arrow in header
4. Try to add another user

OR
1. Go to configuration -> users
2. Click on add new user
3. Fill `name` field and close dialog (click outside)
4. Again click on add new user
5. The name is remembered

## Environment

- Home Assistant release with the issue: Home Assistant 0.106.0.dev0
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome 80.0.3987.106
- Operating system: Windows 10

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Fixed in 0.108
