### ISSUE TITLE
Title not optional in persistent notifications

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#4974]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The [Persistent Notification docs](https://www.home-assistant.io/integrations/persistent_notification/) and service data state that a title is optional.

However, if you don't specify a title, Home Assistant frustratingly adds an unwanted generic title for you - `notification`, `notification_2`, `notification_3` and so forth. This is ugly and distracts from your notification `message`.

And this makes the "optional" descriptor somewhat debatable imo. 

I remember bringing this up like over a year ago in Discord and many smart people tried to come up with workarounds (invisible ascii characters etc) and nothing really worked. Seems I forgot to open an issue for it though, which I'm finally doing now.

## Expected behavior

For title to be truly optional. Don't show a title in the persistent notification card if one wasn't specified.

## Steps to reproduce

1. Go to Developer Tools > Service tab
2. Select the `persistent_notification.create` service
3. Press the "Fill Example Data" button underneath
4. Delete the line that has `title: Test notification` (and the `notification_id: 1234` line too)
5. Press "Call service" button a few times
6. Now check your Notifications in sidebar, you'll see they were sent but with an added title.

## Environment

- Home Assistant release with the issue: 0.106.0b2
- Last working Home Assistant release (if known): never?
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome
- Operating system: macOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by iantrich** [comment]
Looks to be that the backend assigns a notification_id so that it is unique and that is being displayed. I don't know if I see value in displaying that or not...? I'll start and PR and get feedback

**Comment by SeanPM5** [comment]
Awesome. IMO that should be a backend thing only, there's no value to displaying that in the frontend. If someone has left off the title, it's because they don't want a title.

Here is a specific example of the use case (using [feedreader integration](https://www.home-assistant.io/integrations/feedreader/)):

![image](https://i.imgur.com/8LIGwKK.png)

I wanted to have the headline clickable like a traditional RSS reader, but Markdown isn't supported in `title`, only `message`. So idea was to place all the template code inside `message` portion - which I did, except it was adding that annoying "notification_2" title which distracted from the RSS headline. 

Closest I could get was adding a single period character, but that kinda annoys me too 😛 

Code for above screenshot:
```
- service: persistent_notification.create
  data_template:
    title: "."
    message: "## ![image](/local/icons/apps_services/rss.png) [{{trigger.event.data.title}}]({{trigger.event.data.link}}) \n\n Published Date: {{ as_timestamp(now()) | timestamp_custom('%b %d @ %I:%M %p', true) }} "
```
