### ISSUE TITLE
Configurable state_color for covers

### ISSUE THREAD

**Issue by TheNr1Guest** [home-assistant/frontend#4986]
## The request

Right now I am using covers and awnings as covers. The default state is closed which causes the UI to color the icons yellow when they are opened with the state_color:true option. In my house this does not work. If an icon turns yellow I see this as an active use of a device. So when the covers are open they are not being used, only when they are closed do I expect the icon to be colored.

Since it has been brought to my attention that covers are also being used for garage doors and in that regard the current implementation makes sense.

To support a wide range of use cases with covers I would like to see an option active_state:close or active_state:open being added to the UI which allows users to get the right behavior for their usage of covers.

Maybe this option could extend to other controls as well giving users more control with their colored icons.

**Comment by zsarnett** [comment]
This is not something that will be added to Core. You can set the "on" color in a theme for all entities. Specifying this for a specific domain is not something that should be added
