### ISSUE TITLE
Show UI editors even when advanced options used

### ISSUE THREAD

**Issue by iantrich** [home-assistant/frontend#4993]
## The request

We have a lot of options for our Lovelace cards that are not currently supported by our UI editors and some advanced options that may never be there. When that is the case, we currently default to the YAML editor and it is not possible to use the UI editor at all.

I propose that we allow the UI editor the still be used, but add a note to the bottom similar to

"not all used config options supported, switch to YAML editor to edit them"

This allows users that chose to add advanced options to still use the UI editor but also makes them aware that there are something in their configuration that cannot be edited from the UI editor. We could list those there as well.

**Comment by balloob** [comment]
Step 1 would be to update the structs to support all the different options.

**Comment by iantrich** [comment]
We would need two structs, right? The supported and the non-supported options?

**Comment by balloob** [comment]
I guess.

**Comment by zsarnett** [comment]
Related: #7093

**Comment by zsarnett** [comment]
This should be done with the linked PR
