### ISSUE TITLE
Entities display with 700 entities is so heavy that IOS Safari browser freezes

### ISSUE THREAD

**Issue by KennethLavrsen** [home-assistant/frontend#4996]
## Checklist

- [ x] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

Just upgraded to 0.106.

When I look at the Configuration -> Entities page in my Home Assistant on an iPad Pro using the Safari browser then the whole browser freezes from the load and I have to kill it.

I have reloaded the page and refreshed cache. It cannot take the load. There is too much code on one page now that the IOS Safari browser crashes.

It is already like this with the History page that has not worked for 6+ months on IOS but I lived with that. But not being able to control my home assistant from iPad when I am on the road it really bad. Things are getting too heavy. And it is at first load. I cannot even put a filter. Before I can do anything the browser is frozen and you have to kill the browser. And it is actually difficult to start it again because it opens the last page. You have to use ninja tricks to force open a different URL and then close the tab. 

It is the same in the IOS app on my iPad which is not strange because on IOS all browser variants use the same Apple browser code. You cannot avoid it.

I have house full of gadgets now. A small house. A total of 700 entities get listed of which many are automations.

Even on a desktop computer you can see that the loading of the entities page takes time

You have to slim down this feature so you do not load everything per default.

## Environment

- Home Assistant release with the issue:  0.106
- Last working Home Assistant release (if known):  0.105
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: IOS 13.13.1
- Operating system: IOS 13.13.1

**Comment by KennethLavrsen** [comment]
A little bit of extra info.
When I look at the Developer tools -> States which lists more or less the same number of rows of entities with dynamic content, the iPad Safari browser has no issue loading the 700+ items. The page loads on the iPad in less than 2 seconds.

It is some active Javascript stuff on the Configuration -> Entities page that kills the Safari browser. Not the number of lines in the table.

**Comment by bramkragten** [comment]
I know what it is probably, will fix it, test it and add some extra optimizations.

**Comment by bramkragten** [comment]
Fixed in 0.107
