### ISSUE TITLE
Add counter to the helper UI

### ISSUE THREAD

**Issue by bramkragten** [home-assistant/frontend#4998]
With https://github.com/home-assistant/home-assistant-polymer/pull/4940 we have a UI to add and manage the `input_*` domains.

The same should be done for the `counter` domain. There is no support on the backend yet, issue to track that: https://github.com/home-assistant/home-assistant/issues/32226

**Comment by Adminiuga** [comment]
Support on backend side once https://github.com/home-assistant/home-assistant/pull/32295 goes through.

**Comment by danimart1991** [comment]
I would like to work on this issue.
