### ISSUE TITLE
New sensor-graph not showing the correct 'details' when edited

### ISSUE THREAD

**Issue by fribse** [home-assistant/frontend#5001]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

When a sensor is shown as a graph, the graph details is always shown as '1' in the UI, no matter what it's set to.

## Expected behavior

The graph details is supposed to reflect the current setting.

## Steps to reproduce

1) Create a sensor card, activate the graph with line, set the graph details to 2, and activate the card.
2) Reopen the card, it shows 1

## Environment

- Home Assistant release with the issue: 0.106
- Last working Home Assistant release (if known): New feature
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Firefox 74.0b8, Chrome 79.0.3945.130
- Operating system: 

## Problem-relevant configuration

```yaml
type: sensor
entity: sensor.refridgerator_power
graph: line
detail: 2
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by iantrich** [comment]
You're referring to the UI editor, correct?

**Comment by fribse** [comment]
Yes, sorry for not clarifying that.
