### ISSUE TITLE
Moon sensor icon in badges

### ISSUE THREAD

**Issue by boced66** [home-assistant/frontend#5009]
## The request

Currently, the badge for the moon sensor displays the text (ex: last quarter)
It would be more interesting to have the icon (like the sun icon for the sun sensor)

## Additional information
![image](https://user-images.githubusercontent.com/16917643/75418252-560b3280-5933-11ea-92cd-df5baf2faa31.png)

**Comment by Mariusthvdb** [comment]
true.
more like this:
<img width="83" alt="Schermafbeelding 2020-02-27 om 07 45 49" src="https://user-images.githubusercontent.com/33354141/75419062-48ef4300-5935-11ea-8ee7-b7021d867aba.png">

for the time being, create this sensor and show it as a badge:

```
      moon_phases:
        friendly_name_template: >
          {% set phase = states('sensor.moon') %}
          {% set english = states('sensor.moon_phases') %}
          {% set mapper = {'new_moon':'Nieuwe Maan',
                          'waxing_crescent':'Jonge Maansikkel',
                          'first_quarter':'Eerste Kwartier',
                          'waxing_gibbous':'Wassende Maan',
                          'full_moon':'Volle Maan',
                          'waning_gibbous':'Afnemende Maan',
                          'last_quarter':'Laatste Kwartier'} %}
          {{mapper[phase] if phase in mapper else 'Asgrouwe Maan' }} ({{english}})

# else for 'waning_crescent': 'Asgrauwe Maan'
#previously in english # {{states('sensor.moon_phases')}}

        value_template: >
          {{states('sensor.moon').capitalize().replace('_',' ')}}
        entity_picture_template: >
          {% set state = states('sensor.moon_phases') %}
          {{ '/local/weather/moonphases/{}.jpg'.format(state).replace(' ','_')|lower }}
```
you can find a few topics on the community for moon_phases, but here are the images: https://community.home-assistant.io/t/moon-platform-with-moon-phases-pictures/86646/5

**Comment by zsarnett** [comment]
We should use a MD Icon instead of an image but this would be very nice
