### ISSUE TITLE
Script coding not allowing "Sequence" in syntax, it seems. 

### ISSUE THREAD

**Issue by MacelinCane** [home-assistant/frontend#5015]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Attempting to create a new script and am getting an error about extra keys following "sequence:".  The error reads "**_Message malformed: extra keys not allowed @ data['sequence'][0]['script']_**"

## Expected behavior

I expected to use the sequence function to create a script that saves.

## Steps to reproduce

1. start a new script via the UI method.
2. paste into the script the yaml from the scripts syntax page here: https://www.home-assistant.io/docs/scripts/
3. try to save. 
I have tried changing indents, moving lines around, etc. The quick checker blue line shows before I try to save, but it won't save. 
If I paste the same exact code into scripts.yaml file, I get a similar error.
![image](https://user-images.githubusercontent.com/57817530/75511709-ff4a3b00-59bc-11ea-81d4-08a9da148650.png)
![image](https://user-images.githubusercontent.com/57817530/75511836-767fcf00-59bd-11ea-84e6-a8b1055b6382.png)
This screenshot is after dding it copy/paste to my scripts.yaml. I've tried it many different ways, basically all the ways I could think of.

## Environment

Home Assistant on Pi4, 
Home Assistant Core 0.106.1
HassOS 3.11 - Production deployment, 
Supervisor version 201
Add-Ons File Editor, Google Drive Backupo, Mosquitto broker, Node-Red, Samba share, Tasmo Admin (off) Terminal and SSH, Grocy.

- Home Assistant release with the issue: 
- Last working Home Assistant release (if known):  unknown
- UI Type (States or Lovelace):  Lovelace
- Browser and browser version:  Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- Operating system:  W10

## Problem-relevant configuration

Straight from the docs page. 

```script:
  example_script:
    sequence:
      # This is written using the Script Syntax
      - service: light.turn_on
        data:
          entity_id: light.ceiling
      - service: notify.notify
        data:
          message: 'Turned on the ceiling light!'

```

## Javascript errors shown in your browser console/inspector

```
VM437:1 POST http://hassio.local:8123/api/config/script/config/1582867207143 400 (Bad Request)
(anonymous) @ VM437:1
r @ fetch-with-auth.ts:20
o @ hass-call-api.ts:67
callApi @ connection-mixin.ts:86
value @ ha-script-editor.ts:265
handleEvent @ parts.ts:505
__boundHandleEvent @ parts.ts:463
new:1 Uncaught (in promise) {error: "Response error: 400", status_code: 400, body: {…}}
```
![image](https://user-images.githubusercontent.com/57817530/75512779-8a790000-59c0-11ea-9685-9a63dd18778c.png)

```mtgm.js:92 [Violation] Added synchronous DOM mutation listener to a 'DOMNodeInserted' event. Consider using MutationObserver to make the page more responsive.
(anonymous) @ mtgm.js:92
5[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
```
![image](https://user-images.githubusercontent.com/57817530/75512745-746b3f80-59c0-11ea-9847-296d7d2cd57c.png)

## Additional information
I hope this was helpful. Sorry if I left anything out or if it was my fault in some way. I searched for help in community and spent a great deal of time trying to make it work before submitting. Thank you for an awesome tool. Hopefully this is a simple patch.

**Comment by gadgetchnnel** [comment]
The fact that it says `Check: script->script->script->example_script` in the config check looks a bit odd, like you have multiple levels of **script:** in your config. How does your **script:** section in your **configuration.yaml** look? If it looks something like this:

```
script: !include scripts.yaml
```
then in your scripts.yaml file you would only need something like this

```
example_script:
  sequence:
    # This is written using the Script Syntax
    - service: light.turn_on
       data:
         entity_id: light.ceiling
    - service: notify.notify
         data:
           message: 'Turned on the ceiling light!'
```
since the opening `script:` comes from the configuration.yaml file.
