### ISSUE TITLE
Add Automation/Script editors doesn't respect the automations config file location.

### ISSUE THREAD

**Issue by niemyjski** [home-assistant/frontend#5018]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I put my `automation.yaml` file in a config directory (`automation: !include config/automation.yaml`) like many others who share their config including some core team members... I noticed that when I created an automation, the automation looked like it was created but the ui wasn't updated and was always blank. I had a big WTH moment wondering what was going on... Upon discussing in discord it looks like it created an automations.yaml file at the root.

The editor should respect the automations file location or error if it's not in the `"correct"` file location, because doing nothing and creating a file to never have it show up is a really bad experience.

The same is true for scripts.

## Expected behavior

As long as I don't have a merged configuration list for automations, it should respect my file location for automations.

## Steps to reproduce

1. Create an automations file in a /config directory.
2. Reference it `automation: !include config/automation.yaml`
3. Restart HA
4. Try adding a new integration.

## Environment

- Home Assistant release with the issue: 
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): 
- Browser and browser version: 
- Operating system: 

106.1 home-assistant

## Problem-relevant configuration

```yaml
automation: !include config/automation.yaml
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by niemyjski** [comment]
I believe in failing fast and warning when an operation won't succeed. I think we should not allow the automations/scripts to be added (and show a message) if everyone agrees the automations file has to be in the root and it's configured otherwise.

**Comment by bramkragten** [comment]
We will move to a different system in the future where the UI editor does not touch yaml like we do for other things already (lovelace, person, zone, inputs)

**Comment by marcelvandongen** [comment]
If you place your automation.yaml in the /config folder, you should use
```
automation: !include automation.yaml
```
The include files are relative to the configuration.yaml.

**Comment by niemyjski** [comment]
@marcelbrueckner this isn't an issue of my automations not being resolved. The issue as described in the initial post is that it doesn't respect my existing automation file location and just creates a new one that will never be picked up.
