### ISSUE TITLE
Entities grid is super slow to load when you have lots of entities.

### ISSUE THREAD

**Issue by niemyjski** [home-assistant/frontend#5019]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I noticed that the entities page takes a very long time to load on chrome or safari using a high end 2018 MacBook. It never used to be like this the last time I was in there (I think 104ish). It completely freezes the page while trying to load `811` entities.

It was so slow that lighthouse failed to profile the page:

![image](https://user-images.githubusercontent.com/1020579/75554708-7d7c0100-5a00-11ea-8020-a78733fc399c.png)

![image](https://user-images.githubusercontent.com/1020579/75554938-ec595a00-5a00-11ea-8f94-0c3ac86095ec.png)

![image](https://user-images.githubusercontent.com/1020579/75555177-5e31a380-5a01-11ea-8544-e72cb2c6d18d.png)

I almost think the problem is due to so many Dom updates that the digest cycle is constantly running instead of building up the component tree and appending to the Dom in one operation. Even doing batch operations is super slow to select the grid checkboxes

## Expected behavior

It should load instantly and not peg the cpu.

## Steps to reproduce

1. Navigate to entities page and notice it taking forever to load when you have many entities.

## Environment

- Home Assistant release with the issue: 
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): 
- Browser and browser version: 
- Operating system: 

106.1 home-assistant

## Problem-relevant configuration

```yaml
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by Mariusthvdb** [comment]
as commented in the linked issue #5020 I can't open it at all, hangs the interface forcing a manual window close and reopen in a new tab.

Same on Chrome btw, so not a Safari isolated issue (MacBookPro 32gb, Hassio 106.6)

**Comment by bramkragten** [comment]
Is fixed in 0.107

**Comment by niemyjski** [comment]
Is there a pr to see what the changes are so I can learn from it?

**Comment by bramkragten** [comment]
Yeah, see https://github.com/home-assistant/frontend/pull/5066
