### ISSUE TITLE
Entities UI selection/remove bugs

### ISSUE THREAD

**Issue by niemyjski** [home-assistant/frontend#5020]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

This is potentially related to #5019. The app is super slow to select and then fails to select all `811` entities. 

![image](https://user-images.githubusercontent.com/1020579/75555344-a94bb680-5a01-11ea-9cb8-637f8e3407a4.png)

So I unselect all, then type in a new filter to limit my results to unavailable entities which is super fast.

![image](https://user-images.githubusercontent.com/1020579/75555417-d0a28380-5a01-11ea-84a1-440b4a645f90.png)

I then click remove selected:

![image](https://user-images.githubusercontent.com/1020579/75555478-e9129e00-5a01-11ea-9e6a-5ae1005afc3b.png)

You can see the grid says 31 selected but the dialog says 0. Sometimes this says different numbers but never the full selection. I can't ever seem to delete all my entities because even If I delete some here, If I reselect these in the grid the second time it always says 0 as the count.

## Expected behavior

Select all should always select all no mater the list size, it should then allow me to delete the selected entities which it doesn't.

## Steps to reproduce

1. Navigate to entities page.
2. Select all entities or filter and select all.
3. Click remove selected and notice that not all of the entities are selected for deletion
4. Try to delete the entities to notice it fails.
5. Repeat steps 3-4 a second time and notice the dialog always says `do you want to remove 0 entities`.

## Environment

- Home Assistant release with the issue: 
- Last working Home Assistant release (if known): 
- UI Type (States or Lovelace): 
- Browser and browser version: 
- Operating system: 

106.1 home-assistant

## Problem-relevant configuration

```yaml
```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

I've noticed this on both Safari and Chrome (latest) on MacOS (latest)

**Comment by bramkragten** [comment]
You can only remove entities that are restored, so not provided. I will try to communicate this more clearly.

**Comment by niemyjski** [comment]
Thanks! Any ideas on why entity selection is so slow as well?

**Comment by Mariusthvdb** [comment]
it is not only slow here, it completely hangs the HA interface, forcing mw to close the browser and reload a new.
developer-tools/state works as before.
HA106.6 now

**Comment by bramkragten** [comment]
Is fixed in 0.107 super fast now ⚡️

**Comment by niemyjski** [comment]
Thank you!
