### ISSUE TITLE
TypeError when calling frontend.set_theme

### ISSUE THREAD

**Issue by stevenjev** [home-assistant/frontend#5021]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Whenever I call the service `frontend.set_theme` I receive the error: 

`https://****/frontend_latest/app.119d932a.js:726:21627 TypeError: t.themes is undefined`

However, the service call still changes the theme successfully. This occurs with all themes. Themes .yaml files are currently stored in a directory called `themes` . This configuration had previously worked without this error appearing. 

## Expected behavior

The themes are being successfully set, even with the error appearing in the logs. It is expected that the themes could be set without this error. No config was changed between updating from HA `0.105.5` . Issue appears in both `0.106.0` and `0.106.1`

## Steps to reproduce

  Call service `frontend.set_theme`

## Environment

- Home Assistant release with the issue: 0.106.1
- Last working Home Assistant release (if known): 0.105.5
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Firefox, Chrome
- Operating system: Windows, Mac

## Problem-relevant configuration

    frontend:
      themes: !include_dir_merge_named themes

## Javascript errors shown in your browser console/inspector

None

**Comment by ronaldheft** [comment]
Seeing this issue as well. Whenever `frontend.set_theme` is called, this error appears in the log.

It appears as well that whatever events are fired on a theme change are not fired. For example, the iOS companion app will change the status bar color when `set_theme` is called, and that event isn't making it to the app. This worked prior to `0.106`.

I suspect it has to do with the administration lockdown in `0.106`: https://github.com/home-assistant/core/pull/31654

**Comment by stevenjev** [comment]
I am no longer seeing this error as of 0.106.3. @ronaldheft can you confirm if this issue is also fixed for you in 0.106.3 and I will close.

**Comment by ronaldheft** [comment]
I am still seeing this in 0.106.3 unfortunately.

**Comment by ronaldheft** [comment]
Still seeing this in `0.107.x`.

**Comment by bramkragten** [comment]
Check your browser console for errors, they should point us to the right source.

**Comment by ronaldheft** [comment]
Did some more testing, @bramkragten, and I discovered this only occurs when I have the iOS companion app open when `frontend.set_theme` is called.

I suspect this is because the `themes_changed` event no longer includes theme data, and the iOS companion app is throwing a frontend error parsing the missing data (see: https://github.com/home-assistant/home-assistant-iOS/issues/557).

Would that make sense that a frontend error in the iOS companion app would show up in the Home Assistant logs?

**Comment by stevenjev** [comment]
Closing as I haven’t seen this error since 0.106.3.
