### ISSUE TITLE
View URLs that start with X number redirect to a view in position X .

### ISSUE THREAD

**Issue by PurelyNicole** [home-assistant/frontend#5023]
## The problem
I created Lovelace view with the URL "3d-printer", as autopopulated when I gave it the title "3D Printer." When I clicked on that view, it took me to the view in the third position in my UI. The only way to remove the view after this point was via Raw config editor.

## Environment

- Home Assistant release with the issue: 0.105.5
- Last working Home Assistant release (if known): unknown
- Operating environment (Hass.io/Docker/Windows/etc.): Hass.io
- Integration causing this issue: n/a
- Link to integration documentation on our website: https://www.home-assistant.io/lovelace/views/

## Problem-relevant `configuration.yaml`

```yaml
  - title: 3D Printer
    path: 3d-printer
    badges: []
    cards: []

```

## Traceback/Error logs

none

**Comment by bramkragten** [comment]
Fixes
