### ISSUE TITLE
Entities still shown on unused entities page while they are used in a custom card

### ISSUE THREAD

**Issue by Giel538** [home-assistant/frontend#5027]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Not sure if the problem is lovelace related since it is in combination with a custom card. But i use the custom card: :state-switch https://github.com/thomasloven/lovelace-state-switch

The entities which i use only in this card are not marked as "used entities" meaning that they are still visible on the unused entities page In my case it are switches and climate related entities,

## Expected behavior

I would expect that all entities which are used in this custom cards are not displayed in the unused entities page at all.

## Steps to reproduce

I added entities (in my case switches and climate) in the custom card as usual. But maybe because this cards is dynamically and the output based on an input.select, home assistant / lovelace is not detecting which entities are used in this custom card.

## Environment

  | x86_64
-- | --
dev | false
docker | true
hassio | false
os_name | Linux
python_version | 3.7.6
timezone | Europe/Amsterdam
version | 0.106.0
virtualenv | false

## Problem-relevant configuration

I have this since i used this custom card started from 0.104 or something.

**Comment by bramkragten** [comment]
We don't know the config format of custom cards, so we can't support them.
