### ISSUE TITLE
'Remove Entity' is unavailable until Home Assistant is restarted.

### ISSUE THREAD

**Issue by tdejneka** [home-assistant/frontend#5028]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

NOTE: It's unclear to me if this issue is caused by a bug with the frontend or backend.

I cannot access `Remove Entity` until Home Assistant is restarted.

Specifically, this is for an MQTT Light added via MQTT Discovery and then deleted via MQTT Discovery. 

## Expected behavior

1. If an empty payload is published to an entity's MQTT discovery topic, Home Assistant will remove the entity from the States and Entities views.
2. The entity remains in the MQTT Integrations view where it is marked as Unavailable.
3. Click the entity to reveal a dialog-box where you can choose to Remove Entity from the registry.

Step 3 cannot be performed; clicking the entity reveals no dialog-box. However, if you _restart_ Home Assistant, the deleted entity is now presented differently and clicking it opens the dialog-box (where you can now Remove Entity).

Here is how the entity is presented when clicking does _not_ show the dialog-box:
![Screenshot from 2020-02-29 11-15-14](https://user-images.githubusercontent.com/44732909/75611432-72040500-5ae8-11ea-8f27-0354d14094d8.png)

Here is how the entity is presented, after a restart, when clicking _does_ show the dialog-box:
![Screenshot from 2020-02-29 11-16-31](https://user-images.githubusercontent.com/44732909/75611449-a2e43a00-5ae8-11ea-879e-b4ae7d7ec881.png)

Here's the dialog-box offering the ability to Remove Entity:
![Screenshot from 2020-02-29 11-16-48](https://user-images.githubusercontent.com/44732909/75611466-c3ac8f80-5ae8-11ea-9776-717c8afac181.png)

## Steps to reproduce

Here are two scripts. The first adds a light entity via MQTT Discovery. The second one deletes the entity via MQTT Discovery.
```
#script:
  example_create:
    alias: 'Create Example MQTT Light'
    sequence:
      service: mqtt.publish
      data:
        topic: 'homeassistant/light/example/config'
        retain: true
        payload: >
          {
            "name": "Example",
            "unique_id": "ABC123",
            "stat_t": "home/example",
            "cmd_t": "home/example/set",
            "bri_stat_t": "home/example/brightness",
            "bri_cmd_t": "home/example/brightness/set",
          }

  example_delete:
    alias: 'Delete Example MQTT Light'
    sequence:
      service: mqtt.publish
      data:
        topic: 'homeassistant/light/example/config'
        retain: true
        payload: ''
```
1. From the Services page, run `script.example_create` and confirm the presence of `light.example` in States, Entities, and MQTT Integration.
2. Take note that the newly created light entity appears as an icon under the word MQTT on the Integrations page.
![Screenshot from 2020-02-29 11-17-12](https://user-images.githubusercontent.com/44732909/75611813-d5dbfd00-5aeb-11ea-9e38-52e8d3d26840.png)

3. From the Services page, run `script.example_delete` and confirm the absence of `light.example` in States and Entities views.
4. Take note that the deleted entity is no longer displayed as an icon under the word MQTT on the Integrations page (NOTE: I have MQTT entities defined via both `configuration.yaml` and MQTT Discovery so that's why the screenshot shows `MQTT: configuration.yaml`).
![Screenshot from 2020-02-29 11-18-08](https://user-images.githubusercontent.com/44732909/75611821-f6a45280-5aeb-11ea-81a8-67c5091da182.png)

5. Open the MQTT Integrations page and `light.example` will be listed as `(entity unavailable)`. Click it and it fails to open a dialog-box.

6. Restart Home Assistant.
7. Take note that the deleted entity is now displayed as an icon under the word MQTT on the Integrations page.
8.  Open the MQTT Integrations page and `light.example` no longer indicates it is unavailable. Click it and it will the dialog-box.
9. Click Remove Entity. The entity is now removed from the view (and from the entity registry).

## Environment

- Home Assistant release with the issue: 0.106.2 (and 105.1)
- Last working Home Assistant release (if known): unknown
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Firefox 73.0
- Operating system: Ubuntu 18.04.4 LTS

## Problem-relevant configuration

See scripts posted in the previous section.

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Yes, correct. On startup Home Assistant knows that the entity is no longer provided. MQTT should remove the entity.

**Comment by tdejneka** [comment]
You've closed this issue because it is not due to a bug with the frontend  but due to the MQTT Discovery process failing to remove the entity from the entity_registry. 

Have I understood your reply correctly? If so, I assume the next step is to re-post this Issue in the Core repo?

**Comment by bramkragten** [comment]
Correct :-)
