### ISSUE TITLE
Media Player Card Flashing During Media Position Update

### ISSUE THREAD

**Issue by bertbert72** [home-assistant/frontend#5032]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When the media position updates in my media player card, a flash happens on the picture.  This started happening in 0.106.0 and still happens in 0.106.2.  It didn't happen in 0.105.5.  The difference seems to be that in previous versions, the progress bar wasn't being shown (possibly a bug?) but since it has been enabled, this problem is happening.

This is causing problems in a custom component I've created.  While I can disable the progress bar, it would be nice to have it.  Perhaps I'm doing this wrong, so any suggestions gratefully received.

If I disable the progress bar, the problem stops.

Version 0.105.0

https://github.com/bertbert72/TestComponent/blob/master/v105.5%20-%20no%20flash.gif

Version 0.106.2 (at position 11583055118 + 11583055130)

https://github.com/bertbert72/TestComponent/blob/master/v106.2%20-%20flash.gif

## Expected behavior

The progress bar shouldn't cause the screen to flash.

## Steps to reproduce

I've created a minimal example component to show the problem here:

https://github.com/bertbert72/TestComponent

## Environment

- Home Assistant release with the issue: 0.106.0
- Last working Home Assistant release (if known): 0.105.5 
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome 80.0.3987.122 / Edge 44.18362.449.0
- Operating system: Windows 10

## Problem-relevant configuration

```
media_player:
  - platform: testcomponent
    scan_interval: 1
```

## Javascript errors shown in your browser console/inspector

None

**Comment by zsarnett** [comment]
Please let me know if this issue continues once the 0.107 version is released
