### ISSUE TITLE
Lovelace is turning my code upside down

### ISSUE THREAD

**Issue by YRRK** [home-assistant/frontend#5034]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [Firefox] I have tried a different browser to see if it is related to my browser.

## The problem
Lovelace is turning the "official" code order upside down. If I input this according the example:
entities:

```
type: entities
title: Light
  - light.woonkamer
  - light.keuken
```
The next day I want to edit the code he made it into:

```
  - light.keuken
  - light.woonkamer
title: Light
type: entities
```

This is a small example. But it happends with all my code. Complicated verticalhorzontal stuff I buidl is being turned around wich is pretty annoying. So I keep seperate copys of the code on my computer to work around this. Is happends for a long time now, even after many re-installs so I tought it's maybe time to report it.

## Steps to reproduce
Add a card to lovelace using the code layout as shown in de lovelace example pages. Wait until the next day, or do a restart. Then the code is turned around.

## Environment
- Home Assistant release with the issue: As long as I use is. Sinc 0.9x
- Last working Home Assistant release (if known): not
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Firefox 73.0.1 (64-bits)
- Operating system: OSX Mojave

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by DavidFW1960** [comment]
It's not a bug.. it's by design. If you don't like it don't use the raw or GUI editor. Switch to YAML mode.

**Comment by iantrich** [comment]
The "by design" @DavidFW1960 is referring to is the library we use for conversion to JSON to YAML, which does not ensure ordering of maps. But lists should remain ordered.

Can you please use backticks, `, for your configuration so that I can see what you have. Looking above, I think I know what your config looks like, but it also looks to be incomplete; it looks like you're saying it goes from

```yaml
title: Light
type: entities
entities:
  - light.woonkamer
  - light.keuken
```
to
```yaml
entities:
  - light.keuken
  - light.woonkamer
title: Light
type: entities
```
If you're just referring to keys being ordered alphabetically, it is not a bug.

**Comment by YRRK** [comment]
> It's not a bug.. it's by design. If you don't like it don't use the raw or GUI editor. Switch to YAML mode.

I dunno how to switch to YAML, didn't read about that. Just using the standard tools I get reached from Home Assistant and following the documentation.
But thanks for your answer. Now I now this is normal behaviour.

**Comment by YRRK** [comment]
> The "by design" @DavidFW1960 is referring to is the library we use for conversion to JSON to YAML, which does not ensure ordering of maps. But lists should remain ordered.
> 
> Can you please use backticks, `, for your configuration so that I can see what you have. Looking above, I think I know what your config looks like, but it also looks to be incomplete; it looks like you're saying it goes from
> 
> ```yaml
> title: Light
> type: entities
> entities:
>   - light.woonkamer
>   - light.keuken
> ```
> 
> to
> 
> ```yaml
> entities:
>   - light.keuken
>   - light.woonkamer
> title: Light
> type: entities
> ```
> 
> If you're just referring to keys being ordered alphabetically, it is not a bug.

Hey yes, sorry I "fixed" my code in the example. Now you can read it correctly. Ah so the (example) code is being changed in alphabetical order, interesting. I didn't know tought it was a unhandy bug, now I know it's correct. We can close the case :-)
