### ISSUE TITLE
Improvement on more-info behavior on "small-ish" displays

### ISSUE THREAD

**Issue by acateon** [home-assistant/frontend#5035]
## The request

Im using a official raspberry pi display with 800 x 480px resolution and the popup behavior is a bit annoying.

When the height is sub 500px the popup is rendered in full width (not what I want), but as soon as height is increased to 501 its rendered as a centered frame.

Is it possible force center rendering regardless of resolution? Otherwise this would be a much appreciated feature...

Se exempels below:

![74920939-3f158f00-53cd-11ea-8e7e-f10f03cd1dea](https://user-images.githubusercontent.com/14361705/75626332-047ad600-5bc7-11ea-855b-76171196a5d9.png)

![74920945-4341ac80-53cd-11ea-9399-dc1cea37dcdc](https://user-images.githubusercontent.com/14361705/75626333-0b094d80-5bc7-11ea-8601-8d2eec5d8039.png)

**Comment by zsarnett** [comment]
This is done via Media Queries. The dialog takes the whole screen past 500px. This is done for mobile devices. I don't think this is something that should be changed for that reason
