### ISSUE TITLE
Building automations in Firefox slows browser to a crawl

### ISSUE THREAD

**Issue by fribse** [home-assistant/frontend#5048]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [-] I have tried a different browser to see if it is related to my browser.

## The problem

When you start building a more or less complex automation in Lovelace using the Firefox browser, it will slow down to a crawl as soon as you have multiple entities you want to perform actions on.
This does not happen in Chrome.

It might be related to [issue 4918](https://github.com/home-assistant/frontend/issues/4918)

## Expected behavior

It should not make the browser go crazy slow.

## Steps to reproduce

Start a new automation
Select a trigger
Select a condition
Add several service calls with devices like lights, set brightness etc.

After about 3 you will notice a significant slowing, and after 4 or 5 it will slowly die.

## Environment

- Home Assistant release with the issue: 0.106.3
- Last working Home Assistant release (if known): pre 0.100
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Firefox 73.0.1
- Operating system: Windows 10

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt
"This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!"


```

**Comment by bramkragten** [comment]
Is this still an issue? I don't see this with 10 service calls in an automation.
