### ISSUE TITLE
Alarm Card is not displaying the current state.

### ISSUE THREAD

**Issue by owenostrander** [home-assistant/frontend#5057]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Per the documentation, the default value of the name field should be the current state of the alarm entity. It currently is only displaying the default entity name of the alarm.

## Expected behavior

Per the documentation, the default value of the name field should be the current state of the alarm entity. It currently is only displaying the default entity name of the alarm.

## Steps to reproduce

    1. Add a alarm integration
    2. Navigate to Lovelace
    3. Set Alarm

## Environment

- Home Assistant release with the issue: 0.106.4
- Last working Home Assistant release (if known): Unknown
- Browser and browser version: Firefox 73.0.1 (64-bit)
- Operating system: Windows 10 Pro (also replicated issue with Official Android App)

## Problem-relevant configuration

```yaml
type: alarm-panel
states:
  - arm_home
  - arm_away
entity: alarm_control_panel.alarm_system
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
According to the code: https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/cards/hui-alarm-panel-card.ts#L168

This is actually not the case. The code looks for a specified name and then for the Friendly name of the entity and then the state.

I don't think we should show the state of the card there personally. It should be displayed in the icon badge to the right of the header.

**Comment by owenostrander** [comment]
> 
> 
> I don't think we should show the state of the card there personally. It should be displayed in the icon badge to the right of the header.

I think that's a fantastic idea. I am essentially looking for a front-end that is friendly to a non-HA user. I think most people would be looking for something that says "Hey, this is the alarm panel" ("name:"), and it is "Armed/Disarmed", whatever (Icon/Badge). Right now my display says "Alarm System" (friendly name of alarm), but, the badge just says "Away", which ... while I know what that means, isn't descriptive enough to a non-HA user.

**Comment by zsarnett** [comment]
Hmm the issue is even if it worked the way you originally said (State in the Header) it would show as Away I believe. Not Armed.

**Comment by owenostrander** [comment]
> Hmm the issue is even if it worked the way you originally said (State in the Header) it would show as Away I believe. Not Armed.

The animation shown on the documentation page suggests it should say "Armed Away", since the example says "Armed Home". In either case, it seems the documentation is incorrect, because the card doesn't behave as represented.

**Comment by iantrich** [comment]
ALL the images in the docs need a refresh. The docs for this should just be updated.

**Comment by ajschmidt8** [comment]
Does everyone's alarm panel card look like this?

My badge gets cut off and only shows `ARMED` instead of `ARMED HOME` or `ARMED AWAY` etc.

This is from my desktop, but it looks the same on my phone.

![image](https://user-images.githubusercontent.com/7400326/84457700-58b73c80-ac31-11ea-8ad0-9c5ec551cfaf.png)

**Comment by SeLLeRoNe** [comment]
In the past it was showing only "DISARMED,AWAY,NIGHT,HOME", without the "ARMED " part, which makes more sense and makes it more readablae.

I do believe that the way it was showing before was clearer, but maybe having different icons for the badge without the text would work aswell..
