### ISSUE TITLE
Provide Option To Hide Keypad On Alarm Panel Card

### ISSUE THREAD

**Issue by owenostrander** [home-assistant/frontend#5059]
## The request

On a mobile device, clicking the code field brings up the device’s keyboard to enter the code. It would be nice to have the option to hide the key pad if you don't need it, thereby saving space on the front-end display.

**Comment by zsarnett** [comment]
https://github.com/home-assistant/ui-schema/issues/184

The idea of the Card is to interact with the Keypad.
