### ISSUE TITLE
Mobile App Configuration button

### ISSUE THREAD

**Issue by Yevgenium** [home-assistant/frontend#5060]
## The request

At the moment, the Mobile App Сonfiguration button is in the side menu. At the same time, if we add other integrations, for example ZHA, Z-Wave, they appear not in the side menu, but on the Settings page.
Is it possible to move the App Сonfiguration button from the side menu to the Settings page?

<img src="https://user-images.githubusercontent.com/33804747/75853582-a9d8b880-5e18-11ea-8272-12aa1a1da67b.jpg" width="300">

**Comment by sgttrs** [comment]
I also want to add that in the new version of Home Assistant there will be support for several Lovelace panels, so the side menu space will be full.

**Comment by SeanPM5** [comment]
I don't see the benefit of this?

In the sidebar you can access it with one tap, this would require two taps (plus loading an additional page and scrolling to the very bottom of it). That requires more work on the users part and is less discoverable.

Sidebar seems more convenient and practically impossible to miss.

**Comment by sgttrs** [comment]
How often do you open Mobile App settings? The benefit may be that the side panel will free up space for more frequently used things. It’s also strange for me to see two Configuration buttons nearby, they are similar in meaning and this can confuse users.
![photo_2020-03-04](https://user-images.githubusercontent.com/33804747/75857662-c24cd100-5e20-11ea-956c-cb729e852634.jpg)
And why not put all the settings in an orderly place in one place, whether it’s a mobile app’s settings or other settings?

**Comment by zsarnett** [comment]
This is something specific to the applications and something that is added via those repo's
