### ISSUE TITLE
Cosmetics: Add-On Changelogs do not display embeded markup emoji code

### ISSUE THREAD

**Issue by MichelLap** [home-assistant/frontend#5062]
**Home Assistant release with the issue:**

    HA Version 0.106.4

**Operating environment (HassOS/Generic):**

    HassOS version 3.11 on RPi4b

**Supervisor logs:**

    Supervisor version 207

**Description of problem:**

When accessing any Add-On Change Log within HA Supervisor using the "CHANGELOG" link, the HTML page that is rendered in HA does not display the emoji correctly from the Markdown file.  The markup elements are displayed in plain text instead.

Tested both on Safari and Chrome on OSX (and IOS).

![IMG_1297](https://user-images.githubusercontent.com/48298196/75837156-0349d480-5d92-11ea-8834-ea985038e0c5.jpg)

The issue seams to be related to the Marked.js component used in HA-Frontend not displaying the standard Github emoji markup elements, although it should be (just a guess).

**Comment by ludeeus** [comment]
They are rendered correctly, that is just text, not icons.
If you look at the 🔨 (which is an emoticon), you see that it render those just fine.

**Comment by frenck** [comment]
I think this should be closed. Those icons are rendered by GitHub (as for the community add-ons, the changelog is fetched from GitHub before publishing).

I'm going to adjust the community add-ons release script to resolve those icons to Unicode versions before publishing. That will resolve the issue (which is by no means an HA issue).

**Comment by ludeeus** [comment]
I agree 👍
