### ISSUE TITLE
history-graph with regex entities

### ISSUE THREAD

**Issue by chiu0602** [home-assistant/frontend#5077]
## The request
history-graph accepts key `entities_regex` such that all matching entities will be shown on the card
```
type: history-graph
title: 'My Graph'
entities_regex: 'sensor\.outside.*'
```

Then all entities started with "sensor.outside" will be included in the view.

## The alternatives

It will save time to register if there are many items to be monitored.
Also if the entity is named "correctly", it is no need to configure the card anymore.

## Additional information

Nil

**Comment by bramkragten** [comment]
This is not something that will be made in core. It could be done in a custom card.
