### ISSUE TITLE
V/H Stack - no visual editor available

### ISSUE THREAD

**Issue by sekydig** [home-assistant/frontend#5082]
## Checklist

- [ X] I have updated to the latest available Home Assistant version.
- [ X] I have cleared the cache of my browser.
- [ X] I have tried a different browser to see if it is related to my browser.

## The problem

In both Vertical and Horizontal Stack visual editor is grayed out and not accessible:

![image](https://user-images.githubusercontent.com/55030955/76024685-d3cecf80-5f2b-11ea-997f-693702e6d114.png)
## Expected behavior

Visual editor enabled and usable
## Steps to reproduce

1. Home page---Configure UI
2. Add Vertical (or Horizontal) Stack
## Environment

- Home Assistant release with the issue: 0.106.2
- Last working Home Assistant release (if known): don't know
- Browser and browser version: Chrome 80.0.3987.122; Firefox 73.0.1
- Operating system: Linux

arch | armv7l
dev | false
docker | true
hassio | true
python_version | 3.7.6
virtualenv | false
## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
Correct. Versions 0.106 have no editor for stacks. We currently have a merged PR that will be in Beta soon for editors for these cards.
