### ISSUE TITLE
History Graph Card Configuration - Hours to show issue

### ISSUE THREAD

**Issue by pcopa** [home-assistant/frontend#5090]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem
I have two identical cards after each other. The only difference is one should show 50 hours and the other should show 3 hours. When setting them up everything is fine, but after a refresh they both show the same (3 hour) graph.
Have also reset the database without success.

## Expected behavior
Should look like this:
![IMG_20200301_094306](https://user-images.githubusercontent.com/15312957/76093917-c51a0400-5f8f-11ea-9fac-37dc399c4819.jpg)

But looks like this after a refresh!
![IMG_20200301_094326](https://user-images.githubusercontent.com/15312957/76094002-e975e080-5f8f-11ea-9b04-f8ba23fa940d.jpg)

## Steps to reproduce
1. Add one history graph card wit 50 Hours
2. Add one history graph card wit 3 Hours
3. Now close and refresh the page

## Environment

arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
timezone | America/New_York
version | 0.106.5
virtualenv | false

- Home Assistant release with the issue: 0.106.5
- Last working Home Assistant release (if known):
- Browser and browser version: chrome and android
- Operating system: win 10 and android

## Problem-relevant configuration
`entities:
  - entity: sensor.adc14
hours_to_show: 50
refresh_interval: 0
title: 50 H
type: history-graph

entities:
  - entity: sensor.adc14
hours_to_show: 3
refresh_interval: 0
title: 3 H
type: history-graph`

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
This issue has been there for a while but refresh would fix it. Sins last ~3 updates refresh is not fixing the issue.

**Comment by zsarnett** [comment]
#2061 Same issue. Closing
