### ISSUE TITLE
Climate component issue after whole UI updating to Lovelace

### ISSUE THREAD

**Issue by wangyt123ng** [home-assistant/frontend#5092]
## Checklist

- [ yes] I have updated to the latest available Home Assistant version.
- [yes ] I have cleared the cache of my browser.
- [yes ] I have tried a different browser to see if it is related to my browser.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:chrome safari
- Operating system: macos win10

## Problem-relevant configuration

climate:
  - platform: zhong_hong
    host: 192.168.50.98

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by iantrich** [comment]
there's not enough information to go off of here
