### ISSUE TITLE
Component options not fully accessible

### ISSUE THREAD

**Issue by lociii** [home-assistant/frontend#5103]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

If the list of component options is too long, it is cut off instead of showing a scrollbar.
![image](https://user-images.githubusercontent.com/366967/76159750-d72cab80-6123-11ea-9e70-72de9b7e4ae6.png)
There is no way to get to the options following "Room wakeup"

## Expected behavior

Options list is completely accessible.

## Steps to reproduce

Reproduction on stock HA is complicated since this is a custom component in development.
If required, I will provide a custom component for testing purposes.

## Environment

- Home Assistant release with the issue: All
- Last working Home Assistant release (if known): None
- Browser and browser version: Tested on Google Chrome 80.0.3987.132 / Firefox 73.0.1
- Operating system: Windows 10 / Ubuntu 19.10

## Problem-relevant configuration

None

## Javascript errors shown in your browser console/inspector

None

**Comment by bramkragten** [comment]
Wow that are a lot of options, a multi-select would work better probably

**Comment by lociii** [comment]
You're right in this case. However doesn't mean other couldn't run into this issue.
Please close the ticket if you consider it not worth fixing atm.

**Comment by bramkragten** [comment]
That's why it isn't closed. It should be fixed :-)
