### ISSUE TITLE
Theme: "--card-background-color" not respected

### ISSUE THREAD

**Issue by chemelli74** [home-assistant/frontend#5109]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I have found a theme that has a issue with carc background.
I edited and added the corresponding tag but is not honored.

Info taken from F12 screen of browser

## Expected behavior

Tag honored by frontend

## Steps to reproduce

![image](https://user-images.githubusercontent.com/57354320/76204060-f72d9f00-61f7-11ea-8c09-461d80e33ede.png)

![image](https://user-images.githubusercontent.com/57354320/76203979-d7967680-61f7-11ea-9cd3-a0fdde6cc562.png)

## Environment

- Home Assistant release with the issue: 106.2
- Last working Home Assistant release (if known): none
- Browser and browser version: Edge ver 80.0.361.66  (Chromium) and Firefox ver 72.0.2
- Operating system: Windows 10

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Don't use `paper-card-background-color` as base but `card-background-color`. So turn them around (if `paper-card-background-color` is needed at all)

**Comment by chemelli74** [comment]
> Don't use `paper-card-background-color` as base but `card-background-color`. So turn them around (if `paper-card-background-color` is needed at all)

Unfortunately the result doesn't change.
I want to be sure that calling "frontend.reload_themes" and then do CTRL+F5 would be enough after the change or not.

Thank you,

Simone

**Comment by chemelli74** [comment]
I found a working theme and started changing colours from there.
Now I have mine working, but really don't know why.

If someone is interested, I have both files to upload so you can dig more into it.

Simone

**Comment by chemelli74** [comment]
Why closed ?

Simone
