### ISSUE TITLE
Frontend hangs when integration not available

### ISSUE THREAD

**Issue by slankes** [home-assistant/frontend#5111]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I have a unifi controller added in ha using the supplied integration. When the controller is not available and I'm going to 

Configuration >> Integrations >> UniFI Controller: Default and then choose "Edit Default Settings" in the top right, a spinner turns up and the frontend hangs (I've let it run for 10 minutes and cannot find a way around it).

## Expected behavior

A timeout and ideally a way to actually change the configuration to the new ip address.

## Steps to reproduce

1. add a unifi controller
2. navigate to lovelace
3. Click Configuration >> Integrations >> UniFI Controller >> Edit Default Settings

## Environment

- Home Assistant release with the issue: 0.106.5
- Browser and browser version: Firefox and Chrome (latest)
- Operating system: Fedora Linux 31

## Errors shown

The backend shows correctly that it cannot connect.

```txt
2020-03-09 12:49:00 ERROR (MainThread) [homeassistant.components.unifi] Error connecting to the UniFi controller at 192.168.1.9
2020-03-09 12:49:00 WARNING (MainThread) [homeassistant.config_entries] Config entry for unifi not ready yet. Retrying in 80 seconds.
```

```txt

```

**Comment by bramkragten** [comment]
This should be fixed in 0.111
