### ISSUE TITLE
Delay action yaml data not correctly processed by editor

### ISSUE THREAD

**Issue by kevinkk525** [home-assistant/frontend#5123]
## The problem

In order to use a millisecond delay I changed the delay action in the yaml editor to 
```
delay:
  milliseconds: 300
```
This works as intended but as soon as I switch back to the graphical editor or close the automation and open it in the graphical editor again, the action will have changed to:
```
[object Object]
```
If I now try to leave the automation, I get asked if I want to safe the modified automation. 
It is not only a visual bug, because the yaml data gets changed to:
```
delay: '[object Object]'
```

Expected behaviour: Safe the yaml data for delay actions correctly and not modify it on its own.
Actual behaviour: Editor changes the yaml data to [object Object] automatically.

## Environment

- Home Assistant release with the issue: 106.5
- Last working Home Assistant release (if known): 
- Operating environment (Hass.io/Docker/Windows/etc.): Docker
- Integration causing this issue: Automation Editor
- Link to integration documentation on our website: https://www.home-assistant.io/docs/automation/editor/

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by zsarnett** [comment]
#4733
