### ISSUE TITLE
Light Card #Info prevents slider movement when sufficiently small (solution provided)

### ISSUE THREAD

**Issue by jmillnik** [home-assistant/frontend#5125]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
There is nothing here
