### ISSUE TITLE
New Media Player card gradient in Safari

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5138]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The new Media Player card looks INCREDIBLE.... amazing work @zsarnett ! One thing I've noticed so far is the gradient does not render nicely in the Safari browser, both desktop Safari and mobile Safari (iOS 13.3.1).

In Chrome and Firefox it blends seamlessly and matches the color, in Safari it's black and overlaid on the entire album art.

Chrome desktop (nice / expected look)
![chrome-desktop](https://i.imgur.com/qmW3CYQ.png)

Safari desktop (not so nice)
![safari-desktop](https://i.imgur.com/7MsdV80.png)

Safari iOS
![safari-ios](https://i.imgur.com/3iJnWsU.jpg)

## Expected behavior

Same style as Chrome/FF

## Steps to reproduce

Visit [demo site](https://demo.home-assistant.io/#/lovelace/0) Safari on desktop or iOS

## Environment

- Home Assistant release with the issue: 0.107.0b0
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Safari
- Operating system: macOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
This seems to be an issue with how the image is displayed. The image looks dull compared to the Chrome version. The colors on the left are the same.

**Comment by zsarnett** [comment]
Actually its the gradient. Safari has a "bug" / hasn't updated the way they run gradients. So going from the color to transparent doesnt work. The css needs to look like this:

```css
background-image: linear-gradient(to right, rgb(252, 196, 4), rgba(252, 196, 4, 0));
```

I will add a PR tonight to fix
