### ISSUE TITLE
[0.107.0b0] Vertical stacks inside horizontal stack do not work

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/frontend#5140]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I use three vertical stacks inside a horizontal stack to have full control, which card is displayed where. This worked fine in pre 0.107.0b0 (sensible information has been hidden via black boxes):
![Screenshot_2020 03 12_02h46m11s_001_](https://user-images.githubusercontent.com/1368405/76481099-eb68f500-6410-11ea-9ae2-6b69240a6af7.png)

After updating to 0.107.0b0 it looked like this (I removed the sensible elements for demo purpose):
![Screenshot_2020 03 12_03h03m01s_002_](https://user-images.githubusercontent.com/1368405/76480095-0c7c1680-640e-11ea-9e77-37479089e3b1.png)

So I created a new tab and rebuild my layout (three vertical stacks in one horizontal stack), which worked very good. But the issue now is, that the column has a max-width of 500px, so the layout looks like this:
![Screenshot_2020 03 12_03h04m41s_003_](https://user-images.githubusercontent.com/1368405/76480322-a8a61d80-640e-11ea-97c5-9525546ef0cc.png)

When I remove the `max-width: 500px` from the `.column` class, it looks like I want it again:
![Screenshot_2020 03 12_03h05m20s_004_](https://user-images.githubusercontent.com/1368405/76480258-801e2380-640e-11ea-8485-836cb68d7fc8.png)

## Expected behavior

Give the only horizontal card 100% width and don`t force it to have max 500px width.

## Steps to reproduce

Create lovelace with the code provided below

## Environment

- Home Assistant release with the issue: 0.107.0b0
- Last working Home Assistant release (if known): 0.106.x
- Browser and browser version: Edge Chromium 81
- Operating system: Windows 10

## Problem-relevant configuration

Initial lovelace code (used pre 0.107.0b0): https://pastebin.com/cvZK9aRu

Test tab created with 0.107.0b0:  https://pastebin.com/2Uyy5nYx

## Javascript errors shown in your browser console/inspector

```txt
Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":".../static/translations/1/en-dev.json?__WB_REVISION__=981f5df67bc22a4972bf53bbc7d706a9","status":404}]
    at l.o (.../frontend_latest/workbox-v4.1.1/workbox-precaching.prod.js:1:1749)
    at async Promise.all (index 9)
    at async l.install (.../frontend_latest/workbox-v4.1.1/workbox-precaching.prod.js:1:1221)
n @ workbox-core.prod.js:1
o @ workbox-precaching.prod.js:1
```

**Comment by zsarnett** [comment]
#5155

**Comment by TheZoker** [comment]
Worked, thanks!
