### ISSUE TITLE
Helpers - Input Number: Unable to tab/select Display Option

### ISSUE THREAD

**Issue by iantrich** [home-assistant/frontend#5147]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem
The Input Number dialog has a Display Option set of radio buttons, but you cannot tab through them to select an option which is annoying for form entry to have to switch back to mouse

## Expected behavior
Able to hit tab to highlight different options and hit enter to make selection

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
You can switch between the radio inputs with the arrow keys, the radio buttons are a group so it will be 1 element for tab, and to change the selection you should use arrows.

**Comment by iantrich** [comment]
🙈 OMG...
