### ISSUE TITLE
Media Player Card: Unnecessary Marquee when skipping tracks

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5151]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I don't know if this is necessarily a bug, but when you hover over a very long song title and the marquee kicks in, and then you press the skip track button, the next song will always be scrolling initially even if that isn't necessary.

Long title, scrolling marquee:
![image](https://i.imgur.com/DaWf7ks.png)

Skipped track, this is a short song title (3 words) but you can see it was still scrolling at first:
![image](https://i.imgur.com/G2EYT88.png)

This makes it a tiny bit harder to read the song title when skipping tracks if it's scrolling unnecessarily. Not a huge deal, only lasts for like 2 or 3 seconds maybe, but just thought I'd mention it. 

## Steps to reproduce

Can test it by playing this Weird Al album and skipping tracks, since it has some very long song titles followed by short song titles.

https://open.spotify.com/album/7xioktcLt004PnB9nqwBWz?si=83pde1eMQZSDS1N96ccfcA

## Environment

- Home Assistant release with the issue: 0.107.0b0
- Last working Home Assistant release (if known): n/a
- Browser and browser version:
- Operating system:

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by iantrich** [comment]
I would not expect those two songs to be next to each other in a playlist :rofl:

**Comment by SeanPM5** [comment]
Haha yeah, babysitting my nephew so often has really screwed up my "Top Songs" playlists big time 😆

**Comment by iantrich** [comment]
I hear that. I have lots of Disney soundtracks in my recommendations 😂
