### ISSUE TITLE
Media Player Card: Xbox media player not showing artwork

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5153]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I am using Jason Hunters Hassio Xbox One media player add-on. In the old media card it worked, in this new one it does not show the artwork, game title, or controls.

![image](https://i.imgur.com/VHTc0Hb.png)

When I open the more info dialog, you can see there is artwork, title, controls etc, none of which were displayed in the above screenshot:

![image](https://i.imgur.com/nysmkVN.png)

And here it is on the mini media player custom card.

![image](https://i.imgur.com/sVgJFAZ.jpg)

If I had to guess, this is happening because the media player state always gets reported as "**unknown**" for some odd reason. AFAIK that has always been the case with this add-on and despite that weirdness it functions perfectly fine otherwise. Here is some info from the states page.

```
Entity: media_player.xbox_one
State: unknown

source_list: Home, TV, Plex, HBO GO, Netflix, YouTube, Microsoft Edge, Settings, Devil May Cry 5
media_title: Devil May Cry 5
source: Devil May Cry 5
friendly_name: Xbox One
entity_picture: /api/media_player_proxy/media_player.xbox_one?token=44208ce0b49bced6315aa93578ab2061c8b1e9e59c34f2d9af42dfcd88bd6e2e&cache=59856504f6e178e8
supported_features: 18817
```

I also see this in logs - not sure if it's related to this particular issue / media player as I have dozens of media players in my setup so...

```
Logger: homeassistant.components.media_player
Source: components/media_player/__init__.py:904
Integration: Media player (documentation, issues)
First occured: March 11, 2020, 11:23:28 PM (11 occurences)
Last logged: 1:43:40 AM

The websocket command media_player_thumbnail is deprecated. Use /api/media_player_proxy instead.
```

I realize this is probably an edge case, and more of an issue with the add-on itself. It hasn't been updated in ages and isn't actively maintained. So I would understand if this isn't worth looking into.  Just thought I'd report it here anyway on the slim chance this might be a more widespread issue with other media players. Otherwise feel free to close this.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Yes, that is related to the state `unknown` and should be fixed in the xbox integration
