### ISSUE TITLE
Lovelace card editors inconsistent with icon previews in text fields

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5162]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

This is not a big deal or anything, but the Lovelace card editors are a bit inconsistent on how they handle icons. Some cards show the icon preview inside the text field while other cards don't.

Light (yes)

![light](https://i.imgur.com/8DyrM4c.png)

Button (no)

![button](https://i.imgur.com/fZEEOkA.png)

Sensor (no)

![sensor](https://i.imgur.com/3zQ3o0M.png)

I kind of feel this should be consistent across all cards? Either show it in all of them, or show it in none of them. 

And although it's true there's a preview on the right in desktop, on mobile that card preview will not be visible when entering the icon name (due to mobile keyboard taking up half the screen). As you can see in this screenshot: 

![image](https://i.imgur.com/y8UHCCf.jpg)

So the icon preview inside of the text field might be helpful on mobile at the very least? Would allow you to see if the icon is valid/exists without needing to dismiss the keyboard / scroll up and down.

## Expected behavior

Consistent behavior

## Environment

- Home Assistant release with the issue: 0.107.0b0
- Last working Home Assistant release (if known): n/a
- Browser and browser version:
- Operating system:

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Just isn't implemented everywhere yet
