### ISSUE TITLE
Resources: automatically change resource type dropdown depending on file extension

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5164]
## The request

Small UX improvement i thought of, but if you paste a resource with extension ending with .css such as `/local/my-webfont.css`, it would be cool if the "Resource type" dropdown automatically changed to Stylesheet.

This would save two clicks for everyone adding stylesheets, and also make it more fool-proof for users of all skill types.

![image](https://i.imgur.com/Vqx18Ai.png)

**Comment by iantrich** [comment]
to further your point, with only two options now, is there even a point to having a type?

**Comment by bramkragten** [comment]
There could be more extensions, like `mjs`, `scss`, no extension at all, etc.
