### ISSUE TITLE
Use state-icon-color for icon override in more info Settings dialogs

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5166]
## The request

For the icon previews in text field, it displays it in primary text color.

![image](https://i.imgur.com/G4GMXpr.png)

However in the Lovelace frontend it's displayed in color. I believe this is `--state-icon-color` ?

![image](https://i.imgur.com/MShNPM1.png)

I think the Settings dialog should display it the same way it's usually seen in the frontend.

This would also apply to other places it's used, ie the Lovelace card editors https://github.com/home-assistant/frontend/issues/5162

**Comment by zsarnett** [comment]
This is a part of the Input and input text is the font color. I think this should stay how it is in this case.
