### ISSUE TITLE
Zhonghong HVAC component no responding on Lovelace most time

### ISSUE THREAD

**Issue by wangyt123ng** [home-assistant/frontend#5170]
## Checklist

- [ yes] I have updated to the latest available Home Assistant version.
- [yes ] I have cleared the cache of my browser.
- [yes ] I have tried a different browser to see if it is related to my browser.

## The problem

Since HA using Lovelace as frontend, Climate component appears problem which is the component often doesn't get feedback from HVAC stat. But sometime after reboot, it will work for a while. The climate component is <<zhonghong>>. It used work when frontend is not Lovelace, it appears a common problem which I also found in Chinese HA forum.
![75542542-fe67e680-5a5a-11ea-9a0a-7e03ff4e0446](https://user-images.githubusercontent.com/47052753/76136864-44333900-6071-11ea-88d4-bafca2a2ca34.png)

## Expected behavior

It should show current temperature, and current status of HVAC.

## Steps to reproduce

  Provide steps for us, that helps reproducing your issue.
  For example:
    1. Add a climate integration
    2. Navigate to Lovelace
    3. No data shows as the picture
    4. Set the HVAC action to heat
    5. The HVAC will turn to heat however still no status shows on Lovelace climate component

## Environment

Home Assistant 0.106

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:chrome safari
- Operating system: macos win10

## Problem-relevant configuration

climate:
  - platform: zhong_hong
    host: 192.168.50.98

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
I don't think this is a lovelace problem but a problem with the `zhong_hong` integration. What are the state and attributes when it doesn't work?

**Comment by wangyt123ng** [comment]
the strange think is when HA were Not officially using Lovelace as frontend its always works. Now, if i reboot HA several times it sometime will work but not last long

**Comment by bramkragten** [comment]
If you share the state and attributes I can check if it is a problem with Lovelace or the integration. I don't have a `zhong_hong` device so can't check it myself...

**Comment by wangyt123ng** [comment]
![微信图片_20200314004617](https://user-images.githubusercontent.com/47052753/76641905-47588880-658d-11ea-8faa-997c9c21427e.png)
Hi bramkragten
Is that what you mean?
or is there anyway I can dig data deep down, please tell me how to do it.

**Comment by wangyt123ng** [comment]
There weird thing is, I can actually turn it on, but no responding on the interface only seen on the wired control, and can't turn off on Lovelace.

**Comment by wangyt123ng** [comment]
[flows.json.zip](https://github.com/home-assistant/frontend/files/4330678/flows.json.zip)
there is another way make it work which is through Node-red, and it's based on TCP communication and mqtt.
