### ISSUE TITLE
0.107.0b0: Card picker Safari issue

### ISSUE THREAD

**Issue by Quentame** [home-assistant/frontend#5185]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Safari card picker acting weird 

Safari : 
<img width="1014" alt="Capture d’écran 2020-03-13 à 00 24 52" src="https://user-images.githubusercontent.com/14821482/76576028-34788200-64c1-11ea-97cd-e89b6468b7e0.png">

Chrome : 
<img width="1012" alt="Capture d’écran 2020-03-13 à 00 24 33" src="https://user-images.githubusercontent.com/14821482/76576042-3e01ea00-64c1-11ea-8504-02813f7894d2.png">

## Expected behavior

As Chrome

## Steps to reproduce

Try to add a new card with e UI in Safari

## Environment

- Home Assistant release with the issue: 0.107.0b0
- Last working Home Assistant release (if known): 0.106.6
- Browser and browser version: Safari 13, Chrome 80
- Operating system: MacOS 10.15

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
#5139
