### ISSUE TITLE
Media Player card progress bar weirdness

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5186]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I have noticed a little bit of weirdness with the progress bar in the Media Player card.

Here is a song I played, you can see that it's running a little bit faster compared to the actual Spotify progress bar. Not wildly different so far, but if you put the Spotify desktop app over the LL media card and try to line them up I'm sure you can reproduce.

![image](https://i.imgur.com/CqzNAeO.png)

And now here's where the funkiness happens.... 

![image](https://i.imgur.com/BImChZx.png)

Radioheads "Creep" is 3 min 58 seconds in length (I skipped it about ~2:30 in), and Jimi Hendrix "Little Wing" is only 2 min 25 seconds in length. I used a screen recording to capture the exact frames where it transitions from one song to the next, and you can see that it's using the existing progress bar rather than starting over from the 0:00 mark when the song is changed. Seems sorta similar to the marquee bug I reported in https://github.com/home-assistant/frontend/issues/5151 ? 

According to the progress bar here this Jimi Hendrix song is 100% played even though it literally just started.

And another issue with the progress bar... this song I played like 60%, but then scrubbed towards the beginning of the song. You can see in the Spotify app, and in the States panel attributes for `media_position` that it correctly reports 12s. However that change was not reflected in the Lovelace card as you can see.

![image](https://i.imgur.com/SPXtRxd.png)

## Steps to reproduce

1. Launch Spotify
2. Play a song to like 70% completion, note the progress bar length in the LL media card
3. Skip the track
4. Note the progress bar in the LL media card again, it will continue

and

1. Launch Spotify
2. Play a song to like 50% completion or whatever
3. Use the scroll bar to go back to like 10%, see if the progress bar in the card updates (for me it doesn't)

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
I almost think this may be a Spotify integration issue. I am able to reproduce the issue. The issue is that the `media_position_updated_at` after state from pause to play isn't updated. So if you pause wait for 3s then hit play. Our current Algorithm for getting the position bases it off that updated time. So now the player thinks 3s has gone by and that the position is now 3s ahead of the correct position.

@SeanPM5 Are you able to reproduce this with a Cast device (Google Home, Chromecast, other platform)?

**Comment by zsarnett** [comment]
The issue with the seek position after clicking on the card is an easy fix. :) Just need to update progress bar after clicked

**Comment by SeanPM5** [comment]
I think it might be an issue with the Spotify integration too. I know Frenck recently rewrote it in 0.105 so that would make sense. 

I noticed it when playing Spotify on my Mac. I have a whole bunch of different media players I can test it on later (GH, Alexa, Chromecast, Receiver, etc) but won’t be home for a few more hours.

**Comment by SeanPM5** [comment]
Did a bunch of testing and unable to reproduce when using Spotify Connect to Alexa or Google Cast devices. It's just the `media_player.spotify` entity that seems to have this progress bar issue, which I think points to a problem in the Spotify HA integration itself?

In this pic I have the Spotify Mac app, Spotify HA entity in the new core card, same Spotify entity in a mini media player custom card, and then my Echo Dot in Alexa Media Player. (The State attributes on the left side are the `media_player.spotify` entity).

This first pic the `media_position` attribute is at 54.026
![image](https://i.imgur.com/j4C2htK.png)

This next pic is literally half a second after the above one, it jumps from 54.026 all the way to 85.042. 
![image](https://i.imgur.com/ineS83Y.png)

Interesting thing to me is that the `media_position_updated_at` attribute does not seem to update for me at all, except for on track changes? I would think that both `media_position` and `media_position_updated_at` attributes would be updated simultaneously since they are tied together. 

I don't know enough about the technical side of this stuff to write a good bug report on the core repo though... So will tag @frenck and he could move this issue if needed.

**Comment by zsarnett** [comment]
@frenck Would you be able to give any insight here?

**Comment by zsarnett** [comment]
Still an issue

**Comment by mwasowski** [comment]
I confirm, still an issue and it happens on default media player card as well as others.

**Comment by lebowski9000** [comment]
This seems to be an issues on any media player device. The progress bar keeps moving on page refresh. e.g Sonos and Kodi. If I have anything “paused” and flick between tabs. The progress bar keeps creeping forward. If I hit play it resumes at the correct position.

**Comment by Chiggy-Playz** [comment]
This is still an issue :(

I've attached a recording which demonstrates this bug. You can clearly see, that every time spotify is checked, a 30 seconds delay is added to the runtime which isnt needed. 

Even in the beginning, when the song had played for 30 seconds, 1 minute is shown in HA. And then it keeps on increasing in multiple of 30 seconds. 

https://user-images.githubusercontent.com/49774426/163772462-cd812391-47d1-4a53-af14-b48e5eb17b91.mp4
