### ISSUE TITLE
Wider card code editor / Wide mode for card code editor

### ISSUE THREAD

**Issue by noxhirsch** [home-assistant/frontend#5191]
## The request
For custom cards or many nested cards, the code editor of the lovelace card editor is very narrow that you have to scroll vertical to see all the code. This is especially sad if you have a big screen and have the space for a wider editor:
![image](https://user-images.githubusercontent.com/30938717/76608847-aaf39f00-6516-11ea-94e7-0142065663c0.png)

My request would be to make the editor at least double or triple the width if enough space is available.

## The alternatives
An alternative would be a width toggle below the editor where you can change the width of the editor only when needed. Then you could still use the narrow editor for normal stuff and double/triple the size when needed. Or even use the whole width of the monitor minus the width of the card preview.

## Additional information
This would be especially handy for cards like markdown or custom html card:
![image](https://user-images.githubusercontent.com/30938717/76609380-995ec700-6517-11ea-8345-c09be1bc0258.png)

**Comment by zsarnett** [comment]
We do this already on the more info. We should do it similarly
