### ISSUE TITLE
Card picker - sensor card preview cut off

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5196]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Noticed this on both my own setup and reproduced in the [demo](https://demo.home-assistant.io/#/lovelace/0). When adding a card, the Sensor card preview has the text cut off at the top. It's only showing the top half of the sensor name in the preview. See image below, look at the Morning Commute text:

![image](https://i.imgur.com/y47HGuf.png)

Card is fine when clicking through and adding to a view, it's just this preview. Think the height of the card preview in the add card picker is too small or something.

## Steps to reproduce

1. Enter Configure UI Mode
2. Add card picker
3. Look at sensor card preview

## Environment

- Home Assistant release with the issue: 0.107.0b1
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
This will be resolved when we drop Zoom css Property from Chrome. Working on the best solution for this now
