### ISSUE TITLE
Media Player card - inconsistent coloring for same album art

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5202]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

While investigating a different issue, I encountered something else weird...

Had a vertical stack with the `media_player.spotify` entity and `media_player.bedroom_speaker` (a Google Home mini) entity, both playing the same song at the same time. Despite the album art being identical, each card got different coloring. And then I checked on my iPhone 11, which _also_ had different coloring than Chrome Mac?

![image](https://i.imgur.com/uK6qO4F.jpg)

I thought at first this might be random, but it doesn't appear to be. Just different colors depending on entity and device or something? idk.

More examples...

![image](https://i.imgur.com/Hn8B7DU.png)
![image](https://i.imgur.com/EvJXcry.png)
![image](https://i.imgur.com/Tcyd9JY.png)
![image](https://i.imgur.com/MDnvZgy.jpg)

## Steps to reproduce

1. Make a vertical stack with `media_player.spotify` and `media_player.cast_device`
2. In Spotify play to the Cast device
3. Look at the inconsistency

## Environment

- Home Assistant release with the issue: 0.107.0b3
- Last working Home Assistant release (if known): ??
- Browser and browser version: Chrome desktop, HA iOS app
- Operating system: 

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
@balloob 

I have noticed this too with the difference in Spotify and Google Home. I think it has to do with the way the images are supplied. Not 100%. The difference between browsers is not something we can really change. Its the way the browser handles images and colors.

But I would have though the new Generator would have fixed this issue with different colors on the same browser

**Comment by balloob** [comment]
Which beta is this? We redid the algorithm in 3.

Still, it's being downsampled and then a histogram extracted, this is not deterministic. Combine that with the images being a different format via different sources.

Anyway try again on b3 if you didn't yet.

**Comment by SeanPM5** [comment]
This was after updating to b3, all screenshots are from that build. Not sure whether this also occurred on previous betas. Here's the stack I tested it with.

```
- type: vertical-stack
  cards:

    - type: media-control
      entity: media_player.spotify

    - type: media-control
      entity: media_player.your_google_cast_device
```

Was just a little strange as the album art looks identical on my screen(s) and the artwork is being supplied from the same source (Spotify). But I don't think it's a big deal, they all look fine to me. Just thought it was worth mentioning.
