### ISSUE TITLE
Device automation predefined fields are not defined

### ISSUE THREAD

**Issue by Santobert** [home-assistant/frontend#5207]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

![grafik](https://user-images.githubusercontent.com/15657682/76686059-f5f5db00-6618-11ea-8c38-a560721df274.png)

When you create a device automation that is triggered by a changed value, the fields `above` and `below` are predefined with 0. But when I leave them like this, it can't be saved because `Message malformed: must contain at least one of below, above.`
It seems like the fields are not really defined.
At the moment it is not possible to save an automation that triggers around 0.

## Expected behavior
Either the fields are not predefined, or they are and 0 is accepted.

## Steps to reproduce

1. Create an automation
2. Choose a device that provides a numeric value
3. Try to save

## Environment

- Home Assistant release with the issue: 0.107.0b3
- Last working Home Assistant release (if known): Not known
- Browser and browser version: Firefox 73.0.1
- Operating system: Arch Linux (KDE Plasma)

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by Santobert** [comment]
Still an issue with 0.111.2

**Comment by Santobert** [comment]
Still relevant in 0.115.0b7

**Comment by bramkragten** [comment]
Something can never be below 0 and above 0?

**Comment by Santobert** [comment]
That for sure. The issue here is, that the fields are predefined with 0 but this value is not valid and it is ignored. A new trigger looks like this:
![grafik](https://user-images.githubusercontent.com/15657682/92999435-1bf52d00-f521-11ea-862c-f6be8621ee47.png)
But the resulting yaml looks looks like this:
![grafik](https://user-images.githubusercontent.com/15657682/92999444-2d3e3980-f521-11ea-9589-6d7659b06f4a.png)

Even when I try to delete the `below` value the 0 in `above` is ignored. As a result one cannot create a trigger with a 0 in `above` or `below`. This is only possible in yaml, but not with the UI.

**Comment by bramkragten** [comment]
OK, I understand.

**Comment by Santobert** [comment]
Still relevant in 1.0.0b4

**Comment by Santobert** [comment]
Issue persists in 2021.3.4

**Comment by svenbrier** [comment]
I ran into the same issue. Setting the duration fixed it for me:
<pre><code>    domain: sensor
    above: 0
    below: 20
    for:
      hours: 0
      minutes: 1
      seconds: 0</code></pre>

**Comment by Lxxrxns** [comment]
What if I want my trigger for my automation to be "ANY change in a numeric value"? Without the condition that the new value has to be above or below a certain number?
