### ISSUE TITLE
Device automation brightness / brightness_pct

### ISSUE THREAD

**Issue by Santobert** [home-assistant/frontend#5211]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When creating a device automation it is possible to select a brightness value for lights. The slider allows values between 0 and 100, so it should select `brightness_pct`. However, the resulting automation will contain the selected value as `brightness`, which makes the light less bright than intended.

![grafik](https://user-images.githubusercontent.com/15657682/76687167-b41d6280-6621-11ea-8333-4688f1d3a509.png)

The resulting automation:
```yaml
  action:
  - brightness: 80
    device_id: c1c6912e2d2d4928ad990c56a9ecc3bc
    domain: light
    entity_id: light.schlafzimmer
    type: turn_on
```

The light after it was turned on:
![grafik](https://user-images.githubusercontent.com/15657682/76687204-02cafc80-6622-11ea-81fc-e2768be874bc.png)

## Expected behavior
Either select a value between 0 and 255 or set `brightness_pct`

## Environment

- Home Assistant release with the issue: 0.107.0.b3
- Last working Home Assistant release (if known): Not known
- Browser and browser version: Firefox 73.0.1
- Operating system: Arch Linux (KDE Plasma)

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
Not sure, if this is indeed a frontend bug. If not, please transfer it to `core`.

**Comment by Santobert** [comment]
Not sure, if this is indeed a frontend bug. If not, please transfer it to `core`.

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/pull/5201
