### ISSUE TITLE
LIFX integration no longer triggering area selection modal dialog box

### ISSUE THREAD

**Issue by Djelibeybi** [home-assistant/frontend#5215]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

When you enable the LIFX integration, it no longer pops up a modal dialog box to select the area for each discovered bulb. This used to occur in older versions of Home Assistant, but no longer occurs. Unfortunately, I don't know exactly which version was the last one that worked.

## Expected behavior

When you enable the LIFX integration, a modal dialog should pop up (like it does for Hue) with each discovered bulb, allowing selection of area for that bulb.

## Steps to reproduce

1. Have some LIFX devices
2. Add the LIFX integration or click "Configure" if discovery is enabled

## Environment

- Home Assistant release with the issue: 0.106.6
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Firefox 74.0 (64-bit)
- Operating system: macOS 10.15 Catalina

## Problem-relevant configuration

No specific configuration: using `default_config:` and the discovery service.

## Javascript errors shown in your browser console/inspector

None

**Comment by bramkragten** [comment]
Is this a frontend issue or an issue with LIFX? Does it work with other integrations?

**Comment by Djelibeybi** [comment]
> Is this a frontend issue or an issue with LIFX? Does it work with other integrations?

Just LIFX. It works fine with other integrations.

**Comment by bramkragten** [comment]
Then please create an issue in the core repo for lifx
