### ISSUE TITLE
Unable to edit card via Configure UI if view is in Panel Mode

### ISSUE THREAD

**Issue by akasma74** [home-assistant/frontend#5216]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

If in UI mode I select `Configure UI` and open a view with Panel Mode enabled, there is no `Edit` at the bottom of a card inside it. If I click on the pencil next to the view's name and turn Panel Mode off, `Edit` comes back and I can edit my card as usual.

## Expected behavior

`Edit` should be available irrespectively of Panel Mode setting.

## Environment

- Home Assistant release with the issue: 0.105.2
- Last working Home Assistant release (if known): ?
- Browser and browser version: Goggle Chrome 80.0.3987.132 (Official Build) (64-bit)
- Operating system: OS X 10.11.6

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by akasma74** [comment]
@bramkragten I'm sorry but why did you change it from a bug to a feature request?

**Comment by bramkragten** [comment]
A bug is when something doesn't function as the developer intended to.

This is implemented in 0.108

**Comment by akasma74** [comment]
Thanks for letting me know that it's implemented in 0.108

Don't be offended but if it's a) works everywhere apart from this particular situation and b) not documented at the time of reporting and b) reported prior to 0.108, it's not a feature - it's a bug. That's how I see it.
You could've easily close it without changing the label ;)
Nevermind, I'm happy 👍
