### ISSUE TITLE
Brightness slider disappear when brightness = 1

### ISSUE THREAD

**Issue by JonasKristiansen** [home-assistant/frontend#5217]
## The problem

After upgrading to 0.106.6 the "slider" on lamps disappear when you set the brightness to the lowest setting. 

It is still there if you can find it "in the blind", but you can´t see it until brightness is above 2.

Set light to 1.

## Environment

arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
timezone | Europe/Copenhagen
version | 0.106.6
virtualenv | false

- Home Assistant release with the issue: 0.106.6
- Last working Home Assistant release (if known):
- Operating environment (Hass.io/Docker/Windows/etc.): Hass.io
- Integration causing this issue: Light
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes
   

scene: !include scenes.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Alarm
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: xxxx
    pending_time: 3
    delay_time: 3
    trigger_time: 3
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 15
      delay_time: 0
    armed_away:
      pending_time: 15
      delay_time: 0

# Text to speech
tts:
  - platform: google_translate
    language: 'da'
    
# Includes
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Xiaomi støvsuger
vacuum:
  - platform: xiaomi_miio
    host: 192.168.87.106
    token: xxxx

# Lys grupper

light:
  - platform: group
    name: Køkken bord
    entities:
    - light.koekken_v
    - light.koekken_h
    
  - platform: group
    name: Spisebord
    entities:
    - light.spisebord_1
    - light.spisebord_2

# Sensorer

sensor:
  - platform: attributes
    friendly_name: "Last clean-up time"
    attribute: cleaning_time
    icon: 'mdi:clock'
    time_format: '%e %B - %H:%M:%S'
    entities:
      -  vacuum.xiaomi_vacuum_cleaner
      
  - platform: attributes
    friendly_name: "Hours to sensor clean"
    attribute: sensor_dirty_left
    entities:
      -  vacuum.xiaomi_vacuum_cleaner
      
  - platform: attributes
    friendly_name: "Hours to side bruch change"
    attribute: side_brush_left
    entities:
      -  vacuum.xiaomi_vacuum_cleaner
      
  - platform: attributes
    friendly_name: "Hours to main brush change"
    attribute: main_brush_left
    entities:
      -  vacuum.xiaomi_vacuum_cleaner
      
  - platform: attributes
    friendly_name: "Hours to filter change"
    attribute: filter_left
    entities:
      -  vacuum.xiaomi_vacuum_cleaner
      
# Booleans
input_boolean:
  cleaned_today:
    name: Check if vacuum has cleaned today

  guests:
    name: Guests in the house

  empty_vacuum:
    name: Emptied this week

  vacation:
    name: Status of vacation mode
    
  night:
    name: Night mode

    

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information

Brightness = 1. 

No slider.

![Skærmbillede 2020-03-14 kl  20 02 04](https://user-images.githubusercontent.com/59250377/76688668-3fe9bb80-662f-11ea-9371-cd29fe23bf79.png)

Brightness above 1.

Slider is visible.
![Skærmbillede 2020-03-14 kl  20 06 31](https://user-images.githubusercontent.com/59250377/76688688-73c4e100-662f-11ea-8c86-2e2a35c7ee2b.png)

**Comment by frenck** [comment]
Seem like a frontend issue to me, so I have moved it to the Frontend repository.

**Comment by bramkragten** [comment]
Can't replicate, might be theme related. Can you try the default theme?

**Comment by JonasKristiansen** [comment]
Just tested with default theme and this here the slider works as expected. When using dark_mint theme this "bug" appears. I´ve changed my night time theme to dark_teal and here the slider works fine.

Sorry for not testing the default theme first! :-)

"Problem" solved.
