### ISSUE TITLE
Unused Entities - randomly missing icons in 0.107

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5219]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Since 0.107 it seems like ~20% of icons on the Unused Entities screen do not load in.

* This appears to be random, different icons fail to load. If you refresh the page and come back to it, the icons that were not displaying will be displaying now, and some other icons will be missing instead.
* This happens all over at random parts, from the first cell to the last cell. It's not like it loads the first half and then fails with the second half.  
* Clicking on the entity to bring up the more-info dialog _does_ show the correct icon there, it's just not being shown in the data table. 
* This happens on both default domain icons and icons that I have set via `customize:`
* I see this behavior on my main instance (~1300 entities) and another test instance with far fewer, only like ~100 entities. So I don't think it has to do with number of entities either.
* I do **not** see this behavior on the Entities panel which has a similar style data table.
* There doesn't appear to be any relevant errors in the home assistant log or the browser console as far as I can tell.

Here's a pic, these are all supposed to have the default domain icon for automation:

![image](https://i.imgur.com/IPwAIzz.png)

## Expected behavior

Display all icons as normal

## Environment

- Home Assistant release with the issue: 0.107.0b3
- Last working Home Assistant release (if known): 0.106.X
- Browser and browser version: Chrome
- Operating system: macOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by SeanPM5** [comment]
Also is happening on Lovelace card editors:

![image](https://i.imgur.com/lKwziF2.png)

Was able to reproduce this in both places by rapidly scrolling the list up and down. Icons that were previously loaded would go missing after I scrolled past them and then scrolled back up.

Seems to me like it's loading  / unloading icons on the fly now? Because I have definitely noticed a very nice performance increase. Don't know if it's a bug with that, or maybe the Raspberry Pi 4 hardware can't keep up.

**Comment by bramkragten** [comment]
This should be fixed
