### ISSUE TITLE
Default Lovelace Dashboard selector like that for themes

### ISSUE THREAD

**Issue by gadgetchnnel** [home-assistant/frontend#5223]
## The request

With the support for multiple Lovelace dashboards in 0.107 it would be nice to be able to have a drop-down list to select the default dashboard from the user page, the same as for themes.

## The alternatives

Currently setting the default dashboard for a device involves multiple clicks (Configuration > Lovelace Dashboards > *dashboard* > Set as Default on this Device)

**Comment by Nihvel** [comment]
I was going to open the same feature request, but using a different approach:

Admin user(s) should be able to edit the environment of other simple users.
The environment is:
  - themes
  - dashboard

Example:
Given 2 users: [Homer, kiosk1]
_Homer_ is an _Admin_ user.

_Homer_ is allowed to edit _kiosk1_ settings about theme and dashboard.
_Kiosk1_ is a user logged in into a Tablet device and this is in the living room. _Kiosk1_ only requires to see entities related to its environment, therefore _Admins_ users will set the dashboard "Living room" as its default dashboard. Same goes for themes.

Such settings can be set in` Configuration > Users > "name of the user"`

Another user, _Marge_, is the wife of the _Admin_ user. _Marge_ has the app of Home Assistant installed in her smartphone but _Marge_ is not _Admin_. She can still chose whatever theme she likes to use and setup her own dashboard if she prefers. Or, she could chose from predefined Dashboards that the user _Admin_ created previously
_Admins_ may still edit other _non-kiosk_ user environment.

**Comment by ttaidapos** [comment]
This is a big problem with multiple users.  The only way to set a default dashboard is to temporarily assign a person administrator access, go to config, select default dashboard, and then take away access.

**Comment by Giannie** [comment]
I think it would make sense to have non-administrator users set the default dashboard. Ideally it should also be possible to set default dashboard by user instead of by device. If not it would make sense for users to be able to choose a dashboard as their default for their device.

**Comment by Giannie** [comment]
Sorry, I don’t understand why this was closed. I see why the duplicate was closed as this is not a bug, but is there a reason to close the feature request?

**Comment by ttaidapos** [comment]
> Sorry, I don’t understand why this was closed. I see why the duplicate was closed as this is not a bug, but is there a reason to close the feature request?

The feature to select view was moved one of the latest releases, i forget which but now it's possible to select view from user profile.
