### ISSUE TITLE
Theme incorrectly applied in configuration menu for "devices" and "entities"

### ISSUE THREAD

**Issue by browetd** [home-assistant/frontend#5227]
## The problem
 If I apply a dark theme in HA (dark background with white color text for example), it is impossible to read the text displayed in the configuration menu for options "devices" and "entities"...  All the other options are working fine (automations, scenes,...).  The problem comes that the background color is white independtly of the theme applied and if my text color is white as well in the theme, that panel is totally unusable.  

## Environment
I am running HA 0.106.6 in a venv environment on a PI4B with python 3.7.3

- Home Assistant release with the issue: 0.106.6 
- Last working Home Assistant release (if known): ? 
- Operating environment (Hass.io/Docker/Windows/etc.): venv on PI4B with python 3.7.3 
- Integration causing this issue: ?
- Link to integration documentation on our website: ? 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by bramkragten** [comment]
Probably your theme is not correct. (and a screenshot helps to explain issues like these)

![image](https://user-images.githubusercontent.com/5662298/76759078-45f4af00-678b-11ea-9429-73824eb0ed4d.png)

**Comment by browetd** [comment]
Maybe but I cannot explain why Integrations and Areas panels are ok (similar to what you show in the print screen) but not devices and entities panels (these are the only two not displaying correctly in the configuration menu)... It should not work everywhere if my theme was not correct... or maybe the background color of the different options in the menu is using two different characteristics/parameters of the same theme...  Here are 4 print screens (two with the Dark theme and two with the LIght theme)
[Print Screen 1.pdf](https://github.com/home-assistant/frontend/files/4338277/Print.Screen.1.pdf)
[Print Screen 2.pdf](https://github.com/home-assistant/frontend/files/4338278/Print.Screen.2.pdf)
[Print Screen 3.pdf](https://github.com/home-assistant/frontend/files/4338279/Print.Screen.3.pdf)
[Print Screen 4.pdf](https://github.com/home-assistant/frontend/files/4338280/Print.Screen.4.pdf)

**Comment by browetd** [comment]
Maybe but I cannot explain why Integrations and Areas panels are ok (similar to what you show in the print screen) but not devices and entities panels (these are the only two not displaying correctly in the configuration menu)... It should not work everywhere if my theme was not correct... or maybe the background color of the different options in the menu is using different characteristics/parameters of the same theme... Here are 4 print screens (two with the Dark theme and two with the LIght theme)

![ice_screenshot_20200316-140457](https://user-images.githubusercontent.com/46415133/76761206-5575f700-678f-11ea-9dde-fd007a1dbcd0.png)
![ice_screenshot_20200316-140559](https://user-images.githubusercontent.com/46415133/76761211-56a72400-678f-11ea-98b9-eba23f268538.png)
![ice_screenshot_20200316-140536](https://user-images.githubusercontent.com/46415133/76761209-560e8d80-678f-11ea-95e3-93a9f1579cca.png)
![ice_screenshot_20200316-140412](https://user-images.githubusercontent.com/46415133/76761213-56a72400-678f-11ea-9f23-5662555f85e6.png)

**Comment by bramkragten** [comment]
Do you have a `card-background-color` in your theme? If not, you should add it (or replace `paper-card-background-color` with it)

**Comment by browetd** [comment]
@bramkragten  Adding the **card background** to my themes.yaml fixed the problem...  Thank you!  Nevertheless, the behaviour of the options in the configuration menu (at least for the themes) should be standardized I think and use now **card-background-color** ...  it seems that most of the options are still using **paper-card-background-color**  as they were ok before adding the card-background-color in my config...  Do you know where I can find the updated list of parameters for the themes ?  My themes.yaml file is (I think) way too much complicated and with probably a bunch of redundant/unused parameters ...due to all the recent changes/standardization and cleanup in Home assistant...  Thanks !

**Comment by bramkragten** [comment]
Nope, we don't have a list. Hopefully, soon we will finish cleaning up and can make an official list.
