### ISSUE TITLE
No countdown displayed if timer has duration more than 24 hours

### ISSUE THREAD

**Issue by akasma74** [home-assistant/frontend#5235]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

Based on [this](https://community.home-assistant.io/t/timer-duration-limit/179048) topic.
If we start a timer with duration more than 24*60*60 seconds thre will be no countdown if we insert it in LL card.
This is because the remaining time is calculated [here](https://github.com/home-assistant/frontend/blob/dev/src/common/entity/timer_time_remaining.ts#L5) using [this](https://github.com/home-assistant/frontend/blob/2925b930ade3d636ef3cf4faa10bece4af896383/src/common/datetime/duration_to_seconds.ts#L1) function that assumes time is always HH:MM:SS and most likely fails on conversion of '1 day' to a number.

## Expected behavior

As there is no mention of any explicit limits on duration, coundown should be displayed correctly regardless of the `duration` value. Another option is to say explicitly in the docs that the maximum duration supported is 23*3600+59*61

## Steps to reproduce

1. Create a timer
2. Add it to an Entity card in UI
3. Call `timer.start` with `duration: 9000`
4. There will be a countdown in LL card
5. Call `timer.start` with `duration: 90000`
6. There will be an empty space in place of the countdown in LL card

## Environment

- Home Assistant release with the issue: 0.106.6
- Last working Home Assistant release (if known): ?
- Browser and browser version:
- Operating system:

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by akasma74** [comment]
is there a chance this can be looked into?

**Comment by bramkragten** [comment]
Please don't bump your issues. If someone has time they will look at it.

**Comment by akasma74** [comment]
Adios field marshall
