### ISSUE TITLE
Better error handling for input_datetime

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5236]
## The request

When an input_datetime is deleted, it does not show the "Unavailable" state text that pretty much everything else does. Just an empty space on the right side. Example:

![image](https://i.imgur.com/DF3E1SU.png)

This kinda makes it appear like the date was just not set or something? It should be more obvious so the user knows something is wrong and can fix it. Doing this would also make it more consistent with everything else.

Expected behavior:

![image](https://i.imgur.com/O4uqZvD.jpg)

**Comment by spacegaier** [comment]
@SeanPM5 I might be missing something here. If I delete or disable an existing input_datetime that I have in my UI, then it gets shown there as any other missing entity:
![image](https://user-images.githubusercontent.com/114137/96200603-98cd5980-0f5a-11eb-83bf-5d70a0da3811.png)

So it's not clear for me how you ended up with your first screenshot.

**Comment by SeanPM5** [comment]
@spacegaier you're correct, I can no longer reproduce this behavior. I opened this right before Helpers got added to the UI, so perhaps it was improved then or sometime in the following months.

Closing as this is no longer an issue.
