### ISSUE TITLE
Card Picker - Gauge card appearance bug on iOS

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5237]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

From the [demo site](https://demo.home-assistant.io/#/lovelace/0) on iOS 13.3.1 -

![gauge-card](https://i.imgur.com/pRt8H2z.png)

This is only on the card picker in 0.107.0b6 , it doesn't occur in the actual card editor.

## Steps to reproduce

1. Go to Configure UI -> Add Card on an iPhone / iOS device
2. Scroll to Gauge card and see distorted preview

## Environment

- Home Assistant release with the issue: 0.107.0b6
- Last working Home Assistant release (if known): earlier versions of 0.107 betas (not sure which)
- Browser and browser version: iOS mobile Safari
- Operating system: iOS 13.3.1

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
I can't figure this one out... @bramkragten
