### ISSUE TITLE
Invalid Date on Log Details page

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5238]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

On 0.107.0b6 the log details all seem to say invalid date for me (screenshot below). Tested on two different HA instances. There was a minor typo fix for this section in https://github.com/home-assistant/frontend/pull/5225 , not sure if that might have caused it?

![image](https://i.imgur.com/yI8Sr8W.png)

## Expected behavior

Show correct time stamp of when log error first occurred

## Steps to reproduce

1. Navigate to Developer Tools > Logs
2. Click on any log item, see details at top

## Environment

- Home Assistant release with the issue: 0.107.0b6
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome
- Operating system: macOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
🙈

**Comment by bramkragten** [comment]
This is because the backend and the frontend are not aligned. Tagged the backend PR for 0.107
