### ISSUE TITLE
Demo site missing title

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5244]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Noticed this while trying to reproduce a bug in the demo... The title is not showing anymore. The tab in this below screenshot should say "Home Assistant Demo" (and it is in the HTML).

![image](https://i.imgur.com/5T4orBb.png)

I believe it has to do with the "Set Title to Current Panel" PR https://github.com/home-assistant/frontend/pull/5220 . Google cache shows what the title was two days ago:

![image](https://i.imgur.com/Z6MgcJG.png)

And `<title>Home Assistant Demo</title>` is still there when you view source of website, just not being shown.

This doesn't really break anything on the user side, but it might be bad for SEO purposes or something?

## Expected behavior

Show "Home Assistant Demo" as title upon first load.

## Steps to reproduce

1. Visit [Home Assistant Demo](https://demo.home-assistant.io/)

## Environment

- Home Assistant release with the issue: 0.107.0b6
- Last working Home Assistant release (if known): 0.107.0b3 ?
- Browser and browser version:
- Operating system:

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Fixed
