### ISSUE TITLE
Hide data table when no devices

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5260]
## The request

There's a bunch of integrations that don't have devices - Coronavirus, Met.no, Transmission to name just a few. When you view these integrations, they display an empty data table with "No devices" text.

![image](https://i.imgur.com/efwbzNO.png)

Would be nicer if the table could just be hidden in this scenario?

It takes up screen real estate, appears above the actual entities that the user will want to see, and it's not functional obviously (not even the search works).  Hiding the table in this scenario would make things cleaner.

**Comment by bramkragten** [comment]
This screen will be removed in the revamp. That's why I have not given it much attention.

**Comment by SeanPM5** [comment]
Ah good point :)
