### ISSUE TITLE
Card visual editor issue with conditional card in vertical-stack

### ISSUE THREAD

**Issue by gadgetchnnel** [home-assistant/frontend#5261]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When creating a vertical-stack containing a conditional card the visual editor for the card doesn't work and gives the following:

![Screenshot 2020-03-18 at 18 36 53](https://user-images.githubusercontent.com/2099542/76995445-c52ee200-6947-11ea-98a9-8895e1874a28.png)
The only way to get the visual editor to work is to click on **Show code editor**, manually enter the card configuration and then click on **Show visual editor**

When using the conditional card on its own, the card picker is displayed as expected:

![Screenshot 2020-03-18 at 18 41 44](https://user-images.githubusercontent.com/2099542/76995733-32db0e00-6948-11ea-9038-4a1a1e678012.png)

## Expected behavior

The card picker should display on the card tab for a conditional card within a vertical stack.

## Steps to reproduce

1. Add a new card to a view, selecting Verical Stack as the type
2. Add a Conditional card to the Vertical Stack
3. Switch to the **Card** tab in the editor

## Environment

- Home Assistant release with the issue: 0.107.0
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome 80.0.3987.116 
- Operating system: macOS Mojave 10.14.6

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
This has been fixed and will be in 0.107.1
