### ISSUE TITLE
not save the login token

### ISSUE THREAD

**Issue by rant989** [home-assistant/frontend#5264]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

No more asking if keep the login, and every time I refresh I have to login again

## Environment

Home Assistant 0.107.0

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.15.0-91-generic

**Comment by bramkragten** [comment]
Will be fixed in 0.107.1

**Comment by rant989** [comment]
thanks

**Comment by iptvcld** [comment]
thanks..
