### ISSUE TITLE
Input_number value and unit of measurement cut off in mobile portrait

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5266]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Credit to jrijker1 for spotting this. https://community.home-assistant.io/t/media-player-volume-slider-and-source-select/131439/13?u=seanm

On mobile, in portrait mode, the input_number unit of measurement is no longer displayed, think it might be off-screen? There's a little bit of an empty space to the right where it usually displays:

![portrait](https://i.imgur.com/DNUVaIF.jpg)

When switching to landscape, it appears:

![landscape](https://i.imgur.com/sWqWJ1q.jpg)

This did used to display on mobile portrait before (not my screenshot): 

![image](https://i.redd.it/mrqz965qnvj11.jpg)

## Expected behavior

Show unit of measurement in mobile portrait

## Steps to reproduce

Add an input_number to an entity row card, then look on a mobile device (change between portrait/landscape)

## Environment

- Home Assistant release with the issue: 0.107.0
- Last working Home Assistant release (if known): 0.106 i think
- Browser and browser version: HA iOS app
- Operating system: iOS 13.4

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
This should be better in .108 beta. The first thing we hide is the number. So the slider has more room at smaller screens

**Comment by SeanPM5** [comment]
The display of the slider looks nicer than before, but I still consider this a minor issue since all you get on mobile portrait is the slider, no value or unit of measurement. You have to actually drag the slider in order to see the value, but at that point you've already changed what the value was.

But then again you can tap the more info to view those details. So I guess it's not really too big of a deal, closing.
