### ISSUE TITLE
Card Picker - history graph preview shows entities with no history

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5268]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Noticed this today for the first time, the preview on History Graph card in card picker is showing an entity (`sensor.active_radio_source`) that was excluded from recorder. This displays "No state history found" and will _always_ display no state history found. 

![image](https://i.imgur.com/KylUGZY.png)

Not really a great preview. I understand this is selected at random or whatever, but maybe there can be some extra check/logic to make sure it has real data?

(Wasn't sure whether to label this a bug or FR, feel free to change it).

## Expected behavior

Entities excluded from recorder or with "No state history found" should not be shown in previews / stub config.

## Steps to reproduce

1. Exclude domains/entities from [recorder](https://www.home-assistant.io/integrations/recorder/)
2. Open card picker and look at history graph

## Environment

- Home Assistant release with the issue: 0.107.0
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome
- Operating system: macOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
Still an issue

**Comment by zsarnett** [comment]
Talked about this today. This is something that would be nice. but would be very expensive to do just for this case
