### ISSUE TITLE
Error loading hui-markdown-card

### ISSUE THREAD

**Issue by aneisch** [home-assistant/frontend#5272]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Markdown card fails to load

`Custom element doesn't exist: hui-markdown-card.
`

## Environment

- Home Assistant release with the issue: `0.107`
- Last working Home Assistant release (if known): `0.106.6`
- Browser and browser version: `Chrome 80.0.3987.132 x64`
- Operating system: `Docker`

## Problem-relevant configuration

```yaml
title: Home
icon: mdi:home-circle
cards:
  - !include .cards/thermostat.yaml

  - type: custom:vertical-stack-in-card
    cards:
      - type: markdown
        content: |
          {%- set seconds = (as_timestamp(now()) - as_timestamp(states.input_datetime.front_door_last.state)) | int %}
          {%- set minutes = (seconds // 60) | int %}
          {%- set hours = (minutes // 60) | int %}
          {%- set days = (hours // 24) | int %}
          {{ states.input_datetime.front_door_last.name | capitalize }}: **{{days}}d {{hours%24}}h {{minutes%60}}m**

          {%- set seconds = (as_timestamp(now()) - as_timestamp(states.input_datetime.back_door_last.state)) | int %}
          {%- set minutes = (seconds // 60) | int %}
          {%- set hours = (minutes // 60) | int %}
          {%- set days = (hours // 24) | int %}
          {{ states.input_datetime.back_door_last.name | capitalize }}: **{{days}}d {{hours%24}}h {{minutes%60}}m**
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
#4984
