### ISSUE TITLE
"hui-cover-entityrow doesn't exists" exception

### ISSUE THREAD

**Issue by snakuzzo** [home-assistant/frontend#5278]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

After upgraded to 0.107.x my cards with covers and secondaryinfo-entity-row doesn't show correctly...

![image](https://user-images.githubusercontent.com/7205371/77046608-96565180-69c3-11ea-94cc-16d255a94a2a.png)

## Expected behavior

I expect this:

![image](https://user-images.githubusercontent.com/7205371/77046123-b33e5500-69c2-11ea-974d-005ecd0237ac.png)

## Steps to reproduce

1. Integrate custom card `secondaryinfo-entity-row`
2. Create a manual card including my code showed below
3. refresh the page (video linked below in additional info)

## Environment

- Home Assistant release with the issue: 0.107.1 
- Last working Home Assistant release (if known): 0.106.5
- Browser and browser version: Chrome 80.0.3987.149 (Official Build) (64-bit) / Firefox 74.0 (64-bit)
- Operating system: Raspbian Buster

## Problem-relevant configuration

This is my card...
```
entities:
  - entity: cover.matrimoniale
    secondary_info: >-
      [[ if(cover.matrimoniale.state == unavailable, <b style="color:red">non
      disponibile</b>, if(cover.matrimoniale.attributes.current_position == 0,
      "chiusa", if(cover.matrimoniale.attributes.current_position == 100,
      "aperta", cover.matrimoniale.attributes.current_position))) ]]
    type: 'custom:secondaryinfo-entity-row'
show_header_toggle: false
title: Tapparelle
type: entities
```

## Javascript errors shown in your browser console/inspector

No errors 

## Additional information
This is a short clip to show what happens...

https://www.youtube.com/watch?v=pcLHaDFPaXI

An issue is also opened on secondaryinfo-entity-row project...

https://github.com/custom-cards/secondaryinfo-entity-row/issues/27

**Comment by bramkragten** [comment]
This is the custom card that needs updating. Please create an issue there or update.
