### ISSUE TITLE
Demo fails to load

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5280]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

https://demo.home-assistant.io/

Demo site fails to load with error message `Loading chunk 23 failed. (error: https://demo.home-assistant.io/frontend_latest/chunk.ce5bb3ec962ade696583.js)`

This appears to be **only** for the Overview page, everything else (notifications/sidebar/map/profile page) works fine. But the Overview page is the most important part obviously.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Have you cleared your cache? Works here...

**Comment by SeanPM5** [comment]
Works after clearing cache, false alarm :)
