### ISSUE TITLE
0.107.1 No custom ui resources are shown in Cast

### ISSUE THREAD

**Issue by greberg** [home-assistant/frontend#5281]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [] I have tried a different browser to see if it is related to my browser.

## The problem

I have manage to setup a local instance of cast receiver. I can authorize and connect to my Nest Hub without any problem using the local deployed cast receiver. Even show lovelace cards, unfortunate no custom ui resources are shown. The exact same behavior happen during 0.106 release using cast.homeassistant.io but with the new 0.107 release it work so someone did something to get it to work, question is what?
## Expected behavior

Expected behavior is to see my custom resources

## Environment

- Home Assistant release with the issue: 0.107.1
- Last working Home Assistant release (if known): Not know due to local instance
- Browser and browser version: Chrome 
- Operating system: Docker Linux Ubuntu

## Problem-relevant configuration

In my configuration.yaml file I use:
cors_allowed_origins:
    - https://urltocastservice (not using IP, now deployed in production)

Also all resources are moved from ui-lovelace.yaml to configuration.yaml and uses the following structure:
- url: /hacsfiles/weather-card/weather-card.js
      type: module

Custom resources works perfectly on desktop, mobile and cast if running cast.homeassistant.io so it is something when running local setups.

In dev_const.ts:
  - https://urltohomeassistant (not using IP, now deployed in production)

On https://cast.google.com/publish/#/overview:
  - https://urltocastservice/receiver.html (not using IP, now deployed in production)
  
```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
![IMG_3109](https://user-images.githubusercontent.com/213160/77111242-4610db00-6a27-11ea-9379-b31dff4d38f5.jpg)

**Comment by bramkragten** [comment]
You run your own cast app? Have you updated it for 0.107?

**Comment by greberg** [comment]
I run the 0.107 cast receiver locally on my server yes as the readme https://github.com/home-assistant/frontend/blob/dev/cast/README.md says. Everything runs smoothly except no custom ui components work

**Comment by bramkragten** [comment]
I looks like you have an old version, maybe cached?

**Comment by greberg** [comment]
The picture you see is on a nest hub. I believe that nest hub is not using cache? I have restarted it even. I have even tried running launcher in incongnito mode from the desktop computer, authorized and then manually start casting and chose the view that I want to see and I get the same result.

**Comment by bramkragten** [comment]
OK, could you try to update your local code once again? Since the code on cast.home-assistant.io is working, it seems like you have to have a different version running...

Otherwise, try inspecting your Nest Hub and see if there are any errors in the console.

**Comment by greberg** [comment]
Managed to get it to work. Not sure if this solved the problem. I changed in const.ts in /src/cast export const CAST_APP_ID = CAST_DEV ? CAST_DEV_APP_ID : "My own app id"; and then a re-build everything with script/build_cast. Now it works perfectly local

Thanks

**Comment by greberg** [comment]
One more tip to add if someone wants to run it locally. Not sure if this is obvious for everyone but I will write it here.

When I run through my Chrome browser and go to my local my cast launcher, start casting from the launcher and chose home_cast view everything is loaded as expected. No problem to inspect the device using chrome://inspect/#devices. But when I close down the cast and try to start it from an automation using  

cast.show_lovelace_view
entity_id: my_nest_hub
view_path: home_cast

Custom ui components aren't shown and look as the picture above and I can't inspect the device using chrome://inspect/#devices

My thoughts went back to how is launching the cast. In scenario one it is launched by my launcher which uses my app id while in scenarion 2 it is launched by Homeassistant and my homeassistant instance have no clue about my app id. So I needed to modify in my backend core as well. In /homeassistant/components/cast/home_assistant_cast.py you need to uncomment 
controller = HomeAssistantController(
            # If you are developing Home Assistant Cast, uncomment and set to your dev app id.
            # app_id="5FE44367",
            hass_url=hass_url,
            client_id=None,
            refresh_token=refresh_token.token,
        )
app_id and write your own appid to get it to work from home assistant.

I will try to get through a feature request to be able to set your own app id in the configuration of the backend.
