### ISSUE TITLE
Can't cast new lovelace dashboards

### ISSUE THREAD

**Issue by FuzzyMistborn** [home-assistant/frontend#5285]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I set up a new dashboard called "Cast."  I added the views I want to be able to cast (i'll use "cameras" as my example.  When trying to use the cast.show_lovelace_view, for the view_path i've tried "cameras" and "lovelace-cast/cameras" and neither works.  The pages also do not show up on the cast.home-asssistant.io page.
## Expected behavior

Being able to cast the new lovelace dashboard pages.
## Steps to reproduce

See above.
## Environment

arch | x86_64
-- | --
dev | false
docker | true
hassio | false
os_name | Linux
os_version | 4.15.0-74-generic
python_version | 3.7.6
timezone | xxx
version | 0.107.1
virtualenv | false

- Home Assistant release with the issue:
- Last working Home Assistant release (if known): 106.x
- Browser and browser version: All
- Operating system: Linux/Windows

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
The cast service has no support for multiple dashboards yet <https://github.com/home-assistant/core/pull/32913>.

You can use the Lovelace row to cast a different dashboard <https://www.home-assistant.io/lovelace/entities/#cast>
