### ISSUE TITLE
New Media card, not displaying media buttons and progress bar, Fire HD8" tablet

### ISSUE THREAD

**Issue by basesnow** [home-assistant/frontend#5286]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

New media card does not display the media buttons and progress bar on my fire HD8 tablet. I am using the Apple TV Beta integration via HACS. I am running Fully Kiosk, displaying the Lovelace URL as the front end. This doesn't appear to be an issue on Safari on my Mac, or on my iPhone using the home assistant app.

## Expected behavior

When media is playing, I should see the media buttons (play/pause, forward, and back) and the progress bar.

## Steps to reproduce

add new media player card, play media.

## Environment

- Home Assistant release with the issue: 0.107.1
- Last working Home Assistant release (if known): 0.106.x
- Browser and browser version: ? (not sure what browser Fully Kiosk on Fire HD8 tablet uses)
- Operating system: FireOS

## Problem-relevant configuration

none

## Javascript errors shown in your browser console/inspector

none

## Additional information

![FireTablet](https://user-images.githubusercontent.com/36908616/77129838-d94c0f80-6a2b-11ea-983d-4c222615b5f9.jpeg)
![iphone](https://user-images.githubusercontent.com/36908616/77129841-dcdf9680-6a2b-11ea-824f-781e7ecbb801.png)
<img width="1183" alt="mac" src="https://user-images.githubusercontent.com/36908616/77129845-df41f080-6a2b-11ea-8f4c-11adbfa9261f.png">

**Comment by zsarnett** [comment]
This is expected. The size of the card makes a difference on what buttons you will see
