### ISSUE TITLE
Can't change a dashboard for user that is not an administrator

### ISSUE THREAD

**Issue by fantomnotabene** [home-assistant/frontend#5293]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Settings is not available for users, so user can't change his default dashboard

## Expected behavior

Any user can choose dashboard on their own

## Environment

- Home Assistant release with the issue: 0.107.1
- Last working Home Assistant release (if known): no
- Browser and browser version: not applicable
- Operating system: not applicable

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

As a temp solution, I can change user's group to administrator, change dashboard and get back the right group, but.. you know, not the solution anyone wanna see and do :)

**Comment by bramkragten** [comment]
This is feature request, not a bug. And it is a duplicate, can't find the other one right now.

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/issues/5223

**Comment by fantomnotabene** [comment]
This is a bug, I think. The declared function is not working as expected. And you're right, this is a duplicate

**Comment by SeanPM5** [comment]
There's an easier temporary workaround solution for now. If you add the dashboard(s) to your sidebar, regular users will be able to see them and switch that way.

**Comment by fantomnotabene** [comment]
@SeanPM5 yes, it works that way, but for now this user is unable to select any dashboard as his default to have no need to switch every single time

**Comment by bramkragten** [comment]
Yes, that is true. And that's why we have #5223

**Comment by juan11perez** [comment]
Thank you.
