### ISSUE TITLE
Multiple Airvisual locations through integration not possible

### ISSUE THREAD

**Issue by drthanwho** [home-assistant/frontend#5294]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

Adding the AirVisual sensors through the integration on the UI is only letting me add one location for the integration. I thought I just need to add it again with a second location but it won't let you add same api key twice. Whereas, through configuration, according to docs, you can add multiple locations per one api key.
 
![image](https://user-images.githubusercontent.com/22405505/77203727-6c9b4880-6af1-11ea-9fe5-b9a935ff9a88.png)

## Expected behavior

Unclear yet as it was just implemented, but since it's available through the configuration, should it not also be possible to add multiple locations through the UI?

Either by adding two integrations with same api key or option for multiple locations on integration's config page
## Environment

- Home Assistant release with the issue: 0.107
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Chrome 80.0.3987.132
- Operating system: Rpi 3b

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
This is not a frontend bug, create an issue for this integration in the core repo.

**Comment by drthanwho** [comment]
Damn it sorry about that @bramkragten. That's where I started and then got confused if it should belong there or not.
