### ISSUE TITLE
Cannot add cards in pre-existing panel

### ISSUE THREAD

**Issue by fudu** [home-assistant/frontend#5295]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
As in subject, when I try to add a card on preexisting Panel, get message "Which card .. etc etc", but nothing to choose, as in attached image.
If I create a new panel it goes fine

## Expected behavior
Card list

## Steps to reproduce
Click Configure UI
Click + button to add Card

## Environment
![Cattura](https://user-images.githubusercontent.com/6508171/77203766-8b014400-6af1-11ea-8954-c4a5dd4137e0.JPG)

- Home Assistant release with the issue: 0.107.1 - 0.107.2
- Last working Home Assistant release (if known): latest 0.106
- Browser and browser version: Tried with different browser - Chrome, Firefox, Edge
- Operating system: Client various - server: Vm on Qnap virtualization station

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
Are there any logs in the console of the browser?

What are the settings of that view? is it in Panel Mode?

**Comment by bramkragten** [comment]
Any custom cards?

**Comment by fudu** [comment]
> Are there any logs in the console of the browser?
>  

When I try to add cards get message in web console 
 - `compute-unused-entities.ts:54 Uncaught (in promise) TypeError: t.cards.forEach is not a function
    at o (compute-unused-entities.ts:54)
    at compute-unused-entities.ts:54
    at Array.forEach (<anonymous>)
    at o (compute-unused-entities.ts:54)
    at compute-unused-entities.ts:54
    at Array.forEach (<anonymous>)
    at o (compute-unused-entities.ts:54)
    at compute-unused-entities.ts:66
    at Array.forEach (<anonymous>)
    at a (compute-unused-entities.ts:66)`

> What are the settings of that view? is it in Panel Mode?

No, standard view

**Comment by fudu** [comment]
> Any custom cards?

No cards at all
Attached different choices trying add cards in Preexisting Panel and in a new Panel
![Cattura2](https://user-images.githubusercontent.com/6508171/77206431-3d87d580-6af7-11ea-9a54-cb21ca461fc5.JPG)
![Cattura1](https://user-images.githubusercontent.com/6508171/77206433-3eb90280-6af7-11ea-8404-f9340413e7d4.JPG)

**Comment by bramkragten** [comment]
You have an error in your config, something should be an array but isn't.

**Comment by fudu** [comment]
> You have an error in your config, something should be an array but isn't.
> 
> Check for a `cards` that is not an array.
> 
> We should add a check for this in the code like I did for entities.

..?
Sorry, but I don't understand what you mean or how to do it.....

**Comment by bramkragten** [comment]
Check your Lovelace config for `cards:` there is at least one in there that does not have a list. (as it is plural it should be a list)

**Comment by fudu** [comment]
> here is at least one in there that does not have a list. (as it is plural it should be a list)

I found what is the cause of the issue: a conditional card
`cards:
  - entity: input_boolean.riscaldamento_manuale_on
    name: Riscaldamento Manuale
    style:
      - font-size: 12px
      - font-weight: bold
    tap_action:
      action: toggle
    type: entity-button
  - card:
      cards:
        - entity: input_boolean.riscaldamento_away_on
          name: test
          tap_action:
            action: toggle
          type: entity-button
        - entity: input_boolean.riscaldamento_festa_on
          tap_action:
            action: toggle
          type: entity-button
      type: horizontal-stack
    cards: conditional
    conditions:
      - entity: input_boolean.riscaldamento_manuale_on
        state: 'on'
    type: conditional
  - card:
      cards:
        - entity: input_boolean.riscaldamento_estate_on
          tap_action:
            action: toggle
          type: entity-button
        - entity: input_boolean.riscaldamento_antigelo_on
          tap_action:
            action: toggle
          type: entity-button
      type: horizontal-stack
    cards: conditional
    conditions:
      - entity: input_boolean.riscaldamento_manuale_on
        state: 'on'
    type: conditional
title: null
type: vertical-stack`
