### ISSUE TITLE
Remove integrations from the interface

### ISSUE THREAD

**Issue by addisonlynch** [home-assistant/frontend#5298]
## The request

Consider the scenario where an integration is added via the UI (e.g. add MQTT configuration) and the user decides that they would rather handle the configuration via ``configuration.yaml``. There is no way in the UI to remove the integration and configure manually. One must enter into ``.storage/core.config_entries`` and remove the entry for the integration.

Is there a better way to remove the integration cleanly?

Thanks!

**Comment by SeanPM5** [comment]
Go to Configuration -> Integrations -> click on the Integration -> trash can icon in top right will delete it. 

![image](https://i.imgur.com/LjbF7OY.jpg)

**Comment by addisonlynch** [comment]
@SeanPM5 thanks
