### ISSUE TITLE
Helper input field step size issue

### ISSUE THREAD

**Issue by TASSDevon** [home-assistant/frontend#5300]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I found a strange thing with the number input helper.

When selecting the slider, you can change the step size
When selecting "input field" you cannot change the step size, though it remembers.

When I set it to slider, change the stepsize to 0.5, then change it to input field. The UI allows me to use 0.5., otherwise it does not.

The input field should accept half numbers as well (e.g. for radiator valve setpoint)

Next to that I'm missing a field to enter the Friendly Name.

## Expected behavior

I should be able to use 19.5 as well in the input field (but it gets a red indication when I try)

## Environment

- Home Assistant release with the issue: 0.107.3 (Core)
- Last working Home Assistant release (if known): /
- Browser and browser version: Safari / Firefox
- Operating system: macOS

**Comment by edenhaus** [comment]
I wanted to report the same thing just now.
The attribute `step` is relevant also for the `mode:box` and not only for the slider.

We should not hide the step field, when selecting box in the UI.
Also we should change the documentation on the website.
