### ISSUE TITLE
Sensors and binary sensors are not sorted on the generated Lovelace

### ISSUE THREAD

**Issue by OleksandrBerchenko** [home-assistant/frontend#5311]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Migrated from States to the generated Lovelace.  All cards are alphabetically sorted as expected, except for sensors and binary sensors at the top: they are displayed in random order, that's not convenient at all (I have 100+ sensors there).

## Expected behavior

All sensors and binary sensors should be sorted alphabetically by default.

## Steps to reproduce

Open the generated Lovelace UI.

## Environment

- Home Assistant release with the issue: 0.107.5, frontend version: 20200318.1
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Firefox 74.0 + Chrome 80.0
- Operating system: Windows 10

## Problem-relevant configuration

n/a

## Javascript errors shown in your browser console/inspector

n/a

## Additional information

n/a

**Comment by OleksandrBerchenko** [comment]
Still actual as of 0.112.

**Comment by bramkragten** [comment]
You are talking about the badges, right? And please don't bump your issue until the bot asks you to.

**Comment by OleksandrBerchenko** [comment]
@bramkragten Yes!

**Comment by OleksandrBerchenko** [comment]
That's still an issue (as of HA 0.117).  If you have tons of sensors like me, it makes the default UI almost unusable.  I use it only for debugging, but anyway.

Thanks!

**Comment by OleksandrBerchenko** [comment]
@github-actions where are you? :)

**Comment by frenck** [comment]
It removed the stale automatically on the next run (every hour)

**Comment by OleksandrBerchenko** [comment]
Yes, it's still actual!

**Comment by spacegaier** [comment]
> 
> 
> Yes, it's still actual!

Above you confirmed to Bram that your issues is about the badges in the auto-generated view. However, with the latest HA version, there are no longer any badges added to the auto-generated view. So I am a bit confused how this can still be an current issue.

**Comment by OleksandrBerchenko** [comment]
@spacegaier Sorry, I did not install the latest version yet...  But yes, you are right, if they are removed completely, this issue can be closed.
