### ISSUE TITLE
State color wrong for dimmable lights

### ISSUE THREAD

**Issue by ochstobi** [home-assistant/frontend#5313]
## Checklist

- [ x ] I have updated to the latest available Home Assistant version.
- [ x ] I have cleared the cache of my browser.
- [ x ] I have tried a different browser to see if it is related to my browser.

## The problem
When an light is dimmed, the bulb icon is getting darker. When turned off while dimmed the icon is darker than normal.
![SmartSelect_20200322-160532_Home Assistant](https://user-images.githubusercontent.com/12710193/77252860-fc0e3c00-6c56-11ea-9f59-f43fabea2f6e.jpg)

## Expected behavior
The icon should have the right color (like the others).

## Steps to reproduce
Add a dimmable light. Dimm it down to 5-10% and then turn it off.

## Environment
Home Assistant v0.107.5. The issue is on mobile phones (ios/android) and with every browser.

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## Problem-relevant configuration
Should not be configuration relevant.

```yaml

```

## Javascript errors shown in your browser console/inspector
None.

```txt

```

**Comment by iantrich** [comment]
Please check Developer Tools > States? Is brightness still an attribute when off?

If so that would be an integration issue believe as that should be reported when off, to my knowledge. What light integration are you using?

**Comment by ochstobi** [comment]
I have a MQTT integration for a zigbee device. In fact the brightness is still an attribute when turned off. I think it is to retain the brightness so it is in the same dimmed state when turned on again.

==Turned on at full brightness==
brightness: 255
linkquality: 0
state: 'ON'
friendly_name: Licht Wohnzimmer (dimmbar)
supported_features: 41

==Turned off while full brightness
brightness: 255
linkquality: 0
state: 'OFF'
friendly_name: Licht Wohnzimmer (dimmbar)
supported_features: 41

==Turned on while dimmed
brightness: 43
linkquality: 0
state: 'ON'
friendly_name: Licht Wohnzimmer (dimmbar)
supported_features: 41

==Turned off while dimmed==
brightness: 43
linkquality: 0
state: 'OFF'
friendly_name: Licht Wohnzimmer (dimmbar)
supported_features: 41

**Comment by iantrich** [comment]
Well there's your answer then

**Comment by iantrich** [comment]
So right here https://github.com/home-assistant/frontend/blob/dev/src/components/entity/state-badge.ts#L87 we should add a check that state is 'on'

**Comment by ochstobi** [comment]
I could not imagine that everyone else is setting the brightness to 255 before simply turning the light off. Simple case is you dimm the light in home assistant and later on you tap the physical switch which turns your light off.

Shouldn't there be a fix color when turned off instead of going darker from brightness - x?

**Comment by iantrich** [comment]
@ochstobi most integrations do not provide brightness when they are 'off', but the fix is just what I posted earlier and fairly simple
