### ISSUE TITLE
Stack card editors - outline card upon hover or selection

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5318]
## The request

When you're in Configure UI mode, there's a helpful blue highlight / outline when hovering over 
cards in a view. I think this would be a good idea to apply to the Horizontal and Vertical Stack editors as well.

The idea being when you either hover your mouse over a card number **or** select it, the card on the right would be outlined so you're always aware what you're about to edit or actively editing. 

![image](https://i.imgur.com/mP5lqTe.png)

This also makes re-ordering a card using the arrow buttons a little bit nicer, because with an outline you'd be able to more easily track its position as it moves around.

**Comment by zsarnett** [comment]
This isn't really possible because they are two separate elements. Relating the two would be difficult and not sure if its worth for this feature
