### ISSUE TITLE
On-hold action on the light card.

### ISSUE THREAD

**Issue by Gandohr** [home-assistant/frontend#5319]
## The request
  I would like to have a hold action on the light card.
  I have some lights created by light platform group that contain multiple light entities.
  My office has a spot with 3 bulbs. Bulbs are named light.office_bulbX (1,2,3) and with a group
  i create a entity called light.office to switch all 3 at once.
  i use a custom:slider-entity-row to show light.office.
  the toggle is used to turn on and off, a single click opens the default history popup
  and a on_hold action it shows a browser_mod popup that shows a custom:slider-entity-row
  for the 3 lights that are in there, so i can manage them individually.
  this works great. But i wanna start using the "new" Light card.
  But this has no on_hold option, so no way to get a popup with the single bulbs.

## The alternatives
  No alternatives

**Comment by bramkragten** [comment]
Please fill out the template.

**Comment by iantrich** [comment]
@Gandohr I think this is a good addition, but FYI the more-info can be brought up using the overflow button on the top right of the light card

**Comment by Gandohr** [comment]
> @Gandohr I think this is a good addition, but FYI the more-info can be brought up using the overflow button on the top right of the light card

That i know, but i want a single click to give the more-info, but a hold to show a browser_mod popup. And since there is no hold_action i cannot have it to give the popup.

**Comment by iantrich** [comment]
Oh no, I don't think the tap action should ever change...

**Comment by Gandohr** [comment]
> Oh no, I don't think the tap action should ever change...

i don't wanna change the tap_action i'm asking to add a hold_action.
there many items that have a tab_action, double_tap_action and hold_action

**Comment by iantrich** [comment]
Yeah but this card is very specific. I think the tap action should always be to toggle the light

**Comment by Gandohr** [comment]
> Yeah but this card is very specific. I think the tap action should always be to toggle the light

I think we are going in circles.
Yes the tab action should be and stay the tab action. But on the 3 little dots that give you a more-info box and that have absolutely nothing to do with the tab action on the light icon itself. I would like to have a option to show something else on an on hold action.

What don’t you get?

**Comment by Gandohr** [comment]
Why do you close this?
it's a valid request, what is it you don't get in this question request.
Ian keeps going back to the single tab on the icon itself, that has nothing to do with the request.
If you don't understand the request please ask for more details, but to just close it is a bit harsh
will send you the video as well

**Comment by bramkragten** [comment]
Because it was implemented

**Comment by Gandohr** [comment]
> Because it was implemented

Lol well that's a good reason indeed, i stand corrected :)
thanks

**Comment by Gandohr** [comment]
> Because it was implemented

Does not seem to work.
Waited on an update, still does not seem to work.

**Comment by bramkragten** [comment]
It does, I tested it. Please show your config and what you did and what the results are.

**Comment by Gandohr** [comment]
> It does, I tested it. Please show your config and what you did and what the results are.

This is what i have on the light
----
`          - type: horizontal-stack
            cards:
              - type: light
                entity: light.huiskamer_staandelamp
              - type: light
                entity: light.kantoor_plafond
                hold_action:
                  action: call-service
                  service: browser_mod.popup
                  service_data:
                    title: Kantoor
                    style:
                      border-radius: 20px
                      min-width: 500px
                    card:
                      type: entities
                      entities:
                        - type: custom:slider-entity-row
                          name: Kantoor 1
                          entity: light.kantoor_1
                          toggle: true
                        - type: custom:slider-entity-row
                          name: Kantoor 2
                          entity: light.kantoor_2
                          toggle: true
                        - type: custom:slider-entity-row
                          name: Kantoor 3
                          entity: light.kantoor_3
                          toggle: true
              - type: light
                entity: light.slaapkamer`

i use the same on a custom slider row that works
---
`              - type: custom:slider-entity-row
                entity: light.kantoor_plafond
                toggle: true
                hold_action:
                  action: call-service
                  service: browser_mod.popup
                  service_data:
                    title: Kantoor
                    style:
                      border-radius: 20px
                      min-width: 500px
                    card:
                      type: entities
                      entities:
                        - type: custom:slider-entity-row
                          name: Kantoor 1
                          entity: light.kantoor_1
                          toggle: true
                        - type: custom:slider-entity-row
                          name: Kantoor 2
                          entity: light.kantoor_2
                          toggle: true
                        - type: custom:slider-entity-row
                          name: Kantoor 3
                          entity: light.kantoor_3
                          toggle: true`

**Comment by bramkragten** [comment]
Cleared your cache?

**Comment by Gandohr** [comment]
> Cleared your cache?

Yup
Tried on my iMac in safari, chrome and firefox i never use.
on the iPad and the iPhone.

**Comment by iantrich** [comment]
Try with something other than browser-mod, to eliminate that as a possibility. I just tried the following on the demo site and works as expected. https://demo.home-assistant.io/#/lovelace/0

```yaml
type: button
tap_action:
  action: toggle
hold_action:
  action: call-service
  service: light.toggle
  service_data:
    entity_id: light.living_room_lights
show_icon: true
show_name: true
entity: light.kitchen_lights
```

**Comment by iantrich** [comment]
> But on the 3 little dots that give you a more-info box and that have absolutely nothing to do with the tab action on the light icon itself.

The hold/double-tap actions are on the icon, not the vertical dots

**Comment by Gandohr** [comment]
> > But on the 3 little dots that give you a more-info box and that have absolutely nothing to do with the tab action on the light icon itself.
> 
> The hold/double-tap actions are on the light icon, not the vertical dots

Ahh that's it, thanks mates (both of you) works like a charm now
