### ISSUE TITLE
Custom element doesn't exist: hui-alarm-panel-card / hui-picture-glance-card.

### ISSUE THREAD

**Issue by SamPhoenix91** [home-assistant/frontend#5320]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem

Since 107 update, sometimes I get the error messages:
Custom element doesn't exist: hui-alarm-panel-card 
Custom element doesn't exist: hui-picture-glance-card.

My cards are in custom cards, which load properly.

## Expected behavior

Cards to load properly

## Steps to reproduce

  1. Add glance/alarm card inside stack card.
  2. Refresh page

## Environment

Frontend version: 20200318.1 - latest

- Home Assistant release with the issue: 107.4
- Last working Home Assistant release (if known): 106.x
- Browser and browser version: Chrome
- Operating system: Win 10

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
#4984
