### ISSUE TITLE
iframe: allow adding/defining custom HTTP headers - e.g. for transmitting auth tokens

### ISSUE THREAD

**Issue by mirko** [home-assistant/frontend#5323]
## The request
iframe card: allow adding custom headers to HTTP request.

## The use case
Particular web applications, which one migt want to include as card, require authentication.
While entering username/password is far from optimal because of several and obvious reasons, authentication tokens - like being used by home-assistant itself - are used, and passed with every request, potentially defining very fine-grained permissions, without giving away the whole account.
Those tokens are often transferred as HTTP header - e.g. grafana uses "Authorization: Bearer [..]".

## The alternatives
Logging in with username and password, giving away the whole account and having to do it on every device and potentially - depending on lifetime/cookie settings - often, if not every time.

**Comment by zsarnett** [comment]
This is not possible in Iframes
