### ISSUE TITLE
First view gets shown by default when it is not visible for user

### ISSUE THREAD

**Issue by snakuzzo** [home-assistant/frontend#5327]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## Expected behavior

At the first access first view is shown to everyone even the visibility is set only for some users. Users are always redirected on /lovelace/0,
If any user try to access other views changing index in the url (eg. /lovelace/1, lovelace/2 etc.), view is shown even the visibility is set to off

## Steps to reproduce

Set different visibility for different users 

## Environment

- Home Assistant release with the issue: 0.107.5
- Last working Home Assistant release (if known): never worked fine
- Browser and browser version: all browsers
- Operating system: all OS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
It is only used to hide views from the navigation, it will not restrict a user in any way to access a view by directly navigation to it.

**Comment by snakuzzo** [comment]
ok :(

**Comment by snakuzzo** [comment]
Ok, but what about the first view ?
If my first view (/lovelace/0) is hidden for a user, why show /lovelace/0 for that user ?

**Comment by Fritz4all** [comment]
At the moment hiding the default_view (first view) results in showing the default_view (first view).

I have 2 Views in one dashboard : 

Dashboard : Overview (default but took control)
URL View 1 : /lovelace/default_view  <-- Hidden for users
URL View 2 : /lovelace/test                <-- Not hidden for users

When clicking in the left panel on the "Overview" dashboard or browsing to http://%url%/config/lovelace/ always results in showing the default_view.

Tested this with versions 0.107.5, 0.107.6, 0.107.7 and with the latest 0.108.0.dev20200330 build

**Comment by overkillthemighty** [comment]
Can confirm this behavior. I wanted to make a page visible to just one person and have it the default view (Unlock a particular door) and everyone else drop on the default control page. I am not worried about security as much as convenience in this case, I have other things in place for that. It is just super inconvenient that HA can't just drop a user to the first available page rather than the first page they have view permissions set to.
