### ISSUE TITLE
Make resources visibly clickable in Lovelace Dashboards resource editor

### ISSUE THREAD

**Issue by akasma74** [home-assistant/frontend#5333]
## The request

Currently Resources tab looks like this
![Screen Shot 2020-03-24 at 22 04 57 (2)](https://user-images.githubusercontent.com/13675855/77481593-e1d18b00-6e1b-11ea-9817-ecbfe173cd27.png)
and there is no sign that the individual resources are clickable/editable as the mouse cursor does not change shape to a hand or whatever when placed above resource, which makes UI very non-intuitive.

## The alternatives

By trial I discovered it's possible to edit a resource by clicking it but it's a poor design.

**Comment by akasma74** [comment]
Adios field marshall

**Comment by zsarnett** [comment]
We should make this univeral for all tables. Pointer Cursor if clickable
