### ISSUE TITLE
Can't save default Lovelace Dashboard

### ISSUE THREAD

**Issue by benas1989** [home-assistant/frontend#5334]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

I'm trying new homeassistant features. I create two lovelace dashbords and try to set one as default. 
But when I log out and log in again. Settings are not saved.
## Expected behavior
The settings are saved. And setting the dashboard as admin only would not show it to ordinary users

Creating dashboards:
<img width="1792" alt="1" src="https://user-images.githubusercontent.com/6152093/77486672-0c7e0c80-6e39-11ea-8da2-304167ac8993.png">

Add user:
<img width="1788" alt="2" src="https://user-images.githubusercontent.com/6152093/77486676-0daf3980-6e39-11ea-98cf-6bbc7f05e62a.png">

Set "Home_admin" as default UI and admin only. Overview tab disappears.
<img width="1791" alt="3" src="https://user-images.githubusercontent.com/6152093/77486677-0e47d000-6e39-11ea-913d-c2605eb041fb.png">

Log out. Login as admin again. Overview tab is showing again. And "Home_admin" is not default.
<img width="1790" alt="5" src="https://user-images.githubusercontent.com/6152093/77486679-0e47d000-6e39-11ea-8d0e-c6729da5fd1e.png">

<img width="1792" alt="6" src="https://user-images.githubusercontent.com/6152093/77487123-3a178580-6e3a-11ea-94bf-3cf68b96b4d9.png">

Same with regular user. The Overview tab is displayed again.
<img width="1792" alt="4" src="https://user-images.githubusercontent.com/6152093/77486681-0ee06680-6e39-11ea-9752-3a9e687cccec.png">

## Steps to reproduce

1. Create 2 dashboards
2. Create user not admin
3. Set one of created dashboard as default and admin only.
4. Log out. And login.

## Environment

- Home Assistant release with the issue: 0.107.6
- Last working Home Assistant release (if known):
- Browser and browser version: Google Chrome 80.0.3987.149 (Official Build) (64-bit)
- Operating system: MacOS Catalina 10.15.3

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

When I try to set "Home_admin" as default dashboard:
<img width="1791" alt="7" src="https://user-images.githubusercontent.com/6152093/77487718-cd04ef80-6e3b-11ea-8251-347cdac6e6a0.png">

**Comment by bramkragten** [comment]
This is setting is not user specific but browser specific, we store it in the localStorage of your browser. If you logout we clear this storage.

**Comment by benas1989** [comment]
No logic. If you have the setting set to allow only admin then it cannot be stored for one session.

**Comment by bramkragten** [comment]
Allow admin is not just for the session. I was talking about the default dashboard setting.

**Comment by prnewman** [comment]
Clearing cookie storage fixed it for me. You can also try incognito mode.
