### ISSUE TITLE
Can't set default dashboard unless user is set as "Administrator"

### ISSUE THREAD

**Issue by ttaidapos** [home-assistant/frontend#5345]
- [ X] I have updated to the latest available Home Assistant version.
- [X ] I have cleared the cache of my browser.
- [X ] I have tried a different browser to see if it is related to my browser.

## The problem
If you have multiple dashboards and multiple users, with the users being part of "users" group vs. 
"Administrators", they can't browse to configuration > lovelace dashboards to select a default dashboard. You have to temporarily make them member of administrators, make the change, and then revert them to the "users" group.

## Expected behavior
Users should be able to select their default dashboard from their user configuration.

## Steps to reproduce
1.  Have user try to change default lovelace dashboard being a member of "users" group.

## Environment
Rasbian
RPi4

- Home Assistant release with the issue:  106.x
- Last working Home Assistant release (if known):  Never, this was introduced with multiple lovelace dashboards
- Browser and browser version:  any
- Operating system:  any

## Problem-relevant configuration
NA

## Javascript errors shown in your browser console/inspector
NA

## Additional information
NA

**Comment by bramkragten** [comment]
#5223

**Comment by ttaidapos** [comment]
I created this because #5223 is a feature request but it's really a bug.  We can keep 5223 if we tag it as an issue instead of a feature request.

**Comment by bramkragten** [comment]
It is not a bug, it is just not implemented.

**Comment by ttaidapos** [comment]
> It is not a bug, it is just not implemented.
It is an issue because it's not implemented :) Regardless you can do whatever you like with this.  I just see people running into issues forgetting to revoke membership from administrators and mucking up their hass.  You'll be amazed on what a 1yr old can click through on a unlocked phone :)
