### ISSUE TITLE
Drag-Drop Cards

### ISSUE THREAD

**Issue by ttaidapos** [home-assistant/frontend#5346]
## The request
Drag-drop functionality of cards instead of default logic auto-stacking.  End-users should be able to drag-drop cards to a "sticky" position and enumerate them (1,2,3.....9) for ordering, not mutually exclusive.  This will achieve the requirement of keeping one lovelace dashboard instead of 2, 1 for mobile and 1 for browsers and/or tablets.  This reduces configuration maintenance with configuring cards across multiple dashboards.

## The alternatives
1.  Custom vertical stack in card and ordering card.
-You lose all lovelace GUI functionality with any combination of customizations.
-Harder to maintain update cards
-Reconfiguring required every time to add/remove cards and sizes

## Additional information
Google Keep has a similar experience as lovelace but it's more forgiving but it does have drag-drop.

**Comment by zsarnett** [comment]
#3895
