### ISSUE TITLE
Translation: Add Korean to Lokalise

### ISSUE THREAD

**Issue by techinpark** [home-assistant/frontend#5347]
## The request

There is no Korean translation, and I would like to work on one.

English Name : Korean
Native Name : 한국어

## Additional information
Related Issue: 
- https://github.com/home-assistant/home-assistant-iOS/issues/572

**Comment by techinpark** [comment]
@zsarnett Any updates?

**Comment by bramkragten** [comment]
We already have Korean

https://github.com/home-assistant/frontend/blob/dev/src/translations/translationMetadata.json#L92-L93

You might not have access to it on Lokalise, what is your username on Lokalise?
