### ISSUE TITLE
also renaming the entity id's of your entities after updating device name

### ISSUE THREAD

**Issue by melvinve** [home-assistant/frontend#5355]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem

Renaming a device will ask for also renaming all entity's (Ok, or Cancel).
When chosen no, it still renames all entities.
![image](https://user-images.githubusercontent.com/45721379/77834890-89b2c580-7148-11ea-865b-bd5a6bb1fb6f.png)
![image](https://user-images.githubusercontent.com/45721379/77834935-e57d4e80-7148-11ea-8ba6-c7566fe84204.png)

## Expected behavior

Expect to not change all entity names
![image](https://user-images.githubusercontent.com/45721379/77834956-178eb080-7149-11ea-9540-49d3ffd10d2c.png)

## Steps to reproduce

1. Click Configuration
2. Click Devices
3. Select a devie
4. Click settings top right cornre
5. Change Device name
6. Click Cancel when asked to also rename all entities of this device.

## Environment

- Home Assistant release with the issue:
HA supervised on CentOS7 (virtual on proxmox)
arch | x86_64
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 3.10.0-957.27.2.el7.x86_64
python_version | 3.7.7
timezone | Europe/Amsterdam
version | 0.107.7
virtualenv | false

- Last working Home Assistant release (if known):
  unknown
- Browser and browser version:
  Edge 80.0.361.69
  Chrome 80.0.3987.149
- Operating system:
  Windows 10 Enterprise 1803

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
The entity names will always be renamed, it asks about the entity id's.

**Comment by melvinve** [comment]
I see, sorry about that. How about when it's not changing the entity id's when choosing ok? Not sure if that is normal behavior or do I need to create another issue.

**Comment by bramkragten** [comment]
Please share an example of the device name before and after and the entity id. It will only rename it if it matches the old name.

**Comment by melvinve** [comment]
I understand, you last sentence makes everything clear to me and works as you say: "It will only rename it if it matches the old name." I think this should be more clear in the UI.
