### ISSUE TITLE
When adding a lovelace panel, help text for URL field is invalid

### ISSUE THREAD

**Issue by blindahl** [home-assistant/frontend#5356]
![lovelace_panel](https://user-images.githubusercontent.com/545274/77846845-32007280-71b9-11ea-8409-f047415cafe6.png)
Complete Enligsh string is "The URL should contain a - and cannot contain spaces or special characters, except for _ and -" but underscore is not accepted as a valid character.

**Comment by bramkragten** [comment]
You can change this yourself: <https://developers.home-assistant.io/docs/internationalization_translation>

**Comment by bramkragten** [comment]
Btw, the underscore is accepted, but it is missing a `-`

**Comment by blindahl** [comment]
So there have to be a hyphen in the string? Why's that?

**Comment by bramkragten** [comment]
To prevent people from overridden (future) build-in panels

**Comment by blindahl** [comment]
And if that's the case the auto generated url lack a hyphen I would argue.

**Comment by bramkragten** [comment]
The auto-generated URL has a hyphen?
![image](https://user-images.githubusercontent.com/5662298/77847686-48113180-71bf-11ea-9369-ae1dea0f0a30.png)

**Comment by blindahl** [comment]
Ok, I'll do some more testing to reproduce it.  The reason I ran into this issuein the first place was that the url generated didn't have it.
