### ISSUE TITLE
Invalid addon appearing in sidebar

### ISSUE THREAD

**Issue by kaizersoje** [home-assistant/frontend#5370]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Hi,
I am getting this Pi-hole addon appearing in my sidebar.
![hassio sidebar](https://user-images.githubusercontent.com/54566217/77971129-a9f5a680-7339-11ea-81bd-5ef4dddc7d51.png)

When I click on the sidebar addon, I get the following screen.
![addon screen](https://user-images.githubusercontent.com/54566217/77971155-b679ff00-7339-11ea-88e6-06a3f59350b5.png)

However, this addon is not installed.
![hassio addons](https://user-images.githubusercontent.com/54566217/77971169-bed23a00-7339-11ea-9f8e-d0bf9e5cdc7d.png)

## Expected behavior

As this addon does not exist, I would expect this to not appear in the sidebar.

## Environment

- Home Assistant release with the issue: 
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome 80.0.3987.149
- Operating system: MacOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by frenck** [comment]
Just to be sure it is caused by add-on and not configuration?
As in, the Pi-hole add-on never used that icon for example...

Furthermore, that IP address shown in the error message: `192.168.0.10` is not an IP ranged used by add-ons. Add-on uses the internal docker network, which would start with `172.16.x.x`.

So my guess would be that you have a `panel_iframe` in your Home Assistant configuration.

**Comment by kaizersoje** [comment]
`192.168.0.10` is the IP address of my RPi box. The only `panel_iframe` defined in the configuration is for the floorplan. This is the link when I click on the addon option in the sidebar: https://xxx.xxx.x.xx:8123/pihole

**Comment by kaizersoje** [comment]
Frenck, I found the `panel_iframe` residing in one of the package files. Thanks for setting me off in the right direction.
