### ISSUE TITLE
IOS 9.3.5 - I can't log in to my Home Assistant. Stuck on initializing

### ISSUE THREAD

**Issue by victorvlm** [home-assistant/frontend#5376]
## Checklist

- [X ] I have updated to the latest available Home Assistant version.
- [X ] I have cleared the cache of my browser.
- [X ] I have tried a different browser to see if it is related to my browser.

## The problem

When I try to load Home Assistant on my iPad mini running IOS 9.3.5 it is stuck on initializing.
I tried clearing my browser and even factory reset the iPad.
Tried different browsers on my iPad (each time clearing my browser history and cache) but none work.
On my laptop and android tablet I have no problems.
## Expected behavior

I should be able to get the log in screen of HA and then go to my lovelace page.

## Steps to reproduce

1. Connect to wifi
2. Go to Safari
3. Go to HA server adress
4. It is stuck on initializing

## Environment

arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.19.97-v7+
python_version | 3.7.7
timezone | Europe/Amsterdam
version | 0.107.7
virtualenv | false

- Home Assistant release with the issue: 214
- Last working Home Assistant release (if known): Not sure but I think 98
- Browser and browser version: Safari
- Operating system: IOS 9.3.5

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Can you try Chrome? I don't think we support iOS 9 anymore...

And can you share console errors?

**Comment by victorvlm** [comment]
Because the ipad uses an old ios I can't install chrome.
I don't get any console errors.
This used to work but when I reinstalled home assistant I got this problem.

**Comment by DanielGrankvist** [comment]
I have the same issue.
I've tried
Both Safari and Chrome (incognito as well)
Accessing it by https://url/lovelace/states?es5
Changing conf to (frontend) javascript_version: es5

@victorvlm You can install old version apps in Appstore -> Purchased apps :)

**Comment by dgchurchill** [comment]
I've got the same issue too, trying to use Home Assistant from an iPad 2 which can only be updated to iOS 9.3.5. The behaviour has changed slightly with a recent release.

Testing with v0.109.4 / Frontend version: 20200427.2, the login page loads but doesn't show the username or password fields:
![Screen Shot 2020-05-05 at 21 50 29](https://user-images.githubusercontent.com/883857/81063907-08570b80-8f1c-11ea-9931-862c3aab4539.png)

From the dev console I see the following errors:
<img width="803" alt="Screen Shot 2020-05-05 at 21 55 43" src="https://user-images.githubusercontent.com/883857/81063499-3ee05680-8f1b-11ea-977c-3045b5fa66a5.png">

**Comment by dgchurchill** [comment]
Possibly need `import 'mdn-polyfills/Object.entries';` in `src/entrypoints/compatibility.ts`? Could be others I guess too. When I get a moment I'll get a build environment set up and try it out.

**Comment by dgchurchill** [comment]
I didn't end up looking any further into this. Instead I discovered Appdaemon/HADashboard which suits my needs better and supports iOS 9.3.5.

I also noticed that the Home Assistant frontend depends on Polymer v3 which does not support iOS 9 Safari. As such trying to get HA working on iOS 9 might be a futile endeavour?

**Comment by jptime** [comment]
I did a little testing and kept having to add more and more polyfills, but wasn't ever able to get pass that login screen on iOS9.  
I'll take a look at Appdaemon as an alternative @dgchurchill , good find!

**Comment by haegar33** [comment]
a similar error is now apparent on my iPad ioS 11.2 with HA V114. I will open a ticket for that

**Comment by P-Verbrugge** [comment]
Same here. Did a new install of Hassio and now I can't login using the app, safari and chrome browser on iOS. Works fine on MacOS.

**Comment by akloeckner** [comment]
I have the same issue. (iOS 9.3.5 on an old iPad). 

I'm using tileboard. But since that dashboard needs to authenticate with HA, it's not usabale currently on my iPad.

If old iOS is not supported anymore by the regular frontend, that's one (bad) thing. But the authentication should be suited to the most simple browsers, I believe.

**Comment by sobiso** [comment]
Guys you can still generate authtoken (generated from Home Assistant) and put it to tileboard config. Works on old iPad for me.

**Comment by akloeckner** [comment]
Security hint: That works, but isn't recommended, because the token is then stored in clear-text. So, make sure your tileboard is *not* accessible through the internet.

**Comment by sobiso** [comment]
Yes, I know about this, but I'm using only in my network.
