### ISSUE TITLE
Loading screen should be part of themes (to stop white loading screen melting eyeballs at night)

### ISSUE THREAD

**Issue by timdonovanuk** [home-assistant/frontend#5394]
## The request

Currently, despite using a dark theme, if you load HA at night, the bright white loading screen melts eyeballs until frontend loads and a dark theme kicks in.

As requested, here is a picture of my eyeballs melting before my dark theme kicks in:

![image](https://user-images.githubusercontent.com/8156439/78130342-0e376980-7411-11ea-9f38-3f7d8219ac24.png)

## The alternatives

Sunglasses?

**Comment by bramkragten** [comment]
Before we have the data we also don't have the theme, so we can't...

**Comment by Misiu** [comment]
@bramkragten what about local storage?
we only need like 2 variables: background-color and color (for text), those could be stored in local storage (from the last active theme).
This way while loading you will get the loading screen with colors from the last used theme.

**Comment by timdonovanuk** [comment]
Or the entirely non-theme route: most browsers, including on mobile devices, have inbuilt support for dark mode and a media query to check this (see: https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme).

**Comment by Misiu** [comment]
@timdonovanuk that's a good alternative!
What about IE11? It doesn't support this: https://caniuse.com/#search=prefers-color-scheme
BTW is IE11 supported by Home Assistant?

**Comment by timdonovanuk** [comment]
Also a simple user/profile option in HA to make the loading screen "dark mode" would also work!
