### ISSUE TITLE
Add text about Panel Mode not rendering badges

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5412]
## The request

When using Panel Mode on a view, it does not render the badges. But this is not mentioned anywhere in the UI editors. Perhaps it should be?

Had two different ideas / mockups. It could be added to the already existing descriptive text on the "Settings" tab of the view configuration:

![text](https://i.imgur.com/QtuGDwU.png)

Or it could be added to the "Badges" tab under the new badges preview (but this text would only be shown if Panel Mode toggle is on):

![preview](https://i.imgur.com/c99hqjn.jpg)

or maybe both places? I dunno.

**Comment by ludeeus** [comment]
This is described in the documentation <https://www.home-assistant.io/lovelace/dashboards-and-views/#panel>

**Comment by SeanPM5** [comment]
I'm aware of that but I don't think it should be necessary to search documentation when it comes to the user interface IMO. 

Ideally someone completely new could click on the "view demo" link and everything would either feel totally natural or be explained so there's no confusion.

There's already descriptive text next to the panel mode toggle, and a banner above the view when you're editing a view with panel mode on. These mention how cards get handled in this mode, but nothing about badges.

**Comment by danimart1991** [comment]
I like the idea. I think this is a Translation related issue, no frontend modification needed.
