### ISSUE TITLE
Actual theme aligned window frame color when use as installed PWA

### ISSUE THREAD

**Issue by Tamas-Toth-ebola** [home-assistant/frontend#5420]
## The request

Hello!

I would like to ask a not so standard but progressive question.

If we install HA in Chrome as PWA to use it like a native application without address-bar and other fripperies we get a relatively nice result like:

![image](https://user-images.githubusercontent.com/25765137/78278051-c3534a00-7515-11ea-9c91-d316c2ab1885.png)

The windows decorations aligned to the header of HA and basically as the color of the window frame is the primary color of HA the result has something like visual harmony.

BUT as HA is conceptionally themeable if we switch our theme to any other as the default the window decorations stay the same default HA primary color what is a little bit off like:

![image](https://user-images.githubusercontent.com/25765137/78278386-407ebf00-7516-11ea-8b94-8f06509a275a.png)

**Could it be possible to always use in such PWA working method the primary or the header color of the active theme for window decoration?**

If it would be possible the PWA could be really looks like always as a professional native app.

Thanks for your answer in advance!

**Comment by bramkragten** [comment]
If you set the theme from the backend this will be done.
