### ISSUE TITLE
Spacing on config flow progress indicator

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5421]
## The request

There's a new "please wait" text and progress indicator for config flows that take longer, which is nice, but the spacing can be tweaked / increased a little bit IMO.

There's plenty of spacing on all sides of this dialog, yet the text and circular progress indicator are super close and practically touching each other.

![image](https://i.imgur.com/xIiKgX0.png)

**Comment by timmo001** [comment]
Looks like this was remedied in #5500 

![Screenshot_20200411_163619](https://user-images.githubusercontent.com/28114703/79048113-a94ef100-7c12-11ea-8d45-e5b83ecfc026.png)
