### ISSUE TITLE
Search in data tables on mobile doesn't use all data

### ISSUE THREAD

**Issue by agneevX** [home-assistant/frontend#5435]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
Desktop UI shows the complete search result from the search query, whereas the mobile UI doesn't return the complete search result. 

<img width="855" alt="image" src="https://user-images.githubusercontent.com/19761269/78376441-f831d080-75eb-11ea-9e84-b3f4f49e206f.png">

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/19761269/78376499-0e3f9100-75ec-11ea-8a2b-cd20e4dac065.png">

## Expected behavior
Search result should be the same regardless of the device.
 
## Steps to reproduce

Search for `media_player` on desktop UI and mobile UI under `Entities`. 

## Environment 
- Home Assistant release with the issue: 0.107.7
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Safari
- Operating system: macOS

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
N/A

**Comment by shenxn** [comment]
It seems that this is because the search on mobile UI only uses names. I'll look into it.

**Comment by shenxn** [comment]
So I looked into the code. The problem is that the filter only uses columns that are displayed in the table. Since Entity ID is not a column on mobile, the filter will not use that. Still trying to find a good way to fix it.
