### ISSUE TITLE
Chips for user roles in View Visibility

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5439]
## The request

Idea inspired by the new Users panel design that has chips for the users role. 

Thought something similar might be useful on View Configuration -> Visibility tab as well? By default the active chip would be "Everyone" but you'd be able to click admins only / users only rather than doing it user by user.

![image](https://i.imgur.com/OtwvfZX.jpg)

In this mockup hitting the admins only chip would keep only "Parent" toggled, and save a couple clicks from having to toggle off all the other users.

**Comment by zsarnett** [comment]
Is this really that useful? How many admins/users will most people have that these would be useful? We would only be able to add buttons for this not admin only setting. It would set current admins and remove users. But if you add an admin later you would need to go back and update the visibility

**Comment by SeanPM5** [comment]
I'd guess the average family would maybe have 4 accounts? Two admin accounts for spouses, two regular user accounts for their children. It'd only be saving one click in that scenario though, so yeah, not overly useful.

This becomes more beneficial the more accounts you have. Those with larger families and/or those who create accounts for non-family members that need access to their home (babysitter, cleaning person, caretaker/nurse, dog walker, etc). Probably not super common currently, so I'll close this, but might be worth revisiting down the line.
