### ISSUE TITLE
Media control: select other background color if primary is black due to black bars in artwork.

### ISSUE THREAD

**Issue by FredericMa** [home-assistant/frontend#5449]
## The request

Not really sure if I should consider this as a feature request or bug report...
I'm using the new media control card and noticed that a lot (not all) of the art images coming from youtube contain a black bar at the top and bottom (see additional information). This makes black always the background color in that case since it is the dominant color.
The android media player on my phone selects the second color as background in this case.
I would propose to select the second dominant color as background color in case the primary color is pure black.
I'm not very familiar with JavaScript, otherwise I would have made a PR for this.

## The alternatives

Keep as is.

## Additional information
An example on HA:
![image](https://user-images.githubusercontent.com/7840263/78450699-d33b6d00-7680-11ea-9f21-b14875029075.png)
Same video on my phone:
![image](https://user-images.githubusercontent.com/7840263/78450749-1eee1680-7681-11ea-96da-67af8598da37.png)

The background image:
https://i.ytimg.com/vi/gUnK_xeUPgg/hqdefault.jpg
The original video:
https://www.youtube.com/watch?v=gUnK_xeUPgg

**Comment by zsarnett** [comment]
![image](https://user-images.githubusercontent.com/18730868/78460288-99249800-768d-11ea-89a6-66f6093311b4.png)

This doesn't occur for me on Chrome. Though different browsers will have different results

**Comment by FredericMa** [comment]
Hmm.. that's weird.
I see this all my devices... I have a Lenovo Tab 4, Galaxy S8 and Chrome on Windows 10.
I also tested it in Firefox and they all show the same way.

Any hints on why I see this? Could it have something to do with the fact I'm running HA on a Windows machine?

**Comment by zsarnett** [comment]
We cant fix this as different browsers/devices view images differently
