### ISSUE TITLE
Conditional Card Issue

### ISSUE THREAD

**Issue by browetd** [home-assistant/frontend#5450]
## Environment

- Home Assistant Core release with the issue: 0.107.7
- Last working Home Assistant Core release (if known): Unknown
- Operating environment (Home Assistant/Supervised/Docker/venv): venv with python 3.7.3
- Integration causing this issue: -
- Link to integration documentation on our website: - 

## Problem-relevant `configuration.yaml`

```lovelace yaml extract
        - type: conditional
          conditions:
            - entity: automation.at_home_gps
              state: 'off'
            - entity: automation.at_home_wifi
              state: 'on'
          card:
            type: entity-filter
            entities:
              - device_tracker.b0_6f_e0_3f_ec_28
              - device_tracker.b0_6f_e0_3f_dd_b8
            state_filter:
              - 'home'
            card:
               type: glance


```

## Traceback/Error logs

```txt

```

## Additional information

![2020-04-04 14 22 55](https://user-images.githubusercontent.com/46415133/78450873-1e09b480-7682-11ea-8ca2-c89a7f84cb05.jpg)
![2020-04-04 14 23 28](https://user-images.githubusercontent.com/46415133/78450880-2530c280-7682-11ea-806a-e4a6b0121b12.jpg)

**Comment by bramkragten** [comment]
This should be fixed in 0.108
