### ISSUE TITLE
Button card does not display icon if a picture is used

### ISSUE THREAD

**Issue by akasma74** [home-assistant/frontend#5454]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Button card does not display a picture set using `icon` configuration variable but it does display if a mdi icon is used.

## Expected behavior

The button should display both icons and pictures as per the documentation.

## Steps to reproduce
1. Click Configure, "+" and Button card
2. Add `icon: /local/icon.png` (you need to create it beforehand and save to <config>/www/)
3. Save the card
4. A button with name only will be displayed
5. Click Edit
6. Change `icon`'s value to mdi:door
7. Save the card
8. A button with the icon and a name will be displayed

## Environment

- Home Assistant release with the issue: 0.107.7
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome
- Operating system: OS X

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
The documentation does not say that it will allow images in the `icon` field. The documentation states that an Icon can be used to overwrite the entity picture or entity icon
