### ISSUE TITLE
Theme dropdown displays behind top app bar on Profile page (on mobile)

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5461]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

With the placement of the "Theme" dropdown on the profile page, it makes the dropdown open upwards. But this also makes the Backend-selected option appear under the top app bar. From what I can tell this occurs if you have ten or more themes installed.

![image](https://i.imgur.com/rg0VIwV.png)

This happens in both portrait and landscape on my iPhone 11 Pro.

If you scroll the page first, so that "Theme" dropdown is near the top, it will make the dropdown open downwards and that makes all the options available. But I suspect most people won't think of this workaround, if the dropdown is visible without scrolling they're just going to tap that immediately and encounter this bug.

![image](https://i.imgur.com/wqrJ38l.png)

## Expected behavior

Dropdown should display ABOVE the top app bar, or be forced to open downwards or something, so the user can access every option.

## Steps to reproduce

1. Have 10 themes installed
2. Open theme dropdown on mobile

## Environment

- Home Assistant release with the issue: 0.108.0
- Last working Home Assistant release (if known): 
- Browser and browser version: Mobile App iOS
- Operating system: iOS 13.4

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
This happens with ever list object if its close enough to the app header. Create a smaller profile card in an empty view and click the more options icon. it also displays behind the header
