### ISSUE TITLE
Autofill passwords (in Safari) 

### ISSUE THREAD

**Issue by meijerpeter** [home-assistant/frontend#5475]
## The request

It would be very nice if the Hassio login page would use the autofill / autocomplete options of the Safari browser, and perhaps other browsers as well. Currently, when the login page appears, I don't get the option to autofill the password saved in my Keychain (on my Mac). This prevents most users to use generated passwords.

Apple has described the solution here: https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element

**Comment by outadoc** [comment]
Hi, I think this is related to #3133. Same behavior on almost all browsers as far as I can tell.
