### ISSUE TITLE
input_number behaves erratically when converting temperature units

### ISSUE THREAD

**Issue by mvsjes2** [home-assistant/frontend#5482]
Using Lovelace. When input_number unit_of_measurement is °C and the user selects °F in the 'general/unit system' server config settings, the results on the UI for that entity are erratic. When adjusting the slider position, the slider jumps around. It appears that it is converting the °C number entered via the slider to °F and immediately resetting the input_number value to the converted, larger value.

To solve it simply make the unit_of_measurement and unit system agree.

arch | aarch64
dev | false
docker | false
hassio | false
os_name | Linux
python_version | 3.6.9
timezone | America/Halifax
version | 0.103.6
virtualenv | true

**Comment by zsarnett** [comment]
Please create a new issue and fill out the template with images
