### ISSUE TITLE
Light Card - double tap action impossible to activate

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5485]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Light card supports double tap action in 0.108 now, but isn't this impossible to ever activate? Since it's always toggling a light entity, tapping twice will just turn the light off and back on right?

Hold action makes sense but I don't think double tap will work properly with this card? Unless I am missing something. 

## Expected behavior

Remove double tap from Light card editors if it's not going to work

## Steps to reproduce

1. Add and configure a Light card
2. Use the card editor to add double tap action
3. See that it doesn't work

## Environment

- Home Assistant release with the issue: 0.108.0b
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome
- Operating system: macoS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
It works here?

**Comment by SeanPM5** [comment]
Hmm. After testing some more, it seems to work after you save the card, but not in the Card Editor preview? 

to reproduce: 

1. Configure UI > Light card (but don't save it yet)
2. Add double tap action of more-info
3. Double tap the light card in preview, it will not activate more info but instead just toggle light
4. Now save the card, the double tap action will work in the Lovelace view, and will work in the preview after you edit the card.
