### ISSUE TITLE
Logbook the latest entry missing

### ISSUE THREAD

**Issue by pedroke** [home-assistant/frontend#5490]
## The problem

Since upgrade to 0.107.7 the logbook doesn't show the latest entry. 
Always only the single - top - latest entry is missing.
Refresh does not help.
As soon as the new event happens, the last-1 entry is shown, but again the newest one is missing.

## Environment

- Home Assistant Core release with the issue: 0.107.7
- Last working Home Assistant Core release (if known): 0.106.6
- Operating environment (Home Assistant/Supervised/Docker/venv): Supervised
- Integration causing this issue: Logbook
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

Nothing in logs.. simply all entries correctly in logbook except the single latest one.
```txt

```

## Additional information
Hass configured with MariaDB addon.

**Comment by frenck** [comment]
Move to the frontend as per request.
