### ISSUE TITLE
resources page generates error in HA log (Chrome)

### ISSUE THREAD

**Issue by akasma74** [home-assistant/frontend#5492]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

If I navigate to Configuration -> Lovelace Dashboards and click on Resources tab at the top (http://hassio.local:8123/config/lovelace/resources), I get an error in HA log file. It happens every time I open or reload that page (and the error appears several seconds after the page is rendered). It doesn't seem to affect anything though.

> ERROR (MainThread) [frontend.js.latest.202003181] http://hassio.local:8123/config/lovelace/resources:0:0 ResizeObserver loop limit exceeded

I can see no such errors if I open this page in Safari 11.1.2 (11605.3.8.1).

## Expected behavior

There should be no error.

## Steps to reproduce
0. Make sure you have some resources defined
1. Click on Configuration
2. Click on Lovelace Dashboards
3. Click on Resources tab
4. Wait a couple of seconds
5. Open HA log file
6. It should have that ERROR from frontend

## Environment

- Home Assistant release with the issue: 0.107.7
- Last working Home Assistant release (if known):
- Browser and browser version: Version 81.0.4044.92 (Official Build) (64-bit)
- Operating system: OS X 10.11.6

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt
Uncaught TypeError: Cannot read property 'state' of undefined
    at HTMLElement.entityIdChanged (developer-tools-state.js:250)
    at HTMLElement.<anonymous> (template-stamp.js:87)
    at r (fire_event.ts:76)
    at ha-entity-picker.ts:240
```

**Comment by bramkragten** [comment]
Please check for Javascript errors shown in your browser console/inspector

**Comment by akasma74** [comment]
sorry, updated above

**Comment by bramkragten** [comment]
Mmm ok, that doesn't look related. So you get that error in your log but don't see anything other than that in your console?

**Comment by akasma74** [comment]
It's most likely unrelated as I don't see it anymore. No errors at all in console but an error in HA log, take a look
![Screen Shot 2020-04-08 at 14 31 38 (2)](https://user-images.githubusercontent.com/13675855/78790121-fda16900-79a5-11ea-9bf8-77b502cfcce7.png)

**Comment by andriej** [comment]
I can see this error after adding card-tools and flower-card to HA.
On my PC everything loads and works fine (thus I can't see any errors in console of browser) but on mobile app (Android) I get constant "Custom element doesn't exist: flower-card" and this error showed in logs.

Can't make Android app to reload the UI and load addon, have tried reinstaling, changing directory from HACS to direct install, killing app etc.

**Comment by bramkragten** [comment]
I'm going to close this, as it is most likely a custom card that causes this. If you have more info please open a new issue.
