### ISSUE TITLE
Monoprice: zones 21-26 and 31-36 do not show up in Lovelace starting from 0.108

### ISSUE THREAD

**Issue by johanjongsma** [home-assistant/frontend#5507]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I have two HA-setup’s both using the Monoprice integration. With the introduction of the set up of the integration through the Integration page (added in 0.108), only devices 11-16 show up in Lovelace. Devices 21-26 and 31-36 are shown as zones in the details page of the integration, but nowhere else. I did enable ‘show disabled entities’, although the entities should not be disabled: they are active. The integrations worked fine before 0.108.

Result is that zones 21-26 and 31-36 are no longer controllable, not with the new nor with this old configuration.

https://user-images.githubusercontent.com/44827424/78830847-a35cd400-79b6-11ea-9427-0227f8141aee.png
https://user-images.githubusercontent.com/44827424/78830932-c9827400-79b6-11ea-9913-51634437e703.png

## Expected behavior

Display zones 21-26 and 31-36 in case the Monoprice amplifiers are stacked.
## Steps to reproduce

1. Remove the configuration from configuration.yaml
2. Add the Monoprice integration through 'integrations'

## Environment

- Home Assistant release with the issue: 0.108.0
- Last working Home Assistant release (if known): 0.107.7
- Browser and browser version: Chrome Version 81.0.4044.92 (Official Build) (64-bit)
- Operating system: Windows 10

I have two separate setups, one with 2 x monoprice amplifier and one with 3 x monoprice amplifier. The problem exists in both setups.

## Problem-relevant configuration

In 0.107 and before the integration worked fine and showed in configuration.yaml:
media_player:
```
  - platform: monoprice
    port: /dev/ttyUSB0
    zones:
      11:
        name: MP Kitchen
      12:
        name: MP Lanai
      13:
        name: MP Summer kitchen
      14:
        name: MP Dining
      15:
        name: MP Formal Living
      16:
        name: MP Office
      21:
        name: MP Master Bedroom
      22:
        name: MP Master Bathroom
      23:
        name: MP Master Loggia
      24:
        name: MP Foyer
      25:
        name: MP Florida Den
      26:
        name: MP Casita
    sources:
      1: 
        name: Chromecast 1
      2:
        name: Chromecast 2
      5:
        name: Volumio
```
## Javascript errors shown in your browser console/inspector

None

**Comment by johanjongsma** [comment]
@etsinko: this issue has not been resolved with 0.108.2.

**Comment by bramkragten** [comment]
I don't think this is a frontend issue. Please create an issue on the core repo.

**Comment by johanjongsma** [comment]
Issue opened in core.
https://github.com/home-assistant/core/issues/34035
