### ISSUE TITLE
Configuration Menu Reorganization

### ISSUE THREAD

**Issue by mat4444** [home-assistant/frontend#5511]
## The request
In the Configuration menu, I think it would be better to group the “Customizations” submenu with “Integrations, Devices, Entities and Areas”. It’s just a cosmetic or UX detail, but in my opinion, it would make more sense.

![](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/6/9/69459c09b8abc2fc4ef9ccf5301fca5bbb9f0a31.png)

**Comment by ludeeus** [comment]
Each "section" should only contain max 4 elements.

I think grouping it with lovelace (bot customizes things for the UI) is a better placement
![image](https://user-images.githubusercontent.com/15093472/81211763-241de880-8fd4-11ea-8125-362b09860c5a.png)

**Comment by zsarnett** [comment]
We are going to redesign this completely so I am closing this as its not related to the new design
