### ISSUE TITLE
Entity Row: Change Awning Controls to Arrows

### ISSUE THREAD

**Issue by PDekker** [home-assistant/frontend#5513]
@bdraco  please revert  #5309 an awning does not move horizontally

**Comment by bdraco** [comment]
@PDekker The retractable awnings I have fold horizontally so it makes sense to me.

Ideally we would be able to set the direction of movement as another property but that currently isn't possible.

**Comment by PDekker** [comment]
@bdrago are you sure what you have is called an awning? I don’t see any horizontally when I Google form them 

This is an awning: 
https://cdn.mydeal.com.au/22785/134898Black21.jpg

I use the RFlink integration

**Comment by bdraco** [comment]
@PDekker I agree the icons aren't perfect, but it does move horizontally, and it is expanding when you click the expand icon and collapsing when you hit the collapse icon. 

![Image](https://user-images.githubusercontent.com/663432/78928282-f2157700-7a65-11ea-905f-2c2e047c3979.jpg)

**Comment by PDekker** [comment]
@braco except it does not. Mine is expanding when you click the collapse button and collapses when clicked the expand button. 

Are you 100% sure you did not switch the icons around during implementation?

![8256E009-7CCD-4C1E-B58B-77F36287B66B](https://user-images.githubusercontent.com/1951545/78928719-6588aa00-7aa1-11ea-8672-c973eb9d3a91.png)

**Comment by bdraco** [comment]
It looks right to me.  rflink uses an assumed state so both open and close are always available.

Here is what a closed gate that doesn't use assumed state looks like:
<img width="282" alt="Screen Shot 2020-04-09 at 1 41 34 PM" src="https://user-images.githubusercontent.com/663432/78929372-e88d0e80-7a67-11ea-8435-fb2632ce7806.png">

**Comment by bdraco** [comment]
Rflink has an inverted setting (https://www.home-assistant.io/integrations/cover.rflink/#setting-up-a-kaku-asun-650-device). Is it possible that `type: inverted` needs to be set?
```
    entity_device_mapping = {
        # default cover implementation
        TYPE_STANDARD: RflinkCover,
        # cover with open/close commands inverted
        # like KAKU/COCO ASUN-650
        TYPE_INVERTED: InvertedRflinkCover,
    }
```
https://github.com/home-assistant/core/blob/dev/homeassistant/components/rflink/cover.py

**Comment by PDekker** [comment]
@zsarnett An awning is controlled with the same motor as a rolling shutter. Therfore Up arrow should be the collapse icon. 

@bdraco My assumption is that you used something like a shelly and switched the wires the other way around?

**Comment by zsarnett** [comment]
Awnings move horizontally. No matter the motor. I agree with @bdraco 

For an awning to collapse/retract (Not out, Not shading the area underneath) the collapse icon should be used. 
![image](https://user-images.githubusercontent.com/18730868/78930997-13309480-7a73-11ea-8fd8-55fcc0f359f4.png)

For an Awning to be opened (Out, Shading the area under it) the open icon should be used 
![image](https://user-images.githubusercontent.com/18730868/78931101-57239980-7a73-11ea-9448-45a149660baa.png)


These icons make much more sense to me when controlling an awning

**Comment by PDekker** [comment]
@zsarnett I disagree

The collapse icon should be used for /retract/not out/not shading/closed **UP**
The expand icon for /out/shading/open **DOWN**

The other way around just does not works in my head

The type: inverted sugestion does seem to work as a temp fix.

**Comment by ludeeus** [comment]
The frontend displays the correct icon for the action.

If this is wrong in your head, you have the `invented` option.
Or you can open a feature request to change it in the backend (core) on the forum.
<https://community.home-assistant.io/c/feature-requests>

**Comment by PDekker** [comment]
https://github.com/home-assistant/core/issues/26932
https://github.com/home-assistant/core/pull/23257

**Comment by zsarnett** [comment]
Looks like the issue is in Core already. The Icons are correct currently. They will need to be updated in the core as the issue there is discussed
