### ISSUE TITLE
The lovelace default_view randomly omits words from the entity names

### ISSUE THREAD

**Issue by ajayjohn** [home-assistant/frontend#5514]
### Checklist
- [x]  I have updated to the latest available Home Assistant version.
- [x]  I have cleared the cache of my browser.
- [x]  I have tried a different browser to see if it is related to my browser.

### Expected behavior
The entire entity name should be displayed for all entities.

### Steps to reproduce

1. Add a ZHA entity and name it something like 'Dining Room - Lamp 1'
2. Try to view this entity on the default_view lovelace page without modifying anything else.
3. The entity name should read '- Lamp 1' with the initial text missing. However, if you view the details of that entity, the entire name is correctly displayed there. 

### Environment

- Home Assistant release with the issue: 0.108.0
- Last working Home Assistant release (if known): 0.102.x (Approximately)
- Browser and browser version: Chrome and Brave (Chromium based): 80.x+, Safari: 13.0.5
- Operating system: macOS
- Javascript errors shown in your browser console/inspector: None

### Additional information
I have attached a video of this issue highlighting how some names are cut off, while others aren't. Though the browser window was resized to be smaller in the video, this is actually running on a MacOS computer with Brave browser. Resizing the browser window doesn't seem to change the issues's behavior.

![HA_UI_Name_Issue](https://user-images.githubusercontent.com/1575879/78935829-17f54880-7a73-11ea-8c68-4d8027752347.gif)

**Comment by bramkragten** [comment]
This is correct, if the header of your card already specifies Dining Room we assume you know the entities belong that room and don't show it in the entities name.

**Comment by ajayjohn** [comment]
Ah, I see. That does make logical sense.
My only concern is that with this approach, some of the HA screens will b filled with unrecognizable names like Lamp 1, Lamp 2 etc. for every room. Attached below is an example of the ZHA view within the configuration section.
![Screen Shot 2020-04-09 at 6 12 00 PM](https://user-images.githubusercontent.com/1575879/78948510-3b79bc80-7a8e-11ea-9264-9299f29f2e83.png)

Further, having the name contain the room name too, helped in easily exposing these devices to a voice assistant like Google or Alexa. But this second point is not a blocker in any way as I can work-around it by manually defining an alias for each entity I expose.

Do you think this behavior can be made optional by any chance (via a config flag or something similar)?

**Comment by ajayjohn** [comment]
I take that back. ZHA does treat the device different from the individual entities under it. So it can name the devices something different from what the entities are called. This solves my problem. Thanks!
