### ISSUE TITLE
Back button behaves strangely on Android

### ISSUE THREAD

**Issue by federicoodorizzi** [home-assistant/frontend#5515]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

When editing a card on an android phone, using either a browser or the app, the back button/gesture behaves strangely. It acts on the level underneath the editing window, not closing it.
## Expected behavior

I'd expect the back button to act as a save/cancel button, closing the editing window.
## Steps to reproduce

1. Navigate to any page of the UI using a mobile phone
2. Choose "Configure UI"
3. Press "Edit" on any card
4. Press the back button of the mobile phone - Notice no action happening
5. Press "Cancel" to abort the editing
6. Notice that you are now on a different page of the UI than the one you were when started editing.
## Environment

- Home Assistant release with the issue: 0.108.0
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Chrome on Android - V 80.0
- Operating system: Android 10

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by brettp** [comment]
This has not been resolved. The back button behavior is still inconsistent and results in unexpected behavior.

**Comment by bramkragten** [comment]
https://github.com/home-assistant/frontend/pull/6354
