### ISSUE TITLE
Change HTML tag background color to match theme

### ISSUE THREAD

**Issue by Thermacon** [home-assistant/frontend#5520]
## Change HTML tag background colot to var(--background-color)

Currently, the background color of the `<html>` tag is white. While this does not seem like an issue at first, it does mean that when a user over-scrolls when not using the default theme, a small white bar will appear on the bottom of the browser window. I personally find this to be very annoying. If the `background-color` of the `<html>` tag were to be `var(--background-color)` the background color would always match theme, thus removing the tiny white bar.

So, here is what the html tag's CSS would look like:
`<html lang="en" style="background-color: var(--background-color); ...">`

## The alternatives

This is not a major issue, so I have not made any permanent solutions to use. However, it is not hard to change the background color in the chrome inspector.

## Additional information
This is a very small detail, literally one line of code, that I feel makes the experience a little bit better. Most times, over-scrolling and seeing the background of the <html> tag makes the frontend feel a bit off.

**Comment by ludeeus** [comment]
This was added here <https://github.com/home-assistant/frontend/pull/5716>
