### ISSUE TITLE
Tibber problem after 108 update: sensor.real_time_consumption_none non numeric

### ISSUE THREAD

**Issue by cortado** [home-assistant/frontend#5523]
Tibber real time consumption is not showing in gauge card or on badge after 108 update:

Enitity is non numeric: sensor.real_time_consumption_none

Cannot get "average power" (the realtime consumption), all other data from Tibber displays as normal in UI.

**Comment by zsarnett** [comment]
Please open a new issue and fill out the template

**Comment by crackers81** [comment]
Did you find a fix?
