### ISSUE TITLE
Add the ability to organize automations and scripts into categories

### ISSUE THREAD

**Issue by pax2011** [home-assistant/frontend#5525]
## The request
 Add the ability to organize automations and scripts into categories, It would be much more comfortable. Ex. Light automations; Notification automations....

## The alternatives
 I did it manually, like this 
![Cattura](https://user-images.githubusercontent.com/56022493/79064400-e1087800-7ca8-11ea-9bc4-0f8967d0ace6.PNG)

**Comment by zsarnett** [comment]
Duplicate of: https://github.com/home-assistant/frontend/issues/4542

These are the same issues. We will be grouping them by domains
