### ISSUE TITLE
Shopping list drag-drop

### ISSUE THREAD

**Issue by blackshadev** [home-assistant/frontend#5526]
## The request

Drag and drop support for shopping list card to change the order of the items

## The alternatives

Other (android) apps? 
## Additional information
When creating a shopping list I'd like to change the order afterwards, such that I can put them in order I encounter them in the shops.

**Comment by zsarnett** [comment]
We should use Sortable for this like the side bar

**Comment by Misiu** [comment]
This can be closed.
https://github.com/home-assistant/frontend/pull/7296 solves that.
