### ISSUE TITLE
Theme variables support for mobile vs. desktop is different

### ISSUE THREAD

**Issue by liri** [home-assistant/frontend#5529]
## Checklist

- [ x] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem

Mobile vs. Desktop differences in themes definitions. The header (more-info-controls) on mobile takes the wrong color variable as background.

## Expected behavior

The header will take the correct background color.

## Steps to reproduce

Set the variable --primary-color to be the same as --text-primary-color and the more-info-controls header text will be invisible (same colors).

Specific media query that caused the bug:
@media (max-width: 450px), (max-height: 500px)
more-info-controls {
    --more-info-header-background: var(--primary-color);
    --more-info-header-color: var(--text-primary-color);
}

in desktop - the more-info-controls header is fine. Anyhow - the current state isn't consistent. 

## Environment

- Home Assistant release with the issue: 0.108.3
- Last working Home Assistant release (if known):
- Browser and browser version: chrome latest
- Operating system: windows 10

## Problem-relevant configuration

Theme variables:
```txt
primary-color: "#000000"
primary-text-color: "#000000"
```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
Desktop more info:
![image](https://user-images.githubusercontent.com/2714040/79071522-da97f180-7ce4-11ea-8d1a-b7277519fb91.png)

Mobile more-info (same theme):
![image](https://user-images.githubusercontent.com/2714040/79071533-f00d1b80-7ce4-11ea-8775-98ebc36aab58.png)

Since it's a media query definition i cannot override: --more-info-header-background to fix this issue as a workaround.

**Comment by ludeeus** [comment]
This was fixed here <https://github.com/home-assistant/frontend/pull/5716>
