### ISSUE TITLE
Lovelace button - state_color has a couple of issues

### ISSUE THREAD

**Issue by ukmgranger** [home-assistant/frontend#5535]
The icon for a group is not changing colour when devices in the group are switched on.

My lovelace code:

entity: group.kitchen_lights
hold_action:
  action: more-info
icon_height: 70px
name: Kitchen
show_icon: true
show_name: true
state_color: true
tap_action:
  action: toggle
type: button

Additionally, I'm getting the message "Expected a value of type `undefined` for `state_color` but received `true`." in the lovelace editor.  Not sure if this is related?

![Screenshot 2020-04-14 at 10 27 43](https://user-images.githubusercontent.com/35274652/79209561-85222880-7e3b-11ea-9fd1-cfa562299157.png)

**Comment by zsarnett** [comment]
Please open a new issue and fill out the template

**Comment by iantrich** [comment]
groups do not have a state color
