### ISSUE TITLE
input_number: does not show selector between box and slider

### ISSUE THREAD

**Issue by andriej** [home-assistant/frontend#5540]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

While adding helper input_number there's no possibility to choose between 'box' and 'slider' type of this input, which is available via YAML.
UI only shows names and options for slider.
![image](https://user-images.githubusercontent.com/6303489/79311487-ca0e9380-7efd-11ea-8968-19a084da4eac.png)

## Expected behavior

Allow to choose and show options for slider only when slider chosen.

## Steps to reproduce

UI -> Helpers -> Add input number

## Environment

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.19.0-8-amd64
python_version | 3.7.7
timezone | Europe/Warsaw
version | 0.108.3
virtualenv | false

- Home Assistant release with the issue: 0.108.3
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome latest
- Operating system: Windows

## Problem-relevant configuration

n/a

## Javascript errors shown in your browser console/inspector

none

**Comment by SeanPM5** [comment]
This is supported already and was working in 0.107.7 so it seems this is a fairly recent bug. The line that says "Display mode" is supposed to have radio buttons in front of the "Slider" and "Input field" options, but they are not showing for some reason.

The radio buttons are also missing on other Helpers dialogs too (`Text` and `Date and/or time`).

**Comment by ludeeus** [comment]
This _may_ sound strange, but try to go to the "Automation" tab, then to "Helpers", and then try to add one.

**Comment by andriej** [comment]
@ludeeus it is strange, cause it works from this perspective (path)
![image](https://user-images.githubusercontent.com/6303489/79316232-59b74080-7f04-11ea-8546-6e277ece384b.png)

**Comment by oncleben31** [comment]
The workaround doesn't work for the input_boolean

**Comment by ludeeus** [comment]
input_boolean's does not have "radio" elements (the circles)

**Comment by oncleben31** [comment]
OK but the field for the setting this type of helpers is not displayed. It seems related. Do you think I should open an other issue ?

**Comment by ludeeus** [comment]
yes

**Comment by eddriesen** [comment]
> 
> 
> This _may_ sound strange, but try to go to the "Automation" tab, then to "Helpers", and then try to add one.

Oh wow, That did the trick!

**Comment by Sirezul** [comment]
Is it normal to be greyed out?
![grafik](https://user-images.githubusercontent.com/40226949/84542420-b31bd000-acf9-11ea-950e-c86caff81ed2.png)

**Comment by bramkragten** [comment]
Don't ask question on old closed issues.


You should load those integrations.
