### ISSUE TITLE
Helper input for input_datetime is broken as of 0.108.3

### ISSUE THREAD

**Issue by Xandaar** [home-assistant/frontend#5545]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The new helper feature for input_datetime no longer allows one to select if the variable needs a date, time, or both. It just has standard text. 
![INPUT_DATETIME](https://user-images.githubusercontent.com/945200/79364635-a22c2980-7f17-11ea-909b-f114796fabda.PNG)

## Expected behavior
In the past, the user could select whether they needed date, time, or both date and time. Currently, the option is missing and home assistant does not allow one to add the helper due to the missing option. Additionally, setting initial value would be good here. I do not remember if it was available as of 0.107 when these helpers were first introduced. 

## Steps to reproduce
1. navigate to the lovelace side bar
2. click on configuration
3. click on helpers
4. click on the plus to add a helper
5. click on date and/or time
6. you will see the option is missing and home assistant does not allow you to add the helper due to the missing option. 

## Environment

- Home Assistant release with the issue: 0.108
- Last working Home Assistant release (if known): 0.107.?
- Browser and browser version: tested on both chrome and firefox most recent versions
- Operating system: PC running Windows 10 pro.  Home assistant running on raspi 3 and a docker installation running in proxmox.  

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
Thanks! Couldn't live without home assistant.

**Comment by ludeeus** [comment]
Duplicate of https://github.com/home-assistant/frontend/issues/5540
@Xandaar I gave a workaround in #5540, that will work for your issue as well until this is fixed.

**Comment by Xandaar** [comment]
> 
> 
> Duplicate of #5540
> @Xandaar I gave a workaround in #5540, that will work for your issue as well until this is fixed.

Thank you!
