### ISSUE TITLE
Feature Request: Make Emoticons work in Addon Changelogs

### ISSUE THREAD

**Issue by B-Kramer** [home-assistant/frontend#5552]
## The request

Make them render correctly.

## Additional information
![image](https://user-images.githubusercontent.com/5782664/79401942-15519200-7f50-11ea-91ec-5426ae0c02ed.png)

**Comment by ludeeus** [comment]
They are rendered correctly, that is just text, not icons.
If you look at the 🔨 (which is an emoticon, you see that it render those just fine)

**Comment by ludeeus** [comment]
duplicate of https://github.com/home-assistant/frontend/issues/5062
