### ISSUE TITLE
Problem update 108.

### ISSUE THREAD

**Issue by jppuech** [home-assistant/frontend#5553]
## The problem

I am in version 107.7 and I cannot update to version 108.4. Following the update, the home page refuses to launch.
I have to upgrade 107.7. Thanks for your help.

**Comment by ludeeus** [comment]
Hi 👋 

Updating does not fall under the frontend.
Issues are generally only for bugs, this looks like a support ticket (if it was a bug, everyone would have this problem).

Please reach out on the forum/discord to get help with updating.
https://www.home-assistant.io/help/
