### ISSUE TITLE
hui-map-card and hui-picture-entity-card cards do not load in v0.108.x

### ISSUE THREAD

**Issue by kaizersoje** [home-assistant/frontend#5554]
## Checklist

- [ x] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

I have couple of `hui-map-card` and `hui-picture-entity-card` cards. Since I upgraded from v0.106.x, these cards are temperamental. The `hui-map-card` and `hui-picture-entity-card` work sometimes only.

I get the errors - 
`Custom element doesn't exist: hui-map-card.`
`Custom element doesn't exist: hui-picture-entity-card.`

## Expected behavior

I expect the cards to load as expected.

## Environment

System details

arch | armv7l
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.19.114-v7
python_version | 3.7.7
version | 0.108.4
virtualenv | false

I have tried Safari Version 13.1 (14609.1.20.111.8) and Chrome Version 80.0.3987.163 (Official Build) (64-bit) on Mac OSX.

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by Merwenus** [comment]
Same error for me, the old custom elements work well, but no matter what I try to add I get this error message.
Removed cache, tried with chrome, firefox, edge, same error and at least with 3 different custom elements what I tried to install today: mini graph, weeather card, layout-card.

Custom element doesn't exist: mini-graph-card.

**Comment by onemico** [comment]
Same issue with the Map card, saying it is a custom element when I don't believe it is.

Custom element doesn't exist: hui-map-card.
