### ISSUE TITLE
Scenes Editor - Error for Climate Devices/Entities

### ISSUE THREAD

**Issue by Tim-GitHub** [home-assistant/frontend#5557]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

When using the Scenes Editor (via Configuration UI), scenes with climate entities give errors when closing the scene or opening the scene to be edited (when the Scenes Editor is restoring the state of the entities, I assume). This does not happen for other entities (like lights).

For a Z-Wave Thermostat (GC-TBZ48) and Nest thermostat (using the legacy native Nest integration):

```expected float for dictionary value @ data['target_temp_high']```

This error occurs when opening or closing the scene within the Scenes Editor. If I open scenes.yaml in File Editor, I can see the the 'target_temp_high' entry exists and there is no temperature specified. This is because the thermostat is in the 'Cool' mode, which does not use 'target_temp_high' or 'target_temp_low' entries. So it seems that the Scene Editors in the Configuration UI is grabbing all of the states for the climate entity when it 'snapshots' the entities in the Scene, even if they are not relevant to the current settings.

So I switched the climate device to 'Auto' and tried again to create a scene with the Scene Editor. This time I get a new error:

```expected float for dictionary value @ data['temperature']```

In the File Editor I can see that (because the climate device is in 'Auto' mode) the  'target_temp_high' or 'target_temp_low' entries now contain temperatures. The 'temperature' entry is empty, however. This is because when in 'Auto' the climate device uses the range between 'target_temp_high' and 'target_temp_low', and therefore the target 'temperature' entry is null.  There is a 'current_temperature' entry, which shows the current temperature of the room (not the set-point).

**Conclusion:** It seems the process of taking a 'snapshot' of climate entities within the Scenes Editor needs to be revisited. The current temperature of the room when the snapshot was taken is not needed, just the set-point(s). Additionally it seems the Scenes Editor expects all the entries (like 'target_temp_high' and 'target_temp_low') to have data present, even if the climate device does not currently use them.

## Expected behavior

The Scenes Editor should allow the creation of Scenes including climate editions without error, and should not store the 'current_temperature' within the Scene. Additionally either the 'snapshot' of the current state of climate entities should not include entries with on content (shown as 'null' in the States screen, or should include them but not error on their lack of content.

## Steps to reproduce

    1. Add a new Scene within the Scenes Editor
    2. Select the climate entity from the list
    3. Click on the save button to save the current state of the climate entity
    4. Click the back arrow button to return to the list of scenes
    5. Error occurs

## Environment

- Home Assistant release with the issue: 0.108.3
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Chrome 80.0.3987.163 (Official Build) (64-bit)
- Operating system: Windows 10 64-bit

## Problem-relevant configuration

Examples described above:

**scenes.yaml**
```
- id: '1587058015974'
  name: Cool
  entities:
    climate.upstairs_thermostat:
      aux_heat: 'off'
      current_temperature: 76
      fan_action: Idle
      fan_mode: Auto Low
      fan_modes:
      - Auto Low
      - On Low
      friendly_name: Upstairs Thermostat
      hvac_action: idle
      hvac_modes:
      - heat
      - 'off'
      - cool
      - heat_cool
      max_temp: 95
      min_temp: 45
      node_id: 16
      state: cool
      supported_features: 75
      target_temp_high:
      target_temp_low:
      temperature: 79
      value_id: '72057594311606276'
      value_index: 0
      value_instance: 1
- id: '1587058063840'
  name: Auto
  entities:
    climate.upstairs_thermostat:
      aux_heat: 'off'
      current_temperature: 76
      fan_action: Idle
      fan_mode: Auto Low
      fan_modes:
      - Auto Low
      - On Low
      friendly_name: Upstairs Thermostat
      hvac_action: idle
      hvac_modes:
      - heat
      - 'off'
      - cool
      - heat_cool
      max_temp: 95
      min_temp: 45
      node_id: 16
      state: heat_cool
      supported_features: 75
      target_temp_high: 79
      target_temp_low: 64
      temperature:
      value_id: '72057594311606276'
      value_index: 0
      value_instance: 1
```

## Javascript errors shown in your browser console/inspector

```
N/A
```

## Additional information
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1232, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1255, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/scene.py", line 193, in apply_service
    hass, call.data[CONF_ENTITIES].values(), blocking=True, context=call.context
  File "/usr/src/homeassistant/homeassistant/helpers/state.py", line 106, in async_reproduce_state
    *(worker(domain, data) for domain, data in to_call.items())
  File "/usr/src/homeassistant/homeassistant/helpers/state.py", line 100, in worker
    hass, states_by_domain, context=context
  File "/usr/src/homeassistant/homeassistant/components/climate/reproduce_state.py", line 76, in async_reproduce_states
    *(_async_reproduce_states(hass, state, context) for state in states)
  File "/usr/src/homeassistant/homeassistant/components/climate/reproduce_state.py", line 58, in _async_reproduce_states
    [ATTR_TEMPERATURE, ATTR_TARGET_TEMP_HIGH, ATTR_TARGET_TEMP_LOW],
  File "/usr/src/homeassistant/homeassistant/components/climate/reproduce_state.py", line 42, in call_service
    DOMAIN, service, data, blocking=True, context=context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1210, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 208, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 287, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 283, in _exec
    v = func(v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 205, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 287, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 285, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected float for dictionary value @ data['target_temp_high']
```

**Comment by Tim-GitHub** [comment]
Originally opened a case with Core, was instructed to open a case here with Frontend instead. Closed the case with core (mentioned above).

**Comment by Schuyler113** [comment]
Is there any workaround for this in the meantime? I have tried removing the line, and setting temperature to null in the scene - both just turn on the heat.

**Comment by hwhesselink** [comment]
This issue still exists.  I am running the latest version of HA.

**Comment by hwhesselink** [comment]
My current workaround is to edit scenes.yaml (or change the scene via the Scenes Editor UI and then afterwards edit scenes.yaml), fill in the missing values and then reload scenes via Configuration/Server Controls.

It doesn't appear to matter what you fill in, as long as they're numbers, f.i. I use 0 and 100 for target_temp_low and target_temp_high.

**Comment by GeoffMaciolek** [comment]
@bramkragten  (and @Tim-GitHub  ) - as with **hwhesselink** - I seem to have this issue as well.  (Worth noting - I have in the past deleted and re-addied my Ecobee integration; this is probably not relevant, but I don't know if I tried  create scenes before that).  Requesting re-open.

* **HA Version:** Home Assistant 2020.12.1
* **Platform** 
  * **Host Operating System:** Home Assistant OS 5.9
  * **"Operating System Version":** 5.4.79-v8
  * **Device:** RasPi 4 2GB

**Comment by kj4dxk** [comment]
I am having this same issue and came here looking for a solution.  I am fully up to date and created my HA installation only two weeks ago.

**Comment by ryanmaule** [comment]
I am having the same issue.  I can't create a scene that involves my Ecobee thermostat, and if I try to edit the scenes.yaml to add the target_temp_high value it still errors out.

- HA Version: Home Assistant 2021.1.1
- Platform
-- Frontend version: 20201229.1
-- Device: Intel NUC

**Comment by broyuken** [comment]
Just chiming in that I have the same issue as everyone else. And I cannot manually change the scene because I use this to turn off my thermostats when the door is open. When a door or window opens, it snapshots my thermostats and creates a scene, then when the doors close again the scene I created previously gets called. 

Running 2021.3.4

**Comment by broyuken** [comment]
Also this used to work, not sure when it stopped working as I don’t leave my doors/windows open in the winter.

**Comment by garnern2** [comment]
Seems kind of strange this issue hasn't been fixed. One would think the use of thermostats with scenes would be one of the most likely implementations. Have there been any current work-arounds?
