### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by andriej** [home-assistant/frontend#5561]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
While adding automation through UI, interface lagged a lot (I have ~1000 entities and a lot of automations via YAML). Wanted to test UI way of doing them.
After making it to work (which took quite long time as interface froze few times, even when activating automation in the end), I saw in logs:
```Logger: frontend.js.latest.202004072
Source: components/system_log/__init__.py:209
First occurred: 12:05:56 (1 occurrences)
Last logged: 12:05:56

https://[url_redacted]/config/automation:0:0 ResizeObserver loop limit exceeded
```

## Expected behavior

Smooth experience while setting up automations through UI with lots of entities.

## Steps to reproduce

None, except - navigate to UI and start adding automation.
Problems can be seen right after I change i.e. trigger to 'numerical state' or just 'state' and entity list loads in background.

## Environment

- Home Assistant release with the issue: 0.108.6
- Last working Home Assistant release (if known): n/a, always been like that
- Browser and browser version: Chrome latest 
- Operating system: Win 10

## Problem-relevant configuration

n/a

## Javascript errors shown in your browser console/inspector

none

**Comment by Peterhansel88** [comment]
Hi!

I have the same issue except I am on "Home Assistant 0.108.5" and "OS: 3.12".

When I hit the "save button" on an automation or a script (even if I did not change anything), this error showns on error log:

Log Details (ERROR)
Logger: frontend.js.latest.202004072
Source: components/system_log/__init__.py:209
First occurred: 11:39:42 AM (3 occurrences)
Last logged: 11:49:20 AM

http://192.XXX.X.XX:XXXX/config/automation:0:0 ResizeObserver loop limit exceeded
http://192.XXX.X.XX:XXXX/config/script:0:0 ResizeObserver loop limit exceeded


If I change automation or script via text editor or "configurator add-on", and reload them (Configuration/Server Controls/Reload ....)  is working fine without any error log.


Environment:
Home Assistant release with the issue: 0.108.5
Operation System: 3.12
Last working Home Assistant release (if known): 0.105.2
Browser and browser version: Chrome latest
Operating system: Win 10

**Comment by Peterhansel88** [comment]
It looks like not even need to hit save. If I just go in to "Configuration/Automations" or "Configuration/Scripts" the warning log appear instantly.

**Comment by andriej** [comment]
Yes, save is not needed.

**Comment by Yevgenium** [comment]
Same issue, and I see this:
![image](https://user-images.githubusercontent.com/33804747/79636704-702af980-819b-11ea-8c32-e770ac28675d.png)
After some time, the table restores the form.

**Comment by freemann** [comment]
Here also this strange error;
`[frontend.js.latest.202004072] http://192.xxx.xxx.xxx:8123/lovelace/4:0:0 ResizeObserver loop limit exceeded
`

Never used the GUI to make any automations and this error appear out of nothing.
My LoveLoce GUI is hanging and eventually I receive connection denied/refused messages on all my devices (Android(Chrome/App)/Desktop).

**Comment by tdejneka** [comment]
I'm seeing the same error reported whenever I view **Configuration > Scripts**.

> Log Details (ERROR)
Logger: frontend.js.latest.202004072
Source: components/system_log/__init__.py:209
First occurred: 7:01:02 AM (2 occurrences)
Last logged: 7:01:29 AM
>
> http://ha:8123/config/script:0:0 ResizeObserver loop limit exceeded

I'm using Home Assistant Supervised 0.108.6 (Supervisor 217) on Ubuntu 18.04.4. There are 12 scripts (in total) and all are displayed on the screen. In other words, there's no apparent defect other than the error message.

**Comment by stuartlea** [comment]
> I'm seeing the same error reported whenever I view **Configuration > Scripts**.
> 
> > Log Details (ERROR)
> > Logger: frontend.js.latest.202004072
> > Source: components/system_log/**init**.py:209
> > First occurred: 7:01:02 AM (2 occurrences)
> > Last logged: 7:01:29 AM
> > http://ha:8123/config/script:0:0 ResizeObserver loop limit exceeded
> 
> I'm using Home Assistant Supervised 0.108.6 (Supervisor 217) on Ubuntu 18.04.4. There are 12 scripts (in total) and all are displayed on the screen. In other words, there's no apparent defect other than the error message.

I am seeing the same error when going to Configuration > Scripts

**Comment by Frits1980** [comment]
I see the same error whenever I press the execute link on an automation from the UI, my automations are YAML and not UI made (don't know if that make a difference).

**Comment by bramkragten** [comment]
This error is not something to worry about generally, but I improved the performance of the automation panel in 0.109 so please check if that helps.

**Comment by Quentame** [comment]
Still experiencing the issue with HA `0.110.0.dev0` - frontend `20200427.2`.

I don't know if related with automation, I personally don't have any automation, script or scene, and it happens (this is in my dev env).

From here:
![image](https://user-images.githubusercontent.com/14821482/80894222-90010800-8cd9-11ea-8325-34d27e53c056.png)

clicking the back arrow, then having:
```shell
2020-05-03 00:56:30 ERROR (MainThread) [frontend.js.latest.202004272] http://localhost:8123/config/devices/dashboard?historyBack=1&config_entry=0a78dd2d13174186860f553f3eb86e62:0:0 ResizeObserver loop limit exceeded
```

**Comment by mikey60** [comment]
I saw the same error with version 109.6.
https://xxxxxxxxxxxxxxxx.duckdns.org:8123/config/devices/dashboard?historyBack=1&config_entry=277e8c40f84d45cb86e3265835b76d3d:0:0 ResizeObserver loop limit exceeded
