### ISSUE TITLE
Version in frontend not updating

### ISSUE THREAD

**Issue by ac2323** [home-assistant/frontend#5562]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

After updating home assistant, the version number in the frontend still shows the old version (106.0). When upgrading, however, it correctly shows me on an updated version. I am currently running 108.6.

This happened when updating from 106 to 107, originally.

## Expected behavior

Frontend version should show latest.

## Environment

Linux venv

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ludeeus** [comment]
So you don't see this issue now?
This was a one-time thing?
It sounds like a cache issue.

**Comment by ac2323** [comment]
Still an issue, even in Incognito.

**Comment by bramkragten** [comment]
Then I don't get your problem, it showed 106 when upgrading to 107 but you are now on 108.6 so what do you see now?

And how do you know you are on 108.6?

**Comment by ac2323** [comment]
Regardless of any upgrade, the version number still shows 106 in the frontend. I just upgraded to 109.1 and the result was the same. See pics of the upgrade as well as what the frontend is showing

![image](https://user-images.githubusercontent.com/45429681/80761602-de12e180-8b08-11ea-9ff3-ef82a848e1a4.png)

![image](https://user-images.githubusercontent.com/45429681/80761646-f125b180-8b08-11ea-84f4-a6a94527ec67.png)

**Comment by ludeeus** [comment]
You are still running 0.106.0
This is a manual install, and you now probably have 2 HA installations running.
This is not a frontend bug.
Jump into discord or the forum to seek help getting your installation issues sorted <https://www.home-assistant.io/help/>

**Comment by bramkragten** [comment]
Have you restarted Home Assistant after upgrading?

**Comment by ac2323** [comment]
> 
> 
> You are still running 0.106.0
> This is a manual install, and you now probably have 2 HA installations running.
> This is not a frontend bug.
> Jump into discord or the forum to seek help getting your installation issues sorted https://www.home-assistant.io/help/

Ugh, I forgot to activate the venv.

Sorry, this was my mistake. Thanks for your help!
