### ISSUE TITLE
Casting Google Play Music to a Google Cast device causes mixed content warnings when using TLS

### ISSUE THREAD

**Issue by jboiselle** [home-assistant/frontend#5563]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When casting a song from the Google Play Music service to a Google Cast device, the state badge (which displays the album art in this case) seems to be hardcoded to use `http` instead of `https`. This causes mixed content warnings from the browser. This does not occur when streaming media compatible with state badge content from other Google services, such as YouTube.

Inspecting the web page inside of developer tools and manually changing the insecure content URL from `http` to `https` resolves the mixed content error.

## Expected behavior

Home Assistant always remains secure when using `https/tls`.

## Steps to reproduce

1. Open Home Assistant in your browser and confirm that the connection is secure
2. Add a Google Cast device
3. Begin casting a song from Google Play Music to the Google Cast device
4. The browser connection changes to 'Not secure'

## Environment

- Home Assistant release with the issue: 0.107.7
- Frontend version release with the issue: 20200318.1
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Google Chrome 80.0.3987.163 / Mozilla Firefox 75.0
- Operating system: Windows 10 18362.720

**Home Assistant is served via reverse-proxy using nginx/1.10.3 on Debian 9**

## Problem-relevant configuration

n/a

## Javascript errors shown in your browser console/inspector

Chrome developer tools > Security tab
![image](https://user-images.githubusercontent.com/29435457/79607897-0b4fa080-80c2-11ea-8958-3c509248ea09.png)

Mozilla Firefox developer tools > Console tab
![image](https://user-images.githubusercontent.com/29435457/79608716-7c438800-80c3-11ea-8938-4e9f479254ce.png)

```txt

```

**Comment by bramkragten** [comment]
That is the url that is provided by the `media_player` in the `entity_picture` attribute.
