### ISSUE TITLE
FFmpeg still active after close camera window

### ISSUE THREAD

**Issue by ster1um** [home-assistant/frontend#5569]
FFmpeg still active after close camera window.

home assistant version 0.108.5
Frontend 20200407.2 - latest

arch | aarch64
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 5.5.0-rc6-aml-s9xxx
python_version | 3.7.7
timezone | UTC
version | 0.108.1
virtualenv | false

**Comment by bramkragten** [comment]
Please complete the issue template
