### ISSUE TITLE
Theming issues after 0.108

### ISSUE THREAD

**Issue by electrofloat** [home-assistant/frontend#5571]
@frenck suggested here: https://github.com/home-assistant/frontend/commit/7d6f188bfc7bb89976b38439b8a50588e70d6fff to not comment on commits, instead raise an issue on GitHub. So I'm doing that.

Copying the content of that comment here:

Is this patch related to this comment in 0.108 blogpost?:

> Lovelace themes - We discovered our theme logic was wrong, when you didn’t specify a theme for a Lovelace card or view. It would default to the backend selected theme, even when your local theme was different, or your view had a different theme. To fix this we removed the options default and Backend selected from the Lovelace theme selection, and when there is not theme selected it will not set a theme. This will make sure the element has the same theme as it’s parent.

And is this related to everyone having issues using dark (or any other themes)?

After updating to 0.108 switching to a dark theme leaves the left panel white, and also some combox lists, and panel_iframe backgrounds.

**Comment by Mariusthvdb** [comment]
if you'd post the solution to both issues here, it might help to solve the issue quickly:

```
sidebar-background-color: "var(--paper-listbox-background-color)"
```

for the sidebar, and 

```
card-background-color: "var(--paper-card-background-color)"
```

for the card background. All merits to @tom_l for posting these in https://community.home-assistant.io/t/sidebar-background-color-hassio-v-108-2/185573/21?u=mariusthvdb

**Comment by bramkragten** [comment]
The sidebar issue is fixed.
