### ISSUE TITLE
Unable to set Mireds to 500 in the frontend

### ISSUE THREAD

**Issue by Skaronator** [home-assistant/frontend#5574]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I'm unable to move the color temperature slider to the maximum value (500). The maximum value I can set it is always 499 not 500 as you can see here:

![image](https://user-images.githubusercontent.com/2886913/79702323-62ad6680-82a4-11ea-842b-dca2943ae52f.png)

The lowest value (152.998?) works fine:

![image](https://user-images.githubusercontent.com/2886913/79702339-7d7fdb00-82a4-11ea-94d4-8a21b8369a2b.png)

When setting the color temperature via light.turn_on service then the 500 value works just fine:

```yaml
entity_id: light.custom_one
color_temp: 500
```

And is correctly displayed
![image](https://user-images.githubusercontent.com/2886913/79702367-b91aa500-82a4-11ea-82d4-2d2b8f8acd44.png)

## Expected behavior

I should be able to set the light to 500 mireds.

## Steps to reproduce

1. Have a light with color temperature from 6536 Kelvin to 2000 Kelvin
2. Try to move the slider to 500

## Environment

- Home Assistant release with the issue: 0.108.6 (0.107 had this issue as well)
- Last working Home Assistant release (if known): Not known
- Browser and browser version: Chrome 81 & FIrefox 75
- Operating system: Windows 10

I'm using ESPHome with the CCT light with the default cold and warm white values. https://esphome.io/components/light/cwww.html

## Problem-relevant configuration

Configured via UI, no yaml.

```yaml

```

## Javascript errors shown in your browser console/inspector

No Errors.

```txt

```

## Additional information

It looks like this issue could be caused by the weird cold white mired value of 152.998779296875.

This is the slider when setting to the maximum I could. As you can see its 499 but again with the 998779296875 behind.
```html
<paper-progress id="sliderBar" aria-hidden="true" role="progressbar" value="499.998779296875" aria-valuenow="499.998779296875" aria-valuemin="152.998779296875" aria-valuemax="500" aria-disabled="false" style="touch-action: none;">
      </paper-progress>
```

So my guess is: The slider steps are always 1. So due to the weird 152.998... we always have this .998 behind each step. When trying to set the slider to 500 it would be over 500 since it's actually 500.998. Due to the aria-valuemax="500" it would set it to something lower. Thats why it's 499.998.

Not sure what the most elegant solution would be. Either round the min and max values of the slider or just cut of any digits behind the dot?

**Comment by bramkragten** [comment]
I guess this is for a specific integration, I would suggest the integration to round its value. I don't think it is useful to have it that precise?
