### ISSUE TITLE
base64 encoded images are stripped by ha-markdown

### ISSUE THREAD

**Issue by bdraco** [home-assistant/frontend#5576]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I'm attempting to display a QR code that can be scanned to pair homekit, however the image always come out missing

The input is
```
To set up Home Assistant in the Home App, enter the following code:
### 398-89-672
![image](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKUAAAClAQAAAAAVUAB3AAABH0lEQVR4nO2WMY6EMBAEGzkg5An8xHwMiZX42O1PeAKhA+S5nvHp0HGbNtpgHSCoBLune8awF6vgQ9+f7gA6e6D/wsxXLFq6mD1t3Yx0jE8pndE/uYfS7fOI7h46+olvov6eh+MGGvoa9SW9qC6g7h1Ky41cHSWgsZzW4ZoWBT0QJsXkJVXTPVkcu/hhTU1ZyAaavoOYPsYyeYehbbYy/XhHRVlI/h70TtgVWmqrxR7YQlfr9XRjLpLrm+zUV0Rd1ezVrEgefC2NXAysZkWkf9HSyHyysA3yr381tPUzpjB78POfLiegS5uxngvT05h6R4QDOFM
```

Its rendered as
```
<ha-markdown content="To set up Home Assistant in the Home App, enter the following code:
### 398-89-672
![image](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKUAAAClAQAAAAAVUAB3AAABH0lEQVR4nO2WMY6EMBAEGzkg5An8xHwMiZX42O1PeAKhA+S5nvHp0HGbNtpgHSCoBLune8awF6vgQ9+f7gA6e6D/wsxXLFq6mD1t3Yx0jE8pndE/uYfS7fOI7h46+olvov6eh+MGGvoa9SW9qC6g7h1Ky41cHSWgsZzW4ZoWBT0QJsXkJVXTPVkcu/hhTU1ZyAaavoOYPsYyeYehbbYy/XhHRVlI/h70TtgVWmqrxR7YQlfr9XRjLpLrm+zUV0Rd1ezVrEgefC2NXAysZkWkf9HSyHyysA3yr381tPUzpjB78POfLiegS5uxngvT05h6R4QDOFMopP6ovK2U7haK0SqnXowHKQ192dQYwK3NdiVt9752Wzm7p4j+Xx/69vQbhxug2RxgEnoAAAAASUVORK5CYII=)"><p>To set up Home Assistant in the Home App, enter the following code:</p>
<h3>398-89-672</h3>
<p><img src="" alt="image"></p>
</ha-markdown>
```

<img width="469" alt="Screen Shot 2020-04-19 at 11 06 08 PM" src="https://user-images.githubusercontent.com/663432/79713113-633d0180-8292-11ea-8873-73d7c6788d41.png">

## Expected behavior

The marked demo shows it correctly
https://marked.js.org/demo/?text=To%20set%20up%20Home%20Assistant%20in%20the%20Home%20App%2C%20enter%20the%20following%20code%3A%0A%23%23%23%20398-89-672%0A!%5Bimage%5D(data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAAKUAAAClAQAAAAAVUAB3AAABH0lEQVR4nO2WMY6EMBAEGzkg5An8xHwMiZX42O1PeAKhA%2BS5nvHp0HGbNtpgHSCoBLune8awF6vgQ9%2Bf7gA6e6D%2FwsxXLFq6mD1t3Yx0jE8pndE%2FuYfS7fOI7h46%2Bolvov6eh%2BMGGvoa9SW9qC6g7h1Ky41cHSWgsZzW4ZoWBT0QJsXkJVXTPVkcu%2FhhTU1ZyAaavoOYPsYyeYehbbYy%2FXhHRVlI%2Fh70TtgVWmqrxR7YQlfr9XRjLpLrm%2BzUV0Rd1ezVrEgefC2NXAysZkWkf9HSyHyysA3yr381tPUzpjB78POfLiegS5uxngvT05h6R4QDOFMopP6ovK2U7haK0SqnXowHKQ192dQYwK3NdiVt9752Wzm7p4j%2BXx%2F69vQbhxug2RxgEnoAAAAASUVORK5CYII%3D)&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master

<img width="524" alt="Screen Shot 2020-04-19 at 11 06 41 PM" src="https://user-images.githubusercontent.com/663432/79713137-75b73b00-8292-11ea-89ec-8b60d770d35f.png">

## Steps to reproduce

Try pairing homekit with this PR
https://github.com/home-assistant/core/pull/34449

## Environment

- Home Assistant release with the issue: 0.109dev
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Chrome
- Operating system:

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
This is for security, `data:` URLs are not allowed as they can be used for XSS attacks.

<https://github.com/markedjs/marked/blob/master/lib/marked.js#L156>

**Comment by bdraco** [comment]
Worked around :)
