### ISSUE TITLE
Elevation setting should show as "feet" with "Imperial" setting

### ISSUE THREAD

**Issue by guice** [home-assistant/frontend#5583]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The "Elevation" setting within the General settings is expecting elevation in "feet" when using Imperial setting. It's confusing as it still shows "meters" which can result in highly inaccurate weather settings for `met.no` (HA's default weather integration).

## Expected behavior

When you select "Imperial" as your measurement option, the "Elevation" text helper should change to "feet" (and vise-versa when switching back to Metric).

## Environment

- Home Assistant release with the issue: 108.5
- Last working Home Assistant release (if known): Never
- Browser and browser version: Firefox

## Additional information

<img width="650" alt="Screen Shot 2020-04-21 at 9 55 10 AM" src="https://user-images.githubusercontent.com/205378/79907720-4bbb6100-83d7-11ea-84c2-649b19aa0124.png">

I discovered this issue when trying to correct the weather display for HA:

### When using Meters

Weather data was highly inaccurate, even though it used the exact pin-point of our home. The other integrations were using exact same !long and !lat secrets.

<img width="1749" alt="Screen Shot 2020-04-21 at 9 39 01 AM" src="https://user-images.githubusercontent.com/205378/79908071-d8661f00-83d7-11ea-8c3e-d5d2b9579449.png">

### When changing value to Feet

Weather data is now accurate. Seems there is something in HA's weather integration that's taking into account the elevation.

<img width="1007" alt="Screen Shot 2020-04-21 at 10 00 40 AM" src="https://user-images.githubusercontent.com/205378/79908090-e3b94a80-83d7-11ea-8af2-5d37c67e353d.png">

**Comment by MatthewFlamm** [comment]
See https://github.com/home-assistant/core/issues/34781 for more background on this as well.  The frontend used feet for imperial units, which met integration now uses.  But the frontend now doesn't show feet.
