### ISSUE TITLE
Lack of spacing for FAB on Integrations page

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5592]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

First reported by @TheZoker  in Discord, the FAB on the Integrations page lacks spacing and touches the far right side of the browser window. I've noticed this too in my personal setup a while ago so it's not new to this version.
 
![image](https://cdn.discordapp.com/attachments/427516175237382144/702654570135814194/Screenshot_2020.04.23_00h57m56s_005_.png)

If you switch between "Integrations" and "Areas" panels using the tabs at the top, you should notice the difference of FAB spacing.

Using latest Chrome stable but I also just checked in Firefox too and it's happening there as well.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome stable
- Operating system: macOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by timmo001** [comment]
I think this is to do with the fab being `position: fixed;` so it's in the right position when there is no scrollbar, but when one appears, the fab stays int the same position.
