### ISSUE TITLE
Integrations page and dark themes - introduce new theme variable?

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5595]
## The request

Integrations page looks great on the default white theme as you all already know. Seriously great job Bram!

![white](https://i.imgur.com/xeboBgy.png)

But if you're using a dark theme, many of the brand logos are simply not dark mode friendly since they use black logos, and black on black is not too legible. Here's how the same above screenshot looks on a dark theme (not quite as sexy):

![dark](https://i.imgur.com/GQ9msJb.png)

Issue here lies more with the brand logos picked rather than a theme problem. I suspect many of these will get swapped out for more colorful brand logos that work well on both light and dark themes, but this will take a long time and will probably always be a problem to some extent. 

So was thinking it might be useful to introduce a new theme variable, something along these lines:
`integrations-card-background-color: 'var(--card-background-color)'` 
so that theme authors and users can style this kinda... 

End result would be allowing something like this, where you could have a dark theme but with white cards on the integrations page only, to ensure the sexy logos are always visible:

![image](https://i.imgur.com/UuV5Iuz.png)

Or maybe someone has a better solution? I've not given this a ton of thought yet but wanted to get the ball rolling. If anyone uses a dark theme here or is a theme creator please chime in with your thoughts...

## The alternatives
Alternative would be to just hard code / force it as white cards for everyone on the Integrations page. Not sure what people would think of that though.

**Comment by timmo001** [comment]
I wouldn't set mine as white, but maybe a color somewhere in the middle :smiley_cat: 

_Only problem with this is we'd have to override / change to allow alternative colors in `ha-card`_

**Comment by SeanPM5** [comment]
Yeah definitely impacts some themes a lot worse than others, anything that uses pure black or "OLED-style" for the card backgrounds get hit the hardest:

![image](https://i.imgur.com/nu9O2oH.png)

Here the Roku and Spotify logos look quite nice, but the PS4 logo is completely invisible.

**Comment by SeanPM5** [comment]
Closing as my quick suggestion here was a bit flawed. Once you change the card background color from black to white, you'll also want/need to change the text color too in some cases. So you'd have to add another variable to change text too. And I feel that becomes a bit too much and not worth it imo.
