### ISSUE TITLE
Binary sensors with device_class: presence showing bad state (0.109b0)

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5599]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
I use a bunch of bayesian binary sensors for presence detection among other things, I noticed a few of them were displaying funky in Lovelace. Rather than Home it displayed as: `[%key:component::device_tracker::state::home%]`

![image](https://i.imgur.com/y8jIci5.png)

In Dev Tools > States it displays correctly (on).

I've checked all my other binary sensors with device classes (motion, occupancy, connectivity, door, window, etc) and they all display fine. Seems limited to `device_class: presence`.

## Environment

- Home Assistant release with the issue: 0.109.0b0
- Last working Home Assistant release (if known): 0.108.8
- Browser and browser version: Chrome
- Operating system: macOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Seems to work in my dev:
![image](https://user-images.githubusercontent.com/5662298/80095903-ffa02600-8568-11ea-9ebd-d8b83830258c.png)

**Comment by bramkragten** [comment]
Oh, I see this was fixed in the backend yesterday.
