### ISSUE TITLE
Configurator button missing in persistent notifications 0.109 b0

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5604]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When you get the "Configurator" persistent notification there is always supposed to be a button underneath that says "CONFIGURE" or something like that. 

This is not showing on 0.109.0b0 , you can see from the picture below that it's actually there just "invisible" since there's no text. When you hover over the invisible button it changes cursor to indicate it can be clicked, and the button still works just fine. There's just no text, so it's probably a translations thing.

![image](https://i.imgur.com/Ce9h4Af.png)

## Expected behavior

Show button

## Environment

- Home Assistant release with the issue: 0.109.0b0
- Last working Home Assistant release (if known): 0.108.X
- Browser and browser version: Chrome
- Operating system: macOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by frenck** [comment]
OT: Man that configurator needs to go...

**Comment by SeanPM5** [comment]
Fixed now in 0.109 final 👍 

![image](https://i.imgur.com/188futj.png)
