### ISSUE TITLE
Weather card uses backend state rather than a nice name in 0.109.0b

### ISSUE THREAD

**Issue by MatthewFlamm** [home-assistant/frontend#5605]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

The condition is cloudy, or partlycloudy, instead of Cloudy or Partly Cloudy.  The more info has it that way.

![Screenshot_20200423-123559](https://user-images.githubusercontent.com/39341281/80128266-6589af00-8563-11ea-85c5-b48c1093b93d.png)

![Screenshot_20200423-123625](https://user-images.githubusercontent.com/39341281/80128399-99fd6b00-8563-11ea-9843-147b1d4dd4cb.png)

## Expected behavior
Use a nice name for the condition.

## Steps to reproduce
Add a weather forecast card.

## Environment
Android chrome browser accessing a 0.109.0b version of ha.

- Home Assistant release with the issue: 0.109.0b
- Last working Home Assistant release (if known): 0.108
- Browser and browser version:
- Operating system:

## Javascript errors shown in your browser console/inspector

None

## Additional information
The spacing between forecasts also looks a little generous in the new card. The old one fit 4-5 in this situation.  I miss that.

I personally can't quickly distinguish the cloudy states either from the background.  The previous mdi icons had better contrast.

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/pull/5597
