### ISSUE TITLE
HA Cast navigation only works for main dashboard

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#5613]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Home Assistant Cast supports navigating to other views on a loaded Lovelace dashboard. This however only works on the default dashboard (`/lovelace`/).

https://github.com/home-assistant/frontend/blob/4f518cac2c78e8d57e955ca6fdf06ddb72051dbc/cast/src/receiver/layout/hc-main.ts#L98-L104

## Expected behavior

This should work for all dashboards. Clicking a link like `/playground/media` should open my dashboard for `/playground` with the `media` view loaded.

## Steps to reproduce

- Create dashboard on `/playground` with 2 views, `home` and `media`
- Add an entities card with a `weblink` special row to `home` that links to `/playground/media`
- Cast it to HA Cast
- Tap on the link

## Work around

If you know the device it's being cast on, you can use the `cast.show_lovelace_view` service with a `call-service` special row for the entities card.

## Environment

- Home Assistant release with the issue: 0.108
- Last working Home Assistant release (if known): -
- Browser and browser version: all
- Operating system: all

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Should we also allow to change to a different dashboard?

**Comment by balloob** [comment]
Yeah.
