### ISSUE TITLE
Add docs link to Integrations overflow menu

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5614]
## The request

I'm somewhat iffy on this because it's kinda duplicating functionality from Dev Tools > Info... But it also seems like it might be kinda useful and convenient to have on this page as well? 

![docs](https://i.imgur.com/yRfysDL.png)

**Comment by bcrowie** [comment]
Added this feature. I've tested locally and what integrations I have available I have tested. Please let me know if there is anything I need to do additionally for this PR. Thank you.
