### ISSUE TITLE
Weather map does not show current state nicely (0.109.0b1)

### ISSUE THREAD

**Issue by Santobert** [home-assistant/frontend#5618]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The current state does not fit onto the new weather card.
It's even worse on mobile.
The state `Teilweise bewölkt` (partially cloudy) gets reduces to `Teilwe...` which means something like `partia...` in english.

PC:
![grafik](https://user-images.githubusercontent.com/15657682/80201893-2328a680-8625-11ea-8590-4abfa5b2e098.png)

Mobile:
![photo_2020-04-24_12-09-46](https://user-images.githubusercontent.com/15657682/80201621-b31a2080-8624-11ea-8fcb-2c650068b589.jpg)

## Expected behavior

Things move until at least most of the state fit onto the card.

**Comment by bramkragten** [comment]
We should also align the right and left:
![image](https://user-images.githubusercontent.com/5662298/80208955-79034b80-8631-11ea-8da3-cb4ce472f4a9.png)

**Comment by zsarnett** [comment]
The state is the least important information here. You have the icon for that.

**Comment by Santobert** [comment]
@zsarnett I strongly disagree. You need to know most of the symbols to interpret them correctly.
Personally I thnik the state and the temperature are the most important information.

If the state is not important, why is it the largest text there?
To be consistent, it should be much smaller or get the space it needs. I do not like the solution of cutting off parts of the state. And I don't think that this is a good user experience.

**Comment by zsarnett** [comment]
So do why do you have the forecast if you can't interpret the symbols?

**Comment by zsarnett** [comment]
I think there can be some improvements. Visually speaking I don't know what is best..

Probably making the name of the card larger and the state smaller. As a user can shorten the name. Problem is there will always be issues with this if the name or state is long enough

**Comment by Santobert** [comment]
Because it's the only weather card that's available, I guess.
Don't get me wrong, I like the new card. I just think the ux can be improved.

**Comment by zsarnett** [comment]
You can take the forecast off in the settings of the card 😉 

I will see what I can do

**Comment by Santobert** [comment]
What if we swap the name and the state?

**Comment by zsarnett** [comment]
![image](https://user-images.githubusercontent.com/18730868/80220964-9bd23780-8612-11ea-94d0-66bb06101255.png)


Right thats what I was mentioning above. Quickly came up with this

**Comment by bramkragten** [comment]
I like it

**Comment by Santobert** [comment]
I thought about something like that. But it's almost the same :smile: 

![80201893-2328a680-8625-11ea-8590-4abfa5b2e098](https://user-images.githubusercontent.com/15657682/80221625-dbfedd80-8645-11ea-83c3-668ddfbb8c61.png)

**Comment by bramkragten** [comment]
Have both the big ones on top looks better

**Comment by Yevgenium** [comment]
I do not think that for this it is necessary to create a new issue, so I will write here. Openweathermap reports the weather from the current time until the end of the day. If the time is nearing the end of the day, and at this time warming is expected, we can see this:
![owm](https://user-images.githubusercontent.com/33804747/80286404-0edfc900-874d-11ea-9b64-9531825b96e0.jpg)
I think something like this would look better: 2° ... 2.7°C
It will also add more space for state.

**Comment by VDRainer** [comment]
Another issue on this card:
One time it shows:
![Auswahl_318](https://user-images.githubusercontent.com/26381449/80413751-3d39e180-88d0-11ea-9ee5-f9ec8036bdcc.png)
another time
![Auswahl_319](https://user-images.githubusercontent.com/26381449/80413788-49be3a00-88d0-11ea-9eec-cb9ec5b54a17.png)
The size (and also the browser window size) is exactly the same.
If this needs a new issue, please tell me and i'll do.

**Comment by Santobert** [comment]
I think, this can be closed, since the original issue was resolved. @VDRainer I see this behavior as well. It may be worth to create a new issue for it
