### ISSUE TITLE
Lovelace Cover Card icon logic is reversed

### ISSUE THREAD

**Issue by reisub** [home-assistant/frontend#5627]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When using the cover card for my blinds, the button logic is reversed.
For example, when I press the down button:
- the up button is disabled
- the icon on the left side indicates that the cover is going up

For the up button it's again reverse:
- the down button i disabled
- the icon on the left side indicated that the cover is going down

Here is a gif of the issue on my Android device:
![home-assistant-cover-card](https://user-images.githubusercontent.com/992835/80281473-ae7c6780-870b-11ea-8008-bb0bb3dba83f.gif)

## Expected behavior

I expect that then I press the up or down button that the pressed button is disabled while the blinds are running and that the icon indicator displays the correct direction.

## Steps to reproduce

1. Press up or down on the cover card
2. Observe changes to UI

## Environment

I see the same behavior both in Firefox and inside the Home Assistant Android app.

- Home Assistant release with the issue: Home Assistant 0.108.9,  Frontend version: 20200407.2 - latest 
- Last working Home Assistant release (if known): unknown
- Browser and browser version: Firefox 75 / Home Assistant Android app 1.8.0-144 on Android 10 
- Operating system: macOS / Android

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

The cover card is controlling a Shelly 2.5 device which is hooked up to motorized window blinds.

**Comment by reisub** [comment]
I've been updating regularly and this is still an issue in the latest release.

**Comment by bramkragten** [comment]
What integration is providing the cover entities and what is the state in the different conditions?

**Comment by reisub** [comment]
@bramkragten the cover entities are provided by [ShellyForHASS](https://github.com/StyraHem/ShellyForHASS).

I've just now realized that these don't all behave the same, though. I have three of these cover cards, and two of those have the reversed icon logic I described - but one has the correct icon logic.

I have a hunch that this is connected to the shelly web interface for managing each relay. In the web interface, you can select a checkbox to reverse button logic to be able to match how the wires are connected to the physical switches. So this may indeed be a bug within ShellyForHASS.

I'll have to investigate a bit more once I'm back home.

Sorry for confusion, if I had noticed this sooner I would have opened a task in the correct repo - feel free to close if you agree with the conclusion.

**Comment by bramkragten** [comment]
That seems like a possible explanation, you can open a new issue if you think the problem is in the frontend anyway.
