### ISSUE TITLE
entity drop down freezes 

### ISSUE THREAD

**Issue by adonno** [home-assistant/frontend#5632]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Whenever I want to add entities to a card via the UI, the browser freezes. Same when I start to create automations and open the entities, device list.

## Steps to reproduce

https://www.dropbox.com/s/h7vsyw84dw06nyz/Frenck%20demo2.avi?dl=0

## Environment

- Home Assistant release with the issue:  as far as I can remember for the past several versions 
- Last working Home Assistant release (if known): / 
- Browser and browser version:    Managed to have the issue on chrome/Vivaldi and on Firefox even though it took FF more time 
- Operating system: I've encountered this issue on different devices running windows10 

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt
TypeError: Object(...)(...) is null
card-tools.js:1:14091
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! dashboard
TypeError: t is null
card-tools.js:1:14022
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. lit-element.ts:233:24
NS_ERROR_FAILURE 2 chunk.cc6ae5f16983a14edb98.js:1687
hui-alarm-panel-card Error: "Invalid card configuration"
    value hui-alarm-panel-card.ts:96
    s create-element-base.ts:61
    c create-element-base.ts:81
    u create-element-base.ts:155
    Rt create-card-element.ts:56
    value hui-card-picker.ts:326
    value hui-card-picker.ts:362
create-element-base.ts:64:12
hui-plant-status-card Error: "Specify an entity from within the plant domain."
    value hui-plant-status-card.ts:69
    s create-element-base.ts:61
    c create-element-base.ts:81
    u create-element-base.ts:155
    Rt create-card-element.ts:56
    value hui-card-picker.ts:326
    value hui-card-picker.ts:362
create-element-base.ts:64:12
Terminating ServiceWorker for scope ‘https://home.donno.lu/’ with pending waitUntil/respondWith promises because of grace timeout.
```

## Additional information

I am not sure if this is related to the number of entities I have. I am sure there are people with a lot more.   currently 909 Entities

**Comment by drkavnger99** [comment]
I am seeing it with a little over 200 entites and have been since the last few patches.  Thought it was my home assistant instance so moved it over to a bigger server with more ram, cpu, and much faster drives.  Still no change.

**Comment by seanb-uk** [comment]
I'm getting similar behaviour. Using 0.110.4 via Chrome and tried clearing the cache. When I try to add a card, the card preview window loads partially and then hangs the browser tab completely and the only option is to kill the tab.

I get the following errors in the console (I'm not using the plant status card at all):

![2020-05-30 14_35_56-Window](https://user-images.githubusercontent.com/16518559/83329735-0fefa300-a283-11ea-99ae-89cf38dd3ab8.png)

**Comment by bramkragten** [comment]
@seanb-uk that is not the entity picker? Probably a card that is requesting a lot of history, need to fix that too but different issue.

**Comment by seanb-uk** [comment]
Ah, I misread the issue - my problem is when trying to add cards, rather than add entities to a card. I'll raise a separate issue once I've done a bit more digging myself
