### ISSUE TITLE
Sensor Card graph bug on mobile device (Google Chrome for Android)

### ISSUE THREAD

**Issue by tms320** [home-assistant/frontend#5636]
## Checklist
- I have updated to the latest available Home Assistant version.
- I have cleared the cache of my browser.

## The problem
The problem appeared after updating Home Assistant from version 0.101.3 to the current stable version 0.108.9 (I use docker image installation for Raspberry Pi).
On desktop PC the Sensor Card with graph displayed fine.
But on mobile device (Android smartphone with Google Chrome browser v.81.0.4044.117) some Sensor Cards displayed with bug - I see filled rectangle area instead of graph. Some cards displayed normally (see screenshots). I tried different themes - the problem remains. Sometimes, after reload web page, buggy card can become normal, and vise versa - normal card can become buggy.

![photo_2020-04-26_10-59-05](https://user-images.githubusercontent.com/24802646/80301602-ad9c1200-87ad-11ea-8954-9ab7f5fbda58.jpg)
![photo_2020-04-26_10-59-16](https://user-images.githubusercontent.com/24802646/80301604-ae34a880-87ad-11ea-906c-ef8e771e41f0.jpg)
![photo_2020-04-26_11-00-54](https://user-images.githubusercontent.com/24802646/80301606-ae34a880-87ad-11ea-9a8b-8c5f6d9c1d93.jpg)
![photo_2020-04-26_11-01-03](https://user-images.githubusercontent.com/24802646/80301607-aecd3f00-87ad-11ea-901d-da548c1eff36.jpg)
![photo_2020-04-26_11-01-07](https://user-images.githubusercontent.com/24802646/80301608-aecd3f00-87ad-11ea-87fe-96a55c5f62ad.jpg)

**Comment by stave1989** [comment]
I have tje same problem on my android tablet. Any solution?

**Comment by pkishino** [comment]
This is still a problem.. on my older xperia z4 tablet, sensors/graphs etc don't show properly with above bug
