### ISSUE TITLE
Sensor card shows duplicate unit of measurement

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5637]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

This is the same issue as the Entity card one that is being fixed in PR https://github.com/home-assistant/frontend/pull/5631. I just noticed it applies to the Sensor card as well, and it can be seen on the [demo site](https://demo.home-assistant.io/#/lovelace/0):

![sensor](https://i.imgur.com/0XPzj9N.png)

## Environment

- Home Assistant release with the issue: 0.109.0b3
- Last working Home Assistant release (if known): 0.108.8
- Browser and browser version: Chrome stable
- Operating system: macOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
They are the same card. Bram has a PR to fix
