### ISSUE TITLE
Add to Lovelace button should ignore disabled entities

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5638]
## The request

Integrations can disable entities by default, for example this is the IPP printer integration which disables the uptime sensor by default: 

![disabled](https://i.imgur.com/9V5vlYM.png)

However when you use the "Add to Lovelace" button it attempts to add these disabled entities as well like you can see in this below image:

![disabled-added](https://i.imgur.com/xStQ9Fp.png)

Which I don't really think is the expected/desired behavior. A disabled entity will always show as an ugly yellow "not available" box, I don't think anybody wants that added to their UI. And if you have to go in and start deleting a bunch of unwanted things, it removes some of the convenience factor of having this button. 

In this particular example it's very easy to simply delete that last line, but with other integrations (perhaps Unifi for example) there could be _dozens_ of disabled entities where this would be a lot more tedious. I think it would make sense to just not add these in the first place?

## The alternatives

Alternative would be to keep behavior same but have some sort of toggle button or checkbox in the bottom left corner where you could quickly remove any disabled entities with one click.

**Comment by frenck** [comment]
I would consider this a bug to be honest. A user should not be able to end up with a broken thing automatically :)
