### ISSUE TITLE
Can't create "Date and/or Time Helper"

### ISSUE THREAD

**Issue by lalexdotcom** [home-assistant/frontend#5642]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I couldn't create an input_datetime via Lovelace because I cannot choose between Date, Time or DateTime...
The paper radio buttons are in the DOM, but not displayed in the browser

## Expected behavior

3 buttons allowing to choose the input_datetime "type" (has_date and has_date properties)

## Steps to reproduce
Configuration > Helpers > (+) > Date and/or Time

## Environment

- Home Assistant release with the issue:HomeAssistant Core 108.9 in Docker container
- Last working Home Assistant release (if known): ---
- Browser and browser version: Google Chrome Version 81.0.4044.122
- Operating system: MacOS Catalina

## Problem-relevant configuration

Empty input_datetime

```yaml
input_datetime:
```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

<img width="340" alt="Screenshot 2020-04-27 at 11 55 39" src="https://user-images.githubusercontent.com/15171326/80360294-69794200-887f-11ea-9a2e-303d38a0ea59.png">
<img width="497" alt="Screenshot 2020-04-27 at 11 55 27" src="https://user-images.githubusercontent.com/15171326/80360310-6e3df600-887f-11ea-9e79-20223e81229b.png">

**Comment by bramkragten** [comment]
Was fixed with #5547
