### ISSUE TITLE
Improve Layout of Config Page

### ISSUE THREAD

**Issue by Spiffo** [home-assistant/frontend#5658]
## The request

A layout that more closely resembles Lovelace for the config page would be a great improvement as far as I'm concerned. It would be much more user-friendly if the 5 different sections containing buttons (1 integrations, devices, entities and areas, 2 automations, scenes, scripts and helpers, etc.)
would 'float' like in lovelace, so we don't have to scroll all the way down to the server controls.
![Before](https://user-images.githubusercontent.com/3015566/80593884-45099b00-8a22-11ea-9c68-d8654bfb0ff1.png)
![after](https://user-images.githubusercontent.com/3015566/80593885-45a23180-8a22-11ea-8804-702e3ce9b080.png)
Boxes could even be a bit more narrow so 3 columns might fit on one screen, but this probably also depends on the language

**Comment by bramkragten** [comment]
We have a new design for the config panel and are working on implementing it. You can check it at:
https://www.figma.com/file/4LZqQZRynDZGTgA2rN35Te/Home-Assistant-config-mockup?node-id=0%3A1
![image](https://user-images.githubusercontent.com/5662298/80594633-a67e3980-8a23-11ea-82df-2f0d97896937.png)

**Comment by Spiffo** [comment]
Cool!
Only remarkI would have is that the integrations box seems to take up a lot of space, perhaps smaller icons would reduce that. Other than that I think this will completely fit my request, so closing this ticket. Can't wait for this already :)
(and thanks for introducing me to Figma :))
