### ISSUE TITLE
Add Integration list: items overrrun their window. (0.109.0)

### ISSUE THREAD

**Issue by tdejneka** [home-assistant/frontend#5659]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
The Add Integration list has items which overrun their popup window. Items at the bottom of the list are not being cropped by the window but are displayed on the background.

## Expected behavior
List items should be constrained to appear within the bounds of the popup window.

## Steps to reproduce
Go to Configuration > Integrations, click floating `+` button, scroll list of integrations and observe the bottom of the popup window.

Screenshot attached below.

## Environment

- Home Assistant release with the issue: Home Assistant Supervised 0.108.0
- Last working Home Assistant release (if known):
- Browser and browser version: Firefox 75.0
- Operating system: Ubuntu 18.04

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
![Screenshot from 2020-04-29 12-25-54](https://user-images.githubusercontent.com/44732909/80622035-36b58200-8a16-11ea-945f-9fa4014c6455.png)

**Comment by bramkragten** [comment]
Not seeing this here?

**Comment by tdejneka** [comment]
Here, the issue is not visible when I put the browser in full-screen mode:
![Screenshot from 2020-04-29 13-18-56](https://user-images.githubusercontent.com/44732909/80626260-2b655500-8a1c-11ea-92c1-cef7b29b7831.png)

but it becomes visible in non-full-screen mode:
![Screenshot from 2020-04-29 13-19-15](https://user-images.githubusercontent.com/44732909/80626329-48018d00-8a1c-11ea-8cb9-bb9af2a8052b.png)

**Comment by bonanitech** [comment]
I reported a similar issue some time ago. See #4864.

**Comment by SeanPM5** [comment]
I was able to reproduce this just now. Doesn't appear to be a browser specific issue but happens when the browser height is below 775px. 

At 775px the items remain in the dialog as expected:

![image](https://i.imgur.com/baYZWqQ.png)

But right after that things start messing up. Here's 770px, icon goes outside the dialog like in OP:

![image](https://i.imgur.com/N0UB3ks.png)

An iPad in landscape is 768px height so it will happen all the time there.

**Comment by tdejneka** [comment]
Bug is no longer evident in version 0.113.1.
