### ISSUE TITLE
I have a problem with HA Config Alexa

### ISSUE THREAD

**Issue by stevengwynjames** [home-assistant/frontend#5660]
## The alternatives

I have this screen shot but you will notice I have Type “Other” (Figure 2) I am trying to set it up too use the inbuilt templates Type LIGHT,SWITCH etc, I can import 12 devices but they are all “Other”
I read the documentation and all seems correct, yet I cannot import anything,  with the Type not being “other” .
![image](https://user-images.githubusercontent.com/34917886/80625845-abec7b80-8a45-11ea-8fae-4ef7b7b80516.png)

alexa:
  smart_home:
    locale: en-GB
    endpoint: https://api.eu.amazonalexa.com/v3/events
    client_id: amzn1*******************8
    client_secret: ************************88
  filter: 
  entity_config:
   light.test:
     name: “test”
     description: “TEST”
     display_categories: LIGHT

**Comment by zsarnett** [comment]
Please fill out the template correctly and using the correct bug template.
