### ISSUE TITLE
bug in new integration configuration page

### ISSUE THREAD

**Issue by paarak** [home-assistant/frontend#5662]
bug in new integration configuration page. all my devices are gone configuration page. installed fresh PI to test if there was an upgrade bug.
 Then all my stash was there. but as soon as I activated them were gone. 
Everything works but can't see any of the already set up integration.

May it be language. I have Norwegian

## Environment

- Home Assistant Core release with the issue: 
- Last working Home Assistant Core release (if known): 
- Operating environment (Home Assistant/Supervised/Docker/venv): 
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by havardelnan** [comment]
+1 Integrations gone in Norwegian. Show up in English.

**Comment by bramkragten** [comment]
Someone made an error in the translations on Lokalise, seems to be fixed now so should be fixed in next release.

**Comment by hulkhaugen** [comment]
Could you share the error? Maybe i did by mistake, don't want to repeat that bummer...

**Comment by bramkragten** [comment]
It seems like you corrected it, the one below was the one causing the error:
![image](https://user-images.githubusercontent.com/5662298/80890672-47d4ec00-8cbf-11ea-9185-c0954686b468.png)

**Comment by hulkhaugen** [comment]
Good to know
