### ISSUE TITLE
Use grayscale filter on logos for ignored integrations

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5667]
## The request

This is how an ignored and a discovered integration look currently side by side. Although the ignored one has gray coloring at the top to differentiate it, I think your initial focal point will still be on the brand logos.

![image](https://i.imgur.com/N4CKJ5y.png)

So I had an idea to make the brand logo for **ignored integrations** display in [grayscale](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/grayscale). In this below mockup you should be more easily able to differentiate these at a quick glance.

![image](https://i.imgur.com/KLiLqEG.png)

I realize that most people (including me) will probably just use the "Hide ignored integrations" option and rarely see these side by side. But when you do have that "Show" option on, this adds just a tiny bit more polish imo.

**Comment by matstrange** [comment]
I like this idea, it would like consistant with the greying of the top bar. 

It looks simple enough from a code perspective, although I'd like to understand the impact of adding an additional file into the brands ecosystem to support this, and how the fallback would work for it. Perhaps @frenck could offer some insight into that before I make the code change and generate all the additional greyscale images.

**Comment by ludeeus** [comment]
The grayscale would not need a separate file, it would be handled with a filter

**Comment by matstrange** [comment]
Fair enough, I thought it might be nice to cut data overhead and pre render them in greyscale as a one off task

**Comment by frenck** [comment]
@matstrange From an overhead perspective that makes not much sense.

I agree with @ludeeus here, it should be done via CSS, as we already do on other places as well.
