### ISSUE TITLE
Add to lovelace shows only Overview views, not views from other dashboards

### ISSUE THREAD

**Issue by eavanvalkenburg** [home-assistant/frontend#5668]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
When you view a device and its entities, and then click Add to lovelace, it will show only the views of your default dashboard (Overview). I've split my dashboard into multiple views and want to add entities to those views from here as well.
![image](https://user-images.githubusercontent.com/13749212/80685616-bf402b00-8ac7-11ea-8d4a-0175f38c4e9d.png)
These dashboards are my dashboards:
![image](https://user-images.githubusercontent.com/13749212/80685676-dd0d9000-8ac7-11ea-8223-3c7e30d19c94.png)

## Expected behavior
Show all views from all dashboards, probably grouped by dashboard.

## Steps to reproduce
1. create a second dashboard, with one or more views
2. go to a device detail page
3. click Add to lovelace button

## Environment

- Home Assistant release with the issue: 0.109.0
- Last working Home Assistant release (if known): None
- Browser and browser version: Edge Dev
- Operating system: Windows 10

**Comment by spacegaier** [comment]
@bramkragten This was already solved by your PR https://github.com/home-assistant/frontend/pull/6478 and my test just now confirmed that. Can be closed I think.
