### ISSUE TITLE
The "two" variant for plural in translations for some languages

### ISSUE THREAD

**Issue by bieniu** [home-assistant/frontend#5669]
## The request
Some languages (i.g. Polish) need `two` variant for plural in translations.
For example, string `ui::panel::config::integrations::config_entry::entities` has two variants, `one` and `other`. But in Polish should be three variants: `one`, `two` and `other`.
```
{count} {count, plural,
  one {encja}
  two {encje}
  other {encji}
}
```
This applies to these strings:
```
ui::panel::config::integrations::config_entry::entities
ui::panel::config::integrations::config_entry::devices
ui::components::relative_time::duration::week
ui::components::relative_time::duration::day
ui::components::relative_time::duration::hour
ui::components::relative_time::duration::minute
ui::components::relative_time::duration::second
ui::duration::hour
ui::duration::minute
ui::duration::second
ui::duration::week
ui::duration::day
```

**Comment by bramkragten** [comment]
This is something you can do in Lokalise I think? That needs no changes in the code.

**Comment by bramkragten** [comment]
See: https://formatjs.io/docs/icu-syntax#plural-format

**Comment by bieniu** [comment]
@bramkragten So is this correct? And nothing else is needed?
```
{count} {count, plural,
  one {encja}
  two {encje}
  =3 {encje}
  =4 {encje}
  other {encji}
}
```

**Comment by bramkragten** [comment]
I don't think the two is supported, the rest should work.

**Comment by bieniu** [comment]
OK, thanks for help.
