### ISSUE TITLE
Integration page doesn't work if language is set to Norsk Bokmål

### ISSUE THREAD

**Issue by stigvi** [home-assistant/frontend#5670]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

If the language in settings is set to Norsk Bokmål, the integration page does not show any integrations.

## Expected behavior

I expect the same list of integrations as when the language is set to english

## Steps to reproduce

Change language to Norsk Bokmål in the user profile and then select integrations in settings

## Environment

- Home Assistant release with the issue: 0.109.0 and 0.109.1
- Last working Home Assistant release (if known): 0.108.9
- Browser and browser version: Edge based on chromium
- Operating system: Windows 10

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Seems like someone translated it wrong. Seems to be fixed in Lokalise now so should be ok the next release.

**Comment by stigvi** [comment]
> Seems like someone translated it wrong. Seems to be fixed in Lokalise now so should be ok the next release.

Translated wrong? Could that really lead to functional errors? Is the fix tested?

**Comment by bramkragten** [comment]
If you change placeholders and other things like plural keys, then it won't render.

**Comment by stigvi** [comment]
Can you open this again as it is not fixed in 0.109.2

**Comment by bramkragten** [comment]
0.109.2 didn't include a new frontend.
