### ISSUE TITLE
UI not showing binary sensor device class state correctly 

### ISSUE THREAD

**Issue by Yvon-Indel** [home-assistant/frontend#5674]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Hi,

Just after updating to v0.109.0, the way all binary sensors are displayed in the frontend changed.

**before:**
- device_class: opening => show "open" or "closed"  

**now:**
- device_class: opening => show "on" or "off"

Seems to be the same with other device_class
I guess device class in customize.yaml for these sensors is not used anymore.

I try with french language and english language of the UI with same result.

I don't see any change about this in the change log.

Thanks.
## Expected behavior

Same as before update, state displayed on the frontend as in the doc : [https://www.home-assistant.io/integrations/binary_sensor/](https://www.home-assistant.io/integrations/binary_sensor/)
 
## Environment

- Home Assistant release with the issue: 0.109.0 and 0.109.1
- Last working Home Assistant release (if known): before 0.109.0
- Browser and browser version: Chrome Version 81.0.4044.122 (Build officiel) (64 bits)
- Operating system: HassOS 3.13

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
I don't see this, can you share the state and attributes of the entity?

**Comment by joshtbernstein** [comment]
I'm seeing something similar with the lovelace home feed card: https://github.com/gadgetchnnel/lovelace-home-feed-card/issues/40

**Comment by bramkragten** [comment]
Yes custom card will need to update <https://developers.home-assistant.io/blog/2020/04/23/frontend-translations>

**Comment by Yvon-Indel** [comment]
> I don't see this, can you share the state and attributes of the entity?
> (And try a full refresh of your browser)

Hi,

yes, i try full refresh of my browser and try on another computer too.

here is the state and attributes:

![State_trouble](https://user-images.githubusercontent.com/61465979/80820359-00733080-8bd7-11ea-84b4-ff694ebfd98c.jpg)

thanks.

**Comment by bramkragten** [comment]
Do you have a custom component that is not in its own folder?

**Comment by Yvon-Indel** [comment]
> Do you have a custom component that is not in its own folder?

Yes, your right 👍 

One of my custom component was in the "custom component" directory root  and not its own folder.

All is working now.

Thanks a lot.

**Comment by Alfiegerner** [comment]
I'm seeing upgrading from 108 and now on 109.2:

![image](https://user-images.githubusercontent.com/596188/80851841-27ce0a00-8c78-11ea-9c1e-24af6de87fe2.png)

All custom components in their own folder:

![image](https://user-images.githubusercontent.com/596188/80851866-5cda5c80-8c78-11ea-8d44-ba41f5dff084.png)

Any one have any suggestions?

**Comment by Alfiegerner** [comment]
Noticed this issue has been closed, opened new one [here](https://github.com/home-assistant/frontend/issues/5701).
