### ISSUE TITLE
Default UI dashboard fails to render if 'config' option is removed.

### ISSUE THREAD

**Issue by tdejneka** [home-assistant/frontend#5678]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
The default dashboard's cards are not rendered if you remove the `config` option from `configuration.yaml`.

If you replace the `default_config` option with just these options:
```
frontend:
config:
```
the default Lovelace dashboard is rendered correctly and the menu includes `Configuration` (as expected).

If you remove the `config` option, all that should happen (in theory) is the menu will no longer display the `Configuration` item. In fact, the menu item is removed but it _also prevents the default dashboard from being rendered_. The menu and header are displayed but the default dashboard's cards are not. All it does is display a rotating progress indicator.

NOTE:
The default dashboard is unmodified and is under direct control of Home Assistant.

## Expected behavior
It should render the default dashboard's cards

## Steps to reproduce

Ensure the default dashboard is unmodified and under Home Assistant's control. Create a second dashboard and make some sort of minor modification to it so it is no longer under Home Assistant's direct control.

Erase or comment out `default_config` then enter:
```
frontend:
config:
```
Restart Home Assistant. After startup, the default dashboard is displayed and the Configuration menu item is present. So far, it works as expected.

Now remove or comment out the `config` option. Restart Home Assistant. On my system, the Configuration menu item is no longer displayed (as expected) but the default dashboard fails to render.

Now switch to the second dashboard (the one you modified). in my case, this one is instantly and correctly rendered. Switch back to the default one and it still fails to render.

## Environment

- Home Assistant release with the issue: Home Assistant Supervised 0.109.1
- Last working Home Assistant release (if known): unknown
- Browser and browser version: Firefox 75
- Operating system: Ubuntu 18.04

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
We now load config by default.

**Comment by tdejneka** [comment]
> We now load config by default.

Confirmed that in 0.113.1 the Configuration menu is always displayed, even if the `config` option is removed from `configuration.yaml`.

Given that it the option no longer controls the visibility of the Configuration menu, it's effectively deprecated?
