### ISSUE TITLE
Open / close cover buttons disabled

### ISSUE THREAD

**Issue by gezquerra** [home-assistant/frontend#5679]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem

After last update 109.1, the open / close buttons of cover devices are disabled on lovelace interface (stop button remain enabled).

## Expected behavior

![image](https://user-images.githubusercontent.com/14371362/80758748-6cea2300-8b36-11ea-880d-964c07f578f1.png)

## Steps to reproduce

    1. Add cover device of command_line platform
    2. Setup open/close/stop commands
    3. Reboot hassio
    4. Check the device properties
    5. The open / close commands are disabled

## Environment

Home Assistant 0.109.1

- Home Assistant release with the issue: 109.1
- Last working Home Assistant release (if known): 108.9
- Browser and browser version: Chrome 81.0.4044.129
- Operating system: Windows 10 x64

## Problem-relevant configuration

cover:
  - platform: command_line
    covers:
      porta_menjador:
        command_open: /bin/echo -e "xxxxxxxxxxxx" | nc yyy.yyy.yyy.yyy 6653 -u -w 1
        command_close: /bin/echo -e "xxxxxxxxxxxx" | nc yyy.yyy.yyy.yyy 6653 -u -w 1
        command_stop:  /bin/echo -e "xxxxxxxxxxxx" | nc yyy.yyy.yyy.yyy 6653 -u -w 1

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
What is the state of the entity?

**Comment by gezquerra** [comment]
> What is the state of the entity?

**Comment by gezquerra** [comment]
The state is "unknown"

**Comment by chocobn69** [comment]
Hi,
I have exactly the same bug since 0.109.0 update

I tried to change `disabled=""` HTML entity on disabled arrow, and it worked : cover can be controled, so it looks like it's a frontend error

**Comment by bramkragten** [comment]
https://github.com/home-assistant/frontend/pull/5687
