### ISSUE TITLE
Create Home Assistant updating dialog

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#5681]
## The request

When Home Assistant is updating, we should block the whole screen and show "Home Assistant is updating" with a spinner.

We will observe the `hass.connection` and on reconnect we will reload the page.

Make sure that the [reload frontend after backend is upgraded logic](https://github.com/home-assistant/frontend/blob/dev/src/layouts/home-assistant.ts#L79-L92) is disabled while the dialog takes over this logic.

## The alternatives

Do what we do now, which shows the update button light up in red.

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/issues/4387
