### ISSUE TITLE
In case of several similar device we can see several cards in the integration page 

### ISSUE THREAD

**Issue by Korte68** [home-assistant/frontend#5686]
I have a lot of konnected modul, the HA find them all, which is good :)
But it would be better if only one card appear on the integration page with several device.
Now i can see a lot of card and every card represent one konnected device.

It would be better, if every kind of added integration represent in only one card, and if the user has more device about the same kind of integration, it is added to the sam card.

**Comment by Korte68** [comment]
<img width="1010" alt="konnected" src="https://user-images.githubusercontent.com/43949101/80798350-7dd17d80-8ba4-11ea-95a3-478af405e53f.png">

See what i suggest...

Thank you

**Comment by frenck** [comment]
Already done in https://github.com/home-assistant/frontend/pull/5646

Part of 0.110

**Comment by Korte68** [comment]
What a lightning speed :) impressive.

Thank you
