### ISSUE TITLE
Cover up and down no longer working in Lovelace in 0.109

### ISSUE THREAD

**Issue by soffes** [home-assistant/frontend#5690]
## The problem

Since upgrading to 0.109.0 (and 0.109.1), controls for covers aren't working in Lovelace. You can see the up and down buttons are grayed out.

<img width="371" alt="Screen Shot 2020-05-01 at 6 00 49 AM" src="https://user-images.githubusercontent.com/52870/80807205-6c22b280-8b71-11ea-9682-083b32ed4a01.png">

They do work via services though. I was able to open and close just fine with `cover.open_cover`, etc.

My shades are using the `somfy_mylink` integration.

## Environment

- Home Assistant Core release with the issue: 0.109.1
- Last working Home Assistant Core release (if known): 0.108.8
- Operating environment (Home Assistant/Supervised/Docker/venv): Hass.io on Synology
- Integration causing this issue: `somfy_mylink`
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/somfy_mylink/

## Problem-relevant `configuration.yaml`

```yaml
somfy_mylink:
  host: !secret somfy_host
  system_id: !secret somfy_system_id
```

## Traceback/Error logs

Nothing in the logs related to covers or `somfy_mylink`.

## Additional information

It was working in 0.108.8. I haven't changed [my configuration](https://github.com/soffes/home) since upgrading.

**Comment by bramkragten** [comment]
https://github.com/home-assistant/frontend/pull/5687
