### ISSUE TITLE
MQTT Climate device does not display operation modes

### ISSUE THREAD

**Issue by subzero79** [home-assistant/frontend#5700]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

My current mqtt climate device is not displaying the operation modes list. Two days ago i upgraded from 0.107.7 to 0.109.1  then i started noticing the climate entity frontend state was not being displayed. 

The topics and payloads have not been touch since i created the mqtt model in node-red. In the attached ss you can see the op mode being displayed blank

![screenshot--2020 05 02-10_40_36](https://user-images.githubusercontent.com/7058119/80850844-7fad4680-8c61-11ea-8f05-cfbcfc7ecd75.png)
![screenshot-2020 05 02-10_39_46](https://user-images.githubusercontent.com/7058119/80850846-80de7380-8c61-11ea-8935-b53176b03173.png)

## Expected behavior

To test this i went and downgraded back to 0.107.7 now the entity started reporting back the state in the frontend with the corresponding list in the operation mode

![Screenshot from 2020-05-02 10-30-56](https://user-images.githubusercontent.com/7058119/80850907-d450c180-8c61-11ea-9051-b9cc243247e7.png)

I upgraded then to 0.108.9, no issues at all. Finally another upgrade to 109.0, restart homeassistant the frontend still displays the climate entity properly with state, but then the frontend reload notification pops up click reload and back to the same. Another upgrade to latest 0.109.2 an still no state

## Steps to reproduce

1. Create mqtt climate entity via discovery
2. Add the entity to the frontend

## Environment

Home Assistant frontend: 20200427.1 - latest
Home Assistant: via  virtualenv with python 3.7 in debian buster
Browsers tested: Chrome  81.0.4044.129 (Official Build) (64-bit), Firefox 75.0 (64-bit), iOS homeassistant app

This is is the payload for mqtt discovery
```json
{"platform":"mqtt","name":"House AC","initial":23,"unique_id":"house_ac","min_temp":18,"max_temp":30,"modes":["off","cool","heat","auto","fan_only","dry"],"fan_modes":["slow","low","low-mid","medium","mid-high","high","power","auto"],"mode_state_topic":"lg_unit/ac/status","mode_state_template":"{{ value_json.OpMode }}","mode_command_topic":"lg_unit/ac/OpMode/set","temperature_state_topic":"lg_unit/ac/status","temperature_state_template":"{{ value_json.TempCfg }}","temperature_command_topic":"lg_unit/ac/TempCfg/set","current_temperature_topic":"lg_unit/ac/status","current_temperature_template":"{{ value_json.TempCur }}","temperature_unit":"C","fan_mode_state_topic":"lg_unit/ac/status","fan_mode_state_template":"{{ value_json.WindStrength }}","fan_mode_command_topic":"lg_unit/ac/WindStrength/set","device":{"identifiers":["8921beb0-4135-11e9-96db-203dbda1277d"],"connections":[["mac","20:3d:bd:a1:27:7d"]],"model":"RAC_056905_WW (WH24SL-18)","manufacturer":"LG","sw_version":"2.5.8_RTOS_3K","name":"house ac"},"json_attributes_topic":"lg_unit/ac/status","json_attributes_template":"{{ value_json.Attributes | tojson }}"}
```

This is a mode state topic payload

```json
lg_unit/ac/status {"OpMode":"off","WindStrength":"medium","TempCfg":"23","TempCur":"19","Attributes":{"JetMode":"off","Purification":"off","HSwing":"5","VSwing":"0","Filter":{"Remaining":"19%","Usage":"582 hours"},"Energy":{"daily":{"energy":"0 kWh","uptime":"0 hours"},"weekly":{"energy":"4.6 kWh","uptime":"4 hours"},"monthly":{"energy":"0 kWh","uptime":"0 hours"}}}}
```

- Home Assistant release with the issue: 0.109.0 to  0.109.2
- Last working Home Assistant release (if known): 0.108.9
- Browser and browser version: Chrome  81.0.4044.129 (Official Build) (64-bit), Firefox 75.0 (64-bit),
- Operating system: virtualenv with python 3.7 in debian buster

## State of relevant entities

Here is the ss of the state which shows accordingly

![Screenshot from 2020-05-02 11-00-07](https://user-images.githubusercontent.com/7058119/80851289-2e528680-8c64-11ea-9d6b-7fdccf46de58.png)

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

when reloading the page this only error comes

```log
translations-mixin.ts:182 Uncaught (in promise) {code: "unknown_error", message: "Unknown error"}
_loadHassTranslations @ paper-ripple.js:356
async function (async)
_loadHassTranslations @ paper-ripple.js:356
value @ home-assistant.ts:42
initializeHass @ paper-ripple.js:356
value @ home-assistant.ts:42
async function (async)
value @ home-assistant.ts:42
value @ home-assistant.ts:42
performUpdate @ app.573b4877.js:2
_enqueueUpdate @ app.573b4877.js:2
async function (async)
_enqueueUpdate @ app.573b4877.js:2
_requestUpdate @ app.573b4877.js:2
initialize @ app.573b4877.js:2
initialize @ app.573b4877.js:2
A @ app.573b4877.js:2
V @ app.573b4877.js:2
F @ paper-ripple.js:356
(anonymous) @ paper-ripple.js:356
(anonymous) @ paper-ripple.js:356
(anonymous) @ paper-ripple.js:356
(anonymous) @ paper-ripple.js:356
(anonymous) @ paper-ripple.js:356
(anonymous) @ paper-ripple.js:356
(anonymous) @ paper-ripple.js:356
(anonymous) @ paper-ripple.js:356
(anonymous) @ paper-ripple.js:356
(anonymous) @ paper-ripple.js:356
(anonymous) @ paper-ripple.js:356
(anonymous) @ paper-ripple.js:356
(anonymous) @ paper-ripple.js:356
se @ paper-ripple.js:356
r @ home-assistant-main.ts:151
(anonymous) @ home-assistant.ts:42
i @ app.573b4877.js:2
(anonymous) @ app.573b4877.js:2
(anonymous) @ app.573b4877.js:2
```

```txt

```

## Additional information

I activated the demo climate entities to see if some of them showed the same behaviour, they have their operation modes in blank.

![Screenshot from 2020-05-02 11-06-14](https://user-images.githubusercontent.com/7058119/80851419-1d564500-8c65-11ea-9517-3630facb67bc.png)
![Screenshot from 2020-05-02 11-07-50](https://user-images.githubusercontent.com/7058119/80851426-2f37e800-8c65-11ea-85bb-7322c08249fb.png)

I did one testing from the frontend and the operation is not compromised as it if you select something from the blanks still works.

**Comment by bramkragten** [comment]
Fixed in https://github.com/home-assistant/core/pull/35032
