### ISSUE TITLE
Developer Tools, Supervisor, Configuration pages inconsistent on mobile

### ISSUE THREAD

**Issue by CheeseySandal** [home-assistant/frontend#5702]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The above pages are inconsistent. 

Dev Tools is coloured to match the theme and has the hamburger to toggle the sidebar. 
![Screenshot_20200502-081937](https://user-images.githubusercontent.com/26098093/80858108-0a387a80-8c4f-11ea-92d8-f4a5c8d7c555.jpg)

Configuration is now white but still has the hamburger to navigate using the sidebar.
![Screenshot_20200502-081947](https://user-images.githubusercontent.com/26098093/80858136-3bb14600-8c4f-11ea-834a-8a3334f54c0e.jpg)

Supervisor is now white and has icons along the bottom but no hamburger to navigate using the sidebar. Users now forced to use back button to navigate. 
![Screenshot_20200502-081929](https://user-images.githubusercontent.com/26098093/80858203-b11d1680-8c4f-11ea-8faf-ad40dd7b4563.jpg)

## Expected behavior
Pages should either be theme colour or white. Sidebar should be available from the Supervisor page

## Environment

- Home Assistant release with the issue: 0.109.x
- Last working Home Assistant release (if known): 
- Browser and browser version: Firefox, Chrome, HA app
- Operating system: Android 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by anybody84** [comment]
Moreover, it takes few seconds until the bottom icons appear. When I open the Supervisor page it looks like that:
![Screenshot_20200502-095631_Home Assistant](https://user-images.githubusercontent.com/37036776/80864022-2b658f00-8c80-11ea-9105-e1f3cab742ed.jpg)

It's the mobile app, Android 10

**Comment by CheeseySandal** [comment]
Have just noticed that if I press where I expect the hamburger icon to be on the Supervisor page, I get taken to Dev tools. Not sure if there's a white on white icon hidden there.
