### ISSUE TITLE
Add add-on changelog

### ISSUE THREAD

**Issue by frenck** [home-assistant/frontend#5709]
## The request

The add-on changelog is only visible when an add-on is pending.
When using auto-updates for add-ons, this becomes a problem, as you can never view it.

![image](https://user-images.githubusercontent.com/195327/80860834-a7ed7300-8c6a-11ea-9862-56dd6334e5df.png)

Also, when updated, there is no way to check back on version history.

The Supervisor API has an endpoint for changelog. My suggestion is to add a permanent tab to the add-on page with the changelog.

Even when the add-on is not installed, it can be nice to see progress/maintenance on an add-on.

**Comment by bramkragten** [comment]
Tabs are full, max of 4.

**Comment by frenck** [comment]
> My suggestion is to add a permanent tab to the add-on page with the changelog.

It was a suggestion.

Any other solution to be able to view the changelog would be appreciated. Especially with the auto-update, there is no way to see what happened.

I raised this issue after having another user asking "Where can I find the changelog".

**Comment by frenck** [comment]
Hmmm, mobile I guess.

Maybe as a second card underneath the documentation in the documentation tab?

**Comment by bramkragten** [comment]
Yeah or in a popup like we do for a new version?

**Comment by SeanPM5** [comment]
I'm not sure people would expect version history on the documentation tab? It's not really documentation, but info.

I think either make a dedicated version history card under the description card on info tab, or do something along these lines:

![image](https://i.imgur.com/pmfAAmB.png)

This would move the version number from the far right (where it feels "lonely" and out of place IMO) and with all the other info. Version History would be a link that opens the changelog dialog. Maybe someone has a better idea though.
