### ISSUE TITLE
Conditional card: add 'or' to conditions

### ISSUE THREAD

**Issue by andriej** [home-assistant/frontend#5712]
## The request

Ability to select 'or' condition for 'conditional' lovelace card

## The alternatives

Custom cards, but why if there's a solution right in HA

## Additional information

Same as conditions in automations, conditional card should have ability to select 'or' instead of the default and only 'and' for multiple entities.

Example? I have integration for few weather warnings (6 of them). One of them can be 'on' (binary sensors) and I'd like to show glances card with all of them. 
Currently, I can't.

**Comment by andriej** [comment]
Oh well, need coffe. I've managed to. ;-)

**Comment by agneevX** [comment]
How did you solve this?
