### ISSUE TITLE
New weather card sometimes doesn't render all days

### ISSUE THREAD

**Issue by TASSDevon** [home-assistant/frontend#5718]
Using HA Core 0.109.0

Sometimes the weather card only renders 3 days instead of 5:

<img width="508" alt="Screenshot 2020-05-02 at 16 23 04" src="https://user-images.githubusercontent.com/6917072/80866869-645a2f80-8c91-11ea-93b3-ba19bcc39606.png">

When I do a page refresh/reload I get all 5:

<img width="502" alt="Screenshot 2020-05-02 at 16 23 12" src="https://user-images.githubusercontent.com/6917072/80866874-6de39780-8c91-11ea-8720-3af93bece164.png">

**Comment by zsarnett** [comment]
#5656
