### ISSUE TITLE
Cast stops after 10 minutes when photo frame kicks in suddenly

### ISSUE THREAD

**Issue by greberg** [home-assistant/frontend#5729]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem

Seems like cast stops working after 10 minutes if I'm not interacting with the Nest Hub Display.
## Expected behavior
Cast view should continue to work until I close the media.player or interact with Hub

## Steps to reproduce

1. Service
2. cast.show_lovelace_view
3 entity_id: media_player.kitchen
dashboard_path: lovelace
view_path: home_cast 

Everything works as expected but after 10 minutes it closes the cast and it goes into photo frame. I have tried to find if their is any setting in Google Home App but nothing. I first thought it was due 0.109 release because it has been working flawless before that but unfortunatly not, moving back to 0.108.9 didn't work. Even tried with different pychromecast versions but no success. Last thing that I could thought about is that I got a new pre release version for my Nest Hub:
System: 203796
Cast: 1.46.203796

## Environment

- Home Assistant release with the issue: 0.109.2
- Last working Home Assistant release (if known): 0.108.9 (Although can't go back to this and it works now)
- Browser and browser version:
- Operating system: Nest Hub System: 203796
Cast: 1.46.203796

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
I have tried to inspect using chrome://inspect/#devices but nothing shows up when view is closed down and photo frame is shown. Anyone else have problem with Cast in 0.109 or anyone else have pre release 1.46 with Nest Hub

**Comment by greberg** [comment]
Can confirm that the same thing happens using CATT (https://github.com/skorokithakis/catt) So I guess this is something with Cast Firmware and/or perhaps pychromecast

**Comment by tungmeister** [comment]
Also experiencing this on my nest hub on the preview firmware 203796 using Catt. Hoping this is a bug with the preview firmware as this is the primary use for the device.

**Comment by greberg** [comment]
> Also experiencing this on my nest hub on the preview firmware 203796 using Catt. Hoping this is a bug with the preview firmware as this is the primary use for the device. Have you tried leaving the preview program?

Yes I have left the program and also made a factory reset but unfortunatly I need to wait for next official firmware to be pushed so it is impossible to trigger it myself. (A very strange update process I must say :-))

**Comment by radomir75** [comment]
The same problem. Someone has a solution?

**Comment by maxi1134** [comment]
Same problem here, using a node-red flow to cast my stuff every 10 minutes but it's getting old quickly.

Anyone has a better fix?

**Comment by jparthum** [comment]
Also here, and also with CATT as well as [DashCast](https://madmod.github.io/dashcast/).

I'm not actually getting _disconnected_ though.  My Google Home app, my browser Cast Tab, and `mgs.status` from [node-red-contrib-cast](https://github.com/Hypnos3/node-red-contrib-cast) all show that I'm still casting.  I've also tried reverting back through a few versions of pychromecast with no luck.  

I have four hubs and this issue began affecting them at different times over the past week or so.  Unfortunately I didn't have a chance to compare versions, but I highly suspect Google has ~~screwed up~~ "enhanced" our firmware. :angry:

**Comment by Fabenissimo** [comment]
Issue still exists. Running HA 0.114.1

**Comment by radomir75** [comment]
The problem still exists.  HA 0.114.4

**Comment by norjen** [comment]
The problem still exists. HA 0.115.0

**Comment by loeffen** [comment]
also with HA 0.115.6 problem exists

**Comment by bramkragten** [comment]
This is not HA version related. Also, it seems like we can not fix this, it is something Google has changed and I currently see no way to work around it (I already tried all the timeout settings). Maybe if we would play media or something it would stay active, but that is hacky, and not sure what consequences it would have.

But I will continue to check for a solution.

**Comment by tungmeister** [comment]
The easiest solution at present is to setup an automation that recasts every 10 mins while ever you want the content displayed

**Comment by jparthum** [comment]
> Maybe if we would play media or something it would stay active
Unfortunately, I don't even think that would work.  I set up an app using Actions on Google and Diagflow to stream from a music server and Google's own API also loses connection when a song longer than 10 minutes is played.

We need a custom ROM so we can take ownership of these devices, but there doesn't seem to be much interest yet in the ROM developer communities.

**Comment by kind3r** [comment]
This is still an issue, altho not sure it can be solved by HA team.
As a workaround I have made an automation to re-cast every 9 min if the device is idle. You can find the blueprint here: https://community.home-assistant.io/t/cast-and-re-cast-a-lovelace-view-to-a-google-hub/259631 . Not pretty but gets the job done.

**Comment by twodice** [comment]
> This is not HA version related. Also, it seems like we can not fix this, it is something Google has changed and I currently see no way to work around it (I already tried all the timeout settings). Maybe if we would play media or something it would stay active, but that is hacky, and not sure what consequences it would have.
> 
> But I will continue to check for a solution.

This does work - if you set up an infinite queue of silent audio it'll stay alive for quite a while, but it has a distracting media status with moving progress bar on all of the other cast remotes including home assistant. If you play a 1x1 png every 90 seconds or so the progress bar is gone, but it does still show up in the notifications of an android device with controls. As a workaround, these can be disabled for the entire device in the Google Home app. I haven't yet figured out how to suppress the cast controls + convince the player to avoid sleeping. I've tried a number of things on the public API for the cast receiver but haven't yet found anything that will cancel the idle timer other than "playing" something. 

Disabling the cast controls + doing this would probably be sufficient for my purposes, but I'm not sure it's the best solution to submit upstream.
