### ISSUE TITLE
Add-on Store - move repositories to dialog

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5732]
## The request

The UI for the Add-On Store has always kind of prioritized the wrong information IMO. When you click on a page called "Add-On Store" you expect to see _actual add-ons_, but instead you see a bunch of GitHub repo cards first.

Having just 4 of these cards means you already can't see any add-ons on a mobile device without having to scroll first - not good. And even on desktop it's not great either, as you can see in this example below: 

![repos](https://i.imgur.com/zWclytY.jpg)

That is an enormous waste of space for what is essentially nothing more than just URL's. The "Add new repository by URL" card is not as easy to see, it blends in with all the other ones. And as you add more repos the placement of that card is going to shift around the screen rather than being locked in a specific place - so you can never form any muscle memory for where the "add" button is.

It's also inconsistent - these github cards are larger in size and cannot be clicked on, the add-on cards just beneath them are smaller in size and _can_ be clicked on. So two different card behaviors on the very same page, not good.

<hr>

### Proposal

There would maybe be a FAB / floating action button with "Manage Repositories" text. This doesn't necessarily _have_ to be a FAB, it could be some button near the top right of the page or something (maybe to the right of the search field?). 

![manage-button](https://i.imgur.com/Yd5bWiH.png)

We could figure out how the button would look / be placed, but the more important part of this proposal is moving it to a dialog. When you click the button, it brings up a dialog where you can add or edit the repositories, like so:

![repos](https://i.imgur.com/l84sXgh.png)

This is inspired by both the "Helpers" UI and the custom repos in HACS. This is a much better use of space. A lot of users are going to be happy with the default add-ons and never bother adding any custom repos. Other users might only add maybe one or two repos during their whole time using Home Assistant. 

Adding and removing repos is just not an action you do that often, so it doesn't need to be front and center all the time. This proposal solves that problem and would make the add-on store page look a lot cleaner IMO by putting the focus on the add-ons themselves.

**Comment by ludeeus** [comment]
I really like this!
But I do think a better place to initiate that popup is by changing the reload icon to vertical dots and have both "repositories" and "reload" in a menu there.
![2020-05-03_00-42-05](https://user-images.githubusercontent.com/15093472/80893940-f0427a80-8cd6-11ea-94f2-ab220470f72b.gif)

**Comment by SeanPM5** [comment]
Thanks.

Having it there would be fine with me as I think both of those options are seldomly used and don't need to occupy a ton of UI space. But I don't really have any strong opinions on the button part, would be interested to hear others thoughts.

**Comment by richard-scott** [comment]
Since the migration of the store to the Configuration sub menu my add on repositories keep randomly removing themselves from the UI.

When I try and add them back in I get told they are already there. All my installed add one now have the green puzzle icon and now get no updates as HA doesn’t know what/where to check.
