### ISSUE TITLE
Minor cosmetic errors on Info page.

### ISSUE THREAD

**Issue by tdejneka** [home-assistant/frontend#5737]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

**Developer Tools > Info** page contains three cosmetic errors:
- Two missing icons (Hass.io and Lovelace)
- One spelling error (Asssistant)

![Annotation 2020-05-02 230929](https://user-images.githubusercontent.com/44732909/80897796-b9666780-8cca-11ea-8789-c2b44dd5f57c.png)

![Annotation 2020-05-02 230812](https://user-images.githubusercontent.com/44732909/80897798-bf5c4880-8cca-11ea-8975-da0a052e29b2.png)

## Steps to reproduce
Got to **Developer Tools > Info** page.

## Environment

- Home Assistant release with the issue: Home Assistant Supervised 0.109.3
- Last working Home Assistant release (if known):
- Browser and browser version: any
- Operating system: Ubuntu 18.04

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ludeeus** [comment]
I've added a PR to the core repo to fix the typo.
The missing images need to be added to <https://github.com/home-assistant/brands>, when they are there, they will show up.

Since both these "errors" are/should be handled in other repositories I'll close this issue, since it's not directly related to the frontend.

**Comment by bramkragten** [comment]
The icons can be supplied in the brands repo: https://GitHub.com/homeassistant/brands

For the other one Ludeeus made a PR in the core repo.

**Comment by tdejneka** [comment]
> I've added a PR to the core repo to fix the typo.
The missing images need to be added to https://github.com/home-assistant/brands,

Thank you for creating the PR. Can you please transfer this issue to the brands repo so that the task of adding appropriate logos can be assigned to someone? Thank you.

**Comment by frenck** [comment]
@tdejneka There is another issue on that, will pick that up in a second. Will probably be fixed on the next release.

**Comment by tdejneka** [comment]
@frenck 
I appreciate the information.Thank you!
