### ISSUE TITLE
Media control card TTS box ignores TTS settings in configuration.yaml 

### ISSUE THREAD

**Issue by jonnomolenaar** [home-assistant/frontend#5743]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

If you change things in the configuration.yaml for tts, the Lovelace media control card doesn't change with for example the language or the service you put in. But always uses Google translate in English.
## Expected behavior
Changes the settings of that TTS box according to your settings in config.yaml

## Steps to reproduce
Change language in TTS in your config.yaml and type something in media control TTS box

## Environment

- Home Assistant release with the issue: 1.109.3
- Last working Home Assistant release (if known): ?
- Browser and browser version: doesn't matter, in all browsers
- Operating system: Ubuntu 18.04 HA in docker

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
tts:
  - platform: google_translate
    language: 'nl'
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
You probably have cloud enabled and it is using the tts service from cloud instead of the google tts you are configuring.

We should look at a way to select a TTS service to use in the frontend.

**Comment by jonnomolenaar** [comment]
> You probably have cloud enabled and it is using the tts service from cloud instead of the google tts you are configuring.
> 
> We should look at a way to select a TTS service to use in the frontend.

Aaah yeah that's the problem! Maybe a service data option to choose between the config.yaml or cloud voice service?
