### ISSUE TITLE
Remember last used tab

### ISSUE THREAD

**Issue by Scrumplex** [home-assistant/frontend#5746]
## The request

I propose a setting (per user prehabs?) to let the lovelace UI remember which tab was last used.
This makes using the UI on mobile devices easier, as one does not have to find a commonly used tab in the tab bar.

## The alternatives

There are no alternatives for this right now.

## Additional information
This setting should perhabs be off by default for existing accounts to minimize any power-user confusion.

**Comment by zsarnett** [comment]
This should not be a frontend issue. But an issue for the applications (ios and android)

**Comment by Scrumplex** [comment]
> This should not be a frontend issue

Why?
My idea was that this setting would be put somewhere on the user's settings. So it should also appear in the Web UI from a browser
