### ISSUE TITLE
Trapped in Supervisor after entering an add-on page while having "Always hide the sidebar" active

### ISSUE THREAD

**Issue by bonanitech** [home-assistant/frontend#5752]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When I have "Always hide the sidebar" on if I go to Supervisor and open an add-on, either in Dashboard or Add-on store, I can't "exit" Supervisor.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/29807944/81018892-6d830200-8e33-11ea-811c-7704f8013b5f.gif)

## Expected behavior

Sidebar to appear when I click the icon in the top left corner.

## Steps to reproduce

1. Go to the user profile page
1. Activate "Always hide the sidebar"
1. Go to Supervisor
1. Go to any add-on in Dashboard or Add-on store
1. Try to get back to the Lovelace UI

## Environment

- Home Assistant release with the issue: 0.109.3
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome 81.0.4044.129 and Safari 13.1 (15609.1.20.111.8)
- Operating system: macOS Catalina 10.15.4

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ludeeus** [comment]
This was fixed here <https://github.com/home-assistant/frontend/pull/5724> and will be part of an upcoming supervisor update.
For now, you can just swipe in from the left.
