### ISSUE TITLE
Setting camera entities to 'live' prevents states from loading and makes GUI unstable

### ISSUE THREAD

**Issue by xbmcnut** [home-assistant/frontend#5753]
## Checklist

- [ X ] I have updated to the latest available Home Assistant version.
- [ X ] I have cleared the cache of my browser.
- [ X ] I have tried a different browser to see if it is related to my browser.

## The problem
When displaying a view with cameras (tested with Synology and Generic), the graph line in a sensor card often has a spinning icon for >30s and the states history never loads. When the GUI is in this 'state', often other pages like Supervisor, Configuration and Develop Tools fail to load presenting just a blank screen. F5 does not work when that happens. The only way to restore is to close and reopen the tab.
 Video of behaviour here https://youtu.be/kw8zp2XSZ20. Note that although I have custom cards on this page in the video, I tried again with just standard LL cards with the same behaviour.

## Expected behaviour

 Removing the cameras allows the graphs to display and the states history is instant. Clicking around Supervisor, Configuration and Develop Tools never falters without cameras in the view.

## Steps to reproduce
Add four or so cameras to a view page that also has sensors on it. See if the sensors load after a F5 and then check the states history to see if that will load.

## Environment

- Home Assistant release with the issue: 0.109.4
- Last working Home Assistant release (if known): Still an issue as far back as 0.105.5
- Browser and browser version: FF 75.0 and Chrome 81.0.4044.129 (Official Build) (64-bit)
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by xbmcnut** [comment]
Seems the issue is related to me having all six of the cameras (two still images) set to 'live'. If I leave five off them at 'live' and put one on 'auto', everything starts working normally. For some reason, six seems to be the tipping point.  FYI, I'm running this on an Intel NUC with a core i3 and 16GB RAM.

**Comment by bramkragten** [comment]
Yeah, your backend seems just to busy to handle the requests.

**Comment by xbmcnut** [comment]
Is that a factor of the hardware resources or a LL limitation?

**Comment by bramkragten** [comment]
hardware resources, Lovelace runs on the client and doesn't use server resources except for getting data.

**Comment by xbmcnut** [comment]
Sorry, can you clarify? Hardware of the tablet I'm running the LL instance on or the hardware I'm running Home Assistant on?

**Comment by xbmcnut** [comment]
Any traction with this or is this something we just have to live with? When using either the HA Android app or a browser, and HA restarts in the background, my camera images fail to load when they are set to 'Auto' and the app/browser has to be closed and reopened to force the camera images to reload which is lowering the overall WAF.

**Comment by xbmcnut** [comment]
For those with this issue, I found a workaround using Fully Kiosk Browser. After HA restart, I call a rest command to reload the whole browser after a 20s delay and that works a treat. Here is the rest command:
`http://ip.of.display.instance:2323/?cmd=loadStartURL&password=[yourpassword]`
