### ISSUE TITLE
Weather Card: 24 hour time format ignored

### ISSUE THREAD

**Issue by zsarnett** [home-assistant/frontend#5760]
## The problem

The card doesn't show in 24-hour time formats

## Expected behavior

The card should respect if the entity is in 24-hour or 12-hour time formats

Related: https://github.com/home-assistant/frontend/issues/5676

**Comment by vhsw** [comment]
this seems to be fixed in #6671

**Comment by spacegaier** [comment]
@zsarnett Can this be closed? I don't have a card in my current setup that shows times for the weather, so I cannot verify myself conclusevly, but everything seems to point in that direction 😄.

**Comment by zsarnett** [comment]
No idea. I made the issue for others
