### ISSUE TITLE
Weather Card: Ability to choose Secondary Attribute

### ISSUE THREAD

**Issue by zsarnett** [home-assistant/frontend#5764]
## The request

Instead of showing the attribute in order of 

1. Extrema
2. Precipitation
3. Humidity

Allow the user to select which attribute to show

Related: https://github.com/home-assistant/frontend/issues/5676

**Comment by Molodax** [comment]
Is it limited only to three? Why humidity and not air pressure then?

**Comment by zsarnett** [comment]
No it will not be limited to any attributes.If implemented it will be up to the user to choose any attribute from the entity

**Comment by Molodax** [comment]
So is the intention to choose more than attribute? Otherwise, it is still the same issue, e.g. precipitation and wind are equally important.

**Comment by zsarnett** [comment]
Then you will need to use an entities card or entity card to view those attributes.

**Comment by Molodax** [comment]
> Then you will need to use an entities card or entity card to view those attributes.

Why? It was possible in the previous weather card which was unnecessary broken by "beauty" design which make the entire idea of the weather card useless.

**Comment by zsarnett** [comment]
Weather card is completely useless because it doesn't show two Attributes? Really? The card may be useless for you and for that. I am sorry. But for the mass of people where those two attributes aren't that important it is just fine. There are plenty of custom cards out there. Sounds like that's what you need

**Comment by Molodax** [comment]
``

> Weather card is completely useless because it doesn't show two Attributes? Really? The card may be useless for you and for that. I am sorry. But for the mass of people where those two attributes aren't that important it is just fine. There are plenty of custom cards out there. Sounds like that's what you need

Really, useless. It is about attributes that characterize the weather, not about "attributes" for your design. Otherwise, single icon of weather condition provide the same amount of information as your designed card.
Please read the forum or other comments prior to talk about mass of people, or try to use this card yourself as a source of the information.

**Comment by zsarnett** [comment]
I have read all the forums post and the small amount of people in them is not the mass of people that are not. 

I have used the card and have been since before it was released. It is very useful, I want to see what the current state and temp is and the high and low. That information is given. Not often do I need to dive into the details and if I do then I am probably able to click the card to pull the more info. The card is used for at a glance information. Use your finger to Tap or click the mouse on the card to see the information you see :)

I am trying to help with a lot of these issues. But not everyone can get what they want

**Comment by Molodax** [comment]
I bet on the "mass of people" check the current status by looking out the window and not looking at this card.
Have you seen comments/posts asking to implement the "beauty" design to the detriment of usability prior to 0.109?

**Comment by da-anda** [comment]
I also find the new weather card utterly useless now. If all I want to see is the current temperature, I don't need a weather card at all and just display my sensor values. For me, things like humidity and wind speed are also important attributes and I really don't get why they have been removed entirely and not just hidden by default with the possibility to enable them when desired. So I also would welcome an option to choose from multiple attributes to display.

**Comment by markus99** [comment]
I have to concur, much preferred the 'old' card w/ more information.  Also, the 'new' card has much less info - and adds duplicate info?  High/low for today TWICE - same w/ current weather.  Maybe either remove the high/low from top-right so CURRENT TEMP (arguably most important info on the card) is bigger - or remove TODAY from the 'forecast' down below?
![image](https://user-images.githubusercontent.com/2835274/81189937-d0cc7b80-8f7c-11ea-9d5f-ad40b896fda3.png)

Requests:
1) Force 5 day forecast regardless of screen size (My desktop shows 3 days and mobile shows 5 days (My desktop ends up being 3 columns and mobile 1 fwiw)
2) Bring back (or add option to display) anticipated rain amount below hi-low in forecast - as it was before - now I have no idea, at a glance, if it's going to be .1" of rain for 1.5" of rain...
3) Bring back wind speeds, or options to display this
4) Could we have both?  Ie. Bring back the 'old' weather card in HA as well - and then let users choose which they prefer?

**Comment by Molodax** [comment]
Well, it seems that no one is going to fix it, so only one attribute will be implemented as an option which is shame. Hilarious that this PR is marked as a "new feature" while should be marked as an "half fix" of previously functional card.

**Comment by bramkragten** [comment]
@Molodax you can always copy the old card and use it as a custom card.

**Comment by Molodax** [comment]
> @Molodax you can always copy the old card and use it as a custom card.

Thank you, sure I can. I believe you have your own good weather custom card that serves its purpose better than the new "official" one.
One issue with custom cards/components that there is often little/no maintenance over time. Another bigger issue though that some changes to the "official" ones, weather card is a good example, are made without good basis, driven by subjective judgement of one or very few capable individuals.
