### ISSUE TITLE
Weather Card: Wind speed/direction is missing

### ISSUE THREAD

**Issue by Molodax** [home-assistant/frontend#5766]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Wind speed/direction has been removed from the new weather card and can be viewed only if you open the card which downgrades usability of the weather card.

## Expected behavior
Wind speed/direction is equally important wether information that should be (and was) available on the weather card.

## Steps to reproduce
Add weather card.

## Environment

- Home Assistant release with the issue: 0.109.x
- Last working Home Assistant release (if known): 0.108.x
- Browser and browser version: all
- Operating system: all

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/issues/5764

As stated in the #5676 All attributes will not be added. These can be chosen from the attributes listed in #5764 for secondary attribute
