### ISSUE TITLE
Show progress bar when creating snapshot or info when process is running

### ISSUE THREAD

**Issue by Misiu** [home-assistant/frontend#5772]
## The request

Currently, when creating snapshots (using Supervisor->Snapshots) there is no progress indicator.
Full snapshot on Raspberry Pi needs a lot of time, especially when the DB is big.
I think it would be a good improvement to show info or progress bar.

## The alternatives

I click `F5` several times to check if snapshot is created.
## Additional information
I think the `create snapshot` is async, so the progress info doesn't need to disable the whole UI, but instead show info (instead of create snapshot panel) that currently the system is creating a snapshot.
Maybe a notification when the snapshot finish would be useful?

**Comment by ludeeus** [comment]
This is already implemented, the create button now shows a spinner when it's creating the snapshot
![image](https://user-images.githubusercontent.com/15093472/93187095-b468f880-f73f-11ea-9485-255ec8c45f93.png)
