### ISSUE TITLE
WLED card - Would like to see peek feature of WLED as well as speed and effect sliders

### ISSUE THREAD

**Issue by feradelectronics** [home-assistant/frontend#5775]
## The request

WLED card suggestion.  Would like to see peek feature of WLED as well as speed and effect sliders on card if possible.  This would be really cool 

## Additional information
![WLED Card](https://user-images.githubusercontent.com/20371560/81198291-8a781c00-8f7e-11ea-9c5c-1d324764d60a.png)

**Comment by zsarnett** [comment]
Im not sure I understand the request? Are you asking for a card for one integration? WLED?

**Comment by feradelectronics** [comment]
![WLED Card](https://user-images.githubusercontent.com/20371560/81196995-fd809300-8f7c-11ea-9456-38f77a1bf4c2.png)
Something similar to this idea.

**Comment by feradelectronics** [comment]
The peek would be live simulating what is on the LEDs same as the peek option already available in the WLED html for the lights.

**Comment by feradelectronics** [comment]
Sorry, Effect would be the intensity.  by clicking on the three dots allows user to select effect as is already available on the card for WLED

**Comment by zsarnett** [comment]
This should be done in a custom card.

**Comment by feradelectronics** [comment]
This is my idea but i have no understanding how to get this done.

**Comment by bramkragten** [comment]
This is not the place to ask for custom cards, ask your questions on the forum or discord.
