### ISSUE TITLE
Remember 'Do you want to stay logged in'

### ISSUE THREAD

**Issue by dx44** [home-assistant/frontend#5779]
## The request

I suggest adding an option to remember the choice made in the popup 'Do you want to stay logged in ?' when you ... logged in!
This popup appear each time.
There must also be an option in the configuration pane to cancel this choice.

## The alternatives

There are no alternatives for this right now.

## Additional information
There are no additionnal information for this right now.

**Comment by zsarnett** [comment]
This is already possible unless you log out. We shouldn't keep logging you in unless you specifically want that. If you keep logging out then why do you want HA to stay logged in
