### ISSUE TITLE
Top View icons disappear

### ISSUE THREAD

**Issue by GunnarBjoru** [home-assistant/frontend#5783]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

View icon/text in the top is disappearing on reload/refresh.
The only way to get them back (temporary) is to go into another dashboard.
Then reload/refresh that and go back to the initial dashboard - then the icons/text for views are back.
I think it is related to HACS somehow, but that I am not sure of.
## Environment

- Home Assistant release with the issue: 0.110.0.dev20200506
- Last working Home Assistant release (if known): 0.110.0.dev20200504
- Browser and browser version: Chrome, Opera, Edge, iOS Companion
- Operating system: 

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
Supervisor:
Version | 220
Channel | dev

Host system:
System | HassOS 4.5
Deployment | development

**Comment by zsarnett** [comment]
Without more information there is no way to help. This is probably due to a Custom Card, Hacs, or something else custom. Make sure to clear cache and maybe post a Gif of the issue. Other wise remove all custom stuff and try again
