### ISSUE TITLE
Weather Forecast Card not showing days

### ISSUE THREAD

**Issue by optama** [home-assistant/frontend#5792]
![image](https://user-images.githubusercontent.com/509056/81299012-e7a2c900-9075-11ea-90df-f6d8d17e2f3c.png)

Five columns in weather forecast card labeled: 14, 12, 12, 12, 12 (localized for 2pm 12pm 12pm 12pm etc). Is this as intended? Does the 12 in the following columns stand for 12pm the next day? If so then I would rather it show the name of the day instead, ie: fri, sat,  sun, mon etc.

Looking at the code I find this - seems there's a criteria for when to show hours and when to show weekdays.
https://github.com/home-assistant/frontend/blob/56754b4d43d9c14acbb740b1518691eb81fbf1b9/src/panels/lovelace/cards/hui-weather-forecast-card.ts#L158
https://github.com/home-assistant/frontend/blob/56754b4d43d9c14acbb740b1518691eb81fbf1b9/src/panels/lovelace/cards/hui-weather-forecast-card.ts#L215

If I understand it correctly we have an array of forecasts within which we check that the time between the first and next is greater than a day (24h) and if so we show the weekday labels.

My forecast looks like this:
![image](https://user-images.githubusercontent.com/509056/81300034-7106cb00-9077-11ea-852d-c4b0b2886f78.png)

I would assume this should lead to a display of weekday labels, if not - is there a way to force it or should perhaps the criteria algorithm be changed?

Weather integration is SMHI.
Home Assistant version 0.109.4

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/issues/5761
