### ISSUE TITLE
Missing tabs for Add-on store, Snapshots and Sustem.

### ISSUE THREAD

**Issue by reotto613** [home-assistant/frontend#5808]
**Home Assistant release with the issue:**
109.6

**Operating environment (HassOS/Generic):**
Rasperry Pi 3b+

**Supervisor logs:**

**Description of problem:**
On Safari mobile and Apple App only the dashboard tab is visible.  Add-On Store, Snapahots and System is no longer visible. See pic.
![7BB33FAB-7A30-4285-A55E-96946E56DFA3](https://user-images.githubusercontent.com/60767748/81356547-0ebdc280-9097-11ea-8f9d-fd9045776ef4.png)

**Comment by ludeeus** [comment]
related issue: https://github.com/home-assistant/frontend/issues/5807
