### ISSUE TITLE
Supervisor manage repositories - can't delete repo

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5819]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Pressing the trash can icon to delete a repository does not appear to do anything. I don't receive a confirmation prompt and no action takes place either. 

I've tested this on both iPhone app and desktop browser.

## Steps to reproduce

1. Go to Supervisor -> Add On Store
2. Click overflow menu in top right and then Repositories
3. Press trash can / delete button next to something

## Environment

- Home Assistant release with the issue: 0.109.6 / Supervisor 222
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Fixed by https://github.com/home-assistant/frontend/pull/5816

**Comment by bramkragten** [comment]
(press next to the icon but inside the button, that will work :-))

**Comment by sindudas** [comment]
Same issue, now with core-2021.3.0 and supervisor-2021.03.3.

**Comment by bramkragten** [comment]
Please don't comment on closed issues.
