### ISSUE TITLE
Devices UI page, sort by Battery level

### ISSUE THREAD

**Issue by stefanroelofs** [home-assistant/frontend#5821]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
In the devices UI, sort the list by Battery level. The list is not correctly sorted.

## Environment
Home Assistant 0.109.6
Frontend version: 20200427.2 - latest
Browser: Chrome

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by matstrange** [comment]
Am able to replicate this issue. It looks to be grouping (not sorting) by Integration here and not honouring the battery status. 

![image](https://user-images.githubusercontent.com/54028700/81494895-28802500-92a4-11ea-85c3-67c1954c72ae.png)

**Comment by stefanroelofs** [comment]
This issue is still present in the latest version: 0.112.0
Frontend version: 20200701.0

**Comment by stefanroelofs** [comment]
This issue is still present in the latest version: 0.115.6
Frontend version: 20200918.2

**Comment by stefanroelofs** [comment]
This issue is still present in the latest version: 0.116.4
Frontend version: 20201001.2

![afbeelding](https://user-images.githubusercontent.com/37924749/97143311-be304380-1762-11eb-8d15-a8e88ccbe61e.png)

**Comment by SeanPM5** [comment]
Issue is still present in 2021.1.5

![image](https://i.imgur.com/1bwPvdE.png)

**Comment by stefanroelofs** [comment]
Issue is still present in latest HA version:
Home Assistant 2021.4.6
Frontend version: 20210407.3 - latest

The list of devices won't sort correctly by battery level.

![image](https://user-images.githubusercontent.com/37924749/116046983-e2b69b00-a673-11eb-8c51-912c6f6851da.png)

**Comment by stefanroelofs** [comment]
Issue is still present in Home Assistant 2021.7.0

![image](https://user-images.githubusercontent.com/37924749/124818843-d00deb80-df6b-11eb-9867-853afc53d224.png)

I cannot sort by battery level.

**Comment by stefanroelofs** [comment]
Maybe @bramkragten has some time to look into this old issue? 
(sorry to ping you directly, won't do it again...)

Thanks!

**Comment by GirzzlyAK** [comment]
This is not the only issue with Sorting in the UI on the Device or Entities pages. Sorting by name or entity_id does not work correctly either. I did this a LOT recently while renaming hundreds of _things_ using the UI after converting to zwave-js, and the lack of correct column sort functionality was frustrating at best. It is also frustrating that this has been an issue for so long. It would seem to be a pretty simple fix, as there is already SOME sort functionality, it just doesn't work correctly.

**Comment by bramkragten** [comment]
It would help if you would mention what was not correct, just saying it isn't current doesn't help much.

**Comment by stefanroelofs** [comment]
Well, sorting devices (by battery level) does not work. I don't quite know what I can say more. Devices are sorted randomly. The screenshots above speak for themselves. 

Please let me know if I can provide you with more info.

**Comment by bramkragten** [comment]
I was referring to the comment from @GirzzlyAK:

> This is not the only issue with Sorting in the UI on the Device or Entities pages. Sorting by name or entity_id does not work correctly either.

**Comment by GirzzlyAK** [comment]
`It would help if you would mention what was not correct, just saying it isn't current doesn't help much.`

I'm not sure what else can be said. "Sorting" is pretty self explanatory, especially if one assumes the standard alphanumeric sorting order. It's either ascending or descending. Basically, if you sort by a column, the values in that column are never correctly. Some of it might appear sorted, but when you'll have an "A" toward the bottom. Give it a go.

**Comment by bramkragten** [comment]
Yeah, well, it seems perfectly fine here, so an example or reproductable case would really help.

**Comment by GirzzlyAK** [comment]
I think I see what the issue is. There are three sort states: Ascending, Descending, and Unsorted. When  you click the header, it shows Ascending, another click, Descending, a third click, Ascending (again). But, after a second or two (or moving your mouse), the arrow disappears, and the results are actually unsorted. Place your cursor on a title, and without removing it, click the heading three times. The third time, the arrow points up, same as ascending, but it is unsorted.
