### ISSUE TITLE
Lovelace light card slider

### ISSUE THREAD

**Issue by ThrowBackDewd** [home-assistant/frontend#5825]
In Home Assistant (Hassio) 0.109.3 I've noticed that the light card [https://www.home-assistant.io/lovelace/light/] seems to have a bug in it. When trying to set the light with the slider (or external method) the slider will be set to the incorrect value. It appears to be set to the previous value instead of the current value. For example, if I set my lights to 25%, they will appear at 25% but the slider indicator on the light card will show a different value. If I then set my light to 50%, the slider indicator will go to 25%. As I repeat this process, the indicator on the light card always seems to be one setting behind the actual value of the light. I've tried this with several different lights and the same seems to be true on all of them. I just upgraded to 0.109.6 and the same thing is happening. To be clear, the physical brightness of the light appears to be correct in all instances after setting it, but the display on the light card itself is one setting behind.

Light set to 25%, value on light card unknown
Light set to 75%, value on light card shows as 25%
Light set to 50%, value on light card shows at 75%
Light set to 75%, value on light card shows 50%

**Comment by zsarnett** [comment]
PLease fill out the issue template
