### ISSUE TITLE
lovelace is not loading (takes forever to load)

### ISSUE THREAD

**Issue by niccolobusato** [home-assistant/frontend#5827]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

lovelace is really slow to load (not an internet connection problem). used the chrome inspector to check what is the problem and figured out that lovelace has needed 2.5minutes to load completely. all of my camera has been aborted to load the stream.

also all the custom cards are not loading and so on..
## Expected behavior

<img width="1440" alt="Schermata 2020-05-09 alle 20 54 58" src="https://user-images.githubusercontent.com/44100360/81482541-15377000-9238-11ea-9597-3ec3e7434c24.png">
<img width="1439" alt="Schermata 2020-05-09 alle 20 55 14" src="https://user-images.githubusercontent.com/44100360/81482545-1a94ba80-9238-11ea-847b-7a49ebbb46bd.png">

## Environment

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.19.115
python_version | 3.7.7
timezone | Europe/Rome
version | 0.109.6
virtualenv | false

- Home Assistant release with the issue: Home Assistant 0.109.x
- Last working Home Assistant release (if known): 0.107.x/0.108.x
- Browser and browser version: Chrome Latest
- Operating system: MacOs

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

this error appear then in the console (related to all the "camera." entities)
```txt
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```
and this for the manifest.json file 
```txt
Failed to load resource: net::ERR_FAILED
```
## Additional information

some other users are having the same issue (listed on a facebook group)

**Comment by bramkragten** [comment]
Start by disabling all custom cards and integrations.

**Comment by niccolobusato** [comment]
unfortunately I don't think, all automations performed perfectly and without delay. only the ui is very slow

right now i'm trying to stop some addons but nothing is changing

**Comment by niccolobusato** [comment]
downgraded to 0.108.0 and everything is working fine 

0 problems quick and snappy as usual 

all the addons are running, none of the custom cards / components are disabled 

can’t find any relevant information on the change log of v 109.x..

**Comment by niccolobusato** [comment]
<img width="386" alt="Schermata 2020-05-11 alle 19 53 31" src="https://user-images.githubusercontent.com/44100360/81594427-28297c00-93c1-11ea-8664-d6ec02bb6ab4.png">


update!!

**Comment by bramkragten** [comment]
Your backend takes a very long time to respond on requests, I don't think this is a frontend issue actually.

Anything in your backend logs?

**Comment by niccolobusato** [comment]
not the first time i reported that. right now i disabled all the custom card and also hacs.

now the sidebar, the settings page are loading but none of the ui and also the addons via ingress.

a lot of error right now on my logs

<img width="392" alt="Schermata 2020-05-11 alle 20 29 54" src="https://user-images.githubusercontent.com/44100360/81598012-e8fe2980-93c6-11ea-9aa8-7586c61adec5.png">
<img width="631" alt="Schermata 2020-05-11 alle 20 30 19" src="https://user-images.githubusercontent.com/44100360/81598022-edc2dd80-93c6-11ea-9c8d-c16925f78974.png">
<img width="814" alt="Schermata 2020-05-11 alle 20 30 45" src="https://user-images.githubusercontent.com/44100360/81598026-f1eefb00-93c6-11ea-94c2-8c560bc59a63.png">


also don't know if this is relevant for me or only an advice.. 
<img width="1253" alt="Schermata 2020-05-11 alle 20 29 35" src="https://user-images.githubusercontent.com/44100360/81598061-029f7100-93c7-11ea-838a-9410b9aa5f42.png">

**Comment by niccolobusato** [comment]
can't find out which integration is causing this.

fortunately discovered that i have a snapshot. rolled back of a month ad re-update everything. now is working just fine..
