### ISSUE TITLE
Weather Card: NWS (National Weather Service) doesn't display daily forecast properly.

### ISSUE THREAD

**Issue by MarkHofmann11** [home-assistant/frontend#5829]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

NWS integration not displaying the days of the week in the weather forecast card when using daynight entity.  The top pictures shows the issue - the bottom one shows the way it used to display.

## Expected behavior

Please see pictures.

## Environment

- Home Assistant release with the issue: 109
- Last working Home Assistant release (if known): 108
- Browser and browser version:
- Operating system: Windows

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
![Capture](https://user-images.githubusercontent.com/13205433/81487030-8e7a9700-9227-11ea-9734-3519abfbe223.JPG)

**Comment by MarkHofmann11** [comment]
https://github.com/home-assistant/core/issues/35425

**Comment by zsarnett** [comment]
Those times are not daily times? They are Day/Night So not a daily forecast

**Comment by MatthewFlamm** [comment]
Correct.  They were previously displayed with days off the week, so the display was similar to how the dark sky daily entity looks in the card now.

**Comment by zsarnett** [comment]
But they aren't days of the week right? If they were then we were displaying incorrect. I think you could benefit from both being displayed but it would be two of the same days next to each other. Mon - 6am | Mon - 6pm

**Comment by MatthewFlamm** [comment]
The best would be Sun and Sun Night 🙂

**Comment by MatthewFlamm** [comment]
This particular integration has an additional forecast attribute to mark day and night forecast, so it could probably be done without too much effort.

**Comment by MatthewFlamm** [comment]
I actually had started a PR for the old card, but then saw you had started this new card at the same time so dropped it.  See #5578

**Comment by MatthewFlamm** [comment]
@zsarnett I've been thinking that the fact that the frontend display of the weather card has to infer the type of forecast (daily, hourly, etc) from the structure is very cumbersome and leads to issues.  We should have weather entities store the forecast type in the backend so it is explicit.  I will write an architecture proposal.

**Comment by zsarnett** [comment]
That would actually be very helpful. Because of the many ways that the forecast array of data can be stored, it makes it difficult to infer the type of forecast. AKA why we are now comparing the second and third entries of the forecast array to see if daily or hourly because some integrations have the first forecast entry the current time of day.

It would be really simple if the backend told the front end the type. Hourly, Daily, Day/Night. Because we always know how to display it. and if different integrations change the forecast data then we don't have to go back to the card and accommodate that change.

Are you still able to write the proposal? If not, I will start it

**Comment by MatthewFlamm** [comment]
I created the one above.  Feel free to weigh in if you expected it differently.
