### ISSUE TITLE
Missing translation for script "execute" action

### ISSUE THREAD

**Issue by chemelli74** [home-assistant/frontend#5831]
## The problem

"Execute" is not localized in UI language, but it's fixed in English.

## Environment

- Home Assistant Core release with the issue: 0.109.5
- Last working Home Assistant Core release (if known): none 
- Operating environment (Home Assistant/Supervised/Docker/venv): docker
- Integration causing this issue: script
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```
-
```

## Traceback/Error logs

```
-
```

## Additional information

![image](https://user-images.githubusercontent.com/57354320/81495679-4e142b00-92b2-11ea-9bf8-f79cd836600e.png)

**Comment by chemelli74** [comment]
Any update ?

Thank you,

Simone

**Comment by bramkragten** [comment]
Don't bump your issues, please. You will get a notification when a PR is made that will close this issue.

**Comment by chemelli74** [comment]
> Don't bump your issues, please. You will get a notification when a PR is made that will close this issue.

Sorry.
But after 19 days an acknowledge that is a valid issue and will be taken care, is enough.
No answer at all leave it in a limbo.

Was not looking for a quick commit for a fix  ;-)

Thx,

Simone

**Comment by bramkragten** [comment]
Actually it is not a valid issue as it is translatable. If it isn't translated in your language you can do this on Lokalise. https://developers.home-assistant.io/docs/translations

**Comment by chemelli74** [comment]
In the end was not wrong to bump ;-)

I will try to understand why on Lokalize there is a translation for "ui::card::script::execute" but in HA is not working.

Simone

**Comment by bramkragten** [comment]
Works here

![image](https://user-images.githubusercontent.com/5662298/83238822-45b75d80-a197-11ea-98a3-fb7232cd5482.png)

**Comment by chemelli74** [comment]
Works fine on 0.110.3

Thank you for your help.

Simone
