### ISSUE TITLE
iOS Automation page error -save button out of bounds

### ISSUE THREAD

**Issue by jazzmonger** [home-assistant/frontend#5833]
## Checklist

- [ x ] I have updated to the latest available Home Assistant version.
- [ x ] I have cleared the cache of my browser.
- [ x ] I have tried a different browser to see if it is related to my browser.

## The problem

When editing Or creating an automation on an iPad in Chrome or Safari, the save button is hidden by a white bar across the bottom.  You can barely click it and when you can catch it, it will create a second identical automation if you click it a second time. 

On an iPhone using the home assistant app, the save button in automations is visible but does not work.  Clicking save does nothing. 
![97BBFFE8-4BC9-4DD1-86C4-C2B3B729AD9F](https://user-images.githubusercontent.com/52110065/81501632-4b9fda00-928e-11ea-95fb-b03083b93dd9.jpeg)

## Expected behavior

Save button should be visible AND save your work when clicked.

## Steps to reproduce

Add a new automation.  Try and save it. 

## Environment
Using .109.6

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version: 
- Operating system: iOS 13.3.1

![FAAFF4E2-B260-45B8-A1C9-41235EF097D8](https://user-images.githubusercontent.com/52110065/81501908-aab21e80-928f-11ea-9cb1-1a5c8290a05b.jpeg)

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/89776923-144dfd00-db0b-11ea-8ffe-8f17407cbaa3.png)

Seems fixed in 0.114 beta at least, will close for now.
