### ISSUE TITLE
Lovelace dashboard: set default on this device Local/Remote

### ISSUE THREAD

**Issue by allanpersson** [home-assistant/frontend#5835]
## The request

(I looked at issues for similar FR but didnt find any)

When using the "set dashboard as default on this device" is only stored on the network type you are on. So if you set it as default on your local network it will render this dashboard as default when you are on your local network, but when you access your instance from remote on the same device it is not stored and you have to do the process again from your remote connection.

I like the idea of setting different dashboard for home/away and/or even in different zones, but the description and way it works could be smoother.

## The alternatives

  Exepts the above it could be great to be able to assign dashboard to users from admin.

## Additional information

Thank you for your effort and hard work making Home Assistant so awesome (Y)

**Comment by bramkragten** [comment]
This is not true, the network has nothing to do with it. You probably use a different hostname to reach your instance local or remote.

We store the settings in local storage, so it is tied to the hostname.

**Comment by allanpersson** [comment]
I use nabu casa for remote access...

**Comment by ludeeus** [comment]
Yes, and IP/local hostname for local access.
Which makes that 2 different clients to the frontend.

**Comment by allanpersson** [comment]
@ludeeus i was suspecting that, but could this be handled more smooth when setting default lovelace dashboard?

At least the description "set default on this device" is a little misleading as I only have 1 device and 1 HA app (I get its handlede as a local and remote device) 🙏

**Comment by bramkragten** [comment]
No, a website can never store something for a different domain. We could only store it on the backend but that would mean it isn't a device setting either.

**Comment by bramkragten** [comment]
Maybe for the companion apps we could store it in the app.

**Comment by ludeeus** [comment]
To the website you are visiting, you have 2 devices.
You can go into the android app settings and remove the settings for local address and your network name, then it will always use the nabu casa URL.

This could potentially be handled by the app, but I don't think this issue/feature request belongs in this repository.

**Comment by allanpersson** [comment]
@bramkragten im not familiar with the technical aspects, I have just noticed that I had to set it twice ( local and remote) but the button text says device, and I think many people would think they only have 1 device 🙏

**Comment by allanpersson** [comment]
@ludeeus i would not like to miss out on the local connection in the app, I just think the description should be changed then to somehow clearify that remote/local would be set individually 🙏

**Comment by ludeeus** [comment]
TBH, any other description would be even more confusing.

- Set dashboard as default on this browser
- Set dashboard as default on this network
- Set dashboard as default on this user with this browser on this network
- Set dashboard as default on this thing (sometimes) 🤷‍♂️

**Comment by ludeeus** [comment]
You should probably open a feature request in the android app repo to see if they can do some magic in the app itself.

**Comment by allanpersson** [comment]
@ludeeus i will try to open one there 🙏

And maybe your right a more descriptive name would be difficult 🙏

Set default for this device on {{ local }} connection
Would probably be too long..
