### ISSUE TITLE
Automations configuration list is empty

### ISSUE THREAD

**Issue by Mryck** [home-assistant/frontend#5853]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
The list which display automations is empty. It was working in the previous version. 
I have `automation: !include automations.yaml`. I have no log in the web console for that particular page. When I create a new automation, it's correctly append to the automation.yaml file but the list is still empty.

## Expected behavior
Configuration -> automations 
Show all automations available.

## Steps to reproduce
Configuration -> automations 

## Environment
Version: 0.109.6
Raspberry pi 4, HassOS 4.6, supervisor: 222

I tried with Safari, Firefox and Chrome all in normal and incognito mode

- Home Assistant release with the issue: 0.109
- Last working Home Assistant release (if known): I guess 0.108, I don't add automations very often
- Browser and browser version: Safari on mac and iOS
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

**Comment by jodur** [comment]
i have exac the same behaviour with scripts! Scripts are present and new scripts are added correctly. Scripts are also running. Same HW en software configuration (running on 64 bit image, so i can use VSCODE)

**Comment by bramkragten** [comment]
can you check the state of your automations?

**Comment by jodur** [comment]
The automations editor works fine and all automations are shown, only the script editor doesn't show any scripts. (also the newly added trough the GUI not).

**Comment by bramkragten** [comment]
Then give me the state of your script.

**Comment by jodur** [comment]
"State of your script"?? What do you mean with that?

**Comment by jodur** [comment]
Dicord, channel #frontend? -> i am online now

**Comment by bramkragten** [comment]
That explains why you don't see them :-)

Have a `customize` for all your scripts that sets hidden?

**Comment by jodur** [comment]
Problem solved for me, thanks bram.

It appears that i had an old statement of the earlier years from homeassistant still present in my config file:

customize_domain:
    script:
      hidden: True

Never noticed this before in earlies edtions.

**Comment by Mryck** [comment]
Well same for me, never notice as well and totally forgot the hidden: True !
Thanks bram for you help !

**Comment by steve-gombos** [comment]
@bramkragten So is this how it is going to work moving forward?  I also had automations/scripts hidden via customization.  Previously they would show up in the UI, but they were hidden from logbook, etc... 

I assume the new approach would be to just add the domain or entities to the recorder/logbook configuration if I want to exclude them from there, but keep them in the UI.

**Comment by bramkragten** [comment]
I'm not sure honestly, I think `hidden` should not be used at all, `hide_entity` was deprecated, I can't find `hidden` in the docs...

**Comment by steve-gombos** [comment]
I still see hidden in the customization documents.  https://www.home-assistant.io/docs/configuration/customizing-devices/
