### ISSUE TITLE
Markdown Card not rendering: Beta 0.110.0b0

### ISSUE THREAD

**Issue by zsarnett** [home-assistant/frontend#5861]
##  Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Markdown Card not rendering any text until edited.

![image](https://user-images.githubusercontent.com/18730868/81873183-2f7b9180-9549-11ea-8413-f0e54824a924.png)

![30997695f8e534eea5b20cc2feaa02d4](https://user-images.githubusercontent.com/18730868/81873336-94cf8280-9549-11ea-94db-deeb5e05c943.gif)

## Expected behavior

To show the Text in the card

## Steps to reproduce

1. Create Markdown Card
2. Add Text to it
3. Finish the edit
4. Refresh browser

## Environment

- Home Assistant release with the issue: 0.110.0b0
- Last working Home Assistant release (if known): 0.109.6
- Browser and browser version: Chrome and Firefox (latest)
- Operating system: Linux and Window

## Problem-relevant configuration

```yaml
type: markdown
content: >-
  The **Markdown** card allows you to write any text. You can style it **bold**,
  *italicized*, ~strikethrough~ etc. You can do images, links, and more.


  For more information see the [Markdown
  Cheatsheet](https://commonmark.org/help).
```

## Javascript errors shown in your browser console/inspector

Weirdly I have no console error

## Additional information

I would think this may have to do with the new ways views are handled. With @bramkragten recent changes.

Will take a look more into it later. Couple hours if I get to it tonight

**Comment by bramkragten** [comment]
The `hass` setter should be removed and `hass` should be a property instead of `_hass`. That should fix it.

The logic of the setter can be moved to updated.

**Comment by bramkragten** [comment]
(it is because `hass` is set before the card is lazy loaded, and lit handles upgrades for us for properties)
