### ISSUE TITLE
Flashing icons in entity dropdowns 0.110.0b0

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5868]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

All entity dropdowns appear to have flashing icons when the dropdown is expanded. You can see this in all of the card editors, the entity dropdown in the States panel, the entity dropdown in Logbook.

![image](https://i.imgur.com/BXkpSGr.png)

~~When selecting an entity in any of the card editors, the icons seem to flash (disappear and reappear) quite a bit. I first noticed it in the glance card but it occurs in all of them as far as I can tell.~~

## Expected behavior

For it to not do this 😛 

## Steps to reproduce

1. Configure UI > open any card editor
2. Select Entity dropdown, icons will be flashing quickly

## Environment

- Home Assistant release with the issue: 0.110.0b0
- Last working Home Assistant release (if known): 0.109.X
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
I don't see this, what browser are you using?

**Comment by SeanPM5** [comment]
Latest Chrome stable on desktop but I saw it on the iOS app too (wasn’t as noticeable there though).

It’s not constant flashing like a strobe light or anything, but like every ~2-3 seconds at random times the icons will disappear for a few milliseconds. The text always, this is just the icon. Just a little distracting that’s all. 

Initially I thought it was the card editors refreshing the preview that was causing the icons to flash but then I noticed it elsewhere (Services panel).

**Comment by bramkragten** [comment]
Yeah it seems related to an entity updating, but we can't reproduce it in dev, so let's hope it is fixed in the next version 😄

**Comment by jesserockz** [comment]
Seems to be fixed in `20200514.1` but that version is not in any [home-assistant/core](https://github.com/home-assistant/core) version yet

**Comment by bramkragten** [comment]
@SeanPM5 still seeing this?

**Comment by zsarnett** [comment]
![8c054ff902ce22016e686ba949f844e7](https://user-images.githubusercontent.com/18730868/82071974-d7f23880-96a4-11ea-8f20-544d40031d5b.gif)

**Comment by zsarnett** [comment]
https://gyazo.com/8c054ff902ce22016e686ba949f844e7

Link to gif may be able to see it better.

This is set up with the Second ticker automation to update the weather entity

**Comment by bramkragten** [comment]
Don't check the preview, that has been fixed in the next beta, but any other entity picker

**Comment by zsarnett** [comment]
https://gyazo.com/de965992e1efc2c8bcee5be3563ec234

**Comment by zsarnett** [comment]
Still unable to reproduce in dev

**Comment by bramkragten** [comment]
It is client side, so do you use a different browser to do it? :P

**Comment by bramkragten** [comment]
I'm able to reproduce in production but not in dev :-/ that sucks

**Comment by jesserockz** [comment]
Issue is still there on `0.110.0b3` / `20200515.0`
Latest Chrome on MacOS

**Comment by jesserockz** [comment]
I do not see the flashing anymore on `0.110.0b4` / `20200518.0`

**Comment by SeanPM5** [comment]
Indeed, seems to be fixed in 0.110.0b4 🎉
