### ISSUE TITLE
Close button on dropdown in Services panel 0.110.0b0

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5869]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

![image](https://i.imgur.com/ctIzu8W.png)

## Expected behavior

Here's a screenshot of how it looks on one of my other test devices running 0.107

![image](https://i.imgur.com/V0IjF8M.png)

## Steps to reproduce

1. Go to Developer Tools > Services and look at the dropdown

## Environment

- Home Assistant release with the issue: 0.110.0b0
- Last working Home Assistant release (if known): 0.109.X
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by TheZoker** [comment]
Also on the script edit screen:
![Screenshot_2020 05 14_15h05m36s_025_](https://user-images.githubusercontent.com/1368405/81937847-6b1f6580-95f4-11ea-8058-04b749ff73e8.png)
