### ISSUE TITLE
UI does not fall back to brand icon

### ISSUE THREAD

**Issue by eifinger** [home-assistant/frontend#5872]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I have added an icon but no logo for my custom component Folding@HomeControl.
It is available under https://brands.home-assistant.io/foldingathomecontrol/icon.png.

However the frontend does not display it.
Using the Developer Console I see that for the pages 
- `/config/integrations`
- `/config/devices/device/<device_id>` 

it tries to find https://brands.home-assistant.io/foldingathomecontrol/logo.png and gets a HTTP 404.

For the page 
- `/developer-tools/info`

I can see that it tries to find https://brands.home-assistant.io/_/foldingathomecontrol/icon.png which redirects to https://brands.home-assistant.io/_/_placeholder/icon.png

The following urls all work:
- https://brands.home-assistant.io/_/foldingathomecontrol/icon@2x.png
- https://brands.home-assistant.io/_/foldingathomecontrol/logo.png
- https://brands.home-assistant.io/_/foldingathomecontrol/logo@2x.png

## Expected behavior

According to the README of the brands repo I expect the following behaviour:

1. All pages of the Homeassistant UI use the url with fallback to access brand icons. The pages under `/config` don't do that.

1. The URL https://brands.home-assistant.io/_/foldingathomecontrol/icon.png should not get redirected to https://brands.home-assistant.io/_/_placeholder/icon.png.

## Environment

- Home Assistant release with the issue:  0.109.5
- Last working Home Assistant release (if known): -
- Browser and browser version: Chrome 81.0.4044.138
- Operating system: Windows 10 Pro

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by frenck** [comment]
This is caused by caching on the brands repository. The cache will be flushed when we do a major release (or sooner if the cache expires).

The CDN endpoint for me is already expired and correct:

![image](https://user-images.githubusercontent.com/195327/81908373-6e512c00-95c9-11ea-8cf6-bb5cfa4461dd.png)


It depends on bit on where you are in the world. I've flushed the cache for this integration specifically to prove the point, the images should now work for you as well.
