### ISSUE TITLE
[0.110.b0] Back button on grouped integrations card does not work with dark themes 

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/frontend#5874]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The back icon on the grouped integration card does not work well with dark themes:
![Screenshot_2020 05 14_14h42m40s_020_](https://user-images.githubusercontent.com/1368405/81935679-52618080-95f1-11ea-8e9b-1843c93166e8.png)

On the screenshot you can see the state without mouseover. 

## Expected behavior

Icon should also look good on dark themes. 

## Environment

- Home Assistant release with the issue: 0.110.b0
- Last working Home Assistant release (if known): none
- Browser and browser version: Edge Chrome 83
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Fixed

**Comment by TheZoker** [comment]
@bramkragten For me it still looks like this:
![image](https://user-images.githubusercontent.com/1368405/83014527-2c8ba100-a01f-11ea-8da3-da18ed9633df.png)

**Comment by bramkragten** [comment]
Let me guess, your card background color isn't a hex color but a variable?

**Comment by TheZoker** [comment]
I use the midnight theme via HACS:
https://github.com/home-assistant-community-themes/midnight

And yes that has a variable for the `card-background-color`: 
https://github.com/home-assistant-community-themes/midnight/blob/master/themes/midnight.yaml#L7

**Comment by bramkragten** [comment]
Change that to `card-background-color: "#383C45"`

**Comment by bramkragten** [comment]
I don't get that theme but... shouldn't it be `#434954`?
