### ISSUE TITLE
[0.110.0b0] Ignored integrations are shown

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/frontend#5875]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

This is what my integrations page looks like. As you can see, the HomeKit integrations is shown altough it should be ignored:
![Screenshot_2020 05 14_14h48m12s_021_](https://user-images.githubusercontent.com/1368405/81936366-75406480-95f2-11ea-8972-d33a302aac13.png)

When I press "Show ignored integrations", the ignored integrations is shown twice:
![Screenshot_2020 05 14_14h49m54s_022_](https://user-images.githubusercontent.com/1368405/81936273-46c28980-95f2-11ea-8a4e-90da5ca015b1.png)

## Expected behavior

Hide ignored integrations 

## Environment

- Home Assistant release with the issue: 0.110.0b0
- Last working Home Assistant release (if known): 0.109.x
- Browser and browser version: Edge Chrome 83
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
I guess this is an issue with HomeKit? I don't see this.

**Comment by SeanPM5** [comment]
Also seeing this but with UPnP. It has the ignored text, but is shown at the very bottom of my integration list as a "normal" configured card. 

![image](https://i.imgur.com/Qipn4qC.jpg)

When I show ignored integrations I see a UPnP card at the very top and grayed out like it's supposed to. So one in the correct spot and one in the wrong spot. Identical issue as OP but with a different integration. 

(Having other weird problems with discovery/ignore as well - keeps discovering my three Harmony hubs which had already been set up, my Roku streaming stick which had already been set up. None of these have the ignore buttons even though I know they're supposed to).
