### ISSUE TITLE
[0.110.0b0] Integration search result cards have different width

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/frontend#5876]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

This is the grid when nothing is searched:
![Screenshot_2020 05 14_14h48m12s_021_](https://user-images.githubusercontent.com/1368405/81936603-d5370b00-95f2-11ea-9dbb-c7cf86297af2.png)

When I search for a integrations, this is the result page:
![Screenshot_2020 05 14_14h55m03s_023_](https://user-images.githubusercontent.com/1368405/81936687-ebdd6200-95f2-11ea-8ecc-ee67b0b76cc0.png)

As you can see, the width of the card is different to the normal width of the card. 

## Expected behavior

Consistent width of cards across the component 

## Environment

- Home Assistant release with the issue: 0.110.0b0
- Last working Home Assistant release (if known): none
- Browser and browser version: Edge Chrome 83
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
The grid adjusts on the number of cards on the screen and the width of the screen, this is expected.
