### ISSUE TITLE
[0.110.0b0] Weird stuff next to the script edit button

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/frontend#5877]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
On the script page, there is some weird stuff next to the edit icon:
![Screenshot_2020 05 14_15h00m35s_024_](https://user-images.githubusercontent.com/1368405/81937386-da488a00-95f3-11ea-8cfe-b38a1fb04cb2.png)

I'm not sure, if this was there before this beta, I just notieced it. 

## Environment

- Home Assistant release with the issue: 0.110.0b0
- Last working Home Assistant release (if known): 0.109.x???
- Browser and browser version: Edge Chrome 83
- Operating system: Windows 10 

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Fixed
