### ISSUE TITLE
Conditional cards in 0.110.0b

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5890]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Dunno if anything changed regarding conditional cards, but none of them are working for me in 0.110. 

I have a LOT of conditional cards that show when an input_boolean goes from `off` to `on`. But the problem is when the criteria becomes true, the conditional card never appears until I manually refresh the browser.

![image](https://i.imgur.com/E6ddSLY.png)

The conditionals are all using core cards for the most part - conditional card that shows vertical stacks with entities cards inside of them. They always used to work fine, now they don't show until refreshing the browser first.

Issue is identical to an issue I had in the first two 0.108 betas (posted about it here with code samples: https://github.com/home-assistant/frontend/issues/5414) except without any of those console errors.

Fairly certain it's not a browser issue as I've reproduced it in a number of browsers.

## Expected behavior

Show conditional cards immediately when their criteria becomes true (in this case an input_boolean turning on via automation)

## Environment

- Home Assistant release with the issue: 0.110.0b0 and b1
- Last working Home Assistant release (if known): 0.109.6
- Browser and browser version: Chrome stable
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
This was fixed, but the frontend did not make it in b1, it is in b2.

**Comment by SeanPM5** [comment]
Still appears to be an issue on b2 for me - have to refresh browser for conditional card to appear. Dev Tools -> Info says `Frontend version: 20200514.1 - latest` not sure if that's the correct one with this fix.

Not really able to test/troubleshoot things for much of today as I'll be away from home helping move furniture, but just wanted to give a heads up. Maybe someone else can test their conditional cards.

**Comment by zsarnett** [comment]
Re opening until someone can confirm

**Comment by bramkragten** [comment]
#5891 is not in b2.
