### ISSUE TITLE
replace custom-ui, allow for customizing entities globally

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#5892]
## The request

Since from ha0.110 on custom-ui is no longer able to customize <strike>icon and</strike> icon_color (maybe more, but I haven't tested that yet), and core Lovelace up to now offers no way of customizing entities icons and icon_colors, other than per theme or using eg state_color, the request is to

offer some way for replacing custom-ui in core HA

## The alternatives

we can use custom cards, but they too only offer customizations per card

## Additional information

using things like:

```
homeassistant:
  customize_domain:

    automation:
      templates: &state_color
        icon_color: >
          if (state == 'on') return 'gold';
          return 'steelblue';

    switch:
      templates:
        icon: >
          if (state == 'on') return 'mdi:toggle-switch';
          return 'mdi:toggle-switch-off';
        <<: *state_color

  customize_glob:

    light.hue_ambiance_spot_*:
      icon: mdi:spotlight-beam

    switch.*motion_sensor:
      assumed_state: false

    device_tracker.*_bt:
      templates:
        icon: >
          if (state == 'home') return 'mdi:bluetooth';
          return 'mdi:bluetooth-off';
        icon_color: >
          if (state == 'home') return 'blue';
          return 'grey';

    sensor.*_temperature:
      templates:
        icon_color: >
          if (state < -20) return 'black';
          if (state < -15) return 'navy';
          if (state < -10) return 'darkblue';
          if (state < -5) return 'mediumblue';
          if (state < 0) return 'blue';
          if (state < 5) return 'dodgerblue';
          if (state < 10) return 'lightblue';
          if (state < 15) return 'turquoise';
          if (state < 20) return 'green';
          if (state < 25) return 'darkgreen';
          if (state < 30) return 'orange';
          if (state < 35) return 'crimson';
          return 'firebrick';

#icon example
    sensor.owm_wind_bearing:
      friendly_name: Wind bearing
      templates: &direction_icon
        icon: >
          var icons = ['mdi:arrow-down','mdi:arrow-bottom-left','mdi:arrow-left',
                       'mdi:arrow-top-left','mdi:arrow-up','mdi:arrow-top-right',
                       'mdi:arrow-right','mdi:arrow-bottom-right'];
          var quadrant = Math.round(Number(state)/45);
          if (quadrant < icons.length) return icons[quadrant];
          return 'mdi:arrow-down';
#used for all other  wind-direction/bearing sensors, only define once using an anchor...

#untested yet, but hope this will still be possible setting custom images:

    sensor.dark_sky*icon*:
      templates:
        entity_picture: >
          return '/local/weather/icons/' + state + '.png';
```

makes it dead easy to have these entities show with a meaningful icon and icon_color in the frontend, and doesn't enforce styling these entities individually in the Lovelace card configs. Be it core or custom.

example of an issue the now defunct custom-ui throws at the user:

a mere custom:auto-entities card with all temp sensors in the system will become a flat and meaningless card, since without a lot of trouble, and yet again another custom card, like card-mod, we can't style these. Even if we could, these stylings are only refreshed upon reload of the page, and not of the state of the entity. 

As they are now, using custom-ui.

examples:

```
      - type: custom:auto-entities
        card:
          type: entities
          style: |
            ha-card {
              box-shadow: none;
              margin: 0px 0px 0px -36px;
            }
        filter:
          include:
            - group: group.github_repos_in_use
              options:
                tap_action:
                  action: more-info
                hold_action:
                  action: navigate #url
                  navigation_path: weblinks
#        #              url_path: >
#        #                {{ state_attr(config.entity,'latest_release_url') }}
                type: custom:template-entity-row
                style: |
                  :host {
                    --paper-item-icon-color:
                      {% set id = config.entity.split('.')[1] %}
                      {% set repo = 'input_boolean.' + id %}
                      {{'gold' if is_state(repo,'on') else 'green'}}
                      ;

```

forgive me the complexity of this, but that is really the purpose of the post:

Without functional Custom-ui and no core Lovelace alternative for customizing these entities and properties users are forced to create terribly complex configs. Or be satisfied with/ use a rather pale Homeassistant Lovelace interface...

color is a most striking aspect of system feedback. Using custom icons too.
Please don't do away with that option.

<img width="360" alt="Schermafbeelding 2020-05-15 om 00 32 01" src="https://user-images.githubusercontent.com/33354141/82037250-29e58f00-96a2-11ea-884e-89eb4202dbcf.png">

Of course, if at all possible, and a change/edit of the current custom-ui files would be possible, I'd be glad to try and help realizing that. It's only about changing 1 file, so must be doable...?

thanks for considering.

some [discussion in the community](https://community.home-assistant.io/t/ha-110-no-longer-supports-custom-ui/195820/18)

**Comment by Krocko** [comment]
icon is still working. 
But +1 for this!

**Comment by Mariusthvdb** [comment]
a yes, that's correct, some relief!
still, doing this in a 'core' way would be much better, so the FR stands ;-)

**Comment by bramkragten** [comment]
This can be done in a custom card, on an entity level, on state change, the templates are javascript templates and not Jinja templates.

We never deprecated `custom-ui`, it was never in core. The maintainer decided not to develop it anymore.

**Comment by Mariusthvdb** [comment]
> This can be done in a custom card, on an entity level, on state change, the templates are javascript templates and not Jinja templates.

exactly, not globally.. only per custom card.
which is the whole point of this feature request of course. I wouldn't have asked if it were already possible.

I know HA didn't deprecate custom-ui actively, that' why I started out saying:

> custom-ui is no longer able to customize 

I'll rephrase the other sentence. 

HA changed the way icons are used from 110 on, which kills the custom-ui functionality for that. 

This is a feature request to allow for setting icon_color on a HA global way, so whenever an entity is used in which ever Lovelace card, core or custom, it shows that color.

And yes the shown templates are JS, of course, since custom-ui uses that. I was merely illustrating what custom-ui can do, and what the future request is about..

I dont ask to re-enable custom-ui (though wouldn't mind, maybe that's easily feasible with the change of 1 or 2 lines). I am asking for a way to have core Lovelace  set icon and icon_color globally.

**Comment by bramkragten** [comment]
I don't think this will ever make it into core. But what I'm saying is that a custom script should be able to do the same as custom-ui did.

**Comment by Krocko** [comment]
@bramkragten could you please explain it a little bit?

**Comment by Mariusthvdb** [comment]
thanks Bram, that at least sounds like an option going forward. Would still hope for it to be in core, so would be interested why you would say it wont never make it to core.

Having said that, and for swiftness sake.... how should we proceed with this custom script? What kind of script would that be? (knowing custom-ui also had scripts).

Or would they be regular backend scripts, and if so, how should be begin to create these?

thanks if you can find a moment to help us on the way.

**Comment by Mariusthvdb** [comment]
btw, forgot to mention, a big disadvantage of only being able to customize the entities in the Lovelace cards, is the more-info on these entities is un-customized. While when using the current custom-ui, the more-info is nicely updated and reflecting the state the entity is in.

with custom-ui (and a simple entities card without any modding in style):

<img width="306" alt="Schermafbeelding 2020-05-19 om 09 22 32" src="https://user-images.githubusercontent.com/33354141/82296995-4f301100-99b2-11ea-9ee8-464f4c3f6c8d.png">

and more-info:
<img width="360" alt="Schermafbeelding 2020-05-19 om 09 22 25" src="https://user-images.githubusercontent.com/33354141/82297021-5bb46980-99b2-11ea-8efe-fc86e6bd24b4.png">

with Lovelace card and card-mod:

<img width="310" alt="Schermafbeelding 2020-05-19 om 09 23 52" src="https://user-images.githubusercontent.com/33354141/82297112-7a1a6500-99b2-11ea-9799-e6ad4b8b633a.png">

and more-info:

<img width="357" alt="Schermafbeelding 2020-05-19 om 09 24 18" src="https://user-images.githubusercontent.com/33354141/82297157-8999ae00-99b2-11ea-8471-cec74c60758b.png">

config of the card:

```
  - type: custom:auto-entities
    card:
      title: Test auto coloring light level (lux) sensors
      type: entities
    filter:
      include:
        - entity_id: sensor.*_sensor_light_level_raw
          options:
            style: |
              :host {
                --paper-item-icon-color:
                 {% if states(config.entity)|float == 0 %} black
                 {% elif states(config.entity)|float < 1 %} maroon
                 {% elif states(config.entity)|float < 300 %} firebrick
                 {% elif states(config.entity)|float < 10000 %} orange
                 {% elif states(config.entity)|float < 17000 %} green
                 {% elif states(config.entity)|float < 22000 %} gold
                 {% elif states(config.entity)|float < 25500 %} teal
                 {% elif states(config.entity)|float < 28500 %} dodgerblue
                 {% elif states(config.entity)|float < 33000 %} lightskyblue
                 {% elif states(config.entity)|float < 40000 %} lightblue
                 {% elif states(config.entity)|float < 40000 %} lightcyan
                 {% else %} azure
                 {% endif %}
                 ;
               }
```

Hope this illustrates the further need for a true way of customizing entities, globally in HA, opposed to the individual or card-wise config Lovelace now offers.

**Comment by bramkragten** [comment]
A simple entities card without modding in style === Lovelace? So the problem isn't Lovelace then? I don't understand, but I've never looked at `custom-ui` or custom style plugins etc.

**Comment by Mariusthvdb** [comment]
> A simple entities card without modding in style === Lovelace? So the problem isn't Lovelace then? 

well, not really sure what you are saying here, sorry. the 'problem' is that the new way of treating icons has caused the 'old' custom-ui to stop being functional in setting the attribute icon_color on entities.

Ive tried above to show you what custom-ui can do. As I have tried to show what pure Lovelace, or Lovelace with card-mod can not do.

I am trying to bridge the gap, and asking for a 'new' way of setting an attribute icon_color, on entities, globally. So we don't have to 1) use card_mod's style on each and every card/entity, and 2) see that color also in more-info.

> I don't understand, but I've never looked at custom-ui

I can hardly believe you have never looked at custom-ui before... It has been (and for many functionality still is) 1 of the main plugins for years on HA. 
You are right, in saying it was the author who has not kept up with developments. It was of course designed for States, and not Lovelace.

Hence my FR to 'replace custom-ui', and allow for customizing entities globally, now Lovelace has become the single Frontend.

Maybe I can illustrate the need in another way:
Say, I desire to have my battery sensors, grouped per room in 1 card, and have these sensors colored as per state of %.

We now can only do that with a rather complex and non-core set of cards. And, as a downside, none of these entities are colored in the more-info pane. None of these stylings are global, and only in that specific set of cards.

With custom-ui, all we need to do is:
```
homeassistant:
  customize:
    sensor.*_battery_level:
      templates: &battery_color
        icon_color: >
          if (state > 75) return 'green';
          if (state > 50) return 'gold';
          if (state > 25) return 'orange';
          if (state > 10) return 'brown';
          return 'red';
```
and we can follow that up with:

```
    sensor.*_bewegingssensor:
      templates: 
       <<: *battery_color

    sensor.*_dimmer:
      templates:
        <<: *battery_color

    sensor.*_afstandsbediening*:
      templates:
        <<: *battery_color

    sensor.*_remote:
      templates:
        <<: *battery_color

    sensor.*_battery:
      templates:
        <<: *battery_color

    sensor.battery*:
      templates:
        <<: *battery_color
```
And never think again about the battery_level icons. Throughout the full frontend, in any card, custom-card and more-info pane.

it would be so very welcome to see that return (it can be done up to 109.6) in HA 0.110 and be a huge improvement on the visual feedback Lovelace gives the user.

**Comment by bramkragten** [comment]
Just checked the code of `custom-ui` it is not the new icons that break it, itis because of changes I made to `state-badge` it would be easy to make `custom-ui` work again.

Replace:
https://github.com/andrey-git/home-assistant-custom-ui/blob/489c634adb17ca88c0be9da225c51a84d9d1e0cf/src/utils/hooks.js#L507-L510
With:
```js
    this._showIcon = true;
    this._iconStyle = {color: stateObj.attributes.icon_color;}
```

**Comment by Mariusthvdb** [comment]
o wow, that would be so very great! thanks you!

only 1 gripe.... the only file doing the works in the HA instance is [state-card-custom-ui.html](https://github.com/andrey-git/home-assistant-custom-ui/blob/489c634adb17ca88c0be9da225c51a84d9d1e0cf/state-card-custom-ui.html)....

could you please have a look at that too? As that is a file we all have in our systems, and can change manually locally.

**Comment by bramkragten** [comment]
No, replace `Object.assign(this._icon.style,{color:s.attributes.icon_color,filter:""})` with `this._showIcon=true,this._iconStyle={color:s.attributes.icon_color}`

**Comment by Mariusthvdb** [comment]
yesss!
thanks you so much @bramkragten this is such a huge relief. Magic!

**Comment by bramkragten** [comment]
I could do that, the problem is people will expect me to maintain it, and I don't have the time for that 🙈

**Comment by Mariusthvdb** [comment]
> I could do that, the problem is people will expect me to maintain it, and I don't have the time for that 🙈

appreciate that of course. It would be the final clinch and to a modernizes Lovelace though, and stop the need for legacy custom-ui....

As the main front-end dev, it really would have to be you ;-)

or simply promise you wont nibble from custom-ui's options any more... 
thanks again. Ive filed a PR to the original custom-ui in the meantime, but I don't think it will be merged, since Andy hasn't been seen for a long time, sorry to say.

**Comment by Mariusthvdb** [comment]
Hi Bram, please allow one more followup on this:
Ive installed 110 and open the frontend on mu iPhone 11pro, and see the icons are not colored (they are customized).

Originally we also had a [state-card-custom-ui-es5.html](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/state-card-custom-ui-es5.html) but I had thought we didnt need that any longer... in that file an almost identical piece of code is available

```
Object.assign(this._icon.style,{color:e.attributes.icon_color,filter:""})):n.call(this,t)}
```

would you think we need to correct that too and reinstate the file especially for iPhone devices? Or would this be a cache thing. Note I open a regular browser on the iPhone, not the App.

On my iPad, all is well without the extra file, so unless they use different settings, I would think my iPhone needs a cache update..

please have a look if you can find a moment. (no hurry!)

**Comment by bramkragten** [comment]
An iPhone 11 will not use the ES5 build, for older devices you would need it.
My guess would be cache.

**Comment by Mariusthvdb** [comment]
ok thx for confirming, Ill wait some more. all other browser do seem to work, so its  Chrome for now ;-)

**Comment by jhbcosta** [comment]
Hi guys!

I didnt find hook.js in my system. Where I should put it?

Thanks,
José Henrique.

**Comment by Mariusthvdb** [comment]
you shouldn't...

only use the adapted state-card-custom-ui.html

**Comment by jhbcosta** [comment]
I am already using adapted state-card-custom-ui.html but no success at all.

![image](https://user-images.githubusercontent.com/51212559/82505514-551e1300-9ad4-11ea-8a65-e568cae5dbf2.png)

**Comment by Mariusthvdb** [comment]
since this is a closed issue, maybe we should take this elsewhere. Continue on the community, or on the custom-ui GitHub?
anyways, please post how you install custom-ui, and show also show the developer-tools/info of the custom-ui install

**Comment by poudenes** [comment]
They cut down this for a reason? Because many many icons I have add with their own customization.... Entity level, not global...

**Comment by Mariusthvdb** [comment]
Any customization using custom-ui is Ha global. Meaning, anywhere you use the entity, it is customized.

customize_glob is something else, that is used for customizing many entities at once, using wildcard *
