### ISSUE TITLE
Toggle switch for entity displays focus-shadow until clicked away

### ISSUE THREAD

**Issue by mwasowski** [home-assistant/frontend#5899]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I noticed recently that when I click an entity in card group (or single entity for that matter), the shadow that is displayed when clicking element does not go away until anything else is clicked making it loose focus. It looks like the animation gets stuck in the middle and clicking anywhere makes it finish.

## Expected behavior

When the toggle is clicked the entity focus shadow disappears. This is how controls work on the websites:

![16Nteh0Wdf](https://user-images.githubusercontent.com/1921808/82081852-5079e900-96e7-11ea-8e2d-75e7a6cc3448.gif)

It's official slide toggle from Angular Material. I don't know what HA uses but clearly it's not working right.

## Steps to reproduce

1. Add entity card with any type of a switch/input boolean
2. Change it's state
3. Observe shadow not disappearing fully

## Environment

- Home Assistant release with the issue: HA 0.109.6, HassOS 3.13, Supervisor 222
- Last working Home Assistant release (if known): -
- Browser and browser version: Firefox 76.0.1 x64
- Operating system: Windows 10 x64 Build 1909

## State of relevant entities

It's not relevant to specific entity but I noticed it after I added this.
```yaml
entities:
  - entity: sensor.bridge_state
  - entity: input_boolean.zigbee_permit_join
  - entity: timer.zigbee_permit_join
show_header_toggle: false
title: Zigbee
type: entities
```
![JfI0OFu6X2](https://user-images.githubusercontent.com/1921808/82075690-eceabe00-96dc-11ea-8c7f-31866fde9427.gif)

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Don't just open a new issue.

**Comment by mwasowski** [comment]
Then don't close ones I opened without any meaningful answer. Saying 'This is just how websites work, if you click something it gets focus.' is just rude and treats me like I'm a halfwit that posts issues without any idea what he's doing.
