### ISSUE TITLE
110b3 - Cards with "Toolbar" are shown invisible, except the buttons work

### ISSUE THREAD

**Issue by BradleyFord** [home-assistant/frontend#5905]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem
Since 110 beta started all cards with a "Toolbar" capability show the toolbar with the icons totally invisible, yet I can hover over them our click on them.
I have tried with the stock and a dark theme.

The image at this link: https://pasteboard.co/J8EazCn.png

## Expected behavior
In the previous release, the "Toolbar" portions of the cards I could easily see the icons like normal and press the buttons.
The mini-humidifier card I now cannot see anything, but when I press where the icon should be it pops out the toolbar.

## Steps to reproduce
Open HA

## Environment
- Home Assistant release with the issue: 110b0 to 110b3
- Last working Home Assistant release (if known):109.6
- Browser and browser version: Chrome
- Operating system: Windows

## Problem-relevant configuration
Cards that have the issue:
https://github.com/denysdovhan/vacuum-card
https://github.com/artem-sedykh/mini-humidifier

## Javascript errors shown in your browser console/inspector
None

**Comment by zsarnett** [comment]
Please open issues with these cards
