### ISSUE TITLE
Allow non administrator users access to add-ons

### ISSUE THREAD

**Issue by KieranDrain** [home-assistant/frontend#5907]
## The request

When an add-on like Grocy are added from the Add-on store there's an option to add them to the sidebar however this is only available for Admin users.

Allow add-ons to be selectively added for non administrator users.

## The alternatives

The alternatives are to expose the addons to the internet/via a reverse proxy if they have a configurable web server and expose themvia a lovelace UI website card to normal users. This requires  a reasonable amount of other work and not all features may work.

## Additional information

If there's a way to customise the sidebar/expose non admin users to addons i'd be happy to hear it.

**Comment by davfv** [comment]
Hi!
Is this feature in the scope to be developed anytime soon?

To give some context as why I'd find this feature useful: I have a tablet with kiosk logged to home assistant as a plain user, so nobody can edit the configuration. But would be great that everybody at home is able to see some of the add-ons like Grocy.

**Comment by printplaatreparatie** [comment]
Hi, I would love this feature aswell, so others in the house can view the security camera's in MotionEye.

**Comment by quieThu** [comment]
Lookin forward to this feature too! 
What would bee a good implementation IMO is to have an other switch like this in the addon's supervisor view, but with the title: "Show in sidebar for all users"
![image](https://user-images.githubusercontent.com/60850998/105757297-16d3d000-5f4e-11eb-9b3f-386dbd6af49f.png)
Or maybe have a dropdown here in which we can select which user groups can have access to the addon? 
..._crossing fingers for more user groups in the future_

**Comment by mikemanha** [comment]
Hey friends,
In the past, it was also possible to access addons from a user who is not an administrator, but in the latest versions of HA it is no longer possible.
This is definitely an important function that will allow all users to operate the system without the fear of destroying or changing functions unintentionally or perhaps even intentionally ...
Is an update expected?

**Comment by Griever102** [comment]
I to would find this option extremely useful.

**Comment by edashbolt** [comment]
I would like to see this feature implemented as well

**Comment by spacegaier** [comment]
Please refrain from those "spammy" +1 comments and just add a thumbs-up to the original post instead. Thank you.

**Comment by spacegaier** [comment]
> 
> 
> This is definitely an important function that will allow all users to operate the system without the fear of destroying or changing functions unintentionally or perhaps even intentionally ...

You could argue that with allowing that access to add-ons for regular user, they s do actually have the power to destroy or change things (and therefore should "fear" it 😉?). E.g. I am thinking of add-ons that give access to the YAML configuration (VSCode), the devices in your setup (ESPHome) or even terminal/ssh consoles.

So I think just giving access to all add-ons is not the way to go. We need something more fine grained.

**Comment by ludeeus** [comment]
This is up to the add-on author with the `panel_admin` add-on config setting <https://developers.home-assistant.io/docs/add-ons/configuration>

**Comment by oeiber** [comment]
> This is up to the add-on author with the `panel_admin` add-on config setting https://developers.home-assistant.io/docs/add-ons/configuration

I've developed a local addin which also includes `"panel_admin": true`
The addin is shown in user's sidebar, but he's unable to open it. The user receives the following error: `Unable to fetch add-on info to start ingress`

**Comment by ludeeus** [comment]
That should work, so open an issue where you fill out the provided issue template 👍
