### ISSUE TITLE
Screen refresh every minut 

### ISSUE THREAD

**Issue by balou2311** [home-assistant/frontend#5909]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
In my browser a screen refresh takes place every minuut ( tested is in google chrome en Egde Chrominum, I get it in all the sides HA sides running in mij HA server after upgrading tot 109.6

It is fore example not posible to build in Node Red of grafana because it wil send yuo to  the first page after a every Minuut.  
-->

## Expected behavior

Not to refresh 

## Steps to reproduce

just work in HA 
-->

## Environment

HA 109.6
Edge Chromium 81
Google Ghromium 81 
Umbutu LTS B 18

  

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
There is 0 information here. I am guessing this issue is from a custom component. Or even a browser extension. Please let us know your configuration as we use a Reactive Dom. We don't refresh the page for many things

**Comment by balou2311** [comment]
Thanks is found it, deleted the HACS intergration. Problem salved
