### ISSUE TITLE
Ignored items in integration card list 0.110

### ISSUE THREAD

**Issue by sagitt** [home-assistant/frontend#5910]
## The problem

I see ignored items in the integration list even if "show ignored" is not enabled. like fritz. i don't know if this happen for all integrations or only fritz.

![Schermata 2020-05-17 alle 10 49 20](https://user-images.githubusercontent.com/169086/82139965-457ca100-982c-11ea-82b6-0e4e5999dcc1.png)

## Environment
- Home Assistant Core release with the issue: 0.110b3
- Last working Home Assistant Core release (if known): 0.109.6 
- Operating environment (Home Assistant/Supervised/Docker/venv): HassOS proxmox
- Integration causing this issue: All or only Fritz
- Link to integration documentation on our website: n/a

**Comment by SeanPM5** [comment]
There's an existing issue for this, please post it in here: https://github.com/home-assistant/frontend/issues/5875
