### ISSUE TITLE
Persist selected calendars in Calendar panel

### ISSUE THREAD

**Issue by gadgetchnnel** [home-assistant/frontend#5912]
## The request

Currently, the selected calendars in the Calendar panel (added in 0.110) are not persisted across page reloads or when navigating away from the page. This means that, if there is a calendar you don't want to display the events for, you need to uncheck this every time you open the Calendar panel. It would be useful if this could be persisted either to local storage or the backend.

## The alternatives

Alternatively, a way to permanently remove a particular calendar from the Calendar panel (while still allowing events to be tracked for automations, etc.) would serve the same function.

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/issues/5858
