### ISSUE TITLE
Weather card: Wind Speed has no direction attribute

### ISSUE THREAD

**Issue by Molodax** [home-assistant/frontend#5924]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Wind speed as an attribute is missing direction even if wind speed includes direction in the weather attributes.

## Expected behavior
It should show speed and direction, also word "speed" seems redundant.

## Environment

- Home Assistant release with the issue: 0.110.0b3
- Last working Home Assistant release (if known): 0.108.x
- Browser and browser version: Chrome 81.0.4044
- Operating system: Android 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
![Screenshot_20200518-213851_Chrome](https://user-images.githubusercontent.com/22867988/82254792-d1d5b380-9953-11ea-9ea0-3d8026d51bb1.jpg)
![Screenshot_20200518-213533_Chrome](https://user-images.githubusercontent.com/22867988/82254809-d69a6780-9953-11ea-98a9-6c59b0ec72c3.jpg)

**Comment by Molodax** [comment]
Still the same in 0.114.x

**Comment by danimart1991** [comment]
I would like to take this issue. 

**One question about code:**
Could I import src/data/weather.ts in src/dialogs/more-info/controls/more-info-weather.ts and src/panels/lovelace/cards/hui-werather-forecast-cards.ts or there are an architecture decision to no import? I see a lot of repeated code in the three files.

**Comment by zsarnett** [comment]
We should align the repeated code in the weather.ts data file. and import into both places
