### ISSUE TITLE
Set first day of the week in calendar panel

### ISSUE THREAD

**Issue by uphillbattle** [home-assistant/frontend#5941]
The current calendar view has Sunday as the first day of the week. In Europe, Monday is considered the first day of the week. It would be great if the user could select which day is the first of the week.

**Comment by p4sI** [comment]
Fullcalendar already supports this based on a property called `firstDay` which should be set by setting the `locale`. 
The `locale` is set:
https://github.com/home-assistant/frontend/blob/dev/src/panels/calendar/ha-full-calendar.ts#L162

 However the `firstDay` is not. Maybe this helps to find the issue.

@zsarnett maybe you know whats wrong here?

**Comment by Moonbase59** [comment]
This is really needed! And of course it would be just great if could be made dependant from the viewing user’s locale …

**Comment by mirekmal** [comment]
Please, please, do this explicitly configurable... we already struggle enough with time settings (12 vs 24 hours) being automatically detected and not working as users want.

**Comment by breti** [comment]
Please... this is still an issue in 0.115.

**Comment by sgtsilver** [comment]
Still an issue with 0.116.4

**Comment by zsarnett** [comment]
Nothing has been merged. Add a +1 but please do not comment :)
