### ISSUE TITLE
Upgrade to 110, pressing stuff not working as expected

### ISSUE THREAD

**Issue by atxbyea** [home-assistant/frontend#5942]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

After upgrading to 110 pressing stuff on the frontend brings up the context halfway down the page, I am also missing directional arrow on my simple-thermostat cards, theme issue there?
## Expected behavior

Opening the context from top to bottom
## Steps to reproduce

Was working fine on my config before 110
## Environment

Happens in the mobile app, but also issues are seen in both firefox and chrome
- Home Assistant release with the issue: 0.110
- Last working Home Assistant release (if known): 0.109.6
- Browser and browser version: Firefox \ Chrome \ Mobile app all latest versions
- Operating system: Android and Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

See my repo for UI config
https://github.com/atxbyea/HA-Config/

Image of how it appears in the mobile app here 
![Screenshot_20200520_134908_io homeassistant companion android](https://user-images.githubusercontent.com/46269073/82442891-ccd24a80-9aa0-11ea-84ae-932a90c81c30.jpg)
![Screenshot_20200520_134905_io homeassistant companion android](https://user-images.githubusercontent.com/46269073/82442892-ce037780-9aa0-11ea-9908-66c6546cdab5.jpg)

**Comment by bramkragten** [comment]
Update HACS for the more info positioning problem and report the other issue with the developer of that card `paper-icon-button` and `iron-icon` are no longer supported. (https://developers.home-assistant.io/blog/2020/05/09/custom-iconsets)
