### ISSUE TITLE
Vertical spacing in Weather Card too big.

### ISSUE THREAD

**Issue by mirekmal** [home-assistant/frontend#5951]
## The problem

After upgrade to 0.110 vertical spacing between elements of Weather Card got significantly incresed:
![Screenshot 2020-05-20 at 19 04 44](https://user-images.githubusercontent.com/6892816/82475430-c78af500-9acc-11ea-89f1-63f2d2c23e47.png)

## Expected behavior

Vertical spacing between row with weeknames and weather icons and beetween icons and temperature forecast shoul dbe reduced to previous values (0.109.x) to reduce space accupied by card and improve aestetics.

## Steps to reproduce

Created new weather card on new, emty view.

## Environment

Running Home Assistant as VM in ESXi 6.0 free server using standard vmdk image.

- Home Assistant release with the issue: 0.110
- Last working Home Assistant release (if known): 0.109.6
- Browser and browser version: Safari
- Operating system: OS X 10.15.4

## Additional information
Issue cannot be replicated using Chrome on the same computer, so seems to be Safari specific.

**Comment by fedebruni84** [comment]
Same here.
Seems WebKit related, can be replicated using iOS Companion App, iOS Safari or iOS Firefox.
Not on Mac/PC with Chrome.
