### ISSUE TITLE
Add card picker appears broken on demo site

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#5953]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Card picker appears to be messed up on the demo site.

![image](https://i.imgur.com/8813x3Z.png)

I see spinning progress indicators on half the cards on my desktop browsers. Tried first in Chrome and then in Firefox. I can scroll the card picker dialog in Chrome but nothing else - can't type into the search field and cannot press the cancel button at the bottom of the dialog. 

My MacBook Pro's fans spin up, and eventually I get the Chrome "Page Unresponsive" prompt where I can kill the tab. 

![image](https://i.imgur.com/SBUKIH1.png)

iPhone is a sort of similar issue, cannot scroll it at all. After about a minute iOS seems to automatically kill the page. So that's three different browsers across desktop and mobile.

My own setup with 0.110 does not have this issue so this appears limited to demo.

## Environment

- Home Assistant release with the issue: 0.110
- Last working Home Assistant release (if known): 0.109.6
- Browser and browser version: latest Firefox and Chrome (desktop), latest Safari (iOS 13.5)
- Operating system: macOS, iOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
Error in the console at the click of the FAB
`hui-weather-forecast-card Error: Invalid card configuration`


Only thing pending in the network:

![image](https://user-images.githubusercontent.com/18730868/82490277-0a3ed400-9ab1-11ea-97e1-ba5ca967baf1.png)
![image](https://user-images.githubusercontent.com/18730868/82490306-11fe7880-9ab1-11ea-971d-79e332bacda2.png)

**Comment by zsarnett** [comment]
Also not seeing any icons. After clearing cache

**Comment by bramkragten** [comment]
Cache issue, although the freezing of the page is... not nice...

**Comment by SeanPM5** [comment]
Just saw this forum thread, three people saying they've been getting freezing here since 0.109 (or "some weeks") apparently. https://community.home-assistant.io/t/lovelace-ui-add-card-panel-freeze-unresponsive-for-long-time/195483

But still haven't been able to reproduce on my production instance, only the demo.
