### ISSUE TITLE
Picture element mess

### ISSUE THREAD

**Issue by niraviry** [home-assistant/frontend#5954]
Just upgraded to version 0.110.0. The SmartIR error was gone but:
1. Custom Header does not work properly anymore. There is no header at all if the component is loaded.  
2. In all the pages containing picture element, the icons size control in Lovelace does not do anymore, the size is always too small and the zoom is not working as before. Zoom in stretches the whole screen to an oversized screen while the icons size in unchanged.

**Comment by bramkragten** [comment]
1. that is a custom component, that just happend to receive an update with fix, but you should be at the repo of the component.

2. you should probably use `mdc-icon-size` instead of the `iron-icon-width` and `iron-icon-height` you are using now.

**Comment by niraviry** [comment]
Great. Thanks.

בתאריך יום ד׳, 20 במאי 2020, 23:14, מאת Bram Kragten ‏<
notifications@github.com>:
