### ISSUE TITLE
weather-forecast card does not respect `theme:` override when using custom icons.

### ISSUE THREAD

**Issue by pironic** [home-assistant/frontend#5956]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I have created a custom weather.yaml theme and included via the configuration.yaml file, then set a custom theme in the lovelace card but the only way the lovelace card actually utilizes it is if i `frontend.set_theme` to `{"name":"weather"}`... it seems the `theme: weather` option on the lovelace config will only take the color variables into account when generating the card. The preview generator also only shows these if you add a `"` at the end of the config (until you hit save). A clue into what is happening is via the inspect element. screenshots attached. 

Config: 
![image](https://user-images.githubusercontent.com/541154/82493239-dc539280-9aa4-11ea-9e01-cefdca596964.png)
_(i understand there are additional unused states in this image)_

![image](https://user-images.githubusercontent.com/541154/82493248-e2497380-9aa4-11ea-94b7-a0b4981737d6.png)
Yields:
![image](https://user-images.githubusercontent.com/541154/82493284-f1c8bc80-9aa4-11ea-94a8-71ef65538202.png)

![image](https://user-images.githubusercontent.com/541154/82493302-f5f4da00-9aa4-11ea-9058-ca49ec4ab25c.png)
Yields:
![image](https://user-images.githubusercontent.com/541154/82493319-fb522480-9aa4-11ea-9aab-b0160ad4bece.png)

## Expected behavior

Ability to set create a theme that only includes the custom icons for the weather, then set the theme of the card to override the icons only. 

If I set the backend theme to 'weather' then i see this (which is expected):
![image](https://user-images.githubusercontent.com/541154/82493816-d27e5f00-9aa5-11ea-83b7-b1fed2b393ec.png)

Should be able to set a theme independently of the theme override in the lovelace card config.

## Steps to reproduce

screenshots above.

## Environment

HA-Core 0.110.0

- Home Assistant release with the issue: 0.110.0
- Last working Home Assistant release (if known): new option via (https://github.com/home-assistant/frontend/pull/5736) . not available < 0.110.0
- Browser and browser version: Chrome 81
- Operating system: Win10

## State of relevant entities

n/a

## Problem-relevant configuration

```yaml
frontend:
  themes: !include_dir_merge_named themes
weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api
    mode: hourly
```

## Javascript errors shown in your browser console/inspector

n/a

**Comment by bramkragten** [comment]
You are using custom cards in this config, please try it without.

Also, please don't post screenshots of your config but put it in a code block. This makes it easier for us to replicate it without having to retype it all.
