### ISSUE TITLE
Lovelace, slow in loading elements after 110.0

### ISSUE THREAD

**Issue by pergolafabio** [home-assistant/frontend#5957]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I just updated to 110.0, but i am facing issues with my lovelace
i am mssing buttons (no red error) , also i am using declutter templates with markdown for header texts... they are slow
when i do a refresh, sometimes after about 5 secs they show up,

its hard to explain, but seems lovelace is doing something in backround thats its not possible to render, and then other stuff is showing up

i am seeing no errors in my log files about frontend, thats also strange

never had those issues from like release 56.x or something like that

## Expected behavior

Render should be fast

## Environment

- Home Assistant release with the issue: 110.0
- Last working Home Assistant release (if known): 109.6  and below
- Browser and browser version: chrome
- Operating system: Hassos on ESXI system

**Comment by bramkragten** [comment]
So all your issue are with custom cards? Please report them to the developers of the cards.

**Comment by pergolafabio** [comment]
No, Markdown, is just header text, that's also slow in loading...

**Comment by bramkragten** [comment]
Share your config please and fill out the issue template

**Comment by pergolafabio** [comment]
Seems related to declutter card, will close now
