### ISSUE TITLE
Default "Overview" dashboard not hidden in mobile app sidebar

### ISSUE THREAD

**Issue by lalexdotcom** [home-assistant/frontend#5960]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The default Lovelace dashboard cannot be removed, only hidden when you create another dashboard.
But in the mobile app (iOS), it stays visible in the sidebar.
Is there something I'm doing wrong or is it a bug?
I wasn't sure if I had to post this bug in the frontend or iOS repository...

<img width="422" alt="Screenshot 2020-05-21 at 10 29 47" src="https://user-images.githubusercontent.com/15171326/82539667-1b89ee00-9b4e-11ea-8f05-dc0fd2bfea76.png">

![IMG_1145](https://user-images.githubusercontent.com/15171326/82539505-d5cd2580-9b4d-11ea-8930-4c7895c4a127.jpg)

## Expected behavior

Overview dashboard shouldn't be visible in the mobile app's sidebar

## Steps to reproduce

Create a second dashboard to disable the default one

## Environment
I'm on 0.110, but it was the same in 0.109

arch | armv7l
-- | --
dev | false
docker | true
hassio | false
installation_type | Home Assistant Core on Docker
os_name | Linux
os_version | 4.19.97-v7l+
python_version | 3.7.7
timezone | Europe/Paris
version | 0.110.0
virtualenv | false

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
That setting is device based, did you change it on your iOS device?

**Comment by lalexdotcom** [comment]
I didn't. Actually, I changed the server, and uninstalled/reinstalled Companion App to be sure not to keep a single setting...

Would you know where I can change this setting? I don't see any setting in the "Lovelace Dashboard" settings, neither on the iOS app...

**Comment by bramkragten** [comment]
You need to set it as default on your iOS device, just like you did on your other device.

**Comment by lalexdotcom** [comment]
Argh, I feel so dumb! 😅

Would there be a way to set it by default for all users? So the other non-admin users can't see it by default?
