### ISSUE TITLE
Hide custom panels in mobile app

### ISSUE THREAD

**Issue by lalexdotcom** [home-assistant/frontend#5961]
## The request

I'm using custom panels to have a global view of my server and automations (NodeRed, Portainer, more to come...), but those panels are not really mobile-friendly....

A "require_admin" option already exists from "panel_custom" and "panel_iframe" integrations, wouldn't a "mobile" option set to _true_ by default be a good idea?

## The alternatives

I didn't investigate that far, but I'm on my way ;-)

## Additional information
Thanks guys for your awesome work!

**Comment by zsarnett** [comment]
This can be done by customizing the panels in the menu in 0.115
