### ISSUE TITLE
Option to hide the calendar panel

### ISSUE THREAD

**Issue by andriej** [home-assistant/frontend#5963]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Can't 'hide' Calendar view

## Expected behavior

UI -> Dashboards - Calendar enable/disable or other option to hide, as it's not needed dashboard/view for me.

## Environment

- Home Assistant release with the issue: 0.110.0
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome 
- Operating system: Windows 10

## State of relevant entities

n/a

## Problem-relevant configuration

n/a

## Javascript errors shown in your browser console/inspector

n/a

**Comment by lalexdotcom** [comment]
Actually, on the same topic, it would be great to have the calendar and shopping list integrations configurable in the UI, with the ability to enable/disable the panel, to be able to choose between the card and the panel...

**Comment by wojtek14a** [comment]
I think that is is slightly related to a feature request of mine to add the possibility to fully rearrange panels on the sidebar: #5785.
I believe both feature requests could and maybe even should be discussed together :smile:

**Comment by SeanPM5** [comment]
I agree with @wojtek14a personally. I think it will quickly get out of hand UX-wise if there's like 10 different methods of adding/removing things from the sidebar and each integration handles it slightly differently. 

That's arguably already the case today. If you want to remove the Map from sidebar you have to go through the hassle of ditching `default_config:` and manually adding a bunch of things. But with Supervisor / Ingress it's simply a toggle from the UI. And then for other things you have to use YAML again with `panel_iframe:` etc.

I think it would make sense to consolidate a lot of this stuff. One single place to add/remove/re-arrange sidebar items as Wojciech proposed.

**Comment by zsarnett** [comment]
0.115
