### ISSUE TITLE
Strange behaviors with custom cards after 0.110 update

### ISSUE THREAD

**Issue by RomRider** [home-assistant/frontend#5965]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I can see quite some issues with the latest update and custom cards because the hass object is (sometimes not always, but quite often) being assigned while still being `undefined`. Is this expected from lovelace?
Also sometimes the `setConfig` is called before the element is created.
```txt
TypeError: t.setConfig is not a function
    at /__vscode-remote-uri__/workspaces/xxxx/dist/frontend_latest/chunk.3794da5240b9979884e1.js:2140:6459
```

Both of those things happen only after a refresh of the page (not reload from the menu). A "reload" from the menu fixes it but it's definitely not ideal.

## Environment

- Home Assistant release with the issue: 0.110.0
- Last working Home Assistant release (if known): 0.109.6
- Browser and browser version: Chrome MacOS / Chrome Android
- Operating system: MacOS / Android

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Where do you get `hass` before it is defined? I can see it happening in picture elements, made a fix for that. Any other place?

The `setConfig` issue is already fixed.

**Comment by RomRider** [comment]
I can see that in a simple horizontal-stack also
