### ISSUE TITLE
weather-forecast card: wrong measurement unit for temperatures

### ISSUE THREAD

**Issue by betarho** [home-assistant/frontend#5968]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

1. Measurement unit of forecast temperatures is, currently, the "°" symbol. Example: 23.8°. This is wrong: the "°" symbol is the measurement unit for angles.
2. Measurement unit of the current temperature is correct, but the font size is different from the one used for the temperature value itself.
3. Measurement unit of both forecast temperatures and current temperature are attached to the value, without any space.

## Expected behavior

1. For temperatures, it is necessary to express what kind of degrees they are referred to. So, it is "°C" or "°F". Example: 23.8 °C.
2. The measurement unit font size of the current temperature is exactly the same as the one of the value.
3. In order to have consistent measurement units with all the application ones, a space has to be present between the temperature value and its measurement unit, in all the weather-forecast card.

## Steps to reproduce

Look at the weather-forecast card.

## Environment

arch | x86_64
chassis | vm
dev | false
docker | true
hassio | true
host_os | Debian GNU/Linux 10 (buster)
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 4.19.0-8-amd64
python_version | 3.7.7
supervisor | 222
timezone | Europe/Rome
version | 0.110.0
virtualenv | false

- Home Assistant release with the issue: Home Assistant version 0.110.0
- Last working Home Assistant release (if known):
- Browser and browser version: Firefox 76.0.1 (64-bit) on PC
- Operating system: GNU/Linux (Ubuntu 20.04)

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
Same behavior also on mobile app, Home Assistant, version 1.9.0-167, for Android

**Comment by zsarnett** [comment]
The unit is not mandatory. and is not only a measurement for angles. its a measurement for degrees. 

I have 0 idea what you are talking about for the font size

And all these are purely aesthetic opinions

**Comment by betarho** [comment]
Temperature measurement units are:
°C -> Celsius degrees
°F -> Fahrenheit degrees
K -> Kelvin degrees
R -> Rankine degrees

Having only "°" does not say anything about a temperature. It is the measurement unit of angles, not temperatures. And why shouldn't the unit be mandatory? What is a number without its correct measurement unit?

**Comment by betarho** [comment]
In relation to the font size, please look at the attached picture. The "C" letter of the "24.9°C" measurement has a different size, if compared to the "24.9" value.
![Screenshot from 2020-05-21 15-59-47](https://user-images.githubusercontent.com/27917879/82566426-31160c80-9b7c-11ea-80c2-2b2f1b2e52e4.png)

**Comment by bramkragten** [comment]
It is pretty common to leave the unit out as people will know that the temperature in the forecast will be the unit as that of the current temperature.

It is not for angles, but for degrees, what angles are also defined in.

**Comment by betarho** [comment]
Please don't consider these as purely aesthetic opinions. I am talking about measurement correctness in value, measurement unit and syntax.

**Comment by betarho** [comment]
It is the only place in Home Assistant where temperature measurement unit is "°".

**Comment by betarho** [comment]
It is clear that it is related to the temperature, but it is wrong.

**Comment by bramkragten** [comment]
maybe not scientifically correct, but common.
![image](https://user-images.githubusercontent.com/5662298/82567140-40e22080-9b7d-11ea-9c18-33492ecdef1d.png)

**Comment by betarho** [comment]
Very, very bad.

**Comment by betarho** [comment]
I worked in metrology sector, so I cannot stand it...

**Comment by bramkragten** [comment]
let's stick to opinions and not condemnation

**Comment by betarho** [comment]
Anyway, please consider what I said as suggestion to improve the card. It's your decision whether to apply it or not.

**Comment by zsarnett** [comment]
As I have researched and seen in many examples. From a Common UI perspective the way the card currently is displaying the symbols is normal and common. Therefore this will stay as is. I appreciate the feedback and understand this may be out of the norm from a meteorologist or scientific perspective.

**Comment by SeanPM5** [comment]
Just for more specific examples, here are Apple Weather and Dark Sky widgets:

![Weather](https://user-images.githubusercontent.com/9065557/82568937-8be43f80-9b4d-11ea-8ed0-6c67a40f1c84.jpg)

Alexa
![Weather-Alexa](https://user-images.githubusercontent.com/9065557/82568981-9999c500-9b4d-11ea-84bc-fab7abc76623.jpg)

Google
![Weather-Google](https://user-images.githubusercontent.com/9065557/82568999-9dc5e280-9b4d-11ea-91cd-1113db7bd382.jpg)

CARROT Weather
![IMG_A50A8F51A2E1-1](https://user-images.githubusercontent.com/9065557/82569425-3a888000-9b4e-11ea-88d8-b42531ec15c1.jpeg)

It seems to be standard practice among weather apps and widgets to leave out the unit.
