### ISSUE TITLE
Gap between top of screen and window of entity 

### ISSUE THREAD

**Issue by Molodax** [home-assistant/frontend#5971]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Gap between top of screen and window of entity:

![Screenshot_20200521-182319_Chrome](https://user-images.githubusercontent.com/22867988/82581643-2ade5b00-9b91-11ea-8586-e5afa69724fe.jpg)

## Expected behavior
Window should be positioned at the top

## Environment

- Home Assistant release with the issue: 0.110.0
- Last working Home Assistant release (if known): 0.109.x
- Browser and browser version: Chrome 81.0.4044
- Operating system: Android 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Update HACS and clear your cache.

**Comment by Molodax** [comment]
Cache was cleared and HACS is up to date.

**Comment by bramkragten** [comment]
Do you have other custom icon sets installed?
