### ISSUE TITLE
Custom Icon Sets - Support for other/multiple SVG elements

### ISSUE THREAD

**Issue by tommyjlong** [home-assistant/frontend#5973]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem
Looking at the documentation for [Custom Icon Sets](https://developers.home-assistant.io/blog/2020/05/09/custom-iconsets/), it doesn't appear to support SVG elements other than `<Path>` and for `<Path>` only supports the attribute d=, and only one `<Path d=>` at that. 

I have developed a few custom SVG Icons using Inkscape.  These Icons have several other types of elements such as: `<rec>` (rectangle), and for a given element, that are multiples of such an element.  Some of these SVG elements have other attributes such as `transform=rotate()`. Sometimes `transform` is an attribute of the container `<g>`.  There are also multiple containers as well.  Anyway, I don't see a way to do this with the new icon loading scheme.

These were all working prior to 0.110 using HTML using the `<ha-iconset-svg>`.
I mainly copy/pasted all the multiple container parts of the SVG file defined by `<g>` and placed them
inside the HTML file, and all worked.  Is there an API to do the same now for new icon loading scheme?

## Environment

- Home Assistant release with the issue: 0.110.0
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
You probably can transform your svg to a single path with inkscape, except when there are multiple colours or animation that will not be possible.

**Comment by tommyjlong** [comment]
I will play with inkscape some over the weekend and let you know.

**Comment by bramkragten** [comment]
👍 Use the object to path function

**Comment by tommyjlong** [comment]
The best I have been able to do is use the "Path->Combine" which will take all the objects, and convert them to one path element.  That's the good news.  The bad news, is that some of the objects I have are rotated, and when they are combined into one Path, the final icon is also rotated but Inkscape takes care of this by using a path attribute "transform=matrix()" which allows the icon to be properly rotated back.  With HA in Chrome, when I manually add the transform attribute (using Chrome Developer) indeed the icon appears in the correct orientation.  The final piece that is missing, is that the icon is still not in the correct position (too high vertically and gets cropped).  I am not sure what Inkscape uses to correct this, but I do know I can use Viewbox to fix that.

Anyway I hope it will be possible to add support for the more general way of loading SVG elements and attributes like it was done earlier with HTML.

**Comment by bramkragten** [comment]
You have support for setting a custom viewbox.

**Comment by zsarnett** [comment]
The only icons we dont support are duotone
