### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications.

### ISSUE THREAD

**Issue by vlad36N** [home-assistant/frontend#5974]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Log Details (ERROR)

Logger: frontend.js.latest.202005191
Source: components/system_log/__init__.py:209
First occurred: 6:28:43 PM (4 occurrences)
Last logged: 6:48:43 PM
:0:0 ResizeObserver loop completed with undelivered notifications.

## Environment

- Home Assistant release with the issue: Home Assistant 0.110.1
- Last working Home Assistant release (if known): Home Assistant 0.110
- Browser and browser version: Firefox 76.0.1 (64-bit), Google Chrome Version 83.0.4103.61 (Official Build) (64-bit)
- Operating system:
arch | x86_64
dev | false
docker | true
hassio | true
host_os | Ubuntu 18.04.4 LTS
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 4.15.0-99-generic
python_version | 3.7.7
supervisor | 222

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
0 Information.... Please give as much detail as possible. Just the error message is nothing. Else this will be closed

**Comment by vlad36N** [comment]
It just appear in Log, after update to Home Assistant 0.110.1. 
Related to latest frontend.

**Comment by delta010** [comment]
I also have the same error after updating to 0.110.

**Comment by vlad36N** [comment]
Got additional:

Log Details (ERROR)

Logger: frontend.js.latest.202005191
Source: components/system_log/__init__.py:209
First occurred: 5:57:10 PM (4 occurrences)
Last logged: 6:54:33 PM

    https://xxxxx.xxxxxx.xxx/hacsfiles/frontend-20200522122100.js:1:0 NotSupportedError: CustomElementRegistry.define: 'hacs-frontendbase' has already been defined as a custom element
    :0:0 ResizeObserver loop completed with undelivered notifications.

**Comment by zsarnett** [comment]
Seems like a hacs issue. Try creating an issue in the hacs repo

**Comment by YRRK** [comment]
I don't have HACS and also have this isse. Waiting until 110.2 If still present, then i'll report the bug.

2020-05-24 16:59:20 ERROR (MainThread) [frontend.js.latest.202005191] :0:0 ResizeObserver loop completed with undelivered notifications.

**Comment by y0ast** [comment]
I do not use HACS either. But get the following in my log since the latest update:

```
Logger: frontend.js.latest.202005191
Source: components/system_log/__init__.py:209
First occurred: 4:13:37 PM (1 occurrences)
Last logged: 4:13:37 PM
```

```
:0:0 ResizeObserver loop completed with undelivered notifications.
```

Please reopen.

**Comment by YRRK** [comment]
Still there in 110.2

2020-05-24 19:43:02 ERROR (MainThread) [frontend.js.latest.202005194] :0:0 ResizeObserver loop completed with undelivered notifications.

**Comment by YRRK** [comment]
Still there in 110.2

2020-05-24 19:43:02 ERROR (MainThread) [frontend.js.latest.202005194] :0:0 ResizeObserver loop completed with undelivered notifications.

How can we provide more info? I don't have HACS.

---------------------

> 0 Information.... Please give as much detail as possible. Just the error message is nothing. Else this will be closed

**Comment by bramkragten** [comment]
Is anything broken? Probably not?

If you want to help, isolate what card or page is causing this log entry.

But it is probably save to ignore it.

**Comment by YRRK** [comment]
No nothing seems broken. But I try to persue things to make things better, and get all errors out of the log :) Aldoug this one I really don’t know what it means. Happens only after every reboot. If I have an idea what causes it I’ll let you know.

﻿
Is anything broken? Probably not?

If you want to help, isolate what card or page is causing this log entry.

But it is probably save to ignore it.

**Comment by vlad36N** [comment]
Happens after every reboot.
Every time hit or come back to main lovelace page: https://xxxxxx.duckdns.org/lovelace/0

**Comment by y0ast** [comment]
This seems fixed now.

**Comment by w35l3y** [comment]
In my case, it always happens when I type **slowly** in the search field of "Automation & Scenes"
If I type quickly, the error doesn't appear.

![image](https://user-images.githubusercontent.com/963510/161396835-9da06381-5e11-4e2e-9f0d-d2b0a9365c72.png)
![image](https://user-images.githubusercontent.com/963510/161396798-5c134f58-d792-440f-8d1e-933a969e898b.png)


## System Health

version | core-2022.3.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.103-v8
arch | aarch64
timezone | America/Recife

**Comment by MEKadan** [comment]
If I open in different tab the Settings -> Decices & Services -> Entities page, seems to be logging this every time I visit the tab and the Entities page is open there.

Helpers and Integrations are OK to visit in my case, the Devices page logs it when first operned, but not after switching to that tab later.

Obviously on that entities list there is something it does not like...

**Comment by yang3535** [comment]
I'm getting this in 2022.6.4

Why did this issue close?  I don't see any resolution from the previous submissions.

**Comment by msbc42** [comment]
Also seeing this on 2022.6.5 after every restart:

```
Logger: frontend.js.latest.202206010
Source: components/system_log/__init__.py:190
First occurred: 3:57:50 PM (1 occurrences)
Last logged: 3:57:50 PM

:0:0 ResizeObserver loop completed with undelivered notifications.
```

**Comment by cybernard** [comment]
Brand new version just updated today.
same error.

 Logger: frontend.js.latest.202206010
Source: components/system_log/__init__.py:190
First occurred: 8:22:36 PM (1 occurrences)
Last logged: 8:22:36 PM
:0:0 ResizeObserver loop completed with undelivered notifications.

**Comment by LeapFrogSupport** [comment]
Home Assistant Core 2022.6.6 (Docker container)

Logger: frontend.js.latest.202206010
Source: components/system_log/__init__.py:190
First occurred: 2:50:05 PM (18 occurrences)
Last logged: 3:10:13 PM
:0:0 ResizeObserver loop completed with undelivered notifications.

To replicate in Firefox 101.0.1 (64-bit): Click on Logs, then History, then Logs and observe above message.

Can not replicate in Chrome 102.0.5005.115 (Official Build) (64-bit) or Edge 102.0.1245.44 (Official build) (64-bit)

**Comment by akula3** [comment]
Logger: frontend.js.latest.202209072
Source: components/system_log/__init__.py:227
First occurred: 08:19:27 (58 occurrences)
Last logged: 19:06:49
:0:0 ResizeObserver loop completed with undelivered notifications.

 Home Assistant 2022.9.5 Supervisor 2022.09.1 Operating System 9.0 Frontend 20220907.2 - latest
