### ISSUE TITLE
.110:  Stack-in-card with (vertical-stack or horizontal-stack) using Chrome web browser

### ISSUE THREAD

**Issue by mkanet** [home-assistant/frontend#5976]
After upgrading to HA version .110, all my cards that use **stack-in-card** in **vertical-stack**s and **horizontal-stack**s are not displaying correctly (cards are not display at all).  This only happens with Chrome web browsers.  It does not happen with Android Home Assistant app or Windows legacy Edge web browser.

This issue is very easy to reproduce.  Just use stack-in-card with a vertical-stack or horizontal stack on Chrome.

**Comment by zsarnett** [comment]
Please fill out the issue template
