### ISSUE TITLE
Material Design Icons missing in Firefox private mode

### ISSUE THREAD

**Issue by mailq** [home-assistant/frontend#5981]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
After upgrading to HomeAssistant (on Docker) to 0.110.0 and 0.110.1 the icons in the Lovelace user interface went missing. Except the bell icon beside the notification menu entry. So no menu bar icons, no entity icons, no settings icons or close icons.

You can click them (if you know where they are) and they work perfectly, but you can't "see" them.

The only affected environment is Firefox in private mode. See down for more information.

## Expected behavior
The icons should be visible as before the update. Or as they do in "normal" mode.

## Steps to reproduce
- Clean Firefox cache and website data
- Change to Firefox' private mode (STRG+SHIFT+P)
- Open HomeAssistant URL
- Login

Alternative:
- Use Firefox' "Always in private mode" feature

## Environment

- Home Assistant release with the issue: 0.110.0 and 0.110.1
- Last working Home Assistant release (if known): all before 0.110.0
- Browser and browser version:
  - newest Firefox in "normal" mode: working
  - newest Firefox in "private" mode: failing
  - newest Chrome in "normal" mode: working
  - newest Chrome in "private" mode: working
  - newest Edge (Chromium) in "normal" mode: working
  - newest Edge (Chromium) in "private" mode: working
  - newest Android HomeAssistant app: working
- Operating system:
  - Ubuntu 20.04
  - Windows 10 1909
  - Android

## State of relevant entities

Any state. The problem is, that you even can't see the state.

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt
InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.
```

**Comment by bramkragten** [comment]
<https://bugzilla.mozilla.org/show_bug.cgi?id=781982>

It seems difficult to work around this at the time, Firefox is working on a solution, I'll see if we can skip the IDB in Firefox private mode.
