### ISSUE TITLE
Weather card only displays 3 rows instead of 5 rows (regression introduced in 0.109]

### ISSUE THREAD

**Issue by klada** [home-assistant/frontend#5990]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Home Assistant 0.109+ introduced a new weather card. This card only displays three rows instead of five rows, which breaks people's workflows. I am using OpenWeatherMap which displays 3 hour forecast steps. When leaving the house in the morning people need to know about the temps in the evening.

With the old weather card this was possible, with the new weather card it is not possible any more. So this is a regression.

This screenshot shows the problem:

![hass-ui-bug](https://user-images.githubusercontent.com/3250940/82119508-81a5f800-977f-11ea-9988-2369a41fe7ce.png)

## Expected behavior

Old behavior with the same viewport (notice the 5 forecast rows):

![hass_weather_old](https://user-images.githubusercontent.com/3250940/82119503-7357dc00-977f-11ea-8212-96ea3ccd0b4e.png)

## Environment

- Home Assistant release with the issue: 0.109, 0.110
- Last working Home Assistant release (if known): 0.108
- Browser and browser version: Google Chrome
- Operating system: Linux

## Additional information

- This regression is annoying especially with OpenWeatherMap, as you lose parts of today's forecast. For other weather providers this might not be too bad.
- The 3 rows depend on the viewport. On my desktop with a large screen resolution (WQHD) I am getting 5 rows. On the tablet in the hallway (on a 1080x1920 resolution) I am only getting 3 rows.

**Comment by spacegaier** [comment]
I assume instead of "rows" you mean "columns". There is a very recent commit from yesterday that seems to touch on that (reduces the minimum space required to still show 5 columns) and might actually fix your issue: https://github.com/home-assistant/frontend/commit/ba384b9eee6adbd7cdafb336b0ae981c3dac1802
