### ISSUE TITLE
Cover not reporting the correct state in Lovelace

### ISSUE THREAD

**Issue by pdgithub78** [home-assistant/frontend#5993]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I have an automation which closes the blind at sun set. This uses the following action:

cover.set_cover_position
  entity_id: cover.blind
  position: 58

The blind moves to the position, but does not set the position on the slide bar or enable the up arrow.

This was working prior to upgrading to 0.110 and also doesn't work correctly in 0.110.1

## Expected behavior

The blind moves to the defined position and the slide bar show that position in the entity card. Also because the blind is now no longer at 100 the up arrow becomes available.

## Steps to reproduce

Add a cover and make it available in an entity card.

## Environment

Home Assistant 0.110.1
Frontend version: 20200519.1 - latest

I have replicated this in Chrome and Safari on a mac book, also in the IOS app.

- Home Assistant release with the issue: 0.110.0 and 0.110.1
- Last working Home Assistant release (if known): working in prior release
- Browser and browser version: Chrome 81.0.4044.129 and Safari Version 13.1 (15609.1.20.111.8)
- Operating system: Mac OS X 10.15.4

## State of relevant entities

<img width="376" alt="Screenshot 2020-05-22 at 22 12 05" src="https://user-images.githubusercontent.com/60198486/82709873-7e2bd880-9c79-11ea-84c8-45241527f2d3.png">

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by iantrich** [comment]
Does your `Developer Tools -> States` for this entity report correct values?

**Comment by pdgithub78** [comment]
No, this also reports 100 when the slide bar is set to anything but 100.

**Comment by bramkragten** [comment]
That means this is not a frontend problem but a problem with your integration.

**Comment by pdgithub78** [comment]
It's using standard integration via Deconz. Automations can control the blind and also the slide bar, it's the current state that doesn't update.

**Comment by bramkragten** [comment]
So you should create an issue for Deconz in the core repo. If the frontend doesn't get the state from the integration we also can not show it.
