### ISSUE TITLE
Card organising stopped working properly

### ISSUE THREAD

**Issue by i00** [home-assistant/frontend#6001]
## The problem

Cards use to somewhat stack evenly in each of the three columns...
Before:
![image](https://user-images.githubusercontent.com/1435262/82723358-bd0d6d00-9d11-11ea-8fac-92d8e3d73a0f.png)

After:
![image](https://user-images.githubusercontent.com/1435262/82723369-c696d500-9d11-11ea-82fd-e4d2309be304.png)

## Environment

- Home Assistant Core release with the issue: 0.110.0
- Last working Home Assistant Core release (if known): 0.109.6
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker
- Integration causing this issue: ?
- Link to integration documentation on our website: ?

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by bramkragten** [comment]
This is fixed in 0.101.2
