### ISSUE TITLE
shopping list empty

### ISSUE THREAD

**Issue by mitaka8** [home-assistant/frontend#6006]
## Checklist

- [x] I have updated to the latest available Home Assistant version. (**0.110.1**)
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

when loading the shopping list card, it will render as empty until you load the integration on the sidebar.

## Expected behavior

that the card is populated when first loaded.
## Steps to reproduce

1. add the shopping list integration
2. add items to the list
3. add the shopping list card to lovelace
4. clear cookies
5. log in
6. observe empty list
7. click the tab in the sidebar (showing items on the list)
8. navigate back to lovelace (now also showing items) 
## Environment

- Home Assistant release with the issue: 0.110.1
- Last working Home Assistant release (if known): 0.109.*
- Browser and browser version: Firefox & chrome android
- Operating system: manjaro linux

## State of relevant entities

```yaml
title: Boodschappenlijst
type: shopping-list
```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by GP920** [comment]
Same issue here. Shopping list lovelace card doesn't initially appear populated. If I open shopping list from the sidebar OR "config UI" then immediately close out the shopping list lovelace card will then appear populated.
