### ISSUE TITLE
Icons not visible under in firefox

### ISSUE THREAD

**Issue by rvasten** [home-assistant/frontend#6008]
Dear support I have upgraded from a previous running installation of Home Assistant to 0.110.1

In version 0.110.1 the Icons are not visible in Firefox
![ScreenShot1](https://user-images.githubusercontent.com/51000999/82740222-04622080-9d47-11ea-8d04-6e7d215a36b5.jpg)
![ScreenShot2](https://user-images.githubusercontent.com/51000999/82740223-05934d80-9d47-11ea-9c47-4b41de0a78dd.jpg)
![ScreenShot](https://user-images.githubusercontent.com/51000999/82740245-48552580-9d47-11ea-8f1c-e4eb110c93b6.jpg)

**Comment by bramkragten** [comment]
You are probably running Firefox in private mode?

A fix for this is in 0.110.2

**Comment by bambi73** [comment]
I have same problem and I'm definitely not running in private mode.

I tried all "tricks" mentioned in release thread on forum without success.
Tried to clear cache & data, run Firefox in private mode (no cached data), run Firefox on clean VM, run Firefox from 3 different computers without success. So it doesn't look like browser stored status problem.
Tried to start clean new Home assistant docker without success.

Anyway I'll wait for 0.110.2 and see what happens :)

**Comment by rvasten** [comment]
> 
> 
> You are probably running Firefox in private mode?
> 
> A fix for this is in 0.110.2

Dear Bramkragten, I tried the same as Bambi73.
The Icones were working perfectly before the last update.
Upgrading to latest version 0.110. casted this issue.

I wait for the update thanks

**Comment by Goroxx123** [comment]
Can confirm the above, tried 2 Computers with fresh Firefox not in Private Mode and with the Tracker Blocker thingy turned of for HA. Only Errors in my Browser Log/Insprektor:
![grafik](https://user-images.githubusercontent.com/62506383/82755170-366c9480-9dd2-11ea-817b-655c888eacef.png)

**Comment by bambi73** [comment]
Not really sure why I didn't checked browser log myself. 
Found there bit more specific error:

`NotFoundError: IDBDatabase.transaction: 'mdi-icon-store' is not a known object store name`

from http://x.x.x.x:8123/api/hassio/app/chunk.a28c3e62d954cbdbabea.js

**Comment by bambi73** [comment]
So update to 0.110.2 helped, my icons are back.
