### ISSUE TITLE
Weather card: moon icon has no contrast with default theme

### ISSUE THREAD

**Issue by Molodax** [home-assistant/frontend#6009]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
It's barely visible icon of moon if a default theme in use. Apart from that, there is a weird inconsistency when one weather component shows clear night and another one "sunny".
![Screenshot_20200523-221534_Chrome](https://user-images.githubusercontent.com/22867988/82740236-2c518400-9d47-11ea-9c4e-a6f02310e7d7.jpg)

## Expected behavior
Default icons should be consistent in design and colour patterns as well as be readable if the default theme is in use.

## Environment

- Home Assistant release with the issue: 0.0109-0.110
- Last working Home Assistant release (if known): 0.108
- Browser and browser version: Chrome
- Operating system: Android 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by Molodax** [comment]
The issue is still there.

**Comment by KTibow** [comment]
One weather component shows hourly, the other one shows daily. Daily is for the day, not the night, and only updates every day. Mind editing that part out?
