### ISSUE TITLE
OpenWeather Wind_bearing error

### ISSUE THREAD

**Issue by anglrus** [home-assistant/frontend#6015]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
When wind_speed is 0 module can't find wind_bearing. As result error:
[homeassistant.components.openweathermap.sensor] Condition is currently not available: wind_bearing

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Please fill out the template. This not enough info to reproduce this.
