### ISSUE TITLE
Sidebar menu problem when press back button

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [home-assistant/frontend#6037]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

When open VSCode UI from sidebar, and then press browser back button cause multiple sidebar
![Screenshot from 2020-05-25 14-09-10](https://user-images.githubusercontent.com/17345129/82800905-b60d6880-9e91-11ea-9cbd-0ecdc80d528b.png)

## Steps to reproduce

    1. Open VSCode from sidebar
    2. Press back button

## Environment

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.19.0-9-amd64
python_version | 3.7.7
timezone | Asia/Tehran
version | 0.108.9
virtualenv | false

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Not seeing this. Please update Home Assistant and see if that solves it.

Also try a different browser and see if this is addon related by trying it with another addon.

**Comment by AmirHosseinKarimi** [comment]
I have checked with Chromium, this has not this problem.
But in Firefox Stable 76.0.1 which is latest version, I can produce this problem with but Terminal and VScode add-on.
