### ISSUE TITLE
Wrong display of vertical stack

### ISSUE THREAD

**Issue by Gunth** [home-assistant/frontend#6038]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I have 3 vertical stack within my view, by default they are showned 2 columns next to the others (like in the video bellow ), but when i edit the view and then close the editor without any changes the 3 clomuns are next to the others.

It seems to be related to the iframe card because i have another view with a iframe card and i have the same issue. The others view that containe vertical stack cards but without iframe cards are working correclty.

## Expected behavior

The 3 columns ( vertical-card ) need to be displayed next to the others.

## Steps to reproduce

Add 3 vertical stack cards, in the first one add 2 picture-entity cards, in the second an iframe card and in the last a weather card and also an iframe card.

## Environment

- Home Assistant release with the issue: 0.110.2
- Last working Home Assistant release (if known): 0.108 ( if i remember well )
- Browser and browser version: Chrome 
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

No errros
```txt

```

## Additional information
![Overview - Home Assistant 2020-05-25 10-23-26](https://user-images.githubusercontent.com/1955976/82800763-7f792300-9e7c-11ea-8c0b-da6b98dbdfee.gif)

**Comment by bramkragten** [comment]
<https://github.com/home-assistant/frontend/pull/6023>
