### ISSUE TITLE
Add-on documentation's config text unreadable with dark themes

### ISSUE THREAD

**Issue by digitalMedic** [home-assistant/frontend#6039]
**Home Assistant release with the issue:**

0.110.2

**Operating environment (HassOS/Generic):**

HassOS on Raspberry Pi 4B

**Supervisor logs:**

**Description of problem:**
When using a dark theme, the supervisor add-on documentation's config text is unreadable due to very light colored text on a white background (which is inset onto the dark theme).  Returning to the default theme fixes this problem.  This bug has occurred before in previous versions (somewhere in the 90.x versions I think).  This occurs on any add-on with a documentation section that explains configurable text.

Here is a screen shot of one of the add-on's documentation.

[Example](https://ibb.co/F7rGZhM)

**Comment by bramkragten** [comment]
You can change the color of the code background with: `--markdown-code-background-color`

**Comment by digitalMedic** [comment]
Where would I do that?  I am an end-user who just selected the theme from the profile section of HA.  Would I need to do that for any dark theme that I select?  Seems a tad excessive.

**Comment by bramkragten** [comment]
It is not possible that this occurred before because it was just added. And you could also wait for the themes to be updated.

**Comment by digitalMedic** [comment]
It was not this specific instance of the issue, but a similar one where when the user selected a dark theme, the text on some parts of the screen was unreadable (I think is was in the device list or something).  It would appear that we will have to wait for all of the dark theme authors to update their code.
