### ISSUE TITLE
Picture Glance Card: stream with custom UPDATE_INTERVAL

### ISSUE THREAD

**Issue by manny73** [home-assistant/frontend#6040]
Today I'm using "picture glance Card" with Zoneminder integration to view my cameras ( auto or live mode).
The "Auto mode"  refresh every 10 sec. It's possible to parameterized this value? The live method consume too many bandwith.
I've try with camera proxy entity ( remapping camera) , without any success.

Thanks
Manny 

File hui-image.ts

`const UPDATE_INTERVAL = 10000;
        () => this._updateCameraImageSrc(),
        UPDATE_INTERVAL
      );
    }
  }`

**Comment by RyuzakiKK** [comment]
Same here, I'm using picture glance to show my cameras images.

I'm in the position where I don't need a live stream but also the 10 seconds refresh rate is too long.
The ability to manually set the update interval would be very handy.

**Comment by zsarnett** [comment]
Please fill out the feature request template. Thanks
