### ISSUE TITLE
developer-tools/state loading/acting very slowly

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#6044]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

Using developer-tools/state used to be quite swift, and up to version 109.6 took most 2-3 seconds on , RPi4 4 meg instance. After having updated to 110.2 it really seems to to nothing at first, and then after about 15 seconds or so, finally loads the states. Typing in the filter field, really makes the interface unresponsive and long waits are a new fact.

## Expected behavior
A swift interface. As a comparison, the new configuration/entities pages loads practically immediately, indicating it is not a system issue of the setup or config itself?

## Environment

- Home Assistant release with the issue: 110.2
- Last working Home Assistant release (if known): 109.6
- Browser and browser version: Chrome, Safari on Mac all latest software per 25-5-2020
- Operating system: Mac OS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

nothing to add, no errors in the log.
I can add the other pages under developer-tools seem to be quicker than before, so that's good ;-)

**Comment by bramkragten** [comment]
Then you have a lot of states :-)

We can only make it fast if we would remove the attributes column, that's why we can't virtualize it.

**Comment by VDRainer** [comment]
For me it takes about 3-4 times longer than in 0.109.
Also typing in the filter fields takes longer then before. Sometimes if you searched an entity and delete chars with the backspace key, it takes a few seconds to remove them.
The number of entities/states hasn't changed.

**Comment by Mariusthvdb** [comment]
Yes, a major difference which can’t be explained by the states count.

Even took out 2 custom components and their states...  0.2 percent states less ;-)

States is unworkable in my config..

**Comment by VDRainer** [comment]
Two examples:
1. Pressing the backspace with the same speed, it stops and after a while removes the chars.
![backspace](https://user-images.githubusercontent.com/26381449/82834721-38158580-9ec2-11ea-9128-c84772c11f4c.gif)
2. So why not mark the text with the mouse and press 'Del'? I need to press 'Del' 14 times to remove it.
![mark_del](https://user-images.githubusercontent.com/26381449/82834801-7f037b00-9ec2-11ea-83ac-9cceda5c7af1.gif)

**Comment by bramkragten** [comment]
Did a little analyze and got it from 45 to 2.4 secs in my test :-)

**Comment by Mariusthvdb** [comment]
You have even more than I ;-)

Please add to 110.3 ?
