### ISSUE TITLE
Number of cards in a row on integrations page is changing back and forward while hovering

### ISSUE THREAD

**Issue by gerard33** [home-assistant/frontend#6052]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The integration cards on the integrations page are switching from 5 cards in a row to 6 cards in a row when hovering with the mouse on that page.

## Expected behavior

No moving of cards when screensize remains the same.

## Steps to reproduce

See attached gif
![integrations_page](https://user-images.githubusercontent.com/11230573/82946137-22758e00-9f9e-11ea-9911-e3f37f1ca40a.gif)

## Environment

- Home Assistant release with the issue: 0.110.3 (also in earlier versions of 0.110)
- Last working Home Assistant release (if known): 0.109
- Browser and browser version: Vivaldi 3.0 and Microsoft Edge 83.0
- Operating system: Windows 10

## State of relevant entities

See attached gif

## Problem-relevant configuration

n/a

## Javascript errors shown in your browser console/inspector

n/a

**Comment by gerard33** [comment]
Installed 0.111 but issue is still there. Can't even open the integrations page for Netatmo right now.

![integrations_page](https://user-images.githubusercontent.com/11230573/84423290-80e97000-ac1e-11ea-8602-0add49c41d65.gif)

**Comment by bramkragten** [comment]
What size is your window?

**Comment by gerard33** [comment]
I have a 3440x1440 screen and this happens when I set the browser in a split screen modus, so only using the right (or left) half of the screen.

When checking via Developer Tools - Elements the screen size of the HTML part is 1686x1277.

**Comment by bramkragten** [comment]
I am not able to reproduce. Can you be more specific when it happens? Any specific element changing?

**Comment by gerard33** [comment]
It just happens when hovering wit the mouse over the page. In the second example I tried to open the menu of the netatmo integration. Can I do anything else to help finding the issue?

**Comment by gerard33** [comment]
Any news on this? Otherwise I just have to expand the number of integrations I guess 😉

**Comment by bramkragten** [comment]
I have not been able to reproduce this, unfortunately... If you could help me out get a reproduction that would help a lot.

**Comment by gerard33** [comment]
Then it’s apparently a combination of the number of integrations with the screen size.
How can I help? Will giving you access to my HA via Nabu Casa work?
Or is sharing the screen sufficient?

**Comment by bramkragten** [comment]
Btw, I now see the browsers you tried, do you also get this in Chrome/Firefox?

**Comment by gerard33** [comment]
As discussed on Discord this doesn't happen in Chrome.
I have added 2 new integrations and now it doesn't happen in Vivaldi anymore as well. Will close the issue.
