### ISSUE TITLE
Custom Icons not loading when used on top views menu bar

### ISSUE THREAD

**Issue by badguy99** [home-assistant/frontend#6061]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Custom icons used in the top views menu bar do not load.
They do show up in the edit view popup, and if a new view is created with a custom icon, it is shown until the web browser is refreshed.

![image](https://user-images.githubusercontent.com/61918526/83056554-8acf7880-a04d-11ea-9902-125625a6afd1.png)

## Expected behavior

Expect custom icons on Top Views menu bar to be loaded.

## Steps to reproduce

1. Add a new view with a custom icon
2. See that the icon is shown
3. Refresh web browser and see that icon is no longer shown

## Environment

arch | aarch64
-- | --
chassis | embedded
dev | false
docker | true
hassio | true
host_os | HassOS 3.13
installation_type | Home Assistant
os_name | Linux
os_version | 4.19.114-v8
python_version | 3.7.7
supervisor | 224
timezone | Europe/London
version | 0.110.3
virtualenv | false

- Home Assistant release with the issue: 0.110.3
- Last working Home Assistant release (if known): before 0.110.0
- Browser and browser version: FF 76.0.1 / Chrome  81.0.4044.138
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
What custom icon?

**Comment by badguy99** [comment]
one loaded from /config/www/community/custom_icons/custom_icons.js :

```// Iconset API (Home Assistant 0.110 and up):

async function getIcon(name) {
  var CUSTOM_ICONS_MAP = {
'groundfloor': 'M27.66,14.....',
'firstfloor': 'M27.66,14.....',
'topfloor': 'M27.66,14.....',
etc...
};
    return { path: CUSTOM_ICONS_MAP[name], viewBox: "0 0 32 32"};
}
	
window.customIconsets = window.customIconsets || {};
window.customIconsets['custom'] = getIcon;
```

Which is registered as a Lovelace resource. I know this is working correctly, as they load on the main pages, and in the edit box when creating new views, just not on the top view menu bar.

**Comment by bramkragten** [comment]
Because it is not loaded yet when the menu bar is rendered. It is a timing thing. You should not add icons as a Lovelace resource but as [extra_module_url](https://www.home-assistant.io/integrations/frontend/#extra_module_url)
