### ISSUE TITLE
Failed to load SourceMap: ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by chemelli74** [home-assistant/frontend#6071]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Error logged while debugging with Chromium
Not sure if it's HA related or by additional custom cards.

## Expected behavior

No error

## Steps to reproduce

1. Open HA with Chromium Windows 10
2. Open browser debug (F12)

## Environment

- Home Assistant release with the issue: 0.110.3
- Last working Home Assistant release (if known):
- Browser and browser version: Chromium - Version 83.0.478.37 (Official build) (64-bit)
- Operating system: Windows 10

## State of relevant entities

```yaml
-
```

## Problem-relevant configuration

```yaml
-
```

## Javascript errors shown in your browser console/inspector

```txt
DevTools failed to load SourceMap: Could not load content for chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/sourcemaps/onloadwff.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

## Additional information

Simone

**Comment by bramkragten** [comment]
Thats seems to be an `chrome-extension`

**Comment by chemelli74** [comment]
Really sorry, today coffe is not working as it should :-(

Simone
