### ISSUE TITLE
Panoramic Picture Elements Card

### ISSUE THREAD

**Issue by mishoboss** [home-assistant/frontend#6089]
## The request

Imagine having a Panoramic Picture Elements Card the same way we have Picture Elements Card. Basically instead of background picture to have a 360 degrees background picture that users can navigate in 3D space via mouse dragging or touch swiping. All the buttons, icons and text elements of course need to move along the background picture's position. There are a lot of JS libs and frameworks that provide such functionality out of the box (e.g. https://pchen66.github.io/Panolens/#Example).

## The alternatives

There aren't any alternatives right now. It's a completely new way of representing elements on the UI.

## Additional information

Two additional features that are good to have:
1. Setting the viewport position from another element's action. Imagine a list of buttons for quick/favourite positions left or below the card. Clicking e.g. on a button named "Fireplace", the Panoramic Picture Card positions the viewport pointing directly to the fireplace.

2. Ability to change the panoramic picture depending on device states. This feature request is applicable to the regular Picture Elements Card too. The idea is simple - user prepares different pictures or 360 degree shots for different device states - one for when the ceiling light is off and another when the ceiling light is on (or shutters are down and up, you got the idea). Then the UI shows the corresponding picture depending on current states of devices defined. This feature requires a bit of thinking as some sort of simple "rules engine" would be required similar to templates (or maybe actually use templates for that?).

**Comment by bramkragten** [comment]
I would suggest implementing this as a custom card.

**Comment by mishoboss** [comment]
> I would suggest implementing this as a custom card.

It's always an option. But having it as a first citizen would be awesome. IMHO it has a huge potential.

**Comment by bramkragten** [comment]
Maybe, but still, we would like to test the water with a custom card and later adopt it in core.
