### ISSUE TITLE
Latest major UI version flickers with a big black icon on load

### ISSUE THREAD

**Issue by mishoboss** [home-assistant/frontend#6090]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

On loading the UI flickers, rendering a big black icon for a split second. 
Screen record: https://photos.app.goo.gl/S5zHWQTXnW9CxEnG9

## Expected behavior

Smooth page reveal. No flickering and jumping.

## Steps to reproduce

1. Just load or reload Lovelace UI

## Environment

- Home Assistant release with the issue: 0.110.4
- Last working Home Assistant release (if known): 0.109.x
- Browser and browser version: Chrome 83
- Operating system: MacOS / Android

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Update HACS and clear your cache.
