### ISSUE TITLE
Helpers:Not able to recover disabled helper entity

### ISSUE THREAD

**Issue by MadSnuif** [home-assistant/frontend#6092]
## The request
When you disable a Helper entity you can't recover it anymore. Since it is  also not to trace  in yaml code in the config folder it becomes a "gohst" entity.
<img width="337" alt="helpers" src="https://user-images.githubusercontent.com/50414191/83618471-c953be80-a58a-11ea-86e1-6c4177bfe957.png">

It would be nice to have a button to show dissabled Helpers, so you can re-enable these.
## The alternatives

Alternative is just using YAML in config. But then the concept of Helpers is not used at all and the neat thing is keeping the config as tidy as possible
## Additional information
None

**Comment by bramkragten** [comment]
Don't remove the issue template. Please fill it out.

**Comment by MadSnuif** [comment]
Sorry Bram, for some reason the template did not show at first. I copied one form a new issue, it came up alright now. Hope this is ok.

**Comment by bramkragten** [comment]
You copied the one for a feature request now, but ok.

Disabled entities can be found in the entities panel `/config/entities` -> click the filter top right and click `Show disabled entities`

**Comment by MadSnuif** [comment]
Great that helps Bram. Would it still not be more logical to be able to do this for Helpers directly from the /config/helpers screen? That having said it now might be feature request.
