### ISSUE TITLE
Mediaplayer card sending "media_play_pause" instead of "media_stop"

### ISSUE THREAD

**Issue by mvdwetering** [home-assistant/frontend#6097]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I am working on a mediaplayer that supports only Play and Stop as media commands, this is indicated in the supported features. The mediaplayer card renders a Play button (right arrow) when the entity is idle, and a Stop button (square) when the entity is playing. So far so good.

However when pressing the Stop button on the card the "media_play_pause" service is called instead of "media_stop". This causes the Stop command to not work.

This is the request as seen on the websocket when pressing the Stop button.
`{"type":"call_service","domain":"media_player","service":"media_play_pause","service_data":{"entity_id":"media_player.fightclub"},"id":26}`

## Expected behavior

When pressing the Stop button on the mediaplayer card the "media_stop" service is called.

## Steps to reproduce

Probably not really useful as I don't know of other media_players that only support Stop (not Pause). If needed I can build a demo mediaplayer that only has play/stop without needing the actual mediaplayer hardware.

    1. Add a mediaplayer that supports only Stop and Play (not Pause)
    2. Navigate to Lovelace
    3. Click Play, media_play service is called
    4. Wait until entity is playing
    5. Click Stop, media_play_pause is called

## Environment

- Home Assistant release with the issue: 0.110.4
- Last working Home Assistant release (if known): Don't know
- Browser and browser version: Chrome 83.0.4103.61
- Operating system: WSL2 on Windows 10 and Home Assistant on RPi3

## State of relevant entities

UI is showing OK.

## Problem-relevant configuration

Not sure what is expected.

```yaml

```

## Javascript errors shown in your browser console/inspector

No javascript errors or other errors in the HA log
```txt

```

## Additional information

None

**Comment by olalid** [comment]
The same problem is present on 0.114.4.
When using a media_player device that only supports stop service, the UI displays a stop button, but when it is pressed the following can be seen on the web socket:

'''
{"type":"call_service","domain":"media_player","service":"media_play_pause","service_data":{"entity_id":"media_player.h_hobbyrum"},"id":34}	1600375411.2567565
'''
