### ISSUE TITLE
Table column width in Dev Tools/states too small

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/frontend#6101]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
The first two columns are too small.
![Auswahl_346](https://user-images.githubusercontent.com/26381449/83735856-2b76f700-a651-11ea-9bc7-5883784fab13.png)

## Environment

- Home Assistant release with the issue: 0.111.0b0
- Last working Home Assistant release (if known): 0.110.4
- Browser and browser version: FF and Chrome
- Operating system: Ubuntu 18.04

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Can you show the row that is causing this?

**Comment by VDRainer** [comment]
Thanks for the fast response, but i have no clue what row to look for.
Do you mean rows where the attributes column is filled with a lot of text without newlines?
There are multiple of them.

**Comment by bramkragten** [comment]
I see the third column wrapping:
![image](https://user-images.githubusercontent.com/5662298/83748812-09867000-a663-11ea-86f5-0d7fca00f1d0.png)

But something in your third column is not wrapping and stretching the column. As a result the rest of the columns get smaller.

**Comment by VDRainer** [comment]
OK, found a monster input_select that is causing it. :smile: 
The text gets wrapped, but when i remove it the column widths get better.
![Auswahl_351](https://user-images.githubusercontent.com/26381449/83754938-16a85c80-a66d-11ea-914c-202c6f526580.png)
Already too small, i think.
![Auswahl_353](https://user-images.githubusercontent.com/26381449/83755226-81f22e80-a66d-11ea-9568-51b13e33d4b0.png)

**Comment by bramkragten** [comment]
I'll just give the columns a min width... 🤷‍♂️
