### ISSUE TITLE
Lovelace layout and a loading Picture_entity card

### ISSUE THREAD

**Issue by GP920** [home-assistant/frontend#6103]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

In one of my Lovelace views, I expect to see 2 near-equal height columns, but I always initially see 2 columns, the left-most extending beyond the bottom of the screen. 

I think it's got something to do with lovelace loading while the picture entity is loading/fetching (which is a .gif I fetch every 15 minutes) . 

If I move the picture entity to be the last card on the lovelace view, the layout issue doesn't happen.
And clicking "Config UI" then closing out also "fixes" it temporaily.

What I expect - see attached image "ExpectedView_afterRefresh". (Top Image)

What actually happens - see attached image "Initial_Load" (Bottom Image)

![ExpectedView_afterRefresh](https://user-images.githubusercontent.com/33605617/83785993-19e91b80-a660-11ea-810d-8a2eef2a34cd.png)

![Initial_Load](https://user-images.githubusercontent.com/33605617/83786012-21a8c000-a660-11ea-8d22-e8a1781e4b8b.png)

## Environment

i5 NUC, Ubuntu 18.04 LTS
HA 0.110.x

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by GP920** [comment]
Just upgraded to 0.111.0b1 and the issue seems to have spread to a few more of my lovelace views. (My main page went from 3 columns to 4 with no other changes except upgrading) And reloading the page or "'config ui' then close" doesn't seem to fix it this time around.

**Comment by bramkragten** [comment]
0.111 contains a bunch of fixes for card size, and should now do it more correctly.


I see glance cards are not correct, corrected that in https://github.com/home-assistant/frontend/pull/6109

**Comment by GP920** [comment]
Great! Thanks!
