### ISSUE TITLE
Developer Tools - States: columns not wide enough

### ISSUE THREAD

**Issue by bouwew** [home-assistant/frontend#6113]
## The problem

![image](https://user-images.githubusercontent.com/11290930/83950722-30909d80-a82d-11ea-9528-5e1c61c31a37.png)

## Environment

- Home Assistant release with the issue: 0.111.0b2
- Last working Home Assistant release (if known): 0.110.4
- Browser and browser version: Chromium Version 80.0.3987.162 (Developer Build) built on Debian 10.3, running on Debian 10.2 (64-bit)
- Operating system: Linux Mint Debbie 4

**Comment by bramkragten** [comment]
Duplicate and fixed

**Comment by bouwew** [comment]
@bramkragten It is better, but still not great:
![image](https://user-images.githubusercontent.com/11290930/84114418-9b5bf780-aa2c-11ea-9e0a-748ceeedf1cd.png)

Plenty of space left for a (much) wider first column.

**Comment by bramkragten** [comment]
It was changed because the first 2 columns where to big...

**Comment by bouwew** [comment]
Can the column-width be made adaptable to both contents and available space? That would give the best result I think.

**Comment by bramkragten** [comment]
Sure it could, just add a media query for the `min-width`. Can you create a PR for that?

**Comment by bouwew** [comment]
Sorry, I would like to,  but I have no clue what you are talking about :)
I've just become somewhat familiar with creating code for components/integrations, I have no idea (yet) about frontend-related stuff.
