### ISSUE TITLE
Add reload to relevant Configuration Dashboard screens

### ISSUE THREAD

**Issue by alandtse** [home-assistant/frontend#6118]
## The request

Under Configuration, the Dashboard pickers for automations/scripts should include a relevant reload button. For example, for in the scripts picker, users who are modifying the yaml files to reload and then potentially execute the scripts without excessive clicks. This probably makes sense near the top of the page so it doesn't scroll off.

## The alternatives

The current alternative is to toggle between the Configuration Dashboard picker screen and the Reload panel in the Server Controls which is multiple clicks.

**Comment by bramkragten** [comment]
(I believe this is a duplicate, but can't find it)

The reload function is just for scripts/automations defined in YAML. It will be confusing for users that use the UI to define their scripts/automations.
