### ISSUE TITLE
Please make ZHA config flow translatable

### ISSUE THREAD

**Issue by Hedda** [home-assistant/frontend#6121]
## The request

Similar to #3847 requesting all text in the Home Assistant UI to be translatable and translated.

The full ZHA config flow is not yet translated since implemented new options in https://github.com/home-assistant/core/pull/35397

Currently user gets to pick a "radio type" to be used for ZHA, then present a more descriptive Radio Type names for user to select from:

![](https://user-images.githubusercontent.com/5826160/81454340-f662ac00-9159-11ea-8650-d6e6b5d89740.png)

This text is hardcoded in source code ( core/homeassistant/components/zha/core/const.py )

- https://github.com/home-assistant/core/blob/dev/homeassistant/components/zha/core/const.py

## The alternatives

No other alternatives than to leave it hardcoded in the source code.

## Additional information

This part why this was submitted to core https://github.com/home-assistant/core/pull/35607

**Comment by zsarnett** [comment]
This should be a backend request
