### ISSUE TITLE
Message malformed: Cannot use action for tado Smart AC control V3+

### ISSUE THREAD

**Issue by fubar-coder** [home-assistant/frontend#6125]
## Checklist

- [X] I have updated to the latest available Home Assistant version (0.110.6)
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I cannot change the `tado Smart AC Control` device to `away`. I get the error message `Message malformed: not a valid value for dictionary value @ data['type']`.

## Expected behavior

Works without error.

## Steps to reproduce

I use the tado Smart AC Control V3+.

This is the configuration:

![Tado Automation Error](https://user-images.githubusercontent.com/4739844/84124492-95b9de00-aa3b-11ea-8c5d-9d4e694482a7.png)

The preset mode should be set to `away`, as I first chose `home` and then `away` in the drop-down box.

## Environment

  | armv7l
-- | --
dev | false
docker | false
hassio | false
installation_type | Home Assistant Core in a Python Virtual Environment
os_name | Linux
os_version | 4.19.97-v7+
python_version | 3.7.3
timezone | Europe/Berlin
version | 0.110.6
virtualenv | true

- Home Assistant release with the issue: 0.110.6
- Browser and browser version:
  - Chrome 83.0.4103.97 (Windows)
  - Firefox 77.0.1 (Windows)
- Operating system:
  - Home Assistant Server OS: Raspbian GNU/Linux 10 (buster)
  - Client OS: Windows 10 2004 (Build 19041.264)

## State of relevant entities

Entity | State | Attribute
-- | -- | --
sensor.marks_zuhause_tado_bridge_status | True | friendly_name: Marks Zuhause tado bridge status
sensor.wohnzimmer_tado_mode | AWAY | friendly_name: Klimagerät-Steuerung tado mode

## Javascript errors shown in your browser console/inspector

```txt
uncaught exception: Object
```

**Comment by bramkragten** [comment]
Is the `preset_mode` dropdown empty or why doesn't it have a value?

**Comment by jking95** [comment]
🖕

**Comment by fubar-coder** [comment]
It has 2 values: `home` and `away`. Selecting either one doesn't show the value in the control.

**Comment by bramkragten** [comment]
Please provide the stack trace for the error in the console.

**Comment by fubar-coder** [comment]
This problem doesn't produce a stack trace in `home-assistant.log`. Is there another place I can find it? Do I have to change a configuration setting?

Here's the HTTP request sent to the server:

```json
{
   "alias":"Neue Automatisierung",
   "description":"",
   "trigger":[
      {
         "platform":"zone",
         "entity_id":"person.mark_junker",
         "zone":"zone.home",
         "event":"leave"
      }
   ],
   "condition":[

   ],
   "action":[
      {
         "device_id":"9e77e7d5b3f84599a1a44e6a89e952dc",
         "domain":"climate",
         "entity_id":"climate.wohnzimmer",
         "type":"set_preset_mode"
      }
   ]
}
```

It seems that it just doesn't send the `home` or `away` value.

**Comment by bramkragten** [comment]
Check your browser console

**Comment by fubar-coder** [comment]
Firefox just shows`uncaught exception: Object`.

Chrome shows this:

```text
typography.js:181 POST http://REDACTED/api/config/automation/config/1592041851535 400 (Bad Request)
  n @ typography.js:181
  o @ typography.js:181
  callApi @ mwc-ripple-base.ts:203
  value @ ha-automation-editor.ts:46
  handleEvent @ bootstrap:2
  __boundHandleEvent @ bootstrap:2
new:1 Uncaught (in promise) {error: "Response error: 400", status_code: 400, body: {…}}
  Promise.then (async)
  value @ ha-automation-editor.ts:46
  handleEvent @ bootstrap:2
  __boundHandleEvent @ bootstrap:2
```

The `body` contains:

```text
message: "Message malformed: not a valid value for dictionary value @ data['type']"
__proto__: Objecterror: "Response error: 400"
status_code: 400__proto__: Object
```

**Comment by fubar-coder** [comment]
Closing this, because it works in 111.4
