### ISSUE TITLE
History Graphs not updating after Configure UI unless page is refreshed

### ISSUE THREAD

**Issue by theOzzieRat** [home-assistant/frontend#6135]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I have been having a weird issue where the all history graphs appear to randomly stop refreshing until a page refresh is done, after which they then work again. I have narrowed it down though. The history graphs stop refreshing if I go into Configure UI, once in there they no longer refresh (which is fine), but once you exit the configuration (even if you make no changes) the history graphs will not update until you do a browser refresh. My guess is that going into the Configure UI clears some timers/intervals and they don't get re-enabled when you exit the configuration.

## Expected behavior

I would expect that once you exit the Configure UI option that history graphs would update at the specified refresh interval.

## Steps to reproduce

1. Have a card that contains a History Graph with a refresh interval set
2. Go into Configure UI
3. Exit Configure UI
4. Wait for the History Graph to refresh (it won't do this)
5. Refresh the page and the History Graph will start refreshing again

## Environment

- Home Assistant release with the issue: 0.110.7
- Last working Home Assistant release (if known): unknown
- Browser and browser version: Chrome - latest. also tested with Firefox - latest
- Operating system: Win10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by greberg** [comment]
I also have problem with history graph and that goes for cards as well as looking into history tab in left menu. I have checked my sql db and it records all the states and changes but it looks like it doesn't pick it up from the DB. If I use update from right top corner it start working but it still doesn't pick up history values only new updates from the sensors.

**Comment by Krocko** [comment]
I have the same problem:
![C9EE1ADA-B826-4713-B340-E04C87B6B379](https://user-images.githubusercontent.com/29394115/84592367-88d72900-ae45-11ea-9387-d23bf257689c.jpeg)
![3A2F6375-77DB-4E10-B82A-08ED00FF5818](https://user-images.githubusercontent.com/29394115/84592369-8a085600-ae45-11ea-9abc-39a2d9b35261.jpeg)

**Comment by gj52** [comment]
same in Home Assistant 0.111.2
MariaDB is working well, db templates are working
the entities are there, but without any lines

**Comment by theOzzieRat** [comment]
> same in Home Assistant 0.111.2
> MariaDB is working well, db templates are working
> the entities are there, but without any lines

I think there is now a new and improved bug. History Graphs now appear to be totally broken with 0.111.2. I also no longer have any data on the graphs!

**Comment by 03397** [comment]
This also happens when you click an entity and displays the history information about that entity.
This might be related with the frontend recent changes about not loading all the information??

**Comment by bramkragten** [comment]
Guys, you are hijacking an issue while there were already multiple issues about this, and it has been fixed already. Please check if an issue exists already and don't add a new issue to an existing one, create a new one.

**Comment by Smiggel** [comment]
> > same in Home Assistant 0.111.2
> > MariaDB is working well, db templates are working
> > the entities are there, but without any lines
> 
> I think there is now a new and improved bug. History Graphs now appear to be totally broken with 0.111.2. I also no longer have any data on the graphs!

Same here. Went back to 0.111.1 and it works fine again.

**Comment by gj52** [comment]
> Guys, you are hijacking an issue while there were already multiple issues about this, and it has been fixed already. Please check if an issue exists already and don't add a new issue to an existing one, create a new one.

Hi,  this (new) issue was OPEN and describes exact my problem. Do you want miultiple issues for the same problem? You are free to merge it ;-)
The eror comes with the update to the latest version - could not be solved.
Thanks
