### ISSUE TITLE
Refresh tokens list show empty entries

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/frontend#6146]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

In the list of refresh tokens in the user profile, all the entries appear empty showing only the delete button

![image](https://user-images.githubusercontent.com/12411302/84430568-c5c2d600-ac21-11ea-8d89-51def83d1834.png)

## Expected behavior
The list of tokens to show

## Steps to reproduce

1. Go to user profile
2. Scroll down to access tokens
3. Scroll back up and set to default theme to double check
4. Still no tokens

## Environment

- Home Assistant release with the issue: 0.111.0
- Last working Home Assistant release (if known): Unknown sorry (certainly was working a couple of 0.x.0 versions ago
- Browser and browser version: Chrome  83.0.4103.9 (Win10 and macOS) and Safari 13.1.1 15609.2.9.1.2 (macOS)
- Operating system: Windows 10 (2004) and MacOS (10.15.5 (19F101))

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by TomBrien** [comment]
All returned after rebooting HA. Do we close this or dig into why it happened at all?

**Comment by spacegaier** [comment]
Had you deleted any tokes before, so that it could be a data issue that they are only half-gone, leading to the UI attempting to display them?

Had you verified via browser tools that there is indeed no text / data in the page and not just invisible (even though setting the default theme as you did should ensure that already)?

**Comment by TomBrien** [comment]
I had not removed any. I had however probably (can’t 100 % remember) just connect the iOS app so it’s possible the token that created did it. Yeah I check with chrome dev tools and couldn’t see any sign of text in there. I’ll see if I can reproduce with connecting the app again

**Comment by ludeeus** [comment]
A lot of changes was made for 0.115, let's close this for now and rather open a new one if you still get this after 115
