### ISSUE TITLE
0.111.0 Brother says entity doesn't exist during lovelace loading

### ISSUE THREAD

**Issue by chemelli74** [home-assistant/frontend#6150]
## The problem

With the new great loading of the lovelace, some entities report that HA is loading.
Some others, like Brother, instead report they are missing.

## Environment

- Home Assistant Core release with the issue: 0.111.0
- Last working Home Assistant Core release (if known): 
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker
- Integration causing this issue: brother
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml
configured via UI
```

## Traceback/Error logs

```txt
-
```

## Additional information

![image](https://user-images.githubusercontent.com/57354320/84492911-319b5200-aca7-11ea-82fd-87fef26729b1.png)

Simone

**Comment by chemelli74** [comment]
Any news ?

Simone

**Comment by bramkragten** [comment]
This is not entity related, do you use a custom card for the brother entities?

**Comment by chemelli74** [comment]
Yes, [bar-card](https://github.com/custom-cards/bar-card)

Simone

**Comment by bramkragten** [comment]
So you should move your issue to that repo: <https://github.com/custom-cards/bar-card/blob/master/src/bar-card.ts#L129>

**Comment by chemelli74** [comment]
Thx for the feedback.

Simone
