### ISSUE TITLE
User can delete current refresh token

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [home-assistant/frontend#6151]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

In the user profile page > refresh token section, there is one refresh token which referenced to current session, when user hover the delete icon of this session, a tooltip with "Unable to delete current refresh token" will shown, But this does not prevent the user to delete the refresh token.

## Expected behavior

May user can not delete self refresh token, or we should remove this tooltip.

## Environment

arch | x86_64
-- | --
chassis | desktop
dev | false
docker | true
hassio | true
host_os | Debian GNU/Linux 10 (buster)
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 5.5.0-0.bpo.2-amd64
python_version | 3.7.7
supervisor | 227
timezone | Asia/Tehran
version | 0.110.4
virtualenv | false

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by AmirHosseinKarimi** [comment]
Seriously? Just disable css pointer event from front-end to prevent removing current session refresh token? I think this should also implement in the core to prevent user doing this.

**Comment by bramkragten** [comment]
Well this is the frontend repo, not the core repo.
