### ISSUE TITLE
All Charts in 0.111 have a timestamp gap

### ISSUE THREAD

**Issue by DeadEnded** [home-assistant/frontend#6154]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

All charts in the front end have a ~3 hour gap.  The most recent two data points are present and correctly timestamped, and then a multiple hour gap before continuing the data points with incorrect timestamps.  It appears that that the system is moving all records before the most recent two back a few hours, meaning if you remove the gap section, the chart looks correct.  So it is not "missing" data, old records are just getting the wrong timestamp.

![image](https://user-images.githubusercontent.com/45110141/84528478-c143ff00-acad-11ea-8e2d-c5a5ea5dc746.png)

## Expected behavior

Charts appear with proper timestamps on all data points.

## Steps to reproduce

View sensor with data-points using the UI controlled overview dashboard.

## Environment

Frontend version: 20200603.2 - latest

arch | x86_64
-- | --
dev | false
docker | true
hassio | false
installation_type | Home Assistant Container
os_name | Linux
os_version | 5.4.0-33-generic
python_version | 3.7.7
timezone | America/Kentucky/Louisville
version | 0.111.1
virtualenv | false

- Home Assistant release with the issue: 0.111.0 and 0.111.1
- Last working Home Assistant release (if known): 0.110.6
- Browser and browser version: Chrome version 83.0.4103.97 (Official Build) (64-bit)
- Browser and browser version: MS Edge version 44.18362.449.0
- Browser and browser version: MS IE version 11.836.18362.0 only loaded background, couldn't test
- Operating system: Ubuntu 20.04 LTS running Docker version 19.03.11

## State of relevant entities

All entities effected

## Problem-relevant configuration

N/A

## Javascript errors shown in your browser console/inspector

None that I am aware of

**Comment by bramkragten** [comment]
@bdraco could this be related to your optimizations?

**Comment by bdraco** [comment]
Could be.  Looks like its a timezone issue.

@DeadEnded what are you using as a database backend ?

**Comment by bdraco** [comment]
Also can you try this patch https://github.com/bdraco/home-assistant/commit/eeebb9ac31da58cf1a99be5c39b3ef356d68f502

**Comment by DeadEnded** [comment]
DB is in a postgres container.
I checked the host, HA container, and postgres container using `date`.
All three reported the correct time and timezone.

I will try the patch as soon as I can.
