### ISSUE TITLE
0.111.2 breaks history graphs.

### ISSUE THREAD

**Issue by tomlut** [home-assistant/frontend#6161]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Since updating to v0.111.2 (from 0.110.7) all history graphs, including the core Lovelace card and more info pop-ups show only the current value.

My database is fine and custom-mini-graph cards display entity history correctly.

![Screenshot_2020-06-13 Overview - Home Assistant(2)](https://user-images.githubusercontent.com/10679300/84576738-7e2e7c80-add0-11ea-9f08-fe35e4f4847d.png)

## Expected behavior
History graph card to show a history of entities.

## Steps to reproduce
Click on any entity that has history data and a unit. 

## Environment

- Home Assistant release with the issue:
Home Assistant NUC image 0.111.2
- Last working Home Assistant release (if known):
0.110.7
- Browser and browser version:
Fails on the latest Firefox, Chrome, and the iOS app.
- Operating system:
Windows 10, iOS13.5.1
## State of relevant entities
N/A

```yaml

```

## Problem-relevant configuration
N/A

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
What database do you use?

**Comment by bramkragten** [comment]
CC @bdraco

**Comment by thecode** [comment]
I have the same issue, I'm using the MariaDB as an addon, manually downgraded HA to 0.111.1 and got all the sensors data back.

**Comment by tomlut** [comment]
MariaDB

**Comment by bdraco** [comment]
Setting up a mariadb server now for testing

**Comment by thecode** [comment]
can it be related to this https://github.com/home-assistant/core/pull/36746?
My system is using Asia/Jerusalem timezone (GMT+3)

**Comment by bdraco** [comment]
> can it be related to this [home-assistant/core#36746](https://github.com/home-assistant/core/pull/36746)?
> My system is using Asia/Jerusalem timezone (GMT+3)

definitely the cause of the regression

**Comment by thecode** [comment]
@tomlut you can manually downgrade to 0.111.1 by using:
`ha core update --version=0.111.1`
From the SSH / Web Terminal

**Comment by thecode** [comment]
> Please try this patch
> 
> [bdraco/home-assistant@8bcbfdc](https://github.com/bdraco/home-assistant/commit/8bcbfdc911b41a49d5e2f88f13dcedc5a47c5038)

Is there an easy way to apply it on hassio installation? 
I have a dev system with the code but I don't have the DB there.

**Comment by bdraco** [comment]
There is a bit of setup to get inside the hassio docker container:

https://developers.home-assistant.io/docs/operating-system/debugging/#home-assistant-operating-system

https://developers.home-assistant.io/docs/operating-system/debugging/#accessing-the-container-bash

**Comment by tomlut** [comment]
> @tomlut you can manually downgrade to 0.111.1 by using:
> `ha core update --version=0.111.1`
> From the SSH / Web Terminal

Thanks, but I'm already back on 0.110.7

Didn't realise 0.111.1 would work. Also have other issues with custom cards on 0.111 so am waiting for them to be fixed.

**Comment by bdraco** [comment]
I did replicate the issue and verified the patch fixes it. It would be good to get a second verification.

**Comment by tomlut** [comment]
Thanks for the fast response, I have this question too though:

> Is there an easy way to apply it on hassio installation?

**Comment by bdraco** [comment]
> Thanks for the fast response, I have this question too though:
> 
> > Is there an easy way to apply it on hassio installation?

https://github.com/home-assistant/frontend/issues/6161#issuecomment-643668078

**Comment by thecode** [comment]
I can get into the container with portainer, how do I apply the patch?

**Comment by bdraco** [comment]
> I can get into the container with portainer, how do I apply the patch?

Make a backup of `history/__init__.py` and replace it with this one https://raw.githubusercontent.com/bdraco/home-assistant/8bcbfdc911b41a49d5e2f88f13dcedc5a47c5038/homeassistant/components/history/__init__.py

**Comment by thecode** [comment]
@bdraco I have manually replaced the file on HA 0.111.2 and it solves the issue. 
I have verified that the issue exists before replacing the file and that it is fixed after.
Thanks for the effort and fast responses.

**Comment by amaiman** [comment]
Had the same issue (just upgraded to 0.111.2) and just found this issue thread.  I've manually applied the patch and the history graphs are now working properly for me, as well.

**Comment by DavidFW1960** [comment]
I can confirm it fixes it as well

**Comment by poudenes** [comment]
> > I can get into the container with portainer, how do I apply the patch?
> 
> Make a backup of `history/__init__.py` and replace it with this one https://raw.githubusercontent.com/bdraco/home-assistant/8bcbfdc911b41a49d5e2f88f13dcedc5a47c5038/homeassistant/components/history/__init__.py

Did this patch as well and history is back :) thanks

**Comment by anglrus** [comment]
Hello, sorry, where is such file for HA on docker (synology)? thank you

**Comment by thecode** [comment]
> Hello, sorry, where is such file for HA on docker (synology)? thank you

It is the same file and process for Docker, you need shell access to the docker running the home assistant container and replace the file there. 
In my opinion unless you want to check if it works for you it worth waiting for 0.111.3 or downgrade to 0.111.1.
Patch is already merged and I assume a new version will be out soon.

**Comment by arripeo** [comment]
I had the same problem, I'm using mariadb on external server, my system is hassio with Hassos on PI4 4gb 32bit version. At now I came back to 0.111.1 and everything is ok, I hope in a new patch o version 0.111.3

**Comment by VarenDerpsAround** [comment]
> > I can get into the container with portainer, how do I apply the patch?
> 
> Make a backup of `history/__init__.py` and replace it with this one https://raw.githubusercontent.com/bdraco/home-assistant/8bcbfdc911b41a49d5e2f88f13dcedc5a47c5038/homeassistant/components/history/__init__.py

I tried to find this file, had no luck. I'm running proxmox hassos, I do not see a history folder in my samba share. Why was this closed when this issue persists with no patch to the integration?

**Comment by DavidFW1960** [comment]
> Why was this closed when this issue persists with no patch to the integration?

Because there is a patch and it has been merged... it's just you don't know how to patch it.

You need to docker exec into the container:
david@debian:~$ docker exec -it homeassistant /bin/bash
Then cd to this location: 
bash-5.0# cd /usr/src/homeassistant/homeassistant/components/history
Then use vi to edit the file (which is an utter nightmare actually)
I copied the entire patch to the clipboard before editing the file and deleted the contents of the file and pasted the new file in there.

**Comment by iMiMx** [comment]
> > Why was this closed when this issue persists with no patch to the integration?
> 
> Because there is a patch and it has been merged... it's just you don't know how to patch it.
> 
> You need to docker exec into the container:
> david@debian:~$ docker exec -it homeassistant /bin/bash
> Then cd to this location:
> bash-5.0# cd /usr/src/homeassistant/homeassistant/components/history
> Then use vi to edit the file (which is an utter nightmare actually)
> I copied the entire patch to the clipboard before editing the file and deleted the contents of the file and pasted the new file in there.

Or, instead of Vi, assuming you have wget:

`wget -O __init__.py "https://raw.githubusercontent.com/bdraco/home-assistant/8bcbfdc911b41a49d5e2f88f13dcedc5a47c5038/homeassistant/components/history/__init__.py"`

**Comment by DavidFW1960** [comment]
> `wget -O __init__.py "https://raw.githubusercontent.com/bdraco/home-assistant/8bcbfdc911b41a49d5e2f88f13dcedc5a47c5038/homeassistant/components/history/__init__.py"`
> 
> Then restart Home Assistant.

That's awesome. I can't tell you how much I loathe VI
