### ISSUE TITLE
Material Design Icons out of date

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6162]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Material Design Icons version bump in Home Assistant was last done ~5 months ago by @goyney in PR https://github.com/home-assistant/frontend/pull/4764 (to v4.9.95). 

Since then v5.0.45 released with a large number of breaking changes. Understandably, it hasn't been updated yet due to this reason. But at this point it's falling quite far behind. There's a difference of at least 570+ icons by my quick count (120 renames, 450 additions). 

Most people use the search box on [materialdesignicons.com](http://materialdesignicons.com/) to find icons and expect whatever they see there to work in Home Assistant. There's also things like this [Visual Code extension](https://marketplace.visualstudio.com/items?itemName=lukas-tr.materialdesignicons-intellisense) that suggests icons after typing `mdi:` and is suggesting icons that don't work in HA (yet). A member of the community also created a cool [alternative site](https://community.home-assistant.io/t/site-to-make-it-easier-to-find-material-design-icons/203378) and this too also shows the renamed and newly added icons.

**Breaking Changes**:
The full list of breaking changes is here: https://github.com/Templarian/MaterialDesign/issues/4901 and on the [MDI Changelog](https://dev.materialdesignicons.com/changelog) and [Upgrade Guide](https://dev.materialdesignicons.com/upgrade).

Here's a small sample showing some of the most commonly used icons in Home Assistant. I think that almost every Home Assistant user will have at least one of these icons used in their setup:

| **Icon**                                     | **Old Name**   | **New Name**        |
|----------------------------------------------|----------------|---------------------|
| ![image](https://i.imgur.com/nxFPo1Q.png)    | `mdi:hotel`    | `mdi:bed`           |
| ![settings](https://i.imgur.com/cXP96iN.png) | `mdi:settings` | `mdi:cog`           |
| ![timer](https://i.imgur.com/LUn4fPr.png)    | `mdi:timer`    | `mdi:timer-outline` |

I had seen a suggestion to remap the icon names in the past, but even if such a thing is done it would only lessen the impact (albeit significantly) of this breaking change, not eliminate it entirely. It wouldn't be possible to remap the ~75 or so brand icons that got removed. 

This was not intended to rush anything along, just wanted there to be a detailed issue for this so that users can be easily linked to an explanation for the delay. Though if there's ever a good time to put out a breaking change like this, it's probably during quarantine when everyone's at home to fix it 😄 

## Expected behavior

Icon selection and names in Home Assistant should ideally be consistent with what users see on the [materialdesignicons.com](http://materialdesignicons.com/) website and other sources.

## Environment

- Home Assistant release with the issue: all
- Last working Home Assistant release (if known): n/a
- Browser and browser version: n/a
- Operating system: n/a

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by goyney** [comment]
This is a duplicate of #5094.

**Comment by SeanPM5** [comment]
Ah thanks, missed that issue.
