### ISSUE TITLE
hui-weather-forecast-card: TypeError: o.setConfig is not a function

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#6169]
## The problem

Inspector showing this error:

<img width="721" alt="Schermafbeelding 2020-06-14 om 23 39 17" src="https://user-images.githubusercontent.com/33354141/84604719-48ed6180-ae98-11ea-9f7d-001efb0b3a75.png">

## Environment

- Home Assistant Core release with the issue:  0.111.2
- Last working Home Assistant Core release (if known):  not sure
- Operating environment (Home Assistant/Supervised/Docker/venv):  Home Assistant
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information

though most of the time inspector errors arise on a separate view, this errors show even when not a single forecast card is currently displayed. Not sure what yaml to post because of that.

Seems to happen in Safari/Mac, dont see it in Chrome

**Comment by bramkragten** [comment]
I guess this is some custom thing, can you try disabling all custom?

**Comment by Mariusthvdb** [comment]
isn't this the core [weather-forecast](https://www.home-assistant.io/lovelace/weather-forecast/) card ?

I am not aware of any custom card with this name, nor am I using this in eg an entities card, with the prefix `hui:` and suffix `-card`  or as `hui_element:` at all...

only using this card like:

```
  - type: weather-forecast
    entity: weather.openweathermap
```

the 2 other weather integrations in my setup: dark_sky and buienradar

still, today I havent seen this anymore, without changing anything to these cards/configs. Maybe it was a cache thing, that got cleaned up during several restarts.

let me please check this for another day or so, and Ill close if not re-appearing?

**Comment by bramkragten** [comment]
I highly doubt that stack trace is correct. Click the filename top right and see where it takes you.

**Comment by Mariusthvdb** [comment]
got it back again, on a page with a the same error, but in a markdown card:

<img width="1346" alt="Schermafbeelding 2020-06-16 om 12 21 15" src="https://user-images.githubusercontent.com/33354141/84763296-42f89d00-afcc-11ea-9502-cda1e6367ef2.png">


<img width="293" alt="Schermafbeelding 2020-06-16 om 12 22 20" src="https://user-images.githubusercontent.com/33354141/84763315-4ab84180-afcc-11ea-95f3-d89d9d765fd1.png">

clicking that takes to:

<img width="387" alt="Schermafbeelding 2020-06-16 om 12 23 08" src="https://user-images.githubusercontent.com/33354141/84763351-560b6d00-afcc-11ea-863a-8d9b41ba7ad1.png">

**Comment by bramkragten** [comment]
Seems like it is `hui-element.js`

**Comment by Mariusthvdb** [comment]
ok, Ill ask Thomas about this then. Puzzling thing is the relation with the hue-weather-forecast-card though. Would you have any lead on how that could be originated?

**Comment by bramkragten** [comment]
We made some changes to source mapping that might cause to not always be right, not sure.
