### ISSUE TITLE
0.111.2 [Bug] Markdown code style 

### ISSUE THREAD

**Issue by sstefanowski** [home-assistant/frontend#6175]
Hello,
After installing latest HA 0.111.2 the background color for markdown style "Code block" (initialized with three chars ''') is always in the white... making some skins totally unreadable... It would be much better if this default is default-color-of-the-card-in-theme. It wouldn't force many themes to be updated.

Regards,

Examples below:
![image](https://user-images.githubusercontent.com/36473471/84719129-cf7a6f80-af7a-11ea-9241-9fcc7604aef5.png)
![markdown_issue1](https://user-images.githubusercontent.com/36473471/84719757-77446d00-af7c-11ea-98f8-eebc715fa73c.png)

**Comment by ludeeus** [comment]
Use `markdown-code-background-color` in your theme to set that.
