### ISSUE TITLE
Script organisation in UI 

### ISSUE THREAD

**Issue by iainp999** [home-assistant/frontend#6183]
## The request

The number of scripts I have is growing. They each have distinct categories related to what they do, and on the filesystem I create distinct folders to reflect this e.g. scripts related to lighting go into the 'lights' folder.

It would be really nice if there were some way to organise scripts in a similar fashion in the UI, and, for example, being to use rollups to show/hide scripts in a certain category.

I guess this could also be extended to other areas, such as automations.

## The alternatives

Tabs could be one other way to organise.

## Additional information

I'm not familiar with the code, but perhaps there is also some backend work that would need to be done around this.

**Comment by mrand** [comment]
@iainp999 if someone added meta tags (ideally with sorting and/or filtering), I assume that would solve what you're talking about?  Then they could even be "shared" across categories, if there were situations where it made sense to do so.

**Comment by iainp999** [comment]
@mrand sure, I think that would be a great way to achieve it.

**Comment by hhandersson** [comment]
> @iainp999 if someone added meta tags (ideally with sorting and/or filtering), I assume that would solve what you're talking about? Then they could even be "shared" across categories, if there were situations where it made sense to do so.

If the same tags could be used also in the automation section, that would be great, since my automations are starting to grow as well.

**Comment by mrand** [comment]
Taking this one step further: tags could eventually be used for more than just organizing, they could also be used for control.  A simplistic example: a toggle switch for "guest" mode which disables all automations tagged with "away"

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/issues/4542
