### ISSUE TITLE
Sidebar icons added by integrations start out blank

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/frontend#6187]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Integrations such as HACS add a sidebar icon for users to access them, and as of HA 0.111.x, that icon is often just a blank space after restarting HA.  I understand that 0.111.x displays the frontend very quickly, and before the rest of HA (including integrations) has loaded, but I think there needs to be care taken to ensure that UI elements added by integrations are displayed properly.  Sometimes it's possible for users to fix the problem by refreshing the browser, but even that's not enough on the iOS app or browser.  I just installed 0.111.4 and my HACS icon is still missing on the iOS app even after repeatedly refreshing the view by pulling down from the top of the screen.

Ludeeus points to this optimization as the culprit and recommends that users take the manual step of manually refreshing their browser to get the new UI elements to show up, but that's insufficient on some platforms and shouldn't be necessary.  It looks broken, and I expect that most folks who see this will think it's broken.

https://github.com/hacs/integration/issues/1336

<img width="920" alt="Screen Shot 2020-06-14 at 4 17 16 PM" src="https://user-images.githubusercontent.com/860888/84971167-04003f80-b0d1-11ea-9692-5a3667af5397.png">

## Expected behavior

Sidebar icons added by third-party integrations should be visible after restarting Home Assistant and shouldn't require the user to manually refresh the browser or clear the cache first.  Perhaps once HA as finished loading, the frontend could be refreshed to include anything that was added later, either automatically or via an automation triggered by an event indicating that HA is done loading.

## Steps to reproduce

Install a third-party component, such as HACS, that adds a sidebar icon.  Observe that more often than not, the space where the new icon should be is blank.  See screenshot above.

## Environment

- Home Assistant release with the issue: 0.111.4
- Last working Home Assistant release (if known): None
- Browser and browser version: Chrome 83, Safari on iOS 13.5.1
- Operating system: MacOS, Windows 10, iOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

Simply having HACS installed is enough.

```yaml

```

## Javascript errors shown in your browser console/inspector

<img width="1670" alt="Screen Shot 2020-06-14 at 4 17 36 PM" src="https://user-images.githubusercontent.com/860888/84971330-53df0680-b0d1-11ea-9cc7-e03f418238f3.png">

```txt

```

**Comment by bramkragten** [comment]
This is a timing thing, HACS should register its icon before adding itself to the sidebar.

**Comment by rccoleman** [comment]
Thanks, Bram.  I'll relay that back.

**Comment by bramkragten** [comment]
@ludeeus and I talked about it and we found out what is going on. This is only happening when you would load/reload the webpage when the frontend is loaded but HACS isn't yet?

So when you load the webpage during startup?

**Comment by rccoleman** [comment]
No, it often persists for a while after HA is fully started, and gets into a state in the iOS app where no refreshing, clearing the frontend cache, or killing and restarting the app makes the icon appear.  I'm only surmising that it's related to restarting HA, but I'm not sure that has anything to do with it anymore.  I'm really not trying to break it or catch it failing during startup - this just happens when HA has been up for a while (days sometimes) and is in a steady state.  My current instance has been running for 2 days now.

I was just using the iOS app on my phone and the icon was there, and I pulled down from the top of the screen to refresh and the icon is now missing.  It's also missing from my desktop view on my Macbook Pro right now.  I know it was showing up properly last night on both.

It's difficult to get console logs on my phone, so I'm relying on my desktop for that.  I'm getting the exact same messages as above right now.
