### ISSUE TITLE
Logbook and History times on iOS are incorrect

### ISSUE THREAD

**Issue by nukefrenzy** [home-assistant/frontend#6190]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
Logbook and History event times on my iOS device do not match the times shown on my PCs.  They are consistently 5 hours in the future from when the even actually happened.  I logged into HA on the iOS app and via Safari, but both show incorrect times.  The browser on my home PC shows the correct times.  All devices are connected to the same wifi network.

## Expected behavior
All methods of accessing HA should show the same timestamps on events.

## Steps to reproduce
Log items to the standard HA database and view the logbook or history tabs on an iOS device and a separate non-iOS device.

## Environment
Running HA 0.111.4 on an RPi3b+ on HassOS 4.10.  Time zone set to America/Chicago, which matches where all of the devices are located.  No VPN or other apps running on the phone that could cause location/timezone issues.

- Home Assistant release with the issue: 0.111.4
- Last working Home Assistant release (if known): Unknown
- Browser and browser version: iOS app 2020.2 (5), Safari on iOS 13.5.1, Firefox 77.0.1 on Win10
- Operating system: 

## State of relevant entities
Entities states are shown correctly, only timestamps are incorrect.

## Problem-relevant configuration
The configuration of HA does not cause issues on my PCs so I'm not sure what configuration to show here.  I will respond with configuration info if requested.

## Javascript errors shown in your browser console/inspector
None

**Comment by nukefrenzy** [comment]
![Photo Jun 18, 7 56 12 AM](https://user-images.githubusercontent.com/36387475/85031524-65152b00-b144-11ea-8c7b-cee7b72da456.png)
![Photo Jun 18, 8 15 30 AM](https://user-images.githubusercontent.com/36387475/85031783-b3c2c500-b144-11ea-98e1-bac2c41ce39c.png)
![Annotation 2020-06-18 075653](https://user-images.githubusercontent.com/36387475/85031802-b9b8a600-b144-11ea-89f1-8836075786ea.png)

**Comment by bdraco** [comment]
Likely fixed in 0.112 by https://github.com/home-assistant/frontend/pull/6192
