### ISSUE TITLE
Scripts in UI are not shown by their name, making use of them difficult

### ISSUE THREAD

**Issue by JesseCake** [home-assistant/frontend#6194]
## The request

I've been building a whole bunch of scripts via the UI for specific functions to use as building blocks when building automations, however, when I go to use them using the UI by "call service" they're not labelled by name, but by the system generated serial.

This makes it incredibly difficult to use them, as I'm having to keep a separate log of serial vs name so I can find the correct serial for the script I'm trying to call.

The "Call Service" and any other UI element that calls scripts, should map the serials to names when presenting selections to the user, making it easy to pick and choose scripts.

## The alternatives

The only way I've been able to navigate this is to keep a sheet of paper on my desk mapping the serials to names.

**Comment by bramkragten** [comment]
The plan is to make the `entity_id` configurable.

**Comment by zsarnett** [comment]
This is done
