### ISSUE TITLE
Google Calendar Panel - events not displayed in week/month view

### ISSUE THREAD

**Issue by DaveR66** [home-assistant/frontend#6210]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

I have a Calendar in Google where all events are correctly shown in Day view on the Calendar integration screen, but some events don't appear in either the week view or the month view. It appears random, so at the moment I don't see any future events for the next few days, but if I scroll to July then the week/month views are correctly populated. 
This is made more bizarre by the fact June's month view displays 29th June as empty, but if I scroll to the July view, it shows 29th June's events.

I've attached files showing an event on the 23rd in day view but then nothing in week/month

![day](https://user-images.githubusercontent.com/65860011/85334935-0b11be00-b4d4-11ea-8fb9-0c9009f6239d.jpg)
![month](https://user-images.githubusercontent.com/65860011/85334938-0d741800-b4d4-11ea-8c3b-6be888573fdb.jpg)
![week](https://user-images.githubusercontent.com/65860011/85334947-1238cc00-b4d4-11ea-9804-e6d15c4aab59.jpg)

## Expected behavior
All events shown in day view should be seen in all views.

## Environment

- Home Assistant release with the issue: Home Assistant 0.111.4  
- Last working Home Assistant release (if known): Has been all released since I install HA  0.110 onwards
- Browser and browser version: Any browser. Have tried Chrome 83.0.4103.106 , FF 77.0.1
- Operating system: Raspbian Buster

Had to scrub some of the info, I'm wondering if it's the length or some of the characters in the Teams links that's overflowing a buffer? I can provide the full info privately if that helps diagnose,

message: 'Work:K*** T*********- St. M*** ************ Call'
all_day: false
start_time: '2020-06-23 14:00:00'
end_time: '2020-06-23 15:00:00'
location: Microsoft Teams Meeting
description: >-
  Hi all, 

  Please find the invite for our meeting next Tuesday 23/06/2020.

  Kind regards, 

  **********

  ________________________________________________________________________________

  Join Microsoft Teams Meeting

  [https://teams.microsoft.com/l/meetup-join/19%3ameeting_******************************************************%40thread.v2/0?context=%7b%22Tid%22%3a%22683bfafa-12ed-49b9-a787-***********2%2c%22Oid%22%3a%********-73f3-498b-ae60-************%22%7d] 
   

  Learn more about Teams [https://aka.ms/JoinTeamsMeeting] |Meeting options

  [https://teams.microsoft.com/meetingOptions/?organizerId=*********-73f3-498b-ae60-7f483613ce4e&tenantId=*******-12ed-49b9-a787-**********&threadId=19_meeting_************************************************@thread.v2&messageId=0&language=en-US]

  ________________________________________________________________________________

  -------

  Copied from your Office 365 calendar
  (AAMkAGVjYzIwM2U****MzNWYtNDN********************************xa5c0opRJHffd2skGAGBwAzBm4ntDy-************************************************************=)

  Master Event ()

  Check out how template works and limitations: https://aka.ms/flowcalendar
offset_reached: false
friendly_name: work

```yaml

```

## Problem-relevant configuration

- cal_id: 123456yuiyiuyiuyuyiu@group.calendar.google.com
  entities:
  - device_id: work
    ignore_availability: true
    name: work
    track: true

```

## Javascript errors shown in your browser console/inspector

<!--
  If you come across any javascript or other error logs, e.g., in your browser
  console/inspector please provide them.
-->
```

## Additional information
No errors shown in console

**Comment by DaveR66** [comment]
Ok, seems that the documentation is unclear, it's not a code bug (it's been driving me crazy).
 
The docs read:
max_results (integer)(Optional)
Max number of entries to retrieve
Default value:5

Retrieve should be "Display". 

The entries were there but not _displayed_ in week/month view. Sometimes I could see them momentarily be visible and then disappear. That's what was throwing me.
Change the parameter to 20 and they can all be seen now.

**Comment by ramoneich** [comment]
Tank you!!! Took me all day to get it working. It was very strange because on my other ha-instance it is working correctly due to the **max_results: 21 entry in the google_calendars.yaml** - I have just overlooked it!
Thanks! @DaveR66
