### ISSUE TITLE
0.112 Android app not reconnecting

### ISSUE THREAD

**Issue by larena1** [home-assistant/frontend#6227]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When the app was in background for a while, it will not reconnect. It says it's reconnecting but will only after force closing the app. 

Might be related to the newly introduced feature which is supposed to freeze the connection after 5 min. 

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by JBassett** [comment]
I am also seeing this behavior on desktop browsers.  Leaving home assistant in a background tab for more than 5 minutes leaves the reconnecting toast up permanently until I refresh.

**Comment by balloob** [comment]
I did some fixes in b1, could you try again ?

**Comment by JBassett** [comment]
Still having issues, this is what I got after putting app in background and reopening:
![Screenshot_20200626-141242](https://user-images.githubusercontent.com/1051414/85888903-77344080-b7b8-11ea-9caa-3df925c0ee01.png)

After trying to swipe around randomly I got this:
![Screenshot_20200626-141431](https://user-images.githubusercontent.com/1051414/85888992-a480ee80-b7b8-11ea-885e-9bf97437ca05.png)

However the UI never actually updated any values and toggles were not working.  Assuming the websocket never reconnected.

**Comment by larena1** [comment]
Not fixed here either. Never had any issues with Firefox @ Win10 though as @JBassett mentioned issues on desktop.

**Comment by balloob** [comment]
I was able to reproduce it locally on a Google Pixel. 

I run the beta build but the debugger didn't show up in `chrome://inspect`. It is enabled for `dev` here:

https://github.com/home-assistant/android/blob/73a0934de3412ee8af332fc781ba19f4d8f5e9f5/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L96-L98

@JBassett do you know if that flag is enabled for beta play store builds ?

**Comment by JBassett** [comment]
@balloob right now it's only enabled for local builds, not beta or production.

**Comment by balloob** [comment]
Okay, so I don't have a dev env set up. Would you be able to link me a local dev build?

**Comment by JBassett** [comment]
This is a local build that will install beside the beta, it's not signed by the beta or prod account so no push notifications but it will have the dev tools accessible.  Was too large for discord and github doesn't like the apk.

https://drive.google.com/file/d/1cipUPY-kliZoxpjfhYYqlegcZubjyYBs/view?usp=sharing

**Comment by balloob** [comment]
Been debugging. Two things happen:

- `setTimeout` are only executed when the page is visible again. The connection was never disconnected while the app was in the background.
- `visibilitychange` event is not fired for when document is shown

**Comment by bramkragten** [comment]
This should be fixed in beta 3
