### ISSUE TITLE
0.112 Reloading Lovelace yaml disfunctional 

### ISSUE THREAD

**Issue by larena1** [home-assistant/frontend#6228]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Using the 3 dots menu, it was possible to reload the Lovelace yaml files. It won't do anything anymore. 

I've split the Lovelace yaml into several files and include them, in case that matters. Was working fine before 0.112

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by SeanPM5** [comment]
Are you using Custom Header? 

If so, can you try adding `?disable_ch` to the end of the URL and see if that allows you to use the menu items in there? That fixed this problem for me.

I've opened an issue for it here https://github.com/maykar/custom-header/issues/232

**Comment by maykar** [comment]
Latest release (1.6.4) should fix the issue
