### ISSUE TITLE
Card Picker dialog height small on 0.112.0b0

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6231]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The card picker on 0.112.0b0 appears to be set at a fixed height now or something, it is only showing one row of three cards.

This means a lot more scrolling.

![image](https://i.imgur.com/PJXEqb8.jpg)

0.111.4 for reference, it showed four times as many cards in the same size browser window.

![image](https://i.imgur.com/TztpxYz.png)

This may have been intentional, but if so, perhaps we can find a better middle ground? I think at least one more row (six cards) would be nice.

## Expected behavior

Make better use of the available screen real estate in browser

## Steps to reproduce

1. Enter Configure UI mode.
2. Click FAB to add a new card

## Environment

- Home Assistant release with the issue: 0.112.0b0
- Last working Home Assistant release (if known): 0.111.4
- Browser and browser version: Chrome stable
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
It should only set the fixed height when you start searching... Will look at it when I get back

**Comment by balloob** [comment]
It's not actually because of the fixed height PR. I tried looking into it but I am not familiar enough with mdc-dialog. I tried to set `--mdc-dialog-max-height: 100vh` but it didn't increase the size. Leaving this one for you Bram :)
