### ISSUE TITLE
Cosmetic issue on toggles when editing dashboards 0.112.0b0

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6234]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Perhaps related to https://github.com/home-assistant/frontend/issues/6233 but this is a bit different so opened a new issue just to be safe.

Prior to this version the toggle switches would appear on different lines, this is no longer the case. They're showing on the same line now, which might be intentional, but I think at the very least it needs some spacing between. 

![image](https://i.imgur.com/T8EZVN2.jpg)

## Steps to reproduce

1. Go to Configuration -> Lovelace Dashboards
2. Click on a UI-controlled one to open the dialog

## Environment

- Home Assistant release with the issue: 0.112.0b0
- Last working Home Assistant release (if known): 0.111.4
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by balloob** [comment]
Looking into this, it looks like mwc-formfield has changed it's display setting to `inline-flex`. Will find all places where use it and check it .
