### ISSUE TITLE
Code Mirror being 'weird' when editing cards

### ISSUE THREAD

**Issue by firstof9** [home-assistant/frontend#6249]
## The problem

Code Mirror is acting strange when attempting to modify existing cards in the frontend.

## Environment

- Home Assistant Core release with the issue: 0.112b1
- Last working Home Assistant Core release (if known): 0.111.4
- Operating environment (OS/Container/Supervised/Core): Container
- Integration causing this issue: n/a
- Link to integration documentation on our website: n/a

## Problem-relevant `configuration.yaml`

```
n/a
```

## Traceback/Error logs

```
n/a
```

## Additional information

Screenshot of 'Select All'
![image](https://user-images.githubusercontent.com/1105672/85877887-b2207f00-b78c-11ea-9501-ff5baca8057a.png)
![image](https://user-images.githubusercontent.com/1105672/85877927-c2385e80-b78c-11ea-944e-3add5d1e97a4.png)

**Comment by gadgetchnnel** [comment]
This is still happening for me in 0.112 and frontend version 20200701.0, although switching to the visual editor and back to the code editor (or typing something a deleting it) usually fixes it.

**Comment by bramkragten** [comment]
Is that just for a stack card/conditional card? Or what is the context?

**Comment by gadgetchnnel** [comment]
I'm seeing it with stack cards which contain cards which either don't support the visual editor or are using options not supported in the editor. This is an example which demonstrates it for me:

```
type: vertical-stack
cards:
  - type: entities
    title: My Title
    entities:
      - light.light
      - light.bedroom_lights
      - light.computer_room_light
    style: |
      ha-card {
        background-color: red!important;
      }
  - type: entities
    title: My Title
    entities:
      - light.light
      - light.bedroom_lights
      - light.computer_room_light
    style: |
      ha-card {
        background-color: red!important;
      }
```
and gives this when I use Select All:

![image](https://user-images.githubusercontent.com/2099542/86341731-99adda00-bc4e-11ea-8daa-4ce5228535c3.png)

It doesn't seem to be an issue if the cards are not in a stack.

**Comment by bramkragten** [comment]
OK, got a fix for that.
