### ISSUE TITLE
Replace no longer set google-green/google-red

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#6254]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

When we swapped out paper-spinner for mwc in #6205, we also dropped setting four style variables that we kept around to style the spinner:

```css
--google-red-500: #db4437;
--google-blue-500: #4285f4;
--google-green-500: #0f9d58;
--google-yellow-500: #f4b400;
```

The green and the red ones were actually quite widely used. We should introduce our own variables and find/replace the old references. And we should make sure the new variables will use `google-red` / `google-green` if they are defined first, to make it backwards compatible with existing themes.

**Update:** We actually already have `error-color`. We should use that one everywhere instead of google-red.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by balloob** [comment]
Idea from @thomasloven:

> We should probably have like ok-color, warning-color and info-color  too.

**Comment by balloob** [comment]
Note, bootstrap uses success-color instead of ok-color, which I like more

**Comment by thomasloven** [comment]
I was thinking of bootstrap when I suggested it, but was too lazy to look up the names...
