### ISSUE TITLE
Restore focus when panel reconnected

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#6255]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

We don't restore focus when we reconnect the panel after a tab stops being idle.

We should store the focused element (`document.activeElement`) and call `.focus()` on it after we reconnect the panel.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
This will be a pain with `shadowRoot`, `document.activeElement` will always return `home-assistant`...
