### ISSUE TITLE
hui-plant-status-card error without any reason... on each view

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#6262]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

Below error is displayed on each view in my setup. Without any pointer to a plant-status-card whatsoever in the config

On all views, this error about the 
## Environment

- Home Assistant release with the issue: 0.111.4
- Last working Home Assistant release (if known): hasn't happened before
- Browser and browser version: Safari and Chrome
- Operating system: MacOS

## State of relevant entities
No relevant entities

```yaml

```

## Problem-relevant configuration

No clue. I dont even have plant-cards in my config, nor any hardware requiring that.
```yaml

```

## Javascript errors shown in your browser console/inspector

<img width="773" alt="Schermafbeelding 2020-06-27 om 23 37 24" src="https://user-images.githubusercontent.com/33354141/85932763-4e529f00-b8cf-11ea-9cf2-ae224caa1a54.png">

## Additional information

this seems to have correlated with updating both custom cards hui-element and card-tools. No reference to these cards is displayed however, so it should be a core issue?

made related to: https://github.com/home-assistant/frontend/issues/6261 ? also on the hui-weather-forecast-card

**Comment by bramkragten** [comment]
It is the card picker, is fixes in 0.112

**Comment by Mariusthvdb** [comment]
is this the card picker too:

<img width="798" alt="Schermafbeelding 2020-06-29 om 13 25 34" src="https://user-images.githubusercontent.com/33354141/85999243-1bfa8c00-ba0c-11ea-8c72-de5d9352a7b5.png">

**Comment by bramkragten** [comment]
Thats `card-tools`
