### ISSUE TITLE
Firefox For Android Constantly requests vibration permission when toggling entities

### ISSUE THREAD

**Issue by smwa** [home-assistant/frontend#6264]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
When toggling lights or others switches in the UI panels, Firefox for Android requests for permission to vibrate the device. Despite approving it, the next time the web browser restarts, it requests access again when toggling lights.
![Screenshot_20200627-172021](https://user-images.githubusercontent.com/4969375/85933281-fbf78b00-b89a-11ea-81db-0ac44b0b9ead.png)

## Expected behavior
The browser should either remember the vibration preference or not use it at all.

## Steps to reproduce
Open firefox for Android and load home assistant. Turn on a light entity. Accept the vibration request. Force close the browser. Repeat the previous steps.

## Environment
Android 10
Firefox 68.9
Home assistant 0.111.0

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by balloob** [comment]
That seems like a bug in Firefox? We don't control that.
