### ISSUE TITLE
History Graph forms a loop

### ISSUE THREAD

**Issue by Santobert** [home-assistant/frontend#6269]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
The history graph forms a loop if the value changes quickly.

The blue value was at 18 °C for a long time. Within a few seconds I've changed the value to 25 °C, to 12 °C and then to 15 °C. Now the graph forms a loop, which looks kind of weird. It seems that there is a sort of smoothing that leads to this behavior.
![image](https://user-images.githubusercontent.com/15657682/85952272-4430af00-b968-11ea-8d98-4585a9bbb58f.png)

## Environment

- Home Assistant release with the issue: 0.112.0b2
- Last working Home Assistant release (if known): Not known
- Browser and browser version: Firefox 77.0.1
- Operating system: Arch Linux

## State of relevant entities

![image](https://user-images.githubusercontent.com/15657682/85952372-2879d880-b969-11ea-90f7-f50593453df1.png)

**Comment by bramkragten** [comment]
This is not specific to 0.112.0 right?

**Comment by bdraco** [comment]
@Santobert Which database backend do you use?

**Comment by Santobert** [comment]
> @Santobert Which database backend do you use?

The internal sqlite backend

**Comment by bdraco** [comment]
Is it just the single graph that is affected, or all of them?

**Comment by Santobert** [comment]
I cannot say this for sure, since I can't manipulate the other values. But the all values seem to be correct when I hover over them. It's just the representation that is wrong, I guess.

**Comment by bdraco** [comment]
If you look at your other entities, do they have a the same behavior at ~12:00

**Comment by Santobert** [comment]
I'm not sure. They have a lot more values, so it's not clearly visible.
![grafik](https://user-images.githubusercontent.com/15657682/86015694-2e7fc000-ba22-11ea-9721-f38603a86b01.png)

But I can reproduce this issue with the input_boolean. As you can see, the last drop (at 20:23) is not exactly straight.
![grafik](https://user-images.githubusercontent.com/15657682/86015869-68e95d00-ba22-11ea-9338-fa8e1d3c462f.png)

**Comment by Santobert** [comment]
Tp be honest, I don't think they are affected.

![grafik](https://user-images.githubusercontent.com/15657682/86016114-b36ad980-ba22-11ea-93e3-e672dfcf4f6c.png)

![grafik](https://user-images.githubusercontent.com/15657682/86016168-c2ea2280-ba22-11ea-8fcc-7231a5087fb1.png)

**Comment by Santobert** [comment]
All values are correct. Even though it looks otherwise.

![grafik](https://user-images.githubusercontent.com/15657682/86016465-1492ad00-ba23-11ea-8acc-98bccb1a09c9.png)
![grafik](https://user-images.githubusercontent.com/15657682/86016570-38ee8980-ba23-11ea-8dc5-97ecccd2af82.png)
![grafik](https://user-images.githubusercontent.com/15657682/86016600-486dd280-ba23-11ea-97d7-636d1c62fa5f.png)

**Comment by bdraco** [comment]
Thanks. I was worried about a regression in processing timestamps, but it doesn't appear to be the case

**Comment by Santobert** [comment]
Still relevant in 0.115.0b7

**Comment by Santobert** [comment]
Still relevant in current beta

**Comment by Santobert** [comment]
Issue persists in 2021.3.4

**Comment by bramkragten** [comment]
I wonder if this is an upstream issue of something in our code. Got an easy way to reproduce this?

**Comment by Santobert** [comment]
- Create an `input_number` entity with min 0 and max 30
- set the entity to 15
- wait some minutes
- set the slider to max, wait some seconds
- set the slider to min and wait again some seconds
- set the slider back to 15 and wait some minutes
- create a history graph with very limited `hours_to_show` so that the spikes are somewhere in the middle
