### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by LAKY911** [home-assistant/frontend#6270]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Hi, in tab Integrations I have this translation error:
![image](https://user-images.githubusercontent.com/44507644/85952078-43e3e400-b967-11ea-8098-de1c2de01a77.png)

## Environment

- Home Assistant release with the issue: Home Assistant 0.111.4
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome 83.0
- Operating system: Win 10 64bit

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
You can fix translations in Lokalise <https://developers.home-assistant.io/docs/translations>

(In this case the `{integration}` variable should not be present)

**Comment by LAKY911** [comment]
> You can fix translations in Lokalise https://developers.home-assistant.io/docs/translations
> 
> (In this case the `{integration}` variable should not be present)

Hi, I cant find the this translation ("Systémové možnosti pro {integration}") in Lokalise. Where is the problem?

**Comment by bramkragten** [comment]
Then it is probably fixed by someone else already
