### ISSUE TITLE
Optimization for hui-view createColumns

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#6272]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

When we're creating the columns, we create all the cards one by one. If one card is async, we will wait for that card to finish loading before creating the next one. This means that if 2 cards require loading, we will now not start loading the 2nd card until the first card is finished loading. This causes delay.

Before we go through the loop and create cards, we should start the preloading of all cards that are code split out.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
I don't think this is true, we don't wait on the import for lazy cards, we call `createCardElement`, which will start loading all cards.

After all cards are created (not necessarily done loading), we are going to build the columns, there we wait for the loading to be finished to be able to calculate the height.

I don't think we can optimize this much more...

**Comment by balloob** [comment]
Oh you're right. I somehow thought we were still creating the cards in that segment. This is indeed already great!
