### ISSUE TITLE
Unable to authenticate to AdGuard Home in iFrame on Mobile Safari or HA Companion iOS app

### ISSUE THREAD

**Issue by raetha** [home-assistant/frontend#6280]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I use AdGuard Home and have an iFrame component enabled to have the interface inline with Home Assistant. This appears to work fine with most Windows browsers, however on iOS in either Safari or HA Companion, when selecting the iFrame tab, the login screen is presented, but rather than authenticate and login to AdGuard Home, you are continuously returned to the login screen. Going directly to the AdGuard Home page in Safari works as expected, things only fail when in the HA iFrame. It appears that HA frontend is doing something unique on iOS with Safari/Webkit.

## Expected behavior

I would expect logging in to AdGuard Home to either display a login error message if something failed, or successfully log in to the management interface when in an iFrame run in any browser, or in the mobile apps, not just desktop browsers.

## Steps to reproduce

1. Install AdGuard Home (I used docker)
2. Add iFrame configuration in HA to AdGuard Home configuration page
3. Open HA in Safari on iOS (or in HA Companion App)
4. Navigate to AdGuard Home iFrame
5. Attempt to log in to AdGuard Home
6. Screen should flicker, then refresh back to login screen

## Environment

- Home Assistant release with the issue: 0.111.4
- Last working Home Assistant release (if known):
- Browser and browser version: Mobile Safari
- Operating system: iOS 13.5.1
- AdGuard Home: 0.102.0
- HA Companion App: 2020.3 (4) Testflight

## Problem-relevant configuration

```yaml
panel_iframe:
  adguard_home:
    title: AdGuard
    icon: mdi:security-network
    url: !secret adguard_home_url
    require_admin: true
```

**Comment by bramkragten** [comment]
I don't think this is something we do, but maybe something Adguard does in the login screen?

**Comment by raetha** [comment]
I've got an issue logged with them as well, but they were leaning towards it being something with the HA frontend since their stuff works fine outside of HA iFrame, and works from a desktop browser inside the HA iFrame. So it seems like something different that is happening with the way things are working in an HA iFrame on mobile Apple devices. I'm not a web developer at all, so don't even know how you'd troubleshoot something like this, but I'm happy to help on my setup if anyone had guidance.
