### ISSUE TITLE
5 minute timeout causing issues with app and open tabs

### ISSUE THREAD

**Issue by gregg098** [home-assistant/frontend#6283]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
With 0.112.0b2 (also tried 0.113.0.dev20200628), the new 5 minute timeout seems to be causing issues. This is mainly with the mobile app, but also happens on open tabs.

Issue 1) Now, when I open the mobile app (Android, on my Samsung Galaxy S10), almost every time, it just says "Connection lost. Reconnecting..." No matter how long I stay on the page, it never actually refreshes. I have to force close the app and then re-open. I have cleared storage and started from scratch with the same issue. I am using the Nabu Casa URL for the remote address.

Issue 2) Found this while configuring some new Z wave devices over the weekend. I had about 3 tabs of Home Assistant open on my computer so I could see states, the Z wave config, and my front end. Every time the timeout occurred, it would completely reset my screen. For example, if I had a node selected on the Z wave control panel and was tinkering with a config value, the refresh would cause the screen to show as if I just navigated there (no nodes selected, etc.). I was also renaming some entities and the same thing happened. I would go back to a particular tab, it would refresh and then reset what I was doing.

## Expected behavior
Issue 1) Expect the mobile app to just load each time.
Issue 2) Expect that I can leave a specific page open for an extended amount of time without worrying that my view will get reset.

## Steps to reproduce
1) Install 0.112 beta
2) Open mobile app, do some stuff, then go back to home screen
3) Some time later, open mobile app and see the message.

## Environment

- Home Assistant release with the issue: 0.112b2 (also tried 0.113 dev)
- Last working Home Assistant release (if known): 0.111.4
- Browser and browser version: Chrome
- Operating system: Android for mobile app. Windows 10 and Chromebook for other issue.

Using Docker on a Debian system for my Home Assistant server.

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
No log entries are made when this happens. There is nothing else to show.

I think it would be nice to have a flag to disable this functionality, or opt in the first time.

**Comment by bramkragten** [comment]
Fixes in https://github.com/home-assistant/frontend/pull/6257

**Comment by bramkragten** [comment]
As for issue 2, is that just on the z-wave panel? We don't refresh the page, we just disconnect and then connect the panel, this should not cause a reset.

**Comment by gregg098** [comment]
> As for issue 2, is that just on the z-wave panel? We don't refresh the page, we just disconnect and then connect the panel, this should not cause a reset.

It did happen on the states page a few times. I was scrolled way down to a specific sensor and it would reset the page back to the top after the refresh.

**Comment by bramkragten** [comment]
What states page do you mean? Lovelace or the dev-tools? I did add a PR to restore scroll positions.

**Comment by gregg098** [comment]
> What states page do you mean? Lovelace or the dev-tools? I did add a PR to restore scroll positions.

Dev tools states. Just an example. Pretty much any page where you scroll and/or select something (e.g. the Z wave config page) was affected. I have not tried the latest RC yet to see if there is improvement.

**Comment by bramkragten** [comment]
Yeah, my fix will not work on every page, dev-tools is one that will not work for the scrolling. But other than scrolling it should keep everything. Will look into the scrolling on other pages.
