### ISSUE TITLE
Minor cosmetic issue in hovers within dialogs 0.112

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6285]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Tiny visual thing I noticed. When dialogs are first loaded, sometimes the close button has a weird hover at first.

![image](https://i.imgur.com/2bWUJFV.png)

It's not just the Users dialog, but others too like the "Lovelace Dashboards" one:

![image](https://i.imgur.com/g20ZMmy.png)

And the documentation icon in Lovelace card editors (screencap from demo):

![image](https://i.imgur.com/QpU4UzH.png)

Additionally the toggles have a similar problem

![image](https://i.imgur.com/5WGUuNn.png)

Might occur in other places, not sure.

## Steps to reproduce

1. Open a dialog (Configuration > Users, or Configuration > Persons, or Configuration > Lovelace Dashboards etc...)
2. Hover over the close button

## Environment

- Home Assistant release with the issue: 0.112.0b3
- Last working Home Assistant release (if known): 
- Browser and browser version: Chrome stable desktop
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by Misiu** [comment]
Same with add integration dialog:
![image](https://user-images.githubusercontent.com/1741838/86091221-cb3a7000-baab-11ea-9ea9-893226ece37e.png)

**Comment by bramkragten** [comment]
Yes, I have noticed it... I think it is an upstream issue in `mwc` but have to look into it.

**Comment by bramkragten** [comment]
https://github.com/material-components/material-components-web/issues/5443

**Comment by bramkragten** [comment]
https://github.com/material-components/material-components-web-components/pull/1498

**Comment by bramkragten** [comment]
Merged in mwc, waiting for the release now.
