### ISSUE TITLE
I updated from version 0.102.2 to version 0.114 and found that the icon color will not change to yellow when the terminal state is turned on. Why?

### ISSUE THREAD

**Issue by a120578270** [home-assistant/frontend#6286]
I have changed several versions of 0.102.2 and found this problem. The configuration is completely copied!
![image](https://user-images.githubusercontent.com/58241282/86108945-65270a80-baf6-11ea-901f-7b5bb0a1e2c6.png)

**Comment by bramkragten** [comment]
Please read all the changes between 0.102.2 and 0.114 (you might have to wait 6 weeks for those last 2 versions changelogs to show up...) and the documentation.

You can enable this with the `state_color` option: <https://www.home-assistant.io/lovelace/entities/#state_color>
