### ISSUE TITLE
Samba stopped working after Windows 10 update

### ISSUE THREAD

**Issue by bschatzow** [home-assistant/frontend#6287]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Can't access Homeassistant via my windows 10 machines (tried on two different computers) and Samba addon after 1903 update.

## Environment
Android devices working correctly, two windows 10 machines can not access my HA through samba.  They can ping, tracert, etc. Just not samba.

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Sorry, this is the wrong repo, you should create an issue in the repo for the Samba addon.
