### ISSUE TITLE
Toggle for 5 minute background disconnect

### ISSUE THREAD

**Issue by tigattack** [home-assistant/frontend#6296]
## The request
A toggle for the 5 minute background disconnect (introduced in #6152) would be fantastic.    
In order of my personal preference, any or all of the following toggles would be suitable: system-wide, per-user, per-device, or per-dashboard.

I absolutely see the value of the feature and am glad it's been introduced, but something which introduces such a big change should definitely have a toggle in my opinion.

For example, take my use case: I keep HASS open in a pinned tab in my browser. I would much rather it not disconnect in the background so I can switch to it and have every value on the dashboard already be up to date, rather than waiting an albeit short amount of time for the frontend to reconnect.

**Comment by bramkragten** [comment]
Fixed in #6304
