### ISSUE TITLE
Display and use of Node associations in Z-Wave Control Panel is broken

### ISSUE THREAD

**Issue by kpine** [home-assistant/frontend#6299]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The card that displays a node's association groups is missing a title and other labels. Furthermore, no button controls are available, so it's impossible to change associations in the control panel.

Screenshot showing the groups:
![image](https://user-images.githubusercontent.com/791794/86299297-c3b2be00-bbb4-11ea-9995-3ee74d8a9214.png)

## Expected behavior
The card should have a header, labels, and buttons that add or remove associations. Unfortunately I don't have a prior example, but it worked pretty recently. I would suspect recent translation changes.

## Steps to reproduce
1. Navigate to the Z-Wave control panel.
2. Select a node.
3. Scroll down to the groups, notice the missing card header and other labels.
4. Select a group and notice the missing buttons.

## Environment
- Home Assistant release with the issue: 0.112.0, 0.110.7
- Last working Home Assistant release (if known): Don't know
- Browser and browser version: Chrome 83.0.4103.116 (Official Build) (64-bit), Firefox 78.0.1 (64-bit)
- Operating system: Windows 10

```
arch | armv7l
dev | false
docker | true
hassio | false
installation_type | Home Assistant Container
os_name | Linux
os_version | 4.19.118-v7+
python_version | 3.7.7
timezone | America/Los_Angeles
version | 0.112.0
virtualenv | false
```

## State of relevant entities
N/A

## Problem-relevant configuration
Z-Wave integration.

## Javascript errors shown in your browser console/inspector
None

## Additional information
Other users reporting the problem in the forums:
https://community.home-assistant.io/t/zwave-pir-dimmer-association/208300
https://community.home-assistant.io/t/node-group-associations/203082

**Comment by tech165** [comment]
Hi, I am not sure but it looks like it is around localize was added to the Group panel ... and it looks like the same issue as #6330. Thanks
