### ISSUE TITLE
In configuration side panel hamburger menu button is missing

### ISSUE THREAD

**Issue by DavidFW1960** [home-assistant/frontend#6300]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

There is no hamburger menu in the configuration side panel making it difficult to open up the side menu again
## Expected behavior

the hamburger menu is normally there
## Steps to reproduce

open the configuration panel
## Environment

- Home Assistant release with the issue:0.112.0
- Last working Home Assistant release (if known):0.111?
- Browser and browser version:chrome v64
- Operating system: macos

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
I'm not seeing this, got a screenshot of what you mean?

**Comment by DavidFW1960** [comment]
It's just blank where there should be a hamburger? I can do it tomorrow but it does it on desktop and ipad etc as well

**Comment by bramkragten** [comment]
![image](https://user-images.githubusercontent.com/5662298/86336069-9ff08600-bc4f-11ea-9375-0b81368d2875.png)

**Comment by bramkragten** [comment]
![image](https://user-images.githubusercontent.com/5662298/86336110-b0086580-bc4f-11ea-8f25-7aca73dc4526.png)

**Comment by DavidFW1960** [comment]
Ok but I don't have the side bar turned on

**Comment by DavidFW1960** [comment]
Neither do you in first one.... hmm...

**Comment by bramkragten** [comment]
Might be worth mentioning settings like that ;-)

**Comment by DavidFW1960** [comment]
I was thinking it could be the theme but it's fine on other views. (Like the Supervisor panel is ok..)

> Might be worth mentioning settings like that ;-)

Yeah sorry...
