### ISSUE TITLE
The "automatically disconnect if a tab has been hidden for 5 minutes" feature in .112 seems to break my kiosks.

### ISSUE THREAD

**Issue by ksheyman** [home-assistant/frontend#6301]
First Home Assistant release with the issue: .112

Operating environment: Home Assistant Supervised

Integration: Frontend (lovelace)

Description of problem:
This feature renders my raspberry pi lovelace kiosks useless. It doesn’t seem to behave like it is described in the release notes. It says “When the Home Assistant UI is not visible for longer than 5 minutes” but these kiosks constantly are displaying the tab and still disconnecting. I would love to have an option to disable this feature altogether.

**Comment by bramkragten** [comment]
What browser, system, etc?

**Comment by ksheyman** [comment]
> 
> 
> What browser, system, etc?

chromium browser running on raspbian.

**Comment by bramkragten** [comment]
Fixed in https://github.com/home-assistant/frontend/pull/6304
