### ISSUE TITLE
Side bar icon disappears in general settings page

### ISSUE THREAD

**Issue by davidrustingha** [home-assistant/frontend#6309]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
When I go to the general settings page in the frontend the side bar icon disappears and I can't go back to one of the 
dashboards, HACS or anything I have in there.

## Expected behavior
I expected to be able to move to, for instance, the developers page. But I cant.

## Environment

- Home Assistant release with the issue: 112.0
- Last working Home Assistant release (if known): 111.4
- Browser and browser version: Google Chrome, 83.0.4103.116
- Operating system: Windows 10 64bit

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
https://github.com/home-assistant/frontend/issues/6300 ?

**Comment by davidrustingha** [comment]
Exactly. So its fixed, awesome. Thanks!
