### ISSUE TITLE
Missing MQTT tab in developer tools

### ISSUE THREAD

**Issue by denniswham** [home-assistant/frontend#6310]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

In the developer tools the MQTT tab is missing

## Expected behavior

When using the MQTT integration, when opening the developer tools in the UI, there should be also the MQTT tab. 

## Steps to reproduce

1. Go to developer tools
2. Check the (missing) MQTT tab. 

## Environment

- Home Assistant release with the issue: 0.112.0
- Last working Home Assistant release (if known): 0.111.4
- Browser and browser version: Edge (chromium based) Version 83.0.478.58 (Official build) (64-bit) and Android Companion App
- Operating system: Windows 10 (build 19041.329). Android 10

## State of relevant entities

n/a

## Problem-relevant configuration

n/a

## Javascript errors shown in your browser console/inspector

n/a

## Additional information

none

**Comment by hmmbob** [comment]
https://www.home-assistant.io/blog/2020/07/01/release-112/#integration-specific-panels-are-now-on-the-integrations-page

**Comment by denniswham** [comment]
Found it, thanks! With all the changes in this packed update I have overread this.

**Comment by denniswham** [comment]
Issue closed

**Comment by maglub** [comment]
Wow, what a weird way of making it less intuitive. This was honestly a sub optimal move.

The MQTT listener is such an integral part of (probably) a majority of all installations. Hiding it under "Configure" in the MQTT integrations pane is for sure not a good GUI enhancement.

I mean, it could have been hidden there also, but kept as a direct tab/link in the Developer Tools as it was before.

A big thumbs down from me, I must say.
