### ISSUE TITLE
"Config Error" notification links to old logs page on 0.112.0

### ISSUE THREAD

**Issue by marciogranzotto** [home-assistant/frontend#6311]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When there's a config error, there's a notification with a link to the logs. But it's linking to `/developer-tools/logs`.
![image](https://user-images.githubusercontent.com/11080704/86360992-906e3e80-bc49-11ea-9a83-6629e911b11e.png)

## Expected behavior

The link should be to `/core/logs`

## Steps to reproduce

1. Have something not working on your config file
2. Restart core
3. Click on the link in the notification

## Environment

- Home Assistant release with the issue: 0.112.0
- Last working Home Assistant release (if known): 0.111.4
- Browser and browser version: Chrome 83.0.4103.116 (Official Build) **(64-bit)**
- Operating system: macOS

## State of relevant entities

```yaml
Not applicable
```

## Problem-relevant configuration

```yaml
Not applicable
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by AdrinkBeer** [comment]
Fixed in the core by this [PR](https://github.com/home-assistant/core/pull/37311)
