### ISSUE TITLE
Template section doesn't show results correctly

### ISSUE THREAD

**Issue by snakuzzo** [home-assistant/frontend#6312]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

On template testing I noticed a stange behaviour. If I put a correct code in upper position (first 5 rows) nothing is showed

## Expected behavior

If I put correct code in every position I expect to view something

## Steps to reproduce

Clear template code and write something in first 5 rows

## Environment

- Home Assistant release with the issue: 0.112.0
- Last working Home Assistant release (if known): 0.111.4
- Browser and browser version: Chrome Version 83.0.4103.116 (Official Build) (64-bit) and Firefox 77.0.1 (64-bit)
- Operating system client: Ubuntu 20.x
- Operating system server: Raspbian Buster

## State of relevant entities

```yaml

```

## Problem-relevant configuration

![image](https://user-images.githubusercontent.com/7205371/86368958-1d32ef80-bc7e-11ea-983a-7165f5bc960c.png)

![image](https://user-images.githubusercontent.com/7205371/86369012-2f149280-bc7e-11ea-9b5a-db6103aac954.png)

![image](https://user-images.githubusercontent.com/7205371/86369037-35a30a00-bc7e-11ea-8698-2b87d18d4279.png)

```yaml

```

## Javascript errors shown in your browser console/inspector

No javascript errors

```txt

```

**Comment by Scialla** [comment]
Same for me. It seems that first 4 rows are under header

**Comment by cobradodo** [comment]
It seems that first 4 rows are under header...

**Comment by maxcanna** [comment]
both panes are under the header

**Comment by Guyohms** [comment]
see #6297
