### ISSUE TITLE
Zwave (legacy) listing is hid behind the top bar

### ISSUE THREAD

**Issue by 03397** [home-assistant/frontend#6322]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

After upgrading to the latest version 0.112.x the zwave listing of devices is missing the top lines most probably hiding behind the top bar
![image](https://user-images.githubusercontent.com/6150853/86470266-c2fc6200-bd43-11ea-8863-24c62de3dffb.png)

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by nicxvan** [comment]
I am also experiencing this issue on Home assistant .112.4
This also happens for the configuration parameters.
https://i.imgur.com/d9kZIAj.png
https://i.imgur.com/1b6py0e.png

**Comment by nicxvan** [comment]
This occurs on Mac Firefox 77.0.1
Safari version unknown.
Dolphin browser android.

I think it's related to screen size

**Comment by 03397** [comment]
@nicxvan 
I do think this. This happens to various screen sizes and various resolutions. It happens to my 2 mobiles, my laptop and my 2 tablets.
This problem reappeared at some point and it was solved.

**Comment by 03397** [comment]
Problem is still here after it was solved momentarily at a certain point.

**Comment by PrplHaz4** [comment]
Looks like this is still there in 2021.1.4
