### ISSUE TITLE
Logbook doesn't load in 0.112.0 for non-admin users

### ISSUE THREAD

**Issue by tjhiwa** [home-assistant/frontend#6326]
After update to 0.112.0, the logbook no longer load in the app. it works fine from web browser.

Logger: homeassistant.components.websocket_api.http.connection.139821523434704
Source: components/websocket_api/connection.py:97
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 6:44:31 AM (1 occurrences)
Last logged: 6:44:31 AM

Error handling message: Unauthorized

**Comment by balloob** [comment]
Figured it out. This happens because we want to fetch the names of users, but that API is admin-only.

**Comment by tjhiwa** [comment]
I noticed you are changing from user to person. What happens if the user has no linked person?
