### ISSUE TITLE
Unable to Configure UI on iOS (0.112.2)

### ISSUE THREAD

**Issue by aptonline** [home-assistant/frontend#6331]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Unable to use the ‘Configure UI’ from the three docs menu. Unable to select option (or help) and therefore unable to edit UI on iOS. Tested in HA app and Safari.

## Expected behavior

The ability to enter Configure UI mode.

## Steps to reproduce

Attempted to enter Configure UI mode from the menu, unable to select.

## Environment

HA In Docker (Synology host)

- Home Assistant release with the issue: 0.112.2
- Last working Home Assistant release (if known): 0.111.x
- Browser and browser version: Safari
- Operating system: iOS (13.5.1)

## State of relevant entities

N/A

```yaml

```

## Problem-relevant configuration

N/A

```yaml

```

## Javascript errors shown in your browser console/inspector

N/A

```txt

```

**Comment by aptonline** [comment]
**Update**: this issues seems to be related to Custom Header as disabling it resolved the issues. Thanks @ludeeus .

**Comment by maykar** [comment]
In case anyone else running into this ends up here. This has already been fixed in CH pre-release 1.6.6. [More info.](https://github.com/maykar/custom-header/issues/235)
