### ISSUE TITLE
HA Media Player Card Album Cover with Denon HEOS

### ISSUE THREAD

**Issue by schneewe** [home-assistant/frontend#6342]
## Checklist

- [ X ] I have updated to the latest available Home Assistant version.
- [ X ] I have cleared the cache of my browser.
- [ X ] I have tried a different browser to see if it is related to my browser.

## The problem

Hello guys first of all thanks for the great product and the latest updates.
I guess I found an issue in the media player card and the "album cover" feature.
The media player is linked to my Denon HEOS System and shows the right cover, but only the first time or when I stop the playback and start it again.

I only see this when I play music over airplay to my HEOS system and didn't test it with Spotify. 
I don't know how the media player works in detail, but I assume it depends on the "trigger" to reload the cover. 
With airplay on HEOS, the URL to the cover doesn't change on a new title and stays the same (link to the receiver). Only the title changes. 
With Spotify the URL change something in the internet, so the URL is always different.

## Expected behavior

When the title changes on the receiver, the media player card should change the album cover art.
Even if the URL to cover stays the same.

## Steps to reproduce

Create the HEOS integration and link it to a media_player card.
Activate the album cover feature
Change the title (next track)

## Environment

- Home Assistant release with the issue: 0.112.2 (tested first on 0.110.x)
- Last working Home Assistant release (if known): none
- Browser and browser version: Chrome 83.0.4103.97
- Operating system: MacOS Catalina 10.15.5

## Javascript errors shown in your browser console/inspector

None

**Comment by truthfulie** [comment]
Also experiencing the same issue here.

**Comment by joshtbernstein** [comment]
I'm also seeing this issue with the Spotify and Chromecast players.

**Comment by schneewe** [comment]
I just want to ask, if there are any plans to fix this?
Still no fix on this.

The problem is for sure that the URL for the image is not changing, and therefor the picture is not changing.
I guess it would be a better approach to use the title "change trigger" and not the url itself.

**Comment by bramkragten** [comment]
It might be better if the HEOS components changed the URL of the image for every title if the URL is the same for every title, like so:

`https://example.com/artwork.png?title=Title_of_first_song`
`https://example.com/artwork.png?title=Title_of_second_song`

Otherwise, it could still be cached somewhere as the URL is the same.
