### ISSUE TITLE
Re-enabled entity's friendly_name is "Unavailable".

### ISSUE THREAD

**Issue by tdejneka** [home-assistant/frontend#6351]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

In the Entities page, if you disable then re-enable an entity, its friendly_name is reported as being `Unavailable`. In the States view, the re-enabled entity's actual friendly_name is displayed correctly.

In other words, the Entities view isn't refreshing all of the re-enabled entity's information at the moment it is re-enabled.

## Expected behavior

Upon re-enabling the disabled entity, the Entities page should refresh all its information concerning the re-enabled entity and display its correct friendly_name.

## Steps to reproduce

Use any entity automatically created by an integration that supports config flow. I used the Brother Printer integration and  disabled one of its entities:
```
sensor.dcp_7065dn_uptime
```

Upon re-enabling it (and activating "Show disabled entities") its friendly_name is "Unavailable". Refreshing the web-page doesn't correct it. The entity is definitely re-enabled because it appears (with its correct name) in the States view and in the auto-generated UI

You have to completely exit the Entities view (i.e. change to a different view) and then when you return to it, the re-enabled entity's friendly_name is now displayed correctly (i.e. it's no longer Unavailable).

## Environment

- Home Assistant release with the issue: 0.112.3
- Last working Home Assistant release (if known): unknown
- Browser and browser version: Firefox 78.0.1
- Operating system: Ubuntu 18.04.4

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
If refreshing doesn't fix it, your story doesn't add up. Could it be that the entity became available after the refresh and it was just a timing thing?

**Comment by tdejneka** [comment]
> If refreshing doesn't fix it, your story doesn't add up

Have you tried to reproduce the bug?

**Comment by bramkragten** [comment]
No.

**Comment by tdejneka** [comment]
I've attached a video demo of the bug (zipped MP4 file). The video ends with the re-enabled entity displaying "Unavailable" as its friendly_name (even after refreshing the web-page).

What the video does not show is that if you leave the screen untouched, approximately a minute later (I didn't time it) the friendly_name automatically changes from `Unavailable` to it original, correct name. Perhaps it may have something to do with the integration itself which updates its entities? At any rate, the initial lingering display of `Unavailable` is undesirable.

[Demo of unavailable bug.zip](https://github.com/home-assistant/frontend/files/4900079/Demo.of.unavailable.bug.zip)

**Comment by bramkragten** [comment]
Yeah, that is probably the backend not yet providing the entity, is this the same for every integration? Or integration specific?

**Comment by tdejneka** [comment]
I tried it with the **Google Cast** integration (also uses config flow) and it behaves nearly identically. I say "nearly" because no amount of refreshing or waiting allows it to recover its friendly_name and it remains as `Unavailable`. I have to restart Home Assistant to correct it.

FWIW, I originally observed this behavior with input_number and reported it in the Core repo. 
https://github.com/home-assistant/core/issues/37570

balloob responded to the issue and concurred that helpers created via the UI should probably handle re-enabling more cleanly. I also reported the `Unavailable` behavior was present in a _config-flow based integration_, like the Brother Printer integration, but he felt it was a frontend issue ... and so here we are.

So where do we go from here? Should I report back to balloob, in the other issue, that you believe the frontend is not responsible for the behavior?

**Comment by tdejneka** [comment]
Three months and several versions later, the **problem still exists**.

Version 0.116 is still unable to properly restore a disabled entity, such an an input_boolean (even if created via the Helpers menu). The re-enable entity's name remains as `Unavailable`. Neither refreshing the web page or executing Reload input_booleans fixes it.

**Comment by spacegaier** [comment]
The backend will wait 30 seconds before reloading the entities (which is when the frontend gets the new data including the name).

If you enable an entity through its info dialog, the frontend correctly informs the user about that fact. If you directly enable an entity however from the entity overview list, I do not see the dialog, despite the coding trying to show it. This should be fixed. Perhaps we should also show a temporary name, e.g. "Activation pending..."

@tdejneka Which enabling option did you use? I assume you were not shown the warning about the 30 seconds which elad to this confusion?

**Comment by tdejneka** [comment]
I had posted a video (6 posts earlier on July 9, 2020) demonstrating the bug and, yes, I had used the Entities view.

I just repeated the test, using 2020.12.2 (Home Assistant OS on RPi3). I chose an input_boolean from the Entities view, disabled it, then re-enabled it. This time a popup appears indicating it will take 30 seconds for the entity to be enabled.

One minute later it still indicated `Unavailable` so I refreshed the browser (twice) and it remained `Unavailable`.

![Screenshot 2021-01-05 113254](https://user-images.githubusercontent.com/44732909/103672574-7b50d000-4f4a-11eb-9272-d0d85ac29f1a.png)

The input_boolean is also missing from the Entities card that displayed it (indicating it is truly unavailable). I executed "Reload Input Booleans" and the entity remains `Unavailable`.

![Screenshot 2021-01-05 114153](https://user-images.githubusercontent.com/44732909/103672997-0cc04200-4f4b-11eb-8d8c-726d84c6c8f5.png)

Finally, I restarted Home Assistant and the input_boolean is no longer `Unavailable` and it appears in the Lovelace UI.

![Screenshot 2021-01-05 114548](https://user-images.githubusercontent.com/44732909/103673517-ab4ca300-4f4b-11eb-9132-421f102d48cf.png)

![Screenshot 2021-01-05 114715](https://user-images.githubusercontent.com/44732909/103673608-cae3cb80-4f4b-11eb-89ba-03a19410dfde.png)

The bug is still present; disabling an entity is straightforward, re-enabling it is not.

**Comment by spacegaier** [comment]
That sounds like two different scenarios / issues then:
1. If the backend behaves correctly (e.g. I tested with the Synology NAS integration), then re-enabling works (after 30 seconds the backend provides the reloaded data to the frontend and everything gets updated correctly). In this scenarios, only the 30 seconds popup is missing as I mentioned above, if you are not going the route via the entity popup but from the list itself via the top buttons.
2. For the input_boolean the reload itself doesn't seem to work. It seems to never get something back from the backend. That would then be a backend issue most likely (haven't investigated that yet).

**Comment by tdejneka** [comment]
FWIW, I originally posted this Issue in Frontend and was directed to post it in Core (where it also remains an open Issue).
https://github.com/home-assistant/core/issues/37570#issuecomment-657059346

**Comment by bramkragten** [comment]
If the entity doesn't come back after some time, that would be a backend issue.

**Comment by tdejneka** [comment]
> that would be a backend issue

I agree ... and it's why I originally posted it in Core but was then instructed by balloob to post it here.

Anyway, six months later and the Core version of this bug remains unsolved.

**Comment by bramkragten** [comment]
Make a specific issue for a specific integration that is easily reproduceable. That helps a lot generally.

**Comment by tdejneka** [comment]
Was that a joke? It must be a joke because I have documented the issue for input_number, input_boolean, etc, even posted a video demonstrating it, and all are easily reproducible.

**Comment by bramkragten** [comment]
Well, the issue you created in core is very general, while these are probably integration specific issues. The code owners of those issues will not check that general issue. If you create an issue for just a single integration ([like Paulus suggested](https://github.com/home-assistant/core/issues/37570#issuecomment-657348269])), it is more likely to get picked up by the code owner of the integration.

(And no, I have not read the entire issue)

**Comment by tdejneka** [comment]
> the issue you created in core is very general

Its scope is that it affects _disabled entities_. In the issue I demonstrated how to reproduce it for an **input_number** but indicated the problem is _not limited_ to an input_number (and affects other Helpers as well as entities created by other integrations).

Regardless of how many separate Issues ought to be opened, the one opened six months ago, demonstrating it for an input_number, was never resolved.

**Comment by tdejneka** [comment]
Closing this Issue because problem is likely to be in Core not Frontend.
