### ISSUE TITLE
Import from USB - no success/error message

### ISSUE THREAD

**Issue by Misiu** [home-assistant/frontend#6374]
## The request

When trying to import settings from USB thumb drive there is no way to say if the process finished successfully or with errors.
In my case, I'm trying to enable I2C but I don't know if it succeeded (without restarting PI and checking).

Ideally, we should see a toast message when the USB device is connected and a message box when the settings get successfully imported or error message when there was a problem with this.

## The alternatives

There are no alternatives. We can look at logs, but this won't say much.

In supervisor section I see:

> 20-07-13 20:03:45 INFO (MainThread) [supervisor.hassos] Syncing configuration from USB with HassOS.
> 20-07-13 20:03:45 INFO (MainThread) [supervisor.host.services] Restart local service hassos-config.service
> 20-07-13 20:03:45 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.RestartUnit on /org/freedesktop/systemd1
> 20-07-13 20:04:39 INFO (MainThread) [supervisor.hassos] Syncing configuration from USB with HassOS.
> 20-07-13 20:04:39 INFO (MainThread) [supervisor.host.services] Restart local service hassos-config.service
> 20-07-13 20:04:39 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.RestartUnit on /org/freedesktop/systemd1

In host section:

> [ 1313.264543] usb 2-1: New USB device found, idVendor=13fe, idProduct=6300, bcdDevice= 1.10
> [ 1313.264587] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [ 1313.264616] usb 2-1: Product: USB DISK 3.0
> [ 1313.264640] usb 2-1: Manufacturer: Wilk
> [ 1313.264663] usb 2-1: SerialNumber: 070A8CC995B06616
> [ 1313.272692] usb-storage 2-1:1.0: USB Mass Storage device detected
> [ 1313.274823] scsi host0: usb-storage 2-1:1.0
> [ 1314.343921] scsi 0:0:0:0: Direct-Access     Wilk     USB DISK 3.0     PMAP PQ: 0 ANSI: 6
> [ 1314.345816] sd 0:0:0:0: [sda] 60555264 512-byte logical blocks: (31.0 GB/28.9 GiB)
> [ 1314.346309] sd 0:0:0:0: [sda] Write Protect is off
> [ 1314.346345] sd 0:0:0:0: [sda] Mode Sense: 45 00 00 00
> [ 1314.346675] sd 0:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
> [ 1314.473743]  sda: sda1 sda2
> [ 1314.476558] sd 0:0:0:0: [sda] Attached SCSI removable disk
> [ 1314.481043] udevd[417]: inotify_add_watch(6, /dev/sda, 10) failed: No such file or directory
> [ 1314.484941] udevd[265]: inotify_add_watch(7, /dev/sda, 10) failed: No such file or directory
> [ 1314.488341] udevd[264]: inotify_add_watch(7, /dev/sda2, 10) failed: No such file or directory
> [ 1314.488414] udevd[265]: inotify_add_watch(7, /dev/sda1, 10) failed: No such file or directory
> [ 1314.488833] udevd[499]: inotify_add_watch(6, /dev/sda, 10) failed: No such file or directory
> [ 1314.490119] udevd[418]: inotify_add_watch(6, /dev/sda2, 10) failed: No such file or directory
> [ 1314.491488] udevd[417]: inotify_add_watch(6, /dev/sda1, 10) failed: No such file or directory
> [ 1314.493981] udevd[498]: inotify_add_watch(6, /dev/sda2, 10) failed: No such file or directory
> [ 1314.494698] udevd[499]: inotify_add_watch(6, /dev/sda1, 10) failed: No such file or directory

## Additional information
Related issue: https://github.com/home-assistant/operating-system/issues/753

**Comment by bramkragten** [comment]
This should be built in the supervisor first, so could you add an FR there?

**Comment by Misiu** [comment]
@bramkragten according to issue template in supervisor repo, FR should go in the forum. I don't want to get a ban for that.
If possible, could you create it? Thank you.

**Comment by bramkragten** [comment]
So you should create the FR in the forum then, I have never used this functionality so am not the one to create an FR.

**Comment by Misiu** [comment]
https://community.home-assistant.io/t/import-from-usb-no-success-error-message/211563 anyone interested please vote.
