### ISSUE TITLE
Save Automation/Scene/Script with keyboard shortcut

### ISSUE THREAD

**Issue by niro1987** [home-assistant/frontend#6397]
## The request

When editing an automation, scene or script I would like to be able to save the automation, scene or script that I am working on with the keyboard shortcut CTRL+S. 

## The alternatives

No alternatives exist

**Comment by gilsonmandalogo** [comment]
I'll do this change on next hours.

**Comment by Misiu** [comment]
I think this can be closed (#7207 is merged)
