### ISSUE TITLE
0.113.0b0 broke my themese

### ISSUE THREAD

**Issue by roblamoreaux** [home-assistant/frontend#6412]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem

  I updated to 0.113.0b0 and the cards in the dark_blue  Kiosk themed dashboard all went white making it impossible to see the text.
Hunting around with themes that did not break I found the themes I had modified from some a while ago did not have 'card-background-color; and used the 'secondary-background-color' for the cards.

So it seems something changed that now causes it to get the card-background-color from the default theme instead of the secondary-background-color of the current theme.

## Expected behavior

  I expected it to get the card-background color from the secondary background color of the active theme and it didn't.

## Steps to reproduce

  Provide steps for us, that helps reproducing your issue.
  For example:
    1. use a theme with no card-background-color and a light them instead of the dark-blue one

## Environment

  version 0.113.0b0 with themes from somewhere I can't remember

- Home Assistant release with the issue: 0.113.0b0
- Last working Home Assistant release (if known): 0.112.0x
- Browser and browser version: all
- Operating system: all

## State of relevant entities

 Card background color

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Share your theme, do you have `card-background-color` set?

**Comment by roblamoreaux** [comment]
The whole issue is that the file of themes I downloaded last year has a lot of themes without `card-background-color` set (some have `paper-card-background-color` some don't have either) and up until 0.113.0b0 it seems to have gotten the color from the secondary background color of the current theme. With 0.113.0b0 it seems to be getting the color from somewhere else which I suspect is the default theme.

Which is correct I don't care, but it was a change that I did not see any release note for so I wanted to be sure it was brought up. (and it annoyed me that my nice screen became difficult to read)

I can add the line to other themes, but it would be good to let people know that this changed.

[themes.zip](https://github.com/home-assistant/frontend/files/4933154/themes.zip)

**Comment by bramkragten** [comment]
If you don't have `card-background-color` in your theme a lot is broken a while already, as it is just for almost a year now.

We never used secondary background color for the cards, but `ha-card-background` and as a fallback the deprecated `paper-card-background-color`. All variables with `paper` in front of them are not supported and will eventually all be removed.
