### ISSUE TITLE
[0.113.0b0] Overall background changed

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/frontend#6416]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Since the update to 0.113.0b0 the overall background color changed:
![Screenshot_2020 07 17_01h15m05s_005_](https://user-images.githubusercontent.com/1368405/87731677-5bc2c100-c7cb-11ea-88b8-cc67d1024236.png)

This was the layout in version 0.112.x:
![Screenshot_2020 07 17_01h14m54s_004_](https://user-images.githubusercontent.com/1368405/87731676-5a919400-c7cb-11ea-9745-98e0da11a34b.png)

Is there a theme variable I need to change in order to get the same background as before?
Currently the issue is, that the contrast to the card is missing...

## Expected behavior

Have contrast from overall background to card

## Steps to reproduce
1. Update to 0.113
2. View overall background

## Environment

- Home Assistant release with the issue: 0.113.x
- Last working Home Assistant release (if known): 0.112.x
- Browser and browser version: Chrome Edge 84
- Operating system: Windows 10

## State of relevant entities

```yaml
none
```

## Problem-relevant configuration

```yaml
none
```

## Javascript errors shown in your browser console/inspector

```txt
none
```

## Additional information
Theme used: https://github.com/home-assistant-community-themes/midnight

**Comment by bramkragten** [comment]
To keep it all the same replace `paper-card-background-color` with `ha-card-background-color`

**Comment by bramkragten** [comment]
Added it to the release notes.
