### ISSUE TITLE
Weather card exceptional icon not sized correctly

### ISSUE THREAD

**Issue by MatthewFlamm** [home-assistant/frontend#6425]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

The exception icon is too large compared to other icons.  It also obscures the temperature.  Location redacted below.

![Screenshot_20200717-215610~2](https://user-images.githubusercontent.com/39341281/87842437-83249700-c87a-11ea-8e3e-a29cc0db1827.png)

## Expected behavior

Icon to be of similar size and not obscure temperature.

## Steps to reproduce

Have a weather entity with an exceptional state in forecast and display it in weather card.

## Environment

- Home Assistant release with the issue: 0.112.5
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome Android
- Operating system: Android

## State of relevant entities

A forecast entry with (I cannot copy from the states page from chrome browser on Android, but this is a different issue).
```yaml
condition: exceptional
```

## Problem-relevant configuration

UI configured NWS integration

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
Looks good to me :)
