### ISSUE TITLE
The system column in /config/users is not wide enough

### ISSUE THREAD

**Issue by Santobert** [home-assistant/frontend#6428]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

The system column in `/config/users` is not wide enough. The title gets reduced to `S...` which is not really helpful.
There is a lot of space. The first column `Name` spans across the whole page.

![grafik](https://user-images.githubusercontent.com/15657682/87851764-34b7dc80-c8fc-11ea-9b85-17c964129b7a.png)

## Expected behavior

Each column is wide enough to display most of it's content plus the whole title.

## Steps to reproduce

Visits `/config/users`

## Environment

- Home Assistant release with the issue: 0.113.0b1
- Last working Home Assistant release (if known): Not known
- Browser and browser version: Firefox 78.0.2
- Operating system: Windows 10

**Comment by Santobert** [comment]
Still relevant in 0.115.0b7

**Comment by spacegaier** [comment]
I have changed this screen a couple of weeks ago, so this issue does no longer occur in the latest dev version (see screenshots PR https://github.com/home-assistant/frontend/pull/7757). Please test again and then close this issue once confirmed.

**Comment by Santobert** [comment]
Solved in 1.0.0b4. Thanks everyone :tada:
