### ISSUE TITLE
Translation error showing up on integrations

### ISSUE THREAD

**Issue by vdiogo** [home-assistant/frontend#6439]
Most of my integrations are showing a _Translation Error: Invalid values for "count": "xyz". Options are "0", "1"_ type of error.

Tried to remove and re-add again and error message persists. The integration seem to be working properly though.

**Comment by bramkragten** [comment]
There is an error in the translations for your language, these translations are managed through Lokalise.

You can help fix this! Check https://developers.home-assistant.io/docs/translations
