### ISSUE TITLE
Custom Elements doesn’t Exist

### ISSUE THREAD

**Issue by davidrustingha** [home-assistant/frontend#6440]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
Whenever I open the Home Assistant App on my iPhone, android tablet, or when I open home Assistant on my laptop I get the error 
‘Custom elements doesn’t exist ..’
I have a couple of conditional cards and picture cards set up with a custom layout card for spacing.
This is what it looks like
![image](https://user-images.githubusercontent.com/62120423/88026376-12a99e80-cb36-11ea-8ee1-c42b990b4221.png)
This is how it should look
![image](https://user-images.githubusercontent.com/62120423/88026628-7207ae80-cb36-11ea-8216-0e450e9dc138.jpeg)

## Expected behavior
I would expect it to load the cards, instead of showing me the error.

## Steps to reproduce
- open home Assistant (app)
- navigate to one of the dashboards these cards are in
- the problem shows itself

## Environment

- Home Assistant release with the issue: 112 and before
- Last working Home Assistant release (if known): Not sure. I’ve had the issue since I configured the cards.
- Browser and browser version: Chrome (latest), Opera Mobile (latest) & Firefox (latest)
- Operating system: (iOS 12.4.8 (latest for iPhone 6S), Android 4.4.2, Windows 10)

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
Sometimes the page refreshes itself and then the error is gone. Other times I have to refresh it myself to get rid of the error.

**Comment by bramkragten** [comment]
Are you using a custom card here somewhere? Because the built-in cards don't give these errors.
