### ISSUE TITLE
Please don't prefill new cards in Lovelace's visual card editor

### ISSUE THREAD

**Issue by noxhirsch** [home-assistant/frontend#6444]
## The request
Everytime I add a new card in Lovelace UI, the card is prefilled with random entities and in case of the entities-card with a useless title "My Title". This is pretty annoying, because I have to remove all this stuff first before I can use the card.
I understand that this is maybe nice for beginners which don't know how editing the UI works. So this behaviour could be connected with advanced mode - if it's off, the cards get prefilled - if it's on, the cards don't get prefilled.

## The alternatives
Alternatively only the first time a user adds a new card, the card gets prefilled. But I think that's more complex, because HA would need to set another flag for each user.

**Comment by balloob** [comment]
You can just press the "manual" button at the bottom left if you want an empty config?

**Comment by noxhirsch** [comment]
Maybe my text wasn't very clear on that: I don't want an empty card config, but an empty visual editor instead.

**Comment by iantrich** [comment]
We discussed this a bit in chat, think a 'clear' button would make most sense as a compromise on this.

**Comment by noxhirsch** [comment]
I think that's a good compromise, because it could be useful in other cases, too 👍
