### ISSUE TITLE
Security Cameras not streaming 

### ISSUE THREAD

**Issue by billasw1** [home-assistant/frontend#6456]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem

After upgrading to .113 my Axis and Onvif integrations are no longer streaming cameras in the frontend. Before upgrading the cameras were streaming fine
## Expected behavior

I expected cameras to stream normally 
## Environment

- Home Assistant release with the issue: .113
- Last working Home Assistant release (if known): previous version 
- Browser and browser version: Chrome. Latest & HA app
- Operating system: IOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by gydavid** [comment]
Same problem in android chrome

**Comment by godinperson** [comment]
Same!

**Comment by bramkragten** [comment]
Do they work outside of the frontend? Like in HomeKit or Chromecast?

**Comment by godinperson** [comment]
Yes!

**Comment by bramkragten** [comment]
Mmm, it works here, anything in the logs? What integration are you using?

**Comment by godinperson** [comment]
In fact, I'm using a Blue Iris integration. No error in log for me. What can I give you that will help?

**Comment by bramkragten** [comment]
Have you checked the browser logs?

**Comment by godinperson** [comment]
504 (Gateway Timeout) on the cam

**Comment by zsarnett** [comment]
That would mean the URL that the integration said the stream was at timed out (Meaning it couldn't find retrieve the stream within 30s or whatever the timeout is)

**Comment by zsarnett** [comment]
My RTSP streams are working. Lovelace just pulls from the integration. IDK if bram knows something more but this does sound like something is incorrect on the integration side

**Comment by godinperson** [comment]
I can use the same link I have in my configuration to connect to the camera on another tab but won't work in HA anymore. Used to work on 0.112

**Comment by bramkragten** [comment]
🤷‍♂️ You are using a proxy I think, judging by the 504? Check the logs of that. The frontend doesn't give timeouts.

**Comment by godinperson** [comment]
No proxy, straight connection

**Comment by billasw1** [comment]
My AXIS and ONVIF integrations broke when I upgraded to .113 - Both were working fine on .112 - The Still image updates every Seconds but live stream will not work... Had to be something that broke in between versions. I have not tried to add the RSTP streams from the cameras on the configuration file as I figured you guys would fix whatever you broke

**Comment by bramkragten** [comment]
Only change I see is <https://github.com/home-assistant/frontend/pull/6271> but I don't think that would break anything...

**Comment by cyber-arche** [comment]
I'm having a similar problem where my cameras stopped streaming, seems to only affect the Reolink POE ones, my Wyze works, after upgrading to .113.

**Comment by billasw1** [comment]
I’m getting this error in the log. Any clue to the issue caused when upgraded to .113?

2020-07-29 19:35:17 ERROR (stream_worker) [libav.tcp] Port missing in uri

**Comment by billasw1** [comment]
I do not have any rstp stream requests in the configuration.yaml so this has to be coming from the integration

**Comment by billasw1** [comment]
So further investigation shows that if the generic IP camera RSTP stream is loaded via the Configuration.yaml I am able to via the stream within the dashboard. However the live stream from the Axis or Onvif Camera loaded via the respective integration does not work... only the still image capture works from the integration

**Comment by bramkragten** [comment]
Maybe create an issue for the integration in the core repo, I'm not sure at this point as I can't reproduce or have any logs. The above is error is from the core, however.

**Comment by godinperson** [comment]
Good morning, 

I'm back from vacation and would like that issue to be solved. What test or log can I get that would help you?

Upgraded to 0.114.0b3 but same issue

**Comment by godinperson** [comment]
![image](https://user-images.githubusercontent.com/24859095/90068625-f5906780-dcbe-11ea-928f-2dd546e09c8d.png)

**Comment by billasw1** [comment]
@godinperson I opened a new case under the Core section. Seeing some additional log info after upgrading to .114
