### ISSUE TITLE
Existing themes do not work propely with 0.113

### ISSUE THREAD

**Issue by popsyann** [home-assistant/frontend#6457]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by popsyann** [comment]
Hi,
I just upgraded to Home Assistant V 0.113 and none of my existing themes can be displayed as they were in any version used until 0.112.2
The backgrounds of the Lovelace cards are all white, instead of following what was described in the themes. Very annoying. Waiting for a solution/correction in next release. Thank you!

**Comment by zsarnett** [comment]
Please fill out the issue template

Also check the breaking changes for themes.
