### ISSUE TITLE
0.113 Automations/Scene's/Scripts Unsaved changes when nothing changed

### ISSUE THREAD

**Issue by woodmj74** [home-assistant/frontend#6458]
Experienced on both browser and HA app on IOS, HA 0.113 on Raspberry PI Hass.io - using default themes etc. nothing funky!

> Edit an existing automation, scene or script
> do not make any changes
> click the back arrow "<" top left of screen
> warning message shown "You have unsaved changes. Are you sure you want to leave?" when nothing has changed

Also, immediately on edit the save icon (yellow bottom right) is displayed before a change is made

Would have expected (and believe it was prior to 0.113 unless a change was made both the save icon and the warning message were not shown when opening in edit and not making any changes.

**Comment by zsarnett** [comment]
Please fill out the issue template

**Comment by woodmj74** [comment]
Sorry @zsarnett (first time doing this) - have done and tried much harder!
