### ISSUE TITLE
Tuya integration & thermostat shows temperatures as doubled, on/off button needs double click for on state

### ISSUE THREAD

**Issue by Tontze** [home-assistant/frontend#6462]
## Checklist

- [ x] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

Added integration and configured via frtontend using instructions : https://www.home-assistant.io/integrations/tuya/

## Expected behavior

All temperature information are doubled. ON/OFF button turns thermostat "off", turning on turns thermostat "on", but card states thermostat "off", pushing again turns thermostat fast off, and then fast back on, and also card states thermostat is on.

## Steps to reproduce

    1. install tuya integration
    2. add thermostat card
    3. turn on/off
    4. Observe doubled temperatures

## Environment

arch | x86_64
-- | --
chassis | desktop
dev | false
docker | true
docker_version | 19.03.12
hassio | true
host_os | Ubuntu 18.04.4 LTS
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 4.15.0-96-generic
python_version | 3.7.7
supervisor | 229
timezone | Europe/Helsinki
version | 0.112.4
virtualenv | false

- Home Assistant release with the issue:  0.112.4

## State of relevant entities

`

climate.730270563c71bf21d03a | unknown | hvac_modes: off min_temp: 5 max_temp: 35 target_temp_step: 0.5 current_temperature: 39 temperature: 36 friendly_name: Floor heating supported_features: 1
-- | -- | --

`

```yaml

```

## Problem-relevant configuration

Pure UI installation

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

Thermostat : 
https://www.moeshouse.com/collections/electric-floor-heating-thermostat/products/wifi-white-thermostat-temperature-controller-lcd-touch-screen-backlight-for-electric-heating-works-with-alexa-google-home-16a

**Comment by bramkragten** [comment]
I don't totally understand the issue, but this is likely a problem with the integration and not with the frontend.
