### ISSUE TITLE
0.113.1 Developer Tools shadowRoot.querySelector(...) is null

### ISSUE THREAD

**Issue by tomlut** [home-assistant/frontend#6464]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Opening developer tools and moving between any of the tabs causes this error:

Logger: frontend.js.latest.202007160
Source: components/system_log/__init__.py:209
First occurred: 9:57:35 AM (1 occurrences)
Last logged: 9:57:35 AM
https://[my domain redacted].duckdns.org/frontend_latest/chunk.cf565e41b8a8dce0642a.js:133:204 TypeError: this.shadowRoot.querySelector(...) is null

## Expected behavior

Not generating the error.
## Steps to reproduce
Open developer tools.
Move to any Tab e.g. Services
Look at Log.

## Environment

- Home Assistant release with the issue: 0.113.1
- Last working Home Assistant release (if known): 0.112.4
- Browser and browser version: Firefox 78.0.2 , Chrome 84.0.4147.89
- Operating system: Windows 10, 1909 Pro

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Duplicate
