### ISSUE TITLE
Gauge doesn’t show properly in Safari macOS

### ISSUE THREAD

**Issue by avehome** [home-assistant/frontend#6467]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

![Schermafdruk 2020-07-26 14 38 27](https://user-images.githubusercontent.com/50752001/88479509-e46df980-cf4f-11ea-8f02-86a716c9c2f9.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/50752001/88479662-0e73eb80-cf51-11ea-9b94-04f6b62c625b.png)

## Steps to reproduce

    
1. Define a gauge card in Lovelace
2. Open the Home Assistant UI in Safari (macOS)

## Environment

- Home Assistant release with the issue: 0.113.1
- Last working Home Assistant release (if known): 0.112.4
- Browser and browser version: Safari 13.1.2
- Operating system: macOS Catalina, version 10.15.6

I don't see this issue in Safari iOS. Only in Safari macOS.
I didn't test this with other browsers, because I like to use only one browser (also it worked fine in HA 0.112.4).

## State of relevant entities

N/A
```yaml

```

## Problem-relevant configuration

      - title: Elektra
        type: entities
        entities:
          - type: custom:hui-element
            card_type: horizontal-stack
            cards:
              - type: gauge
                title: Stroomverbruik
                entity: sensor.power_consumption_kwh_to_watt
                theme: gauge_card
                min: 0
                max: 4000
                severity:
                  green: 0
                  yellow: 0
                  red: 2000
                style: |
                  ha-card {
                    --ha-card-box-shadow: none;
                    margin: 2px -8px -20px -8px;
                  }
              - type: gauge
                title: Stroomopbrengst
                entity: sensor.power_production_kwh_to_watt
                theme: gauge_card
                min: 0
                max: 1800
                severity:
                  green: 0
                  yellow: 2500
                  red: 3000
                style: |
                  ha-card {
                    --ha-card-box-shadow: none;
                    margin: 2px -8px -20px -8px;
                  }
```yaml

```

## Javascript errors shown in your browser console/inspector

There are no error logs in the browser’s console.

## Additional information
N/A

**Comment by bramkragten** [comment]
> - [x] I have tried a different browser to see if it is related to my browser.


!==

> I didn't test this with other browsers, because I like to use only one browser (also it worked fine in HA 0.112.4).

**Comment by bramkragten** [comment]
Please provide a reproduction without using custom cards.

**Comment by bramkragten** [comment]
Working here on MacOS Safari:

![image](https://user-images.githubusercontent.com/5662298/88525236-a1b52b80-cffa-11ea-972b-0ead9459d0af.png)

**Comment by avehome** [comment]
Did at work a test with Brave on Windows 7 and looks also fine.
So it looks it's something on my side... I'll do a test tonight without using "custom:hui-element"

**Comment by bramkragten** [comment]
And without `card-mod` please :-)

**Comment by avehome** [comment]
Found the problem. Looks like the scaling in safari create the issue.
![image](https://user-images.githubusercontent.com/50752001/88581965-43b23380-d04e-11ea-8ec0-2fdefe0679bf.png)

Without scaling everything looks fine
![image](https://user-images.githubusercontent.com/50752001/88582111-7b20e000-d04e-11ea-8b9a-a615ea830bd8.png)

Weird... I use scaling 125% for a long time without any cosmetic issues? I use this because everything is too small for my eyes on a 40" TV (has something to do with age I think ;-) ).

**Comment by bramkragten** [comment]
The gauge element was rewritten in version 0.113, I'll take a look at the scaling.

**Comment by G8YTZ** [comment]
Same issue here, just MACOS Safari Catlina. OK on Chrome on the same MacBook and ok on MS Edge
<img width="367" alt="Screenshot 2020-07-28 at 15 04 14" src="https://user-images.githubusercontent.com/35895759/88690796-f12b5280-d0f3-11ea-96f6-50dfbe7ef383.png">

**Comment by G8YTZ** [comment]
Hi, @avehome 

how did you achieve the bar-graph historical display? I could not see that option in the documentation for type "sensor" only a line graph.

Justin

**Comment by avehome** [comment]
That's because this is not a default card. It's a custom card you can add to Home Assistant.
Check https://github.com/kalkih/mini-graph-card
