### ISSUE TITLE
More-info X is off center

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#6472]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

<img width="402" alt="Schermafbeelding 2020-07-26 om 23 35 52" src="https://user-images.githubusercontent.com/33354141/88490752-2c1b7200-cf9e-11ea-9f72-dd8c960503ec.png">

## Expected behavior

a centered X.

## Environment

- Home Assistant release with the issue: 113.1
- Last working Home Assistant release (if known): not sure, can only find screenshots without the enclosing circle
- Browser and browser version: Safari, Chrome on Mac, dont see it in the iOS App (no circle around the X)
- Operating system: HA OS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

No errors in the log
```txt

```

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/issues/6285
