### ISSUE TITLE
Gauges Not Displayed Correctly on Safari Browser 0.113.1

### ISSUE THREAD

**Issue by G8YTZ** [home-assistant/frontend#6480]
Hi, I'm seeing Lovelace gauges not displaying correctly on the Safari Browser (Up to date Catalina) OK on the same laptop with Chrome Browser and ok with MS Edge on Windows 10 HASS.IO version 113.1

<img width="367" alt="Screenshot 2020-07-28 at 15 04 14" src="https://user-images.githubusercontent.com/35895759/88676688-4d867600-d0e4-11ea-8f33-c18607f26b22.png">

**Comment by zsarnett** [comment]
#6467 Duplicate

Please search issues before creating them as you may find others have reported. Then you can +1 on the issue 😃
