### ISSUE TITLE
Default thermostat card has wrong font size for °F on Linux/Firefox causing it to be cut off

### ISSUE THREAD

**Issue by derekatkins** [home-assistant/frontend#6481]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Running HassIO/HassOS 4.11 with HA 0.113.1

The Thermostat card displayed poorly on my Firefox browser (but looks okay on Chromium).  Specifically, the "°F" to the right of the temperature is too large and gets cut off (it's much smaller on Chromium, so displays correctly).  I spoke with mono in the frontend discord and they suggested I report here.

I uploaded a screenshot to https://imgur.com/a/FJx7Xum but couldn't figure out how to pull it directly here.

## Expected behavior

I expected to see the text and not have it cut off...  Or at least have it look a little more like the image in the documentation :+1: 

## Steps to reproduce
I just used the default configuration with a thermostat and it, by default, did not display cleanly.

## Environment
I am running Linux with Firefox 70.
HassIO/HassOS 4.11
HA 0.113.1

As I mentioned earlier, it appears fine on Chromium.

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

This is my first install of HA, so I have no idea if it ever worked.

## State of relevant entities

N/A

```yaml

```

## Problem-relevant configuration

```yaml
entity: climate.master_br_therm_main
type: thermostat
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Can't replicate this on Firefox 79 (mac osx), mind updating firefox to see it that solves it?

**Comment by bramkragten** [comment]
Also working in Firefox 70 on mac osx 
![image](https://user-images.githubusercontent.com/5662298/88776871-d48c2a80-d186-11ea-95bb-daf0f4a9ebd8.png)

**Comment by derekatkins** [comment]
I'm on Linux, not a Mac.  Current distro does not have a firefox update.  I will try to run a test on another version ASAP, but I suspect it is a bug in the Linux/FF version I'm running.

**Comment by tdejneka** [comment]
FWIW, I'm unable to reproduce the reported error using Firefox 79.0 on Ubuntu 18.04. 

![Screenshot from 2020-07-29 17-22-22](https://user-images.githubusercontent.com/44732909/88855200-7a0fc000-d1c0-11ea-8055-b65b4a15fd6e.png)
