### ISSUE TITLE
Maintain comments (#) in automations.yaml after editing in the UI

### ISSUE THREAD

**Issue by woodmj74** [home-assistant/frontend#6486]
## The request

More capabilities have been added to automation's in 0.113 which are not yet surfaced fully in the UI. Some users (myself included) are more comfortable in the UI but will venture into yaml to achieve specific results. 

When editing directly in the automation.ymal it is possible to add comments in using # to comment the line out - these are especially helpful for less sophisticated users who may need these when doing subsequent maintenance to understand what is happening

![image](https://user-images.githubusercontent.com/68328701/88807286-7290ec80-d1a9-11ea-9455-ebbaf279f636.png)

However, when editing the same automation via the UI, these comments are stripped from presentation and deleted from the underlying automations.yaml file if a save is undertaken:

![image](https://user-images.githubusercontent.com/68328701/88808011-4033bf00-d1aa-11ea-9190-bd3907fa97c7.png)

The request would therefore be to retain these when presenting in the UI

## The alternatives

The alternative here is not to edit an automation with comments in the UI - the challenge is for a UI user remembering which one, this could be assisted with a prompt when editing via the UI warning this is not a native UI automation and formatting changes may be lost during editing.

Another alternative is to prevent any automations which don't fit in the UI ability of the front end from being edited. However this would go against the desire to continue to drive adoption of the UI and development of it.

**Comment by frenck** [comment]
Anything managed by the UI will not maintain comments, as it goes through a parser.
Parsers are not comment aware, this has been brought up many times, but not fixable.

**Comment by woodmj74** [comment]
Okay, understood and closed

**Comment by dmwyatt** [comment]
> Anything managed by the UI will not maintain comments, as it goes through a parser.
> Parsers are not comment aware, this has been brought up many times, but not fixable.

This isn't entirely correct. The parser being used may not be comment-aware, but there many parsers are. I know, I've written several!

>these are especially helpful for less sophisticated users

The more experienced a developer you are, the more you appreciate good comments in code!
