### ISSUE TITLE
Auto renaming entities doesnt work

### ISSUE THREAD

**Issue by Dinth** [home-assistant/frontend#6500]
## Environment

- Home Assistant Core release with the issue: 0.110.4
- Operating environment (Home Assistant/Supervised/Docker/venv): HassOS
- Integration causing this issue: ozw
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/ozw/

## Additional information

Auto renaming device's entity ID doesnt seem to work. Names of the entities do get changed, but entity ids dont. 

## Steps to reproduce.
1. Click on a device on device's list. 
2. Click a cogwheel icon 
3. Change the name to a different one
4. Click "OK" when asked if entity ID should also be changed. 
5. Names of all entities belonging to the device change, but entity ids dont get changed. 
![Screenshot 2020-06-03 at 22 00 24](https://user-images.githubusercontent.com/313674/83688520-76f3bb80-a5e5-11ea-9348-4319f529fc0c.png)

**Comment by bramkragten** [comment]
This is something the frontend does, and not related to the z-wave integration.

**Comment by bramkragten** [comment]
Can you please supply some examples without the GIF's in the following format:

# Before:
Device name: `CT32 - Instance 2` 
Entity names: `CT32: Instance 2: Air Temperature` and `CT32: Instance 2: Humidity`
Entity ids: `sensor.ct32_instance_2_temperature` and `sensor.ct32_instance_2_humidity`

# After:
Device name: `Bad`
Entity names: `CT32: Instance 2: Air Temperature` and `CT32: Instance 2: Humidity`
Entity ids: `sensor.bad_air_temperature` and `sensor.bad_humidity`

In the case above, it is correct that they are not renamed, we do an equal check between the names, and `CT32 -` !== `CT32:`.

For the entity ids, we compare the old slugged name with the new slugged name, in this case, both a `-` and a `:` are sluggified in a `_`, so they match.

**Comment by Dinth** [comment]
Just renamed Aeotec Multisensor 6 (sorry dont remember what was the original, default name), got an error, but all the nodes were renamed correctly.
![Screenshot from 2020-08-02 11-44-50](https://user-images.githubusercontent.com/313674/89121346-03bbd800-d4b6-11ea-95da-ea17a7ddef26.png)

But few days ago i've been adding and renaming multiple Fibaro Smoke Sensors, same simple names without any non-alphabetic characters and the entity names were not renamed correctly.

**Comment by Dinth** [comment]
Original device name: TZ88 Smart Energy Plug-in Switch
Original entity name: switch.tz88_smart_energy_plug_in_switch_switch

Renaming to: "Guest bedroom diffuser"
No "not a valid value" error during rename.
Entities *not* renamed.
![Screenshot from 2020-08-02 19-52-06](https://user-images.githubusercontent.com/313674/89130011-ad708880-d4f9-11ea-8978-08596464e580.png)

**Comment by Dinth** [comment]
I have just added a Conexis L1 lock
![Screenshot from 2020-08-15 13-45-29](https://user-images.githubusercontent.com/313674/90312598-a08e6480-defd-11ea-9371-b9632d806e77.png)
tried renaming it to "Main door lock" but the entities were not renamed
