### ISSUE TITLE
Econet Integration Not Working

### ISSUE THREAD

**Issue by wotelljm** [home-assistant/frontend#6504]
Econet integration indicating login failure - API token expired

Logger: pyeconet.api
Source: components/econet/water_heater.py:87
First occurred: August 1, 2020, 5:01:14 PM (2 occurrences)
Last logged: August 1, 2020, 5:01:14 PM

Authentication request failed, please check credintials. 400
Token expired.

**Comment by zsarnett** [comment]
Please fill out the issue template. Also, this sounds like a backend issue but maybe not
