### ISSUE TITLE
Markdown card editor, closes when trying to add new line

### ISSUE THREAD

**Issue by kulmegil** [home-assistant/frontend#6514]
## Checklist

- [ x ] I have updated to the latest available Home Assistant version.
- [ x ] I have cleared the cache of my browser.
- [ x ] I have tried a different browser to see if it is related to my browser.

## The problem

Markdown card UI editor closes and saves card config whenever enter is pressed in content field. 

## Expected behavior

New line is added to markdown content.

## Steps to reproduce

1. Create new or edit existing markdown card
2. Press enter when inside "content (required) field"

## Environment

- Home Assistant: 0.113.2+
- Operating system: HassOS 4.11 (clean install!)
- Last working Home Assistant release (if known): unknown
- Browser and browser version: Firefox or Chrome latest
  (no adblock style extensions enabled)

## State of relevant entities

N/A

## Problem-relevant configuration

N/A

## Javascript errors shown in your browser console/inspector

No errors or warning. 

## Additional information

Easy replicated even on clean install of Hassio in VM.

**Comment by ludeeus** [comment]
This was fixed in https://github.com/home-assistant/frontend/pull/6517 and is part of the current beta.
