### ISSUE TITLE
[Beta] Which card would you like to add to your "Home" view? on browser refresh

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/frontend#6526]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
If i refresh the browser with CTRL-F5 or close the browser and open it again, LL asks me which card i would like to add.
I'm using yaml mode.
![Auswahl_375](https://user-images.githubusercontent.com/26381449/89459846-a059d080-d769-11ea-8e1d-e264857725dc.png)

## Steps to reproduce
CTRL-F5

## Environment

- Home Assistant release with the issue: 0.114.0b0
- Last working Home Assistant release (if known): 0.113.3
- Browser and browser version: FF, Chrome an iOS
- Operating system: Ubuntu 18.04

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
lovelace:
  mode: yaml
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
Is this all the time? Or when you do a certain step? When are your refreshing? Does it matter?

**Comment by VDRainer** [comment]
Hard to see some system in it.
I would say 3 of 10 refreshes, but always on a new opened browser window.

**Comment by VDRainer** [comment]
I can also reproduce this in my play HA, which is not in yaml mode.
In a generated and a contolled dashboard.

**Comment by DavidFW1960** [comment]
Same with storage mode for me and it **_always_** does it..

**Comment by colemamd** [comment]
I receive it too on my main dashboard (yaml mode), and on my two tablets running FK with generated dashboards (storage mode)

**Comment by DavidFW1960** [comment]
ok... it's Thomas Loven's card-tools causing this issue
@thomasloven I'll open an issue...

**Comment by ludeeus** [comment]
@VDRainer Can you disable card-tools, then clear the cache and see if the issue is gone?

**Comment by VDRainer** [comment]
Yeah, removing card-tools from the resources and the issue is gone. :+1:

**Comment by ludeeus** [comment]
Then this should be followed up in the issue @DavidFW1960 opened in that repo :+1:

**Comment by thomasloven** [comment]
Just for the record - the **only** ~~good~~ reason to have card-tools installed is because another card tells you to.
None of my cards do, and if you find one that does, you should really let the maintainer know that there are better ways to get that functionality nowadays.
I'll gladly help with the transition.

**Comment by DavidFW1960** [comment]
> Just for the record - the **only** ~good~ reason to have card-tools installed is because another card tells you to.
> None of my cards do, and if you find one that does, you should really let the maintainer know that there are better ways to get that functionality nowadays.

Thanks for that.... I'll have to check my cards now and see if I do need it. I did originally - I think for your cards...

**Comment by MizterB** [comment]
> Just for the record - the **only** ~good~ reason to have card-tools installed is because another card tells you to.
> None of my cards do, and if you find one that does, you should really let the maintainer know that there are better ways to get that functionality nowadays.
> I'll gladly help with the transition.

What does this mean?  Are you suggesting that card-tools is no longer a useful utility?

**Comment by thomasloven** [comment]
It's useful for card developers. But the end user should never even have to know about it.

**Comment by MizterB** [comment]
@thomasloven to close out on your feedback "the end user should never even have to know about it"...they do have install it though - correct?  Or can I somehow reference it in my code without any dependency on the user?

**Comment by thomasloven** [comment]
The user does NOT have to install it.
How to use it is described at the very [top of the readme](https://github.com/thomasloven/lovelace-card-tools#card-developer-instructions).

However - it **can** (but shouldn't) still be used the "old" way too, where it has to be installed as a separate plugin.

**Comment by DavidFW1960** [comment]
@MizterB I see you have committed to Iantrich's secondary-info-entity-row and this is the only card I still use requiring card-tools. For some reason Ian is ignoring this issue on that card and in any case typically doesn't address issues for months anyway. Is there any way you can fix this card?

**Comment by iantrich** [comment]
> @MizterB I see you have committed to Iantrich's secondary-info-entity-row and this is the only card I still use requiring card-tools. For some reason Ian is ignoring this issue on that card and in any case typically doesn't address issues for months anyway. Is there any way you can fix this card?

😂 that's his card, not mine. Nicely done. And David, seriously don't appreciate the negativity.

**Comment by DavidFW1960** [comment]
> that's his card, not mine

oops.. my mistake.

**Comment by tomlut** [comment]
> the **only** ~good~ reason to have card-tools installed is because another card tells you to.
> None of my cards do,

Yikes. The only reason I installed it was because a couple of your cards needed it ages ago. Time to re-read the requirements of all my custom cards and check if I actually need it any more.

**Comment by balloob** [comment]
@DavidFW1960 this attitude is not an acceptable attitude in our community. This is a formal warning.
