### ISSUE TITLE
Disabled button text color in Dark Mode (0.114)

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6528]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

The new dark mode looks amazing, near perfect. The one thing I have a tiny nitpick on is the disabled button text colors. It's black on black (or a very dark gray), so makes it very hard to notice they're even there. See below screenshot for an example, you can barely see the bottom button row.

![image](https://i.imgur.com/FOglyg8.png)

## Expected behavior

I think these should be a more lighter shade of gray, so you know they're there but disabled.

## Steps to reproduce

1. Enable dark mode
2. Bring up a dialog with disabled button (Users panel)

## Environment

- Home Assistant release with the issue: 0.114.0b0
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by tleegaard** [comment]
@bramkragten - the new light grey can't be distinguished from the active (white) color in Dark mode either. In my case - with up/down buttons grouped together (for windows) - I can't tell which button is inactive.

**Comment by bramkragten** [comment]
@tleegaard please create a new issue.
