### ISSUE TITLE
Slightly cut off text in Logbook and History dropdowns

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6536]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

In the Logbook and also History page on the start/end time dropdowns at the top, the final character in AM/PM gets slightly cut off. This below screencap is from my desktop monitor with tons of free vertical space.

![image](https://i.imgur.com/JGOf3Ce.png)

## Environment

- Home Assistant release with the issue: 0.114.0b0
- Last working Home Assistant release (if known): I don't remember seeing this on 0.112 (new Logbook stuff)
- Browser and browser version: Chrome desktop
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ludeeus** [comment]
I'm not able to reproduce this with Chrome (84.0.4147.89) on Ubuntu

1000px width
![image](https://user-images.githubusercontent.com/15093472/89499748-d0808e00-d7c0-11ea-8249-9d67b43638ba.png)

2545px width
![image](https://user-images.githubusercontent.com/15093472/89499824-f27a1080-d7c0-11ea-8780-934e8568c5a9.png)

What version of chrome is this?
What resolution are you running?

You have cleared your cache right? :see_no_evil:

**Comment by SeanPM5** [comment]
I'm using Chrome version 84.0.4147.105 on macOS 10.13.6. I also tried in Microsoft Edge Canary 86.0.599.0 which I know is also Chrome on the backend, but I don't have any extensions on that so that rules it out being an extension issue I think...

It happens at every resolution for me, even at full width/full screen on my 5K resolution display. In the below screencap I made width as small as I could (narrow/mobile-style) and you can see that the time dropdowns are not using the full width like the entity dropdown below it. Is also Incognito so not cached.

![image](https://i.imgur.com/V2WmRML.png)

I could not reproduce this on Firefox 79.0 nor Safari though, both of those display it fine 🤷‍♂️

**Comment by ludeeus** [comment]
I'm able to reproduce it with double-digit days in September :D
