### ISSUE TITLE
Auto generated dashboards should not be shown in Move card dialog 0.114.0b0

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6537]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Noticed this issue while reporting https://github.com/home-assistant/frontend/issues/6535. 

In the "move card" dialog, auto generated dashboards are shown as a target, despite it not being possible to move cards into them because user hasn't taken control yet. This can be a little confusing.

![image](https://i.imgur.com/j8yeBTV.png)

## Expected behavior

 I think they should either be shown in a disabled state (like my YAML dashboard is), or filtered out completely. 

## Steps to reproduce

1. Create a new dashboard under Configuration -> Lovelace dashboards, and do not take control of it yet
2. Enter Configure UI mode on a different dashboard that you already have control of
3. Select "Move to View" on any card
4. You'll see and can select your auto-generated dashboard, despite it being impossible to move the card there

## Environment

- Home Assistant release with the issue: 0.114.0b0
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome
- Operating system: m acOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
We don't know before getting the config if the view is auto generated... 🤷‍♂️
