### ISSUE TITLE
Entity 'Related' info window hides itself on background

### ISSUE THREAD

**Issue by Repsionu** [home-assistant/frontend#6542]
## The problem

Opening any entity in Lovelace, for example this one:

[https://community-assets.home-assistant.io/original/3X/6/0/60a4b409549e72100357dda295f16051fed6a290.png](url)

And clicking the wheel :wheel_of_dharma: up right:

[[https://community-assets.home-assistant.io/original/3X/f/9/f9d920dc70145e95d07279dc171a0ca1ad467591.png](url)

followed by a click on the tab “**Related**” will give you this nice list of related entities:

[https://community-assets.home-assistant.io/optimized/3X/3/4/3475d42657c11df48bf2b76e044f2f536b6b4de9_2_277x499.png](url)

they are clickable and in the past (prior to this release 0.113) they opened the entity directly.

To view the window You have to close window in view- and repeat from beginning to view another **Related**.

## Environment

- Home Assistant Core release with the issue: 0.114b
- Last working Home Assistant Core release (if known): 0.112
- Operating environment (OS/Container/Supervised/Core): Core venv
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by ludeeus** [comment]
More context: The new dialog for the related entity opens behind the current.
