### ISSUE TITLE
Add Reload All button to server control page

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/frontend#6548]
## The request

As the ability to reload stuff keeps growing so does the list of reload buttons on the server control page.  Although not used often sometimes you may come across a time where you need to reload more than one item.  So why not just reload them all in one shot?

## The alternatives

Alternative is to click on each item that you wish to reload.

## Additional information

Its a pretty big list :)  Might want to consider alphabetizing it too
![image](https://user-images.githubusercontent.com/1634145/89562360-b483e900-d7ce-11ea-84db-da0744a5315e.png)

**Comment by bramkragten** [comment]
There is a similar feature request, with selection chips

**Comment by dshokouhi** [comment]
Oh is there? I tried searching for one but didn't see it :)

**Comment by SeanPM5** [comment]
See https://github.com/home-assistant/frontend/issues/4776 for FR / mockup I did a few months back.

Reload all button was suggested in there by Frenck but I think it was questionable whether reloading everything at once would cause things to mess up.

**Comment by dshokouhi** [comment]
@SeanPM5 I thought of that but then I noticed that with the next set of upcoming performance improvements it might be more feasible now since reloading was improved upon :) https://rc.home-assistant.io/blog/2020/08/05/release-114/#yet-another-round-of-performance-improvements

I will close this in favor of the one you linked to. Its well thought out in comparison, thank you!
