### ISSUE TITLE
Area picker icons are incorrectly vertically aligned

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#6549]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

These icons should be horizontally aligned. It's the area picker. 

![image](https://user-images.githubusercontent.com/1444314/89571159-854d9600-d827-11ea-968f-af867234dc83.png)

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
The service picker (e.g. in the tap action for a button) has the same problem as well.
