### ISSUE TITLE
Input_Numbers usability on mobile

### ISSUE THREAD

**Issue by kyleteal** [home-assistant/frontend#6553]
## The request: 

Add some way to change input numbers on mobile so that it is more user friendly. Arrows, or clearing out the current number when clicking so you only have to enter the new numbers and don’t have to erase the old ones. 

## The alternatives
Currently I just don’t change them on mobile but it would be nice if it was more user friendly 

## Additional information: 
Mainly an issue in the iOS app. They told me to come here.

**Comment by zsarnett** [comment]
Input numbers fields are based on the browser and upstream libraries. Adding arrows would be a lot of custom code and would need to be very large.
