### ISSUE TITLE
Long config entry title causes horizontal scrollbar on mobile

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#6554]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
![IMG_0668](https://user-images.githubusercontent.com/1444314/89582518-0feac100-d839-11ea-809c-256a967fee29.PNG)

Long config entry titles are not cut off. (also, we should really not have such long titles to begin with)

This is on iPhone 11.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/issues/5806
