### ISSUE TITLE
Add easy integration for attributes instead of needing a template

### ISSUE THREAD

**Issue by jvalst** [home-assistant/frontend#6560]
## The request
The possibility to easy show an attribute name instead of the state inside cards.

## The alternatives
Now this is (as my knowledge goes) only possible to make a loose template with the desired value_template. 

## Additional information
Make it so that if we need an attribute from (for example) the gps location, so we can use the entity id from the device tracker, and use the attribute "Sub Administrative Area" for example. Without the need of making a template. Just using that attribute on the entity to show up in the different cards.

**Comment by zsarnett** [comment]
This is now possible in the entity and entities cards
