### ISSUE TITLE
Uncaught TypeError: Cannot read property 'header' of null

### ISSUE THREAD

**Issue by Valiceemo** [home-assistant/frontend#6563]
## Checklist

- [ X ] I have updated to the latest available Home Assistant version.
- [ X ] I have cleared the cache of my browser.
- [ X ] I have tried a different browser to see if it is related to my browser.

## The problem

Error thrown in browser when navigating to dev tools
```
2020-08-07 13:41:29 ERROR (MainThread) [frontend.js.latest.202007160] http://<my.ip.address:8123>/frontend_latest/chunk.cf565e41b8a8dce0642a.js:133:238 Uncaught TypeError: Cannot read property 'header' of null
```

## Expected behavior

No browser errors / no home assistant errors

## Steps to reproduce

  Provide steps for us, that helps reproducing your issue.
  For example:
    1. Open developer tools
    2. Select any tab
    3. Select 'States' tab
Note: seems to also error when selecting any tab in dev tools, but the above is a sure fire way to reproduce

## Environment

- Home Assistant release with the issue: 0.113.3
- Last working Home Assistant release (if known): unknown
- Browser and browser version: Microsoft Edge 84.0.522.40 (Official build) (64-bit)
- Operating system: Windows 10

Error also occurs when navigating to the states dev tool via mobile app
- Mobile App Version: 2.1.0.239-full
- Android Version 10.
- OnePlus 7 Pro OxygenOS 10.0.7

Error also occurs when navigating to the states dev tool on mobile web browser Brave 
- Brave browser version: Beta 1.12.106
- Brave browser version: Stable 1.11.105

## State of relevant entities
N/A

## Problem-relevant configuration
N/A

## Javascript errors shown in your browser console/inspector

```txt
chunk.cf565e41b8a8dce0642a.js:1085 Uncaught TypeError: Cannot read property 'header' of null
    at HTMLElement.value (chunk.cf565e41b8a8dce0642a.js:1085)
    at g.handleEvent (app.5aafc0f2.js:1)
    at HTMLElement.__boundHandleEvent (app.5aafc0f2.js:1)
    at HTMLElement.fire (app.5aafc0f2.js:1)
    at HTMLElement._itemActivate (chunk.582a2968cc36c6302d0b.js:1)
    at HTMLElement._activateHandler (chunk.582a2968cc36c6302d0b.js:1)
    at HTMLElement._activateHandler (chunk.582a2968cc36c6302d0b.js:1)
    at HTMLElement._activateHandler (chunk.3c74f20a8b5ae6c404d8.js:1016)
    at HTMLElement.<anonymous> (app.5aafc0f2.js:1)
    at R (app.5aafc0f2.js:1)

  value @ chunk.cf565e41b8a8dce0642a.js:1085
  handleEvent @ app.5aafc0f2.js:1
  __boundHandleEvent @ app.5aafc0f2.js:1
  fire @ app.5aafc0f2.js:1
  _itemActivate @ chunk.582a2968cc36c6302d0b.js:1
  _activateHandler @ chunk.582a2968cc36c6302d0b.js:1
  _activateHandler @ chunk.582a2968cc36c6302d0b.js:1
  _activateHandler @ chunk.3c74f20a8b5ae6c404d8.js:1016
  (anonymous) @ app.5aafc0f2.js:1
  R @ app.5aafc0f2.js:1
  M @ app.5aafc0f2.js:1
  click @ app.5aafc0f2.js:1
  A @ app.5aafc0f2.js:1

```

**Comment by bramkragten** [comment]
Duplicate and already fixed

**Comment by Valiceemo** [comment]
> Duplicate and already fixed

Ah ok
Is the fix due in the next release?
Apologies for the duplicate

**Comment by bramkragten** [comment]
It is in the current beta

**Comment by Valiceemo** [comment]
> It is in the current beta

Got ya. 
I'm not running the beta, so I'll wait for the next release.
Thanks and sorry again fornthe duplicate issue.
