### ISSUE TITLE
Badges View Configuration very narrow width, causes entities to only be partially readable (0.114)

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6568]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The "View Configuration" dialog in 0.114.0b has a very narrow width, this causes many entities to be only partially readable. 

You can easily see and reproduce this on the demo. In the below screenshots the entity is `binary_sensor.door_window_sensor_158d0001bf26df` yet you cannot read the name in the dropdown nor after it's selected.

<img width="470" alt="Screen Shot 2020-08-07 at 5 50 35 PM" src="https://user-images.githubusercontent.com/9065557/89691328-b2a54d00-d8d6-11ea-8dcd-244023425466.png">
<img width="450" alt="Screen Shot 2020-08-07 at 5 53 15 PM" src="https://user-images.githubusercontent.com/9065557/89691427-ef714400-d8d6-11ea-9eb2-f6f18d038440.png">

Additional notes: The "Settings" tab on the same exact dialog has a larger width, as soon as you switch to Badges it notably shrinks in size.

## Steps to reproduce

1. Open demo
2. Configure UI
3. Edit a view
4. On the View Configuration dialog, select Badges tab

## Environment

- Home Assistant release with the issue: 0.114.0b2
- Last working Home Assistant release (if known): 0.113 (I think)
- Browser and browser version: Chrome stable
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ludeeus** [comment]
Even if it used the full width in the dialog (600px), the entity ID `binary_sensor.door_window_sensor_158d0001bf26df` would be cut :thinking:
