### ISSUE TITLE
In 0.114 Light/Dark mode selector does not show if custom themes are set for both dark and light mode

### ISSUE THREAD

**Issue by gadgetchnnel** [home-assistant/frontend#6572]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

If the **frontend.set_theme** service is called to set custom default themes for both Light and Dark mode and the Backend-selected theme is selected, the options to switch manually between the Light and Dark mode are not shown:

![image](https://user-images.githubusercontent.com/2099542/89710730-75e06100-d97d-11ea-8e1c-d80f4f54cb67.png)

It still automatically switches between the two themes, so it appears to be defaulting to Auto but with no way to manually change mode.

## Expected behavior

The Light/Dark mode selector should be shown, as below (this is how it shows with **default** as the Light mode theme):

![image](https://user-images.githubusercontent.com/2099542/89710840-3b2af880-d97e-11ea-8aeb-3452f8f1dfc7.png)

## Steps to reproduce

1. Call the frontend.set_theme service as follows to set the Light and Dark theme:

```
- service: frontend.set_theme
  service_data
    name: Name of Light Theme
    mode: light
- service: frontend.set_theme
  service_data
    name: Name of Dark Theme
    mode: dark
```
See that the Light/Dark mode selector is not shown (as in the first screenshot).

2. Call the frontend.set_theme service as follows to set the Light theme to default:

```
- service: frontend.set_theme
  service_data
    name: default
    mode: light
```

## Environment

- Home Assistant release with the issue: 0.114.0b2
- Last working Home Assistant release (if known):
- Browser and browser version: Google Chrome 84.0.4147.105
- Operating system: macOS Mojave 10.14.6

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ludeeus** [comment]
This is expected, they will only show if no theme is selected or the selected theme in use is "default".

**Comment by gadgetchnnel** [comment]
It's a little confusing that it shows if you are using Backend-selected with a custom theme defined for Dark mode but "default" for Light mode. If it shouldn't show if you have a custom theme, then should it not also apply in that case?

**Comment by bramkragten** [comment]
The default theme can be light and dark, so whenever the default theme is active you can change that in dark/light. Other themes don't have these options so would need to choose a different theme to make it dark or light.

I agree the auto doesn't make sense when a backend dark mode is set and you have it set to backend selected.

**Comment by mrand** [comment]
@gadgetchnnel, is there a second (minor) bug here that the deselected radio buttons next to light and dark don't show up?  Or is that an oversight in your custom theme?

**Comment by ludeeus** [comment]
That's a custom theme, it shows correctly with the default dark theme:
![image](https://user-images.githubusercontent.com/15093472/89943979-641de880-dc1f-11ea-8f20-197cd10f3fb3.png)
