### ISSUE TITLE
Device dashboard assumes percentage unit for battery

### ISSUE THREAD

**Issue by elupus** [home-assistant/frontend#6575]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Device dashboard assumes the battery sensor has a percentage unit instead of getting unit from the entity.

https://github.com/home-assistant/frontend/blob/f8c5eeab5db76f2a14b6c8b51ddb045049d53599/src/panels/config/devices/ha-config-devices-dashboard.ts#L222

This leads to invalid display if entity can only report batter state (low, full).

## Expected behavior

Unit should follow the unit defined by the entity.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

This was found when I was working with battery status of rfxtrx entities. They report a value about full, good, low. Rather than a percentage. It's now mapped to a percentage, which is fine, but still think this should respect unit of the entity.

**Comment by elupus** [comment]
Still valid

**Comment by MartinHjelmare** [comment]
We also support binary battery sensors, so we need to handle that too:
https://developers.home-assistant.io/docs/core/entity/binary-sensor#available-device-classes

**Comment by elupus** [comment]
IMHO the bug remains. It should grab the unit from the state?
