### ISSUE TITLE
Configuration tab background is dark even with light mode enabled

### ISSUE THREAD

**Issue by duncanbarnes** [home-assistant/frontend#6584]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Under 0.114.0b3 (updated from b1), when OS is set to dark mode but profile is explicitly set for light mode, clicking on the 'Configuration' tab presents the GUI with a dark background but white buttons. Text on the left is still there but the background colour appears to come from the dark mode.

Clicking further into the configuration menu (e.g. Integrations) results in a white background, its just the initial configuration view which appears to have this behaviour.

![image](https://user-images.githubusercontent.com/4053079/89776681-473fc300-db02-11ea-9175-8cd9b47533b7.png)

## Expected behavior

If theme selector is set to light mode explicitly rather than auto and browser OS is set to dark mode, all elements of the GUI should use light mode. In all other sections that I have found they do, its just the initial Configuration tab which does not.

## Steps to reproduce

1. Set profile theme explicitly to light mode
2. In mac OS, Preferences > General set appearance to dark mode
2. Access configuration tab

## Environment

- Home Assistant release with the issue: 0.114.0b3
- Last working Home Assistant release (if known): Believe this was fine under 114.0b1 but can't be 100% sure
- Browser and browser version: Behaviour seen in Safari 13.1.2 and Chrome 84.0.4147.105
- Operating system: Mac OS 10.15.6 with dark mode enabled

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
Confirmed on Windows Chrome .114.B4

**Comment by duncanbarnes** [comment]
This appears to go further than I originally flagged in the issue, for instance, in Developer tools, initially the background colour is correct, however, if you scroll down then the background changes to the dark theme colour, see screenshot below which is part scrolled. This behaviour seen on:

- Developer Tools > States
- Developer Tools > Template
- Developer Tools > Events

It does not appear to be an issue within the Supervisor panels. When reloading pages it is possible to get a small flash of black which suggests there are elements underneath with this style.

![image](https://user-images.githubusercontent.com/4053079/89835207-3623a000-db5c-11ea-9505-65bcf7b6c8af.png)
