### ISSUE TITLE
supervisor dashboard not honoring theme set

### ISSUE THREAD

**Issue by nickidw** [home-assistant/frontend#6600]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

The Supervisor part of the front end does not honor the selected theme, it's using the default theme to render.
## Expected behavior

Supervisor should be rendered with the same theme as the rest of the front-end

## Steps to reproduce

Navigate to main dashboard - observe theme
Navigate to Supervisor section- observe selected theme is not honored

## Environment

- Home Assistant release with the issue: 113.3
- Last working Home Assistant release (if known): 113.0
- Browser and browser version: Brave 1.11.104, Chrome 84.0.4147.105
- Operating system: HassOS 4.12

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
![image](https://user-images.githubusercontent.com/12016514/90006800-e4812f80-dc99-11ea-9985-291579276612.png)
![image](https://user-images.githubusercontent.com/12016514/90006829-f4007880-dc99-11ea-9336-2c503eac134c.png)

**Comment by ludeeus** [comment]
What version of the supervisor is this?
Paste any output you see in the console of your browser.

**Comment by nickidw** [comment]
> What version of the supervisor is this? 
231
> Paste any output you see in the console of your browser.
 The console output contains nothing

**Comment by ludeeus** [comment]
There is no reason that should not work.
![image](https://user-images.githubusercontent.com/15093472/90009927-41cbaf80-dc9f-11ea-8f7c-77fbdc02b73b.png)

This is the same versions (mostly)
Try another theme, I used this one to test https://github.com/aFFekopp/noctis

**Comment by nickidw** [comment]
I have an automation on startup that sets the theme to blue-night, so my user theme is set to Backend-selected. this renders incorrectly in Supervisor. If I fire the automation again to set the theme, no change. If I change my user theme to blue-night instead of Backend-selected, it displays correctly.

**Comment by nickidw** [comment]
I installed noctis, restarted homeassistant and it also does not render on the supervisor page unless I set my user theme to noctis from Backend-selected. Even fired the automation to set the theme, no change.

**Comment by nickidw** [comment]
Issue resolved by upgrading to 114.0

**Comment by ludeeus** [comment]
That works too, but #6603 resolves it.

**Comment by nickidw** [comment]
Thank you for the quick response.
