### ISSUE TITLE
No way to remove frontend.set_theme mode: option

### ISSUE THREAD

**Issue by tomlut** [home-assistant/frontend#6608]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

There is no way to undo setting a light or dark theme with the frontend.set_theme service after using the mode: option.
## Expected behavior
Ability to go back to automation only controlled theming on my device.

## Steps to reproduce
Have the profile theme option set to backend selected.
Call the frontend.set_theme service with the mode: option set to light or dark.
It is now not possible to undo this and go back to automation controlled theming. The device will ignore the frontend.set_theme service (without mode: option) and only display a theme based on the previous mode setting and device light/dark state.

## Environment

- Home Assistant release with the issue: 0.114.0
- Last working Home Assistant release (if known): none
- Browser and browser version: iOS app
- Operating system: iOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Use default or none as value
