### ISSUE TITLE
Disabled button text color in Dark Mode (0.114)

### ISSUE THREAD

**Issue by tleegaard** [home-assistant/frontend#6615]
As stated in https://github.com/home-assistant/frontend/issues/6528#issuecomment-673677707 the inactive color (light grey) is too similar to the active color (white) when in Dark Mode:
![image](https://user-images.githubusercontent.com/5439041/90222820-1d8de100-de0d-11ea-9351-ec40e54b8b21.png)
(active on left, inactive on right)

**Comment by spacegaier** [comment]
There was a code change two days ago, that added a darker color: https://github.com/home-assistant/frontend/pull/6694

That's how it looks for me currently.

![image](https://user-images.githubusercontent.com/114137/91441858-38327200-e871-11ea-86c0-566cad7fef89.png)

And one more with all three states / gray tones: Active text, secondary text and disabled text:

![image](https://user-images.githubusercontent.com/114137/91441881-41234380-e871-11ea-8713-bd217415cc5c.png)

**Comment by spacegaier** [comment]
I played around with making it even darker (#505050), but not sure if that offers much:

![image](https://user-images.githubusercontent.com/114137/91442047-89426600-e871-11ea-85c9-efb9e56fe2b5.png)

**Comment by bramkragten** [comment]
This is already fixed? That is why the original issue was closed.
