### ISSUE TITLE
Add "New device added" confirmation in ZHA

### ISSUE THREAD

**Issue by JuanMTech** [home-assistant/frontend#6620]
### The request
When pairing new devices to ZHA, there is no confirmation that the device is added after the card with the new device pops up. 
A suggestion would be to add confirmation, in green, at the top. The confirmation could say, ***"New device added!"*** and a checkmark next to it. The confirmation could stay there until the user leaves the window, or it could remain active for like 30 seconds. 

## Mockup image
![ZHA new device confirmation](https://i.imgur.com/Zrf2Zxw.png)

## Additional information

**Comment by bramkragten** [comment]
All devices that are shown in this screen are newly added. I don't really understand the request or current problem.

**Comment by zsarnett** [comment]
I think it would be best if we put them in a row with a divider from the circular progress just from a UI perspective. They are kind of just floating there

**Comment by JuanMTech** [comment]
Let's put it this way. When a new device is discovered in Home Assistant, you get a card in the Integrations tab and buttons to **Ignore** it or **Configure** it. It's not automatically added.

Now, in ZHA, when you click on the **+** button to add a new device, the card pops up. However the first assumption that a user makes is that the card is for the device **discovered**. Not that it was automatically added.

So, like I was when I first started using ZHA, after the card popped up. I was thinking *" That's it? Is it added? Am I done?"* 

So, for a common user, I think a small confirmation would help a lot.
