### ISSUE TITLE
Dark Mode unreadable for some items

### ISSUE THREAD

**Issue by G8YTZ** [home-assistant/frontend#6622]
1. Cover indications don't show grey/white in "dark" mode (comparison shown in light and dark modes)
2. Maps unreadable in "dark" mode.

Examples below (shown on Safari, iPhone app is the same)

![IMG_1293](https://user-images.githubusercontent.com/35895759/90293686-91b39d80-de7c-11ea-86fa-c3d04b415416.PNG)
![IMG_1292](https://user-images.githubusercontent.com/35895759/90293690-94ae8e00-de7c-11ea-877b-638a55b270e1.PNG)
<img width="294" alt="Screenshot 2020-08-14 at 22 21 38" src="https://user-images.githubusercontent.com/35895759/90293715-a3954080-de7c-11ea-847d-fcbe5488ce1d.png">

**Comment by jellevervloessem** [comment]
I noticed also that on the Cover, the arrows are hard to distinguish. If a cover is open, it's up-arrow is gray, and the down-arrow is black:
![image](https://user-images.githubusercontent.com/6337073/91137021-c6122f80-e6ae-11ea-9477-3745162ec798.png)
In Dark mode, its hard distinguish:
![image](https://user-images.githubusercontent.com/6337073/91137494-e80bb200-e6ae-11ea-9ef8-87aad01a1588.png)

**Comment by bramkragten** [comment]
For the dark mode carts, we use these <https://carto.com/help/building-maps/basemap-list/#carto-vector-basemaps> so there is not much we can do there.

**Comment by skandalfo** [comment]
The dark-mode maps are what breaks the dark theme for me. No contrast at all.

Can this be fixed by some liberal application of the CSS "filter" property? 

e.g.: This, applied via the dev console in Chrome:

```css
filter: invert(1) brightness(2.8) contrast(1.2);
```

Automatically made OSM from the light theme look "dark", but still way more readable than the current dark theme.

My hacking around meant that the overlays got filtered too, but I'm assuming that can be fixed with some work?

**Comment by barrymossel** [comment]
Nothing on this? The map in dark mode is almost unusable...

**Comment by avviano** [comment]
I really love the dark UI in Home Assistant! Seriously Awesome!!! 

... But the map in Dark Mode is totally unusable, please fix: Either make it lighter so we can distinguish features or make option available to set to "normal" or "white" or "color". 

Keep up the good work! 
Cheers

**Comment by bramkragten** [comment]
If someone finds some nice dark mode tiles for Leaflet that we are allowed to use, we are very much open to that. Please continue this discussion in #9493, as this issue is closed.
