### ISSUE TITLE
Cannot see checkmark on Entity dropdowns in Dark Mode

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6624]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Found one more small issue with dark mode, where the checkmark that indicates your selected item is not visible (because it's black on black). This issue occurs in the following places (possibly more):

1. Developer Tools -> States (Entity dropdown)
2. Logbook (Entity dropdown)
3. Lovelace card editors (Entities dropdowns)

![image](https://i.imgur.com/XtqBSBp.png)

## Expected behavior

Checkmark should use primary text color / be white.

## Steps to reproduce

Go to any of the three sections listed above, select an entity from the dropdown, then click the dropdown again. You will not be able to see the checkmark too well.

## Environment

- Home Assistant release with the issue: 0.114
- Last working Home Assistant release (if known): n/a
- Browser and browser version: latest Chrome stable
- Operating system: macOS 10.15.6

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ludeeus** [comment]
Not fair @SeanPM5, you said you found them all :joy: 
Good job :+1: :medal_sports:
