### ISSUE TITLE
Magic Home LEDS wont turn on with flux_led platform

### ISSUE THREAD

**Issue by nytram-md** [home-assistant/frontend#6633]
## Checklist

- [Yes ] I have updated to the latest available Home Assistant version.
- [Yes ] I have cleared the cache of my browser.
- [Yes ] I have tried a different browser to see if it is related to my browser.

## Environment

- Home Assistant release with the issue: All that I have used them in.
- Last working Home Assistant release (if known): Never (that I have known)
- Browser and browser version: Tried my 3 usual ones, Chrome, Edge and Internet Explorer....All versions of last 6 months
- Operating system: Windows 10 

## State of relevant entities

```yaml

```

## Problem-relevant configuration

I dont know the actual problem but after reviewing quite a few posts in various forurms and facebook groups. It was narrowed down to replacing the light.py file. I did this from the github page below and this fixed my issue. I created a flux_led folder under custom_components and dropped the 3 files in there and rebooted. As soon as I did this. I could now turn on the Magic Home controlled LEDs and also control them as I should including changing effects and turning them off
[flux_led.zip](https://github.com/home-assistant/frontend/files/5080239/flux_led.zip)

https://github.com/CorneliousJD/flux_led

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ludeeus** [comment]
Please reopen this issue in the homeassistant/core repo, that is the issue tracker for integrations.
