### ISSUE TITLE
KeePass fields at login

### ISSUE THREAD

**Issue by VictorLamoine** [home-assistant/frontend#6637]
## The request
I would like KeePassCX-Browser extension to be able to fill the credentials fields.

![Screenshot_20200817_114859](https://user-images.githubusercontent.com/5566160/90383001-d8251a00-e07f-11ea-8b37-bc20b6deb916.png)

## Additional information
Currently the fields cannot be selected manually with the browser extension.

**Comment by SeanPM5** [comment]
This is a known issue with the login page, no password managers work on it currently. See https://github.com/home-assistant/frontend/issues/3133 and https://github.com/home-assistant/frontend/issues/1622 for example.
