### ISSUE TITLE
can't add onvif unused entities

### ISSUE THREAD

**Issue by xuefer** [home-assistant/frontend#6639]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.
tested with Chrome but sorry, IE not supported, Edge stuck in "auth/authorize" with text "Initializing", no more browser

## The problem

entity(ies) not added
list not reloaded
nothing happens if following specified steps

## Expected behavior

entity(ies) should be added to love lance ui
list reloaded

## Steps to reproduce

1. "configure UI" -> "unused entities"
2. tick any check box (not the icon) of unused entity of ONVIF integration
3. in "We created a suggestion for you", click the preview image (this is the key condition)
4. click "add to lovelance ui“

## Environment

- Home Assistant release with the issue: 0.114.1
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Version 84.0.4147.125 (Official Build) (64-bit)
- Operating system: Windows 10 x64

## State of relevant entities

N/A

## Problem-relevant configuration

N/A

## Javascript errors shown in your browser console/inspector

no error reported

## Additional information
N/A

**Comment by bramkragten** [comment]
Duplicate of https://github.com/home-assistant/frontend/issues/6640

**Comment by xuefer** [comment]
please reopen this issue, it's not the same steps, not same bug

**Comment by bramkragten** [comment]
The issue is not really clear, could you clarify by maybe adding screenshots of the steps?

**Comment by bramkragten** [comment]
Anything in your console?

**Comment by xuefer** [comment]
step 2:
![1](https://user-images.githubusercontent.com/1741312/90429310-0c3c2180-e0f8-11ea-84ff-4a77ff550e9d.png)

step 3:
![2](https://user-images.githubusercontent.com/1741312/90429391-38f03900-e0f8-11ea-8d06-b81a4d41b527.png)

**Comment by xuefer** [comment]
bug won't be reproduced if you skip (don't) clicking on any image but goes straight for "add to lovelance ui"
