### ISSUE TITLE
unused entities UI overflow with ovinf

### ISSUE THREAD

**Issue by xuefer** [home-assistant/frontend#6640]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.
tested with Chrome but sorry, IE not supported, Edge stuck in "auth/authorize" with text "Initializing", no more browser

## The problem

can't see "add to lovelance ui“, the box is out of visual area, no scroll bar

## Expected behavior

let me click "add to lovelance ui“, provided with scrollbar

## Steps to reproduce

1. "configure UI" -> "unused entities"
2. tick multiple check box of unused entity of ONVIF integration
since it load many preview images, dialog box is squeeze bigger than visual area but no scroll bar is provided

## Environment

- Home Assistant release with the issue: 0.114.1
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Version 84.0.4147.125 (Official Build) (64-bit)
- Operating system: Windows 10 x64

## State of relevant entities

N/A

## Problem-relevant configuration

N/A

## Javascript errors shown in your browser console/inspector

no error reported

## Additional information
N/A

**Comment by bramkragten** [comment]
A screenshot would be really helpful in this case.

**Comment by xuefer** [comment]
problem was reproduced in 0.113 but seems fixed since 0.114.1

**Comment by xuefer** [comment]
actually it still happen, only if browser cache is cleared.
dimension of the pictures is used to calculate the size of dialog box BEFORE pictures get loaded(and resized, taking more space)

**Comment by xuefer** [comment]
![resized](https://user-images.githubusercontent.com/1741312/90429271-faf31500-e0f7-11ea-8288-dd4698fec8be.png)

**Comment by bramkragten** [comment]
OK, this should be fixed when the dialog is migrated to `ha-dialog`.
