### ISSUE TITLE
no "+" button in unused entities UI

### ISSUE THREAD

**Issue by xuefer** [home-assistant/frontend#6641]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.
tested with Chrome but sorry, IE not supported, Edge stuck in "auth/authorize" with text "Initializing", no more browser

## The problem

can't see "+“

## Expected behavior

show "+" button

## Steps to reproduce

1. "configure UI"
-> "+" button is shown
2. open "unused entities"
-> "+" button is hidden

## Environment

- Home Assistant release with the issue: 0.114.1
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Version 84.0.4147.71 (not reproduced with the app)
- Operating system: iOS, phone screen size (not reproduced with Windows 10, PC screen size)

## State of relevant entities

N/A

## Problem-relevant configuration

N/A

## Javascript errors shown in your browser console/inspector

no error reported

## Additional information
N/A

**Comment by bramkragten** [comment]
The buttons shows up as soon as you select an entity.

**Comment by xuefer** [comment]
oh yes, you're right
