### ISSUE TITLE
Using both HDMI on RPi 4

### ISSUE THREAD

**Issue by motionthings** [home-assistant/frontend#6659]
## The request

 The RPi 4 has two HDMI outputs.
Would it be possible for one of them to run an actual web browser (Chromium?)

I want to use the second output to show a Netflix iFrame or anything else online.

## The alternatives

The alternative is to run a second RPi that connects to the Home Assistant.
In my opinion an RPi 4 is more than capable enough to do both running a browser and home automation.
The SoC has hardware encoding/decoding of H.264 and H.265 built in.

## Additional information
My "problem" is that I need two RPi's to accomplish what I want.
With a properly cooled RPi 4 it should be possible to do both on one RPi4?

**Comment by zsarnett** [comment]
This is not a frontend FR
