### ISSUE TITLE
Blink Integration Sensors Not Updating Temp or Motion

### ISSUE THREAD

**Issue by scacace** [home-assistant/frontend#6683]
## Checklist

- [Y ] I have updated to the latest available Home Assistant version.
- [ Y] I have cleared the cache of my browser.
- [Y ] I have tried a different browser to see if it is related to my browser.

## The problem

State History of Temp and Motion Detection pegged at a fixed value until HA Restart.  Unrelated to Validation issue as PIN sent via daily annoyance email via developer tool state send PIN.

## Expected behavior

Sensors to Match Blink App reported value, and reflected in state history, as changes occur..Currently useless to use.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
This is not a frontend issue, please create an in the core repo. Please also fill out the issue template.
