### ISSUE TITLE
Can't restore snapshot with chrome

### ISSUE THREAD

**Issue by sawo69** [home-assistant/frontend#6686]
**Home Assistant release with the issue:**

114.3
**Operating environment (HassOS/Generic):**

* Proxmox  VE 6.2.11

arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.12
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.56
python_version | 3.8.3
supervisor | 235
timezone | UTC
version | 0.114.3
virtualenv | false

* Debian 10
arch | x86_64
-- | --
chassis | laptop
dev | false
docker | true
docker_version | 19.03.12
hassio | true
host_os | Debian GNU/Linux 10 (buster)
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 4.19.0-10-amd64
python_version | 3.8.3
supervisor | 235
timezone | UTC
version | 0.114.3
virtualenv | false

**Supervisor logs:**

**Proxmox**
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[08:34:07] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
20-08-23 08:34:09 INFO (MainThread) [__main__] Initialize Supervisor setup
20-08-23 08:34:09 INFO (MainThread) [supervisor.bootstrap] Initialize Supervisor Sentry
20-08-23 08:34:09 INFO (MainThread) [supervisor.bootstrap] Setup coresys for machine: qemux86-64
20-08-23 08:34:09 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attach to Supervisor homeassistant/amd64-hassio-supervisor with version 235
20-08-23 08:34:09 INFO (MainThread) [__main__] Setup Supervisor
20-08-23 08:34:09 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1
20-08-23 08:34:09 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: org.freedesktop.hostname1 - /org/freedesktop/hostname1
20-08-23 08:34:09 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: de.pengutronix.rauc - /
20-08-23 08:34:09 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: org.freedesktop.NetworkManager - /org/freedesktop/NetworkManager/DnsManager
20-08-23 08:34:09 INFO (MainThread) [supervisor.host.info] Update local host information
20-08-23 08:34:09 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-08-23 08:34:09 INFO (MainThread) [supervisor.host.services] Update service information
20-08-23 08:34:09 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-08-23 08:34:09 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-08-23 08:34:09 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-08-23 08:34:09 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-08-23 08:34:09 INFO (MainThread) [supervisor.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
20-08-23 08:34:09 INFO (MainThread) [supervisor.host.services] Reload local service hassos-apparmor.service
20-08-23 08:34:09 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ReloadOrRestartUnit on /org/freedesktop/systemd1
20-08-23 08:34:09 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-dns with version 9
20-08-23 08:34:09 INFO (MainThread) [supervisor.plugins.dns] Start CoreDNS plugin
20-08-23 08:34:09 INFO (MainThread) [supervisor.misc.forwarder] Start DNS port forwarding to 172.30.32.3
20-08-23 08:34:09 INFO (SyncWorker_0) [supervisor.docker.interface] Clean hassio_dns application
20-08-23 08:34:10 INFO (SyncWorker_0) [supervisor.docker.dns] Start DNS homeassistant/amd64-hassio-dns with version 9 - 172.30.32.3
20-08-23 08:34:10 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
20-08-23 08:34:10 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-audio with version 17
20-08-23 08:34:10 INFO (MainThread) [supervisor.plugins.audio] Start Audio plugin
20-08-23 08:34:10 INFO (SyncWorker_0) [supervisor.docker.interface] Clean hassio_audio application
20-08-23 08:34:11 INFO (SyncWorker_0) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 17 - 172.30.32.4
20-08-23 08:34:11 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-cli with version 25
20-08-23 08:34:11 INFO (MainThread) [supervisor.plugins.cli] Start cli plugin
20-08-23 08:34:11 INFO (SyncWorker_0) [supervisor.docker.interface] Clean hassio_cli application
20-08-23 08:34:11 INFO (SyncWorker_0) [supervisor.docker.cli] Start CLI homeassistant/amd64-hassio-cli with version 25 - 172.30.32.5
20-08-23 08:34:11 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-multicast with version 2
20-08-23 08:34:11 INFO (MainThread) [supervisor.plugins.multicast] Start Multicast plugin
20-08-23 08:34:12 INFO (SyncWorker_0) [supervisor.docker.interface] Clean hassio_multicast application
20-08-23 08:34:12 INFO (SyncWorker_0) [supervisor.docker.multicast] Start Multicast homeassistant/amd64-hassio-multicast with version 2 - Host
20-08-23 08:34:12 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-08-23 08:34:12 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/qemux86-64-homeassistant with version 0.114.3
20-08-23 08:34:12 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /
20-08-23 08:34:12 INFO (MainThread) [supervisor.hassos] Detect HassOS 4.12 / BootSlot A
20-08-23 08:34:12 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/core repository
20-08-23 08:34:12 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/a0d7b954 repository
20-08-23 08:34:12 INFO (MainThread) [supervisor.store] Load add-ons from store: 66 all - 66 new - 0 remove
20-08-23 08:34:12 INFO (MainThread) [supervisor.addons] Found 2 installed add-ons
20-08-23 08:34:12 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-samba with version 9.2.0
20-08-23 08:34:12 INFO (SyncWorker_1) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-ssh with version 8.6.0
20-08-23 08:34:13 INFO (MainThread) [supervisor.snapshots] Found 1 snapshot files
20-08-23 08:34:13 INFO (MainThread) [supervisor.discovery] Load 0 messages
20-08-23 08:34:13 INFO (MainThread) [supervisor.ingress] Load 5 ingress session
20-08-23 08:34:13 INFO (MainThread) [supervisor.misc.secrets] Load Home Assistant secrets: 1
20-08-23 08:34:13 INFO (MainThread) [__main__] Run Supervisor
20-08-23 08:34:13 INFO (MainThread) [supervisor.api] Start API on 172.30.32.2
20-08-23 08:34:13 INFO (MainThread) [supervisor.utils.gdbus] Call de.pengutronix.rauc.Installer.Mark on /
20-08-23 08:34:13 INFO (MainThread) [supervisor.hassos] Rauc: A - marked slot kernel.0 as good
20-08-23 08:34:13 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' start 0 add-ons
20-08-23 08:34:13 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SYSTEM' start 0 add-ons
20-08-23 08:34:13 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SERVICES' start 2 add-ons
20-08-23 08:34:13 INFO (SyncWorker_0) [supervisor.docker.interface] Clean addon_core_samba application
20-08-23 08:34:13 INFO (SyncWorker_0) [supervisor.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 9.2.0
20-08-23 08:34:13 INFO (SyncWorker_0) [supervisor.docker.interface] Clean addon_core_ssh application
20-08-23 08:34:14 INFO (SyncWorker_0) [supervisor.docker.addon] Start Docker add-on homeassistant/amd64-addon-ssh with version 8.6.0
20-08-23 08:34:19 INFO (SyncWorker_1) [supervisor.docker.interface] Start homeassistant
20-08-23 08:34:19 INFO (MainThread) [supervisor.homeassistant] Wait until Home Assistant is ready
20-08-23 08:34:29 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-08-23 08:34:29 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance
20-08-23 08:34:29 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.APPLICATION' start 0 add-ons
20-08-23 08:34:29 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
20-08-23 08:34:29 INFO (MainThread) [supervisor.misc.hwmon] Started Supervisor hardware monitor
20-08-23 08:34:29 INFO (MainThread) [supervisor.core] Supervisor is up and running
20-08-23 08:34:29 INFO (MainThread) [supervisor.host.info] Update local host information
20-08-23 08:34:29 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-08-23 08:34:29 INFO (MainThread) [supervisor.host.services] Update service information
20-08-23 08:34:29 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-08-23 08:34:29 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-08-23 08:34:29 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-08-23 08:34:29 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information

**Debian:**
s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[14:32:35] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
20-08-22 14:32:37 INFO (MainThread) [__main__] Initialize Supervisor setup
20-08-22 14:32:38 INFO (MainThread) [supervisor.bootstrap] Initialize Supervisor Sentry
20-08-22 14:32:38 INFO (MainThread) [supervisor.bootstrap] Setup coresys for machine: qemux86-64
20-08-22 14:32:38 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attach to Supervisor homeassistant/amd64-hassio-supervisor with version 235
20-08-22 14:32:38 INFO (MainThread) [__main__] Setup Supervisor
20-08-22 14:32:38 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1
20-08-22 14:32:38 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: org.freedesktop.hostname1 - /org/freedesktop/hostname1
20-08-22 14:32:38 WARNING (MainThread) [supervisor.dbus.rauc] Host has no rauc support. OTA updates have been disabled.
20-08-22 14:32:38 INFO (MainThread) [supervisor.utils.gdbus] Connect to dbus: org.freedesktop.NetworkManager - /org/freedesktop/NetworkManager/DnsManager
20-08-22 14:32:38 INFO (MainThread) [supervisor.host.info] Update local host information
20-08-22 14:32:38 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-08-22 14:32:38 INFO (MainThread) [supervisor.host.services] Update service information
20-08-22 14:32:38 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-08-22 14:32:38 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-08-22 14:32:38 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-08-22 14:32:38 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information
20-08-22 14:32:38 INFO (MainThread) [supervisor.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
20-08-22 14:32:38 INFO (MainThread) [supervisor.host.services] Reload local service hassio-apparmor.service
20-08-22 14:32:38 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ReloadOrRestartUnit on /org/freedesktop/systemd1
20-08-22 14:32:38 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-dns with version 9
20-08-22 14:32:38 INFO (MainThread) [supervisor.plugins.dns] Start CoreDNS plugin
20-08-22 14:32:38 INFO (MainThread) [supervisor.misc.forwarder] Start DNS port forwarding to 172.30.32.3
20-08-22 14:32:39 INFO (SyncWorker_0) [supervisor.docker.dns] Start DNS homeassistant/amd64-hassio-dns with version 9 - 172.30.32.3
20-08-22 14:32:39 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
20-08-22 14:32:39 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-audio with version 17
20-08-22 14:32:39 INFO (MainThread) [supervisor.plugins.audio] Start Audio plugin
20-08-22 14:32:39 INFO (SyncWorker_0) [supervisor.docker.audio] Start Audio homeassistant/amd64-hassio-audio with version 17 - 172.30.32.4
20-08-22 14:32:39 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-cli with version 25
20-08-22 14:32:39 INFO (MainThread) [supervisor.plugins.cli] Start cli plugin
20-08-22 14:32:40 INFO (SyncWorker_0) [supervisor.docker.cli] Start CLI homeassistant/amd64-hassio-cli with version 25 - 172.30.32.5
20-08-22 14:32:40 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/amd64-hassio-multicast with version 3
20-08-22 14:32:40 INFO (MainThread) [supervisor.plugins.multicast] Start Multicast plugin
20-08-22 14:32:40 INFO (SyncWorker_0) [supervisor.docker.multicast] Start Multicast homeassistant/amd64-hassio-multicast with version 3 - Host
20-08-22 14:32:40 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-08-22 14:32:40 INFO (SyncWorker_0) [supervisor.docker.interface] Attach to homeassistant/qemux86-64-homeassistant with version 0.114.3
20-08-22 14:32:40 INFO (MainThread) [supervisor.hassos] No Home Assistant Operating System found
20-08-22 14:32:41 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/core repository
20-08-22 14:32:41 INFO (MainThread) [supervisor.store.git] Load add-on /data/addons/git/a0d7b954 repository
20-08-22 14:32:41 INFO (MainThread) [supervisor.store] Load add-ons from store: 66 all - 66 new - 0 remove
20-08-22 14:32:41 INFO (MainThread) [supervisor.addons] Found 1 installed add-ons
20-08-22 14:32:41 INFO (SyncWorker_1) [supervisor.docker.interface] Attach to homeassistant/amd64-addon-samba with version 9.2.0
20-08-22 14:32:41 INFO (MainThread) [supervisor.snapshots] Found 1 snapshot files
20-08-22 14:32:41 INFO (MainThread) [supervisor.discovery] Load 0 messages
20-08-22 14:32:41 INFO (MainThread) [supervisor.ingress] Load 0 ingress session
20-08-22 14:32:41 INFO (MainThread) [supervisor.misc.secrets] Load Home Assistant secrets: 1
20-08-22 14:32:41 INFO (MainThread) [__main__] Run Supervisor
20-08-22 14:32:41 INFO (MainThread) [supervisor.api] Start API on 172.30.32.2
20-08-22 14:32:41 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' start 0 add-ons
20-08-22 14:32:41 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SYSTEM' start 0 add-ons
20-08-22 14:32:41 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SERVICES' start 1 add-ons
20-08-22 14:32:41 INFO (SyncWorker_0) [supervisor.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 9.2.0
20-08-22 14:32:46 INFO (SyncWorker_0) [supervisor.docker.interface] Start homeassistant
20-08-22 14:32:47 INFO (MainThread) [supervisor.homeassistant] Wait until Home Assistant is ready
20-08-22 14:32:57 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-08-22 14:32:57 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance
20-08-22 14:32:57 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.APPLICATION' start 0 add-ons
20-08-22 14:32:57 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
20-08-22 14:32:57 INFO (MainThread) [supervisor.misc.hwmon] Started Supervisor hardware monitor
20-08-22 14:32:57 INFO (MainThread) [supervisor.core] Supervisor is up and running
20-08-22 14:32:57 INFO (MainThread) [supervisor.host.info] Update local host information
20-08-22 14:32:57 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
20-08-22 14:32:57 INFO (MainThread) [supervisor.host.services] Update service information
20-08-22 14:32:57 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
20-08-22 14:32:57 INFO (MainThread) [supervisor.host.network] Update local network DNS information
20-08-22 14:32:57 INFO (MainThread) [supervisor.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/NetworkManager/DnsManager
20-08-22 14:32:57 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information

**Description of problem:**
When I want to restore a snapshot nothing happens the page is unresponsive. When I open a new page and login to home assistant everything works fine but the snapshot is not restored. I tried it with a new install on proxmox and Debian with the exact same result.

There is nothing written in the logs about the restore
Did a fresh install of home assistant made a snap shot. Installed one add on for testing, to see if the spanshot has been restored.

**Update**
Seems it is a problem with chrome. I did a restore through ssh terminal and that went fine. Also did a restore with firefox and that also went fine.
Don't know why the problem is only in chrome

**Comment by bramkragten** [comment]
Do you have the Selenium IDE chrome extension?

**Comment by sawo69** [comment]
Yes I do.

**Comment by bramkragten** [comment]
If you disable it, it will work.
