### ISSUE TITLE
Google Calendar Month View Not Showing Everything

### ISSUE THREAD

**Issue by mstarks01** [home-assistant/frontend#6704]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
I was able to set up Google Calendar integration without too much effort, but I have noticed that certain events are missing from the month view. I'm not yet sure what they have in common. For example:

![image](https://user-images.githubusercontent.com/459717/91235627-8b82b400-e6fb-11ea-811b-b027424a5f6a.png)

And the same day in week view:

![image](https://user-images.githubusercontent.com/459717/91235756-da304e00-e6fb-11ea-8999-6e50dd420ad0.png)

## Expected behavior

All views should contain the same events.

## Steps to reproduce

I'm not quite sure how to reproduce it, but I can say that I have two calendars, one that is shared to me. So far, only the one that is shared to me has events that seem to be affected. But it's not all events. And if I log in to Google directly, I can see them.

## Environment

arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.12
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.56
python_version | 3.8.3
supervisor | 235
timezone | America/Chicago
version | 0.113.3
virtualenv | false

Home Assistant 0.113.3
Frontend version: 20200716.0 - latest
Tested with:
- Brave version 1.12.114 Chromium: 84.0.4147.135 (Official Build) (64-bit)
- Opera version:70.0.3728.119

## State of relevant entities

N/A

## Problem-relevant configuration

Nothing special here.

```
google:
  client_id: <removed>.apps.googleusercontent.com
  client_secret: <removed>
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/issues/7075
