### ISSUE TITLE
Automation Editor expands !secrets references to actual values

### ISSUE THREAD

**Issue by alvaromi** [home-assistant/frontend#6710]
## The problem

When editing an automation that references a secret, it replaces "!secret value:" with the actual value when saving.
It should not expand "!secret value" references and save them.

_NOTE: this is the same as issue home-assistant/core#11617 which was closed unresolved, but this makes using secrets.yaml pointless if you need to reference secrets from automations or scripts. In my case, I need to specify the alarm code defined in secrets.yaml in some automations_

## Environment

- Home Assistant Core release with the issue: 0.111.3
- Last working Home Assistant Core release (if known): 
- Operating environment (Home Assistant/Supervised/Docker/venv): Supervised
- Integration causing this issue: Automation/Script UI editor
- Link to integration documentation on our website: https://www.home-assistant.io/docs/automation/editor/

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by devopsleigh** [comment]
This is still occurring. My alarm code appears in the UI editor rather than the !secret alarm_code value in the yaml file, and saving the UI form replaces the value in the yaml file.

**Comment by sujal** [comment]
Is there any sense from the developers about how big of a code change this may be? In other words, is this a good bug for someone new to the codebase to potentially tackle and contribute a fix? I'm still getting a local development instance stood up, but am an experienced developer and am looking for ways to contribute.
