### ISSUE TITLE
incorrect Dutch translation in the logs

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#6714]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

logs showing incorrect Dutch translation for the English word 'times'. It says 'malen' where it should say 'keer'.
'Malen' means either 'to grind' or 'meals'.  I was pointed to https://developers.home-assistant.io/docs/translations but no clue on where to go from there.

<img width="805" alt="Schermafbeelding 2020-08-26 om 22 35 17" src="https://user-images.githubusercontent.com/33354141/91357146-14c7e280-e7f1-11ea-87c1-806db4ba561c.png">

## Expected behavior

Ive tried to edit it and have it show like:

<img width="1406" alt="Schermafbeelding 2020-08-26 om 23 23 02" src="https://user-images.githubusercontent.com/33354141/91358457-29a57580-e7f3-11ea-8b65-978ca0151dfb.png">

but am fully in the dark whether this now has been PR'd or changed. Or not.

## Environment

- Home Assistant release with the issue: 114.3
- Last working Home Assistant release (if known): never?
- Browser and browser version: all versions and types
- Operating system: 

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Changes from localize are synced every night

**Comment by Mariusthvdb** [comment]
will have to wait and see, probably next night then:

<img width="762" alt="Schermafbeelding 2020-08-27 om 09 30 02" src="https://user-images.githubusercontent.com/33354141/91410935-f17c5200-e847-11ea-9530-12ef1e07f407.png">

**Comment by bramkragten** [comment]
Synced to GitHub, not your instance. So next release.
