### ISSUE TITLE
App Crash, iOS 14 latest beta

### ISSUE THREAD

**Issue by kevlacross** [home-assistant/frontend#6722]
My app is crashing if I click on a switch, create a new scene or edit a Card  in the UI. Sometimes Thinks are clickable and sometimes not. But at the moment I can’t click anything. I can only click the Menü and my cards. But if I click on something it crashes.  Ist also happens on mobile safari.

**Comment by SeanPM5** [comment]
This was an Apple bug in iOS 14 beta 5. They fixed it in iOS 14 beta 6 which was released a few days ago. 

All you have to do is update to the latest iOS beta and everything will be fine again.
