### ISSUE TITLE
Media player component doesn't call select_source

### ISSUE THREAD

**Issue by pszafer** [home-assistant/frontend#6740]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
home_assistant_frontend-20200824.0.dist-info
- [x] I have cleared the cache of my browser.
checking in incognito mode
- [x] I have tried a different browser to see if it is related to my browser.
checked in Chromium and Firefox
## The problem

When changing source in media_player nothing happens and nothing gets called from frontend (dev version of Core).
Service call from dev tools is working.
Above gif of behaviour:
![no_source_select](https://user-images.githubusercontent.com/690510/91633518-19ef8200-e9e9-11ea-93f1-0d77c7b8304f.gif)

## Expected behavior
Source should be changed.

## Steps to reproduce

    1. Add an media_player entity - checked epson and onkyo
    2. Navigate to Lovelace
    3. Click more info of the media player entity
    4. Set source to different than currently selected
    5. Nothing happens.

## Environment
```

arch | x86_64
-- | --
dev | true
docker | false
hassio | false
installation_type | Home Assistant Core
os_name | Linux
os_version | 5.8.3-arch1-1
python_version | 3.8.5
timezone | UTC
version | 0.115.0.dev0
virtualenv | true


```
- Home Assistant release with the issue: 0.115.0.dev0
- Last working Home Assistant release (if known): 0.114.4
- Browser and browser version: Chromium 85
- Operating system: Arch Linux

## State of relevant entities
![image](https://user-images.githubusercontent.com/690510/91633550-6fc42a00-e9e9-11ea-934b-1f5ee3b65d5b.png)

## Problem-relevant configuration

```yaml
- platform: onkyo
  host: 192.168.ip
  name: onkyoparter
  sources:
    bd: 'Bluray'
    video3: 'Shield'
    video2: 'NC+'
    fm: 'Radio'

```

**Comment by bramkragten** [comment]
Already fixed
