### ISSUE TITLE
Translation Error for UPNP integrations

### ISSUE THREAD

**Issue by marnikvde** [home-assistant/frontend#6747]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
In Settings->Integrations, I see 2 cards with the UPNP logo that have this text underneath it: "Translation Error: The intl strin...". By inspecting the DOM, I see this:

`Translation Error: The intl string context variable "naam" was not provided to the string "[%%]: {naam}"`

I signed up as a frontend-translator, but I'm not sure where to start here. I'm guessing this is not just a translation error? Happy to help.

## Expected behavior
No translation errors

## Steps to reproduce
    1. Install Home Assistant on a Raspberry Pi 3 Model B
    2. Plug it into a network with certain UPNP devices (I'm not sure which ones these are specifically but I'm willing to investigate if it helps)

## Environment
Home Assistant 0.114.4 on Raspberry PI 3 Model B

## State of relevant entities
Not applicable

## Problem-relevant configuration
Not applicable

## Javascript errors shown in your browser console/inspector
`Translation Error: The intl string context variable "naam" was not provided to the string "[%%]: {naam}"`

## Additional information
None

**Comment by marnikvde** [comment]
Strange, the cards no longer contain the error but iso this:

`Translation Error: The intl string context variable "naam" was not provided to the string "[%%]: {naam}"`

They now read:
`UPnP/IGD: marnikR7000 (Gateway)`
and
`UPnP/IGD: WAC124 (AP)`

The bug is still valid imho.

**Comment by Josverl** [comment]
I ran into the same error: 
Prior steps :

1. install HASS ( engidh)
2. during setup install UPNP (router) 
3. switch to Dutch 
4. remove UPNP 
5. Restart 
6. New device detected 
7. > Error 


`Detectie van Translation Error: The intl string context variable "naam" was not provided to the string "[%%]: {naam}" negeren?`

**Comment by spacegaier** [comment]
Those kind of errors appear if someone accidentally translates a placeholder in lokalise. In both cases mentioned here, the placeholder `{name}` was translated to `{naam}`. But since in the HA frontend coding we only provide a value for the placeholder `{name}`, at runtime the lookup for placeholder `{naam}` then fails, hence the error message.

I just corrected both instances plus a few others in lokalise and they should be fetched during the next translation job run.
