### ISSUE TITLE
Hidden/disabled entity showing in automation editor

### ISSUE THREAD

**Issue by joshtbernstein** [home-assistant/frontend#6761]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
I've hidden/disabled a binary sensor entity belonging to a zwave device. When I create an automation using the editor, it's still a choice in the trigger dropdown.

## Expected behavior
Hidden/disabled entities would not appear in any part of the UI.

## Steps to reproduce
1. Disable an entity belonging to a device in integration section of HA
2. Create a new automation using the editor.
3. Set trigger type to device.
4. Choose the device.
5. The disabled entity is listed in the trigger dropdown.

## Environment

- Home Assistant release with the issue: 0.114.4
- Last working Home Assistant release (if known):
- Browser and browser version: Google Chrome 80.0.3987.122
- Operating system: macOS 10.15.5

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
How did you disable this entity?

**Comment by joshtbernstein** [comment]
Sure:

1. I go to the list of Zwave devices: Configuration > Integrations > Devices (on the Zwave tile)
2. Then in the list of devices, I click the device.
3. Then on the device page, I choose the entity.
4. Lastly, on the entity popup, I click the slider next to "Enable entity" and choose "Update".

**Comment by spacegaier** [comment]
I just tested it and I cannot reproduce it in the latest dev version. Disabled entities are not proposed in the entity dropdown, neither via device triggers nor through condition states.
