### ISSUE TITLE
Unable to get more info panel and need to double tap menu options in android app and chrome on latest frontend 20200901.0

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/frontend#6766]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

In the android app and chrome for android I am unable to tap on any card to get the more info panel, including the badges.  On desktop it works but not on mobile.  Going to the configuration screen takes 2 clicks on the menu item and sometimes it loads a blank screen.  This is on the latest frontend 20200901.0 thats in 0.115dev

![image](https://user-images.githubusercontent.com/1634145/91935090-bba0f880-eca1-11ea-8c50-ff17c4049f7d.png)

![image](https://user-images.githubusercontent.com/1634145/91935100-c2c80680-eca1-11ea-99b9-0d58c063ec80.png)

Normally on one tap I get the more info panel or the configuration opens but here we can see thats not the case since I can take a screenshot.

## Expected behavior

One tap to get the more info and configuration

## Steps to reproduce

1. Load latest frontend in chrome for android or android app
2. Tap on a badge or entity row
3. Observe the more info panel is missing
4. Tap on menu (might need more than 1)
5. Tap on configuration

These options should allow single tap on mobile, on desktop it works as expected

## Environment

- Home Assistant release with the issue: 0.115dev 20200901.0 frontend
- Last working Home Assistant release (if known): 0.114.4
- Browser and browser version: Chrome for android latest and Android app
- Operating system: Androd 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
Generated UI
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by dshokouhi** [comment]
Just a FYI the more info panel issue is fixed however I still need to tap on the menu options more than once in 20200904.0, should I create another bug or should we use this one?  I see the panel being highlighted but sometimes I need to click on it more than once for it to load. In the below video you can see the menu item first being selected then tapped again to load.

video of android app behavior, chrome for android incognito has similar: https://drive.google.com/file/d/1nQVxZcdwfAiKVMpUpROvU2h6HGVYWkbl/view?usp=sharing

**Comment by Jason-nz** [comment]
I've also noticed after this change that scrolling on Lovelace on Android brings up the more info panel when the finger is taken off.

**Comment by dshokouhi** [comment]
@Jason-nz i created a new issue since it technically is, I accidentally added 2 issues here originally. Yours sounds like a new one too so I suggest you create a new issue for it.
