### ISSUE TITLE
History Graph on able to show a single value

### ISSUE THREAD

**Issue by oneofthemany** [home-assistant/frontend#6769]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## Expected behavior

When multiple entities are selected for viewing within a History Graph card I get the following:
![image](https://user-images.githubusercontent.com/44924639/91995063-3d8b3300-ed2f-11ea-8644-b42244c1d220.png)

## Steps to reproduce

    1. Add a History Graph card to the UI
    2. Add more than 1 entity to the card
	
## Environment

- Home Assistant release with the issue: 0.114.4
- Last working Home Assistant release (if known): 0.113.?
- Browser and browser version: Chrome Version 85.0.4183.83 
- Operating system: HassOS 4.12

## State of relevant entities

![image](https://user-images.githubusercontent.com/44924639/92128144-003fa780-edfa-11ea-8312-34b930a91aff.png)

```yaml

```

## Problem-relevant configuration

cards:
  - entities:
      - entity: sensor.withings_weight_lbs_sean
      - entity: sensor.withings_muscle_mass_lbs_sean
      - entity: sensor.withings_fat_free_mass_lbs_sean
      - entity: sensor.withings_bone_mass_lbs_sean
      - entity: sensor.withings_fat_mass_lbs_sean
      - entity: sensor.withings_fat_ratio_pct_sean
    hours_to_show: 336
    refresh_interval: 0
    type: history-graph
type: vertical-stack

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

Confirmation that each entity is able to be graphed singularly has been tested, so it is not an issue with the entity or the data stored for that entity, but seems to be purely a limitation within the history graph element and it only allowing 1 entity per graph

I have also tested on Firefox and MS Edge and I experience the same issue, so it may be safe to say it is not browser related

**Comment by oneofthemany** [comment]
> Please fill out the entire issue template.
> Thanks 👍

A link to the template would be cool as I have googled and found nothing - sorry :)

**Comment by SeanPM5** [comment]
The issue template is located [here](https://github.com/home-assistant/frontend/issues/new?labels=bug&template=BUG_REPORT.md), it's the default text that shows up when pressing the "New issue" button. You are not supposed to delete that text.

Following that issue template is important so the developers can know more details about a bug, things like your browser and OS, Home Assistant version, etc.

**Comment by oneofthemany** [comment]
> The issue template is located [here](https://github.com/home-assistant/frontend/issues/new?labels=bug&template=BUG_REPORT.md), it's the default text that shows up when pressing the "New issue" button. You are not supposed to delete that text.
> 
> Following that issue template is important so the developers can know more details about a bug, things like your browser and OS, Home Assistant version, etc.

I didn't get any of that when I created a new issue, hence what we have above.

Thanks for highlighting this though! :)

**Comment by zsarnett** [comment]
There now you can fill it out :)

**Comment by oneofthemany** [comment]
All done

Let me know if you want anything else

:)

**Comment by zsarnett** [comment]
Is there anything in the logs of your browser? https://kb.mailster.co/how-can-i-open-the-browsers-console/

**Comment by oneofthemany** [comment]
> Is there anything in the logs of your browser? https://kb.mailster.co/how-can-i-open-the-browsers-console/
> 
> Also thank you for filling out the template

This is the error when multiple values are within the  History Graph card:

https://seans-hassio.duckdns.org/api/history/period/2020-08-20T16:01:08.064Z?filter_entity_id=sensor.withings_weight_lbs_sean,sensor.withings_muscle_mass_lbs_sean,sensor.withings_fat_free_mass_lbs_sean,sensor.withings_bone_mass_lbs_sean,sensor.withings_fat_mass_lbs_sean&end_time=2020-09-03T16:01:08.064Z&minimal_response

**Comment by zsarnett** [comment]
Anything in your HA logs that may be related?

**Comment by oneofthemany** [comment]
> Anything in your HA logs that may be related?

Ill have an better look but will have to dump and filter

**Comment by oneofthemany** [comment]
> > Anything in your HA logs that may be related?
> 
> Ill have an better look but will have to dump and filter

I am seeing this a lot:

[parameters: ('2020-08-08 20:08:16.083684', '2020-08-18 08:09:46.918000', 'zone', 'scene', 'sensor.withings_weight_lbs_sean', 'sensor.withings_muscle_mass_lbs_sean', 'sensor.withings_fat_free_mass_lbs_sean', 'sensor.withings_bone_mass_lbs_sean', 'sensor.withings_fat_mass_lbs_sean', 'sensor.withings_fat_ratio_pct_sean')]
(Background on this error at: http://sqlalche.me/e/13/4xp6)

**Comment by bramkragten** [comment]
What is the response for that get request?

**Comment by bramkragten** [comment]
Ok that seems like an issue with your database, can you try with an empty database?

**Comment by oneofthemany** [comment]
> Ok that seems like an issue with your database, can you try with an empty database?

that's fixed the issue thanks

ill keep my on this, and thanks again
