### ISSUE TITLE
Wrong frontend translation in pl.json

### ISSUE THREAD

**Issue by tresor1971** [home-assistant/frontend#6774]
Hello,
I'd like to report wrong translation at line 382 of pl.json file.
It is 
"target_temperature": "Wilgotność docelowa", what is wrong and should be replaced with "target_temperature": "Temperatura docelowa".
Could you please have a look at this?
Thank you for your great work!

**Comment by bramkragten** [comment]
You can fix translations yourself in Lokalise:

<https://developers.home-assistant.io/docs/translations>
