### ISSUE TITLE
Onboarding input field colors have limited contrast

### ISSUE THREAD

**Issue by adr29truck** [home-assistant/frontend#6814]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

During onboarding the input fields have a grey ish color that does not have any real contrast to the background, making it hard to read what is inserted into the fields.
See screenshot below.

## Expected behavior

This grey ish color is used for the placeholder but the user inserted content should have a color ie, black that have a larger contrast to the background.

## Steps to reproduce

1. Set up a new installation of Home Assistant
2. On the location select screen, see error. 
## Environment

- Home Assistant release with the issue: 0.114.4
- Last working Home Assistant release (if known): n/a
- Browser and browser version: chrome, safari
- Operating system: macOS, Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
[https://imgur.com/a/Elc8NFw](https://imgur.com/a/Elc8NFw)

**Comment by bramkragten** [comment]
Looks like it is mixing 2 themes, is your device in dark mode or in light mode?

**Comment by adr29truck** [comment]
OS, was running dark mode, but I see you already sort of figured that out.
