### ISSUE TITLE
Sidebar flashes white background in dark mode during loading

### ISSUE THREAD

**Issue by spacegaier** [home-assistant/frontend#6822]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Follow-up to https://github.com/home-assistant/frontend/issues/6607.

This PR https://github.com/home-assistant/frontend/pull/6815 fixes the flashing for the main content area, but this is still remaining in the sidebar:

![140B3728-9F3E-4969-A51C-33F6B715F884](https://user-images.githubusercontent.com/114137/92410210-b4676800-f143-11ea-947f-9dbe3cfb7779.GIF)

## Environment

- Home Assistant release with the issue: 0.115
- Last working Home Assistant release (if known):
- Browser and browser version: FF 85.0
- Operating system: Win 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
Issue still persist in the latest dev version.

**Comment by gralin** [comment]
I have tested this on latest version (2021.1.5) and I don't have this effect. I've tested without cache and with network speed throttling, using latest versions of Chrome and Firefox. Test performed on Windows with dark mode preference enabled. The only place I noticed the "white flash" is when navigating to Superviso dashboard. Maybe this issue could be closed and another one opened for the Supervisor dashboard?

**Comment by spacegaier** [comment]
@gralin Negative, issue still exists for me on latest dev version with latest Firefox 85.0.

**Comment by gralin** [comment]
@spacegaier interesting, maybe there is a difference between dev version of frontend and version used in the official release? Can you confirm you have the same effect on that one too? The effect I see is this

![map](https://user-images.githubusercontent.com/3457048/105921681-7d81e800-6039-11eb-92d5-ab9f9e2d874d.gif)

**Comment by spacegaier** [comment]
Only happens for me in the dev instance. Production release is fine, so probably optimizations such as the minification speed it up enough that the white bar is never visible there.

**Comment by gralin** [comment]
👍

**Comment by gralin** [comment]
Was I supposed to react with thumbs up for the bot comment to confirm? I've posted a comment with thumbs up as instructed and the issue is not state anymore, I think this is not intended?

**Comment by spacegaier** [comment]
When you comment, the `stale` tag gets removed.

In my dev instance with Firefox I still see the issue, but not in Chrome.

**Comment by gralin** [comment]
@spacegaier 
> When you comment, the stale tag gets removed.

Yeah, I figured, but bot message was clear about 'commenting' not 'reacting' with thumbs up, I try to pay close attention to command details ;) 

I can check again on dev if you want, but I think since the release version doesn't have it (regardless of why is that), then we should close it as it's not important. Should be reopened if this is actually visible in production.

**Comment by spacegaier** [comment]
The issue, still persists, but I have no idea how to tackle it and it is really low prio, so I will stop fighting the stale bot now.
