### ISSUE TITLE
[0.115.0b0] Sidebar customization not mobile-friendly (for iOS, at least)

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/frontend#6830]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I was able to get the sidebar customization to work on my iPhone XS Max running the latest app (2020.6 (12)) once, but now I can't get it to trigger at all.  Holding down on sidebar items just does nothing now.

The one time that I did get it to trigger, the items didn't display properly and I couldn't move or remove any items:

![IMG_1094](https://user-images.githubusercontent.com/860888/92421386-24b6bf00-f12d-11ea-8565-910369cdd989.jpeg)

## Expected behavior

Sidebar customization should work on mobile as it does on desktop browsers.

## Steps to reproduce

Attempt to trigger sidebar customization by pressing and holding an item in the sidebar.  Observe that either nothing happens, or it results in the screenshot above with non-functional behavior.

## Environment

- Home Assistant release with the issue: 0.115.0b0
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Home Assistant iOS 2020.6 (12)
- Operating system: iOS 13.7

**Comment by bramkragten** [comment]
#6853
