### ISSUE TITLE
Reload template entities option missing from Configuration->Server Controls

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/frontend#6834]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

One of the new features of 0.115 is the ability to reload template entities, as described here:

> If this change means you need to make adjustments, we have made it easier by making template entities reloadable in the YAML configuration reloading section under Configure Home Assistant -> Server Controls.

There's no item for this in Server Controls:

<img width="619" alt="Screen Shot 2020-09-07 at 5 44 04 PM" src="https://user-images.githubusercontent.com/860888/92422326-c7713c80-f131-11ea-86e0-ef780e18016a.png">

From Discord:

```txt
bdraco Today at 5:36 PM
You should see a reload template entities
It’s missing for me as well in the latest UI
Please file a frontend github issue
In the mean time you can call the template.reload service in the developer tools
```

## Expected behavior

There should be a link on that page offering the ability to reload template entities.

## Steps to reproduce

Install 0.115.0b0, navigate to Configuration->Server Controls with Advanced Mode on in the profile and observe that there's no option to reload template entities.

## Environment

- Home Assistant release with the issue: 0.115.0b0
- Last working Home Assistant release (if known): N/A (new functionality)
- Browser and browser version: Chrome v85
- Operating system: MacOS 10.15.6

No errors or apparently relevant messages in the log.

**Comment by ludeeus** [comment]
Reload buttons only appear for loaded integrations if they have a reload service.
`template` is not the integration, but rather `sensor`/`binary_sensor` and so on.

**Comment by frenck** [comment]
yet, the `template.reload` service exists...

**Comment by ludeeus** [comment]
True, but that is not the loaded integration, and the current implementation takes loaded integrations and checks if a reload service exists for it.
