### ISSUE TITLE
More info History tab doesn't live update

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6836]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

The new history tab (seen below) does not appear to live update with state changes anymore. You have to close the dialog and re-open it for the logbook and history portion to update.

![image](https://i.imgur.com/8sCNM9m.png)

## Expected behavior

Live update with state changes

## Steps to reproduce

Open the more info dialog for a light, toggle it on and off repeatedly. The history / logbook doesn't live update as it did before.

## Environment

- Home Assistant release with the issue: 0.115.0b0
- Last working Home Assistant release (if known): 0.114.4
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
#6936
