### ISSUE TITLE
Escape key to dismiss Media Browser dialog

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6839]
## The request

It would be nice if the escape key (and/or clicking outside the dialog) dismissed the media browser dialog. I think in many cases, you'll want to quickly select a song/app/movie or something and then close it after you make your selection. This should be quick to do imo.
.

**Comment by spacegaier** [comment]
I added it to my related open PR https://github.com/home-assistant/frontend/pull/6817.
