### ISSUE TITLE
More info History tab - timestamps sometimes wrap to second line

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6842]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

In some cases, on the History tab, the timestamp wraps to two lines despite there being plenty of free space available for it.

This seems to happen mostly on the first two items, the rest render as expected.

![image](https://i.imgur.com/67KMr57.png)

Different entity with exact same weirdness, only the first two logbook items their timestamps wrap to two lines, others display fine.

![image](https://i.imgur.com/yD4bcIs.png)

## Environment

- Home Assistant release with the issue: 0.115.0b0
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
The first 2 items are larger than the rest 😄
