### ISSUE TITLE
Media Browser Spotify recently played sorted alphabetically instead of recent, also shows dupes (0.115.0b0)

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6843]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Again this is sort of a gray area between frontend display issue or integration backend issue, so transfer to core repo if that is the case...

Media Browser for Spotify has a "Recently Played" category. You would expect a recently played to show your most recently played music at the top, but instead this is sorted alphabetically A-Z like all the other categories.

In this demonstration picture, Rick Astley's "Never Gonna Give You Up" was the most recently played and should appear at the top but instead appears in the middle. Also played it three times in a row to demonstrate another issue (IMO) - it shows "duplicates" if you happen to play a song on repeat multiple times.  

![image](https://i.imgur.com/8z4Gmg3.png)

I hope this doesn't ruin my recommendations forever hahah 🙈 

## Steps to reproduce

Go to Spotify media browser -> Recently Played. They are sorted alphabetically rather than recently played.

## Environment

- Home Assistant release with the issue: 0.115.0b0
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome stable
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by frenck** [comment]
Not sure if this is a backend or frontend problem, tagged it for the milestone for the frontend for now.

**Comment by bramkragten** [comment]
It is frontend, the items are sort alphabetically.

**Comment by spacegaier** [comment]
The duplicates are actually coming from the original Spotify payload in my case. Each have their own `played_at` value, so we could e.g. pick the newest entry and use only that and then sort by `played_at`.

**Comment by bramkragten** [comment]
> The duplicates are actually coming from the original Spotify payload in my case. Each have their own `played_at` value, so we could e.g. pick the newest entry and use only that and then sort by `played_at`.

THAT would be backend.

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/pull/6886

We are going to move sorting initially to the backend
