### ISSUE TITLE
More info "Controls" tab naming

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6844]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The first tab on more info dialogs is now called "Controls" which fits well for anything that has interactive controls there - like Lights, Media Players, Remotes, Alarms, Thermostats, Counters, etc... 

But on some others like Sensors, Sun, Device Trackers, Weather, etc which are read only, this naming feels a bit wrong and weird? And for newer users it might be confusing if they're expecting to see controls when that's not actually supported.

![image](https://i.imgur.com/YDFi25F.png)

## Expected behavior

I think for domains that offer interactivity it should display "Controls" and for others that are read-only it should display "Details" or "Info" or "State" or something else....

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
https://github.com/home-assistant/frontend/issues/6856
