### ISSUE TITLE
Expand sidebar when customizing it

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6845]
## The request

I think the sidebar should be expanded when customizing it, for two reasons:

1. This helps you see what you're moving (see example below)
2. You click the "Done" button to save your customizations, so expanding the sidebar is pretty much required anyway right? Doing it for the user will just save an extra step. After they press "Done" button it could collapse again I guess.

## Additional information

Example - this screenshot is currently in edit / jiggle mode, but not expanded. These two icons are identical, you cannot tell them apart when like this. And other icons while usually not identical could sometimes be similar in terms of appearance.

![image](https://i.imgur.com/4nCDJW9.png)

With it expanded though, you can see that one is the Grocy Supervisor add-on and the other is core Shopping List integration:

![image](https://i.imgur.com/fYyMy37.png)

**Comment by frenck** [comment]
Honestly, I think this is a bug...
