### ISSUE TITLE
Demo Bugs in 0.115.0b0

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6846]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

While trying to reproduce a certain bug in the demo, I noticed a couple demo-specific issues.

1. Customizing the sidebar doesn't work in demo. You can enter that mode but not drag anything.
2. Similarly, the "Sortable" stuff doesn't work. Cannot re-arrange entities in Lovelace cards, can't re-arrange Badges under View Configuration, etc...
3. More info "History" tab the Logbook portion always spins constantly, never loads
4. Map panel no longer appears to load. When I click it, the URL in address bar is `https://demo.home-assistant.io/#https://demo.home-assistant.io/map`

Some of these might be expected and/or unfixable, I know it's fake data etc... Just thought I'd point this stuff out just in case.

## Steps to reproduce

1. Browse [demo site](https://demo.home-assistant.io/#/lovelace/0)

## Environment

- Home Assistant release with the issue: 0.115.0b0
- Last working Home Assistant release (if known): n/a (it's mostly all new features)
- Browser and browser version: Chrome stable
- Operating system: macOS beta

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
Are these fixed now?

**Comment by SeanPM5** [comment]
Some of them were fixed (just crossed some out) but the drag and drop in sidebar and Lovelace cards still doesn't work.
