### ISSUE TITLE
Dont show history tab in more info for read-only entities

### ISSUE THREAD

**Issue by bramkragten** [home-assistant/frontend#6856]
## The request

Sensor and binary sensor entities don't have controls, so we should just show the history on the main/single tab.

**Comment by ludeeus** [comment]
The same goes for air_quality, calendar, device_tracker, image_processing, mailbox, persistent_notification, person, sun,  weather, zone

**Comment by bramkragten** [comment]
Yes :-)

**Comment by hunterjm** [comment]
Image processing (and some others) may not have controls, but they do have attributes which are useful. Should that be a 3rd tab? Controls -> History -> Details? Each hidden if no info available?
![077B4233-9676-41FC-88F5-42BC9B762D68](https://user-images.githubusercontent.com/747670/92485385-dea73d00-f1b8-11ea-9255-53044c7948c5.jpeg)

**Comment by zsarnett** [comment]
Yea I hate the attributes 😬 

But out of scope for now

**Comment by zsarnett** [comment]
Oh this isnt a PR

**Comment by hunterjm** [comment]
Sorry for the ginormous image. Posted on mobile. Reading through the beta channel, I think two changes would make this super clean.

1) Hide Controls tab for entities that don't have interactivity.
2) Move attributes from Controls to a third tab hidden away at the end.
   2a) Only show new tab if user is Admin?

**Comment by bramkragten** [comment]
@hunterjm we should probably add dedicated UI for those attributes
