### ISSUE TITLE
Default sound playback on camera stream to off

### ISSUE THREAD

**Issue by olbjan** [home-assistant/frontend#6857]
## The request
In 0.115.0b0 audio was added to the stream component which auto-plays when a camera is added to lovelace as a picture entity card. This is undesirable for multiple reasons but especially since there is no UI to turn playback off in a picture entity card as well as being confusing if multiple cameras are in one view.

I request that camera streams default to audio off and only play audio as part of the more-info dialog.

**Comment by gohassgo** [comment]
+1

**Comment by bramkragten** [comment]
That's weird, all our players appear to be muted, even the more info dialog... I removed it from there, but that won't fix it ofc. I don't have a camera to test it, maybe I can grab a stream from the internet.

**Comment by gohassgo** [comment]
I just took a quick look at my cameras and in the picture entity cards they do not auto play audio. However, when the picture entities are in a vertical stack, they do play the audio.

**Comment by gohassgo** [comment]
In a glance card they do auto play the audio.

**Comment by bramkragten** [comment]
Cna you inspect the player and confirm it has the attribute `muted` on the `video` element?

**Comment by gohassgo** [comment]
I don't see that anywhere and am not sure of the correct syntax to add it.

**Comment by bramkragten** [comment]
This is fixed
