### ISSUE TITLE
OZW (Beta) Control panel add / remove node always uses instance 1 (115.b0)

### ISSUE THREAD

**Issue by hanerd** [home-assistant/frontend#6860]
## Checklist

- [ x] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem
When using the new control panel in 115, using add or remove node on instance 2 for ozw results in the command being sent to instance 1.

![image](https://user-images.githubusercontent.com/49296333/92497637-35177a00-f1bf-11ea-89db-ffa5625ad686.png)

## Expected behavior
I would expect the add  / remove node buttons to correlate to the instance from which they're activated.

## Steps to reproduce
1. Drill into any instance that's not 1
2.  click one of the add or remove buttons.  
3. Monitor mqtt traffic and you'll see that "command" is only ever present on instance 1

## Environment

- Home Assistant release with the issue: 115.b0
- Last working Home Assistant release (if known): It's new in 115, so never.
- Browser and browser version: Chrome 85
- Operating system: MacOS Big Sur Beta

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by kpine** [comment]
Just noticed this myself in 0.116.0.dev20200913. The button handler is not passing in any service data, such as `instance_id`, so it will just use the default of 1.

https://github.com/home-assistant/frontend/blob/aa5e20df05304a161d0be8d2b8688a88c7628171/src/panels/config/integrations/integration-panels/ozw/ozw-network-dashboard.ts#L161-L171
