### ISSUE TITLE
Phone battery state not updating

### ISSUE THREAD

**Issue by c0nt4x** [home-assistant/frontend#6868]
## Checklist

- [ X] I have updated to the latest available Home Assistant version.
- [ X] I have cleared the cache of my browser.
- [ X] I have tried a different browser to see if it is related to my browser.

## The problem

I created an automation based on my iPhone being charged. It didn’t work so when I check the state in Developer Tools it always shows ‘not charging’. This is the case whether it is being charged wirelessly or wired

## Expected behavior
.

When charging the state should change to ‘charging’

## Steps to reproduce

In ‘developer tools’ locate phone/device battery state

## Environment

- Home Assistant release with the issue: 0.114.4
- Last working Home Assistant release (if known): not known
- Browser and browser version: Chrome and iOS app v2020.5.2
- Operating system: iOS 13.7 and Windows

## State of relevant entities

In developer tools the state always shows ‘not charging’ regardless of whether the phone is charging or not.
```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
Please update your issue

Anything within
```
<!-- -->
```

Will not be displayed on the screen

**Comment by SeanPM5** [comment]
This is probably more of an iOS app issue and not a frontend issue.

You can try using the TestFlight beta build (https://www.home-assistant.io/ios/beta) which is currently at version `2020.6 (12)`. I believe there has been improvements to the battery state sensor where it updates significantly faster now than in the build you're using.

**Comment by c0nt4x** [comment]
> This is probably more of an iOS app issue and not a frontend issue.
> 
> 
> 
> You can try using the TestFlight beta build (https://www.home-assistant.io/ios/beta) which is currently at version `2020.6 (12)`. I believe there has been improvements to the battery state sensor where it updates significantly faster now than in the build you're using.
> 
> 

Thanks for the reply.

But the automation should still work regardless of how I'm viewing the state shouldn't it?

**Comment by SeanPM5** [comment]
The automation can only trigger if the state actually changes (from "Not Charging" to "Charging") - which is either not happening in your case, or is happening far slower than you expect.

Either of those cases are an app issue - the mobile app is responsible for how and when your iPhone's battery state sensor updates. The beta app has improvements to the speed of this (see https://github.com/home-assistant/iOS/pull/954 for more info). If you'd rather not use the beta app you can wait for it to hit the App Store, probably sometime later this month.

**Comment by c0nt4x** [comment]
Ok, thank you Sean.

Sent from my iPhone

On 8 Sep 2020, at 23:55, Sean Mooney <notifications@github.com> wrote:

﻿

The automation can only trigger if the state actually changes (from "Not Charging" to "Charging") - which is either not happening in your case, or is happening far slower than you expect.

Either of those cases are an app issue - the mobile app is responsible for how and when your iPhone's battery state sensor updates. The beta app has improvements to the speed of this (see home-assistant/iOS#954<https://github.com/home-assistant/iOS/pull/954> for more info). If you'd rather not use the beta app you can wait for it to hit the App Store, probably sometime later this month.
