### ISSUE TITLE
Scene states

### ISSUE THREAD

**Issue by giuliandenicola1** [home-assistant/frontend#6869]
## The request

Scenes only show `scening` as state. I would like to have the state changed to perhaps `activated` when the exact conditions are met. This will give the possibility to have for example lighted up buttons when a scene is activated.

## The alternatives

I am using a gross code version of the result I want to achieve it's working but it has to use 3 different variables: `1. Input_number`, `2. group(s)` and `3. automation(s)` all of this to achieve a state that is nonexistent not to mention that this will only condition the on/off state of the groups and doesn't fetch the brightness, color, etc.

## Additional information
With scenes that have states it will be much easier and more accurate to achieve this the button will light up when the scene is activated and turn off when the scene is deactivated (or scening).

**Edit**: Like what HomeKit does with it scenes 
[Video example](https://streamable.com/w1uund)

**Comment by ludeeus** [comment]
The frontend only shows what the core knows.
For feature requests to the Core please use the feature request section on the [forum](https://community.home-assistant.io/c/feature-requests/13)

Thanks :+1:
