### ISSUE TITLE
Spotify Media Browser - clicking album art always produces "Unknown error" 0.115.0b1

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6871]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I reported https://github.com/home-assistant/core/issues/39778 yesterday and it was fixed today in b1. But after installing b1 it seems that clicking anywhere on the album art no longer work like it did in b0. If I do that I get "Unknown error" all the time. 

You can never drill down into albums anymore. Can only click on the small play button overlays now (red boxes in below image) to play it, rather than browsing the contents of a playlist or album. That feels like maybe a frontend issue but not sure (please move to core if not).

![image](https://i.imgur.com/jonXRe2.png)

## Steps to reproduce

1. Open Spotify media browser
2. Click on any category, click on an album. Doesn't work unless you specifically click the play button icon now. 

## Environment

- Home Assistant release with the issue: 0.115.0b1
- Last working Home Assistant release (if known): 0.115.0b0
- Browser and browser version: Chrome stable
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
Logger: homeassistant.components.websocket_api.http.connection.547536551072
Source: components/spotify/media_player.py:614
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 7:08:22 PM (2 occurrences)
Last logged: 7:11:50 PM

Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 21, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1002, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/usr/src/homeassistant/homeassistant/components/spotify/media_player.py", line 445, in async_browse_media
    response = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/spotify/media_player.py", line 574, in build_item_response
    response["children"].append(item_payload(item))
  File "/usr/src/homeassistant/homeassistant/components/spotify/media_player.py", line 614, in item_payload
    "media_class": CONTENT_TYPE_MEDIA_CLASS[media_type],
KeyError: 'track'
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by SeanPM5** [comment]
Edit:
- Recently Played, Tracks, Top Tracks no longer work
- Categories now displays "No items" when it was working fine in b0

**Comment by bramkragten** [comment]
That's weird... Tested it yesterday

**Comment by bramkragten** [comment]
https://github.com/home-assistant/core/pull/39841
