### ISSUE TITLE
Config flows - external website dialog issue (0.115.0b1)

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6872]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

There's an issue with the rendering of this dialog, seen in config flows when setting up Plex or Spotify etc.. The text is overlapping the close (X) button.

![image](https://i.imgur.com/MLsl0RQ.png)

## Steps to reproduce

1. Go to Configuration -> Integrations
2. Select Plex (or another like Spotify) that allows logging in via oauth
3. Look at the dialog that shows

## Environment

- Home Assistant release with the issue: 0.115.0b1
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome stable 
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
I can confirm that issue. Had the same on my end during Spotify setup, but forgot to create the ticket for it 🙄 .
