### ISSUE TITLE
Plex Media Browser sorts TV episodes alphabetically rather than by episode order

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6874]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Similar issue as the Spotify 'recently played tracks' one I reported in https://github.com/home-assistant/frontend/issues/6843 but this one is a bigger issue I feel... @jjlawren 

Plex Media Browser in Home Assistant sorts TV episodes alphabetically:

![image](https://i.imgur.com/neDqVDy.png)

Rather than the proper sort, by episode number. Here's the order the above screenshot _should_ be (correct order in Plex app):

![image](https://i.imgur.com/EmzPoY0.jpg)

As you can see, it's literally completely backwards here... Episode 3, Episode 2, Episode 1. If I watched it in this order I'd be spoiled and hella confused... 😛  

TV series seasons should not ever be sorted alphabetically. This might occur in other integrations using media browser, I'm not able to test them all though.
 
## Expected behavior

Episodes must always be sorted by correct episode order (1, 2, 3, 4, 5....) rather than episode titles.

## Steps to reproduce

1. Open Plex media browser and browse to TV episodes

## Environment

- Home Assistant release with the issue: 0.115.0b1
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome stable
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

Another example, this one the episode titles are the actual episode numbers (lack of meta data), but it's still bad cause it jumps from episode 1 straight to episode 10...

![image](https://i.imgur.com/cckfYH4.png)

**Comment by jjlawren** [comment]
This initial media browser implementation doesn't yet provide much metadata to the frontend, such as episode/track numbering, media descriptions, ratings, etc. Of those I agree that the ordering is the most important. I could "fix" this with special title naming in the backend, but it's probably better to fix this in a standardized way for all media browser integrations.

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/pull/6886

We are going to move sorting initially to the backend
