### ISSUE TITLE
Onboarding text has low contrast in dark mode

### ISSUE THREAD

**Issue by bonanitech** [home-assistant/frontend#6882]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Part of the text is barely visible when using dark mode.

| <img width="1280" alt="Screen Shot 2020-09-09 at 7 19 15 AM" src="https://user-images.githubusercontent.com/29807944/92595430-57b69b00-f272-11ea-9cb4-c2e819a8198a.png"> | <img width="1280" alt="Screen Shot 2020-09-09 at 7 19 39 AM" src="https://user-images.githubusercontent.com/29807944/92595438-5ab18b80-f272-11ea-84e4-f82d8764fd63.png"> |
|-|-|
| <img width="1280" alt="Screen Shot 2020-09-09 at 8 00 28 AM" src="https://user-images.githubusercontent.com/29807944/92595588-9c423680-f272-11ea-89a2-bd035188298e.png"> | <img width="1280" alt="Screen Shot 2020-09-09 at 8 00 36 AM" src="https://user-images.githubusercontent.com/29807944/92595598-9ea49080-f272-11ea-8465-3921b42d1d51.png"> |

## Environment

- Home Assistant release with the issue: 0.115.0b2
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome 85.0.4183.83 and Safari 13.1.2
- Operating system: macOS 10.15.6

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
@ludeeus what, what, what... Do you also still get this?

**Comment by ludeeus** [comment]
Don't think I ever checked the user creation part.
But yes, there I see the same

**Comment by bramkragten** [comment]
Oh we just fixed the core step?

**Comment by ludeeus** [comment]
Everything after ha connect seems fine, it's just that before you create the user, ha is not connected so it only loads the default (light) theme vars.

**Comment by bramkragten** [comment]
OK, so needs the same as the login page?

**Comment by bramkragten** [comment]
That I can probably check and fix myself :-)

**Comment by ludeeus** [comment]
Yes, the login page looks correct

**Comment by bramkragten** [comment]
OK... I don't know... But the onboarding user page looks ok here...? I also see the correct styling

![image](https://user-images.githubusercontent.com/5662298/92647503-47410780-f2e8-11ea-854d-b78ff34a689c.png)
![image](https://user-images.githubusercontent.com/5662298/92647540-52943300-f2e8-11ea-94cd-c5030710e093.png)
