### ISSUE TITLE
Removing icons from sidebar doesn't work on iOS

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/frontend#6887]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Removing items from the sidebar doesn't work on iOS.  With 0.115.0b3, I'm now able to put the sidebar into "jiggle mode" reliably and I can move items, but I can't remove them by tapping the "x".  Instead, I see a "ghost" of the item that I'm pressing lower down in the list while I'm holding it, and it disappears when I let go.  The item remains in the list with its "x".

![IMG_1095](https://user-images.githubusercontent.com/860888/92621932-4fae2980-f279-11ea-8488-1ae0d74bd544.jpeg)

Note the "Map" text here under the "Supervisor" text further down in the list.  This screenshot was taken while I was holding the "x" next to Map, and the second "Map" goes away when I let go (item remains in the list).  Same thing happens if I tap quickly or tap/hold the "x".

## Expected behavior

I expect to be able to remove icons from the sidebar by pressing and holding on the sidebar, wait for it to go into "jiggle mode" and hitting the "x" next to an item.  This works fine on a desktop browser (Chrome or Safari) and doesn't work on my iPhone, either in the HA app or in Safari.

## Steps to reproduce

Press and hold on the sidebar, wait for it to go into "jiggle mode" and hit the "x" next to an item

## Environment

- Home Assistant release with the issue: 0.115.0b3 (couldn't get into "jiggle mode" previously)
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Safari webview
- Operating system: iOS 13.7

**Comment by migo-dev** [comment]
@rccoleman may I ask, is this resolved for you? I see the changes have been merged, but I still have the same problem (on Android tho)

**Comment by bramkragten** [comment]
This has not yet been released
