### ISSUE TITLE
BUG : Failed to reboot error message

### ISSUE THREAD

**Issue by xvolte** [home-assistant/frontend#6894]
## The problem

Everytime i want to reboot Home Assistant using the supervisor, i get an error message "Failed to reboot" "unknow error, see logs".

But of course, logs are empty because the system DOES reboot. i don't know what causes this error message to show, but it is annoying :)

Supervisor version : 242
HassOS : 4.12
running on a raspberry pi 3b

Screenshot below:
![Failed to reboot](https://user-images.githubusercontent.com/21142611/92628050-88c3b980-f2cc-11ea-8240-a98f92a14a4f.png)

Thanks in advance,

**Comment by ludeeus** [comment]
This is a frontend issue.

**Comment by ludeeus** [comment]
While I have you here @xvolte why are you rebooting?

**Comment by xvolte** [comment]
Well, from time to time i do a full reboot. 
I guess i could just restart the container of homeassistant by using the configuration pane instead of the full supervisor host reboot.
