### ISSUE TITLE
History no longer displays in 0.115 beta in the iOS App

### ISSUE THREAD

**Issue by bdraco** [home-assistant/frontend#6902]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

![Screenshot 2020-09-09 at 10 23 15 PM](https://user-images.githubusercontent.com/663432/92678358-7016cc00-f2eb-11ea-98ea-91e5fa96c904.png)

If I scroll down the page far enough past the the blank area, I can see the graphs

![Screenshot 2020-09-09 at 10 30 44 PM](https://user-images.githubusercontent.com/663432/92678700-398d8100-f2ec-11ea-8dc0-cb59357c8ae0.png)

## Steps to reproduce

Load history panel on iOS app

## Environment

- Home Assistant release with the issue: 0.116dev/0.115b
- Last working Home Assistant release (if known): 0.114
- Browser and browser version: iOS App
- Operating system: iOS 13.7     iPhone 11 Pro Max

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
This isn't new in 0.115, iOS can't handle all the graphs thrown at it at once. We should virtualize this and update our graph rendering...

**Comment by bdraco** [comment]
Dupe of https://github.com/home-assistant/frontend/issues/3340
