### ISSUE TITLE
Logbook entries on the more info popup are cut off in 0.115 beta using the iOS app

### ISSUE THREAD

**Issue by bdraco** [home-assistant/frontend#6903]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

![Screenshot 2020-09-09 at 10 22 46 PM](https://user-images.githubusercontent.com/663432/92678427-96d50280-f2eb-11ea-8c78-d494f5320a47.png)

## Expected behavior

The panel should take up the whole screen and the logbook div should extend to the bottom.

## Environment

- Home Assistant release with the issue: 0.115b
- Last working Home Assistant release (if known): N/A
- Browser and browser version: iOS app
- Operating system: iOS 13.7     iPhone 11 Pro Max

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Can you scroll it? How many items are in the logbook?

**Comment by bramkragten** [comment]
The problem is that we don't know the height of the logbook exactly beforehand, in your case it is hight than we guessed because there are 2 datelines in it... Have to think a bit how we can solve it.

**Comment by bramkragten** [comment]
I think we should not use virtualizer here
