### ISSUE TITLE
Entities change from exposed to not exposed in google assistant after upgrading to 0.115 beta

### ISSUE THREAD

**Issue by engrbm87** [home-assistant/frontend#6906]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Entities are showing as `not Exposed Entities` under manage entities for google assistant after upgrading to 0.115b0 (same after upgrading to b4). All domains are enabled (by default I guess as this is a new option) but the previous expose status of entities is not maintained after the upgrade.
Also noticed that in google home the entities are still showing. so I think there is a problem with the syncing as well.
## Expected behavior

Entities exposed status should be maintained throughout the upgrade.
## Environment

- Home Assistant release with the issue: 0.115b4
- Last working Home Assistant release (if known): 0.114
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Should be fixed with https://github.com/home-assistant/frontend/pull/6898
