### ISSUE TITLE
Media Browser Panel and Dialog in Safari

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6923]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

This happens when scrolling on both media browser panel and the dialog on 0.115.0b5 ... The heading / title goes into the content when scrolling. Behavior seen on HA macOS app in Big Sur beta, which uses WebKit/Safari.

![image](https://i.imgur.com/9ibBMeO.png)
![image](https://i.imgur.com/aigAjAE.png)

## Environment

- Home Assistant release with the issue: 0.115.0b5
- Last working Home Assistant release (if known): 0.115.0b4 (I think)
- Browser and browser version: Home Assistant MacOS Companion App (uses Safari)
- Operating system: macOS Big Sur Beta

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
I fixed this though wtf

**Comment by SeanPM5** [comment]
Another screenshot related to this issue I think. This is when I scroll in album view, it's like there's no black background and it's transparent or something(?).

![image](https://i.imgur.com/HD2r8zW.png)

I don't see it in Chrome or Firefox, just Safari (macOS HA app).

**Comment by zsarnett** [comment]
Its because the div around it should display block and then make sure we use safari position sticky. But I will look later today

**Comment by bramkragten** [comment]
Should be fixed in b8
