### ISSUE TITLE
Nested Groups of Persons display toggle

### ISSUE THREAD

**Issue by hockey6611** [home-assistant/frontend#6925]
## Checklist

- [x] I have cleared the cache of my browser.
- [x] I have updated to the latest available Home Assistant version.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When a nested group of persons is created, the second order group is not appear to render correctly as an entities card. Instead of showing the status, a toggle is shown. It the details view it is shown correctly. In an entity card (as opposed to 'entities'), it appears to display correctly. When activating the toggle a failed service call is displayed.

![image](https://user-images.githubusercontent.com/28613898/92858416-09191600-f3c4-11ea-9408-faaca6e35b68.png)
![image](https://user-images.githubusercontent.com/28613898/92858438-0fa78d80-f3c4-11ea-93cd-e7c6ca78ab7a.png)
![image](https://user-images.githubusercontent.com/28613898/92858944-ab38fe00-f3c4-11ea-9db4-218c9c8ccc1c.png)
![image](https://user-images.githubusercontent.com/28613898/92858488-1afab900-f3c4-11ea-9104-ff105d551d94.png)

## Expected behavior
No toggle on entity and no toggle on whole card. Display home/away status.

## Steps to reproduce

1. Create group of persons
2. Create second group, nesting the first group
3. Add lovelace entity/entities card

## Environment

- Home Assistant release with the issue: 0.110-0.113
- Last working Home Assistant release (if known): None
- Browser and browser version: Chrome/Firefox all recent versions
- Operating system: n/a

## State of relevant entities

Issue occurs irrelevent of home/away state.
```yaml


```

## Problem-relevant configuration

```yaml
residents:
  name: Residents
  entities:
    - person.one
    - person.two
known_people:
  name: Known People
  entities:
    - group.residents
    - person.three
```

## Javascript errors shown in your browser console/inspector

```txt
n/a
```

## Additional information
Unresolved topic in forum here: https://community.home-assistant.io/t/nested-group-of-persons/210312

**Comment by Mariusthvdb** [comment]
yes, also see https://github.com/home-assistant/frontend/issues/6599

and https://community.home-assistant.io/t/nested-group-showing-with-a-toggle-and-not-state-home-away/203741

hope this gets some traction, thanks for posting
