### ISSUE TITLE
"Trapped" in new OZW Control Panel on mobile in 0.115.0b4

### ISSUE THREAD

**Issue by KevinCathcart** [home-assistant/frontend#6934]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

The back arrow in the upper left hand corner of the new ozw control panel pages does not work as expected. Once a second page within that area has been navigated to, pressing that button will switch back and forth between the ozw pages, and never leave back to the Integration screen. Since the side navigation is completely hidden on mobile while in this screen, this results in being "stuck" in these screens in the mobile app, unless the android OS Back button is used.

I suspect that things are worse on IOS, where there is no OS level back button. This presumably requires force quitting the companion app to escape.

I'm running 0.115.0b4 (cannot update to b5 at the moment, but I don't see any relevant commits at a quick glance).
I'm accessing via the webview in the android companion app on a phone. I expect the problem to be even 

## Steps to reproduce
1. Open site/mobile app.
2. Go to Configuration/Integrations.
3. Find the OZW integration, select configure. We are now on the OZW network information screen.
4. Click the to navigate to the node list.
5. Press the back button in the upper left a bunch of times. Notice that you just get moved between pages of the OZW control panel.

Note: After step 3, if one were to push the back button in the upper left, It will return you to the integration list, as expected.

## Expected behavior

Pressing the back button would bring you back to the integration list. Having it navigate between the nodes list and network information screen is useless, since there are "tab"-like buttons for that.

## Environment

- Home Assistant release with the issue: 0.115.0b4
- Last working Home Assistant release (if known):
- Browser and browser version: Home assistant Android App.
- Operating system: Android 

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by frenck** [comment]
Just slide/swipe the HA menu/sidebar out from the left?
