### ISSUE TITLE
Sidebar: right-clicks don't work anymore

### ISSUE THREAD

**Issue by migo-dev** [home-assistant/frontend#6938]
## Checklist

- [x] I have updated to the latest available Home Assistant version (beta 6).
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Since updating to 0.115 beta, the right-click to show e.g. 'open in new tab' does not work anymore. I used that all the time for quick access to developer tools/VS Code to find information when editing something I don't want to leave at the moment. Now it's: open a new tab, access HA and then click the according element - which is not so convenient.

## Expected behavior

![114 4](https://user-images.githubusercontent.com/57773976/92946442-f3086580-f456-11ea-95c8-bfcdf067a38b.png)

## Steps to reproduce

1. right-click in the sidebar

## Environment

- Home Assistant release with the issue: 0.115+
- Last working Home Assistant release (if known): 0.114.4
- Browser and browser version: Chrome (84.0.4147.135) & Safari (13.1.2)
- Operating system: macOS Catalina (10.15.6)

## State of relevant entities

```yaml
Not applicable
```

## Problem-relevant configuration

```yaml
Not applicable
```

## Javascript errors shown in your browser console/inspector

```txt
Haven't found anything that could be related.
```

## Additional information

I suspect that's a side-effect of it now being customizable. It still works for the "user" element at the bottom, which makes sense, since this one was not affected by the customization. I also created a completely fresh container to rule out interference from custom components.

**Comment by ludeeus** [comment]
This was fixed here <https://github.com/home-assistant/frontend/pull/6933>

**Comment by migo-dev** [comment]
Very nice! Thanks
