### ISSUE TITLE
Sidebar breaks after adding Supervisor add-on to sidebar while in customization mode (0.115b6)

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6940]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I was in sidebar customization (wiggle) mode, and while it was still in that mode, I toggled on the Ingress "Show in sidebar" for a Supervisor add-on. This seems to have broken my sidebar in several ways. 

I can no longer enter customization mode. When I long press, it seems like it tries to expand the sidebar a bit, _but not really_.  Below is a picture of what it looks like, you can see the views moved over to the right but the sidebar never actually expanded.

![image](https://i.imgur.com/g0LNaWf.png)

When I expand the sidebar manually using the hamburger button, I do not see the controls for managing sidebar items (X and + buttons). The sidebar items don't wiggle. I cannot drag and drop them. I have restarted Home Assistant after that (to install b6) and no change.

And then there was a second issue, where the sidebar would not collapse. Have a screen recording of that here: https://gfycat.com/failingnaturalappaloosa ~~A hard refresh in the browser seems to have cleared this one up though.~~ Edit: This occurs when entering sidebar customization mode while in this broken state. There's no "DONE" button in the sidebar header or any controls (X/+) and the sidebar can't be dismissed unless you refresh the page.

I think that two things writing to the sidebar simultaneously corrupted it or something. Since it's device-specific, I can still customize the sidebar on my iPhone, but not my desktop browser.

## Steps to reproduce

1. Go to a Supervisor add-on overview page that supports Ingress / adding to sidebar (Files Editor for example)
2. Enter sidebar customization (wiggle mode)
3. While it's still in wiggle mode, add the Supervisor add-on to your sidebar

## Environment

- Home Assistant release with the issue: 0.115.0b5/6
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Can not reproduce this... any other steps taken? Can you check the content of you localStorage?

**Comment by SeanPM5** [comment]
Heading home shortly so I'll be able to check localStorage then, but going off memory these were the steps:

1. Had Files Editor Supervisor add-on details open. The toggle was displaying "Show in sidebar" there (but I had it removed from sidebar using new customization feature).
2. I think I pressed the + (to add it back to sidebar) and then X (to hide it again). I did not press "DONE" yet in the sidebar header, so basically it had unsaved changes.
3. Then with sidebar still in customize mode, I navigated to the Terminal & SSH add-on, which wasn't in my sidebar before. I toggled on "Show in sidebar" and when it refreshes the page in order to add it to your sidebar, it seems that's when it screwed up. Right after this I removed it from the sidebar.

**Comment by SeanPM5** [comment]
Here are the keys and values in localStorage.

sidebarHiddenPanels = `["core_configurator"]`

sidebarPanelOrder = `["lovelace","lovelace-auto_generated","redirect-logs","lovelace-tablet","map","logbook","history","lovelace-test","hacs","media-browser","calendar","shopping-list"]`

dockedSidebar = `"docked"`

<hr>

I just enabled "Show in sidebar" for File Editor (that is `core_configurator` above), and that made the sidebar work again... 

I am able to reproduce this:
1. Add File editor to sidebar (using toggle in Supervisor add-on details page)
2. Remove File editor from sidebar (using new long press customize feature)
3. Toggle OFF "Show in sidebar" on the File editor add-on page
4. Press "DONE"

Now when you go to edit it (via long-press) it does not do anything. I see this in browser Console:

![image](https://i.imgur.com/v1WmVGq.png)
