### ISSUE TITLE
hold_action no longer defaults to more-info

### ISSUE THREAD

**Issue by vandalon** [home-assistant/frontend#6942]
using hold_action in lovelace used to default to more-info (without adding it to any card)
This no longer works and now hold_action does nothing when not configured. Not sure if this is intended or not, but if so, it is a breaking change in my opinion :)

**Comment by bramkragten** [comment]
What card is this about?

**Comment by vandalon** [comment]
Sorry, i'm using the picture-elements card

**Comment by bramkragten** [comment]
Please share your config. I don't see any changes around this.

**Comment by vandalon** [comment]
So I tested a bit with several cards (picture-element, entity, button-card) and the behaviour is the same everywhere:

before 0.114:
a config without specific hold_action configured would show the more-info always when holding. 

in at least 0.115.b4 and b5

after creating a new button card (for example).
holding now copies the action from tap_action. So if tap_action is configured to toggle, hold wil toggle also when not configured. 

then after changing the tap+action from toggle to more-info, same behaviour. 

But then after changing back from more-info to toggle for tap_action , long press now does show more-info. 

So it seems a bit erratic. Existing lovelace configs that i did not change seem to copy the tap_action behaviour where no hold_action is configured. 

Example config:

```
type: button
tap_action:
  action: toggle
show_icon: true
show_name: true
show_state: false
entity: light.woonkamer
```

**Comment by bramkragten** [comment]
I check the button card you mentioned and am not able to reproduce the issue in current dev. Please re-test with the next frontend beta release.

**Comment by vandalon** [comment]
Can i do this directly somehow or do I need to wait for 0.115b7?

**Comment by vandalon** [comment]
Also, when long pressing normally, when it works, this little circle pops up after a short period of time. This does not happen in my picuture-element or glance-card. This might be a hint somehow? :)

**Comment by bramkragten** [comment]
Well, I don't see a default hold action for those cards in the code... I do see it for the button card.

**Comment by vandalon** [comment]
I can not reproduce it for button card anymore, so it might be something dumb on my side. for picture-element and glance-card I can reproduce it though. But as you see, this is expected behaviour right? Somehow this did work before 0.115 though.

**Comment by vandalon** [comment]
What exactly do you mean with adding a default? adding default behaviour with a configurable option?

**Comment by bramkragten** [comment]
Yes, like the button card has.

**Comment by vandalon** [comment]
A button card only has one entity, where as a glance or picuture-element can have multiple. Can I set a default for the whole card or must this be per entity?

**Comment by bramkragten** [comment]
some have both an option for the card and the entities, but I will try to set everything to what it was previously... Just hope I get them all 😄

**Comment by vandalon** [comment]
Awesome! Thanks!
