### ISSUE TITLE
Custom dasboard shows as empty item in sidebar when "show in sidebar" disabled.

### ISSUE THREAD

**Issue by vandalon** [home-assistant/frontend#6950]
When using a custom dasboard in 0.115b5 as default dasboard in the user settings, and this dashboard has not "show in sidebar" enabled in the dasboard settings it shows as empty row in the sidebar.

<img width="253" alt="image" src="https://user-images.githubusercontent.com/3370317/92991630-97d18400-f4e5-11ea-947e-d9f9c1895fca.png">

I disable "show in sidebar" because I don't want to see other dashboards there, only the one selected in the user settings.

**Comment by bramkragten** [comment]
Already fixed
