### ISSUE TITLE
Add Xiaomi Seat Toilet Wifi in Hassio

### ISSUE THREAD

**Issue by JeedHome44** [home-assistant/frontend#6966]
Hello,

Some Developper can add Xiaomi Seat Toilet wifi in Hassio?
I received one and i can find the token of the seat in Mi Home.

I don't know python, so i dearch developpers who want to add the seat toilet 

Thank you

**Comment by bramkragten** [comment]
This is the frontend repo. Please add request for new integrations on the forum.
