### ISSUE TITLE
Tanslation error (spanish)

### ISSUE THREAD

**Issue by alfonsolsl** [home-assistant/frontend#6967]
https://github.com/home-assistant/frontend/blob/50d37ce4f6f9b48265abc262d17c56c25e750ba0/translations/frontend/es-419.json#L2355

Should be '{type}' ?

![image](https://user-images.githubusercontent.com/6255385/93006381-1861a600-f521-11ea-806f-75a8051673a5.png)

**Comment by bramkragten** [comment]
Translations are handled through Localize, you can help fix this!

https://developers.home-assistant.io/docs/internationalization
