### ISSUE TITLE
Duplicate text on confirmation prompt when resetting Lovelace

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6968]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

![image](https://i.imgur.com/3RFftDR.png)

## Steps to reproduce

1. Create a new dashboard under Configuration -> Lovelace Dashboards
2. Press Edit dashboard to take control of it
3. Then go to Lovelace menu -> Raw configuration editor, select all and then save
4. You'll see same prompt

## Environment

- Home Assistant release with the issue: 0.115.0b7
- Last working Home Assistant release (if known): 
- Browser and browser version: 
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Fixed!
