### ISSUE TITLE
Problems with ExoPlayer and webview

### ISSUE THREAD

**Issue by bramkragten** [home-assistant/frontend#6973]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

The ExoPlayer is used in the Android app now since it supports more formats (like H.256) then the built-in web player in Chrome.

We draw a native player on top of the webview at the place the normal player would be.

There are a couple of problem with this:

- Elements that should be above the video element, like the sidebar, can no longer be above the player.
![image](https://user-images.githubusercontent.com/5662298/93017618-70a0b280-f5ca-11ea-8ab4-5c1c0da02df2.png)

- In Lovelace we use the video player as a background for cards (picture entity/glance card), this is no longer possible as the video will always be the top element.

- The video player does not scroll with the page, meaning it will stay static and block other UI elements.
![1599999594615](https://user-images.githubusercontent.com/5662298/93017936-b494b700-f5cc-11ea-8055-57f2fd2ecfde.gif)

- The video is not always positioned correctly probably caused by the animation of the dialog

## Expected behavior

Same or similar behavior as the native video element.

I don't think all these problems are fixable, as we will never be able to place elements above the video player.

I suggest we turn this feature off for the 0.115 release and start to look for solutions.

/cc @uvjustin 

## Steps to reproduce

Add Lovelace video card

## Environment

- Home Assistant release with the issue: 0.115.0b
- Last working Home Assistant release (if known): 0.114
- Browser and browser version: Android App
- Operating system: Android

## Configuration
Lovelace card:
```yaml
type: picture-entity
title: Gang
entity: camera.gang
camera_view: live
```

**Comment by uvjustin** [comment]
@bramkragten Sorry - I didn't encounter this in my setup because I was only using a regular picture-entity card without `camera_view: live` - once you click in to get the live view there is no toolbar or scrolling. Do you think these issues occur only with `camera_view: live`? If so, maybe we can just avoid using exoplayer in that case.
I'm also fine with taking it out for now, no point in causing headaches for 0.115.
