### ISSUE TITLE
Restrict sidebar swipe gesture while in edit mode

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6977]
## The request

When you are trying to customize your sidebar on mobile, and re-order things, there have been two different occasions where I accidentally dismissed the sidebar. I am not the only one, Rob had same issue. 

I think this swipe gesture should be restricted/disabled while in this mode, until the user presses DONE, to prevent accidental dismissals.

![image](https://i.imgur.com/tuWccKT.jpg)

**Comment by bramkragten** [comment]
Done!
