### ISSUE TITLE
Media Browser Panel - player source hard to read

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#6979]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

As the fix to https://github.com/home-assistant/frontend/issues/6946 the Player source was made smaller. I like the solution, everything fits now on mobile. One minor issue with it using secondary text though, is that it looks a bit awkward on the default light theme. Gray on blue is not easily readable. 

![image](https://i.imgur.com/HfHhTUq.png)

Plex here also says `err.message` when I think it's supposed to say entity not found... Not sure if that is frontend or integration specific. cc @jjlawren 

## Expected behavior

I don't really have a good solution. Maybe use primary text? Would that feel weird? It'd be more readable at least.

Secondary text probably works fine in most cases, including the default dark theme. It just looks a bit weird on the default light theme imo. This is a tiny thing, so feel free to close this if you disagree.

## Environment

- Home Assistant release with the issue: 0.115.0b9
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
You all and your old eyes 👀  :). I am going to change it to white. Paulus brought it up as well...

Thanks for logging as I probably would have forgot

**Comment by jjlawren** [comment]
I haven't added any support for Plex in the Source Browser. Not sure where this is failing.

**Comment by zsarnett** [comment]
The issue is the Grey text nothing with Plex 😄

**Comment by SeanPM5** [comment]
Well I tagged jj too as i thought there was maybe a plex integration issue with that error message... could have sworn it worked in the media browser panel before? 

Sorry for making this confusing by tossing something unrelated into this 😆

**Comment by jjlawren** [comment]
Check the state of the Plex `media_player` entity. I'm guessing it's "unavailable".

**Comment by SeanPM5** [comment]
Yeah that was the issue. It's working after I played something and it became re-available. 

Problem is instead of saying "Entity not currently available" or whatever it did before, now it's saying a vague `err.message` instead.
