### ISSUE TITLE
Button card doesn't execute script, shows more info

### ISSUE THREAD

**Issue by zsarnett** [home-assistant/frontend#6995]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml
type: button
entity: script.1600021998539
```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
Will take a look later today. Real work for now

**Comment by ludeeus** [comment]
This is not new @zsarnett checked the 20200716 release of the frontend, that also opens the more-info if something is not defined.

**Comment by ludeeus** [comment]
Fixed in https://github.com/home-assistant/frontend/pull/7018
