### ISSUE TITLE
Media Browser dialog header disappears after scrolling in Safari

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#7011]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

So another Safari-specific issue with the media browser.

When you scroll the dialog, the header is supposed to shrink and stay on top like this:
![image](https://i.imgur.com/qP0CcWN.png)

It does that initially. But after a tiny bit this header starts to disappear. Here is a screenshot of where it first starts to happen, you lose the breadcrumb trail link and the close button is no longer on-screen:

![image](https://i.imgur.com/HsataQK.png)

If you scroll a tiny bit more it goes completely off screen:
![image](https://i.imgur.com/Ls6kAMe.png)

Confirmed this doesn't happen in Chrome or Firefox, only Safari. On both macOS and iOS. 

It's not a huge deal but it does mean you have to scroll all the way back up to the top. 

## Expected behavior

behave same as chrome/ff, sticky header

## Steps to reproduce

1. In Safari, go to Spotify media browser dialog. 
2. Click Categories
3. Scroll. It will "break" by the third row of cover arts.

## Environment

- Home Assistant release with the issue: 0.115.0b9
- Last working Home Assistant release (if known): ??
- Browser and browser version: iOS companion app, macOS companion app (both Safari)
- Operating system: ios/macos

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
I hate safari more everyday 😅
