### ISSUE TITLE
Can't remove entities from cards when using the X on Android Chrome

### ISSUE THREAD

**Issue by gohassgo** [home-assistant/frontend#7024]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem
This issue was part of:
Issues picking entities for cards on Android Chrome #6947
When editing cards with the visual editor, entities cannot be removed. The X does not work.

## Environment

- Home Assistant release with the issue: Home Assistant 0.115.0b10
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
We will need more info, can't reproduce

**Comment by zsarnett** [comment]
I was able to reproduce on my production environment

**Comment by zsarnett** [comment]
![d0bf17204e3cd1bf800dd2c88631f109](https://user-images.githubusercontent.com/18730868/93391149-5a962a80-f834-11ea-8f55-316cac139090.gif)

**Comment by gohassgo** [comment]
Thanks @zsarnett, that's it!

**Comment by gohassgo** [comment]
It works properly on Firefox.
80.1.3 (Build #2015762835)

**Comment by bramkragten** [comment]
Seems like it doesn't only drag on the handle?

**Comment by bramkragten** [comment]
Still not able to reproduce

**Comment by gohassgo** [comment]
> Seems like it doesn't only drag on the handle?

Correct. One other strange behavior I see happens when dragging an entity down past the last entity. It creates a copy of the entity that was below the one dragged. This copy becomes  the new last entity.

If I can enable screen recording I'll upload a shot...

**Comment by gohassgo** [comment]
Also noticed that the down arrow to the right of the X does not work to pop up an entity list. It only works on the last, empty entity line that does not have an X.

**Comment by bramkragten** [comment]
@zsarnett you still able to reproduce?

**Comment by gohassgo** [comment]
![videotogif_2020 09 25_04 44 50](https://user-images.githubusercontent.com/28564848/94247073-9d1dce00-feea-11ea-968b-0d6a1605f8d9.gif)

**Comment by bramkragten** [comment]
Please try to drag it by the X, also version of Android, Chrome, etc?

**Comment by gohassgo** [comment]
Dressing by the x did not do anything.

Originally saw this problem when on Android 10, just updated yesterday to 11.
Android 11 Build RP1A.200720.009
Chrome version 85.0.4183.120
Home Assistant  0.115.1
Frontend version: 20200917.1 - latest

**Comment by gohassgo** [comment]
I just updated to 0.115.3 (from .1) and the "dragging entity to the bottom makes another entity" problem is fixed.

**Comment by zsarnett** [comment]
Yea I can reproduce on my production on my phone. But I cant figure out why its happening (also I didn't look into that much and forgot about this)

**Comment by gohassgo** [comment]
I found a way to delete entities by erasing the entity name and tap enter on the keyboard.

**Comment by gohassgo** [comment]
I upgraded to HA Core 0.116.0b0 (and see that Chrome updated to version 85.0.4183.127) and all problems are fixed.

- Dragging entities works and does not add more entities.
- The x deletes entities.
- Typing part of an entity correctly pops up the selector.

Thanks!
