### ISSUE TITLE
Allow thermostat card to use custom temperature sensor

### ISSUE THREAD

**Issue by Savjee** [home-assistant/frontend#7036]
## The request

The `thermostat` card has no option to use a custom temperature sensor. This would be useful for AC units controlled via an IR hub (like Harmony Hub, ESPHome IR Climate, ...) since they can't report the current room temperature.

Right now, this is what I get:

![28D1B9E4-3ED5-48A2-9051-736F14CCC762](https://user-images.githubusercontent.com/817109/93496678-cef1cc00-f90f-11ea-83b6-d9ad15df01d6.png)

Proposal: add a `temperature_sensor` attribute:

```yaml
type: thermostat
entity: climate.living
temperature_sensor: sensor.temperature_bureau
```

## The alternatives
My current workaround for this is using the [simple-thermostat](https://github.com/nervetattoo/simple-thermostat) which does support custom temperature sensors. 

Alternatively, I thought about creating a template climate integration, but that doesn't exist either.

## Additional information
/

**Comment by Misiu** [comment]
The target temperature is defined on climate entry, like so:

```
  - platform: generic_thermostat
    name: Salon
    heater: switch.podlogowka_salon
    target_sensor: sensor.temperatura_salon
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 30
```

and my target_sensor is a template sensor, like this:

```
  - platform: template
    sensors:          
      temperatura_salon:
        friendly_name: "Salon"
        unit_of_measurement: '°C'
        value_template: >-
          {{ states.sensor.salon_temperature.state | float - 2.8 }}
```

**Comment by Savjee** [comment]
Correct me if I'm wrong, bjt the `generic_thermostat` platform is useful for when you want to create your own thermostat, including the logic of when to heat and cool?

That's not what I'm after. My AC unit already has that built-in.
The problem is related to the fact that it's controlled through IR, and it doesn't send the current temperature back. Only the target temperature & mode it is operating in.

**Comment by Misiu** [comment]
@Savjee ok, now I understand your request.
I use the `generic_thermostat` so for me this always worked fine.
Your control is based on ESPHome? According to the docs (https://esphome.io/components/climate/ir_climate.html) this should be already supported.

**Comment by Savjee** [comment]
It is indeed based on ESPHome. Do you mean the `sensor` attribute? That's an internal reference to a temperature sensor connected to the ESPHome device (on a GPIO pin). In my case, the temperature sensor is Zigbee based and not physically connected to the hub.

I tried putting a Home Assistant entity_id in here and it won't compile.

All I'm trying to do is combine the existing climate component with another temperature sensor in the frontend.

**Comment by Misiu** [comment]
@Savjee do you have a spare DS18B20 or DHT11/DHT22? YOu could connect them to the ESPHome device and test this.
I think you might be right - ESPHome has access to sensors it is has connected.
You should also ask on the ESPHome GitHub repo, maybe there is a way to access sensors from HA.

**Comment by Savjee** [comment]
Attaching a custom sensor will be tricky, this is a pre-made unit and I don't want to mess it up. (Nor do I know if it has exposed GPIO pins).

But are right, there is an option to pull sensors from HA into ESPHome: https://esphome.io/components/sensor/homeassistant.html Everything is working as expected now.

Still feel like this is a bit of hack. Fetching a sensor value only to send it back, seconds later.

**Comment by Misiu** [comment]
@Savjee yes, that's a bit hacky 🙂 but it works.
Thx for the link

**Comment by etamtlosz** [comment]
Having the option to be able to use a custom temperature sensor makes sense.
I'm switching from my broadlink to esphome and It is lame to have 0 as temperature in the card, just because there's no temp sensor hooked up to my d1mini.

**Comment by BiasF** [comment]
It makes sense because the integrated sensors are not very accurate.
They are too near to the heater

**Comment by nattgris** [comment]
This card got a lot less usable some releases back, when it started to display the current temperature in BIG font in place of where the set temperature was previously. This is a *thermostat* card, not a temperature sensor card. It's main function is to change (and display) the *target* temperature, not to display the actual temperature. So I don't think this change was particularly good, but I realize not everyone thinks the same, and in some way it could be nice to combine the actual and target temperature in the same card. But because the current temperature is optional and not always available it's really not helpful to have a big fat zero as the main element of the card as in the screenshot above.

I think there are three options forward for this card, from least to most desirable:

1. Revert the change to display the current temperature, or whatever that change did.
2. Dynamically switch between the current layout (show both current and target temperature) and the previous layout (show only the target temperature) depending on whether the underlying climate entity provides a current_temperature or not.
3. As 2 but in addition allow to use an arbitrary temperature sensor entity as the current_temperature, overriding any value that may be provided by the climate entity (as the OP suggests).

This should not be fixed in the underlying integrations (ESPHome hacks etc.).

**Comment by bjonness406** [comment]
+1 on this, would be perfect!

**Comment by nattgris** [comment]
Since that change was declined, and after digging into what happened recently with the zero, I've tried to at least fix the display of the pointless zero (so option 2 in my list): #8095

For the functionality wanted here, maybe it's best to create a proxy climate custom integration that can combine an existing climate entity with a separate sensor.

**Comment by jkaberg** [comment]
I do not know if this apply's to this issue; but another issue is when an climate entry has several sensors (eg thermostats that have both Air and Floor) - often I find that the wrong one gets selected and thuss displays 0 (as the sensor is not in use)

The proposed fix here would allow me to override with the correct sensor, which would be alot better.

**Comment by bramkragten** [comment]
@jkaberg that would be something the integration should handle

**Comment by nattgris** [comment]
It would be really nice to be able to use templates in customizations, so you could write something like this

```yaml
customize:
  climate.living_room_hvac:
    current_temperature: '{{ states("sensor.living_room_temperature") }}'
```

Sadly, templates seem to be not evaluated in this context. Maybe that would be a good generic addition to Core that would be the best solution for this and other similar issues.

@jkaberg What are the actual state attributes for the climate entity? Check Developer tools -> States -> climate.gulvvarme_kjokken_thermostat (or what you've called it).

**Comment by jkaberg** [comment]
@nattgris 

Well thats funny 😄 

```
hvac_modes:
  - 'off'
  - heat
  - cool
min_temp: 15
max_temp: 30
target_temp_step: 1
current_temperature: null
temperature: 23
friendly_name: '-Gulvvarme_kjokken_thermostat'
supported_features: 1
```

**Comment by nattgris** [comment]
@jkaberg Yeah so the reason you see a zero in the thermostat card is exactly the issue discussed here, `current_temperature` is null. 

However in your case the actual thermostat controller appears to provide the temperature measurement (several in fact) but it is not exposed to MQTT in the correct way for HA to pick it up. The temperature measurements are provided as separate sensor entities which is fine, but one of the values needs to (additionally) be put in the current_temperature attribute of the climate entity.  I assume the MQTT device for your floor heating has been autodiscovered and not manually configured. See if whatever part of your system that provides the MQTT discovery data to HA can be configured to include the current temperature from the same MQTT topic as used for the `sensor.gulvvarme_kjokken_temperature_air_3` entity. See https://www.home-assistant.io/integrations/climate.mqtt/#current_temperature_topic for details.

**Comment by Jaytie2k7** [comment]
Any news on this? I'm using Fritz Dect 301 thermostats with this default-card. The thermostat displays current temps , which are way too high. I calculate the offset with another thermometer from AVM. But the thermostat card only displays the temp readings from the dect 301. 
Would be awesome, if I can choose any thermometer reading within my home assistant enviroment.

**Comment by bramkragten** [comment]
This should be solved in the core, not in the frontend.

**Comment by liquidbear99** [comment]
Any news on this?

**Comment by bramkragten** [comment]
You should create a feature request on the forum, not an issue. And please don't respond on this closed issue.
