### ISSUE TITLE
Jumping buttons in integrations panel

### ISSUE THREAD

**Issue by SNoof85** [home-assistant/frontend#7040]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When some integration has several configurations, when opening one of these config and moving the mouse to the back icon the Rename and Options (if present) buttons are jumping down a bit. This only happens on the last row of the integration list.

## Steps to reproduce

Go into integrations panel
If you have an integration with 2 or more configs click on one
Move the cursor to the back icon
Jump !

## Environment

- Home Assistant release with the issue: 0.115.0
- Last working Home Assistant release (if known): 0.114.4 i think...
- Browser and browser version: Chrome Version 85.0.4183.102
- Operating system: Win 10 1909

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
It is the scrollbar that makes it jump, because the card gets a little higher.

**Comment by SNoof85** [comment]
> It is the scrollbar that makes it jump, because the card gets a little higher.

Hey @bramkragten , unfortunately i can reproduce without scrollbar. Just set Chrome in full screen and then no scrollbar and same bug.

**Comment by SNoof85** [comment]
Seems this is also the case on other cards of other integrations. On the middle line on MQTT integration as example if if just put the cursor on the 3 dots the buttons will jump down a bit.

**Comment by spacegaier** [comment]
@SNoof85 I cannot reproduce the issue in latest dev, neither in Chrome nor FF (on Win 10). Can you please check again? If you still have the issue, could you upload a GIF to illustrate the behavior?

**Comment by SNoof85** [comment]
Hi,

Seems i forgot that issue for a long time now 😋 
I can't reproduce anymore now with 2020.12.01. Looks like something has changed.

I guess can be closed 👍
