### ISSUE TITLE
Template based values displayed as "Invalid Date" when rendered in ios... though displayed correctly in Desktop browser

### ISSUE THREAD

**Issue by mwunderling** [home-assistant/frontend#7042]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem
Was told this is a frontend problem...  using templates to calculate how much time has passed since a named sensor was last updated. This works as expected when the UI is displayed in a browser on a desktop, but only get "invalid date" values displayed when accessed on ios devices.

Sample of UI output in each environment
![InvalidDate](https://user-images.githubusercontent.com/22336325/93527064-30547380-f8ed-11ea-99bb-012b674d15a2.PNG)

Template code each sensor is based on:
![Code_jNTfH1Q1PR](https://user-images.githubusercontent.com/22336325/93527276-78739600-f8ed-11ea-8b6c-b1766e6933bc.png)

## Environment
HA 0.114.4 in Docker on QNAP NAS
Desktop: Win10/Chrome/Firefox/Vivaldi
iOS: 13&14 on iphone xr, observed behavior in both mobile app & firefox

## Additional information
Trying to determine if this is something unique to ios devices and needs to be fixed in HA....or if there's something I can add to the template to get the values to render correctly when displayed on an ios device

**Comment by gadgetchnnel** [comment]
I've encountered this myself, it appears that **timestamp_local** doesn't give you proper ISO 8601 datetime format (with "T" separating the date and time) and iOS doesn't accept them. Replacing this with `timestamp_custom('%Y-%m-%dT%H:%M:%S%z')` gives a valid ISO 8601 datetime, which should be accepted on iOS.

**Comment by bramkragten** [comment]
@gadgetchnnel is right :-)

**Comment by mwunderling** [comment]
Good to know. Thanks @gadgetchnnel!

@bramkragten seems like this could be relevant to many iOS mobile app users. If this is not already documented somewhere, is there a place it should go? I don't mind creating the write-up if it helps.

**Comment by zsarnett** [comment]
https://www.home-assistant.io/integrations/template

Adding a note here may be good

**Comment by mwunderling** [comment]
@zsarnett Do you think https://www.home-assistant.io/docs/configuration/templating may be a little more relevant since both timestamp_local & timestamp_custom are discussed (...albeit not in the terms highlighted in this thread)? If so, I can put together some suggested edits.

**Comment by zsarnett** [comment]
Sure. Frenck who reviews doc prs may be a better person to ask. But if you create the PR he will let you know. Any change will be good

**Comment by frenck** [comment]
Re-opening this issue.

IMHO this is a bug, our frontend should not behave differently in this case. Especially considering we ship the iOS application. Browsers and platforms behave differently, can't we solve this?

I'm not keen on approving the documentation PR either, as I do not believe in documenting bugs, but fixing them.
