### ISSUE TITLE
Expand / Collapse not working for side tray on Android

### ISSUE THREAD

**Issue by bverkron** [home-assistant/frontend#7043]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Tapping the expand / collapse button at the top of the side tray does nothing on Android (at least the device / browser / apps I tested). If it's expanded it stays expanded and if collapsed it stays collapsed when the button is tapped. Though it still works on other devices (Safari & Chrome on macOS, Safari on iOS)

## Expected behavior

The tray expands / collapses when the button it tapped.

## Steps to reproduce

    1. Open the HA Dashboard on an Android device (might be limited to certain models / OSs?)
    2. Tap the expand / collapse icon. Does not show / hide the side tray

## Environment

- Home Assistant release with the issue: 0.115.0
- Last working Home Assistant release (if known): 0.114.4
- Browser and browser version: Brave 1.13.87, HA app, WallPanel
- Operating system: Android 10 / OneUI 2.0

## State of relevant entities

```yaml
N/A
```

## Problem-relevant configuration

```yaml
N/A
```

## Javascript errors shown in your browser console/inspector

```txt
Not aware of how to inspect the browser console/errors, etc but can check for errors if someone can guide me on where to look on the Android device.
```

**Comment by KennethLavrsen** [comment]
You say it works on IOS. Not on my iPad pro. I cannot collapse the side menu since upgrading to 0.115

In the IOS app I can collapse it and expand if I try 50-100 times and hit the lucky spot so in reality it does not work there either. It really cause a usability error because when you use features like file editor addon you really need that extra screen width.

**Comment by bverkron** [comment]
> You say it works on IOS. Not on my iPad pro. I cannot collapse the side menu since upgrading to 0.115

I only had an iPhone, which I forgot to specifically mention, and it worked. However it looks like a different element / mechanism on a small screen like that which is probably why. Either way looks like it's been fixed / merged. Now we just have to wait for the release. Thanks @bramkragten!

**Comment by KennethLavrsen** [comment]
Did not make it in time for 0.115.1 it seems because it is still in 0.115.1.
