### ISSUE TITLE
Entity drag-to-reorder in a card duplicates the entity if dragged to bottom position

### ISSUE THREAD

**Issue by apaperclip** [home-assistant/frontend#7045]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When using the drag-to-reorder feature, items dragged to the last position duplicate the item instead of moving it.  Clicking the X to remove the duplicated item can removes all instances of that entity in the list depending how many dupes you create.  Clicking save clears it up unless the removal of it removed all other instances, in which case that entity will need readded to the card.

## Expected behavior

Dragging an entity to the bottom should move it just like moving it to any other position.

## Steps to reproduce

1. Click edit on a card. I used an entities card that had 4 entities in it.
2. Drag any of the top three entities and to/below the fourth so it becomes the last
3. The dragged entity is duplicated.

## Environment

- Home Assistant release with the issue: 0.115 / Frontend version: 20200917.1
- Last working Home Assistant release (if known): new feature in 0.115
- Browser and browser version: 
> - Chrome 86.0.4240.22 (Official Build) beta (64-bit)
> - Edge Version 85.0.564.51 (Official build) (64-bit) 
> - Chrome Canary Version 85.0.564.51 (Official build) (64-bit)

- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
Definitely replicated this but I couldn't find an immediate fix tbh I didn't spend much time on it.

**Comment by spacegaier** [comment]
Same here. Can reproduce, but did not find anything weird in the debugger so far. There are only three entities processed and passed along as config entries containing the correct new order after the drop.
