### ISSUE TITLE
Automation: Error when saving

### ISSUE THREAD

**Issue by zsarnett** [home-assistant/frontend#7046]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When saving an Automation I am receiving the following error: `Message malformed: Integration '' not found`

![image](https://user-images.githubusercontent.com/18730868/93551443-7df3cf00-f933-11ea-9665-ab8d45590ec6.png)

## Expected behavior

Save works with no error 😄 

## Steps to reproduce

1. Create Automation
2. Leave default data
3. Try to save it

## Environment

- Home Assistant release with the issue: 0.115.0
- Last working Home Assistant release (if known): 0.114
- Browser and browser version: Chrome `85.0.4183.102 (Official Build) (64-bit) (cohort: Stable)`
- Operating system: Windows 10

## Javascript errors shown in your browser console/inspector

```txt
POST http://192.168.xx.xxx:8123/api/config/automation/config/1600397932803 

body:
message: "Message malformed: Integration '' not found"
__proto__: Object
error: "Response error: 400"
status_code: 400
```

**Comment by bramkragten** [comment]
What is the message sent to the backend?

**Comment by spacegaier** [comment]
I can confirm the issue. This is the payload that gets sent to the backend in my case:

```json
{
	"alias": "New Automation",
	"description": "",
	"trigger": [
		{
			"platform": "device",
			"device_id": "",
			"domain": "",
			"entity_id": ""
		}
	],
	"condition": [],
	"action": [
		{
			"device_id": "",
			"domain": "",
			"entity_id": ""
		}
	],
	"mode": "single"
}
```

**Comment by spacegaier** [comment]
I traced it a bit. It is the validation of the trigger that fails (since of course that's the first part that is checked). The domain `''` cannot be resolved.

https://github.com/home-assistant/core/blob/c291d4aa7dcd2ce7dc0b95ce03068140ac9075d4/homeassistant/requirements.py#L48

**Comment by bramkragten** [comment]
Did you select a device?

**Comment by spacegaier** [comment]
No, as @zsarnett stated in his steps: Open the editor, but do not set anything, just save. The editor is using the default data, which means that trigger type "Device" is selected, but no actual device/entity/... hence the empty data in the payload to the backend.
