### ISSUE TITLE
Filter out @eaDir directories in Media Browser on Synology

### ISSUE THREAD

**Issue by aptonline** [home-assistant/frontend#7054]
## The request

The new media browser feature with Home Assistant is great but because my Home Assistant install is in docker on my Synology its showing '@eaDir' directories which are usually invisible.  Would be great if these directories could be filtered out by default.

## The alternatives

N/A

## Additional information

N/A

**Comment by ludeeus** [comment]
I don't think it should be up to the frontend to hide these, it should just show whatever the integration gives.
You should open a feature request on the [forums](https://community.home-assistant.io/) for this integration :+1:
