### ISSUE TITLE
Calendar card editor - deleting title doesn't update preview/code

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#7056]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Noticed that in the Calendar card editor when removing a title, it never gets removed.

This can be reproduced in the demo, here you can see there is no title in the field in GUI but it's there in the preview/code.

![image](https://i.imgur.com/vrqxswU.png)

1. If you type "Test" and then delete each character one by one it will update until the last character (so you will be left with "T"). Almost like it's requiring something in that field.
2. If you type "Test" and then select it all and press delete (whole word at once) it will say "Test"

## Environment

- Home Assistant release with the issue: 0.115.1
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bverkron** [comment]
I noticed similar behaviour and could not remove the title even after saving, re-opening editor, removing title, saving again. It was permanently stuck
