### ISSUE TITLE
Calendar list view should start today (or have the option of doing so)

### ISSUE THREAD

**Issue by davidmonro** [home-assistant/frontend#7064]
## The request
The current calendar card list view appears to start on the previous Sunday, which makes it useless towards the end of the week
as everything relevant is now scrolled off the bottom (especially for wall mounted displays etc). Please allow at least the option of showing the next few days with today at the top.

## The alternatives
the now discontinued  ljmerza / calendar-card community extension did this right

**Comment by bverkron** [comment]
+1. Yes please!

**Comment by snipes040** [comment]
+1 Please!
