### ISSUE TITLE
More info Sensor Graph Tooltip obscured

### ISSUE THREAD

**Issue by glitter-ball** [home-assistant/frontend#7070]
iPhone SE, Microsoft Edge.

When I open Glance Card and use pop up to read values at the bottom of the graph, the “No logbook entries found.” Text obscures the pop up so the value can’t be read:
![67094D8B-4803-4B28-95D9-27263BB9D0CD](https://user-images.githubusercontent.com/57917148/93671727-6173a600-fa9d-11ea-97fb-d472e46f8acc.jpeg)
![CC657179-AB45-41C6-B25A-29554C6E907C](https://user-images.githubusercontent.com/57917148/93671759-a7306e80-fa9d-11ea-9d1f-4ce2f1eab892.jpeg)

**Comment by glitter-ball** [comment]
On Firefox on Windows 10, the tooltip sits over the "No logbook entries found." text, so maybe it's an issue with Microsoft Edge rendering?
![image](https://user-images.githubusercontent.com/57917148/93689326-7106e500-fac5-11ea-8298-bcdc5d24aa87.png)

Microsoft Edge on Windows 10 also renders it OK:
![image](https://user-images.githubusercontent.com/57917148/93689338-a6133780-fac5-11ea-9e86-ba65a7324901.png)

So, the issue is something around tooltip rendering in Microsoft Edge 45.8.10 on iPhone SE running iOS 13.6.1. The tooltip is sitting behind the text box "No logbook entries found" and is being obscured by it, rather than floating over it. Safari on iOS 13.7 is also OK.

![image](https://user-images.githubusercontent.com/57917148/93689405-25087000-fac6-11ea-9a65-cb3c79e788a1.png)

**Comment by agneevX** [comment]
This is an issue with MobileSafari too.

<img src="https://user-images.githubusercontent.com/19761269/94721050-ed75af80-0372-11eb-87cb-7cd1d1743cbc.png" width="300">

**Comment by glitter-ball** [comment]
Safari on my wife’s iPhone SE did not have the issue. Edge on my iPhone SE does have the issue. So there’s more going on...

**Comment by agneevX** [comment]
> Safari on my wife’s iPhone SE did not have the issue.

That's weird, could be a caching issue. Maybe try in Private @glitter-ball ?

**Comment by glitter-ball** [comment]
Tried Edge in Private on iPhone SE and problem still there.

**Comment by glitter-ball** [comment]
Thanks - that's a good solution and avoids some unnecessary processing too.
