### ISSUE TITLE
Cookies support for html pages in webpage card in Chrome browser

### ISSUE THREAD

**Issue by smithbill17** [home-assistant/frontend#7073]
**Home Assistant Android version:** N/A

**Android version:** 10

**Phone model:** Xiaomi Redmi Note 7

**Home Assistant version:** 0.115.1

**Last working Home Assistant release (if known):**

**Description of problem:**
**Cookies support for html pages in webpage card:**

With a Webpage Card on a Dashboard with the iframe configured to point to any URL web page which requires to store a cookie (eg. http://www.itv.com/news), the cookie is NOT stored and EVERY time the page is refreshed, it again requests storing the cookie. This makes the Webpage Card unusable in Android Chrome.

This happens using Chrome 85.0.4183.101 installed on Android 10. It does not happen if using the Home Assistant 'app' installed from the Google Playstore.

Also, the latest Firefox installed from the Playstore does not exhibit the problem.

**Traceback (if applicable):**

**Screenshot of problem:**
![Screenshot_20200919-183007328](https://user-images.githubusercontent.com/66825587/93681816-422d4680-faa6-11ea-94a7-500e73f96a21.jpg)

**Additional information:**

This is the same as Issue home-assistant/android#548 but that pertains **only** to the Home Assistant app, whereas this issue pertains to the natively installed Android Chrome browser.

I've tried enabling the Chrome Flags for #same-site-by-default-cookies, #improved-cookie-controls & #improved-cookie-controls-for-third-party-cookie-blocking as well as switching Chrome to allow all 3rd Party cookies. Nothing works.

I am not using Home Assistant with SSL.

**Comment by smithbill17** [comment]
Issue is still present in version 0.115.2

**Comment by zsarnett** [comment]
That's because no one has done anything for it. No need to comment for every release ☺️

**Comment by ludeeus** [comment]
This is not something we can solve, this support needs to be implemented on the site you are loading in the iframe.
More info here <https://medium.com/trabe/cookies-and-iframes-f7cca58b3b9e>

Can easily be reproduced outside of HA with this:
```
<!DOCTYPE html>
<html>
    <body>
        <iframe src="https://www.itv.com/news" title="W3Schools Free Online Web Tutorials" height="1024px" width="1024px">
        </iframe>
    </body>
</html>
```

**Comment by smithbill17** [comment]
Okay, thanks for the update.

However, as Chrome now assumes that sites without a SameSite attribute will be treated as SameSite=Lax, meaning the default behavior will be to restrict cookies to first party contexts only, then websites for major organisations (such as UK broadcaster ITV) embedded into iframes as implemented by the Webpage Card in Home Assistant, will no longer work without the incessant Cookie prompt.

For those who find there way here with this issue, I found an apparent 'workaround' where you can go to chrome://flags and change both _same-site-by-default-cookies_ & _cookies-without-same-site-must-be-secure_ to Disabled. Whether that is considered 'secure' or not is up to the individual.

**Comment by jpoeppelman1** [comment]
Hello!  I'm using Chrome and cannot find these flags anywhere when I search.  Is there a different flag to use?
