### ISSUE TITLE
Media player not showing play or pause

### ISSUE THREAD

**Issue by blair287** [home-assistant/frontend#7074]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Using bravia integration if I add the entity media_player into an entity card it will shows previous play/pause and next controls.

But when that entity is expanded the play/pause control disappears only previous and next are shown.

## Expected behavior

Play and pause should also be in the expanded card for the entity like it used to be.

Play pause is there in card on 114.4 screenshot below.
![Screenshot_20200922-024341](https://user-images.githubusercontent.com/44187409/93837330-9f2f2500-fc7d-11ea-80ef-94b18d23fe28.jpg)

## Steps to reproduce

Using bravia integration, add to Lovelace in entities card and turn TV on play and pause controls are shown. Then click on the entity in the card that pops up play and pause is missing.

## Environment

- Home Assistant release with the issue: 0.115.1
- Last working Home Assistant release (if known): pretty sure we're there on 0.114
- Browser and browser version: chrome or android app tested.
- Operating system: proxmox

## State of relevant entities

```

```
![Screenshot_20200919-211601](https://user-images.githubusercontent.com/44187409/93688387-60eb0780-fabd-11ea-8b45-90c9e4473652.jpg)

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

![Screenshot_20200919-210659](https://user-images.githubusercontent.com/44187409/93688393-73fdd780-fabd-11ea-9ca2-ebe724824cd3.jpg)
Play pause shown

![Screenshot_20200919-210711](https://user-images.githubusercontent.com/44187409/93688402-811ac680-fabd-11ea-8602-f0f502729075.jpg)
Play pause missing.

**Comment by blair287** [comment]
What info do you require @zsarnett ?

The play pause still works but when you open the media card where the pop up box comes up the play pause is missing.

Can provide any info you need thanks.

**Comment by kg333** [comment]
Confirmed this issue is still present for the Samsung TV integration in 0.117.4 using Lovelace picture-elements cards with state-icon popup:
![image](https://user-images.githubusercontent.com/4220833/98190827-ea2b9180-1ee5-11eb-9720-0fc60eed0eee.png)

I did confirm that the media_player entity in question responds to the media_play_pause service; the button is merely missing in Lovelace in both Firefox and the Home Assistant Android app.
