### ISSUE TITLE
"Unable to connect to Home Assistant" error page not themed (white on white)

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#7077]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I am using the default dark theme. Something went wrong when updating to 0.115.2 and I am getting the "Unable to connect to Home Assistant" error page. It is displaying the primary text color in white (consistent with what the dark theme should be), but the actual background of the page is white too (incorrect) so you cannot read the text. 

![image](https://i.imgur.com/6DPg5vj.png)
![image](https://i.imgur.com/fRV1fOS.png)

## Expected behavior

Needs to have a black background (I am using the dark theme) so the white text is visible... Or black text so it's visible on the white background.

## Environment

- Home Assistant release with the issue: 0.115.0b2
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

relevant supervisor logs
```
20-09-20 03:26:02 INFO (SyncWorker_2) [supervisor.docker.interface] Stop homeassistant application
20-09-20 03:27:13 INFO (SyncWorker_2) [supervisor.docker.interface] Clean homeassistant application
20-09-20 03:27:37 INFO (MainThread) [supervisor.homeassistant] Update pulse/client.config: /data/tmp/homeassistant_pulse
20-09-20 03:27:38 ERROR (SyncWorker_7) [supervisor.docker] Can't start homeassistant: 403 Client Error: Forbidden ("endpoint with name homeassistant already exists in network host")
20-09-20 03:27:38 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-67677' coro=<process_lock.<locals>.wrap_api() done, defined at /usr/src/supervisor/supervisor/utils/__init__.py:23> exception=HomeAssistantUpdateError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 32, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/homeassistant/core.py", line 202, in update
    raise HomeAssistantUpdateError()
supervisor.exceptions.HomeAssistantUpdateError

```

**Comment by rauljerico** [comment]
Same issue here

when I write the credentials, it says: something was wrong

**Comment by ludeeus** [comment]
Not the same @rauljerico this issue is about styles.
@SeanPM5 I'm not able to replecate this :/ 
![image](https://user-images.githubusercontent.com/15093472/93892103-6ed29f80-fcec-11ea-83e3-92ef22a1fe33.png)

**Comment by bramkragten** [comment]
Is your browser is light or dark mode?

**Comment by SeanPM5** [comment]
Ah I think that might be why.

My main computer doesn't even have dark mode at all (on an older version of macOS for certain app compatibility). So the system appearance is light, and theme in Home Assistant is set to dark.

I suspect it's depending on the OS level system appearance for background color (light in my case), but using the theme selection for primary text color (white text on the dark theme). So that's how I end up with white-on-white. Not sure though.

**Comment by bramkragten** [comment]
Yes, that probably is the issue

**Comment by mrand** [comment]
Not stale
