### ISSUE TITLE
Lack of error handling on user creation

### ISSUE THREAD

**Issue by agilob** [home-assistant/frontend#7079]
![image](https://user-images.githubusercontent.com/2544251/93717416-381e4d00-fb65-11ea-8951-201e7cd4a75b.png)

No error message is displayed, no progress bar, nothing, just me waiting for "Create account" to finish whatever it's doing.

**Comment by zsarnett** [comment]
Please fill out the issue template

**Comment by bramkragten** [comment]
Check the logs of the backend, it should tell us what is going wrong.

**Comment by agilob** [comment]
Yea, I found the error was read only docker volume, but still there should be error label on this page.
