### ISSUE TITLE
Automation time_pattern is not working well since 0.114

### ISSUE THREAD

**Issue by ruzickav** [home-assistant/frontend#7084]
I have found an issue started in 0.114. Automation is not triggered on specified time_patter when added through GUI. 
This is added through GUI - not working - it is starting every whole hour (for example 3:00)
```
  - minutes: '30'
    platform: time_pattern
```

Manually change it in yaml - working well
```
  - minutes: 30
    platform: time_pattern
```

Time_patern /x is working well. "At time" is working well too.

**Comment by zsarnett** [comment]
Please fill out the Issue Template
