### ISSUE TITLE
Password Autofill Unavailable (BitWarden)

### ISSUE THREAD

**Issue by JeffResc** [home-assistant/frontend#7086]
## The request
The username and password field of the login page is not compatible with [BitWarden](https://bitwarden.com/). BitWarden is available as an [addon](https://github.com/hassio-addons/addon-bitwarden) so I believe that others here use it too. I think the autofill is unavailable due to the fact that the `input` field for username/password do not have `id="username"` or `id="password"` in their respected fields, but I would have to look into it more before confirming that.
![Screenshot](https://i.imgur.com/sbvkfPn.png)

## The alternatives
I'm not sure that any other alternatives exist for this issue.

## Additional information
I am familiar with HTML and tried making these changes myself, but I was unable to find where to add this information due to the dynamically generated login form. Any guidance on this would be much appreciated.

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/issues/3133
