### ISSUE TITLE
OZW Integration Configuration - "Select an OpenZWave Instance"

### ISSUE THREAD

**Issue by kpine** [home-assistant/frontend#7088]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I see two problems related to the OpenZWave integration configuration, both occur when the MQTT broker is offline.

When the broker is offline:
1. And HA is online, the integration configuration shows that the ozw daemon is online and everything is OK. I can click on Add and Remove node buttons without any kind of indication that they would fail.
2. And HA is restarted, the integration configuration asks me to "Select an OpenZWave Instance" and has a blank page.

## Expected behavior

I would expect that some kind of error/warning is showing that the ozwd instance is not available, or it was unable to find any instances.

## Steps to reproduce

For scenario 1:

While HA is running:
1. Stop the MQTT broker.
2. Go to Configuration -> Integrations -> OpenZWave -> Click Configure

Observe that the status of the instance is showing whatever it was prior to the broker shutdown. Notice you can click on the service buttons, which won't do anything.

Presumably this is more of an ozw integration/HA problem since it's just rendering the data the backend provides.

For scenario 2:

1. Stop HA
2. Stop the MQTT broker.
3. Start HA.
2. Go to Configuration -> Integrations -> OpenZWave -> Click Configure

Observe that the page is basically empty. It says "Select an OpenZWave Instance" in the header, with body text "You have more than one OpenZWave instance running. Which instance would you like to manage?".

"Select an OpenZWave Instance" is usually only prompted when more than one ozwd instance is seen. When there is only one instance it will select that one automatically. In this case, it sees 0 instances and still prompts. Preferably that'd be some kind of other message indicating that no instances are seen.

## Environment

- Home Assistant release with the issue: I observed in 0.115.2 in my production setup. For testing I am using 0.116.0.dev20200921.
- Last working Home Assistant release (if known): Never, this is new to 0.115.
- Browser and browser version: N/A
- Operating system: N/A

## State of relevant entities

N/A

## Problem-relevant configuration

N/A

## Javascript errors shown in your browser console/inspector

None

## Additional information

None

**Comment by andyfsimon** [comment]
I have the same. I am trying to move from Zwave to Openzwave but this is stopping me.
I tried on my old venv instance, a new instance installed with the preconfigured VM on KVM (so with a totally clean config) but I always have this problem.

**Comment by urbanscribe** [comment]
same issue here (select text + no choices).  
like andysimon trying to move from ZW to OZW but this is a show stopper.

**Comment by pauled23** [comment]
Same error message with no choices here. 

I see the OpenZwave add-on showing success connecting to the MQTT broker in it's logs. I am attempting to migrate from the Zwave integration to the OpenZwave integration.

**Comment by cgarwood** [comment]
Just curious, how is this preventing people from migrating? The config panel as it currently exists is just informational aside from the add/remove node buttons but there are services you can call for that.

**Comment by kpine** [comment]
It shouldn't, this issue is just a symptom of some other problem (e.g. no MQTT broker/topic) and is just a cosmetic issue.
