### ISSUE TITLE
Ingress addons alunched from sidebar return 401: Unauthorized

### ISSUE THREAD

**Issue by mikosoft83** [home-assistant/frontend#7090]
## The problem

When I try to launch any Ingress based addon from sidebar I get 401: Unathorized. This happened just randomly one day on all my devices (3 different computers, android and ios app, ipad app and also in private mode) and has been like that since (several days now). Restarting HA, HassOS or the whole Pi didn't help. The same behavior happens with File Editor, Node Red, ESPHome etc. When I try to launch WebUI directly from Addon page, it works fine.

## Environment

- Home Assistant Core release with the issue: 0.114 and 0.155
- Last working Home Assistant Core release (if known): 0.114
- Operating environment (OS/Container/Supervised/Core): OS
- Integration causing this issue: ingress
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information

![has1](https://user-images.githubusercontent.com/63317931/93598143-90661b00-f9bc-11ea-9521-fc008757a918.png)
![has2](https://user-images.githubusercontent.com/63317931/93598145-91974800-f9bc-11ea-8585-bf75b7cea6c4.png)

**Comment by ludeeus** [comment]
The cookie handling changed a while back to be ready for the upcoming samesite requirements.
How are you accessing it? IP? mDNS? Home assistant cloud? Proxy? Tor? Does it matter?
What type and version of browsers?
Are anything logged to browser console?

**Comment by lovelylain** [comment]
The cookie is `Name=ingress_session	Path=/api/hassio_ingress/	SameSite=Strict`, maybe it's the Path and SameSite property cause the problem.

**Comment by ludeeus** [comment]
They are both correct, now answer my questions.

**Comment by lovelylain** [comment]
ok, it's my browser dit not handle `SameSite=Strict` correctly, I switch to latest chrome and the problem gone.

**Comment by ludeeus** [comment]
@mikosoft83 Can you take a look at https://github.com/home-assistant/frontend/issues/7090#issuecomment-696384358?
and/or check your browser version

**Comment by lovelylain** [comment]
But I think you guys are too radical. I tried a variety of browsers, including PC browsers and Android browsers. Only the latest version of chrome will not show `401: Unauthorized`.

latest chrome:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
```

tried PC browsers:
```
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.25 Safari/537.36 Core/1.70.3775.400 QQBrowser/10.6.4208.400
```

tried Android browsers:
```
Mozilla/5.0 (Linux; U; Android 9; zh-cn; MI 6 Build/PKQ1.190118.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.141 Mobile Safari/537.36 XiaoMi/MiuiBrowser/11.4.17

Mozilla/5.0 (Linux; Android 9; MI 6 Build/PKQ1.190118.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.120 MQQBrowser/6.2 TBS/045331 Mobile Safari/537.36 MMWEBID/5252 MicroMessenger/7.0.18.1740(0x2700123B) Process/tools WeChat/arm64 NetType/WIFI Language/zh_CN ABI/arm64
```

**Comment by mikosoft83** [comment]
> @mikosoft83 Can you take a look at [#7090 (comment)](https://github.com/home-assistant/frontend/issues/7090#issuecomment-696384358)?
> and/or check your browser version

Sorry for being a little late here but my computer is currently stowed away since the room it was in was remodeled. 
The mobile apps started working by themselves.
I am using Vivaldi browser (chromium based). I checked and for some reason it stopped notifying me of updates so I forgot to update. After I updated it the Ingress stuff is now working. Thanks for your help, I wouldn't have noticed the browser was so out of date.

**Comment by ludeeus** [comment]
@lovelylain I have tested this with multiple browsers on desktop (Windows/Ubuntu/MacOS) and mobile (Android 9/iOS 13), none of which have any issues with connection.

**Comment by mikosoft83** [comment]
Well, sorry to reopen, but it happened again, out of the blue, without me updating anything. I think I was on sup 248, I updated Core after that, also Sup but it's the same, 401: Unauthorized.

**Comment by ludeeus** [comment]
My comment still stands <https://github.com/home-assistant/frontend/issues/7090#issuecomment-697231285>

**Comment by mikosoft83** [comment]
I updated my browser and it works again. It was just a minor update.

@ludeeus do I need to religiously update my browser to prevent this from happening? It feels kinda silly.

**Comment by ludeeus** [comment]
Should not need to.
The browser should have the necessary support, or not, on a version that should not magically disappear :shrug: 

Closing this for now, if/when it happens again, please open a new issue and provide the details I asked for :+1:

**Comment by Tyde** [comment]
I see this issue happening again in my firefox, but not on chrome.

The request parameters for Firefox are:

    GET /api/hassio_ingress/Hg-0CXeijTkA-4E4a_okY-qCMbX4dkKN-eX4NoYE1Uc/ HTTP/1.1
    Host: 192.168.178.44:8123
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    Accept-Language: de,en-US;q=0.7,en;q=0.3
    Accept-Encoding: gzip, deflate
    DNT: 1
    Connection: keep-alive
    Referer: http://192.168.178.44:8123/core_configurator
    Upgrade-Insecure-Requests: 1
    Pragma: no-cache
    Cache-Control: no-cache

While on Chrome it sends the following:

    GET /api/hassio_ingress/Hg-0CXeijTkA-4E4a_okY-qCMbX4dkKN-eX4NoYE1Uc/ HTTP/1.1
    Host: 192.168.178.44:8123
    Connection: keep-alive
    Upgrade-Insecure-Requests: 1
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
    Referer: http://192.168.178.44:8123/core_configurator
    Accept-Encoding: gzip, deflate
    Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
    Cookie: ingress_session=#REDACTED#

So it seems like that Firefox is not sending a `ingress_session` cookie. I alse cleared all data for this site on Firefox but that did not help. Looking at the cookie-store for the site Firefox does indeed show a cookie called `ingress_session`, but it isn't part of the request header. Is this an issue with firefox?

**Comment by ludeeus** [comment]
Firefox does not send any cookies when their "Enhanced Tracking Protection" is set to Strict.
They have a warning in their settings:
![Screenshot from 2021-08-14 14-33-41](https://user-images.githubusercontent.com/15093472/129446498-fbd19f63-950d-4e27-bcab-499d90586d3e.png)
`about:preferences#privacy`

**Comment by Tyde** [comment]
Yep thank you that was the issue

**Comment by felurx** [comment]
A note for those who don't want to lower their privacy settings (like me): You can just add an exception by clicking the shield next to the URL and toggling the switch off :)
