### ISSUE TITLE
Allow use of the Escape key to dismiss dialog boxes (and use Y or Return to click yes).

### ISSUE THREAD

**Issue by jschwalbe** [home-assistant/frontend#7094]
## The request

As per a recent [pull request](https://github.com/home-assistant/frontend/pull/6741) from @ludeeus, which is to allow clicking anywhere outside a dialog box to dismiss it, I similarly propose allowing the use of the keyboard to dismiss dialog boxes. Specifically, I would love to be able to press the Escape key on the keyboard to make the dialog box "go away", just like clicking outside the dialog box now will do.

![image](https://user-images.githubusercontent.com/8005921/93838501-dbe82580-fc57-11ea-9e60-9d1fa381e2f8.png)

## The alternatives
Alternative/additional key options:
Y = yes, N = no
Enter = yes

Also might make sense to make the dialog boxes underline the Y in **Y**es or the N in **N**o.

## Additional information
Nothing else to say besides this would be amazing and had [21 votes](https://community.home-assistant.io/t/wth-cant-i-hit-return-on-my-keyboard-to-select-yes-and-esc-to-select-no/221152) during WTH month.

**Comment by ludeeus** [comment]
The PR you referenced added this as well to the same type of dialogs (prompts).
Where is this not working?

I tested it will all I could find, and where I can click outside, I can also use esc.

**Comment by Misiu** [comment]
@ludeeus this doesn't work for integration rename or integration options.
Enter works when I rename integrations, but clicking outside or the ESC key doesn't.
Tested on 0.116.0.dev0

**Comment by ludeeus** [comment]
Those are not prompts so that is expected.
Where you can change a value we do not want a user to accidentally close the dialog.

**Comment by Misiu** [comment]
> Those are not prompts so that is expected.
> Where you can change a value we do not want a user to accidentally close the dialog.

Fair enough, but Enter still works for rename, so Escape should too, or both shouldn't work. This would make things consistent.

**Comment by jschwalbe** [comment]
Guess I spoke too early. I updated HA to newest and esc key works. Great. :)

**Comment by blizzrdof77** [comment]
One instance where the Escape key still doesn't have the expected _dismiss_ behavior is on the **"Integrations"** page (`/config/integrations`) when the **"Add Integration"** dialog box is open (_see screenshot_).

![image](https://user-images.githubusercontent.com/890252/103301264-03752980-49cf-11eb-9efa-ef451c75f67e.png)

**Comment by CptnWookie** [comment]
I might have missed something but this is still not working in the following scenarios : 
- Adding a new Integration: Configurations-->Integrations-->Add Integration
- Managing Add-On Repositories: Supervisor-->Add-On Store-->3 dots-->Repositories

FYI, it does work the HACS menu.

**Comment by CptnWookie** [comment]
I might have missed something but this is still not working in the following scenarios :

    Adding a new Integration: Configurations-->Integrations-->Add Integration
    Managing Add-On Repositories: Supervisor-->Add-On Store-->3 dots-->Repositories

FYI, it does work the HACS menu.
