### ISSUE TITLE
Terminal and SSH configuration page is too broken to actually enable SSH

### ISSUE THREAD

**Issue by deddc23efb** [home-assistant/frontend#7095]
Running homeassisatant 115.2 
Terminal and SSH is supposed to enable SSH. Shockingly the default configuration doesn't do that. It's impossible to ssh to homeassistant when configuring Terminal and SSH.  A WEB UI is not ANY good when the WEB UI Is broken - that's why people install ssh.

Second: The Network Configuration for Terminal and SSH is incorrectly labelled so that SSH stays broken because it will only forward port 22 if the HOST field is configured with a PORT number. This is ridiculously broken UI and should never have been released like this let alone be the Official SSH tool.

The expected behaviour is that enabling the Terminal and SSH Add-on would by default enable SSH.

To reproduce - install the Terminal and SSH add-on and try to ssh. Next , hunt for the PORT field and find it not present to reproduce the no network access for real SSH problem.

**Comment by zsarnett** [comment]
Please fil out the issue template

**Comment by bramkragten** [comment]
This also not a frontend issue but an issue with addons of the supervisor.

**Comment by deddc23efb** [comment]
It's next to impossible to raise a bug against this project.  The instructions for doing so are incomplete and the number of unhelpful gate keepers is large. If the dev team truly wants regular folks to be able to raise bugs that don't get closed for process reasons, the documentation must be in place.

**Comment by bramkragten** [comment]
Well, you could start with changing the tone of your issues, as it is not inviting for a volunteer to put effort into it and help you if you bash their work: 

> This is ridiculously broken UI and should never have been released like this

**Comment by deddc23efb** [comment]
I'm not asking for help.  I figured out how to use the feature and was frankly shocked that it was released that way. Others have struggled with that process and I would think the author or maintainer of the feature would be motivated to fix the problems.  

Should i just be pushing changes into the code base. I can do that if that's a better approach for this project.

**Comment by bramkragten** [comment]
You are always welcome to create a PR, but it might be wise to check in advance if we would accept the change, as things might be done for a reason.
