### ISSUE TITLE
Crashing new lines with custom font sizes in Markdown Card

### ISSUE THREAD

**Issue by mutlucan96** [home-assistant/frontend#7102]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

![Screenshot 2020-09-22 at 12 00 32](https://user-images.githubusercontent.com/42113538/93865058-71be9780-fcce-11ea-81f5-c2f62984e359.png)
See what happens when I change font size.
## Environment

- Home Assistant release with the issue: 0.115.2
- Last working Home Assistant release (if known): 0.114.4
- Browser and browser version: Chrome 86 / Firefox 68
- Operating system: Chrome OS 86 / Debian Buster

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ludeeus** [comment]
That's how markdown works.
You can not use markdown syntax inside HTML tags, if you use HTML it needs to be pure HTML inside the tags.

example
```
<font size="12px">
The <b>markdown</b> card
</font>
```

**Comment by mutlucan96** [comment]
It was working fine before. I won't work if I use pure HTML
![Screenshot 2020-09-22 at 12 53 58](https://user-images.githubusercontent.com/42113538/93868212-cfed7980-fcd2-11ea-9041-e552944b6b4f.png)

**Comment by ludeeus** [comment]
You need to adjust the line-height as well.

**Comment by mutlucan96** [comment]
How? "style" attributes don't work. "font" doesn't have such attribute.
Is it really normal behaviour? Because it wasn't like that in previous versions. I was using font size without this artifact until 0.115.

**Comment by bramkragten** [comment]
The `font` tag is not supported in HTML5. To make this work we would have to set `line-height: normal` on the markdown element.
