### ISSUE TITLE
Integrations - Long Device Name breaks UI

### ISSUE THREAD

**Issue by almostserious** [home-assistant/frontend#7103]
## Checklist

- [X ] I have updated to the latest available Home Assistant version.
- [X ] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

The long name of 1 yeelight breaks the UI in the Integrations page. 
![image](https://user-images.githubusercontent.com/14896478/93882784-fadeca00-fce0-11ea-9caf-ae9823790a7d.png)

## Expected behavior

The name should be capped automatically to not overflow out of the box

## Environment

- Home Assistant release with the issue: 115.2
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome / IE
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/issues/5806
