### ISSUE TITLE
Wrong label in MQTT configuration wizard

### ISSUE THREAD

**Issue by fredericks1982** [home-assistant/frontend#7108]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

In the configuration wizard, both the checkboxes to enable birth and will messages have the label "Enable birth message" (one cut&paste too many? :sweat_smile:). See the screenshot below:

![image](https://user-images.githubusercontent.com/32093333/93910117-f0342d00-fd00-11ea-9aad-2e13d51733f7.png)

## Expected behavior

Correct the second label to "Enable **will** message".

## Steps to reproduce

Re-configure an existing MQTT integration.

## Environment

- Home Assistant release with the issue: 0.115.2
- Last working Home Assistant release (if known):
- Browser and browser version: MS Edge 85.0.564.51
- Operating system: Windows 10 Enterprise

## State of relevant entities

N/A

## Problem-relevant configuration

N/A

## Javascript errors shown in your browser console/inspector

None.

## Additional information
None.

**Comment by zsarnett** [comment]
This is based on the backend. I believe this will need to be changed there

**Comment by fredericks1982** [comment]
Ok thanks, I posted a [new issue](https://github.com/home-assistant/core/issues/40463) in the other repository.
