### ISSUE TITLE
Unnecessary cache reloads from service worker

### ISSUE THREAD

**Issue by m2hofi94** [home-assistant/frontend#7120]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
When reloading the page / opening the page, pretty much all requests are served by the service worker, and the page builds quickly. However, after the initial load, the service worker starts reloading/refreshing all custom resource .js files. Here is an example screenshot from the network view:

![image](https://user-images.githubusercontent.com/7964547/94118598-0f8ca080-fe4e-11ea-9efa-e819dcfeea45.png)
To me this seems unnecessary and causes extra data usage. But I'm not sure if this is simply a limitation of the resources/plugins system for lovelace.

## Expected behavior
I would have expected theses files to also be refreshed only when lovelace prompts me to clear the cache, like after changes to the UI.

## Steps to reproduce
1. Include custom resources (js) in your lovelace configuration via the UI
2. Navigate to any Lovelace View
3. Reload the page, watching the network resources

## Environment

- Home Assistant release with the issue: 0.115.2
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome 85.0.4183.121
- Operating system: Windows 10 20H2

## State of relevant entities

```yaml
n/a
```

## Problem-relevant configuration

![image](https://user-images.githubusercontent.com/7964547/94119078-aeb19800-fe4e-11ea-8334-221fc93553f6.png)

```yaml
n/a
```

## Javascript errors shown in your browser console/inspector

```txt
n/a
```

**Comment by ludeeus** [comment]
This is not a bug in the frontend, this is a feature of HACS <https://hacs.xyz/docs/categories/plugins#custom-view-hacsfiles>
