### ISSUE TITLE
Potential Bug: Color-wheel (color picker) missing on "MQTT Light" entity popup (details tab)

### ISSUE THREAD

**Issue by sstefanowski** [home-assistant/frontend#7121]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I've upgraded to HA 0.115.2 and it looks like.... the Color-wheel (color picker) missing on "MQTT Light" entity popup (details tab).

I have several MQTT Lights with RGB support and until now when I opened "entity details popup" and Light was "on" then the Color-wheel (color picker) was rendered allowing to change the color of the light. In version 0.115.2 this is not appearing and as consequence not allowing to change the color of the light
 
I haven't changed anything in a light. 
It looks like MQTT Light(using JSON schema) are able to absorb the RGB parameters as color of the icon is changing on UI when color is changed with the physical remote.

I can't see any unusual in config. The supported features of the light is 57 indicating RGB support. So, I suppose this is entity popup bug.

Please see all my screens attached.

- Bedroom light accepts the color set on physical remote (icon changed to green when light color was changed to green)
![Bedroom_light_accepts the color](https://user-images.githubusercontent.com/36473471/94119042-9e99b880-fe4e-11ea-8393-6cc04ff29c38.jpg)

- Missing Colorwheel on Light entity details popup (when light is still on)
![Bedroom_missing_colorwheel_and_brightness_slider_on_rgb_ligth_entity_details_page](https://user-images.githubusercontent.com/36473471/94119140-c4bf5880-fe4e-11ea-89d3-c7ff0d8bcac5.jpg)

- Light config and States below (for review)
![Lights_yaml](https://user-images.githubusercontent.com/36473471/94119208-def93680-fe4e-11ea-958b-78e90cca9b8a.jpg)
![Bedroom_light_color_states](https://user-images.githubusercontent.com/36473471/94119213-e02a6380-fe4e-11ea-8421-ca97510a5f76.jpg)

 ## Expected behavior

When I click any Light entity with RGB support (feature turned on) I'm expecting to see related controls on Entity Popup and Details Tab. I expect to see color picker (color wheel) and brightness slider.

## Steps to reproduce
1. Configure MQTT Light with `schema: json `and `rgb: true` and `brightness:true` (see the screenshot above)
2. On Lovelace configure entity Card and insert pre-configured Light as an entity
3. Turn on the light
4. Click the light icon on card to see a popup with entity details - no RGB color picker or brightness slider is shown on popup.

## Environment

- Home Assistant release with the issue: 0.115.2
- Last working Home Assistant release (if known): 0.113
- Browser and browser version: Chrome, HomeAssistent Android App
- Operating system: Raspbian installation (ex hassbian)

## State of relevant entities

```yaml

**Comment by bramkragten** [comment]
Tested here and it works, you also don't get the brightness slider? Looks like the element is not loaded for you, can you check your browser console for errors?

![image](https://user-images.githubusercontent.com/5662298/94138786-eaf1f200-fe68-11ea-9b3a-37ecc6537202.png)

**Comment by sstefanowski** [comment]
Aha.... There you are.... There is an error in th console, but I dont know what's caused it...
any hint?

```
slider-entity-row.js:68 SLIDER-ENTITY-ROW 1.0.0 IS INSTALLED 
banner-card.js:162 banner-card: 0.11.0
fold-entity-row.js:46 FOLD-ENTITY-ROW 19.0.0 IS INSTALLED 
hui-element.js:1 HUI-ELEMENT 1.0.1 IS INSTALLED 
card-mod.js:5 CARD-MOD 2.0.0 IS INSTALLED 
vertical-stack-in-card.js:2 vertical-stack-in-cardVersion: 0.3.3
harmony-card.js:439   HARMONY-CARD   Version 0.11.0    
simple-thermostat.js:1 simple-thermostat: 0.35.0
card-tools.js:90 CARD-TOOLS 2.1.2 IS INSTALLED  DeviceID: 9111da38-d08b5138
custom-header.js:146 ☰  CUSTOM HEADER 1.7.9                 ⋮ User's Name: Sebastian                   User ID: bf6ec94ddd0e47b0b651c66bbf417ec1Device ID: 9111da38-d08b5138             
mini-graph-card-bundle.js:1  MINI-GRAPH-CARD  0.9.4 
lovelace-card-templater.js:8   CARD-TEMPLATER   Version 0.0.9  
chunk.15bafadba8414bba4a3b.js:129 Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "ha-paper-slider" has already been used with this registry
    at Object.185 (https://*********.duckdns.org:8123/frontend_latest/chunk.15bafadba8414bba4a3b.js:19:2214)
    at i (https://*********.duckdns.org:8123/frontend_latest/app.75ee90d1.js:2:362)
    at Object.527 (https://*********.duckdns.org:8123/frontend_latest/chunk.15bafadba8414bba4a3b.js:53:961)
    at i (https://*********.duckdns.org:8123/frontend_latest/app.75ee90d1.js:2:362)
    at Module.939 (https://*********.duckdns.org:8123/frontend_latest/chunk.15bafadba8414bba4a3b.js:183:6227)
    at i (https://*********.duckdns.org:8123/frontend_latest/app.75ee90d1.js:2:362)
```

**Comment by bramkragten** [comment]
That is one of your custom cards that breaks things. It is defining `ha-paper-slider` and then we can't anymore. Please raise an issue there.
