### ISSUE TITLE
Add ability to always hide Lovelace top title

### ISSUE THREAD

**Issue by cadavre** [home-assistant/frontend#7122]
## The request

For lots of devices where Lovelace is running – screen space is worth millions. I.e. tablet hanging on the wall, most likely 1024x768px or similar.

It would be great if we could hide top title like auto-hiding on scroll is doing:

<img width="735" alt="Zrzut ekranu 2020-09-24 o 15 33 49" src="https://user-images.githubusercontent.com/461796/94152026-66f53580-fe7b-11ea-9196-0a95ccaa3416.png">

## The alternatives

Currently there's a plugin called `custom-header` (https://github.com/maykar/custom-header) but it looks like using it is a little bit overwhelming. Also on some devices it's not working correctly.

## Additional information

None.

**Comment by maykar** [comment]
While I agree that this is a much needed core feature, if you're having issues with Custom Header feel free to head over to the forums for assistance. While there are quite a few features (too many in my opinion) the UI editor should make simple things like compacting the header fairly easy. Also, if you're having issues with some devices would you mind making an issue on the [repo](https://github.com/maykar/custom-header)?
