### ISSUE TITLE
Map Day and Night Option

### ISSUE THREAD

**Issue by vMeph** [home-assistant/frontend#7125]
## The request

Would be nice to have a like a switch option in porfile to enable the map theme to act like day and night depending on the time, when is day the map theme is white and when is night it will be dark
like the GPS does

Day
![2](https://user-images.githubusercontent.com/12812111/94179005-cd864d80-fe93-11ea-9c9d-404406bcf270.png)
Night
![1](https://user-images.githubusercontent.com/12812111/94179097-f0b0fd00-fe93-11ea-9928-90edabcc581d.png)

## The alternatives
Not sure id this is possible to do with a automation already

**Comment by bramkragten** [comment]
This is part of the dark theme.
