### ISSUE TITLE
Calendar panel is unstable

### ISSUE THREAD

**Issue by wolverinevn** [home-assistant/frontend#7130]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

 Calendar Panel shows a few events. When move mouse pointer around or select/deselect calendar, events keeps being showed and hidden randomly.
It's useless at all.

## Steps to reproduce

 1. Add Google Calendar with some calendars
 2. Open Calendar panel
 3. Play with it

## Environment

arch | aarch64
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.13
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v8
python_version | 3.8.5
supervisor | 245
timezone | Asia/Ho_Chi_Minh
version | 0.115.2
virtualenv | false

- Home Assistant release with the issue: 0.115
- Last working Home Assistant release (if known): 0.114
- Browser and browser version: Safari 14 & Chrome 85.0.4183.121 on Mac OS 10.15.6; Native app & Safari on iOS 14.
- Operating system: Mac OS & iOS 14

## State of relevant entities

 Calendar entities look fine.

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

No error.

```txt

```

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/issues/7075
