### ISSUE TITLE
The Automations panel layout doesn't render well in High-Res screens

### ISSUE THREAD

**Issue by sdrapha** [home-assistant/frontend#7136]
## The request

The Automations Panel layout is 'almost' unusable with high-res monitors.
The name of the Automations get so far left from the buttons on the other side, that you can't tell they are related to each other, it really is a trial and error situation when I want to pick the right one to edit.

![image](https://user-images.githubusercontent.com/25059996/94318178-e9eabe80-ff55-11ea-8e96-eb3385754cbe.png)

I think that also happens in some other configuration panels too, but the Automations panel is the worse scenario.

## The alternatives

The layout could have some proportional limit to the size of the columns, so they don't get too far apart, also maybe some subtle line guide between values from each side so you could at least visually follow it with the mouse pointer or your finger.

**Comment by SeanPM5** [comment]
When you hover over a table cell with your mouse, it should change colors. 

It's kind of subtle, but you can just follow the one different colored table cell to the other side.

**Comment by sdrapha** [comment]
hmmm... Since you said that, and I don't have that hover effect on my end, I changed my theme back to default white and now I can see what you are talking about.
I don't have that effect on my dark theme ('blue_night') that I like to use. 😭

**Comment by Misiu** [comment]
@sdrapha then ask theme author to add that effect. Of if you know how add it and create a PR to there theme repo.

**Comment by sdrapha** [comment]
I found how to fix the hover effect in the theme and did a pull request to the theme repo. That hover effect is enough to solve this issue for me. I'm closing it. Thanks for all the input.
