### ISSUE TITLE
Media Controls Skip buttons do not work on Google Cast for Youtube Music 

### ISSUE THREAD

**Issue by Nimzr** [home-assistant/frontend#7138]
## Checklist

- [ X] I have updated to the latest available Home Assistant version.
- [X ] I have cleared the cache of my browser.
- [ X] I have tried a different browser to see if it is related to my browser.

## The problem

When casting from youtube music the media control card buttons (other than play/pause) do not work. Skip to next song or back do not do anything. Tried different music services such as spotify and those buttons work just fine. 
![image](https://user-images.githubusercontent.com/50554236/94344699-f878ba80-ffd5-11ea-8a18-03026f926aac.png)

## Expected behavior

When you begin a cast from youtube music you should be able to carry the controls over to the Home Assistant media controller card. At the moment the only function that is available is play / pause and seeking within the same track. I should be able to skip to the next song or go back to previous song. Same as you can with spotify for example using the same card. 

## Steps to reproduce

1. Begin casting from youtube music to a cast device/group
2. go to home assistant frontend card for that device or group. press the skip to the next song button. 
3. Nothing happens. 

## Environment

- Home Assistant release with the issue: Home Assistant 0.115.3
- Last working Home Assistant release (if known):
- Browser and browser version: ChromeVersion 85.0.4183.121 (Official Build) (64-bit)
- Operating system: Windows 10 and Android App

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
This is an integration issue. The integration is not accepting the next service call correctly.

**Comment by Nimzr** [comment]
@zsarnett Should I open up another issue on the integration side? let me know what you prefer, thanks!

**Comment by zsarnett** [comment]
yes
