### ISSUE TITLE
Calendar card layout option

### ISSUE THREAD

**Issue by skank01** [home-assistant/frontend#7143]
## The request

Hi, is it possible to add some kind of visual color seperator between the days filled in , in list view.. Now all text is black/the same and its hard to differntiate the days

## The alternatives

 I used ijmerza calendar card but that one is archived now.. poiting to the lovelace built in card

## Additional information

Screenshots will make this clear

old view
![image](https://user-images.githubusercontent.com/53368406/94364925-2d1b6d80-00cd-11eb-91d9-54de9aa9046f.png)

now with build-in card, its harder to differentiate

![image](https://user-images.githubusercontent.com/53368406/94364946-4f14f000-00cd-11eb-9719-272cf4b1a302.png)

**Comment by davidmonro** [comment]
There is actually a separator there but it is _very_ low contrast. I agree it needs to be a lot more obvious!

**Comment by davidmonro** [comment]
In the old ijmerza card the separator is a 1px border and uses --accent-color 
I'm not sure what the new one is doing, it seems to be a 0-width border?

**Comment by zsarnett** [comment]
0px width would make no sense?

its 1px using the divider color. I am guessing your theme has a color very close to the background color for your divider variable

**Comment by davidmonro** [comment]
I agree 0-width doesn't make sense, but if I inspect it with the firefox built-in web developer tool it shows up and if I modify it to be width 10, it goes white (I'm on a dark theme).

In the screenshot above you can see that it is showing up for @skank01 but it is _very_ faint - 0xf8f8f8 which is very close to 0xffffff

**Comment by zsarnett** [comment]
The divider color on the default theme is correct. Its a grey on white. I would suggest that you edit your theme to use a divider color that makes sense. Meaning able to be seen on the card background

**Comment by davidmonro** [comment]
Ahh. I've noticed something - with my dark theme, the background of the calendar list is darker than a normal card, so the contrast with the darker divider is lost.

I'm using the 'midnight' theme - the card to the left is the ijmerza card (although that isn't really relevant, it is just a normal card). On the right is the new calendar card - note the 'normal' colour on the card border, and then the darker color for the list body.

With the 'default' theme the calendar list area happens to be the same as the normal card background, so the contrast is a little more obvious.

![calendar-contrast](https://user-images.githubusercontent.com/1043726/94631269-4ad61600-030b-11eb-8b2a-4b15b3c16061.png)

**Comment by zsarnett** [comment]
What do you mean by darker than a normal card?

The Core Calendar Card background for all view should be using `--card-background-color` the divider between each day is using `--divider-color`

**Comment by iantrich** [comment]
@davidmonro you're comparing to a custom card, that's not something to base against.

**Comment by davidmonro** [comment]
OK here's it next to a standard "entities" card. The scrollable area is clearly darker.
![calendar-difference](https://user-images.githubusercontent.com/1043726/94633406-7f000580-0310-11eb-91ed-b8b63dfde8b6.png)

**Comment by zsarnett** [comment]
Well that is interesting for sure. I will look into a bug fix for that.

**Comment by davidmonro** [comment]
There's definitely some odd interactions with community themes. Here's what it looks like with the 'synthwave' theme (available through HACS, along with the midnight one I'm using above)

Note the controls for which view to use have almost vanished, although the TODAY box hasn't, as well as the backgrounds for the day names. 

![calendar-synthwave](https://user-images.githubusercontent.com/1043726/94634569-c340d500-0313-11eb-94dc-ae3836a27210.png)

**Comment by skank01** [comment]
If it's any help... i'm using the google dark and google light theme

**Comment by skank01** [comment]
Can i ask one more thing regarding this calendar card?
In list view... it doesnt drop off agenda items..
For ex i have on monday task A and on wednesday task B and thursday tsk C etc etc
Say we are wednesday... and i look into listview.. i still see task A from monday although we are past that date..
It doesnt make sense...

It should drop off items ..
And only show upcoming 3/5 agenda items like with  ijmerza calendar 

Waiting for the divider fix too :p
Thanks guys

**Comment by skank01** [comment]
Any update on this?
