### ISSUE TITLE
Media Browser doesn't list media for the Sonos integration

### ISSUE THREAD

**Issue by RomRider** [home-assistant/frontend#7144]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

The media browser fired up from a sonos media player doesn't list the media available in sonos (note: I don't have local medias, I just want to display the ones available through the Sonos integration)
It just spins forever:
![image](https://user-images.githubusercontent.com/21064206/94369904-be4e0c80-00ec-11eb-9857-3917fb4a4037.png)

## Expected behavior

Displays the media available through the Sonos Integration

## Steps to reproduce
Configure the sonos integration and fire up the media browser from a sonos media_player entity.

## Environment

- Home Assistant release with the issue: 0.115.3
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Chrome (latest)
- Operating system: MacOS

## State of relevant entities

N/A

## Problem-relevant configuration

N/A

## Javascript errors shown in your browser console/inspector
No error.

**Comment by Zeunas** [comment]
I am surprised no one picked up on this yet. Is no one else experiencing this too? @RomRider have you managed to fix it?

**Comment by RomRider** [comment]
Nope, couldn't fix it and no errors in the log, still spinning forever :)

**Comment by dennisoderwald** [comment]
I have the same problem, exactly the same.

**Comment by zsarnett** [comment]
Any errors in the logs of HA?

**Comment by dennisoderwald** [comment]
No errors in the system log and the console. Tested with 0.115.6.

Websocket Response:
```json
{"id": 28, "type": "result", "success": false, "error": {"code": "unknown_error", "message": "Local library not found"}}
```

**Comment by zsarnett** [comment]
@cgtobi Any idea on this? If the Media Directory doesn't exist we need the backend to see the correct error message to the frontend

**Comment by zsarnett** [comment]
@dennisoderwald Do you have a local library? I don't think sonos is set up to browse anything other than the media directory

**Comment by zsarnett** [comment]
(Also, this is technically not a frontend issue)

**Comment by RomRider** [comment]
It is said in the release notes of 0.115 that Sonos would also display stuff from the sonos library (like Spotify, plex, etc...).
Also yeah, maybe not a frontend issue, but without error it could be a frontend or backend issue :)

**Comment by zsarnett** [comment]
> @zsarnett No, I did not. It would make sense to hide the icon if no media library is available.
> 
> A Sonos Library in HA would be awesome but is currently not part of it.

No we should not hide it. If the backend tells us we don't have a media folder then we show a specific message about how to set it up

**Comment by dennisoderwald** [comment]
@RomRider You probably mean:

> Any media player can enable this new feature. This release adds media browser support to Arcam FMJ, Kodi, Philips JS, Plex, Roku, Sonos and Spotify!
https://www.home-assistant.io/blog/2020/09/17/release-115/

I think it means you can play your local media on Sonos with HA Media Library.

**Comment by zsarnett** [comment]
I will wait for @cgtobi to respond as I believe he did the integration so he will have more insight here

**Comment by dennisoderwald** [comment]
> No we should not hide it. If the backend tells us we don't have a media folder then we show a specific message about how to set it up

@zsarnett That makes sense, of course.So the core (backend) returns the wrong error as it seems.

**Comment by zsarnett** [comment]
Yea I believe that is the case here

**Comment by Zeunas** [comment]
> It is said in the release notes of 0.115 that Sonos would also display stuff from the sonos library (like Spotify, plex, etc...).
> Also yeah, maybe not a frontend issue, but without error it could be a frontend or backend issue :)

Yes, this is my understanding too from the release notes. Also agree that can be both frontend or backend after all you should be able to open Sonos library (cloud based?) from fronted...

Just crossed my mind as well, if the release notes actually ment media that is stored in Sonos speaker as opposed sourced from Sonos cloud?

**Comment by bramkragten** [comment]
I think this error is about the local library of Sonos, not that of Home Assistant.

Still the frontend should handle errors from the backend (show the error and stop spinning)

**Comment by zsarnett** [comment]
Oh that makes sense. And also we have error handling so I am not sure why this is spinning... I can look into this later today/weekend

**Comment by RomRider** [comment]
So to be consistent with the other integrations, I think the media browser should show the Sonos cloud library as the Sonos library already allows to play any sort of media (NAS included).
Plex and Spotify both displays the library of each provider, not the local /media content which is what I'd expect from the Sonos media browser too.

**Comment by zsarnett** [comment]
Yes. I'll see a PR for this later right? 😉 Of course that is probably the goal. It just hasn't been developed yet.

**Comment by RomRider** [comment]
I could have a look, didn't yet check how it has been implemented for the other integrations for now.

It would be a good idea to clarify the features to avoid setting false expectations (avoid thinking that it would display the cloud library for Sonos when it doesn't but it does for Spotify or plex format eg.)

**Comment by schultza** [comment]
Any updates on this Issue?

**Comment by robertfgoodworth** [comment]
This might be closed but the issue remains, does for me anyway.

**Comment by zsarnett** [comment]
I dont think this made it to the 0.117.1 release
