### ISSUE TITLE
History's "Last week" option goes one month ahead.

### ISSUE THREAD

**Issue by ChrisMD123** [home-assistant/frontend#7147]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Selecting "last week" under History made the selected dates jump to the next month. 
![image](https://user-images.githubusercontent.com/4922831/94379357-9064ca00-00e4-11eb-85b3-a7e1197abbb4.png)

## Expected behavior

"Last week" should have selected 20-26 September, not 20-26 October.

## Steps to reproduce

    1. Navigate to History
    2. Left-click "Start Date"
    3. Left-click "Last week"

## Environment

Version: 0.115.3, installed in a VM on a Windows Server
Experienced in Chrome and Edge

- Home Assistant release with the issue: 0.115.3
- Last working Home Assistant release (if known): Unknown
- Browser and browser version: Chrome  85.0.4183.121; Edge 85.0.564.63
- Operating system: Client: Windows 10. HA: VM on a Windows Server 

## State of relevant entities

N/A

```yaml

```

## Problem-relevant configuration

N/A

```yaml

```

## Javascript errors shown in your browser console/inspector

None

```txt

```

## Additional information

None

**Comment by spacegaier** [comment]
Works fine for me with HA 0.117.0 (latest dev version) and latest frontend version when tested just now. However, there is a chance that it might only occur during certain days/weeks of a month (somehow overflowing then).

**Comment by BoneheadFraggle** [comment]
In 0.117.b3, the problem remains (today). 
when selecting "last week" today, it selects november 18 - 25.

**Comment by ChrisMD123** [comment]
![Screenshot_20201025-152838](https://user-images.githubusercontent.com/4922831/97120780-d8244480-16d6-11eb-9e90-ced4b0a3066d.png)
Confirmed.

**Comment by e28eta** [comment]
I’m seeing this too.

https://user-images.githubusercontent.com/483223/103180633-5c688480-484c-11eb-8a0f-efdb9a154e9e.MP4

**Comment by spacegaier** [comment]
I was now able to reproduce it and it indeed depends on where in the month we are for this issue to appear. PR is on its way.
