### ISSUE TITLE
Add back vol up and down buttons in media-player more-info dialog

### ISSUE THREAD

**Issue by pszafer** [home-assistant/frontend#7148]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I can't find PR which done that, but since 0.115 vol up/down buttons are gone.
There are media players which doesn't report volume level (epson projector). 
Without those buttons user can't control volume level anymore with buttons and slider doesn't exist.

## Expected behavior

Revert back vol up/down buttons.

## Steps to reproduce

1. Add a epson integration
2. Navigate to Lovelace
3. Click more info of the media player
4. Try to control volume.

## Environment

- Home Assistant release with the issue: 0.115.3
- Last working Home Assistant release (if known): ~0.114
- Browser and browser version: Chromium 85
- Operating system: Alpine Linux 3.11

## State of relevant entities

I don't think it is necessary. Currently my projector is turned off so can't send you state.
Let me know if you need this.

```yaml

```

## Problem-relevant configuration

```yaml
- platform: epson
  host: host
  name: epson
```

## Javascript errors shown in your browser console/inspector
No errors

**Comment by spacegaier** [comment]
Solved via https://github.com/home-assistant/frontend/pull/7376 I guess.
