### ISSUE TITLE
Duplicate automations

### ISSUE THREAD

**Issue by jannecklarsson** [home-assistant/frontend#7158]
You cant duplicate a duplicated automation without Action service-enteties-list dissapears. 
This happens if you dont exit setup of duplicated automation before duplicating again. 

And if you manage to create an automation this way. Ill get the error: 
"Platform automation does not generate unique IDs. ID xxxxxxxx already exists - ignoring automation.xxxxxx"

**Comment by zsarnett** [comment]
Please fill out the issue template
