### ISSUE TITLE
Show brightness value of dimmable lamp in info dialog

### ISSUE THREAD

**Issue by pascalwinters** [home-assistant/frontend#7161]
## The request
In the info dialog you can configure the  brightness of a lamp for example for an scene, but the brightness level is not exactly configurable because you don't have a readiable feedback.

**Comment by atomdaf** [comment]
https://github.com/home-assistant/frontend/labels/hacktoberfest

**Comment by atomdaf** [comment]
https://github.com/home-assistant/frontend/labels/hacktoberfest

**Comment by nahos** [comment]
Hey, I would like to work on this feature.

**Comment by zsarnett** [comment]
Go for it :)

**Comment by nahos** [comment]
Could someone help me setup the environment for windows? I am having a hard time trying to set it up

**Comment by pascalwinters** [comment]
> Could someone help me setup the environment for windows? I am having a hard time trying to set it up

Hi Nahos,
I have the same issues. When you have any tips, you're welcome ;-)

**Comment by nahos** [comment]
> 
> 
> > Could someone help me setup the environment for windows? I am having a hard time trying to set it up
> 
> Hi Nahos,
> I have the same issues. When you have any tips, you're welcome ;-)

Where are you stuck at? I was able to get the home-assistant core working but I am not able to point it to the local frontend. Also in the front end, I am not able to run any of the scripts like bootstarp or develop, it just keeps throwing error.

**Comment by Djowie** [comment]
If still possible I would like to try work on this feature.

**Comment by pascalwinters** [comment]
> If still possible I would like to try work on this feature.

For me it's ok. But I don't know how far nahos is.

**Comment by nahos** [comment]
> 
> 
> If still possible I would like to try work on this feature.

You can take it

**Comment by pascalwinters** [comment]
> If still possible I would like to try work on this feature.

Any progress?

**Comment by Djowie** [comment]
@pascalwinters I'm trying to get the dockers running, but my frontend isn't running. So currently, I'm unable to work on it unfortunately.

**Comment by nahos** [comment]
I had the same issues, could not get the app running on a windows

**Comment by pascalwinters** [comment]
Has already been implemented.
