### ISSUE TITLE
UI editor for time condition

### ISSUE THREAD

**Issue by KTibow** [home-assistant/frontend#7164]
## The request

For the [time condition](https://www.home-assistant.io/docs/scripts/conditions/#time-condition), you can configure weekdays. It'd be nice if you could set up that with the UI editor

## The alternatives

Use YAML.

**Comment by Misiu** [comment]
@KTibow it will be possible in 0.106. Py PR got merged recently.
Take a look: https://github.com/home-assistant/frontend/pull/6848
