### ISSUE TITLE
Panel mode not working

### ISSUE THREAD

**Issue by matt8707** [home-assistant/frontend#7178]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When using `panel: true` in 0.116.0b0 I just get a red card with "r.setConfig is not a function". Removing panel mode works. I've made sure to spin up a new container with an empty config too.

## Expected behavior
...

## Steps to reproduce

  1. Paste in "Problem-relevant configuration"
  2. Add an entity
  3. Save
  4. r.setConfig is not a function

## Environment

- Home Assistant release with the issue: 0.116.0b0
- Last working Home Assistant release (if known): 0.115.6
- Browser and browser version: Chrome 85.0.4183.121
- Operating system: macOS 10.13.6

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
views:
  - title: test
    path: test
    panel: true
    cards:
      - type: entities
        entities: 
          - light.test
```

## Javascript errors shown in your browser console/inspector

```txt
r.setConfig is not a function
ERROR (MainThread) [frontend.js.latest.202009300] /frontend_latest/chunk.1a2a772835e9f63eba8a.js:2270:759 Uncaught

r.setConfig is not a function. (In 'r.setConfig(t)', 'r.setConfig' is undefined)
ERROR (MainThread) [frontend.js.latest.202009300] /frontend_latest/chunk.1a2a772835e9f63eba8a.js:2270:369341 NotSupportedError: A newly constructed custom element must not have attributes
```

**Comment by Spirituss** [comment]
The same result.

<img width="267" alt="Снимок экрана 2020-10-01 в 13 04 07" src="https://user-images.githubusercontent.com/47206760/94795967-cb1d7980-03e6-11eb-9217-48fc06f89155.png">
