### ISSUE TITLE
Cover card open_cover_tilt and close_cover_tilt not available

### ISSUE THREAD

**Issue by ouranos6** [home-assistant/frontend#7186]
##  The problem
Hi everyone, first of all I would like to thank you for this amazing piece of software!!

Where I live we use a lot shutters with slats.

In KNX we use the :
- move_long_address "0" to move UP and "1" to move DOWN
- move_short_address "0" to tilt 1x UP the slats and "1" to tilt 1x to tilt DOWN the slats 

I'am facing an issue with the cover card to make the long move (full UP/DOWN) it's ok it work BUT i'am unable to make it working with the short move because the card doesn't have the functionnalites for

`cover.open_cover_tilt`
and
`cover.close_cover_tilt
`
## Environment
- Home Assistant 0.115.4
- Weinzierl 751 KNX IP router
- Home Assistant Core release with the issue: HassOS 4.13
- Last working Home Assistant Core release (if known): -
- Operating environment (Home Assistant/Supervised/Docker/venv): VM (VirtualBox)
- Integration causing this issue: Cover
- Link to integration documentation on our website: [https://www.home-assistant.io/integrations/cover.knx/](url)

## Problem-relevant `configuration.yaml`

```cover:
  - name: "Store_Terrasse"
    move_long_address: '1/3/1'
    move_short_address: '1/3/2'

```

## Traceback/Error logs

``Nothing

```

## Additional information


Many thanks in advance

**Comment by iantrich** [comment]
Are your referring to the more info dialog?

**Comment by ouranos6** [comment]
Hi,

Not exactly because on the more info dialog we can adjuste the height but not the slats.

I want to move up or down with let say 'impulses' 

The blinds are like that
![image](https://user-images.githubusercontent.com/20718760/96257579-e679ae80-0fba-11eb-964c-a7d9db554c91.png)

**Comment by iantrich** [comment]
Looks like tilt controls are only displayed if the cover ONLY for tilt. @bramkragten or @balloob any insight into why that might be?
https://github.com/home-assistant/frontend/blob/dev/src/dialogs/more-info/controls/more-info-cover.js#L60
https://github.com/home-assistant/frontend/blob/dev/src/util/cover-model.js#L74

**Comment by balloob** [comment]
The entity row card is limited to a single control, so that check was meant to make sure we only show 1 type of control. Not sure how that made it to more info.
