### ISSUE TITLE
Header toggle for lovelace cards not working

### ISSUE THREAD

**Issue by cogneato** [home-assistant/frontend#7189]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Clicking on a header toggle for a lovelace card does nothing.

![Peek 2020-10-01 12-12](https://user-images.githubusercontent.com/2456810/94847540-f2bd1380-03df-11eb-999a-46038b4d6a86.gif)

## Expected behavior
Toggle should manipulate entities within the card

## Steps to reproduce
Checked with Firefox and Chrome:
1. Navigate to existing card.
1. Click header toggle.

## Environment

arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.13
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.63
python_version | 3.8.5
supervisor | 246
timezone | America/Denver
version | 0.116.0b0
virtualenv | false

- Home Assistant release with the issue: 116.0b0
- Last working Home Assistant release (if known): 115.6
- Browser and browser version: Chrome Version 85.0.4183.121
- Operating system: Linux 

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by tigattack** [comment]
Can confirm.
