### ISSUE TITLE
Logbook fails to load when encountering a deleted binary sensor on 0.116b1

### ISSUE THREAD

**Issue by bdraco** [home-assistant/frontend#7190]
```
    case "binary_sensor": {
      const isOn = state === BINARY_STATE_ON;
      const isOff = state === BINARY_STATE_OFF;
===>      const device_class = stateObj.attributes.device_class; <===

```

## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt
Uncaught (in promise) TypeError: Cannot read property 'attributes' of undefined
    at getLogbookMessage (logbook.ts?40d3:141)
    at getLogbookData (logbook.ts?40d3:48)
    at async Promise.all (:8123/index 0)
    at async HTMLElement._getData (ha-panel-logbook.ts?d8ef:266)
```

**Comment by bdraco** [comment]
`stateObj` is undefined

**Comment by zsarnett** [comment]
You have an entity that doesn't exist in the Hass states?

**Comment by bdraco** [comment]
Yes, I disabled the entity when I had to re-auth the integration that provided it and I got back ones I usually don't track.

```
{when: "2020-10-01T20:09:54.786653+00:00", name: "XIZZY online sensor", state: "on", entity_id: "binary_sensor.xizzy_online_sensor"}entity_id: "binary_sensor.xizzy_online_sensor"name: "XIZZY online sensor"state: "on"when: "2020-10-01T20:09:54.786653+00:00"__proto__: Object
logbook.ts?40d3:123 on undefined binary_sensor
```

**Comment by bdraco** [comment]
Its the deleted entity case

**Comment by zsarnett** [comment]
I believe this should fix
