### ISSUE TITLE
Refresh button in developers tools to refresh state of the selected entity

### ISSUE THREAD

**Issue by kukulich** [home-assistant/frontend#7201]
## The request

It would be nice to have refresh button in developers tools to refresh state of the selected entity.

**UPDATED**
The table with entities is updated automatically but the form on the top of the "States" page is not - state update input is not updated and the textarea with state attributes YAML are not updated too.

**Comment by bramkragten** [comment]
In the states dev tools? Our frontend updates automatically, there is no need to do this manually.

**Comment by kukulich** [comment]
Strange it does not work for me sometimes. I'll try to explore it.

**Comment by kukulich** [comment]
@bramkragten The table is updated but the form on the top of the "States" page is not - state update input is not updated and the textarea with state attributes YAML are not updated too.

**Comment by bramkragten** [comment]
And how exactly do you expected me to have understood that from your issue description? 😉

**Comment by kukulich** [comment]
I'm sorry, I will try to be more clear in future.

**Comment by PablexXXXX** [comment]
I have the same issue. A refresh buttom would solve this. 
Everytime I need to update the state of the sensor I have just looked, I need to erase the name and then rewrite it.
