### ISSUE TITLE
Config flow progress dialog: Flickering scrollbar

### ISSUE THREAD

**Issue by spacegaier** [home-assistant/frontend#7213]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Although nothing seems to change in the content of the dialog, the scrollbar appears and then disappears again multiple times until the component config flow finishes.

![0715C629-5681-4690-8BFF-BCF5B036887E](https://user-images.githubusercontent.com/114137/94992966-e8407c80-058d-11eb-8e78-fc6a41ead498.GIF)

## Expected behavior

No scrollbar at all.

## Steps to reproduce

1. Go to integrations page inside HA
2. Add the speedtest integration
3. Once you confirm the initial popup asking you whether the integration should be added, the "dancing" scrollbars starts.

## Environment

- Home Assistant release with the issue: 0.116 dev
- Last working Home Assistant release (if known):
- Browser and browser version: FF 81.0.1 (64-bit) && Chrome 85.0.4183.121
- Operating system: Win 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by NoUsername** [comment]
I'll try to fix this 🤞 will be my first HA Frontend PR
