### ISSUE TITLE
MQTT lock.open 

### ISSUE THREAD

**Issue by mod25** [home-assistant/frontend#7218]
Dear maintainers, hope this finds you all well.
I'm switching from fhem to homeassistant and as i have my homematic devices connected to fhem i use mqtt to send cmnds to devices. what i have now i can't use lock.open service as it is not implemented in mqtt, i get following error:

File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 116, in open
    raise NotImplementedError()
NotImplementedError

Please add open support the mqtt.
Thank you very much

**Comment by ludeeus** [comment]
Welcome @mod25 :wave: 
This issue tracker for our frontend, however you are requesting additional features to our backend (core).
For those please use our [forum](https://community.home-assistant.io/c/feature-requests/13), thanks :+1:
