### ISSUE TITLE
FR: Add tap/hold_action to the weather-forecast card

### ISSUE THREAD

**Issue by jimz011** [home-assistant/frontend#7240]
## The request
Please add a feature that let's us do a tap or hold_action on the weather-forecast lovelace card. E.g. let us navigate to a weather view when pressing the weather card (or call a service for example)

## The alternatives
The alternative was using custom cards, but core is a cleaner way so I wish this was a feature in the core forecast card. Another alternative would be creating a completely new weather-card using picture-elements, but it seems cumbersome to create a new card with picture-elements when this could be addressed directly.

## Additional information
None provided.

**Comment by Mariusthvdb** [comment]
yes, that would be very nice. not only to navigate to another view, but also to  be able to go external:

```
      tap_action:
        action: url
        url_path: https://www.buienradar.nl
```

**Comment by spacegaier** [comment]
Fixed by https://github.com/home-assistant/frontend/pull/7659.
