### ISSUE TITLE
add start/stop to core integration MQTT

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#7244]
## The request

testing the instance for system overload, I tried to stop the MQTT integration, since this is a suspect for a lot of processor usage. Only to find out we can only delete the integration, and have to restart the full instance to have a system without MQTT.

This is not only cumbersome, but it also requires the system to completely calm down again after initial startup, and makes it rather unclear when the MQTT overload would be of influence.

A simple start/stop on the integration could solve this?

have that appear under 'Configure'

<img width="312" alt="Schermafbeelding 2020-10-06 om 09 25 40" src="https://user-images.githubusercontent.com/33354141/95171286-f83aa500-07b5-11eb-83f3-c0e1f2573174.png">

or maybe under the 3 dots Options

## The alternatives

as described above

**Comment by ludeeus** [comment]
Is this possible in the backend?

**Comment by ludeeus** [comment]
Any why only limit it to the MQTT integration?

**Comment by Mariusthvdb** [comment]
if this could be done for integrations in general that would be great of course, I simply stumbled on the need for it now with MQTT.

Posted it here in the frontend because an earlier request was directed here. So hope this is the correct repo.

**Comment by bramkragten** [comment]
This should first be made possible in the backend.
