### ISSUE TITLE
System Metrics: no bar charts displayed when viewed with Firefox.

### ISSUE THREAD

**Issue by tdejneka** [home-assistant/frontend#7254]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The System Metric feature does not display bar charts when viewed with Firefox on Ubuntu. The bar charts are displayed when viewed with Microsoft Edge (the chromium-based version).

## Expected behavior

Charts should also be displayed in Firefox.

## Environment

- Home Assistant release with the issue: 0.116.0
- Last working Home Assistant release (if known): new feature
- Browser and browser version: Firefox 81.0
- Operating system: Ubuntu 18.04.5

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by stefanroelofs** [comment]
I see the same bug on Windows:
![afbeelding](https://user-images.githubusercontent.com/37924749/95426041-91e48c80-0945-11eb-9cc9-fdd45b949f7e.png)

## Environment
  * Home Assistant release with the issue: 0.116.0
  * Browser and browser version: Firefox 81.0.1 (64 bit)
  * Operating system: Windows 10 version 2004
