### ISSUE TITLE
First day of week in lovelace calendar card month view

### ISSUE THREAD

**Issue by ptitmickey** [home-assistant/frontend#7262]
## The request

I would like to change the first day of week in lovelace calendar card month view.

## Additional information

I propose a new field with drop down menu of week days.

![image](https://user-images.githubusercontent.com/10517940/95436335-01fa0f00-0954-11eb-8389-b3e38093e1fe.png)

**Comment by Misiu** [comment]
Isn't this a duplicate of https://github.com/home-assistant/frontend/issues/5941?

**Comment by ptitmickey** [comment]
> Isn't this a duplicate of #5941?

Yes, you're right. I don't have seen this issue.
