### ISSUE TITLE
Synology DSM camera player popup not working in Opera

### ISSUE THREAD

**Issue by hmortensen83** [home-assistant/frontend#7267]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
When using Opera browser (Windows) and clicking on the camera picture, a popup should show live feed, but it triggers an error in the browser:
chunk.fd1b6240dc16a7fcc267.js:1 Uncaught DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
    at SourceBuffer.r._onSBUpdateEnd (https://<host>/frontend_latest/chunk.fd1b6240dc16a7fcc267.js:2:145498)
r._onSBUpdateEnd @ chunk.fd1b6240dc16a7fcc267.js:1

It's working fine in Chrome.

## Steps to reproduce
Add camera to dash board
Click the static image for a live feed popup

## Environment

- Home Assistant release with the issue: Home Assistant 0.116.0
- Last working Home Assistant release (if known):
- Browser and browser version: Opera 71.0.3770.228
- Operating system: 

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
This is an upstream issue it seems https://github.com/video-dev/hls.js/issues/1787
