### ISSUE TITLE
0.116: Ipad only shows one column in Lovelace when in vertical orientation. Used to show 2 columns.

### ISSUE THREAD

**Issue by msvinth** [home-assistant/frontend#7275]
## Checklist

- [ x] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.

## The problem

0.116.0 + 0.116.1 : Ipad only shows one column in Lovelace when in vertical orientation, making it a lot less useful.
In 0.115 and before it used to show 2 columns.

This is on an iPad Pro 11"

Screenshot from iPad

![IMG_B903FBE50BE1-1](https://user-images.githubusercontent.com/22496844/95581697-bd48a380-0a39-11eb-88ed-94ad88324ec7.jpeg)

Before 116 - approximately showing the columns
![Screenshot 2020-10-09 at 14 19 33](https://user-images.githubusercontent.com/22496844/95582175-9474de00-0a3a-11eb-88f0-7108b5ac4762.png)

**Comment by derandiunddasbo** [comment]
I can confirm this change for other tablets as well (Samsung Galaxy Tabs in my case). The columns seem to be rendered wider in 0.116 by default without any obvious reason.

**Comment by larsstaa** [comment]
Some problem here for Samsung Galaxy tab A in vertical orientation. Before it was two rows, now it has one row after update 0.116

**Comment by oischinger** [comment]
Same here on my Huawei mediapad t5

**Comment by bramkragten** [comment]
Not able to replicate, I got 2 columns:

![Uploading image.png…]()

**Comment by oischinger** [comment]
Wird. It doesn't seem to be density-related. Changing density to 800dp (instead of the native 600dp) doesn't change anything. Maybe it's related to the resolution?
I got 1920x1200

**Comment by larsstaa** [comment]
Galaxy Tab A is also 1920 x 1200.

**Comment by larsstaa** [comment]
After the last update 0.116.4 it is now working for me, two rows.

**Comment by oischinger** [comment]
For me the latest update made no difference.

**Comment by derandiunddasbo** [comment]
> After the last update 0.116.4 it is now working for me, two rows.

Still one row on my Galaxy Tabs with 0.116.4.

**Comment by msvinth** [comment]
Also still only one column on iPad Pro 11" with 0.116.4

**Comment by AmoebeLabs** [comment]
0.116.4 on iPad Pro 12.9:
- horizontal: 4 columns
- vertical: 3 columns

Has never been 1 or 2 columns...

**Comment by bramkragten** [comment]
Do you have any custom cards in use? If so, can you replicate it without the custom cards?
