### ISSUE TITLE
Automations gone when editing using GUI

### ISSUE THREAD

**Issue by henriec** [home-assistant/frontend#7280]
## Checklist

- [yes] I have updated to the latest available Home Assistant version.
- [yes] I have cleared the cache of my browser.
- [yes] I have tried a different browser to see if it is related to my browser.

## The problem

Since the update (sadly I'm not sure it was 115.2 or 115.4) it is not possible to edit automations using the GUI (web interface). I only create and edit automations using the GUI. Since very recently when I edit an automation (for example correct 1 character in the name/alias) all automations are gone except one. The modification is perfectly fine in the automations.yaml, but the GUI only shows (what appears to be) the most recently added one. Only after a reboot everything shows up nicely. That's only until you touch one automation....

## Expected behavior
Editing of an automation without the need to restart HA

## Steps to reproduce
 - Click Configuration in the Left menu
 - Click on "Automations"  -> Url should now be ..../config/automation/dashboard
 - Click on the pencil at the end of a line for 1 automation. 
 - Change 1 character in the name 
 - Click on the save button in the lower right
 - Click on "Automations" on the top bar (horizontal menu)

Now al the automations are gone except one. The automations.yaml looks fine. And after a reboot everything is working.

When you edit the only one visible automation now the rest shows up again, but the changes in the name are still not visible in the list.

## Environment

- Home Assistant release with the issue: 115.4 and 116.1
- Last working Home Assistant release (if known): :-( Don't know
- Browser and browser version: tried all 3 of these:
  Safari 13.1 (Version 13.1 (15609.1.20.111.8))
  Firefox 81.0
  Chrome 86.0.4240.75
- Operating system: OS X

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

No javascript errors. No errors whatsoever. The POST gets a 200 and the JSON reply is {"result": "ok"}

**Comment by spacegaier** [comment]
I cannot reproduce this with HA 0.117.0 and frontend 20201001.0.

**Comment by henriec** [comment]
I removed the last added automation. After a reboot and removing the "stale" leftover in the GUI and one more reboot the problem seems to be solved. I added the automation again using the GUI and now everything is working as expected. I think this was not a bug.
