### ISSUE TITLE
since 0.115mobile app integration no longer shows any entities in auto dashboard

### ISSUE THREAD

**Issue by charettepa** [home-assistant/frontend#7285]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

since 0.115mobile app integration no longer shows any entities in auto dashboard
the same issue continued into all 115 releases
the issue has continues into 116

## Expected behavior

to see mobile app entities in the auto dashboard or have the ability to add it

## Steps to reproduce

if you are on 115 or newer you will not see entities for your devices using the mobile app
downgrading to 114 or older return the entities
upgrading to 115 or newer removes them with no ability to add them
## Environment

- Home Assistant release with the issue: 115+
- Last working Home Assistant release (if known): 114.x
- Browser and browser version: chrome, edge, firefox all at latest version
- Operating system: homeassistant core running in docker  / windows 10 and linux mint for (clients) 

## State of relevant entities

none of the mobile app entities are shown and there are no options to show them unless you add them to a custom/manual dashboard.  

I do not want to create a manual dashboard as i like how the auto dashboard auto ads new items.

```yaml

```

## Problem-relevant configuration

having an auto dashboard instead of a custom/manual one
```yaml

```

## Javascript errors shown in your browser console/inspector

no errors are reported, the entities are simply not there as of 115
with no ability to add to the auto dashboard

```txt

```

**Comment by dshokouhi** [comment]
Please check the breaking changes from 0.115 this was one of them.

**Comment by SeanPM5** [comment]
This was intentional because the `mobile_app` integration contains a lot of sensors/entities. Especially if you used it on multiple devices (a phone and tablet for example) or have multiple family members that use it. You could end up with dozens of badges at the top of your screen, cluttering up the user interface.

What you can do is create a second dashboard under **Configuration** -> **Lovelace Dashboards** and take control of that one and add the mobile app entities to that one. You can add all the entities easily via the "Device Info" page for your mobile app, there'll be a listing of the entities on the left and an "Add to Lovelace" button underneath.

**Comment by dshokouhi** [comment]
Android installed on one device can go over 50 by itself lol

**Comment by charettepa** [comment]
creating a custom dashborad would be less of an issue you could keep access to the default one
even though the custom one is default
just because i have a custom one as default, does not mean i dont want to access the default one from time to time

please add the ability to have the default dashboard as a view at the top in the custom one
this would be quite nice

i have managed to do this by creating a new view and specifying the default address as ../lovelace/default_view
the problem is that if you accidentally move it as the first entity, it starts a loop
there could be an option when creating a custom dashboard (include view to default dashboard yes/no)
as well as a toggle in the dashboard settings

it could be all the way to the right and non moveable, but accesible

please consider this, i have attached a screen shot of what it currently looks like
having it all the way to the right and non moveable but selectable from the dashboard settings menu would be great

![image](https://user-images.githubusercontent.com/22502305/95630892-a792a880-0a50-11eb-8fbf-fee52be46d7a.png)

**Comment by charettepa** [comment]
> Please check the breaking changes from 0.115 this was one of them.

sorry I must have missed it

ability to add overview as a view in a custom dashboard would be really nice
best of both worlds as the custom could be default, overview would be gone, but accessible from the custom dashboard

**Comment by charettepa** [comment]
> Android installed on one device can go over 50 by itself lol

yes but you had the ability to hide the ones you did not want to see by disabling them
you could also add them to a group

now you cant see them at all without custom dashboard

ability to add views to default dashboard would be nice
if not ability to add overview as a view in a custom dashboard would be really nice
best of both worlds as the custom could be default, overview would be gone, but accessible from the custom dashboard
