### ISSUE TITLE
Brightness slider doesn't appear for a light group

### ISSUE THREAD

**Issue by dgtal1** [home-assistant/frontend#7307]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

In the previous HA versions I could set brightness for a group consisting of light entities. Now the brightness slider does not show up in the details view when I tap on a group entity in Lovelalce. I discovered a workaround for this: tap on a single light and then back on a light group. The slider then appears, but it's annoying that I have to do that every time I want  to control brighntess of a hole group (and I do that quite often for 3 light spots in my Living room).
![image](https://user-images.githubusercontent.com/27864579/95675689-52be7180-0bb9-11eb-9476-1b2db7d9abde.png)

## Expected behavior
Brightness slider should show up for a light group. It used to work fine in previous HA versions

## Steps to reproduce
1. Open HA GUI either HA app or desktop.
2. Tap on a group of lights
3. Observe no slider
4. Tap on a single light from this group
5. Slider appears just fine
6. Tap back on the light group. 
7. Then the slider apperas fine again but is lost when I refresh page or exit and reenter the HA app
![image](https://user-images.githubusercontent.com/27864579/95675697-6669d800-0bb9-11eb-84f1-676cde2382e5.png)

## Environment

, Windows 10, Android HA app (Android 10)
- Home Assistant release with the issue:  0.116.2.
- Last working Home Assistant release (if known): 0.113, maybe 0.115 as well, but not sure here
- Browser and browser version: Chrome 85.0.4183.121 + the newest HA Android app - same behaviour
- Operating system: Windows 10, Android 11

## State of relevant entities

![image](https://user-images.githubusercontent.com/27864579/95675727-a03ade80-0bb9-11eb-942f-f11940ae509e.png)
This happens for both situations when the lights in the group are on and off.
```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by Ritmjunk** [comment]
I’m experiencing the same issue...

**Comment by hiddedb** [comment]
Also experiencing this!

**Comment by bramkragten** [comment]
This is not a light group, but a group. A light group can be created like this: https://www.home-assistant.io/integrations/light.group/

**Comment by bramkragten** [comment]
Oh I now see the issue, the element is not loaded in the more info control of groups. I'll make a fix.

**Comment by dgtal1** [comment]
Would be great to see a fix for this in the nearest HA release. I think there's another problem here. I noticed once the slider gets visible again - the lovelace card shows some state attributes of one of the underlying entities, which is part of the group. I think this isn't correct as well as the group should only show stuff related to a group and not to a single entity.
