### ISSUE TITLE
Automation-trigger in log shows wrong (default) icon instead of custom icon

### ISSUE THREAD

**Issue by EddyK69** [home-assistant/frontend#7330]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

In the log-view, my automation 'Dag-mode' shows the default icon instead of the custom icon, when the automation has been triggered. When turning on/off the automation, the icon shows correct.

![automation1](https://user-images.githubusercontent.com/13943630/95830676-59bfbe00-0d38-11eb-9295-be23623ee61f.png)
![automation2](https://user-images.githubusercontent.com/13943630/95830688-5d534500-0d38-11eb-8c73-4c2d98fb9be4.png)
![automation3](https://user-images.githubusercontent.com/13943630/95830694-5f1d0880-0d38-11eb-8e20-cdc0e3923b4d.png)
## Expected behavior

I'd expect the same custom icon shows in the log for the same automation

## Steps to reproduce

1) Create automation
2) Set custom icon
3) Trigger automation
4) Show log

## Environment

- Home Assistant release with the issue: 0.116.2 on HASOS 5.2 (rPi 4)
- Last working Home Assistant release (if known): unkown, never noticed this before
- Browser and browser version: Safari 13.1.2 / Chrome 86.0.4240.75
- Operating system: MacOS 10.13.6
## State of relevant entities

```yaml

```
## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
I think that might be by design, to easily show that this was a log entry based on an automation.
