### ISSUE TITLE
Icon Picker/Search

### ISSUE THREAD

**Issue by stephengolub** [home-assistant/frontend#7334]
## The request

An autocomplete or pop up for the various places that we can specify icons would make choosing appropriate icons much simpler.

## The alternatives

Currently, my procedure is to go to [materialdesignicons.com](materialdesignicons.com) and search for an icon I want then copy/paste it into the field.

If there is any version drift, and that icon isn’t available in HA, then it won’t show up and I have to go back and choose a different icon.

## Additional information

I realize that the full “tagged” values that are available on the mdi site may not be available, which isn’t a big deal.

**Comment by Fmstrat** [comment]
I would love to see something like this added in instead: https://codepen.io/mortenson/pen/GMBeEg/

**Comment by wojtek14a** [comment]
I think it might be closed now, we have this picker from 2021.11.

One thing I would consider is adding this picker also in developer tool, sometimes I just want to browse all possible icons and search for one that fits my case. To do it now, I have to go into any entity, click change icon and after browsing them I just click cancel. It would be great if I had this quickly accessible next to other "developer" tools but right now it is already much easier than it was before with the MDI website!

**Comment by wojtek14a** [comment]
How about 2 part of my message? Should I create new feature request for it?

**Comment by spacegaier** [comment]
I you feel strongly about it, you can create a feature request, but I personally do not see (or get) your use case for that.
