### ISSUE TITLE
Highlighting of views with direct links

### ISSUE THREAD

**Issue by PhilippMundhenk** [home-assistant/frontend#7336]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

In the mobile view, when using a navigate link to directly skip to a view (e.g., via /lovelace/4), the first view icon still remains highlighted by color, although underline is removed (see screenshot below: house is still white).

## Expected behavior

Only icon for currently active view should be highlighted.

## Steps to reproduce

1. create two views
2. in the first view, add an icon with
```yaml
tap_action:
  action: navigate
  navigation_path: /lovelace/1/
```
3. open UI in mobile view (e.g., HA app, Chrome, ...)
4. click the icon
5. observe, how underline moves to view 2, but view 1 icon remains highlighted

## Environment

- Home Assistant release with the issue: 0.116.2 (earlier versions were also affected, at least sind 0.96)
- Last working Home Assistant release (if known):
- Browser and browser version: All tested browsers (current versions of Chrome, Firefox, and HA app)
- Operating system: Android

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
![Screenshot_20201013-200531_Home Assistant](https://user-images.githubusercontent.com/4414560/95899256-93bcae80-0d90-11eb-8719-36aca8686e30.jpg)

**Comment by spacegaier** [comment]
@PhilippMundhenk Can you test again with the latest version? I did not test if before, but at least currently it works fine for me in the mobile app.

**Comment by PhilippMundhenk** [comment]
@spacegaier: I updated to 0.116.4, the latest/stable on Docker Hub. I still have the same issue. When trying just now, I noticed, however, that I can narrow down the conditions on when it happens a bit more:

- start the app
- click link to view
=> Everything works as intended!
- return to original view
- click link again
=> Original view icon remains lit!

Note also in my screenshot above, that the bar of view icons is scrollable and slightly scrolled to the right. I also noticed that when scrolling all the way to the left, ensuring that the house icon is fully visible, the highlight color is reset to normal gray. I would suspect something wrong in the combination of scrolling and highlighting.

**Comment by spacegaier** [comment]
Sorry I  was a bit unspecific. With latest I had meant 0.117 (current beta) since there were changes to the header in it. But I just tested again and now I also see the issue on my mobile. I might just not have spotted it before.

The old icon color gets reset if you click into the new tab or as you said if you scroll the tab bar.
