### ISSUE TITLE
Add new device class 'tamper' for binary_sensor

### ISSUE THREAD

**Issue by mamrai1** [home-assistant/frontend#7347]
## Checklist

- [ x] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
@mamrai1 At least to me it's unclear what you are referring to. Where is something missing here in the frontend specifically? Please provide some more details and ideally screenshots if helpful.

**Comment by mamrai1** [comment]
Weird..
