### ISSUE TITLE
Supervisor 248 Incorrectly shows addon options and can't edit options

### ISSUE THREAD

**Issue by DavidFW1960** [home-assistant/frontend#7393]
**Home Assistant release with the issue:**

**Operating environment (HassOS/Generic):**

**Supervisor logs:**

20-10-19 01:27:52 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with fe41fc28_caddy!
20-10-19 01:27:53 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_fe41fc28_caddy application
20-10-19 01:27:53 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on korylprince/hassio-caddy-amd64 with version 1.6
20-10-19 01:27:54 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_fe41fc28_caddy application
20-10-19 01:27:55 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on korylprince/hassio-caddy-amd64 with version 1.6
20-10-19 01:28:07 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_fe41fc28_caddy application
20-10-19 01:28:23 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with fe41fc28_caddy!
20-10-19 01:28:23 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on korylprince/hassio-caddy-amd64 with version 1.6
20-10-19 01:28:27 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_fe41fc28_caddy application
20-10-19 01:29:06 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on korylprince/hassio-caddy-amd64 with version 1.6

**Description of problem:**
When I go into the addon options (all addons) there are no configuration options displayed.
If I try and enter the options, it can't save them.
If I restart the addon everything works as though the options are there and I see in the options.json file in /usr/share/hassio/addons/data/fe41fc28_caddy for the caddy addon for example are all in that file.
![image](https://user-images.githubusercontent.com/36390762/96392522-15d12b00-1208-11eb-985b-3106f3da5233.png)

**Comment by Mariusthvdb** [comment]
seeing the same here on 248:

<img width="1121" alt="Schermafbeelding 2020-10-19 om 15 19 34" src="https://user-images.githubusercontent.com/33354141/96456243-897e3280-121e-11eb-959b-cb08af92a490.png">

<img width="1102" alt="Schermafbeelding 2020-10-19 om 15 20 11" src="https://user-images.githubusercontent.com/33354141/96456294-9ac73f00-121e-11eb-934d-9d02e61e4d9d.png">

instance working fine, all add-on configurations are empty...
