### ISSUE TITLE
Quick Bar: Shortcut for command input not working in Firefox

### ISSUE THREAD

**Issue by spacegaier** [home-assistant/frontend#7410]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

As already discussed with @donkawechico, Firefox catches the shortcut `Ctrl + Shift + P` to open a new private session window. So it cannot be used to open the quick bar currently.

Current workaround: Open the entities quick bar (`Ctrl + P` works fine in FF) and then type ">" to get to the command input.

## Expected behavior

`Ctrl + Shift + P` opens the quick bar command input.

## Steps to reproduce

1. Open frontend
2. Use the shortcut
3. Watch a new private FF window popping up 😒 

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version: FF 81.0.2 (64-bit)
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by donkawechico** [comment]
Thank you @spacegaier. Looks like a known issue in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1325692

We'll need to think this through a bit. We don't want to be juggling a ton of shortcut variations for different environment combinations, but we'd obviously like the experience to be consistent.

**Comment by donkawechico** [comment]
Just tried a bunch of other potential workarounds I found (mostly from [here](https://support.mozilla.org/gl/questions/1241294)), and none of them worked. Tried several "shortcut override" extensions and none of them allow you to override Ctrl+Shift+P. So I'm pretty sure this is a shortcut FF just won't let web apps override.

A couple options I see:
1. Allow user to type Ctrl+P to launch, and Ctrl+P to toggle between modes (my favorite)
2. Use Alt+Shift+P for firefox
3. Add a small, circular, floating fab button to some corner of the UI. Added benefit of working on mobile
4. Double-tapping on the sidebar header launches dialog. Added benefit of working on mobile
5. Adding "Quick Bar" as a left nav clickable row

**Comment by zsarnett** [comment]
The same key set should work on all browsers. So if we have to change it to Alt+shift+P it should be for all browsers.

I think the first option is best out of these.

But also, why CTRL shift P?

Why not CTR+SHIFT+Q?

Just curious

**Comment by donkawechico** [comment]
> But also, why CTRL shift P? Why not CTR+SHIFT+Q?

Because both VS Code and Chrome Devtools use Ctrl+P and Ctrl+Shift+P for their "quick bar" features. It felt the most consistent.

**Comment by spacegaier** [comment]
> 
> I've seen "?" used in web apps to launch hotkey suggestions modals. We could use the "?" here since it also means "query", which is what the quick bar is sorta doing.

Wondering how that would work on a German keyboard where "?" is only accessible by pressing Shift as well. Would that mean that both command for displaying entities and commands would be the same 😕 ?

**Comment by spacegaier** [comment]
Reg. Ctrl + Shift + Q: That is the exit command for Firefox. So indeed a bit risky since if the focus is not properly set on the page to intercept the event, the user would accidentally close all browser windows.

**Comment by Misiu** [comment]
JIRA is using double G (<kbd>G</kbd> + <kbd>G</kbd>) and dot (<kbd>.</kbd>) to show a quick bar.
Maybe similar shortcut can be used for now? Or leave <kbd>Ctrl</kbd> + <kbd>P</kbd>, putting extra <kbd>></kbd> doesn't take long.
GitHub codespaces have the exact same problem on Firefox. I think we must wait for the linked issue to be fixed. Sadly we can't comment on it.
