### ISSUE TITLE
Aarm panel buttons - poor visibility in dark mode.

### ISSUE THREAD

**Issue by tomlut** [home-assistant/frontend#7440]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When dark mode is activated the alarm panel button outlines are very difficult to see. 
## Expected behavior
Not hard coded to a dark value. 

## Steps to reproduce

1. Add an alarm panel (example below)
2. Activate dark mode.

## Environment

- Home Assistant release with the issue: 0.117.0b1
- Last working Home Assistant release (if known):
- Browser and browser version: Firefox 82.0
- Operating system: Windows 10

## State of relevant entities

Light
![Screenshot_2020-10-22 Overview - Home Assistant(2)](https://user-images.githubusercontent.com/10679300/96871049-28a76200-148b-11eb-816e-144af97d211d.png)

Dark
![Screenshot_2020-10-22 Overview - Home Assistant(1)](https://user-images.githubusercontent.com/10679300/96871172-542a4c80-148b-11eb-94d1-94ab23c938dd.png)

```yaml

```

## Problem-relevant configuration

```yaml
entity: alarm_control_panel.house
name: Alarm Panel
states:
  - arm_away
type: alarm-panel
```

## Javascript errors shown in your browser console/inspector
Nil

```txt

```

## Additional information
The text and button outlines could use the primary and secondary text colours instead of being hard coded.

**Comment by tomlut** [comment]
I am informed that `--mdc-button-outline-color` is the element responsible.

**Comment by spacegaier** [comment]
> 
> 
> I am informed that `--mdc-button-outline-color` is the element responsible.

That is correct. PR created.
