### ISSUE TITLE
After navigating to another dashboard or switching browser tabs Quick Bar shortcut doesn't work until page clicked

### ISSUE THREAD

**Issue by gadgetchnnel** [home-assistant/frontend#7442]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When navigating to another Lovelace dashboard or switching tabs in the browser, the keyboard shortcut for the Quick Bar doesn't work (brings up the standard print dialogue box instead) until the page is clicked.

## Expected behavior

Quick Bar keyboard shortcut works immediately after navigating to another dashboard or switching tabs.

### Method 1
1. Navigate to another Lovelace dashboard (or to another panel, such as Map and back to the same dashboard)
2. Press Cmd+P in macOS or Ctrl+P in Windows

### Method 2
1. Switch to a different tab in the browser
2. Switch back to the tab with Home Assistant
3. Press Cmd+P in macOS or Ctrl+P in Windows

After doing either of these the print dialogue box will be displayed instead of the Quick Bar.
After clicking on the page the keyboard shortcut will display the Quick Bar as expected.

## Environment

- Home Assistant release with the issue: 0.117.0b1
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome 86.0.4240.80
- Operating system: macOS Catalina 10.15.7

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
The problem with the first method is known (and I think covered in the documentation): The main content area of the page needs to have the focus currently. For it to work in the sidebar, some underlying things have to be changed in the frontend first, which are already being worked on.

**Comment by gadgetchnnel** [comment]
I also haven't been able to reproduce the issue switching tabs again either, so the page probably didn't have focus before I switched tabs like you said.

**Comment by donkawechico** [comment]
This is a known issue. The fix is to refactor the left nav to use `<mwc-list>` instead of `<paper-listbox>` (paper-listbox has a known bug with event propagation that will never be fixed).

This is non-trivial, but we already have a PR being worked on: https://github.com/home-assistant/frontend/pull/7326
