### ISSUE TITLE
Attribute name being wrongly capitalised in more-info dialogue

### ISSUE THREAD

**Issue by gadgetchnnel** [home-assistant/frontend#7447]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The name of the is_hidden attribute (from one of the Android app WiFi sensors) is incorrectly capitalised in the more-info popup for that sensor as "Is hIDden"

![image](https://user-images.githubusercontent.com/2099542/96892866-fc3b1800-1481-11eb-89e3-f5a5863fed64.png)

It looks like this was introduced this PR: https://github.com/home-assistant/frontend/pull/7313 which is replacing any instance of **id** in the attribute name with **ID**. This should probably not be happening mid-word.

## Expected behavior

The attribute name shows as "Is hidden"

## Steps to reproduce

1. Add an Android app WiFi sensor to an Entities card
2. Click on the entity

## Environment

- Home Assistant release with the issue: 0.117.0b1
- Last working Home Assistant release (if known): 0.116.4
- Browser and browser version: Chrome 86.0.4240.80 (Official Build) (x86_64)
- Operating system: macOS Catalina 10.15.7 (19H2)

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
I had detected that myself already after my initial PR was merged and fixed that in my related PR which is not yet merged: https://github.com/home-assistant/frontend/pull/7337

Since some parts of the second PR still need some more work I will split the regex part into a new PR to get that bug fixed.
