### ISSUE TITLE
HACS frontend cards only visible after refreshing the page

### ISSUE THREAD

**Issue by DasBootU96** [home-assistant/frontend#7452]
## Checklist

- [v] I have updated to the latest available Home Assistant version.
- [v] I have cleared the cache of my browser.
- [v] I have tried a different browser to see if it is related to my browser.

## The problem
I’ve added some HACS front ends like weather card and upcoming media card (using radarr/sonarr/kodi integrations).

When opening the home assistant webpage, these HACS front end cards are not visible. When the page is refreshed, the HACS integrations show up. Usually.

Same behavior in different browsers Edge/Brave/Chrome. Also same on Android Chrome and Android companion app. It does not matter if I connect (ssl:443) to the duckdns.org name or home assistants ip address (8123).

## Expected behavior
HACS cards show up always when the web page loads.

## Steps to reproduce
1. Install any HACS frontend
2. Configure it in LoveLace
3. Open home assistant web page
4. Notice missing HACS entity. Press F5. Entity usually shows. F5 again and sometimes HACS entity is gone.

## Environment
| Description                | Value |
| -------------------------- | ----- |
| HACS version               |1.6.0
| Home Assistant version     |0.116.4
| Last working Home Assistant release      |new install 0.116.0, upgraded to 0.116.4
| Installation method for HA |https://github.com/home-assistant/operating-system/releases/download/4.14/hassos_ova-4.14.vhdx.gz
| Web browser                |Edge/Brave/Chrome
| Web browser version        |Version 86.0.622.48 (Official build) (64-bit) / Version 1.15.76 Chromium: 86.0.4240.111 (Official Build) (64-bit) / Version 86.0.4240.111 (Official Build) (64-bit)
| Operating system        |Windows 10 64-bit - 2004

## State of relevant entities
Here is an animated GIF that shows missing entities when loaded. Pressing F5 will usually show them. This is just an example of the upcoming media cards, but I see the same behavior for others like weather card or the simple thermostat.

![m3jQ5wgOGo](https://user-images.githubusercontent.com/54699211/96925289-33c2b800-14b4-11eb-967d-db75cc1896a3.gif)

Changed ```/hacsfiles/``` to ```/local/community/``` like in the screenshot below, but still the same behavior.
![hacstolocalcommunity](https://user-images.githubusercontent.com/54699211/96925807-ff9bc700-14b4-11eb-8cf9-11f932328939.JPG)

**Note:** Opened HACS issue https://github.com/hacs/integration/issues/1597, but https://github.com/ludeeus mentioned it is not a HACS issue.

```yaml

```

## Problem-relevant configuration

```
type: 'custom:upcoming-media-card'
entity: sensor.sonarr_upcoming_media
title: Upcoming TV
```
```
type: 'custom:weather-card'
entity: weather.lelystad_6269
name: Almere
number_of_forecasts: '5'
```

## Javascript errors shown in your browser console/inspector

<details>
  <summary>Logs</summary>

```

Followed guide https://support.google.com/docs/thread/1873663?hl=en

Errors from 'recently added episodes' and Kodi who want to use http instead of ssl https. 
This only happens on this page. 
The page where HACS 'weather card' and 'simple thermostat' live, show console message: No issues detected so far, yet they are not visible.

10Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure element '<URL>'. This request was automatically upgraded to HTTPS, For more information see <URL>
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://192.168.1.17:8080/image/image%3A%2F%2Fsmb%253A%252F%252Fnas.my.domain%252FMoviesAndSeries%2524%252FTelevision%252FStar%2520Trek-%2520Discovery%252Ffanart.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://192.168.1.17:8080/image/image%3A%2F%2Fsmb%253A%252F%252Fnas.my.domain%252FMoviesAndSeries%2524%252FTelevision%252FThe%2520Third%2520Day%252Ffanart.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://192.168.1.17:8080/image/image%3A%2F%2Fsmb%253A%252F%252Fnas.my.domain%252FMoviesAndSeries%2524%252FTelevision%252FThe%2520Third%2520Day%252Ffanart.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://192.168.1.17:8080/image/image%3A%2F%2Fsmb%253A%252F%252Fnas.my.domain%252FMoviesAndSeries%2524%252FTelevision%252FThe%2520Third%2520Day%252Ffanart.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://192.168.1.17:8080/image/image%3A%2F%2Fsmb%253A%252F%252Fnas.my.domain%252FMoviesAndSeries%2524%252FTelevision%252FThe%2520Third%2520Day%252Ffanart.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://image.tmdb.org/t/p/original/AfgTcW4C6gq6JyUj6KcEs3ZBgeb.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://image.tmdb.org/t/p/original/8sEsY2btFsYULAS0dl21gy64qzQ.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://image.tmdb.org/t/p/original/aO5ILS7qnqtFIprbJ40zla0jhpu.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://image.tmdb.org/t/p/original/v8Nf6Y1qL1Q3PWTBezXNPPaXqza.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/lovelace/media:1 Mixed Content: The page at 'https://example.duckdns.org/lovelace/media' was loaded over HTTPS, but requested an insecure element 'http://image.tmdb.org/t/p/original/rFDWMS8WwAxvFkn8txGDjnZRhkl.jpg'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
2/lovelace/media:1 GET https://192.168.1.17:8080/image/image%3A%2F%2Fsmb%253A%252F%252Fnas.my.domain%252FMoviesAndSeries%2524%252FTelevision%252FStar%2520Trek-%2520Discovery%252Ffanart.jpg net::ERR_CONNECTION_CLOSED



```

</details>

## Additional information
https://github.com/hacs/integration/issues/1597

**Comment by bramkragten** [comment]
Was already fixed.

**Comment by DasBootU96** [comment]
That was quick 👍 
Do you have some details please? Where can I find more info? Thanks!

**Comment by bramkragten** [comment]
<https://github.com/home-assistant/frontend/pull/7407>

Please search the closed issues before opening a new one.
