### ISSUE TITLE
Alarm Panel Number/Keypad Border Changes

### ISSUE THREAD

**Issue by reotto613** [home-assistant/frontend#7456]
## Checklist

- [YES ] I have updated to the latest available Home Assistant version.
- [ YES] I have cleared the cache of my browser.
- [ YES] I have tried a different browser to see if it is related to my browser.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release 116.2:
- Browser and browser version: Chrome: Version 86.0.4240.111
- Operating system: Windows 10 Enterprise

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/pull/7444
