### ISSUE TITLE
Vertical scroll bar always visible on latest 

### ISSUE THREAD

**Issue by rgogada** [home-assistant/frontend#7462]
## Checklist

- [x] updated to 0.117.0b1
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

vertical scroll bar always visible on 0.117.0b1. 

## Expected behavior

when the content fits in the window, no scroll bar should appear. 

## Steps to reproduce

1. update to 0.117.0b1
2. Navigate to Lovelace
3. and the scroll bar is visible always irrespective of content size

## Environment

- Home Assistant release with the issue: 0.117.0b1
- Last working Home Assistant release: 0.116.4
- Browser and browser version: chr0me 86
- Operating system: Win 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by iantrich** [comment]
I'm not seeing this. Have you cleared your browser's cache, you didn't check that box above?

**Comment by rgogada** [comment]
@iantrich thanks for your response.

yes, I did clear the browser cache. please refer to the below screenshot. I was referring to the right side scroll bar. NO matter how big I make the window, it doesn't go away. this is new behavior in 0.117 beta.

![ss1](https://user-images.githubusercontent.com/4284896/96958545-4e913d00-1545-11eb-96c7-c7f7d9ab6285.png)

thanks again for looking into this. let me know if you need any further info.

**Comment by iantrich** [comment]
Is that panel mode with stacks or layout-card?

**Comment by spacegaier** [comment]
> 
> 
> I'm not seeing this. Have you cleared your browser's cache, you didn't check that box above?

I cannot reproduce that on my end either. I only get scrollbars if the content is stacked higher than the screen.

**Comment by rgogada** [comment]
> Is that panel mode with stacks or layout-card?

Yes, it's a panel view

**Comment by spacegaier** [comment]
In panel mode I can reproduce and confirm the issue.

Looks like this is the CSS culprit that forces an element to be too high:

```
#view {
    min-height: calc(100vh - var(--header-height));
    ...
}
```

**Comment by rgogada** [comment]
looks like the issue is actually caused by custom:vertical-stack-in-card. I will create an issue with them instead. thanks for looking into this.
