### ISSUE TITLE
Flickering scrollbars on history graph tooltip

### ISSUE THREAD

**Issue by Santobert** [home-assistant/frontend#7473]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The new tooltip on the history graphs leads to flickering scroll bars on the right and below the map. The reason could be a very long entity id. Sometimes the entity di is also too long for the tooltip, as you can see on the second picture.

### Entity id is too long and the tooltip goes beyond the card
![grafik](https://user-images.githubusercontent.com/15657682/97094916-c3559b80-1659-11eb-9509-cf7c2def762d.png)

### Entity id is too long and the entity id goes beyond the tooltip
![grafik](https://user-images.githubusercontent.com/15657682/97094958-1deef780-165a-11eb-930a-b9e16699e145.png)

## Expected behavior

The entity id and the tooltip fit into the card.

## Steps to reproduce

1. history graph with long entity ids
2. move the mouse over the card

## Environment

- Home Assistant release with the issue: 0.117.0b3
- Last working Home Assistant release (if known): Not known
- Browser and browser version: Firefox 81.0.1
- Operating system: Arch Linux with KDE Plasma

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

- Using 0.117.0b3
- May be related to https://github.com/home-assistant/frontend/pull/7310

**Comment by spacegaier** [comment]
I created a PR for the non wrapped entity IDs. But I am unsure about the second part (the tooltip size itself). 

Depending on the size/content of the card, showing a scrollbar is required to ensure the tooltip can be seen completely. However, the initial card size does not account for that, but instead only adds the scrollbars if/when needed to show a tooltip. This behavior makes sense to me.
Could you please elaborate a bit, what the issue is with the scrollbars?

**Comment by Santobert** [comment]
First of all, thank you for your work!

> Could you please elaborate a bit, what the issue is with the scrollbars?

The current behavior results in a bad user experience because the tooltips are somewhat fluid and from the user's point of view it is not really clear why the scrollbars are needed.
From a technical view it's completely clear, why the scrollbars are there. But they shouldn't be needed in my opinion. The tooltip follows the mouse, so you can not reach out for the scrollbar without changing the whole situation. In my opinion the tooltips should be placed completely inside the card. They should be near the mouse, but most importently they should be completely visible without scrolling.
Furthermore the scrollbars stay there when the mouse left the card and the tooltip is gone.
What do you think?

![HA_tooltip](https://user-images.githubusercontent.com/15657682/97200386-6f5dca80-17b1-11eb-9fb9-f0beefd58f89.gif)

**Comment by Youpimatin** [comment]
I have the same "issue" on the graph card, when the value is in low on the vertical scale, and the tooltip can not display entirely,
scrollbars appear (but I can't see the tooltip anyway)

**Comment by Santobert** [comment]
Solved in 1.0.0b4
