### ISSUE TITLE
Calendar panel not taking full width in desktop browser

### ISSUE THREAD

**Issue by gadgetchnnel** [home-assistant/frontend#7474]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The calendar panel is not taking up the full width of the page in desktop browsers:

It initially displays like this:
![image](https://user-images.githubusercontent.com/2099542/97105442-984b6600-16b2-11eb-9950-23e2210d89fe.png)

Then after a second or so, displays like this:
![image](https://user-images.githubusercontent.com/2099542/97105391-3f7bcd80-16b2-11eb-979b-137efdc303c6.png)

## Expected behavior

Calendar should take full width of page
## Steps to reproduce

Open Calendar panel

## Environment

- Home Assistant release with the issue: 0.117.0b3
- Last working Home Assistant release (if known):
- Browser and browser version: Google Chrome 86.0.4240.80
- Operating system: macOS Catalina 10.15.7 (19H2)

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
Should have been fixed by https://github.com/home-assistant/frontend/pull/7505.
