### ISSUE TITLE
Attempt to use history.pushState() more than 100 times per 30 seconds

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#7481]
## The problem

log flooded with this error during a single minute act night,
## Environment

- Home Assistant Core release with the issue: 0.117.0b3
- Last working Home Assistant Core release (if known): X
- Operating environment (OS/Container/Supervised/Core): OS
- Integration causing this issue: history
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/history/

## Problem-relevant `configuration.yaml`

```yaml
history:
```

## Traceback/Error logs

many hundreds of lines like:

```txt
2020-10-25 01:10:43 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2587861080] Client exceeded max pending messages [2]: 2048
2020-10-25 01:10:43 ERROR (MainThread) [frontend.js.latest.202010212] https://redacted/frontend_latest/app.732ca2f5.js:846:247005 SecurityError: Attempt to use history.pushState() more than 100 times per 30 seconds
```

## Additional information

no indication what caused this, or stopped it, seems to have been a huuuge burst all in 1 minute

**Comment by bdraco** [comment]
Yup its JS not the backend its a literal call to `window.history.pushState`

**Comment by Mariusthvdb** [comment]
found it in bar-card,mini-graph-card, mini-media-player, button-card, swipe-card, simple-weather-card, multiple-entity-row, and browser-mod and some smaller .js files I dont recognize (chunks)

which URL is that Ludeeus? that could be a good pointer

**Comment by ludeeus** [comment]
You only have 1

**Comment by Mariusthvdb** [comment]
> It's the browser URL.

o I see ;-)
shouldn't change that!

on; y thing coming close to that core functionality in my list above would seem browser-mod, and that was updated today yet again.

I'll keep an aye (and debug logger) in that, to see if it attempts once more.
thanks.

**Comment by ludeeus** [comment]
Navigating changes the URL, that is expected.
But > 100 in 30s is not.

**Comment by Mariusthvdb** [comment]
yep, and I got many hundreds of these in that short span of time. still, it was the first and only time (yet).

**Comment by Mariusthvdb** [comment]
closing now, haven't seen this happen anymore, now on 118.3
