### ISSUE TITLE
Call service by drag and drop entities

### ISSUE THREAD

**Issue by junior013** [home-assistant/frontend#7489]
Could be useful - especially on picture-element card - to call service by dragging entities and dropping to an area, or another entity.

It could be used to:
- copy the current state of one entity to another
- move media played on one media_player to another
- group medi_players by dropping one to another
- modify entity attribute with dragging distance and/or direction

**Comment by zsarnett** [comment]
Please fill out a Feature request template

**Comment by junior013** [comment]
@zsarnett Sorry, but where can I found? There's only temlate for bug report, not for feature request.

**Comment by zsarnett** [comment]
Sorry  Iforgot we took that out. We now use Discussions for Feature requests
