### ISSUE TITLE
[Beta] Sidebar displays in lowercase when reloading from non-Lovelace page with sidebar expanded

### ISSUE THREAD

**Issue by gadgetchnnel** [home-assistant/frontend#7512]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When the sidebar is expanded and the page is reloaded from a non-Lovelace page (e.g. Configuration, Logbook, etc.), the sidebar labels appear in lowercase or are missing entirely:

![image](https://user-images.githubusercontent.com/2099542/97444160-bf5c9e80-1923-11eb-8e89-f70469cf999d.png)

It displays correctly when reloading from a Lovelace page

![image](https://user-images.githubusercontent.com/2099542/97444404-0480d080-1924-11eb-9162-bcee0ea9aae3.png)

This appears to be related to loading or applying of translations as, when switching to a different language in profile settings, the lowercase sidebar is still in English.

## Expected behavior

Should display sidebar correctly when reloading from any page.

## Steps to reproduce

1.  Expand sidebar
2. From Configuration page, reload page in browser - should see sidebar with lowercase labels (first screenshot)
2. Navigate to Lovelace dashboard
3. Reload again - correct sidebar should show (second screenshot)

## Environment

- Home Assistant release with the issue: 0.117.0b6
- Last working Home Assistant release (if known): 0.114
- Browser and browser version: Chrome 86.0.4240.80 
- Operating system: macOS Catalina 10.15.7

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by gadgetchnnel** [comment]
Found that this affects more than the sidebar, it seems to affect other sections which use translations.

For example, after reloading from a non-Lovelace page, clicking the "System options" menu for an integration in Integrations displays like this:

![image](https://user-images.githubusercontent.com/2099542/97472069-5421c500-1941-11eb-8fd9-bd69576c1509.png)

and editing an entity in Entities looks like this:

![image](https://user-images.githubusercontent.com/2099542/97472361-ad89f400-1941-11eb-849f-b82d9ae150f0.png)

**Comment by kukulich** [comment]
I can confirm it in 0.117.1.

**Comment by poudenes** [comment]
here also in 0.117.1

**Comment by MrLemur** [comment]
Still showing in 0.117.2

**Comment by TomBrien** [comment]
This is seen a fair amount in the iOS app (WebView)

**Comment by adamjernst** [comment]
I ran into this too — fixed in #7597.
