### ISSUE TITLE
Bug. Missing "Done" button in 0.117.0 when reordering sidebar

### ISSUE THREAD

**Issue by bessarabov** [home-assistant/frontend#7522]
This is screenshot from 0.116.4 — After pressing "Edit" button the button "Done" is visible and it is working

![Screenshot 2020-10-29 at 16 57 08](https://user-images.githubusercontent.com/47263/97583449-058b2e00-1a08-11eb-85a2-0c79b688ae16.png)

This is screenshot from 0.117.0 — After pressing the same "Edit" button there is no "Done" button. And the only way to stop editing is to refresh the page.

![Screenshot 2020-10-29 at 16 59 45](https://user-images.githubusercontent.com/47263/97583759-5733b880-1a08-11eb-80f4-511f9a430bf6.png)

## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## Environment

- Home Assistant release with the issue: 0.117.0
- Last working Home Assistant release (if known): 0.116.4
- Browser and browser version: macOS, tried google chrome Google Chrome 86.0.4240.111 (WebKit 537.36) & Firefox 82.0 (Gecko 82.0)
- Operating system: macoS Catalina 10.15.6 (19G2021)

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

No errors.

```txt

```

**Comment by bramkragten** [comment]
I'm not able to reproduce this

**Comment by bessarabov** [comment]
> I'm not able to reproduce this, did you clear your cache?

I've cleared the cache in google chrome & I also installed fresh new browser Firefox — The bug is still present, there is no "Done" button. 

I have two different working servers Home Assistant — on both I have the same but.

But I've tried fresh install of Home Assistant 0.117.0 — and there is no such bug there.

**Comment by 3ative** [comment]
I updated to 0.117 this morning and 'Done' button is still there for me. 
![image](https://user-images.githubusercontent.com/51385971/97618949-8ef62c80-1a17-11eb-8db9-282a515e3463.png)

**Comment by ShonP40** [comment]
I had the same issue.
Removing the Favicon Changer integration (and then restarting HA) fixed it.

**Comment by bessarabov** [comment]
> I had the same issue.
> Removing the Favicon Changer integration (and then restarting HA) fixed it.

Thank you! You are right. I'm using https://github.com/thomasloven/hass-favicon and after removing it the Done button appears.

I've created an issue in the Favicon Changer repo — https://github.com/thomasloven/hass-favicon/issues/17
