### ISSUE TITLE
0.117 - History-graph popups are shown inside the card element, creating scrollbars

### ISSUE THREAD

**Issue by LordMike** [home-assistant/frontend#7523]
## Checklist

- [x] I have updated to the latest available Home Assistant version. (0.117)
- [x] I have cleared the cache of my browser. (Ctrl+F5)
- [x] I have tried a different browser to see if it is related to my browser. (FF+Edge)

## The problem
After updating to 0.117, the `history-graph` seems to cap popup boxes within the card.

Notice the scroll bar and lacking time to/from.

![image](https://user-images.githubusercontent.com/1027111/97586294-63187e00-19fa-11eb-9ede-19673b1fc8e0.png)

## Expected behavior
Pre-0.117, the popups were shown outside the card if needed.

## Steps to reproduce
1. Add history-graph with 1+ entities
2. Hover over one of the values in the graph

## Environment
- Home Assistant release with the issue: 0.117
- Last working Home Assistant release (if known): 0.116 and earlier
- Browser and browser version: FF 81, Edge (unknown version .. win10)
- Operating system: Windows 10

## State of relevant entities
This occurs for both sensors shown as bars like in my example, and numerical sensors like temperature sensors. 

## Problem-relevant configuration
```yaml
entities:
  - entity: person.mike
hours_to_show: 24
refresh_interval: 0
type: history-graph
```

## Javascript errors shown in your browser console/inspector
```txt
None
```

**Comment by bramkragten** [comment]
it is caused by <https://github.com/home-assistant/frontend/commit/c1dba462e8d1b060b86c3c15c269af966506a711#diff-12a40717c10cf0b428a66ee521fa774c1b8aabe223bc23852e025daf8ac9c2a9R192> @zsarnett do you remember why you added that? Can we remove the overflow?

**Comment by LordMike** [comment]
Well.. That was fast. :)
