### ISSUE TITLE
Custom themes not applied to individual panels when specified in the UI

### ISSUE THREAD

**Issue by drjjr2** [home-assistant/frontend#7549]
## Checklist

- [X ] I have updated to the latest available Home Assistant version.
- [X ] I have cleared the cache of my browser.
- [X ] I have tried a different browser to see if it is related to my browser.

## The problem

After updating to 0.117 themes that are applied to specific panels are not properly applied. Specifying the same theme in the user settings works but then applies to all panels.

## Expected behavior
Prior to this update each panel could have its own individual theme as specified in the UI..

## Steps to reproduce

1. In the Lovelace UI, select a theme for a panel. In my case it was one of the ios-dark-mode-themes from basnijholt. Also saw the failure with JuanMTech/google_dark_theme.
2. Observe that the theme does not affect the current panel.
3. Set the same theme for the user in user settings
4. Observe that now all panels display as expected with that theme.

## Environment

- Home Assistant release with the issue: 117.1
- Last working Home Assistant release (if known): 116.4
- Browser and browser version: Chrome (Version 86.0.4240.111 (Official Build) (64-bit)
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by chrisbl01** [comment]
not working in 0.118.3 either
