### ISSUE TITLE
Translation Error: intl.PluralRules is not available in this environment (iOS 12.4.8 - App and Safari - Italian)

### ISSUE THREAD

**Issue by martymarty004** [home-assistant/frontend#7551]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
After updating to 0.117.0/.1 there are translation error on the iOS app and Safari, but only on my iPhone 6 (iOS 12.4.8).
The errors appear where there should be words that can have a singular and plural form based on the number following them.
Safari and the app are set to Italian.
The issue is not present on other (newer) devices.

## Steps to reproduce
1. Open the app with a "legacy" Apple iPhone 
2. Use Italian language
3. Look for places where plural rules are needed

## Environment

- Home Assistant release with the issue: 0.117.1
- Last working Home Assistant release (if known): 0.116.4
- Browser and browser version: Safari 12.1 - Home Assistant Companion 2020.7 (11)
- Operating system: iOS 12.4.8

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt
Translation Error: intl.PluralRules is not available in this environment. Try polyfilling it using "@formatjs/intl-pluralrules"
```

**Comment by davidrustingha** [comment]
Same bug here. Seems only visible on iOS, windows and android look fine.

**Comment by martymarty004** [comment]
> Same bug here. Seems only visible on iOS, windows and android look fine.
> 
> Edit: My language is set to English and Dutch. And the bug is also visible in the companion app

Are you also on an older iOS version?

**Comment by davidrustingha** [comment]
> > Same bug here. Seems only visible on iOS, windows and android look fine.
> 
> > 
> 
> > Edit: My language is set to English and Dutch. And the bug is also visible in the companion app
> 
> 
> 
> Are you also on an older iOS version?

Yes: iOS 12.4.8, iPhone S6

**Comment by martymarty004** [comment]
> Yes: iOS 12.4.8, iPhone S6

Maybe they forgot about us

**Comment by Rendeik** [comment]
Also with macOS Sierra, Safari Version 12.1.2 (12607.3.10) and updated java 8 to version 271.

**Comment by martymarty004** [comment]
It seems that Safari 12.1 is the problem here

**Comment by davidrustingha** [comment]
> It seems that Safari 12.1 is the problem here

I don’t think so. I have the same error on the latest Chrome version...

**Comment by mnoorenberghe** [comment]
Chrome on iOS isn’t allowed to use their own Blink engine due to Apple’s AppStore rules so it’s just a front end on top of Safari. 

I’m also affected by this on an iPhone 6.

**Comment by davidrustingha** [comment]
> Chrome on iOS isn’t allowed to use their own Blink engine due to Apple’s AppStore rules so it’s just a front end on top of Safari. 
> 
> I’m also affected by this on an iPhone 6.

Wow, I never knew. Thanks!

**Comment by AndyZaa** [comment]
Yes, same here - iPhone 6, iOS 12.4.8. In my case I see it on my Persons and all device trackers. My wife's phone is an iPhone 2020 SE, iOS 13.7 and is not displaying it.

**Comment by martymarty004** [comment]
It has already been fixed. We just need to wait for the next release to be dropped.

**Comment by mnoorenberghe** [comment]
How do we flag this for the next patch release? There already was one since this was fixed.

**Comment by martymarty004** [comment]
They have to release the new frontend version which will be included in the next HA update
