### ISSUE TITLE
Please allow the details/history split referenced here be an option

### ISSUE THREAD

**Issue by ltjessem** [home-assistant/frontend#7554]
Couldn't we have an option to enable/disable this per domain or entity so people have the choice? 

_Originally posted by @zsarnett in https://github.com/home-assistant/frontend/pull/6936#issuecomment-719588501_

**Comment by zsarnett** [comment]
This is not a place for Feature Request anymore. Feature Requests are created in https://github.com/home-assistant/frontend/discussions

But I can answer that question with: no.

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/discussions/7515
