### ISSUE TITLE
Server Control and Check Config not work

### ISSUE THREAD

**Issue by ahmetem** [home-assistant/frontend#7565]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
With the new version(0.117.x), the settings / server controls page started to open halfway.
The page is not fully loaded.
Check Config button dont work.
The problem disappears when I go back to the old version.

## Steps to reproduce

1.Setting tap
2. Server controls page
## Environment

- Home Assistant release with the issue: 0.117.1
- Last working Home Assistant release (if known):0.116.4
- Browser and browser version:Google Chrome 86.0.4240.111 
- Operating system: VirtualBox

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
Did you check your browser console/inspector? Are there any errors logged there?

Also please provide some more details and screenshots:
- "The page is not fully loaded." => So what is loaded? What can you see?
- "Check Config button dont work." => What happens? Just no reaction?

**Comment by ahmetem** [comment]
"The page is not fully loaded." => So what is loaded? What can you see?

![Adsız](https://user-images.githubusercontent.com/26777241/97900829-4ce92580-1d4c-11eb-9677-74a6c068578d.jpg)

"Check Config button dont work." => What happens? Just no reaction?

No reaction.
i added server_kontrol page html source



[server_kontrol.docx](https://github.com/home-assistant/frontend/files/5476964/server_kontrol.docx)

**Comment by ahmetem** [comment]
i upgraded 0.118 .the problem still persists.  Before 0.117, this problem did not exist.
the page is still incomplete loading.

**Comment by ahmetem** [comment]
i found this error .
Uncaught (in promise) SyntaxError: Expected "," but "a" found.
    at Ze (app.c5d13434.js:10291)
    at _ (app.c5d13434.js:10291)
    at Function.A [as __parse] (app.c5d13434.js:10291)
    at new e (app.c5d13434.js:10291)
    at Object.localize (app.c5d13434.js:10291)
    at chunk.9a7682c192ec830d0c49.js:841
    at Array.map (<anonymous>)
    at HTMLElement.value (chunk.9a7682c192ec830d0c49.js:836)
    at HTMLElement.update (app.c5d13434.js:10291)
    at HTMLElement.performUpdate (app.c5d13434.js:10291)

**Comment by ahmetem** [comment]
when i change language turkish to english .problem solved.

**Comment by bramkragten** [comment]
Could you fix this localization bug for us for your language? <https://developers.home-assistant.io/docs/translations>

**Comment by ahmetem** [comment]
> Could you fix this localization bug for us for your language? https://developers.home-assistant.io/docs/translations

yes.i fixed for my language. Whenever new language  updates are activated the problem will be fixed.

**Comment by ahmetem** [comment]
today the new version (0.118.3) has arrived. but I guess the language files are not updated. How often are language files added to the new version?

**Comment by bramkragten** [comment]
Every major release
