### ISSUE TITLE
Additional info box not aligned properly 

### ISSUE THREAD

**Issue by mf-social** [home-assistant/frontend#7568]
## Checklist
- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem
Opening the more info box for an entity, the box is now offset upwards and to the right. 

## Expected behavior 
The box appear correctly aligned. 

## Steps to reproduce

Open states list... 

![Screenshot_20201101-093800](https://user-images.githubusercontent.com/14824890/97799505-917aa100-1c26-11eb-9ef8-fffdffeebc41.png)

Tap the little 'i' icon for an entity... 

![Screenshot_20201101-093815](https://user-images.githubusercontent.com/14824890/97799517-a48d7100-1c26-11eb-826f-db83690abfcd.png)

Note that the new window is offset. 

Guessing here, but... 

The 'upwards' offset appears to be trying to align with the the old 'title' that used to sit above the header before the header was compacted. 'Sideways' offset appears to be the width that the sidebar would be when contracted. 

## Environment
- Home Assistant release with the issue: 0.117.x
- Last working Home Assistant release (if known): 0.116.x
- Browser and browser version: Homeassistant app for android, and chrome on android. 
- Operating system: Android for the browsers, HA supervised on docker, in debian, in proxmox for homeassistant. 

## Additional information
Apologies if this has already been reported but I couldn't see anything obvious

**Comment by mf-social** [comment]
Regarding the checklist item "I have tried a different browser to see if it is related to my browser.", this isn't an issue on desktop browsers because it appears as a smaller popup there, and I don't have any ios devices available to me currently to test with.

**Comment by spacegaier** [comment]
I cannot reproduce the issue, neither in Chrome nor in the HA Android app. In both instances, I get a popup that takes up the whole screen.

Can you please check again, if you still experience the issue?

**Comment by mf-social** [comment]
Yeah it's been fine for ages, I reported this 4 months ago, don't know why it wasn't closed when it was fixed. Only just found out it was still open when you replied.
