### ISSUE TITLE
Thermostat card displaying status in the wrong place

### ISSUE THREAD

**Issue by b4dpxl** [home-assistant/frontend#7570]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I have just updated to 0.117.1. Now the thermostat card is showing the status to the side of the temperature, cut off, instead of underneath, and the target temperature is no longer visible.

![image](https://user-images.githubusercontent.com/26406101/97804364-44f38d80-1c47-11eb-85a8-51d00328c77e.png)

![image](https://user-images.githubusercontent.com/26406101/97804367-4fae2280-1c47-11eb-8cd0-4e5f8cbf81f6.png)

## Expected behavior

State and target temperature visible underneath current temperature, as before.

## Steps to reproduce

1. Update to 0.117.1. 
2. Add a "thermostat" card

## Environment

- Home Assistant release with the issue: 0.117.1
- Last working Home Assistant release (if known): 0.116
- Browser and browser version: Chrome and Edge latest, plus iOS Companion
- Operating system: Windows 10 and iOS 14.0.1

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
I can't reproduce that on my end. Everything looks fine.

Is your card inside some other elements, such as stacks? Is the target temperature element just not visible (e.g. black color) or in a completely wrong position outside of your screenshot?

**Comment by b4dpxl** [comment]
I tried it in a brand new dashboard, so no stacks. It’s the right colour, hence you can see the “le” in “idle”. It’s just moved to the left instead of underneath. I also tried different themes.

**Comment by spacegaier** [comment]
Yes, you can see part of the state, but nothing of the target temperature, hence my question.

**Comment by b4dpxl** [comment]
it's just above. I can see it in the dev console. 

Here's the code from the console in a 0.116 dev version:

![image](https://user-images.githubusercontent.com/26406101/97806500-c81ae080-1c53-11eb-9e2d-cb045ce9020f.png)

And here's the 0.117.1 version:

![image](https://user-images.githubusercontent.com/26406101/97806506-d0731b80-1c53-11eb-9033-2d1e3d54f38b.png)

The new version is missing the `viewbox`, `width`, and `height`. Adding them manually via the console restores the elements to the correct location.

**Comment by b4dpxl** [comment]
Looks like it might have been a rogue module interfering. Removed some old references to unused modules (which I though I'd already removed) and it looks to be fixed.
