### ISSUE TITLE
QR code generation does not match expected tag URL format for companion apps

### ISSUE THREAD

**Issue by dshokouhi** [home-assistant/frontend#7576]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When tag scanning and creating was added to the android app there was some discussion about the URL format for the companion apps to follow: https://github.com/home-assistant/android/pull/689#discussion_r465464512

So the apps are expecting the URL to contain `www` when being scanned.  We should make sure to update the format accordingly, a user on Discord pointed out: https://github.com/home-assistant/frontend/blob/426a7ac8ddcfb703175149280ac5eda2683d675b/src/panels/config/tags/dialog-tag-detail.ts#L234

Ref: https://discord.com/channels/330944238910963714/562408603345092636/772621412023664640

## Expected behavior

the QR code format should match the decision made for the companion apps: https://github.com/home-assistant/android/pull/689#discussion_r465464512

## Steps to reproduce

1. Configuration > Tags
2. Create QR tag
3. Scan with android app

## Environment

- Home Assistant release with the issue: 0.117.x
- Last working Home Assistant release (if known): N/A 
- Browser and browser version: chrome 86
- Operating system: windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by frederickjh** [comment]
Wow, This community is fast. Last night I am too tired to write the bug report before bed. This morning The bug report is filed and a pull request to fix it is already to be committed to the repository!

Thanks @dshokouhi and @spacegaier for taking the initiative on this!

**Comment by frederickjh** [comment]
I will add this one comment that currently scanning the QRcodes generated by the Home Assistant frontend (in which the URL does not have the **www**) and then opening it with the Home Assistant Android Companion App does not work. If I generate the QRcode elsewhere with the **www** then scan it and open it it does work.

Here is a code generated with HA 0.117.1:
![image](https://user-images.githubusercontent.com/864159/97848538-83de1d80-1cf1-11eb-84cb-c2a43eb81a19.png)

And here is the link that it contains when it is scanned:
![image](https://user-images.githubusercontent.com/864159/97848636-a839fa00-1cf1-11eb-895b-b6271622e945.png)

Notice the missing **www**.

As @dshokouhi pointed out the Home Assistant Companion App is configured correctly to open links from `www.home-assintant.io`, with the **www**.
![image](https://user-images.githubusercontent.com/864159/97848894-0961cd80-1cf2-11eb-8dde-85bc68bd5159.png)
