### ISSUE TITLE
Strings occasionally appear un-localized

### ISSUE THREAD

**Issue by adamjernst** [home-assistant/frontend#7596]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Sometimes strings in the sidebar appear as developer string names instead of properly localized strings. Screenshot from Safari on Mac OS X 10.15:

<img width="278" alt="Screen Shot 2020-11-04 at 6 18 04 PM" src="https://user-images.githubusercontent.com/97944/98182054-6c0dc180-1eca-11eb-8dc1-9fe1ae3f0d7b.png">

## Expected behavior

Strings should appear in the correct language.

## Steps to reproduce

Inconsistent repro. All that is required is to load the home page.

I have reproduced in both Chrome and Safari.

## Environment

- Home Assistant release with the issue: 20201021.4
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Safari 14.0
- Operating system: Mac OS X 10.15

## Javascript errors shown in your browser console/inspector

None. However I did track this down to a race condition in how localized strings are loaded. When the bug reproduces, the appropriate strings are *missing* from the Hass object:

```txt
>> document.body.children[0].__hass.resources.en
{
  component.alexa.title: "Amazon Alexa"
  ...
  ... NOTE: no panel.developer_tools string is present.
}
```

## Additional information

Pull request forthcoming.

**Comment by TomBrien** [comment]
Duplicate of #7512

**Comment by adamjernst** [comment]
Yup, duplicate.
