### ISSUE TITLE
Possible to create invisible user without associated person

### ISSUE THREAD

**Issue by travisp** [home-assistant/frontend#7615]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

When adding a person via the user interface, if you choose to allow the person to login, but then cancel at the last moment, the username will be created without the person. There is no way in the UI to remove this username. As a result, a user will be stuck with a username unless they know how to edit the files in `.stoage`

## Expected behavior

Username should not be created if the person is not created OR the UI should allow deleting the username separately.

## Steps to reproduce

1. Click Configuration in the sidebar
2. Click People
3. Click the + button
4. Fill in a name
5. Choose "Allow person to login"
6. Enter a Name, Username, and Password. Click Create
7. Cancel adding the new person

## Environment

- Home Assistant release with the issue: 0.117.5
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ludeeus** [comment]
Enable advanced mode in your profile and you get the option to edit users
