### ISSUE TITLE
Zone Editor

### ISSUE THREAD

**Issue by cortexgaming101** [home-assistant/frontend#7616]
Would be super cool if we could double-click on the zone editor and create a new zone that way. Also if we could enter an address in and get the lat & long automatically. Not all zones are at my house when creating them 😐 some are really far away in other states and would be super nice to just double-click on the map to populate an entire town.

**Comment by zsarnett** [comment]
If you want to submit a Feature Request please follow the directions and use Discussions

**Comment by cortexgaming101** [comment]
The feature request page took me here. Sorry about that

**Comment by zsarnett** [comment]
Like in Github?

**Comment by zsarnett** [comment]
It takes me to discussions
