### ISSUE TITLE
System Health broken since introduction of streaming

### ISSUE THREAD

**Issue by spacegaier** [home-assistant/frontend#7638]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

No information shown in the card. Endless progress loop icon:

![grafik](https://user-images.githubusercontent.com/114137/98609928-c0f87000-22ee-11eb-9e60-e789b55be725.png)

## Expected behavior

Data to be displayed.

## Environment

Latest frontend and core dev versions.

- Home Assistant release with the issue: 0.118.0 dev
- Last working Home Assistant release (if known):
- Browser and browser version: FF and Chrome
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

Nothing suspicious in the backend log. No errors in console or network logs.

**Comment by frenck** [comment]
The backend isn't merged yet?

<https://github.com/home-assistant/core/pull/42831>

**Comment by spacegaier** [comment]
Right, backend is still missing. Since the frontend PR has been merged I assumed the backend was ready as well 😄.
