### ISSUE TITLE
Configuration, Server Controls, YAML configuration reloading the option to reload Groups, Group Entities and Notify Services is centered text instead of left aligned

### ISSUE THREAD

**Issue by jes1417** [home-assistant/frontend#7639]
## Checklist

- [:ballot_box_with_check: ] I have updated to the latest available Home Assistant version.
- [:ballot_box_with_check: ] I have cleared the cache of my browser.
- [:ballot_box_with_check: ] I have tried a different browser to see if it is related to my browser.

## The problem

minor issue, in :gear: Configuration, Server Controls, YAML configuration reloading the option to reload Groups, Group Entities and Notify Services is centered text instead of left aligned like the rest of the options. This only happens to show up on mobile devices.

![image](https://user-images.githubusercontent.com/38092747/98626656-cdbd9980-22d7-11eb-8bc9-2139e48f22d7.png)

## Expected behavior
all options left aligned.
![image](https://user-images.githubusercontent.com/38092747/98626773-0cebea80-22d8-11eb-8bd4-629549eacfaf.png)

## Steps to reproduce

open :gear: Configuration, Server Controls, YAML configuration reloading on mobile device
## Environment

```
arch | x86_64
-- | --
dev | false
docker | true
hassio | false
installation_type | Home Assistant Container
os_name | Linux
os_version | 4.19.0-0.bpo.9-amd64
python_version | 3.8.6
timezone | America/Chicago
version | 0.117.5
virtualenv | false
```

- Home Assistant release with the issue: 0.117.5
- Last working Home Assistant release (if known): many releases before this
- Browser and browser version: Google Chrome Version 86.0.4240.183 (Official Build) (64-bit)
- Operating system: All of them

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```n/a

```

## Javascript errors shown in your browser console/inspector

```n/a

```

**Comment by kukulich** [comment]
It appears when the text cannot fit in one line.

**Comment by spacegaier** [comment]
It is not specific to the mobile app. The same happens in desktop Firefox (in Chrome you can enforce it by making a few element smaller, but by default the minimum size will prevent the wrapping for me).

Once https://github.com/home-assistant/frontend/pull/6730 has been merged all buttons will be centered anyway and the problem disappears.

**Comment by bieniu** [comment]
The issue still exists.

**Comment by bieniu** [comment]
The issue still exists for "Reload rest entities and notify services".

**Comment by jes1417** [comment]
This has been fixed on my end in the HA app![Screenshot_20210805-233510.png](https://user-images.githubusercontent.com/38092747/128456533-e6a3345b-0bd2-4359-ac4f-b7cf863a5229.png)
