### ISSUE TITLE
Foldable sidebar

### ISSUE THREAD

**Issue by JGNi** [home-assistant/frontend#7658]
With the ever growing addons there keeps coming in HA, a foldable sidemenu is really necessary 
Sorted either by tags or drag-and-drop.

**Comment by frenck** [comment]
Re-ordering / organizing the side menu is already possible.

**Comment by JGNi** [comment]
> Re-ordering / organizing the side menu is already possible.

I must have missed that. Can you link to how it's done then?

**Comment by JGNi** [comment]
And not only re-ordering/organizing, but foldable....

**Comment by spacegaier** [comment]
> 
> 
> > Re-ordering / organizing the side menu is already possible.
> 
> I must have missed that. Can you link to how it's done then?

From your user profile => "Change the order and hide items from the sidebar" => "Edit"

You can also press and hold the header of the sidebar to activate edit mode.

**Comment by iantrich** [comment]
When you say "foldable" are you talking about nested sections under a label?

**Comment by JGNi** [comment]
> When you say "foldable" are you talking about nested sections under a label?

Yes. That's what I mean

/JGNi

**Comment by iantrich** [comment]
I don't see a need to add such complexity to our base. Can you better explain the use case you are trying to solve?
