### ISSUE TITLE
device_trackers show 'incorrect' state in logbook

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#7667]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

checking device_trackers in logbook they show 

'was away' when changing to `not_home` and
'was at home' when changing to `home`

this is somewhat confusing. and downright incorrect of course, because 'was at home' means 'is not at home' and 'was away' means 'is not away'.....

<img width="776" alt="Schermafbeelding 2020-11-12 om 16 05 38" src="https://user-images.githubusercontent.com/33354141/98957159-2b80fa00-2501-11eb-9668-a0ec22824f27.png">

## Expected behavior

might be better to change the wording here to

changed to away (not_home) and
changed to (at) home

if the optimal 

went away ( or 'left home') and 
arrived at home

would be too much to ask.

## Environment

- Home Assistant release with the issue: 118.0b0
- Last working Home Assistant release (if known): not sure
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
 this seems to be generic behavior for device_trackers, so no further info provided

**Comment by spacegaier** [comment]
Thought about that a bit, and I am leaning towards "was detected at home" and "was detected away".

Reasoning:
1. The logbook is a log of past events and not a current state representation, so we are listing past state changes => past tense makes more sense.
2. This passive past tense wording also works nicely with the "by XXX" attribution of the state changes.

**Comment by Mariusthvdb** [comment]
why not say 'arrived at home' / 'left home' which seems both correct and grammatically best?

**Comment by spacegaier** [comment]
Because it breaks the scenarios where we have information "who" detected the change:

"Marius arrived at home by Detector Hallway" whereas "Marius was detected at home by Detector Hallway" works.

**Comment by Mariusthvdb** [comment]
ok fair enough ;-), that's much better indeed.
thanks, this would be very nice.

though, right now, there's no 'by any detector at all'  yet. Should there be already? I mean its my nmap, or life360 device_trackers detecting me....

**Comment by spacegaier** [comment]
I have seen it one or twice for the zones in my log, but that might have been manual test data (don't remember).

In general this "by XXX" does exist (could either be a username or a service/automation). In general: If the state change does contain this info, it will be shown.
