### ISSUE TITLE
Addon disappears when resizing the browser window

### ISSUE THREAD

**Issue by fabsenet** [home-assistant/frontend#7668]
https://github.com/hassio-addons/addon-node-red/issues/754 send me here :-)

![bugreport](https://user-images.githubusercontent.com/2065705/98961800-443fde80-2506-11eb-8167-acfcd8a85499.gif)

The gif is on firefox developer edition 83.0b10 (64-Bit)
I also veriefied the issue on chrome Version 86.0.4240.198 (Offizieller Build) (64-Bit) and on edge Version 86.0.622.63 (Offizielles Build) (64-Bit)

My expectation would be to not loosing access to the addon part of the window. it is also very frustrating because you can loose not deployed changes that way!

I verified the issue with node-red and vscode, other sidebar icons work.

also all other versions:
HassOS 4.16
Supervisor 2020.11.0
Browsers were running on Windows 10, Version 2004, Build 19041.610

@sinclairpaul said:

> Only appears to happen when using the "Show in Sidebar" option, and only when the Sidebar is collapsed.

**Comment by JOHLC** [comment]
Same here also happens with file editor

**Comment by fabsenet** [comment]
Issue is still there!

The page gets no longer completely black but it switches to the addonslist on its own!

**Comment by fabsenet** [comment]
current situation:
![bugreport](https://user-images.githubusercontent.com/2065705/108168332-6cd40780-70f7-11eb-8c68-42f5e58022dc.gif)
My versions:
core-2021.2.3
supervisor-2021.02.9

HACS
Integrations Version: | 1.11.3
-- | --
Frontend Version: | 20210214110032
Repositories: | 747
Installierte Repositories: | 6



_just in case I have to do it again, the command for the gif generation I used was:_
```powershell
ffmpeg -i .\bugreport.mp4 -filter_complex 'scale=800:-1:flags=lanczos,split [o1] [o2];[o1] palettegen [p]; [o2] fifo [o3];[o3] [p] paletteuse' bugreport.gif
```
