### ISSUE TITLE
History Graph doesn't scale properly and get horizontal scroll bar when Windows 10 has font size increased 

### ISSUE THREAD

**Issue by haabe** [home-assistant/frontend#7679]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

When I set the font size OR the scaling of Windows 10 to something larger than 100 %, say 150 %, the History Graph card gets a horizontal scroll bar on both Edge and Chrome.

![History Graph Card](https://user-images.githubusercontent.com/2988921/99118433-cd830e00-25f7-11eb-8e10-5b6d382612ac.png)
![Windows 10 settings](https://user-images.githubusercontent.com/2988921/99118441-d1169500-25f7-11eb-9a4c-762971060493.png)

## Expected behavior

I expect the History Graph Card to scale just as nicely as any other card without adding the horizontal scroll bar.

## Steps to reproduce
    1. Add a History Graph Card to your lovelace
    2. Open Display Settings on your Windows 10 computer
    3. Enlarge scale and apply
    4. Open HA in your browser

 
## Environment

arch | x86_64
-- | --
dev | false
docker | false
hassio | false
installation_type | Home Assistant Core
os_name | Linux
os_version | 4.15.0-123-generic
python_version | 3.8.6
timezone | Europe/Oslo
version | 0.117.6
virtualenv | true

- Home Assistant release with the issue: 0.117.6
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome 86.0.4240.198 / Edge 86.0.622.68
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
Setting overflow to hidden on the chartTarget ID is a quickfix:
`#chartTarget { overflow: hidden; }`

**Comment by tomaszpieczykolan** [comment]
I have a simmilar issue, except in my case vertical scroll bars are visible. I'm using 150% scaling. The issue goes away on 100% or 125% scaling.

Here's an example:

![image](https://user-images.githubusercontent.com/14042416/103417359-b8a01100-4b8a-11eb-8adc-c1c84f7ac9a4.png)

**Comment by maximilianriemensberger** [comment]
I see the same problem with both vertical and horizontal scroll bars. Depending on card configuration either one of them or both.  Setting `overflow: hidden` fixes it for me.

**Comment by lucidyan** [comment]
Similar issue, except I have both vertical and horizontal bars. The annoying horizontal goes away on values <= 90% and 110% scaling. I think it temporarily can be fixed with stylish extension and @maximilianriemensberger propose.
<img src="https://user-images.githubusercontent.com/5789108/111666871-30deb000-8825-11eb-885e-9bd767fcea1b.png" width="50%" height="50%">

**Comment by m4dm4xi** [comment]
Where does one apply the "overflow: hidden" fix?

This is the problem:
![image](https://user-images.githubusercontent.com/42769944/116814807-df7f4b80-ab5a-11eb-83e7-c4f42e76beb1.png)

This does not help:
![image](https://user-images.githubusercontent.com/42769944/116814855-0fc6ea00-ab5b-11eb-88a2-ea9220cc81c7.png)

**Comment by maximilianriemensberger** [comment]
@m4dm4xi I just figured out the problem using chrome's debugging tools.  I didn't really find a place to fix it so far. Still looking for a simple way to do so.  I guess the card-mod plugin could be used. But I haven't tried it out.

**Comment by maximilianriemensberger** [comment]
This seems to be the problematic piece of code:

https://github.com/home-assistant/frontend/blob/5d946778cb8ef3412c7d58e1f12ca29c25de35d2/src/components/state-history-chart-line.js#L67-L70

It's apparently a workaround for safari. But it causes nasty scrollbars in some cases on chrome.

Any body an idea what a proper fix would look like that addresses both cases?  Maybe @bramkragten who authored this workaround in https://github.com/home-assistant/frontend/pull/7025 ?
