### ISSUE TITLE
Calendar events show undefined in title/name

### ISSUE THREAD

**Issue by jawaite123** [home-assistant/frontend#7680]
## Checklist

- [X ] I have updated to the latest available Home Assistant version.
- [X ] I have cleared the cache of my browser.
- [X ] I have tried a different browser to see if it is related to my browser.

## The problem

The calendar tab shows events, but all have "undefined" as their title. The events are from iCloud calendars using the caldav platform.
![image](https://user-images.githubusercontent.com/1382932/99125028-4c188500-25d1-11eb-9090-93731cdeb3a2.png)

## Expected behavior

I expect that the event title, i.e. Lunch with Brian, would show in the calendar

## Steps to reproduce

1. add caldav calendar to configuration.yaml
2. Navigate to the Calendar tab in Lovelace

## Environment
```txt
arch | x86_64
chassis | desktop
dev | false
docker | true
docker_version | 19.03.13
hassio | true
host_os | Debian GNU/Linux 10 (buster)
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 4.19.0-12-amd64
python_version | 3.8.6
supervisor | 2020.11.0
timezone | America/New_York
version | 0.117.6
virtualenv | false

```

- Home Assistant release with the issue: Ever since calendar tab appeared in Lovelave
- Last working Home Assistant release (if known): None
- Browser and browser version: Chrome Version 86.0.4240.193
- Operating system: HASS runs on Debian 10 | Client is Windows 10

## Problem-relevant configuration

```yaml
calendar:
  - platform: caldav
    username: "xxx@xx.com"
    password: "xxx"
    url: "https://xxx.icloud.com/"
    calendars:
      - 'Family' 

```

**Comment by asystentka-jolka** [comment]
I noticed similar problem with google calendars but it was not a bug in HA but this came from calendars settings.
Event details were hidden by default in google calendars settings, only free/busy info was returned.
After changing settings like on this picture below it works OK

 ![image](https://user-images.githubusercontent.com/43966761/101239544-7ea53180-36e8-11eb-92f8-21043a3c8ed3.png)
