### ISSUE TITLE
Automation UI not displaying selected  input_datetime entry  

### ISSUE THREAD

**Issue by olivier1091** [home-assistant/frontend#7686]
## Checklist

- [yes ] I have updated to the latest available Home Assistant version.
- [yes ] I have cleared the cache of my browser.
- [ yes] I have tried a different browser to see if it is related to my browser.

## The problem
Automation UI not displaying selected input_datetime entry.
When creating a time based trigger using a an entry value, the selected entry is not displayed anymore by the UI next time you open the automation.
If I switch to YAML view, I can see the selected value. 
platform: time
at: input_datetime.date_retour_vacances    

## Expected behavior
The selected value is displayed when I go back in the automation like we can see in any other part of the automation UI  

## Steps to reproduce

Create an : input_datetime entry
Create a new automation
Chose a Triger “platform: time”
Check the box entry value date/time
Use the drop down list to select the entry you have just created
Add an action 
Save the automation
Go back to automation list
Open the automation you have just created
The “at” field is empty 
But if you switch to yaml, you couls see ta hen entry is selected.   

## Environment

arch | armv7l
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.12
hassio | true
host_os | HassOS 4.16
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7l
python_version | 3.8.6
supervisor | 2020.11.0
timezone | Europe/Zurich
version | 0.117.6
virtualenv | false

- Home Assistant release with the issue:
0.117.6
- Last working Home Assistant release (if known):
- Browser and browser version:
Chrome Version 86.0.4240.198 (Build officiel) (64 bits)
Edge Version 86.0.622.68 (Version officielle) (64 bits)
- Operating system:
Windows 10
![Automation-UI-yaml](https://user-images.githubusercontent.com/45964368/99153027-1db8a980-26a6-11eb-97c7-7394e01df490.JPG)
![Automation-UI](https://user-images.githubusercontent.com/45964368/99153028-1e514000-26a6-11eb-8a39-dd500ffff2ce.JPG)

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by olivier1091** [comment]
By the way, Sorry for my English, and thanks a lot to all for your impressive development works on HA

**Comment by spacegaier** [comment]
Issue confirmed and reproduced. PR to fix created.
