### ISSUE TITLE
Home Assistant Snapshot To Include Wifi Setup

### ISSUE THREAD

**Issue by jaredBevis** [home-assistant/frontend#7701]
I recently restored a snapshot created with HassOS 4.16 and Supervisor 2020.11.0 running on an RPi4 using the system image provided by HA community.  When I went to wipeout and restore this snapshot, the WiFi credentials did not restore.  I had to manually setup and enter the WiFi credentials for my home network over a physical ethernet connection.  Would be great to include the wpa_supplicant file or whatever HA uses to store WiFi creds in the snapshot.

**Comment by frenck** [comment]
This is not a frontend issue, but a feature request for our Supervisor.
Feature requests for our Supervisor are tracked in the forum:

<https://community.home-assistant.io/c/feature-requests/13>

Thanks!
