### ISSUE TITLE
Grid + media-player does not display correctly

### ISSUE THREAD

**Issue by pixeye33** [home-assistant/frontend#7706]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

A media-player card inside a square grid card does not display correctly.
I was hopping that using the grid + media-player combo that i would get a beautifull art display.

![image](https://user-images.githubusercontent.com/1382471/99300742-46c76e80-284d-11eb-966e-885f9446802a.png)

Title and Singer only shows one letter.
The progress bar and controls are in the middle.

## Expected behavior

I would expect the metadata to be displayed fully.
The progress bar and controls should be alligned to the bottom

Something like this ?

![image](https://user-images.githubusercontent.com/1382471/99301744-b12cde80-284e-11eb-8ca3-5deb9f1aed0a.png)

## Steps to reproduce

Here is the config i have :

```
type: grid
columns: 1
cards:
  - type: media-control
    entity: media_player.spotify
```

## Environment

- Home Assistant release with the issue: 0.118.0b2
- Last working Home Assistant release (if known): new feature
- Browser and browser version: Version 86.0.4240.198 (Build officiel) (64 bits)
- Operating system: Windows (client) Docker (server)

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
I can reproduce the issue. I have a local fix that would solve the media title issue, but would make it always use the whole width of the card, even when smaller whereas previously the title never went on top of the album cover. Not sure if that is a good solution.

![image](https://user-images.githubusercontent.com/114137/99430245-60c68700-2909-11eb-91e7-29d4dc6cdec9.png)

![image](https://user-images.githubusercontent.com/114137/99430366-86ec2700-2909-11eb-8ee3-e52640bef833.png)

**Comment by zsarnett** [comment]
We need to have an overall discussion about how our cards should work. THis isn't just affecting the media card

**Comment by bramkragten** [comment]
Fixed by https://github.com/home-assistant/frontend/pull/7727
