### ISSUE TITLE
Group discovered Shelly devices

### ISSUE THREAD

**Issue by michalk-k** [home-assistant/frontend#7707]
## Environment

- Home Assistant Core release with the issue: 0.117.6
- Last working Home Assistant Core release (if known): N/A
- Operating environment (OS/Container/Supervised/Core): N/A
- Integration causing this issue: Shelly
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information

Current version of built-in Shelly integration uses zero conf to discover new devices in the network (as I was adviced on forum).

Every single device is shown as one card. With 100 devices in network it means 100 cards on Integration screen.

There are integrations which uses single card to show number of devices. I believe the Shelly integration could group all its devices into single Integration card

There are other methods to cope with this situation:

1. Adding shelly configuration (yaml or gui) disabling discovering new features. HomeKit integration allows something simar.

2. providing "hide all new devices" similarily to how HACS does that. It could be potencially usefull for other/future integrations. But probably should be issues separatellt.

Any of those approaches would definitively help with flooding Integration page with Shelly cards, which is annoying for users who preffers mqtt.

**Comment by balloob** [comment]
I don't think it's a big issue that we should spend much time on. It's not like people add new devices on a day to day basis. Seems excessive to add a feature that needs a UI and to be maintained for a one-time minor nuisance for users to press a couple of ignore buttons.

**Comment by michalk-k** [comment]
Please consider the most comfortable way for you to implement it.
Maybe it's not big issue but IMO makes harm to overall HA image.
Let's screenshot say thousands words:
![obrazek](https://user-images.githubusercontent.com/7868445/99380415-373a3b00-28ca-11eb-8dc2-66b4ce88507d.png)

If user is flooded with such screen having to click 200 times for 100 entities... it's not something negligible.

As mentioned already a lot of integrations has the requested feature from the scratch. For example:
![obrazek](https://user-images.githubusercontent.com/7868445/99380842-c6dfe980-28ca-11eb-81aa-1aabf6e7abff.png)
Please consider GUI consistency as another argument for such feature

**Comment by bramkragten** [comment]
The reason shelly has a separate config entry for every device is that every device could have its own authentication.

**Comment by paravoid** [comment]
I have 83 Shelly devices on a network, which from what I gather isn't that uncommon (every light bulb and every light switch or two are a separate device - not entirely uncommon to e.g. Zigbee, Hue etc.). This is in fact about to expand by quite more devices later on. Right now, I'm using ShellyForHass, which just discovers them all in on sweep; I'd like to switch to the "official" integration.

Unless I'm missing something, the only way to configure these devices right now is to click "configure" in those configuration menus, manually, 83 times. Have I gotten this wrong? If not, then I'd consider this a very poor user experience, and thus a bug. Does that make sense?

**Comment by bramkragten** [comment]
This is the wrong place for that, please create an issue for the Shelly integration in the core repo.

**Comment by paravoid** [comment]
Are you sure? This task (which originally focused only on "hiding" rather than configuring, i.e. a subset of what I'm talking about) was originally filed on the core repo and then moved here by @balloob as a UI issue. Happy to do whatever you think is the most productive thing for everyone, though.

**Comment by bramkragten** [comment]
Configuring can never be a batch operation in the frontend+ your issue is about the fact that Shelly is using a separate config entry per device.

**Comment by michalk-k** [comment]
> The reason shelly has a separate config entry for every device is that every device could have its own authentication.

Is it really the argument?
Withings integration groups all devices into one UI element while allows to authenticate devices separately. And all those devices are grouped. It's all about programmer will to design UI properly.

BTW please do not transfer responsibility for the issue to reporter. It might be seen as excuse to not do the work.
A layer/component responsible for the issue is unknown area to the user. Also it may vary due to final solution as well as might change with system evolves. Also the UI change might require changes in backend. A user is not able to handle that. 
Since you closed this issue with, I believe you are confident about which team should deliver requested improvement. Then please do your best to make it happen.
