### ISSUE TITLE
HTTP requests not being redirected to HTTPS after switching to SSL

### ISSUE THREAD

**Issue by Sloth-on-meth** [home-assistant/frontend#7711]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem

i enabled SSL and now all my old bookmarks  etc get a ERR_EMPTY_RESPONSE

## Expected behavior

  Redirect HTTP requests to HTTPS

## Steps to reproduce

 open a ssl-enabled home-assistant instance through HTTP, not HTTPS

## Environment

  Docker

- Home Assistant release with the issue: latest
- Last working Home Assistant release (if known): n/a
- Browser and browser version: n/a
- Operating system: n/a

## State of relevant entities

  N/A

```yaml

```

## Problem-relevant configuration

 N/A

```yaml

```

## Javascript errors shown in your browser console/inspector

  ERR_EMPTY_RESPONSE

```txt

```

**Comment by frenck** [comment]
This is not a bug. Home Assistant runs either SSL or non-SSL, not both.

If you are looking for such a feature, you can achieve that by adding a reverse proxy to your setup. If you run a Supervisor enabled system, the NGINX Proxy add-on can help with that.

**Comment by Sloth-on-meth** [comment]
not sure i understand. supervised? im running in docker. it's weird that literally every site i know of that uses SSL allows HTTP requests but directs them to HTTPS, can this be a QOL feature request instead then

**Comment by frenck** [comment]
I just gave an option that is available for Supervised based setups. For Docker-based setup, tons of options are available. NGINX Proxy, NGINX Proxy Manager, HAProxy, Traefik, and many more.

As for a suggestion or feature request, that is welcome; but please use our community forums for that:

<https://community.home-assistant.io/c/feature-requests/13>

**Comment by Sloth-on-meth** [comment]
Thanks frenck! I'll post on the forum. The nginx stuff never works for me, but thanks regardless 💯
