### ISSUE TITLE
Time string translation not working

### ISSUE THREAD

**Issue by acseven** [home-assistant/frontend#7713]
## The problem

In:
https://github.com/home-assistant/frontend/blob/8fd1f35c59b52ffd5e5a94499d5f9e3f2d3132be/translations/frontend/pt.json#L685

"relative_time" > "future" is not being displayed in any other language other than English on a localized UI.

(side note: the actual translation there isn't correct either, it should be `"future": "Dentro de {time}",` and not `"future": "Há {time}",`)

## Expected behavior

The localized string should be displayed.

## Steps to reproduce

In any situation where this is used, with Portuguese language (and likely any other than English)

## Environment

- Home Assistant release with the issue: Home Assistant 0.113.3
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

**Comment by spacegaier** [comment]
Can you please add a screenshot? Is everything in Portuguese and in between the <relative-time> is in English?

Reg. the actual translations: You can adjust those as explained here: https://developers.home-assistant.io/docs/translations/

**Comment by maxwroc** [comment]
I have the similar problem but with ui.components.relative_time.past (english).

![image](https://user-images.githubusercontent.com/8268674/99880510-acc84300-2c0b-11eb-83de-724c87695e11.png)

The translations seems to be present in the file so I don't get why it doesn't work:
https://github.com/home-assistant/frontend/commit/733244531ed2e123400b40bfaedec7aef803bbd7

For sure it was working some time ago as people started reporting the issue for my card recently.

I'm on HA v0.117.6

**Comment by maxwroc** [comment]
It looks like the correct version of translations is not where I was checking and I should look here:
https://github.com/home-assistant/frontend/blob/master/src/translations/en.json
Instead of here
https://github.com/home-assistant/frontend/blob/master/translations/frontend/en.json

And in the one which is used in the UI/cards doesn't have "past" and "future" options. The suggestion is to use past_duration/future_duration ones instead.

**Comment by spacegaier** [comment]
The translation keys `relative_time.past` and `relative_time.future` do no longer exist in HA, but the translations still carry them. Will be cleaned up in a few days so that the obsolete translations get removed.
