### ISSUE TITLE
Some entities dont rename when a device is renamed

### ISSUE THREAD

**Issue by fysmd** [home-assistant/frontend#7714]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
When renameing a device, associated entities do not all rename.final one in thescrenshot still displays old name. 
![image](https://user-images.githubusercontent.com/1367155/99424549-b7c46000-28f9-11eb-85fa-5708f0c2087c.png)

## Expected behavior
All entities rename together and all have the same base name.

## Steps to reproduce
Rename a device, answer positively when prompted to rename entity IDs.

## Environment

arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.12
hassio | true
host_os | HassOS 4.16
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.75
python_version | 3.8.6
supervisor | 2020.11.0
timezone | Europe/London
version | 0.117.6
virtualenv | false

MacOS 11.0.1 (Big Sur)
Chrome 86.0.4240.198
Safari 14.0.1

Both Chrome and Safari exhibit same behaviour.

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
I cannot reproduce this. Renaming works fine for all entities of my devices.

Does this issue appear only for specific devices or all?
