### ISSUE TITLE
HA Translation

### ISSUE THREAD

**Issue by flyerge** [home-assistant/frontend#7720]
Hello,
I've been using HA for over a year now, it's nice and useful. I checked on HA [frontend lokalise](https://lokalise.com/signup/3420425759f6d6d241f598.13594006/all/) project, unfortunately there is no translation for Georgian. 

> According IANA

```
Type: language
Subtag: ka
Description: Georgian
Added: 2005-10-16
Suppress-Script: Geor
```

```
English Name: Georgian
Native Name: Georgian
Aka: Kartuli
```

Me and couple of my friends are ready to translate frontend in my native Georgian language and later backend and etc. Is it possible create new localise for Georgian language? 

With best wishes,
Kakha (კახა კახიძე)

**Comment by bramkragten** [comment]
What is your username (email) on Lokalise so I can add you to the team for Georgian?

**Comment by flyerge** [comment]
> What is your username (email) on Lokalise so I can add you to the team for Georgian?

Hello, you can find me by kakhak@gmail.com (Kakha Kakhidze)

**Comment by flyerge** [comment]
Hi @bramkragten ,
A couple of my friends wants to join the translation into the Georgian lang. How can they get access to Lokalise? Can I add them to a team or project?
