### ISSUE TITLE
Dismiss last Notification

### ISSUE THREAD

**Issue by PierreScerri** [home-assistant/frontend#7723]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The 'Dismiss All' button in the Notification pane is a most welcome addition.  However, clicking 'Dismiss' on the last remaining notification will not automatically close the pane.
## Expected behavior

Notification pane should close when there are no notifications
## Steps to reproduce

    1. Open Notification pane
    2. Leave only 1 notification
    3. Click 'Dismiss'

## Environment

- Home Assistant release with the issue: 0.117.x
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Chrome, Safari, Companion app
- Operating system: MacOS, iOS

## State of relevant entities

N/A
```yaml

```

## Problem-relevant configuration

N/A
```yaml

```

## Javascript errors shown in your browser console/inspector

N/A
```txt

```

## Additional information
![Screenshot 2020-11-18 at 10 11 10](https://user-images.githubusercontent.com/34303331/99510704-ac1f7a80-2987-11eb-86b7-e5c620e1188e.png)
![Screenshot 2020-11-18 at 10 11 19](https://user-images.githubusercontent.com/34303331/99510728-b2adf200-2987-11eb-9d4f-5ea00064e9e4.png)

**Comment by spacegaier** [comment]
Good catch. Logic was already there, but had a small typo/bug.
