### ISSUE TITLE
'Effect' drop-down on light cards doesn't fit properly

### ISSUE THREAD

**Issue by brayStorm** [home-assistant/frontend#7736]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

On mobile app, the card takes up the whole screen, and the effect drop-down is rendered at the far bottom right. Similar on desktop (all browsers), requires scrolling both horizontally and vertically.

## Expected behavior

Might be better as a modal? 
![image](https://user-images.githubusercontent.com/20567279/99708924-6ac9c080-2a96-11eb-9b7a-b2d6d48c61fd.png)

## Steps to reproduce

Select the 'Effect' drop-down on any light card, or light group.

## Environment

- Home Assistant release with the issue: 0.118
- Last working Home Assistant release (if known): None
- Browser and browser version: Firefox (81.0.2 (64-bit)), Chrome (86.0.4240.75), Companion App 2020.7 (11)
- Operating system: Windows 10, iOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
Somewhat linked to this ticket: https://github.com/home-assistant/frontend/discussions/7379
Interestingly in the other screenshot the dropdown is wider.

**Comment by spacegaier** [comment]
With the move of the light effects before the color picker, this might improve the issue described in this ticket. However, I cannot reproduce the horizontal scrollbar it on my desktop dev instance.

**Comment by spacegaier** [comment]
Bot be gone!
