### ISSUE TITLE
Cannot set a default dashboard on the device unless administrator

### ISSUE THREAD

**Issue by K-RAD** [home-assistant/frontend#7742]
I've set a non-administrator user and created a dashboard for my girlfriend's iPhone, and I realized the default Overview comes up first and cannot be hidden. And I don't want that, since that shows everything and can be confusing. I realized that the only way to hide it was to make her an administrator, set the other dashboard as default, and then remove her as administrator. Which makes no sense to me

**Comment by zsarnett** [comment]
Please fill out the issue template.
