### ISSUE TITLE
Adding a History Graph card hangs browser

### ISSUE THREAD

**Issue by leeandy1** [home-assistant/frontend#7749]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When adding a new lovelace history graph card the browser hangs and becomes unresponsive if the default entity is deleted and the dropdown list used to select the required entity. If you add an additional entity to the card the drop down works fine and the fist entity can then be deleted without issue.

## Expected behavior

  You should be able to delete the existing entity and select one from the dropdown

## Steps to reproduce

    1. Edit Dashboard
    2. click add card
    3. click history graph
    4. click the x on the entity to remove the default entity (in my case sensor.date)
    5. click the down arrow to select a new entity
    6. browser hangs and waiting does not recover

## Environment

 Home assistant  0.118.1 running on a Pi4
Frontend version 20201111.2
HassOS 4.17
Installed add-ons:
AppDaemon 4 (0.3.1), File editor (5.2.0), Home Assistant Google Drive Backup (0.102.0), Samba share (9.3.0), Check Home Assistant configuration (3.6.0), Node-RED (7.2.10)

- Home Assistant release with the issue: 0.118.1
- Last working Home Assistant release (if known): 0.117
- Browser and browser version: Edge Version 88.0.702.0 (Official build) dev (64-bit)
- Operating system: Windows 10 Pro 2004 OS 19041.630

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
We need some more information, because I cannot reproduce the issue. Works fine for me in Firefox, Chrome and Edge.

Any errors in the browser log? Did you try adding the graph to a completely empty view to rule out any interference from other cards/stacks?

**Comment by leeandy1** [comment]
I have also tried on Chrome and adding the graph to an empty view

**Comment by spacegaier** [comment]
Okay, now with your extended problem description, I understand the issue: When you remove the initial entity, the preview renders a history card with all entities. Preparing that takes some time, hence the browser hangs. We should probably render an empty preview card if no entity is chosen.

**Comment by leeandy1** [comment]
Apologies this was my first reported issue (I'm new to github) and I did not format the initial post correctly so the information I entered above did not show.
