### ISSUE TITLE
MQTT Cover - Tilt Controls missing (upgrade to 118.1)

### ISSUE THREAD

**Issue by tommyjlong** [home-assistant/frontend#7750]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
The MQTT Cover has tilt controls to "open", "stop", and "close".  These show as angled arrow up, square, angled arrow down buttons.  In upgrading to 118.1 from 117, these buttons disappeared and not longer exist in both the developer Tools->cover.X info card, nor in Lovelace Entities card.  Everything else appears to be as expected, including the slider for the Tilt position.

## Environment
Python venv, yaml based Lovelace.

- Home Assistant release with the issue: 0.118.1
- Last working Home Assistant release (if known): 0.117.6
- Browser and browser version: Chrome and Safari
- Operating system: Windows and iOS 

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

No errors in javascript.  Have hard cleared cache multiple times.
Have changed to HA default theme to make sure there are no issues with it.
Hovering over the areas where the buttons should be does not provide any affect, in other words its not just the icons that are missing, but there are no controls either.
```txt

```

## Additional information
Using Inspect in Chrome, these buttons are in "horizontal layout" div class.  Within this are:
- `<ha-cover-controls hidden>`
- `<ha-cover-tilt-controls>` . It does contains the button/icons, but for some reason they are not showing on the browser.
![InfoCard](https://user-images.githubusercontent.com/35182132/99844752-8fc73d80-2b41-11eb-8493-0d277c91aa1a.jpg)
![TiltButtons](https://user-images.githubusercontent.com/35182132/99844270-d9fbef00-2b40-11eb-9931-efccdb67abd3.jpg)

**Comment by iantrich** [comment]
Bug in my conversion of this element I'm sure. @tommyjlong Can you get me the output from States for this entity?

**Comment by tommyjlong** [comment]
Thanks for taking a look.
I've done the States output before, but sorta forgotten how.
I did in the meantime goto Developer Tools->Templates and did a few things:

`{{states('cover.bonus_room_blinds_north_left')}}`  The results came back:
```
Result type: string
closed

None
```
Another one
 `{{states.cover.bonus_room_blinds_north_left}}`
```
<template TemplateState(<state cover.bonus_room_blinds_north_left=closed; current_tilt_position=0, friendly_name=Bonus Room Blinds North Left, supported_features=240 @ 2020-11-20T18:02:52.590183-05:00>)>
```
Finally I thought I would throw in 
`{{states.cover.bonus_room_blinds_north_left.attributes }}`
```
{'current_tilt_position': 0, 'friendly_name': 'Bonus Room Blinds North Left', 'supported_features': 240}
```

Is this what you're after?

**Comment by iantrich** [comment]
Thanks but no. It's just in Developer Tools > States. I really just need the `supported_features`

**Comment by tommyjlong** [comment]
Ah OK....its there in the list above: `'supported_features': 240`.  Same value showing in the Developer Tools->States.

**Comment by iantrich** [comment]
@tommyjlong found the bug and was a silly error on my part when I refactored the element. Sorry for any trouble, should be in the next point release.

**Comment by tommyjlong** [comment]
I see the fix is in the 0.118.4 milestone list, but did it actually make it into that release?  I just tried it and its still not working.

**Comment by iantrich** [comment]
It looks to be there. Try clearing your browser cache

**Comment by tommyjlong** [comment]
Have done the "Empty cache and hard reload" several times in Chrome.  Have resaved ui-lovelace.yaml to get the frontend refresh prompt and clicked on it to reload.  Have killed/restarted iOS app.  All cases, still not working.  Is there some way to check the actual code in my python venv to see if I actually got your update?

**Comment by tommyjlong** [comment]
I just upgraded to 0.118.5, and the problem still exists (I did the "Empty cache and hard reload" a few times).  What else can we do?

**Comment by tommyjlong** [comment]
Just upgraded to 2020.12.0...
The "tilt-open" and "tilt-close" arrows are back!!  

However the "stop" button is not there.  I do not have any yaml configured for "stop" which may explain why the button is not there, but as a comparison, the "stop" button was there in 0.117, again without any yaml configured for "stop".
