### ISSUE TITLE
Drop down list appears behind other elements

### ISSUE THREAD

**Issue by sp3cialck** [home-assistant/frontend#7774]
![Capturar](https://user-images.githubusercontent.com/49992692/99915660-47587d00-2d05-11eb-95ab-2c8d9d3227a0.JPG)

**Comment by lustefaniak** [comment]
This also happens in the Integrations view:

![Screenshot 2020-12-01 at 13 25 31](https://user-images.githubusercontent.com/177043/100740286-c0786400-33d8-11eb-80cd-229762a9a641.png)
