### ISSUE TITLE
HA darkmode, Hacs inital screen wrong color!

### ISSUE THREAD

**Issue by sp3cialck** [home-assistant/frontend#7775]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [x
![hacs](https://user-images.githubusercontent.com/49992692/99915788-0b71e780-2d06-11eb-9ec8-2ab1bfed5eef.JPG)
 ] I have tried a different browser to see if it is related to my browser.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by frenck** [comment]
Hi there!

Thanks for opening an issue. However, HACS is a third-party tool. Please report the issue with the HACS repository.

<https://github.com/hacs/frontend/issues>
