### ISSUE TITLE
Editing sidebar

### ISSUE THREAD

**Issue by rpbx** [home-assistant/frontend#7783]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When editing the sidebar, it will not allow you to remove more than one item at a time.

## Expected behavior

The item that gets removed should then move to the bottom with an option to add it back.

## Steps to reproduce

Long press on the sidebar, remove a tab.

## Environment

HassOS. Problem is with all browsers and with the app.

- Home Assistant release with the issue: 0.118.2
- Last working Home Assistant release (if known): 0.117.5
- Browser and browser version: Chrome, Firefox, Companion App
- Operating system:

**Comment by spacegaier** [comment]
I don't really get what the problem is. You can enter the edit mode and then click the cross icon for all items you want to have removed and then re-add them if required.

Not sure what you mean by "more than one item at a time" in this context.

**Comment by rpbx** [comment]
I just tested it with other systems and it is working as intended. I guess something is wrong with my instance and is not a frontend issue.
