### ISSUE TITLE
Grid Conditional Cards Still Taking Space and Flexible Heights

### ISSUE THREAD

**Issue by eximo84** [home-assistant/frontend#7788]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

1. Conditional Cards taking space

I have a conditional card which is still showing its place in the grid rather than hiding, this didnt happen when it was a horizontal stack as you can see in the below screenshot.  Top row is a grid and bottom is a horizontal stack.

![cond](https://user-images.githubusercontent.com/25502878/99973232-761f3380-2d97-11eb-9e40-d41f4fb9e4d1.png)

![cond-editmode](https://user-images.githubusercontent.com/25502878/99973250-7a4b5100-2d97-11eb-9c9a-474a15aead13.png)

2. Grid not flexible on height and leaving gaps, again compared to vertical and horizontal stacks.

![gap-problem](https://user-images.githubusercontent.com/25502878/99973418-a5ce3b80-2d97-11eb-8869-7aa56efc8fc9.png)

![gap-noproblem](https://user-images.githubusercontent.com/25502878/99973428-a961c280-2d97-11eb-8ae6-53ded3cb241a.png)

## Expected behavior

See above screen shots comparing Grid to Horizontal and Vertical stacks.

## Steps to reproduce

1. Create grid card
2. Add conditional card
3. Add another card
4. conditional card still shows blank space rather than hiding

--- 

Second is tricky due to different heights in the custom-card lovelace component however im sure the same would happen with a button card if the height was adjusted.

## Environment

- Home Assistant release with the issue: 0.118
- Last working Home Assistant release (if known):
- Browser and browser version: Edge 83.0.478.61
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by gadgetchnnel** [comment]
I can raise a separate issue regarding this if necessary, but it seems that the same happens if you wrap an entire grid card in a conditional card. The space required for the grid is still taken up even if the conditions are not met.

**Comment by eximo84** [comment]
> I can raise a separate issue regarding this if necessary, but it seems that the same happens if you wrap an entire grid card in a conditional card. The space required for the grid is still taken up even if the conditions are not met.

But that surely is a bug. White space shouldn't be left if the condition isn't met. The item should be hidden completely.

**Comment by oywino** [comment]
I second this issue. Just experienced the same today. The grid is fully visible even when the conditions are not met. This is my card config:

![image](https://user-images.githubusercontent.com/18447119/104843253-f2cb1b80-58c9-11eb-88f7-d87ef6f9e45f.png)

And this is the result when everything is off:

![image](https://user-images.githubusercontent.com/18447119/104843283-13937100-58ca-11eb-8b28-9607acf4c368.png)

So, I agree. This must be a bug.

**Comment by oywino** [comment]
I tested this in version 2021.1.3 and the problem is only apparent as long as you remain in Edit mode on a dashboard.
As soon as you exit edit mode, it seems to work as expected.
