### ISSUE TITLE
English as profile language causes misformatted numbers

### ISSUE THREAD

**Issue by scaarup** [home-assistant/frontend#7789]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I am using English as language in my UI profile and after updating to 0.118, I see entity with states like for example "-2,854.7 W". 

## Expected behavior

In Denmark, where I live, we are using a different format and the state should be "-2.854,7 W". Now I could change the profile language to Danish, but I really don't want that.

## Steps to reproduce
No steps necessary, this happened after an update. And it relates specifically to PR [https://github.com/home-assistant/frontend/pull/7516](https://github.com/home-assistant/frontend/pull/7516)

## Environment

- Home Assistant release with the issue: 0.118.2
- Last working Home Assistant release (if known): 0.117.x
- Browser and browser version: Chrome 86.0.4240.111
- Operating system: Mac OS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
This autoformat setting should either be toggled on/off or it should be independent from the language chosen in the UI profile. Just like any phone, computer etc.

**Comment by logicup-dev** [comment]
> In Denmark, where I live, we are using a different format and the state should be "-2.854,7 W". Now I could change the profile language to Danish, but I really don't want that.
> 
> ## Steps to reproduce
> No steps necessary, this happened after an update. And it relates specifically to PR #7516
> 
>
Have a look here: https://github.com/home-assistant/frontend/issues/7745

**Comment by scaarup** [comment]
> > In Denmark, where I live, we are using a different format and the state should be "-2.854,7 W". Now I could change the profile language to Danish, but I really don't want that.
> > ## Steps to reproduce
> > No steps necessary, this happened after an update. And it relates specifically to PR #7516
> 
> Have a look here: #7745

Yeah I see, that is however closed. I am still convinced that this is a bug. 0.118 formats numbers incorrectly. The decision taken about the number formating should directly relate to the language selected, is wrong. And it creates incorrectly formatted numbers for everyone wishing to have an English UI language, but numbers formatted locally. At least give me the possibility to turn this off.

**Comment by bramkragten** [comment]
Change your language to English UK

**Comment by scaarup** [comment]
> Change your language to English UK

I have English and English(GB) - they seem to behave in the same way.

**Comment by krakers09** [comment]
> Change your language to English UK

It was already told couple of times that English GB won't fix it.

**Comment by Erriez** [comment]
> It was already told couple of times that English GB won't fix it.

Correct: There is an inconsistency between number formatting.

Related issues: https://community.home-assistant.io/t/change-sensor-float-to-european-notation/263116

**Comment by scaarup** [comment]
At some point it was decided that, if your profile language in the HA UI is set to English (any kind), you get English/American number formatting (in some places/cards). 
I wonder why the 12-hour clock, feet, miles, yards and all of that is not forced upon on us.

**Comment by spacegaier** [comment]
There is already work under way to add a feature that allows users to control the behavior: https://github.com/home-assistant/frontend/pull/7925

**Comment by scaarup** [comment]
@spacegaier that is great! :)

**Comment by bramkragten** [comment]
Merged so fixed!
