### ISSUE TITLE
Wrong number formatting for climate entity

### ISSUE THREAD

**Issue by bieniu** [home-assistant/frontend#7795]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
I use HA with language set to Polish. From HA 0.118 `,` character is used as the decimal separator. Unfortunately for climate entity in the entities card or in the more-info window `.` is used.

![image](https://user-images.githubusercontent.com/478555/100076440-7d9b1700-2e41-11eb-8eed-b0f996cff83b.png)

![image](https://user-images.githubusercontent.com/478555/100076481-8986d900-2e41-11eb-875e-95dea1f126f2.png)

## Expected behavior

Number formatting should be independent of the entity type.

## Environment

- Home Assistant release with the issue: 0.118.x
- Last working Home Assistant release (if known): 0.117.x
- Browser and browser version: Opera 72/Edge 87
- Operating system: Windows 10

## State of relevant entities

![image](https://user-images.githubusercontent.com/478555/100077305-7f190f00-2e42-11eb-82fe-616e2c1ddd7f.png)

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zsarnett** [comment]
This just hasnt been implemented. Not a bug
