### ISSUE TITLE
Quick Bar - focus jumps to first entity on the list on Safari

### ISSUE THREAD

**Issue by krakers09** [home-assistant/frontend#7799]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Not exactly sure if it's a bug or feature, but looks more like a bug.

On Safari after pressing 'e' to open Quick Bar, focus immediately jumps to first entity on the list. In order to type something in Quick Bar I need to manually click on input field. This happens only on Safari and works correctly in Chrome of Opera

## Expected behavior

Keep focus on input in order to be able typing straight after opening quick bar. Just like in Chrome or Opera
## Environment

- Home Assistant release with the issue: 0.118.1 and 0.118.3
- Last working Home Assistant release (if known): Don't know
- Browser and browser version: Safari Version 14.0.1 (16610.2.11.51.8)
- Operating system: macOS Big Sur 11.0.1

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by krakers09** [comment]
This issue is still present on 2021.2.3 and now Safari Version 14.0.3 (16610.4.3.1.4)

**Comment by hwestman** [comment]
I'm seemingly having the same issue on HA 2021.3.4, Safari 14.0.3

![quickbar](https://user-images.githubusercontent.com/1140735/112442393-112b1880-8d4c-11eb-887d-2b3ae10186e8.gif)
(Sorry about the awful quality)
