### ISSUE TITLE
Grid Card issue when setting columns option

### ISSUE THREAD

**Issue by krzysiek2788** [home-assistant/frontend#7806]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem

Grid Card when added in code editor option:
columns: 2
I cannot get back to Visual editor and I need to write code. If I delete columns: 2 going back to Visual Editor is working fine.

## Expected behavior

![image](https://user-images.githubusercontent.com/61471407/100207399-d3d28d80-2f07-11eb-81e0-769c812c8474.png)

## Environment

- Home Assistant release with the issue: 118.3
- Operating system:
![image](https://user-images.githubusercontent.com/61471407/100207615-14320b80-2f08-11eb-8550-54c78aebd479.png)

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/pull/7762
