### ISSUE TITLE
Lovelance dashboard can not be switch to auto mode

### ISSUE THREAD

**Issue by majkrzak** [home-assistant/frontend#7818]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Is it not possible to simply switch lovelance dashboard back to be automatically manage after switching to manual mode without manual hacking/removing `/config/.storage/lovelance`

## Expected behavior
 - Button/action menu entry for switching lovelance back to auto mode. 
 - Mode config entry in Dashboards manager panel. 

## Steps to reproduce

1. Switch dashboard to manual mode
1. Cry

**Comment by zsarnett** [comment]
This is not a bug. You can create a new dashboard easily in the configuration... The action for that dashboard should not be reversable

**Comment by majkrzak** [comment]
Why so? For me it sounds like a major design flaw. Especially together with lack of possibly to remove default dashboard. When someone will switch it to manually mannaged he is doomed forever by design.

**Comment by SeanPM5** [comment]
You can switch back to auto generated mode by doing the following:
1. Click Lovelace action menu (3 dots)
2. Edit Dashboard
3. Click Lovelace menu again, this time enter "Raw configuration editor"
4. Select all -> Delete everything -> Hit "Save" button in top right
5. Accept prompt

It's kind of hidden / undiscoverable, but that's for the best IMO as you don't want to accidentally do this and lose all your edits.

**Comment by iantrich** [comment]
You can also do:
1. Create new auto dashboard
2. Make it default
3. Delete old dashboard

Given there are multiple solutions to this, I'm going to close. Perhaps a PR to docs could be beneficial to explain
