### ISSUE TITLE
SyntaxError: invalid regexp group in /frontend_latest/chunk.<hash>.jsdomo

### ISSUE THREAD

**Issue by thias** [home-assistant/frontend#7836]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When accessing my existing lovelace dashboard, I see the following in the server log each time:
```
Logger: frontend.js.latest.202011112
Source: components/system_log/__init__.py:193
First occurred: 13:11:48 (1 occurrences)
Last logged: 13:11:48
https://<myhostname>/frontend_latest/chunk.36b0722b88395b178fa2.js:1:36 SyntaxError: invalid regexp group
```
I *think* this started after upgrading from 0.117 to 0.118. Yesterday's 0.118.4 still behaves the same. Same from both Firefox and Chromium.

## Expected behavior

No errors in the logs :innocent: 

## Steps to reproduce

1. Access any of my 2 lovelace dashboads.
1. Check the server logs.

## Environment

Home Assistant 0.118.4 on a Raspberry Pi 4 installed using the 64bit image.

It was recently installed, restoring a backup from 0.118.0 on a Raspberry Pi 3 32bit.

I think 0.117 didn't show this error and that 0.118 on the Pi3 already did, though.

## State of relevant entities

n/a

## Problem-relevant configuration

None. Even the "full" HA-managed lovelace dashboard triggers the log entry.

## Javascript errors shown in your browser console/inspector

```
SyntaxError: invalid regexp group chunk.36b0722b88395b178fa2.js:1:36
```
```
ChunkLoadError: Loading chunk 319 failed.
(missing: https://domo26.marmotte.net/frontend_latest/chunk.36b0722b88395b178fa2.js) app.c5d13434.js:40429
```

## Additional information

At least one other person seems to be seeing the same message: https://community.home-assistant.io/t/frontend-error-log-syntaxerror-invalid-regexp-group/248817

**Comment by thias** [comment]
I no longer see this error, and all of my dashboard elements work again as expected when clicking on them.

I can't think of anything relevant that I might have done: The only things I've poked around with since yesterday were with ONVIF integrations (my Annke camera stopped working properly with 0.118 for some reason and can't be re-added), InfluxDB/Grafana add-ons (and the influxdb configuration) and trying to get the BLE tracker working. Weird.

**Comment by MaximumSU** [comment]
I had this error too (and half of my lovelace dashboards which has more then one vertical stack cards was not showing correctly). But only in Firefox, In Chrome all OK. When i upgraded Firefox to latest (i have something like 76's version before) and error gone.

**Comment by ndonegan** [comment]
Seeing exactly the same error message on a host with Firefox ESR. Newer browser is OK.

The error appeared as soon as I hit the "Menu" button on the top right of a panel.

**Comment by dmak** [comment]
I confirm that the problem for v0.118 is in Firefox only, Chrome works fine. Sometimes Firefox does not open UI at all (shows error just after login dialog). If UI opens then click on any entity on a dashboard has no effect (should open a dialog with extended entity controls).
