### ISSUE TITLE
Developer Tools "states" entity column width too small

### ISSUE THREAD

**Issue by martinhoess** [home-assistant/frontend#7838]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
if an entity has a attribute with a really long value, the entity colum in the developer tools states page is too small. If you filter/search so that the entity with the long attribute is filtered out, the entity column is wide enough.
![image](https://user-images.githubusercontent.com/47973549/100456561-e217d980-30c0-11eb-83dd-df767a6039bb.png)
![image](https://user-images.githubusercontent.com/47973549/100456607-fb208a80-30c0-11eb-9f4c-b234d44db095.png)
![image](https://user-images.githubusercontent.com/47973549/100456738-2a36fc00-30c1-11eb-9b95-04ba430028fa.png)

## Expected behavior
The entity column should never become that small (not smaller than the longest entity name), also the attributes column should always use the full width (second screenshot). So the width should be calculated/prioritized from left to right.

## Steps to reproduce
Developer Tools -> States -> you need an entity with an attribute with a really long value and also entities with a long name

## Environment

- Home Assistant release with the issue: 0.118.4 (and prior)
- Last working Home Assistant release (if known): -
- Browser and browser version: tested with Chrome and Edge
- Operating system: Windows 10

**Comment by spacegaier** [comment]
I don't really agree with that. For me a good overall screen space usage is the higher priority and that means that the element with the most content (attributes) needs some space. If we cannibalize (making entity ID column wider = less width for attributes) that just to not have the entity ID wrap around, I don't think we have a better overall experience.

Since basically all entities have multiple lines of attributes anyway, the wrapping around of the entity ID does not increase the height of a row.

**Comment by noxhirsch** [comment]
I absolutely agree with @martinhoess 
Multiple lines for the entity ID might not make the the rows higher, but are way harder to read when scrolling through. One line per entity ID is much clearer.
Also the very long content in attributes already has multiple lines, so it doesn't matter that much if it get's a little bit longer when the with is reduced by that tiny bit needed for the entity ID.

**Comment by martinhoess** [comment]
> Multiple lines for the entity ID might not make the the rows higher, but are way harder to read when scrolling through (and triggers my OCD, because it looks wrong, too). One line per entity ID is much clearer and cleaner.

Exactly!

> Also the very long contents of some attributes already have multiple lines, so it doesn't matter that much if they get a little bit longer when the with is reduced by that tiny bit needed for the entity IDs.

Mostly it is not about the attributes but about the entities. All entities I have, which have one or more long attributes, are either auto-generated or the attribute value is a endless concatenation of strings or JSON, so it does not matter when/where it is wrapped. Also entities with a long name but only one or two attributes are using an extra line, so if you have a lot of those and one with a long attribute value it uses a lot more of vertical space than it should.  
![image](https://user-images.githubusercontent.com/47973549/100597008-2db6c700-32fd-11eb-8452-82c8bb1adec4.png)

**Comment by noxhirsch** [comment]
This problem still exists in Home Assistant 2021.4.0b4
![image](https://user-images.githubusercontent.com/30938717/113516520-f68e4600-957a-11eb-878a-d47d884d49fb.png)

**Comment by martinhoess** [comment]
For me, the issue is not yet resolved because it still annoys me every day.

**Comment by spacegaier** [comment]
In the linked PR I set a bigger min-width for the entity column, but more crucially I set a percentage width for the column. That means for wide screens, the column will now grow and use more space. I think that might be a good compromise.

Note: Very long entity IDs will still occupy two lines depending on the screen width, but less often.
