### ISSUE TITLE
Node protection select box contains incorrect information

### ISSUE THREAD

**Issue by timmccor** [home-assistant/frontend#7853]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

When looking at the 'Node Protection' select box in my Z-Wave configuration for a device with this capability, I find that the box is populated with the value ID spread across multiple rows.

Looking at the console I see the following:

`dom-repeat expected array for `items`, found 72057594304086020`

The JSON returned from the call to fetch the node protection status was:

```
{
    "value_id": "72057594304086020",
    "selected": "Unprotected",
    "options": [
        "Protection by Sequence",
        "No Operation Possible",
        "Unprotected"
    ]
}
```

Clearly the javascript is attempting to render the value_id instead of the options array.

## Expected behavior

This should contain the 'options' array of the returned JSON, in my case:
```
    "options": [
        "Protection by Sequence",
        "No Operation Possible",
        "Unprotected"
    ]
```

## Steps to reproduce

Add a Z-Wave node which has Node Protection, then navigate to its configuration and click the 'Protection' select box.

## Environment

- Home Assistant release with the issue: 0.118.2
- Last working Home Assistant release (if known): Pretty sure it worked in the past year - don't remember when.
- Browser and browser version: Google Chrome Version 86.0.4240.198
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt
dom-repeat expected array for `items`, found 72057594304086020
```

## Additional information

Tried to diagnose and fix this myself, but I'm obviously missing something.

src/panels/config/integrations/integration-panels/zwave/zwave-node-protection.js

This file appears to show that we always grab the protection options are always expected to be the first element of the returned JSON. Line 133.

Over on the backend in: components/config/zwave.py

Line 228 would appear to suggest that these options are always the 3rd element of the array. And indeed in the JSON I captured from my browser and listed above this is the case.

What's confusing is that it appears things have always been this way, and that it must have never worked. But it did - albeit the setting of the note protection status never worked and I'd perhaps wrongly assumed that was down to something on my system at the time.

I didn't attach screenshots as I thought it probably isn't needed given the other information available in this issue, but if you want them please let me know and I'll go generate them. Likewise happy to gather any other information that might be useful I haven't thought of.

**Comment by horriblenoises** [comment]
I also have this problem. Running docker image 118.5.

**Comment by timmccor** [comment]
I have a fix in the works.
