### ISSUE TITLE
Media player does not show entity picture (Sonos)

### ISSUE THREAD

**Issue by casper-bak** [home-assistant/frontend#7869]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
When using the music services "TELMORE Musik" and "YouSee Musik" through Sonos, no entity picture shows in the Media Player.
The picture is showing in the Sonos app.
If I cast from the "TELMORE Musik" app to Sonos the entity picture shows.

Using "TELMORE Musik" through Sonos:

![Sonos](https://user-images.githubusercontent.com/63472726/100852715-2a4f4700-3487-11eb-8339-f5b017692262.PNG)
![Sonos Tilstand](https://user-images.githubusercontent.com/63472726/100852281-92515d80-3486-11eb-9f93-ce4e702b0594.PNG)

Playing exact same file but casting from the "TELMORE Musik" app to Sonos:

![Telmore](https://user-images.githubusercontent.com/63472726/100852440-d2b0db80-3486-11eb-9b9a-2f5e4b4fc518.PNG)
![Telmore Tilstand](https://user-images.githubusercontent.com/63472726/100852452-d7758f80-3486-11eb-9185-fce727110db3.PNG)

## Expected behavior

The media player should show the album cover as entity picture no matter how a music file is played (through Sonos/To Sonos)
## Environment

- Home Assistant release with the issue: 0.118.0
- Last working Home Assistant release (if known): Do not know
- Browser and browser version: Firefox, Safari, Chrome
- Operating system: Win10, iOS14.2

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
The log file shows following, when playing music in the sonos app

Logger: homeassistant.components.media_player
Source: components/media_player/__init__.py:907
Integration: Medieafspiller (documentation, issues)
First occurred: 21. februar 2021 9.20.52 (10 occurrences)
Last logged: 10.19.59

Error retrieving proxied image from http://192.168.0.4:1400/getaa?s=1&u=x-sonos-http%3acatalog%253atrack%2540%257ecatalog%252f1387%252ftracks%252f184520530.mp4%3fsid%3d175%26flags%3d8224%26sn%3d9
Error retrieving proxied image from http://192.168.0.4:1400/getaa?s=1&u=x-sonos-http%3acatalog%253atrack%2540%257ecatalog%252f1387%252ftracks%252f184520527.mp4%3fsid%3d175%26flags%3d8224%26sn%3d9
Error retrieving proxied image from http://192.168.0.113:1400/getaa?s=1&u=x-sonos-http%3acatalog%253atrack%2540%257ecatalog%252f1387%252ftracks%252f184520532.mp4%3fsid%3d175%26flags%3d8224%26sn%3d9
Error retrieving proxied image from http://192.168.0.4:1400/getaa?s=1&u=x-sonos-http%3acatalog%253atrack%2540%257ecatalog%252f1387%252ftracks%252f224560632.mp4%3fsid%3d175%26flags%3d32%26sn%3d9
Error retrieving proxied image from http://192.168.0.4:1400/getaa?s=1&u=x-sonos-http%3acatalog%253atrack%2540%257ecatalog%252f1387%252ftracks%252f197101183.mp4%3fsid%3d175%26flags%3d8224%26sn%3d9

**Comment by jjlawren** [comment]
I made some improvements to Sonos album art handling that will be in 2021.6, but I'm not sure if that's related to your problem.
