### ISSUE TITLE
Failed to load blueprint in Blueprints panel (1.0.0b0)

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#7879]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

![image](https://i.imgur.com/iKk98HO.png)

This was changed from `!placeholder` to `!input` kinda last minute, but the Blueprints panel is seemingly still looking for placeholder tag and thus printing errors on the default included blueprints.

## Steps to reproduce

1. Go to Configuration -> Blueprints
2. Look at errors

## Environment

- Home Assistant release with the issue: 1.0.0b0 😱 
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome stable
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ludeeus** [comment]
If you used the nightly builds, you need to manually update the blueprints in the config directory

**Comment by SeanPM5** [comment]
Ah that was it, not an issue then, thanks.
