### ISSUE TITLE
Small dots on Blueprint dashboard

### ISSUE THREAD

**Issue by vorostamas** [home-assistant/frontend#7882]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

There are two small dots between the "Create automation" and delete button. See picture below.
It seems to be present only on Chromium browsers, I've tried with Brave, Chrome and Firefox, and the dots are not present on Firefox.
![image](https://user-images.githubusercontent.com/9920416/100995499-23dcd000-3558-11eb-8d4e-0c1726115715.png)

## Expected behavior

There are no small dots.

## Steps to reproduce

1. Navigate to Configuration
2. Click on Blueprints

## Environment

- Home Assistant release with the issue: 1.0.0b0
- Last working Home Assistant release (if known): -
- Browser and browser version: Chrome Version 87.0.4280.66 (Official Build) (64-bit)
- Operating system: Windows

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
The dots are only present when the "Create automation" button is present.

**Comment by bramkragten** [comment]
Fixed!
