### ISSUE TITLE
Blueprints doesn't warn of unsaved changes

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#7896]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

There is a "Manage Blueprints" button on the page. Clicking this navigates you away from the editor back to the Blueprints listing, and thus loses all your unsaved changes.

![image](https://i.imgur.com/0siATwR.png)

## Expected behavior

There should be a warning like the automation editor has:

![image](https://i.imgur.com/rq7zh51.png)

Edit: The Blueprints section does have this same exact warning already, but only when you hit the back button in the top. The Manage Blueprints button navigates you to the same exact page yet it doesn't have this warning...

## Steps to reproduce

1. Go to Configuration -> Blueprints
2. Click "Create Automation" from one of the defaults (like motion-activated light)
3. Add a motion sensor entity (without saving)
4. Now click Manage Blueprints button above. You will be taken to `/config/blueprint/dashboard` with no way to get back to what you were doing. The back button in HA takes you to `/config/dashboard` instead. All your unsaved changes were lost.

## Environment

- Home Assistant release with the issue: 0.1.0b0
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
This button was removed! :-)
