### ISSUE TITLE
Blueprints input description text truncated

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#7898]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Right now the description for inputs gets truncated rather than wrapping lines. This is not good IMO as these descriptions might contain important information/instructions. 

You can see this on the default example blueprint:

![image](https://i.imgur.com/38d0ska.png)
![image](https://i.imgur.com/Rr7G3T0.jpg)

## Expected behavior

Wrap lines instead so that the entire description is visible.

## Environment

- Home Assistant release with the issue: 0.1.0b0
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
Already fixed!
