### ISSUE TITLE
Blueprints lack warning when input criteria can't be met

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#7902]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I think Blueprints can be a little better about letting the user know when they don't meet the criteria for a blueprint.

I don't have any motion sensors in this secondary Home Assistant instance, yet it still displays the entity dropdown (which is empty). I can click on the dropdown but not actually select anything. It feels kinda wrong to let people interact with non-functional controls?

![image](https://i.imgur.com/Kl6PiL8.png)

Here is another example, from a Blueprint I imported from Frenck. I don't have any lights belonging to the Elgato Key Light integration yet it's showing me all of the light picker controls anyway. These are all non-functional: 

![image](https://i.imgur.com/Gf7DO99.png)

I think stuff like this will be confusing, especially for beginners who are just getting started with Home Assistant by importing blueprints. Instead I think it should show just text in place of that.

## Expected behavior

Here is a quick mockup of what I think it should look like. Rather than an empty dropdown, display an error or warning notifying the user they do not meet the criteria.

![image](https://i.imgur.com/9HumkCv.png)

For the other example it could say "You don't have a light entity belonging to the elgato integration"

## Steps to reproduce

1. Go to Configuration -> Blueprints
2. Click Import Blueprint and paste this URL to import Frenck's Blueprint: https://github.com/frenck/home-assistant-config/blob/master/config/blueprints/automation/elgato_keylight_camera.yaml
3. If you do not have the Elgato integration, the "Key Light" input will show you controls that you can interact with but not do anything.

## Environment

- Home Assistant release with the issue: 0.1.0b0
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment]
It is on our to-do list :-)
