### ISSUE TITLE
Login with password managers (autocomplete)

### ISSUE THREAD

**Issue by TheGroundZero** [home-assistant/frontend#7918]
Hi

I would like to request that the `autocomplete="off"` is removed from the username and password field on the login page.  
This tag prevents password managers from auto-filling the login credentials on the login page, which has a negative impact on UX.

Old best practice was to add this tag to login forms in fear of browsers autocompleting logins on shared computers.  
However, nowadays the added security of a password manager outweighs the risk/chance of people sharing a computer without having their own user account or browser account.

Kr 
TGZ

**Comment by frenck** [comment]
Actually, that is not the issue; the issue is caused by the shadow dom, which most password managers fail to work with.

For more information, see #3133, which duplicated this issue.

**Comment by bdougherty** [comment]
The autocomplete attribute should be set to `username` and `current-password` on their respective fields regardless of whether it fixes the password manager issue.

**Comment by spacegaier** [comment]
@bdougherty I played around with that on my dev box. Even if I add "username" to the field, Firefox does ignore it. Chrome for some reason is not asking me to store in the first place although the option is active...

So could also be down to the shadow DOM issue.
