### ISSUE TITLE
Clicks on entities do not work

### ISSUE THREAD

**Issue by aik** [home-assistant/frontend#7920]
Firefox 76b5 with a new clean profile with no addons, Chromium 76, latest HASS 0.118.5.

After upgrading to 0.118.5 from whatever was the latest in September, clicks on entities no longer open them in Firefox only. Chromium is fine though.

The firefox log has:
```
SyntaxError: invalid regexp group chunk.36b0722b88395b178fa2.js:1:36
ChunkLoadError: Loading chunk 319 failed.
(missing: http://aikhasse:8123/frontend_latest/chunk.36b0722b88395b178fa2.js)
```
The file is there, Firefox can open it in a separate window:
```
(homeassistant) aik@aikhass:~/homeassistant/lib/python3.8/site-packages/hass_frontend/frontend_latest$ ls *36b0722b88395b178fa2*
chunk.36b0722b88395b178fa2.js  chunk.36b0722b88395b178fa2.js.gz  chunk.36b0722b88395b178fa2.js.map
```
chunk.36b0722b88395b178fa2.js.LICENSE.txt is missing though and most other files have it so I suspect something did not update when I upgraded to 0.118.5.

upd: created a thread there too: https://community.home-assistant.io/t/cannot-add-anything-to-dashboards-after-upgrading-to-0-118-5-frontend-broken/252477/2

**Comment by bramkragten** [comment]
Updating to a newer Firefox version will fix this. Will look into it for older versions.

**Comment by bramkragten** [comment]
@uvjustin I think this is for the regex introduced in #7417

**Comment by uvjustin** [comment]
I see - looks like named capture groups were not supported in Firefox versions before 78. We used named capture groups for clarity, should we revert to regular capture groups?
https://caniuse.com/?search=regexp%20named%20capture%20groups

**Comment by aik** [comment]
ouch I honestly believed 76b5 is the latest. Upgraded to 84, works now. /me feels stupid :-/

**Comment by bramkragten** [comment]
> I see - looks like named capture groups were not supported in Firefox versions before 78. We used named capture groups for clarity, should we revert to regular capture groups?
> [caniuse.com/?search=regexp%20named%20capture%20groups](https://caniuse.com/?search=regexp%20named%20capture%20groups)

yes, lets revert
