### ISSUE TITLE
UI Automation Editor Deletes Wrong Action

### ISSUE THREAD

**Issue by ZuluWhiskey** [home-assistant/frontend#7932]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When editing an automation in the UI, if you click the three dots next to an 'action' & select delete then the wrong action is deleted. I have definitely had this issue normally but have today only been able to reproduce when actions are in "Edit as YAML" mode.

I have noticed though that the YAML issue seems to be that the UI gets 'confused' (for want of a better word) as if you then change back to UI mode for the actions (can be seen in the GIF below) it's not the same action that the YAML was showing.

![image](https://user-images.githubusercontent.com/35011199/101507481-7d853600-396e-11eb-8a14-e88fb8c72a5d.gif)

## Expected behavior

The correct action is deleted & the correct YAML for that action is shown.

## Steps to reproduce

See my GIF - Add multiple actions to an automation in the UI, edit those actions as YAML, try to delete one.

## Environment

- Home Assistant release with the issue: 0.118.4
- Last working Home Assistant release (if known):
- Browser and browser version: Multiple
- Operating system: I run my installation on a Docker image on my Ubuntu 16.04 server.

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

I've hopefully explained well enough and if not, fingers crossed the GIF explains it better!

**Comment by ZuluWhiskey** [comment]
I haven't tested whether this is still a bug in 2020.12.1, I'll update when I have done so 👍

**Comment by ZuluWhiskey** [comment]
Just to update, this is still an issue in 2020.12.1 - I mentioned in the original comments that it also happens when not in 'Edit as YAML' mode, however I have not been able to replicate that issue so I must've misremembered.

It's also worth calling out that the correct action is removed but the YAML that is shown is incorrect. But as soon as you exit 'Edit as YAML' mode it shows the correct action and when you re-enter 'Edit as YAML' you are shown the correct YAML.

**Comment by spacegaier** [comment]
@ZuluWhiskey Thank you for the additional details. That helped tracking down the issue 👍.

**Comment by ZuluWhiskey** [comment]
> @ZuluWhiskey Thank you for the additional details. That helped tracking down the issue 👍.

Awesome, glad to hear it! 😃
