### ISSUE TITLE
The "Import Blueprint" screen can't be exited on a mobile device

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/frontend#7941]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Using the iOS app, if I click the "Import Blueprint" button from Configuration->Blueprints, I get a full screen dialog where I can enter a URL, but there's no way to exit from that screen without entering a URL and continuing.  Swiping to the right from the left edge doesn't bring up the sidebar, as it usually does elsewhere, and there's no explicit "back" button.  I can use browser's "back" button if I use Safari/Chrome on my phone, but that doesn't seem like the right approach, and doesn't work in the companion app.

## Expected behavior

I should be able to exit the Import Blueprint screen, either by swiping right from the left edge to reveal the sidebar, or with an explicit "left arrow"/"back" button within the HA UI and without requiring the use of the "back" button in a mobile browser.

## Steps to reproduce

On a mobile device, iPhone in my case, navigate to Configuration->Blueprints and tap the "Import Blueprint" button.  Note that if you're using the iOS companion app, you cannot exit that screen without killing the app and re-launching.  If you're using a mobile browser, the only way to back is to use the browser's "back" button.

## Environment

- Home Assistant release with the issue: 1.0b4
- Last working Home Assistant release (if known): N/A
- Browser and browser version: iOS Companion App/Safari
- Operating system: iOS 14.2

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by zacwest** [comment]
This remains an issue in 2021.2.0b2 / 20210127.6, once you enter this screen there are no buttons to exit it.

You may be able to, on some devices, rotate to landscape to expose some gutter area that can be tapped to dismiss.
