### ISSUE TITLE
Last scanned not updating for Tags 

### ISSUE THREAD

**Issue by adonno** [home-assistant/frontend#7943]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Last scanned isn't updating on tags and displays "never"
## Steps to reproduce

1. go to settings
2. go to tags
3. Scan a tag and see if the date of the last scan update 
## Environment

- Home Assistant release with the issue: 1.0.0b5
- Last working Home Assistant release (if known):
- Browser and browser version: Vivaldi & Chrome 
- Operating system: Windows

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
I can confirm the issue. PR to fix it will come in a few minutes.
