### ISSUE TITLE
Device name in card is lowercase

### ISSUE THREAD

**Issue by skorokithakis** [home-assistant/frontend#7948]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I have a device called "Bedroom lamp" and a dashboard card called "Bedroom". HA cleverly removes "Bedroom" from the device name, but it leaves "lamp" in lowercase and it looks ugly.

![image](https://user-images.githubusercontent.com/23648/101950471-0665d100-3bfe-11eb-9fe0-1223745b1ce5.png)

## Expected behavior

I expect the l to be capitalized, "Lamp".

## Steps to reproduce

* Add a device called "Bedroom lamp".
* Add a card called "Bedroom".
* Device name is "lamp".

## Environment

Docker with Compose on Linux

- Home Assistant release with the issue: 0.118.5
- Last working Home Assistant release (if known): None
- Browser and browser version: Firefox latest
- Operating system: Linux

## State of relevant entities

No entities are relevant.

## Problem-relevant configuration

No configuration is relevant.

## Javascript errors shown in your browser console/inspector

No errors.

## Additional information

None.

**Comment by spacegaier** [comment]
I am not aware that HA is on the fly renaming elements in the UI.

What kind of card did you add to the dashboard? Can you please show the YAML for it. Since in most (all?) cards you actually add entities and not devices, can you double check that the rendered entity is not actually called "lamp".

**Comment by frenck** [comment]
@spacegaier The auto generated dashboard does that. It groups by area, and remove the area name from an entity.

This behavior was inspired by Apple's Home Application.

**Comment by spacegaier** [comment]
@frenck Thanks for the hint. I learn something new every day here 😄 .

Issue reproduced and I agree it does not look nice, so I will push a PR in a few seconds that would adjust the behavior.
