### ISSUE TITLE
Frontend not working anymore in Brave browser

### ISSUE THREAD

**Issue by cnico** [home-assistant/frontend#7959]
## Checklist

- [ X ] I have updated to the latest available Home Assistant version.
- [ X ] I have cleared the cache of my browser.
- [ X ] I have tried a different browser to see if it is related to my browser.

## The problem

The home assistant frontend does not work anymore in Brave browser which is a chromium based browser.
It was working good until recently (a few weeks) but after recent update, it does not work anymore in brave.
I can not tell which update introduced the regression, sorry.

In Brave dev tools javascript console, here is the message I have just after the login : 
```
core.7829e4bb.js:1 WebSocket connection to 'wss://[MYDNS]/api/websocket' failed: Unknown reason
a @ core.7829e4bb.js:1
lovelace:1 
```

It works correctly with Edge or  Google chrome

## Expected behavior

No error in Brave.

## Steps to reproduce

Install Brave on windows and connect to a home assistant instance. 

## Environment

- Home Assistant release with the issue: 0.118.5
- Last working Home Assistant release (if known): 
- Browser and browser version: Brave 1.17.75
- Operating system: windows 10 or Ubuntu 20.04

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```

```

## Javascript errors shown in your browser console/inspector

```
core.7829e4bb.js:1 WebSocket connection to 'wss://[MYDNS]/api/websocket' failed: Unknown reason
a @ core.7829e4bb.js:1
lovelace:1 

```

**Comment by spacegaier** [comment]
I cannot reproduce the issue. I just installed the latest x64 Brave version and can without any issues load and use the latest dev version frontend. Also tried my instance that runs the official beta 1.0.0b6. No issues there either.

Can you try accessing the frontend from a private window session of the browser. Sometimes this proves that it is only a caching issue.

**Comment by cnico** [comment]
I did some more test and in private mode, the problem is reproduced.
After digging a few more, I found out that when I disable Brave's privacy protection for my home assistant internet web site, it is working correctly.
Brave seems to interpret homeassistant websocket connection as non correct regarding its privacy settings shields for category 'Trackers and Ads'. 
It is probably a Brave bug like this one : https://github.com/brave/browser-laptop/issues/6641 
You can close this one.
