### ISSUE TITLE
History graph card is not rendered if "history" component is disabled

### ISSUE THREAD

**Issue by dmak** [home-assistant/frontend#7960]
## The problem

[History graph card](https://www.home-assistant.io/lovelace/history-graph/) is not rendered if [history component](https://www.home-assistant.io/integrations/history/) is disabled.

![image](https://user-images.githubusercontent.com/366965/102022440-2379db80-3d87-11eb-8ba2-55c0a79c5d2e.png)

## Expected behavior

Instead of rendering "Loading state history..." a message e.g. "Disabled because of missing history component" should be displayed. At least a warning message should be logged.

## Steps to reproduce

Disable history component, restart Home Assistant and check history graph card.

## Environment

- Home Assistant release with the issue: 0.118.5
- Browser and browser version: Chrome v87.0.4280.88
- Operating system: Windows 7 x64

**Comment by spacegaier** [comment]
I am working on this. PR will be coming soon.
