### ISSUE TITLE
Upgrade Issue

### ISSUE THREAD

**Issue by MarkO2705** [home-assistant/frontend#7966]
I run Home assistant in a virtual machine in Oracle Virtual Box under Windows 10.
I have had this running for 2 months or so
When the VB starts the Home Assistant machine it goes through a process (like a DOS screen) and finally it used to say
running home assistant ver ...
and I used to go into my Web browser and type in the URL of my home-assistant instance
That still happens and works ok 
but
the  Virtual Box screen now requests a login  and I cannot type one in
no username or password seems to be ok
but under my users in the web browser, I have a user name and password
It doesn't affect my Home assistant and all seems to work ok 
I even tried to create a new user administrator & PWxxxx
and the black VM screen won't accept it
it says
Welcome to Home Assistant
homeassistant login: _

my email is mporlicki@gmail.com

**Comment by spacegaier** [comment]
That does not sound like a HA frontend issue. You confirmed that HA runs fine and you can use the frontend. It sounds as if your VM is starting normally and is automatically starting HA after the boot process as well (hence you can access the frontend). The VM login screen you describe sounds like the regular terminal login for the VM itself which has nothing directly to do with HA.

**Comment by MarkO2705** [comment]
Thank you for the reply
I am not concerned as HA works fine   But It did not do this behavior
before,  and I got confused Thinking that a login was required  It was only
by accident when I received a message from HA about another process that I
realized HA was running OK   I don't really need the VM startup info   It
was just weird that this happened
regards
Maeck


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by spacegaier** [comment]
But that has nothing to do with the HA frontend then. Instead the behavior depends on your HA installation type and the used operating system + container.

So please consider closing this ticket.
