### ISSUE TITLE
Entity icons colors in Lovelace

### ISSUE THREAD

**Issue by NeWoKiKi** [home-assistant/frontend#7968]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Hello,

I have an issue with icons colors in Lovelace.
I added my Tuya's switches in my dashboard but when switch is on, the color doesn't change, it stays blue and off.
If I click on this entity in the dashboard, the color is yellow when the swich is on (so it's working).

![image](https://user-images.githubusercontent.com/69678428/102065291-a8510d80-3df8-11eb-877a-b3b669c517e0.png)

![image](https://user-images.githubusercontent.com/69678428/102065311-aedf8500-3df8-11eb-9972-22dcbd1e43eb.png)

It's working with other lights... but it's not working with Tuya switches and Somfy Shutters (maybe others ?)
Could you please help me ?

Many thanks,
Regards,

## Expected behavior

Icon status should be updated both in dashboard and entity window

## Environment

- Home Assistant release with the issue: 2020.12.0 (last)
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome 87.0.4280.88 (last)
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
Can you please properly fill out the issue template, so we have more information to go on? Thanks.

**Comment by NeWoKiKi** [comment]
*** Updated ***

**Comment by spacegaier** [comment]
Please also post the YAML for the card you used. Does it have `state_color: true` set? Otherwise the row in the card will not color the icon, but the more-info is unaffected by that flag so there it gets colored.

**Comment by NeWoKiKi** [comment]
That was as simple as that, my bad
I didn't search this way because it was working by default with lightbulb, so I thought it was working the same way with switches.

I added `state_color: true` to all my cards and now it's working perfectly.

Many thanks !

In addition, is it possible to have multiple icons states ? For example, for my shutters, I want to use `mdi:window-shutter` when closed, `mdi:window-shutter-open` when opened and `mdi:window-shutter-alert` when moving.

**Comment by spacegaier** [comment]
There is also a switch in the card editor, so no need to do that manually in the YAML.

Reg. multiple: I am not sure if/how you can override the state icons. Might be possible with some template magic. But for me, the state icon changes during cover/shutter movement, but might be coming from the integration itself and not the frontend.
