### ISSUE TITLE
Blueprint picker overflows card

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/frontend#7972]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When adding a new automation on a 15 inch screen notebook, the blueprint dialog looks like this:
![Screenshot_2020 12 14_12h59m02s_006_](https://user-images.githubusercontent.com/1368405/102122163-64d0c080-3e45-11eb-9948-2706267d4d76.png)

## Expected behavior

The select input should be within the outer box. The box could go full width here, no need to force it to be 50% off the witdh only. Maybe something like this:
![image](https://user-images.githubusercontent.com/1368405/102122491-d3ae1980-3e45-11eb-998e-3341b13b33f1.png)

## Steps to reproduce

1. Go to settings page
2. Next to automation
3. Create a new automation

## Environment

- Home Assistant release with the issue: 2012.12.0
- Last working Home Assistant release (if known): none
- Browser and browser version: Edge Beta 88
- Operating system: HassOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by TheZoker** [comment]
@bramkragten This is still an issue:
![Screenshot_2021 03 15_00h48m28s_004_](https://user-images.githubusercontent.com/1368405/111088604-3cca2980-8528-11eb-9997-de249e901d63.png)

**Comment by bramkragten** [comment]
What is the size (resolution) of your browser window? Can't reproduce...

**Comment by TheZoker** [comment]
It's a 15,6 inch screen with a 1920x1080 resolution
