### ISSUE TITLE
Lovelace Background No Longer Shows Under Transparent Header

### ISSUE THREAD

**Issue by stmrocket** [home-assistant/frontend#7974]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Prior to 2020.12.0, adding transparency to the header using a theme would result in the Lovelace background showing through the header.  After upgrading, the background appears to start below the header even with header transparency.

## Expected behavior
The header will change to the specified transparency and the Lovelace background will show through.

## Steps to reproduce
1. Set app-header-background-color and app-toolbar-background-color to have transparancy in the current theme.
2. Add a background to the Lovelace view.
3. reload themes and view.

## Environment

- Home Assistant release with the issue: 2020.12.0 (20201212.0)
- Last working Home Assistant release (if known): 0.118.5 (20201111.2)
- Browser and browser version: Chrome  87.0.4280.88
- Operating system: Windows 10

## State of relevant entities

Not Applicable
```yaml

```

## Problem-relevant configuration

From theme:
```yaml
midnight:
  app-header-background-color: "rgba(150,150,150,0.2)"
  app-toolbar-background-color: none
```
Background image from ui-lovelace:
```yaml
background: center / cover no-repeat url("/local/lovelace/background_19.png") fixed
```
## Javascript errors shown in your browser console/inspector
None shown.

```txt

```

## Additional information
Header as shown in Frontend 20201111.2:
![image](https://user-images.githubusercontent.com/19308297/102125480-62ec0a80-3e0f-11eb-85bf-503744e55885.png)

Header as shown in 20201212.0:
![image](https://user-images.githubusercontent.com/19308297/102125645-a0e92e80-3e0f-11eb-93e3-b8ef3dcd05dc.png)

The view icons are different as the 20201111.2 image was taken from a system running the same theme / background configuration but not yet upgraded.

**Comment by blhoward2** [comment]
I am seeing this behavior as well. I used to set the header background as transparent and then draw a background image across the whole screen. Now the header will go transparent but the image is not drawn behind the header.

**Comment by spider7611** [comment]
Have the same problem before have transparent but now it is not working after update.
![Ha](https://user-images.githubusercontent.com/45290475/102182930-59b17b00-3ead-11eb-8630-91672f54cfcd.JPEG)
If scroll down see transparent:
![Ha2](https://user-images.githubusercontent.com/45290475/102183004-70f06880-3ead-11eb-8f29-72dda083592a.JPEG)

**Comment by Karstensson** [comment]
I have the same issue. 118.5 worked well and all releases after that has broken this.

**Comment by peter-dolkens** [comment]
Another person here who was enjoying transparent title bar and is now looking for a solution

**Comment by panhans** [comment]
If someone is interested in a workaround with card-mod simply put this to your theme. Don't forget to edit the theme name, delete the background in your views and put it in the css code. (background-image)

``` 
card-mod-theme: YOURTHEMENAME

card-mod-root: |
  hui-view {
    background: none !important;
  }
  ha-app-layout {
    background-position: center !important;
    background-size: cover !important;
    background-repeat: no-repeat !important;
    background-image: url("/local/images/wallpaper/background.png") !important;
    background-attachment: fixed !important;
  } ```

**Comment by fenster24** [comment]
I am having the same issue. Adding the code suggested by panhans to my theme had no impact (I changed the theme name and also the background image url). Still not transparent until scrolling.

**Comment by fenster24** [comment]
The issue persists in Home Assistant Core 2021.7.2.

**Comment by Giuliointhetube** [comment]
The issue persists in Home Assistant Core 2021.8.8

**Comment by JoachimEngelmann** [comment]
Issue is still there with 2021.9.7

**Comment by liquidthex** [comment]
Issue persists in HA Core 2021.11.5
Would really like a HA that doesn't look totally horrible.

**Comment by Pixelpaule** [comment]
Issue persists in HA Core 2022.2.1

**Comment by snarlingllama** [comment]
Any update on this? Issue still persists on HA Core 2022.2.9.

**Comment by kongjudas** [comment]
2022.4.7 seems to hold on to the problem

**Comment by tYn0** [comment]
Any update on the issue? Still broken in 2022.6.6 :(

**Comment by stmrocket** [comment]
The issue persists in Home Assistant Core 2022.9.5

**Comment by yjamal01** [comment]
2022.11 and issue persists

**Comment by dampflok2000** [comment]
The issue persists in Home Assistant Core 2022.12.6

**Comment by kahancock** [comment]
2023.2.5 and issue presists

**Comment by yjamal01** [comment]
Now I can no longer get transparent header at all

**Comment by JOHLC** [comment]
ITS WORKINGGG!!! 👍🏼
<img width="963" alt="image" src="https://user-images.githubusercontent.com/63735432/236591934-4b4e6c98-40a6-4360-a51e-1e95b62b1232.png">

**Comment by blhoward2** [comment]
> ITS WORKINGGG!!! 👍🏼
> 
> <img width="963" alt="image" src="https://user-images.githubusercontent.com/63735432/236591934-4b4e6c98-40a6-4360-a51e-1e95b62b1232.png">
> 
> 

How are you doing it? Please provide some detail...

**Comment by JOHLC** [comment]
> > ITS WORKINGGG!!! 👍🏼
> > <img alt="image" width="963" src="https://user-images.githubusercontent.com/63735432/236591934-4b4e6c98-40a6-4360-a51e-1e95b62b1232.png">
> 
> How are you doing it? Please provide some detail...

I am using this theme:  https://github.com/JOHLC/transparentblue

**Comment by blhoward2** [comment]
Weird, applying that theme mine is still not transparent. Are you applying any other code with card-mod outside the theme?

**Comment by yjamal01** [comment]
I can confirm its working for me now too, not using that theme but the ios dark theme and google dark theme

**Comment by blhoward2** [comment]
I was able to make the header transparent but still cannot get the background to show under the header, which was the point of this issue. Your theme is loading a separate header background in only that section as far as I can tell…Sent from my iPadOn May 10, 2023, at 1:44 PM, Joel ***@***.***> wrote:﻿

Weird, applying that theme mine is still not transparent. Are you applying any other code with card-mod outside the theme?

Are you on the latest version of Home Assistant?   Also note: You have to scroll down one for it to show like that.

**Comment by blhoward2** [comment]
What is working, though? Making the header transparent or doing that and
extending the background on the main page under the header? You could
always style the header to be transparent.

**Comment by ncodee** [comment]
3 years on-going issue, any updates on this please?

**Comment by ExodusOTH** [comment]
Bumping this. Have not found a way to make the header transparent in-app

**Comment by fenster24** [comment]
@Bergasha This looks great! I haven't worked with card mod before, is this a required custom component? Also, which version of Home Assistant Core are you running?

**Comment by Bergasha** [comment]
@fenster24  it is a requirement mate, just install it in Hacs. I'm running version 2024.3.0

**Comment by fenster24** [comment]
After upgrading to the latest today, my transparent header now works! I didn't make any changes, or add any card mods.

Core
2024.5.3

Supervisor
2024.05.1

Operating System
12.3

Frontend
20240501.1
