### ISSUE TITLE
ZHA Integration configuration header menu disappears when selecting Visualization 

### ISSUE THREAD

**Issue by urbozz** [home-assistant/frontend#7983]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
When looking at the Network Visualization in configurations options for the ZHA Zigbee integration, the header menu disappears which makes it hard to go back to the other configuration options.

## Expected behavior
The header menu should remain allowing navigation back to Network or Groups

## Steps to reproduce
Visit http://homeassistant.local:8123/config/zha/visualization

## System Health

version | 2020.12.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.6
os_name | Linux
os_version | 5.4.79-v8
arch | aarch64
timezone | Europe/London

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 26 December 2020, 0:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.8
-- | --
update_channel | beta
supervisor_version | 2020.12.6
docker_version | 19.03.13
disk_total | 57.8 GB
disk_used | 7.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (2.6.1), Visual Studio Code (2.9.1), UniFi Controller (0.19.3), SSH & Web Terminal (7.8.0), AppDaemon 4 (0.3.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
mode | auto-gen
resources | 0

</details>

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by dmulcahey** [comment]
Are you on mobile?

**Comment by dmulcahey** [comment]
![3B37E30F-644C-4BD8-A685-D5EE529F473A](https://user-images.githubusercontent.com/1335687/102230354-c67f4200-3eba-11eb-88a9-cd72674eb63d.png)


I assume you mean the bottom tabs if you’re on mobile?

**Comment by urbozz** [comment]
I am looking from a desktop perspective, but yes on the bottom if mobile. 

See screenshots below - as i go into the configuration and then when I click visualisation, i loose the top menu header.

![Screenshot 2020-12-15 at 15 22 53](https://user-images.githubusercontent.com/26883465/102234756-85525680-3ee9-11eb-8453-79c511a4c2fe.png)
![Screenshot 2020-12-15 at 15 23 08](https://user-images.githubusercontent.com/26883465/102234763-86838380-3ee9-11eb-8677-ed11fd1dded7.png)

**Comment by urbozz** [comment]
This UX issue still exists in 2021.3.4.

**Comment by dmulcahey** [comment]
@urbozz fixed... sorry this took so long for me to get to.
