### ISSUE TITLE
Sorting by area is mixed up, not working

### ISSUE THREAD

**Issue by Fossy777** [home-assistant/frontend#7984]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When going to configuration, entities and trying to sort for areas, it is mixed up. All other sortings work.
![image](https://user-images.githubusercontent.com/62857275/102220766-8bdcd000-3ee1-11eb-882e-6ea7792a9f35.png)

There are (as you can see in screenshot) even gaps between the lines in this column.
![image](https://user-images.githubusercontent.com/62857275/102222480-c0ea2200-3ee3-11eb-97c0-0ee3421cf042.png)

## Expected behavior

Alphabetical sorting works also for areas, not only for Entity-ID, name, integration and status.

## Steps to reproduce

click on configuration, then on entities, click on "area" column to sort for it, see the unsorted result

## System Health

version | 2020.12.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.6
os_name | Linux
os_version | 5.4.79-v7
arch | armv7l
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4983
Installed Version | 1.9.0
Stage | running
Available Repositories | 756
Installed Repositories | 20

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.8
-- | --
update_channel | stable
supervisor_version | 2020.12.6
docker_version | 19.03.13
disk_total | 28.6 GB
disk_used | 8.7 GB
healthy | true
supported | true
board | rpi3
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.3.0), HomeMatic CCU (10.3), Check Home Assistant configuration (3.6.0), File editor (5.2.0), Terminal & SSH (8.10.0), Mosquitto broker (5.1), motionEye (0.10.2), SSH & Web Terminal (7.8.0), Log Viewer (0.9.1), Home Assistant Google Drive Backup (0.102.0), ESPHome (1.15.3), AppDaemon 4 (0.3.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
mode | storage
views | 6
resources | 9

</details>

- Home Assistant release with the issue: 2020.12.0
- Last working Home Assistant release (if known): unknown
- Browser and browser version: tested on Chrome and Firefox, both latest
- Operating system: Windows

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
Issue reproduced and root cause found. Working on a fix.
