### ISSUE TITLE
Plant Status Card Is Not Scalable 

### ISSUE THREAD

**Issue by Kackerlacka** [home-assistant/frontend#7988]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
Plant Status Card parameters have too much padding and thus cannot be properly scaled in Lovelace. If used in 2x2 grid, the four parameters (temperature, illuminance, conductivity, moisture) are scrunched together with lots of padding around the outside, making it difficult to read. If used in a 3x3 grid, it is completely unreadable.

## Expected behavior
The four parameters should automatically scale to the width of the card as the card shrinks, leaving minimal left and right padding.

## Steps to reproduce
1. Add a grid card with 2 or 3 columns in Lovelace
2. Add two or more Plant Status cards connected to plants.

## Environment

- Home Assistant release with the issue: 2020.12.0
- Last working Home Assistant release (if known): None
- Browser and browser version: Google Chrome (87.0.4280.88 up to date) and Official Android App (3.0.2-full)
- Operating system: Windows, Android

## State of relevant entities

```type: grid
columns: 2
cards:
  - type: plant-status
    entity: plant.lemon_tree
  - type: plant-status
    entity: plant.lime_tree
  - type: plant-status
    entity: plant.banana_tree
  - type: entities
    entities:
      - entity: switch.lemon_light
        name: Lemon
      - entity: switch.lime_light
        name: Lime
      - entity: switch.banana_light
        name: Banana
    title: Plant Lights
    show_header_toggle: false
```
![image](https://user-images.githubusercontent.com/43557714/102262561-2203fc80-3ec8-11eb-9cfe-c1ae94fc9213.png)

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by chemelli74** [comment]
**OT** How did you remove the name from the plant-status card ? **/OT**
