### ISSUE TITLE
Setting state on a slider with value 0 does not set the item to YAML

### ISSUE THREAD

**Issue by tpazderka** [home-assistant/frontend#7993]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When setting automation for Somfy blinds position, I am presented with a slider to set the target position. When it is set to zero and I try to save the automation, I get `Message malformed: value is not allowed for dictionary value @ data['type']`.

When I inspect the YAML, I see that the `position` is missing since it's value is 0.
## Expected behavior
Fill in the required `position` argument although it's value is 0.

## Steps to reproduce
1. Add Somfy integration
2. Navigate to Automations
3. Create an automation with action `Device` and select one `Somfy` blind device and set its position to 0
4. Save the Automation

## Environment
Docker

- Home Assistant release with the issue: 2012.12.0
- Last working Home Assistant release (if known): The previous one
- Browser and browser version: Chrome/Firefox
- Operating system: Linux

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
device_id: XXX
domain: cover
entity_id: cover.XXX
type: set_position
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by rexbron** [comment]
I've encountered the same issue with both the HA Android App and Brave (Chromium based) broswer. 

Home Assistant release with the issue: 2021.1.1
Last working Home Assistant release (if known): Unknown. 
Browser and browser version: HA Android App and Brave
Operating system: Android
