### ISSUE TITLE
Entity areas ignored for default grouping on Overview page

### ISSUE THREAD

**Issue by GeekGoneOld** [home-assistant/frontend#7996]
## Checklist

- [ X] I have updated to the latest available Home Assistant version. (2020.12.07)
- [ X] I have cleared the cache of my browser.
- [ X] I have tried a different browser to see if it is related to my browser. (Firefox and Edge)

## The problem

Entity area (introduced in 2020.12) is ignored in Overview page when Lovelace creates default grouping.  Group area only is used.
## Expected behavior

Correct behaviour should be to use entity area if set otherwise use group area if available in that order.  This behaviour exists with entities of a group (tested with a zwave node) and entities without a group (tested with sensor/binary_sensor/cover templates).  See screenshot displaying "Front Doorlock Last Action" (a template sensor) at the top (near upper left corner of popup) when it should be with the Front Hall group on the left (per the Area shown in popup).
![Screenshot 2020-12-16 115745](https://user-images.githubusercontent.com/8504828/102381263-ff8ce480-3f96-11eb-81ae-ea87856c1ba5.png)

## Steps to reproduce

Add a binary sensor template and make sure it has a unique entity_id
In the UI change the entity area to any area that already has some entities with that group area
Flush browser cache and call up the Lovelace Overview and the binary sensor will not be in the area group on the page.
## System Health

version | 2020.12.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.6
os_name | Linux
os_version | 5.4.79-v7
arch | armv7l
timezone | America/Toronto

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4971
Installed Version | 1.9.0
Stage | running
Available Repositories | 683
Installed Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.8
-- | --
update_channel | stable
supervisor_version | 2020.12.6
docker_version | 19.03.13
disk_total | 28.6 GB
disk_used | 5.6 GB
healthy | true
supported | true
board | rpi3
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.2.0), Mosquitto broker (5.1), OpenZWave (0.7.1), Duck DNS (1.12.4), SSH & Web Terminal (7.8.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
mode | auto-gen
resources | 0

</details>
- Home Assistant release with the issue: 2020.12.6 and newer
- Last working Home Assistant release (if known): N/A
- Browser and browser version: FireFox 83.0 x64 and Edge 87.0.664.60 x64
- Operating system: Windows 10 Pro Version 10.0.18363 Build 18363

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
If this happens in the auto-generated default dashboard, then probably a duplicate of this one? https://github.com/home-assistant/frontend/issues/7991

**Comment by GeekGoneOld** [comment]
I'm very embarassed.  It seems to be the identical issue and the other one was before this.  I thought I checked the list before making this but either I missed it or the other was entered first while I was entering this one.  Many apologies.  I will close this one.
