### ISSUE TITLE
device_class doesn't set Unit on MQTT sensor

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#7997]
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

Not sure if this would be a big, or a feature request, but must admit only today I realized that these (Mqtt) sensors with a device_class set, didn't get a unit. Not a huge issue correcting that using manual setting it, but going to the next paragraph below:
## Expected behavior

(continuing the above) It does seem obvious when one sets a device_class, especially temperature and battery, the appropriate unit (even localized) would be set

## Steps to reproduce

simplest of yaml configurations for an Mqtt binary_sensor:

```
  - platform: mqtt
    name: Attic flood sensor battery level
    state_topic: ha_zwave/sensor/attic_flood_sensor_battery_level/state
    unit_of_measurement: '%' <---- needs this
    device_class: battery

  - platform: mqtt
    name: Attic flood sensor temperature
    state_topic: ha_zwave/sensor/attic_flood_sensor_temperature/state
    unit_of_measurement: °C <---- needs this
    device_class: temperature

```

## Environment

- Home Assistant release with the issue: 2020.10.0
- Last working Home Assistant release (if known): not sure
- Browser and browser version: all
- Operating system: Home Assistant OS

## State of relevant entities

```yaml
  - type: entities
    title: Attic flood sensor
    entities:
      - sensor.attic_flood_sensor_battery_level
      - sensor.attic_flood_sensor_temperature
```

<img width="411" alt="Schermafbeelding 2020-12-16 om 23 08 37" src="https://user-images.githubusercontent.com/33354141/102412392-b1f29500-3ff3-11eb-8398-0e8b0482d8af.png">

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
I am not sure if that is actually something for the frontend. Looking through the code there is currently nothing where the frontend is handling any units. All of that info has to come from the backend. If I look at my gauge display for free system memory only the backend knows whether we are talking about percent of free memory or MB/GB/... 

The same applies to your battery. That could be percent (as it seems to be in your case), but it might also be remaining time in minutes or hours. The frontend cannot infer that. Instead the sensor has to provide that information.

**Comment by Mariusthvdb** [comment]
Yeah, my thought was the unit would be set by the device_class, like it sets an icon.

Apparently it doesn't, so will take this to core then ?

**Comment by spacegaier** [comment]
The icon is determined by the frontend, since there is a rather clear link: If we know that the device class is "battery" then we battery icon will most likely fit. But again the frontend does not know whether we are talking about battery percents or minutes, hours, ...

So from my perspective this would be a core topic. But even then, how should the HA sensor know what unit it gets from the MQTT? Is there a way to reliably infer that? Only the actual device or you as the user setting up the sensor would probably know that.

**Comment by frenck** [comment]
What is listed in the entity in the dev tools?

**Comment by Mariusthvdb** [comment]
@frenck right now it is accordingly and manually set, so it shows that. Without the actual unit_of_measurement customization/addition, it shows nothing.

@spacegaier it shouldn't get the unit from the MQTT, my issues with the device_class. (maybe shouldn't have mentioned MQTT at all, sorry if that causes confusion)

Must confess I haven't ever seen a battery_level sensor set in anything else than %, and for sure, the temperature should be taken from the configs locale.

meaning, if I set a device_class: temperature, it would see I live in The Netherlands and sets an automatic Celcius unit, alongside the icon. As would go for the other available options (which, btw, are already used in the core config parameters)

<img width="628" alt="Schermafbeelding 2020-12-22 om 15 15 28" src="https://user-images.githubusercontent.com/33354141/102897597-90b4fd00-4468-11eb-9eca-299282648425.png">

if they are there, why not use them in the appropriate device_classes, like temperature in this case.

**Comment by frenck** [comment]
@Mariusthvdb Could you provide a dump from the dev tools in the incorrect situation please. Thanks 👍

**Comment by Mariusthvdb** [comment]
sure:
<img width="1003" alt="Schermafbeelding 2020-12-22 om 15 31 51" src="https://user-images.githubusercontent.com/33354141/102899208-dd99d300-446a-11eb-9b11-2d8be43c8f18.png">
<img width="1002" alt="Schermafbeelding 2020-12-22 om 15 32 02" src="https://user-images.githubusercontent.com/33354141/102899211-decb0000-446a-11eb-982c-4d2c085c9123.png">

**Comment by frenck** [comment]
So this makes sense?

As in, a class of the device doesn't determine the unit of measurement...

For example, if the device class would be energy for a sensor, what would the unit of measurement be? Joule? Kilowatt-hour? watt-hour? What if it wasn't electricity but, e.g., natural gas?

**Comment by Mariusthvdb** [comment]
I wasn't talking about all classes, but these 2 only, temperature and battery_level (hence percentage). Totally willing to change the topic title, which is confusing.

you're right this isn't conclusive for several other classes, but at least these 2 seems rather obvious?

**Comment by frenck** [comment]
Batter levels can be expressed in amps as well. And while the temperature is mostly standardized based on core settings, an integration can sill choose to provide a temperature in, e.g., Kelvin, Rankine of Réaumur (which are valid units).

**Comment by Mariusthvdb** [comment]
Ha one learns everyday, had to google that https://nl.m.wikipedia.org/wiki/Réaumur

Seems rather out of context for HA, but I understand a device_class won't set a unit by design.

Thanks for looking into it for me, both.

Happy holidays!

**Comment by frenck** [comment]
> Seems rather out of context for HA

hehe that one, yeah, but the point is, device classes shouldn't control unit of measurement :)

**Comment by spacegaier** [comment]
@Mariusthvdb So can this issue then be closed since not something the frontend can do (and neither the backend for that matter, since device class cannot reliably control the unit)?

**Comment by Mariusthvdb** [comment]
Yes, but the mobile app won't allow me to...

**Comment by Mariusthvdb** [comment]
It did ;-) was a hidden option ...
