### ISSUE TITLE
Custom cards not found

### ISSUE THREAD

**Issue by davidgontier** [home-assistant/frontend#8002]
Hi. I've installed the latest version of HA today. I hoped that it would solve my problem, but unfortunately not.

I installed some custom cards with HACS, which are located in the usual www/community/... but I cannot find them in my lovelace.

I have activated the "Advanced mode", and in Configuration/Lovelace/Ressources, the cards appear. However, if I go to States/three dots/Modify/ Add a card, they do not appear. Am I missing something?

# log 
---------------------------

(several unrelated warnings, and then this line)

2020-12-17 18:32:17 ERROR (MainThread) [frontend.js.latest.202012120] http://192.168.0.15:8123/lovelace/myhome:0:0 Uncaught

# configuration.yaml
---------------------------

My configuration file is simply

```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
input_select: !include_dir_merge_named input_select/

# frontend
frontend:
  themes: !include_dir_merge_named themes

# This is now commented, but I tried this bit, and it did not work better.
#  mode: storage
#  resources:
#    - url: /hacsfiles/button-card/button-card.js
#      type: module
#    - url: /hacsfiles/dual-gauge-card/dual-gauge-card.js
#      type: module
#    - url: /local/bc.js
#      type: module
```

**Comment by iantrich** [comment]
Use the forums or Discord for support. This is not a bug, you just need to manually add them.
