### ISSUE TITLE
Adding of new language - Bulgarian

### ISSUE THREAD

**Issue by tkulev** [home-assistant/frontend#8007]
Hello,

I would like to request adding "Bulgarian" to the list of translations at Lokalise,

English Name: Bulgarian
Native Name: български

Thank you!

**Comment by spacegaier** [comment]
Definition in HA already exists: https://github.com/home-assistant/frontend/blob/c1965492d99654ef5c43267cf2917c4ded885134/src/translations/translationMetadata.json#L9-L11

@bramkragten So probably only the lokalise project is missing.

**Comment by spacegaier** [comment]
@tkulev I just checked and there already is a Bulgarian lokalise project set up, so everything should be in place: https://app.lokalise.com/project/3420425759f6d6d241f598.13594006/?view=single&reference_lang_id=640&single_lang_id=781
