### ISSUE TITLE
all template sensors show Unknown during startup while already available in template editor

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#8009]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
During startup, all cards with template sensors shows these as unavailable, as does the developer-tools/state while in fact they are already available to the system, when checking these templates in developer-tools/template.

<img width="479" alt="Schermafbeelding 2020-12-18 om 16 07 40" src="https://user-images.githubusercontent.com/33354141/102629476-84206400-414b-11eb-88a7-9e6d3e0074bd.png">

<img width="1441" alt="Schermafbeelding 2020-12-18 om 16 21 28" src="https://user-images.githubusercontent.com/33354141/102630701-28ef7100-414d-11eb-8a8d-4f03f6927450.png">

<img width="916" alt="Schermafbeelding 2020-12-18 om 16 21 19" src="https://user-images.githubusercontent.com/33354141/102630725-30af1580-414d-11eb-805e-405f07aba35e.png">

and

<img width="472" alt="Schermafbeelding 2020-12-18 om 16 16 30" src="https://user-images.githubusercontent.com/33354141/102630124-70c1c880-414c-11eb-86f8-9bdcc5f93443.png">

<img width="1415" alt="Schermafbeelding 2020-12-18 om 16 14 48" src="https://user-images.githubusercontent.com/33354141/102629980-3a844900-414c-11eb-9068-ecb9f70b8c84.png">

to show but a few

## Expected behavior

Would be really nice if the already available template sensors would be available in the states, and show up in the frontend
## Environment

- Home Assistant release with the issue: 2020.12.1
- Last working Home Assistant release (if known): ?
- Browser and browser version: all
- Operating system: Home assistant OS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```
no errors
## Additional information
 is a generic issue on all template sensors, so no specific yaml is helping here.

**Comment by iantrich** [comment]
The template editor is not equivalent to a template sensor and their availability are not comparable. The editor is a websocket connection to the backend. The sensors are on the backend and generate state change events.

**Comment by Mariusthvdb** [comment]
but why, when the template would be available in the editor, couldn't it be available in the frontend?

int it possible to have the frontend load the available backend sensors during startup?
