### ISSUE TITLE
entities card with two-line state overlaps secondary_info

### ISSUE THREAD

**Issue by rodpayne** [home-assistant/frontend#8017]
`entities` card with two-line state overlaps secondary info:

![image](https://user-images.githubusercontent.com/28266684/102695531-335d4980-41e5-11eb-94c0-e2b77ca3672c.png)

**Comment by spacegaier** [comment]
In general this "overlapping" is okay. But there are a few things that I tweaked with the linked PR:
1. Secondary info will now also use ellipsis, so it doesn't feel cut off as much. Looks less "wrong" then 😄 .
2. Gave the name more space overall => address value will use more of the second line (where currently it only says "United States").
3. Add a bit of space between the name and the value (doesn't really come into effect in this example).
