### ISSUE TITLE
UI Bug with Automation YAML Editor

### ISSUE THREAD

**Issue by nzepp** [home-assistant/frontend#8018]
I seem to have stumbled across a bug in the UI YAML Editor. The use case is the following: I have automations I am attempting to duplicate, I copied the YAML from the working automation and want to paste it into the YAML editor for a new (blank) automation. When I do so the YAML editor disappears from the UI after I highlight and delete the default YAML. I can no longer interact with the YAML editor.

Steps to reproduce:

1. Create a new blank automation
2. Switch to YAML mode
3. Highlight default YAML and delete the code

As a workaround, you can leave at least one line of the default YAML and then go back and delete it once you paste or type the desired automation YAML into the editor.

**Comment by zsarnett** [comment]
Please fill out the issue template.
