### ISSUE TITLE
Cast.show_lovelace_view is missing the history data

### ISSUE THREAD

**Issue by tosion** [home-assistant/frontend#8027]
I am not sure are these related at all but after updating HassOS 4.14 and later versions lovelace cards lost the history data when casted on Google devices. For instance the card below shows only the state 2.5 C but not the graph when casted on Google Nest Hub or chromecast unit. With HassOS 4.13 I did not see this problem.

![image](https://user-images.githubusercontent.com/48414735/102689361-171dd480-4206-11eb-8d8a-af636c785939.png)

Version	2020.12.1
Installation Type	Home Assistant OS
Development	false
Supervisor	true
Docker	true
Virtual Environment	false
Python Version	3.8.6
Operating System Family	Linux
Operating System Version	5.4.83
CPU Architecture	x86_64
Timezone	Europe/Helsinki

Host Operating System	Home Assistant OS 5.8
Update Channel	stable
Supervisor Version	2020.12.7
Docker Version	19.03.13
Disk Total	109.3 GB
Disk Used	11.7 GB
Healthy	true
Supported	true
Board	intel-nuc
Supervisor API	ok
Version API	ok
Installed Add-ons	Samba share (9.3.0), File editor (5.2.0), Check Home Assistant configuration (3.6.0), Network UPS Tools (0.3.1), NGINX Home Assistant SSL proxy (3.0.1), Terminal & SSH (8.10.0), SSH & Web Terminal (7.8.0), Grafana (5.3.6), Duck DNS (1.12.4), deCONZ (6.6.1), InfluxDB (3.7.9)

**Comment by spacegaier** [comment]
I have no experience with the mentioned casting devices, so this question might be a bit stupid: Is there any way to check for rendering errors / console output in something similar to the browser dev tools?

Also can you definitively rule out caching issues?

**Comment by tosion** [comment]
Thanks a lot for your response!

To be honest I am not able to judge or rule out any root cause for this. It worked great but stopped showing the history data. I am not only one having this issue. People report same issue for example in "Home Assistant Cast"- thread:

https://community.home-assistant.io/t/home-assistant-cast/130280/280

https://community.home-assistant.io/t/home-assistant-cast/130280/282

I sure would like to help solving this if someone can point the direction ....

**Comment by tosion** [comment]
This problem is still existing. I do not know the root cause but if it helps anyone to solve this i can share my experience:

This works but it need random number of restarting the core. From the top of my hat I can say that maybe around once in twenty restart lovelace casting starts to work correctly. Right now my only solution to keep it running is to avoid core restart ac much as possible.

Based on my experience should this issue be moved back to home-assistant/core. You guys know better ;-)

**Comment by giuseppeg88** [comment]
I have the same problem.

## System Health

version | core-2021.3.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.99
arch | x86_64
timezone | Europe/Rome

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.12
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.0
docker_version | 19.03.13
disk_total | 28.8 GB
disk_used | 11.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
api_endpoint_reachable | ok

</details>

**Comment by tosion** [comment]
Yes, it is still a problem - earlier you were able to get this working with multiple restarts - now I can not get it running no matter how many restarts I do. I opened a issue also in core side:

https://github.com/home-assistant/core/issues/49478#issuecomment-823278379

I would appreciate to hear if someone could confirm this feature to work correctly?

![image](https://user-images.githubusercontent.com/48414735/115965123-3ae48480-a530-11eb-82e6-97baa0fb9531.png)

**Comment by SurfingSpider** [comment]
I can confirm that I also do not see history data when casting to a chromecast or lenovo smart screen. 
I just set this up but no restarts seam to fix the issue.

**Comment by surf2fast** [comment]
The problem still exists.
Core Version
core-2021.5.5

Several restarts did not help.

Hopefully solved soon... Regards,

**Comment by SurfingSpider** [comment]
The work around I found was to Cast one lovelace view then set a delay for 10 seconds then cast the actual lovelace view you want to see. Seams to work the second time around (most of the time).

**Comment by Roglogg** [comment]
I have the same problem with HA 2021.7.2
