### ISSUE TITLE
Uptime badge showing date instead of relative time

### ISSUE THREAD

**Issue by tyjtyj** [home-assistant/frontend#8030]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem
Uptime badge showing timestamp instead of relative time. 

## Expected behavior
Uptime badge show time relative like xxx ago.

## Steps to reproduce
add uptime as badge

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known): 0.18.4
- Browser and browser version: Chrome latest
- Operating system: Win 10, android

## State of relevant entities

```yaml
- platform: uptime
  name: 'Hass Uptime'
```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
Did it previously show something other than the timestamp? Given that there is not much space in a badge, basically everything we put int here will get ellipsis during rendering. So I am not sure if an uptime sensor as badge makes really sense to begin with.

If the uptime sensor is used as an entity row, then we show the relative time instead.

**Comment by tyjtyj** [comment]
It shows 0.1 days(unit measurements: day. But this setting has been removed.

**Comment by spacegaier** [comment]
Was that setting on the sensor or on the frontend badge YAML? Could you also select other units? If you were to choose hours the values would get a lot longer.

**Comment by tyjtyj** [comment]
On yaml 0.18.5

```
- platform: uptime
  name: 'Hass Uptime'
  unit_of_measurement: days
```

As part of breakfix in version 2020.12.1, unit of measurement has been removed. The sensor is now timestamp. 

This is how it look like in version 2020.12.1 
![image](https://user-images.githubusercontent.com/5368474/102946157-c276a400-44fa-11eb-8d17-664db52bebc6.png)


This is version 0.18.5
![image](https://user-images.githubusercontent.com/5368474/102946234-0073c800-44fb-11eb-85a5-5df327ecbbe3.png)

**Comment by coolguymatt** [comment]
The same thing happens with the entity card. It also happens for any sensor with device class timestamp.
