### ISSUE TITLE
"Add card" button does not have fixed position

### ISSUE THREAD

**Issue by Sjorsa** [home-assistant/frontend#8034]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
This might be expected behavior so this could also be interpreted as a feature request maybe.
  I feel like it should always be in the lower right hand corner, and not height dependent on the amount of cards in the view. As seen in [this](https://i.imgur.com/aqip8Zo.png) screenshot, it is pretty high on the screen, and in [this](https://i.imgur.com/VT61YWF.png) screenshot it is even below the screen; you need to scroll to see it. 

## Expected behavior
The "Add card" button should always be in the lower right hand corner and be above any cards that might be behind it.

## Environment
Version | 2020.12.1
-- | --
Installation Type | Home Assistant Container
Development | false
Supervisor | false
Docker | true
Virtual Environment | false
Python Version | 3.8.6
Operating System Family | Linux
Operating System Version | 5.4.0-54-generic
CPU Architecture | x86_64
Timezone | Europe/Amsterdam

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by Sjorsa** [comment]
Somehow none of my text got through, but I can still see what I typed when I edit the post...

**Comment by spacegaier** [comment]
@Sjorsa Then probably it is marked as a comment inside `<!-- [...] -->`.

**Comment by Sjorsa** [comment]
@spacegaier yes, I figured that out :P I deleted my comment

**Comment by Sjorsa** [comment]
This has not been changed yet, If I get some time in the near future I might try to fix it myself, if I can manage to set up a test environment.

**Comment by Sjorsa** [comment]
This has not yet been changed
