### ISSUE TITLE
"Jinja2 template documentation" leads to 400 in Developer Tools -> Template

### ISSUE THREAD

**Issue by pashdown** [home-assistant/frontend#8037]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

"Jinja2 template documentation" leads to 400 in Developer Tools -> Template.  

http://jinja.pocoo.org/docs/dev/templates/ leads to a 400 "Bad Request"

Maybe it should be replaced with https://jinja2docs.readthedocs.io/en/stable/templates.html

## Steps to reproduce

1. Navigate to http://homeassistant.local:8123/developer-tools/template
2. Click on "Jinja2 template documentation"
## Environment

- Home Assistant release with the issue: 2020.12.1
- Last working Home Assistant release (if known): unknown
- Browser and browser version: Firefox 83.0
- Operating system: macOS 11.1

**Comment by spacegaier** [comment]
The link resolves to https://jinja.palletsprojects.com/en/master/templates/ for me. Can you please test again if the issues persists for you? Perhaps you need to clear your DNS cache.

**Comment by pashdown** [comment]
Tried a different browser and the link was correct.  Shift-reload on Firefox doesn't clear out the old link.  Not sure why, but it is unrelated to this bug report, so I'm closing it out.
