### ISSUE TITLE
No autoplay of camera streams in lovelace anymore with cameras that stream audio!

### ISSUE THREAD

**Issue by chheiss** [home-assistant/frontend#8041]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

I guess that is the problem! AutoPlay does not work on iPad anymore. It plays when clicking on the video and opening it, then pressing the play button. But it used to play right away in the video card, and when opening it started playing by itself, without pressing the play button.
This prevents playing directly in the picture-glance card, as there is no play option.

## Expected behavior

In a picture-glance (or other camera) card, the live stream started playing by itself. On larger iPads, this does not work anymore.

## Steps to reproduce

Set up new Hassio environment. Set up Unifi NVR and adopt a camera.
Set up Unifi Protect integration or camera RTSP integration.
Picture-glance card does only show still image, not a live stream anymore.
Problem is with iPads only. iPhones, Android and PC browsers workas expected. iPad browsers only show still image.

## Environment

Hassio 2020.12.1

iPads with iPadOS 14.3

Unifi UNVR with latest firmware 1.17.0

## State of relevant entities

```yaml

```

## Problem-relevant configuration

aspect_ratio: 50%
camera_view: live
entity: camera.home_cam_vorgarten
type: picture-entity

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by chheiss** [comment]
Might this be the reason?

Apple: "Video elements that include <video autoplay> play automatically when the video loads in Safari on macOS and iOS, only if those elements also include the playsinline attribute. For more information on inline playback, see Enable Inline Video Playback.

By default, autoplay executes only if the video doesn’t contain an audio track, or if the video element includes the muted attribute. Video playback pauses if the element gains an audio track, becomes unmuted without user interaction, or if the video is no longer onscreen (either by CSS or due to the user scrolling the page)."

**Comment by chheiss** [comment]
Rolled back to Home Asisstant 0.112 from this summer, here it works perfectly. So it is a change between 0.112 and the current version.

**Comment by Phreet** [comment]
I can confirm this behaviour also for other camera streams. I use two Netatmo Presence cameras within my setup, where Lovelace interaction on browser is fine, but when using Android or iOS device, i also have to manually start stream.

Used system:
HA Core: 2020.12.2
HA OS: 5.10
iOS: 2021.1
Android: /

**Comment by uvjustin** [comment]
You say picture-glance but the configuration has picture-entity. Which one is it?
Check that "Low Power Mode" is not enabled on your iPad: https://stackoverflow.com/questions/47655077/autoplay-muted-video-ios-11-2

**Comment by chheiss** [comment]
It is with all cards, not dependent on the card. Glance, Entity, all of them.

**Comment by uvjustin** [comment]
Strange! Does it work on your regular iPads?

**Comment by chheiss** [comment]
Only on the minis. Everything above that, no. And this can easily be reproduced. Fresh setup of Hassio, brand new iPad. Camera with audio capabilities.

**Comment by uvjustin** [comment]
That's good info. Unfortunately I don't have any iPads to test this out on :-( Hopefully someone else can help.

**Comment by briis** [comment]
I can confirm the same behavior but not only for iPads. Even on my Macbook in both Google and Safari, the Livestream is not showing, even if `camera_view: live`.
All my cameras are UniFi cameras, and it does not matter if I use the UniFi Protect integration, or use the Generic Camera Platform, the behavior is the same. All G3 Series cameras won't Live Stream and all G4 Series will live stream. Technically there is a difference with these two types, but I cannot tell exactly what it is.

**Comment by uvjustin** [comment]
While these issues all seem to be with autoplay, they might not be the same problem.
The original issue from @chheiss seems to be a frontend issue which happens with iPads and iPad pros but not with other devices.
The issue from @briis seems to be across all devices but manifests with G4 cameras and not G3 cameras, so it might be some interplay between backend and frontend.
The issue from @Phreet is with Netatmo instead of Unifi sources and only happens on mobile devices and not in browsers.
Unfortunately I don't have the devices/cameras to reproduce any of these issues.

**Comment by chheiss** [comment]
As it turns out now, the issue is not with the Unifi cameras, it is with other cameras as well. Looks like it is an Apple - Home Assistant thing, with Apple iPads not live playing HA streams anymore. The HA streams might need to be fixed.

**Comment by chheiss** [comment]
Anyone looking at this? Might be just a small fix...

**Comment by uvjustin** [comment]
Hmm, from @briis 's edit it looks like his issue is also browser dependent, so the issue is most likely the frontend. Unfortunately autoplay seems a bit tricky across the different browsers.
@chheiss I would guess it has something to do with the attributes/properties that get attached to the video element. If you set up a frontend development environment you can try googling to find out what attributes/properties people use to get autoplay working and try them out in `ha-camera-stream.ts`. Maybe @bramkragten can help you out

**Comment by bramkragten** [comment]
Apple normally doesn't allow auto-loading video/audio on mobile devices without user interaction, but it is surprising that older versions of HA did work...

**Comment by chheiss** [comment]
@bramkragten Do you have any info on what we might do to diagnose? As stated, older HA versions still work, and the problem is only with iPads, not iPhones. It might be connected with HA playing the sound stream now. Can that be turned off for testing?

**Comment by chheiss** [comment]
@uvjustin Is ha-camera-stream.ts a file I should modify?

**Comment by uvjustin** [comment]
Yes that's where I'd start. However, it's not just editing a file - you have to set up a development HA instance which loads the frontend from source or you have to build the frontend and install it on your HA server after every change to see the changes. If you're not familiar with development and don't have a separate dev setup this might be difficult.

**Comment by chheiss** [comment]
Any chance a developer might have a look at it?

**Comment by chheiss** [comment]
Any news here?

**Comment by chheiss** [comment]
Strangely enough, it started working again today, after upgrading HA to 2021.5.0.
Is that accidentally, or has something changed?

**Comment by briis** [comment]
Nothing has changed in the Integration with regards to this issue, but it seems that something has changed in HA.  😊

**Comment by steppel** [comment]
I'm facing the same problem but only on Android. I use the HA app on iOS and Android and only on the Android tablet videos called with more_info are not auto playing. I need to run on the Android tablet since it's wall mounted and I want to popup the camera stream when motion is detected.

**Comment by MindFreeze** [comment]
I have this issue on all of my Android and Windows devices.  Please someone address it. How do we autoplay?

**Comment by jespermeyer** [comment]
I have this problem as well. My Unifi G1 cam streams, but the newer G3 cam doesn't.
