### ISSUE TITLE
Some theme variables on views overridden by main dashboard theme

### ISSUE THREAD

**Issue by kaizersoje** [home-assistant/frontend#8044]
## Checklist

- [ x] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

I have set a different theme on one of the views. However, it seems some of the CSS variables are being set by the theme on the dashboard the view belongs to.  One such variable is `--primary-text-color`

## Expected behavior

It should use the variables based on the theme set on each view.

## Environment

version: 2020.12.1
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 5.4.79-v7
arch: armv7l

host_os: Home Assistant OS 5.9
update_channel: stable
supervisor_version: 2020.12.7
docker_version: 19.03.13
disk_total: 219.4 GB
disk_used: 12.9 GB
healthy: true
supported: true
board: rpi3
supervisor_api: ok
version_api: ok

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml
title: Vacuum
icon: mdi:robot-vacuum
theme: Caule Black Blue
```
Does not use the `--primary-text-color` variable for some cards from this theme and uses the one from the theme set on the dashboard.

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by kaizersoje** [comment]
Any update on this?

**Comment by spacegaier** [comment]
> 
> 
> Any update on this?

Do you see an update? No? Then obviously the answer is "no" 😉.
