### ISSUE TITLE
Firefox password manager does not save username

### ISSUE THREAD

**Issue by Erriez** [home-assistant/frontend#8046]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

The Firefox build-in password manager does not recognize and save the username at the login page.

## Expected behavior

Fill-in username and password on the login page. The Firefox password manager should recognize this to Save both username and password. Currently, only the password is saved and not the username.

## Steps to reproduce

![HomeAssistantFirefoxSaveLogin](https://user-images.githubusercontent.com/8849873/103276378-a2e1ee80-49c6-11eb-9e82-70b14c17164d.gif)

## Environment

- Home Assistant release with the issue: Unknown
- Last working Home Assistant release (if known): Unknown
- Browser and browser version: Latest (84.01)
- Operating system: Ubuntu 18.04 / 20.04 and Windows 10

## State of relevant entities

Not applicable.

## Problem-relevant configuration

Not applicable.

## Javascript errors shown in your browser console/inspector

Not applicable.

## Additional information

See screen capture to reproduce the problem.

**Comment by spacegaier** [comment]
Probably related to this https://github.com/home-assistant/frontend/issues/3133

**Comment by spacegaier** [comment]
I had looked into that issue a couple of weeks ago, but apparently did not save my comment here.

Even if I set the `autocomplete` of the field to `username` (or `name` or `id` for that matter), Firefox does not want to store them.
