### ISSUE TITLE
Blueprints - Cannot set number selector to 0 when using slider

### ISSUE THREAD

**Issue by trankillity** [home-assistant/frontend#8054]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
When using the `slider` mode for the `number` selector, you cannot slide the result to 0 if 0 is the minium. You must manually enter it. 

## Expected behavior
Able to use UI slider to select 0

## Steps to reproduce
Use the default, included `motion_lights.yaml` Blueprint to create an automation. Slide the "Wait time" to 0.

## Environment
- Home Assistant release with the issue: 2020.12.2
- Last working Home Assistant release (if known): None
- Browser and browser version: Chrome Version 87.0.4280.88
- Operating system: Windows 10 64-bit

## Additional information
Seems to be specifically when 0 is the minimum value of the slider where this issue is present. Adjusting the slider range up above 0 allows you to select the minimum value, and also setting it below 0 allows you to select the minimum (while also being able to select 0 above the minimum).

**Comment by spacegaier** [comment]
Workaround is setting 0 via the input box next to the slider, since that works fine.

**Comment by trankillity** [comment]
> Workaround is setting 0 via the input box next to the slider, since that works fine.
Yep, that's what I've been doing for now. Thanks for the PR! Blueprints have a lot of potential!
