### ISSUE TITLE
Line graph card loose 24h older data on auto-update when showing 48h

### ISSUE THREAD

**Issue by BeePerNet** [home-assistant/frontend#8055]
## Checklist

- [ X] I have updated to the latest available Home Assistant version.
- [ X] I have cleared the cache of my browser.
- [ X] I have tried a different browser to see if it is related to my browser.

## The problem

When line graph card update data list, it loose the 24h old and older data.
This happen when using when using a 48h Hours to Show (Optionnal) parameter.

## Expected behavior

Having the same graph with updated data. Correct chart plot for full 48h, not just 24h.

## Steps to reproduce

1. Create any line chart card.
2. Show/display the card
3. Wait for refresh
4. Bug starts to appear after ~1min, ~15min for all). Seems to be at the programmed JS trigger

## Environment

- Home Assistant release with the issue: Supervised Debian 2020.12.7
- Last working Home Assistant release (if known): Unknown
- Browser and browser version: Chrome 87.0.4280.88 & Firefox 84.0.1 & Chromium 86.0.4240.197
- Operating system: Windows 10 19042.685 & Debian 10.7 on RPi 4 & Debian 10.7 on x64

## State of relevant entities

State: all ok except: Last updated: Invalid Date

Picture after full browser update:

![image](https://user-images.githubusercontent.com/46988275/103396947-f443c800-4b03-11eb-9d11-6a31d0d49215.png)

Picture after chart auto refresh

![image](https://user-images.githubusercontent.com/46988275/103396969-0d4c7900-4b04-11eb-9893-d4368d6dfd0d.png)
![image](https://user-images.githubusercontent.com/46988275/103397102-c6ab4e80-4b04-11eb-9aec-77477f302c77.png)

## Problem-relevant configuration

Line graph card:
```yaml
  - type: sensor
    entity: sensor.outside_ds_temperature
    graph: line
    detail: 2
    hours_to_show: 48
```

* (Outside & Outside DS temperature) & (MPL3115 pressure kPa & temperature): MQTT using Discovery
* MPL3115 hPa: sensor template: (states('sensor.mpl3115_pressure') | float * 10) | round(2)
* Environnement Canada: Weather platform environment_canada 
* Institute: Meteorologisk institutt integration
* APC: Network UPS Tools (NUT) integration

## Javascript errors shown in your browser console/inspector

```txt
None relevant
```

## Additional information

If i'm correct, when the graph is updating data, it does not get the full data array. (If yes, a code reusability is missing.)

It seems that only last data is received and the code clean iteself (old data that do not need to be plotted/shown anymore). When the code is cleaning old data, it uses the 24h default configuration rather than the 48h configuration option of the card. Then cleaning data between the 48h and 24h offsets.

**Comment by maweki** [comment]
I have a sensor card for the last 14 days where the same is happening. (Pictures after reload of the page and after update of the card data):

![Bildschirmfoto von 2021-01-02 13-56-38](https://user-images.githubusercontent.com/613272/103458065-d7c2ae00-4d04-11eb-8897-6c0c1b1f2509.png)
![Bildschirmfoto von 2021-01-02 14-05-41](https://user-images.githubusercontent.com/613272/103458066-d85b4480-4d04-11eb-96ad-cae42ec1a150.png)

**Comment by spacegaier** [comment]
I can confirm the issue. Working on a fix.
