### ISSUE TITLE
Deselect all entities after removal

### ISSUE THREAD

**Issue by Erriez** [home-assistant/frontend#8056]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Selected entities for removal are still selected after removal.

## Expected behavior

Deselect all entities after removal.

## Steps to reproduce

![HomeAssistantRemoveEntities3](https://user-images.githubusercontent.com/8849873/103414455-55a87d00-4b7e-11eb-96b9-0d1c4ca9ba3f.gif)

## Environment

- Home Assistant release with the issue:  Home Assistant OS: 2020.12.1; Home Assistant OS 5.8
- Last working Home Assistant release (if known): Unknown
- Browser and browser version: Any browser
- Operating system: Not applicable

## State of relevant entities

Selected entities are in `Restored` state.

## Problem-relevant configuration

Not applicable.

## Javascript errors shown in your browser console/inspector

Not applicable.

## Additional information

See screen capture.

**Comment by spacegaier** [comment]
The coding to do so is there, but it seems to sometimes not take effect (immediately). I also noticed that if I just click the checkbox to either select or deselect all items, it sometimes takes a few seconds until shown in the UI or until I start scrolling the table. Might be related.

**Comment by bramkragten** [comment]
Fixed
