### ISSUE TITLE
The more-info-cover dialog does not properly support tilt control for one-way communication protocols

### ISSUE THREAD

**Issue by dzukero** [home-assistant/frontend#8074]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Currently the only way to display the tilt control UI for covers is to support setting tilt position.  There are covers that use one-way communication protocols (such as Somfy RTS venetian blinds) which support tilt control but not tilt position.  Neither of the current options for them works well:
- add SUPPORT_SET_TILT_POSITION to supported_features without actually supporting it.  The tilt position slider does nothing.
- do not add SUPPORT_SET_TILT_POSITION to supported_features.  Tilt control UI is not shown at all.  Tilt can be controlled with services but not through UI.
- add SUPPORT_SET_TILT_POSITION to supported_features, and build support for it.  Not practical because you have to guestimate the device current position and it depends to too many unknowns such as using a physical remote or buttons, the actual setting of the stop/my button, etc. 

## Expected behavior

The tilt position slider should be shown or not depending on SUPPORT_SET_TILT_POSITION only.  The tilt open, tilt close, and tilt stop buttons should be visible depending on SUPPORT_OPEN_TILT, SUPPORT_CLOSE_TILT, and SUPPORT_STOP_TILT respectively, independently from the tilt position slider.

## Steps to reproduce

The issue came up when adding support for RFY (Somfy RTS) venetian blinds tilt control - https://github.com/home-assistant/core/pull/44309/#pullrequestreview-555937756

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
I "developed" the feature that requires this change (the PR referenced above) but my JavaScript knowledge is close to none and I would really appreciate if someone experienced implements the change in UI.

**Comment by spacegaier** [comment]
I might have a look at the in the next days, since I anyway wanted to check the frontend cover coding as my own blinds do not work as intended currently via the UI.

**Comment by spacegaier** [comment]
@dzukero Does this issue still persist? If yes I will reopen the ticket.
