### ISSUE TITLE
Notifications with pictures are historical in companion Android app

### ISSUE THREAD

**Issue by Arvics** [home-assistant/frontend#8079]
## Checklist

- [ yes ] I have updated to the latest available Home Assistant version.
- [ yes ] I have cleared the cache of my browser.
- [ yes ] I have tried a different browser to see if it is related to my browser.

## The problem
In HA companion Android app notifications show historical pictures. In Android pop-up notifications and in Chrome, web browser access to HA are correct pictures. Also in PC Chrome browser webview notifications are correct pictures.

## Expected behavior
In every notification place must be the same notification with the same picture

## Environment

Version | 2020.12.2
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.6
Operating System Family | Linux
Operating System Version | 5.9.15
CPU Architecture | aarch64

Host Operating System | Home Assistant OS 5.9
-- | --
Update Channel | stable
Supervisor Version | 2020.12.7
Docker Version | 19.03.13
Disk Total | 113.9 GB
Disk Used | 22.2 GB
Healthy | true
Supported | true
Board | odroid-n2
Supervisor API | ok
Version API | ok

- Android version: 11
- Phone model: Samsung S20+5G
- Home Assistant Android version: 3.0.2-full

- Home Assistant release with the issue: 2020.12.2
- Last working Home Assistant release (if known): -
- Browser and browser version: Google Chrome 87.0.4280.88 (Official Build) (64-bit)
- Operating system: W10 pro

## State of relevant entities

```yaml

```

## Problem-relevant configuration
![Node_red_call_service_node](https://user-images.githubusercontent.com/65485482/103490029-ea142780-4e7d-11eb-8ab4-565d7ca64a4f.jpg)

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
I didn't tested picture notifications on Android 10 before upgrade to Android 11, because, that time I still didn't use this notifications.
![3_Screenshots 20210104-093014_Home Assistant](https://user-images.githubusercontent.com/65485482/103489922-12e7ed00-4e7d-11eb-829c-d4cbac86d0e0.jpg)

**Comment by Arvics** [comment]
After more testing today - I noticed, when start coming old pictures in PC Chrome browser. My setup for picture names is - counter count until 50 and after it begin counting from 1. As you see could in my original post "Picture Nr:37...38..."
After I closed browser and open again - I had a latest pictures.
But in Android companion app notifications - the same problem, still old pictures.

**Comment by spacegaier** [comment]
Did you verify that under the URL from the notification (on the device where you are experiencing the issue) you do get the correct image (e.g. directly via a browser)? Or is that the screenshot part that's labeled "Mobile Pop-Up Notifications"? 

I haven't checked the frontend code yet, but I don't think we are specifically caching the images here, so the question is whether the device can actually get the correct image from the URL.

**Comment by spacegaier** [comment]
@dshokouhi There is no caching happening in the app's webview that might be preventing the retrieval of the newer image content from the same URL?

**Comment by dshokouhi** [comment]
@spacegaier the app uses the default caching mechanism which I believe is identical to Chrome: https://developer.android.com/reference/android/webkit/WebSettings#LOAD_DEFAULT

**Comment by bramkragten** [comment]
This would be a caching issue of your device or the app, try clearing its cache.

**Comment by dshokouhi** [comment]
You can also check that android system webview is up to date although not sure what difference that will make since the cache APIs have been around since the beginning.

**Comment by Arvics** [comment]
> You can also check that android system webview is up to date although not sure what difference that will make since the cache APIs have been around since the beginning.

Yes, the "android system webview" is the latest, because of Android 11 upgrade.
If I clear out cache of the phone chrome web browser or on the PC Chrome web browser, after that, I will get the latest pictures, if I use web browser. It do not change anything in HA companion app, there I will get historical pictures. 

Using "Service: notify.mobile_app_sm_g986b" I will always get latest pictures, but with "Service: persistent_notification.create" I'll get historical ones.

For the picture number order I use NodeRed count node who will be reset after number 50.

**Comment by dshokouhi** [comment]
> Yes, the "android system webview" is the latest, because of Android 11 upgrade.

This is incorrect because this app is actually updated in the google play store and does not get included as part of a system update.  It has been this way since Android 5.0

> If I clear out cache of the phone chrome web browser or on the PC Chrome web browser, after that, I will get the latest pictures, if I use web browser. It do not change anything in HA companion app, there I will get historical pictures.

What about clearing cache for the android app?

**Comment by Arvics** [comment]
> This is incorrect because this app is actually updated in the google play store and does not get included as part of a system update. It has been this way since Android 5.0

Android System WebView version: 87.0.4280.101 . In Google Play Store are exactly the same version!

> What about clearing cache for the android app?

Yes - I'm sure after that I'll get the latest pictures. But I'm not interested to do it after every 50 pictures.

For this "bug", I better change the way how I name pictures and add additional service who will delete historical pictures from HA /local/..../ folder.

**Comment by dshokouhi** [comment]
> Yes - I'm sure after that I'll get the latest pictures. But I'm not interested to do it after every 50 pictures.

What we are trying to determine here is that if there is a caching issue where would that need to be fixed.  Based on what you have said it sounds like you haven't even tried it to see if clearing cache would update the image.  Its possible it won't because the app's webview has the default caching mechanism.  But we won't know unless you try and tell us.

Are you always using a different URL or does the same URL get reused after some time?  It sounds like you are occasionally reusing the same URL.

As we can see in the cache link I posted above the android app will use a cached resource if it has not been marked as expired.

>Default cache usage mode. If the navigation type doesn't impose any specific behavior, use cached resources when they are available and not expired, otherwise load resources from the network. 


For notifications the android app itself renders the URL as we get it so the processing there is different.

@bramkragten  or @spacegaier can you guys confirm if this particular resource under persistent notifications has an expiration date? Maybe there is a date 24 hours and the user is reusing the same URL within 24 hours?

The only other change we can make here is to set the app to always fetch new data and not use cache.

https://developer.android.com/reference/android/webkit/WebSettings#LOAD_NO_CACHE

**Comment by bramkragten** [comment]
That is not android specific, the persistent notifications are just the frontend.

Add a `?timestamp` or random number to the url.

We have pretty aggressive caching in the frontend for performance reasons.

**Comment by Arvics** [comment]
> What we are trying to determine here is that if there is a caching issue where would that need to be fixed. Based on what you have said it sounds like you haven't even tried it to see if clearing cache would update the image. Its possible it won't because the app's webview has the default caching mechanism. But we won't know unless you try and tell us.

I did a test. "Forced Stop" HA app, after "Clear cache".
Triggered front door camera and got notifications about motion + pictures.
"Service: notify.mobile_app_sm_g986b" - deliver correct (latest) pictures.
"Service: persistent_notification.create" - (to the HA mobile app) deliver historical (sometimes 2 or 3 days old pictures). It is in mixed order. In mobile Chrome browser and PC Chrome browser - latest pictures.

> It sounds like you are occasionally reusing the same URL.

Yes - after 50 pictures. And it could happen in the same day and could be after 2 - 3 days. Depends on motion detection.

**Comment by Arvics** [comment]
I don't know how to attach long screenshot - I apologies if I did something wrong.
Here are visible on mobile HA app notifications.
![Screenshot_20210106-142607_Home Assistant](https://user-images.githubusercontent.com/65485482/103719502-02c33f80-502e-11eb-8f4b-291a8d50a842.jpg)
