### ISSUE TITLE
Input_number defaults option "initial: null"

### ISSUE THREAD

**Issue by smootjenl** [home-assistant/frontend#8082]
## The problem

When creating input_number's in frontend -> settings -> helpers or via configuration.yaml the input_numbers gets the default value "intial: null" added. 

## Environment

version | 2020.12.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.6
os_name | Linux
os_version | 5.4.84
arch | x86_64
timezone | Europe/Amsterdam

host_os | Home Assistant OS 5.9
-- | --
update_channel | stable
supervisor_version | 2020.12.7
docker_version | 19.03.13
disk_total | 58.4 GB
disk_used | 13.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok

- Home Assistant Core release with the issue: 2020.12.2
- Last working Home Assistant Core release (if known): ?
- Operating environment (OS/Container/Supervised/Core): see above tables
- Integration causing this issue: input_number
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/input_number/#-configuration-variables

## Problem-relevant `configuration.yaml`

```
input_number:
  euro_value:
    name: euro_value
    min: 0
    max: 10
    step: 0.01
```

## Traceback/Error logs
none found

## Additional information
forum post about the issue: https://community.home-assistant.io/t/input-number-initial-config-option-help-input-number-persistence-after-reboot/262298

**Comment by spacegaier** [comment]
Cannot reproduce in latest dev => probably fixed since the initial value is no longer in the UI.
