### ISSUE TITLE
Home Assistant Cast - "Souce not supported" error

### ISSUE THREAD

**Issue by clevtool** [home-assistant/frontend#8094]
Trying to set up HA Cast.  Subscribed to nebu.casa and can open remote UI fine.  When I click 'start casting' from: https://cast.home-assistant.io/ it shows all my Google Cast devices, built in TV devices, built in TiVo devices, but each says "Source not supported"  I can cast any chrome tab, youtube... to any of them.  Any idea what might be wrong?
Thanks,
Mike

**Comment by bramkragten** [comment]
This sounds like a support question, please ask the community for help: https://www.home-assistant.io/help/
