### ISSUE TITLE
Improved device & entities list

### ISSUE THREAD

**Issue by tichris0** [home-assistant/frontend#8098]
Like most users; I've added a TON of things to HA and many of my things added a bunch of items in the entity/device lists.  It's honestly become a little unruly to look at the list.  Yes, there's a search feature which is great if you know what you're looking for, but otherwise it's a complete pain in the ass to look at that list.

I'd love to see a better presentation of the lists in general.  How about grouping them logically per room they're assigned in?  Or grouped by the device they come from or by type?  Anything would be nicer than a current list that lets me sort per column.

I'd also love to see the things that aren't current displayed in anything in overview.  This would make it easier to add new items.

**Comment by bramkragten** [comment]
Please use our discussions for feature requests https://github.com/home-assistant/frontend/discussions
