### ISSUE TITLE
Input_number slider not showing unit or number

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#8112]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

As title, in regular Lovelace card. More_info shows correctly. Safari/Mac has this all the time, Chrome and Firefox seem to do better but still not consistent. Home Assistant companion app (iPhone) suffers identical issue.
## Expected behavior

Have an input_number slider always show its state and unit in the Frontend
## Environment

- Home Assistant release with the issue: 2021.1
- Last working Home Assistant release (if known): not sure, think it has been reported before, cant find it in the open issues
- Browser and browser version: All tested Safari/Chrome/Firefox
- Operating system: HA OS, 

## State of relevant entities

<img width="735" alt="Schermafbeelding 2021-01-08 om 10 29 07" src="https://user-images.githubusercontent.com/33354141/103998558-6bc8c580-519c-11eb-9c60-4c712894a018.png">

```yaml

```

## Problem-relevant frontend configuration

```yaml
input_number:
  transition_time:
    icon: mdi:timer
    name: Transition time
    initial: 5
    min: 1
    max: 60
    step: 1
    unit_of_measurement: Sec
```

## Javascript errors shown in your browser console/inspector

```txt
  - type: entities
    title: Light settings
    show_header_toggle: false
    entities:
      - input_number.perc_outdoors_brightness
      - input_number.lighting_timer
      - type: divider
      - input_boolean.animate_master_bedroom_light
      - input_number.transition_time    <-- this is the example from the yaml above
```

## Additional information
<img width="454" alt="Schermafbeelding 2021-01-08 om 10 16 25" src="https://user-images.githubusercontent.com/33354141/103996764-97e34700-519a-11eb-9d1f-24972dd52509.png">

more-info:

<img width="392" alt="Schermafbeelding 2021-01-08 om 10 17 29" src="https://user-images.githubusercontent.com/33354141/103996898-bfd2aa80-519a-11eb-886d-427a797cd241.png">

after some serious refreshing, resizing and reloading, sometimes, and without any reproducible order, the unit and state appear as they are expected:

<img width="487" alt="Schermafbeelding 2021-01-08 om 10 32 29" src="https://user-images.githubusercontent.com/33354141/103999302-01645500-519d-11eb-8af1-a07a6c999104.png">

but this doesn't stick unfortunately.
Please have a look?

**Comment by spacegaier** [comment]
Sounds like a duplicate of https://github.com/home-assistant/frontend/issues/2905 for which there already exists an open PR https://github.com/home-assistant/frontend/pull/8050 since a few days to remove the condition to show the units based on the width of the card.

**Comment by Mariusthvdb** [comment]
yes is is a duplicate, I knew it existed but couldnt find it..... contributed myself there, with almost the same lovelace card: https://github.com/home-assistant/frontend/issues/2905#issuecomment-532984598

hope PR https://github.com/home-assistant/frontend/pull/8050 will fix it then. closing and sorry for the double issue.
