### ISSUE TITLE
Casting display issues

### ISSUE THREAD

**Issue by i00** [home-assistant/frontend#8127]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- **N/A - the browser is built into Google Home** [ ] I have tried a different browser to see if it is related to my browser.

## The problem

When casting tabs in HA there are two issues I have noticed:
- Themes do not apply
- Panel mode tabs have a border (they do not when in the web interface in a browser)

## Expected behavior

Casting works with the same display behavior as HA via a web browser.

## Steps to reproduce

Setup a page with a dark theme in panel mode

Cast to a Google Home.

Theme (background at least) doesn't apply; and borders exist around the edges.

## Environment

- Home Assistant release with the issue: 2021.1.1
- Last working Home Assistant release (if known): Unknown (it used to work quite a while ago)
- Browser and browser version: N/A as on Google Home
- Operating system: Container

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
Can you please fill out the issue template from the frontend repository where this ticket now resides (you can copy it from the "New issue" dialog) to provide some more details reg. the frontend and your configuration / setup.

**Comment by i00** [comment]
Ok ... I have updated with the new template @spacegaier
