### ISSUE TITLE
Home Assistant Cast  does not scale and cannot change between views

### ISSUE THREAD

**Issue by oywino** [home-assistant/frontend#8136]
## Checklist

- [X ] I have updated to the latest available Home Assistant version.
- [X ] I have cleared the cache of my browser.
- [X ] I have tried a different browser to see if it is related to my browser.

## The problem
When I use https://cast.home-assistant.io/ the result is that only the upper left part of my default Lovelace UI is displayed (Home). I was expecting the Cast to scale the image just like a regular cast from Chrome does.
The cast web shows the following: 
![image](https://user-images.githubusercontent.com/18447119/104233251-d8b8b580-5451-11eb-8793-310ea0adcf35.png)
I i try to switch between the tabs (views), the casted image just jumps around in the same view. It doesn't change tab (View) at all.

## Expected behavior
As described in the HA Docs.

## Steps to reproduce
Just connect and cast.

## Environment
Cast Firmware: 1.50.228700
System Firmware: 2.13.4
HA Docker v2021.1.1
Windows 10 20H2
Chrome v87.0.4280.141

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by oywino** [comment]
I at least expected the maintainer of "Cast" to stop by and comment.

**Comment by spacegaier** [comment]
In most cases backend developers focus on the backend and don't have (much) knowledge about the frontend code base.

For a frontend developer to fix the issue, they need a matching device to reproduce the issue, which e.g. is not the case for me. So you have to wait until someone comes along that wants and actually can help or otherwise try to dig further down into the issue yourself.

**Comment by oywino** [comment]
I dont' understand your comment. The cast is a HA feature promoted on the very front page of the HA home Web (https://www.home-assistant.io/)
I'm just reporting a bug; It doesn't work at all the way it is described.

**Comment by spacegaier** [comment]
Sorry for the confusion: I was just pointing out why in an open-source project your above mentioned expectation might be disappointed. For HA specifically, there is no "dedicated" frontend Cast maintainer. So one of us "general" HA frontend devs needs to have both the required prerequisites (a Cast device) and the motivation to tackle that bug report.

**Comment by oywino** [comment]
I understand that, but if "bug reports" too often are dismissed with "Who cares?" attitude, then we all end up in the dark.
"Not having a Cast device" sounds almost unbelievable, to me. I would think that everyone with a TV also has a cast device (?)
Everyone I know has a TV, and where I live, the largest distributor of cable-TV gives you one for free if you sign up with them

**Comment by spacegaier** [comment]
I do care about the project, but with the limited amount of free time I have, I need to decide on which HA topics I invest it (and of course the ones that I can easily fix and reproduce plus the ones that directly affect my HA instances are higher on the list ;) ). Same applies too all unpaid devs here.

But back to topic: I never looked into the "Cast world". I thought you need a Google Nest / Hub device, which I don't have. I of course do have a TV.

**Comment by oywino** [comment]
Most new smart TV's are cast-enabled. Most Set-top boxes are cast enabled. And a Chromecast will only set you back like perhaps $30. With it, anything that has a HDMI input can become a HA display.  Regretfully though - without touch (yet). Meaning: only info displays. Not interactive. But still, quite useful (if I could only make the cast feature work properly).

But don't get me wrong - I understand completely that open source developers do what they feel like doing 😊
Keep up the good work.
