### ISSUE TITLE
Invalid config for [switch.broadlink]: [type] is an invalid option for [switch.broadlink] into Home Assistant 2021.1.1

### ISSUE THREAD

**Issue by mgerasika** [home-assistant/frontend#8143]
Reproduced into Home Assistant 2021.1.1

Config:
switch:
  - platform: broadlink
    host: 192.168.1.2
    mac: '34:ea:34:91:2f:c2'
    type: sp3
    friendly_name: bradlink_sp3_1

error when validate config:

Invalid config for [switch.broadlink]: [type] is an invalid option for [switch.broadlink]. Check: switch.broadlink->type. (See ?, line ?).
Invalid config for [switch.broadlink]: [type] is an invalid option for [switch.broadlink]. Check: switch.broadlink->type. (See ?, line ?).

https://monosnap.com/file/oDngv3jFZnalWurZ4pzqx1oAmrX4p7

https://user-images.githubusercontent.com/10614750/104282268-75616e80-54b7-11eb-9d84-46c6404dd338.mp4

**Comment by spacegaier** [comment]
Not a bug (and if it were then not a frontend topic, but backend). As the error states `type` is not a valid option for Broadlink switches, see docs: https://www.home-assistant.io/integrations/broadlink/#switch
