### ISSUE TITLE
Unneded navigation when removing items from sidebar

### ISSUE THREAD

**Issue by Misiu** [home-assistant/frontend#8158]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When removing items from the sidebar, after clicking on `X` we get unneeded navigation.
![ha-sidebar-edit](https://user-images.githubusercontent.com/1741838/104584037-3ae80500-5662-11eb-8016-a2957f0498d5.gif)

## Expected behavior

After removing an item from the sidebar navigation to removed item shouldn't happen
## Steps to reproduce

1. Go to https://demo.home-assistant.io/
2. Enter sidebar edit mode
3. Remove Map
## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome 87
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
Only seems to happen in the demo. On my local instances this behavior does not exist.

**Comment by Misiu** [comment]
@spacegaier I'm running 0.115.1, I've cleared the cache and I can configure that the problem doesn't exist.
Not sure why it happens on the demo.
I'll check again with the latest release when I set up a new dev environment.
