### ISSUE TITLE
Logbook Card should have a friendly name 

### ISSUE THREAD

**Issue by flemmingss** [home-assistant/frontend#8170]
https://www.home-assistant.io/lovelace/logbook/

I think it should be possible to add "Name:" for each entity, because entity_id is not always very human friendly to read.
Like this:
```
type: logbook
entities:
  - fan.zigbee_light_46
     name: Bedroom Light
```

**Comment by spacegaier** [comment]
The log book card will (as basically all cards) take the "friendly name" of the entity into account. So if you customize a friendly name it will be shown (not only in the logbook card, but all). That way is much more consistent.
