### ISSUE TITLE
Water heater turn_off/turn_on service call allowed in the UI

### ISSUE THREAD

**Issue by thomasgermain** [home-assistant/frontend#8183]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

![bug](https://user-images.githubusercontent.com/12560542/104849784-e22b9d00-58eb-11eb-9bb5-a18bdea1dc7f.png)

## Expected behavior

`turn_off` and `turn_on` should not be in the list.

## Steps to reproduce

Go to Dev tools, service and write `water_heater`

## Environment

- Home Assistant release with the issue: 2021.1.3
- Last working Home Assistant release (if known):
- Browser and browser version: Version 87.0.4280.88 (Official Build) (64-bit), FF 84.0
- Operating system: Ubuntu 20.04/ Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
The backend is registering those services, so the frontend is displaying them. Not sure what the frontend should do differently here.

https://github.com/home-assistant/core/blob/ae3d038baa54200744b34770a347a7feb9f191dd/homeassistant/components/water_heater/__init__.py#L111

**Comment by thomasgermain** [comment]
Yes agree with you, thanks for checking it !
