### ISSUE TITLE
Please allow to revert pinch-to-zoom within HA on iOS

### ISSUE THREAD

**Issue by ASNNetworks** [home-assistant/frontend#8192]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Since HA 117 there is pinch-to-zoom within the Lovelace interface. This totally breaks using the interface on mobile (at least on iOS). Double tapping sometimes zooms in, or when having accidental touches, it zooms in/out which break the interface. I need to refresh the page or even restart the app to have it zoom again properly.

## Expected behavior

Allow to to disable the pinch-to-zoom gestures, like it was default before. I don't ask to revert the change, there probably are people who need it. But at least give us an option within HA or the app to disable the change.

## Steps to reproduce

Pinch-to-zoom on display.
-->

## Environment

- Home Assistant release with the issue: All instances of HA 117 and up
- Last working Home Assistant release (if known): HA 116.4
- Browser and browser version: Safari on iOS 13 and 14
- Operating system: iOS 13 and 14

**Comment by spacegaier** [comment]
This happens in both the HA companion app and the iOS browser or only the app?

**Comment by ASNNetworks** [comment]
This happens in both. On iOS broswer I kinda understand, since it's a Safari feature. But in HA companion app it doesn't make sense to pinch-to-zoom. This started with HA 117. I reverted to 116.4 way back then because of this (and other reasons). Now I decided to update to latest HA version and clean out all the broken Frontend changes in my interface, and noticed this is still here like on HA 117.

**Comment by zacwest** [comment]
This change was done in #7180. I'm also leaning towards disliking it as it makes the app feel less like an app, and it's almost never what I want the UI to do. If there's a screen which functionally needs zooming (like maps) it should be a zooming component on its own.

**Comment by ASNNetworks** [comment]
> This change was done in #7180. I'm also leaning towards disliking it as it makes the app feel less like an app, and it's almost never what I want the UI to do. If there's a screen which functionally needs zooming (like maps) it should be a zooming component on its own.

Exactly. Also when rotating the screen it zooms in. When rotating back it stays zoomed in. You need to spread-to-zoom-out with 2 fingers and as you see it’s off-set then as well. Totally breaks the UI and the whole point of a mobile UI.

See: 

https://user-images.githubusercontent.com/54230480/105625264-19d4a080-5e28-11eb-8397-adfe754501b9.MP4

**Comment by zacwest** [comment]
I can maybe make it a setting in the iOS app, but I worry that there's cases where we do want to enable this zooming behavior and taking control away from the frontend for that does feel a bit meh.

**Comment by ASNNetworks** [comment]
Any updates regarding this?

**Comment by blandry3** [comment]
The display is zoomed when selecting a time in the calendar of the History menu. 

<img src=“https://user-images.githubusercontent.com/9467857/107136897-b6de1180-68dd-11eb-91a8-fa958f466203.png” width=“300”>

**Comment by ASNNetworks** [comment]
Also breaks using File Editor on iPhones. Searching/typing auto-zooms. When zooming out too much, page reloads which makes you lose all unsaved work. Save button is invisible because of the zoom, doh. 

Only workaround is to carefully zoom out a little.
