### ISSUE TITLE
Volumio media player - Shuffle button doesn't appear

### ISSUE THREAD

**Issue by Krucifixionador** [home-assistant/frontend#8194]
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem

Shuffle button does not appear in Volumio media player.

## Expected behavior

At present:
![Screenshot_1 not ok](https://user-images.githubusercontent.com/7882342/105033002-d4932600-5a57-11eb-9067-d47cd7b24cc6.jpg)
![Screenshot_2 not ok](https://user-images.githubusercontent.com/7882342/105033005-d4932600-5a57-11eb-9fc0-cb891280f1e1.jpg)

With the function included it would be something like this:
![Screenshot_1 ok](https://user-images.githubusercontent.com/7882342/105033076-ed9bd700-5a57-11eb-9266-b88e417d8070.jpg)
![Screenshot_2 ok](https://user-images.githubusercontent.com/7882342/105033078-ed9bd700-5a57-11eb-98d0-8e65cc59ee2c.jpg)

## Steps to reproduce

    1. Add a volumio integration

## Environment

Versión | 2021.1.4
Tipo de instalación | Home Assistant OS
Desarrollo | false
Supervisor | true
Docker | true
Entorno virtual | false
Versión de Python | 3.8.7
Nombre del Sistema Operativo | Linux
Versión del Sistema Operativo | 5.4.79-v8
Arquitectura de CPU | aarch64
Zona horaria | Europe/Madrid

GitHub API | ok
Github API Calls Remaining | 4985
Installed Version | 1.10.0
Stage | running
Available Repositories | 709
Installed Repositories | 2

Sistema operativo del Host | Home Assistant OS 5.10
Canal de actualización | stable
Versión del Supervisor | 2021.01.5
Versión de Docker | 19.03.13
Disco total | 57.8 GB
Disco usado | 3.8 GB
Saludable | true
Soportado | true
Placa | rpi4-64
API del Supervisor | ok
Versión del API | ok
Complementos instalados | Terminal & SSH (8.10.0), Samba share (9.3.0), File editor (5.2.0), Xiaomi Mi Scale (0.1.16), Mosquitto broker (5.1)

- Home Assistant release with the issue: 2021.1.4
- Last working Home Assistant release (if known):
- Browser and browser version: All browsers and home assistant app
- Operating system: 

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
Can you please paste in your volumio entity state. Esp. the `supported_features` attribute is of interest.
