### ISSUE TITLE
automation-condition type-numeric state not correct

### ISSUE THREAD

**Issue by fixx-er** [home-assistant/frontend#8201]
for the latest version of HASSIO in Automation and under condition type.
when choosing Numeric state and available attribute for a light of brightness, the above and below settings are reversed.  In other words when I wanted to check for brightness below the value of 50 it didn't work, but above 50 did.  Actual value at the time is 20. snapshot attached.

Not sure if the behavior is correct or not.  I do not think it is correct.
![Screenshot from 2021-01-19 07-33-26](https://user-images.githubusercontent.com/38498263/105050019-8ae01680-5a2a-11eb-9958-e3af8a4f6db7.png)

My bulb is a Gosund RGBW 8W by Tasmota
Firmware: 8.5.1(tasmota)

**Comment by spacegaier** [comment]
I can't find any problem here. Frontend is correctly saving the condition and I also debugged the backend: The condition is correctly executed.

Can you please double check your scenario?

**Comment by spacegaier** [comment]
One more thing: How did you test the automation? Did you manually trigger it from the user interface via the "Execute" buttons? In that case, the conditions were always skipped. PR is on its way.

**Comment by fixx-er** [comment]
I set the trigger for a fixed time and kept changing the time ahead so it will trigger
the condition that is working for me now is the following snapshot. I may have to test again with the original condition with the light on but low brightness.  I had assumed that it being off the brightness would be zero.  So let me try the original again then.
![Screenshot from 2021-01-27 19-55-13](https://user-images.githubusercontent.com/38498263/106083748-4283c100-60da-11eb-8cfb-843975d82a94.png)

**Comment by fixx-er** [comment]
Ok - the following condition where I check for work day has not changed in my test the condition does not work.  I manually set the brightness to 38
![Screenshot from 2021-01-27 20-10-56](https://user-images.githubusercontent.com/38498263/106084699-0d786e00-60dc-11eb-82c4-24999490e4cd.png)

**Comment by fixx-er** [comment]
I added {{ state.attributes.brightness }} in the value template and it did not execute.

**Comment by fixx-er** [comment]
I used the number 127.5 below and that worked!
So I have been trying to use a percent instead of a number value.  I don't know how to use a percent then and would welcome a way.

**Comment by spacegaier** [comment]
Yes, the condition compares against the actual attribute value which for brightness is in range 0..255. If you want to maintain your condition in percent, you can add this value template to convert it first back to percent: 
`{{ (state.attributes.brightness / 255 * 100) | round(0) }}`.
