### ISSUE TITLE
Operator in entity filter includes wrong entities

### ISSUE THREAD

**Issue by cinghialino** [home-assistant/frontend#8202]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I have attempted several different approaches to solve this problem to no avail.
https://community.home-assistant.io/t/operator-in-entity-filter-includes-wrong-entities/271167?u=cinghialino

## Expected behavior

I should be able to filter only the sensors who are currently drawing power.

## Environment

[https://community-assets.home-assistant.io/original/3X/a/6/a69d944ae6629b769f8b589a70c2e3b3b627e5ff.png](https://community-assets.home-assistant.io/original/3X/a/6/a69d944ae6629b769f8b589a70c2e3b3b627e5ff.png)

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
Everything is fine as explained here: https://community.home-assistant.io/t/operator-in-entity-filter-includes-wrong-entities/271167/9?u=spacegaier
