### ISSUE TITLE
Lovelace Views Code — adding comments.

### ISSUE THREAD

**Issue by SefDik** [home-assistant/frontend#8203]
**Lovelace Views Code — adding comments.**
I try to be a good coder and I want to add comments/remarks to my yamls.  
I have tried this in lovelace views and the # comment lines get deleted after saving and then reopening.  
It would be really good practise NOT to delete these lines.   
I notice if I add a line description: 'my text' it does not get deleted  but I'm reluctant to use this too much in case it gets deprecated and I loose all my comments.

**Comment by spacegaier** [comment]
That is not possible: Although the user sees YAML in the frontend editor, internally everything is stored as JSON which does not allow comments.
