### ISSUE TITLE
Black on black on dark mode in "Unable to connect to Home Assistant."

### ISSUE THREAD

**Issue by KTibow** [home-assistant/frontend#8214]
## Checklist
I couldn't do any of this, because it's hard to cause "unable to connect to home assistant".
- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

I use dark mode in my OS. Sometimes I get a random "Unable to connect to Home Assistant." error, and it's black text on a black background.
![image](https://user-images.githubusercontent.com/10727862/105610773-34464580-5d66-11eb-8dc4-83e5091767e1.png)
This style causes the black background:
![image](https://user-images.githubusercontent.com/10727862/105610800-59d34f00-5d66-11eb-9268-bd0c77f62f9b.png)
This bug can be fixed by changing the style to this:
![image](https://user-images.githubusercontent.com/10727862/105610822-88512a00-5d66-11eb-8b1c-2cafcf92b1db.png)
Which results in this:
![image](https://user-images.githubusercontent.com/10727862/105610835-9acb6380-5d66-11eb-8338-6e203e35d1e1.png)

## Expected behavior

Expected behavior mockup in Firefox devtools:
![image](https://user-images.githubusercontent.com/10727862/105610845-adde3380-5d66-11eb-8dcc-9bf032cf5753.png)

## Steps to reproduce

1. Enable dark mode on your OS
2. Try to load lovelace (Firefox may be a factor)
3. Get the error (I'm not sure how)
4. See text

## Environment

- Home Assistant release with the issue: 2021.1.3
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Firefox 84.0.2 (64-bit)
- Operating system: Windows

## State of relevant entities

N/A
```yaml

```

## Problem-relevant frontend configuration

I wasn't trying to load Lovelace.
```yaml

```

## Javascript errors shown in your browser console/inspector

![image](https://user-images.githubusercontent.com/10727862/105610935-48d70d80-5d67-11eb-9fee-46507ad4fd2e.png)

```txt
contentscript.js: https://ourliltreehouse.duckdns.org/hacs <empty string> contentscript.js:24:9
BROWSER_MOD 1.2.3 IS INSTALLED
    DeviceID: a2b6a40f-9973ecc8 browser_mod.js:149:8195
Firefox can’t establish a connection to the server at wss://ourliltreehouse.duckdns.org/api/websocket. core.94ddb68d.js:1
Uncaught (in promise) 1 2
```
I have the AdNauseum browser extension (`contentscript.js`) and browser_mod installed.

**Comment by KTibow** [comment]
Still a problem.

**Comment by robertalexa** [comment]
Still a problem for me too using the Android Companion app

**Comment by bramkragten** [comment]
Fixed

**Comment by KTibow** [comment]
Which commit/PR fixed it?

**Comment by bramkragten** [comment]
https://github.com/home-assistant/frontend/pull/8997
