### ISSUE TITLE
Bug in the pop-up for choosing the time interval in the Registry and in History

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#8226]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem
  In the pop-up window for choosing the time interval (today, yesterday, etc.)
  both in the Registry and in the History, the list on 
  the left with the time choice items often does not appear.

![Storico](https://user-images.githubusercontent.com/74879713/105638377-968c6c80-5e72-11eb-8444-0eb4dfa4001e.png)

## Steps to reproduce
- I log into Home Assistant
- go to the Registry or History
- click on "Start date"

the pop-up does not appear correctly

## Environment

- Home Assistant release with the issue: at least the last two
- Last working Home Assistant release (if known): I do not know
- Browser and browser version: Chrome the last version
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
Clear your browser cache.

**Comment by WRoss7** [comment]
Thanks for the quick response,
I tried, but after restarting the pc and logging back to HA, the problem persists.

**Comment by spacegaier** [comment]
Restarting PC does not help, you need to clear the browser cache.

**Comment by WRoss7** [comment]
My system:

RaspberryPi 4GiB & MicroSD 64GiB

Versione | 2021.1.5
Tipo di installazione | Home Assistant OS
Sviluppo | false
Supervisore | true
Docker | true
Ambiente virtuale | false
Versione Python | 3.8.7
Famiglia del Sistema Operativo | Linux
Versione del Sistema Operativo | 5.4.79-v7l
Architettura della CPU | armv7l
Fuso orario | Europe/Rome


Sistema Operativo Host | Home Assistant OS 5.10
Canale di aggiornamento | stable
Versione Supervisore | 2021.01.7
Versione Docker | 19.03.13
Disco totale | 57.8 GB
Disco utilizzato | 6.2 GB
Integrità | true
Supportato | true
Scheda di base | rpi4
API Supervisore | ok
Versione API | ok
Componenti aggiuntivi installati | File editor (5.2.0), Glances (0.9.1), InfluxDB (4.0.1), Grafana (6.0.0), Mosquitto broker (5.1), Terminal & SSH (8.10.0), Samba share (9.3.0)

**Comment by WRoss7** [comment]
As written, I tried to no avail, restarting the pc was an extra

**Comment by WRoss7** [comment]
The same in Firefox

**Comment by spacegaier** [comment]
Have you tried it in private browser mode or manually disabled caching in the browser dev tools ("Network" tab)? I have seen the issue you describe a few times, all down to non cleared cache.

**Comment by WRoss7** [comment]
It seems that in private browser mod the problem does not occur, weird bug. I will do other tests.
I disabled caching, and it still shows up in normal mode

**Comment by WRoss7** [comment]
Today I did some other tests in Chrome (first with cache disabled, and then enabled), and I encountered another strange bug: Registry is always empty.
Here's how to reproduce the bug:

- I go to the Registry and choose for example "Today"
- I go to Overview, or to another section
- I return to the Registry, and find it empty

The bug reported yesterday has never occurred again, not even re-enabling the cache, at least until now.

**Comment by spacegaier** [comment]
Once the new frontend code has been loaded into the cache, you can re-enable caching again to get back the performance.

For the other topic: New bug => new issue. I cannot find any issue in what you described, but provide some more details, since I might be missing something.

**Comment by WRoss7** [comment]
@spacegaier
I ran some more tests today, and the bug came back.
I also found the bug in Chrome on Android.
Here is the sequence:

- I cleared the Chrome cache
- I restarted Chrome (I'm sure it wasn't needed)
- I logged in HA
- I clicked "Yes" in the pop-up "Do you want to stay logged in?"
- I clicked on History, on the "Start date" button, then on "Today"
- I clicked on Registry, on the "Start date" button, and here is the bug

Let me know if you need more information or logs.

**Comment by spacegaier** [comment]
I assume with "Registry" you mean the "Logbook"? Try it in a private browser mode window or disable the cache in the Chrome browser dev tools ("Network" tab).
