### ISSUE TITLE
Blank dashboard for second user

### ISSUE THREAD

**Issue by stu247** [home-assistant/frontend#8233]
## Checklist

- [ x] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

I have two dashboards set up: Overview and Admin. The Admin dashboard is set to “admin only”. They are both UI controlled. Both dashboards appear fine on my user login, but are blank pages on my wife’s user login. If I hover over the Overview link on the left hand side with my login, I see a URL that ends in /lovelace. If I click on the link, I am taken to a URL that ultimately ends in /lovelace/default_view. For my wife’s login, the hover shows the same link: /lovelace, but if clicked on it, I am taken to a URL that ultimately ends in /lovelace. It does not have the “/default_view” on the end. If I manually add that on the end of the URL in the browser, then the page displays correctly on my wife’s login.

This happens in Firefox and Chromium.  It also happens in HA iOS app, but I cannot modify the URL in that case.  For the iOS app, if I let the screen timeout while still in the app, then when the phone is unlocked again the dashboard is then displayed.

## Expected behavior

dashboards should not be blank for second login

## Steps to reproduce

See problem statement above.

## Environment

- Home Assistant release with the issue: 2021.1.5
- Last working Home Assistant release (if known): ?
- Browser and browser version:  Firefox 84.0.2, Chromium 88.0.4324.96, iOS HA app 2021.1.1 (9).
- Operating system:  Ubuntu 20.04, iOS 14.3

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by stu247** [comment]
Is there any additional information you need?

**Comment by stu247** [comment]
The same issue occurs with 2021.5.2.

**Comment by bramkragten** [comment]
We atleast need the config of the view and dashboard

**Comment by stu247** [comment]
I looked at the config of the view for the Overview dashboard and noticed that it had a visible variable set to just my user id.  I removed the visible variable and my wife is now able to access the dashboard.  Thanks for pointing me to the config of the view.
