### ISSUE TITLE
/config/info still uses Hass.io

### ISSUE THREAD

**Issue by fabaff** [home-assistant/frontend#8240]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

/config/info still uses Hass.io. 

![Screenshot-20210126114011-663x110](https://user-images.githubusercontent.com/116184/105834906-5e4c7180-5fcb-11eb-9a0a-906d3354b1bc.png)

## Expected behavior

Use the right name.

## Steps to reproduce

Check /config/info while running on Home Assistant.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ludeeus** [comment]
This has been adjusted in the `hassio` integration <https://github.com/home-assistant/core/blob/dev/homeassistant/components/hassio/translations/en.json#L18>
