### ISSUE TITLE
Snapshot restore - wrong info while system is starting up

### ISSUE THREAD

**Issue by andriej** [home-assistant/frontend#8241]
### Describe the issue

While HA is starting up/system not ready user is able to go into Supervisor -> Snapshots and start to restore from snapshot.
After choosing what to restore and selecting i.e. "Restore selected", there's an immidiately info "Snapshot restored" while in log there's an error:
```
Dec 14 01:11:33 abc hassio-supervisor[1044]: home-assistant/supervisor#33[33m20-12-14 00:11:33 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_restore_partial' blocked from execution, system is not running#033[0m
```

### Steps to reproduce

1. Have issue with HA and restart your instance
2. While HA is starting up go to Snapshots and try to Restore something
3. See the 'confirmation' info in bottom right corner while nothing happens in background

### Enviroment details

- **Operating System:**: Debian 10
- **Supervisor version:**: 2020.12.6
- **Home Assistant version**: 0.118.5

### Supervisor logs

<details>
<summary>Supervisor logs</summary>

```
Dec 14 01:11:33 abc hassio-supervisor[1044]: home-assistant/supervisor#33[33m20-12-14 00:11:33 WARNING (MainThread) [supervisor.jobs] 'SnapshotManager.do_restore_partial' blocked from execution, system is not running#033[0m

```

</details>

### System Information

<details>
<summary>System Information</summary>

```
arch: amd64
channel: stable
docker: 19.03.14
features:
- reboot
- shutdown
- services
- network
- hostname
hassos: null
homeassistant: 0.118.5
hostname: brix
logging: info
machine: qemux86-64
operating_system: Debian GNU/Linux 10 (buster)
supervisor: 2020.12.6
supported: true
supported_arch:
- amd64
- i386
timezone: Europe/Warsaw


```

</details>

**Comment by ludeeus** [comment]
This has been fixed, the restore buttons are now disabled if the backend is not ready.
