### ISSUE TITLE
The Logbook is empty

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#8260]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
The Logbook is empty, even after making a choice (for example "Today"),
changed view (for example History), and returned to the Logbook itself

## Expected behavior
The Logbook should never be empty, unless there are no events in the chosen time frame

## Steps to reproduce
- I cleared the Chrome cache
- I restarted Chrome (I'm sure it wasn't needed)
- I logged in HA
- I answered "Yes" in the "Do you want to stay logged in?"
- I clicked on Logbook, and found it empty
- I chose "Today", and the list appeared
- I clicked on History
- I clicked on Logbook, and found it empty

## Environment
Windows 10

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
The time period selection is not stored between view / panel switches. So when you come back to the logbook it is again reset to the default period, which probably had no entries during that period and therefore would be correct?

**Comment by WRoss7** [comment]
Oops, having still a few connected devices, I didn't calculate that they could not even have status changes in the default period.
I'm sorry I wasted your time. It would probably be advisable to memorize the choice instead of resetting to the default value.

P.S. 1) why do I often see multiple identical occurrences of the same entity if it has not undergone status changes (as in the screenshot)?
2) but does Logbook display all status changes of all entities? I haven't investigated that much, but I'm pretty sure in my H.A. spade something lost along the way

![Immagine](https://user-images.githubusercontent.com/74879713/106819882-b2fe8500-667a-11eb-8993-f540ea265672.png)

**Comment by spacegaier** [comment]
Re 1) Perhaps check in the HA database if they are actually the same states, or if it is a translation / rendering issue.

Re 2) Normally each state change should have a corresponding event that the logbook can display. If you find an scenario where that is not the case, that would be a backend issue to report.

**Comment by WRoss7** [comment]
Hi
1) I don't know how to do it, I tried with a SQLite browser, but I only see dates, id, etc, but no entity name
Can you tell me how to do it?

**Comment by spacegaier** [comment]
Look in the "states" table. You should see something like this:
![image](https://user-images.githubusercontent.com/114137/107158076-f3fede00-6987-11eb-8598-055066387198.png)
