### ISSUE TITLE
Chart tooltips hidden immediately 

### ISSUE THREAD

**Issue by larena1** [home-assistant/frontend#8274]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Tooltips of charts in modals will be hidden almost immediately on at least Android

## Environment

- Home Assistant release with the issue: latest beta
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by larena1** [comment]
Upgraded to final, still suffering from this. Is there any chance for a fix or is nobody else impacted? @bramkragten

**Comment by spacegaier** [comment]
Does this happen consistently for you? I sometimes have it for one tap, but if I then just click on it again the tooltip stays longer and for all/most follow-up taps.

But the tooltip does not stay open indefinitely for me, so there might be some updating/re-rendering coming into play that closes the tooltip and in unlucky moments happens a few milliseconds after the tap and therefore the tooltip immediately vanishes.

**Comment by larena1** [comment]
I've never experienced this prior to 2021.2.0.
 Tooltips will show for 1 sec max because that seems to be the interval which the media player's current playback position is updated in.

**Comment by spacegaier** [comment]
Ah, so we are talking about specific cards. Can you please fill out the issue template in the first post, especially the "Steps to reproduce" so we are talking about the same thing here.

**Comment by larena1** [comment]
It's not a card. It's every history chart in a regular lovelace modal.

https://github.com/home-assistant/frontend/commit/7dfa1b0942834b798f8c8ee930702e920c4877c0

Just found this commit which could be related to the issue.
