### ISSUE TITLE
Lock controls duplicated when code_format is set

### ISSUE THREAD

**Issue by ReneNulschDE** [home-assistant/frontend#8296]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I'm working on a custom component to control the lock of cars. 
If I set the the [code_format](https://developers.home-assistant.io/docs/core/entity/lock), then the lock/unlock controls are duplicated in the detail view of the lock.

![image](https://user-images.githubusercontent.com/33263735/106391880-c3e79600-63ef-11eb-844e-18ab94c2f8e0.png)

## Expected behavior

- overall handling of code_format is improved
- unlock/lock is not duplicated
- 
## Steps to reproduce

- add a LOCK component that is using the code_format property
- click on the details of the lock
- lock and unlock buttons are duplicated 

## Environment

- Home Assistant release with the issue: core-2021.3.0.dev0
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Chromium, Version 88.0.4324.96 (Official Build) snap (64-bit)
- Operating system: Linux Ubuntu 20.10, HA-Info: 5.8.0-40-generic
--

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
I think in that scenario only the bottom buttons should be shown since we require a code input, so the top ones make no sense. Also just from the screenshot the alignment of the bottom buttons in relation to the input field, looks off.

**Comment by spacegaier** [comment]
Issue still exists
