### ISSUE TITLE
filter 'Unhealthy for sensitive groups' in dev tools states won't show entity

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#8299]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Issue with a valid first character in the filter:

Using filter 'Unhealthy for sensitive groups' in the state column on developer-tools/state wont display the sensor.u_s_air_pollution_level entity, while using 'nhealthy for sensitive groups' does make it appear:

<img width="943" alt="Schermafbeelding 2021-02-01 om 13 28 52" src="https://user-images.githubusercontent.com/33354141/106458963-73c11000-6491-11eb-85d4-a9c1dd5ee970.png">

while:
<img width="871" alt="Schermafbeelding 2021-02-01 om 13 12 52" src="https://user-images.githubusercontent.com/33354141/106458535-d534af00-6490-11eb-8ab2-3e7accf57d53.png">

or even using only 'un':
<img width="932" alt="Schermafbeelding 2021-02-01 om 13 19 22" src="https://user-images.githubusercontent.com/33354141/106458553-d9f96300-6490-11eb-98a4-d05abf3c2fdb.png">

## Expected behavior

Have the filter show the entity with the first character in place
## Environment

- Home Assistant release with the issue: 2021.1.5
- Last working Home Assistant release (if known): ?
- Browser and browser version: any
- Operating system: Mac

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

nothing really

**Comment by bramkragten** [comment]
This was fixed, we didnt lowercase the search string.
