### ISSUE TITLE
Cannot properly remove Remote-Assistant

### ISSUE THREAD

**Issue by midget1234** [home-assistant/frontend#8300]
## Checklist

- [ X] I have updated to the latest available Home Assistant version.
- [ X] I have cleared the cache of my browser.
- [X ] I have tried a different browser to see if it is related to my browser.

## The problem
  I had installed emote-Assistant (to connected 2 instances). I have now decided I will run a single instance. Although I have removed the Integration, upgraded to a newer version of HA the log still mentions that it cannot properly load emote-Assistant. 

Apparently removing the integration does not remove all related code 

## Expected behavior

I would expect that if I decide to remove the Integration, and restart HA, clear cache etc. that I would no longer receive messages that my emote assistant failed to load correctly. 

## Steps to reproduce

  Provide steps for us, that helps reproducing your issue.
  For example:
    1. Add Remote Assistant
    2. Remove Remote Assistant
    3. Restart HA
    4. Check Log file

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by frenck** [comment]
That is a custom integration. If you need help, support, or are experiencing issues with custom integrations, please contact the third-party author of that integration.

The Home Assistant project itself does not support hose.

**Comment by midget1234** [comment]
Got it, thanks Franck

Verstuurd vanaf mijn iPhone
