### ISSUE TITLE
Supervisor addon resource panel squashes addon option toggles

### ISSUE THREAD

**Issue by spacegaier** [home-assistant/frontend#8306]
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I noticed the issue after update to latest supervisor (don't think it was there before?). Addons that show the addon resource usage info, squashes the options in the red box:

![image](https://user-images.githubusercontent.com/114137/106675686-d6abc780-65b5-11eb-8029-74df019a17c0.png)

Addons without (e.g., `check_config`) are fine.

## Steps to reproduce

Click on an addon to reach its "Info" tab.

## Environment

- Home Assistant release with the issue: supervisor-2021.02.1
- Last working Home Assistant release (if known):
- Browser and browser version: Only Firefox
- Operating system: Win 10

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ludeeus** [comment]
What version of Firefox do you use, and what resolution?

**Comment by spacegaier** [comment]
> 
> 
> What version of Firefox do you use, and what resolution?

Latest = 85.0. Resolution: 2560 x 1080 px
