### ISSUE TITLE
Texecom2MQTT Add-on Config edit problem on core-2021.2.0b3

### ISSUE THREAD

**Issue by AndrewGWalsh** [home-assistant/frontend#8308]
## The problem

The config edit tab for add-on texecom2mqtt appears to be trying to use a blank UI and will not allow the user to supply a configuration.

## Steps to reproduce

Install texecom2mqtt add-on.
Select Configuration tab
Note that UI is blank and that the option to select Edit in YAML is greyed out, there is no method for adding configuration details.

## Environment

Issue became apparent on 2021.2 beta (not sure which one) and is still there on 2021.2 proper
Issue is NOT present on 2021.1 
Issue is apparent on Safari (latest) and Firefox for Mac (latest)
OS is macOS Big Sur (latest)

**Comment by AndrewGWalsh** [comment]
Problem still there on core-2021.2.0b5

**Comment by frenck** [comment]
The Supervisor interface is not related to the version of Core. Updates of Core doesn't impact or change this.

In this case, the version of the Supervisor matters (version number starts with `supervisor-`).

Could you additionally provide a link to the add-on? Thanks 👍

**Comment by HITChris** [comment]
Seeing this with Frigate NVR - https://github.com/blakeblackshear/frigate-hass-addons

In Chrome, with X:

**Comment by AndrewGWalsh** [comment]
Add-on is at https://github.com/dchesterton/texecom2mqtt-hassio 

Supervisor version is latest - supervisor-2021.02.3 but the error started a few versions ago.

**Comment by frenck** [comment]
The common thing between both add-ons, is that both don't provide a schema. (`false`)
