### ISSUE TITLE
Input Number decimal starting with zero not working

### ISSUE THREAD

**Issue by mmarcm** [home-assistant/frontend#8321]
## Checklist

- [ x] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem
Decimal digit of input number is not accepted in frontend, if it starts with 0, e.g. 999,09
It is not possible to enter an input number with a leading 0 as decimal.
However a workaround is possible by entering e.g. 999,9 as decimal and then adding the missing 0.

<img width="342" alt="Screenshot 2021-02-04 at 10 58 11" src="https://user-images.githubusercontent.com/2877860/106877688-54b4bf00-66d9-11eb-9832-6eb808c28e9a.png">

## Expected behavior
Leading zeros as decimal digit should be possible to enter and save without workaround.

## Steps to reproduce
1. Add new input_number from frontend
<img width="350" alt="Screenshot 2021-02-04 at 10 56 00" src="https://user-images.githubusercontent.com/2877860/106876066-a2302c80-66d7-11eb-82d4-5bf8272ced53.png">
2. Try to change the value of newly created input_number to e.g. 999,09 (as long as it has a leading zero as the first decimal digit). 
3. Frontend will not accept the new decimal number and revert to integer.

## Environment

- Home Assistant release with the issue: 2021.2.0
- Last working Home Assistant release (if known):
- Browser and browser version: Google Chrome Version 88.0.4324.96 
- Operating system: Mac OS Mojave 10.14.6

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
I can reproduce the issue. I also realized that commas (used in some languages as decimal separator) is not allowed as well. However simply adjusting the patterns we pass to the `<paper-input>` did not solve it for me as for "12.0" the input still gets truncated to "12". Needs further investigation it seems...
