### ISSUE TITLE
The graph in the History Graph Card is not centered on the card

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#8346]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
The space between the edge of the card and the bar on the left is different than on the right
The same is noticeable in non-binary charts

![Graph](https://user-images.githubusercontent.com/74879713/107153802-aeceb200-696f-11eb-9ce3-31fb4a52af92.png)

Everything also seems to be off-center vertically in the card

## Expected behavior
Should the graphics bar be centered on the card, or is it a deliberate choice?

## Environment

- Home Assistant release with the issue: I don't know, I have been using HA for a few months
- Last working Home Assistant release (if known): ?
- Browser and browser version: Chrome / Firefox > the last version
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment]
I think the element is properly centered horizontally. The time (e.g. "18:00") below the timeline is part of the history chart and taken into account for the centering.

**Comment by WRoss7** [comment]
In my opinion it would be more correct to center the graph, and show the latest time (in this case 18:00) at the far right of the graph, at least as long as needed.

However, the whole thing is vertically off center

**Comment by WRoss7** [comment]
Oops! I didn't see your report.
Should I close this one and open one for vertical off-center?

**Comment by WRoss7** [comment]
An example from Google Material Design
![Graph 2](https://user-images.githubusercontent.com/74879713/107156247-8948a500-697d-11eb-8bb0-27f8e57f0c93.png)
