### ISSUE TITLE
Overview dashboard is hidden if default dashbord changed in profile

### ISSUE THREAD

**Issue by minzel** [home-assistant/frontend#8359]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The default Lovelace dashboard is hidden, if default dashboard changed in profile.

## Expected behavior

Do not hide default Lovlace dashboard, if default dashboard changed in profile.

## Steps to reproduce

Create another dashbord and set as default.

## Environment

- Home Assistant release with the issue: 2021.2.2
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome, Opera
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

https://community.home-assistant.io/t/dont-hide-overview-dashboard/191617

**Comment by newhinton** [comment]
Can this be reopened? I have the same behaviour, and i would like to know if it is possible to not hide it. 
Thanks!

**Comment by spacegaier** [comment]
I don't think that this is a bug, but rather a feature request. As far as I can tell, everything works as designed.
