### ISSUE TITLE
Generic Thermostat 'precision' now locks temperature display to step size

### ISSUE THREAD

**Issue by 3ative** [home-assistant/frontend#8374]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

A recent change to Generic Thermostat saw the 'precision' option also affect the displayed temperature causing it to only show at the same step size as the dial.
This prevents the thermostat from displaying the actual temperature. It has therefore has degraded its usefulness.

**Describe the behavior you expected**

Changing the 'precision: x.x' option should only effect the step/precision of set temperature dial and not effect the displayed temperature from 'target_sensor: sennor.xxxx'. 

**Steps to reproduce the issue**

1. Set 'precision' option to 0.5
2. Reload thermostat / re-start Home Assistant 
3. Adjust thermostat dial, notice it in/decrements by 0.5 (set in step 1 above)
4. Set desired heating temperature 
5. Watch thermostat's display, taken from 'target_sensor' and notice it now too steps in 0.5 degrees (not 0.1 as before)
...

**What version of Home Assistant Core has the issue?**

core-2021.2.2

**What was the last working version of Home Assistant Core?**

_No response_

**In which browser are you experiencing the issue with?**

Any

**Which operating system are you using to run this browser?**

Windows 10

**State of relevant entities**

```yaml
# Paste your state here.

```

**Problem-relevant frontend configuration**

```yaml
- platform: generic_thermostat
  name: Bedroom Heating
  heater: switch.heater
  min_temp: 15
  max_temp: 30
  cold_tolerance: 0.5
  hot_tolerance: 0.0
  precision: 0.5
  target_sensor: sensor.bedroom_temperature

```

**Javascript errors shown in your browser console/inspector**

```txt
# Paste your logs here.

```

This was a breaking change about 15 days ago - while functionality remains the same. Combining this 'precision:' option to both the dial (expected behaviour) to the displayed temperature makes said display less useful - as it does not now display actual data all the time.

**Comment by spacegaier** [comment]
Backend issue (already exists and is already referenced as well).

**Comment by 3ative** [comment]
@spacegaier Ah ok, thanks. ✔
