### ISSUE TITLE
Flux LED/MagicLight integration missing from frontend

### ISSUE THREAD

**Issue by CRZTFR** [home-assistant/frontend#8375]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

The FluxLED/MagicLight integration is missing from the UI Configuration -> Integrations page. 

The documentation here https://www.home-assistant.io/integrations/flux_led/ describes a setup through the UI/frontend. 

**Describe the behavior you expected**

I expect to be able to configure the flux_led integration through the UI. 

**Steps to reproduce the issue**

1. Configuration -> integrations
2. Add integration
3. Search integration shows no results for Flux or Magic. I am also unable to find any information on setup via configuration.yaml

**What version of Home Assistant Core has the issue?**

core-2021.2.3

**What was the last working version of Home Assistant Core?**

_No response_

**In which browser are you experiencing the issue with?**

Google Chrome Version 88.0.4324.150 (Official Build) (64-bit)

**Which operating system are you using to run this browser?**

Windows 10 Pro 18363.1377

**State of relevant entities**

_No response_

**Problem-relevant frontend configuration**

_No response_

**Javascript errors shown in your browser console/inspector**

_No response_

**Comment by frenck** [comment]
This is not a frontend issue, but a documentation issue.
issue @ Documentation: <https://github.com/home-assistant/home-assistant.io/issues/16497>
