### ISSUE TITLE
Kwikset Obsidian 954 using Jwave JS does not reflect bolt status

### ISSUE THREAD

**Issue by MaikaiLife** [home-assistant/frontend#8394]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

When using the Zwave JS integration the bolt status of the Kwikset Obsidian 954 is not reported when a person physically interacts with the door lock, unlocking or locking.

**Describe the behavior you expected**

What should be the expected behavior is that when the Kwikset Obsidian 954 is unlocked or locked either via zwave or manually by a person physically interacting with the lock, the status of the lock should change in Home Assistant.

**Steps to reproduce the issue**

1.Check the current status of the lock in Home Assistant, set it to locked.
2. Physically type in the unlock code or turn the deadbolt on the lock.
3. Look at the lock status in Home Assistant, it will still show locked even though the lock is 'unlocked'
...

**What version of Home Assistant Core has the issue?**

core-2021.2.3

**What was the last working version of Home Assistant Core?**

_No response_

**In which browser are you experiencing the issue with?**

Chrome 88

**Which operating system are you using to run this browser?**

MacOS

**State of relevant entities**

```yaml
# Paste your state here.

```

**Problem-relevant frontend configuration**

entity_id: lock.kwikset_obsidian_current_lock_mode
state: locked
friendly_name: Front Door

**Javascript errors shown in your browser console/inspector**

```txt
# Paste your logs here.

```

**Comment by spacegaier** [comment]
That sounds like a backend issue. If you check the lock's state/values in the HA dev tools, is it correct there? If not, then it's a backend issue. If it is correct there, but wrongly visualized in Lovelace, then it's a frontend issue,

**Comment by MaikaiLife** [comment]
I updated to JS 1.7 and restarted HA and it appears to be following the physical status of the lock.  Sorry for the pre-mature report,.
