### ISSUE TITLE
I report a problem on the authentication page when you want to identify yourself and the home assistant is in French (view the photo below watch this sentence : connexion à ** location ** avec ** name **).

### ISSUE THREAD

**Issue by Xavier-34** [home-assistant/frontend#8395]
**Checklist**

- [x] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

I report a problem on the authentication page when you want to identify yourself and the home assistant is in French (view the photo below watch this sentence : connexion à ** location ** avec ** name **).
**Describe the behavior you expected**

?

**Steps to reproduce the issue**

1. Put the home assistant interface in French.
3.
...

**What version of Home Assistant Core has the issue?**

Home Assistant 2021.2.3

**What was the last working version of Home Assistant Core?**

?

**In which browser are you experiencing the issue with?**

All

**Which operating system are you using to run this browser?**

Windows 10

**State of relevant entities**

```yaml
# Paste your state here.

```

**Problem-relevant frontend configuration**

```yaml
# Paste your YAML here.

```

**Javascript errors shown in your browser console/inspector**

```txt
# Paste your logs here.

```

![home assistant](https://user-images.githubusercontent.com/63707001/107886860-d0491400-6f02-11eb-8347-d1839c00d44a.png)

**Comment by spacegaier** [comment]
That was a French translation issue in the lokalise project (someone had incorrectly added blanks). Was already fixed 4 days ago in the development version ([commit](https://github.com/home-assistant/frontend/commit/6b673c7f44570d637a317196b1e8de7244d01a4b#diff-13363069f5398a416429d5736d7a55422fe49fa57e859e4d5925d1d8d2f0ac5d)).
