### ISSUE TITLE
Lovelace Freeze 4 sec, after closing "more info" dialog

### ISSUE THREAD

**Issue by pergolafabio** [home-assistant/frontend#8396]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

Hi, after updating from 2021.1.5  to 2021.2.x, whenever i open a "more info" dialog (popup, after i close it, it seems the lovelace view freezes for a few seconds, i cant scroll, cant click on anything ...

i need to wait for a few seconds, then it works again

what could be the issue?

**Describe the behavior you expected**

no freeze

**Steps to reproduce the issue**

1. Activate more info dialog
2. close it
3. see the freeze behaviour
...

**What version of Home Assistant Core has the issue?**

core-2021.2.3

**What was the last working version of Home Assistant Core?**

core-2021.1.5

**In which browser are you experiencing the issue with?**

Chrome and HA companion app on andrild

**Which operating system are you using to run this browser?**

Windows 10 / android 10

**State of relevant entities**

not relevant

**Problem-relevant frontend configuration**

not relevant

**Javascript errors shown in your browser console/inspector**

not relevant

**Comment by bramkragten** [comment]
Any specific entity/domain this is with?

**Comment by pergolafabio** [comment]
no, happens with all entities / domains,  lights, switches .... , everything

**Comment by blair287** [comment]
I am also having this issue it appears to happen worse on any device which has a lot of history info I will take a screen recording and upload it makes HA unstable I have to close the browser/app and open again to get it to work.

**Comment by pergolafabio** [comment]
you think it have todo with "history" ? 
then it should resolve if we delete the database, right?

**Comment by blair287** [comment]
> you think it have todo with "history" ?
> then it should resolve if we delete the database, right?

Yes if you delete database it's ok for a few hours until the 24 hour history in the more info tab fills up.

Here's a video of issue.

https://youtu.be/vL5Hz5G3aWg

**Comment by pergolafabio** [comment]
thats even worse then mine!
i did remove my database, i even excluded lights from the recorder, but that didnt help, so in my case its not a history/database issue

https://www.dropbox.com/s/91maks1bcczbipt/lovelacefreeze.mp4?dl=0

i tried making a video, but its not that clear, since you dont see where i click

but anyway, in the video, you see i long press the button "Inkomhal", the more info popups right after, i close it
then i do the same 1 sec later, but the pop never comes .... then HA is freezed for like 4-5 secs's, cant scroll, cant do anything
then afterwards , it sometimes registers a single press instead of a double press
at around 44 sec, you can actually se the HA is freezing and crashing ....

**Comment by bramkragten** [comment]
Can you try if the beta makes it better?

**Comment by pergolafabio** [comment]
you mean this one? 2021.3.0b0

is there something changed there that could fix it?

**Comment by bramkragten** [comment]
Yes, something in the history graphs

**Comment by pergolafabio** [comment]
ok, upgraded, but didnt help in my case :(

**Comment by gieljnssns** [comment]
I'm also seeing something like this in the current beta.
My browser eats a lot of cpu when viewing the frontend especially when opening more info dialogs
<img width="833" alt="Schermafbeelding 2021-02-27 om 14 53 50" src="https://user-images.githubusercontent.com/17234951/109389167-9d901a00-790b-11eb-993a-cfd5f1a3e9ae.png">
<img width="880" alt="Schermafbeelding 2021-02-27 om 14 54 45" src="https://user-images.githubusercontent.com/17234951/109389193-c1536000-790b-11eb-9332-e2aec67cdaf5.png">

**Comment by gieljnssns** [comment]
<img width="1046" alt="Schermafbeelding 2021-02-27 om 14 56 57" src="https://user-images.githubusercontent.com/17234951/109389242-0d9ea000-790c-11eb-80b7-92480539e41a.png">
<img width="1043" alt="Schermafbeelding 2021-02-27 om 14 57 13" src="https://user-images.githubusercontent.com/17234951/109389246-15f6db00-790c-11eb-82de-e4edc749f506.png">
<img width="1048" alt="Schermafbeelding 2021-02-27 om 14 57 31" src="https://user-images.githubusercontent.com/17234951/109389261-2c049b80-790c-11eb-8852-954c52b0d7e5.png">

**Comment by gieljnssns** [comment]
<img width="1727" alt="Schermafbeelding 2021-02-27 om 15 02 30" src="https://user-images.githubusercontent.com/17234951/109389422-d381ce00-790c-11eb-8fe0-baa9b73a536f.png">

**Comment by gieljnssns** [comment]
<img width="1063" alt="Schermafbeelding 2021-02-27 om 15 04 03" src="https://user-images.githubusercontent.com/17234951/109389473-104dc500-790d-11eb-9edd-1d6a9e5242c9.png">

**Comment by pergolafabio** [comment]
updated core and supervisor to 2021.3.0 , and my issue is fixed, no more freezing when i open a more dialog the second time 

not sure what fixed , but thnx again!
