### ISSUE TITLE
setting delay time in script Sequence do not show syntax corect

### ISSUE THREAD

**Issue by sekt1953** [home-assistant/frontend#8402]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

if I edit Script. sequence delay it look like this after saving
delay:
  hours. 0
  minutes: 0
  seconds: .nan
  milliseconds: 0
if I use file editor it look like this:
  - delay:
      hours: 0
      minutes: 0
      seconds: '{{ states.input_number.transition_time.state }}'
      milliseconds: 0

**Describe the behavior you expected**

script fail

**Steps to reproduce the issue**

1.make a script withe delay sequence
2.edit it from file editor like my description
3.open script again and edit as yaml to see the error
...

**What version of Home Assistant Core has the issue?**

core-2021.2.3

**What was the last working version of Home Assistant Core?**

do not know

**In which browser are you experiencing the issue with?**

Firefox on Ubuntu 18.04

**Which operating system are you using to run this browser?**

Raspbian GNU/Linux 10 (buster)

**State of relevant entities**

```yaml
# Paste your state here.

```

**Problem-relevant frontend configuration**

```yaml
# Paste your YAML here.

```

**Javascript errors shown in your browser console/inspector**

```txt
# Paste your logs here.

```

**Comment by spacegaier** [comment]
Closing this in favor of the more elaborate duplicate https://github.com/home-assistant/frontend/issues/8475.

**Comment by sekt1953** [comment]
ok, and tak

Den lør. 27. feb. 2021 kl. 10.17 skrev Philip Allgaier <
notifications@github.com>:
