### ISSUE TITLE
ZWaveJS doesn't detect Fibaro Roller Shutter FGR222 correctly

### ISSUE THREAD

**Issue by foxy82** [home-assistant/frontend#8428]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

I have just migrated from a working OpenZwave installation to the new ZWaveJS using the ZWaveJS2MQTT add on.

I have 2 Fibaro Roller Shutter 2 (FGR222) - they are both detected but one adds a cover entity whilst the other one doens't:

https://imgur.com/EpYE07A

**Describe the behavior you expected**

I'd expect both entities to have a cover.

**Steps to reproduce the issue**

Add two Fibaro Roller Shutter 2 via ZWave JS integration. One will have a cover the other doesn't. Problems persists after a restart.

**What version of Home Assistant Core has the issue?**

core-2021.2.3

**What was the last working version of Home Assistant Core?**

Using OpenZWave

**In which browser are you experiencing the issue with?**

_No response_

**Which operating system are you using to run this browser?**

Windows 10

**State of relevant entities**

```yaml
# Paste your state here.

```

**Problem-relevant frontend configuration**

```yaml
# Paste your YAML here.

```

**Javascript errors shown in your browser console/inspector**

```txt
# Paste your logs here.

```

```txt

2021-02-21 14:52:22 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 422, in _async_add_entity
    supported_features=entity.supported_features,
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 219, in supported_features
    if self.current_cover_position is not None:
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/cover.py", line 75, in current_cover_position
    return round((self.info.primary_value.value / 99) * 100)
TypeError: unsupported operand type(s) for /: 'str' and 'int'
```

**Comment by frenck** [comment]
This is not a frontend issue, but an issue with an integration. Please report issues with integration here:

<http://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
