### ISSUE TITLE
Browser not supported

### ISSUE THREAD

**Issue by beginrescueend** [home-assistant/frontend#8435]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

From your Home Assistant Cast web demo, it says my browser is not supported: "The Cast API is not available in your browser. See the FAQ for more information." https://cast.home-assistant.io/

However, I'm using the latest version of Brave, which is, in essence, Chrome / Chromium, which is supported. Is this just a user-agent issue? The support should be built in.

Brave for Mac -- Version 1.18.75 Chromium: 87.0.4280.101 (Official Build) (x86_64)

**Describe the behavior you expected**

Does not work in Brave. Works in Chrome. (Effectively the same browser.)

**Steps to reproduce the issue**

1. From your Home Assistant Cast web demo, it says my browser is not supported: "The Cast API is not available in your browser. See the FAQ for more information." https://cast.home-assistant.io/

2. Works in Chrome

3. Does not work in Brave

**What version of Home Assistant Core has the issue?**

(demo site)

**What was the last working version of Home Assistant Core?**

(demo site)

**In which browser are you experiencing the issue with?**

Brave for Mac -- Version 1.18.75 Chromium: 87.0.4280.101 (Official Build) (x86_64)

**Which operating system are you using to run this browser?**

MacOS Mojave - 10.14.6

**State of relevant entities**

```yaml
# Paste your state here.

```

**Problem-relevant frontend configuration**

```yaml
# Paste your YAML here.

```

**Javascript errors shown in your browser console/inspector**

```txt
# Paste your logs here.

```

**Comment by bramkragten** [comment]
No, this is something we get back from the Google Cast API:
https://developers.google.com/cast/docs/chrome_sender/integrate#initialization

**Comment by beginrescueend** [comment]
Ah, OK, thanks!
