### ISSUE TITLE
Disable device/entities bugs

### ISSUE THREAD

**Issue by bramkragten** [home-assistant/frontend#8444]
Additional comment, but maybe for a separate PR:
- There should be a popup showing `enabled_delay_confirm` also when enabling devices, warning that the corresponding entities will not immediately be there.
- There's something fishy going on when enabling a disabled entity, they don't show up correctly in the device card until the page is reloaded.

_Originally posted by @emontnemery in https://github.com/home-assistant/frontend/issues/8442#issuecomment-784862327_

**Comment by spacegaier** [comment]
Point one might be a duplicate of this issue I created: https://github.com/home-assistant/frontend/issues/8096

**Comment by emontnemery** [comment]
let's keep this open a bit longer
