### ISSUE TITLE
Shellly integration

### ISSUE THREAD

**Issue by JPOliveGit** [home-assistant/frontend#8446]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

When using the Shelly integration on home assistant directly you can't change decimal numbers showing and you can only do it in the yaml 

**Describe the behavior you expected**

should have all yaml manual options on the visual editor of the sensor

**Steps to reproduce the issue**

1. integrate shelly
2. make a graph sensor

**What version of Home Assistant Core has the issue?**

Home Assistant 2021.2.3

**What was the last working version of Home Assistant Core?**

_No response_

**In which browser are you experiencing the issue with?**

Safari Versão 14.0.3 (16610.4.3.1.4)

**Which operating system are you using to run this browser?**

macOS bigsur 11.2.1

**State of relevant entities**

_No response_

**Problem-relevant frontend configuration**

```yaml
# Paste your YAML here.

```

**Javascript errors shown in your browser console/inspector**

```txt
# Paste your logs here.

```

**Comment by frenck** [comment]
Could you provide a clear YAML example of what isn't possible?

**Comment by JPOliveGit** [comment]
shelly:
  settings:
    temperature: { decimals: 2 }

And if I do this it creates a second instance in the integration menu with the name configuration.yaml with a copy of all sensors from the first one.

**Comment by bieniu** [comment]
Shelly integration doesn't support YAML configuration. Maybe you're using ShellyForHass?

**Comment by frenck** [comment]
That is indeed configuration for the ShellyForHass integration. ShellyForHass is a custom, third-party, integration that is not created, maintained or supported by the Home Assistant project. If you have issues with ShellyForHass, please report those with the ShellyForHass creators.

Thanks 👍

**Comment by JPOliveGit** [comment]
It's not an issue of Shellyforhass the issue is on the core Shelly integration not letting choose the decimal numbers I don't know if there's an issue or this should be a feature request... thanks

**Comment by frenck** [comment]
Aah ok, yeah that would be a feature request, which can be done on our community forum.
