### ISSUE TITLE
Codemirror caret hidden when YAML state filled

### ISSUE THREAD

**Issue by spacegaier** [home-assistant/frontend#8453]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

When you enter the states dev tool and click into the YAML editor the caret appears.

If however you click on an entity in the table below which then fills in the YAML state and then click into the editor, no caret is rendered. If you switch your browser tab and then go back, the caret is rendered again.

**Describe the behavior you expected**

Caret to be visible upon first click into the filled YAML editor.

**Steps to reproduce the issue**

1. Go to states dev tools
2. Click on any entity (via the link in the table)
3. Click into the YAML editor
4. Caret is missing

**What version of Home Assistant Core has the issue?**

core-2021.4.0.dev0 / latest beta

**What was the last working version of Home Assistant Core?**

_No response_

**In which browser are you experiencing the issue with?**

Firefox

**Which operating system are you using to run this browser?**

_No response_

**State of relevant entities**

```yaml
# Paste your state here.

```

**Problem-relevant frontend configuration**

```yaml
# Paste your YAML here.

```

**Javascript errors shown in your browser console/inspector**

```txt
# Paste your logs here.

```

**Comment by bramkragten** [comment]
I don't see this in Chrome, is this just Firefox?

**Comment by spacegaier** [comment]
Yes, seems to be Firefox only. Cannot reproduce in Chrome either. I can also confirm that clicking outside and then inside brings back the caret (so probably any re-focusing, which is what my previous "solution" of switching the tab did as well).

**Comment by bramkragten** [comment]
I think this will solve it: <https://github.com/codemirror/codemirror.next/issues/406>

**Comment by spacegaier** [comment]
It is now solved by one of the many CM related PRs 👍 .
