### ISSUE TITLE
Swicht TV channels on media_player card is not possible anymore

### ISSUE THREAD

**Issue by mib1185** [home-assistant/frontend#8455]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

After changes in #7389 switching TV channels (_in my case `samsungtv` integration is used_) is not possible anymore (_buttons media_previous_track and media_next_track are not shown anymore_).
![image](https://user-images.githubusercontent.com/35783820/109151435-777f4400-776a-11eb-9094-1de60e5f88f5.png)

**Describe the behavior you expected**

TV channels can still be switched like:
![image](https://user-images.githubusercontent.com/35783820/109150913-c9739a00-7769-11eb-9671-898a1e432b84.png)

**Steps to reproduce the issue**

connect Samsung TV via `samsungtv` integration and add medai-player card to dashboard.

**What version of Home Assistant Core has the issue?**

core-2021.2.3

**What was the last working version of Home Assistant Core?**

_No response_

**In which browser are you experiencing the issue with?**

_No response_

**Which operating system are you using to run this browser?**

_No response_

**State of relevant entities**

![image](https://user-images.githubusercontent.com/35783820/109151673-c3ca8400-776a-11eb-916e-ddbd1123e7ce.png)

**Problem-relevant frontend configuration**

```yaml
entity: media_player.samsungtv
type: media-control
```

**Javascript errors shown in your browser console/inspector**

_No response_

Most TV integrations report state=on, but after above noted change, `media-player.ts` lines [266 ](https://github.com/spacegaier/frontend/blob/742f1f85dcaf267bf1a49ba5dcd60057774eb48a/src/data/media-player.ts#L266)and [302](https://github.com/spacegaier/frontend/blob/742f1f85dcaf267bf1a49ba5dcd60057774eb48a/src/data/media-player.ts#L302) only states playing and paused are checked.

**Comment by spacegaier** [comment]
Please add the state of your media player entity and the relevant frontend configuration to the ticket template.

**Comment by mib1185** [comment]
@spacegaier you were to fast, I was not ready with writing the issue 😄 
Now I´m ready 😉

**Comment by mib1185** [comment]
Hi @spacegaier 
are there any additional questions/concerns to this?
