### ISSUE TITLE
[2021.3.0b0] Can't access frontend after updating

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/frontend#8456]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

After updating to version 2021.3.0b0 and reloading the frontend, I can no longer access the webinterface. 

**Describe the behavior you expected**

Show webinterface

**Steps to reproduce the issue**

1. Update to 2021.3.0b0
2. When the message tells you to reload the frontend because of a new version, do it

**What version of Home Assistant Core has the issue?**

2021.3.0b0

**What was the last working version of Home Assistant Core?**

2021.02.x

**In which browser are you experiencing the issue with?**

Microsoft Edge 89.0.774.34

**Which operating system are you using to run this browser?**

Windows 10 20H2

**State of relevant entities**

```yaml
# Paste your state here.

```

**Problem-relevant frontend configuration**

```yaml
# Paste your YAML here.

```

**Javascript errors shown in your browser console/inspector**

```txt
GET https://my.domain/frontend_latest/app.0ed63255.js net::ERR_ABORTED 504
(index):1 GET https://my.domain/frontend_latest/app.0ed63255.js net::ERR_ABORTED 504
(anonymous) @ (index):1
my.domain/:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://my.domain/frontend_latest/app.0ed63255.js
service_worker.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://my.domain/?homescreen=1","error":{}}]
    at J.handle (https://my.domain/service_worker.js:1:14881)
service_worker.js:1 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://my.domain/frontend_latest/app.0ed63255.js","status":504}]
    at x._addURLToCache (https://my.domain/service_worker.js:1:8216)
    at async Promise.all (index 0)
    at async x.install (https://my.domain/service_worker.js:1:7590)
```

![Screenshot_2021 02 25_12h50m39s_003_](https://user-images.githubusercontent.com/1368405/109149716-3d14a780-7768-11eb-8c51-be6cf0814d2c.png)

**Comment by spacegaier** [comment]
HTTP 504 = Gateway timeout => Are you running any services that could interfere here (proxies, firewalls, etc.)?

Also did you enforce a real cache clear (= disable caching) via your browser dev tools (network tab) to test if that resolves the issue?

**Comment by TheZoker** [comment]
Yes I'm running pi-hole, so that was maybe one reason. In the meantime the frontend works again, but I have no clue why it was broken. The strange things was, that before the update it worked and after the update it did not. So I assumed that the issue was with HA. But it seems, that it might been pi-hole or any other network related issue. 
At the time the issue happend, I even deleted all application data from the dev console, so I guess it was not a cache issue. 

The only issue that remains in the dev console is the 
```bash
service_worker.js:1 Uncaught (in promise) no-response: no-response :: [{"url":"https://my.domain/?homescreen=1","error":{}}]
    at J.handle (https://my.domain/service_worker.js:1:14881)
```

This is still there even after the frontend started to work again. 
According to the console, this is the line, where the issue happens (I'm not sure, if this is helpful):
![Screenshot_2021 02 27_12h52m36s_006_](https://user-images.githubusercontent.com/1368405/109386412-bba14e80-78fa-11eb-81d3-40ae3ad56869.png)

Do you have any idea how to solve that? Other then that, I guess this issue can be closed.

**Comment by bramkragten** [comment]
And that URL does work? It is claiming it gets no response from that URL.

This does not look like an issue with the code, going to close this.

**Comment by TheZoker** [comment]
I replaced my domain name with my.domain for security purpose. So yes the actual domain/URL works
