### ISSUE TITLE
Update button does not render text label

### ISSUE THREAD

**Issue by NuAlex** [home-assistant/frontend#8483]
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

When changing the Area for a device the update button seed to be missing, I was on the phone app so I didn't know what to do. Then I switched to a PC browser (Edge) and by rolling over mouse I realized the button is there and it works, its just not displaying the text label "Update" which makes the button invisible. 
Since I was using the dark theme, I switched to Light the the button text appeared back! Oddly enough, when I tried to change the area from another device, the button text disappeared again, while still in Light mode.

**Describe the behavior you expected**

The button should show the text label "Update" otherwise it makes it invisible and a user might not be able to update the device area. On a PC it's easy to roll the mouse over the button but on a phone app you'll just have to guess where's the button.

**Steps to reproduce the issue**

1. open Chrome brower
2. open the HA lovelace page
3. clear all the brower cache
4. click on a device (e.g. light switch)
5. click on the gear icon change settings
6. expand advanced settings
7. click Change Device Area
8. Update button is missing the text label.

**What version of Home Assistant Core has the issue?**

core-2021.2.3

**What was the last working version of Home Assistant Core?**

_No response_

**In which browser are you experiencing the issue with?**

Edge Version 88.0.705.81 (Official build) (64-bit) and Chrome Version 88.0.4324.190 (Official Build) (64-bit)

**Which operating system are you using to run this browser?**

Windows 10

**State of relevant entities**

```yaml
# Paste your state here.

```

**Problem-relevant frontend configuration**

```yaml
# Paste your YAML here.

```

**Javascript errors shown in your browser console/inspector**

```txt
# Paste your logs here.

```

Screenshot of the issue (light mode):
![image](https://user-images.githubusercontent.com/38176824/109399848-14bcb280-78fa-11eb-877b-9f0315714522.png)

Screenshot with mouse roll over (dark mode):
![image](https://user-images.githubusercontent.com/38176824/109399865-374ecb80-78fa-11eb-8586-e1b1a1732ee0.png)

**Comment by spacegaier** [comment]
I assume you have a typo in your step 4 and it should say "entity" instead of "device", correct?

Either way, I cannot reproduce the issue (I am running current beta and dev versions).

I can see that in your screenshot also the text for the toggle/switch is missing. So it could be a translation caching issue. Can you please test-wise disable caching in the Chrome browser tools (tab "Network") and try again.

![image](https://user-images.githubusercontent.com/114137/109400566-c0412380-7949-11eb-8aa2-2f9487e207da.png)

**Comment by NuAlex** [comment]
> I assume you have a typo in your step 4 and it should say "entity" instead of "device", correct?
> 
> Either way, I cannot reproduce the issue (I am running current beta and dev versions).
> 
> I can see that in your screenshot also the text for the toggle/switch is missing. So it could be a translation caching issue. Can you please test-wise disable caching in the Chrome browser tools (tab "Network") and try again.
> 
> ![image](https://user-images.githubusercontent.com/114137/109400566-c0412380-7949-11eb-8aa2-2f9487e207da.png)

I'm not familiar with the right terms, but in #4 I click on a light switch from the lovelace which shows me the status and history of that switch, then (#5) I click in the gear icon and that's when the 'Entity' dialog appears. You need to follow this exact steps otherwise the issue will not reproduce. With cache disabled in chrome I'm able to repro the problem more consistently, so it's definitely a caching issue. I can send you an HAR file and a video capturing a repro (let me know how can I reach out to you in private) but check my new screenshots below. 

Here's the updated steps:

a. Disable cache in Chrome and open HA in lovelace interface - I use CTRL+F5 to fully reload the page

b. Click on any light switch
![image](https://user-images.githubusercontent.com/38176824/109434779-bc55e580-79cb-11eb-8371-db0335784735.png)

c. Click on the gear icon to change settings
![image](https://user-images.githubusercontent.com/38176824/109434811-df809500-79cb-11eb-96ef-9ed1f950b9ce.png)

d. Expand advanced settings and click 'Change Device Area'
![image](https://user-images.githubusercontent.com/38176824/109434849-0212ae00-79cc-11eb-91d6-0660e6609eb9.png)

e. Issue - Update button label and the text for the toggle/switch is missing:
![image](https://user-images.githubusercontent.com/38176824/109434858-12c32400-79cc-11eb-99d2-38cc66bb325a.png)

f. Cancel and go back to lovelace interface

g. Repeat steps b-e for a different light switch

h. Same issue:
 
![image](https://user-images.githubusercontent.com/38176824/109434928-79e0d880-79cc-11eb-90cd-dd8b70560650.png)

i. Now, go to "Configuration"
![image](https://user-images.githubusercontent.com/38176824/109434954-98df6a80-79cc-11eb-9dac-d26014211989.png)

j. And immediately go back to the same lovelace interface.

![image](https://user-images.githubusercontent.com/38176824/109434973-be6c7400-79cc-11eb-84e0-afd2dd10ceb9.png)

k. Repeat steps b-e for the same light switches

l. issue is gone!
![image](https://user-images.githubusercontent.com/38176824/109435005-ed82e580-79cc-11eb-84b2-4fdb934adb05.png)


Hope this helps!
Many thanks for checking this issue, I'm sure other users might be experiencing the same problem.

/Nuno

**Comment by spacegaier** [comment]
Ok, that is indeed important and helpful info. With the detailed description I was now able to reproduce it. Sounds like we are missing some translations in that specific loading sequence.

**Comment by spacegaier** [comment]
@bramkragten Do we need to move the `devices` translation key from `ui.panel.config.devices` to a different non-panel section here?

**Comment by bramkragten** [comment]
Yes, to the dialogs section.

**Comment by spacegaier** [comment]
> 
> 
> Yes, to the dialogs section.

@bramkragten Is there a way to do it, while not losing all existing translations for that section?

**Comment by bramkragten** [comment]
You can use key references https://docs.lokalise.com/en/articles/1400528-key-referencing

**Comment by bramkragten** [comment]
And I could manually change the key name in Lokalise

**Comment by spacegaier** [comment]
I am aware of references but that would around 90 referenced keys as redundant entries (or do we anyway need to keep the existing section as well for the panel)?

**Comment by bramkragten** [comment]
If we don't keep the old one, I can rename the key for the translations

**Comment by spacegaier** [comment]
> 
> 
> If we don't keep the old one, I can rename the key for the translations

Yes, some kind of Lokalise move/edit magic is what I was looking for.
I am not sure if we need to keep the old ones (don't have the deepest understanding yet, when what is loaded where). But I think the devices config section panel would load the dialogs translation section anyway, so we should be good?

**Comment by ingria** [comment]
I'm also experiencing the similar issue. Some labels, buttons or headers in random places are missing.

For example, here's the "add to lovelace" modal:

![hass_1](https://user-images.githubusercontent.com/2178368/112546219-3a8a8980-8dca-11eb-83f1-c586a953c0c5.png)

No text on the buttons and also no titile on the panel (I've added dashed border to missing buttons in dev tools).

Firefox 86
