### ISSUE TITLE
MDI Out of Date

### ISSUE THREAD

**Issue by broyuken** [home-assistant/frontend#8505]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Material Design Icons is significantly out of date, the last update was in August. There are a lot of new icons that would need to be added in to get us back in line with their releases. I noticed that there was a slight bump coming up to 5.6.55 but they are currently on 5.9.55. This leaves a lot of icons available on the site that are not available within HA.

### Describe the behavior you expected

Icon set more up to date

### Steps to reproduce the issue

1. Change icon in HA to mdi:floor-lamp-torchiere
2. See blank icon

### What version of Home Assistant Core has the issue?

all

### What was the last working version of Home Assistant Core?

none

### In which browser are you experiencing the issue with?

all

### Which operating system are you using to run this browser?

all

### State of relevant entities

N/A

### Problem-relevant frontend configuration

icon: mdi:floor-lamp-torchiere

**Comment by spacegaier** [comment]
I think an update makes sense, but the icon you mentioned in the ticket is not part of the MDI icon set. There is however `mdi-floor-lamp`.

**Comment by broyuken** [comment]
I’m not sure what you mean. If I search for floor-lamp-torchiere an icon shows up that I want to use in HA but it hasn’t been updated to the version of mdi that includes it.

**Comment by broyuken** [comment]
on the https://materialdesignicons.com/ website.

**Comment by spacegaier** [comment]
The icon you mentioned is not part of mdi/js or mdi/svg 5.9.55 but I can see it in the main repo https://github.com/Templarian/MaterialDesign. It was added there after 5.9.55 was released, so it will probably be in the next release.

**Comment by broyuken** [comment]
But then it wouldn’t be added to HA for another 6 months or so right?

**Comment by spacegaier** [comment]
That timeline is out of our control. Once a new MDI version is released we can include it in the HA frontend if it does not break anything. 5.9.55 was released on Jan 16, but looking at the previous releases there doesn't seem to be a fixed periodic rhythm: https://github.com/Templarian/MaterialDesign-JS/releases
