### ISSUE TITLE
light.nnn call services missing from Automations editor

### ISSUE THREAD

**Issue by drawbars** [home-assistant/frontend#8511]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating a new Automation, or editing a previous one, using the editor found in the Configuration Home Assistant area, there are no Call Service options to access Light entities.  One can go into automations.yaml and create them by hand, but if one selects an action of Call Service, there are no functions such as light.turn_on or light.turn_off.  In fact, the only 'L' services listed are lock and logbook functions.  If the element has a switch alias, then the equivalent switch.turn_on, etc. function can be used, but most light elements do not have these aliases.  Editing the YAML file by hand allows a workaround, with the caveat that one must know the 'long' entity name for the Light.

### Describe the behavior you expected

In past versions of HA, selecting Call Service and then typing "light." will bring up a series of Light-related functions:  light.toggle, light.turn_on, etc.  Typing the same six characters does nothing.

### Steps to reproduce the issue

1.  Open Configuration in the UI, then Automations.
2.  Choose Add Automation, or edit and existing Automation.
3.  Add an Action of Call Service.
4.  Attempt to choose light.turn_on as the service.
5.  Note that this is not a choice.
6.  Choose switch.turn_on, and if the device has both light and switch entities, then select the equivalent switch value.  If no switch value is available, choose any other switch Entity, and then edit automations.yaml to change the Action to light.turn_on.
7.  Reload the Automations, and note that the light.turn_on function works properly.
...

### What version of Home Assistant Core has the issue?

core-2021.2.3

### What was the last working version of Home Assistant Core?

core 2020-11.x

### Which operating system are you using to run this browser?

MS Windows 10 Pro

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by spacegaier** [comment]
All my instances are already updated to 2021.3.x and there it works fine. All three light services (on, off, toggle) appear in the list and can be selected.

**Comment by drawbars** [comment]
Good to know.  The update doesn't show up in Supervisor Dashboard, so I can't confirm.  Is there another way to get it, other than waiting for Wednesday?

**Comment by spacegaier** [comment]
By switching to the beta channel in the Supervisor settings.

**Comment by drawbars** [comment]
Confirmed -- 2021.3.0b6 does NOT have this issue, as 2021.2.3 did.  I will close this bug.
