### ISSUE TITLE
spacing between title and button on mobile confirmation window too extreme

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#8513]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

spacing between the title and the button is way too extreme. Missed it a few times, because of hands holding the device covering the button. In any case the eyemovement needed for this screen is unnecessary ;l-)

### Describe the behavior you expected

centralize both title and button, or at least have the button be closer to the title

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

latest beta 06

### In which browser are you experiencing the issue with?

Safari on iOS

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

![20210302_083339000_iOS](https://user-images.githubusercontent.com/33354141/109628361-f5649600-7b42-11eb-8ad2-4677874d454c.png)

**Comment by bramkragten** [comment]
The idea is that buttons on mobile are easier reachable on the bottom of the screen.

**Comment by Mariusthvdb** [comment]
well, yes, I understand that of course.
but, tbh, there's an awful lot of white space there.. and, as you can see the Ok button is dangerously close to the iOS interface handle. Which caused the bad user experience on my side (didnt see the button at all...)

this (desktop) seems so much more eye-friendly (though inherently the same, message top left, button bottom right, I see that ):

<img width="623" alt="Schermafbeelding 2021-03-02 om 10 40 44" src="https://user-images.githubusercontent.com/33354141/109630267-031b1b00-7b45-11eb-886a-71b002732f74.png">

**Comment by bramkragten** [comment]
This could be an option:
![image](https://user-images.githubusercontent.com/5662298/109630655-7755be80-7b45-11eb-8ea2-e4e392ec1170.png)

It is what we did in the past.

**Comment by Mariusthvdb** [comment]
yeah, I would feel that to be far superior, and more beautiful too. 
It was on more screens, I think I saw these too when updating Supervisor and Core? And Add-on's. Not sure though. (of the top of my head here now)

**Comment by Mariusthvdb** [comment]
still happening on 2021.6.0b2

**Comment by Mariusthvdb** [comment]
and on 2021.9

**Comment by Mariusthvdb** [comment]
still on 2021.12

**Comment by Mariusthvdb** [comment]
still the case, but if no further action will be taken, might as well close?

**Comment by Mariusthvdb** [comment]
still there
