### ISSUE TITLE
back arrow on integrations doesnt always respond at all

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#8514]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

and needs several clicks before finally going back. as posted in Discord, this is what happens: on a device page, the entities are listed, I dis/enable a certain entity, click ok, and then are returned to the device page. top left icon which should take me back to all devices needs to be clicked multiple times (just tested and it took 3) before landing on the devices dashboard

### Describe the behavior you expected

always immediately go back on click

### Steps to reproduce the issue

1. on a device page, the entities are listed, I dis/enable a certain entity
2. click ok, then are returned to the device page
3. top left icon which should take me back to all devices needs to be clicked multiple times
...

Often it is quicker to reload integrations from configuration/integrations which always works

### What version of Home Assistant Core has the issue?

2021.3.0b6

### What was the last working version of Home Assistant Core?

not sure

### In which browser are you experiencing the issue with?

Safari on iOS, Safari desktop

### Which operating system are you using to run this browser?

Big sur 11.2 Safari 14.0.3

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

nothin really, cant be more precise

**Comment by vvuk** [comment]
I think this is a Safari issue.  I've seen this with both the HA app on iOS (due to webview) and Safari on iOS, but I don't see it with Firefox or Chrome on Windows.

**Comment by RichieFrame** [comment]
It is not just Safari. This also occurs for me using Firefox ESR 78 on Ubuntu Linux with KDE (x11)

**Comment by jes1417** [comment]
Also, in the Android app as well as Chrome on Android, Chrome on Linux and Chrome on Windows.

**Comment by ktownsend-personal** [comment]
This issue caused me extreme frustration in the iOS companion app for several days. I was stuck on the z-wave integration config screen. The back arrow just flashed the current view as if it was reloading it. No amount of clicking the back arrow would take me to the previous screen. I was probably on that screen when my phone screen locked, and then upon resuming I was stuck on that screen. My guess is that the navigation history was not restored when the app resumed. At the time, I wasn't aware of swiping in from the left to get the side menu, so I was effectively stuck on that screen without any visible way to go back to the main dashboard.

**Comment by bramkragten** [comment]
This should be fixed in the next release
