### ISSUE TITLE
Number of disabled integration is always 1

### ISSUE THREAD

**Issue by Guyohms** [home-assistant/frontend#8537]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When disabling integrations there's a note on top showing the number of disabled integrations and it always shows 1.

### Describe the behavior you expected

Show the right amount of disabled integrations

### Steps to reproduce the issue

1. Disable 2 or more integrations
2. Look at the top right of the page

### What version of Home Assistant Core has the issue?

core-2021.3.0

### What was the last working version of Home Assistant Core?

core-2021.2.3

### In which browser are you experiencing the issue with?

Chrome 88.0.4324.190, Firefox 85.0.2

### Which operating system are you using to run this browser?

Windows 10 20H2

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

![image](https://user-images.githubusercontent.com/44414660/109895298-f8ec4000-7c5c-11eb-97aa-8270790e681a.png)

![image](https://user-images.githubusercontent.com/44414660/109895330-073a5c00-7c5d-11eb-9f54-4203383f6dc1.png)

I realize that maybe it's because all my disabled integrations are from ESPHome but I think it should still show that I have 3 disabled integrations.

**Comment by bramkragten** [comment]
You are correct, it now shows the number of hidden cards.
