### ISSUE TITLE
supervisor-2021.03.3 delete custom repository not working

### ISSUE THREAD

**Issue by shirou93** [home-assistant/frontend#8540]
### Describe the issue you are experiencing

When i try delete custom repository in store nothing happening.

### What is the used version of the Supervisor?

supervisor-2021.03.3

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

Debian 10

### What version of Home Assistant Core is installed?

core-2021.3.0

### Steps to reproduce the issue

1. Go to store
2. Repositories
3. Try delete 

### Anything in the Supervisor logs that might be useful for us?

```txt
# Put your logs below this line

```

**Comment by ludeeus** [comment]
Fixed in https://github.com/home-assistant/frontend/pull/8536
