### ISSUE TITLE
Adding a repository replaces all other repositories

### ISSUE THREAD

**Issue by einschmidt** [home-assistant/frontend#8541]
### Describe the issue you are experiencing

After adding a new repository, all existing and configured repositories were removed and replaced with the new one.

### What is the used version of the Supervisor?

supervisor-2021.03.3

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.12

### What version of Home Assistant Core is installed?

core-2021.2.3

### Steps to reproduce the issue

1. Open Supervisor panel
2. Open Add-on Shop
2.b Notice that you have for example 2 or more repositories installed. In my case, Offical add-ons and repository A (example)
3. Click three dots
4. Click Repositories
5. Enter a repository URL
6. Click Add
7. Click Close
8. Notice that there are still only 2 repositories: Official add-ons and repository B. repository A disappeared.

### Anything in the Supervisor logs that might be useful for us?

```txt
21-03-04 07:13:19 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/hassio-addons/repository repository
21-03-04 07:13:21 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://github.com/einschmidt/hassio-addons
21-03-04 07:13:22 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 43 new - 3 remove
```

**Comment by ludeeus** [comment]
Fixed in https://github.com/home-assistant/frontend/pull/8536
