### ISSUE TITLE
Edit YAML still broken on iOS with code mirror 6 (copy, paste, replace issues)

### ISSUE THREAD

**Issue by hagenuck1** [home-assistant/frontend#8542]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Copy and paste still has some issues with code mirror 6 on iOS (tested in safari & Home Assistant App).
Issues in Script Editor > Actions > Edit in Yaml:
- Double tapping a word and "cut" it cuts the whole line
-- Pasting it pasts the whole line
- Double tap a word and clicking the "delete" button on keyboard deletes only one letter at the position you double tapped
- mark multiple lines, cut them and paste them only cuts/ pasts the last line

YAML Editors on Lovelace cards have the same issues as with code mirror 5.

Deleted "all website data" in Settings > Safari > Website Data (Did not delete my whole history).

### Describe the behavior you expected

Boeing able to copy, paste and replace like the demo on www.codemirror.net/6

### Steps to reproduce the issue

1. Open a new script in the editor and select "Edit in YAML" for the action
2. Try to cut/copy a single word or multiple lines or mark one word to delete it
3. Try to edit yaml of a Lovelace card
...

### What version of Home Assistant Core has the issue?

2021.3.0

### What was the last working version of Home Assistant Core?

-

### In which browser are you experiencing the issue with?

iOS 14.4 Safari

### Which operating system are you using to run this browser?

iOS 14.4

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

Issue #8534 should have been fixed by pull request #8382

**Comment by bramkragten** [comment]
If you see the exact same behavior as with the previous version, and the demo of codemirror 6 works, I would say your cache is not cleared correctly?

**Comment by hagenuck1** [comment]
I deleted "All Website Data" as written, as I hoped to be able to preserve my history data.
I did a "Delete all History and data" for safari now.
Re logged in, but the same behavior is still present.
Restarted the iPhone > Same issue
User Safari private Tab > Same issue
Deleted "Frontend Cache" in Home assistant app > Same issue

So I think the cache should not be the issue.

**Comment by bramkragten** [comment]
https://github.com/codemirror/codemirror.next/issues/414

**Comment by hagenuck1** [comment]
![image](https://user-images.githubusercontent.com/15811973/109964077-7f506280-7ced-11eb-87b9-67b8275e3ae0.gif)

[](https://github.com/codemirror/codemirror.next/issues/414)

**Comment by hagenuck1** [comment]
![image](https://user-images.githubusercontent.com/15811973/109964077-7f506280-7ced-11eb-87b9-67b8275e3ae0.gif)

codemirror/codemirror.next#414

**Comment by aptonline** [comment]
I’m seeing the same issue on iOS. Used ‘Reset Frontend Cache’ within home assistant app and still unable to select, copy, paste consistently where as the Codemirror 6 demo (https://codemirror.net/6/) works perfectly.

**Comment by aptonline** [comment]
Issues still present in 2021.3.1.

Also in latest version a horizontal white selection is seen before selecting anything which isn’t an issue in non dark mode themes but light themes obscure the selection text.

**Comment by hagenuck1** [comment]
I've just seen, that you implemented codemirror/view release 0.18.0 and I only guessed it was codemirror/codemirror.next, as "better mobile support" was mentioned. 
Sorry for that. 

As the current codemirror 5 version isn't working fine on mobile I guess we'll wait for codemirror.next to be in a stable state and integrated in home assistant for this to be fixed.

**Comment by bramkragten** [comment]
We do use codemirror/next

**Comment by dentra** [comment]
I have the same issue on iOS (MobileApp, Mobile Safari, Mobile Chrome) and it is always reproducible. Can paste only on top of edit area no matter where cursor is. Can't delete any symbol at any position, only when I select something and write a letter it replaces the selection and after that cursor is immediately moving at top left position. Now the yaml editor is fully unusable in IOS :(

I've checked Codemirror 6 demo too and it is works fine.

**Comment by bramkragten** [comment]
I updated the upstream issue with a repo.
https://github.com/codemirror/codemirror.next/issues/414#issuecomment-821139160
