### ISSUE TITLE
In addon config options the save button text is SAVE SAVE

### ISSUE THREAD

**Issue by jeroenhoebe** [home-assistant/frontend#8544]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The save button for options in the addon config tab will show 'save save'. because the text save is still hardcoded in there and also using translation 

### Describe the behavior you expected

only one save

### Steps to reproduce the issue

Just check options in addon config

### What version of Home Assistant Core has the issue?

core-2021.3.0

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

see line 168 in file `frontend/hassio/src/addon-view/config/hassio-addon-config.ts`

`Save ${this.supervisor.localize("common.save")}`

should be 
`${this.supervisor.localize("common.save")}`

**Comment by frenck** [comment]
Fixed in #8532
