### ISSUE TITLE
Cannot delete automation that was created via the UI

### ISSUE THREAD

**Issue by ziv1234** [home-assistant/frontend#8548]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I created an automation via the UI. I cannot delete it via the UI. I am using automation.yaml 

when i got to configuration -> entities, select it and click "remove selected", I get the following error:

Only 0 selected entities can be removed.
You can only remove 0 of the selected 1 entities. Entities can only be removed when the integration is no longer providing the entities. Sometimes you have to restart Home Assistant before you can remove the entities of a removed integration. Are you sure you want to remove the removable entities?

When I still click "remove", nothing happen

I tried restarting several times but it persists

### Describe the behavior you expected

I expected that once i click "remove selected", it will be deleted.

### Steps to reproduce the issue

1.Create a simple automation from the UI and save
2.try to delete it
3.
...

### What version of Home Assistant Core has the issue?

core-2021.2.3

### In which browser are you experiencing the issue with?

Google Chrome 88.0.4324.190 

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by spacegaier** [comment]
Automations have to be deleted through Configuration -> Automations.

**Comment by ziv1234** [comment]
That was what i assumed, but i have no option to delete there

**Comment by spacegaier** [comment]
It is a bit hidden. You have to enter the automation edit mode and then use the three dot menu.
