### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by crispy78** [home-assistant/frontend#8550]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the Add-on information there is a translation error (Dutch language) that gives the following error:
Translation Error: The intl string context variable "naam" was not provided to the string "Bezoek de {naam} pagina voor meer details"

The same issue is there on the Supervisor System page with the "Restart Core" and "Restart Supervisor" button:
Translation Error: The intl string context variable "naam" was not provided to the string "Herstart {naam}"
Translation Error: The intl string context variable "naam" was not provided to the string "Weet u zeker dat u {naam} opnieuw wilt starten?"

### Describe the behavior you expected

The items should be displaying the correct text.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.3.0

### In which browser are you experiencing the issue with?

Firefox 85.0.2 (64-bit), Microsoft Edge Version 88.0.705.81 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 19041.804

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by spacegaier** [comment]
That means that someone in the community did translate a placeholder which is wrong. I fixed the ones I saw and it seems the others you mentioned were already corrected by someone else.

The new translations will be part of the next frontend release.

**Comment by bramkragten** [comment]
This should be fixed in the translations, the placeholders should not be translated.

You can fix this yourself:

https://developers.home-assistant.io/docs/translations/

**Comment by DigiLive** [comment]
I've just checked and I think it was corrected already:
![afbeelding](https://user-images.githubusercontent.com/7613487/111132514-bf2f0980-8579-11eb-918f-c73fd3112f4a.png)

**Comment by bramkragten** [comment]
yes, so now wait for a new version.
