### ISSUE TITLE
New colors in template editor make it very hard to read in dark theme

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#8552]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

having a hard time reading the template editor when using a dark theme 

### Describe the behavior you expected

have it use less colors, or at least do some auto coloring against the theme

### Steps to reproduce the issue

1. enter any template in the editor
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.3.0

### What was the last working version of Home Assistant Core?

2021.2.3

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

<img width="1331" alt="Schermafbeelding 2021-03-04 om 22 52 57" src="https://user-images.githubusercontent.com/33354141/110036249-04169d00-7d3d-11eb-8054-93ff03055b2b.png">

**Comment by bramkragten** [comment]
I don't think there are new colors?

And all these colors are themeable.

**Comment by spacegaier** [comment]
Readability is good with the HA default dark theme. Looks like you are using a custom theme that is not optimized for the editor.

![image](https://user-images.githubusercontent.com/114137/110040819-ad609180-7d43-11eb-8e21-f5dce5b02fb1.png)

**Comment by Mariusthvdb** [comment]
its a matter of not knowing we can (need ) to use code mirror variables,

Know now ;-) https://discord.com/channels/330944238910963714/460846676358332417/817323378654052383
thanks!
