### ISSUE TITLE
UI yaml editor active line unreadable in dark mode

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/frontend#8556]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The active line in the UI yaml editor has a white background, so some text is unreadable in dark mode.
See screenshot in Additional information.

### Describe the behavior you expected

See the code

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.3.1

### What was the last working version of Home Assistant Core?

core-2021.3.0

### In which browser are you experiencing the issue with?

Latest FF and Chrome

### Which operating system are you using to run this browser?

Ubuntu 18.03

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

![Auswahl_454](https://user-images.githubusercontent.com/26381449/110094390-0eb44f00-7d9c-11eb-9dca-2fd5ff3438da.png)

**Comment by spacegaier** [comment]
Yes, we are already aware and it will most likely be fixed in dev tonight.
