### ISSUE TITLE
black cursor on codemirror editor - reverted 

### ISSUE THREAD

**Issue by scooper1** [home-assistant/frontend#8570]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

standard dark theme 
we have gone back to black cursor  after fix to from over bright selection line

### Describe the behavior you expected

either a inverting cursor or a contrast colour cursor

### Steps to reproduce the issue

1. enter codemirror editor
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.3.2

### What was the last working version of Home Assistant Core?

core-2021.2.0

### In which browser are you experiencing the issue with?

chrome

### Which operating system are you using to run this browser?

windows 10

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by VDRainer** [comment]
Thanks for reporting.
I didn't dare because I've already reported some codemirror issues. :rofl:

**Comment by scooper1** [comment]
Yep I am sure they are fed up with me as well  but they have tried to fix issuesOn 6 Mar 2021 17:31, VDRainer <notifications@github.com> wrote:

Thanks for reporting.

I didn't dare because I've already reported some codemirror issues. 🤣

**Comment by scooper1** [comment]
It looks like a complete revert as search and no history bugs are back 
going to have to revert to older version of core
