### ISSUE TITLE
Ingress session cookie is set with SameSite=Strict

### ISSUE THREAD

**Issue by gcampax** [home-assistant/frontend#8580]
### Describe the issue you are experiencing

Judging from the resolution of https://github.com/home-assistant/supervisor/issues/1044, it seems that crafting URLs to the addons and calling them from outside is a supported setup, but these URLs do not work at all at the moment because the "ingress_session" cookie has SameSite=Strict so it is not passed on redirects or links (at least in Chrome).

This affects in particular configuring OAuth skills in Almond, because the OAuth redirects cannot complete to the add-on.
We're thinking of working around this issue by not using the ingress at all, and exposing our own port, but if we can solve the underlying issue I think it will be a lot better.

### What is the used version of the Supervisor?

git master

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

n/a

### What version of Home Assistant Core is installed?

n/a

### Steps to reproduce the issue

1. Pass an add-on ingress URL to a third-party website
2. Have that website perform a redirect to the given URL or show a clickable link to that URL
3. Observe the 401 error instead of the expected page

### Anything in the Supervisor logs that might be useful for us?

n/a

**Comment by frenck** [comment]
This is handled by the frontend, transferring the issue.

**Comment by gcampax** [comment]
This issue still exists, but it will be resolved in a different way that does not require changes to the frontend.
