### ISSUE TITLE
Service Call UI Area Picker always returns "No matching areas found"; Specifying an Area with YAML works

### ISSUE THREAD

**Issue by Ikcelaks** [home-assistant/frontend#8589]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I attempt to target an Area with the new UI, it always returns "No matching areas found".  This happens everywhere the Area Picker UI is found (Developer Tools, Automations, and Blueprints).

If I switch to YAML Mode and specify an Area target.  The Service Call works as expected.  Also, if I then switch back to UI Mode, the Area does display and act correctly (I can remove it or expand it into the list of devices).

### Describe the behavior you expected

I expect clicking the "Pick area" button will produce a dropdown of areas that contain devices / entities matching the Service.

### Steps to reproduce the issue

1. Go to "Developer Tools" -> "Services".
2. Choose a Service that matches one or more devices in an area.
3. Click "Pick area" in the target section.

### What version of Home Assistant Core has the issue?

core-2021.3.2

### In which browser are you experiencing the issue with?

Google Chrome 89.0.4389.72; Microsoft Edge;

### Which operating system are you using to run this browser?

Windows 19042.804

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

This issue seems to be affecting a few users, but not most users.

This forum comment describes the same problem:
https://community.home-assistant.io/t/2021-3-my-oh-my/286346/24?u=ikcelaks 

Others are reporting a similar issue with the Entity picker (which works fine for me):
https://community.home-assistant.io/t/2021-3-my-oh-my/286346/328?u=ikcelaks

**Comment by bramkragten** [comment]
I would need more info to debug this, it is working for me.

- What service are you using?
- What devices & states are in your areas?

No errors?

**Comment by dannytsang** [comment]
I'm also seeing similar issue. I used turning light on as an example but seems to occur regardless what service is being called.

Bathroom area appears in developer tools > Services
![image](https://user-images.githubusercontent.com/567982/110359114-0460b200-8035-11eb-8d61-ae791e29b7db.png)


Example where other lights exist in other areas:
![image](https://user-images.githubusercontent.com/567982/110359325-4689f380-8035-11eb-8df8-9dd57a21d095.png)


List of areas configured:
![image](https://user-images.githubusercontent.com/567982/110359357-50abf200-8035-11eb-81be-d0d3010ad1ae.png)

Let me know if there's anything else and I can try and provide more information.

**Comment by dannytsang** [comment]
Oh error wise nothing that I can see. All configurations validated successfully as well.

**Comment by frenck** [comment]
Can reproduce the same, no errors; only shows 1 matching area. Devices & entities pickers do contain all items from all areas.

**Comment by Ikcelaks** [comment]
I just discovered that I can make an Area show up by directly adding an appropriate Entity to an Area.  Prior to adding the entity to the Area, it was following the device area.  Afterwards, I reverted to "Follow the device area", and I once again wasn't able to select the Area through the UI.

**Comment by bramkragten** [comment]
Ok thanks for the info all! That should help.
