### ISSUE TITLE
How to remove the left and right space areas please help me out

### ISSUE THREAD

**Issue by horacecar** [home-assistant/frontend#8592]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

How to remove the left and right space areas please help me out. 
ios app and iphone safari is same. please look at my screen shot

using iphone 12 pro max , ios:14.3
and also the upper left corner menu button is missing and cannot click it.

### Describe the behavior you expected

How to remove the left and right space areas please help me out. using iphone 12 pro max , ios:14.3
and also the upper left corner menu button is m

### Steps to reproduce the issue

1. already try to change another image or color.

### What version of Home Assistant Core has the issue?

2021.3.1

### In which browser are you experiencing the issue with?

SAFARI

### Which operating system are you using to run this browser?

WIN 10

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

![0307174512](https://user-images.githubusercontent.com/44496483/110371614-2e8f8f80-8088-11eb-8f19-250edd07bcbe.jpg)

**Comment by horacecar** [comment]
Dont know if another people is same with me. 

may be it is regarding safe area of ios safari ?

https://webkit.org/blog/7929/designing-websites-for-iphone-x/

**Comment by bramkragten** [comment]
This is a support question, please use discord. https://www.home-assistant.io/help/
