### ISSUE TITLE
Sonos logo on integration card almost invisible in 'dark' mode

### ISSUE THREAD

**Issue by Didel** [home-assistant/frontend#8607]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When viewing all the integrations on [homeassistant-url]/config/integrations (Let's give this new fancy 'My Home assistant' thing a try : [![Open your Home Assistant instance and show your integrations.](https://my.home-assistant.io/badges/integrations.svg)](https://my.home-assistant.io/redirect/integrations/)) with the 'dark mode' enabled, the Sonos logo has almost the same color as the background color of the card. That makes the logo almost invisible, and makes it look like the card has no logo at all:

![Schermafbeelding 2021-03-09 om 21 56 19](https://user-images.githubusercontent.com/915243/110537258-bde98100-8122-11eb-8d02-d058574f65c3.png)

### Describe the behavior you expected

I would expect the logo to be (more) clearly visible. My personal preference would be to have separate logo's for the 'light mode' and 'dark mode' themes, but that will require more work in order to make that a generic feature available to all integrations. Other integrations use logo's that use a 'pure black' color (`#000000`), that works much better with the current background color of the card (`#1c1c1c`) and will also work well in the 'light' mode. 

### Steps to reproduce the issue

1. Add/enable the Sonos integration in Home Assistant and make sure the Sonos integration card shows up on `/config/integrations` .
2. Enable dark mode in the theme
3. Visit `/config/integrations` in your browser and notice the Sonos logo is very difficult to see agains the integration-card gray background
...

### What version of Home Assistant Core has the issue?

core-2021.3.3

### In which browser are you experiencing the issue with?

Safari 14.0.3 , Google Chrome 88.0.4324.192

### Which operating system are you using to run this browser?

macOS Catalina 10.15.7

Image that shows the problem:

![Schermafbeelding 2021-03-09 om 21 56 19](https://user-images.githubusercontent.com/915243/110537258-bde98100-8122-11eb-8d02-d058574f65c3.png)

**Comment by spacegaier** [comment]
I noticed the same. However, currently the HA brands repository (that is where all the logos reside) does not support a dark mode. But even if it did: We never modify the official logos and the Sonos only provides a black one (where as other companies provide multiple to also support dark themes)

**Comment by Didel** [comment]
> Sonos only provides a black one (where as other companies provide multiple to also support dark themes), see https://www.sonos.com/en-us/media-kits.

I don't think the logo currently shown in the integration card is the 'official' logo (or actually I suspect a slight rebranding from Sonos since the logo was added) : The logo in the integration card is gray with a very slight gradient, while the logo on the Sonos website (both in the header and the [horrible cut-out/'magic wanded' PNG file](https://user-images.githubusercontent.com/915243/110542975-05bfd680-812a-11eb-9650-0b9b926c60f9.png) you can download under the 'Corporate Materials' section of the page you linked) has a 'pure black' color.

I have also just noted the separate Brands repository, if you don't mind I will create a PR in there to replace the logo with the official 'black' one (but one deducted from the SVG source on the website in stead of the terrifying PNG file they have supplied as 'Corporate material').

![Sonos_Logo](https://user-images.githubusercontent.com/915243/110542975-05bfd680-812a-11eb-9650-0b9b926c60f9.png)

**Comment by spacegaier** [comment]
Okay, then I think this issue can be closed since your brand PR should take care of it?
