### ISSUE TITLE
Configuration > Info shows the wrong section title

### ISSUE THREAD

**Issue by tdejneka** [home-assistant/frontend#8612]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In 2021.**2**.3, Configuration > Info reported System Health's second section with the following title:
**Home Assistant Supervisor**

In 2021.**3**.3, the same section's title is:
**Hass.io**

### Describe the behavior you expected

Unless there's been a design design to revert to using the old name, the section's title should be "Home Assistant Supervisor".

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.3.3

### What was the last working version of Home Assistant Core?

2021.2.3

### In which browser are you experiencing the issue with?

Firefox 86.0

### Which operating system are you using to run this browser?

Ubuntu 20.04

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

In 2021.**2**.3

![Screenshot from 2021-03-10 08-55-44](https://user-images.githubusercontent.com/44732909/110641112-9a085880-817f-11eb-80f2-8b69783cccc5.png)

In 2021.**3**.3

![Screenshot from 2021-03-10 08-56-20](https://user-images.githubusercontent.com/44732909/110641199-b73d2700-817f-11eb-90c6-181a296f8748.png)

**Comment by bramkragten** [comment]
Fixed this in the backend Lokalise translations.

**Comment by tdejneka** [comment]
Glad to hear it was fixed. Do you know in which release the correction will appear? I can confirm that it still says `Hass.io` in 2021.3.4.

**Comment by bramkragten** [comment]
In 2021.4
