### ISSUE TITLE
Optional add-on option, not unsettable via the UI

### ISSUE THREAD

**Issue by frenck** [home-assistant/frontend#8614]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Once an optional add-on option is set; it cannot be unset.

### Describe the behavior you expected

Being able to unset optional parameters.

### Steps to reproduce the issue

1. Install a community add-on
2. Show hidden options
3. Set log level
4. Save configuration
5. Try unsetting it...
...

### What version of Home Assistant Core has the issue?

not related.

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

For example; this debug log variable; is optional... once set, it isn't removable/unsettable.

![image](https://user-images.githubusercontent.com/195327/110702906-6b2bca00-81f3-11eb-858f-a0b4c1cf2259.png)

**Comment by frenck** [comment]
Not stale, thanks bot :)

**Comment by frenck** [comment]
Not stale bot :)

**Comment by ludeeus** [comment]
Even if stale/closed, it was still not dismissed in my notifications 😄
