### ISSUE TITLE
Entities checkbox selection drawing issues

### ISSUE THREAD

**Issue by jjlawren** [home-assistant/frontend#8619]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On the entities page (`/config/entities`), scrolling while any checkboxes are selected causes other entities to randomly appear selected.

### Describe the behavior you expected

Only actually selected entities should display as such.

### Steps to reproduce the issue

1. Check a box
2. Scroll

### What version of Home Assistant Core has the issue?

2021.3.2

### In which browser are you experiencing the issue with?

Chrome 89.0.4389.82

### Which operating system are you using to run this browser?

macOS Catalina 10.15.7

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by jjlawren** [comment]
This seems to affect any list of entities, such as "Add Card > By Entity".

**Comment by fubar-coder** [comment]
Happens for me too:

- Firefox 87.0 (64-Bit)
- Windows 10 20H2 (Build 19042.867)
- NVidia RTX2060
- Home Assistant 2021.3.4
