### ISSUE TITLE
The translation for the word "run" for scripts is not displayed in Polish

### ISSUE THREAD

**Issue by bieniu** [home-assistant/frontend#8620]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After updating HA to 2021.3.x, the translation for the word `run` for scripts is not displayed in Polish.

![image](https://user-images.githubusercontent.com/478555/110907955-6ad42180-830e-11eb-9ce9-b050e1eaf9d6.png)

At `lokalise.com`, this word is translated a long time ago.

![image](https://user-images.githubusercontent.com/478555/110908246-d1f1d600-830e-11eb-903a-8bc78ec1db69.png)

### Describe the behavior you expected

Frontend should display translated word.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.3.X

### What was the last working version of Home Assistant Core?

core-2021.2.X

### In which browser are you experiencing the issue with?

Opera/Edge/Chrome/Android HA Companion

### Which operating system are you using to run this browser?

Windows 10/Linux

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by spacegaier** [comment]
Works fine for me in German. What language are you using?

**Comment by bieniu** [comment]
I use Polish, but I also check Slovenian. Now I checked Slovenian once again and this word is not translated 🤦‍♂️ So it only applies to the Polish language.

**Comment by spacegaier** [comment]
I checked the Polish translations. They are already adjusted in the development version (just tested locally as well), but the translation files of the current release version did not yet contain it (this specific key was added on 02.03.2021), hence the English fallback.

**Comment by bieniu** [comment]
Thanks for help.
