### ISSUE TITLE
Pi-Hole integration config has no field for API key

### ISSUE THREAD

**Issue by jeremysherriff** [home-assistant/frontend#8660]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Pi-Hole integration used to have a field for API key during configuration.  This field is no longer visible, although I am unsure what version it disappeared in.

The API field is noted in the documentation, and enables extra functionality in the form of a switch entity and a service to disable pi-hole.

### Describe the behavior you expected

I expected a field to paste the API key during integration setup.

### Steps to reproduce the issue

1. Remove any existing Pi-Hole integration
2. Add a new Pi-Hole integration, following current documentation (configuration -> integrations -> add integration -> pi-hole)
3. Note no field for API key

### What version of Home Assistant Core has the issue?

core-2021.3.4

### In which browser are you experiencing the issue with?

Chrome 89.0.4389.82 and Edge 89.0.774.54

### Which operating system are you using to run this browser?

Windows 10 20H2

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

![image](https://user-images.githubusercontent.com/1082213/111426201-2c4cc580-8759-11eb-9628-d9aa9805e80b.png)

**Comment by frenck** [comment]
This is not a frontend issue.

As for your question, uncheck statistics only and it will ask for an API key in the next step. Running statistics-only mode would not need an API key.

**Comment by jeremysherriff** [comment]
Apologies, the hints for logging issues in the core lead me to believe this is frontend rather than backend.
Also, the doco makes no mention of the `statistics only` option.

I can confirm the disabling `statistics only` then enables the API key field on the next screen. Thanks.
