### ISSUE TITLE
Chrome 89 throws PWA installability warning

### ISSUE THREAD

**Issue by hmmbob** [home-assistant/frontend#8663]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

While checking the Chrome Console looking for something else, I noticed that Chrome 89 is now throwing a warning about the installability (?) of the PWA:

```txt
Site cannot be installed: Page does not work offline. Starting in Chrome 93, 
the installability criteria is changing, and this site will not be installable. 
See https://goo.gle/improved-pwa-offline-detection for more information.
```

![image](https://user-images.githubusercontent.com/33529490/111501718-83489f80-8745-11eb-949e-b8be8d14727c.png)

The [linked page](https://developer.chrome.com/blog/improved-pwa-offline-detection/) explains the issue and provides a timeline:

- Warning starting Chrome 89 (March 2021)
- Enforcement starting Chrome 93 (August 2021) 

### Describe the behavior you expected

No warning - but raising this for awareness

### Steps to reproduce the issue

1. Open HA in Chrome 89+
2. Open Chrome console
3. See error
...

### What version of Home Assistant Core has the issue?

core-2021.3.4

### In which browser are you experiencing the issue with?

Google Chrome 89.0.4389.90 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Win10

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.
Site cannot be installed: Page does not work offline. Starting in Chrome 93, 
the installability criteria is changing, and this site will not be installable. 
See https://goo.gle/improved-pwa-offline-detection for more information.
```

**Comment by bramkragten** [comment]
This is fixed already :-)
