### ISSUE TITLE
History bar graph lost after update

### ISSUE THREAD

**Issue by Tom7320** [home-assistant/frontend#8665]
### The problem

After updating to 2021.3 the bars in History are lost. The graphs are still there.

### What is version of Home Assistant Core has the issue?

core-2021.3.4

### What was the last working version of Home Assistant Core?

<2021.3

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

History

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/history/

### Example YAML snippet

```yaml
# Only:
default_config:
```

### Anything in the logs that might be useful for us?

```txt
2021-03-05 19:25:51 ERROR (MainThread) [frontend.js.latest.202103024] https://tld.com:8123/frontend_latest/chunk.ab01d5a9d4bd1e838d41.js:179:939 Uncaught TypeError: Cannot read property 'attributes' of undefined
```

Discussion about the issue:
[https://community.home-assistant.io/t/history-bar-graph-lost-after-update/287105](url)

**Comment by dudu631** [comment]
Same here!

**Comment by coppensb** [comment]
Same issue after upgrading to core-2021.3.4. Only the graphs appear, tough bar appear when you apply a filter. Following error appeers in the log 2021-03-24 14:57:17 ERROR (MainThread) [frontend.js.latest.202103026] https://xxxxxx.duckdns.org:8123/frontend_latest/chunk.ab01d5a9d4bd1e838d41.js:179:888 TypeError: this.hass.states[t.entity_id] is undefined

**Comment by spacegaier** [comment]
Can someone of you confirm if this info in the linked thread is correct: https://community.home-assistant.io/t/history-bar-graph-lost-after-update/287105/7

**Comment by coppensb** [comment]
My problem have been fixed without doing anything. Not sure what it is but HA seem to have some nice self-healing capabilities! Maybe some history data went corrupt after upgrading.

**Comment by DayRunner131** [comment]
> My problem have been fixed without doing anything. Not sure what it is but HA seem to have some nice self-healing capabilities! Maybe some history data went corrupt after upgrading.

Same here, but it's frustrating that the error is so vague that you can't locate the entity that is corrupted.

**Comment by davek00997744** [comment]
In the end I just dumped MariaDB and it all sorted itself out nicely.

**Comment by spacegaier** [comment]
@Tom7320 Can you as the author of this ticket also confirm that it works now, then we could close this, even though the actual resolution is unknown.

**Comment by von-Chaps** [comment]
I have this problem too. Don't see how/why you would close with "resolution unknown" just because it's mystically gone away for some people.

**Comment by adamstratton** [comment]
This issue is present for me also- change in configuration.yaml to recorder exclude for an entity that no longer exists seems to have an effect. Snapshots made after the error occurs corrupts the database on restore. Not using MariaDB.

**Comment by vturekhanov** [comment]
Same here. Workaround: purge all recorder data.
In my case the error appears again after deleting any entity configured not in GUI.

**Comment by vturekhanov** [comment]
> Can someone of you confirm if this info in the linked thread is correct: https://community.home-assistant.io/t/history-bar-graph-lost-after-update/287105/7

I don't confirm this.

**Comment by vturekhanov** [comment]
> Can someone of you confirm if this info in the linked thread is correct: https://community.home-assistant.io/t/history-bar-graph-lost-after-update/287105/7

I don't confirm this.

> My problem have been fixed without doing anything. Not sure what it is but HA seem to have some nice self-healing capabilities! Maybe some history data went corrupt after upgrading.

Error disappears if "incorrect" data recorded to database not between Start and End date on history page. But if you try to roll back Start date, I guess error appears again.

**Comment by adamstratton** [comment]
After a bit of troubleshooting, I agree with the previous poster- was brought on by modifying the name of a binary sensor (bayesian) in my case. Issue could be replicated with prior versions of HA when older snapshots loaded.

**Comment by davek00997744** [comment]
Its happened again, nothing to do with MariaDB which i first suspected. I added a few sensors today and always rename my devices to suit my flavour, just went to check on one of them and all the bar graph history has gone again.

**Comment by Tom7320** [comment]
Same here. Ich can temporary „solve“ the problem by deleting the database. But it comes back after a while...

**Comment by truglodite** [comment]
Hassos on a pi4 w/ ssd, mariadb... same issue here. Perhaps my issue was also caused by renaming a binary sensor... I think with zwavejs that would be a popular way to stumble on this, as a lot of people are having renaming parties these days.

**Comment by mbo18** [comment]
I have this issue each time I disable or rename an entity that is displayed in the history tab.

2 solutions : wait 1 day or delete the DB...

**Comment by mbo18** [comment]
> Can someone of you confirm if this info in the linked thread is correct: https://community.home-assistant.io/t/history-bar-graph-lost-after-update/287105/7

I'm filtering what to display in the history tab. But if I comment `history:` I still have the issue. Seems to be each time I disable or rename an entity that is displayed in the history tab. And maybe only binary_sensor

**Comment by KimCarlsen** [comment]
It happened to me on HA 2021.4.2 after i disabled some entities in my OnVif intergration. and yes those were binary sensors

**Comment by DayRunner131** [comment]
Happened to me today again after upgrading my Zwave devices which meant that sensor names changed. I also adjusted some template entities. Zero History bar graphs at the moment, though if I select an individual entity, I can see them.

This time, I've received no error. Running core-2021.04.03

**Comment by giuseppefava** [comment]
happened to me too after renaming a device (cell phone). I adjusted all related entities but no bar graphs appears. Individually selection is ok but not full view.

this id the log:
2021-04-14 10:59:54 ERROR (MainThread) [frontend.js.latest.202104073] https://******************/frontend_latest/chunk.3664ebe9901dff2b82a7.js:179:939 Uncaught TypeError: Cannot read property 'attributes' of undefined

**Comment by Z1ni** [comment]
Happened to me after I disabled a couple mobile app sensor entities that I no longer publish from the phone (as the entities can't be deleted - at least not from the UI).

```
Logger: frontend.js.latest.202104073
Source: components/system_log/__init__.py:190
First occurred: 12:02:29 AM (12 occurrences)
Last logged: 12:05:40 AM

http://snip/frontend_latest/chunk.3664ebe9901dff2b82a7.js:179:888 TypeError: this.hass.states[t.entity_id] is undefined
http://snip/frontend_latest/chunk.3664ebe9901dff2b82a7.js:179:939 Uncaught TypeError: Cannot read property 'attributes' of undefined
```

**Comment by Nowaker** [comment]
Same thing happened to me after upgrading from 0.114.4 to 2021.5.5.

**Comment by kobuki** [comment]
Same thing happens on supervised, core-2021.5.5. After renaming and/or disabling binary sensors, the history sausages disappear and either applying a direct filter or changing the display interval makes them appear (but not always). I'm seeing this JS error in the console:

```
Uncaught TypeError: this.hass.states[t.entity_id] is undefined
    drawChart chunk.27fd72e0ede7e3297345.js:1064
    drawChart chunk.27fd72e0ede7e3297345.js:1064
    connectedCallback chunk.27fd72e0ede7e3297345.js:1064
    __insert app.780f338b.js:12797
    __commitNode app.780f338b.js:12797
    __commitTemplateResult app.780f338b.js:12797
    commit app.780f338b.js:12797
    a app.780f338b.js:12797
    render app.780f338b.js:12797
    update app.780f338b.js:12797
    performUpdate app.780f338b.js:12797
    _enqueueUpdate app.780f338b.js:12797
chunk.27fd72e0ede7e3297345.js:1064
```
