### ISSUE TITLE
Mediaplayer card sending "media_play_pause" instead of "media_play"

### ISSUE THREAD

**Issue by definitio** [home-assistant/frontend#8672]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a media player that supports `Play` and `Stop`. When pressing the `Play` button on the card the `media_play_pause` service is called instead of `media_play`. This causes the `Play` command to not work.

### Describe the behavior you expected

Play button should call `media_play` service.

### Steps to reproduce the issue

1. Add a mediaplayer that supports only Stop and Play (not Pause)
2. Navigate to Lovelace
3. Click Play, `media_play_pause` service is called

### What version of Home Assistant Core has the issue?

2021.3.4

### In which browser are you experiencing the issue with?

Firefox 86.0.1

### Which operating system are you using to run this browser?

Arch Linux

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

Button event:
```
{
    "event_type": "call_service",
    "data": {
        "domain": "media_player",
        "service": "media_play_pause",
        "service_data": {
            "entity_id": "media_player.vacuum"
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-19T12:19:30.581563+00:00",
    "context": {
        "id": "28c9d00eecb1dddea87c75525e3d919c",
        "parent_id": null,
        "user_id": "59507d5e859640a88b270a9bb00babe6"
    }
}
```

**Comment by mrand** [comment]
This has been a long standing problem - since before June of 2020 (per issue #6097, which expired with no response).
