### ISSUE TITLE
/config/info still uses Hass.io

### ISSUE THREAD

**Issue by fabaff** [home-assistant/frontend#8675]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

#8240 was closed but the issue not fixed.

### Describe the behavior you expected

Don't use "Hass.io" anymore as the renaming took place a long time ago. 

### Steps to reproduce the issue

Go to /config/info

### What version of Home Assistant Core has the issue?

core-2021.3.4

### In which browser are you experiencing the issue with?

Every browser

### Which operating system are you using to run this browser?

Doesn't matter

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

![Screenshot-20210319185619-606x121](https://user-images.githubusercontent.com/116184/111823301-153ade80-88e5-11eb-8c47-753e5976f7f7.png)

**Comment by spacegaier** [comment]
I can confirm the issue, but the translation has already been fixed however too late for the last release and in the patches translations are not updated by design.
