### ISSUE TITLE
Config pages not available in UI; raspberry docker

### ISSUE THREAD

**Issue by DirkWolthuis** [home-assistant/frontend#8676]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Under the config page multiple pages are not available. For example: config/devices gives back the error: "Error while loading page devices." Also the pages: entities, areas, blueprint and others. Tried in latest Firefox, Chrome and Brave.

### Describe the behavior you expected

That the pages are available. 

### Steps to reproduce the issue

1. Use a Raspberry Pi 3
2. Install docker
3. Run the docker container
```
docker run --init -d \
  --name homeassistant \
  --restart=unless-stopped \
  -v /etc/localtime:/etc/localtime:ro \
  -v /PATH_TO_YOUR_CONFIG:/config \
  --network=host \
  homeassistant/raspberrypi3-homeassistant:stable
```
4. Navigate to {{IP_ADDRESS}}:8123/config/blueprint for example

### What version of Home Assistant Core has the issue?

core-2021.3.4

### What was the last working version of Home Assistant Core?

core-2021.3.3

### In which browser are you experiencing the issue with?

Brave: Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 - 2004

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
app.52350e7c.js:41926 Error loading page devices ChunkLoadError: Loading chunk 2519 failed.
(error: http://torrents:8123/frontend_latest/chunk.506449cdb2e6a2490738.js)
    at Object.s.f.j (http://torrents:8123/frontend_latest/app.52350e7c.js:1314:13241)
    at http://torrents:8123/frontend_latest/app.52350e7c.js:1314:1015
    at Array.reduce (<anonymous>)
    at Function.s.e (http://torrents:8123/frontend_latest/app.52350e7c.js:1314:993)
    at Object.load (http://torrents:8123/frontend_latest/chunk.eaddc20b507c1e8d9611.js:1:13508)
    at HTMLElement.value (http://torrents:8123/frontend_latest/app.52350e7c.js:997:9754)
    at HTMLElement.performUpdate (http://torrents:8123/frontend_latest/app.52350e7c.js:849:111052)
    at HTMLElement._enqueueUpdate (http://torrents:8123/frontend_latest/app.52350e7c.js:849:110704)
```

I new to HA, I don't know what the pages are for but would not expect an error with a new install.

**Comment by DirkWolthuis** [comment]
Downgraded to 2021.3.3 and it works!

**Comment by DirkWolthuis** [comment]
@bramkragten why did you closed the issue, is it a know issue?

**Comment by bramkragten** [comment]
Because I thought it was working? The issue seems to be cache/network related, it can't load a chunk it needs. Did you try to upgrade to 2021.3.4 again?

There were no changes in the frontend between version 2021.3.3 and 2021.3.4

**Comment by DirkWolthuis** [comment]
@bramkragten sure I can try upgrading and report back. But it was a clean install via Docker so I don’t get why caching would be a problem.
