### ISSUE TITLE
When using actions navigate it goes to page partially scrolled

### ISSUE THREAD

**Issue by blair287** [home-assistant/frontend#8686]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using a action like tap action on for example a picture card and using navigation to another page for the first time after webpage or app opened it will go to top of the page it navigated to. 

But after first go if the page is scrolled down on when you press the action is will go to the new page also scrolled down. It should go to the top of the page or have an option to navigate to top or same place in new page.

### Describe the behavior you expected

When using navigate command it should go to the top of the new page 

Or have an option to pick same place on new page or top of new page.

### Steps to reproduce the issue

Add picture use action to link to another page via navigate.

Tap the picture it will go to New page at top of page.

Now scroll down on page with picture then press it will now navigate to new page but scrolled down.

(Make sure your pages have enough card to have to scroll, easier to reproduce on phone)

### What version of Home Assistant Core has the issue?

2021.3.4

### What was the last working version of Home Assistant Core?

Always had issue

### In which browser are you experiencing the issue with?

Chrome, edge and app

### Which operating system are you using to run this browser?

Windows, android

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

https://youtube.com/shorts/NmdSIXCwhIs

Video of issue.

**Comment by blair287** [comment]
Nothing?

**Comment by spacegaier** [comment]
> 
> 
> Nothing?

Well, obviously not. Open source => someone needs to be willing to tackle that.

Regardless, sounds like a duplicate of https://github.com/home-assistant/frontend/issues/8242 to me.
