### ISSUE TITLE
Input_datetime problem

### ISSUE THREAD

**Issue by mrloggyst** [home-assistant/frontend#8694]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When you look at input_datetime (with date and time storage enabled) in the same window or application. And call the service to change its state (example from another window) to set a new date and time. The input_datetime.set_datetime service only sets the date. And it tries to set the time and returns it back (you can see how the hours and seconds twitch at the time of setting). If after that you run input_datetime.set_datetime again, then the time will also be set. 

### Describe the behavior you expected

The call to input_datetime.set_datetime sets both the date and time in one call and the presence or absence of displaying input_datetime does not affect the logic of the input_datetime.set_datetime service 

### Steps to reproduce the issue

First example
1) Create input_datetime with date & time
2) set to value like (2021-01-01 00:01:02)
3) Open window HA where its displayed
4) Call service input_datetime.set_datetime with different value for displayer input_datetime
...
Second example (work normal as it should be)
1) Create input_datetime with date & time
2) set to value like (2021-01-01 00:01:02)
3) Close all window HA where its displayed
4) Call service input_datetime.set_datetime with different value for displayer input_datetime

### What version of Home Assistant Core has the issue?

core-2021.3.4

### What was the last working version of Home Assistant Core?

core-2021.3.4

### In which browser are you experiencing the issue with?

Firefox 86.0.1 (64)

### Which operating system are you using to run this browser?

Windows10

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by spacegaier** [comment]
Does this only affect the rendering but you verified that the actual state of the input_datetime gets correctly updated by the service call?

**Comment by mrloggyst** [comment]
It's really changes a state not only show update

**Comment by spacegaier** [comment]
> 
> 
> It's really change a state not only show update

I am afraid, I do not understand this reply. Could you please rephrase? Thank you.

**Comment by mrloggyst** [comment]
Yes. Affects. The input_date state changes.
