### ISSUE TITLE
Words get cut off in time zone text box on new install

### ISSUE THREAD

**Issue by zolstarym** [home-assistant/frontend#8722]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On a new install using this: https://www.home-assistant.io/installation/raspberrypi#start-up-your-raspberry-pi
After installing and getting to the onboarding part, when it asks for the time zone, data is cut off due to small text box, so it appears that several time zones can't be distinguished from each other

### Describe the behavior you expected

see above

### Steps to reproduce the issue

see picture

### What version of Home Assistant Core has the issue?

hassos_rpi4-64-5.12

### What was the last working version of Home Assistant Core?

none

### In which browser are you experiencing the issue with?

firefox 87

### Which operating system are you using to run this browser?

linux mint

### State of relevant entities

Not set up yet

### Problem-relevant frontend configuration

None

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

![hass](https://user-images.githubusercontent.com/1832149/112561339-a05f1d00-8d9a-11eb-9efb-5bef042e61f5.png)

**Comment by zolstarym** [comment]
Only happens in firefox 87.
Does not happen in chrome

**Comment by spacegaier** [comment]
> 
> 
> Only happens in firefox
> Does not happen in chrome

How does Chrome behave? Show a dropdown box that also covers the elevation and unit system width?

**Comment by zolstarym** [comment]
The dropdown box for chrome had a completely different layout that didn't cut out anything. I didn't grab a screenshot of it at the time and hass.io apparently corrupted its sqlite db, so when I reinstall I can try for a screenshot then.
