### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by dieterbahr** [home-assistant/frontend#8745]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I think I found a bug in the calDAV calendar. Actually two. How and where can I pass this on?
1.) There is only one appointment in the calendar with start time = stop time
      so not a single appointment is displayed anymore
2.) Is an appointment over several days and the start time is included
      0:00 a.m. only the first day of the event is displayed
      No remaining days 

### Describe the behavior you expected

1.) There is only one appointment in the calendar with start time = stop time
      so not a single appointment is displayed anymore
2.) Is an appointment over several days and the start time is included
      0:00 a.m. only the first day of the event is displayed
      No remaining days 

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.3.4

### What was the last working version of Home Assistant Core?

don´t try before

### In which browser are you experiencing the issue with?

Firefox, Chrome, Safari

### Which operating system are you using to run this browser?

Mac OS Mojave

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by spacegaier** [comment]
Potential (partial) duplicate of https://github.com/home-assistant/frontend/issues/7499?
