### ISSUE TITLE
Lovelace doesn't automatically draw Battery Percentage sensors

### ISSUE THREAD

**Issue by dewitpj** [home-assistant/frontend#8754]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am pushing a battery percentage sensor into the MQTT Auto Discovery topic:

Topic : homeassistant/sensor/0x2FFA/BatteryPercentage/config
Value : {"name":"Doorbell Battery Percentage","unique_id":"0x2FFA_battery_percent","device_class":"battery","unit_of_measurement": "%", "state_topic":"z2ha/0x2FFA/battery_percent"}

I then go into the MQTT Integration and I assign the sensor to an area. I then go to the default dashboard and the sensor is not shown. I can however manually add this to another dashboard and it works fine. Other sensors (temperature etc) are automatically added.

### Describe the behavior you expected

I would have expected the sensor to appear on the dashboard

### Steps to reproduce the issue

1. Publish a MQTT topic for a battery sensor (see above for fields, etc)
2. Publish a value
3. Observe missing sensor on default dashboard

### What version of Home Assistant Core has the issue?

core-2021.3.4

### State of relevant entities

```yaml
# Paste your state here.
unit_of_measurement: '%'
friendly_name: Doorbell Battery Percentage
device_class: battery
```

### Problem-relevant frontend configuration

I am using the auto generated dashboard

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

Thanks :)

**Comment by milanmeu** [comment]
A sensor with device_class `DEVICE_CLASS_BATTERY` is not shown.
A binary sensor with device_class `DEVICE_CLASS_BATTERY` or `DEVICE_CLASS_BATTERY_CHARGING` is shown.

The image below displays this. I have named the sensors according to their device_class.
| ![conf](https://user-images.githubusercontent.com/15276289/114683939-bc5a3c80-9d10-11eb-9f55-8a3613950420.png) | ![overview](https://user-images.githubusercontent.com/15276289/114683945-be240000-9d10-11eb-8837-1ed46eca604a.png) |
|-|-|

**Comment by dewitpj** [comment]
Hi,

I am not sure what is meant by your last comment - I have tried changing the MQTT message to match what I think you said but they are still not shown ?

Thanks :)

**Comment by bramkragten** [comment]
It actually is a feature and not an issue. We choose not to show this by default as it might not be that interesting on your dashboard.

If you do want it on your dashboard, you can always take control and add it.

**Comment by dewitpj** [comment]
Surely knowing what state the battery is in for a "remote" sensor is worth it ? This would be one of the major causes of a sensor not working and it would be nice to have a preview of it

(My problem is that I have almost 100 data points and this is not the final state - the generate dashboard works wonders for me during this stage)

**Comment by milanmeu** [comment]
There are several other options to see the battery percentage:
#### Low-Battery notification (2021.3 or higher) 
The easiest solution. Import the blueprint and you're done. More information about this blueprint can be found [here on the forum](https://community.home-assistant.io/t/low-battery-level-detection-notification-for-all-battery-sensors/258664).
[![Open your Home Assistant instance and show the blueprint import dialog with a specific blueprint pre-filled.](https://my.home-assistant.io/badges/blueprint_import.svg)](https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fgist.github.com%2Fsbyx%2F1f6f434f0903b872b84c4302637d0890)

---
#### Separate dashboard
Create an additional Lovelace dashboard and take control of it. You will have to manually add and remove entities.
[![Open your Home Assistant instance and show your Lovelace dashboard config.](https://my.home-assistant.io/badges/lovelace_dashboards.svg)](https://my.home-assistant.io/redirect/lovelace_dashboards/)
You can change the order of the sidebar in [your profile settings](https://my.home-assistant.io/redirect/profile/).

---
#### Generated Lovelace with an additional generated battery view (2021.5 or higher)
This is a new undocumented feature that could potentially change.
 - Download this gist: https://gist.github.com/balloob/4a70c83287ddba4e9085cb578ffb161f
 - Store the file in `<config>/www/balloob-battery-strategy.js`
 - [Add lovelace resource](https://my.home-assistant.io/redirect/lovelace_resources/): `/local/balloob-battery-strategy.js`, type JavaScript Module
 - Take control of the dashboard and replace the configuration with:
 ```yaml
views:
  - title: Home
    strategy:
      type: original-states
  - title: Battery
    strategy:
      type: 'custom:balloob-battery'
```

**Comment by dewitpj** [comment]
> There are several other options to see the battery percentage:
> 
> #### Low-Battery notification (2021.3 or higher)
> The easiest solution. Import the blueprint and you're done. More information about this blueprint can be found [here on the forum](https://community.home-assistant.io/t/low-battery-level-detection-notification-for-all-battery-sensors/258664).
> [![Open your Home Assistant instance and show the blueprint import dialog with a specific blueprint pre-filled.](https://camo.githubusercontent.com/f704cc739e6eaed32da30b62544a89f49ef28b15ed46c1335a505b60b09bb318/68747470733a2f2f6d792e686f6d652d617373697374616e742e696f2f6261646765732f626c75657072696e745f696d706f72742e737667)](https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fgist.github.com%2Fsbyx%2F1f6f434f0903b872b84c4302637d0890)
> 
> #### Separate dashboard
> Create an additional Lovelace dashboard and take control of it. You will have to manually add and remove entities.
> [![Open your Home Assistant instance and show your Lovelace dashboard config.](https://camo.githubusercontent.com/391a4c2330ef2814b519ac4af62ae6a7f3e17b8905ed9bfc46fe0b3fb4abc878/68747470733a2f2f6d792e686f6d652d617373697374616e742e696f2f6261646765732f6c6f76656c6163655f64617368626f617264732e737667)](https://my.home-assistant.io/redirect/lovelace_dashboards/)
> You can change the order of the sidebar in [your profile settings](https://my.home-assistant.io/redirect/profile/).
> 
> #### Generated Lovelace with an additional generated battery view (2021.5 or higher)
> This is a new undocumented feature that could potentially change.
> See 2021.5 release party: https://youtu.be/bvAKUz-bmqU?t=2698.
> 
> * Download this gist: https://gist.github.com/balloob/4a70c83287ddba4e9085cb578ffb161f
> * Store the file in `<config>/www/balloob-battery-strategy.js`
> * [Add lovelace resource](https://my.home-assistant.io/redirect/lovelace_resources/): `/local/balloob-battery-strategy.js`, type JavaScript Module
> * Take control of the dashboard and replace the configuration with:
> 
> ```yaml
> views:
>  - title: Home
>    strategy:
>      type: original-states
>  - title: Battery
>    strategy:
>      type: 'custom:balloob-battery'
> ```
> 
> #### Device list in settings
> If the battery is registered to a device, you can view it in: `settings` >> `devices`.
> [![Open your Home Assistant instance and show your devices.](https://camo.githubusercontent.com/129fe1df43465baabcb78532123bdcaa1b91842eeb05c8f71d0bf4b5f0f0556d/68747470733a2f2f6d792e686f6d652d617373697374616e742e696f2f6261646765732f646576696365732e737667)](https://my.home-assistant.io/redirect/devices/)

I couldn't get the third option to work which would be nice but the notification is awesome - thanks :)
