### ISSUE TITLE
Number formatting not working for input_number

### ISSUE THREAD

**Issue by spacegaier** [home-assistant/frontend#8770]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The selected format does not work for `input_number`.

I have selected "1.234.567,89" and the `input_number` has value "11.0" in the backend, and is rendered as "11.0" instead of the correct "11,0" (decimal comma).

![image](https://user-images.githubusercontent.com/114137/113145492-c408e400-922e-11eb-8953-2b0551e67903.png)

### Describe the behavior you expected

Rendering as "11,0" (decimal comma).

### Steps to reproduce the issue

1. Select format "1.234.567,89" in profile
2. Create `input_number` with value "11.0"
3. Render in entity row
...

### What version of Home Assistant Core has the issue?

Latest dev / beta

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by spacegaier** [comment]
@joshmcrty Can you have a look?

**Comment by bramkragten** [comment]
It doesn't have a unit of measurement, so we don't format the number and use the string from the backend state.

**Comment by joshmcrty** [comment]
Yes I had to add a special case to handle counters for the same reason. I can look at adding a case for input_number too.
