### ISSUE TITLE
multiple view badges overlap

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#8777]
**iOS device model, version and app version**

Model Name: iPhone 11 Pro
Software Version: 14.4.2
App version: 2021.3 (2021.77)

**Home Assistant Core Version**

2021.3.4
**Describe the bug**
Multiple badges in a view overlap, instead of having a full height to display.
**To Reproduce**
simply list more than a view badges:
```
badges:

  - sensor.home_badge
  - sensor.doors_badge

  - sensor.hubs_badge
  - sensor.critical_badge

  - sensor.lights_badge
  - sensor.switch_badge
  - sensor.active_badge
  - sensor.appli_badge

  - sensor.play_badge
  - sensor.track_badge

```
**Expected behavior**

give the second row more headroom 
**Screenshots**

![20210330_210858000_iOS](https://user-images.githubusercontent.com/33354141/113057711-afd0d280-91ad-11eb-989e-01ba09b33a18.jpg)

**Additional context**

**Comment by bramkragten** [comment]
Does this also happen without custom theme and custom components?

**Comment by Mariusthvdb** [comment]
default theme, without custom_header

![20210401_071554000_iOS](https://user-images.githubusercontent.com/33354141/113257500-fec05a00-92ca-11eb-88d1-f27a88e7b5f9.jpg)

**Comment by bramkragten** [comment]
And what custom thing removed the title from the badge? Cause that is probably why this happens.

**Comment by Mariusthvdb** [comment]
these are badges created in python scripts:
```
hass.states.set(badge_id, count, {
  'friendly_name': '',
  fname: desc,
  'unit_of_measurement': fname + ': ' + str(count),
  'entity_picture': picture,
# 'icon': icon,
})
```
No name is needed, so the field is empty, but still there. At least that was what was intended
