### ISSUE TITLE
"No matching entities found" in automation editor

### ISSUE THREAD

**Issue by dgomes** [home-assistant/frontend#8778]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This is related to https://github.com/home-assistant/core/pull/48556

Configuring utility_meter with 2 tariffs a service called "Calibrate" becomes available, this service can use as target a sensor from the utility_meter platform. This all works in YAML, but in the automation editor it gives "No matching entities found"

### Describe the behavior you expected

I expect the filter to work

### Steps to reproduce the issue

1. Create a utility_meter with 2 tariffs in configuration.yaml
2. Go to developer/tools pick service "Utility Meter: Calibrate"

### What version of Home Assistant Core has the issue?

dev

### In which browser are you experiencing the issue with?

Google Chrome 88.0.4324.150

### Which operating system are you using to run this browser?

macOS Big Sur

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by bramkragten** [comment]
Actually it was the other way around :-)
