### ISSUE TITLE
More info navigation bar visibility is affected by dashboard's navigation bar visibility, requiring scrolling to reveal (X)

### ISSUE THREAD

**Issue by zacwest** [home-assistant/frontend#8788]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The more info panel's navigation bar is not initially visible.

### Describe the behavior you expected

The navigation bar and its (X) is visible when initially opening the more info panel

### Steps to reproduce the issue

This only occurs if the navigation bar is hidden when tapping.

1. Scroll down in dashboard, hiding the navigation bar at the top
2. Tap into an entity's more info
3. Note the navigation bar is not revealed for the more info

### What version of Home Assistant Core has the issue?

2021.4.0b0

### What was the last working version of Home Assistant Core?

2021.3

### In which browser are you experiencing the issue with?

iPhone app

### Which operating system are you using to run this browser?

iOS 14.5

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by bramkragten** [comment]
Can you provide a screenshot? Can't seem to reproduce

**Comment by zacwest** [comment]
Oddly enough I can't either now, on the same device! Is there a path somewhere which can cause the navigation bar at the top to start hiding when scrolling the dashboard? It's possible I got myself into _that_ state somehow.

**Comment by bramkragten** [comment]
It shouldn't I think?

**Comment by zacwest** [comment]
Welp, I can't figure out what I did to get into this state, I'll reopen if I can ever reproduce.
