### ISSUE TITLE
Tab indicator not shown on web when zoomed out to 75% and 90%

### ISSUE THREAD

**Issue by docsparks** [home-assistant/frontend#8792]
### Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

when the Google Chrome browser is zoomed out to 90% and 75% the tab indicator is not visible.  At 67% and 80% it is.

### Describe the behavior you expected

Tab indicator to be shown even at 75%

### Steps to reproduce the issue

1. zoom browser settings to 75%
2. look for tab indicator styling

### What version of Home Assistant Core has the issue?

core-2021.3.4

### Which operating system are you using to run this browser?

windows 10

Just figured this is the place to help, sorry if its not.

**Comment by spacegaier** [comment]
I can confirm the issue on Win 10 + Chrome. Works fine in FF though.
