### ISSUE TITLE
Trace UI - tabs illegible in dark mode (2021.4.0b3)

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#8809]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In 2021.4.0b3 the tabs in Trace UI are no longer visible on the default dark theme, see photo:

![tabs](https://i.imgur.com/i1kMjq0.png)

It's fine in light mode

### Describe the behavior you expected

Visible tabs / use primary text color variable

### Steps to reproduce the issue

1. Switch to default imgudark mode in user profile page
2. View a trace, tabs will be impossible to read

### What version of Home Assistant Core has the issue?

2021.4.0b3

### What was the last working version of Home Assistant Core?

2021.4.0b2

### In which browser are you experiencing the issue with?

Safari and macOS Companion App. Also Firefox.

### Which operating system are you using to run this browser?

macOS High Sierra / macOS Big Sur

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by bramkragten** [comment]
Fixed!
