### ISSUE TITLE
zwave Item dropdown goes up

### ISSUE THREAD

**Issue by ryanm101** [home-assistant/frontend#881]
This means some items are almost impossible to get to.

![offscreen](https://user-images.githubusercontent.com/5185337/36061130-ccf9684a-0e4d-11e8-98b2-044a8a9de5e3.png)

**Comment by c727** [comment]
same for language selection btw, you have to scroll to top of main page first

**Comment by andrey-git** [comment]
The dropdown doesn't like the header. The current workaround works if the window is scrolable.
As a workaround in the zwave window - enable help text which will make the window scrolable.

**Comment by kpine** [comment]
Just confirming that this problem still exists. When the window is maximized, and their is no scrollbar in the browser, the nodes are not all accessible. Shrinking the browser window such that there is a scrollbar makes the nodes visible.

**Comment by nerdfoundrygaming** [comment]
And in 2020 this is still an issue. Took me 15 minutes, and finally switching themes to figure it out 🤣

FWIW, it appears fine on Android mobile (which is why I knew something was up).

**Comment by gbuktenica** [comment]
Confirming that this is still an issue on 106.0
