### ISSUE TITLE
Setting both date and time on input_datetime only changes date

### ISSUE THREAD

**Issue by Crocmagnon** [home-assistant/frontend#8813]
## The problem
I'm having trouble setting an `input_datetime` with both date and time set. When changing both the date and the time in the service call, only the date is set. The time is set for a very brief period but is then reset to whatever it was before. When changing only the date or the time, then it works perfectly.

Here's a screencast demonstrating the behavior:

https://user-images.githubusercontent.com/3630554/104915017-50c23680-5990-11eb-8aa7-580cd8fb9798.mov

## Environment

- Home Assistant Core release with the issue: 2021.1.4, still present in 2021.2.2
- Last working Home Assistant Core release (if known): 0.117 at least, I think it also used to work on the latest 2020.x and maybe on the first 2021 versions too but I'm not sure.
- Operating environment (OS/Container/Supervised/Core): Home Assistant OS
- Integration causing this issue: input_datetime
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/input_datetime

## Problem-relevant `configuration.yaml`
The input_datetime was set using the UI. I don't think there is any relevant `configuration.yaml` but I may be mistaken.

## Traceback/Error logs
No warning or errors relevant to this problem in the logs.

**Comment by balloob** [comment]
Moved this to the frontend, as it's a bug there.

This code makes no sense: <https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/entity-rows/hui-input-datetime-entity-row.ts#L97-L111>

There are two issues:

- The guard to prevent state updates only works with time-only entities.
- An update to `<ha-date-input>` `value` property fires an `@change` event.
