### ISSUE TITLE
ZWave-JS device configuration items are missing units

### ISSUE THREAD

**Issue by kpine** [home-assistant/frontend#8846]
### Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

For configuration parameters that are defined with units (seconds, percentage, etc), the UI is not displaying those units. Without the units you can't always determine what the value you're actually setting; is it minutes, seconds, etc.?

### Describe the behavior you expected

The units to be displayed along with the value. The units help convey the meaning of the parameters.

### Steps to reproduce the issue

1. Navigate to the configuration UI for a zwave-js device, for a device that has configuration parameters with units
2. Observe that a parameter that has values in "seconds", does not communicate that the value is in seconds.
3. Navigate to the same node in the zwavejs2mqtt UI and observe the units are shown.

### What version of Home Assistant Core has the issue?

core-2021.4.0

### In which browser are you experiencing the issue with?

Firefox 87.0

### Which operating system are you using to run this browser?

WIndows 10 

zwavejs2mqtt config params:
![image](https://user-images.githubusercontent.com/791794/113927271-19e70a00-97a2-11eb-847b-a0715596b315.png)

zwave_js integration config params:
![image](https://user-images.githubusercontent.com/791794/113927286-21a6ae80-97a2-11eb-9f71-fa52491a2972.png)

**Comment by spacegaier** [comment]
@cgarwood I think you developed this, so perhaps you can have a look at that?
