### ISSUE TITLE
Mobile App Integration for Xiami wont group battery

### ISSUE THREAD

**Issue by antoweb** [home-assistant/frontend#8854]
## The problem
If i create a group with this 2 entities:
![image](https://user-images.githubusercontent.com/32364871/90806617-8c8f9c00-e31d-11ea-8a6e-fd1f1040320e.png)

These entities disappear form top bar but not are viewed in Group

![image](https://user-images.githubusercontent.com/32364871/90806881-f0b26000-e31d-11ea-837b-034262134556.png)

## Environment

arch | armv7l
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.12
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7
python_version | 3.8.3
supervisor | 235
timezone | Europe/Rome
version | 0.114.2
virtualenv | false

- Home Assistant Core release with the issue: 0.114.2
- Last working Home Assistant Core release (if known): Never
- Operating environment (OS/Container/Supervised/Core):  Hassio/Hoassos
- Integration causing this issue: Mobile App
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information

This Problem is also for Iphone Mobile App integration, the battery sensor cannot be inserted in group

**Comment by antoweb** [comment]
You are right. Changing device_class work good. But why?

**Comment by spacegaier** [comment]
I haven't checked the coding yet, but I assume somewhere something is specifically tied to the `battery` class. If by design or by accident, I cannot say yet.

**Comment by antoweb** [comment]
I think by design

**Comment by bramkragten** [comment]
Yes, this is by design in the default dashboard, if you want it differently, you can take control of your Lovelace dashboard and add the entities manually.
