### ISSUE TITLE
I register a service by REST API,but i can't find it.

### ISSUE THREAD

**Issue by ZJia1231** [home-assistant/frontend#8872]
### Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![4CC7ED79-695A-4438-A24D-7A04645A4D9D](https://user-images.githubusercontent.com/28012988/114156339-0af48900-9955-11eb-873f-9494ff7c1df6.png)

![image](https://user-images.githubusercontent.com/28012988/114156603-573fc900-9955-11eb-9946-4d1ca0fed0a2.png)

### Describe the behavior you expected

I hope it can work,thx!

### Steps to reproduce the issue

1.
```
const registerService = async (domain: string, service: string) => {
    return restRequest({
        method: 'POST',
        url: `/api/events/service_registered`,
        data: {
            domain,
            service,
        },
    })
};
registerService('switch', 'toggle');
registerService('switch', 'turn_on');
registerService('switch', 'turn_off');
```
2. click the switch button on the dashboard
![image](https://user-images.githubusercontent.com/28012988/114157473-3fb51000-9956-11eb-8758-40a6b9576d6f.png)

### What version of Home Assistant Core has the issue?

Home Assistant 2021.4.1

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by bramkragten** [comment]
What do you expect to happen here? You just fire an event, you don't actually register a handler for the service?

**Comment by bramkragten** [comment]
You should create a component in the core that handles these service calls.

<https://developers.home-assistant.io/docs/dev_101_services>

**Comment by ZJia1231** [comment]
> You should create an integration in the core that handles these service calls.
> 
> https://developers.home-assistant.io/docs/dev_101_services

It means that i only can handle the service calls through integration?
I want to handle the service calls by Addon.

**Comment by bramkragten** [comment]
Yes, if you need more help, please ask it in our discord developer channels.

https://www.home-assistant.io/help/

**Comment by ZJia1231** [comment]
> Yes, if you need more help, please ask it in our discord developer channels.
> 
> https://www.home-assistant.io/help/

Why doesn't HA register switch services, light services and other services by default?
I am not expert in Python, i want to controller device by addon in Node.js .
but i found that Addons supports much less than integration.
Does addon will be powerful in the future?

**Comment by bramkragten** [comment]
> Yes, if you need more help, please ask it in our discord developer channels.
> 
> [home-assistant.io/help](https://www.home-assistant.io/help/)

An addon is not the same as an integration.
