### ISSUE TITLE
Unable to update date of input_datetime after upgrade to 2021.4.0 and .1

### ISSUE THREAD

**Issue by EvTheFuture** [home-assistant/frontend#8875]
### Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When updating the date and time of an input_datetime entity, only the time is updated.

It works if she entity is updated through a service call but not in lovelace

### Describe the behavior you expected

The date part of the input_datetime to be updated

### Steps to reproduce the issue

1.
2.
3.
...
1. Create an input_datetime helper entity
2. Add it to an entities card
3. Try to update the value

### What version of Home Assistant Core has the issue?

core-2021.4.1

### What was the last working version of Home Assistant Core?

core-2021.3.x

### In which browser are you experiencing the issue with?

Google Chrome mobile and Firefox mobile

### Which operating system are you using to run this browser?

Android 10

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.
type: entities
entities:
  - entity: input_select.current_climate_mode
  - entity: input_datetime.away_until

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by EvTheFuture** [comment]
Recording of the issue

https://user-images.githubusercontent.com/66333723/114171412-8a259500-9934-11eb-90b5-72beb2aa8dd5.mp4

**Comment by bramkragten** [comment]
Duplicate, and already fixed
