### ISSUE TITLE
Invalid Date in input_boolean last_updated

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#8877]
### Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

checking the state of an input_boolean shows 'Invalid Date' on the last_updated field.

### Describe the behavior you expected

show the correct time like last_changed

### Steps to reproduce the issue

1. filter entity on an input_boolean
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.4.0

### What was the last working version of Home Assistant Core?

DK

### In which browser are you experiencing the issue with?

Any really, both desktop an handheld 

### Which operating system are you using to run this browser?

Big sur 11.2.3 Safari 14.0.3

### State of relevant entities

```yaml
# Paste your state here.
editable: false
friendly_name: Guest
icon: 'mdi:human-greeting'
```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

No frontend issue in Lovelace

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

None

<img width="740" alt="Schermafbeelding 2021-04-09 om 13 48 45" src="https://user-images.githubusercontent.com/33354141/114176923-112a3b80-993c-11eb-86f3-9293a61a7338.png">
<img width="1101" alt="Schermafbeelding 2021-04-09 om 13 52 36" src="https://user-images.githubusercontent.com/33354141/114176926-125b6880-993c-11eb-8cac-e2a24d334b37.png">

**Comment by spacegaier** [comment]
I am not able to reproduce this on the latest dev version (Win 10 though). So either has been fixed already or my test does not match yours.

Given that "last updated" works it should not be an issue with the conversion (where macOS/iOS enforce the "T" ISO 8601 separator) as the backend should take care of that automatically.

**Comment by Mariusthvdb** [comment]
Thanks for your quick response!
don't understand this issue at all I must confess... I now see it on all automations too (didn't check all domains, but alarm_control_panel, alert are ok, yet binary_sensor, device_tracker, switch are all Invalid....) 

would almost deduct the binary domains are Invalid? on 3 instances btw, so not an accidental issue.

__edit__

seems custom-ui is the culprit of this issue. wow thats annoying. can't live without that, but hate it to interfere with all new things you guys add... Do you use a special fronted code that is different from before somehow. I know these 2 fields are relatively new, but why would last_changed show nicely and the last_updated become corrupted
