### ISSUE TITLE
UI crashes when entering automations 

### ISSUE THREAD

**Issue by axwell** [home-assistant/frontend#8879]
### The problem

I just updated to 2021.4.0 and ui crashes when entering automations that contain light entities.
Interface has glitches and after scrolling down a few times eventually will crash.

Using default theme.

### What is version of Home Assistant Core has the issue?

core-2021.4.1

### What was the last working version of Home Assistant Core?

core-2021.3.0

### What type of installation are you running?

Home Assistant Container

**Comment by spacegaier** [comment]
Please share the automation and any errors you can see in the browser logs.

**Comment by axwell** [comment]
There are no error logs in the console.
All automations with light entities do this. (even the simple ones click button and turn on light).

alias: Turn on hallway lights
description: ''
trigger:
  - device_id: e2379ecf502542a3b6c2ca0789fbfc7e
    domain: binary_sensor
    entity_id: binary_sensor.0x00158d0003cc2367_occupancy
    platform: device
    type: motion
  - platform: device
    domain: mqtt
    device_id: 6b248e2a94dd41dc90a25cc02cfe12fa
    type: action
    subtype: single_both
    discovery_id: 0x00158d00022ee168 action_single_both
condition:
  - after: '06:00:00'
    before: '00:00:00'
    condition: time
  - after: sunrise
    condition: sun
  - below: 45
    condition: device
    device_id: ec41b4e37472401bbebc0103ae34948c
    domain: sensor
    entity_id: sensor.0x04cf8cdf3c7880e5_illuminance_lux
    type: is_illuminance
action:
  - data:
      brightness: 255
      transition: 1
    entity_id: light.0xccccccfffe96c568_light
    service: light.turn_on
  - delay: '00:00:01'
  - data:
      kelvin: 3600
    entity_id: light.0xccccccfffe96c568_light
    service: light.turn_on
  - data:
      brightness: 255
      transition: 1
    entity_id: light.0x000d6ffffe12f709_light
    service: light.turn_on
  - delay: '00:00:01'
  - data:
      kelvin: 3600
    service: light.turn_on
    target:
      entity_id: light.0x000d6ffffe12f709_light
mode: single

**Comment by axwell** [comment]
clearly a memory leak somewhere.
![Screenshot_20210409_171858](https://user-images.githubusercontent.com/7890878/114194828-8c014f80-9958-11eb-8300-53b1db009c95.png)

**Comment by stephack** [comment]
I'm having similar experience in the Android Companion app. Most of my automations are fine but any that have the new Target selector UI cause the app to hang or become extremely sluggish. See my post in the forum.
https://community.home-assistant.io/t/home-assistant-companion-android-app-april-2021-release/297538/16?u=stephack

![image](https://user-images.githubusercontent.com/20565645/114316072-e96bdc80-9acf-11eb-8aae-c9191c0eb651.png)

I get the same behavior when viewing these types of automation or scripts via the android chrome browser. Windows Chrome works fine for me.

**Comment by axwell** [comment]
i'm attaching a profiling result, maybe this can help ?
I can reproduce the issue on all platforms macos, linux, windows, mobile app.


<img width="1787" alt="Screenshot 2021-04-12 at 13 33 50" src="https://user-images.githubusercontent.com/7890878/114382005-809a6800-9b94-11eb-865e-b6d61a457b6a.png">

**Comment by sluzynsk** [comment]
This happens on MacOS 11.2.3 Safari as well. Watching Activity Monitor while entering an automation with a light in it, the memory usage for the tab increases into multiple GB before Safari's watchdog kills the tab and reloads it. Happy to collect & share any relevant data to help.

**Comment by axwell** [comment]
this is really stupid, 10 days and no answer, no assignee !
0 interest !

running 2021.4.4. does not fix it !

**Comment by bramkragten** [comment]
Because it is not assigned there is no interest?

I have tried to reproduce and looked for some obvious things, but have not found anything yet.

**Comment by axwell** [comment]
@bramkragten there was no change on the task and no reply,  i can help with any other details.

**Comment by bramkragten** [comment]
Is it just in the automation editor, or also in the service dev tools with the light service?

**Comment by stephack** [comment]
My particular issue (hanging/lag in Android Chrome) went away when I upgraded to 2012.4.4.
I never had the issue on my Windows desktop.
Just a data point but obviously my issue was different from @axwell . Hope you get it resolved soon.

**Comment by bramkragten** [comment]
I think I found the issue, I think you can resolve it for now by upgrading your config to the new syntax:

From:
```yaml
service: light.turn_on
data:
  transition: 64
  kelvin: 3800
entity_id: light.bed_light
```

To:
```yaml
service: light.turn_on
data:
  transition: 64
  kelvin: 3800
target:
  entity_id: light.bed_light
```

**Comment by axwell** [comment]
yes it works, thanks !
