### ISSUE TITLE
Lovelace 'Sensor' cannot be used for motion sensor

### ISSUE THREAD

**Issue by sjikkervisje** [home-assistant/frontend#8880]
### The problem

I have a Philips Hue Outdoor Motion Sensor which can detect motion, light and temperature. I can use the 'Sensor' LoveLace Dashboard item for Temperature or Lightlevel but I can't use the same for the Motionsensor. 

It would be great if this could also be used for that as it then properly displays the grafs also for that.

### What is version of Home Assistant Core has the issue?

core-2021.4.1

### What type of installation are you running?

Home Assistant Core

### Integration causing the issue

Not an integration but a options thing

**Comment by spacegaier** [comment]
The sensor card allows all entities of the domain `sensor`. I myself have no motion sensor available but that should already work.

**Comment by bramkragten** [comment]
A motion sensor is a `binary_sensor`, use the entity card.
