### ISSUE TITLE
Footer overlaps Automations YAML editor in Safari

### ISSUE THREAD

**Issue by agneevX** [home-assistant/frontend#8883]
### Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The footer overlaps the Automations YAML editor. 

<img src="https://user-images.githubusercontent.com/19761269/114215671-7d7c5d80-9983-11eb-93e9-e2400fc8ccac.png" width="400">

### Describe the behavior you expected

Footer should stick at the bottom.

### Steps to reproduce the issue

Open the YAML editor in any automation on a smaller than standard Safari viewport

### What version of Home Assistant Core has the issue?

2021.4.0

### What was the last working version of Home Assistant Core?

2021.3.*

### In which browser are you experiencing the issue with?

Safari 14.0.3

### Which operating system are you using to run this browser?

N/A

### State of relevant entities

N/A

### Problem-relevant frontend configuration

N/A

### Javascript errors shown in your browser console/inspector

N/A

**Comment by bramkragten** [comment]
Seems to be limited to Safari?

**Comment by spacegaier** [comment]
> 
> 
> Seems to be limited to Safari?

Looks like it. Fine for me on Win 10 + FF and Chrome.

**Comment by agneevX** [comment]
Seems to have been fixed, thanks!
