### ISSUE TITLE
Default dashboard URI is appended to other HA pages

### ISSUE THREAD

**Issue by apaperclip** [home-assistant/frontend#8910]
### Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When going directly to a dashboard tab other than default (/lovelace/default_view) such as /lovelace/test, the default dashboard URI is appended to whatever other main HA tab was clicked.  E.g. /map becomes /map/default_view, /logbook becomes /logbook/default_view. These items still load but configuration and developer tools do not.  They do not load unless I navigate to something else first and then back to config or dev tools.

This was uncovered by using the new shortcut features in the android app and has been reproduced in chrome and edge on a windows 10 pc.  

### Describe the behavior you expected

- Configuration and developer tool screens should load if I start my HA interaction at a view other than the default dashboard.  Such as bookmarks, Android shortcuts, browser restart after close/crash.
- The default dashboard URI should not be appended when browsing other pages.

### Steps to reproduce the issue

1. Grab the URI for a dashboard tab other than the default.
2. Open browser incognito/private browsing tab, log in, and paste in the non-default tab URL
3. Click configuration and look at the address bar.  It should show  'http://hahost:port/config/default_view' where default_view is the name of your defined default dashboard tab instead of /config.
4. Click on any other HA tab or dashboard and then return to configuration, it should load fine.

### What version of Home Assistant Core has the issue?

2021.4.3

### In which browser are you experiencing the issue with?

Chrome 92.0.4475.2

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by bramkragten** [comment]
Are you sure this is not caused by something custom? I don't see anywhere in the code we add `default_view` to the url.

**Comment by dshokouhi** [comment]
So when I was able to reproduce it, it almost seemed like a caching issue because if I hit the browser back button and went back to configuration it would actually load for me.  I didn't see any errors in logcat but then @apaperclip mentioned they can see it on the desktop too.  The shortcuts feature starts a new instance of the webview activity that I believe might be a fresh cache state.  Our original suspicion was that maybe something else needs to load that only gets loaded from the default dashboard?

**Comment by apaperclip** [comment]
Thank you both for checking in.

I don't _think_ it's something custom. I can recreate it on my prod instance which has been around since pre-lovelace and a dev instance that is newer and only has a few integrations and no custom cards or anything.

For the prod instance the default dashboard URI is /0 and not /default_view.  I'm guessing the 0 is what it was named on conversion from the old states ui or just something I picked.  Since the behavior is the same regardless of the URI it felt like something in code/cache. 

I'm happy to check or try any suggestions.

**Comment by spacegaier** [comment]
I also cannot reproduce the issue on Win 10 + FF & Chrome on 2021.4.4.

The only place in the coding where we use `default_view` is when we generate the config for the auto-generated default view (`generateDefaultViewConfig()`).

**Comment by dshokouhi** [comment]
Do either of you guys use the android app? The shortcuts feature is a very easy way to replicate the issue as I believe you need to be in incognito mode to reproduce but further more you need to provide the external auth like the app does to bypass login in incognito mode.  The shortcuts feature seems to start a new instance of the browser with its own cache state, at least thats what it appears like.

Here is a video showing where the app first opens to another lovelace view, then the user goes to configuration and is presented a blank screen.  Swiping back on android hits the browser back button and then upon the second attempt the configuration section will load.  When I use chrome remote debugging (you need to load a debug build of the app to get webview debugging) the only thing that is apparent to me is that one of the `chunks` in dev tools is missing on first load of configuration.  More data `chunks` gets loaded on second the attempt.  I know thats not real helpful but hopefuly enough data to go by from the apps perspective.

https://photos.app.goo.gl/qkGoWkqdRsJiVXLL7

**Comment by apaperclip** [comment]
Thanks all for the continued research.

For some additional info I just ran through a from-scratch test.

1. docker run to start a fresh 2021.4.4 instance
2. open browser, go through onboarding 
3. Click triple dots to edit dashboard, take over but did not check the blank dashboard option
4. Create a new tab (i named it test), save, exit edit mode 
5. Copy full URL (ended in /lovelace/test in my case)
6. Close browser tab, open new tab and paste (I did not click stay logged)
7. Login, and click configuration (blank screen) or dev tools (headers visible but none are selected) to see 

observations

- it appears the initial default dashboard uri is /lovelace/default_view when not clicking start with blank when taking control.
- My testing confirms spacegaier's comment, the default_view comes from the generated dashboard when I did not click start with a blank. If I click start with a blank the name I give becomes the URI of the default dashboard. When I create a second dashboard and recreate the issue, that provided name now becomes the string that is appended to /config or /developer-tools.
- It's seems less about the name default_view  and more about whatever variable holds the default dashboard URI and some logic that is appending that on first click of navigation/load.
- side issue, the text after the account creation for analytics option and location is very light, I can create a separate issue


Thanks for the video dshokouhi!

**Comment by dshokouhi** [comment]
yea videos are always helpful :) if you could share some screenshots or a video from the desktop experience too so the devs can see how to best reproduce it there....debugging webview on mobile isnt fun 😂

**Comment by apaperclip** [comment]
sure - here's a quick vid.
![ha-dashboard1](https://user-images.githubusercontent.com/67401560/114916417-c3597b80-9df2-11eb-88ca-35b4713c2037.gif)

**Comment by apaperclip** [comment]
I think this is fixed. I could not recreate in 2021.7.2.  I looked around for an associated PR but nothing jumped out at me.  Thanks all for the assistance.
