### ISSUE TITLE
Entities card: conditional entity not showing state

### ISSUE THREAD

**Issue by scaarup** [home-assistant/frontend#8913]
### Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When adding conditions to an entities card, entities are displayed/listed without their state.

### Describe the behavior you expected

I am expecting to see the state of the entity.

### Steps to reproduce the issue

1. Create an entities card in the UI with the following code:
```  - type: entities
    entities:
      - type: conditional
        conditions:
          - entity: input_boolean.heating_schedule_1_sal
            state: 'on'
        row:
          entity: input_number.heating_target_temp_plan_1_sal
          name: Temp. dagstid
      - entity: input_number.heating_target_temp_plan_1_sal
        name: Temp. dagstid
```
2. Observe the rendered card and notice, that state is missing on the entity with the condition:
![image](https://user-images.githubusercontent.com/8055470/114665055-d4c05c00-9cfc-11eb-8c7d-a91bc5a036fc.png)

Reference: https://community.home-assistant.io/t/conditional-entity-not-showing-state/222344

### What version of Home Assistant Core has the issue?

core-2021.4.1

### What was the last working version of Home Assistant Core?

?

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by scaarup** [comment]
Guys?

**Comment by bramkragten** [comment]
> Guys?

Yes?

There have been PR's open fixing this, but they have gone stale, unfortunately.

**Comment by scaarup** [comment]
Anything I can do - like taking over the PR's or something? Maybe you have some refs @bramkragten

**Comment by spacegaier** [comment]
One thing you can do is testing and reviewing the PRs (and once you found them, link them here).

**Comment by scaarup** [comment]
> One thing you can do is testing and reviewing the PRs (and once you found them, link them here).

would love to do that, but I cannot find those PRs.

**Comment by spacegaier** [comment]
I had a quick look: This one is somewhat related, but does not fix the issue: https://github.com/home-assistant/frontend/pull/9837

The problem is that the input_number GUI element checks the width of the parent to determine if the numeric state should be rendered. If the input_number is in the conditional element, at runtime the width of the conditional row is initially 0 and hence the state gets hidden. The observer apparently in the current form does not fix that.

**Comment by scaarup** [comment]
> > Guys?
> 
> Yes?
> 
> There have been PR's open fixing this, but they have gone stale, unfortunately.

Can you point me to those PRs? I cannot find any.
