### ISSUE TITLE
Extra sidebar is added when add-on restart

### ISSUE THREAD

**Issue by Misiu** [home-assistant/frontend#8926]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I got info that the password to my samba addon must be changed (`Insecure secrets in core_samba`).
After going to the configuration page of the Samba share addon I changed the password and pressed Save.
After confirming the second sidebar showed up. See the below recording:
![ha_samba](https://user-images.githubusercontent.com/1741838/115027190-b062ac00-9ec3-11eb-9c4e-403a0ff5d0f3.gif)

I only get this behavior on Chrome 90, I don't remember getting this on an older version of Chrome. I've checked the same scenarion on Edge 89.0.774.76 and it isn't occurring.

### Describe the behavior you expected

There should be only one sidebar

### Steps to reproduce the issue

1. open any addon configuration page
2. change anything in yaml
3. click save and confirm

### What version of Home Assistant Core has the issue?

core-2021.4.4

### In which browser are you experiencing the issue with?

Chrome 90.0.4430.72

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by TomBrien** [comment]
Just found this. Also happens when updating (which is a restart after all)

**Comment by decairn** [comment]
This also happens when deleting a snapshot (Supervisor -> Snapshots -> click on an instance -> Delete Snapshot)

**Comment by Syntoxr** [comment]
Also happens in Brave browser (which is chromium based) Version 1.23.71 Chromium: 90.0.4430.72

**Comment by carpii** [comment]
I'm seeing this frequently too. 

Chrome 90.0.4430.85 (Official Build) (x86_64)
OSX: 11.2.3
Home Assistant OS 5.13
core-2021.4.6
supervisor-2021.04.0

The easiest way to reproduce it to go to Supervisor -> System -> Change Hostname

Then just click cancel, and the 2nd sidebar appears
