### ISSUE TITLE
codemirror prevent editing in mobile device iOS and Android

### ISSUE THREAD

**Issue by letroll** [home-assistant/frontend#8966]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I can't move my cursor or with a lot of difficulty when I edit yaml. I suggest disabling code mirror on iOS and Android for now.

### Describe the behavior you expected

I would like editing on mobile device also.

### Steps to reproduce the issue

1.
2.
3.
...

## System Health

version | core-2021.4.6
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.11.9-arch1-1
arch | x86_64
timezone | Europe/Paris

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4954
Installed Version | 1.11.3
Stage | running
Available Repositories | 847
Installed Repositories | 22

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 7
views | 7
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### What version of Home Assistant Core has the issue?

core-2021.4.6

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by spacegaier** [comment]
Disable codemirror? Then there would not be anything to edit YAML since no editor would then be rendered at all? That cannot be what you mean 😕.

Either way, sounds like a duplicate as the issue itself is already covered https://github.com/home-assistant/frontend/issues/8542.

**Comment by letroll** [comment]
Not a duplicate for me but a complement because the clipboard is broken like for a classic edit also. And render is not everything we need here. Edition is a thing which could be made native. Android and iOS webview's support native bridge interface. And an edition full-screen is maybe a better UX on "small" screen.

**Comment by bramkragten** [comment]
I'm not aware of any issues with CodeMirror on android? Please explain your problem a bit more.

**Comment by letroll** [comment]
Yes, in short editing, removing and copy and paste text are not working or not easily on touch device like stated here:
https://github.com/home-assistant/android/issues/948
https://github.com/codemirror/CodeMirror/issues/6349

**Comment by bramkragten** [comment]
We don't use the editor those issues are for, we use the next version of CodeMirror, version 6 <https://codemirror.net/6/>, of which you can find the issues here: <https://github.com/codemirror/codemirror.next/issues>
