### ISSUE TITLE
last-changed doesn't update on cover except for open/close

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#8968]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

 `secondary_info: last_changed` on a cover doesnt update unless the cover actually opens or closes.

an automation triggering on the state of the cover does show last_updated correctly, so HA state machine is aware ;-)

### Describe the behavior you expected

Covers tend to have dedicated  intermediary  positions, and it would be expected to see a last_changed update on that (ie on position change in general) too.

### Steps to reproduce the issue

1. entities card with cover and `secondary_info: last-changed`
2. 
3.
...

### What version of Home Assistant Core has the issue?

2021.4.6

### What was the last working version of Home Assistant Core?

never?

### In which browser are you experiencing the issue with?

all

### Which operating system are you using to run this browser?

Big sur 11.2.3 Safari 14.0.3 

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.
      - entity: cover.raamverduistering_stookhok
        name: Stookhok
        secondary_info: last-changed
```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

No errors

### Additional information

<img width="497" alt="Schermafbeelding 2021-04-22 om 09 12 47" src="https://user-images.githubusercontent.com/33354141/115671691-12e7fc00-a34b-11eb-98d9-9e5a61904db5.png">

it's not until fully closed (or opened) the last-changed on the cover is updated:

<img width="487" alt="Schermafbeelding 2021-04-22 om 09 15 08" src="https://user-images.githubusercontent.com/33354141/115672210-9efa2380-a34b-11eb-8b0f-d93a971d7db6.png">

**Comment by spacegaier** [comment]
I either cannot reproduce the issue or do not understand your point. If I change the position of a cover (only by a few percent so no full open or full close) the `last-changed` and `last-updated` both get new values and Lovelace correctly shows them as the secondary info.

**Comment by Mariusthvdb** [comment]
well no, not here, check coming from 100% 2 hours ago:

<img width="450" alt="Schermafbeelding 2021-04-23 om 09 08 58" src="https://user-images.githubusercontent.com/33354141/115833005-d9c78e80-a413-11eb-81ae-e9b9a8aad870.png">
<img width="452" alt="Schermafbeelding 2021-04-23 om 09 09 14" src="https://user-images.githubusercontent.com/33354141/115833009-da602500-a413-11eb-899b-b552f2eda197.png">
<img width="443" alt="Schermafbeelding 2021-04-23 om 09 09 33" src="https://user-images.githubusercontent.com/33354141/115833010-daf8bb80-a413-11eb-8fc3-65275466c7cc.png">

it's only until full closure the last_changed gets updated:

<img width="454" alt="Schermafbeelding 2021-04-23 om 09 10 14" src="https://user-images.githubusercontent.com/33354141/115833011-daf8bb80-a413-11eb-817d-72e8c2071807.png">

**Comment by spacegaier** [comment]
I verified yesterday already that if I use the vanilla HA sliders in the more-info cover dialog it also updates correctly. So it sounds like a custom card issue.

**Comment by Mariusthvdb** [comment]
no, not here:

<img width="399" alt="Schermafbeelding 2021-04-23 om 09 24 50" src="https://user-images.githubusercontent.com/33354141/115835078-2dd37280-a416-11eb-84e7-04e956bcd9b0.png">
<img width="393" alt="Schermafbeelding 2021-04-23 om 09 25 03" src="https://user-images.githubusercontent.com/33354141/115835085-2f9d3600-a416-11eb-87d5-114813170380.png">
<img width="388" alt="Schermafbeelding 2021-04-23 om 09 26 20" src="https://user-images.githubusercontent.com/33354141/115835087-2f9d3600-a416-11eb-8595-11df07e8d9d2.png">
<img width="389" alt="Schermafbeelding 2021-04-23 om 09 26 42" src="https://user-images.githubusercontent.com/33354141/115835090-3035cc80-a416-11eb-9e6a-6954cd9f16ad.png">
<img width="397" alt="Schermafbeelding 2021-04-23 om 09 27 21" src="https://user-images.githubusercontent.com/33354141/115835093-30ce6300-a416-11eb-83bd-8ae629023622.png">
<img width="400" alt="Schermafbeelding 2021-04-23 om 09 27 33" src="https://user-images.githubusercontent.com/33354141/115835094-30ce6300-a416-11eb-88f4-f631bb250a6a.png">

**Comment by bramkragten** [comment]
The state doesn't change, it is still open.

Check the value we get from the backend in the state dev tools.

**Comment by Mariusthvdb** [comment]
don't close please, this is unresolved.
how else can you explain the last_changed is immediately updated when clicking the up/down buttons?

**Comment by bramkragten** [comment]
Because that updates the state probably?

If it is an issue, it definitely isn't a frontend one.

**Comment by Mariusthvdb** [comment]
I am confused now. The main difference between the 2 situations is the difference in which we operate the device in the frontend: either using the up/down buttons, or the slider in the more-info. 

How isn't that a Frontend issue? Surely the user should expect and get the same response in the Frontend by using either method?

**Comment by spacegaier** [comment]
The frontend only shows the data it gets from the backend. Hence Bram's comment that not frontend related.

As I wrote earlier, it also works fine for me: Both buttons and slider correctly update `last_updated` and `last_changed`. It might be an issue with your used cover integration.

**Comment by Mariusthvdb** [comment]
I can confirm last-updated to work, so Ill use that.

My integration is for Somfy which is a custom integration. However the same issue is happening on core Trafdri covers: 
<img width="182" alt="Schermafbeelding 2021-04-23 om 12 11 20" src="https://user-images.githubusercontent.com/33354141/115856713-1d7ac200-a42d-11eb-8bc2-505947127818.png">

even though this is actually moving now (see the icon) the display is still from the earlier full opening 5 hours ago.
