### ISSUE TITLE
Two actions required to set Retain option in Dev Tools > Services

### ISSUE THREAD

**Issue by tdejneka** [home-assistant/frontend#8970]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When calling **MQTT:Publish** via **Developer Tools > Services** (in UI mode), the option requires the user to perform two actions to enable it.

1. Tick the checkbox.
2. Enable the toggle button.

If you only tick the checkbox, the option is not enabled (switch to YAML mode and the `retain` option has not been set to `true`). This can mislead the user to believe the Retain option has been enabled when in fact it has not.

Perhaps this is by design but it seems over-engineered to require two actions to enable a simple binary option.

**![Screenshot from 2021-04-22 17-11-09](https://user-images.githubusercontent.com/44732909/115786974-83b10780-a38f-11eb-947c-b6a93134e756.png)**

### Describe the behavior you expected

- Tick the checkbox and the Retain option is enabled.
- Untick the checkbox and the Retain option is disabled.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

 	core-2021.4.6

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Firefox; Edge

### Which operating system are you using to run this browser?

Ubuntu 20.04; Android 9

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by spacegaier** [comment]
That is by design. The checkbox activates this optional parameter so it gets included in the service call payload, whereas the toggle then controls the value to be sent for this parameter.

**Comment by tdejneka** [comment]
Thank you for taking the time to reply.

> That is by design.

Respectfully, I believe it's a curious design choice.  

It's unusual to see a form where checkboxes are used to include/exclude the form's fields. In most applications, a form consists of fields where field-content alone determines whether the field is included/excluded. 

The design choice has led to various unusual form behaviors and inconsistencies. For example, `topic` has no checkbox and is always included yet all other options in the form have checkboxes. However, mqtt.publish with just a topic alone has no use and, in fact, publishes nothing when executed (i.e. it doesn't publish an empty string; it does nothing). It's unclear why `payload` isn't also handled like `topic` and always included (and so the form would not display a checkbox for `payload`).

Ticking `retain`'s checkbox alone effectively changes nothing (confirmed by viewing YAML mode); it doesn't add `retain: false` but then why should it because that's the default mode for `retain` whether one ticks the checkbox or not. So that leaves only one use for `retain`'s checkbox and that's to make the toggle button visible so it can be enabled (which then adds `retain: true`). 

I appreciate the explanation that the checkboxes make it easier to test services because you can quickly include/exclude options without altering their values. However, I question how many users take advantage of this unique capability at the expense of using a form with non-standard behavior.

Anyway, I don't mean to debate this at length and accept the fact that this Issue is not the result of a bug.

**Comment by spacegaier** [comment]
The backend controls which fields have a checkbox (= are optional) and which are mandatory. If you see a bug there for a service, please create a PR that sets `required: true` for the respective field in the `services.yaml` file of the integration.
