### ISSUE TITLE
Delay does not display correctly in Automation | Actions

### ISSUE THREAD

**Issue by mpaneth** [home-assistant/frontend#8985]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In one of my automations I have the following Action
delay: '300'

It appears in the graphical editor as 
![image](https://user-images.githubusercontent.com/50599186/115954131-aaf40a00-a532-11eb-87c1-8f3aa32d4c18.png)

The display suggests 300 hours rather than 300 seconds (5 minutes)

### Describe the behavior you expected

I expected to see either 
00:00:300:000
or 
00:05:00:000

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.4.6

### In which browser are you experiencing the issue with?

Google Chrome Version 90.0.4430.85 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Win 10

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by spacegaier** [comment]
Can you try removing the apostrophes, so your `'300'` actually becomes a number `300` in your automation? Currently it is a string which we (I think correctly) have to interpret as a time value (so basically 300:00:00:00) hence the display in the editor.

**Comment by mpaneth** [comment]
Now displays correctly
![image](https://user-images.githubusercontent.com/50599186/115956425-ef39d700-a53f-11eb-851f-5f8aa66e76b5.png)

I'll wait to see if it executes correctly.
