### ISSUE TITLE
Circling Supervisor Log

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#8986]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

redirected from /supervisor, reporting here that always when opening the supervisor panel /hassio/system, the Log provider per default selects Supervisor, but keeps showing the continuous cirlcle. Only way to get rid of that is by selecting another Log provider in the dropdown, which displays quite promptly, and selecting Supervisor again also works fine after that.

### Describe the behavior you expected

Immediately show the supervisor Log

### Steps to reproduce the issue

1. select /hassio/system
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.4.6 with beta channel active
supervisor-2021.04.1

### What was the last working version of Home Assistant Core?

DK

### In which browser are you experiencing the issue with?

all/any

### Which operating system are you using to run this browser?

Big sur 11.2.3 Safari 14.0.3 

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

### Additional information

<img width="1532" alt="Schermafbeelding 2021-04-24 om 16 20 36" src="https://user-images.githubusercontent.com/33354141/115962073-cf8fb800-a519-11eb-9c0f-2456adc8dadc.png">

**Comment by spacegaier** [comment]
Never seen that happen on my instances. Do you have an especially long log? On my prod instance I currently have less than 70 lines in the log.

Anything in the browser logs?

**Comment by Mariusthvdb** [comment]
yeah, not much in the logs, and nothing special,
this is what I see:


https://user-images.githubusercontent.com/33354141/115973204-86f4f080-a553-11eb-8b0d-6833acd99cba.mp4

**Comment by spacegaier** [comment]
Might be one of those iOS specific bugs? Works fine on Win and Android for me.

**Comment by Mariusthvdb** [comment]
no am afraid not, its also on my Safari and Chrome browser on Desktop. As a matter of fact, I hadn't tried it on mobile before, and was just checking this for this small screen capture...
Also ,  it is only on this instance, which is set for the beta cycles, my other 2 instances show quite promptly upon first load of the panel. Could it be that?

**Comment by spacegaier** [comment]
My prod instance is also in beta channel and has no such problem.

**Comment by Mariusthvdb** [comment]
could I set log level debug to a specific component to see what is in it when opening supervisor panel?

**Comment by ludeeus** [comment]
Javascript errors shown in your browser console/inspector is where it would be at

**Comment by Mariusthvdb** [comment]
never thought of that.... but this is showing:

<img width="685" alt="Schermafbeelding 2021-06-19 om 12 39 57" src="https://user-images.githubusercontent.com/33354141/122639692-8912a000-d0fb-11eb-9e4d-e0adb8d26e8b.png">

could the be related ?

**Comment by ludeeus** [comment]
nope, those are just warnings and can be ignored.

**Comment by Houdoe** [comment]
For me, the circulating supervisor log is **NOT** solved!. 

I'm using the latest core, supervisor and OS. (core 2021.9.6 supervisor 2021.09.0 and OS 6.4)  When I select the /hassio/system tab the screen freezes, the cursor is circulating. After a few minutes, the log is shown. Warning: 
21-09-17 14:47:54 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None
21-09-17 14:55:44 WARNING (MainThread) [supervisor.host.network] Can't update connectivity information: Error: Timeout was reached

sometimes I get time out: check Observer URL:             http://homeassistant.local:4357. This shows 'connected'.

I don't use an HTTPS:// connection to HA but HTTP:// instead.

I tried different browsers: Edge, Google Chrome, Firefox

I run HA on a raspi 4 with SSD (no SD card)

the /dev/root shows a 100% used space in /sbin/docker-init !?

➜  ~ df
Filesystem           1K-blocks      Used Available Use% Mounted on
overlay              114645624  22733936  87224652  21% /
tmpfs                   946064         0    946064   0% /sys/fs/cgroup
**/dev/root               124288    124288         0 100% /sbin/docker-init**
/dev/sda8            114645624  22733936  87224652  21% /backup
devtmpfs                911376         0    911376   0% /dev
tmpfs                   946064         0    946064   0% /dev/shm
/dev/sda8            114645624  22733936  87224652  21% /data
/dev/sda8            114645624  22733936  87224652  21% /config
/dev/sda8            114645624  22733936  87224652  21% /addons
/dev/sda8            114645624  22733936  87224652  21% /share
/dev/sda8            114645624  22733936  87224652  21% /ssl
/dev/sda8            114645624  22733936  87224652  21% /media
/dev/sda8            114645624  22733936  87224652  21% /etc/resolv.conf
/dev/sda8            114645624  22733936  87224652  21% /run/audio
tmpfs                   378428      1540    376888   0% /run/dbus
tmpfs                   378428      1540    376888   0% /run/docker.sock
/dev/sda8            114645624  22733936  87224652  21% /etc/hosts
/dev/sda8            114645624  22733936  87224652  21% /etc/hostname
/dev/sda8            114645624  22733936  87224652  21% /etc/asound.conf
tmpfs                   946064         0    946064   0% /dev/shm
/dev/sda8            114645624  22733936  87224652  21% /etc/pulse/client.conf
/dev/sda8            114645624  22733936  87224652  21% /var/log/journal
tmpfs                   378428      1540    376888   0% /run/log/journal
tmpfs                   946064         0    946064   0% /proc/asound
devtmpfs                911376         0    911376   0% /proc/keys
devtmpfs                911376         0    911376   0% /proc/latency_stats
devtmpfs                911376         0    911376   0% /proc/timer_list
devtmpfs                911376         0    911376   0% /proc/sched_debug
tmpfs                   946064         0    946064   0% /sys/firmware


## System Health

version | core-2021.9.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4948
Installed Version | 1.15.2
Stage | running
Available Repositories | 944
Installed Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.4
-- | --
update_channel | stable
supervisor_version | supervisor-2021.09.0
docker_version | 20.10.7
disk_total | 109.3 GB
disk_used | 21.7 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Spotify Connect (0.9.1), Mosquitto broker (6.0.1), Samba share (9.5.1), Node-RED (10.0.0), ESPHome (2021.8.2), MariaDB (2.4.0), SSH & Web Terminal (9.0.1), Grafana (7.2.0), InfluxDB (4.2.1), TasmoAdmin (0.15.0), Log Viewer (0.11.1), Home Assistant Google Drive Backup (0.105.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 2
views | 9
mode | storage

</details>
