### ISSUE TITLE
Interactively revealing sidebar/menu doesn't allow scrolling the first time, but does subsequently

### ISSUE THREAD

**Issue by zacwest** [home-assistant/frontend#8988]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When interactively (via panning from the side) revealing the side bar, its contents are initially unscrollable.

### Describe the behavior you expected

The sidebar should be scrollable from any opening mechanism.

### Steps to reproduce the issue

1. Launch the iOS app
2. Pan from the left edge to reveal the sidebar
3. Attempt to scroll the sidebar

The sidebar will not scroll unless dismissed and reopened (there's _some_ mechanism which appears to refresh the contents, which will also kick it into being scrollable, but in my actual instance this feels rare).

This issue does not reproduce via tapping the menu button.

### What version of Home Assistant Core has the issue?

Core 2021.5.0.dev0; Frontend 20210423.0

### In which browser are you experiencing the issue with?

iOS App (iOS 13/14 for sure)

### Which operating system are you using to run this browser?

iOS 14.5

### State of relevant entities

n/a

### Problem-relevant frontend configuration

n/a

### Javascript errors shown in your browser console/inspector

n/a

### Additional information

https://user-images.githubusercontent.com/74188/116004543-fbfa1180-a5b7-11eb-85b3-1f090eea2120.mov

**Comment by genebean** [comment]
I’m fairly sure this needs to stay open

**Comment by Delta1977** [comment]
Same problem here on iOS 14.7.1 with companion 2021.216

**Comment by gardiner4** [comment]
I have the same issue.

**Comment by talondnb** [comment]
Issue remains on 2021.9.6 and 2021.216 with 14.7.1.

**Comment by Sirezul** [comment]
Still the same on 2021.9.7

**Comment by Sirezul** [comment]
This is really annoying :(

**Comment by sebster6** [comment]
Still an issue on 2021.11.x

**Comment by gomble** [comment]
I have this issue also on latest 2021.12.3

**Comment by sebster6** [comment]
This is still an issue on HA 2022.3.5 and companion app 2022.3.

**Comment by zacwest** [comment]
Yeah not stale.

Path forward is probably my writing a native sidebar for the app, though. It's next up on my queue when I get time for it.

**Comment by gardiner4** [comment]
Not stale. Took about 5 seconds to confirm it still exists.

**Comment by moostmartijn** [comment]
Why is this issue still not solved since opening in April 2021… this is the most annoying ‘bug’ while using the iOS app…

**Comment by HRFrazier** [comment]
bump

**Comment by gomble** [comment]
Still anoying

**Comment by gardiner4** [comment]
I see the same issue has been opened on the iOS side. Maybe throw some comments in there.  https://github.com/home-assistant/iOS/issues/2291

**Comment by sebster6** [comment]
Just updated to HA 2023.04.0 and companion app version 2023.4 and the issue seems to be fixed! There‘s a changelog entry that seems to reflect it as well („Fixes gesture to reveal sidebar“). Yay!

**Comment by gardiner4** [comment]
> Just updated to HA 2023.04.0 and companion app version 2023.4 and the issue seems to be fixed! There‘s a changelog entry that seems to reflect it as well („Fixes gesture to reveal sidebar“). Yay!

There was a new issue in the April beta that caused menu issues. It looks like both issues were fixed!
