### ISSUE TITLE
Uncaught DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.

### ISSUE THREAD

**Issue by Pho3niX90** [home-assistant/frontend#8996]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Device: EzViz C3X
Browser in queston: Google Chrome

After adding the camera, only the "auto" Camera View works
![image](https://user-images.githubusercontent.com/7858187/116094182-9b4a0200-a6a7-11eb-9140-90abf9e76476.png)

When clicking on the card to open the live view, I get the error:
`Uncaught DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
    at SourceBuffer.r._onSBUpdateEnd (http://10.0.0.141:8123/frontend_latest/chunk.cf277186969c7b147807.js:2:145490)
r._onSBUpdateEnd @ chunk.cf277186969c7b147807.js:1`

When doing this same steps from an Android device, using the home assistant app:
- Live streaming on the card doesn't work
- Clicking on it to view live view, works

Doing the same, on the same mobile device, via Chrome, doesn't work 

Using a different camera, I do not experience the same issues.

I have also trued setting it up as a normal generic camera, with the RTSP stream, with the same results. 

Codec information of the stream:
![image](https://user-images.githubusercontent.com/7858187/116099156-f7af2080-a6ab-11eb-9210-a485c9e737a1.png)

### Describe the behavior you expected

The stream should work as expected

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.4.6

### In which browser are you experiencing the issue with?

Version 90.0.4430.85

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```javascript
chunk.cf277186969c7b147807.js:1 Uncaught DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
    at SourceBuffer.r._onSBUpdateEnd (http://10.0.0.141:8123/frontend_latest/chunk.cf277186969c7b147807.js:2:145490)

```

**Comment by Pho3niX90** [comment]
PS: This seems to be related: https://github.com/home-assistant/frontend/issues/7267

**Comment by Pho3niX90** [comment]
Also, this might be useful: https://github.com/video-dev/hls.js/issues/2315

**Comment by bramkragten** [comment]
I think this should be handled in the integration, but not sure...
