### ISSUE TITLE
`crossorigin` attribute not set on tiles in map card

### ISSUE THREAD

**Issue by mdegat01** [home-assistant/frontend#8998]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using the map card, the images that make up the tiles of the map all come from `https://d.basemaps.cartocdn.com`. Since its not possible HA is also hosted at the same domain this will be a cross-origin request. It would be good if it set `crossorigin=anonymous` on the `img` elements that make up the map. This way the map can still work even if you configure your reverse proxy to return a [Cross-Origin-Resource-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Resource-Policy) header for security. Right now the map just fails to load if you do this since the elements don't say they are cross-origin.

Also browser's don't really like when you do this anymore (MDN says the browser marks it as 'tainted' in their docs on the [crossorigin attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#attr-crossorigin)) so it seems like good practice since this will definitely be a cross origin request.

### Describe the behavior you expected

I'd expect known cross-origin images to have the cross-origin attribute specified and work even if I returned `Cross-Origin-Resource-Policy: same-origin` as a header.

### Steps to reproduce the issue

1. Add a Map card to the HA UI (or just use the OOTB map dashboard)
2. Put a reverse proxy in front of HA and set it to return the following headers:
  a. `Cross-Origin-Embedder-Policy: require-corp`
  b. `Cross-Origin-Resource-Policy: same-origin`
3. Try to look at the map. Notice the background does not load.

### What version of Home Assistant Core has the issue?

core-2021.4.6

### In which browser are you experiencing the issue with?

Firefox, Chrome, Safari (have tried all 3, same result)

### Which operating system are you using to run this browser?

macOS Catalina (10.15.7)

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

I kind of lost these bouncing between windows. It was just a bunch of "cannot access resource due to COEP policy" errors. Do you need these? I can re-break things again if so.
```txt
# Paste your logs here.

```

**Comment by bramkragten** [comment]
Needs this:
https://leafletjs.com/reference-1.7.1.html#tilelayer-crossorigin
