### ISSUE TITLE
Shopping list doesn't autocapitalize items on mobile

### ISSUE THREAD

**Issue by sveinrou** [home-assistant/frontend#9007]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When adding new items to the shopping list on Android 10 the first letter has to be manually capitalized, which isn't a dealbreaker, but I think it's a little annoying

This happens both in app and browser

I got hold of an iPhone to try it out on, and it doesn't autocapitalize there either

### Describe the behavior you expected

On mobile, the input should start capitalized for the first letter

### Steps to reproduce the issue

1. Add the shopping list integration through the configuration tab
2. Go to the shopping list tab
3. Add a new item

### What version of Home Assistant Core has the issue?

2021.1.5

### In which browser are you experiencing the issue with?

Chrome 90.0.4430.82

### Which operating system are you using to run this browser?

Android 10; CLT-L29 Build/HUAWEICLT-L29

**Comment by spacegaier** [comment]
If we were to do that, then it should be consistent and not mobile-only. And then it comes down to, whether we just show the first letter capitalized in the UI, but leave the actual (backend) values as they are or whether the backend should actually overwrite the user input. Second option would be a breaking change.

**Comment by sveinrou** [comment]
I don't know that I expect the first letter to be autocapitalized on desktop. My thought was to unset the autocapitalize attribute, or set it to "sentences". I think this would be the behaviour that most people expect.
