### ISSUE TITLE
Home Assistant Cloud panel - different paddings

### ISSUE THREAD

**Issue by Yevgenium** [home-assistant/frontend#9015]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am using Home Assistant with Russian localization. When I go to the Home Assistant Cloud panel, the cards are displayed with different padding. If I switch the language to English everything is displayed correctly. 
English:
![EN](https://user-images.githubusercontent.com/33804747/116350948-99ea1800-a814-11eb-917c-5ee6f67eff6d.jpg)
Russian:
![RU](https://user-images.githubusercontent.com/33804747/116351887-2f39dc00-a816-11eb-811a-741d7e2b6c01.jpg)

### Describe the behavior you expected

Display information with the same padding in all languages. 

### Steps to reproduce the issue

1. Switсh language to Russian
2. Go to Configuration panel
3. Go to Home Assistant Cloud panel
...

### What version of Home Assistant Core has the issue?

core-2021.4.6

### In which browser are you experiencing the issue with?

Microsoft Edge 90.0.818.49

### Which operating system are you using to run this browser?

Windows 10 20H2

**Comment by spacegaier** [comment]
Seems to be a general issue, so not only linked to Russian (I see the same with German). In fact even in English it is not aligned for me. The info text on the left side has different widths (there is only a `max-width: 400px` defined for them). That seems to be why the cards on the right end up with different sizes.
