### ISSUE TITLE
Frontend caching is too aggressive

### ISSUE THREAD

**Issue by jurgenhaas** [home-assistant/frontend#9017]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When keeping the frontend open in the browser all the time on a desktop that runs 24/7, the cache size grows up to over 100 GB of data. Don't know what HA is doing with all that data on the client side, but I'm almost certain that's over the top.

On a mobile, where I open the app only now and then, the cache also grows to 4 GB which, I feel, is problematic.

### Describe the behavior you expected

Caching in the browser is great but it's hard to see what all that data (i.e. 100 GB) should ever be used for.

### Steps to reproduce the issue

1. Just keeping home assistant open for a few weeks

### What version of Home Assistant Core has the issue?

2021.4.6

### In which browser are you experiencing the issue with?

Chrome, Brave, Firefox

### Which operating system are you using to run this browser?

Ubuntu 20.04

**Comment by bramkragten** [comment]
Can you check where this data actually is?
In chrome:
Dev tools, application, storage, will give you something like this:

![image](https://user-images.githubusercontent.com/5662298/116399475-4209dc00-a829-11eb-9708-4ef1c1ad3ebf.png)

**Comment by jurgenhaas** [comment]
It's 99% in Cached Storage

**Comment by bramkragten** [comment]
Ok, can you then check what is in Cache storage that is so big?

**Comment by balloob** [comment]
Can you please list:
 - custom integrations
 - custom cards

**Comment by jurgenhaas** [comment]
Will do, when the size grew up again in a few days

**Comment by jurgenhaas** [comment]
So, after only 2 days the cache grew to 4 GB already.

@bramkragten how do I get to that information? I was only able to find the cache storage in the file system where it contains hundreds of files like `f3308566009b7192_0` and they all contain binary data, so I wasn't able to find out what's in them.

@balloob here are the custom components:

Custom integrations:

- deepstack_object
- dwd_weather
- edgeos
- elasticsearch
- gpodder
- hacs
- hpprinter
- plex_assistant
- shelly
- unifiprotect
- zoom

Custom cards:

- /hacsfiles/aftership-card/aftership-card.js
- /hacsfiles/apexcharts-card/apexcharts-card.js
- /hacsfiles/button-card/button-card.js
- /hacsfiles/ha-card-weather-conditions/ha-card-weather-conditions.js
- /hacsfiles/ha-floorplan/floorplan.js
- /hacsfiles/lovelace-badge-card/badge-card.js
- /hacsfiles/lovelace-clock-card/clock-card.js
- /hacsfiles/mini-media-player/mini-media-player-bundle.js
- /hacsfiles/podcast-card/podcast-card.js
- /hacsfiles/refreshable-picture-card/refreshable-picture-card.js
- /hacsfiles/upcoming-media-card/upcoming-media-card.js

**Comment by bramkragten** [comment]
> So, after only 2 days the cache grew to 4 GB already.
> 
> @bramkragten how do I get to that information? I was only able to find the cache storage in the file system where it contains hundreds of files like `f3308566009b7192_0` and they all contain binary data, so I wasn't able to find out what's in them.

In your chrome dev tools, you can see what files are in the cache:

![image](https://user-images.githubusercontent.com/5662298/116683392-d0a86580-a9af-11eb-8b48-c06cf60ce94d.png)

**Comment by jurgenhaas** [comment]
Oh, sorry, that was too easy ;-)

But it helped a lot and now I know what's going wrong. It the `refreshable-picture-card` which refreshes an image once per minute. Each of which is over 500K and then that adds up quickly as this custom card doesn't clean up anything obviously. I guess I should report the problem there.

**Comment by bramkragten** [comment]
I also changed our caching strategy, we now remove things from the cache after 24h.
