### ISSUE TITLE
Onboarding text has low contrast

### ISSUE THREAD

**Issue by bonanitech** [home-assistant/frontend#9029]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Onboarding text has low contrast with the background

### Describe the behavior you expected

Better contrast between text and background

### Steps to reproduce the issue

Install Home Assistant and start the onboarding process

### What version of Home Assistant Core has the issue?

2021.5.0b1

### In which browser are you experiencing the issue with?

Google Chrome 90.0.4430.93

### Which operating system are you using to run this browser?

macOS Big Sur 11.3

### Additional information

<img width="1440" alt="Screen Shot 2021-04-28 at 6 25 17 PM" src="https://user-images.githubusercontent.com/29807944/116481130-996f7280-a850-11eb-8829-632ce9f9bedd.png">

Also tested on Safari 14.1, same issue

**Comment by bonanitech** [comment]
I forgot to mention that my Mac is in dark mode.

**Comment by rmogstad** [comment]
It looks like a commit was added to fix this today

https://github.com/home-assistant/frontend/commit/65a30bf60c33c421ef78507a770f09357181d2b1
