### ISSUE TITLE
Unable to edit configurations in Add on applications on iOS devices (Safari)

### ISSUE THREAD

**Issue by gaussey** [home-assistant/frontend#9030]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The delete button is no longer working in the configurations editors of add on apps.

### Describe the behavior you expected

Being able to edit a configuration

### Steps to reproduce the issue

1. Install zigbee2mqtt addon
2. Attempt to edit the configuration by deleting characters
3. Nothing
...

### What version of Home Assistant Core has the issue?

HASSOS

### In which browser are you experiencing the issue with?

Safari

### Which operating system are you using to run this browser?

iOS

**Comment by bramkragten** [comment]
Duplicate and fixed
