### ISSUE TITLE
RAW Lovelace Editor doesn't load correctly second time

### ISSUE THREAD

**Issue by DavidFW1960** [home-assistant/frontend#9031]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using Chrome.
I edit the lovelace in raw mode save and close.
If I attempt to edit raw file again there is nothing in the file presented to edit - line 0 is the focus and the whole raw file is blank.
Close without saving and CTRL+R to refresh and edit again and all is OK

### Describe the behavior you expected

I expect to be able to edit in raw mode as per previous versions

### Steps to reproduce the issue

1. Edit dashboard in raw mode
2. save and close
3. edit the dashboard a second time - blank
4. close without saving
5. ctrl+R 
6. edit dashboard in raw mode again
7. all is well
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.5.0b1

### What was the last working version of Home Assistant Core?

2021.4.x

### In which browser are you experiencing the issue with?

Google Chrome Version 90.0.4430.93 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

**Comment by bramkragten** [comment]
Fixed with #9041
