### ISSUE TITLE
Spaces in frontend/translations/frontend/es-419.json cause **LOCATION** with **NAME** message

### ISSUE THREAD

**Issue by emavarela** [home-assistant/frontend#9032]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi community,

As with bug: https://github.com/home-assistant/frontend/issues/8395 in the transaltion es-419.json the same spaces are causing the login page to show a wrong wellcome message:

The code:
                "initializing": "Inicializando",
                "logging_in_to_with": "Iniciando sesión en ** {locationName} ** con ** {authProviderName} **.",
                "logging_in_with": "Iniciando sesión con **{authProviderName}**.",
                "pick_auth_provider": "O inicia sesión con"

Should be:

                "initializing": "Inicializando",
                "logging_in_to_with": "Iniciando sesión en **{locationName}** con **{authProviderName}**.",
                "logging_in_with": "Iniciando sesión con **{authProviderName}**.",
                "pick_auth_provider": "O inicia sesión con"

Note that spaces should be removed in the "logging_in_to_with".

Please see attached the error screenshot:

![loging screen](https://user-images.githubusercontent.com/58047343/116496768-2da2ff00-a87c-11eb-96a8-db704e25d37c.png)

Cheers,
Emanuel

### Describe the behavior you expected

The loging screen should display the correct Location and name instead of the placeholders code

### Steps to reproduce the issue

1. Open browser
2. Type home assistant url
3. See that the login screen has the placeholders LOCATION and NAME
...

### What version of Home Assistant Core has the issue?

core-2021.4.6

### Which operating system are you using to run this browser?

Windows 10 x64

**Comment by spacegaier** [comment]
The translations are handled by the community in a lokalise project, see docs: https://developers.home-assistant.io/docs/translations/

I have now moved the extra spaces from the one translation key.
