### ISSUE TITLE
Problem deleting item via Home Assistant UI

### ISSUE THREAD

**Issue by RssFra97** [home-assistant/frontend#9036]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hello, any element that can be deleted from the UI (from integrations to scripts to automations, etc ...) Home Assistant on HassOS does not delete it, returning an error in the browser console.

### Describe the behavior you expected

I expect the system to delete the item by deleting the code as well

### Steps to reproduce the issue

1. enter the UI and look for a disposable item
2. delete it
3. from the browser console check if it gives an error

### What version of Home Assistant Core has the issue?

core-2021.4.6

### What was the last working version of Home Assistant Core?

core-2021.4.6

### Javascript errors shown in your browser console/inspector

```txt
the errors are those in these screens:

https://ibb.co/DCK43Kb
https://ibb.co/r0zmgkh
```

**Comment by bramkragten** [comment]
I guess you are using a reverse proxy or something?

**Comment by RssFra97** [comment]
> 


> I guess you are using a reverse proxy or something?

i am using NGINX as a reverse proxy

**Comment by bramkragten** [comment]
This error is from your proxy not from HomeAssistant, check for errors in the logs of your proxy

**Comment by RssFra97** [comment]
I almost solved the problem by reconfiguring NGINX

**Comment by bramkragten** [comment]
almost? 😄

**Comment by RssFra97** [comment]
> almost? 😄

yes, because I have to do tests if everything remains working correctly in the next few days

**Comment by bramkragten** [comment]
I'll close this then :-)
