### ISSUE TITLE
Unable to update Addon

### ISSUE THREAD

**Issue by roschi02** [home-assistant/frontend#9057]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If i try to update an addon i get kickt out of home assistant and the sidebar is duplicated, on the app i just get kickt out.
A picture of the issue: [https://photos.app.goo.gl/3dSJRektPUFGtE8Z6](https://photos.app.goo.gl/3dSJRektPUFGtE8Z6)

### Describe the behavior you expected

It shouldn't kick me out

### Steps to reproduce the issue

just try to update an addon

### What version of Home Assistant Core has the issue?

core-2021.4.6

### In which browser are you experiencing the issue with?

Chrome Edge and the app

**Comment by spacegaier** [comment]
Worked fine for me back then (by now I am already on 2021.5 beta). The issue of duplicate sidebars appearing has been reported multiple times and is already fixed.

Reg. the update issue: Please define "get kicked out of HA". What exactly happens? Are you logged of from your instance in the browser?

**Comment by roschi02** [comment]
If I try another browser and don't activate the "stay logged in" I have to log in again. And if I activate "stay logged in" I get the logging in loading screen for a short time.
