### ISSUE TITLE
2021.4.5 breaks working zoom and ffmpeg cameras on fully kiosk browser from 2021.1.5

### ISSUE THREAD

**Issue by scstraus** [home-assistant/frontend#9069]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi, I upgraded from 2021.1.5 to 2021.4.5 and while it works fine on my desktop and phone, it completely breaks a couple very important things on fully kiosk browser running on kindle fire tablets. First, pinch to zoom was working great on 2021.1.5, something which strangely works on that version which didn't work for many versions. There are only a few months of versions I've used where it works and now it's broken again. If you allow zoom in fully kiosk, you can only zoom about 25% bigger in the new version, whereas it used to be unlimited in the 2021.1.5. 

And my ffmpeg cameras also behave much worse on the 2021.4.5 than they did on 2021.1.5. They freeze up very quickly and never come back, whereas on 2021.1.5, while they would freeze occasionally, they mostly would stay running for a good hour or 2, and I'd just have it refresh every so often.

### Describe the behavior you expected

Not freezing cameras and full pinch to zoom to any level of zoom

### Steps to reproduce the issue

1. Upgrade from 2021.1.5 to 2021.4.5
2. See not working pinch to zoom and cameras frozen
3. Cry
...

### What version of Home Assistant Core has the issue?

2021.4.5

### What was the last working version of Home Assistant Core?

2021.1.5 (last verified one, not sure exactly which version it stopped working)

### In which browser are you experiencing the issue with?

Fully kiosk broser

### Which operating system are you using to run this browser?

FireOS latest version

### Problem-relevant frontend configuration

```yaml
You can see the lovelace config I was using under 2021.1.5 [here]https://github.com/scstraus/home-assistant-config/tree/23de25169307dd5b435e6dd141b4b135cae6be91/lovelace) and the config I was running on 2021.4.5 before giving up and rolling back [here](https://github.com/scstraus/home-assistant-config/tree/a58c1383ae61ef2fefa0bf7df9c6bc49ca064cad/lovelace). No substantial differences.
```

### Javascript errors shown in your browser console/inspector

```txt
Nothing related to hass.
```

**Comment by spacegaier** [comment]
Pinch to zoom was removed in mid of February, see https://github.com/home-assistant/frontend/pull/8353.

**Comment by scstraus** [comment]
Argh, why?? Is there any way to re-enable it? It's a critical feature for us olds. Enough so that I will be stranded on 2021.1 without it as it's far more important to me than any of the features which have come since (including automation debugging which I was rather excited about but can't compete with not being able to see details easily on my dash).

**Comment by bramkragten** [comment]
You can also just zoom your browser?

**Comment by scstraus** [comment]
No, that's the whole point of the issue and why I opened this problem. It's actually blocking the zoom in the browser itself, despite that I have the setting allowing zoom set in fully kiosk browser enabled.  #8353 definitely broke zoom completely for fully kiosk browser.

**Comment by bramkragten** [comment]
I can't help you with fully kiosk browser, pinch to zoom might be disabled, but normal browser scale/zoom should just work.

**Comment by scstraus** [comment]
Pinch to zoom is definitely not disabled in the browser, it has a setting for it which I have enabled. It's something which #8353 broke. It worked fine in 2021.1 and now I'm stranded on that version because I can't live without it.

**Comment by scstraus** [comment]
I have moved this issue to the more focused one [here](https://github.com/home-assistant/frontend/issues/9251) which explains it better without the cameras which are a black art anyway.
