### ISSUE TITLE
Add-on options do not accept empty string, while valid

### ISSUE THREAD

**Issue by frenck** [home-assistant/frontend#9073]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The add-on accepts an empty string as a default value, however the UI shows:

![image](https://user-images.githubusercontent.com/195327/116807909-1db64400-ab36-11eb-8536-8f0a450f362b.png)

### Describe the behavior you expected

For it to save and accept the empty value.

### Steps to reproduce the issue

Used add-on schema:

```json
{
  "name": "AirCast",
  "version": "dev",
  "slug": "aircast",
  "description": "AirPlay capabilities for your Chromecast devices.",
  "url": "https://github.com/hassio-addons/addon-aircast",
  "startup": "services",
  "init": false,
  "arch": ["aarch64", "amd64", "armv7", "i386"],
  "hassio_api": true,
  "host_network": true,
  "map": ["config:rw"],
  "options": {
    "address": "",
    "latency_rtp": 0,
    "latency_http": 0,
    "drift": false
  },
  "schema": {
    "log_level": "list(trace|debug|info|notice|warning|error|fatal)?",
    "address": "str",
    "latency_rtp": "int",
    "latency_http": "int",
    "drift": "bool"
  }
}
```

### What version of Home Assistant Core has the issue?

supervisor-2021.04.dev2903

### What was the last working version of Home Assistant Core?

Not sure

### In which browser are you experiencing the issue with?

Google Chrome ersion 90.0.4430.93 (Official Build) (x86_64)

### Which operating system are you using to run this browser?

macOS Big Sur

### Problem-relevant frontend configuration

```yaml
address: ''
latency_rtp: 0
latency_http: 0
drift: false
```

**Comment by bramkragten** [comment]
Why not make address optional?

**Comment by frenck** [comment]
@bramkragten Because it is currently already like this with all current users... and than this bug gets in the way: #8614

**Comment by frenck** [comment]
Works 👍  Good enough.
