### ISSUE TITLE
Adding New Scene 

### ISSUE THREAD

**Issue by ozadr1an** [home-assistant/frontend#9075]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Scenes added via GUI are incorrectly written to scenes.yaml, rendering them non-editable in the GUI until a subsequent scene is added, at which point the 1st added scene is editable again. 

### Describe the behavior you expected

Scenes to remain editable when added via the GUI

### Steps to reproduce the issue

1. Go to Configuration -> Scenes -> +Add Scene
2. Enter any scene details - even just a name
3. Click "Save Scene"
4.  Receive error "Only scenes in scenes.yaml are editable." .
5. Click Ok. 
6. Scene is non-editable

If you then check scenes.yaml, the scene has been added with an "id: XXXXXXX" value, but it adds the " - " delimeter to the "name:" field, leaving the id in the wrong place - rendering the scene non-editable from the GUI. 

  id: 31f4299c2b9a4f9baf3b5b17a989a024
- name: New Scene 3
  entities: {}
  id: f015aab452e44cdaa612451db6a430d4
- name: New Scene 4
  entities: {}

### What version of Home Assistant Core has the issue?

core-2021.5.0b5

### What was the last working version of Home Assistant Core?

core-2021.4.6

### In which browser are you experiencing the issue with?

Chrome Version 90.0.4430.93 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 19042

### Problem-relevant frontend configuration

```yaml
scenes.yaml:

  id: 31f4299c2b9a4f9baf3b5b17a989a024
- name: New Scene 3
  entities: {}
  id: f015aab452e44cdaa612451db6a430d4
- name: New Scene 4
  entities: {}
```

**Comment by spacegaier** [comment]
I can confirm the issue. The problem is that after scene saving, the frontend tries to load the scene config, but apparently during saving it does not get an `id` stored. But when you save the second scene, the first one suddenly gets an `id` assigned, which is why it becomes editable then.
