### ISSUE TITLE
Zigbee2MQTT Light not showing brightness and color sliders

### ISSUE THREAD

**Issue by Avdbergnmf** [home-assistant/frontend#9077]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I added  [these](https://www.zigbee2mqtt.io/devices/HG06492B.html) lights through zigbee2mqtt (autodiscovery). They get recognized and added. I can toggle them through lovelace, but I can't control the brightness / color temp.

I can control the brightness & color temp through automations, and I can also control the light straight up through the z2m frontend interface just fine, just not through lovelace.

This is the developers attribute list:
```
effect_list: blink, breathe, okay, channel_change, finish_effect, stop_effect
supported_color_modes: color_temp
color_mode: color_temp
brightness: 159
color_temp: 449
device: 
applicationVersion: 80
dateCode: ''
friendlyName: lamp_slaapkamer_1
hardwareVersion: 1
ieeeAddr: '0x588e81fffedb7735'
manufacturerID: 4098
manufacturerName: _TZ3000_oborybow
model: HG06492B
networkAddress: 58096
powerSource: Mains (single phase)
stackVersion: 0
type: Router
zclVersion: 3

linkquality: 36
state: ON
friendly_name: Lamp Slaapkamer 1
supported_features: 44
```

### Describe the behavior you expected

For the brightness and color temp slider to appear with opening the entity in lovelace. 

### Steps to reproduce the issue

1. add light through zigbee2mqtt
2. add lovelace card with entity
3. open the card
...

### What version of Home Assistant Core has the issue?

container

### State of relevant entities

```txt
light.slaapkamer_1	on
```

**Comment by bramkragten** [comment]
Please complete the template, what version of Home Assistant Core is this on?

**Comment by bramkragten** [comment]
Seems to be related to <https://github.com/Koenkk/zigbee2mqtt/pull/7057>

**Comment by bramkragten** [comment]
Check the first line of the release notes:
https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.18.3

**Comment by Avdbergnmf** [comment]
Ah, perfect, thank you for the help! I totally missed that topic.
