### ISSUE TITLE
service_worker.js:1 Uncaught (in promise) TypeError: Failed to fetch

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#9081]
### The problem

Checking the inspector, this error is displayed. Clicking the underlined ```service_worker.js:1``` does exactly nothing.

### What is version of Home Assistant Core has the issue?

2021.3.4

### What was the last working version of Home Assistant Core?

DK

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

?

### Example YAML snippet

```yaml
_No response_
```

### Anything in the logs that might be useful for us?

```txt
service_worker.js:1 Uncaught (in promise) TypeError: Failed to fetch
```
in Chrome:
<img width="528" alt="Schermafbeelding 2021-03-25 om 16 15 47" src="https://user-images.githubusercontent.com/33354141/112496881-646d8d00-8d85-11eb-8d44-2c055b110d5d.png">

Safari inspector shows this:

<img width="623" alt="Schermafbeelding 2021-03-25 om 16 26 39" src="https://user-images.githubusercontent.com/33354141/112498649-080b6d00-8d87-11eb-993a-1a73845c00b7.png">

which also isn't clickable

Only other issue in the inspector seem to be these warnings:
```
home:19 A preload for 'https://mydomain.duckdns.org:port/frontend_latest/app.52350e7c.js' is found, but is not used because the script type does not match.
```

and 
```
The resource https://mydomain.duckdns.org:port/frontend_latest/core.a16e4a28.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

no relation to factual clicking or navigating in the Instance is obvious

**Comment by Mariusthvdb** [comment]
Havent seen that one around for some time now, but since it didnt show when this happened or what caused it, I have to let inspector run for some time to be sure it has gone...
please leave it open for a day or so, and if not seeing it again I'll close?

thanks

**Comment by bramkragten** [comment]
This was fixed
