### ISSUE TITLE
When selecting device in automation editor,  device dropdown (in trigger) doesn't show area

### ISSUE THREAD

**Issue by thealexparshin** [home-assistant/frontend#9099]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When selecting device in automation editor,  device dropdown (in trigger) doesn't show area (No Area).
Also, Area isn't shown for entities in Entities Card Configuration screen (entity name is shown instead).
Also, Area isn't shown for entities, for menu path: Configuration->Integrations->(Select HomeKit controller)->XX devices.

### Describe the behavior you expected

Showing area anywhere where device/entity name is shown. Otherwise, I get combinations like:
Light     Wall Switch-21B5
Light     Wall Switch-21B6
Light     Wall Switch-21A1
that I have to lookup in Configuration->Entitites for a matching area.

### Steps to reproduce the issue

1. Connect a homekit controller with several devices attached
2. Define area by editing each device
3. Try creating an automation and selecting Device

### What version of Home Assistant Core has the issue?

core-2021.4.6

### In which browser are you experiencing the issue with?

Firefox, Brave, Opera, Android app, etc

### Which operating system are you using to run this browser?

Linux, Android

**Comment by spacegaier** [comment]
Does this issue still occur? My devices all show the correct area (they are however not Homekit ones).
