### ISSUE TITLE
Erratic cursor in YAML card editor

### ISSUE THREAD

**Issue by vlumikero** [home-assistant/frontend#9101]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When editing a Lovelace card on my iPhone (either the companion app or Safari) the cursor behaves erratically and makes it impossible to edit cards. Backspace doesn’t work, and pasting text also fails. 

https://user-images.githubusercontent.com/13744614/117113596-fa380700-ad8a-11eb-9f6c-cf50d9e6b909.MP4

### Describe the behavior you expected

Normal behavior 

### Steps to reproduce the issue

1. Open mobile app
2. Edit mode
3. Edit card
4. Yaml editor
5. Type any text

### What version of Home Assistant Core has the issue?

Core-2021.4.3

### In which browser are you experiencing the issue with?

iOS companion 2021.4.1

### Which operating system are you using to run this browser?

iOS 14.4.2

**Comment by bramkragten** [comment]
Please search old issues first, there were multiple duplicated of this issue.

It is fixed in 2021.5 that will be release later today.

**Comment by vlumikero** [comment]
Thanks, I tried finding it but it was probably closed then already.
