### ISSUE TITLE
Cannot set time_between_updates for DSM_Reader via Integration page

### ISSUE THREAD

**Issue by gigatexel** [home-assistant/frontend#9104]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Recently, the DSMR Reader integration switched to GUI-configureable

DSMR Reader uses the time_between_updates parameter and this is settable using the Integration-options.
When you want to set this value, you cannot use the input field arrows if you value "rolls"

### Describe the behavior you expected

Being able to set using the input field arrows

### Steps to reproduce the issue

1. Install DSMR integration using the UI and click options
2. Set a value for the minimum time (e.g. 10)
3. Save
4. Click options again
5. If you click the "up" arrow, it rolls back to 1 instead of 11
...

### What version of Home Assistant Core has the issue?

core-2021.4.6

### In which browser are you experiencing the issue with?

Version 90.0.4430.93 (Official Build) (32-bit)

### Which operating system are you using to run this browser?

Win10

**Comment by bramkragten** [comment]
Not able to reproduce with the demo option flow

**Comment by gigatexel** [comment]
Roll-over seems fixed by reloading.

But what does not work over here, is selecting zero with the arrows. It skips zero.
