### ISSUE TITLE
Scene icons not displaying

### ISSUE THREAD

**Issue by nmummau** [home-assistant/frontend#9113]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Scene icons are not working. Specifically when trying to assign a scene to a button. But probably in other ways too.

### Describe the behavior you expected

1. Display icons for themes, and
1. Allow overriding the icon of a scene when creating a button to control the theme.

### Steps to reproduce the issue

1. Create a new scene through the UI. Configuration > Scenes > Add scene.
2. Give it a name of "Arrive Home" and an icon value of "hass:mdi-home-outline"
3. Save the theme.
4. Then edit one of your dashboards an add a Button Card pointing to this scene named "scene.arrive_home" 
    - When trying to create a simple button on a dashboard to point to this entity "scene.arrive_home", no icon is displayed in the card creator. Even if I edit the icon value in the card creator it does not display. 

### What version of Home Assistant Core has the issue?

core-2021.4.6

### In which browser are you experiencing the issue with?

Google Chrome 89.0.4389.114 (Official Build) (64-bit)

**Comment by spacegaier** [comment]
Your icon does not exist: The correct icon would "mdi:home-outline" ("hass:home-outline" works as well, but the "hass" prefix should only be used HA internally, so go with the first variant).
