### ISSUE TITLE
custom_ui_more_info/custom_ui_state_card still displayed in customizations option to override

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#9116]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

in the /configuration/customizations I can still select  custom_ui_more_info and custom_ui_state_card, which were options of the old custom_ui custom card.

I have carefully deleted all remnants of that, and searched a full config setup, including the hidden .storage for any references to those strings, and can 100% positively say the config holds nothing of the sorts.

No custom-ui is loaded, and all files are taken out of the config.

and still I see this:

<img width="597" alt="Schermafbeelding 2021-05-06 om 13 52 47" src="https://user-images.githubusercontent.com/33354141/117295072-afde8500-ae73-11eb-9243-5c32d1d42f31.png">

### Describe the behavior you expected

I would have expected these 2 options to not appear in the menu

### Steps to reproduce the issue

1. click /configuration/customizations
2. select entity
3. select pick an attribute to override
...

### What version of Home Assistant Core has the issue?

2021.5.0

### What was the last working version of Home Assistant Core?

dk

### In which browser are you experiencing the issue with?

all/any

### Which operating system are you using to run this browser?

Big sur 11.2.3 Safari 14.0.3 

### State of relevant entities

```txt
any entity, no matter what state
```

### Problem-relevant frontend configuration

```yaml
none
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

I am aware this is a remnant of a non supported custom card. And am not asking for support on that. I am merely asking how this could happen, or where these options in the system are stored. So I could take it away in my configs.

**Comment by bramkragten** [comment]
These can still be used to override the content of the `more-info` dialog, they have nothing to do with the external `custom_ui` package you mention.

**Comment by Mariusthvdb** [comment]
ok thanks, that's a relief!
