### ISSUE TITLE
LQI Column invalid sort order in ZHA component

### ISSUE THREAD

**Issue by ahd71** [home-assistant/frontend#9117]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

LQI Column sorted alphanumerical (101, 102, 31) instead of numerical (31, 101, 102) in the "Show Child" page from ZHA Component.

### Describe the behavior you expected

Sorting numerical (to find the lowest and highest signal quality peers)

### Steps to reproduce the issue

1. Open any entity in ZHA which has childs (and LQI values that qualifies for above criteria)
2. Click "View Children"
3. Click on Column Header "LQI" to sort 

### What version of Home Assistant Core has the issue?

2021.9.3

### What was the last working version of Home Assistant Core?

None

### In which browser are you experiencing the issue with?

Any

### Which operating system are you using to run this browser?

Any

**Comment by ahd71** [comment]
Issue still present in latest version which is 2021.7.4

**Comment by ahd71** [comment]
@dmulcahey Perhaps this is also something for you (probably easy to fix, worst case by padding with leading zeros!)

**Comment by dmulcahey** [comment]
I’ll look at it soon
