### ISSUE TITLE
The themes do not work for me in version 2021.5.0

### ISSUE THREAD

**Issue by albertopalotes35** [home-assistant/frontend#9122]
### The problem

I have updated the home assistant core to version 2021.5.0 and now the themes do not suit me, I have installed a theme and I select it in the user configuration but it shows me the default theme in dark, if I select the default and light mode It also shows me the dark one, it happens to me both in the browser and in the mobile app, before updating the themes, I have uninstalled the theme and reinstalled it, I have cleared the cache and cookies of my browser and I have made the forced reload in the browser and the themes do not suit me either.

### What is version of Home Assistant Core has the issue?

2021.5.0

### What was the last working version of Home Assistant Core?

2021.4.6

### What type of installation are you running?

Home Assistant OS

**Comment by spacegaier** [comment]
Does it also happen in private browsing mode in your browser? Are there any errors in the your browser console?

**Comment by albertopalotes35** [comment]
It also happens in the private mode of the browser and nothing appears in the browser console

**Comment by bramkragten** [comment]
You probably have simple weather card. Update it to the latest version.

**Comment by albertopalotes35** [comment]
I have a custom weather car and a custom card: PVPC Hourly Pricing  and if I remove the PVPC Hourly Pricing Card from the lovelace interface the themes will work again.

**Comment by bramkragten** [comment]
Ok, please create an issue with that card. They probably use the prototype of the `home-assistant` element, they should not do that.

**Comment by albertopalotes35** [comment]
I have reported the problem to the creator of that card

**Comment by spacegaier** [comment]
As reference for the future: This is the kind of things that needs to be adjusted in the custom cards: https://github.com/danimart1991/pvpc-hourly-pricing-card/pull/30
