### ISSUE TITLE
mqtt number entry in lovelace is capped to 100

### ISSUE THREAD

**Issue by blakadder** [home-assistant/frontend#9125]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Entry boxes for MQTT number entities are capped at 100 when using arrows to increment value. 

At the same time, when the value is entered with a keyboard it is highlighted red if above 100

![image](https://user-images.githubusercontent.com/5904370/117408698-96d7e180-af10-11eb-97f2-9ff6b9e82f0e.png)

### Describe the behavior you expected

Since MQTT number does not have min and max values allow entry of any value

### Steps to reproduce the issue

1. set up an MQTT number entity
2. go to Lovelace and try to increment it over 100 using the UI up arrow
3. in the same box try to enter a value over 100 manually

![](https://cdn.discordapp.com/attachments/805463034747027505/839947566501462057/unknown.png)

...

### What version of Home Assistant Core has the issue?

2021.5

### In which browser are you experiencing the issue with?

Brave Version 1.23.75 Chromium: 90.0.4430.93 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

**Comment by spacegaier** [comment]
What is the entity ID and please post the entity state from the HA dev tools in the issue template.

**Comment by blakadder** [comment]
Ah, now I see! Seems to be a hard coded limitation for the MQTT number integration that's not documented
