### ISSUE TITLE
History tab showing wrong service for when switch is turned on

### ISSUE THREAD

**Issue by engrbm87** [home-assistant/frontend#9128]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The History tab shows that the entity is switched on by `switch.turn_off` service.
![entity history typo](https://user-images.githubusercontent.com/5123967/117426635-c563b580-af2c-11eb-98c2-4a816ec17fee.png)

### Describe the behavior you expected

The history tab should show the correct service that changed the state of the entity

### Steps to reproduce the issue

1. Create an automation that turns_on or off a switch
2. Check the history tab once the entity has been switched on or off.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.5.0

### In which browser are you experiencing the issue with?

Firefox 88

### Which operating system are you using to run this browser?

Windows 10

**Comment by spacegaier** [comment]
Not a bug, but a backend design limitation: https://github.com/home-assistant/core/issues/45579

In the logbook panel you can see more details. We might add a quick navigation link (see discussion https://github.com/home-assistant/frontend/pull/8231).
