### ISSUE TITLE
Editing addon configuration files is broken - on iPad and Desktop

### ISSUE THREAD

**Issue by gaussey** [home-assistant/frontend#9133]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Editing configuration files inside addon store apps is broken, typing a letter anywhere moves the cursor back to home on iPad, on desktop whatever you type is either deleted or not saved at all.

Both the Zigbee2MQTT and Zigbee2MQTTassist apps suffer from this and is easily reproduced.

### Describe the behavior you expected

….

### Steps to reproduce the issue

1. Install Zigbee2MQTT
2. Attempt to edit and save the configuration file inside the addon.
2. 2
3. 3

https://user-images.githubusercontent.com/1004313/117522920-dd2f4e00-afad-11eb-834b-a4a39f6ac23f.mov

...

### What version of Home Assistant Core has the issue?

core-2021.5.1

### In which browser are you experiencing the issue with?

Safari/Firefox

### Which operating system are you using to run this browser?

iOS/Windows 10

**Comment by bramkragten** [comment]
This is fixed, but needs a new release of the supervisor
