### ISSUE TITLE
Sensor card updating other cards in Safari when opening dialog for details

### ISSUE THREAD

**Issue by P-Verbrugge** [home-assistant/frontend#9134]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When you have multiple sensor cards in a dashboard and click one of the sensor cards, the other sensors cards are updated. The other sensor cards get the same graph layout as the latest card on the dashboard. This only seems to happen in Safari.

### Describe the behavior you expected

I expected the to see the details of the sensor card I clicked and the other sensor card to not change.

### Steps to reproduce the issue

1. Add multiple sensor cards on your dashboard. For example a temperature, humidity and pressure sensor.
2. Display all cards in a vertical stack
3. Open Safari and click on one of the sensor cards
4. Close the details popup
5. All sensor graph cards on the same dashboard have now all change.
...

### What version of Home Assistant Core has the issue?

Core

### What was the last working version of Home Assistant Core?

Home Assistant 2021.4.5

### In which browser are you experiencing the issue with?

Safari Version 14.1.1 (16611.2.5)

### Which operating system are you using to run this browser?

macOS Big Sur 11.4

### Additional information

Video: https://youtu.be/7ZgC1VG5Kv8

**Comment by brtwrs** [comment]
I have exactly the same issue. @P-Verbrugge did you find a way to fix it?

**Comment by P-Verbrugge** [comment]
No, I have not fixed it. Not sure where this goes wrong. It's a HA issue I think that only happens in Safari.

**Comment by brtwrs** [comment]
In the Mac companion app it happens too btw

**Comment by ChopperRob** [comment]
I have a similar issue with the sensor card in the IOS app as well as the safari browser on the phone.
When multiple sensor card graphs are shown and you lock the phone or switch to another app and then come back all sensor cards show the same graph.
Rotating the device or switching to a different view fixes the issue.

**Comment by denwald** [comment]
This happens on my devices as well when I use the compansion app on iOS or Safari on macOS. If I click or tap on any of the sensor cards, all other cards show the same (identical) graph. To see the actual data again I have to reload the page. Unfortunatey there are no errors in the console.

Firefox on macOS, my main Browser, is not affected by this.

**Comment by ChopperRob** [comment]
Issue is still there on ios 15, latest home assistant version and companion app.

**Comment by deisi** [comment]
Year super annoying as it partially renders the sensor graphs useless. They all just show the same on IOS devices.

**Comment by Smiggel** [comment]
Still no fix for it. :-(

**Comment by jruston** [comment]
Also still experiencing this sadly, in the iOS companion app and in Safari on macOS.

**Comment by P-Verbrugge** [comment]
Same here. Still waiting for this ticket to be picked up. :-)

**Comment by MansM** [comment]
Keeps being an annoying issue

**Comment by jedisct1** [comment]
This seriously degrades usability on iOS.

**Comment by ryingg** [comment]
Still having this issue as well on Safari / iOS

**Comment by denwald** [comment]
This seems to be fixed on iPhone/iPad and macOS using the companion app or Safari. I'm using Home Assistant 2022.6.6 and the latest currently available iOS/macOS.

**Comment by domramsey** [comment]
Currently using the MacOS app and still experiencing this issue. Will it ever be fixed?

**Comment by jruston** [comment]
It does appear that this issue is not resolved. It was improved for me in 2022.5 or 2022.6 (it only happened occasionally) but it seems to occur quite frequently for me again in 2022.8 sadly. It does make using the iOS app quite annoying.

**Comment by TomiCode** [comment]
Sadly, this is still an issue in 2022.12.8, and it's a little bit annoying to refresh the dashboard after I've shown the details for something.
<img width="938" alt="Zrzut ekranu 2022-12-26 o 23 50 00" src="https://user-images.githubusercontent.com/1648325/209587230-0efe9b34-0fe9-4a2c-a4fe-70bdb616f322.png">

**Comment by automaton82** [comment]
Replication steps provided in a [Reddit thread about this](https://www.reddit.com/r/homeassistant/comments/10lxnib/annoying_bug_on_apple_devices_still_not_fixed/)  issue:

Drill into any sensor card graph, back out, switch to another app and back.

**Comment by Jorikay** [comment]
Dare to ask, @balloob this issue is open for 1,5 years and hasn’t actively been looked at, considering this bug report replies. Anything you can do to assist?
