### ISSUE TITLE
Removing blueprint causes automation to dissapear

### ISSUE THREAD

**Issue by euro2** [home-assistant/frontend#9146]
### The problem

removing a blueprint causes the created automation to dissapear and throws an error about a missing blueprint in the logs. 

Removing the automation cannot be done because its gone. 

Only re-adding the blueprint and THEN remove the automation first before removing the blueprint fixes the problem.

Maybe a warming popup it will delete the automations?

### What is version of Home Assistant Core has the issue?

core-2021.5.0

### What type of installation are you running?

Home Assistant Supervised

**Comment by balloob** [comment]
Moving this to the frontend. We should not allow deletion of blueprint if an automation is using it
