### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by andriej** [home-assistant/frontend#9176]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Error thrown in log.
Don't know the context, as there were no visible issue

### Describe the behavior you expected

No error in log

### Steps to reproduce the issue

No known steps to reproduce

### What version of Home Assistant Core has the issue?

core-2021.5.1

### In which browser are you experiencing the issue with?

Backend issue? Used browsers: latest chrome and companion app on Android

### Which operating system are you using to run this browser?

Windows 10 or Android 10's

### State of relevant entities

```txt
No entities in error
```

### Problem-relevant frontend configuration

```yaml
No configuration issue
```

### Javascript errors shown in your browser console/inspector

```txt
No error in browser
```

### Additional information

Error in HA logfile:
```
Logger: aiohttp.server
Source: components/frontend/__init__.py:512
First occurred: 10:01:38 (1 occurrences)
Last logged: 10:01:38

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 468, in _handle
    match_info = await self._router.resolve(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_urldispatcher.py", line 1004, in resolve
    match_dict, allowed = await resource.resolve(request)
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 512, in resolve
    and request.url.parts[1] not in self.hass.data[DATA_PANELS]
IndexError: tuple index out of range
```

**Comment by spacegaier** [comment]
Please provide some more context and if possible try to narrow it down. E.g. on which frontend page / URL were you when the error was logged?

**Comment by andriej** [comment]
The issue is that I can't provide much context - I've noticed it several hours after time it was logged. 
I might just guess it was about to show entity, that has disappeared (I've removed some entities days before), but can't confirm it.
