### ISSUE TITLE
Please reopen #8074

### ISSUE THREAD

**Issue by dzukero** [home-assistant/frontend#9185]
@dzukero Does this issue still persist? If yes I will reopen the ticket.

_Originally posted by @spacegaier in https://github.com/home-assistant/frontend/issues/8074#issuecomment-817373413_

**Comment by dzukero** [comment]
@spacegaier - yes, #8074 is still valid, nothing has changed.    Please keep it open.  Thanks!

**Comment by frenck** [comment]
Please just open a new issue with the latest data and reference the old. Thanks 👍
