### ISSUE TITLE
Unable to delete/remove integration that is in "not loaded" state

### ISSUE THREAD

**Issue by markheloking** [home-assistant/frontend#9189]
### The problem

When an integration enters in a "not loaded" state (for example the Ikea Tradfri integration because your Ikea Tradfri hub no longer functions/is not connected) you are unable to delete/remove this integration as the "three dots" button dissapears from the UI.

Example (note that the Tradfri IP is removed from this screenshot):
![image](https://user-images.githubusercontent.com/3192761/117545277-574ee980-b025-11eb-8601-20b6960c3199.png)

Example method to get an integration to end up "not loaded":

1. Install Tradfri hub
2. Install Tradfri integration
3. Unplug Tradfri hub
4. Restart homeassistant
5. Tradfri integration will stall startup by minutes, but end up in "not loaded" state and becomes impossible to remove/delete

### What is version of Home Assistant Core has the issue?

core-2021.5.1

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Ikea Tradfri, HACS, anything "not loaded" that I've found so far

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/tradfri/

### Additional information

The same issue seemed to be present in the core-2021.3.3 that I was running before upgrading just now.
I've already tried deleting all entities from the Tradfri integration (as you can tell from the screenshot), but I couldn't figure out how to delete the devices associated with this integration without being able to delete the integration.

**Comment by bramkragten** [comment]
This was fixed, will be in the next major release.
