### ISSUE TITLE
Logbook doesn't show customized icon/picture on many entities

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#9191]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

<img width="448" alt="Schermafbeelding 2021-05-17 om 11 25 16" src="https://user-images.githubusercontent.com/33354141/118466295-00bb6c80-b703-11eb-98ec-ffe73ad0ea5c.png">

Ive read #7734 and #7585 but am not sure what the implications there are for this issue. Clicking one of the items clearly shows the all have an icon or picture which can be seen by the backend and frontend. The missing picture is a regular (legacy) template sensor, the icons are templated using custom-ui, which shows correctly throughout HA, except for the logbook..

picture:

<img width="387" alt="Schermafbeelding 2021-05-17 om 11 31 09" src="https://user-images.githubusercontent.com/33354141/118466898-95be6580-b703-11eb-88c0-65c9521bd1f5.png">

icon:
<img width="391" alt="Schermafbeelding 2021-05-17 om 11 31 21" src="https://user-images.githubusercontent.com/33354141/118466926-9c4cdd00-b703-11eb-8c6f-9f47cd078960.png">

### Describe the behavior you expected

icon/picture displayed on all entities

### Steps to reproduce the issue

1. click logbook in left side menu
2. voila
3.
...

### What version of Home Assistant Core has the issue?

2021.5.4

### What was the last working version of Home Assistant Core?

Dk

### In which browser are you experiencing the issue with?

Any/all

### Which operating system are you using to run this browser?

Big sur 11.2.3 Safari 14.0.3 

### State of relevant entities

<img width="693" alt="Schermafbeelding 2021-05-17 om 11 36 22" src="https://user-images.githubusercontent.com/33354141/118467703-4fb5d180-b704-11eb-8d19-ecdff30b8699.png">
<img width="935" alt="Schermafbeelding 2021-05-17 om 11 37 08" src="https://user-images.githubusercontent.com/33354141/118467705-504e6800-b704-11eb-9990-d5ec344b5ec7.png">

### Problem-relevant frontend configuration

```yaml
none relevant to logbook?
```

### Javascript errors shown in your browser console/inspector

```txt
no errors
```

### Additional information

picture template sensor:
```
      wind_bft:
        friendly_name_template: >
          Bft: {{states('sensor.wind_bft')}}
        value_template: >
          {% set wind = 3.6 * states('sensor.windspeed')|float %}
            {% if wind <= 1 %}0
            {% elif wind <= 5 %}1
            {% elif wind <= 11 %}2
            {% elif wind <= 20 %}3
            {% elif wind <= 28 %}4
            {% elif wind <= 39 %}5
            {% elif wind <= 50 %}6
            {% elif wind <= 62 %}7
            {% elif wind <= 75 %}8
            {% elif wind <= 89 %}9
            {% elif wind <= 103 %}10
            {% elif wind <= 117 %}11
            {% else %} > 117 %}12
          {%- endif %}
        entity_picture_template: >
          {% set state = states('sensor.wind_bft') %}
          {% set path = '/local/weather/beaufort/' %}
          {% set ext = '.jpg'%}
            {{[path,state,ext]|join('')|lower}}
```

**Comment by Mariusthvdb** [comment]
Still happening in 2021.8

**Comment by bramkragten** [comment]
This will not be supported, we can't evaluate this for historic states.

**Comment by Mariusthvdb** [comment]
I see, thanks. closing.
