### ISSUE TITLE
Icon disappears when light color is white

### ISSUE THREAD

**Issue by kuchel77** [home-assistant/frontend#9197]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

<img width="125" alt="Screen Shot 2021-05-18 at 8 36 19 am" src="https://user-images.githubusercontent.com/52343790/118564850-6ca9dd80-b7b4-11eb-97a3-40b378f1cc2e.png">
<img width="124" alt="Screen Shot 2021-05-18 at 8 36 06 am" src="https://user-images.githubusercontent.com/52343790/118564844-66b3fc80-b7b4-11eb-87ab-f87d9dfedc05.png">

With a light strip with custom icon mdi:led-strip-variant, whenever the icon should be yellow, it disappears. The above is in a Grid card that has 4 columns.

<img width="165" alt="Screen Shot 2021-05-18 at 8 36 49 am" src="https://user-images.githubusercontent.com/52343790/118565000-c27e8580-b7b4-11eb-8ac3-9d10064b3183.png">
<img width="162" alt="Screen Shot 2021-05-18 at 8 36 56 am" src="https://user-images.githubusercontent.com/52343790/118565003-c4e0df80-b7b4-11eb-8d93-65fc60af8fce.png">

This is the same grid card at 3 columns instead.

Both are using the default light card for them.

The same happens when I have them in an auto-entities based sensor. 

<img width="472" alt="Screen Shot 2021-05-18 at 8 42 13 am" src="https://user-images.githubusercontent.com/52343790/118565273-3b7ddd00-b7b5-11eb-9e48-bb48870e9680.png">
<img width="483" alt="Screen Shot 2021-05-18 at 8 42 41 am" src="https://user-images.githubusercontent.com/52343790/118565283-43d61800-b7b5-11eb-9dde-e65b58d9851c.png">

And as a button.

<img width="130" alt="Screen Shot 2021-05-18 at 8 44 00 am" src="https://user-images.githubusercontent.com/52343790/118565301-4b95bc80-b7b5-11eb-9d22-55a540da8c5e.png">

### Describe the behavior you expected

Icons shouldn't disappear. A default light bulb icon doesn't disappear when on.

<img width="122" alt="Screen Shot 2021-05-18 at 8 45 49 am" src="https://user-images.githubusercontent.com/52343790/118565405-74b64d00-b7b5-11eb-9186-fceb090900a3.png">

Nor do groups of lights

<img width="120" alt="Screen Shot 2021-05-18 at 8 46 19 am" src="https://user-images.githubusercontent.com/52343790/118565455-8992e080-b7b5-11eb-8b9b-6cf3cbaece7d.png">

### Steps to reproduce the issue

Add the to lovelace and turn them on.

### What version of Home Assistant Core has the issue?

core-2021.5.4

### In which browser are you experiencing the issue with?

Safari Version 14.1.1 (16611.2.3) and Firefox 88.0.1 (64-bit) and current IOS app.

### Which operating system are you using to run this browser?

macOS Big Sur Version 11.4 Beta

### State of relevant entities

```txt
All of these are just lights going from on to off.
```

### Problem-relevant frontend configuration

```yaml
type: grid
cards:
  - type: light
    entity: light.living_room_led_lights
columns: 4

```
```


### Javascript errors shown in your browser console/inspector

```txt
Nothing here
```

### Additional information

From customize.yaml:
```
light.lounge_room_led_lights:
  icon: mdi:led-strip-variant
```

**Comment by spacegaier** [comment]
I cannot reproduce the issue. Works fine for me (regarldess of whether I set an icon via customize or via unique ID in the config entry).

**Comment by spacegaier** [comment]
Update: I now added my RGBW LED strips into HA. The icon "disappears" when I set the strip to white. It is then a white icon on a white background.

Can you confirm if that is the issue you reported, so are your LED strips white capable? Can you check the icon behaviour in the dark theme mode.

**Comment by kuchel77** [comment]
![Screen Shot 2021-05-21 at 5 43 04 pm](https://user-images.githubusercontent.com/52343790/119120674-e3263400-ba6f-11eb-98be-657a41511446.png)
![Screen Shot 2021-05-21 at 5 43 15 pm](https://user-images.githubusercontent.com/52343790/119120694-e8837e80-ba6f-11eb-8b81-c29e1ffb6ba0.png)

![Screen Shot 2021-05-21 at 8 07 01 pm](https://user-images.githubusercontent.com/52343790/119120997-3f895380-ba70-11eb-82dc-ee6b78d24c45.png)
![Screen Shot 2021-05-21 at 8 07 33 pm](https://user-images.githubusercontent.com/52343790/119121015-44e69e00-ba70-11eb-8b4a-b97c7ba6cb0e.png)

That makes sense. So in the above photos, Frog Tank Lights are a switch (UV lights), where as the rest are LED light strips that by default are white lights above fish tanks (even though I haven't customised Lounge as yet because we haven't got fish in there at the moment). 

In dark mode, it shows them working as they should be. With the first and third image, both Frog Tank Lights and Boys Bedroom are on, but in the second and fourth, all of them are off (they are the best to compare here).

The first two images are just using the default theme.

**Comment by spacegaier** [comment]
@matthiasdebaat FYI: This is one of the light icon issues we touched upon on Monday in our meeting.

**Comment by SAOPP** [comment]
Guys, the same thing happens to me for 2021.9.3, I give an example in the video below:


https://user-images.githubusercontent.com/5647009/132176790-e8ef363b-8228-495e-a845-fa68ef4d4aad.mp4

**Comment by SAOPP** [comment]
A terrible bug actually.

![20210906-190920](https://user-images.githubusercontent.com/5647009/132243177-bb0c37dc-0991-4086-a610-5fb624208a5c.png)
