### ISSUE TITLE
Link to template documentation is broken

### ISSUE THREAD

**Issue by gpend** [home-assistant/frontend#9203]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The link on /developer-tools/template to 'Jinja2 template documentation" leads to a 'page not found' page.

### Describe the behavior you expected

The link should lead to the Jinja documentation.

### Steps to reproduce the issue

1. open Developer tools
2. navigate to the template page
3. click the 'Jinja2 template documentation' link
...

### What version of Home Assistant Core has the issue?

2021.5.4

### In which browser are you experiencing the issue with?

Google Chrome 90.0.4430.212

### Which operating system are you using to run this browser?

Windows 10

**Comment by bramkragten** [comment]
Was fixed!
