### ISSUE TITLE
Map in general config broken

### ISSUE THREAD

**Issue by bigboban** [home-assistant/frontend#9215]
### The problem

Unable to set HA instance coordinates because map is broken - empty.

![image](https://user-images.githubusercontent.com/7159224/118984317-ac6ff100-b97d-11eb-9c99-642abf92313a.png)

### What is version of Home Assistant Core has the issue?

2021.5.3

### What type of installation are you running?

Home Assistant Supervised

**Comment by spacegaier** [comment]
Please check your browser console. Any errors listed there? Is that a new installation or did it work on that one before? Anything that could interfere network wise (proxy, firewall, ...).

**Comment by bigboban** [comment]
No error in JS console nor network tab. BUT!

When homeassistant: config is in yaml, map is OK but global sesttings are disabled.
When i delete homeassistant block from yaml, settints like timezone are accessible but map is broken.
And... when i put homeassistant back to yaml - map is OK again!!

So - **map is broken only when homeassistant settings are NOT in yaml and Global settintgs should work on UI.**

Tested on two different HA instances and same behavior.

**Comment by spacegaier** [comment]
Unfortunately, I cannot reproduce the issue. In my instances I did not put anything in the YAML and the UI and map works fine.

Did you try in private browser mode to rule out any caching issues? Can you please fill in your browser versions above (see the new issue template here in the frontend repository).

**Comment by bigboban** [comment]
Chrome 90.0.4430.212 (Official Build) (64-bit) - BROKEN
Same chrome private tab - BROKEN
MS Edge Version 90.0.818.66 (Official build) (64-bit) - BROKEN
MSIE 11 - Broken all HA, unable to login.. 

I think i cannot be due some adblock, network issue - why map is ok in yaml mode and broken in UI mode?

Same issue is on two different HA instances in two different houses and different LANs with different inet providers.

**Comment by bigboban** [comment]
Some investigation. On HA where config is in yaml and map ok:

![image](https://user-images.githubusercontent.com/7159224/119706236-fc592700-be59-11eb-956a-4c37c634b3ba.png)


On HA where config is in menu and map not ok:

![image](https://user-images.githubusercontent.com/7159224/119706142-e3e90c80-be59-11eb-988d-f47e90e10744.png)

Some bug of openstreetmaps? But why ok in "disabled" mode and not ok in editable mode?

**Comment by spacegaier** [comment]
Can you compare the requests that are being sent out to get those map tiles? Are they different between YAML and non-YAML mode?

**Comment by bigboban** [comment]
It seems there is no difference.

Example of OK image:
https://b.basemaps.cartocdn.com/light_all/14/8846/5555.png

Example of err image:
https://b.basemaps.cartocdn.com/light_all/9/257/256.png


When I zoom with mouse wheel I see many many similar image requests. All "blind" or error map and all fine on read-only (ok) map.

**Comment by bramkragten** [comment]
What coordinates are set in storage?

**Comment by spacegaier** [comment]
And just to be safe: Did you really (REALLY :) !) zoom out far enough on the map, because the returned image looks like an ocean tile.

**Comment by bigboban** [comment]
I started write something like "of course i zoomed enough i am not stupid!"... So I did not 3 but maybe 10 wheel loops... and ... THAT'S IT:

![image](https://user-images.githubusercontent.com/7159224/119713946-8f965a80-be62-11eb-8cdd-a4cc356360f5.png)

So it is NOT bug.

But maybe some lessons learned - HA should NOT set some "default"?? coordinates in the middle of ocean?

**Comment by spacegaier** [comment]
Yes, that is GPS [0, 0] on the map.

In the coding we set a default of [52.3731339, 4.8903147]. I wonder if that got ignored since you had a YAML interfere at some point.

**Comment by bigboban** [comment]
Yes I think it is default after yaml cleanup. But I think you SHOULD fix it. BTW it requires exactly TEN mouse wheel turns or TEN minus sign clicks to see something on map. I think no one will figure this out.

**Comment by spacegaier** [comment]
Not sure if we could add some logic that if no coordinates are set and we are at [0, 0] we zoom out quite a bit to not only show a pure ocean view, but some continent borders.
