### ISSUE TITLE
Details light domain cut off

### ISSUE THREAD

**Issue by Meniak666** [home-assistant/frontend#9218]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When opening details of a light domain entity, the bottom is cut off, switch domain doesn't have this problem.
![Capture](https://user-images.githubusercontent.com/14911740/119047816-ae0dd900-b9be-11eb-8573-ac89ac269c11.PNG)

### Describe the behavior you expected

The deatils shouldn't be cut off so we can read everything.  We can copy/paste all the info so the data is all there, it's just cut off in UI.

### Steps to reproduce the issue

1. click on light entity that has info in the bottom
2. See it being cut off
3.
...

### What version of Home Assistant Core has the issue?

core-2021.5.5

### What was the last working version of Home Assistant Core?

core-2021.5.5

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```
supported_color_modes:
  - brightness
color_mode: brightness
brightness: 81
shelly_type: Shelly Dimmer 2
shelly_id: E8DB84A1C05C
ip_address: 192.168.1.13
room: Keuken
protocols:
  - CoAP-msg
over_temp: 0
current_consumption: 12 W
friendly_name: Keuken
supported_features: 1
```

**Comment by spacegaier** [comment]
Can you please paste the light entity state (from the HA dev tools "State" tab).

**Comment by Meniak666** [comment]
![Capture](https://user-images.githubusercontent.com/14911740/119049569-004ff980-b9c1-11eb-8891-d25f1c556fc0.PNG)

**Comment by spacegaier** [comment]
Please add as text to the original post, so we can copy&paste it into our dev instance to test. Much easier than typing everything from your screenshot 😉.

**Comment by Meniak666** [comment]
> Please add as text to the original post, so we can copy&paste it into our dev instance to test. Much easier than typing everything from your screenshot 😉.

Done
