### ISSUE TITLE
An integer value in a helper is converted to a float

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#9224]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I created an input_number helper with values from 1 to 7 whose unit of measure is days...

![Helpers](https://user-images.githubusercontent.com/74879713/119197184-a82ffa80-ba87-11eb-9fd6-4bd4799f54ce.PNG)

...but in the card the value is converted to float

![Card](https://user-images.githubusercontent.com/74879713/119197214-b0883580-ba87-11eb-91ed-e4252e58030f.PNG)

### Describe the behavior you expected

IMO the values created in the helpers should reflect the values in the cards: so only if there are float values in the helper, they will be displayed as such in the card

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.5.5

### In which browser are you experiencing the issue with?

Chrome and Firefox: the latest versions

### Which operating system are you using to run this browser?

Windows 10, Android 11, Android Companion App

**Comment by spacegaier** [comment]
If you check the backend state of the helper (e.g. via the HA dev tools) you will see, that the actual backend value is a float, so the frontend is displaying the correct value in the card.

**Comment by WRoss7** [comment]
Hi spacegaier,
correct, let me explain better. What I mean is that for a few weeks a value of a helper has been displayed to me as a float, and it is not the best of life to see 7.0 days: it seems that all integer values ​​are rendered as floats.
By heart, the "bug" came out of the introduction of the number format choice # 8811

![Timer](https://user-images.githubusercontent.com/74879713/119716158-1ba98180-be65-11eb-86f1-7127112a4a1d.PNG)

![Float](https://user-images.githubusercontent.com/74879713/119716405-64f9d100-be65-11eb-8524-78e5a1d370ff.PNG)

**Comment by WRoss7** [comment]
@matthiasdebaat what do you think? it doesn't seem very nice to see entities with labels like "7.0 days"

**Comment by matthiasdebaat** [comment]
> ![Timer](https://user-images.githubusercontent.com/74879713/119716158-1ba98180-be65-11eb-86f1-7127112a4a1d.PNG)

If I understand you correctly, you want a `7` instead of `7,0`? Can an `input_number` work with decimals? In that case I agree that it would be nicer to remove the decimal.

**Comment by matthiasdebaat** [comment]
> ... , or more elegantly adding a checkbox to allow the user to force the value to integer.

I like this, we could add this to the Lovelace card. Wondering if this is a `Advanced option`.

**Comment by joshmcrty** [comment]
`input_number` entities can have float values if the `step` is set to less than `1`.

As @spacegaier said, the actual value of an `input_number` is always stored as a float, so the frontend number formatting preserves that and intentionally keeps the trailing zero.

For an immediate fix you could create a template sensor that rounds the value of the `input_number` to an integer and display that in Lovelace.

I like the idea of having more advanced settings for Lovelace cards that enable greater control over how things are displayed, but that seems like an architecture decision, see https://github.com/home-assistant/architecture/discussions/571

**Comment by WRoss7** [comment]
@joshmcrty thank you for the tip.
Sorry for the late reply: my microSD card has broken and no longer boots 😭 . I am awaiting the delivery of an SSD to be used in conjunction with a new microSD.


> `input_number` entities can have float values if the `step` is set to less than `1`.

@spacegaier @joshmcrty @matthiasdebaat I thought ... wouldn't it be easier to automatically format the value of an input-number at the card level if its step is an integer?

**Comment by ildar170975** [comment]
IMHO:
There is no need for any Advanced options.
The `input_number` integration has a "step" option.
Frontend should display as many digits after point as the "step" accuracy:
step: 1000,100,10,1 -> display 0 digits after point
step: 0.1 -> display 1 digit after point
step: 0.01 -> display 2 digits after point
and so on

**Comment by WRoss7** [comment]
If you look at the screenshot the step is set to 1 (not 0.1), but the card shows 7.0 days.

**Comment by ildar170975** [comment]
Please un-stale

**Comment by ildar170975** [comment]
Bump

**Comment by WRoss7** [comment]
On Home Assistant 2022.10.1

in more info the data is formatted correctly
![Img](https://user-images.githubusercontent.com/74879713/194712587-28fcd408-7fea-47aa-9227-36d8f88d9f03.png)

but in cards no
![Img2](https://user-images.githubusercontent.com/74879713/194712777-d9df5d92-70c2-4809-8444-224a0d3ea890.png)

**Comment by WRoss7** [comment]
Another squashed bug.
Thanks joshmcrty
