### ISSUE TITLE
Missing options in tile for "Not Loaded" integration

### ISSUE THREAD

**Issue by MarijnPessers** [home-assistant/frontend#9240]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Exactly the same as this issue: https://github.com/home-assistant/core/issues/51039

In short: A device is no longer connected to my network (in this case Ikea Tradfri). I am getting the message "Not Loaded" in the tile and I have no three dots to select to delete this item. I have no intention to add the item again. I just want to remove it from my configuration.

### Describe the behavior you expected

Three dots to delete the item.

### Steps to reproduce the issue

Mess something up and have the "Not Loaded" message in the tile. The integration can;t be deleted anymore.

### What version of Home Assistant Core has the issue?

2021.5.5

### In which browser are you experiencing the issue with?

Not a browser issue. Html is not rendered(I checked the source code)

### Which operating system are you using to run this browser?

Not a computer issue.

### Javascript errors shown in your browser console/inspector

```txt
None.
```

### Additional information

I have seen a lot of recent mentions. It seems a programming issue that forgets to render the 3 dots int he tile when there is a "Not L
![not loaded](https://user-images.githubusercontent.com/28067017/119404641-5fbf4980-bce0-11eb-953d-61f13ecc5b9a.png)
oaded" message.

**Comment by bramkragten** [comment]
Duplicate and fixed in next release

**Comment by MarijnPessers** [comment]
Hoi Bram,
Long time no see :) Sorry for the double post. I replied to that post I linked 20 seconds after it was closed. I was told to make a separate bug report. Great to see it will be fixed.
