### ISSUE TITLE
Unable to remove integrations

### ISSUE THREAD

**Issue by Akkor70** [home-assistant/frontend#9242]
### The problem

I have a problem removing integrations on HA
When I select from menu uninstall, the confirmation popup appears, click ok and after nothing happens
I can't find any related error on log
Suggestion ?

### What is version of Home Assistant Core has the issue?

core-2021.5.1

### What type of installation are you running?

Home Assistant Supervised

**Comment by bramkragten** [comment]
> I have a similar issue.
> I have the font-awesome integration removed from HACs and now I can not remove it from the integrations panel:
> 
> ![image](https://user-images.githubusercontent.com/2270425/119348791-a0e23a00-bc9d-11eb-952b-938c528760ca.png)

Duplicate and fixed

**Comment by bramkragten** [comment]
@Akkor70 check your browser console and network calls please

**Comment by Akkor70** [comment]
> @Akkor70 check your browser console and network calls please

What to check in browser console and network calls ?
I temporally solved editing core.config_entries in /usr/share/hassio/homeassistant/.storage

**Comment by bramkragten** [comment]
> What to check in browser console and network calls ?
Errors

What integration is this about? And is it just one integration?

**Comment by Akkor70** [comment]
> What integration is this about? And is it just one integration?

I had problem uninstalling all integrations

**Comment by bramkragten** [comment]
Had? As in, it works now?

**Comment by Akkor70** [comment]
> Had? As in, it works now?

As I said befour..........I temporally solved editing core.config_entries in /usr/share/hassio/homeassistant/.storage
