### ISSUE TITLE
The color of light sensors 💡is gray when it is on but would be yellow

### ISSUE THREAD

**Issue by rodrigogbs** [home-assistant/frontend#9255]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After upgrading to 2021.5 core version the color of light sensors 💡is GRAY when it is ON, like if the entity is unavailable.

### Describe the behavior you expected

The color of light sensors 💡must be YELLOW when it is ON.

### Steps to reproduce the issue

1. Configure a light entity 💡
2. Turn it on (in example attached, the entities “Fita Led Cabeceira Suite” and “Fita Led TV Suite” are showing the problem)

![70BE25C2-1BA3-4CCB-88AD-EA62BB443182](https://user-images.githubusercontent.com/71797145/119575567-a1f29480-bd8d-11eb-930e-cbc332efd774.jpeg)

### What version of Home Assistant Core has the issue?

Core-2021.5.5

### What was the last working version of Home Assistant Core?

Core-2021.4.6

### In which browser are you experiencing the issue with?

Google Chrome 90.0.4430.216 / IPad or iPhone or Macbook app

### Which operating system are you using to run this browser?

Windows 10 / iOS 14.6 / iPad OS 14.6 / macOS Big Sur 11.4

**Comment by spacegaier** [comment]
It will be yellow if the light does not support colors, but only on/off or dimming. But if colors come into play, the rendering gets tricky. Currently you can even end up with a white icon and white background.

Are those RGB/RGBW lights? Please fill in the issue template section for the entity state.

**Comment by rodrigogbs** [comment]
@spacegaier you are right, I didn’t notice this new feature! I changed the color of the RGB light using the palette from entity on HA and the color of the sensor updated !!

Thanks a lot!

![9811CE08-65FA-419C-8A58-ABE25B27E020](https://user-images.githubusercontent.com/71797145/119580962-f6027680-bd97-11eb-89ae-1c3ec2dc3b9f.jpeg)

**Comment by rodrigogbs** [comment]
@spacegaier I’ve just realized that after restarting HA the color of the sensor became gray again. Is it possible to steady the color?

**Comment by spacegaier** [comment]
The frontend will render what the backend provides as data. Is HA not getting / querying the color state from your device after the restart? If not, that would be a backend topic.

**Comment by rodrigogbs** [comment]
Perfect, I’ll open a backend issue.

Thanks again.

**Comment by spacegaier** [comment]
I fixed the link in your last comment so that the two tickets get a connection and I will close this one, as it is now tracked in the backend.
