### ISSUE TITLE
Difference between Edge and Safari on startup

### ISSUE THREAD

**Issue by dof250** [home-assistant/frontend#9256]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

It's not really important, but it's funny to see. I "accidentally" had Safari and Edge open at the same time when restarting HA Core and suddenly I saw a difference in the startup banner. In Edge it shows the complete name, but for Safari it seems to use a shorter name.

<img width="525" alt="Schermafbeelding 2021-05-26 om 08 51 07" src="https://user-images.githubusercontent.com/61125770/119615802-1a923900-be00-11eb-8e31-c243789286b0.png">
<img width="484" alt="Schermafbeelding 2021-05-26 om 08 51 09" src="https://user-images.githubusercontent.com/61125770/119615808-1e25c000-be00-11eb-8c5f-5b294eff0a82.png">

### Describe the behavior you expected

The banner to be the same on both browsers

### Steps to reproduce the issue

1. Open Safari and Edge
2. Restart HA Core

### What version of Home Assistant Core has the issue?

core-2021.5.5

### In which browser are you experiencing the issue with?

Safari 14.1

### Which operating system are you using to run this browser?

macOS Big Sur 11.4

**Comment by spacegaier** [comment]
I always only see the internal short name on FF and Chrome (e.g. for "hacs"). Looking at the coding I could imagine that the component translations used by `domainToName()` might not be loaded. I verified that the first `||` branch is used in my instance.

https://github.com/home-assistant/frontend/blob/b6c5223221c2911a187a828bf58bf183d569e200/src/state/disconnect-toast-mixin.ts#L114-L119

@bramkragten Does it work for you?

**Comment by bramkragten** [comment]
It is a timing thing, that's why we have the fallback. The backend translation might not have been loaded yet.

**Comment by spacegaier** [comment]
> 
> 
> It is a timing thing, that's why we have the fallback. The backend translation might not have been loaded yet.

`ui.notification_toast.intergration_starting` is loaded for me, only the component titles are not yet (used by `domainToName()`). Could it be worthwhile to enforce a load from the toast?

**Comment by bramkragten** [comment]
The first is frontend translation, the second backend. 

Yes, we might want to load the backend translations sooner, but not sure if we will even get them if the integration is not loaded yet...

**Comment by dof250** [comment]
> It is a timing thing, that's why we have the fallback. The backend translation might not have been loaded yet.

The screenshots are simultaneously taken. Shouldn't it be the same in both browsers then? I can reproduce this every restart.

**Comment by spacegaier** [comment]
> 
> Yes, we might want to load the backend translations sooner, but not sure if we will even get them if the integration is not loaded yet...

OP's screenshots would imply so, since in one browser we can see the translated integration name or do you think that is purely lucky caching?
