### ISSUE TITLE
Flux LED/MagicLight lightbulb need to be pressed twice

### ISSUE THREAD

**Issue by lovisair** [home-assistant/frontend#9274]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I connected my LED's with a wifi device that works with the app MagicLight. 
Now when i press the button on my lovelace it goes on but it does not show the brightness and the color. If i press another time the brightness and color shows up and the LED's are still on.
When i press the lightbulb once again the LED's goes off but lovelace shows that the light is on. On pressing the Lightbulb another time brightness and color shows off and the LED's are off as well.

### Describe the behavior you expected

So normaly any other lightbulb on my lovelace goes on and off as it should. Also on the Magic Home app it goes on and off as it should.

### Steps to reproduce the issue

1. Install Magic Home app on Smartphone
2. Connect the LED's with Magic Home app
3. Connect LED's whith Home Assistant as described in the documentation: [Flux LED/MagicLight](https://www.home-assistant.io/integrations/flux_led/)
You should have a working device like this:
![Fluxled](https://user-images.githubusercontent.com/61051800/119795186-88aa2f00-bed8-11eb-8704-d0f7496ef8e2.jpg)

...

### What version of Home Assistant Core has the issue?

core-2021.6.0b0

### What was the last working version of Home Assistant Core?

core-2021.5.5

### In which browser are you experiencing the issue with?

Firefox, Edge, Chrome

### Which operating system are you using to run this browser?

Windows

### Problem-relevant frontend configuration

```yaml
light:
  - platform: flux_led
    # automatic_add: true
    devices:
      192.168.1.131:
        name: LED_Strip
        mode: "rgb"
```

**Comment by spacegaier** [comment]
Can you please check if that is the same behaviour if you trigger the device with service calls through the HA dev tools and then check their returned data in the dev tools? 

Since the frontend is simply showing the data it gets from the backend, the issue could be there. This test should clarify that (if frontend is displaying something incorrectly, or if backend is behaving weird/different).

**Comment by lovisair** [comment]
I tried to trigger it on dev tools.
If i call the service with **light.turn_on** and **light.turn_off** it works on the first time. But:

- light.turn_on: state is on and brightness on 0, light on
- light.turn_on after 10 seconds: state is on and brightness on 255, light on
- light.turn_off: state is on and brightness on 255, light off
- light.turn_off after 10 seconds: state is off and brightness on 0, light off


If i call the service with **light.toggle** i have to click twice to turn the light on and off.

If i press once to turn it off it is schowing me brightness 255 and it is on, but the LED's are off like described above.
The same thing vice versa if i turn it on with toggle.
