### ISSUE TITLE
Theme is not used in certain lovelace views

### ISSUE THREAD

**Issue by reotto613** [home-assistant/frontend#9277]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the HACS and as well as the Supervisor front ends, the selected theme (3rd party-Google Dark) is not being used/selected for those two screens.  All other screens are fine.  If I change it backend selected theme, and change it to dark then the issue is resolved.

### Describe the behavior you expected

I would expect the theme settings would be utilized in the frontend lovelace for all views.

### Steps to reproduce the issue

1.Upgrade to latest beta release of HA core-2021.6.0b & Supervisor supervisor-2021.05.3
2. Check HACS library view or Supervisor view
3.
...

### What version of Home Assistant Core has the issue?

core-2021.6.0b0

### What was the last working version of Home Assistant Core?

2021.5.4

### In which browser are you experiencing the issue with?

Google Chrome Version 89.0.4389.114, Microsoft Edge Version 89.0.774.68, Safari 14.5

### Which operating system are you using to run this browser?

Windows 10 Enterprise & iOS 14.5

### State of relevant entities

```txt
N/A
```

### Problem-relevant frontend configuration

```yaml
N/A
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

### Additional information

N/A

**Comment by bramkragten** [comment]
Thanks for the issue,
This has been fixed!
