### ISSUE TITLE
entity filter developer-tools/state shows incorrect results

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#9282]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

entering a string in the entity filter column doesn't filter on that string (completely, or at all)

### Describe the behavior you expected

correct filtering

### Steps to reproduce the issue

1. enter sensor.astral (to find all sensors beginning with 'astral')
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.6

### What was the last working version of Home Assistant Core?

2021.5

### In which browser are you experiencing the issue with?

Any really, both desktop an handheld /all

### Which operating system are you using to run this browser?

Big sur 11.2.3 Safari 14.0.3 

### Javascript errors shown in your browser console/inspector

```txt
No errors
```

### Additional information

<img width="535" alt="Schermafbeelding 2021-05-28 om 11 08 03" src="https://user-images.githubusercontent.com/33354141/119960195-00459000-bfa5-11eb-8788-fa84025f3d65.png">

this is just an example, any string will show mixed results

**Comment by bramkragten** [comment]
As discussed on discord, this is not a bug, the filtering is correct as the letters you have entered are in the results in that order.

**Comment by Mariusthvdb** [comment]
ok, and since you've also announced you will remove this functionality (fuzzy search) and introduce wildcards (great!) this could be closed?
