### ISSUE TITLE
Devices and Entities not showing up since core-2021.6.0b0

### ISSUE THREAD

**Issue by joselito11** [home-assistant/frontend#9292]
### The problem

Under Settings - Devices and Settings - Entites, nothing shows up. This problem started with core-2021.6.0b0 and is also on core-2021.6.0b1. If I downgrade to 2015.5.5 then works. Have tried also with OS 5.13 and new OS 6 RC2 and RC3, problem persist with core-2021.6.0b0-1.
Have also deleted web browser cache and deleted companion app, but did not help.

Video:

https://user-images.githubusercontent.com/53316474/120076855-f35d9500-c0a7-11eb-8100-e677f94e726c.mp4

### What is version of Home Assistant Core has the issue?

core-2021.6.0b0 and core-2021.6.0b1

### What was the last working version of Home Assistant Core?

core-2021.5.5

### What type of installation are you running?

Home Assistant OS

**Comment by bramkragten** [comment]
Just on iOS devices?

**Comment by joselito11** [comment]
iOS devices and Debian 10, this is from Chrome browser on Debian:
![3706DD28-74ED-4FE6-8BD4-66FB93051845](https://user-images.githubusercontent.com/53316474/120084393-20be3900-c0d0-11eb-94c6-343ee0f499a1.jpeg)

**Comment by bramkragten** [comment]
That seems to be an error of `card-mod`.

**Comment by bramkragten** [comment]
And an error with the translation you use, does it work in another language?

**Comment by joselito11** [comment]
Have changed from Slovenian to English language and now works! Thank you!
