### ISSUE TITLE
Services developer tools tab does not support multiple instances

### ISSUE THREAD

**Issue by matejdro** [home-assistant/frontend#9315]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I open "Developer Tools" -> "Services" screen in multiple tabs, they all synchronise. I cannot, for example, open two services for controlling two different lights side by side because service from one will override another.

### Describe the behavior you expected

Services developer tool should behave independently in each tab, allowing for multiple independent editors

### Steps to reproduce the issue

1. Go to developer tools -> Services
2. Set service to "Turn on light"
3. Select any light entity
4. Duplicate tab
5. In the new tab, select different light
6. Go to the first tab

BUG: Selected light in the first tab has also changed to the selected light in the second tab

### What version of Home Assistant Core has the issue?

2021.5.5

### In which browser are you experiencing the issue with?

Firefox 88.0.1, Chrome 91.0.4472.77

### Which operating system are you using to run this browser?

Manjaro Linux

### Additional information

This behaviour makes it pretty annoying to test multiple services at once, or testing multiple configurations for different service (for example comparing the look of two rgb settings for a particular light).

I realise that this is likely linked to the persistence (Lovelace remembers the last used service until the next session). Maybe this behaviour could be updated in such a way that persistence is only loaded when user first opens the screen, but then it does not load/synchronize anymore, so user can use multiple instances of that screen.

**Comment by matejdro** [comment]
this is still an issue with frontend 20210809.0

**Comment by spacegaier** [comment]
I see the annoyance but not sure if that is really a bug and more specifically, what we could do to change that. If we remove the cookie info regarding which service was last selected in the dev tools, then it will always be empty when you go to that page. Not sure if that is really a benefit overall, compared to the scenario where you need two services, since there is a workaround for that:

Use multiple different browsers or private browsing mode since they will each have their own set of cookies then.

**Comment by bramkragten** [comment]
We could potentially make the listener for storage events optional on the `localStorage` decorator, then it will not sync, but only save the latest and load that on refresh.

**Comment by matejdro** [comment]
I don't think you should remove the cookie. What I do think you should do is disable real-time sync, but still load from storage when page is opened like @bramkragten mentioned.

**Comment by spacegaier** [comment]
Sounds like a good idea 👍. Best of both worlds basically then.

**Comment by matejdro** [comment]
Still happening with frontend 20211109.0

**Comment by matejdro** [comment]
It looks like this does not happen anymore in 20220301.0 :tada:
