### ISSUE TITLE
The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.

### ISSUE THREAD

**Issue by Delta1977** [home-assistant/frontend#9326]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Actual Chrome Browser Console:
The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.

Acording to https://github.com/lit/lit-element: 
LEGACY REPO. This repository is for maintenance of the legacy LitElement library. The LitElement base class is now part of the Lit library, which is developed in the lit monorepo.

### Describe the behavior you expected

Plans to migrate to a non Legacy Lit

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.6.0b4

### In which browser are you experiencing the issue with?

Google Chrome Version 91.0.4472.77

### Which operating system are you using to run this browser?

Win 10 21H1

### Javascript errors shown in your browser console/inspector

```txt
Example :
app.97c87fcc.js:13498 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.
55704 @ app.97c87fcc.js:13498
s @ app.97c87fcc.js:36065
53918 @ app.97c87fcc.js:7396
s @ app.97c87fcc.js:36065
(anonymous) @ app.97c87fcc.js:36065
(anonymous) @ app.97c87fcc.js:42177
(anonymous) @ app.97c87fcc.js:42177
VM983 entrypoint.e529ad28.js:formatted:41542 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.
5704 @ VM983 entrypoint.e529ad28.js:formatted:41542
s @ VM983 entrypoint.e529ad28.js:formatted:57130
4483 @ VM983 entrypoint.e529ad28.js:formatted:46483
s @ VM983 entrypoint.e529ad28.js:formatted:57130
1625 @ VM983 entrypoint.e529ad28.js:formatted:54431
s @ VM983 entrypoint.e529ad28.js:formatted:57130
7783 @ VM983 entrypoint.e529ad28.js:formatted:9513
s @ VM983 entrypoint.e529ad28.js:formatted:57130
(anonymous) @ VM983 entrypoint.e529ad28.js:formatted:57294
(anonymous) @ VM983 entrypoint.e529ad28.js:formatted:57296
entrypoint.e529ad28.js:48667 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.
5704 @ entrypoint.e529ad28.js:48667
s @ entrypoint.e529ad28.js:87320
4483 @ entrypoint.e529ad28.js:77331
s @ entrypoint.e529ad28.js:87320
1625 @ entrypoint.e529ad28.js:85526
s @ entrypoint.e529ad28.js:87320
7783 @ entrypoint.e529ad28.js:14237
s @ entrypoint.e529ad28.js:87320
(anonymous) @ entrypoint.e529ad28.js:87320
(anonymous) @ entrypoint.e529ad28.js:87320
```

**Comment by spacegaier** [comment]
I would guess that you are using custom cards that are using the legacy lit-element, because the HA frontend itself has already been upgraded.

**Comment by Delta1977** [comment]
ok. maybe it comes from HACS

**Comment by bramkragten** [comment]
We have some dependencies that are not updated yet
