### ISSUE TITLE
Frontend "Translation Error"

### ISSUE THREAD

**Issue by martymarty004** [home-assistant/frontend#9330]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the integration page, if I show _disabled integrations_, the Samsung TV integration status contains the following error. The system language is Italian. The error remains after HA restart.

### Describe the behavior you expected

It should show the correct status.

### Steps to reproduce the issue

1. Go to integrations page
2. Disable Samsung TV integration
3. Show disabled integrations
...

### What version of Home Assistant Core has the issue?

2021.5.5

### What was the last working version of Home Assistant Core?

N/A

### In which browser are you experiencing the issue with?

Edge 91.0.864.37, Safari, iOS Companion App

### Which operating system are you using to run this browser?

Windows 10 21H1, iOS 14.6

### State of relevant entities

```txt
N/A (entity is disabled)
```

### Problem-relevant frontend configuration

```yaml
N/A
```

### Javascript errors shown in your browser console/inspector

```txt
Translation Error: The intl string context variable "causa" was not provided to the string "Disabilitato da {causa}"
```

### Additional information

Full text:
Translation Error: The intl string context variable "causa" was not provided to the string "Disabilitato da {causa}"
Riavvia Home Assistant per terminare la disabilitazione di questa integrazione

**Comment by bramkragten** [comment]
Translations are community maintained, you can fix this yourself: https://developers.home-assistant.io/docs/translations
