### ISSUE TITLE
Rename Available Events in Developer Tools > Events to something more descriptive.

### ISSUE THREAD

**Issue by nlighteneddesign** [home-assistant/frontend#9336]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The section on the left is called Available events lending the impression it is a list of events you can listen to rather than the actual function which is a list of events something is currently listening to.

This can cause confusion if an event type changes and you look there to see what types of events are available.

I would suggest something with a short explanation such as:
Current Events
These are events services are currently listening for. This is not a list of available events.

### Describe the behavior you expected

The header should describe the contents of the list below.

### Steps to reproduce the issue

1. Click Developer tools
2. Click Events
3. Look on the right
...

### What version of Home Assistant Core has the issue?

 2021.5.5

### In which browser are you experiencing the issue with?

Firefox

### Which operating system are you using to run this browser?

Ubuntu 20.014

**Comment by spacegaier** [comment]
I think "Current Events" is also a bit misleading, because there are more events that can be raised and listened to. Perhaps something like "Current Listeners" would be clearer?

Or perhaps it might make sense to actually list all events that can be raised (even if no listener is currently active). The current list is provided by the backend, not sure on what basis (probably the listener count > 0).

**Comment by nlighteneddesign** [comment]
I think that makes sense. Current listeners is probably better.

Maybe a little info tool tip that says that just cause something is in the list doesn't mean it actually exists?

The reason I ask is the main reason I would see the list is when a listener broke (zwave_js_events in my case) And seeing it in that list makes me think it's the right event to listen to, rather than the event that I am currently listening for.
