### ISSUE TITLE
Browser compatibility issue - stuck at "Initializing"

### ISSUE THREAD

**Issue by ha0y** [home-assistant/frontend#9344]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Starting from release 20210518.0 , the logging in page fails to load. It stucks at `Initializing`.

The last working version is 20210517.0

Browser: Chrome 70.0.3538.110

### Describe the behavior you expected

Show the logging in page correctly

### Steps to reproduce the issue

1. Use core 2021.6.0 with frontend 20210517.0
2. It works well ![222](https://user-images.githubusercontent.com/30557072/120616470-d8b26400-c48b-11eb-8e5f-66e703acabc0.PNG)
3. Upgrade frontend to 20210518.0 or newer
4. The logging in page fails to load ![111](https://user-images.githubusercontent.com/30557072/120616452-d3551980-c48b-11eb-89f9-b2615dc4dde8.PNG)

### What version of Home Assistant Core has the issue?

2021.6.0

### What was the last working version of Home Assistant Core?

2021.6.0 (By downgrading frontend only)

### In which browser are you experiencing the issue with?

Google Chrome 70.0.3538.110

### Which operating system are you using to run this browser?

Windows 10

### Javascript errors shown in your browser console/inspector

```txt
Uncaught (in promise) ReferenceError: globalThis is not defined
    at Object.25945 (authorize.27b71aa1.js:1)
    at a (authorize.27b71aa1.js:51327)
    at Object.50424 (authorize.27b71aa1.js:10552)
    at a (authorize.27b71aa1.js:51327)
    at Object.6610 (authorize.27b71aa1.js:30037)
    at a (authorize.27b71aa1.js:51327)
    at authorize.27b71aa1.js:51327
    at authorize.27b71aa1.js:51327
25945 @ authorize.27b71aa1.js:1
a @ authorize.27b71aa1.js:51327
50424 @ authorize.27b71aa1.js:10552
a @ authorize.27b71aa1.js:51327
6610 @ authorize.27b71aa1.js:30037
a @ authorize.27b71aa1.js:51327
(anonymous) @ authorize.27b71aa1.js:51327
(anonymous) @ authorize.27b71aa1.js:51327
```

**Comment by spacegaier** [comment]
Does the same happen in a private browser mode window? 

Looking at the error I would say that this is not a HA issue, since we have no `globalThis` in the code. The custom `vacuum-card` however for example does, so that might be where the error is coming from. Do you have that installed in your instance?

**Comment by ha0y** [comment]
> Does the same happen in a private browser mode window?
> 
> Looking at the error I would say that this is not a HA issue, since we have no `globalThis` in the code. The custom `vacuum-card` however for example does, so that might be where the error is coming from. Do you have that installed in your instance?

Yes, it happens in both mode. And I didn't install it in my instance.
It happens only with Chrome 70 + frontend 20210518.0 or newer. Not with other browsers, and not with older frontend versions.

**Comment by bramkragten** [comment]
WHy are you using such an old version of Chrome?

**Comment by ha0y** [comment]
For some user experience reasons. However this not only affects a single device, I found that my old Android phones and tablets also cannot access my hass instance as their stock webview also fails to load the logging in page. Perhaps it is too early to drop support for them?
