### ISSUE TITLE
Light color representation with low brightness is misleading

### ISSUE THREAD

**Issue by EricReiche** [home-assistant/frontend#9356]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi,
the recent change to how colors are handled leads to some weird behavior.
If I set my KNX RGBW LED stripe to red with low brightness, the icon appears black. 
![image](https://user-images.githubusercontent.com/894987/120691541-e4f7ea80-c4a6-11eb-9f28-7d541ed917de.png)

### Describe the behavior you expected

I expect the icon to represent the color of the light, even if the brightness is low. The aactual LED stripe is glowing red, not "black".

### Steps to reproduce the issue

1. Set red color to RGBW light
2. Set brightness to 23%

### What version of Home Assistant Core has the issue?

2021.6.0

### What was the last working version of Home Assistant Core?

2021.5.6

### In which browser are you experiencing the issue with?

Chrome 91.0.4472.77 

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
supported_color_modes:
  - rgbw
color_mode: rgbw
brightness: 23
hs_color:
  - 15.652
  - 100
rgb_color:
  - 23
  - 6
  - 0
rgbw_color:
  - 23
  - 6
  - 0
  - 0
xy_color:
  - 0.612
  - 0.374
friendly_name: O5 Leif Stripes
supported_features: 0
```

### Problem-relevant frontend configuration

```yaml
entities:
  - entity: light.o5_leif_stripes
title: OG
type: entities
state_color: true
```

**Comment by farmio** [comment]
I wonder if this has the same behavior with https://github.com/home-assistant/core/pull/51060 as the returned color is maxed there.

**Comment by bramkragten** [comment]
That light is not at brightness 23% or the integration is wrong. It is way lower, as both the color brightness and overall brightness are 23% meaning the brightness is 23% of 23% = 5% that is nearly off...

The UI will never be able to truly represent the color of a light though

**Comment by farmio** [comment]
Yes, the integration is kind of wrong. It doesn't support dedicated brightness but only brightness encoded in the color values. This is something HA color modes can not handle very well (or I fail to implement it correctly ¯\_(ツ)_/¯ )

**Comment by farmio** [comment]
You can try to run this draft: https://github.com/home-assistant/core/pull/51060 maybe it works better. 
I have no colored lights to test it and have found nobody else to do yet.
