### ISSUE TITLE
Cannot click on dropdown list of entity_id etc... using google-chrome on linux

### ISSUE THREAD

**Issue by foxsam21** [home-assistant/frontend#9360]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I edit the UI using the gui editor and start typing an enity_id the list gets filtered and works as expected. However if I want to select a specific entity_id I need to use the keyboard (either type the rest of the entity_id or select with the arrow keys) but I cannot click on an entry using the mouse it just escapes out of the selection and I need to start over.
A similar issue is in selecting an are for a new device, the UI just ignores the mouse selection and exits out of that menu.

I tried using another browser on linux and it worked as expected. I also tried chrome on windows and it also went as expected.

### Describe the behavior you expected

I expect that when I use the mouse to select an entity_id the entry under my pointer should be highlighted and if I click at that point it should select the highlighted entry.

### Steps to reproduce the issue

1. Edit UI
2. add new entities card
3. change an entity to a new entity_id using your mouse
...

### What version of Home Assistant Core has the issue?

core-2021.6.0

### In which browser are you experiencing the issue with?

Google Chrome Version 89.0.4389.114 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Linux Mint 19.3 Tricia

**Comment by ludeeus** [comment]
I'm not able to replicate this with chrome running on Ubuntu, my version is 90.X
See if upgrading chrome solves it

**Comment by jesserockz** [comment]
I have this issue on Chrome 90.0.4430.212 on Arch Linux

**Comment by tannisroot** [comment]
Same issue with Chrome (google-chrome 91.0.4472.101-1 from AUR) on Arch Linux.

**Comment by malteger** [comment]
Same issue with chromium 91.0.4472.114 on Arch Linux in combination with HomeAssistant Core version 2021.6.5

**Comment by tannisroot** [comment]
I've managed to fix the issue by deleting my old profile (google-chrome or chromium folders in .cache and .local/share) and creating a new one.

**Comment by shbatm** [comment]
Having the same issue on Chrome on Windows 10.  Chrome: Version 92.0.4515.107 (Official Build) (64-bit), last 2 versions of HA (June, July, and August Beta)

**Comment by glmnet** [comment]
Me too ™

Also want to add that on iOS HA Companion app the kind of same thing happens, you type a few letters then touch over the selection and the drop down goes away and no selection is made. (I assume this uses safari behind the scenes, not sure)

**Comment by Lafunamor** [comment]
This is still an issue for me.
Home Assistant 2021.12.10
Chrome Version 97.0.4692.99 (64-Bit)

**Comment by jesserockz** [comment]
Still also an issue for me on Arch Linux with i3-gnome
Home Assistant 2022.2.0b3
Chrome Version 97.0.4692.99 (Official Build) (64-bit)

**Comment by shbatm** [comment]
Deleting the Chrome profile worked for me.

**Comment by Lafunamor** [comment]
This is still happening on HA 2022.5.2 with Chrome 101.0.4951.54
