### ISSUE TITLE
Lovelace is stuck at initializing

### ISSUE THREAD

**Issue by ragaimeena** [home-assistant/frontend#9367]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Lovelace is stuck at initializing
Browser: fully kiosk on fire HD tablet
behavior occurred after most recent update.

### Describe the behavior you expected

loveloace to load with login page

### Steps to reproduce the issue

1.download fully kiosk on fire tablet
2.set the url to the lovelace dashboard

.

### What version of Home Assistant Core has the issue?

core-2021.6.1

### What was the last working version of Home Assistant Core?

core-2021.5.x

### In which browser are you experiencing the issue with?

fully kiosk 

### Which operating system are you using to run this browser?

fireOS

### State of relevant entities

```txt
as above
```

### Problem-relevant frontend configuration

```yaml
same
```

### Javascript errors shown in your browser console/inspector

```txt
same
```

### Additional information

none

**Comment by bramkragten** [comment]
> 1.download fully kiosk on fire tablet

That will be an issue... I don't have a fire tablet...
