### ISSUE TITLE
can't navigate away from Supervisor/Add-ons on Mobile 

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#9370]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

on a iPhone Safari browser window there's no way I can navigate away from the Installed add-ons. It doesn't show the hamburger menu and an unusual 'Installed add-ons' where other browsers show the Hamburger and 'Add-ons' below that

![20210604_182747000_iOS](https://user-images.githubusercontent.com/33354141/120866640-b0605d80-c590-11eb-8a48-62773f85242e.png)

### Describe the behavior you expected

![20210604_215812000_iOS](https://user-images.githubusercontent.com/33354141/120866707-c79f4b00-c590-11eb-80e0-b480e6d29b79.png)

### Steps to reproduce the issue

1. open safari browser to the instance 
2. navigate Supervisor
3. cant go back.....
...

### What version of Home Assistant Core has the issue?

2021.6.1

### In which browser are you experiencing the issue with?

Safari mobile

### State of relevant entities

```txt
not relevant
```

### Problem-relevant frontend configuration

```yaml
no sure what to post
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/120889517-d4a65380-c5fd-11eb-8ec1-a80fcc2f1ced.png)
unable to replicate, try pulling the window down to refresh

**Comment by Mariusthvdb** [comment]
Yeah, its really odd. I've just updated to  2021.6.2 and the first loading of that page seems alright, showing the hamburger. revisiting it after that results in:


https://user-images.githubusercontent.com/33354141/120892941-df1e1880-c610-11eb-8382-8bc91d3ef638.mp4





Also, is it correct there's 2 different title formats for the same page? 'Installed Add-ons'  versus 'Add-ons' ?

**Comment by ludeeus** [comment]
you are just scrolling the content, you need to scroll the page

**Comment by Mariusthvdb** [comment]
That's because the normal view

![image](https://user-images.githubusercontent.com/33354141/120897522-ec460200-c626-11eb-8ad9-231913c8a93f.jpeg)

Regularly is  hidden ![image](https://user-images.githubusercontent.com/33354141/120897524-f536d380-c626-11eb-87ce-94c34f7bf017.jpeg)

And practically out of reach/touch.

Perhaps the title of the issue should be changed to 'supervisor header hides behind window top bar' ....

I now can confirm to just be able to touch that thin line and pull it down.
