### ISSUE TITLE
Logbook puts date header in front of every record which is from yesterday

### ISSUE THREAD

**Issue by KennethLavrsen** [home-assistant/frontend#9371]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When you view the logbook not too long after midnight you get records listed from today followed by records from yesterday All the records from yesterday get a date header for each record

![logbookdataheader](https://user-images.githubusercontent.com/8373419/120882959-ee826f00-c5da-11eb-9b6b-025cfaf1e59c.png)

The date header is supposed to appear only before the first record of that day (that is how it worked in 2021.5.5)

### Describe the behavior you expected

The date header should appear before the first record. And then again every time the date changes - once

### Steps to reproduce the issue

1. You need some records recorded before and after midnight
2. You need to be able to see records from both today and from just before midnight. E.g. test this past midnight or if you value your night sleep test with a timezone that fits the purpose
3. You should see the view from image above
...

### What version of Home Assistant Core has the issue?

core-2021.6.2

### What was the last working version of Home Assistant Core?

core-2021.5.5

### In which browser are you experiencing the issue with?

Chrome and IOS Safari

### Which operating system are you using to run this browser?

Ubuntu-20.04, Windows 10, IOS latest

**Comment by spacegaier** [comment]
I can reproduce that issue. Initial look at the code:

In `private _renderLogbookItem()` we always get the same index == 0 and therefore `previous` remains always undefined.

**Comment by ZuluWhiskey** [comment]
Same issue for me on 2021.8.0 on HA Container
![image](https://user-images.githubusercontent.com/35011199/128319636-a3cf2e31-b3ee-46ad-8cdc-d23886941e57.png)

**Comment by KennethLavrsen** [comment]
Pinging bot

**Comment by KennethLavrsen** [comment]
Pinging bot

**Comment by KennethLavrsen** [comment]
I think this has been fixed. At least now that I check at 0:44 at night
