### ISSUE TITLE
Snapshots can't be downloaded in iOS

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/frontend#9374]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Snapshots cannot be downloaded in iOS (app or browsers). Tapping the download link results in nothing happening. Snapshot uploads appear to be available 

### Describe the behavior you expected

File download prompt to appear

### Steps to reproduce the issue

1. Open instance in any iOS browser
2. Navigate to a snapshot in supervisor
3. Attempt to download

### What version of Home Assistant Core has the issue?

core-2021.6.2

### In which browser are you experiencing the issue with?

iOS Safari

### Which operating system are you using to run this browser?

iOS 14.6

**Comment by dshokouhi** [comment]
You know we had a request to support downloading in the Android app I couldn't get the code to work. I wonder if this was the reason? Never troubleshooted long enough to tell what was actually going on. Will have to recheck once this is solved.

**Comment by ludeeus** [comment]
My PR includes a fix for Android as well @dshokouhi
