### ISSUE TITLE
Time format 24h shows 00:15 as 24:15 in Google Chrome

### ISSUE THREAD

**Issue by tangix** [home-assistant/frontend#9379]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When selecting 24h time format in my profile, times occurring in the first hour of the day (00:00 - 00:59) shows up as 24:xx in Google Chrome. 
Example, this automation ran June 6 at 00:15. 
In Chrome:
<img width="687" alt="2021-06-06_07-44-13" src="https://user-images.githubusercontent.com/1013635/120914003-6fa13b00-c69b-11eb-856e-b9aba07b0ed4.png">
In Safari:
<img width="888" alt="2021-06-06_07-51-34" src="https://user-images.githubusercontent.com/1013635/120914092-079f2480-c69c-11eb-884c-1c3d53b4ccc9.png">

### Describe the behavior you expected

Should show a one would expect, 00:15 in all browsers.

### Steps to reproduce the issue

1. Open profile and set time format to 24h
2. Check automations that have been running the first hour of the day

### What version of Home Assistant Core has the issue?

core-2021.6.2

### In which browser are you experiencing the issue with?

Google Chrome 91.0.4472.77

### Which operating system are you using to run this browser?

macOS Catalina 10.15.7 (19H1217)

**Comment by spacegaier** [comment]
Does it only happen in that view? Did you check e.g. the logbook entries for entities that are changed by that automation run?

Please fill out the automation entity state in the issue template.

**Comment by spacegaier** [comment]
I also cannot reproduce the issue on Win 10 + FF or Chrome.
![image](https://user-images.githubusercontent.com/114137/120916725-7768db80-c6ab-11eb-9b49-59e8cfa08948.png)

**Comment by tangix** [comment]
> Does it only happen in that view? Did you check e.g. the logbook entries for entities that are changed by that automation run?

<img width="762" alt="2021-06-06_10-12-43" src="https://user-images.githubusercontent.com/1013635/120917466-c4e74780-c6af-11eb-9a84-f28a0965cd31.png">

> Which language is your frontend set to?
English

> And did you test it in private browsing mode of Chrome to rule out any caching issues?
Yes

**Comment by tangix** [comment]
> I also cannot reproduce the issue on Win 10 + FF or Chrome.

For me it works in Safari on mac

**Comment by tangix** [comment]
Maybe related? 
https://github.com/moment/luxon/issues/726

**Comment by tangix** [comment]
Don't know how you format the date, but this snippet produces different results in Chrome and Edge versus Safari and FF
```const formatOptions = { hour: 'numeric', minute: 'numeric', hour12: false };
const valueToFormat = Date.parse('2020-01-01T00:15:00');
const dateTimeFormat = new Intl.DateTimeFormat('en-US', formatOptions);
console.log(dateTimeFormat.format(valueToFormat));
```

24:15 on Chromium-based browsers and 00:15 on other.

**Comment by bigboban** [comment]
Same observation. See my report here: https://github.com/home-assistant/core/issues/51974.

**Comment by ripvega** [comment]
I am experiencing the same [issue with HA](https://community.home-assistant.io/t/what-time-is-2431-and-where-is-it-coming-from/341877?u=ashscott).
[](url)

Please see the image in the link above.

Using Chrome on Mac.

**Comment by bangan1910** [comment]
So this is a Chrome issue? Can someone point me in the direction of a solution for this? 
Will it get a workaround from HA? The Chrome thread was closed. Something i can change in my end?

**Comment by gigawatts** [comment]
No idea if this is related, but the "Files" app in Google Chrome OS has the exact same problem, I've been trying to get Google's attention on this bug for the better part of a year.

https://issuetracker.google.com/issues/203123037
