### ISSUE TITLE
purge_entities call service misinformation

### ISSUE THREAD

**Issue by drthanwho** [home-assistant/frontend#9382]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The new call service entities by default in yaml mode doesn't not mention anywhere the need for `target` which seems to be mandatory for the call service to work. For example if you want to delete several sensors using globs or a whole domain you cannot proceed without specifying a target. 

This is what it shows by default once selected (no mention of target)
![image](https://user-images.githubusercontent.com/22405505/120922312-b3f70000-c6c8-11eb-915d-b14b12df588b.png)
Also even if choosing `fill example data` also no target and cannot be called
![image](https://user-images.githubusercontent.com/22405505/120922317-bbb6a480-c6c8-11eb-83eb-ca5d10d15af2.png)

### Describe the behavior you expected

I would expect the service to work by choosing whether you want to delete one entity, multiple using globs or a whole domain. Instead you are forced to pick some random entity you don't care about just so the call service is considered valid

this is a valid call service 
```yaml
service: recorder.purge_entities
data:
  entity_globs: sensor.uptime*
target:
  entity_id: sensor.uptime_pir_lounge
```
However I would expect it to work without needing the extra target argument and that target is mentioned as a requirement which is not. You can only see it's needed if you try through UI mode, in which case you still need to pick an entity and cannot just pick one of the other options
![image](https://user-images.githubusercontent.com/22405505/120925061-02ab9680-c6d7-11eb-8e36-749c7adcfaab.png)
![image](https://user-images.githubusercontent.com/22405505/120925075-11924900-c6d7-11eb-994f-caf45cb44620.png)

### Steps to reproduce the issue

1. Pick call service `recorder.purge_entities`
2. specify an entity glob or a domain
3. Unable to proceed with calling the service (in UI mode you do see TARGETS and in Yaml mode you see no mention of targets although even in UI mode you should be able to choose a glob only)
...

### What version of Home Assistant Core has the issue?

core-2021.6.2

### What was the last working version of Home Assistant Core?

N/A

### In which browser are you experiencing the issue with?

Google Chrome 91.0.4472.77

### Which operating system are you using to run this browser?

Windows 10

### Additional information

The documentation should be modified accordingly depending on the fate of this issue for the use of  `target`😆

**Comment by PeteBa** [comment]
@drthanwho , you are correct, the UI requires the Target parameter to be provided but the "purge_entities" service call does not. The service call will work with any or all of the parameters provided (entities, domains, globs).

This isn't specific to the `purge_entities` service call but rather a requirement of the UI. I raised this in Discord awhile back but didn't get traction for making target optional. Maybe this will spark a conversation.

**Comment by spacegaier** [comment]
> 
> 
> Maybe this will spark a conversation.

Yes, I had had some weeks ago triggered a discussion with @frenck but with no real conclusion. He is currently on vacation and I want his okay, before copying the chat in here.

**Comment by PeteBa** [comment]
One thought I had was for a "multiple" attribute on the target pickers like the standard html select element. Is that an available attribute ?

This would pretty much eliminate the need for a domain and glob option. For example, the entity picker already supports filtering so entering "binary_sensor" presents that domain and entering "fred" will bring up all entities with fred in the name.  We are just missing the shift-click to select the required ones or maybe a "Select All" button.

Even though this wouldnt provide full glob pattern matching, it would provide a familiar UI solution and address, I suspect, the majority of use-cases.

**Comment by gigatexel** [comment]
I'm experiencing the same issue.
It's very odd that even example data does not render a valid service call. This is front-end error I think.
The docs (https://www.home-assistant.io/integrations/recorder/) specify that all three options are optional in the purge_entities service call!

**Comment by PeteBa** [comment]
@gigatexel  I have submitted a documentation PR to hopefully clarify the situation.

The three parameters are optional in the underlying service call when used from within `automations.yaml` or `scripts.yaml`. However, when using the UI in Developer Tools then selecting an entity is mandatory. This is because I chose to use the Target Picker selector which is more feature rich than the Entity Picker. The Target Picker lets you select multiple entities, select entities based on area or entities based on device. However, it does comes with the downside of being mandatory.

Obviously, you can work around the mandatory limitation of Target Picker by specifying an entity that would also be captured by the domain/glob. But I would also be happy to convert the service to use the Entity Picker as that supports the "optional" flag but is limited to selecting a single entity. Appreciate any thoughts.

**Comment by gigatexel** [comment]
@PeteBa thank you for your clarification. The workaround you suggest is in fact the way I use it now.
Some thoughts from my side:

- It's quite confusing for end-users when services behave differently or have different requirements based on where they are called from
- The purge_entities, to me, is a service that is typically called from the UI and not from automations or scripts. I use it to clean up the DB, for example, when entities no longer exist.
