### ISSUE TITLE
Transparent Color for sidebar-background-color not working since HA 2021.6

### ISSUE THREAD

**Issue by FaserF** [home-assistant/frontend#9384]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since HA Version 2021.6 (with frontend 20210603.0) I am unable to use my transparent theme witht he sidebar anymore. The transparent color just gets a strange white color.
The Theme is working fine with alle elements, except sidebar-background-color . Using a color without transparancy is working fine. 
My theme is here: https://github.com/FaserF/transparentgray/blob/ba23c0e0c08e6287e62cbfaabb1f4b68a90640d7/themes/transparentgray.yaml#L56

### Describe the behavior you expected

The transparency should still be working with the sidebar.

### Steps to reproduce the issue

1. Install my Theme (with the state from the commit ba23c0e0c08e6287e62cbfaabb1f4b68a90640d7 or in Version Version 2021-01-23)
2. Set the theme
3. See the white-ish color

### What version of Home Assistant Core has the issue?

2021.6.2

### What was the last working version of Home Assistant Core?

2021.5.X

### In which browser are you experiencing the issue with?

Google Chrome 91.0.4472.77 / Safari from iOS 14.6 / Homeassistant App

### Which operating system are you using to run this browser?

Windows 10 - 21H1 / iOS 14.6 / Homeassistant App

### Problem-relevant frontend configuration

```yaml
https://github.com/FaserF/transparentgray/blob/ba23c0e0c08e6287e62cbfaabb1f4b68a90640d7/themes/transparentgray.yaml#L56
```

**Comment by bramkragten** [comment]
A screenshot would help here.

**Comment by FaserF** [comment]
Hmmm isn’t solved yet, but I understand that it doesn’t have a high priority

**Comment by FaserF** [comment]
Just tested it with 2021.11.5 again.
Still its not working when trying to use some transparency

`sidebar-background-color: 'rgba(24,24,24,0.3)' `

**Comment by spacegaier** [comment]
But the header transparency still works in 2021.11.x for you?

**Comment by FaserF** [comment]
Yeah the rest works fine without any issues.

**Comment by FaserF** [comment]
Issue is still there, but I understand its low priority.

**Comment by FaserF** [comment]
Issue is still there, but I understand its low priority.

**Comment by FaserF** [comment]
Issue is still there, but I understand its low priority.

**Comment by FaserF** [comment]
Issue is still there, but I understand its low priority.

**Comment by FaserF** [comment]
Still there

**Comment by FaserF** [comment]
Issue is still there, but I understand its low priority.
