### ISSUE TITLE
IHC integration - temperature sensor resolution

### ISSUE THREAD

**Issue by Christiansborg** [home-assistant/frontend#9391]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

An IHC temperature sensor reading is displayed with 13 digits after the decimal point in lovelace. 

### Describe the behavior you expected

A resolution of 1 digit after the decimal point.

### Steps to reproduce the issue

1. integrate an IHC temperature sensor (507 D 6531)
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.6.0

**Comment by spacegaier** [comment]
The precision is controlled by the backend, so your integration. If you want different values / precision (and your integration does not offer an parameter to control it), you have two options:

1. Create a PR or FR to add precision to the integration.
2. Create a template entity in your HA instance and round the value there as desired.
