### ISSUE TITLE
Dark, light, and auto options missing for default theme or other themes with dark and light options

### ISSUE THREAD

**Issue by gadgetchnnel** [home-assistant/frontend#9392]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After updating to 2021.6.3, the dark, light, and auto options for the default theme or any other theme with dark and light modes are missing (see first screenshot). Rolling back to 2021.6.0, the options reappeared (second screenshot)

### Describe the behavior you expected

The dark, light, and auto options should show for the theme.

### Steps to reproduce the issue

1. Go to Profile page
2. Select default theme or another theme which has dark and light modes

### What version of Home Assistant Core has the issue?

2021.6.3

### What was the last working version of Home Assistant Core?

2021.6.0

### In which browser are you experiencing the issue with?

Google Chrome 91.0.4472.77 

### Which operating system are you using to run this browser?

macOS Catalina 10.15.7

### Additional information

Screenshot after updating to 2021.6.3

![image](https://user-images.githubusercontent.com/2099542/121184860-695abc80-c85d-11eb-8d8d-57761973a404.png)

Screenshot after rolling back to 2021.6.0

![image](https://user-images.githubusercontent.com/2099542/121184977-842d3100-c85d-11eb-941e-aa48eb8c4180.png)

**Comment by spacegaier** [comment]
I cannot reproduce the issue. Works fine for me in production and dev.

**Comment by gadgetchnnel** [comment]
@spacegaier 
I just reset my themes by:
* Removing themes from configuration.yaml
* Reloading themes
* Adding them back
* Reloading themes again

and the problem disappeared. I then called:

```
service: frontend.set_theme
data:
  name: light
```
(where light is one of my custom themes)
and the issue returned.

Calling

```
service: frontend.set_theme
data:
  name: default
```
resolved it again.

So, it looks like this is only happening if there is a backend selected theme, other than "default".

**Comment by spacegaier** [comment]
Okay, that is a known issues that is already fixed in dev, but is not yet part of a HA release: https://github.com/home-assistant/frontend/pull/9357

**Comment by gadgetchnnel** [comment]
@spacegaier Sorry, I was just checking this and wanted to check if that is the correct PR that you linked to there.

That PR appears that it was part of the frontend release [20210603.0](https://github.com/home-assistant/frontend/releases/tag/20210603.0) which was referenced in the core release [2021.6.1](https://github.com/home-assistant/core/releases/tag/2021.6.1)

I only started seeing this issue when updating from 2021.6.0 to 2021.6.3

I'm still seeing this now - basically, if the backend selected theme supports light and dark mode all themes show the selectors and if it doesn't none of them do.
