### ISSUE TITLE
battery percentage scrambled in device panel on ZwaveJS integration

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#9397]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

battery state, percentage and icon are scrambled

### Describe the behavior you expected

nicely positioned

### Steps to reproduce the issue

1. configuration/integrations/Zwavejs devices
2. click battery powered device
3.
...

### What version of Home Assistant Core has the issue?

2021.6.3

### What was the last working version of Home Assistant Core?

Dk

### In which browser are you experiencing the issue with?

Safari (sorry)  desktop. Resizing window doesn't make a difference. Mobile shows fine

### Which operating system are you using to run this browser?

Big sur 11.2.3 Safari 14.0.3 

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

<img width="1057" alt="Schermafbeelding 2021-06-09 om 14 04 41" src="https://user-images.githubusercontent.com/33354141/121351488-1e5baa80-c92c-11eb-8a8c-9594302076ed.png">

**Comment by spacegaier** [comment]
Is this a Safari only issue and works fine e.g. in Chrome?

**Comment by Mariusthvdb** [comment]
yes only Safari (also tested Firefox, which is ok), and still happening in 2021.9 OS 6.3
