### ISSUE TITLE
Entities takes 3 rows on entities card

### ISSUE THREAD

**Issue by Youpimatin** [home-assistant/frontend#9400]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

OK Before (core-2021.5.0)
![OK](https://user-images.githubusercontent.com/55438591/121495545-fe82c000-c9d9-11eb-99ae-c19059d3911d.png)

BUG after updating to core-2021.6.3
![BUG](https://user-images.githubusercontent.com/55438591/121495572-03e00a80-c9da-11eb-91cb-ce968af23351.png)

### Describe the behavior you expected

...

### Steps to reproduce the issue

nothing to reproduce, just view

### What version of Home Assistant Core has the issue?

core-2021.6.3

### What was the last working version of Home Assistant Core?

core-2021.5.0

### In which browser are you experiencing the issue with?

Firefox 89, Firefox 84, Huawei Honor... 

### Which operating system are you using to run this browser?

Windows 7, 8, android

**Comment by spacegaier** [comment]
That is related to an issue in a custom card, not HA itself. See the discussion of the release notes. Has been discussed there multiple times: https://community.home-assistant.io/t/2021-6-a-little-bit-of-everything

**Comment by Youpimatin** [comment]
Thank you, but this is NOT a custom card, it's a standard "ENTITIES" card...

I Add :
Sometimes it works, sometimes not.

If I log into lovelace with the complete URL of the page it works.... if I switch to another view it doesn't.

Example when I log into this specific page :
![OK2](https://user-images.githubusercontent.com/55438591/121509579-144ab200-c9e7-11eb-84d2-2612c2f1808b.png)

If I log into another page, and I switch to this page : 
![BUG2](https://user-images.githubusercontent.com/55438591/121509638-23c9fb00-c9e7-11eb-8864-2b1101620dfb.png)

**Comment by bramkragten** [comment]
Yes, the custom cards changes the styling of the build-in card (something it ofc should not do :-) )

**Comment by Youpimatin** [comment]
OK, replaced template-entity-row.js and restarted the server,
seems to have resolved my problem !

Thank you !

(The new version of the custom card is better, still I wait the day when I won't need it no more... ofcc.. "ow f* custom card")

maybe one day ... #7391
