### ISSUE TITLE
Utility meter - atribute last_reset not showing at sensor atributes

### ISSUE THREAD

**Issue by lopitos1joao** [home-assistant/frontend#9403]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since last update (2021.6.1) the atribute `last_reset` disappear from the atributes area of an utility meter sensor.
In the Developer Tools the value is correct.
Some screenshots below.

### Describe the behavior you expected

In utility meter, the atribute `last_reset` should be visible at sensor overview like in older versions of Home Assistant.

 

### Steps to reproduce the issue

1. Check an utility meter sensor like this screenshot at developer tools (last_reset atribute is correct):

![developer_tools](https://user-images.githubusercontent.com/60098253/121576033-e9308480-ca1f-11eb-8d4d-5e58ced6714f.jpg)

2. At the sensor atributes last_reset is not showed: 

![sensor](https://user-images.githubusercontent.com/60098253/121576282-2137c780-ca20-11eb-8ad5-84ce072aa33b.jpg)

3.
...

### What version of Home Assistant Core has the issue?

2021.6.3

### What was the last working version of Home Assistant Core?

2021.6.X

### In which browser are you experiencing the issue with?

Google Chrome

### Which operating system are you using to run this browser?

Windows

**Comment by lopitos1joao** [comment]
That info was very useful for rapid troubleshooting. We still have last period (very useful) and last_reset is way more important for monthly and yearly utility meter values. 
For example I use that to compare values of energy consumption with my provider. That way I can simulate future provider changes based on my consumption. 
Now, not having that info at front end, I must go to developer tools. 

Any chance of reconsider have it back again?

**Comment by frenck** [comment]
> Any chance of reconsider have it back again?

That would enable it for all sensors, which is a lot. So I guess not. It is now a similar thing to `last_changed` or `last_updated` attributes.

**Comment by lopitos1joao** [comment]
Ok. 

An idea (maybe very stupid/or not): at atributes, have a link for administrators only for developer tools with that sensor selected. 
If not a good idea please close this immediately.

Thanks for your fast reply.

**Comment by spacegaier** [comment]
One potential option: Show the `last_Reset` value (if not initial) in the tooltip where we show `last_changed` and `last_updated`.
