### ISSUE TITLE
Android throws error with 20210518.0 (but is ok with 20210517.0)

### ISSUE THREAD

**Issue by gdt** [home-assistant/frontend#9404]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Home Assistant Companion (Android) errors with newer frontend versions.   With 20210517.0 (and 20210504.0, which I think was bundled with Core 2021.5.x), everything works fine, as it has for months.  With 20210518.0 (and 0603.0, bundled with 2021.6.3, where I first noticed), I get a webview error:

2021-06-10 16:03:10.684 2750-2750/io.homeassistant.companion.android.minimal I/chromium: [INFO:CONSOLE(849)] "The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.", source: https://foo.example.com:8123/frontend_latest/app.bcb38ac1.js (849)
2021-06-10 16:03:10.728 2750-2750/io.homeassistant.companion.android.minimal I/chromium: [INFO:CONSOLE(2)] "Uncaught (in promise) TypeError: e.flat is not a function", source: https:/foo.example.com:8123/frontend_latest/app.bcb38ac1.js (2)

and the app reports "can't connect".   Changing to 20210517.0 and restarting results in the normal display.

### Describe the behavior you expected

I expect webview to be able to render the display normally, even if the webview is old.

### Steps to reproduce the issue

Lineage 15.1 (AOSP 8.1).  Yes, that's old.
Home Assistant Companion 2021.5.1-minimal from f-droid

### What version of Home Assistant Core has the issue?

2021.6.3, but see above bisection results on frontend

### What was the last working version of Home Assistant Core?

2021.5.?

### In which browser are you experiencing the issue with?

webview within android app, and also fails with "Browser" (chrome-ish) from lineage.

### Which operating system are you using to run this browser?

Lineage 15.1

### Javascript errors shown in your browser console/inspector

```txt
I don't have access to that in the app, but I pasted the adb logcat output above.
```

### Additional information

I realize this is probably a case of "old webview has bugs", but given the number of people  out there with older phones, it seems that it would be really nice for the frontend to avoid them.   Sorry, but I have no other clues about what is going on.   Here's my log of works/doesn't-work from bisecting on tags
```
20210503.0      not tried
20210504.0      works
20210517.0      works
20210518.0      fails
20210526.0
20210528.0      fails
20210531.0
20210531.1      fails
20210601.0
20210601.1      fails
```

I realize this points to the lit update which is not an easy thing to debug.

**Comment by spacegaier** [comment]
Do you use any custom cards? I could imagine that some have not yet updated to the new lit versions and now interfere since the HA frontend is using the latest lit version.

**Comment by gdt** [comment]
No, really pretty vanilla, entities, entity glance, picture glance, weather integration.   My setup is really just a bunch of sensors  where I want to see the values and get alerts if they are out of bounds, plus a few switches; there is almost no fancy GUI.   And it all worked fine in firefox desktop and firefox android.

**Comment by araczkowski** [comment]
flat is a fairly new feature in the browser that the old browser on may not have (because it was not implemented in your old browser version)
The flat method was implement in Chrome v69 - see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

you need to upgrade your browser

**Comment by gdt** [comment]
With newer Android OS with newer webview, it works.    It would be nice for the app to have an explicit statement about requirements, and/or actually check them at runtime and throw a clear error.

**Comment by bramkragten** [comment]
Mmmm we should not use `flat`, or polyfill it... Probably one of our dependencies uses it, will check
