### ISSUE TITLE
Low res splash loading/Info tab image

### ISSUE THREAD

**Issue by agneevX** [home-assistant/frontend#9406]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

- The splash loading screen Home Assistant logo is a low-res PNG.
- The Home Assistant logo inside `Configuration` → `Info` is also the same low-res one.

These should be replaced by a SVG. 

### Describe the behavior you expected

SVG icons

### Steps to reproduce the issue

Open frontend on a mobile device

### What version of Home Assistant Core has the issue?

core-2021.6.3

**Comment by spacegaier** [comment]
I cannot find any HA SVG logo in the current repository, so we might have to take it from here and include it: https://www.home-assistant.io/images/home-assistant-logo.svg

**Comment by agneevX** [comment]
Bad bot.

**Comment by matthiasdebaat** [comment]
> I cannot find any HA SVG logo in the current repository, so we might have to take it from here and include it: https://www.home-assistant.io/images/home-assistant-logo.svg

What can I help you with?

**Comment by ludeeus** [comment]
[`src/components/ha-logo-svg.ts`](https://github.com/home-assistant/frontend/blob/dev/src/components/ha-logo-svg.ts)

**Comment by ludeeus** [comment]
https://github.com/home-assistant/frontend/pull/10807

**Comment by agneevX** [comment]
@ludeeus does this change affect the loading splash too?

**Comment by ludeeus** [comment]
No, that was changed in https://github.com/home-assistant/frontend/pull/10569
