### ISSUE TITLE
vol.Clamp doesn't accept a confirmation via keyboard

### ISSUE THREAD

**Issue by chemelli74** [home-assistant/frontend#9408]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Some config flows use the following additional option:

`vol.All(vol.Coerce(int), vol.Clamp(min=0, max=900)),`

Unfortunately when you hit enter, you get the successfully saved feedback but registry is not updated.
Looking at  WS messages in the network tab under developer-tools of the browser, shows wrong(old) value is sent.

If you hit save with the mouse instead everything works as design.

Confirmed by 2 users with Fritz and 1 with AsusWRT.

Simone

### Describe the behavior you expected

Update value even if confirm is by keyboard

### Steps to reproduce the issue

1. Load one of the integration using vol.Clamp: https://github.com/home-assistant/core/search?q=vol.Clamp
2. Configuration -> <integration> -> configure
3. Change the value by typing or using arrows
4. Hit <enter>
5. Check the registry value
6. Repeat step 2. and 3.
7. Click <save> with the mouse
8. Check the registry value

### What version of Home Assistant Core has the issue?

2021.6.3

### In which browser are you experiencing the issue with?

Microsoft Edge Version 91.0.864.41 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 20H2

**Comment by chemelli74** [comment]
Any frontend guy that may take a look ? ;-)

Simone

**Comment by bramkragten** [comment]
This would need support from voluptuous serialize

**Comment by chemelli74** [comment]
List of affected integrations:

- asuswrt
- control4
- eight_sleep
- fritz
- google_cloud
- lifx
- **light**
- nissan_leaf
- **scene**
- screenlogic
- tellduslive
- tesla
- tuya
- upb
- vallow
- volvooncall
- xiaomi_aqara
- xiaomi_miio

Should we act somehow ?

Simone

**Comment by bramkragten** [comment]
I'm not able to reproduce this.

I added this to the demo options flow:
```py
vol.Optional(
    "clamp",
    default=self.config_entry.options.get("clamp", 200),
): vol.All(vol.Coerce(int), vol.Clamp(min=0, max=900)),
```

And it seems to behave as expected?

**Comment by chemelli74** [comment]
Please check the following screenshot:

![image](https://user-images.githubusercontent.com/57354320/124351327-f8a78580-dbf9-11eb-8aa6-ffb009b33c8b.png)

if I hit ENTER on the keyboard I see the old value in the payload, if instead I click SUBMIT with the mouse it works fine.

I can reproduce with `fritz` integration, @bieniu can reproduce with `asuswrt`.

Simone

**Comment by bramkragten** [comment]
Since I don't have both those integrations, could you make a repo with the demo integration?

**Comment by chemelli74** [comment]
Added suggested code and reproduced.
Did you carefully followed the steps ?

1. 

- change the value
- hit ENTER to confirm
- check browser debugger: you see the old value and not the new one

2. 

- change again the value
- click SUBMIT with the mouse
- check browser debugger: all fine, new value is shows.

Simone

**Comment by bieniu** [comment]
I can confirm that. Exactly the same behavior.

**Comment by bramkragten** [comment]
Yes, I did, although not in Edge. Might this be browser-specific?

**Comment by bieniu** [comment]
I use Edge and Opera and the issue exists on both.

**Comment by chemelli74** [comment]
> Yes, I did, although not in Edge. Might this be browser/platform-specific?

Edge is Chromium, so I would expect the same for other browsers as well.

Simone

**Comment by bramkragten** [comment]
I don't expect anything anymore now that I've been working with browsers for a while...

Here is what I do and get, all keyboard:

https://user-images.githubusercontent.com/5662298/124828173-351b0e80-df77-11eb-82c5-cfb2587fd502.mp4

**Comment by chemelli74** [comment]
Which browser and which OS ? Please give also info on the version.
I would like, if possible, to emulate your scenario.

Simone

**Comment by bramkragten** [comment]
Chrome 91.0.4472.114 on MacOSX 11.4

**Comment by chemelli74** [comment]
Did you get time to test on windows ?

Simone

**Comment by chemelli74** [comment]
Still awaiting verification

Simone

**Comment by spacegaier** [comment]
I am also not able to reproduce the issue (using Bram's code). Works fine for me on Win 10 with FF, Chrome and Edge.

**Comment by chemelli74** [comment]
Didn't retest in the last months; I can confirm it works fine now.

@bieniu, does it work for you as well ?

Simone

**Comment by bieniu** [comment]
I can confirm the problem is solved.
