### ISSUE TITLE
Error while loading page config.

### ISSUE THREAD

**Issue by blavak68** [home-assistant/frontend#9409]
### The problem

By default I use the Firefox web browser (now version 89.0 32-bit), but after the last update, when I click on the Settings (left panel), I get the following error message: "Error while loading page config."

However, when I use for exaple MS Edge everything works properly and then I find this entry in the logs:

Logger: frontend.js.latest.202106030
Source: components / system_log / __ init__.py:190
First occurred: 7:50:10 (6 occurrences)
Last logged: 10:53:44
https: // xxxxxxx: 8123 / frontend_latest / chunk.25494997e56388479d5d.js: 1: 0 SyntaxError: illegal character U + 001F

### What is version of Home Assistant Core has the issue?

core-2021.6.4

### What was the last working version of Home Assistant Core?

core-2021.5.x

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

---

### Link to integration documentation on our website

---

### Example YAML snippet

```yaml
---
```

### Anything in the logs that might be useful for us?

```txt
Logger: frontend.js.latest.202106030
Source: components / system_log / __ init__.py:190
First occurred: 7:50:10 (6 occurrences)
Last logged: 10:53:44
https: // xxxxxxx: 8123 / frontend_latest / chunk.25494997e56388479d5d.js: 1: 0 SyntaxError: illegal character U + 001F
```

**Comment by spacegaier** [comment]
Did you test it in private browsing mode to rule out caching issues?

**Comment by blavak68** [comment]
ok have you right, problem was in old modules in cash

I close the ticket

thx
