### ISSUE TITLE
Number entity with infinite max_value throws error

### ISSUE THREAD

**Issue by farmio** [home-assistant/frontend#9413]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When a number entity is configured that has a `max_value` property of `float('inf')` or `min_value` property of `float('-inf')` HA reports an error when loading the frontend:
```js
ERROR (MainThread) [homeassistant.components.websocket_api.messages] Unable to serialize to JSON. Bad data found at $.event(Event: state_changed).data.new_state(State: number.test_number_percent).attributes.min=-inf(<class 'float'>, $.event(Event: state_changed).data.new_state(State: number.test_number_percent).attributes.max=inf(<class 'float'>
```

The entity registry seems to handle this properly, but since this can not be loaded it leaves the integration unusable and the entry has to be removed by hand.
```json
{
    "entity_id": "number.test_number_percent",
    "config_entry_id": null,
    "device_id": null,
    "area_id": null,
    "unique_id": "0/4/44",
    "platform": "knx",
    "name": null,
    "icon": null,
    "disabled_by": null,
    "capabilities": {
        "min": -Infinity,
        "max": Infinity,
        "step": 1e-07
    },
    "supported_features": 0,
    "device_class": null,
    "unit_of_measurement": null,
    "original_name": "Test-Number-Percent",
    "original_icon": null
}
```

### Describe the behavior you expected

A number entity card without limits for the entered value.

### Steps to reproduce the issue

I have used this PR https://github.com/home-assistant/core/pull/51786 with following configuration.yaml entry:
```yaml
knx:
  number:
    - name: Test-Number-Percent
      address: "0/4/44"
      type: 14
```
Essentially returning `float('inf')` from https://github.com/home-assistant/core/blob/123e8f01a19ec075b597f1052245a24c89388bf6/homeassistant/components/number/__init__.py#L86 triggers the error when the UI is loaded.

### What version of Home Assistant Core has the issue?

dev branch of 12.6.2021

### In which browser are you experiencing the issue with?

Chrome 91

### Which operating system are you using to run this browser?

macOS 10.13.6

**Comment by spacegaier** [comment]
Interesting edge case. Two initial observations:
1. The YAML above does not work for me. I get a config error telling me that I need a `min` attribute (see below).
2. The error seems to come from the backend: https://github.com/home-assistant/core/blob/0730b375f3ab2cf284ff6cebadc8784b236a3223/homeassistant/components/websocket_api/messages.py#L83

> Invalid config for [knx]: 'min' key required for value type '14' @ data['knx']['number'][0]. Got OrderedDict([('name', 'Test-Number-Percent'), ('address', '0/4/44'), ('type', 14)]). (See /home/philip/.homeassistant/configuration.yaml, line 413).

**Comment by farmio** [comment]
My workaround was to check in the schema if the configured `type` uses infinite values and require min/max configured then. https://github.com/home-assistant/core/pull/51786/commits/b9aaa77a9ba0287f3581e1c0d59e3d6d273c1205
Just tested it and it seems you can still trigger it by configuring:
```yaml
knx:
  number:
    - address: "0/4/45"
      respond_to_read: True
      type: 14
      min: -5
      max: inf
```
