### ISSUE TITLE
view with background flashes on hovering in/out menu items

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#9418]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

views with a background set always (keep) flashing when moving the mouse in and out of the menu items in Safari desktop Mac. Believed I had filed an issue long time ago, but unable to find it. so an updated issue in in order.

custom theme (Matrix)

![Jun-14-2021 14-03-43](https://user-images.githubusercontent.com/33354141/121889766-eb455c80-cd19-11eb-93a0-f91acaee801e.gif)

default theme

![Jun-14-2021 14-06-11](https://user-images.githubusercontent.com/33354141/121889897-0b751b80-cd1a-11eb-90a8-73ee9494bcab.gif)

### Describe the behavior you expected

non flashing background, like Chrome does

### Steps to reproduce the issue

1. see screen movies above
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.6.4

### What was the last working version of Home Assistant Core?

dk

### In which browser are you experiencing the issue with?

Safari desktop Mac

### Which operating system are you using to run this browser?

Big sur 11.2.3 Safari 14.0.3 

### State of relevant entities

```txt
not relevant
```

### Problem-relevant frontend configuration

```yaml
nothing special
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

**Comment by spacegaier** [comment]
So it seems to be Safari specific, since it works for you in Chrome? Could there be any custom stuff that interferes, even if only in Safari?

On Win 10 here I have no issues with background images.

**Comment by Mariusthvdb** [comment]
thanks for getting back to this. As I experience it now, 2021.9 has solved this!

to answer your question about custom stuff: I am not sure of course, but don't think any of the custom cards would cause this, and it didnt have to do with that specific theme either, because I have another view with background image acting identically. In any theme.

That too stopped flashing... ;-)
yeah. will close because of that.
