### ISSUE TITLE
Ingress App not working with non administrator privileges

### ISSUE THREAD

**Issue by oeiber** [home-assistant/frontend#9419]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I wrote a ingress addon with the following options in config.json:

```
  "ingress": true,
  "panel_admin": false
```

When I try to access the app using an administrator account, it works perfectly. With a non admin user, the following error appears:

`Unable to fetch add-on info to start ingress`

### Describe the behavior you expected

Users with non admin privileges should be able to access ingress apps with config option   `"panel_admin": false` is set

### What version of Home Assistant Core has the issue?

core-2021.6.4

### In which browser are you experiencing the issue with?

Latest versions of Chrome, MS Edge (Chromium), HAS Companion App for iOS

### Which operating system are you using to run this browser?

macOS Big Shur, Windows 10 20H2

**Comment by spacegaier** [comment]
Can you please check your browser console and network log. There should be some calls that attempt to get the add-on info from the backend (endpoint looking something like this: `/addons/${slug}/info`).

Do you see them and why they fail?

**Comment by oeiber** [comment]
I cannot see any requests to /addons/* in the network log.
But there are a lot of those errors in the console, when I try to access the ingress page:
![image](https://user-images.githubusercontent.com/46045177/132749837-2eac6d57-596a-4cff-ba51-c78dad6f72c0.png)
