### ISSUE TITLE
Buttons missing + Cant open Addons after Update to supervisor-2021.06.3

### ISSUE THREAD

**Issue by FaserF** [home-assistant/frontend#9435]
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After updating to supervisor-2021.06.3 from supervisor-2021.06.0 I am unable to Update my HA Core (button wont work and wont be displayed), many many buttons are now not being displayed anymore and I cant open any of my addons anymore.

What I have done trying to fix it:
Restarted the whole OS
Restarted HA
Cleared my Cache
Opended HA in an incognito Tab
Tried it on another device

### Describe the behavior you expected

That i can click on the "update HA" button, that I see the buttons and that I can open my addons.

### Steps to reproduce the issue

Update Supervisor to supervisor-2021.06.3 from supervisor-2021.06.0
See the issue.

### What version of Home Assistant Core has the issue?

core-2021.6.4

### In which browser are you experiencing the issue with?

Google Chrome 91.0.4472.77

### Which operating system are you using to run this browser?

Windows 10 - 21H1

### Additional information

I had already opened an issue at the supervisor github, where I was told to open the issue here:
https://github.com/home-assistant/supervisor/issues/2963

![image](https://user-images.githubusercontent.com/12374134/122249942-8c264a00-cec9-11eb-83bc-dc87fe884810.png)
![image](https://user-images.githubusercontent.com/12374134/122249950-8df00d80-cec9-11eb-8617-9188373e314c.png)
![image](https://user-images.githubusercontent.com/12374134/122249960-8fb9d100-cec9-11eb-97a7-27acba1eab0b.png)

**Comment by ludeeus** [comment]
Can you add everything that shows in the browser console under "Javascript errors shown in your browser console/inspector" in the issue template?

**Comment by ludeeus** [comment]
And how are you accessing the frontend?
http? proxy? https?

**Comment by Wh1terat** [comment]
Same problem - only seems to occur over https (cloudflare proxy).

Seems to be failing to grab "<snip>/api/hassio/app/static/translations/en-f4ad98584c6b4ec5293e2bacb27e9359.json"

```
entrypoint.586ea840.js:2824 Uncaught (in promise) Error: Fail to fetch translation en-f4ad98584c6b4ec5293e2bacb27e9359.json: HTTP response status is 404
    at entrypoint.586ea840.js:2824
    at async HTMLElement.value (entrypoint.586ea840.js:2824)
```

**Comment by ludeeus** [comment]
Clear cloudflare cache for your domain

**Comment by Wh1terat** [comment]
Done but no change. 
The translation that it's failing to pull isn't available over http locally either.

**Comment by ludeeus** [comment]
It must be cache somewhere that file is not included in <https://github.com/home-assistant/supervisor/tree/2021.06.3/supervisor/api/panel/static/translations>

But was in <https://github.com/home-assistant/supervisor/tree/2021.06.0/supervisor/api/panel/static/translations>

**Comment by FaserF** [comment]
Yeah, I am also using https with cloudflare and nginx proxy.

Now out of nowhere it is working again. Seems to be as thought a cloudflare cache thing.
So „sadly“ I can’t provide some JavaScript logs.

i would leave the issue opened for @Wh1terat

**Comment by ludeeus** [comment]
Cloudflare takes some time to clear it on all edge locations, up to 1 min I think

**Comment by Wh1terat** [comment]
Thanks @ludeeus, bit of impatience on my side after clearing!

**Comment by ludeeus** [comment]
Great! 🎉
