### ISSUE TITLE
Change icon_template only one if check self state

### ISSUE THREAD

**Issue by DimkaInc** [home-assistant/frontend#9439]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The problem described [here(home-assistant/core#42003)](https://github.com/home-assistant/core/issues/42003) is still present and has not been fixed, although it has already been closed.

### Describe the behavior you expected

Each time the status of the sensor changes, the icon should change according to the condition 

### Steps to reproduce the issue

1. Config:

```
- platform: template
  sensors:
    
    day_period:
      friendly_name: 'Dagdeel'
      icon_template: >
        {% set my_state = states.sensor.day_period.state %}
        {% if (my_state == 'Nacht') %} mdi:weather-night
        {% elif (my_state == 'Ochtend') %} mdi:weather-sunset-up
        {% elif (my_state == 'Dag') %} mdi:weather-sunny
        {% elif (my_state == 'Avond') %} mdi:weather-sunset-down
        {% else %} mdi:crop-square
        {% endif %}
      value_template: >
        {% if state_attr("sun.sun", "elevation")|float >= 10 %} Dag
        {% elif (state_attr("sun.sun", "elevation")|float >= -7.0 and now().hour < 12) %} Ochtend
        {% elif (state_attr("sun.sun", "elevation")|float >= -20.0 and now().hour > 12 and now().hour <= 22) %} Avond
        {% else %} Nacht
        {% endif %}

```
2. Server start - set icon
3. Sensor first change - change icon
4. Sensor next change - icon not change and show this warning:
```


    HA start: everything ok
    First state update of sensor: icon updates ok BUT Template loop error logged
    From second update on: reverted back to "HA load" icon + Template loop error

2021-06-17 16:47:12 WARNING (MainThread) [homeassistant.components.template.template_entity] Template loop detected while processing event: <Event state_changed[L]: entity_id=sensor.day_period, old_state=<state sensor.day_period=Nacht; friendly_name=Dagdeel, icon=mdi:weather-sunny @ 2021-06-17T16:46:33.331971+03:00>, new_state=<state sensor.day_period=Avond; friendly_name=Dagdeel, icon=mdi:weather-sunny @ 2021-06-17T16:47:12.256788+03:00>>, skipping template render for Template[{% set my_state = states.sensor.day_period.state %} {% if (my_state == 'Nacht') %} mdi:weather-night {% elif (my_state == 'Ochtend') %} mdi:weather-sunset-up {% elif (my_state == 'Dag') %} mdi:weather-sunny {% elif (my_state == 'Avond') %} mdi:weather-sunset-down {% else %} mdi:crop-square {% endif %}
```

### What version of Home Assistant Core has the issue?

core-2021.6.5

**Comment by spacegaier** [comment]
This is not a frontend issue. The frontend simply renders what the backend provides as the resulting icon from the template evaluation.

Scrolling through the linked core issue, it sounds like the template you use is the root case due to some self references? There apparently were some changes some time ago that in certain scenarios allow self-references (https://github.com/home-assistant/core/pull/39943) but I am no HA template expert.
