### ISSUE TITLE
Onboarding page doesn't load correctly through Iframe

### ISSUE THREAD

**Issue by Morphy99** [home-assistant/frontend#9441]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When trying to onboard a new installation through an Iframe the page fails to load correctly showing just the Home Assistant banner:

![image](https://user-images.githubusercontent.com/5853979/122481882-7303c300-cfc7-11eb-872a-555464c07e7c.png)

 Inspecting further in Chrome x86 I see this error:

```
Uncaught (in promise) DOMException: Blocked a frame with origin "http://192.168.0.195:8081" from accessing a cross-origin frame.
    at Object.72055 (http://192.168.0.195:8081/frontend_latest/onboarding.59a126ca.js:1297:129501)
    at a (http://192.168.0.195:8081/frontend_latest/onboarding.59a126ca.js:1869:1335)
    at Object.74265 (http://192.168.0.195:8081/frontend_latest/onboarding.59a126ca.js:1345:2288)
    at a (http://192.168.0.195:8081/frontend_latest/onboarding.59a126ca.js:1869:1335)
    at Object.33005 (http://192.168.0.195:8081/frontend_latest/onboarding.59a126ca.js:1345:63549)
    at a (http://192.168.0.195:8081/frontend_latest/onboarding.59a126ca.js:1869:1335)
    at http://192.168.0.195:8081/frontend_latest/onboarding.59a126ca.js:1869:10300
    at http://192.168.0.195:8081/frontend_latest/onboarding.59a126ca.js:1869:10310

```

After loading the page directly and onboarding everything seems to work OK through the Iframe.

### Describe the behavior you expected

Page loads with correct onboarding page:

![image](https://user-images.githubusercontent.com/5853979/122481972-96c70900-cfc7-11eb-928b-b4f4e84b2d99.png)

### Steps to reproduce the issue

1. Open browser and load iframe page up
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.6.5

### In which browser are you experiencing the issue with?

Google Chrome 91.0.4472.106 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 7 x64

**Comment by Morphy99** [comment]
Still an issue on 2021.9.6

**Comment by Morphy99** [comment]
Still an issue on 2021.12.7

**Comment by bschatzow** [comment]
Still an issue using chrome on a new 2021.12.7 install.
