### ISSUE TITLE
Opening system options also opens rename pop-up

### ISSUE THREAD

**Issue by milanmeu** [home-assistant/frontend#9450]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The rename menu opens together with the system options pop-up on the integration page.
This only happens if the rename menu of the same integration was opened before.

### Describe the behavior you expected

Don't open the rename menu when opening the system options.

### Steps to reproduce the issue

1. Open config entry `rename` menu
2. Close the pop-up by clicking `OK` or `CANCEL`
3. Open config entry `system options` for the same integration

### What version of Home Assistant has the issue?

Core: 2021.6.3, Latest
Frontend: 20210603.0, https://github.com/home-assistant/frontend/commit/c1d571de42c41a60aac7884e3c2d6b298ccb10b0

### In which browser are you experiencing the issue with?

Chromium, Firefox

### Which operating system are you using to run this browser?

Ubuntu 21.04

### Additional information

https://user-images.githubusercontent.com/15276289/122658597-7cc82a80-d16f-11eb-83e9-48df1ffcc99c.mp4

**Comment by spacegaier** [comment]
I can confirm the issue. PR that should fix it, is coming soon.

**Comment by Misiu** [comment]
@milanmeu this should be fixed right now. Please close this issue if it is working correctly.
