### ISSUE TITLE
Too many preview cards during adding pushes UI off screen, inaccessible

### ISSUE THREAD

**Issue by ProjectPatatoe** [home-assistant/frontend#9452]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

While editing the lovelace UI, I am filling a view with cameras. After checking a bunch of cameras for entities I want to add, it then gives me a preview of all the cards. However the number of cards pushed the bottom of the modal off the bottom of the screen and is inaccessible. 

I suspect this would probably happen with other types and not just camera but I don't know what preview cards are large enough to push off screen.

To continue: Clicking out of the modal will close it but I would be unable to ever get the 'card preview'. A refresh of the page will fix it (separate issue, will post - )

### Describe the behavior you expected

Still able to access the "continue" or "cancel" button on the bottom

### Steps to reproduce the issue

1. Edit UI / Add Card
2. By Entity
3. Add many things at once (in my case, 4+ cameras

### What version of Home Assistant Core has the issue?

core 2021.6.5

### In which browser are you experiencing the issue with?

Chrome 91 / FF 89.0.1

### Which operating system are you using to run this browser?

Windows 21H1

**Comment by bramkragten** [comment]
Can you add a screenshot?

**Comment by ProjectPatatoe** [comment]
![image](https://user-images.githubusercontent.com/27925441/123000113-fde81300-d363-11eb-8222-564945b48c7a.png)
It seems a little bit low.
Turns out that if I resize the page, the modal resizes and it works then / has a scroll bar
