### ISSUE TITLE
HA refreshes every minute

### ISSUE THREAD

**Issue by thisisbenwoo** [home-assistant/frontend#9458]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Follow Up from Issue #4894 
^^ hopefully I'm referencing correctly. I read that when an issue is closed, I should start a new issue.

> @blattmann My issue appears to be with HAProxy. I don't have the periodic refresh if I access Home Assistant Core GUI via ip address. It only happens when using my reverse proxy. I fixed it by adjusting some http options in the configuration.yaml. You can go ahead and close this.

Can you advise what changes you made please? I'm experiencing this issue with 2021.06.all?? 
My frontend is refreshing every minute or so. Started around the upgrade to 2021.06.x
I am behind HAproxy on pfSense. I have added the "timeout tunnel 1h" to the Backend pass thru portion of the backend for HA.

### Describe the behavior you expected

The frontend should not be refreshing constantly.

My frontend is refreshing every minute or so. Started around the upgrade to 2021.06.x
I am behind HAproxy on pfSense. I have added the "timeout tunnel 1h" to the Backend pass thru portion of the backend for HA.

### Steps to reproduce the issue

1. Just go to homeassistant:8123 from internet --> pfsense firewall --> HAProxy --> <HA ip>:8123
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.6.1 through core-2021.6.6

### What was the last working version of Home Assistant Core?

core-2021.5.x

### In which browser are you experiencing the issue with?

Google Chrome 91.0.4472.114 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 Pro 21H1 Build 19043.1081

**Comment by spacegaier** [comment]
Please check the comments from https://github.com/home-assistant/frontend/issues/9398. Seems to be a similar issue, so the questions that bramkragten asked there would also apply to this ticket, esp. reg. console entries.
