### ISSUE TITLE
History graph card 'hours to show' field odd behavior

### ISSUE THREAD

**Issue by steelincable** [home-assistant/frontend#9462]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Three issues related to the default history graph card:
1. The 'hours to show' field won't let you clear it completely (say to set it to 6 hours) - it keeps resetting itself back to 24 when attempting to backspace over the 2 in 24.
2. When the value entered in the 'hours to show' field of a history graph card is a large number the browser will lock up.
3. The documented maximum for the 'hours to show' field is 80, but numbers higher than 80 are accepted which exacerbates issue 2.
![Untitled picture](https://user-images.githubusercontent.com/58582770/123267366-8c72a680-d4c2-11eb-8d91-b3b73e60272d.png)

The 'hours to show' field acts very strangely because it wants to reset to 24 and will not let you completely clear the field.  It's very easy to accidentally set it to a large number.  For example, if I want to set the value to 6 and the current value is 8 I would place my cursor in the field, press the backspace key then press the 6 key.  Due to issue 1 above the result would be 246 then due to issue 2 above the browser locks up and I have to close/reopen the tab.  If the number isn't too large and you wait long enough, the browser may finally render the entity history in the preview screen, but as shown in the screenshot the browser will become unresponsive and prompt to stop processing the page. 

### Describe the behavior you expected

I would expect to be able to clear the field so I can enter the value I desire up to the documented maximum.  I would expect an error on a value above the maximum either when it is entered (value allowed in the field, but a tooltip that it's invalid) or an error pop when saving the card.

### Steps to reproduce the issue

1. Edit a history graph card
2. On the history graph card configuration screen attempt to set the 'hours to show' field to the value of 6.  
3.
...

### What version of Home Assistant Core has the issue?

core-2021.6.6

### In which browser are you experiencing the issue with?

Firefox 89.0.1 (64-bit), Chrome 91.0.4472.114 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 home 20H2 19042.1052

### Problem-relevant frontend configuration

```yaml
type: history-graph
entities:
  - entity: binary_sensor.esphome_second_floor_motion_sensor
  - entity: input_boolean.morningmotion
refresh_interval: 0
title: Upstairs Motion Sensor
hours_to_show: 2
```

**Comment by jeeftor** [comment]
I experienced this yesterday - however I was able to get it working correctly on IOS after fiddling around and moving the cursor

**Comment by spacegaier** [comment]
1. I think that is by design. As soon as you reach an invalid value (and empty is invalid here since the minimum is 1) the values gets reset to the default. Scrolling and using the arrow keys works fine as well. I do get that the behavior might seem a bit weird. I will create a PR that will set a minimum value so that the scrolling and arrow keys can no longer reach 0.
2. That can happen since a lot of data (and hence rendering) can be involved.
3. I think the documentation is outdated since I cannot find any mention of this limit in the coding. I will prepare a correction PR.
