### ISSUE TITLE
Restore snapshot from onboarding screen is broken

### ISSUE THREAD

**Issue by knoopx** [home-assistant/frontend#9472]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

can't restore snapshot because of client-side error

### Describe the behavior you expected

the snapshot to be restored

### Steps to reproduce the issue

when clicking over and selecting a full snapshot

![image](https://user-images.githubusercontent.com/100993/123636746-83b10600-d81d-11eb-8c2a-e82e322bc0d4.png)

![image](https://user-images.githubusercontent.com/100993/123636817-988d9980-d81d-11eb-8f8c-1f95dc21da31.png)

### What version of Home Assistant Core has the issue?

haos_rpi4-64-6.1.img.xz

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

macOS X Big Sur

### State of relevant entities

```txt
fresh flash of haos_rpi4-64-6.1.img.xz to sdcard. first run.
```

### Javascript errors shown in your browser console/inspector

```txt
(anonymous) @ onboarding.59a126ca.js:37398
chunk.f877794aa8421b754491.js:872 Uncaught (in promise) TypeError: Cannot read property 'localize' of undefined
    at b (chunk.f877794aa8421b754491.js:872)
    at HTMLElement.value (chunk.a0d8c96fee72f9f74c91.js:812)
    at HTMLElement.update (onboarding.59a126ca.js:9352)
    at HTMLElement.performUpdate (onboarding.59a126ca.js:1)
    at HTMLElement.Πq (onboarding.59a126ca.js:1)
```

**Comment by ludeeus** [comment]
This was fixed in <https://github.com/home-assistant/frontend/pull/9385>
