### ISSUE TITLE
Cog and pen button functionality swapped on automations and scripts

### ISSUE THREAD

**Issue by BloodyusHellus** [home-assistant/frontend#9473]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using companion app on Android, when navigating throught entity -> related to a script or automation you get this page with a cog and pen in the upper right corner. Instead of editing the automation/script the pen takes you back to the "related" page and the cog let's you edit. After repeatedly going back and forth the issue seems to solve itself? Did not try to replicate in (desktop) browser

### Describe the behavior you expected

I expect the pen to get you to the editing screen
What the cog is meant to do in this case is not entirely clear to me

### Steps to reproduce the issue

1. Click an entity
2. Click the cog
3. Click "related" tab
4. Click an automation or script on that page
5. In the next page click pen or cog. It won't work as it should

### What version of Home Assistant Core has the issue?

2021.6.5

### In which browser are you experiencing the issue with?

Companion app on Android

### Which operating system are you using to run this browser?

Android 11

**Comment by bramkragten** [comment]
Not able to replicate this, the pen gets me to the edit screen for both scripts and automations.

**Comment by spacegaier** [comment]
Yes, I noticed the same behaviour. The dialogs stays open and that is confusing.
