### ISSUE TITLE
Initial service worker registration reloads page

### ISSUE THREAD

**Issue by rianadon** [home-assistant/frontend#9492]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I'm trying to automate testing of my custom component by using browser automation. I noticed that as soon a few seconds after a visit the login page, the page refreshes.

I've tracked the problem down to this line:
https://github.com/home-assistant/frontend/blob/1f377d43c59253bb50848b51440ded70c01bd434/src/util/register-service-worker.ts#L16-L18

Since it's the first time loading the page, I don't think there is a need for a reload. But I'm no service worker expert.

### Describe the behavior you expected

On a clean browser environment (such as `playwright` or just loading Home Assistant for the first time in a normal browser), Home Assistant should not refresh when you visit the site for the first time.

### Steps to reproduce the issue

I can reproduce this on normal Firefox and Chrome as well (steps are probably similar for other browsers):

1. Run Home Assistant on a host that supports service workers (`localhost` or https)
2. Visit `http://localhost:8123`
3. Open developer tools, go to the Application tab, make sure you are on the "Service Workers" section and unregister all service workers
4. Refresh the page. The page refreshes on its own a second time shortly thereafter
5. Refresh the page. Now that the service workers is registered, it no longer refreshes on its own

### What version of Home Assistant Core has the issue?

n/a

### In which browser are you experiencing the issue with?

latest Firefox & Chrome

### Which operating system are you using to run this browser?

macOS

### Additional information

Please don't spend a lot of time on this one; I'm currently sidestepping this problem in playwright by using 127.0.0.1 instead of localhost (as the `supportsServiceWorker` method only checks for `localhost` - hopefully that is not a bug too?). And an extra refresh probably bothers no one.

I was just hoping there might be some really obvious and easy fix to this bug.

**Comment by bramkragten** [comment]
You are right, we should not reload on first install, just on updates.
