### ISSUE TITLE
Charts ignore desired timezone from settings and uses browsers timezone instead. 

### ISSUE THREAD

**Issue by dalanmiller** [home-assistant/frontend#9501]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Charts are using the timezone of my browser instead of the one I've set in the hass settings. 

Because Firefox sets the timezone to UTC to prevent malicious fingerprinting, this makes the charts not very useful. Hass should just use the set timezone. 

### Describe the behavior you expected

Expected for timezone to reflect my preferred timezone. 

Confirmed that this works as expected in Safari. 

### Steps to reproduce the issue

1. Use firefox
2. Take a look at any chart
3. Observe that the timezone is UTC
...

### What version of Home Assistant Core has the issue?

core-2021.6.6

### What was the last working version of Home Assistant Core?

Uncertain

### In which browser are you experiencing the issue with?

Firefox 89.0.2 (64-bit)

### Which operating system are you using to run this browser?

macOS Big Sur (11.4)

**Comment by dalanmiller** [comment]
translations.ts

**Comment by bramkragten** [comment]
> translations.ts

What's with that file? 😄

**Comment by dalanmiller** [comment]
@bramkragten ha! Was perusing the code base on my iPad which doesn't have a good way to copy paths, anyway it seemed a good place to start to try and figure out what's happening here.

**Comment by bramkragten** [comment]
This is basically default behavior of a browser, it will display a date/time in the timezone of the browser.

**Comment by dalanmiller** [comment]
@bramkragten agreed, but this isn't very useful as this may be set to UTC by Firefox as a fingerprinting countermeasure.

https://wiki.mozilla.org/Security/Fingerprinting#Terse_List
<img width="1112" alt="Screen Shot 2021-07-11 at 9 51 58 am" src="https://user-images.githubusercontent.com/863286/125179027-f20ca580-e1d9-11eb-984c-0f0243782dd8.png">

In this case, I think if UTC is detected as the browser's locale, the frontend should fall back to the settings in `configuration.yaml`:

```
homeassistant:
    time_zone: "Australia/Melbourne"
```

**Comment by bramkragten** [comment]
Or turn off tracking protection for your local home assistant instance, as that will not track anyway?

**Comment by dalanmiller** [comment]
I turned this off and reset `resistFingerprinting` to false in `about:config` now when I run `new Date()` in the console I get the TZ I expect. However, the chart is still showing tool tips/datapoint in UTC time. 

Not sure what to try next.

**Comment by dalanmiller** [comment]
Example: 

In the console `new Date()` is appropriately returning with my system timezone. However, the time series line chart is still showing UTC time. 

<img width="870" alt="Screen Shot 2021-07-14 at 14 42 10" src="https://user-images.githubusercontent.com/863286/125562421-b5ec82ef-a99d-4599-b6a0-3e23447188c2.png">
