### ISSUE TITLE
Reword "Configuration>Server Controls>YAML configuration reloading" directions

### ISSUE THREAD

**Issue by gonzotek** [home-assistant/frontend#9515]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the YAML configuration reloading section, the directions refer to "hitting reload".  There is no "reload" to hit. 

### Describe the behavior you expected

I would expect to see the word "Reload" in front of each possible item to reload.  Or for the directions to refer to "hitting" something else (e.g. the item names).

### Steps to reproduce the issue

1. Open Home Assistant Configuration 
2. Go to Server Controls > YAML configuration reloading 
3. Observe the directions stating "Hitting reload" will unload current YAML configuration and load the new one.
4. Try to find the mythical reload button :-)
![Reload Screen](https://user-images.githubusercontent.com/253407/124654773-f6009680-de6c-11eb-8261-7a8cb03641e3.png)

### What version of Home Assistant Core has the issue?

core-2021.6.6

### What was the last working version of Home Assistant Core?

core.0.114

**Comment by spacegaier** [comment]
Has been fixed roughly two months ago: https://github.com/home-assistant/frontend/pull/9529
