### ISSUE TITLE
HTTP 415 Unsupported Media Type - NotSupportedException (…) in addon: traccar (0.12.0) after update to core-2021.7.0

### ISSUE THREAD

**Issue by dosdoncellas6** [home-assistant/frontend#9531]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After the update from core-2021.6.6 tocore-2021.7.0 the traccar addon in version 0.12.0 shows this message:

HTTP 415 Unsupported Media Type - NotSupportedException (…)

The same issue that this:

https://community.home-assistant.io/t/error-http-415-unsupported-media-type-notsupportedexception/320731

Reverted via snapshot to core-2021.6.6 the error disappear and the integration works correctly.

### Describe the behavior you expected

The expected behavior is the correct opening of the web UI in the traccar addon

### Steps to reproduce the issue

1. core-2021.7.0
2. traccar addon 0.12.0
3. try to open "WEB UI" from the traccar addon
...

### What version of Home Assistant Core has the issue?

core-2021.7.0

### What was the last working version of Home Assistant Core?

core-2021.6.6

### In which browser are you experiencing the issue with?

Chromium 90.0.4430.212, Google Chrome 91.0.4472.114, Home Assistant Android App 2021.6.2-full

### Which operating system are you using to run this browser?

Debian 10.10, android 11, android 7.1.2, Ubuntu 21.04

**Comment by bramkragten** [comment]
Is this about an addon?

**Comment by dosdoncellas6** [comment]
Yes sorry, the traccar addon
I correct the title

**Comment by bramkragten** [comment]
Please create an issue for that addon, this is either something that the addon should fix, or a change in core, but not a frontend issue.

**Comment by dosdoncellas6** [comment]
But the addon with the last version of core reverted from the snapshot works again, the change that broke the addon might be in the new version of the core.

**Comment by bramkragten** [comment]
Still create the issue in the addon repo, the author can probably pin point the issue more easily.
