### ISSUE TITLE
Custom icons not displayed in menu

### ISSUE THREAD

**Issue by jsiemek** [home-assistant/frontend#9541]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When you use custom icons they are visible everywhere but not in the menu.
If you switch into edit mode they got loaded and remain until app/browser restart.

### Describe the behavior you expected

Custom icons are visible everywhere also in the menu.

### Steps to reproduce the issue

1. add custom icon.
2. set menu item to use one of them.
3. exit edit mode, clear cache or restart browser. See empty place.
...

### What version of Home Assistant Core has the issue?

core-2021.7.1

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Google Chrome Version 91.0.4472.114 (Official Build) (x86_64)

### Which operating system are you using to run this browser?

macOS Big Sur 11.4

**Comment by jsiemek** [comment]
![Screenshot 2021-07-11 at 09 18 37](https://user-images.githubusercontent.com/36767404/125186658-fb266280-e22b-11eb-89d4-1003dbf519ac.png)
![Screenshot 2021-07-11 at 09 18 13](https://user-images.githubusercontent.com/36767404/125186659-fc578f80-e22b-11eb-926a-1aee6326b1cb.png)
![Screenshot 2021-07-11 at 09 18 01](https://user-images.githubusercontent.com/36767404/125186660-fc578f80-e22b-11eb-9fee-179f63095d16.png)

**Comment by jsiemek** [comment]
[custom_icons.zip](https://github.com/home-assistant/frontend/files/6796520/custom_icons.zip)

**Comment by bramkragten** [comment]
This means your icons are loaded too late. How do you load them?

**Comment by jsiemek** [comment]
I added /local/custom_icons.js to Configuration->Lovelace Dashboards->Resources.

**Comment by tribut** [comment]
This happens a lot for me when using an entity card. After a reload, the entity card has no icon, but when the card is clicked, the icon in the popup is present.

I'm using the same method (Lovelace -> Resources -> JS) to load my (trivial, one-icon) .js file.

**Comment by jsiemek** [comment]
Simply add this to your configuration.yaml

```
frontend:
  extra_module_url:
    - /local/custom_icons.js
```

**Comment by ildar170975** [comment]
> Simply add this to your configuration.yaml

I am using Custom brand icons:
https://github.com/elax46/custom-brand-icons
Sometimes these icons are not displayed on the tab menu - just a blank space is displayed.
The installed icons are located here as paths:
www/community/custom-brand-icons/custom-brand-icons.js

I added this line into configuration.yaml
```
frontend:
  extra_module_url:
    - /hacsfiles/custom-brand-icons/custom-brand-icons.js
```
Will this solution help me?
