### ISSUE TITLE
List scroll is broken after returning from the item view (Automations, Devices, etc.)

### ISSUE THREAD

**Issue by gorbunovav** [home-assistant/frontend#9543]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

List scroll is broken after returning from the item page (e.g. Automations list -> Automation page -> return back).

### Describe the behavior you expected

Normal scrolling after returning from the item page.

### Steps to reproduce the issue

1. Open Automations list (or any other list with a lot of items and standalone item page)
2. Try to scroll up/down - should work normal
3. Open item (e.g. by clicking on the edit icon in automations list)
4. Click the "Back" button
5. Try to scroll the list - on Firefox the position will be jumping and eventually you will stuck at the bottom of the list. On Chrome it is less obvious, but there will be a jump in the middle of the list (so it is impossible to reach the middle position of the scroll bar).
6. Navigate to some other page and then return back - now scroll  works ok.

It happens for me both on desktop and in iOs app.

### What version of Home Assistant Core has the issue?

core-2021.7.1

### What was the last working version of Home Assistant Core?

core-2021.6.6 (I guess)

### In which browser are you experiencing the issue with?

Firefox, Chrome, Safari iOs

### Which operating system are you using to run this browser?

Windows 11, iOs 14.7

### Javascript errors shown in your browser console/inspector

```txt
Don't see any new items during the navigation.
```

**Comment by jtaseff** [comment]
Same issue for me. On 2021.6, the symptom was getting stuck when I tried to scroll to the bottom of the list, the scroll bar would flicker to top and bottom and can't reach the bottom. Now on 2021.8, I can reach the bottom, but the scroll bar flickers up and down and the screen slowly scrolls back up by itself about a pixel at a time.

**Comment by tofurky** [comment]
i will add, there is very high cpu usage when the page slowly and automatically scrolls upwards after you try to manually scroll down. not sure if it's a .js thing or rendering - guessing .js.

**Comment by Final-Hawk** [comment]
I have the same issue. I also get a similar bug on the logbook page, scrolling back up causes it there. Thanks to the developers, but Its bugs like these that make HA feel rough.
