### ISSUE TITLE
Time displays as 24:48 instead of 00:48

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/frontend#9545]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The device tracker shows, that the person was home from `24:48` until `01:17`, but instead it should show `00:48` until `01:17`:
![image](https://user-images.githubusercontent.com/1368405/125212748-c5c35880-e2af-11eb-935f-9a77ac0ba062.png)

### Describe the behavior you expected

Show `00:48` instead of `24:48`

### Steps to reproduce the issue

1. Use device tracker
2. Have an event between 0 o'clock and 1 o'clock
3. Hover over time

### What version of Home Assistant Core has the issue?

core-2021.7.1

### What was the last working version of Home Assistant Core?

?

### In which browser are you experiencing the issue with?

Microsoft Edge 92.0.902.40

### Which operating system are you using to run this browser?

Windows 10 21H1

**Comment by spacegaier** [comment]
Duplicate of https://github.com/home-assistant/frontend/issues/9379

**Comment by TheZoker** [comment]
Yes that's indeed the same bug. Closing this issue
