### ISSUE TITLE
History Graphs - Color change in 2021.7.1 update - Cannot find documentation of the change - new colors are harder to read

### ISSUE THREAD

**Issue by srnoth** [home-assistant/frontend#9547]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

With the last update to 2021.7.1, the colors / look of the History Graph in lovelace have changed. I looked through the release notes and all recent pull requests, and none mention where or why the previous colors were changed.

Previously, for a history graph with multiple values/entities, lovelace would automatically choose very contrasting colors, making the graphs easy to read.

With the change, lovelace is selecting different colors yes, but they are all very similar, variations of blue/purple/teal, making the graphs much harder to read.

I believe this issue is related to the one mentioned here:
https://github.com/home-assistant/frontend/issues/9495#issuecomment-875826241

Essentially something changed the automatic color scheme for the History Graphs.

### Describe the behavior you expected

Previous colors were more distinct.

### Steps to reproduce the issue

Update from 2021.6 to 2021.7. Use History Graphs in lovelace.

### What version of Home Assistant Core has the issue?

2021.7.1

### What was the last working version of Home Assistant Core?

2021.6

**Comment by srnoth** [comment]
New colors are not distinct, difficult to differentiate at a glance:
![image](https://user-images.githubusercontent.com/69703084/125229778-72e4a380-e2a5-11eb-83f7-6535c288e5fb.png)

**Comment by bramkragten** [comment]
Mmm yeah... In this case, we use the color for cooling, but that clashes with the 1 first random color... I'll make sure this doesn't happen by default

**Comment by mmiller7** [comment]
I'll second this issue.  For some reason it has picked light-purple and light-teal as 2 adjacent colors which is the worst by far but many graphs and history bars are now harder to read.  With no way to customize we really need the random colors to at least have good contrast, not be all similar pastel-light.

![image](https://user-images.githubusercontent.com/606945/126067033-c1abe10f-254a-45d2-b224-cfac7d701c63.png)

**Comment by mkanet** [comment]
Can we please just revert back to the old colors?  The old colors were just fine.  I had to revert back to version 2021.6 for multiple unrelated breaking changes; including https://github.com/home-assistant/core/issues/53207

**Comment by mmiller7** [comment]
I think there may be another bug where if I click to "hide" one sensor on a graph it seems to "turn back on" by itself after several seconds.

Seems like these new graphs are a big mess.

**Comment by mkanet** [comment]
Does anyone know if it's possible for us to use **ChartJS V2** with Home Assistant Version >2021.7.x   ...similar to how we can override broken HA integrations with a previous version by copying the older source files to the below path?  This would solve the problem until there's a fix in the future.

`/config/custom_components/xxxxxxxxx`

If so, could someone please show me how to do that?

**Comment by Youpimatin** [comment]
Same problem with new colors...
I'm searching a way to return to previous graph implementation (and colors)
And why did they choose the colors of the graph line, the same color as the circle border, and not the color INSIDE the circle ?

**Comment by bramkragten** [comment]
If you look closely you'll see that is about the same list

**Comment by SiliconAvatar** [comment]
> If you look closely you'll see that is about the same list

Some of the colors are similar, however since the graph colors are chosen from the list in order, the first few are arguably the most important. It's the first 3 colors of the new colors that's the main problem (in my view).

In the new color list, the first 3 colors are rather similar to each other and hard to distinguish:
#377eb8 (blueish pastel), #984ea3 (purpleish), #00d2d5 (a blueish pastel somewhere between the first 2 colors)

Where as in the old color list, the initial 3 colors used are distinct:
#ff0029 (red), #66a61e (green), #377eb8 (blue).

If an acceptable PR would be to just replace the current (new) color list with the old color list, I'd gladly submit it. I'm just not hopeful it would be an accepted change. I have the assumption that the only acceptable PR around this would be one that allows selecting custom colors as a new feature, which is beyond my abilities.

**Comment by mkanet** [comment]
@SiliconAvatar thanks for the offer.  I doubt anyone would mind if you were to just revert all the colors back to exactly how it was before.... until someday someone decides to add color customization.

**Comment by srnoth** [comment]
I would absolutely prefer we revert to the old colors, until customization can be added.

**Comment by Youpimatin** [comment]
> 
> 
> I would absolutely prefer we revert to the old colors, until customization can be added.

Ditto !

I'm still blocked at **core-2021.6.6** version for this color problem.
Will there be a light at the end of the tunnel ?

**Comment by Mariusthvdb** [comment]
would it in anyway be feasible to allow the history-graph colors to be theme-able? If so, Id gladly write a discussion/fr on that. 
Currently the random colors mostly really 'async' with our carefully curated color settings. 

Realizing we can only curate those in Custom cards (card-mod and custom-ui) I ask here first before writing that FR up.
