### ISSUE TITLE
History graph date and time makers are misaligned on x-axis

### ISSUE THREAD

**Issue by RobPijpers** [home-assistant/frontend#9555]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

From update 2021.7.1 the history graph shows a date marker between the hour markers. As the markers move to the left of the graph during time the date and hour markers overlap each other as shown in the attachment.
Also the y-axis label is turned vertically which makes it harder to read and the vertical time bars are not equally divided.

![has](https://user-images.githubusercontent.com/17836136/125422621-97c70a50-4289-4426-bb18-6b9f1bf7a8f7.png)

### Describe the behavior you expected

1. No overlappen of the markers
2. Vertical time bars evenly divided
3. Y-axis legend placed horizontally

### Steps to reproduce the issue

1. Create a history graph panel to the lovelace dashboard
2. Add some temperature sensors
3. Wait for at last 24h to view the history graph 24h time frame

### What version of Home Assistant Core has the issue?

core-2021.7.1 and core-2021.7.2

### What was the last working version of Home Assistant Core?

core-2021.6.x

### In which browser are you experiencing the issue with?

Edge chromium, Safari, Home Assistant IOS App

### Which operating system are you using to run this browser?

macOS Big Sur, Windows 10, IOS 14

**Comment by RichieFrame** [comment]
This is still occurring on 2021.8.6, using any browser (on linux os) as well as the Android mobile app
