### ISSUE TITLE
Climacell Feels like temp is to 4 decimals. Can this be to 1 or 2 decimals please ?

### ISSUE THREAD

**Issue by nytram-md** [home-assistant/frontend#9557]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Please could we have the feels like temperature entity in Climacell integration to just 1 or 2 decimals like the HACS version as this is better to look at on the UI and for everyday stuff, we dont need to 4 decimal places.

### Describe the behavior you expected

Feels like temp to only 1 or 2 decimal places ie 25.1 or 25.12 in the UI

### Steps to reproduce the issue

1.
2.
3.
...
add climacell integration and enable the feels like entity

### What version of Home Assistant Core has the issue?

core-2021.7.0 and .1 and .2

### What was the last working version of Home Assistant Core?

New addition in 2021.7.0

### In which browser are you experiencing the issue with?

Not a browser issue. Just a tweak on the integration for decimal places to show

### State of relevant entities

```txt
Its the state of the entity sensor.climacell_feels_like
```

### Problem-relevant frontend configuration

```yaml
NONE
```

### Javascript errors shown in your browser console/inspector

```txt
NONE
```

### Additional information

NONE

**Comment by ludeeus** [comment]
The frontend does not handle integration-specific data.
For feature requests for integrations please raise those on the forum <https://community.home-assistant.io/c/feature-requests/13> thanks 👍
