### ISSUE TITLE
"Empty"paths in traces are not being correctly highlighted

### ISSUE THREAD

**Issue by DanielBaulig** [home-assistant/frontend#9565]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Sometimes* it appears certain paths in a trace with a branch are not correctly highlighted, even though the execution clearly flowed through them. See screenshot below.

* if I'm not mistaken this happens if the path is "empty", i.e. there is no explicit action on that path before the path merges back with a split execution path.

<img width="152" alt="Screen Shot 2021-07-14 at 9 12 12 PM" src="https://user-images.githubusercontent.com/158797/125728132-1f6aa005-c1bd-428d-b760-fece1d942082.png">

### Describe the behavior you expected

The "shortcut" path should be highlighted.

### Steps to reproduce the issue

1. Create a script/automation with a branching path (e.g. with a choose)
2. Keep one of the execution paths empty, e.g. an implicit  default in a choose
3. Record a trace of the script/automation and make it branch into the empty branch.
4. Note that in the UI the empty path will not be correctly highlighted.

### What version of Home Assistant Core has the issue?

core-2021.7.1

**Comment by bramkragten** [comment]
Thanks for reporting! This has been fixed in dev (#9527) already!
