### ISSUE TITLE
zoom for map in Lovelace not working

### ISSUE THREAD

**Issue by erd82** [home-assistant/frontend#9567]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When adapting the "Standard-Zoom" for a map in lovelace, the zoom value is not used.
![image](https://user-images.githubusercontent.com/63564291/125950611-b3046dbf-18a6-48c7-850e-ba800993135e.png)

Independent from the entered value the zoom level of your map keeps the same. 

Cheers, red

### Describe the behavior you expected

If I change the "Standard-Zoom" of the map configuration I expect that map in lovelace is zoomed in or out by default according to the given value.

### Steps to reproduce the issue

1. Add a map card to lovelace
2. define a zoom value as standard zoom
3. check the map and it's zoom
4. change the standard zoom value
5. check the map and it's zoom again

### What version of Home Assistant Core has the issue?

core-2021.7.2, core-2021.7.3

### What was the last working version of Home Assistant Core?

can't remember

### In which browser are you experiencing the issue with?

all browsers

### Which operating system are you using to run this browser?

Windows 10

**Comment by donoghdb** [comment]
I have the same issue. The zoom stopped working with the latest updates.

**Comment by Herbs851** [comment]
The same here. I downgraded to an earlier version (core 2021.6.6 frontend 20210603.0) and with these versions it works.

**Comment by donoghdb** [comment]
I think it's the changes under #9331 that have created the issue.
