### ISSUE TITLE
Right-click on a highlighted last word of an integration title in Chrome 90/91 crashes the browser tab

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/frontend#9571]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In Configuration->Integrations, if I highlight and right-click on the last word of a multi-word integration title of a card that contains multiple instances in Chrome 90/91, the browser tab crashes with `Error code: STATUS_BREAKPOINT` and the browser devtools disconnect.

Screenshot of the Integrations page with "TV" highlighted in "Apple TV" (must be hightlighted):

![image](https://user-images.githubusercontent.com/860888/125987912-39174d82-bd00-4666-b698-97f0cbf5e969.png)

If I right-click on "TV", I get this:

![image](https://user-images.githubusercontent.com/860888/125987807-453f1a97-7a3f-4532-b5e1-0e9b638ac800.png)

And this in the browser dev tools:

![image](https://user-images.githubusercontent.com/860888/125988009-83d7192a-9d5c-4261-a406-001d35d05c4c.png)

Any integration card that meets the following criteria repros the issue:
* Multi-word title (I think)
* Multiple instances added
* Highlight the whole title or just the last word
* Right-click on the highlighted last word

This only happens in Chrome (various 90/91 versions) for me, and not the Chromium-based Microsoft Edge (Version 91.0.864.70 (Official build) (64-bit)) or Firefox (from others testing on Discord).

### Describe the behavior you expected

I should get the typical browser right-click menu, as I do if I right-click on anything other than the highlighted last word of the title.

### Steps to reproduce the issue

1. Find an integration in Configuration->Integrations that has a multi-word title (like "Apple TV")
2. Highlight the whole title or just the last word
3. Right-click on the highlighted last word
4. Observe that the tab crashes with the screenshots shown above

### What version of Home Assistant Core has the issue?

core-2021.7.3

### In which browser are you experiencing the issue with?

Chrome Version 91.0.4472.164 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 20H2 Build 19042.1083

### Javascript errors shown in your browser console/inspector

```txt
The browser console/devtools disconnect when this happens.
```

**Comment by balloob** [comment]
This is a bug in Chrome. We should try to get a smallest as possible repro and submit it to the chrome bug tracker.

I am able to reproduce on my HA instance. Unable to reproduce in the gallery https://dev--home-assistant-gallery.netlify.app/#demo-integration-card

**Comment by balloob** [comment]
Submitted to Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1230262
