### ISSUE TITLE
Edit dashboard doesn't show buttons (EDIT, arrows, three dots)

### ISSUE THREAD

**Issue by Protoncek** [home-assistant/frontend#9594]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

From 2021.7 onwards when i click "edit dashboard" buttons "edit", arrows and three vertical dots  most of the times don't appear. This usually happens when i try to edit non-default dashboard. For these buttons to re-appear i must go to default dashboard, click "edit", go back to the dashboard i want to edit and re-click "edit" - now buttons appear again. 
Tried on three different PC's , different browsers, Android tablet and iOs tablet.

### Describe the behavior you expected

I'd expect that "edit" buttons will appear first time...

### Steps to reproduce the issue

1. open non-default dashboard
2. click "edit dashboard" - buttons DOES NOT appear
3. go to default dasboard and clikc "edit" there
4. go back to dasboard from before, click "edit again - now buttons are there
...

### What version of Home Assistant Core has the issue?

2021.7.x

### What was the last working version of Home Assistant Core?

2021.6.x

### In which browser are you experiencing the issue with?

Chrome, Edge, Safari

### Which operating system are you using to run this browser?

Windows 10

### Additional information

There's a topic on that problem here: 
[https://community.home-assistant.io/t/lovelace-card-edit-bars-gone/164590/6](url)
I believe that this problem started with July update.

**Comment by spacegaier** [comment]
I am not able to reproduce that (Chrome on Win 10) neither on my dev instance nor in production.

**Comment by Protoncek** [comment]
That’s interesting… In HA forum number of members had same experience. There’s also a second topic there (can’t find it now) about same problem.
As i wrote: it happens on my ipad, on my android phone and on all three my PC’s. 
And, i doubt that it’s my HA installation’s fault, since i have two instanced: production and “test VM” (for playing around) and happens on both installations.
I know that you can’t fix it if you can’t reproduce it…bummer…

**Comment by RainerFa** [comment]
I have same problem. Running 2021.6.5 before. After the update to 2021.7.4 the edit buttons  and the arrows below the cards are gone.  I can still edit the views and also raw edit is still possible. I did only experience this problem with my PI4.  I did exactly the same version update on my Pi3 without any problems. There am other user in the forum reporting the same problem on the Pi4. He even did a clean reimage and had the same problem.

**Comment by Protoncek** [comment]
I don’t have Pi, but VM inside synology NAS…

**Comment by spacegaier** [comment]
My production instance is a PI4 so that cannot be it.

Did you test it in a browser in private browsing mode to rule out any caching issues?

**Comment by RainerFa** [comment]
Many thx for your feedback. Cleared the chrome bowser cache. Tried the private mode in chrome, safari , HA desktop app, IOS chrome, IOS safari, IOS HA app but problem is still there.  It has something to fo with the HA setup.  Have not too many integration running, so far all worked fine with 2021.6.5 for weeks until I did this update to 2021.7.4 today. Will use another PI4 and do some more test the next days.

**Comment by ronsum232** [comment]
This may be the same or similar to issue logged in thomasloven/lovelace-layout-card [issue #153](https://github.com/thomasloven/lovelace-layout-card/issues/153).

**Comment by Protoncek** [comment]
Yes, it's the same. However, it's not  the same as [Lovelace edit mode broken #158](url) - in my case i do have lovelace page edit handles, only card handles (at the bottom of each card) are missing.

**Comment by RainerFa** [comment]
I did some testings. I can confirm that changing the view layout from Masonry or Vertical back to default will bring back the edit button and the arrows.

**Comment by Protoncek** [comment]
The problem still exists in 2021.8 version (it just happened...).

**Comment by RainerFa** [comment]
Yes I can confirm as well that it still exists in 2021.8. As workaround it helped to change  the view layout to default.

**Comment by Protoncek** [comment]
An update for this problem:
it seems that this problem exists only if lovelace layout is set to anything but default. I have one lovelace borad set to "vertical" (for my mobile phone) i have this problem. If i set layout back to default all is ok and "edit" bars appear immediately.
So, going to ANY lovelace with default layout causes all other pages to go back to normal. But only until browser is closed and re-opened...

**Comment by thomasloven** [comment]
I think it's fair to assume that this is "caused" by layout-card.

Please note that by default custom layouts DO NOT have any editing options at all.
Those included in Layout-card are exceptions.

Either way, it should work again with layout-card 2.3.1.

**Comment by Protoncek** [comment]
Yep, so far it works perfect! And i love new position of this setting - it's better accessible.

Many thanks!!!!
