### ISSUE TITLE
ZHA visualization triggers Python exception

### ISSUE THREAD

**Issue by samueltardieu** [home-assistant/frontend#9597]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When going through "Configuration > Integrations > ZHA > Visualization", an exception is triggered on the server side and nothing is displayed:

```
2021-07-23 13:59:16 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281472899855984] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/zha/api.py", line 248, in websocket_get_devices
    devices = [device.zha_device_info for device in zha_gateway.devices.values()]
  File "/usr/src/homeassistant/homeassistant/components/zha/api.py", line 248, in <listcomp>
    devices = [device.zha_device_info for device in zha_gateway.devices.values()]
  File "/usr/src/homeassistant/homeassistant/components/zha/core/device.py", line 470, in zha_device_info
    device_info.update(self.device_info)
  File "/usr/src/homeassistant/homeassistant/components/zha/core/device.py", line 419, in device_info
    ATTR_DEVICE_TYPE: self.device_type,
  File "/usr/src/homeassistant/homeassistant/components/zha/core/device.py", line 227, in device_type
    return self._zigpy_device.node_desc.logical_type.name
AttributeError: 'NoneType' object has no attribute 'name'
```

I noticed that after migrating the configuration from a RPi3b to an Odroid N2+ using the same ConBee I stick. Everything works as expected (around 35 Zigbee devices), no suspicious devices or groups seem to exist. 

### Describe the behavior you expected

I would have expected to see the Zigbee devices as before.

### Steps to reproduce the issue

1. Configuration > Integrations > ZHA > Visualization
2. Notice nothing is displayed
3. Notice the above-mentioned exception in the logs

### What version of Home Assistant Core has the issue?

core-2021.7.4

### In which browser are you experiencing the issue with?

Firefox nightly 92.0a1

### Which operating system are you using to run this browser?

ArchLinux x86_64 up-to-date

### Javascript errors shown in your browser console/inspector

```txt
Uncaught (in promise) 
Object { code: "unknown_error", message: "Unknown error" }
```

**Comment by samueltardieu** [comment]
It looks like this happens when a known Zigbee device has not registered with ZHA in the current session. Printing `self._zigpy_device` and `self._zigpy_device.node_desc` around line 227 of `homeassistant/components/za/core/device.py` yields respectively `<MijaButton model='lumi.sensor_switch' manuf='LUMI' nwk=0xA327 ieee=00:15:8d:00:04:03:42:17 is_initialized=False>` and `NodeDescriptor()`. 

There is already an early return in the `device_type` method for when `ßelf._zigpy_device.node_desc` is `None`, returning type `UNKNOWN`. Another one should be added when `self._zigpy_device.node_desc.logical_type` is `None` since it is indeed unknown as well at this stage. I'll propose a patch.

**Comment by bramkragten** [comment]
This is not a frontend issue, and seems to be addressed already.
