### ISSUE TITLE
Map card default zoom no longer has any effect

### ISSUE THREAD

**Issue by dlarrick** [home-assistant/frontend#9611]
### The problem

The Map card no longer honors the "defaut_zoom" parameter. No setting (I tried all numbers between 0 and 100) has any effect on the displayed zoom level of the map.

### What is version of Home Assistant Core has the issue?

core-2021.7.4

### What was the last working version of Home Assistant Core?

core-2021.5 ?

### What type of installation are you running?

Home Assistant Core

### Link to integration documentation on our website

https://www.home-assistant.io/lovelace/map/

**Comment by bramkragten** [comment]
Duplicate of #9567
