### ISSUE TITLE
history graph of input_number mis-represents actual values

### ISSUE THREAD

**Issue by mmiller7** [home-assistant/frontend#9623]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When viewing the history graph of an input_number type, the graph misrepresents the values.

Forum discussion indicates I am not alone in this observation: https://community.home-assistant.io/t/graph-whats-going-on/325070/8

![image](https://user-images.githubusercontent.com/606945/127174402-a62993a7-eede-4cf2-a989-9398fdbe2bf6.png)

### Describe the behavior you expected

I expect the graph to accurately represent what the actual values were at the indicated times across the X-axis (in my screenshot, at 04:00 AM the value is 76 but graph shows 74.5).

### Steps to reproduce the issue

1. Create some input_numbers
2. Set them to different values over time
3. Observe the history graph
...

### What version of Home Assistant Core has the issue?

core-2021.7.4

### In which browser are you experiencing the issue with?

Firefox 90.0.2; Chromium 92.0.4515.107 

### Which operating system are you using to run this browser?

Linux Mint 20

### Additional information

It looks like some sort of over-smoothing is being applied to the graph but is creating a new problem of mis-representing the values and when they changed.

**Comment by GirzzlyAK** [comment]
I have a similar issue with Counters in that the graph does not represent a Step Change, but a slope from last change to latest change (see image). Appears to be smoothing when it is not appropriate
![Capture](https://user-images.githubusercontent.com/4411963/134609736-849eab89-7be3-4fc1-b13d-2aa47afbc2c5.JPG)
.

**Comment by GrizzlyAK** [comment]
Still an issue. numbers should be plotted more like temperature brightness, etc., not smoothed like this is.

**Comment by mmiller7** [comment]
> Still an issue. numbers should be plotted more like temperature brightness, etc., not smoothed like this is.

Looks like at least for my input_number fields its now fixed, though I don't know if that applies to all the other data-types as you found at least one other case it was broken.

**Comment by ildar170975** [comment]
AFAIK this is not just about a "snooth".
I guess that the whole card is based on interpolating value dependingly on `points_per_hour` option.
If your `input_number` is changed 4 times an hour and `points_per_hour: 1` - what do you expect to see?
Set a higher value of `points_per_hour` (like `60`).

**Comment by GrizzlyAK** [comment]
The Counter issue I reported 2 mo ago, is no ow resolved.
