### ISSUE TITLE
Surecare petflap battery level incorrectly reported

### ISSUE THREAD

**Issue by ptyers** [home-assistant/frontend#9650]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Battery level seems to be incorrectly reported - divided by 4 ?

### Describe the behavior you expected

Battery level appears to be reported at about 25% of value

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.7.4

### State of relevant entities

```txt
sensor.pet_flap_front_door_battery_level
Pet_flap Front door Battery Level
24
```

**Comment by zsarnett** [comment]
This sounds like an issue with the integration. If its a core integration please create an issue in the core repo
