### ISSUE TITLE
Too many digits after the dot on energy dashboard

### ISSUE THREAD

**Issue by bessarabov** [home-assistant/frontend#9652]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Here is the screenshot of the new energy dashboard — in many places I see numbers with a lot of digits after the dot.

![Screen Shot 2021-07-30 at 14 40 57](https://user-images.githubusercontent.com/47263/127648509-7b4a33fd-3439-4ac0-8013-e292dfaeab2a.png)

### Describe the behavior you expected

I expect to see maximum 2 numbers after the dot.

### Steps to reproduce the issue

1. Use the latest beta of HA
2. Finish the master for the energy dashboard
3. Wait for some time
4. Get this behaviour

### What version of Home Assistant Core has the issue?

	core-2021.8.0b4

### In which browser are you experiencing the issue with?

Google Chrome 92.0.4515.107 (WebKit 537.36); Safari 14.1 (WebKit 605.1.15)

### Which operating system are you using to run this browser?

macOS BIg Sur 11.4 (20F71)

**Comment by bramkragten** [comment]
What is your number format setting?

**Comment by bessarabov** [comment]
> What is your number format setting?

It was "None". Setting any other value to the number format fixes the problem.

I always had "None" for the number format (since it has appeared) and I had no problem in other parts of the Home Assistant.

**Comment by bramkragten** [comment]
Not saying it is not an issue 🙂 we should still round even when not formatting.
