### ISSUE TITLE
Energy - Beta Release - Device's Total consumption is showed incorrectly

### ISSUE THREAD

**Issue by SeLLeRoNe** [home-assistant/frontend#9657]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I've setup a fairly simple amount of devices to test the new Energy integration and when I added the single devices, I was prompted only with the "Total" kWh ones (All Tasmota devices).
I've been told that's okay, so the issue I am now facing seems to be somehow visualization, all the devices but one report negative values (attached screenshot).
![image](https://user-images.githubusercontent.com/9599441/127680771-1e7d3167-2f5c-494b-8cea-281c52dd591a.png)

Here you can see one of the entities that I used (the one with the higher negative value):
![image](https://user-images.githubusercontent.com/9599441/127681214-6722b456-3d88-4911-9148-21f8026cc206.png)

If you need further information/screenshots/data just let me know

### Describe the behavior you expected

To have the data visualized correctly :)

### Steps to reproduce the issue

Not really sure, I simply used one of those Tasmota devices discovered by the Tasmota integration.

### What version of Home Assistant Core has the issue?

core-2021.8.0b4

### What was the last working version of Home Assistant Core?

N/A

### In which browser are you experiencing the issue with?

Chrome and Firefox

### Which operating system are you using to run this browser?

Windows 10

### Javascript errors shown in your browser console/inspector

```txt
None
```

**Comment by bramkragten** [comment]
You statistics data is wrong probably. Are these entities always increasing? Never reset?

**Comment by SeLLeRoNe** [comment]
Those are all tasmota to the latest version.
Yes, the Total entity supposively it's always going up, as it is a total kWh used with the device.
I was of the idea that the Daily sensor is the one to use (which is the one I use with the utility_meters), but @frenck confirmed that the "Total" one is the one to use and that HA would handle it.
Based on his check the attributes on the sensor were correct, but still I got this odd issue.. I was told this was most likely a frontend issue, that's why I opened the ticket here.

Is there anything more that I could possibly provide to help debug/fix this strange behaviour?

Here a screenshot of when I try to add a device, just to show that only the "Total" one are appearing and none of the "Today" ones:

![image](https://user-images.githubusercontent.com/9599441/127734103-7e6adece-d7c2-4efb-a176-f4e73e11731b.png)

And this is how the "Today" sensor look:
![image](https://user-images.githubusercontent.com/9599441/127734118-90f87454-9f96-4a54-bd6a-dfd35f5c514a.png)

**Comment by bramkragten** [comment]
Please provide the statisticus data for 1 of the wrong entities

**Comment by SeLLeRoNe** [comment]
Sorry where do I get those?

**Comment by SeLLeRoNe** [comment]
Just one update, something has happened since last release (not really sure it was the release tho)

![image](https://user-images.githubusercontent.com/9599441/127900285-e377f977-3692-4ede-b61d-8f68fa17f949.png)

Some have started to go on "positive".

Here the info I have for one that didn't get magically fixed :)
![image](https://user-images.githubusercontent.com/9599441/127900374-98ace447-1e86-4a3e-bbbb-d7fd8f898761.png)

One more thing that might need a minor fix is that "0" shouldn't be a negative value ^^
![image](https://user-images.githubusercontent.com/9599441/127900472-90451bde-e37d-43bf-8a15-65fd6a8af76e.png)

Thanks :)

**Comment by SeLLeRoNe** [comment]
I've found the reason of the issue.
I had an automation that at midnight was sending out an MQTT message to my Tasmota devices to run a "EnergyReset" command.

That was causing values to become negative somehow, not sure why and how tbh, but removing that automation (that was there before I started using the Tasmota Integration within HA) fixed the issue.

**Comment by bramkragten** [comment]
If it is reset, last reset should be set with the time of reset
