### ISSUE TITLE
Energy integration - beta release - wrong calculations for exported energy

### ISSUE THREAD

**Issue by alexdelprete** [home-assistant/frontend#9661]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Like discussed on discord (#devs_energy), there's something wrong with the calculations of exported energy, it shows a negative value, represented as a cost, for energy exported to the grid.

Here's an example:

![image](https://user-images.githubusercontent.com/7027842/127719826-51680664-cbb6-43eb-888f-5558c9574f95.png)

Here's the configuration of the value per kWh:

![image](https://user-images.githubusercontent.com/7027842/127719852-85b81a93-e655-42a5-ac80-cbc02cbfa49d.png)

### Describe the behavior you expected

I expect that the value for exported energy is represented as a positive one, and not as a cost, but as a credit.

### Steps to reproduce the issue

1. Configure the tariff for exported energy
2. Monitor the daily production/usage
3. Look at the summary table
...

### What version of Home Assistant Core has the issue?

core-2021.8.0b4

**Comment by bramkragten** [comment]
Fixed in latest beta
