### ISSUE TITLE
Add JSON.stringify/print actual msg when showing error message

### ISSUE THREAD

**Issue by wsdt** [home-assistant/frontend#9664]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

An error message `[JsonObject]` is printed.

### Describe the behavior you expected

A human readable error message.

### Steps to reproduce the issue

1. Add a non-existent integration/sensor into the configuration.yaml (other errors might be sufficient as well) via the File-Editor and click on save.
2. Try to restart Hass via File-Editor Add-On. 

### What version of Home Assistant Core has the issue?

core-2021.7.4

### In which browser are you experiencing the issue with?

Chromium (Brave)

### Which operating system are you using to run this browser?

Windows 10

**Comment by ludeeus** [comment]
This is not controlled by this repo, the add-on wraps <https://github.com/danielperna84/hass-configurator> I suggest you raise this in that repo :+1:
