### ISSUE TITLE
Workday sensor

### ISSUE THREAD

**Issue by tomsruk** [home-assistant/frontend#9682]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

My alarm failed to go off this morning due to workday showing as “off”. Why? I’m in the UK, but more specifically England.

Scotland does have a bank holiday today but England doesn’t. England doesn’t have its own country code though.

Can this be fixed?

### Describe the behavior you expected

I expected that today, Workday should be 'on'.

### Steps to reproduce the issue

Set Workday integration to 'UK'

### What version of Home Assistant Core has the issue?

2021.7.3

**Comment by frenck** [comment]
This is not a frontend issue, please report integration issues here:

<https://github.com/home-assistant/core/issues>

(as to which I've redirected you earlier today as well).


Thanks! 👍
