### ISSUE TITLE
On core-2021.7.4 the problem is still there, is going to be solved in the next releases?

### ISSUE THREAD

**Issue by Stefano0042** [home-assistant/frontend#9693]
On core-2021.7.4 the problem is still there, is going to be solved in the next releases?

```yaml
type: entities
title: example
entities:
  - type: button
```

Configuration errors detected:
Required key "entities.2.entity" is missing.
Required key "entities.2.name" is missing.
Required key "entities.2.tap_action" is missing.
Required key "entities.2.tap_action" is missing.
Required key "entities.2.tap_action" is missing.
Required key "entities.2.tap_action" is missing.
Required key "entities.2.tap_action" is missing.
Required key "entities.2.view" is missing.
Required key "entities.2.view" is missing.
Required key "entities.2.view" is missing.
Required key "entities.2.conditions" is missing.
Required key "entities.2.url" is missing.
Required key "entities.2.entities" is missing.
Required key "entities.2.entity" is missing.
Required key "entities.2.attribute" is missing.
Required key "entities.2.name" is missing.
Required key "entities.2.service" is missing.
Required key "entities.2.name" is missing.
Required key "entities.2.text" is missing.

_Originally posted by @Stefano0042 in https://github.com/home-assistant/frontend/issues/9436#issuecomment-890338281_

**Comment by bramkragten** [comment]
Please follow the issue template.
