### ISSUE TITLE
Missing translation/label for new "Energy" settings item

### ISSUE THREAD

**Issue by myxor** [home-assistant/frontend#9708]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When opening settings the new settings item for "Energy" is shown as

> [%key:ui::panel::config::energy::caption%]

![image](https://user-images.githubusercontent.com/1397377/128171747-fe3406e3-2832-4125-bd23-76b58b73c6ac.png)

### Describe the behavior you expected

Expecting it to be called "Energy"

### Steps to reproduce the issue

1. Update to 2021.8.0
2. Open settings
3. Scroll down to "NFC Tags" and look at item below it
...

### What version of Home Assistant Core has the issue?

2021.8.0

### In which browser are you experiencing the issue with?

Firefox 90.0.2

### Which operating system are you using to run this browser?

Ubuntu 20.04

**Comment by Syntoxr** [comment]
Can confirm this bug

**Comment by bramkragten** [comment]
You can fix this yourself: <https://developers.home-assistant.io/docs/translations>

We don't track translations in the frontend repo.

**Comment by bramkragten** [comment]
(Fixed this one in localize now)
