### ISSUE TITLE
Dialog boxes truncated (iOS)

### ISSUE THREAD

**Issue by pedolsky** [home-assistant/frontend#9716]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Dropdown selection is not possible because the collapsed list is truncated, see attached images. 

![54869FB2-1856-4411-92E1-1B27F748C456](https://user-images.githubusercontent.com/71203830/128241762-d27e748c-62f3-4a4a-a90d-6ed48f72875f.jpeg)
![502399E3-2D86-4CE2-9D09-256E12A6D7E8](https://user-images.githubusercontent.com/71203830/128241776-ea7bb6f5-c4cb-467b-8dcb-e92566d79984.jpeg)

### Describe the behavior you expected

Completely collapsed dropdown lists

### Steps to reproduce the issue

1. Open a dropdown in any lovelace card (ui and yaml) or in editor mode in ui dashboard 
2. Try to select an item in the dropdown list 

...

### What version of Home Assistant Core has the issue?

core-2022.7.5

### In which browser are you experiencing the issue with?

Chrome 103.0.5060.63, Safari 15.5

### Which operating system are you using to run this browser?

iPadOS 15.5

**Comment by organicaudio** [comment]
I'm pretty sure this is related to the updates to Safari & WebKit in iOS 15. 

I've got a few other web-ui based systems running that are showing similar symptoms where drop down menus no longer extend beyond the limits of whatever box their in. 

It impacts both Safari and Chrome on iOS because they both use WebKit. 

**Safari browser user agent running iOS 15 beta 4:**
```
Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Mobile/15E148 Safari/604.1
```

**Chrome browser user agent running iOS 15 beta 4:**
```
Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/92.0.4515.90 Mobile/15E148 Safari/604.1
```

Apple still has a long way to go with Safari / WebKit before it's ready for GM (I can't even use the preview tab in this comment box right now)

**Comment by pedolsky** [comment]
Thanks for your reply. Alas, the issue appeared before Apple's 15.

**Comment by pedolsky** [comment]
^

**Comment by pedolsky** [comment]
^

**Comment by pedolsky** [comment]
Updated to 2021.8 - context menus still cropped. Some examples: 

![C1B1004D-2D1D-44F0-86FE-88B8408958BF](https://user-images.githubusercontent.com/71203830/148521354-906ba3fa-9061-48d1-ae7c-e2ae693485cd.jpeg)
![CEE42EEA-95E9-4332-BD56-60525CDE686F](https://user-images.githubusercontent.com/71203830/148521358-016ab34b-ff7d-4192-bf39-2ae3536ed873.jpeg)

**Comment by pedolsky** [comment]
Now things become really bad, can't configure integrations:

![835ED357-EBA1-4000-B441-0C7061029FAD](https://user-images.githubusercontent.com/71203830/150102211-564c2f78-b1ba-4fb9-b8c4-9439ac7179b9.jpeg)

**Comment by Mariusthvdb** [comment]
also see https://github.com/home-assistant/frontend/issues/9416 which is identical issue?

**Comment by pedolsky** [comment]
Yes, it's corresponding. So annoying.

**Comment by Mariusthvdb** [comment]
see what Bram wrote: https://github.com/home-assistant/frontend/issues/9416#issuecomment-1030897957

**Comment by pedolsky** [comment]
up

**Comment by pedolsky** [comment]
Problem persists.

**Comment by pedolsky** [comment]
This issue is not solved.

**Comment by pedolsky** [comment]
up

**Comment by pedolsky** [comment]
Finally, everything is working since 2023.2 beta. I still want to wait for the stable release before closing this issue.
