### ISSUE TITLE
Statistics card bar chart should plot differences in data at period start and end and not sum

### ISSUE THREAD

**Issue by wigster** [home-assistant/frontend#9720]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The new bar chart in the statistics card plots the value of accumulating sensors, e.g. my coffee machine's total energy use, directly. This means that I get an endlessly increasing set of bars which in the end do not make it easy to extract any interesting information.

To me this bar chart seems to be fundamentally broken in the case of accumulating sensors, which are the only ones that make sense to be plotted on such a chart, so I am filing this as an issue instead of a feature request.

### Describe the behavior you expected

For such accumulating sensors, I would like to be able to see the difference in the sensor values over whatever the period the statistics card has chosen to represent as a bar -- e..g if there is one bar per day, that bar should show the amount of energy that has been used by the coffee machine over that day. 

Ideally, the duration of the period represented by a bar would actually be user-controlled, but I guess this is more of a feature request.

As an alternative, one could achieve this by an automation which would reset the accumulating sensor's value on a regular basis, e.g. once a day or once a month. But then the bar chart would make even less sense if it were the case that the period of the bar chart is not equal to that on which the sensor is being reset.

### Steps to reproduce the issue

1. Create a statistics graph card
2. Add an accumulating sensor statistic and choose bar chart

### What version of Home Assistant Core has the issue?

2021.8.0

### In which browser are you experiencing the issue with?

Microsoft Edge 94

### Which operating system are you using to run this browser?

Windows 10

**Comment by bramkragten** [comment]
This is a feature request for a growth function, not a bug report.
