### ISSUE TITLE
Energy overview over devices looks odd when going forward or backward a day.

### ISSUE THREAD

**Issue by fribse** [home-assistant/frontend#9722]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I open the energy view in HA, it looks correct:
![image](https://user-images.githubusercontent.com/13660621/128333292-5c3f7571-f201-45a8-a066-5ba02fb713eb.png)
But if I go back or forward a day it changes to this:
![image](https://user-images.githubusercontent.com/13660621/128333354-c042cca8-eec0-42b8-a50b-d807f6beae69.png)
When it's showing that, an F5 is required to get the view back correctly.

### Describe the behavior you expected

I expect it to show the days correctly, even after going back and forth, or going to today

### Steps to reproduce the issue

1. Open the energy view
2. Go back a day, problem
3. Go to today, problem

### What version of Home Assistant Core has the issue?

core-2021.8.1

### What was the last working version of Home Assistant Core?

None

### In which browser are you experiencing the issue with?

Firefox 90.0.2, Chrome 92.0.4515.131

### Which operating system are you using to run this browser?

Windows 10

### Javascript errors shown in your browser console/inspector

```txt
The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.

The resource at “https://xxx.ui.nabu.casa/static/fonts/roboto/Roboto-Regular.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly.
```

### Additional information

I'm using a custom theme, but I've also tried with the default theme, no change.

**Comment by fribse** [comment]
Ok, I found out that it does work, it just takes forever to get the graphs showing?
The HA is running on an Intel NUC i5 with a MariaDB in addon for recorder, so performance wise the system is ok.

**Comment by v-alvex** [comment]
![graph](https://user-images.githubusercontent.com/64501737/128580144-26ff8821-6b9a-4527-a0ce-62ec09fd2648.jpg)
Some for me. It never loads by itself.
After clicking anywhere on the graph, the more-info dialog of the clicked entity pops-up, and the graph loads correctly.

**Comment by theetron** [comment]
When using the date buttons, the labels of the individual devices are also gone.

**Comment by pascalwinters** [comment]
Same for me. Screenshot iPhone:

![938BB401-2004-42C8-A638-519DDF662950](https://user-images.githubusercontent.com/69316923/128679367-3a472c66-589b-4467-a6fb-3bd0119a54bf.jpeg)

**Comment by balonchiks** [comment]
i am having the same problem both in Energy tab and when using the lovelace `type: energy-devices-graph` card.

**Comment by bramkragten** [comment]
> Ok, I found out that it does work, it just takes forever to get the graphs showing?
> The HA is running on an Intel NUC i5 with a MariaDB in addon for recorder, so performance wise the system is ok.

Just hovering over the graph will fix it.

**Comment by fribse** [comment]
@bramkragten You are right, that's really strange (looking from the outside, but just placing the cursor over it fixes it...

**Comment by balonchiks** [comment]
unfortunately, it does not fix it for me. the behavior is still the same for "`Monitor individual devices`"

**Comment by bramkragten** [comment]
Did you test that on the dev branch? Because it is not released yet.

**Comment by balonchiks** [comment]
my bad, i somehow thought it's in the latest release. all good, thanks for fixing.
