### ISSUE TITLE
Date format is weird in Norsk Bokmål and Norsk Nynorsk

### ISSUE THREAD

**Issue by sepodele** [home-assistant/frontend#9724]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When selecting Norsk Bokmål or Norsk Nynorsk in profile settings the date format is weird everywhere. Here is a screenshot from Logbook where date is shown as '2021 M08 5 15:00' instead of for instance '5 August 2021, 15:00' (English (GB)).

![image](https://user-images.githubusercontent.com/25592497/128376203-dfd764ce-e3e6-49d7-85a8-d8c9ad513477.png)

### Describe the behavior you expected

I expect it to show something like '5. august 2021, 15:00'. I think it was correct maybe a couple months ago.

### Steps to reproduce the issue

1. Select Norsk Bokmål as language in profile.
2. Go to Logbook and look.
3. ...but a couple of users on Discord could not verify this...

### What version of Home Assistant Core has the issue?

core-2021.8.1

### In which browser are you experiencing the issue with?

Google Chrome 92.0.4515.131 AND Home Assistant app for Android

### Which operating system are you using to run this browser?

Windows 10 / Android 11

**Comment by bramkragten** [comment]
If you run the following in your browser console, what does it return?

```js
new Intl.DateTimeFormat("no", {
      year: "numeric",
      month: "long",
      day: "numeric",
    }).format(new Date())
```

**Comment by sepodele** [comment]
`"2021 M08 6"`. So that means it's browser/PC settings related? I get the same in Edge. But why do I then have the same issue in the Android app?

**Comment by sepodele** [comment]
Could it be this? https://bugs.chromium.org/p/chromium/issues/detail?id=1215606&q=norwegian&can=2

**Comment by bramkragten** [comment]
It isn't an issue with Home Assistant in that case, no.

Probably a bug in chrome, all the browsers you mention are chrome based.

**Comment by sepodele** [comment]
I agree. Thanks!
