### ISSUE TITLE
Using button with variable "icon:" or "entity:" in entities card results in "Configuration errors detected:"

### ISSUE THREAD

**Issue by Stefano0042** [home-assistant/frontend#9729]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

```yaml
type: entities
title: test
entities:
  - type: button
    tap_action:
      action: call-service
      confirmation: true
      service: script.rpi_turn_off
    icon: hass:stop-circle-outline
    entity: script.rpi_turn_off
    name: Quit the system
```

Configuration errors detected:
Required key "entities.0.entity" is missing.
Required key "entities.0.view" is missing.
Required key "entities.0.view" is missing.
Required key "entities.0.view" is missing.
Required key "entities.0.conditions" is missing.
Required key "entities.0.url" is missing.
Required key "entities.0.entities" is missing.
Required key "entities.0.entity" is missing.
Required key "entities.0.attribute" is missing.
Required key "entities.0.service" is missing.
Required key "entities.0.text" is missing.

Visual editor is not supported for this configuration:

Key "entities.0.type" is not expected or not supported by the visual editor.
The provided value for "entities.0" is not supported by the visual editor. We support (string) but received ({"type":"button","tap_action":{"action":"call-service","service":"rest_command.calibration_shelly25_1","confirmation":true},"icon":"hass:arrow-expand-vertical","name":"Calibra"}).
Key "entities.0.icon" is not expected or not supported by the visual editor.
The provided value for "entities.0.type" is not supported by the visual editor. We support (literal) but received ("button").
Key "entities.0.tap_action" is not expected or not supported by the visual editor.
The provided value for "entities.0.type" is not supported by the visual editor. We support (literal) but received ("button").
Key "entities.0.tap_action" is not expected or not supported by the visual editor.
Key "entities.0.icon" is not expected or not supported by the visual editor.
Key "entities.0.name" is not expected or not supported by the visual editor.
The provided value for "entities.0.type" is not supported by the visual editor. We support (literal) but received ("button").
Key "entities.0.tap_action" is not expected or not supported by the visual editor.
Key "entities.0.icon" is not expected or not supported by the visual editor.
Key "entities.0.name" is not expected or not supported by the visual editor.
The provided value for "entities.0.type" is not supported by the visual editor. We support (literal) but received ("button").
Key "entities.0.tap_action" is not expected or not supported by the visual editor.
Key "entities.0.icon" is not expected or not supported by the visual editor.
Key "entities.0.name" is not expected or not supported by the visual editor.
The provided value for "entities.0.type" is not supported by the visual editor. We support (literal) but received ("button").
Key "entities.0.tap_action" is not expected or not supported by the visual editor.
The provided value for "entities.0.type" is not supported by the visual editor. We support (literal) but received ("button").
Key "entities.0.tap_action" is not expected or not supported by the visual editor.
Key "entities.0.icon" is not expected or not supported by the visual editor.
Key "entities.0.name" is not expected or not supported by the visual editor.
The provided value for "entities.0.type" is not supported by the visual editor. We support (literal) but received ("button").
Key "entities.0.tap_action" is not expected or not supported by the visual editor.
Key "entities.0.icon" is not expected or not supported by the visual editor.
The provided value for "entities.0.type" is not supported by the visual editor. We support (literal) but received ("button").
Key "entities.0.tap_action" is not expected or not supported by the visual editor.
The provided value for "entities.0.type" is not supported by the visual editor. We support (literal) but received ("button").
Key "entities.0.tap_action" is not expected or not supported by the visual editor.
The provided value for "entities.0.type" is not supported by the visual editor. We support (custom element type) but received ("button").
You can still edit your config in YAML

### Describe the behavior you expected

During editing/creating a button in an entities card with specific icon: assigned, the editor reports "configuration errors were detected" and will not show the save button when a modification occur.
The card is operationally working fine, it just cannot be saved using the GUI.

### Steps to reproduce the issue

1. Create/edit an entities card
2. Use the type: button in the card
3. Use the icon: variable
4. Use the entity: variable

### What version of Home Assistant Core has the issue?

core-2021.8.0

### What was the last working version of Home Assistant Core?

core-2021.4.

### In which browser are you experiencing the issue with?

Microsoft edge / Companion app

### Which operating system are you using to run this browser?

Windows 10 / iOS

**Comment by ZephireNZ** [comment]
This is the same issue as #9578

**Comment by Stefano0042** [comment]
> This is the same issue as #9578

Hi, I'm not a contributor but it seem that the problem root is of the same type, e.g.  tap_action: in "button:" but not yet  in "buttons" has been solved in PR [Add struct for fire-dom-event action #9556](https://github.com/home-assistant/frontend/pull/9556)
