### ISSUE TITLE
Tesla integration is not working since update to 2021.8.2 2021.06.8

### ISSUE THREAD

**Issue by offlinehoster** [home-assistant/frontend#9733]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After updating to the lastest core-2021.8.2 and supervisor-2021.06.8 the Tesla integration does not seem to be able to login anymore...

```
2021-08-06 13:22:28 WARNING (MainThread) [homeassistant.setup] Setup of tesla is taking over 10 seconds.
2021-08-06 13:22:47 ERROR (MainThread) [homeassistant.components.tesla.config_flow] Authentication error: Unable to login with credentials 
2021-08-06 13:22:47 ERROR (MainThread) [homeassistant.setup] Setup failed for tesla: Integration failed to initialize.
````

### Describe the behavior you expected

I thought it will just work...

### Steps to reproduce the issue

1.Update to the latest version

### What version of Home Assistant Core has the issue?

core-2021.8.2

### What was the last working version of Home Assistant Core?

lower than core-2021.8.2

### In which browser are you experiencing the issue with?

Firefox

### Which operating system are you using to run this browser?

Archlinux

### Javascript errors shown in your browser console/inspector

```txt
no errors
```

### Additional information

I already removed the config details from configuration.yaml and fill it back in...no change.

**Comment by paracetamol32** [comment]
Same here

**Comment by offlinehoster** [comment]
I also deactivated the config for the Tesla plugin. Added again, no change. Login with this Credentials to the Tesla Website is working fine from a regular PC.

![Bildschirmfoto von 2021-08-06 16-06-00](https://user-images.githubusercontent.com/1618359/128523048-75b9ce39-4dab-4e73-ba24-6228169ac257.png)
![Bildschirmfoto von 2021-08-06 16-06-08](https://user-images.githubusercontent.com/1618359/128523050-666cb435-7869-4159-88fd-90555e4d5f80.png)
![Bildschirmfoto von 2021-08-06 16-05-49](https://user-images.githubusercontent.com/1618359/128523052-8a4d06de-952e-4293-9e53-a0763dc44934.png)

**Comment by paracetamol32** [comment]
i have restored snapshoot Home Assistant 2021.7.4 and problem persist

**Comment by paracetamol32** [comment]
It's not a version problem : https://github.com/home-assistant/core/issues/51243

**Comment by balloob** [comment]
Please see https://github.com/home-assistant/core/issues/51243. This is the frontend repo and does not deal with integrations.
