### ISSUE TITLE
Energy dashboard: cost displayed as -0

### ISSUE THREAD

**Issue by gigatexel** [home-assistant/frontend#9740]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When there is no infeed to the grid, the "cost" (which is actually an income/revenue) for production-related sources in the energy dashboard is displayed as "-0 euro" instead of "0 euro"

### Describe the behavior you expected

I would expect the cost (or more correctly: revenue/income) be displayed as "0"

### Steps to reproduce the issue

1. Observe the dashboard early in the morning, when there is no infeed to the grid.

### What version of Home Assistant Core has the issue?

core-2021.8.2

**Comment by bramkragten** [comment]
This is as intended. Costs are positive, compensation negative, so we can calc your net costs
