### ISSUE TITLE
Gauge background colour (severity) not showing in negative values when needle is turned on

### ISSUE THREAD

**Issue by derekcfoley** [home-assistant/frontend#9741]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

My home energy monitor (Aeotec Home Energy Monitor Gen 5) reports its values in positives (when my system puts power onto the grid), and negative when it uses grid power.

Previously I simulated a centred guage by setting the min to -10,000 and max to 10,000, so if the needle goes right it means I'm generating solar and if it goes left into "the red" I know I'm using grid power.

Obviously I was excited to finally see a proper needle gauge implementation now in core-2021.8.3

However, although it works functionally, the colour background defining severity now doesn't work when the "needle" is turned on (see before and after screenshots)

### Describe the behavior you expected

The negative part of the guage should have the defined colour severity in minus values.

### Steps to reproduce the issue

1. create a gauge (non needle)
2. define minimum to -10000 and max to 10000
3. set severity so red is a negative, green is a positive
4. insert data for positve and negatives.
5. observe gauge reaction
6. turn on "needle"
7. repeat 4 & 5
...

![image](https://user-images.githubusercontent.com/25664126/128599746-691e6f75-8be8-407b-afa1-098314aca3f8.png)

![negative and positive gauge](https://user-images.githubusercontent.com/25664126/128599576-e3c282fe-e628-4c3c-bfe3-b5ad00e10d78.jpg)

![needle and negatives](https://user-images.githubusercontent.com/25664126/128599580-c7f04d14-3c73-4b97-8ab8-d5a57bf09ee3.jpg)

![image](https://user-images.githubusercontent.com/25664126/128599641-f4e4e0a0-f86c-4d88-b23e-3b02348e2723.png)

### What version of Home Assistant Core has the issue?

core-2021.8.3

### Which operating system are you using to run this browser?

Windows 8.1

### State of relevant entities

```txt
(see screencap above)
```

**Comment by OptimusGREEN** [comment]
was just about to report this. Its not just negative values, its anything prior to where 'green' starts.

**Comment by bramkragten** [comment]
> was just about to report this. Its not just negative values, its anything prior to where 'green' starts.

That is fixes already, so if this is the same, this can be closed

**Comment by OptimusGREEN** [comment]
![Screenshot_20210815-175616_Home Assistant](https://user-images.githubusercontent.com/17599575/129486285-ca87e298-bfba-4e32-86c9-5eed4f83ec8c.jpg)
Still the same.

**Comment by bramkragten** [comment]
Fixed isn't the same as released, it is in dev atm

**Comment by OptimusGREEN** [comment]
you never mentioned that it was only fixed in dev, hence my reply. glad its fixed in dev though, however I don't believe this can be closed until its fixed in the release as thats what the majority of people use.

**Comment by bramkragten** [comment]
That's not how an issues tracker works :-)
