### ISSUE TITLE
Cannot configure Energy Monitor

### ISSUE THREAD

**Issue by vekexasia** [home-assistant/frontend#9747]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Energy configuration panel does not work. The dropdown prompts some sensors but clicking on any of the presented items results in no action

### Describe the behavior you expected

To let me select. Also writing is disallowed it seems.

### Steps to reproduce the issue

1. Start configuring Energy
2. Open dropdown for solar (for example)
3. Try to select any item from the list.
...

### What version of Home Assistant Core has the issue?

core-2021.8.4

### In which browser are you experiencing the issue with?

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
.
```

### Problem-relevant frontend configuration

```yaml
.
```

### Javascript errors shown in your browser console/inspector

```txt
no errors
```

### Additional information

-

**Comment by bramkragten** [comment]
Not able to reproduce, can you share a screenshot?
