### ISSUE TITLE
Self consumed solar energy above 100%

### ISSUE THREAD

**Issue by gigatexel** [home-assistant/frontend#9754]
### The problem

Early in each day, the "Self consumed solar energy" is above 100%.
As the day passes on, this normalises to plausible values.

### What is version of Home Assistant Core has the issue?

core-2021.8.2

### What was the last working version of Home Assistant Core?

N/A

### What type of installation are you running?

Home Assistant Supervised

### Integration causing the issue

energy

**Comment by gigatexel** [comment]
I tried removing Energy Production (tarif 2) but without result.

I think there is something wrong with the individual energy counters that calculate the daily energy. They have small values while they should absolutely be 0.

For example: tarif 1 is never active at night, but still has a small value in HA Energy dashboard.

**Comment by gigatexel** [comment]
![image](https://user-images.githubusercontent.com/65073191/128819674-ac17af12-5db4-4086-9ff4-7720d9e5fac8.png)
See image. Can never be >0kWh because there is no infeed today untill this moment of the day.

**Comment by bramkragten** [comment]
Production should be shown as negative, are your sensors correct?

**Comment by gigatexel** [comment]
![image](https://user-images.githubusercontent.com/65073191/128869685-aed9e3f8-c9c6-4303-8e21-f5681be8ca8e.png)
![image](https://user-images.githubusercontent.com/65073191/128869709-9cadbce4-8c93-47aa-8b1e-dd6eb5e5ce98.png)

The sensors are the ones provided by the DSMR integration.

**Comment by bramkragten** [comment]
This one? <https://www.home-assistant.io/integrations/dsmr/> or the dsmr reader <https://www.home-assistant.io/integrations/dsmr_reader/> integration?

The first one should work, am using it myself...

**Comment by gigatexel** [comment]
Removing/adding the production-entities, waiting for the next day, has fixed this.

**Comment by gigatexel** [comment]
@bramkragten still not reporting well atm

Production-day register is postive, which is not possible according to your feedback.
Using this integration: https://www.home-assistant.io/integrations/dsmr

![image](https://user-images.githubusercontent.com/65073191/129316541-1fce2750-6a8c-46e0-9266-5b8c47abbd85.png)

**Comment by gigatexel** [comment]
This is the sensor value at midnight and now. So no idea why Energy dashboard is displaying 0,03kWh

![image](https://user-images.githubusercontent.com/65073191/129323818-ef739c57-40e3-48aa-a54a-9067ed9d83c9.png)
![image](https://user-images.githubusercontent.com/65073191/129323880-f5bb95f8-a00e-4a82-ba10-9428f3ef5497.png)

**Comment by gigatexel** [comment]
![BD43CFD9-E081-4D5C-A2B4-CE647EE75532](https://user-images.githubusercontent.com/65073191/129435731-d3125638-4a2e-4905-8b4a-e1bd24ebd2cb.png)

now even negative :-/

**Comment by bramkragten** [comment]
Your sensors are wrong, this has nothing to do with the frontend.

**Comment by gigatexel** [comment]
@bramkragten i don’t get it. What is wrong with the raw sensor data I posted? The energy-delta is clearly zero but dashboard reports 0,3kWh

**Comment by bramkragten** [comment]
Because it uses a different data source, and your entity probably just isn't set up correctly.

**Comment by gigatexel** [comment]
@bramkragten I'm trying to document this as thouroughly as possible, since I no longer know where to look.

The "Production Day" entity is provided by the DSMR Slimme Meter integration as entity-id `sensor.energy_production_tarif_1`
Besides the global parameter regarding the update interval (5s) and the country code (5B), there is no configuration possible for this integration.

![image](https://user-images.githubusercontent.com/65073191/129518216-3e537019-f39d-4cbf-998c-208b3bf6d9cb.png)

On the Energy dashboard, this is the exact same sensor that is configured:

![image](https://user-images.githubusercontent.com/65073191/129518406-f159b1bb-2bc7-4bb5-92cb-c35dd8f19085.png)

I am using MySQL-AddOn as HA Backend.
Looking at the first and last record of today, the raw value in the DB is identical.

Query:
```
(SELECT entity_id, state, attributes, created FROM `states` WHERE DATE(`created`) = CURDATE() AND entity_id = 'sensor.energy_production_tarif_1' order by created ASC LIMIT 1)
UNION
(SELECT entity_id, state, attributes, created FROM `states` WHERE DATE(`created`) = CURDATE() AND entity_id = 'sensor.energy_production_tarif_1' order by created DESC LIMIT 1)
```

Result:
![image](https://user-images.githubusercontent.com/65073191/129519713-9e7518b2-fa8a-4a88-a916-d012dcb0e406.png)

So I dont think the entity itself is behaving wrong.

Furthermore, the `statistics_meta` reports `sensor.energy_production_tarif_1` as having ID 5

![image](https://user-images.githubusercontent.com/65073191/129519951-8eba3388-fc47-464a-b99b-c5ceb2c1706b.png)

Fetching data from `statistics` table:
```
SELECT * FROM `statistics` WHERE metadata_id = '5'  and date(`created`) = curdate()
ORDER BY `statistics`.`start` DESC;
```

Gives us: 
![image](https://user-images.githubusercontent.com/65073191/129520955-d3e55574-54ea-4066-af2f-45481d733aed.png)


So to conclude, looking at the sum-column, I shoud open a bug for statistics?

**Comment by bramkragten** [comment]
If you believe the statistics are wrong, create an issue in the core repo for that.
