### ISSUE TITLE
Statistics Graph card does not render neagtive values

### ISSUE THREAD

**Issue by andre-richter** [home-assistant/frontend#9772]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

For sensors that can report positive and negative values (or negative only), it seems that the statistics graph card doesn't render for periods where the mean is negative.

### Describe the behavior you expected

That it works with sensors reporting negative values.

### Steps to reproduce the issue

1. Have a sensor that can report positive and negative values.
2. Have a period where for an hour, the mean of the sensor values is negative.
3. Observe the statistics graph card not rendering the negative mean/min/max.

### What version of Home Assistant Core has the issue?

core-2021.8.5

### In which browser are you experiencing the issue with?

Firefox 90

### Which operating system are you using to run this browser?

Windows 10

**Comment by fancygaphtrn** [comment]
I find the same for the guage card.   Running 2021.8.6

**Comment by andre-richter** [comment]
Gauge card works for me if you set the optional minimum value to negative

**Comment by asturale** [comment]
Sensors with only negative values (freezer temp in my case) don't show at all.

**Comment by bramkragten** [comment]
This seems to be core issue, looks like statistics are only generated for positive values.

**Comment by bramkragten** [comment]
Fixed in https://github.com/home-assistant/core/pull/55708
