### ISSUE TITLE
Inconsistent delete vs remove entity terminology

### ISSUE THREAD

**Issue by scop** [home-assistant/frontend#9773]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The entities list uses the term "REMOVE SELECTED" for the button for removing selected entities, and also consistently "remove" in the confirmation dialog.

But the dialog showing data for a single entity uses "DELETE" as the button name, and "Are you sure you want to delete this entry?" in the confirmation.

### Describe the behavior you expected

Both would use the term remove, or both would use delete, but not a mixture.

### Steps to reproduce the issue

1. Open the entities list, see the "remove selected", button, select some entities and click the button to see the confirmation
2. Open a single entity from the list, see the "delete" button, click it to see the confirmation
3.
...

### What version of Home Assistant Core has the issue?

 core-2021.9.0.dev0

**Comment by scop** [comment]
Also, the confirmation text for entity removal would be better as "Are you sure you want to delete this entity?", not "... entry?".

**Comment by matthiasdebaat** [comment]
We follow the [Material Design guidelines](https://developers.home-assistant.io/docs/translations#rules), but can't find a glossary or other kind of word list. Just checked Gmail and they used `Delete`, what I also think is the best. So great find @scop, let's change it to `Delete`.

**Comment by matthiasdebaat** [comment]
> Also, the confirmation text for entity removal would be better as "Are you sure you want to delete this entity?", not "... entry?".

The title is a [brief and clear question](https://material.io/components/dialogs#anatomy), but should changed to `Delete`. 

<img width="617" alt="Schermafbeelding 2021-08-11 om 10 04 42" src="https://user-images.githubusercontent.com/20203284/128993127-61a12e16-53a3-4c0b-b7a5-dc2457207ef3.png">

**Comment by scop** [comment]
By the additional thing I meant the confirmation that pops up when one clicks "DELETE" from the dialog showing a single entity:
![Screenshot from 2021-08-11 12-34-59](https://user-images.githubusercontent.com/109152/129006459-e343f0e3-c509-4760-b7f8-e7116602f0ba.png)

("delete" there is fine, but it would be better to say "entity" instead of "entry". But maybe this is a generic dialog that lacks context to show more specific info, dunno.)

**Comment by scop** [comment]
Would not hurt to sync the instructions from the multiple delete dialog to this one too, if doable.

**Comment by spacegaier** [comment]
@matthiasdebaat Can you please weigh in on my comment here https://github.com/home-assistant/frontend/pull/13159#issuecomment-1236086373 that is related to this issue.

**Comment by matthiasdebaat** [comment]
We should follow the guidelines of this is [great article](https://uxmag.com/articles/ui-copy-remove-vs-delete2-banner) about Delete vs. Remove. In our case it would be, for example:

- Helper entities are created by a user and can be deleted from existence.
- Device entities are part of a devices, that can only be removed from Home Assistant.

It's is maybe to complex to add this logic to Home Assistant.
 **I would suggest to use remove entity, because that is the most common.**

(btw, I've also added some guidelines about dialogs on our [Design website ](https://design.home-assistant.io/#components/dialogs), will add some guidelines about Delete vs. Remove too.)
