### ISSUE TITLE
No documentation regarding color codes for template editor

### ISSUE THREAD

**Issue by Spirituss** [home-assistant/frontend#9776]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

There is a lot of color codes in HA themes that can modify UI of HA and lovelace. But I didn't find any information in official HA documentation regarding color codes that can modify HA code colouring in template editor. Thus, for example, for dark themes the code becomes unreadable:
<img width="650" alt="Снимок экрана 2021-08-11 в 12 49 06" src="https://user-images.githubusercontent.com/47206760/128990761-80c00e0b-c8cc-4dfd-acca-59d1e9de4c6c.png">

### Describe the behavior you expected

Please, update HA documentation with relevant color codes for all code key word types.

### Steps to reproduce the issue

1. Set dark theme of HA.
2. Open HA template editor.

### What version of Home Assistant Core has the issue?

core-2021.8.2

### In which browser are you experiencing the issue with?

Chrome, Opera

### Which operating system are you using to run this browser?

macOS Catalina

**Comment by bramkragten** [comment]
This is not a bug of the frontend, but belongs on the documentation branch.

You can find the different vars here: <https://github.com/home-assistant/frontend/blob/dev/src/resources/styles.ts#L16-L33>

**Comment by Spirituss** [comment]
Thanks! it works.
