### ISSUE TITLE
Statistics Graph Card does not show data for non-administrator users

### ISSUE THREAD

**Issue by github-0** [home-assistant/frontend#9792]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When viewing the card in Lovelace UI as a user without administrator rights, an empty graph is shown. When the user is granted administrator rights the graph is shown populated with data. 

With admin-rights:
![ha_1](https://user-images.githubusercontent.com/6333614/129262164-fa4faffd-bd9f-41a6-a916-21f9370e7553.png)
![ha_1_admin](https://user-images.githubusercontent.com/6333614/129262611-25456684-4ec0-4d68-bc33-d9a77730a65f.png)

Without:
![ha_2](https://user-images.githubusercontent.com/6333614/129262175-6378f521-de3e-42c9-ad5a-39af5a08ac8b.png)
![ha_2_user](https://user-images.githubusercontent.com/6333614/129262635-b044827e-cc3f-42fd-8b4a-a4c6a06ff435.png)

### Describe the behavior you expected

Graph should be shown the same way regardless of user rights.

### Steps to reproduce the issue

1. Create Statistics Graph Card with data as shown.
2. Create new user without admin rights.
3. View the graph as the new user.

### What version of Home Assistant Core has the issue?

core-2021.8.6

### In which browser are you experiencing the issue with?

Home Assistant Android app, Chrome on Android, Brave on Ubuntu

### Problem-relevant frontend configuration

```yaml
type: statistics-graph
entities:
  - sensor.000005a21cbc
  - sensor.000005a256c6
  - sensor.000005d27e1e
days_to_show: 30
stat_types:
  - mean
chart_type: line
```

### Additional information

This line is created on Core log when viewing the card:
2021-08-12 21:42:39 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140510020898288] Error handling message: Unauthorized

**Comment by ludeeus** [comment]
This is not a bug, this is by design, the history integration does not allow non-admins to get the data.
For feature requests please raise those on [the forums](https://community.home-assistant.io/c/feature-requests/13) thanks :+1:

**Comment by github-0** [comment]
> This is not a bug, this is by design, the history integration does not allow non-admins to get the data.

This is probably just me not understanding the inner workings well enough, but is this really the case since non-admins can access history data from the History menu? 

![history](https://user-images.githubusercontent.com/6333614/129475549-5103e62c-3ec0-4623-9429-635eab9e1cd8.png)

**Comment by ludeeus** [comment]
I don't understand it myself really, a feature request for it would be great :+1:

**Comment by github-0** [comment]
FR [here](https://community.home-assistant.io/t/statistics-graph-should-be-visible-to-non-admin-users/330114). Thanks for the prompt reply!
