### ISSUE TITLE
default overview lovelace dashboard is empty

### ISSUE THREAD

**Issue by rcremasco** [home-assistant/frontend#9821]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

after latest docker (homeassistant/raspberrypi3-homeassistant) upgrade the defaul lovelace overview page contains only 1 card with following text:

Error loading the view strategy:

[object Object]

![ha](https://user-images.githubusercontent.com/20765598/129481449-f674e2b9-b9e1-4549-9f66-879ffe18cb34.jpg)

other custom dashboards are fine

### Describe the behavior you expected

i should see all discovered entities

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.9.0.dev20210815

### Additional information

i have alredy tryed ti remove all lovelace* file from .storage with no changes in behavior
tryed also to set:

lovelace:
  mode: storage 

and 

lovelace:
  mode: yaml

with no success.

**Comment by bramkragten** [comment]
You are using a development version of Home Assistant, is that intentional? Doesn't sound like that. You should probably stick to the stable versions.

**Comment by rcremasco** [comment]
i clicked on configuration -> Info -> integrations panel -> lovelace - issue link
to start this thread.
anyway i think is a dev version
