### ISSUE TITLE
Logbook reload button

### ISSUE THREAD

**Issue by matthiasdebaat** [home-assistant/frontend#9828]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On the top right there's a reload button. 
![Logbook reload](https://user-images.githubusercontent.com/20203284/129553162-3a52c903-f53a-4f7e-ac9d-e32d7c263a05.png)

### Describe the behavior you expected

Why does the logbook page need a reload button? Other pages doesn't have it and a browser already got a reload button. I think it should be removed.

### Steps to reproduce the issue

1. Open Logbook

### What version of Home Assistant Core has the issue?

core-2021.8.5

**Comment by ludeeus** [comment]
If you reload the browser, you loose your inputs

**Comment by matthiasdebaat** [comment]
Why and when do you want to press the reload button? Does that also apply to 'History'?

**Comment by ludeeus** [comment]
You want to click that when you want to fetch new data from the backend while still retaining your inputs

**Comment by matthiasdebaat** [comment]
That seems like an edge case to me. If not, we need to add it to the 'History' page as well

**Comment by spacegaier** [comment]
I think we should keep that button for the reasons ludeeus outlined. I also agree that we need to add a refresh button to the "History" panel.
