### ISSUE TITLE
Incorrect information about integration "Failed to setup"

### ISSUE THREAD

**Issue by mirceadamian** [home-assistant/frontend#9831]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This was partially covered (as a side issue) in ticket #54714 for the core since it seems that two messages which are related to the ZHA integration are causing the Config/Integration page to show wrong information.
Basically it is showing the HACS integration in a red with the message "Failed to setup" and the option to "Check logs"
![image](https://user-images.githubusercontent.com/60296639/129715542-89ee07ce-28ec-4fb1-9815-ae550740413e.png)

When I check the logs I see those two above mentioned messages related to the ZHA integration which are not relevant to HACS (which is in the first place it is working well and the setup is complete and OK).

```
2021-08-16 17:36:06 WARNING (MainThread) [zigpy.zcl] Unknown cluster 61185
2021-08-16 17:36:06 WARNING (MainThread) [zigpy.zcl] Unknown cluster 61185
```

### Describe the behavior you expected

I expect that the integration is not showing as a failed one.

### Steps to reproduce the issue

1. Go to Configuration
2. Click on Integration
3. You will see here the red rectangle which in my case is on the HACS integration (but I guess it is just because those two messages happen to be exactly after the HACS Setup task)

```
2021-08-16 17:36:05 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.HACS_REPO
2021-08-16 17:36:06 WARNING (MainThread) [zigpy.zcl] Unknown cluster 61185
2021-08-16 17:36:06 WARNING (MainThread) [zigpy.zcl] Unknown cluster 61185
```

### What version of Home Assistant Core has the issue?

2021.8.7

### In which browser are you experiencing the issue with?

 Google Chrome 92.0.4515.131 (Official Build) (64-bit) (cohort: Stable)

### Which operating system are you using to run this browser?

Windows 10

**Comment by ludeeus** [comment]
Issues about custom integrations should be reported to the author of that custom integration.
Bu since that is me, there is no need.

You get that message when using YAML, and have used HACS for a long time (before this change was made sometime last year).

Click the 3 dots on the HACS card and remove it, it should not be there when using YAML.
