### ISSUE TITLE
Web UI mistakenly reports missing /data/addons directory as "Invalid Add-on Repository"

### ISSUE THREAD

**Issue by timbrunson** [home-assistant/frontend#9835]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When the /data/addons directory goes away, the front-end generates the misleading error "Invalid Add-on Repository". A side effect of the problem is that Community Add-Ons are no longer displayed in the Supervisor > Add-On Store screen below the Official Add-Ons.

It's not clear why the directory went away; I did not explicitly delete it. The problem surfaced when I was trying to add an external repository (https://github.com/sebr/bhyve-home-assistant, in this case.)

Configuration is Raspberry Pi/HASS with data moved to SSD using datactl command.

### Describe the behavior you expected

I would expect an error indicating that /data/addons no longer exists, rather than an error saying I'm trying to add an invalid add-on. This error should be displayed when the add-on store is originally displayed by clicking on the Add-On tab in the Supervisor section, rather than when trying to add a repository.

### Steps to reproduce the issue

1. Delete the /data/addons directory.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.8.6

### What was the last working version of Home Assistant Core?

All tested (restoring snapshot from previous recent releases made no difference.)

### In which browser are you experiencing the issue with?

Safari V14.1.1

### Which operating system are you using to run this browser?

macOS V11.4

### Additional information

I don't know why the addons directory disappeared, but in the event it's relevant: I'm running the community version of the SSH/Web Terminal add-on, with root access enabled, (although I did not delete the directory.)

**Comment by ludeeus** [comment]
This is not something the frontend can do.
Please raise your issue in the Supervisor repo :+1:

**Comment by ludeeus** [comment]
Actually... looked at your link.
The message is correct, that is not a valid add-on repository.
It's not an add-on in there at all, there are a custom integration (custom_component) and a python script

**Comment by timbrunson** [comment]
OK, but HA (whether it’s the supervisor or front-end) still fails to report the missing directory correctly, and loses the Community Add-Ons in the process. Simply recreating the directory (cd /data; mkdir addons) brings back the Community Add-Ons.

Thanks for responding to the report.
