### ISSUE TITLE
In the bar graphs, the scale values overlap

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#9851]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![Bag1](https://user-images.githubusercontent.com/74879713/130132763-d5438210-3fb6-44d6-a7c2-1cbd6922cbe9.png)

### Describe the behavior you expected

The values should not overlap

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.8.7

### Which operating system are you using to run this browser?

Windows 10

**Comment by WRoss7** [comment]
Hi, any news here?

**Comment by WRoss7** [comment]
Hi, any news here?

**Comment by ildar170975** [comment]
The bug still present

**Comment by WRoss7** [comment]
This bug still persist

**Comment by WRoss7** [comment]
The bug is still persistent

**Comment by WRoss7** [comment]
In 2022.11.0 things got worse:
the bar graphs also appear with different lengths.

![Img1](https://user-images.githubusercontent.com/74879713/199752270-8c849053-f505-4310-9d0d-4155c1ead13a.png)

**Comment by karwosts** [comment]
Closing as duplicate of #9815
