### ISSUE TITLE
Bug in the history graph labels

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#9852]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![Bag2](https://user-images.githubusercontent.com/74879713/130134667-ea257847-3794-432c-b5bc-f8ce5fac545a.png)

Long labels not ellipsized

### Describe the behavior you expected

The text should not be truncated at the beginning of the sentence and be left aligned

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.8.7

**Comment by spacegaier** [comment]
I think we should render the beginning of the name and then add ellipsis plus a "title" tooltip for the full name (similar to #9264).

**Comment by WRoss7** [comment]
Hi Philip, that would be great
