### ISSUE TITLE
mediaplayer 'Playlist.Clear' in stead of 'Player.PlayPause'

### ISSUE THREAD

**Issue by Kouwe-sudo** [home-assistant/frontend#9857]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I use the media player card with a Kodi media player I can view the contents of the music library attached to Kodi. I can select an album and within an album a song. However when I then press "play" I get the following error message:

> jsonrpc_base.jsonrpc.ProtocolError: (-32602, 'Invalid params.', {'error': {'code': -32602, 'data': {'method': 'Playlist.Clear', 'stack': {'message': 'Invalid type object received', 'name': 'playlistid', 'type': 'integer'}}, 'message': 'Invalid params.'}, 'id': '2e880ae6-9e60-45a3-88d0-2d23c55fa8c5', 'jsonrpc': '2.0'})

### Describe the behavior you expected

I see that the method is 'Playlist.Clear' whereas I would expect something along the lines of 'Player.PlayPause'

I really just want to play a song or album through my amplifier and speakers. Or do I now want something that can't be done this way?

### Steps to reproduce the issue

1. Go to entities and select the kodi mediaplayer
2. Card pops up and select the icon in the upper right corner (settings?)
3. A new card pops up
4. Hit the library-button and
5. Kodi libraries popup.
6. choose Album
7. Choose a random album
8. In that album choose a random song
9. Hit play

### What version of Home Assistant Core has the issue?

core-2021.8.8

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue with?

Firefox and Chrome

### Which operating system are you using to run this browser?

Windows 10

**Comment by spacegaier** [comment]
I don't have Kodi, but it works fine for me with the Spotify library browser and I think they use the same default frontend browsing logic.

**Comment by Kouwe-sudo** [comment]
Perhaps that's the problem. It works differently for spotify. You only work with playlists there aren't you? I want to play a song from my own (kodi) library. A real .flac-file
