### ISSUE TITLE
Gauge card blue color missing with needle set

### ISSUE THREAD

**Issue by chheiss** [home-assistant/frontend#9858]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The new gauge card with needle has the blue color missing when severity is set. Previously, if severity was below green threshold, it showed blue. Now, it shows just white.

### Describe the behavior you expected

Blue color for severity below green threshold.

### Steps to reproduce the issue

1. Add gauge card with severity

### What version of Home Assistant Core has the issue?

core-2021-8-8

### In which browser are you experiencing the issue with?

Chrome, Firefox, Safari, Edge

### Which operating system are you using to run this browser?

Windows 10

**Comment by bramkragten** [comment]
Duplicate and fixed
