### ISSUE TITLE
Still HA refreshing fast on iOS 12.5.4 and Shelly history Voltage and Power not shown

### ISSUE THREAD

**Issue by apeiron69** [home-assistant/frontend#9861]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

As I update from HA 2021.5 to core 2021.8.8 and Supervisor 2021.06.8, i found HA lovelace unusable on iPad mini 2 because of continuous refreshing. Another issue is in the History card of the Shelly EM. When I add the card i see the two diagrams but when HA refreshes the diagrams both disappear. Same issue of HA found in Chrome, Edge and Firefox for iOS. In newer iPads, iPhones, Androids and Windows PCs the sistem works fine. 

### Describe the behavior you expected

Lovelace should function as normal without constant refreshing and history card of Shelly EM working as in other OS. Can I go back to previous version?

### Steps to reproduce the issue

1. Launch the HA app from iPad 
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.8.8

### What was the last working version of Home Assistant Core?

2021.5

### In which browser are you experiencing the issue with?

HA, Chrome, Fiefox and Edge for iOS

### Which operating system are you using to run this browser?

iOS 12.5.4

**Comment by bramkragten** [comment]
Create an issue for every individual issue.
The iOS 12 issue when using the App has been fixed (will be in the next release)
