### ISSUE TITLE
Helpers; input select options disappear

### ISSUE THREAD

**Issue by stovedoctor** [home-assistant/frontend#9872]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Only the active input select option shows after creating a set of options in helpers option select in configuration window of helpers.
Unable to use frontend automation tools or node red  to select in drop down list of helpers because only the active option is used.
Can manually set options with data in cal of service using node red and change options running the automation. 
Not all are doing this just the news one I have created. 

### Describe the behavior you expected

Show a drop down list of options in the helpers configuration.
Show drop down list of options in automation tools.

### Steps to reproduce the issue

1. Create a option select helper with several options 
2.save and close 
3.use node red or front end automation to use input select in a automation.
4. After some time go back to add another option or edit automations and noticed only the active option is showing.

...

### What version of Home Assistant Core has the issue?

2021.8.6

### In which browser are you experiencing the issue with?

Chrome and android HA app. 

### Which operating system are you using to run this browser?

Windows and Android HA app.

**Comment by stovedoctor** [comment]
never mind my screwup. it was because i used set_input in node red and it takes way the option drop down in the front end.

**Comment by spacegaier** [comment]
Seems to have cleared itself up :)
