### ISSUE TITLE
BH1750 illuminance sensor (ESPHome) is not available in statistics-graph card

### ISSUE THREAD

**Issue by paulius2k** [home-assistant/frontend#9882]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hello,

I have an BH1750 illuminance device attached to ESP8266 integrated via ESPHome.

The problem: this sensor is not available in the Statistics Graph Card (https://www.home-assistant.io/lovelace/statistics-graph/)

I checked the requirements: https://www.home-assistant.io/more-info/statistics/
and to me it seems that **the needed attributes of the sensor are created** as per requirements, i.e. this is what I see in the HA developer tools:
```
state_class: measurement
unit_of_measurement: lx
friendly_name: BH1750 Illuminance
device_class: illuminance
```
What else is needed for this sensor to become available in the Statistics Graph Card?

Thank you!

P.S.: I have also registered a ticket in the ESPHome github, with only 1 comment so far basically directing the problem back to HA:  https://github.com/esphome/issues/issues/2338

### Describe the behavior you expected

My illuminance sensor should be available for selection in the drop-down of the statistics-graph card.

### Steps to reproduce the issue

1. Goto Lovelace dashboard.
2. Three dots --> Edit dashboard
3. +Add card
4. Select Statistics Graph card.
5. Illuminance sensor is not available in the list of sensors.

### What version of Home Assistant Core has the issue?

core-2021.8.8

### In which browser are you experiencing the issue with?

Chrome 92.0.4515.159 (64-bit); Edge Version 92.0.902.78 (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
sensor.bh1750_illuminance
BH1750 Illuminance
24953.3	

state_class: measurement
unit_of_measurement: lx
friendly_name: BH1750 Illuminance
device_class: illuminance
```

### Problem-relevant frontend configuration

```yaml
--
```

### Javascript errors shown in your browser console/inspector

```txt
--
```

**Comment by apaperclip** [comment]
Maybe 2021.9 will address this https://rc.home-assistant.io/blog/2021/08/25/release-20219/#long-term-statistics-unlocked-for-all-sensors

**Comment by paulius2k** [comment]
@apaperclip - thank you for pointing this out!
Yes, now it works in 2021.9.2.
Closing this issue.
