### ISSUE TITLE
Hidden chart values reappear after data refresh

### ISSUE THREAD

**Issue by zaubererty** [home-assistant/frontend#9886]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have created a Chart with  [Sample initial Load](https://pasteboard.co/KhFPIz5.png)
Not all values are needed at all times so I hide them by clicking on them [Sample with hidden values](https://pasteboard.co/KhFJ5NZ.png)
When the chart refreshes data the values appear again. [Sample after refresh](https://pasteboard.co/KhFKND9.png)

### Describe the behavior you expected

The values should  stay hidden

### Steps to reproduce the issue

1. Create a chart in HA with multiple values
2. Hide one or more by clicking on the title
3. wait for the data refresh in my case 120 sec.

### What version of Home Assistant Core has the issue?

core-2021.8.8

### What was the last working version of Home Assistant Core?

core-2021.6.?

### In which browser are you experiencing the issue with?

Google Crome 

### Which operating system are you using to run this browser?

Windows 10 (20H2)

### Javascript errors shown in your browser console/inspector

no errors

**Comment by pgoddijn** [comment]
I have the same issue, but I wanted to add that this can be replicated with only one value/entity. It appears the more values/entities in a graph, the faster the error appears

OS: Windows 10 (21H1)
Browser: Google Chrome 92.0.4515.159 / Microsoft Edge 92.0.902.78

**Comment by bramkragten** [comment]
This is fixed in the current beta
