### ISSUE TITLE
History Graph "hide sensor" doesn't work anymore

### ISSUE THREAD

**Issue by mmiller7** [home-assistant/frontend#9902]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When viewing a history graph (such as temperature of several rooms), if you click on a sensor in the legend to hide it the line either does not hide or returns after a few seconds.

![image](https://user-images.githubusercontent.com/606945/131256394-4b22cdcb-e1a0-4a24-8dbf-075d653fe0cb.png)

### Describe the behavior you expected

I expect the corresponding line to stay hidden until I un-hide or reload the page.

### Steps to reproduce the issue

1. Make a history graph with temperature/humidity/voltage (anything that will plot a line value)
2. Hide one or more sensors by clicking on it in the graph legend
3. Wait a few seconds, the line will un-hide (if it ever hid to begin with)
...

### What version of Home Assistant Core has the issue?

core-2021.8.8

### In which browser are you experiencing the issue with?

Firefox (multiple versions Win/Linux), Chrome 92.0.4515.159, Android app

### Which operating system are you using to run this browser?

Linux Mint 20, Windows, Android

### Additional information

I believe this started around the same time as the graph colors changed.

**Comment by bramkragten** [comment]
This was fixed in the current beta
