### ISSUE TITLE
Inconsistent text justification in reloading screen of Android app

### ISSUE THREAD

**Issue by mikevansighem** [home-assistant/frontend#9910]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the reload screen the text for reloading groups is centred while all other options are aligned on the left. Observed on the android app only. After reporting the issue in the android app repo I was redirected to raise it here. [Original issue](https://github.com/home-assistant/android/issues/1692)

### Describe the behavior you expected

All text left-justified.

### Steps to reproduce the issue

No particular steps, always present.

### What version of Home Assistant Core has the issue?

2021.6.2

### Which operating system are you using to run this browser?

Android 10

### Additional information

Screenshot

![Screenshot_20210829-165939_Home Assistant](https://user-images.githubusercontent.com/36593824/131255154-ae0901c3-45c0-4f9d-a0fb-e198ab0c4618.jpg)

**Comment by spacegaier** [comment]
Happens based on the screen width, see this duplicate https://github.com/home-assistant/frontend/issues/7639. Those elements are technically buttons and they will auto-center their content. As long as there is only a single line of text, you cannot tell, but as soon as there are two lines (and hence the button uses the whole screen width) you can.

Will eventually get fixed once the the redesign gets tackled: https://github.com/home-assistant/frontend/pull/6730
