### ISSUE TITLE
Statistics-Graph showing a maximum of 28 (?) days, no matter the "days" setting.

### ISSUE THREAD

**Issue by theorician** [home-assistant/frontend#9916]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I might be doing something wrong here, so forgive me if this is either a known issue/design choice or me doing it wrong. (In particular, I suspect that this is a backwards-compatibility issue with collected sensor data so this might just need slightly improved docs. Posting as a bug anyway just in case.)

I set up a statistics graph for a temperature sensor I have. I've verified that the sensor has data going back over a year - on the History page I can select a long time-frame. However, the stats graph page only shows me 28 days (starting Aug 3rd to today), no matter if I select a higher number.

### Describe the behavior you expected

I expect statistics for the entire period that I've selected to show up.

### Steps to reproduce the issue

1. Have a sensor with a year's worth of data recorded
2. Create a statistics graph card, selecting e.g. 120 days as the time frame
3. Observe that 120 days are not displayed on the graph.

### What version of Home Assistant Core has the issue?

core-2021.8.8

### What was the last working version of Home Assistant Core?

N/A

### In which browser are you experiencing the issue with?

Firefox 91.0.1 (64-bit)

### Which operating system are you using to run this browser?

MacOS Catalina 10.15.7

### Additional information

I _assume_ that this is because statistics are kept separate from the actual data, and are being generated only for new data coming in from whatever point the statistics feature was implemented. However, https://www.home-assistant.io/lovelace/statistics-graph/ makes no mention of this.

If that is the case, then maybe updating the docs to state that stats are not backwards compatible might help.

**Comment by bramkragten** [comment]
You are correct, we only generate stats for the current hour. Feel free to update the docs with this.
