### ISSUE TITLE
Service call UI link to integration documentation is wrong for custom integrations

### ISSUE THREAD

**Issue by dgomes** [home-assistant/frontend#9919]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This can be summarised by https://github.com/HASwitchPlate/openHASP-custom-component/issues/70

The link assumes the integration is always core

### Describe the behavior you expected

Should read the link from manifest and not assume

### Steps to reproduce the issue

1. Install a custom_integration with service
2. go to the service page in Developer tools
3. Click on ?

### What version of Home Assistant Core has the issue?

core-2020.08

**Comment by spacegaier** [comment]
I can confirm the issue.

The manifest is not something that the frontend currently has access to. What the frontend knows is the content from `services.yaml`.

I think the backend and the JS websocket would need to be extended to pass the documentation URL from the backend to the frontend.
@bramkragten Is my understanding correct?

**Comment by bramkragten** [comment]
No, we can already fetch the manifest of the integrations, might be a bit expensive, something we have to look into.

**Comment by spacegaier** [comment]
@bramkragten Thanks for the hint. I found now where we already retrieve the manifest and will push a matching PR in a few seconds.

**Comment by dgomes** [comment]
Thank you @spacegaier !
