### ISSUE TITLE
Shortcut bar causes error when started and closed

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#9925]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

entering 'c' to get to the shortcut bar shows the shortcut bar alright, but also errors in the log, see below.
when the shortcut bar is removed/closed another error is displayed

this is happening in Safari Mac. When using Chrome, only the closing error is raised

### Describe the behavior you expected

no errors

### Steps to reproduce the issue

1. enter c to reveal shortcut bar
2. nothing further is needed
3. closing...
...

### What version of Home Assistant Core has the issue?

2021.9.0b6/7

### What was the last working version of Home Assistant Core?

not sure

### In which browser are you experiencing the issue with?

Safari  Mac, Chrome Mac

### Which operating system are you using to run this browser?

macOS Big sur 11.4

### Javascript errors shown in your browser console/inspector

opening error
```txt
2021-09-01 11:35:29 ERROR (MainThread) [frontend.js.latest.202108300] :0:0 Script error.
```

and upon closing:

```
2021-09-01 11:37:36 ERROR (MainThread) [frontend.js.latest.202108300] https://mydomain:port/frontend_latest/a4f644cd.js:172:56140 TypeError: undefined is not an object (evaluating 'e.target.items[t].item')
```

### Additional information

as per request in. https://discord.com/channels/330944238910963714/427516175237382144/882595152798023690

**Comment by rccoleman** [comment]
I can reproduce this in Chrome (the closing error), and I get the following in the browser console:

```
Uncaught TypeError: Cannot read property 'item' of undefined
    at HTMLElement.value (a4f644cd.js:2160)
    at j.handleEvent (app.f08a72d3.js:5264)
    at Object.notifySelected (02f7d316.js:1359)
    at G.setSingleSelectionAtIndex_ (02f7d316.js:238)
    at G.setSelectedIndex (02f7d316.js:238)
    at HTMLElement.select (02f7d316.js:1359)
    at HTMLElement.updateItems (02f7d316.js:238)
    at HTMLElement.layout (02f7d316.js:1359)
    at 02f7d316.js:238
value @ a4f644cd.js:2160
handleEvent @ app.f08a72d3.js:5264
notifySelected @ 02f7d316.js:1359
setSingleSelectionAtIndex_ @ 02f7d316.js:238
setSelectedIndex @ 02f7d316.js:238
select @ 02f7d316.js:1359
updateItems @ 02f7d316.js:238
layout @ 02f7d316.js:1359
(anonymous) @ 02f7d316.js:238
setTimeout (async)
(anonymous) @ 02f7d316.js:238
J.debouncedLayout @ 02f7d316.js:238
disconnectedCallback @ 02f7d316.js:238
_$AR @ app.f08a72d3.js:5264
A @ app.f08a72d3.js:5264
T @ app.f08a72d3.js:5264
_$AI @ app.f08a72d3.js:5264
O @ app.f08a72d3.js:5264
update @ app.f08a72d3.js:5264
performUpdate @ app.f08a72d3.js:1
_$EC @ app.f08a72d3.js:1
async function (async)
_$EC @ app.f08a72d3.js:1
requestUpdate @ app.f08a72d3.js:1
set @ app.f08a72d3.js:1
value @ a4f644cd.js:1069
value @ a4f644cd.js:2160
async function (async)
value @ a4f644cd.js:2160
value @ a4f644cd.js:2160
handleEvent @ app.f08a72d3.js:5264
notifySelected @ 02f7d316.js:1359
setSingleSelectionAtIndex_ @ 02f7d316.js:238
setSelectedIndexOnAction_ @ 02f7d316.js:238
handleSingleSelection @ 02f7d316.js:238
onRequestSelected @ 02f7d316.js:1359
handleEvent @ app.f08a72d3.js:5264
fireRequestSelected @ 02f7d316.js:238
onClick @ 02f7d316.js:238
cb @ 02f7d316.js:1
```

**Comment by VDRainer** [comment]
Firefox 91.0.2 on Ubuntu
opening
```
2021-09-02 19:46:45 ERROR (MainThread) [frontend.js.latest.202108300] :0:0 ResizeObserver loop completed with undelivered notifications.
```
closing
```
2021-09-02 19:46:54 ERROR (MainThread) [frontend.js.latest.202108300] http://192.168.77.67:8123/frontend_latest/a4f644cd.js:172:233 TypeError: e.target.items[t] is undefined
```
