### ISSUE TITLE
occasional dip in total energy causes mayhem in Energy panel

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#9929]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

every now and then, sensors do this, and cause the energy panel graphs to see the full total usage as daily usage

### Describe the behavior you expected

filter these small dips

### Steps to reproduce the issue

1. nothing, just happening every now and then
2.
3.
...

 

### What version of Home Assistant Core has the issue?

2021.9

### What was the last working version of Home Assistant Core?

never

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

macOS Big sur 11.4

### Additional information

<img width="1387" alt="Schermafbeelding 2021-09-01 om 23 42 37" src="https://user-images.githubusercontent.com/33354141/131749500-d5ee9d5a-c63f-4a27-9eb6-e5e6c999bf23.png">

**Comment by bramkragten** [comment]
The integration should filter this out if they claim to be only increasing.

**Comment by Mariusthvdb** [comment]
this is an mqtt sensor, so simply fed by a topic that can have its ups and downs apparently

**Comment by bramkragten** [comment]
If the state class is `total_increasing` it should not drop. If it will/can drop it should not have `total_increasing`.

**Comment by Mariusthvdb** [comment]
that's just the thing is it, it _should not_ drop, but hardware interference sometimes causes these communication issues, maybe RF, or what have you in the house going on. The sensor is a `total_increasing` for sure, but this glitch is something the HA system should be able to handle. Having said that, I guess it's a backend core issue, not a frontend, so I will move it. thanks for the link.
