### ISSUE TITLE
Error loading the view strategy: [object Object]

### ISSUE THREAD

**Issue by NuijtenDev** [home-assistant/frontend#9932]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Loading the lovelace/0 dashboard i get a error loading in the view. 

![image](https://user-images.githubusercontent.com/23700539/131802111-0e5ab73a-f6f0-4d9d-93fe-c4a055b1f47d.png)

### Describe the behavior you expected

loading in the lovelace view 

### Steps to reproduce the issue

1. starting the docker container
2. open overview

### What version of Home Assistant Core has the issue?

core-2021.9.0.dev20210815

### In which browser are you experiencing the issue with?

Firefox, Chrome

### Which operating system are you using to run this browser?

Windows 10  19042.1110

### Javascript errors shown in your browser console/inspector

```txt
Uncaught (in promise) 
Object { code: "not_found", message: "No prefs" }
core.9523fe48.js:1


Object { code: "not_found", message: "No prefs" }
6309d84d.js:262

Error: Promised response from onMessage listener went out of scope
```

**Comment by ludeeus** [comment]
This is an old dev build, this issue has already been fixed, if you run dev please stay up to date with it :+1:
