### ISSUE TITLE
Camera streaming continues even when stream window is closed.

### ISSUE THREAD

**Issue by Plazmin** [home-assistant/frontend#9943]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing
 look in [Generic camera streaming continues even when stopped](https://github.com/home-assistant/frontend/issues/8630)

### Describe the behavior you expected

look in [Generic camera streaming continues even when stopped](https://github.com/home-assistant/frontend/issues/8630)

### Steps to reproduce the issue

1. look in [Generic camera streaming continues even when stopped](https://github.com/home-assistant/frontend/issues/8630)
2.
3. 
...

### What version of Home Assistant Core has the issue?

 core-2021.9.1

### In which browser are you experiencing the issue with?

firefox 78.13.0esr, firefox 91.0.2, 

### Which operating system are you using to run this browser?

debian buster, windows 10

### Additional information

The problem described in a closed issue [Generic camera streaming continues even when stopped](https://github.com/home-assistant/frontend/issues/8630) still exists, despite **bramkragten** information "This should be fixed in the current beta" and Home Assistant [release notes](https://www.home-assistant.io/blog/2021/09/01/release-20219): 
"Thanks to @bdraco, camera images can now be scaled to a resolution that fits the device/screen you are looking at; Additionally, they only update when visible. This makes cameras usable in any bandwidth situation."

**Comment by bramkragten** [comment]
Please create an issue by filling out the template and giving it a descriptive title.
Also please supply info about the stream, is it an MPJEG stream, or an HLS stream?
Thank you.

**Comment by Plazmin** [comment]
Cameras configured through onvif integration. As far as I know it is rtsp stream. Closing the browser does not help, the rtsp connection exists between the camera and Home assistant server. Only HA reloading helps.

**Comment by bramkragten** [comment]
If it is about the connection between Home Assistant server and the camera, then this is an issue for the core repo. If it is about the connection between your browser and the Home Assistant server, then this is the place for that.
