### ISSUE TITLE
Error when Displaying Grid or Stack cards

### ISSUE THREAD

**Issue by TheMrPhantom** [home-assistant/frontend#9950]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When i create gridcards, horizontal or vertical stacks a red error box is displayed with message:
`this.toggleAttribute is not a function. (In 'this.toggleAtttribute("square",this.square)', 'this.toggleAttribute' is undefined)`

### Describe the behavior you expected

Cards are Displayed without arror

### Steps to reproduce the issue

1. Create Card inside gridcard, horizontal or vertial stack
2. Dashboard is showing red box with error message

### What version of Home Assistant Core has the issue?

2021.9.1

### In which browser are you experiencing the issue with?

Edge, Safari, Kiosk Browser App

### Which operating system are you using to run this browser?

iOS 9.x

**Comment by spacegaier** [comment]
I tried to reproduce the issue in 2021.9.0 and latest dev on Win 10 + FF and Chrome, but cannot do so.

Does the issue only appear on iOS for you?

**Comment by TheMrPhantom** [comment]
Yes, on Win10 it works fine for me as well. But on my phone with older ios version it does produce this error. I am running ios9.

**Comment by bramkragten** [comment]
`toggleAtttribute` doesn't seem to have too much support... https://caniuse.com/?search=toggleAttribute
