### ISSUE TITLE
OpenWeatherMap Statistics

### ISSUE THREAD

**Issue by wormuths** [home-assistant/frontend#9951]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Please enable the "statistics" feature for the OpenWeatherMap integration.  This is valuable data for long term analysis of weather and home energy usage.

### Describe the behavior you expected

Ability to view weather statistics over long-term periods.

### Steps to reproduce the issue

No statistics available in drop-down of the statistics card.
...

### What version of Home Assistant Core has the issue?

2021.9.2

### In which browser are you experiencing the issue with?

ALL

### Which operating system are you using to run this browser?

Home Assistant OS

### Additional information

I am not positive this is the appropriate place to create an issue for the integration.  Sorry if it is not.

**Comment by bramkragten** [comment]
This is not a frontend issue. Create an issue in the core repo for the specific integration.
