### ISSUE TITLE
Icon color changed between 2021.8 and 2021.09.0/1/2

### ISSUE THREAD

**Issue by tnaumann71** [home-assistant/frontend#9957]
### The problem

I recognized a change in the color in some of the light icons between 2021.08.x and all 2021.09.x Releases.

please See the Screenshots. The Lights (Essen, Küche, Wohnen) connected via Zigbee via Conbee II are affected. These lights are only CW/WW no RGB. So the red/orange Color in the Display is Not configurable. Lights connected to Bosch cloud (Licht Abzug & Abzug Ambi) are not affected.
I updated to 2021.9.0 and went back to 2021.8.8. The same with .1 and .2. I changed nothing else.

![0F875E12-358E-424D-846C-D46ECA847790](https://user-images.githubusercontent.com/72469985/132093292-ac953475-f9d9-4c83-8148-9abc8e86f553.png)
![09AC8841-4036-4A1F-8133-9EF83D768556](https://user-images.githubusercontent.com/72469985/132093295-a0f8314b-d360-4a11-964e-460b9bbedde9.png)

### What is version of Home Assistant Core has the issue?

2021.9.2

### What was the last working version of Home Assistant Core?

2021.8.8

### What type of installation are you running?

Home Assistant OS

### Additional information

Hass OS 6.2
Supervisor 2021.08.01
DeCONZ 6.10.0 / Phoscon 2.12.06
Conbee II Firmware 26720700

Hass OS as VM in proxmox 7.0 on Intel NUC

**Comment by spacegaier** [comment]
Please post the state YAML from the HA dev tools for one of the affected lights.

**Comment by bramkragten** [comment]
This is not a bug but a feature, color temperature is shown too now. This is not a frontend change btw, but a core change.

**Comment by tnaumann71** [comment]
Ok if it is a feature then it is uncomfortable implemented because the color representation of COLD is a nearly WHITE buld and can't be seen.

Here the state of "Küche" when ON an WARM:

'
min_mireds: 140
max_mireds: 650
supported_color_modes:
  - color_temp
color_mode: color_temp
brightness: 254
color_temp: 495
hs_color:
  - 30.512
  - 93.472
rgb_color:
  - 255
  - 137
  - 16
xy_color:
  - 0.597
  - 0.383
is_deconz_group: false
friendly_name: Küche
supported_features: 40
'

Here the state of "Küche" when ON an COLD:
'
min_mireds: 140
max_mireds: 650
supported_color_modes:
  - color_temp
color_mode: color_temp
brightness: 254
color_temp: 158
hs_color:
  - 37.231
  - 3.66
rgb_color:
  - 255
  - 251
  - 245
xy_color:
  - 0.331
  - 0.335
is_deconz_group: false
friendly_name: Küche
supported_features: 40
'

Please find attached a screenshot of the COLD buld in the HA dashboard.

![Bildschirmfoto 2021-09-05 um 18 32 00](https://user-images.githubusercontent.com/72469985/132134320-05b04945-f092-4a19-ad70-98c4a4fe8deb.png)

**Comment by jerodjchastain** [comment]
Is there an answer to this yet, when my rgb lights are set to white and on I can not seem them on the default theme. Is there a way to stop the RGB lights from "trying to show their color or temp color"?

**Comment by tnaumann71** [comment]
No no answer and no solution. This behaviour is intended.

**Comment by bramkragten** [comment]
This is not something the frontend does, so please create an issue on the backend.
