### ISSUE TITLE
Weird graph scale on different client time

### ISSUE THREAD

**Issue by bigboban** [home-assistant/frontend#9970]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have HA and i name it "SERVER" here. Server is on some place in some time zone and has some right set time. I think 99% of HA users has "local" measures, so "kitchen temp" or "garage door" is something **on server place**.

And HA records reality into DB (recorder) with **server** timestamp.

Example: 

HA server has "now" time 6. september 2021, 14:00 CET.

User's PC has broken unsynced time for example 6. september 2021 8:00 CET.

And all graphs end not at 14:00 but at 8:00! = BUG. Someone steal me 6 hours of reality! 6 hours missing somewhere. 

Tested on Chrome and Edge (chromium edge).

### Describe the behavior you expected

**I think client time cannot affect server times because only server time is correct and event occurred on server place on server time in server time zone.**

So i think right behavior is to show SERVER times on graph.

### Steps to reproduce the issue

1. Go to pc time settings, set time few hours back.
2. Show HA lovelace with some graphs and (hard?) refresh fe.
3.
...

### What version of Home Assistant Core has the issue?

2021.9.3

**Comment by bramkragten** [comment]
It shows the time it has happened, in the timezone of the user. That seems correct to me.

**Comment by bigboban** [comment]
I think you don't understand. I don't say labels on X axis are not right. I say whole graph is broken, because **X hours of graph **values** are missing**. 

And second note. **I think client should use time zone only** not client exact time. 

Now lovelace "miss" hour of values for every client with incorrect time in client pc?

And last note - it is only my opinion but for me is right option to show all times in server manner. As i said - reality has happened on server place so i think preferred way of time show is server zone/time.

**Comment by to-rhis** [comment]
Exactly ! "As i said - reality has happened on server place so i think preferred way of time show is server zone/time."
I was setting up an light to start on an certain time from Firefox. It started the light 2 hours early  "2 o,clock instead of 4 o,clock" because of this "little annoyance thinking" , you understand how I wonder why the lights goes on at 02:00 in the morning.. Double checked times again, but it showed start time at 4:00 in Firefox. 
Well the rest you know about nowadays, more about this fix in other bug reports.
