### ISSUE TITLE
Cards with percentages and temperatures not showing up

### ISSUE THREAD

**Issue by TheMrPhantom** [home-assistant/frontend#9972]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Entities that are percentages or temperatures are not shown in dashboards.
If it is an Entity card only the percentage or temperature entity is not shown but the other are. If it is a gauge for example the whole card is not displayed at all.

### Describe the behavior you expected

Entities and gauges are displayed

### Steps to reproduce the issue

1. Create Entity-Card with percentage or temperature entity or gauge-card
2. Look at Dashboard

### What version of Home Assistant Core has the issue?

2021.9.1

### In which browser are you experiencing the issue with?

Edge, Safari, Kiosk Browser App

### Which operating system are you using to run this browser?

iOS 9

**Comment by spacegaier** [comment]
Does this only apply to iOS 9? because for me on Win 10 I can of course use an Entity card to show a temperature sensor.
![image](https://user-images.githubusercontent.com/114137/132248794-57ae987f-daf2-4272-a502-42e67cf63f48.png)

**Comment by TheMrPhantom** [comment]
yes i does work on windows 10 for me as well

**Comment by TheMrPhantom** [comment]
It appears to be fixed in version core-2021.11.1
