### ISSUE TITLE
 energy-date-selection card always set to narrow

### ISSUE THREAD

**Issue by oziee** [home-assistant/frontend#9979]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

the type: energy-date-selection always has the attribute Narrow. This sets the component to two rows and never one row no matter that width of the screen is.

I have the card inside a horizontal stack and seem that the offset width is always nothing.

### Describe the behavior you expected

should work like in the energy panel where the component resizes depending on the width of the screen

### Steps to reproduce the issue

add a horizontal stack
add type: energy-date-selection to the horizontal stack
resize the window

### What version of Home Assistant Core has the issue?

2019.9.2

### In which browser are you experiencing the issue with?

safari, chrome

### Which operating system are you using to run this browser?

Mac, samsung a7 tablet

### State of relevant entities

```txt
-
```

### Problem-relevant frontend configuration

```yaml
type: custom:stack-in-card
mode: horizontal
cards:
  - type: energy-date-selection
```

### Javascript errors shown in your browser console/inspector

```txt
nil
```

### Additional information

<img width="1117" alt="Screen Shot 2021-09-07 at 12 40 24 pm" src="https://user-images.githubusercontent.com/1471841/132275925-30845884-d8d8-4404-b729-4f4f7170da86.png">
<img width="353" alt="Screen Shot 2021-09-07 at 12 28 59 pm" src="https://user-images.githubusercontent.com/1471841/132275931-864a5c73-ba12-482c-b9f2-3028cef2a3b3.png">

**Comment by spacegaier** [comment]
In your example config you have a custom element. Does the issue also occur with vanilla elements / stacks?

**Comment by oziee** [comment]
yes it does the same thing in any container

**Comment by robertalexa** [comment]
Are there any plans to make this pickable? e.g. whether it is narrow or not?

**Comment by robertalexa** [comment]
@spacegaier Is this something that will be looked at by any chance? Thanks in advance
