### ISSUE TITLE
aspect ratio in picture-elements not working as expected

### ISSUE THREAD

**Issue by kobi111** [home-assistant/frontend#9986]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

my old version was 2021.8 and after upgrading to 2021.9 
the aspect ratio Instead of adjusting the image, cuts the picture up and down
i searched the forum and i saw some posts about this bug

this is the starting code:

type: picture-elements
image: local/home2.png
aspect_ratio: 16x8

### Describe the behavior you expected

the full picture need to be scaled to 16x8 and not be cut

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.9.4

### What was the last working version of Home Assistant Core?

core-2021.8.2

### Which operating system are you using to run this browser?

win 10 20H2 & xiaomi 4 android 7 phone

**Comment by DravenSA** [comment]
Right there with you, Aspect ratio Crops image and Video instead of Constraint

**Comment by drinfernoo** [comment]
Can confirm, same thing happens to me.

**Comment by DravenSA** [comment]
Not just on Picture Elements, but on Picture Entity and Picture Glance

**Comment by DravenSA** [comment]
This problem still exists i am running
Core
Version
core-2021.11.5

Supervisor
Version
supervisor-2021.10.8

Operating System
Home Assistant OS 6.6

**Comment by DravenSA** [comment]
This problem still exists i am running
Core
Version
core-2021.12.3

Supervisor
Version
supervisor-2021.12.2

Operating System
Home Assistant OS 7.0
