### ISSUE TITLE
Floorplan images keep reloading every 4-5 seconds making UI totally unusable

### ISSUE THREAD

**Issue by marcor78** [home-assistant/frontend#9989]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I use a floorplan based on picture-elements with conditional images based on specific conditions (lights on/off, doors open/close and so on).
Since a few days (probably after 2021.09 versions) all the images from the floorplan keep reloading continuously, therefore UI is totally unusable. 
I have other views with picture-elements that don't present this issue, nor this issue is present in the settings panel or other tabs.

### Describe the behavior you expected

images shouldn't reload by themselves every 5 seconds

### Steps to reproduce the issue

1. Simply starting UI and the issue is there
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.9.4

### In which browser are you experiencing the issue with?

Google Chrome 93.0.4577.63
Firefox 91.0.2

### Which operating system are you using to run this browser?
Windows 10
MacOS 11 (Big Sur)
Android Phone

**Comment by marcor78** [comment]
here's a demo video of the issue...
[https://drive.google.com/file/d/18McYPhS8l96U5nZLxEMw-PUSXBQVxSof/view?usp=sharing](url)

**Comment by spacegaier** [comment]
In order to find a reproducible example: Does the issue happen for you if you just add the default `picture-element` to your dashboard? Because for me, it works fine with that. No reloads are issues with loading the badge on it.

**Comment by marcor78** [comment]
> 
> 
> In order to find a reproducible example: Does the issue happen for you if you just add the default `picture-element` to your dashboard? Because for me, it works fine with that. No reloads are issues with loading the badge on it.

I'm not sure about what you mean, but I have a view with a picture-element of a 2D floorplan that doesn't refresh and behave normally (you can see it in the video I published, at the minute 1:30). The main view with the 3D floorplan - which by the way contains a lot more images in it - refreshes continuously

**Comment by holdestmade** [comment]
Is this related to my issue ?
#9988

**Comment by marcor78** [comment]
> 
> 
> Is this related to my issue ?
> #9988

I can't tell. It seems your issue is just about slow render, but then they finally render and stay there. Instead my images keep refreshing themselves forever

**Comment by holdestmade** [comment]
Yes probably not now I look closer, see this closed issue, seems to be similar to yours ?:

#9968

**Comment by marcor78** [comment]
> 
> 
> Yes probably not now I look closer, see this closed issue, seems to be similar to yours ?:
> 
> #9968

yes, I guess this is the same issue.
By the way, as I've said before and shown in the video, I have other views with picture-element (without config-template-card) and they perform flawlessly. The issue in my case must be definitely related to the combination of picture-element and config-template-card together. It must be something new introduced from the version 2021.9x

**Comment by spacegaier** [comment]
> 
> The issue in my case must be definitely related to the combination of picture-element and config-template-card together.

Then same answer as in #9968 => raise the issue with the author of the custom card, since that is then the culprit and there is nothing we can do in HA frontend.

**Comment by bkr1969** [comment]
Adding my comments here as well to keep track.  4-5 seconds would be great (not really) compared to every second or less when my Roomba is running.  I can barely even click the edit button before the screen reloads.  Definitely seems to be an issue with config-template-card.
