### ISSUE TITLE
Template Select object in the front end retuns the error when state changes, but works if service select.select_option is used instead of the front end element to change it's state

### ISSUE THREAD

**Issue by gribouk** [home-assistant/frontend#9996]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Recently new entity Template Select was introduced. To use it in the front end standard element, identical to input_select, is offered. On attempt of state change it returns an error:  "Не удалось вызвать службу select/select_option. must contain at least one of entity_id, device_id, area_id." and does not do anything. But when service: select.select_option is used, it changes state no problem - thus it is an front end element issue.
![error_msg](https://user-images.githubusercontent.com/72703085/132607684-052156d6-f530-4aec-b668-ed5deac7b35f.jpg)

### Describe the behavior you expected

When new option selected, everything should work

### Steps to reproduce the issue

1. Create an entity of Template Select type
2. Make an entities card and add your template select card to it
3. Try to chose new option
4. Enjoy!
...

### What version of Home Assistant Core has the issue?

2021.9.5

### In which browser are you experiencing the issue with?

Google Chrome, Edge

### Which operating system are you using to run this browser?

Win10 buid 21322

**Comment by andrey-yantsen** [comment]
Same problem here: it doesn't work for me on MQTT-based selects, but does work for the helpers (Input Select). Just in case, the English version of the error message is the following:
```
Failed to call service select/select_option. must contain at least one of entity_id, device_id, area_id.
```

Interesting that it's translated only halfway :)

**Comment by gribouk** [comment]
> Started to work for me on HA 2021.10.4. @gribouk what about your case?

Just updated to 2021.10.4 and tried to change options with standard front end object - same issue af before, nothing has changed for me so far.

**Comment by vlycop** [comment]
i am having that same issue with wled integration select.
none of the colors pallets, preset, or live override work.
those are my only select not being input_select so i am wondering if it's not ALL select that are broken ?
![Screenshot from 2021-12-27 15-59-30](https://user-images.githubusercontent.com/17001679/147483909-bbbf4ce7-5d0f-452f-9a1c-574c2e574000.png)

**Comment by gribouk** [comment]
> i am having that same issue with wled integration select. none of the colors pallets, preset, or live override work. those are my only select not being input_select so i am wondering if it's not ALL select that are broken ? ![Screenshot from 2021-12-27 15-59-30](https://user-images.githubusercontent.com/17001679/147483909-bbbf4ce7-5d0f-452f-9a1c-574c2e574000.png)

That's wired, just with the update to 2021.12 standard front end elements finally started to work for me and I was about to close this issue... Though I am not using these anyways since I've developed my own front end elements to display selects which is nicer...
