### ISSUE TITLE
Error in logs when selecting from the Quick Bar

### ISSUE THREAD

**Issue by cdonovan** [home-assistant/frontend#9999]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When selecting an item via the Quick Bar (accessed via the "e" keyboard shortcut), an error appears in the logs:
```
a4f644cd.js:2160 Uncaught TypeError: Cannot read properties of undefined (reading 'item')
    at HTMLElement.value (a4f644cd.js:2160)
    at j.handleEvent (app.f08a72d3.js:5264)
    at Object.notifySelected (02f7d316.js:1359)
    at G.setSingleSelectionAtIndex_ (02f7d316.js:238)
    at G.setSelectedIndex (02f7d316.js:238)
    at HTMLElement.select (02f7d316.js:1359)
    at HTMLElement.updateItems (02f7d316.js:238)
    at HTMLElement.layout (02f7d316.js:1359)
    at 02f7d316.js:238
```
It appears the error is thrown in the following handler:
https://github.com/home-assistant/frontend/blob/aba96674f3e8013223c7f31288f8a9eddb139caa/src/dialogs/quick-bar/ha-quick-bar.ts#L300-L308

### Describe the behavior you expected

No error to be thrown.

### Steps to reproduce the issue

1. Open the Quick Bar ("e" keyboard shortcut)
2. Select an item from the list
3. Observe the error in dev tools (and also the HA logs afterwards)

### What version of Home Assistant Core has the issue?

core-2021.9.5

### In which browser are you experiencing the issue with?

Google Chrome 93.0.4577.63, Firefox 92.0

### Which operating system are you using to run this browser?

macOS Big Sur 11.5.2

### Javascript errors shown in your browser console/inspector

```txt
app.f08a72d3.js:5264 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.
55704 @ app.f08a72d3.js:5264
s @ app.f08a72d3.js:30632
53918 @ app.f08a72d3.js:1290
s @ app.f08a72d3.js:30632
(anonymous) @ app.f08a72d3.js:30632
(anonymous) @ app.f08a72d3.js:36741
(anonymous) @ app.f08a72d3.js:36741
button-card.js:425   BUTTON-CARD   Version 3.4.2 
a4f644cd.js:2160 Uncaught TypeError: Cannot read properties of undefined (reading 'item')
    at HTMLElement.value (a4f644cd.js:2160)
    at j.handleEvent (app.f08a72d3.js:5264)
    at Object.notifySelected (02f7d316.js:1359)
    at G.setSingleSelectionAtIndex_ (02f7d316.js:238)
    at G.setSelectedIndex (02f7d316.js:238)
    at HTMLElement.select (02f7d316.js:1359)
    at HTMLElement.updateItems (02f7d316.js:238)
    at HTMLElement.layout (02f7d316.js:1359)
    at 02f7d316.js:238
value @ a4f644cd.js:2160
handleEvent @ app.f08a72d3.js:5264
notifySelected @ 02f7d316.js:1359
setSingleSelectionAtIndex_ @ 02f7d316.js:238
setSelectedIndex @ 02f7d316.js:238
select @ 02f7d316.js:1359
updateItems @ 02f7d316.js:238
layout @ 02f7d316.js:1359
(anonymous) @ 02f7d316.js:238
setTimeout (async)
(anonymous) @ 02f7d316.js:238
J.debouncedLayout @ 02f7d316.js:238
disconnectedCallback @ 02f7d316.js:238
_$AR @ app.f08a72d3.js:5264
A @ app.f08a72d3.js:5264
T @ app.f08a72d3.js:5264
_$AI @ app.f08a72d3.js:5264
O @ app.f08a72d3.js:5264
update @ app.f08a72d3.js:5264
performUpdate @ app.f08a72d3.js:1
_$EC @ app.f08a72d3.js:1
async function (async)
_$EC @ app.f08a72d3.js:1
requestUpdate @ app.f08a72d3.js:1
set @ app.f08a72d3.js:1
value @ a4f644cd.js:1069
value @ a4f644cd.js:2160
async function (async)
value @ a4f644cd.js:2160
value @ a4f644cd.js:2160
handleEvent @ app.f08a72d3.js:5264
notifySelected @ 02f7d316.js:1359
setSingleSelectionAtIndex_ @ 02f7d316.js:238
setSelectedIndexOnAction_ @ 02f7d316.js:238
handleSingleSelection @ 02f7d316.js:238
onRequestSelected @ 02f7d316.js:1359
handleEvent @ app.f08a72d3.js:5264
fireRequestSelected @ 02f7d316.js:238
onClick @ 02f7d316.js:238
cb @ 02f7d316.js:1
```

**Comment by Akhil132-dev** [comment]
hey i would like to work on this issue would please guide me how can i setup project to local machine and can run project

**Comment by spacegaier** [comment]
I already fixed that in dev a couple of days ago:  https://github.com/home-assistant/frontend/pull/9964

@Akhil132-dev https://developers.home-assistant.io/docs/frontend/development

**Comment by cdonovan** [comment]
Thanks @spacegaier!  When I searched for this problem initially, I think I was only looking at *open* issues, not closed/merged. Appreciate the quick response!
